### ISSUE TITLE
Elwynn Quest "Gnoll Bounty" Unable to Turn In

### ISSUE THREAD

**Issue by Zhohan** [slowtorta/turtlewow-bug-tracker#1]
**Current behavior**: 
The Turtle WoW quest from Elwynn Forest "Gnoll Bounty" cannot be turned in despite reaching the objective goal and the quest is labeled as complete. In addition to that, it says, "Riverpaw Runt slain: 15/10 (Complete)".
**Expected behavior**: 
The quest can be turned in and the mob slain counter cap at 10/10.
**Proofs**:
In attached image.
![GnollBountyBug](https://user-images.githubusercontent.com/22847755/105567865-d6304880-5cfa-11eb-99fb-08a41946a1c1.PNG)
**Steps to reproduce**:

1. Accept "Gnoll Bounty"
2. Kill gnolls in northern Elwynn Forest and kill an adequate number of gnolls until the quest is labeled as complete in the quest log.
3. Return to Supervisor Raelen and the question mark is greyed out and unable to turn in.

**Comment by Zhohan** [comment]
UPDATE:
After relogging, the quest log stated the quest was not complete.
Riverpaw Runt slain: 7/10
Riverpaw Outrunner slain: 10/10 (Complete)
I then killed 3 more Runt NPCs and then turned in the quest. I was able to complete it.

**Comment by slowtorta** [comment]
Thank you for reporting it. I can not reproduce this bug tho. Please clear your in-game cache (delete WDB folder all together) at least once a month. It will help to avoid minor glitches like this one.

**Comment by WarpQ** [comment]
I ran into this bug a couple of days ago. If I'm not mistaken, the "Riverpaw Runt slain" counter is somehow linked to the counter of the Elwynn Pumpkins that you have to collect 15 of for the Pumpkin Thieves quest. Collecting an Elwynn Pumpkin will simultaneously increase the "Riverpaw Runt slain" counter.
