### ISSUE TITLE
Winterspring Rune Teleportation not Triggering?

### ISSUE THREAD

**Issue by perl1743** [slowtorta/turtlewow-bug-tracker#10]
By opening this Issue, I admit to having done the pertinent research using sources from Vanilla (preferably) or Classic. I also understand that sources from other private servers are not acceptable.

**Current behavior**: 
Winterspring ground runes do nothing when walked over.
**Expected behavior**: 
Walking over them should trigger a teleport between the two.
**Proofs**:
Rune is located near https://database.turtle-wow.org/?npc=10929
![WoW_2021-06-02_11-22-41](https://user-images.githubusercontent.com/2818608/120516359-e1743e80-c394-11eb-9c54-d71641c87bdf.png)

**Comment by slowtorta** [comment]
Thanks.
