### ISSUE TITLE
Verog the Dervish not spawning for quest

### ISSUE THREAD

**Issue by MlFoushee** [slowtorta/turtlewow-bug-tracker#100]
**Please, provide a clear description what the bug is:**
Verog the Dervish does not spawn for the quest to kill him and take his head.

**Steps to reproduce the behavior with as much detail as possible:**

1.
2. 
3. 

**IDs of affected creatures, items, quests or spells with a link to the relevant page:**

NPC: https://database.turtle-wow.org/?npc=3395
Item: https://database.turtle-wow.org/?item=5023
Quest: https://database.turtle-wow.org/?quest=851
Spell: https://database.turtle-wow.org/?spell=
Object: https://database.turtle-wow.org/?object=

**Expected behavior. Describe how it should work:**
Verog should appear after you kill a few centaurs near his command tent.

**Comment by adrenalize74** [comment]
I dont think this is fixed.  I have killed over 80 Kolkar in the area, every one of them in the 4 separate areas around the hill.  Never spawns.
