### ISSUE TITLE
Database is not showing drop percentages

### ISSUE THREAD

**Issue by Zeebler** [slowtorta/turtlewow-bug-tracker#1002]
**Please, provide a clear description what the bug is:**

The Turtle Wow Database is no longer showing drop percentages as it did before.

**Steps to reproduce the behavior with as much detail as possible:**

1. Go to drops tab for npc on https://database.turtle-wow.org/?npc=639
2. Verify it does not show drop %

**Comment by Khanz0** [comment]
True. Yesterday saw this

**Comment by zomgits** [comment]
The decision to remove the drop rates was deliberate, according to Tinyfin.  But I do think it would be good to show *something*, so you can distinguish 50% from 0.05%.

**Comment by Zeebler** [comment]
Would they be misleading due to inaccurate data or something else?

**Comment by LeopoldHock** [comment]
I'm closing this since it's not a bug. Please make a suggestion thread on the forum.
