### ISSUE TITLE
Warrior Two-Handed Maces not on the Weapon Master List

### ISSUE THREAD

**Issue by 1Strawz1** [slowtorta/turtlewow-bug-tracker#1003]
**Please, provide a clear description what the bug is:**
Don't see Two-Handed maces on the Weapon master List.

**Steps to reproduce the behavior with as much detail as possible:**

1.Go to Buliwyf Stonehand in Irongorge 
2. Select Filters: Available, Unavailable, Already Known
3. Two-Handed Maces not showing in list:

**IDs of affected creatures, items, quests or spells with a link to the relevant page:**

NPC: https://database.turtle-wow.org/?npc=
Item: https://database.turtle-wow.org/?item=
Quest: https://database.turtle-wow.org/?quest=
Spell: https://database.turtle-wow.org/?spell=
Object: https://database.turtle-wow.org/?object=

**Expected behavior. Describe how it should work:**
Should be able to learn Two-Handed Mace for warrior
![image](https://user-images.githubusercontent.com/97827077/151638218-cdfe2f53-70ec-4243-9c24-79d313dba4de.png)
![image](https://user-images.githubusercontent.com/97827077/151638242-c17de82e-d678-4dc9-853e-02caf7f064ad.png)
![image](https://user-images.githubusercontent.com/97827077/151638274-c8ab7580-25e9-4fda-a947-0f64c896fc87.png)
![image](https://user-images.githubusercontent.com/97827077/151638311-9db6442a-a2ba-4efc-96d0-cb56c2a8de66.png)

**Comment by Zebouski** [comment]
this affects only high elf warriors
other race and class comibanations dont get this bug

**Comment by slowtorta** [comment]
Fixed in 1.16.1.
