### ISSUE TITLE
Bugged Defias Thugs at Northshire Vineyards

### ISSUE THREAD

**Issue by ASRoux** [slowtorta/turtlewow-bug-tracker#1005]
Please, provide a clear description what the bug is:
I'm playing a priest char. Every time I try to attack some of the Defias thugs, they stay where they were when I started attacking them. I get two hits in with the smite spell when after the third their health just resets.  After the health reset they start to evade every attack I throw at them, ranged or melee. It seems most of the thugs aren't bugged and behave/react normally, but some are bugged.

Steps to reproduce the behavior with as much detail as possible:

1. Go to Northshire Vineyard.
2. Go to the river bank on the left side of the bridge.
3. Attack the Defias thugs standing near, there should be three grouped together.

IDs of affected creatures, items, quests or spells with a link to the relevant page:

NPC: https://database.turtle-wow.org/?npc=38
Item: https://database.turtle-wow.org/?item= n/a
Quest: https://database.turtle-wow.org/?quest= n/a
Spell: https://database.turtle-wow.org/?spell= n/a
Object: https://database.turtle-wow.org/?object= n/a

Expected behavior. Describe how it should work:
When you attack them they should react normally; run towards the player and start attacking, be able to take damage and die.

**Comment by zomgits** [comment]
A new person to the server said "This isn't a good first impression."  I thought that was a good point.

**Comment by DanielLevesque** [comment]
New to the server, allow me to elaborate: 

The Northshire Defias mobs, when engaged in combat, most will "stick" to a specific spot, similar to how a mob would in retail when you exit it's legal pathing parameters. And enter the "evade" state. However, it will continue to hit you, except in this case: at range. Until you die. Which is entirely whacky. I have experienced some examples, as a rogue, sneaking up to a defias, backstabing them and then the npc would immediately enter evade mode and just stand there. I can't hit them, then eventually leave their regular aggro radius only to, 30 seconds later suddenly die as their attacks get batched on me somehow. 

That whole wing of the starting area is messed up. <3

**Comment by slowtorta** [comment]
Nothing we can do server-side about it, this is a mapping issue. This matter is under investigation in our internal tracker.

**Comment by slowtorta** [comment]
Possibly fixed or at least improved on the previous server update.
