### ISSUE TITLE
Please add "Rabbit" critters to Coldridge Valley (dwarf and gnome starting zone)

### ISSUE THREAD

**Issue by Gasan918** [slowtorta/turtlewow-bug-tracker#1007]
**Please, provide a clear description what the bug is:**

No rabbits are spawned at starnig zone.

**IDs of affected creatures, items, quests or spells with a link to the relevant page:**

NPC: https://database.turtle-wow.org/?npc=721

**Expected behavior. Describe how it should work:**

See 

https://vanillawowdb.com/?npc=721

**Comment by slowtorta** [comment]
Fixed on the next server update!
