### ISSUE TITLE
Scholomance Students Have Too Much HP

### ISSUE THREAD

**Issue by Axoc77** [slowtorta/turtlewow-bug-tracker#101]
**Please, provide a clear description what the bug is:**
Scholomance Students have incorrect HP.

**Steps to reproduce the behavior with as much detail as possible:**

1. Enter Scholomance.
2. Target a Scholomance Student.
3. Look at its HP value.

**IDs of affected creatures, items, quests or spells with a link to the relevant page:**

NPC: https://database.turtle-wow.org/?npc=10475

**Expected behavior. Describe how it should work:**
Scholomance Students should have 888 HP. Citation:
https://classic.wowhead.com/npc=10475/scholomance-student

**Comment by slowtorta** [comment]
HP values 888 comes from this quest:  https://database.turtle-wow.org/?quest=4771. There's an item you have to use in that room that will turn the students into skeletons.

https://youtu.be/3c07w_p0pWw?t=3434
Look how fast the skeletons die vs the student that didn't get turned:
https://youtu.be/3c07w_p0pWw?t=3453

At best we can change the script to change HP when mobs turn to skellies.
