### ISSUE TITLE
PVP: Alterac Valley - Doesn't start 5 minute countdown when less than 12 v 12 is active

### ISSUE THREAD

**Issue by Rakura1** [slowtorta/turtlewow-bug-tracker#1010]
**Please, provide a clear description what the bug is:**
Every other battleground has a count down timer when not enough people are in the game. For WSG its 4v4 and AB its 5v5. For Alterac Valley it could be 40 vs 1 and the timer will not count down. This causes major issues when games get down to 5 vs 2 and there is no way to finish the game.

**Steps to reproduce the behavior with as much detail as possible:**

1. Join game of Alterac Valley
2. Watch team numbers reach uneven or drop below 12 v 12
3. Timer never starts
4. Watch one side usually horde all leave and game timer never starts

**IDs of affected creatures, items, quests or spells with a link to the relevant page:**

**Expected behavior. Describe how it should work:**
If there are less than 12 v 12  a 5 min count down timer should start to close the round.

**Comment by jameyboor** [comment]
It's valid to have this in place for AV for certain numbers. We will be experimenting with this upcoming update.
