### ISSUE TITLE
Npc gazban doesn't turn into a elemental 

### ISSUE THREAD

**Issue by geojak** [slowtorta/turtlewow-bug-tracker#1011]
**Please, provide a clear description what the bug is:**

the npc gazban doesnt turn into an water elemental and doesnt attack the player on summon. he just stands around when summoned being neutral.

**Steps to reproduce the behavior with as much detail as possible:**

1. get the qeust the curse of tides
2. summo at the altar in the water next to the murlocs
3. gazban appears but doesnt attack as he should
4. attack him, he doesnt transform into a water elemtnal as he should

**IDs of affected creatures, items, quests or spells with a link to the relevant page:**

https://database.turtle-wow.org/?npc=2624
https://database.turtle-wow.org/?quest=611

**Expected behavior. Describe how it should work:**

https://www.youtube.com/watch?v=SDIoxfPCaGw

**Comment by slowtorta** [comment]
Thank you for your report. This will be fixed on the next server update.
![image](https://user-images.githubusercontent.com/66763404/153483644-70197519-4418-4b7d-bbfc-596d2e76ff33.png)
