### ISSUE TITLE
Saltspittle Raiders completion not displaying text

### ISSUE THREAD

**Issue by Elviraxxx** [slowtorta/turtlewow-bug-tracker#1012]
**Please, provide a clear description what the bug is:**
No text is displayed upon completion of the quest (the completion page is blank). In addition extra text (presumably the completion text) is displayed on the quest tracking. 

**Steps to reproduce the behavior with as much detail as possible:**

1. Turn the quest in to Hadanos Greenblade
2. 
3. 

**IDs of affected creatures, items, quests or spells with a link to the relevant page:**
NPC No 60472
Quest No 40230

NPC: https://database.turtle-wow.org/?npc=
Item: https://database.turtle-wow.org/?item=
Quest: https://database.turtle-wow.org/?quest=
Spell: https://database.turtle-wow.org/?spell=
Object: https://database.turtle-wow.org/?object=

**Expected behavior. Describe how it should work:**
There should be text upon completion.

![WoWScrnShot_013022_000513](https://user-images.githubusercontent.com/98165207/151681768-22604cdb-93ba-4e7e-aa74-5ef0af95e756.png)

**Comment by slowtorta** [comment]
Fixed, please clear WDB.
