### ISSUE TITLE
unreachable ooze covered mithril vain in strangelthron

### ISSUE THREAD

**Issue by geojak** [slowtorta/turtlewow-bug-tracker#1015]
there is an unreachable ooze covered mithril vain clsoe to booty bay

see provdied screenshots for location
![WoWScrnShot_013022_142239-min](https://user-images.githubusercontent.com/25199983/151701699-6099d2cc-78c4-45e4-858f-e988d527f4a3.jpg)
![WoWScrnShot_013022_142252-min](https://user-images.githubusercontent.com/25199983/151701700-da168b68-c75c-457e-977d-641a9c083dc3.jpg)

**Steps to reproduce the behavior with as much detail as possible:**

1. are oozed covered mithril vains supposed to spawn in strangethorn?
2. it is also impossible to reach this vain

**IDs of affected creatures, items, quests or spells with a link to the relevant page:**

**Expected behavior. Describe how it should work:**

should be reachable and probably not oozed covered

**Comment by LeopoldHock** [comment]
Vein was removed.
