### ISSUE TITLE
[CAN'T LOGIN]

### ISSUE THREAD

**Issue by Savionight** [slowtorta/turtlewow-bug-tracker#1018]
**Please, provide a clear description what the bug is:**

I can't login. When I insert my username and password, I have to wait for a long time for ''connecting'', after some time, I get ''disconected from server''.

I've uploaded on Youtube a video trying to describe my problem as accurate possible.

https://youtu.be/ApyBsnPwgMY

**Comment by LeopoldHock** [comment]
Not a bug. Login issues were related to restrictive firewall setup.
