### ISSUE TITLE
Wisp form audio bug

### ISSUE THREAD

**Issue by Zeebler** [slowtorta/turtlewow-bug-tracker#1019]
**Please, provide a clear description what the bug is:**

Night elf wisp form sound is missing.

**Steps to reproduce the behavior with as much detail as possible:**

1. Roll night elf.
2. Die
3. Listen for wisp sound. (Spirit audio music is still present)

**Expected behavior. Describe how it should work:**

There is a unique sound for wisp form that is missing. I couldn't find any audio to reference. It is like a ethereal humming.

**Comment by slowtorta** [comment]
Moving this issue to the internal tracker for client-related problems, thank you.
