### ISSUE TITLE
Schematic: Thorium Widget  is not being sold by the horde vendor

### ISSUE THREAD

**Issue by Tinyfin-github** [slowtorta/turtlewow-bug-tracker#1024]
Schematic: Thorium Widget  is not being sold by the horde vendor

https://database.turtle-wow.org/?item=16042  Schematic: Thorium Widget  is not being sold by the horde vendor, right now is only available for alliance.

https://database.turtle-wow.org/?npc=3413 Sovik should sell it for horde.

**Comment by geojak** [comment]
you can learn it from the master engineer trainer in tanaris too.

**Comment by Kruxis** [comment]
Will be applied on next server restart o/
