### ISSUE TITLE
Bloodhoof Innkeeper not interactable

### ISSUE THREAD

**Issue by Kiltzombie** [slowtorta/turtlewow-bug-tracker#1026]
**Please, provide a clear description what the bug is:**

**Steps to reproduce the behavior with as much detail as possible:**

1. The innkeeper in Bloodhoof village has no dialogue options
2. 
3. 

**IDs of affected creatures, items, quests or spells with a link to the relevant page:**

NPC: https://database.turtle-wow.org/?npc=
Item: https://database.turtle-wow.org/?item=
Quest: https://database.turtle-wow.org/?quest=
Spell: https://database.turtle-wow.org/?spell=
Object: https://database.turtle-wow.org/?object=

**Expected behavior. Describe how it should work:**

**Comment by LeopoldHock** [comment]
Known issue. Edited title to make it noticable easier.
