### ISSUE TITLE
tauren racial Endurance not scaling correctly

### ISSUE THREAD

**Issue by sewlek** [slowtorta/turtlewow-bug-tracker#1028]
when playing as tauren, the racial spell Endurance scales only with the base HP value, rather than the total value.

repro: create a tauren and equip items with stamina / buff stamina

Spell: https://database.turtle-wow.org/?spell=20550

expected behavior: in vanilla and TBC tauren received 5% of their total heal increased, including buffs.

**Comment by geojak** [comment]
It might be that also gnomes and human +% facials for spirit and int are only baseline.

To be honest this night be a good thing, considering making races fairer

**Comment by LeopoldHock** [comment]
@Nolin7777 could this be a vmangos issue?

**Comment by LeopoldHock** [comment]
Actually, checking wowhead confirms that the 5% is added **before** gear and stamina in Vanilla (I don't know about Classic): https://classic.wowhead.com/spell=20550/endurance#comments:id=2732855

**Comment by sewlek** [comment]
i dont believe this is correct, i remember drama about the tauren racial in vanilla TBC being op, here an old discussion about it: https://gamefaqs.gamespot.com/boards/534914-world-of-warcraft/47603692

this is from classic era, showing how tauren racial scales with gear: https://www.youtube.com/watch?v=ys5Xnu6btx4

**Comment by sewlek** [comment]
https://tbc.wowhead.com/spell=20550/endurance#comments

" [littlidabbi](https://tbc.wowhead.com/user=littlidabbi) [on 2008/02/19](https://tbc.wowhead.com/spell=20550/endurance#comments:id=234098:reply=326078) (Patch 2.3.3) 
Its total health, not base health. So, its +5% health after all ur gear and buffs."

**Comment by geojak** [comment]
Considering there was even drama in vanilla tbc how it's op when applied after gear. It still is propably for the best that here on vmangos its before gear. - - >working as intended?

**Comment by sewlek** [comment]
ok i did some math and found a video from vanilla with readable numbers and gear

https://www.youtube.com/watch?v=RGBnjELkgok&t=110s

tauren base health: 2760 (112 stamina at level 60)
395-112 = 283 additional stamina through gear:
2830 gear + 2760 base = 5590
+ 5% tauren bonus from gear: 141,5
5590 + 141.5 = 5731

that matches pretty much what is seen in the video, without tauren racial gear scaling you couldnt explain how he got 57xx HP

**Comment by sewlek** [comment]
so regarding the question if tauren racial scaled on total HP in vanilla, the answer is yes. should it also scale on turtle wow? thats an entirely different question, but considering that both in pvp and pve horde is underrepresented, id say the answer should also be yes

**Comment by sewlek** [comment]
i stand corrected, the scaling actually works correctly on turtle wow, sorry for the unnecessary bug report
