### ISSUE TITLE
Lifegiving Gem healing incorrect

### ISSUE THREAD

**Issue by sewlek** [slowtorta/turtlewow-bug-tracker#1029]
The warrior trinket "Lifegiving Gem" heals less than it should.

repro: create a warrior and equip lifegiving gem, lose some health and use the trinket

Item: https://database.turtle-wow.org/?item=19341

expected behavior: lifegiving gem should heal for much more, in full T3 currently it barely heals as much as a major healing potion, but it should heal over twice as much

**Comment by sewlek** [comment]
for comparison classic era vs turtle WoW:
https://www.youtube.com/watch?v=NYA3EyYfuB4

https://www.youtube.com/watch?v=04fEvPHFWbM

in classic era, current health changes by 2103, but on turtle WoW only by 1100

**Comment by jameyboor** [comment]
With 2760 HP it heals me for 476. 2760 / 100 * 15 = 414, with some bonus healing -> 476. Works as intended.

**Comment by sewlek** [comment]
its missing scaling up of current hp

**Comment by sewlek** [comment]
healAmount = maxHP * 0.15

what happens on turtle wow is:

maxHP += healAmount 
currentHP += healAmount 

what should happen instead:

currentHP += healAmount 
(currentHP / maxHP) = percentage
maxHP += healAmount 
currentHP = maxHP * percentage

-> the healAmount is correct, the scaling up of currentHP is skipped
