### ISSUE TITLE
Saltspittle Raiders quest summary line messes up tracker

### ISSUE THREAD

**Issue by zomgits** [slowtorta/turtlewow-bug-tracker#1031]
**Please, provide a clear description what the bug is:**
The quest summary line for Saltspittle Raiders is too long for the default UI quest tracker and contains a substitution, which won't work there.

![image](https://user-images.githubusercontent.com/97355053/151839115-753ea5c8-697d-4432-a28b-f77811660bda.png)

**IDs of affected creatures, items, quests or spells with a link to the relevant page:**

Quest: https://database.turtle-wow.org/?quest=40230

**Expected behavior. Describe how it should work:**
Quest summary lines should be very short while indicating the objective.  In this case: "Greenblade Book: 0/1".

**Comment by zomgits** [comment]
This quest also has blank text when you hand it in.

**Comment by mikefirefly** [comment]
Related to #1012 #958 #872 #892 

Would be nice if a dev thought about this for a while instead of doing a quick "fix"...

**Comment by zomgits** [comment]
> Related to #1012 #958 #872 #892
> 
> Would be nice if a dev thought about this for a moment and understood what's happening here instead of doing a quick hackjob which fixes nothing...

Oops. I should've searched.

**Comment by zomgits** [comment]
Actually, one of those is *my* bug and I believed the "fixed" tag.  I guess they didn't test their fix.
