### ISSUE TITLE
Custom level 60 mobs are still unleashed

### ISSUE THREAD

**Issue by zomgits** [slowtorta/turtlewow-bug-tracker#1034]
See https://github.com/slowtorta/turtlewow-bug-tracker/issues/966#issuecomment-1019358890

New report:
![image](https://user-images.githubusercontent.com/97355053/151856373-da915549-3636-4c33-9663-d0c6a4a8f1c3.png)

**Comment by LeopoldHock** [comment]
@Dormilon
