### ISSUE TITLE
Blueleaf Tubers doesn't work if both factions are in the group

### ISSUE THREAD

**Issue by Katsuane** [slowtorta/turtlewow-bug-tracker#1037]
Blueleaf tubers doesn't work if both factions are in the same group for the instance.

I personally haven't tested this myself yet, I just see it talked about in world almost daily.

https://database.turtle-wow.org/?quest=1221
https://database.turtle-wow.org/?item=5876
https://database.turtle-wow.org/?object=20920

Quest should work despite the cross-faction grouping. It just obviously wasn't accounted for.

**Comment by LeopoldHock** [comment]
I completed the quest in a cross-faction group last year. Please include specific steps on how to reproduce the issue and describe what exactly isn't working.

**Comment by LeopoldHock** [comment]
@Katsuane

**Comment by LeopoldHock** [comment]
Was tested on 28th january in a cross-faction group and the issue could not be reproduced. Closing until getting proper steps to reproduce.
