### ISSUE TITLE
A Harmonious Offering (Mulgore) - cannot complete

### ISSUE THREAD

**Issue by thecreth** [slowtorta/turtlewow-bug-tracker#1038]
Please, provide a clear description what the bug is:
Quest 'Harmonious Offering' from the dryad NPC (Melyndella) in Bloodhoof Village is impossible to complete

Steps to reproduce the behavior with as much detail as possible:

1. Accept the quest Harmonious Offering from Melyndella, thereby receiving the quest item
2. Go to the NPC described by Melyndella and attempt to deliver the quest item
3. You will see the NPC can be interacted with but has no option to give them the item, therefore making the quest impossible

IDs of affected creatures, items, quests or spells with a link to the relevant page:
NPC: https://database.turtle-wow.org/?npc=66002
Quest: https://database.turtle-wow.org/?quest=40366

Expected behavior. Describe how it should work:
1. Accept the quest and acquire the quest item from the NPC <-- this works
2. Deliver the item to the described NPC <-- this does not work
3. Return to the original NPC and complete the quest <-- this is impossible

**Comment by LeopoldHock** [comment]
@thecreth did you try clearing WDB and retaking the quest?

**Comment by thecreth** [comment]
I cleared WDB and relogged, this did not fix the issue. I did not clear WDB, abandon quest, and re-take it. I can test that later.

**Comment by slowtorta** [comment]
Try again please, it's been updated once more.

**Comment by thecreth** [comment]
Confirming that the quest works correctly with WDB cleared.
