### ISSUE TITLE
Undead Hunter's Taming the Beast quests: wrong debuff description.

### ISSUE THREAD

**Issue by TrangOul** [slowtorta/turtlewow-bug-tracker#1041]
**Please, provide a clear description what the bug is:**

When Undead Hunters tame a beast as a part of their Taming the Beast quests, a debuff on the beast in displayed incorrectly as Tame Dire Mottled Boar:

![image](https://user-images.githubusercontent.com/5629046/151938411-25ec241f-6954-46be-969e-072ff842d6e8.png)
![image](https://user-images.githubusercontent.com/5629046/151938420-ed8dcd8c-950e-402e-91d9-6e0e9811c9aa.png)

**Steps to reproduce the behavior with as much detail as possible:**

1. Take Taming the Beast I, II or III quest from Liott Maneskin.
2. Tame a beast.
3. Look at its debuffs.

**IDs of affected creatures, items, quests or spells with a link to the relevant page:**

NPC: https://database.turtle-wow.org/?npc=60484 (undead hunter quest giver)
NPC: https://database.turtle-wow.org/?npc=3099 (creature described in the debuff)
NPC: https://database.turtle-wow.org/?npc=3171 (orc/troll hunter quest giver)
Item: https://database.turtle-wow.org/?item=60329 (item for undead hunter quest I)
Item: https://database.turtle-wow.org/?item=60330 (item for undead hunter quest II)
Item: https://database.turtle-wow.org/?item=60331 (item for undead hunter quest III)
Item: https://database.turtle-wow.org/?item=15917 (item for orc/troll hunter quest)
Quest: https://database.turtle-wow.org/?quest=40248 (undead hunter quest I)
Quest: https://database.turtle-wow.org/?quest=40249 (undead hunter quest II)
Quest: https://database.turtle-wow.org/?quest=40250 (undead hunter quest III)
Quest: https://database.turtle-wow.org/?quest=6062  (orc/troll hunter quest with relevant creature to tame)

**Expected behavior. Describe how it should work:**

A correct debuff is displayed, not copied from the Hunter quest in Durotar.

**Comment by slowtorta** [comment]
Moving this issue to the internal tracker for client-related problems, thank you.
