### ISSUE TITLE
Silver Sun Mine camera issues

### ISSUE THREAD

**Issue by Jalamon** [slowtorta/turtlewow-bug-tracker#1042]
**Please, provide a clear description what the bug is:**

In the Silver Sun Mine in Alah'Thalas there are many areas where the player camera gets pinched down due to invisible ceilings and walls.

**Steps to reproduce the behavior with as much detail as possible:**

1.Walk into Silver Sun Mine in Alah'Thalas
2. Walk around, especially in the center of the cave
3. Have camera limited so much so that it will make you go first person in some areas.

**IDs of affected creatures, items, quests or spells with a link to the relevant page:**

Quest: https://database.turtle-wow.org/?quest=80252
Object: https://database.turtle-wow.org/?object=3000222

**Expected behavior. Describe how it should work:**

When questing here and collecting crystals or mining copper, should not have camera pinching so much so that the player cannot scroll out and is forced into first person or very close to the model.

**Comment by Mosch0512** [comment]
Hey there i just want to say this is still a issue. And i dont really get why it is closed if it is not done yet... could be let opened until its dont inside your internal tracker and linked so you know you have to close this one too. @slowtorta
