### ISSUE TITLE
[Paladin] [Spell] [Talent] Reckoning

### ISSUE THREAD

**Issue by mclgv** [slowtorta/turtlewow-bug-tracker#1045]
Reckoning is activated on my character after getting critical strike. Character name is Ironbelly.

**Steps to reproduce the behavior with as much detail as possible:**

1. Go interface options, check to show reactive spells and abilities
2. Gather up 3+ mobs that equal to your level.
3. Get into fight and wait for activating of Reckoning

Spell: https://database.turtle-wow.org/?spell=20182

**Expected behavior. Describe how it should work:**

During Combat Reckoning must be activated after getting critical strike and give double damage to target.

Expected Behavior for talent, scene starts at 3:10

https://youtu.be/dzK8VQg0_gI?t=190

**Comment by geojak** [comment]
So reckoning is not working at all on TWoW or its working wrong?

Thaz pvp video has so much going on. Hard to say what's different

**Comment by Velite12** [comment]
What is the issue?

**Comment by geojak** [comment]
I respected to prot today and reckoning OS working. It just doesn't show up in combat log.
