### ISSUE TITLE
Warlock Damage bugged in recent update

### ISSUE THREAD

**Issue by Durisbane** [slowtorta/turtlewow-bug-tracker#1046]
**Please, provide a clear description what the bug is:**
After the recent update warlock shadow DoT skills (Curse of Agony, Corruption and Siphon Life) are doing reduced damage per tick

**Steps to reproduce the behavior with as much detail as possible:**

1. Curse of Agony, Corruption and Siphon Life
2. Record the damage it does
3. Compare the damage before and after the recent update

**IDs of affected creatures, items, quests or spells with a link to the relevant page:**

NPC: https://database.turtle-wow.org/?npc=
Item: https://database.turtle-wow.org/?item=
Quest: https://database.turtle-wow.org/?quest=
Spell: https://database.turtle-wow.org/?spell=
Object: https://database.turtle-wow.org/?object=

**Expected behavior. Describe how it should work:**
Before last update:
Curse of agony was doing 185 damage on first tick for me
Corruption was doing 276 damage per tick for me

After last update:
Curse of agony is doing 155 damage on first tick for me
Corruption is doing 244 per tick for me

These damage differences are with the exact same gear, and exact same setting (PvP)

**Comment by CosminPOP** [comment]
Damage coefficients for a lot of spells were bugged when patch released in december, not they're back to normal.
