### ISSUE TITLE
DM:E Treants not patrolling since latest restart.

### ISSUE THREAD

**Issue by mch123456785** [slowtorta/turtlewow-bug-tracker#1049]
**Please, provide a clear description what the bug is:**

2 pats in DM:E aren't patrolling with the third in the group (treants on lower level) since reset.

**Steps to reproduce the behavior with as much detail as possible:**

1. Enter DM:East
2. Jump to lower level
3. Look at patrolling mobs (furthest two from entrance are the ones that don't patrol)

**IDs of affected creatures, items, quests or spells with a link to the relevant page:**

NPC: https://database.turtle-wow.org/?npc=
Item: https://database.turtle-wow.org/?item=
Quest: https://database.turtle-wow.org/?quest=
Spell: https://database.turtle-wow.org/?spell=
Object: https://database.turtle-wow.org/?object=

**Expected behavior. Describe how it should work:**

Those mobs should be part of the packs and patrol.
![Screenshot (215)](https://user-images.githubusercontent.com/98909993/152215784-3d278b8c-1fa8-47a2-aff2-8b10cc0661a2.png)
![Screenshot (216)](https://user-images.githubusercontent.com/98909993/152215801-b4962a93-fd10-4dfe-bf00-0334ffeb1aba.png)

**Comment by geojak** [comment]
lots and lots of patrols are broken

**Comment by redmagejoe** [comment]
These patrol properly now.
