### ISSUE TITLE
tooga not moving

### ISSUE THREAD

**Issue by geojak** [slowtorta/turtlewow-bug-tracker#1050]
**Please, provide a clear description what the bug is:**

toggas spawn point is wrong and he also doesnt wander around 

**IDs of affected creatures, items, quests or spells with a link to the relevant page:**

https://database.turtle-wow.org/?npc=5955

**Expected behavior. Describe how it should work:**

https://classic.wowhead.com/npc=5955/tooga

**Comment by LeopoldHock** [comment]
The spawn point was moved intentionally. Checking wowhead confirms he's supposed to wander around, however.

**Comment by geojak** [comment]
If he is supposed to be lost, then he should be standing static around

**Comment by slowtorta** [comment]
Made my bro wander 🐢
