### ISSUE TITLE
Lady Janira quest displays the wrong quest level

### ISSUE THREAD

**Issue by Chnams** [slowtorta/turtlewow-bug-tracker#1053]
**Please, provide a clear description what the bug is:**  

The Lady Janira quest in Feralas is shown as a level 45 quest:
![image](https://user-images.githubusercontent.com/29188104/152325713-e924293c-f6ed-466d-83c5-102279a2e79c.png)
But the elite that you need to kill is level 50:
![image](https://user-images.githubusercontent.com/29188104/152325731-78262e62-21ae-4b50-94ea-a35b8f477208.png)

The quest level is also shown as 45 on the turtle database, so it's not an issue on my end.

**Steps to reproduce the behavior with as much detail as possible:**

1. Not much to do here, just pick up the quest in Feralas and notice that the elite is lvl 50 instead of 45 :)

**IDs of affected creatures, items, quests or spells with a link to the relevant page:**

NPC: https://database.turtle-wow.org/?npc=51280
Quest: https://database.turtle-wow.org/?quest=60020

**Expected behavior. Describe how it should work:**

The quest level should be marked as 50 for clarity.

**Comment by gheor7** [comment]
Clearly says 45+, it's supposed to be a group quest most likely, so you either do it with another player or two or you solo it later :)

**Comment by Chnams** [comment]
45+ means it's an elite or dungeon quest, not that it's meant for levels 45 and up :)

**Comment by geojak** [comment]
I agree with chnmas. The lvl doesn't match with other vanilla elite quests framework
