### ISSUE TITLE
Race Changed - Can no longer res at Graveyard 

### ISSUE THREAD

**Issue by littletoads** [slowtorta/turtlewow-bug-tracker#1054]
I have the same problem urag had but my "other" tab in reputation doesnt look like his, its alliance just hated with certain alliance faction
![Screenshot (4)](https://user-images.githubusercontent.com/72800555/152345866-9166e0e4-82c9-4d88-b769-7afe94178766.png)
s

**Comment by Tinyfin-github** [comment]
I  am sorry, i forgot to fix this issue for you when i did the race change because you did not discovered the faction yet.

I discovered the factions, disabled at war, and you should be able to to see the factions now and res at the spirit healer.

**Comment by littletoads** [comment]
working fine now thank you
