### ISSUE TITLE
Tight leashing/ kiting broken

### ISSUE THREAD

**Issue by Steevo2** [slowtorta/turtlewow-bug-tracker#1055]
I have noticed recently that the leashes on most mobs in turtle is incredibly tight, and does not care if the mob has been hit recently. This is a huge problem for classes that need kiting like War or mage, and also triggers on feared mobs very easily. The most obvious way to reproduce this is on a mage using frost nova, blink and frostbolt - leashing will occur within an unreasonably short distance if kiting doesnt back on itself within the same 50 yards. 

I know that its not that the mob isnt being hit enough either as the nova is broken by the frostbolt, and the mob is constantly being hit by frostbolts. I got another lvl 60 mage to test for me and they had the same issue and swore it hadn't been a probelm before, although I cant speak that that personally. Someone is chat said it was about preventing leashing to kill HC chars which I appreciate, but you need to increase it a little IMO

**Comment by mikefirefly** [comment]
Can confirm. As a hunter, it's basically impossible to kite using Scorpid Sting. It's as if the mob didn't care it's being actively damaged, and just resets as normal.

**Comment by Steevo2** [comment]
Just writing to add that I just had an enemy leash whilst actively being mind flayed maybe 60 yards from where it was pulled from. This is definitely not vanilla settings

**Comment by jameyboor** [comment]
It's not. And it's intended. Leashing mechanics are slightly different on TWoW. I have modified this to slightly relax the leashing timings. This should be in effect on next server update.
