### ISSUE TITLE
Lunar Fireworks quest dont work

### ISSUE THREAD

**Issue by Drwarlocke** [slowtorta/turtlewow-bug-tracker#1057]
**Please, provide a clear description what the bug is:**

**Steps to reproduce the behavior with as much detail as possible:**

1. get the quest no problem Lunar Fireworks 
2. Buy Lunar Firework Fired and Lunar Fireworks Cluster no problem from vendor 
3. use Firework Fired and Cluster dont work must be a bug...
4. https://database.turtle-wow.org/?quest=8867
**IDs of affected creatures, items, quests or spells with a link to the relevant page:**

NPC: https://database.turtle-wow.org/?npc=
Item: https://database.turtle-wow.org/?item=
Quest: https://database.turtle-wow.org/?quest=
Spell: https://database.turtle-wow.org/?spell=
Object: https://database.turtle-wow.org/?object=

**Expected behavior. Describe how it should work:**

**Comment by LeopoldHock** [comment]
This is fixed and will go live soon.
