### ISSUE TITLE
some engineer companion pets dont go into speelbok

### ISSUE THREAD

**Issue by geojak** [slowtorta/turtlewow-bug-tracker#1058]
**Please, provide a clear description what the bug is:**
the goblin engineer unique crafted pet item "pet bombling"doesnt go into the spellbook. the mechanical squirrer and the gnomish lil smoky had the same problem but it has been almost fixed by now. they are now in the generals book instead of the pet part but atleast they dont take any invertory space. so it would be great if the pet bombling could be fixed too.

**Steps to reproduce the behavior with as much detail as possible:**

1. craft pet bombling as engineer
2. summon the pet
3. it works like on standard vanilla and the item stays in the bag

**IDs of affected creatures, items, quests or spells with a link to the relevant page:**

https://database.turtle-wow.org/?item=11825

**Expected behavior. Describe how it should work:**

item should vanish and pet boobling added to pet spell book

**Comment by geojak** [comment]
the pet lifelike mechanical toad has the same problem

https://database.turtle-wow.org/?item=15996

**Comment by slowtorta** [comment]
Fixed in 1.16.1, thank you!
