### ISSUE TITLE
PVP: Concerted effort - Arathi Basin doesn't reward correct rep

### ISSUE THREAD

**Issue by Rakura1** [slowtorta/turtlewow-bug-tracker#1059]
**Please, provide a clear description what the bug is:**
Arathi basin should be getting 150 rep per concerted effort turn in. At present it only gives 100.
**Steps to reproduce the behavior with as much detail as possible:**

1. Get 3 marks for all 3 bgs
2. Turin concerted effort quest
3.  Get 200 for av / 150 for wsg / 100 for ab

**IDs of affected creatures, items, quests or spells with a link to the relevant page:**

Quest: https://classic.wowhead.com/quest=8371/concerted-efforts

**Expected behavior. Describe how it should work:**
Should receive 150 rep for Arathi basin. If the devs are feeling generous give 200 rep for all 3 in stead of picking and choosing like vanilla designed to improve quality of life.

**Comment by CosminPOP** [comment]
Working as intended.

First quest is https://classic.wowhead.com/quest=8371/concerted-efforts
150 reputation with [The League of Arathor]
200 reputation with [Stormpike Guard]
150 reputation with [Silverwing Sentinels]

Repeatable quest is https://classic.wowhead.com/quest=8385/concerted-efforts
150 reputation with [Stormpike Guard]
100 reputation with [The League of Arathor]
100 reputation with [Silverwing Sentinels]
