### ISSUE TITLE
Augerer's  set recipe is already gray when learned at the 200-210 tailoring range

### ISSUE THREAD

**Issue by Tinyfin-github** [slowtorta/turtlewow-bug-tracker#1062]
Augerer's  set recipe is already gray when learned  at the 200 -210 tailoring and  the items give no experience when crafted

The set needs  Between 200 -210 tailoring to learn, the recipes should not be gray.

https://database.turtle-wow.org/?npc=4576 Josef Gregorian can teach them to you.

![WoW_4TYZsWu4RT](https://user-images.githubusercontent.com/83077166/152488690-d6e64b73-8b83-4403-ab45-ed523c90ecd1.png)

![WoW_vE1Dw9EMn2](https://user-images.githubusercontent.com/83077166/152488933-6a9cd300-50a1-4061-b2a6-46299afd43f7.png)

![WoW_y293H8wYbN](https://user-images.githubusercontent.com/83077166/152488929-206a22a9-240d-4a30-9e19-7444dbb4173b.png)
![WoW_iBvmd829q7](https://user-images.githubusercontent.com/83077166/152488931-9a4ba71b-df19-49d5-a9e1-6ecee71666d5.png)

**Comment by geojak** [comment]
Same problem. With the wormhole engineer recipes

**Comment by slowtorta** [comment]
Moving this issue to the internal bug-tracker for client developers, thank you.
