### ISSUE TITLE
Time-Worn Rune - dissapears / gets consumed

### ISSUE THREAD

**Issue by dole555** [slowtorta/turtlewow-bug-tracker#1063]
**Please, provide a clear description what the bug is:**
The item Time-Worn Rune dissapears from your bags after 5 uses (estimated). 

**Steps to reproduce the behavior with as much detail as possible:**

1. Aquire item Time-Worn Rune
2. Use it 5 times (estimated)
3. See as it dissapears from your bags.

**IDs of affected creatures, items, quests or spells with a link to the relevant page:**

Item: https://database.turtle-wow.org/?item=61000

**Expected behavior. Describe how it should work:**
The item note should say it has 5 uses (estimated), but it doesnt. Or it should remain in your bags if that is intended and not get used up.

**Comment by slowtorta** [comment]
Thank you. This is a client issue and it'll be fixed in the upcoming patch 1.16.1.
![image](https://user-images.githubusercontent.com/66763404/153496184-2e4c2f58-361c-4ac0-b2a9-7467716194f1.png)
