### ISSUE TITLE
Typo in NPCs text (Prospector Gehn)

### ISSUE THREAD

**Issue by Gasan918** [slowtorta/turtlewow-bug-tracker#1064]
**Please, provide a clear description what the bug is:**

![image](https://user-images.githubusercontent.com/96973359/152583332-9b8dc3e2-5161-4936-812e-7901a217e6ec.png)

**Steps to reproduce the behavior with as much detail as possible:**

1. Talk to Prospector Gehn

**IDs of affected creatures, items, quests or spells with a link to the relevant page:**

NPC: https://database.turtle-wow.org/?npc=1255

**Comment by Kruxis** [comment]
Greetings! 

Typo will be fixed on next restart!
