### ISSUE TITLE
"The Active Agent" quest claimable without completing the quest

### ISSUE THREAD

**Issue by Sylebrias** [slowtorta/turtlewow-bug-tracker#1066]
**Please, provide a clear description what the bug is:**

I'm able to claim the rewards from "The Active Agent" without of having completed it, haven't even been to Stratholme yet.

**Steps to reproduce the behavior with as much detail as possible:**

Character Nidi

1. Talk to Betina Bigglezink at lights hope chapel and pick "Betina, I'd like a replacement Rune of the dawn Please!" or "Betina, I'd like a replacement Seal of the dawn Please!"
2.  Get trinket for quest I haven't completed

**IDs of affected creatures, items, quests or spells with a link to the relevant page:**

NPC: https://database.turtle-wow.org/?npc=11035
Item: https://database.turtle-wow.org/?item=13209
or https://database.turtle-wow.org/?item=19812
Quest: https://database.turtle-wow.org/?quest=5213

**Expected behavior. Describe how it should work:**

Not to be able to claim a trinket for a quest i haven't done

**Comment by Dormilon** [comment]
The quest is working correctly.
