### ISSUE TITLE
[Reputation Visual bug] Darnassus won't  show the real reputation in the Faction Tab

### ISSUE THREAD

**Issue by Tinyfin-github** [slowtorta/turtlewow-bug-tracker#1069]
[Reputation Visual bug] Darnassus won't  show the real reputation in the Faction Tab

But the real reputation effects apply:
Example: If  a player reaches exalted, while it will show revered, he can purchase the racial mounts.

When trying to set to exalted:

![image](https://user-images.githubusercontent.com/83077166/152671821-9cd7b425-e985-4608-87bf-3f2bfddfed79.png)

![image](https://user-images.githubusercontent.com/83077166/152671824-6be5789f-a608-4714-95a1-c1764021ceee.png)

![image](https://user-images.githubusercontent.com/83077166/152671832-947009da-bab1-4618-8d16-8a6d78147d33.png)

When trying to set to friendly:

![image](https://user-images.githubusercontent.com/83077166/152671854-6907b38d-1ef1-42ae-82f4-7527e91ea371.png)
![image](https://user-images.githubusercontent.com/83077166/152671856-b2172876-a151-421c-ba82-5a6195da5084.png)

**Comment by slowtorta** [comment]
Moving this issue to the internal bug-tracker for client developers, thank you.
