### ISSUE TITLE
[Warrior][Druid] Warriors and Bear Druids do not get a rage refund on missed melee abilities.

### ISSUE THREAD

**Issue by Velite12** [slowtorta/turtlewow-bug-tracker#1070]
**Please, provide a clear description what the bug is:**

On classic, when warriors, rogues, cat and bear druids MISS DODGE or PARRY an ability that hits a single target, they only pay 20% of the base cost of the ability in rage/energy

On turtle, warriors and bear druids pay full 100% of rage cost if an ability is a MISS, but they get the discount on DODGE/PARRY
On turtle, rogues and cat druids get discount on MISS DODGE PARRY like classic.

**Steps to reproduce the behavior with as much detail as possible:**

1. Heroic strike/maul with 100 rage
2. Miss
3. You have 85 rage

**IDs of affected creatures, items, quests or spells with a link to the relevant page:**

Warriors and Bear druids rage refund when ability is a MISS

**Expected behavior. Describe how it should work:**

If you have 100 rage, you should see 97 rage after a heroic strike/maul MISS DODGE or PARRY

![image](https://user-images.githubusercontent.com/45871932/152674968-82c17688-111e-443b-b1d3-7ad2e7da1b27.png)

![image](https://user-images.githubusercontent.com/45871932/152674975-54fa7e56-d367-42c4-9c5a-7d000f573e6e.png)

![image](https://user-images.githubusercontent.com/45871932/152675057-a369fc26-5d7e-4c6b-b4ba-9f997a540a30.png)

![image](https://user-images.githubusercontent.com/45871932/152675189-5e42d1c7-dfd5-4c44-95aa-6b2e537a1867.png)

**Comment by jameyboor** [comment]
According to some Vanilla posts, like https://www.bluetracker.gg/wow/topic/eu-en/12911577-18-02-05-kalgans-response-to-warriors/, this seems to be the case for dodge/parry definitely, unsure about miss. But seeing how we don't have more verifiable evidence for now we'll look into following the classic behaviour for now.

**Comment by Velite12** [comment]
@jameyboor So does this mean you are going to add the behavior for bear druids and warriors to get an energy refund when they miss an ability?

**Comment by jameyboor** [comment]
Yes. @Velite12

**Comment by Velite12** [comment]
Ok, thanks @jameyboor, usually I don't see the issue closed until it's fixed that is why I was asking.
