### ISSUE TITLE
Barthos' Engineering Notes are required, but not listed as a requirement

### ISSUE THREAD

**Issue by zomgits** [slowtorta/turtlewow-bug-tracker#1071]
**Please, provide a clear description what the bug is:**
Bug 1. For the quest "Tilting Oscilation Inhibitor?!" [sic] the item Barthos' Engineering Notes is required for hand-in, but it not listed as a required item in either the quest text or the hand-in dialog.

![WoW 2022-02-06 17-19-23](https://user-images.githubusercontent.com/97355053/152692939-b47e1b71-db20-4203-8e67-e3156904ae5b.png)

Bug 2. The database also does not show it as a quest objective.

Bug 3. That's not how you spell "oscilation".

**Steps to reproduce the behavior with as much detail as possible:**

1. Take the quest "Tilting Oscilation Inhibitor?!"
2. Collect the quest items.
3. Delete the engineering notes.
4. Note: Quest shows as "Complete".
5. Try to hand in quest.

**IDs of affected creatures, items, quests or spells with a link to the relevant page:**

NPC: https://database.turtle-wow.org/?npc=52066
Item: https://database.turtle-wow.org/?item=81409
Quest: https://database.turtle-wow.org/?quest=55210

**Expected behavior. Describe how it should work:**
1. Either the notes should not be required (best) or they should be listed as a required item.
2. The database should show them as a quest objective if they are a quest objective.
3. Spelling checker?

Thanks!

**Comment by zomgits** [comment]
A workaround for anyone else who does this: abandon the quest and take it again. It won't delete the engineering items and you'll get the notes again.

**Comment by Dormilon** [comment]
Apparently someone fixed the quest before me. The item "Barthos' Engineering Notes" is not required to complete the quest.
