### ISSUE TITLE
Stormwind Florist vendor catalogue inaccuracy

### ISSUE THREAD

**Issue by Zeebler** [slowtorta/turtlewow-bug-tracker#1077]
**Please, provide a clear description what the bug is:**

NPC named Bernard Gump does not sell herbs as expected. NPC Bernard Gump is a Florist located at Fragrant Flowers in Stormwind.
This is following official wow Classic data as a reference. I also know this based off my experience with Blizzards version wow classic. 

**Steps to reproduce the behavior with as much detail as possible:**

1. Talk to Bernard Gump.
 (OR) view Database for verification

**IDs of affected creatures, items, quests or spells with a link to the relevant page:**

classic wowhead db: https://classic.wowhead.com/npc=1302/bernard-gump
turtle wow db: https://database.turtle-wow.org/?npc=1302

**Expected behavior. Describe how it should work:**
Bernard Gump should sell the following herbs in limited supply: Kingsblood (1), Wild Steelbloom(1), Mageroyal(4), Bruiseweed(3), Silverlead(3), Peacebloom(3), Earthroot(6).

**Comment by Gasan918** [comment]
IMAO Turtle team have implemented Vanilla version of Bernard Gump, not Classic

https://vanillawowdb.com/?npc=1302

Some Vanilla server:
![image](https://user-images.githubusercontent.com/96973359/152846055-d6b93908-a186-45f9-a366-a7ceb4b7aa1c.png)

**Comment by jameyboor** [comment]
Correct, and we strive to stay as close to vanilla unless there are compelling arguments for taking Classics version, i.e. not enough evidence etc.

**Comment by Zeebler** [comment]
> Correct, and we strive to stay as close to vanilla unless there are compelling arguments for taking Classics version, i.e. not enough evidence etc.

If you read wowhead comments from 2004-2006 people do mention seeing herbs sold. 1 person said he doesnt but perhaps he was out of stock. This as far as my research goes. I dont really know how to dig deeper onto this subject.

I'd say the fact that this is even discussed in that time is substantial evidence to support that he sold herbs. If he did not sell the herbs it would not have been a subject for discussion. As it stands there is no evidence to show his catalogue on turtle wow is true to vanilla.
