### ISSUE TITLE
Un'Goro Power Crystal Changes Color When Camera Angle Changes

### ISSUE THREAD

**Issue by pillbug22** [slowtorta/turtlewow-bug-tracker#1078]
**Please, provide a clear description what the bug is:**
Possibly more of a client issue?

Power crystal in Un'Goro Crater changes visible color based on camera angle. In the example video clip, the tooltip (and beginning camera angle) shows a red power crystal, but changing the camera angle shows a green crystal. However, the tooltip still states red. Also noticed after a few minutes (when typing up this report) that the crystal is now showing green, as well as the tooltip.

Edit: Most crystals appear to be behaving normally. Have only seen this happen a few rare times.

https://user-images.githubusercontent.com/4721980/152833258-e390a178-18a2-49be-a700-f9ce6c44ac18.mp4

**Steps to reproduce the behavior with as much detail as possible:**
1. Find power crystal in Un'goro Crater
2. Ride close to crystal
3. Change camera angle

**IDs of affected creatures, items, quests or spells with a link to the relevant page:**
Item: https://database.turtle-wow.org/?item=11186

**Expected behavior. Describe how it should work:**
Power crystal stays the same, regardless of camera angle

**Comment by Kruxis** [comment]
What rosen40 said. Can rarely happen. =)

**Comment by pillbug22** [comment]
Makes sense. Thanks for verifying/explaining!
