### ISSUE TITLE
[Hunter] Sewer Beast won't move while in combat after taming him

### ISSUE THREAD

**Issue by blargsnarf** [slowtorta/turtlewow-bug-tracker#108]
**Please, provide a clear description what the bug is:** I tamed Sewer Beast, the albino croc in SW, then took him outside to fight some mobs. When I tell him to attack and he enters combat, he stops moving, and won't move again until I tell him to return to me and leave combat. He also stops moving if he aggros an enemy by himself.

**Steps to reproduce the behavior with as much detail as possible:**

1. Tame Sewer Beast.
2. Get him into combat, either by sending him, or letting him aggro a mob.
3. He stops moving.

**IDs of affected creatures, items, quests or spells with a link to the relevant page:**

NPC: https://database.turtle-wow.org/?npc=3581

**Expected behavior. Describe how it should work:** Sewer Beast should run around in combat like all other hunter pets.

**Comment by slowtorta** [comment]
Cannot reproduce. Working as intended. I was able to tame Sewer Beast and successfully send him into battle.
