### ISSUE TITLE
Apostrophe catastrophe in Naga Tridents

### ISSUE THREAD

**Issue by zomgits** [slowtorta/turtlewow-bug-tracker#1080]
**Please, provide a clear description what the bug is:**
The quest "Naga Tridents" uses an apostrophe for the plural of "trident", making "trident's".

> Gather 14 Naga Trident's for Raga Darkeye ...

**IDs of affected creatures, items, quests or spells with a link to the relevant page:**

Quest: https://database.turtle-wow.org/?quest=40328

**Expected behavior. Describe how it should work:**
Never form plurals with apostrophes.

**Comment by Kruxis** [comment]
Thanks for the report, will be applied soon =) 

Safe Travels!
