### ISSUE TITLE
Gor'dosh Firethrower and Gor'dosh Shaman abilities mixed

### ISSUE THREAD

**Issue by Tinyfin-github** [slowtorta/turtlewow-bug-tracker#1081]
Gor'dosh Firethrower and Gor'dosh Shaman abilities mixed

Gor'dosh Firethrower https://database.turtle-wow.org/?npc=91852#abilities  has skill specific to shamans

![image](https://user-images.githubusercontent.com/83077166/153066915-1289eae2-f416-4f1e-93e7-c763dd5d6a19.png)

Gor'dosh Shaman https://database.turtle-wow.org/?npc=91851#abilities has skills that would be better fitted for firethrower

![image](https://user-images.githubusercontent.com/83077166/153067125-2ec1c6f5-2cc5-4baa-b857-457866f196d2.png)

**Comment by slowtorta** [comment]
Fixed on the next server update!
