### ISSUE TITLE
Dead Stormwind Guard NPC at Elwynn Forest

### ISSUE THREAD

**Issue by Gasan918** [slowtorta/turtlewow-bug-tracker#1086]
**Please, provide a clear description what the bug is:**

Stormwind Guard corpse on the road not far from Notrhshire gate. He is always dead, <s>wrapped in plastic</s>, lying on the road at 47.2, 52.4.

If it is not some custom quest stuff, I think he must be fixed.

![image](https://user-images.githubusercontent.com/96973359/153275923-d9c49533-7d2d-4592-92d0-973c089846a4.png)

NPC: https://database.turtle-wow.org/?npc=1423

**Expected behavior. Describe how it should work:**

Guard must :

1) be alive
2) patrol the road from Goldshire to Northshire

Some Vanilla server:
![image](https://user-images.githubusercontent.com/96973359/153276218-b3aedca1-e945-4e0d-9171-a7901e162e5a.png)

**Comment by jameyboor** [comment]
Fixed on next update.
