### ISSUE TITLE
List of known faction change issues

### ISSUE THREAD

**Issue by slowtorta** [slowtorta/turtlewow-bug-tracker#1088]
After a race change faction reputations do not get adjusted properly. #419
After a race change between Alliance and Horde acquired flight paths get lost. #417
After a race change between Alliance and Horde not all mounts change to others faction equivalent. #416

**Comment by littletoads** [comment]
I have the resurection issue. 
I'm missing the friendly faction under other in reputation

![Screenshot (5)](https://user-images.githubusercontent.com/72800555/153669849-ff8d4f9a-361c-40c8-b497-5b2780ebadfa.png)
n

**Comment by Tinyfin-github** [comment]
> I have the resurection issue. I'm missing the friendly faction under other in reputation
> 
> ![Screenshot (5)](https://user-images.githubusercontent.com/72800555/153669849-ff8d4f9a-361c-40c8-b497-5b2780ebadfa.png) n

I forgot to fix this issue when i did your race change.
It's fixed now, you will be able to resurrect.
