### ISSUE TITLE
Rooted for 20s on login

### ISSUE THREAD

**Issue by imaglcian** [slowtorta/turtlewow-bug-tracker#109]
**Please, provide a clear description what the bug is:**
Whenever i login on my account, i get netted for 20s. I don't have the gnomish-net-o-matic projector equipped, but i also get rooted with it equipped.
**Steps to reproduce the behavior with as much detail as possible:**

1. Login
2. Logout
3. Login (very easy)

**Expected behavior. Describe how it should work:**
I should not get rooted on login.

**Proofs**
https://www.youtube.com/watch?v=Vj4f-umIWt8

**Comment by CosminPOP** [comment]
.unaura all
