### ISSUE TITLE
Skinning: Trainer learned too many ranks ( after re-learning this proff )

### ISSUE THREAD

**Issue by Borvaselin** [slowtorta/turtlewow-bug-tracker#1091]
**Please, provide a clear description what the bug is:**
while leveling i learned skinning, rerolled with lv60 and rerolled now again to skinning. teacher in OG learned me 3 Ranks at once ( as shown in pic ).
after reaching skill 70 the teacher didnt rank me up, so i skilled till 75 but nnothing happened then, nore in Skill.table or at teacher ( see pic )
**Steps to reproduce the behavior with as much detail as possible:**

1.
2. 
3.    ( idk )

**IDs of affected creatures, items, quests or spells with a link to the relevant page:**

NPC: https://database.turtle-wow.org/?npc=     all horde skinning trainers
Item: https://database.turtle-wow.org/?item=
Quest: https://database.turtle-wow.org/?quest=
Spell: https://database.turtle-wow.org/?spell=8617
Object: https://database.turtle-wow.org/?object=

**Expected behavior. Describe how it should work:**
get ability skinning Journeyman

Char: Vvn, lv60 Troll Hunter
![vvn1](https://user-images.githubusercontent.com/97921219/153505556-1fe2eb19-57fb-404f-a12c-d8b61e6055f5.jpg)
![vvn2](https://user-images.githubusercontent.com/97921219/153505576-20d4c030-bbc8-4126-8a4e-bd9c7ef9b42e.jpg)

**Comment by Borvaselin** [comment]
-closed -
solved, thx a lot !

**Comment by geojak** [comment]
I had a Similiar issue. That is the iron forge artisan engineer trainers recipes here somehow all with the expert trainer (by the gnomes)

**Comment by geojak** [comment]
My issue I also noticed only after I repeated the prffesion
