### ISSUE TITLE
Lua Error upon Login after WDB Deletion

### ISSUE THREAD

**Issue by AyleeJenn** [slowtorta/turtlewow-bug-tracker#1092]
**Please, provide a clear description what the bug is:**
I can only provide a screenshot of it since I am not sure I even understand what the error says exactly

![transmogerror](https://user-images.githubusercontent.com/87241085/153530981-11fd376e-a1d3-40e9-a091-8e054a6a03fb.jpg)

**Steps to reproduce the behavior with as much detail as possible:**

1. Delete the WBD Folder
2. Log into the game
3. Thats it

**IDs of affected creatures, items, quests or spells with a link to the relevant page:**

NPC: https://database.turtle-wow.org/?npc=
Item: https://database.turtle-wow.org/?item=
Quest: https://database.turtle-wow.org/?quest=
Spell: https://database.turtle-wow.org/?spell=
Object: https://database.turtle-wow.org/?object=

**Expected behavior. Describe how it should work:**
One would expect this error to not show up ... I know this isn't the usual level of detail on my bug reports but I am sorry that I can't be more helpful on this one.

**Comment by slowtorta** [comment]
This will be fixed in the client patch 1.16.1!
