### ISSUE TITLE
Judgement of Light involuntarily flags hardcore characters for PvP

### ISSUE THREAD

**Issue by zomgits** [slowtorta/turtlewow-bug-tracker#1093]
**Please, provide a clear description what the bug is:**
If an unflagged HC paladin uses Judgement of Light on a mob, and that mob is attacked by a flagged friendly character, the paladin is flagged, even though they took no action.

**Steps to reproduce the behavior with as much detail as possible:**

1. Make a hardcore mode paladin with Judgement of Light and same faction character.
2. Flag the second character for PvP.
3. Use the paladin to place Judgement of Light on a mob.
4. Attack the mob with the other character.
5. Paladin is now flagged for PvP and can be killed.

**IDs of affected creatures, items, quests or spells with a link to the relevant page:**

Spell: https://database.turtle-wow.org/?spell=20185

**Expected behavior. Describe how it should work:**
Hardcore characters should only be flagged when they take a deliberate action. That should be directly using an ability on another character, not through indirect effects such as campfires or AoE *or debuffs*.

**Comment by zomgits** [comment]
Note: This also works in reverse.  A flagged paladin can flag *anyone else* with judgement of light.  It even works on target dummies in towns.

**Comment by Velite12** [comment]
Semantically, the healing produced by Judgement of Light on vmangos core belongs to the _paladin_ not the player who activated it like classic. So technically the paladin healed that player hence they get flagged. I think this is the cause of the behavior.

**Comment by Velite12** [comment]
This is why on Vmangos based servers, when posting healing logs, the healing from judgement of light shows up under that paladin's healing. And consequently, the _**Threat**_ produced goes to the paladin, not the person who triggered it.

**Comment by slowtorta** [comment]
Fixed 08/24/2022.
