### ISSUE TITLE
Druid: Ferocious Bite uses all energy instead of 35.

### ISSUE THREAD

**Issue by Alvanosa-code** [slowtorta/turtlewow-bug-tracker#1094]
**Please, provide a clear description what the bug is:**
When using Ferocious Bite as a finisher it uses all energy you have at the moment instead of the 35 indicated by the Tooltip.

**Steps to reproduce the behavior with as much detail as possible:**

1. Level a Druid until level 32 for Ferocious Bite.
2. Be feral specced:
![image](https://user-images.githubusercontent.com/59435761/153706438-6152010a-fa8e-46e9-9e9c-508160b179ef.png)
3. Get combo points on the mob and wait until the energy bar is full, use Ferocious Bite.

**IDs of affected creatures, items, quests or spells with a link to the relevant page:**
Spell: https://database.turtle-wow.org/?spell=22568

**Expected behavior. Describe how it should work:**
The Ferocious Bite should use 35 energy instead of all energy as indicated on the tooltip:
![image](https://user-images.githubusercontent.com/59435761/153706482-b2d3291c-e6c4-41ce-af40-620f6635b783.png)

**Comment by Rakura1** [comment]
There is no bug here. If you have 35 energy for the base cost the spell can actrivate. If you have 100 energy ie full bar then 65 energy is then converted into additonal damage. Working as intended.
