### ISSUE TITLE
Sound issue: Sound not playing

### ISSUE THREAD

**Issue by AyleeJenn** [slowtorta/turtlewow-bug-tracker#1095]
**Please, provide a clear description what the bug is:**
The sound when cooking something no longer plays
**Steps to reproduce the behavior with as much detail as possible:**

1. get ingredients for any cooking recipe
2. activate the cooking process
3. hear no cooking sound

**IDs of affected creatures, items, quests or spells with a link to the relevant page:**

NPC: https://database.turtle-wow.org/?npc=
Item: https://database.turtle-wow.org/?item=
Quest: https://database.turtle-wow.org/?quest=
Spell: https://database.turtle-wow.org/?spell=
Object: https://database.turtle-wow.org/?object=

**Expected behavior. Describe how it should work:**
a cooking sound should play when you cook a recipe from the cooking secondary profession

**Comment by slowtorta** [comment]
Moving this issue to the internal tracker for client-related problems, thank you.
