### ISSUE TITLE
2 versions of Lieutenant Rotimer standing next to Ironforge Bank

### ISSUE THREAD

**Issue by IcemanHHW** [slowtorta/turtlewow-bug-tracker#1097]
**Please, provide a clear description what the bug is:**
There are 2 versions of Lieutenant Rotimer standing next to the Ironforge bank, both having a Quest mark over them as well, My WDB is empty so it doesn't seem to be caused by that.

**Steps to reproduce the behavior with as much detail as possible:**

1. Go to Ironforge on any character
2. Go to the Ironforge bank
3. 2 versions of Lieutenant Rotimer stand in front of the left pillar of the Ironforge Bank

**IDs of affected creatures, items, quests or spells with a link to the relevant page:**

NPC: https://database.turtle-wow.org/?npc=13843
Item: https://database.turtle-wow.org/?item=
Quest: https://database.turtle-wow.org/?quest=
Spell: https://database.turtle-wow.org/?spell=
Object: https://database.turtle-wow.org/?object=

**Expected behavior. Describe how it should work:**

Only one version of Lieutenant Rotimer existing in the world.
![Screenshot_82](https://user-images.githubusercontent.com/20383130/153715396-7c53b3df-a67e-4eff-983e-4b116110232d.png)

**Comment by slowtorta** [comment]
Thanks, fixed :)
