### ISSUE TITLE
Quest Grand Herbal Theft doesn't clearly say where to turn it in

### ISSUE THREAD

**Issue by zomgits** [slowtorta/turtlewow-bug-tracker#1098]
**Please, provide a clear description what the bug is:**
The quest "Grand Herbal Theft" says to turn it in to Shagu, but not where Shagu is.

**IDs of affected creatures, items, quests or spells with a link to the relevant page:**

Quest: https://database.turtle-wow.org/?quest=40002

**Expected behavior. Describe how it should work:**
It could say " If ya do find da satchel, take it back to Shagu *in Bloodhoof Village* ..."

**Comment by slowtorta** [comment]
Thank you, it'll be fixed on the next server update :)
