### ISSUE TITLE
Quest: Race Against Time!  is bugged

### ISSUE THREAD

**Issue by Gitaccount095** [slowtorta/turtlewow-bug-tracker#11]
By opening this Issue, I admit to having done the pertinent research using sources from Vanilla (preferably) or Classic. I also understand that sources from other private servers are not acceptable.

**Current behavior**: 

**Expected behavior**: 

**Proofs**:

**Steps to reproduce**:

1. Upon being able to actually move after the countdown, the player moves at a very slow speed, which seems to be fixed when picking up a speed boost on the track.
2. The player should be moving at a faster speed than what it currently is before obtaining a speed boost power-up.
3. The bugged slow speed is immediately apparent upon movement.
4. Simply right-click Daisy and begin the quest. The bugged speed will present itself upon movement.
5. The Gnome vs Goblin race likely also suffers this from this bug.

**Comment by fuzzytrick** [comment]
Hey, I'd like to add to this:

1. You gain a normal and regular speed whether you pick a speed boost up, or crash into a sheep/crystal. Also, the boost ability does not seem to have any effect on this speed while at the very beginning.
2. The quest is on a timer, and the countdown does not stop after actually completing the race, but runs until you turn the quest in. This way, if you have completed the race in the designated timeframe, and do not turn in the quest before the clock turns 0, the quest is failed. There were many occasions where I had finished the race, but had 3-4 seconds to turn the quest in, which I could not do.

**Comment by slowtorta** [comment]
Thanks for reporting it. Missing speed bonus bug on the race start has been fixed. The timer is working as intended. You have to reach the NPC before it runs off, it is how all timed quests work in Vanilla. It's absolutely doable and the quest is just hard by its design. Good luck!
