### ISSUE TITLE
Fiery Plate Gauntlets, Storm Gauntlets - Do not proc Vengeance as intended in Classic WoW (Possibly for the T2 Bonus aswell)

### ISSUE THREAD

**Issue by gmarguelles** [slowtorta/turtlewow-bug-tracker#1100]
**Please, provide a clear description what the bug is:**
The fire proc from Fiery plate gauntlets is not activating vengeance as it should
I do not have storm gauntlets so i cannot test it with them but its safe to assume it is not going to proc it
(Same might be true for 8/8 judgment paladin tier set proc)

**Steps to reproduce the behavior with as much detail as possible:**

1. Equip fiery plate gauntlets
2. Pick up vengeance talent
3. Attack until these items crit
4. Items will crit but not proc vengeance

**IDs of affected creatures, items, quests or spells with a link to the relevant page:**

NPC: https://database.turtle-wow.org/?npc=
Item: https://database.turtle-wow.org/?item=
Quest: https://database.turtle-wow.org/?quest=
Spell: https://database.turtle-wow.org/?spell=
Object: https://database.turtle-wow.org/?object=

**Expected behavior. Describe how it should work:**

In classic warcraft these items proc the paladin ability vengeance, I have video proof from classic wow linked below:

https://drive.google.com/file/d/1vb5ts0uMxUdWl_-2mgRUYp2fb-qsnUbj/view?usp=sharing

https://drive.google.com/file/d/1-akeAvEpftm5g6iAvejs6hJXB-u8mUrH/view?usp=sharing

Bug might be because these triggers might not be considered spells for some reason within the TurtleWoW server, is this something that can be fixed? These items open up a new avenue and itemization options for ret paladins and protection paladins.

Thank you!

**Comment by theloras** [comment]
likewise enginering grenade dmg crits are also not triggering Vengeance either - I would assume Crystal Charge from Ungoro Crater and Stratholme Holy Water are probably in the same boat

**Comment by jameyboor** [comment]
Fixed on next restart.

**Comment by theloras** [comment]
@jameyboor - will the fix also affect grenade crits triggering vengeance as well?

**Comment by NickTyrer** [comment]
@jameyboor how did you manage to fix this?
