### ISSUE TITLE
Gubber Blump won't teach Fishing or sell Fishing Pole and Shiny Bauble

### ISSUE THREAD

**Issue by s1lver1us** [slowtorta/turtlewow-bug-tracker#1102]
Gubber Blump has no conversation options to teach Fishing if you have not learned it yet or to sell Fishing Pole and Shiny Bauble after accepting the quest "The Family and the Fishing Pole"

I have tried to delete WDB and restart client each time before and after accepting the quest but the options still do not appear.

**IDs**
NPC (Gubber Blump): https://database.turtle-wow.org/?npc=10216
Item 1 (Fishing Pole): https://database.turtle-wow.org/?item=6256
Item 2 (Shiny Bauble): https://database.turtle-wow.org/?item=6529
Quest (The Family and the Fishing Pole): https://database.turtle-wow.org/?quest=1141
Spell (Apprentice Fishing): https://database.turtle-wow.org/?spell=7733

**Expected behavior**
Upon accepting the quest "The Family and the Fishing Pole" Gubber Blump should have conversation options to teach you fishing for free if you have not learned it yet by casting (Apprentice Fishing): https://database.turtle-wow.org/?spell=7733 on the player ("Gubber, I don't know how to fish".) and to open his vendor to buy Fishing Pole and Shiny Bauble ("Gubber, I don't have a fishing pole").

**WoW Classic reference video**: https://www.youtube.com/watch?v=qEoPX5r3weM

![WoWScrnShot_021322_125905](https://user-images.githubusercontent.com/99420301/153740103-a2441ebb-e454-4c61-9c33-e84cb25e536d.jpg)

**Comment by slowtorta** [comment]
Have you tried completing this quest first?

**Comment by zomgits** [comment]
I have bought poles and lures from Gubber.  Is LazyPig skipping his vendor dialog?

**Comment by s1lver1us** [comment]
**> Have you tried completing this quest first?**
The quest requires the player to fish Darkshore Grouper, if the player already has the fishing profession learned, the conversation option ("Gubber, I don't know how to fish".) will not appear but the vendor conversation option ("Gubber, I don't have a fishing pole") will.
WoW Classic video reference 1: https://www.youtube.com/watch?v=HQuab8X0JsY
WoW Classic video reference 2: https://www.youtube.com/watch?v=SnHcPWTsWmo
WoW Classic video reference 3: https://youtu.be/KGTPBBoOywA?t=85

**> I have bought poles and lures from Gubber. Is LazyPig skipping his vendor dialog?**
I'm not using LazyPig addon but just to be 100% sure, I disabled all addons, closed WoW client and deleted WDB folder. I followed these steps once before and a second time after accepting the quest. The issue still persists I'm afraid.

**Comment by zomgits** [comment]
I've just checked with my main character and I get the vendor dialog and can buy stuff.  Very odd!

**Comment by zomgits** [comment]
> > I've just checked with my main character and I get the vendor dialog and can buy stuff. Very odd!
> 
> Hmmm, could it be you have done his quest before the 1.16.0 update? I created my character after the update and I'm playing on hardcore mode.

No that's all the same.  I will try some other alts a bit later and see if I can reproduce the problem.

**Comment by s1lver1us** [comment]
I appreciate it ty:)

**Comment by slowtorta** [comment]
> The quest requires the player to fish Darkshore Grouper, if the player already has the fishing profession learned, the conversation option ("Gubber, I don't know how to fish".) will not appear but the vendor conversation option ("Gubber, I don't have a fishing pole") will. I should also clarify that I do not have the fishing profession learned yet.

This is an intentional change. Before, if the player already had Fishing Skill the first option could reset it to 0/75 again. See: https://github.com/slowtorta/turtlewow-bug-tracker/issues/348

Tested with the completed quest and no fishing skill:
![image](https://user-images.githubusercontent.com/66763404/153777730-eca6f879-07dc-4acf-95b8-1780e8b04b77.png)
Tested with the completed quest after learning Fishing Skill: 
![image](https://user-images.githubusercontent.com/66763404/153777752-9003ea65-a9a4-45af-86ad-e70193722d2b.png)

This is working as intended. There's no need to display a fishing supplies menu if player doesn't know how to fish.
