### ISSUE TITLE
Flying from Quel'Thalas Flight Path -> WPL, then embarking WPL -> SW sends back player flying through the world to Lights Hope.

### ISSUE THREAD

**Issue by tubtubs** [slowtorta/turtlewow-bug-tracker#1103]
**Please, provide a clear description what the bug is:**

**Steps to reproduce the behavior with as much detail as possible:**

1. Fly from Quel'Thalas to Western Plaguelands Chillwind Camp
2. Get off FP, maybe pick up something from Chromie
3.  Fly to Stormwind from Western Plaguelands Chillwind Camp
4. You will fly to Stormwind, but on arrival you will fly back through the world to Quel'Thalas, then to Lights Hope after glitching around for a bit.

This is with WDB freshly deleted, and I have been able to re-produce.

My character is a Human Paladin @lvl 60

**Expected behavior. Describe how it should work:**
Flying from Western Plaguelands Chillwind Camp to Stormwind should never fly the character back to Light's Hope Chapel.

**Comment by slowtorta** [comment]
Hello! Thank you for your report. This is fixed in Patch 1.16.1 (scheduled for release in the nearest future).
