### ISSUE TITLE
A Crew Under Fire cant not be completed

### ISSUE THREAD

**Issue by geojak** [slowtorta/turtlewow-bug-tracker#1104]
**Please, provide a clear description what the bug is:**

**Steps to reproduce the behavior with as much detail as possible:**

1. start the qeust
2. naga waves span, but with big gaps in between
3. quest never finished

**IDs of affected creatures, items, quests or spells with a link to the relevant page:**

https://database.turtle-wow.org/?quest=3382

**Expected behavior. Describe how it should work:**

some kind of reward or follow up quest and quest completable

the qeust also disapearrs from the log

**Comment by slowtorta** [comment]
Thank you, this will be fixed on the next server update.
![image](https://user-images.githubusercontent.com/66763404/153778568-85558a31-800d-47b0-8325-4033f37d4e90.png)
