### ISSUE TITLE
spinefin halibut recipe missing (not a bug)

### ISSUE THREAD

**Issue by geojak** [slowtorta/turtlewow-bug-tracker#1105]
**Please, provide a clear description what the bug is:**

the game has raw spinefin halibut and it has cooked spinefin halibut. you can fish them, some npcs drop cooked ones or raw ones. but no recipe exists for cooking.

this is the same in blizzard classic, but an oversight that would be nice if fixed in turtle

*
**IDs of affected creatures, items, quests or spells with a link to the relevant page:**

https://database.turtle-wow.org/?item=8957
https://database.turtle-wow.org/?item=8959

**Expected behavior. Describe how it should work:**

there shoudl be a cooking recipe for this

**Comment by slowtorta** [comment]
Sorry, got no free hands for this kind of task right now, nor probably in the visible future.
