### ISSUE TITLE
High Elf lvl 20 priest racial skill "Sun's Embrance" does not work

### ISSUE THREAD

**Issue by ThunderSunday** [slowtorta/turtlewow-bug-tracker#1106]
**Please, provide a clear description what the bug is:**

High Elf priests can learn their second racial spell on 20 lvl by purchasing the item Codex: Sun's Serenity (Rank 1).  This spell, "Sun's Embrance", has the following description:

![sun](https://user-images.githubusercontent.com/99614173/153771076-1e5b8bb4-22e8-4e7e-a42c-263d81edafa9.jpg)

Yet, after learning the spell and using it it does nothing, except going on cooldown and making character do "salute" animation. Spell costs stay exactly the same, tested both on Smite and Holy Fire. I could not find that spell in the database, npc and item ID's are provided below.

**Steps to reproduce the behavior with as much detail as possible:**

1. Level High Elf priest to lvl 20.
2. Purchase the item Codex: Sun's Serenity (Rank 1).
3. Cast Smite or Holy Fire on Target  Dummy or a mob. Observe the mana spent. Use the "Sun's Embrace" skill, cast Smite or Holy Fire and compare mana expenditure.

**IDs of affected creatures, items, quests or spells with a link to the relevant page:**

NPC: https://database.turtle-wow.org/?npc=80966
Item: https://database.turtle-wow.org/?item=81008

**Expected behavior. Describe how it should work:**

After using the skill, for 20 seconds or next five casts, mana cost of Smite, Holy Fire and Holy Nova should be decreased by the amount in spell's description.

**Comment by slowtorta** [comment]
Hello there :) It will be fixed in Patch 1.16.1!
