### ISSUE TITLE
An Infinite Hunt bugs

### ISSUE THREAD

**Issue by Tinyfin-github** [slowtorta/turtlewow-bug-tracker#1107]
An Infinite Hunt bugs 

https://database.turtle-wow.org/?quest=80411

Objective is not completed in the quest log even if you can complete the quest it at Chromie
Chromie turns into a dragon  but does not attack

https://streamable.com/zwl4al

**Comment by Neto-WoW** [comment]
Fix pushed. As for Kephri can you make sure this NPC has mana? Its working as intended on my local.
