### ISSUE TITLE
ungro devilsauers no stomping sound

### ISSUE THREAD

**Issue by geojak** [slowtorta/turtlewow-bug-tracker#1108]
**Please, provide a clear description what the bug is:**

the giant devilsaurs of ungro should make a stomping sounds, they are currentlz sneaking upon plaers in silence

**Expected behavior. Describe how it should work:**

similair to the bugged kodos in desolacne, these mobs should be heard from far away

**Comment by slowtorta** [comment]
Moved to the internal bug-tracer for client-related issues.

**Comment by geojak** [comment]
i just watched this video from classic https://www.youtube.com/watch?v=HADqwoixub8.
mazbe no stomping sound is blizzlike and mz memorz is wrong. srz for that

**Comment by slowtorta** [comment]
> i just watched this video from classic https://www.youtube.com/watch?v=HADqwoixub8. mazbe no stomping sound is blizzlike and mz memorz is wrong. srz for that

No, not really. We got a big problem with sounds in general in the updated client, no solution yet.
