### ISSUE TITLE
Twin Emperor's in AQ40 revive after being killed

### ISSUE THREAD

**Issue by Durisbane** [slowtorta/turtlewow-bug-tracker#1109]
**Please, provide a clear description what the bug is:**
when you kill the twin emperors in AQ40 they sometimes revive themselves and start attacking the raid again
**Steps to reproduce the behavior with as much detail as possible:**

1. go into AQ40
2. Kill Twin Emperors
3. They respawns and start attacking again

**IDs of affected creatures, items, quests or spells with a link to the relevant page:**

NPC:
https://database.turtle-wow.org/?npc=15276
https://database.turtle-wow.org/?npc=15275

**Expected behavior. Describe how it should work:**
when they die they should not come back to life

video evidence:
https://www.youtube.com/watch?v=pcsfzah4seU

**Comment by geojak** [comment]
Wasn't that the gimmick of them. They revive unless you kill them at the almost exact same time.

**Comment by slowtorta** [comment]
The only issues I see are the moving corpses, which shouldn't be the case.

**Comment by CosminPOP** [comment]
> Wasn't that the gimmick of them. They revive unless you kill them at the almost exact same time.

no, they share hp, the gimmick is that they heal if they are too close

**Comment by Velite12** [comment]
I recall before that when one died the other died as well even if it had full hp, but it seems to not be the case here, the other one is still alive for some reason. Maybe the method to keep the hp % equal failed? which is why the corpse was still active.

**Comment by OrnsteinHunter** [comment]
every single week this is happening now, its wiping our entire raid group and theres nothing we can do about it.

**Comment by Lunkdunk** [comment]
It has happened quite a lot since the new expansion. Several times only vek'lor fully died, then we had to wipe and kill veknilash once again from full health. Another time both bugged out, so when we wiped both came close to each other and healed to full.

**Comment by CosminPOP** [comment]
should be fixed next restart
