### ISSUE TITLE
Isalien t0.5 summon boss will duplicate add on wipe

### ISSUE THREAD

**Issue by Zebouski** [slowtorta/turtlewow-bug-tracker#1111]
**Please, provide a clear description what the bug is:**
When a party wipes on this boss, you will end up with 2 adds instead of one, which ensures defeat. forces the team to reset the instance and lose all that progress.

**Steps to reproduce the behavior with as much detail as possible:**

1. Summon Isalien in dire maul east, after the satyr boss
2. Let her summon the hyppogryph, then wipe to her
3. Pull the boss again
4. Notice that Isalien will summon a second hyppogryph

**IDs of affected creatures, items, quests or spells with a link to the relevant page:**

NPC: https://database.turtle-wow.org/?npc=16097

**Expected behavior. Describe how it should work:**
When the party wipes, the add should be scripted to despawn, that'd fix it

**Comment by redmagejoe** [comment]
Is is true that the NPC will summon a second instance of https://database.turtle-wow.org/?npc=16098 even while the first one is alive. If would be best to do a check for creature count > 0 and prevent spawning if this returns true.

**Comment by ratkosrb** [comment]
https://github.com/slowtorta/turtle-wow/commit/42f26fb1f455120e2431d64efcd94eb5a7d8ce43
