### ISSUE TITLE
Skinning Bug

### ISSUE THREAD

**Issue by Domagorr** [slowtorta/turtlewow-bug-tracker#1112]
Hi i am a lvl 37 orc hunter , and i have skinning as a profession.
When my pet alone kills a mob (i dont hit a mob at all) i skin the mob but i dont get any leather.

This is a minor bug and its not game breaking but it would be nice if it can be fixed.

**Comment by TrangOul** [comment]
To clarify: the bug is that skinning is possible, not that there is on drop. Otherwise hunters could AFK farm leather, by allowing their pets to kill mobs and just skin the corpses.

**Comment by zomgits** [comment]
This is intentional.  If your pet alone kills a mob, you don't gain anything: no experience, no loot. It is so that you can't AFK farm with your pet.

**Comment by slowtorta** [comment]
That's correct, this is a normal Vanilla WoW skinning behavior.
