### ISSUE TITLE
Quest says to shoo sharks but shooing them doesn't work

### ISSUE THREAD

**Issue by zomgits** [slowtorta/turtlewow-bug-tracker#1113]
**Please, provide a clear description what the bug is:**
The quest Sharks Are Friends, Not Food says:
>Do you see that dorsal fin rising out of the water? That's a shark. It appears to have come too close to the shoreline which is an anomaly for this species. I'm a marine biologist by trade and I've been watching that poor creature for a while now. There could be a number of reasons that it's trapped here, but the goblins want to kill it like a stuck pig! They think it's a threat to people in the water, but it's probably just scared and confused. I can't let that happen. I need you to go into the water and shoo the shark away. 

1. The shark you must deal with is the one that *does not* have a dorsal fin above the water.  There *are* sharks that have dorsal fins, but they are the baby sharks.  This is misleading.
2. If you go in to the water and shoo sharks with /shoo, nothing happens.
3. The quest goal says "Scare the shark away" but scaring the shark with any fear spell (e.g. Scare Beast) also does not work.

In fact, you must right click sharks deep in the water and talk to them.

**IDs of affected creatures, items, quests or spells with a link to the relevant page:**

NPC: https://database.turtle-wow.org/?npc=81006
Quest: https://database.turtle-wow.org/?quest=80383

**Expected behavior. Describe how it should work:**
1. If a quest says to shoo a shark, then shooing the shark should work.
2. If a quest says to look for a shark with a dorsal fin above the water, then its dorsal fin should be above the water, especially if *other* sharks *do* have that, and are not the right sharks.
3. If a quest says to scare a shark, then scaring a shark with Scare Beast should work.
4. If a quest requires you to right click a shark, it could say something like "interact with" or "pet" or something that does not misleadingly refer to other abilities like "/shoo" or Scare Beast.

**Comment by slowtorta** [comment]
Thank you, it's a great idea :) Let's change it to work this way. 🦈

**Comment by slowtorta** [comment]
Fixed on the next server update.
