### ISSUE TITLE
Can't transmog one handed sword with one handed swords categorized as 'main hand'

### ISSUE THREAD

**Issue by inxdigo** [slowtorta/turtlewow-bug-tracker#1116]
I'm not able to transmog any one handed swords with looks from one handed swords categorized as 'main hand' instead of 'one hand'. Not sure if this is intended or a bug. 
The look doesn't show up in the transmog menu when attempting to transmog my one-handed sword.

Example: can't transmog Vanquisher's Sword as Viking Sword.

**Comment by slowtorta** [comment]
This is an intentional limitation by the feature's design. There's an ongoing discussion about it on our forum so it's a subject of a change: https://forum.turtle-wow.org/viewtopic.php?f=14&t=2618
