### ISSUE TITLE
Bengus Deepforge teaches two Steel Plate Helm items

### ISSUE THREAD

**Issue by Gasan918** [slowtorta/turtlewow-bug-tracker#1117]
**Please, provide a clear description what the bug is:**

Bengus Deepforge, Artisan Blacksmith in Ironforge, teaches to make:

1. Vanilla **Steel Plate Helm** (id=7922)
2. Custom content **Steel Plate Helm** (id=83415), which is a part of custom Steel Plate set.

![image](https://user-images.githubusercontent.com/96973359/154124405-31476a30-47e4-4afa-b6a1-cc5e90876338.png)

NPC: https://database.turtle-wow.org/?npc=4258
Item: https://database.turtle-wow.org/?item=7922, 83415

**Expected behavior. Describe how it should work:**

I  suggest renaming custom item into Steel Plate Barbute. Or maybe it's better to rename a whole set into something like "Hardened Steel" or "Alloy Steel" or "Ironforge Steel" or "Dwarven Steel". Or "Deepforge Steel". Only Deepforge blacksmith clan owns the secret of this set.

**Comment by slowtorta** [comment]
Moving this issue to the internal tracker for the client-related problems.
