### ISSUE TITLE
[Rogue] Abilties excluding damage-dealing ones are incapable of proccing weapon effects (Sap, Gouge, Crusader/Lifesteal/Icy Chill, Shadow Oil and more)

### ISSUE THREAD

**Issue by imaglcian** [slowtorta/turtlewow-bug-tracker#1118]
**Please, provide a clear description what the bug is:**
Sap/Cheap Shot/Kidney Shot/Gouge is unable to proc poisons, crusader, lifesteal or other like-minded effects (only the initial auto-attacks can). Re-opened this ticket as it got closed/re-opened and closed again without any further comments regarding this issue.
https://www.youtube.com/watch?v=F_0Xh5IH-Cg - Tested without Improved Poisons talent, with 3-piece T2 (5% poison proc chance)

**Steps to reproduce the behavior with as much detail as possible:**

1. Apply crippling poison (or any other passive poison to test)
2. Sap a target until you can get poisons to proc off from mentioned abilities
3. Bug fixed.

**IDs of affected creatures, items, quests or spells with a link to the relevant page:**

Item : https://database.turtle-wow.org/?item=3776
Spell(s) : https://database.turtle-wow.org/?spell=20007

**Expected behavior. Describe how it should work:**
Sap and other similar abilities (The ones mentioned above specifically) should be able to proc poisons/enchanting effects/other weapon enchants.

**Proofs:**
All from WoW Classic.
https://youtu.be/kf04RPqMml4?t=55
https://youtu.be/cwtxj-ubudw?t=43
https://youtu.be/xTa9WTGCGaI?t=53
https://youtu.be/xTa9WTGCGaI?t=139
https://youtu.be/8Gy8bydO_Hw?t=11
https://youtu.be/DhWRkCvWovI?t=774

**Comment by redmagejoe** [comment]
I am not doubting authenticity of this behavior, but I must question the wisdom of being able to apply a damage poison on Sap... Is it perhaps only certain poisons which can be applied by these abilities, or all poisons?

**Comment by imaglcian** [comment]
Any weapon effect that isn't harmful, should be able to be proceed off of
sap as far as I recall. Wound Poison/Crippling Poison for example.

Den tors. 23. feb. 2023 kl. 12.52 skrev redmagejoe ***@***.***
