### ISSUE TITLE
Blademaster's Blindfold helm isn't adding +5 polearms on character skill window

### ISSUE THREAD

**Issue by theloras** [slowtorta/turtlewow-bug-tracker#1119]
It would appear that the following head armor item hasn't had the +5 polearms added to it in the database:

Blademaster's Blindfold
Binds when picked up
Head    Leather
147 Armor
+9 Agility
+15 Stamina
Durability 60 / 60
Requires Level 60
Equip: Improves your chance to get a critical strike by 1%.
https://database.turtle-wow.org/?item=60414

In addition to the stats above from the turtle db, in game it also has +5 polearm but it isn't showing up for my Paladin - he remains 300/300 polearms

i cleared my wdb already - one thing - the tooltip for the helm in game says "Polearm" whereas in the Skills window it says "POLEARMS" plural
could it be as simple as that?

the odd thing with the helm though is that the DB is missing the +5 polearms in the stats listed so it could be a compounded issue
both in game with the plural and in the db itself with the missing stat as it isn't listed

**Comment by slowtorta** [comment]
Thank you, it'll be fixed on the next update!
