### ISSUE TITLE
Hazzuri Scavengers classified as beasts

### ISSUE THREAD

**Issue by Aeliren** [slowtorta/turtlewow-bug-tracker#1120]
The Hazzuri Scavengers from Lapidis Isle are classified as beasts when they're clearly trolls and should be humanoids.

![image](https://user-images.githubusercontent.com/96898927/154168729-f46bccf6-9700-426e-afa2-feef47b31729.png)
![image](https://user-images.githubusercontent.com/96898927/154168736-7110b90c-3fa2-4443-b43d-a31264b5d4c2.png)

**IDs of affected creatures, items, quests or spells with a link to the relevant page:**

NPC: https://database.turtle-wow.org/?npc=91824

**Comment by Kruxis** [comment]
Thanks for the report!
