### ISSUE TITLE
Love in the air event Kwee Q. Peddlefeet is not receiving  gift collection

### ISSUE THREAD

**Issue by Tinyfin-github** [slowtorta/turtlewow-bug-tracker#1121]
Love in the air event- Kwee Q. Peddlefeet is not receiving  gift collection

https://database.turtle-wow.org/?npc=16075#starts Kwee Q. Peddlefeet 

![image](https://user-images.githubusercontent.com/83077166/154222527-afc4463e-3bb3-49ab-9b82-11b9ffc1c8ae.png)

**Comment by geojak** [comment]
another bug. if you /kiss the goblin he should give a +200 hp buff i read somewhere
