### ISSUE TITLE
Shaman clearcasting no longer procs since yesterday's patch

### ISSUE THREAD

**Issue by Prooks55** [slowtorta/turtlewow-bug-tracker#1122]
Title.

I'm an ele shaman with the clearcasting talent allocated, and have not gotten a clearcasting proc since the server restarted. I raided for a few hours last night and did some questing this morning, so I believe this to be statistically significant.

I noticed the issue titled "Elemental focus is not triggering on spell cast but spell land #166" had some activity recently. Is this related?

**Comment by Velite12** [comment]
![image](https://user-images.githubusercontent.com/45871932/154379533-5901d2f1-2f8c-4ef5-a0d9-5c1e41b70d91.png)
Casted 100+ casts and 0 Clearcasting procs

**Comment by snakemansreal** [comment]
Likely redundant but I can also confirm (anecdotally) that I haven't seen a Clearcasting proc since Tuesday night. Feels super bad; I OOM'd a _lot_ to begin with but this just makes me not even want to log onto my shaman anymore :C

**Comment by slowtorta** [comment]
Fixed on the next update.
