### ISSUE TITLE
Finding the source (ungoro quest)

### ISSUE THREAD

**Issue by geojak** [slowtorta/turtlewow-bug-tracker#1124]
**Please, provide a clear description what the bug is:**

this quest isnt exatly blizzlike.

**Steps to reproduce the behavior with as much detail as possible:**

1. go to any of the hot measuring points and use the tool
2. and turtle wow it will finish
3. it will also not display the yellow text messaure how hot the temperaure was measured

**IDs of affected creatures, items, quests or spells with a link to the relevant page:**

https://database.turtle-wow.org/?quest=974

**Expected behavior. Describe how it should work:**

each point should have a different temperatue and a few different flavour messages
but only the one at the top next to the elite in the cave should be the hottest and finish the qeust

https://www.youtube.com/watch?v=ZLaHxrqGHaw

**Comment by slowtorta** [comment]
Fixed on the next update.
