### ISSUE TITLE
Time-Worn Rune - not working

### ISSUE THREAD

**Issue by dole555** [slowtorta/turtlewow-bug-tracker#1127]
**Please, provide a clear description what the bug is:**

The Time-Worn Rune to teleport to Caverns of Time is not working.
Since last update it now needs Rune of Teleportation to be used.
Clicked item, it used a rune of teleportation, started the 20min cooldown, it went from "5 charges" to "4 charges" but it didn't teleport me anywhere

**Steps to reproduce the behavior with as much detail as possible:**

1. Get Time-Worn Rune.
2. Get Rune of Teleportation.
3. Use TIme-Worn Rune.

**IDs of affected creatures, items, quests or spells with a link to the relevant page:**

Item: https://database.turtle-wow.org/?item=61000
Item: https://database.turtle-wow.org/?item=17031

**Expected behavior. Describe how it should work:**
Using TIme-Worn Rune should teleport you to Caverns of Time.

**Comment by slowtorta** [comment]
It'll be fixed in 1.16.1
