### ISSUE TITLE
wavetreasher scale qeust item drops without the qeust

### ISSUE THREAD

**Issue by geojak** [slowtorta/turtlewow-bug-tracker#1129]
**Please, provide a clear description what the bug is:**

the wavetrasher in azahara drop a qeust item even when zou dont have the qeust for it

**Steps to reproduce the behavior with as much detail as possible:**

1. go to azahara
2. kill wavetrashers around the tower of eldara
3. loot scales (quest item)
4. dont even have the quest for it

**IDs of affected creatures, items, quests or spells with a link to the relevant page:**

https://database.turtle-wow.org/?item=20087

**Expected behavior. Describe how it should work:**

quest items should only drop when on the quest

**Comment by Kruxis** [comment]
Thanks for the report,

fix will be applied on next server restart =)
