### ISSUE TITLE
Midsummer

### ISSUE THREAD

**Issue by Maug666** [slowtorta/turtlewow-bug-tracker#113]
*the event seems not to work. On my night elf I cant click fires of oppisite faction and cant recive quests of my faction*

**Steps to reproduce the behavior with as much detail as possible:**

1.take a character and attempt to interact with a fire of oppsite faction
2. Try to revive quest from your faction
3. 

**IDs of affected creatures, items, quests or spells with a link to the relevant page:**

NPC: https://database.turtle-wow.org/?npc=
Item: https://database.turtle-wow.org/?item=
Quest: https://database.turtle-wow.org/?quest=
Spell: https://database.turtle-wow.org/?spell=
Object: https://database.turtle-wow.org/?object=

**Expected behavior. Describe how it should work:**
Oppisite factions should be prompted to be put out and same faction should be promoted with a quest giver

**Comment by Nolin7777** [comment]
Hello and thank you for your report!

Please add any evidence in form of a legit source (for example wowhead.com) or a video captured from Blizzard's Classic server.

This ticket will be closed until more information added.
