### ISSUE TITLE
Database query limit too low to show class skills

### ISSUE THREAD

**Issue by zomgits** [slowtorta/turtlewow-bug-tracker#1132]
**Please, provide a clear description what the bug is:**
The database web site only shows 300 results from queries.  This isn't enough to show all the skills from classes.  For example, it only shows hunter skills up to level 40, see https://database.turtle-wow.org/?spells=7.3#250+2+1

**Steps to reproduce the behavior with as much detail as possible:**

1. Try to look up all hunter skills.

**Expected behavior. Describe how it should work:**
I'd expect to be able to look up class skills.

Thanks!

**Comment by slowtorta** [comment]
Will be fixed on the next website update.
