### ISSUE TITLE
Gug Fatcandle in Undead Stratholme

### ISSUE THREAD

**Issue by norgigorgi** [slowtorta/turtlewow-bug-tracker#1133]
**Please, provide a clear description what the bug is:**

The last two runs of Undead Stratholme, once Baron Rivendare has been killed, an invisible and non-targetable "Gug Fatcandle" begins attacking the group. This makes it impossible to hearth for the character being attacked and the group remains in combat.

**Steps to reproduce the behavior with as much detail as possible:**

Tried to leave the instance and come back inside. The NPC immediately re-enters combat with players.

**IDs of affected creatures, items, quests or spells with a link to the relevant page:**

NPC: https://classic.wowhead.com/npc=62/gug-fatcandle

**Comment by Prooks55** [comment]
I believe this invisible NPC may spawn during the fight, not after it. Or it may simply live in Rivendare's room. 
During the fight the healer receives aggro and keeps it after Rivendare dies. As a shaman I was able to eventually kill it with Lightning Shield and a lucky fire totem that was able to target it somehow. A group with any sort of thorns, ret aura, horde priest racials etc. might be able to replicate this result. (pets on aggressive might path to him?)

I realize my post is completely unhelpful to you, but wanted to share anyway.

**Comment by Kruxis** [comment]
Greetings! 

Thanks for the report but we couldn't reproduce the bug.
Might be a 1 : 100000 hickup :D 

Save Travels!

**Comment by slowtorta** [comment]
It happened to me as well once, but I don't know how it gets there. This NPC isn't supposed to be in Vanilla anyway, so I'll just delete it altogether.

**Comment by Kruxis** [comment]
Fixed.

Should not attack players anymore upon next server restart!
