### ISSUE TITLE
Shatterspear Trolls are non Hostile toward alliance. Faction not found.

### ISSUE THREAD

**Issue by Zeebler** [slowtorta/turtlewow-bug-tracker#1134]
**Please, provide a clear description what the bug is:**

Shatterspear trolls in Shatterspear Vale is a popular AOE spot for mages on alliance. They appear friendly on turtle wow and I'm unable to kill them as an alliance toon. Shatterspear Trolls faction does not appear in reputation list. They have a loot table that appears on the database but no other information about this NPC. The friendly behavior is not blizz-like and unexpected.

**Steps to reproduce the behavior with as much detail as possible:**

1. Go to Shatterspear Vale. Located in Darkshort (68.4, 22.7)
2. Roll alliance.
3. Attempt to attack.

**IDs of affected creatures, items, quests or spells with a link to the relevant page:**

NPC: https://database.turtle-wow.org/?npc=10919
Faction: https://database.turtle-wow.org/?faction=629
Wowhead Link: https://classic.wowhead.com/faction=629/shatterspear-trolls
Wowhead Link: https://classic.wowhead.com/npc=10919/shatterspear-troll

**Expected behavior. Describe how it should work:**

Shatterspear trolls should be hostile to alliance.
![image](https://user-images.githubusercontent.com/26336411/154826908-f09b106a-8850-469d-869f-3b1c5126d751.png)
![image](https://user-images.githubusercontent.com/26336411/154826918-e433bf53-5f79-45e8-8637-4537a02cabc4.png)
![image](https://user-images.githubusercontent.com/26336411/154826922-2d4e2f37-3e32-4944-8dee-c1b1b8e8e3fb.png)
![image](https://user-images.githubusercontent.com/26336411/154826929-fa5e9580-d27c-44bc-8350-70a82a5db368.png)

**Comment by slowtorta** [comment]
This change is intentional and they're friendly to everyone because there's a guild house located in this village.
