### ISSUE TITLE
script event missing after handing in bloodpetal sprouts qeust

### ISSUE THREAD

**Issue by geojak** [slowtorta/turtlewow-bug-tracker#1136]
**Please, provide a clear description what the bug is:**

upon handing in the alliance quest Bloodpetal Sprouts to muigin, a little event should take place. muigin release a horde of bloodpetal pests and they kill lariot. on twow nothing happens

dont confuse this quest with the 15 repetable qeust on the kodo

**Steps to reproduce the behavior with as much detail as possible:**

1. hand in bloodpetal sprouts quest
2. wait for the event
3. nothing happens

**IDs of affected creatures, items, quests or spells with a link to the relevant page:**

https://database.turtle-wow.org/?quest=4144

**Expected behavior. Describe how it should work:**

scripted event should take place. unfortunelty its hard to find video material of it

**Comment by Nolin7777** [comment]
Hello and thank you for your report!

For comparison please add any evidence in form of a legit source (for example wowhead.com) or a video captured from Blizzard's Classic server.

This ticket will be closed until more information added.

**Comment by geojak** [comment]
If have searched intesivlry the interent. 
There is no footage of it.
I guess still will have to stay broken

**Comment by geojak** [comment]
But if rly find it bad practice to just close it. Not like the unblizzlike missing script gets fixed if we pretend it's not there. But you are the devs

**Comment by Nolin7777** [comment]
We cannot script an event without knowing how the event looks like at all, sorry.

**Comment by geojak** [comment]
I fully understand that. It's a big problem. But closing the issues is like pretending it doesn't exist or it's fixed. That's just not the case. The problem exists, we just can't fix it at the moment doesn't mean it's not there

**Comment by geojak** [comment]
When I made this issue I searched the Internet for over an hour. I guess we will only solve this if someone went on a Blizzard server purposely to record. Which is unlikely to happen, for a lvl 50 quest that requires a longer chain and altar hakkar dungeon. :(

**Comment by slowtorta** [comment]
Alright, let's not be upset about it :) It would be enough to have a text description of this event from someone who's playing retail Classic.

**Comment by geojak** [comment]
actually my dad play thb classic. I will ask him if he has competed the quest on his main. If not next time I visit him I can take his 70 on a trip to sunken temple and record thisml

Thank you for reopening!

**Comment by NickTyrer** [comment]
When I checked on classic Muigin was releasing the Bloodpetal Pests every 5 mins. I scripted this into Muigin's EventAI in vMangos, I am unsure however if completing the quest triggers the event.

**Comment by geojak** [comment]
I think he should release them every 5 minutes, but only on quest completion he should release the stronger hakkar haze uodrsded ones that actually manage to kill larion

**Comment by NickTyrer** [comment]
I have scripted the event here https://github.com/vmangos/core/pull/1467,

**Comment by slowtorta** [comment]
> I have scripted the event here [vmangos/core#1467](https://github.com/vmangos/core/pull/1467),

Great news, thank you for sharing!

**Comment by slowtorta** [comment]
> I have scripted the event here [vmangos/core#1467](https://github.com/vmangos/core/pull/1467),

I applied it on TW and there is one problem with those plants that I noticed: they will not despawn and will be endlessly stuck at the endpoint.

**Comment by geojak** [comment]
Thank you guys and girls for working on this <3

**Comment by slowtorta** [comment]
Thanks, will be in-game on the next update!
