### ISSUE TITLE
Stormwind Guard don't patrol road from SW to Goldshire

### ISSUE THREAD

**Issue by Gasan918** [slowtorta/turtlewow-bug-tracker#1137]
**Please, provide a clear description what the bug is:**

NPC is not patrolling, just standing.

**Steps to reproduce the behavior with as much detail as possible:**

1. Get to (35.3, 53.7)

**IDs of affected creatures, items, quests or spells with a link to the relevant page:**

NPC: https://database.turtle-wow.org/?npc=1423

**Expected behavior. Describe how it should work:**

Guard must patrol road from (42.1, 64.6) to (32.5, 50.1)

**Comment by Kruxis** [comment]
Greetings, 

Thanks for the report, fix will be applied on next restart.
