### ISSUE TITLE
Tauren druids lose mana on level up between level 1 and 2

### ISSUE THREAD

**Issue by Tinyfin-github** [slowtorta/turtlewow-bug-tracker#1139]
![WoW_YM7HahbdYB](https://user-images.githubusercontent.com/83077166/154861463-a831daa9-f9ca-4aaa-8df2-bb54e4a5d7de.png)
![WoW_Ws40TgFcpW](https://user-images.githubusercontent.com/83077166/154861466-d52643b3-71cb-4552-8ded-bb4e83ce6c6e.png)

**Comment by Velite12** [comment]
https://github.com/slowtorta/turtlewow-bug-tracker/issues/270

![image](https://user-images.githubusercontent.com/45871932/155002177-c368a438-ce4a-47e3-8192-9b3ce2aa32a3.png)


the starting mana should be 67

**Comment by Velite12** [comment]
Something is wrong with the intellect to mana calculation then. Or the way this was fixed.

**Comment by slowtorta** [comment]
Base values (int/str/agi for each level) aren't 'calculated' on mangos, those are static values. We're missing a proper source for those sadly.

**Comment by Velite12** [comment]
![image](https://user-images.githubusercontent.com/45871932/155856865-e9bf50dd-7558-46a7-a87b-d7041c8a954a.png)
![image](https://user-images.githubusercontent.com/45871932/155856891-2b661924-9110-4e7f-8d55-6bbec14781ab.png)
@slowtorta  Season of Mastery level 1 stats
Try these to see if you get the correct mana value.

**Comment by slowtorta** [comment]
That won't help me. I need data for every level :(
