### ISSUE TITLE
 Quest items for Arcane Arms  : Crystal of the Serpent and Everchanging Essence don't have a 100% drop rate

### ISSUE THREAD

**Issue by Tinyfin-github** [slowtorta/turtlewow-bug-tracker#114]
Quest items for Arcane Arms  : Crystal of the Serpent and Everchanging Essence don't have a 100% drop rate
https://database.turtle-wow.org/?quest=80312- Arcane arms custom turtle wow quest.
 
 The quest items from  the  wailing caverns bosses are shown to have 100% drop rate in the database
 But they don't drop every time. 
https://database.turtle-wow.org/?item=80864 -   Everchanging Essence
https://database.turtle-wow.org/?item=80863 -  Crystal of the Serpent

**Comment by slowtorta** [comment]
Sorry, I'm unable to reproduce it.

**Comment by Tinyfin-github** [comment]
Issue persists
