### ISSUE TITLE
Blackshackle Bracers unable to be repaired

### ISSUE THREAD

**Issue by snakemansreal** [slowtorta/turtlewow-bug-tracker#1141]
**Please, provide a clear description what the bug is:**
Been running the custom Turtle item Blackshackle Bracers on my ele/enh shaman for a couple of weeks now - just noticed today that I cannot actually repair them. With the length of time I've been using them they likely have been repaired, but it seems that this past reset has hecked something and they can't actually be repaired anymore. I've tried multiple vendors (Kaja in Orgrimmar and two of my guildies' repair bots) to no avail. Have tried deleting WDB since the issue cropped up but it doesn't seem to have fixed anything.

video -- https://youtu.be/DYA4vzB6j2c

**Steps to reproduce the behavior with as much detail as possible:**

1. Kill Blademaster Kargron
2. Pry Blackshackle Bracers from his corpse
3. Wear Blackshackle Bracers until they break
4. Try and fail to repair Blackshackle Bracers

**IDs of affected creatures, items, quests or spells with a link to the relevant page:**
Item: https://database.turtle-wow.org/?item=81368

**Expected behavior. Describe how it should work:**
They should not stay at 0/40 durability when you try to repair them

**Comment by Kruxis** [comment]
Fixed, will be applied on next restart =)

**Comment by Kruxis** [comment]
Fixed, will be applied on next restart =)
