### ISSUE TITLE
Tiara of the Deep can only be looted by one player

### ISSUE THREAD

**Issue by SaxxonPike** [slowtorta/turtlewow-bug-tracker#1143]
**Please, provide a clear description what the bug is:**

Killing Hydromancer Velratha results in a lootable Tiara of the Deep quest item. However, the tiara can only be looted by one person. Afterwards, it is not lootable by anyone else.

**Steps to reproduce the behavior with as much detail as possible:**

1. Enter ZF with two people who have the Tiara of the Deep quest.
2. Clear the instance to Hydromancer Velratha and kill her.
3. Attempt to loot the tiara on both characters.

**IDs of affected creatures, items, quests or spells with a link to the relevant page:**

NPC: https://database.turtle-wow.org/?npc=7795
Item: https://database.turtle-wow.org/?item=9234
Quest: https://database.turtle-wow.org/?quest=2846

**Expected behavior. Describe how it should work:**

Tiara of the Deep should be lootable by everyone who has the quest.

**Comment by slowtorta** [comment]
Will be fixed on the next update, thank you.
