### ISSUE TITLE
mechanical dragonling issues

### ISSUE THREAD

**Issue by geojak** [slowtorta/turtlewow-bug-tracker#1144]
**Please, provide a clear description what the bug is:**

there are 3 mechanical dragonlings crafted by engineers in the game.
i have crafted the mitrhil and basic version and noted some problems

note i am lvl 57 and got engineering 300

**Steps to reproduce the behavior with as much detail as possible:**

1. summon the basic mechanical dragonling
2. obesrvere it has over 3000 hp and deals around 9-10 dmg against the glassweb spiders  in searing gourge
3. summon the meithril dragonling
4. observe it got only around 500 hp and deals 7 damage against the same spiders
5. also observe the mithril dragonling doesnt use its fire abilities (basic version has no abilitties)

**IDs of affected creatures, items, quests or spells with a link to the relevant page:**

https://database.turtle-wow.org/?search=dragonling#npcs

**Expected behavior. Describe how it should work:**

the mithril dragonling is supposed to be an upgrade

https://classic.wowhead.com/npc=8615/mithril-dragonling
https://classic.wowhead.com/npc=2678/mechanical-dragonling
https://classic.wowhead.com/npc=12473/arcanite-dragonling

**Comment by Khanz0** [comment]
Just noticed that. My arcanite dragonling dies MUCH faster than my regular one

**Comment by geojak** [comment]
i crafted the arcanite one today, it deals a lot more damage and also sues a fire spell, comapred to the mithril one with just sucks and doesnt use the fire spell it should have

**Comment by redmagejoe** [comment]
These creatures are still broken.

**Comment by Giperion** [comment]
@geojak 
What is mechanical dragonling HP suppose to be?

**Comment by Giperion** [comment]
Msg to QA: Resolved, but the true HP of Mechanical Dragonling is still a mystery

**Comment by twowTurtReynolds** [comment]
@Giperion 
![image](https://github.com/slowtorta/turtlewow-bug-tracker/assets/151180101/b7f45a5e-c2e6-4e0a-873c-e2f315b0bedd)
Latest vmangos has it at 1HP

**Comment by twowTurtReynolds** [comment]
We will be deviating from blizzlike on this.

> Mechanical Dragonling pet HP changed from 3184 to 400
> Mithril Dragonling damage is increased to 41, and now he casts "Flame Breath" from time to time
> Arcanite Dragonling damage is slightly increased to 71
