### ISSUE TITLE
Freedom for All Creatures - Captured spirit darter don't move

### ISSUE THREAD

**Issue by Tinyfin-github** [slowtorta/turtlewow-bug-tracker#1145]
Freedom for All Creatures  https://database.turtle-wow.org/?quest=2969 - Captured spirit darter https://database.turtle-wow.org/?npc=7997  don't move  

![WoW_srmKSG3rd1](https://user-images.githubusercontent.com/83077166/155013165-75bf76b8-c654-4f57-a128-dcadfff43ccc.jpg)

**Comment by geojak** [comment]
they moved when i did the qeust a few weeks ago

**Comment by slowtorta** [comment]
Couldn't reproduce, works well for me...

**Comment by geojak** [comment]
maybe tiny meant the ones inside the cave dont move? pre releasing them

**Comment by Kruxis** [comment]
Also couldn't reproduce.

**Comment by Tinyfin-github** [comment]
Issue persists.
