### ISSUE TITLE
Taunt should work through banish

### ISSUE THREAD

**Issue by Zebouski** [slowtorta/turtlewow-bug-tracker#1148]
**Please, provide a clear description what the bug is:**
Currently, mobs are immune to taunt when banished.

**Steps to reproduce the behavior with as much detail as possible:**

1. Banish an elemental
2. Try to taunt it as druid or war
3. See that it says Immune

**IDs of affected creatures, items, quests or spells with a link to the relevant page:**

NPC: https://database.turtle-wow.org/?npc=12076

**Expected behavior. Describe how it should work:**
On classic, banished mobs can be tauned (druid and war single and aoe taunts. not mocking blow)

The only time this is important, is when it's really important: the molten core Lava Elementals will do a cone aoe stun, that is nearly always faced towards the casters as healers pull heal threat. If you can taunt before banish ends, this ensures the mob faces away from the raid, and is a way for more attentive tanks to show their skill and strongly help the raid on these pulls. Especially on the 1.12 client, where we don't have accurate banish debuff timers, a team where the warlock coordinates in chat or voice when it's going to break, and the tank that taunts at the right time, should be rewarded. Currently it's just RNG whether all will go well and is more about the tank's internet connection than their attentiveness/execution of the pull.

**Comment by jameyboor** [comment]
Fixed on next update.
