### ISSUE TITLE
Quest Lard Lost His Lunch is bugged.

### ISSUE THREAD

**Issue by SierraNairn** [slowtorta/turtlewow-bug-tracker#115]
Quest Lard Lost His Lunch is bugged
https://database.turtle-wow.org/?quest=7840
Quest sends you to find a item, The item drops from trolls you summon at a location by clicking  a object on the ground. It was supossed to be clickable once.
You can  click the item multiple times and it will spawn 3 mobs each time . The mobs don't despawn after a time.

**Comment by slowtorta** [comment]
Thanks for reporting it. It'll be fixed on the next server restart. Make sure to clear your WDB folder.
