### ISSUE TITLE
Unreachable Iron Deposit in Arathi Highlands just South of Farwell Stead

### ISSUE THREAD

**Issue by tubtubs** [slowtorta/turtlewow-bug-tracker#1150]
**Please, provide a clear description what the bug is:**
There is an iron Deposit in Arathi that appears to be under the ground near the start of the land ramp heading up to Farwell Stead.

The iron deposit in question is around 31.3 18.2. See screenshots for more positional information.

![image](https://user-images.githubusercontent.com/96892771/155176955-11a51b38-6717-4c77-a4d4-7feecc2f455b.png)
![image](https://user-images.githubusercontent.com/96892771/155176987-2eafdde7-bba8-44ae-a38a-95674ba841cf.png)

**IDs of affected creatures, items, quests or spells with a link to the relevant page:**
Object: https://database.turtle-wow.org/?object=1735

**Comment by Shellyoung** [comment]
The deposit is still unreachable in 28.07.2022. The issue is not fixed.
