### ISSUE TITLE
Unreachable mitrhil deposit at the dark portal

### ISSUE THREAD

**Issue by geojak** [slowtorta/turtlewow-bug-tracker#1158]
**Please, provide a clear description what the bug is:**
 cords are 57.5 52.3.

**Expected behavior. Describe how it should work:**
 should be above ground

**Comment by slowtorta** [comment]
Please post a screenshot of a minimap for us to locate it. I don't have this coord addon.

**Comment by geojak** [comment]
sure can d
![WoWScrnShot_022322_225552](https://user-images.githubusercontent.com/25199983/155427476-cdf0fca9-6958-41dc-beb8-94de49b732ff.jpg)
o
![WoWScrnShot_022322_225555](https://user-images.githubusercontent.com/25199983/155427490-4511d06e-741b-409b-84b5-c12b2db75aa4.jpg)

**Comment by geojak** [comment]
Another mithril span is extremely close to this one, that one I could harvest, be a bit careful to remove/edir the right one in dB
