### ISSUE TITLE
wrong label on hellcaler diadem

### ISSUE THREAD

**Issue by geojak** [slowtorta/turtlewow-bug-tracker#1160]
**Please, provide a clear description what the bug is:**

this headpiece is not tagged as cloth as it should

**Steps to reproduce the behavior with as much detail as possible:**

1. put the hellcaler diadem in the ah
2. go to mischeanchilosu headpiece in ah
3. its listed there and not under cloth

**IDs of affected creatures, items, quests or spells with a link to the relevant page:**

https://database.turtle-wow.org/?item=80833

**Expected behavior. Describe how it should work:**

should be listed under cloth in the ah

**Comment by Kruxis** [comment]
Greetings,

Thanks for the report! Will be fixed on next server restart =)
