### ISSUE TITLE
rethban ore cant be mined from nodes inside the cave

### ISSUE THREAD

**Issue by geojak** [slowtorta/turtlewow-bug-tracker#1161]
**Please, provide a clear description what the bug is:**

rethban ore in redridge mountain drops from gnoll dredgers. additionally it should be possbile to get the ore faster by mining copper and tin vains inside the cave. in twow this does not work

**Steps to reproduce the behavior with as much detail as possible:**

1. go insdie the cave in redridge mountain that has the rethab ore gnolls
2.  mine vains
3. dont get rethban ore

**IDs of affected creatures, items, quests or spells with a link to the relevant page:**

all copper and tin vains inside the cave
https://database.turtle-wow.org/?item=2798

**Expected behavior. Describe how it should work:**

https://classic.wowhead.com/item=2798/rethban-ore#mined-from-object

according to the twow db some tin vains are suppoed to drop it (i could not verify this) accroding wowhead the copper should drop it too thought

**Comment by slowtorta** [comment]
Will be fixed on the next update.
