### ISSUE TITLE
Smoked Sage Fish does not regenerate health only mana

### ISSUE THREAD

**Issue by Domagorr** [slowtorta/turtlewow-bug-tracker#1163]
Hi , i use Smoke Sage Fish bcs i am warlock and its a pretty good food for my class , and since yesterday , for some reason , smoked sage fish doesnt regenerate health only mana.

I know its a minor bug , but the more bugs are fixed , the server is better. Idk if this is only happening to my character.

Here are some pics to back this up:
![bug](https://user-images.githubusercontent.com/99244485/155837208-9bca1085-9775-424f-b14e-211884f06575.png)
![bug2](https://user-images.githubusercontent.com/99244485/155837214-a4ce674e-4483-4fc0-b4db-12e34441e8b6.png)

**Comment by geojak** [comment]
Report all the bugs you find, even the minor ones.  The more reports the better.

**Comment by slowtorta** [comment]
Thank you, it'll be fixed on the next update. 
![image](https://user-images.githubusercontent.com/66763404/159126420-b523a1ad-0f56-47ea-a249-73f1b9ca33a8.png)
