### ISSUE TITLE
wrong sign in menethil harbor

### ISSUE THREAD

**Issue by geojak** [slowtorta/turtlewow-bug-tracker#1164]
**Please, provide a clear description what the bug is:**

on menethil is a wrong label. i have reported this befor, but its not fixed. see picture below.

**Steps to reproduce the behavior with as much detail as possible:**

1. delete wdb
2.  check the sign
3. still says auberdine even thought there is no boat anymore for allaicne

**IDs of affected creatures, items, quests or spells with a link to the relevant page:**
![WoWScrnShot_022622_111139(1)](https://user-images.githubusercontent.com/25199983/155839318-59313171-1b31-4429-b105-b45e0bb94e8f.jpg)

**Expected behavior. Describe how it should work:**

i would hope for a new boat route, since alliance got the short end of the stick by far with all the new connections horde got while allaicne just moved one to an arguably worse location.

how about connect menethil and southshore like fethermaon boat, so no zooning. this would help alliance lowbies to reach shadow fang keep and scarlet monastery when going to southsore the first time.

would help alliacne low leveling alot to ecourage going especially to sfk.

anyway remove the wrong sign information atleast, or replace the text with (unused)

**Comment by slowtorta** [comment]
Sorry, the boat routes are too tedious to make and I don't plan to get back to it any time soon. The sign will be removed on the next server update :)
