### ISSUE TITLE
Lvl1s getting endgame trinkets

### ISSUE THREAD

**Issue by Deekinbc** [slowtorta/turtlewow-bug-tracker#1165]
**Please, provide a clear description what the bug is:**
Seal of the Dawn and equivalent are both available to a lvl1 character if they make it to Eastern Plaguelands. Very overpowered items.
**Steps to reproduce the behavior with as much detail as possible:**

1. Take a character to Light's Hope Chapel
2. Take the two trinkets by talking to the gnome
3. 

**IDs of affected creatures, items, quests or spells with a link to the relevant page:**

NPC: https://database.turtle-wow.org/?npc=
Item: https://database.turtle-wow.org/?item=13209
Quest: https://database.turtle-wow.org/?quest=
Spell: https://database.turtle-wow.org/?spell=
Object: https://database.turtle-wow.org/?object=

**Expected behavior. Describe how it should work:**
Should only be a reward from long quest chain.

**Comment by geojak** [comment]
I think you need revered reputation  for these or atleasz honored, maybe that's not working here?

**Comment by jameyboor** [comment]
Fixed on next restart.
