### ISSUE TITLE
Defence not listing/working properly

### ISSUE THREAD

**Issue by vladzag** [slowtorta/turtlewow-bug-tracker#1167]
Please, provide a clear description what the bug is:
My character is a prot paladin with 5/5 Anticipation.
My character though has just 295/305 points in defence and I can't level the skill in any way (I'm 65% at 59 so definitely should have received a few hits).
If I equip an item that provided defence skill I get 295(+5)/305 skill. I'm not sure if I get any bonus from that, but the ingame calc tells me that I get 0.2% more dodge, parry etc

IDs of affected creatures, items, quests or spells with a link to the relevant page:

NPC: https://database.turtle-wow.org/?npc=]
Item: https://database.turtle-wow.org/?item=
Quest: https://database.turtle-wow.org/?quest=
Spell: https://database.turtle-wow.org/?spell=20100
Object: https://database.turtle-wow.org/?object=

Expected behavior. Describe how it should work:

Should increase and get increased by taking talents&taking hits.
You can check screenshots [here](https://drive.google.com/drive/folders/1l8gfBxS61GORAZgQHx5gPaLOIgHeNOae?usp=sharing)

Thanks!

**Comment by geojak** [comment]
I have the same problem on my lvl 60 pala

**Comment by Nolin7777** [comment]
https://github.com/slowtorta/turtlewow-bug-tracker/issues/708
