### ISSUE TITLE
shaman bugs (reincarnation and elemental focus)

### ISSUE THREAD

**Issue by turtlewow123** [slowtorta/turtlewow-bug-tracker#1168]
elemental focus does not procc at all.

shaman reincarnation doesnt work in AV or in BRD. there is no option to revive via reincarnation, but the spell is placed on cool down and an ankh (reagent) is consumed when you revive at the spirit healer in AV, reagent is not consumed when riviving through the dungeon portal in BRD

Spell: https://database.turtle-wow.org/?spell=16164
Spell: https://database.turtle-wow.org/?spell=21169

**Expected behavior. Describe how it should work:**

elemental focus should proc 10% of the time after casting a nature, frost or fire spell as per tool tip.

you should be able to rivive using reincarnation in every death scenario

thanks for the great server!

**Comment by jameyboor** [comment]
![afbeelding](https://user-images.githubusercontent.com/1365563/156244055-39e288c3-9715-4038-8629-1041c1017863.png)

Reincarnation seems to work fine in BGs, AV here.

We're looking into Elemental Focus.

**Comment by Prooks55** [comment]
I know this is going to sound rude, but what exactly is the complication behind Elemental Focus? Is it not as simple as undoing whatever was done in the patch on 2/15? It still doesn't seem to be fixed as of today's restart and waiting another two weeks is going to be frustrating. Is there anything at all we can do to help?

**Comment by turtlewow123** [comment]
hi,

not rude at all, i appreciate the questions. elemental focus does not procc, essentially making dmg spells 10% more expensive than they would be with the talent (over a long period of time with many casts). i havent been playing on your server for a long time (couple of weeks) so i am only familiar with the current patch. my knowledge of programming is very simple so i dont know how much work this is; but reducing the cost of lightning ball and chain lightning by 10 % (effectively taking the 10% rng out of elemental focus).

"Gives you a 10% chance to enter a Clearcasting state after casting any Fire, Frost, or Nature damage spell.  The Clearcasting state reduces the mana cost of your next damage spell by 100%."

the removal of the rng is a bit of a buff, so having it only effect lightning ball and chain lightning would make it more balanced; also in pve those are usually the only spells an elemental shaman will cast.

if this solution isnt acceptable id be happy to brainstorm some more ideas given parameters. i have played a lot of shaman in classic, tbc and wotlk and consider myself to a bit of an expert in the class mechanics. im more than happy to provide feedback or answer any questions you may have.

thank you for reaching out with your questions and your diligent work on the server
if i can be of any assistance, please dont hesistate to ask

all the best and hoping you are safe

swishy
________________________________

**Comment by Velite12** [comment]
> I know this is going to sound rude, but what exactly is the complication behind Elemental Focus? Is it not as simple as undoing whatever was done in the patch on 2/15? It still doesn't seem to be fixed as of today's restart and waiting another two weeks is going to be frustrating. Is there anything at all we can do to help?

The complication is that turtle wow imported commits from vmangos, and even though everything works fine on vmangos it doesn't on turtle wow, so this is an issue in their code's end.

**Comment by jameyboor** [comment]
Fixed on next update.
