### ISSUE TITLE
Searing Gorge Quest [Suntara Stones] Part 1 Escort Quest Spawning and Pathfinding Issue

### ISSUE THREAD

**Issue by Zhohan** [slowtorta/turtlewow-bug-tracker#117]
The escort quest mob Dorius Stonetender instead of spawning at the Grimesilt Dig Site, spawns at the location the quest is meant to be completed next to the dwarven gate. His pathfinding also seems off, he went straight over hills and ignored terrain height.

1. Start quest Suntara Stones at improper location.
2. Dorius pathfinding wonky to location the quest is meant to be picked up from.
3. No signs of NPC that is meant to kill him for the second part of the quest.

NPC: https://database.turtle-wow.org/?npc=8284
Quest: https://database.turtle-wow.org/?quest=3367

https://youtu.be/s8qTBCDPJIU
Video above shows Classic WoW Blizzard scripting. Dorius starts quest at digsite then runs to the hills. There are moments where he catches his breath and is ambushed by mobs. He gets close to gate before he is slain by a sniper, which allows the player to interact with object for the second part of Suntara Stones.

**Comment by Zhohan** [comment]
After submitting this bug report, I noticed he has now respawned in his correct location. I tested the quest a second time. The quest worked near-perfectly. There was some NPC dialogue missing, but the quest worked properly. I think sometimes it bugs out with his spawning.

**Comment by redmagejoe** [comment]
Requesting this be reopened, as most of the issues with this quest apparent on almost every server and indicated in this report persist.

1. The singed letter is already on the ground before Dorius drops dead.
2. The Dark Iron Sniper never appears to shoot Dorius.
3. Dialogue is missing as indicated in links above.
4. Dorius spends a long time (~10 seconds) at the point where the first ambush wave appears before anything happens, in dead silence.
