### ISSUE TITLE
Riverpaw Gnolls drop 30+ items

### ISSUE THREAD

**Issue by Gasan918** [slowtorta/turtlewow-bug-tracker#1170]
**Please, provide a clear description what the bug is:**

11-12 lvl Riverpaw Gnolls drop 30+ grey and white items. One item per ~100 gnolls. Please check drop list. Please check Riverpaw Scouts and Shamans also.

![image](https://user-images.githubusercontent.com/96973359/155892851-5f318165-9f5a-430d-94d7-f378e1369c48.png)
![image](https://user-images.githubusercontent.com/96973359/155892880-65231573-b914-44e3-a86f-74036fd7cd34.png)
![image](https://user-images.githubusercontent.com/96973359/155892936-4fb4ecbe-5565-4c43-bc2c-b4548a4b8a1e.png)

**IDs of affected creatures, items, quests or spells with a link to the relevant page:**

NPC: https://database.turtle-wow.org/?npc=117

**Comment by geojak** [comment]
i once got a lvl 35ish grey 2h in a chest from wailing cavers. nice money o nthat level. felt also out of place thought

**Comment by slowtorta** [comment]
Thank you, it'll be fixed on the next update.
