### ISSUE TITLE
Talent Does not work properly (Divine Intellect) - Paladin

### ISSUE THREAD

**Issue by Mordrux** [slowtorta/turtlewow-bug-tracker#1172]
Hello, i am level 12, i get one point to Divine Intellect and mana cap doesn't increased, i get seccond point, Mana Increased, i get third point 3/5, Mana Cap Doesn't increased mana before 479/479, after 479/479. On High Level can be problem when this talent does not work properly.

Please Fix This .. Thank You

(Sorry for miss on chat, i learn english from Movie/Games Only)

TY

**Comment by geojak** [comment]
maybe you got so little int at your low level that 2% more or less didnt give you an extra int so no change.

**Comment by Mordrux** [comment]
> maybe you got so little int at your low level that 2% more or less didnt give you an extra int so no change.

FIrst Point dont give me Mana Cap increase, Second give me mana Cap increase and third point dont give Mana Cap increase ? Nah

**Comment by Mordrux** [comment]
I dont have money for reset talents and try again for more tests.

**Comment by geojak** [comment]
Might be  rounding thing

**Comment by jameyboor** [comment]
As Geojak described. This is due to rounding. You'll see it having more effect once you acquire more intellect.
