### ISSUE TITLE
swim speed gear doesnt stack

### ISSUE THREAD

**Issue by geojak** [slowtorta/turtlewow-bug-tracker#1173]
**Please, provide a clear description what the bug is:**

the vanilla azure silk belt gives 15% swimspeed
the turtle swim spee trinket rethress tide crest gives 15% swimmspeed
i was told their is also a custom turtle boot with swim speed but couldnt find in on the db

**Steps to reproduce the behavior with as much detail as possible:**

1. equipt azure silk belt and tide cresr
2. equip only one of these on another char
3. race against each other in swimming
4. find out they are same speed

**IDs of affected creatures, items, quests or spells with a link to the relevant page:**
https://database.turtle-wow.org/?item=40061
https://database.turtle-wow.org/?item=7052

**Expected behavior. Describe how it should work:**

they should stack, else, whats the point of these? or should they not?
carrot and mithril spurs also stack
this makes me qeustion ff carrot and custom goblin car key really stacks or not

**Comment by Zebouski** [comment]
I confirmed with the belt and boots a while ago, yep those 2 don't stack either.

**Comment by Khanz0** [comment]
I can confirm. Got +45 (3 items) and dont stack. I made a suggestion

**Comment by Khanz0** [comment]
Got today the last item i missed. +60 bonus swim speed and none stack

**Comment by Iacov** [comment]
Bump
https://database.turtle-wow.org/?spell=8747
6) Apply Aura #58: Mod Speed Swim
Value: 15
Aura modifier is identical, root of problem is it overwriting itself.

Please Look into it.

Cheers,

**Comment by Iacov** [comment]
Is there a problem with the speed Aura @slowtorta ? Or is this more of a decision to make.

**Comment by geojak** [comment]
@ratkosrb may I ask what is the conclusion?
No changes or stacking?

**Comment by slowtorta** [comment]
Stacking :)
