### ISSUE TITLE
Hitting Call Anathema or Call Benediction, will wipe the xmog of the weapon

### ISSUE THREAD

**Issue by Zebouski** [slowtorta/turtlewow-bug-tracker#1174]
**Please, provide a clear description what the bug is:**
Right clicking your benediction or anathema will transform the weapon, but when transformed back, the xmog is gone completely, and youi'll have to spend another token to get it back.

I assume other similar weapons like thunderstrike, have the same problem, but I haven't checked

**Steps to reproduce the behavior with as much detail as possible:**

1. xmog benediction
2. equip and right clikc the weapon
3. wait 30 mins
4. right click the weapon again
5. see benediction no longer xmog'd

**IDs of affected creatures, items, quests or spells with a link to the relevant page:**

Item: https://database.turtle-wow.org/?item=18608

**Expected behavior. Describe how it should work:**
Benediction should have one xmog, and anathema its own. Both should keep their xmog retained even when switching between them

Or, could just have 1 xmog for both, like how you get 1 enchant that will transfer between both.

**Comment by slowtorta** [comment]
Sorry, we cannot fix it.
