### ISSUE TITLE
Curse of Thorns from hillsbrad syndicate does too much damage 

### ISSUE THREAD

**Issue by Kangaroux** [slowtorta/turtlewow-bug-tracker#1175]
https://database.turtle-wow.org/?npc=2244
https://database.turtle-wow.org/?spell=16247

![image](https://user-images.githubusercontent.com/2302541/156101840-04b4d019-1a31-4810-b4f2-94c605b5718e.png)
![image](https://user-images.githubusercontent.com/2302541/156101669-14df45c9-6132-4765-a839-791d6e87f53e.png)
![image](https://user-images.githubusercontent.com/2302541/156101687-2ffe60ea-3c97-4232-b739-ecded9b19a68.png)

**Comment by Kangaroux** [comment]
My assumption is that it's scaling up the damage based on my level, not the caster's level. The tooltip shows the correct scaled damage from the caster.

**Comment by Nolin7777** [comment]
Hi and thank you for the ticket!

Just for clarification, some spells (not all) are influenced by coefficients and other scalings, this can lead to deviations which doesn't match with the given tooltip at the end. Comparing the tooltip with the actual values, I'd say it still falls in admissible limits. Hence, not a bug.

Please don't hesitate to report any bugs in the future!
