### ISSUE TITLE
Jailor Marlgen perma-nets, uses ranged attack

### ISSUE THREAD

**Issue by Kangaroux** [slowtorta/turtlewow-bug-tracker#1176]
https://database.turtle-wow.org/?npc=2428

This NPC nets you for ~10s and will only wait 1s before throwing another net once the previous one wears off.

This wouldn't be too terrible if not for the fact that he is ranged. The only way to kill him as melee is to maybe get a hit in between nets, otherwise you better have a ranged weapon.

**Comment by jameyboor** [comment]
Fixed upon next restart.
