### ISSUE TITLE
In Service of the Lightnot available

### ISSUE THREAD

**Issue by geojak** [slowtorta/turtlewow-bug-tracker#1177]
**Please, provide a clear description what the bug is:**

the qeust In Service of the Light in suppoedly available from thomas, but there is nothing here. no preqeust should be requirred either

**Steps to reproduce the behavior with as much detail as possible:**

1. be lvl 60
2. go to thomas in the cathedral
3. no qeust

**IDs of affected creatures, items, quests or spells with a link to the relevant page:**

https://database.turtle-wow.org/?npc=4982
https://database.turtle-wow.org/?quest=50300

**Expected behavior. Describe how it should work:**

qeust should be offered

**Comment by slowtorta** [comment]
This quest was meant to be removed from the game. This is an intentional change.

**Comment by geojak** [comment]
Ah OK, I didn't know that. Someone on discord mentioned the quests and the dB seemed like it should be offered. Thx for clarifying
