### ISSUE TITLE
Some bosses are part of an incorrect class of armor value

### ISSUE THREAD

**Issue by Velite12** [slowtorta/turtlewow-bug-tracker#1178]
**Please, provide a clear description what the bug is:**

As a result of the discovery that bosses in turtle wow had TBC armor values, a compromise was made to lower the values, between the values of Classic and the Previous values. However, some of those previous values were not the actual TBC values, and were artificially created.

The TBC armor values we had previously were taken from the 2008 Bestiary. However, there is no third armor class like what we have here, so I am led to believe this was an imaginary class of armor created.

**IDs of affected creatures, items, quests or spells with a link to the relevant page:**

https://database.turtle-wow.org/?npc=15928
https://database.turtle-wow.org/?npc=16011
https://database.turtle-wow.org/?npc=16028

**Expected behavior. Describe how it should work:**

![image](https://user-images.githubusercontent.com/45871932/156279577-3b25ae54-0485-4c77-b8e7-e1a706b454b2.png)
The values of armor from classic. As you can see, Loatheb, Patchwerk and Thaddius share the same class of armor as everyone but Kel'Thuzad

![image](https://user-images.githubusercontent.com/45871932/156281624-4900951b-4a03-4e7a-937a-4589d604218d.png)
![image](https://user-images.githubusercontent.com/45871932/156279769-0484eaa6-5021-4784-82f9-e029955b12d4.png)
![image](https://user-images.githubusercontent.com/45871932/156279787-1ac76439-ae06-465b-b810-439dd586e4db.png)
![image](https://user-images.githubusercontent.com/45871932/156279989-38df9680-c73b-4f95-900e-4e91f37274d1.png)

As you can see here, in the bestiary, all 3 of these bosses were part of the same class as razuvious' armor value in TBC.

![image](https://user-images.githubusercontent.com/45871932/156280071-996ada40-377d-47c7-b895-0775dd579781.png)
![image](https://user-images.githubusercontent.com/45871932/156280148-29624472-5544-41e8-bf94-503eda6af0e3.png)

However, on Turtle they currently exist in a separate, higher armor class.

**Comment by CosminPOP** [comment]
Current values are intended and we plan to keep them this way.
