### ISSUE TITLE
Kebok Visual Bug

### ISSUE THREAD

**Issue by Strongbone101** [slowtorta/turtlewow-bug-tracker#118]
Kebok, a Goblin Quest Giver in Ratchet, will sometimes disappear depending on what angle you're looking at him.

**Steps to reproduce the behavior with as much detail as possible:**

1. Look at Kebok.
2. If you see him, turn and he will disappear
3. If you don't see him, turn and he will appear

**IDs of affected creatures, items, quests or spells with a link to the relevant page:**

NPC: https://database.turtle-wow.org/?npc= 737

**Expected behavior. Describe how it should work:**
I don't think he should dissappear based on what angle you're looking at him from
![Now you don't](https://user-images.githubusercontent.com/85890157/123861387-1bcdee80-d8f5-11eb-8de8-aa90e87dd777.png)
![First you see him](https://user-images.githubusercontent.com/85890157/123861392-1c668500-d8f5-11eb-92d1-4ca0dd8fb9fc.png)

**Comment by slowtorta** [comment]
I tried jumping around, rotating my camera, looking at them from different angles, but could not reproduce this issue, sorry.
