### ISSUE TITLE
Animation issue with character 

### ISSUE THREAD

**Issue by Zkittyx3** [slowtorta/turtlewow-bug-tracker#1180]
The dryad illusion's bow animation has the bow in the wrong hand. so she pulls the bow back instead of the string, seems like it only needs to switch hands to be fixed.

![Screenshot_20220301-224715_File Viewer](https://user-images.githubusercontent.com/100822697/156498357-763fe101-23d6-46db-9cfd-dc700c3ca933.jpg)
#

**Comment by slowtorta** [comment]
Thank you. Moving this issues to the internal bug-tracker for client-related bugs.
