### ISSUE TITLE
High-elf (Female) priest tier 3 helm visual effects are broken!

### ISSUE THREAD

**Issue by Rammue** [slowtorta/turtlewow-bug-tracker#1181]
**Please, provide a clear description what the bug is:**

The high elf has broken effects when they wear priest t3, at least the women as I can't confirm if the men have this same issue.
When I wear my T3 helm the circlet appears to be up-side down! >.>
WDB has been deleted several times aswell!

**Steps to reproduce the behavior with as much detail as possible:**

1. Put circlet of faith on lady helf's head
2. ??????
3. Profit

**IDs of affected creatures, items, quests or spells with a link to the relevant page:**

Item: https://database.turtle-wow.org/?item=22514

**Expected behavior. Describe how it should work:**
The effects should flow upwards.
Provided is an image of the circlet in game on a helf versus how it is supposed to look on other races.

![259192](https://user-images.githubusercontent.com/97422687/156523503-b3b347c0-2141-4e1f-9a55-1c8b900dad9d.jpg)
![WoWScrnShot_030322_015240](https://user-images.githubusercontent.com/97422687/156523507-5dbc6e78-ed4b-42f5-aefb-4a86a10d43bd.png)

**Comment by slowtorta** [comment]
Thank you. I'm moving this one to the intern tracker for client-related bugs.
