### ISSUE TITLE
Aszhara quest " the storm bay mutiny" bugged

### ISSUE THREAD

**Issue by Khanz0** [slowtorta/turtlewow-bug-tracker#1182]
This custom quest in azhara is bugged
https://database.turtle-wow.org/?quest=40037
The quest requires kill 10 storm bay warrior https://database.turtle-wow.org/?npc=6371 and 10 storm bay oracle https://database.turtle-wow.org/?npc=6351

The quest cant be completed because no matter hiw many you kill you dont get any kill. The kills dont count

Could fix it? Its a chain quest with a cool reward and you cant complete it

**Comment by Tinyfin-github** [comment]
Greetings! Please clear your WDB folder while the game is closed.

![WoW_5n7UfchX3y](https://user-images.githubusercontent.com/83077166/156600295-ee10a618-a0c7-4a44-b1f7-01938cbbcd2c.png)

![WoW_wxV2i2UfZ9](https://user-images.githubusercontent.com/83077166/156600304-fca5cab3-ca99-4b1a-88fc-c37e34591466.jpg)

**Comment by Khanz0** [comment]
Tested again and fixed. Ty
