### ISSUE TITLE
Character Only Getting Rested XP From Tents

### ISSUE THREAD

**Issue by ZoSo3** [slowtorta/turtlewow-bug-tracker#1183]
My character does not gain rested XP while in cities and/or inns. However, if I get close to a tent, I become Rested and start accumulating the Rested bonus. WDB deletions have not worked.

To test this, I went to the Arena and got to maximum Rested, then proceeded to quest and level. Upon reaching my Normal XP, I hearthed to Orgrimmar and as of right now, still haven't become Rested.  I can, however, log out instantly and the "zzz" appears near my character frame. I attached a screenshot to show better detail.

And just to hopefully rule out any user error, I have never used glyphs of any kind - such as Exhaustion -  on this character. I'd appreciate any input. Thank you :)

![restedXPbug](https://user-images.githubusercontent.com/100882515/156667371-d6e52b10-a7c5-4465-a852-2728b7b151bf.png)

**Comment by gheor7** [comment]
I might be wrong but as far as I am aware you get rested experience while being logged out in an inn/city.

**Comment by ZoSo3** [comment]
> I might be wrong but as far as I am aware you get rested experience while being logged out in an inn/city.

You are correct, however your XP bar should turn blue for Rested within a few seconds of entering the city or inn. It does for all of my other characters.
