### ISSUE TITLE
part of ungoro map cant be uncovered

### ISSUE THREAD

**Issue by geojak** [slowtorta/turtlewow-bug-tracker#1184]
**Please, provide a clear description what the bug is:**

i have been trying for a good 10 minutes to uncover this map part. the location in the upper right above the minimap never changed rom the general ungor ocrater to the acutal map location, sometinhg like abandonded camp

**Steps to reproduce the behavior with as much detail as possible:**

1.
![WoWScrnShot_030422_165506](https://user-images.githubusercontent.com/25199983/156796457-076af6d3-f136-4295-98d6-23f82568a931.jpg)
![WoWScrnShot_030422_165505](https://user-images.githubusercontent.com/25199983/156796460-e590f87d-85b8-42ec-8f4e-062d6192dc41.jpg)

2. walk around everywhere in the map part missing in my screenshot
3. still not uncovered

**IDs of affected creatures, items, quests or spells with a link to the relevant page:**

NPC: https://database.turtle-wow.org/?npc=
Item: https://database.turtle-wow.org/?item=
Quest: https://database.turtle-wow.org/?quest=
Spell: https://database.turtle-wow.org/?spell=
Object: https://database.turtle-wow.org/?object=

**Expected behavior. Describe how it should work:**

map should be uncovered
game should display the area name

**Comment by slowtorta** [comment]
I have been able to discover this part of the map w/o a problem. Try visiting the area on my screenshot: 
![image](https://user-images.githubusercontent.com/66763404/157315729-c9242f11-3e4f-463d-b0e5-e632de207267.png)

**Comment by geojak** [comment]
i will give it a trz, but the part in their screenshot zou are at, isnt even in the map area i was trzing to uncover. weird
