### ISSUE TITLE
relic coffer key not in keyring

### ISSUE THREAD

**Issue by geojak** [slowtorta/turtlewow-bug-tracker#1185]
**Please, provide a clear description what the bug is:**

the relic coffer keys from brd are not in the keyring and waste players inventory space

**Steps to reproduce the behavior with as much detail as possible:**

1. get a relic key
2. try move it to your keyring since its is your normal invetory
3. cant

**IDs of affected creatures, items, quests or spells with a link to the relevant page:**

https://database.turtle-wow.org/?item=11078

**Expected behavior. Describe how it should work:**

should go inside the keyring since its a key

**Comment by slowtorta** [comment]
Was it the same in Vanilla? The keyring in this version is the game doesn't scale, it is probably why they kept only essential key items as keys.

**Comment by geojak** [comment]
not sure, the kezs in staholme for example from the coruier also dont go inside the kezring

https://classic.wowhead.com/npc=11082/stratholme-courier

**Comment by slowtorta** [comment]
Will be a key on the next update.

**Comment by geojak** [comment]
another key no it the keyring is:
https://database.turtle-wow.org/?item=9249
the captains key for the chest in one of the boats in tanaras.
not huegly impactfull, just sort of inconsistent since its a key

**Comment by geojak** [comment]
another key
https://database.turtle-wow.org/?item=5020
kolkar bootz key can

i am just going to collet these here, mazbe some daz the kezring will be enlarged, then we got a collecton

**Comment by geojak** [comment]
https://database.turtle-wow.org/?item=18250 
the dm north keys too
