### ISSUE TITLE
Warrior can't train 2H Mace

### ISSUE THREAD

**Issue by Lustrellia** [slowtorta/turtlewow-bug-tracker#1187]
**Please, provide a clear description what the bug is:**
I went to the weapon trainer in Ironforge to learn 2H maces from the dwarf. He did not have it. I opened the window and made it show everything possible and still nothing showed up. I've deleted my WDB folder, I've logged off, disabled addons, restarted the WoW client. Nothing works.

**Steps to reproduce the behavior with as much detail as possible:**

1. Went to trainer
2.  2H Mace Skill not available
3.  Skill not listed in my weapon skill list

**IDs of affected creatures, items, quests or spells with a link to the relevant page:**

NPC: https://database.turtle-wow.org/?npc=
Item: https://database.turtle-wow.org/?item=
Quest: https://database.turtle-wow.org/?quest=
Spell: https://database.turtle-wow.org/?spell=
Object: https://database.turtle-wow.org/?object=

**Expected behavior. Describe how it should work:**
I should be able to train it, right?

![signal-2022-03-05-172146_001](https://user-images.githubusercontent.com/101056547/156930515-3d035853-c730-4780-9cb6-3834d66682a8.jpeg)
![signal-2022-03-05-172119_001](https://user-images.githubusercontent.com/101056547/156930518-40eae1be-f3f8-419b-b70a-d072f503a7bc.jpeg)
![signal-2022-03-05-172107_001](https://user-images.githubusercontent.com/101056547/156930609-256a2750-2c54-4355-b80a-e63d47f991de.jpeg)

**Comment by geojak** [comment]
Did you check stormwind too?

**Comment by slowtorta** [comment]
We know about this bug, it's client-related. No solution yet, sorry. Moving to the internal bug-tacker.
