### ISSUE TITLE
Full soundtrack missing in Naxxramas

### ISSUE THREAD

**Issue by MisaHack** [slowtorta/turtlewow-bug-tracker#1188]
**Please, provide a clear description what the bug is:**

There is no soundtrack in Naxxramas, not a single composition.

**Steps to reproduce the behavior with as much detail as possible:**

1.  Get inside Naxx
2.  You will hear no soundtrack.

**IDs of affected creatures, items, quests or spells with a link to the relevant page:**

- Just soundtrack missing.

**Expected behavior. Describe how it should work:**

- Soundtrack should be heard.

**Comment by slowtorta** [comment]
Moving this one to the internal client bug tracker, thank you.
