### ISSUE TITLE
Araj's Phylactery cannot be looted by multiple people

### ISSUE THREAD

**Issue by SaxxonPike** [slowtorta/turtlewow-bug-tracker#1189]
**Please, provide a clear description what the bug is:**

Araj's Phylactery Shard and Araj's Scarab can only have quest items looted by one person.

**Steps to reproduce the behavior with as much detail as possible:**

1. Kill Araj the Summoner.
2. Attempt to loot Araj's Phylactery.
3. Discover that both quest items can only be looted by one person.

**IDs of affected creatures, items, quests or spells with a link to the relevant page:**

NPC: https://database.turtle-wow.org/?npc=1852
Item:
https://database.turtle-wow.org/?item=17114
https://database.turtle-wow.org/?item=14610
Quest: https://database.turtle-wow.org/?quest=211
https://database.turtle-wow.org/?quest=5803
Spell: n/a
Object: https://database.turtle-wow.org/?object=177241

**Expected behavior. Describe how it should work:**

Both Araj's Phylactery shard and the Scarab should be lootable by anyone, even those not in the party. It is currently like this on WoW Classic Era (verified on the Windseeker realm)

Comments from 1.10 on the Wowhead page also mention this, so it's not just a Classic thing either:
https://classic.wowhead.com/item=14610/arajs-scarab

**Comment by slowtorta** [comment]
Thanks, it'll be fixed on the next update.
