### ISSUE TITLE
AB Pathing/ line of sight problem spot

### ISSUE THREAD

**Issue by Zebouski** [slowtorta/turtlewow-bug-tracker#1190]
**Please, provide a clear description what the bug is:**
In the East corner of the arathi basin Farm's hut, is a spot where pets cant path to you, and players are LOS'd and must meele you. I had a hunter pet on me and was able to use this spot to get out of combat and start eating

**Steps to reproduce the behavior with as much detail as possible:**

1. go to arathi basin with 1 person on each team
2. have 1 player go to the east corner of the farm hut, another in the middle fo the hut
3. try to attack eacohter, send pets at eachother etc.

**Expected behavior. Describe how it should work:**
no LOS and pathing issues

**Comment by slowtorta** [comment]
Thanks, moving it to the internal tracker for client-related problems.
