### ISSUE TITLE
Npc inmsom'ni bugged

### ISSUE THREAD

**Issue by Khanz0** [slowtorta/turtlewow-bug-tracker#1191]
Please, p
Cannot interact with Insom'ni on Kazon Isle
.
Steps to reproduce the behavior with as much detail as possible:

Travel to Kazon Isle between Gilijim and Lapidis.
Try to click on Insomni to talk.
IDs of affected creatures, items, quests or spells with a link to the relevant page:

NPC: https://database.turtle-wow.org/?npc=60446

Expected behavior. Describe how it should work:
He should have a text box show up to interact and and to complete quests.

**Comment by jlautenbach** [comment]
Just got a report in #support that this is the case with at least quest 'Jadefire Revenge'.

![image](https://user-images.githubusercontent.com/73019779/168424067-1ea1e20b-4b2b-4023-a8b4-22274d610bbd.png)

**Comment by Joooni** [comment]
As of today, 12.08.2022, Insom'ni is still bugged when trying to hand in Jadefire Revenge and Tower of Lapidis VIII.

**Comment by slowtorta** [comment]
Duplicate for https://github.com/slowtorta/turtlewow-bug-tracker/issues/2153
