### ISSUE TITLE
mossflayer scout weird behaviour

### ISSUE THREAD

**Issue by geojak** [slowtorta/turtlewow-bug-tracker#1192]
**Please, provide a clear description what the bug is:**

the mossflayer scouts in eastern plagueland use hamstring. then they will run away. but they never actually use their range attack. they just keep running liek chickens 

**Steps to reproduce the behavior with as much detail as possible:**

1. attack a scout
2.  wait for them to use hamstring
3. see then run around healdes
4. maybe walk towards them a bit more while slowed

**IDs of affected creatures, items, quests or spells with a link to the relevant page:**

https://database.turtle-wow.org/?npc=8560

**Expected behavior. Describe how it should work:**

they should behavioir in a way that makes sense. so they should try to keep a set range to the player, instead they should run a set amount then stop running and shoot

**Comment by slowtorta** [comment]
The way they behave is Blizzlike. I cannot see any confirmations that it should be another way around, sorry.

**Comment by geojak** [comment]
Hello torta, I got you some proof from classic

https://m.youtube.com/watch?v=gc-vnmM1Nws

**Comment by geojak** [comment]
It appears to me these scouts don't use any ranged attack at all, they hamstring you, run away, and even if you don't move at all and let them do their thing, they still won't range attack.

In classic they dont run away, which makes sense if they hit no enraged attack anyway

**Comment by cyaohiri** [comment]
According to comments found here (https://classic.wowhead.com/npc=8560/mossflayer-scout#comments), it does seem they run away when pulled.
