### ISSUE TITLE
Quest text typos: The Tower of Lapidis II

### ISSUE THREAD

**Issue by inxdigo** [slowtorta/turtlewow-bug-tracker#1193]
![thetoweroflapidistypo](https://user-images.githubusercontent.com/74259373/157710518-c4dc33d2-c6b6-4048-a1e2-034519bef2a9.PNG)

Typos in the quest text: "n < Ansirem Runeweaver studies the Shimmering Brass key >."

**Comment by Kruxis** [comment]
Thanks for the report! Will be fixed on next server restart =)
