### ISSUE TITLE
BG queues via minimap teleport you back to queue spot upon completion

### ISSUE THREAD

**Issue by Zebouski** [slowtorta/turtlewow-bug-tracker#1195]
**Please, provide a clear description what the bug is:**
When you queue a BG via the minimap queue, take the pop, complete the game, and leave, you will be teleported back to where you first queued, isntead of where you are in the world.

For UI queueing for dungeons and BGs in WotLK and beyond, this was not the case, you were put right back in place from where the queue actually was popped and taken. This is how people expect it to work.

This back-teleporting is a significant reason that low lv BGs are dead. people don't want to be questing somewhere, get a game, then have to walk all the way back to their questing spot; only sometimes is the back teleport useful, but more often it will be detrimental.

**Steps to reproduce the behavior with as much detail as possible:**

1. queue bg via minimap tool
2. move around
3. take bg pop
4. see teleported back to queue spot

**Expected behavior. Describe how it should work:**
Players should be sent back to the spot they hit "Enter battle" at

**Comment by slowtorta** [comment]
Fixed in the next revision.

**Comment by geojak** [comment]
Hello, this doesn't appear fixed. I still got ported back to sw where I queued up and not back to Pestland where I got the bg pop and clicked enter

@slowtorta could you pls reopen the ticket?

**Comment by slowtorta** [comment]
Fixed approx. two weeks ago.
