### ISSUE TITLE
you can interact with Franclorn Forgewright alive

### ISSUE THREAD

**Issue by geojak** [slowtorta/turtlewow-bug-tracker#1196]
**Please, provide a clear description what the bug is:**

the npc Franclorn Forgewright that hand s out the qeust for the brd key shoukd only be interactable while being dead

**Steps to reproduce the behavior with as much detail as possible:**

1. be alive
2. walk to the npc
3. see him
4. accept the qeust

**IDs of affected creatures, items, quests or spells with a link to the relevant page:**

https://database.turtle-wow.org/?npc=8888

**Expected behavior. Describe how it should work:**

you should only be able to see and interact with him while dead. comapre wow head classic comments which also confirm this

https://classic.wowhead.com/npc=8888/franclorn-forgewright#comments

**Comment by slowtorta** [comment]
Will be fixed on the next update.
