### ISSUE TITLE
brd tavern not turning hostile

### ISSUE THREAD

**Issue by geojak** [slowtorta/turtlewow-bug-tracker#1197]
**Please, provide a clear description what the bug is:**

after feeding the dark iron ale to the drwarf npc which will initiate a little script which he goes and breaks the kegs, then phalanx aggors and the door opens

the issues here, this route should turn the hole room hostile after the kegs are broken and the party distrubed

this is not the case on twow

thats why the love potion quest is prefered way to open the door since it does not aggro the room

**Steps to reproduce the behavior with as much detail as possible:**

1. go to brd tavern
2. hand in the dark iron ale
3. kill phalanx
4. door is open now
5. tavern npc are still neutral and not hostile

**IDs of affected creatures, items, quests or spells with a link to the relevant page:**

**Expected behavior. Describe how it should work:**

the tavern nps should turn hostile when choosing this route to open the door

here are some wow head links with comments that proof this too

https://classic.wowhead.com/npc=9502/phalanx#comments

and here is definitive proof from a video from 2006, see at the very end when the yellow turns to red!!
https://www.youtube.com/watch?v=HQpoksHqVig

**Comment by SabineWren** [comment]
> here are some wow head links with comments that proof this too
> 
> https://classic.wowhead.com/npc=9502/phalanx#comments
> 
> and here is definitive proof from a video from 2006, see at the very end when the yellow turns to red!! https://www.youtube.com/watch?v=HQpoksHqVig

Both the comments and video confirm killing _Plugger_ makes the bar hostile. Killing Phalanx is fine.

**Comment by slowtorta** [comment]
Fixed in the last week's update. Please re-open if still broken.
