### ISSUE TITLE
lasting -armor in brd

### ISSUE THREAD

**Issue by geojak** [slowtorta/turtlewow-bug-tracker#1198]
**Please, provide a clear description what the bug is:**

the mobs in brd use armor penetration. there seems to be a  bug that sometimes this -armor is not cleared properby after the debug runs out.

here are some screenshots from my 2 back to back brd runs without relogging and you can see how it keeps building up

sometime from the first round
![WoWScrnShot_031122_183140](https://user-images.githubusercontent.com/25199983/158012709-bc0c13ad-e791-4b87-8c05-aa2b9f217598.jpg)

this screenshot is when i finished the first run and on the way back for the second run
![WoWScrnShot_031122_192514](https://user-images.githubusercontent.com/25199983/158012712-f69cbccd-726d-4dfa-b143-d2a3545a9e7d.jpg)

from the end of the second run
![WoWScrnShot_031122_204149](https://user-images.githubusercontent.com/25199983/158012713-d6b009d5-311d-4e9f-ac63-aed6c0727341.jpg)

i had the same issuea week earlier in my brd run, but didnt report back then, now when it happened cosisntely again i made this report 

**Steps to reproduce the behavior with as much detail as possible:**

1. be a lvl 60 padadin tank
2. dont use the armor aura
3. have some points the in +%armor talents
4. get affected by armor pen around the marshal winsor parts of the dungeons
5. even leave the dungeon
6. reset the dungeon
7. come back to a second run
8. it just builds up more randomyl sometimes

**IDs of affected creatures, items, quests or spells with a link to the relevant page:**

NPC: https://database.turtle-wow.org/?npc=
Item: https://database.turtle-wow.org/?item=
Quest: https://database.turtle-wow.org/?quest=
Spell: https://database.turtle-wow.org/?spell=
Object: https://database.turtle-wow.org/?object=

**Expected behavior. Describe how it should work:**

-armor should not last

disclaimer: i dont use any addons for stats

**Comment by geojak** [comment]
i cannot give better description for when and how it happens, could you please use devs tool to further investiagte this

**Comment by geojak** [comment]
Just to update, I rember this bug is more general
Its not just a paladin bug or a brd bug 

For example when you have food buff with plus spirit and get affected by some certain spirit debuffs, then it can hspoen thaz you get permanently lost stats.
Something is wrong with interaction of stat buffs and stat debuffs when running out, there must be a like this.

You have a buff increased staty x amount
Now you get a debuff to reduce stat by y%
Now buff runs out and yiu lose x stats 
Now debuff runs out and you get back your percentage stats but yiu don't get back y * x
Its permanently lost

**Comment by redmagejoe** [comment]
As stated in #1202 this issue is merely a display bug in the client. Serverside, the stat is correct, however there is indeed a strange interaction causing the clientside display to be erroneous. How this can be resolved, I am not certain.
