### ISSUE TITLE
yeti engineer pet not in the pet collection tab

### ISSUE THREAD

**Issue by geojak** [slowtorta/turtlewow-bug-tracker#1199]
**Please, provide a clear description what the bug is:**

i found another engineer pet that does not go into the collection tab
its the tranquil mechanical yeti

**Steps to reproduce the behavior with as much detail as possible:**

1. craft a tranquil mechanical yeti as engineer
2. use the item to summon the yeti
3. the item satys in yout back

**IDs of affected creatures, items, quests or spells with a link to the relevant page:**

https://database.turtle-wow.org/?item=21277

**Expected behavior. Describe how it should work:**

should go into the spellbook and remove the item

**Comment by slowtorta** [comment]
Fixed on the next update :) The tab will work only with 1.16.1 tho.
