### ISSUE TITLE
Imp gets hit by AoE while phase shifted

### ISSUE THREAD

**Issue by Lunkdunk** [slowtorta/turtlewow-bug-tracker#120]
**Please, provide a clear description what the bug is:**
Imp is getting hit by AoE while being on passive and phase shifted. From logs:
6/29 15:37:26.531  Zigpit suffers 400 Fire damage from Lava Bomb 's Conflagration.
6/29 16:01:24.427  Zigpit suffers 400 Fire damage from Lava Bomb 's Conflagration.
6/29 16:55:22.511  Baron Geddon 's Explosion hits Zigpit for 3200 Fire damage.
**Steps to reproduce the behavior with as much detail as possible:**

1.
2. 
3. 

**IDs of affected creatures, items, quests or spells with a link to the relevant page:**

NPC: https://database.turtle-wow.org/?npc=
Item: https://database.turtle-wow.org/?item=
Quest: https://database.turtle-wow.org/?quest=
Spell: https://database.turtle-wow.org/?spell=4511
Object: https://database.turtle-wow.org/?object=

**Expected behavior. Describe how it should work:**
Imp should be invulnerable while being phase shifted.

**Comment by CosminPOP** [comment]
#87

**Comment by Nolin7777** [comment]
Duplicate
