### ISSUE TITLE
Being the last person in your dungeon party will cause you to lose ownership of the instance

### ISSUE THREAD

**Issue by Zebouski** [slowtorta/turtlewow-bug-tracker#1200]
**Please, provide a clear description what the bug is:**
When everyone else leaves a group, all players lose control of the instance. This can be used to grief on purpose and accident, sending people out of the instance when they still need to do stuff in there.

**Steps to reproduce the behavior with as much detail as possible:**

1. Go into instance
2. Invite someone to group
3. Have them leave group
4. Get message that you are being teleported out

**Expected behavior. Describe how it should work:**
Whoever is the last person to remain in a group, should get to be the authoritative person that owns the instance. They will now be partyless and everyone else gets teleported out if they try to stay around. This is how it behaves on classic

This fix would also fix another issue, and allow people to leave a raid, then get invites from the new authoritative owner, so that they can be a party now.

**Comment by Zebouski** [comment]
this just bit me again, we were doing the high elf questline, going to ghostlands, and the other person couldnt join. they left party and I got sent all the way back to stormwind. extremely extremely frustrating bug

**Comment by 9600bauds** [comment]
In Classic, you were able to get around this by relogging before the 60 seconds were up to "reclaim" the instance, not sure if this is the case for this server too

**Comment by ratkosrb** [comment]
Will be fixed by https://github.com/slowtorta/turtle-wow/commit/2a190cc4785109fa30098fe5cd6784837d4d3d06

**Comment by Zebouski** [comment]
![image](https://user-images.githubusercontent.com/11151284/220792005-3e853372-c7f5-483b-b75a-27f0686ce5ec.png)
Confirmed working, the last man standing is no longer booted out. Big thanks!
