### ISSUE TITLE
general angerforge enrage spamm

### ISSUE THREAD

**Issue by geojak** [slowtorta/turtlewow-bug-tracker#1201]
**Please, provide a clear description what the bug is:**

the brd boss general angerforge enrages like every second. it looks rly messed up

**Steps to reproduce the behavior with as much detail as possible:**

1. attack the boss
2. watch him use something like berserker rage every second
3. the hole fight

**IDs of affected creatures, items, quests or spells with a link to the relevant page:**

https://database.turtle-wow.org/?npc=9033

**Expected behavior. Describe how it should work:**

https://www.youtube.com/watch?v=8f8kRFMeERE

here they fight him around minute 32 for a better view from meele
https://www.youtube.com/watch?v=aRTbXLKhYTE

**Comment by CosminPOP** [comment]
What you're seeing is an ability he's got.

[Enrage] — General Angerforge Enrages each time he is critically struck by a melee attack. Enrage increases the Physical damage General Angerforge inflicts by 55 and increases his melee attack speed by 30%. Enrage lasts for 5 sec.


https://wowpedia.fandom.com/wiki/General_Angerforge

**Comment by geojak** [comment]
Then it lacks an internal cooldoen, it the videos I linked you can clearly see he is not using the enrage animations multiple times per second

**Comment by geojak** [comment]
I see, I was wrong. It blizzlike
