### ISSUE TITLE
[Priest] Spirit Tap causing PERMANENT Spirit loss

### ISSUE THREAD

**Issue by VladosPrime** [slowtorta/turtlewow-bug-tracker#1202]
**Please, provide a clear description what the bug is:**

The talent Spirit Tap from Priest can cause a PERMANENT Spirit loss. I found this out when I was leveling in the Wetlands: the Mosshide Fenrunners and Mosshide Gnolls can apply a disease called Spirit Decay, which decreases your Spirit attribute by 6. Spirit Tap temporarily doubles your Spirit after killing an enemy, however because of the way it is coded it appears to temporarily double any Spirit debuffs you have as well (aka it doubles your TOTAL Spirit, including any Spirit debuffs). In this case, if you are afflicted by Spirit Decay it will double the Spirit loss from -6 to -12. The problem comes when trying to cast Cure Disease on yourself when Spirit Tap and Spirit Decay are both active: Cure Disease will remove the -6 Spirit debuff from the Spirit Decay, however the rest of -6 Spirit will remain even after the debuff has been removed, going down to a PERMANENT -3 Spirit after Spirit Tap expires. This can lead to some unfortunate permanent Spirit loss (I'm currently at -6 Spirit because I've done it twice) that cannot be recovered by any means as far as I'm aware. A similar behavior can be expected if the Spirit Decay debuff naturally expires before Spirit Tap does while both are active.

**Steps to reproduce the behavior with as much detail as possible:**

1. Play Priest and have 5/5 points in Spirit Tap.  Make sure that you have the Cure Disease spell trained as well.
2. Fight a Mosshide Fenrunner or Mosshide Gnoll and let him cast Spirit Decay on you.
3. When you kill him and Spirit Tap procs, check your attributes. You should have -12 Spirit instead of -6.
4. Cast Cure Disease on yourself while Spirit Tap is still active. The Spirit Decay disease will be gone, but you will have -6 Spirit while Spirit Tap is still active.
5. Wait for Spirit Tap to expire. You should now end up with a permanent -3 Spirit debuff. It can even stack if you do it multiple times.

**IDs of affected creatures, items, quests or spells with a link to the relevant page:**

NPC: https://database.turtle-wow.org/?npc=1010
         https://database.turtle-wow.org/?npc=1007

Spell: https://database.turtle-wow.org/?spell=15338
         https://database.turtle-wow.org/?spell=528

**Expected behavior. Describe how it should work:**

Spirit Tap should not double your Spirit debuffs. There should be no permanent attribute loss like this after curing Spirit Decay while Spirit Tap is active.

Thanks for taking the time to read this.

**Comment by geojak** [comment]
This might explain my permsnr armor loss in brd

**Comment by geojak** [comment]
ok so i have the same issue now.
in eastern plagueland the infected mossflayertrolls give you a debuf called something like whither with - stam and -spirit. if you are affected by a food buff you can end up with a permanent -2 to stam and spirit

**Comment by redmagejoe** [comment]
This ticket needs to be renamed to be less misleading. The issue is not a permanent loss of stats, but rather a session-persistent DISPLAY bug where stats come out to the correct values, but are displayed in a peculiar way.

**Comment by slowtorta** [comment]
I couldn't reproduce it. Possible that it's an addon issue.

**Comment by geojak** [comment]
I don't use any addons for stats
