### ISSUE TITLE
a mechanical npc can be feared in brd

### ISSUE THREAD

**Issue by geojak** [slowtorta/turtlewow-bug-tracker#1203]
**Please, provide a clear description what the bug is:**
 the warth hammer construct in brd is a mechanical golem, but it can be feared. 

**Steps to reproduce the behavior with as much detail as possible:**

1. be a warlock
2. fear
3. its mechanical
4. ???

**IDs of affected creatures, items, quests or spells with a link to the relevant page:**
https://database.turtle-wow.org/?npc=8907

**Expected behavior. Describe how it should work:**
mechanical nps are not fearable

**Comment by Kruxis** [comment]
Thanks for the report, will be fixed next restart!
