### ISSUE TITLE
Sunken Temple Rarespawns do not currently have the correct loot tables

### ISSUE THREAD

**Issue by Azeron223** [slowtorta/turtlewow-bug-tracker#1204]
The three rarespawn NPCs in the outside the Sunken Temple dungeon ([Zekkis](https://database.turtle-wow.org/?npc=5400), [Veyzhak the Cannibal](https://database.turtle-wow.org/?npc=5399) and [Jade](https://database.turtle-wow.org/?npc=1063)) do _not_ currently have loot tables appropriate for a rarespawn NPC.

I have killed all 3 of these rarespawns on at least 2 seperate occations and so far have not received a guaranteed green drop as you should expect for an NPC of this type.

Considering the work done to give existing rare elites custom loot more appropriate to their elite status and rarity, it would of course be fantastic to see these much unloved NPCs receive similar treatment, however I would settle for them having their guaranteed BoE green item drop as they should normally have!

**Comment by Kruxis** [comment]
i checked the droprate and they are pretty much vanilla. No love for the boys sorry
