### ISSUE TITLE
Incendosaur respawn rate does not match the 1.12 state

### ISSUE THREAD

**Issue by Azeron223** [slowtorta/turtlewow-bug-tracker#1205]
The [Incendosaur](https://database.turtle-wow.org/?npc=9318#drop) NPCs in Searing Gorge are currently not respawning in the same manner as they did in original 1.12 wow, leaving many people doing the incendosaur quest having to wait for respawns to finish the quest.

Currently the behaviour is simply that the mobs have a fixed respawn timer of about 5 minutes. With there being about 12 total spawns up in the cave this obviously leaves players short for the 20 required for the quest which feels somewhat clunky for those not aware of how their respawn mechanic works.

The expected behaviour for these mobs was a system whereby roughly 15-25% of the [Incendosaur](https://database.turtle-wow.org/?npc=9318#drop) NPCs would always be up in the cave any any time, should the number fall below the threshold it would bypass the normal 5 minute respawn timer and randomly spawn a new [Incendosaur](https://database.turtle-wow.org/?npc=9318#drop) at any of the spawn locations.

**Comment by Kruxis** [comment]
Thanks for the report, will be fixed on next server restart =)
