### ISSUE TITLE
[Hunter] Pet becomes corrupted after traveling on a boat

### ISSUE THREAD

**Issue by Tinyfin-github** [slowtorta/turtlewow-bug-tracker#1207]
Pet becomes corrupted after traveling on a boat

![image](https://user-images.githubusercontent.com/83077166/158534491-f5add8d4-3a21-4306-a51e-626af3b2f13d.png)

The cat pet has gone into stables, and the Burning blade Invoker  appeared  dead.

The burning blade invoker can't be summoned, dismissed or changed for other pets. It does not show in the stables.
Deleted it solves the issue
![image](https://user-images.githubusercontent.com/83077166/158534612-d5a68b78-e0bc-4e24-9f6b-27075412c42a.png)

**Comment by slowtorta** [comment]
Also related: https://github.com/slowtorta/turtlewow-bug-tracker/issues/380

**Comment by slowtorta** [comment]
This should no longer be the case as we now dismiss pets before the teleportation event happens.
