### ISSUE TITLE
Gordok Inner door Key Disappears

### ISSUE THREAD

**Issue by Steevo2** [slowtorta/turtlewow-bug-tracker#1208]
The Dire Maul North instance has a door key to open the final door dropped by the first boss called the Gordok inner door key :https://classic.wowhead.com/item=18268/gordok-inner-door-key. This key is suppose to despawn if you leave the instance while alive, but in fact it despawns if you die, making any wipes a run ender. 
The key actually doesn't disappear until you actual enter the dungeon again, strangely enough

**Comment by Steevo2** [comment]
Does the strat key disappear when you go back in? if not then I guess that's a related but different problem

**Comment by slowtorta** [comment]
Fixed on the next update.
