### ISSUE TITLE
Maraudon  : cannot click on the Larva Spewer  to destroy it. Spewed Larva keep spawning

### ISSUE THREAD

**Issue by Tinyfin-github** [slowtorta/turtlewow-bug-tracker#121]
Maraudon :  cannot click on the Larva Spewer  to destroy it . Spewed Larva keep spawning.
You should be able to destroy the Larva Spewer so that the Spewed Larva stop spawning.

https://database.turtle-wow.org/?object=178559 Larva Spewer
https://database.turtle-wow.org/?npc=13533 Spewed Larva

**Comment by Nolin7777** [comment]
??????

**Comment by Tinyfin-github** [comment]
Updated with more information.

**Comment by slowtorta** [comment]
I don't think it was the case in Vanilla. Probably added in later expansions?
