### ISSUE TITLE
dire pool is invisible

### ISSUE THREAD

**Issue by geojak** [slowtorta/turtlewow-bug-tracker#1210]
**Please, provide a clear description what the bug is:**
here you can see where the dire pool is.
![WoWScrnShot_031622_211224](https://user-images.githubusercontent.com/25199983/158682367-0af28aed-1609-4bfd-a1d3-9c2816504688.jpg)
its a physical object and i cant walk on it
i can also fill the vial of dire water here
but i cant see it
if i did not have pfquest, this quest would be impissible

**Steps to reproduce the behavior with as much detail as possible:**

1. go to dm with the quest fragments of the past
2. go to where my screenshot is
3. you cant see the pool
4. you cant walk on it
5. you can fill your vial 

**IDs of affected creatures, items, quests or spells with a link to the relevant page:**

https://classic.wowhead.com/quest=5247/fragments-of-the-past
https://database.turtle-wow.org/?quest=5247
https://database.turtle-wow.org/?item=16973

**Expected behavior. Describe how it should work:**

should be visible

Note: classic had this issue too, as you can see on wowhead comments, it was fixed during classic thought
https://classic.wowhead.com/quest=5247/fragments-of-the-past#comments

here you see how it should look
https://www.wowhead.com/item=16973/vial-of-dire-water

**Comment by slowtorta** [comment]
Couldn't reproduce it, working fine for me: 
![image](https://user-images.githubusercontent.com/66763404/200174136-854ae831-a358-4c33-9b34-7d6fd66ef7f8.png)
