### ISSUE TITLE
mashall winsor in brd attacks horde players

### ISSUE THREAD

**Issue by geojak** [slowtorta/turtlewow-bug-tracker#1211]
**Please, provide a clear description what the bug is:**

this issues emerged with crossfaction. not being able to do the escort together with your horde group members ruins cross faction play. and it weights heavior than some lore reason that winsor hates horde or something.

**Steps to reproduce the behavior with as much detail as possible:**

1. do brd escrot
2.  have horde in your team
3.  they cant attack winsor
4. but winsor will attack them

**IDs of affected creatures, items, quests or spells with a link to the relevant page:**

https://database.turtle-wow.org/?npc=9023

**Expected behavior. Describe how it should work:**

crossfactction should mean we can do this quest together with cross groups

**Comment by slowtorta** [comment]
Sorry, but I'm afraid having his faction changed will break more things. Crossafaction isn't exactly the feature this game was supposed to have in the first place.

I'd suggest not doing those quests in cross-faction parties.
