### ISSUE TITLE
yellow border on wand shoot

### ISSUE THREAD

**Issue by geojak** [slowtorta/turtlewow-bug-tracker#1212]
**Please, provide a clear description what the bug is:**

the yellow border while shooting with a wand is not always properly displayed

**Steps to reproduce the behavior with as much detail as possible:**

1. drag wand shoot into your action bar 2 times
2. click the button with the mouse and all shot in actionbars wll properly glow yellow
3. use they keybind and only the other shoot will glow, but not the actually keybind triggered one

**Expected behavior. Describe how it should work:**

shoot should glow yellow while wand shooting no matter if clicked or keybind used

**Comment by slowtorta** [comment]
Sounds like a random client glitch. This is not anything what we could ever fix.
