### ISSUE TITLE
twow battlegrounds queue shows wrong queed bgs

### ISSUE THREAD

**Issue by geojak** [slowtorta/turtlewow-bug-tracker#1213]
**Please, provide a clear description what the bug is:**

![WoWScrnShot_031922_012535](https://user-images.githubusercontent.com/25199983/159099330-ca320df8-5253-46c5-a362-3b8f6c8ecd9b.jpg)

**Steps to reproduce the behavior with as much detail as possible:**

1. queue alterac valley
2.  right click to queue for mor
3.  see that it shows as i am queued for warsong gulch
4. but the blizzard standard waiting icon says alterac which is correct sonce thats what i queued

**IDs of affected creatures, items, quests or spells with a link to the relevant page:**

**Expected behavior. Describe how it should work:**

the turtle wow icon to queue bgs should show the right bgs i am queued

**Comment by slowtorta** [comment]
It's fixed in 1.16.1
