### ISSUE TITLE
Codex: Sun\'s Serenity  can be used on NPCs

### ISSUE THREAD

**Issue by Tinyfin-github** [slowtorta/turtlewow-bug-tracker#1215]
Codex: Sun\'s Serenity  can be used on NPCs

https://user-images.githubusercontent.com/83077166/159158432-76fc6288-adc8-435a-95a0-4bdd8348c835.mp4

 https://database.turtle-wow.org/?item=81008

**Comment by slowtorta** [comment]
Fixed in the next revision.
