### ISSUE TITLE
Miss Danna is missing her students

### ISSUE THREAD

**Issue by Fin9622** [slowtorta/turtlewow-bug-tracker#1218]
Miss Danna https://database.turtle-wow.org/?npc=3513  is missing her students. She should be giving sightseeing tours to her students

Students:

https://database.turtle-wow.org/?npc=3509
https://database.turtle-wow.org/?npc=3512
https://database.turtle-wow.org/?npc=3508
https://database.turtle-wow.org/?npc=3511
https://database.turtle-wow.org/?npc=3510
https://database.turtle-wow.org/?npc=3507
https://database.turtle-wow.org/?npc=3505

![WoW_7vbMWqhEFq](https://user-images.githubusercontent.com/83077166/159430279-4620d8a5-0b3b-4379-a7b1-6a01462c9bfe.jpg)
.

**Comment by redmagejoe** [comment]
This occurs with most NPCs that are meant to move in groups. For some reason on Turtle, their pathing desyncs even though I know I've seen all NPCs stay together on other servers. This affects Paige and her kids, the Orgrimmar snake vendor and his snake, Little Timmy and his kitten, and so many others.
