### ISSUE TITLE
Seeing What Happens can't be completed

### ISSUE THREAD

**Issue by MadLitrus** [slowtorta/turtlewow-bug-tracker#1221]
**Please, provide a clear description what the bug is:**
Can't interact with the Uldum Pedestal

![Uldum](https://user-images.githubusercontent.com/97635850/159577818-b7e14adc-b14a-45df-98d7-215d223a8e1f.png)

**Steps to reproduce the behavior with as much detail as possible:**

1. Pick up "Seeing What Happens" quest from Ironforge
2. Going to Uldum in Tanaris

**IDs of affected creatures, items, quests or spells with a link to the relevant page:**

Quest: https://database.turtle-wow.org/?quest=2946

**Expected behavior. Describe how it should work:**
Should be amble to interact with the pedestal and complete the quest, unlocking The Stone Watcher quest.

**Comment by Tinyfin-github** [comment]
> It was bugged, then the issue finally fixed and closed a few weeks ago. I was even able to finish the quest. No its bugged again? What's, going on?

It's a different issue this time.

**Comment by Kruxis** [comment]
*sight* i check it out this evening

**Comment by Kruxis** [comment]
Wait i need more info. @geojak 

Did you interact and the Dwarf appeared and now nothing works anymore?

Was the Dwarf already there, you can see a gear when hovering over the pedestal but nothing happens?

OR 

Your cursor doesnt change and you cant even click the pedestal?

**Comment by MadLitrus** [comment]
The issue wasn't there the next day i logged in. But when i wrote the ticket, the dwarf hologram was already there when i got to uldum and i wasn't able to interact with the pedestal in any way.

**Comment by Kruxis** [comment]
Gotcha! Thanks for the info

**Comment by Neto-WoW** [comment]
Should be good on next update. A few things that are unique with this code so please report any further issues.

**Comment by fortego** [comment]
Stuck with this quest too, Pedestal is not clickable.
As I understand, the problem is caused by this bug: https://github.com/slowtorta/turtlewow-bug-tracker/issues/4031
It doesn't finish this blue-halogram-guy animation.
