### ISSUE TITLE
Seal of ascension issue

### ISSUE THREAD

**Issue by Tinyfin-github** [slowtorta/turtlewow-bug-tracker#1224]
https://database.turtle-wow.org/?quest=4743  Seal of Ascension  
https://database.turtle-wow.org/?item=12300  Orb of Draconic Energy 
https://database.turtle-wow.org/?item=12323  Unforged Seal of Ascension
https://database.turtle-wow.org/?npc=10321 Embestrife

How it works now:
You don't need to use the orb of draconic energy to control emberstrife. You just need to place down the seal when he is low hp
https://streamable.com/fl03gb

How it should work:
You need to use the orb of draconic energy to control emberstrife. You  need to place down the seal when he is low hp and breathe fire.
https://youtu.be/kuTKldEedkQ?t=244

**Comment by slowtorta** [comment]
Related to https://github.com/slowtorta/turtlewow-bug-tracker/issues/2091
