### ISSUE TITLE
Quest [A Bloody Good Deed] reward

### ISSUE THREAD

**Issue by Haaxor1689** [slowtorta/turtlewow-bug-tracker#1225]
Quest [[A Bloody Good Deed]](https://database.turtle-wow.org/?quest=80396) has only one reward but still makes you "choose" it before you are able to complete it.

![image](https://user-images.githubusercontent.com/25706343/159740819-74347a8e-1811-4915-9304-5b5bb13ed696.png)

**Comment by Kruxis** [comment]
Thanks for the report, will be fixed on next restart =)
