### ISSUE TITLE
No City Protector title + item with standing 1

### ISSUE THREAD

**Issue by Oledien43** [slowtorta/turtlewow-bug-tracker#1226]
**Please, provide a clear description what the bug is:**
I got standing 1 as orc (horde in general aswell) and should receive a title plus jaina's necklace (the city protector one that allows you to teleport to your capital) for this whole week. I did not.

**Steps to reproduce the behavior with as much detail as possible:**

1.Get highest standing for your race.
2. Expect to receive said item and title.
3. Do not receive said item and title.

**IDs of affected creatures, items, quests or spells with a link to the relevant page:**
Item ID=50056
Page link: https://database.turtle-wow.org/?item=50056

NPC: https://database.turtle-wow.org/?npc=
Item: https://database.turtle-wow.org/?item=50056
Quest: https://database.turtle-wow.org/?quest=
Spell: https://database.turtle-wow.org/?spell=
Object: https://database.turtle-wow.org/?object=
![download](https://user-images.githubusercontent.com/28779603/159822450-92b1bf32-6421-415c-87ff-481a77ad82fd.png)
![download (1)](https://user-images.githubusercontent.com/28779603/159822515-87126cb3-78d6-40eb-9b24-57316d8bd302.png)

**Expected behavior. Describe how it should work:**
I should have received the item plus title,

**Comment by slowtorta** [comment]
Hello there! I know I haven't posted a changelog for the latest update but the system had been changed to work with the last week's honorable kills, not the actual standing.

**Comment by slowtorta** [comment]
It works for the Alliance, I'm assuming it works for the Horde as well :)
