### ISSUE TITLE
Large guild's rosters are showing incorrect number of online people.

### ISSUE THREAD

**Issue by slowtorta** [slowtorta/turtlewow-bug-tracker#123]
**Please, provide a clear description what the bug is:**

Large guild's rosters are showing incorrect number of online people.

**Steps to reproduce the behavior with as much detail as possible:**

1. Create a Hardcore character.
2. Open guild tab (~1000 members in total), filter by online members.
3. Compare the number in /who still alive with the number in the tab.

**Expected behavior. Describe how it should work:**

Guild roster must show correct number of online members.

**Comment by LeopoldHock** [comment]
According to today's patch notes, this can be closed. :)
