### ISSUE TITLE
Quest item [Storn's Head] and [Salorn's Ring] have incorrect drops

### ISSUE THREAD

**Issue by Haaxor1689** [slowtorta/turtlewow-bug-tracker#1232]
Item [[Storn's Head]](https://database.turtle-wow.org/?item=60197) shows that it drops from [[Defias Highwayman]](https://database.turtle-wow.org/?npc=122) as well as from Storn as it's supposed to.

![image](https://user-images.githubusercontent.com/25706343/159998215-26bf1a2a-3626-4d99-a8be-2e6edb8b7f81.png)

Another item with the same problem [[Salorn's Ring]](https://database.turtle-wow.org/?item=60378)

![image](https://user-images.githubusercontent.com/25706343/160008748-94d43806-3de7-4292-bbc9-20d1ae49d0a6.png)

**Comment by slowtorta** [comment]
Thank you for reporting all those issues. It'll be fixed in the next server update this week.
