### ISSUE TITLE
Quest [Reinforcing The Sepulcher] should probably be blacksmith only

### ISSUE THREAD

**Issue by Haaxor1689** [slowtorta/turtlewow-bug-tracker#1233]
Quest [[Reinforcing The Sepulcher]](https://database.turtle-wow.org/?quest=70040) should probably have an additional requirement of the player having Blacksmithing since the objective is to turn in bs crafted items.

**Comment by slowtorta** [comment]
That's alright. Even if some players don't have BM skills, they can always ask someone who does :)
