### ISSUE TITLE
Quest [Angor Fortress] can pull the whole map by standing in one spot

### ISSUE THREAD

**Issue by maksimkholod** [slowtorta/turtlewow-bug-tracker#1234]
**Please, provide a clear description what the bug is:**

There is a spot in angerforge fortress that pulls the whole map

**Steps to reproduce the behavior with as much detail as possible:**

Just pull one mob and then walk through the door, the mob runs in a circle to pull all the other patrols.

**IDs of affected creatures, items, quests or spells with a link to the relevant page:**

NPC: https://database.turtle-wow.org/?npc=2742
NPC: https://database.turtle-wow.org/?npc=2743

Quest: https://database.turtle-wow.org/?quest=40229

**Expected behavior. Describe how it should work:**

The mob should follow you through the doorway.

https://www.youtube.com/watch?v=zQmF5LhXD24

**Comment by slowtorta** [comment]
Thank you. I'll move this report to the internal tracker for client-related problems.

**Comment by slowtorta** [comment]
Possibly fixed or at least improved on the previous server update.

**Comment by gabryatfendor** [comment]
Aggroed the whole floor through the same means, so I think it isn't fixed
