### ISSUE TITLE
Can't start the quest "Enticing Negolash"

### ISSUE THREAD

**Issue by MadLitrus** [slowtorta/turtlewow-bug-tracker#1235]
**Please, provide a clear description what the bug is:**

In Stranglethorn Vale, at Wild Shore there is a boat near an NPC named Morgan the Storm. You should be able to interact with it to start the quest Enticing Negolash but you can't.

![image](https://user-images.githubusercontent.com/97635850/160235870-1d6dae06-8132-4c31-8853-24bfb06dbbac.png)

**IDs of affected creatures, items, quests or spells with a link to the relevant page:**

Quest: https://database.turtle-wow.org/?quest=619

**Expected behavior. Describe how it should work:**

You should be able to interact with the recked boat and start the Quest.

**Comment by slowtorta** [comment]
This is working as intended, you need to have one of those quests in your quest log to interact with the object: https://database.turtle-wow.org/?search=Facing+Negolash
