### ISSUE TITLE
Spell Lock (Felhunter) Not Working Properly

### ISSUE THREAD

**Issue by triana2021** [slowtorta/turtlewow-bug-tracker#1236]
**Please, provide a clear description what the bug is:**
Spelllock is not appyling its kick 'lock out'. It is only silencing for 3seconds, losing significant functionality in pvp and open world.
**Steps to reproduce the behavior with as much detail as possible:**

1. Summon Felhunter
2.  Have an enemy player spellcasting
3. Cast spell lock
4. Notice that the 'kick' portion of spelllock is not applying

**IDs of affected creatures, items, quests or spells with a link to the relevant page:**

NPC: https://database.turtle-wow.org/?npc=
Item: https://database.turtle-wow.org/?item=
Quest: https://database.turtle-wow.org/?quest=
Spell: https://database.turtle-wow.org/?spell=
Object: https://database.turtle-wow.org/?object=

**Expected behavior. Describe how it should work:**
Spelllock should silence for 3 seconds AND function as a longer lockout kick when timed correctly. It seems that window for timing may be off, or the kick portion is absent entirely

**Comment by CosminPOP** [comment]
tested in a duel
![image](https://user-images.githubusercontent.com/7255825/160586708-87da12a1-42b0-40f8-a255-e580cafa5991.png)

**Comment by triana2021** [comment]
will try to see if its some other interaction causing it not to. thank you for test
