### ISSUE TITLE
[Return to Kheyna] wrong quest turn in npc

### ISSUE THREAD

**Issue by Tinyfin-github** [slowtorta/turtlewow-bug-tracker#1237]
[Return to Kheyna] wrong quest turn in npc The quest should be turned in at Kheyna https://database.turtle-wow.org/?npc=81041 not
Chromie https://database.turtle-wow.org/?npc=10667

https://database.turtle-wow.org/?quest=80409 Return to Kheyna

![image](https://user-images.githubusercontent.com/83077166/160268729-fb5aa37b-437c-4919-a4f7-9689c07f069f.png)

**Comment by demiurgeQuantified** [comment]
now kheyna is the start of the quest, instead of rheas, and the end is still chromie
