### ISSUE TITLE
Argent Dawn Quest [Argent Dawn Commission] not available to players at level 50.

### ISSUE THREAD

**Issue by Zhohan** [slowtorta/turtlewow-bug-tracker#124]
Unable to pickup quest [Argent Dawn Commission] at Chillwind Camp (Alliance) at level 50. Every DB including TWoW says available at 50, quest is 55.

1. Right-click Argent Officer Pureheart <The Argent Dawn> at Chillwind Camp.
2. Quest does not appear.
3. Suffer.

NPC: https://database.turtle-wow.org/?npc=10840
Item: https://database.turtle-wow.org/?item=12846
Quest: https://database.turtle-wow.org/?quest=5401

Quest should be available at level 50.

**Comment by slowtorta** [comment]
Thanks for reporting it. It'll be fixed on the next server restart. Make sure to clear your WDB folder.

**Comment by slowtorta** [comment]
Thanks for reporting it. It'll be fixed on the next server restart. Make sure to clear your WDB folder.
