### ISSUE TITLE
Makura OIlclaw mobs don't move at all

### ISSUE THREAD

**Issue by FeyfolkenFantasy** [slowtorta/turtlewow-bug-tracker#1241]
**Please, provide a clear description what the bug is:**

Makura Oilclaw mobs located on the oilfield, east of Sparkwater Port (Durotar) are immobiles/frozen.
You can attack them, but if you move away from them they don't follow you.

**Steps to reproduce the behavior with as much detail as possible:**

1. Go to the oilfield east of Sparkwater port and attack a Makura OIlclaw.

**IDs of affected creatures, items, quests or spells with a link to the relevant page:**

NPC: https://database.turtle-wow.org/?npc=91194

**Expected behavior. Describe how it should work:**

Those little adorable creatures should be able to move! Give them love!

**Comment by slowtorta** [comment]
Fixed on the next update :)
