### ISSUE TITLE
Visual Lightning Glitch, Sparkwater Port (Durotar)

### ISSUE THREAD

**Issue by FeyfolkenFantasy** [slowtorta/turtlewow-bug-tracker#1242]
**Please, provide a clear description what the bug is:**

Very little lightning glitch at the very tip of the dock of Sparkwater Port to Revantusk Village. Probably caused by a misaligned meshe or misaligned vertices.

**Steps to reproduce the behavior with as much detail as possible:**

1. Go to ther very tip of the dock of Sparkwater Port

**IDs of affected creatures, items, quests or spells with a link to the relevant page:**

![WoWScrnShot_032822_214445](https://user-images.githubusercontent.com/102554573/160483025-91b33fd7-ac3d-4230-ad00-3f7247faf7b6.jpg)

**Expected behavior. Describe how it should work:**

The dock should be nice and clean! ... well at least to Goblins standards.

**Comment by slowtorta** [comment]
Thank you. Moving it to the internal tracker for client issues.
