### ISSUE TITLE
Two cooking tables at the exact same spot

### ISSUE THREAD

**Issue by FeyfolkenFantasy** [slowtorta/turtlewow-bug-tracker#1244]
**Please, provide a clear description what the bug is:**

Two cooking tables have been placed at the exact same spot in Razor Hill (Durotar), next to Cook Torka (51:42)

**Steps to reproduce the behavior with as much detail as possible:**

1. Go to Razor Hill
2. Put your mouse over the cooking tables next to Cook Torka

![Sans titre](https://user-images.githubusercontent.com/102554573/160615160-3e51d72c-a73d-4bc8-823c-7aaa57edb454.jpg)

**IDs of affected creatures, items, quests or spells with a link to the relevant page:**

Object: https://database.turtle-wow.org/?object=176463

**Expected behavior. Describe how it should work:**

TW devs probably wanted to highlight that Cook Torka is a Master Chief, but one cooking table is enough n_n

**Comment by slowtorta** [comment]
Thank you, it'll be fixed shortly :)
