### ISSUE TITLE
Quivers not affecting wand speed

### ISSUE THREAD

**Issue by triana2021** [slowtorta/turtlewow-bug-tracker#1246]
**Please, provide a clear description what the bug is:**
Quiver speed increase not affecting wanding speed.

**Steps to reproduce the behavior with as much detail as possible:**

1. as a wand using class, equip a quiver
2.  wand a target (or look at shoot button)
3.  see speed is not affected

**IDs of affected creatures, items, quests or spells with a link to the relevant page:**

NPC: https://database.turtle-wow.org/?npc=
Item: https://database.turtle-wow.org/?item=
Quest: https://database.turtle-wow.org/?quest=
Spell: https://database.turtle-wow.org/?spell=
Object: https://database.turtle-wow.org/?object=

**Expected behavior. Describe how it should work:**
Based on reading old vanilla posts I *think* it should add quiver speed to wanding.

**Comment by geojak** [comment]
i think thi isnt true, quiver should not affect wands at all

**Comment by slowtorta** [comment]
Hello! This is an intended change, they aren't supposed to increase it. The bug was present only in emulation, it's not the case on Classic, nor were in Vanilla.
