### ISSUE TITLE
Storn's head is not dropped by Storn

### ISSUE THREAD

**Issue by Tinyfin-github** [slowtorta/turtlewow-bug-tracker#1250]
Storn's head is not dropped by Storn 

https://database.turtle-wow.org/?item=60197 Storn's Head
https://database.turtle-wow.org/?npc=91718 Storn
https://database.turtle-wow.org/?quest=40138 Bandit Lord

**Comment by FuNtasticXs** [comment]
Hi @Kruxis this bug is appear again. There is no drop of Storn's Head https://database.turtle-wow.org/?item=60197 at the current moment.[https://pasteboard.co/1CFeqpyXNYdU.png](url)
