### ISSUE TITLE
Viridian Band  bugged

### ISSUE THREAD

**Issue by Tinyfin-github** [slowtorta/turtlewow-bug-tracker#1252]
https://database.turtle-wow.org/?item=6589 Viridian Band  does not give random  bonus, it only gives of retaliation.  The retalation bonus seems to never proc.
Also there seems to be two items with the same name Viridian bad but different id https://database.turtle-wow.org/?search=Viridian+Band

https://streamable.com/o27kkk
https://streamable.com/nfk94d

**Comment by slowtorta** [comment]
Fixed in the next revision. Renamed to `Glimmering Ring of the ...`
