### ISSUE TITLE
quest text states wrong location

### ISSUE THREAD

**Issue by geojak** [slowtorta/turtlewow-bug-tracker#1255]
**Please, provide a clear description what the bug is:**

the qeust text says to return to the npc Vanessa Clang in Mudsprocket. 
but the npc is in sparkwater port

**Steps to reproduce the behavior with as much detail as possible:**

**IDs of affected creatures, items, quests or spells with a link to the relevant page:**

https://database.turtle-wow.org/?quest=80386

**Expected behavior. Describe how it should work:**

mudsprocket should be starkwater port in the text

**Comment by slowtorta** [comment]
Fixed in the next revision.
