### ISSUE TITLE
Empty Faction Added (Harken Windtotem)

### ISSUE THREAD

**Issue by Firestoat** [slowtorta/turtlewow-bug-tracker#1256]
The NPC questgiver in Bloodhoof village, Mulgore, is assigning / opening a new Unlabled faction on the character's faction list the moment he is left clicked on / targeted. The unlabled blank faction remains on the character's faction page with a 500 value.

This game bug can be reproduced by creating a fresh Horde character and running it over to Bloodhoof Village and left click / targeting the NPC, Harken Windtotem. Upon completing the quest that the NPC offers, the correct reward / Thunder Bluff faction increase is added. That part is not bugged.

WoWhead Classic NPC Link -- https://classic.wowhead.com/npc=2947/harken-windtotem
TurtleWoW Database NPC Link -- https://database.turtle-wow.org/?npc=2947

![WoWScrnShot_031922_215502](https://user-images.githubusercontent.com/33730653/161102175-8b885831-de75-4268-a0c3-66d6d756f9fe.jpg)

Expected Behavior: The NPC shouldn't flag a blank faction in a character's reputation page.

**Comment by Zmitrok1984** [comment]
This faction for Spirit Healer - wihtout it you will not resurect on graveyard

**Comment by slowtorta** [comment]
Hello. This is a client-side issue and we already fixed it in the internal build of the upcoming patch 1.16.1 :)
