### ISSUE TITLE
Broken NPC Speech Script (Okla)

### ISSUE THREAD

**Issue by Firestoat** [slowtorta/turtlewow-bug-tracker#1257]
The little ork girl named Okla, located in The Barrens, is currently broken in that she does not speak her routine script while hunting for shiny rocks near her father, Kranal Fiss.

WoWHead Classic NPC Link -- https://classic.wowhead.com/npc=14873/okla
TurtleWoW Database NPC Link -- https://database.turtle-wow.org/?npc=14873

In Game Image of Bug -- https://postimg.cc/QBhVQ3VK

While the NPC correctly executes her scripted movements and proper pauses at different navigation checkpoints, she is entirely silent while going through her routine. All of her spoken script has been archived Here -- https://wowwiki-archive.fandom.com/wiki/Okla

**Comment by redmagejoe** [comment]
This issue still persists on current version and should be a relatively easy fix.
