### ISSUE TITLE
Deepmoss Webspinner (Broken ability cooldown)

### ISSUE THREAD

**Issue by Firestoat** [slowtorta/turtlewow-bug-tracker#1258]
The Deepmoss Webspinner NPC mob located in Stonetalon will currently use its Web root effect on a player that has a duration of 9 seconds, and immediately root the player in succession every 8 seconds while a combat continues. There are no diminishing returns applied on the Web effect - it retains its full 9 second duration each time. There is no appreciable cooldown to its ability with it being set at 8 seconds. The mob will just spam it eternally with full effect.

This behavior is incorrect. While I am not certain that its documented that this Web effect should have diminishing returns, it absolutely should have the standard 6 second cooldown between uses of this ability or greater.

In Game Image of the Bugged NPC -- https://postimg.cc/Ff0rnnk5

WoWHead Classic NPC Link -- https://classic.wowhead.com/npc=4006/deepmoss-webspinner
TurtleWoW Database NPC Link -- https://database.turtle-wow.org/?npc=4006

**Comment by slowtorta** [comment]
Thanks. Fixed in the next revision.
