### ISSUE TITLE
The quest "A Harmonious Offering" is not completable

### ISSUE THREAD

**Issue by FeyfolkenFantasy** [slowtorta/turtlewow-bug-tracker#1260]
**Please, provide a clear description what the bug is:**

The quest "a harmonious offering" needs you to give a pack of pelt to the assistant innkeeper Waya Tallgrain in the Bloodhoof Village (Mulgore).
Unfortunatly, you can not talk to Waya Tallgrain nor target her.

**Steps to reproduce the behavior with as much detail as possible:**

1. Go to the Bloodhoof Village (Mulgore)
2. Start the chain quest of Melyndella [id:66002, pos: 46/60.9]
3. Get the quest "a harmonious offering" (4th quest of the chain)

**IDs of affected creatures, items, quests or spells with a link to the relevant page:**

NPC: https://database.turtle-wow.org/?npc=60652
Quest: https://database.turtle-wow.org/?quest=40366

**Expected behavior. Describe how it should work:**

Since I am playing a custom race (goblin), maybe it has something to do with that.
But one should be able to give the pack of pelt to this lovely Tauren. Nobody can talk to her, she must be so sad!

**Comment by Kruxis** [comment]
Greetings Traveler! Thanks for the report, the bug will be fixed on next restart =)

**Comment by FeyfolkenFantasy** [comment]
@Kruxis thank you! 🙂
