### ISSUE TITLE
Unspecified Taxi Error: Thunder Bluff --> Zoram'gar Outpost, Ashenvale

### ISSUE THREAD

**Issue by Firestoat** [slowtorta/turtlewow-bug-tracker#1261]
As of the date of this post, I am unable to use a vanilla flight point path from Thunder Bluff to Zoram'gar Outpost in Ashenvale. I did indeed log out of the game, delete the contents of my WDB folder, and attempt to take the flight path again. The error was still present, at which point I took the screenshot below to show the error.

In Game Screenshot -- https://postimg.cc/KkLKP347

**Comment by Tinyfin-github** [comment]
Greetings!

Thank you for the report.

The issue will be fixed with the release of 1.16.1.
