### ISSUE TITLE
Wanted: Layle | Orgrimmar | Server disconnect

### ISSUE THREAD

**Issue by jlautenbach** [slowtorta/turtlewow-bug-tracker#1262]
**Please, provide a clear description what the bug is:**

When clicking quest "Wanted: Layle" at wanted sign in Orgrimmar at cords 69, 72 you get disconnected from server. I (Niral) reproduced the issue mentioned by a player who had also cleared WDB. 

**Steps to reproduce the behavior with as much detail as possible:**

1. Go to Wanted Poster in Orgrimmar at cords 69, 72 
2. Click: "Wanted: Layle"
3. Observe server DC. You are now seeing the login screen.

**Expected behavior. Describe how it should work:**
Should be able to accept the quest instead of DC.

![image](https://user-images.githubusercontent.com/73019779/161350437-dbc39480-8490-49c1-81d9-ce04b663b03d.png)
![image](https://user-images.githubusercontent.com/73019779/161350453-65c54773-b6a5-4370-be99-e53811d87b77.png)
![image](https://user-images.githubusercontent.com/73019779/161350579-ba86206e-4566-4a92-8ddf-23d760228702.png)

**Comment by Kruxis** [comment]
Note:
Bug exists on Fresh Client, properly setup, no addons. 
Bug occures when clicking the Gameobject's gossip_option for the PvP quest.

Couldn't reproduce myself.

**Comment by slowtorta** [comment]
This could happen if your client doesn't have writing permission in WDB folder. Please check if it's the case!
