### ISSUE TITLE
the druid aoe healing particles stay permanent in lbrs

### ISSUE THREAD

**Issue by geojak** [slowtorta/turtlewow-bug-tracker#1264]
**Please, provide a clear description what the bug is:**

so i ran lbrs with a druid healer and he used the aoe heal a  few times. unfortunelty i satyed permanelty and over time i had severe fps issues

**Steps to reproduce the behavior with as much detail as possible:**

1. cast the aoe druid heal spell
2. watch the effect stays permanetly
3. build up severe fps issues over time

![WoWScrnShot_033122_202902](https://user-images.githubusercontent.com/25199983/161393721-154a443d-2b6f-4188-9bb1-b0ff69d44f99.jpg)

**Expected behavior. Describe how it should work:**
effect should disappear when spell ends

**Comment by geojak** [comment]
The scholo ghouls Green clouds also stay permanent now. This was end these case before.

**Comment by geojak** [comment]
It's seems I am not the only one. Someone posted this on discord

@Support  Does anyone have any idea whatsoever why this might be happening? I'm not talking about the error message, but rather that hurricane is still on my screen long after the cast. This situation happens with blink and consecrate as well, the spell effects continue into the environment. At first I thought it was the HD mod from the forums, but I've removed all patch-# mods, all addons, deleted configs and wdb folder and it still persists. I've downloaded an entirely fresh client off the website and it's still there. The only thing left to try is on an entirely new computer =/

**Comment by geojak** [comment]
updating nvidida did not fix it

**Comment by slowtorta** [comment]
Do you have any additional client patches, like HD models?

**Comment by slowtorta** [comment]
Sorry, nothing we can do about it, it's a client issue. Happens in default 1.12.* Vanilla as well.
