### ISSUE TITLE
weird buff when summong the lbrs t0.5 druid boss

### ISSUE THREAD

**Issue by geojak** [slowtorta/turtlewow-bug-tracker#1265]
**Please, provide a clear description what the bug is:**

just see the screenshot. the buff apeared when summoning the lbrs t0.5 special druid boss
![WoWScrnShot_033122_191340](https://user-images.githubusercontent.com/25199983/161393783-37789b9e-0709-45e3-b661-abaeb2173567.jpg)

**IDs of affected creatures, items, quests or spells with a link to the relevant page:**

**Expected behavior. Describe how it should work:**
 not sure, maybe hidden buff?

**Comment by slowtorta** [comment]
Please provide mob IDs and quest IDs involved with this issue.

**Comment by Tinyfin-github** [comment]
https://database.turtle-wow.org/?item=22057  Brazier of Invocation
https://database.turtle-wow.org/?item=22049  Brazier of Beckoning
https://database.turtle-wow.org/?npc=16080#objective-of  Mor Grayhoof

You gain the buff when you use the braziers to summon any  of the tier 0.5 bosses
https://database.turtle-wow.org/?search=Brazier+of+Beckoning


![WoW_H34WZ4ay20](https://user-images.githubusercontent.com/83077166/161600838-689a4999-64a6-4d80-af68-0bc328303241.jpg)


https://user-images.githubusercontent.com/83077166/161601209-8ee0d568-717f-4f26-ba41-5a81ba5616b2.mp4


https://user-images.githubusercontent.com/83077166/161601238-6e971cb7-bc14-48d9-9e8d-9afc4a965a6c.mp4

**Comment by slowtorta** [comment]
Fixed in the next revision.
