### ISSUE TITLE
lbrs npcs not aggroing that sleep in weird positions

### ISSUE THREAD

**Issue by geojak** [slowtorta/turtlewow-bug-tracker#1266]
**Please, provide a clear description what the bug is:**

there are a few orcs sleeping in weird positinos that dont aggro and are also hard to attack by the player.
they should aggro together with their friends when they are attacked, instead they keep sleeping while their comrades dies

in the middle part with the fire casters
![WoWScrnShot_033122_191721](https://user-images.githubusercontent.com/25199983/161393847-8b866c91-b899-47a7-a106-49682df3d72f.jpg)
before ednboss, dude on the left is bugged
![WoWScrnShot_033122_200404](https://user-images.githubusercontent.com/25199983/161393850-c37a1d89-0eb1-42bb-8a0f-041d0af5c480.jpg)

**Steps to reproduce the behavior with as much detail as possible:**

1. go to lbrs
2. see the sleeping orcs before endboss and in the middle part with the orc fire casters
3. some are buggy

**IDs of affected creatures, items, quests or spells with a link to the relevant page:**

**Expected behavior. Describe how it should work:**
they should attack

**Comment by slowtorta** [comment]
I believe this is related to the custom change we introduced a year ago: any static objects on TW are now considered as obsticles for movement and casting. You can't cast through lampposts, tree stomps, and so on. Some minor glitches like this are a sacrifice we have to live with, I'm sorry.
