### ISSUE TITLE
Quest Issue - Lucky Coin - Numerous spelling errors. 

### ISSUE THREAD

**Issue by BobsenJr** [slowtorta/turtlewow-bug-tracker#1268]
**Please, provide a clear description what the bug is:**

The quest, Lucky Coin, available near Northshire Abbey, features some pretty terrible spelling, to the point where the objective of the quest is a little hard to understand. Examples of the spelling issues:
"Toss a coin with a wish for my short by return to Stormwind for good?"
"...I have a request for you. Hah, I've said that!" 
"I could possibly ask for one thing I desire to do...." 

**Steps to reproduce the behavior with as much detail as possible:**

1. Start a new character
2. Walk up to the quest giver (Teresa)
3. Read the quest

**IDs of affected creatures, items, quests or spells with a link to the relevant page:**

Quest: https://database.turtle-wow.org/?quest=60050

**Expected behavior. Describe how it should work:**

Grammatically the quest log needs a tune up in several ways. The quest says "Drop a coin to *the* trade district fountain", when it should be drop a coin *in* the trade district fountain. "Hah, i've said that!" should be "Hah, i've said it!" or "Hah, I finally said it!". "I'm so nervous to pick on people leaving the Abbey" should be "It makes me so nervous to approach people leaving the abbey". "But for me, it's the only way I could possibly ask for one thing I desire to do" should be  "But it's the only way I can possibly get my wish fulfilled".

In the next paragraph, "You see, I love to visit Stormwind from time to time when I'm on my trade trip to the Gallina Winery" should be "You see, I love visiting Stormwind when I go to trade at Gallina Winery". "I always walk by the Trade District Fountain which stands right next to the Bank" should be "I always walk past the trade district fountain, which is right next to the bank". 

The third paragraph is a bit of a mess and needs a complete rewriting. I propose "Could you toss a coin of mine into the fountain for good luck? I've heard that if you drop a coin into the fountain, your wish might get granted, and my wish is to visit Stormwind again as soon as possible!"

Those are my suggested alterations anyways.

**Comment by slowtorta** [comment]
Thank you for your suggestion! The edits will be implemented on the next server update :)
