### ISSUE TITLE
Cloth drop rates are lower than on Classic

### ISSUE THREAD

**Issue by tojothethief** [slowtorta/turtlewow-bug-tracker#127]
**Please, provide a clear description what the bug is:**
Cloth drop rates are about a half less than what they are on Classic, depending on specific cloth.

**IDs of affected creatures, items, quests or spells with a link to the relevant page:**
As an example, compare Splinter Fist Ogre's drop rates for wool on both Turtle and Classic dbs;

https://database.turtle-wow.org/?npc=889
https://classic.wowhead.com/npc=889/splinter-fist-ogre

**Comment by Nolin7777** [comment]
Won't change.
