### ISSUE TITLE
Quest - Seal of Ascension cannot be turned in

### ISSUE THREAD

**Issue by SaxxonPike** [slowtorta/turtlewow-bug-tracker#1270]
**Please, provide a clear description what the bug is:**

After completing the Emberstrife event and forging the Seal of Ascension, the quest cannot be turned in to Vaelan.

**Steps to reproduce the behavior with as much detail as possible:**

1. Do the Seal of Ascension quest, confronting Emberstrife and forge the seal (buggy in its own right, but that is already filed as a separate issue)
2. Approach Vaelan in LBRS so that he is interactable
3. Attempt to turn the quest in, but you can't, as there's no prompt to do so. Only gossip.

**IDs of affected creatures, items, quests or spells with a link to the relevant page:**

NPC: https://database.turtle-wow.org/?npc=10296 (Vaelan)
NPC: https://database.turtle-wow.org/?npc=10299 (Scarshield Infiltrator, before he has revealed himself)
Item: https://database.turtle-wow.org/?item=12324
Quest: https://database.turtle-wow.org/?quest=4743

**Expected behavior. Describe how it should work:**

You should be able to talk to Vaelan after he has revealed himself and turn in this quest.

**Comment by SaxxonPike** [comment]
Also, this is related to, *but not identical to*, this other issue filed with the quest:
https://github.com/slowtorta/turtlewow-bug-tracker/issues/1224

**Comment by SaxxonPike** [comment]
A friend had discovered that it is required to have **another** [Unadorned Seal of Ascension] in your bag, a random drop from LBRS, in order to get the chat options that will work.

**Comment by slowtorta** [comment]
Related to https://github.com/slowtorta/turtlewow-bug-tracker/issues/2091 (this quests event needs a rework in general)
