### ISSUE TITLE
Strat life bastion in combat bug 

### ISSUE THREAD

**Issue by geojak** [slowtorta/turtlewow-bug-tracker#1271]
**Please, provide a clear description what the bug is:**

Every second or so strat life run we got this same issue. Sometime inside bastion, most of the time in the last hallway until end boss, the group is suddenly stuck in combat. 

This is especially annoying as paladin thaz has no spirit and relies on drinking 
You also can't rezz

**Steps to reproduce the behavior with as much detail as possible:**

1. Go bastion strat life
2.  Around the last trash mobs until endboss
3. Sunddely in combat and can't get out

**IDs of affected creatures, items, quests or spells with a link to the relevant page:**

**Expected behavior. Describe how it should work:**

Pls investigate the random spawning undeads und crusaders if they cause this.

**Comment by geojak** [comment]
Happens more like 90% of times, only once so far it didn't bug out, well even that is not true, only one time somehow we were able to eventually get out of combat.

**Comment by Kruxis** [comment]
Greetings! Thanks for the report, the issue will be fixed on next server restart =)

**Comment by geojak** [comment]
Yes! Thy alot for fixing it. This one was one of the more annoying bugs! Rly looking forward to it on the next bastion run
