### ISSUE TITLE
FIery Plate Gauntlets proc Vengeance, but Storm Gauntlets do not. Also, they have the wrong sound effect.

### ISSUE THREAD

**Issue by gmarguelles** [slowtorta/turtlewow-bug-tracker#1274]
Reposting bug report due to Storm gauntlets not proccing vengeance.
Thank you for fixing it with Fiery Plate Gauntlets, those do work, but Storm Gauntlets do not.

Please, provide a clear description what the bug is:
The nature proc from Storm Gauntlets are not activating vengeance as it should
I have the gauntlets and after testing them, the damage proc criting does not proc vengeance
(Same might be true for 8/8 judgment paladin tier set proc)

Steps to reproduce the behavior with as much detail as possible:

Equip fiery plate gauntlets and storm gauntlets
Pick up vengeance talent
Attack until these items crit
Items will crit but only fiery plate gauntlets not proc vengeance
IDs of affected creatures, items, quests or spells with a link to the relevant page:

NPC: https://database.turtle-wow.org/?npc=
Item: https://database.turtle-wow.org/?item=
Quest: https://database.turtle-wow.org/?quest=
Spell: https://database.turtle-wow.org/?spell=
Object: https://database.turtle-wow.org/?object=

Expected behavior. Describe how it should work:

In classic warcraft these items proc the paladin ability vengeance, I have video proof from classic wow linked below:

https://drive.google.com/file/d/1vb5ts0uMxUdWl_-2mgRUYp2fb-qsnUbj/view?usp=sharing

https://drive.google.com/file/d/1-akeAvEpftm5g6iAvejs6hJXB-u8mUrH/view?usp=sharing

Bug might be because these triggers might not be considered spells for some reason within the TurtleWoW server, is this something that can be fixed? These items open up a new avenue and itemization options for ret paladins and protection paladins.

Thank you!

**Comment by geojak** [comment]
Do these elemental dmasge even work. Like a weapon with +elentsl damage, since it is not displayed anywhere

**Comment by gmarguelles** [comment]
Depends, for example War Blade of Caer Darrow's ice damage is folded into the weapons damage, so in that case its just one hit.

But with weapons like fiery retributer the fire damaghe on it is a separate proc that SHOULD proc vengeance separately

**Comment by geojak** [comment]
Actually my crimson blades fire smaage is displayed separately and it can procc vengeance. Rly nice

**Comment by gmarguelles** [comment]
Oh I see! Hopefully this will be fixed one of these days :c

**Comment by geojak** [comment]
I got the firey plate gauntlets too now, they seem to work asweel. Rly nice that they added +10 stam on them here on twow

**Comment by slowtorta** [comment]
Please test it after the next update and let me know if it's working now.
