### ISSUE TITLE
Fashion coins quests wrong text objective

### ISSUE THREAD

**Issue by Tinyfin-github** [slowtorta/turtlewow-bug-tracker#1275]
Fashion coins quests wrong quest text  objective. The quest text that tells you what items to  bring is the old one before the changes. The actual objective shows the correct needed items.

https://database.turtle-wow.org/?quest=60030  lv 10 bracket 
https://database.turtle-wow.org/?quest=60031  lv 20 bracket 
https://database.turtle-wow.org/?quest=60032 lv 30 bracket
https://database.turtle-wow.org/?quest=60033  lv 40 bracket
https://database.turtle-wow.org/?quest=60034 lv 50 bracket
https://database.turtle-wow.org/?quest=60035 lv 60 bracket 
https://database.turtle-wow.org/?quest=60036 Make the Right Choice

https://database.turtle-wow.org/?quest=60030  lv 10 bracket 

![image](https://user-images.githubusercontent.com/83077166/161495320-b841311c-1237-41d3-8e43-9c3a27ddd816.png)

https://database.turtle-wow.org/?quest=60031  lv 20 bracket 

![image](https://user-images.githubusercontent.com/83077166/161496019-098b4043-8a70-4f83-bb4f-7d43e59e77cc.png)

https://database.turtle-wow.org/?quest=60032 lv 30 bracket

![image](https://user-images.githubusercontent.com/83077166/161496660-69d5dc78-2d61-4c32-9e36-acc710f600aa.png)

https://database.turtle-wow.org/?quest=60033  lv 40 bracket

![image](https://user-images.githubusercontent.com/83077166/161497251-eefa01b6-e234-4b68-812f-c4c12e7a607d.png)

https://database.turtle-wow.org/?quest=60034 lv 50 bracket

![image](https://user-images.githubusercontent.com/83077166/161497814-2ce9776a-898d-4290-b40e-dcff0b9cf1ff.png)

https://database.turtle-wow.org/?quest=60035 lv 60 bracket 

![image](https://user-images.githubusercontent.com/83077166/161498189-3ecafb67-cef9-40d0-9b71-ae2124804e8d.png)

https://database.turtle-wow.org/?quest=60036 Make the Right Choice

![image](https://user-images.githubusercontent.com/83077166/161498585-3ba05fde-7235-41f0-98a2-c25cf3cf5692.png)

**Comment by Kruxis** [comment]
Even with fancy arrows 👀 Will fix today

**Comment by geojak** [comment]
See the last screenshot above. It said below again 5 orbs in the text.

**Comment by Kruxis** [comment]
Don't worry, everything's fixed =)
