### ISSUE TITLE
Southsea Buccaneer and Southsea Corsair give no experience

### ISSUE THREAD

**Issue by Tinyfin-github** [slowtorta/turtlewow-bug-tracker#1276]
Southsea Buccaneer and Southsea Corsair give no experience

https://database.turtle-wow.org/?npc=91845 Southsea Corsair
https://database.turtle-wow.org/?npc=91844 Southsea Buccaneer

https://user-images.githubusercontent.com/83077166/161566378-1934a0db-ee87-49a0-9095-9a5aa70a08c7.mp4

https://user-images.githubusercontent.com/83077166/161566388-e4590ef4-da04-4a8c-b1f6-5a7f243e6173.mp4

**Comment by slowtorta** [comment]
Fixed in the next revision!
