### ISSUE TITLE
Dire Maul East: Felvine Shard objects that drop after Alzzin the Wildshaper disappear after one minute

### ISSUE THREAD

**Issue by Tinyfin-github** [slowtorta/turtlewow-bug-tracker#1277]
Dire Maul East: Felvine Shard objects that drop after Alzzin the Wildshaper disappear after one minute

https://database.turtle-wow.org/?object=179559 Felvine Shard

https://user-images.githubusercontent.com/83077166/161593710-e4771ca6-0353-4d1b-b3eb-3abe31dffc42.mp4

**Comment by Kruxis** [comment]
How long does it last usually?

**Comment by slowtorta** [comment]
Fixed in the next revision.
