### ISSUE TITLE
Denalan is stuck in his farming animation

### ISSUE THREAD

**Issue by Tinyfin-github** [slowtorta/turtlewow-bug-tracker#1278]
Denalan is stuck in his farming animation

https://database.turtle-wow.org/?npc=2080 Denalan

https://user-images.githubusercontent.com/83077166/162141502-a7ff6051-27a4-437e-825c-599d1adb9248.mp4

He should not be in his farming animation at all times :
https://www.youtube.com/watch?v=6gTQRvZH9gU

**Comment by slowtorta** [comment]
Fixed in the next revision.
