### ISSUE TITLE
Resistances in AQ are too high

### ISSUE THREAD

**Issue by Lunkdunk** [slowtorta/turtlewow-bug-tracker#1279]
**Please, provide a clear description what the bug is:**
All mobs and bosses have a flat resistance of 75 to all schools of magic in AQ40. In AQ20 there are even higher resistances, bosses and mobs range from 115-155 (ossirian excluded). The resistance in classic seems to be roughly 30, see below.
**Steps to reproduce the behavior with as much detail as possible:**
To check the average damage mitigation casters get in classic I looked at elemental shamans, since no curse helps them with nature resistance. I exluded anyone with spellpen gear and only looked at boss encounters so the level-based resistance would be at a flat 24 resistance and 6% average damage mitigation from it. Thunderfury debuff was too prevalent to be excluded, but the shamans without this debuff showed no exception. That is a bit odd since the resistances doesnt seem to be 0, but it could just be a small sample.

Links to the 9 ele shamans I checked:
https://vanilla.warcraftlogs.com/reports/6b2AQDKWJxVqFv3r#type=damage-done&boss=-2&difficulty=0&source=32
https://vanilla.warcraftlogs.com/reports/Tnq1jP42XVfGgFdZ#type=damage-done&boss=-2&difficulty=0&source=34
https://vanilla.warcraftlogs.com/reports/Y7zcgkPXfwyMGhCD#type=damage-done&boss=-2&difficulty=0&source=29
https://vanilla.warcraftlogs.com/reports/6XdRpDPCzyHtWfkb#type=damage-done&boss=-2&difficulty=0&source=4
https://vanilla.warcraftlogs.com/reports/rWKHzxGMAZQ7w9Jc#type=damage-done&boss=-2&difficulty=0&source=48
https://vanilla.warcraftlogs.com/reports/t4xhrNLf3mcGbVjC#type=damage-done&boss=-2&difficulty=0&source=13
https://vanilla.warcraftlogs.com/reports/L6TwxgKYZCf1jDyn#type=damage-done&boss=-2&difficulty=0&source=16
https://vanilla.warcraftlogs.com/reports/8nT91ZVHx4DtrkYC#type=damage-done&boss=-2&difficulty=0&source=25
https://vanilla.warcraftlogs.com/reports/Wq8thLV4jMB6wrJn#type=damage-done&boss=-2&difficulty=0&source=57

I calculated the damage mitigation % of their lightning bolt to be 11,12%. Thunderfury debuff uptime was 41,2%, resulting in an average spellpen of 10,2 from the debuff (2,55% decrease of the damage mitigation). This results in an average nature resistance of roughly 30. To help estimating the resistances I used this:
https://royalgiraffe.github.io/legacy-sim/#/resistances
Calculations:
![Eleshaman_aq40](https://user-images.githubusercontent.com/85248554/162177098-43678adf-53f5-437d-96ba-eb74e43f960e.png)
[Eleshaman_aq40.xlsx](https://github.com/slowtorta/turtlewow-bug-tracker/files/8441880/Eleshaman_aq40.xlsx)
Edit: I also checked a few elemental shamans in AQ20 but didnt make any calculations. They seem to get the same amount of resists.
**IDs of affected creatures, items, quests or spells with a link to the relevant page:**

NPC: All mobs and bosses in AQ20 and AQ40, excluding Ossirian the Unscarred. 
Item: https://database.turtle-wow.org/?item=
Quest: https://database.turtle-wow.org/?quest=
Spell: https://database.turtle-wow.org/?spell=
Object: https://database.turtle-wow.org/?object=

**Expected behavior. Describe how it should work:**
Lower the resistances of bosses and mobs in AQ to atleast 30.

**Comment by geojak** [comment]
Aren't the raids already easy enough? It think harder than classic raids might be desirable

**Comment by Lunkdunk** [comment]
We have harder raids than classic and they will still be harder even if the resistance is lowered. This mostly punishes off-meta specs like ele shamans who cannot get the benefit of a curse, or when the composition isn't optimal with 3 warlocks. Boss armor got reduced before so you could reduce it to 0 with debuffs, I think it would be fair for casters to get theirs. Armor and resistances aren't a good way of making bosses harder, you just do less damage than you did in raids prior.

**Comment by geojak** [comment]
Then just lower nature resistance only?

**Comment by Lunkdunk** [comment]
Curse of shadow lowers arcane resistance too, but thats not addressing my point about lock composition. Curse of elements/shadow is now more than 30% increase in dps, 10% from the flat bonus and more than 20% from the resistance reduction. If you have 3 warlocks and no off-meta specs my changes would not make AQ easier.

**Comment by geojak** [comment]
But you do need 3 curse of shadows currently, it does reduce the need for coordinated play of 3 curse of shadows then.

Just lower nature ress, since it only affects shamans and moonkins, or alternately introduce a new debuff form to lower nature ress and increase holy dmasge (no ress here) as a copy of curse of shadow and elements for meme speccs.

Then remove debug limit

**Comment by Lunkdunk** [comment]
3 curse of shadows? I'm not sure what you mean with that. 3 locks means we have curse of reck/elements/shadows. Debuff slots have been discussed for a long time but lead to nothing. Your suggestion about getting yet another debuff of the already highly contested debuff slots would make group composition even more fragile. My suggestion is much more simple.

**Comment by Lunkdunk** [comment]
If a new spell would be introduced it would be nice if curse of elements and curse of shadows became one spell like in TBC. It could reduce nature resist too.

**Comment by slowtorta** [comment]
I'm sorry but at this point of the server's progression, we don't want to change AQ mob stats, nor the dungeon difficulty. This raid is being successfully farmed by several raiding groups.
