### ISSUE TITLE
Completing a  A New Rune-Frontier should not remove Untempered Runeblade

### ISSUE THREAD

**Issue by Fin9622** [slowtorta/turtlewow-bug-tracker#1280]
Completing a  A New Rune-Frontier  https://database.turtle-wow.org/?quest=40234 should not remove Untempered Runeblade https://database.turtle-wow.org/?item=60293

https://user-images.githubusercontent.com/83077166/162197385-f507406b-03d4-4c54-be66-81af90e5fbdc.mp4

**Comment by Neto-WoW** [comment]
Working as intended. Please see Dormilon for more info.
