### ISSUE TITLE
av neverstopping npc respawning

### ISSUE THREAD

**Issue by geojak** [slowtorta/turtlewow-bug-tracker#1281]
**Please, provide a clear description what the bug is:**

from my source 
https://classic.wowhead.com/guides/alterac-valley-battleground-strategy-wow-classic
which is backed by personal classic experience of players i have talked to in game in twow

"Lieutenants are fairly weak elites that can be killed by a skilled player or a few players. Killing Lieutenants grants bonus honor, and disables the respawning of some enemy troops."

"Commanders
Commanders occupy the Towers/Bunkers and patrol the Graveyards of their faction while providing a moderate buff to nearby players.

Commanders are moderately tough elites that can be killed by a few players. Killing Commanders grants bonus honor, and disables the respawning of some enemy troops. Be careful to pull Commanders well away from other titled elites, as some of them buff and/or heal other NPCs."

**Steps to reproduce the behavior with as much detail as possible:**

1. kill a liteunant
2. sourding npcs still respawn in his region
3. endless grindfest intesifies

from patch 1.6:
"Alterac Valley's guard spawn is now controlled via a more intuitive mechanism. Please check the Officer Supply vendors for your faction to read up on the changes."

this referes to the ingame book peeling of the onion in which it also describes killing officers to stop respawn 
https://classic.wowhead.com/item=19483/peeling-the-onion

**Expected behavior. Describe how it should work:**

what this means is, if you kill the lieutenants, the surdoung regular npcs guards and patrols resapwn should be disabled. similair how archers dotn respawn in destroyed towers, and mine stop when the minelayer died

unfortunetly more precise data is hard to find, but this is proof that there is a general thing wrong with av on twow

p.s. i was told this has been reported on the forum a year ago already, but i was not able to find it

**Comment by LeopoldHock** [comment]
You seem to refer to the 1.6 version of AV, while Turtle runs 1.12.

**Comment by geojak** [comment]
Turtle wow has the orc tooth etc turn ins with was not present in 1.12, twow also has mines and mine layers which are removed in 1.12

**Comment by geojak** [comment]
could you pls loot into this? these unrestricted patrol respawns are currently killing the av scene since they enable endless turtleing
