### ISSUE TITLE
Level requirements for weapon training (except polearms) did not exist in Vanilla

### ISSUE THREAD

**Issue by Nadare76** [slowtorta/turtlewow-bug-tracker#1283]
On current Turtle WoW, weapon training requires level 5, but on Vanilla, it only required level one as can be seen here:

https://wowpedia.fandom.com/wiki/Weapon_master?type=revision&diff=22127&oldid=5295

This edit is from Vanilla-time and has not been challenged, and in addition to that, while polearms are clearly mentioned as requiring a certain level in the WoWhead comments of the era, none do for other weapon skills; I think this is sufficient evidence to say those requirements did not exist.

**Comment by slowtorta** [comment]
It'll be fixed in the next revision!
