### ISSUE TITLE
When using a bow as the Dryad Illusion, the bow is held it the wrong hand.

### ISSUE THREAD

**Issue by ameliandra** [slowtorta/turtlewow-bug-tracker#1286]
**Please, provide a clear description what the bug is: When you use a dryad illusion from the donation rewards, if you equip a bow, the bow is in the wrong hand, which leads to having an inverted attack animation where the bow gets pulled back instead of a string.

**Steps to reproduce the behavior with as much detail as possible:**

1. Use the dryad illusion.
2. Equip a bow.
3. Attack an enemy with the bow.
4. Notice that the bow and string and in the wrong hands.

**IDs of affected creatures, items, quests or spells with a link to the relevant page:**

NPC: https://database.turtle-wow.org/?npc=
Item: https://database.turtle-wow.org/?item=
Quest: https://database.turtle-wow.org/?quest=
Spell: https://database.turtle-wow.org/?spell=
Object: https://database.turtle-wow.org/?object=

**Expected behavior. Describe how it should work:**

**Comment by geojak** [comment]
I have seen this reported before here somewhere

**Comment by slowtorta** [comment]
Known issue, present in our internal client tracker, we're looking into it.
