### ISSUE TITLE
wrong spell bonus at gear

### ISSUE THREAD

**Issue by TorTun** [slowtorta/turtlewow-bug-tracker#1289]
[Embersilk Tunic of Arcane Wrath] got to low spell bonus for 37 lvl gear

![image](https://user-images.githubusercontent.com/95168215/162646079-e48cac15-9d69-4403-be5e-142d9e263c35.png)

**Comment by geojak** [comment]
Now that's bis gear

**Comment by slowtorta** [comment]
This item already has the correct random_property ID assigned. You've been just unlucky.
![image](https://user-images.githubusercontent.com/66763404/164278811-1bab2529-d506-4dcf-a5d2-2ffc259fb1d0.png)
