### ISSUE TITLE
Bugged mob ability (that will kill HC players) - Disease Cloud by Abomination (lvl60) in Fungal Vale in EPL

### ISSUE THREAD

**Issue by GravitusHC** [slowtorta/turtlewow-bug-tracker#129]
**Please, provide a clear description what the bug is:**

I engaged a lvl60 normal mob "Abomination" in Fungal Vale on character Gravius at approx. 11:25PM-11:29PM EST. It immediately spammed "Disease Cloud" insanely fast - something like 5-10 ticks in a matter of a second (where it should have only been 1 tick) taking a massive chunk of my HP away. It continued to do so every second/half a second. I would have died if I weren't a paladin (I bubble-hearthed out). It was ticking average 7 ticks in duration of what should have been 1 tick.

**Steps to reproduce the behavior with as much detail as possible:**

1. Go to Fungal Vale
2. Attack lvl60 green "Abomination"
3.  Get murdered by it's insanely fast ticking Disease Cloud aura

**IDs of affected creatures, items, quests or spells with a link to the relevant page:**

https://classic.wowhead.com/npc=8545/abomination

**Expected behavior. Describe how it should work:**

It should only tick once. Not multiples of times.

**Comment by Velite12** [comment]
Just to confirm that this also occurs for Abominations inside of Stratholme who also have this disease cloud. Have not seen it happen in Naxxramas yet however.

**Comment by slowtorta** [comment]
Upon trying several times, I was unable to reproduce this bug. Please, make a video if the issue is till present and re-open this issue.
![image](https://user-images.githubusercontent.com/66763404/127880158-014f479f-fca7-48d5-b1eb-2551d2f93f66.png)

**Comment by Tinyfin-github** [comment]
Issue still persists and i was able to reproduce:

https://user-images.githubusercontent.com/83077166/170854155-25233805-69e6-4063-a935-07b2186c0af7.mp4

**Comment by GravitusHC** [comment]
The patrolling abomination does this too, but not always (I wasn't able to figure out what the exact trigger is on my interactions with it).

**Comment by GravitusHC** [comment]
The gray blobs in the hole with HEelf quest near Glenshire (Tirisfal Glades) did the same thing yesterday where they hit a lot of times instantly with whatever ability or aura they were doing.

**Comment by slowtorta** [comment]
Hopefully fixed, please re-open if the issue persists.
