### ISSUE TITLE
Corssfaction loot

### ISSUE THREAD

**Issue by geojak** [slowtorta/turtlewow-bug-tracker#1290]
**Please, provide a clear description what the bug is:**

When for example shaman hear drops in mc, then alliance players can't see it. Problem is, then you need to change loot master just for that to work around the bug 

**Steps to reproduce the behavior with as much detail as possible:**

1. Have a shaman libram drop for example in scholo
2. Alliance players can't see the loot
3. In raids it becomes extra cumbersome with loot master system 

**IDs of affected creatures, items, quests or spells with a link to the relevant page:**

NPC: https://database.turtle-wow.org/?npc=
Item: https://database.turtle-wow.org/?item=
Quest: https://database.turtle-wow.org/?quest=
Spell: https://database.turtle-wow.org/?spell=
Object: https://database.turtle-wow.org/?object=

**Expected behavior. Describe how it should work:**

Crossfacrion enabled, therefor no more faction specific loot

**Comment by slowtorta** [comment]
Fixed in the next revision. Now both factions will be able to see faction-restricted loot if they're in a dungeon or a raid.
