### ISSUE TITLE
Ratchet Flight master bug 

### ISSUE THREAD

**Issue by gigachadbro** [slowtorta/turtlewow-bug-tracker#1292]
**Please, provide a clear description what the bug is:**

Hey , i try to use flight path from ratchet to orgrimmar , it says to me : " Unspecified taxi error  " , but when i clicked on crossroads it does work normally . 
 

NPC: flight master ratchet
Item: flying to orgrimmar
Spell: taxi flying service between towns

**Expected behavior. Describe how it should work:**
It should bring me to orgrimmar normally , i have necessary money for this .

**Comment by slowtorta** [comment]
Hello. This is fixed in the internal build of patch 1.16.1. I'll soon be released :)

**Comment by gigachadbro** [comment]
great , keep up the good job :D

**Comment by nonameform** [comment]
Hopefully this also fixes other flight master but I have encountered in Searing Gorge. Could not fly from there to Loch Modan. Had to fly to Ironforge first.
