### ISSUE TITLE
Blackfathom Depths - Lady Sarevess Slow Bug

### ISSUE THREAD

**Issue by AyleeJenn** [slowtorta/turtlewow-bug-tracker#1293]
**Please, provide a clear description what the bug is:**
The optional boss "Lady Sarevess" in the dungeon "Blackfathom Depths" has a spell that shows and reads as "Slow". It is supposed to slow the player's movement speed and their attack speed. However, the spell actually -roots- the player in place so that they cannot move.

**Steps to reproduce the behavior with as much detail as possible:**

1. Enter Blackfathom Depths and seek out the optional battle with Lady Sarevess
2.  Observe closely as she casts slow on the party and try to move with the W,S, A and D keys
3. Note how movement is not possible

**IDs of affected creatures, items, quests or spells with a link to the relevant page:**

NPC: https://database.turtle-wow.org/?npc=4831

**Expected behavior. Describe how it should work:**
The "slow" spell cast on the players by Lady Sarevess should only slow the players but not root them in place. At least if the description is to be believed.

**Comment by slowtorta** [comment]
She doesn't have Slow spell on Turtle WoW, nor in Vanilla in general (this one had been added only in Cata). On TW she's using Frost Nova to root players for a few seconds, this is a correct behavior :)
