### ISSUE TITLE
Blackfathom Depths - Shadowmage Mindcontrol Bug

### ISSUE THREAD

**Issue by AyleeJenn** [slowtorta/turtlewow-bug-tracker#1294]
**Please, provide a clear description what the bug is:**
In the dungeon "Blackfathom Depths" near the end you can find Twilight Shadow mages who will often try to mind control player characters. By default, the player should be able to counterspell the attempt to mind control a player provided they notice and counterspell in time. However, testing has showed that the casting of mind control by twilight shadow mages can -NOT- be counter spelled even if the mage catches it in time. The counter spell will hit but the mind control will finish casting and either get resisted by the player or hit the player who is then mind controlled until the enemy shadow mage is defeated

**Steps to reproduce the behavior with as much detail as possible:**

1. Enter Blackfathom Depths and proceed to where Twilight shadow mages can be found to initiate combat with one
2. Attempt to counter spell the mind control spell they cast on one of the players
3. Note how the counter spell -does- hit but the mind control finishes casting anyways

**IDs of affected creatures, items, quests or spells with a link to the relevant page:**

NPC: https://database.turtle-wow.org/?npc=4813

**Expected behavior. Describe how it should work:**
The counter spell should interrupt the mind control spell and forbid casting shadow magic for ten seconds, or however long counter spell forbids casting the same magic that was counter spelled.

**Comment by slowtorta** [comment]
I'm sorry, not enough information. Please provide a video of its behavior from Classic PTR. It's possible that this spell isn't conterspellable due to this dungeon's encounter design.
