### ISSUE TITLE
Cannot be disenchanted - Mountain Watcher's Crown

### ISSUE THREAD

**Issue by AyleeJenn** [slowtorta/turtlewow-bug-tracker#1295]
**Please, provide a clear description what the bug is:**
Item cannot be disenchanted

**Steps to reproduce the behavior with as much detail as possible:**

1. Complete the wetlands quest "Retaking The Roadways" of the new area Dun Agrath
2. Try disenchanting the quest reward helmet "[Mountain Watcher's Crown](https://database.turtle-wow.org/?item=81402)"
3. Observe as an error is reported that the item cannot be disenchanted

**IDs of affected creatures, items, quests or spells with a link to the relevant page:**

Item: https://database.turtle-wow.org/?item=81402
Quest: https://database.turtle-wow.org/?quest=55201

**Expected behavior. Describe how it should work:**
The item should disenchant into something

**Comment by slowtorta** [comment]
Fixed in the next revision.
