### ISSUE TITLE
Cannot be disenchanted - Oscilation Inhibited Disc

### ISSUE THREAD

**Issue by AyleeJenn** [slowtorta/turtlewow-bug-tracker#1296]
**Please, provide a clear description what the bug is:**
item cannot be disenchanted

**Steps to reproduce the behavior with as much detail as possible:**

1. Complete the quest "Oscilation Inhibited Disc!" in Hawk's Vigil
2. Try disenchanting the quest reward "Oscilation Inhibited Disc"
3. Observe as an error is reported as the item cannot be disenchanted

**IDs of affected creatures, items, quests or spells with a link to the relevant page:**

Item: https://database.turtle-wow.org/?item=81411
Quest: https://database.turtle-wow.org/?quest=55211

**Expected behavior. Describe how it should work:**
The item should disenchant into something.

**Comment by slowtorta** [comment]
Fixed in the next revision.
