### ISSUE TITLE
Cannot be Counterspelled - Shadowfang Moonwalker

### ISSUE THREAD

**Issue by AyleeJenn** [slowtorta/turtlewow-bug-tracker#1297]
**Please, provide a clear description what the bug is:**
In the dungeon "Shadowfang Keep" a certain enemy called "Shadowfang Moonwalker" casts a shield that makes them immune to magic. But it takes a few seconds to ask it. In this brief window of opportunity the mage ability "counterspell" should be able to interrupt the casting so long as the anti-magic shield is not yet online. But counter does not interrupt it.

**Steps to reproduce the behavior with as much detail as possible:**

1. Enter shadowfang keep nd find a Shadowfang Moonwalker to engage in combat.
2. Try counter spelling when it starts the casting time for the anti magic shield
3. Observe how counterspell does not interrupt the casting

**IDs of affected creatures, items, quests or spells with a link to the relevant page:**

NPC: https://database.turtle-wow.org/?npc=3853

**Expected behavior. Describe how it should work:**
Counterspell should be able to interrupt the casting of the anti-magic shield of the Shadowfang Moonwalkers so long as the casting is not complete.

**Comment by slowtorta** [comment]
I'm sorry, not enough information. Please provide a video of its behavior from Classic PTR. It's possible that this spell isn't conterspellable due to this dungeon's encounter design.
