### ISSUE TITLE
acid spit not poision 

### ISSUE THREAD

**Issue by geojak** [slowtorta/turtlewow-bug-tracker#1299]
**Please, provide a clear description what the bug is:**

the elite hydra letashaz uses an acid spit ability. its should be tagged as posion and dispeable, but its tagged with nothing and cant be dispelled

**Steps to reproduce the behavior with as much detail as possible:**

1. engage letashaz elite hydra on gijim iland at the naga mine
2. get hit my acid spit
3. try to dispell oison
4. doesnt work

**IDs of affected creatures, items, quests or spells with a link to the relevant page:**

https://database.turtle-wow.org/?npc=92163

**Expected behavior. Describe how it should work:**

acid spit should be a poison

**Comment by slowtorta** [comment]
This one is intended.
