### ISSUE TITLE
Trinket "Chained Essence of Eranikus"

### ISSUE THREAD

**Issue by BRBScratcher** [slowtorta/turtlewow-bug-tracker#13]
By opening this Issue, I admit to having done the pertinent research using sources from Vanilla (preferably) or Classic. I also understand that sources from other private servers are not acceptable.

**Current behavior**: 

Everytime the trinket is used, the following text appears in chat:
"Eranikus the Chained whispers: error

**Expected behavior**: 
the following whispers should actually appear (only 1 each time you use the trinket):

"Will the nightmare ever end?! I cannot force myself awake!"
"My soul is not a trinket! Mortal, you must release me from these chains!"
"My eyes! It burns... it burns..."
"Torture me no more! Release me, mortal! The Swamp of Sorrows... mortal... please..."
"Foolish mortal, I will rend your soul in two once I am released!"
"Foolish mortals you do not yet see the potential of that Artifact."
"You are an agent of their wicked god, fool. I will see you destroyed!"
"It hurts so much... Itharius, my old friend... Please help me..."
"My charge to watch the temple has failed... my corrupted soul knows no peace..."

**Proofs**:
https://wowwiki-archive.fandom.com/wiki/Chained_Essence_of_Eranikus

![Unbenannt](https://user-images.githubusercontent.com/50635128/122156812-0921d700-ce6a-11eb-8f37-adeedfc24395.jpg)

**Steps to reproduce**:

1. equip the trinket Chained Essence of Eranikus
2. target an enemy
3. rightclick to use the trinket
[](url)

**Comment by slowtorta** [comment]
Thanks for reporting it. It'll be fixed on the next server restart. Make sure to clear your WDB folder.
