### ISSUE TITLE
[ROGUE] Sap can't proc poisons onto targets

### ISSUE THREAD

**Issue by imaglcian** [slowtorta/turtlewow-bug-tracker#130]
By opening this Issue, I admit to having done the pertinent research using sources from Vanilla (preferably) or Classic. I also understand that sources from other private servers are not acceptable.

**Please, provide a clear description what the bug is:**
Sap is unable to proc poisons at the moment, never has been.

**Current Behavior:** 
Sap cannot proc rogue poisons, but it can proc on-hit effects like Misplaced Servo Arm (not weapon enchants/buffs) - Sap should therefore also be able to proc Crusader, Lifestealing etc.

**Expected Behavior:**
Saps should be able to proc poisons.

**Proofs**
https://youtu.be/kf04RPqMml4?t=55
https://youtu.be/cwtxj-ubudw?t=43

**Comment by imaglcian** [comment]
Would also like to add, poisons should not break a sap/gouge as seen here. (Shadowguard proc and Sap break, note how I was facing 90 degrees, not in melee range, but I can just hit with abilities, it wasn't a melee attack.) : https://youtu.be/6cRgE0mYNOM?t=10) - https://youtu.be/xTa9WTGCGaI?t=21 for reference. (Crusader and Poison proc via cheap shot, also not possible here. Doesn't break sap)

*Other proofs:*
https://youtu.be/xTa9WTGCGaI?t=53
https://youtu.be/xTa9WTGCGaI?t=139
https://youtu.be/8Gy8bydO_Hw?t=11
https://youtu.be/DhWRkCvWovI?t=774

**Comment by Nolin7777** [comment]
Possible fix has been applied, please test after next maintenance.
