### ISSUE TITLE
hermits wrath not tagged as elite

### ISSUE THREAD

**Issue by geojak** [slowtorta/turtlewow-bug-tracker#1300]
**Please, provide a clear description what the bug is:**

the lapidis iland elite troll qeust the hermits warth is not tagged as elite. the names elites you should kill are elite thought, so the quest should be elite too

**IDs of affected creatures, items, quests or spells with a link to the relevant page:**

https://database.turtle-wow.org/?quest=40213

**Expected behavior. Describe how it should work:**

tagg the qeust as elite

**Comment by Kruxis** [comment]
Thanks for the report, will be fixed on next restart
