### ISSUE TITLE
water elementals doing fire damage instead

### ISSUE THREAD

**Issue by geojak** [slowtorta/turtlewow-bug-tracker#1301]
**Please, provide a clear description what the bug is:**

the water elemtals at lapidis iland tower do fire dmaage

**Steps to reproduce the behavior with as much detail as possible:**

1. engage water lemental at lapidis iland
2. check combat log
3. its fire damage

**IDs of affected creatures, items, quests or spells with a link to the relevant page:**
![WoWScrnShot_041322_220601](https://user-images.githubusercontent.com/25199983/163264292-316ff131-b214-4149-93a5-696bd87ea724.jpg)

https://database.turtle-wow.org/?npc=60468

**Expected behavior. Describe how it should work:**

water elemtals do water dmaage

**Comment by geojak** [comment]
ps the water lementals also have 0 loot which sucks

**Comment by slowtorta** [comment]
Fixed in the next revision.
