### ISSUE TITLE
arch hydromancer lapidis doesnt use any spell

### ISSUE THREAD

**Issue by geojak** [slowtorta/turtlewow-bug-tracker#1303]
**Please, provide a clear description what the bug is:**

the arch hydromancer lapidis doesnt use a single spell, he just fist fight you. what a joke of an arch frostmage

**Steps to reproduce the behavior with as much detail as possible:**

1. fight the archmage in lapidis tower
2. he is an ARCHMAGE
3. he only fist fights

**IDs of affected creatures, items, quests or spells with a link to the relevant page:**

https://database.turtle-wow.org/?npc=60467

**Expected behavior. Describe how it should work:**

archhydromancer should know spells.
frostnova, frost cone of cold, maybe summon some more water eles, frost mage armor buff.

**Comment by slowtorta** [comment]
Fixed in the next revision.
