### ISSUE TITLE
lapidis tower key is not a key

### ISSUE THREAD

**Issue by geojak** [slowtorta/turtlewow-bug-tracker#1304]
**Please, provide a clear description what the bug is:**

it would be nice it this key could be tagged as key so palyers can store it in their keychain to keep acces to the lapidis tower

**IDs of affected creatures, items, quests or spells with a link to the relevant page:**

https://database.turtle-wow.org/?item=60302

**Expected behavior. Describe how it should work:**

keys should go inside the keyring

**Comment by slowtorta** [comment]
Sorry, it's a quest item that you don't even store for that long.
