### ISSUE TITLE
silent icebeears 

### ISSUE THREAD

**Issue by geojak** [slowtorta/turtlewow-bug-tracker#1307]
**Please, provide a clear description what the bug is:**
 the icepoint bears are very silent, dont make bear sound

https://database.turtle-wow.org/?npc=60545

**Expected behavior. Describe how it should work:**
bears should make bear sounds in combat

**Comment by slowtorta** [comment]
Fixed in 1.16.1 :)

**Comment by geojak** [comment]
rawr <3 :)
