### ISSUE TITLE
Quest item persist after completion of quest 

### ISSUE THREAD

**Issue by gigachadbro** [slowtorta/turtlewow-bug-tracker#1308]
**Please, provide a clear description what the bug is:**
quest item " Sunscale Feather " , stay in bags after the quest is done 

**IDs of affected creatures, items, quests or spells with a link to the relevant page:**

Item: https://database.turtle-wow.org/?item=5165
Quest: https://database.turtle-wow.org/?quest=905

**Expected behavior. Describe how it should work:**
quest items should be deleted after completion or deletion of a quest 
![image](https://user-images.githubusercontent.com/46192630/163497766-d5e2cbbb-0d43-412b-b5d4-3b100670bdc7.png)

**Comment by Neto-WoW** [comment]
@gigachadbro - Thanks for the report. Can you please attempt this quest without using bag addons? I tested and it removed the items upon quest completion.

**Comment by slowtorta** [comment]
Tested, working as intended. You have to clear your cache and try it without the addon!
