### ISSUE TITLE
Item persist on bag after completion of "nugget slugs " quest 

### ISSUE THREAD

**Issue by gigachadbro** [slowtorta/turtlewow-bug-tracker#1309]
Please, provide a clear description what the bug is:
quest item " Sunscale Feather " , stay in bags after the quest is done

IDs of affected creatures, items, quests or spells with a link to the relevant page:

Item: https://database.turtle-wow.org/?item=11143
Quest: https://database.turtle-wow.org/?quest=3922

Expected behavior. Describe how it should work:
quest items should be deleted after completion or deletion of a quest
![image](https://user-images.githubusercontent.com/46192630/163505885-2e9f4755-214b-4d7b-89bc-43ad8b6a6ff0.png)

**Comment by slowtorta** [comment]
Hello. I tested it and couldn't reproduce the issues, I'm sorry.
