### ISSUE TITLE
ores not marked as underground on giljim iland

### ISSUE THREAD

**Issue by geojak** [slowtorta/turtlewow-bug-tracker#1310]
**Please, provide a clear description what the bug is:**

at the deeptide sacntum is a cave with an elite hydra in front.
inside is has 2 small thorium mines vains
these two vains are not displayed in greyed colour when you are outside the cave
normally mines in caves are showned greyed out to indicate to the player they are underground
ever more, once you go inside the cave, the thorium veins dont show up at all on the minimap anymore

**Steps to reproduce the behavior with as much detail as possible:**

1. go to the cave behind the hydra 
2. dont go in, and check minimpa for thorium, see them in yellow
3. go inside, check minimap ,no more thorium displayed despite them being in there

**Expected behavior. Describe how it should work:**

throium displayed in the cave in yellow (instead of missing)
thorium displayed in grey whn you are outside

**Comment by slowtorta** [comment]
Ye, it's some client glitch, can't really do anything about it, sorry.
