### ISSUE TITLE
black copper vein , bug ? 

### ISSUE THREAD

**Issue by gigachadbro** [slowtorta/turtlewow-bug-tracker#1313]
**Please, provide a clear description what the bug is:**

**Steps to reproduce the behavior with as much detail as possible:**

this copper vein , is black lol , it should looks white  , its near crossroads on the mountain near it , this is a bug mostly .

Object: Copper Vein 

**Expected behavior. Describe how it should work:**
it should be white 

![image](https://user-images.githubusercontent.com/46192630/163726468-64c201c9-d2d6-4c6e-a5a2-a1944f13bd8c.png)

**Comment by slowtorta** [comment]
Sorry, all the ore nodes look normal and the same to me on that Hill. Probably just a random lighting bug in your client :) Nothing we can do about it!
