### ISSUE TITLE
Consumed By Hatred quest bug !

### ISSUE THREAD

**Issue by gigachadbro** [slowtorta/turtlewow-bug-tracker#1315]
**Please, provide a clear description what the bug is:**
When i valid the quest , the game did crashed for me . 
This is the reward i did choosed btw : Boar Hunter's Cape

**IDs of affected creatures, items, quests or spells with a link to the relevant page:**

NPC: https://database.turtle-wow.org/?npc=3432
Item: https://database.turtle-wow.org/?item=5314
Quest: https://database.turtle-wow.org/?quest=899
Spell: https://database.turtle-wow.org/?spell=
Object: https://database.turtle-wow.org/?object=

**Expected behavior. Describe how it should work:**
game shouldnt crash

**Comment by slowtorta** [comment]
![image](https://user-images.githubusercontent.com/66763404/164293247-444e92c7-2013-4ace-a770-5ec998575050.png)
![image](https://user-images.githubusercontent.com/66763404/164293272-4f63c678-ee21-47af-8541-3d3d40309aeb.png)
![image](https://user-images.githubusercontent.com/66763404/164293295-e58583a8-3892-48dc-bc04-bfc2c64f4018.png)

I was able to complete this quest w/o issues. Please ensure you aren't using any additional patches. best if you re-download the game client from our website!
