### ISSUE TITLE
Haunting Spirits makes ghost spawn too fast

### ISSUE THREAD

**Issue by Tinyfin-github** [slowtorta/turtlewow-bug-tracker#1316]
https://database.turtle-wow.org/?spell=7057 Haunting Spirits makes ghost spawn too fast

Classic: https://youtu.be/PQOifDDT6z8?t=1025
Turtle: https://youtu.be/uMMm_GCuNYI

**Comment by slowtorta** [comment]
Fixed in the next revision.
