### ISSUE TITLE
Vorsha the Lasher event broken

### ISSUE THREAD

**Issue by Tinyfin-github** [slowtorta/turtlewow-bug-tracker#1317]
Vorsha the Lasher event broken  https://database.turtle-wow.org/?quest=6641

Turtle: https://youtu.be/nn0gF3Lpcj8
Classic: https://www.youtube.com/watch?v=Hua5mdj0vT0

**Comment by geojak** [comment]
Maybe related https://github.com/slowtorta/turtlewow-bug-tracker/issues/913

**Comment by slowtorta** [comment]
Dublicate.
