### ISSUE TITLE
NPC: Boiling Elemental (ability cooldown)

### ISSUE THREAD

**Issue by Firestoat** [slowtorta/turtlewow-bug-tracker#1320]
The Boiling Elemental NPC mob in 1000 Needles has an incorrect short cooldown on its Steam Jet ability. The mob can currently keep a 100% uptime on the ability for a character to suffer a miss chance during the full fight with one. This is incorrect - on retail WoW in the 2004/2005 era the mob would have a cooldown on the ability that was greater than its duration by 4 seconds or so which would give a melee character a chance to spam abilities to kill it or at least greatly injure it so it could be finished off.

TurtleWoW Mob Link -- https://database.turtle-wow.org/?npc=10757
TurtleWoW Mob Ability Link -- https://database.turtle-wow.org/?spell=11983

WoWHead Classic Mob Link -- https://classic.wowhead.com/npc=10757/boiling-elemental
WoWHead Classic Ability Link -- https://classic.wowhead.com/spell=11983/steam-jet

TurtleWoW In Game Image -- https://postimg.cc/gx6FVVp0

**Comment by slowtorta** [comment]
Fixed: https://github.com/slowtorta/turtlewow-bug-tracker/issues/1142
