### ISSUE TITLE
Sprite Darter NPC (Adds Null Reputation to Character)

### ISSUE THREAD

**Issue by Firestoat** [slowtorta/turtlewow-bug-tracker#1322]
The Sprite Darter NPC Mob near the horde outpost in Feralas is giving a horde character a null faction entry the moment they are clicked on.

TurtleWoW NPC Link -- https://database.turtle-wow.org/?npc=5278

WoWHead Classic NPC Link -- https://classic.wowhead.com/npc=5278/sprite-darter

To replicate this bug, simply take a fresh horde character to Feralas and click on the mob from a distance to gain the Null reputation entry in the character panel.

TurtleWoW In Game Image -- https://postimg.cc/zyMhM14j

**Comment by slowtorta** [comment]
This is fixed in the internal build of the upcoming P1.16.1.
