### ISSUE TITLE
Cannot be De-Cursed - Gift of Arugal (Archmage Arugal Version)

### ISSUE THREAD

**Issue by AyleeJenn** [slowtorta/turtlewow-bug-tracker#1323]
**Please, provide a clear description what the bug is:**
In the dungeon "Shadowfang Keep" the final battle against sorcerer Arugal features a curse that is called "Arugal's Gift". This debuff is labled as a curse. its the one where a player is temporarily made to look like a worgen and attack other players. However, if you try to use "Remove Curse" on that curse debuff, it says "There is nothing to dispell". And it won't let you remove a curse even though it is listed as a curse.

NOTE: This only seems to affect the version cast by _archmage arugal_.
Note 2: This has been tested with the de-cursing player being unaffected by the debuff and trying to "remove curse" on a different player affected by the debuff.

**Steps to reproduce the behavior with as much detail as possible:**

1. Run "Shadowfang Keep" dungeon up to the final battle against Archmage Arugal
2. Play a class that can remove curses and wait until someone gets the "Gift of Arugal" curse type debuff
3. Attempt to cast "Remove Curse" on someone with the curse type debuff "Gift of Arugal"

**IDs of affected creatures, items, quests or spells with a link to the relevant page:**

NPC: https://database.turtle-wow.org/?npc=4275

**Expected behavior. Describe how it should work:**
I feel it would make sense if the curse "Gift of Arugal" can be dispelled with "Remove Curse". One would expect that remove curse removes curses, no?

**Comment by slowtorta** [comment]
Could you please provide any video of this to happen in Vanilla or Classic WoW? Sometimes Blizzard itself isn't really logical and some spells don't have the attributes they look like they should have.

**Comment by slowtorta** [comment]
Tested this morning, and could decurse it without issues.
