### ISSUE TITLE
Horde Quest: The Black Shield (Item Bug)

### ISSUE THREAD

**Issue by Firestoat** [slowtorta/turtlewow-bug-tracker#1324]
For the 3rd step of the Horde Quest of the Black Shield in Dustwallow Marsh, the player is to gather some Acidic Venom Sac items that are a drop from killing spiders near the Horde Outpost in the zone. The issue is that the Acidic Venom Sac items either are not dropping, or have an extremely low drop rate that is not in line with old 2004/2005 retail WoW. I was able to do the "Jarl Needs Eyes" quest given in the zone, requiring 40 spider eyes, with 2 different characters with neither one getting a single Acidic Venom Sac. Screenshot proof down below.

TurtleWoW Quest Link -- https://database.turtle-wow.org/?quest=1322
TurtleWoW Acidic Venom Sac Link -- https://database.turtle-wow.org/?item=5959

Classic WoWHead Quest Link -- https://classic.wowhead.com/quest=1322/the-black-shield
Classic WoWHead Acidic Venom Sac Link -- https://classic.wowhead.com/item=5959/acidic-venom-sac

Suggested Fix -- On old 2004/2005 retail WoW when doing both quests (Jarl Needs Eyes, Black Shield) I would gather about 3-5 Venom Sacs in the time I spent killing to get the 40 eyes for Jarl. There was no need to kill spiders inside of the cave nearby - the outdoor open air spider spawns would drop both quest items. I would politely suggest a drop rate of 15-20% so that within 5 to 6 kills, a Venom Sac would drop. A player might have a streak of bad luck and take 8-12 spiders killed to get a sac, but they should at least be dropping.

TurtleWoW In Game Image (Character 1) -- https://postimg.cc/WDXBjX6X
TurtleWoW In Game Image (Character 2) -- https://postimg.cc/cgzPtCz3

**Comment by slowtorta** [comment]
This was indeed bugged! Fixed in the next revision.
