### ISSUE TITLE
Cannot be Counter Spelled - Gift of Arugal (Archmage Arugal Version)

### ISSUE THREAD

**Issue by AyleeJenn** [slowtorta/turtlewow-bug-tracker#1325]
**Please, provide a clear description what the bug is:**
In the dungeon "Shadowfang Keep" the final battle against archmage arugal features a curse type debuff that seems cast anyways even though a successful "counterspell" hit the npc who casts it.

**Steps to reproduce the behavior with as much detail as possible:**

1. Initiate combat with the final battle of "Shadowfang Keep", archmage arugal
2. Play a mage and wait until the npc attempts to cast "Gift of Arugal" on another player
3. Use "counter spell" and observe how even a successful counter spell does not prevent the debuff from completing to cast

**IDs of affected creatures, items, quests or spells with a link to the relevant page:**

NPC: https://database.turtle-wow.org/?npc=4275#abilities

**Expected behavior. Describe how it should work:**
Counterspell should interrupt a cast in progress and prevent the caster from using any casting of similar type. I suspect that this "Gift of Arugal" is actually listed as an "abiltiy" and not a spell which could be the reason why it can't be counterspelled. But it looks like a spell, behaves like a spell but you can't interrupt it like a spell. Counterspell should counter/interrupt spells.

**Comment by slowtorta** [comment]
I'm sorry, not enough information. Please provide a video of its behavior from Classic PTR. It's possible that this spell isn't conterspellable due to the boss encounter design.
