### ISSUE TITLE
Arch Mage Arugal - "Evade" positional Glitch

### ISSUE THREAD

**Issue by AyleeJenn** [slowtorta/turtlewow-bug-tracker#1326]
**Please, provide a clear description what the bug is:**
Mind you, this is a highly specific glitch that only happened once in seven runs of the dungeon. But -if- it happens it will almost certainly wipe the party unless they have excessive preparations on hand.

Archmage arugal tends to teleport to two alternative locations during the fight. However, if he runs out of mana when he teleports to the location near the stairway and the entrance door into his room ... he will glitch because for some reason he won't find a path to the nearest player. He will quickly regenerate his hitpoints and "Evade" any attacks.

This only seems to happen if the fight is drawn out and the npc runs out of mana. So it likely concerns under leveled or at-level characters.

**Steps to reproduce the behavior with as much detail as possible:**

1. Initiate the fight against Archemage Arugal
2. Wait until he runs out of mana
3. Observe as he fails to find a path to players once he ran out of mana and teleported to the location near the entrance door.

**IDs of affected creatures, items, quests or spells with a link to the relevant page:**

NPC: https://database.turtle-wow.org/?npc=4275#abilities

**Expected behavior. Describe how it should work:**
What should happen here is that archmage arugal should find a valid path to engage players in melee combat after he runs out of mana. The fact that he does not do that suggests a problem with the exact position of his alternative teleport locations.

**Comment by slowtorta** [comment]
Fixed in the next revision.
