### ISSUE TITLE
NPC: Marsh Inkspewer (Ability Cooldown)

### ISSUE THREAD

**Issue by Firestoat** [slowtorta/turtlewow-bug-tracker#1327]
The Marsh Inkspewer in Swamp of Sorrows currently has a 6 to 8 second cooldown on its Inkspray ability, giving the player a 50% melee hit miss chance for 15 seconds, leaving this ability with a 100% uptime during a combat with one.

TurtleWoW NPC Mob Link -- https://database.turtle-wow.org/?npc=750
TurtleWoW NPC Ability Link -- https://database.turtle-wow.org/?spell=9612

WoWHead Classic Mob Link -- https://classic.wowhead.com/npc=750/marsh-inkspewer#drops
WoWHead Classic Ability Link -- https://classic.wowhead.com/spell=9612/ink-spray

TurtleWoW In Game Image -- https://postimg.cc/Yvw0mCcT

Observation -- the old 2004/2005 retail version of this mob would have a cast time of 1 second on the ability (giving a quick player a chance to interrupt) while also having a very, very short combat range that it could cast it on a player. In the old days you'd fight one as a bear druid or a warrior, wait to hear / see its casting animation, and IMMEDIATELY side strafe / jump to the side so that when the cast would conclude, the target (player) was out of the combat range of the spell and it would fail.

This Mang0s build of the mob and ability is giving it a much greater casting range to target (cannot do the classic dodge to fail the cast), and also has the mob recast within its 15 second duration (with no diminishing returns) for 100% of the fight. This is kind of OP and not in line with the old game.

Suggestion -- Restrict the range of the cast spell closer to the classic combat range (TurtleWoW's Silithid Invader / Silithid Pox abilities match how the Inkspray Should be working) or give the ability a cooldown that is greater than its duration by 4 or 5 seconds.

Silithid Invader Reference TurtleWoW Link -- https://database.turtle-wow.org/?npc=4131#drop

**Comment by slowtorta** [comment]
Fixed in the next revision, making it a bit less brutal.
