### ISSUE TITLE
wrong drop chances on the db

### ISSUE THREAD

**Issue by geojak** [slowtorta/turtlewow-bug-tracker#1332]
**Please, provide a clear description what the bug is:**

so i checked the db for the cow kings hides dropchances.

to my suprise it lised a few easy to kill mbos with an insane 10% dropchance.

of course i went out and farmed them a bit. 

i killed atleast 20 of each dragons (scalding broodling), diseades wolfs, and plaguehoud rants

the chances that the 10% dropchance is true and i still didnt get a drop is statistically exteremely low

something is off with db dropchances

**Expected behavior. Describe how it should work:**

https://database.turtle-wow.org/?item=13009

**Comment by slowtorta** [comment]
DB isn't very accurate when it comes to displaying reference loot chances, but it's not something we are going to work on any time soon, because it's too low priority, sorry.
