### ISSUE TITLE
Warlock Xraylen VoidWalker Summon Causes Sacrifice

### ISSUE THREAD

**Issue by mybrid** [slowtorta/turtlewow-bug-tracker#1333]
Hi! When I hit 60 on my Warlock something strange happened, every time I summoned my Voidwalker it would immediately cause the spell Sacrifice to activate dispelling the demon and giving my warlock the bubble.  Also, I cannot summon the Inferno demon. I posted a few times in Discord asking if anyone else has this issue. I also asked in guild chat and world chat. This behavior seems specific to the toon. I disabled all Add Ons and deleted the WDB folder.I then downloaded the game again with no Add Ons and the behavior persists. I'm convinced this must be server related. 

**Steps to reproduce the behavior with as much detail as possible:**

1. Log in as Xralen
2. Summon Voidwalker.
3. Attack something
4. Demon will despawn using Sacrifice spell. 
5. Cast summon Inferno demo outdoors. Nothing happens. 
6. Try with a fresh game download, repeat 1-4. 

**IDs of affected creatures, items, quests or spells with a link to the relevant page:**

NPC: https://database.turtle-wow.org/?npc=
Item: https://database.turtle-wow.org/?item=
Quest: https://database.turtle-wow.org/?quest=
Spell: https://database.turtle-wow.org/?spell=
Object: https://database.turtle-wow.org/?object=

**Expected behavior. Describe how it should work:**

**Comment by FrostedScorpion** [comment]
submit an in game ticket and get gms to look at it

**Comment by slowtorta** [comment]
Hello. Was this resolved via GM ticket or the issue still persist?

**Comment by slowtorta** [comment]
Reported as solved by Tinyfin.
