### ISSUE TITLE
Anibisath Defenders chain pull far too easily compared to classic and vmangos dev

### ISSUE THREAD

**Issue by Zebouski** [slowtorta/turtlewow-bug-tracker#1334]
**Please, provide a clear description what the bug is:**
Since the bug that allowed us to teleport past the twin emps trash has been fixed, we now have to do the twin emps trash. However, these mobs have been bugged in that they chainpull from like 100, maybe 150yds away. This means in practice that we have to wait like 3-5 minutes between every pull to wait until the RNG of the mobs' pathing lines up perfectly

**Steps to reproduce the behavior with as much detail as possible:**

1. go to the trash past huhuron 
2. pull one of the mobs like you would not knowing any better
3. see 1 or 2 other mobs chainpull

can also load up the latest vmangos dev branch, do the same thing and see how lenient it is

**IDs of affected creatures, items, quests or spells with a link to the relevant page:**

NPC: https://database.turtle-wow.org/?npc=15277

**Expected behavior. Describe how it should work:**
Exactly like it does on vmangos upstream dev branch, which im guessing feels to me like chainpull only within 50yds

**Comment by FrostedScorpion** [comment]
this is the worst part of aq40, wish this was fixed before they fixed the broken teleport.

**Comment by slowtorta** [comment]
I'm sorry, but we have the same values as any other vmangos-based server for those mobs. I don't know what's causing this.

**Comment by jameyboor** [comment]
This is fixed upon next server maintenance.
