### ISSUE TITLE
 Sen'jin Buckler graphic missing ! 

### ISSUE THREAD

**Issue by gigachadbro** [slowtorta/turtlewow-bug-tracker#1335]
**Please, provide a clear description what the bug is:**
The shield ( Sen'jin Buckler ) , appear as a box , so it means graphic is not uploaded on the turtle wow client 

 
**IDs of affected creatures, items, quests or spells with a link to the relevant page:**

NPC: https://database.turtle-wow.org/?npc=3188
Object: Sen'jin Buckler ( object dont appear in turtle wow database 

**Expected behavior. Describe how it should work:**
Shield should appear normally
![image](https://user-images.githubusercontent.com/46192630/164551182-ac8af0bd-16dc-43a5-ab1b-7365eff8f52d.png)

**Comment by slowtorta** [comment]
![image](https://user-images.githubusercontent.com/66763404/164687372-76fb85a1-8fda-48ed-ab62-398441bebc05.png)
This had been fixed a week ago, please clear your WDB folder to see the change.
