### ISSUE TITLE
Bugged geant Corrupted Scorpid in durotar

### ISSUE THREAD

**Issue by gigachadbro** [slowtorta/turtlewow-bug-tracker#1336]
**Please, provide a clear description what the bug is:**
Hey , just meet a geant corrupted scorpid , and its a bug that have to be fixed , i indicate its position and its image in the uploaded images with this post 

**IDs of affected creatures, items, quests or spells with a link to the relevant page:**

NPC: https://database.turtle-wow.org/?npc=3226

**Expected behavior. Describe how it should work:**
![image](https://user-images.githubusercontent.com/46192630/164570105-94096773-65bb-484e-8cdd-2aa178b52ef2.png)

![image](https://user-images.githubusercontent.com/46192630/164570131-09b44bea-21dc-4f96-ae4e-3461917df1d1.png)

**Comment by slowtorta** [comment]
This isn't a bug, those mobs are supposed to be here: https://classic.wowhead.com/npc=3226/corrupted-scorpid
