### ISSUE TITLE
Bug Durotar Scouring quest durotar

### ISSUE THREAD

**Issue by gigachadbro** [slowtorta/turtlewow-bug-tracker#1337]
**Please, provide a clear description what the bug is:**
After deleting quest : Durotar Scouring ( turtle wow quest ) , the items ( Scorched Heart ) stay in bag ! 

**IDs of affected creatures, items, quests or spells with a link to the relevant page:**

Item: https://database.turtle-wow.org/?item=4868
Quest: https://database.turtle-wow.org/?quest=807

**Expected behavior. Describe how it should work:**
![image](https://user-images.githubusercontent.com/46192630/164577511-b3176a00-678a-4d9c-8f53-d38173b91d95.png)
![image](https://user-images.githubusercontent.com/46192630/164577543-33c66a8f-75a5-4976-8fad-197e864a0ad0.png)

**Comment by Dormilon** [comment]
Tested, working as intended, can't reproduce.
