### ISSUE TITLE
Misleading quest text for "Preventing Poison"

### ISSUE THREAD

**Issue by Kangaroux** [slowtorta/turtlewow-bug-tracker#134]
# Issue

The quest "Preventing Poison" you get from Tonga Runetotem in the Barrens says to use a salve on healthy gazelles to vaccinate them:

![image](https://user-images.githubusercontent.com/2302541/124363665-999e3c80-dc0a-11eb-878e-d277f1284a92.png)

However the salve itself says to use it on sick gazelles to cure them:

![image](https://user-images.githubusercontent.com/2302541/124363675-b175c080-dc0a-11eb-9d7f-face5e219acf.png)

# Expected

The quest text and the salve text should be consistent.

**⚠️ IMPORTANT ⚠️** If you try using the salve on a healthy gazelle to vaccinate it, it wastes a charge and doesn't count towards the quest. If this happens you need to restart the quest to complete it.

**Comment by slowtorta** [comment]
Thanks for reporting it. It'll be fixed on the next server restart. Make sure to clear your WDB folder.
