### ISSUE TITLE
Innkeepers seemingly not working on some maps

### ISSUE THREAD

**Issue by Tamamo-no-Bae** [slowtorta/turtlewow-bug-tracker#1340]
**Please, provide a clear description what the bug is:**
Innkeepers appear to not function outside of EK and Kalimdor. This could be a very big issue later.

**Steps to reproduce the behavior with as much detail as possible:**

1. Type .tele sunstrider on an Alliance char
2. Enter the Sun Spire (Big tower beside where you appeared)
3. Speak to the Innkeeper and set your house here, watch as nothing happens. (Said Innkeeper works elsewhere)

**IDs of affected creatures, items, quests or spells with a link to the relevant page:**

NPC: https://database.turtle-wow.org/?npc=80400

**Expected behavior. Describe how it should work:**
Upon talking to the Innkeeper and making it your home, a glowy thing should appear around your character, and you should be able to use the hearthstone to go home.

**Comment by slowtorta** [comment]
Working as intended.
![image](https://user-images.githubusercontent.com/66763404/165717956-4f8edd6d-7a85-4ddd-a9b9-a82294484dfd.png)

Ensure that your GM character isn't invisible when interacting with the NPC. Also, the probably map should not have an Instance/Raid type. This will not be the case with Outland.
