### ISSUE TITLE
[Stealth] Stealth mobs don't reaply stealth after disengaging from combat

### ISSUE THREAD

**Issue by Tinyfin-github** [slowtorta/turtlewow-bug-tracker#1341]
Stealth mobs don't reaply stealth after disengaging from combat

Examples:

Wildthorn Lurker https://database.turtle-wow.org/?npc=3821
Forsaken Assassin  https://database.turtle-wow.org/?npc=3807
Forsaken Infiltrator https://database.turtle-wow.org/?npc=3806
Forsaken Intruder  https://database.turtle-wow.org/?npc=3806
Ashenvale Stalker https://database.turtle-wow.org/?npc=70025
Ashenvale Outrunner https://database.turtle-wow.org/?npc=12856

**Comment by slowtorta** [comment]
Do you have any examples of mobs that do that?

**Comment by nonameform** [comment]
I can confirm that I have encountered many mobs while leveling who were supposed to be stealthed, but were visible to me. Not sure if they aggroed other players before or just spawned that way. For example, in the Hinterlands wolves in the east part of the zone are all stalkers, but some are just walking around as regular mobs, while others actually jump at you from the shadows. Mob in question: [Silverman Stalker] ((https://database.turtle-wow.org/?npc=2926).

**Comment by ratkosrb** [comment]
Some of these mobs use Phasing Stealth. They periodically go in and out of stealth. They are not meant to be permanently stealthed.
