### ISSUE TITLE
The Stagnant Oasis barrens quest , item bug 

### ISSUE THREAD

**Issue by gigachadbro** [slowtorta/turtlewow-bug-tracker#1342]
**Please, provide a clear description what the bug is:**
dried seeds quest item , dont disapear after finishing and validing the quest ! 

**IDs of affected creatures, items, quests or spells with a link to the relevant page:**

NPC: https://database.turtle-wow.org/?npc=3448
Item: https://database.turtle-wow.org/?item=5068
Quest: https://database.turtle-wow.org/?quest=877

**Expected behavior. Describe how it should work:**
quest item should be deleted
![image](https://user-images.githubusercontent.com/46192630/164859369-f5b8bde7-7037-4ec5-a4fe-82dc5b7145fb.png)

**Comment by slowtorta** [comment]
It's working as intended! Please, stop reporting those. It's your own issue with your Bagnon addon. Ensure to clean WDB and disable your Bank/Inventory addon!
