### ISSUE TITLE
Item switched stats

### ISSUE THREAD

**Issue by virre117** [slowtorta/turtlewow-bug-tracker#1343]
**Please, provide a clear description what the bug is:**
I am not quite surtain that this is a bug or a unannunced hotfix, i am creating this ticket in the case of a bug.

The 19th April, new update nerfed the Black Morass dungeon and at the same time it boosted some of the items dropped from the bosses.
One of theese items where "[Band of Infinite Possibilities]".

The updated version of the item is listed in Turtle Wow DB:
https://database.turtle-wow.org/?item=61032

However on the evening 23th of April the item switched it's stats back to the old ones.
The old stats is the following:
8 Stamina
8 Intellect
1 - 35 spell dmg.

**Steps to reproduce the behavior with as much detail as possible:**
![Namnlös](https://user-images.githubusercontent.com/97085867/164883985-ebb4170e-2b92-4eb3-a7e5-b1bb6c6188e3.png)

1.
2. 
3. 

**IDs of affected creatures, items, quests or spells with a link to the relevant page:**

NPC: https://database.turtle-wow.org/?npc=
Item: https://database.turtle-wow.org/?item=61032
Quest: https://database.turtle-wow.org/?quest=
Spell: https://database.turtle-wow.org/?spell=
Object: https://database.turtle-wow.org/?object=

**Expected behavior. Describe how it should work:**

**Comment by Dragunovi** [comment]
There was a typo in the SQL update that gave the ring the stats of the plate leggings "Legguards of the Last Stand" https://database.turtle-wow.org/?item=61035
This was never intended and the ring was a spellpower ring before the buffs so this mistake was rectified, where the original intention was to buff its intellect with the latest buff wave.
We're sorry for any inconvenience caused.
