### ISSUE TITLE
Naxx mob Deathknight will use its anti-kite ability far too agressively

### ISSUE THREAD

**Issue by Zebouski** [slowtorta/turtlewow-bug-tracker#1344]
**Please, provide a clear description what the bug is:**
the Deathknight mobs have an anti-kite ability where they spawn a bunch of adds that do massive damage

**Steps to reproduce the behavior with as much detail as possible:**

1. pretend you are a tank, do a ranged pull and backpedal to get into position (pulling back 20-30 yds so the raid doesnt get feared into the next packs)
2. repeat this a few times
3. eventually you will see the anti-kite spell kick in and adds spawn
4. can also try tanking and moving the mob around, even when right next to the mob, anti-kite will sometimes kick in

**IDs of affected creatures, items, quests or spells with a link to the relevant page:**

NPC: https://database.turtle-wow.org/?npc=16146

**Expected behavior. Describe how it should work:**
They should only activate this ability when they arent reaching the target after about 10 seconds or so, which would be the case only with a hunter that is actively kiting them

**Comment by ratkosrb** [comment]
The spell targets nearby dead mobs, not the creature's victim, so it's not dependent on how far you are. In classic sniffs i see many casts of it by this mob, so I'll correct the cast timer to match statistics from there.
