### ISSUE TITLE
Fireguard destroyer in brd deal too little damage 

### ISSUE THREAD

**Issue by geojak** [slowtorta/turtlewow-bug-tracker#1345]
**Please, provide a clear description what the bug is:**

The fireguard destroyer trash pacld have always been the most hard hitting and challenging part of a brd run. Not so on turtle wow Total pushover here.they just don't do enough damage. 
Feels underwhelming 

**Steps to reproduce the behavior with as much detail as possible:**

1. Emgahnge fireguard destroyers in brd, for example in front of tavern or at mc entrance
2. Watch for instant fireball cast and meele damage hits 
3. Even without defensive stance you get hit lower than in the classic video I linked below

**IDs of affected creatures, items, quests or spells with a link to the relevant page:**

https://database.turtle-wow.org/?npc=8911

**Expected behavior. Describe how it should work:**

https://m.youtube.com/watch?v=hnRIUMTjygU
Watch around 2:21-2:23

The fireleements shot some kind of instant fireball and hit harder in general

**Comment by geojak** [comment]
P. S. There is a weaker fire elemtnals type in brd, for example around the anvil and the fire ele Boss.

Maybe they need a fix too.

**Comment by geojak** [comment]
Maybe they don't use their fireblast ability?

**Comment by slowtorta** [comment]
Fixed in the next revision.
