### ISSUE TITLE
got troubles with saving Cyrillic letters in Guild Information window...

### ISSUE THREAD

**Issue by TorTun** [slowtorta/turtlewow-bug-tracker#1346]
got troubles with saving Cyrillic letters in Guild Information window...

**Comment by slowtorta** [comment]
Вот сюда заходите и ставьте тут Russian (Lnaguage for non-Unicode Programms):

![image](https://user-images.githubusercontent.com/66763404/165718962-3db0466e-aeea-43c9-8a36-c28ec72e24f2.png)

Есть есть галочка Beta: - можно её.
