### ISSUE TITLE
Dark Iron Demolitionist - Ignoring Line of Sight

### ISSUE THREAD

**Issue by AyleeJenn** [slowtorta/turtlewow-bug-tracker#1347]
**Please, provide a clear description what the bug is:**
In the area "Wetlands", the region of "Dun Modr" there are dark iron elite npcs. One type of these npcs seems to malfunction. The type that is malfunctioning is "Dark Iron Demolitionist" (the ones with the dynamite). Their malfunction is that they throw the dynamite through walls, building floors and any terrain that can usually obstruct "line of sight".

That clearly shouldn't be happening.

**Steps to reproduce the behavior with as much detail as possible:**

1. Travel to "Wetlands" area and find "Dun Modr" in the northern portion of the map
2. Be very careful as you engage into the elite enemies until you find a "Dark Iron Demolitionist"
3. Observe as they will throw their dynamite through walls and building floors

**IDs of affected creatures, items, quests or spells with a link to the relevant page:**

NPC: https://database.turtle-wow.org/?npc=1054

**Expected behavior. Describe how it should work:**
The ranged dynamite attack of "Dark iron Demolitionist" should not ignore terrain and when "Line-of-sight" is obstructed, the npc should behave like other correctly functioning ranged npcs and seek out the target within pursuit distance to regain line-of-sight.

**Comment by slowtorta** [comment]
Fixed in the next revision.
