### ISSUE TITLE
serpentbloom bug 

### ISSUE THREAD

**Issue by gigachadbro** [slowtorta/turtlewow-bug-tracker#1348]
**Please, provide a clear description what the bug is:**
many serpentblooms have twice spawns in same spot , so when i loot one , i find another below it 

**IDs of affected creatures, items, quests or spells with a link to the relevant page:**

Object: https://database.turtle-wow.org/?item=5339
quest : https://database.turtle-wow.org/?quest=60125

**Expected behavior. Describe how it should work:**
it should be getten once from player

**Comment by slowtorta** [comment]
Couldn't reproduce. The issue is on your side. Please ensure your client can write WDB folder and doesn't have the ReadOnly flag.
