### ISSUE TITLE
Blood Fury orc racial talent does not stack with Rockbiter Weapon ability.

### ISSUE THREAD

**Issue by Trakstral** [slowtorta/turtlewow-bug-tracker#135]
**Blood fury orc race talent does not stack with rockbiter weapon ability. Blood fury by itself works for me but when I use rockbiter on top of it, it does not stack.**
![bloodfury_bug_1](https://user-images.githubusercontent.com/86891904/124364723-a7bc7f00-dc43-11eb-87d1-b30c68ffd4c9.png)
![bloodfury_bug_2](https://user-images.githubusercontent.com/86891904/124364726-ae4af680-dc43-11eb-89b4-9c3af825ba2d.png)

**Steps to reproduce the behavior with as much detail as possible:**
1. Press rockbiter weapon ability and see melee attack power stat.
2. Press blood fury after the step one and the number of melee attack power is not increasing.

**IDs of affected creatures, items, quests or spells with a link to the relevant page:**
Spell Blood Fury: https://database.turtle-wow.org/?spell=20572
Spell Rockbiter weapon: https://database.turtle-wow.org/?spell=8017

**Expected behavior. Describe how it should work:**
The additional power from Blood Fury racial ability should stack on top of a melee attack power bonus from Rockbiter weapon spell.

**Comment by Trakstral** [comment]
The numbers behind it do not add up to me. Rockbiter should give only 29 ap at this lvl, but the ap given is 49 (with or without blood fury). Blood fury without rockbiter gives 13, something is wrong, but it seems like it is kind of working. Maybe I am missing something..

**Comment by Velite12** [comment]
blood fury only increases base ap of your character which is determined by level and applies before anything else. It doesn't stack with anything.
