### ISSUE TITLE
Sound not playing: Fishing

### ISSUE THREAD

**Issue by AyleeJenn** [slowtorta/turtlewow-bug-tracker#1350]
**Please, provide a clear description what the bug is:**
When you click the icon to start fishing a sound used to play. Now it doesn't. =(

**Steps to reproduce the behavior with as much detail as possible:**

1. Equip a fishing rod (and have fishing learned as profession)
2. Click the fishing icon near water
3. Observe (or listen rather) as no sound plays when the fishing icon is clicked

**IDs of affected creatures, items, quests or spells with a link to the relevant page:**

Spell: https://database.turtle-wow.org/?spell=18248

**Expected behavior. Describe how it should work:**
A sound should play when you click the fishing icon

**Comment by slowtorta** [comment]
Known client issue, we don't know yet what's causing it. But this one is already present in our internal bug tracker.

**Comment by sambonz** [comment]
This is happening to me also. Any updates since April 2022?
