### ISSUE TITLE
out of place syndicate agent in alterac mountains

### ISSUE THREAD

**Issue by geojak** [slowtorta/turtlewow-bug-tracker#1351]
**Please, provide a clear description what the bug is:**
![WoWScrnShot_042622_220354](https://user-images.githubusercontent.com/25199983/165391336-96a2f2b8-0ca9-4afe-9f6f-b632fdd66b6e.jpg)
![WoWScrnShot_042622_220345](https://user-images.githubusercontent.com/25199983/165391343-cb4e0931-68b6-4e6f-ada8-32088be01c6a.jpg)
![WoWScrnShot_042622_220348](https://user-images.githubusercontent.com/25199983/165391346-56a2ee3b-5ab1-4863-bff6-7bd5dca02cd8.jpg)

**Steps to reproduce the behavior with as much detail as possible:**

1. go to the oger castle in alterac mountains
2. walk up the stairs
3. see a out of place looking syndicate agent randomly standing around

**IDs of affected creatures, items, quests or spells with a link to the relevant page:**

https://database.turtle-wow.org/?npc=13150

**Expected behavior. Describe how it should work:**

these syndicate agent were according to https://wowpedia.fandom.com/wiki/Syndicate_Agent part of alterac valley bg and removed later by blizzard togetehr with the gnolls.

i like that you brought them back, but atleast put that agent in some corner and in stealth as an easter egg, right now it lookgs just wrong

**Comment by slowtorta** [comment]
Fixed in the next revision.
