### ISSUE TITLE
Sound not playing: Sharpening/Weight/Grinding Stone

### ISSUE THREAD

**Issue by AyleeJenn** [slowtorta/turtlewow-bug-tracker#1352]
**Please, provide a clear description what the bug is:**
A sound should play upon completion of the listed blacksmithing recipes. It used to play but at some point after a recent update stopped playing and has not played since. The recipes in question appear to be blacksmithing recipes that process various stone byproducts of mining. Sharpening stones, weight stones and grinding stones.

**Steps to reproduce the behavior with as much detail as possible:**

1. Have Blacksmithing as profession and try creating one of the listed recipes
2. Observe as no sound plays upon completion of the recipe (a sound is supposed to play)
3. 

**IDs of affected creatures, items, quests or spells with a link to the relevant page:**

Rough:
Spell: https://database.turtle-wow.org/?spell=2660
Spell: https://database.turtle-wow.org/?spell=3115
Spell: https://database.turtle-wow.org/?spell=3320

Coarse:
Spell: https://database.turtle-wow.org/?spell=3116
Spell: https://database.turtle-wow.org/?spell=3326
Spell: https://database.turtle-wow.org/?spell=2665

Heavy:
Spell: https://database.turtle-wow.org/?spell=3117
Spell: https://database.turtle-wow.org/?spell=3337
Spell: https://database.turtle-wow.org/?spell=2674

Solid:
Spell: https://database.turtle-wow.org/?spell=9918
Spell: https://database.turtle-wow.org/?spell=9921
Spell: https://database.turtle-wow.org/?spell=9920

Dense:
Spell: https://database.turtle-wow.org/?spell=16641
Spell: https://database.turtle-wow.org/?spell=16640
Spell: https://database.turtle-wow.org/?spell=16639

Elemental:
Spell: https://database.turtle-wow.org/?spell=22757

**Expected behavior. Describe how it should work:**
Upon completion of the listed recipes a sound is supposed to play.

**Comment by slowtorta** [comment]
Moving this one to the internal tracker, thank you for collecting the spell IDs!
