### ISSUE TITLE
Quest cannot be turned in: Appealing to the Alliance Dwarves/Gnomes/Nightelves

### ISSUE THREAD

**Issue by AyleeJenn** [slowtorta/turtlewow-bug-tracker#1353]
**Please, provide a clear description what the bug is:**
The Ala'thalas quest "Appealing to the Alliance" provides "Sealed Missive" now but the quests for the dwarves, Gnomes and Nightelves cannot be turned in at the respective leaders.

**My -guess- is that the four sealed missive items that the player receives have the same item IDs and the player therefore has four sealed missives for Stormwind since that is the only quest of the four quests that can be turned in. That would explain why the quest for stormwind can be turned in but not the quests for the other alliance leaders.**

This is a problem because the "Diplomatic Mission" quest requires responses from all four leaders to be turned in but the player can only get the response from stormwind at present

**Steps to reproduce the behavior with as much detail as possible:**

1. Start the quest "A Diplomatic Mission" from the Highelven leader and collect the four quests for the respective alliance leaders
2. Turn in the quest for Stormwind and then try to turn in the quest at the other alliance leaders
3. Observe as the stormwind quest can be turned in but the other alliance leaders will have a grey questionmark despite you having the "sealed missive item" in your inventory

**IDs of affected creatures, items, quests or spells with a link to the relevant page:**

Item: https://database.turtle-wow.org/?item=83012

**Expected behavior. Describe how it should work:**
The quest should be possible to be turned in at each alliance leader, not just stormwind.

**Comment by slowtorta** [comment]
Hello. Have you tried re-taking the quests and accepting those again?

**Comment by AyleeJenn** [comment]
Hello!! Yes, I have tried aborting and retaking the quests again. Here is my full testing...
I tried ...
#1. Clearing WDB folder - no effect
#2. Aborting quest and retaking it - no effect
#3. Aborting all quests and only retaking a single one (dwarves) - no effect
