### ISSUE TITLE
Black Morass - Invissible wall

### ISSUE THREAD

**Issue by virre117** [slowtorta/turtlewow-bug-tracker#1354]
**Please, provide a clear description what the bug is:**
Hello,

Since the updated version of Black Morass on the 19th of April i did my first, second, third and forth entrence in the dungeon.
And at every single occasion there have been a specific bug it seems.

After infinite Chromie dies and the event is over we still are unable to enter the swamp.
It is like there is an invisseble wall.

The forth time we entered we got help by GM and got ported through the invis wall.

Still i thought i better report this too you guys to raise awearness.

**Steps to reproduce the behavior with as much detail as possible:**

1.
2. 
3. 

**IDs of affected creatures, items, quests or spells with a link to the relevant page:**

NPC: https://database.turtle-wow.org/?npc=
Item: https://database.turtle-wow.org/?item=
Quest: https://database.turtle-wow.org/?quest=
Spell: https://database.turtle-wow.org/?spell=
Object: https://database.turtle-wow.org/?object=

**Expected behavior. Describe how it should work:**

**Comment by slowtorta** [comment]
Neto changed this event to not require walls starting the next upate.
