### ISSUE TITLE
Sound not playing: Recipe Learning

### ISSUE THREAD

**Issue by AyleeJenn** [slowtorta/turtlewow-bug-tracker#1355]
**Please, provide a clear description what the bug is:**
Dear developers, I apologize in advance for this report but I simply cannot test this adequately because recipes can only be learned once and I have no idea which exactly no longer play the sound they should be playing upon casting the "spell" to learn it.

But what I can say is that when you right click a recipe a sound is supposed to play. it sounds a little bit like crumpling paper which is the sound that is supposed to play when you learn a recipe.

These sounds don't seem to play anymore, however -some- recipes actually play a (different) sound when you learn them. But they are rare, most recipes do not play a sound anymore when you learn them even though they should.

**Steps to reproduce the behavior with as much detail as possible:**

1. This is kind of tricky because you have to be able to learn recipes to test this
2. Learn a recipe of your choice from a recipe item in your inventory
3. Observe as no sound plays while you learn the "spell" (recipe)

**IDs of affected creatures, items, quests or spells with a link to the relevant page:**

In the interest of not making this a page long post (and since I can't even remember all the recipes from scroll items that my characters learned) I will need to say here that almost all recipes that you can learn from inventory items no longer play a sound. I apologize v.v but this is almost impossible to test for me and I can only look back on my experience.

**Expected behavior. Describe how it should work:**
A sound should be playing when you learn a recipe. It should play the sound that sounds like crumpling paper. That is (or is supposed to be) the standard sound that should play when a player learns a recipe from an inventory recipe item.

**Comment by slowtorta** [comment]
This goes to the internal tracker, thank you.
