### ISSUE TITLE
Pyroblast crit chance lowered. Poly time in pvp lowered.

### ISSUE THREAD

**Issue by Tele4eg** [slowtorta/turtlewow-bug-tracker#1356]
- Pretty sure pyroblast crit chance is lowered somehow. Why? its not the way to balance.
https://i.postimg.cc/d1WRVLpb/pyro.jpg
- Also polymorph time in pvp is way to low. It should be atleast 15 seconds on 1st poly. Here now its like less than 10 and its wrong for sure!!!

**Comment by slowtorta** [comment]
Sorry, absolutely not enough information to work with in this bug report.
