### ISSUE TITLE
Quest cannot be turned in: Appealing to the Alliance Gnomes/Nightelves

### ISSUE THREAD

**Issue by AyleeJenn** [slowtorta/turtlewow-bug-tracker#1357]
**Please, provide a clear description what the bug is:**
Sorry to open a new issue but this quest still is not fixed yet. I tried running this quest on a different character and I encountered the exact same problems as I did when I wrote this report #1353 

**Steps to reproduce the behavior with as much detail as possible:**

1. Accept the diplomatic missive quests in Alah'thalas for the humans, dwarves, gnomes and night elves
2. Try to turn in the diplomatic missives quests for the respective leaders.
3. Observe as the missives for the human leader can be turned in, but not the missives for the dwarves, gnomish and night elven leaders, they will still have grey questionmarks despite the presence of the quest item in the player's inventory

**IDs of affected creatures, items, quests or spells with a link to the relevant page:**

NPC: https://database.turtle-wow.org/?npc=7937
NPC: https://database.turtle-wow.org/?npc=60669
Item: https://database.turtle-wow.org/?item=83012
Quest: https://database.turtle-wow.org/?quest=40374
Quest: https://database.turtle-wow.org/?quest=40375

**Expected behavior. Describe how it should work:**
It is awesome that the human part of the quest work but without the dwarven, gnomish and night elven part working the quest still cannot be completed.

**Comment by AyleeJenn** [comment]
I did some testing with this after posting this report and it turns out that the gnomish portion can be turned in if you log out after turning in the dwarven missive and clear the WDB folder and then log in again. That might allow for the gnomish missive to be turned in also.

The night elven missive still cannot be turned in at all even with logging out and clearing the WDB folder after turning in the gnomish missive.

**Comment by slowtorta** [comment]
If the issues is marked as fixed, it doesn't mean the fix was immediately applied to the server :) Please wait till the next Wednesday to restart!

**Comment by slowtorta** [comment]
Thank you for submitting such well-written and detailed reports, we really appreciate it!

**Comment by AyleeJenn** [comment]
You are right, I am sorry. I feel I need to apologize for getting a bit carried away >.< I will wait in the future until the next restart. I did not mean to disrespect a "fixed" at all, but ended up doing it because of my getting carried away. I apologize and will conduct myself better next time. =s

That said, you are welcome for the reports and it is honestly my pleasure. =)

**Comment by slowtorta** [comment]
Tested once again before we update next week:
![image](https://user-images.githubusercontent.com/66763404/166107290-ce0ea4be-1e10-4fe2-a3a0-bd9265bfc12d.png)
![image](https://user-images.githubusercontent.com/66763404/166107297-c6f98a03-2053-445b-9803-df196f83e06d.png)
![image](https://user-images.githubusercontent.com/66763404/166107352-4660ca98-7b85-410c-962f-2106e9b9d2bc.png)
I think it's safe to close this one then :) Make sure to delete your WDB and re-take the quests if needed.
