### ISSUE TITLE
Reinforced Red Pounder summon  a skeletal horse

### ISSUE THREAD

**Issue by Tinyfin-github** [slowtorta/turtlewow-bug-tracker#1358]
Reinforced Red Pounder  https://database.turtle-wow.org/?item=81253 teaches you spell 46513 - [Red Pounder enUS]  but it summon a skeletal horse

![image](https://user-images.githubusercontent.com/83077166/165981227-d3e70635-9b3c-49fa-bfa8-52c718fdd335.png)

**Comment by slowtorta** [comment]
Fixed in the next revision.
