### ISSUE TITLE
Bailor's Ore Shipment missing pre requeired quest

### ISSUE THREAD

**Issue by Tinyfin-github** [slowtorta/turtlewow-bug-tracker#1359]
Bailor's Ore Shipment missing pre requeired quest

https://database.turtle-wow.org/?quest=1655 Bailor's Ore Shipment should be available only after completing  https://database.turtle-wow.org/?quest=1653 The Test of Righteousness

**Comment by slowtorta** [comment]
According to Wowhead Classic, it should require https://classicdb.ch/?quest=1654 as pre-quest. Fixed in the next revision!
