### ISSUE TITLE
double spawn of quest Triggered durotar 

### ISSUE THREAD

**Issue by gigachadbro** [slowtorta/turtlewow-bug-tracker#1360]
**Please, provide a clear description what the bug is:**
the custom turtle wow quest have double spawn of this quest Triggered .
**kaja's ammo** , have double spawns in each place ! so when i do pick one i can find another one 

**IDs of affected creatures, items, quests or spells with a link to the relevant page:**

Quest: https://database.turtle-wow.org/?quest=60120
Object: https://database.turtle-wow.org/?object=1000389

**Expected behavior. Describe how it should work:**
the box should be picked only once at each spawn point . 
![image](https://user-images.githubusercontent.com/46192630/166075196-71c28373-bc32-4a37-90b3-ee7975fdc562.png)

**Comment by slowtorta** [comment]
Working as intended. The issue is on your side.
