### ISSUE TITLE
Custom quest Red Skies of Durotar , bug 

### ISSUE THREAD

**Issue by gigachadbro** [slowtorta/turtlewow-bug-tracker#1361]
**Please, provide a clear description what the bug is:**
" Red skies of durotar " custom turtle wow quest have a bug , i dont have necessary required item in my bag " chunk of boar meat " , but i still can see interogation point at the npc wyvern ! ( i got previously the necessary meats , but i kept them at my bank ) 

**IDs of affected creatures, items, quests or spells with a link to the relevant page:**

NPC: https://database.turtle-wow.org/?npc=60539
Quest: https://database.turtle-wow.org/?quest=40298

**Expected behavior. Describe how it should work:**
![image](https://user-images.githubusercontent.com/46192630/166076127-7ebd76df-dd5a-419f-b310-908f075a81fc.png)

**Comment by slowtorta** [comment]
All your bugs are on your side. Please contact support on our Discord.
