### ISSUE TITLE
Harlus Ashbuckle - Remains keep orienting towards target

### ISSUE THREAD

**Issue by AyleeJenn** [slowtorta/turtlewow-bug-tracker#1362]
**Please, provide a clear description what the bug is:**
I saw two players fighting Harlus Ashbuckle in Hawk's Vigil. They managed to defeat the npc in the end. However the defeated npc Harlus Ashbuckle (i.E. the remains) seemed to keep orienting towards the player who had the aggro. That clearly shouldn't be happening but I doubt that is the "dark practices" the npc stands accused of in the game world. Though it would certainly freak out any unsuspecting bystander!

**Steps to reproduce the behavior with as much detail as possible:**

1. Fight or observe others fight "Harlus Ashbuckle" in Hawk's Vigil
2. Observe how the remains keep orienting towards the target the npc had.

**IDs of affected creatures, items, quests or spells with a link to the relevant page:**

NPC: https://database.turtle-wow.org/?npc=52119
Quest: https://database.turtle-wow.org/?quest=55225

**Expected behavior. Describe how it should work:**
Like any other defeated npc remains the remains of Harlus Ashbuckle should not move at all once defeated.

**Comment by slowtorta** [comment]
Thanks, fixed in the next revision :)
