### ISSUE TITLE
Wastewander Bandit/Thief don't actually reward Steamwheedle Reputation on death

### ISSUE THREAD

**Issue by tubtubs** [slowtorta/turtlewow-bug-tracker#1363]
**Please, provide a clear description what the bug is:**
There's a chat message, and scrolling combat text rewarding Steamwheedle Cartel Reputation, but tracking the value for the reputations (watching them carefully mouse over while killing) reveals that no reputation is gained.

There may be more mobs impacted by this bug, but I have noticed it in Tanaris on these specific mobs so far. 

**Steps to reproduce the behavior with as much detail as possible:**

1. Check Steamwheedle Cartel reps (mouse over each)
2. Kill Wastewander mob in Waterspring Field Tanaris
3. Notice no actual change in reputation

**IDs of affected creatures, items, quests or spells with a link to the relevant page:**

NPC: https://database.turtle-wow.org/?npc=5616
https://database.turtle-wow.org/?npc=5623

Item: https://database.turtle-wow.org/?item=
Quest: https://database.turtle-wow.org/?quest=
Spell: https://database.turtle-wow.org/?spell=
Object: https://database.turtle-wow.org/?object=

**Expected behavior. Describe how it should work:**
After killing these mobs, each of the Steamwheedle Cartel reputations should increase by 5.

**Comment by slowtorta** [comment]
This is working as intended :) The maximum standing you can get by killing mobs is 3.


![image](https://user-images.githubusercontent.com/66763404/166118180-a8ff1a68-b52b-4610-8c39-93a4fa606c56.png)
![image](https://user-images.githubusercontent.com/66763404/166118172-76732460-0317-4e18-a602-0070678c4610.png)
![image](https://user-images.githubusercontent.com/66763404/166118188-9de8c49d-dadd-4692-a431-fb84144f9ef8.png)

5 points are given only if your level isn't far above the creature level:
![image](https://user-images.githubusercontent.com/66763404/166118234-96ee6468-cb0a-4a60-8f90-a0bd4535e796.png)

**Comment by tubtubs** [comment]
![WoW 2022-04-30 11-36-18](https://user-images.githubusercontent.com/96892771/166118415-5f26b480-e0c8-4e6b-b859-6e1d4b292ff1.png)
![WoW 2022-04-30 11-35-53](https://user-images.githubusercontent.com/96892771/166118416-b35a01e5-5e78-4d63-ba3a-82c4dc9f994a.png)
It really is supposed to say +5 but give no rep?
