### ISSUE TITLE
Disgusting Oozeling does not go in the spellbook

### ISSUE THREAD

**Issue by Tinyfin-github** [slowtorta/turtlewow-bug-tracker#1365]
Disgusting Oozeling https://database.turtle-wow.org/?item=20769 does not go in the spellbook

![image](https://user-images.githubusercontent.com/83077166/166134917-767bc76f-4d86-4343-ad51-1c4031080687.png)

**Comment by slowtorta** [comment]
Please report it to Moon, it's a client-side thing.
