### ISSUE TITLE
Ashenvale Quest: Vorsha the Lasher

### ISSUE THREAD

**Issue by FeyfolkenFantasy** [slowtorta/turtlewow-bug-tracker#1368]
**Please, provide a clear description what the bug is:**

The Quest "Vorsha the Lasher" involves you to escort Muglash(id:12717) to a brazier in the Zoram Strand, in Ashenvale.
Then you have to protect Muglash from waves of Nagas and finally an hydra named Vorsha.
BUT even though you don't kill Vorsha, you will get the quest completed.
I did this quest at level 32, so I was probably too high level to aggro Vorsha, who did not attack Muglash anyway.

**Steps to reproduce the behavior with as much detail as possible:**

1. Be level ~30 minimum.
2. Go to the Zoram'Gar in Ashenvale.
3. Talk to Muglash and start the quest Vorsha the Lasher.
4. Protect Muglash from the nagas if needed.
5. When Vorsha pops, don't move and wait until the quest is completed even though you don't kill it.

**IDs of affected creatures, items, quests or spells with a link to the relevant page:**

NPC: https://database.turtle-wow.org/?npc=12940
Quest: https://database.turtle-wow.org/?quest=6641

**Expected behavior. Describe how it should work:**

We are supposed to kill Vorsha the Lasher in order to validate this quest.
Hydras eat turtles! Hydras bad!

**Comment by Tinyfin-github** [comment]
Thank you for the reporting this bug.

https://github.com/slowtorta/turtlewow-bug-tracker/issues/913
