### ISSUE TITLE
Ashenvale: Broken Spear item

### ISSUE THREAD

**Issue by FeyfolkenFantasy** [slowtorta/turtlewow-bug-tracker#1369]
**Please, provide a clear description what the bug is:**

The "Broken Spear" is an item you can get from the demons in the Felfire Hill, Ashenvale.
It starts the quest "Hawk Beak" which asks you to give the spear to Norvok Hawkspear(id:70022).
If you try to start the quest "Hawk Beak" from the Broken spear before the completion of the quest "Norvok of the spear" you will get an error message.

Later on, after you completed both quests, if you kill demons in Felfire Hill you will notice that even though you looted some demons, the loot icon will still appear on some of them. 
Probably because of the Broken spear still drops, but you can no longer loot it since you have completed the quest.

**Steps to reproduce the behavior with as much detail as possible:**

1. Start the chain quest "A Brother Worried Mind" from "Loruk Foreststrider" in Splintertree Post, Ashenvale.
2. When you get the quest "Norvok of the spear" go kill the demons.
3. You loot the Broken spear.
4. Try to start the quest of the broken spear before having completed "Norvok of the spear" -error message-
5. Later, after having completed both quest go kill demons again and you will notice that even though you have looted everything from some of them, the loot icon still appears.

**IDs of affected creatures, items, quests or spells with a link to the relevant page:**

Item: https://database.turtle-wow.org/?item=70027
Quest: https://database.turtle-wow.org/?quest=70034
Quest: https://database.turtle-wow.org/?quest=70022

**Expected behavior. Describe how it should work:**

Either you can NOT get the "Broken spear" before having completed the quest "Norvok of the spear".
Either you CAN start the quest "Hawk's Beak" from the Broken spear while you are doing the quest "Norvok of the spear"
This way no more error message :^)

**Comment by geojak** [comment]
The broken spwata drops for alliance players too, which can't start it

It should only drop for horde characters

**Comment by slowtorta** [comment]
Fixed in the next reivsion.
