### ISSUE TITLE
Alah'Thalas has no fish table

### ISSUE THREAD

**Issue by SasaDermanovic** [slowtorta/turtlewow-bug-tracker#137]
**IDs of affected creatures, items, quests or spells with a link to the relevant page:**
Alah'Thalas, High Elf zone.

**Expected behavior. Describe how it should work: Upon casting fishing when a fish takes the lure you should be able to fish her.**
**Actual behavior. Describe what is exactly wrong: You can cast fishing and bait is activated but no fish come out**

**Comment by slowtorta** [comment]
Thanks for reporting it. It'll be fixed on the next server restart. Make sure to clear your WDB folder.
