### ISSUE TITLE
Sound not playing: Matthias' Letter

### ISSUE THREAD

**Issue by AyleeJenn** [slowtorta/turtlewow-bug-tracker#1370]
**Please, provide a clear description what the bug is:**
The quest object Matthias' Letter for the quest "Matthias' Letter" makes no sounds when you click it and move it in your inventory. It should make the same sound as any scroll.
**Steps to reproduce the behavior with as much detail as possible:**

1. Make sure to be on the quest "Matthias' Letter"
2. Try to click the quest item "Matthias' Letter"
3. Observe as no sound plays

**IDs of affected creatures, items, quests or spells with a link to the relevant page:**

Item: https://database.turtle-wow.org/?item=81415
Quest: https://database.turtle-wow.org/?quest=55224

**Expected behavior. Describe how it should work:**
The quest item "Matthias' Letter" should make the same sounds as any scroll item, for example ...
https://database.turtle-wow.org/?item=3013

**Comment by slowtorta** [comment]
This is the same issue as with the scrolls.

**Comment by slowtorta** [comment]
Noted to the internal tracker.
