### ISSUE TITLE
Supplying the Front | Unable to complete quest

### ISSUE THREAD

**Issue by jlautenbach** [slowtorta/turtlewow-bug-tracker#1372]
**Please, provide a clear description what the bug is:**
Reported by user Alunda, WDB cleared and fresh client.

**Steps to reproduce the behavior with as much detail as possible:**

1. Accept quest Supplying the Front
2. Retrieve 6x Copper Axe
3. Retrieve 6x Copper Chain Belt
4. Questlog says (Completed)
5. Unable to turn in quest at Thorvald Deepforge

**IDs of affected creatures, items, quests or spells with a link to the relevant page:**

NPC: https://database.turtle-wow.org/?npc=6030
Quest: https://database.turtle-wow.org/?quest=1578

**Expected behavior. Describe how it should work:**
When items are in inventory and quest shows (Completed) you should be able to complete the quest.

![image](https://user-images.githubusercontent.com/73019779/166344183-8af0319b-89ff-4a15-b1f7-6634aa05e218.png)
![image](https://user-images.githubusercontent.com/73019779/166344221-efd7aca1-d4c8-4b6e-b856-ba0202749897.png)

**Comment by slowtorta** [comment]
Unable to reproduce, I'm sorry!
