### ISSUE TITLE
Fix the spawn timer by Bael'dun Digsite on Barrens

### ISSUE THREAD

**Issue by Zeroqxp** [slowtorta/turtlewow-bug-tracker#1373]
**Please, provide a clear description what the bug is:**

The bug is the spawn timer for mobs to respawn is way too quick by the entrance from cave entrance for the tunnel system similar to Uldaman, with this spawn timer by the entrance, making it extra difficult to clear out the exit that drains out the HP and Mana and absolutely deadly for Hardcore challenge players, even in groups together

**Steps to reproduce the behavior with as much detail as possible:**

1. Golem by the cave entrance is fighting Bael'dun diggers and appraisers
2. Wait 15 seconds
3. Both sides spawned immediately making impossible to enter or leave for Hardcore Players not alive

**IDs of affected creatures, items, quests or spells with a link to the relevant page:**

NPC:'
https://database.turtle-wow.org/?npc=2990
https://database.turtle-wow.org/?npc=2989
https://database.turtle-wow.org/?npc=60442
https://database.turtle-wow.org/?npc=3377
https://database.turtle-wow.org/?npc=3374

Quest:

https://database.turtle-wow.org/?quest=40130
https://database.turtle-wow.org/?quest=40367
https://database.turtle-wow.org/?quest=843
https://database.turtle-wow.org/?quest=846
https://database.turtle-wow.org/?quest=849

**Expected behavior. Describe how it should work:**

The appraisers and diggers that usually spawns from Mulgore's digsite are easy to get killed by the bael modan golems themselves, wait 15 seconds and they are spawned back in. The same can be said about bael modan golems when its up to the players to kill the mob, kill 15 seconds and they are spawned back in, prolonging the fight forever without having to catch up to rest up from the fight that is suppose to end

**Comment by slowtorta** [comment]
Fixed in the next revision.
