### ISSUE TITLE
Cannot be Counterspelled: Mind Tremor (Razorfen Kraul)

### ISSUE THREAD

**Issue by AyleeJenn** [slowtorta/turtlewow-bug-tracker#1374]
**Please, provide a clear description what the bug is:**
In the dungeon "Razorfen Kraul" we came upon an enemy that casts a debuff called "Mind Tremor" that cannot be counter-spelled. We tested it several times and each time the counter-spell hit (connected) but the spell finished casting anyways and the debuff hit the player.

We can't be sure but it seems to be a similar issue to #1297  and #1325 and #1294 where spells-in-progress could not be counter-spelled. Despite the counter spell correctly connecting.

**Steps to reproduce the behavior with as much detail as possible:**

1. Enter the dungeon "Razorfen Kraul" and progress to and pick a fight with an "Razorfen Earthbreaker"
2. Wait until they cast "Mind Tremor" (a shadowy casty animation) and attempt to counter-spell it
3. Observe as the counter spell hits but the spell finishes anyways and the debuff hits the player

**IDs of affected creatures, items, quests or spells with a link to the relevant page:**

NPC: https://database.turtle-wow.org/?npc=4525

**Expected behavior. Describe how it should work:**
When a spell is counterspelled it should not finish casting, it should be interrupted.

**Comment by slowtorta** [comment]
I'm sorry, not enough information. Please provide a video of its behavior from Classic PTR. It's possible that this spell isn't conterspellable due to this dungeon's encounter design.
