### ISSUE TITLE
Database Error - Recipe: Lesser Stoneshield Potion

### ISSUE THREAD

**Issue by AyleeJenn** [slowtorta/turtlewow-bug-tracker#1376]
**Please, provide a clear description what the bug is:**
in the turtle wow database the quest for the recipe "Lesser Stoneshield Potion" is listed as requiring the wrong pre-requisite quests.

It is missing one pre-requisite quest. Namely "https://database.turtle-wow.org/?quest=710"

**Steps to reproduce the behavior with as much detail as possible:**

1. Complete https://database.turtle-wow.org/?quest=714 and find that the follow up quest https://database.turtle-wow.org/?quest=715 is not available.
2. Complete the https://database.turtle-wow.org/?quest=710 (all three quests of the quest series) and observe as https://database.turtle-wow.org/?quest=715 becomes available

**IDs of affected creatures, items, quests or spells with a link to the relevant page:**

NPC: https://database.turtle-wow.org/?npc=2921
NPC: https://database.turtle-wow.org/?npc=2920
Quest: https://database.turtle-wow.org/?quest=715

**Expected behavior. Describe how it should work:**
The database should show the quest "https://database.turtle-wow.org/?quest=710" as pre-requisite for the quest 
Quest:

**Comment by slowtorta** [comment]
Working as intended: this quest should require both quests to become available: https://classic.wowhead.com/quest=715/liquid-stone. For the DB display error: this will probably remain as it is since it's very minor, sorry.

**Comment by slowtorta** [comment]
@CosminPOP Check that out if you want to. This is how it's working in-game: 
![image](https://user-images.githubusercontent.com/66763404/167399792-a5e88d21-442b-47c6-a328-129580f90930.png)
