### ISSUE TITLE
Sickly Gazelle wrong type of mob

### ISSUE THREAD

**Issue by Kaporalhart** [slowtorta/turtlewow-bug-tracker#1377]
**Please, provide a clear description what the bug is:**

The mob Sickly Gazelle, in the barrens, for the horde druid quest Gathering the Cure, is a level 11-13 beast, with according stats, when it should be a level 3 critter. Players killing it for the quest must run after it, as it still has the critter combat behaviour of running erraticly instead of fighting.

**Steps to reproduce the behavior with as much detail as possible:**

1. Simply attack a Sickly Gazelle.

**IDs of affected creatures, items, quests or spells with a link to the relevant page:**

NPC: https://database.turtle-wow.org/?npc=12296

**Expected behavior. Describe how it should work:**

The gazelle should be a level 3 critter with very low health.

Although a bit impended, the quest still works.

**Comment by slowtorta** [comment]
Fixed in the next revision.
