### ISSUE TITLE
You can't ignore any more players

### ISSUE THREAD

**Issue by Gasan918** [slowtorta/turtlewow-bug-tracker#1378]
I am playing HC mode in "Still Alive" guild. My ignore list is full of "unknown" players. And I can't delete these "unknowns" manually ("player not found"). IMAO this happened because when someone deletes character it is not deleted from other players' ignore lists.

**Expected behavior. Describe how it should work:**

1. Remove player from all ignore lists when deleted by owner.
2. OR. Run a batch cleaning all "unknowns" during server maintenance. (and I need this now, my list is full allready)

**Comment by geojak** [comment]
My friend list is also full. Would be cool of it could be a little bit larger in general

**Comment by slowtorta** [comment]
Possibly fixed in the next revision, re-open if not.
