### ISSUE TITLE
copper vein behind rock 

### ISSUE THREAD

**Issue by gigachadbro** [slowtorta/turtlewow-bug-tracker#1379]
**Please, provide a clear description what the bug is:**
Mining node hiden behind rock in thousand needles
copper vein

**IDs of affected creatures, items, quests or spells with a link to the relevant page:**

Object: https://database.turtle-wow.org/?object=2055

**Expected behavior. Describe how it should work:**
it shouldnt be hidden 
![image](https://user-images.githubusercontent.com/46192630/167295056-f7f76deb-9e4f-4a40-a38b-2529c5327df6.png)
![image](https://user-images.githubusercontent.com/46192630/167295112-6f9ef0be-37af-42e5-8c4d-b79b6071d512.png)

**Comment by slowtorta** [comment]
Working as intended. Please walk around the stone formation to see a node. 
![image](https://user-images.githubusercontent.com/66763404/167400189-06af99ab-6677-412d-bd3b-fc5d81fdf667.png)
