### ISSUE TITLE
Horde shared reputation mechanics broken

### ISSUE THREAD

**Issue by FeyfolkenFantasy** [slowtorta/turtlewow-bug-tracker#1380]
**Please, provide a clear description what the bug is:**

When you gain reputation from a given Horde faction, half (or a quarter) of it shall go to the other Horde factions. I don't remember if it was half or quarter.
It is not the case on Turtle WoW

**Steps to reproduce the behavior with as much detail as possible:**

1. Create any Horde character.
2. Check each of your Horde reputation.
3. Do any Horde starting area quest.
4. See that only one reputation increased after you did your quest.

**Expected behavior. Describe how it should work:**

For instance if you complete a quest and gain 250pts of reputation to Orgrimmar, you should gain reputation to the other Horde factions.

Note that the shared reputation system is not broken for the Steamwheedle Cartel.
When you gain reputation for Booty Bay, you gain half of it for the other 3 factions of the cartel.

I did not check the Alliance reputations.

Since I play Goblin, it might be related to custom race.

**Comment by geojak** [comment]
Spillover rep might be a tbc thing actually

**Comment by FeyfolkenFantasy** [comment]
Here is an article from June 2006 stating that Spillover was indeed a thing for Horde, Alliance and for the Steamwheedle Cartel reputations.
https://www.ownedcore.com/forums/world-of-warcraft/world-of-warcraft-guides/990-ultimate-reputation-guide.html

**Comment by FeyfolkenFantasy** [comment]
And here is a link of the 1.7.0 patch note:
https://wowwiki-archive.fandom.com/wiki/Patch_1.7.0
You can read in the quest section: 
"Reputation gains given to a player on the Alliance, Horde, or Steamwheedle Cartel factions directly will now cascade down to member factions through the middle of the Exalted reputation level."

**Comment by FeyfolkenFantasy** [comment]
Thanks you very much :)
