### ISSUE TITLE
Attackspeedissues with Flurry

### ISSUE THREAD

**Issue by Melphoone** [slowtorta/turtlewow-bug-tracker#1383]
Bugissue: Attackspeedbenefits from Flurry are not equal to the Tooltip shown. (Tested with a lvl 60 shaman)
At 5/5 skillpoints, there should be a benfit of 30% Attackspeed.
Example with a 3.50 sec. Speed 2h Mace. 
- Procc occurs after a Critical hit, Weaponspeed is reduces to 2.69 seconds (0.81sec, should be 1.05 sec)
- corresponds 23% attackspeed instead of 30%

If I put on Attackspeedequipment with a total amount of 14% Changes are:
-  3.05sec Weaponspeed ( 0.45sec, should be 0.49sec)
- corresponds 13% attackspeed instead of 14%

Now with this equipment attached, Flurry occurs with 30%, that should do a sum of 44%
- 2.34sec Weaponspeed ( 1.16sec, should be 1.54sec)
- corresponds 33% attackspeed instead of 44%

So, if i have not missed anything.....where is all this promised Attackspeed gone?
Same issue with Wepons of other speed, 1handers included.

List of Reference Items
Weapon: https://database.turtle-wow.org/?item=19358 Enchanted with Counterweight : https://database.turtle-wow.org/?item=6043    3% Speed
Head: https://database.turtle-wow.org/?item=22097 Enchanted with Arcanum https://database.turtle-wow.org/?item=18329   2% speed
Chest: https://database.turtle-wow.org/?item=22102   1% Speed
Legs: https://database.turtle-wow.org/?item=22100 Enchanted with Arcanum https://database.turtle-wow.org/?item=18329  2% Speed
Feet: https://database.turtle-wow.org/?item=22096  1% Speed
Hands: 1% speed enchant
Ring: https://database.turtle-wow.org/?item=83217  1% Speed
Trinket: Whip of Encuragement 3% speed (from stormwind vaults)
Total amount of Passive Attackspeed: 14%

**Comment by Velite12** [comment]
https://classic-wow-archive.fandom.com/wiki/Attack_speed

This is the same formula that is used on classic. Haste sources are multiplicative. Closing this issue as solved.
