### ISSUE TITLE
Defias Enchanter does too much melee damage for it's level

### ISSUE THREAD

**Issue by Tinyfin-github** [slowtorta/turtlewow-bug-tracker#1384]
Defias Enchanter https://database.turtle-wow.org/?npc=910  does too much  melee damage for it's level 

![image](https://user-images.githubusercontent.com/83077166/167476327-f8b11836-a8bf-4ea8-8aa2-9b1e001d90aa.png)

For comparation here is a Defias Night Runner  https://database.turtle-wow.org/?npc=215

![image](https://user-images.githubusercontent.com/83077166/167476502-6f280e32-cfa3-4c93-8f08-3ae33eaad3a8.png)

**Comment by slowtorta** [comment]
Fixed in the next revision.
