### ISSUE TITLE
Wanted: Caliph Scorpidsting

### ISSUE THREAD

**Issue by Firestoat** [slowtorta/turtlewow-bug-tracker#1385]
There are 2 problems with this quest, which is currently broken.
1 -- There should be a Wanted! poster in-game object spawned at location 51.9, 27 within Gadgetzan that allows a player within the proper level range to acquire the quest. It is currently not spawned at all in Gadgetzan, Tanaris zone at that location or anywhere else nearby.

In Game Screenshot -- https://postimg.cc/Vrvvk15n

2 -- The quest target NPC Caliph Scorpidsting IS spawned and walks his correct patrol path where he should be in the Tanaris desert. The issue is that there should be 2 Wastelander Rogue mobs using stealth that should be following him very closely as he patrols. These bodyguard Rogue mobs are not spawned or patrolling with him.

In Game Screenshot -- https://postimg.cc/56YPFFDk

TurtleWoW quest link -- https://database.turtle-wow.org/?quest=2781

TurtleWoW Wanted Poster Object Link -- https://database.turtle-wow.org/?object=150075
TurtleWoW Caliph Scorpidsting Mob Link -- https://database.turtle-wow.org/?npc=7847
TurtleWoW Wastelander Rogue Mob Link -- https://database.turtle-wow.org/?npc=5615

Suggestion -- A common issue on a Mang0s core server is that a player may tag / aggro Caliph Scorpidsting and run him away from his 2 rogue bodyguards, kill him, loot his head, and then run off to leave the 2 rogue bodyguards with a broken path / script with the quest target mob gone. Once the quest starter Wanted Poster object is added and working, and the 2 rogue bodyguard mobs are added to Caliph Scorpidsting's patrol route, the script for a similar quest target / bodyguard patrol set could be referenced to keep the whole thing working well.

This reference quest with a target mob + bodyguards that IS working well on the server would be the horde Barrens Quest - Hezrul Bloodmark.

TurtleWoW Hezrul Bloodmark Quest Reference link -- https://database.turtle-wow.org/?quest=852

**Comment by atazs** [comment]
Ummm i have completed this quest? And there were also two stealthed NPCs following him

**Comment by Kruxis** [comment]
Greetings! All working as intended. Object IS already spawned =) 
![image](https://user-images.githubusercontent.com/32237664/170844142-68cb07cf-5c9a-4aef-9a2d-d5e64ca55fda.png)
