### ISSUE TITLE
Wanted: Andre Firebeard

### ISSUE THREAD

**Issue by Firestoat** [slowtorta/turtlewow-bug-tracker#1386]
This quest is currently broken in that both of my characters were unable to start it with the Wanted Poster game object. This was after confirming that the contents of my WDB folder was emptied and the game was restarted. The Wanted Poster game object IS spawned at the correct location in Tanaris, and the target mob Andre Firebeard IS also correctly spawned at his pirate cove location.

The Wanted Poster game object which players interact with to obtain the quest will need to be reviewed to see if it is enabled to allow players to obtain the offered quest.

In Game Screenshot of bugged Wanted Poster -- https://postimg.cc/N2THQYPb

TurtleWoW Quest Link -- https://database.turtle-wow.org/?quest=2875
TurtleWoW Wanted Poster object Link -- https://database.turtle-wow.org/?object=150075
TurtleWoW Andre Firebeard Mob Link -- https://database.turtle-wow.org/?npc=7883

**Comment by slowtorta** [comment]
I believe you're looking at the wrong poster :) Please check the location of the poster on our DB (it's correct, same as on Classic). 
![image](https://user-images.githubusercontent.com/66763404/168465394-3cd9d80c-5cd4-4433-91ac-e7df72d2af52.png)

Working as intended.
