### ISSUE TITLE
Divine Shield doesn't protect you from drowning

### ISSUE THREAD

**Issue by PabloMB95** [slowtorta/turtlewow-bug-tracker#1387]
**Please, provide a clear description what the bug is:**

When the paladin activates the ability "Divine Shield" while underwater, it doesn't protect the paladin from damage caused by drowning.

![image](https://user-images.githubusercontent.com/46705245/167497858-08f52238-6e1b-40f6-92d8-3848af8119c0.png)

**Steps to reproduce the behavior with as much detail as possible:**

1. Stay underwater until you are out of breath.
2. The paladin uses Divine Shield.
3. The paladin is taking damage while Divine Shield is active and dies.

**IDs of affected creatures, items, quests or spells with a link to the relevant page:**

Spell: https://database.turtle-wow.org/?spell=642

**Expected behavior. Describe how it should work:**

The paladin shouldn't take any damage while drowning.

Evidence:

Classic WoW: ![image](https://user-images.githubusercontent.com/46705245/167497580-68225e7e-2afc-42ef-8b8b-a3a3a230805e.png)

WoWHead: https://www.wowhead.com/spell=642/divine-shield#comments:id=321966

WoWWiki: https://vanilla-wow-archive.fandom.com/wiki/Divine_Shield

**Comment by jameyboor** [comment]
Fixed on next server update.
