### ISSUE TITLE
A Letter From a Friend (Broken Quest)

### ISSUE THREAD

**Issue by Firestoat** [slowtorta/turtlewow-bug-tracker#1388]
This custom content quest is currently not working for either of my Horde characters. I did double check it by deleting the contents of my WDB folder and restarting the game. I am able to accept the quest and can find it in my quest log, but when my character reaches the target area and stands right on top of the crashed rocket car, nothing happens. I double checked this with both characters standing on the object and running an increasingly larger circle around the crashed car as well as follow its path up into the hillside. The quest refused to complete so the next stage could be started.

In Game Screenshot -- https://postimg.cc/2LwCQKqr

TurtleWoW Quest Link -- https://database.turtle-wow.org/?quest=80407

**Comment by Tinyfin-github** [comment]
Greetings! The quest works. You are not at the correct location. Please follow the crash path and look for a object that will draw your attention.
