### ISSUE TITLE
Frostfire Robe Stat Bug

### ISSUE THREAD

**Issue by afizzler** [slowtorta/turtlewow-bug-tracker#1389]
Frostfire robe should have 13 spell penetration, but in-game and database show it as not having 13 spell penetration. On Classic WoW, it has 13 spell penetration. 

1. Look at the stat values from WoW Classic for Frostfire Robe and compare to the stat values from this server in-game and database. 

WoW Classic version: https://classic.wowhead.com/item=22496/frostfire-robe

Turtle WoW version: https://database.turtle-wow.org/?item=22496

**Comment by AyleeJenn** [comment]
I might be wrong on this (do feel free to correct me if I am) but one percent of spell hit would translate vaguely to a value of thirteen spell penetration making it somewhat synonymous I believe.

**Comment by slowtorta** [comment]
Fixed in the next revision.
