### ISSUE TITLE
Jubie Gadgetspring is hostile to Horde Players

### ISSUE THREAD

**Issue by FeyfolkenFantasy** [slowtorta/turtlewow-bug-tracker#1391]
**Please, provide a clear description what the bug is:**

Jubie Gadgetspring is a Gnome npc located in Aszhara. On Turtle WoW, she is hostile to Horde players when she is not supposed to be.

**Steps to reproduce the behavior with as much detail as possible:**

1. Play a Horde character.
2. Go to Aszhara.
3. Find Jubie Gadgetspring in the coordinates "45.3, 91".
4. See that you can not interacte with her, nor buy item from her.

**IDs of affected creatures, items, quests or spells with a link to the relevant page:**

NPC: https://database.turtle-wow.org/?npc=8678

**Expected behavior. Describe how it should work:**

Jubie Gadgetspring is supposed not to be affilated with Gnomeregan.
She is supposed to be neutral and used to be the npc who was selling the "Shematic : Deepdive Helmet" to both Alliance and Horde Engineers.
She was removed from the game in patch 4.0.3.

You can see that she is supposed to be friendly to both Alliance and Horde players with the links below:

https://wowpedia.fandom.com/wiki/Jubie_Gadgetspring
https://fr.classic.wowhead.com/npc=8678/jubie-gadgetspring

**Comment by slowtorta** [comment]
Fixed in the next revision.
