### ISSUE TITLE
Searing Whelp

### ISSUE THREAD

**Issue by Firestoat** [slowtorta/turtlewow-bug-tracker#1392]
There are 2 issues with the Searing Whelp mob located in Dustwallow Marsh.

1) Nearly half of the spawned mobs are Elite in status. This is in error - only the Dragonkin within the zone are Elites. These tiny whelps were never Elite in the 2004/2005 version of the retail game and were one of the few sources of Worn Dragonscales for Dragonscale Leatherworking with a solo character of appropriate mid 40's level.

2) The second issue is one shared by numerous spawns within the zone - Roughly 50% of the time when the mob is killed and skinned a player will not receive a leather based drop. This appears to be a database issue, possibly related to all of the custom content that was added to this zone.

In Game Screenshot of Mob - https://postimg.cc/kD8YVcq2

TurtleWoW Mob Link - https://database.turtle-wow.org/?npc=4324

Classic WoWHead Mob Link - https://classic.wowhead.com/npc=4324/searing-whelp#comments

**Comment by slowtorta** [comment]
Fixed in the next revision.
