### ISSUE TITLE
Bloodfen Screecher (Skinning)

### ISSUE THREAD

**Issue by Firestoat** [slowtorta/turtlewow-bug-tracker#1395]
The Bloodfen Screecher raptor Mob located in Dustwallow Marsh currently only gives a player a leather based loot drop from skinning 50% of the time. From my testing this appears to be a bug associated with mobs that spawn from specific locations, with half of the raptors always giving leather from skinning and the other half always giving a player nothing from skinning.

This is how it's currently working for the previously reported bugged mobs of Searing Whelp, Drywallow Vicejaw, and Bloodfen Razormaw. Specific mobs from specific spawn points are bugged for skinning.

In Game Image -- https://postimg.cc/CZrMq0Cs/318cb93b

TurtleWoW Mob Link -- https://database.turtle-wow.org/?npc=4352

WoWHead Classic Mob Link -- https://classic.wowhead.com/npc=4352/bloodfen-screecher

Observation -- As a side note, after leveling a pair of horde characters through the majority of horde related zones, it's only Dustwallow Marsh that I've located mobs with this issue. All the other zones are fine for skinning, leading me to think it might be related to the custom content added to Dustwallow + additional spawn placement and the loot database missing a draw.

**Comment by slowtorta** [comment]
I tested those and it's working as intended. The positioning of a mob cannot affect its loot table, it's simply impossible.

**Comment by cyaohiri** [comment]
This is related to #2283 and #2284. The mobs either disappear just after being skinned or indeed drop nothing; it's hard to tell which of the two is the case, as the result is the same. I've only noticed this in Dustwallow Marsh and Tanaris.
