### ISSUE TITLE
Goblin Rocket Cars Glitch

### ISSUE THREAD

**Issue by FeyfolkenFantasy** [slowtorta/turtlewow-bug-tracker#1396]
**Please, provide a clear description what the bug is:**

Goblin Rocket Cars do not follow the terrain curvature.

**Steps to reproduce the behavior with as much detail as possible:**

1. Get any of the 3 goblin rocket cars.
2. Ride hills!
3. See that your rocket car is stuck horizontally.

![Sans titre](https://user-images.githubusercontent.com/102554573/167948249-f3b40f97-531a-49e3-b722-65e4b6782c61.png)

**IDs of affected creatures, items, quests or spells with a link to the relevant page:**

Item: https://database.turtle-wow.org/?item=80460
Item: https://database.turtle-wow.org/?item=80461
Item: https://database.turtle-wow.org/?item=80462

**Expected behavior. Describe how it should work:**

Every standard WoW mount follow the terrain curvature, even though I am aware that goblin are famous for building stuff that act strangely.

**Special Note:** I started playing WoW late TBC. I remember the very first time I saw those rocket cars in the Shimmering Flats and thought "I wish I could ride one some day".
Fourteen years later, here I am, on TWoW riding one of those excentric mount!
Turtle WoW is a fantastic server and I thank everybody who participated and are participating to this project!

Much love!

**Comment by slowtorta** [comment]
Thank you, I'll take this report to the internal client-related bug tracker.
