### ISSUE TITLE
npc sells unlimited gychromatoms

### ISSUE THREAD

**Issue by geojak** [slowtorta/turtlewow-bug-tracker#1397]
**Please, provide a clear description what the bug is:**

the gyrochrom atom is an engineer part item. like many part items vendors have limited quantity amounts for sale. something must have broken, becuase some vendors ,e.g. in sw now sells unlimited amounts of these. 
![WoWScrnShot_051222_002006](https://user-images.githubusercontent.com/25199983/167957145-c33b9d14-c6ac-45d1-b7b8-a085a2a393b0.jpg)

https://database.turtle-wow.org/?item=4389
(see other vendor with unlimited amount on the db)

**Expected behavior. Describe how it should work:**

https://classic.wowhead.com/item=4389/gyrochronatom#sold-by
no unlimited parts that make ruin engineer ecoomy game on the ah pls

**Comment by geojak** [comment]
while fixing this, also check out

https://database.turtle-wow.org/?item=4364#sold-by
there is one single custom vendor in theg ame that sells unlimited amounts of coarse blasting powder.

**Comment by slowtorta** [comment]
Fixed in the next revision.
