### ISSUE TITLE
Ship from Durotar to Badlands kills you on transport

### ISSUE THREAD

**Issue by OonaQueenoftheBae** [slowtorta/turtlewow-bug-tracker#1398]
**Please, provide a clear description what the bug is:**
When taking the airship from Durotar to the Badlands, when you load into the badlands you take falling damage and die.

**Steps to reproduce the behavior with as much detail as possible:**

1. Get on the ship to the badlands in durotar
2. Wait for it to transition to the loading screen
3. Arrive dead in the badlands

**IDs of affected creatures, items, quests or spells with a link to the relevant page:**
N/A

NPC: https://database.turtle-wow.org/?npc=
Item: https://database.turtle-wow.org/?item=
Quest: https://database.turtle-wow.org/?quest=
Spell: https://database.turtle-wow.org/?spell=
Object: https://database.turtle-wow.org/?object=

**Expected behavior. Describe how it should work:**
Should not di
![shipdeath](https://user-images.githubusercontent.com/105398809/167966267-9582df5f-824e-406f-be00-992cfb93f735.jpg)
e

**Comment by slowtorta** [comment]
Duplicate, known.
