### ISSUE TITLE
Northshire Defias Thug Pathfinding 

### ISSUE THREAD

**Issue by Daemanis** [slowtorta/turtlewow-bug-tracker#1399]
**Please, provide a clear description what the bug is:**
The Defias Mobs in Northshire will not approach the river at all, and if you're standing on the river side closest to them they will avoid all damage and remain agro while doing so, pulling any other Defias mob to them in the process.  You then have to run almost across Northshire before they will drop Aggro on you and return to their normal pathing.
**Steps to reproduce the behavior with as much detail as possible:**

1. Approach the River (be close to it, though clearly on their side of it
2.  try to fight Any Defias Mobs
3. 

**IDs of affected creatures, items, quests or spells with a link to the relevant page:**

All Defias Mobs in Northshire

**Expected behavior. Describe how it should work:**
They will race up to you and attack you out to a certain point, the river should not impede there path finding in the least as it is not deep enough to swim.

**Comment by Tinyfin-github** [comment]
Greetings!

Thank you for reporting this bug.  It's a client side issue that's under investigation in our internal tracker.
