### ISSUE TITLE
Snowballs should proc judgement of wisdom

### ISSUE THREAD

**Issue by Velite12** [slowtorta/turtlewow-bug-tracker#14]
By opening this Issue, I admit to having done the pertinent research using sources from Vanilla (preferably) or Classic. I also understand that sources from other private servers are not acceptable.

**Current behavior**: 

Snowballs do not proc judgement of wisdom.

**Expected behavior**: 

Snowballs should proc judgement of wisdom.

**Proofs**:

https://www.youtube.com/watch?v=mPeBIJ1r1Jg

World rank 3 Ret paladin on patchwerk

![image](https://user-images.githubusercontent.com/45871932/120870898-3caa5a80-c568-11eb-837b-1188c9865b61.png)

**Steps to reproduce**:

1. Judge wisdom on an enemy
2. Use a snowball on them
3. Wisdom will not proc

**Comment by Nolin7777** [comment]
Closed after internal discussion

**Comment by geojak** [comment]
do we really want snowballs to proc this thought, even if its blizzlike.

**Comment by slowtorta** [comment]
Snowball is a fun holiday item, it shouldn't cause any procs, from my point of view, I'm sorry.
