### ISSUE TITLE
Can't open chest  in Westfall. Out of line of sight error.

### ISSUE THREAD

**Issue by SierraNairn** [slowtorta/turtlewow-bug-tracker#140]
Can't open chest  in Westfall. Out of line of sight error.
Location:

![WoW_tAWW6O8rAg](https://user-images.githubusercontent.com/83077166/124379669-155ac080-dcc1-11eb-81c5-7e54e6499e72.png)

![WoW_GzJZxieUsD](https://user-images.githubusercontent.com/83077166/124379688-21df1900-dcc1-11eb-850b-6ef05b02464b.png)

**Comment by slowtorta** [comment]
Thanks for reporting it. It'll be fixed on the next server restart. Make sure to clear your WDB folder.
