### ISSUE TITLE
Trasmogrified items reset their appearance on any durability change

### ISSUE THREAD

**Issue by spuxx1701** [slowtorta/turtlewow-bug-tracker#1400]
**Please, provide a clear description what the bug is:**
Trasmogrified items will reset their visual appearance on any durability change (e.g. by taking durability damage or repairing).

**Steps to reproduce the behavior with as much detail as possible:**

1. Transmog a gear piece and have it equipped.
2. Cause the durability of that gear piece to change while.
3. Gear piece will revert to it's original appearance (that of the actual item).

The bug is client-side only and does not affect other clients - for them, the gear piece will keep its transmogrified appearance. Reequipping the gear piece or logging back in fixes the appearance.

**Expected behavior. Describe how it should work:**
Transmogrified gear pieces should keep their appearance also on durability changes.

**Comment by AyleeJenn** [comment]
There is something you can do as a temporary work around until this gets fixed. Make sure you are out of combat and un-equip and re-quip your item. That will restore your custom appearance at least temporarily.

**Comment by LeopoldHock** [comment]
I am aware of this workaround, but durability changes too often for that to be a satisfying solution.

**Comment by Sringaram** [comment]
Has this been memoryholed?

**Comment by slowtorta** [comment]
We're aware of all the issues related to transmog. There's no point to fix single flaws in the current system, as it must be reworked all together in the future.

**Comment by twowTurtReynolds** [comment]
This issue was fixed recently!
