### ISSUE TITLE
korvir's prey npc barrens

### ISSUE THREAD

**Issue by gigachadbro** [slowtorta/turtlewow-bug-tracker#1401]
**Please, provide a clear description what the bug is:**
In barrens , the npc "korvir's prey" have 0 Hp and it serve just as i see as decoration to show that the wolf " korvir " do chase dinosaurs there . 
But it can receive damage and then it does follow the player making him staying in combat . 

**IDs of affected creatures, items, quests or spells with a link to the relevant page:**

NPC: https://database.turtle-wow.org/?npc=60412

**Expected behavior. Describe how it should work:**
normally , it shouldnt receive any area of effect damage or effects by players 
![image](https://user-images.githubusercontent.com/46192630/168173414-0b44795d-6818-4416-abac-e3d18997e3ad.png)
![image](https://user-images.githubusercontent.com/46192630/168173871-bad5e66e-197d-4f7b-81d1-01decd9635e4.png)
![image](https://user-images.githubusercontent.com/46192630/168173898-59790f0f-6119-403e-8265-a8f67556296a.png)

**Comment by slowtorta** [comment]
Thank you, this will be fixed in the next revision.
