### ISSUE TITLE
Tirion Fordring won't give Redemption after completing Demon Dogs

### ISSUE THREAD

**Issue by Tinyfin-github** [slowtorta/turtlewow-bug-tracker#1402]
Tirion Fordring https://database.turtle-wow.org/?npc=1855 Won't give Redemption https://database.turtle-wow.org/?quest=5742 after completing [Demon Dogs](https://database.turtle-wow.org/?quest=5542)

**Comment by geojak** [comment]
Did you sit? Or was that, some other part of the qeust line where you needed to sit?
