### ISSUE TITLE
A Diplomatic Mission

### ISSUE THREAD

**Issue by Drwarlocke** [slowtorta/turtlewow-bug-tracker#1403]
**Please, provide a clear description what the bug is:**
Hi 
Go the quest for A Diplomatic Mission from the NPC Ranger-General Damilara Sunsorrow 
she gave me 4 more quest speka to Stormwind and Ironfors, Gnome and last Night elf...
i spoke to Stormwind and Ironforge but when i get to Gnome king no question mark at all?..
i open the quest book the quest for Appealing to the Alliance: Gnome King is not in my quest book?? i know i take the quest..
i go back to Ranger-General Damilara Sunsorrow She dont have the quest any more`?.. i deleted the quest all of them 
And now I can not get any quest from her at all??

**Steps to reproduce the behavior with as much detail as possible:**

1. A Diplomatic Mission + 4 Appealing to the Alliance
2. 3 quest work and 1 dont work Appealing to the Alliance Gnome dont work?
3. I deleted all quests and know ther is no quest to get from Ranger-General Damilara Sunsorrow ??

**IDs of affected creatures, items, quests or spells with a link to the relevant page:**

NPC: https://database.turtle-wow.org/?npc=
Item: https://database.turtle-wow.org/?item=
Quest: https://database.turtle-wow.org/?quest=
Spell: https://database.turtle-wow.org/?spell=
Object: https://database.turtle-wow.org/?object=

**Expected behavior. Describe how it should work:**

**Comment by Tinyfin-github** [comment]
Greeting!

The issue where you would get the wrong quest items and you were unable to complete the Appealing to the Alliance quest chain has  been fixed. Please clear your WDB folder while the game is closed and take the quests again for the correct items to be provided.

If you encounter any more issues, please open an in game ticket  for GM assistance.
