### ISSUE TITLE
Spellpower Goggles Xtreme don't glow for male goblins

### ISSUE THREAD

**Issue by Tinyfin-github** [slowtorta/turtlewow-bug-tracker#1404]
Spellpower Goggles Xtreme https://database.turtle-wow.org/?item=10502  don't glow for male goblins. They should glow.

![ShareX_NYgPJQ930i](https://user-images.githubusercontent.com/83077166/168417139-c31350b6-52ec-489a-bda0-c0d29728b001.png)
![ShareX_l7wohpfjcl](https://user-images.githubusercontent.com/83077166/168417141-ff527677-38af-4b6d-a6fc-a4211f747d84.png)
![ShareX_746mtsVWqh](https://user-images.githubusercontent.com/83077166/168417142-911a39be-1e3a-4a62-9878-18fe165d2e72.png)

**Comment by slowtorta** [comment]
I don't think it's something we can fix, honestly. But I'll move it to the internal tracker.
