### ISSUE TITLE
Compact Harvest Reapers are mean!

### ISSUE THREAD

**Issue by FeyfolkenFantasy** [slowtorta/turtlewow-bug-tracker#1405]
**Please, provide a clear description what the bug is:**

In the Stranglethorn Vale, the Venture Co. Tinkerers are npcs who have the ability to summon two Compact Harvest Reapers.
If you manage to escape a Venture Co. Tinkerer attacking you with his two minions Compact Harvest Reapers, you will be stuck in combat forever.
The only solution to solve this issue is to close the game with the Task Manager and log back in to get out of combat.

**Steps to reproduce the behavior with as much detail as possible:**

1. Go to the Stranglethorn Vale around the coordinates 41,43.
2. Aggro a Venture Co. Tinkerer, he is going to summon two Compact Harvest Reaper.
3. Escape them, you will be stuck in combat forever.

**IDs of affected creatures, items, quests or spells with a link to the relevant page:**

NPC: https://database.turtle-wow.org/?npc=667
NPC: https://database.turtle-wow.org/?npc=2676

**Expected behavior. Describe how it should work:**

After you managed to escape the Venture Co. Tinkerer and his two Compact Harvest Reapers, you should not get stuck into combat forever.
Being a coward and surrender from a fight is a right xD

**Comment by slowtorta** [comment]
Couldn't reproduce. Probably related to a general bug related to stucking in aggro, not specifically to those mobs.
