### ISSUE TITLE
Bloodsail npcs Pathfinding issue

### ISSUE THREAD

**Issue by FeyfolkenFantasy** [slowtorta/turtlewow-bug-tracker#1406]
**Please, provide a clear description what the bug is:**

Playing with my 41 rogue, I was visiting one of the boat south of Booty Bay (Stranglethorn Vale). I was able to sneak up to the captain cabin of one of those boat when I aggroed a pirate.
Then I sprinted to the top of the boat and jumped in the water at the opposite side of the ramp leading to this boat.
I was thinking "it shall be ok, by the time they take the ramp and swim to me I will be far".

But I was wrong. The pirates chased me, ran and swam at hyper speed, and killed me.
Then I saw them fly and go through the boat walls to reach their original position.

**Steps to reproduce the behavior with as much detail as possible:**

1. Go to the Stranglethorn Vale, with a rogue lvl~41-42.
2. Sneak into one of the 3 boats south of Booty Bay.
3. Aggro any npc and sprint on the top of a boat.
4. Jump to the water at the opposite side of the ramp leading to the boat you've chosen.

**IDs of affected creatures, items, quests or spells with a link to the relevant page:**

NPC: https://database.turtle-wow.org/?npc=1565
NPC: https://database.turtle-wow.org/?npc=1653
NPC: https://database.turtle-wow.org/?npc=4505
NPC: https://database.turtle-wow.org/?npc=4506

**Expected behavior. Describe how it should work:**

Those npcs shall not run that fast nor being able to walk through walls when chasing a player character, or when the are going back to there original position.

**Comment by slowtorta** [comment]
It's not something that we can fix for just one NPC or one specific zone. Next week there'll be either a complex fix for all related issues in the world, or nothing.
