### ISSUE TITLE
By Any Means Necessary I | Typos in quest description

### ISSUE THREAD

**Issue by jlautenbach** [slowtorta/turtlewow-bug-tracker#1407]
**Please, provide a clear description what the bug is:** 
Typos in quest's description:
1. 'then' should be 'than'
2. 'lands corruption' should be 'land's corruption' 

**Steps to reproduce the behavior with as much detail as possible:**

1. Check DB: https://database.turtle-wow.org/?quest=40397
2. Verify in-game: 
   a. teleport to [Niremius Darkwind](https://database.turtle-wow.org/?npc=60710)
   b. Open a dialog, see quest description of quest By Any Means Necessary I

**IDs of affected creatures, items, quests or spells with a link to the relevant page:**

NPC: https://database.turtle-wow.org/?npc=60710
Quest: https://database.turtle-wow.org/?quest=40397

**Expected behavior. Describe how it should work:**
Typos should be corrected.

![image](https://user-images.githubusercontent.com/73019779/168440243-b922516e-a14c-4f04-aa33-3d0b417deb8e.png)

**Comment by slowtorta** [comment]
Fixed in the next revision.
