### ISSUE TITLE
By Any Means Necessary questline | No gold reward instead of XP at max level

### ISSUE THREAD

**Issue by jlautenbach** [slowtorta/turtlewow-bug-tracker#1408]
**Please, provide a clear description what the bug is:**
When doing questline By Any Means Necessary (https://database.turtle-wow.org/?quest=40397) with a level 60 character, the exp reward is not converted to a silver/gold reward.

**Steps to reproduce the behavior with as much detail as possible:**

1. Port to [Niremius Darkwind](https://database.turtle-wow.org/?npc=60710)
2. Accept quest By Any Means Necessary I (https://database.turtle-wow.org/?quest=40397)
3. Complete quest
4. No reward in silver/gold is observed (note that RewExp is given when < 60)

**IDs of affected creatures, items, quests or spells with a link to the relevant page:**

NPC: https://database.turtle-wow.org/?npc=60710
Quest: https://database.turtle-wow.org/?quest=40397

**Expected behavior. Describe how it should work:**
RewExp should be converted to a silver/gold reward when at max-level.

_Reported by Twilightish, reproduced by Niral
![image](https://user-images.githubusercontent.com/73019779/168440548-c4bdeff3-0147-4c8d-a946-6c1c8e17da5d.png)

**Comment by slowtorta** [comment]
Fixed in the next revision.
