### ISSUE TITLE
duplicate categories for cavern of time quests

### ISSUE THREAD

**Issue by geojak** [slowtorta/turtlewow-bug-tracker#1409]
**Please, provide a clear description what the bug is:**

**Steps to reproduce the behavior with as much detail as possible:**

![WoWScrnShot_051522_141535](https://user-images.githubusercontent.com/25199983/168472394-625dd2ce-882e-4b41-8994-bafba81b1755.jpg)

1. see mz screenshot
2. check out the cavern of times quests
3. there are 2 duplicate but seperate categories

**IDs of affected creatures, items, quests or spells with a link to the relevant page:**

https://database.turtle-wow.org/?quest=80605
https://database.turtle-wow.org/?quest=40340

**Expected behavior. Describe how it should work:**

first opening of dark portal qeust should be together with the other cavern of times quests for example with corrupted sand

**Comment by slowtorta** [comment]
Fixed in the next revision.
