### ISSUE TITLE
Can't open chest in Swamp of Sorrows. Out of line of sight error.

### ISSUE THREAD

**Issue by SierraNairn** [slowtorta/turtlewow-bug-tracker#141]
Can't open chest in Swamp of Sorrows. Out of line of sight error.

Location:

![WoW_8faoWL5bRq](https://user-images.githubusercontent.com/83077166/124379730-5ce14c80-dcc1-11eb-9efe-fa3f0dcbb68a.png)

![WoW_2RsosTW1X6](https://user-images.githubusercontent.com/83077166/124379734-623e9700-dcc1-11eb-9d22-5404d0364ac4.png)

**Comment by slowtorta** [comment]
Thanks for reporting it. It'll be fixed on the next server restart. Make sure to clear your WDB folder.
