### ISSUE TITLE
Ice Crawler crabs are humanoids

### ISSUE THREAD

**Issue by Gasan918** [slowtorta/turtlewow-bug-tracker#1410]
**Please, provide a clear description what the bug is:**

Ice Crawler crabs in Kaneq'nuun and Icepoint Rock loactions have 'humanoid' type of NPC.

![image](https://user-images.githubusercontent.com/96973359/168474331-25b7fa1b-0697-4172-a34f-6ac1fd36fd65.png)

**IDs of affected creatures, items, quests or spells with a link to the relevant page:**

NPC: https://database.turtle-wow.org/?npc=60605

**Expected behavior. Describe how it should work:**

Crabs should be beasts.

**Comment by slowtorta** [comment]
Fixed in the next revision.
