### ISSUE TITLE
Amani eagle pet movement speed bugged (too slow)

### ISSUE THREAD

**Issue by Khanz0** [slowtorta/turtlewow-bug-tracker#1411]
*the new custom Hunter pet "amani eagle" (added as a skin of owl) have his movement speed bugged. He is too slow. Even with the talent "bestial swiftness"

Without the talent he is slower than any mob. You can kite any mob and the eagle cant attack him because the mob moves faster than eagle

And if you are mounted the eagle cant run as fast as yourself (even with the talent)

**Steps to reproduce the behavior with as much detail as possible:**

1.just have a amani eagle as hunter pet
2. Kite any mob or mount
3. See his slow speed

**IDs of affected creatures, items, quests or spells with a link to the relevant page:**

NPC: https://database.turtle-wow.org/?npc=80920

**Expected behavior. Describe how it should work:**

The pet should be as fast as any mob without talent. And with the talent should be run as fast as you even mounted (as any other pet)

**Comment by slowtorta** [comment]
Fixed in the next revision.

**Comment by Khanz0** [comment]
Thanxs

I think only happens when the eagle is.in combat
