### ISSUE TITLE
[Quest] Reinforcing The Sepulcher: Missing quest reward, player is not actually awarded anything

### ISSUE THREAD

**Issue by 9600bauds** [slowtorta/turtlewow-bug-tracker#1412]
**Please, provide a clear description what the bug is:**
This quest says it will reward you with blacksmithing plans: "Upon delivery you will be rewarded with plans for a new set of armor", however, you receive no plans, and even if you're a blacksmith (83 skill as of this bug report) you don't learn any recipes either.
Checking the turtle database, the alliance quest ["Gearing Redridge"](https://database.turtle-wow.org/?quest=1618) is the Alliance version of the same quest, and it does reward the player with green-quality blacksmithing plans.
It's also a pretty expensive quest to make for its level range so it's a real letdown :(

**Steps to reproduce the behavior with as much detail as possible:**

1. Accept the quest
2. Read the quest text promising you cool plans for a new and exciting set of armor that you've never seen before!!
3. Turn in the quest
4. Receive nothing
5. Sadness

**IDs of affected creatures, items, quests or spells with a link to the relevant page:**
Quest: https://database.turtle-wow.org/?quest=70040

**Expected behavior. Describe how it should work:**
Player should be awarded a blacksmithing plan or recipe for completing the quest.

**Comment by slowtorta** [comment]
Fixed in the next update. The tooltip of the recipe might show the wrong item but it'll be fixed with the upcoming client patch.
