### ISSUE TITLE
Holy Strike not refreshing judgments

### ISSUE THREAD

**Issue by gmarguelles** [slowtorta/turtlewow-bug-tracker#1413]
**Please, provide a clear description what the bug is:**
Holy Strike is not refreshing judgments

**Steps to reproduce the behavior with as much detail as possible:**

1. Judge any seal ( I used Wisdom)
2. Wait for Holy Strike Auto Attack
3. Judgment not refreshed

I dont know if this is intended but Holy Strike does not refresh judgments.

**Comment by slowtorta** [comment]
It's not intended, it's a bug and yet to be fixed. Duplicate: https://github.com/slowtorta/turtlewow-bug-tracker/issues/975
