### ISSUE TITLE
Verog the Dervish can spawn when he's already spawned, usually results in an untouchable army of Verog the Dervishes

### ISSUE THREAD

**Issue by 9600bauds** [slowtorta/turtlewow-bug-tracker#1415]
**Please, provide a clear description what the bug is:**
Verog the Dervish spawns very often. Which is fine, except that he also spawns when he's already spawned.
This results in an untouchable deathblob of Verog that you can't really do anything about without help from a 60

**Steps to reproduce the behavior with as much detail as possible:**

1. Kill a few centaurs around the area as part of your normal questing
2. Once every few kills, another Verog spawns
3. ![WoW_22-05-16-15-03-55](https://user-images.githubusercontent.com/6526157/168655326-c9aac287-56de-4323-bf58-4e6da0b00f83.png)
![FSViewer_22-05-16-15-09-36](https://user-images.githubusercontent.com/6526157/168656105-fc50c17b-7cae-4335-a84e-d069c0249604.png)

**IDs of affected creatures, items, quests or spells with a link to the relevant page:**

NPC: https://database.turtle-wow.org/?npc=3395

**Expected behavior. Describe how it should work:**
Not sure? It's possible that this could always have happened before and it only wasn't a problem due to the low spawn chance. It would make sense if only one Verog could spawn at a time though.

**Comment by Gasan918** [comment]
I was doing this quest on Sunday. Yes, Verog spawned 4 or 5 another Verogs, lol. Killed all of them ofc (I was 41)

**Comment by slowtorta** [comment]
Lowered the chance again.

**Comment by 9600bauds** [comment]
FWIW this still happens semi-often, it's just limited to 2-3 Verogs at a time
