### ISSUE TITLE
[Item] Hidden Shoulders have wrong armor values on their tooltip

### ISSUE THREAD

**Issue by 9600bauds** [slowtorta/turtlewow-bug-tracker#1416]
**Please, provide a clear description what the bug is:**
The Hidden Shoulders that were added recently for transmog purposes have a discrepancy in the tooltip. They appear to be white shoulders which, although they have no other stats, have an unusually high armor rating:
![WoW_22-05-16-18-44-28](https://user-images.githubusercontent.com/6526157/168687744-9c83af84-913f-4cbe-aaca-2c39cbcbe184.png)
For context, at level 17, I have 656 armor so this would be a 50% boost.
However, after you actually buy the shoulders and equip them, your character pane armor value only goes up by 1.

**Steps to reproduce the behavior with as much detail as possible:**

1. Buy hidden shoulders
2. Equip them
3. Notice how your armor increases by 1 instead of however much it says on the tooltip

**IDs of affected creatures, items, quests or spells with a link to the relevant page:**

Item: https://database.turtle-wow.org/?item=83542

**Expected behavior. Describe how it should work:**
It should just say "1 armor" to prevent me from being tricked into buying them. They cost like 20 silver and I will never financially recover from this jape.

**Comment by slowtorta** [comment]
Please clear your WDB folder. The tooltip values are wrongly cached.
