### ISSUE TITLE
Auction House interface shows deposit fees, although there are no deposit fees

### ISSUE THREAD

**Issue by 9600bauds** [slowtorta/turtlewow-bug-tracker#1417]
**Please, provide a clear description what the bug is:**
When you're at the AH and try to post something, you will be informed of the deposit fees from making the auction:
![WoW_22-05-16-18-51-32](https://user-images.githubusercontent.com/6526157/168688536-8413b9b6-3e73-4876-8c70-b8814a85893f.png)
However, there are no deposit fees from Turtle AH as far as I can tell, and when you post the auction, you lose no gold to the fee.
This really confused me as a new player and prevented me from realizing how the Turtle AH works for a while.

**Steps to reproduce the behavior with as much detail as possible:**

1. Try to post item on the AH
2. Notice the deposit fee window
3. Post the item
4. Notice that you have lost no gold

**Expected behavior. Describe how it should work:**
It should show a deposit fee of 0 copper.

**Comment by jameyboor** [comment]
Due to a change in AH deposit handling this will be fixed upon next patch release.

**Comment by geojak** [comment]
Are you reintroducing introducing fees? Pls not
