### ISSUE TITLE
Korvir's Prey is classified as a humanoid, should be beast

### ISSUE THREAD

**Issue by 9600bauds** [slowtorta/turtlewow-bug-tracker#1418]
**Please, provide a clear description what the bug is:**
![WoW_22-05-17-00-11-21](https://user-images.githubusercontent.com/6526157/168720869-e078903a-2116-4df3-9f38-baba07577571.png)

**IDs of affected creatures, items, quests or spells with a link to the relevant page:**

NPC: https://database.turtle-wow.org/?npc=60412

**Expected behavior. Describe how it should work:**
Should be a beast

**Comment by slowtorta** [comment]
Fixed in the next revision.
