### ISSUE TITLE
mankirks wife quest barrens crossroads horde 

### ISSUE THREAD

**Issue by gigachadbro** [slowtorta/turtlewow-bug-tracker#1420]
**Please, provide a clear description what the bug is:**
Im horde warrior orc ,  found mankirks wife  quest " lost in battle "  is complete in my quests , while i didnt done it at all . 
Btw before this happens i went to do this quest " the disruption ends " : https://database.turtle-wow.org/?quest=872

**IDs of affected creatures, items, quests or spells with a link to the relevant page:**

Quest: https://database.turtle-wow.org/?quest=4921

**Expected behavior. Describe how it should work:**
i never ever meet mankirks wife npc , i just took the quest 
![image](https://user-images.githubusercontent.com/46192630/168873274-a8287ddc-d129-49a4-8ce4-a0d3a7bf5712.png)

**Comment by slowtorta** [comment]
Can't reproduce, working as intended. You probably clicked on the Beaten Corpse NPC in Barrens. That completes the quest.

**Comment by gigachadbro** [comment]
i didnt even gone south barrens as in screenshot , btw dont know why its not " complete " anymore XD its a bug for sure ![image](https://user-images.githubusercontent.com/46192630/168925057-bd96e9cd-cefe-44eb-b13f-a0cb7d69a13e.png)
