### ISSUE TITLE
Shadowguard bugged out

### ISSUE THREAD

**Issue by KyrielleRedwyne** [slowtorta/turtlewow-bug-tracker#1422]
**Please, provide a clear description what the bug is:**

I am loosing charges of my Shadowguard when no one's hitting me, no dots, nothing. When in combat, or when i'm **not** in combat, doesn't matter. This appears to happen anytime i'm healing myself or anybody else. I realise it happens because my own Shadowguard is hitting me, which causes the charges to be used. The problem appeared today. Never had this issue before.

Also i tried out in a duel to see if this bug only occurs while casting heals. Whenever i use an offensive spell, it doesn't seem to bug, everything's normal. When i use my wand, the bug occurs once again -getting hit by my own Shadowguard when i hit my target with a wand-, but it doesn't occur when i use my main weapon.  

I did relogged, and deleted cache, still the issue is happening.

As an exemple, from my combat log:

"You gain Renew.
Your Shadowguard hits you for 97 Shadow damage."

![shadowguard](https://user-images.githubusercontent.com/105807806/169093193-72353bef-04af-49fe-a7ac-be8478bd11d0.png)

**Steps to reproduce the behavior with as much detail as possible:**

1. I put my Shadowguard buff. 3 charges.
2. I heal myself/anyone. Can be an instant (Renew) or not (Flash Heal, Greater Heal....)  /  I attack someone with my wand, that person doesn't attack me, stays still, no buffs on him.
3. I instantly get damaged by Shadowguard, which ofc looses its charges. (Loosing from 1 to 2 charges from what i've seen, for each heal/attack)

**IDs of affected creatures, items, quests or spells with a link to the relevant page:**

Spell: https://database.turtle-wow.org/?spell=18137

**Expected behavior. Describe how it should work:**

Shadowguard is supposed to hit the person who's hitting you when you have charges on it. It isn't supposed to proc when not in combat -not getting attacked, not attacking anyone either- and it isn't supposed to deal damage to yourself either.

**Comment by KyrielleRedwyne** [comment]
Alright, i've asked if i was the only one having this problem, i and it appears other priests have this issue as well. Just so you know.

**Comment by slowtorta** [comment]
Fixed in the next revision.
