### ISSUE TITLE
ghost gryphon master doesnt work in eastern plagueland

### ISSUE THREAD

**Issue by geojak** [slowtorta/turtlewow-bug-tracker#1424]
**Please, provide a clear description what the bug is:**

**Steps to reproduce the behavior with as much detail as possible:**
![WoWScrnShot_051822_224256](https://user-images.githubusercontent.com/25199983/169152483-14fd8398-4435-48ce-9e3d-10d1385bec07.jpg)

![WoWScrnShot_051822_224258](https://user-images.githubusercontent.com/25199983/169152478-c3909d1f-86ed-4f80-99bb-51b8570fce9b.jpg)

1. cap the plaguetower in the top left part
2. get the ghost gryphon master to spawn after capping the tower
3. try to fly to another tower
4. doesnt work, no option to fly

**IDs of affected creatures, items, quests or spells with a link to the relevant page:**

https://database.turtle-wow.org/?npc=17209

**Expected behavior. Describe how it should work:**

you should be ablte to fly to other towers
https://wowwiki-archive.fandom.com/wiki/A_Game_of_Towers

"Finally, the [Plaguewood Tower](https://wowwiki-archive.fandom.com/wiki/Plaguewood_Tower) contains a Ghost Flight Master, who will allow you and your team to fly to any of the other three towers, on a special ghostly flying mount. This is very useful for quick reinforcement of contested zones -- and is also fairly handy for getting to [Light's Hope Chapel](https://wowwiki-archive.fandom.com/wiki/Light%27s_Hope_Chapel) quickly (fly to [Eastwall Tower](https://wowwiki-archive.fandom.com/wiki/Eastwall_Tower) and ride south)."

also check the npc saying so himself but doesnt offer it ingame

**Comment by geojak** [comment]
Also, as can be seen in the screenshot. The north Western tower is not displayed on the map at all

**Comment by redmagejoe** [comment]
This option is still not offered even when all 4 towers are captured on current version.
