### ISSUE TITLE
Bael Modan Golem not immune to bleeds

### ISSUE THREAD

**Issue by 9600bauds** [slowtorta/turtlewow-bug-tracker#1425]
**Please, provide a clear description what the bug is:**
Bael Modan Golem seems to be a completely default "humanoid" mob without the characteristic traits of other golems. For example, it's not immune to bleeds, and probably other things.
(It also drops no loot at all. It also has no abilities. Also Bael Modan, the zone, says that it's actually "razorfen downs" a lot. Also the zone has no mining nodes. ...the whole place really needs some polish, it's seriously the most boring quest I've played, without exaggerating) 

**Steps to reproduce the behavior with as much detail as possible:**

1. Go to golem
2. Notice how it's not bleed immune, like other golems
3. Also notice it drops no loot

**IDs of affected creatures, items, quests or spells with a link to the relevant page:**

NPC: https://database.turtle-wow.org/?npc=60442

**Expected behavior. Describe how it should work:**
It should bleed, drop loot, and probably do *something, anything* since it's the only mob in the entire cave

**Comment by Kruxis** [comment]
Greetings!

Thanks for the report, the issue will be fixed on next server restart =)
