### ISSUE TITLE
Ostarius: X-faction PvP protection kicks players from the raid group during the fight

### ISSUE THREAD

**Issue by spuxx1701** [slowtorta/turtlewow-bug-tracker#1426]
**Please, provide a clear description what the bug is:**
During Ostarius boss fight, apparently the cross-faction PvP protection leads to players being kicked from the raid group mid-fight upon taking damage from Conflag by the adds (Xerron has details). Needs to be tested with a cross-faction group.

**Comment by SabineWren** [comment]
This also happens with the trash before Lethon, as the elite dragons mind control people.
