### ISSUE TITLE
No minimap inside Amani'Alor cave

### ISSUE THREAD

**Issue by 9600bauds** [slowtorta/turtlewow-bug-tracker#1427]
**Please, provide a clear description what the bug is:**
When you go into the Amani'Alor (the troll quest hub in Stonetalon that you can teleport to from org) cave (the one with the risen trolls that you have to light pyres inside of), your minimap is completely empty. Finding the exit can be problematic if it's your first time there.

**Steps to reproduce the behavior with as much detail as possible:**

1. Go to Amani'Alor
2. Step inside the cave that has the risen trolls
3. Notice how your minimap is empty
4. Walk deeper into the cave
5. Forget where you are
6. Get completely lost

**Expected behavior. Describe how it should work:**

There should be a minimap inside, similar to other caves or structures

**Comment by slowtorta** [comment]
Client issue, taking it to the internal tracker, thank you.
