### ISSUE TITLE
SFK: Arugal's Voidwalker can inexplicably become stuck in evade mode, preventing progress into the dungeon

### ISSUE THREAD

**Issue by 9600bauds** [slowtorta/turtlewow-bug-tracker#1429]
**Please, provide a clear description what the bug is:**
In SFK, after you kill Fenrus the Devourer, a few Arugal's Voidwalker mobs will spawn. You must kill all of these mobs before the gate in the room opens and you can progress further into the dungeon. However, these voidwalkers have a nasty tendency to become stuck in evade mode, making them unkillable, and thus preventing the gate from being opened.

**Steps to reproduce the behavior with as much detail as possible:**

1. Go to SFK, kill Fenrus the Devourer
2. Notice how several Arugal's Voidwalkers will spawn
3. I have no idea what actually causes the voidwalkers to become stuck. It's possible that fear might cause it, I think I saw one become feared?
4. Once the voidwalker is stuck, notice how the gate refuses to open, and you can't kill the voidwalker anymore.
5. After a lot of running around we managed to make the voidwalker get unstuck, somehow, and we could kill it and progress normally. A party member said that this had happened to them before and their solution was to have everyone in the party die so the stuck voidwalker went out of combat. Presumably having everyone zone out/drop combat would work as well?

**IDs of affected creatures, items, quests or spells with a link to the relevant page:**

NPC: https://database.turtle-wow.org/?npc=4627

**Expected behavior. Describe how it should work:**
Ideally the voidwalker shouldn't get stuck at all. Failing that, Idunno, it should despawn after a short while? Have the gate open after a short while? Give the voidwalker an ability that teleports it back to a waypoint when evading?

**Comment by jameyboor** [comment]
Fixed.

**Comment by 9600bauds** [comment]
Bless you Jamey
