### ISSUE TITLE
Too low droprates of Idols in AQ40

### ISSUE THREAD

**Issue by Lunkdunk** [slowtorta/turtlewow-bug-tracker#1430]
**Please, provide a clear description what the bug is:**
All raid groups doing AQ40 have a large amount of unused tier 2.5 tokens because of too few Idols. Compared to classic the droprate is significantly lower. On Turtle the droprate for all Idols on all mobs are 0,4% while on Classic the droprate ranges from 0,5-1,9%. The mobs we kill the most is in the higher part of that interval.
**Steps to reproduce the behavior with as much detail as possible:**
Idol of Death as an example:
https://database.turtle-wow.org/?item=20876
https://classic.wowhead.com/item=20876/idol-of-death
**IDs of affected creatures, items, quests or spells with a link to the relevant page:**

NPC: https://database.turtle-wow.org/?npc=
Item: https://database.turtle-wow.org/?item=
Quest: https://database.turtle-wow.org/?quest=
Spell: https://database.turtle-wow.org/?spell=
Object: https://database.turtle-wow.org/?object=

**Expected behavior. Describe how it should work:**
Increase the droprate, ideally to 2% flat to solve the deficit.

**Comment by slowtorta** [comment]
The data isn't any different from any other Vanilla server out there, I'm sorry but we don't see a point to change it. The majority of idols come from chests, which are opened with a special key that drops from mobs. So less trash killing, less keys, less idols.

**Comment by Lunkdunk** [comment]
I'm giving you classic values with up to four times as high droprates, with samples of tens of thousands. I have no idea about other vanilla servers, they could be experiencing the same kind of deficit. I don't see how that is relevant, this bug tracker github is proof that vanilla servers are a work in progress.
Secondly, if we have a deficit because we don't kill everything, so be it. But that is irrelevant to the notion that that the mobs we do kill have a lower droprate. 
The majority of Idols we get are indeed from coffers, but it wouldnt be if the droprates were like classic. Instead of the Turtle droprate of 0,5 Idol of each type each raid we would get 1,5 Idols. Thats is a big difference, and its accumulating for each week. The average Idols of each type we get from Large Scarab Coffers are 0,75 each raid. The amount of Idols would almost double with classic droprates.
