### ISSUE TITLE
cavern of tiems quest not taggeda as dungeon qeust

### ISSUE THREAD

**Issue by geojak** [slowtorta/turtlewow-bug-tracker#1431]
**Steps to reproduce the behavior with as much detail as possible:**

1. open qeust log
2. qeuck the follwing quests listed in your leg
3. see they are not marked as dungeon qeusts in brackets

**IDs of affected creatures, items, quests or spells with a link to the relevant page:**

https://database.turtle-wow.org/?quest=40340
https://database.turtle-wow.org/?quest=40341
https://database.turtle-wow.org/?quest=80605
https://database.turtle-wow.org/?quest=40342

**Expected behavior. Describe how it should work:**

should be tagged in brackets as dungeon qeust similair as for pther quests

**Comment by Kruxis** [comment]
Greetings! THanks for the report, it will be fixed on next server restart =)

**Comment by geojak** [comment]
You're welcome
