### ISSUE TITLE
mana potions warrior 

### ISSUE THREAD

**Issue by gigachadbro** [slowtorta/turtlewow-bug-tracker#1433]
**Please, provide a clear description what the bug is:**
Hey , i dont think its bug , but it could have better message ! 
When i try drink mana potions as warrior ( i think all mana potions would say same message ) it says " you are at full rage " , and this is already wrong and message could be like this better  : "Your class cant generate mana" , or " your class ressource is rage " 

**i dont want silly comments like " are you stupid to not know this ? " , im suggesting an improvement and fix for the message shown just , i know everything personally about this game , but it would help so much the new players :)** 

**Expected behavior. Describe how it should work:**
![image](https://user-images.githubusercontent.com/46192630/169718345-e604f5f8-5ff4-4e1e-b678-fdf095ba6937.png)

**Comment by Kruxis** [comment]
Thanks for the report, will be fixed on next server restart =)
