### ISSUE TITLE
Warlock Spell Inferno (Mob: Infernal duration)

### ISSUE THREAD

**Issue by Firestoat** [slowtorta/turtlewow-bug-tracker#1434]
**Please, provide a clear description what the bug is:**
Currently on the server, if an Infernal is summoned by the Warlock spell, Inferno, it will remain spawned for a duration of 30 minutes. This is a very old Mang0s core bug plaguing private servers since 2012 at least, inclusive of Valkyrie, Feenix, Kronos, & Nostalrius WoW. It's sadly abused by players to create lethal situations in quest hubs for the lulz.

**Steps to reproduce the behavior with as much detail as possible:**
Cast the spell and then confirm the Infernal Mob will hang around for the extended duration.

**IDs of affected creatures, items, quests or spells with a link to the relevant page:**

Turtle WoW Warlock Spell Link (Inferno) -- https://database.turtle-wow.org/?spell=1122
Turtle WoW summoned Mob Link -- https://database.turtle-wow.org/?npc=89

Classic WoWHead spell link -- https://classic.wowhead.com/spell=1122/inferno
Classic WoWhead summoned Mob Link -- https://classic.wowhead.com/npc=89/infernal

Vintage Youtube Link from 2006 era retail (infernal) -- https://www.youtube.com/watch?v=zWGKVPQ2LZ8
Vintage Youtube Link from 2006 era retail (Doomguard) -- https://www.youtube.com/watch?v=SagtQmamJ9A

**Expected behavior. Describe how it should work:**
How it should work - The Inferno Spell will summon the Infernal Mob which will gain a hate list of enemy flagged mobs and players within its normal radius for detection. The mob will remain spawned for as long as the hate list contains targets. Note that healing or buffing a player or mob adds targets to the hate list as usual.

Once the hate list is empty, the mob will despawn on its own within a 10 second time frame and the hate list continues to be empty. Note that this hate list mechanic for keeping the mob spawned is identical to the mechanic used for the old 2004-2006 retail Doomguard summon, either from Ritual of Doom or Curse of Doom.

" When Enslave breaks, the only person that's on the Infernal's agro list is you. If it kills you, then its agro list is empty and it despawns. But what normally happens is that someone else hits the Infernal, or heals you, or does something else to end up on its list - which means that the Infernal won't despawn until that person is dead. "

http://wowmb.net/forums/f9/2827-infernal_doomguard_discussion/p2/

**Comment by jameyboor** [comment]
Fixed in next update.
