### ISSUE TITLE
Warlock Summoned Mob Duration (Doomguard)

### ISSUE THREAD

**Issue by Firestoat** [slowtorta/turtlewow-bug-tracker#1435]
**Please, provide a clear description what the bug is:**
This is identical to the newly posted bug for the Infernal by myself. Currently on the server, if a Doomguard is summoned it will remain spawned for a default 30 minutes. This is incorrect from old 2004-2006 retail WoW behavior, and is a very old Mang0s core bug located on the previous Valkyrie, VanillaWoW, Feenix, Kronos, and Nostalrius servers.

**Steps to reproduce the behavior with as much detail as possible:**
Summon a Doomguard with a Warlock using either the Curse of Doom or the Ritual of Doom spells.

**IDs of affected creatures, items, quests or spells with a link to the relevant page:**
TurtleWoW Spell Link (Curse of Doom) -- https://database.turtle-wow.org/?spell=603
TurtleWoW Spell Link (Ritual of Doom) -- https://database.turtle-wow.org/?spell=18540
TurtleWoW Mob Link (Doomguard) -- https://database.turtle-wow.org/?npc=11859

WoWHead Classic Spell Link (Curse of Doom) -- https://classic.wowhead.com/spell=603/curse-of-doom
WoWHead Classic Spell Link (Ritual of Doom) -- https://classic.wowhead.com/spell=18540/ritual-of-doom
WoWHead Classic Mob Link (Doomguard) -- https://classic.wowhead.com/npc=11859/doomguard

Vintage Youtube Doomguard behavior Link -- https://www.youtube.com/watch?v=SagtQmamJ9A

**Expected behavior. Describe how it should work:**
This is nearly identical to how the summoned Infernal script is supposed to work, but with one change. When a Doomguard is summoned by means of the Curse of Doom spell, it will pick up a hate list of enemy targets within its normal detection range and remain spawned as long as his hate list has something on it. The Doomguard can be kited, the same as the infernal, which can increase targets on the hate list. Once the Doomguard's hate list is empty, it despawns within 10 seconds of it remaining clear.

The Ritual of Doom means of summoning it is slightly different. The Doomguard gains the casting Warlock as its initial hate list target automatically the moment it spawns. The amount of hate the Doomguard has for the Warlock is extremely weak - a lvl 1 healing spell or a buff cast on the Warlock from another player will put the 2nd player higher on the hate list every time. It follows the exact same behavior for despawning when its hate list is clear within 10 seconds.

**Comment by jameyboor** [comment]
Fixed in next update.
