### ISSUE TITLE
database.turtle-wow issues

### ISSUE THREAD

**Issue by Haaxor1689** [slowtorta/turtlewow-bug-tracker#1438]
I'll try to summarize here all the various issues I found with https://database.turtle-wow.org/ and custom content

- [ ] Some custom NPCs don't load at all (most of them are goblins)
    Examples:
    - https://database.turtle-wow.org/?npc=80121
    - https://database.turtle-wow.org/?npc=80128
    - https://database.turtle-wow.org/?npc=80601
    - https://database.turtle-wow.org/?npc=80603
    - https://database.turtle-wow.org/?npc=80605 (only non goblin I found)
- [ ] Same for some quests
    Examples:
    - https://database.turtle-wow.org/?quest=40050
    - https://database.turtle-wow.org/?quest=40060
- [ ] Some quests are missing start and end info (many of them seem to be WANTED boards)
    Examples:
    - https://database.turtle-wow.org/?quest=80735
    - https://database.turtle-wow.org/?quest=80736
    - https://database.turtle-wow.org/?quest=70059
- [ ] Sometimes spawn locations are incorrect
    Examples:
    - https://database.turtle-wow.org/?object=3000200
- [ ] NPCs in custom zones have missing location
    Many of these are not in any subzone and "outside of map" so there is no better position to show them then world map (which does not have an image) but Gillijim isle mobs show up in world map only as well even though it's a valid subzone
    Examples:
    - https://database.turtle-wow.org/?npc=80802
    - https://database.turtle-wow.org/?npc=14734
    - https://database.turtle-wow.org/?npc=80459
    - https://database.turtle-wow.org/?npc=80231
    - https://database.turtle-wow.org/?npc=92177
- [ ] It seem like the webpage uses vanilla map assets and not the custom ones

More examples can be found [here](https://docs.google.com/spreadsheets/d/1-DYHaEq8GD8lH10GJXZxD9iNLNWjl4XA32u_Ire11NY/edit#gid=837509470)

**Comment by geojak** [comment]
Some have wrong drop chance, see cow Kings hides

**Comment by 9600bauds** [comment]
Some items are missing their corresponding recipe: https://database.turtle-wow.org/?item=83415

**Comment by burner1024** [comment]
also lists seem to be limited to 500

**Comment by slowtorta** [comment]
https://github.com/slowtorta/turtlewow-bug-tracker/issues/2818
