### ISSUE TITLE
issues with baxxil

### ISSUE THREAD

**Issue by geojak** [slowtorta/turtlewow-bug-tracker#1441]
**Please, provide a clear description what the bug is:**

![WoWScrnShot_052322_222209](https://user-images.githubusercontent.com/25199983/170218573-be38d5b8-b841-4f95-9a52-133683ebd9a2.jpg)
![WoWScrnShot_052322_222215](https://user-images.githubusercontent.com/25199983/170218587-0f7af9ee-c470-4e85-8016-f85ebfb4aba8.jpg)
![WoWScrnShot_052322_222945](https://user-images.githubusercontent.com/25199983/170218590-21cd27d5-bd75-4471-94bc-6398dadee824.jpg)
![WoWScrnShot_052322_222150](https://user-images.githubusercontent.com/25199983/170218592-d64424b0-3645-47a4-9d3f-a4f54763cb3d.jpg)
![WoWScrnShot_052322_222201](https://user-images.githubusercontent.com/25199983/170218596-fca9d92e-db26-4de1-aa01-ac3100ad1a59.jpg)

**Steps to reproduce the behavior with as much detail as possible:**

1. see in barrens at his spawnpoint are 2 baxils standing around
2. engange them in ranged combat and notice they are rooted in place where they entered combat and will not walk up to you to meele
3. hand in the quest in steemwheedle point to return the prisoner and notice baxxil follwos you around even after handing it in

**IDs of affected creatures, items, quests or spells with a link to the relevant page:**

https://database.turtle-wow.org/?quest=55048
https://database.turtle-wow.org/?npc=91297

/*Expected behavior. Describe how it should work:**

1. onlz one baxxil spawn
2. he is mobile and walks to you to meele like any other mob
3. he despawn upon handing on his qeust

**Comment by geojak** [comment]
https://forum.turtle-wow.org/viewtopic.php?f=4&t=3060&p=18849#p18849

**Comment by slowtorta** [comment]
Fixed in June, as far as I remember.
