### ISSUE TITLE
arcane arms wrong qeust categorie

### ISSUE THREAD

**Issue by geojak** [slowtorta/turtlewow-bug-tracker#1442]
**Please, provide a clear description what the bug is:**

the qeust arcane arms is a custom horde mage quest that wants you to collect stuff from wc
the quest in your questlog is in the barrens category
but it wants you to go to wc and collect stuff so it should be a wc cateogry
but wait, its a mage quest, so independant of that it should be mage category

**IDs of affected creatures, items, quests or spells with a link to the relevant page:**

https://database.turtle-wow.org/?quest=80312

**Expected behavior. Describe how it should work:**

mage category in quest log and not barrens

**Comment by slowtorta** [comment]
Fixed in the next revision.
