### ISSUE TITLE
items share cd but its not displayed

### ISSUE THREAD

**Issue by geojak** [slowtorta/turtlewow-bug-tracker#1443]
**Please, provide a clear description what the bug is:**

**Steps to reproduce the behavior with as much detail as possible:**

1. get the viking helmet from uldaman and the goblin rocket helm
2. use either on of them and you get a 60 minute cd on the used item
3. equip the other item
4. if you try to use it, it will say, "cant use that yet"but its not diplasyed as on cd.
5. apparenbtly the shared cd display is bugged
6. the exacpt same problem for parashoot cloak and the all purpose shield

**IDs of affected creatures, items, quests or spells with a link to the relevant page:**

https://database.turtle-wow.org/?item=10518
https://database.turtle-wow.org/?item=9404

https://database.turtle-wow.org/?item=9394
https://database.turtle-wow.org/?item=10588

**Expected behavior. Describe how it should work:**

item thas is on cd is displayed as on cd, shared cds displayed properly

**Comment by slowtorta** [comment]
They use the same spell, it's working as intended.
