### ISSUE TITLE
The Challenge quest, double Rezznik spawn

### ISSUE THREAD

**Issue by Rykenwolf** [slowtorta/turtlewow-bug-tracker#1445]
**Please, provide a clear description what the bug is:**
Mob 'Rezznik' spawned twice when commencing 'The Challenge' quest in BRD

**Steps to reproduce the behavior with as much detail as possible:**

1.  Player placed 'Banner of Provocation' in side BRD arena, starting quest event
2. Multiple mobs spawn as happens normally, except that two 'Rezznik' npcs spawned
3. Quest able to be completed as normal

**IDs of affected creatures, items, quests or spells with a link to the relevant page:**

NPC: https://database.turtle-wow.org/?npc=16054
Quest: https://database.turtle-wow.org/?quest=9015

**Expected behavior. Describe how it should work:**
Only one Rezzik npc should spawn. Image shows both corpses.
![image](https://user-images.githubusercontent.com/106287790/170393248-9aec698f-186d-4f81-8cb8-48b41bbddd20.png)

**Comment by Kruxis** [comment]
Thanks for the report, issue will be fixed after the next server restart, =)
