### ISSUE TITLE
Quest "Shaking a Cold Arm" dont active after complete "Short Five Minute Adventure"

### ISSUE THREAD

**Issue by el-dias** [slowtorta/turtlewow-bug-tracker#1447]
The quest "Shaking a Cold Arm" dont active after complete "Short Five Minute Adventure"

**Steps to reproduce the behavior with as much detail as possible:**

1. I completed the quest "Short Five Minute Adventure"
2. In Turtle WoW Database says that quest "Shaking a Cold Arm" should be enable.
3. But the quest dont enable for me, but in PfQuest-Turtle shows to 

NPC: https://database.turtle-wow.org/?npc=80178 (NPC in Turtle WoW Database)
NPC: https://database.turtle-wow.org/?npc=91275 (NPC in PFQuest Turtle)
Quest: https://database.turtle-wow.org/?quest=55013

The quest should be enable

**Comment by Kruxis** [comment]
Thanks for the report! Will be fixed on next restart =)
