### ISSUE TITLE
Alah'Thalas Flightpath Buggy

### ISSUE THREAD

**Issue by Lexiebean** [slowtorta/turtlewow-bug-tracker#1449]
I took a connecting flight from Alah'Thalas to Chillwind Camp, WPL. Then later took a flight from WPL to Searing Gorge. (I then went AFK to make food...) When I came back I was flying through the world, underwater and sometimes sideways until I reached Alah'Thalas. Then finally landing in Light's Hope in EPL.

I'm assuming that I made it to Searing Gorge the first time then turned around.

**Comment by slowtorta** [comment]
This will be fixed in the upcoming client update :)

**Comment by Tinyfin-github** [comment]
Issue persists

**Comment by slowtorta** [comment]
https://github.com/slowtorta/turtlewow-bug-tracker/issues/2047
