### ISSUE TITLE
Goblins (can't access 'Children's Week' quest)

### ISSUE THREAD

**Issue by Vikkyne** [slowtorta/turtlewow-bug-tracker#145]
**Please, provide a clear description what the bug is:**

**Steps to reproduce the behavior with as much detail as possible:**

**1. lvl 17 goblin - has *not* done the event; fresh quest marker is not showing**

**IDs of affected creatures, items, quests or spells with a link to the relevant page:**

***** PLEASE NOTE: Classic WoW IDs used below; _the Turtle WoW Database goes to the wrong quest for Horde Children's Week (it goes to 'Ambushed in the Forest' - which ALSO has the Quest ID of 172 --- and therein, I think, lies the problem)_**

**NPC: https://database.turtle-wow.org/?npc=14451 (classic wow)
Quest: https://database.turtle-wow.org/?quest=172 (classic wow)**

**Expected behavior. Describe how it should work:**
**--- Goblins should be able to pick up quest (please note: High Elves *can* get their version)**

**Comment by slowtorta** [comment]
Thanks for reporting it. It'll be fixed on the next server restart. Make sure to clear your WDB folder.
