### ISSUE TITLE
Ol' Sooty should be patrolling

### ISSUE THREAD

**Issue by Tinyfin-github** [slowtorta/turtlewow-bug-tracker#1451]
Ol' Sooty should be patrolling from his cave at the top of the nearby hill and down to the foothills of it

Turtle: https://database.turtle-wow.org/?npc=1225
Classic: https://classic.wowhead.com/npc=1225/ol-sooty

https://www.youtube.com/watch?v=K98yj8NkubI

**Comment by slowtorta** [comment]
Fixed in the next revision.
