### ISSUE TITLE
Trash respawns and respawns too quick in Karazhan Crypt

### ISSUE THREAD

**Issue by atazs** [slowtorta/turtlewow-bug-tracker#1453]
**Please, provide a clear description what the bug is:**
Elite trash mobs (Tomb bats and Skeletal Remains) in Karazhan Crypts respawn, and respawn too quick.

**Steps to reproduce the behavior with as much detail as possible:**

1. Enter Karazhan Crypts
2. Start clearing the trash
3. After 30 minutes or less, some mobs will have respawned 

**IDs of affected creatures, items, quests or spells with a link to the relevant page:**

NPC: https://database.turtle-wow.org/?npc=91921
NPC: https://database.turtle-wow.org/?npc=91924

**Expected behavior. Describe how it should work:**
Mobs should stay dead.

**Comment by atazs** [comment]
This is really really bad because you have to drop down into a hole in the first room, and you take massive amounts of fall damage that almost kills you. If your group is still down there, you will have absolutely no chance to make the drop or clear the mobs on your own, and your team has no way of coming up to help you unless they too die themselves.

**Comment by Kruxis** [comment]
Greetings! Thanks for the report, will be fixed on next server restart =)
