### ISSUE TITLE
Bugs in the Quest: "The Stones That Bind Us" 

### ISSUE THREAD

**Issue by atazs** [slowtorta/turtlewow-bug-tracker#1454]
**Please, provide a clear description what the bug is:**

The stones of Bindings are already interactable from the start, without engaging the mobs. The mobs themselves WILL NOT become stunned at 10% HP, meaning that you cannot destroy the Stone of Bindings, (you will get interrupted as you attack them) nor kill the mobs as they are invincible otherwise, unless you can stun them or have someone tanking them while you destroy the stone. 

**Steps to reproduce the behavior with as much detail as possible:**

1. Engage one of the servants in the Blasted Lands
2. DPS them down then try to destroy the stone of binding 
3. Fail

**IDs of affected creatures, items, quests or spells with a link to the relevant page:**

NPC: https://database.turtle-wow.org/?npc=7668
NPC: https://database.turtle-wow.org/?npc=7669
NPC: https://database.turtle-wow.org/?npc=7670
NPC: https://database.turtle-wow.org/?npc=7671
Item: https://database.turtle-wow.org/?object=141858
Quest: https://database.turtle-wow.org/?quest=2681

**Expected behavior. Describe how it should work:**
"To finish this quest, you must first locate the [Stone of Binding](https://classic.wowhead.com/object=141812/stone-of-binding), which will be nearby any servant, but will not be interactable right away, which means that **there will be neither mouseover prompt nor highlighting**. After the stone located, you must attack a servant while keeping them around the stone, but you won't be able to kill it yourself: **their health will stop draining after around 10% and they will be stunned for about 30 seconds.** **At this moment Stone of Binding will become interactable**"

**Comment by Khanz0** [comment]
I did it slowing his movemen. When are at 1% they  move slower. Plus a hamstring/wingclip/slow... Make them really really slow. Just move them a little far away from stone and click it before he reach you

**Comment by redmagejoe** [comment]
This NPC behavior / script needs to be addressed.
