### ISSUE TITLE
[Quest] The Warsong Lumber Camp/Ashenvale demon-hunting quest chain is not properly defined as a chain, but rather many individual quests

### ISSUE THREAD

**Issue by 9600bauds** [slowtorta/turtlewow-bug-tracker#1455]
**Please, provide a clear description what the bug is:**
The long quest chain that starts with https://database.turtle-wow.org/?quest=70020
has a small issue in that the 12+ quests involved are not marked as a chain, they are simply standalone quests that mark the previous quest as required.
This is actually different and causes two minor problems:
A) The database doesn't show all the quests in the chain, making it hard to navigate (a normal quest chain has a display [like this](https://i.imgur.com/cXPaqEt.png) in the DB)
B) When you turn in a quest, you are not automatically offered the next quest in the chain, you have to talk to the NPC again
These are admittedly minor problems but it's worth mentioning for future reference if nothing else.

**Steps to reproduce the behavior with as much detail as possible:**

1. Go to https://database.turtle-wow.org/?quest=70020
2. Try to use the DB to check what the quest reward at the end of the chain is
3. Cry
4. Do the quest in-game
5. Notice that you have to talk to the NPC after each step, unlike a regular quest chain that automatically presents you with the next step

**IDs of affected creatures, items, quests or spells with a link to the relevant page:**

https://database.turtle-wow.org/?quest=70020

**Expected behavior. Describe how it should work:**
It should be a quest chain, with a display [like this](https://i.imgur.com/cXPaqEt.png) in the DB and with the NPCs automatically offering the next step of the chain

**Comment by Kruxis** [comment]
Greetings! Thanks for the report, should be (hopefully) fixed on next server restart =)
