### ISSUE TITLE
Somthing is rong  Survival..

### ISSUE THREAD

**Issue by Drwarlocke** [slowtorta/turtlewow-bug-tracker#1456]
**Please, provide a clear description what the bug is:**
Hi...
To day  i login and open the Spellbook to continue with Survival skill but now is it empty can lvl up the skill..
im at 75/150..

**Steps to reproduce the behavior with as much detail as possible:**

1.
2. 
3. 

**IDs of affected creatures, items, quests or spells with a link to the relevant page:**

NPC: https://database.turtle-wow.org/?npc=
Item: https://database.turtle-wow.org/?item=
Quest: https://database.turtle-wow.org/?quest=
Spell: https://database.turtle-wow.org/?spell=
Object: https://database.turtle-wow.org/?object=

**Expected behavior. Describe how it should work:**

**Comment by Tinyfin-github** [comment]
Greetings!

Please switch between two profession windows to momentary fix this bug.

Issue has been moved to our internal tracker and it's being worked on for a  permanent fix.
