### ISSUE TITLE
Rank meter broke

### ISSUE THREAD

**Issue by Tinyfin-github** [slowtorta/turtlewow-bug-tracker#1457]
Rank meter broke

![image](https://user-images.githubusercontent.com/83077166/170853979-9ee9e678-e961-49ea-9c09-5510efbc6c5c.png)

**Comment by Tinyfin-github** [comment]
Issue persists and is present only to some players.

**Comment by slowtorta** [comment]
Duplicate for https://github.com/slowtorta/turtlewow-bug-tracker/issues/1506
