### ISSUE TITLE
Guild has unknown members that can't be removed

### ISSUE THREAD

**Issue by Tinyfin-github** [slowtorta/turtlewow-bug-tracker#1458]
Guild has unknown members that can't be removed

![image](https://user-images.githubusercontent.com/83077166/170854101-7e1909b8-a2bf-4c66-8f74-f745d8da48c3.png)

**Comment by slowtorta** [comment]
Possibly fixed in the next revision, re-open if not.

**Comment by shagu** [comment]
The HC Guild today had players with names, and a guild-info that contained always changing garbage:

![image](https://user-images.githubusercontent.com/11586807/173201520-7d79f57e-817e-4d98-886b-ebd708ba0b1a.png)
![image](https://user-images.githubusercontent.com/11586807/173201526-a0d1c635-738f-4dbc-9e5a-5225fcf6f82d.png)

The garbage in the Guild-Note is changing from "1C" to "fC" to "^C" to "mC" and to others every few seconds.

**Comment by geojak** [comment]
This issue might be the root for my mail game crashes since the name clear up.

Mail addon uses an autocompelte feature. When I type any letter on my main in the golden moon guild, the game crashes (memory violation) . I assume because the auto complete tries to access names from bugged players.

I don't have the issue on chars in beginner guild

**Comment by geojak** [comment]
![image](https://user-images.githubusercontent.com/25199983/173232415-e4394ab0-400c-4d4d-93c1-eb0575951b02.png)

**Comment by geojak** [comment]
interstingly they are all lvl 26 warlocks
![image](https://user-images.githubusercontent.com/25199983/173232745-e7c74032-f2b3-468e-ba14-6b975f6b9000.png)

**Comment by shagu** [comment]
Leaving here what I already wrote on discord:
> **Regarding the recent crashes today:**
To my investigations, the crashes are (again, as in december last year) related to a broken GetGuildRosterInfo(i) call, which addons use to obtain guild informations. 
This API call sometimes receives garbage while in the <Still Alive> guild, and and depending on what is received, it can crash the client.

> As you can see on this issue, there are changing "random" characters in the guild-note on weirdly random named players.

> My assumption is: If those characters become a horizontal tab (ascii-9) - which is used in the client as content-separator - the client receives more fields than it is expecting and therefore writes the additional one into memory where it shouldn't be allowed to write -> Critical Error.

> Meanwhile this issue is not fixed server side, a recent version of pfUI with all guild-features disabled is attached to the pinned message of the #hc-lounge channel.
For every other addon that is using those API calls, identify and disable those, leave guild, or just hope for good luck.

**Comment by slowtorta** [comment]
Fixed for real now. The public guilds will now display only online members in the roster and the large players guilds will adjust their roster and note sizes to not cause an overflow. Some of the offline members won't be displayed but it is what it is.
