### ISSUE TITLE
Neutral NPC not clickable , only hostile

### ISSUE THREAD

**Issue by Leodimas** [slowtorta/turtlewow-bug-tracker#1459]
**Steps to reproduce the behavior with as much detail as possible:**

1. Go to Un Goro Crater 
2. Click the NPC : Muigin
3. NPC is marked green but can only be attacked
            NPC:https://database.turtle-wow.org/?npc=9119

**Expected behavior. Describe how it should work:**

Npc should be friend and be able to talk. NPC is quest giver for  https://database.turtle-wow.org/?quest=4141

![image](https://user-images.githubusercontent.com/12403564/170862185-828a418e-379f-48e3-b537-35353f581429.png)

**Comment by Kruxis** [comment]
Greetings! I am standing next to him as alliance right now. He is indeed friendly and not attackable. Please try deactivating all Addons and retry =)
