### ISSUE TITLE
[Paladin] Paladin Talent, Two-Handed Weapon Specalization does not seem to work

### ISSUE THREAD

**Issue by ReggyDawn** [slowtorta/turtlewow-bug-tracker#1460]
The 5th row retribution talent that grants a 6% increase to the damage of two-handed weapon does not appear to display correctly on the character sheet.

Testing it, it appears to display correctly immediately after speccing into it, showing a green number and a 106% multiplier, but after logging out, it resets back to 100% and a lower weapon damage. For fairness, I have not tested it on a dummy, to confirm if the bug is just visual, or also mechanical, and I'm sorry for that. I hope drawing attention to it will have someone look into it, however. Thank you!

**Comment by Velite12** [comment]
![image](https://user-images.githubusercontent.com/45871932/192048245-0fcb93e3-d25a-439a-957f-3d0cd627c408.png)
![image](https://user-images.githubusercontent.com/45871932/192048305-154734f6-17f5-4d7c-a64f-3f78c5bfcdff.png)
As you can see the number value changed.

![image](https://user-images.githubusercontent.com/45871932/192048454-ef840e2a-820a-4422-b2e0-8dbfdd888c2a.png)
Logged out and the value remains. However I am not seeing a multiplier amount.
![image](https://user-images.githubusercontent.com/45871932/192048569-4224037c-c4f8-4d6e-9a49-e4a594e8b847.png)
I only see it when vengeance applies. The 2h Talent is a background multiplier not an active one. That's probably where you were confused.

![image](https://user-images.githubusercontent.com/45871932/192048932-61ec3a23-0bb9-4cd1-afd3-3ed361b303d4.png)
I checked on classic as well and it does the same. Marking this as closed.
