### ISSUE TITLE
Plainsrunning breaks when using Track Minerals/Track Herbs etc.

### ISSUE THREAD

**Issue by 9600bauds** [slowtorta/turtlewow-bug-tracker#1462]
**Please, provide a clear description what the bug is:**
The Tauren racial ability Plainsrunning breaks when casting a spell, which balances the fact that you normally can't cast spells on mounts.
However, Track Minerals/Track Herbs etc. is the one exception of spells that you can cast while mounted. Plainsrunning does not have this exception, making it unnecessarily annoying to use.

**Steps to reproduce the behavior with as much detail as possible:**

1. Be Tauren
2. Use Plainsrunning
3. Use Track Minerals/Track Herbs etc.

**IDs of affected creatures, items, quests or spells with a link to the relevant page:**

Spell: https://database.turtle-wow.org/?spell=12566

**Expected behavior. Describe how it should work:**
It should mimic mounts and allow you to switch tracking types without booting you.

**Comment by 9600bauds** [comment]
Also happens with warriors switching stances which is the other exception I can think of

**Comment by LeopoldHock** [comment]
Plainsrunning works a bit different than mounts in quite a lot of ways (e.g. also dazing/cancellation). This sounds more like a suggestion than a bug. :)
