### ISSUE TITLE
Geodata issue at Ranazjar Isle

### ISSUE THREAD

**Issue by Gasan918** [slowtorta/turtlewow-bug-tracker#1463]
**Please, provide a clear description what the bug is:**

Slitherblade Sea Witch falled through textures near 29.3, 11.0

![image](https://user-images.githubusercontent.com/96973359/171236115-e2ee9935-a176-414a-8589-3d61100ed4d6.png)

**Comment by slowtorta** [comment]
Couldn't confirm it, working as intended, I'm sorry. Sometimes glitches like this happen, but we cannot fix it for a single creature.
