### ISSUE TITLE
Learning from a trainer how to craft Steel Plate gear is not instant, is a castable spell, and interrupting it eats your money

### ISSUE THREAD

**Issue by 9600bauds** [slowtorta/turtlewow-bug-tracker#1464]
**Please, provide a clear description what the bug is:**
Normally when you learn a tradeskill recipe from a trainer, you learn it instantly.
For whatever reason, the turtle-exclusive Steel Plate recipes are not learned instantly, learning them has a cast timer.
If you interrupt this cast, you lose your money but don't learn how to craft the item.

**Steps to reproduce the behavior with as much detail as possible:**

1. Get 220 blacksmithing
2. Go to Saru Steelfury, Artisan Blacksmith
3. Pay to learn Steel Plate Gauntlets/boots/etc
4. Notice how a castbar starts
5. Cancel it by moving
6. Notice how you lost money for the training cost but you haven't learned anything and must pay to do it again and not move this time

**IDs of affected creatures, items, quests or spells with a link to the relevant page:**
Example of 1 item that this happens with:
Item: https://database.turtle-wow.org/?item=83410
(the corresponding recipe seems to not exist in the DB)

**Expected behavior. Describe how it should work:**
The learning process should be instant, so you can't screw it up

**Comment by slowtorta** [comment]
Fixed in the next revision.
