### ISSUE TITLE
[Breaking the Felstar] quest text is misleading

### ISSUE THREAD

**Issue by Zulmamwe** [slowtorta/turtlewow-bug-tracker#1467]
**Please, provide a clear description what the bug is:**
Quest text of [[Breaking the Felstar]](https://database.turtle-wow.org/?quest=40377) states that you need to (quoting quest text) "meet my rangers near the border of Felwood, north of Raynewood's Retreat. Help them stop this attack and make sure to take proof of your victory to the Ashylah Starcaller in Darnassus."
If fact there are no archers at all (been looking for them for 10+ minutes until just asked in chat and received a response that this quest text is incorrect) and all you need to do is use (object)[Corrupted Felstone](https://database.turtle-wow.org/?object=2010883) to summon couple of defenders and after you kill them elite satyr [Dra'lox Felstar](https://database.turtle-wow.org/?npc=60425) appears that drops [[Dra'lox's Horn]](https://database.turtle-wow.org/?item=60148) required for this quest. But still archers doesn't appear and nobody is helping you, leaving you 1 on 1 vs elite impossible to solo kill on that level (quest doesnt say that its elite or group)

**Steps to reproduce the behavior with as much detail as possible:**

1. Accept quest [Breaking the Felstar]
2. Go to Raynewood Retreat in Ashenvale
3. Search for rangers that you are supposed to meet (to probably talk to them and start the event to deflect satyrs attack with their help, that was my idea of what's gonna happen after i read the quest)
4. Find none of the rangers
5. Be confused, ask chat for help (optional)

**IDs of affected creatures, items, quests or spells with a link to the relevant page:**

Quest: https://database.turtle-wow.org/?quest=40377

Object: https://database.turtle-wow.org/?object=2010883
NPC: https://database.turtle-wow.org/?npc=60425
Item: https://database.turtle-wow.org/?item=60148

**Expected behavior. Describe how it should work:**
Quest text shouldn't say anything about meeting archers, it should be something like:
"We found very important felstone on the border of Ashenvale and Felwood but it was corrupted by satyr named Dra'lox Felstar. We believe that the source of his corrupting power is in his horns. Bring them to druids in Darnassus so they can research it and maybe find a way to reverse the corruption. He is a demon elite and won't go out that easily. Try to meddle with corrupted felsone to attract demon defenders assigned to it and after you will be done with them Dra'lox Felstar will definitely show himself."
P.S. i wrote that before checking out what next quest says so edit it accordingly to not disrupt or rewrite whole quest line

**Comment by geojak** [comment]
I agree with op. Was also searching for the rangers for quite a while.
When I did it, after I killed the satyrs or at the end, the rangers actually spawned somewhere far away to the mountain. Not rly helpful or in any way involved in the quest
