### ISSUE TITLE
Trained Razorbeaks in Hinterlands have 20000 armor points too many

### ISSUE THREAD

**Issue by 9600bauds** [slowtorta/turtlewow-bug-tracker#1468]
**Please, provide a clear description what the bug is:**
If you install an addon to see armor values, and you check the beasts of The Hinterlands, you will see that they're usually around the ~2200 range:
![WoW_22-06-01-18-04-48](https://user-images.githubusercontent.com/6526157/171503338-c717a182-9fd2-4533-84a5-4c4d45bfa1fc.png)
However, Trained Razorbeaks have 22456 armor instead:
![WoW_22-06-01-18-05-32](https://user-images.githubusercontent.com/6526157/171503588-1bf4f336-4db4-4440-91ac-578e7faeeff6.png)
This is not a visual bug, they really do have 4 times more armor than a raidboss and they hit the armor hard cap. This is very noticeable as a melee class because your attacks suddenly hit like you left your fishing pole on.

**Steps to reproduce the behavior with as much detail as possible:**

1. Go to West Hinterlands close to the ally hub
2. Whack a normal mob, notice how you do 174 damage pet whitehit
3. Whack a Trained Razorbeak, notice how you do 76 damage per whitehit

**IDs of affected creatures, items, quests or spells with a link to the relevant page:**

NPC: https://database.turtle-wow.org/?npc=2657

**Expected behavior. Describe how it should work:**
It should probably have 2456 armor.

**Comment by 9600bauds** [comment]
![WoW_22-06-01-18-04-16](https://user-images.githubusercontent.com/6526157/171504872-d5101ba9-3f26-4440-ad02-4bc73923d5c9.png)
Related: The custom Hinterlands Eagles nearby also have custom armor values which are unnaturally high, about 40% too high.

**Comment by slowtorta** [comment]
I couldn't find any information, but this report sounds reasonable. Maybe someone will present any proof that those mobs should actually have such a high armor value.
