### ISSUE TITLE
Orgrimmar -> Kargath Zeppelin kills people via fall damage

### ISSUE THREAD

**Issue by 9600bauds** [slowtorta/turtlewow-bug-tracker#1469]
**Please, provide a clear description what the bug is:**
This is a pretty common problem but I couldn't find an open issue about it.
When you take the zeppelin from Orgrimmar to Kargath, you have a very good chance of instantly dying from fall damage.
In fact, the zeppelin is rather infamous for this. If you go to Kargath you will almost certainly see floating corpses and skeletons.

Worldchat has said the following about this bug:
- It does not happen when going from Kargath to Orgrimmar, only from Orgrimmar to Kargath.
- Apparently, if your loading screens are *very* fast, you don't die from it. This might depend on your connection to the server, your PC, or both.
- If it happens to you, it will happen to you pretty much 100% of the time. If it doesn't happen to you, it will probably never happen to you. Further crediting the idea that it depends on your connection to the server, your PC, or both.
- One guy said the devs tried to fix it by adding a grace period where you are immune to fall damage after teleporting from a zep, but the fall damage is "stored" until after your game finishes loading, so you die if your loading screen is longer than the grace period.
- One guy said alttabbing during the loading screen makes him fall through boats, further crediting the idea that strange things during loading screens is the cause for these problems.

**Steps to reproduce the behavior with as much detail as possible:**

1. Take the zeppelin from Orgrimmar to Kargath.
2. ???
3. death

**Expected behavior. Describe how it should work:**
![no problem](https://user-images.githubusercontent.com/6526157/171545202-a1993d2a-344b-41f1-b303-198ae4441c30.jpg)

**Comment by slowtorta** [comment]
Thank you.
