### ISSUE TITLE
Baron Rivendare /Strath UD broken.

### ISSUE THREAD

**Issue by Zangatsu** [slowtorta/turtlewow-bug-tracker#147]
Hello, this is Zangatsu from Turtle WoW. On 7/8/2021 at about 3:30 am Central time, our Baron Rivendare, last boss of Stratholme, was extremely bugged. Even though we killed all of his Mindless Servants, his Death Pact ability healed him to full every time. We had a group of 7 players and three times in a row this bug happened. When you kill all of the skeletons, he is not supposed to receive a heal.

**Comment by CosminPOP** [comment]
Seems to be working right now. Closing.
