### ISSUE TITLE
Balos Jacken in Dustwallow Marsh won't reset and will keep chasing you if aggro'd

### ISSUE THREAD

**Issue by lokhengchau** [slowtorta/turtlewow-bug-tracker#1472]
**Please, provide a clear description what the bug is:**

It's a very minor, small bug but I found it amsuing. Balos Jacken, the hostile quest NPC for the quest The Deserters, wouldn't give up and would just keep chasing you if aggro'd. I actually ran all the way to Barrens and he still kept chasing. He only gave up and despawned after I cast fear.

**Steps to reproduce the behavior with as much detail as possible:**

1. Have the quest The Deserters where you have to talk to Balos Jacken.
2. Attack him, bring down his HP and make him friendly. Finish this part of the quest.
3. Wait for him to reset and turn hostile. Aggro him and he'd chase you to the end of the world.

**IDs of affected creatures, items, quests or spells with a link to the relevant page:**

NPC: https://database.turtle-wow.org/?npc=5089
Quest: https://database.turtle-wow.org/?quest=1286

**Expected behavior. Describe how it should work:**

Enemy should stop chasing and reset. Or maybe this guy is just special.

**Comment by redmagejoe** [comment]
Cannot reproduce on current version. Balos properly resets combat at maximum leash distance.

Fixed.
