### ISSUE TITLE
[Looking For Turtles] The LFT addon suggested level range for SM:Lib is very off

### ISSUE THREAD

**Issue by 9600bauds** [slowtorta/turtlewow-bug-tracker#1473]
**Please, provide a clear description what the bug is:**
Apologies if this is not the right place for this report.
The Looking For Turtles addon says that you can do SM:Library at levels 28 to 39, and even shows it as green around level 32ish.
However, the actual mobs inside are level 32-35ish, with the final boss being 37. In fact, you can't even equip any of the gear you get from the final boss until level 33-34.
This is an unfortunately common problem, where LFT-made groups for Library very often end up being made of players who are woefully underleveled for the content, and tanks that can't even touch the final boss due to miss+dodge chance.
The level ranges in the LFT tool aren't very accurate in general, but this one is easily the most misleading one of all.

**Expected behavior. Describe how it should work:**
The level range should probably start at 32-ish. Maybe 32-43?

**Comment by slowtorta** [comment]
Moving this one to the internal tracker, thank you.
