### ISSUE TITLE
[Warrior] You can't use Overpower on mobs that dodge your Whirlwind, unless they were your current target at the time of the dodge

### ISSUE THREAD

**Issue by 9600bauds** [slowtorta/turtlewow-bug-tracker#1475]
**Please, provide a clear description what the bug is:**
Weird bug so please bear with me.
Imagine you're a Warrior fighting 2 mobs, mob A (your current target) and mob B (a mob that you are not targeting).
If mob B dodges an attack from any ability except Whirlwind, you will be able to switch targets and Overpower B as expected. This works for Cleave and Sweeping Strikes for sure.
However, Whirlwind is broken and somehow doesn't allow you to Overpower mob B if it dodges your Whirlwind hit. If mob A dodges your Whirlwind hit, you can still Overpower it as expected. This only happens for mobs that dodge Whirlwind while not being your current target.
Here's a couple of combat logs I could get, but they're not very useful because they don't show you who I was targeting.
![WoW_22-06-03-22-05-56](https://user-images.githubusercontent.com/6526157/171972097-462a8442-b17f-4791-a20b-e3a9aa32c8f3.png)
![WoW_22-06-03-22-23-28](https://user-images.githubusercontent.com/6526157/171972098-4a354bde-c99b-4f59-bc93-60f2f5a7308d.png)

**Steps to reproduce the behavior with as much detail as possible:**

1. Be a Warrior with Whirlwind
2. Fight 2 mobs at the same time
3. Use Whirlwind until a mob dodges the Whirlwind hit
4. Try to use Overpower on the mob that dodged, notice how this will only work if you were targeting the mob at that time

**IDs of affected creatures, items, quests or spells with a link to the relevant page:**

https://database.turtle-wow.org/?spell=1680
https://database.turtle-wow.org/?spell=9633

**Expected behavior. Describe how it should work:**
Whirlwind dodges should allow for Overpower to be cast, just like other multi-hit abilities, regardless of which mob the Warrior was targeting at the time

**Comment by 9600bauds** [comment]
After more testing I can't always replicate this. It seems to work sometimes, sometimes not. I think it only happens when Sweeping Strikes is up. I'll try to gather more evidence for this bug.

**Comment by redmagejoe** [comment]
Can confirm this still happens on current version. While spells such as Cleave or any attacks from Sweeping Strikes will allow you to target the Dodging enemy and use Overpower, Whirlwind Dodges will simply not highlight (or "activate") Overpower.

**Comment by Zeyla-TW** [comment]
Believe it or not, the main difference of whirlwind is that it's considered an AoE spell that deals weapon damage, except it's specifically hardcapped to 4 targets. This may sound obvious at first, but the other abilities such as cleave and sweeping strikes use different spell effects on a fundamental level that generate "targeted attacks". Even though whirlwind can be dodged, the system never registers a specific target or targets for the spell, and thus overpower is unable to register a target for itself. This cannot be fixed without fundamentally changing how whirlwind functions.

**Comment by 9600bauds** [comment]
I'm fairly sure it didn't work like that in Classic, but I don't have any evidence for that at the moment.
