### ISSUE TITLE
Captured Sprite Darters don't care about the fact that they are caged, will destroy you if approached

### ISSUE THREAD

**Issue by 9600bauds** [slowtorta/turtlewow-bug-tracker#1476]
**Please, provide a clear description what the bug is:**
![Desktop 2022 06 04 - 01 33 14 02 DVR mp4_snapshot_00 19 399](https://user-images.githubusercontent.com/6526157/171983176-00464874-6b02-4083-ae68-6068ad8d2f32.jpg)
![Desktop 2022 06 04 - 01 33 14 02 DVR mp4_snapshot_00 20 985](https://user-images.githubusercontent.com/6526157/171983177-d73fb9e9-a68a-43bf-8039-40cc50fcbd4e.jpg)
![Desktop 2022 06 04 - 01 33 14 02 DVR mp4_snapshot_00 24 365](https://user-images.githubusercontent.com/6526157/171983179-c82ee7bd-0827-4965-ad6d-0f29226cdeff.jpg)
![WoW_22-06-04-01-40-33](https://user-images.githubusercontent.com/6526157/171983324-96d2690f-d9a7-402f-8fd9-54096838f8ea.png)

Captured Sprite Darters are a bunch of sprite darters in a cage. Since they are caged, they are supposed to be passive and unattackable until you can get the key to their cage and release them.
However, they are bugged and aggro onto closeby players like a regular hostile mob, after which they happily phase through the cage to gang on the unwitting player.

**Steps to reproduce the behavior with as much detail as possible:**

1. Go to 66,47 in Feralas
2. Approach Captured Sprite Darter cage
3. Notice how the Captured Sprite Darter aggros you through the cage, instead of being passive as intended

**IDs of affected creatures, items, quests or spells with a link to the relevant page:**

NPC: https://database.turtle-wow.org/?npc=7997

**Expected behavior. Describe how it should work:**
It should be impossible to aggro or even attack the sprite darters until the cage is opened

**Comment by 9600bauds** [comment]
https://user-images.githubusercontent.com/6526157/172510024-7f36181c-50cb-4ef7-b603-c23564b3964e.mp4


After testing, it appears that it's only the door that they aggro you through the closed door.
They also respawn extremely fast, which probably makes this cage an extremely broken leveling spot for mages or the right party setup.

**Comment by redmagejoe** [comment]
These NPCs are now passive to Horde players as well, so this should no longer be an issue.

Fixed.
