### ISSUE TITLE
Druid - Ferocious Bite consuming energy and clearcasting proc

### ISSUE THREAD

**Issue by Leodimas** [slowtorta/turtlewow-bug-tracker#1477]
**Please, provide a clear description what the bug is:**

**Steps to reproduce the behavior with as much detail as possible:**
video example :https://www.youtube.com/watch?v=2_5elgjedNQ -----> skip to 2nd mob at 0:40 

1. Wait for Clearcasting proc f
2. use Ferocious Bite
3. Ferocious Bite will consume energy and clearcast proc

**IDs of affected creatures, items, quests or spells with a link to the relevant page:**

Spell: https://database.turtle-wow.org/?spell=31018

**Expected behavior. Describe how it should work:**

Should not consume energy.

**Comment by slowtorta** [comment]
Working as intended, please read: https://us.forums.blizzard.com/en/wow/t/clearcasting-ferocious-bite-broken/990313
