### ISSUE TITLE
Transmog Issue

### ISSUE THREAD

**Issue by Lexiebean** [slowtorta/turtlewow-bug-tracker#1479]
If a One-Hand hand item added to your collection, it cannot be used for a Main-Hand transmog.

**The bug**:
However if at a later point you find a Main-Hand item that shares the same item model, it still wont be added to your collection for Main-Hand because that model is already saved to One-Hand.

**Expected**:

One-Hand weapons should be usable interchangeable for Main-Hand and Off-Hand transmog.

OR

Weapon Models should be obtainable for more than one weapon type.

**Comment by Zebouski** [comment]
this was fixed with 1.16.1, if i'm understanding the question correctly
