### ISSUE TITLE
Various "Race Against Time!" bugs

### ISSUE THREAD

**Issue by Lunkdunk** [slowtorta/turtlewow-bug-tracker#148]
**Please, provide a clear description what the bug is:**
1. If the first speedboost doesnt appear it is impossible to finish the race in time. This depends on what I assume is another bug - 
at the start before you get the first speedboost, your car goes much slower than regular.
2. If you type .dismount you will become invisible and sheeps wont affect you.
3. At the finish you can be teleported around 15 yds away and stunned so it makes it hard to complete the quest even if you finished it in time.
**Steps to reproduce the behavior with as much detail as possible:**
Bug 1 and 3 doesnt happen all the time but you should be able to reproduce all of this if you try it for 20 min.
**IDs of affected creatures, items, quests or spells with a link to the relevant page:**

NPC: https://database.turtle-wow.org/?npc=
Item: https://database.turtle-wow.org/?item=
Quest: https://database.turtle-wow.org/?quest=50316
Spell: https://database.turtle-wow.org/?spell=
Object: https://database.turtle-wow.org/?object=

**Expected behavior. Describe how it should work:**
Bugs are self-explanatory.

**Comment by slowtorta** [comment]
Thanks for reporting it. It'll be fixed on the next server restart.
