### ISSUE TITLE
Attacking swoop in mulgore causes PvP flag

### ISSUE THREAD

**Issue by BowtiesAreCool** [slowtorta/turtlewow-bug-tracker#1481]
Attacking the swoop that hangs around the road between Darkmoon Faire and Bloodhoof Village causes players to be flagged for PvP.

Steps to reproduce:

1. Find the level 7-9 swoop near the road between DMF and Bloodhoof village.
2. Attack the swoop.
3. Note that character has gained a PvP flag.

Affected creature: Level 7-9 Swoop in Mulgore. https://database.turtle-wow.org/?npc=2970

Expected behavior: Attacking this creature should not result in a PvP flag.

**Comment by BowtiesAreCool** [comment]
Having now run all over Mulgore, I can say it seems to be just the one Swoop near the Thunderhorn Water Well. Other Swoops in the zone are not affected.

**Comment by slowtorta** [comment]
I'm sorry but it's probably something else that flagged you. I tried fighting many of those and it didn't trigger PvP mode.
