### ISSUE TITLE
Watchmaster Sorigal appears friendly (green plate) but right clicking will start attack

### ISSUE THREAD

**Issue by lokhengchau** [slowtorta/turtlewow-bug-tracker#1482]
**Please, provide a clear description what the bug is:**

Watchmaster Sorigal at Darkshire appears friendly (green plate) but right clicking on him will attack. Cannot return and complete quest Vital Supplies.

![image](https://user-images.githubusercontent.com/37974241/172062505-acaf365b-c6fe-4e12-bebb-923dca8dd778.png)

**Steps to reproduce the behavior with as much detail as possible:**

1. Reach level 41 (I remember he wasn't bugged when I was lower level)
2. Pick up quest Vital Supplies.
3. Talk to Watchmaster Sorigal and instead will attack.

**IDs of affected creatures, items, quests or spells with a link to the relevant page:**

NPC: https://database.turtle-wow.org/?npc=5464
Quest: https://database.turtle-wow.org/?quest=1477

**Expected behavior. Describe how it should work:**

Should not attack. Complete quest and start the next one.

**Comment by Tinyfin-github** [comment]
Greetings!

Please go to your reputation tab and uncheck at war with factions under <Others>
