### ISSUE TITLE
Hitah'ya the Keeper (Hinterlands elite troll) kicks players from crossfaction parties when attacked

### ISSUE THREAD

**Issue by 9600bauds** [slowtorta/turtlewow-bug-tracker#1483]
**Please, provide a clear description what the bug is:**
![WoW_22-06-05-21-49-18](https://user-images.githubusercontent.com/6526157/172086831-a60f08cb-3eb2-4d54-8bb1-c5199565f048.jpg)
You know that thing where if you have a crossfaction group and you attack an enemy player, you get kicked from the group?
Hitah'ya the Keeper, the "final boss" of the Hinterlands Elite Troll City Quest Thing, does that too.
None of the other Hinterlands Elite Troll City Quest Thing monsters do that, only this one.

**Steps to reproduce the behavior with as much detail as possible:**

1. Make crossfaction group (with a couple of warmode players if it makes any difference)
2. Attack Hitah'ya the Keeper
3. Get kicked
4. Confusion and sadness because you now have to farm the mob 1 time for each party member

**IDs of affected creatures, items, quests or spells with a link to the relevant page:**

NPC: https://database.turtle-wow.org/?npc=10802

**Expected behavior. Describe how it should work:**

It shouldn't kick you from the party.

**Comment by slowtorta** [comment]
I'm sorry but I've been unable to reproduce this bug. If you're able please make a video and post it in the comments.
