### ISSUE TITLE
[Client] Turtle Donation Mount "White Stag" Missing Image

### ISSUE THREAD

**Issue by redmagejoe** [slowtorta/turtlewow-bug-tracker#1484]
At current, one of the tiles for the Turtle WoW Donation Rewards UI is missing an image element for "White Stag" mount, on Page 4/6 of the Mounts sub-menu.

![Mount Menu](https://i.imgur.com/DYtNwqe.png)

![White Stag Selection](https://i.imgur.com/DT4MRsP.png)

**Comment by slowtorta** [comment]
Fixed in 1.16.1, thank you.
