### ISSUE TITLE
Infernal and Doomguard despawns

### ISSUE THREAD

**Issue by Acheron25** [slowtorta/turtlewow-bug-tracker#1485]
**Description:**
When i use the warlock spell "Inferno" the spawned "Infernal" disappears after a few (3-10) seconds unless it is in combat. If it is in combat, it will immediately despawn when it gets out of combat. The same thing happens with the "Ritual of Doom" spell. I have tested it in multiple areas and got the same result every time. I know of at least 3 other warlocks who also experienced this issue.

**How to reproduce the bug:**
1. Go to a location of your choice, preferably an area with few or no mobs.
2.  Cast the spell "Inferno" and wait a few seconds.

**IDs of affected creatures, items, quests or spells with a link to the relevant page:**

NPCs: Infernal https://database.turtle-wow.org/?npc=89 Doomguard https://database.turtle-wow.org/?npc=11859
Spells: Inferno https://database.turtle-wow.org/?spell=1122 Ritual of Doom https://database.turtle-wow.org/?spell=18540

**Expected behavior:**
The infernal or doomguard should not despawn at all. Even when the enslave effect breaks they attack the warlock who summoned them. If the warlock gets too far away, they return to the position where they were summoned.

**Comment by geojak** [comment]
I wonder if there are an videos around from classic or vanilla to see how it worked there

**Comment by ratkosrb** [comment]
@slowtorta  This was fixed in vmangos here https://github.com/vmangos/core/commit/a5567ba373de4378b8864317d075fa52c552de3d

**Comment by slowtorta** [comment]
> @slowtorta This was fixed in vmangos here [vmangos/core@a5567ba](https://github.com/vmangos/core/commit/a5567ba373de4378b8864317d075fa52c552de3d)

Thanks, successfully copypasted 👍
