### ISSUE TITLE
Maraudon: Larva Spewer object is not interactable, cannot be stopped

### ISSUE THREAD

**Issue by 9600bauds** [slowtorta/turtlewow-bug-tracker#1486]
**Please, provide a clear description what the bug is:**
In Maraudon Orange, you come across a Larva Spewer that constantly spawns adds until you rightclick it to destroy it.
Unfortunately, in TurtleWoW, the spewer is not rightclickable, so you can never stop the adds, which is rather problematic.
Here is a video demonstration of the object I'm talking about: https://youtu.be/PWdm5RYzKAk?t=291 unfortunately the video doesn't actually show him rightclicking the object.

![firefox_22-06-09-20-46-42](https://user-images.githubusercontent.com/6526157/172963080-3fd90704-360f-4e75-82a5-a78ce5e036b0.png)
![firefox_22-06-09-20-47-55](https://user-images.githubusercontent.com/6526157/172963159-25068442-e90f-4ddd-95fc-d96cf627132f.png)

**Steps to reproduce the behavior with as much detail as possible:**

1. Go to Maraudon Orange, clear until a couple packs before Noxxion
2. Locate the Larva Spewer that spews Spewed Larvas
3. Try to rightclick it
4. Notice now it doesn't even have a tooltip, so you can't rightclick it
5. Cry because you now have to kill the patrolling add every 30 secs

**IDs of affected creatures, items, quests or spells with a link to the relevant page:**

NPC: https://database.turtle-wow.org/?npc=13533
Object: https://database.turtle-wow.org/?object=178559

**Expected behavior. Describe how it should work:**
You should be able to rightclick it to destroy it.

**Comment by redmagejoe** [comment]
Can confirm this behavior persists as of 2022/07/08. This make Maraudon Orange runs more stressful than is necessary after you pass the larva rooms.

**Comment by Khanz0** [comment]
Just made a solo run yesterday and this still happens
