### ISSUE TITLE
tirisclaw bears in upper tirisfall new zone are static

### ISSUE THREAD

**Issue by geojak** [slowtorta/turtlewow-bug-tracker#1488]
**Please, provide a clear description what the bug is:**

some bears in the new tirisfaluplands zone are compeltely static. when the zone was new many mobs had this problem. this has mostly been resolved. the bears seemingly are still affected. its abnormal for wildife to be complety still and static

**Steps to reproduce the behavior with as much detail as possible:**

https://database.turtle-wow.org/?npc=91984
https://database.turtle-wow.org/?npc=91985

**Expected behavior. Describe how it should work:**

i would assume these kind of bearas, especially the ones with cubs to be patrolling around a bit, but its your custom zone, anything is find

**Comment by geojak** [comment]
the old issue 
https://github.com/slowtorta/turtlewow-bug-tracker/issues/796

**Comment by slowtorta** [comment]
Fixed in the next revision.

**Comment by geojak** [comment]
hello torta @slowtorta  i still found some bears that are static for example at aroud 17.6/56.8 if you use cords

**Comment by geojak** [comment]
no acutally its all of them, the fix didnt work it appears

**Comment by geojak** [comment]
the tirisclaw roamers move the others dont
