### ISSUE TITLE
lifetime "highest rank" but impossible to buy items (PVP rewards)

### ISSUE THREAD

**Issue by boulzorman** [slowtorta/turtlewow-bug-tracker#1489]
**The "highest rank" is supposed to let you buy the PVP items as long as your attempt inscribbed in "Highest rank" (pvp tab) is setup along the items you want to purchase, problem is, this lifetime rank is ignored and only the current rank matter.**

**Steps to reproduce the behavior with as much detail as possible:**

1. attempt a rank (for example r14)
2. downrank after reaching the supposed rank (for this example, loosing current rank 14)
3. try to buy the items (for this example, r14 weapons)

**IDs of affected creatures, items, quests or spells with a link to the relevant page:**

Patch Update notes and changes from 1.4 to 1.6 (PVP)

https://wowwiki-archive.fandom.com/wiki/Patch_1.6.0

**Expected behavior. Describe how it should work:**

During 1.4 (the launch of pvp battlegrounds and ranks) it was not possible to buy the items after losing the current r14 attempt. In 1.6 they added the feature "Highest rank" in pvp tab to enable players to buy the items again.

**Quote from 1.6 patch:** "_Honor system reward items with a rank requirement will now require a lifetime "highest rank" of that rank, rather than requiring the character to currently have the required rank."_

**Comment by geojak** [comment]
It would be best if you could lose a rank at all. Lose points yes, lose progress towarss the next rank yes, but go down a rank NO.

This would stop pvp burnout since players could actually take breaks from ranking without losing everything

**Comment by jlautenbach** [comment]
For now this is still as designed. 😦 Referring to 1.16 WoW compared to 1.16 TWoW is unfortunately not applicable in this case, afterall TWoW tries to create a Vanilla(+) experience, based of 1.12.1. But this is certainly a Quality of Life change we'll have to further look into! Thank you for reporting.

**Comment by geojak** [comment]
The op was referring to patch 1.6 not 1.16.,therefoe this is valid since 1.6 came out before 1.12.1 on which the server is based. Maybe you misunderstood something there

**Comment by Muigin** [comment]
This issue is no longer relevant with the PvP update.
