### ISSUE TITLE
Rabid Bonepaw pack do not patrol

### ISSUE THREAD

**Issue by Gasan918** [slowtorta/turtlewow-bug-tracker#1491]
**Please, provide a clear description what the bug is:**

Rabid Bonepaw pack near 53.7, 46.4 do not patrol Desolace. Stupid animals just stand and watch.

**Steps to reproduce the behavior with as much detail as possible:**

1. Come to 53.7, 46.4

![image](https://user-images.githubusercontent.com/96973359/173188355-c128823e-e9ed-4ec8-a3ba-889ddff8de1b.png)

**IDs of affected creatures, items, quests or spells with a link to the relevant page:**

NPC: https://database.turtle-wow.org/?npc=4690

**Expected behavior. Describe how it should work:**

Pack must patrol the location

![image](https://user-images.githubusercontent.com/96973359/173188495-4cafd01d-d22e-4b89-858c-f9845d7cb97d.png)

**Comment by geojak** [comment]
https://github.com/slowtorta/turtlewow-bug-tracker/issues/859
