### ISSUE TITLE
Ragefire Chasm: Missing music effect

### ISSUE THREAD

**Issue by jlautenbach** [slowtorta/turtlewow-bug-tracker#1492]
**Please, provide a clear description what the bug is:**
Ragefire Chasm is missing music sound. Only ambient sound is hearable while entering dungeon.

**Steps to reproduce the behavior with as much detail as possible:**

1. tele RFC
2. Observe sound

**Expected behavior. Describe how it should work:**
![image](https://user-images.githubusercontent.com/73019779/173197128-e3e6cbfb-b391-4f83-ba51-eac55b949239.png)

RFC should trigger instance-specific music to play.

**Comment by slowtorta** [comment]
Internal tracker, thanks.

**Comment by slowtorta** [comment]
Fixed in 1.16.1
