### ISSUE TITLE
Crashes

### ISSUE THREAD

**Issue by Omegabears** [slowtorta/turtlewow-bug-tracker#1493]
**Please, provide a clear description what the bug is:**
Game Crashing

**Steps to reproduce the behavior with as much detail as possible:**

1. Seems to happen a lot upon entering Teldrassil
2.  Happened nonstop when engaging Gnarlpine NPCs with bugged visuals.
3. Happened while traveling around Dolanaar

**IDs of affected creatures, items, quests or spells with a link to the relevant page:**

Gnarlpine Shaman: Display ID-897
Gnarlpine Augut: Display ID: 3024
Gnarlpine Avenger: Display ID: 6803

NPC: https://database.turtle-wow.org/?npc=
Item: https://database.turtle-wow.org/?item=
Quest: https://database.turtle-wow.org/?quest=
Spell: https://database.turtle-wow.org/?spell=
Object: https://database.turtle-wow.org/?object=

**Expected behavior. Describe how it should work:**

Immediate disconnect upon engaging certain NPCs, see the pictures attached of couple of NPCs with visual buggs, as well as the type of error received.
![image](https://user-images.githubusercontent.com/107325622/173205297-53171403-510b-43f6-966f-3692c79c410a.png)

![image](https://user-images.githubusercontent.com/107325622/173205315-80a13bbc-f0c4-428a-ab1a-9839d5c324e5.png)

NOTE: I do not have pfUI addon, got kicked out immediately even after disabling pfQuest and pfQuest [Turtlewow DB]
NOTE#2: Just got a crash while creating a new character in character creation window.

**Comment by Tinyfin-github** [comment]
Greetings!

Please enable  vertex animation shaders in video settings then restart the game. If you encounter any issue please contact support on discord.
