### ISSUE TITLE
All of the Imperial Plate recipe quests need 2x as much thorium as they claim they do

### ISSUE THREAD

**Issue by 9600bauds** [slowtorta/turtlewow-bug-tracker#1494]
**Please, provide a clear description what the bug is:**

![WoW_22-06-11-19-46-15](https://user-images.githubusercontent.com/6526157/173207287-5627b981-bf70-410b-b3d2-6f1c5621faef.png)

**Steps to reproduce the behavior with as much detail as possible:**

1. Go to Gadgetzan, talk to Derotain Mudsipper (you need lvl50 and 265+ blacksmithing)
2. Complete his initial quest 
3. Talk to him again to get the quests for each Imperial Plate recipe
4. Notice how he claims he needs 20 bars but actually needs 40, or claims he needs 30 bars but needs 60 etc.
5. Notice how this happens for literally all of his quests

**IDs of affected creatures, items, quests or spells with a link to the relevant page:**

https://database.turtle-wow.org/?npc=14567#ends

**Expected behavior. Describe how it should work:**

The quest description should match the quest requirements.

**Comment by slowtorta** [comment]
Can't confirm these issues. It's all correct in your DB. Please clear your WDB cache!

**Comment by 9600bauds** [comment]
Issue is present in the DB:
![firefox_22-06-13-18-26-13](https://user-images.githubusercontent.com/6526157/173448160-35803e29-6225-4294-89cd-2e54b09d26d7.png)
The top text is never used because this is a "ready-to-turn-in" quest that is pre-accepted, players only ever see the "Progress:" text.

**Comment by Velite12** [comment]
https://tbc.wowhead.com/quest=7656/imperial-plate-chest 

This is funny but I want to point out:

Wowhead Classic Vanilla has 60 in the quest text and 60 for the requirement

![image](https://user-images.githubusercontent.com/45871932/173767490-1fae4b8c-603d-464a-bf6d-1d3bd683a7e1.png)


Wowhead Classic TBC has 60 in the quest text, but 30 for the requirement

![image](https://user-images.githubusercontent.com/45871932/173767433-09037ba8-538c-46e4-a8e1-646f75c86fab.png)

Wowhead Retail has 30 for 30

![image](https://user-images.githubusercontent.com/45871932/173767586-421b9c79-b6d1-4b97-8b1d-e4648e431631.png)

**Comment by Velite12** [comment]
It seems that it is supposed to be 60 bars in vanilla, but the quest text is misleading.

**Comment by slowtorta** [comment]
Fixed in the next revision.
