### ISSUE TITLE
The new undead zone in trisifal  npc bug

### ISSUE THREAD

**Issue by Dariusius** [slowtorta/turtlewow-bug-tracker#1497]
as alliance druid i can hit and kill ally npc on that new zone almost all the lordaeron  remmnants npc  can be killed by me as i said i'm  an alliance night elf druid i'm on warmode  lvl 48  Darius
**-here  is the npc that can be killed :**
https://database.turtle-wow.org/?npc=91977
https://database.turtle-wow.org/?npc=91352
https://database.turtle-wow.org/?npc=91975
https://database.turtle-wow.org/?npc=91978
https://database.turtle-wow.org/?npc=91979
https://database.turtle-wow.org/?npc=91351
https://database.turtle-wow.org/?npc=91976
https://database.turtle-wow.org/?npc=91974
https://database.turtle-wow.org/?npc=91353
https://database.turtle-wow.org/?npc=91772
https://database.turtle-wow.org/?npc=91773
https://database.turtle-wow.org/?npc=91980
https://database.turtle-wow.org/?npc=91981
-here is the npcs that are good not bugged for me 👍 
the 3 high elves on that zone and 
https://database.turtle-wow.org/?npc=91721
Conclusion: 
i think the bugged its about the warmode on that zone these npc for me got green name and can be killed by me but they dont atk me its  only i can kill them as ally  hope its all u need have :D

**Comment by Tinyfin-github** [comment]
Please go to your reputation  tab and uncheck at war with factions under <Other>

![image](https://user-images.githubusercontent.com/83077166/173333917-6625035a-61dc-4e91-81a9-d9cdfdb1137e.png)
