### ISSUE TITLE
School of Tastyfish Spawns

### ISSUE THREAD

**Issue by redmagejoe** [slowtorta/turtlewow-bug-tracker#1498]
https://classic.wowhead.com/item=19807/speckled-tastyfish#map

The number of pools that spawn during the Stranglethorn Fishing Extravaganza is obscenely small compared to what's supposed to be available during the actual event. There's supposed to be an abundance of pools, including in places where a low level twink could conceivably safely fish without fear of being attacked by high level mobs. Old guides even mention Yojamba Isle, which on Turtle has 0 schools, lending credence to the map provided being accurate to how it should be on Turtle.

https://xpoff.com/threads/stv-fishing-tourny-a-guide-for-low-level-twinks.48773/#:~:text=The%20red%20circle%20(north%20west,twink%20prior%20to%20the%20Shattering.

**Comment by geojak** [comment]
i am trying too today and it seems all the pools are already spawend before the compettition started with the regular black mouth sirefin etc. so tastfish could not spawn there instead.

**Comment by geojak** [comment]
Some of the tasty fish spawn pools are bugged, so you can barely hit the swimmer in because too close to land or the cycle pool is even only displayed halve
