### ISSUE TITLE
[Druid] Druid enrage does not reduce armor

### ISSUE THREAD

**Issue by Tinyfin-github** [slowtorta/turtlewow-bug-tracker#1499]
Druid enrage does not reduce armor

https://database.turtle-wow.org/?spell=5229#taught-by-npc

**Comment by faralynn** [comment]
I would actually request this be adopted as a custom feature with the spell's text adjusted to reflect that and avoid confusion.

On Turtle WoW, Druid Tanks are a bit behind Warrior's still. In TABC raids they were undeniably more squishy than Warrior's no matter how hard they tried or how much gear they were fed. Fixing this would only make things worse, IMO. 

Sure, it may be blizz-like to fix it and it may indeed be a bug but not everything on Turtle is blizz-like anyway, especially with mobs and their values for armor, cooldowns, etc.
