### ISSUE TITLE
Paladin Blessings and Shaman Totems should stack

### ISSUE THREAD

**Issue by Velite12** [slowtorta/turtlewow-bug-tracker#15]
By opening this Issue, I admit to having done the pertinent research using sources from Vanilla (preferably) or Classic. I also understand that sources from other private servers are not acceptable.

**Current behavior**: 

Windfury and Blessing of Kings do not stack
Blessing of Might and Strength of Earth totem do not stack.

**Expected behavior**: 

Paladin blessings and shaman totems should stack.

Note that all evidence will only exist showing the 5 min (single target version) of blessings. This is because Greater Blessings will be removed when the paladin leaves the group. And you couldn't invite paladins to join your group in vanilla/classic.

**Proofs**:

https://youtu.be/FzJAa9LFbH0?t=111

![image](https://user-images.githubusercontent.com/45871932/120879269-34feac00-c590-11eb-9035-79ca773616c2.png)

**Steps to reproduce**:

1. Group a shaman with a paladin and attempt to cast blessings
2. Notice that the pulse of shaman totems will remove certain paladin blessings

**Comment by Mamotromico** [comment]
That is not a bug, it's a server feature. Check the second post:

https://forum.turtle-wow.org/viewtopic.php?f=4&t=912

**Comment by perl1743** [comment]
Don't think Qixel is a member of staff, just a forum poster.

**Comment by Velite12** [comment]
> 
> 
> That is not a bug, it's a server feature. Check the second post:
> 
> https://forum.turtle-wow.org/viewtopic.php?f=4&t=912

That's just detailing how the interactions work, it wasn't intentionally set that way on turtle wow, that's just the current behavior in the database that vmangos servers use.

**Comment by Nolin7777** [comment]
Closed after internal discussion
