### ISSUE TITLE
Pets use Dash even in melee range

### ISSUE THREAD

**Issue by spuxx1701** [slowtorta/turtlewow-bug-tracker#1500]
**Please, provide a clear description what the bug is:**
Hunter pets use the 'Dash' ability when having it on auto-cast even in melee range. That ability is not useful in melee range, since it only increases movement speed, and results in the waste of focus.

**Expected behavior. Describe how it should work:**
I cannot say for sure how it was in Vanilla, but at least in Classic, pets don't use Dash in melee range, but only when moving towards an enemy. That makes them quite a bit more focus-efficient.

**Comment by nonameform** [comment]
Classic is different from Vanilla as it uses a modified game engine, so not all abilities work the same way as they used to work in 2004-2006.

The easy solution is to disable auto casting for Dash.

The AI for pets is very primitive: if you have both Bite and Claw on auto-cast, Bite will be used once and then the pet will dump all focus into Claw, so you have to babysit your pet for maximum efficiency.

**Comment by slowtorta** [comment]
This is correct, you have to disable auto-cast for your pet's abilities :)
