### ISSUE TITLE
Mind Flay skill animation issue

### ISSUE THREAD

**Issue by Darkana89** [slowtorta/turtlewow-bug-tracker#1503]
**Please, provide a clear description what the bug is:**

Good day, I play as a Shadow Priest and my problem is the buggy animation of the "Mind Flay" skill:
1) As if interrupting it (the character starts waving his arms and the cast bar behaves as if the cast continues)
2) When casting the same spell again before its first full cast, i.e. interrupting the first cast and immediately starting the second, there is no animation of the beam connecting the priest and his target.
3) Аnother nuance, when you interrupt the mind flay cast, after a global cooldown, sometimes the skills on the assigned buttons do not work, they just seem to not be pressed, as if the interface does not respond.

Since we play on x1 server, and the leveling and generally the time of playing on the character is quite large, this becomes a very significant problem for me personally, inclining me to bad thoughts. In addition, this is a commonly used skill. This is very annoying) Please, please fix this, and I will continue to be your humble fan. Thank you!

**IDs of affected creatures, items, quests or spells with a link to the relevant page:**

https://database.turtle-wow.org/?spell=16568

**Expected behavior. Describe how it should work:**

I played on different projects for the shadow priest, including on the official vanilla servers, it should work logically, when you cast - the cast goes on, when you interrupt it, then the character should not wave his arms and perform some extraneous actions, and the cast bar should not continue to pretend that the cast is not interrupted, so the animation should work even after interrupting and starting a new cast.

PS: I've tried reinstalling and tweaking my video drivers - didn't help. I tried to remove and install a clean client without addons, etc. - it did not help.

**VIDEO:**
https://youtu.be/fUn2lRT0bQ0

![mind Flay](https://user-images.githubusercontent.com/107635434/174121144-6f25724e-ced6-40e7-8bdc-6eb0c34299a1.png)

**Comment by redmagejoe** [comment]
Can confirm this is still an issue

**Comment by Giperion** [comment]
Waving hands animation is still active for 3 seconds at the end of the spell. It actually doesn't matter, if it was interrupted or not. Even if it was fully successful - character will still stay 3 seconds with hands

**Comment by Giperion** [comment]
```
When casting the same spell again before its first full cast, i.e. interrupting the first cast and immediately starting the second, there is no animation of the beam connecting the priest and his target.
```
Can't reproduce that, no matter how hard I tried
