### ISSUE TITLE
Zantiki <Leatherworking Trainer> won't train

### ISSUE THREAD

**Issue by Rykenwolf** [slowtorta/turtlewow-bug-tracker#1504]
**Please, provide a clear description what the bug is:**

Zantiki <Leatherworking Trainer> Turtle custom NPC, located in Durotar, 37.1, 22.7, does not offer to train leatherworking despite his title. Image shows skills indicating Leatherworking, and also chat box displayed when talking to Zantiki
![image](https://user-images.githubusercontent.com/106287790/174206457-72c244ef-d56a-41a7-9d41-018b6dc97a18.png)

**Steps to reproduce the behavior with as much detail as possible:**

1. Right click to talk to Zantiki. Character has Journeyman Leatherworking previously trained.
2. Zantiki has a simple chat dialogue, no option for Training

**IDs of affected creatures, items, quests or spells with a link to the relevant page:**

NPC: https://database.turtle-wow.org/?npc=60511

**Expected behavior. Describe how it should work:**
Zantiki should offer to train leatherworking skills.

**Comment by slowtorta** [comment]
Fixed in the next revision.
