### ISSUE TITLE
Alliance Quests unavailable for Stormwind vault, and are marked under incorrect zone category in the DB

### ISSUE THREAD

**Issue by atazs** [slowtorta/turtlewow-bug-tracker#1507]
**Please, provide a clear description what the bug is:**
Quests for Alliance players, "Alien Artifact" and "A Noble Fear" are unavailable at lvl 60. There is not even a grey ? above the heads of the NPCs. The quests are also marked under "Tirisfal Glades" zone, when in fact, Tirisfal Glades has nothing to do with the quests and the NPCs are located in Stormwind City.

**Steps to reproduce the behavior with as much detail as possible:**

1. Go to the NPCs linked below in Stormwind

**IDs of affected creatures, items, quests or spells with a link to the relevant page:**

NPC: https://database.turtle-wow.org/?npc=80450
NPC: https://database.turtle-wow.org/?npc=80451
Quest: https://database.turtle-wow.org/?quest=80004
Quest: https://database.turtle-wow.org/?quest=80002

**Expected behavior. Describe how it should work:**
According to the Turtle WoW database, the two NPCs linked above should give quests for the Stormwind Vault instance and the quests should be either uncategorized, or marked under Stormwind or Stormwind Vault.

**Comment by gheor7** [comment]
The quests were scrapped, and were written at least on year prior the dungeon's release.

**Comment by atazs** [comment]
T

> The quests were scrapped, and were written at least one year prior the dungeon's release.
> 
> It simply didn't work out as it was meant to, perhaps it will be revised in the future but it is currently not a bug.

Then they should be removed, or marked as deleted/obselete. I asked several times in Discord, even sent a personal DM to Tinyfin, receiving complete silence.

**Comment by slowtorta** [comment]
Removed in the next revision.
