### ISSUE TITLE
Lots of mobs in Gillijim's Isle have unnaturally poor or totally empty loot tables

### ISSUE THREAD

**Issue by 9600bauds** [slowtorta/turtlewow-bug-tracker#1508]
**Please, provide a clear description what the bug is:**
There are many mobs in Gillijim's Isle that seem to have nonexistent or unfinished loot tables. This means they drop little to no loot, which is a sharp contrast compared to vanilla mobs and kinda hurts the zone's popularity as a leveling area.
Documenting the ones that I find but I probably missed some:

 - All the drowned ghosts on the shore (example of one: https://database.turtle-wow.org/?npc=92164
No loot at all, should drop cloth, Ichor of Undeath and a few other generic humanoid drops. Examples of similar level ghost type mobs from other zones, and their loot tables: https://database.turtle-wow.org/?npc=7864 https://database.turtle-wow.org/?npc=8540 https://database.turtle-wow.org/?npc=3094

- Both types of basilisk: https://database.turtle-wow.org/?npc=91964 https://database.turtle-wow.org/?npc=91963
Effectively only drop crocolisk teeth which are kinda out of place. Should drop basilisk tails, basilisk eyes, and more expensive vendor loot. Example of similar level basilisk from another area, and its loot table: https://database.turtle-wow.org/?npc=5990

- All the Deepsnap Makrura types on the shore, here's an example of one: https://database.turtle-wow.org/?npc=91834
No loot at all, should have clams and generic Makrura loot. Example of similar level Makrura mob from Aszhara: https://database.turtle-wow.org/?npc=6372

- All the Southsea Outlaws and miners, here's two examples: https://database.turtle-wow.org/?npc=92139 https://database.turtle-wow.org/?npc=92134 etc
No loot at all, should have cloth and other generic humanoid drops

- Water elementals on the beach, here's one example: https://database.turtle-wow.org/?npc=91967
No loot at all, should drop water elemental stuff like this similar elemental in Feralas: https://database.turtle-wow.org/?npc=5461

- All the nagas, here's one example: https://database.turtle-wow.org/?npc=91840
No loot at all, should drop clams and other naga stuff like this similar naga in Aszhara: https://database.turtle-wow.org/?npc=6190

- All the murlocs, here's one example: https://database.turtle-wow.org/?npc=92160
No loot at all, should drop clams and other murloc stuff like this similar murloc in Swamp of Sorrows: https://database.turtle-wow.org/?npc=747

- All the turtles, here's one example: https://database.turtle-wow.org/?npc=91838
No loot at all, should drop turtle meat and other turtle stuff like this similar turtle: https://database.turtle-wow.org/?npc=13599

**Comment by afizzler** [comment]
I can say the same for trash mobs in Stormwind Vault and Black Morass

**Comment by redmagejoe** [comment]
These NPCs still need to have loot tables copied from similar existing entities. Please put a prio on this.

**Comment by Haaxor1689** [comment]
Fixed!
