### ISSUE TITLE
Possible wrong quest reward in Gillijim?

### ISSUE THREAD

**Issue by 9600bauds** [slowtorta/turtlewow-bug-tracker#1509]
**Please, provide a clear description what the bug is:**
When you do this quest: https://database.turtle-wow.org/?quest=40196
You are given as reward a Barrel of Steamwheedle Wine: https://database.turtle-wow.org/?item=60270
Which is confusing for several reasons:
1. It's a quest item for a lvl30 Bloodsail Buccaneers quest
2. That quest is in a completely different zone
3. The quest item is extremely easy to obtain even if you're still doing the lvl30 quest for some reason
4. There is no other reward for this kill-an-elite quest, which usually give something better

**Expected behavior. Describe how it should work:**
No clue. Maybe this quest was supposed to award something else? If it was meant to give you booze, maybe it should be normal booze that's not a quest item for another unrelated quest, maybe booze that you can actually drink? And the NPC maybe should remark on this unusual quest reward if it really is intended

**Comment by slowtorta** [comment]
Thank you, it'll be fixed in the next revision.
