### ISSUE TITLE
More Alah'Thalas Flightpath Bugs

### ISSUE THREAD

**Issue by Lexiebean** [slowtorta/turtlewow-bug-tracker#1510]
This one feels quite strange.

I took the Alah'Thalas flightpath to Chillwind Camp, Western Plaguelands.

I then did a Scholomance. When we were done I used my hearthstone, which took me to Feathermoon Stronghold. Where I logged out shortly after.

When I logged back in a little later I was at the Chillwind Camp, Western Plaguelands flightpoint spot.

**Comment by geojak** [comment]
It also lacks a Griffonnest near the flight master like everywhere else pls

**Comment by slowtorta** [comment]
Fixed in 1.16.1.

**Comment by Tinyfin-github** [comment]
Issue still persists

**Comment by slowtorta** [comment]
https://github.com/slowtorta/turtlewow-bug-tracker/issues/1449

**Comment by slowtorta** [comment]
Nearly impossible to fix until we have some content on the non-finished part of EK to provide a path w/o teleport mid-flight. Keeping it in mind for the future.
