### ISSUE TITLE
Alliance Gillijim's/Lapidis quests unable to be picked up by High Elves

### ISSUE THREAD

**Issue by usedcars4cheap** [slowtorta/turtlewow-bug-tracker#1512]
These quests are obtained through interacting with world objects: 

"The Rotten Renown" https://database.turtle-wow.org/?quest=40149
"An Extravagant Book" https://database.turtle-wow.org/?quest=40153

The flags for these quests exclude High Elves - players can mouseover and see cogwheel for the world object but not interact and pick up the respective quests.

Previously experienced by players before: https://github.com/slowtorta/turtlewow-bug-tracker/issues/1312

**Comment by atazs** [comment]
Allowable Races: Human, Dwarf, Nightelf, Gnome

Not sure why they'd leave high elves out of them. Could be intentional?

**Comment by slowtorta** [comment]
Fixed in the next revision.
