### ISSUE TITLE
[Ring of Demonic Fury] attack speed increase affects only melee attack speed

### ISSUE THREAD

**Issue by Khelekmir** [slowtorta/turtlewow-bug-tracker#1514]
**Please, provide a clear description what the bug is:**

[Ring of Demonic Fury] secondary item effect: "Equip: Increases your attack speed by 1%" affects ONLY melee attack speed, not ranged attack speed. Unsure if this is by design or not.

**Steps to reproduce the behavior with as much detail as possible:**

1.  Compare melee/ranged attack speed in character sheet before and after equipping [Ring of Demonic Fury] 
2.  
3. 

**IDs of affected creatures, items, quests or spells with a link to the relevant page:**

Item: https://database.turtle-wow.org/?item=83217
((PROBABLY ALSO: Item: https://database.turtle-wow.org/?item=60258 ... but this is a rare drop that I have not acquired, and am unable to supply data for. As a hunter, I am disincentivized to farm for it if the attack speed increase is likewise only for melee... ))

**Expected behavior. Describe how it should work:**

Expect Ranged Attack Speed to also improve by 1% in character menu for "attack speed increase", similar to "attack power increase" affecting both ranged/melee ... unless ring is designed to affect only melee attack speed, in which case expectations can be managed by rewording: "Equip: Increases **melee** attack speed by 1%"

**Comment by Dragunovi** [comment]
The original spell supported on melee haste, but we are likely implementing it so the effect also effects ranged attack speed and casting speed with the release of 1.16.1. So sadly you will have to wait for the release of the next client patch.
