### ISSUE TITLE
Midsummer Quests

### ISSUE THREAD

**Issue by afizzler** [slowtorta/turtlewow-bug-tracker#1518]
It is not letting me get quests from Festival Loremaster or horde NPC equivalent, such as Stealing Stormwind's Flame. It could be nice if it was fixed quickly, so I could parse for naxx. 

Quests Affected:
https://database.turtle-wow.org/?quest=9332
https://database.turtle-wow.org/?quest=9331
https://database.turtle-wow.org/?quest=9324
https://database.turtle-wow.org/?quest=9330
https://database.turtle-wow.org/?quest=9325
https://database.turtle-wow.org/?quest=9326

NPCs Affected:
https://database.turtle-wow.org/?npc=16817
https://database.turtle-wow.org/?npc=16818

I should be able to get these quests during Midsummer.

**Comment by afizzler** [comment]
need to do more testing myself

**Comment by geojak** [comment]
there are no quests available to alliance it seems, only for horde

**Comment by Gurky-Turtle** [comment]
closing this as it looks fixed.
