### ISSUE TITLE
Mechanist's Bonechopper Replica animation seems to be a bit broken

### ISSUE THREAD

**Issue by 9600bauds** [slowtorta/turtlewow-bug-tracker#1519]
**Please, provide a clear description what the bug is:**

https://user-images.githubusercontent.com/6526157/175197136-090521c5-1c42-4a87-9787-b6c5029a48b2.mp4

The part where the cog frenetically switches size and then seemingly inverts itself inside-out is probably not intended.

**IDs of affected creatures, items, quests or spells with a link to the relevant page:**
Item: https://database.turtle-wow.org/?item=81288

**Expected behavior. Describe how it should work:**
The cog should probably spin around and maybe rattle around a little bit, but it should probably stay the same size.

**Comment by slowtorta** [comment]
This one is working as intended, Blizzard made this model, we can't really modify it easily.
