### ISSUE TITLE
[Post Restart 2022/06/21] Pyrewood Village NPCs No Longer Transform at Night

### ISSUE THREAD

**Issue by redmagejoe** [slowtorta/turtlewow-bug-tracker#1520]
After an arbitrary server time (as it never seems to have correlated to the moment the Sun or Moon icon in the minimap icon change), the Pyrewood Village NPCs are meant to shift from humans into Moonrage Worgen, and back to humans during the daytime. Relevant day and night NPCs are listed below.

Day:
https://database.turtle-wow.org/?npc=1891
https://database.turtle-wow.org/?npc=1894
https://database.turtle-wow.org/?npc=1895
https://database.turtle-wow.org/?npc=3528
https://database.turtle-wow.org/?npc=3530
https://database.turtle-wow.org/?npc=3532

Night:
https://database.turtle-wow.org/?npc=1892
https://database.turtle-wow.org/?npc=1893
https://database.turtle-wow.org/?npc=1896
https://database.turtle-wow.org/?npc=3529
https://database.turtle-wow.org/?npc=3531
https://database.turtle-wow.org/?npc=3533

After the most recent restart, these NPCs seem to have been cured of their curse! Wonderful for them! It is, however, wrong. At various "night times" of day, I have observed these NPCs untransformed on the way to Shadowfang Keep. Server times have been 9:35pm, 1:53am, and 4:04am. While this indirectly seems to fix the howl spam bug (https://github.com/slowtorta/turtlewow-bug-tracker/issues/1421) which was associated with nighttime, it is not appropriate behavior.

**Comment by geojak** [comment]
this diesnt appear to be fixed.

npcs were in human from at 23 sevre time just now

**Comment by redmagejoe** [comment]
This has been fixed for a while so I'm closing this.
