### ISSUE TITLE
Chillwind Abduction

### ISSUE THREAD

**Issue by Gildrick** [slowtorta/turtlewow-bug-tracker#1521]
**Please, provide a clear description what the bug is:**

**Steps to reproduce the behavior with as much detail as possible:**

1. I hearth to Stormwind.
2. I log out.
3. I log back in at Chillwind Camp.

This has happened several times. Cleared WDB several times, doesn't work.

**Comment by slowtorta** [comment]
I'm sorry, I could not reproduce it. Make a video of this event please next time.
