### ISSUE TITLE
Undead workers in ab gm

### ISSUE THREAD

**Issue by geojak** [slowtorta/turtlewow-bug-tracker#1523]
**Please, provide a clear description what the bug is:**
 There are undead miners at the ab gold mine even when allaince controls it
**Steps to reproduce the behavior with as much detail as possible:**

1. Go inside ab goldmine when alliance controlled it
2. See there are undead
3. They hsoud not be, compare to stable where there are human or undead workers depending on who controlled it

**IDs of affected creatures, items, quests or spells with a link to the relevant page:**

**Expected behavior. Describe how it should work:**
 Human workers when humans controlled it

**Comment by redmagejoe** [comment]
Tested on current version. All 5 nodes show human laborers when owned by Alliance, and all 5 nodes show Forsaken laborers when owned by Horde.

Fixed.
