### ISSUE TITLE
Two Orgrimmar Music Tracks Not Being Played

### ISSUE THREAD

**Issue by FeyfolkenFantasy** [slowtorta/turtlewow-bug-tracker#1525]
**Please, provide a clear description what the bug is:**

The two following music tracks are not being played in Orgrimmar:
orgrimmar01-moment
orgrimmar02-moment

**Steps to reproduce the behavior with as much detail as possible:**

1. Create the following folder tree in your Turtle WoW file directory (where WoW.exe is located) : Sound>Music>CityMusic>Orgrimmar

2. In the "Orgrimmar" folder, put 5 different and easily distinguable music tracks in the Mp3 format.

3. Rename them as: "orgrimmar_intro-moment", "orgrimmar01-moment", "orgrimmar01-zone",  "orgrimmar02-moment", "orgrimmar02-zone" (without the " ").

4. Login to TurtleWoW, go to Orgrimmar and stay there. You will soon notice that the music tracks that you have chosen to replace "orgrimmar01-moment" and "orgrimmar02-moment" are not being played at all.

**Expected behavior. Describe how it should work:**

Orgrimmar has 5 different soundtracks and all of them should be played.

**Comment by slowtorta** [comment]
It's a known issue and will be fixed in Patch 1.16.1 :)
