### ISSUE TITLE
Quest item for SFK quest "Into The Jaws" should respawn quicker.

### ISSUE THREAD

**Issue by nobodyinteresting** [slowtorta/turtlewow-bug-tracker#1526]
**Please, provide a clear description what the bug is:**
Currently, if doing a run of SFK with a full group and everyone has the "Into The Jaws" quest, each player has to wait 5~ minutes for the quest item to respawn. This should probably not be the case inside a dungeon.

For instance, the object for the quest The Book of Ur spawns in the same room, and respawns after 5 seconds.

**IDs of affected creatures, items, quests or spells with a link to the relevant page:**
Quest: https://database.turtle-wow.org/?quest=40281
Object: https://database.turtle-wow.org/?object=2010856

**Comment by slowtorta** [comment]
Fixed in the next revision.
