### ISSUE TITLE
Stone Guardians in Un'Goro can't move

### ISSUE THREAD

**Issue by 9600bauds** [slowtorta/turtlewow-bug-tracker#1528]
**Please, provide a clear description what the bug is:**
Similar issue as some other custom mob issues, these mobs stand still and are permanently rooted in place. This means they are infinitely farmable by any ranged class.

**Steps to reproduce the behavior with as much detail as possible:**

1. Go to Northern Un'Goro around 52.5 13
2. Find the circle of Stone Guardians
3. Shoot them to death
4. Notice how they never come close

**IDs of affected creatures, items, quests or spells with a link to the relevant page:**

NPC: https://database.turtle-wow.org/?npc=60402 (I am not 100% sure this is the mob? When I tried killing one, it did drop loot, but the DB shows these as lootless)

**Expected behavior. Describe how it should work:**
They should move.

**Comment by geojak** [comment]
https://github.com/slowtorta/turtlewow-bug-tracker/issues/681

**Comment by geojak** [comment]
they dont seem to drop guardian stones anymore, that is a good change, since it ruined the guaridna stone prices and made farming the elites obsolete.

too bad was hoping to use this little trick to make up for the ah eco colapse

**Comment by slowtorta** [comment]
Fixed in the next revision.
