### ISSUE TITLE
Fall damages glitch

### ISSUE THREAD

**Issue by FeyfolkenFantasy** [slowtorta/turtlewow-bug-tracker#1529]
**Please, provide a clear description what the bug is:**

I was leisurely walking on the upper floor of the Trade Quarter of Undercity. Religiously countning my gold coins as every goblin does it every single hours. When I suddently missed the step and fell right under, near the cook master. And?!... I died... Lost 100% of my health from a tiny fall.

![WoWScrnShot_062822_001128](https://user-images.githubusercontent.com/102554573/176047448-2d9ade40-4eaa-4167-bb7e-7e3be3d3ee8e.jpg)

**Steps to reproduce the behavior with as much detail as possible:**

I really doubt one can reproduce this glitch at will, as it happens for no reasons.
This is a very knows bug which has been inherent to TurtleWoW for months.
This happens also regularly on the zeppelin from Orgrimmar to Kargath for instance.

Could you fix it once and for all please!?

**Expected behavior. Describe how it should work:**

One shall not die of fall damages for no reasons or for very short falls at all.

**Comment by slowtorta** [comment]
Ancient bug, after 20 years is now considered to be part of the game. Brace for impact!
