### ISSUE TITLE
AB control basses quest are crossfaction

### ISSUE THREAD

**Issue by geojak** [slowtorta/turtlewow-bug-tracker#1530]
**Please, provide a clear description what the bug is:**

for ab there are qeust to control 4/5 bases at the same time.
turned out, these are qeuest are basically for free, why?
if 4/5 bases are controlled in total, horde + allaicne combined, the quest finsihes

[**Steps to reproduce the behavior with as much detail as possible:**

1. have the qeust for 5 bases
2. go into ab
3. have horde and alliance takes baes
4. for example 3 horde controlled, 2 alliance controlled
5. qeust finishes since all 5 bases are controlled by someone

**IDs of affected creatures, items, quests or spells with a link to the relevant page:**

https://database.turtle-wow.org/?search=bases

**Expected behavior. Describe how it should work:**

quest should not be crossfaction, you need to cotrol 4/5 bases with your faction. the qeust is supposed to be hard not free

**Comment by redmagejoe** [comment]
Cross-faction credit does not appear to be an issue on current version. However, the quest does appear to "remember" which nodes you've captured similar to the "assault these four nodes" quest. I am fairly certain that is not how it is meant to behave, and the quest is meant to check if you are holding 4 nodes at the same time in one AB for credit, but that is another issue.

Fixed.
