### ISSUE TITLE
Spelling mistake in quest: "Zabini's Information"

### ISSUE THREAD

**Issue by Galuur** [slowtorta/turtlewow-bug-tracker#1532]
There is a spelling mistake in the quest text for Zabini's Information quest. First paragraph, it states: "The dark magic within Hawk's Vigil has seemingly appeared out of nowhere, it's presence...." when it should read "... its presence...". 

Additionally, same quest later states "... at a level where many like myself, and Marge would have come...." when it is grammatically correct to state "at a level where many, like myself and Marge, would have come ....".

**Comment by slowtorta** [comment]
Fixed in the next revision!
