### ISSUE TITLE
Using the word RADAR is inconsistent with WoW's lore time period.

### ISSUE THREAD

**Issue by Shellyoung** [slowtorta/turtlewow-bug-tracker#1534]
**Please, provide a clear description what the bug is:**

You might say "This is a strange waste of my time". The issue resembles using of a word "Fire" in Lord of the Rings: The Return of the King movie as a command for archers to release arrows. WoW's lore is based on medieval ages that lasted approximately years 500-1500. [Radar](https://en.wikipedia.org/wiki/Radar) is an acronym for RAdio Detection And Ranging. First experiments on Radar are dated to year 1886 which is far later then medieval ages.

**Steps to reproduce the behavior with as much detail as possible:**
- Open [Martin's Unsent Letter](https://imgur.com/nJd7Gj3)

**IDs of affected creatures, items, quests or spells with a link to the relevant page:**

- Item: https://database.turtle-wow.org/?item=81414

**Expected behavior. Describe how it should work:**
- Change the sentence to "I am keeping myself safe since I have left Stormwind."

**Comment by gheor7** [comment]
Radio already exists as gnomish invention. A radar is not far from an engineering point of view.

https://classic.wowhead.com/item=10723/gnomish-ham-radio

**Comment by Velite12** [comment]
I'd substitute "under the radar" for "low profile"

**Comment by slowtorta** [comment]
Changed in the next revision to:

> To Duke Ramon III,

Thanks again for everything you've done. For my own safety, I had to keep my head low since I left Stormwind.

It appears that SI:7 has been keeping tabs on me, but I assure you that I have kept myself unseen so far and well-hidden within my room.

**Comment by Shellyoung** [comment]
![index](https://user-images.githubusercontent.com/40469927/178105793-d045292c-b241-4c89-96d2-a2050c95d37c.png)
