### ISSUE TITLE
Cant restart Avatar of Hakkar encounter

### ISSUE THREAD

**Issue by freddemannen** [slowtorta/turtlewow-bug-tracker#1536]
**Please, provide a clear description what the bug is:**
When you fail the Avatar of Hakkar encounter, on the quest The God Hakkar the mobs wont spawn again when you use the [Egg of Hakkar] which has a 5min CD, and you cant get out of the gates.
**Steps to reproduce the behavior with as much detail as possible:**

1. Mobs wont spawn after you use the egg again, you just see the green glow on the ground.
2. Gates stay closed so you have to use hearthstone.
3. 

**IDs of affected creatures, items, quests or spells with a link to the relevant page:**

NPC: https://database.turtle-wow.org/?npc=
Item: https://database.turtle-wow.org/?item=
Quest: https://database.turtle-wow.org/?quest=
Spell: https://database.turtle-wow.org/?spell=
Object: https://database.turtle-wow.org/?object=

**Expected behavior. Describe how it should work:**

**Comment by gorxen** [comment]
confirming, this bug has been present for over a year now.

**Comment by redmagejoe** [comment]
Encountered this bug today. It seems that using the activation a third time after the second attempt fails to activate, the event starts as normal. Something is not triggering properly on the second activation that is apparently resolved by the third.

**Comment by ratkosrb** [comment]
Actually you should not be able to restart the event after failing. You only get 1 chance. I tested on Classic and you have to reset the dungeon to attempt the Avatar of Hakkar event again after dying. However if you die after Hakkar has already been summoned and becomes attackable, he does not despawn on evade, and you can run back in and kill him, as the event itself is considered complete at that point.
