### ISSUE TITLE
Quest: "Establishing New Outposts" - Warmode PVP Flag doesn't count

### ISSUE THREAD

**Issue by usedcars4cheap** [slowtorta/turtlewow-bug-tracker#1537]
For the quest "Establishing New Outposts", where Alliance players are tasked with taking control of all four Eastern Plaguelands towers:
https://database.turtle-wow.org/?quest=9664

Credit is not granted to players pvp flagged under Warmode - they must manually flag up to receive quest credit.
Unsure if intended.

**Comment by slowtorta** [comment]
PvP flag is the same in normal PvP mode and in War Mode, sorry, I couldn't reproduce this bug!

**Comment by magzys** [comment]
I just encountered this bug. Stood on a tower for 5-10 minutes as a warmode player. was curious as to why the bar wasn't coming up. Found this page, and typed /pvp and it poped up and started capping. going to 2nd tower as we speak.
