### ISSUE TITLE
Farming Sand in BWL is not possible 

### ISSUE THREAD

**Issue by Nathan2403** [slowtorta/turtlewow-bug-tracker#1538]
**Please, provide a clear description what the bug is:**
Our BWL raid cleared to Chromag and then went to farm sand from the pack we had skipped. After killing the Blackwing Technicians and resetting the pack, the goblins did not respawn.

**Steps to reproduce the behavior with as much detail as possible:**

1.  Kill the Goblin Technicians
2. Reset the pack by jumping on a barrel or leaving the instance

**IDs of affected creatures, items, quests or spells with a link to the relevant page:**

NPC: https://database.turtle-wow.org/?npc=13996
Item: https://database.turtle-wow.org/?item=
Quest: https://database.turtle-wow.org/?quest=
Spell: https://database.turtle-wow.org/?spell=
Object: https://database.turtle-wow.org/?object=

**Expected behavior. Describe how it should work:**

If a single npc from one of these packs lives, then the whole pack should respawn. After killing the goblins and resetting the rest, the goblins should respawn.

**Comment by Lexiebean** [comment]
Working as intended
