### ISSUE TITLE
Human Female Face Customization Option Missing

### ISSUE THREAD

**Issue by jim-goose** [slowtorta/turtlewow-bug-tracker#1539]
**Please, provide a clear description what the bug is:**

A human female face customization opition shown in a screen shot on the website under new character customizations linked here: https://www.turtle-wow.org/images/skins/unknown%20(9).png is missing in game.

**Steps to reproduce the behavior with as much detail as possible:**

1. Create new human female
2. Face from website is missing

**Expected behavior. Describe how it should work:**

Please add the face. Sorry if this doesn't count as a real bug. I just really like the face and want to use it! <3

**Comment by JoLiKMC** [comment]
I can confirm this.  The default human female player model only has the default 15 faces while the two Vanilla NPC skins, "Scarlet Inquisitor" and "Scholomance Student", are available as donation rewards.  The skin displayed in the linked image does not match any of these skins and is, therefore, unavailable at this time.

**Comment by slowtorta** [comment]
Fixed in the next revision. We can't add new skin types in the selection menu without the client update, but it'll be available as donation reward or a reputation reward in the later content :)
