### ISSUE TITLE
Pyrewood Ambush event does not start

### ISSUE THREAD

**Issue by Tinyfin-github** [slowtorta/turtlewow-bug-tracker#1540]
Pyrewood Ambush event does not start

https://database.turtle-wow.org/?quest=452

https://screencast-o-matic.com/watch/c3iebpV0ZIK

**Comment by slowtorta** [comment]
https://github.com/slowtorta/turtlewow-bug-tracker/issues/1520

**Comment by geojak** [comment]
@slowtorta 
this issue is not fixed and i also dont thing the one you linked is a duplicate.

this issue here is that the scripted qeust event/patrol doesnt work.

the one that was linked is about the npcs not truning into werewolfes at night and the howling.
