### ISSUE TITLE
SoC does not benefit from Human weapon skill racial

### ISSUE THREAD

**Issue by PizzaOfHut** [slowtorta/turtlewow-bug-tracker#1543]
**Please, provide a clear description what the bug is:**

A Human Ret Pally using a sword or mace with 3/3 Precision and a total of 3% melee hit on gear still has a 3% chance for the proc on SoC to miss.

**Steps to reproduce the behavior with as much detail as possible:**

1. Spec a Human Pally into 3/3 Precision and SoC
2. Equip a gearset that includes a sword or mace, and an additional 3% melee hit.
3. Attack the level 63 training dummy in SW for 3 minutes with SoC up.

**IDs of affected creatures, items, quests or spells with a link to the relevant page:**

Spell: https://database.turtle-wow.org/?spell=20920

**Expected behavior. Describe how it should work:**

A Pally with 305 skill in his equipped weapon, 3/3 Precision, and an additional 3% melee hit from gear should never have an SoC proc miss against a raid boss.

**Comment by Giperion** [comment]
@PizzaOfHut Can't reproduce with newest revision of core. I followed steps and according to code - miss chance for Seal of Command is now 0%.
Spell still can be dodged however.
