### ISSUE TITLE
Portal at Rut'theran Village / Darnasuss not working after running Cresecent Grove (requires relog)

### ISSUE THREAD

**Issue by Riverleafs** [slowtorta/turtlewow-bug-tracker#1544]
**Please, provide a clear description what the bug is:**

Unable to use the portal at Rut'theran Village or Darnassus after running Crescent Grove - must relog in order for it to work.

**Steps to reproduce the behavior with as much detail as possible:**

1. Enter Crescent Grove
2. Exit Crescent Grove
3. Try to use portal to Rut'theran from Darnassus or the other way around
4. Relogging solves the issue

**IDs of affected creatures, items, quests or spells with a link to the relevant page:**

Dungeon: Crescent Grove

**Expected behavior. Describe how it should work:**

You should be able to use the portal without having to relog

**Comment by slowtorta** [comment]
Sorry, cannot reproduce, working as intended.
