### ISSUE TITLE
Gaffer Jacks is not available for high elfs

### ISSUE THREAD

**Issue by Gurky-Kronos** [slowtorta/turtlewow-bug-tracker#1546]
**Please, provide a clear description what the bug is:**
High elfs cannot take the quest Gaffer Jacks

**Steps to reproduce the behavior with as much detail as possible:**

1. Gaffer Jacks cannot be picked up from the quest giver.

**IDs of affected creatures, items, quests or spells with a link to the relevant page:**

[NPC: https://database.turtle-wow.org/?npc=](https://database.turtle-wow.org/?npc=3666)
[Quest: https://database.turtle-wow.org/?quest=](https://database.turtle-wow.org/?quest=1579)

**Expected behavior. Describe how it should work:**

High Elfs should be able to take this quest seeing all other alliance races can.

**Comment by geojak** [comment]
I finished gaffer Jack's on my highelf Paladin. Maybe you don't have the required fishing skill for it to show up. It's rather high
