### ISSUE TITLE
Shadow word pain issue in ZG

### ISSUE THREAD

**Issue by Alicemay99** [slowtorta/turtlewow-bug-tracker#1547]
**Please, provide a clear description what the bug is:**
Shadow word pain on crocs is only lasting ten seconds, not 18 as per the spell

**Steps to reproduce the behavior with as much detail as possible:**

1. Cast shadow word pain on croc
2. Count to twenty
3. Falls off at 10 not 18

**IDs of affected creatures, items, quests or spells with a link to the relevant page:**

NPC: https://database.turtle-wow.org/?npc=
Item: https://database.turtle-wow.org/?item=
Quest: https://database.turtle-wow.org/?quest=
Spell: https://database.turtle-wow.org/?spell=
Object: https://database.turtle-wow.org/?object=

**Expected behavior. Describe how it should work:**
Cast on croc, lasts 18 seconds

**Comment by redmagejoe** [comment]
Tested on latest version, and ticks for the full 18 second duration.

Fixed.
