### ISSUE TITLE
Problems with Blacksmith Skills: Copper Knuckles

### ISSUE THREAD

**Issue by JoLiKMC** [slowtorta/turtlewow-bug-tracker#1548]
I recently started to raise a Blacksmith character.  When said character was a sufficiently high level, I noticed that there was a new recipe available from a trainer: Copper Knuckles.  This recipe has three problems with it.

- When learning the recipe from a trainer, there is a **two-second cast time**.  If the player moves while learning the recipe, **they are not refunded their spent money**.
(Special thanks to someone on _Discord_ for mentioning the second part.)
- The item requires **a very low amount of skill** to create, meaning that the recipe is **already grey** by the time it's obtainable.
- ~~The item **requires Level 5** to equip, but characters **can't learn Fist Weapons until Level 10**.~~
I made a mistake.  Players can learn Fist Weapons at Level 1 but normally, the earliest fist weapon is found at Level 10.
–

**Steps to reproduce the behavior with as much detail as possible:**
1. Create a character and have them learn Blacksmithing up to Skill Level 50.
2. Go to any Blacksmith Trainer and have your character learn Copper Knuckles.
3. A black cast bar will appear for two seconds before the skill is learned.
4. Once the skill is learned, open the Blacksmithing menu.  "Copper Knuckles" will be gray, meaning no skill points can be earned from it.
5. Hover the cursor over the item in the Blacksmithing menu.  It will say "Requires Level 5".  ~~Players cannot learn Fist Weapons until Level 10.~~  Normally, the lowest level fist weapon is the Brass Knuckles at Level 10.

**IDs of affected creatures, items, quests or spells with a link to the relevant page:**

Item: https://database.turtle-wow.org/?item=65010 (Copper Knuckles)
Spell: https://database.turtle-wow.org/?spell=2018 (Apprentice Blacksmithing)

**Expected behavior. Describe how it should work:**
- Learning _any_ recipe from a trainer should be **instant** and **uninterruptable**.
- Recipes learned at-level should **always grant an increase in skill** when crafting.
- ~~Copper Knuckles should **require Level 10** to equip _or_ Fist Weapons should be learnable at a lower level.~~
~~(The latter would not be implemented until _Cataclysm_ on Retail, however.)~~
(Never mind.  I made a mistake.)

**Comment by geojak** [comment]
same problem on the tailoring augerer set

**Comment by slowtorta** [comment]
Casting time will be fixed on the next update, the skill values in the patch 1.16.1 :)

**Comment by JoLiKMC** [comment]
It's probably worth noting (but not re-opening the issue) that actually _making_ the Copper Knuckles takes a good 30 seconds, too.  That's probably more realistic than whipping it up in five, but man, that's a heck of a discrepancy compared to most other weapon craft time.
