### ISSUE TITLE
Patchwerk blocking ranged attacks too much 

### ISSUE THREAD

**Issue by Velite12** [slowtorta/turtlewow-bug-tracker#155]
![image](https://user-images.githubusercontent.com/45871932/125177343-04bab680-e1a9-11eb-823e-324175191d66.png)

NPC=https://database.turtle-wow.org/?npc=16028

It seems that patchwerk is blocking much of ranged attack damage for some reason, which is really reducing hunter dps on the boss. Would like to know if there is an issue here.

**Comment by OrnsteinHunter** [comment]
some more screenshots.

![blocked1](https://user-images.githubusercontent.com/87275647/125203156-f918cf80-e23c-11eb-823d-3701b8fe1e70.png)
![blocked2](https://user-images.githubusercontent.com/87275647/125203162-fcac5680-e23c-11eb-8f4b-84a024ea7f3a.png)

**Comment by slowtorta** [comment]
He's okay. Stop being like this!
