### ISSUE TITLE
Plate Scraps not Dropping Abnormally

### ISSUE THREAD

**Issue by afizzler** [slowtorta/turtlewow-bug-tracker#1553]
It seems like plate scraps in naxxramas drop way less frequently than stated on the turtle wow database. I want to confirm if the database is showing the wrong values, or it is an actual bug.

https://database.turtle-wow.org/?item=22375

**Steps to reproduce the behavior with as much detail as possible:

1. Spawn a certain number of naxxramas mobs of one type
2. Kill all of them
3. Loot them

**Comment by slowtorta** [comment]
The online DB is displaying values from the actual server. The % is the same as on any other Vanilla server :)
