### ISSUE TITLE
NPC sells Schematic: Ice Deflector with no restock time

### ISSUE THREAD

**Issue by Shellyoung** [slowtorta/turtlewow-bug-tracker#1555]
**Please, provide a clear description what the bug is:**
The game allow a player to buy an unlimited amount schematics with no restock time.
Screenshot: [https://i.imgur.com/r5pXgqG.png](https://i.imgur.com/r5pXgqG.png)

**Steps to reproduce the behavior with as much detail as possible:**
1. Trade with Rizz Loosebolt at Alterac Mountains

**IDs of affected creatures, items, quests or spells with a link to the relevant page:**
NPC: https://database.turtle-wow.org/?npc=2684
Item: https://database.turtle-wow.org/?item=13308

**Expected behavior. Describe how it should work:**
The stock of Schematic: Ice Deflector should be limited, according to https://classic.wowhead.com/npc=2684/rizz-loosebolt.

**Comment by slowtorta** [comment]
Fixed in the next revision.
