### ISSUE TITLE
Felhunter's Spell Lock not Counterspelling

### ISSUE THREAD

**Issue by tocopherylacetate** [slowtorta/turtlewow-bug-tracker#1556]
**Please, provide a clear description what the bug is:**
The warlock's level 30 pet Felhunter's Spell Lock does not silence the opponent's school when used during an enemy cast. It only global silences for 3 seconds.

**Steps to reproduce the behavior with as much detail as possible:**

1. Summon felhunter
2. Have an enemy player cast a non-instant offensive spell
3. Have felhunter use Spell Lock
4. Notice that the enemy can still cast the entire school related to the silenced spell after 3 seconds

**IDs of affected creatures, items, quests or spells with a link to the relevant page:**

NPC: https://database.turtle-wow.org/?npc=417
Item: https://database.turtle-wow.org/?item=16389
Quest: https://database.turtle-wow.org/?quest=
Spell: https://database.turtle-wow.org/?spell=19647
Object: https://database.turtle-wow.org/?object=

**Expected behavior. Describe how it should work:**
A felhunter's spell lock should silence the related school for 8 seconds if used during an enemy cast.

Thanks in advance, have a good day

**Comment by ratkosrb** [comment]
Cannot reproduce the issue. The school of the spell I was casting gets locked for 8 seconds after getting interrupted by a Felhunter pet.

https://streamja.com/nzJkz
