### ISSUE TITLE
Amplify Curse not working with Curse of Exhaustion

### ISSUE THREAD

**Issue by tocopherylacetate** [slowtorta/turtlewow-bug-tracker#1557]
**Please, provide a clear description what the bug is:**
When casting Amplify Curse, then casting Curse of Exhaustion, the Amplify Curse buff stays on the player and curse of exhaustion lands on the enemy, not consuming the amp.curse buff nor adding 20% to the effect
**Steps to reproduce the behavior with as much detail as possible:**

1. Cast Amplify Curse
2. Cast Curse of Exhaustion
3. Notice Amplify Curse buff stays on player
4. Also notice that Curse of Exhaustion tooltip is stuck at 10%

**IDs of affected creatures, items, quests or spells with a link to the relevant page:**

Spell:
Amplify Curse 
https://database.turtle-wow.org/?spell=18288
Curse of Exhaustion(s)
https://database.turtle-wow.org/?spell=18310
https://database.turtle-wow.org/?spell=18311
https://database.turtle-wow.org/?spell=18312
https://database.turtle-wow.org/?spell=18313

Yes there are 4 different 'ranks' of it depending on the talents and none of them work with Amplify Curse.

**Expected behavior. Describe how it should work:**
Amplify Curse into Curse of Exhaustion should add 20% slow to the Curse of Exhaustion debuff and be consumed in the process.

Thanks in advance, have a good day

**Comment by Daribon** [comment]
Known vmangos bug: https://github.com/vmangos/core/issues/1307
