### ISSUE TITLE
Stratholme bug (Eye of Naxxramas summoning too many Gargoyles)

### ISSUE THREAD

**Issue by Riverleafs** [slowtorta/turtlewow-bug-tracker#1558]
**Please, provide a clear description what the bug is:**

Eye of Naxxramas (NPC) inside of Stratholme

**Steps to reproduce the behavior with as much detail as possible:**

1. Find Eye of Naxxramas
2. Do not kill it
3. See how it keeps summoning Gargoyles that do not despawn.

**IDs of affected creatures, items, quests or spells with a link to the relevant page:**

NPC: https://database.turtle-wow.org/?npc=10411
Item: https://database.turtle-wow.org/?item=
Quest: https://database.turtle-wow.org/?quest=
Spell: https://database.turtle-wow.org/?spell= 
Object: https://database.turtle-wow.org/?object=

**Expected behavior. Describe how it should work:**

It is supposed to summon **_### ONLY 2 gargoyles per aggro_** (after yelling 2-3 times), and not an unlimited amount every 5-10 seconds while in combat and casting. It is impossible to do the dungeon right now (if you do not kill them fast enough, once they spot you) as they do not despawn the gargoyles either. Unsure whether they are supposed to despawn or not, but only 2 should be summoned.

**Comment by geojak** [comment]
Same problem in DM North. Had an eye spawn 2x2 void walkers on us
