### ISSUE TITLE
Icepoint Rock and Kaneq'nuun mobs drop

### ISSUE THREAD

**Issue by Gasan918** [slowtorta/turtlewow-bug-tracker#1559]
**Please, provide a clear description what the bug is:**

Icepoint Rock and Kaneq'nuun mobs

1) Ice Crawler
2) Icepoint Whiteclaw
3) Tarqsiku

drops only money as if they are humanids.
![image](https://user-images.githubusercontent.com/96973359/178064175-f3b262be-90bd-4994-a80e-41fa353882ef.png)

![image](https://user-images.githubusercontent.com/96973359/178064013-bb12fecc-dbc9-4093-8ff4-3c37f9c6a693.png)
![image](https://user-images.githubusercontent.com/96973359/178064086-9ebdaa30-90cc-4077-89ec-ccad0683e9c2.png)

**Steps to reproduce the behavior with as much detail as possible:**

Come to "Vanilla Nordskol" and loot those mobs

**IDs of affected creatures, items, quests or spells with a link to the relevant page:**

NPC: https://database.turtle-wow.org/?npc=60605, 60545, 60544

**Expected behavior. Describe how it should work:**

They should have

1) Crab
2) Bear
3) Elemental

droplists.

**Comment by Kruxis** [comment]
Thanks for the report, we adjusted the loot slightly =)
