### ISSUE TITLE
into the jaws sfk qeust item in tirisfal upladns

### ISSUE THREAD

**Issue by geojak** [slowtorta/turtlewow-bug-tracker#1560]
**Please, provide a clear description what the bug is:**
![WoWScrnShot_070822_183943](https://user-images.githubusercontent.com/25199983/178064878-b4dce2ad-8d65-4145-9fe0-eeb3896c3efd.jpg)

this is a custom turle wow qeust for sfk

its not marked as dungeon qeust, nor elite, or is in sfk qeust category.

even more so, the quest item i looted in a pile of dirt at the screenshtot location in tirisfal uplands entrance

**Comment by slowtorta** [comment]
Fixed in the next revision.
