### ISSUE TITLE
[Vanilla Bug] Thorvald Deepforge in Loch Modan Sells Nothing

### ISSUE THREAD

**Issue by JoLiKMC** [slowtorta/turtlewow-bug-tracker#1561]
There's a vendor in the Valley of Kings in Loch Modan that is marked as a weapon / equipment vendor, but when the player clicks on him, he has absolutely nothing to sell.  He has a blacksmithing quest, "[12] Supplying the Front", but otherwise?  He's just an empty vendor.

**Steps to reproduce the behavior with as much detail as possible:**
1. Take a character to the south-west Loch Modan.
2. Find the NPC "Thorvald Deepforge" at coordinates **23.6, 74.3**.
3. Interact with Thorvald and open the vendor dialogue.  He will have nothing to sell.

**IDs of affected creatures, items, quests or spells with a link to the relevant page:**
NPC: https://database.turtle-wow.org/?npc=6030 (Thorvald Deepforge)

**Expected behavior. Describe how it should work:**
Surprisingly, Thorvald Deepforge has _always_ been like this since he was added to the game in v1.11.1.7272.  Even in _World of Warcraft Classic_, Thorvald is an "empty vendor" with a blacksmithing quest.  So, technically speaking… there's nothing wrong with him, at all.

When _World of Warcraft: Cataclysm_ rolled around on Retail, the NPC was updated, slightly, and began to sell [various Level 4 / 5 weapons](https://www.wowhead.com/npc=6030/thorvald-deepforge#sells).  I would consider updating his inventory accordingly, but obviously, leaving him empty-handed isn't hurting anything.

**Comment by slowtorta** [comment]
Fixed in the next revision!
![image](https://user-images.githubusercontent.com/66763404/178116222-578057d1-f003-4801-8915-c52b3001c4f4.png)
