### ISSUE TITLE
Ravager cannot proc off itself

### ISSUE THREAD

**Issue by 9600bauds** [slowtorta/turtlewow-bug-tracker#1562]
**Please, provide a clear description what the bug is:**
Ravager is a weapon that has a chance to cast Bladestorm, causing the user to spin around and do AoE damage every 3 seconds.
However, each hit that you get on a mob by means of this AoE damage is supposed to still have a chance to proc Ravager. Currently it does not work like that in this server.

**Steps to reproduce the behavior with as much detail as possible:**

1. Get Ravager
2. Stand next to 100 mobs
3. Get Ravager to proc
4. Expect it to constantly reproc itself from all the hits it's causing (in this example, each tick of the proc would cause 100 hits, all of which would have the normal chance to start the proc again)
5. It never reprocs off itself, proc always ends at 9 seconds

**IDs of affected creatures, items, quests or spells with a link to the relevant page:**
Item: https://database.turtle-wow.org/?item=7717

**Expected behavior. Describe how it should work:**
It should proc off itself, resulting in the proc "refreshing" itself commonly

**Comment by 9600bauds** [comment]
If anyone knows, it would be helpful to know whether it can also proc Crusader and other similar on-hit enchants.

**Comment by burner1024** [comment]
Ravager definitely did not proc off itself in Classic, not sure about vanilla, but probably also not.

**Comment by 9600bauds** [comment]
It surprises me that anyone would say that considering it's pretty obvious when using the weapon, and is in fact pretty much the whole point of it.

Regardless, some proof is in order, this is footage from Classic, fairly self-explainatory:

https://user-images.githubusercontent.com/6526157/180597171-74130f1e-b08c-464c-b06d-dd64446ca091.mp4

https://user-images.githubusercontent.com/6526157/180597181-c5400d21-58a6-4811-b86c-1eec5ad4cdd9.mp4

**Comment by burner1024** [comment]
Hm, looks right. It doesn't prove that each of 100 hits of a tick can reproc, though. Just that it can reproc.

**Comment by slowtorta** [comment]
Related to https://github.com/slowtorta/turtlewow-bug-tracker/issues/1975
