### ISSUE TITLE
Mother's Milk (Quest)

### ISSUE THREAD

**Issue by Riverleafs** [slowtorta/turtlewow-bug-tracker#1563]
**Please, provide a clear description what the bug is:**

Not able to turn in the quest even with the "Mother's Milk" buff on you (quest ID: 4866). Supposed to be able to turn it in at Ragged John once you've obtained the debuff from inside a dungeon.

**Steps to reproduce the behavior with as much detail as possible:**

1. Go to the boss Mother Smolder Web (10596) and obtain Mother's milk debuff (16468)
2. Go to Ragged John in Burning Steppes
3. Turn in the quest and see how the dialogue box is not there.

**IDs of affected creatures, items, quests or spells with a link to the relevant page:**

NPC: https://database.turtle-wow.org/?npc= 10596
Item: https://database.turtle-wow.org/?item=
Quest: https://database.turtle-wow.org/?quest= 4866
Spell: https://database.turtle-wow.org/?spell= 16468
Object: https://database.turtle-wow.org/?object=

**Expected behavior. Describe how it should work:**

You should be able to turn in the quest Mother's Milk (4866) after having the debuff: Mother's milk (16468) on you and the NPC Ragged John (10596) through a dialogue box.

**Comment by geojak** [comment]
i finished the quests, maybe you didnt get milked?

**Comment by banallwowbots** [comment]
Had the same issue on some of my alts. They simply can't turn in the quest. Retaking the quest don't help.

And yes, it won't work even with the milked debuff.

**Comment by ratkosrb** [comment]
Can't reproduce the issue. You need to have the "Mother's Milk" debuff on you and when you talk to him and the "Milk me, John" option will appear.
