### ISSUE TITLE
rot hide ichor dropchance too high

### ISSUE THREAD

**Issue by geojak** [slowtorta/turtlewow-bug-tracker#1566]
**Please, provide a clear description what the bug is:**

the rot hide ichor drops far too esaily (80%), makign the qeusts a bit too easy to complete. i dont mind making compelting stuff easier on twow, but this is too much imo

**IDs of affected creatures, items, quests or spells with a link to the relevant page:**

https://database.turtle-wow.org/?item=3236
80%

**Expected behavior. Describe how it should work:**

https://classic.wowhead.com/item=3236/rot-hide-ichor
30%

**Comment by slowtorta** [comment]
Fixed in the next revision.
