### ISSUE TITLE
There Are No Spirit Healers in the Scarlet Enclave (Eastern Plaguelands)

### ISSUE THREAD

**Issue by JoLiKMC** [slowtorta/turtlewow-bug-tracker#1567]
As stated, there are no Spirit Healers in the Scarlet Enclave.  This means that if a player dies within New Avalon or any regions within the zone, they don't get teleported anywhere and simply spawn as ghosts right on top of their corpse.  One could argue that this is a "good bad bug", but a bug it is, all the same.

**Steps to reproduce the behavior with as much detail as possible:**

1. Go to the Scarlet Enclave zone southeast of the Eastern Plaguelands.  Enter New Avalon.
2. Run out of Health and release your spirit to the nearest graveyard.
3. Watch as your spirit stays right where your body was.

**Expected behavior. Describe how it should work:**
Players should respawn near Hope's Light Chapel, or maybe even someplace within New Avalon, itself.

**Further details:**
Okay, so hear me out on this one.  I was taking a very roundabout path to get to Light's Hope Chapel.  Specifically, I jumped off the Thandol Span between the Wetlands and the Arathi Highlands and swam around.  I arrived at King's Harbor and headed into New Avalon with every intention of dying and respawning at the 'Healer.  When I was obliterated by a Scarlet Enchanter, I noticed that my ghost appeared where I died instead of at Light's Hope Cathedral.  This struck me as odd because I took a similar trip with another character where I went around the _north_ side of the Eastern Plaguelands.  When I died in the Scarlet Enclave, that time, I ended up respawning at Light's Hope.

No idea.  None at all.  Especially since King's Harbor is classified as being part of the Eastern Plaguelands rather than the Scarlet Enclave.

**Comment by Dragunovi** [comment]
This zone is currently under production and not open to the general playerbase, so a spirit player and respawn location hasn't been placed yet. This issue will be fixed when the zone is fully complete and open to experience. In the meanwhile in the case that you get stuck somewhere feel free to open a ticket for our gamemasters to handle the issue swiftly.
