### ISSUE TITLE
Invisible Wall Near King's Harbor (Eastern Plaguelands)

### ISSUE THREAD

**Issue by JoLiKMC** [slowtorta/turtlewow-bug-tracker#1568]
There is a large, invisible, rectangular wall or "box" situated just south of King's Harbor in the Eastern Plaguelands.

**Steps to reproduce the behavior with as much detail as possible:**

1. Arrive at King's Harbor from any direction.
2. Swim south along the rocky hills and get to around **61.8, 27.3** (in _Cartographer_ coordinates) on the World Map.
![TWoW_Eastern Kingdoms 61-8 27-3](https://user-images.githubusercontent.com/102710555/178332203-5d34fa31-14ef-481c-9213-994d9dc1895f.png)
3. Behold the spectacle of swimming in place against a solid wall of nothing!

**Expected behavior. Describe how it should work:**
There should be no box.  It's not blocking access to anything.  It just kind of slides out from the mountain and sticks out into the sea.  Here's a picture of where one corner of it ends, facing King's Harbor.
![WoWScrnShot_071122_060700](https://user-images.githubusercontent.com/102710555/178332641-3a242f38-aabc-40db-bd15-04d06c130a04.jpg)

**Comment by Zmitrok1984** [comment]
Here is unfinished zone where in future will be new raid Scarlet Citadel. Nothing to do here while zone isn't ready - because it will be necessary to save any curious person who will come here and fall under the textures

**Comment by slowtorta** [comment]
That's intended :)

**Comment by JoLiKMC** [comment]
Okay, but… the invisible box doesn't do anything.  It's not even in the way.  It just sticks out so far and can be swam around.  Possibly even swam _under_.  It serves no purpose at all.
