### ISSUE TITLE
A Different Shade of Red illusion does not work

### ISSUE THREAD

**Issue by Tinyfin-github** [slowtorta/turtlewow-bug-tracker#1569]
https://database.turtle-wow.org/?quest=80729 A Different Shade of Red illusion does not work

https://database.turtle-wow.org/?item=53003 When applying the scarlet illusion nothing happens

**Comment by CasualNerdity** [comment]
Using the Illusion: Scarlet Crusade does not visibly change the character, nor does it change the Scarlet Crusade faction to Friendly, but it does use up one charge from the item and causes a shapeshift state, throwing the "You are in shapeshift form" error when trying to mount.

**Comment by LachtanCesky** [comment]
Same issue for me:
https://database.turtle-wow.org/?quest=80729 A Different Shade of Red illusion does not work

https://database.turtle-wow.org/?item=53003 When applying the scarlet illusion nothing happens

**Comment by slowtorta** [comment]
Duplicate for https://github.com/slowtorta/turtlewow-bug-tracker/issues/2222
