### ISSUE TITLE
Blacksmith Profession - Missing Recipe (Rough Grinding Stone)

### ISSUE THREAD

**Issue by AyleeJenn** [slowtorta/turtlewow-bug-tracker#157]
**Please, provide a clear description what the bug is:**
Missing recipe Bug for the recipe "Rough Grinding Stone". The recipe is not automatically awarded to the blacksmith upon learning the profession

**Steps to reproduce the behavior with as much detail as possible:**

1. Learning the Blacksmith Profession from the blacksmith in Stormwind, Dwarven district (instead of Goldshire)
2. N/A
3. N/A

**IDs of affected creatures, items, quests or spells with a link to the relevant page:**

NPC: https://database.turtle-wow.org/?npc=
Item: https://database.turtle-wow.org/?item=3470
Quest: https://database.turtle-wow.org/?quest=
Spell: https://database.turtle-wow.org/?spell=
Object: https://database.turtle-wow.org/?object=

**Expected behavior. Describe how it should work:**
When a character learns the blacksmith profession from -any- blacksmith trainer, the recipe for "Rough Grinding Stone" should automatically be awarded.

**Comment by slowtorta** [comment]
Wrong. This recipe requires BM Skill 25 to be learnt, according to Classic DB: https://classic.wowhead.com/spell=3320/rough-grinding-stone#recipes

**Comment by AyleeJenn** [comment]
I stand corrected. Apologies.
