### ISSUE TITLE
Food not restoring the listed value

### ISSUE THREAD

**Issue by CasualNerdity** [slowtorta/turtlewow-bug-tracker#1570]
**Please, provide a clear description what the bug is:**
Festival Dumplings tooltip states it restores 4% of max health and mana over 25 seconds, 100% if you wait the entire duration. I have noticed that they only leave me with 75% of my max mana after spending the full 25 seconds eating, the same value as Conjured Mana Oranges, Candy Corn, Lollipops, and Candy Bar from the Hallows End seasonal event.
**Steps to reproduce the behavior with as much detail as possible:**

1. Run down to lowest possible mana (36/3855).
2. Start eating Festival Dumpling.
3. After the final tick, end up with less than 100% mana (3468/3855)

**IDs of affected creatures, items, quests or spells with a link to the relevant page:**
Item: https://database.turtle-wow.org/?item=21537

**Expected behavior. Describe how it should work:**
Based on the tooltip, I expected to be at 100% mana after the full duration.

**Comment by Gurky-Turtle** [comment]
Should be fixed next update.
