### ISSUE TITLE
Scarlet Cleric casting Mind Blast on himself/herself (Tyr's Hand)

### ISSUE THREAD

**Issue by Riverleafs** [slowtorta/turtlewow-bug-tracker#1571]
**Please, provide a clear description what the bug is:**
Scarlet Cleric at Tyr's Hand casts Mind blast at herself/himself. Should cast at player.
**Steps to reproduce the behavior with as much detail as possible:**

1. Find a Scarlet Cleric at Tyr's Hand
2. Attack the NPC and damage it a little
3. See how the Cleric casts Mind Blast on herself

**IDs of affected creatures, items, quests or spells with a link to the relevant page:**

NPC: https://database.turtle-wow.org/?npc= 9449
Item: https://database.turtle-wow.org/?item=
Quest: https://database.turtle-wow.org/?quest=
Spell: https://database.turtle-wow.org/?spell=
Object: https://database.turtle-wow.org/?object=

**Expected behavior. Describe how it should work:**

Should cast Mind Blast on player.

**Comment by slowtorta** [comment]
Fixed in the next revision.
