### ISSUE TITLE
Princess Tempestria's corpse disappears EXTREMELY quickly, taking all loot with it

### ISSUE THREAD

**Issue by 9600bauds** [slowtorta/turtlewow-bug-tracker#1572]
**Please, provide a clear description what the bug is:**
Princess Tempestria is a world boss that spawns in Winterspring as part as the Elemental Invasion.
She functions normally, except that, for some reason, her corpse despawns EXTREMELY fast. So fast that I was unable to loot the BOPs fast enough, she disappeared before I could click "accept" on the binding notification.
I don't know if this issue also happens with the other elemental invasion bosses (Baron Charr etc), but it would be worthwhile to check.
My guess is that this could be an issue with the code that ends the elemental invasion (boss dies -> call EndElementalInvasion() -> the first thing EndElementalInvasion() does is despawn the boss' corpse) rather than an issue inherent to the mob itself.

**Steps to reproduce the behavior with as much detail as possible:**

1. Go to Winterspring while the elemental invasion event is active.
2. Kill Princess Tempestria.
3. Notice how her corpse will despawn unusually fast, taking all loot with it

**IDs of affected creatures, items, quests or spells with a link to the relevant page:**

NPC: https://database.turtle-wow.org/?npc=14457

**Expected behavior. Describe how it should work:**
The corpse should stay up for, like at least a couple minutes so you don't easily lose all loot from it

**Comment by slowtorta** [comment]
Fixed in this commit: https://github.com/slowtorta/turtle-wow/commit/918790683eb9f4ee6ba60172c3bd1ef59c06ccdb
