### ISSUE TITLE
Matter Of Trust quest is not shareable

### ISSUE THREAD

**Issue by 9600bauds** [slowtorta/turtlewow-bug-tracker#1573]
**Please, provide a clear description what the bug is:**
A common problem with Turtle WoW quests is that they are not marked as shareable, even though it seems that they should be.
Usually when a vanilla quest is not shareable it's because it's part of a chain, or because it has a special requirement in the form of starting from an item or requiring you to take an item from the questgiver to do the quest. Many TurtleWoW quests are simply not shareable for no apparent reason (my guess is that it's probably just the default when making a quest from scratch  and it goes unnoticed?).

One example of a nonshareable TurtleWoW quest is Matter of Trust: https://database.turtle-wow.org/?quest=60070 which doesn't seem to have any reason for not being shareable

**Steps to reproduce the behavior with as much detail as possible:**

1. Accept the quest
2. Try to share it
3. Share button greyed out
4. Sadness

**IDs of affected creatures, items, quests or spells with a link to the relevant page:**

Quest: https://database.turtle-wow.org/?quest=60070

**Expected behavior. Describe how it should work:**
Like Vanilla quests that don't have special requirements, it should be shareable.

**Comment by slowtorta** [comment]
Fixed in the next revision.
