### ISSUE TITLE
Most, if not all, quests in Gillijim's Isle don't give money instead of XP when completed at lvl60

### ISSUE THREAD

**Issue by 9600bauds** [slowtorta/turtlewow-bug-tracker#1574]
**Please, provide a clear description what the bug is:**
When you do a quest at lvl60, they are supposed to give you extra money to make up for the XP that you're not getting because of being max level, at a rate of 6 copper per XP point. Almost all (if not all?) vanilla quests work like this.
However, a common problem with Turtle WoW quests is that they don't do that, they just give 0 gold or their normal amount of gold when completed at lvl60. This is because their RewMoneyMaxLevel field needs to be set manually.
Here's an example of one such quest that doesn't have a RewMoneyMaxLevel value despite seeming like it should: https://database.turtle-wow.org/?quest=40196
![firefox_22-07-12-23-36-20](https://user-images.githubusercontent.com/6526157/178638873-136d1158-29c6-4dd7-ac35-14bc6fa3e6de.png)

...compare to a normal Vanilla quest chosen at random:
![firefox_22-07-12-23-37-05](https://user-images.githubusercontent.com/6526157/178638951-bef95eac-1a57-47cf-a950-e0ea2ab5301e.png)

**Steps to reproduce the behavior with as much detail as possible:**

1. Do vanilla quests at lvl60
2. Notice how they give extra gold at a rate of 6 copper per xp that they would have given
3. Do Gillijim's Isle quests at lvl60
4. Notice how you get no gold or just the normal gold for a non-60

**IDs of affected creatures, items, quests or spells with a link to the relevant page:**

Quest: https://database.turtle-wow.org/?quest=40196

**Expected behavior. Describe how it should work:**
They should give extra gold for lvl60 characters.

**Comment by slowtorta** [comment]
Fixed in the next revision.
