### ISSUE TITLE
Black Morass Aqir Larva mobs glitched AoE life drain spam (instant party wipe) + others.

### ISSUE THREAD

**Issue by Beertaster** [slowtorta/turtlewow-bug-tracker#1575]
**Please, provide a clear description what the bug is:**
Aqir Larva spams AoE Life drain 10-20 times a server tick it seems. Wiping the party intantly.
When the second boss Harbinger Aph'ygth spawns larva the party instantly wipes. We had to skip this boss and sneak around him after 2-3 attempts.

Also when Fighting Infinite Chromie. Her mana burn would delete my mana bar at the start of the fight. I was useless as a warlock. Can't say for sure its a bug, man was it punishing. We couldn't get her past 60% adds would murder us on every attempt. and despite chugging major mana pots If had no mana, healer to focused n tank, healthstone + bandages didn't help either.
**Steps to reproduce the behavior with as much detail as possible:**

1. Be in melee range.
2. 
3. 

**IDs of affected creatures, items, quests or spells with a link to the relevant page:**

NPC: https://database.turtle-wow.org/?npc= https://database.turtle-wow.org/?npc=65115
NPC: https://database.turtle-wow.org/?npc= https://database.turtle-wow.org/?npc=65114
Item: https://database.turtle-wow.org/?item=
Quest: https://database.turtle-wow.org/?quest=
Spell: https://database.turtle-wow.org/?spell=
Object: https://database.turtle-wow.org/?object=

**Expected behavior. Describe how it should work:**

To attack once a second and not 10 times a second, or more.

**Comment by gorxen** [comment]
Confirming, this boss requieres a MANDATORY frost mage to kill (to be able to hold the larvas in place for aoe) and I find that completely unfair, my guild friends and I decided to not do this place anymore until something about this is done.

**Comment by Zmitrok1984** [comment]
Frost mag isn't necessary. There is a rock ledge at the battle site. If you kite the boss on him, and when the Larvas  appear - everyone who was there, jump off, then they will crawl along a long path. And while they crawl - kill them all.

**Comment by slowtorta** [comment]
Fixed in the next revision.
