### ISSUE TITLE
30-Second Riding Gryphon (Goldshire) / Wind Rider (Razor Hill) Emote Problems

### ISSUE THREAD

**Issue by JoLiKMC** [slowtorta/turtlewow-bug-tracker#1577]
After completing the Alliance quest "[A Matter of Trust](https://database.turtle-wow.org/?quest=60070)" in Goldshire or the Horde quest "[Red Skies of Durotar](https://database.turtle-wow.org/?quest=40298)" in Razor Hill, the player is allowed to pay and use a flying mount for about 30 seconds.  If the player doesn't have the required food item, the NPC plays an emote reading:

"The [gryphon / wyvern] recognizes you and doesn't seem to be satisfied. Perhaps a handful of [famous Dwarven Mild / Mutton Chops] could do some good?"

Additionally, the emote always uses "second person" phrasing, meaning that Player A can initiate it and Players B, C, and D will all see "recognizes **you**" instead of "recognizes **[player name]**".

**Steps to reproduce the behavior with as much detail as possible:**
1. Complete the quest "A Matter of Trust" (Alliance) / "Red Skies of Durotar" (Horde)
2. Attempt to ride Kelton's Riding Gryphon (Alliance) without any Dwarven Mild (or)
Attempt to ride Bristlefur (Horde) without any Mutton Chops
3. The gryphon / wyvern will play an emote to everyone within range regardless of who initiated it.

**IDs of affected creatures, items, quests or spells with a link to the relevant page:**
NPC: https://database.turtle-wow.org/?npc=51562 (Kelton's Riding Gryphon)
NPC: https://database.turtle-wow.org/?npc=60539 (Bristlefur)

**Expected behavior. Describe how it should work:**
One of two things should happen.  Either…

- This emote should play only for the player who initiated it.
- Two different emotes should play – one for the player and one for everyone nearby.

For the latter, the current emote can easily be modified to use third-person terms:
"The [gryphon / wyvern] recognizes [player name] and doesn't seem to be satisfied. Perhaps a handful of [famous Dwarven Mild / Mutton Chops] could do them some good?"

Personally, though?  I recommend the former.  I recently found out that a persistent player can actually **fill the chat log** with the emote if they keep clicking without the requested item.  Just a thought.

**Related issues:**
- #1578

**Comment by slowtorta** [comment]
Fixed in the next revision.

**Comment by JoLiKMC** [comment]
For the curious, this was fixed by removing the emotes and replacing it with a "status" text message:
"Dwarven Mild / Mutton Chop required."

Works for me~
