### ISSUE TITLE
Dark Iron Scrapping - Starter High Elf quest issue

### ISSUE THREAD

**Issue by gorxen** [slowtorta/turtlewow-bug-tracker#1579]
**Please, provide a clear description what the bug is:**

The door of the cage that holds the Elf refugees takes forever to close back once someone has triggered it. I've been here around 30 mins waiting and it just won't close.

EDIT UPDATE: This does not seem to happen all the time but randomly.

**IDs of affected creatures, items, quests or spells with a link to the relevant page:**

Quest: https://database.turtle-wow.org/?quest=80207

**Expected behavior. Describe how it should work:**

Close back within 1 or 2 mins. after being opened.

**Comment by Kruxis** [comment]
Greetings and thanks for the report! Unfortunatelly i, too, was unable to recreate that issue. Must have been a 1 in 1000 bug which happened.
