### ISSUE TITLE
 Quest item :Rockhide Boar Meat drops from  Rockhide Boar when you don't have  the quest.

### ISSUE THREAD

**Issue by SierraNairn** [slowtorta/turtlewow-bug-tracker#158]
Quest item :Rockhide Boar Meat drops from  Rockhide Boar when you don't have  the quest.
https://database.turtle-wow.org/?item=51868  -Rockhide Boar Meat
https://database.turtle-wow.org/?npc=524- Rockhide Boar
https://database.turtle-wow.org/?quest=60141 -Quest Duty to the light
It's supossed to drop from the boar's you kill only when you have the quest.

**Comment by slowtorta** [comment]
Thanks for reporting it. It'll be fixed on the next server restart. Make sure to clear your WDB folder.
