### ISSUE TITLE
 /reload and /reloadui commands missing from custom classes/races

### ISSUE THREAD

**Issue by gorxen** [slowtorta/turtlewow-bug-tracker#1580]
**Please, provide a clear description what the bug is:**

what the title says, the /reload and /reloadui commands appear to be missing on most custom classes/races combinations, tested with some of them but not all, notably high elves and dwarf mages.

**Comment by JoLiKMC** [comment]
This server is based on _World of Warcraft_ v1.12.1.  The official shortcuts for the `reloadUI` console command weren't added to retail until [v3.2.0](https://wowpedia.fandom.com/wiki/MACRO_reload).

Certain AddOns also add these shortcuts in versions prior to 3.2.0.

**Comment by slowtorta** [comment]
That is correct. Those commands do not exist in Vanilla.
