### ISSUE TITLE
Spawn point of Dagun the Ravenous is incorrect

### ISSUE THREAD

**Issue by Shellyoung** [slowtorta/turtlewow-bug-tracker#1584]
**Please, provide a clear description what the bug is:**
Dagun the Ravenous spawn on island near Seaworn Altar.

**Steps to reproduce the behavior with as much detail as possible:**

1. Use Enchanted Sea Kelp near Seaworn Altar in Dustwallow Marsh. The altar is located at 59.3, 9.6.

**IDs of affected creatures, items, quests or spells with a link to the relevant page:**

NPC: https://database.turtle-wow.org/?npc=2937
Quest: https://database.turtle-wow.org/?quest=735
Spell: https://database.turtle-wow.org/?spell=4945

**Expected behavior. Describe how it should work:**
Dagun the Ravenous should spawn in sea and then walk to Seaworn Altar. Video of Dagun walking out of sea: [https://www.youtube.com/watch?v=DHeJWwNWNfo](https://www.youtube.com/watch?v=DHeJWwNWNfo)

**Comment by slowtorta** [comment]
Fixed in the next revision.
