### ISSUE TITLE
Two Sen'Jin Village quests are too low level

### ISSUE THREAD

**Issue by Kangaroux** [slowtorta/turtlewow-bug-tracker#159]
`Unity is Strength` from Kor'ghan and `What Do You Rely On?` from Master Vornal are both rated too low level.

UiS should be a level 8-9 quest, and WDYRO should probably be 10-11.

As a level 6 char, these two quests are at the top of my quest log.

![image](https://user-images.githubusercontent.com/2302541/125554624-3501cfd1-cad5-4c64-98a1-0f161bbd8d56.png)

**Comment by slowtorta** [comment]
Thanks for reporting it. It'll be fixed on the next server restart. Make sure to clear your WDB folder.
