### ISSUE TITLE
Wsg doesnt register flag carry 

### ISSUE THREAD

**Issue by melg8** [slowtorta/turtlewow-bug-tracker#1591]
**Please, provide a clear description what the bug is:**
On my horde rogue character Melgo (not hardcore mode character, but with War Mode challenge enabled) - playing in bracket 40-49 on wsg - take alliance flag and
take it to our base i can't place it and get +1 to our team. Our flag is on base and not captured by
enemy team. If i drop my flag with right click on buf, and other horde player pick it up - he can score
flag by simply entering ring around our flag. 
I myself cant score flag by entering red zone around our flag, by entering and going out from it, jumping, dropping and picking it up again. So i bassically can't score as flag capture.

**Steps to reproduce the behavior with as much detail as possible:**
1. Go to wsg as Melgo in 40-49 bracket (maybe that behaviour same on other brackets)
2. capture ally flag
3. bring it to horde base
4. Enter room with horde flag
5. Enter circle around horde flag
6. Nothing happens.

**IDs of affected creatures, items, quests or spells with a link to the relevant page:**

**Expected behavior. Describe how it should work:**
Should score as flag capture and get additional honor.

**Comment by Zebouski** [comment]
ive experienced this in a lv 9 game and many lv 60 games. it's been broken since patch 1.16

**Comment by melg8** [comment]
@Zebouski  is it character based, or sometimes you can still bring flag back?

**Comment by melg8** [comment]
@ratkosrb can confirm, now problem fixed, captured 3 flags today. Thank you so much for fast fixes!
