### ISSUE TITLE
[Vanilla Oversight?] Rezlak's Quests Give Horde Reputation to Alliance Players

### ISSUE THREAD

**Issue by JoLiKMC** [slowtorta/turtlewow-bug-tracker#1593]
Two neutral quests that NPC Rezlak has give reputation for Orgrimmar and the Darkspear Trolls.  This is normal.  What _isn't_ normal is that these reputation gains also apply to Alliance players!

**Steps to reproduce the behavior with as much detail as possible:**
1. As a Level 7+ Alliance player, find the Ratchet NPC Rezlak near the entrance to Orgrimmar in Durotar
2. Accept his quests and complete them
3. Gain 200 (100 + 100) Reputation with both Orgrimmar and the Darkspear Trolls

**IDs of affected creatures, items, quests or spells with a link to the relevant page:**
NPC: https://database.turtle-wow.org/?npc=3293 (Rezlak)
Quests:
- https://database.turtle-wow.org/?quest=834 (Winds in the Desert)
- https://database.turtle-wow.org/?quest=835 (Securing the Lines)

**Expected behavior. Describe how it should work:**
Honestly, these quests are _probably_ working exactly as it always has since Patch 1.11.1.10772.  The thing of it is… because players can seen _all_ faction reputation on this server, it's much easier to notice for an Alliance player to notice a sudden reputation gain with a Horde faction.  I'm not sure if any other quests in the game are like this, either.  Would be kind of fun to not be attacked sight-on-scene by the opposite faction's guards, though…

**Comment by Zebouski** [comment]
the lunar festival NPCs giving tokens around the world in january, those also give you both freindly and opposite faction reputation.
