### ISSUE TITLE
"Wanted!" Quests Marked as Available to Both Factions in Database

### ISSUE THREAD

**Issue by JoLiKMC** [slowtorta/turtlewow-bug-tracker#1594]
The quest, "WANTED: Hole Escapee", is marked as being available for both the Horde and the Alliance in the _Turtle WoW Database_, but the object which gives the quest can only be interacted with by Horde players.
Additionally, the quest, "Wanted: Maggot Eye", is marked as being available for both the Horde and the Alliance under similar circumstances.

**Steps to reproduce the behavior with as much detail as possible:**
1. As a Level 8+ Alliance player, go to either Sparkwater Port in Durotar or Brill in Tirisfal Glades
2. Try and interact with the "wanted" board and find that it's impossible

**IDs of affected creatures, items, quests or spells with a link to the relevant page:**
Quests:
- https://database.turtle-wow.org/?quest=398 (Wanted: Maggot Eye)
- https://database.turtle-wow.org/?quest=55048 (WANTED: Hole Escapee)
Objects:
- https://database.turtle-wow.org/?object=711 ("Wanted!" signpost)
- https://database.turtle-wow.org/?object=1000504 ("WANTED!" signpost)

**Expected behavior. Describe how it should work:**
Either:
- The quests should marked as Horde-only
- The quest-givers should be moved somewhere that Alliance players can interact with it

**Additional notes:**
While I didn't expect an object deep within a Horde sub-city to be available to Alliance players, I do think that it's an oversight that the quest is flagged as "available" to both sides.  This is definitely an oversight of some kind.

**Comment by slowtorta** [comment]
This is normal, many quests didn't have this limitation in Vanilla. The availability was defined by a quest giver's faction. I'll fix it for those two, but it's really not that relevant unless players can find a way to speak with hostile quest givers.
