### ISSUE TITLE
[Alliance] Death in Northern Barrens, Revival in Ashenvale?

### ISSUE THREAD

**Issue by JoLiKMC** [slowtorta/turtlewow-bug-tracker#1595]
Dying in the northern parts of the Barrens as an Alliance player leads to the player's spirit teleporting to Ashenvale.
Additionally, dying in Silverpine Forest as an Alliance player leads to the player's spirit teleporting to Southshore in the Hillsbrad Foothills

**Steps to reproduce the behavior with as much detail as possible:**
_Barrens to Ashenvale_
1. As an Alliance player, walk to The Sludge Fen in the northern-most area of The Barrens
2. Lose all one's health, then click Release Spirit
3. The player will be teleported to the Spirit Healer in Ashenvale, coordinates: 80.7, 58.4

_Silverpine to Southshore_
1. As an Alliance player, find a way to Silverpine Forest
2. Lose all one's health, then click Release Spirit
3. The player will be teleported to the Spirit Healer in Southshore, Hillsbrad Foothills, coordinates: 51.8, 52.5

**IDs of affected creatures, items, quests or spells with a link to the relevant page:**
NPC: https://database.turtle-wow.org/?npc=6491 (Spirit Healer)

**Expected behavior. Describe how it should work:**
The Alliance player should be teleported to the Spirit Healer at Ratchet or the Spirit Healer near the Scarlet Monastery, respectively.

**Further details:**
While attempting to do a singular quest in The Sludge Fen of the northern Barrens, I died to an Elite Rare Mob.  I expected a lengthy walk back from Camp Taurajo, or some neutral spot, but instead, I found myself in Ashenvale!
I also experienced a similar thing while wandering through Silverpine Forest as an Alliance character.  I died and ended up in Southshore!

This doesn't seem right, to me.  But, for all I know, it probably is.  Vanilla is a weird beast.

**Comment by Daribon** [comment]
Vmangos has a lot of inconsistencies when it comes to graveyard. Several graveyards are incorrectly set as horde or alliance, when they should be set as neutral. I'm working on fixing it, turtle can pull the fix whenever it is pushed to vmangos.

**Comment by JoLiKMC** [comment]
Good enough for me~
