### ISSUE TITLE
Archmage Ataeric Marked as Vendor; Sells One (1) Dalaran Wizard's Robe

### ISSUE THREAD

**Issue by JoLiKMC** [slowtorta/turtlewow-bug-tracker#1597]
Alliance players can interact with certain NPCs at Ambermill within Silverpine Forest.  One such NPC is Archmage Ataeric, who sells a Dalaran Wizard's Robe in limited quantity.

**Steps to reproduce the behavior with as much detail as possible:**
1. As an Alliance player, go to Ambermill in Silverpine Forest
2. Within the town hall, find Archmage Ataeric and interact with him
3. He will act as a vendor selling one (1) Dalaran Wizard's Robe

**IDs of affected creatures, items, quests or spells with a link to the relevant page:**
NPC: https://database.turtle-wow.org/?npc=2120 (Archmage Ataeric)

**Expected behavior. Describe how it should work:**
Archmage Ataeric probably should not be marked as a vendor.

**Further notes:**
The only reason I bring this up is because there is a Dalaran Quartermaster right outside the town hall, [Lonum Magicus](https://database.turtle-wow.org/?npc=80953), who not only sells an _infinite_ supply of Dalaran Wizard's Robes, but also sells an Armored Dalaran Warhorse.

On a similar note, there's a seemingly random NPC, [Abigale Rowe](https://database.turtle-wow.org/?npc=81045), who's in charge of selling Dalaran Tabards.  That seems a bit odd.
(She also has a _disproportionate_ amount of health when compared to other nearby NPCs.)

**Comment by JoLiKMC** [comment]
Well, the archmage no longer has anything to sell, apparently.  Guess this was hot-fixed.

**Comment by slowtorta** [comment]
The server never receives updates listed in the tracker immediately. We usually apply them once a week. All the reputation rewards will be available at this NPC after the update:

![image](https://user-images.githubusercontent.com/66763404/180735899-3d200b8c-478d-4cea-b308-bcd7309adf48.png)
