### ISSUE TITLE
"A Call to Aid" Quest Chain Gives No Reputation

### ISSUE THREAD

**Issue by JoLiKMC** [slowtorta/turtlewow-bug-tracker#1598]
The three quests in the optional "A Call to Aid" quest line in West Tirisfal gives the player absolutely no reputation upon completion.
Additionally, the quests are marked as available to both factions despite the quest-givers being hostile to Horde players.

**Steps to reproduce the behavior with as much detail as possible:**
1. As a Level 11+ Alliance player, head to The Remnant Camp in West Tirisfal
2. Talk to Captain Silas, do his quest, do the return quest
3. Talk to Barkeep Clemens, do his quest
4. The quests give absolutely no reputation reward with any Alliance faction or sub-faction

**IDs of affected creatures, items, quests or spells with a link to the relevant page:**
Quests:
- https://database.turtle-wow.org/?quest=40318 ("A Call to Aid", trip to Stormwind)
- https://database.turtle-wow.org/?quest=40319 ("A Call to Aid", trip back)
- https://database.turtle-wow.org/?quest=40320 ("A Call to Aid", Graypaw Flanks quest)

**Expected behavior. Describe how it should work:**
The Lordaeron NPCs should give reputation for _some_ Alliance faction.  Oddly, they're marked as "Stormwind" NPCs despite being part of the Lordaeron Remnant.

**Comment by slowtorta** [comment]
In lore they are completely different entities: Lordaeron Remnants are not part of the Alliance. This is working as intended, those quests are not supposed to give any reputation values.

> Additionally, the quests are marked as available to both factions despite the quest-givers being hostile to Horde players.

This also is a quite normal approach for WoW Vanilla, many Blizzlike quests are done in the same fashion. Strict limitations were added in TBC.
