### ISSUE TITLE
Insect swarm rank 2 is missing from NPC's

### ISSUE THREAD

**Issue by Tinyfin-github** [slowtorta/turtlewow-bug-tracker#1599]
Insect swarm rank 2 is missing from trainer's.

https://classic.wowhead.com/spell=24974/insect-swarm
https://database.turtle-wow.org/?spell=24974

**Comment by slowtorta** [comment]
This is intended for 1.16.1. The change wasn't supposed to be live, but will be aligned with the rest of the changes SoonTM.

**Comment by burner1024** [comment]
1.16.1 is out, but the spell is still missing.

**Comment by Milton3450** [comment]
After last hotfix we can train IS r2. But now further from there. Now it's just like before, just r3 now.
