### ISSUE TITLE
Missing Item icon in Quest "Deadly Desert Venom"

### ISSUE THREAD

**Issue by BRBScratcher** [slowtorta/turtlewow-bug-tracker#16]
By opening this Issue, I admit to having done the pertinent research using sources from Vanilla (preferably) or Classic. I also understand that sources from other private servers are not acceptable.

**Current behavior**: 
In the Quest "Deadly Desert Venom" in Silithus you need to get 8 "Stonelash Scorpid Stinger".
The item shows up with a questionmark icon. (deleting the WDB folder didn't change it)

**Expected behavior**: 
Its icon should be a black sting on green background.

**Proofs**:
ingame:
![Unbenannt](https://user-images.githubusercontent.com/50635128/122156922-40908380-ce6a-11eb-8556-5268c8135cc0.jpg)

how it should look:
https://classic.wowhead.com/item=20373/stonelash-scorpid-stinger

**Steps to reproduce**:

1.  Go to  Cenarion Hold in Silithus
2.  Get the Quest "Deadly Desert Venom" from Beetix Ficklespragg (the female Goblin that is with the poisened male Goblin)
3.  kill "Stonelash Scorpid Stingers" near Cenarion Hold till the item drops

**Comment by slowtorta** [comment]
Thanks for reporting it. It'll be fixed on the next server restart. Make sure to clear your WDB folder.
