### ISSUE TITLE
(Suggestion) Include a wand as a starter reward in Valley of Trials

### ISSUE THREAD

**Issue by Kangaroux** [slowtorta/turtlewow-bug-tracker#160]
One of the very early Undead quests offers you a wand (and/or a bag?) and it's super helpful for priests.

It would be great if one of the quest rewards in VoT was a wand. None of the vendors in VoT, Sen'Jin, or Razor Hill sell wands.

**Comment by gheor7** [comment]
Hello, this a bug-tracker.
For suggestions please use our forums, an idea to get this quest going would also be appreciated

**Comment by Kangaroux** [comment]
https://forum.turtle-wow.org/viewtopic.php?f=14&t=1880
