### ISSUE TITLE
Sunken Temple "Shade of Eranikus" Mob Trigger

### ISSUE THREAD

**Issue by afizzler** [slowtorta/turtlewow-bug-tracker#1601]
Bringing Hazzas or Morphaz to Shade of Eranikus does not trigger an event in which all green dragonspawn mobs are pulled to the shade itself. 

**Steps to reproduce the behavior with as much detail as possible:**

1. Pull either Hazzas or Morphaz (or both) to the Shade of Eranikus
2. Nothing happens likely???

**IDs of affected creatures, items, quests or spells with a link to the relevant page:**

Hazzas: https://database.turtle-wow.org/?npc=5722
Morphaz: https://database.turtle-wow.org/?npc=5719
Shade of Eranikus: https://database.turtle-wow.org/?npc=5709

Nightmare Wanderer: https://database.turtle-wow.org/?npc=5283
Nightmare Scalebane: https://database.turtle-wow.org/?npc=5277
Nightmare Wyrmkin: https://database.turtle-wow.org/?npc=5280
Nightmare Whelp: https://database.turtle-wow.org/?npc=8319

Video Evidence: https://www.youtube.com/watch?v=QWy94I5Gxlo&t=193s
Go to timestamp 4:10 of the video.

**Comment by redmagejoe** [comment]
Pulling Morphaz and Hazzas specifically are not meant ot trigger a meaningful interaction with Shade of Eranikus. In fact, you need to manually attack the Shade to initiate the event where he summons all remaining dragonkin. This works properly. In the video, the Mage aggro'd Eranikus with Cone of Cold. It had nothing to do with dragging a dragon over him.

This issue can be closed.
