### ISSUE TITLE
Druid: Equiping Idols gives (Turtle_TransmogUI.lua) error

### ISSUE THREAD

**Issue by BosBeest** [slowtorta/turtlewow-bug-tracker#1604]
**Please, provide a clear description what the bug is:**
When logging in with the trinkets mentioned below will spit out an Error message saying: 
"...ace\FrameXML\Turtle_TransmogUI\Turtle_TransmogUI.lua:1996: attempt to concatenate field `?'(a nil value)"

But is also happens when you switch/swap said Trinkets later on(continuously), it will spit out the same message but line (2073) is giving Errors:
"...ace\FrameXML\Turtle_TransmogUI\Turtle_TransmogUI.lua:2073: attempt to concatenate field `?'(a nil value)"

Deleting WDB Folder and clearing Recycle Bin does not resolve the problem(same 2 Error codes).
Disabeling all Addons does not resolve the problem(same 2 Error codes).
Setting Addon Script Memory to "0" or "999" does not resolve the problem(same 2 Error codes).
The client i'm running is downloaded of the website when it was alterred to 1.16.0, so not updated from the older versions.

Also an Error message can pop up at random, but normally this happens immediately or in an time frame of less then 10 seconds after switching Idols(line 1996 or later on after an 1996 error , line 2073 will continue), When logging in the Error is immediately visible(line 1996).

This has been an problem for me since the Transmog capability was added to the game.
I'm not 100% sure that the Idols are the **only** item that is responsible for errors, i've only narrowed down the Idols items to give an Error message.

![BosBeestIdolError](https://user-images.githubusercontent.com/86881988/180097616-16686ca6-0fc5-4d12-b637-fdaae8f8786f.jpg)

**Steps to reproduce the behavior with as much detail as possible:**
1.Equipping Idols:
   - "Idol of Ferocity"(https://database.turtle-wow.org/?item=22397), 
   - "Idol of Brutality"(https://database.turtle-wow.org/?item=23198) 
   - "Idol of Rejuvenation"(https://database.turtle-wow.org/?item=22398)
   - The idols: _(Idol of Health), (Idol of Longevity) and (Idol of the Wildshifter)_ might also be problematic but i cannot give an positive on that.
2. Log in your character **or** Switch between Idols **or** wait for it to randomly spit out an Error message.
3. -

**IDs of affected creatures, items, quests or spells with a link to the relevant page:**
NPC: -
**Item:** (https://database.turtle-wow.org/?item=22397), (https://database.turtle-wow.org/?item=23198), (https://database.turtle-wow.org/?item=22398), _(https://database.turtle-wow.org/?item=22399), (https://database.turtle-wow.org/?item=23004), (https://database.turtle-wow.org/?item=51798)_.
Quest: -
Spell: -
Object: -

**Expected behavior. Describe how it should work:**
Spit out no Error messages.

**Comment by slowtorta** [comment]
Fixed in patch 1.16.1 :)

**Comment by BosBeest** [comment]
> Fixed in patch 1.16.1 :)

Thanks for the response but I'm confused, i just downloaded another client of the website and it is still version 1.16.0
How does one get an client with version 1.16.1?
