### ISSUE TITLE
Ironbark Protector and Ghost Stack in Dire Maul West

### ISSUE THREAD

**Issue by Dragunovi** [slowtorta/turtlewow-bug-tracker#1607]
**Please, provide a clear description what the bug is:**
Patrolling Ironbark Protectors and Eldreth Spectres are bunched up as a deathball patrol in Dire Maul: West.
**Steps to reproduce the behavior with as much detail as possible:**

1. Go to Dire Maul West side.
2. Look at tree ancients and see them stacked.
3. Go to ghost room and see that all invisible ghosts are also stacked together.

**IDs of affected creatures, items, quests or spells with a link to the relevant page:**

NPC: https://database.turtle-wow.org/?npc=11459
NPC: https://database.turtle-wow.org/?npc=11473

**Expected behavior. Describe how it should work:**
Their pathing should be spread out evenly.

**Comment by redmagejoe** [comment]
Recently tested and found this is no longer the issue.

Fixed.
