### ISSUE TITLE
Using the word "radar" in Dry Hiding quest description (Same kind of issue)

### ISSUE THREAD

**Issue by Shellyoung** [slowtorta/turtlewow-bug-tracker#1609]
**Please, provide a clear description what the bug is:**
Same issue as in [Using the word RADAR is inconsistent with WoW's lore time period](https://github.com/slowtorta/turtlewow-bug-tracker/issues/1534). Image: [https://i.imgur.com/O0Evdmw.png](https://i.imgur.com/O0Evdmw.png).

**IDs of affected creatures, items, quests or spells with a link to the relevant page:**

Quest: https://database.turtle-wow.org/?quest=55025

**Expected behavior. Describe how it should work:**
The goblin can say "hide under the roof".

**Comment by gheor7** [comment]
Considering radios are part of the game, a radar isn't necessarily out of the question.
Radars are an ingenuity done by engineering.

https://classic.wowhead.com/item=10585/goblin-radio

Definition of a radar:

"a system for detecting the presence, direction, distance, and speed of aircraft, ships, and other objects, by sending out pulses of radio waves which are reflected off the object back to the source."

An antenna also exists in WoW already, based on these already existing thing, a radar is definitely possible to exist in the universe. It's simply that your character might not be accustomed to it so he'd simply shrug at the mention if it.

https://classic.wowhead.com/item=7119/twitching-antenna

**Comment by Shellyoung** [comment]
[R.A.D.A.R.](https://www.wowhead.com/item=160245/r-a-d-a-r) has been added in Battle for Azeroth expansion. It lenghtens in "Reconnaissance and Discovery Atmospheric Resonator".

**Comment by gheor7** [comment]
Not sure what has to do with anything. 

From an Engineering POV, and I mean as Engineering works in-game, a radar is highly possible to have been built up to this point. 
Again, the resources to create one are already there. 

Goblins have rockets, Gnomes have planes.  Extracting Oil is also a thing. 
This fantasy universe has technology, it'd be silly to consider they wouldn't be able to build a radar but every other Goblin carries rocket fuel with them.
