### ISSUE TITLE
In dreams bugged

### ISSUE THREAD

**Issue by Tinyfin-github** [slowtorta/turtlewow-bug-tracker#1614]
In dreams bugged

https://database.turtle-wow.org/?quest=5944

After taelan dies, the mob despawns and the quest fails.

The quest was attempted in multiple possible ways, even trying to kill the elites and tank   Inquisitor Isillien

There was a bug like this in the past : https://github.com/slowtorta/turtlewow-bug-tracker/issues/132

**Comment by ratkosrb** [comment]
Please make video of the bug, so I can see what happens, because I can't reproduce it locally. The quest works for me.
