### ISSUE TITLE
Ragehammer proc bug

### ISSUE THREAD

**Issue by Tedementa** [slowtorta/turtlewow-bug-tracker#1615]
**Please, provide a clear description what the bug is:**
With my ret pally have the ragehammer and when i hit something and gain enrage my attack speed is lowered instead of faster.

**Steps to reproduce the behavior with as much detail as possible:**

1. Equip ragehammer without enchants
2. Hit some dummy and active enrage who is the proc of weapon
3. with and without seals happens

**IDs of affected creatures, items, quests or spells with a link to the relevant page:**

NPC: https://database.turtle-wow.org/?npc=
Item: https://es.classic.wowhead.com/item=10626/martillo-de-ira
Quest: https://database.turtle-wow.org/?quest=
Spell: https://database.turtle-wow.org/?spell=
Object: https://database.turtle-wow.org/?object=

**Expected behavior. Describe how it should work:**
when procs happen you gain the effect of enrage who increase your attack speed  in 5% and your damage in 20 points( i dont know if this is weapon or base damage)
![imagen](https://user-images.githubusercontent.com/109830289/180577928-6059d2c9-0847-4267-8c62-e87e32e269d7.png)
![imagen](https://user-images.githubusercontent.com/109830289/180577993-a5865e79-f354-4d67-b8ca-8500cee7260f.png)
![imagen](https://user-images.githubusercontent.com/109830289/180578026-8a38fdc5-5d3f-47e1-8710-cbe5418fc4b9.png)

**Comment by redmagejoe** [comment]
3.70 speed became 3.88 upon weapon proc.

This does indeed behave contrary to its description. "Increased attack speed" and the use of "swing timers" in the game, even with Blizzard behavior, can at times cause confusion. In this case, the swing timer is being increased, thus the attack speed is being DECREASED. Whatever the intended behavior, let's please match the effect and the description.
