### ISSUE TITLE
Bear mount does not dismount on skill use

### ISSUE THREAD

**Issue by testening** [slowtorta/turtlewow-bug-tracker#1616]
**Please, provide a clear description what the bug is:**
Using skills while riding a custom bear mount does not dismount you

     **Steps to reproduce the behavior with as much detail as possible:**
1. Activate Black Bear mount.
2. Attempt to autoattack or use any skill
3. Stay on mount instead of being dismounted

      **IDs of affected creatures, items, quests or spells with a link to the relevant page:**
Item: https://database.turtle-wow.org/?item=80433

      **Expected behavior. Describe how it should work:**
Using a skill while mounted should dismount you.

**Comment by Tinyfin-github** [comment]
Greetings!

In vanilla wow you don't get dismounted when you use skills for any mount.. This is a Addon function.
