### ISSUE TITLE
"Creature Hits vs. You" Not Appearing in Combat Log

### ISSUE THREAD

**Issue by JoLiKMC** [slowtorta/turtlewow-bug-tracker#1617]
`COMBAT_HOSTILEPLAYER_HITS` ("Creature Hits vs. You") messages are not appearing in the chat log.
**Note:** `COMBAT_HOSTILEPLAYER_MISSES` ("Creature Misses vs. You") are still working just fine.

**Steps to reproduce the behavior with as much detail as possible:**
1. Log in to any character and switch to the Combat Log chat tab
2. Get into a fight with any creature that can attack back and take damage
3. There will be no display in the Combat Log of damage taken

**Expected behavior. Describe how it should work:**
The Combat Log should display how much damage an attack does against the player, as well as if it's "glancing" or not.

**Major edit:**
Hey, guess what?  It was an AddOn that was doing it.  _Who would have thought_.

Apologies.  I'll transcribe this to the appropriate _GitHub_ repository.

**Comment by Niqlo** [comment]
https://i.imgur.com/C9hotsV.png


i think you just disabled them. they work fine for me.

**Comment by JoLiKMC** [comment]
It was an AddOn.  Sorry.  I'm a dum-dum.
