### ISSUE TITLE
Characters jump underwater instead of swimming upwards

### ISSUE THREAD

**Issue by TrangOul** [slowtorta/turtlewow-bug-tracker#162]
When I press Space key when underwater, my character jumps, moving slightly up (towards the surface). When I press and hold Space, the character still performs one jump.

The screen shows night elf's jumping animation underwater - the characteristic flip is shown.
![image](https://user-images.githubusercontent.com/5629046/125672869-cd577ea8-9d39-406e-aee9-3dd0ea7b80c2.png)

**Steps to reproduce the behavior:*

1. Go underwater, preferably deep.
2. Try to rise to the surface by holding Space key.

**Expected behavior:**
When holding Space, the character ascends towards the surface. Pressing (or holding) the space does not make the character jump when underwater.

**Comment by Velite12** [comment]
Ah the age old "bug" of mangos. Swimming is basically just treated like flying in mangos and jumping while flying breaks it, but then the game remembers since you're underwater you should continue flying.

**Comment by jameyboor** [comment]
No. It's not a bug of mangos in particular. Swimming has always worked like this in vanilla wow. You probably just remembered newer expansions which fixed this.

Proof :
http://youtu.be/FaV6oAteJGI?t=40m50s
