### ISSUE TITLE
Fishing bobber DOES NOT make sound with Widescreen Build 1.16.0 (7001) while alt-tabbed

### ISSUE THREAD

**Issue by quititsquid** [slowtorta/turtlewow-bug-tracker#1621]
**Please, provide a clear description what the bug is:**

The fishing bobber doesn't make any sound when the fish gets hooked while alt-tabbed, while everything else does. It still makes sound if your window is in focus, or if it was in focus at the moment that the fish bit.

**Steps to reproduce the behavior with as much detail as possible:**

1. Cast Fishing
2. Alt-Tab
3. Wait until a fish gets hooked

**IDs of affected creatures, items, quests or spells with a link to the relevant page:**

Fishing: https://database.turtle-wow.org/?spell=7620

**Expected behavior. Describe how it should work:**

It should still make sound when alt-tabbed.

**Comment by quititsquid** [comment]
I tested the custom launcher some more and it seems like this is more of a general sound issue than I thought.

I really was under the impression that all sounds worked because all game sounds that happen while your window is still in focus still go on after you alt-tab (for example, warlock's Rain of Fire plays for it's entire duration, general ambience and water sounds still play, the music still plays), but the sounds that happen after you alt-tab do not play until you focus back on the game window (for example, warlock's Hellfire doesn't keep making noise, the music after it's enabled but didn't start yet before you alt-tab, the fishing bobber, other player sounds, etc.). 

I thought it was only the fishing bobber but it's not. Can't seem to remove the topic but also not sure if the issue needs a proper page of its own since Turtle only ever claimed that it was just the music that works while alt-tabbed?

**Comment by slowtorta** [comment]
In its current implementation, it'll continue to play only sound events active at the moment of alt-tab.

I don't think we can do much more at this moment, even if we wanted to, without having a client source.

**Comment by slowtorta** [comment]
I'll keep this open for a while in case anyone will come up with a solution, but I don't think it's possible.
