### ISSUE TITLE
Blood frenzy missing attack speed, rage [1.16.1]

### ISSUE THREAD

**Issue by burner1024** [slowtorta/turtlewow-bug-tracker#1624]
**Please, provide a clear description what the bug is:**
Tiger's fury with Blood frenzy learned doesn't increase attack speed, Enrage doesn't add extra rage.
The only thing working from the talent is tiger's fury increased duration.

![Captura de pantalla de 2022-07-26 06-40-22](https://user-images.githubusercontent.com/1279852/180892687-4319ab02-fa10-4080-84de-6b968e322fe1.png)

(This is with BetterCharacterStats addon, I think vanilla doesn't show attack speed for forms?).

**Steps to reproduce the behavior with as much detail as possible:**
1. Learn blood frenzy.
2. Shift to cat, cast tiger's fury, check attack speed.
4. Shift to bear, cast Enrage, see that no rage is added immediately. Also check attack speed.

**IDs of affected creatures, items, quests or spells with a link to the relevant page:**
Database is disabled, so...

**Expected behavior. Describe how it should work:**
- Increase attack speed, as per talent description.
- Enrage instantly generates 10 rage as per talent description.
- Spell and buff tooltips should reflect changes from the talent.

**Comment by Jammyxx** [comment]
Stil bugged Patch 1.16.2

**Comment by Milton3450** [comment]
Can confirm.

**Comment by Jammyxx** [comment]
Still bugged 1.16.3

**Comment by ratkosrb** [comment]
Wait for next server update.
