### ISSUE TITLE
Target Frame No Longer Displays Relative Health

### ISSUE THREAD

**Issue by JoLiKMC** [slowtorta/turtlewow-bug-tracker#1625]
As of v1.16.1 (7010), the Health bar on target unit frames no longer display any sort of numbers.
This applies to both **on hover** and **with Status Bar Text** enabled.

**Steps to reproduce the behavior with as much detail as possible:**
1. Log in and find any unit (enemy, friendly, neutral, player), target the unit
(If Status Bar Text is disabled, hover the mouse over the target unit frame)
2. Notice the lack of numbers in the target status bar

**Expected behavior. Describe how it should work:**
A relative or estimated amount of Health and/or Resources should appear on the target's unit frame.

**Further notes:**
Back in v1.16.0 (and prior?), using the default UI would display a specific number for a target's Health and the game would kind of display health decreases in numbers and percentile as damage was done.  This was a _Turtle WoW_-exclusive sort of thing done without AddOns and the like.  As of v1.16.1, this is no longer the case.

**Relevant screenshots:**
![v116-0_EnemyHealth](https://user-images.githubusercontent.com/102710555/180892967-0fc50e20-7fe7-4deb-b2af-165c43b46d36.jpg)
_Target Health with the default UI (v1.16.0)_

![v116-1_NoEnemyHealth](https://user-images.githubusercontent.com/102710555/180892968-f0274bf9-38d6-4495-b25f-146064539d6d.jpg)
_Target Health with the default UI (v1.16.1)_

**Comment by slowtorta** [comment]
Fixed in 1.16.4, along with the target frame repositioning.
