### ISSUE TITLE
Druid's Berserk increases max health only

### ISSUE THREAD

**Issue by burner1024** [slowtorta/turtlewow-bug-tracker#1627]
**Please, provide a clear description what the bug is:**
When cast in Bear form, Berserk does not add health, only increases max HP.

**Steps to reproduce the behavior with as much detail as possible:**

1. Check that you have full HP.
2. Shift to bear, cast berserk.
3. See that you don't have full HP.

**IDs of affected creatures, items, quests or spells with a link to the relevant page:**
Database disabled.

**Expected behavior. Describe how it should work:**
Berserk actually adding 20% health.
Current implementation makes no sense. My understanding is that it's bear's [Last Stand](https://classic.wowhead.com/spell=12975/last-stand), which increases max hp, and increases current health by the same amount.

**Comment by Testerrosaurus** [comment]
Still only increases max HP as of today.
