### ISSUE TITLE
Aquementas Quest Item Bug

### ISSUE THREAD

**Issue by blargsnarf** [slowtorta/turtlewow-bug-tracker#163]
**Please, provide a clear description what the bug is:** During the quest [Aquementas](https://database.turtle-wow.org/?quest=4005) in Felwood, you are handed [Eridan's Supplies](https://database.turtle-wow.org/?item=11617), which is supposed to contain the [quest book](https://database.turtle-wow.org/?item=11169) as well as the two quest items you fetched during the last part of the quest: [Silvery Claws](https://database.turtle-wow.org/?item=11172), and [Irontree Heart](https://database.turtle-wow.org/?item=11173). However, myself and at least 1 other player have experienced a bug where Eridan's Supplies does not contain the Irontree Heart.

Note that when this bug happens, the Eridan's Supplies enters a glitched state where you cannot loot it, but it will not destroy itself like a normal empty container.

**Steps to reproduce the behavior with as much detail as possible:**

1. Accept the quest Aquementas.
2. Possibly travel away from Felwood before opening the bag?
3. Open the bag and it will not contain all the necessary quest items.

Please note for both of us we fixed this issue by flying back to Felwood, abandoning the quest, and re-accepting it. Opening the bag the 2nd time included all the quest items.

**Expected behavior. Describe how it should work:**

All 3 items (Book, Claws and Heart) should be in Eridan's Supplies 100% of the time.

**Comment by slowtorta** [comment]
Cannot reproduce. Was able to obtain items summon the mob and receive the totem in my bag.

**Comment by Sringaram** [comment]
This just happened to me too. I only got 11 scales and the book from the box.
