### ISSUE TITLE
Priest - Improved Shadowform lost on talent reset

### ISSUE THREAD

**Issue by JustAnima9** [slowtorta/turtlewow-bug-tracker#1632]
**Please, provide a clear description what the bug is:**
When player resets it's talents through trainer or goblin brainwashing device and then chooses again Shadowform as a talent, player will not gain Improved Shadoform and instead has to relearn it from Trainer again

**Steps to reproduce the behavior with as much detail as possible:**
1. Learn Improved Shadowform from trainer
2. Reset talents at trainer or through Goblin Brainwashing device
3. Choose Shadowform in Shadow talent tree

**Expected behavior. Describe how it should work:**
Upon selecting Shadowform talent in Shadow tree and being lvl 60 with already trained Improved Shadowform, player should automaticaly re-learn it.

**Comment by Vynora** [comment]
this bug is still present. bump

**Comment by Apimius** [comment]
yes please fix this, its really annoying, you cant go to shadow again mid raid if you swaped to healer

**Comment by JaceEverwood** [comment]
we probably have too many healer and tank in-game anyway

**Comment by Apimius** [comment]
bump

**Comment by slowtorta** [comment]
Duplicate for https://github.com/slowtorta/turtlewow-bug-tracker/issues/1843
