### ISSUE TITLE
Priest - Vampiric Touch regenerates 10% mana instead of 4%

### ISSUE THREAD

**Issue by JustAnima9** [slowtorta/turtlewow-bug-tracker#1633]
**Please, provide a clear description what the bug is:**
Vampiric touch regenerates 10% mana from damage cause instead of 4%

**Steps to reproduce the behavior with as much detail as possible:**
1.Spend 2 points in Vampiric touch
2. Apply Vampiric Embrace on target
3. Cast damaging spell

**Expected behavior. Describe how it should work:**
Vampiric touch should regenerate only 4% mana from damage caused.

**Comment by JustAnima9** [comment]
Correction:

Upon further testing, Vampiric touch regenerates 9% mana twice. It also applies second heal. See picture below:

![Snímek obrazovky 2022-07-26 070157](https://user-images.githubusercontent.com/110008297/180927235-b436d408-c150-421c-be62-04fc880cb16e.png)

**Comment by slowtorta** [comment]
Fix for this should be already in-game, please double-check.

**Comment by JustAnima9** [comment]
Vampiric touch is applied only once, however mana return is still 9% and not 4% as it should be.
