### ISSUE TITLE
Priest - High elf racial Sun's embrace does not fade after 5 casts

### ISSUE THREAD

**Issue by JustAnima9** [slowtorta/turtlewow-bug-tracker#1636]
**Please, provide a clear description what the bug is:**
Sun's embrace stays active after 5 casts have been made

**Steps to reproduce the behavior with as much detail as possible:**
1. Activate Sun's embrace
2. Cast 6 or more Smites/Holy nova or Holy fire

**Expected behavior. Describe how it should work:**
The buff should fade after 5 casts of any damaging spells listed in its description or after 20 seconds

**Comment by Apimius** [comment]
tbh im am not sad about that bug at all, smite priest need mana reduction lol

**Comment by slowtorta** [comment]
Reworking this spell completely in 1.16.4, stand by.
