### ISSUE TITLE
Direct spells/abilities does not generate threat. Only autoattack hits and "dots".

### ISSUE THREAD

**Issue by banallwowbots** [slowtorta/turtlewow-bug-tracker#1639]
When using spells or abilities on mobs, no threat are generated. You must either autoattack hit the mob or use an ability/spell that do damage over time (dot).
You will not get experience from mobs that you only do direct spells/abilities to.

1. Cast frostbolt spell on any mob as a mage. Do not kill it. 
    -> You will have aggro cause you are the only one on the threat list.
2. Have a another character (eg. rogue) do a normal white hit (auto attack) to the same mob.
   -> Mob will start attacking the rogue immediately cause white hits generate threat, direct spells like frostbolt do not.

Expected behaviour:
Spells should generate threat and you should get experience from mobs you only do direct spells to.

**Comment by VenRPG** [comment]
Is this still the case after the hotfix they did to fix those abilities not giving xp?

**Comment by banallwowbots** [comment]
Seems to be fixed now!
