### ISSUE TITLE
[Hunter] Auto Shot Interrupted message when killing mob & it prevents quest kill message

### ISSUE THREAD

**Issue by RocketeerRaccoon** [slowtorta/turtlewow-bug-tracker#164]
When your attacking as Hunter and finish killing a mob, the Interrupted message keeps appearing and if you have the pfUI addon, it also prevents the quest kill message from appearing.

**Steps to reproduce the behavior with as much detail as possible:**

1. Have pfUI enabled.
2. Get a quest to kill a certain number of mobs.
3. Kill the mob as usual with your arrows/ammo.
4. Interrupted message shows up instead of quest kill message.

**Expected behavior. Describe how it should work:**
Interrupted message should not appear at all when target is killed with Auto Shot, and it should not overlap quest kill message.

**Comment by Nolin7777** [comment]
Closed until proof added.
