### ISSUE TITLE
Channeled spells will not aggro mobs until damage is done.

### ISSUE THREAD

**Issue by banallwowbots** [slowtorta/turtlewow-bug-tracker#1640]
Channeled spells like blizzard and arcane missilies will not aggro mobs immediately when used on mobs. They only aggro once damage is done to the mob by the channeled spell.
This bug happened after the latest update.

1. Have a mage cast blizzard or arcane missilies on a mob, then immediately cancel the channeling.
  -> The mob will not aggro (bug).
2. Have a mage cast blizzard or arcane missilies on a mob. The mob will aggro first when damage is done to the mob.

Expected behaviour:
Mobs should aggro immediately when using channeled spells on them, even if no damage is done yet. This worked before the latest update.

**Comment by ratkosrb** [comment]
That's not a bug. That's how it should work. The new behavior is blizzlike.
