### ISSUE TITLE
Frenzied regeneration heals too little

### ISSUE THREAD

**Issue by burner1024** [slowtorta/turtlewow-bug-tracker#1641]
**Please, provide a clear description what the bug is:**
Frenzied regeneration does not add 10% of stamina to heal. More like 1%.
![Captura de pantalla de 2022-07-26 17-55-49](https://user-images.githubusercontent.com/1279852/180991618-ae60fdf6-182f-4aed-a9de-ce616d9269d0.png)

**Steps to reproduce the behavior with as much detail as possible:**

1. Shift to bear
2. take some damage
3. Pop frenzied regeneration.

**IDs of affected creatures, items, quests or spells with a link to the relevant page:**
DB down.

**Expected behavior. Describe how it should work:**
Should add 10% of stamina to heal.
![Captura de pantalla de 2022-07-28 06-11-54](https://user-images.githubusercontent.com/1279852/181388092-adceadb7-7735-40cd-96a0-e4f9b7f08f21.png)

**Comment by Testerrosaurus** [comment]
Still broken as of today:
With 240 stamina Frenzied Regeneration(Rank 1) heals for 102 per 10-rage-tick instead of 340.
(10 + 240*0.1)*10=340
