### ISSUE TITLE
New Talent: Redoubt procs on 100% of successful attacks against the Paladin.

### ISSUE THREAD

**Issue by Gabsky8** [slowtorta/turtlewow-bug-tracker#1644]
**Please, provide a clear description what the bug is:**
The new Redoubt talent suggests that the extra Chance to Block should only happen 10% of the time on successful attacks made against the Paladin but right now it happens on 100% of successful attacks, thus Redoubt is always up.

**Steps to reproduce the behavior with as much detail as possible:**

1. Have a Paladin level 14 or more.
2. Put 5 talent points into Redoubt, first row of the Protection tree.
3. Get attacked by mobs.
4. Notice that the Redoubt talent procs every single time the Paladin gets hit, instead of the 10% suggested by the talent.

**IDs of affected creatures, items, quests or spells with a link to the relevant page:**
Talent: https://talents.turtle-wow.org/paladin/0-5

**Expected behavior. Describe how it should work:**
The talent should have a 10% chance to happen on successful attacks made against the Paladin.

**Notes:**
The talent was not tried with 1-2-3-4 points in it, only with 5/5.
Character level tested with: 29-30.
No Video available.

**Comment by slowtorta** [comment]
Fixed in 1.16.3
