### ISSUE TITLE
When you are concussed or stunned by a mob you acquire a permanent movement impairment

### ISSUE THREAD

**Issue by TheShreen** [slowtorta/turtlewow-bug-tracker#1646]
**Please, provide a clear description what the bug is:**

When you are concussed or stunned by a mob you acquire a permanent movement impairment where your character walks normal then walks slow and normal and slow. It makes playing the game for melee almost impossible.

**Steps to reproduce the behavior with as much detail as possible:**

1. Get on hunter turn on cheetah to force stun witness the pain of the movement impairment
2. 
3. 

**IDs of affected creatures, items, quests or spells with a link to the relevant page:**

NPC: https://database.turtle-wow.org/?npc=
Item: https://database.turtle-wow.org/?item=
Quest: https://database.turtle-wow.org/?quest=
Spell: https://database.turtle-wow.org/?spell=
Object: https://database.turtle-wow.org/?object=

**Expected behavior. Describe how it should work:**

**Comment by nonameform** [comment]
The only solution so far is to relog.
