### ISSUE TITLE
Trueshot (new ability: Hunter) not intitating auto-shoot

### ISSUE THREAD

**Issue by Riverleafs** [slowtorta/turtlewow-bug-tracker#1647]
**Please, provide a clear description what the bug is:**

Trueshot (new ability: Hunter) not intitating auto-shoot

**Steps to reproduce the behavior with as much detail as possible:**

1. Find a player/npc
2.  Use Trueshot
3. See how the ability does not start auto-shooting afterwards as it should

**IDs of affected creatures, items, quests or spells with a link to the relevant page:**

NPC: https://database.turtle-wow.org/?npc=
Item: https://database.turtle-wow.org/?item=
Quest: https://database.turtle-wow.org/?quest=
Spell: https://database.turtle-wow.org/?spell= (Database currently unavailable: Hunter ability: Trueshot)
Object: https://database.turtle-wow.org/?object=

**Expected behavior. Describe how it should work:**

Start auto-shooting after using the ability.

**Comment by nonameform** [comment]
Can confirm that. If you are using auto-shot and weave a Trueshot, the character will continue shooting after the cast. If you start with Trueshot, the character will just stand there after the cast.
