### ISSUE TITLE
Can't queue for all bgs simultaneously.

### ISSUE THREAD

**Issue by burner1024** [slowtorta/turtlewow-bug-tracker#1648]
**Please, provide a clear description what the bug is:**
Can't queue for more than 3 bgs.

**Steps to reproduce the behavior with as much detail as possible:**

1. Queue for each bg.
2. See that you can't queue for more than 3.  Nothing happens upon pressing the join button.

**Expected behavior. Describe how it should work:**
Should be able to queue for all of them.

**Comment by slowtorta** [comment]
Related to the same matter as here: https://github.com/slowtorta/turtlewow-bug-tracker/issues/1612

**Comment by twowTurtReynolds** [comment]
Current investigation shows this to be a hardcoded client issue, something we can't fix unfortunately.
