### ISSUE TITLE
Some Hunter Trainers do not teach new abilities

### ISSUE THREAD

**Issue by nonameform** [slowtorta/turtlewow-bug-tracker#1649]
**Please, provide a clear description what the bug is:**

Not all hunter trainers can teach the new abilities. 

**Steps to reproduce the behavior with as much detail as possible:**

Hunter Trainers that can't teach new abilities (Aspect of the Wolf and Trueshot):
Jocaste at Darnassus
Danlaar Nightstride at Ashenvale (can only teach Aspect of the Wolf)
Clover Spinpistol at Dun Morogh

Hunter Trainers that shouldn't teach new abilities:
Ayanna Everstride at Teldrassil (she should only teach abilities up to level 6)
Thorgas Grimson at Dun Morogh (he should only teach abilities up to level 6)

**IDs of affected creatures, items, quests or spells with a link to the relevant page:**

Cannot link anything since DB is disabled.

**Expected behavior. Describe how it should work:**
Every class trainer except the starting ones should be able to teach all abilities.

**Comment by Massie323** [comment]
To add to this from the horde side;
All Undead trainers in Undercity/Brill are lacking the new abilities to teach you.

However all trainers in Orgrimmar are able to teach you the new abilities.

**Comment by usedcars4cheap** [comment]
Ranger Canarah Kim'Alah - https://database.turtle-wow.org/?npc=80458
- also does not teach Trueshot nor Aspect of the Wolf
