### ISSUE TITLE
Jailor Eston does not drop quest items when killed when character is Enslaved

### ISSUE THREAD

**Issue by TrangOul** [slowtorta/turtlewow-bug-tracker#165]
As a warlock with a pet I started a fight with Jailor Eston. I applied my DoTs, as usual. During the fight I got Enslaved, and when still enslaved, Eston died of DoTs or killed by my pet. After the caster's death Enslave ended, but Eston's body (containing quest item: Dull Iron Key) cannot be looted.
I haven't checked if it matters if a pet is involved in the fight, or just DoTs. It may be the former, since when enslaved, the pet is treated as a hostile entity.

**Steps to reproduce the behavior:**

1. Have a combat pet.
2. Start fight with Jailor Eston in Durnholde Keep.
3. Get enslaved.
4. Let the pet kill Jailor Eston when being Enslaved.
5. Try to loot Eston body for Dull Iron Key

**IDs of affected creatures, items, quests or spells with a link to the relevant page:**

NPC: https://database.turtle-wow.org/?npc=2427
Item: https://database.turtle-wow.org/?item=3467
Quest: https://database.turtle-wow.org/?quest=498
Spell: https://database.turtle-wow.org/?spell=3442

**Expected behavior**
Jailor Eston's body is lootable, as he's been killed by player's actions.

**Workaround**
Nuke (or CC) Jailor Eston so he doesn't have a chance to cast Enslave.

**Comment by Nolin7777** [comment]
Hello and thank you for your report!

For comparison please add any evidence in form of a legit source (for example wowhead.com) or a video captured from Blizzard's Classic server for.

This ticket will be closed until more information added.
