### ISSUE TITLE
Dying in BGs doesn't teleport to nearest gy

### ISSUE THREAD

**Issue by burner1024** [slowtorta/turtlewow-bug-tracker#1650]
**Please, provide a clear description what the bug is:**
Dying in BGs doesn't teleport to nearest gy.

**Steps to reproduce the behavior with as much detail as possible:**

1. Die in BG.

**Expected behavior. Describe how it should work:**
Teleport to nearest gy owned by the faction. If that gy is attacked during waiting for ressurection, then port to the next allied gy, and so on.

**Comment by burner1024** [comment]
Actually, not limited to bgs, had the same happen in instances.

**Comment by burner1024** [comment]
It seems to be working mostly fine in AV now.

How, there's another issue: if a gy gets attacked just before you are resurrected, sometimes you're not ported to the nearest friendly gy, and have to ghost run. That happens on AB, at least. Hard to reproduce.

**Comment by ratkosrb** [comment]
Can't reproduce.

**Comment by burner1024** [comment]
Of course you can't, it's hard to reproduce. But it happens.

**Comment by burner1024** [comment]
![Captura de pantalla de 2022-08-19 18-53-56](https://user-images.githubusercontent.com/1279852/185613068-4c9120b1-f36b-412d-bd78-428b5c25b660.png)
