### ISSUE TITLE
Blood Ring doesn't teleport out on premature end

### ISSUE THREAD

**Issue by burner1024** [slowtorta/turtlewow-bug-tracker#1651]
**Please, provide a clear description what the bug is:**
If opposite side didn't accept queue, you get stuck in BR waiting room.

**Steps to reproduce the behavior with as much detail as possible:**

1. Queue BR.
2. Join.
3. Other side doesn't show up: "Not all players have accepted queue"
4. You're stuck. The only way out is HS or other teleport, along with deserter debuff.

**Expected behavior. Describe how it should work:**

Teleported back where you were when accepting invitation.

**Comment by Zebouski** [comment]
this is not fixed, still happening right now, please reopen
![image](https://user-images.githubusercontent.com/11151284/183549877-6e4f208a-a105-484a-9468-6b1f0beef6b0.png)
