### ISSUE TITLE
Spirit Link (Tauren Shaman)

### ISSUE THREAD

**Issue by xhummerx** [slowtorta/turtlewow-bug-tracker#1652]
**Please, provide a clear description what the bug is:**
Spirit Link Shaman racial does nothing after casting it since i aint sure how they want it to work i cant really explain much more
cooldown is also 30 sec instead of the intended 10 min
**Steps to reproduce the behavior with as much detail as possible:**

1. target a friendly player cast spirit link
2. targets gets buff for half a second it fades
3. nothing happend

**IDs of affected creatures, items, quests or spells with a link to the relevant page:**

Cant linkt to db since its down first week

**Expected behavior. Describe how it should work:**
should buff the target and nearby friendly players should take 15 %  of the dmg of the buffed player

**Comment by ratkosrb** [comment]
Will be fixed after https://github.com/slowtorta/turtle-wow/commit/eec5bcfe24f89091f3e87beb38ce656decebb02a
