### ISSUE TITLE
Shred Rank 6 is no different to Shred Rank 5

### ISSUE THREAD

**Issue by chloejaynebond** [slowtorta/turtlewow-bug-tracker#1654]
**Please, provide a clear description what the bug is:** The new rank of Shred 6 from the custom class book is no different to Shred Rank 5.

**Steps to reproduce the behavior with as much detail as possible:**

1. Create a druid with Shred Rank 5. Check the tool tip for Shred Rank 5: "Shred the target, causing 225% damage plus 180 to the target. Must be behind the target. Awards 1 combo point." Also check the damage the individual druid does.
2. Learn Rank 6 from the custom book: "Book of Shred VI"
3.  Compare to what is listed in step 1 and notice there is no difference.

**IDs of affected creatures, items, quests or spells with a link to the relevant page:**

NPC: https://database.turtle-wow.org/?npc=
Item: https://database.turtle-wow.org/?item= https://database.turtle-wow.org/?item=83573
Quest: https://database.turtle-wow.org/?quest=
Spell: https://database.turtle-wow.org/?spell=
Object: https://database.turtle-wow.org/?object=

**Expected behavior. Describe how it should work:** The new rank 6 of Shred should increase damage from Shred compared to rank 5.

**Comment by chloejaynebond** [comment]
tested before and after using the book on a target dummy on my friend's druid. this is only a visual bug and the damage increase from the new book is about 11.7%

**Comment by burner1024** [comment]
A visual bug is still a bug.
