### ISSUE TITLE
Avenger's Breastplate missing physical hit rate.

### ISSUE THREAD

**Issue by ReggyDawn** [slowtorta/turtlewow-bug-tracker#1655]
**Please, provide a clear description what the bug is:** Avenger's Breastplate seems to have lost it's 1% physical hit and reverted to 1% spell crit.

**IDs of affected creatures, items, quests or spells with a link to the relevant page:**

Database currently unavailable, so cannot.

**Expected behavior. Describe how it should work:**
It should instead have 1% physical hit rate, as described in changelogs.

**Comment by slowtorta** [comment]
Working as intended. It was probably an online DB display bug. 
![image](https://user-images.githubusercontent.com/66763404/200149997-00598bc2-1514-4037-a450-d570037420ab.png)
