### ISSUE TITLE
Precision talent in Protection Paladin tree not working.

### ISSUE THREAD

**Issue by ReggyDawn** [slowtorta/turtlewow-bug-tracker#1657]
**Please, provide a clear description what the bug is:**
As in the name. It does not show up in any sort of stat tracker, and I appear to be missing level 60 enemies where before I did not.

**Steps to reproduce the behavior with as much detail as possible:**

1. Simply selecting the talent and checking character sheet. 
2. Testing against dummies and/or live targets then comparing the math.

**Expected behavior. Describe how it should work:**
Should be getting 3% physical and spell hit rate from the talent.

**Comment by software-eugeneer** [comment]
+1
[https://github.com/slowtorta/turtlewow-bug-tracker/issues/2801#issuecomment-1436524942](url)

**Comment by redmagejoe** [comment]
This requires more testing to determine if it is an addon issue (is the addon reading hit from the server, or only predefined Talent IDs in the client, which may have been impacted with the class changes?) or if it is indeed a serverside issue.

**Comment by software-eugeneer** [comment]
@redmagejoe seems like you're right
[addon code](https://github.com/yutsuku/BetterCharacterStats/blob/master/helper.lua#L135)
will try to update this code in the evening

but still
according to formula from [here](https://vanilla-wow-archive.fandom.com/wiki/Hit#Calculating_Miss_Rate_for_Physical_Damage_Attacks)

I'm lvl 47 human paladin with sword fighting humanoid level 44 so 
my_weapon skill = (47 * 5) + 5(from racial) = 240
mob_defense = 44*5 = 220
difference is less than 10, so following should be correct `5% + (Defense Skill - Weapon Skill)*.1%`
5%+(220-240)*0.1% = 0.03% chance to miss
with at least 1 point Precision (and I have 2) seems like I should never miss an attack, but I am

My calculation and understanding could be wrong, but still any additional check and info from devs would be awesome!

**Comment by software-eugeneer** [comment]
Tested a bit more fighting mobs level 44-45 (still lvl 47 2h sword with 2 points precision)
per formulas from vanilla-wow
lvl44: 5%+(220-240)*0.1% = 0.03% chance to miss
lvl45: 5%+(225-240)*0.1% = 0.035% chance to miss
![image](https://user-images.githubusercontent.com/45651092/220696972-0b5699a6-c07f-4663-be50-e92a9755c7cc.png)

**Comment by software-eugeneer** [comment]
with no points spent on Precision
![image](https://user-images.githubusercontent.com/45651092/220884490-abbf93c1-2cf5-4fe1-92ed-5faca022d2bc.png)
so it seems like talent is working
My only questions would be: 
1. is it any hardcoded miss chance for melee hit?
2. is [this formulas](https://vanilla-wow-archive.fandom.com/wiki/Hit#Calculating_Miss_Rate_for_Physical_Damage_Attacks) correct for TWoW

**Comment by kingalion** [comment]
So everything is working? Missing and mot criting is just a bad luck  thing?

**Comment by redmagejoe** [comment]
Talent is working as intended with empirical evidence.

This can be closed.

**Comment by software-eugeneer** [comment]
@redmagejoe are you somehow close with dev team?
I'm really wondering formula and hard miss cap
