### ISSUE TITLE
after unlearned my new talents, old talents have appeared

### ISSUE THREAD

**Issue by NeroSoft111** [slowtorta/turtlewow-bug-tracker#1660]
**Please, provide a clear description what the bug is:**
Nickname Simfero, I play for a druid, after the reset of new talents, old talents appeared and I can't study them
I'm applying a screen
![2022-07-26_20-19-27](https://user-images.githubusercontent.com/110053693/181072866-3eddf0cb-de45-459e-a5f2-44519c38d28a.png)

**Steps to reproduce the behavior with as much detail as possible:**

1.contact the druid trainer Turak Runetotem, say "I wish unlearn my talents"

**Expected behavior. Describe how it should work:**
after unlearned my new talents, new talents remain

**Comment by slowtorta** [comment]
Please resolve it with a help of a GM with the in-game ticket!
