### ISSUE TITLE
Skinning mobs I did not kill won't yield loot.

### ISSUE THREAD

**Issue by Sygmoond** [slowtorta/turtlewow-bug-tracker#1662]
**Please, provide a clear description what the bug is:**

**Steps to reproduce the behavior with as much detail as possible:**

1. Walk to a skinnable mob who wasn't killed by you or a party member.
2. Proceed to skin.
3. Note the skill does go up, but yields no XP.

**Expected behavior. Describe how it should work:**

Skinned mob should yield some sort of leather, or leather scraps.

**Comment by Gurky-Kronos** [comment]
"Note the skill does go up, but yields no XP."

Do you mean yields no loot? Vanilla did not give xp for processions.

**Comment by Sygmoond** [comment]
> "Note the skill does go up, but yields no XP."
> 
> Do you mean yields no loot? Vanilla did not give xp for professions.

Gives no loot. Sorry, mistyped

**Comment by nonameform** [comment]
Had this issue before as hunter: pet kills an enemy, I skin it and get no skin. The same problem also happened when I was killing critters for scraps with ranged weapons.

**Comment by redmagejoe** [comment]
This issue cannot be reproduced on the latest version. I have been able to regularly follow other players around and skin their mobs.

Fixed.
