### ISSUE TITLE
(Druid) Savage Bite's inexplicable GCD category

### ISSUE THREAD

**Issue by Platinumcoated** [slowtorta/turtlewow-bug-tracker#1664]
Savage Bite's GCD category makes no sense. It's not on regular abilities GCD, but it triggers GCD on abilities which should be off GCD

**how it works:**
Regular ability GCD, caused by for example Swipe (bear), Rejuvenation, or Moonfire does not affect Savage Bite. It looks like Savage Bite doesn't conform to GCD at all. 

Savage Bite doesn't cause GCD for these regular abilities which should be on GCD (I can use Savage Bite and Swipe right after, or Rejuvenation, or Moonfire)

On the other hand, using Savage Bite puts GCD on abilities which should not be on GCD, abilities like Maul, Feral Charge, Growl (taunt), or even potions

**how it should work:**
not like this i'm sure

**Comment by Testerrosaurus** [comment]
Still bugged as of 30.08.2022

**Comment by Platinumcoated** [comment]
Server patch notes claim´that this is supposed to be fixed, but nothing has changed.

**Comment by GrizB37** [comment]
Still bugged
