### ISSUE TITLE
Young and Foolish can not interact with Quest NPC

### ISSUE THREAD

**Issue by terraform123** [slowtorta/turtlewow-bug-tracker#1666]
**Please, provide a clear description what the bug is:**

The [Young and Foolish] quest part where the player needs to talk to NPCs in Lakeshire does not work as one can not talk with Foreman Oslow (probably due to completing all his quests already previously). This bug was claimed to have been fixed in #1549 but it seems some parts are still bugged.

**Steps to reproduce the behavior with as much detail as possible:**

1. Take up quest [Young and Foolish]
2. Progress to part where one needs to interact with NPCs in Lakeshire
3. Can not talk with Foreman Oslow

**Expected behavior. Describe how it should work:**

To progress the quest, the player must be able to interact with the NPC.

![image](https://user-images.githubusercontent.com/93649249/181086813-9f6636cc-ee88-42ca-97c5-ca86af46a4be.png)

**Comment by usedcars4cheap** [comment]
Confirm Terraform123's hypothesis - Foreman Oslow and Magistrate Solomon's dialogue options are available when your character has quests still pending, but are no longer interactable once those quests are completed.

**Comment by lokhengchau** [comment]
Confirmed. Both Foreman Oslow and Magistrate Solomon won't talk.
