### ISSUE TITLE
Talents for Paladin

### ISSUE THREAD

**Issue by Tobbsu** [slowtorta/turtlewow-bug-tracker#1668]
(1): {**Shield Specialization**}: do not give mana back when you block the attack.
(2): {**Improved Seal of Justice**}: do not taunt the target - even if is not attacking you.
(3): {**Precision**}: do not give 1/2/3 hit change to melee or spell.
(4): {**Ardent Defender**} do not give reduce damage when below 35% heath.

**Comment by akzkak** [comment]
([5](https://github.com/slowtorta/turtlewow-bug-tracker/issues/1658)): {**Consecration**} Do not have increased scaling (0.042 → 0.119) 
([6](https://github.com/slowtorta/turtlewow-bug-tracker/issues/1643)): {**Retribution Aura**} Do not have scaling added: (0.033)
([7](https://github.com/slowtorta/turtlewow-bug-tracker/issues/1644)): {**Redoubt**} do not have a  2/4/6/8/10% chance to activate off of any direct attack, but instead 100% chance.

**Comment by redmagejoe** [comment]
(2) Please provide evidence of this. I've tested this for several minutes with rank 3 of the talent (it's 33% per rank on the taunt) and haven't failed to taunt yet. It even puts a taunted debuff on the enemy just like Taunt or Growl does.

**Comment by Galuur** [comment]
Issue 7 does not appear to be fixed. I am still getting 100% redoubt activation on each hit taken by mobs.
