### ISSUE TITLE
Druid: berserk doesn't remove fear

### ISSUE THREAD

**Issue by burner1024** [slowtorta/turtlewow-bug-tracker#1669]
**Please, provide a clear description what the bug is:**
Berserk doesn't remove fear.

**Steps to reproduce the behavior with as much detail as possible:**

1. Get feared.
2. Try to cast berserk. It's not usable in fear.

**IDs of affected creatures, items, quests or spells with a link to the relevant page:**
Db down.

**Expected behavior. Describe how it should work:**
Should be castable in feared state. Should clear fear.

**Comment by ratkosrb** [comment]
Can't reproduce this.
