### ISSUE TITLE
Mobs Daze to often.

### ISSUE THREAD

**Issue by BosBeest** [slowtorta/turtlewow-bug-tracker#167]
Mobs of your own level or way lower daze(https://database.turtle-wow.org/?spell=1604) you way to often. Other servers have it infrequent where "sometimes" you are being pushed of your mount and you just have to deal with the mob or kite it away(wich is already not a fun mechanic). Here it seems that every mob can Daze you indefinitely.

Druid Shapeshift should remove the Daze Effect too since it says: "The act of shapeshifting frees the caster from Polymorph and Movement Impairing effects."

**Comment by jameyboor** [comment]
Source from : https://vanilla-wow-archive.fandom.com/wiki/Daze 

Source from retail wow reddit : https://www.reddit.com/r/wow/comments/97o7ao/why_does_shapeshifting_as_a_druid_not_remove_the/

 
Shapeshifts shouldn't remove the dazed effect.

I have checked the code for the daze and the formula is completely accurate to the wiki describing the chance.

Closing this issue.
