### ISSUE TITLE
[Quest][Hunter][NPC] - This demon need to be enslaved: Solenor's freewill

### ISSUE THREAD

**Issue by aswlt** [slowtorta/turtlewow-bug-tracker#1670]
Hello there,
After killed two of them, I am now struggling with this guy, but you know I saw 3 videos about mechanics et strategies, not only those dum-dum and getting a Warlock for Curse of Reckless Rank 1, to avoid Dreadful Fright(A fleeing effect). I tried to solo it, in pre-bis raid for t1, not doable, even with a [Greater Shadow Protection Potion] + [Major Healing Potion], It's impossible to kite him, even playing with the Environemental advantage.
-Solenor can summon bugs, they're very very slow, they're not in issue.
-Solenor have a Rage effect in early, as a player, you can cleanse it with a Frozen/Freezing Trap, it work perfecly.
-Solenor's damage are accurate, his movespeed too, he's fast but it's normal.

Level: 58 - 60
Class: Elite
React: A H
Faction: [Demon] 73
Health: 18,918 - 19,193
Wealth: 4 46
Damage: 790 - 939 (Physical)
Model: 8610

Bad guy in disguise
Nelson the Nice
NPC: https://classic.wowhead.com/npc=14536
AKA
Solenor the Slayer
NPC: https://classic.wowhead.com/npc=14530

Dreadful Fright can be ONLY casted when Solenor is under Crippling Clip effect.
Spell: https://classic.wowhead.com/spell=23275
Crippling Clip, debuff applied WHEN you Wing Clip Rank 3, WC Rank 1 doesn't works, it wont trigger Crippling Clip
https://classic.wowhead.com/spell=23279

Dropping this item
Item: https://classic.wowhead.com/item=18954

Epic Hunter Quest
Quest: https://classic.wowhead.com/quest=7636

So, how It should be, simple :
-If Solenor the Slayer is under effect of Crippling Clip, applied with Wing Clip Rank 3.
-Solenor is able to cast Crippling Clip, without it he can't, that all.

Bonus: This is a good example how he can be killed without Wing Clip, by the way. This perso is doing it, naked, hunter buffs only, no assistance, no cheese.
https://www.youtube.com/watch?v=kjCCI8jMMsQ

**Comment by ratkosrb** [comment]
This should work as intended after https://github.com/slowtorta/turtle-wow/commit/66d9f22c09166e33dcb6e17592cef566c275d0eb
