### ISSUE TITLE
Grifter's Leggings are Steel Plate Legguards

### ISSUE THREAD

**Issue by madScripting** [slowtorta/turtlewow-bug-tracker#1671]
![screenshot](https://user-images.githubusercontent.com/33383366/181139054-86b8882d-8030-4b3c-b722-618178c296bd.png)

The Grifter's Leggings in the Leatherworking panel is showing the Steel Plate Legguards when mousing over the item's icon.

I did not craft the item.
I do not know if crafting the items actually gives Grifter's Leggings or Steel Plate Legguards.

Since Grifter's Leggings is a new item and the Turtle DB is down, i do not know the item ID#.

**Comment by Reignwizard** [comment]
have same problem too. please fix this

**Comment by Zulmamwe** [comment]
![image](https://user-images.githubusercontent.com/22682876/182571310-10242282-e04b-49e6-b221-78ea4a776986.png)
Have same problem, even tried to craft it once hoping that it's jsut a visual bug and will produce griefter's leggins, but it created plate

**Comment by Seberats** [comment]
Problem still there 
![image](https://user-images.githubusercontent.com/30988115/182934485-d660ae95-0c30-4cd0-a40b-4f1200b9c569.png)

**Comment by Jammyxx** [comment]
Please fix this

**Comment by slowtorta** [comment]
Fixed in the next server update. The client display might look messy but the actual crafted item will actually be correct.
