### ISSUE TITLE
Auto Loot after Tweaked Patch no longer works

### ISSUE THREAD

**Issue by TheShreen** [slowtorta/turtlewow-bug-tracker#1675]
**Please, provide a clear description what the bug is:**
After applying the patch to the EXE that creates the WoW_Tweaked.exe auto worked fine.  However after this new update the auto-loot no longer functions and you must now, once again, shift+right click to auto loot.

**Steps to reproduce the behavior with as much detail as possible:**

1. Right clicking to loot no longer auto-loots 
2. 
3. 

**IDs of affected creatures, items, quests or spells with a link to the relevant page:**

NPC: https://database.turtle-wow.org/?npc=
Item: https://database.turtle-wow.org/?item=
Quest: https://database.turtle-wow.org/?quest=
Spell: https://database.turtle-wow.org/?spell=
Object: https://database.turtle-wow.org/?object=

**Expected behavior. Describe how it should work:**

**Comment by Zmitrok1984** [comment]
Auto-loot isn't included to 1.16.1.
You need to tweak Wow.exe agian if you need auto-loot

**Comment by JoLiKMC** [comment]
Additionally, the Turtle WoW Team is not responsible for third-party additions, AddOns, or modifications made to the game beyond what comes packed with updated patches or the downloadable game client.

If you have any questions or comments about third-party additions, please either refer to the forums or the public _Discord_.

**Comment by slowtorta** [comment]
> Auto-loot isn't included to 1.16.1. You need to tweak Wow.exe agian if you need auto-loot

This is correct, you have to modify your binary once again.
