### ISSUE TITLE
Hunter Feed Pet broken

### ISSUE THREAD

**Issue by TheShreen** [slowtorta/turtlewow-bug-tracker#1676]
**Please, provide a clear description what the bug is:**
When you feed your hunter pet it starts to feed them but then ends almost immediately.

**Steps to reproduce the behavior with as much detail as possible:**

1. Log into a hunter
2. Feed your pet with feed pet skill.
3. 

**IDs of affected creatures, items, quests or spells with a link to the relevant page:**

NPC: https://database.turtle-wow.org/?npc=
Item: https://database.turtle-wow.org/?item=
Quest: https://database.turtle-wow.org/?quest=
Spell: https://database.turtle-wow.org/?spell=
Object: https://database.turtle-wow.org/?object=

**Expected behavior. Describe how it should work:**

**Comment by Zmitrok1984** [comment]
Works fine for me
![image](https://user-images.githubusercontent.com/99164611/181176073-36923ab0-aecc-4662-9a1f-21615bff0243.png)

**Comment by nonameform** [comment]
Works fine.
