### ISSUE TITLE
EZDismount broken after patch

### ISSUE THREAD

**Issue by Sagenod** [slowtorta/turtlewow-bug-tracker#1678]
All addons which provide dismount functionality stopped working immediately after the patch. 

PFUI built in dismount function does not work. 

ZDismount does not work, after deleting addon and using newest version the problem was not resolved. 

Lazypig addon Auto dismount feature also does not work, when enabled it removes the error message "You are mounted," but it does not dismount. Also deleted and installed latest version.

The only mount i have is the Turtle mount, can not test with other mounts

Please help!

**Comment by redmagejoe** [comment]
EzDismount Turtle version still works on everything but the Turtle.

**Comment by geojak** [comment]
This is an addon issue, not server issue.

You can a tually, fix this yourself, I teel you how.
All these addons work by identifying the Mount with the aporoate mount icon namw

Turtlecwow addon new custom icons with the last patch

Addons nned to be extended to account for these new icons.

That's it. Yiu can do it or ask in #addons

Close the issue
