### ISSUE TITLE
[REQUEST] Please fix the female dwarf running sound to match actual gait

### ISSUE THREAD

**Issue by goudekid** [slowtorta/turtlewow-bug-tracker#1679]
**Please, provide a clear description what the bug is:**

**Steps to reproduce the behavior with as much detail as possible:**

1. Play on a female dwarf with sound enabled
2.  Run
3.  Listen as the sound effect is lop-sided like she is limping even though she is clearly running normally

This drives me up the wall, would love if you fixed this in the client so the sound matched the run animation

**Comment by slowtorta** [comment]
I'm sorry, this sounds like a default model behavior, we cannot easily alter those :)

**Comment by goudekid** [comment]
To be clear, I want the audio file changed, not the model animation lol
