### ISSUE TITLE
Custom Quest "Grave Injustice" should be a 100% drop

### ISSUE THREAD

**Issue by blargsnarf** [slowtorta/turtlewow-bug-tracker#168]
**Please, provide a clear description what the bug is:** The quest Grave Injustice requires you to get a shovel from a Grave Robber in Duskwood. It's currently a ~20% drop, but only 3 Grave Robbers spawn in the whole world, and you have to fight all 3 at once, so it feels like it should be one of the normal 100% drop quests.

**IDs of affected creatures, items, quests or spells with a link to the relevant page:**

NPC: https://database.turtle-wow.org/?npc=218
Item: https://database.turtle-wow.org/?item=70035#dropped-by
Quest: https://database.turtle-wow.org/?quest=70054

**Expected behavior. Describe how it should work:**
Make it a 100% or at least an 80% drop, or spawn many more grave robbers.

**Comment by slowtorta** [comment]
Very well. It'll be increased to 100% on the next server update.
