### ISSUE TITLE
Warlock - Demon Portal spell not working 1.16.1

### ISSUE THREAD

**Issue by Sardes85** [slowtorta/turtlewow-bug-tracker#1680]
**Please, provide a clear description what the bug is:**
New Demon Portal spell doesnt summon any new demon Felguard. When casted, it consume Demonic figurine, plays casting animation similar to summoning other demons, felsteed or dreadsteed. When casting is finished you hear imp summoning sound and then nothing happens. It doenst matter if casted in group or without.

**Steps to reproduce the behavior with as much detail as possible:**

1. Cast new spell Demon Portal
2. Wait till spellcasting is finished
3. Nothing happens

**IDs of affected creatures, items, quests or spells with a link to the relevant page:**

DB not available

**Expected behavior. Describe how it should work:**

New spell, no idea. Perhaps it should create a clickable object, just like Ritual of Summoning, and after 2 more party members click on it, new demon Felguard got summoned.

**Comment by Sardes85** [comment]
Still not working. Any ETA when it will be implemented?

**Comment by ratkosrb** [comment]
When an issue is closed as completed, it means it has been fixed in the internal development branch. It does not mean the fix is live. You have to wait until the next patch update.
