### ISSUE TITLE
Druid / Primal Fury generating too much Combo Points/Rage

### ISSUE THREAD

**Issue by gala320** [slowtorta/turtlewow-bug-tracker#1681]
**Please, provide a clear description what the bug is:**
Primal Fury talent is currently working incorrectly: 
1) Non-critical hits from abilities used by the player generate extra combo points in Cat Form
2) Non-critical hits received generate extra rage in Bear Form

**Steps to reproduce the behavior with as much detail as possible:**

To reproduce issue from problem 1):
1. Have 2/2 Primal Fury talent
2. Enter Cat Form, use any ability
3. Observe Combo Points

To reproduce issue from problem 2):
1. Have 2/2 Primal Fury talent
2. Enter Bear Form, get hit by a monster
3. Observe Rage resource gain

**Expected behavior. Describe how it should work:**
Primal Fury should work only for critical hits done by abilities in Cat Form and critical hits received in Bear Form.

**Comment by gala320** [comment]
Demoralizing Shout also procs Primal Fury, use the shout and look in your combat log :)

**Comment by leylandpaladin** [comment]
There is also broken synergy with on-hit effects, I made an issue there:

https://github.com/slowtorta/turtlewow-bug-tracker/issues/1758

**Comment by Testerrosaurus** [comment]
Bear still has almost infinite rage as of today.
On my feral druid with Ferocity 5/5 and Primal Fury 2/2 these are my observations which i hope will be help to fix the bug:
1. Non-crit Maul does not decrease rage unless it misses or gets dodged/parried (then it decreases rage by 10 as it should).
2. Crit Maul increases rage by 5.
3. Single-target Non-crit Swipe decreases rage by 5 unless it misses or gets dodged/parried (then it decreases rage by 15 as it should).
4. Two-target Non-crit Swipe increases rage by 5 unless it misses or gets dodged/parried.
5. Three-target Non-crit Swipe increases rage by 15 it misses or gets dodged/parried.

From that i conclude that every landed Maul and Swipe hit gives 10 rage for no reason. (maybe white-hits as well but i did not pay attention/did not bother with rage calculation formula)

**Comment by Testerrosaurus** [comment]
Both Combo points and rage seem to work fine right now.
(combo points were fixed pretty fast right after 1.16.1 update and rage got fixed a few weeks after that)
I suppose this issue should be closed now.

**Comment by slowtorta** [comment]
Thanks for testing!
