### ISSUE TITLE
Druid / Omen of Clarity not proccing on offensive spell casts

### ISSUE THREAD

**Issue by gala320** [slowtorta/turtlewow-bug-tracker#1682]
**Please, provide a clear description what the bug is:**
Omen of Clarity does not proc Clearcasting when using offensive spells

**Steps to reproduce the behavior with as much detail as possible:**

1. Spec into Omen of Clarity
2. Use any offensive spell (e.g. Starfire)
3. Observe no procs happening.

**Expected behavior. Describe how it should work:**
Omen of Clarity should proc Clearcasting on offensive spells as well.

**Comment by Gurky-Kronos** [comment]
Same issue as https://github.com/slowtorta/turtlewow-bug-tracker/issues/1821
