### ISSUE TITLE
Holy strike, crusader strike, seal of judgement, seal of crusader bugs

### ISSUE THREAD

**Issue by Tinyfin-github** [slowtorta/turtlewow-bug-tracker#1683]
Holy strike bugged
Holy strike work as spell now, must as mellee:
Holy strike resisted now, must be missed
 Holy strike critical hit  not have 200% damage, must have 200% damage as mellee attack
 Holy strike not proc seals now. must proc as mellee attack
Crusader Strike bugged
Crusader Strike is removing any your judgemens from target
Crusader Strike not have critical hits
 Seal & Judgemet of Crusader bugged
Seal of Crusader not add bonus from item "Libram of Fervor"

**Comment by Drabic** [comment]
OMG this text is copypast frommy ingame ticket
