### ISSUE TITLE
Quest: The Ramulous Gem - item not dropping

### ISSUE THREAD

**Issue by studnafsson** [slowtorta/turtlewow-bug-tracker#1684]
Quest from Ironforge High elves, description says the Gem was stolen by a Trogg called Grash.
Grash is at his supposedly correct location of Gol'Bolar Quarry, close to the end of the cave in a large opening. 
Did not drop the quest item after killing him 5 times, just to check.

Should be quick to fix, I do not know the assigned IDs, as we do not have DB access. 

Thank you.
IGN: Ardum.

**Comment by slowtorta** [comment]
Fixed in the present revision.
