### ISSUE TITLE
Warrior's talent 'imroved thunder clap' is broken

### ISSUE THREAD

**Issue by Scifsyh** [slowtorta/turtlewow-bug-tracker#1686]
Warrior's talent 'imroved thunder clap' is broken

**Comment by GrenderG** [comment]
Can you please be more specific? Thanks.

**Comment by wmichon237** [comment]
This talent only decreases rage cost, has no impact on the damage of the spell.

**Comment by Scifsyh** [comment]
Rank 4 with talent show that it should damage for 55. But its damage in fact is 39. 60% increase dont work

**Comment by Austyngio** [comment]
I have rank 4 with 2/3 talents and only 51 dmg (due to mob armor). not getting the dmg increase
