### ISSUE TITLE
Repaired electro-lanthern can't be learned

### ISSUE THREAD

**Issue by burner1024** [slowtorta/turtlewow-bug-tracker#1687]
**Please, provide a clear description what the bug is:**

Pattern requires 60 survival, but unusable even with 150.

![Captura de pantalla de 2022-07-27 20-22-58](https://user-images.githubusercontent.com/1279852/181257796-945c2d56-e715-4fef-836f-afdce14239b3.png)
![Captura de pantalla de 2022-07-27 20-23-06](https://user-images.githubusercontent.com/1279852/181257807-9762d38c-d11e-459d-b0f8-c3b686b4fc15.png)

**Steps to reproduce the behavior with as much detail as possible:**

1. Get the pattern
2. Try to learn

**IDs of affected creatures, items, quests or spells with a link to the relevant page:**
Db down.

**Expected behavior. Describe how it should work:**
Should be learnable.

**Comment by slowtorta** [comment]
Please clean your WDB folder, it's fixed now.
