### ISSUE TITLE
you don't gain the explorer title after finishing exploring

### ISSUE THREAD

**Issue by Tinyfin-github** [slowtorta/turtlewow-bug-tracker#1690]
you don't gain the explorer title after finishing exploring

**Comment by JoLiKMC** [comment]
Depending on how literal the "Explorer" title requirements are, there are a lot of potential places that the player can miss without intending to.  I'm assuming the Explorer title requirements is limited only to places that give "discovery XP", though.

To my limited research, in _World of Warcraft_ v1.12.1 / _Classic_, there are 485 different named locations and 27 instances.
_Turtle WoW_ adds several more of both, many of which don't give the player exploration XP.
There is also no way to track which ones a player has already triggered.

How would a player know that they've _actually_ found every single place in the game?

**Comment by slowtorta** [comment]
Fixed in the next revision.
