### ISSUE TITLE
Priest - Pain Spike does not consume Inner Focus effect

### ISSUE THREAD

**Issue by JustAnima9** [slowtorta/turtlewow-bug-tracker#1691]
**Please, provide a clear description what the bug is:**
 Casting Pain Spike does not consume Inner Focus effect.

**Steps to reproduce the behavior with as much detail as possible:**
1. cast Innter focus
2.  cast Pain Spike

**Expected behavior. Describe how it should work:**
The inner focus should be consumed, reducing the mana cost and increasing crit chance for Pain Spike

**Comment by ratkosrb** [comment]
Fixed by https://github.com/slowtorta/turtle-wow/commit/8ec03b3af91a4fc822175282f70338a4887c1d23
