### ISSUE TITLE
High Elf Starting Weapon Inconsistency (Post 1.16.1)

### ISSUE THREAD

**Issue by JoLiKMC** [slowtorta/turtlewow-bug-tracker#1698]
When creating a high elf character, one kind of weapon is shown in their hands.  When _finalizing_ a high elf character, they're equipped with something entirely different.

**Steps to reproduce the behavior with as much detail as possible:**
1. Log in to _Turtle WoW_ using the official game client.
2. Click "Create New Character".  Select "High Elf" for the race.  Gender, Class, and Name don't matter.
3. Take note of the weapon in the character's hand, then click "Accept".
4. Examine the newly-created character.  The weapon they start with is different from what was shown in Step 3.

**Expected behavior. Describe how it should work:**
The character should be finalized with the same weapon they were created with.

**Further notes:**
I'm re-opening / remaking this bug report because it still hasn't been fixed despite the "fixed" status and label.

Here are the weapons that appear in the Character Creator, followed by what the player actually ends up with:
- _Warrior_
**Scratched Claymore** -> Worn Shortsword, Worn Thalassian Shield
(This one's particularly odd since the preview shows a _two-handed weapon_ while the character gets a _one-hander_.)
- _Hunter_
**Scuffed Dagger** -> Worn Dagger
- _Rogue_
**Scuffed Dagger** -> Worn Dagger
- _Priest_
**Blackrock Mace** (?) -> Worn Mace
(The weapon in question _looks_ like a Blackrock Mace.  No other model in Vanilla matches it.)
- _Mage_
**Apprentice's Staff** (?) -> Bent Staff
(The weapon in question _looks_ like the Apprentice's Staff from _The Burning Crusade._  No other model in Vanilla matches it.)
- _Paladin_
**Scratched Claymore** -> Battleworn Bastard Sword

Not to put too fine a point on it, but this is still _just a cosmetic thing_ and obviously has no impact on gameplay or anything important.  But, hey.  It _is_ a bug – or at least an "oversight" of some kind.  It wouldn't be until Retail v5.0.1 that the player could preview what their character would look like completely decked out in high-level gear.

**Relevant screenshots:**
![116-1_HelfWeaponry](https://user-images.githubusercontent.com/102710555/180888227-acd05618-9584-43b4-9c4b-e9522f6efc37.jpg)
_The character creation weapon is not the same as what's given upon creation._

**See also:**
- #1535 
(The original issue from 1.16.0, not fixed.)

**Comment by slowtorta** [comment]
Fixed partly server-side next week / partly client-side in 1.16.4.
