### ISSUE TITLE
Paladin: Crusader strike lower ranks visually refresh duration only

### ISSUE THREAD

**Issue by Rykenwolf** [slowtorta/turtlewow-bug-tracker#1699]
**Please, provide a clear description what the bug is:**
Once a higher rank (rank 5) of crusader strike debuff is on a target, a lower rank of crusader strike when applied will visually reset the 30second duration on the debuff, but in reality the time doesn't reset and the debuff when expire based on time of last used highest rank.

**Steps to reproduce the behavior with as much detail as possible:**

1. Apply rank five crusader strike, observe debuff and 30sec duration 
2.  Apply rank four or lower crusader strike, observe debuff duration reset to 30sec
3. Observe as the debuff drops off in accordance with time left from initial rank five application, despite the debuff visually showing more time left 

**IDs of affected creatures, items, quests or spells with a link to the relevant page:**
Database unavailable 

**Expected behavior. Describe how it should work:**
Depending on design: Crusader strike lower ranks should refresh the debuff duration in accordance with visual state currently, or the visual debuff duration should not reset at all visually

**Comment by Zeyla-TW** [comment]
I assume this no longer applies after recent changes, but if it is then it's more likely a problem with the addon you're using to track debuff durations at this point, as my personal addon for debuff durations no longer has this issue. Gonna consider this solved for now but we can re-open it if another technical issue is found.
