### ISSUE TITLE
Bug: Tonal Stone: Kamio

### ISSUE THREAD

**Issue by Pythol** [slowtorta/turtlewow-bug-tracker#17]
**Current behavior**:  When you use the Tonal Stone: Kamio a mob in your vicinity will be "attacked" - i realized this when i pressed the tone and my pet suddenly attacked a critter like a deer or a rat. The last time it happened was my pet was dismissed and i used the stone in Orgrimmar and suddenly the neutral tauren mob in the inn attacked me.

**Expected behavior**:  Well it should only play music

**Proofs**:  X

**Steps to reproduce**:

1. Stand next to a neutral mob like a boar in a starting area and use the "Tonal Stone: Kamio"
2. 
3.

**Comment by slowtorta** [comment]
Thanks for reporting it. It's fixed and will be deployed on the next server update.
