### ISSUE TITLE
Quest: Defias of Duskwood is broken

### ISSUE THREAD

**Issue by TheShreen** [slowtorta/turtlewow-bug-tracker#1700]
**Please, provide a clear description what the bug is:**
When killing the mobs required for quest I was stuck at 3/10 on Defias Enchanters and 5/15 on Defias Night Runners. Killing more of each did not progress the quest. Killing more enchanters did not give me credit and killing more Night Runners also did not give me credit.

**Steps to reproduce the behavior with as much detail as possible:**

1. Get Quest kill mobs watch the progress stop. 
2. 
3. 

**IDs of affected creatures, items, quests or spells with a link to the relevant page:**

NPC: https://database.turtle-wow.org/?npc=
Item: https://database.turtle-wow.org/?item=
Quest: https://database.turtle-wow.org/?quest=
Spell: https://database.turtle-wow.org/?spell=
Object: https://database.turtle-wow.org/?object=

**Expected behavior. Describe how it should work:**

**Comment by TheShreen** [comment]
UPDATE: Quest was completed it's just that the numbers were not incrementing!

**Comment by JoLiKMC** [comment]
A very similar thing happens with [Bristleback Aggression](https://database.turtle-wow.org/?quest=60150) _([Google cached](https://webcache.googleusercontent.com/search?q=cache:CU4A3eOoVqYJ:https://database.turtle-wow.org/%3Fquest%3D60150+&cd=3&hl=en&ct=clnk&gl=us))_ in that the counter for Bristleback Quilboars will sometimes stop counting or even reset, despite the quest working fine.

**Comment by slowtorta** [comment]
Please clear your WBD folder.
