### ISSUE TITLE
Paladin: Sanctified Command does not work

### ISSUE THREAD

**Issue by Rykenwolf** [slowtorta/turtlewow-bug-tracker#1701]
**Please, provide a clear description what the bug is:**
New talent 'Sanctified Command' in Retribution not working at all

**Steps to reproduce the behavior with as much detail as possible:**

1. Choose 2/2 talents of Sanctified Command
2. Cast Seal of Command, get enemy player priest to cast dispel on paladin, watch as Seal of Command is removed 100% of the time
3. Cast Seal of Command, cast Judgement on target, observe as no mana is returned to paladin or group

**IDs of affected creatures, items, quests or spells with a link to the relevant page:**
Database not available

**Expected behavior. Describe how it should work:**
As per tooltip, should return 20% base mana cost of Seal of Command to group, and should resist dispel 90% of the time

**Comment by ratkosrb** [comment]
Fixed in https://github.com/slowtorta/turtle-wow/commit/3832250c1a2afcdcac65dccf7f4b1baa7ff422e7
