### ISSUE TITLE
Priest : Reflective Shields talent does not work

### ISSUE THREAD

**Issue by JustAnima9** [slowtorta/turtlewow-bug-tracker#1703]
**Please, provide a clear description what the bug is:**
Reflective Shields talent does not reflect any damage to enemy mobs

**Steps to reproduce the behavior with as much detail as possible:**
1. Select Reflective shields talent
2. Cast a PW:Shield on yourself
3. Aggro a mob

**Expected behavior. Describe how it should work:**
Spell should reflect 20% od incoming damage back to it's attacker

**Comment by Zebouski** [comment]
> This was fixed earlier today, fix should be already live.

please reopen, this is not fixed at the moment
![pve meele](https://cdn.discordapp.com/attachments/810850727215104050/1003764900058910871/unknown.png)
![pve spells](https://user-images.githubusercontent.com/11151284/182244400-497300f5-691b-4536-8306-62acff6520c4.png)
![pvp meele does work though](https://cdn.discordapp.com/attachments/810850727215104050/1003764637428371588/unknown.png)

**Comment by pchigrin** [comment]
It still doesn't work for PvE

**Comment by ratkosrb** [comment]
Will be fixed in https://github.com/slowtorta/turtle-wow/commit/1300df08b7f62e64b146c91a6b22e88f98f46d8c
