### ISSUE TITLE
Shaman: Clearcasting

### ISSUE THREAD

**Issue by ylfek** [slowtorta/turtlewow-bug-tracker#1709]
**Please, provide a clear description what the bug is:*
*Elemental Power talent procs fine, i can see 2 stacks of clearlasting, but when I cast spell it has normal mana cost

**Steps to reproduce the behavior with as much detail as possible:**

1.i cast spell, passive procs
2. can see 2 stacks, so i cast another spell
3. cost didnt change either for shocks or lightning bolt

**IDs of affected creatures, items, quests or spells with a link to the relevant page:**

NPC: https://database.turtle-wow.org/?npc=
Item: https://database.turtle-wow.org/?item=
Quest: https://database.turtle-wow.org/?quest=
Spell: https://database.turtle-wow.org/?spell=
Object: https://database.turtle-wow.org/?object=

**Expected behavior. Describe how it should work:**

**Comment by Niqlo** [comment]
I am not having this issue, when clearcasting procs from either melee or spell I can see my Earthshock go from 450-270 mana
