### ISSUE TITLE
Disconnected while in party leads to inconsistent party zombie state

### ISSUE THREAD

**Issue by OriusKhan** [slowtorta/turtlewow-bug-tracker#1713]
**Please, provide a clear description what the bug is:**
There seems to be a drastic increase in random disconnects since the major update a day or 2 ago. The specific issue I'm reporting is related to that: When you're in a party and get D/C'd, upon logging back in SOMETIMES (fairly often) everything on the UI will indicate that you're NOT in a party. Party frames, hitting F2-F5, trying to type in /p party chat, etc. However, everyone else in the party still sees you as being in the group. Since your client thinks you're not in a party, there's no way for you to leave it either.

Requires the party leader to kick you from the group, and then re-invite. Everything seems to work as expected after that. If the leader of the party has this happen to them while in a dungeon, they re-appear outside the dungeon when logged back in, and there's no way for the group to get them back inside. (ie. Everyone has to drop party and the dungeon gets reset...)

**Steps to reproduce the behavior with as much detail as possible:**

1. Be in a party.
2. Get disconnected.
3. Log back in.

**IDs of affected creatures, items, quests or spells with a link to the relevant page:**

**Expected behavior. Describe how it should work:**
You should still be in the party when logging back in after getting disconnected. Alternatively if that is not the desired behavior, then you should be fully removed from the party, not partially.

**Comment by slowtorta** [comment]
Sorry, but it's impossible to reproduce.
