### ISSUE TITLE
Paladin : Shield Specialization returns 2 mana instead of 2% mana

### ISSUE THREAD

**Issue by voodoom-fr** [slowtorta/turtlewow-bug-tracker#1716]
**Please, provide a clear description what the bug is:**
When you block an attack with the "Shield Specialization" talent, you get 2 mana back instead of 2% mana.

**Steps to reproduce the behavior with as much detail as possible:**

1. Learn the "Redoubt" and "Shield Specialization" talents.
2. Attack a mob and wait for "Lasting Defense" to proc.
3. You get 2 mana instead of 2% of your mana.

**Expected behavior. Describe how it should work:**
You should get 2% of your mana back when "Lasting Defense" does proc, but instead you get 2 mana.

**Comment by ratkosrb** [comment]
I tested it and I get 2% of total mana, not just 2 mana.

![WoWScrnShot_072922_185656](https://user-images.githubusercontent.com/35845488/181798514-ae01f616-a36e-45fe-a17b-e88f1fd284a6.jpg)

**Comment by voodoom-fr** [comment]
Fixed.
