### ISSUE TITLE
Druid Primal Fury Talent Bug

### ISSUE THREAD

**Issue by Jammyxx** [slowtorta/turtlewow-bug-tracker#1717]
**Please, provide a clear description what the bug is:**
Primal Fury talent, Instead of on crit, it is giving 5 rage on every hit, and also when this talent is taken most of the druid bear form abilities dont consume rage, essentially giving druid unlimited rage in bear, Also using Demoralising roar generates 5 free rage.
**Steps to reproduce the behavior with as much detail as possible:**

1. Turn into bear
2.  Hit stuff
3.  Use demo roar

**IDs of affected creatures, items, quests or spells with a link to the relevant page:**

NPC: https://database.turtle-wow.org/?npc=
Item: https://database.turtle-wow.org/?item=
Quest: https://database.turtle-wow.org/?quest=
Spell: https://database.turtle-wow.org/?spell=
Object: https://database.turtle-wow.org/?object=

**Expected behavior. Describe how it should work:**

**Comment by ratkosrb** [comment]
It will be fixed in the next client patch.
