### ISSUE TITLE
Blood Frenzy Druid Talent Bug

### ISSUE THREAD

**Issue by Jammyxx** [slowtorta/turtlewow-bug-tracker#1718]
**Please, provide a clear description what the bug is:**
The attack speed bonus is not granted when Enrage or Tigers fury are active, Also does not generate the 10 free rage for Bear form.
**Steps to reproduce the behavior with as much detail as possible:**

1. Shift to bear or cat
2.  use tigers fury or enrage
3.  check character screen (no atk speed increase)

**IDs of affected creatures, items, quests or spells with a link to the relevant page:**

NPC: https://database.turtle-wow.org/?npc=
Item: https://database.turtle-wow.org/?item=
Quest: https://database.turtle-wow.org/?quest=
Spell: https://database.turtle-wow.org/?spell=
Object: https://database.turtle-wow.org/?object=

**Expected behavior. Describe how it should work:**

**Comment by Platinumcoated** [comment]
already reported https://github.com/slowtorta/turtlewow-bug-tracker/issues/1624
