### ISSUE TITLE
Some hair dye options missing for High Elves

### ISSUE THREAD

**Issue by tmt01** [slowtorta/turtlewow-bug-tracker#172]
High Elf Hair Dye: Cinnamon Brown (https://database.turtle-wow.org/?item=80653) item is not sold by the barber NPC, unlike other existing dyes for high elves. Blue hair dye item does not exist at all, despite blue color being available at character creation.

**Comment by slowtorta** [comment]
Thanks for reporting it. It'll be fixed on the next server restart. Make sure to clear your WDB folder.
