### ISSUE TITLE
*Not an emergency* Cactus floaters

### ISSUE THREAD

**Issue by FeyfolkenFantasy** [slowtorta/turtlewow-bug-tracker#1722]
**Please, provide a clear description what the bug is:**

There are two cactus floaters located between the Sparkwater Mine and Sparkwater Port in Durotar.

![floaters](https://user-images.githubusercontent.com/102554573/181788744-1b1a575d-5e97-4258-8a98-652adcede67e.jpg)

**Steps to reproduce the behavior with as much detail as possible:**

1. Go to Sparkwater Port.
2. Locate the group of cactus between the mine and the city.
3. See that two of them have started there ascendance to the stars!

**Expected behavior. Describe how it should work:**

I agree with Turtle Dev'. Cactus shall be able to fly!

**Comment by slowtorta** [comment]
Thanks for reporting it, I'll move it to our internal client bug tracker :)
