### ISSUE TITLE
Northern Arathi Highlands has terrain gaps in the seam that connects it to the southern half.

### ISSUE THREAD

**Issue by Massie323** [slowtorta/turtlewow-bug-tracker#1725]
**Please, provide a clear description what the bug is:**
I've noticed a spot along the seam that connects northern Arathi Highlands with the rest of AH, where the terrain doesn't match the seam, creating a clearly visible gap. The gap is not just cosmetic but an actual hole in the collision mesh so spells like Eagle Eye can be used through it, and if you can shrink the model down far enough you could potentially fall through the world. I don't know yet if there are more spots like these, but it is easy to see that the holes only appear between the seams of the two map sections (the minimap shows clear discoloration that seperates the custom northern section of AH vs. the vanilla southern section of AH.)
**Steps to reproduce the behavior with as much detail as possible:**

1. Go to the marked location provided in the screenshot.
2. Observe the gap.

![WoW_zUUOTyvLWU](https://user-images.githubusercontent.com/57675820/181806945-4cfe5463-0695-43b1-bef1-dae2da4fcb22.jpg)
![WoW_pe5t70v7tA](https://user-images.githubusercontent.com/57675820/181806965-64724b49-ab2f-48eb-a973-d104678b464f.jpg)
![WoW_652V9geH0U](https://user-images.githubusercontent.com/57675820/181806972-59a1a3ad-bdcb-4500-9092-27a4cd53209e.jpg)

**Comment by slowtorta** [comment]
This is a client issue, moving this to the internal client tracker.

**Comment by slowtorta** [comment]
Fixed in 1.16.4.
