### ISSUE TITLE
Lethon has a buggy aggro/reaggro range

### ISSUE THREAD

**Issue by Zebouski** [slowtorta/turtlewow-bug-tracker#1727]
**Please, provide a clear description what the bug is:**
Lethon (currently in feralas on live right now) will aggro almsot from the water, where he used to aggro from the bottom of the stairs. He also will re-aggro when resetting, immediately and spam the chat

**Steps to reproduce the behavior with as much detail as possible:**

1. go to feralas green dragon area on live
2. approach lethon, see him aggro early
3. go midway into the water to see him constantly aggro/deaggro/reaggro again and again

**IDs of affected creatures, items, quests or spells with a link to the relevant page:**

NPC: https://database.turtle-wow.org/?npc=14888

**Expected behavior. Describe how it should work:**
he should only pull from the base of the stairs. he should also fully reset back to his home spot before reaggroing

**Comment by redmagejoe** [comment]
This issue can no longer be reproduced. Lethon appears to have normal aggro range on current version (level 60 can be just below him on his ramp without pulling).

Fixed.
