### ISSUE TITLE
brd arena banner of provocation issues

### ISSUE THREAD

**Issue by geojak** [slowtorta/turtlewow-bug-tracker#1729]
**Please, provide a clear description what the bug is:**

we killed the brd arena banner of provocation t0.5 fight.
first we killed the dwarf and i looted my quest item immidielty, then we killed the remaining dues.

after the last boss died the loot box spawned for 1 sec and despawned immideitly.

our group was therfore ripped of their loot

secndly after we had killed the trash wave before the boss, we were permaetly stuck in combar for the total remiander of the dungeon run

**Steps to reproduce the behavior with as much detail as possible:**

1. go brd arena
2.  use banner of provocation t0.5 item
3. after trash wave yo uare stack in combar
4. after you killed the boss wave the loot box despawns immidiely

https://database.turtle-wow.org/?quest=9015
https://database.turtle-wow.org/?item=21986

**Expected behavior. Describe how it should work:**

no stuck in combat
no despawning loot box

**Comment by SabineWren** [comment]
Can confirm. That loot despawn happened the second time I did this event (without the quest).

Stuck in combat is probably a separate bug. I don't see an issue for it, but it happens occasionally in raids. Current workaround is for everyone to relog.

**Comment by redmagejoe** [comment]
This event seems to work mostly properly, except you are placed in combat and stuck in combat the moment you place the Banner of Provocation. The banner must be placed before starting the Arena event to replace the Arena boss with Theldren's team, so you cannot complete this event after you have already completed the Arena event.

Current issues:
The box despawns after about a minute. The box SHOULD NOT despawn at all until it is looted.
Combat should not be initiated by the banner itself, and should be cleared properly when not in combat.
