### ISSUE TITLE
Stormstrike Rank 2 Cannot Proc Shaman Weapon Imbues

### ISSUE THREAD

**Issue by Niqlo** [slowtorta/turtlewow-bug-tracker#1731]
**Please, provide a clear description what the bug is:**
Stormstrike Rank 1 is able to proc all shaman weapon imbues (windfury, frostbrand, flametongue). Rank 2 is currently not able to proc any of them. It still benefits from rockbiter, however.

https://imgur.com/a/ecdebkB

Rank 2 stormstrike shows as a yellow hit.

**Steps to reproduce the behavior with as much detail as possible:**

1. Spec out of and back into stormstrike so you have rank 1 and rank 2 (rank 1 is removed on logout)
2. Cast any shaman weapon imbue with a proc (windfury, frostbrand, flametongue). flametongue is the easiest to see the issue.
3. Cast rank 1 stormstrike, it will do fire damage as well from flametongue. Cast rank 2 stormstrike, it will not do fire damage.

**IDs of affected creatures, items, quests or spells with a link to the relevant page:**

Spell: https://database.turtle-wow.org/?spell=17364

I don't think I can link to rank 2 stormstrike in the database.

**Expected behavior. Describe how it should work:**
Rank 2 stormstrike should proc shaman weapon imbues just like rank 1.

**Comment by meebybell** [comment]
Thought I'd mention that although it appears that rockbiter is working properly, it isn't. The on-hit component is the threat, not the extra damage. Your attack power is increased by rockbiter directly, mean you do extra damage with anything that uses attack power regardless of whether the on hit effect works.

**Comment by Melphoone** [comment]
also to mention on flametongue is, that it´s not applied to every weapon swing on lvl 60+ mobs. it doesn´t even is showsn in the combat log (no resist or something)

**Comment by Niqlo** [comment]
Issue has returned but affects rank 1 stormstrike as well now. Both are yellow hits so neither procs weapon enhancements,

**Comment by twowTurtReynolds** [comment]
Should be fixed next restart :)
