### ISSUE TITLE
The Southsea Sandbar is named SOUNDBAR on World Map

### ISSUE THREAD

**Issue by Shellyoung** [slowtorta/turtlewow-bug-tracker#1735]
**Please, provide a clear description what the bug is:**
![sandbar](https://user-images.githubusercontent.com/40469927/181904128-352b8356-afaf-4a0a-9a81-9eea1c23f3ed.png)
![soundbar](https://user-images.githubusercontent.com/40469927/181904131-b53dbee8-4d7f-4ea3-9141-9b8eeb231895.png)

**Expected behavior. Describe how it should work:**
The area should be named "The Southsea Sandbar".

[Sandbar](https://dictionary.cambridge.org/dictionary/english/sandbar) — a long raised area of sand below the surface of the water, especially where a river enters the sea, usually formed by moving currents.
![sandba_noun_002_32058](https://user-images.githubusercontent.com/40469927/181904294-5be09ead-1bd0-4ed7-acb0-a7d16a0c85aa.jpg)

**Comment by slowtorta** [comment]
Was fixed in 1.16.2.
