### ISSUE TITLE
Sanctity aura not work

### ISSUE THREAD

**Issue by Lancelot7622** [slowtorta/turtlewow-bug-tracker#1739]
**Please, provide a clear description what the bug is:**

**Steps to reproduce the behavior with as much detail as possible:**

1.https://database.turtle-wow.org/?spell=20218
2. Sanctity Aura not work
3. проверил на вех боевых заклинаниях паладина святой урон не повышается

**IDs of affected creatures, items, quests or spells with a link to the relevant page:**

NPC: https://database.turtle-wow.org/?npc=
Item: https://database.turtle-wow.org/?item=
Quest: https://database.turtle-wow.org/?quest=
Spell: https://database.turtle-wow.org/?spell=
Object: https://database.turtle-wow.org/?object=

**Expected behavior. Describe how it should work:**

**Comment by Lancelot7622** [comment]
https://database.turtle-wow.org/?spell=20218 проверил на всех заклинаниях паладина не работает аура святой урон не повышается

**Comment by Zmitrok1984** [comment]
You are wrong.
First screenshot - consecration tick with aura:
![image](https://user-images.githubusercontent.com/99164611/181917751-6e5a571a-e9fc-410c-acd9-9840938fdfe7.png)
Second screenshot - consecration tick without aura:
![image](https://user-images.githubusercontent.com/99164611/181917814-fb0da23d-57c7-4afb-8636-6293d275c34a.png)

**Comment by ratkosrb** [comment]
It definitely works.
