### ISSUE TITLE
ZF zombies/dead heroes aggro bug

### ISSUE THREAD

**Issue by afizzler** [slowtorta/turtlewow-bug-tracker#174]
The expected behavior is when clicking on the shallow grave in Zul’farrak, any zombies and dead heroes should first go move towards Witch Doctor Zum’rah before aggroing onto the player who clicked on the shallow grave. This behavior is bugged on this server since any zombies or dead heroes spawned from clicking on shallow graves immediately aggro onto you.

Video of how aggro behavior should work from a classic mage PoV: https://youtu.be/V7dvoljg8DA

1. Click on a shallow grave
2. ZF zombie or dead hero spawns

Shallow Grave: https://database.turtle-wow.org/?object=128308
Witch Doctor Zum’vah: https://database.turtle-wow.org/?npc=7271
Zul’farrak Zombie: https://database.turtle-wow.org/?npc=7286
Zul’farrak Dead Hero: https://database.turtle-wow.org/?npc=7276

**Comment by Turvek** [comment]
Tested yesterday, I can confirm they don't run toward the boss but directly goes on you.

**Comment by Nolin7777** [comment]
Fixed after next maintenance.
