### ISSUE TITLE
The Old Church of Westfall is not an obstacle for Blink spell

### ISSUE THREAD

**Issue by Shellyoung** [slowtorta/turtlewow-bug-tracker#1743]
**Please, p
![WoW_GgR1Wpzm9n](https://user-images.githubusercontent.com/40469927/181933656-7524694a-e4c4-484e-b415-c32ee964d942.gif)
rovide a clear description what the bug is:**

**Steps to reproduce the behavior with as much detail as possible:**

1. Go to The Old Church of Westfall
2. Face it.
3. Cast Blink.

**IDs of affected creatures, items, quests or spells with a link to the relevant page:**

Object: https://database.turtle-wow.org/?object=6000004

**Expected behavior. Describe how it should work:**
The church should be an obstacle for Blink spell

**Comment by slowtorta** [comment]
Unable to reproduce, couldn't blink through the church.

**Comment by Shellyoung** [comment]
I just did

**Comment by slowtorta** [comment]
It might get fixed for you when we generated server-side maps for the next Patch 1.16.4, not earlier.
