### ISSUE TITLE
quest - Your place in the world

### ISSUE THREAD

**Issue by zasnool** [slowtorta/turtlewow-bug-tracker#1744]
1. Create a Horde character of a race other than Troll or an Orc
2. Go to Durotar orc starting area
4. quest is not available

NPC: https://classic.wowhead.com/npc=3143
Quest: https://classic.wowhead.com/quest=4641

Either this [quest](https://classic.wowhead.com/quest=4641/your-place-in-the-world)
![image](https://user-images.githubusercontent.com/100788360/181936135-94d50a82-d3ce-4abd-9abb-e861a176d3a4.png)
or [the new horde](https://classic.wowhead.com/quest=787/the-new-horde)
![image](https://user-images.githubusercontent.com/100788360/181936179-8ef9e610-1de4-47bd-b4e9-c574bd78a433.png)
should be available to the Horde characters of race other than orc or a troll so that you can start the questing in Durotar instead of your races specific starting location.

You closed my other bug report without really resolving it, and i don't know if you will ever look at a closed issue. So according to #1707 example I am creating the new report just in case.

**Comment by slowtorta** [comment]
I'm going to make The New Horde available again :)
