### ISSUE TITLE
Error #132 error with full error log

### ISSUE THREAD

**Issue by Trinitygam3r** [slowtorta/turtlewow-bug-tracker#1746]
**Please, provide a clear description what the bug is:**

**Steps to reproduce the behavior with as much detail as possible:**

1.
2. 
3. 

**IDs of affected creatures, items, quests or spells with a link to the relevant page:**

NPC: https://database.turtle-wow.org/?npc=
Item: https://database.turtle-wow.org/?item=
Quest: https://database.turtle-wow.org/?quest=
Spell: https://database.turtle-wow.org/?spell=
Object: https://database.turtle-wow.org/?object=

**Expected behavior. Describe how it should work:**

I've been playing this game for over a month without any issues. I'm now on a particular mission just outside of IronForge (killing headhunters in their cave). As soon as I enter their cave I get kicked out with an Error #132. I've played this area before without any issues (prior to the recent update).
I tried downloading a fresh copy of the client which did not fix the issue.
I also tried disabling my antivirus to see if that was causing an issue ... it did not.
I'm at my wits end... can anyone help?
Here is the entire error log:

==============================================================================
World of WarCraft (build 5875)

Exe:      D:\Games\WOW Turtle\WoW.exe
Time:     Jul 30, 2022  8:41:00.951 PM
User:     frank
Computer: MSI
------------------------------------------------------------------------------

This application has encountered a critical error:

ERROR #132 (0x85100084) Fatal Exception
Program:	D:\Games\WOW Turtle\WoW.exe
Exception:	0xC0000005 (ACCESS_VIOLATION) at 0023:006D6AD0

The instruction at "0x006D6AD0" referenced memory at "0x00000000".
The memory could not be "read".

WoWBuild: 5875
------------------------------------------------------------------------------

----------------------------------------
    x86 Registers
----------------------------------------

EAX=00000000  EBX=000000C8  ECX=00000000  EDX=00000000  ESI=0019F8E8
EDI=00000000  EBP=0019F8D0  ESP=0019F8B8  EIP=006D6AD0  FLG=00010246
CS =0023      DS =002B      ES =002B      SS =002B      FS =0053      GS =002B

----------------------------------------
    Stack Trace (Manual)
----------------------------------------

Address  Frame    Logical addr  Module

006D6AD0 0019F8D0 0001:002D5AD0 D:\Games\WOW Turtle\WoW.exe
006D2FD6 0019FA58 0001:002D1FD6 D:\Games\WOW Turtle\WoW.exe
006D25D9 0019FB9C 0001:002D15D9 D:\Games\WOW Turtle\WoW.exe
006D45A0 0019FBC8 0001:002D35A0 D:\Games\WOW Turtle\WoW.exe
0066FE82 0019FBE4 0001:0026EE82 D:\Games\WOW Turtle\WoW.exe
0048329C 0019FC88 0001:0008229C D:\Games\WOW Turtle\WoW.exe
00482E73 0019FD14 0001:00081E73 D:\Games\WOW Turtle\WoW.exe
0076FC31 0019FD30 0001:0036EC31 D:\Games\WOW Turtle\WoW.exe
007658E7 0019FD54 0001:003648E7 D:\Games\WOW Turtle\WoW.exe
0076434C 0019FD60 0001:0036334C D:\Games\WOW Turtle\WoW.exe
0044264E 0019FE28 0001:0004164E D:\Games\WOW Turtle\WoW.exe
004246B0 0019FE5C 0001:000236B0 D:\Games\WOW Turtle\WoW.exe
0042106F 0019FECC 0001:0002006F D:\Games\WOW Turtle\WoW.exe
00420BF1 0019FEE4 0001:0001FBF1 D:\Games\WOW Turtle\WoW.exe
0040411E 0019FF74 0001:0000311E D:\Games\WOW Turtle\WoW.exe
77417BA9 0019FF84 0001:00007BA9 C:\WINDOWS\System32\KERNEL32.DLL
77ABBB3B 0019FFDC 0001:0006AB3B C:\WINDOWS\SYSTEM32\ntdll.dll
77ABBABF 0019FFEC 0001:0006AABF C:\WINDOWS\SYSTEM32\ntdll.dll

----------------------------------------
    Stack Trace (Using DBGHELP.DLL)
----------------------------------------

006D6AD0 WoW.exe      <unknown symbol>+0 (0x00000000,0x0019FA8C,0x19DD6808,0x00000000)

----------------------------------------
    Loaded Modules
----------------------------------------

0x00400000 - 0x00D06000  D:\Games\WOW Turtle\WoW.exe
0x02DE0000 - 0x02E49000  D:\Games\WOW Turtle\DivxDecoder.dll
0x10000000 - 0x10096000  D:\Games\WOW Turtle\fmod.dll
0x14A60000 - 0x14AE3000  C:\Program Files\Logitech Gaming Software\SDK\LCD\x86\LgLcdApi.dll
0x31020000 - 0x31138000  D:\Games\WOW Turtle\dbghelp.dll
0x50020000 - 0x50088000  C:\Program Files\Norton Security\NortonData\22.20.5.39\Definitions\BASHDefs\20220727.011\UMEngx86.dll
0x50090000 - 0x5010A000  C:\WINDOWS\SYSTEM32\AcSpecfc.DLL
0x50CE0000 - 0x50CF0000  C:\WINDOWS\SYSTEM32\resourcepolicyclient.dll
0x50D00000 - 0x50D3B000  C:\WINDOWS\SYSTEM32\wdmaud.drv
0x534B0000 - 0x534B8000  C:\WINDOWS\SYSTEM32\midimap.dll
0x53500000 - 0x5351F000  C:\WINDOWS\SYSTEM32\winmmbase.dll
0x55940000 - 0x55982000  C:\WINDOWS\SYSTEM32\GLU32.dll
0x55FD0000 - 0x55FDB000  C:\WINDOWS\SYSTEM32\msacm32.drv
0x55FE0000 - 0x55FFE000  D:\Games\WOW Turtle\DiscordOverlay.dll
0x56000000 - 0x56019000  C:\WINDOWS\SYSTEM32\MSACM32.dll
0x5A050000 - 0x5A0E1000  C:\WINDOWS\WinSxS\x86_microsoft.windows.common-controls_6595b64144ccf1df_5.82.22621.436_none_42d86fc98da003f3\COMCTL32.dll
0x5B470000 - 0x5B477000  C:\WINDOWS\SYSTEM32\ksuser.dll
0x5CF20000 - 0x5CFBF000  C:\WINDOWS\SYSTEM32\mscms.dll
0x5D620000 - 0x5D6B5000  C:\WINDOWS\SYSTEM32\TextShaping.dll
0x5D6C0000 - 0x5D78D000  C:\WINDOWS\SYSTEM32\CoreMessaging.dll
0x5E060000 - 0x5E069000  C:\WINDOWS\SYSTEM32\msdmo.dll
0x5EBB0000 - 0x5ECBA000  C:\Windows\System32\Windows.UI.dll
0x5ECC0000 - 0x5EE49000  C:\WINDOWS\SYSTEM32\AudioSes.dll
0x5EE50000 - 0x5EE59000  C:\WINDOWS\SYSTEM32\AVRT.dll
0x5F1D0000 - 0x5F208000  C:\ProgramData\A-Volute\A-Volute.Nahimic\Modules\Scheduled\ASM.Plugin.AudioDevProps2.dll
0x5F210000 - 0x5F28C000  C:\WINDOWS\System32\MMDevApi.dll
0x5F2A0000 - 0x5F2B1000  C:\WINDOWS\system32\wshbth.dll
0x5F2C0000 - 0x5F344000  C:\WINDOWS\System32\schannel.dll
0x5FB00000 - 0x5FB09000  C:\WINDOWS\SYSTEM32\ktmw32.dll
0x5FB10000 - 0x5FB26000  C:\WINDOWS\system32\pnrpnsp.dll
0x5FDA0000 - 0x61D94000  C:\WINDOWS\System32\DriverStore\FileRepository\iigd_dch.inf_amd64_3e62be9c39fb0007\igc32.dll
0x61DA0000 - 0x61DBD000  C:\WINDOWS\System32\DriverStore\FileRepository\iigd_dch.inf_amd64_3e62be9c39fb0007\igdinfo32.dll
0x61E40000 - 0x61E47000  C:\WINDOWS\SYSTEM32\DCIMAN32.dll
0x61E70000 - 0x61E88000  C:\WINDOWS\system32\nlansp_c.dll
0x62FE0000 - 0x630D9000  C:\ProgramData\A-Volute\A-Volute.Nahimic\Modules\Scheduled\AudioDevProps2.dll
0x632B0000 - 0x632BE000  C:\WINDOWS\System32\winrnr.dll
0x63330000 - 0x64745000  C:\WINDOWS\System32\DriverStore\FileRepository\nvmii.inf_amd64_bade69c3f3c5f2ca\nvd3dum.dll
0x647E0000 - 0x648E9000  C:\WINDOWS\SYSTEM32\drvstore.dll
0x648F0000 - 0x6497C000  C:\WINDOWS\System32\DriverStore\FileRepository\nvmii.inf_amd64_bade69c3f3c5f2ca\nvldumd.dll
0x64980000 - 0x649BC000  C:\WINDOWS\SYSTEM32\directxdatabasehelper.dll
0x649C0000 - 0x64AF6000  C:\WINDOWS\System32\DriverStore\FileRepository\iigd_dch.inf_amd64_3e62be9c39fb0007\igdgmm32.dll
0x64B00000 - 0x6874B000  C:\WINDOWS\System32\DriverStore\FileRepository\iigd_dch.inf_amd64_3e62be9c39fb0007\igd9dxva32.dll
0x68750000 - 0x6888B000  C:\WINDOWS\System32\DriverStore\FileRepository\iigd_dch.inf_amd64_3e62be9c39fb0007\igdumdim32.dll
0x68890000 - 0x68A01000  C:\WINDOWS\SYSTEM32\d3d9.dll
0x68C50000 - 0x68CA4000  C:\ProgramData\A-Volute\A-Volute.Nahimic\Modules\Scheduled\ProductInfo.dll
0x697A0000 - 0x697C7000  C:\WINDOWS\SYSTEM32\cryptnet.dll
0x69EC0000 - 0x69FA3000  C:\WINDOWS\SYSTEM32\textinputframework.dll
0x69FD0000 - 0x69FFD000  C:\WINDOWS\SYSTEM32\dxcore.dll
0x6A000000 - 0x6A0CA000  C:\WINDOWS\SYSTEM32\dxgi.dll
0x6CB90000 - 0x6CBA2000  C:\WINDOWS\system32\napinsp.dll
0x6CFA0000 - 0x6CFB4000  C:\WINDOWS\SYSTEM32\ondemandconnroutehelper.dll
0x6CFC0000 - 0x6CFE8000  C:\WINDOWS\SYSTEM32\NTASN1.dll
0x6CFF0000 - 0x6D015000  C:\WINDOWS\SYSTEM32\ncrypt.dll
0x6D340000 - 0x6D359000  C:\WINDOWS\SYSTEM32\MPR.dll
0x6D400000 - 0x6D440000  C:\WINDOWS\SYSTEM32\wldp.dll
0x6D440000 - 0x6D46A000  C:\WINDOWS\SYSTEM32\SspiCli.dll
0x6D4A0000 - 0x6D6CE000  C:\WINDOWS\SYSTEM32\iertutil.dll
0x6D6D0000 - 0x6D6DB000  C:\WINDOWS\SYSTEM32\netutils.dll
0x6D6E0000 - 0x6D6FD000  C:\WINDOWS\SYSTEM32\srvcli.dll
0x6D700000 - 0x6D8A1000  C:\WINDOWS\SYSTEM32\urlmon.dll
0x6D960000 - 0x6D980000  C:\WINDOWS\system32\ncryptsslp.dll
0x6DD60000 - 0x6DD68000  C:\WINDOWS\SYSTEM32\DPAPI.DLL
0x6DD70000 - 0x6DD7A000  C:\WINDOWS\SYSTEM32\WINNSI.DLL
0x6EF50000 - 0x6EFF5000  C:\WINDOWS\SYSTEM32\apphelp.dll
0x6F000000 - 0x6F024000  C:\WINDOWS\SYSTEM32\devobj.dll
0x6F030000 - 0x6F08D000  C:\WINDOWS\System32\fwpuclnt.dll
0x6F090000 - 0x6F098000  C:\Windows\System32\rasadhlp.dll
0x6F0A0000 - 0x6F0C1000  C:\Program Files (x86)\Bonjour\mdnsNSP.dll
0x6F0D0000 - 0x6F189000  C:\WINDOWS\SYSTEM32\DNSAPI.dll
0x6F290000 - 0x6F356000  C:\WINDOWS\SYSTEM32\PropSys.dll
0x6FD00000 - 0x6FD1A000  C:\WINDOWS\SYSTEM32\bcrypt.dll
0x6FD20000 - 0x6FD2B000  C:\WINDOWS\SYSTEM32\CRYPTBASE.DLL
0x6FD30000 - 0x6FD60000  C:\WINDOWS\system32\rsaenh.dll
0x6FD60000 - 0x6FD75000  C:\WINDOWS\SYSTEM32\CRYPTSP.dll
0x72450000 - 0x72469000  C:\WINDOWS\SYSTEM32\profapi.dll
0x724F0000 - 0x72514000  C:\WINDOWS\SYSTEM32\dwmapi.dll
0x72520000 - 0x7259F000  C:\WINDOWS\system32\uxtheme.dll
0x739D0000 - 0x739DE000  C:\WINDOWS\SYSTEM32\UMPDC.dll
0x739E0000 - 0x73AA6000  C:\WINDOWS\SYSTEM32\wintypes.dll
0x73B90000 - 0x7424E000  C:\WINDOWS\SYSTEM32\windows.storage.dll
0x74250000 - 0x7425E000  C:\WINDOWS\SYSTEM32\msasn1.dll
0x74260000 - 0x742A5000  C:\WINDOWS\SYSTEM32\powrprof.dll
0x742B0000 - 0x742D9000  C:\WINDOWS\SYSTEM32\ntmarta.dll
0x742E0000 - 0x743B6000  C:\WINDOWS\SYSTEM32\WINHTTP.dll
0x743C0000 - 0x743FD000  C:\WINDOWS\SYSTEM32\cfgmgr32.dll
0x74400000 - 0x74424000  C:\WINDOWS\SYSTEM32\IPHLPAPI.DLL
0x74FA0000 - 0x74FF1000  C:\WINDOWS\SYSTEM32\mswsock.dll
0x75000000 - 0x75013000  C:\WINDOWS\SYSTEM32\kernel.appcore.dll
0x75020000 - 0x754A8000  C:\WINDOWS\SYSTEM32\WININET.dll
0x75510000 - 0x75584000  C:\WINDOWS\SYSTEM32\WINSPOOL.DRV
0x75590000 - 0x75598000  C:\WINDOWS\SYSTEM32\VERSION.dll
0x755A0000 - 0x755BF000  C:\WINDOWS\SYSTEM32\USERENV.dll
0x756F0000 - 0x756F8000  C:\WINDOWS\SYSTEM32\WSOCK32.dll
0x75700000 - 0x75731000  C:\WINDOWS\SYSTEM32\WINMM.dll
0x757A0000 - 0x75864000  C:\WINDOWS\System32\msvcrt.dll
0x75870000 - 0x758CF000  C:\WINDOWS\System32\WS2_32.dll
0x75930000 - 0x759B2000  C:\WINDOWS\System32\clbcatq.dll
0x759C0000 - 0x75AC3000  C:\WINDOWS\System32\CRYPT32.dll
0x75AD0000 - 0x75B1B000  C:\WINDOWS\System32\SHLWAPI.dll
0x75B30000 - 0x75C42000  C:\WINDOWS\System32\ucrtbase.dll
0x75C50000 - 0x762A0000  C:\WINDOWS\System32\SHELL32.dll
0x762A0000 - 0x762BA000  C:\WINDOWS\System32\win32u.dll
0x762C0000 - 0x762E5000  C:\WINDOWS\System32\IMM32.dll
0x762F0000 - 0x763B0000  C:\WINDOWS\System32\shcore.dll
0x763B0000 - 0x764FD000  C:\WINDOWS\System32\ole32.dll
0x76510000 - 0x765C9000  C:\WINDOWS\System32\RPCRT4.dll
0x765D0000 - 0x76632000  C:\WINDOWS\System32\bcryptPrimitives.dll
0x76640000 - 0x768A8000  C:\WINDOWS\System32\KERNELBASE.dll
0x768B0000 - 0x768B7000  C:\WINDOWS\System32\NSI.dll
0x76960000 - 0x76A3D000  C:\WINDOWS\System32\gdi32full.dll
0x76A40000 - 0x76A5B000  C:\WINDOWS\System32\imagehlp.dll
0x76A60000 - 0x76AD9000  C:\WINDOWS\System32\msvcp_win.dll
0x76AE0000 - 0x76B62000  C:\WINDOWS\System32\sechost.dll
0x76B70000 - 0x76C0C000  C:\WINDOWS\System32\OLEAUT32.dll
0x77050000 - 0x770FF000  C:\WINDOWS\System32\COMDLG32.dll
0x77100000 - 0x7717C000  C:\WINDOWS\System32\ADVAPI32.dll
0x77180000 - 0x773FC000  C:\WINDOWS\System32\combase.dll
0x77400000 - 0x774F0000  C:\WINDOWS\System32\KERNEL32.DLL
0x774F0000 - 0x77697000  C:\WINDOWS\System32\USER32.dll
0x776A0000 - 0x776C2000  C:\WINDOWS\System32\GDI32.dll
0x776D0000 - 0x777AB000  C:\WINDOWS\System32\MSCTF.dll
0x77920000 - 0x77977000  C:\WINDOWS\System32\WINTRUST.DLL
0x77A50000 - 0x77BFF000  C:\WINDOWS\SYSTEM32\ntdll.dll
0x77C50000 - 0x77D3B000  C:\WINDOWS\SYSTEM32\DDRAW.dll
0x77D40000 - 0x77FF3000  C:\WINDOWS\SYSTEM32\msi.dll
0x79A00000 - 0x79A99000  C:\WINDOWS\SYSTEM32\ResampleDmo.DLL
0x7C460000 - 0x7C540000  C:\WINDOWS\SYSTEM32\OPENGL32.dll
0x7C540000 - 0x7C843000  D:\Games\WOW Turtle\discord_game_sdk.dll
0x7C850000 - 0x7C8C2000  C:\WINDOWS\SYSTEM32\dsound.dll

----------------------------------------
    Memory Dump
----------------------------------------

Code: 16 bytes starting at (EIP = 006D6AD0)

006D6AD0: 8B 01 8D 04  C0 8D 44 42  EF 85 C0 7C  12 3B 05 A8  ......DB...|.;..

Stack: 1024 bytes starting at (ESP = 0019F8B8)

* = addr                            **                                *       
0019F8B0: 00 00 00 00  D0 F8 19 00  E9 64 6D 00  00 00 00 00  .........dm.....
0019F8C0: 54 69 DD 19  00 00 00 00  40 2F 6D 00  00 00 80 3F  Ti......@/m....?
0019F8D0: 58 FA 19 00  D6 2F 6D 00  00 00 00 00  8C FA 19 00  X..../m.........
0019F8E0: 08 68 DD 19  00 00 00 00  00 00 00 00  00 00 00 00  .h..............
0019F8F0: 00 00 00 00  00 00 00 00  00 00 00 00  00 00 00 00  ................
0019F900: 00 00 00 00  00 00 00 00  00 00 00 00  00 00 00 00  ................
0019F910: 00 00 00 00  00 00 00 00  00 00 00 00  00 00 00 00  ................
0019F920: 00 00 00 00  00 00 00 00  00 00 00 00  55 55 D0 43  ............UU.C
0019F930: 9A 99 99 BE  00 00 00 00  00 00 80 3F  00 00 80 3F  ...........?...?
0019F940: 33 33 73 3F  33 33 73 3F  00 00 80 3F  00 00 00 00  33s?33s?...?....
0019F950: 00 00 00 3F  00 00 80 3F  00 00 40 3F  00 00 80 3F  ...?...?..@?...?
0019F960: 00 00 00 00  00 00 00 00  00 00 00 00  00 00 00 00  ................
0019F970: 00 00 00 00  00 00 00 00  84 83 7F FF  66 44 13 FF  ............fD..
0019F980: 16 12 0B FF  59 4C 1D FF  60 67 46 FF  8A 8F 47 FF  ....YL..`gF...G.
0019F990: 8C 7E 46 FF  54 40 0F FF  D2 E7 DD FF  73 7E 6A FF  .~F.T@......s~j.
0019F9A0: 73 52 23 FF  00 00 00 FF  00 00 00 FF  29 25 14 FF  sR#.........)%..
0019F9B0: 1F 14 0D FF  29 25 14 FF  1F 14 0D FF  46 CA 4E 44  ....)%......F.ND
0019F9C0: 8E E3 38 3E  4D 4D 4D FF  00 00 80 3F  00 00 80 3F  ..8>MMM....?...?
0019F9D0: 00 00 00 3F  33 33 73 3F  00 00 80 3F  CD CC 4C 3E  ...?33s?...?..L>
0019F9E0: 00 00 00 3F  00 00 80 3F  00 00 40 3F  00 00 80 3F  ...?...?..@?...?
0019F9F0: 00 00 00 00  00 00 80 3F  00 00 00 00  00 00 00 00  .......?........
0019FA00: 00 00 00 00  00 00 80 3F  00 00 00 00  C8 00 00 00  .......?........
0019FA10: FC FA 19 00  C8 00 00 00  56 29 00 C6  B3 71 C2 43  ........V)...q.C
0019FA20: 54 69 DD 19  34 16 81 00  08 4A E3 0E  00 01 00 00  Ti..4....J......
0019FA30: 08 4A E3 0E  00 01 00 00  20 00 00 00  20 00 00 00  .J...... ... ...
0019FA40: 01 00 00 00  00 00 00 00  B3 71 C2 43  54 69 DD 19  .........q.CTi..
0019FA50: 00 00 80 3F  AB 3C 48 43  9C FB 19 00  D9 25 6D 00  ...?.<HC.....%m.
0019FA60: 6C FC 19 00  60 9B CE 00  00 00 00 00  65 65 65 FF  l...`.......eee.
0019FA70: 5F 4E 4E FF  6F 6F 6F FF  6D 6D 6D FF  6F 6F 6F FF  _NN.ooo.mmm.ooo.
0019FA80: 67 67 67 FF  52 53 52 FF  52 54 52 FF  58 58 58 FF  ggg.RSR.RTR.XXX.
0019FA90: B5 C3 C3 FF  3E 3F 3D FF  00 00 00 FF  00 00 00 FF  ....>?=.........
0019FAA0: 4D 4D 4D FF  43 43 43 FF  4D 4D 4D FF  43 43 43 FF  MMM.CCC.MMM.CCC.
0019FAB0: 8E E3 8A 43  00 00 00 BF  38 38 38 FF  00 00 00 00  ...C....888.....
0019FAC0: 00 00 80 3F  33 33 73 3F  00 00 00 00  00 00 80 3F  ...?33s?.......?
0019FAD0: 00 00 00 3F  00 00 00 3F  00 00 80 3F  00 00 40 3F  ...?...?...?..@?
0019FAE0: 00 00 80 3F  00 00 00 00  00 00 80 3F  00 00 00 00  ...?.......?....
0019FAF0: 00 00 00 00  00 00 00 00  00 00 80 3F  84 82 7E FF  ...........?..~.
0019FB00: 66 44 12 FF  16 12 0A FF  58 4C 1C FF  62 66 46 FF  fD......XL..bfF.
0019FB10: 8C 8E 46 FF  8C 7E 42 FF  5E 48 16 FF  D2 E6 DC FF  ..F..~B.^H......
0019FB20: 8E 92 76 FF  98 6C 36 FF  00 00 00 FF  00 00 00 FF  ..v..l6.........
0019FB30: 28 24 14 FF  1E 14 0C FF  28 24 14 FF  1E 14 0C FF  ($......($......
0019FB40: 14 F6 31 44  5B 9B 3A 3D  4C 4C 4C FF  00 00 80 3F  ..1D[.:=LLL....?
0019FB50: 00 00 80 3F  A4 5C 20 3F  33 33 73 3F  00 00 80 3F  ...?.\ ?33s?...?
0019FB60: 00 00 00 00  00 00 00 3F  00 00 80 3F  00 00 40 3F  .......?...?..@?
0019FB70: 00 00 80 3F  00 00 00 00  00 00 80 3F  00 00 00 00  ...?.......?....
0019FB80: 00 00 00 00  00 00 00 00  00 00 80 3F  C8 00 00 00  ...........?....
0019FB90: AB 3C 48 43  00 00 00 00  0F 00 00 00  C8 FB 19 00  .<HC............
0019FBA0: A0 45 6D 00  E8 FF 66 00  DB 01 00 00  6C FC 19 00  .Em...f.....l...
0019FBB0: 00 00 00 00  00 00 00 00  00 00 80 3F  D8 F6 6B BF  ...........?..k.
0019FBC0: 4C 90 C6 3E  00 00 00 00  E4 FB 19 00  82 FE 66 00  L..>..........f.
0019FBD0: 08 80 15 1A  08 00 F7 0E  08 80 15 1A  6C FC 19 00  ............l...
0019FBE0: FC FB 19 00  88 FC 19 00  9C 32 48 00  D2 F5 38 C0  .........2H...8.
0019FBF0: 24 C2 F2 0E  08 00 F7 0E  E8 20 43 25  70 1C AD C5  $........ C%p...
0019FC00: FD 6E 17 44  F9 08 C7 43  94 FC 19 00  E0 EE 8E 68  .n.D...C.......h
0019FC10: C0 AD B2 05  DC AD B2 05  60 FC 19 00  9B EE 8E 68  ........`......h
0019FC20: C0 AD B2 05  02 00 00 00  94 FC 19 00  8B E4 9C EB  ................
0019FC30: 94 FC 19 00  C0 AD B2 05  88 9A 0F 0F  C4 AD B2 05  ................
0019FC40: 00 00 00 00  00 00 00 00  6A 67 AD C5  70 6B 18 44  ........jg..pk.D
0019FC50: 35 11 C6 43  6A 67 AD C5  70 6B 18 44  35 11 C6 43  5..Cjg..pk.D5..C
0019FC60: 6A 67 AD C5  70 6B 18 44  EB FC C7 43  10 15 AD C5  jg..pk.D...C....
0019FC70: 2A 56 17 44  6B 09 C7 43  00 00 00 00  90 C2 75 3C  *V.Dk..C......u<
0019FC80: 01 00 00 00  00 00 00 00  14 FD 19 00  73 2E 48 00  ............s.H.
0019FC90: 00 00 00 00  00 00 80 3F  00 00 00 00  00 00 00 00  .......?........
0019FCA0: 00 00 00 00  00 00 00 00  00 00 80 3F  00 00 00 00  ...........?....
0019FCB0: 00 00 00 00  00 00 00 00  00 00 00 00  00 00 80 3F  ...............?

------------------------------------------------------------------------------

======================================================================
Hardware/Driver Information:
Processor:              0x0
Page Size:              4096
Min App Address:        0x10000
Max App Address:        0x7ffeffff
Processor Mask:         0xfff
Number of Processors:   12
Processor Type:         586
Allocation Granularity: 65536
Processor Level:        6
Processor Revision:     42242

Percent memory used:    72
Total physical memory:  2147483647
Free Memory:            2147483647
Page file:              -1
Total virtual memory:   2147352576

**Comment by slowtorta** [comment]
This has been fixed in 1.16.3. Please re-download a client from our website if your auto-update is failing to get installed!
