### ISSUE TITLE
The Weaver quest - Archmage Ataeric invisible and unlootable

### ISSUE THREAD

**Issue by Darcisselock** [slowtorta/turtlewow-bug-tracker#1747]
During the quest [22]The Weaver, you have to kill an NPC Archmage Ataeric who is inside a building in Ambermill, Silverpine forest. Problem is that sometimes he is not visible (only his nameplate if you have it enabled, which allows you to target and attack him), and upon death, his corpse is not lootable if you kill him in this state. His invisibility can also be a nasty surprise to hardcore levelers.
Moving him by line of sighting and pulling him outside tends to jerk him back to visibility and then he drops loot as intended. 

I really don't know why he sometimes spawns like this (I can't give steps to reproduce) but I saw it twice so far, so it cannot be a one-time glitch. Other times he respawns normally and is visible and lootable.

I can provide screenshot proof of him in bugged state, you can see his corpse is there because of the hitbox, but Ataeric himself is not visible, and there is no loot on his corpse (which there should be, because I was on the aforementioned quest): https://ibb.co/jJBFy9Q

NPC: https://database.turtle-wow.org/?npc=2120
Quest: https://database.turtle-wow.org/?quest=480
Loot: https://database.turtle-wow.org/?item=3515

**Expected behavior. Describe how it should work:**
Archmage Ataeric should always be visible to players and lootable upon death.

**Comment by slowtorta** [comment]
I tried many times and couldn't reproduce it. Please clean your WDB folder, must be a client-side glitch!
