### ISSUE TITLE
Number of enemy debuffs beyond 16 are invisible 1.16.3

### ISSUE THREAD

**Issue by tocopherylacetate** [slowtorta/turtlewow-bug-tracker#1749]
**Please, provide a clear description what the bug is:**
Enemy debuffs beyond 16 cannot be seen, and the hidden ones do not 'move up' when earlier ones fade.

**Steps to reproduce the behavior with as much detail as possible:**

1. debuff an enemy to 16
2. put a DoT on enemy that you cant see
3. notice you are still dealing damage
4. notice you cannot see the debuff you just applied
5. wait till a debuff from the 1-16 slot to fade
6. notice your DoT still ticking and still not visible, indicating that it didnt go up the ranks

**IDs of affected creatures, items, quests or spells with a link to the relevant page:**

all debuffs heh

**Expected behavior. Describe how it should work:**
Well according to some sneaky screenshots all 24 buffs should be visible, and thus interactable with 'detect spell icon' macros, a side effect of this is that most macros searching for enemy debuff faerie fire etc stop functioning

**Comment by slowtorta** [comment]
Attempting to fix it in 1.16.4.
