### ISSUE TITLE
Damage over time effects are doing way more damage than they should be

### ISSUE THREAD

**Issue by Velite12** [slowtorta/turtlewow-bug-tracker#175]
![image](https://user-images.githubusercontent.com/45871932/126197029-38356b9a-607d-4ec5-9084-6a9cc4731c38.png)

![image](https://user-images.githubusercontent.com/45871932/126197608-a29c6713-5c31-4671-8f6d-a1b27fbeab4d.png)

All damage over time effects with the exception of 4: (kri, vaelastrasz, nightmare dragons and sapphiron) are following a "10% resistance rule" whereby resistance damage reduction (as according to this table) is only 10% as strong as it should be. These 4 damage over time effects do not follow this rule because there is video evidence to show that they aren't. I am making this bug report to expand this list to more DoT effects as shown by classic/2006 video evidence. There are potentially more DoT effects that need to be investigated. Officially, most dots were claimed fixed of this issue by patch 2.0 in retail, so it is possible the 10% reduction is more an exception and not the rule.  It does appear on classic however that all DoTs factor in resistance correctly, and by 2006 evidence it does seem like there are PvE DoTs that do should not follow this rule, but currently are on Turtle-wow.

Ragnaros' Elemental Fire:

Spell: https://database.turtle-wow.org/?spell=20564

2006 footage where it does not follow this 10% reduction rule 

https://www.youtube.com/watch?v=zrzTPbbEPu4&t=138s

2020 where, despite being under fire resist cap, still does not take the full damage on any ticks (540 damage) (following the resistance table)

https://www.youtube.com/watch?v=n5d833CbMf8

Highlord Mograine's Righteous Fire

Spell: https://database.turtle-wow.org/?spell=28882

This is a warcraft log of one of the tanks wearing under 315 resist, seems to be about 200, and he mitigated about 55% of the fire damage, which is consistent with that level of resist, but that damage mitigation on Turtle-wow would be much lower here due to the 10% rule.

https://vanilla.warcraftlogs.com/reports/a73C8KXGcjFwkrBP#fight=119&type=damage-taken&source=22

If you test this on turtle wow, even at 315 (resistance cap) the majority of your dot ticks will be for full damage.

**Comment by CosminPOP** [comment]
Fixed for Highlord Mograine's Righteous Fire, Closing this.
Make a new Issue for Ragnaros' Elemental Fire please.
