### ISSUE TITLE
Feign Death broken

### ISSUE THREAD

**Issue by dole555** [slowtorta/turtlewow-bug-tracker#1751]
**Please, provide a clear description what the bug is:**
If you use trueshot during a combat, if you feign death you get put back in combat shortly after feighn death.
**Steps to reproduce the behavior with as much detail as possible:**

1. Attack a target.
2. Use Trueshot
3. Feign death.
4. You get put back in combat after combat dropping.

**IDs of affected creatures, items, quests or spells with a link to the relevant page:**

Spell: https://database.turtle-wow.org/?spell=3669

**Expected behavior. Describe how it should work:**
It doesn't matter if you use Trueshot right before Feign Death. It also happens if you do Trueshot -> Autoshot -> Multishot -> Autoshot -> Feign Death, you still get put back into combat regardless of how far ago you used trueshot. In a rotation/combat that has no trueshot use at all, if you Feign Death you get put out of combat normally without issue.

**Comment by SabineWren** [comment]
Easy to reproduce this bug, even on target dummies. It's especially annoying in battlegrounds.
