### ISSUE TITLE
Shaman Totem Attacking Cross-Faction In Group

### ISSUE THREAD

**Issue by GarBear121** [slowtorta/turtlewow-bug-tracker#1753]
**Please, provide a clear description what the bug is:**
If in a dungeon group with warmode enabled, if the opposing faction uses a totem while in group, once group is dropped the totem will attack opposing faction group members who are no longer in group - this is correct.

Issue is the totem will continue to attack once invited back into the group.

**Steps to reproduce the behavior with as much detail as possible:**

1.Summon Searing Totem while in group with an Alliance in group and within range
2. Have Alliance with warmode enabled attack opposing faction
3. Rejoin group that was dropped due to attacking while in group with opposing faction
4. Watch searing totem

**IDs of affected creatures, items, quests or spells with a link to the relevant page:**

NPC: https://database.turtle-wow.org/?npc=
Item: https://database.turtle-wow.org/?item=
Quest: https://database.turtle-wow.org/?quest=
Spell: https://database.turtle-wow.org/?spell=
Object: https://database.turtle-wow.org/?object=

**Expected behavior. Describe how it should work:**

**Comment by Velite12** [comment]
Just curious, does this happen with all pets or just totems?

**Comment by GarBear121** [comment]
Noticed this with totems, did not try to recreate this with pets. I would assume the pet would have to be in combat with the target player rejoining the group for this to occur.

**Comment by jameyboor** [comment]
Fixed on next update.
