### ISSUE TITLE
Leprous Assistant spawned behind invisible wall in Gnomeregan

### ISSUE THREAD

**Issue by Shellyoung** [slowtorta/turtlewow-bug-tracker#1756]
**Please, provide a clear description what the bug is:**
![WoW_wFgNbFUumV](https://user-images.githubusercontent.com/40469927/182033835-5c3960dc-8523-413f-8635-a0e14f0c36a4.gif)

Location:
![WoW_Tr5mL1IgLW](https://user-images.githubusercontent.com/40469927/182033822-a952feb9-7ce7-41e4-ad2f-e874a35a35bd.png)

**IDs of affected creatures, items, quests or spells with a link to the relevant page:**

NPC: https://database.turtle-wow.org/?npc=7603

**Expected behavior. Describe how it should work:**
He should spawn in accessible space.

**Comment by slowtorta** [comment]
Sorry, I was unable to find this one. Please provide a specific location for this mob.

**Comment by Shellyoung** [comment]
The location is on the map on the second screenshot

**Comment by slowtorta** [comment]
I found one and was able to aggro them w/o any issues. I'm suggesting that you download a fresh client from our website, it seems like some sort of client-side glitch.
![image](https://user-images.githubusercontent.com/66763404/184538095-ac1cd5e4-634b-43e6-9242-4ecb6bd24c68.png)

**Comment by Shellyoung** [comment]
I assume that an algorithm spawned him behind the wall by random pick
