### ISSUE TITLE
Druid, PRIMAL FURY, Electrified gloves and free combo points

### ISSUE THREAD

**Issue by leylandpaladin** [slowtorta/turtlewow-bug-tracker#1758]
Electrified gloves https://database.turtle-wow.org/?item=80747 gives a combo point on proc (in druid cat form):

Steps to reproduce the behavior with as much detail as possible:

1. Equip https://database.turtle-wow.org/?item=80747 and get 2/2 PRIMAL FURY
2. Start attack some mob
3. See combo points generating from procs, you got 2 combo points on crit, so that why I think it's another issue with PRIMAL FURY

Expected behavior. Describe how it should work:

It should not give combo points on proc

**Comment by leylandpaladin** [comment]
Update! seems like every item with on-hit effects gives CP on proc.

I got this today https://database.turtle-wow.org/?item=60568
And now I'm literally getting combo point on every auto attack

**Comment by redmagejoe** [comment]
Cannot reproduce this issue.
