### ISSUE TITLE
Thorns, nature grasp and dire bear form.

### ISSUE THREAD

**Issue by leylandpaladin** [slowtorta/turtlewow-bug-tracker#1759]
You can cast thorns and nature grasp in Dire Bear Form!:

Steps to reproduce the behavior with as much detail as possible:

1. Use your dire bear form
2. See your thorns and nature grasp is not grayed out on action bars
3.  Use it and ensure that is not visual bug. They still spend mana tho.

IDs of affected creatures, items, quests or spells with a link to the relevant page:

Expected behavior. Describe how it should work:

They should not be usable in bear form

UPDATE:

Soothe animal works in dire bear form too!

**Comment by Platinumcoated** [comment]
noticed that too, also noticed it weirdly excludes some ranks, so I went and tried everything

Currently, only the following spells can be cast while shapeshifted into Dire Bear Form:

  (I provided database links, but the database is still on patch 1.16 )
Nature's Grasp (rank 1) [https://database.turtle-wow.org/?spell=16689](url)
Nature's Grasp (rank 2) [https://database.turtle-wow.org/?spell=16810](url)
Nature's Grasp (rank 3) [https://database.turtle-wow.org/?spell=16811](url)
Nature's Grasp (rank 4) [https://database.turtle-wow.org/?spell=16812](url)
Nature's Grasp (rank 5) [https://database.turtle-wow.org/?spell=16813](url)
Nature's Grasp (rank 6) [https://database.turtle-wow.org/?spell=17329](url)
Omen of Clarity [https://database.turtle-wow.org/?spell=16864](url)
Soothe Animal (rank 2) [https://database.turtle-wow.org/?spell=8955](url)
Soothe Animal (rank 3) [https://database.turtle-wow.org/?spell=9901](url)
Thorns (rank 4) [https://database.turtle-wow.org/?spell=8914](url)
Thorns (rank 5) [https://database.turtle-wow.org/?spell=9756](url)

No balance or restoration spells can be cast while shapeshifted into Cat Form

**Comment by cyaohiri** [comment]
Another thing to note is that using these abilities in bear form is complete free, contrary to what's said in the original post.

**Comment by welpenhund** [comment]
![image](https://user-images.githubusercontent.com/30401521/230903891-549d8c0b-d1ce-4f49-b74b-1ad76ab06414.png)
Source: https://vanilla-wow-archive.fandom.com/wiki/Nature%27s_Grasp

""Can also be cast in Cat, Bear, Tree of Life, and Moonkin forms.""

**Comment by cyaohiri** [comment]
> ""Can also be cast in Cat, Bear, Tree of Life, and Moonkin forms.""
The fact that it mentions Tree of Life means it's referring to TBC, if not later expansions.

**Comment by Haaxor1689** [comment]
Will be fixed in 1.17 update
