### ISSUE TITLE
NPC sees half-meter tall border as an obstacle

### ISSUE THREAD

**Issue by Shellyoung** [slowtorta/turtlewow-bug-tracker#1760]
**Please, provide a clear description what the bug is:**
![MaxView_s4I0IQa8Tq](https://user-images.githubusercontent.com/40469927/182035488-92eda631-55f8-4e9d-98d1-f14241880ea0.gif)

**Location:** Engineering Labs, Gnomeregan
![WoW_HhmQw5HFb5](https://user-images.githubusercontent.com/40469927/182035564-ef7115b0-6df1-4244-9bc9-4b63224eb9e6.png)

**Expected behavior. Describe how it should work:**
I do not know about how it functions on Blizzard servers, but I guess the height of obstacles which NPCs should pass should be greater.

**Comment by jameyboor** [comment]
This will be looked into, thank you.
