### ISSUE TITLE
Hunter pets trigger the chain cleave on the Vaelastrasz the Corrupt fight.

### ISSUE THREAD

**Issue by OrnsteinHunter** [slowtorta/turtlewow-bug-tracker#1761]
**Please, provide a clear description what the bug is:**

**Steps to reproduce the behavior with as much detail as possible:**

1. Start the Vaelastrasz the Corrupt Fight
2. Send a hunter pet in
3. It triggers Vaels chain cleave because the pet gets too close to the front of the boss

**IDs of affected creatures, items, quests or spells with a link to the relevant page:**

NPC: https://database.turtle-wow.org/?npc=13020

**Expected behavior. Describe how it should work:**
Hunters are supposed to be able to use their pet on Vaelatrasz but currently it triggers a chain cleave which wipes the raid. This is a huge damage loss for a hunter player.

https://www.youtube.com/watch?v=3jR0GxFJYqc 

@ 1:50 in the video you can see the orange damage from a hunters pet but it doesn't trigger any cleave to wipe the raid.

**Comment by Giperion** [comment]
After reading the code, I see that cleave is always casted on current target, not on nearest random unit. Which means that it will affect everyone who stands near the boss. It is by design

**Comment by Giperion** [comment]
Also it doesn't actually care, if someone stand near or not. It will cast it anyway

**Comment by luskanek** [comment]
Working as intended.

**Comment by balakethelock** [comment]
Some explanation the reason why this issue happens here and not in classic wow for the people who don't know:
Mobs pathing to attack a target in vmangos takes them to enter far into the mob's hitbox. In classic (and in real vanilla wow) when a mob (or a pet) is sent to attack a target, it will walk up only to the edge of the hitbox.

So in here, the pet will go deep into vael's hitbox, and become in range of the maintank causing the cleave to chain.
In classic, the pet only walks up to the edge of the hitbox, far away from the maintank.
