### ISSUE TITLE
Stormwind vault no trash loot at alll

### ISSUE THREAD

**Issue by geojak** [slowtorta/turtlewow-bug-tracker#1763]
**Please, provide a clear description what the bug is:**

All mobs in sw vault don't drop anything besides silver. Maybe of you lucky you get some runecloth.

No greys, no whites, no random greens or blues, no wolf drops nothing. Pls add it Similiar to hateforge or cresent groove has it

**Comment by Azeron223** [comment]
Can confirm this, ventured in there for the first time today, it was a little dissapointing to see no loot, especially with the level of these mobs it would be excellect to see them have level 61~ mob loot added to their tables as these would be a new source for extra rare high level items!

Plus it would be cool to see demonic runes added to the loot tables of the demons in here as well ;)

**Comment by slowtorta** [comment]
Fixed in the next update.
