### ISSUE TITLE
Sw vault uncklickable trash

### ISSUE THREAD

**Issue by geojak** [slowtorta/turtlewow-bug-tracker#1764]
**Please, provide a clear description what the bug is:**

Sometimes some of the trash (slimes and undeads) in the room in font of the boos you reach if yo ugo strisght from the dungeon entrance become untargetable

You can't click them, loot them, you can target them with tab thought 

Its somewhat random
In my first run only oone mob was affected, in my section run 2 groups, in my third run none

**Comment by slowtorta** [comment]
It's probably related to the fog object in this room. It's somewhat... a perk. Can't see bodies in the white fog on the floor.

**Comment by geojak** [comment]
you can see the bodies just fine, i didnt even notice any fog. but i cant click them even when dragged into another room and fightin me directy on my head.

i should have taken a screenshot

**Comment by geojak** [comment]
ah  see now what you meant torta, it is the fog

**Comment by geojak** [comment]
![WoWScrnShot_090622_170141](https://user-images.githubusercontent.com/25199983/190431444-70a982f3-d5b1-43ad-b644-e8be71a96e2e.jpg)
issue this prevails. cant loot in the fog. sucks when you pull the boss into that room and then cant acutally click it
