### ISSUE TITLE
Mind Vision breaks after target moves a few hundred yards

### ISSUE THREAD

**Issue by goudekid** [slowtorta/turtlewow-bug-tracker#1765]
**Please, provide a clear description what the bug is:**

Mind vision should last until channeling is finished or cancelled, currently it will break automatically if the target moves too far away

**Steps to reproduce the behavior with as much detail as possible:**

1. Use mind vision on someone who is moving away from you
2. automatically breaks after they move too far away

**I have only tested with rank 1 but others in discord say that rank 2 also faces the same issue**

**IDs of affected creatures, items, quests or spells with a link to the relevant page:**

Spell: https://database.turtle-wow.org/?spell=2096

**Expected behavior. Describe how it should work:**

 it should continue to channel and provide you vision to them until cancelled or the channel runs out

**Comment by jameyboor** [comment]
Do you have proof of this expected behavior? Classic wowhead also says max range of 100 yards.
