### ISSUE TITLE
Sw vault enslaved imps attack group memebrs

### ISSUE THREAD

**Issue by geojak** [slowtorta/turtlewow-bug-tracker#1766]
**Please, provide a clear description what the bug is:**

IF you enslave an imp as a warlock on sw vault, the imp will first attack other imps, and then group nembers

Enslvaed demons sjoild not attack group members

**Comment by geojak** [comment]
probably related, if you use the gnomish battle chicken in a duel, then the chicken will show no mercy and finish your opponent off after you won.

**Comment by jameyboor** [comment]
Fixed.
