### ISSUE TITLE
ravager missing ticks

### ISSUE THREAD

**Issue by geojak** [slowtorta/turtlewow-bug-tracker#1767]
**Please, provide a clear description what the bug is:**

the ravager spins is 9 sec long and very 3 sec it should aoe
but the last ticks is msising

what happens is 3 sec wait aoe. 3 sec wait aoe 3 sec wait NOTHING
last tick is missing

**IDs of affected creatures, items, quests or spells with a link to the relevant page:**

https://database.turtle-wow.org/?item=7717
https://database.turtle-wow.org/?item=60413

**Expected behavior. Describe how it should work:**

9 seocodns every 3 sec an aoe

**Comment by slowtorta** [comment]
Related to https://github.com/slowtorta/turtlewow-bug-tracker/issues/1975
