### ISSUE TITLE
Hand of Antu'sul proc

### ISSUE THREAD

**Issue by lucas-m123** [slowtorta/turtlewow-bug-tracker#1768]
The item Hand of Antu'sul (https://database.turtle-wow.org/?item=9639) procs a Thunder Clap-like effect but it triggers your thunder clap cooldown as a warrior. Does its damage (7 nature according to the item) regardless of its rank.

It shouldn't be like that because they're separate skills:

The proc skill: https://database.turtle-wow.org/?spell=13532#used-by-item
Warrior skill: https://database.turtle-wow.org/?spell=11581

**Comment by redmagejoe** [comment]
Tested on current version. This is indeed still triggering Warrior Thunderclap cooldown.

**Comment by Zeyla-TW** [comment]
This is an NPC thunder clap spell that is used by the item, but is currently listed in the same spell category with shared category recovery times as the warrior thunder clap spells. This should be a simple fix.

**Comment by Zeyla-TW** [comment]
Disregard my previous post, I just checked and the shared cooldown with thunder clap for warriors is actually how the item worked on Blizzard servers.
