### ISSUE TITLE
Cannot learn the "Traveler's Tent" skill

### ISSUE THREAD

**Issue by pypaut** [slowtorta/turtlewow-bug-tracker#1769]
**Please, provide a clear description what the bug is:**

After buying and triggering the item "Outline: Traveler's Tent", I cannot find the "tent" skill anywhere in my spell book.

**Steps to reproduce the behavior with as much detail as possible:**

1. Buy the "Outline: Traveler's Tent" from Rufus Hardwick NPC
2. Right click this item from inventory
3. Wait for the progress bar to complete
4. Read the success message "You have learned..."
5. Cannot find "Tent" in skill book

**IDs of affected creatures, items, quests or spells with a link to the relevant page:**

Item: https://database.turtle-wow.org/?item=50234
NPC: https://database.turtle-wow.org/?npc=50070

**Expected behavior. Describe how it should work:**

I should be able to find the "Tent" recipe, in the skill book or Survival book.

**Thank you and good luck**

**Comment by Tinyfin-github** [comment]
Greetings!

The tent should be in your  profession skill tab. If it's not there you need to reinstall patch W
