### ISSUE TITLE
Warrior talent: Blood Craze rip

### ISSUE THREAD

**Issue by Jecs21** [slowtorta/turtlewow-bug-tracker#177]
![image](https://user-images.githubusercontent.com/8251068/126233166-0ec7875b-33ac-49af-bed2-bc6d8391929d.png)

Spell: https://database.turtle-wow.org/?search=blood+craze

**Comment by rosen40** [comment]
not a bug, did you maybe not notice that you get more ticks? its always a 1% tick per tick but rank 1 you get 1 tick, rank 2 you get 2 ticks and rank 3 you get 3 ticks...

**Comment by Nolin7777** [comment]
Working as intended
