### ISSUE TITLE
Warchief's Blessing not giving casters Spell Haste 1.16.1

### ISSUE THREAD

**Issue by tocopherylacetate** [slowtorta/turtlewow-bug-tracker#1772]
**Please, provide a clear description what the bug is:**
Haste should now apply to casters
**Steps to reproduce the behavior with as much detail as possible:**

1. Get Warchief's Blessing
2. Cast any spell, like fireball
3. See no cast time reduction

**IDs of affected creatures, items, quests or spells with a link to the relevant page:**

Spell: https://database.turtle-wow.org/?spell=16609

**Expected behavior. Describe how it should work:**
Should see cast time reduction on spellcasts when buffed with Warchief's Blessing

![Screenshot from 2022-08-01 19-27-45](https://user-images.githubusercontent.com/108923904/182138604-16547c3f-1b22-4608-95ae-a14a335f900c.png)

**Comment by Zmitrok1984** [comment]
![image](https://user-images.githubusercontent.com/99164611/182112456-93e086a1-1df1-48af-87da-ee4234bb1f04.png)
I can read an spell description only here:15% haste to melee attacks

**Comment by afizzler** [comment]
Dragunovi's statement means that all haste buffs should be reworked to reflect the new change.

**Comment by Qix03** [comment]
Nah, he was pretty clearly referring to the ones that affect melee/ranged attack speed. Specific vs General. Otherwise you ought to report quivers not affecting your speed, too.

**Comment by Velite12** [comment]
When he refers to "haste stat" he means the new thing assigned to items. That "haste stat" is a spell. That is the spell being changed. Warchief's Blessing is a different spell which is not stated to be changed; the "haste" on it is an effect, not a spell.

**Comment by Timonthemage** [comment]
need MSG to start bitching about it not working for casters then it will get fixed within a few minutes

**Comment by jameyboor** [comment]
Closed. @Velite12 is right.
