### ISSUE TITLE
Can't Dispel Curses or Poisons as Tree of Life form.

### ISSUE THREAD

**Issue by Sygmoond** [slowtorta/turtlewow-bug-tracker#1774]
**Please, provide a clear description what the bug is:**
Title, it's not possible to cast Remove Curse or Abolish Poison.
**Steps to reproduce the behavior with as much detail as possible:**

1. Enter Tree of Life Form
2. Try to dispel a curse on any member of the party or yourself.

**Expected behavior. Describe how it should work:**
As it reads, you should be able to cast Remove Curse or Abolish Poison.
New Talent: Tree of Life Form (Row 7)
Shapeshift into the Tree of Life. While in this form you increase healing received by 20% of your total Spirit for all party members within 30 yards, your movement speed is reduced by 20%, and you cannot cast damaging spells or Healing Touch, but the mana cost of these spells is reduced by 20%.

The act of shapeshifting frees the caster of Polymorph and Movement Impairing effects.

**Comment by ratkosrb** [comment]
Abolish Poison works fine for me. Only Remove Curse was not castable in tree form.

**Comment by Sygmoond** [comment]
It should still be able to be casted, though

**Comment by ratkosrb** [comment]
It will be fixed in the next update.

**Comment by Sygmoond** [comment]
Thank you
