### ISSUE TITLE
Windshear Mine Lockpick Box Respawn

### ISSUE THREAD

**Issue by SagaPaladin** [slowtorta/turtlewow-bug-tracker#1775]
**Please, provide a clear description what the bug is:**

**Steps to reproduce the behavior with as much detail as possible:**

1. Pick the locks on the boxes in Windshear Mine
2.  Wait 30 minutes for respawn
3.  Only the outside box respawned, once. They haven't respawned since

**IDs of affected creatures, items, quests or spells with a link to the relevant page:**

NPC: https://database.turtle-wow.org/?npc=
Item: https://database.turtle-wow.org/?item=
Quest: https://database.turtle-wow.org/?quest=
Spell: https://database.turtle-wow.org/?spell=
Object: https://database.turtle-wow.org/?object=

**Expected behavior. Describe how it should work:** Lockpick boxes should respawn at a normal rate

**Comment by ratkosrb** [comment]
The respawn time is currently 2 hours. Do you think it should be shorter?

**Comment by SagaPaladin** [comment]
2 hours seems extreme for 3 lockpick training boxes to me? Maybe I'm crazy,  but it seems all the others are closer to 5 minutes.  The three inside the cave are also a slightly higher level box than the others in the crag, so they're very nice while leveling lockpicking.. 

Seems like a nice short lockpicking boost to reward players braving the much more dangerous cave.
