### ISSUE TITLE
Underground Mining Node - STV

### ISSUE THREAD

**Issue by usedcars4cheap** [slowtorta/turtlewow-bug-tracker#1778]
Player reported an inaccessible Truesilver Deposit in Stranglethorn Valley approx 39,53

Potentially an underground mining node?

**Comment by slowtorta** [comment]
Is it possible to have server-side coordinates?

**Comment by usedcars4cheap** [comment]
Eastern Kingdoms, Zone 33, Area 1577
X: -13450
Y: -281

Give or take, ish?
