### ISSUE TITLE
Spellpower coefficient for Healing Touch Rank 3 is wrong (possibly all spells with level 20 penalty)

### ISSUE THREAD

**Issue by Lunkdunk** [slowtorta/turtlewow-bug-tracker#178]
**Please, provide a clear description what the bug is:**
I noticed a difference with Rank 3 Healing Touch today so I did some math. I had 0 talent points when I tested it.
Average Rank 3 Healing Touch from 20 casts = 623
Average base heal = 219
Bonus heal = 623 - 219 = 404
My current healing power = 917
Healing power coefficient = 404/917 = 0,44
Theoretical healing power coefficient for Rank 3 Healing Touch (2,5s cast time and learned at level 14):
(2,5/3,5)*(1-(20-14)*0,0375) = 0,55
I also did some quick tests of some healing spells under level 20 and all got a lower coefficient than the theoretical value.
**Steps to reproduce the behavior with as much detail as possible:**

1.
2. 
3. 

**IDs of affected creatures, items, quests or spells with a link to the relevant page:**
Spell: https://database.turtle-wow.org/?spell=5192
**Expected behavior. Describe how it should work:**

**Comment by rosen40** [comment]
not a bug

**Comment by Lunkdunk** [comment]
> not a bug

how so?

**Comment by rosen40** [comment]
Thats the correct coeff

**Comment by rosen40** [comment]
Sry, for some readon i got impression you are saying its too higj, nvm
