### ISSUE TITLE
Oil platform east of Durotar // bugged pathfinding and/or aggro

### ISSUE THREAD

**Issue by adiosamigos** [slowtorta/turtlewow-bug-tracker#1780]
**Please, provide a clear description what the bug is:**
Hi, the aggro works not as indended in the water near the oil platform and on the platform itself. 
Hunter's pet can't get to the platform (and it ignores the follow command), instead it aggroes ALL the mobs in the water for some reason.

**Steps to reproduce the behavior with as much detail as possible:**

1. Be a lv 12 hunter with boar pet
2. Jump to the water from the goblin settlment (can't recall its name) and swim towards the oil platform
3. Get to the lower level of the platform (jump out of the water)
4. Try to get your pet with you on the platform (use follow command)
5. See as your pet is unablet to get to you and instead gets aggro from the mobs in the water triggering combat for both of you
6. Once the pet is dead try to recall in while you are on the platform (your pet will be summoned in the water outside of your vision)
7. Get the same result as in para 5 above
8. Once your pet is dead, jump down to the water from the platform and get aggro from dozen of surrounding mobs which just shredded your pet
9. Get back to the platform if you are lucky and HS the hell out of there

**IDs of affected creatures, items, quests or spells with a link to the relevant page:**

NPC: https://database.turtle-wow.org/?npc=
Item: https://database.turtle-wow.org/?item=
Quest: https://database.turtle-wow.org/?quest=
Spell: https://database.turtle-wow.org/?spell=
Object: https://database.turtle-wow.org/?object=

**Expected behavior. Describe how it should work:**
Your pet should follow you in water as usual and be able to get to the platform with you, it should not attack/neither be attacked by the mobs outside of their aggro range.

**Comment by slowtorta** [comment]
This is a part of a more general problem and we're aware of that. We cannot fix pathing on a specific house, platform, or cave.  Fixes like that come in batches with the general mmap/vmap overhaul!
