### ISSUE TITLE
Silithus Abyssal Lords do not drop the Abyssal Scepter 100% of the time

### ISSUE THREAD

**Issue by OonaFae** [slowtorta/turtlewow-bug-tracker#1781]
**Please, provide a clear description what the bug is:**
When killing Abyssal Lords in Silithus they should drop the Abyssal Scepter 100% of the time.
my guild has observed this as not happening. So far we have only seen this issue with the Wind Lord but that could just be our smaller sample size.

**Steps to reproduce the behavior with as much detail as possible:**

1. Summon an Abyssal Lord and defeat it 
2. Loot the Lord
3. Sometimes there is no Abyssal Scepter

**IDs of affected creatures, items, quests or spells with a link to the relevant page:**

https://database.turtle-wow.org/?item=20515
https://database.turtle-wow.org/?npc=15205
https://database.turtle-wow.org/?npc=15204
https://database.turtle-wow.org/?npc=15305
https://database.turtle-wow.org/?npc=15203

**Expected behavior. Describe how it should work:**
Abyssal Scepter should drop 100% of the time.

**Comment by OonaQueenoftheBae** [comment]
https://www.youtube.com/watch?v=f363adsZ6Ic&list=PLoJjOcE78CJvfcUrAXe1v5Wm9Mj3Vj5tJ

Here is video of us doing the three Abyssal Lords that do not drop the Scepter, as you can see there is no scepter on them

**Comment by OonaQueenoftheBae** [comment]
According to the database, none of the Lords except Kazum have the Scepter on their loot table. Like likely got removed somehow when the new Abyssal (Element) were added on.

**Comment by OonaQueenoftheBae** [comment]
The Fire Lord is now dropping the Scepter as of 8/7
I am yet to confirm the others

**Comment by OonaQueenoftheBae** [comment]
Confirmed Wind is dropping scepter.
Will close ticket if i can confirm water is dropping

**Comment by OonaQueenoftheBae** [comment]
Confirmed that this is not dropping from the Water Lord still
