### ISSUE TITLE
incendosaur skin paudlrons do not drop anywhere

### ISSUE THREAD

**Issue by geojak** [slowtorta/turtlewow-bug-tracker#1783]
**Please, provide a clear description what the bug is:**

hateforge quarry introduced a cool new leather incendosaur set

the boots drop from a boss
https://database.turtle-wow.org/?item=60568

the gloves are BOE and drop from trash
https://database.turtle-wow.org/?item=60582

and the las item the shoulder??? according from database their are not available
https://database.turtle-wow.org/?item=60572

**Expected behavior. Describe how it should work:**

should drop somewehre in hateforge

**Comment by jameyboor** [comment]
Fixed.

**Comment by geojak** [comment]
Uff that drop rate on a bop. Thx for fixing it thought!
