### ISSUE TITLE
Spirit of Zandalar buff not given in booty bay

### ISSUE THREAD

**Issue by bugsyreporter** [slowtorta/turtlewow-bug-tracker#1784]
**Please, provide a clear description what the bug is:**
Spirit of Zandalar buff not given in booty bay when the quest is completed

**Steps to reproduce the behavior with as much detail as possible:**

1. be in booty bay
2. wait for somebody to complete the quest

**IDs of affected creatures, items, quests or spells with a link to the relevant page:**

NPC: https://database.turtle-wow.org/?npc=
Item: https://database.turtle-wow.org/?item=
Quest: https://database.turtle-wow.org/?quest=
Spell: https://database.turtle-wow.org/?spell=
Object: https://database.turtle-wow.org/?object=

**Expected behavior. Describe how it should work:**
I should get the buff

**Comment by slowtorta** [comment]
Fixed in one of the recent updates.
