### ISSUE TITLE
Codex:Shadow Mend Drop-eventuality is buged

### ISSUE THREAD

**Issue by Apimius** [slowtorta/turtlewow-bug-tracker#1788]
The Codex Shadow Mend is at the moment not obtainable since it can not drop (confirmed by Tinyfin)

**Steps to reproduce the behavior with as much detail as possible:**

1.Run Kara Crypts all day
2. Ask a GM if the codex is even in the game
3. Be mad that you find out dropchance is buged

https://database.turtle-wow.org/?item=83571 (item link)

Should drop for 20 % on Alarus, and should not take the blue item drop slot

**Comment by ratkosrb** [comment]
![WoWScrnShot_080222_044629](https://user-images.githubusercontent.com/35845488/182274348-b3af7696-3eee-4cc4-977b-ed97f06be442.jpg)

It's not bugged, he drops the item. I just spawned the npc and killed it a few times and it dropped.

**Comment by Apimius** [comment]
He only drops one item though, in hateforge quarry there drops a blue and the manual when it drops. Should be the same case here. The codex should not take the place of the blue

**Comment by Tinyfin-github** [comment]
Issue was fixed in a previous applied update.
