### ISSUE TITLE
Swimspeed bug after quest gryphon flight

### ISSUE THREAD

**Issue by TatkaS1** [slowtorta/turtlewow-bug-tracker#179]
**Please, provide a clear description what the bug is:**
Probably caused by a custom quest mount, my swim speed when holding W is many times increased (by like 300%)

**Steps to reproduce the behavior with as much detail as possible:**
Not 100% sure but it happened after:
1. Did the quest in Elwynn: Matter of trust
2. Used the gryphon and flew to logging camp - got dismounted midflight, was in combat with murlocs
3. Did some running around and when I went to swim, I had super speed (only forward, like when on a mount)

**IDs of affected creatures, items, quests or spells with a link to the relevant page:**
Quest: https://database.turtle-wow.org/?quest=60070

**Expected behavior. Describe how it should work:**
The swim speed shouldn't be affected :)

**Comment by jameyboor** [comment]
Fixed in next update.
