### ISSUE TITLE
проблемы с игрой

### ISSUE THREAD

**Issue by topik43** [slowtorta/turtlewow-bug-tracker#1794]
![20220802_131813](https://user-images.githubusercontent.com/110463875/182356376-d576ad6c-8f43-4a31-82ce-beca3e16ab4e.jpg)
![20220802_124717](https://user-images.githubusercontent.com/110463875/182356450-4a871671-5edb-4fa7-9613-82101548e32a.jpg)
у меня возникла вот такая проблема как решить ее

**Comment by slowtorta** [comment]
В Дун Мороге такой краш происходит? Если да, то вот этот файл загрузите в папку Data, пожалуйста. Это патч на конкретно этот краш.
[patch-Z.zip](https://github.com/slowtorta/turtlewow-bug-tracker/files/9246108/patch-Z.zip)

**Comment by topik43** [comment]
Скажите пожалуйста где можно найти Сфера Каландуса в Монастыре Алого Ордена по квесту The orb of kalandus
