### ISSUE TITLE
Flourish rogue spell

### ISSUE THREAD

**Issue by dole555** [slowtorta/turtlewow-bug-tracker#1797]
**Please, provide a clear description what the bug is:**
The finishing move increases chance to parry by 21%. The spell tooltip sais "increases your chance to parry by an additional 21 to 20%" which is odd. The patch notes sais 20%. The increase is of 21%. The spell in twow database sais 10%.

**IDs of affected creatures, items, quests or spells with a link to the relevant page:**

Spell: https://database.turtle-wow.org/?spell=5934

**Expected behavior. Describe how it should work:**

**Comment by redmagejoe** [comment]
The aura that appears when using Flourish does indeed say 21 to 20%. This may require a clientside update.

**Comment by Zeyla-TW** [comment]
I believe this is due to the way that the spell system reads the base value and die sides. I believe this can be fixed by changing spell 45604 effect 2's base points from 20 to 19 and die sides from 0 to 1. It won't change what the spell does but iirc that should fix the tooltip display.
