### ISSUE TITLE
Swift Magic Rooster Dismount

### ISSUE THREAD

**Issue by loot29** [slowtorta/turtlewow-bug-tracker#1798]
**Please, provide a clear description what the bug is:**
Not being able to automatically dismount while on Swift Magic Rooster
**Steps to reproduce the behavior with as much detail as possible:**

1.Mount up Swift Magic Rooster
2. Cast Totem/Spell. Does not dismount. Not even when using various auto-dismount addons, or shagutweaks
3. Only manually possible, clicking the Rooster itself, or the Buff. 

**IDs of affected creatures, items, quests or spells with a link to the relevant page:**

NPC: https://database.turtle-wow.org/?npc=
Item: https://database.turtle-wow.org/?item=80431
Quest: https://database.turtle-wow.org/?quest=
Spell: https://database.turtle-wow.org/?spell=
Object: https://database.turtle-wow.org/?object=

**Expected behavior. Describe how it should work:**
It should be able to automatically dismount you when you cast a spell or similar. Especially with addons that were created exactly for that purpose. Automatic dismount works with all other tested Mounts.

**Comment by Lexiebean** [comment]
This is an addon issue.

Try https://github.com/CosminPOP/_LazyPig
