### ISSUE TITLE
FrameXML error CTD

### ISSUE THREAD

**Issue by Tellerofjokes** [slowtorta/turtlewow-bug-tracker#1799]
I downloaded the client and updated.
Logged in, created a character and pressed Enter Server
Loading bar fills, then crash to desktop with the following error box
![CTD](https://user-images.githubusercontent.com/110502985/182492103-19e3e34a-dba8-4973-bf59-2f45edb07772.png)

Thanks

**Comment by jameyboor** [comment]
You're most likely not running our wow.exe or your update has failed. Try to download the updated full client on the website and try that one.
