### ISSUE TITLE
A Glittering Opportunity can't be completed

### ISSUE THREAD

**Issue by SierraNairn** [slowtorta/turtlewow-bug-tracker#180]
A Glittering Opportunity can't be complete
https://database.turtle-wow.org/?quest=80395
How the quest works : you find a red object on the ground, you summon Kheyna Spinpistol, you complete the quest.
What does  not work: When you summon Kheyna Spinpistol you can't complete the  quest.
![WoW_otDGcZcc3S](https://user-images.githubusercontent.com/83077166/126327330-902f8c8b-26b9-48e8-9b1e-b05fcbdda39c.png)

**Comment by Kangaroux** [comment]
This happened to me as well. Relogging, deleting WDB folder, abandoning, none of these fixed it.

When I went to the gem someone had already activated her, so I'm not sure if that had any impact.

**Comment by slowtorta** [comment]
You must activate Crystal yourself in order to complete the quest. Please, try it again.

**Comment by Kangaroux** [comment]
@slowtorta Activating the crystal yourself doesn't fix it, at least for me (unless something was changed recently).
