### ISSUE TITLE
Grifter's Boots are BoP?

### ISSUE THREAD

**Issue by Zulmamwe** [slowtorta/turtlewow-bug-tracker#1805]
**Please, provide a clear description what the bug is:**
Grifter's Boots are becoming soulbound on pick up making it impossible to get a full set for non-leatherworkers
![image](https://user-images.githubusercontent.com/22682876/182577522-1a15cb05-7e7e-4109-a5ea-a09f4cc145c3.png)

**IDs of affected creatures, items, quests or spells with a link to the relevant page:**

Item: https://database.turtle-wow.org/?item=83255
Item: https://database.turtle-wow.org/?item=83405

**Expected behavior. Describe how it should work:**
They should probably be BoE

**Comment by xhummerx** [comment]
thats intented

**Comment by Zulmamwe** [comment]
> thats intented

Sucks :(
Wanted to wear that set on a rogue alt, definitely not gonna level LW on him just for that
