### ISSUE TITLE
Armory talents redirect user to WoWHead, instead of Turtle WoW

### ISSUE THREAD

**Issue by Mozaiczny** [slowtorta/turtlewow-bug-tracker#1806]
**Please, provide a clear description what the bug is:**
Armory redirect to [https://classic.wowhead.com/talent-calc/druid](url) instead of Turtle-WoW Calculator.
Turtle-WoW has altered talents relative to classic WoW, and this can cause significant differences.

**Steps to reproduce the behavior with as much detail as possible:**
1. Open any character armory, as example: [https://armory.turtle-wow.org/#!/character/Mozaiczny](url)
2. Click on linked talents: **0 / 0 / 0**
![image](https://user-images.githubusercontent.com/46848544/182592506-541266c4-36c0-47c3-88ce-151500e2f9ad.png)
3. User is redirected to **classic.wowhead** talent page.

**Expected behavior. Describe how it should work:**
In the above test case, for _step 3_, the expected result is the opening of talents on this site: [https://talents.turtle-wow.org/](url).

**Comment by slowtorta** [comment]
I'll move this issue to the internal tracker, thank you.
