### ISSUE TITLE
Paladin: Sanctified Command dispel resistance not working, mana refund not recorded

### ISSUE THREAD

**Issue by Rykenwolf** [slowtorta/turtlewow-bug-tracker#1808]
**Please, provide a clear description what the bug is:**

Refer earlier issue which was closed: https://github.com/slowtorta/turtlewow-bug-tracker/issues/1701
Note: Unclear if this is to be fixed next patch

Matter is reported to be fixed, however the Sanctified Command talent still does not provide any resistance to dispel.
Further, the mana refund does not appear in combat log, making it difficult to track.

**Steps to reproduce the behavior with as much detail as possible:**

1. Choose 2/2 Sanctified Command talent
2. Cast Seal of Command, have enemy player cast dispel/purge on paladin
3. Observe as Seal of Command is removed 100% of the time, thereby indicating there is no dispel resistance
4. Judge Seal of Command on target, watch as no combat log records refund of mana to paladin or the party

**Expected behavior. Describe how it should work:**

With Sanctified Command talent 2/2 chosen, paladin should resist Seal of Command dispelling 90% of the time. Further, it would be beneficial if the mana refund from judging Seal of Command was visible in the combat log to all party members, similar to how any mana gain is shown, such as the Shield Specialisation talent mana refund

**Comment by ratkosrb** [comment]
The fix is not live yet. You have to wait for the server update.
