### ISSUE TITLE
pvp rank bug?

### ISSUE THREAD

**Issue by Sallammbo** [slowtorta/turtlewow-bug-tracker#1811]
**Please, provide a clear description what the bug is:**

**Steps to reproduce the behavior with as much detail as possible:**

1. Why character named Salammbo get nothing ranking progress? We played together with mage (on screenshot) but he did and I not?
2. 
![WoWScrnShot_080322_212501](https://user-images.githubusercontent.com/110562916/182819490-c40454ab-2212-4096-ae2f-007391f70657.jpg)

3. 

**IDs of affected creatures, items, quests or spells with a link to the relevant page:**

NPC: https://database.turtle-wow.org/?npc=
Item: https://database.turtle-wow.org/?item=
Quest: https://database.turtle-wow.org/?quest=
Spell: https://database.turtle-wow.org/?spell=
Object: https://database.turtle-wow.org/?object=

**Expected behavior. Describe how it should work:**

**Comment by CosminPOP** [comment]
Did you hide your rank maybe ?
You can see your highest rank as Corporal, so you did rank up.

**Comment by Sallammbo** [comment]
> Did you hide your rank maybe ? You can see your highest rank as Corporal, so you did rank up.

nop, im not, i must see progress bar anyway. and i didn't hide anything

**Comment by slowtorta** [comment]
Related to https://github.com/slowtorta/turtlewow-bug-tracker/issues/1506
