### ISSUE TITLE
Donation Mount Shadowhorn Stag

### ISSUE THREAD

**Issue by loot29** [slowtorta/turtlewow-bug-tracker#1814]
**Please, provide a clear description what the bug is:**
The mount has no mountspecial at all. Pressing Space while standing does nothing.
**Steps to reproduce the behavior with as much detail as possible:**

1.Mount up
2. Press Space
3. 

**IDs of affected creatures, items, quests or spells with a link to the relevant page:**

NPC: https://database.turtle-wow.org/?npc=
Item: https://database.turtle-wow.org/?item=50406
Quest: https://database.turtle-wow.org/?quest=
Spell: https://database.turtle-wow.org/?spell=
Object: https://database.turtle-wow.org/?object=

**Expected behavior. Describe how it should work:**
Should at least have an animation, probably with a sound.

**Comment by slowtorta** [comment]
This moel doesn't have this animation by default, I'm sorry! If it's too much of a concern, please request a refund of tokens via in-game ticket :)
