### ISSUE TITLE
Thrash Blade

### ISSUE THREAD

**Issue by Vociferous121** [slowtorta/turtlewow-bug-tracker#1816]
**Please, provide a clear description what the bug is:**
Thrash Blade seems to have wrong PPM when equipped in off-hand. It should have an overall proc chance around 4% with information gained online and videos of DPS meters. The proc rate now, I'm unsure of the %, is definitely much lower than it should be. Gaining 1 extra swing through Thrash Blade maybe every 2 NPC's. Further, Rogue talent Blade Furry should proc the extra attack from Thrash Blade, and other proc on other weapons similar. As such, the off hand weapon should have an increased proc chance due to the way Rogues handles offhand weapons - including the talent Sword Specialization to cause swords to increase chance to gain an extra attack - there is no 5% + 4% proc from blade. Something is not calculating right.
 I will post an updated % based on a DPS meter that gathers what attack does what damage and how many times it procs to further help with this.

**Steps to reproduce the behavior with as much detail as possible:**

1. Equip Thrash Blade IN OFF-HAND
2.  Attack enemies
3.  Wonder why extra attack is not proccing

**IDs of affected creatures, items, quests or spells with a link to the relevant page:**

NPC: https://database.turtle-wow.org/?npc=
Item: https://database.turtle-wow.org/?item=17705
Quest: https://database.turtle-wow.org/?quest=
Spell: https://database.turtle-wow.org/?spell=12281
Object: https://database.turtle-wow.org/?object=

**Expected behavior. Describe how it should work:**
Proc rate should be increased. 5% from sword specialization + 4% from Thrash Blade. Even if it is not a +9% it should still be a +5% then add another +4% this is not occuring.

Sword Specialization and Thrash Blade extra attack should be able to proc together and they are not.

**Comment by GarBear121** [comment]
Further testing shows Rogue Sword Specialization at a 2% proc rate and Thrash Blade at a 1% proc rate. I will do a steady 100 mob kill to test a decent % of procs.
![Screenshot 2022-08-04 140653](https://user-images.githubusercontent.com/43530387/182920471-ca9e9d9d-36f9-4e54-8d9e-42304801ca63.png)
![Screenshot 2022-08-04 140201](https://user-images.githubusercontent.com/43530387/182920479-63423e0a-84a3-460d-b752-4ec711b5e2cb.png)

**Comment by GarBear121** [comment]
I stopped at less than 50 NPC kills. Thrash continues to drop in proc rate, even with Blade Furry active and Slice and Dice active at all times possible
![d](https://user-images.githubusercontent.com/43530387/182934512-ae0ca16c-d55b-4af6-aa99-4ee71cd76bcf.png)
![a](https://user-images.githubusercontent.com/43530387/182934521-fb78672e-15ec-4364-84ea-0b567bb374a0.png)
![b](https://user-images.githubusercontent.com/43530387/182934524-45ab9625-4b43-42d8-9e51-71a7b0e60a4c.png)
.

**Comment by GarBear121** [comment]
I believe the main cause to be a wrong increased chance to miss on off-hand weapons
![b](https://user-images.githubusercontent.com/43530387/182968706-e4c372fc-bf48-436f-9e8e-8bd303e8f86c.png)
![a](https://user-images.githubusercontent.com/43530387/182968707-71042776-d9cd-403d-a465-7a14d8a4c69f.png)
.

**Comment by GarBear121** [comment]
In conclusion I either believe chance to miss on off-hand weapons has the full 19% and it should be split between main-hand and off-hand weapons or Thrash Blade proc itself has a +50% chance to miss while wielding in off-hand. Note that other proc chance on hit weapons do not miss this often when in off-hand, if the proc misses at all. The proc should not miss. If it procs it procs. Chance to gain extra attack can be missed, but it should not occur more with off-hand than main-hand.
