### ISSUE TITLE
Un'Goro Gorillas

### ISSUE THREAD

**Issue by GarBear121** [slowtorta/turtlewow-bug-tracker#1817]
**Please, provide a clear description what the bug is:**
Un'Goro Gorillas can be pickpocketed but they have no loot?
**Steps to reproduce the behavior with as much detail as possible:**

1. Pick pocket an Un'Goro Gorilla
2.  Receive no loot

**IDs of affected creatures, items, quests or spells with a link to the relevant page:**

NPC: https://database.turtle-wow.org/?npc=6513
NPC: https://database.turtle-wow.org/?npc=6514
NPC: https://database.turtle-wow.org/?npc=6516
Spell: https://database.turtle-wow.org/?spell=921

**Expected behavior. Describe how it should work:**
Either produce loot or say target has no pockets to pick!

**Comment by GarBear121** [comment]
Unrelated - it seems the apes also have an high increased stealth detection compared to other NPC's. Is this correct?

**Comment by itswicky** [comment]
Are they considered humanoids instead of beasts?

**Comment by GarBear121** [comment]
> Are they considered humanoids instead of beasts?

They are considered beasts. So they should not have pockets to pick. But no message displays. You use pickpocket and the spells casts with no loot obtained.

**Comment by jameyboor** [comment]
Fixed in next update.
