### ISSUE TITLE
Insignia looting interrupted by releasing

### ISSUE THREAD

**Issue by burner1024** [slowtorta/turtlewow-bug-tracker#1820]
**Please, provide a clear description what the bug is:**
Releasing ghost interrupts insignia looting.

**Steps to reproduce the behavior with as much detail as possible:**

1. Kill enemy in bg.
2. Start looting insignia.
3. Enemy releases.
4. Looting interrupted, you have to loot again.

**Expected behavior. Describe how it should work:**

Looting not interrupted by releasing.

**Comment by tocopherylacetate** [comment]
enemy insignia looting giving a mark of honor when

**Comment by redmagejoe** [comment]
BG corpse looting in general is still quite buggy.

**Comment by Giperion** [comment]
That's looks like a vanilla bug actually.
But we fixed it anyway.
