### ISSUE TITLE
Fishing from Icepoint Rock yields nothing

### ISSUE THREAD

**Issue by GarBear121** [slowtorta/turtlewow-bug-tracker#1822]
**Please, provide a clear description what the bug is:**
Fishing does not produce any loot. Even the fisherman says the fish are always biting, what a lie! They bite, you just don't catch them lol.
![a](https://user-images.githubusercontent.com/43530387/183081846-b6f110ce-ee38-4eb4-9897-9d5eb05b6a92.png)

Seems the text is missing punctuation at the end. A period or something .
**Steps to reproduce the behavior with as much detail as possible:**

1. Take boat to Icepoint Rock
2.  Fish
3.  Receive no loot

**IDs of affected creatures, items, quests or spells with a link to the relevant page:**

NPC: https://database.turtle-wow.org/?npc=60543
Spell: https://database.turtle-wow.org/?spell=18248

**Expected behavior. Describe how it should work:**
Produce loot or not have a fisherman on the shore which signals a fishing area.

**Comment by geojak** [comment]
Same as cow lvl
