### ISSUE TITLE
Power Word: Shield on NPC blocks threat

### ISSUE THREAD

**Issue by Vociferous121** [slowtorta/turtlewow-bug-tracker#1823]
**Please, provide a clear description what the bug is:**
Observed in Scarlet Monastery on NPC Scarlet Chaplain. Their spell Power Word: Shield blocks threat from tank spells. Damage is caused to the shield but no threat is generated.

**Steps to reproduce the behavior with as much detail as possible:**

1.  Group in Scarlet Monastery Library
2.  Have tank attack NPC with Power Word: Shield active on the NPC as their ability
3.  Tank cannot generate threat until shield on NPC is gone

**IDs of affected creatures, items, quests or spells with a link to the relevant page:**

NPC: https://database.turtle-wow.org/?npc=4299
Spell: https://database.turtle-wow.org/?spell=6066
Spell: https://database.turtle-wow.org/?spell=27674

**Expected behavior. Describe how it should work:**

Threat should be generated when damaging Power Word: Shield ability on NPC.

**Comment by Zeyla-TW** [comment]
This is actually how threat works for damaging abilities and auto-attacks. The exception is non-damaging threat abilities like sunder armor, other debuffs, healing aggro or certain buffs/group buffs, all of which can still work even if a mob has an absorb shield active. Working as intended.
