### ISSUE TITLE
Paladin Redoubt talent triggering at 100%

### ISSUE THREAD

**Issue by Galuur** [slowtorta/turtlewow-bug-tracker#1824]
Paladin's Redoubt talent (at 3/3) is triggering at 100% instead of only on received critical strikes. Currently it has a perpetual duration during combat.

https://database.turtle-wow.org/?spell=20134

I've uploaded a youtube video showing the behaviour: https://www.youtube.com/watch?v=dtbnkUCFwHw

**Comment by geojak** [comment]
This is fixed already
