### ISSUE TITLE
Arcane Missiles often losing final wave/tick

### ISSUE THREAD

**Issue by eX1stenZT** [slowtorta/turtlewow-bug-tracker#1825]
**Please, provide a clear description what the bug is:**
Arcane Missiles often lose the final wave/tick. This happens most commonly during peak time with ~2.5k players online when there is a global delay.
It is possible that this is a common channeling issue, which was often times happening with Penance (wotlk) on private servers - although I can't remember any other channeling spell w/ waves, perhaps the NE priest racial spell.
With recent class changes buffing arcane and making it a viable spec, the absence of last tick pushes arcane back below other 2 specs as you effectively can lose ~10% dps on this along with clearcasting procs (assuming happening circa 50% of the time).

**Steps to reproduce the behavior with as much detail as possible:**

1. Log on a mage during peak time, as it is most commonly happening during. (It CAN happen when the server is doing perfectly fine with less people, although it is less common.)
2. Start casting 'Arcane Missiles (Rank 3)' onto any target. A dummy is fine.
3. Observe that quite often the last tick produces sound effect and animation, but no actual "wave" goes out.

**IDs of affected creatures, items, quests or spells with a link to the relevant page:**

Spell: https://database.turtle-wow.org/?spell=5145
(Note: any rank of arcane missiles should be affected, tested with 3 and 4 which have 5 ticks, r1 having 3 ticks, r2 4, r3 and higher get 5)

**Expected behavior. Describe how it should work:**
Arcane Missiles should produce 5 ticks and not skip the final tick.

**Comment by geojak** [comment]
This also affects other channeled abilities liek warlock rain of fire.

Or consecration which is not channeled and has its own ticket somewhere here

**Comment by redmagejoe** [comment]
Just tested this 3 hours after restart, and out of 10 casts, 3 of Arcane Missiles did not fire their last volley. This is still not completely fixed assuming the fix was applied to live in the last update, and thus the issue needs to be reopened.

Rank 3 was used to test, combat log confirms visual observation of projectiles. The interval between volleys is still inconsistent as well.

**Comment by geojak** [comment]
@ratkosrb see above pls

**Comment by ratkosrb** [comment]
I made another change, you can test it next week. And if it still doesn't work then try to catch the issue on video with the combat log open.

**Comment by redmagejoe** [comment]
This is fixed with @ratkosrb's latest fix after tonight's server maintenance.
