### ISSUE TITLE
Zandalar Signet of Tenacity does not work

### ISSUE THREAD

**Issue by afizzler** [slowtorta/turtlewow-bug-tracker#1826]
The new ZG signet added recently does not apply the enchant to a shoulder.

**Comment by davmon01** [comment]
I'd like to second this, I am unable to apply this enchant to my shoulders. I wonder if the problem is due to there already being a +5 nature res enchant on the shoulders and it's not triggering the pop-up to replace it.

**Comment by Zebouski** [comment]
this isnt fixed, just tried this today and have the same issue.

**Comment by Twili1** [comment]
Same here, enchant still not working

**Comment by Zebouski** [comment]
https://cdn.discordapp.com/attachments/737297929584377947/1017536328285560853/unknown.png
