### ISSUE TITLE
Battery-Powered Crowd Pummeler cannot be charged

### ISSUE THREAD

**Issue by chloejaynebond** [slowtorta/turtlewow-bug-tracker#1827]
**Please, provide a clear description what the bug is:**

**Steps to reproduce the behavior with as much detail as possible:**

1. Loot Schematic: Hypertech Battery Pack from Mekgineer Thermaplugg in Gnomer. Create some of these.
2. Loot Schematic: Battery-Powered Crowd Pummeler for Gizlock in Maraudon. Make the weapon.
3. See that the weapon has no charges and that the batteries cannot be used in conjunction with it.

**IDs of affected creatures, items, quests or spells with a link to the relevant page:**

NPC: https://database.turtle-wow.org/?npc=
Item: https://database.turtle-wow.org/?item=60099 and https://database.turtle-wow.org/?item=60098
Quest: https://database.turtle-wow.org/?quest=
Spell: https://database.turtle-wow.org/?spell=
Object: https://database.turtle-wow.org/?object=

**Expected behavior. Describe how it should work:**
The batteries should charge the Pummeler

**Comment by ratkosrb** [comment]
The battery powered crowd pummeler does not have charges, because its battery powered. You need a battery to activate the effect. It consumes a battery when used.

**Comment by ratkosrb** [comment]
The reason it looks like it does nothing at the moment is because the new MPQ patch is not live yet. The game client needs to be updated for it to work properly.

**Comment by chloejaynebond** [comment]
Thank you for the fast response :)
