### ISSUE TITLE
"Eastern Kingdoms" in BG queue indicator

### ISSUE THREAD

**Issue by burner1024** [slowtorta/turtlewow-bug-tracker#1828]
**Please, provide a clear description what the bug is:**

![Captura de pantalla de 2022-08-06 12-50-27](https://user-images.githubusercontent.com/1279852/183236142-3b62974f-9069-4d31-9c33-1645cf20389a.png)

**Steps to reproduce the behavior with as much detail as possible:**

Uhm, hard to say for sure, but I think this mostly happens when you queue for some bgs, then log out and log in again in a few mins.

**Expected behavior. Describe how it should work:**

Should not have "Eastern Kingdoms" there.

**Comment by slowtorta** [comment]
Attempting to fix it in 1.16.4.

**Comment by Gurky-Turtle** [comment]
https://github.com/slowtorta/turtlewow-bug-tracker/issues/3372

Reopening.

**Comment by Muigin** [comment]
This issue no longer seems relevant.
