### ISSUE TITLE
Natural Weapons does not add melee hit% 

### ISSUE THREAD

**Issue by konungr10** [slowtorta/turtlewow-bug-tracker#1829]
Natural Weapons does not add melee hit% like the tooltip says

**Steps to reproduce the behavior with as much detail as possible:**

1.  Select three points in Natural Weapons talent
2. Equip 6% hit from gear
3.  Attack "boss" dummy from behind.  Witness yellow damage misses.

With 3 points in Natural Weapons, and 6% hit from gear, the character should not miss on a boss with yellow damage abilities.

**Comment by konungr10** [comment]
Already opened.

**Comment by konungr10** [comment]
Was opened before, but found it under closed, as in "fixed bugs."  It is not fixed.

**Comment by Zebouski** [comment]
you might be just seeing the 1% miss bug that is affecting vmangos upstream https://github.com/vmangos/core/issues/1419

can you sit infront of the dummy for maybe an hour, with an addon to record hits/misses, and confirm if you are getting 4% miss, or 1% miss? if its the former then yes this talent is bugged. if the latter, no it's just that other bug that affects all meele on all vmanogs servers.

**Comment by burner1024** [comment]
You don't need to sit for an hour, just get enough +hit gear, and see if you still get misses.

**Comment by Zebouski** [comment]
> You don't need to sit for an hour, just get enough +hit gear, and see if you still get misses.

you do, as there is 1 confirmed upstream bug, and this being the unconfirmed 2nd bug. A big sample size is needed to tell if you get 1% miss or 4% miss.
