### ISSUE TITLE
Blood Frenzy Druid Talent

### ISSUE THREAD

**Issue by konungr10** [slowtorta/turtlewow-bug-tracker#1831]
When two points are taken, the Blood Frenzy talent in the druid feral tree does not increase melee haste by 12%

1.  Take blood frenzy talent 2/2
2.  Attack target dummy 
3.  Use tiger's fury
4.  Observe player's attack speed not increasing

**IDs of affected creatures, items, quests or spells with a link to the relevant page:**

NPC: https://database.turtle-wow.org/?npc=
Item: https://database.turtle-wow.org/?item=
Quest: https://database.turtle-wow.org/?quest=
Spell: https://database.turtle-wow.org/?spell=  Tiger's Fury
Object: https://database.turtle-wow.org/?object=

When 2/2 taken in blood frenzy, and in cat form, a player's melee attack speed should increase by 12% when under the Tiger's Fury self-buff ability.  Of note, 2/2 blood frenzy DOES increase Tiger's Fury duration as intended, so at least that works.

**Comment by konungr10** [comment]
Already Reported, apparently.

**Comment by konungr10** [comment]
Already reported, but found under the "closed" category, as in fixed.  It is not fixed.

**Comment by Platinumcoated** [comment]
you made the 3rd report about this.
it's reported here already https://github.com/slowtorta/turtlewow-bug-tracker/issues/1624
