### ISSUE TITLE
Friend's characters are bugged when trying to follow

### ISSUE THREAD

**Issue by Mozlo** [slowtorta/turtlewow-bug-tracker#1833]
**Please, provide a clear description what the bug is:**
WHenever my friend follows my character it starts off fine. Soon though his character begins to jitter and then if I turn a corner his character starts running off in a different direction and does not follow. We tried making  a new character that was not a night elf male but it did the exact same thing. He has also deleted and re-exported the client which did not fix the issue. He is therefore unable to follow anyone at all as this persists across his characters and whomever he tries to follow.

**Steps to reproduce the behavior with as much detail as possible:**

1. Be on his characters and try to follow anyone after right clicking their portrait and clicking follow
2. 
3. 

**IDs of affected creatures, items, quests or spells with a link to the relevant page:**

NPC: https://database.turtle-wow.org/?npc=
Item: https://database.turtle-wow.org/?item=
Quest: https://database.turtle-wow.org/?quest=
Spell: https://database.turtle-wow.org/?spell=
Object: https://database.turtle-wow.org/?object=

**Expected behavior. Describe how it should work:**
When I follow him it works perfectly like it should in retail wow however his bugs 100% of the time.

**Comment by jameyboor** [comment]
Client side issue. Try enabling vsync.
