### ISSUE TITLE
Combat is "laggy"

### ISSUE THREAD

**Issue by andersahp** [slowtorta/turtlewow-bug-tracker#1834]
1. Combat seem more laggy / slower than in classic.  Swings and spells often have an extra delay before hitting, and often two white swings are shown simultaneously even though swing timer is 3 sec. My ping is 19 so its not real "lag" and the issue has been there consistently since i started playing. From discord i know its a know issue, perhaps inherent to the client version. As Zaas said on discord:

Zaas: so its not batching
[1:00 AM] Zaas: its how abilities are sent to the server
[1:00 AM] Zaas: theres no real queueing
[1:00 AM] Zaas: when your client is able to send a spell, only then is it sent
[1:00 AM] Zaas: this makes it WAY shittier of a client to play on
[1:00 AM] Zaas: this is the big reason why in old 2005 clips
[1:00 AM] Zaas: casters would press frostbolt
[1:01 AM] Zaas: then wait like a second

One could mistake it for batching, but its not consistently batching. 

Its very easy to notice in PVP combat, and its almost unplayable as melee. Comparing with combat on classic server its immediately obvious. 

I assume there's no fix for this, but i would like to know if its something you are aware off and are trying to fix?

**Comment by 9600bauds** [comment]
So obviously there's many differences between how classic and 1.12 client do netcode and batching and whatever, but it really sounds like what you're describing is just how melee attack floating numbers are tied to animations. The damage is done instantly but the floating text doesn't appear until your character has time to swing, and sometimes the animation gets interrupted so the engine has to wait until your next swing to display the whitenumber, resulting in what seems like 2 melee attacks happening at the same time. This actually has nothing to do with netcode and is just an animation issue (and it's not even a bug, just how blizz decided to code it for some reason). The damage happens exactly like expected. Pay attention to the health bar or install a floating damage text addon and you'll see how you actually do damage the first swing despite no number popping up, and in fact you do damage before the animation even starts, the game just delays the number from popping up to make it more cinematic or whatever.

**Comment by slowtorta** [comment]
Fixing performance issues is an on-going process.
