### ISSUE TITLE
Shadow Word Pain bugging out on some bosses

### ISSUE THREAD

**Issue by Apimius** [slowtorta/turtlewow-bug-tracker#1835]
**Please, provide a clear description what the bug is:**

Sometimes shadow word pain does not apply even though the enemy has not reached debuff cap yet, atleast for shadow word pain

**Steps to reproduce the behavior with as much detail as possible:**

1.raid
2. notice that shadow word pain does not apply sometimes

**Comment by jameyboor** [comment]
Fixed due to non present client side showing of extended debuffs.
