### ISSUE TITLE
Compact Harvest Reaper corpses persisting longer than expected

### ISSUE THREAD

**Issue by Azeron223** [slowtorta/turtlewow-bug-tracker#1838]
The corpses of [Compact Harvest Reapers](https://database.turtle-wow.org/?npc=2676) (NPC ID: 2676) spawned by [Venture Co. Tinkerers](https://database.turtle-wow.org/?npc=677) (NPC ID: 677) seem to persist for roughly 1 hour after being killed by players, this seems excessive when compared to the corpses of most NPCs killed by players.

I imagine these should be despawning at the same rate as any other NPC in the game,

**Comment by slowtorta** [comment]
Fixed  — 08/08/2022
