### ISSUE TITLE
Only 1 combo point is awarded to feral cat upon an ability's critical hit with 2/2 Primal Fury

### ISSUE THREAD

**Issue by chloejaynebond** [slowtorta/turtlewow-bug-tracker#1842]
**Please, provide a clear description what the bug is:**

**Steps to reproduce the behavior with as much detail as possible:**

1. Create a druid. Take 2/2 Primal Fury.
2.  Attack something using abilities. Note that crits do not award combo points.
3. 

**IDs of affected creatures, items, quests or spells with a link to the relevant page:**

NPC: https://database.turtle-wow.org/?npc=
Item: https://database.turtle-wow.org/?item=
Quest: https://database.turtle-wow.org/?quest=
Spell: https://database.turtle-wow.org/?spell=
Object: https://database.turtle-wow.org/?object=

**Expected behavior. Describe how it should work:**
Crits should award 2 combos points with 2/2 Primal Fury.

**Comment by Zeuaireus** [comment]
I can also confirm Primal Fury is not given additional combo points from Cat form critical hits. I'd also like to add, Primal Fury is also not granting additional rage for critical hits with bear form. This talent was working prior to this latest patch.

**Comment by Zeuaireus** [comment]
Update. The Latest Server Maintenance appears to have fixed the combo point issue with Primal Fury for Cat Form, as well as the rage generation with the same talent for Bear Form. However, combat log is showing only 5 rage is being generated instead of 10 rage with 2/2 points applied to the talent. 

I have attached a screen shot taken at 11.12am server time.  https://imgur.com/a/0sBY9yG

**Comment by cyaohiri** [comment]
This works fine for me.

**Comment by Testerrosaurus** [comment]
Both Combo points and rage seem to work fine right now.
(combo points were fixed pretty fast right after 1.16.1 update and rage got fixed a few weeks after that)
I suppose this issue should be closed now.

**Comment by slowtorta** [comment]
Thanks for testing, we appreciate it.
