### ISSUE TITLE
Improved Shadow Form being Unlearned when Respeccing

### ISSUE THREAD

**Issue by Darkraggs** [slowtorta/turtlewow-bug-tracker#1843]
**Please, provide a clear description what the bug is:**
Each time I respec while I have the Shadow Form talent, it removes Improved Shadow Form from my book and does not return it after getting the Shadow Form talent again, forcing me to return to a class trainer to learn the Improved version again.

**Steps to reproduce the behavior with as much detail as possible:**

1. Spend talent points to get Shadow Form
2. Learn Improved Shadow Form from the trainer
3. Respec with the Goblin Brainwashing Device
4. Spend Talent points to get Shadow Form
5. Look at your chat and it'll show "You learned a new spell: Shadowform" then "You learned a new spell: Pain Spike", but not another line that mentions learning Improved Shadowform
6. Check spellbook for Improved Shadow Form on Page 1 of the Shadow Magic tab

**IDs of affected creatures, items, quests or spells with a link to the relevant page:**

Spell: https://database.turtle-wow.org/?spell=45553
https://database.turtle-wow.org/?spell=47271

**Expected behavior. Describe how it should work:**
After respeccing, if I get the Shadow Form talent again it should also return the Improved Shadow Form to my book rather than having to return to a trainer to relearn the spell just like Pain Spike currently does.

**Comment by Apimius** [comment]
bump

**Comment by suggney** [comment]
bump

**Comment by Zebouski** [comment]
this is affecting me as well

**Comment by Rammue** [comment]
WTB fix for this issue as someone who frequently switches to shadow for non group activities. Please and thanks.

**Comment by Northyn** [comment]
Consistent issue for me on my priest as well.

**Comment by Gurky-Kronos** [comment]
Same happened to me
