### ISSUE TITLE
Double "Alliance" in reputation tab

### ISSUE THREAD

**Issue by burner1024** [slowtorta/turtlewow-bug-tracker#1844]
**Please, provide a clear description what the bug is:**
![Captura de pantalla de 2022-08-08 13-15-19](https://user-images.githubusercontent.com/1279852/183351699-ec53e4bd-5f9e-4429-8f71-4a3c32c7e583.png)

Clicking on the second one expands all faction lists.

**Steps to reproduce the behavior with as much detail as possible:**

1. Open reputation tab.

**IDs of affected creatures, items, quests or spells with a link to the relevant page:**

NPC: https://database.turtle-wow.org/?npc=
Item: https://database.turtle-wow.org/?item=
Quest: https://database.turtle-wow.org/?quest=
Spell: https://database.turtle-wow.org/?spell=
Object: https://database.turtle-wow.org/?object=

**Expected behavior. Describe how it should work:**
Shouldn't have second "Alliance" item.

**Comment by slowtorta** [comment]
I'm unable to reproduce this bug. Try to download a fresh client from our website, please.

**Comment by cyaohiri** [comment]
I'm seeing the same thing. The top Alliance tab shows the capitals, but the one on the bottom shows the rest, and is under "Other".

**Comment by slowtorta** [comment]
Attempting to fix it in 1.16.4.
