### ISSUE TITLE
Shield Specialization bug

### ISSUE THREAD

**Issue by thp1990** [slowtorta/turtlewow-bug-tracker#1845]
I wish to report that Shield Specialization talent no longer restore 2% of maximum mana after the patch 1.16.2. Also Redoubt seems to trigger much less often, after the patch too.

https://ibb.co/VSSsKpC

**Comment by Zmitrok1984** [comment]
Yes, the same for me, blocking isn't restore mana now.
![image](https://user-images.githubusercontent.com/99164611/183365760-7eda9389-79cf-4f3e-8723-226dcbb43e6c.png)

**Comment by Zmitrok1984** [comment]
Now restoring mana  at blocking fixed.
But at blocking my character play animation with drinking potion.

**Comment by ratkosrb** [comment]
Issues with this will fixed next update.
