### ISSUE TITLE
BG finder tooltip wrong

### ISSUE THREAD

**Issue by burner1024** [slowtorta/turtlewow-bug-tracker#1849]
**Please, provide a clear description what the bug is:**
BG finders now requires left click, but tooltip says right.
![Captura de pantalla de 2022-08-08 16-13-16](https://user-images.githubusercontent.com/1279852/183383796-f27d55b9-43f0-4102-aa71-87aabd16a705.png)

**Steps to reproduce the behavior with as much detail as possible:**

1. Hover over finder.

**Expected behavior. Describe how it should work:**
Should have correct tooltip.

**Comment by slowtorta** [comment]
Fixed in patch 1.16.4
