### ISSUE TITLE
Master Conjuror talent not working 1.16.3

### ISSUE THREAD

**Issue by tocopherylacetate** [slowtorta/turtlewow-bug-tracker#1851]
**Please, provide a clear description what the bug is:**
Healthstones do not reflect points spent in the new Master Conjuror talent.
**Steps to reproduce the behavior with as much detail as possible:**

1. Create healthstone
2. Add 1 point to Master Conjuror
3. Try to create another healhstone
4. Realize you can't, indicating that the talent hasnt tried making a different ID of health/spell/firestone
5. Cry that you're not only obsoleted by Tea with Sugar, but now your green cookie is forever stuck at 1200hp
6. Cry that youll never be good enough to use spellstones in pvp properly after the trauma of using one while worldbuffed still lingers
7. Laugh as you look at your firestone and delete it immediately

**IDs of affected creatures, items, quests or spells with a link to the relevant page:**

https://database.turtle-wow.org/?search=master+conjuror can you add this too
https://database.turtle-wow.org/?search=healthstone there are like 3 versions of each healthstone indicating how many (old) talent points are spent in each

**Expected behavior. Describe how it should work:**
Each point in master conjuror should let you create another healthstone, allowing players to have 3 at once if 3 warlocks are present with their differing point allocations.

**Comment by Tinyfin-github** [comment]
https://github.com/slowtorta/turtlewow-bug-tracker/issues/1890
