### ISSUE TITLE
Kargath Zepplin killing players

### ISSUE THREAD

**Issue by Azeron223** [slowtorta/turtlewow-bug-tracker#1852]
_One minor note, I did look for this bug in the outstanding open bug list, but failed to find it, hopefully this hasn't been reported yet!_

The custom zepplin ride from Durotar to Kargath is currently killing players upon arriving in Badlands.

Simply jump on the zepplin and take the ride over to Kargath, as soon as you load into the zone your character is killed, I didn't see anyting in the combat log but I would assume it may be an issue causing players to die from fall damage.

This also may not effect all races, I've seen a Tauren male survive the journey, but based on [this screenshot](https://imgur.com/a/ONTWxa7) you can see many other races are effected.

**Comment by slowtorta** [comment]
Known issue, listed here: https://github.com/slowtorta/turtlewow-bug-tracker/issues/1087
