### ISSUE TITLE
Skinning rate for heavy hides is well below what it should be

### ISSUE THREAD

**Issue by VladislavLeontev** [slowtorta/turtlewow-bug-tracker#1853]
**Please, provide a clear description what the bug is:**
Skinning rate for heavy hides is well below of what is in turtle wow database for Ghostpaw Alfas and Elder Shadowhorn Stags

**Steps to reproduce the behavior with as much detail as possible:**

1. Go to Ashenvale and kill 100 Ghostpaw Alfas and Elder Shadowhorn Stag, Skin them.
2. Get 67 medium leather, 26 heavy leather and 7 medium hides.
3. NO HEAVY HIDES, according to database percentages i should've got at least one already.

**IDs of affected creatures, items, quests or spells with a link to the relevant page:**

NPC: https://database.turtle-wow.org/?npc=3825
and https://database.turtle-wow.org/?npc=3818

Item: https://database.turtle-wow.org/?item=4235

**Expected behavior. Describe how it should work:**
Should get at least one heavy hide via skinning statistically.

**Comment by jameyboor** [comment]
"NO HEAVY HIDES, according to database percentages i should've got at least one already."

That's not how percentages work.

Works as expected.
