### ISSUE TITLE
Paladin - Heart of the Crusader not increasing Holy Dmaage and Retribution Aura is white damage and not benefitting from +holy damage effects

### ISSUE THREAD

**Issue by LawfulEvilMagus** [slowtorta/turtlewow-bug-tracker#1854]
**Please, provide a clear description what the bug is:**

As stated in the title. The tooltip and buff/debuff for judgement of the Crusader or crusader strike doesn't seem to ahve updated damage numbers and the damage seems to be the same with or without the talent.

In addition, Retribution Aura is white damage (I think the same is for Thorns on Druid). They are meant to be yellow damage I believe so they scale off of spell power and +dmg effects (like the ebforementioned crusader strike/judgement of the crusader

**Steps to reproduce the behavior with as much detail as possible:**

1. Use holy abilities as paladin without talent and with talent when debuff is present
2. Be attacked while under effect of Retribution Aura. Damage is white and will not increase vs holddmg+ effects
3. 

**IDs of affected creatures, items, quests or spells with a link to the relevant page:**

NPC: https://database.turtle-wow.org/?npc=
Item: https://database.turtle-wow.org/?item=
Quest: https://database.turtle-wow.org/?quest=
Spell: https://database.turtle-wow.org/?spell=
Object: https://database.turtle-wow.org/?object=

**Expected behavior. Describe how it should work:**

Thorns/Retribution Aura  are meant to be yellow damage I believe so they scale off of spell power and +dmg effects (like the beforementioned crusader strike/judgement of the crusader

**Comment by ratkosrb** [comment]
The damage color is normal for vanilla.
