### ISSUE TITLE
Can't Dispel Curses in Moonkin form.

### ISSUE THREAD

**Issue by Milton3450** [slowtorta/turtlewow-bug-tracker#1855]
**Please, provide a clear description what the bug is:**
Tooltip for Moonkin form states that remove curse can be cast in Moonkin form. 
**Steps to reproduce the behavior with as much detail as possible:**

1. Go into Moonkin Form.
2. Cast remove curse on someone or yourself.
3. It will shift you out of form.

**IDs of affected creatures, items, quests or spells with a link to the relevant page:**

**Expected behavior. Describe how it should work:**
Should dispel curse and keep you in Moonkin Form.

**Comment by Ziandos** [comment]
Can confirm. Just hit 40 today and tried Moonkin form. Can't dispel without being kicked out of form.

**Comment by ratkosrb** [comment]
Will be fixed next time there is a client update https://github.com/slowtorta/turtle-wow/commit/468b7770d6f8ea12a3db772acad11c9582037211
