### ISSUE TITLE
Suggestion: Open Captain Grayson's quests to Horde

### ISSUE THREAD

**Issue by usedcars4cheap** [slowtorta/turtlewow-bug-tracker#1857]
Captain Grayson, the ghost in Westfall offers 3 vanilla baseline quests to players - these are limited to Alliance only on Turtle WoW but were open to both factions in Vanilla.

https://database.turtle-wow.org/?npc=392
https://classic.wowhead.com/npc=392/captain-grayson#starts

Suggestion: allow Horde to complete the following quests:
https://database.turtle-wow.org/?quest=103 (Keeper of the Flame)
https://database.turtle-wow.org/?quest=152 (The Coast Isn't Clear)
https://database.turtle-wow.org/?quest=104 (The Coastal Menace)

**Comment by dlaub-100** [comment]
Yes, I love to drop into Westfall with my Horde characters and kill Murlocs! Especially hunters, as there are some key pets available here at level 17-18. Thanks!
