### ISSUE TITLE
Can not turn in quest The Zoram Strand

### ISSUE THREAD

**Issue by blightborne92** [slowtorta/turtlewow-bug-tracker#1859]
**Please, provide a clear description what the bug is:**

after I collected 15 Wrathtail Heads, it is not possible to get more, because quest behaves like it is finished. After go to questgiver, yellow questionmark is visible but I can not turn in quest.
**Steps to reproduce the behavior with as much detail as possible:**

1. Get x heads required to complete q
2. Die
3. Ressurrect
4. Get few more heads
5. The q seems to be finished
6. Can not turn in quest

**IDs of affected creatures, items, quests or spells with a link to the relevant page:**

NPC: https://database.turtle-wow.org/?npc=3845
Item: https://database.turtle-wow.org/?item=5490
Quest: https://database.turtle-wow.org/?quest=1008

**Expected behavior. Describe how it should work:**

Quest should have been able to turn in after I get 20 heads not 15. 
![twow](https://user-images.githubusercontent.com/110857176/183513659-92096d0d-06f9-47d1-82a1-3e9fe5f68f53.jpg)
![TWOW2](https://user-images.githubusercontent.com/110857176/183513675-267108af-d743-4cbe-b942-ca202a8bb1ca.jpg)

**Comment by slowtorta** [comment]
Couldn't reproduce. Working as intended. Please delete your WDB folder and try again :) 
![image](https://user-images.githubusercontent.com/66763404/184018748-0b49870e-752f-4b05-92d0-efeed05da557.png)
