### ISSUE TITLE
 Speedy Racer Goggles  not obtainable from Gahz'rilla

### ISSUE THREAD

**Issue by SierraNairn** [slowtorta/turtlewow-bug-tracker#186]
Speedy Racer Goggles not obtainable from Gahz'rilla
https://database.turtle-wow.org/?item=9653 -Speedy Racer Goggles
https://database.turtle-wow.org/?quest=2770 -Quest Gahz'rilla 

In the database it shows you can choose between carrot on a stick and the speedy racer googles.
In  game you don't get this choice.
This item was removed in the  original vanilla cause nobody was choosing it over carrot on a stick.
![WoW_7j57eECdb6](https://user-images.githubusercontent.com/83077166/126769252-a2901292-640c-4d78-b49b-bbf4b5cb1037.png)

**Comment by slowtorta** [comment]
DB shows also the old and the new version of the quest. Here's the correct one: https://database.turtle-wow.org/?quest=2770 (I'll see that it doesn't display the old patch rewards). I don't think we should add it, because googles on Turtle are available on the Mirage Raceway now.
