### ISSUE TITLE
WANTED: Valadorn! - Get logged out when trying to open quest

### ISSUE THREAD

**Issue by Marrikulus** [slowtorta/turtlewow-bug-tracker#1861]
**Please, provide a clear description what the bug is:**

I get logged out when trying to open the quest "WANTED: Valadorn!".
I can confirm that the quest is broken in both patch-W and patch-X.
I could not find anything in the logs about what went wrong, and there was no error logged in the console.

**Steps to reproduce the behavior with as much detail as possible:**

1. Go to the Wanted board outside the bank of ogrimmar
2. Open the wanted board panel
3. Click on the quest
4. Game logs you out

**IDs of affected creatures, items, quests or spells with a link to the relevant page:**

Quest: https://database.turtle-wow.org/?quest=50323

**Expected behavior. Describe how it should work:**

Should open the quest description without getting logged out.

![turtle_wow_error1](https://user-images.githubusercontent.com/15344566/183525644-0a9d1372-aaca-46df-9500-d27c594f0437.png)
![turtle_wow_error2](https://user-images.githubusercontent.com/15344566/183525658-bd0a0cde-4cbb-461b-8967-42c1ea89582b.png)

**Comment by slowtorta** [comment]
Couldn't reproduce. The Bounty Board is working. Please clear your WDB folder an try again.
