### ISSUE TITLE
Male troll /wave voice is female

### ISSUE THREAD

**Issue by dole555** [slowtorta/turtlewow-bug-tracker#1867]
**Please, provide a clear description what the bug is:**
Male troll /wave voice is female. checked the other emotes and the rest are fine. also female troll emotes are fine (are female)

**Steps to reproduce the behavior with as much detail as possible:**

1. make troll male character
2. do /wave
3. female

**IDs of affected creatures, items, quests or spells with a link to the relevant page:**

NPC: https://database.turtle-wow.org/?npc=
Item: https://database.turtle-wow.org/?item=
Quest: https://database.turtle-wow.org/?quest=
Spell: https://database.turtle-wow.org/?spell=
Object: https://database.turtle-wow.org/?object=

**Expected behavior. Describe how it should work:**

**Comment by LashDee** [comment]
Hey! Still is still an issue.

(thanks for a great game experience )

**Comment by slowtorta** [comment]
This can be fixed only with the client update (which is only planned for this Autumn). Internally, it's fixed :)

**Comment by LashDee** [comment]
Ah ok nice! :D Thanks for the answer buddy!
