### ISSUE TITLE
Hunter Quest - Artorius [Winterspring demon NPC]

### ISSUE THREAD

**Issue by FeanoroWoW** [slowtorta/turtlewow-bug-tracker#1868]
**Please, provide a clear description what the bug is:**
Artorius, a demon NPC for the hunter epic quest, leashes far too quickly. This NPC is intended to be kited over a long distance (easily verified in many video guides and writeups), typically up a hill and onto the road. When spawned and pulled from the location in the screenshots (58, 21 coordinates) and kited up the nearby hill towards the road, the NPC evades and resets approximately 3/4 of the way up.

![image](https://user-images.githubusercontent.com/110290116/183713675-95b5a695-d0d9-4ea0-8370-8e351ff1da42.png)
![image](https://user-images.githubusercontent.com/110290116/183724678-15eb6eed-22c5-411a-9d9b-c1d055f7fc1b.png)

**Steps to reproduce the behavior with as much detail as possible:**
1. As a hunter on the quest "Stave of the Ancients", speak to Artorius the Amiable at the given coordinates (58, 21) or that rough location. Landmarks include a small rock formation and small tree. This will cause the spawn of the demon NPC.

2. Attempt to kite the demon uphill with Serpent Sting rank 8, using Arcane Shot rank 1 on cooldown to maintain threat.

4. The demon will correctly maintain aggro until approximately (55,22), long before reaching the road, when it will leash, evade, and reset.

**IDs of affected creatures, items, quests or spells with a link to the relevant page:**
Artorius the Doombringer, demon NPC
https://database.turtle-wow.org/?npc=14535
https://classic.wowhead.com/npc=14535/artorius-the-doombringer

Artorius the Amiable, Tauren NPC that spawns the above
https://database.turtle-wow.org/?npc=14531
https://classic.wowhead.com/npc=14531/artorius-the-amiable

Stave of the Ancients, class quest that requires killing the demon NPC
https://database.turtle-wow.org/?quest=7636
https://classic.wowhead.com/quest=7636/stave-of-the-ancients

WoWhead guide for quick verification that kiting to the road is intended
https://classic.wowhead.com/guides/classic-hunter-quest-ancient-petrified-leaf#artorius-the-doombringer

**Expected behavior. Describe how it should work:**
The NPC should be able to be kited much further without leashing. 

Note: The expected long distance kite was reported to be the case in 1.16.1 by Jamey, but perhaps the 1.16.2 patch reverted the change.

**Comment by slowtorta** [comment]
This was fixed a while ago.
