### ISSUE TITLE
Warlock summon and hunter pets

### ISSUE THREAD

**Issue by dole555** [slowtorta/turtlewow-bug-tracker#1869]
**Please, provide a clear description what the bug is:**
I received a summon (while in a raid), i got summoned but my pet just started running to my new location.

**Expected behavior. Describe how it should work:**
Pets should port to the new location too on summon. or at least just despawn. not aggro the whole raid:)

**Comment by slowtorta** [comment]
If the distance between your current position and your teleport destination isn't too far, the pet won't be de-summoned. You had to consider that yourself :)

If it works not the same way on Classic, please submit a video proof!
