### ISSUE TITLE
Hunter pet trainer doesn't teach avoidance

### ISSUE THREAD

**Issue by OrnsteinHunter** [slowtorta/turtlewow-bug-tracker#1870]
**Please, provide a clear description what the bug is:**

The 1.16.1 notes imply you can learn the pet avoidance talent which reduces the damage your pet takes from aoe, but it currently is not at the pet trainer.

**Comment by Khanz0** [comment]
I think they still dont add into the game

**Comment by Jacccop** [comment]
bumping this as it has been a long time since class changes were released and it is still not fixed

**Comment by TheSyg** [comment]
Still bugged @ February 7th
