### ISSUE TITLE
[Paladin] Shield specialization triggers the potion cooldown

### ISSUE THREAD

**Issue by Velite12** [slowtorta/turtlewow-bug-tracker#1871]
![image](https://user-images.githubusercontent.com/45871932/183730257-d8592c54-e81f-43f2-9a47-b8d58e2201e4.png)

1. Block with Shield Specialization 3/3
2. All potions go on cooldown

**Expected behavior. Describe how it should work:**

Shield Specialization should not trigger the potion cooldown.

**Comment by ratkosrb** [comment]
Already fixed.
