### ISSUE TITLE
No Rested XP

### ISSUE THREAD

**Issue by Sumbats** [slowtorta/turtlewow-bug-tracker#1873]
**Please, provide a clear description what the bug is:**

No rested xp from staying still in inns and tents.

Have not enabled glyph of exhaustion.

Noticed another player having a similar issue today: https://forum.turtle-wow.org/viewtopic.php?f=3&t=3580&p=21550&hilit=no+rested+xp#p21550

Only warmode on for me. 

**Steps to reproduce the behavior with as much detail as possible:**

1. Tried Goldshire and Sentinel Hill inns and player tents

**Comment by slowtorta** [comment]
Please right-click on your character portrait and see if your XP gains are enabled.

**Comment by Sumbats** [comment]
Hey Torta,

My XP gains have been enabled since before I posted this issue.

**Comment by slowtorta** [comment]
So XP gains are enabled but the issue persists?

**Comment by Sumbats** [comment]
Yes the issue still persists. However, yesterday when I logged after 24h when I left my char in the Sentinel Hill inn, my rested xp increased from 0 to 12%. Again, I left it in there and when I logged on this morning, it was 24%. Rested XP is not supposed to accumulate this slow right?

**Comment by Sumbats** [comment]
The issue seems to be that I do have rested XP but its just not showing the correct value in the XP bar.

**Comment by slowtorta** [comment]
Looks it's working as intended for you, I'm sorry :) Use Survival's Tents to gain more rested XP :)
