### ISSUE TITLE
Simple Grammar Mistakes 

### ISSUE THREAD

**Issue by GarBear121** [slowtorta/turtlewow-bug-tracker#1878]
**Please, provide a clear description what the bug is:**
Dockmaster in Darkshore > boat to Stormwind City

NPC Aeria Goldenmoon

1. Line that reads  "boat to board" should have a period or other punctation at end
2. Line that reads "If it not here yet" should read similar to "If it **_is_** not here yet" or "If **_it's_** not here yet"

![a](https://user-images.githubusercontent.com/43530387/183798349-59409ddb-e6ed-4ca7-99b6-255771a51649.png)

**IDs of affected creatures, items, quests or spells with a link to the relevant page:**

NPC: https://database.turtle-wow.org/?npc=60621

**Comment by jameyboor** [comment]
Will be fixed on next update.
