### ISSUE TITLE
Priest lightwell can't be used by druid in cat/bear form

### ISSUE THREAD

**Issue by dole555** [slowtorta/turtlewow-bug-tracker#1880]
**Please, provide a clear description what the bug is:**
The priest lightwell can't be used by shapeshifted druids.
For it to be of use, shapeshifted druids should be able to click it.

**IDs of affected creatures, items, quests or spells with a link to the relevant page:**

Spell: https://database.turtle-wow.org/?spell=27871

**Expected behavior. Describe how it should work:**

**Comment by ratkosrb** [comment]
This is impossible to change, without making everything interactible in Bear Form. It's hardcoded in the client that gameobjects of type Spellcaster are not interactible in shapeshifts that forbid interactions.

**Comment by ratkosrb** [comment]
After consultations, it was decided not to make everything interactible in Bear Form, so this will remain as it is. You need to leave shapeshift to use the Lightwell.
