### ISSUE TITLE
honor rank reseted

### ISSUE THREAD

**Issue by agizangsu** [slowtorta/turtlewow-bug-tracker#1883]
**Please, provide a clear description what the bug is:**

**Steps to reproduce the behavior with as much detail as possible:**

1. ID : Hanoi
2. my honor rank reseted...
3. last week i was standing 30 in horde side. but my rank reseted 4 to 0

**IDs of affected creatures, items, quests or spells with a link to the relevant page:**

NPC: https://database.turtle-wow.org/?npc=
Item: https://database.turtle-wow.org/?item=
Quest: https://database.turtle-wow.org/?quest=
Spell: https://database.turtle-wow.org/?spell=
Object: https://database.turtle-wow.org/?object=

**Expected behavior. Describe how it should work:**

**Comment by slowtorta** [comment]
Related to https://github.com/slowtorta/turtlewow-bug-tracker/issues/1506
