### ISSUE TITLE
Demons in Ashenvale use the wrong models

### ISSUE THREAD

**Issue by adiosamigos** [slowtorta/turtlewow-bug-tracker#1885]
There are three types of demons next to the Warsong Lumber Camp in Ashenvale with a bunch of quests attached to them - succubi (Mannoroc Lashers), infernals (Searing Infrenals) and felguards (Felguards).
The thing is that most of them use the wrong models, e.g an Infernal may look (and be named) as a succubi and vice versa.

**Steps to reproduce the behavior with as much detail as possible:**

Just visit the location SW from Warsong Lumber Camp in Ashenvale and see it yourself.

**IDs of affected creatures, items, quests or spells with a link to the relevant page:**

NPC: https://database.turtle-wow.org/?npc=11697
NPC: https://database.turtle-wow.org/?npc=6073
NPC: https://database.turtle-wow.org/?npc=6115

**Expected behavior. Describe how it should work:**

All demons should use the correct models.

**Comment by slowtorta** [comment]
Couldn't find anyone with the wrong model, was probably fixed in one of the previous updates.
