### ISSUE TITLE
Item: Shadowruned Girdle

### ISSUE THREAD

**Issue by Milton3450** [slowtorta/turtlewow-bug-tracker#1887]
**Please, provide a clear description what the bug is:**
I think Devs made a mistake with this belt. The belt has, instead of "equip: increase in attack and cast speed", it has "use". Nothing happens when I right click on the belt, although it gives a 30 cd cooldown, like when u would equip a trinket. I think the intention was "equip" instead of "use".
**Steps to reproduce the behavior with as much detail as possible:**

1. Get Shadowruned Girdle
2.  Look at character info. Attack speed doesn't apply.

**IDs of affected creatures, items, quests or spells with a link to the relevant page:**

Item: https://database.turtle-wow.org/?item=60550

**Expected behavior. Describe how it should work:**
Probably "equip:" instead of a use effect.

**Comment by jameyboor** [comment]
Fixed on next update.
