### ISSUE TITLE
Arcane Missle bugged.

### ISSUE THREAD

**Issue by PaulGreenEyes** [slowtorta/turtlewow-bug-tracker#189]
Ever since the "update" to Arcane Missles that "fixed" the spell animation matching up with the channel bar the spell has been bugged due to the fact that it can no longer proc anything apart from Arcane Concentration on the cast itself.
To explain why this is a bug allow me to explain how Arcane Missles used to,and should,work:
                                   Arcane Missles prior to the 14.06.2021 update "• Arcane Missiles animation has been fixed and are now synced with damage hits.",used to have 6 different shots that would hit an enemy.The first one would be a "dry shot",the actual cast itself (that used to put you in combat but was later changed to not do so <3) which could proc Arcane Concentration and was the only part of the spell that could proc the Darkmoon Card:Blue Dragon effect.Following this "dry shot" was the actual 5 missles,the last of which would often times come AFTER the channel finished(hence the "fix").In practice though,this meant that the 5th missle would simply take the place of the "dry shot" of the next channel,if timed correctly,resulting in a constant stream of missles.Those 5 missles would be able to proc any and all effects that would trigger upon LANDING a spell,including stuff like Arcane Concentration and Blade of Eternal Darkness.It could also proc the tier 2 mage set bonus for the full set on each missle,despite it triggering upon "casting Arcane Missles".
                                  So in summery:Arcane Missles counted as 5 different spells united under one channel,for the purpose of procs that deal with casting and landing spells(this includes critical hits,misses and resists) but it is still only considered 1 "succesfull spell"(for the purpose of the Blue Card) because I assume that is tied to the spending mana(which you pay the full ammount upon cast.You don't get a refund of mana if you only channel for 2 missles).

--"But that's how it's on classic"--

While the devs for Classic WoW did an amazing job shaping the modern wow client into what we now know as Classic WoW,the truth of the matter is that it is just a butchered version of the modern client.
In Retail,Arcane Missles is a machinegun that is affected by cast speed alterations and the only part of the actual spell that can proc anything(including critical hits) is the cast itself.This sadly has translated into Classic WoW with the result being this broken version of Arcane Missles that we sadly now have on our server.

I must stress that each missle CAN still critically hit,miss and get resisted INDEPENDENTLY.Not only that,but each missle CAN still proc the Wrath of Cenarius ring effect.And if each missle is still considered a different instance of spell HIT,it should still proc the effects that it used to be able to.

https://classic.wowhead.com/spell=12577/arcane-concentration#modifies 

/\ (Clearly states "after any damage spell hits a target",NOT "upon a succesfull spellcast")

https://database.turtle-wow.org/?item=21190

/\(It can still proc this item on each missle) (Though to be fair,this thing can proc on wand hits so hey)

https://database.turtle-wow.org/?item=17780

/\(Cannot proc this anymore,at all)

https://database.turtle-wow.org/?spell=22007

/\(Confirmed to not be able to proc it anymore despite being able to before the update)

https://classic.wowhead.com/item=19288/darkmoon-card-blue-dragon

/\(Only procs on the cast itself,unchanged)

------------------------------------------------------------------------------------------------------------

All I'm asking is to simply revert whatever changes were made with the 14/06/2021 update "• Arcane Missiles animation has been fixed and are now synced with damage hits." and simply leave it as it used to be, "bugged animation" and everything.It worked fine,it was fun to play with and Classic is simply wrong on this one.

pls help <3

**Comment by ttdgrin** [comment]
arcane missile still broken, has yet to be fixed.
it wont prock things like Clearcasting during the channeling, only on the initial cast

**Comment by slowtorta** [comment]
Animation fix was reverted. Should work as it worked previously now, please check again after the next server restart.
