### ISSUE TITLE
Master Conjurer Warlock talent does not increase HS effect

### ISSUE THREAD

**Issue by Frenique** [slowtorta/turtlewow-bug-tracker#1890]
Master Conjurer Warlock talent does not increase HS effect. When used healthstone has no increased effect and tooltip doesnt change either. Dont know if it works for the firestones and spellstones.

1. Taken both rank 1 and 2 master conjurer does not increase HS.
2. Used it to check if tooltip was wrong.
3. Even tried after deleting WDB folder.

https://database.turtle-wow.org/?item=5512
https://database.turtle-wow.org/?item=5511

Increase health from healthstone rank 1 talent 10%, rank 2 20%. (also effect of firestone and spellstone with 30%, dont know if that works)

**Comment by SolarGuru** [comment]
Effect of HS is determined when it is created, so you need to have the talents before creating HS. But this doesn't work with HSs from "Table" spell, I guess.
