### ISSUE TITLE
Aspect of the Cheetah Daze from Shadow Word: Pain Initial Cast

### ISSUE THREAD

**Issue by dontwakedad** [slowtorta/turtlewow-bug-tracker#1895]
**Please, provide a clear description what the bug is:**

**Steps to reproduce the behavior with as much detail as possible:**

1. Cast Aspect of the Cheetah on Hunter
2. Priest cast Shadow Word: Pain on the Hunter
3. Initial Cast acts as direct damage and causes hunter to be dazed
EDIT:
All DoTs are causing daze... Curse Of Agony, Corruption, etc 
**IDs of affected creatures, items, quests or spells with a link to the relevant page:**

Spell: https://database.turtle-wow.org/?spell=589
Spell: https://database.turtle-wow.org/?spell=5118
Spell: https://database.turtle-wow.org/?spell=172
Spell: https://database.turtle-wow.org/?spell=980

**Expected behavior. Describe how it should work:**
Initial cast from the Shadow Word: Pain or following damage over time from spell should not cause daze effect, only direct damage.

**Comment by SabineWren** [comment]
Pretty breaking in PvP.

**Comment by adiosamigos** [comment]
+1  literally unplayable for hunters vs warlocks/priests, need to be fixed ASAP

**Comment by D4nSch** [comment]
Bump! Really takes the fun of Hunter PvP!

**Comment by adiosamigos** [comment]
this bug puts hunters at big disadvantage and breaks the classic playstyle, please fix ASAP
