### ISSUE TITLE
Acidently sold my weapon to vendor

### ISSUE THREAD

**Issue by LachtanCesky** [slowtorta/turtlewow-bug-tracker#1897]
**Please, provide a clear description what the bug is:**
As title says, I accidently sold my weapon to a vendor when I was "testing" some other weapon. Unfortunatelly I've found out of it the next day and I'd like to have it back if possible.
Character: Nitakurak, lvl45 (Horde)

**IDs of affected creatures, items, quests or spells with a link to the relevant page:**
Item: https://database.turtle-wow.org/?item=10823

**Comment by geojak** [comment]
Make a ticket in game and close this
