### ISSUE TITLE
Wastewander Bandits/Thieves "actually" reward Steamwheedle Reputation (hidden faction?) on death

### ISSUE THREAD

**Issue by lokhengchau** [slowtorta/turtlewow-bug-tracker#1899]
I did a search in the bug list and found a previous reported issue where killing wastewander mobs in tanaris do not actually reward steamwheedle rep [(link)](https://github.com/slowtorta/turtlewow-bug-tracker/issues/1363). The issue has been marked as closed but I can confirm that it's still not working as intended. I am not getting reps for the four factions (Booty Bay, Everlook, etc..), but instead, I'm actually getting reps for "steamwheedle cartel".

![image](https://user-images.githubusercontent.com/37974241/184273578-1a2773e0-de35-421f-a117-b09c3fe19b61.png)

I'm using pfui and at lvl 60, the xp bar will show the faction rep whenever I earn rep. I'm confused what this faction is. I'm getting rep for this instead of the four factions.

I've noticed similar issues with quests that reward alliance rep. Instead of giving rep to the 5 alliance factions, it gives rep to a faction called "alliance".

**Steps to reproduce the behavior with as much detail as possible:**

1. Check Steamwheedle Cartel reps (mouse over each)
2. Kill Wastewander mob in Waterspring Field Tanaris
3. Notice no actual change in reputation

**IDs of affected creatures, items, quests or spells with a link to the relevant page:**

NPC: https://database.turtle-wow.org/?npc=5616
https://database.turtle-wow.org/?npc=5623

**Expected behavior. Describe how it should work:**
After killing these mobs, each of the Steamwheedle Cartel reputations should increase, not the Stemwheedle Cartel faction.

**Comment by slowtorta** [comment]
Related to for https://github.com/slowtorta/turtlewow-bug-tracker/issues/2147
