### ISSUE TITLE
Mobs Disappearing During Raid

### ISSUE THREAD

**Issue by hazlema** [slowtorta/turtlewow-bug-tracker#19]
By opening this Issue, I admit to having done the pertinent research using sources from Vanilla (preferably) or Classic. I also understand that sources from other private servers are not acceptable.

**Current behavior**: 
When raiding BWL today, we were on the second boss (Vaelastrasz the Corrupt)  I got the Burning Adrenaline and after I died the boss vanished from my view but the boss fight was still going on.  Seems this only happened to me as no one else saw this..  On subsequent attempts it behaved normally.

**Expected behavior**: 
Boss should not disappear

**Proofs**:
https://ibb.co/j8pGBwG

**Steps to reproduce**:

1.  Not sure how to reliably reproduce.

**Comment by Nolin7777** [comment]
Dev Note: Maybe client related?
