### ISSUE TITLE
Text for imperial plate shows incorrect requirements

### ISSUE THREAD

**Issue by BowtiesAreCool** [slowtorta/turtlewow-bug-tracker#190]
The quests for the Imperial Plate set from Derotain Mudsipper in Gadgetzan have incorrect text. They are showing half the amount of thorium bars that is actually required for each hand in. This affects all the quests, IDs 7563 - 7569.

Steps to reproduce:
1. Accept any of the imperial plate quests from the NPC.
2. Review the quest text vs. required items and note the discrepancy.

Quests affected:

- https://database.turtle-wow.org/?quest=7653
- https://database.turtle-wow.org/?quest=7654
- https://database.turtle-wow.org/?quest=7655
- https://database.turtle-wow.org/?quest=7656
- https://database.turtle-wow.org/?quest=7657
- https://database.turtle-wow.org/?quest=7658
- https://database.turtle-wow.org/?quest=7659

Expected behaviour:
- Quest text matches required items for each quest.

![imperial-plate-text](https://user-images.githubusercontent.com/46679133/126872597-4d6ee214-8bed-4458-8834-f5d72101faae.png)

**Comment by slowtorta** [comment]
Thanks for reporting it. It'll be fixed on the next server restart. Make sure to clear your WDB folder.
