### ISSUE TITLE
Grifter's Leggings

### ISSUE THREAD

**Issue by Stianh16** [slowtorta/turtlewow-bug-tracker#1902]
**Please, provide a clear description what the bug is:**

Grifter's Leggings are shown as a different item in the Leatherworking proffesion tab and aren't recognized as part of the set by the game, thus equipping it won't give the set bonus.

**Steps to reproduce the behavior with as much detail as possible:**

1. Open Leatherworking window, search for Grifter's Leggings in the "Plate" tab
 
![image](https://user-images.githubusercontent.com/111102049/184278556-ca75bb2b-5893-4245-b3ca-d2e7795eab42.png)
![image](https://user-images.githubusercontent.com/111102049/184278612-e72f732d-3331-4199-a43a-25de7e215278.png)
2. After crafting it and contacting a GM, the item was swiftly changed, but the referenced pants do not show as part of the set  & do not provide the bonus as it shows in the following images.
![image](https://user-images.githubusercontent.com/111102049/184278746-d3f1619a-545a-44d2-a5a9-3d7ad6b441ea.png)
![image](https://user-images.githubusercontent.com/111102049/184279026-dca62d49-7702-4630-b51f-de3500904725.png)

**IDs of affected creatures, items, quests or spells with a link to the relevant page:**
Items:
https://database.turtle-wow.org/?item=83252
or (they are the same, database shows them both though)
https://database.turtle-wow.org/?item=83402
The "Steel Plate Legguards" that shows instead of "Grifter's Leggings" in the Leatherworking window
https://database.turtle-wow.org/?item=83412

**Expected behavior. Describe how it should work:**
"Grifter's Leggings" should show in the Leather tab, after having it crafted it should provide with the correct item either "83252" or "83402"  instead of "83412" and finally, it should be recognized as part of the set.

**Comment by slowtorta** [comment]
This has been fixed,  yet not deployed to the main server. https://github.com/slowtorta/turtlewow-bug-tracker/issues/1671
