### ISSUE TITLE
Mining nodes under terrain - Mulgore

### ISSUE THREAD

**Issue by None-Above** [slowtorta/turtlewow-bug-tracker#1908]
**Please, provide a clear description of what the bug is:**
Several mining nodes under terrain in mulgore
Coordinates:
60.5/31.5
56.6/15.7
56.9/16
**Expected behaviour. Describe how it should work:**
Nodes on the surface.
![image](https://user-images.githubusercontent.com/111132789/184366207-4346cba7-3312-4110-bff2-f48722416671.png)
![image](https://user-images.githubusercontent.com/111132789/184366318-16d4d775-bcfd-47cb-98e4-e2c5b65c2ecc.png)
![image](https://user-images.githubusercontent.com/111132789/184419415-5f0e9c2e-bfe8-4c44-8e2a-9d2087876963.png)
![image](https://user-images.githubusercontent.com/111132789/184426276-e6137b61-40d8-41e6-9138-374bf97526c1.png)

**Comment by None-Above** [comment]
Notes tracked on minimap.

**Comment by sosa1996** [comment]
you can find the same thing in Arathi Highlands some nodes are underground

**Comment by None-Above** [comment]
> you can find the same thing in Arathi Highlands some nodes are underground

I think it would be most effective to report each zone individually.

**Comment by None-Above** [comment]
There's also mob under terrain at 56.9/16
