### ISSUE TITLE
Multiple Mages cannot cast Arcane Missiles.

### ISSUE THREAD

**Issue by OonaFae** [slowtorta/turtlewow-bug-tracker#1910]
**Please, provide a clear description what the bug is:**
When a mage is channeling Arcane Missiles on an enemy if another mage begins to channel arcane missiles, the first mages will be cancelled. See below video.

https://youtu.be/yFuaOWKEjXM

**Steps to reproduce the behavior with as much detail as possible:**

1. Begin Casting Arcane Missiles
2. Have another mage start casting Arcane Missiles shortly after
3.  The first mages missiles will be cancelled and the seconds will continue on.

**IDs of affected creatures, items, quests or spells with a link to the relevant page:**

Tested with several higher ranks of missiles, all behave the same

**Expected behavior. Describe how it should work:**

Neither Arcane Missiles channel should be cancelled.

**Comment by makujah** [comment]
Just wanted to make the same ticket, but you've presented it better than I would have :D 

Definitely a gamebreaking bug, can't do dungeons with other arcanes

**Comment by eX1stenZT** [comment]
Haven't had 2 arcane in a group yet but if this is the case, that's a blocker for a spec.

**Comment by makujah** [comment]
> Haven't had 2 arcane in a group yet but if this is the case, that's a blocker for a spec.

you just get a single one arcane in your entire raid for the main caster group or healer group for that brilliance aura and that's it XD

Nah, hopefully it's gonna get fixed soon :)

**Comment by geojak** [comment]
Maybe can even fix last arcane missile coming when channeling is already finished finally pls

**Comment by Megamagepal** [comment]
this spell has been extremely busted for years, it needs fixing badly, playing arcane mage feels so bad

**Comment by redmagejoe** [comment]
This bug needs to be escalated to a higher priority given that it completely breaks fundamental gameplay mechanics, with a severe impact on a specific class's capabilities.

**Comment by ratkosrb** [comment]
It should be fixed after the next update. The issue only happened when two people are using different ranks btw.
