### ISSUE TITLE
Druid: Travel Form mana cost is 32% base mana instead of 20%

### ISSUE THREAD

**Issue by Testerrosaurus** [slowtorta/turtlewow-bug-tracker#1912]
**Please, provide a clear description what the bug is:**

Druid's Travel Form and Aquatic Form cost around 32% base mana instead of 20%.

On my level 40 druid Travel Form and Aquatic Form cost about 170 mana, Cat Form and Bear Form cost about 290 mana.

Given that Cat Form and Bear Form cost 55% base mana (https://database.turtle-wow.org/?spell=768) - my base mana is 290/0.55~=527, so 170/527~=0.32 which means that Travel Form and Aquatic Form cost ~32% base mana.

I don't have level 60 druid to check, but i'm pretty sure it's also wrong on level 60 and costs around 320 mana instead of 200 (lvl 60 druid should have around 1000 base mana, so it should be around 550 mana for Bear/Cat Form and around 200 mana for Travel/Aquatic Form).

That 200 vs 320 mana difference is very significant when Travel Form is being spammed/used very often.

Other vanilla-wow databases also show 55% base mana for Bear/Cat Form and 20% base mana for Travel/Aquatic Form.

**Steps to reproduce the behavior with as much detail as possible:**
1. Log on to a lvl 30+ druid and check Travel Form mana cost and check the ratio "[Travel Form mana cost]/([Bear Form mana cost]/0.55)", it should be ~0.2 but now it actually is ~0.32.
2. Log on to a lvl 60 druid without "Natural Shapeshifter" talent and check Travel Form mana cost, it should be around 200 mana, but it probably is around 320 mana.

**IDs of affected creatures, items, quests or spells with a link to the relevant page:**
Spell: https://database.turtle-wow.org/?spell=783
Spell: https://database.turtle-wow.org/?spell=1066

**Expected behavior. Describe how it should work:**
Travel Form and Aquatic Form should cost 20% base mana (which is around 200 mana on level 60 druid and around 110 mana on level 40 druid).

**Comment by Platinumcoated** [comment]
Turtle WoW discord - druid channel:

Moon — 26/07/2022
"mana cost for transformations were baseline made their burning crusade values"
[https://discord.com/channels/466622455805378571/810850778838990859/1001276083238359060](link to message)

Bear form mana cost has been reduced from 55% of base mana to 35% base mana in 1.16.1

**Comment by Testerrosaurus** [comment]
> Turtle WoW discord - druid channel:
> 
> Moon — 26/07/2022 "mana cost for transformations were baseline made their burning crusade values" [link to message](https://discord.com/channels/466622455805378571/810850778838990859/1001276083238359060)
> 
> Bear form mana cost has been reduced from 55% of base mana to 35% base mana in 1.16.1

Ok, then Travel Form would be 20% indeed, but then it seems that by changing Bear Form and Cat Form mana cost from 55% to 35% but leaving other spells base mana cost unchanged - other spells may now cost significantly more than they should. Given that on TBC Bear Form costs 35% base mana and Travel Form costs 13% base mana - it seems exactly like it is the case.

I already made a report #1924 for Swiftmend mana cost also based on vanilla-base-mana-values and Bear Form base mana, but it seems Swiftmend mana cost was adjusted on turtle-wow to 16% like in TBC instead of 20% so swiftmend is not bugged.
But Travel Form is still 20% but is 13% on TBC. So Travel Form mana cost is still bugged and is too high, it should be 13%.

And also - absence of a complete list of custom changes on web-site/forum or in database makes it very confusing.
It would be nice have at least something like https://forum.turtle-wow.org/viewtopic.php?t=3334 but with all changes (some changes including "Bear form mana cost has been reduced from 55% of base mana to 35% base mana in 1.16.1" is missing there, new ability Savage Bite description is also missing there) and/or adjust database.turtle-wow.org accordingly.

**Comment by Testerrosaurus** [comment]
> but then it seems that by changing Bear Form and Cat Form mana cost from 55% to 35% but leaving other spells base mana cost unchanged - other spells may now cost significantly more than they should.

Yes, indeed, besides Travel Form and Aquatic Form (20% to 13%) also not adjusted to tbc values:
Barkskin (15% to 12%)
Innervate (5% to 4%)
Rebirth (85% to 68%)
Abolish Poison (16% to 13%)
Cure Poison (16% to 13%)
Remove Curse (10% to 8%)

And all of them now cost more in absolute mana values than they should because base mana values for characters is higher.

**Comment by ratkosrb** [comment]
I have reduced the mana cost percent of Travel Form and Aquatic Form to 13% like you wanted, but it will still display the old amount on the tooltip until a new client patch is released, as this requires a change in Spell.dbc in the client files.
