### ISSUE TITLE
Running Animation Sometimes Continues When Entering or Exiting a Druid Form

### ISSUE THREAD

**Issue by Jdavidlol** [slowtorta/turtlewow-bug-tracker#1913]
**What the bug is: As a druid (and possibly Shaman) your running animation gets locked in place from time to time.**

**Steps to reproduce the behavior with as much detail as possible:**

1. Play as Druid (or Shaman)
2.  Use travel form repeatedly (or Ghost wolf)
3.  Occasionally (every few minutes) your characters running animation will continue after leaving or entering a form.

**Expected behavior. Describe how it should work: When I stop pressing W or S and shift in and out of form the animation should stop. I have a feeling this animation issue could be something network related but I KNOW I am not the only person who has experienced it. It does resemble when you see another player DC, except it is happening to you.. and it seems despite my ping. I am not sure if it is possible to fix but I wanted to suggest it because it is pretty jarring when it happens a lot... and for me, it does as I am Feral. **

**Comment by slowtorta** [comment]
I'm sorry, but this is the original Vanilla client bug, which is impossible to fix without a client source code (the one from Blizzard Entertainment).
