### ISSUE TITLE
Automatic use of healing potions

### ISSUE THREAD

**Issue by Taiyosama8** [slowtorta/turtlewow-bug-tracker#1915]
During combat, my character always uses a healing potion automatically. I don't press the button. It started after I learned the "Flourish" ability. Do something, otherwise I will lose the opportunity to use the potion when it is really necessary.

My charecter is hardcore, names Kaithyr.

**Comment by slowtorta** [comment]
Do you have any addons installed?

**Comment by Taiyosama8** [comment]
pfUI addon installed, cartographer and atlas loot

**Comment by slowtorta** [comment]
This isn't a server-side bug, I'm sorry. Try to disable your addons and see if it persits.
