### ISSUE TITLE
Quest - Redemption in EPL

### ISSUE THREAD

**Issue by GarBear121** [slowtorta/turtlewow-bug-tracker#1919]
**Please, provide a clear description what the bug is:**
Quest 'Redemption' in Eastern Plaguelands
Quest is not able to be completed. Player finishes the 3 sets of quests killing bats, dogs and grubs and the subsequent quest is one where you listen to an NPC talk and he has no text, so the quest is not able to be completed.

**Steps to reproduce the behavior with as much detail as possible:**

1. Obtain quest - Redemption
2.  NPC has no text to display to "listen to"
3.  Talk to NPC and cannot complete quest or any other action

**IDs of affected creatures, items, quests or spells with a link to the relevant page:**

NPC: https://database.turtle-wow.org/?npc=1855
Quest: https://database.turtle-wow.org/?quest=5742

**Expected behavior. Describe how it should work:**
Quest text should appear, or at least the timer for the script to allow player to finish quest.

**Comment by GarBear121** [comment]
using wrong action to complete quest

**Comment by Tinyfin-github** [comment]
Greetings!

Please /sit then open the dialogue window.

You need to perform the action indicated in the quest text.
