### ISSUE TITLE
Ony/nefa buff is not working on my char

### ISSUE THREAD

**Issue by Prestelame** [slowtorta/turtlewow-bug-tracker#1920]
Greetings, MJ response to my ticket told me to post here. 

Stormwind got 3 times a buff when I was here : https://classic.wowhead.com/spell=22888/rallying-cry-of-the-dragonslayer

Unfortunately, everyone got this buff when it pops excepted for me. First time I was thinking I had a chronoboon or something, but no. I have a chronoboon on my bag but there's not ony buff. I don't really know what to do, if I did a mistake or something so I post my screen here hoping that you can resolve the problem. 

https://www.hosting-images.net/image/proof.nTzN

Thanks !

**Comment by jimmychonga69** [comment]
I have the same problem on three horde characters when I'm in orgrimmar or crossroads. Is there a reputation requirement?

**Comment by slowtorta** [comment]
This was fixed a while ago.
