### ISSUE TITLE
Firemaw, Ebonroc and Flamegor dropping only 1 item

### ISSUE THREAD

**Issue by Lexiebean** [slowtorta/turtlewow-bug-tracker#1925]
They don't ALWAYS drop only 1 item, but more often than not they're only dropping one.

IIRC they should always be dropping 2 items.

Some random old videos show 2 items.
https://youtu.be/usLhstoYxgU?t=119
https://youtu.be/BBapW_mBLeE?t=83

Firemaw: https://database.turtle-wow.org/?npc=11983
Ebonroc: https://database.turtle-wow.org/?npc=14601
Flamegor: https://database.turtle-wow.org/?npc=11981

**Comment by OonaFae** [comment]
Updating here, we ran BWL tonight and had Flamegor only drop one itme, please investigate further.

**Comment by ratkosrb** [comment]
When an issue is closed it does not mean the update is applied to the live server. It means it's been fixed internally, and will be live some time in the future.
