### ISSUE TITLE
Warlock's Master conjurer talent doesn't work; Wyvern companion apsent

### ISSUE THREAD

**Issue by Tyrannos37** [slowtorta/turtlewow-bug-tracker#1928]
**Please, provide a clear description what the bug is:**

So I have two issues:

1) I have a 21 lvl HC warlock with a Master conjurer talent up 2(HealthStones created have 20% more points). When I played before it was working and I was creating little HSs with 120 hp, 4 days ago when I entered the game I tried to do this but the HS I created has 100 hp only like a bassic one without a talent and till now the talent doesn't work and I can not create Stones with additional 20% hit points.  
HC warlocks I asked about this issue said that they don't have this issue.

2) Not so long ago in mulgore were added some new quests that allow to get a reward -  a wyvern companion. I got it with my hc Shaman, activating the egg and the wyvern companion was added to my library(spell book page). So I can call it whenever I want...
When I made these quests with my hc warlock 4 days ago I got the egg, but When I activate it instead to add a companion to my library it was called and appear close to me so when I pick the other companion the wyvern one dissapear. And I have never seen it again.

\
**IDs of affected creatures, items, quests or spells with a link to the relevant page:**

NPC: https://database.turtle-wow.org/?npc=
Item: https://database.turtle-wow.org/?item=
Quest: https://database.turtle-wow.org/?quest= new mulgore quest to aquiare a wyvern companion
Spell: https://database.turtle-wow.org/?spell= create a little healthstone
Object: https://database.turtle-wow.org/?object= 

**Expected behavior. Describe how it should work:**
1) The stones I create as my hc Warlock have 20% more hitpoints
2) I get a wyvern companion in my library

**Comment by slowtorta** [comment]
To restore your companion, please submit a ticket in-game.
