### ISSUE TITLE
Can't open chest in Loch Modan. Out of line of sight error.

### ISSUE THREAD

**Issue by SierraNairn** [slowtorta/turtlewow-bug-tracker#193]
Can't open chest in Loch Modan. Out of line of sight error.
Location:

![WoW_lip4FyjgLJ](https://user-images.githubusercontent.com/83077166/126994184-0debd046-2b25-4368-91d5-e5ab28af61b7.png)

![WoW_BDZWrk2puK](https://user-images.githubusercontent.com/83077166/126994211-a397886f-cc7f-4b7f-bb9c-93b9bbf32f91.png)

**Comment by slowtorta** [comment]
Thanks for reporting it. It'll be fixed on the next server restart. Make sure to clear your WDB folder.
