### ISSUE TITLE
Voidwalker AoE taunt: Suffering not breaking enemy rogues out of stealth 1.16.3

### ISSUE THREAD

**Issue by tocopherylacetate** [slowtorta/turtlewow-bug-tracker#1930]
**Please, provide a clear description what the bug is:**
Voidwalker AoE taunt: Suffering not breaking enemy rogues out of stealth, should work like piercing howl that warriors have

**Steps to reproduce the behavior with as much detail as possible:**

1. Duel a rogue, any rogue and have him stealth
2. Have voidlwalker cast suffering
3. Notice it doesnt break rogues out of stealth
4. Die to the rogue because LAP was on cd

**IDs of affected creatures, items, quests or spells with a link to the relevant page:**

https://database.turtle-wow.org/?spell=17752
https://database.turtle-wow.org/?spell=17751
https://database.turtle-wow.org/?spell=17750
https://database.turtle-wow.org/?spell=17735

**Expected behavior. Describe how it should work:**
The 2 minute spell suffering should break rogues out of stealth

**Comment by Giperion** [comment]
@tocopherylacetate Why you think that this ability should break stealth?
This is not the same as "piercing howl". They different in many aspects. "Suffering" only generated threat, and not causing any other effects, while "Piercing Howl" affecting speed, which is technically a debuff. Suffering can't even affect players, technically.

**Comment by Giperion** [comment]
If you have proof that it certainly should break enemy stealth - please provide it to us. But for now - we closing this issue.
