### ISSUE TITLE
Paladin Reckoning talent not proccing

### ISSUE THREAD

**Issue by zulnam** [slowtorta/turtlewow-bug-tracker#1932]
**Please, provide a clear description what the bug is:**
The Reckoning talent for paladin does not proc when crit 4 times.

**Steps to reproduce the behavior with as much detail as possible:**
Prerequisites:
Reckoning talent (protection) - 5/5.

1.Find a mob close to your level or higher.
2.Let it crit you 4 times.
3.Attack the mob.

**IDs of affected creatures, items, quests or spells with a link to the relevant page:**
N/A (Reckoning not present in DB)

**Expected behavior. Describe how it should work:**
When crit 4 times in a row, reckoning should unload 4 attacks that can proc seals (in accordance to vanilla/classic).

**Comment by ratkosrb** [comment]
I can't reproduce the issue. I can get 4 extra attacks at once.
![WoWScrnShot_081522_115833](https://user-images.githubusercontent.com/35845488/184607417-847d5966-2f88-4bd6-842f-077805e03583.jpg)

**Comment by zulnam** [comment]
will try to reproduce with screenshot

**Comment by ratkosrb** [comment]
Don't see how WDB can be related. Maybe try resetting your talents and picking up Reckoning again. Also make sure you are not deselecting your target while auto attack is on or cancelling your auto attack, cause that can clear reckoning charges.

**Comment by zulnam** [comment]
Can't reproduce.
