### ISSUE TITLE
Black Diamond sell price

### ISSUE THREAD

**Issue by thp1990** [slowtorta/turtlewow-bug-tracker#1934]
According to [Patch 1.16.1 — Class changes and more!](https://forum.turtle-wow.org/viewtopic.php?f=2&t=3334)

Added 1 Silver sell price to Black Diamond.

https://database.turtle-wow.org/?item=11754

But at the moment, Black Diamond still has "no sell price".

**Comment by geojak** [comment]
I have sold countless of black diamonds for 1s. Are you sure it's not just a, dB error?

**Comment by slowtorta** [comment]
Please clear your WDB folder and it'll display correctly :)

**Comment by thp1990** [comment]
![Black Diamond](https://user-images.githubusercontent.com/109424879/184618947-f5d0d427-fb35-4e7d-926f-34f6c6981e56.jpg)

**Comment by thp1990** [comment]
> Please clear your WDB folder and it'll display correctly :)

Yes I have already clear WDB.
