### ISSUE TITLE
Whirlwind Shredders & Burning Blade Adepts ( Desolace ) don't leash and teleport-chase indefinitely; glitching around.

### ISSUE THREAD

**Issue by prev1234** [slowtorta/turtlewow-bug-tracker#1935]
Whirlwind Shredders & Burning Blade Casters ( Desolace ) fail to leash correctly and teleport behind the player until they die.
— I'm surprised that it hasn't been posted here. It's been killing a lot of HC players and managed to get me too when I knew.
— It's, I think, very significant / disruptive and basically compromises an entire or most of a zone. That being "Desolace."

***Steps to reproduce the behavior with as much detail as possible***:

1. Enter Desolace with rumors circulating about bugged wind / air elementals.
2. Approach the zone's center from any direction, below the northern-middle ridge.
3. Notice the Whirlwind Shredder(s), air elementals that can / might be seen glitching around the area.
4. Attempt to pass through the area, even giving them a ridiculous distance compared to other mobs.
5. Notice that their effecting aggro radius is exponentially larger because of their tendency to glitch / teleport around.
6. Instead of approaching the player, they teleport to the player instantly. There are (3) or more of them.
7. Strangely, Burning Blade Adepts also aggro and teleport to the player from seemingly nowhere / VERY far away.
8. Now that the player, sometimes hardcore, is fighting (3) or more elementals and possibly orc casters, they'll likely run.
9. While the Whirlwind Shredders ARE faster than a player with 108% speed, they will also not effectively leash / disengage.
10. When the player has run a set distance, they turn away but re-aggro and teleport back to the player.
11. Unless the player manages to kill everything involved, which is exceedingly difficult, they'll successfully attack the player indefinitely.
12. Almost always results in a death sentence for the player unless they're somehow all killed or maybe vanish / feign.
13. It's worth noting that it functioned as a sort of "trap," that the mobs spring on an unsuspecting player; it's like a sequence.

**NOTE** — the character WAS level 37 at the time, paladin

**IDs of affected creatures, items, quests or spells with a link to the relevant page:**

***Whirlwind Shredder***: https://database.turtle-wow.org/?npc=11578
***Burning Blade Adept***: https://database.turtle-wow.org/?npc=4665

"*Yes, Officer, it was these guys right here.*"

**NOTE** — elementals were visibly glitching around in the area north of kodo graveyard
**NOTE** — orc adepts were teleporting from an unknown location ( someone said under the map / terrain )
**NOTE** — it's supposedly happening in areas of central desolace, and makes the quests in central desolace extremely dangerous

**Expected behavior. Describe how it should work:**

If you go anywhere near ( ridiculous range ) these things or really even just central desolace, they'll proceed to teleport to the player upon aggro and every time the leash resets. Each time they "leash," they turn and teleport back to combat with the player until the player kills the teleporting stampede or until they die. Almost everyone dies because if you continue running away, they'll follow you indefinitely. And, they teleport to you and deliver attacks regardless of what you do or however fast you are. Was able to have one successfully leash / disengage after damaging it significantly. However, they just overwhelm you because there are too many.

As someone who just died excruciatingly to this, I hope that my firsthand account of it will provide sufficient information / detail.
Respect to the Turtle WoW team for this awesome server and project. Ran into this and was suggested to post about it here.

**Comment by ratkosrb** [comment]
I can't reproduce the issues you are having. They don't teleport around, and they evade properly. However I'll add a forced 30 yard leash, so they will evade if they go beyond that distance no matter what.
