### ISSUE TITLE
Different item stats (cleared WDB)

### ISSUE THREAD

**Issue by thp1990** [slowtorta/turtlewow-bug-tracker#1936]
This in-game cloak vs the one on the website [Kirin Tor Shawl of Authority
](https://database.turtle-wow.org/?item=60647) are very different.
![Kirin Tor Shawl](https://user-images.githubusercontent.com/109424879/184630056-6c4b85a0-4a37-4dfe-8df7-c7b29c1ce745.jpg)

**Comment by slowtorta** [comment]
This is the general website bug, we're looking into it :)

**Comment by slowtorta** [comment]
Fixed now.
