### ISSUE TITLE
Hakkari Breastplate has no level requirement

### ISSUE THREAD

**Issue by terraform123** [slowtorta/turtlewow-bug-tracker#1937]
**Please, provide a clear description what the bug is:**

[Hakkari Breastplate](https://database.turtle-wow.org/?item=10781) drops from lvl 49-50 elite mobs but is BoE and has no level requirement.

**Steps to reproduce the behavior with as much detail as possible:**

1. Obtain Hakkari Breastplate
2. Can be equipped by level 1 characters.

**IDs of affected creatures, items, quests or spells with a link to the relevant page:**

Item: https://database.turtle-wow.org/?item=10781

**Expected behavior. Describe how it should work:**

Item should have level requirement (~lvl 45?)

**Comment by ratkosrb** [comment]
It's BoP not BoE. It can't be traded.

**Comment by vkekd** [comment]
https://classic.wowhead.com/item=10781/hakkari-breastplate
One minute search can answer your question. The item never had level requirement.

**Comment by terraform123** [comment]
@ratkosrb It'd indeed BoE, sorry my honest mistake.

It's strange that it's supposed to have level requirement, because this character is level 10 and has it equipped: https://armory.turtle-wow.org/#!/character/Gatemaster

**Comment by jameyboor** [comment]
We'll take it into consideration.

**Comment by Twili1** [comment]
There is no bug with the level requirement. The item never had a level requirement in vanilla as it’s gated behind a quest with a level requirement. Probably the source is the issue, database says it drops from ST mobs, which probably shouldn’t be the case

**Comment by Zebouski** [comment]
> Overall this is pretty low hanging fruit though. A twink even without this item will still kill just about any other player within a certain level range of them. Saying this from a point of neutrality, but i'd rather not set the precedent of players using the staff as their personal attack dog just because someone over-geared killed them in low level world pvp

It's a bug. it should be fixed to be blizzlike where it isn't obtainable by anyone sub 40. this has nothing to do with any spite
