### ISSUE TITLE
[Quest] Helcular's Revenge problem since update

### ISSUE THREAD

**Issue by Darcisselock** [slowtorta/turtlewow-bug-tracker#1938]
Hi, this is not so much a bug report as a feedback, as it is a custom change done on purpose. Still, it interferes with the gameplay and is not blizz-like, so I hope the staff considers modifying it.
Town guards received an increase in power in order to help protect from gankers with the new patch, which is very welcome, however, in remote towns, the primary victims seem to be low levels that suffer a higher aggro range from the now lvl 60 guards (and also get 1-2shot by them).

On this specific quest, in order to hand in, Horde players must wander into the Southshore graveyard. There are some guards near the quest objective, which made it a risky endeavor already with the regular guard levels, but now the player requires even higher level (possibly 43-44, for a lvl 33 quest) to hand it in with care, and an accidental aggro means guaranteed death with the increased guard power.
There are probably other quests which are interfered with in a similar manner, however this is the most spectacular as hardcore players regularly die there.

**Steps to reproduce the behavior with as much detail as possible:**

1. Approach Southshore graveyard as a lvl appropriate (35-36) character
2. Try not to aggro the guards
3. Run away before they kill you

**IDs of affected creatures, items, quests or spells with a link to the relevant page:**

NPC: https://database.turtle-wow.org/?npc=2386
Quest: https://database.turtle-wow.org/?quest=553

**Expected behavior. Describe how it should work:**

These guards should remain level 55 with their original damage values. Nobody is ganking in Southshore anyway.

**Comment by ratkosrb** [comment]
This will be improved in the next update. Guard aggro distance will be lower against players that are not flagged for PvP.
