### ISSUE TITLE
Horde has another GY in Hinterlands

### ISSUE THREAD

**Issue by Kerebrien** [slowtorta/turtlewow-bug-tracker#1939]
**Please, provide a clear description what the bug is:**
Originally, Horde are supposed to only have one graveyard in the Hinterlands - the one near their town at the east coast.

**Steps to reproduce the behavior with as much detail as possible:**

1. Die as Horde near Aerie Peak.

**IDs of affected creatures, items, quests or spells with a link to the relevant page:**

-

**Expected behavior. Describe how it should work:**

Horde are supposed to only have the graveyard at the east coast.

**Comment by Daribon** [comment]
This is correct behavior.

Hinterlands had only had one graveyard until 1.6.0 and that's why the Aerie Peaks graveyard is neutral.
