### ISSUE TITLE
Field Duty Papers event  for alliance bugged.

### ISSUE THREAD

**Issue by Tinyfin-github** [slowtorta/turtlewow-bug-tracker#194]
How it should work :
Go to  Windcaller Kaldon  get the field duty quest : 
 Go to  Captain Blackanvil   and  a Hive'Zora Abomination  get's summoned
 Kil it, talk to Captain Blackanvil  get your papers signed and return to  Windcaller Kaldon.

 
 What does not work:
 Hive'Zora Abomination   does not get summoned. You can simple go to  Captain Blackanvil have the papers signed then return to Windcaller Kaldon.

https://database.turtle-wow.org/?quest=8507 -Field duty quest
https://database.turtle-wow.org/?npc=15440 -Captain Blackanvil 
 https://database.turtle-wow.org/?npc=15449 -Hive'Zora Abomination

**Comment by slowtorta** [comment]
Is this one still broken?
