### ISSUE TITLE
Typo in settings

### ISSUE THREAD

**Issue by pypaut** [slowtorta/turtlewow-bug-tracker#1940]
**Please, provide a clear description what the bug is:**

There is a little typo in the Key Bindings settings of the client : "Togle Turtle Finder" (should be Toggle, right?)

**Steps to reproduce the behavior with as much detail as possible:**

1. Open game menu (usually with ESC)
2. Select Key Bindings
3. Scroll all the way down to find the "Looking for Turtles" section

Thanks for the amazing WoW client

**Comment by slowtorta** [comment]
Fixed in 1.16.4.
