### ISSUE TITLE
Warlocks talents

### ISSUE THREAD

**Issue by Smelly-Foot** [slowtorta/turtlewow-bug-tracker#1941]
The warlock talent "Master Conjuror" does not work. "Healthstone" does not increase at any level.

Also the "Improved Drain Soul" talent doesn't work properly. Trigger chance at level 2 is NOT 100%.

![image](https://user-images.githubusercontent.com/68133442/184669612-1e424449-0209-4285-99f9-cb574b2d2d22.png)
![image](https://user-images.githubusercontent.com/68133442/184669654-cb1778f3-858d-4f45-9ce9-65606d42899c.png)
![image](https://user-images.githubusercontent.com/68133442/184669708-25ed32b0-c286-48e3-bf21-163690cf0994.png)

**Comment by tocopherylacetate** [comment]
imp drain soul needs to be killed by player, not pet, not anyone else for it to trigger

**Comment by Tinyfin-github** [comment]
https://github.com/slowtorta/turtlewow-bug-tracker/issues/1890
