### ISSUE TITLE
Game crashes

### ISSUE THREAD

**Issue by Smelly-Foot** [slowtorta/turtlewow-bug-tracker#1942]
Can't open mail. The game immediately freezes and crashes after a while!!! Still can't open mai

https://user-images.githubusercontent.com/68133442/184678966-87cd3bfd-d657-4cd4-9233-873c0ddca3ff.mp4

l

**Comment by jameyboor** [comment]
Suggesting to disable all addons and updating this issue. This is more suited for per-player based help such as the forums or Discord.
