### ISSUE TITLE
Lapidis Isle not focused

### ISSUE THREAD

**Issue by Vleled** [slowtorta/turtlewow-bug-tracker#1946]
**Please, provide a clear description what the bug is:**
Lapidis Isle not clickable in the world map, focuses Stranglethorn Vale.

**Steps to reproduce the behavior with as much detail as possible:**

1. Open world map
2. Go to eastern kingdoms
3. Hover over/Click where Lapidis Isle should be

**Expected behavior. Describe how it should work:**
Should have the right focus upon hovering and be clickable from the world map
![image](https://user-images.githubusercontent.com/59024704/184734506-5763955e-cc71-4197-9906-c4ba6dc63c49.png)

**Comment by slowtorta** [comment]
Sadly it's too complicated to for us to fix without proper tools.
