### ISSUE TITLE
Grifters Leggings not appearing after crafting

### ISSUE THREAD

**Issue by burlakovk** [slowtorta/turtlewow-bug-tracker#1947]
**Please, provide a clear description what the bug is:**
After crafting Grifters Leggings (https://database.turtle-wow.org/?item=83252) I receive Steel Plate Legguards (https://database.turtle-wow.org/?item=83412).

**Steps to reproduce the behavior with as much detail as possible:**
1. Craft Grifters Leggings.

**IDs of affected creatures, items, quests or spells with a link to the relevant page:**

Item: https://database.turtle-wow.org/?item=83252
https://database.turtle-wow.org/?item=83412

**Expected behavior. Describe how it should work:**
After crafting Grifters Leggings, they should appear in my inventory

**Comment by slowtorta** [comment]
It's fixed, please wait for the server update :)
