### ISSUE TITLE
Sunnyglade issues

### ISSUE THREAD

**Issue by burner1024** [slowtorta/turtlewow-bug-tracker#1950]
**Please, provide a clear description what the bug is:**
Assorted Sunnyglade issues.
[Also see](https://forum.turtle-wow.org/viewtopic.php?f=14&t=3717).

**Steps to reproduce the behavior with as much detail as possible:**
It's hard to provide exact details for some, because SGV almost never pops.

1. The elf in the fort sometimes stops accepting sparks. There's just no dialog option to turn them in. (Even before total count is 100, not sure if that's relevant).
2. NPCs in towers do not attack, just aggro and stick around (at least alliance ones).
3. Someone [got ported](https://discord.com/channels/466622455805378571/846263724481839154/1008507322215182376) above Northshire after BG, fell and died.

**Comment by Lexiebean** [comment]
No option to release when dead

**Comment by Lexiebean** [comment]
Can't hand sparks in https://i.imgur.com/SGoMWgi.jpg

**Comment by Lexiebean** [comment]
Warlord Blackskull should not be kiteable all the way back to the Alliance GY and Human Leader lmfao

**Comment by Lexiebean** [comment]
No rep at all for losing.

Honor values or speed of game should be adjusted

**Comment by slowtorta** [comment]
https://github.com/slowtorta/turtlewow-bug-tracker/issues/2900
Dying in Sunnyglade Valley doesn't return you to GY #2900

**Comment by slowtorta** [comment]
@ratkosrb

**Comment by ratkosrb** [comment]
@slowtorta :(
