### ISSUE TITLE
BG queues never popping for me

### ISSUE THREAD

**Issue by bmondeel** [slowtorta/turtlewow-bug-tracker#1952]
**Please, provide a clear description what the bug is:**
Since yesterday, 2022/08/15, I haven't been able to get into any Battleground.
Monitored closely enough to see people from my faction get into multiple instances of a BG I was queued for, and saw that there was always room for more from my faction (less than total possible numbers for the BG, more Alliance than Horde. I'm Horde).

Before work this morning I tried for 2 hours, focussed on AV, and the conditions above applied.

Behavior is the same queueing from the mini-map icon or from the BG NPCs.

**Steps to reproduce the behavior with as much detail as possible:**

1. Sign on as me (account NoblemanDire, usually character Ruex)
2. Queue all BGs
3. Sit. Quest. Sit. Chat. Sit. Do /who "Alterac Valley", sort by race, count, curse. Sit.

**IDs of affected creatures, items, quests or spells with a link to the relevant page:**

NPC: https://database.turtle-wow.org/?npc=
Item: https://database.turtle-wow.org/?item=
Quest: https://database.turtle-wow.org/?quest=
Spell: https://database.turtle-wow.org/?spell=
Object: https://database.turtle-wow.org/?object=

**Expected behavior. Describe how it should work:**
I queue BGs, then get an invite to join when there is room and my turn comes up. Never a problem before yesterday.

**Comment by bmondeel** [comment]
BGs popping for me again as of late 8/16

**Comment by slowtorta** [comment]
I'm glad it's resolved itself.
