### ISSUE TITLE
Warrior: Overpower doesn't trigger correctly

### ISSUE THREAD

**Issue by Kerebrien** [slowtorta/turtlewow-bug-tracker#1955]
**Please, provide a clear description what the bug is:**

Overpower only correctly triggers from targeted abilities. Retaliation, Whirlwind and Sweeping Strikes do not trigger Overpower when an attack is dodged.

**Steps to reproduce the behavior with as much detail as possible:**

1. Activate Retaliation or Sweeping Strikes, go into Berserker Stance
2. Wait for the mob to dodge an attack made by the skill
3. See that you cannot activate Overpower when switching to Battle Stance

**IDs of affected creatures, items, quests or spells with a link to the relevant page:**

NPC: https://database.turtle-wow.org/?npc=
Item: https://database.turtle-wow.org/?item=
Quest: https://database.turtle-wow.org/?quest=
Spell: https://database.turtle-wow.org/?spell=
Object: https://database.turtle-wow.org/?object=

**Expected behavior. Describe how it should work:**

Overpower should trigger with any dodged attack you make, be it direct or indirect via AoE

**Comment by Giperion** [comment]
Whirlwind can trigger Overpower if target managed to dodge it.
Retaliation on the other hand had a problem. I fixed that, so in next server update it will trigger Overpower, **but only if your target dodges it!** If someone else did it, doesn't count!
