### ISSUE TITLE
Inner Focus not working with Pain Spike

### ISSUE THREAD

**Issue by Vynora** [slowtorta/turtlewow-bug-tracker#1956]
**After Casting Inner Focus the mana cost of Pain Spike stays the same, after casting pain spike, inner focus is not removed.**

**Steps to reproduce the behavior with as much detail as possible:**

1. Cast Inner Focus
2. Cast Pain Spike
3. No interactions happen

**IDs of affected creatures, items, quests or spells with a link to the relevant page:**

Spell: https://database.turtle-wow.org/?spell=45555
https://database.turtle-wow.org/?spell=14751

**Expected behavior. Describe how it should work:
After casting Inner Focus the mana cost of Pain spike should be 0, after casting Pain spike Inner focus should be removed**

**Comment by ratkosrb** [comment]
Fixed by https://github.com/slowtorta/turtle-wow/commit/8ec03b3af91a4fc822175282f70338a4887c1d23
