### ISSUE TITLE
Vampiric Touch only give 2% mana return in game while the website/changelog stated that it should be 4%

### ISSUE THREAD

**Issue by JaceEverwood** [slowtorta/turtlewow-bug-tracker#1957]
**Please, provide a clear description what the bug is:**
Vampiric Touch only give 2% mana return in game while the website/changelog stated that it should be 4%

![image](https://user-images.githubusercontent.com/19348079/185003627-bcfaa3ac-fdc2-400b-8a38-41c6e1d4e21f.png)
![image](https://user-images.githubusercontent.com/19348079/185003816-fb943fe5-74c3-48df-97bf-b0b7ef27115d.png)
https://turtle-wow.org/#/priest
**Steps to reproduce the behavior with as much detail as possible:**

1.
2. 
3. 

**IDs of affected creatures, items, quests or spells with a link to the relevant page:**

NPC: https://database.turtle-wow.org/?npc=
Item: https://database.turtle-wow.org/?item=
Quest: https://database.turtle-wow.org/?quest=
Spell: https://database.turtle-wow.org/?spell=
Object: https://database.turtle-wow.org/?object=

**Expected behavior. Describe how it should work:**
it should return 4% or more mana from shadow damage dealt to the target. shadow priest still facing hardship with mana problem, as well as not get brought to raid because damage and debuff slots

**Comment by ratkosrb** [comment]
The change cannot be reflected on the tooltip until a new MPQ patch for the client is released, but it still returns 2 / 4 % mana, so it's working. The tooltip will be updated on the next client update.
