### ISSUE TITLE
Blood frenzy, next iteration

### ISSUE THREAD

**Issue by burner1024** [slowtorta/turtlewow-bug-tracker#1958]
**Please, provide a clear description what the bug is:**
1. Buff tooltip is strange: "13 ro 12%"
![Captura de pantalla de 2022-08-17 07-49-53](https://user-images.githubusercontent.com/1279852/185009811-e65166ac-793d-45d9-be41-61221dec788b.png)

2. Spell tooltip is not updated when talent is taken, old duration is shown.
![Captura de pantalla de 2022-08-17 07-50-58](https://user-images.githubusercontent.com/1279852/185009981-1f89afbf-948a-40f4-8d60-af77a6168b8d.png)

**Steps to reproduce the behavior with as much detail as possible:**

1. Learn the talent.
2. Pop tiger's fury, check tooltips.

**IDs of affected creatures, items, quests or spells with a link to the relevant page:**
Spell: https://database.turtle-wow.org/?spell=45722

**Expected behavior. Describe how it should work:**
Should show correct tooltips.

**Comment by slowtorta** [comment]
Visual bug requires a client update, but the talent is working as intended server-side at this moment.
