### ISSUE TITLE
Entrapment bugged again

### ISSUE THREAD

**Issue by Khanz0** [slowtorta/turtlewow-bug-tracker#1959]
The talent entrapment looks bugged again. Trapped a lot of mobs today and never proc the root a single time

**Comment by Khanz0** [comment]
I think was fixed in last update. Or i was just very unlucky

Today i saw a proc

But could test if it procs correcty? I feel it procs too little even with 3/3

**Comment by SabineWren** [comment]
Entrapment works fine for me.
