### ISSUE TITLE
Dustwallow Marsh: Flying fish

### ISSUE THREAD

**Issue by Stilleta** [slowtorta/turtlewow-bug-tracker#196]
School of fish at about (62, 46) in the bay, off the left side of the bridge leaving Theramore spend some of their time above the surface of the water.

**Steps to reproduce the behavior with as much detail as possible:**

1.
2. 
3. 

**IDs of affected creatures, items, quests or spells with a link to the relevant page:**

NPC: https://database.turtle-wow.org/?npc=
Item: https://database.turtle-wow.org/?item=
Quest: https://database.turtle-wow.org/?quest=
Spell: https://database.turtle-wow.org/?spell=
Object: https://database.turtle-wow.org/?object=

**Expected behavior. Describe how it should work:**

**Comment by slowtorta** [comment]
Unable to find the flying fish. Please clear WDB and visit this place again, all should be under the water.
