### ISSUE TITLE
Druid: Frenzied Regeneration still heals too little.

### ISSUE THREAD

**Issue by Testerrosaurus** [slowtorta/turtlewow-bug-tracker#1962]
**Please, provide a clear description what the bug is:**
Tooltip of "Frenzied Regeneration(Rank 2)" states "Converts up to 10 rage per second into health for 10 sec. Each point of rage is converted into 15 plus 10% of your stamina as health."

Before 16.08.2022 update Frenzied Regeneration(Rank 2) was healing for 152 per 10-rage-tick with 256 stamina.
After 16.08.2022 update Frenzied Regeneration(Rank 2) started to heal for 175 per 10-rage-tick with 256 stamina.
It is still wrong - Frenzied Regeneration(Rank 2) should be healing for 406 per 10-rage-tick with 256 stamina. 406=(15+25.6)*10

**Steps to reproduce the behavior with as much detail as possible:**
1. Shift to bear
2. Take some damage
3. Pop frenzied regeneration.

**IDs of affected creatures, items, quests or spells with a link to the relevant page:**
DB down.

**Expected behavior. Describe how it should work:**
It should add 10% of stamina for each point of rage.

**Comment by cyaohiri** [comment]
It seems like the "10% of your stamina as health" part always heals you just 10%, regardless of how much rage was consumed, whereas, if it consumed 10 rage, you should get 100% of you stamina as health in that tick.

**Comment by Testerrosaurus** [comment]
Yes, indeed, +10% of stamina seems to be always applied regardless of rage.

With 320 stamina i get 32 for 0-rage-tick, 232 for 10-rage-tick, 72 for 2-rage-tick, e.t.c.

Although there are often strange numbers for ticks like 60 or 120 or 216 or 218 which do not conform to the previous pattern "20*N + 32" where N is integer (maybe because of rounding of rage or smth, or maybe not).
