### ISSUE TITLE
Omen of Clarity proc rate

### ISSUE THREAD

**Issue by burner1024** [slowtorta/turtlewow-bug-tracker#1963]
**Please, provide a clear description what the bug is:**
Omen is procing too rarely.

**Steps to reproduce the behavior with as much detail as possible:**

1. Cast Omen.
2. Shift to cat, start attacking training dummy.
3. Count procs. I got 9 procs in 10 minutes.
![Captura de pantalla de 2022-08-18 03-48-44](https://user-images.githubusercontent.com/1279852/185240323-33d5f0d4-be5d-4f45-8d30-05e4af0cf1b2.png)

**IDs of affected creatures, items, quests or spells with a link to the relevant page:**
Db down.

**Expected behavior. Describe how it should work:**
According to comments [here](https://classic.wowhead.com/spell=16864/omen-of-clarity#comments), it should be 2 ppm just from auto attacks, not counting abilities.
I saw #907, but I'm not sure why it says "6 to 10% proc rate". 2 PPM for cat auto attack with base speed of 1 is 3.33%, but obviously that's not what happening. For bear, base speed of 2.5 should give 8.33% proc.

I didn't test abilities and spells, since I'm not sure what's the set ppm for them. Can you confirm that it should be 2 ppm for everything? Or some other number?

**Comment by slowtorta** [comment]
Fixed in https://forum.turtle-wow.org/viewtopic.php?f=63&t=3752
