### ISSUE TITLE
Dust Devils in Westfall phase out after spawning

### ISSUE THREAD

**Issue by Kerebrien** [slowtorta/turtlewow-bug-tracker#1964]
**Please, provide a clear description what the bug is:**

Dust Devils miraculously despawn / phase out right after spawning

**Steps to reproduce the behavior with as much detail as possible:**

1. Go to Westfall
2. Go to the Dust Devil spawn location
3. Check what the frick is going on

**Expected behavior. Describe how it should work:**

They shouldn't do what I said obviously.

**Comment by slowtorta** [comment]
Sorry, we were unable to reproduce this bug. Clear your WDB folder or download a fresh client from our website.
