### ISSUE TITLE
Chest spawning system

### ISSUE THREAD

**Issue by Azeron223** [slowtorta/turtlewow-bug-tracker#1965]
The current chest spawning system does not match how the original game worked.

**Current Behaviour**
As it currently stands, all chests in the game have static spawn location and respawn timers depending on the level of the chest, both inside and outside dungeons with every chest in a "cluster" always respawning leading to some small locations having as many as 4~ chests up at the same time - thus if you loot a chest you can be guaranteed it will respawn in that exact location within 30-120 minutes, the higher level the chest the longer the respawn timer which is obviously leading to abuse as players can set timers and know exactly when to loot a freshly spawned chest (Which has been observed to be abused by low level alts on "safe" high level chests even on Turtlewow).

**Chest Object IDs:** 2844, 2849, 2843, 106318, 106319, 75293, 131979, 75297, 75295, 74447, 75296, 153465, 131978, 153469, 153468, 153463, 75300, 75299, 153464, 75298, 74448, 4149, 2852, 153451, 153453, 153454, 2857, 2855, 2850, 105570, 3714, 111095, 3715, 105579, 4096, 105581, 105578.

It's possible there are more chests IDs effected by this issue, though the normal Classic Wowhead only lists the above chests as ones being available to players.

**Expected Behaviour**
The chest system as it worked in original vanilla worked in a cluster system, in any general area there would potantially be anything from 2-8~ potential locations for a chest to spawn, picking a single location in the cluster to spawn the chest per respawn. It should also be noted that there are many chest spawn locations not currently being used at all compared to Classic (Which from memory is accurate to 1.12, while private servers tend to have always used a more simplified system which can be more easily abused)

As seen in the below example for private servers, all of these chest locations in Wetlands are static, they always respawn on a set respawn timer which for this level is 60 minutes from memory.
![Private](https://user-images.githubusercontent.com/88284400/185337295-8053826f-c966-4370-8f69-df625046bb9b.jpg)

In this image taken from Classic however, each color represents a "Cluster" of chests, (guessed based on personal testing and memory) all clusters of chests can potentially spawn at the same time, however there should only be 1 chest up per cluster and there should also be far more chest spawn locations when compared to the current private server locations.
![Classic](https://user-images.githubusercontent.com/88284400/185337298-3531931f-beff-4f7d-ae17-c9f690a17fed.jpg)

It should be noted this effects every zone and every instance where chests can spawn, instance chests should also have randomly spawning chests based on this system (Stratholme for example should typically have 2-4 chests, with them potentially spawning as locked over roughly 12~ different locations, currently there seems to only be a single unlocked chest  and a single locked chest spawning in the same locations for the whole instance)

**Comment by Velite12** [comment]
![image](https://user-images.githubusercontent.com/45871932/185855666-cc41fb6b-2c4f-494e-8c53-a362de660ccc.png)

**Comment by slowtorta** [comment]
This indeed needs to be improved, but if we're to change how the chest pools respawn, their position will not mimic Classic :)
