### ISSUE TITLE
Priest empower champion buff not giving ranged attack power anymore

### ISSUE THREAD

**Issue by OrnsteinHunter** [slowtorta/turtlewow-bug-tracker#1968]
**Please, provide a clear description what the bug is:**

The priest capstone, proclaim champion, is not giving ranged attack power when you buff the target with empower champion. It appears that its only set to give (6) Apply Aura #99: Mod Attack Power and not ranged attack power

**Steps to reproduce the behavior with as much detail as possible:**

1. spec into proclaim champion and give it to a target
2. use empower champion on your target
3. use an addon like bettercharacterstats to show it doesn't give ranged attack power

**IDs of affected creatures, items, quests or spells with a link to the relevant page:**

Spell: https://database.turtle-wow.org/?spell=45565

**Expected behavior. Describe how it should work:**

The intended behavior as described by Moon is that its supposed to give ranged attack power so hunters can benefit from the buff. It used to function this way but was broken in a server update it seems.

Heres an image of Moon confirming it should give ranged attack power

https://imgur.com/a/uN8BsXb

**Comment by Gurky-Turtle** [comment]
You cannot rely on bettercharacterstats  for correct values its a custom spell you are using and what bettercharacterstats does is reads the buff/debuff and item text itself to parse information and if that buff/debuff  or item text isnt coded into the addon it will not be able to read it. 

I suggest making a bug report for Bettercharacterstats here: https://github.com/Gurky-Turtle/BetterCharacterStats

**Comment by Gurky-Turtle** [comment]
will be fixed in the next update no need to reopen.
