### ISSUE TITLE
Dustwallow Marsh: Turtles can not be skinned

### ISSUE THREAD

**Issue by Stilleta** [slowtorta/turtlewow-bug-tracker#197]
The Mudrock Snapjaw turtles in the bay across from Theramore once killed can not be skinned.

**Steps to reproduce the behavior with as much detail as possible:**

1. Locate Mudrock Snapjaw turtles in bay across from Theramore to the west.
2. Kill Mudrock Snapjaw.
3. Loot and attempt to skin.

**IDs of affected creatures, items, quests or spells with a link to the relevant page:**

NPC: https://database.turtle-wow.org/?npc=4400

NPC should be skinnable upon death.m Skinning should drop appropriate loot.

Skinning loot table should be similar to NPC: https://database.turtle-wow.org/?npc=14123 (Tanaris Steeljaw Snapper) 
but slightly lower level.

**Comment by slowtorta** [comment]
Thanks for reporting it. It'll be fixed on the next server restart. Make sure to clear your WDB folder.
