### ISSUE TITLE
Arcane Missiles Goblin Bug

### ISSUE THREAD

**Issue by probablysalsa** [slowtorta/turtlewow-bug-tracker#1970]
**Please, provide a clear description what the bug is:**
When playing Goblin Arcane Mage, the animation for Arcane Missiles is broken. The character will begin casting, damage will be dealt, but no individual missiles will be shown until .5 seconds after the cast is completed.
**Steps to reproduce the behavior with as much detail as possible:**

1.  Roll a goblin mage to level 8.
2.  Use the Arcane Missiles spell.
3.  Be really sad when one of the coolest animations doesn't work for your race :(. Step 4 is a screen recording of the issue.
4. https://youtu.be/MFcZcRUjhYQ

**IDs of affected creatures, items, quests or spells with a link to the relevant page:**

Spell: https://database.turtle-wow.org/?spell=5143
Spell: https://database.turtle-wow.org/?spell=5143

**Expected behavior. Describe how it should work:**
An animation should fire every second that Arcane Missiles is channeled. I compared my animation with a high elf mage and their animation worked perfectly.

**Comment by geojak** [comment]
It's not goblin bug, affects my troll aswell. Also long long tiem reported before but was closed...

**Comment by geojak** [comment]
https://github.com/slowtorta/turtlewow-bug-tracker/issues/951

Just Was never fixed

**Comment by probablysalsa** [comment]
> #951
> 
> Just Was never fixed

It seems like, from looking at the video attached, Trolls at the very least get missiles appearing during the channel.
Goblins don't get an animation at all.

**Comment by slowtorta** [comment]
Related to https://github.com/slowtorta/turtlewow-bug-tracker/issues/1825
