### ISSUE TITLE
Item: Ravager

### ISSUE THREAD

**Issue by Kerebrien** [slowtorta/turtlewow-bug-tracker#1975]
**Please, provide a clear description what the bug is:**

The item 'Ravager' has some issues about it's ability.
The most obvious one would be that the third AoE tick doesn't seem to come out most of the time.
Another problem is that the 'Bladestorm' ability immediately stops when the current target is dead. Oftentimes it even stops when the initial target is dead, despite having switched targets since the channel started.
If by any chance this is intended as a QoL feature to make the weapon easier to handle, please revert this change. One can always unclick the 'Bladestorm' buff or use another skill to cancel it.

**Steps to reproduce the behavior with as much detail as possible:**

1. Get surrounded by a bunch of low HP mobs
2. Attack until the 'Bladestorm' ability triggers
3. See that it stops after your target died, despite having switched targets.

**Expected behavior. Describe how it should work:**

It should consistently stay up and give off all 3 AoE cleaves when completely channeled. It's more than enough to be able to cancel it by removing the aura.

**Comment by Khanz0** [comment]
I hope they fix the issue when you kill a mob

**Comment by geojak** [comment]
I have the lvl 60 version on ravage from sw vault and it misses the third tick all the time. Makes it useless

**Comment by Kerebrien** [comment]
https://cdn.discordapp.com/attachments/1005126782409773127/1013403811194339408/Ravager_Bladestorm_Channel_Bug.mp4

First clip shows a bugged-out proc
Second clip shows how it's supposed to work (kinda)

The spin animation weirdly persists for some reason, you do a weird 'spin-out' that does nothing.
Also, even Herod himself seems to be suffering from this issue, saw his 3rd tick missing quite often.

**Comment by redmagejoe** [comment]
This appears to have been fixed in a previous update. Bladestorm spell, which is on both Ravager and the aforementioned SW Vault weapon, hits 3 times even when no enemy is targeted or the initial target is dead.

Fixed.
