### ISSUE TITLE
Keeper Remulos not Appearing in Moonglade

### ISSUE THREAD

**Issue by burlakovk** [slowtorta/turtlewow-bug-tracker#1976]
**Please, provide a clear description what the bug is:**
Keeper Remulos, Keeper of the Grove type NPC, is not at his place in Moonglade

**IDs of affected creatures, items, quests or spells with a link to the relevant page:**

NPC: https://database.turtle-wow.org/?npc=11832

**Comment by slowtorta** [comment]
It'll be fixed in the next update this Wednesday!
