### ISSUE TITLE
Of love and family is bugged,  Artist Renfray can't be seen

### ISSUE THREAD

**Issue by Tinyfin-github** [slowtorta/turtlewow-bug-tracker#1978]
https://database.turtle-wow.org/?quest=5846 

Of love and family is bugged,  Artist Renfray can't be seen

https://database.turtle-wow.org/?npc=11936

**Comment by redmagejoe** [comment]
I don't believe this is bugged. Rather, I'm fairly certain she's among the ghosts in Caer Darrow that require the item received from Eva as part of the Kirtonos the Herald quest chain.

https://database.turtle-wow.org/?item=13544

If you do not have this item equipped, you cannot see any ghosts aside from the servants. This report should be closed: working as intended unless even the Spectral Essence does not reveal this NPC.

**Comment by GuybrushGit** [comment]
@ratkosrb @redmagejoe I seriously doubt you need the item to see this npc. I've done this quest many times on retail and never needed it.
If you look at the quest comments even from 2006 people mention that you don't need the spectral essence: https://classic.wowhead.com/quest=5846/of-love-and-family#comments

**Comment by ratkosrb** [comment]
@GuybrushGit I know, I checked sniffs and removed the wrong invisibility aura from the npc, that's why I closed the issue.
