### ISSUE TITLE
Box of Goodies doesn't always contain a single item

### ISSUE THREAD

**Issue by blargsnarf** [slowtorta/turtlewow-bug-tracker#198]
**Please, provide a clear description what the bug is:** Box of Goodies, reward from An Extraordinary Egg in Tanaris, has the possibility of being empty.

**Steps to reproduce the behavior with as much detail as possible:**

1. Do the quest.
2. Open the box.
3. See there's nothing in the box.
4. Lose the box.

**IDs of affected creatures, items, quests or spells with a link to the relevant page:**

NPC: https://database.turtle-wow.org/?npc=
Item: https://database.turtle-wow.org/?item=9541
Quest: https://database.turtle-wow.org/?quest=2747
Spell: https://database.turtle-wow.org/?spell=
Object: https://database.turtle-wow.org/?object=

**Expected behavior. Describe how it should work:** I'm pretty sure the box should always contain something, at least.

**Comment by slowtorta** [comment]
Thanks for reporting it. It'll be fixed on the next server restart. Make sure to clear your WDB folder.
