### ISSUE TITLE
herbs not showing up on minimap unless close.

### ISSUE THREAD

**Issue by tarakan404** [slowtorta/turtlewow-bug-tracker#1983]
**Herbs show up on the minimap only when im close to them, and disappear when only half the minimap away, when usually they appear and disappear at the border of the minimap :** also i noticed that the mobs appear  only when im close.
Tried fresh client, different ssd, different PC, different network, still the same. the bug went away after doing an instance, but came back the next day, loading into a instance did not help.
![WoWScrnShot_082122_130017](https://user-images.githubusercontent.com/111710013/185992613-3e275d5e-8a65-4f23-aa60-ce9b591d04a2.jpg)
![WoWScrnShot_082122_130015](https://user-images.githubusercontent.com/111710013/185992662-312d2bb8-c731-4685-ac85-59cc4ff1c724.jpg)
on the screens you can see how close i have to get to be able to see the herbs on the minimap
![WoWScrnShot_082122_124445](https://user-images.githubusercontent.com/111710013/185992899-fe175a20-dcf7-4ad6-b74e-ec5424b67219.jpg)
![WoWScrnShot_082122_124453](https://user-images.githubusercontent.com/111710013/185992936-43a83a29-ca6d-46dc-9dc6-97cec10eb59a.jpg)

**Comment by spacestr** [comment]
Confirming that I also have similar experience with herb and mining nodes. They also seem to blink out and back in when moving, but overall this bug makes farming mats much more annoying.

**Comment by spacestr** [comment]
I also noticed that it goes back to normal detection range during lower player count on the server.

**Comment by tarakan404** [comment]
yep i can confirm that, once the server pop reaches 2500online the bug starts to appear

**Comment by slowtorta** [comment]
Fixed on the next update.
