### ISSUE TITLE
Troll Males say female lines for /wave and /greet

### ISSUE THREAD

**Issue by dromen48** [slowtorta/turtlewow-bug-tracker#1985]
**Please, provide a clear description what the bug is:**

**Steps to reproduce the behavior with as much detail as possible:**

1. Be a male troll
2. /greet
3. /wave

**IDs of affected creatures, items, quests or spells with a link to the relevant page:**

**Expected behavior. Describe how it should work:**
Male troll lines

**Comment by cyaohiri** [comment]
Another thing to note is that /wave should NOT be making any sound instead of making the same sound as /greet or /hi. This is how it worked before the update, and it's how it's described in the emote table here: https://wowpedia.fandom.com/wiki/List_of_emotes

**Comment by dromen48** [comment]
Okay. So can the voice line be removed for /wave and the /greet be fixed?

**Comment by slowtorta** [comment]
Fixed in 1.16.4
