### ISSUE TITLE
[Quest} The Dunemaul Compound can't be complete

### ISSUE THREAD

**Issue by dole555** [slowtorta/turtlewow-bug-tracker#1987]
**Please, provide a clear description what the bug is:**
[Dunemaul Enforcer](https://database.turtle-wow.org/?npc=5472) don't spawn anywhere anymore.

**IDs of affected creatures, items, quests or spells with a link to the relevant page:**

NPC: https://database.turtle-wow.org/?npc=5472
Quest: https://database.turtle-wow.org/?quest=5863

**Expected behavior. Describe how it should work:**

**Comment by ratkosrb** [comment]
They do spawn. They share spawn points with Dunemaul Ogre, Dunemaul Ogre Mage and Dunemaul Warlock.
