### ISSUE TITLE
[Uldaman] mob Stone Keeper missing ability

### ISSUE THREAD

**Issue by dole555** [slowtorta/turtlewow-bug-tracker#1989]
**Please, provide a clear description what the bug is:**
Stone Keepers should blow up close to death. They don't do that.
https://classic.wowhead.com/npc=4857/stone-keeper#comments;mode:normal
Here you can see comment that they should, also the self destruct spells under 'spells'

**IDs of affected creatures, items, quests or spells with a link to the relevant page:**

NPC: https://database.turtle-wow.org/?npc=4857
Spell: https://database.turtle-wow.org/?spell=9879
Spell: https://database.turtle-wow.org/?spell=9874

**Expected behavior. Describe how it should work:**

**Comment by geojak** [comment]
duplicate from this january issue https://github.com/slowtorta/turtlewow-bug-tracker/issues/956

**Comment by geojak** [comment]
@slowtorta But now you closed both issues as duplicates of each other? Is this fixed?

**Comment by ratkosrb** [comment]
Should be fixed in the next update.
