### ISSUE TITLE
Skinning not working properly

### ISSUE THREAD

**Issue by allenphreak** [slowtorta/turtlewow-bug-tracker#199]
Occasionally when skinning, the loot window will be empty. Other times, I may skin a mob with 1-4 skinning items in it. It feels like the missing ones from the skinning attempts with no result?

1. Kill and skin mobs.
2. Note the skinning loot window.
3. Profit!

NPC: https://database.turtle-wow.org/?npc=4324, https://database.turtle-wow.org/?npc=4323, https://database.turtle-wow.org/?npc=5422
Item: https://database.turtle-wow.org/?item=8165, https://database.turtle-wow.org/?item=4304, https://database.turtle-wow.org/?item=8154

Usually one item per skinning attempt, always get something. Not sure why it's empty sometimes and full of loot others.

**Comment by GrenderG** [comment]
Can you provide any proof showing that this is not the expected behavior?

**Comment by allenphreak** [comment]
Only that nothing else works that way. You pick herbs and never get an empty window, you go mining and never get an empty window, and it doesn't seem to happen everywhere. I don't recall it ever happening in the past anywhere I've played.


Sent from Yahoo Mail for iPhone


On Thursday, August 19, 2021, 8:28 AM, GrenderG ***@***.***> wrote:




Can you provide any proof showing that this is not the expected behavior?

—
You are receiving this because you authored the thread.
Reply to this email directly, view it on GitHub, or unsubscribe.
Triage notifications on the go with GitHub Mobile for iOS or Android.

**Comment by Rakura1** [comment]
Can confirm this is happening with Snapjaw turtles in Tanaris. You will skin the mob and it will just disappear or will open with a blank window. This is very frustrating when really the only way to get turtle scales is through skinning. It varies but at most I've seen 5 straight mobs show blank skinning loot.

**Comment by Nolin7777** [comment]
Closed until proof added.
