### ISSUE TITLE
Crusader Strike, is not affected by rank 7 gloves.

### ISSUE THREAD

**Issue by abbraxxas** [slowtorta/turtlewow-bug-tracker#1990]
1. unequipped rank7 gloves - hit training dummy with 5 stacks and seal of righteousness.
2. equipped rank7 gloves - hit training dummy with 5 stacks and seal of righteousness.
3. check combat log, same values.

----------------------------------------------------------------

1. damage with seal : 92 -93
2. damage with seal : 92 -93

![without gloves](https://user-images.githubusercontent.com/111962404/186362199-303c9ce5-3735-4395-87a9-c357826dc079.jpg)

![with gloves](https://user-images.githubusercontent.com/111962404/186362167-d623a52d-29b9-4102-b50f-f5fa06cf40b1.jpg)

the tooltip of crusader strike is neither affected by heart of the crusader nor rank 7 gloves.

-----------------------------------------------------------------

i tried the same process while unequipping libram of fervor witch contributes to crusader strike, no difference. 
i just tested heart of the crusader, it gives 22.5 bonus to crusader strike.
with libram of fervor it should be 47.5.
but it stays at 22.5 at all time.
intended or not ? as a % increase should increase the total amount, not just a portion? its not + base * 1.15. as there are items that affect crusader strike, either include or exclude the possibiltie in the tooltip please.

i now tested something else. 

i respecced without heart of the crusader, and my damage was the same with seal of righteous,

conclusion, Libram of Fervor overwrites heart of the crusader.
![non heart of the crusader](https://user-images.githubusercontent.com/111962404/186369983-f9b1f14e-e871-4edf-a22e-cbf7c38f0dc8.jpg)

**Comment by abbraxxas** [comment]
i tried the same process while unequipping libram of fervor witch contributes to crusader strike, no difference, same with heart of the crusader, currently i only found libram of fervor to affect crusader strike at all.

**Comment by abbraxxas** [comment]
i just tested heart of the crusader, it gives 22.5 bonus to crusader strike.
with libram of fervor it should be 47.5.
but it stays at 22.5 at all time.

**Comment by geojak** [comment]
Is that the same for judgment of crusader?

**Comment by Velite12** [comment]
Actually, the talent is working. What it's doing is it's increasing the damage of the crusader strike itself...
![image](https://user-images.githubusercontent.com/45871932/186490675-c3947be8-697f-4289-aaaf-e577b40a205c.png)

**Comment by Velite12** [comment]
![image](https://user-images.githubusercontent.com/45871932/186491739-e02f8dbf-038a-4c82-9a1c-cc97a0957030.png)

Adding libram of fervor is also increasing the damage the strike itself does which I also think is unintended.

**Comment by geojak** [comment]
Hey that makes crusader strike actually pretty good
