### ISSUE TITLE
pibgib imp demon is humanoid

### ISSUE THREAD

**Issue by geojak** [slowtorta/turtlewow-bug-tracker#1991]
**Please, provide a clear description what the bug is:**
pimgib is a imp demon warlock pet

https://database.turtle-wow.org/?npc=14349

its classified as hamnoid

**Expected behavior. Describe how it should work:**

shoud be a demon, and exocism should work on it

**Comment by gheor7** [comment]
https://classic.wowhead.com/npc=14349/pimgib

Was this change added with classic?

**Comment by geojak** [comment]
well its a demon, so maybe classic was bugged too
