### ISSUE TITLE
Completing requirement isn't granting Lorekeeper title

### ISSUE THREAD

**Issue by Zmitrok1984** [slowtorta/turtlewow-bug-tracker#1992]
**Please, provide a clear description what the bug is:**
They say that knowledge is power and now you have a way to show your power through your diligent exploration skills with vast quest awareness! Lorekeeper is the title for those who managed to complete 1700 quests!
https://discord.com/channels/466622455805378571/747135466192633906/1005605130902700153

According to in-game command I have completed 1937 quests
![image](https://user-images.githubusercontent.com/99164611/186440946-daa2d404-5dbd-4561-ae3d-b5f1e98fbc8c.png)
But there is no new title Lorekeeper for selection
![image](https://user-images.githubusercontent.com/99164611/186441630-35b506e6-93a2-4a5b-acb6-92f9f1635e46.png)
**Expected behavior. Describe how it should work:**
It should be possible to select new title

**Comment by slowtorta** [comment]
That's pretty weird, I couldn't reproduce this issue. Were you to receive this title after re-loggin in the game?

**Comment by geojak** [comment]
I have the same issue on msg

**Comment by cyaohiri** [comment]
Could it be that the title isn't given retroactively, i.e. if you completed 1,700 quests _before_ the title was introduced, you won't get it?

**Comment by gala320** [comment]
I have a character that hit 1700 quests recently, did not receive the title either.

**Comment by jameyboor** [comment]
Fixed on next update.
