### ISSUE TITLE
[Quest] Quest giver not giving "Gnoll Bounty" quest

### ISSUE THREAD

**Issue by CAKyPA** [slowtorta/turtlewow-bug-tracker#1994]
As title said, quest giver not giving this quest.
I already completed the requested quest "The Pumpkin Thieves".
Was using not saving any WDB files (user permission method), tried enabling WDB files and still not giving the quest.

https://database.turtle-wow.org/?quest=60042

**Comment by cyaohiri** [comment]
I had the same issue on one of my characters. I finished all quests in Elwynn Forest, but was never able to take Gnoll Bounty.
The database says [Gnoll Bounty](https://database.turtle-wow.org/?quest=60042) requires  [The Pumpkin Thieves](https://database.turtle-wow.org/?quest=60041) to be completed, but that's not my experience at all. The Pumpkin Thieves asks you to talk to [Terry Palin](https://database.turtle-wow.org/?npc=1650), and that's when you can also accept Gnoll Bounty, so you can have both of those quests at the same time. Being unable to accept Gnoll Bounty happened to be only once in about 10 characters.

**Comment by CAKyPA** [comment]
Maybe quest is only available during [The Pumpkin Thieves](https://database.turtle-wow.org/?quest=60041) quest, once you completed the [The Pumpkin Thieves](https://database.turtle-wow.org/?quest=60041) you can't take the [Gnoll Bounty](https://database.turtle-wow.org/?quest=60042) quest anymore. Not sure if it's intentional or bug.

Also found out why I missed the [Gnoll Bounty](https://database.turtle-wow.org/?quest=60042).
[The Pumpkin Thieves](https://database.turtle-wow.org/?quest=60041), Speak to Terry Palin have a wrong link.
And it's same on PFQuest and PFQuest-turtle, not pointing the correct NPC.
Wrong: https://database.turtle-wow.org/?npc=51299
Correct: https://database.turtle-wow.org/?npc=1650

Found him after reading the description and didn't take the [Gnoll Bounty](https://database.turtle-wow.org/?quest=60042) because was thinking doing "Eastvale Logging Camp" quests later.

**Comment by slowtorta** [comment]
This is the intended design. He'll give this quest only if you're out there searching for stolen pumpkins :)
