### ISSUE TITLE
Male/?Female? High Elf /Silly Voice Output Is Unconsistant

### ISSUE THREAD

**Issue by Apimius** [slowtorta/turtlewow-bug-tracker#1995]
The high Elf Silly Emote does not work sometimes (voice lines missing). I can only verify this for male high elfs

**Steps to reproduce the behavior with as much detail as possible:**

1. Use /silly on a male high elf 
2.  Notice that about only 1 out of 3 /silly emotes give a working voice output
3. Be sad

Every /silly should have a working voice output, and each time it should be a different one until it repeats

**Comment by redmagejoe** [comment]
This is a result of a quick fix that was made to get the 1.16.1 patch pushed through, which required silencing lore-inconsistent voice lines as these are still the Blizzard Blood Elf voice lines on Male High Elf. There was talk of having a voice actor completely redo all the Male High Elf lines, so I would imagine this will be resolved when that goes live.
