### ISSUE TITLE
Warsong Flag not visible in flag room after previous pickup

### ISSUE THREAD

**Issue by FaeshaDawnwing** [slowtorta/turtlewow-bug-tracker#1997]
**Please, provide a clear description what the bug is:**
Enemy flag wasn't visible in Warsong Gulch while it was already 0/2, presumably making it impossible to win. Probably triggered due to already picking it up while it was 0/2 and getting killed, allowing the Horde to return it. After standing around in the enemy flagroom and trying (and failing) to stop the efc from capping, I whispered him to ask if their flag was still visible for him, which he confirmed. No Alliance player made it to the Horde base, so I wasn't able to have one of them try to pick it up, so I can't tell if it was truely only on my end or not. I was almost in the tunnel of our own base when I died, so the enemy flag room probably wasn't loaded at the time of my death, if that's important. I didn't try to relog, as I'm 90% sure that would result in me being removed from the battleground with a deserter debuff. Happend in the 30-39 bracket, if it's important (which I doubt).

**Steps to reproduce the behavior with as much detail as possible:**
Can't guarantee it always doesn't work due to the specifics.
1. pick up flag in Warsong Gulch
2. die and have enemy return their flag
3. return to enemy base with no visible flag

**IDs of affected creatures, items, quests or spells with a link to the relevant page:**
Warsong Flag: https://database.turtle-wow.org/?object=179831 (I think)
Silverwing Flag: https://database.turtle-wow.org/?object=179830 (presumed)

**Expected behavior. Describe how it should work:**
When entering the enemy flag room, their flag should be visible and ready to pick up, no matter if you previously picked it up or not. Only exception should be in the seconds right after a flag was captured.

I've added a screenshot to show me in the enemy flag room with no flag. Remained there for several minutes until the Horde picked up our flag and turned it in, with no change happening in that time.
![tfw no flag](https://user-images.githubusercontent.com/112026780/186525835-830442b4-724c-4bbd-a41b-49658f84ac98.png)

**Comment by slowtorta** [comment]
It was probably fixed the beginning of September. Please re-open this issue if it's still occurring.
