### ISSUE TITLE
En-ay-es-tee-why Egg sack spawns issue

### ISSUE THREAD

**Issue by Azeron223** [slowtorta/turtlewow-bug-tracker#1998]
The [Spire Spider Eggs](https://database.turtle-wow.org/?object=175606) (Object ID: 175606) in LBRS for the quest [En-ay-es-tee-why ](https://tbc.wowhead.com/quest=4862/en-ay-es-tee-why) (Quest ID: 4862) aren't working as they did in original release.

Currently in the LBRS dungeon for the quest [En-ay-es-tee-why](4862), there are a total of only 4 lootable [Spire Spider Eggs](https://database.turtle-wow.org/?object=175606) on a 5-minute respawn timer, which isn't enough for even a single group member to complete the quest without waiting for respawns.

**Expected behavior:**
For starters there should be far more [Spire Spider Egg](https://database.turtle-wow.org/?object=175606) spawn locations, from memory I beleive there were 20-30 spawns spread from the bottom of [Mother Smolderweb's](https://database.turtle-wow.org/?npc=10596) ramp right through to just before [Urok Doomhowl's](https://database.turtle-wow.org/?npc=10584) platform.

In addition to this, looting an egg should have a chance (I beleive this is a 50% chance from memory) to spawn the same pack of [Spire Spiderling's](https://tbc.wowhead.com/npc=10375/spire-spiderling) (Mob ID: 10375) spawned by [Spire Spider's](https://tbc.wowhead.com/npc=10374/spire-spider) (Mob ID: 10374), it's possible this is done using the same [Summon Spire Spiderling spell](https://tbc.wowhead.com/spell=16103/summon-spire-spiderling) (Spell ID: 16103) as the mob itself.

**Comment by slowtorta** [comment]
Fixed on the next update.
