### ISSUE TITLE
Blessing of Freedom does not remove webs cast by Webwood Lurkers

### ISSUE THREAD

**Issue by BowtiesAreCool** [slowtorta/turtlewow-bug-tracker#20]
The paladin spell Blessing of Freedom does not remove or make players immune to the webs cast by Webwood Lurkers in Teldrassil.

The expected behaviour is that this spell makes the target (a friendly player) immune to movement-impairing effects, including removing existing effects, for 10 seconds. 

The blessing works as expected on many other movement-impairing effects. It is not known if any other effects are currently affected by this issue.

Screenshot attached showing both the blessing and a web effect active on a targeted player simultaneously.

Steps to reproduce:
1. Go to Teldrassil and engage a webwood lurker with a paladin present.
2. Get webbed by the spider.
3. Cast Blessing of Freedom on the webbed player.

![blessing-of-freedom-bug](https://user-images.githubusercontent.com/46679133/121016725-97ee7e00-c7f0-11eb-83ed-c87fffbf25ee.png)

**Comment by Nolin7777** [comment]
No proof
