### ISSUE TITLE
In Dreams - This quest has been broken for too long.

### ISSUE THREAD

**Issue by Zangatsu** [slowtorta/turtlewow-bug-tracker#200]
The quest in Western Plaguelands, the conclusion to Tirion Fordring's chain, In Dreams offers a pre-raid BIS necklace for melee dps, a tank chestpiece, and several other very powerful pieces of gear.  This is a centric quest to classic wow endgame, yet it has been broken for as long as I have played on TWoW.  It needs fixed.

You escort Taelan out of Hearthglen, and he engages the fight with Isillien and dies, the player is then supposed to be able to stay far away from Grand Inquisitor Isillien  and remain out of combat with him, waiting for Tirion Fordring to arrive and finish the quest.  On Turtle WoW, no matter your distance, Grand Inquisitor Isillien  engages combat with you and attacks you.   You can see here based on comments from 15 years ago that players were able to simply stay out of his aggro range and wait. https://classic.wowhead.com/quest=5944/in-dreams#comments   Some players have been able to complete this quest by going through great measures, such as kiting the mobs around the tower for several minutes with the help of a party or a warrior with piercing howl/rage potions, but I have struggled long with my 160ms and failed to succeed.  Hours have been dedicated to trying to beat this bugged quest and earn my best in slot pre-raid DPS necklace.  Please simply fix the quest so that Grand Inquisitor Isillien does not engage the player from an unreasonable range.

**Comment by UsernameChad42069IsNotAvailable** [comment]
not onyl should you not get combat, but also the quest is made for you to die and see the scene unfold after your death you will see taelan fordrign get ressurected by Tyrion, and after q is complete you would release.. dying shouldn't fail quest

**Comment by LeopoldHock** [comment]
> not only should you not get combat, but also the quest is made for you to die and see the scene unfold after your death you will see taelan fordrign get ressurected by Tyrion, and after q is complete you would release.. dying shouldn't fail quest

This is only true for Classic. Checking original wowhead comments from 2006 confirms that dying fails the quest. What is not correct behavior is that Isillien aggroes over any distance:
https://classic.wowhead.com/quest=5944/in-dreams#comments:id=305

**Comment by jameyboor** [comment]
Fixed next update.
