### ISSUE TITLE
wrong disechant id on custom tailor chest

### ISSUE THREAD

**Issue by geojak** [slowtorta/turtlewow-bug-tracker#2000]
**Please, provide a clear description what the bug is:**

the custom tailor blue cheast https://database.turtle-wow.org/?item=83281 has disenchant ID 45
this is wrong
comapre it to the vanilla lvl 42 item https://database.turtle-wow.org/?item=9415 which has the right disenchant ID 46

this would result in getting worse shards then what is expected for a lvl 44 item

**Expected behavior. Describe how it should work:**

whoever is making these items, pls gives them a guide for correct disenchant IDs
this guide ob the froum is WRONG https://forum.turtle-wow.org/viewtopic.php?f=3&t=1164&p=23416#p23416

**Comment by 9600bauds** [comment]
The guide on the forum is correct, but it's for itemlevel, not for level required to equip.

**Comment by geojak** [comment]
Oh that makes sense
