### ISSUE TITLE
lawbringer set doesnt have 8 set bonus anymore

### ISSUE THREAD

**Issue by geojak** [slowtorta/turtlewow-bug-tracker#2002]
**Please, provide a clear description what the bug is:**
![WoWScrnShot_082522_185304](https://user-images.githubusercontent.com/25199983/186724562-aa09b5b7-f6ee-42c4-9c2d-314eb4455e05.jpg)

in the screenshot i am hovering over my lawbringer boots.

there is no 8 set bonus anymore!

i dont not own more set pieces so can t test if its just visual bug or there is an acutal 8 set bonus effect

**Comment by geojak** [comment]
I have the pants and on the pants the 8 set bonus is displayed, but not on shoes

**Comment by jameyboor** [comment]
Delete your WDB. The set bonus is there.

**Comment by geojak** [comment]
@jameyboor I just welted wdb, no change. Its missing on t1 boots, it's ivislvd on t1 pants

I dotm have other prices to check.

Pls reopen...

**Comment by slowtorta** [comment]
I cannot reproduce, fine for me. Please check if your client is intact, and download a fresh version from the website if needed.
![image](https://user-images.githubusercontent.com/66763404/187200296-b7ce9d1c-e3ca-480c-8f9d-ace044c271c0.png)
