### ISSUE TITLE
Character skin has not changed and is not affected

### ISSUE THREAD

**Issue by Undisturbed1** [slowtorta/turtlewow-bug-tracker#2003]
**Please, provide a clear description what the bug is:**
Character Nosimpin purchased 2 different high elf skins: Dark Ranger and Blood Elf. Dark Ranger was initially applied and refunded as the aesthetic was not pleasing. Unable to see any other skin beyond the Dark Ranger one which was initially applied. Was repeatedly told the bug was not reproducible. Even when applying the Blood Elf Skin unable to override the dark ranger skin.  I have tried deleting the WDB folder, deleting all addons, and doing 2 fresh installs of T-Wow
![nosimping dark ranger skin bug](https://user-images.githubusercontent.com/112115162/186734495-be615de8-e7b2-4719-a7e0-84aad661e241.PNG)

**Steps to reproduce the behavior with as much detail as possible:**

1. Skin does not change
2. 
3. 

**IDs of affected creatures, items, quests or spells with a link to the relevant page:**
Nosimpin
NPC: https://database.turtle-wow.org/?npc=
Item: https://database.turtle-wow.org/?item=
Quest: https://database.turtle-wow.org/?quest=
Spell: https://database.turtle-wow.org/?spell=
Object: https://database.turtle-wow.org/?object=

**Expected behavior. Describe how it should work:**
I should be able to see the default skin and be able to apply the blood elf skin

**Comment by Tinyfin-github** [comment]
Greetings!

There is no issue with your character. Please install a clean client as instructed. In your screenshot you are not showing a clean client. Don't copy over WDB/WTF settings. Don't 

![image](https://user-images.githubusercontent.com/83077166/186878156-9c08aac6-b17d-48bc-9edd-c2d2b50c0bb2.png)
