### ISSUE TITLE
Felguard mana regeneration bug

### ISSUE THREAD

**Issue by balakethelock** [slowtorta/turtlewow-bug-tracker#2005]
**Please, provide a clear description what the bug is:**
The felguard summoned by the new warlock ability only regenerates 7 mana per tick. Technically it's more an oversight than a bug
**Steps to reproduce the behavior with as much detail as possible:**
1.Summon felguard pet
2. Use all its abilities to drain its mana (happens very fast cause its abilities cost too much, which is a balance problem not a bug)
3. Wait for it to regen its mana. It'll take you minutes to get mana for another Legion Strike

**IDs of affected creatures, items, quests or spells with a link to the relevant page:**

NPC: https://database.turtle-wow.org/?npc=17252

**Expected behavior. Describe how it should work:**
For context, imps regenerate 500 mana per tick. Voidwalkers are the worst at 200 mana per tick. Since the felguard is a warrior archetype like the voidwalker, it should have the same mana regen. In addition, Voidwalker abilities cost around 100 to 300 mana, not 500 to 1200. The felguard needs its mana costs reduced by 60% to be useful because currently it ooms after just one use of its abilities.

**Comment by ratkosrb** [comment]
I've reduced the mana cost of his abilities except Felstorm, but you won't be able to see the change on the tooltip until the next client patch.
