### ISSUE TITLE
Elven Legends quest fail issue

### ISSUE THREAD

**Issue by Azeron223** [slowtorta/turtlewow-bug-tracker#2006]
When completing the quest [Elven Legends](https://database.turtle-wow.org/?quest=7481) (Quest ID: 7481 & 7482) if you're grouped with other people also on the quest, it seems the quest is only completed for the person who interacts with the [Skeletal Remains of Kariel Winthalus](https://database.turtle-wow.org/?object=179544) (Object ID: 179544) while the rest of the group fails the quest.

**Expected behavior. Describe how it should work:**
Upon interacting with [Skeletal Remains of Kariel Winthalus](https://database.turtle-wow.org/?object=179544) I beleive the quest completion trigger should work for all party members close enough to the trigger location.

**Comment by redmagejoe** [comment]
Can confirm that this globally fails the quest for all other party members whenever someone inspects the skeleton. Please double check what is causing this.

**Comment by slowtorta** [comment]
https://github.com/slowtorta/turtlewow-bug-tracker/issues/3143
