### ISSUE TITLE
Glaives and Transmog

### ISSUE THREAD

**Issue by Iacov** [slowtorta/turtlewow-bug-tracker#2008]
**Please, provide a clear description what the bug is:**

**Steps to reproduce the behavior with as much detail as possible:**

1. [Sentinel's Glaive] in off-hand sheathes within the character model, and transmogging other items will render colourful results ... :
![image](https://user-images.githubusercontent.com/6597238/186908504-57feefd0-53d0-49b2-b521-f55edac46b62.png)
Image 1 on MH ^
![image](https://user-images.githubusercontent.com/6597238/186908635-c3dc2d2f-9022-442a-8319-c0ae8416df66.png)
Image 2 on OH ^

2. Transmogging and equipping so will replicate OH item model placement:
![image](https://user-images.githubusercontent.com/6597238/186908762-f3191098-0dfe-43a5-905b-6f546bc411e2.png)
![image](https://user-images.githubusercontent.com/6597238/186908812-92d78708-7cdd-4ac6-b89b-c1c8137b6a90.png)

**IDs of affected creatures, items, quests or spells with a link to the relevant page:**

Item: https://database.turtle-wow.org/?item=60752
Quest: https://database.turtle-wow.org/?quest=
Spell: https://database.turtle-wow.org/?spell=
Object: https://database.turtle-wow.org/?object=

**Expected behavior. Describe how it should work:**
Transmogged items with 60752 model should either sheath on the back, or not stab the character model :
![image](https://user-images.githubusercontent.com/6597238/186909169-15af4195-1dd8-4102-b90b-fe94bb8ff5d9.png)

If you could please look into this,

Thank you for your time and dedication,
Yours Sincerely,
Ednaryt

**Comment by slowtorta** [comment]
The transmogged models will always inherit the original model's sheath, I'm sorry, but at this point, we have no way to change it.

**Comment by slowtorta** [comment]
@jameyboor Take a look when you can.

**Comment by slowtorta** [comment]
Sadly, this bug that we're unable to fix in the any foreseeable future.
