### ISSUE TITLE
NPC: Shade of Eranikus

### ISSUE THREAD

**Issue by Sringaram** [slowtorta/turtlewow-bug-tracker#2014]
ID: https://database.turtle-wow.org/?npc=5709

This boss has the same bug it had on classic, the Thrash ability is activated every single hit, instantly deleting even tanks of the appropriate level.

**Comment by redmagejoe** [comment]
Cannot reproduce this on current version. Thrash appears to happen every 6-9 seconds now rather than on every attack. If it is a proc chance, it seems the chance is no longer so high. If it is an internal cooldown, it seems this cooldown was fixed.

Fixed.
