### ISSUE TITLE
Lorekeeper and /played

### ISSUE THREAD

**Issue by geojak** [slowtorta/turtlewow-bug-tracker#2016]
**Please, provide a clear description what the bug is:**

When I type in /played I have on my char msg over 2100 competed quests displayed. 

I do not have the lore master title

So either the title doesn't exist, or 1700 is not the required number or /played competed numbers shows is not true

**Expected behavior. Describe how it should work:**

I would have expected the lorekeeper title or a lower /played quests completed number on my char or a higher number communicated than 1700 as requirement. 

I asked this first in #support but got no response so I assume its a bug

**Comment by geojak** [comment]
Also duplicate from https://github.com/slowtorta/turtlewow-bug-tracker/issues

**Comment by jameyboor** [comment]
Fixed on next update.

**Comment by geojak** [comment]
@jameyboor next update as in wednesday sevrer restart? or next update as in 1.16.4?
because it doesnt seem fixed on this wednesday morning
