### ISSUE TITLE
wrong mount color being recieved in spellbook after using the item

### ISSUE THREAD

**Issue by Mentlegeen** [slowtorta/turtlewow-bug-tracker#2018]
After buying a brown kodo and using it, i recieved a spell in spellbook 'gray kodo', used it - it was a grey kodo indeed, brown one was lost somewhere

how to replicate

1. be a lvl 40 balance druid in moonkin form
2. buy riding at lvl 40, then go to the other trainer to buy brown kodo and pick up plainsrunning q
3. use brown kodo, recieve grey kodo in your spellbook

**IDs of affected creatures, items, quests or spells with a link to the relevant page:**

NPC: https://database.turtle-wow.org/?npc=3685
Item: https://database.turtle-wow.org/?item=15290
Quest: https://database.turtle-wow.org/?quest=
Spell: https://database.turtle-wow.org/?spell=
Object: https://database.turtle-wow.org/?object=

**Expected behavior. Describe how it should work:**
it should give me the brown kodo spell in my spellbook
![bugged kodo](https://user-images.githubusercontent.com/88183993/187017873-7ea821a7-a9cc-48dd-b605-765899c01f61.png)

**Comment by slowtorta** [comment]
This will be fixed in the next update. The item name was misleading, you'll have to request help from a GM to exchange your mount in-game. The item you look for is this one: https://database.turtle-wow.org/?item=15290
