### ISSUE TITLE
Elemental Weapons Talent (Shaman)

### ISSUE THREAD

**Issue by Melphoone** [slowtorta/turtlewow-bug-tracker#2019]
**Please, provide a clear description what the bug is:**
The Elemental Weapons Talent does not affect the Flametongue Weapon Effect (Works fine on Rockbiter, Windfury, Frostbrand)

**Steps to reproduce the behavior with as much detail as possible:**

1. Respec, spend 0-3 points on the Talent
2. Watch the Damage Scaling on an Enemy/Dummy
3. There is no change in dmg, regardless how many Points are skilled

**IDs of affected creatures, items, quests or spells with a link to the relevant page:**

Spell: https://database.turtle-wow.org/?spell=16266
(see also Rank 2 or 3)

**Expected behavior. Describe how it should work:**
As told in the Tooltip, the damage of Flametongue Weapon should be raised by 5-15% depending on points spend.

**Comment by ratkosrb** [comment]
Because it's fixed and will go live in the next update. We don't wait for fixes to be put on the live server for them to be closed, they are closed as soon as there is a solution found internally.
