### ISSUE TITLE
Projectile/Sound Display Issue

### ISSUE THREAD

**Issue by AyleeJenn** [slowtorta/turtlewow-bug-tracker#202]
**Please, provide a clear description what the bug is:**
If someone who is situated behind "your camera" (i.E. Off-Camera) fires a projectile, a wand or a spell, you will not see the projectile unless you turn your camera. You may (or may not) hear it, but you won't see it.
This happens consistently and is easy to reproduce.

**Steps to reproduce the behavior with as much detail as possible:**

1. Find someone who can fire projectiles and walk in front of them so they are behind "your camera" and cannot be seen as you face forward (with them behind you or off-camera far enough)
2. Find a target and have your enlisted help attack it with anything that fire projectiles. (Wands, ranged weapons, spells, etc)
3. Observe as you will not see projectiles.
4. Interestingly, this sometimes happens with sounds as well. You can find an npc, a smith for example, and when you turn your camera so they are off-camera, you will suddenly stop hearing the smithing sounds. As soon as you turn your camera to look at the smith again, the sounds will resume. Very odd.

**IDs of affected creatures, items, quests or spells with a link to the relevant page:**

NPC: https://database.turtle-wow.org/?npc= N/A
Item: https://database.turtle-wow.org/?item= N/A
Quest: https://database.turtle-wow.org/?quest= N/A
Spell: https://database.turtle-wow.org/?spell= N/A
Object: https://database.turtle-wow.org/?object= N/A

**Expected behavior. Describe how it should work:**
What -should- be happening is that sounds as well as projectiles should be displaying and playing even if they are "off-camera".

**Comment by Nolin7777** [comment]
Most likely a client issue, I assume.

**Comment by slowtorta** [comment]
Moving this issue to the internal tracker for client-related problems, thank you.
