### ISSUE TITLE
Flametongue Weapon Procc Issue

### ISSUE THREAD

**Issue by Melphoone** [slowtorta/turtlewow-bug-tracker#2020]
**Please, provide a clear description what the bug is:**
Flametongue Weapon does not Procc the Elemental Devastation Talent, although it proccs similar Effects which require Spell hits/crits,

**Steps to reproduce the behavior with as much detail as possible:**

1. Activate Flametongue Weapon, Skill Elemental Devastation ( 1-3 Points)
2. Land a Critical hit with Flametongue
3. nothing Happens

**IDs of affected creatures, items, quests or spells with a link to the relevant page:**

Spell: https://database.turtle-wow.org/?spell=8024
Talent: https://database.turtle-wow.org/?spell=30160

**Expected behavior. Describe how it should work:**
Critical Hits from Flametounge Weapon should also activate the Elemental devastation Procc.

**Comment by Kuz-Shaman** [comment]
This is a big issue, it severly hinders my playstyle. Any update on this from a Dev please would be greatly apreciated :)

**Comment by slowtorta** [comment]
https://www.wowhead.com/classic/spell=29180/elemental-devastation#comments
Working as intended.
