### ISSUE TITLE
Flametongue Weapon Issue 

### ISSUE THREAD

**Issue by Melphoone** [slowtorta/turtlewow-bug-tracker#2021]
**Please, provide a clear description what the bug is:**
Flametongue Weapon Effect is not applied to Every Waponswing as described in the Tooltip.

**Steps to reproduce the behavior with as much detail as possible:**

1. Activate Flametongue Weapon, attack Enemy/Dummy
2. Watch the combat log
3. occassionally no Flametongue effect is applied to the hit of the weaponswing.
(there is no sign of resistance either, just not applied to the hit)

**IDs of affected creatures, items, quests or spells with a link to the relevant page:**

Spell: https://database.turtle-wow.org/?spell=8024#see-also-ability

**Expected behavior. Describe how it should work:**
Flametongue Weapon should be cast on every autohit that hit´s the enemy

**Comment by ratkosrb** [comment]
I can't reproduce your issue. The only time it doesn't trigger is if the attack misses or is parried/dodged.

**Comment by Velite12** [comment]
Can you show a picture of the combat log where you activate Flametongue Weapon and then auto attack?

**Comment by Melphoone** [comment]
https://imgur.com/a/59hVlx1
