### ISSUE TITLE
Gnome rogue Escape Artist Issue

### ISSUE THREAD

**Issue by turtlewowrookie** [slowtorta/turtlewow-bug-tracker#2022]
**Please, provide a clear description what the bug is:**

**Steps to reproduce the behavior with as much detail as possible:**

1.Travel to Teldrassil as Gnome Rogue . From Shadowglen to Dolanaar are spiders named "Webwood Lurkers" lv5-6 .
2. Let "Webwood Lurker" to use the ability "Web" on you . It casts net that hold you in place without able to move for several seconds .
3. Cast "Escape Artist" ( Gnome-only racial ) . Look at combat log . While "Escape Artist" is succesfully casted , you are still holded in place from "Web" ability of spiders . 
**IDs of affected creatures, items, quests or spells with a link to the relevant page:**

NPC: https://database.turtle-wow.org/?npc=
Item: https://database.turtle-wow.org/?item=
Quest: https://database.turtle-wow.org/?quest=
Spell: https://database.turtle-wow.org/?spell=
Object: https://database.turtle-wow.org/?object=

**Expected behavior. Describe how it should work:**
According to "Escape Artist" description , you should "Escape the effects of ANY immobilization or movemend speed reduction effect ." Clearly this not work as it should , it still hold me in place with the net visible on me for full duration of spider's "Web" ability and i cannot move until the "Web" expires .

**Comment by jameyboor** [comment]
I can't reproduce this. Once I get hit by a spider's net casting Escape Artist sets me free.
