### ISSUE TITLE
Some quests need adjustment of quest objectives respawn timers

### ISSUE THREAD

**Issue by RussianE39** [slowtorta/turtlewow-bug-tracker#2023]
**Please, provide a clear description what the bug is:**
A few quests need respawn timer adjustment, with current population default 6 or 10minutes timer is not viable at all.
Here is the list I found so far:
1. In search of corruption ( QuestID 40192). Adjust respawn timer for quest items 60261(from Object 2010838), 60263(from Object 2010839) and NPC (NPC ID 60469). It is around 6 minutes currently, so its not viable with current population.
2. Bingles' Missing Supplies (QuestID 2038) - 1 tool has instant respawn, 3 other are ~6 min. Should be adjusted.
3. Saltspittle Raiders (QuestID 40230) - Greenblade Book (ItemID 60312 from Object 2010845) respawn timer not viable for current population, should be adjusted too.

**Comment by cyaohiri** [comment]
It seems like respawn time for all items for #2146 is now 5 minutes.
