### ISSUE TITLE
Lightening shield and shadowguard both not working

### ISSUE THREAD

**Issue by JaceEverwood** [slowtorta/turtlewow-bug-tracker#2024]
**Please, provide a clear description what the bug is:**
Lightening shield and shadowguard both won't trigger by ranged attack and spell attack while under shield effect

**Steps to reproduce the behavior with as much detail as possible:**

1. Both I(priest) and Shaman friend went to tanaris these out the above skill by applying shield+ shadowguard or lightening shield effect.
2.  tag the mob axe thrower(ranged attack) and firecaller(spell attack; fireball).
3.  both lightning shield and shadowguard will not get triggered by ranged attack and spell damage before the shielding effect is expired. 
![image](https://user-images.githubusercontent.com/19348079/187028800-16725745-cef1-42a0-927f-a6fbd51ce748.png)

**IDs of affected creatures, items, quests or spells with a link to the relevant page:**

NPC: https://database.turtle-wow.org/?npc=
Item: https://database.turtle-wow.org/?item=
Quest: https://database.turtle-wow.org/?quest=
Spell: https://database.turtle-wow.org/?spell=
Object: https://database.turtle-wow.org/?object=

**Expected behavior. Describe how it should work:**
it should work consistently,  both lightening shield and Shadowguard will get trigger by melee attack while under shielding effect and it should behave the same facing ranged attack/spell attack

**Comment by Zeyla-TW** [comment]
Charge-reactive abilities like lightning shield, shadowguard and inner fire have never consumed a charge when the incoming attack is fully absorbed. If you can find evidence to the contrary then we can discuss it further, but for now this is working as intended.
