### ISSUE TITLE
The Dunemaul Compound can't complete quest

### ISSUE THREAD

**Issue by mybrid** [slowtorta/turtlewow-bug-tracker#2025]
(W/X/R Raylen) The Enforcers only spawn in two places, one in the camp and one in the ruins. They are never replacing any Brutes, Orgres, Mages or Warlocks. They are only replacing these two dedicated Enforcers. This bug was closed four days ago but still persists.  I suppose one could complete this quest but given the server now as more population it is not realistic and I'm abandoning the quest. 

**Steps to reproduce the behavior with as much detail as possible:**

1. Quest: Dunemaul Compound
2. Dunemaul Compound has only one Enforcer that does respawn as Enforcer. 
3. No other Ogre respawns as Enforcer
4. There is one other Enforcer in the ruins. 

**IDs of affected creatures, items, quests or spells with a link to the relevant page:**

NPC: https://database.turtle-wow.org/?npc=
Item: https://database.turtle-wow.org/?item=
Quest: https://database.turtle-wow.org/?quest=
Spell: https://database.turtle-wow.org/?spell=
Object: https://database.turtle-wow.org/?object=

**Expected behavior. Describe how it should work:**

**Comment by adiosamigos** [comment]
From my experience as someone who completed the quest about a week ago, Enforcers are way to rare compared to the other ogre types, yet they have a chance to replace other ogres, so you need to keep killing ogres untll Enforcers spawn instead of them. Agreed, that spawn rate should be adjusted.
