### ISSUE TITLE
Gnome rogue Escape Artist Issue with VIDEO proof .

### ISSUE THREAD

**Issue by turtlewowrookie** [slowtorta/turtlewow-bug-tracker#2029]
**Please, provide a clear description what the bug is:**

https://sendvid.com/kacy18ft

**Steps to reproduce the behavior with as much detail as possible:**

1.1.Travel to Teldrassil as Gnome Rogue . From Shadowglen to Dolanaar are spiders named "Webwood Lurkers" lv5-6 .
2. Let "Webwood Lurker" to use the ability "Web" on you . It casts net that hold you in place without able to move for several seconds .
3. Cast "Escape Artist" ( Gnome-only racial ) . Look at combat log . While "Escape Artist" is succesfully casted , you are still holded in place from "Web" ability of spiders.

**IDs of affected creatures, items, quests or spells with a link to the relevant page:**

NPC: https://database.turtle-wow.org/?npc=
Item: https://database.turtle-wow.org/?item=
Quest: https://database.turtle-wow.org/?quest=
Spell: https://database.turtle-wow.org/?spell=
Object: https://database.turtle-wow.org/?object=

**Expected behavior. Describe how it should work:**
According to "Escape Artist" description , you should "Escape the effects of ANY immobilization or movemend speed reduction effect ." Clearly this not work as it should , it still hold me in place with the net visible on me for full duration of spider's "Web" ability and i cannot move until the "Web" expires .

P.S. @jameyboor i did reproduced for you  and i will check it regularly to see if is fixed , do not close issue until fix it .

**Comment by redmagejoe** [comment]
This issue still persists.

**Comment by 0Moon01** [comment]
This was an oversight on the original game's developers. Some Web spells doesn't have their Mechanic flag set to snare as they should. While this isn't a Turtle-specific issue, we will correct anyway.

**Comment by ratkosrb** [comment]
This appears to be already fixed.
