### ISSUE TITLE
Paladin's Holy Light lower ranks are not being penalized by the level 20 spell penalty

### ISSUE THREAD

**Issue by faralynn** [slowtorta/turtlewow-bug-tracker#203]
Seems there's lots of bugs lately with spell coefficients and the like with some some of the recent changes. This time it's with Paladin's Holy Light ranks 1 2 and 3.

**Steps to reproduce the behavior with as much detail as possible:**

1. Cast a low level Holy Light spell.
2. Observe it healing for nearly 3x more than it should be.

**IDs of affected creatures, items, quests or spells with a link to the relevant page:**
https://database.turtle-wow.org/?spell=635
https://database.turtle-wow.org/?spell=639
https://database.turtle-wow.org/?spell=647

**Expected behavior. Describe how it should work:**
These spells are learned prior to level 20 and should be effected by the level 20 penalty:
https://wowwiki-archive.fandom.com/wiki/Downranking#Level_20_penalty

**How the spells should heal with 707 Healing Power and my talents on Classic using a simulator which uses known formulas:**
![image](https://user-images.githubusercontent.com/2092314/127421730-0502d3cb-5954-4e20-b972-5643356a2d34.png)

**And this is how much Rank 1 Holy Light is healing for right now in game with 707 Healing Power, same talents used in simulator:**
![image](https://user-images.githubusercontent.com/2092314/127421960-67b32be3-5713-4c4d-a5f5-7a4a506e7048.png)

**Comment by Nolin7777** [comment]
Possible fix will be applied on next maintenance.
Please re-open in case issue still exists.
