### ISSUE TITLE
Devotion Aura and Stoneskin Totem

### ISSUE THREAD

**Issue by andrethespaniard** [slowtorta/turtlewow-bug-tracker#2030]
**Please, provide a clear description what the bug is:**
While on a low-level dungeon run in Shadowfang Keep I noticed that my devotion aura was getting turned off due to the Shaman's Stoneskin Totem. I was a level 27 High Elf Paladin with Rank 3 Devotion Aura and the Shaman was a level 26 Troll Shaman with either level 2 or level 3 Stoneskin Totem.

**Steps to reproduce the behavior with as much detail as possible:**

1. Turn on Rank 3 Devotion Aura.
2. Have Shaman place a Stoneskin Totem (level 2 or 3).
3. Devotion Aura shuts off instead of stacking with it and is unable to be turned back on because it says Stoneskin Totem is a greater spell.

**IDs of affected creatures, items, quests or spells with a link to the relevant page:**

https://database.turtle-wow.org/?object=2010254
https://database.turtle-wow.org/?npc=5919

**Expected behavior. Describe how it should work:**
Devotion Aura should stack with Stoneskin Totem.. right?

**Comment by geojak** [comment]
https://forum.turtle-wow.org/viewtopic.php?f=14&t=3931

**Comment by Velite12** [comment]
https://github.com/slowtorta/turtlewow-bug-tracker/issues/15

https://github.com/vmangos/core/pull/1358

**Comment by slowtorta** [comment]
This i s a suggestion and it's being discussed on our forums right now: https://forum.turtle-wow.org/viewtopic.php?f=2&t=4232
