### ISSUE TITLE
NPC: Isle of Lapidis/Gilijim mobs

### ISSUE THREAD

**Issue by Sringaram** [slowtorta/turtlewow-bug-tracker#2031]
It seems like the majority of mobs in there have messed up loot tables.

One example is https://database.turtle-wow.org/?npc=91965 which drops Un'Goro soil (shared loot table with Un'Goro lurkers?). The serpents seem to drop elemental fire and some mobs do not drop anything other than their quest items.

Mobs also seem to either miss skills entirely (some pirates do not have any).

https://database.turtle-wow.org/?npc=91965 in question also uses roots which still go off even when interrupted.

I guess this report is a general call to review the fauna of those islands.

**Comment by geojak** [comment]
Yea those islands mobs are a mess. The islands could use a sorrow check. Adding abilities and loot. Nagas also have no abilities last time I checked. It feels unfinished

**Comment by Sringaram** [comment]
Ah yes, the mystic murlocs don't cast any spells either.

**Comment by Sringaram** [comment]
Another issue is that level 50+ mobs are dropping level 4x loot.

**Comment by slowtorta** [comment]
Duplicate for: https://github.com/slowtorta/turtlewow-bug-tracker/issues/1508
