### ISSUE TITLE
Server instability and crashes in naxxramas

### ISSUE THREAD

**Issue by afizzler** [slowtorta/turtlewow-bug-tracker#2032]
It did get addressed before, but there are still consistent lag spikes and instability in which cause gameplay to be less desirable. It would be nice if devs looked into more crash logs from naxxramas and other areas to solve it. The devs told me to put it here since it will not be addressed in their discord server.

**Comment by Tinyfin-github** [comment]
For crash issue: Please DM  Torta#2728 on discord with your crash.txt and crash. dmp

The lag spikes are getting looked.
