### ISSUE TITLE
Dwarf male animation bug

### ISSUE THREAD

**Issue by jendryk** [slowtorta/turtlewow-bug-tracker#2035]
**Please, provide a clear description what the bug is:** The Dwarf male doesn't have an interaction animation.

**Steps to reproduce the behavior with as much detail as possible:**

1. Find an object with cogwheel icon.
2. Click it.
3. Dwarf should kneel and move hands, but just stands.

**Expected behavior. Describe how it should work:** Dwarf should kneel and move hands while interacting with object like races.

![WoWScrnShot_082922_204943](https://user-images.githubusercontent.com/7814954/187282810-7f2f7df5-80f6-4fcf-8e13-777770b10dd7.jpg)

![WoWScrnShot_082922_204945](https://user-images.githubusercontent.com/7814954/187282803-8f8aa31c-1c1b-49c1-9d1d-cdbaae5b055d.jpg)

**Comment by adiosamigos** [comment]
I think the looting animation should be cast in the end of chanelling when loot window pops up -- this is how I see it for my orc and how I remember it to work in classic retail wow

**Comment by jendryk** [comment]
I don't mean the looting animation... I mean the "interacting" animation during channel, character should kneel and move hands and after casting he should still be kneeling and "reaching" for something (looting animation)

**Comment by slowtorta** [comment]
![image](https://user-images.githubusercontent.com/66763404/197291471-15b4098b-da5b-4334-a4b1-3b3bb2b6ad99.png)

This isn't related to the model but to the object type. The animation is here. :)
