### ISSUE TITLE
Wind serpent pets with bugged attack sounds

### ISSUE THREAD

**Issue by Baroli1** [slowtorta/turtlewow-bug-tracker#2037]
**Please, provide a clear description what the bug is:**

The hunter wind serpent pet has bugged sound when it comes to its attack: Lightning Breath.

**Steps to reproduce the behavior with as much detail as possible:**

1. Go to a training dummy.
2. Have the wind serpent attack it with disabled Lightning Breath attack.
3. Notice the irregular auto attack sounds, as they should be.
4. Toggle Lightning Breath
5. Notice how even with depleted focus it still triggers the sound of the attack, making it loop the hissing sound permanently.

**IDs of affected creatures, items, quests or spells with a link to the relevant page:**

NPC: https://database.turtle-wow.org/?npc=4117

**Expected behavior. Describe how it should work:**

The hissing sound connected to the Lightning Breath attack should only occur when the attack actually goes off. Not every time it checks if it has enough focus or tries to queue up the attack. Its pretty annoying and kind of ruins the pet because at some point the holder will go mad and probably end up strangling it.

**Comment by slowtorta** [comment]
This is a client issue we're unable to resolve fully. All I could do for now is to make this sound less loud in 1.16.4.
