### ISSUE TITLE
Druid Bear "Bash" ability duration is way too low.

### ISSUE THREAD

**Issue by Cplantijn** [slowtorta/turtlewow-bug-tracker#2038]
**Please, provide a clear description what the bug is:**
Using Bash Rank 1 as a bear druid only lasts at most 1 second. Even if your druid character is talented in increased bash durations, actually bashing a target will at most last 1 second. Sometimes even under .5s. This is for same-level PvE mobs of all kinds, and there are no other DRs on the mob when bash is done.

**Steps to reproduce the behavior with as much detail as possible:**

1. Play as a druid, in bear form, with Bash
2. Use ability on any similar level PvE mob.
3. Observe the incredibly low duration

**IDs of affected creatures, items, quests or spells with a link to the relevant page:**

NPC: ANY
Item: N/A
Quest: N/A
Spell: https://database.turtle-wow.org/?spell=5211
Object: N/A

**Expected behavior. Describe how it should work:**
Bash should last 2 seconds untalented, And 3 seconds when talented 2/2 "Brutal Impact"

**Comment by redmagejoe** [comment]
Cannot reproduce this on current version. Bash duration appears to be exactly as it should be.

Fixed.
