### ISSUE TITLE
Various spells learned under level 20 do not have the penalty for the coefficient

### ISSUE THREAD

**Issue by Velite12** [slowtorta/turtlewow-bug-tracker#204]
As of the latest update, many spells learned under level 20 do not have the penalty to it's coefficient for when the spell is learned under level 20 and are thus scaling as much as the ranks learned after level 20. To my knowledge, this is affecting:

Seal of righteousness, Holy light, Regrowth, Flametongue weapon

It seems the latest update removed the penalty. There are possibly more spells that have this issue but I do not have the characters to test them. The other caster classes should be investigated.

As an example, here is holy light rank 1, with 969 healing power + 400 from blessing of light. It should be healing for much less

![image](https://user-images.githubusercontent.com/45871932/127423048-016c18a4-7a64-4918-bb5a-f67fae70d004.png)
![image](https://user-images.githubusercontent.com/45871932/127423056-e4d942da-49f1-40b5-98ff-c083f1fe0ea1.png)

**Comment by Nolin7777** [comment]
Possible fix will be applied on next maintenance.
Please re-open in case issue still exists.
