### ISSUE TITLE
Quest Donning the Red Flag bugged, [Illusion: Scarlet Crusades] does not work

### ISSUE THREAD

**Issue by lokhengchau** [slowtorta/turtlewow-bug-tracker#2041]
**Please, provide a clear description what the bug is:**

In the quest, you are given the item [Illusion: Scarlet Crusades] to alter your appearance. However the item is broken. Using it won't change your appearance and will still aggro the mobs, however when trying to mount up it will say you are in shapeshift form. Entering AV while bugged will turn you into a cube.

**Steps to reproduce the behavior with as much detail as possible:**

1. Use [Illusion: Scarlet Crusade] outside of Tyr's Hand.
2. Does not shapeshift and still aggro mobs.
3. The game thinks you are in shapeshift form, cannot mount up.

**IDs of affected creatures, items, quests or spells with a link to the relevant page:**

Item: https://database.turtle-wow.org/?item=53003
Quest: https://database.turtle-wow.org/?quest=80709

**Expected behavior. Describe how it should work:**
The item correctly shapeshifts you into one of scarlet crusades.

**Comment by Khanz0** [comment]
I reported it time a go. They told me it wil be fixed in Next update

**Comment by geojak** [comment]
still buggeda s of today

**Comment by geojak** [comment]
interstingly, it says now i am shapeshifted and i cant mount up. thought i see no illusion, no buff, and i am also not firendly to the scarlets

**Comment by geojak** [comment]
and after i used my hs this happened

![WoWScrnShot_090922_164031](https://user-images.githubusercontent.com/25199983/189376190-88ed6421-e794-4d87-8395-f2a752b41f48.jpg)

**Comment by BloodRaven0** [comment]
+1
The horde version of the item "Rotten Apple" works perfectly, and doesn't even have charges. when I opened a ticket to have a gm switch my useless scroll with an apple, they told me that "this item is for a different quest". Well duh, it's for the same quest, just for the horde side, and the item is literally identical.
