### ISSUE TITLE
Respawn at corpse without being teleported to the graveyard

### ISSUE THREAD

**Issue by ZambieFizz** [slowtorta/turtlewow-bug-tracker#2044]
**Please, provide a clear description what the bug is:**
If you preform the steps below, your ghost will spawn at your corpse instead of at the graveyard. It is very easy, I can reproduce it on command.
**Steps to reproduce the behavior with as much detail as possible:**

1.Die in any way 
2. Click Release Spirit extremely fast after dying, like, as fast as possible.
3. Wait for respawn timer to end
4. Respawn

**Expected behavior. Describe how it should work:**
Your ghost should instantly appear at your corpse without ever needing to run to it. I have done it multiple times in a row, mostly on accident.

**Comment by redmagejoe** [comment]
This is likely a side effect of something I have noticed only on Turtle, in that when you release, you are temporarily above your corpse in the spirit realm before you are teleported to the nearest graveyard. This seems like an improper order of events. My understanding is that your ghost should not even spawn until its spawn location has been set to the nearest graveyard.

**Comment by ratkosrb** [comment]
Can you record a video of the bug happening and not getting teleported to the graveyard? I can't reproduce the issue.
