### ISSUE TITLE
Chronoboon Loop

### ISSUE THREAD

**Issue by moppingaround** [slowtorta/turtlewow-bug-tracker#2046]
I went to a Dire Maul Tribute run to get World Buffs. As soon as I got my last buff applied, I used my Chronoboon. It said on my in-game message that I had received the Supercharged Chronoboon in my inventory but when I looked into my inventory, nothing was there and my buffs were still active. After this, I decided to write a ticket about my incident. Because it was taking awhile, I had decided to take a different approach and redo the buffs and run as fast as I can to Chromie. When I got to Chromie, I bought a chronoboon to store my buffs. Unfortunately, it did it again. It uses the Chronoboon and doesn't leave me a supercharged one in my inventory. In addition to this it displayed a different message in where it shows the buffs auto-restoring after each use. 

**Steps to reproduce the behavior with as much detail as possible:**

1. After a long DMT run, use the Chronoboon to store your buff. 

![Chronoboon Loop](https://user-images.githubusercontent.com/112610466/187849413-1efe7fc7-a7e2-4e17-a411-1934d0b7d454.png)

**Comment by slowtorta** [comment]
Sorry, we were unable to reproduce this.
