### ISSUE TITLE
Invisibility from potions break upon starting to cast a spell

### ISSUE THREAD

**Issue by Zolcev** [slowtorta/turtlewow-bug-tracker#2049]
**Please, provide a clear description what the bug is:**

Invisibility from both invisibility potions break when you start casting a spell, not when you finish like it is suposed to. Invisibility from gnomish cloaking device is working as intended.

**Steps to reproduce the behavior with as much detail as possible:**

1. Use an invisibility potion or a lesser invisibility potion
2.  Cast a spell, it will break invisibility

**IDs of affected creatures, items, quests or spells with a link to the relevant page:**

https://database.turtle-wow.org/?item=9172      (item ID 17898)
https://database.turtle-wow.org/?item=3823      (item ID 2354)

**Expected behavior. Describe how it should work:**

Invisibility should break upon finishing a cast, as it can be seen at the minute 1:10 of the following video (and in numerous other parts of the same video):

https://www.youtube.com/watch?v=C6kycQeUkY8

**Comment by jameyboor** [comment]
This is intended. See
https://wowwiki-archive.fandom.com/wiki/Patch_1.10.0

> Stealth and Invisibility effects will now be canceled at the beginning of an action (spellcast, ability use etc...), rather than at the completion of the action.
