### ISSUE TITLE
Paladin's healing Libram bonuses are being applied erroneously as a flat bonus rather than being formulated properly with the spells cast time, level penalty and coefficient

### ISSUE THREAD

**Issue by faralynn** [slowtorta/turtlewow-bug-tracker#205]
**Please, provide a clear description what the bug is:**
Just as the title says here. The way vMangos is factoring in Paladin healing Libram's right now for Flash of Light is not proper.

At the moment, the bonuses of the following items:
![image](https://user-images.githubusercontent.com/2092314/127423197-85562971-b91d-4676-b164-76944aa61b81.png)

![image](https://user-images.githubusercontent.com/2092314/127423217-9e80ce04-8041-4b4d-822f-3792e13f2660.png)

Are being applied AFTER the spells effective coefficient is being formulated as a flat bonus. Essentially bypassing the cast time penalty entirely.

How the bonuses of those items should be factored is the bonus should be added to the players overall healing power then be factored with both cast time penalty and the level 20 penalty if applicable. 

The coefficient of Flash of Light is static amongst all ranks: 0.4286
Using my Paladin's 707 healing power as an example, the healing done of a rank 6 Flash of Light without Libram should be **0.4286 * 707 + (Base heal of spell)**  which works out to 709 healing done on average. about right:
![image](https://user-images.githubusercontent.com/2092314/127425491-789a8ac5-37ad-416e-953a-1eed5fe11803.png)
_Four casts of Flash of Light (rank 6) casted without any healing Libram._

Now if I do those casts with the Libram of Divinity equipped:
![image](https://user-images.githubusercontent.com/2092314/127425672-e90b6505-57cd-47fb-9ac2-07ef02a39f68.png)
...... As you can see, yeah. it's rather broken. This is effectively, because it isn't being penalized by the cast time penalty at all, an item that gives +106 Healing Power for Flash of Light that's obtainable right from Scholomance.

**Proof that it should work otherwise than how it works now:**
*Screenscraped directly from WoWhead, posted in 2006*
![image](https://user-images.githubusercontent.com/2092314/127426123-15d17d6d-840f-4c77-9bca-cb46ea130ded.png)

**IDs of affected creatures, items, quests or spells with a link to the relevant page:**

https://database.turtle-wow.org/?item=23201
https://database.turtle-wow.org/?item=23006

(All ranks)
https://database.turtle-wow.org/?search=flash+of+light

**Comment by Velite12** [comment]
Flash of light has no level penalty since it's first learned at level 20

**Comment by faralynn** [comment]
> 
> 
> Flash of light has no level penalty since it's first learned at level 20

Level penalty was only mentioned because I suspect other items that contribute to a particular spells healing or damage done are like this as well. 

It's clearly the cast time penalty that isn't being applied in this case.

**Comment by Nolin7777** [comment]
Possible fix will be applied on next maintenance.
Please re-open in case issue still exists.
