### ISSUE TITLE
The Balance of Light and Shadow Bugged

### ISSUE THREAD

**Issue by elfpriestess** [slowtorta/turtlewow-bug-tracker#2051]
**Please, provide a clear description what the bug is:**
The Priest quest the Balance of Light and Shadow which is critical for obtaining Benediction/Anathema is bugged/overtuned, making it currently impossible for newer Priests to complete their class quest. This has been tested with two other priests and numerous issues have been found. The first is that the Cleaner will spawn even when he shouldn't. In original vanilla as well as Classic WoW it was completely allowed for a priest to bring another priest friend and a druid to make the quest a bit easier, there are forum posts dating back to 2005 confirming this as well as videos on YouTube 
https://www.youtube.com/watch?v=CsupFBgRRQE&ab_channel=Lemur%27sCorner < Just an example of the quest working correctly. We attempted the druid strategy and two priest strategy and both times the Cleaner instantly spawned and attacked us, this is not supposed to happen when the quest is working correctly, at one point 2 Cleaners spawned at the exact same time which I have never seen happen before. Even when attempting to solo the quest, it is impossible as the ground skeletons spawn endlessly when there should only be one group per wave, I had a friend who completed their Benediction quest a few months earlier attempt it on my Priest and they confirmed it was significantly more difficult than when they attempted it and the amount of skeletons spawning was overwhelming. I understand the quest is meant to be challenging but as it stands it's impossible and very frustrating. The pathfinding of the peasants is also bugged, causing them to walk into the sides of the cliffs. 
**Steps to reproduce the behavior with as much detail as possible:**

1. Begin the quest with anyone or anything near you (druid strat, second priest strat, mechanical yeti, Barov peasant caller) The quest will either instantly fail or the Cleaner(s) will spawn and kill you. This is not supposed to happen in the vanilla client, you were allowed limited assistance from items/friends in the original client
2. Attempt the quest alone, you will be overwhelmed by waves of skeletons spawning too quickly and too many by the third wave even with plenty of consumables/pots/downranked spells etc
3. Trying to start the quest at all has a chance to instantly fail and spawn the Cleaner to kill you even if you are completely alone

**IDs of affected creatures, items, quests or spells with a link to the relevant page:**

NPC: https://database.turtle-wow.org/?npc=14503 , https://database.turtle-wow.org/?npc=14485 , https://database.turtle-wow.org/?npc=14484 , https://database.turtle-wow.org/?npc=14486
Item: https://database.turtle-wow.org/?item=15778 , https://database.turtle-wow.org/?item=14023
Quest: https://database.turtle-wow.org/?quest=7622
Spell: 
Object: 

**Expected behavior. Describe how it should work:**

The Cleaner should NOT spawn solely because there are other players in the vicinity, only if they intervene directly with the player currently on the quest. A druid is allowed to stand still with thorns to tank the skeletons at the entrance of the cave if needed, and a second priest with the Eye of Divinity can offer heals so long as they don't move and don't interact with the player on the quest, assistance items like mechanical yeti and Barov Peasant Caller also shouldn't spawn the Cleaner or fail the quest, these were permitted in Vanilla. Scourge Footsoldiers should only spawn in a single group ONCE per wave, not constantly pouring out every few seconds. Plagued/Injured Peasants should walk in the center of the road and not stray off near the cliffside making it more difficult to track them.

**Comment by Doctorbeefy** [comment]
I can confirm both the issues exist with the skells spawning way too often and the peasants not walking correctly.

**Comment by cawilliamson** [comment]
Just had the EXACT same issues on my end.

I actually completed the quest successffully *scraped it!* and it still marked as Failed. Guess what? GMs told me to raise a ticket here.

What a surprise - there already IS a ticket here being completely ignored.

**Comment by cawilliamson** [comment]
@ratkosrb "Completed" in what sense? Has this been resolved? If so, how?

**Comment by ratkosrb** [comment]
The Cleaner will only spawn when another player is moving or healing the mobs, instead of constantly scanning the area for any player. The archer damage has been reduced to the blizzlike amount.

**Comment by cawilliamson** [comment]
@ratkosrb Awesome - can I check: when will that fix go live? Already life or on the next server reboot?

**Comment by ratkosrb** [comment]
Whenever the server gets updated. The change is not live currently.
