### ISSUE TITLE
ONY and ZG bug   SQUAD RAID

### ISSUE THREAD

**Issue by Cru313** [slowtorta/turtlewow-bug-tracker#2052]
**Please, provide a clear description what the bug is:**

**Steps to reproduce the behavior with as much detail as possible:** SQUAD raid night

1.ony dropped from 66-33% health skipping phase 2
2. jindo in zg had shades that could not be targeted
3. spider boss had unlimited rage on poinsin and out mages were max range. also resisted all warrior tank tuants

**IDs of affected creatures, items, quests or spells with a link to the relevant page:**

NPC: https://database.turtle-wow.org/?npc=
Item: https://database.turtle-wow.org/?item=
Quest: https://database.turtle-wow.org/?quest=
Spell: https://database.turtle-wow.org/?spell=
Object: https://database.turtle-wow.org/?object=

**Expected behavior. Describe how it should work:**

**Comment by Gurky-Turtle** [comment]
Closing this as we have not had this issue in forever. 

Sorry @Cru313

**Comment by Cru313** [comment]
Sounds good

Get Outlook for iOS<https://aka.ms/o0ukef>
________________________________
