### ISSUE TITLE
Hakkari Breastplate and Hakkari Shroud  should only be obtainable from the secret of the temple reward box

### ISSUE THREAD

**Issue by Tinyfin-github** [slowtorta/turtlewow-bug-tracker#2054]
Hakkari Breastplate and Hakkari Shroud  should only be obtainable from the secret of the temple reward box. You should not be able to get them from mobs or steel boxes

https://classic.wowhead.com/item=10773/hakkari-urn#reward-from-q

https://classic.wowhead.com/item=10781/hakkari-breastplate#contained-in-item
https://database.turtle-wow.org/?item=10781#contained-in-item

https://database.turtle-wow.org/?item=10782#dropped-by
https://classic.wowhead.com/item=10782/hakkari-shroud

https://database.turtle-wow.org/?item=4637#contains:150-12+1
https://classic.wowhead.com/item=4637/steel-lockbox#contains;150

**Comment by Steevo2** [comment]
Just to check, is this being removed from twinks that already have it?

**Comment by GrenderG** [comment]
As far as I know this wasn't fixed in retail until WotLk, I might be wrong though.
