### ISSUE TITLE
Hakkari Urn items in regular box table

### ISSUE THREAD

**Issue by Steevo2** [slowtorta/turtlewow-bug-tracker#2055]
Quest rewards from the sunken temple quest box are available in steel lockboxes. This has allowed twink Nexor to be basically unkillable in lvl 10-19 WSG, dragging games out over an hour. You can see that this happened here https://armory.turtle-wow.org/#!/character/Nexor . He says the source was steel lock box, but regardless, these rather need a lvl requirement added to them.

**Comment by Tinyfin-github** [comment]
Duplicate of https://github.com/slowtorta/turtlewow-bug-tracker/issues/2054
