### ISSUE TITLE
Quest Attack from the inside NPC don't give the item quest

### ISSUE THREAD

**Issue by Rainwors** [slowtorta/turtlewow-bug-tracker#2057]
**Please, provide a clear description what the bug is:**

Name quest: Attack from the inside
Link quest: https://vanilla-twinhead.twinstar.cz/?quest=40099
Location quest giver: Between Silverpine forest and Upperlands in Tirisfal Glades in the pass mountain, in the house where is a First Aid trainer.
Additional information: This is from a quest line that starts on Glenshire in the curch from the NPC Duke Nargelas.

**Steps to reproduce the behavior with as much detail as possible:**

1. When you accept the pertinent quest you should recive a item quest poison vial for interact with an ambiental object on the quest completion zone, but you actually don't recieve nothing, there is no instruction of where can be or if you should be able to get from the world itself, i looked for the entire house and surroundings and even the completion zone but there is not pickable item for the mentioned quest.
2. Abandoning the quest and retaking doesn't work, i also found other people in-game that couldn't complete it for this reason. There is also people on the Discord Turtle WoW that already informed/asked wihtout solution.
3. 

**IDs of affected creatures, items, quests or spells with a link to the relevant page:**

NPC: https://database.turtle-wow.org/?npc=91711
Quest: https://vanilla-twinhead.twinstar.cz/?quest=40099

Previuos quest form the questline: https://database.turtle-wow.org/?quest=40098

**Expected behavior. Describe how it should work:**

It should give you the item quest when you accept the quest.

**Comment by slowtorta** [comment]
Fixed a while ago.
