### ISSUE TITLE
skill ice armor bug

### ISSUE THREAD

**Issue by ireele** [slowtorta/turtlewow-bug-tracker#2059]
**ice armor disappears when melees hit me**

https://classic.wowhead.com/spell=7302/ice-armor#taught-by-npc

previously it was perfect because now this bug appears

https://mega.nz/file/NM9AhZwQ#zOF5VjKXg4mo-KG9prSs7Csk8oDHtwnjM-cqyIXDCRI

I need a quick fix because this skill is indispensable for the mage.

**Comment by ratkosrb** [comment]
Cannot reproduce the issue.
