### ISSUE TITLE
The Twilight Camp  quest is broken: Twilight Tome can't be interact with

### ISSUE THREAD

**Issue by SierraNairn** [slowtorta/turtlewow-bug-tracker#206]
The Twilight Camp  quest is broken: Twilight Tome can't be interact with
https://database.turtle-wow.org/?quest=949 -The Twilight Camp  
https://database.turtle-wow.org/?object=12666 -Twilight Tom

How it supossed to work : Find book,  then complete quest.
What does not work: You can't interact with the book.

![WoW_70GAfQQnTP](https://user-images.githubusercontent.com/83077166/127451603-412ddcce-cd07-4d7f-b112-bafdb36e7efe.png)

**Comment by slowtorta** [comment]
Thanks for reporting it. It'll be fixed on the next server restart. Make sure to clear your WDB folder.
