### ISSUE TITLE
Aspect of the Cheetah Daze on Dot application

### ISSUE THREAD

**Issue by Baroli1** [slowtorta/turtlewow-bug-tracker#2060]
**Please, provide a clear description what the bug is:**

Aspect of the Cheetah dazes you when you get any sort of dot applied to you. Be it Shadow Word: Pain from a Priest. Corruption, Curse of Agony or Siphon Life from a Warlock. Serpent Sting from a Hunter. Probably others which i havent tested. 

**Steps to reproduce the behavior with as much detail as possible:**

1. Have a duel with a dot class.
2. Sit in Aspect of the Cheetah while he applies his dot.
3. Notice how you get dazed as soon as the dot is applied to you but not from the periodic damage.

**IDs of affected creatures, items, quests or spells with a link to the relevant page:**

Spell: https://database.turtle-wow.org/?spell=5118

**Expected behavior. Describe how it should work:**

Aspect of the Cheetah should not get you dazed if you are not struck with direct damage (such as Moonfire). It should also not daze you when taking damage from any dot. Most dots deal no initial damage and therefore should not be able to daze. The dot is applied and, in the case of Corruption (Warlock dot), it takes 3 seconds for the first damage to roll out.

Here is video proof from classic of how it is supposed to function.
https://www.youtube.com/watch?v=BUojGa-jnSc&ab_channel=DannyGaminGnC
At 0:39 he runs at the Hunter casting Shadow Word: Pain. The hunter is in Cheetah as you can see from his fast movement speed.
At 0:47 the Priest casts Mind Blast and the hunter becomes dazed. 
He did not change into the aspect as you would be able to see the animation above his head which means he was in it all along.
At 1:32 the Hunter is afflicted by another sw:p and is not dazed.
At 2:02 same thing.
At 2:08 he gets dazed because he is hit by the wand.

Please fix this. Its terrible in pvp.

**Comment by Iacov** [comment]
*Bump*

**Comment by adiosamigos** [comment]
this bug puts hunters at big disadvantage and breaks the classic playstyle, please fix ASAP
