### ISSUE TITLE
Sartura is immune to taunt

### ISSUE THREAD

**Issue by vkekd** [slowtorta/turtlewow-bug-tracker#2061]
The aq40 boss Sartura is immune to taunt, challenging shout and mocking blow while using whirlwind but in classic its tauntable.

1. Start the fight
2. Try to taunt her while shes doing the whirlwind

NPC: https://database.turtle-wow.org/?npc=15516

Sartura should be tauntable by all three spells while shes using whirlwind as you can see in these examples from classic: 
1.- https://youtu.be/5Y-znW8zEvI?t=518
2.- https://youtu.be/EBQJWWc_Ha8?t=515

**Comment by Sringaram** [comment]
Isn't that the whole point of the mechanic? The targeted player running away during the whirlwind and the tank picking her back up once it ends? I don't recall her ever being taunted while spinning in actual vanilla.
This would make the fight braindead easy.

**Comment by vkekd** [comment]
> Isn't that the whole point of the mechanic? The targeted player running away during the whirlwind and the tank picking her back up once it ends? I don't recall her ever being taunted while spinning in actual vanilla. This would make the fight braindead easy.

- https://youtu.be/Xxoxyg9lGFk?t=34
- https://youtu.be/Kg7Chsn7Ve8?t=87
Vanilla footage
you can see Sartura getting taunted while doing the whirlwind in these 2 videos

**Comment by Velite12** [comment]
Do you mean that it says "immune" when you try to taunt, or that the debuff lands but does nothing? The way the whirlwind script works is that it should just target random players every sec or two. I'm pretty sure she can be taunted but it doesn't influence the script.

**Comment by jameyboor** [comment]
Velite is right and intended.
