### ISSUE TITLE
Stratholme Undead: Baron Rivendare Aggro Range too big

### ISSUE THREAD

**Issue by zulnam** [slowtorta/turtlewow-bug-tracker#2062]
**Please, provide a clear description what the bug is:**
Baron Rivendare's aggro range is so big, only one player of the party gets a chance to go inside the room before the doors close. If they pull back it means the party has to fight him in the hall before his room (very bad location).

**Steps to reproduce the behavior with as much detail as possible:**

1. Go into Stratholme Undead.
2.  Reach Baron Rivendare
3.  Proceed to enter his room.

**IDs of affected creatures, items, quests or spells with a link to the relevant page:**
NPC: https://database.turtle-wow.org/?npc=10440

**Expected behavior. Describe how it should work:**
The boss should have a much smaller aggro range so that all players get a decent chance of entering his room and not 3-2-1 time it like it's anything more than a 5-man dungeon giving low-tier loot. Remember this is done primarily by PuGs with no voice comms (because it's strat).

**Comment by Sringaram** [comment]
Yeah, I clearly recall the whole group entering the room and standing in a corner before the pull in vanilla.
