### ISSUE TITLE
Charge and overpower

### ISSUE THREAD

**Issue by DawoAA** [slowtorta/turtlewow-bug-tracker#2063]
**Please, provide a clear description what the bug is:**

**Steps to reproduce the behavior with as much detail as possible:**

1.cast Charge.Should generate 12 points of anger,But sometimes it's 10
2. overpower.When switching states,Active state, sometimes disappears in advance
3. 

**IDs of affected creatures, items, quests or spells with a link to the relevant page:**

NPC: https://database.turtle-wow.org/?npc=
Item: https://database.turtle-wow.org/?item=
Quest: https://database.turtle-wow.org/?quest=
Spell: https://database.turtle-wow.org/?spell=
Object: https://database.turtle-wow.org/?object=

**Expected behavior. Describe how it should work:**

**Comment by slowtorta** [comment]
Not enough information, I'm sorry.
