### ISSUE TITLE
Warlord's Command quest, documents not respawning.

### ISSUE THREAD

**Issue by Whitepussicat** [slowtorta/turtlewow-bug-tracker#2065]
The Horde quest Warlord's Command, the documents you need behind the last boss did not respawn after a team member grabbed them.

NPC: https://database.turtle-wow.org/?npc=9077
Item: https://database.turtle-wow.org/?item=12562
Quest: https://database.turtle-wow.org/?quest=4903
Spell: 
Object: https://database.turtle-wow.org/?object=175785

This item should respawn after being taken. Wowhead comments plus team members confirmed. I only have a screenshot of me waiting for about ten minutes for the item to respawn.
![WoWScrnShot_090322_182519](https://user-images.githubusercontent.com/112793165/188298096-ff689a80-4866-43e6-99c4-7b49522eacab.jpg)

**Comment by slowtorta** [comment]
This was fixed a while ago. 
![image](https://user-images.githubusercontent.com/66763404/200174877-00aa74b6-b3e1-447f-8ee5-bdf3c7474378.png)
