### ISSUE TITLE
Shaman Clearcasting consumed in 1x Lightning Bolt

### ISSUE THREAD

**Issue by SnorreP** [slowtorta/turtlewow-bug-tracker#2067]
### **Please, provide a clear description what the bug is:**
Clearcasting is consumed on 1x Lightning Bolt in a specific case described below.

### **Steps to reproduce the behavior with as much detail as possible:**
_EDIT 2022,10-03: 
New and improved description of the issue by Niqlo in a comment below:_

- You cast a lightning bolt and immediately queue up another. When the first bolt lands, if you're currently casting you will lose both stacks of clearcasting.

**Workaround**
You cast a lightning bolt but wait for the first one to land before you start casting a second. Only one stack of clearcasting will be used

**Old description**
~~Get a Clearcasting proc and finish the mob you are fighting without casting any spells that consume Clearcasting.
Leave combat and pull another mob with Lightning Bolt
Clearcasting is gone after 1x Lightning Bolt. It seems to happen when you leave combat and start new fight, because I tried hardcasting 2x Lightning Bolts against the same mob that I procced Clearcasting on, and then I could cast two Lightning Bolts before Clearcasting was consumed~~

### **IDs of affected creatures, items, quests or spells with a link to the relevant page:**

Talent: 

1. https://database.turtle-wow.org/?spell=45541

### **Expected behavior. Describe how it should work:**
I should get two Lightning Bolts at a 40% mana discount from Elemental Focus in all cases.

**Comment by Niqlo** [comment]
This bug actually happens when you are casting a lightning bolt when one lands

for example: you crit a spell, get 2 stacks of clearcasting:

1. you cast a lightning bolt and immediately queue up another. when the first bolt lands, if you're currently casting you will lose both stacks of clearcasting

2. you cast a lightning bolt but wait for the first one to land before you start casting a second. Only one stack of clearcasting will be used

**Comment by SnorreP** [comment]
I wish to add that I experience what Niqlo is describing, and I suspect, that it is the same thing I experienced in my original description/bug report.

The difference is that, when I tested, I forced a crit proc with a melee attack, and then I would hardcast 2x Lightning Bolts back-to-back while the mob was hitting me. I guess that the short traveling time from being in melee is the reason I did not see both stacks consumed.

**Comment by KreepAK** [comment]
Description by @Niqlo describes the issue perfectly. Experiencing this bug when playing as Elemental Mastery hammy. You can imagine my frustration being full elemental shaman with major (Turtle wow updated) talent broken. It supposed to be the best dps class, but atm its disappointment. Aren't talents in priority for fix above quests and other less important stuff? Please fix this ASAP

**Comment by Kuz-Shaman** [comment]
This doesnt only affect me, it forces me to play a spec that I do not want to play.

**Comment by Seberats** [comment]
As a shaman, i'm really affected by this bug. Shamelem is bad enough in pve... The patch was months ago ! Fix it please!!!
