### ISSUE TITLE
stealth not working right

### ISSUE THREAD

**Issue by guruvex** [slowtorta/turtlewow-bug-tracker#2070]
**Please, provide a clear description what the bug is:**
then the talent patch was going to be put in (the first time) so 8-9 months ago. i went from no one can see me to every mod can.

i have 5/5 in master of deception (5 lvls), nightscape boots (1 lvl), blackened defias mask (1 lvl), and the stealth enchant (1 lvl). giving me a total of 8 extra lvls of stealth. so as a stealth level 68, how can a lvl 20 mob spin to see me? and even attack me in stealth?

**Steps to reproduce the behavior with as much detail as possible:**

1. use stealth
2. stand near a mob 48 lvls lower
3. mod will see you and even attack.

**IDs of affected creatures, items, quests or spells with a link to the relevant page:**

every mob in the game to my knowledge, from deadmines to blackwing layer, from wintersprings to silithis.

**Expected behavior. Describe how it should work:**
to my understanding and much googling. the stealth vs perception is the same as wep skill vs def skill. so a lvl 20 mob should not be able to hit a lvl 68 player. its 100 wep skill vs 340 def skill. i should be able to /dance on there head and not be seen. granted i know there's the min distance but still you get my point.

**Comment by Francesq** [comment]
This is a bit complicated
Especially, cloak enchant give 5 points
Master of deception 3 points for each level

The level skill is 300at 60 (I suppose 5/level) and it modifies the way you can be detect.

The detection is much more important in a cone in front of the mob so by using distract you can escape a part of the mob detection.

mat least you will always be detectable because the difference between detection and stealth level only reduce the distance you can be detected to the incompressible 5 meters in a cone in front the entity.

**Comment by guruvex** [comment]
I am aware of the min distance Infront of the mob, I used that to compare
the cloak enchantment vs night scape boots or the defias mask to see how
much the cloak enchantment gave.

But that still don't explain why a lvl 30 mob in Scarlett monastery will
spin  to look at me when I'm more than 5 meters away to his side.

**Comment by cyaohiri** [comment]
> that still don't explain why a lvl 30 mob in Scarlett monastery will spin to look at me when I'm more than 5 meters away to his side.

A thing you might not have noticed is that even neutral mobs (e.g. Tanaris turtles) or mobs that seem hostile but aren't (e.g. the guard at the great lift) will face you when you're in stealth, although they won't attack even if you weren't in stealth.

**Comment by Nozdormus** [comment]
I agree with [guruvex] talent doesn't work. I chek it on classic era servers. There mobs that my lvl or lower doesn`t see me at all even if i stand infront of them. Here on twow mobs see me alwayse. I am lvl 18 mobs are lvl 13 and they detect me always.
