### ISSUE TITLE
Agitating poison

### ISSUE THREAD

**Issue by guruvex** [slowtorta/turtlewow-bug-tracker#2071]
**Please, provide a clear description what the bug is:**
2 issues with it.
(1) it don't stack like every other poison, not game braking but it makes my bags cry.

(2) cant use it on weapons

**Steps to reproduce the behavior with as much detail as possible:**

1. make poison
2. right click to use it
3. click on weapon to use it on. (don't work)

**Expected behavior. Describe how it should work:**
it should give a temporary (30 min) buff to the weapon.

**Comment by rj8216** [comment]
I can confirm that this is happening on my rogue as well. Poisons don't stack, nor is there anyway to apply the poison. I did try to toggle auto-self cast to see if it changed anything, but sadly it still doesn't work.
