### ISSUE TITLE
Rested xp gains via tents is slower in S&S

### ISSUE THREAD

**Issue by MishailTM** [slowtorta/turtlewow-bug-tracker#2072]
As said in the title, Rested xp gains via tents is slower in S&S

**Steps to reproduce the behavior with as much detail as possible:**

1. Enable S&S
2.  Go to a survival tent
3. See rested xp gains are slower

**Expected behavior. Describe how it should work:**
Since S&S only reduces mob kill xp, it shouldnt reduce rested xp from tents as it doesn't say that anywhere.

**Comment by slowtorta** [comment]
This is the intended behavior. Was probably announced in some of the long-forgotten changelogs a long time ago. We will include this in the website S&S description :)
