### ISSUE TITLE
Animation of footprint splashes in shallow water loop for lengthy periods of time.

### ISSUE THREAD

**Issue by BartoszDerenda** [slowtorta/turtlewow-bug-tracker#2074]
**Please, provide a clear description what the bug is:**
Animation of footprint splashes in shallow water remains permanent.
Bug first noticed around the water rim of one of Barren's Oasis (Northwest one).
I have not yet tested it around any other body of water in Azeroth.

EDIT: After logging out for an extended amount of time, one needed to make and eat supper, the footprint animations are gone.

**Steps to reproduce the behavior with as much detail as possible:**

1. Run around in shallow water.

**Expected behavior. Describe how it should work:**
Animation is still looping even after you relog, proving that it may not be a client sided issue.

**Comment by BartoszDerenda** [comment]
After noticing the persistance of aoe visual effects of Centaurs in the Barrens, I decided to clear WDB cache.
So far it still persists.

**Comment by slowtorta** [comment]
This isn't a general client bug, must be something related to the settings specific only to your graphic adapter + client video config.  Try to play around with this guide: https://forum.nostalrius.org/viewtopic.php?t=1100
You could disable footprints altogether or lower the water-related graphic effects: https://github.com/mrrosh/VanillaGraphicBoost
