### ISSUE TITLE
GetShapeshiftFormInfo() not vanilla-like, breaking 1.12 addons

### ISSUE THREAD

**Issue by TaylerWilbourn** [slowtorta/turtlewow-bug-tracker#2076]
The API function GetShapeshiftFormInfo() does not return vanilla-like results, and therefor breaks 1.12 addons which rely on it.

Expected behavior:
Calling GetShapeshiftFormInfo(i) should return results corresponding to the vanilla wow API documentation which can be found below.
https://vanilla-wow-archive.fandom.com/wiki/API_GetShapeshiftFormInfo

Observed behavior:
At least one class seems to use different integers to index their stances than what is documented for vanilla. (Druid)
This causes addons to break when they rely on detecting specific stances.

Repro:
- Start with level 20+ druid.
- Call GetShapeshiftFormInfo(1) while in bear form.
- Observe correct behavior.
- Call GetShapeshiftFormInfo(3) while in cat form. (This is the documented index for cat form)
- Observe incorrect behavior.
- Call GetShapeshiftFormInfo(2) while in cat form.
- Observe correct behavior, but on incorrect index. (This is the documented index for aquatic form, but on TurtleWoW it corresponds to cat form)

Notes: 
Only bear and cat form seem to be represented at all in the TurtleWoW implementation, but the function is intended to index all druid forms, including tree of life. This function is also used to track Warrior, Rogue, Paladin, and Priest stances. I have not tested behavior for other classes, but it is worth comparing the internal data with the documentation to ensure that they are returning correctly as well. This bug prevents the Bongos addon from properly paging action bars according to druid form, and it is likely not the only addon to do so.

**Comment by geojak** [comment]
The api docu is unfrotuently not accurate. You can check for example the info on the website for getbuffinfo or something like that and the game returns cokpeltely different stuff.
The docu is wrong not the function

**Comment by TaylerWilbourn** [comment]
Both Bongos and ElvUI are written against the 1.12 client, have used the above linked tables for their shapeshift enums, and were working as intended 10+ years ago on multiple other servers. Even if the values returned by TWoW for this function were what was returned in retail 1.12 (I do not believe they are), they are incongruous with the standard which1.12 addons have been written against for at least a decade. The fact that the server returns something different than the documentation is in fact the issue I am reporting. It is not proof that there is no issue.

**Comment by Terrub** [comment]
Did a quick check on my warrior (who doesn't have Berserker Stance yet sadly)
Calling index 1 gives me the correct icon, name and, whilst in Battle Stance, the active flag (1) else nil
Calling index 2 gives me the correct icon, name and. whilst in Defensive Stance, the active flag (1) else nil

Also I can acknowledge that I was surprised to learn that Catform was not the 2nd index when I was writing addons/Lua/macro's long long ago (most likely retail BC/LK, unsure)

**Comment by slowtorta** [comment]
We never modified the existing client API functions, probably the information you're looking for is part of the DBC data.
This is our current SpellShapeshiftForm.dbc
![image](https://user-images.githubusercontent.com/66763404/200201515-53ad2cee-5297-4748-b255-13fb9cadfc42.png)
