### ISSUE TITLE
Unmineable Truesilver Deposit - Stranglethorn Vale

### ISSUE THREAD

**Issue by Pati3ntZer0** [slowtorta/turtlewow-bug-tracker#2077]
**Please, provide a clear description what the bug is:**

**Steps to reproduce the behavior with as much detail as possible:**

1. The Truesilver deposit at 39.5, 53 cannot be reached for mining.  It is under a small hill.
2.  
3. 

**IDs of affected creatures, items, quests or spells with a link to the relevant page:**

NPC: https://database.turtle-wow.org/?npc=
Item: https://database.turtle-wow.org/?item=
Quest: https://database.turtle-wow.org/?quest=
Spell: https://database.turtle-wow.org/?spell=
Object: https://database.turtle-wow.org/?object=

**Expected behavior. Describe how it should work:**

**Comment by slowtorta** [comment]
Please report such cases via in-game ticket, it can be hotfixed by GMs.
