### ISSUE TITLE
"Collection of Goods" Epic Paladin Mount Quest is bugged.

### ISSUE THREAD

**Issue by Merthues** [slowtorta/turtlewow-bug-tracker#2079]
**Please, provide a clear description what the bug is:**
Unable to turn in materials once all have been gathered to move on to next stage of quest.
**Steps to reproduce the behavior with as much detail as possible:**

1.  Gather materials
2.  Talk to Grimand Elmore
3.  Be unable to turn in quest.

**IDs of affected creatures, items, quests or spells with a link to the relevant page:**

NPC: https://database.turtle-wow.org/?npc=grimand elmore
Item: https://database.turtle-wow.org/?item=
Quest: https://database.turtle-wow.org/?quest=Collection of Goods
Spell: https://database.turtle-wow.org/?spell=
Object: https://database.turtle-wow.org/?object=

**Expected behavior. Describe how it should work:**
hand in items, move on to next stage of questline.

**Comment by Tinyfin-github** [comment]
For those issues please cancel the quest and take it again to solve the problem.

If the issue persists, please open an in game ticket.
