### ISSUE TITLE
Holy wrath is missing spell projectile visual

### ISSUE THREAD

**Issue by Velite12** [slowtorta/turtlewow-bug-tracker#208]
https://youtu.be/cvWFOvGfbH8?t=141

On turtle there is no projectile visual to show the mobs being hit, they just receive the impact

https://database.turtle-wow.org/?spell=2812
https://database.turtle-wow.org/?spell=10318

**Comment by slowtorta** [comment]
![image](https://user-images.githubusercontent.com/66763404/159126662-85ef4032-b6ab-4f2a-bf81-f194b21bc9c6.png)
![image](https://user-images.githubusercontent.com/66763404/159126686-dd44313c-e089-46ac-bc97-e1c6cf23f1e0.png)

Cannot reproduce, I see projectile w/o issues.
