### ISSUE TITLE
Fishing pools in lapidis isle and gillijim’s isle

### ISSUE THREAD

**Issue by afizzler** [slowtorta/turtlewow-bug-tracker#2082]
It isn’t necessarily a bug, but it feels buggy to not see fishing pools in these custom islands when there are a lot of fishing pool spawns in coastal areas. It could be nice if time was used later to add fishing pools to these zones.

**Comment by Dormilon** [comment]
https://github.com/slowtorta/turtlewow-bug-tracker/issues/2780 Closed.
