### ISSUE TITLE
Lethon despawns in 10 seconds after kill

### ISSUE THREAD

**Issue by Zebouski** [slowtorta/turtlewow-bug-tracker#2084]
1. Kill lethon
2. wait 10 seconds
3. see him despawn

**IDs of affected creatures, items, quests or spells with a link to the relevant page:**

NPC: https://database.turtle-wow.org/?npc=14888

**Expected behavior. Describe how it should work:**
his body should last hours

**Comment by geojak** [comment]
Yo madlads actually did it

**Comment by Lexiebean** [comment]
Dragons of Nightmare are still despawning in 10 secs after the final one is killed

**Comment by slowtorta** [comment]
https://github.com/slowtorta/turtlewow-bug-tracker/issues/3091
