### ISSUE TITLE
Hunter Multi-shot

### ISSUE THREAD

**Issue by Otakoe** [slowtorta/turtlewow-bug-tracker#2085]
**Please, provide a clear description what the bug is:**
I was surprised to see red text while moving and using this spell. Also was surprised when during using i have delay as Auto-shot. Any DB and as i remember - multishot has Instant cast. Addon for autoshot also shows delay like for autoshot

**Steps to reproduce the behavior with as much detail as possible:**

1. Shoot in any mob in moving
2. Reading red text.
3. Shoot in any mob in standing. Looking on delay.

**IDs of affected creatures, items, quests or spells with a link to the relevant page:**

https://database.turtle-wow.org/?spell=2643

**Expected behavior. Describe how it should work:**
Instant cast without any delay

**Comment by D4nSch** [comment]
You always had to be still to use it, it's a half second "cast" which is not indicated by the vanilla client without addons. That's why multi shot needs to be weaved into your auto shot.

An addon called YaHT might help you there!

**Comment by ratkosrb** [comment]
The current way it works is blizzlike. If you would like to see it changed, suggest it in the forums for the next round of class changes.
