### ISSUE TITLE
Straight shallow water line is in the middle of the ocean

### ISSUE THREAD

**Issue by Shellyoung** [slowtorta/turtlewow-bug-tracker#2088]
**Please, provide a clear description what the bug is:**

![Ocean line error](https://user-images.githubusercontent.com/40469927/189277252-2cbbaabd-0cec-4bbc-b308-e8d99e1ac1a6.png)

**Location:**
![Ocean line error location](https://user-images.githubusercontent.com/40469927/189277480-bb7e2093-74ca-493c-9801-76a2b0b5e233.png)

**Expected behavior. Describe how it should work:**
The water should look homogeneous.

**Comment by slowtorta** [comment]
This looks like a general Vanilla client glitch ignored by the original developers a long time ago. Since it's very minor ad not affecting gameplay, we're not going to look into fixing this one, I'm sorry.
