### ISSUE TITLE
ERROR #132 at Gnomeregan Entrance

### ISSUE THREAD

**Issue by Lacerda1303** [slowtorta/turtlewow-bug-tracker#2089]
I was exploring the area with my Priest (Human) and as soon as I got near the entrance of Gnomeregan in Dun Morogh the game crashed with the:  

**_ERROR #132 (0x85100084) Fatal Exception... 
Exception: 0xC0000005 (ACCESS_VIOLATION) at 0023:006D6AD0

The instruction at "0x006D6Ad0" referenced memory at "0x00000000".
The memory could not be "read".

Press OK to terminate the application._**

After the game closed, I opened again and loged in. If I choose a different character it's fine, but if I select my Human Priest, who is at the same place the game closed before, the same error keeps happening and the game closes as soon as the loading of the character (after selection) finishes. I have no chances to get out of the area or something else.

![ERROR 1](https://user-images.githubusercontent.com/113174379/189320633-bd52de7f-e287-41e7-ac7d-f057d709780d.jpg)

**Comment by Tinyfin-github** [comment]
You are running a client with old patches.

Please get the fully updated client from the website.
