### ISSUE TITLE
Lethtendris shadowbolt doing way too much damage

### ISSUE THREAD

**Issue by Velite12** [slowtorta/turtlewow-bug-tracker#209]
https://youtu.be/hdU-IWdLZ54?t=154

![image](https://user-images.githubusercontent.com/45871932/127572973-e930fe42-e1df-47b1-84bf-a4693ef64a13.png)
![image](https://user-images.githubusercontent.com/45871932/127573017-4d85d65c-e530-4d1a-9b5e-acc54b15b865.png)

In this video you can see her shadowbolt hits the enslaved satyr for 1029 damage (non resisted), on turtle wow this shadowbolt hits for 3000 damage 

https://database.turtle-wow.org/?npc=14327

**Comment by Nolin7777** [comment]
Most likely a wrong spell assigned.

**Comment by slowtorta** [comment]
It's been fixed. 
![image](https://user-images.githubusercontent.com/66763404/148814416-405755fc-566e-41fb-b4bf-6dd9cf411a34.png)
![image](https://user-images.githubusercontent.com/66763404/148814429-ca9db728-c618-4bd9-a20e-bf9cfb1e925b.png)

**Comment by Velite12** [comment]
It's still not fixed
