### ISSUE TITLE
"Seal of Ascension" (second part) not fully working / unable to restart

### ISSUE THREAD

**Issue by SplashX2** [slowtorta/turtlewow-bug-tracker#2091]
**Please, provide a clear description what the bug is:**

I gathered all gems for the Quest "Seal of Ascension" starting at "Vaelan" in UBRS got both the "Unforged Seal of Ascension" and the "Orb of Draconic Energy" and headed to Emberstrife. However, I could not finish the quest as the "Unforged Seal of Ascension" despawned quickly (about 1-2 minutes) and the mind-control did not function since Emberstrife "did not falter" at any HP (1%-15%). The "Unforged Seal of Ascension" only has 5 charges which I used in the process of several tries then the item disappeared. So I went to Vaelon to get another 5 charges of "Unforged Seal of Ascension" but he would not. I then cancelled the quest so I can restart it but Vaelon only offers "gossip" (clickable dialogue).

**Steps to reproduce the behavior with as much detail as possible:**

1. Finish the first part of "Seal of Ascension"
2. Putting the "Unforged Seal of Ascension" in front of Emberstrife
3. Trying to get Emberstrife to repeatedly breath on the "Unforged Seal of Ascension" (at low HP of Emberstrife, since the mind control is also bugged and Emberstrife does not falter)
4. Seeing the "Unforged Seal of Ascension" dissapear without being forged
5. Repeat 5 times until the "Unforged Seal of Ascension" dissappears
6. Try to replenish the "Unforged Seal of Ascension" when talking to Vaelan
7. Try to restart the quest "Seal of Ascension" after cancelling it at again talking to Vaelan.

**IDs of affected creatures, items, quests or spells with a link to the relevant page:**

NPC: https://database.turtle-wow.org/?npc=10296
Item: https://database.turtle-wow.org/?item=12323
Quest: https://database.turtle-wow.org/?quest=4743

**Expected behavior. Describe how it should work:**

The "Unforged Seal of Ascension" should be placed in front of Emberstrife. Emberstrife should be mind-controllable as soon as he "falters". The seal should then be forged when performing "flame breath" / attacking the "Unforged Seal of Ascension".

If the charges of the "Unforged Seal of Ascension" are used, the "Unforged Seal of Ascension" should be replenished when talking to "Vaelan".

If the quest Seal of Ascension (ID: 4743) is cancelled one should be able to restart it when talking to Vaelon.

**Comment by Tinyfin-github** [comment]
You need a Unadorned Seal of Ascension]  to talk to Vaelon
