### ISSUE TITLE
Spell: Cold Blood

### ISSUE THREAD

**Issue by Sringaram** [slowtorta/turtlewow-bug-tracker#2093]
ID: https://database.turtle-wow.org/?spell=14177

The buff is consumed if your skill misses or is avoided, which isn't supposed to happen as far as I know.

**Comment by Francesq** [comment]
As far as I know is a bit light...

**Comment by Sringaram** [comment]
On every vanilla server I played, the buff remained on you till you actually landed a hit. I did not play rogue in actual Blizzard's vanilla back then so I've no idea how it behaved there, but I did in TBC, and it behaved in the same way.
It only makes sense since this is a long cooldown and having it just randomly disappear due to RNG doesn't seem right to me.

**Comment by cyaohiri** [comment]
Looking at comments posted back in vanilla, it does seem the buff goes away even if the attack does not land. https://www.wowhead.com/classic/spell=14177/cold-blood#comments:id=2743379

**Comment by Sringaram** [comment]
Then this can fall into the logical QoL suggestions category along with TBC combo points.

**Comment by Francesq** [comment]
Coming from "it should be like that cause I remember" then end up by "we should apply some changes cause I think it is better".
Please stop acting like this with bugtracker which is only a way to report bug not another manner to make suggestions. There is forum for this.
