### ISSUE TITLE
NPC: Mushgog

### ISSUE THREAD

**Issue by Sringaram** [slowtorta/turtlewow-bug-tracker#2095]
ID: https://database.turtle-wow.org/?npc=11447

The abilities this rare uses don't seem to be right at all.

It constantly spams AoE knockback (cannot be interrupted), followed by Spore Cloud which applies a dot that ticks for about 3k damage over 3 seconds or so and sticks to you, meaning that leaving the cloud does nothing. This is done constantly and is basically unavoidable. Even with RDPS and tank strat, the tank melts even with focus healing because there's no way to avoid the AoE DoT.

You'd need a NR geared tank and a decked out healer for this, which seems very off considering this is entry level content dropping one random blue BoE.

**Comment by SabineWren** [comment]
Yeah, Mushgog's harder than everything else in Dire Maul. You need a strong group to take him down, while the other rares can be soloed by a hunter.

The high difficulty is less of a problem than the fact new groups don't know his power until wiping on him. If you show up to run part of Dire Maul and think "Hey look, we can kill a rare before starting", it won't go well for you!

Making him a boss like Teremus would warn groups they're in for a struggle. I'd prefer that to nerfs, especially if his loot improved slightly.

**Comment by Sringaram** [comment]
I don't think you're expected to bring NR geared tank and only RDPS for this, are you?

Perhaps the cloud is supposed to be an actual cloud you can move out from and not a lingerind DoT?

**Comment by SabineWren** [comment]
No need for NR, and melee works if your healer doesn't go oom. Any group of five 60s can probably kill him, even with blue gear. He needs a warning sign "you must be this tall to fight" to scare off the DME groups that bring levelers in greens.

**Comment by slowtorta** [comment]
If you believe this boss isn't working correctly, please re-open this issue with a video-proof from Classic PTR :)
