### ISSUE TITLE
Quest: Earthen Arise BUG

### ISSUE THREAD

**Issue by csindone** [slowtorta/turtlewow-bug-tracker#2096]
**Please, provide a clear description what the bug is:**

**Steps to reproduce the behavior with as much detail as possible:**

1. Goggeroc spawns correctly but I am unable to attack him
2. If touch the Resonite cask again or click the Enchanted Resonite Crystal in my bag addition Goggeric spawn
3.  The additional Goggeric attack and I die
**IDs of affected creatures, items, quests or spells with a link to the relevant page:**

NPC: https://database.turtle-wow.org/?npc=11920
Item: https://database.turtle-wow.org/?item=16603 and 178145
Quest: https://database.turtle-wow.org/?quest=6481
Spell: https://database.turtle-wow.org/?spell=
Object: https://database.turtle-wow.org/?object=

**Expected behavior. Describe how it should work:**
A single Goggeric should spawn to fight and kill

**Comment by redmagejoe** [comment]
This is still an issue. Prevent more than one instance of this creature existing at a time, and also disable a player's ability to interact with the stone gameobject once they've successfully killed Goggeroc and have received quest credit.
