### ISSUE TITLE
Druid's stag travel form quest is cut in the middle of it's description.

### ISSUE THREAD

**Issue by BartoszDerenda** [slowtorta/turtlewow-bug-tracker#2097]
**Please, provide a clear description what the bug is:**
One of the custom quests in the game seems to have reached it's character limit.

**Steps to reproduce the behavior with as much detail as possible:**

1. Lvl up a druid to 30 :)
2. Go Moonglade.
3. Get Antler's Guidance (https://database.turtle-wow.org/?quest=40010)
4. Travel to the border of Southern Barrens and Dustwallow Marsh.
5. Finish the quest and pick up The White Stag and the Moon (https://database.turtle-wow.org/?quest=40012).
6. Attempt to read it's description.

**IDs of affected creatures, items, quests or spells with a link to the relevant page:**

NPC: https://database.turtle-wow.org/?npc=60310
Quest: https://database.turtle-wow.org/?quest=40012

**Expected behavior. Describe how it should work:**
Entirety of quest's text should be visible to the player.

**Comment by slowtorta** [comment]
I cannot reproduce. Do you use any quest-log addons?

![image](https://user-images.githubusercontent.com/66763404/189607056-397b3bb6-532a-4b21-957b-53a0c3cf5134.png)
