### ISSUE TITLE
sillithus nother wesern prophet race glitches around like devilsaurs in ungro crater. 

### ISSUE THREAD

**Issue by geojak** [slowtorta/turtlewow-bug-tracker#2099]
**Please, provide a clear description what the bug is:**

![WoWScrnShot_091022_221704](https://user-images.githubusercontent.com/25199983/189501543-de83f6c6-957e-45b6-b7e0-dd8ea2c71dbd.jpg)
![WoWScrnShot_091022_221719](https://user-images.githubusercontent.com/25199983/189501547-059c3c0c-6c4e-4b41-9cb7-2ee7380a68c4.jpg)

they start normal walking after racing back to the elemtals
**Expected behavior. Describe how it should work:**

no glitchy killer squat speedforce user twillight prohet

**Comment by slowtorta** [comment]
Duplicate for https://github.com/slowtorta/turtlewow-bug-tracker/issues/2169
