### ISSUE TITLE
Drop Quest: A talking Head

### ISSUE THREAD

**Issue by Pythol** [slowtorta/turtlewow-bug-tracker#21]
**Current behavior**: The Item to start the quest "Resting in Pieces" isn't dropping. I killed around 100 of those gnolls and it shouldn't be that of a rare drop. Here is the database link:

https://database.turtle-wow.org/?item=3317#starts

**Expected behavior**: The itom should drop from the Rot Hide Gnolls

**Proofs**: X

**Steps to reproduce**:

1. Kill a lot of Gnolls or check their droplist!
2. 
3.

**Comment by Nolin7777** [comment]
Has a 2% chance to drop.
