### ISSUE TITLE
Can't cast Remove Curse in Moonkin form, despite it saying I should be able to.

### ISSUE THREAD

**Issue by DraxerTABC** [slowtorta/turtlewow-bug-tracker#2100]
**Please, provide a clear description what the bug is:**
Cannot cast Remove Curse while in Moonkin form. It's saying "Cannot cast while shapeshifted." The Moonkin form itself is saying I should be able to.

**IDs of affected creatures, items, quests or spells with a link to the relevant page:**

Spell: https://database.turtle-wow.org/?spell=24858 (Moonkin form)
Spell: https://database.turtle-wow.org/?spell=2782 (Remove Curse)

**Expected behavior. Describe how it should work:**
I should be able to cast Remove Curse while in Moonkin Form.

**Comment by slowtorta** [comment]
This will be fixed in 1.16.4 (requires a client update).
