### ISSUE TITLE
Suggestion: Give PVP rank hiding (5g cost) a confirmation dialogue

### ISSUE THREAD

**Issue by usedcars4cheap** [slowtorta/turtlewow-bug-tracker#2102]
For the two NPCs which allow players to hide their player rank - add a confirmation dialogue to spend the 5 gold.
https://database.turtle-wow.org/?search=Wheeler-dealer

some people not read so good

**Comment by slowtorta** [comment]
This is technically impossible, I'm sorry :(

**Comment by slowtorta** [comment]
I could only add some text saying that I'll cost them 5 gold.
