### ISSUE TITLE
Invisible lvl60 Guard

### ISSUE THREAD

**Issue by Drinxy** [slowtorta/turtlewow-bug-tracker#2103]
There is a bug in wetlands where a lvl 60 Menethil guard just appears and aggro's horde players out of nowhere in the middle of the area (right across the bridge where the goblin vendor is). You can see my combat log in attached pictures. I'm aware of your statement that there will be no character restoration whatsoever, but if this bug is not enough for character revival, I'm afraid I need to move on from the server. I mean, what's the point of playing hc if there are bugs like this. Anyway, you guys are doing great job with custom content, keep it up, cheers!
![WoWScrnShot_091122_143921](https://user-images.githubusercontent.com/93180842/189530376-8acbb65c-f255-45f2-8853-930a19350b29.png)
![WoWScrnShot_091122_143957](https://user-images.githubusercontent.com/93180842/189530379-4fe0502c-6c84-46ec-9141-e4c1c0b98773.png)

**Comment by ratkosrb** [comment]
The guard is not invisible, he gets summoned by the alliance civilian npc there. Steps have been taken to prevent this from happening again.
