### ISSUE TITLE
Ranged attack speed is bugged on my Character Daufina

### ISSUE THREAD

**Issue by Dauf2** [slowtorta/turtlewow-bug-tracker#2106]
**Please, provide a clear description what the bug is:**

Ranged attack speed is bugged. Ranged weapon speed is 3.3 and is not taking into account my quiver increasing my ranged attack speed.

**Steps to reproduce the behavior with as much detail as possible:**

Not sure, seems to be isolated to just my character. Created another level 1 hunter and the ranged attack speed calculations seem to be working fine

**IDs of affected creatures, items, quests or spells with a link to the relevant page:**

Any quiver and ranged weapon combo I equip is not taking the increase in ranged weapon speed provided by the quiver

**Expected behavior. Describe how it should work:**

weapon speed is 3.3
quiver is 13% increased ranged attack speed
Attack_speed = 3.3 / ( (13 / 100) + 1 ) = 2.92 not 3.3

![Ranged Attack Speed Bugged](https://user-images.githubusercontent.com/113302922/189544035-cb2b85b1-fbf1-43fb-8b63-6d05075302a8.JPG)

**Comment by Dauf2** [comment]
https://user-images.githubusercontent.com/113302922/190040211-35404782-80ab-4546-ab9c-67338e809b8d.mp4

**Comment by geojak** [comment]
Are you use using that new crossbow with the bugged animation (uses gun animation)

Are you sure it's not just that item bugged instead of your char

**Comment by Dauf2** [comment]
any weapon and quiver combo I equip is not conferring the correct attack speed.

**Comment by Dauf2** [comment]
Thanks for the tip. Through various combinations of equipping bullet bags, other ranged weapons and the like, it seems to work. I suppose the twow developers should try to fix the item then.

**Comment by Iacov** [comment]
Issue still persists as of 16/10

**Comment by jameyboor** [comment]
What item is this?

**Comment by geojak** [comment]
Probably https://database.turtle-wow.org/?item=60624

**Comment by slowtorta** [comment]
Fixed on the next update.
