### ISSUE TITLE
Mother's Milk quest as a High Elf

### ISSUE THREAD

**Issue by Isarke** [slowtorta/turtlewow-bug-tracker#2107]
**Please, provide a clear description what the bug is:**
As a High Elf the NPCdoesn't have a prompt in the window to remove the poison and complete the quest
**Steps to reproduce the behavior with as much detail as possible:**

1.Got the Mother's Milk poison debuff
2. NPC doesnt have the prompt to "milk it" to remove it and finish the quest for a High Elf
3. 

**IDs of affected creatures, items, quests or spells with a link to the relevant page:**

NPC: https://database.turtle-wow.org/?npc=9563
Item: https://database.turtle-wow.org/?item=
Quest: https://database.turtle-wow.org/?quest=4866
Spell: https://database.turtle-wow.org/?spell=
Object: https://database.turtle-wow.org/?object=

**Expected behavior. Describe how it should work:**
Prompt under the quest text to remove it and finish the quest

**Comment by ratkosrb** [comment]
I am unable to reproduce the issue.
https://streamja.com/3m4Mb

**Comment by Isarke** [comment]
https://i.imgur.com/gUi17Jg.png

idk what it is it doesn't work for me

**Comment by Isarke** [comment]
GM helped me by finishing the quest
