### ISSUE TITLE
Lamp disappear if walked close to it

### ISSUE THREAD

**Issue by Shellyoung** [slowtorta/turtlewow-bug-tracker#2109]
**Please, provide a clear description what the bug is:**

There is a house in the south seas with a lamp inside it that disappear if walk close to it.

![Ошибка  Лампа исчезает](https://user-images.githubusercontent.com/40469927/189543383-b7dafb4b-97b3-4819-816c-479b910ff9ec.gif)

### Location:
Sandy island that is not on world map north from Tanaris.
![Location](https://user-images.githubusercontent.com/40469927/189544879-b1c44a8d-286e-44cd-8005-564abc74b929.jpg)

### The house:
![house](https://user-images.githubusercontent.com/40469927/189544886-a9c44e39-b67f-49d9-9fe4-89176e71819b.jpg)

**Steps to reproduce the behavior with as much detail as possible:**

1. Find the lamp
2. Walk to it until it disappear

**Expected behavior. Describe how it should work:**
The lamp should hang without disappearing.

**Comment by slowtorta** [comment]
This is the original client glitch and it's not really worth to initiate editing of this zone in Noggit just for the lamp, I'm sorry.
