### ISSUE TITLE
High Priestess Jeklik aoe silence radius is too large

### ISSUE THREAD

**Issue by Velite12** [slowtorta/turtlewow-bug-tracker#211]
https://youtu.be/R48hdaKR_BU?t=196

As you can see in the video, at the range of drain mana (Warlock) you should not get silenced, but you do get silenced on this server.

https://database.turtle-wow.org/?npc=14517

**Comment by jameyboor** [comment]
No repro. The spell casted is set on a radius of 20 yards which is Blizzlike.
