### ISSUE TITLE
Whip of Encouragement does not work on spell casts

### ISSUE THREAD

**Issue by balakethelock** [slowtorta/turtlewow-bug-tracker#2111]
**Please, provide a clear description what the bug is:**
Whip of Encouragement is different from the other haste items and is the only one that doesn't work on spell casts

**Steps to reproduce the behavior with as much detail as possible:**
1.Equip any haste item
2. notice that it affects cast time
3. equip whip
4. notice that it doesn't affect

**IDs of affected creatures, items, quests or spells with a link to the relevant page:**
Item: https://database.turtle-wow.org/?item=60501
Spell that doesn't work: https://database.turtle-wow.org/?spell=13680
Spell that works: https://database.turtle-wow.org/?spell=13679
spell that works has "(6) Apply Aura #65: Haste - Spells value 2" effect

**Expected behavior. Describe how it should work:**
Haste 3 should have **"(6) Apply Aura #65: Haste - Spells value 4"** to work with spells

**Comment by geojak** [comment]
Enchantments also don't work.

Dragunovi confirmed enchants on hands, pants, head, and even 3% on weapk should all work too, or not?

**Comment by balakethelock** [comment]
Still bugged as of 21/09/2022

**Comment by ratkosrb** [comment]
Until you see fixes mentioned in the official changelog, they are not live.
