### ISSUE TITLE
Quest: "Salve via Disenchanting" not available from Maybess Riverbreeze with enchanting learned

### ISSUE THREAD

**Issue by woody-b** [slowtorta/turtlewow-bug-tracker#2112]
**Please, provide a clear description what the bug is:**
I can't recieve the quest Salve by disenchanting. Character Woob.

**Steps to reproduce the behavior with as much detail as possible:**

1. Learn enchanting.
2. See the quest.
3. Many months later.
4. Quest no longer appearing.

**IDs of affected creatures, items, quests or spells with a link to the relevant page:**

Four different identical named quests for this, so I just picked one out of the hat.
Quest: https://database.turtle-wow.org/?quest=5886
NPC: https://database.turtle-wow.org/?npc=9529

**Expected behavior. Describe how it should work:**
Should have the quest for my profession.
![image](https://user-images.githubusercontent.com/59381153/189766684-a8c28eb4-353c-4405-b231-31348051c0f1.png)
![image](https://user-images.githubusercontent.com/59381153/189766767-9a2fabb9-2a66-4f84-bcec-09abdb9a4400.png)
![image](https://user-images.githubusercontent.com/59381153/189766791-c5690f43-3d61-43ac-a48a-a819f6beadc3.png)

**Comment by woody-b** [comment]
I'm not sure if unlearning it and skilling it back up might help fix it. Also not sure if I would lose all my recipes doing that.

**Comment by Tinyfin-github** [comment]
Greetings!  To unlock  the quests Salvia you need to complete the first quest in the chain <Cleansing Felwood>.
This is the correct behavior for both turtle and classic.
https://database.turtle-wow.org/?quest=4102
https://classic.wowhead.com/quest=4101/cleansing-felwood

**Comment by woody-b** [comment]
Well it still looks a bit scuffed. I can still do some of the quests with Maybess.
