### ISSUE TITLE
Omen of Clarity proc rate

### ISSUE THREAD

**Issue by burner1024** [slowtorta/turtlewow-bug-tracker#2115]
**Please, provide a clear description what the bug is:**
 Omen is procing too rarely.
#1963 is closed as fixed, it is not fixed and changelog doesn't mention anything about fixing it.

**Steps to reproduce the behavior with as much detail as possible:**
1. Cast Omen.
2. Shift to cat, start attacking training dummy.
3. Count procs.
![Captura de pantalla de 2022-09-13 17-56-52](https://user-images.githubusercontent.com/1279852/189884760-4b475118-800c-4051-a117-201c79c65fc2.png)

**IDs of affected creatures, items, quests or spells with a link to the relevant page:**
https://database.turtle-wow.org/?spell=16864

**Expected behavior. Describe how it should work:**
2 ppm from autoattacks, +extra from spells and abilities, based on corresponding form's attack speed (bear/cat/travel/aquatic) and base spell cast time (humanoid/moonkin).

**Comment by ratkosrb** [comment]
It is at 2 currently, but since you say its only 1 in practice, I've doubled it to 4, and perhaps your addon will report its 2 now.

**Comment by burner1024** [comment]
Effective immediately?

**Comment by ratkosrb** [comment]
No, effective whenever server gets updated next.

**Comment by burner1024** [comment]
@ratkosrb I'm sorry, but I'm still not getting anywhere near right numbers.
I increased sample sizes and recorded 2 full 30 min sessions (cat):
![Captura de pantalla de 2022-09-28 20-13-33](https://user-images.githubusercontent.com/1279852/192805074-0039bc0d-15cc-41bf-821c-1b30f2e8929d.png) ![Captura de pantalla de 2022-09-28 21-22-13](https://user-images.githubusercontent.com/1279852/192805081-cae1e207-2b57-4e93-b7f9-5628ab2a6223.png)

Assuming proc chance of 3.33% for cat autoattack, my estimation is that first screenshot has only 4% chance of happening, and second one is about 15%, which together makes 0.6% - pretty solid number suggesting that something's off.
But you don't have to take my word for it - just test for yourself.

**Comment by burner1024** [comment]
@ratkosrb so what do you say? Is this data enough?
