### ISSUE TITLE
Sharpened Claws doesn't match website/ingame

### ISSUE THREAD

**Issue by KanseiDrift** [slowtorta/turtlewow-bug-tracker#2116]
The talent Sharpened Claws in the feral druid tree does not match the one on the website. 

The Turtle wow website calculator shows that Sharpened claws has a maximum of 2 points that can be invested in it.
However ingame, 3 points can be invested into Sharpened Claws. 

https://database.turtle-wow.org/?spell=16942

**Comment by slowtorta** [comment]
The website calculator isn't updated yet but we're working on it.
