### ISSUE TITLE
Can't decurse on Moonkin Form

### ISSUE THREAD

**Issue by MishailTM** [slowtorta/turtlewow-bug-tracker#2117]
Even though it was announced we could decurse in moonkin form. We are still unable to do so.

**Steps to reproduce the behavior with as much detail as possible:**

1. Enter Moonkin form
2. Cast Decurse
3. Get error message you are shapeshifted and forced to go outside of moonkin form.

**IDs of affected creatures, items, quests or spells with a link to the relevant page:**

Spell: https://database.turtle-wow.org/?spell=24858 <- Moonkin form
https://database.turtle-wow.org/?spell=2782 <- Remove Curse

**Expected behavior. Describe how it should work:**
As said in Moonkin form tooltip: The Moonkin can only cast Balance spells, Innervate, AND REMOVE CURSE while shapeshifted. The act of shapeshifting frees the caster of Polymorph and Movement Impairing effects.

**Comment by ratkosrb** [comment]
As was said in the changelog, this requires a client patch to work. The restriction is removed server side, but the client does it's own checks based on its own copy of the data, which can only be updated with a new MPQ patch. You have to wait for the new client patch to be released.
