### ISSUE TITLE
Outdated hunter talent tree in talent calculator

### ISSUE THREAD

**Issue by marcuis** [slowtorta/turtlewow-bug-tracker#2118]
Outdated hunter survival talent tree in talent calculator. 

**Steps to reproduce the behavior with as much detail as possible:**

1.Go to https://talents.turtle-wow.org/hunter

**Expected behavior. Describe how it should work:**
The first row, 3rd talent (deflection) should be the improved Raptor Strike talent.

**Comment by slowtorta** [comment]
We're aware of this issue and it's listed in our internal tracker.
