### ISSUE TITLE
Pseudo-join a battleground

### ISSUE THREAD

**Issue by usedcars4cheap** [slowtorta/turtlewow-bug-tracker#2119]
Client crashed during WSG loading screen, and on subsequent login I was pushed outside the battleground with deserter debuff, except I was also participating in the battleground?

![WoWScrnShot_091422_012111](https://user-images.githubusercontent.com/68176649/190110019-584f4f7a-3aeb-4def-8cf2-1ddc60d9ddae.jpg)
Note the deserter debuff, and quest turn-in in between flag capture activity on the chat log.

Upon completion of the battleground, my character could not move or use abilities, just like at the conclusion of a normal battleground. Relogging allowed me to act normally again.
![WoWScrnShot_091422_012518](https://user-images.githubusercontent.com/68176649/190110370-5b9ad07f-39ea-4dd9-931a-0dd83d51dc7b.jpg)
Note the lack of "participation" (0 kills / deaths / HKs)

No idea what's going on here.

**Comment by slowtorta** [comment]
99% impossible to reproduce :( Super rare edge case, I'm sorry!
