### ISSUE TITLE
General Rajaxx next waves should immediately and only trigger after the entire previous wave dies.

### ISSUE THREAD

**Issue by Velite12** [slowtorta/turtlewow-bug-tracker#212]
https://youtu.be/X4Qd9DftF0g

According to 2006 vanilla, when the last mob of the wave dies (captain or regular adds) dies, the next wave comes in.

Currently, the next wave comes in when the captain dies, which always forces you to kill the captains last.

**Comment by jameyboor** [comment]
Fixed.
