### ISSUE TITLE
Insect Swarm Lv 3 Not showing in Spell book, but does show Already Learned spell in Trainer

### ISSUE THREAD

**Issue by Tuckerfly** [slowtorta/turtlewow-bug-tracker#2124]
**Please, provide a clear description what the bug is:**
Insect Swarm Lv 3 is Unlearnable from any druid trainer on my character: Wolfin

It states that the spell is already learned, but it does not appear in my spell book. In addition, the Insect Swarm lv 4 and above can not be learned as well, since it states I need to learn Insect Swarm Lv 3 first.
**Steps to reproduce the behavior with as much detail as possible:**

1.  I noticed that when I initially learned the spell, I purchased Lv 3 right away, and never actually purchased Lv 1 and 2. I play WOW a decent amount so i know that this is not normal behavior, and I should have purchased Lv 1 first, but i was being greedy and wanted to save Silver at the time, since it was allowing me to skip a couple steps and just purchase lv 3 right away

2. Unfortunately the best way to approach this would be for me to make another Druid and wait until Lv 40 to Learn Lv 3 first if that is even an option this time.
3. 

**IDs of affected creatures, items, quests or spells with a link to the relevant page:**
https://database.turtle-wow.org/?spell=5570
https://database.turtle-wow.org/?spell=24974
https://database.turtle-wow.org/?spell=24975
NPC: https://database.turtle-wow.org/?npc=
Item: https://database.turtle-wow.org/?item=
Quest: https://database.turtle-wow.org/?quest=
Spell: https://database.turtle-wow.org/?spell=24975
Object: https://database.turtle-wow.org/?object=

**Expected behavior. Describe how it should work:**
It should normally let me Use the spell th
![IS Lv3 bug 2](https://user-images.githubusercontent.com/113559669/190273254-910959a6-5205-4a0f-aadb-40ac4ff5a98e.PNG)
![IS Lv3 bug](https://user-images.githubusercontent.com/113559669/190273258-f3213f4e-e8c8-4d95-97ad-8c80e09d5632.PNG)
![IS Lv3 bug3](https://user-images.githubusercontent.com/113559669/190273259-8e095819-48c3-4b6b-958c-f87b351af70c.PNG)
at was "Learned" and then purchase Insect Swarm 4,5,6 without soft locking the spell

Screenshots attached below. I work Support too for my Career, so I appreciate the Support! Love you guys! :)
![IS Lv3 bug](https://user-images.githubusercontent.com/113559669/190273432-244a9ecb-6ed1-475c-92c7-ab5b0810a404.PNG)
![IS Lv3 bug3](https://user-images.githubusercontent.com/113559669/190273438-0f7fa839-f89f-4a1f-8c02-1546d906f15c.PNG)
![IS Lv3 bug 2](https://user-images.githubusercontent.com/113559669/190273440-78eacd22-5a60-40df-96f0-e081b84d6abb.PNG)

**Comment by eX1stenZT** [comment]
Yup, same issue on my druid.

Got only lvl1+2 in spell book, trainer will not teach me lvl3 or higher.

**Comment by slowtorta** [comment]
Fixed, but requires a client update.
