### ISSUE TITLE
school of fishes in booty bay are not random

### ISSUE THREAD

**Issue by geojak** [slowtorta/turtlewow-bug-tracker#2125]
**Please, provide a clear description what the bug is:**

the school of fishes in booty bay alwasy respawn with the same fish. meaning there is this 1 stonescale fish school that resapwn every 5(?) minutes always at the same palce that most fisher know is the best spot on the server since nowhere else you have a guranted stonescale eel respawn or a wreckage with mithril trunks every few minutes.

on the otehr hand the other fish school in booty bay are completely useless becuase everyone knows the NEVER spawn stonescale school or wreckages, always the same firefin and mudschnapper.

**Expected behavior. Describe how it should work:**

the school of fishes in booty bay should respawn randomly. meaning every school spot can be eitehr firefin, stonescale and mudsnapper and not fixed location.

**Comment by geojak** [comment]
p.s. this is a prime fish bot location since htye can just spam fish at the same palce for ever

**Comment by geojak** [comment]
@ratkosrb could you check the respawn times of the school of fishes. the ones in my screenshot above respawns significantly faster than the others. could you pls reopen the issue for that?

thank you for the other fix, i think you made it that the other school can also have stonescale now? atleat i saw one palce with stonescale that i have only seen with firesnapper before

**Comment by ratkosrb** [comment]
I updated the respawn time for all 4 spots in Booty Bay.
