### ISSUE TITLE
Super-Seller 680 absent

### ISSUE THREAD

**Issue by Delired73** [slowtorta/turtlewow-bug-tracker#2129]
**Please, provide a clear description what the bug is:**

**Steps to reproduce the behavior with as much detail as possible:**

1. Just go on coordonates 40.5, 79.3 in Desolace. You will see the PNJ Super-Seller 680 isn't here

**IDs of affected creatures, items, quests or spells with a link to the relevant page:**
NPC: https://database.turtle-wow.org/?npc=12246

**Expected behavior. Describe how it should work:**

The NPC should be always present at the coordonates mentionned on the database

**Comment by Tinyfin-github** [comment]
![image](https://user-images.githubusercontent.com/83077166/190577280-745af5be-7f9a-414b-bab0-a255e00310d5.png)

The npc is the correct location

**Comment by Delired73** [comment]
Hello,

Thank you for the answer, but I'm at the exact same location and I don't see him : 
![image](https://user-images.githubusercontent.com/113647022/190599430-54c81c90-fa03-4253-84e1-b12821e60a1a.png)


Plus, I saw that was a part of a caravan, I found the caravan at desolace north but seems bug: the caravan isn't moving at all depside the fact it's on the road : 
![image](https://user-images.githubusercontent.com/113647022/190597066-3bac80ab-4a7e-41de-8928-21d341dfabd6.png)
![image](https://user-images.githubusercontent.com/113647022/190599039-29b98924-4a43-4d08-81dc-c4b66b0aed91.png)


Does that means that I have to make the escort quest to see him ?
