### ISSUE TITLE
Thaddius Phase 2 his initial target seems to not be based on proximity

### ISSUE THREAD

**Issue by Velite12** [slowtorta/turtlewow-bug-tracker#213]
https://youtu.be/3hen_d6cb-Y

I was watching this video, and when they reach phase 2 of Thaddius, he appears to be attacking the main tank before the main tank even attacks, on turtle wow he chooses to attack a random member of the raid.

**Comment by jameyboor** [comment]
Currently he attacks the nearest target after threat reset as looks to be Blizzlike, closing for now.
