### ISSUE TITLE
Underground Mining Node

### ISSUE THREAD

**Issue by usedcars4cheap** [slowtorta/turtlewow-bug-tracker#2130]
You are OUTdoor
Map: 0 (Eastern Kingdoms) Zone: 45 (Arathi Highlands) Area: 45 (Arathi Highlands)
X: -567.190186 Y: -2007.087158 Z: 64.303810 Orientation: 1.664125
grid[28,30]cell[3,14] InstanceID: 0
 ZoneX: 31.678349 ZoneY: 18.077370
GroundZ: 79.899635 FloorZ: 79.899635 Have height data (Map: 1 VMap: 1)

![image](https://user-images.githubusercontent.com/68176649/190527198-91027f30-b479-41cb-9815-a27f11cd1e0a.png)

**Comment by slowtorta** [comment]
Please use GM command `.gm move GUID XYZ` to move the object right in the game w/o creating a report.
