### ISSUE TITLE
Booldring gryphon

### ISSUE THREAD

**Issue by geojak** [slowtorta/turtlewow-bug-tracker#2133]
**Please, provide a clear description what the bug is:**

queue bloodring
be on a gryphon
click enter
be ported into blood ring
still on a grypon
fligh away into the void out of the arnea
???

**Expected behavior. Describe how it should work:**

gryphon canceled in arena, restored afterwards or atleat ported to destination of the gryphon

**Comment by geojak** [comment]
![WoWScrnShot_091622_143645](https://user-images.githubusercontent.com/25199983/190640444-fb66c958-145c-4b3a-999a-4455bfe81f94.jpg)

sometimes you are also just stuck for a minute

**Comment by redmagejoe** [comment]
Cannot reproduce on current version.

Fixed.
