### ISSUE TITLE
[Spell]Thunderclap [NPC]Skeletal Smith

### ISSUE THREAD

**Issue by Meanwalk** [slowtorta/turtlewow-bug-tracker#214]
**Please, provide a clear description what the bug is:**
Thunderclap range is about 60+- yards.
**Steps to reproduce the behavior with as much detail as possible:**
1. Pull at maximum range.
2. Run to maintain distance.
3. Take claps. :D
-Did hunter pet suicide pulls to confirm it-
**IDs of affected creatures, items, quests or spells with a link to the relevant page:**

NPC: https://database.turtle-wow.org/?npc=16193
Spell: https://database.turtle-wow.org/?spell=23931

**Expected behavior. Describe how it should work:**
Should affect all hostile units in 10ya radius.

**Comment by Nolin7777** [comment]
Not able to reproduce
