### ISSUE TITLE
Wastewander npcs in Tanaris give fake reputation

### ISSUE THREAD

**Issue by FeyfolkenFantasy** [slowtorta/turtlewow-bug-tracker#2147]
**Please, provide a clear description what the bug is:**

The Wastewander npcs in Tanaris (Wastewander Bandits, Thieves, Assassins, Rogues and Shadow Mages) give 5pts of reputation to Gadgetzan when killed, up to Friendly.
But past Friendly, when you kill those mobs it is written in your chat window that they now give 5pts to the Steamwheedle Cartel which is wrong, they don't give any reputation points at all.

**Steps to reproduce the behavior with as much detail as possible:**

1. Get your reputation to Gadgetzan to Honored for example.
2. Check your four Steamwheedle reputations.
3. Go kill those Wastelander npcs and notice de message in your chat windows stating that your Steamwheedle Cartel reputation has increased by 5pts.
4. Notice that none of the four reputations has increased.

![WoWScrnShot_091622_221802](https://user-images.githubusercontent.com/102554573/190729218-7c9bc561-c6b9-481a-81d0-f63183fa1cd5.jpg)

**IDs of affected creatures, items, quests or spells with a link to the relevant page:**

NPC: https://database.turtle-wow.org/?npc=5615
NPC: https://database.turtle-wow.org/?npc=5616
NPC: https://database.turtle-wow.org/?npc=5617
NPC: https://database.turtle-wow.org/?npc=5618
NPC: https://database.turtle-wow.org/?npc=5623

**Expected behavior. Describe how it should work:**

Past Friendly to Gadgetzan, those npcs shall not give any reputation at all.
They do try because they are nice people, but they fail every time xD

**Comment by redmagejoe** [comment]
This issue persists. Not gaining any reputation for kills in Ratchet, Everlook, Gadgetzan, or Booty Bay despite Combat Log saying I'm gaining 1 per kill.

**Comment by GrenderG** [comment]
Related https://github.com/vmangos/core/issues/849

**Comment by Gurky-Turtle** [comment]
https://github.com/slowtorta/turtlewow-bug-tracker/issues/3984

**Comment by Muigin** [comment]
While I'm not sure if the underlying Faction awarding sub-faction rep behavior has been addressed, on Turtle, all kills now individually award sub-faction rep to address this.

Considering this working as intended for all intents and purposes.
