### ISSUE TITLE
survival bright campfire bug

### ISSUE THREAD

**Issue by Mentlegeen** [slowtorta/turtlewow-bug-tracker#215]
after hitting lvl 15 in survival, i grabbed the pattern for bright campfire. it caused me to learn it twice and it turned out, one of them doesnt give a skill point at all, while the other skill does

**Steps to reproduce the behavior with as much detail as possible:**

1. be a hunter (no pet summoned)
2. use torches on normal campfire
3. learn bright campfire
4. get 2 skills, one of them doesnt give you a skill point, however it still provides you with rested xp buff and the spirit buff

**IDs of affected creatures, items, quests or spells with a link to the relevant page:**

NPC: https://database.turtle-wow.org/?npc=50070
Item: https://database.turtle-wow.org/?item=50254
Quest: https://database.turtle-wow.org/?quest=
Spell: https://database.turtle-wow.org/?spell= (cant find spell in database)
Object: https://database.turtle-wow.org/?object=

you should learn skill only once and remove the other bugged entity or whatever it is

update: now that i used the proper bright campfire spell, it seems both of them now function indentically.

**Comment by slowtorta** [comment]
Thanks for reporting it. It'll be fixed on the next server restart. Make sure to clear your WDB folder.
