### ISSUE TITLE
Natural Weapons hit% missing.

### ISSUE THREAD

**Issue by Sygmoond** [slowtorta/turtlewow-bug-tracker#2151]
**Please, provide a clear description what the bug is:**

Natural weapons is a talent in the second row of the balance tree that reads as following: 
Natural Weapons (3 ranks)
Increases the damage you deal with physical in all forms by 4/7/10% and increases your chance to hit with melee attacks and spells by 1/2/3%. 

It might be affected totally or maybe the only problem is the tooltip, in either case I'm letting you guys know.

**Expected behavior. Describe how it should work:**

In case the problem is the talent not giving the corresponding stats, then it should give you 10% increased physical damage and 3% chance to hit. In case the bug is in the tooltip, well it should show in your character stats. 

Note I already have 3% hit chance provided by my head piece and my neck piece (Blooddrenched Mask and Fury of the Forgotten Swarm), so the stats should say 6% instead of 3%.

![imagen](https://user-images.githubusercontent.com/89550040/190808257-39bb36c2-c36a-4a4b-b402-7c7e20a8870b.png)

**Comment by geojak** [comment]
This is an addon problem.

**Comment by ratkosrb** [comment]
The server does not send hit chance to the client. You are using an addon to display it, which must be checking what talents you have active, and calculates it based on that, but your addon was not made for the current version of talents in turtle wow, so it doesn't know it should add hit % to the total when you select the talent.
