### ISSUE TITLE
[Hunter] Viper Stinger Skill Stackable

### ISSUE THREAD

**Issue by 1ManaTap1** [slowtorta/turtlewow-bug-tracker#2152]
**Please, provide a clear description what the bug is:**
Viper stinger can be stacked multiple times by hunters and it shouldn't
![Screenshot_2](https://user-images.githubusercontent.com/110747992/190866584-45bd6abd-10ed-4acb-9e92-452a91b9271e.jpg)

**IDs of affected creatures, items, quests or spells with a link to the relevant page:**

Spell: https://database.turtle-wow.org/?spell=3034
        https://classic.wowhead.com/spell=14280/viper-sting
        https://vanilla-wow-archive.fandom.com/wiki/Viper_Sting

**Expected behavior. Describe how it should work:**
Can only one be active on a target

**Comment by Iacov** [comment]
@1ManaTap1 please read the description 
![image](https://user-images.githubusercontent.com/6597238/191300422-e073f7aa-496c-4ee3-a661-9fb3163e91cf.png)
Thanks.

**Comment by Velite12** [comment]
> @1ManaTap1 please read the description ![image](https://user-images.githubusercontent.com/6597238/191300422-e073f7aa-496c-4ee3-a661-9fb3163e91cf.png) Thanks.

![image](https://user-images.githubusercontent.com/45871932/193090505-f9fc5ecd-288f-4237-8f7e-106f2831d33f.png)
This is an accurate bug. On classic you can only have 1 viper sting on a target.

![image](https://user-images.githubusercontent.com/45871932/193090654-e2026695-61e9-4dae-8fcf-ad2e07cea5bf.png)
You can have 2 serpent stings.
