### ISSUE TITLE
Quest: The Hermit's Wrath

### ISSUE THREAD

**Issue by Sringaram** [slowtorta/turtlewow-bug-tracker#2153]
ID: https://database.turtle-wow.org/?quest=40213

The quest cannot be turned in. The NPC shows yellow question mark but won't talk to you.

**Comment by cyaohiri** [comment]
He gets bugged when taking or abandoning [Uncovering Evil](https://database.turtle-wow.org/?quest=40214). Someone must've bugged it before you were able to turn in your quest.

**Comment by slowtorta** [comment]
Hopefully fixed in the next update 🤞
