### ISSUE TITLE
Dungeon: Stormwind Vault loot issues

### ISSUE THREAD

**Issue by Sringaram** [slowtorta/turtlewow-bug-tracker#2155]
Sightless Leather Hood (https://database.turtle-wow.org/?item=60436) does not seem to drop at all. I haven't seen it even once after about 20 runs and neither have other people I asked around.

The final chest sometimes does not drop the transmog coin, I'd say in about 10% of cases.
Sometimes male taurens can not enter the room with the chest.

**Comment by geojak** [comment]
I have run vault about 15 Tines and seen the hood many times. I have never seen whip of encouragement drop ever, which is why I was there...

Close the issue, we just have bad luck
