### ISSUE TITLE
Blackmisth: Silver Skeleton key eats materials but no key

### ISSUE THREAD

**Issue by gustavoalmeidait** [slowtorta/turtlewow-bug-tracker#2156]
**Please, provide a clear description what the bug is:**
The recipe to craft Silver keys does not produce an output
**Steps to reproduce the behavior with as much detail as possible:**

1.Get rough stone for Rough Grinding Stones and Silver ingots.
2. Craft Silver Skeleton Key.
3. Check inventory. The materials are used but no item is added to the bag.

**IDs of affected creatures, items, quests or spells with a link to the relevant page:**
https://classicdb.ch/?item=15869

**Comment by geojak** [comment]
Did you check your keyring too?
