### ISSUE TITLE
[Hunter] FD + TRAP 

### ISSUE THREAD

**Issue by Hecleas** [slowtorta/turtlewow-bug-tracker#2158]
There are several problems and bugs for the FD and the trap.
Before specifying my details, I want to let you know that I have been playing hunt since 2009 and I have been beta tested for daemon and viper for those who know (the admins of Nostalrius Beta and Begins.), I am more commonly known under the pseudonym of Kaszia.

Bugs:
1) Sometimes when the pet takes physical damage, it keeps us in combat or brings us back into combat, while the entry and exit of combat for the hunter and his pet are interdependent. (It causes big problems when we try FD+trap) It's part of a general problem too, when we're out of combat, when we eat to regen, but our pet or the group makes us go into combat, we don't regen anymore, although we continue to eat, normally it doesn't happen. don't go like this

2) When we execute FD and we rotate the camera to the left or to the right (right click) it lifts us up immediately, except it's not supposed to lift us up, suddenly it produces an entry into direct combat.

3) The trap is not supposed to have a slight activation delay, it must be instantaneous, even if a war is charging us.
Because to put you in situation; a trap set in front of us, if a war charges us and at the time to put an automatic attack + a knee breaker (especially if it is end game stuff), it's over.
Except this is not supposed to be the case and the trap should activate instantly.

4) Traps can be resisted in pvp, but on the other hand the FD is not supposed to be resisted in PVP.
The talent point that reduces resist FD is useful for PVE.

5) to be checked, but it seems to me that our character is totally out of combat when the FD animation ends, which is not advantageous for those who have a long death animation.
Normally we go out of combat as soon as the spell is activated.

These are the major problems I encountered on the FD + TRAP.
Of course my expertise is based on wow vanilla of the time, on various sources, memories and old videos, which unfortunately the more time passes, the more they are likely to be deleted from you tube.

I have other bugs to report for the hunt. But this thread deals with the FD + TRAP

**Comment by Iacov** [comment]
For Reference:

https://database.turtle-wow.org/?spell=5384
https://database.turtle-wow.org/?spell=19287

Also why would you nerf https://database.turtle-wow.org/?item=19621 lol

**Comment by Hecleas** [comment]
Bump?

**Comment by redmagejoe** [comment]
This issue persists and needs to be looked into. Turtle is the only server where Feign Death + Freeze Trap seems difficult or downright impossible to achieve.

**Comment by ratkosrb** [comment]
You need to stop your pet from attacking before Feigning Death if you want to leave combat instantly and be able to place a trap. This is how it works on classic. If you continue attacking with the pet, you will remain in combat, despite Feigning Death.
