### ISSUE TITLE
Ancestral War Totem Xmog looks weird and off.

### ISSUE THREAD

**Issue by Sygmoond** [slowtorta/turtlewow-bug-tracker#2159]
Hey, noticed something extremely off when I transmogged my weapon (Battery-Powered Crowd Pummeler) with the Ancestral War Totem appearance. Here's the original weapon, this is not a transmog, this is how it looks normally.

![2 png](https://user-images.githubusercontent.com/89550040/191352211-e368ff64-15ec-4bfe-b181-740f4298c182.png)
![1](https://user-images.githubusercontent.com/89550040/191352225-bbcc19a7-1416-4cd7-a807-151c6d4b0999.png)

And then this is how it looks when  you mog into its appereance. The totem is upside down, unleveled and it sheathes on the opposite side.

![4](https://user-images.githubusercontent.com/89550040/191352692-fb753ccb-3b21-401f-8d26-63c427479035.png)
![3](https://user-images.githubusercontent.com/89550040/191352713-805d5173-4b9b-4b87-9ef1-577302bb2575.png)

**Comment by slowtorta** [comment]
Trandsmogged weapons always inherit the original weapons' sheath. Sadly we cannot change it with the current thansmog system, I'm sorry!
