### ISSUE TITLE
Wrong boots name

### ISSUE THREAD

**Issue by SierraNairn** [slowtorta/turtlewow-bug-tracker#216]
Wrong boots name
The boots name should not  be Tiny red dragon:
https://database.turtle-wow.org/?item=14756
Thats the name of  npc with the same id:
https://database.turtle-wow.org/?npc=14756

**Comment by slowtorta** [comment]
Thanks for reporting it. It'll be fixed on the next server restart. Make sure to clear your WDB folder.
