### ISSUE TITLE
PVP Rewards - Losers not gaining anything if game lasts less than 10 min

### ISSUE THREAD

**Issue by usedcars4cheap** [slowtorta/turtlewow-bug-tracker#2162]
Duplicate of [Issue # 660](https://github.com/slowtorta/turtlewow-bug-tracker/issues/660)

**Problem:** When in Arathi Basin or Warson Gulch and enemy team is dominated either 5 cap or 3-0 "incentivized rewards" are not being given.

**Steps to reproduce the behavior with as much detail as possible:**

Enter in AB
Get 5 capped
Lose the match
You will receive no rewards ie token or rep. Also it should be further noted as a part 2 to this that Bonus honor is not working in Arathi Basin at all for specific RSS gained.

**Expected behavior. Describe how it should work:**
Losers of specific Battlegrounds will now be rewarded accordingly to incentivize Battlegrounds.

**This behavior is consistent during one day during vanilla retail, reverted the next day:**
https://wowpedia.fandom.com/wiki/Battleground
![image](https://user-images.githubusercontent.com/68176649/191661928-315e2bd4-e792-4057-b610-bcd3391a6164.png)

**Comment by geojak** [comment]
It's like this, if the game closes because of too little players, then the side with fewer player get set nothing. If both side have same, then both get nothing. So you are incrtivises to help the enemy faction with one more player to win before in closes so you can get atleast a loser mark.

This is an outrsgoies situation which has caused lots of frustration and salt over then months and was complained about many times already

**Comment by usedcars4cheap** [comment]
To add to this, a battleground closing due to insufficient players appears to ignore completed objectives so far - e.g. a team can win in WSG by virtue of having more players even if they are down 0-2 flags.

To Geojak - is this accurate?
![image](https://user-images.githubusercontent.com/68176649/191705163-c8e9a4f6-d677-42ce-809b-afc7936e7c46.png)

**Comment by geojak** [comment]
That's is exactly accurate. It's a huge shit show if am being honest

**Comment by usedcars4cheap** [comment]
Edited table to reflect Geojak's observations

**Comment by jameyboor** [comment]
Starting next update all battlegrounds will at minimum reward 1 mark upon any form of draw or loss. Furthermore, the amount of players will no longer decide the winner of BGs that end prematurely but will rather be progression based per BG as follows:

- **Warsong Gulch**: Flags captured
- **Alterac Vallet**: No winner by default
- **Arathi Basin**: Resource points
- **Sunnyglade Valley**: Sparks earned
- **Blood Ring**: Players alive

**Comment by geojak** [comment]
That's amazing, thank you jamey!
