### ISSUE TITLE
Stormwind Vault rat gate bug

### ISSUE THREAD

**Issue by BloodRaven0** [slowtorta/turtlewow-bug-tracker#2165]
If someone walks through the door that is supposed to close and spawn rats, but quickly runs out again before the door has finished closing, the rats will not spawn and the group will be stuck. This is because the script to spawn the rats runs after the door, but only if there is still a player there. It should be one script that does both things, just with a delay.

There is one workaround, which involves a party member leaving the group, and a mage of the opposite faction polymorphing them, so they wander through the gate and trigger the rats. Not all groups have a mage and are crossfaction though.

**Comment by geojak** [comment]
Yea this bug than cause groups to be stuck at a closed gate and a wasted dungeon Id.

Pls, fix it
