### ISSUE TITLE
Sun's Embrace

### ISSUE THREAD

**Issue by Apimius** [slowtorta/turtlewow-bug-tracker#2166]
Sun's Embrace usage causes an global cooldown which should not be the case i think

**Steps to reproduce the behavior with as much detail as possible:**

1. Use the high elf racial Sun's Embrace
2. Notice the GCD going off
3. Be sad 

**IDs of affected creatures, items, quests or spells with a link to the relevant page:**

Spell: https://database.turtle-wow.org/?spell=46046

**Expected behavior. Describe how it should work:**

You should be able to continue your rotation after using Sun's Embrace otherwise it disrupts any synergy with trinkets or power infusion

**Comment by slowtorta** [comment]
Reworking this spell completely in 1.16.4, stand by.

**Comment by Apimius** [comment]
Oh god i am scared. Any info on what kind of change yet?
