### ISSUE TITLE
npc Razzle Longpipe only horde friendly (should be Neutral)

### ISSUE THREAD

**Issue by Khanz0** [slowtorta/turtlewow-bug-tracker#2167]
The npc Razzle Longpipe in Durotar (new goblin city) is only horde friendly in game. The database says he is neutral but you cant buy his unique items as aliance (and those items are bop so cant get from other source)

Could you turn him into neutral as the Db says so aliance players can buy his rarities too? (In fact he sells a legplates for paladins. Something that horde dont have)

Thanx

**Comment by slowtorta** [comment]
Sparkwater Port is a Horde city and Razzle is a Horde NPC. Online DB has a few issues but in the game, he's working as intended. Maybe eventually Alliance will have a similar vendor in one of the new locations! :)
