### ISSUE TITLE
NPC: Twilight Prophet

### ISSUE THREAD

**Issue by Sringaram** [slowtorta/turtlewow-bug-tracker#2169]
ID: https://database.turtle-wow.org/?npc=15308

Their escort and spawn logics are all kinds of messed up.

1. The bodyguards are linked to the prophet but not the other way around. You can separate and pick the bodyguards one by one through sap and/or distract. Stopping a prophet will make the whole pack stop and wait for her.

2. The prophets seem to respawn randomly or not respawn at all. Meanwhile the bodyguards just slowly respawn (based on the time you killed them) and stand still in a place. It seems like prophets may sometimes not respawn at all until a reboot.

3. I have seen a prophet and her pack zoom across Silithus at sonic speed as if they were leashed but much faster. Perhaps a conflict between spawn points or the prophet spawning somewhere away from her bodyguards?

The prophets are the principal source of rep texts so it's quite a big deal not being able to farm them.

**Comment by geojak** [comment]
Prophet only respawna after all bodyguards are killed too. If you pick out the prophet but leveaw her Escort alive, then it will never respawn.

**Comment by geojak** [comment]
For your number 3 point, i also made an issue a few weeks ago on her. It's still open

**Comment by Sringaram** [comment]
I've had a whole pack of bodyguards just stand around for a long while without prophet anywhere on sight. Shouldn't they spawn all together once the prophet respawns?

I was looking at this: https://classic.wowhead.com/npc=15308/twilight-prophet#comments

There are some interesting things such as:

She will respawn regardless of the bodyguards being killed but it'll take longer if you don't. - Not the case here apparently.
You can separate her from the bodyguards through sap/distract and kill her alone. - Not the case here either.
The respawn point is close to where you killed her. - Not the case here, it seems to be fixed.

**Comment by Sringaram** [comment]
I just got killed by the whole pack just appearing from under the ground, killing me and then zooming across Silithus at light speed. This wasn't even anywhere near their spawn points.

**Comment by slowtorta** [comment]
Duplicate to https://github.com/slowtorta/turtlewow-bug-tracker/issues/3137
