### ISSUE TITLE
Zone: Crescent Grove

### ISSUE THREAD

**Issue by cyaohiri** [slowtorta/turtlewow-bug-tracker#2170]
In an area in Crescent Grove, player location is shown as Vilethorn Scar, which is an area inside Crescent Grove with the spirits, but the player location should always show "Crescent Grove". Upon entering this area, the public channels also change to Vilethorn Scar, instead of staying Crescent Grove for the entire dungeon.

**Comment by slowtorta** [comment]
Fixed in 1.16.4.
