### ISSUE TITLE
Item: Treasure Seeker's Torch

### ISSUE THREAD

**Issue by cyaohiri** [slowtorta/turtlewow-bug-tracker#2172]
When sheathed, [Grayson's Torch](https://database.turtle-wow.org/?item=1172) is visible on the character, but [Treasure Seeker's Torch](https://database.turtle-wow.org/?item=50049) isn't.

**Comment by slowtorta** [comment]
Seems rather wrong to make them visible when sheathed... 

![image](https://user-images.githubusercontent.com/66763404/192093031-8f9d0eff-0de9-4bc6-aab5-fc10ea952eb2.png)

**Comment by cyaohiri** [comment]
That might be true, but the Treasure Seeker's Torch is the exception, not the rule. Other torches (those present in vanilla) are visible when sheathed, which is why I thought this one was unintentionally made invisible.

**Comment by Apimius** [comment]
> That might be true, but the Treasure Seeker's Torch is the exception, not the rule. Other torches (those present in vanilla) are visible when sheathed, which is why I thought this one was unintentionally made invisible.

This! The torch offhands from original vanilla/classic wow were visible when sheadthed. I had [Grayson's Torch](https://database.turtle-wow.org/?item=1172) in classic wow and it was visible there.
