### ISSUE TITLE
NPC: Horde Peon

### ISSUE THREAD

**Issue by cyaohiri** [slowtorta/turtlewow-bug-tracker#2184]
Horde Peons attempt to run away in fear as soon as they're engaged (same behavior as other humanoids when on low life). Based on this [comment](https://classic.wowhead.com/npc=11656/horde-peon#comments), they are supposed to run towards the nearest grunt or scout.

NPC: https://database.turtle-wow.org/?npc=11656

**Comment by geojak** [comment]
That's a general bug. Npcs running in fear should aways go for nearest ally. On here they run randomly

**Comment by cyaohiri** [comment]
If you mean units running away on low life, they don't run randomly, they always run away from you. Is that not the way it's supposed to be?

**Comment by redmagejoe** [comment]
NPCs are behaving as they should, running in opposite direction they're facing with a bias towards nearest ally as soon as they're engaged. These are not the only NPCs who do this on engage rather than at low life.

Working as intended.
