### ISSUE TITLE
Quest: Return to Kheyna

### ISSUE THREAD

**Issue by spacestr** [slowtorta/turtlewow-bug-tracker#2188]
**Please, provide a clear description what the bug is:**
Returning to the crystal and interacting with it spawn Chromie instead of Kheyna Spinpistol

**Steps to reproduce the behavior with as much detail as possible:**

1. Complete quest "A Letter From a Friend"
2. Complete quest "A Slaughter for Brains"
3. Attempt to complete quest "Return to Kheyna"

**IDs of affected creatures, items, quests or spells with a link to the relevant page:**

NPC: https://database.turtle-wow.org/?npc=
Item: https://database.turtle-wow.org/?item=
Quest: https://database.turtle-wow.org/?quest=80409
Spell: https://database.turtle-wow.org/?spell=
Object: https://database.turtle-wow.org/?object=

**Expected behavior. Describe how it should work:**
Interacting with crystal on this quest should spawn Kheyna Spinpistol

**Comment by slowtorta** [comment]
Duplicate https://github.com/slowtorta/turtlewow-bug-tracker/issues/1622
