### ISSUE TITLE
Track Quest not working consistently

### ISSUE THREAD

**Issue by NinaFelwitch** [slowtorta/turtlewow-bug-tracker#2189]
**Please, provide a clear description what the bug is:**
I can't track quests after turning in finished quests

Workaround: Logging out and back in, quests are trackable again.

**Steps to reproduce the behavior with as much detail as possible:**

1. Have a bunch of trackable quests
2. Track up to 5 of them
3. Finish the tracked quests
4. Try to track remaining quests

**Expected behavior. Describe how it should work:**
Tracking Quests should work.

**Comment by cyaohiri** [comment]
A faster workaround is to reload your UI with "/console reloadui" or "/reload".

**Comment by cyaohiri** [comment]
Sometimes a quest will get tracked up to three times, displaying the same objectives three times, and requiring you to shift-click it in your quest log three times to hide it (each click untracks one copy of the quest).

**Comment by jameyboor** [comment]
This is a client issue that would be unfeasible to fix. For now please use the workaround. Sorry.
