### ISSUE TITLE
Instance portals brake

### ISSUE THREAD

**Issue by Rhade15** [slowtorta/turtlewow-bug-tracker#2192]
**Please, provide a clear description what the bug is:**
As soon as I join a party/raid the instance portals stop working, meaning that when I walk thru the portal the instance doesn't load. This bug persists even if I leave the group. The only way I found to fix it is to reboot the application. I have reinstalled the client from your website on a different hard drive but the issue persists. It seems to only happen when I'm inside the Moomoo Grove while accepting the invite.
**Steps to reproduce the behavior with as much detail as possible:**
Be inside the Moomoo Grove and accept a party/raid invite. Hearth out to Stormwind and try walking thru any instance portal.
**IDs of affected creatures, items, quests or spells with a link to the relevant page:**
None
**Expected behavior. Describe how it should work:**
The instance should load

https://user-images.githubusercontent.com/114367453/192170879-85a30088-0061-4c28-8524-ef1ff1d3a8b6.mp4

https://user-images.githubusercontent.com/114367453/192170885-b9421491-ea36-4316-b5d2-a1eeb903a1f0.mp4

**Comment by cyaohiri** [comment]
I've had similar issues after doing dungeons. This bug also prevents you from entering Darnassus. Relog fixes it though.

**Comment by geojak** [comment]
Also sw mage tower portal.

A relog fixes it

**Comment by Rhade15** [comment]
The relog does indeed fix it for that group but the issue is recurring and
quite frustrating

**Comment by Rhade15** [comment]
I've managed to replicate the bug and have updated my post accordingly

**Comment by slowtorta** [comment]
Fixed.
