### ISSUE TITLE
Spirit Link Does not Work

### ISSUE THREAD

**Issue by Mawataki** [slowtorta/turtlewow-bug-tracker#2193]
I m playing Tauren Shaman. Level 52 and learned Spirit Link without any problem when i was around 40-45 levels. When i m using "Spirit Link", it only leaves a buff on my main target. And other players around my target in 15 yards, doesn't get the spirit link buff. So the spell doing nothing by this. 

Spell: https://database.turtle-wow.org/?spell=45500#see-also-ability

It should Link the spirits of an ally and their 3 closest allies within 15 yards together. When linked targets take damage, 15% is distributed among the other linked allies. Lasts 30 sec.

**Comment by cyaohiri** [comment]
Should it say "15% is distributed among linked group members" rather than nearby allies, as it links to group members?

**Comment by Mawataki** [comment]
So its working but there will be no buff on linked players ?
