### ISSUE TITLE
Experience gain in a group with experience modifiers

### ISSUE THREAD

**Issue by cyaohiri** [slowtorta/turtlewow-bug-tracker#2194]
Experience modifiers (War Mode and Slow & Steady) do not work as intended.

Characters:
Bob - level 1 with War Mode (1.3x XP gain)
Alice - level 1 with Slow & Steady (0.5x XP gain)
Boar - level 1 mob (normally gives 50 XP)

Scenario 1:
Alice stands nearby, Bob pulls and kills the boar.
Result: Each player gets 12 XP
Expectation: The base 50XP should be split in two, and then each player's modifiers should modify that value, which results in Alice getting 50 / 2 = 25 => 25 * 0.5 = 12XP, and Bob getting 50 / 2 = 25 => 25 * 1.3 = 32XP.

Scenario 2:
Bob stands nearby, Alice pulls and kills the boar.
Result: Each player gets 32 XP
Expectation: Result should match the result from scenario 1.

**Comment by cyaohiri** [comment]
There are further issues with dungeons, where the XP gain depends on whether the last person invited into the group has War Mode/Slow & Steady. This can change the amount of XP you gain by a factor of ~2.

**Comment by Massie323** [comment]
Update on this issue:
XP is now consistent and not dependtent on invite / gamemode composition - HOWEVER:
Slow & Steady players still suffer from 0.5x XP inside dungeons, when the penalty should be disabled during dungeons, according to the website.
