### ISSUE TITLE
DME tunnel VEINS BUGGED 

### ISSUE THREAD

**Issue by 5euroopjemuilgauw** [slowtorta/turtlewow-bug-tracker#2195]
50% of the runs either 1 or both of the rich thorium veins cant be mined 

![afbeelding](https://user-images.githubusercontent.com/114439314/192363280-ef93b6f0-e51d-4066-b76d-655ba54a30d5.png)
![buggef vein](https://user-images.githubusercontent.com/114439314/192363392-25644cca-911e-4628-820d-13fa90166bf0.PNG)
![bugged vein 2](https://user-images.githubusercontent.com/114439314/192363413-2d50e779-e5c2-4906-89c9-78e51e97ddde.PNG)

**Comment by geojak** [comment]
I never had that issue in my 20 dme runs

**Comment by 5euroopjemuilgauw** [comment]
lucky you ^^
at this point it aint even worth farming

**Comment by Vynora** [comment]
Did u kill the boss or just reset him?
Seems like there is some sort of "protection" and those could only be mined after killing the boss

**Comment by 5euroopjemuilgauw** [comment]
oh i had every possible outcome killing the boss, able to mine both, 1 or none at all, i had moment on wipe (undergeared) and same story its seems to be total random

**Comment by 5euroopjemuilgauw** [comment]
> Did u kill the boss or just reset him? Seems like there is some sort of "protection" and those could only be mined after killing the boss

i tested and 1 off the veins did became minable after killing him, so you where right about the protection

**Comment by Vynora** [comment]
Then its definitely the protection causing some issues

**Comment by geojak** [comment]
Did you skip some bosses?

When I killed water boss and satyr boss upstairs plus endboss, then it always worked for me

**Comment by 5euroopjemuilgauw** [comment]
its the protection of last boss

**Comment by Velite12** [comment]
You need to make sure you actually kill the final boss for the veins to work. It's unclear in the post if that was being done. This is an anti-gold farming protection that's in place on vmangos.
