### ISSUE TITLE
Login issue & Realm selection issue

### ISSUE THREAD

**Issue by AGUARON0815** [slowtorta/turtlewow-bug-tracker#2197]
**Hi, 
as always, I started wow, put in my password and clicked login. I just received the status "connecting" and then after several minutes "disconnected from server". 
I live in the Philippines (dont know if that is a new issue) Then I connected via VPN to Germany, logged in, it worked, but brought me to the Realm selection. I see my realm with the correct number of characters on it, after selecting this realm it brings me back again to the realm selection and this happens period. **

**Steps to reproduce the behavior with as much detail as possible: **

1. Start turtle-wow, enter pw, click login
2. Realm Selection shows up, select the only available realm
3. Realm Selection shows up, select the only available realm
4. Realm Selection shows up, select the only available realm
5. this happens period, so im not able to actually log into the realm and select one of my chars.

**It happens with my account: ########:**

NPC: https://database.turtle-wow.org/?npc=
Item: https://database.turtle-wow.org/?item=
Quest: https://database.turtle-wow.org/?quest=
Spell: https://database.turtle-wow.org/?spell=
Object: https://database.turtle-wow.org/?object=

**Expected behavior. Describe how it should work:**

Thank you in advance for your help.

Best
Aguaron

**Comment by Lexiebean** [comment]
The server is down right now for weekly maintenance.

Usually it's back up within a few mins, but it's been a little slower today for some reason.

**Comment by AGUARON0815** [comment]
thank you very much Lexiebean, I unfortunately must have missed that. 

Have a wonderful day ahead.
