### ISSUE TITLE
Ironbark the Redeemed yell typo

### ISSUE THREAD

**Issue by Velite12** [slowtorta/turtlewow-bug-tracker#220]
![image](https://user-images.githubusercontent.com/45871932/127773739-60b6cf08-3748-4d9a-8f3d-f93cc1ba00a8.png)

should say "cursed" instead of "curse"

https://database.turtle-wow.org/?npc=14241

**Comment by slowtorta** [comment]
Seems like a client issue. The line in the database is correct. 
![image](https://user-images.githubusercontent.com/66763404/127823566-ca3a7581-614f-414b-abf7-5b271771785c.png)
