### ISSUE TITLE
Title Carthographer does not work

### ISSUE THREAD

**Issue by geojak** [slowtorta/turtlewow-bug-tracker#2200]
**Please, provide a clear description what the bug is:**

1. explore everything on the map (that is everything that on the world map uncovers a map part)
2. use carthographer addon to make sure you didnt miss anything by highliting misses parts
3. still no title for weeks/months
4. know other ppl in the same situation
5. find out the only guy you know that has the title, had to ask a gm to manually get the title
6. make a ticket, because it seems not working

**Expected behavior. Describe how it should work:**

if you explored every map part you should auto get the tile without the need of help from a gm

**Comment by jameyboor** [comment]
This is fixed.
