### ISSUE TITLE
Dream's Herald Tooltip

### ISSUE THREAD

**Issue by usedcars4cheap** [slowtorta/turtlewow-bug-tracker#2202]
For the item Dream's Herald - https://database.turtle-wow.org/?item=65008
The effect claims 150 damage over 12 seconds and attack/mvmt speed reduction of 20% - https://database.turtle-wow.org/?spell=48004

This tooltip does not seem to reflect this:
![image](https://user-images.githubusercontent.com/68176649/192942380-078e9c1b-1846-4e90-b849-b46a35cac3b3.png)

**Comment by jlabranche** [comment]
I noticed that this was marked as resolved, and figured maybe it'll be resolved with the next update.
However that doesn't appear to be the case,
when I log in to the game and atk some monsters i still get this exact scenario.

This doesn't appear to be resolved

**Comment by ratkosrb** [comment]
Changes to spell tooltips require an update to Spell.dbc to be delivered in a new MPQ patch. The new client patch is not released yet, you have to wait. The issue being closed just means we have fixed it internally, not that it's live.
