### ISSUE TITLE
Net-o-matic debuff  everytime I login

### ISSUE THREAD

**Issue by yaboydarrell** [slowtorta/turtlewow-bug-tracker#2205]
**Please, provide a clear description what the bug is:**

**Steps to reproduce the behavior with as much detail as possible:**

1.  Login
2.  Get Net-o-matic debuff

**Expected behavior. Describe how it should work:**
 I found an old closed ticket but it's still happening.   Even if the net isn't equipped I get the debuff.   Not sure what is causing this bug but it is very annoying.  

https://imgur.com/a/dovTdcb

**Comment by yaboydarrell** [comment]
Well, it went away.   Not sure what caused it to happen, sorry.

**Comment by slowtorta** [comment]
I'm sorry, couldn't reproduce this bug 😕
