### ISSUE TITLE
UBRS repeating loot

### ISSUE THREAD

**Issue by FIRESLAYER69** [slowtorta/turtlewow-bug-tracker#2206]
**Please, provide a clear description what the bug is:**

**Steps to reproduce the behavior with as much detail as possible:**

1. ive run the instance several times to aquire a specific item with a decent drop rate
2. Ive seen items with lower drop rates   drop and never the item im after
3. im loosing my patience and am starting to not have fun anymore
4. ive explained this to the gm's and they sent me here
5. I dont have a screenshot as im old and challenged
6. 
7. 

**IDs of affected creatures, items, quests or spells with a link to the relevant page:**

NPC: https://database.turtle-wow.org/?npc=
Item: https://database.turtle-wow.org/?item=
Quest: https://database.turtle-wow.org/?quest=
Spell: https://database.turtle-wow.org/?spell=
Object: https://database.turtle-wow.org/?object=

**Expected behavior. Describe how it should work:**

**Comment by FIRESLAYER69** [comment]
Im after the shoulders of valor from UBRS, i havnt seen them yet and getting frustrated,  Vanilla was never this bad on loot drops.  Ive seen the same exact items drop several times in a row for my runs....HELP

**Comment by geojak** [comment]
You are just unlucky. No reason to make a bug ticket.

I am a paladin and got your valor shoulders becuase they kept dropping and nobody wants it

**Comment by FIRESLAYER69** [comment]
Wow, so right after I submitted a ticket,  I ran UBRS and my item dropped. Unlucky my assSent via the Samsung Galaxy S8, an AT&T 5G Evolution capable smartphone
-------- Original message --------From: geojak ***@***.***> Date: 9/30/22  12:24 AM  (GMT-08:00) To: slowtorta/turtlewow-bug-tracker ***@***.***> Cc: Fireslayer ***@***.***>, Author ***@***.***> Subject: Re: [slowtorta/turtlewow-bug-tracker] UBRS repeating loot (Issue #2206) 
You are just unlucky. No reason to make a bug ticket.
I am a paladin and got your valor shoulders becuase they kept dropping and nobody wants it

**Comment by geojak** [comment]
Close the ticket. Its not a bug

**Comment by FIRESLAYER69** [comment]
Thanks for listening Sent via the Samsung Galaxy S8, an AT&T 5G Evolution capable smartphone
-------- Original message --------From: Torta ***@***.***> Date: 9/30/22  3:18 PM  (GMT-08:00) To: slowtorta/turtlewow-bug-tracker ***@***.***> Cc: Fireslayer ***@***.***>, Author ***@***.***> Subject: Re: [slowtorta/turtlewow-bug-tracker] UBRS repeating loot (Issue #2206) 
Closed #2206 as completed.
