### ISSUE TITLE
Graphical glitch inside Ironforge

### ISSUE THREAD

**Issue by fbbraganca** [slowtorta/turtlewow-bug-tracker#2209]
Sometimes walking inside Ironforge produces graphical glitches. GPU is AMD Vega 8 (ryzen 5 3500u)

**Steps to reproduce the behavior with as much detail as possible:**

1. Walk into Ironforge through main gate
2. Go to left or right (more frequent in Mystic Ward)
3. Cool graphical distorcions

![asasa](https://user-images.githubusercontent.com/91222797/193334846-d3e99382-eff5-4e19-8fd3-2480791ed533.png)
![Sem título](https://user-images.githubusercontent.com/91222797/193334851-e237b941-7687-4300-9fe9-b41a2446a5fb.png)

**Comment by slowtorta** [comment]
This is a modern graphic card / old game compatibility issue. 

The same is described here: https://community.amd.com/t5/graphics/rx-580-graphical-flickering-and-stretched-textures-exclusive-to/td-p/400656

Try to play around with the game config using this guide: https://forum.nostalrius.org/viewtopic.php?t=1100
Try switching between the following graphic API as described here: https://www.mmo-champion.com/threads/687894-OpenGL-vs-DirectX

**Comment by ratkosrb** [comment]
You can also try using DXVK to replace the DirectX 9 renderer with Vulkan. This should solve any graphical glitches. Download it from [here](https://github.com/doitsujin/dxvk/releases/tag/v1.10.3) and place the 32 bit dll files in the game folder.

**Comment by fbbraganca** [comment]
Thanks for the quick answer and for the awesome work :)
