### ISSUE TITLE
[Paladin] Suppression aura in BWL should not affect target with Divine Shield level immunities

### ISSUE THREAD

**Issue by Velite12** [slowtorta/turtlewow-bug-tracker#221]
https://www.twitch.tv/videos/903956641

Currently, having divine shield will only remove the debuff but not prevent reapplication.

https://database.turtle-wow.org/?spell=22247

**Comment by itswicky** [comment]
The triggered spell, suppression, may have a flag which allows it to bypass immunity.

**Comment by Haaxor1689** [comment]
Intended behavior
