### ISSUE TITLE
Mind Soothe/Calm Elements/Soothe Animal Resist Pulls

### ISSUE THREAD

**Issue by Apimius** [slowtorta/turtlewow-bug-tracker#2211]
**Please, provide a clear description what the bug is:**

Mind soothe resists make you in combat with your target.

**Steps to reproduce the behavior with as much detail as possible:**

1. have a mind soothe resist
2. notice that the enemy gets in combat with you
3. be sad

**IDs of affected creatures, items, quests or spells with a link to the relevant page:**

Spell: https://database.turtle-wow.org/?spell=10953

**Expected behavior. Describe how it should work:**

Mind soothe resists should just have no effect but should not make you go in combat with your target.

**Comment by ratkosrb** [comment]
I believe that must be blizzlike, because the spell has the "Threat Only on Miss" attribute.

**Comment by Apimius** [comment]
its super annoying though, should get removed for that ability imo

**Comment by Apimius** [comment]
not fun that a 1 % miss (that cant be removed) chance can fck you over, same for sap

**Comment by Zebouski** [comment]
the 1% unremovable resist should indeed be removed, but that's a post for the twow suggestions forum, not a nonblizzlike bug to be reported, i'd suggest moving this topic there.

**Comment by slowtorta** [comment]
I personally agree with them, it makes not much sense right now @ratkosrb

**Comment by cyaohiri** [comment]
Same goes for [Soothe Animal](https://www.wowhead.com/classic/spell=2908).

**Comment by balakethelock** [comment]
I was told Calm Elements was not bundled in with mind soothe when this change was implemented

https://database.turtle-wow.org/?spell=45529

Allegedly, it still aggros the mob if it resist. I have no way to personally test and confirm if that's true

**Comment by balakethelock** [comment]
@twowTurtReynolds I have tested & can confirm resisted Calm Elements causes the mob to aggro. Requesting reopen and also requesting testing with Soothe Animal

**Comment by ratkosrb** [comment]
Calm Elements will have the attribute removed in the next update.
