### ISSUE TITLE
Marshal Windsor begin combat with horde players

### ISSUE THREAD

**Issue by Shellyoung** [slowtorta/turtlewow-bug-tracker#2213]
**Please, provide a clear description what the bug is:**
If a horde player come close to Marshal Windsor, then Windsor aggro at him and then follow. After this an alliance player is unable to begin or complete any quests offered by Windsor.

**Steps to reproduce the behavior with as much detail as possible:**

1. Become horde.
2. Get close to Marshal Windsor in his cell.

**IDs of affected creatures, items, quests or spells with a link to the relevant page:**

NPC: [Marshal Windsor](https://database.turtle-wow.org/?quest=4241)

**Expected behavior. Describe how it should work:**
He should not aggro at horde players.

**Comment by Tinyfin-github** [comment]
Hello

While dungeons can be done crossfaction, quests can't be completed crossfaction and  the opossite faction npc will be hostile to you.
