### ISSUE TITLE
Sparkwater Port herb nodes

### ISSUE THREAD

**Issue by MorlanOriginal** [slowtorta/turtlewow-bug-tracker#2214]
**Please, provide a clear description what the bug is:**
Herb nodes in Sparkwater Port that not exist, or in wall, or under textures, probably legacy artifacts from vanilla where no port on this place.

**Steps to reproduce the behavior with as much detail as possible:**

1. Come to Sparkwater Port in Durotar with [Find Herbs](https://database.turtle-wow.org/?spell=2383) active.

**Expected behavior. Describe how it should work:**
Remove or fix nods on territory that now Sparkwater Port.
![WoWScrnShot_100122_170749](https://user-images.githubusercontent.com/112715239/193415393-9a424b4b-e778-41ec-9274-7a6388fcf5a7.png)
![WoWScrnShot_100122_170809](https://user-images.githubusercontent.com/112715239/193415403-7212ee95-9126-47fa-9386-ab013144aa9e.png)

**Comment by geojak** [comment]
I reported these asweel. my ticket is also open, somewhere here.

**Comment by geojak** [comment]
https://github.com/slowtorta/turtlewow-bug-tracker/issues/20

**Comment by MorlanOriginal** [comment]
Oh, ye. My bad. Usually i check if there any topic with same problem before post. Didnt do this that time. But still, lets hope that double post have double chance for react from turtle-team :)
