### ISSUE TITLE
Whirldwind shredder mobs in Desolace

### ISSUE THREAD

**Issue by CillitbangEU** [slowtorta/turtlewow-bug-tracker#2218]
**Please, provide a clear description what the bug is:**

The whirldwind shredder mobs in desolace, is showing as being one place but is actually in another. I was just fighting, an dead flyer and 3 of them popped out of no where and ganked me like rogues. So ended up loosing my hunter to this death trap of a bug.

**Steps to reproduce the behavior with as much detail as possible:**

1. Mobs not being where their were
2. Mobs teleporting too player when attacking
3. Mobs apperantly traveling in groups of three, but shown being solo.

**IDs of affected creatures, items, quests or spells with a link to the relevant page:**

NPC: https://database.turtle-wow.org/?npc=11578

**Expected behavior. Describe how it should work:**

They shouldnt be teleporting or be stealth. They should be pathing and showing their pathing as normal, instead of just randomly teleporting to a player in groups of 3.

**Comment by cyaohiri** [comment]
Similar to #2218.
They're still behaving in a weird way.

**Comment by ratkosrb** [comment]
I can't reproduce the issue you're having, but I'll make these mobs sit idle out of combat, and perhaps that will fix the movement issues you're seeing.
