### ISSUE TITLE
Joining a bg while chilling AFK punishes with a deserter

### ISSUE THREAD

**Issue by Zebouski** [slowtorta/turtlewow-bug-tracker#2219]
**Please, provide a clear description what the bug is:**
when you join a bg while afk, you get instantly kicked with deserter. this happens to me cosnistently as I am afk, watching youtube or whatever until my long bg queue pops, and I hit accept queue without moving my toon because this problem didnt happen on classic and i forget about this bug here. it's obnoxious and contributes to this server's ghost queue problem

**Steps to reproduce the behavior with as much detail as possible:**

1. queue bg and get afk status
2. take bg pop
3. get teleported back with deserter

**Expected behavior. Describe how it should work:**
AFK status should be cleaned off the moment you press Accept on the bg pop, so that when you enter the BG, you don't get kicked.

**Comment by slowtorta** [comment]
We were unable to reproduce this issue, it's working as intended: the AFK flag is being revoked on entering the [battleground.]
[AntiAFK.zip](https://github.com/slowtorta/turtlewow-bug-tracker/files/9693586/AntiAFK.zip)
Please try to re-donwload your client from our website or use this AntiAFK hack (it won't allow you to AFK on the Battleground but will help to solve unexpected issues like the one you described).

**Comment by slowtorta** [comment]
Just a wild guess, but please check if your PC time is accurate.
