### ISSUE TITLE
Quest An Infinite Hunt is bugged

### ISSUE THREAD

**Issue by SierraNairn** [slowtorta/turtlewow-bug-tracker#222]
Quest An Infinite Hunt is bugged
https://database.turtle-wow.org/?quest=80411
After the event the quest is incompleted in quest log and can't be completed  at chromie.

![WoW_8wJTJsUwOo](https://user-images.githubusercontent.com/83077166/127836959-235b58e3-1356-4052-a108-8e680c599ace.png)

But the quest  id shows as completed.
![image](https://user-images.githubusercontent.com/83077166/127836925-089ba212-3eb2-497e-8d8e-1d98516451ee.png)

Can't be completed by  .quest complete. To complete the quest you have to remove with .quest remove, add it to quest log, and then complete it without doing the event  with .quest complete.

Note: During the event the  Antnormi was supossed to yell a line.

What he was supossed to say:
![ApplicationFrameHost_ERy3rnxfvr](https://user-images.githubusercontent.com/83077166/127838609-dca9edfe-9b37-4f52-9505-fcf025b73ec9.png)

He does not say it :
And one of Kheyna dialogue line is also missing
![image](https://user-images.githubusercontent.com/83077166/127837670-535cb7ca-d434-4f21-9e2b-7153de19915b.png)

**Comment by Neto-WoW** [comment]
Hi there. Thanks for the report. 

Fixes pushed to PTR. Should be good for live deployment.
