### ISSUE TITLE
Spell: Vanish/Stealth Aura

### ISSUE THREAD

**Issue by Sringaram** [slowtorta/turtlewow-bug-tracker#2220]
ID: https://database.turtle-wow.org/?spell=1857

It seems like the vast majority of bosses put you into combat again after you vanish so they'll beeline for you once everybody else is dead. This happens regardless of distance.
This does not seem to happen with hunter's Feign Death.

**Comment by Sringaram** [comment]
I guess it would be more accurate to say that the issue is with stealth aura instead.

Some examples of the fights where it happens regardless of distance: Ossirian, Nefarian.

**Comment by Sringaram** [comment]
I assume a simple fix would be to give stealth aura the FD treatment against monsters so that you're not flagged for combat merely by being in the zone.

**Comment by Sringaram** [comment]
This happens even with many trash packs, you're just instantly put into combat again despite being far away.

**Comment by jameyboor** [comment]
I cant reproduce this. Please upload a video or mention some specific cases you've seen this. I've tried it with multiple mobs and bosses.

**Comment by Sringaram** [comment]
Pretty much all raid fights feature this issue. Are you testing this alone? Try doing it with another character in the raid and engaged in the fight.
Try Ossirian or Nefarian for example.
