### ISSUE TITLE
The Lich, Ras Frostwhisper (quest)

### ISSUE THREAD

**Issue by jfarinhote** [slowtorta/turtlewow-bug-tracker#2223]
**Please, provide a clear description what the bug is:**
Using the item KeepSake it doesnt make Ras Frostwhisper human

**Steps to reproduce the behavior with as much detail as possible:**

1. In Scholomance at Ras Frostwhisper's room and using KeepSake item/book doesnt turn Ras Frostwhisper human after 2 attempts in a row. I fully channeled before he dies twice and he didnt turn to human.

**IDs of affected creatures, items, quests or spells with a link to the relevant page:**

NPC: https://database.turtle-wow.org/?npc=10508
Item: https://database.turtle-wow.org/?item=13752
Quest: https://database.turtle-wow.org/?quest=5466

**Expected behavior. Describe how it should work:**
Ras Frostwhisper should turn to human so we can kill him in human form to complete the quest

**Comment by geojak** [comment]
Used to work for me back in August

Maybe fixing this ticket a tually broke it 
https://github.com/slowtorta/turtlewow-bug-tracker/issues/1954

**Comment by ratkosrb** [comment]
I can't reproduce the issue.

**Comment by jfarinhote** [comment]
FYI
I was able to do the quest today, actually 3 of the party members had the quest and we all channeled and he turned to human. I am not sure if this had anything to.
