### ISSUE TITLE
Fix your fucking GMs

### ISSUE THREAD

**Issue by Shellyoung** [slowtorta/turtlewow-bug-tracker#2224]
And I know Tinyfin reads this. Can you please delete my Advanced Trade Skill Window addon page? Don't forget this, you fuckerface.

**Comment by ratkosrb** [comment]
Please insult the GMs using in game tickets. The bug tracker is for insulting developers only.

**Comment by Tinyfin-github** [comment]
Please send insults and after you are done sending insults your appeal  about the problem : help.turtlewow@gmail.com
In game tickets are for solving issues not insults.

**Comment by Shellyoung** [comment]
Unban my forum account. I will delete all my messages and say good bye to your crazy turtle family.
