### ISSUE TITLE
<A Donation of Wool> quest issue

### ISSUE THREAD

**Issue by akwonglv** [slowtorta/turtlewow-bug-tracker#2225]
**Please, provide a clear description what the bug is:**
A Donation of Wool quest was never accepted and not in quest log. But Clavicus Knavingham has a "?" mark above his head showing it can be turned in. The quest icon on the map is also not where it should be in the Mage Quarter - it is by the front gate of Stormwind (83.8/81.6). 

**Steps to reproduce the behavior with as much detail as possible:**
1. Entered Stormwind for the first time yesterday
2. Never having accepted the quest / not able to accept

**IDs of affected creatures, items, quests or spells with a link to the relevant page:**
NPC: https://database.turtle-wow.org/?npc=14722
Quest: https://database.turtle-wow.org/?quest=7791

**Expected behavior. Describe how it should work:**
Clavicus Knavingham should have the "!" mark above his head allowing me to accept the quest. The icon on the map should also be in the correct spot 
![image](https://user-images.githubusercontent.com/114947377/193647444-0000e4f9-dc85-4c4e-bc86-2150bb42c5b9.png)
![image](https://user-images.githubusercontent.com/114947377/193647538-39328b3e-2aca-45d0-a2f3-bcd61075b475.png)
![image](https://user-images.githubusercontent.com/114947377/193647858-6c5af464-7510-4293-b942-4cda77db9f42.png)

**Comment by mikefirefly** [comment]
Not only in SW, also in IF and Darnassus it looks the same. Nice that someone raised this at last.

**Comment by geojak** [comment]
Isn't this blizzlike for the cloth turn ins?

The map issue is addon issue. You just need to download pfquest-turtle

**Comment by akwonglv** [comment]
Both pfquest and pfquest-turtle freshly installed as of a week ago

**Comment by geojak** [comment]
Alright then ofquest has problem. But you should report than on pfquest github and not the TWoW one. They aren't related.

I still believe the? For cloth turn ins is blizzlike

**Comment by ratkosrb** [comment]
This is not a bug. You don't need to accept those quests, they can be turned in directly.
