### ISSUE TITLE
quest: miners union mutiny 2

### ISSUE THREAD

**Issue by geojak** [slowtorta/turtlewow-bug-tracker#2226]
**Please, provide a clear description what the bug is:**

the custom quest asks you to kill 20 miner in hatefroge quarry. the kill counter is bugged

**Steps to reproduce the behavior with as much detail as possible:**

1. go hatefroge with the qesut
2. kill miners
3. reach 20/20 killed miners
4. kill another miner
5. quest counter goes back to 1/20 killed miner
6. kill more miners
7. notice the counter is now permanetly stuck at 1/20

**IDs of affected creatures, items, quests or spells with a link to the relevant page:**

https://database.turtle-wow.org/?quest=40468

**Expected behavior. Describe how it should work:**

at 20/20 qeust should be finished and counter not buggily doing stuff?

**Comment by ratkosrb** [comment]
I can't reproduce the issue.

**Comment by redmagejoe** [comment]
This is an issue that's usually caused by a caching problem. Deleting WDB should address this.

**Comment by geojak** [comment]
Hmm I do delete my wdb like every other week. I handed in the qeust, so if rat can't repedocue I just close it
