### ISSUE TITLE
Quest Text Typo "Mystery of Lake Mennar" - Bloodfist Point, Azshara

### ISSUE THREAD

**Issue by dromen48** [slowtorta/turtlewow-bug-tracker#2227]
**Please, provide a clear description what the bug is:**

**Steps to reproduce the behavior with as much detail as possible:**

Part III of the Farseer question chain in Bloodfist Point, Azshara. It's from the tauren, Talom Stridecloud.
![image](https://user-images.githubusercontent.com/111084731/193690097-04412ba7-4dbc-41b0-bb36-4af963a2891e.png)

**IDs of affected creatures, items, quests or spells with a link to the relevant page:**

NPC: https://database.turtle-wow.org/?npc=
Item: https://database.turtle-wow.org/?item=
Quest: https://database.turtle-wow.org/?quest=
Spell: https://database.turtle-wow.org/?spell=
Object: https://database.turtle-wow.org/?object=

**Expected behavior. Describe how it should work:**

**Comment by cyaohiri** [comment]
It would save time if you quoted the part that has the typo.
It's after "on the other hand".

**Comment by dromen48** [comment]
How about they just read the screenshot and appreciate that I even took the time to make a ticket :)
