### ISSUE TITLE
Can't train Character 

### ISSUE THREAD

**Issue by XhenGuy** [slowtorta/turtlewow-bug-tracker#2229]
**Please, provide a clear description what the bug is:**
When I'm trying to train as a Night Elf Hunter the game crashes and has an error message of "Your game interface files are corrupt. Please remove your Interface\FrameXML folder.
**Steps to reproduce the behavior with as much detail as possible:**

1.Go to any Hunter Trainer
2. Click I'd like to train
3. Game crashes
4. Error pops up saying "Your game interface files are corrupt. Please remove your Interface\FrameXML folder.

**IDs of affected creatures, items, quests or spells with a link to the relevant page:**

NPC: https://database.turtle-wow.org/?npc=

**Expected behavior. Describe how it should work:**
You should be able to train your character but you can't train period.

**Comment by slowtorta** [comment]
Please try to donwload a fresh client from our website. This isn't a server-side issue.
