### ISSUE TITLE
Arch Druid Renferal & other NPC's camp horde graveyard in AV

### ISSUE THREAD

**Issue by yaboydarrell** [slowtorta/turtlewow-bug-tracker#2232]
**Please, provide a clear description what the bug is:**

https://imgur.com/a/9PUtHL8

**Steps to reproduce the behavior with as much detail as possible:**

Unsure how to reproduce but we got camped over & over by a group of elite NPC's in the wrong position.

**IDs of affected creatures, items, quests or spells with a link to the relevant page:**

NPC: https://database.turtle-wow.org/?npc=13442

**Expected behavior. Describe how it should work:**

Certainly they should never spawn or be leashed here.

**Comment by slowtorta** [comment]
@ratkosrb Perhaps, a lesser leash distance for https://database.turtle-wow.org/?npc=13442?

**Comment by ratkosrb** [comment]
@slowtorta The screenshot is not even from the current version AV, the terrain does not look like in the picture anymore. And the mobs don't appear to be in combat, they seem to be standing there while out of combat, so leach would not affect them. Leash range is checked only while in combat, and the distance check is to the position from which the creature entered combat. So if mob was sitting there and you aggroed it, leash would not make it go back to spawn position. I have added a hardcoded check to make the creature run to its home position if it goes near the graveyard instead, but the graveyard is not even at the position its in the screenshot as I previously mentioned.
