### ISSUE TITLE
Quest Honoring a Hero, Horde side (Harvest Festival) broken

### ISSUE THREAD

**Issue by FeyfolkenFantasy** [slowtorta/turtlewow-bug-tracker#2233]
**Please, provide a clear description what the bug is:**

The Quest "Honoring a Hero", which is part of the harvest festival is broken.
When you put the tribute at the base of Grom's monument in Demon fall Canyon (Ashenvale) the quest is not being updated as completed.
**It might be a custom race issue as I experienced that on my Goblin.**

**Steps to reproduce the behavior with as much detail as possible:**

1. Play a Goblin
2. Take the quest "Honoring a Hero" from Javnir Nashak in front of Orgimmar.
3. Go to Demon Fall Canyon and drop the tribute at the Grom's monument.

**IDs of affected creatures, items, quests or spells with a link to the relevant page:**

NPC: https://database.turtle-wow.org/?npc=15012
Item: https://database.turtle-wow.org/?item=19851
Quest: https://database.turtle-wow.org/?quest=8150

**Expected behavior. Describe how it should work:**

As soon as you drop the tribute at the base of the monument in Demon Fall Canyon, the quest shall be marked as completed.

**Comment by geojak** [comment]
hello i have the exact same issue as alliance for the uther tomb. quest is not getting completed when you use the item

**Comment by usedcars4cheap** [comment]
Maybe a custom races issue, my sample size is High Elf = no credit, Night Elf = works properly

**Comment by slowtorta** [comment]
Closing as dupliacte.
