### ISSUE TITLE
Defective Inn in Northern Barrens

### ISSUE THREAD

**Issue by MorlanOriginal** [slowtorta/turtlewow-bug-tracker#2238]
**Please, provide a clear description what the bug is:**
In Northern Barrens slight southern from Warsong Gulch enter custom Inn not consider as rested place.

**Steps to reproduce the behavior with as much detail as possible:**

1. Come to Barrens.
2. Come to defective inn.

**Expected behavior. Describe how it should work:**
Inn should become a rested place.
![WoWScrnShot_100422_212910](https://user-images.githubusercontent.com/112715239/194142753-ee0a19a3-6206-4238-a685-93198b429c45.png)
![WoWScrnShot_100422_212926](https://user-images.githubusercontent.com/112715239/194142762-5122b0b9-945b-4ebc-8fa9-1b479e78b088.png)

**Comment by slowtorta** [comment]
This is a guild base, as far as I remember, an abandoned one. This innkeeper isn't even supposed to be here. We'll look into it :)
