### ISSUE TITLE
[Shaman][Not really a bug but this was fixed on classic] Improved Weapon Totems talent does not apply to other party members.

### ISSUE THREAD

**Issue by Velite12** [slowtorta/turtlewow-bug-tracker#224]
Source: https://classic.wowhead.com/news/blizzard-plans-to-fix-improved-weapon-totems-bug-party-should-benefit-from-318160

![image](https://user-images.githubusercontent.com/45871932/128051364-68148b32-acbb-4928-a887-bf4e5741ca9c.png)

Turtle:

![image](https://user-images.githubusercontent.com/45871932/128051414-8c3e8345-492c-43f3-8167-c68aef50d2bf.png)

Flametongue Totem on another party member with and without the talent:

![image](https://user-images.githubusercontent.com/45871932/128051791-d9dade5f-3fa0-4f7d-a4d7-047b589ce2b4.png)
![image](https://user-images.githubusercontent.com/45871932/128051810-dd275e47-4324-4169-aa4b-2444c2e58fb9.png)

![image](https://user-images.githubusercontent.com/45871932/128051864-d5b435b7-9230-4acc-af5f-80a0dfe346ff.png)

This talent does not apply the benefit to other party members.  It's not really a bug as it is intended behavior in 1.12, but it was not caught until Classic and then it was patched by Blizzard. 

In its current state this talent is useless to spec into since shamans do not actually use the buffs from their own totems, but this is not advertised to the user.

This is in the same category as World buffs not giving ranged ap to hunters, That was an authentic vanilla 2006 bug but was patched on this server and on classic to give the buffs ranged ap (referencing https://github.com/slowtorta/turtlewow-bug-tracker/issues/225):

https://classic.wowhead.com/news/hunter-buffs-auras-and-buffs-will-properly-apply-to-ranged-attack-power-in-wow-318385

**Comment by Apimius** [comment]
please make the profit for the whole group-

**Comment by Zeyla-TW** [comment]
This should be fixable by adjusting the effects of spells 29192 and 29193 by changing spell effect 1's Target A from "1 - Target_Unit_Caster" with radius 0 to "20 - Target_Unit_Caster_Area_Party" with a radius of about 100, since the application of the aura will do nothing if they do not also receive the weapon enhancement from the totem itself.

**Comment by Zeyla-TW** [comment]
I just tested it on my personal test server, and simply changing both spell effects 1 & 2 from 6 to 35 causes party members to benefit.
