### ISSUE TITLE
(Druid) Omen of Clarity not working correctly when Maul is queued

### ISSUE THREAD

**Issue by dan-personal** [slowtorta/turtlewow-bug-tracker#2240]
**Please, provide a clear description what the bug is:**
As a druid in bear form, when you have a Clearcasting proc from Omen of Clarity and a Maul queued, casting another rage ability (e.g Swipe, Savage Bite) will consume the Clearcasting proc but will not discount the ability. You might think that it's just some weird lag or spell queuing issue and it will discount the Maul rather than the other ability, but no, it discounts neither.

**Steps to reproduce the behavior with as much detail as possible:**

1. Be a Druid in bear form, with access to Maul and another rage-costing ability, and talented in to Omen of Clarity.
2. Auto attack until you have a Clearcasting proc
3. Wait for a further auto attack to allow yourself plenty of time to set up and observe the bug
4. Queue a Maul
5. Before the Maul goes off, cast a rage-costing ability
6. Observe that you have lost Clearcasting, but your rage has been reduced by the cost of the ability (talent dependent)
7. Wait for the Maul to go off
8. Observe that the Maul has also not been discounted. Note: I wouldn't expect the Maul to be discounted, but this refutes the possible argument that some sort of lag is causing the Clearcasting proc to be consumed on Maul rather than the first ability you cast.

Note: I only personally tested these steps with Swipe and Savage Bite. I have made the assumption that other rage costing abilities are affected similarly - Demoralizing Roar, Challenging Roar

**IDs of affected creatures, items, quests or spells with a link to the relevant page:**

Spell: https://database.turtle-wow.org/?spell=9881
Spell: https://database.turtle-wow.org/?spell=16864

**Expected behavior. Describe how it should work:**
The rage-costing ability should be free when it is cast with a Clearcasting proc.

**Comment by Proworx** [comment]
Any ETA on the resolve of this issue? Has been around for a while.

**Comment by SaxxonPike** [comment]
This isn't the same issue as #1960 (that might be a spell db correction) but I'm going to share the necessary spell to look at from that issue:

Spell ID for Clearcasting (Druid): 16870
https://database.turtle-wow.org/?spell=16870
https://www.wowhead.com/classic/spell=16870/clearcasting

**Comment by jameyboor** [comment]
Maul is properly discounted. Closing.

**Comment by dan-personal** [comment]
Not fixed. Clearcasting proc is consumed by the rage costing ability (e.g swipe) but not discounted. Maul is then discounted. Slightly better, but still broken.

Not only does it make no real sense for maul to be discounted in this case, but it's also not even the ability consuming the clearcasting proc. The ability that consumes the clearcasting proc is the ability that should be discounted. If that is a maul, then maul is discounted. In this case it is NOT maul that consumes the clearcasting proc (nor should it be). Any other behaviour is silly.

Bug should be reopened!
