### ISSUE TITLE
Gold plated royal crossbow

### ISSUE THREAD

**Issue by marcinb12500** [slowtorta/turtlewow-bug-tracker#2242]
**The crossbow is held on the left instead of the right. It has a bugged animation when firing, and is kinda floating (uses gun animation). It cannot be transmogged (to either gun or crossbow)**

**Steps to reproduce the behavior with as much detail as possible:**

1. Equip crossbow
2. fire
3. try to transmog

**IDs of affected creatures, items, quests or spells with a link to the relevant page:**

NPC: https://database.turtle-wow.org/?npc=
Item: https://database.turtle-wow.org/?item=60624         
Quest: https://database.turtle-wow.org/?quest=
Spell: https://database.turtle-wow.org/?spell=
Object: https://database.turtle-wow.org/?object=

**Expected behavior. Describe how it should work:**

Like any other vanilla crossbow (held in right hand) propper clipping animations and not floating (and transmogable

**Comment by geojak** [comment]
It also does not benefit from the attackspeed bonus of the quiver, ins was uses ammunition bag
