### ISSUE TITLE
Can't get reputation with Darnassus via Runecloth quest

### ISSUE THREAD

**Issue by afamyau** [slowtorta/turtlewow-bug-tracker#2244]
1. I turn in quest "Additional Runecloth: Darnassus"
2. I don't get reputation
3. Reputation with Darnassus doesn't change

Quest: https://database.turtle-wow.org/?quest=7801
NPC: https://database.turtle-wow.org/?npc=14725
Item: https://database.turtle-wow.org/?item=14047

It should give reputation with Darnassus, and it worked few days ago.

https://user-images.githubusercontent.com/40724458/194597035-b90dd2b2-d107-44aa-bb34-29c1d7aeeaab.mp4

**Comment by slowtorta** [comment]
It's working as intended. Please disable your interface addon, clear your WDB cache and try again.
