### ISSUE TITLE
Shaman's searing totem(rank 1) constant damage

### ISSUE THREAD

**Issue by darkhorror1984** [slowtorta/turtlewow-bug-tracker#2247]
Shaman's Searing Totem (rank 1) always damaged to 10, but tooltip say about from 9 to 11 damage

1. Summon Searing totem (rank 1)
2. See his damage

NPC: https://database.turtle-wow.org/?npc=2523

Searing Totem (rank 1) damage from 9 to 11.

**Comment by Velite12** [comment]
Possibly a rounding error when it comes to damage? 

https://database.turtle-wow.org/?spell=22048

The spell is listed with a value of 10, there may not be variance?
