### ISSUE TITLE
Rallying cry of the Dragonslayer still doesn't give RAP

### ISSUE THREAD

**Issue by Velite12** [slowtorta/turtlewow-bug-tracker#225]
Spell with issue: https://database.turtle-wow.org/?spell=22888

A while back, the issue caught in classic that certain buffs that gave attack power only gave Melee attack power was fixed on this server too, however, Rallying cry of the Dragonslayer currently does not give RAP for hunters, even though the following were fixed to give RAP:

https://database.turtle-wow.org/?spell=22817
https://database.turtle-wow.org/?spell=28826
https://database.turtle-wow.org/?spell=28791
https://database.turtle-wow.org/?spell=16329

**Comment by jameyboor** [comment]
Greetings,

Do you have a source for your claims? More specifically, we are not sure that the current behavior of the auras are non-blizzlike as it specifically does not claim to give ranged attack power.

**Comment by Velite12** [comment]
It states attack power.

https://classic.wowhead.com/spell=22888/rallying-cry-of-the-dragonslayer

In classic blizzard corrected the oversight and gave it ranged attack power as well.

https://classic.wowhead.com/news/hunter-buffs-auras-and-buffs-will-properly-apply-to-ranged-attack-power-in-wow-318385#news-post-318385

**Comment by jameyboor** [comment]
We like to stay as close as vanilla as possible and would generally pick vanilla over classic behavior. However some things pop up that are discussed on a per-case basis to stray away from this implementation. One of such cases is your case here. We will look into the bug and add RAP to these buffs accordingly shortly.

**Comment by jameyboor** [comment]
Added next update.
