### ISSUE TITLE
(Paladin) Judgement bug

### ISSUE THREAD

**Issue by blade7606** [slowtorta/turtlewow-bug-tracker#2252]
Occasionally when a paladin player uses judgement (any seal) it activates and goes on cooldown and uses mana to cast the spell, however, the spell does not actually go off.

**Steps to reproduce the behavior with as much detail as possible:**

1. Cast judgement in combat quite often.
2.  It feels to be around a 5% failure rate but may be more (1 in 20 chance)
3. 

**IDs of affected creatures, items, quests or spells with a link to the relevant page:**

Spell: https://database.turtle-wow.org/?spell=20271

**Expected behavior. Describe how it should work:**
Like every other spell in the game, if you cast judgement it should work and be casted properly.

**Comment by geojak** [comment]
Thus is a duplicate. Velite repaired it sometime ago

**Comment by cyaohiri** [comment]
Duplicate of #1953.
