### ISSUE TITLE
(Paladin) Judgement of Crusader / Crusader Strike does not increase the holy damage from Seal of Command

### ISSUE THREAD

**Issue by blade7606** [slowtorta/turtlewow-bug-tracker#2253]
**Please, provide a clear description what the bug is:**
Judgement of the crusader / Crusader Strike does not increase the holy damage from Seal of Command. Seal of command damage does not increase even after judgement of crusader and crusader strike x5 debuffs are applied to the target. There should be a fairly noticeable difference. Seal of command is a proc for 70% of your weapon damage as holy and it's damage should be increased if either or both debuffs are present. 

**Steps to reproduce the behavior with as much detail as possible:**

1. View seal of command proc damage before debuffing target with judgement of crusader / crusader strike x5
2. View seal of command proc damage remain the same after debuff target with aforementioned spells.

**IDs of affected creatures, items, quests or spells with a link to the relevant page:**

Spell: https://database.turtle-wow.org/?spell=20309

**Expected behavior. Describe how it should work:**
After Judging seal of crusader and / or debuffing crusader strike x5 on a target Seal of Command should benefit from the increased holy damage debuffs.

**Comment by Apimius** [comment]
It works for priests holy spells. Both Crusader Judgement and Crusader Strike.

**Comment by blade7606** [comment]
> It works for priests holy spells. Both Crusader Judgement and Crusader Strike.

Yes, the issue is with seal of command...

**Comment by Apimius** [comment]
> > It works for priests holy spells. Both Crusader Judgement and Crusader Strike.
> 
> Yes, the issue is with seal of command...

I know, i just wrote this so programmers see that there is no issue with holy spells of other classes.

**Comment by redmagejoe** [comment]
Cannot reproduce on current version. Each stack of Crusader Strike Rank 5 increases damage of Seal of Command Rank 1 by the expected amount.

Fixed.
