### ISSUE TITLE
Revantusk Village inn is not a resting area

### ISSUE THREAD

**Issue by SnorreP** [slowtorta/turtlewow-bug-tracker#2256]
### **Please, provide a clear description what the bug is:**
Staying in the inn in Revantusk Village in The Hinterlands does not provide instant logouts and additional rested exp.

### **Steps to reproduce the behavior with as much detail as possible:**

1. Log out while in the inn in Revantusk Village to see that it is not instant
2. Look at your character portrait to see that you are not within a resting area while in the inn

### **Expected behavior. Describe how it should work:**
Being an inn, I expect instant logout and increased rested exp gain from logging out there.

**Comment by slowtorta** [comment]
This is expected behavior. Please go up to the second floor, the resting bonus will kick in the area with the bed. This Inn worked the same in Vanilla and Classic.
