### ISSUE TITLE
Seasoned Wolf Kabobs quest unable to be turned in

### ISSUE THREAD

**Issue by Tenyar97** [slowtorta/turtlewow-bug-tracker#2259]
**Please, provide a clear description what the bug is:**
Unable to turn in the quest [Seasoned Wolf Kabobs](https://database.turtle-wow.org/?quest=90).  All of the materials have been gathered, but I am unable to complete the quest.

**Steps to reproduce the behavior with as much detail as possible:**

1. Accept the quest: [Seasoned Wolf Kabobs](https://database.turtle-wow.org/?quest=90)
2. Gather the needed materials
3. Try to turn it it.

**IDs of affected creatures, items, quests or spells with a link to the relevant page:**

NPC: [Chef Grual](https://database.turtle-wow.org/?npc=272)
Quest: [Seasoned Wolf Kabobs](https://database.turtle-wow.org/?quest=90)

**Expected behavior. Describe how it should work:**
Able to turn the quest in, and receive credit for doing so.  
![e465b8a7fa869c16a6b2c7867f9d498c](https://user-images.githubusercontent.com/3698491/195003807-b8047266-d523-4934-8ccf-328525a372ca.jpg)

**Comment by cyaohiri** [comment]
It's not a permanent solution, but try abandoning and accepting the quest. It should fix it.
