### ISSUE TITLE
3x marks of warsong gluch lost

### ISSUE THREAD

**Issue by moradxdev** [slowtorta/turtlewow-bug-tracker#2260]
**Please, provide a clear description what the bug is:**
I entered warsong gulsh match. In the game I capped the flag and the match ended because there was no enough players. Normaly I receive 3 marks  but this time didnot receive anything.

**Steps to reproduce the behavior with as much detail as possible:**

1. posible lag at the end of the match.
2. 
3. 

**IDs of affected creatures, items, quests or spells with a link to the relevant page:**

NPC: https://database.turtle-wow.org/?npc=
Item: https://database.turtle-wow.org/?item=
Quest: https://database.turtle-wow.org/?quest=
Spell: https://database.turtle-wow.org/?spell=
Object: https://database.turtle-wow.org/?object=

**Expected behavior. Describe how it should work:**
receive 3 x marks of warsong glutch.

**Comment by slowtorta** [comment]
Please submit a ticket in-game, it's not a general bug :)
