### ISSUE TITLE
Omen of Clarity proc rate, still

### ISSUE THREAD

**Issue by burner1024** [slowtorta/turtlewow-bug-tracker#2264]
**Please, provide a clear description what the bug is:**
Omen still procing too rarely.
Ref #1963, #2115.

I increased sample sizes and recorded 2 full 30 min sessions (cat):
![Captura de pantalla de 2022-09-28 20-13-33](https://user-images.githubusercontent.com/1279852/192805074-0039bc0d-15cc-41bf-821c-1b30f2e8929d.png) ![Captura de pantalla de 2022-09-28 21-22-13](https://user-images.githubusercontent.com/1279852/192805081-cae1e207-2b57-4e93-b7f9-5628ab2a6223.png)

Assuming proc chance of 3.33% for cat attack, my estimation is that first screenshot has only 4% chance of happening, and second one is about 15%, which together makes 0.6% - pretty solid number suggesting that something's off.
But you don't have to take my word for it - just test for yourself.

**Steps to reproduce the behavior with as much detail as possible:**
1. Cast Omen.
2. Shift to cat, start attacking training dummy.
3. Count procs.

**IDs of affected creatures, items, quests or spells with a link to the relevant page:**
https://database.turtle-wow.org/?spell=16864

**Expected behavior. Describe how it should work:**
- 3.33% chance for auto and instant attacks in cat form
- 8.33% for auto and instant attacks in bear form.

**Comment by Platinumcoated** [comment]
I tried to reproduce the test and found out that I can't get Combat Log to show Aura refreshes, which means that every time I gain Clearcasting when I already had it, ProcWatch doesn't register it, even if it came from the ability using Clearcasting.
I don't suppose your combat log is any different ?

**Comment by burner1024** [comment]
I will re-check and report.

**Comment by burner1024** [comment]
You're right, refreshes do not get logged.
I performed a new, adusted test:
![Captura de pantalla de 2022-10-19 19-38-05](https://user-images.githubusercontent.com/1279852/196693269-3c0a5a34-256b-4683-b21a-7d5074ae640b.png)
Apparently PPM is 4 now.
I apologize for misleading results provided previously.

**Comment by cyaohiri** [comment]
You could've called CancelPlayerBuff() function whenever you gain any buff, or once per game update, but your method is still accurate enough to give statistically significant results.
