### ISSUE TITLE
Game crash when inspecting someone with a dalaran human female skin.

### ISSUE THREAD

**Issue by WenzelOfMidgard** [slowtorta/turtlewow-bug-tracker#2265]
**Please, provide a clear description what the bug is:** Game crash when inspecting someone with a dalaran human female skin.

**Steps to reproduce the behavior with as much detail as possible:**

1.
2. 
3. 

**IDs of affected creatures, items, quests or spells with a link to the relevant page:**

NPC: https://database.turtle-wow.org/?npc=
Item: https://database.turtle-wow.org/?item=
Quest: https://database.turtle-wow.org/?quest=
Spell: https://database.turtle-wow.org/?spell=
Object: https://database.turtle-wow.org/?object=

**Expected behavior. Describe how it should work:**

**Comment by Sringaram** [comment]
This is a general issue with transmogs. You gotta clear your WDB cache to be able to inspect those players.
