### ISSUE TITLE
NPC: Blisterpaw Hyena

### ISSUE THREAD

**Issue by cyaohiri** [slowtorta/turtlewow-bug-tracker#2266]
Blisterpaw Hyenas have a chance of dropping ~lv10 equippable items, which is not right.

NPC: https://database.turtle-wow.org/?npc=5426

**Comment by slowtorta** [comment]
Issues closed without any comments will be fixed on the next server update, just to clarify :)

**Comment by cyaohiri** [comment]
Thanks for clarifying!
