### ISSUE TITLE
NPC: Gnarlpine Warrior

### ISSUE THREAD

**Issue by cyaohiri** [slowtorta/turtlewow-bug-tracker#2275]
[Gnarlpine Warrior](https://database.turtle-wow.org/?npc=2008)'s Strike doesn't trigger [Thorns](https://database.turtle-wow.org/?spell=467). It seems likely that the Strike ability doesn't trigger any other on-hit effects, perhaps including any other mobs using this ability (the list is long).

NPC: https://database.turtle-wow.org/?npc=2008

**Comment by slowtorta** [comment]
For reports like this, we'd need a video-evidence of the same behavior on Classic, please!

**Comment by cyaohiri** [comment]
Video: https://www.youtube.com/watch?v=PsqJryrR3eU

Timestamps: 59:37/1:00:14/1:03:30
The warrior hits the character for 17/17/21 damage. Their base damage is 7-10, and it wasn't a critical hit, so it seems very likely that's their strike Strike ability. Another piece of evidence is the visual effect on the character getting hit by it, which is different from the effect of getting hit by a regular attack.

In all three cases, you can see Thorns causing 3 damage to the warrior after the character gets hit by Strike.

As I mentioned in my original post, this could be a more general issue, applying to many more mob abilities that should trigger on-hit effects.

**Comment by slowtorta** [comment]
Thank you!

**Comment by Muigin** [comment]
Confirmed that this is still not working as intended.
