### ISSUE TITLE
Spell: Blessing of Blackfathom

### ISSUE THREAD

**Issue by cyaohiri** [slowtorta/turtlewow-bug-tracker#2279]
The tooltip for [Blessing of Blackfathom](https://database.turtle-wow.org/?spell=8733) spells "Intellect", "Spirit" and "Frost damage" in all lowercase. This got fixed in The Burning Crusade.

Spell: https://database.turtle-wow.org/?spell=8733

**Comment by slowtorta** [comment]
Fixed on the next client update.
