### ISSUE TITLE
NPC: Bloodfen Screecher

### ISSUE THREAD

**Issue by cyaohiri** [slowtorta/turtlewow-bug-tracker#2283]
[Bloodfen Screechers](https://database.turtle-wow.org/?npc=4352) sometimes disappear just after being skinned, but before the skinning loot window appears. It's still possible to increase your Skinning skill this way.

NPC: https://database.turtle-wow.org/?npc=4352

This could be a more general issue.

**Comment by slowtorta** [comment]
Couldn't reproduce.
