### ISSUE TITLE
NPC: Drywallow Crocolisk

### ISSUE THREAD

**Issue by cyaohiri** [slowtorta/turtlewow-bug-tracker#2284]
[Drywallow Crocolisks](https://database.turtle-wow.org/?npc=4341) sometimes disappear just after being skinned, but before the skinning loot window appears. It's still possible to increase your Skinning skill this way.

NPC: https://database.turtle-wow.org/?npc=4341

This could be a more general issue.

**Comment by slowtorta** [comment]
Couldn't reproduce.
