### ISSUE TITLE
Quest CLUCK!

### ISSUE THREAD

**Issue by Ragnarockin** [slowtorta/turtlewow-bug-tracker#2287]
The second half of CLUCK! is broken.

targeting the chicken using the /chicken command eventually turns chicken friendly, allowing player to accept quest. 
Upon accepting quest chicken immediately becomes neutral and no amount of /chicken on the same NPC, or any other NPC chicken, will allow you to turn in quest for the pet.

Quest: https://database.turtle-wow.org/?quest=3861

**Comment by Gurky-Kronos** [comment]
Not a bug read the quest text...
"When you find it, /cheer at it before trying to give it the Special Chicken Feed."
