### ISSUE TITLE
Delay for unshapeshift as a druid

### ISSUE THREAD

**Issue by RalphThomas** [slowtorta/turtlewow-bug-tracker#2288]
**Please, provide a clear description what the bug is:**
There is a delay in unshapeshifting that is not vanilla-like. in vanilla, when you pressed rejuvenation, you would simply get out of bear (or another) form. press again and rejuv would be cast. BUT you could use the macro 
/cancelaura Bear Form
/cast Rejuvenation
to make it in 1 click. on Turtle, this macro gives out the warning i am in bear form (even though physically i am instantly a cow, and this action takes no gcd). smashing this macro does end with a rejuv cast, but it takes a good second to get there. its abnormal, and should not be there as a delay.

**Steps to reproduce the behavior with as much detail as possible:**

1.make macro
2. get in bear form
3. cast macro several times quickly

**Expected behavior. Describe how it should work:**
no delay, can cast anything immediately as soon as out of form.

**Comment by cyaohiri** [comment]
According to [this comment](https://www.reddit.com/r/Nostalrius/comments/3x3j37/comment/cy1lus1/) posted back in 2015, cancelling a form does in fact trigger GCD.

**Comment by usedcars4cheap** [comment]
This is correct behavior, druids cannot cast immediately out of shapeshift until one of the later expansions (Warlords of Draenor, iirc)

**Comment by RalphThomas** [comment]
one of the later expansions being TBC though. that i can assure you. i dabbled a bit in vanilla as a kid, but TBC i played serious balls deep. gladiator restokin n all. the macros needed were endless but the delays were non existant. after that, in wotlk, it was automatic. casting rejuv put u in casterform and cast rejuv in single click, no macro needed or anything. in wod, we had casting a bear form ability would put the druid in bear form auto. that was the last change to those mechanics, and eliminated a shitton of macros once again. anyhow. here it does not trigger a gcd on the client, but still has delay

**Comment by Francesq** [comment]
Are you sure this is unmorph which triggers gcd and not only morph ?

**Comment by usedcars4cheap** [comment]
Unmorph doesn't trigger a GCD, but requires the server side to acknowledge that you've shifted out of a form. I played treeform to gladiator during original TBC -- the macro written as described wouldn't work until Arena Season 3, and could not be accomplished without a macro until much later.

From a practical standpoint, it's probably difficult to re-write the architecture to let the client determine druidform.
