### ISSUE TITLE
Ironforge reputation cloth turn in bugged

### ISSUE THREAD

**Issue by SierraNairn** [slowtorta/turtlewow-bug-tracker#229]
Ironforge reputation cloth turn is bugged
Mistina Steelshield does not give a Donation of  Silk after completing a Donation of Wool
https://database.turtle-wow.org/?npc=14723 -Mistina Steelshield <Alliance Cloth Quartermaster>
https://database.turtle-wow.org/?quest=7803 - A Donation of Silk
https://database.turtle-wow.org/?quest=7802 - A Donation of Wool

Note: In the database A Donation of Wool from Mistina  is connected to A Donation of Silk  from Bubulo Acerbus  the Gnomeregan Exiles  cloth turn in npc.
https://database.turtle-wow.org/?npc=14724 Bubulo Acerbus

**Comment by slowtorta** [comment]
Thanks for reporting it. It'll be fixed on the next server restart. Make sure to clear your WDB folder.
