### ISSUE TITLE
Suntail Pass bug - Bristleback Boar charges straight into the cave and not directly at me.

### ISSUE THREAD

**Issue by Frostwolf103** [slowtorta/turtlewow-bug-tracker#2290]
**Please, provide a clear description what the bug is: Pathfinding Bristleback Boar **

**Steps to reproduce the behavior with as much detail as possible:**

1. Attack Bristleback Boar at Suntail Pass by the bridge
2. Bristleback Boar uses Charge however it goes straight into the cave and pull every mob inside the cave
3. Returns back to fight with second Charge ability now used correctly, however I died later to the pulled mobs that netted me.

**IDs of affected creatures, items, quests or spells with a link to the relevant page:**

NPC: https://database.turtle-wow.org/?npc=60848 / https://database.turtle-wow.org/?npc=60849 / https://database.turtle-wow.org/?npc=60847
Item: https://database.turtle-wow.org/?item=60654
Quest: https://database.turtle-wow.org/?quest=40446 / https://database.turtle-wow.org/?quest=40447
Spell: https://database.turtle-wow.org/?spell=
Object: https://database.turtle-wow.org/?object=

**Expected behavior. Describe how it should work: So when I attacked the Bristleback Boar or at least approached it, the boar uses Charge ability but has trouble finding me and goes straight into the cave instead pulling every mob inside before returning back to me which I killed without an issue until I see the pulled mob that blocked my escape and I died, I think that bristleback boar charge ability was unsuccessful unable to find my exact location even though I stand 10 feet across from them without any obstruction.**

**Comment by Frostwolf103** [comment]
![image](https://user-images.githubusercontent.com/115891646/196037302-c02b7c07-953d-423f-b569-162c7515d95f.png)

**Comment by slowtorta** [comment]
VMAPs issue, known, unrelated to the boars.
