### ISSUE TITLE
Quest "The Old Bonds"

### ISSUE THREAD

**Issue by Bloodline1x9** [slowtorta/turtlewow-bug-tracker#2291]
**Please, provide a clear description what the bug is:**
After accepting the quest from NPC, its description in the questlog book changed to the another quest description - "The Old Ways" quest https://database.turtle-wow.org/?quest=2756
From "Bonds" to "Ways". And questhelper thought that I needed to go to Ogrimmar (despite the fact that I am an Alliance)
And when I came to Slip, he despite this accepted successful completion "The Old Bond" quest.
So it's not a big problem. Just want you to know
**Steps to reproduce the behavior with as much detail as possible:**
1. 
2. 
3. 
[https://i.postimg.cc/XqhJgHqs/the-old-bonds.png](url)
**IDs of affected creatures, items, quests or spells with a link to the relevant page:**

NPC: https://database.turtle-wow.org/?npc=60504
Item: https://database.turtle-wow.org/?item=
Quest: https://database.turtle-wow.org/?quest=40225
Spell: https://database.turtle-wow.org/?spell=
Object: https://database.turtle-wow.org/?object=

**Expected behavior. Describe how it should work:**

**Comment by slowtorta** [comment]
I'm sorry, I was not able to reproduce this bug. Possibly, you're using some interface modifications?
