### ISSUE TITLE
Holy Resistance On NPCs

### ISSUE THREAD

**Issue by Apimius** [slowtorta/turtlewow-bug-tracker#2293]
NPCs seem to have holy resistance on turtle wow. I am aware of the 2 messures to determine a resist in vanilla which are based on spellhit and magic school resistance of the enemy. I got 16 spellhit with my priest and so a resist on my holy spells should be only 1 %. But I am getting quite frequent resists still. This suggests that there is actually holy resistance in turtle wow which should not be the case.

Nostalrius thread about the same issue: https://forum.nostalrius.org/viewtopic.php?f=5&t=36395

**Steps to reproduce the behavior with as much detail as possible:**

1. get 16% spellhit as a priest
2. spam smite rank2 on a lvl 63 dummy
3. notice quite alot of spell resists

There should be no resistance on NPCs and players for the holy magic school.

**Comment by cyaohiri** [comment]
You can see your target's resistances using this macro: `/run u=UnitResistance y="target" h=u(y ,1) f=u(y ,2) n=u(y ,3) fr=u(y ,4) s=u(y ,5) z=u(y ,6) DEFAULT_CHAT_FRAME:AddMessage(UnitName(y).." has "..h.." Holy, "..f.." Fire, "..n.." Nature, "..z.." Arcane, "..fr.." Frost and "..s.." Shadow res.")`

**Comment by Apimius** [comment]
> /run u=UnitResistance y="target" h=u(y ,1) f=u(y ,2) n=u(y ,3) fr=u(y ,4) s=u(y ,5) z=u(y ,6) DEFAULT_CHAT_FRAME:AddMessage(UnitName(y).." has "..h.." Holy, "..f.." Fire, "..n.." Nature, "..z.." Arcane, "..fr.." Frost and "..s.." Shadow res.")

Apparently that boss dummy has no resistances, but im still getting like 3-4 partial resists in a row (happened quite a few times now) so this can not be accurate.

**Comment by Apimius** [comment]
There must be some underlying problem in the coding that still calculates resistances for holy damage

**Comment by Apimius** [comment]
Under which assumption did this issue get closed?

**Comment by Apimius** [comment]
Under which assumption did this issue get closed?

**Comment by ratkosrb** [comment]
The chance for holy spells to be resisted will be lowered in the next update.

**Comment by Apimius** [comment]
> The chance for holy spells to be resisted will be lowered in the next update.

I hope with lowered you mean setting it to 0 in every circustance as that is blizzlike.
