### ISSUE TITLE
Mother's Milk - Quest Dialogue Unavailable

### ISSUE THREAD

**Issue by usedcars4cheap** [slowtorta/turtlewow-bug-tracker#2295]
For quest Mother's Milk - https://database.turtle-wow.org/?quest=4866

Expected dialogue when received debuff from Mother Smolderweb--
![image](https://user-images.githubusercontent.com/68176649/196097862-d95bfdf2-1ce4-46fe-902c-e705ae3ebf3d.png)

Can be missing, conditions unknown.
![image](https://user-images.githubusercontent.com/68176649/196097575-db7061d6-4a84-4a1f-ad39-cd76ead2cdab.png)

Attempts to recreate:
- Multiple players seem to be able to turn in this quest in quick succession
- Presence of another unrelated poison doesn't seem to interfere

**Comment by slowtorta** [comment]
What race/class your character is?

**Comment by usedcars4cheap** [comment]
Experienced by players from both factions (Undead Priest, Night Elf Druid)
In two separate incidents, multiple party members were on the quest - some were successful, some could not see dialogue
Tested affected player using separate character on account - one worked and one didn't, doesn't appear to be client/WDB-related?

**Comment by sieleyah** [comment]
Could it be that multiple party members being on the quest could confuse the NPC?  It worked just fine to me when I handed in the quest alone (Undead warlock)
Another thing I can think of is that some specific elixirs or buffs mess with the detection, which not all party members have.
Lastly, you most certainly cannot progress the quest if your party is set to raid group, which some spire groups are.

**Comment by sieleyah** [comment]
To elaborate on option one: We had a similar issue with a dungeon quest in Dire Maul, where you have to find some guy's remains. Upon the first player interacting with the bones, half the party had the quest randomly completed, the other half failed. No such issue when going there alone.

**Comment by usedcars4cheap** [comment]
- Multiple party members confuse NPC? Possibly?
    - Incident 1: 1 party member able to turn in, 1 party member unable to turn in, 2 party members able to turn in
    - Incident 2: 1 party member able to turn in, 2 party members unable to turn in, no further party members on quest
- Presence of other spellauras interfering with Ragged John's ability to detect the poison sounds possible?
- In both cases, the party was set to "party" and not "raid"
- Issue persisted for affected players through reloadui and relogging
-

**Comment by jameyboor** [comment]
Any level discrepancies?

**Comment by usedcars4cheap** [comment]
Players unable to turn in quest were all level 60

First occurrence in party with all level 60s
Second occurrence in party with mixed levels (don't recall the exact numbers)

**Comment by slowtorta** [comment]
Is this still relevant?

**Comment by redmagejoe** [comment]
Able to reproduce but unable to narrow down the cause for why it is not consistent across characters.
