### ISSUE TITLE
Oversight: Plainsrunning can be used with shaman water walking.

### ISSUE THREAD

**Issue by Oomsdvc** [slowtorta/turtlewow-bug-tracker#2296]
**Please, provide a clear description what the bug is:**

Tauran shamans can use Plainsrunning and water walking at the same time. this is an imbalance in my eyes because you cannot use mounts or shapeshift while maintaining water walking since it will be dispelled when you do.

**Steps to reproduce the behavior with as much detail as possible:**

1. Cast water walking on self.
2. Cast Plainsrunning.
3. Observe how water walking is not broken.

**IDs of affected creatures, items, quests or spells with a link to the relevant page:**

Spell: https://database.turtle-wow.org/?spell=546
Spell: https://database.turtle-wow.org/?spell=12568

**Expected behavior. Describe how it should work:**

Plainsrunning is custom content, i am in no position to say how it should or should not work. But i deem it an oversight as mounting up or shapeshifting breaks water walking while Plainsrunning does not. I have experienced first hand how powerful it can be against other players, both in competing for resources and pvp.

In my situation i am an orc shaman that runs between wreckage pools in Azshara, but a tauren shaman took over my fishing route with her massive speed which i felt was quite unfair. There is certainly some bias here but i hope it doesn't take away from the argument i've made.

**Comment by 9600bauds** [comment]
Every time I've pointed out that plainsrunning is insanely annoying to use and a total downgrade from mounts in almost every imaginable way, an angry mod was quick to point out that uhhh waterwalking plainsrunning is a thing so, there, it's balanced or something.

So yeah, we COULD have plainsrunning that doesn't make you want to rip your teeth out with the blunt end of a hammer, but we get this instead. Fun.

**Comment by jameyboor** [comment]
This is intended and won't be fixed.
