### ISSUE TITLE
Mob: Wildthorn Lurker

### ISSUE THREAD

**Issue by Pythol** [slowtorta/turtlewow-bug-tracker#23]
**Current behavior**:  The Wildthorn Lurkers in the "Warsong Lumber Camp" in "Ashenvale" respawn instantly.
https://database.turtle-wow.org/?npc=3821

**Expected behavior**: I guess they should have a respawn timer like other mobs?

**Proofs**: X

**Steps to reproduce**:

1. Kill a Wildthorn Lurker
2. 
3.

**Comment by slowtorta** [comment]
Thanks for reporting it. It'll be fixed on the next server restart. Make sure to clear your WDB folder.
