### ISSUE TITLE
Item Gnomish Cloaking Device doesn't work

### ISSUE THREAD

**Issue by Energizer188** [slowtorta/turtlewow-bug-tracker#2301]
**Please, provide a clear description what the bug is:**
The item Gnomish Cloaking Device doesn't work at all. It does not make us invisible, nor reset the mob when we are in combat.

**Steps to reproduce the behavior with as much detail as possible:**
Attack a mob and use it while in combat. The mob still see you and hit you.
Same thing with another player, they still see you when you use it.

**IDs of affected creatures, items, quests or spells with a link to the relevant page:**
Item: https://database.turtle-wow.org/?item=4397

**Expected behavior. Describe how it should work:**
Well, it's supposed to make us invisible, and reset the mob if we are in combat.
Other players can't see us nor target us, but they can hit us with AOE spells. If we get hit by an AOE the effect is cancelled.

**Comment by redmagejoe** [comment]
This issue persists on current version.

**Comment by Zeyla-TW** [comment]
As for the first issue (does not make you invisible) I was able to successfully use the cloaking device and run directly through hostile mobs without aggroing them, so it appears to be functioning in that regard.

As for the second issue (does not reset mob/remove you from combat) we would have to determine which iteration of the cloaking device we wish to have, as Blizzard changed the way this item functioned on multiple occasions. In this case, I believe you're remembering the function of the cloaking device during the early days of Classic WoW's launch, when it did indeed have an effect similar to vanish, but was later fixed to be more in line with the original function (when it wasn't usable in combat at all).

For now I believe we can call this working as intended unless the staff determines to implement the vanish-like version of the trinket's function at a later date.
