### ISSUE TITLE
Honoring the Departed, sprigs of Auribloom can't be interact with

### ISSUE THREAD

**Issue by Tinyfin-github** [slowtorta/turtlewow-bug-tracker#2302]
Honoring the Departed, sprigs of Auribloom can't be interact with

https://database.turtle-wow.org/?quest=40368

Player reported the same issue with https://database.turtle-wow.org/?quest=80258 Tears of the Poppy
This bug  can only be reproduced by logging on the players who encounters the issues character. [Contact Tinyfin for names]
It was tested on a clean client,  with the latest patches, with no addons and wdb folder cleared.

https://screencast-o-matic.com/watch/c36q1nVt99w

**Comment by usedcars4cheap** [comment]
Issue also occurs with "A Crystal Clear Task" https://database.turtle-wow.org/?quest=80252

**Comment by redmagejoe** [comment]
Cannot reproduce.
