### ISSUE TITLE
Inner Focus  does not work with the new priest champion spells

### ISSUE THREAD

**Issue by Fin9622** [slowtorta/turtlewow-bug-tracker#2310]
Inner Focus  does not work with the new priest champion spells

**Comment by Apimius** [comment]
Inner Focus does not seem to work with any custom priest spell, like for example: Pain Spike, Shadow Mend

**Comment by slowtorta** [comment]
https://github.com/slowtorta/turtlewow-bug-tracker/issues/1967

**Comment by Gurky-Turtle** [comment]
https://github.com/slowtorta/turtlewow-bug-tracker/issues/3805
