### ISSUE TITLE
Warlock pet avoidance

### ISSUE THREAD

**Issue by sieleyah** [slowtorta/turtlewow-bug-tracker#2315]
**Please, provide a clear description what the bug is:**
Hi, I would like to report the custom turtle avoidance not working at all on warlock pets. 
I don't know if they even have the buff, because the grimoire we get at lvl 40 is bugged and unusable, however I confirm they take full damage from raid AOE effects (such as meteors on AQ trash, poison bolts in ZG, shadow bolts in scholo, every kind of cleave etc.)
This defeats the whole purpose of the only notable class change we received to try and empower a pet based playstyle. Hunter pets with their new avoidance seem to have no trouble surviving most raid effects, but ours are essentially useless.

**Steps to reproduce the behavior with as much detail as possible:**
Go in any raid and see how long your pet lives.

**IDs of affected creatures, items, quests or spells with a link to the relevant page:**
I can't find ID of the grimoire or effect anywhere. It's some custom thing.

**Expected behavior. Describe how it should work:**
Warlock pets since the 1.16 update should be taking 50% mitigated AOE damage, allowing them to survive most raid encounters.

**Comment by sieleyah** [comment]
https://database.turtle-wow.org/?item=83584 grimoire that should teach spell

**Comment by sieleyah** [comment]
There is no improvement on this after update. Pets still take full damage from every source of AOE, grimoire is still bugged and unusable.

**Comment by Tinyfin-github** [comment]
> There is no improvement on this after update. Pets still take full damage from every source of AOE, grimoire is still bugged and unusable.

As it was described in the patch notes: The bug is fixed, but it needs a client update to work:

![image](https://user-images.githubusercontent.com/83077166/202231088-57875c4b-418b-456b-ad4e-b38875d6ace0.png)
https://forum.turtle-wow.org/viewtopic.php?f=63&t=4863&p=29337#p29337

**Comment by sieleyah** [comment]
Sigh. Why can't we just get it at lvl 50 automatically like hunters >,<
Thanks anyways, I missed that.
