### ISSUE TITLE
Overlord Wyrmthalak doesn't always drop loot

### ISSUE THREAD

**Issue by sieleyah** [slowtorta/turtlewow-bug-tracker#2317]
**Please, provide a clear description what the bug is:**
Hi, the last boss in LBRS seems to have an issue with loot table. Sometimes he drops no loot other than the alliance quest letter and the fashion coin. Very disappointing considering the dungeon is long and tiresome. 
Perhaps it's an issue with the fashion coin being considered the minimum drop of 1 item. That's just not right, it shouldn't replace normal loot but be an addition. (I think this might happen on other bosses with the coin too, but I haven't looked into it on a greater scale)

**Steps to reproduce the behavior with as much detail as possible:**
Just kill him enough times and sooner or later you will run into it.

**IDs of affected creatures, items, quests or spells with a link to the relevant page:**
https://database.turtle-wow.org/?npc=9568

**Expected behavior. Describe how it should work:**
Overlord Wyrmthalak should always drop at least one of his proper items on top of the fashion coin and the quest letter.

**Comment by usedcars4cheap** [comment]
This is also the situation with Quartermaster Zigris, although judging by historical Wowhead comments, Zigris not always dropping a blue item might have been intentional.

**Comment by sieleyah** [comment]
I know it is intended for Zigris, but not for Wyrmthalak. Zigris is an optional boss whose main loot table is potions. Even the Wiki outlines that he doesn't always drop other loot. This is not the case for Wyrmthalak. He is the end boss and I found no trace of any comments mentioning that he would sometimes drop no loot. Here so far it's been 2 out of 4 kills for me that he dropped nothing, which means it's very common.
