### ISSUE TITLE
Bristleback Aggression visual progress reset.

### ISSUE THREAD

**Issue by Kharkov72** [slowtorta/turtlewow-bug-tracker#2319]
https://database.turtle-wow.org/?quest=60150

**Steps to reproduce the behavior with as much detail as possible:**

1. Get Bristleback Quilboar https://database.turtle-wow.org/?npc=2952 to 6/6
2. Do the objectives for Preventive Strike https://database.turtle-wow.org/?quest=60115, https://database.turtle-wow.org/?npc=3229
3.  After picking up Attack on Camp Narache (https://database.turtle-wow.org/?quest=781) notice it goes down to 1/6 and no longer progresses.

**Expected behavior. Describe how it should work:**
It should have simply been at 6/6 and completed, but that was not the case. Unsure how it reset, really.

**Comment by Kharkov72** [comment]
Update, it's just a display bug, still scared the shit out of me though.

**Comment by slowtorta** [comment]
Sorry I was unable to reproduce this bug.
