### ISSUE TITLE
Darkspear Trolls reputation cloth turn in  does not work

### ISSUE THREAD

**Issue by SierraNairn** [slowtorta/turtlewow-bug-tracker#232]
Darkspear Trolls reputation cloth turn in  does not work

How it should work: after completing A Donation of Mageweave Vehena should give you A Donation of Runecloth.
What does not work: Vehena does not give you  A Donation of Runecloth.

https://database.turtle-wow.org/?npc=14727 Vehena <Horde Cloth Quartermaster>
https://database.turtle-wow.org/?quest=7835 A Donation of Mageweave 
https://database.turtle-wow.org/?quest=7836 A Donation of Runecloth

Note: In the database A donation of Mageweave from Vehena  is connected to A Donation of Runecloth from Rashona  the Ogrimmar reputation cloth turn in npc.
Rashona Straglash https://database.turtle-wow.org/?npc=14726

**Comment by slowtorta** [comment]
Thanks for reporting it. It'll be fixed on the next server restart. Make sure to clear your WDB folder.
