### ISSUE TITLE
Character with the buff "Skeletone costume" is not able to use flights and mounts

### ISSUE THREAD

**Issue by valentynpozniakov** [slowtorta/turtlewow-bug-tracker#2322]
**Character with the buff "Skeletone costume" is not able to use flights and mounts**

**Steps to reproduce:**

1. Log in to WoW
2. Go to any Innkeeper
3. Click to talk and select the "trick or treat" option (Haloween addition)
4. Try to use a mount or use flights to get to another location

**IDs of affected creatures, items, quests, or spells with a link to the relevant page:**

NPC: https://database.turtle-wow.org/?npc=6741
Spell: https://database.turtle-wow.org/?spell=24723

![wowissue1-2](https://user-images.githubusercontent.com/67410840/197280840-8629b5eb-19fb-406d-9138-5b1036a8cb54.png)
![wowissue1](https://user-images.githubusercontent.com/67410840/197280862-2c402f1c-4d8b-4aba-8b20-37601780f3d6.png)

**Expected: User should be able to use at least flights:**

**Comment by mikefirefly** [comment]
Cilck on the buff near your minimap - it will be gone and you'll be able to fly etc.
Every costume works like that, not only skeleton btw.

**Comment by slowtorta** [comment]
This is intended, works the same on Classic and in Vanilla.
