### ISSUE TITLE
Removing/Reducing Holy Damage Reduction On Chromaggus/Death Talon Wyrmguard/Death Talon Overseer

### ISSUE THREAD

**Issue by Apimius** [slowtorta/turtlewow-bug-tracker#2323]
Currently Chromaggus and the Death Talon Wyrmguards/Death Talon Overseers in BWL have 75% damage reduction to holy spells. Since there is no holy vulnerability for these NPCs there should also be no damage reduction for the holy magic school.

**Steps to reproduce the behavior with as much detail as possible:**

1. Go into BWL and Smite Chromaggus or a Death Talon Wyrmguard/Death Talon Overseer
2. Notice that the damage is reduced by 75%
3. Notice that there is no holy vulnerbility for these NPCs

**IDs of affected creatures, items, quests or spells with a link to the relevant page:**

NPCs: https://database.turtle-wow.org/?npc=14020, https://database.turtle-wow.org/?npc=12460, https://database.turtle-wow.org/?npc=12461

**Expected behavior. Describe how it should work:**

There should be either no damage reduction for holy spells on these NPCs or a holy vulnerability.

**Comment by Velite12** [comment]
This isn't really a bug, this is more of an oversight and already has multiple posts on the forums. So this is really more of a suggestion than a bug, because it is supposed to technically work like this in vanilla BWL. I'd recommending moving the discussion there.
