### ISSUE TITLE
Stormcloth Boots can't be disenchanted

### ISSUE THREAD

**Issue by Tinyfin-github** [slowtorta/turtlewow-bug-tracker#2324]
Stormcloth Boots can't be disenchanted

https://database.turtle-wow.org/?item=10039

**Comment by slowtorta** [comment]
This is intended behavior, many crafted items cannot be disenchanted. https://www.wowhead.com/classic/item=10039/stormcloth-boots

**Comment by slowtorta** [comment]
I was wrong, apparently, this set should have disenchant IDs assigned. Will be fixed in the next update.
