### ISSUE TITLE
"Preventive Strike" minor paragraph indent defects still

### ISSUE THREAD

**Issue by MorlanOriginal** [slowtorta/turtlewow-bug-tracker#2327]
**Please, provide a clear description what the bug is:**
Even after previous fix in quest texts still exist minor defects. In both quest acquiring and quest completing texts.

**Steps to reproduce the behavior with as much detail as possible:**
1. Come to [Brave Windfeather](https://database.turtle-wow.org/?npc=3209) in Camp Narache at Red Cloud Mesa in Mulgore;
2. Accept [Preventive Strike](https://database.turtle-wow.org/?quest=60115);
3. Complete [Preventive Strike](https://database.turtle-wow.org/?quest=60115).

**IDs of affected creatures, items, quests or spells with a link to the relevant page:**
NPC: [Brave Windfeather](https://database.turtle-wow.org/?npc=3209)
Quest: [Preventive Strike](https://database.turtle-wow.org/?quest=60115)

**Expected behavior. Describe how it should work:**
Paragraph indent should be added in underline spots.
![WoWScrnShot_102222_081900_cr](https://user-images.githubusercontent.com/112715239/197346514-9275d77d-c8d7-4320-8f10-19d77ef02c5b.png)
![WoWScrnShot_102222_085712_cr](https://user-images.githubusercontent.com/112715239/197346517-08eab2b1-9bb2-4137-b49d-82a38459eff1.png)

**Comment by slowtorta** [comment]
The fixes are not applied immediately. Please wait for the server update this Wednesday :)

**Comment by MorlanOriginal** [comment]
In previous iteration all texts was without indents at all. So i suppose previous fix with paragraph indent was applied. But their stiil 2 minor typos that can be seen on screens.

**Comment by slowtorta** [comment]
Don't worry. We noticed that as well, it's part of the development revision that isn't in production yet.
