### ISSUE TITLE
NPC: Gurubashi Mojo Madness Tablet

### ISSUE THREAD

**Issue by Sringaram** [slowtorta/turtlewow-bug-tracker#2329]
ID: No idea.

The tablet behind the gong appears to not be clickable to maxed alchemists so they can't learn the recipe. No idea if it's broken for good or this only happens sometimes.

**Comment by slowtorta** [comment]
Not enough information.

**Comment by Sringaram** [comment]
I'm talking about this:

https://www.wowhead.com/classic/guide/edge-of-madness-zul-gurub-strategy

The recipe to create the mojo is learned through the big tabled behind the summoning brazier but only 300 alchemists can interact with it.

**Comment by slowtorta** [comment]
I see, thank you. Currently, in our database, 148 people have this recipe learned, so I assume it's working as intended :)

**Comment by Sringaram** [comment]
I've had to open a ticket and a GM triggered the script interaction for us because the tablet wasn't clickable.
