### ISSUE TITLE
Raw Sagefish does show food buff

### ISSUE THREAD

**Issue by Gr0vey** [slowtorta/turtlewow-bug-tracker#233]
Eating Raw Sagefish does not restore health (No buff appears)

How it should work: It should give Brain Food and Food buffs - restoring mana and health

https://database.turtle-wow.org/?item=21071 Raw Sagefish
https://database.turtle-wow.org/?spell=25701 Brain Food
https://database.turtle-wow.org/?spell=25700 Food

**Comment by slowtorta** [comment]
Thank you, it'll be fixed on the next update. 
![image](https://user-images.githubusercontent.com/66763404/159126447-9f5653f4-d2ff-4b1d-8da3-deb110ac4cc2.png)
