### ISSUE TITLE
Adamantite Rod is not present on the loot table of the mob is supossed to drop from.

### ISSUE THREAD

**Issue by SierraNairn** [slowtorta/turtlewow-bug-tracker#234]
Adamantite Rod is not present on the loot table of the mob is supossed to drop from.
Adamantite Rod- https://database.turtle-wow.org/?item=81282
Mob- https://database.turtle-wow.org/?npc=11120 
It's needed for the quest to build a pounder- https://database.turtle-wow.org/?quest=80401

**Comment by slowtorta** [comment]
Thanks for reporting it. It'll be fixed on the next server restart. Make sure to clear your WDB folder.
