### ISSUE TITLE
Object: Earthroot

### ISSUE THREAD

**Issue by cyaohiri** [slowtorta/turtlewow-bug-tracker#2342]
[Earthroot](https://database.turtle-wow.org/?object=1619) in Darkshore at 47.3, 48.8 (next to the [Mysterious Red Crystal](https://database.turtle-wow.org/?object=175524)) spawns underground.

**Comment by slowtorta** [comment]
Please report misplacements of NPC or objects via in-game ticket, GMs have the tools to fix those.
