### ISSUE TITLE
Item: Healthstone

### ISSUE THREAD

**Issue by cyaohiri** [slowtorta/turtlewow-bug-tracker#2343]
[Healthstones](https://database.turtle-wow.org/?search=healthstone), unlike healing potions, are usable at full health, which doesn't seem right.

**Comment by ratkosrb** [comment]
I can't reproduce the issue. Healthstones are not usable at full health.
![WoWScrnShot_102322_161058](https://user-images.githubusercontent.com/35845488/197394212-5677418f-877c-480e-b0a2-2252e9d6907e.jpg)

**Comment by cyaohiri** [comment]
I haven't tried it as a warlock, the healthstones I tested it on were traded to me, but I don't remember what rank they were.

**Comment by ratkosrb** [comment]
I am unable to use traded Healthstones either.

**Comment by cyaohiri** [comment]
This was from about a month ago, so it's possible something changed in the meantime. Will reopen if I reproduce the issue.
