### ISSUE TITLE
NPC: Bluegill Muckdweller

### ISSUE THREAD

**Issue by cyaohiri** [slowtorta/turtlewow-bug-tracker#2344]
[Bluegill Muckdweller](https://database.turtle-wow.org/?npc=1028) at 11.9, 33.7 is stuck underground underwater. He can be found about 40 yards south of the boat, following the coastline.

**Comment by slowtorta** [comment]
Please report misplacements of NPC or objects via in-game ticket, GMs have the tools to fix those.
