### ISSUE TITLE
Item: Report on the Defias Brotherhood

### ISSUE THREAD

**Issue by cyaohiri** [slowtorta/turtlewow-bug-tracker#2348]
The text inside the [Report on the Defias Brotherhood](https://database.turtle-wow.org/?item=2956) isn't separated by paragraphs, and the last letter on the first three pages is missing.

**Comment by ratkosrb** [comment]
The lack of paragraphs is blizzlike, but the missing letters will be fixed.

**Comment by cyaohiri** [comment]
Paragraphs seem to be existent, at least according to the text here: https://www.wowhead.com/classic/item=2956
