### ISSUE TITLE
 Ogrimmar reputation cloth turn is bugged

### ISSUE THREAD

**Issue by SierraNairn** [slowtorta/turtlewow-bug-tracker#235]
Ogrimmar reputation cloth turn is bugged
 How it should work: Rashona Straglash should  give you a A Donation of Runecloth after you complete a A Donation of Mageweave.
 What does not work: Rashona Straglash does not give you a A Donation of Runecloth.
  Rashona Straglash https://database.turtle-wow.org/?npc=14726
  A Donation of Mageweave  https://database.turtle-wow.org/?quest=7831
  A Donation of Runecloth https://database.turtle-wow.org/?quest=7824
  
  Note: In the database A donation of Mageweave  from Rashona is connected to  A Donation of Runecloth from Vehena  the darkspear trolls cloth turn in npc.
  Vehena -https://database.turtle-wow.org/?npc=14727

**Comment by slowtorta** [comment]
Thanks for reporting it. It'll be fixed on the next server restart. Make sure to clear your WDB folder.
