### ISSUE TITLE
Fara Boltbreaker inaccessiable

### ISSUE THREAD

**Issue by MorlanOriginal** [slowtorta/turtlewow-bug-tracker#2351]
**Please, provide a clear description what the bug is:**
Due Hallow's End event [Fara Boltbreaker](https://database.turtle-wow.org/?npc=50530) stay inside pumpkin and players cant interact with her.

**Steps to reproduce the behavior with as much detail as possible:**

1. Come to Orgrimmar neat Auction House where [Fara Boltbreaker](https://database.turtle-wow.org/?npc=50530) stay.

**IDs of affected creatures, items, quests or spells with a link to the relevant page:**

NPC: [Fara Boltbreaker](https://database.turtle-wow.org/?npc=50530)

**Expected behavior. Describe how it should work:**
Npc/Pumpkin should be moved. And access to NPC should be restored.
![WoWScrnShot_102322_132901](https://user-images.githubusercontent.com/112715239/197399131-937ca5b2-9434-4038-b92d-be0f7fa6f010.png)

**Comment by slowtorta** [comment]
She's been rescued by GM Pumpkin.
