### ISSUE TITLE
Can't create mooncloth in a moonwell near Dire Maul

### ISSUE THREAD

**Issue by zhorabzhora** [slowtorta/turtlewow-bug-tracker#2352]
**Please, provide a clear description what the bug is:**
Can't create mooncloth in a moonwell near Dire Maul

**Steps to reproduce the behavior with as much detail as possible:**
Try to create a mooncloth near that moonwell (Feralas, 58 45)

**IDs of affected creatures, items, quests or spells with a link to the relevant page:**
Spell: https://database.turtle-wow.org/?spell=18560

**Expected behavior. Describe how it should work:**
Should be able to purify felcloth there

**Comment by slowtorta** [comment]
The Moonwell is corrupted and destroyed, so it's working as intended :)
