### ISSUE TITLE
NPC: Whirlwind Shredder

### ISSUE THREAD

**Issue by cyaohiri** [slowtorta/turtlewow-bug-tracker#2353]
As mentioned in #1935 and #2218, [Whirlwind Shredders](https://database.turtle-wow.org/?npc=11578) teleport around and behave strangely as seen in the video below.

https://www.veed.io/view/cdd674a5-73b4-427f-9a15-7e00128da39f

At 2:00 you can see a pack of [Rabid Bonepaw](https://database.turtle-wow.org/?npc=4690) hyenas being pulled from quite a distance, possibly pulled by the shredders.
At 2:14, [Burning Blade Felsworn](https://database.turtle-wow.org/?npc=4666) seems to appear out of nowhere, possibly pulled by the shredders from much farther west, as these units aren't found in this area.
At 2:55 you can see the hyena pack leaving combat, and then reentering it 3 seconds later. They do this again at 3:11, and they reenter combat at 3:13.
At 3:08 you can see my location on the map.
At 3:37, the remaining shredder for seemingly no reason leaves combat and stops moving until I engage, at 3:53.

As a side note, based on our and Wowhead's database, [Whirlwind Shredders](https://database.turtle-wow.org/?npc=11578) shouldn't even be in the northern half of the zone.

Regarding the fix https://github.com/slowtorta/turtlewow-bug-tracker/issues/2218#issuecomment-1267179619, I did see shredders in the south of the zone that are indeed not moving when out of combat and are working properly, so it seems like the fix didn't apply to all of them, but only to shredders in the south, where they're supposed to be.

**Comment by slowtorta** [comment]
Fixed on the next update.
