### ISSUE TITLE
Ancient Frostsaber missing a sound

### ISSUE THREAD

**Issue by whoopie-cushion** [slowtorta/turtlewow-bug-tracker#2355]
Ancient Frostsaber's stationary animation does not produce a (roar) sound.

1. Mount Frostsaber
2. Press the Space key
3. Mount will do animation, but the expected 'cat roar' sound does not occur

Item: https://database.turtle-wow.org/?item=12302

I honestly don't know if this is normal behavior. Maybe this item always had no sound attached to the stationary animation. I also don't know if this affects other cat mounts. The summon noise _does_ work; I believe the stationary sound should be the same: SummonerTiger

**Comment by Apimius** [comment]
It is the same for the Golden Sabercat.

**Comment by slowtorta** [comment]
I tested those and a few default Vanilla cat mounts and none of them has this sound. It's probably normal for 1.12.* client.
