### ISSUE TITLE
Blessing of sanctuary following spell coefficients for reduction

### ISSUE THREAD

**Issue by Velite12** [slowtorta/turtlewow-bug-tracker#236]
EDIT: Some spells appear to be taking less of a reduction than they should, and it has come to my attention that the no-coefficient spells do indeed take full reduction from sanctuary. However, there are spells which are taking less of a reduction than in 2006/classic, so that is the focus of my issue, is whether or not sanctuary should be following spell coefficients.

Currently, blessing of sanctuary is not reducing damage taken from many spells in the game. A very clear example of blessing of sanctuary working against spells is against ragnaros. I have two videos from classic showing that Blessing of sanctuary reduces his elemental fire spell (https://database.turtle-wow.org/?spell=20564) damage by _Exactly_ the amount provided by the spell:

https://www.youtube.com/watch?v=7pkhwkwkIYM
https://www.youtube.com/watch?v=277yEO2PXyo

![image](https://user-images.githubusercontent.com/45871932/128649148-7c3a9eca-67be-44bb-aa79-9ee9742f3796.png)
![image](https://user-images.githubusercontent.com/45871932/128649175-8371989d-4087-4fd5-bf5d-dfeb3cd68230.png)

The first video shows a rank 1 Blessing of sanctuary (indicated by the 14 damage dealt during blocks) reducing the damage of the dot from 600 to 590, hence, -10 damage taken. The second video shows the same thing with a max rank greater blessing of sanctuary reducing the damage taken from elemental fire by 24, as the tooltip states.

https://legacyplayers.com/viewer/1339/event_log/to_actor

Here I have a ragnaros kill on turtle wow, where despite having greater blessing of sanctuary, as shown by the damage procs in the logs, i still take full damage from the elemental fire ticks.

As additional evidence, here is a log showing that the damage reduced for spell: https://database.turtle-wow.org/?spell=26053 was consistent with -24 damage reduction from blessing of sanctuary, so the effect is not isolated to Ragnaros, _**Blessing of sanctuary should be reducing spell damage (non-physical) by the exact amount said on the tooltip.**_ https://classic.warcraftlogs.com/reports/kvnTzwLhKbRYrBH2#fight=26&type=damage-taken&source=8&ability=26053

My speculation for the cause is the discrepancy in the spell effects:

![image](https://user-images.githubusercontent.com/45871932/128649741-7c229dae-c3be-41be-bc8a-14785b92b1e5.png)
![image](https://user-images.githubusercontent.com/45871932/128649745-465c480a-7dda-4c3e-a2eb-327f5ed30f8d.png)

Spells:

https://database.turtle-wow.org/?spell=25899
https://database.turtle-wow.org/?spell=20911
https://database.turtle-wow.org/?spell=20912
https://database.turtle-wow.org/?spell=20913
https://database.turtle-wow.org/?spell=20914

**Comment by Velite12** [comment]
As a further comment I believe this issue is caused by a previous issue: https://github.com/slowtorta/turtlewow-bug-tracker/issues/175. It seems that upon testing Blessing of sanctuary, Rank 1 was able to reduce damage taken from https://classic.wowhead.com/spell=9834/moonfire by 1 point of damage (10%) and then by 3 points of damage with max rank (it reduces by 24 so it seems the value is rounded up). It seems as though damage reduction taken is factored into the resistance equation when it should not be.

**Comment by Velite12** [comment]
![image](https://user-images.githubusercontent.com/45871932/128651281-6cf85e38-287c-4461-8d1b-456f16b5e3fb.png)

Tested on my own local, even a spell that doesn't follow the 10% resistance rule doesn't have any damage reduction from sanctuary.

**Comment by Velite12** [comment]
![image](https://user-images.githubusercontent.com/45871932/128782272-1cb09da7-8fc0-4efb-aaa4-83cad42c1980.png)
On my vmangos test server, sanctuary is reducing the damage of ragnaros' dot by 24, dealing 576 damage. So this is an issue just on Turtle wow.

**Comment by Nolin7777** [comment]
Possible fix will be applied on next maintenance.
Please re-open in case issue still exists.
