### ISSUE TITLE
NPC: Icepoint Whiteclaw

### ISSUE THREAD

**Issue by cyaohiri** [slowtorta/turtlewow-bug-tracker#2364]
[Icepoint Whiteclaws](https://database.turtle-wow.org/?npc=60545) are level 44-46 bears (beasts), but cannot be skinned, drop money and Heavy Leather instead of dropping what other bears of similar level drop. A good example for both the drop and skinning would be [Grizzled Ironfur Bears](https://www.wowhead.com/classic/npc=5272/grizzled-ironfur-bear).

**Comment by cyaohiri** [comment]
When copying the loot table from [Grizzled Ironfur Bear](https://database.turtle-wow.org/?npc=5272), you've copied the [OOX-17/TN Distress Beacon](https://database.turtle-wow.org/?item=8623) which shouldn't drop there.

**Comment by cyaohiri** [comment]
@twowTurtReynolds, could you reopen this? I don't want to open a new issue for the same NPC. The pelt is fine, but it still drops those two quest items it shouldn't.

**Comment by ratkosrb** [comment]
It will be fixed in the next update.
