### ISSUE TITLE
Item: Razorflank's Heart

### ISSUE THREAD

**Issue by cyaohiri** [slowtorta/turtlewow-bug-tracker#2366]
[Razorflank's Heart](https://database.turtle-wow.org/?item=5793) can be looted as Alliance, even though it's required for a Horde-only quest. Moreover, it shouldn't even drop if one doesn't have the quest.

It's possible [Razorflank's Medallion](https://database.turtle-wow.org/?item=5792) has the same issue on the Horde side.

**Comment by slowtorta** [comment]
Couldn't reproduce it, it doesn't drop for me without the quest.
