### ISSUE TITLE
Quest: James Hyal part II bugged

### ISSUE THREAD

**Issue by Wollepetri** [slowtorta/turtlewow-bug-tracker#2368]
Hey everyone,

I realized today that when I turned in the "[James Hyal](https://database.turtle-wow.org/?quest=1301)" quest Part I and wanted to accept [Part II](https://database.turtle-wow.org/?quest=1302), the game gave me the "Quest failed" sound and told me: "You don't meet the requirements for that quest." Now I can't accept the part II anymore - no more exclamation mark over the NPC's head. But in the map the quest is still shown as "available" (yellow exclamation mark).

As stated: I finished the first part, I saw the exclamation mart over the head of [Vincent Hyal](https://database.turtle-wow.org/?npc=5082) in the Menethil Harbor inn and as soon as I wanted to "Accept" the quest, I was given the "quest failed" sound and the notification in the chat.

Is this a known issue and can a GM give me part II of the quest?

Kind regards

Wolle

**Comment by ratkosrb** [comment]
You've most likely done quest 'They Call Him Smiling Jim' which is exclusive to this one.

![Untitled](https://user-images.githubusercontent.com/35845488/198348487-dd0fead1-3b16-4991-8ee6-5128a2242e73.jpg)

**Comment by slowtorta** [comment]
Tested, but couldn't reproduce it! Please confirm with GMs that you haven't completed an exclusive quest :)
