### ISSUE TITLE
Turtle Finder raid group bug report

### ISSUE THREAD

**Issue by Xerrash** [slowtorta/turtlewow-bug-tracker#2372]
**Please, provide a clear description what the bug is:**
If someone searches "find more" while in a raid group it seems to invite people from turtle finder but it doesn't register which dungeon you are queued for.
**Steps to reproduce the behavior with as much detail as possible:**

1. Have a raid group (I assume, it happened to me, I wasn't the one doing it)
2. Press find more.
3.  People join without knowing what they joined.

**IDs of affected creatures, items, quests or spells with a link to the relevant page:**

NPC: https://database.turtle-wow.org/?npc=
Item: https://database.turtle-wow.org/?item=
Quest: https://database.turtle-wow.org/?quest=
Spell: https://database.turtle-wow.org/?spell=
Object: https://database.turtle-wow.org/?object=

**Expected behavior. Describe how it should work:**
It should tell you which dungeon you queued for.

**Comment by slowtorta** [comment]
Client issue, thanks. Moving this to our internal bug tracker.
