### ISSUE TITLE
"Zalazane's Apprentice" rewarded with "The Defilers" reputation

### ISSUE THREAD

**Issue by MorlanOriginal** [slowtorta/turtlewow-bug-tracker#2373]
**Please, provide a clear description what the bug is:**
After completing [Zalazane's Apprenice](https://database.turtle-wow.org/?quest=80399) players rewarded with Orgrimmar and The Defilers reputations.

**Steps to reproduce the behavior with as much detail as possible:**

1. Drop [Shabby Letter](https://database.turtle-wow.org/?item=59990) from [Hexed Troll](https://database.turtle-wow.org/?npc=3207) or [Voodoo Troll](https://database.turtle-wow.org/?npc=3206);
2. Kill [Makasgar](https://database.turtle-wow.org/?npc=13157) and loot him;
3. Complete quest at [Master Gadrin](https://database.turtle-wow.org/?npc=3188).

**IDs of affected creatures, items, quests or spells with a link to the relevant page:**

Quest: [Zalazane's Apprenice](https://database.turtle-wow.org/?quest=80399)

**Expected behavior. Describe how it should work:**
Change The Defilers reputation to Darkspear Trolls.

**Comment by ratkosrb** [comment]
https://github.com/slowtorta/turtle-wow/commit/9c00325908f65a02e5ab8caa302356f867620aaf
