### ISSUE TITLE
"Dustwind Cave" pathfinding bug

### ISSUE THREAD

**Issue by MorlanOriginal** [slowtorta/turtlewow-bug-tracker#2379]
**Please, provide a clear description what the bug is:**
In Dustwind Cave in Durotar warriors charge not possible into mobs. Suppose hunter and warlock pets have issues with targeting in this cave aswell.

**Steps to reproduce the behavior with as much detail as possible:**

1. Come to Durotar at Dustwind Cave location.
2. Try to charge as warrior in mobs inside. Or if issiue with hunters or warlocks order pets to attack.

**Expected behavior. Describe how it should work:**
Fix a paths inside a cave.
![WoWScrnShot_102822_121901](https://user-images.githubusercontent.com/112715239/198558748-0804bf78-6c77-43cd-b13b-ba01a5aa5502.png)

**Comment by slowtorta** [comment]
Not related to this specific cave, otherwise, the issue is known!
