### ISSUE TITLE
error message

### ISSUE THREAD

**Issue by Fierce666** [slowtorta/turtlewow-bug-tracker#2380]
an error message keeps popping up in the middle of my screen. i can press "Okay". sometimes its gone for a while. it always comes back, sometimes real quick too.
i tried disabling addons and resetting settings (renamed folder in WTF thats named after my character). the error message says:
...e/FrameXML/Turtle_GuildBankUI/Turtle_GuildBankUI.lua:2370: bad argument #1 to 'tinsert' (table expected, got nil)

now, the good people in tickets couldn't help me, that's why i'm here.

**Comment by Fierce666** [comment]
![Uploading B6E938CE-C182-4BEF-98FE-2CB273983BEF.jpeg…]()

**Comment by Fierce666** [comment]
![BFFDE2BD-9A23-4564-993E-837B26B323D2](https://user-images.githubusercontent.com/116917937/198825551-c02f371d-c065-4972-8fab-85287da3fd37.png)

This person has the same problem.

**Comment by Fierce666** [comment]
Ok, I‘m just getting ShaguError. But maybe you can still fix that <3

**Comment by slowtorta** [comment]
Please make a screenshot of your Data folder, including the file sizes.

**Comment by Fierce666** [comment]
![File-sizes-screenshot](https://user-images.githubusercontent.com/116917937/198974546-b89e6a4f-0739-455e-901a-ec4d27a1ae26.jpeg)

sure, its in german. hope thats no problem. i played around a little with sound.MPQ. it had nothing to do with guild banks (ofc).

**Comment by slowtorta** [comment]
Thanks. Are you getting this error with all addons disabled?

**Comment by slowtorta** [comment]
Couldn't reproduce. Please try to download a fresh client from the website and disable your addons, to see if the issue persists.
