### ISSUE TITLE
Curse of Weakness reducing elemental weapon/wand damage

### ISSUE THREAD

**Issue by Kangaroux** [slowtorta/turtlewow-bug-tracker#2384]
**Please, provide a clear description what the bug is:**

Curse of Weakness buff applied by Mosh'Ogg ogres outside grom'gol reduces physical damage, but appears to also be reducing shadow damage from wand.

![image](https://user-images.githubusercontent.com/2302541/198846012-09576050-f926-47c5-8d91-1e6bd89dee19.png)

## Before receiving curse:
![image](https://user-images.githubusercontent.com/2302541/198846072-884f71a6-caf8-4a9e-909f-8d046397eb8f.png)

## After receiving curse:
![image](https://user-images.githubusercontent.com/2302541/198845961-fa508496-06b0-4eef-ab67-194ac975e3c6.png)

**Steps to reproduce the behavior with as much detail as possible:**

1. Receive curse
2. Use wand
3. Check damage per hit is reduced and that it's not because of resist

**IDs of affected creatures, items, quests or spells with a link to the relevant page:**

NPC: https://database.turtle-wow.org/?npc=1144
Spell: https://database.turtle-wow.org/?spell=11980

**Expected behavior. Describe how it should work:**
Elemental damage from wands should not be affected

**Comment by Zeyla-TW** [comment]
I know this may be misleading, but abilities that reduces phyiscal damage (like curse of weakness) are intended to apply directly to the weapon damage range in your character sheet, regardless of the damage type that your weapon deals. Changing the way that this functions for specific items (like wands or melee weapons that add/deal elemental damage) would be rather difficult. For now we should consider this to be working as intended.
