### ISSUE TITLE
Exalted Requirement On Arathi Basin Tabards

### ISSUE THREAD

**Issue by Apimius** [slowtorta/turtlewow-bug-tracker#2385]
The Arathi Basin tabards have a exalted requirement on them but the Warsong tabards do not. These 2 BGs are rarely being played hence it is pretty much impossible to reach exalted in Arathi Basin to use the tabard. I am aware that the exalted requirement on the AB tabard is blizzlike, but as of now this makes no sense since no one will be realisticly be able to use them - AB is rarely played.

1.Look at the warsong tabards and then at the arathi tabards
2. Notice that the arathi tabards have a exalted rep requirement but the warsong ones do not
3. Notice that AB/WSG are rarely being played, hence its almost impossible to be able to use AB tabards.

Item: https://database.turtle-wow.org/?item=20132

The arathor battle tabard should have no rep requirement like the warsong gulch tabards.

**Comment by slowtorta** [comment]
Sorry, but we're not planning to remove the requirement only because the BG is rarely played. It'd make more sense to make the WSG tabard require reputation. Perhaps, lesser rank.

However, too late for this change! :)

**Comment by Apimius** [comment]
If the AB tabards would also be useable at friendly like the WSG tabards it would be totally fine.
