### ISSUE TITLE
Items sharing visual ID but not sharing the same weapon slot are not added to the transmogrification NPC

### ISSUE THREAD

**Issue by Apimius** [slowtorta/turtlewow-bug-tracker#2389]
I am not sure if this issue is only existent for this specific case but, when you either equip torch of austen (wand) or smoldering brand (mace), its gets added to the transmogrification NPC, the second one will not be added even though its a different weapon type. They both share the same visual ID which is why this is happening.

1. equip smoldering brand or torch of austen
2. notice it getting added to the transmog system
3. equip the other item and notice that this one will not get added to the transmog system even though its a different weapon type

Items: https://database.turtle-wow.org/?item=70047, https://database.turtle-wow.org/?item=13004

It should be possible to be able to transmog both items at the same time since they dont share the same weapon slot.

**Comment by jameyboor** [comment]
Fixed in next update.
