### ISSUE TITLE
Grayson's Torch sheathed is not visible if transmoged

### ISSUE THREAD

**Issue by Apimius** [slowtorta/turtlewow-bug-tracker#2390]
If you equip Grayson's Torch normaly you see it sheathed on the right hip of your character.

If you equip another offhand and trasmogrify it to look like Grayson's Torch it only appears when you unsheath it.

1. equip Grayson's Torch and notice you see it sheathed
2. transmog it to another offhand
3. notice that the transmoged offhand is not visible in the sheathed state like the original Grayson's Torch

When you transmog Grayson's Torch to an offhand it should be visible in a sheathed state.

**Comment by cyaohiri** [comment]
See #2172.

**Comment by Apimius** [comment]
So is that Treasure Seeker's Torch visible when sheathed?

**Comment by Apimius** [comment]
I know that Graysons Torch was visible when sheathed on classic wow (re-release of original vanilla).

**Comment by cyaohiri** [comment]
> So is that Treasure Seeker's Torch visible when sheathed?

It's not.

**Comment by slowtorta** [comment]
The transmogged item inherits the sheath of the base item. Sadly, right now this cannot be changed.
