### ISSUE TITLE
Improved shadow form got unlearn everytime respec/use brain wash device

### ISSUE THREAD

**Issue by JaceEverwood** [slowtorta/turtlewow-bug-tracker#2392]
**Please, provide a clear description what the bug is:**
after using the Brainwash device from donation shop to switch between talent builds. Priest lost improved shadow form. and it is required to go to a class trainer in major city to buy(19+ silver) the spell over and over again.  this should align with the other class's passive spells. this behavior is unusual

**Steps to reproduce the behavior with as much detail as possible:**

1. buy improved shadow form while in shadow spec
2. respec or use brain wash device to switch to shadow pvp or healing spec
3. need to go back to class trainer in city to relearn improved shadow form

**IDs of affected creatures, items, quests or spells with a link to the relevant page:**

NPC: https://database.turtle-wow.org/?npc=
Item: https://database.turtle-wow.org/?item=
Quest: https://database.turtle-wow.org/?quest=
Spell: https://database.turtle-wow.org/?spell=
Object: https://database.turtle-wow.org/?object=

**Expected behavior. Describe how it should work:**

**Comment by slowtorta** [comment]
Duplicate for https://github.com/slowtorta/turtlewow-bug-tracker/issues/1843
