### ISSUE TITLE
Improved Starfire seem not to sometimes apply.

### ISSUE THREAD

**Issue by DraxerTABC** [slowtorta/turtlewow-bug-tracker#2393]
**Please, provide a clear description what the bug is:**
Sometimes Starfire with the talent doesn't get 0.5s cast time reduction.
**IDs of affected creatures, items, quests or spells with a link to the relevant page:**

Spell: https://database.turtle-wow.org/?spell=25298

**Expected behavior. Describe how it should work:**
Improved Starfire should always remove 0.5 sec cast time from Starfire. It seems RNG whenever it works or not.

**Comment by DraxerTABC** [comment]
No idea how to replicate it yet, but it just happens.

**Comment by jameyboor** [comment]
How do you know it does not work?
