### ISSUE TITLE
Seal of Righteousness proc bug and Judgement of the wisdom/light proc cap.

### ISSUE THREAD

**Issue by luminieraa** [slowtorta/turtlewow-bug-tracker#2394]
**Please, provide a clear description what the bug is:**
![image](https://user-images.githubusercontent.com/78947022/199948050-f28e84e4-ba2e-4e9b-9cd1-a6d377539321.png)
![image](https://user-images.githubusercontent.com/78947022/199948812-48eb134d-e071-4647-9fb0-702a522ade75.png)
https://media.discordapp.net/attachments/810850211571171328/1038028721388523570/image.png

**Steps to reproduce the behavior with as much detail as possible:**
as in my case, tested with blazefury medallion, which gives 2 fire hit per strike.
1.equip blazefury medallion
2.press seal of wisdom
3. put judgement of the wisdom in the target, in this case was tested by dummy.
4. put on seal of righteousness
5. hit the dummy with a normal attack.
6. you can see that your normal attack is lacking 1 more hit, in this case the fire damage from the blazefury.
7. if you proc the judgement of the wisdom, you are currently capped in 1 proc.
[Items]
](https://database.turtle-wow.org/?item=17111)
https://database.turtle-wow.org/?item=22194

Spell: https://database.turtle-wow.org/?spell=
https://database.turtle-wow.org/?spell=20355
https://database.turtle-wow.org/?spell=25757
https://database.turtle-wow.org/?spell=25713

**Expected behavior. Describe how it should work:**

1.equip blazefury medallion
2.press seal of wisdom
3. put judgement of the wisdom in the target, in this case was tested by dummy.
4. put on seal of righteousness
5. hit the dummy with a normal attack.
6. with blazefury medallion, you should be hitting 4 times in 1 normal auto attack, 1 from normal attack,1 from Seal of righteousness,2  hits of fire damage from blazefury medallion(proc by Seal of righteousness)
7. after hitting with 4 hits in 1 normal auto attack, you should be proccing Judgement of the wisdom and its not capped to 1 proc(minimum of 0 to maximum 4 proc)

**Comment by ratkosrb** [comment]
This is not a bug. Previously all auras were wrongly allowed to proc from procs. We finally implemented a check for the spell attribute which controls this. Only a few auras like Vengeance have it. Seals do not have it.

Here is a link from Wowhead, since the Turtle db does not list attributes.
Wisdom - https://www.wowhead.com/classic/spell=20355/judgement-of-wisdom
Vengeance - https://www.wowhead.com/classic/spell=20059/vengeance

You can see the judgement does not have this attribute, but the Vengeance talent does.

Here is a full list of spells which are allowed to proc from procs:
```
Aftermath
Ascendance
Blackout
Counterattack
Divine Favor
Elemental Focus
Elemental Strength
Engulfing Shadows
Grounding Totem Effect
Healing Way
Illumination
Jom Gabbar
Lifebinding
Magic Absorption
Parry
Persistent Shield
Setup
Shadow Weaving
Spell Blasting
Stormstrike
Sun's Embrace
The Eye of the Dead
Unstable Power
Vampiric Embrace
Vengeance
Viscidus Frost Weakness
```
