### ISSUE TITLE
Items in bags stuck in unusable state after automatic sorting

### ISSUE THREAD

**Issue by refaim** [slowtorta/turtlewow-bug-tracker#2395]
**Please, provide a clear description what the bug is:**

Some items in bags stuck in unusable "greyed out" state after sorting bags with SortBags addon. I can't interact with such items until logout/login. Interface reloading does not help. Sometimes I get disconnected from server after logging out.

**Steps to reproduce the behavior with as much detail as possible:**

1. Install https://github.com/shirsig/SortBags-vanilla
2. Add 20-30 items to random bag slots
3. Execute "/run SortBags()" command

**IDs of affected creatures, items, quests or spells with a link to the relevant page:**

Not applicable.

**Expected behavior. Describe how it should work:**

Items in bags stay in usable/interactable state after automatic sorting with SortBags addon.

Also please see https://github.com/shagu/pfUI/issues/272, https://github.com/shirsig/Cleanup/issues/1 and https://github.com/LightsHope/issues/issues/150.

**Comment by jameyboor** [comment]
Server side filtering blocks some of the swap commands this addon sends in a short amount of time. As said in the other issues you could increase the delay so the server allows this. This will not be modified.

**Comment by refaim** [comment]
Increasing the delay to 1.2s seems to work.

**Comment by refaim** [comment]
https://github.com/refaim/SortBags-turtle fixed version.

**Comment by slowtorta** [comment]
I'm glad it's sorted, thank you :)
