### ISSUE TITLE
Pedistal in front of Uldum is spawned in the ground

### ISSUE THREAD

**Issue by Kharkov72** [slowtorta/turtlewow-bug-tracker#2397]
![Untitled](https://user-images.githubusercontent.com/25846834/200104292-a3d012ea-008f-49b3-8293-30c461036a80.png)

You are meant to interact with this for the quest
Seeing What Happens (https://database.turtle-wow.org/?quest=2946)
from which you get The Stone Watcher (https://database.turtle-wow.org/?quest=2954)

But it's spawned in the floor.
GM showed up and spawned it above ground and it worked as usual, so the quest functions other than it being spawned incorrectly.

**Comment by Tinyfin-github** [comment]
The pedastal will be temporary removed for bug fixing  other issues.
