### ISSUE TITLE
Didnt get Warchiefs Blessing

### ISSUE THREAD

**Issue by AnionLP** [slowtorta/turtlewow-bug-tracker#2399]
I didnt get the Warchiefs Blessing even though I handed in the quest "For The Horde"

Player Name: Ghilian
Faction: Horde

NPC: https://database.turtle-wow.org/?npc=4949
Quest: https://database.turtle-wow.org/?quest=4974
Spell: https://database.turtle-wow.org/?spell=16609

Please give me the Buff, because I need it in my next Molten Core Raid.

**Comment by slowtorta** [comment]
Hello! This is a GM issue, please submit a ticket in-game :)
