### ISSUE TITLE
Inconspicuous Documents  despawn after being loot by one person.

### ISSUE THREAD

**Issue by Tinyfin-github** [slowtorta/turtlewow-bug-tracker#240]
Inconspicuous Documents  despawn after being loot by one person.

**How it should work**:  For the quest Warlord's Command  you go to Blackrock Spire and loot Important Blackrock Documents from Inconspicuous Documents. It should be Lootable for everyone in the party that has the quest. For each run, the documents should be randomly placed at one of these four places:

At the feet of Overlord Wyrmthalak
In an empty corner next to War Master Voone
Near Highlord Omokk
Next to Urok's Tribute Pile

**What does not work:** After 1 person loots  Important Blackrock Documents from Inconspicuous Documents it despawns.

Warlord's Command  https://database.turtle-wow.org/?quest=4903
Important Blackrock Documents  https://database.turtle-wow.org/?item=12562#objective-of
Inconspicuous Documents https://database.turtle-wow.org/?object=175785

Source: https://classic.wowhead.com/item=12562/important-blackrock-documents#comments  Comments

**Comment by Tinyfin-github** [comment]
Issue  persists.

**Comment by redmagejoe** [comment]
As of time of writing this comment, the documents DO respawn after 5 seconds. However, they can spawn in 4 possible places, and they respawn in any of those places. The position should be determined at instance generation and the object should ONLY respawn at that location every time. The other positions are irrelevant after an instance has been started, therefore this is still bugged.
