### ISSUE TITLE
Lotherias Moonglow vest cannot complete

### ISSUE THREAD

**Issue by Phoenix8204** [slowtorta/turtlewow-bug-tracker#2400]
I cannot seem to hand in the quest for moonglow vest at Lotherias.

All items were were crafted.
Double checked if armor kits were applied - No.
Checked if it was soul bound - No.
Quest log shows completed (green tick).
Continue button Greyed out at NPC.

Tried clearing WDB Folder as advised, no change.

Please assist:

Char name: Lauranthalas
Account Phoenix8204

Thank you

**Comment by Tinyfin-github** [comment]
Please drop the quest and take it again. You won't lose the quest items and it will fix the issue.
Please don't post private information such as account name.
