### ISSUE TITLE
Durotar - Missing Mining Node

### ISSUE THREAD

**Issue by 8EightySixed6** [slowtorta/turtlewow-bug-tracker#2402]
**Please, provide a clear description what the bug is: Mining node shows on minimap but doesn't exist. This is in Durotar.

**Steps to reproduce the behavior with as much detail as possible:**

1. Goto coordinates 59 61
2. Mining node shows on map for copper but doesn't exist
3. 

**IDs of affected creatures, items, quests or spells with a link to the relevant page:**

NPC: https://database.turtle-wow.org/?npc=
Item: https://database.turtle-wow.org/?item=
Quest: https://database.turtle-wow.org/?quest=
Spell: https://database.turtle-wow.org/?spell=
Object: https://database.turtle-wow.org/?object=

**Expected behavior. Describe how it should work:**

**Comment by slowtorta** [comment]
Please report such issues via in-game ticket, GMs can fix them right away.

**Comment by usedcars4cheap** [comment]
This mining node has been moved to an interactable area on the torchlit path
