### ISSUE TITLE
Durotar Mining Node

### ISSUE THREAD

**Issue by 8EightySixed6** [slowtorta/turtlewow-bug-tracker#2404]
**Please, provide a clear description what the bug is:**

Unable to mine a mining node in Durotar. Shows on the minimap but unable to see/mine.

**Steps to reproduce the behavior with as much detail as possible:**

 1. Goto Durotar coordinates 47 20
2.  There is a rock formation that is supposed to have this mining node. 
![Screenshot 2022-11-06 232549](https://user-images.githubusercontent.com/115322320/200226527-a5459d37-c23a-4c0a-90d4-a781ba8e7416.jpg)

**IDs of affected creatures, items, quests or spells with a link to the relevant page:**

NPC: https://database.turtle-wow.org/?npc=
Item: https://database.turtle-wow.org/?item=
Quest: https://database.turtle-wow.org/?quest=
Spell: https://database.turtle-wow.org/?spell=
Object: https://database.turtle-wow.org/?object=

**Expected behavior. Describe how it should work:**

**Comment by cyaohiri** [comment]
See #2402.

**Comment by slowtorta** [comment]
Please report such issues via in-game ticket, GMs can fix them right away.

**Comment by usedcars4cheap** [comment]
This node has been moved to an interactable area outside of the rock formation
