### ISSUE TITLE
Charge

### ISSUE THREAD

**Issue by Otari98** [slowtorta/turtlewow-bug-tracker#2407]
Warriors charge doesnt work properly, it doesnt put you in combat when you use it, only when you reach the target and hit it or target hits you, so **YOU LOSE RAGE WHILE CHARGING** because you are technically **out of combat**.

**Steps to reproduce:**

1. Charge
2. Watch your rage
3. Cry Q _ Q

Spell: https://classicdb.ch/?spell=11578

**Expected behavior:**
Charge should put you in combat when you hit the button, so you get 15 or whatever rage as it says in tooltip, not sometimes 13, sometimes 15. Thanks for coming to my TED talk.

**Comment by ratkosrb** [comment]
It doesn't put you in combat automatically in classic either. I don't think this is a bug.
