### ISSUE TITLE
Rogue's talents shows the wrong value

### ISSUE THREAD

**Issue by Maykaien** [slowtorta/turtlewow-bug-tracker#2408]
Inspecting the Rogue's talents shows the wrong value
![Безымянный](https://user-images.githubusercontent.com/117762535/200629978-b3230621-f4e7-4514-b329-3ce2e7b481cc.png)

**Comment by slowtorta** [comment]
Something is wrong with your client or addons that you're using. Please download a fresh client fro our website to ensure that you have all the custom MPQ required for a comfortable play!

![image](https://user-images.githubusercontent.com/66763404/200973037-63c6372e-76b4-4b20-bd0a-15069cbb3992.png)
