### ISSUE TITLE
[Paladin] Greater Blessing and Blessing of Sanctuary on one target from two different paladins should stack

### ISSUE THREAD

**Issue by Velite12** [slowtorta/turtlewow-bug-tracker#241]
![image](https://user-images.githubusercontent.com/45871932/128936272-9aab9c98-5c75-41f1-932e-c0267cc4bc9f.png)
https://wowwiki-archive.fandom.com/wiki/Patch_3.0.3

![image](https://user-images.githubusercontent.com/45871932/128936370-050ba904-b651-491d-aa19-36b8eb454f99.png)
https://youtu.be/ChGg2ZNIDDQ?t=2360

Currently, if a target has blessing of sanctuary from one paladin, and another paladin uses Greater Blessing of Sanctuary on them, the regular blessing is overwritten, when they should be able to stack, like they do on classic and before Wrath of the lich king.

**Comment by geojak** [comment]
Is it not like a big they have om classic and its fixed in vmangos?
