### ISSUE TITLE
NPC: Gold-Tooth Gary

### ISSUE THREAD

**Issue by cyaohiri** [slowtorta/turtlewow-bug-tracker#2417]
When [Gold-Tooth Gary](https://database.turtle-wow.org/?npc=60450) rolls a die, it says "rolls a dice" instead of "rolls a die".
It's probably also the case with other gambling NPCs.

**Comment by slowtorta** [comment]
`rolls a dice` is a correct phrasing.

**Comment by cyaohiri** [comment]
Plural of "die" is "dice", at least to my understanding.

**Comment by cyaohiri** [comment]
Yeah, if they're actually rolling multiple dice, but I always imagine it to be a single 100-sided die.
