### ISSUE TITLE
Spell: Tiger's Fury's duration is being increased by Brutal Impact

### ISSUE THREAD

**Issue by cyaohiri** [slowtorta/turtlewow-bug-tracker#2418]
[Tiger's Fury](https://database.turtle-wow.org/?spell=5217), when improved with 2/2 [Blood Frenzy](https://database.turtle-wow.org/?spell=16952), lasts for 13 seconds instead of 12, thus lasting a second longer than Blood Frenzy.

**Comment by Zeyla-TW** [comment]
My testing shows Tiger's Fury lasting only 12 seconds with 2/2 Blood Frenzy. Cannot reproduce.

**Comment by cyaohiri** [comment]
Could you check it again? When using Tiger's Fury, the buff would start at 12 seconds, which means it lasts for 13 seconds. It would expire a second after Blood Frenzy expired. Blood Frenzy buff starts at 11 seconds, as it should, as it lasts for 12 seconds.

**Comment by Zeyla-TW** [comment]
I see, Brutal Impact is currently also increasing the duration of tiger's fury.

**Comment by Muigin** [comment]
This issue is no longer relevant to current version.

Fixed.
