### ISSUE TITLE
Spell: Blood Frenzy

### ISSUE THREAD

**Issue by cyaohiri** [slowtorta/turtlewow-bug-tracker#2420]
[Blood Frenzy](https://database.turtle-wow.org/?spell=16954) lasts for 12 seconds when using [Enrage](https://database.turtle-wow.org/?spell=5229), instead of matching Enrage's 10 second duration.

**Comment by Zeyla-TW** [comment]
The 12 second duration for Blood Frenzy's attack speed matches what is indicated in the talent tooltip. Working as intended.
