### ISSUE TITLE
[BWL] Growing Flames spell should follow normal resistance rules

### ISSUE THREAD

**Issue by Velite12** [slowtorta/turtlewow-bug-tracker#243]
Spell : https://database.turtle-wow.org/?spell=22442

https://www.youtube.com/watch?v=wqmpEHTstQA

https://classic.warcraftlogs.com/reports/RA4MadH8f6YWwj9V#fight=10&type=damage-taken&source=51&ability=22442

Ticks from growing flames should follow normal resistance rules, they currently do not.

**Comment by CosminPOP** [comment]
Fixed on next restart.
