### ISSUE TITLE
Item: Blade of Eternal Darkness has a false droprate for phase 5

### ISSUE THREAD

**Issue by Apimius** [slowtorta/turtlewow-bug-tracker#2430]
The Blade of Eternal Darkness has a too low drop rate for phase 5 vanilla.

Item: https://database.turtle-wow.org/?item=17780

The item should have a droprate around 2 % instead of the current 1 %.

**Comment by slowtorta** [comment]
Sorry, but this report lacks proof or a reason for this suggestion. It's even less in the Classic DB.

**Comment by Apimius** [comment]
The classic DB shows pre phase 5 (dungeon revamp patch) values. I am trying to find a phase 5 database but cant find one atm. I will come back to this when i get news.
