### ISSUE TITLE
Combo points disappearing when clicking off target

### ISSUE THREAD

**Issue by borg101** [slowtorta/turtlewow-bug-tracker#2431]
**Please, provide a clear description what the bug is:**
As a feral druid, using any ability that puts combo points on a target, losing target by any means...even pressing escape...removes all combo points from target.
**Steps to reproduce the behavior with as much detail as possible:**

1. Use any ability to put combo points on target
2. Unacquire target by any means, tab target (not hitting another target), clicking on "white space", pressing escape, etc 
3. Reacquiring target shows all combo points are gone.

**IDs of affected creatures, items, quests or spells with a link to the relevant page:**
All targetes

NPC: https://database.turtle-wow.org/?npc=
Item: https://database.turtle-wow.org/?item=
Quest: https://database.turtle-wow.org/?quest=
Spell: https://database.turtle-wow.org/?spell=
Object: https://database.turtle-wow.org/?object=

**Expected behavior. Describe how it should work:**
Clicking off target should not remove combo points.  If pressing escape, then clicking on the target again, all previous combo points should still be present.

**Comment by Sringaram** [comment]
That is sadly intended behavior but I hope it eventually gets changed to the TBC version which makes much more sense.

**Comment by slowtorta** [comment]
Intended. It's possible that we might change it in the future, but right now it's not considered.

**Comment by cyaohiri** [comment]
To clarify what OP said, combo points are being lost when dropping the target, not just when changing it. I can't reproduce this though.
