### ISSUE TITLE
"Quit" Fail Race agains time 

### ISSUE THREAD

**Issue by AKryukov92** [slowtorta/turtlewow-bug-tracker#2434]
**Please, provide a clear description what the bug is:**
Sometimes you fail race event with message like "You quit the race" while you are on a track.

**Steps to reproduce the behavior with as much detail as possible:**
1. Start a race
2. Get bad luck
3. Fail race
Seriously, I can't reproduce it 100%. It happen from time to time.

**IDs of affected creatures, items, quests or spells with a link to the relevant page:**

Quest: https://database.turtle-wow.org/?quest=50316

**Expected behavior. Describe how it should work:**
Player should fail race if he is too far from track or cheating and cut corners of the track.

**Comment by slowtorta** [comment]
You should not skip the purple marks, it's working as intended :)
