### ISSUE TITLE
Spells: Blood Fury and Rockbiter Weapon (Rank 1) do not stack

### ISSUE THREAD

**Issue by BovenDien** [slowtorta/turtlewow-bug-tracker#2436]
**Please, provide a clear description what the bug is:**

Using Blood Fury while no weapon is equipped or while having a weapon equipped (without it being imbued with Rockbiter Weapon) shows an increased Attack Power while if a weapon is imbued with Rockbiter Weapon it seems Blood Fury does not add any Attack Power.

**Steps to reproduce the behavior with as much detail as possible:**

1. Equip a weapon and use Rockbiter Weapon, check how much Attack Power it shows
2. Use Blood Fury, it does not add any Attack Power
3. Unequip the weapon, then it does show Attack Power is added due to Blood Fury
4. Equip the weapon again that is imbued with Rockbiter Weapon, it shows the same as before

**IDs of affected creatures, items, quests or spells with a link to the relevant page:**

Spell: https://database.turtle-wow.org/?spell=20572
Spell: https://database.turtle-wow.org/?spell=8017

**Expected behavior. Describe how it should work:**

I believe Blood Fury should always increase Attack Power, even if the weapon is imbued with Rockbiter Weapon.

![NoWeap](https://user-images.githubusercontent.com/97112576/200921751-09147420-0038-4e42-9953-1a3d04f92846.png)
![BF+NoWeap](https://user-images.githubusercontent.com/97112576/200921817-33b1524b-9004-46ef-9ddb-510f98e96669.png)
![RockbiterAP](https://user-images.githubusercontent.com/97112576/200921843-7d259f03-4c36-4c36-8677-9c0a9a2f963b.png)
![RB+Weap](https://user-images.githubusercontent.com/97112576/200921867-968d6806-91a2-4355-a6cf-8c6233936959.png)
![BF+RB+Weap](https://user-images.githubusercontent.com/97112576/200921897-428baa5e-138c-4fdd-9e14-9ecd3d11ec6e.png)

**Comment by Zeyla-TW** [comment]
This does indeed seem to be the case for Rockbiter Weapon Rank 1, but you'll be pleased to hear that every other rank of Rockbiter Weapon seems to be functioning and stacking with Blood Fury properly. This will likely be low priority since rank 2 can be learned as early as level 8, but we can eventually get around to looking into Rockbiter Weapon Rank 1's difference from the other ranks.

**Comment by Gurky-Turtle** [comment]
https://github.com/slowtorta/turtlewow-bug-tracker/issues/3809
