### ISSUE TITLE
Chromie in Tanaris not selling Chronoboons anymore / talking

### ISSUE THREAD

**Issue by DraxerTABC** [slowtorta/turtlewow-bug-tracker#2437]
**Please, provide a clear description what the bug is:**
Chromie after doing a quest line would let you buy Chronoboons at Tanaris instead of WPL.
**IDs of affected creatures, items, quests or spells with a link to the relevant page:**

NPC: https://database.turtle-wow.org/?npc=10667

**Expected behavior. Describe how it should work:**
She should be selling Chronoboons in Tanaris. This glitch makes playing Horde even crappier than it already is.

**Comment by Tinyfin-github** [comment]
This is not a bug.  The crystal was supposed to summon [Kheyna Spinpistol](https://database.turtle-wow.org/?npc=81041) not Chromie.

**Comment by DraxerTABC** [comment]
Except it still summons Chromie so not fixed even from that point.

**Comment by slowtorta** [comment]
The crystal will summon a different NPC depending on the quest you're on. "Return to Kheyna" will trigger Chromie spawn, it's part of the story: Chromie will appear instead of Kneyna to explain to you your wrong-doings.

**Comment by DraxerTABC** [comment]
Still not explained why she isn't selling the Chronoboon anymore tho ifi ts Chromie still.

**Comment by slowtorta** [comment]
It's a different instance of this creature. We don't want that players can hand in quests unrelated to this specific story. This crystal isn't supposed to summon her at all if you're no longer on the quest, this' is gonna be fixed as well soon.

**Comment by DraxerTABC** [comment]
So Horde players gonna have it more annoying yet again for Chronoboons then.

**Comment by slowtorta** [comment]
There's a Chromie inside the COT Hub, we could make her trade boons.

**Comment by DraxerTABC** [comment]
Could be good idea and good reason to do Black Morass once it get fixed
