### ISSUE TITLE
Pool spawn rate is significantly reduced

### ISSUE THREAD

**Issue by Kangaroux** [slowtorta/turtlewow-bug-tracker#244]
It seems that pools (fish, wreckage) are not respawning after 5 minutes.

In Ratchet you can usually find 3-4 pools at the docks and they respawn after 5 minutes. Now when I visit Ratchet I maybe see 1 pool, and it doesn't respawn after even 15 minutes.

Speaking with other players it seems that the slow respawn rate is not just a problem with Ratchet.

**Comment by Nolin7777** [comment]
Working as intended
