### ISSUE TITLE
Warlock Felguard has no mana regen

### ISSUE THREAD

**Issue by sieleyah** [slowtorta/turtlewow-bug-tracker#2440]
**Please, provide a clear description what the bug is:**
Hi, the custom warlock pet Felguard is missing a proper mana regen value, as currently his mana replenishes at a rate of 7-8 mana every 5seconds while not casting. It's as good as nothing considering his spells cost 600-1200 mana. Essentially renders him useless after about 20seconds of attacking. 

In comparison, other lvl 60 pets have 500~ mp5 while not casting, which allows them to regen a decent portion of their mana after 5seconds of being inactive due to oom. 
The Felguard has a higher mana pool with higher mana costs, hence his value is expected to be higher than the above (I'd expect around 800 mp5, realistically in order to allow using his specials at a reasonable rate)

**Steps to reproduce the behavior with as much detail as possible:**

Summon Felguard and set him to use at least his cleave ability. This will run him out of mana after about 5-6casts. (If you pop everything else, it's pretty much instant.)
Then you will see his mana never regens back. 5-10minutes later he might be able to cast again.

**IDs of affected creatures, items, quests or spells with a link to the relevant page:**

https://database.turtle-wow.org/?spell=45908

**Expected behavior. Describe how it should work:**

The Felguard should have mana regen comparable to those of other pets and sufficient to keep using his special abilities at a reasonable rate.

**Comment by ratkosrb** [comment]
He does more damage than other pets, and can even aoe, so his mana is intentionally a limited resource. The regen will be increased slightly, but not to the point you can spam his abilities.

**Comment by sieleyah** [comment]
Okay but please keep in mind pets don't regen mana while casting anyways. He will inevitably oom after 5-6 cleaves and then be inactive for 5seconds at the very least. Giving him a mana regen value of 600/5seconds is only enough to get out another cleave every 5sec afterwards and nothing else, so it would not be sufficient for spamming his stun/aoe etc unless you toggle off his cleave to save up mana. The values I suggested are not high enough to spam all his specials.
At the same time, he is a pet with high effort to maintain (costs 1gold to summon and breaks loose frequently + requires party to summon) so with all that in mind I think his utility above other pets is kind of justified. 90% of warlocks don't summon it at all because they cannot be bothered.
