### ISSUE TITLE
Warlock Felguard is unable to swim

### ISSUE THREAD

**Issue by sieleyah** [slowtorta/turtlewow-bug-tracker#2441]
**Please, provide a clear description what the bug is:**
Hi, the custom warlock pet Felguard is stuck on the edge of water whenever the warlock has to swim, he refuses to cross.
Other pets (regular and enslaved alike) have no such issue, you should be able to bring them into water or move across with them.

It's kind of silly that a flaming piece of rock (the Infernal) isn't afraid of water but this guy can't swim.

**Steps to reproduce the behavior with as much detail as possible:**
Find any water that's deep enough to swim (the river in ZG for example) and attempt to bring the Felguard into or across it. He will just keep staring at you from the shore and upon the enslave breaking, you will notice he is evade-bugged.

**IDs of affected creatures, items, quests or spells with a link to the relevant page:**
https://database.turtle-wow.org/?spell=45908

**Expected behavior. Describe how it should work:**
Felguard should be capable of moving into and across water with its owner.

**Comment by slowtorta** [comment]
Hopefully fixed on the next update. Please re-open if still bugged.
