### ISSUE TITLE
Proclaim Champion -- Champion's Grace unavailable ingame

### ISSUE THREAD

**Issue by astraeah** [slowtorta/turtlewow-bug-tracker#2448]
Issue: Champion's Grace (the 10% healing buff from the Holy Talent tree) seems to be missing from the game. Selecting the talent does not train it and it is unavailable on the trainers. 

**Steps to reproduce the behavior with as much detail as possible:**

1. Get a Priest to level 40
2. Take talent Proclaim Champion
3. Observe that Champion's Grace is not learned, and is unavailable via the Priest trainers

**IDs of affected creatures, items, quests or spells with a link to the relevant page:**

https://database.turtle-wow.org/?spell=47287 (this is the spell that's intended to train the buff I believe)
https://database.turtle-wow.org/?spell=45563 (this is the actual buff)

**Expected behavior. Describe how it should work:**
Should be available at level 40, via trainer or from selecting the talent.

Source: https://forum.turtle-wow.org/viewtopic.php?f=63&t=3334

**Comment by NoOneSurvives** [comment]
Hello, guys!
It's ability must be really helpfull for HC charactrers, 
There is also message in the forum: https://forum.turtle-wow.org/viewtopic.php?t=4324

**Comment by slowtorta** [comment]
@jameyboor

**Comment by VrogragFishslayer** [comment]
Hey Dev's pretty sure you just fixed this open bug, might want to close this ticket. Also, I had no idea they were waiting since last November for this fix. :scratches note down:
