### ISSUE TITLE
Enchant Bracer - Mana Regenerat - dont work

### ISSUE THREAD

**Issue by Rekinado** [slowtorta/turtlewow-bug-tracker#2449]
Enchant Bracer - Mana Regeneration (Permanently enchants bracers to restore 4.00 mana every 5.00 seconds.) dont work. 
This value does not show in "Mana regen" 

![obraz](https://user-images.githubusercontent.com/117974788/201292697-0ba13a30-fc24-4d6e-9925-029a10ad30ce.png)

**Comment by Rekinado** [comment]
When im Put IN wrist, it is ADD only 3 mana regen from spirit. Not from enchant

**Comment by geojak** [comment]
Most likely this is an addon problem

**Comment by slowtorta** [comment]
Working as intended, please try disabling your addons.

**Comment by loya16** [comment]
> 
Please, check it again, just saw this really not working:
1. Casted spell and checked mana difference before put on item with mp5 enchant (item didn't have any spirit or mp5)
2. Casted spell with item with enchant on it. No difference at all
