### ISSUE TITLE
Onyxia, Magmadar, and Nefarian should not drop Aggro on the tank when they are feared.

### ISSUE THREAD

**Issue by Velite12** [slowtorta/turtlewow-bug-tracker#245]
Currently, Magmadar and Onyxia will drop aggro on the main tank when he is hit by the fear. On classic and in 2006 vanilla this is not true, the tank will continue to be hit by the boss while feared.

https://youtu.be/z4M_XjnoRlA?t=603

https://youtu.be/ChGg2ZNIDDQ?t=1107

https://youtu.be/z_fBigd64Xk?t=172

https://youtu.be/5sfANJfZ4Co?t=152

Spells:

https://database.turtle-wow.org/?spell=19408 (magmadar)
https://database.turtle-wow.org/?spell=18431 (onyxia)
https://database.turtle-wow.org/?spell=22686 (nefarian)

**Comment by geojak** [comment]
You said in paladin discord, that in SoM this was changes to be like it is on turtle wow already. Therefor turtle behaviour is correct,

**Comment by Velite12** [comment]
> You said in paladin discord, that in SoM this was changes to be like it is on turtle wow already. Therefor turtle behaviour is correct,

I said that it was changed in SoM _to this pre 1.12 behavior to make it more difficult_. If you check Classic wow from 2019-2021 you will see that this is not the correct behavior if it was based on 1.12.

**Comment by geojak** [comment]
I disagree with you here. Som and blizzard classic should be aimed to be emulated as the most up to date version of blizzard and not some outdated 1.12.1.

Except for the faster leveling changes of SoM

**Comment by Zebouski** [comment]
I hear that this bevaior has returned ingame.

However it looks like this was a Classic bug that was actually fixed late into classic and also fixed on SoM 
2006 footage: https://youtu.be/iFB4Lj5y4ng?si=PHiFpdZXylwXB7SK&t=294
late classic with bug fixed: https://clips.twitch.tv/BusyBoldGnatPeteZarollTie

With this info, this ticket should never be reopened, not a bug
