### ISSUE TITLE
McWeaksauce potions has no sell price to vendor

### ISSUE THREAD

**Issue by AKryukov92** [slowtorta/turtlewow-bug-tracker#2450]
**Please, provide a clear description what the bug is:**
Some rewards of time trial can't be sold to vendor.

**Steps to reproduce the behavior with as much detail as possible:**

1. get https://database.turtle-wow.org/?item=51009
2. Open it

**IDs of affected creatures, items, quests or spells with a link to the relevant page:**

Item: box https://database.turtle-wow.org/?item=51009
Potions:
Mana https://database.turtle-wow.org/?item=23578
HP https://database.turtle-wow.org/?item=23579

**Expected behavior. Describe how it should work:**
I expect them to have vendor price at least like
HP https://database.turtle-wow.org/?item=13446
Major mana potion https://database.turtle-wow.org/?item=13444
since they restore same amount of health and mana.

**Comment by slowtorta** [comment]
Fixed on the next update. Reports closed without any comments are fixed reports as well, just for clarification.
