### ISSUE TITLE
los issues on boats and airships

### ISSUE THREAD

**Issue by Sephy1** [slowtorta/turtlewow-bug-tracker#2452]
On airships you basically have to be in backstab range to cast a spell on an enemy player.  This isn't a problem on boats but it's impossible to throw grenades for some reason.  Please fix.

**Comment by slowtorta** [comment]
For clarification: it's probably absolutely normal for the 2004 version of the game. Boats and ships are moving objects and normal spell mechanics that require reading coordinates, simply won't work there. Changing something this fundamental for a very rare edge case requires an insane amount of work time and is simply not worth it.
