### ISSUE TITLE
Cockroach Pets dont follow :(

### ISSUE THREAD

**Issue by Roachiez** [slowtorta/turtlewow-bug-tracker#2453]
**Please, provide a clear description what the bug is:**
Cockroach pet will not follow as of latest update
**Steps to reproduce the behavior with as much detail as possible:**

1. Summon Cockroach
2.  Walk away
3. Look at cockroach waaay over there /wave

**IDs of affected creatures, items, quests or spells with a link to the relevant page:**
Could be some other pets aswell
NPC: https://database.turtle-wow.org/?npc=
Item: https://database.turtle-wow.org/?item=
Quest: https://database.turtle-wow.org/?quest=
Spell: https://database.turtle-wow.org/?spell=
Object: https://database.turtle-wow.org/?object=

**Expected behavior. Describe how it should work:**

**Comment by slowtorta** [comment]
Fixed next update.
