### ISSUE TITLE
Bonespike shoulder procc on every hit

### ISSUE THREAD

**Issue by geojak** [slowtorta/turtlewow-bug-tracker#2455]
**Please, provide a clear description what the bug is:**

The bonespike shoulders from ubrs tooltip say it deals dmg on receiving a meele crit. 
What actually is happening is, that it deals dmg on every single hit you receive

This makes it the single best dmg and treat item when tanking multiple meele targets. 

This item from experience makes up for 15% of dealt dmg as a prot pala. 

**IDs of affected creatures, items, quests or spells with a link to the relevant page:**

https://database.turtle-wow.org/?item=12588

**Expected behavior. Describe how it should work:**

This item is supposed to be vendor trash and useless since only proccs on meele crits according to tooltip and blizzlike.

**Comment by jameyboor** [comment]
Fixed next update.
