### ISSUE TITLE
Airship LOS issues.

### ISSUE THREAD

**Issue by Sephy1** [slowtorta/turtlewow-bug-tracker#2457]
When casting single target spells on enemy players while on an airship you have to be in mele range for them to work.  
 This isn't an isssue on boats. I understand grenades and other aoe spells won't be fixed but surely single target spells shouldn't be an issue.

**Comment by slowtorta** [comment]
https://github.com/slowtorta/turtlewow-bug-tracker/issues/2650

**Comment by slowtorta** [comment]
https://github.com/slowtorta/turtlewow-bug-tracker/issues/2696
