### ISSUE TITLE
Bugged Fish School Darkshore 41.5, 23.6.

### ISSUE THREAD

**Issue by Hiethen** [slowtorta/turtlewow-bug-tracker#2458]
I'm unable to create a GM ticket in game, not using pfUI addon.

1. Fish school appears too close to land. making it very hard to cast into or near it. Located in Darkshore 41.5, 23.6.
![image](https://user-images.githubusercontent.com/32824778/201489415-405254c6-7f5d-45f3-bc03-8ffc777a4cf7.png)

**Expected behavior. Describe how it should work:**
Should be slightly further away from land.

**Comment by slowtorta** [comment]
@Tinyfin-github
