### ISSUE TITLE
Slow & Steady xp penalty is still applied in dungeons when it shouldn't.

### ISSUE THREAD

**Issue by Massie323** [slowtorta/turtlewow-bug-tracker#2462]
Reproduction:
- Make a party of 1 Slow & Steady member and 1 Warmode or normal member.
- Kill a dungeon mob.
- Notice the drastic difference in XP share:

Warmode:
![WoW_tweaked_QwJweOFajG](https://user-images.githubusercontent.com/57675820/201544457-9c5c479f-7aca-4ddb-873c-f64ec0b1602d.png)
Slow & Steady:
![WoW_tweaked_A4h9USHUXm](https://user-images.githubusercontent.com/57675820/201544463-4e33378c-100e-4d45-b69e-a97011f84477.png)

Website page for the gamemode states the penalty is supposed to be disabled inside dungeons:
![chrome_928h7Web0n](https://user-images.githubusercontent.com/57675820/201544508-f2886a2a-9760-4761-b105-b286e0d1c306.png)

**Comment by jameyboor** [comment]
Will be fixed on next update.
