### ISSUE TITLE
Warrior: Reflective Damage / Thorns reduced dmg in defensive stance by 10%

### ISSUE THREAD

**Issue by jlabranche** [slowtorta/turtlewow-bug-tracker#2465]
**Please, provide a clear description what the bug is:**

Thorns, 
Shield Spikes, 
Electromagnetic Gigaflux Reactivator, 
Crystal spire,

have reduced damage in defensive stance by 10%

**Steps to reproduce the behavior with as much detail as possible:**

Reduce Damage
1. Apply Thorns.
2. Go to Defensive Stance
3. Take Damage from a physical hit
![defensive_thorns](https://user-images.githubusercontent.com/7516736/201708111-b7493eaf-3735-4dc1-810b-b6f43db96834.png)

Normal Damage
1. Apply Thorns.
2. Go to Zerker Stance
3. Take Damage from a physical hit
![zerker_thorns](https://user-images.githubusercontent.com/7516736/201708134-efa1a29d-18a4-418f-9e22-3f80b9b9d7fb.png)

**IDs of affected creatures, items, quests or spells with a link to the relevant page:**
https://database.turtle-wow.org/?spell=11841
https://database.turtle-wow.org/?spell=9910

**Expected behavior. Describe how it should work:**

Thorn/reflective damage should be normal and not reduced while in defensive stance

**Comment by jameyboor** [comment]
Please show proof that this is not intended.
