### ISSUE TITLE
Shaman new `Thunderhead` talent not reducing mana cost as intended.

### ISSUE THREAD

**Issue by sailor4242** [slowtorta/turtlewow-bug-tracker#2466]
**Please, provide a clear description what the bug is:**
The `Thunderhead` talent description says that the mana cost should be reduced by 20%, however that is not true and it costs the same mana as spell description has, tested on rank 3 - 96 mana cost.
Also the `Improved lightning shield` talent does not seem to increase the damage of the orbs by 15% as it should. The damage number I see is the same as the spell description states.

**Comment by Zeyla-TW** [comment]
Tooltips are usually dynamically updated to reflect the mana cost and damage changes from talents. You are looking at the modified values. 
![image](https://user-images.githubusercontent.com/119783172/223561033-d36bb25b-4f4b-446d-8aa9-9cf7bf5dd49c.png)
Working as intended.
