### ISSUE TITLE
shadow mend spell is not scale off shadow damage gear. incorrect cast time

### ISSUE THREAD

**Issue by JaceEverwood** [slowtorta/turtlewow-bug-tracker#2467]
**Please, provide a clear description what the bug is:**
remember seeing some turtle forum post talking about it being 1.5 or 2 second cast( buy after I purchase the book and learn the spell it show it take 3 sec; which is completely useless in both pvp and pve. also a spell that require shadow form is not scaling off shadow gear.
**Steps to reproduce the behavior with as much detail as possible:**

1. 
2. 
3. 

**IDs of affected creatures, items, quests or spells with a link to the relevant page:**
![image](https://user-images.githubusercontent.com/19348079/201792700-7c0092b3-d018-442f-b488-97de73ecbce0.png)

NPC: https://database.turtle-wow.org/?npc=
Item: https://database.turtle-wow.org/?item=
Quest: https://database.turtle-wow.org/?quest=
Spell: https://database.turtle-wow.org/?spell=
Object: https://database.turtle-wow.org/?object=

**Expected behavior. Describe how it should work:**

**Comment by Zeyla-TW** [comment]
While shadow mend is indeed classified as a shadow school spell, the effect that it utilizes is flagged as a "Heal" in the game's spell system, and thus it is intended to only benefit from bonus healing effects. As for the debate over the 3 sec cast time, that is not a bug but a discussion best had in the suggestions forum. Working as intended.
