### ISSUE TITLE
Krom'Grul spawning underground

### ISSUE THREAD

**Issue by Kharkov72** [slowtorta/turtlewow-bug-tracker#2468]
1. Krom'Grul's picture wasn't showing when targeted
2.  When my voidwalker was sent to attack him he ran up to a random slope and stared at it
3.  Spells indicated it was close to that point

https://database.turtle-wow.org/?npc=8977

**Comment by slowtorta** [comment]
![image](https://user-images.githubusercontent.com/66763404/201877454-58ae523b-b0e6-4a77-9676-f5e49807bddb.png)

**Comment by Kharkov72** [comment]
no im owned im OWNED
