### ISSUE TITLE
 Revantusk Watcher's Chestplate icon is bugged

### ISSUE THREAD

**Issue by SierraNairn** [slowtorta/turtlewow-bug-tracker#247]
Revantusk Watcher's Chestplate icon is bugged

https://database.turtle-wow.org/?item=80607

It shows no icon. And if you switch slots with another item in your inventory it takes that items icon as it's own.

![WoW_nV0KEwqhT5](https://user-images.githubusercontent.com/83077166/129319318-a23841a9-ea43-46fb-b4cb-5592560b6cf3.png)

![WoW_COx4VW70MD](https://user-images.githubusercontent.com/83077166/129319317-48487ffb-9f0a-4d6f-9cd8-7dceff7bbb33.png)

![WoW_yClsh5FH1C](https://user-images.githubusercontent.com/83077166/129319315-ec0099ab-bf33-4184-9288-0890d774d610.png)

And if you sell it it gets a random icon

![image](https://user-images.githubusercontent.com/83077166/129319663-083d35a5-9175-4969-b0f7-6deb221db0bf.png)

**Comment by slowtorta** [comment]
This will be fixed in the client patch 1.15.2.
