### ISSUE TITLE
Brilliance aura have no effect on caster

### ISSUE THREAD

**Issue by Thormeard** [slowtorta/turtlewow-bug-tracker#2470]
**Please, provide a clear description what the bug is:**
Brilliance aura (arcane mage last talent) doesnt work on caster, but work on group members
I did ticket, GM wasn't been able to reproduce it, so I recorded it
(before recording I reset my talents, then logout, deleted wdb)
https://youtu.be/pWbpwLmIjv8

client version 1.16.3 (7030)

**Steps to reproduce the behavior with as much detail as possible:**

1. Cast brilliance aura, see that there is no difference with and without it

**IDs of affected creatures, items, quests or spells with a link to the relevant page:**

Spell: https://database.turtle-wow.org/?spell=45408 (not sure if this is correct one, there is like 4 of them)

**Expected behavior. Describe how it should work:**

Should give mana regen to caster (same as group members)

**Comment by slowtorta** [comment]
Duplicate for https://github.com/slowtorta/turtlewow-bug-tracker/issues
