### ISSUE TITLE
gnomish mind control cap failure rate seems really high

### ISSUE THREAD

**Issue by Sephy1** [slowtorta/turtlewow-bug-tracker#2471]
I've been experimenting with this item in ab for a few days now and it seems to fail really often, like 35% of the time.  Seems a bit high for an item with a 30 minute CD.  Was it really this bad in vanilla?  I also can't seem to get characters under mc to attack other players, they just stand still and don't engage.

**Comment by jameyboor** [comment]
Working as intended.
