### ISSUE TITLE
PVP flagging mobs via enslave (possibly mind control/tame pet)

### ISSUE THREAD

**Issue by sieleyah** [slowtorta/turtlewow-bug-tracker#2472]
**Please, provide a clear description what the bug is:**
Hi, I have noticed earlier that certain mobs in the world are FFA PVP flagged for no apparent reason and I believe I have found the reason for this. This is a problem because people hitting these mobs become pvp flagged and possible to gank while they are questing/farming. At low levels, this puts a risk at hardcore players too, as it could be a method to bait them into flagging. (I have no reason to believe anyone is doing this on purpose right now, but you do get flagged time to time by hitting a mob that shouldn't flag you, which is a huge scare)

I have tested this via Enslave demon, but I have strong reasons to believe MC and taming can behave the same way as I have encountered sporadic mistakenly flagged humanoid/beast type mobs before.

**Steps to reproduce the behavior with as much detail as possible:**

1. Enslave any demon type of mob using Enslave Demon
2. Have this demon engage in PVP with a nearby flagged person of the opposite faction. This flags the demon after a single hit.
3. Release the demon from enslave and now he has the FFA PVP flag on its portrait. 
4. Run out of leash range and allow him to reset back to full health. Now you have a demon with PVP flag in the middle of a peaceful quest hub.

This is most common to happen in the elite demon hub Darkwhisper Gorge, where warlocks tend to run for their lives upon Enslave breaking rather than killing off the difficult enemies, so they leave behind PVP flagged demons all the time. You can usually see a number of those Hederine NPCs flagged. (ref to my earlier report: https://github.com/slowtorta/turtlewow-bug-tracker/issues/2328)
However there are sporadic flagged mobs scattered in the world as well, not specific to any quest hub.

**IDs of affected creatures, items, quests or spells with a link to the relevant page:**

https://database.turtle-wow.org/?spell=11726
https://database.turtle-wow.org/?spell=10912 (untested)
https://database.turtle-wow.org/?spell=1515 (untested)

**Expected behavior. Describe how it should work:**

Engaging in PVP combat with a controlled pet and then releasing the pet should not leave flagged mobs behind in the world. Mobs should lose any pvp flags upon reseting.

**Comment by ratkosrb** [comment]
Thanks for finding out what causes this.
