### ISSUE TITLE
Texture glitch on window change

### ISSUE THREAD

**Issue by yogo1212** [slowtorta/turtlewow-bug-tracker#2475]
**Please, provide a clear description what the bug is:**

After changing the window, textures are all wonky and/or missing.
Nothing says it like:
![turtle_glitch1](https://user-images.githubusercontent.com/5165324/202372574-0f65d9b4-7c8c-403d-b9d7-d6c3a900ce96.png)

When I get the glitch in the character screen and get the game to load, there is no glitch in the game (until i switch in/out again).
Interestingly, if I log out (instead of restarting), the character selection is still glitched.
It looks to me like texture memory was corrupted somehow. Or maybe an array of texture indices gets garbled. Probably the former. There's no other sign of memory corruption. The game plays normally - if you can see the cursor and know where everything is.

I should add that this error wasn't there half a year ago and there have been not only updates to the client but to wine as well.
It's entirely possible that this is a wine (7.19-1 + 7.20-1)/mesa (22.2.1-1 + 22.2.3-1) issue - but if anyone has this problem outside linux/mac, they can hopefully find this issue.

**Steps to reproduce the behavior with as much detail as possible:**

1. Start game
2. Switch to desktop from the login/character selection or from the game
3. Switch back to the client

**IDs of affected creatures, items, quests or spells with a link to the relevant page:**

n/a

**Expected behavior. Describe how it should work:**

Original textures :-)

**Comment by slowtorta** [comment]
Hello! This is a modern graphic card / old game compatibility issue. 

The same is described here: https://community.amd.com/t5/graphics/rx-580-graphical-flickering-and-stretched-textures-exclusive-to/td-p/400656

Try to play around with the game config using this guide: https://forum.nostalrius.org/viewtopic.php?t=1100
Try switching between the following graphic API as described here: https://www.mmo-champion.com/threads/687894-OpenGL-vs-DirectX

You can also try using DXVK to replace the DirectX 9 renderer with Vulkan. This should solve any graphical glitches. Download it from [here](https://github.com/doitsujin/dxvk/releases/tag/v1.10.3) and place the 32-bit dll files in the game folder.

**Comment by yogo1212** [comment]
@slowtorta that's a very cool idea with dxvk - thank you!
