### ISSUE TITLE
Prestor's Neck Not Giving Correct AP

### ISSUE THREAD

**Issue by borg101** [slowtorta/turtlewow-bug-tracker#2478]
**Please, provide a clear description what the bug is:**
I got Prestor's neck from Nefarian last night.  When equipping it,I lost .10% crit compared to Onyxia Tooth Pendant.  When checking my attack power, it was the exact same as my Ony neck.  
**Steps to reproduce the behavior with as much detail as possible:**

1. Equip Onyxia Tooth
2. Observe/take note of AP & Crit
3. Equip Prestor's
4. Observe/take note of AP & Crit

**IDs of affected creatures, items, quests or spells with a link to the relevant page:**

ONY NECK Item: https://database.turtle-wow.org/?item=18404

PRESTOR'S https://database.turtle-wow.org/?item=19377

**Expected behavior. Describe how it should work:**

According to my math, guildmates, and general vanilla guides online, Prestor's should be giving more AP.  Approximately 18 more.  I'm not sure about the Crit difference, but that's not the issue... Though I would appreciate that being double checked as well.

**Comment by Sringaram** [comment]
You should specify your class.

**Comment by SolarGuru** [comment]
I believe that @borg101 is feral druid (he was in #2431). Druids doesn't get AP from agility and get 0.9% crit chance for additional 18 agility from Prestor's neck.

**Comment by slowtorta** [comment]
Thanks for investigating :)

**Comment by burner1024** [comment]
druids get ap from agi only in cat form
