### ISSUE TITLE
Maybess Riverbreeze npc

### ISSUE THREAD

**Issue by sieleyah** [slowtorta/turtlewow-bug-tracker#2480]
**Please, provide a clear description what the bug is:**
This npc has been missing from the game for many days. I heard she was removed on purpose because of some bug fixing, but it feels like the staff just forgot about her. An "urgent bug fix" shouldn't take weeks, right?
She provides salves for felwood world buffs and consumes, it must be high priority to place her back in game. Not willing to rush anyone, but maybe an open report is a good reminder that we are expecting her back. 

**Steps to reproduce the behavior with as much detail as possible:**
NPC is not there.

**IDs of affected creatures, items, quests or spells with a link to the relevant page:**

https://database.turtle-wow.org/?npc=9529

**Expected behavior. Describe how it should work:**
NPC should be in game.

**Comment by Tinyfin-github** [comment]
Npc is not missing for weeks. It has been removed for  4 days. Weekly updates happen once per week. Please have patience , bugs get fixed as soon as possible.
