### ISSUE TITLE
Ironforge and Undercity Map Doesn't Show

### ISSUE THREAD

**Issue by Hiethen** [slowtorta/turtlewow-bug-tracker#2482]
When you click on cities in the in game map like Thunder Bluff, Ogrimmar, Darnassus, and Stormwind, I can access a map of the city.
This doesn't happen for Undercity and Ironforge.

**Steps to reproduce the behavior with as much detail as possible:**

1.  Open in game map, click on either Ironforge or Undercity and city map will will not appear.

**Expected behavior. Describe how it should work:**

The city map for Undercity and Ironforge should open up like it does for other cities.

**Comment by slowtorta** [comment]
Can you please confirm that it worked as you described in the original Vanilla client?

**Comment by Hiethen** [comment]
Tested with version 1.12.1 and it doesn't open the city map either, I guess that its like that.

**Comment by Haaxor1689** [comment]
It's a bug inside original vanilla client that they solved in later expansions. Sadly there seems to be no way of fixing it here.

**Comment by Haaxor1689** [comment]
@Hiethen goood news everybody, this will be fixed in the next patch :)
