### ISSUE TITLE
Improved Life Tap

### ISSUE THREAD

**Issue by Findagon88** [slowtorta/turtlewow-bug-tracker#2485]
Current behavior: The talent "Improved Life Tap" (spell ID see below) increases the Mana gained from Life Tap (which is correct) BUT also increases the Health cost of the Spell (which is incorrect)

Spell: https://database.turtle-wow.org/?spell=18183

Expected behavior: "Improved Life Tap" should increase the Mana gained without the increase cost of Health

**Comment by Findagon88** [comment]
Yeah, tested it more indepth today and yes, I correct what I wrote, it does indeed work.
BUT
1. It still says on the skill that it's a 1:1 conversion (meaning it's a tooltip error)
2. Everytime I relog, the amount of health/mana on the tooltip is different

**Comment by slowtorta** [comment]
It's normal in Vanilla that tooltips never represent the actual value.
