### ISSUE TITLE
Brilliance Aura broken mana regen

### ISSUE THREAD

**Issue by SolarGuru** [slowtorta/turtlewow-bug-tracker#2486]
**Please, provide a clear description what the bug is:**
Effect of custom Brilliance Aura of arcane mages (last talent in tree) is 5 times less than stated in tooltip (15% of mage's mana regen). 
This makes specialized deep-tree utility talent almost useless and unbalanced: arcane mages are the WORST at damage due to bad +spd and +crit scaling and their utility broken.

**Steps to reproduce the behavior with as much detail as possible:**

1. Get usual mage and calculate his mana/tic regen (mana per 2 secs) by formula: 
Spirit/4+12.5 + mp5 from items (convert [mp5 / 5 * 2] to tics). 
It's 48.75 on my 145 spirit mage with 0 bonus mp5.

2. Calculate Brilliance Aura stated effect: mana/tic * 0.15. 
It's ~7.3 for my mage.

3. Activate Brilliance Aura and look at the difference in mana regen on party members. You will see the difference in ~1-2 mana/tic (depends on rounded numbers of different party members) and not expected ~7.3 mana/tic.

**IDs of affected creatures, items, quests or spells with a link to the relevant page:**

There is no Brilliance Aura in database.

**Expected behavior. Describe how it should work:**

1. Brilliance Aura expected to give 15% of mage's mana regen, not 3%. I believe the problem is in mixed up concepts like MP5 (mana per 5 secs), mana/tic (mana per 2 secs) and mana/sec (mana per sec) in code.
2. It's also should affect mage himself due to it is the AURA (like paladin or hunter ones). There is even a visual effect on mage, but no aura bonus!
3. And... this visual effect looks weird on mounted riders. It is located on hips of rider, but not on ground under mount. Looks bad, pls fix it or remove visual at all.

**Comment by SolarGuru** [comment]
Brilliance Aura in talent tree:
![ba](https://user-images.githubusercontent.com/56233770/203047009-6e981558-7af2-4b47-a51b-8c3e0711e566.png)

Visual effect on mounted players:
![image](https://user-images.githubusercontent.com/56233770/203047561-2be0732d-952b-42cb-9d56-533e98893796.png)

**Comment by SolarGuru** [comment]
Video proof of how many mata/tic Brilliance Aura gives:
https://user-images.githubusercontent.com/56233770/203053117-7cdd6f37-5471-438f-a088-e5bb7496cdb0.mp4

**Comment by slowtorta** [comment]
Please, let's make it higher priority, since it's a new custom spell @jameyboor  @ratkosrb
