### ISSUE TITLE
[Priest] [Talent] Spirit Tap does not consistantly activate while grouped.

### ISSUE THREAD

**Issue by Rhythmfish** [slowtorta/turtlewow-bug-tracker#2487]
**Please, provide a clear description what the bug is:**  

###Expected behavior:   
Spirit Tap grants a buff that increases spirit for a brief period after killing or contributed to killing something that yields experience or honor.  

###Actual behavior:  
Spirit Tap is inconsistently applied while grouped.   
Anecdotally, from a DPS perspective - it seems to only activate when the priest gets the killing blow. 

**Steps to reproduce the behavior with as much detail as possible:**

1. Talent 5/5 Spirit Tap.
2. Group up.
3. Kill mobs that yield experience.
4. Observe erratic Spirit Tap behavior.  

**IDs of affected creatures, items, quests or spells with a link to the relevant page:**

Spell: https://database.turtle-wow.org/?spell=15338

**Comment by cyaohiri** [comment]
Looking at the comment [here](https://www.wowhead.com/classic/spell=15338/spirit-tap#comments), it seems like you do in fact need to get the killing blow. [Remorseless Attacks](https://www.wowhead.com/classic/spell=14148) talent works the same way.

**Comment by Rhythmfish** [comment]
Good find. 
Closed as intended behavior.
