### ISSUE TITLE
The Honor of the quest "For Great Honor" didnt get saved

### ISSUE THREAD

**Issue by AnionLP** [slowtorta/turtlewow-bug-tracker#2488]
Before the server reset my game said that I was at around 420k honor. Now it says that I was at 403k. Shortly before reset I completed the quest "For Great Honor" 6 times and it seems they and my last alterac valley didnt get counted.

Player: Ghilian
Quests: https://database.turtle-wow.org/?quest=8367 (1x)
Quest:  https://database.turtle-wow.org/?quest=8367 (5x)

**Comment by D4nSch** [comment]
Did you turn in the quests after midnight? Because it seems like any honor after midnight till server resets already counts to the new day!
