### ISSUE TITLE
Wrong Rank Points (RP) calculation/distribution on server reset

### ISSUE THREAD

**Issue by D4nSch** [slowtorta/turtlewow-bug-tracker#2489]
**Please, provide a clear description what the bug is:**

The ranking calculation during last server reset reset (Wednesday, 23.11) did not work as intended on Horde. Even though of stacking in BR1 (=BR14) by all 4 players the distributed Ranking Points (= RP) were far less then they should have been. Even without any stacking done by the players the gained RP should have been more.

https://docs.google.com/spreadsheets/d/1YQWd1U6q6L8aAKEY4F5u51s9GATigER-UOLWXsyNIMU/edit#gid=0 <<< current live data

Example with data:

> STACKED | EXPECTED
Name | RP Gain | Current RP | Current Rank
Damortys | 13000 | 58350 | R13 67%
Urtica | ~12990 | 52833 | R12 56%
Texazz | ~12980 | 43930 | R10 78%
Lailai | ~12970 | 39355 | R9 87%

> NORMAL (non-stack) | EXPECTED
Name | RP Gain | Current RP | Current Rank
Damortys | 13000 | 58350 | R13 67%
Urtica | 12750 | 52593 | R12 51%
Texazz | 12500 | 43450 | R10 69%
Lailai | 12250 | 38635 | R9 72%

Wrong calculation/distribution:
> **THIS HAPPENED**
Name | RP Gain | Current RP | Current Rank
Damortys | 13000 | 58350 | R13 67%
Urtica | 12392 | 52235 | R12 44%
Texazz | 12069 | 43019 | R10 60%
Lailai | 12007 | 38392 | R9 67%

**Standing 2, 3, 4 lost way too much of the expected stacked RP gain value:**
(even without stacking the RP loss would be way too much)

Standing 2 **-608 RP (-12% of Rank)**
Standing 3 **-931 RP (-18% of Rank)**
Standing 4 **-993 RP (-20% of Rank)**

Apparently it worked on Alliance for all BR1 players where each got close to 13000 RP (maximum of possible RP gain).

**Steps to reproduce the behavior with as much detail as possible:**

1. Get 4 characters with different current RP values
2. Get them all in BR1 and make them stack their honor (625.4k, 625.3k, 625.2k, 625.1k) 
3. Check their gained RPs (the value should be very close to 13000 but it actually isn't; keep in mind the decay of -20% of the current RPs) 

**Expected behavior. Describe how it should work:**

In a stacked bracket (honor of all within a range of 200-300) the distributed RPs for each player should be close to the maximum of the specific bracket, e.g.: BR1 = 13000. Even without stacking the expected RP should be 13000, 12750, 12500, 12250 RP for standing 1-4.

**Additional Information:**

All players of standing 2-4 swapped from Alliance to Horde, could there be a connection to the buggy calculation?

**Sources:**

https://vanilla-wow-archive.fandom.com/wiki/Honor_System <<< vanilla pvp system (twow got a fixed poolsize of 1200 though)
https://www.youtube.com/watch?v=GN41tbxJJCY <<< stacking; used since the beginning of PVP (worked on all privates + classic 2019)

**Comment by D4nSch** [comment]
If possible please create a honor information logfile (seems like it's disabled by default):
https://github.com/vmangos/core/blob/a1cf05688d8e4bf13e0b11fcdc5c150dc8776631/src/mangosd/mangosd.conf.dist.in#L542

**Comment by D4nSch** [comment]
### Happened again this week (23.11-30.11) - ranking points are off by a large margin:

**All players were stacked within a range of 150 honor (very good stacking)!**

Standing #1: 13000 RP (hardcoded value)
Standing #2: ~12250 RP
Standing #3: ~12150 RP
Standing #4: ~12000 RP

With this kind of RP distribution Rank 14 is only possible for Standing #1, which should not be the case!

**Comment by jameyboor** [comment]
This is not a bug.
