### ISSUE TITLE
Several of the Syndicate in the buildings on the lower level of Durnholde Keep act like they are behind walls

### ISSUE THREAD

**Issue by Nyteterror** [slowtorta/turtlewow-bug-tracker#249]
**Please, provide a clear description what the bug is:**

After entering the buildings, some of the Syndicate cannot be attacked either by spells or melee.  You must run to the other side of them.

**Steps to reproduce the behavior with as much detail as possible:**

1. On the bottom level of Durnehold Keep, enter the bulding(s) from the yard.
2. Try to attack those Syndicate on the far side of the room; nothing happens. 
3. Run around the Syndicate and you can now attack.

**IDs of affected creatures, items, quests or spells with a link to the relevant page:**

NPC: https://database.turtle-wow.org/?npc=
Item: https://database.turtle-wow.org/?item=
Quest: https://database.turtle-wow.org/?quest=
Spell: https://database.turtle-wow.org/?spell=
Object: https://database.turtle-wow.org/?object=

**Expected behavior. Describe how it should work:**

**Comment by Nolin7777** [comment]
Map LoS issue
