### ISSUE TITLE
Блок щитом

### ISSUE THREAD

**Issue by bap4yk** [slowtorta/turtlewow-bug-tracker#2490]
**Please, provide a clear description what the bug is:**
Добрый день. Заметил такую особенность. С 1-10 лвл не работает блок щитом. Когда в прот ветке берешь таланты, тогда блок щитом начинает работать. Прокачался специально с 1-7 лвл гриндом и не разу не увидел блок щитом, хотя стартовый щит не снимал. По показателям персонажа есть 5% блока щитом и парринга. Вот паринг срабатывает, увороты срабатывают. 
**Steps to reproduce the behavior with as much detail as possible:**

1.
2. 
3. 

**IDs of affected creatures, items, quests or spells with a link to the relevant page:**

NPC: https://database.turtle-wow.org/?npc=
Item: https://database.turtle-wow.org/?item=
Quest: https://database.turtle-wow.org/?quest=
Spell: https://database.turtle-wow.org/?spell=
Object: https://database.turtle-wow.org/?object=

**Expected behavior. Describe how it should work:**

**Comment by bap4yk** [comment]
Добрый день. Заметил такую особенность. С 1-10 лвл не работает блок щитом. Когда в прот ветке берешь таланты, тогда блок щитом начинает работать. Прокачался специально с 1-7 лвл гриндом и не разу не увидел блок щитом, хотя стартовый щит не снимал. По показателям персонажа есть 5% блока щитом и парринга. Вот паринг срабатывает, увороты срабатывают.

**Comment by SolarGuru** [comment]
Работает. Проверено только что воином 1 лвл.
![image](https://user-images.githubusercontent.com/56233770/203590062-afe5e05c-a11c-4ac9-9a5d-db71cfccd9e6.png)
