### ISSUE TITLE
Crusader Strike Bugs

### ISSUE THREAD

**Issue by AidanSI** [slowtorta/turtlewow-bug-tracker#2491]
**Please, provide a clear description what the bug is:**

Crusader Strike appears to have been broken in a few ways after the 2022.11.24 patch: 
1. The debuff brought by Crusader Strike, which increases holy damage taken, does not show up on the target anymore. It exists, but is invisible. 
2. Crusader Strike costs twice as much mana as what the tooltip suggests. Rank 1 is supposed to cost 25 yet uses 50 mana, rank 5 costs 90 but uses 180 mana, etc.

**Steps to reproduce the behavior with as much detail as possible:**

1. Monitor your current mana level before using Crusader Strike.
2. Read the mana cost on the tooltip.
3. Use crusader strike on a target: twice as much mana should be deducted.
4. The target does not have the 'Crusader Strike' debuff visible. 

**IDs of affected creatures, items, quests or spells with a link to the relevant page:**

Spell: https://database.turtle-wow.org/?spell=10337

**Expected behavior. Describe how it should work:**

1. The CS debuff should be visible on the target, including the number of CS debuff stacks present. 
2. Crusader Strike should probably use up as much mana as written on the tooltip.

**Comment by jbockmon** [comment]
Actually the bug goes a little deeper than not showing up. If you have active debuffs on the target like judgement of the crusader, then do a crusader strike, both disappear, but stay active on target.

**Comment by ratkosrb** [comment]
The debuff is not visible because the debuff was separated into a new spell id, and there has not been a new client patch yet to bring the updated Spell.dbc. It will be fixed in 1.16.4.
