### ISSUE TITLE
NPC: Vaelan

### ISSUE THREAD

**Issue by Sringaram** [slowtorta/turtlewow-bug-tracker#2494]
ID: https://database.turtle-wow.org/?npc=10296

This dragon has the same issue he had in vanilla/classic. He will only show you the quest dialogue option if you have an Unadorned Seal of Ascension in your bags (https://database.turtle-wow.org/?item=12219).
This happens even when you already completed the quest and brought him the forged seal, forcing you to farm a base seal just to turn in the quest.

**Comment by Muigin** [comment]
Working as intended.
