### ISSUE TITLE
Deadmines NPC teleporting

### ISSUE THREAD

**Issue by kribtex** [slowtorta/turtlewow-bug-tracker#2495]
Was farming Deadmines by myself at level 50, got to the part before the second goblin boss.
![image](https://user-images.githubusercontent.com/119063037/204012775-0ccc21b4-cd3d-4d9f-a75e-0dc7bd74a271.png)

Defias teleported somehow. Pulled a bunch of mobs from the next room.

**Comment by slowtorta** [comment]
I'm sorry but it's impossible to reproduce without steps to do so.
