### ISSUE TITLE
Learning heavy mageweave bandage is broken - Dr. Gregory Victor

### ISSUE THREAD

**Issue by Tschakalakaboum** [slowtorta/turtlewow-bug-tracker#2498]
**Please, provide a clear description what the bug is:**

After finishing the triage-quest in Hammerfall, i got first aid level 225/300.
I do some more mageweave-bandages till 240, but Dr. Gregory Victor doesnt talk to me.
I deleted my wtf, disabled all Addons, but i cant get any interaction with him.

**Steps to reproduce the behavior with as much detail as possible:**

1. finish quest "Triage" at first aid level 225
2. level first aid to 240
3. talk to Dr. Gregory Victor

**IDs of affected creatures, items, quests or spells with a link to the relevant page:**

NPC: https://database.turtle-wow.org/?npc=12920
Item: https://database.turtle-wow.org/?item=
Quest: https://database.turtle-wow.org/?quest=6622
Spell: https://database.turtle-wow.org/?spell=
Object: https://database.turtle-wow.org/?object=

**Expected behavior. Describe how it should work:**

**Comment by cyaohiri** [comment]
Looks like the NPC is stuck in an invalid state. Open a ticket and a GM should be able to fix it by resetting the NPC.

**Comment by SaxxonPike** [comment]
This just happened to me today. Doctor Gustaf VanHowzen is clickable, but no gossip comes up when you interact.

**Comment by JackoRackham** [comment]
Works when Level 40 and still 240



Von meinem/meiner Galaxy gesendet



-------- Ursprüngliche Nachricht --------
Von: Tony Konzel ***@***.***>
Datum: 20.12.22 11:54 (GMT+01:00)
An: slowtorta/turtlewow-bug-tracker ***@***.***>
Cc: Subscribed ***@***.***>
Betreff: Re: [slowtorta/turtlewow-bug-tracker] Learning heavy mageweave bandage is broken - Dr. Gregory Victor (Issue #2498)


This just happened to me today. Doctor Gustaf VanHowzen is clickable, but no gossip comes up when you interact.
