### ISSUE TITLE
Object: Transfer Documents II

### ISSUE THREAD

**Issue by cyaohiri** [slowtorta/turtlewow-bug-tracker#2502]
[Transfer Documents II](https://database.turtle-wow.org/?object=2010906) can be interacted with even without the quest. The same is probably true for [Transfer Documents I](https://database.turtle-wow.org/?object=2010905) and [Transfer Documents III](https://database.turtle-wow.org/?object=2010907), but I have not tested this.

**Comment by Gurky-Turtle** [comment]
This should be fixed in the next update.
