### ISSUE TITLE
Quest: Saving Sharpbeak

### ISSUE THREAD

**Issue by cyaohiri** [slowtorta/turtlewow-bug-tracker#2505]
When opening the cage for [Saving Sharpbeak](https://database.turtle-wow.org/?quest=2994), we get the credit for opening the cage, but Sharpbeak doesn't move. He's supposed to leave the cage, and a few second later, his parents come to pick him up. This event worked a few months ago.

**Comment by redmagejoe** [comment]
This event is now scripted properly on current version.

Fixed.
