### ISSUE TITLE
Spell: Strike of the Scorpok

### ISSUE THREAD

**Issue by cyaohiri** [slowtorta/turtlewow-bug-tracker#2511]
[Strike of the Scorpok](https://database.turtle-wow.org/?spell=10672) seems to disappear for no reason, although in this case it disappeared when leaving [Cat Form](https://database.turtle-wow.org/?spell=768). I've also seen it disappear while fighting mobs, without any shapeshifting. I have not seen this happen with other similar buffs, such as [Spirit of Boar](https://database.turtle-wow.org/?spell=10671), [Rage of Ages](https://database.turtle-wow.org/?spell=10670), etc.

https://user-images.githubusercontent.com/86041826/204160513-edf11505-d58b-4068-a77a-f805854f11e1.mp4

**Comment by cyaohiri** [comment]
No, this has nothing to do with shifting, as mentioned in the original post.

**Comment by balakethelock** [comment]
Yes, but do you have any addons or macros that try to remove buffs? VCB, Tank Buddy, Lazypig, anything?

**Comment by cyaohiri** [comment]
Not that I'm aware. I'll try to find a few more clips of this happening and will post them here.

**Comment by cyaohiri** [comment]
Going through other recordings I've realized I indeed had something that removed the buff whenever I would dismount. It's probably the auto dismount feature from ShaguTweaks. You were right!
