### ISSUE TITLE
Quest Log: abandoning a quest

### ISSUE THREAD

**Issue by cyaohiri** [slowtorta/turtlewow-bug-tracker#2515]
When abandoning a quest that has provided item(s) (item(s) given when accepting the quest), such as [Young Lovers](https://database.turtle-wow.org/?quest=106), the confirmation message doesn't say the provided item(s) will be destroyed.

Using this quest as an example, the confirmation message should say: "Abandon 'Young Lovers', destroying Maybell's Love Letter?"

**Comment by slowtorta** [comment]
Can' you please include video proof of the suggested behavior?

**Comment by cyaohiri** [comment]
Sure, the game version is 1.12.1.5875.

https://user-images.githubusercontent.com/86041826/204162398-70784a19-3547-4691-b2ca-d9b6623bc5a3.mp4

**Comment by slowtorta** [comment]
Thanks!

**Comment by slowtorta** [comment]
We will not fix it just yet while the other bug with turning on quests like Westfall Stew or Ledger in Tanaris is present. Apparently, it was disabled a long time ago in vmangos to allow players to drop and accept the quest without losing the progress.

**Comment by cyaohiri** [comment]
> We will not fix it just yet while the other bug with turning in quests like Westfall Stew or Ledger in Tanaris is present. Apparently, it was disabled a long time ago in vmangos to allow players to drop and accept the quest without losing the progress.

Could you clarify what you mean by "losing progress"? Only items you get when accepting the quest (called provided items) get removed when abandoning it, but those you've collected as a part of the quest don't get removed, e.g. the ingredients for Westfall Stew will stay in your inventory after abandoning the quest, as they haven't been provided.

The issue posted here is only regarding the message. The functionality is already correct.
