### ISSUE TITLE
Dungeon: Sunken Temple

### ISSUE THREAD

**Issue by cyaohiri** [slowtorta/turtlewow-bug-tracker#2518]
Video: https://gofile.io/d/GUQd5P
In the location seen in the video, a mob or a pack of mobs gets pulled from somewhere while engaging a different pack, probably from the balcony above, and start running towards us for about a minute, bringing more mobs with them. This happened twice in the video.

To explain further, the video starts with me out of combat, then I use Enrage, which starts combat as expected and I engage mobs with maggots in them. After all of them have been killed (0:36), I stay in combat, surprisingly. While still in combat, we engage another pack of mobs (1:10), and a few seconds later (1:17), more mobs show up from somewhere. These are probably the ones that got pulled along with the pack at the very beginning of the video, keeping me in combat the entire time. Once all these have been killed, I finally left combat (1:46).

After this, the next two single pulls at 1:58 and 2:13 go as expected, letting me leave combat as soon as the pulled mobs are dead.

Next pull was at 2:30, and after we killed all those mobs (2:47), I stayed in combat. About a minute later, a bunch of mobs showed up (3:45), and then another Deep Lurker showed up at 4:41. Once we've killed all these, I finally left combat.

The mobs in this video are those that are normally in the circular hallway on the floor just above us. My suspicion is that [Slime Maggots](https://database.turtle-wow.org/?npc=8311) have some special aggro rules, being that pulling them, even though they're not hostile, will pull nearby hostile mobs and other maggots. Perhaps those rules ignore line of sight, which then allows pulling other maggots on the balcony above, who then pull more mobs as they're moving towards us.

Although not captured in this video, the same thing can happen when engaging mobs (possibly Maggots) on the balcony, where the mobs from below will be pulled in a similar fashion.

**Comment by sieleyah** [comment]
I confirm this happens every time in ST. When you get to that part of the dungeon those packs aggro from somewhere and can very well wipe you if you don't anticipate it.

**Comment by ratkosrb** [comment]
https://github.com/slowtorta/turtle-wow/commit/e84f5f58284753c8a7541e5e2e5bc50d0ac2878c
