### ISSUE TITLE
Reputation: Booty Bay

### ISSUE THREAD

**Issue by PAKNADNE** [slowtorta/turtlewow-bug-tracker#2519]
Good afternoon.
Reputation after killing pirates does not improve with the bay.
![WoWScrnShot_112822_020151](https://user-images.githubusercontent.com/119265865/204164548-1e6555ee-3caf-481c-89aa-f9252dabacad.jpg)
![WoWScrnShot_112822_020123](https://user-images.githubusercontent.com/119265865/204164551-faf03f05-05a4-472e-b7bc-ceb93b931ec5.jpg)

**Comment by Gurky-Turtle** [comment]
It could be because you are at war with them. Click on the rep bar for them and untoggle at war.

**Comment by Gurky-Turtle** [comment]
@PAKNADNE please let me know.

**Comment by slowtorta** [comment]
This seems like the case.
