### ISSUE TITLE
Players can die in duels from a hunter fire trap

### ISSUE THREAD

**Issue by Kangaroux** [slowtorta/turtlewow-bug-tracker#252]
We did some testing to see if it's safe to duel hardcore chars.

As expected everything just gets the opponent down to 1hp and the duel ends, however if you place a hunter fire trap on the ground and a player runs into it, they can die while dueling.

While just a single example this might suggest that entities which are owned by a player, but not the player themselves, can kill in a duel.

**Comment by Nolin7777** [comment]
Thanks for the ticket. We implemented a safe solution.
