### ISSUE TITLE
Paladin's Holy Talent [Illumination] 5/5 does not refund mana cost of Holy Shock critical spell hit!

### ISSUE THREAD

**Issue by Zhohan** [slowtorta/turtlewow-bug-tracker#2522]
Critical spell hits with Holy Shock are not refunding mana, which is nerfing damage/healing output for Holy Paladins.

1. Cast [Divine Favor].
2. [Holy Shock] a target.
3. No mana refund, cry in corner.

Spells:
https://database.turtle-wow.org/?spell=20215
https://database.turtle-wow.org/?spell=20930

Illumination should refund mana cost from Holy Shock.

Light be with you.

**Comment by geojak** [comment]
It does refund if you use it to heal I think. But not if you use it offensively.

**Comment by geojak** [comment]
Tested and works when healing. Not supposed on dmg. Not a bug

**Comment by Zebouski** [comment]
![image](https://user-images.githubusercontent.com/11151284/206753722-8d09a5e6-fce1-4272-a68d-8f4b63e92f74.png)

confirmed. Illumination talent specifically says "Holy Shock heal spell".

it's up to the devs if they wanna deviate from blizzlike here

**Comment by jameyboor** [comment]
This is not a bug.
