### ISSUE TITLE
Priest's Mind Vision successful channeling but show at character instead of the target's location

### ISSUE THREAD

**Issue by khucngantieu** [slowtorta/turtlewow-bug-tracker#2523]
When using multiple Mind Vision spells, jumping from one mob to another very often the cast was successful but sometimes shows at  character's location instead of the target's location.  The spell shows as channeling.

**Steps to reproduce the behavior with as much detail as possible:**

1. Mind vision a target not at current location
2. Mind vision again bouncing from first mob to the next mob in different location
3. Make sure it's not the same location as the priest.

**IDs of affected creatures, items, quests or spells with a link to the relevant page:**

All NPCs

**Expected behavior. Describe how it should work:**

If the Mind Vision spell is successful and it shows channeling, then I should see the target's location and not my current (priest's) location.

**Comment by Muigin** [comment]
This issue is no longer relevant to the current version.
