### ISSUE TITLE
Drain life threat bug

### ISSUE THREAD

**Issue by balakethelock** [slowtorta/turtlewow-bug-tracker#2524]
**Please, provide a clear description what the bug is:**
Drain Life healing does threat. In vanilla wow it did not do that.
Sources:

https://worldofwarcraft.fandom.com/et/wiki/Drain#Life_Drains:~:text=Their%20damage%20causes%20normal%20threat%2C%20whereas%20their%20healing%20does%20not%20generate%20any%20threat%20at%20all.

https://www.reddit.com/r/classicwow/comments/egscd0/warlocks_common_misconceptions_bugs_and_open/

**Steps to reproduce the behavior with as much detail as possible:**

1.Use twow threat addon in a group to see threat
2. Lifetap to low health
3. Cast drain life, watch it do threat of healing on top of the damage threat
Another method:
1. send voidwalker on a mob then set it on passive to stop attacking
2. pull a second mob and drain the second mob
3. watch the first mob attack you because of the healing aggro

**IDs of affected creatures, items, quests or spells with a link to the relevant page:**

https://database.turtle-wow.org/?spell=689
https://database.turtle-wow.org/?spell=699
https://database.turtle-wow.org/?spell=709
https://database.turtle-wow.org/?spell=7651
https://database.turtle-wow.org/?spell=11699
https://database.turtle-wow.org/?spell=11700

**Expected behavior. Describe how it should work:**
Drain Life healing does not cause threat.

**Comment by sieleyah** [comment]
I confirm this is a problem, and i think it also affects Siphon life and Death coil (every drain health effect basically)

**Comment by jameyboor** [comment]
Fixed on next update.
