### ISSUE TITLE
500.5 Ranking points less than calculated.

### ISSUE THREAD

**Issue by Ghilian1** [slowtorta/turtlewow-bug-tracker#2525]
I calculated our entire Poolsize of 1200 with my standing of 8 and should have ended up with 36755, but after the reset i only ended up with 36254.5

**Comment by Ghilian1** [comment]
Player: Ghilian

**Comment by jameyboor** [comment]
Where did you get that poolsize from?

**Comment by jameyboor** [comment]
This is not a bug.
