### ISSUE TITLE
Paragons of Power are marked lv 60 required instead of 58

### ISSUE THREAD

**Issue by Zebouski** [slowtorta/turtlewow-bug-tracker#2529]
**Please, provide a clear description what the bug is:**
lv 58s are unable to turn in the tokens for the 3 pieces of the zg set, nor the quests to upgrade the neck for the 4th peiece

**IDs of affected creatures, items, quests or spells with a link to the relevant page:**
https://database.turtle-wow.org/?search=paragons
https://database.turtle-wow.org/?quest=8048

**Expected behavior. Describe how it should work:**
https://www.wowhead.com/classic/search?q=paragons
https://www.wowhead.com/classic/quest=8048/the-heros-brand

I personally made a 59 twink on classic in 2020 where me and others indeed got 4 out of 5 peices of the ZG set.
There are a few 59 twinks on turtle that would appreciate this bug being fixed.

**Comment by slowtorta** [comment]
Fixes on the next update.
