### ISSUE TITLE
Blackblade of Shahram's 50stats proc is just refeshing, not stacking x5

### ISSUE THREAD

**Issue by Zebouski** [slowtorta/turtlewow-bug-tracker#2532]
**Please, provide a clear description what the bug is:**
When Blackblade of Shahram's procs the 50stats proc, that works. But when 50stats gets procced again, the 50stats just refreshes 

**Steps to reproduce the behavior with as much detail as possible:**

1. proc the 50stats proc
2. proc the 50stats proc again while the old one is up, see it just refresh

**IDs of affected creatures, items, quests or spells with a link to the relevant page:**

Spell: https://database.turtle-wow.org/?spell=16602

**Expected behavior. Describe how it should work:**
On classic and 2006, this proc was able to stack x5 times

**Comment by geojak** [comment]
If this is changed, wount that be very broken with the new jotc mechanic. Imagine paladins stacking consistely to +250 stats.i mean, I am all for it, just food for thoughts.

**Comment by Nicorus49** [comment]
It would be a huge mistake to allow this to stack. 500ap, 17% crit, 2500hp. To the entire group and even more if there is an attack speed buff as well. Literally 2x more powerful than world buffs

**Comment by Zebouski** [comment]
This is how the weapon is meant to function blizzlike. SotC's effect can be tuned individually.

**Comment by geojak** [comment]
The new jotc is a nightmare to balance. How do you keep weapons not op for paladins but also not shit for warriors that have no 'force' proccing.

The weapon has a 1.2% drop chance. So their won't be many paladin gods walking around with it anyway

**Comment by ratkosrb** [comment]
We are keeping this as it is.

**Comment by Galpala** [comment]
The only proc for group is the haste, Fist of Shahram.

**Comment by Zebouski** [comment]
@Galpala the mp5 and hp5 proc is also for the group.

**Comment by twowTurtReynolds** [comment]
As Blackblade has been given a JotC nerf exception, we will be fixing the weapon to be blizzlike.

**Comment by ratkosrb** [comment]
If new buff slot is used for each caster, then there's no way there's a limit of 5 stacks like the issue says.

**Comment by twowTurtReynolds** [comment]
The only footage I could find of 2 will procs at once is: https://youtu.be/rakfLOlB-xc?t=25
![image](https://github.com/slowtorta/turtlewow-bug-tracker/assets/151180101/c6c29723-779b-40e0-b4a3-bdc8881254d0)
And we can see here they show up as two different buffs.

https://www.wowhead.com/classic/item=12592/blackblade-of-shahram#comments:id=5202 This person from 2006 says 5 stacks to 250. This must be the prevailing reason people say 5 stacks, that could easily be urban legend.
https://www.reddit.com/r/classicwow/comments/c21uup/blackblade_of_shahram/ random commenters in 2019 say 5
https://us.forums.blizzard.com/en/wow/t/buffs-of-the-blackbladeog-blizz-dev-shahram-shane-dabiris-nod-in-game/765336/3 This person also without proof says 6 stacks on TBC Classic

This is a hard one to get solid evidence for. Maybe there is no stack limit.

I hope this helps for investigations on how to treat this for the wide vmangos populace :)
