### ISSUE TITLE
Arcane Missiles: Spell Power scaling coefficient still the same

### ISSUE THREAD

**Issue by Thormeard** [slowtorta/turtlewow-bug-tracker#2533]
**Please, provide a clear description what the bug is:**
AM spellpower coef should be 0.286 but its still 0.24

**Steps to reproduce the behavior with as much detail as possible:**
1. Get some spellpower items
2. Do math and compare to actual values
3. Works for all the other ranks of Arcane missiles (not only last rank)

As you can see on screenshoot below, I have 278 spell power, my missle hit for 304
237 - base tick value
278*0.24  = 66,72 (additional damage from spellpower)
237 + 66,72 = 303.72 (~304 from screenshot)

With 0.286 it should be 237 + 278*0.286 = 316.508 (~317)

![изображение](https://user-images.githubusercontent.com/25845025/205462761-48bc4cac-da81-453a-ae5b-57aa6c835d7d.png)

**IDs of affected creatures, items, quests or spells with a link to the relevant page:**

Spell: https://database.turtle-wow.org/?spell=25345 (rank 8)
also all the lower ranks: 
https://database.turtle-wow.org/?spell=10212 (rank 7)
https://database.turtle-wow.org/?spell=10211 (rank 6)
https://database.turtle-wow.org/?spell=8417 (rank 5)
https://database.turtle-wow.org/?spell=8416 (rank 4)
https://database.turtle-wow.org/?spell=5145 (rank 3)

**Expected behavior. Describe how it should work:**
Сoeficient should be 0.286 as it was promised

Also you can see that I have only 4 ticks instead of 5...
Can we get at least spell power coefficient fixed, should be just copypaste the number in the code.

**Comment by SolarGuru** [comment]
Confirming the issue. Tested with +0 and +100 bonus Spell Damage gives only +24 bonus per missile.

Here's some screenshots on 60 lvl mage with no talents:
![image](https://user-images.githubusercontent.com/56233770/205493474-ffcebf82-9e6a-443e-be8b-fed62af4dfc5.png)
