### ISSUE TITLE
Spell Haste not stacking and possibly not working on items/enchants

### ISSUE THREAD

**Issue by Zeyla-TW** [slowtorta/turtlewow-bug-tracker#2534]
**Please, provide a clear description what the bug is:**

**Steps to reproduce the behavior with as much detail as possible:**

1. Open spell 13679 (Haste 1) in the spell editor and view effect 3's aura type 65: SPELL_AURA_MOD_CASTING_SPEED_NOT_STACK (equipping more than 1 source of this does not stack with one another, as indicated by the flag description, and also does not stack with certain mechanics like the aura of command from lieutenant general andorov in AQ20 which also uses the non-stacking spell haste aura type.
2. I believe the ranged and cast speed may both also not be working at all due to the base points and die sides being assigned in reverse of the convention (normally you'd assign a base point of 0 and a die side of 1 to get 1% from the effect, but they're reversed as base point 1 and die side 0, which I've seen cause issues in the past when I designed spells for a different server. This only seems to be an issue for spell 13679 which is the 1% haste on various items, but the base points and die sides are assigned normally on 13928 which is the 1% glove enchant.)
3. There may also be an issue with spell class mask assignments for the spells, but I can't confirm it as I wasn't able to see that data from what I could extract from the client files.

**IDs of affected creatures, items, quests or spells with a link to the relevant page:**

NPC: 
Item: https://database.turtle-wow.org/?item=60559 https://database.turtle-wow.org/?item=83217
Quest: 
Spell: https://database.turtle-wow.org/?spell=13679 https://database.turtle-wow.org/?spell=13928
Object: 

**Expected behavior. Describe how it should work:**
Change the aura type from 65: SPELL_AURA_MOD_CASTING_SPEED_NOT_STACK to 216: SPELL_AURA_HASTE_SPELLS. If that does not fix it, perhaps there is another aura type in the list which would be suitable. Also, hopefully that would reflect the adjusted cast speed on player's spell tooltips, if it works properly.

**Comment by ratkosrb** [comment]
I see no issue here. Both the attack speed and casting speed components work, and they are reflected on the tooltip of spells.
https://streamja.com/XWrQz

**Comment by sieleyah** [comment]
Generally speaking ,haste works.
Specifically the Minor Haste gloves enchant is broken. It does not provide spell haste, only melee and ranged. I have been lazy to open a report for that :<

**Comment by geojak** [comment]
The custom items with spell haste all work.

The aq20 buff with 11%, I think it doesn't work, worth checking out.

The vanilla glove leg and head enchant are all just attackspeed, also counterweight and do bit work on spells liek it was half a year ago once stated by I think Dragunovi that they would be also for spells changed.

**Comment by Zeyla-TW** [comment]
> 

Interesting, the tooltip wasn't updating for the mage I tested it on. Thanks for clearing that up.

**Comment by sieleyah** [comment]
> The custom items with spell haste all work.
> 
> The aq20 buff with 11%, I think it doesn't work, worth checking out.
> 
> The vanilla glove leg and head enchant are all just attackspeed, also counterweight and do not work on spells like it was half a year ago once stated by I think Dragunovi that they would be also changed for spells.

Well yes but in the turtle db already there is a spellhaste component to the glove enchant and the tooltip also says "attack AND casting speed" so one would expect it gives spell haste here. I understand if it's a custom change it takes time to apply but it can confuse people regardless.

**Comment by geojak** [comment]
Doesn't say and attackspeed on my enchanted gloves. Only for example on my whip of encouragement. I cleared wdb last weekend and Jsut a player like you, thought

**Comment by redmagejoe** [comment]
#1762

**Comment by slowtorta** [comment]
Fixed in the next update.
