### ISSUE TITLE
Judgment of the Crusader and Crusader Strike Debuff Not Showing Up nor Applying Bonus Damage

### ISSUE THREAD

**Issue by Learngoat** [slowtorta/turtlewow-bug-tracker#2537]
**Please, provide a clear description what the bug is:**
Applying Judgment of the Crusader does not show up as a debuff, and does not seem to boost the 28 base damage from Judgment of Righteousness up by any amount which means it's more than hidden, it does not apply at all. 

**Steps to reproduce the behavior with as much detail as possible:**

1. Apply Seal of the Crusader to Paladin
2. Press Judgment of the Crusader to put on enemy mob. It does not show up at all on UI.
3. To see if it's just UI, apply Judgment of Righteousness to see if holy damage is different before or after. But it still does exactly 28 damage both times. 

**IDs of affected creatures, items, quests or spells with a link to the relevant page:**

Spell: https://database.turtle-wow.org/?spell=21082

**Expected behavior. Describe how it should work:**
When applying the Judgment, it should show up as a debuff on the enemy, and then boost holy damage.

**Comment by ratkosrb** [comment]
The debuff from Judgement of the Crusader has been removed from the game, and instead the judgement triggers procs on your weapon now. You will be able to see the Crusader Strike debuff when the 1.16.4 patch is released.
