### ISSUE TITLE
Chain Lightning

### ISSUE THREAD

**Issue by DotShockCrusade** [slowtorta/turtlewow-bug-tracker#2539]
**Please, provide a clear description what the bug is:**
Shaman spell Chain Lightning sound file is erroneous. It has TBC sound file, sounding like Earth Shock and Lightning Bolt

**Expected behavior. Describe how it should work:**

It should have the thunder sound it had before 2.0.1 patch

**Comment by Zelestreo** [comment]
This would be great. 
These are the vanilla sounds:
https://www.wowhead.com/classic/sound=5635/chainheal
