### ISSUE TITLE
SP coefficients under level 20 are wrong for healing touch and rejuvenation again.

### ISSUE THREAD

**Issue by Lunkdunk** [slowtorta/turtlewow-bug-tracker#254]
**Please, provide a clear description what the bug is:**
SP coefficient for healing touch and rejuv are wrong under level 20 again. Same as #178 , double level penalty.
**Steps to reproduce the behavior with as much detail as possible:**

1.
2. 
3. 

**IDs of affected creatures, items, quests or spells with a link to the relevant page:**

NPC: https://database.turtle-wow.org/?npc=
Item: https://database.turtle-wow.org/?item=
Quest: https://database.turtle-wow.org/?quest=
Spell: https://database.turtle-wow.org/?spell=
Object: https://database.turtle-wow.org/?object=

**Expected behavior. Describe how it should work:**

**Comment by Nolin7777** [comment]
Possible fix will be applied on next maintenance.
Please re-open in case issue still exists.

**Comment by Lunkdunk** [comment]
SP cofficients are still wrong after the maintenance.

**Comment by Lunkdunk** [comment]
After the maintenance today on thursday it is fixed, thank you!
