### ISSUE TITLE
Solenor the Slayer bugged

### ISSUE THREAD

**Issue by DotShockCrusade** [slowtorta/turtlewow-bug-tracker#2540]
**Please, provide a clear description what the bug is:**
Solenor the Slayer casts its fear ability regardless of conditions, making him impossible to kite or solo without warlock help

**Steps to reproduce the behavior with as much detail as possible:**

1. Just engage the fight and be within distance

**IDs of affected creatures, items, quests or spells with a link to the relevant page:**

NPC: https://database.turtle-wow.org/?npc=14530
Item: https://database.turtle-wow.org/?item=
Quest: https://database.turtle-wow.org/?quest=
Spell: https://database.turtle-wow.org/?spell=
Object: https://database.turtle-wow.org/?object=

**Expected behavior. Describe how it should work:**

It should only cast fear upon player if snared/rooted

**Comment by Tinyfin-github** [comment]
Issue has been fixed and the fix will be applied at the next update.
