### ISSUE TITLE
Double jed in ubrs 

### ISSUE THREAD

**Issue by geojak** [slowtorta/turtlewow-bug-tracker#2541]
**Please, provide a clear description what the bug is:**

So I was told today that jed in ubrs is not a rare anymore and the annoying Id fishing isn't needed anymore. Very good change! 
Problem is now there is double jed 
**Steps to reproduce the behavior with as much detail as possible:**

1. Go ubrs 
2.  Kill jed 
3.  Twice in one run 

**IDs of affected creatures, items, quests or spells with a link to the relevant page:**

NPC: https://database.turtle-wow.org/?npc=
Item: https://database.turtle-wow.org/?item=
Quest: https://database.turtle-wow.org/?quest=
Spell: https://database.turtle-wow.org/?spell=
Object: https://database.turtle-wow.org/?object=

**Expected behavior. Describe how it should work:**
No double jed

**Comment by Tinyfin-github** [comment]
Fixed.
