### ISSUE TITLE
Undermine Clam Chowder recipe stock never come back

### ISSUE THREAD

**Issue by IxDay** [slowtorta/turtlewow-bug-tracker#2545]
**Please, provide a clear description what the bug is:**
It seems that the recipe `Undermine Clam Chowder` stock is not refreshed. I went there quite a few time and there was no stock. Given the relative low importance of this recipe I have the intuition that this stock CD is not set properly.

**Steps to reproduce the behavior with as much detail as possible:**

1. Go to Jabbey in SteamWheedle Port in Tanaris
2. Talk to the NPC and go to page 3 to see stocks of `Undermine Clam Chowder`
3. Notice that there is none, come back later, there is still no recipe

**IDs of affected creatures, items, quests or spells with a link to the relevant page:**

NPC: https://database.turtle-wow.org/?npc=8139
Item: https://database.turtle-wow.org/?item=16767

**Expected behavior. Describe how it should work:**
I do not recall the CD for this one, but I guess around 1h should do it.

**Comment by slowtorta** [comment]
It's currently set to 2 hours +/- 20% of that time up or down. Working as intended. Seems you've just been unlucky  😢
