### ISSUE TITLE
Moonfury only providing Base Dmg increase and not total dmg increase.

### ISSUE THREAD

**Issue by DraxerTABC** [slowtorta/turtlewow-bug-tracker#2546]
**Please, provide a clear description what the bug is:**
Moonfury is only increasing the base dmg of the spells, not total. Since change of 1.8.0 and the Druid Talent Overhaul it should increase total. https://wowwiki-archive.fandom.com/wiki/Moonfury 

**IDs of affected creatures, items, quests or spells with a link to the relevant page:**
https://database.turtle-wow.org/?spell=16901

**Expected behavior. Describe how it should work:**
It should increase total, not only base.

(Also it seems Idol of the Moon isnt scalling either when it should have after the patch 1.12 [ https://www.wowhead.com/classic/item=23197/idol-of-the-moon#comments:id=3095978
By Dades [on 2006/08/29] (Patch 1.12.0)
As of 1.12 this is calculated after spell damage, thus it is worthwhile again. Tested on a bunch of mobs with Recap. ]

Math on the xlsx file below
ˇˇˇˇˇˇˇˇˇˇˇˇˇˇˇˇˇˇˇˇˇˇˇˇˇˇˇˇˇˇˇ
[Moonkin math about Moonfury and Idol of the Moon.xlsx](https://github.com/slowtorta/turtlewow-bug-tracker/files/10195813/Moonkin.math.about.Moonfury.and.Idol.of.the.Moon.xlsx)

**Comment by DraxerTABC** [comment]
Forgot to add in math about Starfire aswell, but it gets only ~50 more dmg with Max Rank both base and with gear, the gear one should be about 2.4x the increase, not same as ungeared one.

**Comment by SolarGuru** [comment]
**The Idol of the Moon:**

If you look at idol and talent damage increase in your .xlsx, you can see that idol (+17%) gives +17 dmg and talent (+10%) gives +10 dmg to DoT portion. Is this coincidence or real +flat dmg increase? Check on lower rank of moonfire.

Also, look at the comment here (patch 1.12.0):
> no spelldmg equip: 106 dmg per tick
> no spelldmg equip + idol: 111 dmg per tick
So, there is only +5 dmg, not +17 like you have.
Link: https://www.wowhead.com/classic/item=23197/idol-of-the-moon#comments:id=3095980

More comments here say (patch 1.12.0):
> the 17% is added BEFORE +damage
Link: https://www.wowhead.com/classic/item=23197/idol-of-the-moon#comments:id=3095994

**Comment by balakethelock** [comment]
However, another comment says this; 
> As of 1.12 this is calculated after spell damage, thus it is worthwhile again. Tested on a bunch of mobs with Recap.
link: https://www.wowhead.com/classic/item=23197/idol-of-the-moon#comments:id=3095978

So who knows. Clearly blizzard TRIED to make it apply after spell damage, broke it again in a hotfix of the same 1.12 patch and private servers simply assumed it applied before spell damage.

In all cases, Blizzard's intent for both the talent and the idol was to apply AFTER spell damage. Just like the talents shadow priests, warlocks, and mages have.

**Comment by balakethelock** [comment]
@ratkosrb Related: warlock improved Curse of Agony has the same issue.

**Comment by ratkosrb** [comment]
@balakethelock Changed that one too.
