### ISSUE TITLE
Spirit of Redemption removes Soulstone

### ISSUE THREAD

**Issue by ghost** [slowtorta/turtlewow-bug-tracker#2547]
**Please, provide a clear description what the bug is:**
Hi, when a holy priest spec'd into Spirit of Redemption dies with Soulstone on them, the soulstone effect simply disappears. They remain able to heal in spirit form for 10sec, then they just die and receive no option to use SS to rez.
**Steps to reproduce the behavior with as much detail as possible:**

1. Put soulstone on deep holy spec priest
2. have priest die and activate spirit of redemption
3. priest can't use SS after dying at the end of duration

**IDs of affected creatures, items, quests or spells with a link to the relevant page:**

https://database.turtle-wow.org/?item=16896
https://database.turtle-wow.org/?spell=20711

**Expected behavior. Describe how it should work:**
Spirit of Redemption shouldn't remove soulstone effect. The priest should be able to use the rez option after the spirit expires and the priest dies for good.

**Comment by Gurky-Turtle** [comment]
I was unable to reproduce this on a human priest.

**Comment by sieleyah** [comment]
RIP, might have a different condition that i didn't notice. Our priest was a dwarf but i doubt that should matter. I need to find out what else can possibly dispel a fresh 30min SS from a priest in a raid...
