### ISSUE TITLE
Far sight breaks during chained casts

### ISSUE THREAD

**Issue by Zelestreo** [slowtorta/turtlewow-bug-tracker#2549]
**Please, provide a clear description what the bug is:**
Shaman spell Far Sight breaks after a few chain casts.
Issue started after a patch applied on Nov 7. (https://forum.turtle-wow.org/viewtopic.php?f=63&t=4790)
Can only speculate what caused the change - perhaps the bugfix on Hunter spell Eyes of the Beast affected Far Sight?

**Steps to reproduce the behavior with as much detail as possible:**

1. Cast Far Sight in a large outdoors area (Winterspring is a good example, issue seems to occur faster in the larger zones)
2. While channeling, cast another one to a different spot further from your character.
3. Repeat a few times, and the spell should incorrectly put your camera back to your character while still maintaining the channel.

**IDs of affected creatures, items, quests or spells with a link to the relevant page:**

Spell: https://database.turtle-wow.org/?spell=6196

**Expected behavior. Describe how it should work:**
Normally you would be able to span an entire continent without the spell breaking.
I could reliably check herb nodes in Winterspring while waiting for the zeppelin in Durotar for example.

**Comment by Zelestreo** [comment]
Just wanted to give this a bump, it's still broken for me in the same manner as before

**Comment by ratkosrb** [comment]
I can't reproduce the issue myself, but I did another change that might help. Try it again next time the server is updated.

**Comment by Zelestreo** [comment]
No worries, thanks will do!

**Comment by Zelestreo** [comment]
Bumping to say it works now, thanks! \o/
