### ISSUE TITLE
Aura: Stealth

### ISSUE THREAD

**Issue by Sringaram** [slowtorta/turtlewow-bug-tracker#2551]
Reopening [this](https://github.com/slowtorta/turtlewow-bug-tracker/issues/2220) issue again.

Steps to reproduce:

1. Be in a raid group with at least one more player.
2. Engage a raid boss. Most will work.
3. Both players have to be on the threat table.
4. Use Vanish. You'll be put out of combat momentarily and then in combat once again.
5. Wait for the other player to die.
6. The boss/adds will now beeline for you through stealth. This happens regardless of the distance or being out of the line of sight.

Expected behavior: You should remain out of combat if you stay far away enough from the boss/adds.

The only way for this to actually work correctly is for you to be the last player alive before using Vanish, which is only possible through Preparation for double Vanish (PvP build).

Feign Death aura does not suffer from this issue and hunters can correctly avoid dying on wipes.

**Comment by Sringaram** [comment]
This issue also impacts trinket swapping since sometimes you're put in combat before your addon can even swap the trinket out.

**Comment by jlabranche** [comment]
Pretty sure vanish is only suppose to put you at the bottom of the threat table and not take you out of combat in vanilla wow. 

There are several reports on Reddit and our places explaining that vanish leaves combat after 3ish seconds

So wouldn't happen in many raid environments 

And rogues using it to swap nature resist or trinkets shouldn't be possible

**Comment by Sringaram** [comment]
Vanish drops you from combat, that's the intended mechanic and it works fine everywhere else. It also works in raids but you're put in combat again instants later. It is possible to swap gear but it may be inconsistent.
The issue is that there's some kind of instance-wide pulsing "combat" aura which flags you for combat again unless you're under feign death.

**Comment by Sringaram** [comment]
This also happens on some trash packs and it's very inconsistent. Sometimes a single mob you haven't even touched will beeline for you even though the rest already leashed back.

**Comment by jameyboor** [comment]
See https://www.reddit.com/r/classicwow/comments/d9m233/vanish_and_wipes_to_raid_bosses/

This mechanic is correct and how it was in Vanilla and thus not a bug. I do admit however it's a clunky interaction and I will discuss internally if we want to take the non-Vanilla approach for this.
