### ISSUE TITLE
Twilight patrol death trap

### ISSUE THREAD

**Issue by ghost** [slowtorta/turtlewow-bug-tracker#2553]
**Please, provide a clear description what the bug is:**
Hi, there seems to be a pathing issue with the escort of the Twilight prophet. In certain areas during their patrol route (particularly around the twilight camps) they are not visually present where they actually are. When this happens, two things can happen:
1. you see them literally fly through the air at insane speed from point A to point B without them actually being present (you keep getting message "out of range" regardless of being visually in range)
2. You get assaulted by an invisible mob pack (they aren't visually present, but they are there and aggroing on you) and they show up flying in towards you with above mentioned incredible speed after attacking you for 5-10seconds.
Needless to say, option 2 is an horrible death trap that can grief hardcore players.

Note: this happens regardless of my cache/wdb file being clean and other players have experienced this too. It happens with or without the Twilight Prophet being a part of the party. When she is present she copies the behavior of the bugged patrol.

**Steps to reproduce the behavior with as much detail as possible:**

1. Seek out the Twilight prophet patrol in Silithus (they go in circles between the 3 twilight camps on the left side of the map)
2. Follow their route for at least an entire circle. They tend to bug out when approaching the camps. Suddenly they just start sprinting mid air and their visual appearance have nothing to do with their actual position afterwards.
Alternatively, sit down along the patrol route around coords (24;31) in Silithus. Sooner or later you will get assaulted out of thin air, while they aren't visually present (they usually fly through this area in the bugged state so you can't tell where they are until engaging in combat by accident and they fly super fast over to you)

**IDs of affected creatures, items, quests or spells with a link to the relevant page:**
https://database.turtle-wow.org/?npc=15308
https://database.turtle-wow.org/?npc=11880

**Expected behavior. Describe how it should work:**
The patrol should not lose its pathing and start flying around. They should always be visually where they are actually present.

**Comment by cyaohiri** [comment]
This seems to be a very similar behavior to #529 and #2353. Both of these issues are still present.

**Comment by SolarGuru** [comment]
Some more info about this possible bug.

I have ~20 kills of the Twilight Prophet and never seen such a problem.
There is the Prophet and her 4 Guards (Twilight Avengers), but only Prophet have patrol route, Guards just escort her. 
Respawn time of Prophet is ~15 mins less than respawn time of Guards. So, there is situation when you can meet respawned Prophet patrolling without Guards OR respawned Guards waiting on their respawn point for the Prophet to respawn.

I believe "the flying guards" are just respawned Guards trying to reach patrolling Prophet at far.

Also, once I met lonely Prophet far away from patrol route. She flew away to patrol route from me when I engaged in combat, so I have to chase her and kill because I was stuck never-ending combat.

**Comment by slowtorta** [comment]
Hopefully, fixed on the next update.

**Comment by geojak** [comment]
@slowtorta unfrotuently not fixed as of today after last client patch

**Comment by SolarGuru** [comment]
Still meeting flying patrol with no Prophet (looks like she's still not respawned)
![image](https://user-images.githubusercontent.com/56233770/211194264-46618e18-6e59-4b32-849b-2511ce2d779a.png)

**Comment by geojak** [comment]
i also saw the ungroro devilsaur speedhacking again around the east pylon near the river. it seems to me the mobs when they almost finished their patrol they somehow speed hack back to the starting point
