### ISSUE TITLE
Hunter: Aimed shot delay after end casting

### ISSUE THREAD

**Issue by Otakoe** [slowtorta/turtlewow-bug-tracker#2554]
**description:**
I did notice that Aimed shot is the only one spell in game what has delay agter finishing casting. Some players tries to fix that with macro -> https://forum.turtle-wow.org/viewtopic.php?f=45&t=4358&p=25955#p25955 . Some players recomends to use Nampower addon but im not sure is it legal to using -> https://github.com/namreeb/nampower
But this game not about macro and addons. So its just old annoying bug. This delay ruins dps when u not expect that. For example when u use Rapid fire + have proc by Imroved aspect of the hawk, u expect on fast cast time (1.6s on my cast bar) but instead that u have additional delay (1.6+ from 0.3 to 0.7). Not ping problem (55-90 mine), i never seen delay on Shadow bolt, and i didnt see this behavior on old vanilla videos

**Steps to reproduce:**

1. Cast Aimed shot
2. See the time between cast ending and shoot.
note 1: for measuring recomend to use any video recorder (OBS for example)

Link on spell in Database
https://database.turtle-wow.org/?spell=19434

**Expected behavior:**
1. After finishing casting no any delays. As casting shadowbolt, frostbolt, firebolt etc.

**Comment by SabineWren** [comment]
Related #1742

Aimed Shot, Trueshot, and Multi-Shot all add a 0.5 second delay that's unaffected by haste. Therefore,
Aimed Shot casts in 1.76 seconds with QS+RF.

This confused me for a long time too, but it's intended. Only documentation I found was an old Blizzard changelog:
https://www.mmo-champion.com/content/2188-Patch-4-0-6-Feb-22-Hotfixes-Blue-Posts-Artworks-Comic

**Comment by twowTurtReynolds** [comment]
Thank you @SabineWren for the confirmation. These really obscure timings throw us all for a loop, don't they?

@Otakoe By the way, Nampower is allowed on Turtle WoW.
