### ISSUE TITLE
Warlock shard/pet not refunded when dying in bgs

### ISSUE THREAD

**Issue by ghost** [slowtorta/turtlewow-bug-tracker#2555]
**Please, provide a clear description what the bug is:**
Hi, there seems to be an issue with refunding pets (indirectly, the shards) for warlocks when the warlock dies in CC (could be other causes too, but this one I noticed the most).
Normally, when the warlock is killed, their current pet is refunded and respawns together with the lock in the graveyard, saving you the time and soul shard from having to resummon it. This applies also when the warlock runs with Demonic Sacrifice instead of a pet - the pet which was sacrificed is refunded instead.
However, usually when I die in a stunlock or my character is otherwise crowd controlled, after dying I get no refund on either shard or pet, which is about 50% of the time. This means I am out of the game for 10seconds to resummon my pet and I lose a shard every time, something which is incredibly difficult to replenish in a PVP situation. This puts warlocks at a huge disadvantage when fighting for time sensitive objectives or in long battlegrounds where you need to bring at least 40 shards to have a chance of not running out this way.

**Steps to reproduce the behavior with as much detail as possible:**
It's not exactly clear to me which types of specific crowd control cause the issue. There is little room to see what's happening in a messy pvp battle.
Generally you want to get attacked by a gang of rogues and die while in their stunlock if you want to reproduce this.

**IDs of affected creatures, items, quests or spells with a link to the relevant page:**
Not sure what to link here for this report. 
https://database.turtle-wow.org/?item=6265
https://database.turtle-wow.org/?spell=24827?
https://database.turtle-wow.org/?spell=23464?
https://database.turtle-wow.org/?spell=697
https://database.turtle-wow.org/?spell=712
https://database.turtle-wow.org/?spell=691

**Expected behavior. Describe how it should work:**
Warlocks should always get their pet (or at least the shard they cost) refunded when dying in bgs, regardless of the circumstances of their deaths.

**Comment by ratkosrb** [comment]
I can't reproduce the issue. Tried stunning and fearing the warlock, the pet, and both, but the shard is refunded each time and my pet is there when I respawn. Try to remember more details about what happened when you didn't get a shard, so that the true reason can be found.

**Comment by sieleyah** [comment]
Hmm, I have mostly played with Demonic Sacrifice instead of an active pet, that might be an important factor. 
My pet usually respawns properly with me when I die slowly (just a few players firing at me), and more commonly vanishes when i'm under heavy fire/stunlock. If it's not the crowd control, could it be possibly the sheer amount of debuffs/incoming attacks? Could it be related to my insignia being taken? (It is not usually taken when there are fewer players present)
