### ISSUE TITLE
Guild Bank Tab2 isn't logging items being deposited or withdrawn. 

### ISSUE THREAD

**Issue by tomcoffingiii** [slowtorta/turtlewow-bug-tracker#2557]
**Please, provide a clear description what the bug is:**

**Steps to reproduce the behavior with as much detail as possible:**

1. Placed something into a tab2 into the guild bank
2. When looking at the logs, it's not showing up.
3. Happens for anything I placed in.  

**IDs of affected creatures, items, quests or spells with a link to the relevant page:**

NPC: https://database.turtle-wow.org/?npc=
Item: https://database.turtle-wow.org/?item=
Quest: https://database.turtle-wow.org/?quest=
Spell: https://database.turtle-wow.org/?spell=
Object: https://database.turtle-wow.org/?object=

Anytime I take something out of the bank / place something into the bank, a record should be created.  It works fine on other tabs, it just seems to be tab2 of <SQAUD>'s guild bank. Screenshots Attached.
![Issue1-2](https://user-images.githubusercontent.com/3590573/207197418-b7f56fc5-d7e6-4a54-a131-1a36a09647b2.png)
![Issue1](https://user-images.githubusercontent.com/3590573/207197403-765d32d2-47a1-4552-8ab5-bea52e1cb5d4.png)

**Comment by slowtorta** [comment]
@CosminPOP

**Comment by slowtorta** [comment]
Tested in 1.16.5, working as intended.
