### ISSUE TITLE
Paladin: Seal of Crusader not procing holy damage. 

### ISSUE THREAD

**Issue by 8EightySixed6** [slowtorta/turtlewow-bug-tracker#2558]
**Please, provide a clear description what the bug is:**

**Steps to reproduce the behavior with as much detail as possible:**

1. Cast Seal of Crusader
2. Judgement any enemy
3. Cast Seal of Righteousness

**IDs of affected creatures, items, quests or spells with a link to the relevant page:**

NPC: https://database.turtle-wow.org/?npc=
Item: https://database.turtle-wow.org/?item=
Quest: https://database.turtle-wow.org/?quest=
Spell: https://database.turtle-wow.org/?spell=
Object: https://database.turtle-wow.org/?object=

**Expected behavior. Describe how it should work:**

Should be adding more holy damage and its not.

**Comment by ratkosrb** [comment]
The seal has been changed and no longer does that. The Judgement procs effects on your weapon instead. Wait for the next client patch to see the real description.

**Comment by 8EightySixed6** [comment]
What description will it have? Trying to understand what exactly it does? Does it just increase weapon damage? Does it not show a debuff on the target too? I don't see it buff my char either....

**Comment by ratkosrb** [comment]
It causes Chance on Hit effects on your weapon to proc when you judge it.

So if you have this weapon for example it will shoot a Fireball when you use Judgement.
https://database.turtle-wow.org/?item=17182

**Comment by 8EightySixed6** [comment]
Will it shoot fireball with every hit?

**Comment by 8EightySixed6** [comment]
Interesting changes! Makes we want more weapons with more abilities now haha

So as long as Seal of Crusader is active on me it will proc the weapon? Just to clarify sorry just making sure I got it!

What happens if I use judgement? Seal of Crusader + Judgement

**Comment by ratkosrb** [comment]
The seal is the same as before. The judgement will proc your weapon effect and enchants.
