### ISSUE TITLE
Nature's Grasp(Rank 1) dissapears from spellbook after learning Nature's Grasp(Rank 3)

### ISSUE THREAD

**Issue by Tinyfin-github** [slowtorta/turtlewow-bug-tracker#256]
Nature's Grasp(Rank 1) dissapears from spellbook after learning Nature's Grasp(Rank 3)

![unknown](https://user-images.githubusercontent.com/83077166/129961704-4f75b81a-4ebd-48fe-ad3f-0067f542f956.png)

Nature's Grasp(Rank 1)   https://database.turtle-wow.org/?spell=16689
Nature's Grasp(Rank 3)  https://database.turtle-wow.org/?spell=16811

**Comment by slowtorta** [comment]
Fixed in the next revision. 
![image](https://user-images.githubusercontent.com/66763404/166123597-1c029c38-d4e7-4605-9dae-0c9b0b653d71.png)
