### ISSUE TITLE
Windfury Totem

### ISSUE THREAD

**Issue by vkekd** [slowtorta/turtlewow-bug-tracker#2561]
The 30% melee attack power that the talent 'Improved Weapon Totems' should apply doesn't work on anyone else except for the shaman.
Currently only the caster can benefit from this talent, which makes it completely useless.

1. Spec into 'Improved Weapon Totems' and drop Windfury Totem
2. Attack with the Shaman and with an alt
3. Check the attack power on both characters whenever you get a windfury proc

'Improved Weapon Totems' should work for anyone in the party.

**Comment by Zeyla-TW** [comment]
This is currently being addressed and should be fixed in an upcoming patch.
