### ISSUE TITLE
City Protector's Medallion.

### ISSUE THREAD

**Issue by tarkustrakustarkus** [slowtorta/turtlewow-bug-tracker#2563]
Please, provide a clear description what the bug is: 

I have not received a new City Protector's Medallion for being Thane this week.

Steps to reproduce the behavior with as much detail as possible:

1. I have been Thane for 3 weeks in a row. I would like a new City Protector's Medallion for being Thane again this week.
2. I received 2 City Protector's Medallions on the first week I was Thane and have not recieved a new one since then.
3. Some people have told me there can be a delay with receving the medallion and that makes sense no problem there. Some people have also noted to me that they have received more than 1 City Protector's Medallion at a time.

IDs of affected creatures, items, quests or spells with a link to the relevant page:
https://database.turtle-wow.org/?item=50056

Expected behavior. Describe how it should work:
The item says it has 7 days duration of playtime and is also supposed to work if you have the city protector title. My item has only a few hours of duration left since it was the first one that I recieved. 
![WoWScrnShot_121522_095306](https://user-images.githubusercontent.com/120693644/207998248-fbe39d3a-a377-4a71-933d-46d2eec9bbea.jpg)
![WoWScrnShot_121522_095256](https://user-images.githubusercontent.com/120693644/207998249-2bbdd862-281e-400d-885b-4c82279349dc.jpg)

**Comment by slowtorta** [comment]
You'll receive a new one if the old one would expire if you meet the requirements.
