### ISSUE TITLE
Druid - Set bonus error: cenarion rainment - 3 piece bonus

### ISSUE THREAD

**Issue by 88kr** [slowtorta/turtlewow-bug-tracker#2565]
**Please, provide a clear description what the bug is:**

**Steps to reproduce the behavior with as much detail as possible:**

1. Error in the set bonus from Druid's Cenarion Rainment 3-Piece set bonus.   
2. To replicate, I am using 3 Cenarion set pieces:  Gloves, Boots, Shoulders
3.  Set bonus should be thorns buff duration extended to 15 min (this part works), and also damage increasing from 18 to 22. 
4. In-game tooltip for set bonus shows 15 min / 22 damage, but buff received shows 15 min /  (only) 18 damage.  this is the error / bug.

**IDs of affected creatures, items, quests or spells with a link to the relevant page:**

NPC: https://database.turtle-wow.org/?npc=
Item: https://database.turtle-wow.org/?item=
Quest: https://database.turtle-wow.org/?quest=
Spell: https://database.turtle-wow.org/?spell=
Object: https://database.turtle-wow.org/?object=

**Expected behavior. Describe how it should work:**

**Comment by Dragunovi** [comment]
Damage values on buffs and debuffs are not actively updated with talents and set bonuses, this is likely functional but not displayed.
