### ISSUE TITLE
RevMoneyMaxLevel incorrect calculations

### ISSUE THREAD

**Issue by ghost** [slowtorta/turtlewow-bug-tracker#2567]
**Please, provide a clear description what the bug is:**
Hi, the lvl 60 monetary reward is still incorrectly calculated for a large number of dungeon and raid quests, as well as custom quests. Most of these high difficulty quests seem to award only 10% of the expected gold value. 
RevMoneyMaxLevel is supposed to be calculated as 6xRewXP. 
In case of over a hundred tested quests on turtle, it seems to be 0,6xRewXP.
Since Jamey's update on the database (ref to my earlier report: https://github.com/slowtorta/turtlewow-bug-tracker/issues/2439), you can now see quest EXP rewards, RevMoneyMaxLevel values, and also the equivalent gold reward on each quest in the database, so this does not require in game testing, though I assure you I have done the quests and the experienced values match the wrongly calculated database values.

Here is an example:
https://database.turtle-wow.org/?quest=40495 >> RewXP 6400 >> 6*6400 = 38400, which is what the RevMoneyMaxLevel should be. But the RevMoneyMaxLevel is only 3840. This translates to 38,4silver instead of 3,84 gold.
Meanwhile, notice this quest: https://database.turtle-wow.org/?quest=4982 has the same 6400 RewXP and the proper 38400 RevMoneyMaxLevel and awards the proper amount of money.

I cannot tell what makes it so that two quests with the same exp reward have different calculations for reward money. 

The number of affected quests is probably in the range of hundreds and I definitely cannot link them all 1 by 1.

Here are a few more examples to give you an idea:

https://database.turtle-wow.org/?quest=8710 >>This is the warlock AQ20 weapon quest. Same thing 3960 instead of 39600. 39,6 silver instead of 3,96 gold.
https://database.turtle-wow.org/?quest=8702 >>This is the warlock AQ20 cloak quest. Again, 10% of the calculated value is present. One digit off. 
There are 3 turn-ins per class, and 9 classes so this is a total of 27 affected quests.

Now the AQ40 turn ins: 
https://database.turtle-wow.org/?quest=8662 >>This is the Warlock AQ40 t2,5 helm quest. With 9950 RewXP the expected value is 6*9950= 59700 or 5,97 gold. In reality, the RevMoneyMaxLevel is only 5970 and the quest only awards 59,7 silver.
Note, there are 5 quest turn-ins for each class in AQ40 and there are 9 classes. That's 45 quests total. Pretty sure they all have the same issue. 

Here is an example from the quest chain for Red Scepter shard: 
https://database.turtle-wow.org/?quest=8730 RewXP 9950, same as above. RevMoneyMaxLevel only 5970. 
The entire quest chain behaves the same way, which is like 8-9quests or something.

Here are some examples for non-dungeon quests from Karfang Hold, a custom turtle quest hub (all of the quests in this hub have same issue, at least 8-10 quests)
https://database.turtle-wow.org/?quest=40505
https://database.turtle-wow.org/?quest=40506
https://database.turtle-wow.org/?quest=40508

Here are some quests from Sandfury trolls custom area (most of them are regular quests, only one is dungeon)
https://database.turtle-wow.org/?quest=40525
https://database.turtle-wow.org/?quest=40522 whole chain
https://database.turtle-wow.org/?quest=40526

A random custom dungeon quest from Uldaman https://database.turtle-wow.org/?quest=40129
A random, non-custom dungeon quest from Blackfathom Deeps https://database.turtle-wow.org/?quest=6561

As you can see, the amount of gold players lose to this bug is not small. 5gold per raid quest, 3gold per dungeon quest.
This is a general issue that seems to affect most dungeon quests, raid quests, and custom turtle quests. To the point this makes it not worth for lvl 60s to quest for gold at all.

**Steps to reproduce the behavior with as much detail as possible:**

1. Do the above mentioned quests at lvl 60.
2. You barely get any gold.

**IDs of affected creatures, items, quests or spells with a link to the relevant page:**

Far too many to make a comprehensive list. This is not a one man job to gather.

**Expected behavior. Describe how it should work:**
All quests should have proper RevMoneyMaxLevel calculation and should award the proper amount of gold to lvl 60s who complete them.

**Comment by slowtorta** [comment]
Added RewMoneyMaxLevel for 204 new quests.
Corrected money rewards for 800 other quests in our custom range.
