### ISSUE TITLE
Ossirian's Pylons and Entrance Door are Broken

### ISSUE THREAD

**Issue by Dragunovi** [slowtorta/turtlewow-bug-tracker#257]
**Please, provide a clear description what the bug is:**
Ossirian's pylons don't shoot him %90 of the time, no matter how close he is to the activated pylon.
Addition to this the door at the entrance of the instance seems to get permanently blocked after a wipe/random reset from Ossirian the Unscarred, forcing a summon to even get inside.
**Steps to reproduce the behavior with as much detail as possible:**

1. Go to AQ20
2. Go to Ossirian the Unscarred and engage the fight.
3. Drag him to a pylon and activate it, and see if it works. Make sure to try a few times.

**IDs of affected creatures, items, quests or spells with a link to the relevant page:**

NPC: https://database.turtle-wow.org/?npc=15590
NPC: https://database.turtle-wow.org/?npc=15339

**Expected behavior. Describe how it should work:**
The pylon should be able to hit and weaken Ossirian the Unscarred when in range every time.

**Comment by slowtorta** [comment]
Is it still broken?
