### ISSUE TITLE
Ankh Bug for my shaman Ressickness

### ISSUE THREAD

**Issue by Ressickness** [slowtorta/turtlewow-bug-tracker#2570]
**Please, provide a clear description what the bug is:**
When I die in PVP or PVE I receive a standard textbook to release spirit or to use my ankh.  When I click to use my ankh, there is red script that says, "Not enough mana."  It then leaves me dead without a text box that allows for even a simple release to the graveyard.  It does not use an ankh during this occurence.  I have no way to release to a graveyard until I /reload.

**Steps to reproduce the behavior with as much detail as possible:**

1. Have someone kill the character
2.  Click for the ankh
3.  Watch as nothing happens

**IDs of affected creatures, items, quests or spells with a link to the relevant page:**

NPC: https://database.turtle-wow.org/?npc=
Item: https://database.turtle-wow.org/?item= Ressickness (Ankh bug)
Quest: https://database.turtle-wow.org/?quest=
Spell: https://database.turtle-wow.org/?spell=
Object: https://database.turtle-wow.org/?object=

**Expected behavior. Describe how it should work:**

It should reincarnate the toon upon clicking the option to ankh.
![WoWScrnShot_121822_111947](https://user-images.githubusercontent.com/120978897/208315583-f6891fa1-d26a-4f82-97f3-8d15b079f9a1.jpg)
![WoWScrnShot_121822_111949](https://user-images.githubusercontent.com/120978897/208315584-657c3171-b86a-43e7-8e7f-e58624d4bcf5.jpg)

**Comment by Jeradooka** [comment]
As a fellow shaman player, I am not experiencing this bug. I am an orc shaman and can successfully use the ankh in both PVP and PVE settings.
