### ISSUE TITLE
Cannibalize forsaken racial

### ISSUE THREAD

**Issue by ghost** [slowtorta/turtlewow-bug-tracker#2571]
**Please, provide a clear description what the bug is:**
Hi, this racial ability is supposed to be usable on any humanoid/undead corpse, not specified to hostile ones. Currently the ability only works against hostile targets, not on the corpses of friendly NPCs or players. This greatly reduces the value of the ability, as you don't get to regen health from fallen comrades in a bunch of situations where it is supposed to be a part of your toolkit to survive.

**Steps to reproduce the behavior with as much detail as possible:**

1. Find the corpse of a friendly target (i.eg. dead group member in a raid or battleground)
2. Stand on top of corpse and use cannibalize
3. You get error message, as if there were no corpses nearby

**IDs of affected creatures, items, quests or spells with a link to the relevant page:**

https://database.turtle-wow.org/?spell=20577

**Expected behavior. Describe how it should work:**
Cannibalize should work on any undead/humanoid corpse, including friendly npcs, friendly players, and opposite faction players that are in your dungeon/raid group, as long as they haven't resurrected and turned into a skeleton.

**Comment by jameyboor** [comment]
Can you provide a source for this claim? I'm almost certain it's not allowed to begin with.
