### ISSUE TITLE
Wolf Totem typo

### ISSUE THREAD

**Issue by Kharkov72** [slowtorta/turtlewow-bug-tracker#2572]
https://database.turtle-wow.org/?item=60104
![Untitled](https://user-images.githubusercontent.com/25846834/208361045-e2e59caa-3dff-4f5a-a0a5-5b3dd4853ae7.png)
Should be Though.

**Comment by slowtorta** [comment]
This will be fixed in the next client update.

**Comment by slowtorta** [comment]
Sorry for the first misleding comment, wrong issue. Fixed on the next update.
