### ISSUE TITLE
Highvale Gorilla's stun is not immunable

### ISSUE THREAD

**Issue by Zebouski** [slowtorta/turtlewow-bug-tracker#2576]
**Please, provide a clear description what the bug is:**
on tel abim, some of the gorillas have a stun that cannot be removed like blizzlike stuns can

**Steps to reproduce the behavior with as much detail as possible:**

0. equip pvp trinket on a class where it removes stuns, like warrior
1. pop a free action potion
2. pull mob
3. get stunned during FAP
4. try to pop pvp stun trinket

**Expected behavior. Describe how it should work:**
if the tooltip says stun, it should be removed/immuned by stuff that counters stun

**Comment by slowtorta** [comment]
https://github.com/slowtorta/turtlewow-bug-tracker/issues/2612
https://github.com/slowtorta/turtlewow-bug-tracker/issues/2634

Related to the same mob ^

**Comment by Muigin** [comment]
The stun spell on Tel'Abim gorillas has been changed, and is now susceptible to immunity and diminishing returns.
