### ISSUE TITLE
Immortal Champion's Charger

### ISSUE THREAD

**Issue by Shieldzies** [slowtorta/turtlewow-bug-tracker#2577]
**Please, provide a clear description what the bug is:**
Prior to the patch I had an Immortal Champion's Charger. The icon is a purple dragon head and says "Riding Nexus Drake" there is also a drake roar when you mount it. The actual mount is exactly the same it is still the horse.
**Steps to reproduce the behavior with as much detail as possible:**

1. Open spellbook
2. Click mounts tab
3. "Riding Nexus Drake"

**IDs of affected creatures, items, quests or spells with a link to the relevant page:**

NPC: https://database.turtle-wow.org/?npc=
https://database.turtle-wow.org/?item=80692
Quest: https://database.turtle-wow.org/?quest=
Spell: https://database.turtle-wow.org/?spell=
Object: https://database.turtle-wow.org/?object=

**Expected behavior. Describe how it should work:**
Horse icon and horse sound

**Comment by slowtorta** [comment]
Fixed after update. 
![image](https://user-images.githubusercontent.com/66763404/208720641-41a2f50f-9078-45f3-b45b-9e6b30e56244.png)
