### ISSUE TITLE
Battery-Powered Crowd Pummeler on use disappeared.

### ISSUE THREAD

**Issue by Sygmoond** [slowtorta/turtlewow-bug-tracker#2578]
**Please, provide a clear description what the bug is:**

Title! The on use ability of BPCP disappeared, leaving feral druids on suicide watch

How it looks in game:
![depression](https://user-images.githubusercontent.com/89550040/208613944-ad86f0b6-f951-4746-b504-65677216aa2f.png)

Item: https://database.turtle-wow.org/?item=60099

**Expected behavior. Describe how it should work:**

Should look like this: 

![happiness](https://user-images.githubusercontent.com/89550040/208614160-18a3f01b-f345-4316-9fd0-8ce7201ccb2b.jpg)

gib back hasty pls

**Comment by slowtorta** [comment]
Fixed after update.
