### ISSUE TITLE
Pendant of the Faceless unique but tooltip states otherwise

### ISSUE THREAD

**Issue by gabor-varga** [slowtorta/turtlewow-bug-tracker#2580]
**Please, provide a clear description what the bug is:**

The pre-patch for `1.16.4` turned [Pendant of the Faceless](https://database.turtle-wow.org/?item=60551) unique, however the tooltip of the item does not say so. Either change it back to be not unique (wink wink) or adjust the tooltip.

**Steps to reproduce the behavior with as much detail as possible:**

1. Look at Pendant of the Faceless
2. Tooltip doesn't say unique
3. Spend 250 runs on HFQ to farm 2 trinkets
4. 1.16.4 Prepatch removes one item from your inventory and you get it in mail
5. Can't take item from mail as it say "you can only have one of these items"

**IDs of affected creatures, items, quests or spells with a link to the relevant page:**

Item: https://database.turtle-wow.org/?item=60551

**Expected behavior. Describe how it should work:**

Revert it to be non-unique, or add tooltip.

**Comment by geojak** [comment]
Did you delete wdb? Maybe tooltip isn't updated?

**Comment by gabor-varga** [comment]
> Did you delete wdb? Maybe tooltip isn't updated?

I downloaded a new client altogether for today but will double check after I delete WDB

**Comment by gabor-varga** [comment]
After downloading a fresh `1.16.5` client the "unique" tag is now visible.
