### ISSUE TITLE
Alterac Valley Mine Layer constantly CC feral

### ISSUE THREAD

**Issue by gabor-varga** [slowtorta/turtlewow-bug-tracker#2581]
**Please, provide a clear description what the bug is:**

The Horde [Mine Layer](https://database.turtle-wow.org/?npc=13357) ability [Flash Bomb](https://database.turtle-wow.org/?spell=29419) has no CD and no diminishing return. As a feral this puts you in constant CC that can not be broken (or even if it is, you get CC-d again soon). This is probably not the intended mechanic, as you can not get even close to this NPC much less tank/kill it.

**Steps to reproduce the behavior with as much detail as possible:**

1. Shift to feral form
2. Get close to Horde Mine Layer
3. Get CC-d into oblivion
4. Profit

**IDs of affected creatures, items, quests or spells with a link to the relevant page:**

NPC: https://database.turtle-wow.org/?npc=13357
Spell: https://database.turtle-wow.org/?spell=29419

**Expected behavior. Describe how it should work:**

The spell should have proper CD, and diminishing return. Currently the duration is always 10 s.

**Comment by ratkosrb** [comment]
This appears to be in fact intended behavior. There is a comment in his script that says so.
![Untitled](https://user-images.githubusercontent.com/35845488/211195638-5a31f839-aeb6-41da-84af-a66a1b1d5e93.jpg)
