### ISSUE TITLE
Floating debris spots no longer float

### ISSUE THREAD

**Issue by Slimthegrim** [slowtorta/turtlewow-bug-tracker#2582]
**Some floating debris fish spawn spots are spawning on seafloor, not floating up top on water.**

**Steps to reproduce the behavior with as much detail as possible:**
1. Be fast.
2. Go to shoreline where Floating Debris can spawn
3. See problem

![image](https://user-images.githubusercontent.com/110629519/208672997-24a47357-92ac-4d2b-ae3e-46e4102acecb.png)

**Expected behavior. Describe how it should work:**
Well wood floats eh? Looks like boxes to me.

**Comment by slowtorta** [comment]
Floating just fine for me, not enough information to reproduce the bug.
