### ISSUE TITLE
Ashenvale Outrunner movement

### ISSUE THREAD

**Issue by swaglis** [slowtorta/turtlewow-bug-tracker#2583]
**Steps to reproduce the behavior with as much detail as possible:**

1. Aggro an Ashenvale Outrunner mob
2. Try to run away

Instead of running after you the mob will rp walk.

**IDs of affected creatures, items, quests or spells with a link to the relevant page:**
https://database.turtle-wow.org/?npc=12856

**Expected behavior. Describe how it should work:**
When out of range the mob will run after me instead of walking.

**Comment by redmagejoe** [comment]
Cannot reproduce. NPCs run properly.

Fixed.
