### ISSUE TITLE
Crashing very often on Linux with client 1165

### ISSUE THREAD

**Issue by cckfrnk** [slowtorta/turtlewow-bug-tracker#2584]
After the new patch I get crashes very often, not as much at first after the initial install (I downloaded a new client each time) but with increasing frequency as I play for longer. This happened yesterday (Monday night) after the initial release, after which I was even able to be in Winter Veil Vale for a while, but after around 30m I started crashing every 5 minutes more or less, and most of those crashes were simply the game freezing until I finally had to terminate the process, so not even a message most of the time (like that memory issue which used to occur before the patch). The few times in which there's a message it's as in the attached image below. I've given up on playing Turtle for today since after a total of more than 10 crashes within an hour I just crashed an additional 4 times with an average of 2 minutes between each crash (and if this continues I won't be able to play at all until it's fixed of course, raiding is impossible and my ranking plans were already broken by the patch being pushed before the server reset - during AV holiday - and at this point I'll spend more time with the deserter debuff than in BGs).

Since there's no associated log or even error message most of the time I'm not sure how to describe a way to reproduce behavior, all I can say is that I'm using Wine in Linux Mint and attach the image I referred to earlier:
![image](https://user-images.githubusercontent.com/121141490/208801340-ab6fe29a-66a7-40e3-bd4e-d3190f1d54e7.png)

**Comment by slowtorta** [comment]
Please, reach out to support on our Discord.

**Comment by cckfrnk** [comment]
I did, after the usual suggestions (like reinstalling the client, clearing addons and applying the 4gb patch) I was told to open an issue here. I haven't crashed today despite no changes on my side, but I'm waiting until after raiding tonight to check if it's indeed solved.
