### ISSUE TITLE
Magistrate Barthilas not running.

### ISSUE THREAD

**Issue by Kharkov72** [slowtorta/turtlewow-bug-tracker#2585]
Rather than running to his normal location before Slaughter Square, he just stays before the gate in Elder's square, easily farmable. 
https://database.turtle-wow.org/?npc=10435

**Steps to reproduce the behavior with as much detail as possible:**

1. Enter Instance from shortcut to the undead quarter
2.  Open first gate
3.  He yells and runs to the gate but no further

**Expected behavior. Describe how it should work:**
Apparently if you enter from the shortcut, he is supposed to run further in the instance, but this is not the case. Could be a design choice, or could be something like his scripting not opening the gate and just shitting.

**Comment by ratkosrb** [comment]
https://github.com/slowtorta/turtle-wow/commit/0cb8842c81b931f8be1d39876101941df77a6250
