### ISSUE TITLE
bug in fel rock

### ISSUE THREAD

**Issue by zulashi** [slowtorta/turtlewow-bug-tracker#2586]
**Please, provide a clear description what the bug is:**
i was doing the "twisted hatred" as a hunter then i jumped in the water cuz i was about to die then the enemys started evading and not taking damage and apprantly can't swin
**Steps to reproduce the behavior with as much detail as possible:**

1.jump on water 
2. damage any enemy there
3. and u have to be in the steep part of the water 

**IDs of affected creatures, items, quests or spells with a link to the relevant page:**

creatures: https://database.turtle-wow.org/?npc=2005
Item: https://database.turtle-wow.org/?item=
Quest: https://database.turtle-wow.org/?quest=932
Spell: https://database.turtle-wow.org/?spell=
Object: https://database.turtle-wow.org/?object=
creatures :https://database.turtle-wow.org/?npc=2004

**Expected behavior. Describe how it should work:**
i guess swim and not evading my attacks when am on the water

**Comment by slowtorta** [comment]
@jameyboor More issues for pathing around the water.
