### ISSUE TITLE
Tirsfal Uplands: Steepwater Cliff Graveyard

### ISSUE THREAD

**Issue by swaglis** [slowtorta/turtlewow-bug-tracker#2589]
**Please, provide a clear description what the bug is:**
When I died in the uplands I got teleported to the Deathknell graveyard, instead of the Steepwater Cliff.
Happened to me two times: once was at (14,60) coords and the other time it was while killing the gnolls in the area, but I don't remember the exact spot.

**Comment by redmagejoe** [comment]
This issue persists on current version.

**Comment by slowtorta** [comment]
Fixed in 1.16.6. Hower if you die _too close_ to Deathkneel, you'll end up there.
