### ISSUE TITLE
Transmorg + Devilsaur Set

### ISSUE THREAD

**Issue by Dolden1** [slowtorta/turtlewow-bug-tracker#2591]
**Please, provide a clear description what the bug is:**
Set bonus does not show, if one item is bag, it will show it equipped, otherwise if both are equipped none show equipped under bonus area.
**Steps to reproduce the behavior with as much detail as possible:**

1. Transmorg gauntlets and leggings, both from different leatherworkers.
2. Restart wow, delete WDB, requip gear.
3. No bonus. Not sure if its just graphical or what, since it is not possible to show hit % rating?

**IDs of affected creatures, items, quests or spells with a link to the relevant page:**

NPC: https://database.turtle-wow.org/?npc=
Item: https://database.turtle-wow.org/?item=
Quest: https://database.turtle-wow.org/?quest=
Spell: https://database.turtle-wow.org/?spell=
Object: https://database.turtle-wow.org/?object=

**Expected behavior. Describe how it should work:**

**Comment by slowtorta** [comment]
Sadly, this bug that we're unable to fix in the any foreseeable future.
