### ISSUE TITLE
sw keep guard started sprinting on patrol

### ISSUE THREAD

**Issue by geojak** [slowtorta/turtlewow-bug-tracker#2595]
**Please, provide a clear description what the bug is:**

the guard in sw patrol that walks betwen the entrance and the main hall started to sprint in 1.16.5. he should walk with more chill

**Steps to reproduce the behavior with as much detail as possible:**

1. go to sw keep
2. watch the guard
3. see my video 

https://user-images.githubusercontent.com/25199983/209401021-ed9d8b82-7775-41d0-9bf3-c3819390b547.mp4

** Expected behavior. Describe how it should work:**

rp walking guards

**Comment by geojak** [comment]
theramore guards also sprint

**Comment by Gurky-Turtle** [comment]
I believe this has something to do with them dropping combat at some point and after they just run everywhere.
