### ISSUE TITLE
Hero of the Frostwolf 

### ISSUE THREAD

**Issue by Olamek** [slowtorta/turtlewow-bug-tracker#2596]
Hello,

Horde quest "Hero of the Frostwolf" seems bugged. After finishing it´s "pre-quest" - "The Battle for Alterac" the mentioned quest isn´t offered by NPC.

I already tried to discuss this with GM´s in game via ticket, they tried to reset both quests + add them back in my quest log, but it didn´t help to fix this issue.

I meet all the requirements for this,  "Hero of the Frostwolf" quest (meaning at least lvl 51 and already done quest "The Battle for Alterac" but NPC "Voggah Deathgrip" do not offer me this quest.
![Q](https://user-images.githubusercontent.com/110063863/209408748-1ba7ab64-6586-4ede-9d5d-975c0d38e880.PNG)
![W](https://user-images.githubusercontent.com/110063863/209408751-cce3e1de-fabd-4594-85a4-d7122150592f.PNG)

After finishing "The Battle for Alterac" (Horde side) NPC "Voggah Deathgrip" should offer to player follow-up quest "Hero of the Frostwolf" so PC can pick up is reward.

NPC: https://database.turtle-wow.org/?npc=13817
"Bugged"Quest: https://database.turtle-wow.org/?quest=8272
"Pre-quest"Quest: https://database.turtle-wow.org/?quest=7142

Attached are also 2 pictures with short communication (and answer) with in game GM.

Thank you

**Comment by redmagejoe** [comment]
I believe this quest was replaced with the quest to kill Korrak Bloodrager with the implementation of old Alterac Valley. Both quests existed in the database, but only one was available. It seems likely that they have swapped, and you must now organize a contingent to kill Korrak.

**Comment by ratkosrb** [comment]
This is not a bug. The old quest has been removed and is replaced by The Legend of Korrak. This is how it was originally in early vanilla, before AV was redesigned and Korrak was removed. Since we've restored the original AV map on turtle, we also restored the original quest.
