### ISSUE TITLE
Aggression Link of Air Elementals in Desolace

### ISSUE THREAD

**Issue by Sudlu** [slowtorta/turtlewow-bug-tracker#2597]
**Please, provide a clear description what the bug is:**

Near the quest giver Smeed Scrabblescrew are air elementals that seemed to be linked with a pack of hyenas and some cultists of the burning blade.

**Steps to reproduce the behavior with as much detail as possible:**

1. Attack an Elemental near the goblin
2. Watch the second elemental and hyenas beeline towards you
3. Wait long enough to see cultists of the burning blade beeline towards you

**IDs of affected creatures, items, quests or spells with a link to the relevant page:**

Location: Near https://database.turtle-wow.org/?npc=11596
NPC: https://database.turtle-wow.org/?npc=11578/whirlwind-shredder
NPC: https://database.turtle-wow.org/?npc=4688
NPC: https://database.turtle-wow.org/?npc=4690
NPC: https://database.turtle-wow.org/?npc=4666    (Unsure about this one. I was killed too quickly to see it and it is not easy as HC to reproduce the problem)

**Expected behavior. Describe how it should work:**

They are not linked and aggro together, as any other elemental, hyena and cultist in the remaining areas of Desolace. They stop chasing you and do not reengage their aggression behavior after running away for multiple minutes.

**Comment by Sudlu** [comment]
Now that there are quests involving killing air elementals in Desolace, it would be mighty fine if that was fixed. Those two elementals with their entourage are just a random death trap for everyone, especially since they are close to the centaur clans, which give out the quests. One is even repeatable, so chances are high that they cost more lives.

**Comment by cyaohiri** [comment]
Very similar behavior was described in #2353.

**Comment by SolarGuru** [comment]
Confirming the issue since Oct 2022 by now. Attacking hyenas chains aggro on Elementals and vice versa.
Same behavior as described in https://github.com/slowtorta/turtlewow-bug-tracker/issues/2353.

**Comment by slowtorta** [comment]
Fixed on the next update.
