### ISSUE TITLE
Loreseeker title.

### ISSUE THREAD

**Issue by Pirell** [slowtorta/turtlewow-bug-tracker#2599]
I have completed 1700 quests and didn't receive the ''Lorekeeper'' title, i opened an ingame ticket and got directed to this thread to report the issue as a bug, thank you again for your time and appreciate any and all feedback on the matter.

Character name = Vaeran, High Elf Priest.

**Comment by slowtorta** [comment]
With the introduction of the new patch, we raised the cap for 2000 quests. I'm sorry, you have to do some more :) Type /time to see your current amount!
