### ISSUE TITLE
Armaments of Battle quests are gone

### ISSUE THREAD

**Issue by tmt01** [slowtorta/turtlewow-bug-tracker#26]
Quartermaster Miranda Breechlock has none of the quests for insignia turn-ins (I'm revered with AD at the moment of writing). I was able to see them before recent patches.

**Comment by tmt01** [comment]
Update: I'm playing a high elf. It seems like some other quests are no longer available to high elves after the update (post-BRD alliance attunement quest https://database.turtle-wow.org/?quest=6402 )

**Comment by slowtorta** [comment]
Thanks for reporting it.
