### ISSUE TITLE
The quest Seal of Ascension can't be completed.

### ISSUE THREAD

**Issue by Tinyfin-github** [slowtorta/turtlewow-bug-tracker#260]
The quest Seal of Ascension can't be completed.

How it should work :  Take the  Unforged Seal of Ascension to Emberstrife , mind control it , create Forged Seal of Ascension return to Scarshield Infiltrator which transforms to  Vaelan.  Talk to Vaelan and complete the quest.

What does not work: After getting the Forged Seal of Ascension  and return to Vaelan , you can  talk with him about his story  but you cannot complete the quest,  He just emotes.

https://database.turtle-wow.org/?quest=4743 Seal of Ascension
https://database.turtle-wow.org/?item=12324 Forged Seal of Ascension
https://database.turtle-wow.org/?npc=10299 Scarshield Infiltrator <Scarshield Legion>
https://database.turtle-wow.org/?npc=10296 Vaelan

**Comment by BobSemple** [comment]
This is actually a bug that was present in the original vanilla. You must have an unadorned seal in your inventory besides the quest items for him to offer the right lines.
