### ISSUE TITLE
(Tel'Abim quest) King Morogo Thunderfoot! - wrong zone in quest log

### ISSUE THREAD

**Issue by Platinumcoated** [slowtorta/turtlewow-bug-tracker#2600]
it's a Tel'Abim bounty board quest, to kill a monkey in Tel'Abim 
("...hunt down King Morogo Thunderfoot, last seen at the heights of Highvale Rise.") - description states

the quest is currently listed under **Felwood** in the quest log

should be listed under **Tel'Abim**, just like other Tel'Abim quests

**Comment by Sringaram** [comment]
The mob is also deep inside of a cave at the mountain's foot, not on top of it.
