### ISSUE TITLE
Incorrect reputation reward for new Tanaris quest Chasing Sand

### ISSUE THREAD

**Issue by Fidget16** [slowtorta/turtlewow-bug-tracker#2605]
**Please, provide a clear description what the bug is:**

See completed request #2601 that I submitted yesterday, I think this is same thing. Reputation currently is Durotar Labor Union, even for Alliance. Should probably be Gadgetzan.

In case I have quest name wrong, this is the quest the other goblin gives, to go out and loot the machine in the broken camp.

**Comment by vkekd** [comment]
Completed doesnt mean fixed, you need to wait for the update to go out

**Comment by Fidget16** [comment]
Yes thats correct.

But this is a different issue. There are two different quests, from two different quest givers. I referenced the first in 2601, this is for the other one, which I had not done at the time I made report 2601, and so I have made I second ticket.
