### ISSUE TITLE
Quest: Chillwind Armor

### ISSUE THREAD

**Issue by Sringaram** [slowtorta/turtlewow-bug-tracker#2607]
Quest ID: it's not in the database.

It's one of the new Tel'Abim quests. The quest in question lacks description and is displayed as "Chillwind E'ko" when linked in chat.

**Comment by slowtorta** [comment]
https://database.turtle-wow.org/?quest=40769

Sounds like an addon bug, please try to disable any quest-related addons and see if it persists.
