### ISSUE TITLE
Unlootable Gifts in IF Winter Veil

### ISSUE THREAD

**Issue by afizzler** [slowtorta/turtlewow-bug-tracker#2608]
I am unable to loot gifts under the tree in Ironforge during Winter Veil. It seems to be a strange problem considering when my friend's account that I can loot gifts while with my main and other guildies of mine that I can't loot gifts with.

**Comment by geojak** [comment]
It seems to me gifts were not reset from last year.

I was able to open the lvl 40 gift only on my paladin this year  because last year I did not reach that lvl at that point yet.
