### ISSUE TITLE
NPC: Highvale Gorilla (Tel'Abim)

### ISSUE THREAD

**Issue by Sringaram** [slowtorta/turtlewow-bug-tracker#2612]
The Bash skill they use (stun) appears to be ranged and seemingly ignores avoidance. There's also no animation for it.

The 5s duration also seems to be a bit over the top.

**Comment by geojak** [comment]
@slowtorta, the issue you linked is about the other gorilla's that use the mentioned stun.

This issue is about the other type of gorilla that use nothing and is not related to the stun issue
