### ISSUE TITLE
land nessy at new zone south theramore

### ISSUE THREAD

**Issue by geojak** [slowtorta/turtlewow-bug-tracker#2613]
**Please, provide a clear description what the bug is:**
![WoWScrnShot_122722_222753](https://user-images.githubusercontent.com/25199983/209724096-b97cb430-ffb0-4e60-9f0c-00dee40c6551.jpg)

**Expected behavior. Describe how it should work:**
 
![WoWScrnShot_122722_222749](https://user-images.githubusercontent.com/25199983/209724102-96d1f611-0c00-46c7-a387-0e58200a34c3.jpg)
![WoWScrnShot_122722_222751](https://user-images.githubusercontent.com/25199983/209724104-a3cfe9de-a26e-49ea-bb77-239a7eb06edf.jpg)

![WoWScrnShot_122722_222752](https://user-images.githubusercontent.com/25199983/209724106-1df764a5-3e16-4a6f-8361-9f221754e49e.jpg)

**Comment by geojak** [comment]
probably needs a new spawn point?

**Comment by slowtorta** [comment]
Fixed on the next update.
