### ISSUE TITLE
quillboar suspcet wrong location in qeust text

### ISSUE THREAD

**Issue by geojak** [slowtorta/turtlewow-bug-tracker#2614]
**Please, provide a clear description what the bug is:**

quillboar suspect new qeust for the burned in qeust says in the qeust text go look north of razorfen downs.

but actually the camp is north of razorfen downs.

**Expected behavior. Describe how it should work:**

acurat description in qeust text. wastes me and a fried quiet some time and frustration that is not necessary. we would appreciate a fix for future players

**Comment by geojak** [comment]
![WoWScrnShot_122722_230950](https://user-images.githubusercontent.com/25199983/209726783-f51f99b5-9fba-492f-b761-d2a7957b85fb.jpg)
![WoWScrnShot_122722_230954](https://user-images.githubusercontent.com/25199983/209726788-260e0dd0-a663-415c-8a02-c17a389105c5.jpg)
locked for almost an hour

**Comment by redmagejoe** [comment]
To clarify somewhat on this bug report, the quest mentions a camp just off the road north of Razorfen Kraul, when in reality, it should mention that it is north of Bael Modan.
