### ISSUE TITLE
LFT selecting incorrect roles

### ISSUE THREAD

**Issue by Hawksford** [slowtorta/turtlewow-bug-tracker#262]
LFT is automatically queuing me as a healer in, if I select damage it queues me as damage and healer (I'm playing Warlock) despite saying "your class cannot do this role" for healing.

**Steps to reproduce the behavior with as much detail as possible:**

1. Used LFT several times, always happens
2. 
3. 

It should just queue me for my selected role and not ones I'm not capable of.

Great server otherwise!

Regards

**Comment by CosminPOP** [comment]
Type `/run LFT_ROLE = "damage"`

**Comment by Hawksford** [comment]
Seems to have done the trick, thank you!!
