### ISSUE TITLE
Arcane Missiles can be cast on dead targets

### ISSUE THREAD

**Issue by RUTHINAS** [slowtorta/turtlewow-bug-tracker#2623]
**Please, provide a clear description what the bug is:**

Arcane Missiles can be cast on dead targets. The channel starts and progresses for the first second (until the initial tick) and is then stopped. However, mana is already spent at the start of the channeling. For pretty much every other spell, there would be a fizzle sound effect and a red "Invalid target" text at the top of the screen.

I tested this with Arcane Missiles ranks 1, 2 and 3. I do not currently have access to further ranks.

**Steps to reproduce the behavior with as much detail as possible:**

1. Find a dead enemy, or slay one.
2. Target the dead body.
3. Cast Arcane Missiles. Observe the mana spent, observe the channeling bar.

**IDs of affected creatures, items, quests or spells with a link to the relevant page:**

Spell: https://database.turtle-wow.org/?spell=5145

**Expected behavior. Describe how it should work:**
The "Invalid target" error text should pop up as the button is pressed. No mana should be used, and casting should not be started in the first place.

**Comment by SolarGuru** [comment]
Confirming the issue on all ranks of Arcane Missiles. Cast can be started on dead enemies, lasts for 1 sec then breaks, mana still drained.
I believe there is the same bug with all channeling targeting spells (priest's Mind Flay), but I didn't check it.
