### ISSUE TITLE
Targeting issues, hard to reproduce

### ISSUE THREAD

**Issue by RUTHINAS** [slowtorta/turtlewow-bug-tracker#2624]
**Please, provide a clear description what the bug is:**
Upon targeting a unit (the intended target) in the game world (by clicking on their model), the game sometimes targets another one with the exact same name (the eventual target). It isn't always apparent at first, until the player walks close enough to the intended target to start casting/attacking, but the game gives an "Out of range" error. The intended and eventual target need not be close to one another, and the eventual target is not necessarily even in the player's field of vision (as if they had clicked on a unit off-screen). I have gotten the bug with some regularity, estimating around a dozen incidents per month, and it always seems to pick a target with the same name. The level may be different, as can be the gender of the unit (as far as I know; name, level and gender are the factors used to "identify" targets before the introduction of unit ID numbers). It seems like the game is running a /target <name> script behind the scenes.

It becomes apparent in instances when a pet class sends their pet to a unit they _thought_ was the target everyone in the group was attacking, and the pet ends up pulling an extra pack by going around a corner to attack a group not visible to the party. 

This bug seems to pop up every now and then, but I have not yet discovered a way to reproduce it. Having talked to people about it, some have also noticed the issue popping up, whereas others couldn't say if it had happened to them.

**Expected behavior. Describe how it should work:**
Targeting a unit by clicking on its model in the world should always set the target as that particular unit.

**Comment by jameyboor** [comment]
This is a client inconsistency and is not something we can fix.
