### ISSUE TITLE
Chest in Temple of Zin-Malor, Azshara can not be opened by players in a reasonable level range

### ISSUE THREAD

**Issue by RUTHINAS** [slowtorta/turtlewow-bug-tracker#2628]
**Please, provide a clear description what the bug is:**
There is a Large Solid Chest on the second layer of the Temple of Zin-Malor, Azshara, that was out of my level range while I was questing in the area.

I understand it is intended for chests to be opened by players in a certain level range, and that makes perfect sense to me. However, since quest givers can give me quests to the area where the chest is, and I am able to defeat the mobs guarding it, I think it should be reasonable for me to open the chest as well. The excitement of seeing a chest in the distance, and fighting one's way to it turned into a bitter disappointment, when neither I or my friend could open it, at levels 47 and 46. I don't think it's a good user experience.

**IDs of affected creatures, items, quests or spells with a link to the relevant page:**
Object: https://database.turtle-wow.org/?object=153464

**Expected behavior. Describe how it should work:**
I don't expect the level requirement for chests to be lifted entirely, but it would make sense to me that the players questing in the area would be able to open them. Perhaps Azshara chests ought be openable by those level 45 and above, as that is pretty much the level one starts getting quests there.

**Comment by slowtorta** [comment]
We'll lower it from 52 to 47.
