### ISSUE TITLE
Unlootable Tel'abim bananas

### ISSUE THREAD

**Issue by Sringaram** [slowtorta/turtlewow-bug-tracker#2631]
The bananas at the Southeastern island seem to become unlootable to everybody.

**Comment by slowtorta** [comment]
Are you talking about quest bananas? They are supposed to be unlootable once the quest is complete.

**Comment by Sringaram** [comment]
Are they different bananas? They look the same on the ground as those you need for food.

**Comment by geojak** [comment]
They are special bananas according to the quests. Maybe they sjoild have weird color to indicate it

**Comment by slowtorta** [comment]
Quest bananas seem to work as intended.
