### ISSUE TITLE
Danonzo's Tel'abim Medley (haste food)

### ISSUE THREAD

**Issue by Sringaram** [slowtorta/turtlewow-bug-tracker#2632]
The recipe requires an Essence of Air which seems to be a mistake. Maybe it was meant to be Elemental Air?

This makes this food like forty times more expensive than the other two since the airs go for 5-6g on average and that's ridiculous for a single piece of food.

**Comment by slowtorta** [comment]
This is the intended design. 2% haste buff is much more valuable than other two.

**Comment by Sringaram** [comment]
The best by far food out of the three is the RAP one since it provides a massive boost to the class while also being a massive upgrade to what they could use before (10 AGI). It is also infinitely cheaper.
The haste food is by far the most expensive consumable in the game when you account the small effect, the duration and the fact that it's gone on death. Even the most expensive elixirs are like half the price while lasting thrice as long, and all other food is much, much cheaper.
There isn't anything particularly stellar about 2% haste and it's a common bonus we can see on many custom items.

So far this food is just wasted potential and you can see how there's no market for it either. It's just people selling the single one they got from completing the quest.
