### ISSUE TITLE
Azshara quest The Search for the Blade has a level inaccuracy

### ISSUE THREAD

**Issue by RUTHINAS** [slowtorta/turtlewow-bug-tracker#2633]
**Please, provide a clear description what the bug is:**
The quest The Search for the Blade is marked as a level 52 quest. The large group of mobs protecting the quest object are level 55, take a long time to kill and have a relatively short respawn timer. Getting the item is extremely difficult, as the mobs seem to spawn while the player is still clearing the other ones.

**IDs of affected creatures, items, quests or spells with a link to the relevant page:**

Quest: https://database.turtle-wow.org/?quest=40286

**Expected behavior. Describe how it should work:**
The quest should be properly marked as level 55, showing up red to players too low to succesfully complete it.

**Comment by slowtorta** [comment]
This is intended. We'll up the quest level to be properly highlight in red as a dangerous one. Can't have too large gaps between quests in a chain, else many people might never notice that it continues.
