### ISSUE TITLE
gravelhide bassiliks on telabim are unable to move

### ISSUE THREAD

**Issue by geojak** [slowtorta/turtlewow-bug-tracker#2635]
**Please, provide a clear description what the bug is:**

when you engange comba with these they will evade and not move a single step
over mobs didnt seem to have thos problem

**Expected behavior. Describe how it should work:**

when i back of from a bassilik on combat they should follow

**Comment by slowtorta** [comment]
Please stop reporting mmaps issues for every single mob. It's a general bug.
