### ISSUE TITLE
Reproduceable cases for newest mmap's bug. 

### ISSUE THREAD

**Issue by slowtorta** [slowtorta/turtlewow-bug-tracker#2636]
Please do not report pathing issues for every single creature in the world, we are aware of the issues and working on it.

gravelhide bassiliks on telabim are unable to move #2635

Quest: The Balance of Light and Shadow - Injured Peasant's Pathtracking Bugged #2629

Lieutenant Alverold out of combat bug #2622

Paladin Danuvis on Anchor's Edge won't move #2621

Anchor's Edge Expedition Officer NPC will not move on aggro #2617

Impossible to use "Charge" Warrior spell on Anchor's Edge dock #2616

Anchor's Edge NPC clips through house #2615

Crystal mine  near Alah'Thalas, go figure, all the mobs are flying above.

Players are having trouble sometimes  lotting mobs if hey die underwater 

shay leaf runner can randomly bug during the escort and go mountain  climbing..

The Barrens - Achor's Edge #2620

**Comment by slowtorta** [comment]
Crystal mine in near Alah'Thalas, go figure, all the mobs are flying above.

**Comment by slowtorta** [comment]
bug in fel rock #2586

**Comment by slowtorta** [comment]
Anchor's Edge NPCs aggro through walls #2619

**Comment by slowtorta** [comment]
Anchor's Edge difficult to attack NPC #2618

**Comment by slowtorta** [comment]
**Investigate root cause of mobs that have patrol paths, mostly city guards, entering a sprinting state permanently while not in combat. This is still visible on live as recently as yesterday.**

**Comment by slowtorta** [comment]
https://github.com/slowtorta/turtlewow-bug-tracker/issues/2661

**Comment by slowtorta** [comment]
Malfunctioning Arcane Constructs On Mountain #2729

**Comment by slowtorta** [comment]
https://github.com/slowtorta/turtlewow-bug-tracker/issues/2831

**Comment by slowtorta** [comment]
https://github.com/slowtorta/turtlewow-bug-tracker/issues/2849

**Comment by rodolfo-santos-meta** [comment]
#3039
