### ISSUE TITLE
New sheild added, accidentally marked as offhand

### ISSUE THREAD

**Issue by Zebouski** [slowtorta/turtlewow-bug-tracker#2643]
Please, provide a clear description what the bug is:

https://database.turtle-wow.org/?item=60950
From a horde quest. All classes can equip this even druids and clothies.

Expected behavior. Describe how it should work:
Tag it as a as shield not offhand

**Comment by ratkosrb** [comment]
https://github.com/slowtorta/turtle-wow/commit/eb1a2d39c136ba1e2326c97a290bdf5b9113a50b
