### ISSUE TITLE
Sometimes mage can't cast fire spells 

### ISSUE THREAD

**Issue by valentynpozniakov** [slowtorta/turtlewow-bug-tracker#2646]
**Sometimes mage can't cast fire spells due to Invalid target error on some mobs**

**Steps to reproduce the behavior with as much detail as possible:**

1. Faced an issue by myself in DME (see screenshot)
2. Yesterday in a raid (Zul Gurub) mage were not able to do fire spells at all

![image](https://user-images.githubusercontent.com/67410840/210232907-4e8493d9-07ad-4c39-a25c-3f56daeec458.png)

**Comment by SolarGuru** [comment]
Playing fire mage since Sep 2022 from lvl 1 to AQ40, fire spells never been an issue of that kind for me.

**Comment by valentynpozniakov** [comment]
> We can't reproduce this bug w/o directions on when or how it breaks.

Idk what happened, same was in AQ40 on C'tun this week... in guild said that SHIFT+ALT helps, so after I pressed these buttons issue was fixed.

**Comment by cyaohiri** [comment]
> > We can't reproduce this bug w/o directions on when or how it breaks.
> 
> Idk what happened, same was in AQ40 on C'tun this week... in guild said that SHIFT+ALT helps, so after I pressed these buttons issue was fixed.

This sound like the issue of Alt staying pressed after using Alt + Tab to switch to the game. Simply pressing and releasing it fixes the issue. The reason you see the "Invalid target" error is because you are trying to cast those spells at you, as Alt is usually used to force self casting.

**Comment by valentynpozniakov** [comment]
> > > We can't reproduce this bug w/o directions on when or how it breaks.
> > 
> > 
> > Idk what happened, same was in AQ40 on C'tun this week... in guild said that SHIFT+ALT helps, so after I pressed these buttons issue was fixed.
> 
> This sound like the issue of Alt staying pressed after using Alt + Tab to switch to the game. Simply pressing and releasing it fixes the issue. The reason you see the "Invalid target" error is because you are trying to cast those spells at you, as Alt is usually used to force self casting.

Thanks, now it's clear.
