### ISSUE TITLE
A Fine Mess / Kernobee

### ISSUE THREAD

**Issue by Nadare76** [slowtorta/turtlewow-bug-tracker#265]
**Please, provide a clear description what the bug is:** After picking up the quest, Kernobee and his robot started following the person who picked the quest, but as we entered a tunnel, they both disappeared. No idea if the quest would still be complete-able or anything, we were on HC and bailed out to reset to avoid them pulling a bunch of mobs from somewhere else or anything.

**Steps to reproduce the behavior with as much detail as possible:**

1. Take the quest (With a goblin who has tried to use the bugged B terminal, for the punch cards, if it matters)
2. Start going through the tunnel towards the Electrocutioner 6000

**IDs of affected creatures, items, quests or spells with a link to the relevant page:**

NPC: https://database.turtle-wow.org/?npc=7850
Quest: https://database.turtle-wow.org/?quest=2904

**Expected behavior. Describe how it should work:** They should stay with the person they're following.

**Comment by slowtorta** [comment]
I could not reproduce it. Is this still happening?

**Comment by Nadare76** [comment]
No idea, sorry.

**Comment by slowtorta** [comment]
Currently, 3428 players got this quest completed and rewarded, so I assume it's working :)
