### ISSUE TITLE
Rare Zeppelin collision outside of Orgrimmar

### ISSUE THREAD

**Issue by RUTHINAS** [slowtorta/turtlewow-bug-tracker#2650]
**Please, provide a clear description what the bug is:**
The Kargath zeppelin collides with another one during its return journey at the Orgrimmar end. This is likely an issue that only occurs when the timings line up just right. The collision can cause players to fall out of the zeppelin. I'm not sure which zeppelin it collided with, or whether said zeppelin was arriving or departing. I would think it to be very annoying, however, if one were to be ejected from their zeppelin upon departure, not so much when arriving.

**Steps to reproduce the behavior with as much detail as possible:**

1. Board the Kargath zeppelin
2. Travel the route (probably several times, the frequency of this bug is not known to me)
3. Experience the midair collision

**Expected behavior. Describe how it should work:**
The routes or the timings of the zeppelins should be adjusted so that a collision is not possible. If the two zeppelins that are prone to colliding were to be timed so that their arrival and departure is always exactly the same in relation to one another, the collision incident could be avoided. Currently the timings drift, leading to the two zeppelins being in the same location at the same time occasionally. Synchronizing the timings by adjusting departure delays could be more easily achieved than changing the pathing.

**Comment by slowtorta** [comment]
This is what happens when you let them fly w/o a crew!

**Comment by Rangtuk** [comment]
TB zep most likely, Kargath zep takes a wide turn towards barrens, directly in line with the way TB zep leaves

**Comment by RUTHINAS** [comment]
I was departing recently on the Undercity zeppelin when another one clipped right through. Based on the location, I'm pretty certain it was the arriving Kargath zeppelin again, as it comes in from the direction of the sea.
