### ISSUE TITLE
Winter Veil Branch transmog

### ISSUE THREAD

**Issue by testening** [slowtorta/turtlewow-bug-tracker#2655]
**Please, provide a clear description what the bug is:**

Winter Veil Branch doesn't unlock its t-mog on equip.

**Steps to reproduce the behavior with as much detail as possible:**

1. acquire weapon
2. equip it
3. see no transmog unlock popup
4. check fashionista
5. transmog not on the 2h list

**IDs of affected creatures, items, quests or spells with a link to the relevant page:**

Item: (https://database.turtle-wow.org/?item=61087)

**Expected behavior. Describe how it should work:**

1. acquire weapon
2. equip it
3. see transmog unlock popup
4. check fashionista
5. transmog is on the 2h list

I have (https://database.turtle-wow.org/?item=15226) unlocked, which is the same model but 1h. Maybe Winter Veil Branch is unlocking the 1h version of the transmog instead?

**Comment by slowtorta** [comment]
![image](https://user-images.githubusercontent.com/66763404/211394813-f1fa56b1-ce03-48ea-84a9-2081b9c0e16e.png)
Working as intended! You probably already know this item appearance :)
