### ISSUE TITLE
Resetting the rank and rank after joining the guild

### ISSUE THREAD

**Issue by EveqMiner** [slowtorta/turtlewow-bug-tracker#2656]
Hello. My name is Michael. Game account Harnik. Today my rank was reset after joining Guild. Where did rank 6 go?

**Comment by EveqMiner** [comment]
![HARNIK](https://user-images.githubusercontent.com/121969304/210619366-71dd7bb8-6147-490d-9e22-33a04c432fa4.jpg)

**Comment by EveqMiner** [comment]
6th rank received this morning. The strip of the 6th rank was half. Now everything is 0 ((

**Comment by slowtorta** [comment]
Fixed in the next update.
