### ISSUE TITLE
AV mobs bug

### ISSUE THREAD

**Issue by Madliv21** [slowtorta/turtlewow-bug-tracker#2657]
**Please, provide a clear description what the bug is:**
Instead of one unit type spamming, patrols contain all the four types
**Steps to reproduce the behavior with as much detail as possible:**

1. Join AV
2.  Walk in the middle of map/ near towers
3.  Get Zerged by 500 mobs.

**Expected behavior. Describe how it should work:**

Just one unit type.
![29dc971573bb8440f64f311f862055e7](https://user-images.githubusercontent.com/38496780/210619712-827ab3c7-1c2a-4707-aff2-7d0875995f44.png)

**Comment by ratkosrb** [comment]
Already solved internally. Will be fixed once server is updated.
