### ISSUE TITLE
gnomes missing at entrance elevator gnomergan

### ISSUE THREAD

**Issue by geojak** [slowtorta/turtlewow-bug-tracker#2659]
**Please, provide a clear description what the bug is:**

when you take the elevator down right after entering gnomergan from dun morgoth, you enter a hallway that on twow is compeltey empty.

this is not corrrect, there should be mobs, and sometimes random gnomes appear that run for the lift in groups and shout some emotes.

**Expected behavior. Describe how it should work:**

this is the best video proof i could find. watch 1.30-2.45 minutes to see all the missing mobs, its from tbc classic
https://www.youtube.com/watch?v=0x54Bw3Fctw

**Comment by geojak** [comment]
i think a handfull of troggs right at the crossing are missing too, you seem them from 2.45-3.10

**Comment by slowtorta** [comment]
Please provide entries for the missing NPCs.

**Comment by geojak** [comment]
hi torta, how would i do that and in which form? like coordiantes? i have never developed vmangos

**Comment by geojak** [comment]
https://www.wowhead.com/classic/npc=7843/gnomeregan-evacuee
