### ISSUE TITLE
Crit chance lowered in druid forms

### ISSUE THREAD

**Issue by Affict** [slowtorta/turtlewow-bug-tracker#2663]
Noticed that i'm having very rare crits in cat form. I can't figure out when it started, half a level at least. 
Crit chance is remain to be the unchanged in all druid forms.
I had ~13% crit chance before the bug as i remember and also I asked a druid player of my lvl - he had around 12%.

Talent reset didnt help.
I tried to relog / turn off all addons / cleared WDB

**Expected behavior. Describe how it should work:**
Crit chance in druid forms is unaffected by weapon skill and should be around 12-20% with all gear
![Uploading 3.PNG…]()
<img width="931" alt="2" src="https://user-images.githubusercontent.com/122057397/210888288-6bdd4229-c4bf-4dfd-9949-381772a94fab.PNG">
<img width="918" alt="4" src="https://user-images.githubusercontent.com/122057397/210888263-4bd0b2bc-0223-45d1-b41a-e2eacd4327e1.PNG">

**Comment by welpenhund** [comment]
In your first screenshot you wear full gear.
In second screenshot you dropped all the gear (different hp + it shows even in your bags that you unequipped the gear, ofc your crit is lower then)

**Comment by AkalixFrost** [comment]
Cannot reproduce. If you are able to reproduce, please provide clear video evidence or documentation on how.
