### ISSUE TITLE
Kul'tiran mobs counterattack all pickpocket attempts

### ISSUE THREAD

**Issue by Slimthegrim** [slowtorta/turtlewow-bug-tracker#2664]
**Please, provide a clear description what the bug is:**
Pickpocketing the new Kul'tiras mobs named "Expedition Soldier" has an unexpected "feature". They counterattack 100% of the time when pickpocketing successfully. 

**Steps to reproduce the behavior with as much detail as possible:**

1. Be rich gobbo ... or maybe just be a rog.
2. Goto Anchor's Edge Island
3. Pickpocket any mob named Expedition Soldier, chaching when you loot successfully
4. Surprise! Mob counter attacks despite you never breaking stealth, not being too close, and not having a resist. 

**IDs of affected creatures, items, quests or spells with a link to the relevant page:**

NPC: https://database.turtle-wow.org/?npc=60897
https://database.turtle-wow.org/?npc=60896
https://database.turtle-wow.org/?npc=60902

**Expected behavior. Describe how it should work:**
Should work like any other normal humanoid mob with pickpocketing given stealth never breaks, and you gain money from the pickpocket. At minimum you should get an interaction and be detected and fail the pickpocket if the mob is intended to be immune or something.

**Comment by Slimthegrim** [comment]
These too: https://database.turtle-wow.org/?npc=60894

**Comment by Slimthegrim** [comment]
Geh I hate these buttons, unintended close ❌

**Comment by Dormilon** [comment]
The problem has not been identified. The ability is working correctly. Tested as a level 17 rogue in stealth rank1.
