### ISSUE TITLE
The Forging of Quel'Serrar

### ISSUE THREAD

**Issue by SignOfTheRaven** [slowtorta/turtlewow-bug-tracker#2665]
**Unfired ancient blade disappeared**

**Steps to reproduce the behavior with as much detail as possible:**

1. Get unfired ancient blade by starting the diremaul quest chain.
2. place sword on ground and let onyxia breath on it during her phase 3.
3. sword turned red from the flames, we killed onyxia, onyxia fell on the sword when killed, and the sword could not be recovered.

**Unfired ancient blade; Onyxia raid boss**

NPC: https://www.wowhead.com/classic/npc=10184/onyxia
Item: https://www.wowhead.com/classic/item=18489/unfired-ancient-blade
Quest: https://www.wowhead.com/classic/quest=7509/the-forging-of-quelserrar
Spell: https://database.turtle-wow.org/?spell=
Object: https://database.turtle-wow.org/?object=

**After the blade is dropped on the ground, Onyxia breaths fire onto it. Once she is defeated, you pick up the blade and stab it into her. However my sword disappeared and could not be recovered to stab into Onyxia. I thought I had screenshots, but I do not. My screenshot folder is empty after the most recent update.**

**Comment by SignOfTheRaven** [comment]
If any more information is required, please ask.

**Comment by geojak** [comment]
It worked for me somehow. You just gotta loot imidielty after she breathed even during combat

**Comment by SignOfTheRaven** [comment]
> It worked for me somehow. You just gotta loot imidielty after she breathed even during combat

Well that's good to know. At least it works. Wowhead mentioned it stays there for awhile, so I didn't think it would disappear that quickly. Guess I gotta wait until another week to try again...
