### ISSUE TITLE
Raid display not showing

### ISSUE THREAD

**Issue by Maiyus** [slowtorta/turtlewow-bug-tracker#2667]
I'm relatively new to TurtleWoW, so I don't know if this is intended or not, but I am missing the raid display that used to be in normal WoW every time I'm in a raidgroup here.
In other words, there are no health/status bars for the whole raid showing, only the normal ones for my own group.

Obviously this is a huge problem when you need to heal members of groups other than your own.

Here is a picture of the 'typical' raid display I used to have in retail WoW and that I wonder why is missing here in TurtleWoW:
![raid interface](https://user-images.githubusercontent.com/121011603/211167372-4eef5a50-3609-409b-9b07-f13acafedb38.jpg)

Here is a picture of my current situation whenever I'm in a raid group in TurtleWoW:
<img width="960" alt="raid display missing (Turtle WoW)" src="https://user-images.githubusercontent.com/121011603/211167507-ba0aab40-3e9f-408c-9c27-b209ac3a74a8.png">

Is this intended, or is there a setting I need to activate/add on I need to download?

Thanks in advance.

**Comment by Otari98** [comment]
There are raid frames in vanilla, but you have to manually drag them out everytime you join the raid, so the best way is to download addon like LunaUnitFrames or Xpearl or something along those lines.

**Comment by Maiyus** [comment]
Thank you.

I have heard it mentioned before about "dragging them manually", but whenever I press (O) and go to the raid tab and so try to "drag" the player names out of the box onto the screen...they are not moving. They are locked and nothing happens, like trying to move a mountain. So exactly how should I do this?

**Comment by Maiyus** [comment]
Bump.

Isn't there TurtleWoW representative that answers these posts?
GM told me as response to my in game ticket to make a thread here, and I did.

**Comment by Kruxis** [comment]
Greetings Maiyus!

We do not always respond. We got several open issues and work on them one by one. Please be patient about it as we have to look into that.

For now, do you use any Addons? If yes, which?

**Comment by Maiyus** [comment]
I would have wanted to play this game as I usually do - without any add ons, but it seems its not possible when in a raid and you need knowledge about other players than those in your own party.
I tried Pfui and LunaUnit, but quickly abandoned them both as the original rustic display and the feeling that goes with it dissapeared completely.
Anyway, it seems the best way to keep the display as it originally is and this be able to function as a healer in a raid in TurtleWoW is to install/use Healbot, and so that I now have.
Thanks for checking into the thread anyhow.
Maiyus

**Comment by slowtorta** [comment]
Please check this thread for some additional options: https://forum.turtle-wow.org/viewtopic.php?t=874
