### ISSUE TITLE
v1.16.5 (7060) startup bug on ARM M1 & no ADDONs capability

### ISSUE THREAD

**Issue by markusfrobinson** [slowtorta/turtlewow-bug-tracker#2669]
1) Performed a vanilla install of twmoa_1165.zip on Apple ARM M1 machine running Parallels Version 18.1.1 (53328) on Windows 11.
2) Log in to Turtle WOW with my standard character name and password, get to screen Alleta 'Enter World'
3) Upon entering Azamoth, popup error message reports "Interface\FrameXML\UIDropDownMenu.iua: 156: attempt to concatenate global 'UIDROPDOWNMENU_OPEN_MENU' (a nil value)" along with the popup's 'Okay' click button.
4) Clicking the latter, superficially things seem to operate correctly.  However, no ADDONS are ever recognized, nor are ADDONS like Healbot loaded into /Users/markusfrobinson/data/DOCS/Devices/Computers/MACs/VM (PC Emulation Environment)/Apps/Turtle WOW/twmoa_1165/Interface/AddOns/HealBot ever recognized, despite them being installed in the directory automatically created by the ZIP file uncompress.  (which loaded your /Users/markusfrobinson/data/DOCS/Devices/Computers/MACs/VM (PC Emulation Environment)/Apps/Turtle WOW/twmoa_1165/Interface/AddOns/LFT by default in that directory.)

**Steps to reproduce the behavior with as much detail as possible:**

1. See above...

**Expected behavior. Describe how it should work:**

1) No error message at startup...
2) Add ons working (if in fact this is the same issue)

Thank you folks!  Markus Robinson (markusfrobinson@gmail.com)

Happy to let a debugger view my desktop to help diagnose the problem.  Just contact me...

**Comment by Kruxis** [comment]
Greetings traveller! 

Would you mind joining our Discord for further instructions and troubleshooting? Bit rough texting on Github ^^'
Discord: https://discord.gg/UferuVDX

**Comment by Kruxis** [comment]
To make sure your addon works on our server check this link: https://forum.Turtle-WoW.org/viewtopic.php?f=18&t=874

Make sure that when you place the addon in intercace/Addons/ that the Addon doesn't have a master-<name> infront of it.
For example (healbot) and not (master-healbot)
