### ISSUE TITLE
wandering forest walker not wandering

### ISSUE THREAD

**Issue by geojak** [slowtorta/turtlewow-bug-tracker#2673]
**Please, provide a clear description what the bug is:**

in feralas exst wandering forest walker tree npcs that should patrol around.
they dont. the one i found is standing around behind the temple of isilidien

https://database.turtle-wow.org/?npc=7584

**Expected behavior. Describe how it should work:**
 should patrol the zone
https://www.wowhead.com/classic/npc=7584/wandering-forest-walker

**Comment by geojak** [comment]
possibly related to https://github.com/slowtorta/turtlewow-bug-tracker/issues/1047

**Comment by redmagejoe** [comment]
Of the 5 which exist, only the one mentioned is static. Whether this is intentional or not, I do not know.

**Comment by Herdon** [comment]
Just want to mention that the Wandering Forest Walker who is behind Isildien is static. 
![wf](https://user-images.githubusercontent.com/2021593/230790106-fa3d6065-f069-496b-b427-385c0e537386.jpg)

On WoWhead (Classic) you can find his patrol route.
https://www.wowhead.com/classic/npc=7584/wandering-forest-walker
