### ISSUE TITLE
Rank 1 Rockbiter Weapon gives too much AP

### ISSUE THREAD

**Issue by Kangaroux** [slowtorta/turtlewow-bug-tracker#268]
Ability text says it increases AP by 29 but it actually increases it by 49. Rank 2 correctly increases AP by 58.

**Comment by Tinyfin-github** [comment]
Bug confirmation:

Rockbiter Weapon rank (1)  https://database.turtle-wow.org/?spell=8017

https://user-images.githubusercontent.com/83077166/143668901-7019c95a-433e-406b-b7f2-b72ed3e4f6b5.mp4

**Comment by Tinyfin-github** [comment]
Greetings!  I have checked and have been unable to find any issues.  Please update with more information, screenshots or videos that show us how to reproduce the bug and sources that show the correct behavior.

All spells scale with level. The tooltip won't show the scaling but the formula will be applied correctly upon use.

Rockbiter Weapon (rank 1)  https://database.turtle-wow.org/?spell=8017

https://user-images.githubusercontent.com/83077166/143674639-be6072c9-9792-43bb-b5f8-78daa0142bc6.mp4

Same behavior with Rockbiter Weapon (rank 2) https://database.turtle-wow.org/?spell=8018  and any other ranks of rockbitter

https://user-images.githubusercontent.com/83077166/143674719-586a1de7-bd65-4151-8cd0-e8bd21fd142d.mp4
