### ISSUE TITLE
Hunter pet Avoidance not in the game

### ISSUE THREAD

**Issue by Fierce666** [slowtorta/turtlewow-bug-tracker#2688]
my pet wolf does not have avoidance since the patch where pets talent points got fixed. it used to be in the pets spellbook. apparently some pet families have it, while others dont. as proof i just tamed a little boar, on which i found avoidance in its spellbook. im linking a screenshot of that. my wolfs screenshot is in here too. other ppl on the hunter disc also have an issue with wolves and avoidance. apparently cats and boars have avoidance, while wolves and wind serpents dont.
![WoWScrnShot_011123_214208](https://user-images.githubusercontent.com/116917937/211914538-8d8d23f6-6676-4c20-a133-bf4196c8658d.jpg)
![WoWScrnShot_011123_214348](https://user-images.githubusercontent.com/116917937/211914569-d29cca1e-d467-469c-9b16-1bfba2518ca7.jpg)

**Comment by bankmasta** [comment]
Fox pet does also not have avoidance.

**Comment by cawilliamson** [comment]
Any update on this?

Since the pet accounts for a huge part of the Hunter's overall damage and you were super quick to implement the "pet abilities don't consume TP" issue - this is a major PITA.

As an example yesterday in a BWL raid I had to res my pet around 15 times *with* max fire resistance talented. It's a bit ridiculous to be honest and really destroys the fun of raiding on a Hunter.

**Comment by Kazar808** [comment]
I would also love an update :) my bear too is missing the skill. Thx <3

**Comment by Pati3ntZer0** [comment]
The eagle from the Revantusk rep area does not have it either.  The location where you have to talk to the orgrimmar mages to portal to.

**Comment by slowtorta** [comment]
https://github.com/slowtorta/turtlewow-bug-tracker/issues/2701

**Comment by slowtorta** [comment]
@jameyboor

**Comment by slowtorta** [comment]
https://github.com/slowtorta/turtlewow-bug-tracker/issues/2690

**Comment by slowtorta** [comment]
https://github.com/slowtorta/turtlewow-bug-tracker/issues/3100

**Comment by slowtorta** [comment]
https://github.com/slowtorta/turtlewow-bug-tracker/issues/2996
