### ISSUE TITLE
Cant Get World Buffs in Org,

### ISSUE THREAD

**Issue by Firbolg00** [slowtorta/turtlewow-bug-tracker#2689]
**i noticed a while a ago i couldnt get Wolrd buffs in org i made a ticket ingame GM told me to be more specific when buff came, the last Wolrd buff was nefarian at 09:19 server time so i made another ticket and GM asked me to put it here:**

**all my chars can get the buff xpet for my priest named Firbolg**

1.
2. 
3. 

**IDs of affected creatures, items, quests or spells with a link to the relevant page:**

NPC: https://database.turtle-wow.org/?npc=
Item: https://database.turtle-wow.org/?item=
Quest: https://database.turtle-wow.org/?quest=
Spell: https://database.turtle-wow.org/?spell=
Object: https://database.turtle-wow.org/?object=

**I have 3 accounts and only happens to my Priest named Firbolg:**

**Comment by slowtorta** [comment]
I'm sorry, but this report does not contain any information that can be used to reproduce the bug.
