### ISSUE TITLE
Seal of command no longer triggers judgement of wisdom/light or Black grasp of the destroyer

### ISSUE THREAD

**Issue by Velite12** [slowtorta/turtlewow-bug-tracker#269]
All 5 ranks of seal of command are not triggering judgement of wisdom, judgement of light, nor the glove item Black grasp of the destroyer's 8 mana on hit proc. They no longer do this as of August 23 when I was testing, they did in the past.

Spell: https://database.turtle-wow.org/?spell=20424

**Comment by Nolin7777** [comment]
Possible fix has been applied, please test after next maintenance.
