### ISSUE TITLE
Pet skills missing

### ISSUE THREAD

**Issue by jessiphile** [slowtorta/turtlewow-bug-tracker#2690]
![image](https://user-images.githubusercontent.com/82982786/211929233-f1f197d7-7cde-4b32-ac95-0b28c2dec8ac.png)

I tamed a Longsnout shortly after taming another, different boar, but the only spell it had already was Avoidance. I can't train Growl at a trainer and only unavailable higher ranks show up. Unlike the first boar, it also doesn't have the Charge ability, which the first one did immediately, and is also not available at a trainer as far as I know. 

NPC: https://database.turtle-wow.org/?npc=119
Spell: https://database.turtle-wow.org/?spell=1853

**Comment by rodolfo-santos-meta** [comment]
![image](https://user-images.githubusercontent.com/95623301/227101493-f242d365-bc4a-453b-b6f6-67a89496f7e5.png)
Can we reopen this one?

Just tamed a Deepmoss Venomspitter and it didn't came with any abilities, just **Avoidance**
`NPC: https://database.turtle-wow.org/?npc=4007`

Taming a Deepmoss Creeper comes with the ability **Bite**, but I don't learn it to teach to other pets after using it
`NPC: https://database.turtle-wow.org/?npc=4005`

Or do I have to open a issue for every pet?
