### ISSUE TITLE
Controllable Escort not completing upon finish line

### ISSUE THREAD

**Issue by Nelenora** [slowtorta/turtlewow-bug-tracker#2691]
Bug: The escorted NPC doesn't recognize the area where it's supposed to finish, continues to follow player. 

![bild1](https://user-images.githubusercontent.com/122533554/212068966-e13d979c-b83f-4ac4-873b-79cf5d10cdb3.png)
NPC: https://database.turtle-wow.org/?npc=11218
Item: https://database.turtle-wow.org/?item=13536
Quest: https://database.turtle-wow.org/?quest=5321

Another controllable escort that didn't trigger the event upon the finish line:

![bild2](https://user-images.githubusercontent.com/122533554/212069108-bc278d8f-c66c-4fe9-86df-6f2221630eb3.png)

NPC: https://database.turtle-wow.org/?npc=6669
Item: https://database.turtle-wow.org/?item=7442
Quest: https://database.turtle-wow.org/?quest=2078

**Comment by slowtorta** [comment]
I believe this one was fixed two weeks ago.
