### ISSUE TITLE
next: black morast (.cartographer) impossibe atm

### ISSUE THREAD

**Issue by geojak** [slowtorta/turtlewow-bug-tracker#2694]
**Please, provide a clear description what the bug is:**

the black morast dungeon in cavern of times have been closed for almsot a year. its not possible to explore it for cartographer title.

**Expected behavior. Describe how it should work:**

as long as the dungeon is not accesible it should not be requirred for the title

**Comment by geojak** [comment]
p.s. thx for including that next on .cartographer. rly awesome! i am down to 4 left. exploring the great sea in every single zone was a bit dumb but atleast i knew what to do thx to the next!

**Comment by slowtorta** [comment]
BM was excluded.

**Comment by geojak** [comment]
Thank you torta!
