### ISSUE TITLE
neto the time weaver script broke

### ISSUE THREAD

**Issue by geojak** [slowtorta/turtlewow-bug-tracker#2695]
**Please, provide a clear description what the bug is:**
in caverns of time neto the time weaver used to teleport random lore characters in and sent them to the left and right with some custom cool conversations. it broke and seems not happening anymore

**Expected behavior. Describe how it should work:**
script readded, also black morast reopened? plllls :)

**Comment by slowtorta** [comment]
@Nolin7777

**Comment by slowtorta** [comment]
It's fixed now.
