### ISSUE TITLE
Vendor stock inconsistency with database

### ISSUE THREAD

**Issue by M0bbey** [slowtorta/turtlewow-bug-tracker#2697]
The vendor Gigget Zipcoil in Hinterlands seems to never replenish her stock of the leatherworking pattern for Ironfeather Shoulders. After checking Turtlewow's database, that item should have unlimited stocks to begin with : https://database.turtle-wow.org/?npc=12958

**Comment by slowtorta** [comment]
We haven't completed the migration of all our web infrastructure to the new machine. DB is outdated.
