### ISSUE TITLE
Small Thorium Veins in Talonbranch Glade

### ISSUE THREAD

**Issue by ChookzNZ** [slowtorta/turtlewow-bug-tracker#2699]
Small Thorium Veins in Talonbranch Glade are.. a bit all over the show.
Below is one in mid-air along the new ramp towards the tower
![image](https://user-images.githubusercontent.com/122669592/212464623-0850d239-f239-40db-b560-421592002f6a.png)
And there is also one stuck in a tree.

Cheers,
Kalibur

**Comment by slowtorta** [comment]
I was able to locate one floating mine. If you spot more please report it via ticket right away. This way it can be fixed almost immediately with the GM's help.
