### ISSUE TITLE
Custom Quest: A Warm Feeling - No 'Winterspring Tea Leaf' Drops

### ISSUE THREAD

**Issue by perl1743** [slowtorta/turtlewow-bug-tracker#27]
~~By opening this Issue, I admit to having done the pertinent research using sources from Vanilla (preferably) or Classic. I also understand that sources from other private servers are not acceptable.~~
It's a custom quest, can't cross-check other sources.

**Current behavior**: 
[Winterspring Tea Leaf](https://database.turtle-wow.org/?item=80880) is listed as 100% drop rate, but none are dropping.
[A Warm Feeling](https://database.turtle-wow.org/?quest=80369) does not appear in quest log, but appears as in progress.
![image](https://user-images.githubusercontent.com/2818608/121608087-dbc2cc80-ca16-11eb-85ea-c2caace74fd5.png)
**Expected behavior**: 
If repeatable quest is in progress, tea leaves should drop, 100% of the time as listed.
(Last time I was able to complete this quest as normal was two or three days ago.)
**Proofs**:
![image](https://user-images.githubusercontent.com/2818608/121608710-20029c80-ca18-11eb-8d56-1e3f5a857561.png)

**Steps to reproduce**:

1. Check [Salfa](https://database.turtle-wow.org/?npc=11556), ensure quest is in progress.
2. Go kill owlbeasts.
3. Get no drops.

**Comment by slowtorta** [comment]
Can't reproduce, working as intended. Is it possible you have been in a raid group?

**Comment by perl1743** [comment]
Checked again today, all working now, closing issue.
~Being in raid wouldn't explain the hidden quest entry in log.
