### ISSUE TITLE
Hunter owl pet missing Avoidance skill.

### ISSUE THREAD

**Issue by RantingLemming** [slowtorta/turtlewow-bug-tracker#2701]
**Please, provide a clear description what the bug is:**

Following the latest patch, my existing owl pet (tamed from Teldrassil) has lost Avoidance.

See screenshot below for pet spellbook.

![TurtleWow_OwlPetMissingAvoidance](https://user-images.githubusercontent.com/17890031/212504359-dc0e2e43-48a2-49e9-931f-a601eb76dcd1.png)

**Comment by RantingLemming** [comment]
I tamed a new owl from Winterspring, level 55, right outside Everlook.  This one is also missing Avoidance.

![TurtleWow_OwlPetMissingAvoidanceStill](https://user-images.githubusercontent.com/17890031/212533633-623d547e-6cc4-4fd5-8600-5e97b2be3a8d.png)

**Comment by mikefirefly** [comment]
Can confirm, both my owls are missing Avoidance (level 55 and 59).

**Comment by Zmitrok1984** [comment]
Added a voice: my wolf pet 56 lvl hasn't avoidance skill, even cat pet 60 lvl has it.
![image](https://user-images.githubusercontent.com/99164611/212661489-08e389f3-64c8-4e98-ba41-d4ded2f7e706.png)
![image](https://user-images.githubusercontent.com/99164611/212661055-c3e69a8d-cfb5-4632-a03f-dfa3dc148e08.png)
