### ISSUE TITLE
Spell: Tiger's Fury

### ISSUE THREAD

**Issue by chakanauk** [slowtorta/turtlewow-bug-tracker#2702]
The [Tiger's Fury](https://database.turtle-wow.org/?spell=5217) buff gets removed once shapeshifting out and back in to cat form.

**Comment by geojak** [comment]
Isn't that intended?

**Comment by chakanauk** [comment]
I don't believe so since it makes this spell not viable in rotation. Other spell's such as [Blood Frenzy](https://database.turtle-wow.org/?spell=16952), Berserk, Nature's Grasp, etc. all remain active since druids are meant to be shapeshifting frequently.
