### ISSUE TITLE
Dying in sm doesn't Port to gy

### ISSUE THREAD

**Issue by geojak** [slowtorta/turtlewow-bug-tracker#2703]
1. Be alliance 
2. Go to sm monastery and die in front of the dungeon entrances, not inside the dungeons
3. Release spirit
4. Don't get portet to the gy instead directly stand up on the spot 

**Expected behavior. Describe how it should work:**

Need to walk from the sm grwyeyars outside

**Comment by ratkosrb** [comment]
Will be fixed on next server update.
