### ISSUE TITLE
The Scarlet Basilica is not discoverable for Cartographer title

### ISSUE THREAD

**Issue by chloejaynebond** [slowtorta/turtlewow-bug-tracker#2704]
I am currently working towards the Cartographer title.
Per the .cartographer command my next area to discover is The Scarlet Basilica in Tyr's Hand in EPL.
I am entering the Basilica and not getting anything.

**Steps to reproduce the behavior with as much detail as possible:**

1. Do not have The Scarlet Basilica discovered
2. Enter The Scarlet Basilica in Tyr's Hand
3. Note no discovery

**Expected behavior. Describe how it should work:**
Entering The Scarlet Basilica should give credit for discovery.

**Comment by slowtorta** [comment]
This will be fixed on the next server update.
