### ISSUE TITLE
Erratic mana regeneration as Arcane Mage

### ISSUE THREAD

**Issue by RUTHINAS** [slowtorta/turtlewow-bug-tracker#2706]
**Please, provide a clear description what the bug is:**
After reaching level 40 and getting Brilliance Aura, I started noticing some strange behavior from my mana regeneration.

Right away after self-buffing (Arcane Intellect rank 4, Mage Armor rank 1, Brilliance Aura) and dumping all my mana it takes me 2 minutes 18 seconds to regenerate my mana pool of 4500. However, just a few moments prior to this – before my previous set of self buffs expired – I could do the same regen in only 26 seconds.

Obviously regenerating ~340 mana per 2 seconds as a level 43 mage is not reasonable, and it essentially leaves my mana permanently capped. Actually dumping my entire pool for this initial trial turned out to be a difficult task, since having 60% mana regen while casting, not even Conjure Water seemed to do the trick. Luckily Arcane Intellect rank 4 costs a hefty 945 mana per cast, so I could eventually get rid of it all.

So I did a test: standing idle in a capital city with only my own buffs affecting me. Dumping my mana pool (nearly) empty by spamming Arcane Intellect and then measuring the time it takes for me to regenerate everything back to full (4500). The first trial was directly after casting the set of buffs (as explained above) and it took me 2 minutes and 18 seconds to regenerate.

I repeated the test after 8 minutes had passed, only to get the same 2 minutes 18 seconds result. Again, at 16 minutes, the result was the same; 2 minutes and 18 seconds. Once more a further 8 minutes later, the result was an unremarkable 2 minutes and 18 seconds. Finally, after cancelling the effects of Brilliance Aura and Mage armor, regenerating the entire mana pool took a bit longer at 2 minutes 40 seconds – perfectly in line with the fact that Brilliance Aura gives 15% more mana regen.

Seemingly it is not about the time that has passed since casting Brilliance Aura, but instead some interaction of how I play while Brilliance Aura is active. I used plenty of Mana Shield (which absorbed a lot of damage, consuming large amounts of mana in the progress), Arcane Explosion and Arcane Missiles during the previous set of buffs, as well as consumed one Mana Jade and used Evocation twice, and drank a few bottles of water (fewer towards the end of the buff cycle, as I started noticing my mana regen already ramping up while playing). I also had Mark of the Wild, Divine Spirit and Power Word: Fortitude on me, and Lesser Mana Oil (8 mana every 5 seconds) on my weapon for a good portion of the buff cycle, although I had cancelled them all (except for the mana oil) while timing the 26 second result. I suppose they could somehow still alter the regeneration given by Brilliance Aura.

I don't know whether the mana regen from Brilliance Aura is to blame, but I don't remember noticing anything like this before picking it up. So far it looks very suspect. It also seems that by recasting Brilliance Aura my regen goes back to normal.

**Steps to reproduce the behavior with as much detail as possible:**

1. Pick up Brilliance Aura and apply the buff (possibly along with Mage Armor and Arcane Intellect, possibly also some buffs from other classes) 
2. Play normally; use abilities, spend mana, regenerate mana
3. Observe a slowly increasing rate of mana regeneration, which is then reset when Brilliance Aura expires

**IDs of affected creatures, items, quests or spells with a link to the relevant page:**

Spell: https://database.turtle-wow.org/?spell=45408

**Expected behavior. Describe how it should work:**
The mana regeneration should remain consistent over time.

**Comment by ratkosrb** [comment]
Brilliance Aura snapshots 15% of your regen as you cast it, and you will continue to have this bonus until aura is removed. If your mana regen is different at the time you cast it next time, then the bonus it gives will be different.

**Comment by RUTHINAS** [comment]
I did some trials, and discovered the source of this mana regen. You wouldn't believe it even if you saw it, but with the same gear, talents and self buffs (arcane intellect, mage armor, brilliance aura, mana shield) as in the previous trial (which ended up at 2 minutes 18 seconds from empty to full), I managed to boost my mana regeneration to 645 per two-second tick. To regenerate my 4500 mana pool, it took only 12 seconds.

The first few ticks still remained within the 5 second rule, as I was spamming Arcane Intellect to dump my mana – they generated only 615 mana (strangely, this is ~95% mana regeneration "while casting", despite my buffs and talents totaling to 60%).

This is equivalent to approximately 1613 mana per 5 seconds while not casting, and 1538 while casting. I doubt these values would be reasonable even while channeling evocation (which, during this trial, generated a massive 1478 mana per tick, equaling to 3695 per 5 seconds).

After this trial, I did another one with only Arcane Brilliance as a buff, doing the other steps needed to replicate this bug as quickly as possible. In less than a minute I had attained enough mana regeneration to fully regenerate my 4137 unbuffed mana pool in 12 seconds. Of note is that the buff applied to party members also ramps up in a similar fashion. A shaman friend of mine who would normally regenerate 49 mana per tick while not casting (or ~123 mana every 5 seconds) gained a massive boost, allowing them to regenerate 145 mana per tick while not casting (~363 mana per 5 seconds).

I now have made a macro that will with no effort replicate the bug reliably.

With the ease of replication and powerful effect affecting both the mage and their party, this bug is pretty much game-breaking.

Please contact me directly on the Turtle Discord, as I don't feel comfortable having such a powerful bug out in the open before there has been a chance to fix it.
