### ISSUE TITLE
"It's All in Their Brains" - Scarlet Crusade Insignia QuestChain is broken

### ISSUE THREAD

**Issue by reaver594** [slowtorta/turtlewow-bug-tracker#2707]
**Please, provide a clear description what the bug is:**

The ChestChain to receive the "Scarlet Crusade Insignia" is broken right now.
After Completing "A Different Shade of Red" the follow up Quest "It's All in Their Brains" can't be properly accepted. (It can be accepted but wont appear in the Questlog or anywhere else, and doesnt count as active.)
So the QuestChain can not be continued.

**Steps to reproduce the behavior with as much detail as possible:**

1. Complete Quest "A Different Shade of Red" (Horde) or "Donning the Red Flag" (Alliance at NPC "Mavel Brightwood" in Tyr's Hand while being in Disguise via "Illusion: Scarlet Crusade".
2. Try to accept the follow up Quest "It's All in Their Brains" (Click Quest in Dialogue -> Click "accept")
3. Check Questlog if the Quest Appeared.
4. Check Overall Number of Active Quests, to confirm it has not ben accepted.
5. Check Dialogue Options for NPC "Mavel Brightwood" again, to see Quest is not shown anymore to accept.

**IDs of affected creatures, items, quests or spells with a link to the relevant page:**

NPC: (Mavel Brightwood) https://database.turtle-wow.org/?npc=50677
Item: (Illusion: Scarlet Crusade) https://database.turtle-wow.org/?item=53003
Quest: (It's All in Their Brains) https://database.turtle-wow.org/?quest=80710

**Expected behavior. Describe how it should work:**
The quest should appear in the Questlog after accepting. It should count as +1 in Number of active Quests and it should be possible to be progressed.
The Quest should also be able to be retaken, since it is not active or completable for Players right now.

**Comment by Dormilon** [comment]
The problem has not been identified. Quest is functioning correctly.
