### ISSUE TITLE
Trelane's defenses elite quest

### ISSUE THREAD

**Issue by UsernameChad42069IsNotAvailable** [slowtorta/turtlewow-bug-tracker#271]
**Please, provide a clear description what the bug is:**
When using Azure Agate to activate the towers defenses they won't activate, making the quest impossible for lowbies.
**Steps to reproduce the behavior with as much detail as possible:**

1. Just by using Azure Agate and even tried with multiple players using it, it just doesn't do jack.

**IDs of affected creatures, items, quests or spells with a link to the relevant page:**

https://database.turtle-wow.org/?npc=2789
https://database.turtle-wow.org/?item=4527
https://database.turtle-wow.org/?quest=694

**Expected behavior. Describe how it should work:**
Make the defenses actually activate when using Azure Agate, which will summon water elementals to your aid.

**Comment by geojak** [comment]
The water elements didn't do much in classic either. But yes here there aren't even any

**Comment by redmagejoe** [comment]
This quest is still not scripted properly.

**Comment by redmagejoe** [comment]
Please file your tickets properly and mention the appropriate quest in your links and in the title for clarity.  The quest that should actually have been linked is "Attak on the Tower" which is https://database.turtle-wow.org/?quest=696

**Comment by ratkosrb** [comment]
https://github.com/slowtorta/turtle-wow/commit/2ea59d827aaa5f26d01037e7e9527f5c4db1b09c
