### ISSUE TITLE
Darkshore Schools of Fish too close to the shoreline.

### ISSUE THREAD

**Issue by Nelenora** [slowtorta/turtlewow-bug-tracker#2710]
There are several schools of fish / debris that are practically unfishable due to their close proximity to the shoreline where the water isn't deep enough in Darkshore.

https://database.turtle-wow.org/?item=21071#fished-in 
![image](https://user-images.githubusercontent.com/122533554/212887847-386c75a2-49f5-4815-a524-cf54ba91899c.png)
![image](https://user-images.githubusercontent.com/122533554/212890474-8c93a935-f887-4bce-8fb0-0cf29be15f81.png)

https://database.turtle-wow.org/?object=180655

![image](https://user-images.githubusercontent.com/122533554/212893892-956df1a0-ef50-4944-abec-4b5bb2904751.png)
![image](https://user-images.githubusercontent.com/122533554/212894007-a1d36ea2-44cc-48a8-9f50-527662c50b6a.png)

https://database.turtle-wow.org/?item=6358
![image](https://user-images.githubusercontent.com/122533554/212894640-a366be1d-14fa-4a9b-9a93-bb7cb72681b3.png)
![image](https://user-images.githubusercontent.com/122533554/212894747-d87d2b1d-0ae8-4062-bfab-ba9d97c25bf2.png)

![image](https://user-images.githubusercontent.com/122533554/212895305-3b1462b9-a4c0-4b4e-913b-50d582d8c1a0.png)
![image](https://user-images.githubusercontent.com/122533554/212895340-039645f9-9769-4c4a-bb8d-fc5396d01df9.png)

.

**Comment by Gurky-Turtle** [comment]
Schools of Fish in Darkshore should now be the correct distance from the shore.
