### ISSUE TITLE
Silvermane howlers will not swim in Valorwind Lake in Hinterlands

### ISSUE THREAD

**Issue by xHucknasty** [slowtorta/turtlewow-bug-tracker#2712]
**Please, provide a clear description what the bug is:**

**Steps to reproduce the behavior with as much detail as possible:**

1. Go to Valorwind Lake in Hinterlands (39.3, 61.4)
2.  Aggro a Silvermane Howler
3. Run into the lake, the wolf will stop just inside the water and not proceed further.  Eventually evades back to spawn.

**IDs of affected creatures, items, quests or spells with a link to the relevant page:**

NPC: https://database.turtle-wow.org/?npc=2925
Item: https://database.turtle-wow.org/?item=
Quest: https://database.turtle-wow.org/?quest=
Spell: https://database.turtle-wow.org/?spell=
Object: https://database.turtle-wow.org/?object=

**Expected behavior. Describe how it should work:**
Generally mobs will swim after their enemies.  I've never seen a mob not go in the water, although I have seen the reverse when it makes logical sense (i.e. fish that don't leave the water).

**Comment by slowtorta** [comment]
It's normal that wolves do not enter the water in Vanilla WoW. I see no indication that this specific wolf should be able to swim, sorry!
