### ISSUE TITLE
Quest: WANTED : Hole Escapee

### ISSUE THREAD

**Issue by mw4821** [slowtorta/turtlewow-bug-tracker#2716]
3 Issues with the quest

1. After you've defeated Baxxil and right click and have him follow you... an invisible Riding wolf keeps attacking you as long as your within so many feet of where you fought him. 
2. His pathing is off if you swim across the river and not walk across the bridge. He will in many spot run to the bridge and back to your location.
3. When turning in... If you right click HIzzle and select the ? WANTED: Hole Escapee instead of the text below ..... The text to complete quest will disappear.  I had him with me for a long time so I don't know if someone else got Baxill that cause it or just the UI selection. Made me go and fight Baxxil again.

**Steps to reproduce the behavior with as much detail as possible:**

1. Fight Baxxil and defeat
2. Right click and select follow me back partner I am the law or whatever...
4. Stand still and the invisible wolf will continue to beat on you tlll you die... Very nerve racking as HC.

**IDs of affected creatures, items, quests or spells with a link to the relevant page:**

[NPC: https://database.turtle-wow.org/?npc=91249
Item: https://database.turtle-wow.org/?item=
[Quest: https://database.turtle-wow.org/?quest=55048
Spell: https://database.turtle-wow.org/?spell=
Object: https://database.turtle-wow.org/?object=

**Expected behavior. Describe how it should work:**
1. Should be no invisible Wolf Attacking you.
2. Pathing: He should follow you like a pet with the river.
3. Turn in text should not disappear since the NPC is still with you and allow turnin.

**Comment by slowtorta** [comment]
I'm sorry but it worked just fine for me. No wolves, no bugs.

**Comment by Lashmush** [comment]
I just got my L14 HC killed this way. This is very much an issue.

**Comment by acolis** [comment]
Hi, can confirm it is still happening, link to video
https://www.youtube.com/watch?v=_ZL9t73V4rQ

**Comment by twowTurtReynolds** [comment]
![image](https://github.com/slowtorta/turtlewow-bug-tracker/assets/151180101/bad1846d-f451-4dfd-8196-8dd7edabef05)
I'm not able to replicate this. Baxxil was moved since your video, maybe that solved it?

Please let me know on your end as well.
