### ISSUE TITLE
Brood of Nozdorum Reputation Lost.

### ISSUE THREAD

**Issue by Executhor** [slowtorta/turtlewow-bug-tracker#2718]
I Lost Reputation on the Brood of Nozdorum.

1. I was last Week raiding AQ 40 Full Run with my Guild. 
2. I was on Full Run and many repeating Q(trash item) they i have Completet and after that Friendly by arround 1500 with the Reputation,.
3. and now im Unfriendly without any reason.

AQ40 Full Run with my Guild  "Thunder Ale Brewing Co" on  the 13.01.2023

My Char : Executhor Orc Warrior

![BUGGGG](https://user-images.githubusercontent.com/123056830/213376405-51f53bc9-23a5-4f71-b4aa-41381704dc91.png)

**Comment by slowtorta** [comment]
https://github.com/slowtorta/turtlewow-bug-tracker/issues/2797
