### ISSUE TITLE
Ravager spin

### ISSUE THREAD

**Issue by UsernameChad42069IsNotAvailable** [slowtorta/turtlewow-bug-tracker#272]
**Please, provide a clear description what the bug is:**
Ravager will stop spinning randomly due to I believe mobs around me dying, it shouldnt do that. It should stop spinning only if cancelled 
**Steps to reproduce the behavior with as much detail as possible:**

1. Just use it on multiple mobs that are dying.
2. I was in a dungeon with a group when this kept happening.

**IDs of affected creatures, items, quests or spells with a link to the relevant page:**

https://database.turtle-wow.org/?item=7717

**Expected behavior. Describe how it should work:**
Ravager shouldn't stop spinning for its full duration unless you are cced.

**Comment by ILostMyPants** [comment]
I would like to add that Ravager should also be able to proc itself, enchantments and will proc a paladin's Vengeance talent when it crits, while it currently does not.

**Comment by Khanz0** [comment]
Is supossed be able to proc itself AND proc from enchants like fiery blaze enchantments and other damage procs

**Comment by Nolin7777** [comment]
Hello and thank you for your report!

Please add any evidence in form of a legit source (for example wowhead.com) or a video captured from Blizzard's Classic server.

This ticket will be closed until more information added.
