### ISSUE TITLE
shield not showing in shadowform

### ISSUE THREAD

**Issue by ozzymagnum** [slowtorta/turtlewow-bug-tracker#2721]
**Please, provide a clear description what the bug is:**

**Steps to reproduce the behavior with as much detail as possible:**

1. when i use shadowform and then power word shield it doesnt show but the buff shows https://imgbb.com/0y8L9jF
2. 
3. 

**IDs of affected creatures, items, quests or spells with a link to the relevant page:**

NPC: https://database.turtle-wow.org/?npc=
Item: https://database.turtle-wow.org/?item=
Quest: https://database.turtle-wow.org/?quest=
Spell: https://database.turtle-wow.org/?spell=
Object: https://database.turtle-wow.org/?object=

**Expected behavior. Describe how it should work:**

**Comment by slowtorta** [comment]
![image](https://user-images.githubusercontent.com/66763404/220190667-d14f5f69-9e99-4291-aff3-98cd9c419722.png)
The aura is here, but it's barely visible because it becomes even more transparent in Shadow Form. This is the correct behavior in Vanilla client.
