### ISSUE TITLE
Title: Cartographer "Next:" message shows already discovered subzone.

### ISSUE THREAD

**Issue by coldwhitelight** [slowtorta/turtlewow-bug-tracker#2725]
**Please, provide a clear description what the bug is:**

While typing `.cartographer` command, the second part of the message is "Next: SUBZONE". For my character it was showing "You have 45 areas left to explore" and the next was "The Great Sea". After discovering "The Great Sea" in Azshara it now says "You have 44 areas left to explore" and the next is still "The Great Sea".

**Steps to reproduce the behavior with as much detail as possible:**

1. Have "The Great Sea" as the next subzone to explore
2. Discover "The Great Sea" in Azshara
3. Check `.cartographer` command to see if "The Great Sea" is still the next subzone.

**Expected behavior. Describe how it should work:**

It should either show another "Next: SUBZONE" message or if there are more than one with the same name it should show "Next: SUBZONE [ZONE]".

**Comment by ratkosrb** [comment]
There are 13 areas named "The Great Sea", and the cartographer list includes 9 of them. So you have to go explore the sea in multiple places off the coast of different zones.

**Comment by coldwhitelight** [comment]
> There are 13 areas named "The Great Sea", and the cartographer list includes 9 of them. So you have to go explore the sea in multiple places off the coast of different zones.

Thank you for the information. Will do that. :)
