### ISSUE TITLE
Malfunctioning Arcane Constructs On Mountain

### ISSUE THREAD

**Issue by DraconicLeafTalarus** [slowtorta/turtlewow-bug-tracker#2729]
The Malfunctioning Arcane Constructs on Ala'Thalas are spawning on the mountain instead of inside the mine.

![Construct Mountain](https://user-images.githubusercontent.com/96985605/213868656-fa8cdd10-1d12-41fa-834e-7666d8b8990b.jpeg)

Database page: https://database.turtle-wow.org/?npc=80241

**Comment by slowtorta** [comment]
This is the part of more complex problem we're aware about.
