### ISSUE TITLE
'Data Rescue'

### ISSUE THREAD

**Issue by Sygmoond** [slowtorta/turtlewow-bug-tracker#273]
**Please, provide a clear description what the bug is:**
Gnomeregan's quest 'Data Rescue' is bugged. Whenever I interact with the Matrix Punchograph 3005-B, I don't get the next punchcard.

**Steps to reproduce the behavior with as much detail as possible:**

1. Run to Gnomeregan.
2. Acquire a white punchcard.
3. Interact with Matrix Punchograph 3005-A
4. Run to the Matrix Punchograph 3005-B and interact with it.
5. No response.

**IDs of affected creatures, items, quests or spells with a link to the relevant page:**

NPC: https://database.turtle-wow.org/?npc=
Item: https://database.turtle-wow.org/?item=
Quest: https://database.turtle-wow.org/?quest=2930
Spell: https://database.turtle-wow.org/?spell=
Object: https://database.turtle-wow.org/?object=

**Expected behavior. Describe how it should work:**
The quest should 'transform' my yellow punchcard into a blue punchcard.

**Comment by Nolin7777** [comment]
Duplicate
