### ISSUE TITLE
Missing sounds in the Hunter's shots

### ISSUE THREAD

**Issue by Punked20** [slowtorta/turtlewow-bug-tracker#2730]
I have noticed that since a couple of patches ago when using the skills, Auto-Shot, Aimed Shot, Arcane Shot, Trueshot, Multi-Shot, Volley, Concussive Shot, the sound that should sound when firing the weapon, has a chance of not sounding.

Sometimes it sounds, sometimes it doesn't, at first I thought it had to do with my macros, but after restarting the client there are sounds, but after a while, it disappears again after a couple of relogs.

**Steps to reproduce the behavior with as much detail as possible:** 

The weapon I have is the Dark Iron Desecrator, and before that I had the Dwarven Hand Cannon, the problem persists regardless of the weapon. It's a matter of firing a burst of skills and seeing how none of them have sound.

(I want to clarify that I don't have the game, nor any sound option muted).

**Expected behavior. Describe how it should work:** When shooting a skill, or the auto-shot itself, the sound of the gun reloading, and then the shot, should be played (instead it is completely muted, neither of the two effects are heard).

**Comment by ozzymagnum** [comment]
same when you use wands

**Comment by redmagejoe** [comment]
This is not a bug, but is related to the reduction in available sound channels in the latest version of the client to the default vanilla behavior after the previously increased sound channel "hack" was causing crashes due to memory overflow.

Working as intended.
