### ISSUE TITLE
Fishing Tournament winner

### ISSUE THREAD

**Issue by Meatfeet** [slowtorta/turtlewow-bug-tracker#2733]
I did the fishing tournament today. Usually when there is a winner, the assistant says, "even though there was already a winner, you can still turn in your tasty fish"
Today when I went back and she said, "Once there is a winner, you can turn your tasty fish into me"

I went back out and caught 13 more fish, just to see if I could still win, and there was not change. 

Did someone win today? 

Meatfeet - Player name
Riggle Bassbait - NPC
Jang - NPC

NPC: https://database.turtle-wow.org/?npc=
Item: https://database.turtle-wow.org/?item=
Quest: https://database.turtle-wow.org/?quest=
Spell: https://database.turtle-wow.org/?spell=
Object: https://database.turtle-wow.org/?object=

**Comment by Gurky-Turtle** [comment]
There needs to be a lot more information on this report in order to look into it further it is really lacking also I am not seeing any NPCs say exactly what you state above. 

It can be reopened when more information is provided.
