### ISSUE TITLE
(Druid) Swipe hitting targets far away

### ISSUE THREAD

**Issue by njalsson** [slowtorta/turtlewow-bug-tracker#2737]
Druid's 🐻  bear form ability swipe  has a chance of hitting a target far away, ranging from 10 to 40 yards away. It's happened a few times today in dungeons where a mob with 98% health comes running out of nowhere with his posse following.  👀 

I have not found a method to reproduce it, it seems random.

Spell: https://database.turtle-wow.org/?spell=9908

Swipe should be limited to 5 yards range.

**Comment by twowTurtReynolds** [comment]
Need solid replication steps please! Find out what exactly you are doing differently when this does occur.

**Comment by twowTurtReynolds** [comment]
I'll close this report until you follow back up with us.
