### ISSUE TITLE
Imp's Blood Pact goes away

### ISSUE THREAD

**Issue by Ricviu** [slowtorta/turtlewow-bug-tracker#2738]
**Please, provide a clear description what the bug is:**
Bug description: Warlock Imp's Blood Pact stops applying after some time. I'm not sure what causes it. Me and a friend are questing with new-ish (level 10) characters in Durotar, near Razor Hill now but the bug has been repeating ever since I taught the imp the spell.

I thought it might have been related to the new islands in the Echo Isles, but the bug is repeating in Durotar proper as well. We have repeatedly deleted WDB and relogged in an attempt to fix it, to only temporary success.

**Steps to reproduce the behavior with as much detail as possible:**

1. As a warlock, summon an imp
2. Have the imp activate Blood Pact
3. The imp's blood pact is on autocast
4. Blood Pact stops affecting the party member after some time (only tested with 1 party member). They do not have the Blood Pact buff active on them
5. After some more time you will also no longer have the buff either
6. The imp will be the only one with Blood Pact buffing them

**IDs of affected creatures, items, quests or spells with a link to the relevant page:**

NPC: Warlock player's imp summon pet (spell ID to summon because I can't find the NPC in the database)
https://database.turtle-wow.org/?spell=688

Spell: Blood Pact (Warlock Imp spell, rank 1)
https://database.turtle-wow.org/?spell=20397

Players Grensha (Orc Warlock) and Malahit (Troll Shaman) are affected, untested with others

**Expected behavior. Describe how it should work:**
Expected behavior is that the imp's Blood Pact is a constant buff that stays on for all party members.

**Comment by slowtorta** [comment]
https://github.com/slowtorta/turtlewow-bug-tracker/issues/2740
