### ISSUE TITLE
Private Thorsen

### ISSUE THREAD

**Issue by Sygmoond** [slowtorta/turtlewow-bug-tracker#274]
**Please, provide a clear description what the bug is:**
Private Thorsen should be attacked by the Kurzen amidst his patrol. He does not get attacked, and so I can't start the quest 'Jungle Secrets'
**Steps to reproduce the behavior with as much detail as possible:**

1. Go to the Rebel Camp in STV
2. Wait for Thorsen to go on his patrol.
3. Follow him

**IDs of affected creatures, items, quests or spells with a link to the relevant page:**

NPC: https://database.turtle-wow.org/?npc=738
Item: https://database.turtle-wow.org/?item=
Quest: https://database.turtle-wow.org/?quest=215
Spell: https://database.turtle-wow.org/?spell=
Object: https://database.turtle-wow.org/?object=

**Expected behavior. Describe how it should work:**

Instead of peacefully walk on his patrol and going back. Thorsen should get attacked, the player should rescue him and start a quest chain with the first one being 'Jungle Secrets'.

![imagen](https://user-images.githubusercontent.com/89550040/130873498-a9a0fe2d-907b-4243-a1c1-e4899f3c7db8.png)

**Comment by Nolin7777** [comment]
Closed until proof added.
