### ISSUE TITLE
Updated imp blood pact issue (current)

### ISSUE THREAD

**Issue by Ricviu** [slowtorta/turtlewow-bug-tracker#2740]
**Please, provide a clear description what the bug is:**
Bug description: Warlock Imp's Blood Pact does not reapply if someone gets out of range.

Recasting the Blood Pact still does not reapply the buff, but the warlock relogging does.

**Steps to reproduce the behavior with as much detail as possible:**

1. As a warlock, summon an imp
2. Activate Blood Pact (autocast)
3. Move out of range of the imp
4. Blood Pact will not become active on your character until you relog

**IDs of affected creatures, items, quests or spells with a link to the relevant page:**

NPC: Warlock player's imp summon pet (spell ID to summon because I can't find the NPC in the database)
https://database.turtle-wow.org/?spell=688

Spell: Blood Pact (Warlock Imp spell, rank 1)
https://database.turtle-wow.org/?spell=20397

Players Grensha (Orc Warlock) and Malahit (Troll Shaman) are affected, untested with others

**Expected behavior. Describe how it should work:**
Expected behavior is that the imp's Blood Pact will become active once you get back in range of the imp.

**Comment by redmagejoe** [comment]
Cannot reproduce this on current version. Moving in and out of radius causes the expected +Blood Pact, -Blood Pact spam.

Fixed.
