### ISSUE TITLE
Faerie Fire (Feral) cannot be learned

### ISSUE THREAD

**Issue by Eloxai** [slowtorta/turtlewow-bug-tracker#2743]
Hello.

I am 42 level druid and i've tried to learn Faerie Fire (Feral) from every trainer in Thunder Bluff and Moonglade but i just see the spell in red and i cannot click on train.

I will appreciate any tips.

Regards.

**Comment by redmagejoe** [comment]
Cannot reproduce on current version. Please be sure you delete your WDB folder (cache) as this spell was made baseline some time ago and if you are an old returning player, the client may be operating on old information.

Working as intended.
