### ISSUE TITLE
Player name Pino cannot receive world buffs

### ISSUE THREAD

**Issue by IamPino21ffs** [slowtorta/turtlewow-bug-tracker#2746]
**Please, provide a clear description what the bug is:**
Player name Pino cannot receive world buffs
**Steps to reproduce the behavior with as much detail as possible:**

1.Stay in orgrimmar when boss head is being turned
2.no buff received
3. 

**IDs of affected creatures, items, quests or spells with a link to the relevant page:**

NPC: https://database.turtle-wow.org/?npc=
Item: https://database.turtle-wow.org/?item=
Quest: https://database.turtle-wow.org/?quest=
Spell: https://database.turtle-wow.org/?spell=
Object: https://database.turtle-wow.org/?object=

**Expected behavior. Describe how it should work:**

**Comment by slowtorta** [comment]
I'm sorry, this is isn't something we can fix. Things like that can happen randomly to any character at different times.

**Comment by IamPino21ffs** [comment]
so I will never have world buffs? sadpepe

**Comment by IamPino21ffs** [comment]
is this the first ocurrence? if not, is there any similarity to another ocurrence? such as undead hunter, etc - can I get a chronoboom per week with wbuffs.. thanks!
