### ISSUE TITLE
Buffs not working while in raid groups

### ISSUE THREAD

**Issue by rocktalon** [slowtorta/turtlewow-bug-tracker#2747]
**Please, provide a clear description what the bug is:**
any kind of "aura buff" seems not to effect my character while in a raid group. Things like shaman totems, leader of the pack, blood pact, all do not show up on my buff bar and are not reflected in my character sheet. I place down a grace of air and my agility remains the same. I place down a nature resist totem and my nature resist does not go up. This is only effecting me and not my party members. As soon as I leave raid group, everything starts working as intended again. I have tried deleting WDB, which has not fixed the problem. Sometimes it will start working normally again seemingly at random, only for the issue to come back after a few minutes. This has been happening consistently with my shaman for the last two raids I have done.
**Steps to reproduce the behavior with as much detail as possible:**

1. join raid group
2. place down totem
3. buff does not show up on bar and stats are not increased

**IDs of affected creatures, items, quests or spells with a link to the relevant page:**

NPC: 
Item: 
Quest: 
Spell: https://database.turtle-wow.org/?spell=25359 
https://database.turtle-wow.org/?spell=10601 
https://database.turtle-wow.org/?spell=10408 
https://database.turtle-wow.org/?spell=25361 
https://database.turtle-wow.org/?spell=10479 
https://database.turtle-wow.org/?spell=10538
Object: 

**Expected behavior. Describe how it should work:**
My own totems and other characters buffs should be showing up on my buff bar and changing my characters stats

**Comment by rocktalon** [comment]
update: discovered a strange fix, if anyone else is having this problem or if this gives any insight to the the source of the problem. if i place a windfury totem down, then another totem that is not an air totem, it fixes it for some time before i must repeat that process

**Comment by slowtorta** [comment]
This is presently not considered being a a bug. Cross-faction auras are exclusive on Turtle WoW but it's a subject of an ongoing discussion.
