### ISSUE TITLE
Not receiving ANY rested xp from anything

### ISSUE THREAD

**Issue by YourOniichan** [slowtorta/turtlewow-bug-tracker#2748]
**Please, provide a clear description what the bug is:**
I am not receiving rested xp, I do not have glyph of exhaustion ect, I am level 9 currently , I have tried 2 different places, GM ingame told me to make a bug report here
**Steps to reproduce the behavior with as much detail as possible:**

1. I'm not sure if its just my character bugged? I dont have addons on , I'm a night elf druid 
2.  I walk into "inn" see the rested icon on portrait, but xp bar never goes to rested
3.  N/A

**IDs of affected creatures, items, quests or spells with a link to the relevant page:**

NPC: https://database.turtle-wow.org/?npc=
![image_2023-01-24_194056620](https://user-images.githubusercontent.com/123521054/214453972-dbac0dc8-9818-4646-aded-67330214667b.png)

Item: https://database.turtle-wow.org/?item=
Quest: https://database.turtle-wow.org/?quest=
Spell: https://database.turtle-wow.org/?spell=
Object: https://database.turtle-wow.org/?object=

**Expected behavior. Describe how it should work:**
You walk into an Inn for Rested xp and the game doesnt give you anything online or offline.

**Comment by geojak** [comment]
Exhausted challenge disables rested exp. Check your skill book general page

**Comment by YourOniichan** [comment]
As I stated I do not have that ...

**Comment by YourOniichan** [comment]
Tents seem to give me rested xp but only tents do not inns

**Comment by slowtorta** [comment]
This was fixed in one of the previous updates.
