### ISSUE TITLE
Sometimes you can't use flight paths with an illusion on

### ISSUE THREAD

**Issue by Kangaroux** [slowtorta/turtlewow-bug-tracker#2750]
Doesn't appear to be a problem with specific flight paths. Sometimes it automatically removes the illusion, other times it says I can't use the fp while shapeshifted. If I get the shapeshift error, repeatedly clicking the flight path doesn't work. I either get the error or it works first try.

I'm using the furbolg illusion from winter veil.

**Comment by slowtorta** [comment]
You can't use FP if your Illusion doesn't support sitting on a mount animation. That's intended behavior.

**Comment by Kangaroux** [comment]
@slowtorta The issue is that the game will remove the illusion automatically but only sometimes
