### ISSUE TITLE
Skill up with gray. Bug or feature?(Herbalism+cultivation)

### ISSUE THREAD

**Issue by tsangek** [slowtorta/turtlewow-bug-tracker#2753]
**Please, provide a clear description what the bug is:**

Tauren with racial passive(cultivation) can increases skill with "gray" herbs. (I installed clear client and launched without addons and WTF folder, and same problem)

**Steps to reproduce the behavior with as much detail as possible:**

1. Tauren with Herbalism 117
2. Collect some Earthroots (gray on client)
3. and wait when Herbalism has increased

**IDs of affected creatures, items, quests or spells with a link to the relevant page:**

Guide: https://www.wowhead.com/classic/guide/herbalism-leveling-1-300-wow-classic
(Earthroot from 115 skill cannot up your skill)
**Expected behavior. Describe how it should work:**
If you can increase your skill, then it should be shown on client.
![1](https://user-images.githubusercontent.com/60919489/214686046-5898cb35-fb2c-4dd0-9be0-dea0ea811e4f.jpg)
![2](https://user-images.githubusercontent.com/60919489/214686052-81b3443d-8db0-4d16-8bc3-882896577051.jpg)

**Comment by slowtorta** [comment]
I'm sorry, unable to reproduce it. Possibly a client-side glitch.

**Comment by cyaohiri** [comment]
I was able to reproduce it, but this seems to be how it should work, although it does seem like an oversight in the original game.

Here's a quote from https://wowpedia.fandom.com/wiki/Herbalism:
"Note that skill bonuses can make the skill-up colors behave a little oddly. While the chance to gain a skill point from an herb depends on your base skill and does not change, the color coding goes by total skill, which causes herbs to appear to "gray out" faster than normal. Thus, with skill bonuses, it's possible to gain a skill point from an herb that seems to be gray."
