### ISSUE TITLE
wrath of cenarius

### ISSUE THREAD

**Issue by gzlnon** [slowtorta/turtlewow-bug-tracker#2754]
The ppm of wrath of cenarius is way too high, making this ring have close to a 100% proc rate. That means that this ring is completely overpowered by giving you 132 spell power all the time just from 1 ring.
Is hard to find the ppm of certain items from classic but here https://wowwiki-archive.fandom.com/wiki/Wrath_of_Cenarius_(item) you can see that a 5% proc chance sounds about right.
https://database.turtle-wow.org/?item=21190 Equip this item and cast consecration or whatever you want, you will see it procs way too often.

**Comment by Altgf-spelladin** [comment]
and? I don't see any issue there.

**Comment by gzlnon** [comment]
> and? I don't see any issue there.

The issue is that this item has not the correct proc per minute, making it BiS for every spell caster. This item gives 132 spell power, nearly as much as a flask and close to a 100% proc rate. Having a ring that gives that much spell power, more than naxx weapons so yeah, sounds like an issue to me.

**Comment by gzlnon** [comment]
> 

No one is talking about aoe situations. Single target the proc is crazy high

**Comment by Meraxphone** [comment]
it not working properly, naxx rets are abusing the high proc on it on single targets

**Comment by JuliaXperenza** [comment]
the proc rate is decent but its not 100%, thats exaggerated

**Comment by luminieraa** [comment]
it works properly, the uptime for single target is not 100% if you pop consecration, and agreed on altgf,

for the other guy i feel like this dude just likes to target ret who tries properly in high end raids, you been really toxic on the server

**Comment by Altgf-spelladin** [comment]
Either butthurt about paladins doing good damage when they tryhard or someone too lazy to farm it.

**Comment by Meraxphone** [comment]
> it works properly, the uptime for single target is not 100% if you pop consecration, and agreed on altgf,
> 
> for the other guy i feel like this dude just likes to target ret who tries properly in high end raids, you been really toxic on the server

my hate for ret is a different thing, but obviously the item is NOT WORKING properly

**Comment by JuliaXperenza** [comment]
100% not bugged, for the time you dumped on getting the Wrath of Cenarius deff should be doing the thing it should, the proc rate is not 100%

**Comment by JuliaXperenza** [comment]
> The ppm of wrath of cenarius is way too high, making this ring have close to a 100% proc rate. That means that this ring is completely overpowered by giving you 132 spell power all the time just from 1 ring. Is hard to find the ppm of certain items from classic but here https://wowwiki-archive.fandom.com/wiki/Wrath_of_Cenarius_(item) you can see that a 5% proc chance sounds about right. https://database.turtle-wow.org/?item=21190 Equip this item and cast consecration or whatever you want, you will see it procs way too often.

i suggest you show a proof that it provides a nearly close 100% proc rate

**Comment by Meraxphone** [comment]
eitherway ticket is closed, you are fucked

**Comment by geojak** [comment]
@ratkosrb may I ask, what exactly changed?

**Comment by dkmnllth** [comment]
Hi, Torta you wrote that you fixed Wrath of Cenarius in the changelog 4 months ago, but your fix has made Wrath of Cenarius useless. I farmed this item over the course of 30+ hours and 500 gold spent so I could use it on my prot pally on aoe pulls, only to find out that it never procs anymore due to a custom nerf. There has to be a better middle ground so that it doesnt proc all the time on single target, but yet still consistently procs on aoe. Please revisit this nerf, as it's extremely unsetting to have an item as central and hard to farm as this nerfed to a useless status.

**Comment by dkmnllth** [comment]
Perhaps it accidentally got changed to 5% chance on spell cast rather than on spell land? It should have a 5% chance of proc on initial tick of consecration. On pulls of 20+ mobs, it seems to only proc once in every 20 Consecration casts, rather than once in every 20 mob hits.
