### ISSUE TITLE
"Supplies to Auberdine" quest in ashenvale bugged.

### ISSUE THREAD

**Issue by stickerorchard** [slowtorta/turtlewow-bug-tracker#2755]
**Please, provide a clear description what the bug is:**
Quest "Supplies to Auberdine"  at Maestras Post in Ashenvale is bugged. The Quest giver does not assist and makes the quest almost unbeatable on the very first set of mobs that spawn. NPC just stands there and all mobs aggro straight to you vs  initially aggro taken from the NPC. You are quickly overtaken on the first set of 4 mobs that spawn. 
**Steps to reproduce the behavior with as much detail as possible:**

1. I have tried repeating the quest 6 times and each time the NPC does not assist and am quickly taken over by the 4 mobs that spawn.
2. 
3. 

**IDs of affected creatures, items, quests or spells with a link to the relevant page:**

NPC: https://database.turtle-wow.org/?npc=4484
Item: https://database.turtle-wow.org/?item=
Quest: https://database.turtle-wow.org/?quest=976
Spell: https://database.turtle-wow.org/?spell=
Object: https://database.turtle-wow.org/?object=

**Expected behavior. Describe how it should work:**

From videos I have seen of the quest, the quest giver Feero Ironhand should assist with the mobs that spawn and gain initial aggro as well as continue to fight along side you.

**Comment by ratkosrb** [comment]
https://github.com/slowtorta/turtle-wow/commit/34cbdaa8e6c677fc8591a03dc97c8c2e6f25fd1d
