### ISSUE TITLE
Mounting up in shadowform visual bug

### ISSUE THREAD

**Issue by rolfjohnny** [slowtorta/turtlewow-bug-tracker#2756]
When I mount up in shadowform it changes how shadowform looks. When I dismount the bug persists until I cancel shadowform and cast it again.

1. Cast Shadowform
2.  Mount Up

Spell: https://database.turtle-wow.org/?spell=15473

**Comment by slowtorta** [comment]
Unfortunatelly it's the bug of the original game spell effect from 2004 and we wouldn't know how to make it any different.
