### ISSUE TITLE
Lunar festival quests did not reset

### ISSUE THREAD

**Issue by geojak** [slowtorta/turtlewow-bug-tracker#2758]
**Please, provide a clear description what the bug is:**

Basically the same issue blizzard had in wow, clsssic
https://us.forums.blizzard.com/en/wow/t/lunar-festival-elders-are-not-reset/859064/5
Lunar fesrivsl progress should reset each year, just like the Christmas presents (which also didn't reset) so yiu can do them every year again

**Expected behavior. Describe how it should work:**

I should be able to get coins from all elders again this year. But can't :(

**Comment by ratkosrb** [comment]
This should be fixed after the next update. I added a system to reset marked quests if completed in the previous year.
