### ISSUE TITLE
The Razorfen Kraul entry in "looking for turtles" has a wrong level range

### ISSUE THREAD

**Issue by AstridCone** [slowtorta/turtlewow-bug-tracker#2759]
And that's all there is to it really. Its leading to people of appropriate level not really queueing for it it would seem. Its set to (29 - 38) when the mobs there are at most only level 33!

Maybe this is deemed correct or whatever, but it sure seems out of whack to me

**Comment by Lexiebean** [comment]
29-38 is what https://wowpedia.fandom.com/wiki/Razorfen_Kraul_(Classic) says
