### ISSUE TITLE
'Suppression' talent (warlock) ineffective

### ISSUE THREAD

**Issue by Vikkyne** [slowtorta/turtlewow-bug-tracker#276]
**Please, provide a clear description what the bug is:**

**Three talent points in 'Suppression' should block resistance to shadow spells. However, as a lvl 14 warlock, I had a level 8 mob resist my Corruption lvl 2 spell (should not happen)**

**Steps to reproduce the behavior with as much detail as possible:**

**1.  Attack mob 5-6 levels lower than character, use Corruption (with Suppression talented to 3 points)
2. Attack until 'resist' result**

**IDs of affected creatures, items, quests or spells with a link to the relevant page:**

**Spell: https://database.turtle-wow.org/?spell= 18176**

**Expected behavior. Describe how it should work:**
**The mob should not be able to resist a shadow spell.**

I have concerns about the overall integrity of all the resistance-lowering talents in the game's talent trees at this point.

**Comment by Velite12** [comment]
Regardless of what your spell hit is, any caster will always have at least 1% chance to have their spell fully resisted.

**Comment by Vikkyne** [comment]
OK, I am seeing that with reference to PvP here:

https://classic-wow-archive.fandom.com/wiki/Resistance

Do we know that to be the case for players vs mobs?  I am just curious, and if possible would be cool to have some reference.

**Comment by Velite12** [comment]
Both, players v mobs and mobs v players, any spell has a 1% resist chance

**Comment by Vikkyne** [comment]
I have to agree, although it doesn't reference mobs (and the relationship between char-char, is sometimes diff than the mechanics between char-mob). So I can't counter the argument (which is fine). Thx for the attention to it.
