### ISSUE TITLE
Character is not receivingrested exp

### ISSUE THREAD

**Issue by Gilleeuy** [slowtorta/turtlewow-bug-tracker#2761]
**Please, provide a clear description what the bug is:**

**Steps to reproduce the behavior with as much detail as possible:**

1. Entering capital city or any Inn Character exp bar is not turning "blue" as indicator of receiving rested experience, no glyphs were bought from the beginning of character creation 
2. Tried leaving character at the Dolanaar Inn last te when I exit the game, after I logged back there were no rested experience accumulated 
3. Tried deleting cache folder, reloading game, exiting and entering capital Darnassus, no changes do experience bar and its color 
4. Character name Gilleeuy, Night Elf, Druid. 
**IDs of affected creatures, items, quests or spells with a link to the relevant page:**

NPC: https://database.turtle-wow.org/?npc=
Item: https://database.turtle-wow.org/?item=
Quest: https://database.turtle-wow.org/?quest=
Spell: https://database.turtle-wow.org/?spell=
Object: https://database.turtle-wow.org/?object=

**Expected behavior. Describe how it should work:**

**Comment by slowtorta** [comment]
Please check your keychain/bags for https://database.turtle-wow.org/?item=50520 or spellbook for this spell: https://database.turtle-wow.org/?spell=50020

**Comment by slowtorta** [comment]
![image](https://user-images.githubusercontent.com/66763404/215262831-769fb0bb-0e3e-4b2b-90a6-7d343ad05f80.png)

I logged in on your character and had no issues receiving rested experience. It's possible that you're using some addons that break the correct display of your experience bar?

**Comment by slowtorta** [comment]
Possible related to the area trigger DBC bug. Closing as duplicate for https://github.com/slowtorta/turtlewow-bug-tracker/issues/2748
