### ISSUE TITLE
The Pumpkin Thieves

### ISSUE THREAD

**Issue by Mu-ffi** [slowtorta/turtlewow-bug-tracker#2762]
**Please, provide a clear description what the bug is:**

Hi, 
there seems to be bug with The Pumpkin Thieves quest in Elwynn Forest. Quest description tells me to speak with Terry Palin in Eastvale Logging Camp but when I went to him, he doesn't have any dialogue option or anything really that would progress the quest. He just offer the Gnoll Bounty quest and thats all. When I try to collect the pumpins themself it says Invalid target. Screenshots bellow.
This bug also affects completing of Delicious pumpkin pie quest. 
I tried restarting the game, turning off all addons, clearing WDB folder and abbandoning and retaking the quest but nothing seems to help.

![WoWScrnShot_012723_115311](https://user-images.githubusercontent.com/57496310/215071539-0162b630-2a99-4f21-b05d-9ef877c30f71.jpg)
![WoWScrnShot_012723_114752](https://user-images.githubusercontent.com/57496310/215071570-eb5ad706-e544-49ed-af69-39a32b4b1c8d.jpg)
![WoWScrnShot_012723_114745](https://user-images.githubusercontent.com/57496310/215072458-33072ac9-d52d-4171-a412-29aa32123230.jpg)

**IDs of affected creatures, items, quests or spells with a link to the relevant page:**

NPC: https://database.turtle-wow.org/?npc=1650
Item: https://database.turtle-wow.org/?item=51325
Quest: https://database.turtle-wow.org/?quest=60041
Spell: 
Object: https://database.turtle-wow.org/?object=1000082

**Expected behavior. Describe how it should work:**
When I speak with Terry, he should have dialogue option to further progress the quest. Stolen elwynn pumpkins should be lootable.

**Comment by slowtorta** [comment]
Please clear your WDB folder, the quest no longer requires you talking to the guy.
