### ISSUE TITLE
High Elf Priest Racial Infomation for players

### ISSUE THREAD

**Issue by Ken92vold** [slowtorta/turtlewow-bug-tracker#2763]
**Please, provide a clear description what the bug is:**

**Steps to reproduce the behavior with as much detail as possible:**

1. There is no infomation when picking priest high elf, that you can get the priest "racial"
2.  Maybe have a quest for high elf priest at level 10 to get to the NPC 80966
3. 

**IDs of affected creatures, items, quests or spells with a link to the relevant page:**

NPC: https://database.turtle-wow.org/?npc=80966
Item: https://database.turtle-wow.org/?item=81012
Quest: https://database.turtle-wow.org/?quest=
Spell: https://database.turtle-wow.org/?spell=46042
Object: https://database.turtle-wow.org/?object=

**Expected behavior. Describe how it should work:**

**Comment by slowtorta** [comment]
The quest will be added in one of the future content updates.
