### ISSUE TITLE
Leader of the Pack / Trueshot Aura bugged out

### ISSUE THREAD

**Issue by Stianawne** [slowtorta/turtlewow-bug-tracker#2766]
**Please, provide a clear description what the bug is:**

**Steps to reproduce the behavior with as much detail as possible:**

1. Buffs like Trueshot Aura and Leader of the Pack is not applying correctly to all the members in the group.
2. This was first noticed by us <Clickers> last Sunday during Naxxramas, when Leader of the Pack would not apply to Warriors or Rogues, but it worked for hunters. Then after the Druid with Leader of the pack relogged and even redid his talents to try and make it work, it stopped working for Hunters in the group as well as for himself.
3. During this weeks raids we have had similar issues with Trueshot Aura, and the issues with Leader of the Pack has continued. It seems random what classes get it or not and we have not been able to fix it on our own. We also don't know what causes this. It just seems random whether it works or not, but it stays that way for the entire raid.
4. I do not know if this happens with other similar buffs like Moonkin Aura or others.

**IDs of affected creatures, items, quests or spells with a link to the relevant page:**

NPC: https://database.turtle-wow.org/?npc=
Item: https://database.turtle-wow.org/?item=
Quest: https://database.turtle-wow.org/?quest=
Spell: https://database.turtle-wow.org/?spell=
Object: https://database.turtle-wow.org/?object=

**Expected behavior. Describe how it should work:**

**Comment by cawilliamson** [comment]
This may not be related but I found that my Trueshot Aura was not applied to people PvP flagged in a raid group if I was not flagged myself.

**Comment by ratkosrb** [comment]
> This may not be related but I found that my Trueshot Aura was not applied to people PvP flagged in a raid group if I was not flagged myself.

This is the correct blizzlike behavior.

**Comment by cawilliamson** [comment]
> > This may not be related but I found that my Trueshot Aura was not applied to people PvP flagged in a raid group if I was not flagged myself.
> 
> This is the correct blizzlike behavior.

I wasn't reporting it as a bug. Was just thinking it may be the explanation for this issue the poster saw.
