### ISSUE TITLE
Bloodlord Mandokir's Threatening Gaze

### ISSUE THREAD

**Issue by Lexiebean** [slowtorta/turtlewow-bug-tracker#2767]
**This bug was reported to me, I'm unable to verify it.**

**Please, provide a clear description what the bug is:**

Bloodlord Mandokir's Threatening Gaze is apparently killing people that have DoTs or HoTs ticking

**Steps to reproduce the behavior with as much detail as possible:**

1. Have a DoT or HoT running
2. Be Threatening Gaze'd
3. Splat

**IDs of affected creatures, items, quests or spells with a link to the relevant page:**

NPC: https://database.turtle-wow.org/?npc=11382

**Expected behavior. Describe how it should work:**

Player's shouldn't go splat

**Comment by Gurky-Turtle** [comment]
I am unable to reproduce this at all. Going to close for now seeing its a report through someone else.
