### ISSUE TITLE
Silent Fang weapon proc

### ISSUE THREAD

**Issue by xASIVx** [slowtorta/turtlewow-bug-tracker#2768]
**Please, provide a clear description what the bug is:**
I believe the weapon Silent Fang is not procing correctly
**Steps to reproduce the behavior with as much detail as possible:**

When casting Judgement of the Crusader all other weapons' built in effects as well as applied enchantments and oils will proc 100% of the time, this was not the case for Silent Fang. To test this, I applied Frost oil to a weapon casted JotC on a target dummy at a distance, the oil proc'd everytime. When doing the same with Silent Fang, the oil proc'd roughly 50% of the time(only 5% for the built in Silence effect). To test it again, I auto attacked the same target dummy with the same two weapons under the same conditions(buffs) and the frost oil applied to Silent Fang proc'd 17% while proccing 25% on the other weapon.

**IDs of affected creatures, items, quests or spells with a link to the relevant page:**

https://database.turtle-wow.org/?item=13953
https://database.turtle-wow.org/?item=3829
https://database.turtle-wow.org/?npc=50516

**Expected behavior. Describe how it should work:**
Not sure but its most likely not doing procs correctly

**Comment by ratkosrb** [comment]
Effectiveness of JotC is greatly reduced on weapons with CC effects. The silence on Silent Fang falls in that category, as it would be too overpowered to be able to silence people every 8 seconds on demand.

**Comment by Galpala** [comment]
Some items also have internal cooldowns.
