### ISSUE TITLE
The quest 'Earned Reverence' does not grant reputation.

### ISSUE THREAD

**Issue by Qix03** [slowtorta/turtlewow-bug-tracker#277]
**Please, provide a clear description what the bug is:** The quest to receive your Rank 4 AV trinket, Earned Reverence ( https://classic.wowhead.com/quest=7170/earned-reverence ) does not grant reputation. It is supposed to grant 150 reputation with both Ironforge and the Stormpike Guard, but it does not grant it for either. I would assume this is also the case for the horde version.

**Steps to reproduce the behavior with as much detail as possible:**

1.
2. 
3. 

**IDs of affected creatures, items, quests or spells with a link to the relevant page:**

Quest: https://database.turtle-wow.org/?quest=7170

**Expected behavior. Describe how it should work:** Quest should reward 150 rep with Ironforge and Stormpike Guard.

**Comment by slowtorta** [comment]
Thanks for reporting it. It'll be fixed on the next server restart. Make sure to clear your WDB folder.
