### ISSUE TITLE
Zul'Farrak in wrong time zone

### ISSUE THREAD

**Issue by RUTHINAS** [slowtorta/turtlewow-bug-tracker#2770]
**Please, provide a clear description what the bug is:**
Upon entering Zul'Farrak, the server clock (which depends on whether the player is in Kalimdor or in the Eastern Kingdoms) makes a 12 hour leap. It can be nighttime inside the instance while it's daytime right outside in Tanaris, or vice versa.

I haven't checked, but this might also affect other instances on Kalimdor. It would be most obvious in the case of "outdoor" instances like Zul'Farrak, The Crescent Grove and parts of Maraudon (the last part with the large waterfalls has direct sky access) where the difference between day and night is visible. Indoor instances wouldn't be much affected, but the clock would nevertheless be misadjusted.

**Steps to reproduce the behavior with as much detail as possible:**

1. Take note of the time in Tanaris
2. Enter Zul'Farrak
3. Notice the 12 hour time shift
4. Repeat for other instances in Kalimdor to check if they are affected

**Expected behavior. Describe how it should work:**
Being on the same continent, Zul'Farrak should be in the same time zone as Tanaris.

**Comment by slowtorta** [comment]
Sorry, but we aren't going to alter instance day/night circle.
