### ISSUE TITLE
Tainted ooze casts Dark Sludge even after interrupted

### ISSUE THREAD

**Issue by xHucknasty** [slowtorta/turtlewow-bug-tracker#2772]
**Please, provide a clear description what the bug is:**
Title
**Steps to reproduce the behavior with as much detail as possible:**

1. 
2. 
3. 

**IDs of affected creatures, items, quests or spells with a link to the relevant page:**

NPC: https://database.turtle-wow.org/?npc=7092
Item: https://database.turtle-wow.org/?item=
Quest: https://database.turtle-wow.org/?quest=
Spell: https://database.turtle-wow.org/?spell=3335
Object: https://database.turtle-wow.org/?object=

**Expected behavior. Describe how it should work:**

**Comment by xHucknasty** [comment]
After further testing, I have learned something.  All of my bug reports involve me trying to interrupt with Earth Shock.  I used War Stomp and the ability was interrupted.  Possible this is an issue related to earth shock.

**Comment by Sringaram** [comment]
There's an issue on this server where skills that cannot be interrupted, are still shown as interrupted and the mob seemingly stops the cast but it still goes off. It's been reported before.

**Comment by mikefirefly** [comment]
> War Stomp does not interrupt it. It stuns the mob. The ability itself can't be interrupted no matter what you use (kick, pummel, earthshock, counterspell) as said in these wowhead comments.
> 
> https://www.wowhead.com/spell=3335/dark-sludge#comments

In the linked page it doesn't say anywhere that it cannot be interrupted.

Additionally, I am 99% sure the "step back" trick dosn't work on Turtle WoW. I've tested running away far more than 5 yards (more like 20) and I was still getting the debuff no matter what.

**Comment by balakethelock** [comment]
https://www.wowhead.com/tbc/spell=3335/dark-sludge#comments:id=2780528
