### ISSUE TITLE
Tier 3 Quest Progress and Completion Text

### ISSUE THREAD

**Issue by Aeliren** [slowtorta/turtlewow-bug-tracker#2773]
The progress and completion text for Tier 3 gear from questgivers in Light's Hope Chapel is incorrect, still being typo-filled placeholder text.

The progress text for all quests shows as the following:

"You got some missing parts for the quest please go and get them all!"

![image](https://user-images.githubusercontent.com/96898927/215302719-73bf1816-7d16-413f-9e40-efc7df498b70.png)

The completion text goes along the following lines:

"Exellent < name > !
, you got everything just as i asked and now i can make a [item name here]."

_Example:_
"Exellent < name > !
, you got everything just as i asked and now i can make a Cryptstalker Girdle."

![image](https://user-images.githubusercontent.com/96898927/215302726-aa0cd037-9fa1-4374-b482-9a3a9a336d58.png)

**Steps to reproduce the behavior with as much detail as possible:**

1. Complete the quest "Echoes of War" from Commander Eligor Dawnbringer.
2. Pick up any or all relevant Tier 3 quest for your class.
3. Look at the progress text; when you have the required items, look at the completion text.

**IDs of affected creatures, items, quests or spells with a link to the relevant page:**

NPC: Huntsman Leopold - https://database.turtle-wow.org/?npc=16132
NPC: Father Inigo Montoy - https://database.turtle-wow.org/?npc=16113
NPC: Korfax, Champion of the Light - https://database.turtle-wow.org/?npc=16112
NPC: Commander Eligor Dawnbringer - https://database.turtle-wow.org/?npc=16115
NPC: Rohan the Assassin - https://database.turtle-wow.org/?npc=16131
NPC: Mataus the Wrathcaster - https://database.turtle-wow.org/?npc=16133
NPC: Rayne - https://database.turtle-wow.org/?npc=16135
NPC: Rimblat Earthshatter - https://database.turtle-wow.org/?npc=16134
NPC: Archmage Angela Dosantos - https://database.turtle-wow.org/?npc=16116
Quest: Almost all Tier 3 quests, which can also be found here - https://database.turtle-wow.org/?quests=3.3456

**Expected behavior:**

The correct progress and completion text for all Tier 3 items can be found on Wowhead. As this amounts to 2 sets of dialogue over 8 quests per class for a total of 144 pieces of dialogue over 72 quests, I'll note down one set of fixes as example with links to both the Turtle WoW database and Wowhead so as not to clog this report:

**Cryptstalker Headpiece - https://database.turtle-wow.org/?quest=9056 / https://www.wowhead.com/classic/quest=9056/cryptstalker-headpiece:**
_Progress:_
Do you have the items I asked for, < class >?

_Completion:_
You are turning into a fearsome creature, < name >.

**Cryptstalker Spaulders - https://database.turtle-wow.org/?quest=9057 / https://www.wowhead.com/classic/quest=9057/cryptstalker-spaulders:**
_Progress:_
Do you have the items I asked for, < class >?

_Completion:_
I have taken special care in making these shoulders as large and pronounced as possible. Take my word for it; you're going to love them...

**Cryptstalker Tunic - https://database.turtle-wow.org/?quest=9054 / https://www.wowhead.com/classic/quest=9054/cryptstalker-tunic:**
_Progress:_
Do you have the items I asked for, < class >?

_Completion:_
They will fear you, <name>.

**Cryptstalker Girdle - https://database.turtle-wow.org/?quest=9060 / https://www.wowhead.com/classic/quest=9060/cryptstalker-girdle:**
_Progress:_
Do you have the items I asked for, < class >?

_Completion:_
A girdle fit for royalty! It's ready for you, < name >.

**Cryptstalker Handguards - https://database.turtle-wow.org/?quest=9059 / https://www.wowhead.com/classic/quest=9059/cryptstalker-handguards:**
_Progress:_
Do you have the items I asked for, < class >?

_Completion:_
Let the rage of the crypt fiend guide your hand, < name >.

**Cryptstalker Wristguards - https://database.turtle-wow.org/?quest=9061 / https://www.wowhead.com/classic/quest=9061/cryptstalker-wristguards:**
_Progress:_
Do you have the items I asked for, < class >?

_Completion:_
The wristguards are ready. Enjoy!

**Cryptstalker Legguards - https://database.turtle-wow.org/?quest=9055 / https://www.wowhead.com/classic/quest=9055/cryptstalker-legguards:**
_Progress:_
Do you have the items I asked for, < class >?

_Completion:_
As you don more of this armor, you will notice that your persona is changing. You will gain a preternatural ability for killing. Perhaps, even, a lust for blood.

Let it be said that I will not be held responsible for what chaos you may invoke...

**Cryptstalker Boots - https://database.turtle-wow.org/?quest=9058 / https://www.wowhead.com/classic/quest=9058/cryptstalker-boots:**
_Progress:_
Do you have the items I asked for, < class >?

_Completion:_
The boots are ready, < name >! Wear them well.

**Comment by redmagejoe** [comment]
This will likely take a while to correct, but given other quests have been getting proofreading of late, it's likely only a matter of time before this is resolved.
