### ISSUE TITLE
"Unity in Strength" quest, minor typo

### ISSUE THREAD

**Issue by MorlanOriginal** [slowtorta/turtlewow-bug-tracker#2777]
**Please, provide a clear description what the bug is:**
In quest progress text missing two commas.

**Steps to reproduce the behavior with as much detail as possible:**

1. Come in Durotar in Sen'Jin Village;
2. Speak to [Kor'ghan](https://database.turtle-wow.org/?npc=3189), take and complete [Study to Survive](https://database.turtle-wow.org/?quest=810);
3. Speak to [Kor'ghan](https://database.turtle-wow.org/?npc=3189) and take [Unity is Strength](https://database.turtle-wow.org/?quest=811);
4. Speak to [Kor'ghan](https://database.turtle-wow.org/?npc=3189) again.

**IDs of affected creatures, items, quests or spells with a link to the relevant page:**

NPC: [Kor'ghan](https://database.turtle-wow.org/?npc=3189);
Quest: [Unity is Strength](https://database.turtle-wow.org/?quest=811).

**Expected behavior. Describe how it should work:**
Add commas after _Be careful_ and _the scorpids_.
![WoWScrnShot_012923_211931_cr](https://user-images.githubusercontent.com/112715239/215352312-df79d831-7dea-4dc8-a39e-1cc8446f6a41.png)

**Comment by redmagejoe** [comment]
There are no commas necessary in this sentence, and in fact commas would make it grammatically incorrect.
