### ISSUE TITLE
Magic Mushroom (Stamina) has a deposit cost on the AH. Every other gardening food buff does not. Oversight?

### ISSUE THREAD

**Issue by ConcernedTurtler** [slowtorta/turtlewow-bug-tracker#2779]
Only pointing this out because every other farming food doesn't have a deposit cost on the AH, not even the magic mushrooms that provide 20str.  Only the stamina mushrooms cost money to put on the AH. Just wanted to make sure this wasn't an oversight or something.

Thank you.

**Comment by geojak** [comment]
I would argue the oversight is the other way round, that all the other ones should have a vendor value and deposit

**Comment by ConcernedTurtler** [comment]
I figured it's more likely they messed up one item instead of 8. There's a lot of other items in the game that have a 0 deposit.  bijous and coins for example.
