### ISSUE TITLE
Wandering Skeleton in WPL does not drop Outhouse Key

### ISSUE THREAD

**Issue by xHucknasty** [slowtorta/turtlewow-bug-tracker#2781]
**Please, provide a clear description what the bug is:**
Wandering Skeleton in WPL does not drop the Dalson Outhouse Key despite having a 100% drop rate in the wiki
**Steps to reproduce the behavior with as much detail as possible:**

1. Locate wandering skeleton at 48.3, 49
2. Defeat
3. Loot

**IDs of affected creatures, items, quests or spells with a link to the relevant page:**

NPC: https://database.turtle-wow.org/?npc=10816
Item: https://database.turtle-wow.org/?item=12738
Quest: https://database.turtle-wow.org/?quest=
Spell: https://database.turtle-wow.org/?spell=
Object: https://database.turtle-wow.org/?object=

**Expected behavior. Describe how it should work:**
Atleast according to the wiki the key should have a 100% drop rate.  I've killed the skeleton 3 times with no luck.  Just asking to confirm that the key is actually in the drop table.

**Comment by ratkosrb** [comment]
The item has a condition attached in order to drop. You must have completed quest "Mrs. Dalson's Diary".

**Comment by xHucknasty** [comment]
> The item has a condition attached in order to drop. You must have completed quest "Mrs. Dalson's Diary".

understood, thank you.  will check this before submitting future reports
