### ISSUE TITLE
can't swim

### ISSUE THREAD

**Issue by theolddude** [slowtorta/turtlewow-bug-tracker#2782]
**Please, provide a clear description what the bug is:**

**Steps to reproduce the behavior with as much detail as possible:**

1.character will not go under water to swim or move, pushing X button with no result. NO key bindings have been touched. character will sit and stand pushing X button but not go under water when standing on it. Deleted WDB and WTF with no help, Deleted all characters and started over, NO help. I just want to play.....
2. 
3. 

**IDs of affected creatures, items, quests or spells with a link to the relevant page:**

NPC: https://database.turtle-wow.org/?npc=
Item: https://database.turtle-wow.org/?item=
Quest: https://database.turtle-wow.org/?quest=
Spell: https://database.turtle-wow.org/?spell=
Object: https://database.turtle-wow.org/?object=

**Expected behavior. Describe how it should work:**

**Comment by ratkosrb** [comment]
You can't descend with X or ascend slowly with Space in water in the Vanilla client. Hold the right mouse button and aim with the mouse while pressing the button to go forward in order to go in the direction you want while swimming. If you have a water walking buff on you (or are a ghost), you need to aim your character at the water with the mouse, while holding the right mouse button, in order to stop walking on the surface and submerge.

**Comment by theolddude** [comment]
im not a ghost, it will not descend while pressing the x button.
uninstalled the whole game and it still does it. i have no buffs level 2,
just wont go under like it should.

**Comment by redmagejoe** [comment]
I don't believe you understand. Pressing sit to swim down and jump to swim up was introduced in Wrath of the Lich King. This is not Wrath of the Lich King. Therefore this is working as intended and is not a bug.

Topic can be closed: Working as Intended

**Comment by theolddude** [comment]
then how do i swim down bro

**Comment by Lexiebean** [comment]
> then how do i swim down bro

Hold right click, angle your camera down into the water and move forward

**Comment by theolddude** [comment]
It does go under water just not the way i thought and I was wrong, THANK
YOU for explaining it to the old guy, i had actually forgotten how but it
was this way when I first started many many moons ago. Thanks again for
being patient with the old guy.
