### ISSUE TITLE
Auberdine Inn isn't flagged as an Inn

### ISSUE THREAD

**Issue by LezChap** [slowtorta/turtlewow-bug-tracker#2783]
Auburdine Inn (the building with Innkeeper Shaussley (https://database.turtle-wow.org/?npc=6737)) does not appear to have the "Inn" flag.  You do not gain rested experience in this building, and must wait the 20 second counter to log out.

**Expected behavior. Describe how it should work:**
I believe this building is supposed to be flagged as an inn and allow immediate logout.

**Comment by ratkosrb** [comment]
I can't reproduce the issue. The "zzz" icon appears on my character as soon as I enter the Inn, which means I'm resting and can instantly log out.

![WoWScrnShot_013023_061351](https://user-images.githubusercontent.com/35845488/215386338-2ccd1966-396a-48e4-8b8e-e503afbf2f59.jpg)

**Comment by LezChap** [comment]
I reported it cause I was in there on my mage and couldn't get the resting zzzs to show up, and had the logout timer.  Going to log back over and see if I can replicate the issue on my end.
