### ISSUE TITLE
Solid chest in 25-30 zone contains items of lvl 5

### ISSUE THREAD

**Issue by AKryukov92** [slowtorta/turtlewow-bug-tracker#2784]
Solid chest located in Wetlands, Ashenvale and South Barrens contain items for low lvl.

Object: https://database.turtle-wow.org/?object=2850

I think most items with level requirement below lvl 20 are irrelevant in it.

I expect it to contain items requiring at least 20 lvl

**Comment by Gurky-Turtle** [comment]
@AKryukov92 could you please give us some examples? Also please compare it to the list here: https://www.wowhead.com/classic/object=2850/solid-chest#contains;0+3-19+1

**Comment by AKryukov92** [comment]
That list seems relevant.
Lowest green item level is [Grunt Axe](https://www.wowhead.com/classic/item=4568/grunt-axe)
In turtle solid chest 2850 there are 
[Notched Shortsword](https://database.turtle-wow.org/?item=727) for lvl 5
[Seer's Pants](https://database.turtle-wow.org/?item=2982) for level 15 in wowhead those pants are in https://www.wowhead.com/classic/object=75293/large-battered-chest#contains;mode:normal;0-2-19+1
in turtle those pants are contained in https://database.turtle-wow.org/?object=75293#contains:100+2-12+1 too

**Comment by slowtorta** [comment]
Fixed on the next update.
