### ISSUE TITLE
Bow Specialization doesn't seem to be accurately calculating for Trolls

### ISSUE THREAD

**Issue by suggney** [slowtorta/turtlewow-bug-tracker#2787]
**Please, provide a clear description what the bug is:**

Bow Specialization doesn't seem to be accurately calculating for Trolls; applying something like 0.6%-ish hit instead of 3% versus level 63 enemies.

**Steps to reproduce the behavior with as much detail as possible:**

1. Have a level 60 Troll hunter with a bow and 6% hit from gear
2. Auto shoot a level 63 boss dummy to establish a hit rate
3. Observe the non hit-capped results

**IDs of affected creatures, items, quests or spells with a link to the relevant page:**

Spell: https://database.turtle-wow.org/?spell=26290

**Expected behavior. Describe how it should work:**

You should be receiving 3% hit from Bow Specialization.

**Comment by redmagejoe** [comment]
Please provide empirical evidence (long-term damage / hit graphs as shown in other similar tickets) to confrim this issue.  Without substantial data and relying on unreliable UI elements from addons, it is difficult to tell if this is, in fact, not working.
