### ISSUE TITLE
Glimmering Ring of Retaliation proc chance seems too low, doesn't show in combat log

### ISSUE THREAD

**Issue by dropsera** [slowtorta/turtlewow-bug-tracker#2791]
**Please, provide a clear description what the bug is:**
Glimmering Ring of Retaliation, a custom item (of Retaliation being a random bonus) that reads as 10% chance on getting hit to cast a shdowbolt to the offender, doesn't feel like 10% at all.

From about 5 minutes of getting hit in the back by several mobs the ring (I had 2 equiped) proced 3 times total, while paladin talent Redoubt (10% chance on getting hit to get extra block) proced 18 times, also, Argent Defender shield (1% chance on getting hit to get extra block) proced 3 times. 

This leads me to believe that either the ring description is incorrect or it is coded wrong to proc about 1% instead of 10%.

As an addition, the ring's damage does not show in combat log at all, while damage numbers are visible on screen. 

**Steps to reproduce the behavior with as much detail as possible:**

1. Equip Glimmering Ring of Retaliaton
2. Get hit
3. Barely anything happens

**IDs of affected creatures, items, quests or spells with a link to the relevant page:**

https://database.turtle-wow.org/?item=6589

**Expected behavior. Describe how it should work:**

Proc more, silly ring!

**Comment by twowTurtReynolds** [comment]
I can't even create this item with .additem, it seems to have long been removed from drop tables.

Unfortunately that means we can't justify spending developer effort for a now deprecated item.
