### ISSUE TITLE
Quest: (Costly Menace) Bug

### ISSUE THREAD

**Issue by Chef16** [slowtorta/turtlewow-bug-tracker#2792]
**Please, provide a clear description what the bug is:**

Killing the mountain lion does not give credit for killing the mountain lion?

**Steps to reproduce the behavior with as much detail as possible:**

1. Kill Mountain Lion x8
2. Receive credit for kills x8  <<<< problem
3. Turn in quest?

**IDs of affected creatures, items, quests or spells with a link to the relevant page:**

NPC: https://database.turtle-wow.org/?npc=2406
Quest: https://database.turtle-wow.org/?quest=564

**Expected behavior. Describe how it should work:**

Expected the kills to give credit towards the quest, the mountain lions themselves have the tag that shows that they are the ones required for the quest. The kills do not give credit towards the quest. Unsure how i have 1/8 since i believe i logged off with multiple accredited kills and now the number is 1 and not budging no matter how many felines i maim.

![Mountainbastards](https://user-images.githubusercontent.com/124081172/215842325-7bdd45f9-58e3-43b0-bd7a-008d9b82fc92.png)

**Comment by cyaohiri** [comment]
It could just be a visual bug. Try to close the game, delete your WDB folder, and see if you get the credit. If it's still not updating, make sure you have killed 8 in total as it sometimes gets fixed when you kill all that are needed, and quest changes state to complete.
