### ISSUE TITLE
Swamp of Sorrow Spiders 40-42lvl they leave combat after 15sec and re-enter combat

### ISSUE THREAD

**Issue by Merlinthewis** [slowtorta/turtlewow-bug-tracker#2794]
**Please, provide a clear description what the bug is:**

**Steps to reproduce the behavior with as much detail as possible:**

1.pleas check the Spiders in Swamp of Sorrow, after being in combat for 15+ secconds there HP resets, making Mage aoe farming impossible while also making the game broken and break on it self...for a classic experience this game bug killed me 3 times so far...pleas fix this cuz the mobs leave combat after 15 sec in combat....this is BROKEN
2. 
3. 

**IDs of affected creatures, items, quests or spells with a link to the relevant page:**

NPC: https://database.turtle-wow.org/?npc=
Item: https://database.turtle-wow.org/?item=
Quest: https://database.turtle-wow.org/?quest=
Spell: https://database.turtle-wow.org/?spell=
Object: https://database.turtle-wow.org/?object=

**Expected behavior. Describe how it should work:**

**Comment by redmagejoe** [comment]
Cannot reproduce on current version. Be sure you are not dragging the spiders outside their leash radius without doing any damage to them, or they will reset.

Working as intended.
