### ISSUE TITLE
Taking 6k fall damage when the fall damage should be 0

### ISSUE THREAD

**Issue by Stianawne** [slowtorta/turtlewow-bug-tracker#2795]
**Please, provide a clear description what the bug is:**

**Steps to reproduce the behavior with as much detail as possible:**

1. Taking 6k fall damage from falling 5cm. No, I'm not joking.
2. Tauren character. This might only happen with Plainsrunning active. It seems very random, I have not been able to recreate this issue, but it happens at random times when walking and taking a small drop. 
3. 

**IDs of affected creatures, items, quests or spells with a link to the relevant page:**

NPC: https://database.turtle-wow.org/?npc=
Item: https://database.turtle-wow.org/?item=
Quest: https://database.turtle-wow.org/?quest=
Spell: https://database.turtle-wow.org/?spell=
Object: https://database.turtle-wow.org/?object=

**Expected behavior. Describe how it should work:**

**Comment by Stianawne** [comment]
Can confirm this is NOT tied to plainsrunning.

**Comment by geojak** [comment]
Posbly related to the changes in https://github.com/slowtorta/turtlewow-bug-tracker/issues/2675

**Comment by RUTHINAS** [comment]
This happened to a shaman on our Sunken Temple run. At the stairs that circle down all the way to the bottom of the dungeon, the shaman abruptly died. We were in combat, so they used reincarnation and moved from their position, so I could never find the exact location where it happened, and was unable to replicate. The damage, however, was attributed to falling, despite there being only a low angle ramp that we went down.

It would seem to me that the game had problems checking whether the character is in solid ground or not, and the fall damage was somehow accumulating until some part of the stairs or floor was reached, and the fall damage applied (it did maximum damage, ie. 100% of the health pool).

If I recall correctly, this was after the slow fall fix was done. I can try looking through screen shots if I can find a way to confirm the timing.

**Comment by slowtorta** [comment]
This issue is present in this core since approx. 8 years. Sadly, no solution had been found yet. We're aware of this bug, there's been several similar bug reports about it in our tracker.
