### ISSUE TITLE
Lingering spell effects.

### ISSUE THREAD

**Issue by Stianawne** [slowtorta/turtlewow-bug-tracker#2796]
**Please, provide a clear description what the bug is:**

**Steps to reproduce the behavior with as much detail as possible:**

1. Lingering spell effects in the game.
2. Effects that come from Tranquility, Hurricane, Frost Nova (the effect that is around the character) never goes away unless i relog. This happens everywhere, in instances, raids, Battlegrounds etc. The effects do not disappear unless I relog. This issue will persist through infinite numbers of the same instance loaded, i.e. Alterac Valley, where it just keeps adding on between every BG started/ended.
3. This also happens with effects in an instance, such as the green Gass/fumes in the tunnel from Grobbulus to Gluth.
4. This also might effect other effects in the game as Poison Clouds from Grobbulus are invisible (this has nothing to do with my graphics settings), but I can not confirm that this is related.

**IDs of affected creatures, items, quests or spells with a link to the relevant page:**

NPC: https://database.turtle-wow.org/?npc=
Item: https://database.turtle-wow.org/?item=
Quest: https://database.turtle-wow.org/?quest=
Spell: https://database.turtle-wow.org/?spell=
Object: https://database.turtle-wow.org/?object=

**Expected behavior. Describe how it should work:**

**Comment by redmagejoe** [comment]
This is an intermittent issue experienced by some players and not by others, and seems to affect the same players or not after updates. I can only assume this is something clientside, but unfortunately there is nothing concrete or reproducible to meaningfully address this bug.

Cannot reliably reproduce.

**Comment by slowtorta** [comment]
This is totally client-side.
https://nostalrius.org/viewtopic.php?f=76&t=30228

**Comment by slowtorta** [comment]
It's probably one of those "20 year old client running on modern software" issues we cannot possibly resolve. Unless there's more information provided on this matter, we cannot do much.
