### ISSUE TITLE
Brood of Nozdormu Rep Reset to Hostile

### ISSUE THREAD

**Issue by MunchkinPoncho** [slowtorta/turtlewow-bug-tracker#2797]
**Please, provide a clear description what the bug is:**

Hi this Shokisan, Human Paladin.
uh oh. so my ticket is, Brood of Nozdormu reset to Hostile for me, when I should've gone to Revered. It happened after I accepted the quest for Avenger's Chestplate, and then mounte}d up in AQ40, then got rep from team members killing something. I went to Hostile. Since doing 1 AQ40, it's back up to Friendly.

**Steps to reproduce the behavior with as much detail as possible:**

1.  Accept Avenger's Chestplate Quest (it was after 1st boss)
2.  Mount up on yellow mount
3.  Get rep from guildies killing mob, then my rep reset to Hostile.

I think I was close to Revered when it happened? I was Honored already when it reset to Hostile suddenly. I quick;y got back up to Friendly just with 1 AQ40 tho. But I should probably be at Revered. Strange bug.

**Comment by twowTurtReynolds** [comment]
![image](https://github.com/slowtorta/turtlewow-bug-tracker/assets/151180101/14c08c38-ee0e-4194-845b-9a96c747fe90)

I then went and killed a bunch of mobs and didn't get set back down.

Looks like this is long solved.
