### ISSUE TITLE
Belnistrasz can't be healed

### ISSUE THREAD

**Issue by AKryukov92** [slowtorta/turtlewow-bug-tracker#2799]
Belnistrasz https://database.turtle-wow.org/?npc=8516
can't be healed during the quest Extinguishing the Idol https://database.turtle-wow.org/?quest=3525
When you target him and cast healing spell (tried Regrowth, Rejuvination) you cast this spell on yourself.
This is an escort quest and ability to heal him is important.
There are multiple waves of mobs which spawn very close to him and attack him first.

It should be possible to heal him and buff.

**Comment by ratkosrb** [comment]
This will remain as it is, since its blizzlike, and some people are against making it easier.

**Comment by AKryukov92** [comment]
@ratkosrb may be it is possible to spawn mobs a little further from Belnistrasz? In some of tonnels leading to that cave.
Because now they spawn in melee distance and immediately do autoattack.
