### ISSUE TITLE
Dark Ranger Lanissa (Hunter Trainer) non-responsive.

### ISSUE THREAD

**Issue by DaddyM0E** [slowtorta/turtlewow-bug-tracker#28]
By opening this Issue, I admit to having done the pertinent research using sources from Vanilla (preferably) or Classic. I also understand that sources from other private servers are not acceptable.

**Current behavior**: Does not respond to mouse "clicks" and open training window.

**Expected behavior**: Open training window to purchase skills for Hunter class

**Proofs**: I have 3 hunters on the server. All 3 are Orc. (This *is* in "undead" territory but I know the lay-of-the-land there and like to level my Horde toons there when possible.) The NPC does not respond to any of them. Further, when I look into the Turtle-WoW DB and search for this NPC, the graphic for the NPC is what I would refer to as a "Shambling Mound" and not the Blond Elf with red eyes as portrayed in-game.

**Steps to reproduce**:

1. Honestly, I haven't brought any other horde race to speak with the NPC besides my Orcs.
2. 
3.

**Comment by slowtorta** [comment]
Thanks for reporting it. It's fixed and will be deployed on the next server update.
