### ISSUE TITLE
Mercutio is Dead!

### ISSUE THREAD

**Issue by redmagejoe** [slowtorta/turtlewow-bug-tracker#2800]
[Image](https://i.imgur.com/EE7b2Ky.png)

Upon speaking to [Squire Rowe](https://database.turtle-wow.org/?npc=17804) while the quest [Stormwind Rendezvous](https://database.turtle-wow.org/?quest=6402) is in progress and selecting the option to summon [Reginald Windsor](https://database.turtle-wow.org/?npc=12580), a script is meant to occur where Windsor rides in on his horse, [Mercutio](https://database.turtle-wow.org/?npc=12581).  After dismissing his horse, Mercutio is meant to run back into Elwynn and then despawn (see: fade out / vanish).

Currently, the horse falls over dead at the end of its path rather than seamlessly disappearing, resulting in the ability to pile up a mound of dead Mercutios and looking quite grim.  Not to mention it's just not the way it properly works.

**Comment by Letic92** [comment]
Fixed.
