### ISSUE TITLE
Issue with Hit and Crit

### ISSUE THREAD

**Issue by kingalion** [slowtorta/turtlewow-bug-tracker#2801]
Hello.Lately I had an issue with my hit and crit in ret paladin character. I miss more than i used to (I don't hit in general like dodge ..etc). Also I crit way less than I used to. Something just feels off. I'm a human with a 2h sword and with bonus 2% hit from items ( so that makes 5% hit out of 9% hit cap for bosses and lvl 63 enemies so i dont think my hit% is that bad, also the enemies i face now are most my level or below my level ). the same goes with crits they happen way less than i was used to. I thought at first it might be RNG something like bad luck but the issue persists. Is there a way to know if it is in fact bad luck or im making a mistake somewhere or if it is in fact a bug or something.

**Comment by geojak** [comment]
Who knows, I am not a dev and also just a player but Why not test against the target dummies uncontrolled environmental where you know what your hut and crit should be.
Use a addon to track and then make a proper bug report

**Comment by kingalion** [comment]
Hey, can u tell me an addon like that. I pretty sure something is wrong.

**Comment by kingalion** [comment]
Hey, I dont know how much it usually takes to get a response for issues submitted , but it took kinda a long time .

**Comment by software-eugeneer** [comment]
+1 

Tried to check hit rating with
https://github.com/yutsuku/BetterCharacterStats
https://github.com/Linae-Kronos/StatCompare
API calls:
GetCombatRating()
GetCombatRatingBonus()
GetHitModifier()

![image](https://user-images.githubusercontent.com/45651092/220049656-d67e2ace-9e68-443a-8edb-41cd76e16f52.png)

**Comment by kingalion** [comment]
I didnt pick percision

**Comment by kingalion** [comment]
These addons might only count items with +hit %

**Comment by software-eugeneer** [comment]
First I thought the same, but below there was a screenshot from a friend of mine who is playing rogue, and using same addon 5% hit from rogue talent tree was displayed. Of course this could be something addon specific, but if this is any API call or other method that would allow me to confirm hit rating value - would be awesome (c'mon its potentially 8 garbage talent points :) )

**Comment by kingalion** [comment]
What about weapon specialization racial thing? should it be shown?
I hope we get a response soon.

**Comment by software-eugeneer** [comment]
you mean with addon?
it appears that addon is just picking value from talents ([read more](https://github.com/slowtorta/turtlewow-bug-tracker/issues/1657#issuecomment-1438231161), but i still have a feeling like something is wrong with this hit.

**Comment by kingalion** [comment]
I tried to level up a caster ( warlock) and the same problem happened with me. I get more resists than usual ( one time i got 3 resists in a row from a level 30 enemy when i was level 31, it just happens too often). I really think those two issues are related.
