### ISSUE TITLE
[Plans: Rune-Etched Breastplate] not searchable in A.H.

### ISSUE THREAD

**Issue by gorxen** [slowtorta/turtlewow-bug-tracker#2804]
**Steps to reproduce the behavior with as much detail as possible:**

1. Put [Plans: Rune-Etched Breastplate] [https://database.turtle-wow.org/?item=83503](url) on the auction house for sale.
2. Search for it, with any character or any account you will not find it, cause for some reason it doesn't come out in the search results, however I DO see it listed on my active auctions tab.

**Expected behavior. Describe how it should work:**

The recipe should appear when searched for.

**Comment by slowtorta** [comment]
![image](https://user-images.githubusercontent.com/66763404/216835631-f8dca386-fc90-4211-b082-273e430583db.png)

No issues. I'm sorry but the bug is on your side. Probably a bad AH addon?
