### ISSUE TITLE
Quest Reward - Chillwind Armor - Not working

### ISSUE THREAD

**Issue by Galpala** [slowtorta/turtlewow-bug-tracker#2805]
The item, Chillwind Armor, quest reward from the quest Chillwind Armor, does not proc. The chest item has a Chance on Hit: [Inflicts 5 to 8 Frost damage to an enemy every 3 sec., slowing its movement speed by 1% for 12 sec.]

**Comment by ratkosrb** [comment]
Only weapons can have Chance on Hit effects. It will never proc if its assigned to a non-weapon item, as you cant attack people with a chest piece. Seems whoever designed that item screwed up.
