### ISSUE TITLE
Missing icon on Theradras' Shed Tear

### ISSUE THREAD

**Issue by KlumzByte** [slowtorta/turtlewow-bug-tracker#2806]
**Please, provide a clear description what the bug is:**
The item Theradras' Shed Tear from the quest "An Honorary Gelkis" is missing the icon.

Clearing the WDB folder did not fix the issue.

![image](https://user-images.githubusercontent.com/5812155/216831875-04f38545-82d3-4aa8-ae23-a4a49fbbbf7a.png)

**Steps to reproduce the behavior with as much detail as possible:**

1. Aquire the item with ID: 60859.
2. Check for missing Icon.

**IDs of affected creatures, items, quests or spells with a link to the relevant page:**

Item: https://database.turtle-wow.org/?item=60859
Quest: https://database.turtle-wow.org/?quest=40629

**Expected behavior. Describe how it should work:**
The item should have an icon.

**Comment by 1Szatesz1** [comment]
Yea it don't have an own icon and always copy other item's icon if u move it within your invertory.

**Comment by Dragunovi** [comment]
Remember to delete your WDB folder for item fixes to be visible.
