### ISSUE TITLE
World buffs

### ISSUE THREAD

**Issue by mraa9** [slowtorta/turtlewow-bug-tracker#2807]
hi i seem to have a problems with World buffs

I have problems receiving the buffs like Onyxia Buff or Rend buff 
I'm not sure what's the issue but whenever I'm in a major city and a world buff is about to drop i don't receive the buff. 
i Have no problems with receiving DMF buffs  

Please help and ty

**Comment by Gurky-Turtle** [comment]
@mraa9 where are you standing in the city? There are certain areas where you have to be.

**Comment by mraa9** [comment]
> @mraa9 where are you standing in the city? There are certain areas where you have to be.

i was standing in the tent area in the Xroads the barrens and i was standing near the Ah in orgimmar

**Comment by Gurky-Turtle** [comment]
Not sure about xroads but you have to be outside of any buildings in org and by the bank.

**Comment by mraa9** [comment]
> Not sure about xroads but you have to be outside of any buildings in org and by the bank.

i was out of the building 
does warmode glyph have to do anything with the buffs?

**Comment by Gurky-Turtle** [comment]
The glyph should not affect anything. 

If you can provide a video of the next time it happens it will be helpful.

**Comment by Lexiebean** [comment]
What is your reputation with Org?

**Comment by Zmitrok1984** [comment]
Are you have [Supercharged Chronoboon Displacer](https://database.turtle-wow.org/?item=83001) in bags?

**Comment by Gurky-Turtle** [comment]
@Sringaram in stormwind try being directly in the middle of the trade district by the tree.

**Comment by mraa9** [comment]
> What is your reputation with Org?

I'm neutral  2771/3000
leveling still tried getting the WBs to make leveling easier and this incident happened with me couple of times and I'm still confused why I'm not able to get the buffs 

i have Warmode glyph

**Comment by Gurky-Turtle** [comment]
@mraa9 check the reputation tab and make sure you are not at war with them.

**Comment by mraa9** [comment]
> @mraa9 check the reputation tab and make sure you are not at war with them.

Im not in war with org rep

**Comment by Lexiebean** [comment]
I've heard that you need to be friendly with Org/SW to get them.

**Comment by balakethelock** [comment]
You need to be friendly to benefit from warchief's blessing. The same could also be true for dragonslayer's cry.
