### ISSUE TITLE
OnEvent() update not working for trinkets slots

### ISSUE THREAD

**Issue by guruvex** [slowtorta/turtlewow-bug-tracker#2808]
**Please, provide a clear description what the bug is:**
in my addon when i swap trinkets it no longer triggers an update. all the other slots will trigger it.

**Steps to reproduce the behavior with as much detail as possible:**

1. here is the addon i am using and was working till last update https://github.com/guruvex/Avoidance
2. do /avoid show to show the window.
3. when you swap gear the avoidance total updates except the trinket slots.

**IDs of affected creatures, items, quests or spells with a link to the relevant page:**
**Expected behavior. Describe how it should work:**
when swapping trinkets it should update like all other slots. (it was working before the last update) and nothing in the addon changed.

**Comment by Zeyla-TW** [comment]
This would best best addressed to the addon creator, or by searching for another version. Turtle WoW doesn't adjust the API that addons use to function, so the problem lies with the addon itself.

**Comment by slowtorta** [comment]
It's possible that the issue lies with the item itself. Try with different trinkets from Vanilla and if it works, re-open it with the name of the troublesome item.
