### ISSUE TITLE
Kasui

### ISSUE THREAD

**Issue by Tim100290** [slowtorta/turtlewow-bug-tracker#2810]
**My character Kasui, does not gain any experience anymore. Seems she missed already a few thousends. XP bar stuck at 1404 XP.
And the spell "blessing of freedom" has no effect / is not working**

**Steps to reproduce the behavior with as much detail as possible:**

1.
2. 
3. 

**IDs of affected creatures, items, quests or spells with a link to the relevant page:**

NPC: https://database.turtle-wow.org/?npc=
Item: https://database.turtle-wow.org/?item=
Quest: https://database.turtle-wow.org/?quest=
Spell: https://database.turtle-wow.org/?spell=
Object: https://database.turtle-wow.org/?object=

**Expected behavior. Describe how it should work:**

**Comment by Tinyfin-github** [comment]
Hello.

Please try to re enable experience using the command .xp on

**Comment by Tim100290** [comment]
> 

what exactly I have to type in the chat?
