### ISSUE TITLE
Netherwind Pants trasmog 

### ISSUE THREAD

**Issue by FazakasAlexandra** [slowtorta/turtlewow-bug-tracker#2812]
Netherwind Pants do not appeared transmogrified into Regal Leggings or Embroidered Pants for other players on their client.

**Steps to reproduce the behavior:**

1. Wear Netherwind Pants
2. Transmogrifie Netherwind Pants into Regal Leggings
3. You see yourself wearing bikini, not Regal Leggings
4. Ask another player to tell you if transmog shows 
5. He sees you wearing bikini, not Regal Leggings
5. Log out and delete your WDB folder then login again
5. You see yourself wearing Regal Leggings
7. Ask the player to tell you if transmog shows
8. He sees you wearing bikini, not Regal Leggings
9. Ask the player to delete their WDB folder then login again
10. Ask the player to tell you if transmog shows
11. He sees you wearing bikini, not Regal Leggings

**IDs of affected creatures, items, quests or spells with a link to the relevant page:**

Item Netherwind Pants: https://database.turtle-wow.org/?item=16915
Item Regal Leggings: https://database.turtle-wow.org/?item=7469
Item Embroidered Pants: https://database.turtle-wow.org/?item=2437

**Expected behavior:**
1. Wear Netherwind Pants
2. Transmogrifie Netherwind Pants into Regal Leggings
3. You see yourself wearing Regal Leggings
4. Ask another player to tell you if transmog shows
5. He sees you wearing Regal Leggings

**Comment by slowtorta** [comment]
Please make sure your client is not in read-only.
