### ISSUE TITLE
Holy Fire and Holy Nova are still using old scaling values

### ISSUE THREAD

**Issue by Silbotronic** [slowtorta/turtlewow-bug-tracker#2816]
According to the priest changes page on turtle-wow: 
_Holy Fire initial damage component scaling has been adjusted: (0.75 → 0.857) 
Holy Nova talent damage component scaling has been adjusted: (0.107 → 0.161)_ 

These changes have **not** been implemented as the spells are still using their old spell damage scaling values.

**Steps to reproduce the behavior with as much detail as possible:**

1. Equip some spell damage gear (100+)
2. Cast low ranks of Holy Fire/ Holy Nova

**IDs of affected creatures, items, quests or spells with a link to the relevant page:**

https://database.turtle-wow.org/?spell=15261
https://database.turtle-wow.org/?spell=27801

**Expected behavior. Describe how it should work:**
Holy Fire and Holy Nova should use the updated spell damage scaling values shown on the priest changes page:
https://turtle-wow.org/#/priest

**Comment by ConcernedTurtler** [comment]
any update on this?

**Comment by Silbotronic** [comment]
I tried both spells today and it seems this has been stealth fixed, so I'm closing this.
