### ISSUE TITLE
problem with ench shaman...

### ISSUE THREAD

**Issue by ivanku4eto** [slowtorta/turtlewow-bug-tracker#2817]
hello there GM you tell me to open ticket here there you go now i have problem with my shaman when i use totems more then 5 times they stop to work i mean i put it in ground and then do it 4 more times after this they stop to give me bonus from totem i chek the abilities but nothing happen they just dont work when i logout from game and log again everything is fine and after 5 times use totems is going the same thing pls help me i try to delete game and downloaded again but not work still i have this problem i disable all addons and notthing help to slove problem

**Comment by redmagejoe** [comment]
I am assuming this ticket is saying "spamming a totem with a buff too many times causes the buff to stop applying." I cannot reproduce this behavior on current version.
