### ISSUE TITLE
TW Database for browsing Misc Armor items does not work

### ISSUE THREAD

**Issue by burmanj** [slowtorta/turtlewow-bug-tracker#2818]
The TW database for browsing items does not work for Items/Armor/Miscellaneous. Everything forwards to shirts except cloaks that forwards to cloth heads for some reason.

Link here: https://database.turtle-wow.org/?items=4.0

**Comment by burmanj** [comment]
This seems to be the same issue with all armor types. Nothing is really being sorted into the different slot categories

**Comment by slowtorta** [comment]
@CosminPOP
