### ISSUE TITLE
Pedestal in front of Uldum is not spawned correctly

### ISSUE THREAD

**Issue by dagigliotti** [slowtorta/turtlewow-bug-tracker#2819]
When trying to complete quest Seeing What Happens, there is no pedestal to interact with outside Uldum.  I can see the shadow but cursor does not change to gear to interact. 

![image](https://user-images.githubusercontent.com/107203299/217993698-08fa1378-b376-4969-a1f4-05b1a077fc2b.png)

**Comment by Tinyfin-github** [comment]
The pedastal is removed until some bugs are fixed.
