### ISSUE TITLE
Too many Mosh'Ogg Witch Doctors 

### ISSUE THREAD

**Issue by AKryukov92** [slowtorta/turtlewow-bug-tracker#2820]
Too many witch doctors
![image](https://user-images.githubusercontent.com/24266616/218009220-8a19506c-e2df-4998-ad7f-8fb6eb3fcbcb.png)
In quest [The Defense of Grom'gol](https://database.turtle-wow.org/?quest=569)
You ordered to kill 5 Witch doctors and 10 brutes, but their only camp filled only with witch doctors. 7 in camp and 3 outside of camp.
In the same time, there are only 4 brutes around. It would be cool if their numbers will be adjusted. May be more brutes to be added.

[Mosh'Ogg Witch Doctor](https://database.turtle-wow.org/?npc=1144)
[Mosh'Ogg Brute](https://database.turtle-wow.org/?npc=1142)

**Comment by Kangaroux** [comment]
Brutes and witch doctors share the same spawn locations so this can happen especially if no one kills the witch doctors. The same issue happens for the Headhunters in STV and the harpies in Stonetalon.

Ideally there would be a limit to prevent situations like this, like preventing witch doctors from spawning if 60% of their spawn locations already have a witch doctor.
