### ISSUE TITLE
Signet of the Zandalar

### ISSUE THREAD

**Issue by Madliv21** [slowtorta/turtlewow-bug-tracker#2822]
Hello,

The stamina version of the signet of the zandalar shoulder enchant can be applied to other players which makes the whole reputation grind obsolete.

**Steps to reproduce the behavior with as much detail as possible:**

1. Buy the enchant for 15 tokens
2.  Enchant it to other player
3. 

**IDs of affected creatures, items, quests or spells with a link to the relevant page:**

NPC: https://database.turtle-wow.org/?npc=https://www.wowhead.com/classic/npc=14921/rinwosho-the-trader
Item: https://database.turtle-wow.org/?item=
Quest: https://database.turtle-wow.org/?quest=
Spell: https://database.turtle-wow.org/?spell=
Object: https://database.turtle-wow.org/?object=

**Expected behavior. Describe how it should work:**

Should not work, like the other enchants

**Comment by slowtorta** [comment]
Will be fixed on the next update.
