### ISSUE TITLE
Carver Molsen's loot box timing

### ISSUE THREAD

**Issue by ConspicuousMoo** [slowtorta/turtlewow-bug-tracker#2824]
The loot box that contains items to complete the Carver Molsen quest takes too long to respawn.  For an elite quest that normally requires grouping, perhaps the respawn time could be lowered?  He respawns faster than the loot box does.

Steps to reproduce the behavior with as much detail as possible:

1.  Kill Carver Molsen
2.  Loot box
3. 

IDs of affected creatures, items, quests or spells with a link to the relevant page:

Quest: https://database.turtle-wow.org/?quest=40602

Expected behavior. Describe how it should work:

Lower respawn timer to 10 seconds or something?

**Comment by Kruxis** [comment]
Greetings adventurer! 

This issue has been looked into and will be fixed on next server restart.
Safe Travels!
