### ISSUE TITLE
Ultrasafe Transporter: Gadgetzan issue

### ISSUE THREAD

**Issue by Neglected2013** [slowtorta/turtlewow-bug-tracker#2825]
**Please, provide a clear description what the bug is:**
I am unable to use my Ultrasafe Transporter: Gadgetzan trinket after crafting despite learning Gnomish engineering and having the gnome engineer membership card.
**Steps to reproduce the behavior with as much detail as possible:**

1. Create Ultrasafe Transporter: Gadgetzan
2. Attempt to equip, but it failed for my character. (Even deleted WDB folder in hopes it fix it, but still didn't work)

**IDs of affected creatures, items, quests or spells with a link to the relevant page:**

NPC: https://database.turtle-wow.org/?npc=7406
Item: https://database.turtle-wow.org/?item=18986

**Expected behavior. Describe how it should work:**

**Comment by Kangaroux** [comment]
@Neglected2013 What error do you get when you try to equip it?

**Comment by Zeyla-TW** [comment]
Are you using an item that gives you a bonus to your engineering skill to reach 265?

**Comment by Neglected2013** [comment]
@Kangaroux the error is that I am unable to use the gadgetzan teleporter despite being a gnomish engineer. 

@Zeyla-TW Nope, I'm not using any item to boost my skill but my engineering is 300/300, so I don't think I need it.

**Comment by Gurky-Turtle** [comment]
I cannot reproduce this, we will need more information.

**Comment by twowTurtReynolds** [comment]
No information has been given after 6 months.
