### ISSUE TITLE
BG que

### ISSUE THREAD

**Issue by d-u-b** [slowtorta/turtlewow-bug-tracker#2827]
**Please, provide a clear description what the bug is:**

**Steps to reproduce the behavior with as much detail as possible:**

1.
2. 
3. 

**IDs of affected creatures, items, quests or spells with a link to the relevant page:**

NPC: https://database.turtle-wow.org/?npc=
Item: https://database.turtle-wow.org/?item=
Quest: https://database.turtle-wow.org/?quest=
Spell: https://database.turtle-wow.org/?spell=
Object: https://database.turtle-wow.org/?object=

**Expected behavior. Describe how it should work:**

**Comment by d-u-b** [comment]
Добрый день, проблема следующая, не могу попасть на бг уже больше 2 суток, просто идет очередь дожидался до 3 часов, на бг AB/WSG/AV пробовал отключать аддоны, чистить папки с кэшем, регать через NPC, у всех максимум 30 минут ожидание

**Comment by d-u-b** [comment]
имя персонажа Wasley

**Comment by d-u-b** [comment]
![image](https://user-images.githubusercontent.com/6154054/218279749-55826b27-010d-4f9a-9bac-3822672ef98d.png)
я мог ждать больше , но уже хотелось спать

**Comment by slowtorta** [comment]
I'm sorry we cannot help with this issue. You're probably just unlucky.
