### ISSUE TITLE
<Shaman> Call of the Earth duplicate

### ISSUE THREAD

**Issue by Riovuri** [slowtorta/turtlewow-bug-tracker#2829]
I started a tauren shaman and went through the Call of Earth questline in Mulgore (mob Seer Ravenfeather) to get my earth totem. After that, I went to Durotar to work on various quest chains there for rep, etc. One of the quests that was available was the other version of Call of Earth (mob Canaga Earthcaller). It allowed me to get the 2nd quest chain and do the first 2 parts. When it got to the 3rd part it allowed me to do it, but when I went to turn it in, the game would not allow me. It said I had a duplicate item. However, you cannot destroy earth totems (thankfully). I assume I shouldn't have been able to pick up the 2nd quest chain after completing it on the other mob in the first place.

If it matters, I had not completed the next totem questline yet (call of fire), but had picked up the starter for it.

Mulgore
NPC: https://database.turtle-wow.org/?npc=5888
Item: https://database.turtle-wow.org/?item=5175
Quest: https://database.turtle-wow.org/?quest=1521
Spell: https://database.turtle-wow.org/?spell=8071

Durotar
NPC: https://database.turtle-wow.org/?npc=5887
Item: https://database.turtle-wow.org/?item=5175
Quest: https://database.turtle-wow.org/?quest=1518
Spell: https://database.turtle-wow.org/?spell=8071

**Comment by redmagejoe** [comment]
A racial mask likely needs to be added to these quests to prevent the player from doing both of them.
