### ISSUE TITLE
Druid bear form armor penetration

### ISSUE THREAD

**Issue by f33h** [slowtorta/turtlewow-bug-tracker#283]
**Please, provide a clear description what the bug is:**
Found two examples of what it seems an armor penetration received by melee damage while being in a Bear Form, or a wrong melee damage multiplier on a critical hits. 
In both cases the damage received is considered way to high even for an elite NPCs for the levels described below.

All the critical hits were similar to the numbers described. 

**Steps to reproduce the behavior with as much detail as possible:**
All the damage was melee and received being in a bear form, only the Critical Damage was recorded.

**First Case**
Zone: Ashenvale, Lake Falathim
NPC Name: Saltspittle Puddlejumper / Saltspittle Muckdweller, 
NPC: https://database.turtle-wow.org/?npc=3737
NPC: https://database.turtle-wow.org/?npc=3740
NPC Level:   19-20
Druid Level: 23
Critical Melee Damage received in a bear form: around 120.

Can't remember which of these two produced these hits, all I remember is that that Saltspittle Oracle had a correct behavior.
To compare the expected critical damage, we can take as an example any Naga from the Ashenvale coust that has the same level.

NPC Name: Wrathtail Wave Rider
NPC: https://database.turtle-wow.org/?npc=3713
NPC Level:  18-19
Druid Level: 23
Critical Melee Damage from a two hand weapon received in a bear form: 57 Max.

**Second Case**
Last quest form the chain The Legend of Stalvan
NPC Name: Stalvan Mistmantle
NPC: https://database.turtle-wow.org/?npc=315
NPC Level: 32
Druid Level: 33
Critical Melee Damage from a one hand weapon received in a bear form: around 170-200

Can't say for sure how much melee critical damage has to come from each one hand hit given the amount of armor of level 33 druid, but it must be no more than from 30-60.

Do no hesitate to PM me if more information is needed.

**Comment by Nolin7777** [comment]
Hello and thank you for your report!

For comparison please add any evidence in form of a video captured from Blizzard's Classic server.

This ticket will be closed until more information added.
