### ISSUE TITLE
King of the Foulweald quest did not spawn adds with Chief Murgut

### ISSUE THREAD

**Issue by xHucknasty** [slowtorta/turtlewow-bug-tracker#2830]
**Please, provide a clear description what the bug is:**

**Steps to reproduce the behavior with as much detail as possible:**

1. Place banner at location
2.  Wait for spawns, observe "Unknown unit" error message
3.  Chief Murgut eventually spawns after 2-3 minutes

**IDs of affected creatures, items, quests or spells with a link to the relevant page:**

NPC: https://database.turtle-wow.org/?npc=12918
Item: https://database.turtle-wow.org/?item=
Quest: https://database.turtle-wow.org/?quest=6621
Spell: https://database.turtle-wow.org/?spell=
Object: https://database.turtle-wow.org/?object=

**Expected behavior. Describe how it should work:**
According to WoWHead comments here: https://www.wowhead.com/classic/quest=6621/king-of-the-foulweald#comments this is a difficult to solo quest due to the number of adds that spawn.  When I initiated the battle, I saw a single enraged foulweald (https://database.turtle-wow.org/?npc=12921) spawn then despawn immediately.  Note that at the time of using the banner, there were some 5 Chief Murgut corpses near the mound.  This may have something to do with it, or it may not.  After 2-3 minutes Chief Murgut did spawn and I was able to loot the quest item from the basket after his death.  However, this quest is not working as intended due to it's extremely scaled down difficulty from only having to fight one mob versus what likely should be waves of firbolg.

**Comment by redmagejoe** [comment]
Can confirm this behavior.  Worked a few updates ago.  Something changed that caused the NPCs to phase out and not spawn properly.
