### ISSUE TITLE
Pet pathing in Keep on Fenris isle is unpredictable, teleporting

### ISSUE THREAD

**Issue by xHucknasty** [slowtorta/turtlewow-bug-tracker#2831]
**Please, provide a clear description what the bug is:**
In the Keep on Fenris Isle, when approaching the main center room for the elite quest "Assault on Fenris Isle", my voidwalker became very unpredictable.  I did not visually see it, but I believe he teleported above to the room and ran back down because as soon as I entered the hallway with the ramp up to the center, the entire elite pack pulled.
**Steps to reproduce the behavior with as much detail as possible:**

1. Enter Fenris Keep with pet
2. Proceed to upper hallway with ramp (left or right side)
3. Observe pet aggro elite (likely needs to be of appropriate level)

**IDs of affected creatures, items, quests or spells with a link to the relevant page:**

NPC: https://database.turtle-wow.org/?npc=1947
Item: https://database.turtle-wow.org/?item=
Quest: https://database.turtle-wow.org/?quest=442
Spell: https://database.turtle-wow.org/?spell=
Object: https://database.turtle-wow.org/?object=

**Expected behavior. Describe how it should work:**
Self explanatory

**Comment by Zergvl** [comment]
similar problem with Dustwind Cave in Durotar.
Mobs in this cave evades from range attacks, you cannot send your pet to attack them.
Your pet always fails somewhere, e.t.c.
