### ISSUE TITLE
Pet pulling mobs from inside the Pyrewood village buildings 

### ISSUE THREAD

**Issue by xHucknasty** [slowtorta/turtlewow-bug-tracker#2832]
**Please, provide a clear description what the bug is:**
My voidwalker pulled mobs from inside the building near 44,76, Pyrewood village, Silverpine forest.  This occurred as I was moving behind the building and staying close to the spiked barricade that surrounds the village.
**Steps to reproduce the behavior with as much detail as possible:**

1. Enter Pyrewood village with pet
2. Hug the back side of the buildings and observe pet behavior
3. 

**IDs of affected creatures, items, quests or spells with a link to the relevant page:**

NPC: https://database.turtle-wow.org/?npc=
Item: https://database.turtle-wow.org/?item=
Quest: https://database.turtle-wow.org/?quest=
Spell: https://database.turtle-wow.org/?spell=
Object: https://database.turtle-wow.org/?object=

**Expected behavior. Describe how it should work:**

**Comment by slowtorta** [comment]
Part of a general pathing issue.
