### ISSUE TITLE
Gift of the Wild Icon

### ISSUE THREAD

**Issue by Jammyxx** [slowtorta/turtlewow-bug-tracker#2833]
**Please, provide a clear description what the bug is:**
Gift of the Wild is using  Mark of the Wilds icon. 
**Steps to reproduce the behavior with as much detail as possible:**

1.Buff yourself or check spell book
2. Check icon
3. It's the wrong one. 

**IDs of affected creatures, items, quests or spells with a link to the relevant page:**

NPC: https://database.turtle-wow.org/?npc=
Item: https://database.turtle-wow.org/?item=
Quest: https://database.turtle-wow.org/?quest=
Spell: https://database.turtle-wow.org/?spell=
Object: https://database.turtle-wow.org/?object=

**Expected behavior. Describe how it should work:**

**Comment by ratkosrb** [comment]
Gift of the Wild is supposed to have the same icon as Mark of the Wild in Vanilla. The new icon was added in TBC.

Classic Wowhead
https://www.wowhead.com/classic/spell=21850/gift-of-the-wild
TBC Wowhead
https://www.wowhead.com/tbc/spell=21850/gift-of-the-wild
