### ISSUE TITLE
Ironaya cannot be shot with Trueshot

### ISSUE THREAD

**Issue by thisiskt** [slowtorta/turtlewow-bug-tracker#2835]
**Please, provide a clear description what the bug is:**

Ironaya; the boss behind the "staff room" in uldaman cannot be targeted with Trueshot. Says 'invalid target'.

**Steps to reproduce the behavior with as much detail as possible:**

1. Go to Uldaman.
2. Start the boss encounter.
3. Try using Trueshot.

**IDs of affected creatures, items, quests or spells with a link to the relevant page:**

NPC: https://database.turtle-wow.org/?npc=7228
Spell: https://database.turtle-wow.org/?spell=3036

**Expected behavior. Describe how it should work:**
You should be able to shoot the boss with the skill.

**Comment by redmagejoe** [comment]
Cannot reproduce on current version. Trueshot works just fine on Ironaya.
