### ISSUE TITLE
Dungeon maps: Gnomeregan map issue

### ISSUE THREAD

**Issue by DanilFishkDev** [slowtorta/turtlewow-bug-tracker#2838]
After introducing the new dungeon maps feature, there are still some dungeons which have somewhat broken maps or not full maps yet. The one example of that is Gnomeregan, after you enter the dungeon you can see the dungeon map only for first part of the dungeon. 
Steps to reproduce:
1. Go inside Gnomeregan dungeon (after portal)
2. Open the map
3. Try to select the subzone from Zone menu on the top of the map interface (highlighted on the pic with orange)
4. The list with selectable subzones of the map should open, but it doesn't
The issue is that you can only view the map for the first part of the dungeon from entrance, you can't switch the map to show in subzones menu (Zone menu highlighted in orange on the pic). Even in the case you moved to some other part of the dungeon it will not switch the map for you, and you still can't select subzone from the menu to show
Expected behawiour:
After entering the dungeon you can open the map and see your current location and the map for that part of the dungeon, with capability to switch subzone to look into other parts of the dungeon map, if that dungeon has multiple maps and can't be shown fully in one map. For example in Shadowfang keep you can switch subzone and look into other part of the dungeon

<img width="899" alt="Gnomeregan-map-red" src="https://user-images.githubusercontent.com/50210142/218832471-e93bd55a-430b-4f1e-9c92-b78eae410303.png">

**Comment by MrToothless** [comment]
Wailing Caverns is missing the right half too; your player marker ends up floating out in the middle of nowhere on the map.

**Comment by redmagejoe** [comment]
The Cata dungeon maps being added is a WIP and, due to the different way vanilla mapIDs and areaIDs work compared to in Cata, it will take some modifications before multi-floor/layer dungeon maps work properly on Turtle. Best we can do is be patient and trust the devs responsible for implementing these maps in the first place are working on it.

**Comment by Haaxor1689** [comment]
Wailing Caverns missing right part will be added next patch as well as fixed Zul'Gurub locations
