### ISSUE TITLE
Shadowprey Village in water Fissure

### ISSUE THREAD

**Issue by Jejji1** [slowtorta/turtlewow-bug-tracker#284]
**Please, provide a clear description what the bug is:**
The fissures that should provide underwater breathing does not work as intended.
**Steps to reproduce the behavior with as much detail as possible:**

1.go to water
2. go near fissure
3. don't breath, and die.

**IDs of affected creatures, items, quests or spells with a link to the relevant page:**

NPC: https://database.turtle-wow.org/?npc=
Item: https://database.turtle-wow.org/?item=
Quest: https://database.turtle-wow.org/?quest=
Spell: https://database.turtle-wow.org/?spell=
Object: https://database.turtle-wow.org/?object=

**Expected behavior. Describe how it should work:**
It should grant underwater breathing.

**Comment by Kangaroux** [comment]
This is also true for the fissures in the Barrens. I would say it's safe to assume most if not all fissures are broken.

**Comment by slowtorta** [comment]
Please, provide the object IDs and spell IDs. I cannot find any information about it.

**Comment by Kangaroux** [comment]
@slowtorta 

Barrens:
- https://vanillawowdb.com/?object=3737
- https://vanillawowdb.com/?object=180057

Desolace:
- https://vanillawowdb.com/?object=177524

**Comment by Nolin7777** [comment]
Fixed on next maintenance.
