### ISSUE TITLE
Cannot equip Robe of the Archmage without tailoring

### ISSUE THREAD

**Issue by Lubali** [slowtorta/turtlewow-bug-tracker#2841]
**Please, provide a clear description what the bug is:**
Robe of The Archmage is no longer equippable if you dont have tailoring.
**Steps to reproduce the behavior with as much detail as possible:**

1.
2. 
3. 

**IDs of affected creatures, items, quests or spells with a link to the relevant page:**

NPC: https://database.turtle-wow.org/?npc=
Item: https://database.turtle-wow.org/?item=14152
Quest: https://database.turtle-wow.org/?quest=
Spell: https://database.turtle-wow.org/?spell=
Object: https://database.turtle-wow.org/?object=

**Expected behavior. Describe how it should work:**
It should be equippable even if you drop tailoring
https://www.wowhead.com/classic/item=14152/robe-of-the-archmage
Does not say "requires 300 tailoring"
https://www.reddit.com/r/classicwow/comments/devirt/robe_of_the_archmage_do_you_need_to_keep_300/

**Comment by ratkosrb** [comment]
This is not a bug, but an intentional change.

**Comment by Lubali** [comment]
> 

For what reason? There are many items you don't lose access to an item just because you unlearn the profession. I leveled tailoring for this exact reason, now I cannot equip the robe I have worn for 2 years because of the wims of the devs. This is an intentional design for these items. What other items do we have to expect a nerf from the devs? Gnomish engineering items when you learn goblin engineering?

**Comment by Lubali** [comment]
And why is this not included in the patch notes?
