### ISSUE TITLE
Enemy companions do not attack pet 

### ISSUE THREAD

**Issue by Zergvl** [slowtorta/turtlewow-bug-tracker#2842]
**Please, provide a clear description what the bug is:**

When starting an attack with your pet, and not making your own attacks (like shot or other spells) - enemy companions immediately runs to attack your character, ignoring your pet.

**Steps to reproduce the behavior with as much detail as possible:**

1. Become a hunter with own pet
2. Found enemy (E) with pet (P) or add (P)
3. Target (E), then press Attack on own's pet panel ( or use "/script PetAttack()" )
4. observe that your pet runs to (E) to start attacking it
5. Then (P) will runs to you (your character) to attack you instead of your pet

Checked it on:
 - Kolkar Pack Runner (E) with Kolkar packhound (P)
 - Hezrul Bloodmark (E) with two adds - Kolkar Bloodcharger (P)

I assume this behavior applies to all enemies with companions, but can't check because it's very dangerous for HC character =)

**IDs of affected creatures, items, quests or spells with a link to the relevant page:**

NPC:
 - https://database.turtle-wow.org/?npc=3274
 - https://database.turtle-wow.org/?npc=4316
 - https://database.turtle-wow.org/?npc=3396
 - https://database.turtle-wow.org/?npc=3397
 

**Expected behavior. Describe how it should work:**
Enemy companions (P) must attack your pet if you start battle with your pets attack (button or PetAttack())

**Comment by Zergvl** [comment]
Why closed?

**Comment by ratkosrb** [comment]
https://streamja.com/Xv5Qy

Cannot reproduce anymore. Before the change it was reproducible every time. Now I no longer get attacked when sending the pet.

**Comment by Zergvl** [comment]
17.02 ~12:00 server time ( 5 min ago )
I cleared WDB folder before start playing
https://youtu.be/QdlS0lVdv9I

**Comment by ratkosrb** [comment]
In the video its the same issue as https://github.com/slowtorta/turtlewow-bug-tracker/issues/2848
It happens because the pet pulls with a spell (charge). It will be fixed next update.

**Comment by MrToothless** [comment]
There was no change at all. The patch did nothing. You closed the issue without fixing this. Not a great look at all...

**Comment by Zergvl** [comment]
> In the video its the same issue as #2848 It happens because the pet pulls with a spell (charge). It will be fixed next update.

You are right! without charge all ok! thanks!
