### ISSUE TITLE
All Mind Controlling effects are currently not functioning as intended

### ISSUE THREAD

**Issue by suggney** [slowtorta/turtlewow-bug-tracker#2843]
**Please, provide a clear description what the bug is:**
Whenever you are mind controlled, you do not become attackable or CCable by your allies. Hakkar MCs cannot be sheeped and must leave the raid to be PVPed for the duration of the MC, same for Nefarian phase one. I assume this is the case for Skeram and Kel'Thuzad, which would make these fights almost impossible.
**Steps to reproduce the behavior with as much detail as possible:**

1. Do a boss with a mind control effect.
2. Enjoy!

**IDs of affected creatures, items, quests or spells with a link to the relevant page:**

NPC: https://database.turtle-wow.org/?npc=14834 https://database.turtle-wow.org/?npc=11583 https://database.turtle-wow.org/?npc=15263 https://database.turtle-wow.org/?npc=15990 
Spell: https://database.turtle-wow.org/?spell=24327 https://database.turtle-wow.org/?spell=22667 https://database.turtle-wow.org/?spell=785 https://database.turtle-wow.org/?spell=28410

**Expected behavior. Describe how it should work:**
You should be able to Polymorph, Fear, and do other somesuch CCs to your allies when they are mind controlled.

**Comment by ConcernedTurtler** [comment]
My guild is able to sheep/fear/cc mind controlled characters during skeram.
