### ISSUE TITLE
Rejuvenation does not crit.

### ISSUE THREAD

**Issue by ConcernedTurtler** [slowtorta/turtlewow-bug-tracker#2844]
I cast over a 100 rejuvenations on myself and party members with 15% chance to crit and it didn't crit once.  Every other healing spell in the game has a chance to crit so I'm assuming this is a bug.  Thank you.

**Comment by balakethelock** [comment]
It is not a bug. Damage and healing over time effects can't crit in vanilla.

**Comment by ConcernedTurtler** [comment]
Oh that's a shame. When was that changed? Burning Crusade?
