### ISSUE TITLE
Chromaggus healing bug.

### ISSUE THREAD

**Issue by shoy14** [slowtorta/turtlewow-bug-tracker#2846]
During our fight with Chromaggus, we continuously ran into an issue where Chromaggus would heal himself, despite nobody dying to brood affliction: red. 

We engaged the fight several times. We ensured that no pets were summoned that could have been affected. We clipped the fight to make sure we were not missing any deaths. Throughout the clip, there are multiple instances where chromaggus healed himself, despit nobody dying to brood affliction: red. 

NPC: Chromaggus (BWL) 14367
Spell: Brood Affliction: Red

Based on the current descriptions of the brood afflictions, Brood affliction: Red should apply a period damage aura, and heal himself only if somebody were to die to the period damage aura.

Please find attached the link to the clip, as mentioned.

https://www.twitch.tv/videos/1739570136

**Comment by shoy14** [comment]
Time stamps for heals:
heal 1 @ 4:15
heal 2 @ 4:35
heal 3/4 @ 5:45
etc..

**Comment by ConcernedTurtler** [comment]
Confirmed on our raid as well.

**Comment by ametc1** [comment]
Confirmed
<East Oceanic Trading Company>

We didn't get any heals on chromag until people died, one of them had red when he died but every time the tick happened chromag would heal

I think Chromag is healing off the corpse in this case

**Comment by ametc1** [comment]
Definitely healing of corpses, had no heals until corpses were present and then he just heals
