### ISSUE TITLE
Pet pull aggro

### ISSUE THREAD

**Issue by MrToothless** [slowtorta/turtlewow-bug-tracker#2848]
Upon pulling a mob with Imp's Firebolt, the mob's initial aggro is on the player, until the Firebolt lands, upon which the aggro is correctly assigned to the Imp. This is game-breaking on group pulls as the entire pack aggroes onto the player, instead of the Imp.

**Steps to reproduce the behavior with as much detail as possible:**

1. Find mob
2. Pet-attack with Imp
3. ???

Mobs should obviously aggro the Imp when the firebolt lands and a linked group should then aggro onto the Imp, not the player upon Firebolt cast.

**Comment by MrToothless** [comment]
Why was this issue closed before it was fixed?

**Comment by ratkosrb** [comment]
Because it is fixed, internally. We close issues as soon as we have a fix on our side. Not when we update the server with the fixes.

**Comment by MrToothless** [comment]
Fair enough. Might I suggest commenting as such when closing issues?

**Comment by cyaohiri** [comment]
Generally the rule has been that issues closed without any comments are fixed.
