### ISSUE TITLE
[AQ40 BOSS BUG] Ouro is only targeting people in melee for sandblast

### ISSUE THREAD

**Issue by Velite12** [slowtorta/turtlewow-bug-tracker#285]
**Please, provide a clear description what the bug is:**
![image](https://user-images.githubusercontent.com/45871932/132271283-7e035aa2-c359-4376-80e0-254976789d2e.png)

Ouro should be targeting the highest person on threat, not his current target in melee, for sand blast. Right now, he will only sandblast the person with the highest threat in melee range, aka his current melee target.

The code currently used for Ouro selecting his target for sandblast has a check to ignore an out of melee range target for an immobilized attacker when selecting hostile targets:

![image](https://user-images.githubusercontent.com/45871932/132385434-b4b5a5c9-d442-4eed-83e2-894b2e7eae0a.png)

**Steps to reproduce the behavior with as much detail as possible:**

1.Fight Ouro
2. Get to sandblast
3. See he is only targeting people in melee.

**IDs of affected creatures, items, quests or spells with a link to the relevant page:**

NPC: https://database.turtle-wow.org/?npc= https://database.turtle-wow.org/?npc=15517

**Expected behavior. Describe how it should work:**
https://youtu.be/jRebEcWw9vI?t=78

Ouro should target the person who is highest on threat for sand blast, which will usually be a Ranged dps like a mage or warlock, not the people in melee.
![image](https://user-images.githubusercontent.com/45871932/132271616-9267511a-d707-45fa-9c55-d252cadf1f2c.png)

https://www.youtube.com/watch?v=Gej6wGALjqE

![image](https://user-images.githubusercontent.com/45871932/132271778-047afbff-3f19-4dc0-9de3-3ffc70658d63.png)

![image](https://user-images.githubusercontent.com/45871932/132271915-51980a63-4158-4c8f-8dd8-f1daa0a3e692.png)

**Comment by jameyboor** [comment]
Fixed.

**Comment by Zebouski** [comment]
@jameyboor unfortunately this fix didn't seem to work. we are still having totems take over aggro as well as casters remain untargetted.

**Comment by Gurky-Turtle** [comment]
@jameyboor can this get a relook there seems to be other issues with this boss as well compared to standard classic strats.

**Comment by ratkosrb** [comment]
https://github.com/slowtorta/turtle-wow/commit/e5403ef190bab19d40da330492747a24e582e9ab
