### ISSUE TITLE
Argent Dawn quartermasters don't give a vendor option

### ISSUE THREAD

**Issue by Kangaroux** [slowtorta/turtlewow-bug-tracker#2850]
When speaking to any of the quartermasters, none of them give me any vendoring options. I am currently friendly with AD. I've experienced this on past characters as well. I recall being able to vendor once I hit honored (on a previous alt). I've tried deleting WDB, reloading UI, trying chars on different accounts, etc.

**Comment by Haaxor1689** [comment]
Duplicate of #1565
