### ISSUE TITLE
Caravan Kodo (remote bank) causing screen tremors

### ISSUE THREAD

**Issue by RUTHINAS** [slowtorta/turtlewow-bug-tracker#2851]
**Please, provide a clear description what the bug is:**
The Caravan Kodo, clearly modeled after the ones in Gizelton's caravan in Desolace, cause a screen tremor to any nearby players when walking. The ones in Desolace are absolutely massive, and their slow thumping steps carry such heft that this makes sense. The Caravan Kodo, however, is tiny in comparison. It doesn't fit the scale that the entirety of Orgrimmar is quaking when one walks by. In addition, due to the smaller model scale, its walking animations are sped up to keep up to pace with the player. This leads to the tremors having a much higher frequency.

Screen shake effects can be an accessibility issue for players susceptible to motion sickness or with impaired vision.

NPC: https://database.turtle-wow.org/?npc=51300

**Expected behavior. Describe how it should work:**
The small Caravan Kodo should not cause screen tremors because it doesn't make sense for its size and because it can cause accessibility issues for players.

**Comment by redmagejoe** [comment]
Screen shake is tied to models clientside, with a specific entity being given a displayID serverside which calls that client model. The only way to remove the screen shake would be to create a duplicate model and display entry in the client without screen shake effects and create a new displayID for it specifically for the caravan kodo. Whether staff is willing to do this is up for debate.
