### ISSUE TITLE
Brood of nozdorumu reputation

### ISSUE THREAD

**Issue by omgthisissoannoying** [slowtorta/turtlewow-bug-tracker#2852]
**Please, provide a clear description what the bug is:**
My reputation keeps reseting. Stuck in hostile.
**Steps to reproduce the behavior with as much detail as possible:**

1.
2. 
3. 

**IDs of affected creatures, items, quests or spells with a link to the relevant page:**

NPC: https://database.turtle-wow.org/?npc=
Item: https://database.turtle-wow.org/?item=
Quest: https://database.turtle-wow.org/?quest=
Spell: https://database.turtle-wow.org/?spell=
Object: https://database.turtle-wow.org/?object=

**Expected behavior. Describe how it should work:**

**Comment by slowtorta** [comment]
https://github.com/slowtorta/turtlewow-bug-tracker/issues/2797
