### ISSUE TITLE
Blade of Eternal Darkness proc

### ISSUE THREAD

**Issue by Smittych** [slowtorta/turtlewow-bug-tracker#2853]
**Please, provide a clear description what the bug is:**
Item [Blade of Eternal Darkness] with proc description:
"Chance on landing a damaging spell to deal 100 Shadow damage and restore 100 mana to you."
also has a chance to proc from "procs" of items like [Incendosaur Skin Boots] with description:
"Adds 2 fire damage to your melee attacks."

How does it is look like: 
A Feral druid in cat form fully as possible geared with items with same "proc" as [Incendosaur Skin Boots] (5 items for example),
with each attack has additional 5 "attacks" each of them has a chance of [Blade of Eternal Darkness] proc. In summary, [Blade of Eternal Darkness] can proc insane times a minute.

In my opinion, it shouldn't proc from additional damage of that kind of items, because that proc is not a spell.

PS: There is a suspicion that Hand of Justice can proc from that attacks too.

**Steps to reproduce the behavior with as much detail as possible:**
1. Take a feral druid
2. Wear [Blade of Eternal Darkness] + all possible items with passive ability like [Incendosaur Skin Boots] has (Incendosaur items, some lantern and cloak with electric damage, etc.)
3. Hit something in cat form
As example, druid Iag (IAG not Lag) has that build, so you may check his items.

**IDs of affected creatures, items, quests or spells with a link to the relevant page:**
[Blade of Eternal Darkness]: https://database.turtle-wow.org/?item=17780
[Incendosaur Skin Boots]: https://database.turtle-wow.org/?item=60568
[Hand of Justice]: https://database.turtle-wow.org/?item=11815

**Expected behavior. Describe how it should work:**
That "added damage" shouldn't work as attack and trigger item's proc as normal attack or spell.

**Comment by geojak** [comment]
Out of curoisty, what dps can he do with thaz build. Is it like rly op? Or is it just a, weird, special niche, still comparable to other classes but not better either.

**Comment by geojak** [comment]
There is also wrath of cenarius ring which is Similiar triggered by this interaction. I would be sad to lose this interaction  I spent months getting it knowing beforehand that it worked liek that

**Comment by burner1024** [comment]
By every imaginable metric, paladin>druid. Well, except running, I guess. So on a case by case basis, it would make sense to go the other way, actually.
It's also worth noting that there's a lot of other classes that can use this combo, but those aren't mentioned in the initial post. Think why.

In summary, I'd suggest to prioritize fixing glaring issues in class design, and specifically hybrid classes design, rather than taking away the ways players are coping with said issues. If that's done, many secondary issues will go away on their own.

**Comment by twowTurtReynolds** [comment]
Staff is aware and have seen no reason to change this behavior.
