### ISSUE TITLE
Warlock Demonic Aegis Buff Tooltip is incorrect

### ISSUE THREAD

**Issue by msegers** [slowtorta/turtlewow-bug-tracker#2855]
**Please, provide a clear description what the bug is:**

Demonic Aegis is not represented in buff tooltip for warlock.

**Steps to reproduce the behavior with as much detail as possible:**

1. Spec warlock with Demonic Aegis 3/3/
2. cast Demon Armor 3
3. Tooltip in spell says armor should be 624, however it is 390, so talent is not applied to tooltip

**IDs of affected creatures, items, quests or spells with a link to the relevant page:**

Spell: https://database.turtle-wow.org/?spell=11733

**Expected behavior. Describe how it should work:**

Actual armor improvement in tooltip should be 624, and likely also an improvement in shadow res and health regen!

**Comment by msegers** [comment]
Sorry, I just noticed It was a visual bug, I'm certain I saw something wrong this afternoon, but I must have been mistaken.
Right now the only thing that's off is that the buff in my top right corner is displaying the wrong numbers, ignore my above comment on wrong values applied.

**Comment by slowtorta** [comment]
This is abasolutely normal that tooltips don't always represent the real values in Vanilla.
