### ISSUE TITLE
Skinning multiple different Duskwallow Dragonkin gives no skins/hides/scales.

### ISSUE THREAD

**Issue by MasterPooBaa** [slowtorta/turtlewow-bug-tracker#2856]
**Please, provide a clear description what the bug is:**

Dragonkin (both Elite and non-elite) produce blank skinning results in Duskwallow Marsh - bug in skinning loot table?
Searing Whelp.
Searing Hatchling.
Firemane Ash Tail.
Firemane Scout.
Firemane Scalebane

**Steps to reproduce the behavior with as much detail as possible:**

1. Have logged out, cleared wdb folder, logged back in.
2. Killed and skinned all the mobs around StoneMaul Ruins.
3. Finding about 25% to 40% of the time a skinning results in no skin/hide/scale.

**IDs of affected creatures, items, quests or spells with a link to the relevant page:**

NPC: https://database.turtle-wow.org/?npc=4324
NPC: https://database.turtle-wow.org/?npc=4323
NPC: https://database.turtle-wow.org/?npc=4331
NPC: https://database.turtle-wow.org/?npc=4329
NPC: https://database.turtle-wow.org/?npc=4328

**Expected behavior. Describe how it should work:**

**Comment by Fierce666** [comment]
I‘ve had this happen elsewhere too. For example in Silithus. I used to farm the Dredge Crushers and I guess 1 in 20 didn‘t yield anything after skinning it. I kill it, then I skin it for 1.5 sec., and then, without giving me anything, it just lies dead there lol

**Comment by Kangaroux** [comment]
This is due to the skinning loot table not using any item groups, each skin is a separate roll and it's possible for none of them to be skinned.

@Fierce666 I think that's a separate issue, it seems to happen on any skinnable mob. I thought it only happened if you skinned something from max range, but I've also had it happen if I'm standing on top of the mob when I skin it

**Comment by MasterPooBaa** [comment]
> @Fierce666 I think that's a separate issue, it seems to happen on any skinnable mob. I thought it only happened if you skinned something from max range, but I've also had it happen if I'm standing on top of the mob when I skin it

I am aware of the distance skinning issue, so when I skin i make sure im standing right ontop the mob.

On a side note, in Retail re-released classic wow Dredge in Silithus are not skinnable at all.  I dont know if they were back in 2005 classic wow.

**Comment by geojak** [comment]
Drudgers in Sillothus were not skin able in 2005
