### ISSUE TITLE
Brood of Nozdorumu reputation bug.

### ISSUE THREAD

**Issue by omgthisissoannoying** [slowtorta/turtlewow-bug-tracker#2858]
**Please, provide a clear description what the bug is:**
Character name Issah
Hello! I'm stuck in hostile, it caps then starting over. I've done multiple full runs, and turned in quest items.

**Steps to reproduce the behavior with as much detail as possible:**

1. Go to AQ 40
2. Cap that rep
3. Watch it reset

I do not know how to detail it any further.

**Expected behavior. Describe how it should work:**
It should not reset

**Comment by slowtorta** [comment]
https://github.com/slowtorta/turtlewow-bug-tracker/issues/2797

**Comment by omgthisissoannoying** [comment]
I do not understand what you mean by that : (

**Comment by omgthisissoannoying** [comment]
> #2797

I do not understand what you mean by this.

**Comment by slowtorta** [comment]
It means we are aware of this issue and already working on it :)

**Comment by omgthisissoannoying** [comment]
> It means we are aware of this issue and already working on it :)

Oh my bad, thanks for the quick respons!
