### ISSUE TITLE
"Breaking The Felstar" quest does not spawn the NPCs that should help you

### ISSUE THREAD

**Issue by EskayRogue** [slowtorta/turtlewow-bug-tracker#2860]
In the quest "Breaking the Felstar" it says "Once you are close to the Felstone, destroy it. The Satyr will definitely try ti prevent its destruction and attack you. Our rangers will then come out of hiding and help you"
**Steps to reproduce the behavior with as much detail as possible:**

1. Get the quet
2. Go to the Felstone
3. Break it
4. No NPC spawn

**IDs of affected creatures, items, quests or spells with a link to the relevant page:**
I do not know the ID of the ranger NPCs for the quest, but the boss mob in question is Dra'lox

NPC: https://database.turtle-wow.org/?npc=
Item: https://database.turtle-wow.org/?item=
Quest: https://database.turtle-wow.org/?quest=
Spell: https://database.turtle-wow.org/?spell=
Object: https://database.turtle-wow.org/?object=

**Expected behavior. Describe how it should work:**
Per the quest text, you break the Quest objective and then the NPCs should spawn in and help you kill the monsters.

**Comment by redmagejoe** [comment]
The event script for this quest has long been broken and needs a proper rewrite.
