### ISSUE TITLE
Love is in the Air (all in one report)

### ISSUE THREAD

**Issue by slowtorta** [slowtorta/turtlewow-bug-tracker#2861]
...

**Comment by slowtorta** [comment]
![image](https://user-images.githubusercontent.com/66763404/220087786-32b41d5b-d7e0-43ec-befb-5f9d1c45ea9a.png)

**Comment by jimmytaker** [comment]
Found the following bugs today (21.02 - so after the changes):
1. Kwee does not count the new turn ins. Total for horde is shown as 0. REMARK: This used to work correctly last week (before the addition of the new shop items server restart, which initially broke Love is in the Air. REMARK2: The event seemed to work as it should in the 1st few days after it was added).
2. On a char that had not yet participated in the love token giving - 1st ever token given resulted in heartbroken - this should not happen. REMARK: This used to work correctly yesterday (before the changes).
3. Believe same unterlying issue as 2. - It is possible to get heartbroken while having the "Adored" debuff. Heartbroken should only be possible to occur when having no "Adored" debuff. REMARK: This used to work correctly yesterday (before the changes).
4. Giving Love Token to NPC while having "Adored" debuff resets the CD on the debuff back to 60 min - this should not happen. While "Adored" u only receive "Gift of friendship" and the debuff should remain at the time it was. REMARK: This used to work correctly yesterday (before the changes).
5. Very few NPC in Org available, who can give u Freshly Baked Pie. REMARK: This used to work correctly yesterday (before the changes).

**Comment by slowtorta** [comment]
@ratkosrb Not sure if you've seen this.

**Comment by jimmytaker** [comment]
Point 5 is not fixed:
Very few NPC in Org available, who can give u Freshly Baked Pie. REMARK: This used to work correctly yesterday (before the changes).

Walking around the valley of Strength (where the bank and inn are), there is not a single citizen NPC (not guard), u can give a love token to. There were a lot of NPC, who could be "loved" a few days ago.

**Comment by jimmytaker** [comment]
OK, nvm. U went the other way. Now almost no NPC in SW trade district can be "loved" either. What was bothering me was the discrepancy between the amount of NPCs, who could be "loved" in SW and Org. Now both cities are "loveless". That also works.

May be a bit hard to understand why one vendor accepts tokens, while another one does not, but that is hardly a bug.

**Comment by slowtorta** [comment]
Heartbreaking 😢

**Comment by fatnerdynerd** [comment]
A few issues.

1. Most SW/Org Civ NPCs won't ever get the heart, or will have it one day and have it gone the next (Snake vendor in Org for instance lost his taste for love by today)
2. As of today I found 3 Civ NPCs in Org that are still willing to take tokens: The Enchanting Trainer, A random vendor in Valley of Strength, and the Tabard vendor.
3. Very few Guards gain hearts, around 6 in either cities.
4. Darnassus seems to have similar issues, the only Civ NPC that I could give a token to were the bread vendors.
5. Haven't tested UC/TB yet, can't comment on those

**Comment by fatnerdynerd** [comment]
Thunderbluff has 0 Civillian NPCs that are functioning, 2 has hearts above them but aren't giving any gifts

**Comment by fatnerdynerd** [comment]
Upon further inspection, Thunder Bluff has 1 single Guard NPC whos giving out gifts

**Comment by jimmytaker** [comment]
The Tokens are not actually deducted from your inv. U gain present, but still have the same number of tokens.
