### ISSUE TITLE
2.5 Itemization changes not implemented in-game

### ISSUE THREAD

**Issue by snakeboard** [slowtorta/turtlewow-bug-tracker#2862]
**Please, provide a clear description what the bug is:**

The February 15th patch notes state that there were changes made to the stats on the hunter, shaman, and warlock 2.5 set pieces.  When I log into game and check the gear on my shaman and hunter, they have not been changed at all, and are still the same stats as always.  I have deleted my WDB folder multiple times, to no avail.  I don't have a warlock with 2.5 to check my own items but I have inspected other players and seen the same thing.  I am uncertain these changes were actually implemented. 

**IDs of affected creatures, items, quests or spells with a link to the relevant page:**

https://database.turtle-wow.org/?item=21372
https://database.turtle-wow.org/?item=21373
https://database.turtle-wow.org/?item=21374
https://database.turtle-wow.org/?item=21375
https://database.turtle-wow.org/?item=21376

https://database.turtle-wow.org/?item=21334
https://database.turtle-wow.org/?item=21335
https://database.turtle-wow.org/?item=21336
https://database.turtle-wow.org/?item=21337
https://database.turtle-wow.org/?item=21338

https://database.turtle-wow.org/?item=21365
https://database.turtle-wow.org/?item=21366
https://database.turtle-wow.org/?item=21367
https://database.turtle-wow.org/?item=21368
https://database.turtle-wow.org/?item=21369

Ineterstingly, if you look at the database, the stats do appear to be changed, but these are NOT reflected in-game.  Also there's a typo on the Stormcaller's Footguards (item 21373) on the database, it now says it decreases the spell resistances of your targets by 1 when it should be 10.

**Expected behavior. Describe how it should work:**

The stats on these items should be the same in-game as they are shown to be in the database and in the forum post detailing the changes supposedly made on Feb 15.

**Comment by slowtorta** [comment]
It's fixed now, please clear your WDB folder and restart your game.
