### ISSUE TITLE
Shaman totem Buff Bug in party ( warmode enabled)

### ISSUE THREAD

**Issue by spogsta** [slowtorta/turtlewow-bug-tracker#2863]
I have an interesting bug and haven't found much information on how to fix my issue.

I'm a shaman and have a party member that I'm leveling with.

We both have warmode enabled.

When I drop a totem when not in a party, i get the totem buff.

When I drop a totem within the party, neither of us get the buff.

Does anyone know what is going on/how I can fix this issue? I'm not entirely sure what's going on

Spells used: totem of ironskin and strength totem- we had no other conflicting buffs (mage buff)

party members: Myself-a shaman and a mage

**Comment by spogsta** [comment]
server reset fixed my issue. we now can enjoy the totem buff.

**Comment by spogsta** [comment]
Now I died and it doesnt work again lol

**Comment by slowtorta** [comment]
Do you have a Paladin in your party?

**Comment by spogsta** [comment]
no we are both horde, troll mage. both warmode. The st range thing is when she's in my party but further away, I can receive the totem buff. When she moves into my area neither of us can get the buff. We've deduced it's when she's nearby and in the party. If i leave the party I can get the buff, or if shes far away I also can get it.

**Comment by spogsta** [comment]
The really weird thing is sometimes it does just work, we receive the totem buffs, sometimes it doesn't. But more often then not, it doesn't work. 

If you need me to create a video replicating this I can

**Comment by Zeyla-TW** [comment]
I've also experienced this bug. Sometimes some buff totem will just suddenly stop providing their auras to the group/shaman. From my experience, dropping a windfury totem when this happens, then totemic calling the totems to get rid of them, and then re-dropping the buff totem will then fix it. (I was told this fix by a fellow shaman player who had been experiencing this for quite a while)

**Comment by spogsta** [comment]
Thank you, I will us this when I get totemic calling. Much appreciated.

**Comment by Kronkers007** [comment]
Hellooo Shamans,

So I've noticed this bug with totems as well. Not working in parties even if both group mates have warmode on.
To fix this I have us both log out.  Before inviting him to the group I apply strength totem to myself to get the buff. Then I invite him. After that totems will work fine for awhile till it randomly breaks hours later.

Hope this issue can be fixed. Totems work fine in dungeons but not open world parties.

**Comment by ratkosrb** [comment]
I've made a change that could possibly fix this. Let me know if it still happens next week.

**Comment by twowTurtReynolds** [comment]
Can't currently reproduce this, only the weird interaction where unflaged shaman's totems wont buff a flagged player, but afaik that is intended.
