### ISSUE TITLE
bug with facetarget with rogue 

### ISSUE THREAD

**Issue by ivanku4eto** [slowtorta/turtlewow-bug-tracker#2864]
![afdag](https://user-images.githubusercontent.com/124826155/220105216-360a1be6-47a2-4234-9e92-53a76210ea9b.jpg)
hello there i want help this always hapening to me when i fight all time i cant hit backstab becouse mob is in wrong place look vs players is still same pls help

**Comment by redmagejoe** [comment]
This is related to #562 which has been closed as completed.

Fixed.
