### ISSUE TITLE
Remnants sentrys do not have agro.

### ISSUE THREAD

**Issue by Nozdormus** [slowtorta/turtlewow-bug-tracker#2867]
Please, provide a clear description what the bug is: Remnant sentrys do not have agro and do not attak hostile players.
Steps to reproduce the behavior with as much detail as possible: Go to Whispering forest and try to walk near them in wrecked tower.
IDs of affected creatures, items, quests or spells with a link to the relevant page:

NPC: https://database.turtle-wow.org/?npc= https://database.turtle-wow.org/?npc=91772
Expected behavior. Describe how it should work: They must have aggro range and attack hostile players
![image](https://user-images.githubusercontent.com/8399484/220148735-65bf8fa9-c2e8-41c3-a7e4-f1ae99ec0721.png)

**Comment by redmagejoe** [comment]
Can confirm this issue.
