### ISSUE TITLE
Bandages no longer give hp on the first tick

### ISSUE THREAD

**Issue by Kangaroux** [slowtorta/turtlewow-bug-tracker#2869]
When using a bandage you should get a tick of healing immediately, allowing you to use it in the middle of a fight. However, it no longer gives any healing on the first tick (when it applies the recently bandaged debuff)

**Comment by redmagejoe** [comment]
It is an 8 second channel with each tick happening after each second. You were never meant to gain an instant tick, otherwise the last second of the channel would be pointless. I tested and the math adds up.

Bandages are working as intended, and this can be closed.
