### ISSUE TITLE
The hunter's pet skills missed after latest updates

### ISSUE THREAD

**Issue by Noade** [slowtorta/turtlewow-bug-tracker#2871]
**Please, provide a clear description what the bug is:**

Some of my active and passive pet skills no longer work after last updates. I missed Crowl and all passive pet skills.

**Steps to reproduce the behavior with as much detail as possible:**

Crowl learned, but i don't have it on panel or book

![Desktop_Screenshot_2023 02 21_-_15 40 18 17](https://user-images.githubusercontent.com/32249083/220371773-0028d67a-9d98-4294-be53-c9b6d7226054.png)

![Desktop Screenshot 2023 02 21 - 16 18 09 56](https://user-images.githubusercontent.com/32249083/220371877-421fdd63-0042-4708-8f35-287b616aba8d.png)

Same thing with passive skills (Resistance/Stamina) they doesn't work at all

![Снимок экрана 2023-02-21 163015](https://user-images.githubusercontent.com/32249083/220373518-226d11a6-2af6-4a99-9922-d2ee800b9f44.png)

Whatever skill I learned - doesent matter - nothing work.

**Comment by slowtorta** [comment]
Please, learn them again at the trainer.
