### ISSUE TITLE
winterax cahmpion qeust does nothing

### ISSUE THREAD

**Issue by geojak** [slowtorta/turtlewow-bug-tracker#2873]
**Please, provide a clear description what the bug is:**

**Steps to reproduce the behavior with as much detail as possible:**

1. get the disguise
2.  get the qeust
3. kill the gnolls
4. hand in
5. red error says " you must be in alterac" when you hand it in
6. nothing happend
7. be very disppointed as the qeust promised a reward

**IDs of affected creatures, items, quests or spells with a link to the relevant page:**
https://database.turtle-wow.org/?quest=40004

**Expected behavior. Describe how it should work:**

something, anthing rly, a buff?

**Comment by geojak** [comment]
secondly when you go with blood of korrak and disguise inside the winterax cave, the blood of korrak debuff just vanished. nothing happens. were is the secret interaction when it just disappears

**Comment by ratkosrb** [comment]
The quest is supposed to give you a buff. Did it not work?

**Comment by geojak** [comment]
No

**Comment by ratkosrb** [comment]
I found the issue. The inside of the cave has a different area id than the rest of AV, and that's why the buff didn't work.

**Comment by geojak** [comment]
@ratkosrb did you also fix blood of korrak debuff dispearing on cave enter?

**Comment by ratkosrb** [comment]
yes
