### ISSUE TITLE
Travel form does not get autoremoved when entering indoors in some locations

### ISSUE THREAD

**Issue by jimmytaker** [slowtorta/turtlewow-bug-tracker#2875]
Most indoor locations druid travel form gets removed automatically.

There are exceptions I have found:
1. The arcane crystal mine in alah'thalas
2. The pirate ship on the main dock in theramore (the one with the marines on it)

REMARK: After manually removing travel form, it is impossible to go back into travel form in these locations. The error message "Can only be used outside" correctly pops.

**Comment by slowtorta** [comment]
Pirate ship won't work, because it's a manually spawned object.
We're aware about the Crystal Mine, it's going to be patched in the next client update.
