### ISSUE TITLE
Slow respawn on "Smuggled Procurements" for the quest "Kul Tiran Provisions: Special Goods"

### ISSUE THREAD

**Issue by jimmytaker** [slowtorta/turtlewow-bug-tracker#2877]
The item "Smuggled Procurements" in Theramore takes 5 min to respawn. I know u are fixing these to respawn quicker.

Probably best to also check "Smuggled Gunpowder" in Ratchet

**Comment by slowtorta** [comment]
Fixed on the next maintenance :)
