### ISSUE TITLE
Getting stuck in combat untill death

### ISSUE THREAD

**Issue by ComradeMaya** [slowtorta/turtlewow-bug-tracker#2883]
**Please, provide a clear description what the bug is:**
Me and my friend for unknown reasons can't get out of combat once we enter it. We can't do anything to stop being in combat, no matter how long we wait unless we die. Then once we fight anything we are stuck in combat again.
**Steps to reproduce the behavior with as much detail as possible:**
The only thing we did that could maybe trigger this is throwing out buffs on peple while travelling to westfall (mark of the wild rank 2, thorns rank 1, fortitude rank 2). Our characters are a lvl 13 druid and priest named Machakw and Maja respectively

**Comment by redmagejoe** [comment]
This often happens when you buff someone who is in combat, and they spend an excessive amount of time in combat. It should not, however, be permanent.  More clear and detailed steps would be necessary to attempt to reproduce this issue.

**Comment by slowtorta** [comment]
Please request assistance from a GM if it happens. It's not a regular but and there's no way to reproduce or fix it right now.
