### ISSUE TITLE
LFT window freezes

### ISSUE THREAD

**Issue by 4iloveg** [slowtorta/turtlewow-bug-tracker#2885]
![Скриншот 23-02-2023 032010](https://user-images.githubusercontent.com/19300333/220794598-84b0932d-7616-4356-9f71-f1a4d2a8bd09.jpg)
Sometimes it happens that there is no way to close this window, which should close on its own. And have to restart the game, but after the restart the problem may occur again, this happens in 10% of cases. Can you add to the addon function that will close this frame, when the buttons wayting and leave are not clickable.

**Comment by cyaohiri** [comment]
In the meantime, use `/console reloadui`, that should close it.

**Comment by 4iloveg** [comment]
> In the meantime, use `/console reloadui`, that should close it.

Yes, this solves the problem, but it causes the LFT to reload and drop from the queue if the group is not formed, I just think that adding a hide frame button would be useful for those who are not familiar with the command

**Comment by slowtorta** [comment]
@CosminPOP

**Comment by Gurky-Turtle** [comment]
I am going to remove this report to https://github.com/CosminPOP/LFT/issues

**Comment by Gurky-Turtle** [comment]
Moved to here https://github.com/CosminPOP/LFT/issues/15
