### ISSUE TITLE
Hunter - Quiver fails to modify Ranged Attack Speed

### ISSUE THREAD

**Issue by Khelekmir** [slowtorta/turtlewow-bug-tracker#2886]
**Please, provide a clear description what the bug is:**

Hunter ranged attack speed failed to be modified by quiver attack speed increase. 3.00 attack speed ranged weapon yields 3.00 ranged attack speed, irrespective of 14% ranged weapon attack speed increase from quiver. Verified with timed test of 20 shots in 60 seconds (1 shot every 3 seconds precisely); 14% increased attack speed SHOULD yield 2.58 sec atk speed, with 23+ shots in 60 seconds.

Issue follows custom weapons (shieldbreaker arbalest, bloodscalp bow) and pre-existing ones (hurricane, vendor whites);
Issue follows multiple quivers (ribbley's quiver, light quiver, medium quiver).

![attack speed_1](https://user-images.githubusercontent.com/107819244/220830033-44f47f02-5a60-4873-9e9b-e799b5ce5d0e.png)
![attack speed_2](https://user-images.githubusercontent.com/107819244/220830065-d89f41b6-6358-4501-9d83-a04d7198213a.png)

NOTE: have polled several other hunters in-game, and they are NOT experiencing this issue.

**Steps to reproduce the behavior with as much detail as possible:**

1.  no special action necessary; displayed attack speed accurately reflects no increase to attack speed, as verified through timed test on attack dummy in city.
2.   relog does NOT fix
3.   delete WDB does NOT fix

**IDs of affected creatures, items, quests or spells with a link to the relevant page:**

NA

**Expected behavior. Describe how it should work:**

expect an increase to attack speed commensurate with quiver atk speed bonus. this should accurately display in the character menu, and affect ranged attack speed.

![attack speed_3](https://user-images.githubusercontent.com/107819244/220830496-526292ec-a5fe-4c74-8234-08995c192d40.png)
![attack speed_4](https://user-images.githubusercontent.com/107819244/220830514-ce8c60e6-1984-4eed-9386-1a18f82ee7e3.png)

**Comment by geojak** [comment]
What weapon are you using? Does this bug also appear with other ranged weapons for you?

**Comment by redmagejoe** [comment]
See #2865. This should be fixed on the next update.

This can be closed. Reopen if quiver/weapon-swapping still doesn't work as desired.
