### ISSUE TITLE
Grim Reach does not affect Drain Soul

### ISSUE THREAD

**Issue by balakethelock** [slowtorta/turtlewow-bug-tracker#2887]
**Please, provide a clear description what the bug is:**
The talent in warlock affliction tree Grim Reach does not increase the range of Drain soul. Drain soul is the only affliction ability harmed by this bug.

**Steps to reproduce the behavior with as much detail as possible:**

1. Spec into 2 points of Grim Reach
2. See the range of most of your abilities increase to 36 yards
3. see the range of drain soul still 30 yards

**IDs of affected creatures, items, quests or spells with a link to the relevant page:**

IDs of the talent grim reach:
https://database.turtle-wow.org/?spell=18218
https://database.turtle-wow.org/?spell=18219

IDs of the spell Drain Soul:
https://database.turtle-wow.org/?spell=1120
https://database.turtle-wow.org/?spell=8288
https://database.turtle-wow.org/?spell=8289
https://database.turtle-wow.org/?spell=11675

**Expected behavior. Describe how it should work:**
Grim reach increases the range of Drain Soul by 20%. From 30 to 36yards

**Comment by redmagejoe** [comment]
Can confirm, this does not affect Drain Soul on current version, when it should.
https://www.wowhead.com/classic/spell=18219/grim-reach
