### ISSUE TITLE
Razormane Pathfinder chance for addtitional attacks broken

### ISSUE THREAD

**Issue by aniserg** [slowtorta/turtlewow-bug-tracker#2888]
**Razormane Pathfinder chance to deal two additional attacks affects new attacks, which sometimes let him attack 5x times**
![изображение](https://user-images.githubusercontent.com/1251672/220864637-98c9975e-1dbb-4e3e-9ed6-859934f6b9ab.png)

**Steps to reproduce the behavior with as much detail as possible:**

1. Just fight him

**IDs of affected creatures, items, quests or spells with a link to the relevant page:**

NPC: https://database.turtle-wow.org/?npc=3456

**Expected behavior. Describe how it should work:**

Chance to deal extra attacks should work only for first attack, not for extra attacks.

**Comment by geojak** [comment]
Sounds like a hardcore character trap

**Comment by Haaxor1689** [comment]
cannot reproduce on current version after multiple minutes of testing
working as intended
