### ISSUE TITLE
Dropped weapon effect with one\two handed spec talents lowers your damage permanently

### ISSUE THREAD

**Issue by dropsera** [slowtorta/turtlewow-bug-tracker#2889]
**Please, provide a clear description what the bug is:**
When paladin (and probably other classes with similar talents) starts switching weapons while under "Dropped your weapon" effects, damage after the effect stops gets progressively lower, stopping only at 1-1 damage with any weapon at all. The cause is probably one\two handed spec talent calculating final values incorrectly. This gets fixed after relog, but lingers permanently without.

**Steps to reproduce the behavior with as much detail as possible:**

1.Spec into one handed specialization, have weapon equiped
2. Get hit by "Dropped your weapon" effect from Highland Lashtail in Wetlands for example
3. Start switching weapons or reequiping same weapon
4. Deal a whopping 1 damage after several rounds

**IDs of affected creatures, items, quests or spells with a link to the relevant page:**

https://database.turtle-wow.org/?npc=1016
https://database.turtle-wow.org/?spell=6608
https://database.turtle-wow.org/?spell=20199

**Expected behavior. Describe how it should work:**

![WoWScrnShot_022423_010202](https://user-images.githubusercontent.com/98346835/221047198-e3c0c2e7-e0cb-471a-a6f4-5b15fe2e9a63.jpg)

**Comment by geojak** [comment]
Visual only or do you rly do Jsut 1 dmg?

**Comment by geojak** [comment]
Sounds very Similiar to https://github.com/slowtorta/turtlewow-bug-tracker/issues/2865

**Comment by dropsera** [comment]
yes, really
![534567778](https://user-images.githubusercontent.com/98346835/221210717-645c198f-9d1a-4ce9-86b3-296d4d099f03.jpg)

**Comment by dropsera** [comment]
Yes, really.
![534567778636333](https://user-images.githubusercontent.com/98346835/221211262-ad43548a-3c2c-4a59-bcde-926fe1a7a48c.jpg)

**Comment by twowTurtReynolds** [comment]
Someone must have noticed this issue elsewhere, and disabled the mobs ability to cast Lash, as I cannot get 5 of them to cast it on me...

**Comment by cyaohiri** [comment]
> Someone must have noticed this issue elsewhere, and disabled the mobs ability to cast Lash, as I cannot get 5 of them to cast it on me...

Is that just a temporary fix until the disarm effects are fixed?
Does it also affect other mobs that can trigger the Dropped Weapon effect?
https://www.wowhead.com/classic/spell=6607/lash#used-by-npc
https://www.wowhead.com/classic/spell=25852/lash#used-by-npc
https://www.wowhead.com/classic/spell=25425/shockwave#used-by-npc
