### ISSUE TITLE
Unswappable weapon glitch

### ISSUE THREAD

**Issue by BosBeest** [slowtorta/turtlewow-bug-tracker#289]
Quest: "Set Them Ablaze!" https://classicdb.ch/?quest=3463
Item: "Torch of Retribution" https://classicdb.ch/?item=10515

Equiping the 2h staff Wich is also an quest item functions as normal, but if you get into combat once you cannot switch weapons untill you relog, you're stuck wairing the staff.

**Comment by slowtorta** [comment]
Couldn't reproduce this one, working as intended, sorry.
