### ISSUE TITLE
Ekos in winterspring shouldn't be shared quest loot 

### ISSUE THREAD

**Issue by geojak** [slowtorta/turtlewow-bug-tracker#2890]
**Please, provide a clear description what the bug is:**

"Winterspring is notorius for people farming it for consumes, but, those who have farmed it know that the BEST way to farm E'kos is to have multiple lvl 60 characters in a raid and just kill the mobs with 1 character and if an Eko DOES drop, every party and raid member gets one.
This is good for veterans but it's discouraging for players without access to multiple accounts with lvl 60 characters on them."

Imagien yiu made a raid with 40 people and everyone could herb the black lotus or loot fellcoth. This is the situation here, because ekos can a lctually be sold for good money on ah. Nothing else works like this with shared group loot that can be traded. Only, quest items that are soulbound and untradeable. This is a bug

**Steps to reproduce the behavior with as much detail as possible:**

1. Be in a raid with people
2. Kill winterspring mobs for eko
3. When a eko drops, everyone in raid can loot one like a shared quest item

**IDs of affected creatures, items, quests or spells with a link to the relevant page:**

https://database.turtle-wow.org/?search=E%27ko 

**Expected behavior. Describe how it should work:**

Should not be shared group loot and instead be normal loot that is not shared. One eko drops, one person gets it. 

P. S. Come lynch me tawwney

**Comment by balakethelock** [comment]
When your life purpose is being an annoyance to other people, you start to delude yourself into thinking every convenient feature is a bug.
https://www.wowhead.com/classic/item=12436/frostmaul-eko#comments:id=3163633

**it's blizzlike. NOT A BUG**

**Comment by suggney** [comment]
not a bug

**Comment by CosminPOP** [comment]
Not a bug.

**Comment by geojak** [comment]
Well then it's a blizzlike bug @ratkosrb

**Comment by fatnerdynerd** [comment]
Msg you need to understand that this isn't a good use of your time, it's unhealthy, nobody likes this, you're delaying future updates by forcing Devs to look into bugs that half the time are intended the other half no1 wants them fixed. Just drop it.

**Comment by afizzler** [comment]
Please stop trying to intentionally make bug reports without merit to simply drag down dev resources.

**Comment by geojak** [comment]
@suggney 
You said" not a bug at all, same mechanic as multiple other things that loot in such a fashion ". 

Could you name a few examples? I would be interest to know

**Comment by suggney** [comment]
head of balnazzar etc, id say more quests but i'll save you the time of
individually making a ticket for all of them

**Comment by geojak** [comment]
No mean, any item that works like that, that can be traded

**Comment by Haaxor1689** [comment]
don't worry about dev resources, just report anything you might find to not work as intended. worst case scenario, reading and closing an issue takes few seconds.

**Comment by Zebouski** [comment]
Geojak, this change would remove one of the very few goldfarms in the game that actually encourage you to group up with friends. Encouraging socialization through the game design, is one of the core tenents of vanilla wow, and going the other way, to encourage people to play solo in this mmo.... well that's super duper lame. I feel everyone else in this thread feels this same thing, they just dont know or care enough to articulate it. Hopefully this sheds some light.

Yes people bringing 10 accounts multiboxing to pick them up is cringe. But that's been fixed, we're now only allowed two 2box in the world in combat.

And yes, a 40man raid farming a place would be strange, but here's the thing, there's a limited amount of eko droppers to kill, with a limited respawn time. Even at 3 people, you will raze a winterfall village to the ground. 5 people is kind of the max, and any more trying to farm the area will just eat into eachother's profits until it is no longer any good. The problem of a 40man raid farming something solves itself, and now you see why 40mans are never seen farming winterspring.

**Comment by geojak** [comment]
thank you Zebouski for giving good and based arguments
thank you for caring to explain instead of just going straight to personal attacks
