### ISSUE TITLE
Selling The Hawk's Vigil rewards to vendor

### ISSUE THREAD

**Issue by Kitty-Pryde** [slowtorta/turtlewow-bug-tracker#2892]
**Please, provide a clear description what the bug is:**

The Hawk's Vigil rewards say they have no sell price when they can be sold. 

**Steps to reproduce the behavior with as much detail as possible:**

1. Complete The Hawk's Vigil and take Magnificent Necklace.
2.  Sell item.  

**IDs of affected creatures, items, quests or spells with a link to the relevant page:**

Item: https://database.turtle-wow.org/?item=81418
Quest: https://database.turtle-wow.org/?quest=55225

**Expected behavior. Describe how it should work:**

If it indeed has no sell price, Magnificent Necklace (and I assume the other reward options too) should not be able to be sold. Otherwise, they need to be updated to display their vendor sell price correctly—20 silver.

**Comment by Kitty-Pryde** [comment]
Just in case anyone needs to know

**Comment by cyaohiri** [comment]
The vanilla client does not display item sell prices. It's up to the addon you're using to include each item's sell price into its database.

**Comment by redmagejoe** [comment]
Items do indeed have a sell price. If you are using the SellValue addon, it will list items as No Sell Price until you visit a vendor, at which point the saved price will be updated.

This is working as intended, and can be closed.

**Comment by Kitty-Pryde** [comment]
I'm not using any addons. The item literally says "no sell price" but can still be sold. If it can be sold for 20 silver, then it should say that when I go to vendor like the rest of the items.

**Comment by redmagejoe** [comment]
This is clientside and not a server bug. I cannot reproduce. The correct sell price displayed for me when tested.
