### ISSUE TITLE
Not possible to make fishing boat's

### ISSUE THREAD

**Issue by sulvar** [slowtorta/turtlewow-bug-tracker#2895]
**Please, provide a clear description what the bug is:**
I tried making a fishing boat on my character for the first time. It took my required items but did not give me a boat. I checked mail and bank. I tried to make another after cool down and it says I can't hold any more of these. I did have a tent in my inventory so maybe that effected it.
I then used my other character with survival that has also never made a boat. It took my items also and didn't give me a boat. 
I did make sure there was no tent in my inventory. I do have to keep tents in my inbox since we can't store more than 1 tent in our inventory. I have tents in both of there inboxes all the time. 
**Steps to reproduce the behavior with as much detail as possible:**

1.
2. 
3. 

**IDs of affected creatures, items, quests or spells with a link to the relevant page:**

NPC: https://database.turtle-wow.org/?npc=
Item: https://database.turtle-wow.org/?item=
Quest: https://database.turtle-wow.org/?quest=
Spell: https://database.turtle-wow.org/?spell=
Object: https://database.turtle-wow.org/?object=

**Expected behavior. Describe how it should work:**

**Comment by RUTHINAS** [comment]
The Fishing Boat icon is a stack of planks. Looks exactly like Simple Wood, very easy to miss.

It does need a new icon, though.

**Comment by redmagejoe** [comment]
Cannot reproduce on current version. I just made a fishing boat.

Working as intended.
