### ISSUE TITLE
Typos in Breaking Contracts custom quest

### ISSUE THREAD

**Issue by alazae55** [slowtorta/turtlewow-bug-tracker#2897]
There are some typos in the quest text. for "Breaking Contracts"

1. It says "you may not see it, but its there." when it should be "you may not see it, but it's there."
2. it says "seperates" instead of "separates"

**IDs of affected creatures, items, quests or spells with a link to the relevant page:**
Quest: https://database.turtle-wow.org/?quest=40223

Please use spellcheck on quest text it's not that difficult.

**Comment by cyaohiri** [comment]
Also, "smilling" instead of "smiling".
