### ISSUE TITLE
[EPL] Crypt Fiend's abilities "Crypt Scarabs" seems to be broken

### ISSUE THREAD

**Issue by faralynn** [slowtorta/turtlewow-bug-tracker#29]
By opening this Issue, I admit to having done the pertinent research using sources from Vanilla (preferably) or Classic. I also understand that sources from other private servers are not acceptable.

**Current behavior**: 
It summons Crypt Scarab's but they almost immediately despawn.

**Expected behavior**: 
They should last 10 seconds or at least until killed.

**Proofs**:
![crypt](https://user-images.githubusercontent.com/2092314/121649803-ed33c500-ca66-11eb-9855-8e0f9b000b5f.jpg)

Note the timestamps here. At 03:55:43 it finishes casting Crypt Scarabs. At 03:55:44 there are no more attacks from them. Seems they have a lifetime of 1s than 10s.

And here is one of the Crypt Scarabs spells (there's 3)
https://database.turtle-wow.org/?spell=16594

> Summons 4 Crypt Scarabs to aid the caster in battle for 10 sec.

**Steps to reproduce**:

1. Goto Terrorweb Tunnel in EPL
2. Aggro a Crypt Fiend
3. Observe it casting Crypt Scarabs
4. Note down their lifespan

**Potentially semi-related issue**
I most certainly observed a similar bug in Stratholme Undead. I believe it was with Nerub'enkan seeing that it is the only monster in Stratholme that can summon scarabs.

**Comment by Nolin7777** [comment]
Cannot reproduce. They die until the reach/hit you.
