### ISSUE TITLE
Custom expedition mobs have a massive stealth touch radius

### ISSUE THREAD

**Issue by Kangaroux** [slowtorta/turtlewow-bug-tracker#2901]
Level 23 rogue, level 11 mob.

Mobs detect you if you get too close to them. This detection radius is also where their stealth vision starts. All of the expedition mobs (scouts, commandos, soldiers, etc.) have a touch radius which is way too big. This makes it extremely difficult to attack them from stealth, or even pickpocket.

https://user-images.githubusercontent.com/2302541/221383921-1af3fd7a-6cc4-4e62-aa76-63cc03f19fc7

**Comment by Kangaroux** [comment]
Tiragarde mobs for comparison. The touch radius should be about the same as the red target circle under the mob.

https://user-images.githubusercontent.com/2302541/221384198-254f02cf-d663-419f-9eb6-6180e7b26082.mp4

**Comment by Sringaram** [comment]
This also happens in custom dungeons and other custom zones. 

Not sure if it's an oversight or the developer in charge hates rogues and druids.
