### ISSUE TITLE
Shaman talent [Elemental Focus] (clearcasting) is not affecting [Stormstrike]

### ISSUE THREAD

**Issue by Rhythmfish** [slowtorta/turtlewow-bug-tracker#2902]
**Please, provide a clear description what the bug is:**
Elemental Focus is a talent that reduces mana cost of the next 2 outgoing damage spells.
If Stormstrike is a damage spell then it is not affecting it correctly. Mana cost is not reduced under the clearcasting buff.

**Steps to reproduce the behavior with as much detail as possible:**

1. Get clearcasting buff
2. Notice mana did not decrease on stormstrike
3. profit?

**IDs of affected creatures, items, quests or spells with a link to the relevant page:**

https://database.turtle-wow.org/?spell=17364
https://database.turtle-wow.org/?spell=16246
https://database.turtle-wow.org/?spell=16164

**Expected behavior. Describe how it should work:**

Clearcasting reduces mana cost of stormstrike by 40%

**Comment by Babygrim** [comment]
Stormstrike grants extra MELEE attack on use, hence benefits from MELEE %hit, so its clearly not a damaging spell, so why would it benefit from proc that affects damaging SPELLS?

**Comment by Rhythmfish** [comment]
> Stormstrike grants extra MELEE attack on use, hence benefits from MELEE %hit, so its clearly not a damaging spell, so why would it benefit from proc that affects damaging SPELLS?

Fair enough. I thought it was a spell.

**Comment by jameyboor** [comment]
Not a bug.
