### ISSUE TITLE
Cowl of Mivax: no mana regen during casts

### ISSUE THREAD

**Issue by Trofogol** [slowtorta/turtlewow-bug-tracker#2904]
**Description of the bug:**
Cowl of Mivax does not give a 5% of mana regeneration speed during casts

**Steps to reproduce the behavior:**

1. Equip Cowl of Mivax
2. Cast any spell
3. Check the mana regeneration during casting

**IDs of affected itemwith a link to the relevant page:**

Item: https://database.turtle-wow.org/?item=83451

**Expected behavior:**
Mana should regenerate during the casts (5% of a non-casting speed) according to the item description

**Comment by redmagejoe** [comment]
Cannot reproduce on current version. With this equipped on a character with no "mana regen while casting" talents or effects, I still gained 2/3 mana of my 50 window mp5 every few seconds even while spamming spells.

Working as intended.
