### ISSUE TITLE
Judgement Bug

### ISSUE THREAD

**Issue by Babygrim** [slowtorta/turtlewow-bug-tracker#2905]
**Please, provide a clear description what the bug is:**

Sometimes judgement does not unleash seal's power but simply removes it with no effect at all.
I met this bug with Seal of Righteousness and other paladin from world chat confirmed that he had same issue with Seal of Command, I assume it can occur with any paladin seal. No message that it was resisted or anything in combat log nor UI.

**Steps to reproduce the behavior with as much detail as possible:**

1. Activate any paladin seal.
2. Time use of judgement with auto-attack swing or Holy Strike swing.
3. Sometimes judgement wont unleash active seals power.

**IDs of affected creatures, items, quests or spells with a link to the relevant page:**
Spell: https://database.turtle-wow.org/?spell=20271
Spell: https://www.wowhead.com/classic/spell=20289/seal-of-righteousness

**Expected behavior. Describe how it should work:**
Judgement should be always unleashing active seals power.

**Comment by geojak** [comment]
https://github.com/slowtorta/turtlewow-bug-tracker/issues/1953

**Comment by Zeyla-TW** [comment]
I just confirmed this twice out of about 20 attempts to judgement at the exact moment that a auto-attack swing occurs. The combat log does not show any damage dealt by judgement of righteousness, nor do the numbers appear as combat text. Lining up the 2 combat log events perfectly such that the auto-attack prevents the judgement damage from occurring seems fairly rare, but it can indeed happen.

**Comment by twowTurtReynolds** [comment]
Tracking this dupe under https://github.com/slowtorta/turtlewow-bug-tracker/issues/1953
