### ISSUE TITLE
Load Lightning - 1k Needles Missing Vulture spawns(6)

### ISSUE THREAD

**Issue by ShiyoKozuki** [slowtorta/turtlewow-bug-tracker#2906]
This  quest is terrible to do now that you added a town and removed the 6 spawns at the destroyed boat

It was already the worst and hardest of the shimmering flat quests, now it's legit unbearable.

There is currently SIX people camping 3 spawns of mobs on a 5 minute timer that you need 10 minimum (not 100% drop rate) of to complete the quest. This is awful.

 Please add back the missing vultures.

**Comment by Zeyla-TW** [comment]
This isn't really a bug but more of a QoL suggestion for the questing hub in Shimmering Flats to re-add some mob spawns.
