### ISSUE TITLE
Gray enemy agro radius.

### ISSUE THREAD

**Issue by Darkhag** [slowtorta/turtlewow-bug-tracker#291]
**Please, provide a clear description what the bug is:**

Gray enemies are agroing even at distance.  They are also taking almost as long to take down as greens ( this would be grays ten and 20+ levels below)
It wasn't like this a year ago that I can remember when I last played.  I'm sorry there's no object or spell to  place from the data base.  it's everywhere and everything.  At first I thought it was my game so I deleted wdb and wtf.  that resulted in gray mobs  not hitting as hard and reduced the amount of beating upon them I needed to do to kill them when they attacked me for running past ( which was almost as much as I need to kill an at level enemy before I deleted my wtf)  I asked around and a lot of players have the same issue.   Agro radius to wide? High? Broken?

**Steps to reproduce the behavior with as much detail as possible:**

1. Go to an area where mobs are gray to your test character.
2.  Walk around.
3. Observe different type of enemy reactions and range from enemy when  agroed.

**IDs of affected creatures, items, quests or spells with a link to the relevant page:**

NPC: https://database.turtle-wow.org/?npc=
Item: https://database.turtle-wow.org/?item=
Quest: https://database.turtle-wow.org/?quest=
Spell: https://database.turtle-wow.org/?spell=
Object: https://database.turtle-wow.org/?object=

**Expected behavior. Describe how it should work:**
Gray enemies should ignore players. Unless 1. the player attacks them and 2. A player walks into them.

**Comment by AyleeJenn** [comment]
I don't know if there is really an error here. As far as I can tell aggro range changes dynamically depending on your level relative to the leve of the enemy. If you are far below an enemy's level, they will aggro you from miles away. But if you vastly out level an enemy you will have to get closer and closer to even get aggro from the enemy.

I tested this on a level three enemy when my own character was level twenty or so. I did not get aggro unless I walked straight into the enemy. So, could it be that this is working as intended?

**Comment by Darkhag** [comment]
Maybe it’s my account. I made it last year and I’ve had nothing but problems since I came back.  With agro, with broken triage, with the mobs needing to be hit as much as a green mob when 20 levels below me to kill them,  the mysterious stranger only being a checkered cube.  A few other things as well.  IS there anything I can do to fix this at all? I deleted the wtf and wdb and no changes.
Account DARKHAG
I really appreciate your time. I know you must be busy.
But if my account is unsalvageable I don’t want to buy the tokens I want if I have to abandon it and start again.

**Comment by AyleeJenn** [comment]
Oof, thats a slew of problems alright. It sounds like you might want to pm Torta directly about this, as I am just a player participating in the bug reporting. You can try reaching out via the serve's discord channel.

**Comment by Darkhag** [comment]
Thank you very much. I will do that.  Your reply is  appreciated to the max.

Sent from Mail<https://go.microsoft.com/fwlink/?LinkId=550986> for Windows

**Comment by Nolin7777** [comment]
Working as intended
