### ISSUE TITLE
Arathi Basin Nodes on Map

### ISSUE THREAD

**Issue by Jammyxx** [slowtorta/turtlewow-bug-tracker#2911]
**Please, provide a clear description what the bug is:**
The Nodes on the map do not appear, so you cannot see which faction controls which base. 
**Steps to reproduce the behavior with as much detail as possible:**

1. Join AB
2. Open Map. 
3. 

**IDs of affected creatures, items, quests or spells with a link to the relevant page:**

NPC: https://database.turtle-wow.org/?npc=
Item: https://database.turtle-wow.org/?item=
Quest: https://database.turtle-wow.org/?quest=
Spell: https://database.turtle-wow.org/?spell=
Object: https://database.turtle-wow.org/?object=

**Expected behavior. Describe how it should work:**

**Comment by Haaxor1689** [comment]
Will be fixed next client patch
