### ISSUE TITLE
quests on tel'abim doesnt give extra gold at max level

### ISSUE THREAD

**Issue by hejez** [slowtorta/turtlewow-bug-tracker#2912]
**Please, provide a clear description what the bug is:**
When questing on Tel'Abim at max level, the quest rewards does'nt give extra gold as it should, when it should turn experience into gold. This works in all other zones.
**Steps to reproduce the behavior with as much detail as possible:**

1. Do a quest on Tel'Abim, for example the one with murlocs
2. Turn it in
3. ????

**IDs of affected creatures, items, quests or spells with a link to the relevant page:**

NPC: https://database.turtle-wow.org/?npc=
Item: https://database.turtle-wow.org/?item=
Quest: https://database.turtle-wow.org/?quest=
Spell: https://database.turtle-wow.org/?spell=
Object: https://database.turtle-wow.org/?object=

**Expected behavior. Describe how it should work:**
It should give extra gold, converting the experience into gold.

**Comment by cyaohiri** [comment]
This seems related to #2439.
