### ISSUE TITLE
Occasionally empty fishing loot in Gillijim Isle

### ISSUE THREAD

**Issue by RUTHINAS** [slowtorta/turtlewow-bug-tracker#2913]
**Please, provide a clear description what the bug is:**
Fishing in open water in Gillijim occasionally yields "empty" loot; the bobber splashes, but right clicking it causes it to despawn with no loot window. I haven't done a thorough study, but it seems to happen quite often, perhaps once every five casts. There is no "Your fish got away" error message. The behavior is the same as it was before fishing loot tables were added to Gillijim, except then it happened on every cast.

**Steps to reproduce the behavior with as much detail as possible:**

1. Fish repeatedly in Gillijim Isle
2. Observe occasional empty loot

**Expected behavior. Describe how it should work:**
Typically, when fishing with sufficient skill and bonuses, every use of the fishing ability should yield loot.

**Comment by Zeyla-TW** [comment]
Indeed, the open water around Gillijim Strand does not seem to reference a loot table to the fishing bobber, and you can only receive items when fishing in pools instead. I do not know if it was intended or not, but one would likely expect similar loot to other coastal areas around the same level when not fishing in a pool.
