### ISSUE TITLE
Tirisclaw Bears and Cubs are static

### ISSUE THREAD

**Issue by Herdon** [slowtorta/turtlewow-bug-tracker#2917]
**Please, provide a clear description what the bug is:**
Tirisclaw Bears and Tirisclaw Cubs are static and not wondering like the rest of the mobs in Tirisfal Uplands.

**IDs of affected creatures, items, quests or spells with a link to the relevant page:**

https://database.turtle-wow.org/?npc=91984 (Tirisclaw Bear) 
https://database.turtle-wow.org/?npc=91985 (Tirisclaw Cub)

**Expected behavior. Describe how it should work:**
They should be wondering like the rest of mobs in the zone. Bears _with_ Cubs should probably have linked pathing.

![Bear Static 2](https://user-images.githubusercontent.com/2021593/222044571-97cded3e-08c8-4c61-bb92-8082adaef6bd.jpg) ![Bear Static 1](https://user-images.githubusercontent.com/2021593/222044577-9f91cc29-a7cf-47d8-b075-143a0562b143.jpg)

**Comment by geojak** [comment]
This has been reported before

**Comment by geojak** [comment]
https://github.com/slowtorta/turtlewow-bug-tracker/issues/1488

**Comment by Herdon** [comment]
Those issues were **closed**, but the problem still persist.

**Comment by geojak** [comment]
Yea sadly

**Comment by Herdon** [comment]
Problem still persist after March 10 Update:
https://forum.turtle-wow.org/viewtopic.php?t=5932

https://user-images.githubusercontent.com/2021593/226210472-e5f20a33-a756-4546-b893-2288ed16bb8c.mp4

_Video was taken on March 19_

**Comment by Gurky-Turtle** [comment]
Done @geojak

**Comment by Muigin** [comment]
This will be fixed in a future maintenance.
