### ISSUE TITLE
Hunter pets cant gain loyalty

### ISSUE THREAD

**Issue by Zrambox** [slowtorta/turtlewow-bug-tracker#292]
I've been trying for several hours to gain loyalty with different hunter pets and after raising them several levels and feed all the time they stay rebellious until they leave because get more happiness turn more difficult dont matter how many stacks of food i give to him. 

seems the same case as this: 
https://us.forums.blizzard.com/en/wow/t/hunter-pets-not-gaining-or-retaining-loyalty-runs-away/282732

**Comment by Denmokin** [comment]
Same issue here, it is always running with no reason please fix it :)

**Comment by Harlotfields** [comment]
Similar issue with NElf Hunter and pet (Cat). Constantly I'm feeding it after a minute of being Green only for it to fall back to Yellow after a few minutes.

**Comment by LeopoldHock** [comment]
This is Vanilla behavior. Pets lose happiness extremely fast while on low loyalty levels. It gets better when loyalty increases up to the point where you can easily leave your pet unfed for 60 minutes without happiness dropping from green to yellow.
