### ISSUE TITLE
Spell Haste glove enchant not reflected in tooltips

### ISSUE THREAD

**Issue by Jeradooka** [slowtorta/turtlewow-bug-tracker#2921]
**Please, provide a clear description what the bug is:**
Equipping gloves enchanted with the +1% haste enchant does not get properly reflected in tooltip cast times.

**Steps to reproduce the behavior with as much detail as possible:**

1. Equip gloves without the 1% haste enchant. Note spell casting time tooltips.
2. Equip gloves with the 1% haste enchant.
3. Compare the two times and notice there has been no reduction.

**IDs of affected creatures, items, quests or spells with a link to the relevant page:**

Enchant: https://database.turtle-wow.org/?spell=13948
Lightning Bolt: https://database.turtle-wow.org/?spell=15210

**Expected behavior. Describe how it should work:**
Other items that reduce casting times are reflected in tooltips. These should do the same. Or the others should not modify tooltips.

**Comment by Zeyla-TW** [comment]
Confirmed, while haste equip bonuses on items and arcanum of rapidity enchant to legs/helm dynamically adjust the cast time in spell tooltips, the 1% haste to glove enchant does not cause a dynamic update to the cast time in tooltips.

**Comment by geojak** [comment]
https://github.com/slowtorta/turtlewow-bug-tracker/issues/1762 might be related

**Comment by geojak** [comment]
the head and leg libram enchatns dont appear to increase cating spell tootlitp either @Zeyla-TW . or you i have to reenechant my gear?

**Comment by geojak** [comment]
![image](https://user-images.githubusercontent.com/25199983/223191479-7f73b297-a901-460a-9c1f-1c51a08ae3d7.png)
![image](https://user-images.githubusercontent.com/25199983/223191546-c258ad70-3873-4b28-b688-bcbdac372aee.png)

**Comment by Zeyla-TW** [comment]
> the head and leg libram enchatns dont appear to increase cating spell tootlitp either @Zeyla-TW . or do i have to reenechant my gear?

They updated things like lightning bolt and healing wave when I checked. I just checked flash of light as well and a single arcanum of rapidity brought it to 1.49 in the tooltip, and the 2nd brought it to 1.47. 
![image](https://user-images.githubusercontent.com/119783172/223225407-021a9d59-8195-4b63-972f-76f697b83f81.png)

**Comment by geojak** [comment]
does that mean i have to reenchantm my gear to get the new effect. this is rly weird

**Comment by Zeyla-TW** [comment]
> does that mean i have to reenchantm my gear to get the new effect. this is rly weird does it say attackspeed or haste on your tooltip?

I wouldn't just yet. I believe some haste spells may have been tweaked on the PTR so don't be too "hasty" 😄

**Comment by geojak** [comment]
i see, thank you for explaining! then i will be awaiting the good news once ptr changes go to live :)
