### ISSUE TITLE
Quest Return to Port! grouped with Arathi Highlands quests

### ISSUE THREAD

**Issue by AKryukov92** [slowtorta/turtlewow-bug-tracker#2924]
Current behavior:
Return to Port! https://database.turtle-wow.org/?quest=55051
is under Arathi Highlands category in quest log.
Player should "Report the good news to Pazzle Brightwrench in Sparkwater Port."

Expected behavior:
Quest should be in Durotar category

**Comment by Haaxor1689** [comment]
Fixed next udpate
