### ISSUE TITLE
Target Dummies dropping no loot

### ISSUE THREAD

**Issue by RUTHINAS** [slowtorta/turtlewow-bug-tracker#2925]
**Please, provide a clear description what the bug is:**
As of the most recent patch, where loot issues with target dummies were supposedly fixed (#2640), a new and worse loot bug has been introduced. Target Dummies drop no loot whatsoever, none for the engineer or for the party to pick up. I tested this with the regular Target Dummies and the high-level Masterwork Target Dummies.

The previous loot tables were accurate to vanilla. The issue was that the dummies were lootable by everyone in the party, and affected by loot rules (group loot, free-for-all, master looter) when they should be lootable only by the engineer that uses them. Now it seems that they have no loot tables at all. This makes using the dummies prohibitively expensive, as previously some portion of the materials has been recycleable.

**Steps to reproduce the behavior with as much detail as possible:**

1. Use a target dummy, any kind
2. Wait for it to expire or have it be destroyed by damage
3. Observe a lack of loot

**IDs of affected creatures, items, quests or spells with a link to the relevant page:**

NPC:
https://database.turtle-wow.org/?npc=2673
https://database.turtle-wow.org/?npc=2674 (untested)
https://database.turtle-wow.org/?npc=12426

**Expected behavior. Describe how it should work:**
The dummies should have their previous loot tables (containing the same materials used to craft them, along with the occasional drop of a Fused Wiring). They should be lootable by the engineer that used them, and by the engineer only (including the uncommon-quality Truesilver Bar sometimes contained in a Masterwork Target Dummy, which would previously pop up as a loot roll). This should not be in any way affected by loot rules.

In case making this fix would take a long time to perform, I believe it would be better to roll back to the previous version in the meantime. I'd much rather go through the trouble involved in pestering party members to loot the dummies and then having them to trade the materials to me, than not having any loot at all.

**Comment by slowtorta** [comment]
You're correct, I forgot that they drop their ingredients and assumed they simply got empty loot tables assigned by a mistake. It'll be reverted.
