### ISSUE TITLE
Warlock - Spellstone dispel magic effect

### ISSUE THREAD

**Issue by lunarpriest** [slowtorta/turtlewow-bug-tracker#2926]
**Please, provide a clear description what the bug is:**

There are two conflicting ingame descriptions as to how spellstones work when used (i.e. whether all magic effects are dispelled or only harmful magic effects are dispelled).

(1) the item description states that using the item dispel all magic effects.

(2) the spell description states that the conjured item can be used to dispel harmful magic effects only.

**Steps to reproduce the behavior with as much detail as possible:**

1. create spellstone (normal, greater, major)
2. equip spellstone in offhand making sure a mainhand weapon is equipped
3. cast demon armor or demon skin (of any rank)
4. use spellstone
5.  demon armor gets dispelled (not a harmful spell)

**IDs of affected creatures, items, quests or spells with a link to the relevant page:**

Item: https://database.turtle-wow.org/?item=5522
Spell: https://database.turtle-wow.org/?spell=2362

**Expected behavior. Describe how it should work:**

I believe the intended way it should work is that when the spellstone is used only harmful magic effects are dispelled.

**Comment by Zeyla-TW** [comment]
This is actually how spellstones have always worked. Even though it says "harmful effects" on the spell tooltip, the conjured item itself does indicate that it removes "ALL" magic effects, and if you do a quick search you can see that people from back in 2006-2007 made the same observations.

At this point, we would call this "Working as intended" but we could also address this with the twow devs specifically to determine if this should be changed one way or the others on the server (either make it only affect harmful magic effects or change the tooltip on each 'conjure spellstone' rank to indicate that it removes all magic effects).

**Comment by lunarpriest** [comment]
I agree with everything Zeyla-TW wrote. I would consider the options listed as suitable for closing the issue. That is, either (1) change the spell tooltip description to match the conjured item description (removes all magic effects) or (2) rework how the spellstone interacts with magic effects (e.g. remove only harmful magic effects). I would prefer the second option, but that's just my opinion.
