### ISSUE TITLE
Mining Nodes - far too many everywhere

### ISSUE THREAD

**Issue by ShiyoKozuki** [slowtorta/turtlewow-bug-tracker#2927]
There are far too many mining nodes nearly everywhere. Did someone just copy one of the user-made maps from WoWhead? There isn't supposed to be 10 iron nodes in caves or other absurd amounts I'm finding everywhere. Most of the nodes look out of place, too, they're just sitting in the middle of a path.

I'd say nearly half the nodes in the game need to be removed to be Blizzard/retail/classic accurate.

**Comment by geojak** [comment]
Yea I agree the amount of nodes for iron and small thorium or true silver and gold in particular are insane.

**Comment by Trinax11** [comment]
Agreed. Same situation is with herbs. They are literally everywhere in insane amounts.
