### ISSUE TITLE
Typos and incorrect grammar found in TWoW custom quest, "The Keepers Charge"

### ISSUE THREAD

**Issue by bebraveorbeslave** [slowtorta/turtlewow-bug-tracker#2928]
Recommended corrections for quest description:

"For thousands of years I have kept my watch over this place. <(period here instead of comma) I have seen the world change around me, and most of the old city be swept beneath the waves. The magic <(lower-case m instead of upper-case M) that once ran through this place has been dampened <(no comma here) and is almost non-existent. <("existent", not "existant")

With the rising waters my studies have been increasingly difficult. <(period here instead of comma) To keep watch over this tower is to protect it, and with the growing threat of the invasive ocean species my time has been more toward survival then study.

I ask for assistance in this matter. <(period here instead of comma followed by capital letter for new sentence) Slay the murloc, the hydra and the crab beasts <(plural "beasts" here instead of singular "beast") around the area to preserve this tower if even for a moment longer."

Recommended corrections for quest completion:

"I can breathe a sigh of relief. <(period here instead of comma followed by capital letter for new sentence) At one time I could walk the entirety of the beach, I could journey through the buried ruins of the old city, now submerged beneath the waves, but now, I am confined to this very tower. Perhaps one day I will be free to journey again."

Link to quest in database:

https://database.turtle-wow.org/?quest=40243

**Comment by cyaohiri** [comment]
>Slay the murloc, the hydra and the crab beasts <(plural "beasts" here instead of singular "beast") around the area to preserve this tower if even for a moment longer."

Given that the quest asks for you to slay multiple of each type, shouldn't all three be in the plural form?
