### ISSUE TITLE
Warlock - Remove Avoidance from players

### ISSUE THREAD

**Issue by balakethelock** [slowtorta/turtlewow-bug-tracker#2930]
**Please, provide a clear description what the bug is:**
Aoe abilities do half the damage they say they do on combat logs

**Steps to reproduce the behavior with as much detail as possible:**
1. Enter combat with a mob or a player
2. Cast any rank of hellfire or rain of fire
3. Watch the target's health drop by only half the amount it should drop.
**THEORY:  the cause of the bug is the grimoire of Avoidance that should let pets take half damage from aoe. The damage reduction is exactly half in both cases.**
**So if you can't reproduce it, learn Avoidance and try again**

https://youtu.be/9zbjt0P1r0o
https://youtu.be/oY-O3T4UD_Q

**IDs of affected creatures, items, quests or spells with a link to the relevant page:**
https://database.turtle-wow.org/?spell=46024

**Expected behavior. Describe how it should work:**
Hellfire and Rain of fire should do the correct damage mentioned in combat logs.

**Comment by redmagejoe** [comment]
Cannot reproduce. Tested both Rain of Fire (Rank 4) and Hellfire (Rank 3) with Imp, Succubus, Voidwalker, and Fel Hunter, all of whom know Avoidance. Checked Combat Log (227 per Rain of Fire tick, 212 per Hellfire tick) and observed the same amount leave the enemy's HP bar. Tested on multiple enemy types with no variation outside of resists.

Be sure you are not suffering from the AoE target cap, a threshold beyond which your AoE damage is reduced per affected target to avoid situations where a player could in theory mob 50 enemies and hit them with full-power AoE spells.

Working as intended.

**Comment by balakethelock** [comment]
The avoidance is not on the pets, **it's on me in **my** spellbook.**
And as you can see from the video my spell was only hitting one target or two so its impossible to be the AoE target cap which doesn't even exist in vanilla.
The issue still exists for people who learned Avoidance when the grimoire was bugged and gave the ability to the player instead of to the pet and for that reason I request reopening it and looking more closely at the video I posted.

**Comment by balakethelock** [comment]
@Haaxor1689

**Comment by Haaxor1689** [comment]
If there was a bug where Avoidance was applied to players instead of their demons then that is what's supposed to be fixed. Then it won't be relevant whether avoidance reduces caster's aoe damage as well.

**Comment by balakethelock** [comment]
Update: I opened a ticket and a GM removed avoidance from me manually ingame, there might still be warlock players who have Avoidance and unknowingly continue playing with the bug.

**Comment by Haaxor1689** [comment]
We will keep this opened until it's removed from players globally.
