### ISSUE TITLE
Game breaking possible infinite loot

### ISSUE THREAD

**Issue by Seaofgioy** [slowtorta/turtlewow-bug-tracker#2931]
**Please, provide a clear description what the bug is:**

**Steps to reproduce the behavior with as much detail as possible:**

1.Kill any Monster
2. Hold Shift for Autoloot [Optional: while in combat with another monster. Makes it easier to tab target]
3. Right click to Autoloot
4. Press "Esc", "Tab" or anything else to change target before the table closes.
5. The mob will remain lootable.
6. it's possible that higher ping makes it easier to perform, but i'm working on a 30ms ping.

Images of me looting the same mob for 3 times its silver.
**IDs of affected creatures, items, quests or spells with a link to the relevant page:**

NPC: https://database.turtle-wow.org/?npc=4466 , probably every mob.
Item: as long as it's only 1 lootable item it's fine.

**Expected behavior. Describe how it should work:**
You should only be able to loot it once
![bug 2](https://user-images.githubusercontent.com/126973349/222916473-8421b444-6189-4163-b2cb-0fbc4a644f38.png)
![bug infinite loot](https://user-images.githubusercontent.com/126973349/222916474-a4af894b-6122-4dd2-a10c-9bcc49b35315.png)

**Comment by cyaohiri** [comment]
Last time I tested this, the bug was only visual. The money was looted only the first time. Make sure to check the money in your bags before and after the multiple loot.

**Comment by Seaofgioy** [comment]
This might be the case, i'll try to replicate this, not having much success.

**Comment by Seaofgioy** [comment]
Very good, it's only visual, that i could see, You onlt obtain the silver the last time you loot it!
