### ISSUE TITLE
Consume Shadows - voidwalker behaviour bugged

### ISSUE THREAD

**Issue by Trinax11** [slowtorta/turtlewow-bug-tracker#2935]
**Please, provide a clear description what the bug is:**
Consume Shadows (voidwalker spell) channel always cancels because voidwalker keeps following player. You basically now have to stay and don't move or force voidwalker to stay with a command. 
**Steps to reproduce the behavior with as much detail as possible:**
1. Cast consume shadows
2. Walk away from voidwalker
3. Voidwalker stops cast and follows a player.

**IDs of affected creatures, items, quests or spells with a link to the relevant page:**
Spell: https://database.turtle-wow.org/?spell=17854

**Expected behavior. Describe how it should work:**
Voidwalker should stay on his position while channeling the spell. After finishing the channel he follows player again.

**Comment by Zeyla-TW** [comment]
Confirmed, the spell typically causes the voidwalker to channel and effectively "hold position" until the channel ends or and attack order or other spell command is issued, but it currently tries to follow immediately if the warlock moves, causing the Consume Shadows to be interrupted. It indeed did not work this way previously.
