### ISSUE TITLE
WoW Turtle custom quests are not sharable

### ISSUE THREAD

**Issue by ibuk27** [slowtorta/turtlewow-bug-tracker#2937]
**Please, provide a clear description what the bug is:**

Pretty much all new custom quests I've come across are not sharable. The only custom quests that are sharable are dungeon quests.

**Expected behavior. Describe how it should work:**

By original standards, many of these new quests should be sharable (excepting, of course, quests that don't meet the criteria for being sharable, like when quest giver gives you an item, etc.). For those of us who level in group, it's unfortunate that this isn't implemented. Thank you

**Comment by slowtorta** [comment]
Sadly, we cannot do much with a report like that. You have to at least open report and specify quest chains, or specific quests so we can pinpoint and fix it.

**Comment by ibuk27** [comment]
Thank you for your reply! I honestly don't understand why does it have to be on the player's side to specify quest chains. ALL turtle custom quests are unsharable -- that's it. The "share quest" quest log button is always greyed out for Turtle custom quests (apart from new dungeon quests). This is not a bug pertaining to a set of specific quests.

I would think there would be no need to pinpoint anything else. Unless you expect the player to send you a spreadsheet with the list of all custom quests (surely hundreds)? I suppose you already have that information... Or am I expected to open a in-game report for every custom quest there is in the game (which would also amount to hundreds of tickets)?...

At first, I thought this was a deliberate choice, and posted on TWoW's forum as a suggestion. Someone told me to come here and report the issue. I thought I was doing my part reporting this. I'm sorry if I come across as rude, but I'm just confused... Thank you anyway!

**Comment by redmagejoe** [comment]
I mentioned this in your forum thread where you expressed the same idea, but I'll repeat here: I think you have a misconception about how the development process works. As you can see from this bug tracker and even more not listed here, the dev team has a lot on their plate and a lot of tasks they are currently working on and that are in backlog. They do not have a magic wand they can wave and utter "unshareable quests" that pops a list up in front of them. They rely on the exact same database you and I have access to, and in order to fix the correct quests with the correct flag, they must make a SQL query for all affected quest IDs.

They cannot use a blanket query, otherwise all quests in the game become shareable. Asking the devs to dig through every single Turtle custom quest to fix this is not entirely reasonable, but at the same time, you are right, you as the player are not obligated to do the same. Just know that it means that this bug will not get fixed in the timely manner you may wish. If you want specific quests to be made shareable sooner, it is behoove you to pinpoint the problem quests which would allow a dev to immediately write an SQL query, push it to live, and have it fixed in the next update.

Please provide more information if you want anything to come of this ticket. Thank you for your understanding.

**Comment by ibuk27** [comment]
Thank you for taking the time to elucidate me, I sincerely appreciate the effort. I don't understand how quests become part of the game, but it seems thing were not double-checked. Now we have hundreds of quests that are not sharable, and, it seems, no means to otherwise correct this situation. Anyway, it's no big deal, and thank you again for your time!

**Comment by cyaohiri** [comment]
I may have found a way to do this systematically.

Inside the mangos database, quests are in the `quest_template` table.
The goal is to select only those custom quests that should be shareable.
I don' t know which column is used to indicate that it's a custom (non-vanilla) quest, but you probably already know which one it is.
For the sake of the example, I'll use the `patch` column, and assume custom quests use value `42`.

Running `SELECT * FROM quest_template WHERE patch=42` returns all custom quests, but obviously, not all of them should be shareable.

The `quest_template` table contains columns `SrcItemId` and `PrevQuestId` that are relevant.

SrcItemId contains the ID of an item provided when accepting the quest, e.g. the quest [Young Lovers](https://www.wowhead.com/classic/quest=106/young-lovers) (ID 106) has 1208 as SrcItemId, which is [Maybell's Love Letter](https://www.wowhead.com/classic/item=1208/maybells-love-letter).
Quests that have provided items such as this one should _not_ be, and _are not_ shareable, as the provided items can only be provided by the NPC giving the quest.

To make sure we don't select those quests, we can add another condition which makes sure quest doesn't have any provided items.
Running `SELECT * FROM quest_template WHERE patch=42 AND SrcItemId=0` gives us all custom quests that have no provided items and are thus candidates for being shareable.

`PrevQuestId` is the ID of the quest needed to complete to unlock a given quest, e.g. [Seek Redemption!](https://www.wowhead.com/classic/quest=489/seek-redemption) requires [Zenn's Bidding](https://www.wowhead.com/classic/quest=488/zenns-bidding) (ID 488) to be completed, so it has 488 in the `PrevQuestId` column.

When trying to share a shareable quest with a player that hasn't done the prerequisite quest, the game just says that the player isn't eligible for the quest. This is how it works in vanilla and here, including both vanilla and some custom shareable quests such as [The Orb of Kaladus](https://database.turtle-wow.org/?quest=40233).

In summary, out of the set of all custom quests, those that have provided items (`SrcItemId`) should not be shareable (and already aren't).
Of the remaining quests, probably all should be shareable, given that the player with whom we're sharing it has completed any prerequisite quests.

Furthermore, we could select only those custom quests that have no provided items and no prerequisite quests by running `SELECT * FROM quest_template WHERE patch=42 AND SrcItemId=0 AND PrevQuestId=0`. However, as noted above, doing this would miss quests that should be shareable, but have prerequisite quests.

The best option seems to be to select the quests using `SELECT * FROM quest_template WHERE patch=42 AND SrcItemId=0`, and then exclude any quests that should not be shareable. There probably won't be many exceptions, and thus will be a net-positive change.

Going through a number of quests on Wowhead, I've noticed that the vast majority of non-shareable quests in fact had provided items.
I haven't figured out which, if any, of the columns in the `quest_template` table mark the quest as shareable. Know that would help me get a better idea on how many false-positives there will be when running the aforementioned query, as I'll be able to go through a lot more vanilla quests and perhaps see the pattern of non-shareable quests with no provided items.

Hopefully this helps.

**Comment by slowtorta** [comment]
Fixed on the next update.
