### ISSUE TITLE
Online database

### ISSUE THREAD

**Issue by cyaohiri** [slowtorta/turtlewow-bug-tracker#2938]
Here's a list of issues I've found on our online database. I'm aware of the pinned issue #1438, but since it was closed, it seems more appropriate to post a new one, rather than adding more in the comments.

1. Searching with a leading or trailing spaces yields no results as the spaces don't get stripped before submitting the query. Cf. https://classicdb.ch
3. Sorting quests by "Level" sorts the levels alphabetically instead of numerically (https://database.turtle-wow.org/?quests#0+2+3+1).
Note that sorting by "Required level" sorts them numerically.
4. Quests listed under a faction page, e.g. Darnassus (https://database.turtle-wow.org/?faction=69) do not contain quest IDs, thus the links to quests don't work.
5. Faction pages, e.g. Darnassus (https://database.turtle-wow.org/?faction=69) do not have a "Members" tab, cf. https://classicdb.ch/?faction=69
6. Razorfen Kraul (https://database.turtle-wow.org/?quests=2.491) doesn't show quests as it uses zone ID 491 instead of 1717, i.e. the URL should be https://database.turtle-wow.org/?quests=2.1717 instead.
7. Broken anchor tags on quest pages, e.g. https://database.turtle-wow.org/?quest=2499.
The anchor tags for the items listed at the top, as well as for the faction reputation reward at the bottom are set to "ahref" instead of "a href", making neither of them into hyperlinks.
8. Quest items are shown on the last page, e.g. Red Linen Bandana in https://database.turtle-wow.org/?npc=116, cf. https://classicdb.ch/?npc=116
10. It's not possible to submit a query with fewer than four characters. Cf. https://classicdb.ch/?search=1.
However, manually changing the URL does work sometimes, e.g. https://database.turtle-wow.org/?search=fox does yield results.

**Comment by slowtorta** [comment]
Moving this to the internal bug tracker. Thank you for putting this list together but te online DB and forum issues is the lowest priority, please do not expect them to be fixed any time soon.
