### ISSUE TITLE
Viewing Chieftain's Ceremonial Mantle in the dressing room crashes the game.

### ISSUE THREAD

**Issue by SierraNairn** [slowtorta/turtlewow-bug-tracker#294]
Viewing Chieftain's Ceremonial Mantle in the dressing room crashes the game.
Lansa Skyseer  sells two copy of the same items but with different item id.
https://database.turtle-wow.org/?npc=80948 Lansa Skyseer 
https://database.turtle-wow.org/?item=80099  Chieftain's Ceremonial Mantle
https://database.turtle-wow.org/?item=81167 Chieftain's Ceremonial Mantle
Trying to view both of them in the dressing room crashes the game.

![WoW_XYqyLG9JqG](https://user-images.githubusercontent.com/83077166/132985146-fc43e00f-7e45-41d1-87ff-b331cb6d5f3d.png)

![WoW_SGxcCYzXNG](https://user-images.githubusercontent.com/83077166/132985148-bbebd088-130a-480d-9fe3-e6f899a0aab8.png)

**Comment by slowtorta** [comment]
Deleted items from the game for now to prevent abuse.
