### ISSUE TITLE
Certain Mounts Unusable in Stormwind

### ISSUE THREAD

**Issue by Euphemistic** [slowtorta/turtlewow-bug-tracker#2940]
Certain mounts are unable to be used while you are standing in Stormwind, and running into Stormwind while mounted on them will dismount you as if you entered a building. Currently my Red Pounder does not work, and I have heard the Bronze Drake also does not. The Riding Turtle and Swift Horde Wolf that I bought off the shop still work however. Not sure how many mounts do not work.

**Comment by cyaohiri** [comment]
This is intended. https://discord.com/channels/466622455805378571/691438750185553950/1081873149420904498

**Comment by slowtorta** [comment]
This is intended. Some mount models are too big to the crowded places and it's disturbing other players. Please ride something more compact while you're galloring through a trade district :p
