### ISSUE TITLE
Spell: Repair the Blade of Heroes

### ISSUE THREAD

**Issue by cyaohiri** [slowtorta/turtlewow-bug-tracker#2948]
There is a space before a comma in the text of [Repair the Blade of Heroes](https://database.turtle-wow.org/?spell=11923).
"...Strong Flux , 2 Elemental Fire..."

Item: https://database.turtle-wow.org/?item=9719

**Comment by slowtorta** [comment]
Spell descriptions are client-side. Fixed in 1.16.6
