### ISSUE TITLE
NPC: Sewer Beast

### ISSUE THREAD

**Issue by cyaohiri** [slowtorta/turtlewow-bug-tracker#2955]
It seems like [Sewer Beast](https://database.turtle-wow.org/?npc=3581) cannot be skinned, though I have not tested this.

NPC: https://database.turtle-wow.org/?npc=3581

**Comment by Zeyla-TW** [comment]
Cannot reproduce, I was able to skin Sewer Beast at 250+ skinning with no issues.

**Comment by cyaohiri** [comment]
In that case, only the online database should be updated.
