### ISSUE TITLE
NPC minions

### ISSUE THREAD

**Issue by cyaohiri** [slowtorta/turtlewow-bug-tracker#2956]
Killing NPC minions (Imps, Voidwalkers, etc.) grants experience, but doesn't trigger on-kill effects such as [Remorseless Attacks](https://database.turtle-wow.org/?spell=14144), [Spirit Tap](https://database.turtle-wow.org/?spell=15270), and possibly others.

**Comment by slowtorta** [comment]
Death of minions doesn't proc such effects. Please re-open if you find a proof that it should :)

**Comment by cyaohiri** [comment]
If minions didn't grant experience on kill, it would make sense. but even in classic they do. Seems like this inconsistently is from vanilla.

**Comment by slowtorta** [comment]
Can you provide some log or a video?

**Comment by cyaohiri** [comment]
What I meant was that they indeed do not proc on-kill effects as far as I know, even though they do grant experience on kill, which is why it looks like an oversight (in vanilla). Seems like they should either grant no experience, and thus not proc it, or grant experience and proc it.

**Comment by Zeyla-TW** [comment]
Can you please provide specific NPC references, or possibly database links to them? Not all minions behave identically so it helps to have specific examples.

**Comment by cyaohiri** [comment]
Sure, [Wastewander Shadow Mage](https://database.turtle-wow.org/?npc=5617)'s Voidwalker Minions, or [Dark Strand Cultist](https://database.turtle-wow.org/?npc=3725)'s Imp Minions. This is probably how all minions behave.

**Comment by Zeyla-TW** [comment]
After digging through multiple classic wow videos, I've confirmed that the Voidwalker Minions in Tanaris that are pets to the Wastewander Shadow Mages do grants XP on death but do not trigger on-kill effects in classic. Therefor, this is working as intended.

**Comment by cyaohiri** [comment]
Yes, I've confirmed that in my previous messages, and have then said it's an inconsistency, and that it's from vanilla.

> What I meant was that they indeed do not proc on-kill effects as far as I know, even though they do grant experience on kill, which is why it looks like an oversight (in vanilla). Seems like they should either grant no experience, and thus not proc it, or grant experience and proc it.

Sorry if that was unclear.

**Comment by twowTurtReynolds** [comment]
A user brought this up and evidence from Classic 2021 and 2023-HC was brought up. Do we have evidence from 2006 that says the contrary as this could possibly be a classic bug?

https://youtu.be/NzviHxxpINA?t=443
https://youtu.be/lNy2ohTWeLw?t=303

I have confirmed Turtle matches latest vmangos behavior.
