### ISSUE TITLE
Yetis and Pick Pocket

### ISSUE THREAD

**Issue by cyaohiri** [slowtorta/turtlewow-bug-tracker#2957]
Yetis can be pickpocketed, which doesn't seem correct.

https://database.turtle-wow.org/?search=yeti#npcs

**Comment by slowtorta** [comment]
Yeti got one pocket and you don't want to stick your hand into it.

I couldn't find verify this via Classic Wowhead, nor in other Blizzlike server DBs such as cmangos and vmangos.
