### ISSUE TITLE
The gossip text for Strange Fruited Plants is wrong

### ISSUE THREAD

**Issue by Tinyfin-github** [slowtorta/turtlewow-bug-tracker#296]
The gossip text for Strange Fruited Plants is wrong

![WoW_hG0XIeAZye](https://user-images.githubusercontent.com/83077166/132998255-d825bda4-6d96-458f-8648-977849218b69.png)

The correct gossip text should be: This plant stands out among the normal flora of Teldrassil, and emits a strange, purplish glow."
https://database.turtle-wow.org/?object=6751 Object Strange Fruited Plant
https://database.turtle-wow.org/?quest=930  Quest The Glowing Fruit

**Comment by slowtorta** [comment]
Thanks for reporting it. It'll be fixed on the next server restart. Make sure to clear your WDB folder.
