### ISSUE TITLE
Can not turn in "The Sleeper Has Awakened" Escort Quest in Darkshore

### ISSUE THREAD

**Issue by Nightdawg** [slowtorta/turtlewow-bug-tracker#2960]
**Please, provide a clear description what the bug is:**
Kerlonian Evershade, the escort NPC of the the "The Sleeper Has Awakened" escort quest, shapeshifts from bear form to humanoid the moment you start the quest, which prevents us from finishing the quest once we reach the end of the route.

**Steps to reproduce the behavior with as much detail as possible:**

1. In Darkshore, start the "The Sleeper Has Awakened" escort quest
2. Observe the NPC shapeshift into humanoid form
3. When you reach the end of the route, the quest will not finish

**IDs of affected creatures, items, quests or spells with a link to the relevant page:**

NPC: https://database.turtle-wow.org/?npc=11218
Quest: https://database.turtle-wow.org/?quest=5321

**Expected behavior. Describe how it should work:**
Kerlonian Evershade should not shapeshift into humanoid form. We were able to complete this quest 3-4 weeks ago multiple times, and he was not changing forms at the start of the quest. I suspect this to be the reason this quest bugs out.

**Comment by MBJ89** [comment]
Same problem :)

**Comment by slowtorta** [comment]
Should be fixed on the next update.
