### ISSUE TITLE
Pounder mounts are unmountable in certain normally-mountable areas

### ISSUE THREAD

**Issue by Rangtuk** [slowtorta/turtlewow-bug-tracker#2961]
**Please, provide a clear description what the bug is:**
 Black Pounder mount (and presumably other Pounder variations) are unmountable in certain areas.
**Steps to reproduce the behavior with as much detail as possible:**

1. Go to Orgrimmar
2. Try to mount onto your Reinforced Black Pounder
3. Cry when you are given an 'unable to mount here' error
4. Mount onto another mount (turtle, reindeer, rocket car) and have it succeed in the same place

**IDs of affected creatures, items, quests or spells with a link to the relevant page:**

Item: https://database.turtle-wow.org/?item=81250

**Expected behavior. Describe how it should work:**
A mount's a mount, if this just trying to force people to be unable to be enormous on mech-type mounts theres a number of other large mounts to choose from and this is just making life unnecessarily annoying

**Comment by ratkosrb** [comment]
This is an intentional change, and not a bug.
