### ISSUE TITLE
ostalrius is always up?

### ISSUE THREAD

**Issue by geojak** [slowtorta/turtlewow-bug-tracker#2962]
**Please, provide a clear description what the bug is:**

so we killed ostarius today in a pug
tabc showed up later and gireved us at 10% but boss still died, but that isnt the point if the ticket 
the bug is, that tabc then proceeded to do the boss aswell... 

**Expected behavior. Describe how it should work:**

world boss can be killed once then respawn
not summon as many times as you like? or is it a feature?

**Comment by Lexiebean** [comment]
It's a summonable boss from the end of a quest chain
