### ISSUE TITLE
Stable slot is bugged

### ISSUE THREAD

**Issue by AnoosLord1** [slowtorta/turtlewow-bug-tracker#2964]
**Please, provide a clear description what the bug is:**
So i was one of the people who had the ogre pet, and i think in one of the updates it was removed while it was still in my stable, and now i cant use that slot.
**Steps to reproduce the behavior with as much detail as possible:**
Not sure how to reproduce the bug
1.
2. 
3. 

**IDs of affected creatures, items, quests or spells with a link to the relevant page:**
i dont remember the name of it so not sure what to put here
NPC: https://database.turtle-wow.org/?npc=
Item: https://database.turtle-wow.org/?item=
Quest: https://database.turtle-wow.org/?quest=
Spell: https://database.turtle-wow.org/?spell=
Object: https://database.turtle-wow.org/?object=

**Expected behavior. Describe how it should work:**
not sure how it should work

**Comment by Gurky-Turtle** [comment]
@AnoosLord1 make an in-game ticket so a GM can fix it for you.
