### ISSUE TITLE
Chat controls out of position on login

### ISSUE THREAD

**Issue by jtkimbell** [slowtorta/turtlewow-bug-tracker#2965]
**Please, provide a clear description what the bug is:**
When logging into the game, my chat box and controls are always messed up, with the buttons overlapping and the chat pane empty. Only clicking on "General" fixes the issue.

**Steps to reproduce the behavior with as much detail as possible:**

1. Log into any character (account 'studbucket')
2. Notice that the "chat bubble" button is not in the correct place, it is either to the left of or on top of the arrows
3. Notice that the chat window is empty regardless of which tab is focused on. It could be "General" or a custom tab I made (such as "Whisper"), it's always empty.
4. Clicking the "General" tab fixes the issue and the alignment is fixed and chat behaves normally.

This has been the case for me ever since I installed TWoW 8 months ago.

Screenshot for steps 2+3 (example of issue on 2 different characters)
![image](https://user-images.githubusercontent.com/44843397/223253203-aa38a05c-38ee-4cff-a95d-76245f41b09a.png)

Screenshot for step 4 (fixed)
![image](https://user-images.githubusercontent.com/44843397/223254457-53a62d5f-e1c1-467d-a293-dbd829f47622.png)

**IDs of affected creatures, items, quests or spells with a link to the relevant page:**

N/A

**Expected behavior. Describe how it should work:**

When loading the game the chat buttons are in the correct place and my chat window is populated.

**Comment by Gurky-Turtle** [comment]
@jtkimbell This most likely was caused by an addon, the fix will be to quit wow delete your wtf folder and reopen wow and log in, keep in mind you will need to redo all of your settings.
