### ISSUE TITLE
Issue with Breaking the Felstar

### ISSUE THREAD

**Issue by Shephield** [slowtorta/turtlewow-bug-tracker#2969]
**Please, provide a clear description what the bug is:**

Scripted spawn of NPCs to help with an elite quest mob isn't occurring.

**Steps to reproduce the behavior with as much detail as possible:**

1. Start the quest by activating the corrupted felstone.
2. Kill the mobs wave by wave.
3. Dra'lox Felstar will then spawn; however the rangers won't spawn to help you with the elite.

**IDs of affected creatures, items, quests or spells with a link to the relevant page:**

NPC: https://database.turtle-wow.org/?npc=60425
Item: https://database.turtle-wow.org/?item=60148
Quest: https://database.turtle-wow.org/?quest=40377
Object: https://database.turtle-wow.org/?object=2010883

**Expected behavior. Describe how it should work:**

After the wave event; as listed in the quest description, rangers are supposed to spawn and help with the elite NPC.

**Comment by slowtorta** [comment]
Should be fixed in the next update.
