### ISSUE TITLE
Revantusk Mystic's Robe shows no durability

### ISSUE THREAD

**Issue by Tinyfin-github** [slowtorta/turtlewow-bug-tracker#297]
Revantusk Mystic's Robe shows no durability

![image](https://user-images.githubusercontent.com/83077166/133024377-40789de9-785d-487f-aeb1-6a8ad33d2997.png)

https://database.turtle-wow.org/?item=80612 - Revantusk Mystic\'s Robe

**Comment by slowtorta** [comment]
Thanks for reporting it. It'll be fixed on the next server restart. Make sure to clear your WDB folder.
