### ISSUE TITLE
BUG - Life Tap not showing correct stats

### ISSUE THREAD

**Issue by rhogar83** [slowtorta/turtlewow-bug-tracker#2970]
**Please, provide a clear description what the bug is:**

When talents for improved life tap have points in them, life tap doesn't reflect the correct stats. 

![Impoved-LifeTap](https://user-images.githubusercontent.com/51790520/223594668-60f1dcd3-408d-4fc0-a72b-56906c28e839.jpg)

**Steps to reproduce the behavior with as much detail as possible:**

1. Learn Life Tap as a warlock
2. Put talents in Improved Life Tap
3. 
**IDs of affected creatures, items, quests or spells with a link to the relevant page:**

https://database.turtle-wow.org/?spell=1454
https://database.turtle-wow.org/?spell=1455
https://database.turtle-wow.org/?spell=18182
https://database.turtle-wow.org/?spell=18183

**Expected behavior. Describe how it should work:**

**Comment by rhogar83** [comment]
It should be reporting that I am getting extra mana in return of life but it does not.

**Comment by balakethelock** [comment]
Not a bug with lifetap but a natural thing in vanilla client. Talents that buff a spell don't change the tooltip of the spell but they still work. You can turn on mana generation in combat text and see that it works.
