### ISSUE TITLE
Soul Shard Refund When Not Supposed to?

### ISSUE THREAD

**Issue by NelSeeker** [slowtorta/turtlewow-bug-tracker#2972]
**Please, provide a clear description what the bug is:**
Soul Shards are being refunded when summoned Voidwalker or Player dies during combat.

**Steps to reproduce the behavior with as much detail as possible:**

Not much to go on here. Tested it either way and refund seems to happen regardless, ei I die, it dies, or we both die. I was confused why my bag was filling up with Soul Shards when I would "replenish" them after combat. Found out when I stared at an empty slot in my bag when the Voidwalker perished. Note that it takes a few seconds after it dies, but not sure if the delay is significant.

**IDs of affected creatures, items, quests or spells with a link to the relevant page:**

https://database.turtle-wow.org/?spell=697
https://database.turtle-wow.org/?npc=5676
https://database.turtle-wow.org/?item=6265#reagent-for

**Expected behavior. Describe how it should work:**
https://wowpedia.fandom.com/wiki/Soul_Shard_(item)#:~:text=Soul%20Shards%20may%20be%20refunded,Zoning%20under%20certain%20circumstances.

As described under notes, Soul Shards are only refunded under specific circumstances, ie. not to be refunded under death of either the summon or player. I assume specific considerations are made like dismissing or flight rentals/blimp rides, so unsure if this is intended to make leveling a little easier or an unintended bug.

**Comment by balakethelock** [comment]
Can't reproduce, were you in a battleground when that happened?

**Comment by NelSeeker** [comment]
Currently in the Silverpine Forest. Tested with multiple mobs here just doing normal questing. You think my character is bugged itself?

**Comment by NelSeeker** [comment]
Seemed to have stopped out of nowhere. Unsure why, but I've leveled since then and have done content outside the Silverpine Forest.
