### ISSUE TITLE
ZF Trash BoE Drops Only From Bosses

### ISSUE THREAD

**Issue by redmagejoe** [slowtorta/turtlewow-bug-tracker#2974]
https://database.turtle-wow.org/?item=9484 is clearly intended to be a trash drop, but currently only drops off of bosses, likely due to the level range tiering that may have even been an issue on vanilla. Suggest placing this in the loot table for all existing Zul'Farrak mobs.

**Comment by slowtorta** [comment]
Those pants are known to be one of the rarest drops in the game, why break the legend? At least let's reserve it for some newer dungeons, instead of adding it to ZG... @Dragunovi
