### ISSUE TITLE
Bugs: When mage casts blink in the water and air, it will blink to wrong place.

### ISSUE THREAD

**Issue by Nilyang404** [slowtorta/turtlewow-bug-tracker#2975]
**Please, provide a clear description what the bug is:**

**Steps to reproduce the behavior with as much detail as possible:**

1.When a mage casts the blink in the water, it will move to the bottom of the water instead of the front.  I have never seen any thing like this in other servers , SoI think this is bug, because it will blink to the front of  character  in wow classic
2.When blink in the air, it will blink to the head of the character rather than the front of  character.(it's like you jump down from 50 yrd hight , and blink at 10 yrd hight , then you will go to the 20yrd and continue to fall. )

**IDs of affected creatures, items, quests or spells with a link to the relevant page:**

NPC: https://database.turtle-wow.org/?npc=
Item: https://database.turtle-wow.org/?item=
Quest: https://database.turtle-wow.org/?quest=
Spell: https://database.turtle-wow.org/?spell=
Object: https://database.turtle-wow.org/?object=

**Expected behavior. Describe how it should work:**
1.blink to the front of  the character 
2.blink to the  front of  the character  at the same hight

**Comment by cyaohiri** [comment]
Furthermore, blinking above above an underground room can place you underground, and then you will continue to fall into the underground room.

**Comment by Muigin** [comment]
Cannot reproduce on current version. Water blinking works correctly, and air blinking works as intended.
