### ISSUE TITLE
Naxx trash droprates not blizzlike too high

### ISSUE THREAD

**Issue by geojak** [slowtorta/turtlewow-bug-tracker#2977]
**Please, provide a clear description what the bug is:**

In this forum post
https://forum.turtle-wow.org/viewtopic.php?f=14&t=5908
it was pointed out that naxx trash droprates are 2-3x higher than normal blizzlike and what harmfull effect this can have on the server making naxx trash farming so easy and rewarding

the following 2 weapons are the most impactfull naxx trash items

wowhead
https://www.wowhead.com/classic/item=23221/misplaced-servo-arm
twow
https://database.turtle-wow.org/?item=23221

wowhead
https://www.wowhead.com/classic/item=23044/harbinger-of-doom
twow
https://database.turtle-wow.org/?item=23044

here you can see all the remianing naxx trash drop in this mobs loottable
https://database.turtle-wow.org/?npc=16165#drop:0-2-12+1

this is the same mob on wow classic with overally significant lower droprates
https://www.wowhead.com/classic/npc=16165/necro-knight#drops;mode:40player;0-3+17-21+1

**Comment by suggney** [comment]
believe this was intended. why do you hate fun?

**Comment by geojak** [comment]
If its intended, then thy can just close, the issue, no problem. Why do yuu think I hate fun? I don't see the connection. I like challenging games and hate when the game gifts out stuff too easily making it feel unearned and unrewarding.

I give you an extreme example. Let's say tf binding drop rates Was 10x higher on twow than normal. Of course you would say oh so fuuun. But a lctually you just made getting thunderfurry 10 times less rewarding and all other weapons in the game meaningless at the same time.

Things like the these just need to reviewed, to make sure it's is actually intended and not just a bug. That's all

**Comment by balakethelock** [comment]
Geojak the difference is that thunderfury you get one chance per week to drop a binding, naxx trash can be farmed infinitely. Higher drop rate will simply mean more expensive drops. As long as those weapons exist, people will still want them and will still pay mages as much as they can to get it.

**Comment by geojak** [comment]
Let the devs decide, I am just raising attention to an not blizzlike situation. They can keep it or change it, I don't really, care

**Comment by ConcernedTurtler** [comment]
You know this guy got his misplaced servo arm before reporting. Kicking away the ladder.

**Comment by nerasw** [comment]
if it's bug - it should be reported. Opening issue is the only way one can report it. He did it. What's the problem? You against the bugfix? Say it. Why trashtalk?
BTW i'm hc-only player so i dont give a !@#$ about naxx, but game should be healthy for all players.

**Comment by fatnerdynerd** [comment]
I'd like to speak on behalf of the whole server when I write this: Geojak has done no endgame content on this server and he is doing nothing except browse guild discords and request anything thats even remotely fun/brings an advantage to be nerfed or fixed or removed. And therefor I'd like to request his permanent blacklist from any and all Turtlewow related discussion and forums and alike. He serves zero purpose and all his comments and bug reports are juvenile attempts at harming the server and it's users. He has done more to kill this server than any other player or personel on this server and I can vouch for hundreds of other players that his disposal from here would bring joy and celebration, nothing else.

**Comment by afizzler** [comment]
> I'd like to speak on behalf of the whole server when I write this: Geojak has done no endgame content on this server and he is doing nothing except browse guild discords and request anything thats even remotely fun/brings an advantage to be nerfed or fixed or removed. And therefor I'd like to request his permanent blacklist from any and all Turtlewow related discussion and forums and alike. He serves zero purpose and all his comments and bug reports are juvenile attempts at harming the server and it's users. He has done more to kill this server than any other player or personel on this server and I can vouch for hundreds of other players that his disposal from here would bring joy and celebration, nothing else.

Pretty much that is his intent since day 1.

**Comment by vkekd** [comment]
This feels more like a suggestion rather than a bug report but i agree that naxx trash farms should be something that needs to be change in favor of a better weapon progresion. 
Currently you hit 60, form a naxx trash group and you get your bis weapons + chest until KT weapons (Gressil + THC).
If you want the current weapons from past tiers + the incoming ones from karazhan and emerald sanctum to stay relevant, this needs to be changed.

**Comment by Zebouski** [comment]
> This feels more like a suggestion rather than a bug report but i agree that naxx trash farms should be something that needs to be change in favor of a better weapon progresion. Currently you hit 60, form a naxx trash group and you get your bis weapons + chest until KT weapons (Gressil + THC). If you want the current weapons from past tiers + the incoming ones from karazhan and emerald sanctum to stay relevant, this needs to be changed.

The OP post here is not a suggestion, its a proper bug report as this is a deviation from blizzlike and severely hurts the game.

**Comment by Gurky-Turtle** [comment]
This will need to sit a while, I went through Wowhead and a lot of the information there is not accurate between the item page and the NPC page. 

for example https://www.wowhead.com/classic/npc=16448/plagued-deathhound
https://www.wowhead.com/classic/item=23044/harbinger-of-doom

item page says plagued deathhound is 0.9 but you then go to the plagued deathhound's page and it's not on its drop list. 

Also, a ton of the trash claims it drops t3 tokens which is not correct. 

I would take Naxx data from Wowhead with a grain of salt.
