### ISSUE TITLE
Quest The Sleeper has Awakened - totaly broken

### ISSUE THREAD

**Issue by pristn** [slowtorta/turtlewow-bug-tracker#2978]
Quest The Sleeper has Awakened - totaly broken

1. The quest does not count when you arrive at the quest turn-in point.
2. None of the triggers along the route work.
3. The quest cannot be completed.

![WoWScrnShot_030923_144738](https://user-images.githubusercontent.com/117263498/224015563-3541f2b9-a1e4-4c8f-aa86-bdd17e8b8270.jpg)

https://database.turtle-wow.org/?quest=5321

**Comment by geojak** [comment]
https://github.com/slowtorta/turtlewow-bug-tracker/issues/2960
