### ISSUE TITLE
Splintertree inn does not give rested

### ISSUE THREAD

**Issue by Kangaroux** [slowtorta/turtlewow-bug-tracker#2982]
The inn at Splintertree Post in Ashenvale does not make you rested. I ran around the inn a bit and couldn't find any spots that made me rested.

**Comment by slowtorta** [comment]
![image](https://user-images.githubusercontent.com/66763404/224503907-8dd13d88-6f04-4df9-bad6-6e4dc509ad18.png)
Working as intended.
