### ISSUE TITLE
Chatacter stats buged

### ISSUE THREAD

**Issue by d-u-b** [slowtorta/turtlewow-bug-tracker#2983]
![12345](https://user-images.githubusercontent.com/6154054/224301713-eb016365-1058-46ff-9e0c-7f758842a94a.jpg)
![54321](https://user-images.githubusercontent.com/6154054/224303566-5ee1b14b-f613-4bf3-ac7e-23a6169c3268.jpg)

Hello!
1. Then i equip this shoulders not add set bonus from 2 items
2. My bracers enchanted +12 spd but this is not add spell power
Yesterday all worked good
I tried different ways to fix the bug, cleaned WDB folder, disabled addons, took off and put on things in a different sequence

**Comment by Zebouski** [comment]
This is an xmog bug that ruins the client's ability to see if you have the set bonus or not, its purely visual and the serverside does understand and you actually do get the spellpower bonus.

the +spell dmg in the character sheet, you are seeing is an addon, which is incorrect. you could contact the developer of that addon to see if they can fix their own bug

**Comment by d-u-b** [comment]
Okay, sorry to bother you, no one in the game could explain this to me.
