### ISSUE TITLE
[Reconning] talent doesn't work properly, I tested it in pvp and pve...

### ISSUE THREAD

**Issue by Sauron930** [slowtorta/turtlewow-bug-tracker#2984]
**Please, provide a clear description what the bug is:**

**Steps to reproduce the behavior with as much detail as possible:**

1.
2. 
3. 

**IDs of affected creatures, items, quests or spells with a link to the relevant page:**

NPC: https://database.turtle-wow.org/?npc=
Item: https://database.turtle-wow.org/?item=
Quest: https://database.turtle-wow.org/?quest=
Spell: https://database.turtle-wow.org/?spell=
Object: https://database.turtle-wow.org/?object=

**Expected behavior. Describe how it should work:**

**Comment by Sauron930** [comment]
I tested it in pvp and pve...

**Comment by redmagejoe** [comment]
There is no useful information available in this ticket whatsoever. Please add information or staff will end up closing this ticket.
