### ISSUE TITLE
Ultra-Flash Shadow Reflector does not work on Black Guard Sentry in Stratholme Undead.

### ISSUE THREAD

**Issue by njalsson** [slowtorta/turtlewow-bug-tracker#2986]
**Please, provide a clear description what the bug is:**
The engineering trinket that reflects shadow spells does not reflect damage vs Black Guard Sentry in Stratholme Undead, as the shadow shocks are not reflected you take damage when it can be unexpected, and possibly get 1shot.

**Steps to reproduce the behavior with as much detail as possible:**

1. Equip Ultra-Flash Shadow Reflector
2.  Use it against Black Guard Sentry
3.  It fails

**IDs of affected creatures, items, quests or spells with a link to the relevant page:**

NPC: https://database.turtle-wow.org/?npc=10394
Item: https://database.turtle-wow.org/?item=18639
Spell: https://database.turtle-wow.org/?spell=17439

**Expected behavior. Describe how it should work:**
Ultra-Flash Shadow Reflector should reflect these shadow shocks.

**Comment by twowTurtReynolds** [comment]
![image](https://github.com/slowtorta/turtlewow-bug-tracker/assets/151180101/d38cb959-2414-43ec-9e0e-66177f2dec24)
This seems to be working now.

The damage reflected didnt display in the log, but they took this much damage.
![image](https://github.com/slowtorta/turtlewow-bug-tracker/assets/151180101/21bd3fc4-a9a1-451f-92a1-e89f797e76b7)
