### ISSUE TITLE
Tents dissapear when you hearth or logout

### ISSUE THREAD

**Issue by Zebouski** [slowtorta/turtlewow-bug-tracker#2991]
**Steps to reproduce the behavior with as much detail as possible:**

1. place tent
2. log off
3. see on another character that the tent has dissapeared

**IDs of affected creatures, items, quests or spells with a link to the relevant page:**

Item: https://database.turtle-wow.org/?item=51283

**Expected behavior. Describe how it should work:**
Tents should last their full duration once placed, no matter where the placer goes. This allows higher level incl lv 60 players to feel freer to drop tents, and not be obligated to stand around afk for 20 minutes for no good reason.

**Comment by slowtorta** [comment]
That is the correct behavior. Summoned objects stans as long as the player is online.
