### ISSUE TITLE
Few mobs, low chance of drop in quest The Corrupter

### ISSUE THREAD

**Issue by AKryukov92** [slowtorta/turtlewow-bug-tracker#2994]
Currently quest The Corrupter https://database.turtle-wow.org/?quest=1482
requires you to kill nagas [Slitherblade Oracle](https://database.turtle-wow.org/?npc=4718)
which drop Oracle Crystal with 15% chance
2 mobs on island, 3 in sea. Doesn't look like spawn is shared. I henocided all nagas on the island and Oracles spawn in constant places.

I assume that droprates are being reduced across whole world.
Expected that drop chance should be higher. Probably 50% or 100%

**Comment by slowtorta** [comment]
Sorry, but the chances and the amount of mobs are correct
