### ISSUE TITLE
Low level metals in The Hinterlands

### ISSUE THREAD

**Issue by AKryukov92** [slowtorta/turtlewow-bug-tracker#2995]
Currently there is Iron node found approximately at 0.52382749319077, 0.59622412919998 near it Silvermane Howler of level 45.
more iron at 0.51576846837997, 0.65734475851059 with Vilebranch Scalper of lvl 46 nearby
0.62807166576385, 0.59267663955688 with trolls of 46 lvl nearby
0.62486517429352, 0.59513181447983 with trolls of 46 lvl nearby

Iron Deposit https://database.turtle-wow.org/?object=1735
Mithril Deposit https://database.turtle-wow.org/?object=2040

Expected: Mithril nodes instead of Iron.

**Comment by twowTurtReynolds** [comment]
https://www.wowhead.com/classic/object=1735/iron-deposit Iron in the hinterlands is blizzlike.
