### ISSUE TITLE
Transmogification of the sword set "Warblade of the hakkari" does not work properly

### ISSUE THREAD

**Issue by lyssebabz** [slowtorta/turtlewow-bug-tracker#2997]
**Please, provide a clear description what the bug is:** 
Transmogification of the sword "Warblade of the Hakkari" dosen't work like it should. I want it transmogged in my main hand, but it dosen't allow it. I have both blades

**Steps to reproduce the behavior with as much detail as possible:**

1. Aquire Warblade of the Hakkari for off hand and wield it to get the transmog
2. Aquire a second Warblade of the hakkari, now for the main hand. Already have a better main hand, so i want to transmog my current on into warblade of the hakkari, but it didn't allow me.
3. I unequipped my off hand even, because it kept only transmogging my off hand only, as if my main hand was not there. 
4. try transmogging again without off hand, to see it show my transmogging my off hand picture (https://imgur.com/a/dixgdMJ)

**IDs of affected creatures, items, quests or spells with a link to the relevant page:**

Item: https://database.turtle-wow.org/?item=19866
Item: https://database.turtle-wow.org/?item=19865

**Expected behavior. Describe how it should work:**
It could work in 2 ways i reckon. 
1: It could recognize both weapons as seperate weapons instead of just 1 
2: Allow both off and main hand to be transmogged interchangeably of eachother

**Comment by CosminPOP** [comment]
Working as intended.
Off-hand weapons can be transmogged only to other off-hand weapons due to the nature of their models.


![image](https://user-images.githubusercontent.com/7255825/229039323-7c312e24-f2da-40c2-978d-562de5a8be5a.png)

![image](https://user-images.githubusercontent.com/7255825/229039177-c59998e5-a117-45f7-84d2-754e157847cf.png)

**Comment by lyssebabz** [comment]
I could only see the off hand in the transmogrification window, i have both but I could only transmog off hand

**Comment by CosminPOP** [comment]
What's your main hand weapon ?

**Comment by lyssebabz** [comment]
I have tried with Anubisath Warhammer, Dream's Herald and Brutality blade. They all default to off-hand

**Comment by lyssebabz** [comment]
https://imgur.com/a/Iasxgf5 notice in the first picture how im wearing a shield, then i try to transmogify main hand it just transmog my off hand 
https://imgur.com/a/Iasxgf5

**Comment by CosminPOP** [comment]
they're all one-handed weapons and https://database.turtle-wow.org/?item=19865 hakkari sword is main-handed
one-handed weapons go into one-handed
main-handed weapons go into main-hand
and so on

**Comment by CosminPOP** [comment]
> https://imgur.com/a/Iasxgf5 notice in the first picture how im wearing a shield, then i try to transmogify main hand it just transmog my off hand https://imgur.com/a/Iasxgf5

ignore what the preview whos, the dressing room bugs out on dual wield classes or on some weapons dressing previews

**Comment by lyssebabz** [comment]
ah it works! thanks a lot for clarifying! 

> > https://imgur.com/a/Iasxgf5 notice in the first picture how im wearing a shield, then i try to transmogify main hand it just transmog my off hand https://imgur.com/a/Iasxgf5
> 
> ignore what the preview whos, the dressing room bugs out on dual wield classes or on some weapons dressing previews
