### ISSUE TITLE
Head of Bazil Thredd shouldn't be dropped from goblins in STV

### ISSUE THREAD

**Issue by miamistarz** [slowtorta/turtlewow-bug-tracker#2998]
**Please, provide a clear description what the bug is:**

**Steps to reproduce the behavior with as much detail as possible:**

The issue with loottable for quest item https://database.turtle-wow.org/?item=2926 which can be dropped in dungeon 'The Stockade' from boss (which is correct), but also from [Venture Co. Lumberjack](https://database.turtle-wow.org/?npc=921) in STV.

**IDs of affected creatures, items, quests or spells with a link to the relevant page:**

NPC: https://database.turtle-wow.org/?npc=921
Item: https://database.turtle-wow.org/?item=2926
Quest: https://database.turtle-wow.org/?quest=391

**Expected behavior. Describe how it should work:**
Should be dropped only by boss in dungeon https://database.turtle-wow.org/?npc=1716

**Comment by slowtorta** [comment]
The chances in our DB seem correct. Online DB doesn't display reference drop chances correctly.
