### ISSUE TITLE
High Elf Weapon on Back floating (literally unplayable)

### ISSUE THREAD

**Issue by JvMarchetti** [slowtorta/turtlewow-bug-tracker#30]
By opening this Issue, I admit to having done the pertinent research using sources from Vanilla (preferably) or Classic. I also understand that sources from other private servers are not acceptable.

**Current behavior**: When i use a two-handed weapon, the weapon on the back of my High-Elf is floating. Jokes aside, i think it would very good to polish these models 

**Proofs**:

![Screenshot_1](https://user-images.githubusercontent.com/85771279/121759192-e5256500-cafa-11eb-8906-bc95788e95b6.png)
![Screenshot_2](https://user-images.githubusercontent.com/85771279/121759194-e6569200-cafa-11eb-8f98-0f4b9bd4621b.png)
![Screenshot_3](https://user-images.githubusercontent.com/85771279/121759196-e6ef2880-cafa-11eb-82dd-8d8708b35a63.png)
![Screenshot_4](https://user-images.githubusercontent.com/85771279/121759197-e6ef2880-cafa-11eb-96b7-e2468deb1768.png)

**Steps to reproduce**:

1. You probably know what i'm talking about.

**Comment by slowtorta** [comment]
Thanks for reporting it. This might happen in some very distant client update, those are not happen too often.
