### ISSUE TITLE
Alliance Quest cannot be completed by High Elf

### ISSUE THREAD

**Issue by Sneedsen** [slowtorta/turtlewow-bug-tracker#3002]
High Elves cannot start the Alliance quest, A Foul Effigy, started by using the Foul Effigy item randomly dropped by Satyr in Satyrnaar in Ashenvale. Attempting to begin the quest outputs the following message in chat, "That quest is not available to your race". I can only imagine this is unintended as the turtle database shows the quest being completable for all other Alliance races.

Quest: https://database.turtle-wow.org/?quest=40797
Item to start the quest: https://database.turtle-wow.org/?item=61153

**Comment by slowtorta** [comment]
Fixed on the next update.
