### ISSUE TITLE
Hakkari Breastplate and Hakkari Shroud

### ISSUE THREAD

**Issue by RandomXD** [slowtorta/turtlewow-bug-tracker#3003]
**Please, provide a clear description what the bug is:**
Initially I made a ticket about this but I got a mail asking me to post it on the bugtracker. There are ppl at level 19 with Hakkari Breastplate and Hakkari Shroud items which were once available for low level ppl to get from Sunken Temple due to a bug from what I understood from other ppl. The items cannot be obtained anymore but the ppl that got them at that time still kept them, seen them on Nexor 19 gnome rogue. Should those still be kept by those that got them at low lvl or should they be removed?
**Steps to reproduce the behavior with as much detail as possible:**

1.
2. 
3. 

**IDs of affected creatures, items, quests or spells with a link to the relevant page:**

NPC: https://database.turtle-wow.org/?npc=
Item: https://database.turtle-wow.org/?item=
Quest: https://database.turtle-wow.org/?quest=
Spell: https://database.turtle-wow.org/?spell=
Object: https://database.turtle-wow.org/?object=

**Expected behavior. Describe how it should work:**

**Comment by cyaohiri** [comment]
These items have a very small chance to drop from [Steel Lockboxes](https://database.turtle-wow.org/?item=4637). It existed in vanilla, and is probably an oversight.

**Comment by RandomXD** [comment]
I see, I checked a random vanilla database and it shows there aswell.

**Comment by slowtorta** [comment]
The items were removed from those lockboxes in our version of the game.
