### ISSUE TITLE
Queueing BG to skip flight travel

### ISSUE THREAD

**Issue by RandomXD** [slowtorta/turtlewow-bug-tracker#3004]
**Please, provide a clear description what the bug is:**
If you queue for a BG then start flying, enter the BG while on flight and then leave the BG you will be ported to the destination and skip the whole flight, this is used often and can screw up numbers in a BG due to ppl entering and leaving instantly just to skip flight time.
**Steps to reproduce the behavior with as much detail as possible:**

1.  Queue for a BG and wait for it to pop
2.  Start flying to wherever you wanna go then enter the BG
3.  Leave the BG and you're at the destination

**IDs of affected creatures, items, quests or spells with a link to the relevant page:**

NPC: https://database.turtle-wow.org/?npc=
Item: https://database.turtle-wow.org/?item=
Quest: https://database.turtle-wow.org/?quest=
Spell: https://database.turtle-wow.org/?spell=
Object: https://database.turtle-wow.org/?object=

**Expected behavior. Describe how it should work:**

**Comment by redmagejoe** [comment]
This no longer happens. The flight instead drops you wherever you were midflight when you leave the BG.

Ticket can be closed.
