### ISSUE TITLE
Missing NPC

### ISSUE THREAD

**Issue by xASIVx** [slowtorta/turtlewow-bug-tracker#3005]
**Please, provide a clear description what the bug is:**
The NPC "Apothecary Staffron Lerent" is missing

**Steps to reproduce the behavior with as much detail as possible:**
1.travel to Alterac Mountains, coordinate 90/76 
2. witness lack of NPC and cauldron prop 

**IDs of affected creatures, items, quests or spells with a link to the relevant page:**
NPC: https://database.turtle-wow.org/?npc=16107
Quest: https://database.turtle-wow.org/?quest=9028

**Expected behavior. Describe how it should work:**
The NPC should exist in game at the given location so players can proceed with their quest

**Comment by cyaohiri** [comment]
He's there only during the "Love is in the Air" event.

**Comment by xASIVx** [comment]
ah okay thanks nevermind then
