### ISSUE TITLE
Taking a flight path does not unflag for pvp

### ISSUE THREAD

**Issue by aglock363** [slowtorta/turtlewow-bug-tracker#3013]
Taking a flight path does not unflag your character for PvP. This is different than on Classic wow and many other private servers,

Steps to reproduce

1. flag for pvp with /pvp, then type /pvp again to begin the 5 minute deflag timer
2. take a flight path
3. note you are still flagged on the flight path

expected behavior
On other servers, entering a flight path instantly unflags you for pvp, even on a PvP realm. You would only reflag if you landed in a pvp zone on a pvp realm.

**Comment by Frechfuchs** [comment]
https://wowpedia.fandom.com/wiki/PvP_flag#Bringing_down_your_flag

It states here it should behave like you described, but only if you fly into a friendly territory. 
Did you test with flying into a friendly territory?

**Comment by Muigin** [comment]
Can confirm that this is not behaving as intended.

**Comment by balakethelock** [comment]
https://wowpedia.fandom.com/wiki/Patch_1.6.0#:~:text=The%20PvP%20flag%20is%20no%20longer%20cleared%20when%20you%20take%20a%20flight%2C%20if%20you%20have%20/pvp%20toggled%20on.
are you sure?
