### ISSUE TITLE
Danonzo's Tel'Abim Surprise level requirment

### ISSUE THREAD

**Issue by Jeradooka** [slowtorta/turtlewow-bug-tracker#3014]
**Please, provide a clear description what the bug is:**
The Ranged Attack Power bananas (Danonzo's Tel'Abim Surprise) don't show the level requirement on them in the tooltip.

**Steps to reproduce the behavior with as much detail as possible:**

1. Search "Tel'Abim" in the auction house.
2. Compare the Tel'Abim Surprise's tooltip to the others.

**IDs of affected creatures, items, quests or spells with a link to the relevant page:**

Danonzo's Tel'Abim Surprise: https://database.turtle-wow.org/?item=60976

**Expected behavior. Describe how it should work:**
I would expect to see that it requires level 55, like the others.

**Comment by Jeradooka** [comment]
![image](https://user-images.githubusercontent.com/41565304/224854294-6006f5d7-a2d8-419a-84ea-f6185cfc7cdb.png)

**Comment by Jeradooka** [comment]
![image](https://user-images.githubusercontent.com/41565304/224854549-59771dde-75bd-4e9b-ad98-0f49a10af284.png)

**Comment by TWShang** [comment]
Hello there, this issue is already fixed, please make sure you delete your WDB folder, it removes cached information on the client such as item text/data.
