### ISSUE TITLE
Hardwood Cudgel

### ISSUE THREAD

**Issue by Ragnarockin** [slowtorta/turtlewow-bug-tracker#3017]
**Please, provide a clear description what the bug is:**
After completing the quest Mathystra Relics and choosing Hardwood Cudgel, receiving reward and equipping, Hardwood Cudgel has no sheathed texture or mesh. It does not appear on character.

**Steps to reproduce the behavior with as much detail as possible:**

1. Equip Hardwood Cudgel after completion of Mathystra Relics.
2. Sheath and unsheathe weapons. Hardwood Cudgel will be missing its sheath texture and mesh.

**IDs of affected creatures, items, quests or spells with a link to the relevant page:**

NPC: https://database.turtle-wow.org/?npc=3616
Item: https://database.turtle-wow.org/?item=5757
Quest: https://database.turtle-wow.org/?quest=951

**Expected behavior. Describe how it should work:**

Weapon should appear on hip of character when sheathed.

**Comment by Muigin** [comment]
This is a Blizzard item which is behaving precisely how it did in retail. The Client and 3D Devs have stated they have no intention of deconstructing and retooling Blizzard's existing item models.

Won't fix.
