### ISSUE TITLE
Симон Совратительница

### ISSUE THREAD

**Issue by DemonDept** [slowtorta/turtlewow-bug-tracker#3018]
Доброго времени суток. У меня возникла проблема с выполнением классового квеста на Охотника, а именно! Симон Совратительница - когда я её призываю и начинаю бой, я их с питомцем виду по кругу озера( водил и по прямой линии). Обоих постоянно контролю и агрю , но бывает моменты когда они или в середине боя или в начале боя просто убегают от меня и начинают носиться по всей локации Унгора. Спустя 1-2 мин появляться на том месте где я их призвал. Так же возникает проблема с убийством самой Симон Совратительница т.к. после убийства пета, она просто наносит 1 дамаг и снова убегает. И таких проблем много: могут убегать в начале боя да же если между ними и мной расстояние 30-45 ярдов. Могут убежать если между мной и Боссом пройдет(пролетит) мировой моб. Могут убежать если на ландшафте где происходит бой есть объект. Могут убежать если Симон Совратительница  зашла в озера. Могут просто убежать без ведомой причины. 
  Обоих держу постоянно в агро, обоих контролю, но ничего не выходит. Мой согильдиец смог её убить, но только с 10 раза т.к. 9 предыдущих раз было тоже самое что я описал сверху. На просьбу описать как он это сделал он сказал: Пробуй может в этот раз повезет что бы они от тебя не убежали.
 Что бы не быть голословным, я позвал согильдийцев на бой с Симон Совратительница,  после чего они тоже убедились что Симон Совратительница с питомцем забагованы и надо обратиться в службу поддержки.
 Мне очень сложно сдержать свои эмоции т.к. я уже 15 часов (за двое суток) пытаюсь убить Симон Совратительница, много потрачено ресурсов на бой, но бои заканчиваются тем что от меня убегает Босс по неведомым мне причинам.
 Методики ведения боя выучил уже все наизусть и причин что бы они не работали нет. Помогите решить этот баг с выполнением квеста на голову Симон Совратительница!

**Comment by Herdon** [comment]
What?

**Comment by Haaxor1689** [comment]
https://database.turtle-wow.org/?npc=14533
This mob is supposedly evading unexpectedly.

**Comment by DemonDept** [comment]
> https://database.turtle-wow.org/?npc=14533 Эта толпа якобы неожиданно уклоняется.

Absolutely right!

**Comment by RRamz** [comment]
Сделай мили-билд. С бафами будет полегче, но можно и без них. Возьми пару бытылок и чай. Пета сразу в трапу, когда выйдет примени Magic Dust. За это время убьешь Симону в мили. Кайтить на TurtleWoW непросто, тут исправлены абюзы на поиск пути и т.п.

**Comment by slowtorta** [comment]
https://github.com/slowtorta/turtlewow-bug-tracker/issues/3177

The same report but in English. I'll keep the other one open 😺
