### ISSUE TITLE
+ arcane spell damage

### ISSUE THREAD

**Issue by Leroxit** [slowtorta/turtlewow-bug-tracker#3019]
**Please, provide a clear description what the bug is:**

**Steps to reproduce the behavior with as much detail as possible:**

1. green items with +arcane spell damage
2.  arcane explosions of mage
3.  bonus from items doesnt add to damage

**IDs of affected creatures, items, quests or spells with a link to the relevant page:**

NPC: https://database.turtle-wow.org/?npc=
Item: https://database.turtle-wow.org/?item=
Quest: https://database.turtle-wow.org/?quest=
Spell: https://database.turtle-wow.org/?spell=
Object: https://database.turtle-wow.org/?object=

**Expected behavior. Describe how it should work:**
![image](https://user-images.githubusercontent.com/22352054/225376860-05e952c5-2815-4e98-aaee-90f2c2790b1b.png)
![image](https://user-images.githubusercontent.com/22352054/225376959-ba80137a-a1ba-49e2-a923-142091f0b6a7.png)
![image](https://user-images.githubusercontent.com/22352054/225377179-008776d8-ee1d-47a3-a814-65e9e0474818.png)

**Comment by Sringaram** [comment]
AE receives 14.28% of SP bonus, which is rounded down. In your case you're looking at +1 damage on both the lower and the higher end.

**Comment by Zebouski** [comment]
Sringaram's right, your gear is working correctly.

The fact you aren't seeing the +damage in the Schools tab, is a bug in https://github.com/yutsuku/BetterCharacterStats. go report it there.

The tooltip not updating the damage is blizzlike. If you want tooltips to update effective damage with your gear and spec, install this addon https://github.com/Zebouski/TheoryCraft-Turtle/
