### ISSUE TITLE
Learning the Bright campfire outlight while targeting in NPC did not teach it.

### ISSUE THREAD

**Issue by Tebec** [slowtorta/turtlewow-bug-tracker#302]
**Please, provide a clear description what the bug is:**
I learned the Bright campfire for survival and instead of me learning it the NPC vendor I had targets got the spell learning animation.

**Steps to reproduce the behavior with as much detail as possible:**

1. Target a NPC.
2. Try to learn bright campfire
3. 

**IDs of affected creatures, items, quests or spells with a link to the relevant page:**

Item: https://database.turtle-wow.org/?item=50254

**Expected behavior. Describe how it should work:**
I should learn to make a bright campfire.

**Comment by slowtorta** [comment]
In Patch 1.16 this Outline will become obsolete as you will be able to learn Bright Campfire at the trainer.
