### ISSUE TITLE
[Quests] High elf low level quests not available

### ISSUE THREAD

**Issue by mywebpage-rocks** [slowtorta/turtlewow-bug-tracker#3020]
**Please, provide a clear description what the bug is:**

**Steps to reproduce the behavior with as much detail as possible:**

1. Level up a high elf or any other alliance race to 14. 
2. Go to the farstriders lodge.
3. Try to pick up any quests.

**IDs of affected creatures, items, quests or spells with a link to the relevant page:**

There are no quests available for any alliance race at farstriders lodge if character level is higher than 14. Possibly no quests of high elves are available to any other race at lvl 1.

**Expected behavior. Describe how it should work:**

These quests - just as the quests in Teldrassi/Elwynn Forest/Dun Morogh - should be available to any level/alliance race without any requirement (besides min lvl for some quests.

<img width="1901" alt="no-quests-in-fs-lodge" src="https://user-images.githubusercontent.com/52109141/225403974-8e4f25fb-d29b-4f86-b2e1-26b352d17545.png">

**Comment by slowtorta** [comment]
It's correct. The quest are for the high elves alone.
