### ISSUE TITLE
Demons in Whispering Gorge suddenly immune to enslavement

### ISSUE THREAD

**Issue by Ampeva** [slowtorta/turtlewow-bug-tracker#3021]
**Please, provide a clear description what the bug is:**

**Steps to reproduce the behavior with as much detail as possible:**

1. Go to whispering gorge as a lvl 60 warlock
2.  See if it's possible to enslave one of the elite demons
3. Look for a pop-up: Immune

**IDs of affected creatures, items, quests or spells with a link to the relevant page:**

https://database.turtle-wow.org/?search=hederine#npcs

**Expected behavior. Describe how it should work:**
Before these elite demons were always able to be enslaved, as they should.

**Comment by cyaohiri** [comment]
That was changed in this commit: https://github.com/vmangos/core/commit/f8a50e33edd59b0986205fccda1d3b01ced32bc7

**Comment by cyaohiri** [comment]
Relevant comments: https://github.com/slowtorta/turtlewow-bug-tracker/issues/2989

**Comment by ratkosrb** [comment]
This is not a bug.

**Comment by Doombabe** [comment]
What a lazy PoS response.
