### ISSUE TITLE
Spirit Armor talent doesnt work on Troll

### ISSUE THREAD

**Issue by Alorgg** [slowtorta/turtlewow-bug-tracker#3023]
Talent doesnt work just get  + 10%
i think its just trollrace.

last time i got this message, didnt help:(
"
Please un-equip and re-equip your shield after changing talents in order to update the armor values. This is a known issue with changing talents, and loading into instances/re-logging should also cause the armor update to occur. Due to the nature of the talent swap system and the ease of the talent naturally updating itself through gameplay, this is a very niche and minor issue. If your problem is being caused by something other than this, please address it here and we can re-open this issue."

Thank you in advance

**Comment by Silbotronic** [comment]
You do get the bonus armor, the confusing part is that the extra armor isn't removed when you unequip the shield (only when unequipping other gear).
