### ISSUE TITLE
[Warsong Gulch] Alliance + Horde flag above tunnel disappearing upon drop

### ISSUE THREAD

**Issue by Riverleafs** [slowtorta/turtlewow-bug-tracker#3024]
**Please, provide a clear description what the bug is:**

**Steps to reproduce the behavior with as much detail as possible:**

1. Pick up alliance/horde flag
2. Go above the tunnel on either horde or alliance side in Warsong Gulch
3. Drop the flag above the tunnel and it'll disappear or go inside the tunnel under you.

**IDs of affected creatures, items, quests or spells with a link to the relevant page:**

NPC: https://database.turtle-wow.org/?npc=
Item: https://database.turtle-wow.org/?item=
Quest: https://database.turtle-wow.org/?quest=
Spell: https://database.turtle-wow.org/?spell=
Object: https://database.turtle-wow.org/?object=

**Expected behavior. Describe how it should work:**

The flag should not disappear or go inside the tunnel. It should re-appear right behind you or on top of you when dropping it.

**Comment by Riverleafs** [comment]
![image](https://user-images.githubusercontent.com/108731586/225694905-22a5ef61-cf1e-40d4-a4ef-731299360e67.png)


By above the tunnel I mean the part here marked as tunnel.

**Comment by Muigin** [comment]
Cannot reproduce on current version.
