### ISSUE TITLE
Redoubt talent issues (doesn't appear to stack as talent points are increased).

### ISSUE THREAD

**Issue by hilltopper06** [slowtorta/turtlewow-bug-tracker#3025]
**Please, provide a clear description what the bug is:**

My Prot paladin doesn't appear to benefit from additional points in the Redoubt talent.  The percentages from 1/5 talent points appear to be the same as 5/5.  This results in Redoubt not procing as often, and when it does proc the charges go unused.  Expectation at 5/5 is 10% chance on physical hit taken to gain 30% block chance for 10 seconds or 5 hits.  Actual results at 5/5 indicate 2% chance on physical hit taken to gain 6% block chance.

**Steps to reproduce the behavior with as much detail as possible:**

1.  Take 5/5 talents in redoubt as a shield wearing paladin
2.  Allow a physical mob to attack you
3.  See much less redoubt procs and even fewer uses of the buff when it does proc

**IDs of affected creatures, items, quests or spells with a link to the relevant page:**

NPC: https://database.turtle-wow.org/?npc=
Item: https://database.turtle-wow.org/?item=
Quest: https://database.turtle-wow.org/?quest=
Spell: https://database.turtle-wow.org/?spell=45822
Object: https://database.turtle-wow.org/?object=

**Expected behavior. Describe how it should work:**
Redoubt Rank 5 should be easier to proc and more useful when it does proc.

https://database.turtle-wow.org/?spell=45822 is behaving like https://database.turtle-wow.org/?spell=20127 in my experience, or I am the unluckiest paladin alive.

**Comment by redmagejoe** [comment]
This skill appears to be working as intended with a very high proc chance on my Tankadin.

**Comment by hilltopper06** [comment]
It seems to work properly for me now.  Not sure if it was bugged at low levels, if I was just unlucky, or if a clearing of cache corrected it.  Either way, I am good.
