### ISSUE TITLE
Warrior enter combat when targeting mob and pressing attack without being in range of melee

### ISSUE THREAD

**Issue by blombergniklas** [slowtorta/turtlewow-bug-tracker#3026]
**Please, provide a clear description what the bug is:**

Warrior enter combat when targeting mob and pressing attack without being in range of melee

**Steps to reproduce the behavior with as much detail as possible:**

1. Create a new warrior (mine was a goblin)
2. Target a mob further away than you can melee, press attack
3. Observer combat indicator on portrait indicating you are in combat.

**Expected behavior. Describe how it should work:**
Should be able to enable attack without being put in combat if character is not in range to melee mob.
![Screenshot 2023-03-16 at 20 59 05](https://user-images.githubusercontent.com/1698658/225739050-eb9c446b-d3aa-4d88-b7a2-d2973ac82625.png)
![Screenshot 2023-03-16 at 20 59 14](https://user-images.githubusercontent.com/1698658/225739079-415bcb4a-0599-4daf-b7db-8e16f34c1e63.png)

**Comment by blombergniklas** [comment]
Got charge and tested, can use it. So more an issue with client state(?) then a game mechanic from my testing.

**Comment by balakethelock** [comment]
The unit frame shows when your character's autoattack is on, not when it's in combat. For combat you can use the scrolling combat text in interface options.
