### ISSUE TITLE
[Heart of Wyrmthalak]

### ISSUE THREAD

**Issue by Faxe-the-druid** [slowtorta/turtlewow-bug-tracker#3027]
[Heart of Wyrmthalak] (trinket) works only the first time while equipped and after will not proc by any melee attack. re-equipping it repeats the proc, but again only the first time. After wow-head database it has a 2-3% proc rate. Happy fixing, Faxe the druid.

**Comment by Muigin** [comment]
Cannot reproduce on current version.  Activated twice in 60 seconds while auto-attacking dummy in cat form without ever touching any buttons.
