### ISSUE TITLE
Quest: "Gnoll Bounty" - cannot turn in

### ISSUE THREAD

**Issue by peregrinealpha** [slowtorta/turtlewow-bug-tracker#303]
**Please, provide a clear description what the bug is:**
I am trying to turn in a quest called "Gnoll Bounty" to Supervisor Raelen at Eastvale Logging Camp.  My quest log says "Riverpaw Runt slain: 15/10 (Complete) and Riverpaw Outrunner slain: 10/10 (Complete) but it will not let me turn in the quest.

**Steps to reproduce the behavior with as much detail as possible:**

1. I click on Supervisor Raelen.  She has a gray exclamation mark over her head.  She says "I hope you have some good news for me, Marcos!"
2. The continue button is grayed out.  I cannot turn in the quest.
3. I checked the gnolls and the quest tooltip does not show up for any of them; I have killed a sufficient amount of them.

**IDs of affected creatures, items, quests or spells with a link to the relevant page:**

NPC: https://database.turtle-wow.org/?npc=10616 
Quest:https://database.turtle-wow.org/?quest=60042
Character: Marcos (Human Paladin)

**Expected behavior. Describe how it should work:**
I expected to be able to turn in the quest.  It will not let me Complete the quest to turn it in.

Screenshot:
![Gnoll-Bounty-Turnin](https://user-images.githubusercontent.com/89053238/133539417-00818eb7-4dc6-46c6-93d5-6e2abf3bf946.png)

**Comment by Snufflenose** [comment]
I can confirm this bug.

Riverpaw Runt slain: 15/10 (Complete)
Riverpaw Outrunner slain: 10/10 (Complete)

Quest finished, but I can't turn it in.

**Comment by Snufflenose** [comment]
Update:

I wrote an ingame ticket and the kind GM asked me to delete the WDB folder (I honestly didn't think about that even though you're regularly reminded to do so, duh).

I did and was able to turn in the quest, yay!

**Comment by Snufflenose** [comment]
It's still strange that it says "Riverpaw Runt slain: **15/10** (Complete)"

**Comment by slowtorta** [comment]
This is WDB issue, sorry.
