### ISSUE TITLE
Can't turn in quest

### ISSUE THREAD

**Issue by Danog123** [slowtorta/turtlewow-bug-tracker#3030]
**Please, provide a clear description what the bug is:**

Varian Wrynn doesn't exist in Stormwind, so I can't turn in this quest

**IDs of affected creatures, items, quests or spells with a link to the relevant page:**

Quest: https://database.turtle-wow.org/?quest=396

**Expected behavior. Describe how it should work:**

I assume that either Varian Wrynn or Lady Prestor should be in the Stormwind Keep, but they aren't there. Only Anduin and Bolvar are.

**Comment by redmagejoe** [comment]
Simply wait for Lady Katrana Prestor to reappear. She vanishes for a while during a particular event.
