### ISSUE TITLE
Baron Geddon Bomb

### ISSUE THREAD

**Issue by Derrurak** [slowtorta/turtlewow-bug-tracker#3033]
**Please, provide a clear description what the bug is:**
Baron Geddon's Bomb is doing more damage than its supposed to(maybe scales with spellpower?) and is capable of critically striking
**Steps to reproduce the behavior with as much detail as possible:**
fight baron geddon, critical strikes with the bomb seem to be a lot more common on casters and healers

1. ![Screenshot 2023-03-18 055001](https://user-images.githubusercontent.com/128205507/226085357-d9235a9b-2fbd-4a89-81d3-f233223491da.png)
2.  ![Screenshot 2023-03-18 055205](https://user-images.githubusercontent.com/128205507/226085440-a11848c2-7d5f-466f-b57b-d99ef74229b2.png) bomb crits less often on a healer and doesnt do quite as much damage, probably because only tiny amounts of spell damage as a healer

3.  i have no evidence for this as i dont have dpsmate screenshots from 1 month ago, but living bomb used to be considered damage taken(or enemy damage done) now it shows as friendly fire

**IDs of affected creatures, items, quests or spells with a link to the relevant page:**

NPC: https://database.turtle-wow.org/?npc=12056
Item: https://database.turtle-wow.org/?item=
Quest: https://database.turtle-wow.org/?quest=
Spell: https://database.turtle-wow.org/?spell=20475
Object: https://database.turtle-wow.org/?object=

**Expected behavior. Describe how it should work:**

https://legacyplayers.info/viewer/5/ability?history_state=7 bombs before the patch that disabled world buffs would never crit and would do 3200 damage(unless berserker stance or similar applies), this is in line with values in the database https://database.turtle-wow.org/?spell=20475

**Comment by balakethelock** [comment]
https://media.discordapp.net/attachments/745013702713016320/1094355379347009628/image.png?width=1083&height=609
The bug is still happening. the explosion damage is self inflicted and uses the player's spell crit. Possibly modified by talents such as warlock's Emberstorm and fire mage's Fire Power as well.

**Comment by balakethelock** [comment]
Did molten core today and the bomb crit me again. This encounter-breaking bug is still happening and all the devs have to do is go to this spell id https://database.turtle-wow.org/?spell=20476 and flag it as "can't crit". What's the freaking hold up for?
