### ISSUE TITLE
Body and Heart Level 10 Druid quest bugged

### ISSUE THREAD

**Issue by Wallabee01** [slowtorta/turtlewow-bug-tracker#3034]
**Please, provide a clear description what the bug is:**
Level 10 Druid Quest "Body and Heart" is unavailable to pickup. Im level 13 now and its still greyed out exclamation mark, on the map its a yellow exclamation mark though.

Bugged NPC: Turak Runetotem
Location: Thunder Bluff
Bugged Quest: Body and Heart
Problem: Cant start quest, exclamation mark is greyed out and im level 13, been greyed out since level 10.
Possible solutions tried; Logged out, quit game for several minutes, logged back in.

**Comment by welpenhund** [comment]
Its greyed out because that is a quest chain.
You gotta do first https://www.wowhead.com/classic/quest=5926/heeding-the-call and then continue till you get to "Body and Heart".
I did the quest myself 1 week ago, it works fine.
