### ISSUE TITLE
Possible Game breaking bug found in custom item Skull of tham

### ISSUE THREAD

**Issue by SimenSch** [slowtorta/turtlewow-bug-tracker#3035]
**Please, provide a clear description what the bug is:**
Skull of tham lets me double hit with my mainhand.
**Steps to reproduce the behavior with as much detail as possible:**

1. equip skull of tham
2.  hit enemy
3.  main hand hits double

**IDs of affected creatures, items, quests or spells with a link to the relevant page:**

Item: https://database.turtle-wow.org/?item=60417

**Expected behavior. Describe how it should work:**
an held in offhand item should not make main hand hit twice, and or hit by itself. when melee damage is hovered over in the character sheet the offhand is shown to have Unarmed speed and 1 damage with 0.5 dps

**Comment by ConcernedTurtler** [comment]
tested and it's almost completely useless on any enemey over level 1 and will miss every time.

**Comment by Zebouski** [comment]
Looks like it needs the tag "Miscellaneous" removed as that's causing the weird behavior

This isn't a game breaking bug tho lol

**Comment by SimenSch** [comment]
you might be correct, we are testing this with some more weapons with some geared warriors to make sure, just wanted to let the devs know asap just incase. i might have been a bit overdramatic with the title of the post =)

**Comment by SimenSch** [comment]
although shadow oil seems to be proccing twice as much even though it only is put on the mainhand

**Comment by ConcernedTurtler** [comment]
Tested this and while it improves your dps a ton on level 1 enemies it's impossible to hit the 60 and bosses. At least on my paladin.  Assuming it's because misc weapons don't have weapon skill.

**Comment by SimenSch** [comment]
i tested getting Unarmed up and then you hit :)

**Comment by Haudraufinix** [comment]
Unarmed weaponskill maxed doesn't help.
The hitcalculation seems to always be at 1 Weapon skill due to the weapon having no weapontype associated. But it does proc effects such as SoR when it connects.

It might however be a probblem in BGs as there Weaponskill is set to playerlvl *5 (+whatever bonuses you might have). Didn't test that yet

**Comment by ConcernedTurtler** [comment]
yeah you'll be really lucky to hit a lvl 60 player with it and you'll never hit a boss.
