### ISSUE TITLE
Flying path is not continuing after leaving BG

### ISSUE THREAD

**Issue by valentynpozniakov** [slowtorta/turtlewow-bug-tracker#3043]
**Please, provide a clear description what the bug is:**
Flying path is not continuing after leaving BG

**Steps to reproduce the behavior with as much detail as possible:**

1. Start flying path from Orgrimmar to Bloodvenom post, Fellwood
![image](https://user-images.githubusercontent.com/67410840/226361387-bc36dc73-a39f-4780-9c0b-99b4b929df5b.png)
2. In middle of the flying path join BG queue (in my case it was Alterac Valley) 
3. Join BG
4. Leave BG after some time using /afk

**Actual Result:** 
Character falled down from the air where he flight before joined BG

**Expected behavior. Describe how it should work:**
Flying path should be continued untill end point

**Comment by slowtorta** [comment]
It's not supposed to work this way in Vanilla. You'll return to the nearest taxi node.

**Comment by redmagejoe** [comment]
This need to be reopened: The issue isn't that it's not continuing, but that it doesn't behave the way @slowtorta mentions. You are literally dropped from where you were before the BG to the ground. If you were flying to Lapidis Isle and are over the ocean when the BG queue pops, guess what? When you leave the BG, you will drop into the middle of the ocean.
