### ISSUE TITLE
Combo Points disappear during various openers.

### ISSUE THREAD

**Issue by ShiraZen** [slowtorta/turtlewow-bug-tracker#3044]
**Please, provide a clear description what the bug is:**

**Steps to reproduce the behavior with as much detail as possible:**

Whenever I'm fighting players, NPCs, or raid bosses - sometimes the first combo point generator will HIT (dealing damage), I will see the combo points show up, and then a few ticks later the combo points will disappear off of the target.

This has been happening consistently for a long time, at first I thought it was an issue with tab targeting, but it definitely is not. Even if I take my hands off the keyboard after the first attack and no other targets are active, the combo points will simply fall off of opponents.

Sinister Strike, Hemo, Cheap Shot, and Garrote all have had this behavior.

**Comment by Frechfuchs** [comment]
I tried playing a new human rogue and did not encounter this problem at all.

**Comment by twowTurtReynolds** [comment]
Others with this issue found it to be due to addons that target other mobs and quickly switch back to your current target, in order to perform their features. When the game differs in framerate, this can cause the target and untarget to be across frames, losing your combo points.
