### ISSUE TITLE
Crusader Strike

### ISSUE THREAD

**Issue by vkekd** [slowtorta/turtlewow-bug-tracker#3045]
Here you can see that it procs vis'kag and frost oil
This makes paladins a really obnoxious class in PVP since CS is a spammable spell that can be used even in bubble
![crsd](https://user-images.githubusercontent.com/110942912/226406934-a4f1f95f-e2c4-4346-8b67-f3a270984b15.png)

![wbsooc](https://user-images.githubusercontent.com/110942912/226407115-256519fe-14b8-4edd-a325-e12a7ae9c4f8.png)

If this is intended the information in the website should be changed https://turtle-wow.org/#/paladin

**Comment by fatnerdynerd** [comment]
please fix this I'm tired of paladins killing me :( 👍

**Comment by balakethelock** [comment]
To clarify, it says "damage-based procs" This means utility procs like quel'sellar or nightfall should still work with crusader strike so pls don't accidentally hit them when you fix the bug

**Comment by balakethelock** [comment]
@geojak  github is for reporting bugs, if you want to propose class changes use the forums.

**Comment by balakethelock** [comment]
What you said might be true but this bugfix must be done. Windfury can be allowed to proc by semantically calling it "not a damage proc" because technically resetting the swing timer is not a damage proc.

**Comment by vkekd** [comment]
> 

I will update the report then and delete the SoC part

**Comment by HuMa69** [comment]
with this cry reports you will make paladin useless again, if WF doesnt proc on CS paladin will be useless again

**Comment by Gurky-Turtle** [comment]
https://github.com/slowtorta/turtlewow-bug-tracker/issues/3889
https://github.com/slowtorta/turtlewow-bug-tracker/issues/3860
https://github.com/slowtorta/turtlewow-bug-tracker/issues/3850

**Comment by burner1024** [comment]
Why are you closing tickets about Judgement of the Crusader and linking them to this issue, which is about Crusader Strike?
These are different spells and different issues.

**Comment by Gurky-Turtle** [comment]
bulking pally issues together

**Comment by twowTurtReynolds** [comment]
This is the current design for Crusader Strike, initially unintended it may be. This may be up for discussion with the 2nd class changes pass.

The website needs an update in the mean time. Remove the text "damage-based procs, "
