### ISSUE TITLE
herb and mining nodes not showing up on minimap unless close

### ISSUE THREAD

**Issue by tarakan404** [slowtorta/turtlewow-bug-tracker#3046]
the herbing and mining nodes bug is back, 
Herbs show up on the minimap only when im close to them, and disappear when only half the minimap away, when usually they appear and disappear at the border of the minimap

had this issue before. here is the old report https://github.com/slowtorta/turtlewow-bug-tracker/issues/1983

**Comment by Gurky-Turtle** [comment]
https://github.com/slowtorta/turtlewow-bug-tracker/issues/3952
