### ISSUE TITLE
Rare NPC "Lord Condar" seems gone from the game.

### ISSUE THREAD

**Issue by Adso777** [slowtorta/turtlewow-bug-tracker#3049]
**Please, provide a clear description what the bug is:**

Rare NPC **_Lord Condar_** is gone from the game. Its 2 spawning points are now taken over by the new custom High Elves areas in Loch Modan and probably it got deleted or something?

**Steps to reproduce the behavior with as much detail as possible:**

1. Go the the 2 spawning points and camp them for hours....the guy just never respawns. It's simply not there anymore but it used to be there before the High Elves as I used to tame it with a new dwarf hunter character.
2. I've also never seen its corpse either. I have the addon Unitscan so I couldn't possible miss it or its corpse all this time.
3. 

**IDs of affected creatures, items, quests or spells with a link to the relevant page:**

NPC: https://www.wowhead.com/classic/npc=14268/lord-condar (wowhead)
NPC: https://database.turtle-wow.org/?npc=14268  (Turtle database)

**Expected behavior. Describe how it should work:**
It should be either where the dark iron new camp (High Elf intro zone) or where the High Elf "Heirs" is. It's never there though.

**Comment by slowtorta** [comment]
Re-added to a different position.
