### ISSUE TITLE
Deadwood Furbolgs bugged. 

### ISSUE THREAD

**Issue by Sapplejacks** [slowtorta/turtlewow-bug-tracker#3051]
**Please, provide a clear description what the bug is:** At least 50% of the Deadwood furbolgs outside the tunnel to wintergrasp/moonglade that you farm for rep are bugged. They will stand still in their spot after aggro'd and make it impossible to charge in (no path available). Even ranged have to walk up and hug them to do any damage so they don't evade. Very irritating & risky to farm the rep out as an HC especially because of this. On top of this: using blink here will usually send you under the map & a friend of mine has experience this and ended up on top of the demon warlocks.

**Steps to reproduce the behavior with as much detail as possible:**

1. Just walk over there and experiment with all of the mobs. Half of them do this half of them don't.
2. 
3. 

**IDs of affected creatures, items, quests or spells with a link to the relevant page:**

NPC: https://database.turtle-wow.org/?npc= https://database.turtle-wow.org/?npc=7157 / https://database.turtle-wow.org/?npc=7158 / https://database.turtle-wow.org/?npc=7156
Item: https://database.turtle-wow.org/?item=
Quest: https://database.turtle-wow.org/?quest=
Spell: https://database.turtle-wow.org/?spell=
Object: https://database.turtle-wow.org/?object=

**Expected behavior. Describe how it should work:**
Evading and standing still.

**Comment by nickgreyden** [comment]
The clarify: This affects The Deadwood Furbolgs ( Den Watcher, Shamans, and Avengers) around the lake just outside the Timbermaw tunnel in the north of Felwood that leads to Moonglade and Winterspring. They have a terrible pathing issues especially around the lake area and will "evade bug".

**Steps to reproduce the behavior with as much detail as possible:**
Simply walk to any of the Deadwood Furbolgs in the low lying area around the lake and attack them from 20+ yds out. I would venture to say 75% of these mobs in that specific location cannot find a path over the vast majority of the terrain.

**NPC:**
https://database.turtle-wow.org/?npc=7157 
https://database.turtle-wow.org/?npc=7158 
https://database.turtle-wow.org/?npc=7156
https://database.turtle-wow.org/?npc=9462
**Quest:**
https://database.turtle-wow.org/?quest=8461
https://database.turtle-wow.org/?quest=8467

**Comment by Olivinee** [comment]
Still occuring

**Comment by Reignwizard** [comment]
it's a pain to aoe farm them because they just evade and you need to be in melee to hit them.

also, when you charge them it say there is no path to target

**Comment by YamaYAML** [comment]
Troubleshooting and working on a fix

**Comment by Gurky-Turtle** [comment]
https://github.com/slowtorta/turtlewow-bug-tracker/issues/3813

**Comment by Olivinee** [comment]
still occuring

**Comment by melg8** [comment]
Still occuring.

**Comment by YamaYAML** [comment]
Thanks! Very helpful info. Nothing better than a repeodicle scenario. I'll get to this one soon, promise

**Comment by nickgreyden** [comment]
Made periodic trips there with my mage and noticed the situation getting better. Over the past week I've spent a lot of time up there and have not noticed a single evade bug on my mage and there have been tons of hunters there too and I haven't seen issues with them as well. So thanks for the work. I'm sure this will be completed soon!
