### ISSUE TITLE
Devilsaur Leggings/Gauntlets not showing set bonus. Greyed out showing 0/2 pieces.

### ISSUE THREAD

**Issue by Grexx1** [slowtorta/turtlewow-bug-tracker#3052]
**Please, provide a clear description what the bug is:**
Devilsaur Leggings/Gauntlets not showing set bonus. With both pieces equipped my set list is greyed out showing 0/2 pieces.  When I take off one peice and have it in my bag and highlight it, it shows 1/2 in yellow and lists the other piece I still have equipped as being detected.  When I put both back on, it goes back to grey and 0/2. Both items are transmogged.

**Steps to reproduce the behavior with as much detail as possible:**

1. Wear the items.

**IDs of affected creatures, items, quests or spells with a link to the relevant page:**

Item: 
https://database.turtle-wow.org/?item=15063
https://database.turtle-wow.org/?item=15062

**Expected behavior. Describe how it should work:**
My set list should be yellow and show 2/2 as it normally would.

**Comment by Ryobazt** [comment]
@balakethelock are u sure? im almost reset my transmog'ed items cuz have same problem like @Grexx1

**Comment by slowtorta** [comment]
It's a transmog issue. THe bonus is there.
