### ISSUE TITLE
Archmage Xylem "A Special Kind of Summons" Not Available

### ISSUE THREAD

**Issue by lordofhell666** [slowtorta/turtlewow-bug-tracker#3054]
**Please, provide a clear description what the bug is:**
I'm unable to get the quest "Lost to the Sands" on my mage; it's not available on Xylem. He only has his basic, universal quests available.
**Steps to reproduce the behavior with as much detail as possible:**

1. Get the quest "A Special Kind of Summons"
2. Turn it in to Sanath Lim-yo.
3. Talk to Xylem and see he has no oranges quest available.

**IDs of affected creatures, items, quests or spells with a link to the relevant page:**

NPC: https://database.turtle-wow.org/?npc=8379
Quest: https://database.turtle-wow.org/?quest=70001

**Expected behavior. Describe how it should work:**
Turn in "Lost to the Sands," find "A Special Kind of Summons" available from Xylem; as it says it should be on the databse.

**Comment by slowtorta** [comment]
Workin as intended. Please disable your addons if any.  
![image](https://user-images.githubusercontent.com/66763404/229360851-fccddb4e-908a-4eb7-b9c4-f3c7fd261e31.png)
