### ISSUE TITLE
Pixelated effects on Turtle client

### ISSUE THREAD

**Issue by HuMa69** [slowtorta/turtlewow-bug-tracker#3055]
**Please, provide a clear description what the bug is:** Pixelated effects on Turtle client

**Steps to reproduce the behavior with as much detail as possible:**

Almost every spell looks pixelated in the middle of the animation

![image](https://user-images.githubusercontent.com/23564552/226640938-bf9e35c7-d5ff-4fdc-8b52-f1b2e0a028ff.png)
![image](https://user-images.githubusercontent.com/23564552/226641133-5e5073d4-ab63-4773-90a4-a46ffcda7ccc.png)
![image](https://user-images.githubusercontent.com/23564552/226641175-9d9bf6bb-1cca-4886-a2fa-989b84ba9f8c.png)

Im using AMD GPU but i only have this bug on turtle client, with maxed graphics and no mods, other servers under 1.12.1 looks okay

**Comment by HuMa69** [comment]
bump

**Comment by twowTurtReynolds** [comment]
@slowtorta this fix aparently didn't make it into 1.17.0 https://streamable.com/gf1xfc
