### ISSUE TITLE
Hunter pet disappearing

### ISSUE THREAD

**Issue by Metsaurpo** [slowtorta/turtlewow-bug-tracker#3057]
**Please, provide a clear description what the bug is:**

My hunter pet keeps disappearing,

**Steps to reproduce the behavior with as much detail as possible:**

1. I train a pet and it works fine.
2.  The pet keeps being unhappy no matter how much i feed it food.
3.  about 15 to 20 minutes it just vanishes into void.  Can't tame it again cause it is gone. 
4.  Happened with Worgs and Bears. 

**IDs of affected creatures, items, quests or spells with a link to the relevant page:**

NPC: https://database.turtle-wow.org/?npc=
Item: https://database.turtle-wow.org/?item=
Quest: https://database.turtle-wow.org/?quest=
Spell: https://database.turtle-wow.org/?spell=
Object: https://database.turtle-wow.org/?object=

**Expected behavior. Describe how it should work:**

The pet should turn hostile if it loses my trust not just vanish.

**Comment by twowTurtReynolds** [comment]
Rank 1 loyalty pets take _a lot_ of food to keep happy. They will flee on you if not kept happy.
