### ISSUE TITLE
[Rethban Ore] doesnt drop from veins inside Rethban Caverns

### ISSUE THREAD

**Issue by Zulmamwe** [slowtorta/turtlewow-bug-tracker#306]
**Please, provide a clear description what the bug is:**
Quest item [Rethban Ore](https://database.turtle-wow.org/?item=2798#mined-from-object) is not dropped from Veins (db says only Tin, but Copper too) or drop rate is too low
>Rethban ore can be mined from tin veins, but only those in the northwestern area of Redridge.

>Because the rethban ore only drops from these specific veins, the drop rate (0.6% - tracking the drops from all veins everywhere) is very inaccurate. In reality, about 1-2 ores drop from each tin vein. Edit: Just as a clarification; the area where you can mine this ore is the Rethban Cavern in the northwestern area of Redridge Mountains. It also drops from the gnolls in the cavern (as stated by the "Dropped by"-tab), so you don't have to be a miner for the quest.

>Note: Although not stated here, it can also be mined from Copper Veins in the Rethban Caverns.
So currently being a miner doesnt aid you in that quest in any way.

**Steps to reproduce the behavior with as much detail as possible:**

1. Go to Rethban Caverns (Redridge, north of Lakeshire)
2. Mine any vein
3. Dont get 2+ ores per vein

**IDs of affected creatures, items, quests or spells with a link to the relevant page:**

Item: https://database.turtle-wow.org/?item=2798
Wowhead comments (look at old patches) - https://www.wowhead.com/item=2798/rethban-ore#comments
Quest: https://database.turtle-wow.org/?quest=347
Object: https://database.turtle-wow.org/?object=2054

**Expected behavior. Describe how it should work:**
Rethban ore should drop with >90% chance from any veins in that cave, but other copper or tin veins across the world shouldn't have a chance to drop it at all

**Comment by slowtorta** [comment]
Thanks for reporting it. It'll be fixed on the next server restart. Make sure to clear your WDB folder.

**Comment by geojak** [comment]
hello this doesnt seem to be fixed, i made a new issue
