### ISSUE TITLE
The quest Wandering Shay in feralas can kill HC players

### ISSUE THREAD

**Issue by kheker** [slowtorta/turtlewow-bug-tracker#3063]
**Please, provide a clear description what the bug is:**
 The quest Wandering Shay in feralas who belong to alliance they have to scort a Night Elf. 
**Steps to reproduce the behavior with as much detail as possible:**

1. the quest Wandering Shay in feralas who belong to alliance they have to scort a Night Elf. 
2. hordes near this npc can be attacked and have a very long aggro range. can be used to kill hardcore players
3. hordes can't attack npc

**IDs of affected creatures, items, quests or spells with a link to the relevant page:**

NPC: https://database.turtle-wow.org/?npc=
Item: https://database.turtle-wow.org/?item=
Quest: https://database.turtle-wow.org/?quest=2845
Spell: https://database.turtle-wow.org/?spell=
Object: https://database.turtle-wow.org/?object=

**Expected behavior. Describe how it should work:**

**Comment by twowTurtReynolds** [comment]
![image](https://github.com/slowtorta/turtlewow-bug-tracker/assets/151180101/490f5662-729d-4c37-9523-16f514fd341c)
Can't reproduce. Shay doesn't seem interested at all at this juicy lv 40 I put right here.
