### ISSUE TITLE
Sapphiron Shoulder Enchants not working.

### ISSUE THREAD

**Issue by Heyzeussss** [slowtorta/turtlewow-bug-tracker#3066]
**Please, provide a clear description what the bug is:**
Sapphiron healing shoulder enchant & possibly others have been bugged for some time.  
**Steps to reproduce the behavior with as much detail as possible:**

1.
2. 
3. 

**IDs of affected creatures, items, quests or spells with a link to the relevant page:**

NPC: https://database.turtle-wow.org/?npc=
Item: https://database.turtle-wow.org/?item=
Quest: https://database.turtle-wow.org/?quest=
Spell: https://database.turtle-wow.org/?spell=
Object: https://database.turtle-wow.org/?object=

**Expected behavior. Describe how it should work:**
The 31 healing + 5 MP5 shoulder enchant should provide it's benefits when used on the piece of shoulder equipment

**Comment by Zebouski** [comment]
what is your proof these aren't working? i get 371 vs 366 with t3 + saph enchant vs t2 + zg enchant, thats 82 vs 60 +heal and would be 51 vs 60 if not working.

**Comment by Heyzeussss** [comment]
> what is your proof these aren't working? i get renew ticks for 371 vs 366 with t3 + saph enchant vs t2 + zg enchant, thats 82 vs 60 +heal and would be 51 vs 60 if not working.

Has been proven by two holy paladins that it doesn't increase healing at all.  One by Plasterchan if you need to whipser him.  It doesnt do anything atm.  Most likely a gap in healing from your gear

**Comment by Zebouski** [comment]
they should probably be the ones putting in the bug report with the proof then. I just proved it's working as intended for priests at the very least.

**Comment by CosminPOP** [comment]
pure healing enchant https://database.turtle-wow.org/?item=23547
![image](https://user-images.githubusercontent.com/7255825/228811827-9abc08e7-89a4-429a-9061-f589ae16ef0b.png)
first 3 are without shoulder enchant
last 3 are with shoulder enchant

spelldamage and healing enchant https://database.turtle-wow.org/?item=23547
![image](https://user-images.githubusercontent.com/7255825/228812238-45926856-9c99-415d-b979-dce2ad177753.png)
first 3 are without shoulder enchant
last 3 are with shoulder enchant

**Comment by Gurky-Turtle** [comment]
Most likely these guys were looking at better character stats or something which the base version is missing a lot of checks for a ton of things. I made a modified version that actually checks for these enchants and calculates them. I have found the same thing as @CosminPOP on my priest they work.

**Comment by lyssebabz** [comment]
It shows spellpower but not crit
