### ISSUE TITLE
Orb of Draconic Energy gets "Invalid Target" when it shouldn't, preventing quest completion (still persists)

### ISSUE THREAD

**Issue by Patryvius** [slowtorta/turtlewow-bug-tracker#3067]
Here's the link to the original:

https://github.com/slowtorta/turtlewow-bug-tracker/issues/467

This has not been fixed at all, the mind control quest item doesn't work and prevents quest completion.

**Comment by Muigin** [comment]
Cannot reproduce on current version. Seal forges properly when Emberstrife breathes fire on it.
