### ISSUE TITLE
sounds missing when losing bg

### ISSUE THREAD

**Issue by geojak** [slowtorta/turtlewow-bug-tracker#3070]
**Please, provide a clear description what the bug is:**

1. queue wsg as allaince
2. lose wsg to the horde
3. scroe window pops up
4. no music plays, silent

**Expected behavior. Describe how it should work:**
when alliance wins the allaicne theme music plays, 
when horde wins the horde theme music plays
when the game is closed due to too little players, no music plays (current sitaution when losing)

**Comment by Muigin** [comment]
Cannot reproduce on current version.
