### ISSUE TITLE
Unable to access Alah'Thalas from SW Mage tower

### ISSUE THREAD

**Issue by Jon-Snows** [slowtorta/turtlewow-bug-tracker#3072]
**Please, provide a clear description what the bug is:**

**Steps to reproduce the behavior with as much detail as possible:**

1. Talk to Elsharin "mage trainer" but no option for port
2. I tried deleting WDB folder and restarting app no luck.
3. I can see the crystal spawn when other High Elf players are porting but it doesn't let me interact with it and it despawns after a few seconds. 
4.  I also tried turning off all Add Ons, and deleting WDB folder and restarting app but no luck. 
5.  my High Elf mage character name is Tribulation

**IDs of affected creatures, items, quests or spells with a link to the relevant page:**

NPC: https://database.turtle-wow.org/?npc= Elsharin
Item: https://database.turtle-wow.org/?item=
Quest: https://database.turtle-wow.org/?quest=
Spell: https://database.turtle-wow.org/?spell=
Object: https://database.turtle-wow.org/?object=

**Expected behavior. Describe how it should work:**
Talk to Elsharin and she says safe travels and spwns a crystal I can click on to to get to Alah'Thalas.

**Comment by redmagejoe** [comment]
Did you complete the necessary quest chain?
https://database.turtle-wow.org/?quest=80250

**Comment by slowtorta** [comment]
Click on the teleportation orb she spawns next to her :)

**Comment by slowtorta** [comment]
Working as intended, indeed please complete the pre-quest.
