### ISSUE TITLE
Bug with NPC Overlord Mok'Morokk

### ISSUE THREAD

**Issue by Jambossa** [slowtorta/turtlewow-bug-tracker#3073]
**Please, provide a clear description what the bug is:**

**Steps to reproduce the behavior with as much detail as possible:**

1. ALL quests u must do by the interaction with this NPC are unevailable, its just innactive

**IDs of affected creatures, items, quests or spells with a link to the relevant page:**

NPC: https://database.turtle-wow.org/?npc=4500
Quest: https://database.turtle-wow.org/?quest=1166
           https://database.turtle-wow.org/?quest=1171
           https://database.turtle-wow.org/?quest=1173

**Expected behavior. Describe how it should work:**
It should work well, thats all

**Comment by slowtorta** [comment]
He's working as intended. Please cleard your WDB folder and try again! :)
