### ISSUE TITLE
Ancient Burial Container has long respawn timer

### ISSUE THREAD

**Issue by AKryukov92** [slowtorta/turtlewow-bug-tracker#3074]
Container for quest item in quest Drifting Across the Sand has long respawn timer.
Expected it to have small respawn timer to let every party member to get quest item.
Drifting Across the Sand https://database.turtle-wow.org/?quest=40519
[Ancient Burial Container](https://database.turtle-wow.org/?object=2010915)

**Comment by jameyboor** [comment]
This will be fixed on next server update.
