### ISSUE TITLE
"Uldum Awaits" horde quest

### ISSUE THREAD

**Issue by Wayrond** [slowtorta/turtlewow-bug-tracker#3077]
The quest "Uldum Awaits" cannot be completed because it is impossible to activate the pedestal, when you hover over the pedestal in front of the gates of Uldum, it is still inactive.

1. Quest started in Thunder Bluff.
2. The pedestal in Tanaris, at the gates of Uldum, remains inactive.

![WoWScrnShot_032423_221640](https://user-images.githubusercontent.com/128882566/227698512-ea356879-359a-471e-a380-319f35d92336.png)

Quest: https://database.turtle-wow.org/?quest=40114

The pedestal must be active and it should be possible to complete the quest.

**Comment by slowtorta** [comment]
Probably fixed in the next revision.

**Comment by slowtorta** [comment]
Probably fixed in the next revision.
