### ISSUE TITLE
Fashion Demand Sacrifice L.v10 Quest (Alliance) Bug Cannot turn in

### ISSUE THREAD

**Issue by jongyi233** [slowtorta/turtlewow-bug-tracker#3078]
**Please, provide a clear description what the bug is:**
I cannot turn in and complete Fashion Demand Sacrifice quest despite having all the necessary items in inventory
**Steps to reproduce the behavior with as much detail as possible:**

1. Have all the items for quest in inventory
2. Ophelia Worthinton has quest complete icon on her head
3. Cannot complete the quest and turn in

**IDs of affected creatures, items, quests or spells with a link to the relevant page:**

NPC: https://database.turtle-wow.org/?npc=https://database.turtle-wow.org/?npc=51292
Item: https://database.turtle-wow.org/?item=
Quest: https://database.turtle-wow.org/?quest= https://database.turtle-wow.org/?quest=60030
Spell: https://database.turtle-wow.org/?spell=
Object: https://database.turtle-wow.org/?object=

**Expected behavior. Describe how it should work:**
Should complete the quest

**Comment by cyaohiri** [comment]
Abandoning the quest and taking it should fix it. Make sure the items are in your bags, and not in your bank.

**Comment by slowtorta** [comment]
You're probably past the quest' available level range.
