### ISSUE TITLE
Can't obtain Cairne's hoofprint

### ISSUE THREAD

**Issue by Robaj** [slowtorta/turtlewow-bug-tracker#308]
I am doing the Children's Week questline with my Orc Hunter, Robaj.

I am on the Cairne's Hoofprint quest currently in the questline. I have my Orphan out, and I can speak to Cairne, as I should according to the quest, but as he should give me his hoofprint, I get a message "You don't have any space in your bags." But I do have empty space in each of my bags, so I don't understand what could be the problem.

Please help me resolve this bug so I can continue the questline.

**Comment by SierraNairn** [comment]
Please make a in game ticket.

**Comment by Robaj** [comment]
Thank you, how do I do that?

**Comment by SierraNairn** [comment]
https://forum.turtle-wow.org/viewtopic.php?p=11338#p11338

**Comment by Robaj** [comment]
Thank you very much!

**Comment by slowtorta** [comment]
Thank you. This will be fixed on the next server update.
