### ISSUE TITLE
Corruption of Earth and Seed

### ISSUE THREAD

**Issue by Markmuza** [slowtorta/turtlewow-bug-tracker#3080]
**Please, provide a clear description what the bug is:**
Can't start the "Corruption of Earth and Seed" quest, as i'm not allowed to interact with Keeper Marandis.
Can't talk to him, only attack him.

**Steps to reproduce the behavior with as much detail as possible:**

1. be lvl 46 gnome
2. try and talk to Keeper Marandis
3. fail, cause i can only attack him

**IDs of affected creatures, items, quests or spells with a link to the relevant page:**

NPC: https://database.turtle-wow.org/?npc=13698
Item: https://database.turtle-wow.org/?item=
Quest: https://database.turtle-wow.org/?quest=7065
Spell: https://database.turtle-wow.org/?spell=
Object: https://database.turtle-wow.org/?object=

**Expected behavior. Describe how it should work:**
i should be able to talk to him

**Comment by balakethelock** [comment]
Go to character sheet, reputation tab, scroll down to "cenarion circle" and turn off "at war" with them.

**Comment by Markmuza** [comment]
god bless ❤️
________________________________
Fra: balakethelock ***@***.***>
Sendt: lørdag 25. mars 2023 11:43
Til: slowtorta/turtlewow-bug-tracker ***@***.***>
Kopi: Markmuza ***@***.***>; Author ***@***.***>
Emne: Re: [slowtorta/turtlewow-bug-tracker] Corruption of Earth and Seed (Issue #3080)


Go to character sheet, reputation tab, scroll down to "cenarion circle" and turn off "at war" with them.

**Comment by jameyboor** [comment]
The Cenarion Circle default to At War will be resolved in the next client patch but you can use the fix of @balakethelock for now.
