### ISSUE TITLE
Cannot mark targets solo

### ISSUE THREAD

**Issue by Jorrick** [slowtorta/turtlewow-bug-tracker#3081]
**Please, provide a clear description what the bug is:**

In classic you were able (100% sure) to mark targets with a skull/cross etc. without being in a party AND being the party leader.
I use /target <specific mob name like tideress in ashenvale> to see if they are up, then I mark them to find them.
In Turtle wow, it's only possible if you are in a party AND it's leader. 

**Steps to reproduce the behavior with as much detail as possible:**

1.  Target a mob
2.  Don't be in a party
3.  Try to put a skull on it

**IDs of affected creatures, items, quests or spells with a link to the relevant page:**

Not relevant, it's all mobs

**Expected behavior. Describe how it should work:**

1.  Target a mob
2.  Don't be in a party
3.  Put a mark on it 

I have excluded any addons, ran it without any addons or modifications and it's thesame behaviour.

It's as if there is a double " If statement" in the code that checks for being in a party and it's leader, that wasnt in original classic.

**Comment by balakethelock** [comment]
That's never been possible in 1.12 vanilla client. Classic is different from 1.12 vanilla in this regard.

**Comment by Jorrick** [comment]
The the nostalrius / lightshope / blizzard vanilla were all different from this version then I reckon. 
Would it be possible to implement this? I have heard others in both discord and world chat asking this very same question.

**Comment by jameyboor** [comment]
This is a client-side restriction that we're not addressing at this moment.

**Comment by burner1024** [comment]
This certainly would be a very desired QoL addition, and I believe not hard to implement.
