### ISSUE TITLE
It is possible to enchant Zandalar Signet of Tenacity to low level character

### ISSUE THREAD

**Issue by AKryukov92** [slowtorta/turtlewow-bug-tracker#3083]
Zandalar Signet of Tenacity https://database.turtle-wow.org/?item=65033
can be enchanted via trade.
All other enchants can not be enchanted via trade:
[Zandalar Signet of Might](https://database.turtle-wow.org/?item=20077)
[Zandalar Signet of Mojo](https://database.turtle-wow.org/?item=20076)
[Zandalar Signet of Serenity](https://database.turtle-wow.org/?item=20078)

Expected behavior:
Signet of Tenacity should not be possible to enchant via trade.

**Comment by AKryukov92** [comment]
Actually, I hadn't checked it in February. It would be cool if someone confirm is it in game or not.
Something should also be done with existing applied enchants. Refund as 15 Bijous for everyone without enchant sounds fair.

**Comment by slowtorta** [comment]
Duplicate to newer issue, still persisting.
