### ISSUE TITLE
Imp's Blood Pact not working within a group.

### ISSUE THREAD

**Issue by Knuckle02** [slowtorta/turtlewow-bug-tracker#3084]
Bug description: Warlock Imp's Blood Pact does not reapply if someone gets out of range while in a party.

Recasting the Blood Pact still does not reapply the buff, but leaving the party or deleting WDB folder does.

Steps to reproduce the behavior with as much detail as possible:

- Be in a party of at least two people nearby each other.
- As a warlock, summon an imp.
- Activate Blood Pact (autocast).
- Have anyone move out of range of the imp.
- Blood Pact will not become active on your character or others in the party until WDB folder is deleted. Resummoning the Imp, toggling it off and on does nothing, nor does relogging. Only deleting WDB folder or leaving the party.
- Rejoining the party will have the Blood Pact active on the warlock's character, but no one elses. Recasting Blood Pact in this situation will only remove the buff from your character too.

IDs of affected creatures, items, quests or spells with a link to the relevant page:

NPC: Warlock player's imp summon pet
https://database.turtle-wow.org/?spell=688

Spell: Blood Pact (Warlock Imp spell, rank 2)
https://database.turtle-wow.org/?spell=20318

Players Beardedgnome (Gnome Warlock) and any others in group are affected.

Expected behavior. Describe how it should work:
Expected behavior is that the Imp's Blood Pact is a constant buff that stays on for all party members within a 20 yd radius.

**Comment by Knuckle02** [comment]
I wanted to note that it appears Blood Pact is fully functional in instanced groups, but not open world.

**Comment by ratkosrb** [comment]
Most likely some of your party are flagged for PvP, but the owner of the Imp is not flagged. It is blizzlike for party auras not to affect PvP flagged targets when the caster is not flagged. Otherwise you could help people in PvP, by joining their party and giving them party wide auras, while you yourself are not flagged and not attackable.

**Comment by Knuckle02** [comment]
> Most likely some of your party are flagged for PvP, but the owner of the Imp is not flagged. It is blizzlike for party auras not to affect PvP flagged targets when the caster is not flagged. Otherwise you could help people in PvP, by joining their party and giving them party wide auras, while you yourself are not flagged and not attackable.

This is not the case. I am pvp flagged and others with pvp flag on do not receive the buff. It applies to non-pvp flagged players in the group the first time they enter, but once outranged it disappears.

**Comment by twowTurtReynolds** [comment]
The giver is flagged and the reciever is not flagged, and we see the lack of buff:
![image](https://github.com/slowtorta/turtlewow-bug-tracker/assets/151180101/c7733f85-797e-4a2c-96d6-14687c2720ca)

And then I pvp flag, and it works:
![image](https://github.com/slowtorta/turtlewow-bug-tracker/assets/151180101/1860ab50-288d-4918-8032-59081eb90899)

Make sure that all players in your group either don't flag, or all flag.
