### ISSUE TITLE
The Long night is not over quest

### ISSUE THREAD

**Issue by Apollodonis** [slowtorta/turtlewow-bug-tracker#3086]
**Please, provide a clear description what the bug is:**

**Steps to reproduce the behavior with as much detail as possible:**

1. Quest is not showing for me, cannot take it
2. Level 60, raiding Naxx already
3. 

**IDs of affected creatures, items, quests or spells with a link to the relevant page:**

NPC: https://database.turtle-wow.org/?npc=11536
Quest: https://database.turtle-wow.org/?quest=40221

**Expected behavior. Describe how it should work:**

**Comment by Gurky-Turtle** [comment]
This requires Revered with the argent dawn, not a bug.
