### ISSUE TITLE
Cannot cast imp's Fire Shield on other players

### ISSUE THREAD

**Issue by joycourier** [slowtorta/turtlewow-bug-tracker#3087]
**Please, provide a clear description what the bug is:**
When I target any player and cast Fire Shield, the imp plays a casting animation and 60 mana is consumed from the imp's mana pool, but the buff does not activate. Only when Fire Shield is cast while targeting myself does it work.

**Steps to reproduce the behavior with as much detail as possible:**

1. Target other player within 30 yards.
2. Click 'Fire Shield' on the pet hotbar.
3. https://i.imgur.com/XW3kw1d.mp4

**IDs of affected creatures, items, quests or spells with a link to the relevant page:**

Spell: https://database.turtle-wow.org/?spell=2947

**Expected behavior. Describe how it should work:**
Select friendly target, cast fire shield, target receives fire shield buff.

**Comment by redmagejoe** [comment]
It is not a bug. You are trying to cast Fire Shield with no target selected, meaning it is attempting to cast on your Imp. Your Imp is phase shifted, and this is not checked before the cast attempt.  This is vanilla behavior.

**Comment by cyaohiri** [comment]
> It is not a bug. You are trying to cast Fire Shield with no target selected, meaning it is attempting to cast on your Imp. Your Imp is phase shifted, and this is not checked before the cast attempt. This is vanilla behavior.

I tested it without Phase Shift. When there is no target, an error says "No target"' nothing happens, and mana is not used, as expected.
If I target a hostile NPC, it says "Invalid target" and again, nothing happens, and mana is not used.
However, if I target the imp himself or a friendly target not in the group, including friendly NPCs, the imp will spend his mana, even though Fire Shield wasn't applied to anyone.

That last part seems like a bug, even though it might match the vanilla behavior.
