### ISSUE TITLE
Drop chance: Totem of sustaining

### ISSUE THREAD

**Issue by cawilliamson** [slowtorta/turtlewow-bug-tracker#3088]
**Please, provide a clear description what the bug is:**

The drop chance of Totem of Sustaining is lower than retail based on Wowhead drop chances for some bosses:

https://www.wowhead.com/classic/item=23200/totem-of-sustaining
https://database.turtle-wow.org/?item=23200

I've lost track of how many times I've ran this place over the now 4 days but have failed to see it once. Apparently the drop is working but the chances seem a bit off. May be worth checking.

**Steps to reproduce the behavior with as much detail as possible:**

1. Run Scholomance
2. Kill last 6 bosses
3. Loot
4. Cry
5. Repeat

**IDs of affected creatures, items, quests or spells with a link to the relevant page:**

https://www.wowhead.com/classic/item=23200/totem-of-sustaining
https://database.turtle-wow.org/?item=23200

**Expected behavior. Describe how it should work:**

Should drop more frequently - at least a little bit. Though it would be nice to give this and the Paladin libram a buff anyway to make this grind a lot less awful! :)

**Comment by Jeradooka** [comment]
4. Cry
5. Repeat
6. Claim that it is a bug on Github

**Comment by slowtorta** [comment]
The chances in our DB seem correct. Online DB doesn't display reference drop chances correctly.
