### ISSUE TITLE
The warlocks succubist move called "Sudduction" is not working as inteded

### ISSUE THREAD

**Issue by Necromentia000** [slowtorta/turtlewow-bug-tracker#309]
**Please, provide a clear description what the bug is:** As a warlock I cannot get my pet "Succubist" to use one of her special moves called "Seduction" which the move is subpost to last 15 seconds *Without diminishing returns* against players but this is not the case you can have your pet constantly cast this spell but it barely even hits and when it does *Rarely*  hit it will last from 1-2 seconds if you are lucky it might last 6 but that is still very low in seconds *On entities the effect is the same it will not get seduced with casting the spell constantly most of the time I even tested this on very very low levels*. Because of the bug that has lasted for a few months warlocks are currently the weakest pvp class on the server.

**Steps to reproduce the behavior with as much detail as possible:**

1. Cast the spell "Summon Succubist" 
2. Have your succubist cast seduction
3. cast seduction many times on both a entitie and a player

**IDs of affected creatures, items, quests or spells with a link to the relevant page:**

NPC: https://database.turtle-wow.org/?npc=
Item: https://database.turtle-wow.org/?item=
Quest: https://database.turtle-wow.org/?quest=
Spell: https://classic.wowhead.com/spell=6358/seduction
Object: https://database.turtle-wow.org/?object=

**Expected behavior. Describe how it should work:**
What is a expected that should happen is it should often hit and have the same time in seconds as a rank2 fear.

**Comment by jameyboor** [comment]
Fixed.
