### ISSUE TITLE
Druid Quest: Bloodpetal Poison needs tweaking

### ISSUE THREAD

**Issue by DavidYakobi** [slowtorta/turtlewow-bug-tracker#3093]
The Gorishi Stings don't drop.

Steps:
1.  Acquire the quest at level 50 from Torwa Pathfinder.
2.  Go to Gorishi Hive area in Un'Goro Crater.
3.  None of the insects drop a "Gorishi Sting", even though the tooltip says (15% drop rate on some).
4.  I have tried killing them all:  Wasps, Workers, Stingers, Burrowers, Reavers.   No drops!

Me:  Tauren Druid level 50 at the time.

NPC: Torwa Pathfinder - https://database.turtle-wow.org/?npc=9619
Item: Gorishi Sting - https://database.turtle-wow.org/?item=22435
Quest:  Bloodpetal Poison - https://database.turtle-wow.org/?quest=9052

**Comment by DavidYakobi** [comment]
Ok, I tried again today and I got 1 drop from a Wasp after over 50 kills.   I think maybe the drop-rate is off by a factor of 10, so instead of a 15% chance drop we are getting a 1.5% chance?   Please investigate.

**Comment by Gurky-Turtle** [comment]
![image](https://github.com/slowtorta/turtlewow-bug-tracker/assets/90982783/e6a82b0e-aa24-4cb8-b50c-af862c0552a3)
its 15% rate just bad rng this is not a bug
