### ISSUE TITLE
Rested XP despite playing on Exhaustion Mode

### ISSUE THREAD

**Issue by Sacralletius** [slowtorta/turtlewow-bug-tracker#3094]
**Please, provide a clear description what the bug is:**

_I'm playing on Exhaustion Mode (and Slow and Steady Mode). Today, when I logged in, my XP bar had turned blue and there was a small part of it that counted as rested XP. In logged out in Teldrassil (Aldrassil) and when I logged back in, there was my XP was blue.
It happened after the server got down yesterday, so I wasn't able to log out "properly", but instead got disconnected forcefully._

**Steps to reproduce the behavior with as much detail as possible:**

_I can't reproduce it, since it seems to be related to the server going down._

**IDs of affected creatures, items, quests or spells with a link to the relevant page:**

NPC: https://database.turtle-wow.org/?npc=
Item: https://database.turtle-wow.org/?item=
Quest: https://database.turtle-wow.org/?quest=
Spell: https://database.turtle-wow.org/?spell=
Object: https://database.turtle-wow.org/?object=

**Expected behavior. Describe how it should work:**
_I should not be getting any rested XP._
![WoWScrnShot_032723_152636](https://user-images.githubusercontent.com/8215116/227952786-52a2b88d-2acb-457a-ad8d-7bbe68f3fd3a.jpg)

**Comment by cyaohiri** [comment]
It's a known issue. The rested experience should go away after one kill that grants experience.
