### ISSUE TITLE
Poisons/Weapon Effects & Enchants can not be procced off Sap, Gouge, Cheap/Kidney Shot OR Feint (+ More)

### ISSUE THREAD

**Issue by imaglcian** [slowtorta/turtlewow-bug-tracker#3097]
**Please, provide a clear description what the bug is:**
So, I made a bug report over a year ago discussing this topic, in which it still hasn't been fixed. 
Crippling, Mind-Numbing and Wound Poison + Alot of passive weapon effects/enchants can not be procced by incapacitating abilities here, which isn't blizz-like. (Also this does work on other servers)
I'll include a bunch of YouTube links to sources proving the fact it should be possible, aswell as my own testing and some talking in my own clips.

The biggest downside to this, which I explain in my own video, is that facing warriors just becomes instantly more unfavored for us, especially Orc warriors. We rely on a certain opener to not get hit at the start, and not get any unlucky stun resists, and ultimately can kite them from the start. With the non-addition of not being able to proc poisons during our openers, and with the melee leeway already being bad enough as it is (See https://youtu.be/d0ofoVFQ8c0?t=45 for more info; I strafe him, and as he strafes back and I follow his pathing, he still gets an intercept off  - This is another bug report within itself, in which i have to gather ALOT more clips for. For now, distract will also be useless on this server - Or Demonic Rune/Sapper/Death Ray batching on CC), this just makes Rogue V. Warrior pretty onesided.

My own video (Please note, that Crusdader did NOT proc off sinister strike, the 3rd clip was heavily cut down, but I did about 11 Sinister Strikes=: https://www.youtube.com/watch?v=57VVfP6Sq8M)

**Steps to reproduce the behavior with as much detail as possible:**

1. Sap/Gouge/Feint a player target
2. See if weapon enchants like Crusader, Frost Chill OR Poisons like Crippling/Mind-Numbing/Wound OR weapon effects like Serenity proc.
3. If not, then it should be considered a bug.

**Expected behavior. Describe how it should work:**
Sap/Gouge/Feint, etc. Should all be able to proc non-damaging poisons, weapon effects and enchant effects.

**Proofs**
All from WoW Classic.
https://youtu.be/kf04RPqMml4?t=55 = Crippling Poison on Sap Proc
https://youtu.be/cwtxj-ubudw?t=43 = Crippling Poison on Sap Proc
https://youtu.be/xTa9WTGCGaI?t=53 = Crippling Poison on Sap Proc
https://youtu.be/xTa9WTGCGaI?t=139 = Crippling Poison on Sap Proc
https://youtu.be/8Gy8bydO_Hw?t=11 = Crippling Poison on Sap Proc
https://youtu.be/DhWRkCvWovI?t=774 = Crippling Poison on Sap Proc
https://youtu.be/RmbyeyhWQIA?t=226 = Crippling Poison on Sap Proc

https://www.youtube.com/watch?v=RmbyeyhWQIA = Crippling Poison on Cheap Shot Proc
https://youtu.be/xTa9WTGCGaI?t=53 = Crippling Poison on Cheap Shot Proc

https://youtu.be/RmbyeyhWQIA?t=356 = Crippling Poison on Gouge Proc
https://youtu.be/YkCJeCtYzEU?t=103 = Crippling Poison on Gouge Proc

https://youtu.be/xTa9WTGCGaI?t=23 = Crusader on Sap Proc (These are hard to find, as Crusader in itself is a super rare proc already)

https://youtu.be/-3_FkK_Fsfk?t=65 & https://youtu.be/-3_FkK_Fsfk?t=194 = Perplexity about Serenity proccing off quick abilities like Feint.

**From other Private Servers**
Finding clips from private servers is super hard, although I'll say I have enough proofs
https://youtu.be/NENsoOaM7xc?t=116 = Crippling Poison on Cheap Shot Proc @ Kronos -> Then crusader proc on auto (Not crippling) 

**MOST IMPORTANT NOTE**
https://youtu.be/-3_FkK_Fsfk?t=227 = As Perp mentions, every special ability should be able to proc weapon affects, although Sap was never able to proc damaging abilities, same goes for Gouge.
And again, not being able to proc crippling poison, makes playing rogue in Battlegrounds feel horrendous. Your main objective in WSG for example, is to keep everyone crippled, lock down healers and keep the EFC pinned. One of your most important objectives, now doesn't work as efficient, as proccing poisons on multiple targets is near impossible like this.
- This would also apply, to say an Enchancement shaman with Windfury; Getting a Windfury proc after an auto-attack, and then the Windfury Proc, proccing the Earthshaker effect - Every ability that works similar to this, should work, so paladin procs that work in a similar fashion, aswell as Frostbite weapon etc. Alot of examples I could fill this post out with. (Just to throw a last example, I'm fairly certain scatter shot should be able to proc improved hawk)

This isn't even remotely close to something like the debate about Gouge > Restealth not being blizz-like (Which kind of works anyway)

There's alot of rogue stuff that i've complained about, dating back to up to over a year ago, which still aren't fixed/optimized.
Things like
- Weapon procs like I am mentioning now
- Pet aggro in stealth (Although blizz-like, should not be)
- Combo points dissapearing after a new target is aquired, which hinders cleave fights in raids, and also punishes you for missclicks. (Which is also blizz-like, but should not be and was fixed later)
- Also want to note, that stealth values here are abseloutely fucked, which should be buffed to be up-to-par with other servers/clients

**Comment by kronos** [comment]
I believe I am not the kronos you need.
