### ISSUE TITLE
Goblin Radio KABOOM-Box X23B76 item missing cooldown info / tooltip on hover and in bags

### ISSUE THREAD

**Issue by Slimthegrim** [slowtorta/turtlewow-bug-tracker#3098]
**Please, provide a clear description what the bug is:**
The item Goblin Radio KABOOM-Box is missing its cooldown and item duration information. Also missing during item mouseover in bags.

**Steps to reproduce the behavior with as much detail as possible:**

1. Be the be$t AND have a Goblin radio ready to use.
2. Use it.
3. Try to use it again, see that spell isn't ready, the item's on cooldown like any other usable item / trinket.
4. Observe issue 1: no tooltip / item cooldown displayed after use on mouseover, even though receive red error: "Spell not ready" on use again.
5. Observe issue 2: Item tooltip also missing duration and cooldown information once you trigger cooldown.

![image](https://user-images.githubusercontent.com/110629519/228025817-b1648566-d9e6-4124-96b3-edaa15a1898e.png)

**IDs of affected creatures, items, quests or spells with a link to the relevant page:**

[Item](https://database.turtle-wow.org/?item=10585)

**Expected behavior. Describe how it should work:**
When you use items with cooldowns, the cooldown is stated once its triggered in the item sprite box in your bags. Also would expect the item's duration and the items' cooldown to be presented in the tooltip like is standard for all other items.

**Comment by twowTurtReynolds** [comment]
![image](https://github.com/slowtorta/turtlewow-bug-tracker/assets/151180101/f1c02110-0d5a-4d50-877b-e44f837a2156)
