### ISSUE TITLE
Auction searching speed

### ISSUE THREAD

**Issue by QuadrozZz** [slowtorta/turtlewow-bug-tracker#3099]
At the moment, scanning the auction with addons (the aux-addon for example) is too slow. One page is scanned for five seconds. It takes a minute to scan twelve pages. It is too long. If I understand correctly, this is due to the five second break between clicking the "Next Page" button in the auction window. If you could reduce the delay between "Next Page" clicks to at least one second, that would be great. This would save a lot of time. The population on the server is growing, which cannot but rejoice, of course, there are more lots at the auction, scanning takes longer.
I hope you take it into account. And make scanning auction lots faster.

**Comment by Gurky-Turtle** [comment]
I believe this is intended due to the strain it puts on the server.

**Comment by QuadrozZz** [comment]
> I believe this is intended due to the strain it puts on the server.

I understand it. But I think that in the case of an auction, you can sacrifice a little performance and find another way to compensate. For example, make a small delay for requests in the "Who" window. But you still need to increase the search speed at the auction, I think.

> Keep it slow, SLOW AND STEADY. Not a fan of people using auction house addons. They clog the AH with single-stack items at cheaper prices than bulk pricers. Its just not right

Players will use addons like aux, anyway, who uses them. In order to create an auction lot for one piece, you do not need to wait for the item to be fully scanned. But to find the cheapest lot you need. Single-stack items selling is not always bad. And single-stack items more higher than than bulk pricers. As you told.

https://imgur.com/3TcDPVi
https://imgur.com/knsHi4Z

**Comment by QuadrozZz** [comment]
> i scan the ah everyday, yes it takes alot of time. but it also givs alot of advantages. i am agaisnt reducing the time needed. it opens the flood gates for ah botting

"it opens the flood gates for ah botting" - How does this relate to auction speed-up?

On the contrary, the speed of the auction is less important for bots. The bots seem to work autonomously, if I understand correctly. The bot is launched and it performs its tasks. Longer, but he also doing it. While a person has to sit and wait fifty seconds while an auction searches for ten pages of cheap linen cloth, this is just an example. And this is only one item that you need to buy or sell. And if there are dozens in bags? This takes a huge amount of time. Which could be reduced.

Take note and think about it. I don't want to harm the server in any way. I just want to improve the quality of life of the players.

**Comment by QuadrozZz** [comment]
Those people who rarely use the auction are unlikely to feel a big difference. But for those who use regularly, this will be good news. But you can always return the changes to the previous values. In this case, I don't think it will be very difficult to do.

**Comment by QuadrozZz** [comment]
Would be great to see the answer from Dev's.
