### ISSUE TITLE
Nekrum's Medallion doesn't drop

### ISSUE THREAD

**Issue by Pleeplaa** [slowtorta/turtlewow-bug-tracker#31]
According to another person on the Discord Support it has dropped for them, but my entire party of 5 had no drops for the Nekrum's Medallion quest in Zul'Farrak, Nekrum Gutchewer did not drop a single medallion for any of us.

I am unsure why this had happened, but I do have screenshots of my character over his corpse.

My in game character name is Freyacloud, a High Elf Priest.

**Comment by slowtorta** [comment]
Are you sure your group wasn't a raiding group?

**Comment by Pleeplaa** [comment]
This was a 5man, non raid group.

**Comment by slowtorta** [comment]
Thanks for reporting it. It'll be fixed on the next server restart. Make sure to clear your WDB folder.
