### ISSUE TITLE
Twinking Glyph active at all times

### ISSUE THREAD

**Issue by Vikkyne** [slowtorta/turtlewow-bug-tracker#310]
**Please, provide a clear description what the bug is:**
Unlike the Diplomacy and Exhaustion glyphs, the Twinking glyph is active/in force whether it is in your bank or your bags/keyring.  If in the bank, the Diplomacy and Exhaustion glyphs are **not activated** for the player; Twinking is always activated.

**Steps to reproduce the behavior with as much detail as possible:**

1. Have exhaustion or diplomacy glyph in bank, attempt to use (they will not activate or have proper effect); put them in your bags/keyring, they will act properly

2. Have Twinking glyph in bank, kill mob or turn in quest, no reward will accrue to the character (it will report the XP, but the bar will not advance)

**IDs of affected creatures, items, quests or spells with link to the relevant page:**

Object: https://database.turtle-wow.org/?object=50008

**Expected behavior. Describe how it should work:**

Glyphs (aside from Turtle & HC) should be inactivated when in bank; the Twinking glyph overrides this and is **always** in force if anywhere in the player's inventory.

**Comment by slowtorta** [comment]
Thank you. It'll be fixed on the next server update.
