### ISSUE TITLE
Transmog issues

### ISSUE THREAD

**Issue by Shoc9524** [slowtorta/turtlewow-bug-tracker#3102]
- When durability changes on gear,  (after repair, or when your gear gets damaged in fight, or after death) transmogged gear changes back to its original look. Only in case of armors. You can temporaly fix this, by re-equiping them.

- When transmogging weapons into different type (sword into mace for example) the weapon keeps its base weapons original sounds (sword sounding mace).

- Maybe make tokens a bit more accessable? -- optional, personal preferrence. i understand why is it like this atm --

**Comment by slowtorta** [comment]
We're aware of all the issues related to transmog. There's no point to fix single flaws in the current system, as it must be reworked all together in the future.

**Comment by Shoc9524** [comment]
> We're aware of all the issues related to transmog. There's no point to fix single flaws in the current system, as it must be reworked all together in the future.

Its like this for a very long time now :( And in raids it causes complications, causing ppl to crash, and get teleported to the start of the raid. Any ETA on that? Or is it just a plan atm? Thanks for the reply.

**Comment by slowtorta** [comment]
We do not have any ETA. Hopefully around the summer 🌞 it's not a promise.

**Comment by twowTurtReynolds** [comment]
Duplicate of https://github.com/slowtorta/turtlewow-bug-tracker/issues/1400
