### ISSUE TITLE
Shadowcaller axe "use" effect

### ISSUE THREAD

**Issue by dropsera** [slowtorta/turtlewow-bug-tracker#3104]
**Please, provide a clear description what the bug is:**

While maybe intended, the Shadowcaller Axe effect is not a on-hit proc, but a use effect with a cooldown of 10 minutes, which makes little sense and has even less usability. Is such behavior correct? Seems underwhelming for a rare 49lvl weapon.

**Steps to reproduce the behavior with as much detail as possible:**

1.Press Shadowcaller Axe
2. Bathe in glorious 75 shadow damage once in 10 minutes

**IDs of affected creatures, items, quests or spells with a link to the relevant page:**

Item: https://database.turtle-wow.org/?item=60616

**Expected behavior. Describe how it should work:**
It probably should be a "on-hit" effect.

**Comment by balakethelock** [comment]
It has a 30 yard range, technically it can work as a ranged pull in its current state and the game is full of much stronger on-hit weapons so there's no reason to change it.

**Comment by dropsera** [comment]
> I think this is a, suggestion and not a bug.
> 
> The use on the custom axe works even if it's bad

Don't see the way of knowing if intended or not without making a bug report. It might be an oversight like that one shield that game considered as an "held in off-hand".

**Comment by slowtorta** [comment]
@Dragunovi

**Comment by slowtorta** [comment]
Intended :)
