### ISSUE TITLE
I can't complete the quest

### ISSUE THREAD

**Issue by gumpyfo** [slowtorta/turtlewow-bug-tracker#3105]
**Please, provide a clear description what the bug is:**
There is no way to complete the Warleader Tamukar quest in Dessole from Gelkis Clan Cantaur while having a friendly reputation with Gelkis Clan Cantaur. I can't interact with this NPC in absolutely no way.

**Steps to reproduce the behavior with as much detail as possible:**

1.Took 2 quests from Warleader Temukar.
2. I have fulfilled all the necessary conditions of these quests.
3. Having come to this NPC, I can't hand over the quest to him, since I can't interact with him in any way, nor right-clicking in any way.
4. I noticed that the other members of the Gelkis clan are friendly to me, but I can cast damage spells on them.
5. Also can't interact with Gelkis Quartermaster
6. I wrote a ticket to the support service, they told me to clean the WDB folder, but it didn't help. When contacting me again, I was told to contact bug tracker.

**IDs of affected creatures, items, quests or spells with a link to the relevant page:**

NPC: https://database.turtle-wow.org/?npc=61045#drop
Item: https://database.turtle-wow.org/?item=7069
Quest: https://database.turtle-wow.org/?quest=40631
           https://database.turtle-wow.org/?quest=40632

**Expected behavior. Describe how it should work:**
![2023-03-28_21-49-23](https://user-images.githubusercontent.com/129215507/228338599-6f69d2eb-9b66-4934-81e6-5307bc97b6eb.png)
![2023-03-28_21-50-15](https://user-images.githubusercontent.com/129215507/228338610-4aea913e-24ee-4877-b5da-85473a8f283c.png)
![2023-03-28_21-50-50](https://user-images.githubusercontent.com/129215507/228338612-781b416e-eb86-4913-b0cd-7e66d9db366a.png)

**Comment by slowtorta** [comment]
Please make sure you don't have AtWar flag set with this faction in your reputation tab. It's working as intended :)

**Comment by gumpyfo** [comment]
Guys, thank you very much, I'm sorry that you had to solve such a stupid problem because of my stupidity. God grant you good health!
