### ISSUE TITLE
Hunter Pets should not Parry attacks

### ISSUE THREAD

**Issue by Jeradooka** [slowtorta/turtlewow-bug-tracker#3108]
**Please, provide a clear description what the bug is:**
Hunter pets have a chance to Parry in PVP, even though they do not have a weapon (Druid bears/cats cannot parry). They should not be able to Parry, since they do not have a weapon.

**Steps to reproduce the behavior with as much detail as possible:**

1. Attack hunter pet 100 times.
2. Notice how many Parry's happen.

**IDs of affected creatures, items, quests or spells with a link to the relevant page:**

Not sure what to put here...

**Expected behavior. Describe how it should work:**
The attack should be dodged, miss, crit, (or block if turtle pet). The pet should not be able to Parry an attack.
![Capture](https://user-images.githubusercontent.com/41565304/228366952-94f5f758-db1e-40dc-9f26-49d666128764.PNG)

**Comment by burner1024** [comment]
All NPC beasts can parry, though.
