### ISSUE TITLE
Event: Ostarius

### ISSUE THREAD

**Issue by Sringaram** [slowtorta/turtlewow-bug-tracker#3110]
The script will go into cooldown if the boss despawns through a wipe, bug, evading, etc.
This basically gives the server a single clean attempt per week which is ridiculous.

Expected behavior. Describe how it should work:
The cooldown is triggered once the boss is defeated. Upon a wipe/bug/evade bug I assume all the portals should despawn along with the boss, making it possible to trigger the event again through the pedestal.

**Comment by slowtorta** [comment]
Will be fixed in the next update.
