### ISSUE TITLE
Magram Clan Centaur quests bugged in Desolace

### ISSUE THREAD

**Issue by Hookky665** [slowtorta/turtlewow-bug-tracker#3113]
**Please, provide a clear description what the bug is:**

I cannot return these two quests to Warcaller Dekshar or even talk to Jochi next to him in Magram Village. I was able to talk to them before, but not anymore. Also, I cannot talk with the quartermaster who sells faction items. I was also able to do that.

I am friendly with Magram Clan Centaurs 1860 / 6000.

I deleted WDB folder and it did not help.

![image](https://user-images.githubusercontent.com/129312359/228599299-4ef645b8-3f09-4f67-833f-c7fea25795f3.png)

**Steps to reproduce the behavior with as much detail as possible:**

1. Trying to return quests in Magram village

**IDs of affected creatures, items, quests or spells with a link to the relevant page:**

NPC: Warcaller Dekshar, Jochi
Item: https://database.turtle-wow.org/?item=
Quest: Raiding The Lesser Tribes, War for Food
Spell: https://database.turtle-wow.org/?spell=
Object: https://database.turtle-wow.org/?object=

**Expected behavior. Describe how it should work:**

**Comment by slowtorta** [comment]
Please open your reputation tab, locate the faction of this NPC, click on it, and make sure to remove the <At War> flag that's preventing you from opening the dialog window.
