### ISSUE TITLE
Starfire still broken, randomly losing 0.5 cast time reduction.

### ISSUE THREAD

**Issue by DraxerTABC** [slowtorta/turtlewow-bug-tracker#3114]
**Please, provide a clear description what the bug is:**
Starfire just randomly gets 0.5 cast time reduction remove, so it goes back to being 3.5s cast time
**Steps to reproduce the behavior with as much detail as possible:**
No idea, it just happens during dungeons or raids. Might be too many casts at once or maybe the server forgets that you should have the talent active. It might mistake Nature Grace being used alongside with the cast time reduction to null it?

**IDs of affected creatures, items, quests or spells with a link to the relevant page:**

Starfire: https://database.turtle-wow.org/?spell=25298

Both Nature's Grace's just in case: 
https://database.turtle-wow.org/?spell=16886
https://database.turtle-wow.org/?spell=16880
(Noticed the database says about Nature's Grace that it reduces by 1 second, when it should be 0.5 seconds, that might be the issue?)
**Expected behavior. Describe how it should work:**
Starfire should not lose the 0,5 cast time reduction. With Talents it should be 3 second cast time and 2.5 second cast time while Nature's Grace is active.

**Comment by ConcernedTurtler** [comment]
time to switch to wrath it does more damage anyway

**Comment by ConcernedTurtler** [comment]
ah I didn't know about curse of shadows.

**Comment by Muigin** [comment]
Cannot reproduce on current version.
