### ISSUE TITLE
[Paladin] Zandalarian hero charm

### ISSUE THREAD

**Issue by UsernameChad42069IsNotAvailable** [slowtorta/turtlewow-bug-tracker#312]
Zandalarian hero charm reduces in spell power with each spell cast.
However it also reduces in spell power with each hit from Seal of Righteousness, thats not how it should work.
Consecration doesn't reduce its spell power with each tick after it has been casted once, Seal of Righteousness melee hits aren't considered "casting a spell" therefore this is a bug.

https://database.turtle-wow.org/?item=19950

**Comment by itswicky** [comment]
I'm not 100% certain on this, but there is a flag in spell.dbc along the lines of 'cannot proc' which prevents a spell from triggering other effects. I don't know if SoR is meant to trigger other effects, so I'm not sure this would be a proper solution.

**Comment by redmagejoe** [comment]
For the record, Seal of Righteousness is working as intended on 1.12 by causing melee attack procs. This was only changed in patch 2.1.0. https://wowpedia.fandom.com/wiki/Seal_of_Righteousness#Patch_changes

Whether that aids in addressing this ticket or not, I do not know.

**Comment by redmagejoe** [comment]
Looked into this further. See https://wowpedia.fandom.com/wiki/Zandalarian_Hero_Charm#Patch_changes and note that Seal of Righteousness is a "melee and ranged abilities and spells which do non-physical damage"

Working as intended. Can be closed.
