### ISSUE TITLE
NPC: Farseer Yharg'osh

### ISSUE THREAD

**Issue by arneb23** [slowtorta/turtlewow-bug-tracker#3127]
**Please, provide a clear description what the bug is:**
Farseer Yharg'osh in Bloodfist Point, Azshara, is not targetable or interactible.
Attempting to target him will give you the auditory "poke" dialogue ("Speak, friend" or "Lok'tar" or "Thrall hall!" etc) but nothing will show up as your currently-selected target, and no text dialogue window shows up.
Furthermore, despite having NPC Names checked, he does not have a name showing above his head at all, though he does have the yellow question mark of a quest to be turned in above his head.
Below: Yharg'osh with a grunt; his name is not visible.
Below that: An unrelated, non-bugged quest NPC with both question mark and name visible. Yharg'osh, being bugged, lacks the latter.
![image](https://user-images.githubusercontent.com/129344303/228698042-b2789f4b-67c5-4c50-a14e-dd35cd9c20df.png)
![image](https://user-images.githubusercontent.com/129344303/228698248-064fecc0-20fa-4ac5-8595-a5441473f39b.png)

(After doing the delete-WDB and disable-addons things, I had a GM show up to try to unstick him. Two forced deaths and one mild wandering session where he walked to the crates behind him and started staring at them later, he still remained untargetable. They also reported having the same issue as me—i.e., Yharg'osh being untargetable is not a clientside issue.)

**Steps to reproduce the behavior with as much detail as possible:**

1. Left or right click on Yharg'osh.

**IDs of affected creatures, items, quests or spells with a link to the relevant page:**

NPC: https://database.turtle-wow.org/?npc=92197
Quest: https://database.turtle-wow.org/?quest=40292

**Expected behavior. Describe how it should work:**
I walk into the hut he's chilling in. He looks at me when I right-click him, goes "oh, my quest items," takes them, and gives me EXP for it.

**Comment by twowTurtReynolds** [comment]
He's all good now.
![image](https://github.com/slowtorta/turtlewow-bug-tracker/assets/151180101/971ea693-6b68-4a03-b8f8-780e1463b266)
