### ISSUE TITLE
Orc shaman racial Feral Spirit bugged 

### ISSUE THREAD

**Issue by dekr6** [slowtorta/turtlewow-bug-tracker#3128]
The level 40 Orc shaman racial feral spirit seems to not work when attacking enemy players. When i summon the feral spirits they do not attack the enemy player and just stand next to my character. I have tried pet attack macros but nothing seems to work. They work fine against PvE mobs but do not work against enemy players.

**Comment by Jeradooka** [comment]
My spirit wolves are also bugged and do not attack.

**Comment by jameyboor** [comment]
Fixed on next server update.
