### ISSUE TITLE
Tar Lurkers are uninterruptable

### ISSUE THREAD

**Issue by trumpetx** [slowtorta/turtlewow-bug-tracker#313]
**Please, provide a clear description what the bug is:**

**Steps to reproduce the behavior with as much detail as possible:**

1. Find a Tar Lurker in Un'Goro
2. Kick Entangling Roots or Black Sludge
3. Watch the cast stop
Expected Results:
4. Cast stops
Actual Results:
4. Debuff/spell is applied anyway

![sludge_compressed](https://user-images.githubusercontent.com/115343/133946828-4ad09e4d-afec-4050-9ec0-0ef1b7f33d3c.gif)

**IDs of affected creatures, items, quests or spells with a link to the relevant page:**

https://database.turtle-wow.org/?npc=6518

**Expected behavior. Describe how it should work:**
I expect that I can kick (and interrupt) spells cast by Sludge Lurkers

**Comment by GrenderG** [comment]
Please provide evidence showing that this is not working as intended. Thanks.

**Comment by trumpetx** [comment]
> Please provide evidence showing that this is not working as intended. Thanks.

If you watch the video, the cast is interrupted (cast bar stops) indicating that the cast was interrupted.  This could be an issue with the 1.12.1 pfUI addon, but in my experience, non-interruptable spells simply keep casting denoting the difference.

I did a little googling, and it seems that the spell is not interruptible on the classic servers according to a 2019 wowhead comment.  The spell itself seems to be different in retail versions so that it's not nearly as long.  All I have really as "evidence" is that the cast bar stops when the kick is performed.

**Comment by Kangaroux** [comment]
Possibly related to #267

**Comment by Kangaroux** [comment]
@trumpetx I've noticed some strange behavior before with pfUI's cast bars. It tends to make some assumptions which can cause some visual bugs. One of those assumptions might be that all spells with a cast time are interruptible.

**Comment by trumpetx** [comment]
@Kangaroux @GrenderG - I just checked on classic (tbc) and this spell is uninterruptible there; however, I've noticed a bunch of other spells that are also not interruptible (and interruptible on classic)  #267 among them.  I'll open a new ticket for the Chillwind Chimeras in Winterspring.
