### ISSUE TITLE
Pull Animation

### ISSUE THREAD

**Issue by Mixxl** [slowtorta/turtlewow-bug-tracker#3131]
For some reason, I cannot pull my weapons. The animation is there, the character grabs behind bis back/next to his hips,  but the game doesn’t show the weapons/whatever is held in your hand. I experienced this on my dwarf and on my human.

**Comment by slowtorta** [comment]
Please make sure your client is correctly updated and doesn't have any additional modifications. This issue isn't present in our client build.
