### ISSUE TITLE
Tailor Master

### ISSUE THREAD

**Issue by qbick205** [slowtorta/turtlewow-bug-tracker#3133]
**Please, provide a clear description what the bug is:**
In Aliance, NPC Timothy Worthington, trying learn "Artisan Tailor 225 - > 300 skill master, when clicking, nothing happen, relog and delete WDB not helped, tryed learn something else from this trainer, nothing happen too.
**Steps to reproduce the behavior with as much detail as possible:**

1.Relog
2. Delete WDB
3. NPC wont nothing learn

**IDs of affected creatures, items, quests or spells with a link to the relevant page:**

NPC: https://database.turtle-wow.org/?npc=11052
Item: Learning skill
Quest: Its not a quest
Spell: Its not a spell
Object: NOC

**Expected behavior. Describe how it should work:** When clicking on, he must learn character to new skill.

**Comment by slowtorta** [comment]
Working as intended. Please try to disable the addons and delete your WDB folder while your client is completely closed.
![image](https://user-images.githubusercontent.com/66763404/229310254-25c5c9d9-c691-4f8f-95c0-a7b605abfd9f.png)
