### ISSUE TITLE
Messages are not sent to the chat channels

### ISSUE THREAD

**Issue by KaneiJones** [slowtorta/turtlewow-bug-tracker#3139]
**Please, provide a clear description what the bug is:**

**Steps to reproduce the behavior with as much detail as possible:**

1. Open any chat channel.
2. Try to send a message
3. Many times, the message will not be sent. No matter what words it has, nor the length,

**It is an error that did not occur to me at the beginning. But the more time progresses, the more messages don't be sent to the chat channels. This does not happen when I whisper to another player or speak using /s or /y. I have tried to delete the WDB folder and the chat-cache files. I even reset the interface settings, but nothing worked.**

**Comment by Shonatan** [comment]
having this same issues

**Comment by slowtorta** [comment]
Please submit a ticket in-game. You've been probably muted by the automatic chat filter. GMs will help you to resolve this. Tag me here if the issue persists afterward.
