### ISSUE TITLE
aq20 bosses and enemies have a lot of resist compared to other raids.

### ISSUE THREAD

**Issue by ConcernedTurtler** [slowtorta/turtlewow-bug-tracker#3140]
Maybe it's intentional but I think it's a little odd that the bosses in aq20 have so much magic/elemental resistance compared to bosses in other raids.  The highest boss resist in aq40 for example is 75 but bosses and even some enemies in aq20 have up 135. 

Just something I think should be looked into.

**Comment by balakethelock** [comment]
Aq40 resistance is bugged too, all raid mobs and bosses in vanilla have between 0 and 15 reducible resistance UNLESS they are especially resistant to that school, in which case they have 100 or more.

For example, KT has 100 shadow resist but 15 resist of the other schools. AQ40 and AQ20 are the only places where every mob has more than 75 resist to every school and there's no classic wow source that says they have that, only private servers.

**Comment by balakethelock** [comment]
https://www.reddit.com/r/classicwow/comments/k23tno/decrease_the_magical_resistance_of_your_spell/gdt7aqm/

**Comment by ConcernedTurtler** [comment]
There's a macro that tell's you how much resist an enemy/boss has 
/script u=UnitResistance y="target" a=u(y ,0) h=u(y ,1) f=u(y ,2) n=u(y ,3) fr=u(y ,4) s=u(y ,5) z=u(y ,6) SendChatMessage(UnitName(y).." has "..a.." Armor, "..h.." HR, "..f.." FR, "..n.." NR, "..fr.." FrR, "..s.." SR and "..z.." AR.", SAY)

not sure if it works in classic tho if someone wanted to check what resists bosses are supposed to have.

**Comment by ConcernedTurtler** [comment]
> Aq40 resistance is bugged too, all raid mobs and bosses in vanilla have between 0 and 15 reducible resistance UNLESS they are especially resistant to that school, in which case they have 100 or more.
> 
> For example, KT has 100 shadow resist but 15 resist of the other schools. AQ40 and AQ20 are the only places where every mob has more than 75 resist to every school and there's no classic wow source that says they have that, only private servers.

75 doesn't bother me because curse of elements/shadows reduces that to 0 with the exception of nature resist. So the only losers are Moonkins that use wrath over starfire and Elemental Shamans.

**Comment by balakethelock** [comment]
It works, and the addon aDF can tell, and the database has it all. The database itself is wrong compared to classic, the fix must be implemented at that level.

**Comment by balakethelock** [comment]
Full list of affected npcs is here
https://www.wowhead.com/classic/zone=3429/ruins-of-ahnqiraj#npcs
https://www.wowhead.com/classic/zone=3428/ahnqiraj#npcs
Every mob with 75 resist should have 15 resist, the ones with more (135) stay at 135

**Comment by ConcernedTurtler** [comment]
how do you see resist on wowhead?

**Comment by balakethelock** [comment]
You can't on wowhead, I meant turtle wow's custom database. For example, Fankriss https://database.turtle-wow.org/?npc=15510 in the database and ingame has 75 resists, when it should have 15.

**Comment by balakethelock** [comment]
@ratkosrb Thank you <3.
Some npc ids have missed the bug fix
https://database.turtle-wow.org/?npc=15517
https://database.turtle-wow.org/?npc=15589
https://database.turtle-wow.org/?npc=15725
https://database.turtle-wow.org/?npc=15726
https://database.turtle-wow.org/?npc=15802
https://database.turtle-wow.org/?npc=15728
https://database.turtle-wow.org/?npc=15334
