### ISSUE TITLE
Missing AH money, and ability learned

### ISSUE THREAD

**Issue by ellohello** [slowtorta/turtlewow-bug-tracker#3142]
**Please, provide a clear description what the bug is:**

I recently made over 90S in my auction house trades, when receiving the letter and clicking to accept the money, things seemed to work. But when I opened up my bag, the money wasn't there. In addition, my friend sent me a spell book to train my first aid silk bandages. After clicking to learn and waiting for the bar to complete, the skill isn't in my first aid abilities. This is all important as I'm quite low level and everything matters.

I've also submitted a donation of 36Euro and have yet to receive the credits.

Account: ellohello
Email: thethomasbrady@gmail.com

**Steps to reproduce the behavior with as much detail as possible:**

1.
2. 
3. 

**IDs of affected creatures, items, quests or spells with a link to the relevant page:**

NPC: https://database.turtle-wow.org/?npc=
Item: https://database.turtle-wow.org/?item=
Quest: https://database.turtle-wow.org/?quest=
Spell: https://database.turtle-wow.org/?spell=
Object: https://database.turtle-wow.org/?object=

**Expected behavior. Describe how it should work:**

I get my money, I'm able to use the ability that I was trained in

**Comment by slowtorta** [comment]
Please sumit a ticket in-game and GMs will assist you. This isn't kind of an issue we can help here in the bug-tracker :)
