### ISSUE TITLE
Hunter combat bug

### ISSUE THREAD

**Issue by Allemonz** [slowtorta/turtlewow-bug-tracker#3147]
When pet did killing blow on normal mobs (not pvp) i still remain in combat for 5 sec, didn't happened when i do killing blow and in dungeons its even bigger problem because after any pack of trash i remain in combat for 5 sec.
Race High Elf.
Pet Broken tooth.

**Comment by Allemonz** [comment]
@ratkosrb why here is no comments why topic is closed? Fixed? Intended? How i can play on character and always think is this a bug or what?

**Comment by ratkosrb** [comment]
![Untitled](https://user-images.githubusercontent.com/35845488/229323218-ed1b6c44-bc1f-4b91-9ac4-6d852c33440d.jpg)

When you see that the rectangle which says Closed is in purple color, and there is a notification saying it's "closed as completed", it means we've fixed it internally, and you just have to wait for the server to be updated.
