### ISSUE TITLE
Shadowform Visual Bug

### ISSUE THREAD

**Issue by SinisterRewind** [slowtorta/turtlewow-bug-tracker#3149]
**Please, provide a clear description what the bug is:**

When I mount up or take a flight path when Shadowform is active, Shadowform loses it's shadow effect, retaining only it's transparency and shadowy whisps from the ground. I'm not sure if anything else will cause this to happen, as I've only experienced it with mounting and taking a flight path.

![shadowform bug 1](https://user-images.githubusercontent.com/59970220/229338866-b0a6c408-6e63-431d-96bf-cc2465a59bdb.PNG)
![shadowform bug 2](https://user-images.githubusercontent.com/59970220/229338869-1fc68659-ce1c-4f39-bd22-52ca4b7c34be.PNG)

**Steps to reproduce the behavior with as much detail as possible:**

1. Activate Shadowform.
2. Mount up or Take a flight path. It does not seem to matter what mount or where you fly.

**IDs of affected creatures, items, quests or spells with a link to the relevant page:**

Spell: https://database.turtle-wow.org/?spell=15473

**Expected behavior. Describe how it should work:**

Shadowform should retain it's shadowy effect when mounting or taking a flight path.

**Comment by slowtorta** [comment]
This is the original's game bug (or intentional behavior) introduced on the release of this game. We cannot do much about this one.
