### ISSUE TITLE
Died to fall damage on flat ground.

### ISSUE THREAD

**Issue by sonpansatan** [slowtorta/turtlewow-bug-tracker#315]
When I was riding my turtle mount, I died to fall damage despite being on flat ground.

1.Mount on the turtle mount.
2. Go to Ashenvale at 17.8, 23.8

I should not die to fall damage. but I do so anyway despite the ground being flat.

**Comment by sonpansatan** [comment]
Tried to reproduce but didn't work. Also could not be rezed since body was "out of range"

**Comment by slowtorta** [comment]
To reprodude this issue run into the mentioned coordinate from a long distance without jumping or changing your Z coord any other way.
