### ISSUE TITLE
you can blink under the mine on Alah'Thalas map

### ISSUE THREAD

**Issue by frostyfyre** [slowtorta/turtlewow-bug-tracker#3151]
**Please, provide a clear description what the bug is:**

You can go under textured map with blink in a specific spot in the game.

**Steps to reproduce the behavior with as much detail as possible:**

1. Be a mage and have the spell Blink (this one works on 100% of the times i tried on my mage)
2. Go to Alah'thalas and face the mine entrance (just in front or near the npc called Melkolar Dawnrise is fine)
3. Blink and notice 

**IDs of affected creatures, items, quests or spells with a link to the relevant page:**

NPC: https://database.turtle-wow.org/?npc=
Item: https://database.turtle-wow.org/?item=
Quest: https://database.turtle-wow.org/?quest=
Spell: https://database.turtle-wow.org/?spell=
Object: https://database.turtle-wow.org/?object=

**Expected behavior. Describe how it should work:**

The expected behavior should be to stay above the ground when you blink.
![WoWScrnShot_040223_160439](https://user-images.githubusercontent.com/97914280/229354703-5af51518-f04b-41e9-a544-b94a105de401.jpg)

**Comment by slowtorta** [comment]
Fixed on the next client update.
