### ISSUE TITLE
ZG Shoulder enchant

### ISSUE THREAD

**Issue by d-u-b** [slowtorta/turtlewow-bug-tracker#3152]
ZG Shoulder enchant, for example https://database.turtle-wow.org/?item=20077 can enchant without exalted reputation, a lot of peoples are use it on 60 lvl and **19 lvl twinks!!!** Hope you are fix it soon, thank you

**Comment by ratkosrb** [comment]
How do you obtain the enchant if you are not exalted with ZG, since the quest that rewards them requires you to be exalted?

**Comment by slowtorta** [comment]
@ratkosrb related: https://github.com/slowtorta/turtlewow-bug-tracker/issues/3083
