### ISSUE TITLE
Lordaeron soldiers spawning during phase 1 of Kel'thuzad encounter

### ISSUE THREAD

**Issue by afizzler** [slowtorta/turtlewow-bug-tracker#3153]
[
![image](https://user-images.githubusercontent.com/87098931/229373175-ccb52b6f-2e42-4de7-bcd6-377c11498dba.png)
](url)

I do not think lordaeron soldiers should be spawning during the fight. 

Lordaeron Soldier NPC: https://database.turtle-wow.org/?npc=17647

**Comment by ratkosrb** [comment]
WTF, nowhere in the script does it spawn this npc :O
