### ISSUE TITLE
Seed of Life quest

### ISSUE THREAD

**Issue by Keezah** [slowtorta/turtlewow-bug-tracker#3154]
**Please, provide a clear description what the bug is:**
When I go to turn in the Seed of Life quest in Moonglade, I get no option to open a dialogue box with Keeper Romulo to turn in, only the sword mouse icon to attack. 
**Steps to reproduce the behavior with as much detail as possible:**

1. Tried turning in multiple times after multiple server restarts. I get the same result.
2. 
3. 

**IDs of affected creatures, items, quests or spells with a link to the relevant page:**

NPC: https://database.turtle-wow.org/?npc=
Item: https://database.turtle-wow.org/?item=
Quest: https://database.turtle-wow.org/?quest=
Spell: https://database.turtle-wow.org/?spell=
Object: https://database.turtle-wow.org/?object=

**Expected behavior. Describe how it should work:**
I should have the ability to open a dialog box with Keeper Romulo to turn in the quest instead of attacking him.

**Comment by ratkosrb** [comment]
You must be at war with Cenarion Circle. Press U to open the reputation tab and uncheck At War for that faction.
