### ISSUE TITLE
Devilsaur pathing/aggro bug

### ISSUE THREAD

**Issue by Bovrilmatter** [slowtorta/turtlewow-bug-tracker#3156]
Having an issue with devilsaur running away at a fast speed with no target and then coming back to attack a player when the mob is nowhere near the player.

I cannot reproduce this right now as I am hardcore and don't want to die the reason this was such an issue to me is the fact I was hardcore. I will try to reproduce this with video evidence at 60 but I have confirmed the issue with a couple of other players.

NPC: hhttps://database.turtle-wow.org/?npc=6498

Expected the mob to attack from an aggro distance and not to run at a very fast speed with no target in the first place

EDIT: I have also seen video evidence of this issue on another report and it was basically the exact same location I had the issue including the mob pathing through a tree.

https://github.com/slowtorta/turtlewow-bug-tracker/issues/3116

**Comment by Bovrilmatter** [comment]
I have also seen video evidence of this issue on another report and it was basically the exact same location I had the issue including the mob pathing through a tree.

**Comment by slowtorta** [comment]
https://github.com/slowtorta/turtlewow-bug-tracker/issues/3116
