### ISSUE TITLE
Gordok inner door key disappearing

### ISSUE THREAD

**Issue by Ulrick2b** [slowtorta/turtlewow-bug-tracker#3157]
**Please, provide a clear description what the bug is:**
The gordok inner door key disappears if the person carrying it dies or leaves the instance by any means.
**Steps to reproduce the behavior with as much detail as possible:**

1.Get the Gordok inner door key on Guard Mol'dar
2.Die or leave the instance
3.The key disappears from the inventory

**IDs of affected creatures, items, quests or spells with a link to the relevant page:**

NPC: https://database.turtle-wow.org/?npc=
Item: https://database.turtle-wow.org/?item=https://database.turtle-wow.org/?item=18268
Quest: https://database.turtle-wow.org/?quest=
Spell: https://database.turtle-wow.org/?spell=
Object: https://database.turtle-wow.org/?object=

**Expected behavior. Describe how it should work:** The key should stay in the inventory to not have to rerun the WHOLE DAMN THING WHEN I'M JUST TRYING TO LOOT THE MUGGER'S BELT FFS IT'S BEEN SO MANY TRIES AND IT BUGS HALF THE TIME.

**Comment by slowtorta** [comment]
This is intended behavior. The key is a part of the dungeon event and it's map bound.
