### ISSUE TITLE
Benedict's Chest respawn timer

### ISSUE THREAD

**Issue by QuadrozZz** [slowtorta/turtlewow-bug-tracker#3158]
https://www.wowhead.com/classic/object=3239/benedicts-chest
Bug: Long respawn timer.
Should appear immediately after use.

**Comment by QuadrozZz** [comment]
Rejected or accepted?

**Comment by cyaohiri** [comment]
If it's closed with a comment, it's been fixed.

**Comment by cyaohiri** [comment]
That was a typo on my part; I meant "without"!

**Comment by QuadrozZz** [comment]
@slowtorta https://www.youtube.com/live/3BnCsTaszpk?feature=share&t=7097 btw
