### ISSUE TITLE
Quest Stranglethorn Fever bugged

### ISSUE THREAD

**Issue by tokurwacojestdostepne** [slowtorta/turtlewow-bug-tracker#3162]
**Please, provide a clear description what the bug is:**
Can take quest, but unable to speak with witch doctor

**Steps to reproduce the behavior with as much detail as possible:**

1. take quest from fin fizracket
2. go to witch doctor unbagwa
3. try to speak with him to get quest for 10 gorilla fang - unable to speak with him at all

**IDs of affected creatures, items, quests or spells with a link to the relevant page:**

NPC: https://database.turtle-wow.org/?npc= Witch Doctor Unbagwa
Item: https://database.turtle-wow.org/?item= Gorilla Fang
Quest: https://database.turtle-wow.org/?quest= Stranglethorn Fever
Spell: https://database.turtle-wow.org/?spell=
Object: https://database.turtle-wow.org/?object=

**Expected behavior. Describe how it should work:**

**Comment by Gurky-Turtle** [comment]
![image](https://github.com/slowtorta/turtlewow-bug-tracker/assets/90982783/5a383bba-c938-4b48-a283-ed6fc7011f3f)
unable to produce seems to work like it should.
