### ISSUE TITLE
Cannot talk in general or guild chat

### ISSUE THREAD

**Issue by Ornithorink** [slowtorta/turtlewow-bug-tracker#3164]
**Please, provide a clear description what the bug is:**

I cannot talk in general or guild chat. I do not receive any warning telling me I can't talk. My messages just don't show up.
I can read general and guild chat and I had no problem using /say /yell /whisper or /party 
I'm a level 11 orc hardcore warrior named Gorhdan. I also already tried clearing my WDB folder.

**Steps to reproduce the behavior with as much detail as possible:**

I'm unsure about the "reproductability" of that bug, but here it is:
1. Write a message in general or guild chat
2. Observe the message not appearing in said chat channel.

**Expected behavior. Describe how it should work:**

I should be able to talk in general or guild chat.

**Comment by slowtorta** [comment]
Please submit a ticket in game. GMs will help you to resolve this.
