### ISSUE TITLE
Deadly light post in Bloodhoof

### ISSUE THREAD

**Issue by Sty0pa1** [slowtorta/turtlewow-bug-tracker#3172]
**Please, provide a clear description what the bug is:**
The lightpost next to the path outside bloodhoof (the closest one south of the bridge) - I brushed it with a character on autorun and instantly died.  Character was Shoobedoo.  Combat log said 348 damage from falling.

**Steps to reproduce the behavior with as much detail as possible:**

1. be on the path
2.  autorun toward the bridge, literally lining up to see if I could autorun all the way across the bridge without touching my toon
3.  just before you get to bridge, there wil be a flaming post just on the right side of the path slightly in your way (wasnt sure if it would bump me to the left and knock me out of alignment on the bridge)
4. touch post - die.  
5. Did not replicate.

**IDs of affected creatures, items, quests or spells with a link to the relevant page:**

NPC: https://database.turtle-wow.org/?npc=
Item: https://database.turtle-wow.org/?item=
Quest: https://database.turtle-wow.org/?quest=
Spell: https://database.turtle-wow.org/?spell=
Object: https://database.turtle-wow.org/?object=

**Expected behavior. Describe how it should work:**
I assume posts shouldn't kill you.

**Comment by Gurky-Turtle** [comment]
tried multi times to replicate this but could not going to close for now.
