### ISSUE TITLE
cant use greater blessing anymore on yourself when not grouped

### ISSUE THREAD

**Issue by geojak** [slowtorta/turtlewow-bug-tracker#3175]
**Please, provide a clear description what the bug is:**
since the last restart this bug appeared, possibly related to the graeter blessigns pet fix
@ratkosrb 

you can not use greater blessings on non group and raid memebers (intended)
if a group memeber leaves group they lose grater blessing (intended)
but you still should be able to use grater blessings on yourselfs (new bug here)

**Steps to reproduce the behavior with as much detail as possible:**

1. be not in group
2. cast gretaer blessing on yourself
3. spell ist cast, mana spent, reagent used up
4. no buff???

**Expected behavior. Describe how it should work:**

buff should work, or if it doesnt work, then not cast in the first place so no mana and reagent spent for nothing

**Comment by ratkosrb** [comment]
Should be fixed once this commit goes live https://github.com/slowtorta/turtle-wow/commit/159d7e419d42b2913a1150288bbf87ea3f82d785
