### ISSUE TITLE
Deleted Jordan's Refined Ore Shipment + Cannot Restore (The Test of Righteousness)

### ISSUE THREAD

**Issue by Kanishani** [slowtorta/turtlewow-bug-tracker#3180]
After I abandoned quest The Test of Righteousness, I deleted the item Jordan's Refined Ore Shipment. This is a quest reward from Bailor Stonehand. It cannot be restore from Trash Collector Gaston, the only item he allows me to restore is the Tome of Valor. After restoring the Tome of Valor, I cannot talk to Gaston again because I have nothing left to restore. I have completed Bailor's Ore Shipment, so Bailor Stonehand cannot be interacted with at all, after I picked up The Test of Righteousness again. Clicking on Tome of Valor allows me to start the quest chain leading up to The Test of Righteousness from the very beginning. I left it alone in my inventory and did not pick up the quest from the tome.  I also have access to Seeking the Kor Gem quest as well without issues.

Steps to reproduce the behavior with as much detail as possible:

1. Accept The Test of Righteousness, go to Thelsamar and accept Bailor Stonehand's quest. Complete it and turn it in.
2. Abandon The Test of Righteousness and delete Jordan's Refined Ore Shipment from inventory.
3. Pick up quest The Test of Righteousness, go to Thelsamar and see that Bailor Stonehand has no quest if you had already completed it.
4. Go to Ratchet to see Trash Collector Gaston and only see Tome of Valor available for item restoration. Collect the item and be locked out from interacting with Gaston.
5.  Clicking on the tome has a quest to accept, which is the start of the quest chain leading up to The Test of Righteousness. As I have already completed up to the point where Jordan Stilwell asks me to collect items to craft a weapon, I ignored this quest.

IDs of affected creatures, items, quests or spells with a link to the relevant page:

NPC: https://database.turtle-wow.org/?npc=6241
NPC: https://database.turtle-wow.org/?npc=8
NPC: https://database.turtle-wow.org/?npc=6181
Item: https://database.turtle-wow.org/?item=6993
Item: https://database.turtle-wow.org/?item=6776
Quest: https://database.turtle-wow.org/?quest=1654
Quest: https://database.turtle-wow.org/?quest=1655
Quest: https://database.turtle-wow.org/?quest=1649
Quest: https://database.turtle-wow.org/?quest=1655

Expected behavior:

Gaston should have had Jordan's Refined Ore Shipment available for item restoration. He does not, and instead gave me the Tome of Valor.

**Comment by Gurky-Turtle** [comment]
Jordan's Ore Shipment and Jordan's Refined Ore Shipment will be indestructible in the next update.
