### ISSUE TITLE
World PVP kills don't count as HK sometimes

### ISSUE THREAD

**Issue by Kangaroux** [slowtorta/turtlewow-bug-tracker#3181]
I'm scout rank, and I've had at least 4 pvp kills now against players around my level (i.e. not grey) that didn't count as an HK and gave no honor. I'm not grouped and I'm engaging on people who have at least 50% hp. The latest example was last night against a rank 4 player two levels higher than me. I haven't noticed any pattern for when it happens. Each time it's happened I've seen "You have slain _name_!" in the combat log

**Comment by ratkosrb** [comment]
Did they have the Honorless Target target buff perhaps?

**Comment by Kangaroux** [comment]
@ratkosrb Nope, these are players out questing who didn't just login. I don't camp people either so this would have been the first kill (full honor)

**Comment by Jammyxx** [comment]
Also its supposed to show their Highest Rank when you get a HK, but currently shows their current rank.

**Comment by Kangaroux** [comment]
I'm noticing that lower level players are giving a lot more honor than players at or above my level. The honor amount feels extremely inconsistent. At lvl 43, killing a 36 gave me 15 honor. Killing a 41 gave me 6. The 36 was unranked and the 41 was rank 2.

**Comment by twowTurtReynolds** [comment]
We will need solid replication steps.

**Comment by twowTurtReynolds** [comment]
I'll mark this closed until replication steps are provided.
