### ISSUE TITLE
Paladin "greater" buffs dont work in open world. 

### ISSUE THREAD

**Issue by Priscillian** [slowtorta/turtlewow-bug-tracker#3184]
I was fishing and waiting for AV. After 2-3 AV procs I could not buff myself with any kinds of "Greater Blessings" in an open world anymore.
Reloging doesn't help, deleting WDB doesn't help eather.

**Comment by cyaohiri** [comment]
Duplicate of #3175.

**Comment by Priscillian** [comment]
Git it
