### ISSUE TITLE
Bug Items sold that do not disappear

### ISSUE THREAD

**Issue by Celadon142** [slowtorta/turtlewow-bug-tracker#3187]
**Please, provide a clear description what the bug is:**

**Steps to reproduce the behavior with as much detail as possible:**

items sold to merchants stay on the interface forever ? They never go away. I can't sell more items. thanks

**IDs of affected creatures, items, quests or spells with a link to the relevant page:**

NPC: https://database.turtle-wow.org/?npc=
Item: https://database.turtle-wow.org/?item=
Quest: https://database.turtle-wow.org/?quest=
Spell: https://database.turtle
![WoWScrnShot_040623_191749](https://user-images.githubusercontent.com/130085792/230451011-087c5170-8196-4c56-ad54-c2041a54fcfe.png)
-wow.org/?spell=
Object: https://database.turtle-wow.org/?object=

**Expected behavior. Describe how it should work:**

**Comment by cyaohiri** [comment]
You are in the Buyback tab. Switch to the merchant tab and you'll be able to sell items.
