### ISSUE TITLE
Tunnel Rat Geomancer spamming Fire Blast deletes players

### ISSUE THREAD

**Issue by zemiguel20** [slowtorta/turtlewow-bug-tracker#3190]
Tunnel Rat Geomancer in Silver Stream Mine, Loch Modan, spam Fire Blast, making their damage output too high. This results in a Souls-like scene with multiple player graves.

NPC: https://database.turtle-wow.org/?npc=1174

I do not know how it was like in the original vanilla, but this is clearly broken as players cant get through the mines without getting melted. Fire Blast does not have a cooldown, so either decrease their mana or increase their global cooldown (if possible) so they cant spam it.
The WoWHead Classic link shows that in WoW Classic they do not have Fire Blast at all (https://www.wowhead.com/classic/npc=1174/tunnel-rat-geomancer#abilities)

**Comment by ratkosrb** [comment]
Fire Blast already has a 9-14 seconds cooldown. Perhaps you are confusing it with Fire Shield, which continually damages all enemies in melee range?

**Comment by ratkosrb** [comment]
I've increased the cooldown of his Fireblast to 30 seconds, but you should know the previous cooldown was correct, it matched values from classic sniffs.
![Untitled](https://user-images.githubusercontent.com/35845488/230516827-fa36f15c-b97b-49ce-8fd2-aa2db76fee16.jpg)

**Comment by zemiguel20** [comment]
@ratkosrb Ah I think I was confusing it with Fire Shield, I am deeply sorry! I went over there again and I still got a lot of damage. Fire Blast was indeed *not* being spammed, but it was the damage of the normal attack + Fire Shield tick that made me think it was. So even if they have a lot of damage, they were working as intended.
Then I have rather a suggestion than a bug report: The area is packed, so maybe reducing the spawns should help not pulling 2/3 guys every time? Should I place this request in the forums?

**Comment by balakethelock** [comment]
> @ratkosrb Ah I think I was confusing it with Fire Shield, I am deeply sorry! I went over there again and I still got a lot of damage. Fire Blast was indeed _not_ being spammed, but it was the damage of the normal attack + Fire Shield tick that made me think it was. So even if they have a lot of damage, they were working as intended. Then I have rather a suggestion than a bug report: The area is packed, so maybe reducing the spawns should help not pulling 2/3 guys every time? Should I place this request in the forums?

Caves in general are supposed to be a group endeavor unless your class is powerful, you outlevel/outgear the content, AND you are a skilled player. I would advise avoiding ranged humanoids in packed places in general if you're solo.

**Comment by zemiguel20** [comment]
> > @ratkosrb Ah I think I was confusing it with Fire Shield, I am deeply sorry! I went over there again and I still got a lot of damage. Fire Blast was indeed _not_ being spammed, but it was the damage of the normal attack + Fire Shield tick that made me think it was. So even if they have a lot of damage, they were working as intended. Then I have rather a suggestion than a bug report: The area is packed, so maybe reducing the spawns should help not pulling 2/3 guys every time? Should I place this request in the forums?
> 
> Caves in general are supposed to be a group endeavor unless your class is powerful, you outlevel/outgear the content, AND you are a skilled player. I would advise avoiding ranged humanoids in packed places in general if you're solo.

Ok, thank you for the tip! I will keep that in mind from now on
