### ISSUE TITLE
Phantom Mail Showing Up Seemingly Randomly

### ISSUE THREAD

**Issue by TooHighOnLife** [slowtorta/turtlewow-bug-tracker#3192]
**Please, provide a clear description what the bug is:**
Character Name: Eos
When I get a mail notification and check my mail there will be nothing there.
I have disabled addons and deleted WDB folder numerous times
Since those did nothing I use all my addons again
The issue went away for a whole day after Sneaky helped me but it came back after I sent a bunch of cloth or something and used Postal to Open all
It may have not even had anything to do with that but it's all I can think of that may have brought it back.
I'll check my mail when I wake up and clear my auctions then throughout the day I will see the Mail symbol pop up without any auctions ending or expiring.
Thinking I may have got mail from a Guild mate or friend I will go out of my way to check it and when I do there will be nothing there.
I have not been on my other characters enough to know if it is character specific or not.

Edit: Update as of 15:57 Server time I turned off Postal as I had Phantom mail and when I reloaded it shows I have mail. The Icon did not go away when I opened my mailbox at that point with Postal disabled like it would when it was enabled
I then entered an AV and it is still there so far

Update: 16:03 Server Time I got out of AV and icon is still there
Reloaded UI and still have Icon
Attempting To Restart and Delete WDB (Postal is still disabled at this point)
Upon entering into the game no Mail icon so far, Will post any updates

Update: as of 06:02 Server time with postal disabled no phantom mail so far it may me the addon doing something I guess even if I disable the addon and reload it needs a full restart to fix perhaps. will post another update if anything changes

**Steps to reproduce the behavior with as much detail as possible:**

1. Check my mail in the morning (typically using the Open All button on Postal)
2. Mailbox is Fully Empty
3. Start playing doing whatever (I quest or farm and Queue AV while I do)
4. I am not sure when, be it after I get some kind of load screen, or just randomly while I am fighting, heck maybe it's when I cast Divine Shield on myself, but I get a Mail Notification without any system messages for auctions.
5. I stop what I am doing Typically unless it's a dungeon or BG and go check my mail
6. I purchased the mailbox with my points at first because this got to be so tedious (Sneaky helped me with this already Thank You again!)
7. Checking my mail I see nothing inside
8. The Notification Symbol goes away
9. Repeat step 3.

**IDs of affected creatures, items, quests or spells with a link to the relevant page:**
(MEME LINKS ONLY! Nothing to do with the bug itself!)
NPC: https://database.turtle-wow.org/?npc=3094
Item: https://database.turtle-wow.org/?item=83542
Quest: https://database.turtle-wow.org/?quest=60121
Spell: https://database.turtle-wow.org/?spell=8737
Object: https://database.turtle-wow.org/?object=144131

**Expected behavior. Describe how it should work:**
When the Mail notification shows up I actually have mail :)

**Comment by redmagejoe** [comment]
Open All is specific to the addon Postal, and this phantom mail icon issue is entirely a direct result OF the Open All button.

Not a Turtle bug. Ticket can be closed.
