### ISSUE TITLE
Ornate Dagger of Jalvan Stats

### ISSUE THREAD

**Issue by Lamadarius** [slowtorta/turtlewow-bug-tracker#3194]
Has the caster reward (Ornate Dagger of Jalvan) for 'And Justice For All' been coded correctly? I find it difficult to believe that it is deliberately meant to have a negative stat (-3 Int) when none of the other rewards have a negative stat. I know some rewards have a negative stat, but it doesn't fit the context of a cursed weapon, especially since the other rewards are all positive stats.

Look at the quest reward for 'And Justice For All' 

https://database.turtle-wow.org/?item=60820

Note: In the DB it is listed as +-3 Intellect

**Comment by ratkosrb** [comment]
Have you tried deleting your WDB cache?

**Comment by Lamadarius** [comment]
I didn't, but I have now and the item is +3 Intellect. Thanks! :)
