### ISSUE TITLE
My Rogue cant get skills

### ISSUE THREAD

**Issue by pepsipoint** [slowtorta/turtlewow-bug-tracker#3195]
The bug seems to not allow my character to get Rogue skills till 30, or get any profession till 10, only one was achievable Engineering and the first skill isn't available till level 30

Character name is Tpol

I should not only be able to get professions but level them up some at level 10 as well as get more rogue skills

**Comment by Muigin** [comment]
Please open a ticket in-game with a GM for character-specific issues. This platform is for universal bugs that can be reproduced.
