### ISSUE TITLE
Greater Blessings don't work without party/raid

### ISSUE THREAD

**Issue by Zmitrok1984** [slowtorta/turtlewow-bug-tracker#3196]
When I try buff himself via Greater Blessing for example Wisdom, nothing happen, buff isn't applied to me (Symbol of Kings is used).
I am alone, without party or raid.
On BG in raid I can buff with  Greater Blessing

Spell: 
https://database.turtle-wow.org/?spell=25898
https://database.turtle-wow.org/?spell=25916
https://database.turtle-wow.org/?spell=25918

**Expected behavior.**
Greater Blessing should work when you alone, as well as in party or raid.

**Comment by ratkosrb** [comment]
This was already fixed internally. You have to wait for server to be updated.
