### ISSUE TITLE
Unable to turn in quests 40632 & 40631

### ISSUE THREAD

**Issue by ForFoxes** [slowtorta/turtlewow-bug-tracker#3198]
**Please, provide a clear description what the bug is:**
Unable to turn in quests at Warleader Temukar at Gelkis Village in Desolace
**Steps to reproduce the behavior with as much detail as possible:**

1. finished quests "Our Mortal Enemies" & "In Commune With Wind" 
2. Returned to quest giver and was unable to talk to him to turn in quests 
3. 

**IDs of affected creatures, items, quests or spells with a link to the relevant page:**

NPC: https://database.turtle-wow.org/?npc=61045
Item: https://database.turtle-wow.org/?item=
Quest: https://database.turtle-wow.org/?quest=40632 & 40631
Spell: https://database.turtle-wow.org/?spell=
Object: https://database.turtle-wow.org/?object=

**Expected behavior. Describe how it should work:**
Should be able to speak to the NPC to turn in quests

**Comment by slowtorta** [comment]
Hello! Please open your reputation tab, locate the faction of this NPC, click on it, and make sure to remove the <At War> flag that's preventing you from opening the dialog window.
