### ISSUE TITLE
"Guardians of the Altar" quest is bugged

### ISSUE THREAD

**Issue by Leinadkat** [slowtorta/turtlewow-bug-tracker#32]
By opening this Issue, I admit to having done the pertinent research using sources from Vanilla (preferably) or Classic. I also understand that sources from other private servers are not acceptable.

**Current behavior**: the escort mob in the quest "guardians of the altar" ignores the moonkins in ther way( also theres a typo "sevral" in the text)

**Expected behavior**: i think they should fight them?

[**Proofs**:]
![Screenshot (309)](https://user-images.githubusercontent.com/85810009/121790492-29d6fc00-cbe0-11eb-9642-48307ec22ac5.png)

**Steps to reproduce**:

1. start the quest
2. follow the NPC
3. watch as the mob passes true moonkins

**Comment by Nolin7777** [comment]
No proof

**Comment by slowtorta** [comment]
This will be fixed on the next server update, thank you!
