### ISSUE TITLE
Paladin Quest 'Symbol of Life'

### ISSUE THREAD

**Issue by PkuMyron** [slowtorta/turtlewow-bug-tracker#3200]
My Paladin is now level 12, has completed the 'Symbol of Life' quest, but still has items in the backpack and hasn't learned the 'Redemption' skill. Is this a bug? I need help

**Comment by Sneaky42** [comment]
Greetings, May we have the player name for your character so we can research this further?

**Comment by PkuMyron** [comment]
Tinyhand，Human female，Now Lv14

**Comment by PkuMyron** [comment]
> Greetings, May we have the player name for your character so we can research this further?

Tinyhand

**Comment by PkuMyron** [comment]
> Greetings, May we have the player name for your character so we can research this further?

The problem has been solved, thanks a lot!
