### ISSUE TITLE
Ouro (AQ40) inconsistent/bugged mechanic - Sand blast

### ISSUE THREAD

**Issue by ametc1** [slowtorta/turtlewow-bug-tracker#3204]
**Please, provide a clear description what the bug is:**
Sand Blast is meant to wipe threat on the MT/Top threat target, and the swipe causing knockback in the direction Ouro is facing

On multiple attempts, Ouro would either not wipe threat on the target of sand blast or would knockback/cleave in other directions beside the direction Ouro is facing
When it would hit and cause the threat wipe, Ouro would seemingly target a random person on the threat table, regardless of their position on threat and attack them instead of the next on threat(regardless of range)

**Steps to reproduce the behavior with as much detail as possible:**

1. Have a PC target of Ouro, with several others in different directions/angles and distances around Ouro
2. Check to ensure the knockback and Sand Blast are affecting the correct directions/ranges

**IDs of affected creatures, items, quests or spells with a link to the relevant page:**

https://database.turtle-wow.org/?npc=15517

**Expected behavior. Describe how it should work:**

Sand blast should be cast in direction of the target (top threat)
Sweep/knockback should only effect those in melee range

**Comment by twowTurtReynolds** [comment]
Will be tracked under https://github.com/slowtorta/turtlewow-bug-tracker/issues/3538
