### ISSUE TITLE
Shaman's [Rockbiter Weapon] + Orc's [Blood Fury]

### ISSUE THREAD

**Issue by sergei-dokshin** [slowtorta/turtlewow-bug-tracker#3206]
**Please, provide a clear description what the bug is:**
When [Rockbiter Weapon] is active(on equipped weapon) the [Blood Fury] has **no any effect**. It should increase melee attack power!
 I tested it on another server and it works there.

**Steps to reproduce the behavior with as much detail as possible:**

1. Create Orc Shaman.
2. Use [Rockbiter Weapon] and check value of melee attack power.
3. Use racial ability [Blood Fury] and check value of melee attack power again - it will be the same.

**IDs of affected creatures, items, quests or spells with a link to the relevant page:**

NPC: 
Item: 
Quest: 
Spell: [Rockbiter Weapon] ID: 8017;  [Blood Fury] ID: 20572;
Object: 

**Expected behavior. Describe how it should work:**
[Blood Fury] should increase melee attack power, even when [Rockbiter Weapon] is active.

**Comment by ratkosrb** [comment]
I can't reproduce the issue. My attack power increases when i use Blood Fury, even if i have Rockbiter Weapon active. Do you use some kind of addon to display stats? It could be a bug in the addon. With the default interface the attack power increase is correctly displayed in my tests.


https://user-images.githubusercontent.com/35845488/230732778-08f0b307-382b-4bf1-b654-12b566be2b9e.mp4

**Comment by sergei-dokshin** [comment]
I don't use any addons to display characteristics. I understand what's the matter, in the video you use Rockbiter level 2.
The bug is only with Rockbiter level 1. Watch my the video.
In this case, this is an insignificant bug.
Sorry for disturbing you.

https://user-images.githubusercontent.com/98055136/230736343-ad1e0eb9-6d79-448c-a08e-7242efc51ab1.mov

**Comment by Jeradooka** [comment]
I tested on a level 60 with Rockbiter (Rank 1) and Blood Fury worked as expected. 
![image](https://user-images.githubusercontent.com/41565304/232938164-c2dffe53-c03d-46cf-89a0-95860b5e2875.png)
![image](https://user-images.githubusercontent.com/41565304/232938418-9d4fe857-ee69-41cc-9add-ca9c06a30216.png)
