### ISSUE TITLE
Kel'thuzad phase 1 spawn timers are delayed

### ISSUE THREAD

**Issue by balakethelock** [slowtorta/turtlewow-bug-tracker#3207]
### **Please, provide a clear description what the bug is:**
Soul Weavers start spawning 30 seconds later than they should, and overcorrect that delay by spawning too fast at the end of first phase.

### **Steps to reproduce the behavior with as much detail as possible:**

1. Start the Kel'thuzad encounter
2. use the addon BigWigs to track the spawn timer of soul weavers, judged with the phase timer.
3. find that the first soul weaver spawns at 4:30, instead of 5:00. This delay continues with all the soul weavers.

### **IDs of affected creatures, items, quests or spells with a link to the relevant page:**

NPC: https://database.turtle-wow.org/?npc=16429

### **Expected behavior. Describe how it should work:**

**Proof that the first spawn is delayed: how it should be** [the first weaver spawns in 5:00](https://youtu.be/FeKXd9L7nMg?t=19) vs **how it is in turtle wow** [the first weaver spawns in 4:30](https://youtu.be/DzzrEILr7CA?t=35)

**Proof that the delay continues throughout the encounter:** I have watched the video of the vanilla fight from a mage POV many times in slow motion and could accurately find the exact spawn timer of the soul weavers. [Here is the full video](https://www.youtube.com/watch?v=FeKXd9L7nMg) and here are my results: 

**Soul weavers spawn in the following times (counting down to end of phase 1, like bigwigs timer)**
 - **5:00** 4:30 4:00 3:30 3:05 2:45 2:25 2:05 1:45 **1:25 1:05 0:45 0:25 0:10**
Written differently, the first weaver spawns 30 seconds after entering the circle, or 15 seconds after the game puts the players in combat.

In Turtle wow, the timer between weaver spawns for the first 9 is identical to blizzard. After the 9th weaver, the game starts rapidly spawning weavers in the following rhythm:
 - 4:30 4:00 3:30 3:05 2:45 2:25 2:05 1:45 **1:25 1:05 0:45 0:35 0:25 0:10**

**how it should be** [the weaver that spawns in 1:25 is the 10th weaver as shown in the order above](https://youtu.be/FeKXd9L7nMg?t=229) vs **how it is in turtle wow** [The weaver that spawns in 1:25 is the 9th weaver](https://youtu.be/DzzrEILr7CA?t=219)

**Comment by ratkosrb** [comment]
I've adjusted the timers according to your research. Please let me know if its working correctly after the server is updated.
