### ISSUE TITLE
Unable to begin the quest "Zanzil's Mixture and a Fool's Stout" (ID Ticket from precedent message : 53039)

### ISSUE THREAD

**Issue by Waltorius** [slowtorta/turtlewow-bug-tracker#3210]
**Please, provide a clear description what the bug is:**
The situation is the following, I am unable to begin the quest called "Zanzil's Mixture and a Fool's Stout" given by Crank Fizzlebub in Botty Bay even after completing all other requirement (being having finished the precedent qest in the chain, "Back to Booty Bay" and "Zanzil's Secret" and being above the minimal required level to begin this part of the quest (the level range shown is 35-44 and my character Waltorius is already level 47.

I have talked with one of your GM, Sneaky, and followed what he told me to do : inspecting that I am not at War with any of the Steamwheelde Cartel, especially Booty Bay, not being in a group or Raid, logging off and on after clearing my WDB folder, none of those action had any impact, I can talk to the NPC but can't get the quest, even while the Pfturtle-quest is able to show me I should be able to acquire it and start it.

**Steps to reproduce the behavior with as much detail as possible:**

1. Having finished Back to Booty Bay" and "Zanzil's Secret" given by Crank Fizzlebub
2. Being at lest level 35
3. Being not at war with the Booty Bay

**IDs of affected creatures, items, quests or spells with a link to the relevant page:**

NPC: https://database.turtle-wow.org/?npc=2498/crank-fizzlebub
Quest: https://database.turtle-wow.org/?quest=1119/zanzils-mixture-and-a-fools-stout

**Expected behavior. Describe how it should work:**
I should be able to start this quest with no problem, is it because it is a timed quest, I haven't seen any timed quest up until now, are they problematic ? 

I hope I have given all the necessary information about this case.

I await your answer with great anticipation !

**Comment by twowTurtReynolds** [comment]
![image](https://github.com/slowtorta/turtlewow-bug-tracker/assets/151180101/60b4f450-26d9-4173-92ff-232432184cb6)
All seems well. I am also not sure what caused this to not work for you, Walt.
