### ISSUE TITLE
The Stonewrought Dam Quest Completion Bug

### ISSUE THREAD

**Issue by softshellll** [slowtorta/turtlewow-bug-tracker#3213]
**Please, provide a clear description what the bug is:**
Upon summoning and approaching the dam with the orphan in tow I'm not receiving a quest completion notification, but when talking to the kid you will get the 'complete quest' dialogue and prompt. Upon clicking the active/highlighted 'complete quest' button nothing happens and I'm not able to complete the quest. I tried moving further away, abandoning the quest, resummoning the kid, accepting the quest again and going back, but there was no change. In fact I still get the same dialogue and prompt to complete the quest from that far back. It should be noted the question mark over his head remains silver/grey the whole time.

**Steps to reproduce the behavior with as much detail as possible:**

1. Approach dam with child summoned
2. Attempt to turn in quest
3. Click complete quest with no response

**IDs of affected creatures, items, quests or spells with a link to the relevant page:**

NPC: https://database.turtle-wow.org/?npc=14305
Item: https://database.turtle-wow.org/?item=
Quest: https://database.turtle-wow.org/?quest=1558
Spell: https://database.turtle-wow.org/?spell=
Object: https://database.turtle-wow.org/?object=

**Expected behavior. Describe how it should work:**
Summon human orphan. Approach dam. Receive quest completed prompt. Turn in quest.

**Comment by Muigin** [comment]
Cannot reproduce on current version.
