### ISSUE TITLE
Camera issues in the Silver Sun Mine

### ISSUE THREAD

**Issue by Avarajihari** [slowtorta/turtlewow-bug-tracker#322]
**Please, provide a clear description what the bug is:**

There are a lot of camera issues in the Silver Sun Mine in Alah'Thalas. It seems like an issue that you probably know about but I haven't found any report regarding this so here I go. Plenty of times the camera jumps right into my character as if there was an invisible wall there forcing the camera to get super-close. I can't pinpoint the exact locations, but a brief jog through the mine should reveal at least 3 places where is happens.

Love y'all <3

**Steps to reproduce the behavior with as much detail as possible:**

1. Have the camera not extremely close to the character (any usual distance will work).
2. Go into the Silver Sun Mine in Alah'Thalas.
3. Jog through the mine and notice the issues with the camera.

**IDs of affected creatures, items, quests or spells with a link to the relevant page:**

N/A

**Expected behavior. Describe how it should work:**

The camera should behave like it does in other places/caves in WoW. It should only zoom in when there's an actual object blocking the LoS between the camera and the character.

**Comment by Nolin7777** [comment]
Thanks for report but we have plenty of broken maps tickets open, I will close this one due to duplication

**Comment by Avarajihari** [comment]
Hey @Nolin7777! Do you mind letting me know where those can be found? I don't want to report duplicates but I can't find any other report regarding camera in that place so maybe I'm not searching well enough. Thanks!
