### ISSUE TITLE
Brutal Armor for Horde questgiver Thun'grim Firegaze is currently not completing

### ISSUE THREAD

**Issue by daeffex** [slowtorta/turtlewow-bug-tracker#3221]
**Please, provide a clear description what the bug is:**
Hello.

Collecting all the items required for the Brutal Armor quest for Thun'grim Firegaze is currently not working. After gathering all the intended items, the quest is not marked as complete and will remain a grey question mark.

**Steps to reproduce the behavior with as much detail as possible:**

1. Complete the previous quests in the Warrior chain, Veteren Uzzek, Path of Defense, Thun'grim Firegaze, Forged Steel
2. Accept the Thun'grim Firegaze quest for "Brutal Armor"
3. Collect all the items necessary for the quest (throw away the note "Thun'grim's Instructions")
4. Attempt to hand in the four items (Iron Bars[10], Vial of Phlogiston, Powdered Azurite[10], Smoky Iron Ingot[15])

**IDs of affected creatures, items, quests or spells with a link to the relevant page:**

NPC: https://database.turtle-wow.org/?npc=5878
Quest: https://database.turtle-wow.org/?quest=1838
Item: https://database.turtle-wow.org/?item=7587

**Expected behavior. Describe how it should work:**
The quest should be able to be completed, regardless of if the Thun'grim's Instructions is thrown away.
![Brutal Armor](https://user-images.githubusercontent.com/130334702/230825255-7881ef63-abec-4609-920f-a1c1a979760d.PNG)

**Comment by Gurky-Turtle** [comment]
was able to complete this quest when testing. Please retake the quest and delete your wdb folder.
