### ISSUE TITLE
Quest-Bugg

### ISSUE THREAD

**Issue by UAreMyDarkness** [slowtorta/turtlewow-bug-tracker#3222]
**Please, provide a clear description what the bug is:**

**Steps to reproduce the behavior with as much detail as possible:**

1. I did the Quest called "Sark's Grudge", after killing the Npc Called "Ironpatch" i was able to kill / attack the friendly marked Npcs.
2. 
3. 

**IDs of affected creatures, items, quests or spells with a link to the relevant page:**

NPC: https://database.turtle-wow.org/?npc=60481 - https://database.turtle-wow.org/?npc=60480 - https://database.turtle-wow.org/?npc=60479 - 
Item: No Item
Quest: https://database.turtle-wow.org/?quest=40328 -  https://database.turtle-wow.org/?quest=40330 - And a 3rd Quest from the NPC "Falgig Wazzlewrench" which i can't see. (But a Questmark is on his head) 
Spell: No Spell
Object: No Object

**Expected behavior. Describe how it should work:**

They should just give me quest's as intended. But right now i just can attack them.

Screenshot from this Bugg: 
https://gyazo.com/3d4131c07420d0fb81dc38e489f82c03

**Comment by UAreMyDarkness** [comment]
https://streamable.com/i79m38

Here is a Video of this as well for better understanding what exactly happened

**Comment by UAreMyDarkness** [comment]
Okay i know where the problem was. It seems that killing the Npc "Ironpatch" from the Quest "Sark's Grudge" set's you at war with "Bloodsail Buccaneers". Thats why i couldn't interact with the npc's.

**Comment by redmagejoe** [comment]
If your issue is resolved, please close this ticket rather than waiting for devs to do so.
