### ISSUE TITLE
need help

### ISSUE THREAD

**Issue by supermanuel123** [slowtorta/turtlewow-bug-tracker#3224]
I have a level 31 warlock orc and I can't get the quest devourer of souls from orgrimmar or Undercity I tried everything but nothing worked I deleted everything from the WDB file I deleted turtle wow and re-downloaded the game I am not in a party or raid group and the quest you get it at level 20 but I never get it because the ques givers they don't have the yellow quest mark on them and I have no UI addons I disabled lft and pf quest to but no luck please I need help this is a warlock class quest you can send me an email on   manuel.xuereb.2213@gmail.com     or in-game mail my name is thegrimster thank you           

![Screenshot 2023-04-10 112226](https://user-images.githubusercontent.com/130352880/230874229-b4039cb4-ae81-4daf-9f8b-07dbccb10ba3.png)

![Screenshot 2023-04-10 110935](https://user-images.githubusercontent.com/130352880/230874283-75a3ee7a-0665-4ad7-b8da-b79684ef33b7.png)

**Comment by cyaohiri** [comment]
It might help to read #3209.

**Comment by supermanuel123** [comment]
I have only these 2 quests that are for warlocks I am level 31 
![Screenshot 2023-04-10 145850](https://user-images.githubusercontent.com/130352880/230905928-3b4f1aff-e200-4fc7-bfc4-6809cfed78fb.png)
