### ISSUE TITLE
High elf males don't blink

### ISSUE THREAD

**Issue by StrawberryBrains** [slowtorta/turtlewow-bug-tracker#323]
**Please, provide a clear description what the bug is:**
High elf males never blink (as in close their eyes, not the mage spell). All the other races do, high elf females too.

**Steps to reproduce the behavior with as much detail as possible:**
Check the character creation screen, character screen or in-game.

**IDs of affected creatures, items, quests or spells with a link to the relevant page:**
All high elf male player and NPC characters.

**Expected behavior. Describe how it should work:**
High elf males should blink, it's creepy

**Comment by Floralys23** [comment]
On the other hand, goblins still blink when they're dead :P
