### ISSUE TITLE
Flight route Brackenwall Village to Mudsprocket and reverse

### ISSUE THREAD

**Issue by QuadrozZz** [slowtorta/turtlewow-bug-tracker#3230]
Please correct the flight route between Brackenwall village and Mudsprocket.
The current route isn't profitable both in terms of time and costs and is not logical.

https://imgur.com/JVyXZna

**Comment by alexilaiho1** [comment]
To add to this, it's not just between those two flight points, any flight both FROM and TO Mudsprocket seems to first take you to the Barrens (Taurajo>Crossroads>...) before the actual destination.
