### ISSUE TITLE
Tinyhoof's Enlargening Elixir not working

### ISSUE THREAD

**Issue by GoldenSpatula69** [slowtorta/turtlewow-bug-tracker#3231]
**Please, provide a clear description what the bug is:** **_Tinyhoof's Shrinking Balm_**, the Horde equivalent of _Gnome Enlargement Balm_, **has no effect**. The Alliance version of the item turns you into a goo if you're not a gnome, and so the Horde item should do the exact same thing if you're **_not a tauren_**. 

**Steps to reproduce the behavior with as much detail as possible:**

1. Go to the **Thunderbluff Quartermaster**
2. Buy Tinyhoof's Enlargening Elixir (10min CD)
3. Verify that indeed it has no effect

**IDs of affected creatures, items, quests or spells with a link to the relevant page:**

None

**Expected behavior. Describe how it should work:** Instead, it only makes your character say **"Ouch..."** (tried with Orcs and Undeads). It should turn you into a **goo**, as it's useful for **RP** and Horde should have a replica of the Alliance item. It should turn you into goo until **log off**.

![gnome_balm](https://user-images.githubusercontent.com/130491945/231463445-52789f06-1fed-471d-bec7-a1f96be1d3cb.png)
![goo_result](https://user-images.githubusercontent.com/130491945/231463465-5d320869-9182-4e18-bfc7-650596a708be.png)
![tauren_balm](https://user-images.githubusercontent.com/130491945/231463480-eec72496-e1b6-4eda-8799-d020f2068587.png)
![bug_result](https://user-images.githubusercontent.com/130491945/231463505-2c8f5125-4b0b-44a5-929d-ad0caae22fcd.png)

**Comment by twowTurtReynolds** [comment]
At time of writing, this is scripted to have you /s Ouch.. and deals 500 damage to you.
