### ISSUE TITLE
The Maul'Ogg war quest is bugged

### ISSUE THREAD

**Issue by Jorrick** [slowtorta/turtlewow-bug-tracker#3232]
**Please, provide a clear description what the bug is:**

It asks me to kill lurking jungle creepers and jungle stalkers.
Yet when I kill them, the quest keeps saying 0/10 on both mobs.
I deleted WDB, rebooted and still thesame thing happens.

**Steps to reproduce the behavior with as much detail as possible:**

1. Accept The Maul'Ogg war quest
2. Kill a mob
3. See nothing happening

**IDs of affected creatures, items, quests or spells with a link to the relevant page:**

Quest: https://database.turtle-wow.org/?quest=40199

**Expected behavior. Describe how it should work:**

Just how any other quest works, accept-do-finish. 
![Bug](https://user-images.githubusercontent.com/56451400/231475947-2a0547a7-95dc-4d81-aa84-6941db375706.JPG)

**Comment by Jorrick** [comment]
Nvrm I think cuz some1 in my party made the party into a raid.

**Comment by redmagejoe** [comment]
If your issue is resolved, please close your own ticket to lower the burden on the devs.
