### ISSUE TITLE
Atiesh: possible to adjust stats or create a version useful for balance druids?

### ISSUE THREAD

**Issue by tomcoffingiii** [slowtorta/turtlewow-bug-tracker#3234]
**Please, provide a clear description what the bug is:**

Atiesh, the legendary caster staff from Naxxramas, is available to mages, warlocks, priests, and druids.  However the druid version only gives +healing instead of +spell power, which isn't useful for balance druids at all.  I raid as a balance druid and do top-5 in DPS in every raid.  Can you release a version of Atiesh that is similar to the mage version and benefits balance druids with spell power?  

**IDs of affected creatures, items, quests or spells with a link to the relevant page:**

Item: https://database.turtle-wow.org/?item=22632

**Expected behavior. Describe how it should work:**

Allowing balance druids to use a staff similar to what mages have available to them would be awesome: https://database.turtle-wow.org/?item=22589

**Comment by Zmitrok1984** [comment]
The same situation for priest - Atiesh gives only + healing.

**Comment by redmagejoe** [comment]
This is not the place to post suggestions.  This is a bugtracker and this ticket is not a bug.  Please post your suggestions in the appropriate place.

This ticket can be closed.
