### ISSUE TITLE
raventusk troll bug

### ISSUE THREAD

**Issue by Gimbodi** [slowtorta/turtlewow-bug-tracker#3237]
Hi!

Sorry, my english is really bad.
One day to the next can't open Amani'Alor portal in Orgrimmar. for several character, it exists on 2 accounts. Try walking to Amani'alor, but can't pick daily quests. Wormhole to Orgrimmar is working. Revantusk watchers does not give the starter quest any more. When other player opened the portal i can't use it.

Thanks for watching!

**Comment by dshwedovsky-sc** [comment]
Read patch notes from [5 April](https://forum.turtle-wow.org/viewtopic.php?t=6395)

**Comment by redmagejoe** [comment]
This issue can be closed. Working as intended.
