### ISSUE TITLE
A Hunter's Boast [257] unintentionally difficult

### ISSUE THREAD

**Issue by zeress** [slowtorta/turtlewow-bug-tracker#3238]
**Please, provide a clear description what the bug is:**
The quest "A Hunter's Boast" (ID: 257) has very few quest mobs available to be able to complete it reasonably in the allotted time limit of 15m. This is likely caused by the introduction of the HE starter subzone suplanting most of the spawns of Mountain Buzzard (ID: 1194)

**Steps to reproduce the behavior with as much detail as possible:**

1. Accept the quest
2. Note just how few mobs there are available for the quest, making it very difficult if another person/group is also doing it

**IDs of affected creatures, items, quests or spells with a link to the relevant page:**

NPC: https://database.turtle-wow.org/?npc=1194
Quest: https://database.turtle-wow.org/?quest=257

**Expected behavior. Describe how it should work:**

The spawn range of Mountain Buzzard should be expanded to accommodate the shrinking of their initial range. This example shows the original range of them. I believe adding a few more spawns between the mountains north of the Excavation Site should suffice, without adversly affecting new HEs.

![image](https://user-images.githubusercontent.com/3210721/231593966-fe22724a-cee9-45b6-8b88-29a8336da928.png)

**Comment by Gurky-Turtle** [comment]
This seems to have been fixed already.
