### ISSUE TITLE
Crash to Desktop - Flight from Westfall -> Lakeshire

### ISSUE THREAD

**Issue by AyleeJenn** [slowtorta/turtlewow-bug-tracker#324]
**Please, provide a clear description what the bug is:**
During the flight from Westfall, Sentinel Hill to Redridge, Lakeshire the game sometimes crashes to desktop without warning or error message.

**Steps to reproduce the behavior with as much detail as possible:**

1. Go to Westfall, Sentinell Hill and book a flight to Redridge, Lakeshire
2. Watch the entire flight - the crash always occurred in the section where it rapidly switches between Elwynn Forest and Duskwood
3. When the game crashes to desktop, there won't be an error message. The problem is reproducing this RELIABLY. As of yet I have only been able to reproduce it un-reliably. Sometimes it crashes, sometimes it doesn't.

**IDs of affected creatures, items, quests or spells with a link to the relevant page:**

NPC: https://database.turtle-wow.org/?npc=
Item: https://database.turtle-wow.org/?item=
Quest: https://database.turtle-wow.org/?quest=
Spell: https://database.turtle-wow.org/?spell=
Object: https://database.turtle-wow.org/?object=

**Expected behavior. Describe how it should work:**
The game should not crash to desktop during the flight from Westfall to Redridge

**Comment by Nolin7777** [comment]
Unable to reproduce.
