### ISSUE TITLE
golden-scale-bracers are BoP while other golden scale items are not and were not on official vanilla 

### ISSUE THREAD

**Issue by nerasw** [slowtorta/turtlewow-bug-tracker#3241]
**Please, provide a clear description what the bug is:**
Golden Scale Bracers are BoP while they [shouldn't](https://www.wowhead.com/classic/item=6040/golden-scale-bracers)

**IDs of affected creatures, items, quests or spells with a link to the relevant page:**

Item: https://database.turtle-wow.org/?item=6040

**Comment by redmagejoe** [comment]
Golden Scale Bracers are also reworked and clearly a different item on Turtle than what you linked on Classic. How an item behaved on Classic that has been completely changed on Turtle is irrelevant.

This ticket can be closed.

**Comment by nerasw** [comment]
> Golden Scale Bracers are also reworked and clearly a different item on Turtle than what you linked on Classic. How an item behaved on Classic that has been completely changed on Turtle is irrelevant. The devs decided to make this an item that benefits Blacksmiths rather than being a worthless white for leveling purposes that no other players would use anyway.
> 
> This ticket can be closed as this is not a bug.

are you dev? if so pls answer why whole set is BoE, Just as other "completely" reworked items in the same patch...

**Comment by Haaxor1689** [comment]
upon review of this and other items, the team has opted to convert this and select other craftable BoPs into BoEs. this will be fixed in the next maintenance

**Comment by nerasw** [comment]
Big thanks!
