### ISSUE TITLE
Horde AV quests don't provide reputation

### ISSUE THREAD

**Issue by gnarbrok** [slowtorta/turtlewow-bug-tracker#3242]
The Horde AV quests "Towers and Bunkers" and "The Graveyards of Alterac" reward no reputation. Others might not as well. They should reward reputation though:

https://www.wowhead.com/classic/quest=7101/towers-and-bunkers
https://database.turtle-wow.org/?quest=7101
https://www.wowhead.com/classic/quest=7082/the-graveyards-of-alterac
https://database.turtle-wow.org/?quest=7082

Also it'd be great if I could get reputation for the quest I completed (Graveyards of Alterac). (Sorry to be self-centered but AV rep grind is not something I find particularly fun to begin with. Just a part of vanilla though.)

**Comment by Gurky-Turtle** [comment]
This should be resolved next update.
