### ISSUE TITLE
Sickly gazelles do not drop sample if killed by pet

### ISSUE THREAD

**Issue by Kangaroux** [slowtorta/turtlewow-bug-tracker#3245]
**Please, provide a clear description what the bug is:**
If you send your pet to kill a sickly gazelle it will not drop a flesh sample quest item. 

**Steps to reproduce the behavior with as much detail as possible:**

1. Use a pet class (I tested with lock)
2. Send pet to attack gazelle
3. Gazelle does not drop sample

**IDs of affected creatures, items, quests or spells with a link to the relevant page:**

NPC: https://database.turtle-wow.org/?npc=12296
Item: https://database.turtle-wow.org/?item=51860
Quest: https://database.turtle-wow.org/?quest=60133

**Comment by redmagejoe** [comment]
This is not a bug. Enemies and creatures give 0 exp and 0 drops if your pet did 100% of the work on a mob. This was implemented by Blizzard (and emulated on private servers) to prevent Hunters from AFK farming with their pets.
