### ISSUE TITLE
Option to disable honor gain

### ISSUE THREAD

**Issue by burner1024** [slowtorta/turtlewow-bug-tracker#3248]
**Please, provide a clear description what the bug is:**
Please add an option to disable honor gain. Like XP one, but for honor. This is so people who don't need it can avoid crowding top honor positions, and let those still ranking have easier time.

Just a command would suffice. An interface option would be fine too, but if that delays the release, please make the command first. It's going to be immediately useful.

**Comment by Muigin** [comment]
If you'd like to make a suggestion, do so in the suggestions forums.  This is for bug reports.
