### ISSUE TITLE
Hansu Go'sha bugged quest

### ISSUE THREAD

**Issue by Pattsy** [slowtorta/turtlewow-bug-tracker#3249]
**Please, provide a clear description what the bug is:**
The quest auto completes when you accept it. It might be because I've already been to ZF and have possibly already triggered the condition for the quest to be complete? But it didn't even go in my quest log, it just auto-completed when I clicked accept
**Steps to reproduce the behavior with as much detail as possible:**
1. I just spoke to Hansu and got the quest.

**IDs of affected creatures, items, quests or spells with a link to the relevant page:**

NPC: https://database.turtle-wow.org/?npc=60856
Quest: https://database.turtle-wow.org/?quest=40519

**Expected behavior. Describe how it should work:**
It should make you go to the dungeon before it finishes.

**Comment by Gurky-Turtle** [comment]
did not auto complete in my tests you might have already had the item or something
![image](https://github.com/slowtorta/turtlewow-bug-tracker/assets/90982783/f03434c9-364c-4572-a02e-d2fb6091b8e7)
