### ISSUE TITLE
Night Elf Male Model: Satin Blindfold

### ISSUE THREAD

**Issue by dromen48** [slowtorta/turtlewow-bug-tracker#3250]
**Please, provide a clear description what the bug is:**
![image](https://user-images.githubusercontent.com/111084731/232129999-2cfa04f1-9bab-4145-b9da-4206cceb1eb2.png)
![satin_blindfold](https://user-images.githubusercontent.com/111084731/232131501-2525dd7b-3562-4700-90f2-abb5a1402424.png)

^That is that issue. 
**Steps to reproduce the behavior with as much detail as possible:**
https://database.turtle-wow.org/?item=60827
1. Play Warcraft III, night elf campaign
2. Okay take a break wow that was good right? You see how cool Illidan, Tyrande, and Malfurion are (in that order)? Ok, now you're playing turtle wow and you see a red blindfold and you're like "shiiiit Okokokok, wish it was dark gray though" so you get it as a male night elf and you see the eyes shine through the blindfold.
3. Take the item off, but keep it in bag/bank now.

**IDs of affected creatures, items, quests or spells with a link to the relevant page:**
Me, Arenthil
Player: https://database.turtle-wow.org/?player=Arenthil
Item: https://database.turtle-wow.org/?item=
Quest: https://database.turtle-wow.org/?quest=
Spell: https://database.turtle-wow.org/?spell=
Object: https://database.turtle-wow.org/?object=

**Expected behavior. Describe how it should work:**
Glowy eye not go through blindfold. ty /bow *and buffs you*

**Comment by twowTurtReynolds** [comment]
As per the Modeling team, this is an unfortunate interaction of the 1.12 client we just don't have the tools to fix.
