### ISSUE TITLE
Hammer of Wrath not working

### ISSUE THREAD

**Issue by Altgf1** [slowtorta/turtlewow-bug-tracker#3254]
**Please, provide a clear description what the bug is:**
Paladin spell Hammer of Wrath is not capable of critical strike ever.
**Steps to reproduce the behavior with as much detail as possible:**

1. Get to a target dummy of any level and set it's HP to be 20%.
2.  Equip some gear with melee critical chance and spell critical chance (let's say 10% of both)
3.  Start using the ability over and over again, you will see that even after 10 or 100 casts, you will get 0 critical strikes.

**IDs of affected creatures, items, quests or spells with a link to the relevant page:**

Spell: https://database.turtle-wow.org/?spell=24239

**Expected behavior. Describe how it should work:**

The spell should be capable of critical effect. This is ability like Seal of Command, and it should benefit from melee crit.

**Comment by Gurky-Turtle** [comment]
https://github.com/slowtorta/turtlewow-bug-tracker/issues/3716
