### ISSUE TITLE
Young Bengal Tiger HP

### ISSUE THREAD

**Issue by Shieldzies** [slowtorta/turtlewow-bug-tracker#3257]
**Please, provide a clear description what the bug is:**
The NPC "Young Bengal Tiger" spawns as 48 and 49 on Lapidis Isle. The level 48s have 2768 health and the 49s have 1,000 more at 3768. This huge jump in hp can't be intentional. They have even more hp than the lvl 52 Bengal Tigers that come in at 2228.
**Steps to reproduce the behavior with as much detail as possible:**

1. Southeast Lapidis Isle tigers

**IDs of affected creatures, items, quests or spells with a link to the relevant page:**

NPC: https://database.turtle-wow.org/?npc=91825
Item: 
Quest: 
Spell: 
Object: 

**Expected behavior. Describe how it should work:**
Closer hp amounts on the mobs that are only 2 levels difference with same name

**Comment by khoopek** [comment]
I have some screenshots to show the wildly varying HP value for level 49 Young Bengal Tigers:
![WoWScrnShot_042323_093949](https://user-images.githubusercontent.com/110908179/233814870-7b396f2a-ec9c-44ef-8cde-14a4206100ea.png)
![WoWScrnShot_042323_093853](https://user-images.githubusercontent.com/110908179/233814874-12041fc1-8956-4250-98aa-dab96e1c2cda.png)
![WoWScrnShot_042323_93807](https://user-images.githubusercontent.com/110908179/233814875-e77d382b-ccaa-4109-aabe-d8eca5e3b9b3.png)

**Comment by Muigin** [comment]
This has been fixed in a previous update.
