### ISSUE TITLE
Group Invites Remove Players from LFT 

### ISSUE THREAD

**Issue by ForFoxes** [slowtorta/turtlewow-bug-tracker#3258]
**Please, provide a clear description what the bug is:**

When in Que using Looking For Turtles addon, if a player is invited to a group, it removes them from LFT. Even if the player declines the group invitation, they are still removed from Que. 

When questing, players get invited to groups frequently but may not want to group so they can stay in the LFT Que. If they get invited to  a group they drop their Que and have to rejoin LFT, losing their place in the Que.

**Steps to reproduce the behavior with as much detail as possible:**

1.
2. 
3. 

**IDs of affected creatures, items, quests or spells with a link to the relevant page:**

NPC: https://database.turtle-wow.org/?npc=
Item: https://database.turtle-wow.org/?item=
Quest: https://database.turtle-wow.org/?quest=
Spell: https://database.turtle-wow.org/?spell=
Object: https://database.turtle-wow.org/?object=

**Expected behavior. Describe how it should work:**

**Comment by Gurky-Turtle** [comment]
please report this bug to the LFT repo https://github.com/CosminPOP/LFT
