### ISSUE TITLE
Gaffer Jacks

### ISSUE THREAD

**Issue by Calesto** [slowtorta/turtlewow-bug-tracker#3260]
Gaffer Jacks is a fishing quest and should be available at level 30 fishing.

1. I have deleted my WDB folder.
2. I completed this quest on Classic WoW servers and it works as follows:
3. Be any race, have fishing lvl 30. 
4. I am currently lvl 47 fishing on Turtle WoW and the quest still isn't available. If you have changed the level requirements for this quest for Turtle WoW, please do not have the information for this quest, on your database be pulled from Wowhead.

**IDs of affected creatures, items, quests or spells with a link to the relevant page:**

[NPC: https://database.turtle-wow.org/?
Item: https://database.turtle-wow.org/?item=
Quest: https://database.turtle-wow.org/?quest=
Spell: https://database.turtle-wow.org/?spell=
Object: https://database.turtle-wow.org/?object=

**Expected behaviour. Describe how it should work:**

**Comment by ratkosrb** [comment]
I cannot reproduce the issue. I made a new character, learned fishing, and set my skill to 30, and the quest became available.

![WoWScrnShot_041623_235841](https://user-images.githubusercontent.com/35845488/232341886-092fe166-3aec-443a-a6bb-dd4124677e18.jpg)

Perhaps you've already done the quest before and you forgot?
