### ISSUE TITLE
Sword Tempest's Rage. Chance on hit does not work correctly.

### ISSUE THREAD

**Issue by fabilya** [slowtorta/turtlewow-bug-tracker#3261]
**Please, provide a clear description what the bug is:**
According to the description, sword should give a buff (Chance on hit: Increases your attack speed by 15% for 20 sec.) only for me, but he gives a buff to the enemy too.

**Steps to reproduce the behavior with as much detail as possible:**
1.  Attack creature or duel with player
2.  Look in the combat log when the chance on hit is triggered
3.  The enemy also got a buff and his attack speed also increased

**IDs of affected creatures, items, quests or spells with a link to the relevant page:**
Item: https://database.turtle-wow.org/?item=83564

**Expected behavior. Describe how it should work:**
When triggered, the attack speed buff should only be given to the owner of the sword

**Comment by ratkosrb** [comment]
It will be fixed after the next server update.
