### ISSUE TITLE
Teleport Up Infinitely

### ISSUE THREAD

**Issue by ReasSwift** [slowtorta/turtlewow-bug-tracker#3262]
**In 'Silver Sun Mine' near 'The Golden Citadel' when jumping on a set of rocks next to a ceiling skylight, if you hit the movement keys of 'W' and Spacebar' you will proceed to teleport upward infinitely above the cave mesh and through the entire world. :**

**Steps to reproduce the behavior with as much detail as possible:**

1. **Get in my character's exact position** next to the smaller rock in between two larger boulders next to the ceiling skylight in 'Silver Sun Mine.' 
![Screenshot (949)](https://user-images.githubusercontent.com/130950068/232369029-8aefbed1-6b07-4173-9408-c4fa0f4125ed.png)

2. Jump while your **'W' -forward key** and your **Jump movement key or Spacebar** are simultaneously active at the **same time** so you are **jumping forward.**
![Screenshot (950)](https://user-images.githubusercontent.com/130950068/232370273-a2f51716-da70-4008-a28e-1155f2e81ba8.png)

3. Proceed to hold the **'W' -forward key** and your **Jump movement key.** So, essentially, **hold these two keys down continuously,** and you will teleport up through the cave mesh and into the world infinitely. So once you hit the first jump with 'W' and 'Spacebar' pressed while jumping on top of the smaller boulder forward and up, you hold these two keys, and it will teleport you infinitely upward. If you let go of the keys, it will eventually send you flying down to your death.
![Screenshot (951)](https://user-images.githubusercontent.com/130950068/232370487-d697f74f-0e56-4c58-a208-e08b98a16395.png)

![Screenshot (952)](https://user-images.githubusercontent.com/130950068/232370786-671e7379-9932-4afa-93fb-800e745daf89.png)

**IDs of affected creatures, items, quests, or spells with a link to the relevant page:**

NPC: https://database.turtle-wow.org/?npc= not relevant 
Item: https://database.turtle-wow.org/?item= not relevant
Quest: https://database.turtle-wow.org/?quest= not relevant
Spell: https://database.turtle-wow.org/?spell= not relevant
Object: https://database.turtle-wow.org/?object= not relevant

**When a player is jumping around randomly and happens to encounter a glitch such as this it can be world-breaking but also deadly.**

**Comment by slowtorta** [comment]
We;re aware of this issues, it'll be fixes in the patch 116.6
