### ISSUE TITLE
Razzari Priest not using abilities

### ISSUE THREAD

**Issue by Herdon** [slowtorta/turtlewow-bug-tracker#3263]
**Please, provide a clear description what the bug is:**
At the moment Razzari Priests in Isle of Giljim are not using their **Lightning Bolt** ability.

**Steps to reproduce the behavior with as much detail as possible:**

1. Fight a Razzari Priest

**IDs of affected creatures, items, quests or spells with a link to the relevant page:**

NPC: https://database.turtle-wow.org/?npc=92148
Spell: https://database.turtle-wow.org/?spell=15207

**Expected behavior. Describe how it should work:**
The NPC should use the **Lightning Bolt** ability as listed in the **TWoW DB.**

**Comment by Muigin** [comment]
Confirmed. Passing this to our dev team.
