### ISSUE TITLE
Razzari Mystic not using abilities

### ISSUE THREAD

**Issue by Herdon** [slowtorta/turtlewow-bug-tracker#3264]
**Please, provide a clear description what the bug is:**
At the moment Razzari Mystics in Isle of Giljim are not using their **Lesser Healing Wave** ability on themselves or friendly npc on low health.

**Steps to reproduce the behavior with as much detail as possible:**

1. Fight a Razzari Mystic

**IDs of affected creatures, items, quests or spells with a link to the relevant page:**

NPC: https://database.turtle-wow.org/?npc=92154
Spell: https://database.turtle-wow.org/?spell=10466

**Expected behavior. Describe how it should work:**
The NPC should use the **Lesser Healing Wave** ability on low health or when friendly npc is on low health.

**Comment by Muigin** [comment]
Confirmed.  Passing this to our dev team.
