### ISSUE TITLE
Venomous Jungle Serpents are not skinnable

### ISSUE THREAD

**Issue by Herdon** [slowtorta/turtlewow-bug-tracker#3265]
**Please, provide a clear description what the bug is:**
At the moment Venomous Jungle Serpents at Isle of Giljim are **not skinnable** like other serpents of same type.
Also for some reason they drop **Elemental Fire?**
![no Skin](https://user-images.githubusercontent.com/2021593/232425410-9f4c14dc-45af-4707-8611-a6b9e4a9e0ba.jpg)

**Steps to reproduce the behavior with as much detail as possible:**

1. Defeat Venomous Jungle Serpent
2. Try to skin Venomous Jungle Serpent

**IDs of affected creatures, items, quests or spells with a link to the relevant page:**

NPC: https://database.turtle-wow.org/?npc=91966

**Expected behavior. Describe how it should work:**
I feel they **should be skinnable** like any other serpent in Azeroth. Maybe also some **tweaks** to the **loot table**.

**Comment by Gurky-Turtle** [comment]
https://github.com/slowtorta/turtlewow-bug-tracker/issues/3757
