### ISSUE TITLE
Deadmines Van Cleef shoulders

### ISSUE THREAD

**Issue by hjortmar** [slowtorta/turtlewow-bug-tracker#3266]
**Please, provide a clear description what the bug is:**

The equip effect on these shoulders is not working. They are meant to deal 1 arcane damage to any attacker but does not.

**Steps to reproduce the behavior with as much detail as possible:**

1. Wear item.
2. Let mob attack you.
3. See that equip effect is not affecting any attacker.

**IDs of affected creatures, items, quests or spells with a link to the relevant page:**

NPC: https://database.turtle-wow.org/?npc=639
Item: https://database.turtle-wow.org/?item=81005

**Expected behavior. Describe how it should work:**

**Comment by hjortmar** [comment]
Just noticed that it works in berserker stance, maybe battle stance but not definately not in defensive stance

**Comment by Muigin** [comment]
Cannot reproduce.

**Comment by hjortmar** [comment]
Did you go into defensive stance when attempting to reproduce?

fre 20 okt. 2023 kl. 10:50 skrev Muigin ***@***.***>:
