### ISSUE TITLE
Quest Call of Water

### ISSUE THREAD

**Issue by DIMMSK** [slowtorta/turtlewow-bug-tracker#3268]
The Dark power character has the following problem. When completing the Call of Water quest, I accidentally canceled the quest when completing the last task. The quest NPC Searn Firewarder has become unavailable (white quest sign). After the message, GM manually added the quest to the task log. The first Islen Waterseer NPC in the quest chain. After talking to him, I lost the quest from the task log again. WDB cleaned. What should I do?

**Comment by Gurky-Turtle** [comment]
Cannot reproduce this, I still need more details.

**Comment by twowTurtReynolds** [comment]
No details provided in half a year.
