### ISSUE TITLE
Boat to Auberdine not arriving in Menethil.

### ISSUE THREAD

**Issue by tehulysses** [slowtorta/turtlewow-bug-tracker#3269]
**Please, provide a clear description what the bug is:**

The boat between Auberdine and Menethil is not arriving in Menethil.

**Steps to reproduce the behavior with as much detail as possible:**

1. Go wait at the dock in Menethil for the boat to Auberdine.
2. Continue waiting.
3. Repeat step 2.

**IDs of affected creatures, items, quests or spells with a link to the relevant page:**

Object: https://database.turtle-wow.org/?object=181985

**Expected behavior. Describe how it should work:**

It should take maybe 5 min to cycle between locations for frequent travelers. Anything less than never but not more than 5-7 min.

**Comment by cyaohiri** [comment]
That boat was moved from Menethil Harbor to Stormwind harbor.
