### ISSUE TITLE
Weapon Effects/Procs still have a chance to put you out of stealth when sapping

### ISSUE THREAD

**Issue by imaglcian** [slowtorta/turtlewow-bug-tracker#3270]
**Please, provide a clear description what the bug is:**
With Crippling Poison, sap still has a chance to break your stealth and also put you in combat (Neither of these should happen). I had 2/2 Improved Sap for all of the clips shown. Also Poison Procs don't feel nearly as high as they should be.
Made a report on this 2 weeks ago, check #3171. - The hotfix was posted with the next patch, but nothing came of it (No difference what-so-ever)
I'm hoping this will finally fix what was promised to be 3 times

Check: https://www.youtube.com/watch?v=TO4hAyW_GkI for more info and detailed video on this issue.

**Steps to reproduce the behavior with as much detail as possible:**

1. Sap an enemy with Crippling Poisons on both hands
2. Don't get put in combat, or have your stealth broken
3. Done

**Expected behavior. Describe how it should work:**
You should never get out of stealth when using Sap with 2/2 Improved from talents, and neither should Sap ever put you in combat.

**Comment by Sringaram** [comment]
Gouge still procs instant poison and all other procs.

**Comment by ratkosrb** [comment]
@Sringaram That's cause Gouge does damage.

**Comment by ratkosrb** [comment]
> You should never get out of stealth when using Sap with 2/2 Improved from talents

That is not completely true. Sap should break stealth if it Misses.

**Comment by ratkosrb** [comment]
I re-implemented Improved Sap, let's see next week if it fixes the problem.

**Comment by Sringaram** [comment]
> @Sringaram That's cause Gouge does damage.

So this won't get fixed? We've had working gouge for years that allowed you to use proc weapons and poisons and now after the recent change that's no longer possible.

**Comment by imaglcian** [comment]
> That is not completely true. Sap should break stealth if it Misses.

@ratkosrb 
Actually, even though it _does do damage_, Gouge was never meant to break when applying on-hit effects or poisons. This was a concurrent theme on other private servers as well as Classic. My first bug report made on this topic a year ago, and reposted a month ago was on this topic; Incapacitating special abilities should be able to proc non-damaging effects, while every other special ability should be able to proc any effects such as weapon on-hits, and weapon "enchants" like poisons, including Feint- Which it doesn't sound like is getting fixed either sadly.
I don't want to overcomplicate my reply by mentioning other known bugs affecting rogues on this server, (example: Stealth at high levels). 

**Here is how I see it**:
- Either gouge should not proc any damaging effects (like the hotfixes have promised), or gouge should not be able to proc any effects at all (prior state, also considered a bug). The argument that it does damage and it being reasonable of breaking wouldn't be valid for 2 reasons:
1. It _only_ does 45 damage
2. It's an Incapacitate, and the damage should be applied before the incapacitate effect
- There have been no arguments disproving the fact that Feint should be able to proc everything mentioned, I have even posted links to clips showcasing examples of it, from both Classic and Nostarius.

I also want to mention that Sap shouldn't have a "chance to miss" and never did until this point (on this server only) but I appreciate having the talent re-implemented and working again. Is there any word regarding my other questions related to this bug report, Gouge / Feint?

**Comment by imaglcian** [comment]
> Why doesn't your sap trigger my Lightning Shield and pop you out of stealth? It's technically a hit, since it is affected by hit...

1. Sap is and should not be affected by physical hit%
2. I don't believe Sap resist chances can be decreased here with Spell Hit% (Not tested)
3. Since Sap is a spell, that most likely has no chance of decreasing it's chance of resist, it should therefore not consume a stack of Lightning/Earth/Water shield when sapped.
4. With your argument, you are saying that Battle Shout, Demo Shout and others should also consume a charge of those shields?

**Comment by ratkosrb** [comment]
Gouge should be fixed next week.
