### ISSUE TITLE
Patterns: Tough Scorpid

### ISSUE THREAD

**Issue by wmalewolokno** [slowtorta/turtlewow-bug-tracker#3271]
**Please, provide a clear description what the bug is:**
Crafting items using *Scorpid Scale* give incorrect stats.
For some reason I don't understand, items are given Stamina, but just a couple of months ago everything was working correctly
**Steps to reproduce the behavior with as much detail as possible:**

1. by using *Scorpid Scale* you can create 7(seven) items
2. 
3. 

**IDs of affected creatures, items, quests or spells with a link to the relevant page:**

NPC: https://database.turtle-wow.org/?npc=
Item: https://database.turtle-wow.org/?item=8154#reagent-for
Quest: https://database.turtle-wow.org/?quest=
Spell: https://database.turtle-wow.org/?spell=
Object: https://database.turtle-wow.org/?object=

**Expected behavior. Describe how it should work:**
items must have the following characteristics: Agility and Spirit

**Comment by cyaohiri** [comment]
Spirit was recently changed to Stamina. It's not a bug.
