### ISSUE TITLE
Gor'dosh Firethrower not using ability

### ISSUE THREAD

**Issue by Herdon** [slowtorta/turtlewow-bug-tracker#3274]
**Please, provide a clear description what the bug is:**
At the moment Gor'dosh Firethrowers in Lapidis Isle are not using their **Fireball** ability. They currently only use their second ability **Torch**.

**Steps to reproduce the behavior with as much detail as possible:**

1. Fight a Gor'dosh Firethrower

**IDs of affected creatures, items, quests or spells with a link to the relevant page:**

NPC: https://database.turtle-wow.org/?npc=91852
Spell: https://database.turtle-wow.org/?spell=20793

**Expected behavior. Describe how it should work:**
The NPC should use the **Fireball** ability as listed in the **TWoW DB.**

**Comment by ratkosrb** [comment]
Will be fixed after the next server update.
