### ISSUE TITLE
Commander Starwind bugged

### ISSUE THREAD

**Issue by IamDonFrye** [slowtorta/turtlewow-bug-tracker#3275]
**Please, provide a clear description what the bug is:**
Commander Starwind in Forest Song Ashenvale is not giving quest to start Havoc on the Battlefield quest chain. Appears to let people advance the quest chain but cannot start it.
**Steps to reproduce the behavior with as much detail as possible:**

1.Be a new hero and try to get quest, you can't
2. 
3. 

**IDs of affected creatures, items, quests or spells with a link to the relevant page:**

NPC: https://database.turtle-wow.org/?npc=61143

Quest: https://database.turtle-wow.org/?quest=40808

**Expected behavior. Describe how it should work:**
Should get the quest by talking to her, no pre quest needed

**Comment by TWShang** [comment]
Quest chain operates correctly, you can either choose to start the quest chain with the druids or the sentinels, picking one closes the other side.
