### ISSUE TITLE
Quest trouble (HC players)

### ISSUE THREAD

**Issue by Podvaldeda** [slowtorta/turtlewow-bug-tracker#3277]
**Please, provide a clear description what the bug is: Can't complete priest quest [Garments of the Moon] on hardcore mode, because can't cast positive spells (heal, buffs) on NPC**

**IDs of affected creatures, items, quests or spells with a link to the relevant page:**

NPC: https://database.turtle-wow.org/?npc=12429
Quest: https://database.turtle-wow.org/?quest=5621

**Comment by cyaohiri** [comment]
This will be fixed in the next update. Currently you have to be PvP flagged to buff PvP flagged targets.
