### ISSUE TITLE
Mage quest lvl 16 is not working

### ISSUE THREAD

**Issue by Xupiscu** [slowtorta/turtlewow-bug-tracker#3281]
**Please, provide a clear description what the bug is:**

**Steps to reproduce the behavior with as much detail as possible:**

1.[Mage quest lv 16(investigate the blue recluese) is bugged
2 according to the quest, the item "cantation of manifestation" should spawn 3 mana elementals when used in the tavern Blue Recluse in stormwind
3. But when u use the item, the mana elementals are not spawning

**IDs of affected creatures, items, quests or spells with a link to the relevant page:**

NPC: https://database.turtle-wow.org/?npc=
Item: https://database.turtle-wow.org/?item=/script DEFAULT_CHAT_FRAME:AddMessage("\124cffffffff\124Hitem:7308:0:0:0:0:0:0:0:0\124h[Cantation of Manifestation]\124h\124r");
Quest: https://database.turtle-wow.org/?quest=1920
Spell: https://database.turtle-wow.org/?spell=
Object: https://database.turtle-wow.org/?object=

**Expected behavior. Describe how it should work:**

**Comment by Teknishun7** [comment]
Worked fine for me. Needs to be in the basement tho.
