### ISSUE TITLE
Morbent's Bane / Torch of Holy Fire

### ISSUE THREAD

**Issue by magzys** [slowtorta/turtlewow-bug-tracker#3283]
**Please, provide a clear description what the bug is:**

**Steps to reproduce the behavior with as much detail as possible:**

1. The quest item, Morbent's Bane I had equip to do the quest back while leveling, had been added to my transmog table for offhand Frills.

After turning in the quest and receiving the item Torch of Holy Fire, I had equip it, and thought nothing of it.

After getting to 60, and going to try and transmog Torch of Holy Fire, it is not in my transmog table, as it has the exact same model as Morben's Bane. 

This normally wouldn't be an issue, but with this item, they sheath on the side of the hip differently. The Torch is visible while sheathed, where the Morbent's Bane is not visible while sheathed/casting. 

Is there any way you can remove Morbent's Bane from my transmog list so i can re-equip Torch of Holy Fire and learn the correct visual <3?

![WoWScrnShot_041923_001014](https://user-images.githubusercontent.com/128333544/232965122-5802b9cd-1e67-4b29-965f-1e7f850250ec.jpg)
![WoWScrnShot_041823_235929](https://user-images.githubusercontent.com/128333544/232965137-d5598ed1-b446-431d-8f7d-d6c09e9b0173.jpg)

**IDs of affected creatures, items, quests or spells with a link to the relevant page:**

NPC: https://database.turtle-wow.org/?npc=
Item: https://database.turtle-wow.org/?item=
Quest: https://database.turtle-wow.org/?quest=
Spell: https://database.turtle-wow.org/?spell=
Object: https://database.turtle-wow.org/?object=

**Expected behavior. Describe how it should work:**

**Comment by magzys** [comment]
Additional photo, Torch equip, Morbent's Bane in Transmog window, Torch nowhere to be found in window

![WoWScrnShot_041923_001804](https://user-images.githubusercontent.com/128333544/232966089-211f1108-1955-4ba7-b3c7-5493f4d310ad.jpg)

**Comment by magzys** [comment]
suggestion to fix the issue, just change Morbent's Bane items visual ID to the Torches.

**Comment by magzys** [comment]
bump. still waiting on a fix for this please <3

**Comment by twowTurtReynolds** [comment]
Turns out that this is the same issue of https://github.com/slowtorta/turtlewow-bug-tracker/issues/5556. I'll add this case there, make sure to subscribe to that thread for updates when fixed.
