### ISSUE TITLE
Glowing Cat Figurine wasn't updated with latest patch.  Overlooked?

### ISSUE THREAD

**Issue by ConcernedTurtler** [slowtorta/turtlewow-bug-tracker#3284]
**Please, provide a clear description what the bug is:**

Not really a bug but today a patch dropped that updated a lot of items that summon temporary mobs to assist the player which included the following: Dog Whistle, Mechanical Yeti, Mechanical Greench and Spiked Collar.

Absent was the glowing cat figurine which is found in darkshore and summons a ghost saber to assist the player for 10 minutes: https://www.wowhead.com/classic/item=5332/glowing-cat-figurine

I'm wondering if this item was accidentally overlooked or if it was purposely ignored. Thank you.

**Comment by ConcernedTurtler** [comment]
Yeah that was my guess as well. Would make for a cool trinket.

**Comment by Dragunovi** [comment]
Thanks for the report, we've missed it due to an oversight. The item should be updated with our next scheduled restart to become a trinket. 1 hour cooldown due to the pet lasting up to 10 minutes.
