### ISSUE TITLE
purple tallstrider cant swim 

### ISSUE THREAD

**Issue by bisman2000** [slowtorta/turtlewow-bug-tracker#3286]
**Please, provide a clear description of what the bug is:**
purple tallstrider cant swim 
**Steps to reproduce the behavior with as much detail as possible:**

1. summon a purple tallstrider
2.  go to any deep water area and mount will disappear like before patch noted 8/04/2023

**IDs of affected creatures, items, quests or spells with a link to the relevant page:**

Item: https://database.turtle-wow.org/?item=50075

**Expected behavior. Describe how it should work:**
purple tallstrider can swim like patch note 8/04/2023 describe

**Comment by ratkosrb** [comment]
Will be fixed by https://github.com/slowtorta/turtle-wow/commit/52c027d9e07f4a9e5d260e7fe2ce6a24a8fd178f
