### ISSUE TITLE
Unobtainable Syndicate mask.

### ISSUE THREAD

**Issue by Scramms** [slowtorta/turtlewow-bug-tracker#3287]
**Please, provide a clear description what the bug is:**
There is an item ingame or in the database that's not obtainable. The item is called Syndicate Mask  You cannot get past neutral reputation as far as I know.
**Steps to reproduce the behavior with as much detail as possible:**

1. Either change the equip and purchase from friendly to neutral.
2. Or make a way to get from neutral to friendly.
3. Perhaps also add a way to get reputation at all. At this moment you have to kill level 50 mobs that give only 5 rep, and you need 40k rep to get to neutral.

**IDs of affected creatures, items, quests or spells with a link to the relevant page:**

NPC: https://database.turtle-wow.org/?npc=https://database.turtle-wow.org/?npc=80946
Item: https://database.turtle-wow.org/?item= https://database.turtle-wow.org/?item=81080
Quest: https://database.turtle-wow.org/?quest=
Spell: https://database.turtle-wow.org/?spell=
Object: https://database.turtle-wow.org/?object=

**Expected behavior. Describe how it should work:**

**Comment by Scramms** [comment]
How is it completed?..

**Comment by ratkosrb** [comment]
If you are neutral, go talk to Lord Falconcrest.

**Comment by Scramms** [comment]
But... The item still has Friendly required.. I have the item already!
________________________________
Van: ratkosrb ***@***.***>
Verzonden: vrijdag 21 april 2023 08:31
Aan: slowtorta/turtlewow-bug-tracker ***@***.***>
CC: Scramms ***@***.***>; Author ***@***.***>
Onderwerp: Re: [slowtorta/turtlewow-bug-tracker] Unobtainable Syndicate mask. (Issue #3287)


If you are neutral, go talk to Lord Falconcrest.
