### ISSUE TITLE
water on dry land

### ISSUE THREAD

**Issue by Konspaul** [slowtorta/turtlewow-bug-tracker#3296]
**Please, provide a clear description what the bug is:**

**Steps to reproduce the behavior with as much detail as possible:**

1.Durotar river has water on dry land
2. Please see the attached image
3. 

**IDs of affected creatures, items, quests or spells with a link to the relevant page:**
![Screenshot 2023-04-19 at 18 35 32](https://user-images.githubusercontent.com/16685288/233128600-8e51dd92-20e8-496f-8d23-0d455636fd4d.jpg)

NPC: https://database.turtle-wow.org/?npc=
Item: https://database.turtle-wow.org/?item=
Quest: https://database.turtle-wow.org/?quest=
Spell: https://database.turtle-wow.org/?spell=
Object: https://database.turtle-wow.org/?object=

**Expected behavior. Describe how it should work:**

**Comment by twowTurtReynolds** [comment]
![image](https://github.com/slowtorta/turtlewow-bug-tracker/assets/151180101/5cd2613d-838a-47cb-8d8e-83a213987d60)
