### ISSUE TITLE
Tallstrider Mount dismounts in water

### ISSUE THREAD

**Issue by misterjigs** [slowtorta/turtlewow-bug-tracker#3297]
Ivory Tallstrider dismounts in water

Occurs when entering any water while on this mount

Occurs with Ivory Tallstrider mount, though I suspect it probably happens with all the tallstrider mounts.

Item: https://database.turtle-wow.org/?item=50071

Per a recent twow update, players should stay mounted when entering water on any mount.
![land](https://user-images.githubusercontent.com/60898593/233141671-9961f9ac-9e39-4e2d-b2ad-49054f8ae8d2.png)
![water](https://user-images.githubusercontent.com/60898593/233141691-8aab6b00-6144-4e86-9139-7d5f8eb9b1d2.png)

**Comment by Gurky-Turtle** [comment]
https://github.com/slowtorta/turtlewow-bug-tracker/issues/3286

**Comment by misterjigs** [comment]
Can this be reopened? The purple tallstrider was fixed in the patch today but the Ivory Tallstrider remains with this issue.
