### ISSUE TITLE
Guardian-summoning items

### ISSUE THREAD

**Issue by cyaohiri** [slowtorta/turtlewow-bug-tracker#3298]
Motivated by #3284, I've generated a list of items used to summon guardian creatures with limited charges that were not affected in the last update in case they were overlooked.

https://www.wowhead.com/classic/item=5218/cleansed-timberling-heart
https://www.wowhead.com/classic/item=23379/cinder-bracers
https://www.wowhead.com/classic/item=18645/gnomish-alarm-o-bot

**Comment by Muigin** [comment]
These items have been fixed since this ticket was made.
