### ISSUE TITLE
Quest: Attack on Camp Narache is not enable to all horde races

### ISSUE THREAD

**Issue by el-dias** [slowtorta/turtlewow-bug-tracker#33]
By opening this Issue, I admit to having done the pertinent research using sources from Vanilla (preferably) or Classic. I also understand that sources from other private servers are not acceptable.

**Current behavior**: 

"Quest is not available to your race"

**Expected behavior**: 

Quest should be available to all horde races

**Proofs**:

https://classic.wowhead.com/quest=781/attack-on-camp-narache

**Steps to reproduce**:

1.  Try to active quest and "Quest is not available to your race"
2. 
3.

**Comment by slowtorta** [comment]
Thanks for reporting it. It's fixed and will be deployed on the next server update.
