### ISSUE TITLE
Bael Hardul - Inn not triggering expected Inn like behaviours.

### ISSUE THREAD

**Issue by exidtv** [slowtorta/turtlewow-bug-tracker#3300]
**Please, provide a clear description what the bug is:**

Location: Bael Hardul inn is not classified as an inn even though it has an innkeeper and you can set your hearthstone at the location, you do not get rested while inside the building nor can you instantly exit the game inside the building which is expected behaviour within a inn type building in WoW.

**Comment by slowtorta** [comment]
Will be fixed in patch 1.16.6
