### ISSUE TITLE
Skill: "Trueshot" (new hunter spell) that uses focus instead of mana

### ISSUE THREAD

**Issue by 21Khal** [slowtorta/turtlewow-bug-tracker#3301]
**Please, provide a clear description what the bug is:**

I learned Trueshot from a Hunter Trainer Kragg at level 40 in Grom'gol and it uses Focus instead of mana.

**Steps to reproduce the behavior with as much detail as possible:**

1. Go to Grom'gol
2. Talk to the Hunter Trainer Kragg
3. Learn Trueshot

**IDs of affected creatures, items, quests or spells with a link to the relevant page:**

Hunter trainer Kragg: https://database.turtle-wow.org/?npc=1404
Proper Trueshot: https://database.turtle-wow.org/?spell=3035

**Expected behavior. Describe how it should work:**
It should have mana. Screenshot with Trueshot using Focus:
![Desktop Screenshot 2023 04 21 - 18 18 33 73](https://user-images.githubusercontent.com/131459498/233638403-dc3ff8fe-f6ae-4f85-a0d3-04e42423a38f.png)

**Comment by slowtorta** [comment]
It looks like there's an issue with your client. Please download the latest version from our website and do not apply any custom modifications.

**Comment by 21Khal** [comment]
> It looks like there's an issue with your client. Please download the latest version from our website and do not apply any custom modifications.

Indeed it was! Had the same client since I started playing and guess it just accumulated junk and deleting WTB wasn't enough. Спасибо, Торта.
