### ISSUE TITLE
The Harvest Golem Mystery , problems with falling out

### ISSUE THREAD

**Issue by Gorzoth** [slowtorta/turtlewow-bug-tracker#3303]
The item does not fall on the task: The Harvest Golem Mastery , namely: Cracked Animation Rune .
I was engaged in farming for 3 hours, I was not in a raid group, I did not have addons enabled, and as a result, I spent the evening in vain. 3 hours for the loss of what should fall with a chance of 80%, as stated by p fquest and information from your own DB.

1.
2. 
3. 

**IDs of affected creatures, items, quests or spells with a link to the relevant page:**

NPC: https://database.turtle-wow.org/?npc=115
NPC: https://database.turtle-wow.org/?npc=114
NPC: https://database.turtle-wow.org/?npc=36
Item: https://database.turtle-wow.org/?item=60676
Quest: https://database.turtle-wow.org/?quest=40470

**This should correspond to the corresponding specified chance of dropping 80%, or correct your mistake in the database regarding the chance of dropping an item!**

**Comment by Gurky-Turtle** [comment]
Just tested this and looked up the values and the drop is set to 80% there is no bug here sounds like a WDB issue.
