### ISSUE TITLE
Malor Boss in stratholme with loot issues

### ISSUE THREAD

**Issue by Bittermens** [slowtorta/turtlewow-bug-tracker#3306]
**Issue**
Malor the Zealous isn't dropping his new boss loot after kill, or even dropping gold once dead if there is a horde player who aggros him or a new race

**How to Reproduce**

1. Aggro him and kill him as horde character or one of the new races
2. Kill him normally
3. Loot doesn't trigger or has zero loot.

NPC: https://database.turtle-wow.org/?npc=11032

**Expected behavior. Describe how it should work:**
His loot should drop normally as the bosses inside the bastion like 2 items off his boss loot. As of now is unbearable with a good chance of dropping nothing at all, even gold.

This needs to be fixed for it affects all players.

**Comment by Gurky-Turtle** [comment]
![image](https://github.com/slowtorta/turtlewow-bug-tracker/assets/90982783/ce7e055c-f007-4f9c-a69c-96f67f937bf5)
![image](https://github.com/slowtorta/turtlewow-bug-tracker/assets/90982783/5d5f8c39-9246-4698-b38f-0e66dfc056b6)

**Comment by Gurky-Turtle** [comment]
![image](https://github.com/slowtorta/turtlewow-bug-tracker/assets/90982783/9b81388e-e467-4c0f-b589-bdf7e634e9dc)

**Comment by Gurky-Turtle** [comment]
seems to have something to do with faction loot flags

**Comment by twowTurtReynolds** [comment]
![image](https://github.com/slowtorta/turtlewow-bug-tracker/assets/151180101/a1b6c32f-154a-4bd6-aa65-2f57ca3def45)
I'm not able to replicate this. Pulled with the pvp flagged goblin, hit once with the human, and gold and loot did drop.
