### ISSUE TITLE
Skill: Heroic Strike queue and offhand hit interaction

### ISSUE THREAD

**Issue by Sringaram** [slowtorta/turtlewow-bug-tracker#3307]
I thought I'd post this here so it gets more attention as the [forum post](https://forum.turtle-wow.org/viewtopic.php?t=2794) hasn't received any replies from the staff. I'll just quote Ugoboom here;

Currently, when a warrior dual wields, they can press Heroic Strike which will queue the effect for next swing, and while this queue is in effect, the offhand weapon gains +19% hit chance, meaning with proper mainhand hit cap, the offhand will never miss.

This interaction has existed on retail from vanilla 1.0 to cata 4.0, on blizzard classic, and for about a year here on turtle wow. It is entirely blizzlike, but I argue this is a bug and must be removed, to better aid developers in their effort to balance classes and add new gear and content with confidence.

No other spec, of any class, gets to triple dip on gear like DW warrior does right now. 2H warrior and many other class specs simple double dip.

This unique gear triple dip, is the main reason that dual wield warrior is the best dps in the endgame of 1.12.  Rogue, cat, and 2h warrior would be far closer if the HS queueing +hit bonus was removed, which is why I suggest its removal.

**Comment by balakethelock** [comment]
> Question, could hunter so this too with raptor strike?

Yes, it works on raptor strike too.

**Comment by twowTurtReynolds** [comment]
The bug tracker is not a place for fixing bugs of Blizzard content. This if ever changed would have to be as part of Class Changes passes.
