### ISSUE TITLE
Mage: Arcane Brilliance Talent Requirement Bug

### ISSUE THREAD

**Issue by Sigsene** [slowtorta/turtlewow-bug-tracker#3309]
Arcane Brilliance Talent Requirement Bug

The Talent Arcane Brilliance gets to be available and gained as an ability when the talent, Arcane Potency, which is a three-point requirement for Arcane Brilliance, is only at one point. What I mean is one can get Arcane Brilliance with only one point of Arcane Potency, which is a three-point talent, and I don't think that should be the case as of how the new talents were designed, so please, I'd like to ask Turtle WoW team to do something about that.

**Comment by Gurky-Turtle** [comment]
![image](https://github.com/slowtorta/turtlewow-bug-tracker/assets/90982783/03257b32-0978-47d5-b793-b7517aa72326)

**Comment by Gurky-Turtle** [comment]
only requires 1 point clear your wdb folder.
