### ISSUE TITLE
Saltjaw Basilisk in Gilligim's Isle dropping items from basilisk in Blasted Lands

### ISSUE THREAD

**Issue by khoopek** [slowtorta/turtlewow-bug-tracker#3310]
Saltjaw Basilisk in Gilligim's Isle dropping items from basilisk in Blasted Lands.
I remembered the Basilisk Brain and Imperfect Draenethyst Fragment were only available from Redstone Basilisk in Blasted Lands.
Not sure if this is intended, as other basilisk from other places don't drop those 2 items.

NPCs and item links:
https://database.turtle-wow.org/?npc=91964
https://database.turtle-wow.org/?npc=5990
https://database.turtle-wow.org/?item=8394
https://database.turtle-wow.org/?item=10593

**Comment by Sringaram** [comment]
Pretty much all the mobs in there have shared loot tables. The elemental shamblers drop Un'Goro loot from the same type of mobs.
