### ISSUE TITLE
Skinning still buged wont give leathers after skin

### ISSUE THREAD

**Issue by Deadnot23** [slowtorta/turtlewow-bug-tracker#3314]
skinning a beasts sometimes skins the beast and gives no leathers nothing at alll and the corpse dissapears too as if it was skinned

ive been skinning from 0 to 300

and its happening all the time randomly when sometimes no matter how far or close you skin a beast corpse, sometimes it simply gives nothing at alll

**Comment by cyaohiri** [comment]
Possibly related to #199.

**Comment by Deadnot23** [comment]
welll yeah seems like it pretty much the same isssuse that was since 2021 so still nothing was done? the issue still exists....

**Comment by slowtorta** [comment]
Report a specific creature ID where it happens the most, please.
