### ISSUE TITLE
Custom quest - The Old Bonds (Problem with the quest text)

### ISSUE THREAD

**Issue by cygnus-xr1** [slowtorta/turtlewow-bug-tracker#3316]
The quest 'The Old Bonds' from the goblin named 'Oilfuse' in Ratchet is bugged. The quest text differs in the quest log after it's accepted from the NPC.

**Steps to reproduce the behavior with as much detail as possible:**

1. Do the pre-quests from 'Slip' in Booty Bay
2. Get the quest 'The Old Bonds' from Oilfuse in Ratchet
3. Check the quest log

![old_bonds_1](https://user-images.githubusercontent.com/91410790/233852321-4eaa3017-27de-4300-b3fa-ece76401eea5.png)
![old_bonds_2](https://user-images.githubusercontent.com/91410790/233852325-aaf0f198-6f4b-4d53-8fe1-41075f006b84.png)
![old_bonds_in_questlog](https://user-images.githubusercontent.com/91410790/233852328-e3a1fa8f-5ab9-4f56-a955-da22115711bf.png)

**Comment by slowtorta** [comment]
![image](https://user-images.githubusercontent.com/66763404/235093565-9662677e-c3cf-45a6-be5f-47bb42248838.png)
![image](https://user-images.githubusercontent.com/66763404/235093602-aacfc2e6-fc81-4916-b487-1df4e57e58a1.png)

This is working as intended. Please delete your WDB folder to prevent this from happening.
