### ISSUE TITLE
[Raw Nightfin Snapper] drop rate 15% instead of 30%.

### ISSUE THREAD

**Issue by Teknishun7** [slowtorta/turtlewow-bug-tracker#3317]
[Raw Nightfin Snapper] drop rate 15% instead of 30%. I have tested this extensively and confirmed this with other players.

Test conditions:
-On a fishing boat. _+50 fishing_
-Best possible location according to Wowhead, TurtleWoW-DB and the players (Feralas, Winterspring, EP/WP, etc).
-Best possible lure [Aquadynamic Fish Attractor]. _+100 fishing_
-A really decent rod [Nat Pagle's Extreme Angler FC-5000] _+25 fishing_
-Best possible skill of 300 fishing _475 with buffs._
-Best Possible time between 00:00 and 06:00 _[Raw Nightfin Snapper] will drop according to **.server time** command, confirmed by devs_
-Even took this one step further and noticed they had a 14% rate in Winterspring according to [https://database.turtle-wow.org/?item=13759](url)

So the rate is definitely around 12% to (at most in perfect condition with RNG on your side) 15%.

I really don't want to be that guy here, but according to the [https://www.wowhead.com/classic/item=13759/raw-nightfin-snapper#comments](url) in Vanilla and Classic the rates were around 30%. Keep in mind that it's even worst if you're used to Classic fishing compared to Vanilla because in classic the fish could pop at any time. In Vanilla you have to wait to at least 50% of the channeling bar making fishing a lot slower.

Why is the rate nerfed by over half? Would it be possible to restore the rate at 30%?

Thanks, signed,
an angry fisherman.

**Comment by Gurky-Turtle** [comment]
<img width="991" alt="Screenshot 2023-05-05 at 10 01 27 AM" src="https://user-images.githubusercontent.com/90982783/236479278-6fc0e256-6db4-4c7e-905e-a9cd0108e34b.png">
I am not seeing where you see 30%, based on this page it looks like 22% is the highest and that is in moonglade.

However the %'s on the turtle wow database could be updated it seems.

looks like these should be the values:

Moonglade - 22%
Un'Goro Crater - 22%
Western Plaguelands - 20%
Winterspring - 20%
Deadwind Pass - 19%
Eastern Plaguelands - 19%
Felwood - 19%
Alterac Valley - 16%
Feralas - 12%
The Hinterlands - 10%
Silithus - 6%
Burning Steppes - 5%
Duskwood - 2%
Azshara - 1.4%

**Comment by Gurky-Turtle** [comment]
You have to go off base values in the database not the rng the addons pick up. I listed the base DB values for classic above which should be what they get changed to.

**Comment by Teknishun7** [comment]
Thanks, any adjustement will be greatly appreciated.

**Comment by Gurky-Turtle** [comment]
Should be applied next patch.
