### ISSUE TITLE
Geddon dropped right half binding 

### ISSUE THREAD

**Issue by Cru313** [slowtorta/turtlewow-bug-tracker#3318]
**Please, provide a clear description what the bug is:**
Back in September of 2022 my guild killed Geddon and a right half binding had dropped, thinking i needed garr for the last 8 months i farmed garr only to get another right binding. assuming the bug was fixed or there is still a bug where the wrong sided binding can drop

1. Had  Geddon drop right side back in sptember
![image](https://user-images.githubusercontent.com/112676181/233901069-ff115765-698a-49e1-a150-a32323e0647f.png)

2. Garr then drops the right side 4-23-2023
3. i had to delete my binding in order to pick up the new binding, was able to trade and then restore my old binding i got off geddon 8 months ago waiting for garr binding...........

**IDs of affected creatures, items, quests or spells with a link to the relevant page:**

NPC: https://database.turtle-wow.org/?npc=
Item: https://database.turtle-wow.org/?item=
Quest: https://database.turtle-wow.org/?quest=
Spell: https://database.turtle-wow.org/?spell=
Object: https://database.turtle-wow.org/?object=

**Expected behavior. Describe how it should work:**

**Comment by Cru313** [comment]
![image](https://user-images.githubusercontent.com/112676181/233901379-e6adf981-31a0-4fc5-a680-01a879de5541.png)

**Comment by Cru313** [comment]
![image](https://user-images.githubusercontent.com/112676181/233901411-5d9c9846-e135-4490-8446-cd090cbaa0b2.png)
had this in bags for 8 months since september had it drop off geddon, i have 10 ppl or more that also recall

**Comment by balakethelock** [comment]
https://database.turtle-wow.org/?item=18564 right binding drops only from Garr.
https://database.turtle-wow.org/?item=18563 left binding drops only from Geddon.

This is in the official database so unless theres some very convoluted bug happening, I don't see any way the game would drop the wrong item. The event that happened now (garr dropped right binding) is correct. What happened 8 months ago is most likely just misremembering the story.

**Comment by ConcernedTurtler** [comment]
Assuming the loot tables weren't correct 8 months ago and were fixed at some point.

**Comment by balakethelock** [comment]
> Assuming the loot tables weren't correct 8 months ago and were fixed at some point.

If that's the case then I'm genuinely surprised somebody and their whole guild went 8 months not realizing they got the wrong binding and had it reversed all that time. Did nobody ever glance at atlasloot or join other guilds molten cores?

**Comment by HudsonParttimeMage** [comment]
I'm in his guild, Geddon did drop the wrong binding but legit noone in the raid noticed at that time.  The binding sat in his bags for all this time and the guild farmed Baron for him.  Since then 2 Geddon bindings dropped the correct one which were given to other members.  It's been an ongoing meme in the guild that Baron's binding would never drop for Cru, only for it to finally happen and realize he had it all this time.  Absolutely tragic.

**Comment by ConcernedTurtler** [comment]
> > Assuming the loot tables weren't correct 8 months ago and were fixed at some point.
> 
> If that's the case then I'm genuinely surprised somebody and their whole guild went 8 months not realizing they got the wrong binding and had it reversed all that time. Did nobody ever glance at atlasloot or join other guilds molten cores?

I think most people will just assume they got the correct loot from the boss.

**Comment by HudsonParttimeMage** [comment]
> > > Assuming the loot tables weren't correct 8 months ago and were fixed at some point.
> > 
> > 
> > If that's the case then I'm genuinely surprised somebody and their whole guild went 8 months not realizing they got the wrong binding and had it reversed all that time. Did nobody ever glance at atlasloot or join other guilds molten cores?
> 
> I think most people will just assume they got the correct loot from the boss.

This ^ Also doesn't help they are pretty much identically named except for one word "right/left" lol

**Comment by Cru313** [comment]
so either mandela effect or i and 20 ppl are wrong
