### ISSUE TITLE
Mount makes no sound

### ISSUE THREAD

**Issue by Redeemer166** [slowtorta/turtlewow-bug-tracker#3319]
I recently purchased a Palomino mount and it makes no footstep sounds or mount special (spacebar) sounds.

1.Use mount from spellbook
2. press spacebar while stationary for mount special
3. run around on mount

Item: https://database.turtle-wow.org/?item=12354
Spell: https://database.turtle-wow.org/?spell=16082

The mount should make horse hoof sounds when running and whinny or neigh when using mount special as on classic wow.

**Comment by Redeemer166** [comment]
I have updated my client to the latest available and this issue still affects me.

**Comment by twowTurtReynolds** [comment]
![image](https://github.com/slowtorta/turtlewow-bug-tracker/assets/151180101/3626773d-5d6b-4dab-a833-dad381614c85)
The mount now makes a sound.
