### ISSUE TITLE
Har'gesh Doomcaller shadow reflect does not work

### ISSUE THREAD

**Issue by afizzler** [slowtorta/turtlewow-bug-tracker#3321]
Using shadow reflector should be able to reflect back his shadow bolt. 

Shadow Reflector: https://database.turtle-wow.org/?item=18639
Har'gesh Doomcaller: https://database.turtle-wow.org/?npc=60737

**Comment by twowTurtReynolds** [comment]
![image](https://github.com/slowtorta/turtlewow-bug-tracker/assets/151180101/f2950e73-bb1c-4188-a9d9-21abceb19bd6)
Looks good now.
