### ISSUE TITLE
I can't remove druid's stag travel form

### ISSUE THREAD

**Issue by Bogdaniero** [slowtorta/turtlewow-bug-tracker#3323]
The deer's travel form is used, despite the absence of Glyph of the Stag in the inventory.

1. I did the quest "The White Stag and the Moon" (4672) some time ago, I didn't pay attention, but I don't remember that the "Glyph of the Stag" (7694) was ever received at all after complieting the quest. Therefore, I don't see any way to remove it from the inventory.
2. Always when using the travel form, a deer appears, while growling like a cheetah.

Please help me get rid of the deer travel form :)

**Comment by cyaohiri** [comment]
The glyph is inside your keyring. If you move it to your bank, you'll go back to your cheetah form.

**Comment by Bogdaniero** [comment]
Oh, a keyring, I didn't notice that, thank you!
