### ISSUE TITLE
Succubus Seduction passing through Divine Shield

### ISSUE THREAD

**Issue by RevengeanceOne** [slowtorta/turtlewow-bug-tracker#3325]
**Please, provide a clear description what the bug is:**

Succubus Seduction spell is passing through Divine Shield if during the cast of seduction the Paladin is using Divine Shield.

**Steps to reproduce the behavior with as much detail as possible:**

1. Have a Succubus start casting Seduction on the Paladin.
2. Have the Paladin cast Divine Shield during that Seduction cast.
3. Notice how Seduction is passing through Divine Shield.

![afce0c0d6d2a2e37c6acb2f2031c0163-png](https://user-images.githubusercontent.com/131232558/234172449-266df34c-c134-4bf0-82fb-cf4290e2edb4.jpg)
![f4b999fcda4c1185005e7a6f3fc8af4d-png](https://user-images.githubusercontent.com/131232558/234172452-06789a53-e016-4330-87c9-7042ade8abfb.jpg)

**IDs of affected creatures, items, quests or spells with a link to the relevant page:**

Spell: https://database.turtle-wow.org/?spell=1020
Spell: https://database.turtle-wow.org/?spell=6358

**Expected behavior. Describe how it should work:**

Seduction should not pass through Divine Shield in any circumstance, same as any other CC ability.

**Comment by Gurky-Turtle** [comment]
https://github.com/slowtorta/turtlewow-bug-tracker/issues/3424
