### ISSUE TITLE
PvP Honor gain for wipes in dungeons

### ISSUE THREAD

**Issue by welpenhund** [slowtorta/turtlewow-bug-tracker#3327]
**Please, provide a clear description what the bug is:**

**Steps to reproduce the behavior with as much detail as possible:**

1. Make any crossfaction group (example - 4 allys - 1 horde)
2.  Wipe in the group as last person. (if they buff you and you have pvp on they get flagged too)
4. You get Honored kills for wiping even though you never attacked them.
5.  That's sadly how some people break the bracket system in WoW ranking discord.

**IDs of affected creatures, items, quests or spells with a link to the relevant page:**

NPC: https://database.turtle-wow.org/?npc=
Item: https://database.turtle-wow.org/?item=
Quest: https://database.turtle-wow.org/?quest=
Spell: https://database.turtle-wow.org/?spell=
Object: https://database.turtle-wow.org/?object=

**Expected behavior. Describe how it should work:**

You are not supposed to get the kills credited done by a boss just because someone has PvP on. (This bug also works in raids against world bosses and inside huge raids like Molten core  and BWL/Naxx)

**Comment by welpenhund** [comment]
seems to be fixed, can be closed

**Comment by Gurky-Turtle** [comment]
closing
