### ISSUE TITLE
WANTED: Murkdeep an invisible NPC appeared and killed me.

### ISSUE THREAD

**Issue by Dragolin4** [slowtorta/turtlewow-bug-tracker#3328]
Quest WANTED: Murkdeep after clearing the camp, the first wave of murlocks (By the battle log Greymist Warrior 12-13 lvl) came running, killing them, we were attacked by an invisible NPC with net ability, like Greymist Netter, but in the battle logs writes that the damage received comes from a kobold miner.

**Steps to reproduce the behavior with as much detail as possible:**

1. Go to Darkshore coast at the norhern most Murloc hovel on the beach.
2. Kill all the murlocs at the hovel.
3. Stand by the seashore near the spawn point Murkdeep.

**IDs of affected creatures, items, quests or spells with a link to the relevant page:**

NPC: 
Quest: https://database.turtle-wow.org/?quest=4740
NPC: https://database.turtle-wow.org/?npc=2204
NPC: https://database.turtle-wow.org/?npc=2205

**Expected behavior. Describe how it should work:**
There should not be an invisible NPC without a model, which cannot be targeted, but which causes damage to the player.
[WoWScrnShot_042623_005927.pdf](https://github.com/slowtorta/turtlewow-bug-tracker/files/11326775/WoWScrnShot_042623_005927.pdf)

**Comment by Gurky-Turtle** [comment]
![image](https://github.com/slowtorta/turtlewow-bug-tracker/assets/90982783/a2f3d603-fe36-4315-8c4d-42a7543b9d9c)
unable to reproduce this no invisible npcs attacked me just the npcs that spawned from the event and they were visible.

**Comment by devwearsprada** [comment]
Can reproduce this. Just AoE in the water where the waves of mobs are spawning. No need to clear the camp.
