### ISSUE TITLE
Seal of the Crusader granting less attack speed than the tool tip states

### ISSUE THREAD

**Issue by Vrerk** [slowtorta/turtlewow-bug-tracker#3329]
I'm currently using a weapon with a speed of 3.2 and currently using rank 4 of SotC; with the stated 45% attack speed increase the swing timer should be 1.76, instead it's 2.21. All previous ranks have the same issue as well.

**Comment by balakethelock** [comment]
It is correct, look at the formula for attack speed. What you want is almost a 90% increase.

**Comment by cyaohiri** [comment]
See the answers in #2923.
