### ISSUE TITLE
Darnassus reputation cloth turn in is given all at once

### ISSUE THREAD

**Issue by Tinyfin-github** [slowtorta/turtlewow-bug-tracker#333]
Darnassus reputation cloth turn in is given all at once

How it should: You turn in cloth and you get the next quest in line with the higher level cloth.
The order should be wool->-silk->mageweave->runecloth->Runecloth(Repeatable)

What does it not work: The Quest are out of order, instead of being linked to the cloth quest next in line they are all linked to runecloth and give all at once

https://database.turtle-wow.org/?quest=7792 A Donation of Wool
https://database.turtle-wow.org/?quest=7798 A Donation of Silk
https://database.turtle-wow.org/?quest=7799 A Donation of Mageweave
https://database.turtle-wow.org/?quest=7800 A Donation of Runecloth
https://database.turtle-wow.org/?npc=14725 Raedon Duskstriker <Alliance Cloth Quartermaster>

![image](https://user-images.githubusercontent.com/83077166/134525834-a4a8072e-3a36-4709-83d8-57909040690b.png)

**Comment by slowtorta** [comment]
This will be fixed on the next update.
