### ISSUE TITLE
Starshards does not flag PvP

### ISSUE THREAD

**Issue by Shieldzies** [slowtorta/turtlewow-bug-tracker#3333]
**Please, provide a clear description what the bug is:**
Attacking an opposite faction player or NPC with Starshards will not pvp flag you. You can even be in a neutral town like Booty Bay, and the guards will not even react to you attacking someone.
**Steps to reproduce the behavior with as much detail as possible:**

1.Be a Night Elf Priest
2. Cast starshards on an enemy faction player or NPC

**IDs of affected creatures, items, quests or spells with a link to the relevant page:**

NPC: 
Item: 
Quest: 
Spell: https://database.turtle-wow.org/?spell=19305
Object: 

**Expected behavior. Describe how it should work:**
Offensive spells should flag you for pvp. This is highly abusable

**Comment by twowTurtReynolds** [comment]
![image](https://github.com/slowtorta/turtlewow-bug-tracker/assets/151180101/0f1102c7-4aff-42f9-afb8-3f52cc8f227e)

**Comment by ratkosrb** [comment]
It should be fixed on the next update.
https://github.com/vmangos/core/commit/4625239137e7652a6f2692ae31f807d49b9725ad
