### ISSUE TITLE
Buffs and heals are incorrectly splitting their threat to every mob

### ISSUE THREAD

**Issue by Zebouski** [slowtorta/turtlewow-bug-tracker#3336]
**Please, provide a clear description what the bug is:**
Heals and buffs have threat based on their spell and also for heals by their effective healing done. 

Here, threat that these generate is split per mob. 

The current bugged implementation causes multitarget tanking too easy, and removes the viability of using buffs like Battle Shout and Bessing of Kings for threat. Though, i do believe BoK specifically had this fixed while the rest of the spells remained incorrect.

**Steps to reproduce the behavior with as much detail as possible:**

1. Install TWThreat, multibox a warrior priest and paladin
2. Pull 1 mob. Do a battle shout. Do a blessing of kings. Do a rank 1 renew on the warrior who took damage and has HP to be healed. Notate all the threat values
3. Pull a 2nd mob. Repeat the same and notice the threat values are halved.

**Expected behavior. Describe how it should work:**
See https://us.forums.blizzard.com/en/wow/t/demoralizing-shout-is-bugged-and-it-is-why-we-have-this-aoe-meta/295678/64

> In addition, we’ve also identified a fix for a separate issue that was causing Battle Shout and most healing spells, effects, and buffs to incorrectly split the threat they generate between enemies that had members of the buffed party on their threat list.
> 
> Hotfixes for these issues are going to be deployed very soon, at which time all of these effects will match their functionality in the 1.12 reference client.

When threat is correctly not split and instead applied to everything, this should allow guides written for classic that mention kings and bshout for threat to work as intended. This will also increase the difficulty of competing as a tank to fight heal threat, to its blizzlike difficulty.

**Comment by Zebouski** [comment]
There is a ton of misinfo about this in both directions. Classic players sourcing vmangos and vice versa, and its all a mess. In favor of this bug report, here's icyveins telling classic players to use bshout on multitarget https://www.icy-veins.com/wow-classic/warrior-tank-pve-rotation-cooldowns-abilities#multi-target-rotation-for-warrior-tanks

As for authoritative sources, what we have is the bluepost I linked saying threat splitting was incorrect compared to their actual 1.12 source code.

**Comment by Zebouski** [comment]
I forgot that Classic's api actually reports accurate threat data from the server, like twthreat does here. Last i remember, Details' Tinythreat is good for this.  If anyone still has access to classic era to test if heal/bshout/kings threat splits or not, with the same methodology, that would probably be the authority to go by.

**Comment by balakethelock** [comment]
Demoralizing shout here works as intended (as was 2007 vanilla, and as blizzard hotfixed it in classic). It generates a small amount of threat (Around 40, vanilla sources said "a sixth of a sunder" which is about right)
source for that here. Demo shout's threat is testable here with the addon and you'll find it to be 40 raw. https://wowwiki-archive.fandom.com/wiki/Kenco%27s_research_on_threat#:~:text=Demo%20Shout%3A%2043%20(42.8%20%2D%2043.8)

The classic bug was something entirely different (demo shout did more threat on each mob the more mobs it hit, basically it did 40 threat if you hit one mob, but it did 80 threat on both mobs if you hit two).

Battle shout is indeed bugged here, it splits threat to all enemies in combat. The correct behavior is doing static threat to all enemies regardless of how many are in combat.

As for healing threat. The correct behavior is splitting, the Blizz post is wrong (and I think they didnt actually implement what they said for healing, they only implemented the demo shout fix>which made demo shout work like it works here already)

http://web.archive.org/web/20071219022452/http://elitistjerks.com/f31/t9258-kenco_guide_threat/

**Comment by Zebouski** [comment]
Sounds like you're right about the healing aspect, that the bluepost was wrong about that. Would definitely be nice to see some hard evidence as to how classic era works.

**Comment by Belrand** [comment]
**As far as Classic is concerned:** 
Threat generated by Buffs and Heals is/was split between the targets in combat.

Tests were done after the Battle Shout/Demo Shout fix by Fight Club Discord and results can be seen on [magi's github](https://github.com/magey/classic-warrior/wiki/Threat-Mechanics#battle-shout-testing) where threat is indeed split (see tests 5 and 6)

The Blue Post mentionned that threat was "incorrectly split" but never elaborate on whether the split was incorrect or if the value of the split was incorrect.  A quick look through old FC post seems to indicate that threat was being split more times than intended. 
I vaguely recall someone testing this and reporting that extra threat was being generated from ally buffed who were not in combat with the target or that some mobs wouldn't receive any threat if they were outside of exp range but I didn't find anything conclusive.

I also recall someone mentionning that threat was only being split if the targets belonged to the same faction (i.e. if you pulled a red mob and a yellow mob, threat wouldn't be split between them) but I can't find anything substantial on the subject either.


**About "vanilla":**
Here should be the [webarchive link](https://web.archive.org/web/20061218200637/http://evilempireguild.org:80/guides/kenco2.php) of the original Kenco Guide (date of last edit July 2006) that already mentions `These forms of buffs all have infinite range; they will cause threat to all mobs on whose threat list you are on. Furthermore, the threat caused is split equally among all the affected mobs. If you are on one mobs threat list, a 1000 point heal will cause 500 threat to that mob. If 5 mobs are aware of you, the same heal will cause 100 threat on each mob.` which would confirm that Threat Split is the correct behaviour

It's worth mentionning that TBC prepatch (v2.0.1 Dec 2006) lists a fix to Battle Shout "causing too much threat" but it's never specified exactly what was the issue that caused "too much threat"
I honestly wouldn't bet on Blizzard being good at communicating anything tbh

**Comment by Muigin** [comment]
Working as intended.
