### ISSUE TITLE
Dire bear form enters combat

### ISSUE THREAD

**Issue by burner1024** [slowtorta/turtlewow-bug-tracker#3337]
**Please, provide a clear description what the bug is:**
Shifting to dire bear put the character in combat.
(Probably the same with usual bear, can't test.)

**Steps to reproduce the behavior with as much detail as possible:**

1. Shift to dire bear.
2. See that food on actions bars is darkened out. That doesn't happen with other forms.
  (Or use any addon that shows combat state.)

**IDs of affected creatures, items, quests or spells with a link to the relevant page:**

Spell: https://database.turtle-wow.org/?spell=9634

**Expected behavior. Describe how it should work:**
The act of shifting by itself should not trigger combat.

**Comment by burner1024** [comment]
Looks like a hack, in that case.

**Comment by cyaohiri** [comment]
According to https://wowpedia.fandom.com/wiki/Furor, this didn't change until patch 2.2.0: "Patch 2.2.0: Enrage and Furor should no longer initiate combat, though it will prevent rage decay for the duration."

**Comment by burner1024** [comment]
I think it's a more sensible implementation.

**Comment by twowTurtReynolds** [comment]
Working as Blizzard intended.
