### ISSUE TITLE
Improved sap most recent changes cause npcs to aggro onto you if you sap a player in AV

### ISSUE THREAD

**Issue by lovelymuffins** [slowtorta/turtlewow-bug-tracker#3339]
**Steps to reproduce the behavior with as much detail as possible:**

1. Find a player near some npcs in AV, this can include archers in the towers while the player is on the ground
2. Sapping the player will put you into combat aggroing the npcs which will attack you pulling you out of stealth.

**IDs of affected creatures, items, quests or spells with a link to the relevant page:**

Spell: https://database.turtle-wow.org/?spell=11297
Talent: https://database.turtle-wow.org/?spell=14094

**Expected behavior. Describe how it should work:**
Before the most recent patch it did not do this. You stayed stealth. This was never an issue. I could sap someone near npcs and it would not cause them to aggro to me.

Additional information
I only tested this Alliance side and I uploaded a quick video showing I have imp sap talented and sapped someone near npcs. 
https://www.youtube.com/watch?v=iEbPds4r5As&ab_channel=lovelymuffins
I tested different weapons, poisons on or off doesn't matter.
I also spent around 3 minutes sapping npcs to confirm it is only related to players near npcs.

**Comment by ratkosrb** [comment]
It will be fixed after the next update.
