### ISSUE TITLE
Shadowguard not working as intended 

### ISSUE THREAD

**Issue by M0nkeys1ut** [slowtorta/turtlewow-bug-tracker#3341]
**Please, provide a clear description what the bug is:**

Shadowguard the troll racial priest spell, isn't working as intended:
Unlike blizz-like classic, shadowguard never proc when spells and ranged attacks hit a priest under any shield effect.

This is preventing the synergy between Power Word: Shield and Shadowguard and blackout.
This is breaking a core gameplay feature for troll priests.

**Steps to reproduce the behavior with as much detail as possible:**

1. Auto target cast Power Word: Shield on the Troll Priest
2. Cast Shadowguard on the Troll Priest
3. Ranged attacks and spells won't trigger shadowguard ever... While melee hits work as intended.

**IDs of affected creatures, items, quests or spells with a link to the relevant page:**

Spell: https://database.turtle-wow.org/?spell= ???
It is not present on the dB.

**Expected behavior. Describe how it should work:**

As in offi Blizz vanilla and classic, Shadowguard should be able to proc from ranged attacks and spells (just as it does with melee attacks) while Power Word: Shield is up.

Shadowguard proc when the character is HIT by something NOT when damage occurs. 

https://github.com/slowtorta/turtlewow-bug-tracker/issues/386

**Comment by ratkosrb** [comment]
https://user-images.githubusercontent.com/35845488/235085021-9ba2d756-cdf6-484d-86d1-23d27abcda6b.mp4

I can't reproduce the issue. As you can see in my test video, I take damage from Shadowguard after casting Fireball on a priest with Power World: Shield.
