### ISSUE TITLE
Mount still makes no sound AFTER CLIENT UPDATE

### ISSUE THREAD

**Issue by Redeemer166** [slowtorta/turtlewow-bug-tracker#3345]
I recently purchased a Palomino mount and it makes no footstep sounds or mount special (spacebar) sounds.

1.Use mount from spellbook
2. press spacebar while stationary for mount special
3. run around on mount

Item: https://database.turtle-wow.org/?item=12354
Spell: https://database.turtle-wow.org/?spell=16082

The mount should make horse hoof sounds when running and whinny or neigh when using mount special as on classic wow.

I have updated to latest client to no avail.

**Comment by slowtorta** [comment]
I didn't mean that you have to update your client... It requires a client patch from our side, the next planned is 1.16.6. Please stay patient :)

**Comment by Redeemer166** [comment]
Oh I see, apologies for my impatience. I do appreciate what you guys do
