### ISSUE TITLE
Razormane pathfinder thrash granting too many attacks?

### ISSUE THREAD

**Issue by Kangaroux** [slowtorta/turtlewow-bug-tracker#3346]
Pathfinders have thrash which is only supposed to give 2 additional attacks, but I got hit 5 times in total. This seems to happen if you pull a pathfinder from range. As soon as it runs to you, you get hit with a massive burst of attacks.

https://database.turtle-wow.org/?npc=3456

![image](https://user-images.githubusercontent.com/2302541/235259392-eb3dbc2c-ba1a-4f3d-9891-a0836e9719b3.png)

**Comment by Kangaroux** [comment]
@Gurky-Turtle I don't know what info if you are looking for it you don't tell me

**Comment by Gurky-Turtle** [comment]
Proof of your claims on how it should work as well of proof of only one npc hitting that many times in a row, there are no timestamps in your screenshot above.
