### ISSUE TITLE
Threat does not reset on death 

### ISSUE THREAD

**Issue by geojak** [slowtorta/turtlewow-bug-tracker#3347]
**Please, provide a clear description what the bug is:**

When you die, your threat should be cleared. On twow it stays

**Steps to reproduce the behavior with as much detail as possible:**

1. Be first in thread in raid
2. Die
3. Get battle rezzed
4. Accept
5. You might be still first on trhest since it did not reset 
6. Immidietly on rezz get boss aggro back and die again

**Expected behavior. Describe how it should work:**
After a battle rezz you should start with 0 threat again

**Comment by StasyaLight** [comment]
Agree, as a priestess can say: every cast of Prayer of Healing when Fade spell in 30sec CD makes 100% death cause of threat. As priest u haven't paladin's bubble, only cloth armor, Physic Scream with same 30sec CD (that u can't cast in 90% cases or it will wipe all raid/group) and Fade spell.

So every time when u get lucky to have res in combat, u immediately become a target for boss/mobs even with no single cast yet.

**Comment by twowTurtReynolds** [comment]
According to TWT, threat resets on death now.
