### ISSUE TITLE
Missing NPC Krolg for Quest Raene's Cleansing

### ISSUE THREAD

**Issue by viper712** [slowtorta/turtlewow-bug-tracker#3348]
1. Quest name "Raene's Cleansing" 
2. On the 7th part of the quest, you have Dartol's Rod of Transformation and you need to speak with a furbolg named "Krolg". 
3. Krolg is supposed to be near the Crescent Grove entrance on top of the waterfall on the south east side of Mystral Lake but he is missing. 

NPC: https://database.turtle-wow.org/?npc=3897
Quest: https://database.turtle-wow.org/?quest=1045

**Comment by Herdon** [comment]
You mean the level 9 Furbolg who is hostile to Horde and gets killed almost every time a Horde group is nearby?

**Comment by viper712** [comment]
Ah. my mistake then. I sat there awhile thinking there was an issue.

**Comment by viper712** [comment]
In case anyone else see's this and is confused like me. Krolg isn't on the top of the waterfall. He's at the base of the ramp. Near 54, 74.
