### ISSUE TITLE
Transmogrified Bloodvine Vest breaks set bonus :(

### ISSUE THREAD

**Issue by hjortmar** [slowtorta/turtlewow-bug-tracker#3350]
**Please, provide a clear description what the bug is:**

**Steps to reproduce the behavior with as much detail as possible:**

1. Transmogrify the Bloodvine vest, boots and/or legs.
2. Equip your fresh items.
3. Look at character sheet and see that the set bonus is no longer applied.

**IDs of affected creatures, items, quests or spells with a link to the relevant page:**

Item: https://database.turtle-wow.org/?search=bloodvine

**Expected behavior. Describe how it should work:**

**Comment by Gurky-Turtle** [comment]
This is just a graphical bug you still get the bonus.
