### ISSUE TITLE
Forging The Mightstone (Paladin Quest)

### ISSUE THREAD

**Issue by McSaltyCakes** [slowtorta/turtlewow-bug-tracker#3352]
**Please, provide a clear description what the bug is:**
-I do not know if it is a bug, however, when going through Sunken Temple and killing all people needed. It did not drop 1 Green feather. I was unable to complete the quest but everyone else got their feather. I was wondering if that was intentionally? If not, could I get that added into the bag?

**Steps to reproduce the behavior with as much detail as possible:**

1. Kill one of the mini bosses in ST.

**IDs of affected creatures, items, quests or spells with a link to the relevant page:**

Item: https://www.wowhead.com/classic/item=20608/green-voodoo-feather
Quest: https://www.wowhead.com/classic/quest=8418/forging-the-mightstone

**Expected behavior. Describe how it should work:**
-Drop the item.

**Comment by slowtorta** [comment]
![image](https://user-images.githubusercontent.com/66763404/236456755-d8721d13-dacc-4188-99f5-e395e2cd88e9.png)
This is working as intended. Please visit the dungeon one more time!
