### ISSUE TITLE
(ROGUE) Using Flourish/Slice and Dice on OOC Mobs puts you in combat and Aggros said mob

### ISSUE THREAD

**Issue by imaglcian** [slowtorta/turtlewow-bug-tracker#3355]
**Please, provide a clear description what the bug is:**

When using Slice and Dice or Flourish, you can now be put in combat and Aggro the minion who had the combo points on him, despite it not being supposed to work like that. There's a range limit shown in the video, but this should never happen.
https://www.youtube.com/watch?v=Ceav9jMHa00

**Steps to reproduce the behavior with as much detail as possible:**

1. Have combo points on a random mob.
2. Use Slice and Dice / Flourish in a medium range.
3. Mob should aggro you if you are close enough. (Range is weird, but again, this should never happen)

**Expected behavior. Describe how it should work:**

* Using Flourish/Slice and Dice should never aggro any mob, since it is a self-buff and doesn't add any threat anywhere (Or isn't supposed to).
* It is however supposed to put you in combat when using.

**Comment by Muigin** [comment]
This has been fixed in a previous update.
