### ISSUE TITLE
Solenor fearing when not rooted

### ISSUE THREAD

**Issue by ArthurusMenks** [slowtorta/turtlewow-bug-tracker#3358]
**Please, provide a clear description what the bug is:**
Solenor's fear ability should not be used when he's nor rooted but it's encounter rn is bugged, not only he's perma enraged which I have already writen a report on it but also discovered that he shouñdn't be spamming his fear ability when not rooted which he keeps doing when you use concussive shoot on him, which I suppose has something to do with the slow part of the spell.
**Steps to reproduce the behavior with as much detail as possible:**

1. When fighting solenor (as a hunter obvs) cast conc shot
2. Solenor gets conc shot and slowsdown but it detects himself as rooted
3. Solenor casts his fear ability when he should not because he's slowed not rooted which makes his 

**IDs of affected creatures, items, quests or spells with a link to the relevant page:**

NPC: https://database.turtle-wow.org/?npc=14530

**Expected behavior. Describe how it should work:**
Should just try to keep catching up with the hunter as normal without casting the spell

**Comment by twowTurtReynolds** [comment]
Tracking under https://github.com/slowtorta/turtlewow-bug-tracker/issues/1142
