### ISSUE TITLE
List of npc that become uninteractable sometimes

### ISSUE THREAD

**Issue by Tinyfin-github** [slowtorta/turtlewow-bug-tracker#336]
List of npc that become uninteractable sometimes

https://database.turtle-wow.org/?npc=12939 Doctor Gustaf VanHowzen 
https://database.turtle-wow.org/?npc=11711 Sentinel Aynasha
https://database.turtle-wow.org/?npc=5089 Balos Jacken
https://database.turtle-wow.org/?npc=11832 Keeper Remulos
https://database.turtle-wow.org/?npc=7774#ends Shay Leafrunner
https://database.turtle-wow.org/?npc=5644#starts Dalinda Malem
https://database.turtle-wow.org/?npc=1265#starts Rudra Amberstill
https://database.turtle-wow.org/?npc=2917 Prospector Remtravel

When you click on them the character just emotes. A GM has to kill them and revive them for them to be interactable again.  
Sometimes they are found at different location then were they were supposed to be.  This might happen after their scripted event is failed and they don't reset properly.

**Comment by slowtorta** [comment]
Could you please verify that this issue is still present?

**Comment by Gumba826** [comment]
Attempted to interact with Keeper Remulos today for a turn in, and npc was uninteractable as described above. No dialogue window to complete the quest.
