### ISSUE TITLE
Naxx Shoulder Enchants Bug

### ISSUE THREAD

**Issue by OdessaCubbage** [slowtorta/turtlewow-bug-tracker#3361]
Naxx Enchants [Power of the Scourge](https://database.turtle-wow.org/?item=23545) and [Resilience of the Scourge](https://database.turtle-wow.org/?item=23547) are both partially bugged.
Power of the Scourge correctly applies the spell damage bonus but does not apply the spell crit bonus.
Resilience of the Scourge correctly applies the mp5, but does not apply the bonus to healing power.

This can be reproduced by applying either of these to shoulder enchants and observing the effect, both what is present and lacking, on the player's stats.

**Comment by Zmitrok1984** [comment]
How do you measure the fact that the enchant is not applied?
In case  some addon like BetterCharacterStats, may be your addon doesn't count enchant?

**Comment by OdessaCubbage** [comment]
In the case of the healing bonus the addon detects other healing enchants without issue. I don’t know of other spell crit enchants to compare with though, so it’s possible it doesn’t pick that up.

However I’m also not the only one to experience this, the bug is fairly well known among Naxx raiders and the lack of impact is reflected in logs. I should see if I can dig some up where it was tested.

**Comment by Kuz-Shaman** [comment]
I can confirm this Issue. Feels bad to have a worse enchant than zg enchant now... please fix

**Comment by Kuz-Shaman** [comment]
Can a dev confirm that the enchant is broken?
Is there a way to read the actual character stats from the game? In my Case, spellpower portion is shown on improved character stats addon but it does not add the spellcrit.

**Comment by lyssebabz** [comment]
It haven't worked for a loooong time!

**Comment by lyssebabz** [comment]
It does show spellpower in my character sheet but not crit

**Comment by Kuz-Shaman** [comment]
I did some testing as well, but I could not find a significant difference with and without enchant, maybe due to margin of error. It's 1% afterall. I did 1000 spells (firestrike) 6 times and got no clear winner. All within +- 0,5%

**Comment by Gurky-Turtle** [comment]
If you are going off what an addon tells you for this the addon was not programmed to read this enchant. As you can see here I had to manually add the enchant to the addon: https://github.com/Gurky-Turtle/BetterCharacterStats 

Good rule of thumb is never trust what old stat addons give you seeing they have to be programmed to read item stats off the item tool tips. 

This bug needs more proof with actual numbers with and without the enchant applied. 

Related https://github.com/slowtorta/turtlewow-bug-tracker/issues/3066
