### ISSUE TITLE
Porting to Goldshire | Not being ported after clicking NPC action.

### ISSUE THREAD

**Issue by jlautenbach** [slowtorta/turtlewow-bug-tracker#3362]
**Please, provide a clear description what the bug is:**
Unable to teleport from The Farstrider Loge to Goldshire via Magistrix Ishalah. After completing all starting quests, you are summoned to Magistrix Ishalah to get teleport to Goldshire. Upon clicking nothing happens.

**Steps to reproduce the behavior with as much detail as possible:**

1. Get Quest Porting to Goldshire
2. When talking to NPC Magistrix Dugan click on 'I'm ready. Teleport me to Goldshire!'
3. Nothing happens

**IDs of affected creatures, items, quests or spells with a link to the relevant page:**

NPC: https://database.turtle-wow.org/?npc=80213
Quest: https://database.turtle-wow.org/?quest=80209

**Expected behavior. Describe how it should work:**
After clicking NPC dialog: 'I'm ready, Ishalah. Teleport me to Goldshire!' you have expect to be teleported.

**Comment by jlautenbach** [comment]
Will look into this.

**Comment by Nimawei** [comment]
Not a bug, you're supposed to talk to the Magistrix and then she will activate an object next to her:
![image](https://user-images.githubusercontent.com/132086678/235548914-dcedd4c0-b55d-4185-b8de-2a95b467ef93.png)

You're supposed to interact with that object.
