### ISSUE TITLE
Defias Trapper ability Net, can break it's own root such as Ice Nova.

### ISSUE THREAD

**Issue by DragoSlayin12** [slowtorta/turtlewow-bug-tracker#3363]
**Please, provide a clear description what the bug is:**

**Steps to reproduce the behavior with as much detail as possible:**

1. Engage Defias Trapper.
2. Cast Ice Nova, to root it in place.
3. Defias Trapper is now rooted, it casts net, the net breaks it's root instantly, and roots you.

**IDs of affected creatures, items, quests or spells with a link to the relevant page:**

NPC: https://database.turtle-wow.org/?npc=504
Item: https://database.turtle-wow.org/?item=
Quest: https://database.turtle-wow.org/?quest=
Spell: https://database.turtle-wow.org/?spell=12024
Object: https://database.turtle-wow.org/?object=

**Expected behavior. Describe how it should work:**
Expected behavior is, an enemy casting a root ability DOESN'T break it's own fucking root! And no, the Trapper that killed my HC character didn't resist my Ice Nova, I literally watched it get frozen in place, only to root me and break it's own root.

**Comment by balakethelock** [comment]
Frost nova can break randomly at any moment. That is called a Heartbeat Resist.
