### ISSUE TITLE
Bloodlust Bug

### ISSUE THREAD

**Issue by Tugryn** [slowtorta/turtlewow-bug-tracker#3366]
Good evening.
I found a bug abuse.
Some shamans can use Bloodlust (rank 2) ability not in enhancement spec because of a bug, although it's only enhancement  ability.
I saw how healer did it.

**Comment by balakethelock** [comment]
I see warrior tanks use bloodthirst, because they specced into it. Some healers spec into Bloodlust. You're not saying you inspected them and made sure they don't have the talent, you're just saying you saw them do it as a healer. So due to lack of detail I'd say this is not a bug.

**Comment by Tugryn** [comment]
It was a pure healer, not enhancement shaman with healer's gear, i inspected him.
That's why i was confused when i heard the sound of Bloodlust. 
We talked about it and he said that he just has this ability in the spell book.
He is old player on this server, and old players can use something that new players can't use, like items with old stats.
They abuse both bugged abilities and broken items in raids.

**Comment by Muigin** [comment]
Not enough information.
