### ISSUE TITLE
Female goblin head and hair has issues with many head pieces (masks / shrouds included)

### ISSUE THREAD

**Issue by mou244** [slowtorta/turtlewow-bug-tracker#3368]
**Please, provide a clear description what the bug is:**
Many headpieces have issues with the goblin model or hair.

**Steps to reproduce the behavior with as much detail as possible:**

1. Be female goblin.
2. Put on any face mask.
3. Put on something that covers hair (see clipping with any hairstyle).
![image](https://user-images.githubusercontent.com/108933524/235494990-c66cd927-dfe7-4322-bee7-d8a917d06941.png)
![image](https://user-images.githubusercontent.com/108933524/235495056-1e58dfea-865d-4bb5-a93a-b844df198902.png)

**IDs of affected creatures, items, quests or spells with a link to the relevant page:**

**Item:** 
https://database.turtle-wow.org/?item=11925   <- Hair example
https://database.turtle-wow.org/?item=7997     < - Mask example

**Expected behavior. Describe how it should work:**
The cheekbones shouldn't clip through face masks (it should be sized up a bit to compensate maybe), and hair shouldn't be visible through the top of shrouds and other headpieces. <3

**Comment by twowTurtReynolds** [comment]
![image](https://github.com/slowtorta/turtlewow-bug-tracker/assets/151180101/97f031d7-5851-4306-a880-2c3038798340)

Some much more minor clipping:
![image](https://github.com/slowtorta/turtlewow-bug-tracker/assets/151180101/6a6b2fee-3c7f-4811-9c40-0d51405c58ab)
