### ISSUE TITLE
Gnomiosh Net-o-matic projector

### ISSUE THREAD

**Issue by welpenhund** [slowtorta/turtlewow-bug-tracker#3371]
**Please, provide a clear description what the bug is:**

**Steps to reproduce the behavior with as much detail as possible:**

1. Throw net as a druid
2.  If it fails and only root you, then you are unable to shift out of it, it keeps spamming the root effect on you

**IDs of affected creatures, items, quests or spells with a link to the relevant page:**

NPC: https://database.turtle-wow.org/?npc=
[Item: https://database.turtle-wow.org/?item=10720
Quest: https://database.turtle-wow.org/?quest=
Spell: https://database.turtle-wow.org/?spell=
Object: https://database.turtle-wow.org/?object=

**Expected behavior. Describe how it should work:**
As a druid you should be able to shift out of it....

**Comment by ratkosrb** [comment]
The self debuff will be removed upon shapeshifting after the next update.
