### ISSUE TITLE
"The Battle of Darrowshire"

### ISSUE THREAD

**Issue by Nemoose** [slowtorta/turtlewow-bug-tracker#3373]
**Please, provide a clear description what the bug is:**

When the Event of "The Battle of Darrowshire" is started with a horde character, all friendly NPCs will be taged as "Ogrimmar" (haven't tested it, but I guess, if alliance charakter start the event the NPC will be taged as "Stormwind").
Because of this the friendly NPC you should protect will attack parts of your own group (if you are crossfaction) but they are also from the beginning till the end green (friendly) to every player and can't be attacked.

**Steps to reproduce the behavior with as much detail as possible:**

1. Start the Event of the Quest "The Battle of Darrowshire"
2. Have a crossfaction group
3. Get attacked by green (friendly) NPCs till you die or run away

**IDs of affected creatures, items, quests or spells with a link to the relevant page:**

NPC: 
https://database.turtle-wow.org/?npc=10948
https://database.turtle-wow.org/?npc=10944
https://database.turtle-wow.org/?npc=10937

Item: https://database.turtle-wow.org/?item=15209

Quest: https://database.turtle-wow.org/?quest=5721

Spell: https://database.turtle-wow.org/?spell=18987

Object: https://database.turtle-wow.org/?object=944

**Expected behavior. Describe how it should work:**

I expected the friendly NPCs to be friendly to both factions and/or be red to the other faction especialy once the NPC starts attacking a player. A Gamemaster told me that some quests can't be done with crossfaction, but i think in this case there is no real reason why, because both faction can have the same Quest, looking like an oversight when crossfaction was intruduced.
I can't describe how it should work, since i have no information how the NPC reacted to the other faction on a blizzard Server, but my guess is they would be atleast red and attackable or just friendly to everyone.

Thanks for your time and help

**Comment by ratkosrb** [comment]
They will be friendly to all players after the next update.
