### ISSUE TITLE
Advenced target Dummy - loot after killed or expired divided to party/raid members

### ISSUE THREAD

**Issue by Avlli** [slowtorta/turtlewow-bug-tracker#3375]
Hello,

Advenced target Dummy after killed or expired drops look for All party/raid members.
It should be restricted for user only.

So far am using only Advenced target dummy

**Comment by RUTHINAS** [comment]
This is a copy of #3115

The bug was fixed in a patch some time ago, but the fix introduced another bug entirely – the dummies had no loot. This fix was then rolled back, and the original bug persists.

**Comment by Gurky-Turtle** [comment]
Please keep the comments in the bug you linked above seeing it is still open.
