### ISSUE TITLE
Lady Katrana Prestov - please reduce respawn time

### ISSUE THREAD

**Issue by wingoswk** [slowtorta/turtlewow-bug-tracker#3376]
Please, provide a clear description what the bug is:
That is not a bug, i have raised also a GM ticket in-game with this wish proposal - reducing the respawn timer after final onyxia encounter

Steps to reproduce the behavior with as much detail as possible:

1. wait till npc respawns
2. try to turin in q with fat fingers
3. cant do it as someone is faster and start the encounter wiht final ony q

IDs of affected creatures, items, quests or spells with a link to the relevant page:

NPC: https://database.turtle-wow.org/?npc=1749

Expected behavior. Describe how it should work:
It works as expected probably, when there is not 6k people online.

Today i have been victim of numerour tries to turn in q to said NPC, but it was impossible duo to long queue of people trying to turn in various quests to said npc.
the respawn took a long time in my opinion and makes it unpleasant for a people. There was 9 people waiting for a respawn, some of those people havent turn in q as the encounter was started by someone.
Please consider reducing respawn time, thanks.

**Comment by ratkosrb** [comment]
Her respawn time is only 3 minutes.
