### ISSUE TITLE
Hunter Taming quest lvl 10 High Elf

### ISSUE THREAD

**Issue by Graggaw** [slowtorta/turtlewow-bug-tracker#3377]
**Please, provide a clear description what the bug is:**
After taking the taming hunter quest I can tame pets and call them But nothing more, like feeding them or training them.
**Steps to reproduce the behavior with as much detail as possible:**

1. Took the lvl 10 quest for hunter for taming pets
2. Finished it succesfully but havent recieved skills Revive pet, Train, Feed
3. I can only use Call pet or Tame beast so pet always disapears since I cant feed it

**IDs of affected creatures, items, quests or spells with a link to the relevant page:**

NPC: https://database.turtle-wow.org/?npc=
Item: https://database.turtle-wow.org/?item=
Quest: https://database.turtle-wow.org/?quest=
Spell: https://database.turtle-wow.org/?spell=
Object: https://database.turtle-wow.org/?object=

**Expected behavior. Describe how it should work:**
Usually you can feed the pet so It stays with you without the abilities it just runs away for lack of loyality.

**Comment by Gurky-Turtle** [comment]
You have to do the Training the Beast quest after the Taming quests to learn the other spells. https://database.turtle-wow.org/?spell=6991
