### ISSUE TITLE
highelf warrior no weapon on character creation screen

### ISSUE THREAD

**Issue by geojak** [slowtorta/turtlewow-bug-tracker#3379]
**Please, provide a clear description what the bug is:**

make new character
click highelf warrior
see that the char does not have a weapon in hand in the customization screen

**Expected behavior. Describe how it should work:**

any class/race combo should have a weapon in their hand on character creation screen

**Comment by slowtorta** [comment]
Fixed in the next patch.

**Comment by twowTurtReynolds** [comment]
![image](https://github.com/slowtorta/turtlewow-bug-tracker/assets/151180101/6b4657b0-eb71-4f36-ade2-16b20334edb8)
