### ISSUE TITLE
Chillwind Chimera (Winterspring) Lighting Breath is not interruptable

### ISSUE THREAD

**Issue by trumpetx** [slowtorta/turtlewow-bug-tracker#338]
**Please, provide a clear description what the bug is:**
Chillwind Chimera (Winterspring) Lighting Breath is not interruptible

**Steps to reproduce the behavior with as much detail as possible:**

1. Fight a Chillwind Chimera
2. Kick Lightning Breath

Expected:
  3. It interrupts the spell
Actual:
  3. It does not interrupt the spell

**IDs of affected creatures, items, quests or spells with a link to the relevant page:**

NPC: https://database.turtle-wow.org/?npc=7448
Spell: https://database.turtle-wow.org/?spell=15797

**Expected behavior. Describe how it should work:**
The spell should be interrupted as seen on Classic (tested today) servers (and from memory, old Vanilla).

Possibly related to #267

**Comment by Nolin7777** [comment]
Please provide any proof in form of a picture or video.
CLosed until proof added.

**Comment by trumpetx** [comment]
What proof is required?  This is 100% a bug.  I checked on Classic and it is fully interruptible.

**Comment by jameyboor** [comment]
A video showing the expected behavior would be enough.

**Comment by trumpetx** [comment]
https://1drv.ms/u/s!AvHvz0tSpeAOujx-8rFSKYvSXaO2?e=DyIhKz

**Comment by jameyboor** [comment]
Thanks, I'll look at it.

**Comment by slowtorta** [comment]
Fixed in the next revision.
