### ISSUE TITLE
Grimoire of Avoidance is unusable (new warlock tome)

### ISSUE THREAD

**Issue by jongdetim** [slowtorta/turtlewow-bug-tracker#3383]
**Please, provide a clear description what the bug is:**

The Grimoire of Avoidance warlock item doesn't work. When you try to use it, nothing happens except a message in red showing up that states your pet can't learn that ability. It doesn't matter which demon pet you have out. I assume this has to do with a previous bug where players could learn the avoidance skill, and it would half the aoe damage they take AND deal. Perhaps the fix for that issue didn't resolve all issues with the item.

**Steps to reproduce the behavior with as much detail as possible:**

1. Buy the Grimoire of Avoidance at lvl 40 from the gnome warlock trainer in the Slaughtered Lamb in SW. Notice the item description.
2. Try using the tome without a pet, and with every warlock pet, but it says something along the lines of: 'your pet can't learn that spell'
3. Check your pets' spellbook to make sure they didn't learn the ability.

**IDs of affected creatures, items, quests or spells with a link to the relevant page:**

Item: https://database.turtle-wow.org/?item=83584

**Expected behavior. Describe how it should work:**

The item should, when used, teach warlock pets the avoidance skill, which reduces aoe damage taken by 50%.

**Comment by Doombabe** [comment]
Can confirm that this is an issue for myself, and for all warlocks I've heard from in the guild discord.

I've tried teaching it to all demons, both while targeting or not targeting the demon, and always get the same game error: "That ability is not available to your pet."

**Comment by BouggaGnema** [comment]
I am also having this issue. I saw on a forum to “just put in a ticket and they’ll give you your 2g back. It’s a known issue.” Whoever answered my ticket did nothing of the sort. They told me to put in a ticket to the GitHub.

**Comment by twowTurtReynolds** [comment]
This person https://github.com/slowtorta/turtlewow-bug-tracker/issues/4143 has it learned to voidwalker?

**Comment by twowTurtReynolds** [comment]
Something must have changed, the item is completely missing from the DB. I suppose disabled until the devs can get it in correctly, in which case we will QA its implementation and avoid this. Closing as this is no longer a public bug.
