### ISSUE TITLE
Steeljaw Snapper Skinning Loot table issues.

### ISSUE THREAD

**Issue by Nimawei** [slowtorta/turtlewow-bug-tracker#3386]
**Please, provide a clear description what the bug is:**
Whenever you skin the Steeljaw Snappers on the coast of Tanaris (Steamwheedle Port), their skinning loot table seems to be... not functioning correctly. Often times, it will give absolutely zero rewards (no skins, no turtle scale, no hide) and sometimes it will give one of each. As far as I'm aware, it should only net one of the items in the loot table, but not more than one (or none at all).

**Steps to reproduce the behavior with as much detail as possible:**

1. Kill Steeljaw Snapper
2. Apply Skinning
3. Receive multiple drops from the Skinning Loot pool for this mob (or none)

**IDs of affected creatures, items, quests or spells with a link to the relevant page:**

NPC: https://database.turtle-wow.org/?npc=14123
Spell: https://database.turtle-wow.org/?spell=10768

**Expected behavior. Describe how it should work:**
When skinning the turtles, they should net one of the following:
https://database.turtle-wow.org/?item=4304
https://database.turtle-wow.org/?item=8167
https://database.turtle-wow.org/?item=4234
https://database.turtle-wow.org/?item=8169
https://database.turtle-wow.org/?item=4235

And not multiples (or none).

**Comment by slowtorta** [comment]
This is normal in Vanilla that skinning loot not always gives you an item.
