### ISSUE TITLE
Heavy Leather Ball can be thrown from a normal character to a HC character allowing a 'trade' of sorts.

### ISSUE THREAD

**Issue by thrassoss** [slowtorta/turtlewow-bug-tracker#339]
**Please, provide a clear description what the bug is:**

A Heavy Leather Ball (as crafted by a leatherworker or thrown Zebrain the Mad) by can be traded from a normal character to a Hardcore character.  This allows a very limited trade as it's vendor price is 5 copper.   

**Steps to reproduce the behavior with as much detail as possible:**

1.

Craft a Heavy Leather ball or get one thrown at you by the NPC Zebrain the Mad.

2.

Throw it at a HC character.

3. 

**IDs of affected creatures, items, quests or spells with a link to the relevant page:**
https://database.turtle-wow.org/?item=18662#created-by

NPC: https://database.turtle-wow.org/?npc=

https://database.turtle-wow.org/?npc=50103

Item: https://database.turtle-wow.org/?item=

https://database.turtle-wow.org/?item=18662#created-by

Quest: https://database.turtle-wow.org/?quest=
Spell: https://database.turtle-wow.org/?spell=
Object: https://database.turtle-wow.org/?object=

**Expected behavior. Describe how it should work:**

A Heavy Leather Ball (as crafted by a leatherworker or thrown Zebrain the Mad) by can be traded from a normal character to a Hardcore character.  This allows a very limited trade as it's vendor price is 5 copper.   The conversion of money would be very limited like 100g from a normal character to 1g for a HC character but could be done.  Maybe make the ball worth 0. Or add a check to prevent it.

**Comment by slowtorta** [comment]
Alright, let's make it cost 0 copper :)
