### ISSUE TITLE
Druid Talent Bugged

### ISSUE THREAD

**Issue by Kharkov72** [slowtorta/turtlewow-bug-tracker#3390]
**Please, provide a clear description what the bug is:**
Blood frenzy, the druid feral talent, provides 10 rage when using Enrage, even though I only have one point in it, where I should only be getting 5.
**Steps to reproduce the behavior with as much detail as possible:**

1. Apply one talent point to Blood Frenzy in feral, tier 4.
2.  Use enrage.
3.  Gaze upon your instant 10 rage.

**Comment by Kharkov72** [comment]
![Untitled](https://user-images.githubusercontent.com/25846834/236371530-d51e72b5-afb1-4d5a-b104-3e3180ac3868.png)
Evidence.

**Comment by Gurky-Turtle** [comment]
Related https://github.com/slowtorta/turtlewow-bug-tracker/issues/2419
