### ISSUE TITLE
Holy strike double dips on +% damage buffs

### ISSUE THREAD

**Issue by Zebouski** [slowtorta/turtlewow-bug-tracker#3393]
**Please, provide a clear description what the bug is:**
Buffs like darkmoon faire's 10% damage, and PVP's 30% damage berserker, thaddius's stacking charges, are supposed to just increase the damage you would have done by that. But paladin's holy strike, and only this spell, seems to get WAY more out of it than you'd expect.

This bug results in berserker paladins critting for like 4.5k in battlegrounds with a meele instant.
This bug resulted (when wbuffs were ingame) in people doing 36k damage in a single holy strike on thaddius. Compare to the top possible damage of war executes on this fight, around 17k.

From what we can tell, this is likely due to the code doing this kind of math, beserserker +30% buff for example:

(Phys hit * 130%) * 130% + Spellpower added
Instead of
 (Phys hit * 130%) + (Spellpower added * 130%)

**Steps to reproduce the behavior with as much detail as possible:**

1. Do a bunch of holy strikes normally. see their avg damage
2. Put and keep the beserker buff on, then repeat the test
3. Compare the avg damages and see its most like +60% than +30%

**IDs of affected creatures, items, quests or spells with a link to the relevant page:**

Spell: https://database.turtle-wow.org/?spell=679

**Expected behavior. Describe how it should work:**
The +% damage should apply to both phys and spell components, but the phys counterpart should not be multiplied by the +% damage twice. This fixes holystrike in PVP (lots and lots of valid complaints every single day) and Thaddius (where they simply pull threat and die from this insane damage).

**Comment by balakethelock** [comment]
> As said in discord before. It's not just holy strike that works this way. It is the same for seal of command and it's blizz like for that spell as far as people say. Immo not a bug but a case of class changes that should be rolled out with other changes

Many things work that way and are balanced around working this way. IMO it's a good thing that certain modifiers can double dip on certain abilities to balance things more delicately around pvp and pve (for example, ignite technically double dips from modifiers).

Imo the best thing to do right now is to manually exclude certain auras from this double dipping to keep ret paladins in a viable pve position
https://database.turtle-wow.org/?spell=23505 (bgs berserking buff)
https://database.turtle-wow.org/?spell=785 skeram's mind control buff. Breaks paladins and lets even holy paladins with a 1.8 speed onehander do 7000 damage holy strikes on their allies
https://database.turtle-wow.org/?spell=28410 KT's mind control buff. Same deal, mind controlled paladins can do 10k holy strikes regular, not crits. Makes the fight harder the more paladins especially rets, they can randomly get mind controlled and oneshot your tank

**Comment by Zebouski** [comment]
I agree with balake's solution of fixing this, just for the few instances this cause more problems to the game than not.

I suppose paladins being by far the strongest on thaddius is okay, this is not unprecedented as other bosses like vael specifically only make wars/rogues/cats good and leave the rest in the dust.

**Comment by burner1024** [comment]
Problem: paladins oneshotting everyone left and right, ally and enemy alike.
Solution: let's make them not oneshot allies.
Cool.

> IF the problem is just pvp, why not tsrget berserking directly and leave pve rets untouched?

Because with or without berserking, it's still oneshot, maybe in 55% cases instead of 65%.
The real problem is holy strike itself, and berserking bug is just a mild aggravation.

**Comment by balakethelock** [comment]
> Are there any other abilities besides holy strike and Soc based on weapon dmg converted into spell dmg in game? Those woild be affected too by, double dipping. First the weapon dmg is increased by the percentage Then the abilities spell dmg increased again

None by players, only by mobs.

**Comment by burner1024** [comment]
Also if you're comparing holy strike to SoC, I'd check its spell coefficient. For SoC it's supposed to be 0.2, and how much it's for HS is not obvious from db...

**Comment by Nicorus49** [comment]
> Since double dipping is basically blizzlike behaviour, here is an alternative solution I think might be better:
> 
> I propose, keep double dipping for holy strike instead nerf the ability by letting the dmg of it be affected by armor.that's a massive around 35% dmg reduction in pvp But only a slight nerf in raids due to armor pen on bosses
> 
> This way we can both keep ret viable in raids and leave the constant paladin op pvp complaints behind us

This is likely the best solution. Though all changes should wait until class changes 2.0 for a comprehensive rebalance since even in pve armor is not reduced to 0 and this would be a nerf in many situations.

**Comment by Muigin** [comment]
This is not a bug, but an unforeseen oversight of the spell's design. This spell will be revisited during the next phase of class change discussions.
