### ISSUE TITLE
High Elf daily crystal cavern: blinked through the floor into the void below.

### ISSUE THREAD

**Issue by JohnEdwa** [slowtorta/turtlewow-bug-tracker#3394]
Went to do the crystal gathering daily, managed to blink through the ground while entering the cave falling into a void (that started ticking fall damage while I was falling) that eventually ended in water, jumping on the surface ticking that "fall" damage again. Thankfully it was easy to TP out of there.

Instant Replay captured it all so here's the clip for reference: https://www.youtube.com/watch?v=s9fHkUBydtY

**Comment by slowtorta** [comment]
We're aware of this issue, it'll be fixed in patch 1.16.6
