### ISSUE TITLE
GBank addon, possibly more, is erroring out on macros with #showtooltip Comma, Weapon

### ISSUE THREAD

**Issue by Zebouski** [slowtorta/turtlewow-bug-tracker#3395]
**Please, provide a clear description what the bug is:**
With weapons like "Gressil, Dawn of Ruin" and "Thunderfury, Blessed Blade of the Windseeker", people will make macros involving equipping this weapon. However, this causes lua errors from one of turtle's bundled addons:

![image](https://user-images.githubusercontent.com/11151284/236505543-4acd7936-1a26-4aa5-899a-49ccdc39f3fa.png)

It seems to be that the comma is not being sanitized, and so when the code places this item into this function that only takes 2 params, the comma turns it into a 3 param function.

**Steps to reproduce the behavior with as much detail as possible:**

1. Install https://github.com/DennisWG/Roid-Macros
2. create a macro with `#showtooltip Gressil, Dawn of Ruin` at the top
3. place on your bars
4. hover over it. See that the roidmacros tooltip works, but the turtle addon is erroring out

**Expected behavior. Describe how it should work:**
No errors pls thanks

**Comment by Gurky-Turtle** [comment]
I believe this could be something Roid Macros is causing as I dont get this error with other addons. It could be that they are both sharing the same function for links.

**Comment by Zebouski** [comment]
> How about removing the, form the item names. Easy hackfix :)

You mean like change the top line to `#showtooltip Gressil Dawn of Ruin`? That just breaks the tooltip. Same as just deleting the line.
![image](https://user-images.githubusercontent.com/11151284/236526063-5d672d8b-bbfd-4e22-aaa0-05e3e64359ec.png)
The goal here is to get roid's #showtooltip working without erroring up the turtle addons.

**Comment by Zebouski** [comment]
Ah yes, take away the iconic `,` of thunderfury.

**Comment by Gurky-Turtle** [comment]
I wonder if it is how the comma is being handled that is causing some problems.

**Comment by Zebouski** [comment]
> I wonder if it is how the comma is being handled that is causing some problems.

yeah it definitely is an escaping issue

**Comment by Gurky-Turtle** [comment]
@Zebouski what happens if you do something like #showtooltip Gressil\, Dawn of Ruin

**Comment by Zebouski** [comment]
After review, we found that Shagu's code used to hook tooltips is being used for the gbank addon to show on tooltips if an item exists in the gbank and how much.

This same bug appears with other addons with this code like https://github.com/Zebouski/MoPGearTooltips, so we will fix the bug testing with this instead. I will reopen this report with the adjustments, if it is the Shagu code that needs the fix.
