### ISSUE TITLE
Ostarius Pedestal Bug

### ISSUE THREAD

**Issue by SabineWren** [slowtorta/turtlewow-bug-tracker#3397]
**Please, provide a clear description what the bug is:**

One person can bug the Ostarius pedestal. That makes it impossible to kill the boss if someone wants to grief your raid.

**Steps to reproduce the behavior with as much detail as possible:**

1. Summon the boss
2. Accept BG queue or summon / Hearthstone / Vanish / Feign Death
3. Wait for boss to finish his speech
4. Boss despawns before anyone enters combat
5. Blue hologram remains on pedestal until server crash

This is not the same as the "pedestal is charging" message you get after killing the boss. Instead, the pedestal is completely un-interactable with a blue hologram above it.

**IDs of affected creatures, items, quests or spells with a link to the relevant page:**
https://database.turtle-wow.org/?npc=80935
https://database.turtle-wow.org/?spell=57000
https://database.turtle-wow.org/?quest=40107
https://database.turtle-wow.org/?quest=40115

It's not the stone watcher hologram that stays, but the blue one from the event.

**Expected behavior. Describe how it should work:**
The boss should either stay to fight the remaining players, or despawn without breaking the pedestal.

**Comment by jlabranche** [comment]
This is really frustrating a lot of players

**Comment by SabineWren** [comment]
Still bugged, and GMs no longer fix it.
