### ISSUE TITLE
Item "Winterhoof Cleansing Totem" should be availble all horde races

### ISSUE THREAD

**Issue by el-dias** [slowtorta/turtlewow-bug-tracker#34]
By opening this Issue, I admit to having done the pertinent research using sources from Vanilla (preferably) or Classic. I also understand that sources from other private servers are not acceptable.

**Current behavior**: 

Trying to use "Winterhoof Cleansing Totem" and shows: "You can't use this item"

**Expected behavior**: 

Should be available to all horde races to continue the "Cleasing" chain quest in Mulgore

**Proofs**:

https://classic.wowhead.com/item=5411/winterhoof-cleansing-totem

**Steps to reproduce**:

1. Trying to use "Winterhoof Cleansing Totem" and shows: "You can't use this item"
2. 
3.

**Comment by Vikkyne** [comment]
https://classic.wowhead.com/quest=754/winterhoof-cleansing

You can collect the items and get the line just up to the point of the cleansing, but you can't get that quest (and the rest of the line done). It is indeed a Tauren-only quest (as seen in Classic).  It is part of their unique storyline - cleansing their land.
