### ISSUE TITLE
Hearthstone location not properly set for Mudsprocket

### ISSUE THREAD

**Issue by Vleled** [slowtorta/turtlewow-bug-tracker#340]
Setting hearthstone location to Mudsprocket, Dustwallow Marsh does not affect the current hearthstone location.

**Steps to reproduce the behavior with as much detail as possible:**

1. Go to Mudsprocket in Dustwallow Marsh
2. Talk to Innkeeper Frizzo 
3. Select the "Make this inn your home" option

**IDs of affected creatures, items, quests or spells with a link to the relevant page:**

NPC: https://database.turtle-wow.org/?npc=80930
Item: https://database.turtle-wow.org/?item=6948

**Expected behavior. Describe how it should work:**
Selecting "Make this inn your home" option should change the current hearthstone location to Mudsprocket

**Comment by slowtorta** [comment]
This was a LOS issue. Had to move this NPC out of the building, should be fine now.
