### ISSUE TITLE
pumpkin buff gives less stats than tooltip says

### ISSUE THREAD

**Issue by geojak** [slowtorta/turtlewow-bug-tracker#3400]
**Please, provide a clear description what the bug is:**

1. eat a pumpkin

![image](https://user-images.githubusercontent.com/25199983/236575473-7cc9bd4e-01ae-43b2-9e93-3518415cd425.png)

2. the tooltip says 25% of lvl and my lvl is 60, so ishould get 15 stam and 15 spirit
![image](https://user-images.githubusercontent.com/25199983/236575418-9078a5da-f1d6-454b-b712-31d31d816993.png)

3. notice that your stamina and spirit only increase by 7 (tested by me and a druid friend, same result)

**Expected behavior. Describe how it should work:**

stat increase matching the tooltip

possibly some seasonal buff food also affected

**Comment by Gurky-Turtle** [comment]
Should be fixed in the next update
