### ISSUE TITLE
T2 bonus set not working after transmogging a set piece

### ISSUE THREAD

**Issue by BlackHound22** [slowtorta/turtlewow-bug-tracker#3403]
**Please, provide a clear description what the bug is:**
I have three pieces of the T2 set for priests, which should grant me a 15% mana regen to continue while casting. After transmogging one of those pieces (legs), I discovered that the set bonus is not active anymore, almost as if the legs were not recognized as parts of the set anymore. A GM in game told me it was only a visual bug, due to the transmog, but upon checking the statistics on my character I saw that my total mana regen while casting is only 15%. Given that I also have a talent that bumps it up by the same amount, the total should be 30% with the bonus set. 

**Steps to reproduce the behavior with as much detail as possible:**

1. Level 60 priest with three T2 pieces, in my case head, hands and legs and verify the 3 pieces bonus is active (including character stats)
2. Transmog "leggings of transcendence" to "black mageweave leggings"
3. Three pieces bonus not active anymore, which is visible both in the items description, and in the character stats in game.

**IDs of affected creatures, items, quests or spells with a link to the relevant page:**
Item:  https://database.turtle-wow.org/?item=16922

**Expected behavior. Describe how it should work:**
Under the recap called "vestments of transcendence" the number of pieces equiped should be highlited and numbered. The lowest recap showing the bonus being active should also be highlited. When checking the character stats in game, the mana regen section should report "%Regen while casting" according to the correct amount; in my case 30%.

**Comment by balakethelock** [comment]
character statistics can also be visually bugged (since it's an addon that gives them, and not the default UI). Check your mana regen by counting how much you get per tick during and outside 5 second rule.

**Comment by slowtorta** [comment]
This is a visual buff, your bonus set is intact!
