### ISSUE TITLE
Haste to gloves does not increase casting speed.

### ISSUE THREAD

**Issue by ConcernedTurtler** [slowtorta/turtlewow-bug-tracker#3404]
**Steps to reproduce the behavior with as much detail as possible:**

1. Observed the tooltip for the haste to gloves enchant said it increased casting speed.
https://database.turtle-wow.org/?spell=13948
2. Had an enchanter put this on my gloves.
3. Casting speed did not increase.

**Comment by Gurky-Turtle** [comment]
https://github.com/slowtorta/turtlewow-bug-tracker/issues/2921
