### ISSUE TITLE
Gorishi Sting isnt dropping

### ISSUE THREAD

**Issue by DontPanicCS** [slowtorta/turtlewow-bug-tracker#3406]
**Please, provide a clear description what the bug is:**
I am attempting to get the gorishi sting drops for the druid quest bloodpetal poison. The Turtle Atlas says it is a 15% drop rate. I have to farm fucking 8 of these....Killed 60 so far and not 1 damn drop
**Steps to reproduce the behavior with as much detail as possible:**

1. Accept quest
2. Get bloodcaps
3. Kill 60+ gorishi worker/reaver 
4. no drop

**IDs of affected creatures, items, quests or spells with a link to the relevant page:**

NPC: https://database.turtle-wow.org/?npc=
Item: 34925
Quest: Bloodpetal Poison
Spell: https://database.turtle-wow.org/?spell=
Object: https://database.turtle-wow.org/?object=

**Expected behavior. Describe how it should work:**
Kill gorishi, get drop every once in a while.

**Comment by AKryukov92** [comment]
Sting drops from flying ones https://database.turtle-wow.org/?item=22435
Reavers and workers are wrong mobs to drop it.

**Comment by DontPanicCS** [comment]
Please fix turtle atlas then?

**Comment by slowtorta** [comment]
TW Atlas isn't officially supported feature. It's a community project. Please always refer to our online DB if you need help.
