### ISSUE TITLE
Warmode is broken for casters

### ISSUE THREAD

**Issue by Primebeef1227** [slowtorta/turtlewow-bug-tracker#3407]
**Please, provide a clear description what the bug is:**
In PVP as a caster against anyone above 10 levels it is impossible to fear, polymorph, frost armor, root, or even damage an opponent. While melee classes and hunters can use their attacks and abilities against a level 60 without any problems. As a caster you have literally no options but to die.

**Steps to reproduce the behavior with as much detail as possible:**

I dueled a 28 rogue, 29 warlock, and 23 hunter to test all damage types. The rogue could land his autos as well as Sinister Strike, Eviscerates, as well as Sap with no issue. The warlock couldn't land one spell that wasn't resisted. While the hunter could land all auto attacks as well as all his spells from Hunters Mark, Serpent Sting, and Arcane Shot with no issue.

**Expected behavior. Describe how it should work:**

Warmode broken if you roll any caster class and fight anyone above 4 levels from yourself. 

![melee](https://user-images.githubusercontent.com/132806621/236662886-6f939035-19f2-40f5-99e5-a5a567426297.png)
![caster](https://user-images.githubusercontent.com/132806621/236662897-d3de38f1-8632-42a1-a318-f8ab8b3d61e9.png)
![hunterranged](https://user-images.githubusercontent.com/132806621/236662903-2bdae053-563c-4cda-89e9-d51d07a03d20.png)

**Comment by ratkosrb** [comment]
The level based miss chance for spells will be capped to the equivalent of 10 levels difference, since experience from classic shows there is some kind of lower limit, and it shouldn't be impossible to hit the target with spells.

**Comment by ConcernedTurtler** [comment]
It's really annoying when you get gouged by a level 10 rogue you're trying to mind control off a zepplein. Please fix.
