### ISSUE TITLE
Transmogrification Visual Bug

### ISSUE THREAD

**Issue by Aruze** [slowtorta/turtlewow-bug-tracker#3409]
**Please, provide a clear description what the bug is:**
The Transmoged item, sometimes loses the skin of the item, causing it to revert back to its orginal form, sometimes when taking damage, or sustaining durability loss to your item.
also, possibly from using Hearthstone, and Zoning out via Flightmaster, Possibly every time the server checks? or ticks? or Lags? the item reverts, my ping is  36ms stable.

Sometimes when im standing in Stormwind, the armor reverts to its orginal form...

**Steps to reproduce the behavior with as much detail as possible:**

1. Take Durability damage to your item
2. use Hearthstone or Zone your character somehow
3. check lag related or client to server to confirm loss of information.
4. Equip Different types of SET items on your character.

**IDs of affected creatures, items, quests or spells with a link to the relevant page:**

Imperial SET pieces, Plate, Shoulders, Gauntlets.
https://database.turtle-wow.org/?item=12428
https://database.turtle-wow.org/?item=65007

Steel Plate Boots (SET) item.
https://database.turtle-wow.org/?item=83410

Elemental Rockridge Leggings:
https://database.turtle-wow.org/?item=17711
(They also bug out alot)

So far, seems to affect SET pieces, possibly i am wearing both? it checks my character for buffs maybe?

**Expected behavior. Describe how it should work:**

i transmog an item, it stays the same skin forever, no reverting.

**Comment by twowTurtReynolds** [comment]
Duplicate of https://github.com/slowtorta/turtlewow-bug-tracker/issues/1400
