### ISSUE TITLE
Paladin taunt sometimes permanently  bugged 

### ISSUE THREAD

**Issue by geojak** [slowtorta/turtlewow-bug-tracker#3411]
**Steps to reproduce the behavior with as much detail as possible:**

1. Be a paladin in bwl
2. Use taunt on ebonroc with talents 
3. Use it 5 mroe times 
4. Don't work
5. Let another pala taint
6. Works imkidelty for others 
7. Relog
8. Now your taunt also works again
9.??? 

**Expected behavior. Describe how it should work:**
Taunt should not bug out

**Comment by twowTurtReynolds** [comment]
Tested the taunt in BWL around 10 times, and it seemed to work fine. We will need clearer replication steps.
