### ISSUE TITLE
Bosses not spawning in Wailing Caverns

### ISSUE THREAD

**Issue by Fildoso** [slowtorta/turtlewow-bug-tracker#3414]
**Please, provide a clear description what the bug is:**
This happened to me twice already. First time Lady Anacondra and the turtle boss where missing, so we decided to reset, and then every boss was there. Second time first 3 bosses where there (Anacondra, Cobrahn, and the turtle), but the rest were missing. A guy who i was grouped with rthought that what happend was that the instance not reseted fully, but i am not sure. 

**Steps to reproduce the behavior with as much detail as possible:**

1. Queue for Waling Caverns
2. Go inside
3. Sometimes bosses are not there.

**Expected behavior. Describe how it should work:**
All bossess should be there.

**Comment by Kangaroux** [comment]
@Fildoso Did you check the bosses using a target macro? Lady Anacondra has 4 different locations she can spawn

**Comment by Gurky-Turtle** [comment]
unable to reproduce this are you sure the leader didn't already have a lockout running before you joined?
