### ISSUE TITLE
Stormstrike Does Not Proc Weapon Imbues

### ISSUE THREAD

**Issue by Niqlo** [slowtorta/turtlewow-bug-tracker#3415]
Same issue as:
 https://github.com/slowtorta/turtlewow-bug-tracker/issues/1731#issue-1322817554

Now affects both ranks of stormstrike. This is because there was some problem with yellow hits not proccing windfury/flametongue/frostbrand, so rank 2 stormstrike was changed to a white hit if I remember correctly. However, now both are yellow hits (this was not mentioned in any changelog) and so neither rank will proc any imbues. Bug has been around since at least march

EDIT: stormstrike (rank 2) will only proc windfury, (but if it does your weapon swing timer is reset - the debate on whether it is supposed to do this or not fried my brain a little). It will not proc flametongue or frostbrand. Same applies to rank 1.

**Comment by Melphoone** [comment]
Confirmed, Since the change to Yellow dmg with stormstrike, no weapon imbue is activated-.-

**Comment by Reiiama** [comment]
Bump, just realized this issue. Big issue, drastically affects Enhance shamans. It works with Windfury, but doesn't seem to count as an actual attack for the purpose of Frostbrand or Flametongue.
