### ISSUE TITLE
Atiesh aura for mage doesn't provide the 2% crit

### ISSUE THREAD

**Issue by frostyfyre** [slowtorta/turtlewow-bug-tracker#3416]
**Please, provide a clear description what the bug is:**
The Atiesh legendary for mage should provide 2% crit for the party, but when you add the numbers the crit is not there.
**Steps to reproduce the behavior with as much detail as possible:**

1. Check the wowhead database and create a mage with BiS items and enchants :https://www.wowhead.com/classic/gear-planner/mage/human/AjwRIwBVAAAC9QUgIAIwMwUfAD-BV-JeZAJaEYNZx3MbhVfgTjkGWMqHWh5eZIhX5DZCiVntTiiKVFFh9gtaFgxaxQ1Lsw5aBo9aCmH8kFg9WN0SWSU
2. Notice that the wowhead stats show 23.83% Crit and 166 spirit
3. Now look on my uploaded picture from my mage and notice 20.83% crit and 172 spirit, the rest of the stats being EXACTLY the stame (34 str, 39 agi, 246 sta, 335 int). 
4. After looking at the difference, the missing 3% crit comes from the shoulder enchant (1%) and Atiesh aura (2%) , and the extra 10% spirit, i have no idea where it is from.

![printscreen with my addons](https://user-images.githubusercontent.com/97914280/236840260-dfed7ae9-7a20-45e3-a16a-3bfb63e590b4.png)
![mage bis stats](https://user-images.githubusercontent.com/97914280/236840265-0e5bbb44-251c-4b05-aa92-52da46fa3644.png)

**IDs of affected creatures, items, quests or spells with a link to the relevant page:**

NPC: https://database.turtle-wow.org/?npc=
Item: https://database.turtle-wow.org/?item=22589
Quest: https://database.turtle-wow.org/?quest=
Spell: https://database.turtle-wow.org/?spell=
Object: https://database.turtle-wow.org/?object=

**Expected behavior. Describe how it should work:**
The items should provide the crit that their description is saying it is there.

**Comment by lyssebabz** [comment]
[https://github.com/slowtorta/turtlewow-bug-tracker/issues/3361](url)

**Comment by lyssebabz** [comment]
#3066  #3361

**Comment by balakethelock** [comment]
I would like to draw attention to another bug. Atiesh auras still don't stack with each other https://github.com/slowtorta/turtlewow-bug-tracker/issues/3007

**Comment by Gurky-Turtle** [comment]
This is an addon issue please create a bug report here: https://github.com/Gurky-Turtle/BetterCharacterStats

Include the buff tooltip as well as the full item tooltips seeing this is how the addon works and it is currently not checking for those buffs. See https://github.com/slowtorta/turtlewow-bug-tracker/issues/3066 https://github.com/slowtorta/turtlewow-bug-tracker/issues/3361
