### ISSUE TITLE
Dream's Herald

### ISSUE THREAD

**Issue by welpenhund** [slowtorta/turtlewow-bug-tracker#3419]
**Please, provide a clear description what the bug is:**
Weapon proc Effect lasts 30 seconds and not 12 seconds like described in the tooltip

**Steps to reproduce the behavior with as much detail as possible:**

1. Equip [Dream's Herald]
2. Hit your target till the weapon effect procs

**IDs of affected creatures, items, quests or spells with a link to the relevant page:**

Item: https://database.turtle-wow.org/?item=65008
Quest: https://database.turtle-wow.org/?quest=
Spell: https://database.turtle-wow.org/?spell=48004
Object: https://database.turtle-wow.org/?object=

Effect is supposed to last 12 seconds after proccing, at the moment it lasts 30 seconds.
![grafik](https://user-images.githubusercontent.com/30401521/236892755-e9f5533d-6627-4b2b-aa68-d257849274ff.png)

**Comment by welpenhund** [comment]
bump

**Comment by Gurky-Turtle** [comment]
should be fixed in the next update
