### ISSUE TITLE
Can't Talk with Timbermaw despite being neutral

### ISSUE THREAD

**Issue by Rakura1** [slowtorta/turtlewow-bug-tracker#342]
**Please, provide a clear description what the bug is:**

**Steps to reproduce the behavior with as much detail as possible:**

1. Get Neutral with Timbermaw
2. Go try to talk with one
3. See that a sword icon appears and you will attack any of them you try to talk to

**IDs of affected creatures, items, quests or spells with a link to the relevant page:**

NPC: https://database.turtle-wow.org/?npc=
Item: https://database.turtle-wow.org/?item=
Quest: https://database.turtle-wow.org/?quest=
Spell: https://database.turtle-wow.org/?spell=
Object: https://database.turtle-wow.org/?object=

**Expected behavior. Describe how it should work:**
Once neutral you should be able to talk / turn in quests / shop from their vendors.

**Comment by Rakura1** [comment]
Follow up: It appears it is the same bug with cenarion where the player will be at war with them upon reaching neutral.

**Comment by Nolin7777** [comment]
Thanks, will be fixed at next update
