### ISSUE TITLE
(Hunter) Vek'nilash (Twin Emperors) is immune to 8/8 Dragonstalker proc & Hunter's Mark

### ISSUE THREAD

**Issue by imaglcian** [slowtorta/turtlewow-bug-tracker#3422]
**Please, provide a clear description what the bug is:**

Currently in AQ40 during the Twin Emperors encounter, 8/8 Dragonstalker proc (Expose Weakness) does not work on Vek'nilash, neither does Hunter's Mark. These should be considered physical debuffs, similar to Bleeds.

**Steps to reproduce the behavior with as much detail as possible:**

1. Perform Hunter's Mark & fish for 8/8 Dragonstalker procs on Vek'nilash
2. Observe how you get an "IMMUNE" message with Scrolling Combat Text, and the debuff is not applied.

**Expected behavior. Describe how it should work:**

Hunter's Mark and 8/8 Dragonstalker (Expose Weakness) Should be applicable to Vek'nilash.

**Comment by Shoshanahah** [comment]
This is not a bug. This has always been the case on any server, including Blizzard's classic server. These are considered magic abilities, obviously not working on a mob immune to magic.

**Comment by imaglcian** [comment]
I believe they should be considered Physical Abilities regardless. Hunters in vanilla were an unfinished class with weird ability types etc.
This would also go for Blackwing Spellbinders
