### ISSUE TITLE
Evil Twin debuff is bugging warlock summons

### ISSUE THREAD

**Issue by balakethelock** [slowtorta/turtlewow-bug-tracker#3426]
**Please, provide a clear description what the bug is:**
Players affected with the Evil Twin debuff can't be summoned by warlock portals

**Steps to reproduce the behavior with as much detail as possible:**

1. Use engineering transport trinkets until you get the debuff. Alternatively just put it on yourself with gm commands
2. Try to be summoned by a warlock while you have the debuff
3. The summon does not work

**IDs of affected creatures, items, quests or spells with a link to the relevant page:**

Spell: https://database.turtle-wow.org/?spell=23445

**Expected behavior. Describe how it should work:**
The debuff is merely an easter egg and has no gameplay effect whatsoever. Proof: https://www.wowhead.com/classic/spell=23445/evil-twin#comments

**Comment by ConcernedTurtler** [comment]
this is intended

**Comment by ConcernedTurtler** [comment]
> > this is intended
> 
> source?

first google result:
https://i.imgur.com/f6fUD9W.png

**Comment by balakethelock** [comment]
I see 0 wowhead comments claiming it affects warlock summons https://www.wowhead.com/classic/spell=23445/evil-twin#comments

and look at the discussion about it in the wiki https://wowwiki-archive.fandom.com/wiki/Talk:Evil_Twin

Its a myth, the debuff has absolutely no effect and it had no effect in modern classic as well so there's no question about what's true now.

**Comment by Gurky-Turtle** [comment]
You cannot summon people with the evil twin debuff this is intended you can look at code for old vanilla 1.12.1 addons to see summons were ignored if the user have evil twin.

WoWWiki/Gamepedia (one is a copy of the other) said it in their oldest 2006 version:
https://wow.gamepedia.com/index.php?title=Evil_Twin&oldid=76791
https://wowwiki.fandom.com/wiki/Evil_Twin?oldid=76791

Prevents you from being summoned by a Warlock.

As well as multiple wowhead comments:
https://classic.wowhead.com/item=18984/dimensional-ripper-everlook#comments:id=2684001:reply=1167073

prevents you from being summoned by a warlock

https://classic.wowhead.com/item=18984/dimensional-ripper-everlook#comments:id=2684042

No, it just makes it so you can't be summoned.

https://classic.wowhead.com/item=18986/ultrasafe-transporter-gadgetzan#comments:id=2714760

Guys,
I had 'Evil Twin' and no Warlocks could summon me.
As soon as 'Evil Twin' was gone - summon away.
Interesting the Summons used a shard, and the Warlocks thought the summon was sucessful, until I never showed up (and I got no message either)...

https://classic.wowhead.com/item=18986/ultrasafe-transporter-gadgetzan#comments:id=3071392

When you have the 'Evil Twin' debuff you can't be summoned. It wears off upon death.

**Comment by balakethelock** [comment]
Requesting reopen. All the comments saying that were either trolling (this may have been some vanilla era running joke, like the saying "paladins can't use maces". Here's an exhaustive list of proof from all sorts of places.

- The wiki edit history is full of people going back and forth adding and removing the information on disabling summons. It's clearly a very contested issue even in vanilla days when it was possible to check. This can only mean it was some sort of joke.
https://wowpedia.fandom.com/wiki/Evil_Twin?action=history
see the [ebb](https://wowpedia.fandom.com/wiki/Evil_Twin?diff=321245&oldid=321199) and [flow](https://wowpedia.fandom.com/wiki/Evil_Twin?diff=321158&oldid=308386)

- In the [talk page](https://wowpedia.fandom.com/wiki/Talk:Evil_Twin), the user "CJ" CrazyJack is certain that the debuff does not disable warlock summons. This guy was super active in the wiki, doing almost [13000 edits](https://wowwiki-archive.fandom.com/wiki/Special:Contributions/CrazyJack) in the span of vanilla-tbc.

- [Warlock classic discord](https://discord.com/invite/3fvUDqF) has the [following ](https://discord.com/channels/253210018697052162/498619347778928661/783260177729847296)to say

![image](https://github.com/slowtorta/turtlewow-bug-tracker/assets/111737968/12d83e95-803b-4534-b08c-3e93af676b9d)


All this proof points that the no summons on evil twin is a myth, urban legend, troll, or whatever you want to call it. Evil twin was 100% an easter egg with no gameplay effect.

**Comment by Gurky-Turtle** [comment]
I'll reopen it and discuss with the team it looks like you made a pr to vmangos so let's see what they say. Keep in mind classic isn't always the end all as something do not work as they should there either. 

There are quite a lot of mixed things that I have found online.

**Comment by Gurky-Turtle** [comment]
https://web.archive.org/web/20071019045404/http://thottbot.com/s23445 found this as well as this https://wowpedia.fandom.com/wiki/Evil_Twin?action=history (History for the second link ping pongs back and forth. 

I also checked all wow patch notes for vanilla and the only one that references Evil Twin is this one: https://vanilla-wow-archive.fandom.com/wiki/Patch_1.11.0

"When a Paladin is replaced by their Evil Twin due to transporter malfunction, they can no longer revert to their normal self using divine shield."

**Comment by Gurky-Turtle** [comment]
Looks like it will be applied next update.
