### ISSUE TITLE
"The level based spell miss chance is now capped to 10 levels difference, making it possible to hit high level players in PvP."

### ISSUE THREAD

**Issue by Nemoose** [slowtorta/turtlewow-bug-tracker#3428]
Hello,
I don't know if it is intendet, but the new change "The level based spell miss chance is now capped to 10 levels difference, making it possible to hit high level players in PvP." effects PvE aswell. Lower level mobs have a way higher chance to hit you with spells now.

**Steps to reproduce the behavior with as much detail as possible:**

1. Get attacked by a lower level Mob (higher level difference than 10)
2. Get hit by many more spells then before

**Expected behavior. Describe how it should work:**

I would expect to get a lot of misses while being attacked by low level Mobs, but it should work how ever the turtle team intendet it to work.

**Comment by ratkosrb** [comment]
https://github.com/slowtorta/turtle-wow/commit/b2a86cb1b0450c71854869b620477a9d0c586cd8
