### ISSUE TITLE
Quest VIP Invites bugged

### ISSUE THREAD

**Issue by Nyteterror** [slowtorta/turtlewow-bug-tracker#3429]
We don’t get the invitations after accepting the quest.

**Steps to reproduce the behavior with as much detail as possible:**

1. In the Beach Party in Tanaris, click the npc Risa.
2. Accept the quest VIP Invites.
3. Quest added to the quest list but without the invitations.

**IDs of affected creatures, items, quests or spells with a link to the relevant page:**

NPC: https://database.turtle-wow.org/?npc= 15323
Item: https://database.turtle-wow.org/?item=
Quest: https://database.turtle-wow.org/?quest=
Spell: https://database.turtle-wow.org/?spell=
Object: https://database.turtle-wow.org/?object=

**Expected behavior**
Should receive special invitations.

**Comment by slowtorta** [comment]
![image](https://github.com/slowtorta/turtlewow-bug-tracker/assets/66763404/ddd8abba-284a-4008-8568-6f1e40fb60fa)
![image](https://github.com/slowtorta/turtlewow-bug-tracker/assets/66763404/87f02d17-e518-4536-883f-09e9590eb3d5)
![image](https://github.com/slowtorta/turtlewow-bug-tracker/assets/66763404/b0ce65f8-ee80-43a6-830e-223b82b32492)

This one is working as intended, you don't have to actually carry three letter around to complete it.
