### ISSUE TITLE
Stealth detection radius of NPC too large.

### ISSUE THREAD

**Issue by gh-borz** [slowtorta/turtlewow-bug-tracker#343]
**Please, provide a clear description what the bug is:**

NPC’s ability to detect stealthed player is too far. Even with extra talent points in stealth ability (as a rogue or Druid), NPCs can detect you in stealth from too far away.  Additionally, the detection behaviour is not normal. Normally if you go within NPC detection range, they will turn to face you, and make a “huh?” alert sound. If you stop moving, they will look in your direction for awhile then turn away, or continue their pathing, and will then only go straight to attack if their resumed path brings them even closer to you.  On this server, if they detect you and your range is too close, they will immediately transition into attack. This should not happen because the whole point of the detection alert is to give you a chance to move away.

This is a big problem because it essentially almost makes stealthed skills useless. As a rogue I’m finding it very hard to pick pocket any NPC that is not standing completely still, and it makes skills like rogue’s “ambush” almost completely useless.

**Steps to reproduce the behavior with as much detail as possible:**

1. Go stealth
2. Move towards to NPC
3. NPC will detect you from quite far away. And if you are closer than maximal detection range, they will transition straight into attack after pausing.

**IDs of affected creatures, items, quests or spells with a link to the relevant page:**

All NPC’sz

NPC: https://database.turtle-wow.org/?npc=
Item: https://database.turtle-wow.org/?item=
Quest: https://database.turtle-wow.org/?quest=
Spell: https://database.turtle-wow.org/?spell=
Object: https://database.turtle-wow.org/?object=

**Expected behavior. Describe how it should work:**

Each point of skill in a stealth talent should raise the stealth level by one. So for eg, a stealthed player who is level 20, with 5 points into improved stealth talent, should have the stealth detection radius of a level 25 player to the NPC. This should mean that it is almost impossible for an NPC/mob to detect you if they are at equal / lower level than you, unless you cross directly into their path/hit-box.

**Comment by Tinyfin-github** [comment]
More information: https://forum.turtle-wow.org/viewtopic.php?f=3&t=2217

**Comment by Muspellheimer** [comment]
we are locking into it... yea my ass...

**Comment by Muspellheimer** [comment]
fix your fucking shit you retarded morons...

**Comment by Muspellheimer** [comment]
deleting comments doesn really help does it?

**Comment by Muspellheimer** [comment]
you pathetic fuck ups...

**Comment by jameyboor** [comment]
Fixed.
