### ISSUE TITLE
Enter World text on the character select screen is offcenter

### ISSUE THREAD

**Issue by Zebouski** [slowtorta/turtlewow-bug-tracker#3430]
**Please, provide a clear description what the bug is:**
![image](https://github.com/slowtorta/turtlewow-bug-tracker/assets/11151284/236e694d-4c7c-4073-8b95-7abdbd911709)
**Expected behavior. Describe how it should work:**
![image](https://github.com/slowtorta/turtlewow-bug-tracker/assets/11151284/a8966f5d-f1d9-4bfd-9fb3-c3716eaf8d26)
IIRC you guys do know how to mod the char screen UI? If this could be fixed like the WotLK version you see in the second screenshot, would be super based and I can finally unsee this monstrosity.

**Comment by biqqles** [comment]
Hah! Didn't expect my screenshots to curse you like this.

**Comment by Zebouski** [comment]
aaaaa the suffering aaaaaaaaa

**Comment by slowtorta** [comment]
It is exactly in the middle in my client. 
![image](https://github.com/slowtorta/turtlewow-bug-tracker/assets/66763404/b1691390-1c6e-4804-b7b6-04a9cb5df3f6)

**Comment by Zebouski** [comment]
Thanks Torta. I know this is really such a tiny nitpick and probably a waste of dev time, but its something blizzard fixed in later retail, and kept fixed for classic. Tiny baby bit of polish goes a long way :)

In your pic I'm counting 49 pixels wide here
![image](https://github.com/slowtorta/turtlewow-bug-tracker/assets/11151284/e0125aac-9556-4ec6-b052-d8bd0b5de117)
and 53 pixels wide here
![image](https://github.com/slowtorta/turtlewow-bug-tracker/assets/11151284/2c2f220c-93b0-4a90-a651-187183e687c6)

Moving the text 2 pixels to the right should solve it.

Here's another reference pic, from my turtle and 1.14 client:
![image](https://github.com/slowtorta/turtlewow-bug-tracker/assets/11151284/44f6356b-abeb-4f15-b7db-fa4f2f1eaddf)
![image](https://github.com/slowtorta/turtlewow-bug-tracker/assets/11151284/af09419a-c610-41e0-8ed8-efc622a1263c)

**Comment by luskanek** [comment]
This will be fixed in patch 1.16.6.

**Comment by twowTurtReynolds** [comment]
![image](https://github.com/slowtorta/turtlewow-bug-tracker/assets/151180101/6173a9f0-f956-4982-a93a-effe32991635)
