### ISSUE TITLE
"Cuergo's Gold" Quest not starting

### ISSUE THREAD

**Issue by norgigorgi** [slowtorta/turtlewow-bug-tracker#3431]
"Cuergo's Gold" quest in Tanaris not starting from item "Cuergo's Treasure Map" in character inventory. Game is indicating that the quest has already in quest log. Quest is not in quest log. WDB folder has been deleted and persists.

Attempted to complete quest despite the quest not being in quest log. No success.

Link to video of bug:

https://www.youtube.com/watch?v=T3sNxd2KyOA&ab

**Comment by Gurky-Turtle** [comment]
Have a gm check if your character has already done https://database.turtle-wow.org/?quest=2882 you will get that message if you have already completed the quest. 

Cannot reproduce.
