### ISSUE TITLE
(Stealth) Summoned trinkets/pets can still attack you when in stealth

### ISSUE THREAD

**Issue by imaglcian** [slowtorta/turtlewow-bug-tracker#3432]
**Please, provide a clear description what the bug is:**

So with the new change this patch, "Pets will no longer attack invisible targets", there was a slight oversight with summonable trinkets/items.
Additionally, these summoned mobs are immune to distract (Unlike hunter/warlock pets)

**Steps to reproduce the behavior with as much detail as possible:**

1. Use Barov Peasant Caller, Defender of Timbermaw, Vanquished Tentacle of C'thun, Dog Whistle, Fox Stone, Dragonling (Any) etc. (Even Feral Spirit)
2. Attack the target, then stop attacking
3. Have the rogue/druid enter stealth
4. See how the summoned mobs still go after the invisible target.

**Expected behavior. Describe how it should work:**

- Summonable trinkets/items should also be affected by this new change.
- These items' summoned mobs should not be immune to Distract (Distract will put a pet in place, where they do not move until told to come back (See how distract works here): https://www.youtube.com/watch?v=Xv-gvaz46Kc

**Comment by imaglcian** [comment]
I also want to add to this report:
Stealthed mobs and targets in the open-world, **even when targetable by the Hunter** can not be attacked by flaring them out of stealth/attacking with pet. For now it seems you HAVE to get hit by them to send a pet on them.

**Comment by duerok** [comment]
Also stealthed targets with hunters mark pet will not attack either. Seems pet won't attack any stealthed mob after the vanish "fix"

**Comment by Muigin** [comment]
This behavior was fixed in a previous update.
