### ISSUE TITLE
Retribution aura shown as physical damage (client bug)

### ISSUE THREAD

**Issue by r0ssi** [slowtorta/turtlewow-bug-tracker#3434]
**Please, provide a clear description what the bug is:**
Retribution aura shown as physical damage but aura in fact deals holy damage. 1.12 client has this bug on every private server.
**Steps to reproduce the behavior with as much detail as possible:**

1. Attack someone
2. Wait for hit

**IDs of affected creatures, items, quests or spells with a link to the relevant page:**

NPC: https://database.turtle-wow.org/?npc=
Item: https://database.turtle-wow.org/?item=
Quest: https://database.turtle-wow.org/?quest=
Spell: https://database.turtle-wow.org/?spell=
Object: https://database.turtle-wow.org/?object=

**Expected behavior. Describe how it should work:**

**Comment by ratkosrb** [comment]
This is not possible to change. We would need to have the client's source code to change the packet structure and include the damage school in the packet as in the newer clients.
