### ISSUE TITLE
Items: [Bloody Pick] and [Crossguarded Blade]

### ISSUE THREAD

**Issue by Hopelesss1337** [slowtorta/turtlewow-bug-tracker#3438]
### Clear description what the bug is

NPCs in High Elf starting zone don't drop following items: **[Bloody Pick]** and **[Crossguarded Blade]**

According to _Turtle WoW Database_, **[Shadowforge Prowler]** drops **[Bloody Pick]** with 3% drop chance and **[Shadowforge Fire Priest]** drops **[Crossguarded Blade]** with 0.3% drop chance

I've spent three days trying to obtain following items (at least **[Bloody Pick]**), but it seems to be impossible

### Steps to reproduce the behavior

1. Go to High Elf starting zone (_Loch Modan_)
2. Slay **[Shadowforge Prowlers]** and **[Shadowforge Fire Priests]**
3. Note that mentioned items do not drop

### IDs of affected creatures, items

NPC: https://database.turtle-wow.org/?npc=80207
         https://database.turtle-wow.org/?npc=80205

Item: https://database.turtle-wow.org/?item=61372
         https://database.turtle-wow.org/?item=61375

### Expected behavior

You should be able to loot **[Bloody Pick]** and **[Crossguarded Blade]** from **[Shadowforge Prowlers]** and **[Shadowforge Fire Priests]** whenever they drop

**Comment by Hopelesss1337** [comment]
@ratkosrb Excuse me, could you comment on the situation? If anything alright, this items really can drop and it's just about my luck, then I'll apologise. But if something is broken, just tell about it. Thank you.

**Comment by ratkosrb** [comment]
They should be able to drop after the next update.
