### ISSUE TITLE
Ret aura causing damage to enemies when you're bubbled

### ISSUE THREAD

**Issue by r0ssi** [slowtorta/turtlewow-bug-tracker#3439]
**Please, provide a clear description what the bug is:**
Retribution aura should not cause damage to attacker when you are bubbled
**Steps to reproduce the behavior with as much detail as possible:**

1. Attack someone
2. Use Ret Aura
3. Bubble

**IDs of affected creatures, items, quests or spells with a link to the relevant page:**

NPC: https://database.turtle-wow.org/?npc=
Item: https://database.turtle-wow.org/?item=
Quest: https://database.turtle-wow.org/?quest=
Spell: https://database.turtle-wow.org/?spell=7294
Object: https://database.turtle-wow.org/?object=

**Expected behavior. Describe how it should work:**

**Comment by balakethelock** [comment]
You need to give proof this isn't intended behavior

**Comment by ratkosrb** [comment]
Tested and confirmed it on Classic.
