### ISSUE TITLE
custom dungeons and blood ring break portals

### ISSUE THREAD

**Issue by geojak** [slowtorta/turtlewow-bug-tracker#3445]
**Please, provide a clear description what the bug is:**
after playing blood ring you get unable to go trough portals

1. queue blood ring
2. play blood ring
3. finish blood ring
4. back to the real world
5. try go trough any portal, like sw mage tower or go inside a dungeon
6. cant go inside 
7. have to relog to fix

**Expected behavior. Describe how it should work:**

blood ring should not break portals

**Comment by Zebouski** [comment]
I've been informed that Crescent Grove also does this to you, and similarly a relog fixes it.

Darnassus <-> Rutheran TP is also affected

**Comment by Gurky-Turtle** [comment]
I dont think this is just blood ring it seems to happen when you port from one map id to another

**Comment by Zebouski** [comment]
> I dont think this is just blood ring it seems to happen when you port from one map id to another

big point is, is that this doesnt seem to happen when entering blizzlike dungeons. only the custom turtle instances is "poisioning" the session

**Comment by AyleeJenn** [comment]
Has this been noted/addressed yet??

My group and I can confirm that this does indeed reliably happen in Crescent Grove dungeon. We tried it several times and every time the bug could be reproduced. I do believe that this may be a genuine bug. So I am leaving a comment here to affirm the relevance and reproducibility of this issue.

**Comment by Gurky-Turtle** [comment]
No it's not addressed it is still open

**Comment by Muigin** [comment]
All maps without AreaTriggers and using custom portals (rather than official behavior portals) have been fixed as of 1.17.0
