### ISSUE TITLE
[Quest] Return to Kheyna

### ISSUE THREAD

**Issue by mniert** [slowtorta/turtlewow-bug-tracker#3447]
**Please, provide a clear description what the bug is:**
The npc to hand in "Return to Kheyna" is bugged. Crystal summons her with no problem but players cant talk to her and so cant finish the quest 

**IDs of affected creatures, items, quests or spells with a link to the relevant page:**

NPC: https://database.turtle-wow.org/?npc=81041
Quest: https://database.turtle-wow.org/?quest=80409

**Expected behavior. Describe how it should work:**

Players should be able to hand in the quest

**Comment by slowtorta** [comment]
This one is working as intended.
