### ISSUE TITLE
Mana Funnel (rank 1) does not exist. Trainer only teaches rank 2.

### ISSUE THREAD

**Issue by jongdetim** [slowtorta/turtlewow-bug-tracker#3448]
Please, provide a clear description what the bug is:

The Turtle Wow warlock ability mana funnel (rank 1) is not sold at level 40. It actually does not even exist. The warlock trainer only sells mana funnel (rank 2) at level 50.

Steps to reproduce the behavior with as much detail as possible:

Go to the warlock trainer and check the demonology spells they teach.

Expected behavior. Describe how it should work:

The warlock class trainer should teach mana funnel (rank 1) at level 40.

**Comment by Gurky-Turtle** [comment]
this will be fixed in the next update.
