### ISSUE TITLE
Blood Pact often not applying to any or all characters, solo or grouped

### ISSUE THREAD

**Issue by jongdetim** [slowtorta/turtlewow-bug-tracker#3449]
**Please, provide a clear description what the bug is:**

The warlock demon pet Imp has an ability called Blood Pact. It increases all party member's stamina. Seemingly randomly, the buff isn't applied to any party member, including the warlock and when not grouped. The fix seems to be to disable autocasting of the Blood Pact spell. Then uncasting it. Resummoning an Imp, and then casting the Blood Pact spell.

**Steps to reproduce the behavior with as much detail as possible:**

1. Summon the Imp, and have Blood Pact on autocast.
2. Play for a while or resummon the Imp until you notice that you don't have the buff, and recasting it doesn't fix it.

**Expected behavior. Describe how it should work:**

It should correctly apply the buff to all party members within range.

**Comment by twowTurtReynolds** [comment]
We will need solid replication steps on this!

**Comment by balakethelock** [comment]
@jongdetim has to precise if at the time of the bug, the imp has the aura or not. If the imp has the aura: most likely the ol' bug with warmode not letting friendly auras affect others. If the imp doesn't have the aura: pet AI bug.

**Comment by cyaohiri** [comment]
Looks similar to #3084 and #2740.

**Comment by twowTurtReynolds** [comment]
Thanks. Closing until rep steps can be acquired.
