### ISSUE TITLE
Stormwind Druid Trainer NPC Factions (Training Prices)

### ISSUE THREAD

**Issue by Barabbi** [slowtorta/turtlewow-bug-tracker#345]
Be a Night Elf Druid that is Honored with Darnassus but only Friendly with Stormwind.  Go to the Stormwind Park area, and speak with the various Druid Trainers in the center of the area.  "Theridran" appears to be on the Darnassus reputation, while all of the other Druid Trainers in the immediate area are on Stormwind ... or another one?  This is confirmed via my level 14 Druid, training "Thorns Rank 2" costing 8s10c on Theridran but 9s on the others.

Although npcs, much like PCs, could have changed their preferred reputation, I feel they should all be on the same reputation (at a minimum).  This "druid expedition, along with others of their party", came to Stormwind and live here with the permission of Stormwind Nobles (in this era of the game, instead of the royal family).  Further, non-rp reasons, price uniformity should exist for players.

Whether Darnassus ("all druids look to the home tree") or Stormwind ("these npcs all are allied to the city / house / king"), is up to you. 

Alternatively, for even more rp, have each of the trainers have a text dialog where you can speak with them and they, in character, speak about how they are allied with a particular reputation.  So, Theridran "always looks to the home tree", another one "loves the Park, the city, and the new life here in Stormwind", and another "remembers his / her time passing through Ironforge... all those years ago... and wishes to return."

**Comment by Dormilon** [comment]
Please provide information, what exactly needs to be done?
