### ISSUE TITLE
Quest The Instigator's Enchantment cannot be turned in

### ISSUE THREAD

**Issue by Cicimici92** [slowtorta/turtlewow-bug-tracker#3450]
On my character Richgnome (lvl 60 Gnome Mage) I have obtained all quest items required for The Instigator's Enchantment quest (https://database.turtle-wow.org/?quest=8950), and the quest is marked as completed in my log:

Items:
[Jeering Spectre's Essence](https://database.turtle-wow.org/?item=22224)
4x[Dark Rune](https://database.turtle-wow.org/?item=20520)
8x[Large Brilliant Shard](https://database.turtle-wow.org/?item=14344)

However, when I go to the NPC located in Dire Maul Library (Falrin Treeshaper (https://database.turtle-wow.org/?npc=16032))
I am not able to turn in the quest (the Complete button is greyed out).

I have tried resetting the instance, logging out and in, and deleting WDB, but nothing worked.

Can you look into this?

Attached are some screenshots of my inventory, quest log and the turn in.

Thanks.
![Screenshot_2](https://github.com/slowtorta/turtlewow-bug-tracker/assets/133494765/50239e75-f6ea-4aa2-b2c7-c2e728c94c8c)
![Screenshot_3](https://github.com/slowtorta/turtlewow-bug-tracker/assets/133494765/a9c2e76a-910e-4b27-b184-9f8d0bf45705)
![Screenshot_4](https://github.com/slowtorta/turtlewow-bug-tracker/assets/133494765/1209c624-a584-4414-9e16-eb0e7f05b711)
![Screenshot_1](https://github.com/slowtorta/turtlewow-bug-tracker/assets/133494765/338199d7-3a2a-4cca-b0a0-b3cadaeb6ac7)
![Screenshot_5](https://github.com/slowtorta/turtlewow-bug-tracker/assets/133494765/fcfb6a4e-5f5f-427d-a3de-8791eb9848d0)
![Screenshot_6](https://github.com/slowtorta/turtlewow-bug-tracker/assets/133494765/4b8b70c3-ca11-4727-9af4-9c40ae1304a9)

**Comment by Gurky-Turtle** [comment]
![image](https://github.com/slowtorta/turtlewow-bug-tracker/assets/90982783/e3eecbd7-ee69-40cb-87d9-284996db594f)
![image](https://github.com/slowtorta/turtlewow-bug-tracker/assets/90982783/c68d08c0-8228-43de-b7ca-bf2028cd0d0d)
![image](https://github.com/slowtorta/turtlewow-bug-tracker/assets/90982783/cf306903-d8e1-4357-b9a2-22e4739dc3dc)
Was able to turn this in fine, abandon it and retake it also clear your wdb folder. Not a bug.
