### ISSUE TITLE
Extremely inconsistent framerate until refresh rate is set to 144hz in settings. Settings always display 60hz

### ISSUE THREAD

**Issue by jongdetim** [slowtorta/turtlewow-bug-tracker#3454]
**Please, provide a clear description what the bug is:**

Every session, my fps oscillates between ~60 and 147, and the game is visually unsmooth. After setting the refresh rate to 144 in the game's video settings, suddenly it maintains a steady 147.8 fps. This also comes with visual bugs in the menus, such as the character screen tabs, which are white squares without text.

**Steps to reproduce the behavior with as much detail as possible:**

1. On a 144 hz monitor, on "windowed mode", notice the settings show 60hz selected.
2. Notice the frametimes being all over the place.
3. Select the 144hz setting in video settings.
4. Notice that the frametimes are fixed.
5. Menus are now graphically bugged.

**Comment by Gurky-Turtle** [comment]
This is a client limitation, you can always try editing the config.wtf with a frame rate of 200 as I have heard that works.

**Comment by jongdetim** [comment]
Indeed. I have since fixed it by using VanillaFixes
