### ISSUE TITLE
Seal/Judgement of Wisdom does not give threat

### ISSUE THREAD

**Issue by bugzy411** [slowtorta/turtlewow-bug-tracker#3455]
It's a well-known fact that resource regen causes threat. Rage has a 5x threat modifier. HP has a 0.25x threat modifier. Mana has a 0.5x threat modifier. So, if someone hits a mob and deals 100 threat, if you are on the threat table, and immediately pop a potion, you'll rip aggro off the tank if your healing or mana regen goes over 110 threat in melee or 130 threat if ranged since you need to do 1.1x threat to pull aggro in melee or 1.3x threat in ranged. Passive mana regen from say blessing of wisdom or mana spring totem do not give threat.

If seal/judgement both proc from a single hit, that will give you 149 mana regen. This should give the paladin 141.55 extra threat spread throughout all the mobs that you have on the threat table since righteous fury affects holy spells and should apply a 1.9 threat modifier. Likewise, if using seal of righteousness and it procs judgement of wisdom, it should give you an extra 56.05 threat per proc. If the turtle wow threat meter is legit and is showing proper threat values, then you are not gaining this threat at all.

I tested on a training dummy in Stormwind and I used the turtle wow threat meter, which supposedly pulls directly from the server to show accurate threat values and all I see are my white hits from auto attack generating threat. I've dropped my hp and my mana to test this and should be fixed asap. Seal/judgement of light is giving proper threat values and is modified by righeous fury.

**Comment by redmagejoe** [comment]
Confirmed that no Power Gains generate threat on Turtle (and possibly vmangos).  Bloodrage is an exception, possibly having been programmed with inherent threat bonus, as it was tested extensively and was the only form of technique by which to gain Rage which pulled aggro on a 0 threat target.

**Comment by Gurky-Turtle** [comment]
Fixed in the next update
