### ISSUE TITLE
Forlorn spirit stalvan quest elwynn forest

### ISSUE THREAD

**Issue by GrillBanditten** [slowtorta/turtlewow-bug-tracker#3458]
**Please, provide a clear description what the bug is:**
So i was doing the stalvan questline and when i reached the lumber camp in elwynn forest there where multiple (10+) of these spirits.
It would seem to me that the despawn timer is disabled or some other bug has happened before i arrived there. 
Server time 19:45.

A GM turned and killed them all, and when i took the torn jounal only one spawned as intended.

As it was a single coincidence for me, i cant reproduce anything. Sorry.

**Steps to reproduce the behavior with as much detail as possible:**

1.
2. 
3. 

**IDs of affected creatures, items, quests or spells with a link to the relevant page:**

NPC: https://database.turtle-wow.org/?npc=2044
Item: https://database.turtle-wow.org/?item=
Quest: https://database.turtle-wow.org/?quest=74
Spell: https://database.turtle-wow.org/?spell=
Object: https://database.turtle-wow.org/?object=

**Expected behavior. Describe how it should work:**

**Comment by Muigin** [comment]
Cannot reproduce on current version.
