### ISSUE TITLE
Goblins Hunters Can't Learn Skills from Liott Maneskin

### ISSUE THREAD

**Issue by JoLiKMC** [slowtorta/turtlewow-bug-tracker#3459]
**Please, provide a clear description what the bug is:**
When a Goblin Hunter talks to Liott Maneskin, the a Level 15 Hunter Trainer hanging out in Brill, Tirisfail Glades, they are not given the option to learn new skills.

**Steps to reproduce the behavior with as much detail as possible:**
1. Create a Goblin Hunter character.
2. Go to Brill in the Tirisfal Glades and talk to Liott Maneskin. <sup>(X: 60.2, Y: 61.5)</sup>

**IDs of affected creatures, items, quests or spells with a link to the relevant page:**
NPC: https://database.turtle-wow.org/?npc=60484

**Expected behavior. Describe how it should work:**
When talking to a class trainer of any kind, if the player is a matching class, they should always be able to learn new skills from said trainer so long as their Reputation is Neutral or higher.  [Morpheus Ribcage](https://database.turtle-wow.org/?npc=60483) is able to teach Goblin Hunters new skills up to Level 6, as expected.  The three Hunter Trainers inside the Undercity are also able to teach skills to Goblin Hunters.  It's only Liott that's the odd trainer out.

Incidentally, I have not tested this with the other three races (Orc, Troll, Tauren), so this may not be isolated to just Goblins.

**Comment by JoLiKMC** [comment]
Upon further investigation, [Dark Ranger Lanissa](https://database.turtle-wow.org/?npc=81050) can and does allow Goblins to train their Hunter skills.  Considering her proximity to Liott Maneskin, I'd say this bug just became even less significant.

**Comment by twowTurtReynolds** [comment]
![image](https://github.com/slowtorta/turtlewow-bug-tracker/assets/151180101/1c9f9fa9-a7fd-4cf0-9f38-9cf3681773c2)
I cannot reproduce.
