### ISSUE TITLE
[Data rescue] Gnomeregan quest item is unobtainable

### ISSUE THREAD

**Issue by Zulmamwe** [slowtorta/turtlewow-bug-tracker#346]
I see that there are already 3 issues about this problem #139 #142 #273  but i thought that they dont describe it as wholesome and maybe that's why there is no progress fixing it

**Please, provide a clear description what the bug is:**
Gnomeregan quest [Data rescue](https://database.turtle-wow.org/?quest=2930) cannot be completed since required quest item is unobtainable

**Steps to reproduce the behavior with as much detail as possible:**

1. Take quest and do steps 1 & 2 described in expected behavior
2. Try to interact with [Matrix Punchograph 3005-B](https://database.turtle-wow.org/?object=142475) and see that dialogue window doesnt open leaving you with no way to receive next punch cards

**IDs of affected creatures, items, quests or spells with a link to the relevant page:**

Quest: https://database.turtle-wow.org/?quest=2930
Items:
https://database.turtle-wow.org/?item=9282 - blue
https://database.turtle-wow.org/?item=9281 - red
https://database.turtle-wow.org/?item=9316 - prismatic

Objects:
https://database.turtle-wow.org/?object=142475 - terminal 2
https://database.turtle-wow.org/?object=142476 - terminal 3
https://database.turtle-wow.org/?object=142696 - terminal 4 (on first glance it seems to work fine but no means to check)

**Expected behavior. Describe how it should work:**
The quest itself requires you to do next steps:
1. First get a random drop [White Punch Card](https://database.turtle-wow.org/?item=9279) from monsters near Gnomeregan entrance - **that part works**
2. Then go to first terminal [Matrix Punchograph 3005-A](https://database.turtle-wow.org/?object=142345) that is also near entrance and acts as quest giver (clicking opens dialogue window and doesnt require casting/opening time) which has dialogue option to put white punch card in (it is removed then) to receive [Yellow Punch Card](https://database.turtle-wow.org/?item=9280) - **that part works**
3. Go to the second terminal [Matrix Punchograph 3005-B](https://database.turtle-wow.org/?object=142475),  this one is inside dungeon near gnome camp, this terminal should do the same thing but requiring [Yellow Punch Card](https://database.turtle-wow.org/?item=9280) to produce [Blue Punch Card](https://database.turtle-wow.org/?item=9282) - **this doesnt work, terminal acts as a container (requiring 5s to open it) and doesnt show dialogue window making [Blue Punch Card](https://database.turtle-wow.org/?item=9282) unobtainable and next stages incompletable**
4. Go to third terminal [Matrix Punchograph 3005-C](https://database.turtle-wow.org/?object=142476) located on a platform near boss [Electrocutioner 6000](https://database.turtle-wow.org/?npc=6235) to give in [Blue Punch Card](https://database.turtle-wow.org/?item=9282) and receive [Red Punch Card](https://database.turtle-wow.org/?item=9281) - **i assume this doesnt work since it acts as a container too and doesnt show dialogue window (checked just now but can't say for sure cuz blue punch card is unobtainable)**
5. Finally go to last fourth terminal [Matrix Punchograph 3005-D](https://database.turtle-wow.org/?object=142696) located on the lower level of room where boss [Crowd Pummeler 9-60](https://database.turtle-wow.org/?npc=6229) resides to transform [Red Punch Card](https://database.turtle-wow.org/?item=9281) into [Prismatic Punch Card](https://database.turtle-wow.org/?item=9316) which is the objective of this quest - **this part seems to be working, terminal acts as it should and opens dialogue window, but since previous punch cards are unobtainable i cant check if it can transform punch card into desired quest item**

Another way to fix this quest (more like hot fix to make it at least completable while you work on fixing it fully) is to make quest objective item [Prismatic Punch Card](https://database.turtle-wow.org/?item=9316) drop from boss in the same room as last terminal [Crowd Pummeler 9-60](https://database.turtle-wow.org/?npc=6229) and add that info into quest text

**Comment by thrassoss** [comment]
This is an excellent description and I also can confirm this bug.

**Comment by slowtorta** [comment]
Thank you for this great and detailed report. This will be fixed on the next server update!
