### ISSUE TITLE
"The Hunter's Path" (Goblin, Thunder Bluff) is Buggy

### ISSUE THREAD

**Issue by JoLiKMC** [slowtorta/turtlewow-bug-tracker#3461]
**Please, provide a clear description what the bug is:**
As a Goblin Hunter, when doing the Level 10 quest, "The Hunter's Path", Kary Thunderhorn both starts **and** finishes the quest, but she's not supposed to finish the quest.

**Steps to reproduce the behavior with as much detail as possible:**
1. Create a Goblin Hunter character.  Raise it up to Level 10.
2. Go to the Hunter Rise of Thunder Bluff and talk to Kary Thunderhorn. <sup>(X: 58.5, Y: 88.4)</sup>
3. Accept her version of the quest, "The Hunter's Path".

**IDs of affected creatures, items, quests or spells with a link to the relevant page:**
NPC: https://database.turtle-wow.org/?npc=3038 ("Kary Thunderhorn")
Quest: https://database.turtle-wow.org/?quest=80330 ("The Hunter's Path")

**Expected behavior. Describe how it should work:**
The player should not be able to turn the quest in to the quest-giver.  Instead, it should be turned in at [Viz Fizbeast](https://database.turtle-wow.org/?npc=80903).

**Further details:**
After receiving the quest, the player is directed to go to Razor Hill in Durotar and speak with Viz Fizbeast to start the pet training quest chain.  However, the prerequisite quest can *also* be turned in to the quest-giver, Kary Thunderhorn.  Doing so causes the quest to complete like normal, but the quest completion dialogue stays open.

This doesn't appear to have any negative impact on the quest line.  It disallows the other versions of the quest and [the next quest](https://database.turtle-wow.org/?quest=80331) still opens up just fine.

**Comment by Gurky-Turtle** [comment]
should be fixed next update.
