### ISSUE TITLE
Flypath bug and reconnected at the wrong place

### ISSUE THREAD

**Issue by pierretusseau** [slowtorta/turtlewow-bug-tracker#3463]
## **Please, provide a clear description what the bug is:**
I took the flypath from Wester Plague Lands (Chillwind Camp) in direction for Menethil Harbor.
I tried to move (forward key) just as I arrived, then the griffin started acted strange (a bit like the griffin in Goldshire when you move just as griffin pop)
Suddenly the griffin started to fly in straight line to the north, going through the terrain. It went past Alah'thalas until the border of the map.
When it arrived at the far north it started flying backwards with a weird angle back to the south.
It passes through Alah'thalas FP and got back to Wester Plague Lands FP.

Since then I've **often** a bug when I reconnect (from SW or something else in Eastern Kingdom), I respawn at Chillwind Camp

I wish at least to get a reset to have my char reconnect at the suitable place.

## **Steps to reproduce the behavior with as much detail as possible:**

1. Take Flypath from Western Plague Lands (Chillwind Camp)
2. Arrive at Menethil Harbor (maybe try to move JUST AS the FP finish)

## **Expected behavior. Describe how it should work:**
Arrive at the FP without problem.
Respawning where I disconnected.

**Comment by slowtorta** [comment]
This bug will be fixed in the patch 1166.

**Comment by pierretusseau** [comment]
Thanks a lot for the hard work ! 💪😁 👍
