### ISSUE TITLE
Jail break!

### ISSUE THREAD

**Issue by Meridaw** [slowtorta/turtlewow-bug-tracker#3466]
**Please, provide a clear description what the bug is:**

**Steps to reproduce the behavior with as much detail as possible:**

1. After [Marshal Windsor](https://www.wowhead.com/classic/npc=9023/marshal-windsor) get his gear back horde players can attack him. easily bugging the quest.

**IDs of affected creatures, items, quests or spells with a link to the relevant page:**

NPC: https://www.wowhead.com/classic/npc=9023/marshal-windsor
Quest: https://www.wowhead.com/classic/quest=4322/jail-break

**Expected behavior. Describe how it should work:**
Horde players should have no opportunity to attack him during the quest partying with Alliance players.

**Comment by twowTurtReynolds** [comment]
![image](https://github.com/slowtorta/turtlewow-bug-tracker/assets/151180101/2763c211-3cbb-4858-a446-139df3059c13)
Yep, his NPC ID 9023 works fine, but this powered up one 9682 doesn't:
![image](https://github.com/slowtorta/turtlewow-bug-tracker/assets/151180101/04c3b2b3-9b5f-44ab-b5fa-2e504d92a942)

**Comment by ratkosrb** [comment]
Should be fixed in the next update.
