### ISSUE TITLE
Breaking the Felstar, Friendly NPC's not spawning.

### ISSUE THREAD

**Issue by Nolez123** [slowtorta/turtlewow-bug-tracker#3467]
I was hoping to be able to reopen ticket #2969 as this exact issue has just happened. The event starts fine and the elite mob spawns after the 2 waves of normal npcs are killed. However the Ranger Mobs that are supposed to spawn to assist in this quest do not spawn at all after the elite mob does.

**Comment by Letic92** [comment]
@Nolez123 

Helpers should spawn when dralox felstar has hp between 50% and 75%. If they are not spawned in that period, then it is a bug.

**Comment by Muigin** [comment]
Cannot reproduce on current version.
