### ISSUE TITLE
Spirit link spell should be the exact same but instead of 2s cast, instant cast.

### ISSUE THREAD

**Issue by chud123** [slowtorta/turtlewow-bug-tracker#3468]
**Please, provide a clear description what the bug is:**

**Steps to reproduce the behavior with as much detail as possible:**

1. Use twow only, Tauren Shaman, ability: Spirit Link
2. It is horrible at a 2 second cast, Orc and Troll get wolves/hex respectively when they are already meta and "better" than Tauren as shammy.
3. If you made it an instant cast maybe it gets used sometimes.  Cool spell, let's make it useful!  Currently at a 2 sec cast and chain heal having 2.1s (with aq40 gear) it seems like only useful as a prebuff but it lasts 30 seconds....Instant makes it more balanced with the other two races that can play shammy both for PvE and PvP.  People in-game have agreed it should at least be instant to be viable.

**IDs of affected creatures, items, quests or spells with a link to the relevant page:**

Spell: https://database.turtle-wow.org/?spell=45500

**Expected behavior. Describe how it should work:**
Spirit link spell should be the exact same but instead of 2s cast, instant cast.

**Comment by twowTurtReynolds** [comment]
Suggestions do not belong on the bug tracker.
