### ISSUE TITLE
Hunter pet skill bug - game breaking

### ISSUE THREAD

**Issue by davephilpz** [slowtorta/turtlewow-bug-tracker#3469]
**Please, provide a clear description what the bug is:**

**Steps to reproduce the behavior with as much detail as possible:**

1. Account Zansatsusha; Character Evilmoka
2. All hunter pets have no skills
3. Cannot open skill panel
4. Cannot reset or retrain at trainer
5. Tried WDB etc.
6. Need a hard reset since it was broken on the reset patch
7. 
8. P.S. I am a programmer and could possibly help with game updates etc.

**IDs of affected creatures, items, quests or spells with a link to the relevant page:**

NPC: https://database.turtle-wow.org/?npc=
Item: https://database.turtle-wow.org/?item=
Quest: https://database.turtle-wow.org/?quest=
Spell: https://database.turtle-wow.org/?spell=
Object: https://database.turtle-wow.org/?object=

**Expected behavior. Describe how it should work:**

**Comment by slowtorta** [comment]
We are looking into your issue, it will be fixed as soon as we know what happened.

**Comment by davephilpz** [comment]
Thanks.

Let me know if you need any help with new game updates etc.

Have experience in JS, C#, Python and SQL, noSQL, vector databases and AI integrations.
