### ISSUE TITLE
Silver Skeleton Key does not get add-ed to your inventory

### ISSUE THREAD

**Issue by Tinyfin-github** [slowtorta/turtlewow-bug-tracker#347]
Silver Skeleton Key does not get add-ed to your inventory.

When creating the key the required items get consumed but the key does not show in the inventory.
The key can't be add-ed by gm commands. You get the  You create: [Silver Skeleton Key]. confirmation message, but there is no item in the inventory.

https://database.turtle-wow.org/?item=15869 Silver Skeleton Key

**Comment by AyleeJenn** [comment]
When ever I create "Silver Skeleton Key" via the blacksmith profession, the keys are directly put into the key ring. And when I open my key ring I find the silver skeleton keys that I created.

If my key ring is full, then the silver skeleton keys are put in my inventory.
