### ISSUE TITLE
Can't see above water surface while swimming

### ISSUE THREAD

**Issue by lasuax** [slowtorta/turtlewow-bug-tracker#3474]
**Please, provide a clear description what the bug is:**

I play as a _Female Tauren Warrior_, the world above water is not visible while swimming through any angle.

**Steps to reproduce the behavior with as much detail as possible:**

As a **_female tauren warrior_**,

1. Jump into water
2. Swim & change camera angle in order to see the world
3. Observe the result. It's not possible to see sky unless you jump

**Expected behavior. Describe how it should work:**

I should be able to see my head, back & the world above while swimming.

You can see from the images that I'm at the top of water and there's no breath bar.

![image](https://github.com/slowtorta/turtlewow-bug-tracker/assets/8995583/85e48d6b-12e4-4fee-9791-6014ce56d9bb)
![image](https://github.com/slowtorta/turtlewow-bug-tracker/assets/8995583/31b9234b-6500-47a3-97c4-7837aa5a8b5e)

**Comment by JoLiKMC** [comment]
Have you tried disabling all of your AddOns and testing again?  I've only been able to replicate this problem by doing the following:

1. Log in as a female Tauren character.
2. Open the Game Menu, go to Interface Options.
3. Under "Camera", click the checkbox and **enable** Water Collision.
4. Move forward and jump.
Doing this, you will occasionally get the "underwater camera" despite being above water.

Anyway, Try disabling "Water Collision" and see if that helps.

**Comment by lasuax** [comment]
> Have you tried disabling all of your AddOns and testing again? I've only been able to replicate this problem by doing the following:
> 
>     1. Log in as a female Tauren character.
> 
>     2. Open the Game Menu, go to Interface Options.
> 
>     3. Under "Camera", click the checkbox and **enable** Water Collision.
> 
>     4. Move forward and jump.
>        Doing this, you will occasionally get the "underwater camera" despite being above water.
> 
> 
> Anyway, try disabling "Water Collision" and see if that helps.

All these years, I have never realized that there's such a setting there. Disabling 'Water Collision' fixed the issue. Thank you very much @JoLiKMC
