### ISSUE TITLE
Steepcliff Inn Not Giving Rested XP Buff… Again?

### ISSUE THREAD

**Issue by JoLiKMC** [slowtorta/turtlewow-bug-tracker#3477]
**Please, provide a clear description what the bug is:**
The inn building at Steepcliff Port in Tirisfal Glades does not give players any amount of "Rested" experience points.

**Steps to reproduce the behavior with as much detail as possible:**
1. Bring a Horde character to Steepcliff Port in Tirisfal Glades.
2. Make your character enter the large building near X: 4.5, Y: 62.4.

**IDs of affected creatures, items, quests or spells with a link to the relevant page:**
NPC: https://database.turtle-wow.org/?npc=91748 (Innkeeper Natt)

**Expected behavior. Describe how it should work:**
As with all inns that the player can set as their home, it's expected that when the get within range of the building, they begin [earning Rested XP](https://wowpedia.fandom.com/wiki/Rest).

**Further details:**
This issue has been documented as "don't know how to fix" in #623 and marked as **solved** in #755 (as of v1.16.1).  Currently (v1.16.5), however, the inn seems to have stopped (?) giving the expected buff.  Not game-breaking, but slightly frustrating.

**Comment by slowtorta** [comment]
Will be fixed in patch 1.16.6
