### ISSUE TITLE
Bugged Timothy Worthington

### ISSUE THREAD

**Issue by madziom** [slowtorta/turtlewow-bug-tracker#3478]
**Please, provide a clear description what the bug is: Can't learn artistian tailoring. [Timothy Worthington] wont teach me a thing. 

**Steps to reproduce the behavior with as much detail as possible: I have 225lvl tailoring lvl 50 warlock. When i click on "learn" nothin happens.

**IDs of affected creatures, items, quests or spells with a link to the relevant page:**

NPC: https://database.turtle-wow.org/?npc=11052

**Expected behavior. Describe how it should work: i should be able to learn new skill - tailoring to 300 lvl and recipies from https://database.turtle-wow.org/?npc=11052

**Comment by Gurky-Turtle** [comment]
Unable to reproduce this issue, might have been caused by WDB or a addon.
