### ISSUE TITLE
Gubber Blump will teach you fishing even if you already know

### ISSUE THREAD

**Issue by AyleeJenn** [slowtorta/turtlewow-bug-tracker#348]
**Please, provide a clear description what the bug is:**

Gubber Blump (fishing npc in Auberdine) will have a conversation option reading "Gubber, I don't know how to fish".
It -looks- like a speech option like when you ask the guards where to learn fishing but if you click that Gubber Blump will (without warning) teach you fishing.

If you don't know fishing yet, thats a good thing
But if you already know fishing, thats not a good thing.

Especially if you have a higher fishing rank than journeyman (skill 0 - 75)
What will happen is that your fishing skill will be "reset" and your character screen will show something like, for example, 158/75 (as if your fishing skill had a maximum of 75).

Your fishing **rank** will still show as expert or however far you got and as a result, fishing teachers won't teach you.

**Steps to reproduce the behavior with as much detail as possible:**

1. Learn fishing to a more advanced rank than journeyman
2.  Talk to Gubber Blump in Auberdine and select "Gubber, I don't know how to fish"
3.  Press "C" to open your character screen and browse your skills

**IDs of affected creatures, items, quests or spells with a link to the relevant page:**

NPC: https://database.turtle-wow.org/?npc=10216
Item: https://database.turtle-wow.org/?item=
Quest: https://database.turtle-wow.org/?quest=
Spell: https://database.turtle-wow.org/?spell=
Object: https://database.turtle-wow.org/?object=

**Expected behavior. Describe how it should work:**
In my opinion, what **should** happen is that a "Fishing Teacher Window" opens and you can select to manually learn fishing. But having the NPC cast the "spell" on you without warning can really unsettle you and give your the impression that your character is bugged. Especially if it happens on a HC =S

I was able to resolve this issue myself (at least I think) I will detail this in a comment below. But I still recommend changing Gubber Blump to open a fishing teacher window rather than just teaching you without warning.

**Comment by AyleeJenn** [comment]
How to fix this if it happens to you:

#1. Log out of the game
#2 Find and delete your WDB folder
#3. Log back into the game and press "C" to open your character window and browse your skills.
#4. Your fishing skill -should- be back to where it was.

At least that is how it worked for me.

**Comment by slowtorta** [comment]
This will be fixed on the next server update. He'll no longer show this option to players who already know how to fish.
