### ISSUE TITLE
Enchant Gloves - Minor Haste does not increase casting speed

### ISSUE THREAD

**Issue by moujique** [slowtorta/turtlewow-bug-tracker#3482]
**Please, provide a clear description what the bug is:**

**Steps to reproduce the behavior with as much detail as possible:**

1. Only increases attack speed
2. 
3. 

**IDs of affected creatures, items, quests or spells with a link to the relevant page:**

NPC: https://database.turtle-wow.org/?npc=
Item: https://database.turtle-wow.org/?item=
Quest: https://database.turtle-wow.org/?quest=
Spell: https://database.turtle-wow.org/?spell=13948
Object: https://database.turtle-wow.org/?object=

**Expected behavior. Describe how it should work:**  Should increase casting speed also according to description

**Comment by Gurky-Turtle** [comment]
https://github.com/slowtorta/turtlewow-bug-tracker/issues/2921
