### ISSUE TITLE
Basic Campfire does not do damage to player

### ISSUE THREAD

**Issue by moujique** [slowtorta/turtlewow-bug-tracker#3483]
**Please, provide a clear description what the bug is:**

**Steps to reproduce the behavior with as much detail as possible:**

1. Basic Campfire does not do damage to player
2. 
3. 

**IDs of affected creatures, items, quests or spells with a link to the relevant page:**

NPC: https://database.turtle-wow.org/?npc=
Item: https://database.turtle-wow.org/?item=
Quest: https://database.turtle-wow.org/?quest=
Spell: https://database.turtle-wow.org/?spell=13948
Object: https://database.turtle-wow.org/?object=31442 

**Expected behavior. Describe how it should work:**  Probably should do periodic damage to player if you stand on it

**Comment by redmagejoe** [comment]
This behavior was changed on Turtle a long time ago for anti-griefing reasons. It is likely it will be labelled as Won't Fix.
