### ISSUE TITLE
Arathi Basin Missing From Battleground Finder Until Level 20

### ISSUE THREAD

**Issue by JoLiKMC** [slowtorta/turtlewow-bug-tracker#3486]
**Please, provide a clear description what the bug is:**
Low level players (Level 1 through Level 19) can participate in Arathi Basin Battlegrounds when speaking with the appropriate Battlemaster.  However, this Battleground is not listed in the Battleground Finder.  Only Blood Ring and Warsong Gulch.

**Steps to reproduce the behavior with as much detail as possible:**
1. Create a new character **or** log in with a character that's Level 19 or lower.
2. Go to any main city and find the Arathi Basin Battlemaster.
3. Talk to the Arathi Basin Battlemaster.

**Expected behavior. Describe how it should work:**
- Arathi Basin should be listed in the Battleground Finder from Level 1 onward.
**Or**
- The Battlemaster should turn away any player who is Level 19 or below.

**Further thoughts:**
I know that Warsong Gulch is open for players Level 1 and higher on this server, but I don't recall anything about Arathi Basin.  I was very surprised when I talked to an Arathi Basin Battlemaster at Level 1 and they were like, "Yeah!  Join the fight!"  Then I tried again at Level 19 and, yep, same thing.  Despite that, there's no listing for it in the Battleground Finder.

Either the lack of a minimum level is the oversight or the lack of listing in the Battleground Finder is.  I say this because talking to a Alterac Valley Battlemaster won't let players under Level 19 (at least) join an Alterac Valley match.  Honestly, though, I think it'd be hilarious to see a Level 1 Arathi Basin Battleground, sometime!

**Comment by redmagejoe** [comment]
Arathi is a 20+ BG.  This is working as intended.

@slowtorta Please close.
