### ISSUE TITLE
Exit Strategy (Goblin Racial) Does Not Stack With Other Speed Boosts

### ISSUE THREAD

**Issue by JoLiKMC** [slowtorta/turtlewow-bug-tracker#3487]
**Please, provide a clear description what the bug is:**
If a player uses the Goblin racial ability "Exit Strategy" while under the effects of another speed-boosting ability, the two do not combine for an additional speed boost.

**Steps to reproduce the behavior with as much detail as possible:**
1. Create a Goblin character.
2. Level high enough to get a speed-boosting ability. (Sprint, Aspect of the Cheetah, et cetera.)
3. Cast your speed-boosting ability and move forward.
4. Cast Exit Strategy while moving during the other speed boost.

**IDs of affected creatures, items, quests or spells with a link to the relevant page:**
Spell: https://database.turtle-wow.org/?spell=46240 (Exit Strategy <sup>(speed boost, speed loss effect)</sup>)

**Expected behavior. Describe how it should work:**
The 40% speed increase of Exit Strategy should be added to whatever speed boost is already in effect.

**Further thoughts:**
Rather than stack, it doesn't do anything at all if the current speed boost is higher than 40%.  In all honesty, this is probably intentional.  Exit Strategy seems like it was meant to be a temporary ability to begin with.  Still, it would be kind of cool to have, for example, a very short 110% speed boost from Sprint (Rank 3) and Exit Strategy.

**Comment by jendryk** [comment]
I think it was meant to be this way. If you look closely, Exit Strategy is not a buff, it's a debuff and if it stacked with like sprint it might have been broken.
