### ISSUE TITLE
The aspect of the pack does not affect undead priests in both standard and shadow form

### ISSUE THREAD

**Issue by bisman2000** [slowtorta/turtlewow-bug-tracker#3488]
**Please, provide a clear description of what the bug is:**
The aspect of the pack does not affect undead priests in both standard and shadow form
**Steps to reproduce the behavior with as much detail as possible:**

1. need hunter with 2 points on pathfinding talent and priest group together
2. Hunter turns on the aspect of  the pack

**IDs of affected creatures, items, quests, or spells with a link to the relevant page:**
Spell: https://database.turtle-wow.org/?spell=13159
Spell:https://database.turtle-wow.org/?spell=19563

**Expected behavior. Describe how it should work:**
the priest should be under the effect of the Aspect of the pack
![image](https://github.com/slowtorta/turtlewow-bug-tracker/assets/128370906/875a48e6-a070-41b1-a867-e6b158e3b4ac)

**Comment by balakethelock** [comment]
Most likely the cause is not being an undead priest as you said.

Related to #2863

**Comment by twowTurtReynolds** [comment]
Seems to be working as expected at the moment. Please let me know if you find other replication steps.
