### ISSUE TITLE
Gluth Decimate Bug

### ISSUE THREAD

**Issue by Spoo-THC** [slowtorta/turtlewow-bug-tracker#3489]
**Please, provide a clear description what the bug is:**
On decimate in Gluth Fight all warriors in beserker stance are instantly killed. Previously it would drop you to the correct % of HP but now i beleave its dealing a extra 10% damage based off beserker stance. This happened Tonight in THC raid
**Steps to reproduce the behavior with as much detail as possible:**

1. Beserker stance on gluth
2. Gluth casts decimate 
3. Death

**IDs of affected creatures, items, quests or spells with a link to the relevant page:**
Naxx 1434
NPC: https://database.turtle-wow.org/?npc=15932
Item: https://database.turtle-wow.org/?item=
Quest: https://database.turtle-wow.org/?quest=
Spell: https://database.turtle-wow.org/?spell=
Object: https://database.turtle-wow.org/?object=

**Expected behavior. Describe how it should work:**
Decimate should drop you to correct % of HP not kill you instantly :)

**Comment by twowTurtReynolds** [comment]
I set my HP to 2billion
![image](https://github.com/slowtorta/turtlewow-bug-tracker/assets/151180101/d91c4405-185b-4db7-ad7e-d6a8f173e7d8)
He left me with 100 million.
