### ISSUE TITLE
Zombies from above!? More likely than you think. Arathi highland bug

### ISSUE THREAD

**Issue by Goldfeessh** [slowtorta/turtlewow-bug-tracker#3491]
**Please, provide a clear description what the bug is:**
I was walking in Arathi highlands on the main road. And there was a group of 4/5 lvl 35 forsaken bodyguards (I think that’s their name) and at some point their “code” got confused and they lifted off the ground in a running animation and went many “miles” in a few seconds to the start of the path  and on the way tagged my character and “returned to unleash vengeance”. All while flying and completely ignoring vanish. It happened in like 10 seconds and was really strange because usually mobs will just turn around and walk slowly if they’re pathing like that. But maybe they’re an elite band of trained killers who know how to fly and strike with deadly precision? If that’s the case I think their skills are being wasted on dwarves that just wanted to go fishing. I know it’s no one’s fault it just sucks to have lost 50 hours to a glitch so I’m hopping it can be tweaked so it doesn’t happen to anyone else. 

**Steps to reproduce the behavior with as much detail as possible:**

1. Walk down main road in Arathi highlands
2. Witness godsquad zombies
3. Watch as they fly over you, recognize you as unworthy and slap you into the nether realm. 

**IDs of affected creatures, items, quests or spells with a link to the relevant page:**

NPC: https://database.turtle-wow.org/?npc=
Item: https://database.turtle-wow.org/?item=
Quest: https://database.turtle-wow.org/?quest=
Spell: https://database.turtle-wow.org/?spell=
Object: https://database.turtle-wow.org/?object=

**Expected behavior. Describe how it should work:**

Hopefully a more natural pathing behavior, I was staying a ways back so I could see them turn around and sidestep them. But 🤔 now that I think about it they probably saw that coming. So this might actually be my fault. 

I’m still a bit grumpy so I’m trying to be silly about it. I hope this is clear enough and I appreciate the work you put in. Turtle wow (despite flying zombies) has been alot of fun and a way to connect with my brother while they’re away. 

All the best, Heamh, the very dead dwarf.

**Comment by Muigin** [comment]
Cannot reproduce on current version.
