### ISSUE TITLE
Totemic Recall is not returning mana from some totems

### ISSUE THREAD

**Issue by KedsCode** [slowtorta/turtlewow-bug-tracker#3492]
I don't know if it's a bug with war mode like the totems buffs not showing up or not. But:

**Steps to reproduce the behavior with as much detail as possible:**

1. Use Earthbind Tot or Healing Stream tot or Poison/Disease Cleaning Totem or Ground totem, Tranquil Tot or Sentry Tot.
2. Use Totemic Recall expecting 25% of their mana cost back
3. Don't get any mana back

**Expected behavior. Describe how it should work:**

Should be returning the equivalent mana.

**Comment by ekl1111** [comment]
I did some tests with totemic recall.
I should be getting 78.75 mana from 4 totems but I get 31 mana. 
Tested with Stoneskin Totem, Searing Totem, Mana Spring Totem, Grounding Totem.

**Comment by twowTurtReynolds** [comment]
Stoneskin 210 mana returns 50
Searing 110 mana returns 25
Stoneskin 210 searing 110 returns 75
Mana spring 100 returns 25

All seems well.
