### ISSUE TITLE
Shaman Feral Spirit Orc Racial Wolf weird behavior and very low damage

### ISSUE THREAD

**Issue by KedsCode** [slowtorta/turtlewow-bug-tracker#3493]
**Steps to reproduce the behavior with as much detail as possible:**

1. I was questing with my GF, her void walker was tanking a mob, I used Feral Spirit and just auto attacked
2. Wolf just standed there doing nothing until the time the ability ended, doing ZERO attacks.
3. Also, their damage seems to low for my level (58) doing 24 damage each hit based on the long CD the ability has and high mana cost.

**Expected behavior. Describe how it should work:**
1. Spirit Wolf should be able to detect whenever I'm in combat and should attack the target accordingly.
2. Spirit Wolf should do more damage (maybe be based on my attack power or something)

**Comment by ratkosrb** [comment]
They will be improved after the next update.
