### ISSUE TITLE
Felgur Twocuts doesn't give quests

### ISSUE THREAD

**Issue by t0bb1** [slowtorta/turtlewow-bug-tracker#3494]
The quest giver "Felgur Twocuts" in Desolace just doesn't give any quest
![khan](https://github.com/slowtorta/turtlewow-bug-tracker/assets/134105881/a693fd96-0b31-40bf-a485-6da3e550b23a)

NPC: https://database.turtle-wow.org/?npc=5395
Quest: https://database.turtle-wow.org/?quest=1365

**Expected behavior. Describe how it should work:**
- Flegur Twocuts should give the quest called "Khan Dez'hepah"

**Comment by ratkosrb** [comment]
This is not a bug. You must complete the prequest The Kolkar of Desolace first.
