### ISSUE TITLE
Newly Created Characters Not Appearing on Character Select

### ISSUE THREAD

**Issue by JoLiKMC** [slowtorta/turtlewow-bug-tracker#3496]
**Please, provide a clear description what the bug is:**
Seemingly at random, a newly-created character will not appear on the character selection screen.

**Steps to reproduce the behavior with as much detail as possible:**
***Note:** This may not always work as the glitch seems to happen entirely at random…*
1. Log into your *World of Warcraft* account.
2. Create a new character of any race / class combo and with any valid name.

**Expected behavior. Describe how it should work:**
The new character should appear on in your character roster and be immediately selectable.

**Further details:**
When a character disappears from a player's roster, they will still appear on the "characters on realm" counter in the Realm Selection screen – at least, for a time.  Eventually, the character seems to vanish entirely, lost in limbo.  The characters also don't appear on the Account Management page on the main website.  However, their name becomes unusable, hinting that the character still exists.

This seems to have started as of yesterday.  A handful of users (myself included) [have reported this](https://forum.turtle-wow.org/viewtopic.php?t=7338) on the official forums.  It's a very odd bug and very confusing…  The fact that it happens at *random* absolutely does not help with bug-testing.  However, one thing I've noticed is that it seems to happen more when users delete a character then try to make a character with the *same name*.

Maybe the database can't keep up?  I can't even *fathom* how many characters are in that thing by now.
<sup>My own local census has over 12,000 from just the last three weeks or so…</sup>

**Comment by JD-42** [comment]
Lost 3 characters to this so far. It does indeed seem to occur after you delete a character and use the same name within a few minutes timeframe causing the name to be taken but the character to not exist on the account as a playable character.

**Comment by JoLiKMC** [comment]
Oh, right.  I sort of forgot about this, entirely.  It was fixed about [two weeks ago](https://forum.turtle-wow.org/viewtopic.php?t=7411).

Cheers, Turtle Team!  ♥
