### ISSUE TITLE
Item has wrong quality type

### ISSUE THREAD

**Issue by MrShmiTT** [slowtorta/turtlewow-bug-tracker#3498]
**Please, provide a clear description what the bug is:**
Item Battered Viking Shield has Common quality type (white text color).

**IDs of affected creatures, items, quests or spells with a link to the relevant page:**
[Item: https://database.turtle-wow.org/?item=9403](https://database.turtle-wow.org/?item=9403)

**Expected behavior. Describe how it should work:**
Item should be Uncommon quality (green text color).

**Comment by balakethelock** [comment]
Not a bug, this is a cool quirk blizzard added. White item with stats can exist, because it is not freely tradeable and not bound-on-equip
