### ISSUE TITLE
Counterstrike in blood ring

### ISSUE THREAD

**Issue by geojak** [slowtorta/turtlewow-bug-tracker#3499]
**Please, provide a clear description what the bug is:**

Until recently all 30 minute and longer cd ability were disabled in blood ring. 
Recently this chnahed but undocumented. 

Warriors have shield wall, recklessness and counterstrike on 30cd. These were not usable in blood ring
Now you can use counterstrike but not the other teo. Additionally the CD does not reset so you still have to wait 30 minutes between games.  

**Expected behavior. Describe how it should work:**

IF think this is inconsistent. Why only one out of 3 warrior CDs. 
Either disable counterstrike again in blood ring or make all long cd abilities usable but not reset for all classes. 

That is shield wall, recklessness, lay on hands,battle rez, soulstone, ank. And more of other classes I don't remeber the CD of.

I think using those speels in one game every half an hour is fine. For lay on hands it woild be even once per hour. Jsut don't make the CD reset, that woild screw everything, then it's better to keep all disabled

**Comment by Muigin** [comment]
This behavior has been fixed in a previous update.
