### ISSUE TITLE
Some non-combat pets do not move after summoning them

### ISSUE THREAD

**Issue by blargsnarf** [slowtorta/turtlewow-bug-tracker#35]
By opening this Issue, I admit to having done the pertinent research using sources from Vanilla (preferably) or Classic. I also understand that sources from other private servers are not acceptable.

**Current behavior**: When summoned, both Lulu the sheep and the Prairie dog do not move, and stay where spawned.

**Expected behavior**: The pets should follow their owner like all other pets.

**Proofs**:

**Steps to reproduce**:

1. Acquire either [Lulu](https://database.turtle-wow.org/?item=51221) or a [Prairie Dog Whistle](https://database.turtle-wow.org/?item=10394)
2. Use the item
3. The pet will summon, but will not move as the owner moves.
[NOTE: This DID work as intended at one point, months ago. Then when I came back after the merge, these pets were broken.]

![prairiedog](https://user-images.githubusercontent.com/6321534/121796157-08c4da00-cbe5-11eb-81b7-cbe75ab93e23.png)

**Comment by slowtorta** [comment]
Thanks for reporting it. It's fixed and will be deployed on the next server update.
