### ISSUE TITLE
Object Audio Bug: Sound not playing

### ISSUE THREAD

**Issue by AyleeJenn** [slowtorta/turtlewow-bug-tracker#3504]
**Please, provide a clear description what the bug is:**
In the quest described there is a wooden chest that can be opened with a quest object key. The "spell" that is cast to open the chest does not display any sound.

**Steps to reproduce the behavior with as much detail as possible:**

1. Start the linked quest in Ashenvale
2. Acquire the wooden key from the treants
3. Open the quest chest and listen as no sound plays

**IDs of affected creatures, items, quests or spells with a link to the relevant page:**

Item: https://database.turtle-wow.org/?item=5475
Quest: https://database.turtle-wow.org/?quest=1026
Object: https://database.turtle-wow.org/?object=19022

**Expected behavior. Describe how it should work:**
A sound would be nice that indicates that a lock is being opened.

**Comment by slowtorta** [comment]
@ratkosrb It's a general problem - ompare this behavior with the chest of a similar model Trelane's Chest: 2716. It won't play opening sound if the Lock ID is assigned, so any GO that requires a key won't play its sounds. Could you please tell me if the same issue is present in vmangos?

**Comment by slowtorta** [comment]
Same issue: https://github.com/slowtorta/turtlewow-bug-tracker/issues/3506

**Comment by ratkosrb** [comment]
https://github.com/slowtorta/turtlewow-bug-tracker/assets/35845488/9bc49bf3-2ed1-452d-91c6-50bc98596183

**Comment by slowtorta** [comment]
Yup it's the same then, Unlocking spell doesn't trigger GO opening animation and sounds. If you open chest that doesn't require a  key, it'll behave differently.

**Comment by ratkosrb** [comment]
https://github.com/slowtorta/turtlewow-bug-tracker/assets/35845488/e1120fc1-ed83-42ee-bb66-2b7ddcdf1474

Behavior is the same with 1.14 client. I think it's always worked like that?

**Comment by slowtorta** [comment]
Not a bug then... We might improve this, if it's reasonable, otherwise it'll remain as it is.
