### ISSUE TITLE
Object Audio Bug: Velinde's Locker

### ISSUE THREAD

**Issue by AyleeJenn** [slowtorta/turtlewow-bug-tracker#3506]
**Please, provide a clear description what the bug is:**
When the player opens "Velinde's Locker" on the quest "Velinde's Effects" no sound plays while the locker is opened.

**Steps to reproduce the behavior with as much detail as possible:**

1. On the quest "Velinde's Effects" right click "Velinde's Locker" to open it with the quest key.
2.  Listen as no sound plays as the player performs that action
3. 

**IDs of affected creatures, items, quests or spells with a link to the relevant page:**

Object: https://database.turtle-wow.org/?object=19877

**Expected behavior. Describe how it should work:**
It would be nice if a sound played when the player opens the locker. A lock opening sound like when the player opens a bronze box you can find as loot. Or any lockpicking sound. I know it is not critical and really just polish but I feel it adds something. A level of immersion to the game.

**Comment by slowtorta** [comment]
Some of the audo-related bugs I closed require a client update, some do not and won't be fixed until 1.16.6 release. Please keep this in mind when you encounter the same behavior.

**Comment by AyleeJenn** [comment]
Mh, okay. Thank you the heads up :) May I ask which audio related bugs would you prefer me to report then? Just "Object" related bugs? (like quest lockers and such not making a sound when opening?)
So far I have just quickly written up everything I encountered when I encountered it. (so I won't forget later v.v)
But I will stop mentioning "item" related audio bugs (such as recipes, schematics, etc not making a sound when learning them) for now as you said they will be fixed in 1.16.6.

Usually, the way my team and I handle this is we gather what bug reports we find (as we play) and then I write up the ones we feel should be mentioned here on the bug tracker. I don't mean to flood though!

**Comment by AyleeJenn** [comment]
Alright, I understand. Thank you very much for all your time and all your hard work :)
