### ISSUE TITLE
Item Audio Bug: Recipe - Mithril Head Trout

### ISSUE THREAD

**Issue by AyleeJenn** [slowtorta/turtlewow-bug-tracker#3508]
**Please, provide a clear description what the bug is:**
When learning the recipe "Mithril Head Trout" no sound is playing.

**Steps to reproduce the behavior with as much detail as possible:**

1. Buy the recipe for "Mithril Head Trout" in Booty Bay and learn it
2. Listen as no sound plays when learning the recipe
3. 

**IDs of affected creatures, items, quests or spells with a link to the relevant page:**

Item: https://database.turtle-wow.org/?item=17062

**Expected behavior. Describe how it should work:**
A sound should be playing when learning the recipe. The default sound sounds like someone working with paper, I know it is not critical to game play but I am still listing it since Turtle WoW has always convinced with quality and excellence. :)

**Comment by slowtorta** [comment]
Thanks for reporting those. Any issues with sounds not playing when using patterns, plans, recipes, formulas, schematics will be fixed in patch 1.16.6. It's possible that some of the custom items are still overlooked.
