### ISSUE TITLE
Item Audio Bug: Black Swashbuckler's Shirt

### ISSUE THREAD

**Issue by AyleeJenn** [slowtorta/turtlewow-bug-tracker#3509]
**Please, provide a clear description what the bug is:**
The tailoring recipe for "Black Swashbuckler's Shirt" plays no sound when the player learns it.

**Steps to reproduce the behavior with as much detail as possible:**

1. Buy the recipe for "black Swashbuckler's Shirt" from the pirate supplies in booty bay
2. Listen as no sound plays when learning it
3. 

**IDs of affected creatures, items, quests or spells with a link to the relevant page:**

Item: https://database.turtle-wow.org/?item=10728

**Expected behavior. Describe how it should work:**
A sound should be playing when learning any recipe. Usually, in the standard client a sound plays that sounds like someone crumpling paper. I would love the sound effects being present again. ^.^

**Comment by slowtorta** [comment]
Do you have any proof that recipe/pattern learning sounds were present in Vanilla version of the game back in 2004? Because I cannot find any trace of this being a thing in the client. Not the sound itself, nor its reference in DBC.
