### ISSUE TITLE
Broken daily quests for Alliance

### ISSUE THREAD

**Issue by lurkvan** [slowtorta/turtlewow-bug-tracker#3510]
**Please, provide a clear description what the bug is:**
Completed daily quests is reset every day. Every morning I check /played and see that the meter has remained at the same value. It's like I didn't do the daily quests. This never happened before when I was doing Lorekeeper.

**Steps to reproduce the behavior with as much detail as possible:**

1. Just doing all 4 daily quests for the title Seeker of Knowledge every day (Lorekeeper already have)
2. Checking /played and make sure that the quest counter remains at the same value
3. 

**IDs of affected creatures, items, quests or spells with a link to the relevant page:**
Quests: 
A Crystal Clear Task - https://database.turtle-wow.org/?quest=80252
Relics in Feralas - https://database.turtle-wow.org/?quest=80253
Smashing Zul'Mashar - https://database.turtle-wow.org/?quest=80254
Tears of the Poppy - https://database.turtle-wow.org/?quest=80258

**Expected behavior. Describe how it should work:**
Daily quests should count towards the total number of quests

**Comment by slowtorta** [comment]
No, daily quests will not count towards the total number of quests. It's working as intended.
