### ISSUE TITLE
Drain Soul does not have a 100% chance to proc Soul Siphon, even when talented fully.

### ISSUE THREAD

**Issue by jmcf914** [slowtorta/turtlewow-bug-tracker#3513]
**Please, provide a clear description what the bug is:**  Drain Soul does not have a 100% chance to proc Soul Siphon, even when talented fully.

**Steps to reproduce the behavior with as much detail as possible:**

1. Cast drain soul on mobs that are about to be killed until soul siphon is not procced. 
2. 
3. 

**IDs of affected creatures, items, quests or spells with a link to the relevant page:**

NPC: https://database.turtle-wow.org/?npc=
Item: https://database.turtle-wow.org/?item=
Quest: https://database.turtle-wow.org/?quest=
Spell: https://database.turtle-wow.org/?spell=
Object: https://database.turtle-wow.org/?object=

**Expected behavior. Describe how it should work:**  

When talented fully, soul siphon should ALWAYS proc when a mob dies while under the effects of "drain soul"

**Comment by balakethelock** [comment]
Are you landing the killing blow, it doesn't proc if your pet kills the mob

**Comment by Gurky-Turtle** [comment]
What balakethelock said I have tested this and cannot reproduce this issue.
