### ISSUE TITLE
Blade of Eternal Darkness does not proc off of chanelled spell ticks.

### ISSUE THREAD

**Issue by ConcernedTurtler** [slowtorta/turtlewow-bug-tracker#3514]
**Please, provide a clear description what the bug is:**

When using mind flay the blade of eternal darkness will only proc off of the initial cast and not the following ticks. According to wowhead classic comments it has a chance to proc off of mind flay ticks:  https://www.wowhead.com/classic/item=17780/blade-of-eternal-darkness#comments

Other comments say it also works on arcane missiles, I can't test this as I am a priest but I'm assuming it wouldn't work with arcane missiles either.

https://database.turtle-wow.org/?item=17780

Thank you,

NPC: https://database.turtle-wow.org/?npc=
Item: https://database.turtle-wow.org/?item=
Quest: https://database.turtle-wow.org/?quest=
Spell: https://database.turtle-wow.org/?spell=
Object: https://database.turtle-wow.org/?object=

**Expected behavior. Describe how it should work:**

**Comment by balakethelock** [comment]
I don't see any comment claiming that, blizzlike behavior is: it procs on initial application of spells, and does not proc on dot ticks.
It procs on the use of mind flay that applies the aura on the enemy, never on the dots that follow it.

Arcane missiles is different, the aura you put on the enemy is not a dot but rather periodically triggers another spell on the target and THAT spell can proc the blade.
