### ISSUE TITLE
Character's not showing up on list after creating them

### ISSUE THREAD

**Issue by jkitty13** [slowtorta/turtlewow-bug-tracker#3516]
**Please, provide a clear description what the bug is:**

Upon creating a new character sometimes the new character does not show up on your character select list at all, the character clearly exists because when you view your character count for the server it includes the invisible character, you are also unable to create a new character with that name as it comes up as taken.

Logging in and out/fully closing the game and restarting etc, does not fix this issue.

A friend of mine even reported that even after an entire day, the character has yet to show up.

**Steps to reproduce the behavior with as much detail as possible:**

1. Create a new character

**Expected behavior. Describe how it should work:**

Character should show up on your list

**Comment by slowtorta** [comment]
We're aware of this issue, it will probably be fixed on the next update.
