### ISSUE TITLE
Elemental invasion bosses 

### ISSUE THREAD

**Issue by zealothim** [slowtorta/turtlewow-bug-tracker#352]
**Please, provide a clear description what the bug is:**
After killing Avalanchion you will have around 6 seconds to loot it or his body will disappear and you will lose all the loot.
**Steps to reproduce the behavior with as much detail as possible:**

1.
2. 
3. 

**IDs of affected creatures, items, quests or spells with a link to the relevant page:**

NPC: https://database.turtle-wow.org/?npc=14464
Item: https://database.turtle-wow.org/?item=
Quest: https://database.turtle-wow.org/?quest=
Spell: https://database.turtle-wow.org/?spell=
Object: https://database.turtle-wow.org/?object=

**Expected behavior. Describe how it should work:**
It shouldn't disappear that fast(?

**Comment by jameyboor** [comment]
Possible fix on PTR. Needs testing.
