### ISSUE TITLE
Suggestion: Challenge Mode "Attractive and Dangerous"

### ISSUE THREAD

**Issue by AyleeJenn** [slowtorta/turtlewow-bug-tracker#3521]
### This post is a suggestion for another challenge for players to enjoy at their own risk.

**_Challenge Name:_** "Attractive and Dangerous"

> **Attractive and Dangerous**
> 
> Effects: +100% Aggro Range
> 
> Description: You are attractive and dangerous, in other words a high priority target. Enemies will attack you from twice as far as normally.
> 
> Reward: Custom title "Highly Sought After" (rewarded for leveling from 1 - 60 with this challenge active)

**_Why this challenge?_**

1. Because it allows players to play with more dangerous enemies. Its for people who seek the challenge.
2. It adds reply value.
3. It lets you customize your leveling and gaming experience.

Its primarily meant as a means to customize your gaming experience with an added bonus of being a challenge when activated at level 1 and left active until level 60.

**_Implementation?_**
A passive ability in the general "spellbook" of the player if activated at level 1. Similar implementation to "Slow and Steady".
A second passive ability in the general "spellbook" of the player if activated after level 1. Activating this past level 1 won't yield a reward but allows existing characters to play with this challenge if they so desire.

**_Boundaries and Limitations?_**
Can be freely activated and deactivated at the master of glyphs at any level.

**_Reward mechanics?_**
Deactivating the challenge disqualifies player from the reward.
Custom title awarded upon reaching level 60 if challenge was activated at level 1 and never deactivated afterwards.

**_What about existing characters who want to enjoy this?_**
They can freely activate and deactivate it past level 1 but won't receive the custom title reward.

**Comment by AyleeJenn** [comment]
If this is not a good idea or we have enough challenges already or it is simply not feasible I am absolutely okay with that being so if that is the case. It was just an idea I had :)

**Comment by slowtorta** [comment]
I am sorry, but it seems like this could potentially disrupt the gameplay of other players. What if someone tags every mob within range just by standing AFK? In the future, please post any future suggestions on the forums. :)
