### ISSUE TITLE
Object Bug: Object Misplaced

### ISSUE THREAD

**Issue by AyleeJenn** [slowtorta/turtlewow-bug-tracker#3522]
**Please, provide a clear description what the bug is:**
As shown in the screenshot there is a misplaced decoration object outside of a building that probably belongs inside.

![visualerror1](https://github.com/slowtorta/turtlewow-bug-tracker/assets/87241085/b5812999-550a-4949-9baf-79c113fa0a1c)

**Steps to reproduce the behavior with as much detail as possible:**

1. Travel to Forest Song in Ashenvale (as Alliance)
2. Go just outside the building where Brolthan Ironglade is
3. Look for the misplaced object on the screenshot

**Comment by slowtorta** [comment]
Fixed in 1.16.6
