### ISSUE TITLE
Chromatic Dragons and Chromag have 100% holy resist all the time

### ISSUE THREAD

**Issue by ConcernedTurtler** [slowtorta/turtlewow-bug-tracker#3527]
**Please, provide a clear description what the bug is:**

The chromatic dragons and chromag are not supposed to be resistant to holy damage and they never have holy weakness.

This makes being a smite priest a waste of time in bwl. The only thing you can do is wand or use your much weaker shadow spells.  The mobs shouldn't be resistant to holy as it goes against the game's lore but if they have to be they should have a weakness phase like the other schools of magic.  This will make the encounter more fun and engaging anyway as holy priests and paladins will get a turn to dps.

https://database.turtle-wow.org/?npc=14020
https://database.turtle-wow.org/?npc=14302
https://database.turtle-wow.org/?npc=10814

**Comment by twowTurtReynolds** [comment]
This is a blizzard design, not a bug.
