### ISSUE TITLE
 Silithus Field Duty Quest Bug (Horde)

### ISSUE THREAD

**Issue by Boomdrawzz** [slowtorta/turtlewow-bug-tracker#3528]
The quest Field Duty in Silithus is bugged, making the quest way harder than it was intended. This quest is the initiation quest for being able to farm Cenarion Circle Badges, such as the Cenarion Circle Logistics Badge, right after it being done. First you have to talk to Krug Skullsplit then a big Hive creature called Hive'Regal Hunter-Killer will emerge. There is a major problem with this quest. This Hive creature is like a 20 man raidboss. Thats why there are elite grunts and axe-throwers in the back to aid Krug and the player(s) in this fight. The problem is that the npcs, meaning the grunts and axe-throwers do not help in the fight. Even when kiting the mob into them, when the mob does aoe they do not care. This makes the quest impossible to complete, preventing people from getting into the content of farming for Badges and earning rare and epic items from the Cenarion Circle. 

NPCs: https://database.turtle-wow.org/?npc=15612  , https://database.turtle-wow.org/?npc=15620 , https://database.turtle-wow.org/?npc=15613 , https://database.turtle-wow.org/?npc=15615 , https://database.turtle-wow.org/?npc=15617 , https://database.turtle-wow.org/?npc=15616
Quest: https://database.turtle-wow.org/?quest=8731

**Expected behavior. Describe how it should work: Usually you start the quest the same like on this server, by talking to Krug Skullsplit then the Hive'Regal Hunter-Killer will emerge. Exactly like on Turtle wow. After the Hive creature turns hostile not only Krug Skullsplit, but all Npcs near him should run right up to the Hive creature and attack it. This quest was intended to be done with 2-5 people, not a whole raid.**

**Comment by Gurky-Turtle** [comment]
https://github.com/slowtorta/turtlewow-bug-tracker/issues/2405

**Comment by Niqlo** [comment]
this shit is still cancer

**Comment by twowTurtReynolds** [comment]
Duplicate of https://github.com/slowtorta/turtlewow-bug-tracker/issues/2405
