### ISSUE TITLE
Killing Grundig Darkcloud doesn't result in quest completion

### ISSUE THREAD

**Issue by borg101** [slowtorta/turtlewow-bug-tracker#3533]
**Please, provide a clear description what the bug is:**

**Steps to reproduce the behavior with as much detail as possible:**

1. Kill Grundig Darkcloud (In Stonetalon)
2. Killing 6/6 grimtotem brutes works.  however killing Grundig Darkcloud, even multiple times...including looting the corpse, still leaves the quest 0/1.

**IDs of affected creatures, items, quests or spells with a link to the relevant page:**

NPC: https://www.wowhead.com/classic/npc=11858/grundig-darkcloud
Item: https://database.turtle-wow.org/?item=
Quest: https://www.wowhead.com/classic/quest=6629/kill-grundig-darkcloud
Spell: https://database.turtle-wow.org/?spell=
Object: https://database.turtle-wow.org/?object=

**Expected behavior. Describe how it should work:**

**Comment by slowtorta** [comment]
This is working as intended. Please delete your in-game cache (WDB folder) and try again.
