### ISSUE TITLE
Honoring a Hero is bugged.

### ISSUE THREAD

**Issue by Fin9622** [slowtorta/turtlewow-bug-tracker#354]
Honoring a Hero is bugged.

How it should work:
 You go to Uther Tombs  at Uther's statue in Western Plaguelands and you use Uther's Tribute and you place an tribute
 You go to  Grom's Monument in the Demon Fall Canyon of Ashenvale  and you use Grom's Tribute and you place an tribute
 
 
What does not work : 
When you are at Uther's statue and you use Uther's Tribute you get the message "Requires Uther's Tombs Statue while the character attempt to do a animation 
When you are at Grom's Monument and you use Grom's Tribute  you get the message "Requires Grom's Monument"while the character attempt to do a animation 

https://database.turtle-wow.org/?quest=8149 Honoring a Hero(Alliance)
https://database.turtle-wow.org/?item=19850 Uther's Tribute
https://database.turtle-wow.org/?object=182483 Uther Shrine Lightbeam  - for Monument's location, i can't target the monument
https://database.turtle-wow.org/?object=180214 Uther's Dwarf Tribute
https://database.turtle-wow.org/?object=180210 Uther's Human Tribute

https://database.turtle-wow.org/?quest=8150 Honoring a Hero(Horde)
https://database.turtle-wow.org/?item=19851 Grom's Tribute 
https://database.turtle-wow.org/?object=21004  Grom's Monument
https://database.turtle-wow.org/?object=180207 Grom's Orc Tribute
https://database.turtle-wow.org/?object=180209 Grom's Tauren Tribute

![WoW_EtPevJjFfy](https://user-images.githubusercontent.com/83077166/135722296-463f887d-809e-43a7-a956-4d6c42e6f285.png)

![image](https://user-images.githubusercontent.com/83077166/135741515-43ec8084-b21b-4772-b8f5-7134e70af9e2.png)

**Comment by slowtorta** [comment]
Have you tried it during the Harvest Festivafle? Because this quest is active only during this event.

**Comment by slowtorta** [comment]
Fixed on the next update ! 
![image](https://user-images.githubusercontent.com/66763404/153781268-2c30b12f-8a5e-4062-89df-97f354e38fb1.png)

**Comment by slowtorta** [comment]
https://github.com/slowtorta/turtlewow-bug-tracker/issues/2233
