### ISSUE TITLE
Durotar Labor Union Reputation not Shown in Reputation Tab

### ISSUE THREAD

**Issue by JanQuGit** [slowtorta/turtlewow-bug-tracker#3541]
**Please, provide a clear description what the bug is:**

Durotar Labor Union Reputation not Shown in Reputation Tab. I'm certain that I have activated this faction on my character, as I have done some quests for them, and got the reputation gain messages.

It shows properly on other characters.

I have tried clear WDB & disable all addons & relogging & restart client.

**Steps to reproduce the behavior with as much detail as possible:**

1. Only this one character has this issue. I don't know how to reproduce it on other characters.
2. To reproduce, just log in my character and the issue remains.

**IDs of affected creatures, items, quests or spells with a link to the relevant page:**

Didn't find ID for the faction in database.

**Expected behavior. Describe how it should work:**

Reputation shown properly in reputation tab, under Horde category.

**Comment by JoLiKMC** [comment]
This seems to exclusive affect **new Orc and Unread characters**.  Tauren, Trolls, and bizarrely, even new Goblins who shouldn't *know* about the Durotar Labor Union – because it doesn't yet *exist* – have the faction on their reputation list.

Not all Goblins are part of the DLU.  The one outside of the canyon in Durotar is part of Ratchet, for example.  Not sure about the ones in Orgrimmar.  In any case, just head over to Sparkwater Port in Durotar and give any Goblin NPC a left-click.  That should add the faction to your list.

**Comment by JanQuGit** [comment]
> This seems to exclusive affect **new Orc and Unread characters**. Tauren, Trolls, and bizarrely, even new Goblins who shouldn't _know_ about the Durotar Labor Union – because it doesn't yet _exist_ – have the faction on their reputation list.
> 
> Not all Goblins are part of the DLU. The one outside of the canyon in Durotar is part of Ratchet, for example. Not sure about the ones in Orgrimmar. In any case, just head over to Sparkwater Port in Durotar and give any Goblin NPC a left-click. That should add the faction to your list.

Sadly this is a bug affecting my Orc character. I have done several quests from Sparkwater Port and got the reputation increase messages such as "Your Durotar Labor Union reputation has increased by 100" many times.

I submitted a ticket in game before posting here. And the gm told me to report bug in this thread.

**Comment by Avery1337** [comment]
This is still not working for me as of today 7/10/23.  It hasn't been working for Orcs since the Durotar Labor Union came out...

**Comment by slowtorta** [comment]
This will be fixed in the next CLIENT patch.
