### ISSUE TITLE
Orcs and Undead Can Go "At War" With Durotar Labor Union

### ISSUE THREAD

**Issue by JoLiKMC** [slowtorta/turtlewow-bug-tracker#3543]
**Please, provide a clear description what the bug is:**
Orcs and Undead characters can choose to be "At War" with the Horde Goblin faction, the Durotar Labor Union.

**Steps to reproduce the behavior with as much detail as possible:**
1. Create a new Orc or Undead character.
2. Head over to Sparkwater Port. <sup>(It's Southeast of Orgrimmar.)</sup>
3. Left-click on any "Durotar Labor Union" NPC.  This should add their reputation to your list.
4. Open your Reputation list.  Click on "Durotar Labor Union".  The option to go "At War" should be available.

**Expected behavior. Describe how it should work:**
Players should not be able to go At War with sub-factions of their own side.

**Further details:**
Very sad to report this one <sub>(because it's *hilarious*)</sub>, but it's what must be done – especially after someone reported the missing faction bug.  

<sup>A similar thing had happened with a Tauren NPC who was just part of the "Horde Forces" sub-faction, but it was fixed a while ago.  ):</sup>

**Related bugs:**
* #3541

**Comment by twowTurtReynolds** [comment]
![image](https://github.com/slowtorta/turtlewow-bug-tracker/assets/151180101/00594c5f-b68d-4158-a8aa-de16ad76865d)
Looks like this was fixed for new characters, and old characters would have been batch fixed at the time.
