### ISSUE TITLE
Quest "The Missing Diplomat" flags for PvP indirectly

### ISSUE THREAD

**Issue by zeress** [slowtorta/turtlewow-bug-tracker#3545]
**Please, provide a clear description what the bug is:**
The quest "The Missing Diplomat" automatically activates PvP mode due to the NPCs involved being flagged for PvP. Despite being located in Old Town of Stormwind, this quest lacks clear indications of its PvP nature. Performing the quest as intended will inevitably lead to the activation of PvP mode, as all three attacking NPCs are flagged.

**Steps to reproduce the behavior with as much detail as possible:**

1. Accept the quest
2. Note that the NPCs attack you as appropriate
3. Note that fighting back, required to complete the quest, will promptly flag you for pvp

**IDs of affected creatures, items, quests or spells with a link to the relevant page:**

NPCs: https://database.turtle-wow.org/?npc=4961, https://database.turtle-wow.org/?npc=1395, https://database.turtle-wow.org/?npc=2795
Quest: https://database.turtle-wow.org/?quest=1447

**Expected behavior. Describe how it should work:**
The 3 NPCs involved should not be flagged for PvP, and thus should not result in you becoming flagged for PvP

**Comment by Gurky-Turtle** [comment]
https://youtu.be/1nlDIXYygio?t=330
he is a pvp flagged mod who is aggressive which when you fight back you will be flagged for pvp this is intended. 
![image](https://github.com/slowtorta/turtlewow-bug-tracker/assets/90982783/14d154c7-b1bb-44fd-bd48-7969e123ee2a)
