### ISSUE TITLE
The Missing Diplomat quest NPC tagging you for PVP

### ISSUE THREAD

**Issue by Dualityz** [slowtorta/turtlewow-bug-tracker#3546]
Dashel Stonefist, the you have to beat up for the quest "The Missing Diplomat" in Stormwind along with his two Old Town Thugs pals, tags you pvp as soon as you damage him. 

**Steps to reproduce the behavior with as much detail as possible:**

1. Try the quest yourself, it happend litterally every single time I did it. 
2. 
3. 

**IDs of affected creatures, items, quests or spells with a link to the relevant page:**

NPC: https://database.turtle-wow.org/?npc=4961
Quest: https://database.turtle-wow.org/?quest=1447

**Expected behavior. Describe how it should work:**

When you turn in the previous quest 
( https://database.turtle-wow.org/?quest=1246 )
He instantly turns red and spawns two Old Town Thugs, as expected. He does not lose his pvp tag though I beleive, so that might be the problem ? You activate pvp by damageing him in any way possible.

**Comment by zeress** [comment]
same as #3545
