### ISSUE TITLE
High Elf female character is not seated in the center of a mount saddle

### ISSUE THREAD

**Issue by Avarajihari** [slowtorta/turtlewow-bug-tracker#355]
**Please, provide a clear description what the bug is:**
This might be a nitpick but it's driving me crazy: there is a small offset when it comes to the center of my character when she's mounted. This means that she's not sitting in the "middle" of a saddle but instead a bit to the side. It's just a visual "bug" and it does not affect gameplay at all. I only tested the riding turtle and the 10g unicorn.

**Steps to reproduce the behavior with as much detail as possible:**

1. Have a high elf female character.
2. Mount up on any mount. I think it's especially noticeable on a 10g unicorn.

**IDs of affected creatures, items, quests or spells with a link to the relevant page:**

Unicorn: https://database.turtle-wow.org/?item=80459

**Expected behavior. Describe how it should work:**
I expect my character to be saddled in the middle of the saddle without any offset.

**Comment by slowtorta** [comment]
Included in https://github.com/slowtorta/turtlewow-bug-tracker/issues/449
