### ISSUE TITLE
Wrapped Gifts displaying item suffix in trade window

### ISSUE THREAD

**Issue by syrathegreat** [slowtorta/turtlewow-bug-tracker#3550]
**Please, provide a clear description what the bug is:**
I got my friend a present of [War Knife of Shadow Wrath] and wrapped it in [Blue Ribboned Wrapping Paper] as a surprise. However when I went to trade it to them, instead of appearing as [Blue Ribboned Gift] in the trade window, it instead appeared as [Wrapped Gift of Shadow Wrath] despite the tooltip still showing correctly, which completely gave away the surprise. 

**Steps to reproduce the behavior with as much detail as possible:**

1. Wrap a BoE item with a suffix in wrapping paper
2. Place it in the trade window with another player

**IDs of affected creatures, items, quests or spells with a link to the relevant page:**

https://database.turtle-wow.org/?item=4571
https://database.turtle-wow.org/?item=5048
https://database.turtle-wow.org/?item=5044

**Expected behavior. Describe how it should work:**

Item should appear in the trade window as [Blue Ribboned Gift]

**Comment by Gurky-Turtle** [comment]
![image](https://github.com/slowtorta/turtlewow-bug-tracker/assets/90982783/2f7c1078-61b3-4b72-b253-a4283a81911d)
![image](https://github.com/slowtorta/turtlewow-bug-tracker/assets/90982783/8134fe21-8c00-4948-b490-01a88f31a39f)
can't reproduce it works fine with the exact items you gave me.
