### ISSUE TITLE
60 Hardcore cannot receive gold or items in mail, have deleted wdb folder numerous times.

### ISSUE THREAD

**Issue by Ubbernoobie** [slowtorta/turtlewow-bug-tracker#3553]
**Please, provide a clear description what the bug is:**

**Steps to reproduce the behavior with as much detail as possible:**

1.trying to mail gold or items from alt lvl 1 to my 60 HC character get message HC characters cannot receive gold or mail with attachments
2. trying to mail gold or items from lvl 60 mage to HC lvl 60 warrior get message HC characters cannot receive gold or mail with attachments
3. 

**IDs of affected creatures, items, quests or spells with a link to the relevant page:**

NPC: https://database.turtle-wow.org/?npc=
Item: https://database.turtle-wow.org/?item=
Quest: https://database.turtle-wow.org/?quest=
Spell: https://database.turtle-wow.org/?spell=
Object: https://database.turtle-wow.org/?object=

**Expected behavior. Describe how it should work:**

**Comment by twowTurtReynolds** [comment]
Please contact a GM.
