### ISSUE TITLE
Warlocks Stuck in PvP due to bug with summoned pet.

### ISSUE THREAD

**Issue by Homemadecherrypie** [slowtorta/turtlewow-bug-tracker#3555]
**Please, provide a clear description what the bug is:**
When a warlock with a succubus pet exits a BG, they remain flagged until the pet is put away.
**Steps to reproduce the behavior with as much detail as possible:**

1. Be a warlock
2.  Do a battleground with succubus pet
3.  Exit battleground

**IDs of affected creatures, items, quests or spells with a link to the relevant page:**
 N/A

**Expected behavior. Describe how it should work:**
Pvp flag should drop after 5 minutes regardless of summoned pets. 
I am a GM (Hi guys!) and have personally seen this happen to a specific warlock for weeks now. I've even dealt with the ticket about it. After being stumped I forwarded the issue to Jamey who suspected it was the pet that was the issue. We have tested this multiple times now and it has been proven correct. We need to make it so warlock pets don't keep renewing PvP timers. Thank you.

**Comment by twowTurtReynolds** [comment]
![image](https://github.com/slowtorta/turtlewow-bug-tracker/assets/151180101/92e73cd1-84bb-4da5-a755-4189f5b07fe4)
![image](https://github.com/slowtorta/turtlewow-bug-tracker/assets/151180101/5f047ce4-a0c9-4b1b-b850-e5f81c9a1954)

Seems fine.
