### ISSUE TITLE
PERMAFROST TALENT BUG i CANT play!

### ISSUE THREAD

**Issue by Qnimage** [slowtorta/turtlewow-bug-tracker#3556]
**Please, provide a clear description what the bug is:**
Permafrost talent doesn't work on my mage. The description of the ability looks correct, but the effect of Permafrost does not work (instead of 50% slow, 40% is applied, the duration of the slow is also not increased).

Previously, I played a magician with the same name, but after his death I created this one (I don’t know if this helps). On that mage, this talent worked correctly. Resetting talents and restarting the game did not solve the problem.

**Steps to reproduce the behavior with as much detail as possible:**

1. create a mage
2. Level up to get this talent
3. Watching
I am more than sure that it is difficult to reproduce it. I can show it in the game at any time my nickname is Qni - just write and I will demonstrate.
GM - wont help me with this or smply look at.

**IDs of affected creatures, items, quests or spells with a link to the relevant page:**
https://www.wowhead.com/classic/spell=12571/permafrost

idk https://database.turtle-wow.org/?spell=12571

**Expected behavior. Describe how it should work:**
It should work as described!! What should I do?

https://github.com/slowtorta/turtlewow-bug-tracker/assets/134722753/81971caf-a345-4086-8752-77e84c9b802d

https://github.com/slowtorta/turtlewow-bug-tracker/assets/134722753/32eb9ce8-905c-4192-9061-232ccfed5424

**Comment by Qnimage** [comment]
its not a 50% slow. its 40$ slow.
Go online as ure mage and lets test it.

**Comment by Qnimage** [comment]
> It works. It increased timer (as you see, with talent it go from 5 sec to 8 second for frost bolt rank 1) and it also increases slow but that doesn't show on debuff but it works! this is a thing about vanilla wow and not a bug.
its not a 50% slow. its 40% slow.
Go online as ure mage and lets test it.

**Comment by balakethelock** [comment]
> Go online as ure mage and lets test it.

I don't have a mage in turtle wow but I assure you it works. There is nothing to test except this: use frostbolt without talent and look how slow mob is moving
put points in the talent then try frostbolt again. Even if debuff says 40%, you will see mob move much slower now

**Comment by Qnimage** [comment]
Its 5g cost. u think its only a ui bug?

**Comment by balakethelock** [comment]
> Its 5g cost. u think its only a ui bug?

yes. only UI bug

**Comment by Qnimage** [comment]
so still a bug

**Comment by Muigin** [comment]
Tooltips on enemy targets or in your buffs do not reflect talent improvements in vanilla. The updated values will only reflect accurately in your spellbook.
