### ISSUE TITLE
% haste enchants, buffs and etc. reduce proc rate of PPM weapons and items

### ISSUE THREAD

**Issue by ReggyDawn** [slowtorta/turtlewow-bug-tracker#3557]
**Please, provide a clear description what the bug is:** In regular vanilla mechanics, haste is not something that effects the base weapon speed, but rather a modifier in the same way 10% dmg bonus would be a modifier to your weapon damage. Because of this, when a proc per minute weapon calculates it's proc rate, it only consults the base attack speed of the weapon, and not the modified attack speed. This can increase the uptime of effects like crusader and etc.

However here, your proc rate and uptime on items such as, for example, untamed blade actually DROPS by increasing your haste. And this change happened at some point in the past, but after the recent wave of class changes. I believe it was around the moment when paladins Seal of the Crusader recieved a method of utilizing weapon procs in the way that it does. This can be observed simply by looking at my own logs from before this change and after this change, as the total uptime of Untamed Blade was DRASTICALLY different.

**Steps to reproduce the behavior with as much detail as possible:**
A good way to confirm this
1. Go to a dummy, use haste related gear, get a shaman friend and use Seal of Righteousness for good measure, as all of these effects are independant of your auto-attack speed, but are subject to the same proc rate.
2. Test for 10 minutes at the dummy with haste modifiers and without them.
3.  Observe total uptime of the buff in a details addon.

**IDs of affected creatures, items, quests or spells with a link to the relevant page:**

All PPM items.

**Expected behavior. Describe how it should work:**

The way it should work is that a PPM effect would have a fixed proc rate based on the unmodified weapon speed of the weapon. The only exception being Manual Crowd Pummeler, as it directly effects base weapon speed and doesn't behave like haste normally behaves.

**Comment by twowTurtReynolds** [comment]
I have added .aura 18065, the +10% haste buff 34 times. UTB on my character has gone from 3.4s to 0.13s

![image](https://github.com/slowtorta/turtlewow-bug-tracker/assets/151180101/dd6f93b1-9178-465b-a9d0-481ac26a9cbc)

I had to repeatedly spam right click my buff area to keep the buff from immediately refreshing and not generating a combat log entry.

It looks to not be a problem with melee weapons and procs.
