### ISSUE TITLE
Bonfire in Dun Agrath unusable

### ISSUE THREAD

**Issue by zeress** [slowtorta/turtlewow-bug-tracker#3558]
**Please, provide a clear description what the bug is:**
The bonfire in Dun Agrath is purely visual. It neither does damage when you are too close, nor allows cooking.

**Steps to reproduce the behavior with as much detail as possible:**

1. Stand on top of fire
2. Note no ticking damage
3. Try to cook
4. Note "Requires Cooking Fire" error

**IDs of affected creatures, items, quests or spells with a link to the relevant page:**

Coordinates: Wetlands - 23.8 66.9

**Expected behavior. Describe how it should work:**
The fire should hurt and allow cooking

**Comment by Gurky-Turtle** [comment]
it looks like this is due to the fire not being a game object and is terrain instead. There isnt a way to make this fire cookable.
