### ISSUE TITLE
Basic unicorn sounds like a tiger when mounted

### ISSUE THREAD

**Issue by Avarajihari** [slowtorta/turtlewow-bug-tracker#356]
**Please, provide a clear description what the bug is:**
When a character mounts up, the mount plays a sound. For the 10g unicorn (high elf racial mount) this sound is a tiger roar.

**Steps to reproduce the behavior with as much detail as possible:**

1. Have the 10g Thalassian unicorn.
2. Mount up and listen to the sound it makes.

**IDs of affected creatures, items, quests or spells with a link to the relevant page:**

Unicorn: https://database.turtle-wow.org/?item=80459

**Expected behavior. Describe how it should work:**
I expect the unicorn to NOT sound like a tiger. If there are no unicorn sounds available, I think a horse (human mount) sound would be more fitting.

**Comment by slowtorta** [comment]
Included in https://github.com/slowtorta/turtlewow-bug-tracker/issues/449
