### ISSUE TITLE
[Ironforge Chain] unable to disenchant

### ISSUE THREAD

**Issue by syrathegreat** [slowtorta/turtlewow-bug-tracker#3560]
**Please, provide a clear description what the bug is:**
[Ironforge Chain] cannot be disenchanted, despite it being an Uncommon (Green) item. This was noted on an item that was soulbound to the enchanter themselves. This was still replicated after clearing WDB folder. Perhaps item does not have a disenchanting table?

**Steps to reproduce the behavior with as much detail as possible:**

1. Craft [Ironforge Chain] Mail Chest item.
2. Attempt to disenchant said item.
3. Equip [Ironforge Chain] to soulbind it.
4.  Attempt to disenchant said item.
5. In either case, should get a warning "Item cannot be disenchanted"

**IDs of affected creatures, items, quests or spells with a link to the relevant page:**

https://database.turtle-wow.org/?item=6730
https://database.turtle-wow.org/?spell=13262

**Expected behavior. Describe how it should work:**

Item should be disenchanted successfully like all other Uncommon (Green) items.

**Comment by AyleeJenn** [comment]
I have encountered that with a number of custom items specific to turtle WoW, this error is, indeed, generally caused by a missing disenchant ID (what you called "disenchanting table") on the item as far as I understand the system.
