### ISSUE TITLE
Talents not working properly (Hunter)

### ISSUE THREAD

**Issue by SuurRuhtinas** [slowtorta/turtlewow-bug-tracker#3565]
**Please, provide a clear description what the bug is:**
Hunter's Mark doesn't seem to be affected by the Hunter's mark talent points increase. On toolbar and on the icon in your spell book it says the correct amount of Ranged AP added (86 at rank 3 and 5 talent points). But when casted on enemy target it says shows that Hunter's mark only gives 75 Ranged AP, which is the normal amount, if you didn't have talent points spent on improving your hunter's mark.  Its seems that this bug might affect Serpent Sting talent as well.

**Steps to reproduce the behavior with as much detail as possible:**

1. Add hunter's Mark talent points
2.  (Add Serpent Sting talent points)
3. 

**IDs of affected creatures, items, quests or spells with a link to the relevant page:**

Spell: https://database.turtle-wow.org/?spell=14324
Spell: https://database.turtle-wow.org/?spell=5298
Spell: https://database.turtle-wow.org/?spell=1130

(Most likely as well all Serpent Stings) Spell: https://database.turtle-wow.org/?spell=1978

**Expected behavior. Describe how it should work:**
Hunter's Mark should affect the enemy with the Ranged AP it tells you, not the basic 75 Ranged AP. Similarly Serpents Sting doesn't seem to have damage increase even if you spend talent points to it.

**Comment by Muigin** [comment]
Tooltips on enemy targets or in your buffs do not reflect talent improvements in vanilla.  The updated values will only reflect accurately in your spellbook.
