### ISSUE TITLE
Paladin Ret aura rank 3

### ISSUE THREAD

**Issue by Joao-Paulo-Macauba-da-Costa** [slowtorta/turtlewow-bug-tracker#3566]
**Please, provide a clear description what the bug is:**

Im lvling a Ret paladin and just got my retribution aura rank 3. It should do 18 dmg + 50% since i have the talent. The spell tooltip say 18 dmg, but the active buff tooltip says 12 dmg(rank 2).

When i did the test in a combat It was doing 18 dmg (rank 2 +50%), but should be doing 27(rank 3+50%) dmg.

**Steps to reproduce the behavior with as much detail as possible:**

1.Get the Ret aura talent for 50% more dmg
2. Get Ret aura rank 3 from a trainer
3. Check the tooltip from the spell and from the active buff
4. Get hit by a mob and see the result

**IDs of affected creatures, items, quests or spells with a link to the relevant page:**

**Expected behavior. Describe how it should work:**

Retribution aura rank 3 should do 18 dmg and with the talent It should do 27 dmg.

**Comment by bugzy411** [comment]
You need to recast ret aura to get the new rank active. This isn't a bug. This is just incompetence.

**Comment by Joao-Paulo-Macauba-da-Costa** [comment]
> You need to recast ret aura to get the new rank active. This isn't a bug. This is just incompetence.

Oh yeah, i tried what ur saying "kind" sir, and isnt working :)

**Comment by twowTurtReynolds** [comment]
![image](https://github.com/slowtorta/turtlewow-bug-tracker/assets/151180101/d906e344-6b2c-40a8-a8f5-8c3351ae72ee)
I can confirm that @bugzy411 is correct.
