### ISSUE TITLE
[Netherwind Bindings] not in drop list (i think)

### ISSUE THREAD

**Issue by firstimewow** [slowtorta/turtlewow-bug-tracker#3567]
[Netherwind Bindings] not in drop list atm (i think)

NPC: https://database.turtle-wow.org/?npc=12435
Item: https://database.turtle-wow.org/?item=16918

8-9 kills - 0 drop, its insane, other pieces of this set drop is ok
im raiding two month bwl, got 7/8 t2 set, but this wrist.....
im horde btw,  master looter is alliance

**Comment by fatnerdynerd** [comment]
honestly an embarassment you even had the courage to write this

devs nuke this guy's post

**Comment by afizzler** [comment]
haha

**Comment by Zebouski** [comment]
Welcome to RNG. Things are not guaranteed to drop. While unlikely, It is possible for you to go years with a piece never dropping.

The DB has accurate loot drop percentages and has 2x chances for 11% chance drop. You will get it

**Comment by Dragunovi** [comment]
Doesn't seem to be an actual issue, closing.
