### ISSUE TITLE
lvl 60 qeust reward ring not bop and no lvl restriction

### ISSUE THREAD

**Issue by geojak** [slowtorta/turtlewow-bug-tracker#3568]
**Please, provide a clear description what the bug is:**

1. get this ring rom khara qeust https://database.turtle-wow.org/?item=60465
2. its not bop and has no lvl requirement
3. Put it on ah
4. buy it with a lvl 1 character
5. now zou got a lvl 60 blue ring with 15 strengh and 20 arcane rsistance at lvl 1

**Expected behavior. Describe how it should work:**

qeust rewards should be soulbound

**Comment by ConcernedTurtler** [comment]
i'd rather have stamina
