### ISSUE TITLE
Tailoring, learning new recipes from Timothy Woringhton

### ISSUE THREAD

**Issue by madziom** [slowtorta/turtlewow-bug-tracker#3569]
**Please, provide a clear description what the bug is:** Cant learn from artistian talioring teacher

**Steps to reproduce the behavior with as much detail as possible:**

1. had same problem some time ago, seem to work for a sec and now again I cant learn new recipes from tailoring teacher. Reached 231skill and cant learn anything form this guy mentioned above. I click on "learn" and nothing happens. I posted same problem before, this worked so i could learn artistian tailoring and some recipes... but now again it doesnt work.
2. 
3. 

**IDs of affected creatures, items, quests or spells with a link to the relevant page:**

NPC: https://database.turtle-wow.org/?npc=11052

**Expected behavior. Describe how it should work:** I should be able to learn from him every recipe

**Comment by Gurky-Turtle** [comment]
Cannot reproduce, sounds like a wdb issue or an addon issue.

**Comment by parsn** [comment]
I had the same problem. 
I tried to delete the wtb folder (with the client closed)
My way around this: Copy the client to a new place, delete WDB-folder and everything in WTF\Accounts (leaving the config.wtf) 
So I guess it is addon related.
