### ISSUE TITLE
Zamek's Distraction event does not work

### ISSUE THREAD

**Issue by Tinyfin-github** [slowtorta/turtlewow-bug-tracker#357]
Zamek's Distraction event does not work

How it should work:  To complete the quest Keeping Pace you need to Start and finish the quest Zamek's Distraction to enable Rizzle's Schematics
Keeping pace Requires you to steal some plans by  starting the quest  Zamek's Distraction , in which Zamek  will place a bomb so you can steal Rizzle's Schematics and start the quest Rizzle's Schematics.

What does not work: Zamek does not place the bomb. While walking to the bomb location he just turns back.

https://database.turtle-wow.org/?quest=1190 Keeping Pace
https://database.turtle-wow.org/?quest=1191 Zamek's Distraction
https://database.turtle-wow.org/?quest=1194 Rizzle's Schematics
https://database.turtle-wow.org/?npc=4709 Zamek
https://database.turtle-wow.org/?object=20805 Rizzle's Unguarded Plans

**Comment by slowtorta** [comment]
Fixed on the next update!
