### ISSUE TITLE
Sunnyglade valley

### ISSUE THREAD

**Issue by xoro189** [slowtorta/turtlewow-bug-tracker#3570]
**Please, provide a clear description what the bug is:**
By giving 20 Flickering Time Spark to the elf who is in the middle having the tower, it fulfills its function but when you talk to him again he does not give any option even if you have Flickering Time Spark x50. another person with Flickering Time Spark x20 tried it and he didn't give him the option either

**Steps to reproduce the behavior with as much detail as possible:**

1.I hand over 20 Flickering Time Spark. Good
[![sv2.png](https://i.postimg.cc/prGx2gRq/sv2.png)](https://postimg.cc/y3Z2jpJZ)
2. I try to deliver 50 and the npc does not give an option
[![sv1.png](https://i.postimg.cc/TwK6YtN9/sv1.png)](https://postimg.cc/sQC8T4rQ)
3. another player tries to deliver 20 and does not give him an option

**IDs of affected creatures, items, quests or spells with a link to the relevant page:**

NPC: https://database.turtle-wow.org/?npc=13760
Item: https://database.turtle-wow.org/?item=81390

**Expected behavior. Describe how it should work:**
I don't know how this bg works but I think this is a bug

**Comment by twowTurtReynolds** [comment]
![image](https://github.com/slowtorta/turtlewow-bug-tracker/assets/151180101/cea7f56a-baf8-4e8f-b002-e962fedc6c0c)
It seems about 10 seconds after the announcement of the final battle goes out, the options close. I suppose the text could be ammended to tell players sparks beyond this point do not matter.

Closing as working fine.
