### ISSUE TITLE
Memory could not be read

### ISSUE THREAD

**Issue by lomja** [slowtorta/turtlewow-bug-tracker#3571]
**Please, provide a clear description what the bug is:**

**Steps to reproduce the behavior with as much detail as possible:**

1.
2. 
![vvvx](https://github.com/slowtorta/turtlewow-bug-tracker/assets/134825698/64417ee4-8c26-4a33-ae31-f9d34f2e907d)

3. 

**IDs of affected creatures, items, quests or spells with a link to the relevant page:**

NPC: https://database.turtle-wow.org/?npc=
Item: https://database.turtle-wow.org/?item=
Quest: https://database.turtle-wow.org/?quest=
Spell: https://database.turtle-wow.org/?spell=
Object: https://database.turtle-wow.org/?object=

**Expected behavior. Describe how it should work:**

**Comment by slowtorta** [comment]
Please re-download our client from the website and do not apply any modifications!
