### ISSUE TITLE
Warsong Gulch Warrior Charge

### ISSUE THREAD

**Issue by Blank3ts** [slowtorta/turtlewow-bug-tracker#3572]
**Please, provide a clear description what the bug is:**
Warriors essentially may target an enemy player that is in the tunnel of horde / ally base, and can charge too him if they stand directly above the tunnel, near the entrances to the horde / alliance base that are by the graveyard.
**Steps to reproduce the behavior with as much detail as possible:**

1. Find enemy player in tunnel
2. Position yourself as close to the enemy player you want to charge as possible thru the terrain / walls.
3. Charge enemy player from either directly above the tunnel (so either between ramp and graveyard right at top entrance of base, or can also be done from inside base I believe)
4. It will rapidly zoom the player thru the quickest possible path, which is normally thru the base, into the flagroom, and down into the tunnel.

**IDs of affected creatures, items, quests or spells with a link to the relevant page:**

NPC: https://database.turtle-wow.org/?npc=
Item: https://database.turtle-wow.org/?item=
Quest: https://database.turtle-wow.org/?quest=
Spell: https://database.turtle-wow.org/?spell=
Object: https://database.turtle-wow.org/?object=

**Expected behavior. Describe how it should work:**
Shouldn't be able to charge when there is no LOS.

**Comment by Muigin** [comment]
Cannot reproduce on current version.
