### ISSUE TITLE
Opposite faction can see Local Defense channel

### ISSUE THREAD

**Issue by Blank3ts** [slowtorta/turtlewow-bug-tracker#3573]
**Please, provide a clear description what the bug is:**
Was just in The Barrens and I noticed a human warlock was able to speak to me through the local defense channel and see my text. I don't think this is how its supposed to work, and even though there is cross-faction, it can be difficult trying to communicate with only horde players if alliance players can see what we're saying in the defense channel.
**Steps to reproduce the behavior with as much detail as possible:**

1. Go to the Barrens
2. Speak in Local Defense
3. Have opposite faction speak back

**IDs of affected creatures, items, quests or spells with a link to the relevant page:**

NPC: https://database.turtle-wow.org/?npc=
Item: https://database.turtle-wow.org/?item=
Quest: https://database.turtle-wow.org/?quest=
Spell: https://database.turtle-wow.org/?spell=
Object: https://database.turtle-wow.org/?object=

**Expected behavior. Describe how it should work:**

**Comment by Blank3ts** [comment]
Am I mistaken maybe? Is this how its supposed to work?

**Comment by balakethelock** [comment]
> Am I mistaken maybe? Is this how its supposed to work?

He fixed it and closed the ticket. You can see that it's fixed here https://forum.turtle-wow.org/viewtopic.php?f=63&t=7524&sid=994688fe1294e3f527cb282d34d75a1e&p=48266#p48266
