### ISSUE TITLE
Darkmoon Card: Maelstrom do not proc on the druids, or do not proc at all, don't know

### ISSUE THREAD

**Issue by Talasym** [slowtorta/turtlewow-bug-tracker#3574]
**Please, provide a clear description what the bug is:**

**Steps to reproduce the behavior with as much detail as possible:**

1. I checked around 200 attacks in cat form and zero procs
2. Checked also 200 attacks in normal form zero procs
3. 

**IDs of affected creatures, items, quests or spells with a link to the relevant page:**
https://database.turtle-wow.org/?item=19289

**Expected behavior. Describe how it should work:**
I have played so many years and i know how this trinket proc, and definitely work in any druid form.

**Comment by ratkosrb** [comment]
Cannot reproduce the issue. It procced for me in cat form.

![WoWScrnShot_052923_131644](https://github.com/slowtorta/turtlewow-bug-tracker/assets/35845488/3439251e-50ee-468a-8f0d-de75acbf6ad3)
