### ISSUE TITLE
Blood Circle ignores Preparation CD

### ISSUE THREAD

**Issue by Phobos-Programmer** [slowtorta/turtlewow-bug-tracker#3575]
**Please, provide a clear description what the bug is:**
Blood Circle arena does not restore rogue "preparation" ability if it’s on cooldown.
**Steps to reproduce the behavior with as much detail as possible:**
Just start Blood Circle with preparation on CD and check that it didn't get refreshed.

**Expected behavior: when you enter Blood Circle all rogue ability on cooldown should be restored and ready to b used on arena**

**Comment by ratkosrb** [comment]
It will be fixed on the next update, but the name of the arena is Blood Ring, not Blood Circle.
