### ISSUE TITLE
Flametongue Weapon Issue

### ISSUE THREAD

**Issue by Melphoone** [slowtorta/turtlewow-bug-tracker#3576]
**Please, provide a clear description what the bug is:**
Flametongue Weapon Critical Hits do not activate Elemental Devastation, although they activate the Clearcasting state(Elemental Focus Talent). Both require Spell critical Hits.
**Steps to reproduce the behavior with as much detail as possible:**

1. Imbue weapon with Flametongue Weapon Spell
2. Land a critical hit with the Flametongue Spell
3. Clearcasting state activates, but not the Elemental Devastation

**IDs of affected creatures, items, quests or spells with a link to the relevant page:**

Spell: https://database.turtle-wow.org/?spell=29178 (Elemental Devastation)
https://database.turtle-wow.org/?spell=45541 (Elemental Focus)
https://database.turtle-wow.org/?spell=16342 (Flametongue weapon)

**Expected behavior. Describe how it should work:**
When landing a critical hit with Flametongue, Elemental Devastation should Procc, just as Elemental Focus does.

**Comment by ratkosrb** [comment]
I don't know what you say "it should", given that it's not blizzlike, but it will be made to work how you want it to work on the next update.
