### ISSUE TITLE
Players Able to Talk Before Level 5

### ISSUE THREAD

**Issue by JoLiKMC** [slowtorta/turtlewow-bug-tracker#3579]
**Please, provide a clear description what the bug is:**
Some players are able to Say, Yell, Emote, and/or use Channels before they reach Level 5.

**Steps to reproduce the behavior with as much detail as possible:**
1. Create a new character or head to a starting zone.  Sit and wait.
2. When someone talks or uses a custom Emote, check their level.

Or…
1. Create a new character and log in.
2. Try and talk.

**Expected behavior. Describe how it should work:**
Players below Level 5 should not be able to communicate beyond using built-in Emotes. (/cry, /sleep, et cetera.)

**Further details:**
On this server, there is a Level 5 minimum before players are able to communicate.  I have seen some players talk before hitting Level 5 – though they are somewhat rare.  The fact that I've seen it a few times makes me wonder what's going on…

**Screenshots:**
![AllYourCandlesAreBelongToUs](https://github.com/slowtorta/turtlewow-bug-tracker/assets/102710555/11bf0bbb-1765-4951-8e13-4925e63e8acd)
*A player talking at Level 2.*
<sup>(Player name censored to protect identity.)</sup>

**Comment by slowtorta** [comment]
This is correct behavior. If you have a high-level character on your account, you can safely use all the chats.

**Comment by JoLiKMC** [comment]
I was not aware.  That's very interesting to note.

Thank you.
