### ISSUE TITLE
Orientation of GM-placed assets changing

### ISSUE THREAD

**Issue by LeopoldHock** [slowtorta/turtlewow-bug-tracker#358]
**Please, provide a clear description what the bug is:**
Since today's server restart (3rd October 21), some gm-placed assets were changed in orientation. I observed this at Southfury Trading guild house (south of Far Watch Post) and also Orgrimmar.

**Steps to reproduce the behavior with as much detail as possible:**

1. Check gm-placed assets (e.g. in Orgrimmar, food stall at auction house).
2. Observe change in orientation by 180° or 45°

**Expected behavior. Describe how it should work:**
Assets should retain their orientation.

**Comment by jameyboor** [comment]
Fixed on next update.
