### ISSUE TITLE
Gug Fatcandle (Test Entity) Attacks Players

### ISSUE THREAD

**Issue by imcdermott13** [slowtorta/turtlewow-bug-tracker#3580]
During a recent Sapphiron attempt we noticed an issue where an invisible test script mob named Gug Fatcandle attacked the closest player to the boss immediately after the spawn animation completed, causing the tank to die at the very beginning of the fight, leading to a wipe.

![GugCombatLog](https://github.com/slowtorta/turtlewow-bug-tracker/assets/52016320/1c856ad6-cbff-4a49-880d-72c9c44bbe5f)

**Steps to reproduce:**

1. Walk into Sapphiron's chamber in Naxxramas
2. Stand next to where Sapphiron spawns while the animation is ongoing
3. Gug Fatcandle attacks the player right as the animation completes (visible only in combat logs)

**IDs of affected creatures:**

Gug Fatcandle: https://database.turtle-wow.org/?npc=62

**Expected behavior:**

Script-based entities and test mobs should not be able to attack players/

**Comment by Muigin** [comment]
This NPC should no longer be in Naxx.

**Comment by Lexiebean** [comment]
Instead of saying Gug Fatcandle it now says Unknown

**Comment by ratkosrb** [comment]
It may be fixed in the next update. If it's not, then a GM needs to turn on GM mode while the invisible creature is attacking players in order to see it, and say which creature is actually doing it. The only suspect atm is 17025.
