### ISSUE TITLE
Bugged Lazy Peon

### ISSUE THREAD

**Issue by Slazmaz** [slowtorta/turtlewow-bug-tracker#3581]
**Please, provide a clear description what the bug is:**

One of the lazy peons does not move nor go to sleep. I found it at 45.6, 65.3.

**Steps to reproduce the behavior with as much detail as possible:**

It was already bugged when I found it. I realize this little information makes it difficult to fix but that's all I have.

**IDs of affected creatures, items, quests or spells with a link to the relevant page:**

NPC: https://database.turtle-wow.org/?npc=10556
Quest: https://database.turtle-wow.org/?quest=5441

**Expected behavior. Describe how it should work:**

The peon should doze off so that it can be awoken for the Lazy Peons quest

**Comment by Slazmaz** [comment]
Said Lazy Peon is still doesn't move even after a server restart. Either the bug reoccurred very quickly or maybe the npc is missing its AI?

**Comment by Gurky-Turtle** [comment]
it looks like it might have been a one off I just checked all lazy peons and they are sleeping and chopping wood.
