### ISSUE TITLE
Unobtainable Children's week quest

### ISSUE THREAD

**Issue by jstwayy** [slowtorta/turtlewow-bug-tracker#3584]
Unable to obtain children's week quest when it is normally available to other players. Spoke to a GM, who mentioned that the quest was already completed by my character, however I have not completed the quest at all. 
Quest: https://database.turtle-wow.org/?quest=1468
Follow up quests are available from other players' orphan NPC. 

Character was created a year ago (iirc), and was not played for a while.

**Comment by Gurky-Turtle** [comment]
Sounds like at some point you did the first part but got rid of your whistle and never did the following parts.
