### ISSUE TITLE
Kelton's Riding Gryphon Stuck on the Ground

### ISSUE THREAD

**Issue by Quackmandan** [slowtorta/turtlewow-bug-tracker#3585]
**Please, provide a clear description what the bug is:**
Kelton's Riding Gryphon gets stuck on the ground.  
**Steps to reproduce the behavior with as much detail as possible:**

1. Complete his prerequisite quest
2. Give it cheese
3. Shake your head as the gryphon gets stuck on the ground, occasionally spasming in different directions.

**IDs of affected creatures, items, quests or spells with a link to the relevant page:**

NPC: https://database.turtle-wow.org/?npc=
Item: https://database.turtle-wow.org/?item=
Quest: https://database.turtle-wow.org/?quest=
Spell: https://database.turtle-wow.org/?spell=
Object: https://database.turtle-wow.org/?object=

**Expected behavior. Describe how it should work:**
It should allow you to fly around Elwynn Forest for 30 seconds, but sometimes you can hardly move it at all.

**Comment by slowtorta** [comment]
This was probably a one-time glitch. I'm unable to reproduce this.

**Comment by Quackmandan** [comment]
It happened to me multiple times. I have watched some other people get
stuck as well. It might have something to do with moving too soon after
mounting the gryphon.
