### ISSUE TITLE
Male Goblin has invisible/delayed projectiles when casting Arcane Missiles

### ISSUE THREAD

**Issue by meginmagi** [slowtorta/turtlewow-bug-tracker#3586]
**Please, provide a clear description what the bug is:**
Male Goblin mages only have glowing hands when casting arcane missiles, until the last volley. When the last volley deals damage, all the missiles fire at once after a 1 second delay. This delay also affects spells such as Fireball if cast after arcane missiles with presence of mind.

The invisible damage is confusing to everyone, as only the goblin mage knows which enemy he is attacking.

**Steps to reproduce the behavior with as much detail as possible:**

1. Be a male goblin mage
2. Cast arcane missiles at anything
3. That's it. It affects all ranks of arcane missiles.

**Expected behavior. Describe how it should work:**
By using a shapeshifting item such as noggenfogger elixir or savory deviate delight, the player makes the arcane missile volleys appear normally.

**Comment by amstiel** [comment]
➕
Same here

**Comment by Muigin** [comment]
This has been fixed and will be pushed in our next client patch (1.17.1)
