### ISSUE TITLE
Unable to train Champions Grace after respeccing

### ISSUE THREAD

**Issue by Martjohn96** [slowtorta/turtlewow-bug-tracker#3589]
**Please, provide a clear description what the bug is:**
According to the priest class changes https://turtle-wow.org/#/priest Once you have Proclaim Champion and hit level 40 you can learn Champions Grace. After respeccing at level 41 or 42 and picking the Proclaim Champion talent the Champions Grace spell have never showed up for me.  

**Steps to reproduce the behavior with as much detail as possible:**

1. Be level 41/42 priest
2. Respec and pick Proclaim Champion talent
3. Not possible to learn Champions Grace

**IDs of affected creatures, items, quests or spells with a link to the relevant page:**
Only affects my ingame character Belayer as far as I know. Have tried the WDB file wipe but no luck.

NPC: https://database.turtle-wow.org/?npc=
Item: https://database.turtle-wow.org/?item=
Quest: https://database.turtle-wow.org/?quest=
Spell: https://database.turtle-wow.org/?spell=
Object: https://database.turtle-wow.org/?object=

**Expected behavior. Describe how it should work:**
That you can learn Champions Grace.

**Comment by Muigin** [comment]
Champion's Grace has only recently been added into the game.  This should now work properly.
