### ISSUE TITLE
Half-Buried Bottles at Shimmering Flats

### ISSUE THREAD

**Issue by zeress** [slowtorta/turtlewow-bug-tracker#3593]
**Please, provide a clear description what the bug is:**
The object Half-Buried Bottle is spawning on some crates in the shimmering flats, when it should only spawn along the east coast of Stranglethorn Vale.

**Steps to reproduce the behavior with as much detail as possible:**

1. Go to 78.1 76 in Thousand Needles
2. Behold green bottles on top of the crates
3. Note that you can loot them, and even get the the quest starter "Carefully Folded Note"
4. ![Screenshot 2023-05-30 181059](https://github.com/slowtorta/turtlewow-bug-tracker/assets/3210721/3090bc08-0010-4e6f-9559-e5f8c2704ae8)

**IDs of affected creatures, items, quests or spells with a link to the relevant page:**

Object: https://database.turtle-wow.org/?object=2560

**Expected behavior. Describe how it should work:**
They should only spawn in Stranglethorn Vale. The bottles in Thousand Needles should be replaced with a non-interactable version instead

**Comment by ratkosrb** [comment]
https://github.com/slowtorta/turtle-wow/commit/13df8a222803c667c67ab64915ff33646b95ee96
