### ISSUE TITLE
The Sleeper Has Awakened

### ISSUE THREAD

**Issue by nonameform** [slowtorta/turtlewow-bug-tracker#36]
**Current behavior**: 
The NPC for the quest _[The Sleeper Has Awakened](https://database.turtle-wow.org/?quest=5321)_ Kerlonian Evershade is supposed to be sleeping in a druid bear form. Currently he is using regular brown bear model. Once you get into combat, he switches from regular bear model into Druid bear form.

**Expected behavior**: 
Once you pick up the quest the Druid who is supposed to be sleeping in Druid bear form transforms into Night Elf and stays this way until you turn in the quest. He does not transform back into bear.

**Proofs**:
The only [proof](https://www.youtube.com/watch?v=1cfc3KLPKj0) nowadays seems to be from Classic WoW videos, but I know certain private servers that had the same behavior way before Classic.

**Comment by slowtorta** [comment]
Thanks for reporting, but it's working as intended. Probably you tried to pick up the quest directly after someone else did it and he was still in his "humanoid" phase. 
![image](https://user-images.githubusercontent.com/66763404/127833769-0ee0ffcf-e387-4c92-a6d0-3adfced2bb51.png)

**Comment by redmagejoe** [comment]
There are a few strange issues with this quest still.
1. When Kerlonian falls asleep, he is meant to have the green "ZZZ" above his head like on Hibernated targets or the Lazy Peons. Currently, he does not.
2. In the second NPC attack, of the three mobs that attack, 2 of them are correctly [Dark Strand Excavators](https://database.turtle-wow.org/?npc=3730) while 1 is a [Witchwing Slayer](https://database.turtle-wow.org/?npc=3278)
