### ISSUE TITLE
NPC periodic yell doubled (Tansy Sparkpen)

### ISSUE THREAD

**Issue by perl1743** [slowtorta/turtlewow-bug-tracker#360]
**Please, provide a clear description what the bug is:**
Tansy Sparkpen's periodic yell is occurring twice each time.
"Latest news from the best race event ever! Come and get your own magazine!"
"Latest news from the best race event ever! Come and get your own magazine!"
![WoW_2021-10-05_16-51-53](https://user-images.githubusercontent.com/2818608/136108050-7eedc666-9549-49c2-aebc-022865db1c23.png)
**Steps to reproduce the behavior with as much detail as possible:**
Not applicable
**IDs of affected creatures, items, quests or spells with a link to the relevant page:**
NPC: https://database.turtle-wow.org/?npc=50760
**Expected behavior. Describe how it should work:**
Should only say the single line periodically, not doubled.

**Comment by slowtorta** [comment]
This will be fixed on the next server update.
