### ISSUE TITLE
Looking For Turtles-LFT  not work

### ISSUE THREAD

**Issue by nabakova** [slowtorta/turtlewow-bug-tracker#3601]
**Please, provide a clear description what the bug is:**

Looking For Turtles-LFT  not work

**Steps to reproduce the behavior with as much detail as possible:**

1.I use the left mouse button to click on the eye of Looking For Turtles-LFT, hoping to use it to join the dungeon, so far it doesn't work, I click on it, it doesn't work

2. Every time I click on the Looking For Turtles-LFT eye, it doesn't work and pops up in the game's chat window, telling me [LFT Notice] you need to be a Diplomat to use LFT. speak with Josepg Dalton in Stormwind to get a [Glyph of Diplomacy] and become a diplomat! you will be able to ggroup and trade with the players of an opposite faction.

3. im in here up new LFT to addons https://github.com/CosminPOP/LFT  and not work 

4. im is windows7 x64  

**IDs of affected creatures, items, quests or spells with a link to the relevant page:**

NPC: https://database.turtle-wow.org/?npc=Stormwind - Josepg Dalton
Item: https://database.turtle-wow.org/?item=
Quest: https://database.turtle-wow.org/?quest=
Spell: https://database.turtle-wow.org/?spell=
Object: https://database.turtle-wow.org/?object=

**Expected behavior. Describe how it should work:**

**Comment by Gurky-Turtle** [comment]
Please make the bug report here https://github.com/CosminPOP/LFT
