### ISSUE TITLE
Druids Out Forms GCD

### ISSUE THREAD

**Issue by wherber60** [slowtorta/turtlewow-bug-tracker#3602]
**Please, provide a clear description what the bug is:**
When character out from Druids any forms it starts GCD 
**Steps to reproduce the behavior with as much detail as possible:**

1. Yo cant cast spells , drink potions or take quests after out forms about 1 sec
2. 
3. 

**IDs of affected creatures, items, quests or spells with a link to the relevant page:**

NPC: https://database.turtle-wow.org/?npc=
Item: https://database.turtle-wow.org/?item=
Quest: https://database.turtle-wow.org/?quest=
Spell: https://database.turtle-wow.org/?spell=
Object: https://database.turtle-wow.org/?object=

**Expected behavior. Describe how it should work:** 
Without GCD on out forms how it was on classic
At the same time there is no GCD when cancel (right click) on buff
But Its on when cancel (right click) on forms buff
I  hope You will Fix it and ill enjoy playing my druid =) Thank you

**Comment by ratkosrb** [comment]
https://github.com/slowtorta/turtlewow-bug-tracker/assets/35845488/ee689e02-4447-41f5-80d8-0185e3616e34


I'm not sure what you mean, because I don't see any GCD on leaving form, no matter if i cancel the buff or click the form again.

**Comment by wherber60** [comment]
Yes, visually it is not there. But in fact it is :) Try to cancel the buff (any form) and immediately click on the potion or spell (it is better to use a hotkey or script), for example, Rejuvenation. You will hear a characteristic error sound so the action will not be performed due to GCD. Also for this reason, scripts for exiting the form + spell or potions do not work. Thank you for your attention.

**Comment by welpenhund** [comment]
Have to agree on  what he says, if you write a macro that (for example) cancels your druid form followed by using a potion you have to click this macro twice because canceling the form triggers an invisible cooldown (don't think it is 1.5 seconds though, more like shorter but it still triggers an invisible cooldown)

**Comment by welpenhund** [comment]
Will try it out, thank you :)

**Comment by wherber60** [comment]
still not fixed

**Comment by Gurky-Turtle** [comment]
@wherber60 did you try nampower?

**Comment by wherber60** [comment]
no. i dont understand how to use it :(

**Comment by wherber60** [comment]
> @wherber60 did you try nampower?

 started nampower. unfortunately it didn't change anything.

**Comment by welpenhund** [comment]
> @welpenhund did nampower help?

i mean... its a little faster but still nothing compared to the proper swaps.

**Comment by Gurky-Turtle** [comment]
I will leave this open for a client dev but I believe this might not be fixable and is a issue with the client itself.

**Comment by wherber60** [comment]
> I will leave this open for a client dev but I believe this might not be fixable and is a issue with the vanilla client itself.

anyway thanks for the help :)

**Comment by luskanek** [comment]
Even if we shipped the game with nampower with the permission of the author, this wouldn't fix the reported issue. It would probably work better for some and for some not. This is not something that we can fix.
