### ISSUE TITLE
[Mug O' Hurt] - Being a daze effect instead of a 50% slow effect.

### ISSUE THREAD

**Issue by welpenhund** [slowtorta/turtlewow-bug-tracker#3603]
Text change after having a talk with a developer: Was in classic and vanilla a daze effect but since it can be highly abused with crusader strike it will be changed to a slow instead that can be shifted or dispelled....

**Steps to reproduce the behavior with as much detail as possible:**

1. equip the item
2. apply seal of crusader and cast them on your opponent
3. procs every time and you are dazed 10 seconds 

**IDs of affected creatures, items, quests or spells with a link to the relevant page:**

NPC: https://database.turtle-wow.org/?npc=
Item: https://database.turtle-wow.org/?item=4090
Quest: https://database.turtle-wow.org/?quest=
Spell: https://database.turtle-wow.org/?spell=
Object: https://database.turtle-wow.org/?object=

**Expected behavior. Describe how it should work:**
Doubt it is supposed to be 100% proc chance and not having any cooldown. You can simply be daze your target for ever.

**Comment by welpenhund** [comment]
> Paladins abuse this item in PvP to proc this with seal of Crusader, then go back to their normal weapon.. you are dazed full 10 seconds without anything you can do about it. Problem here is, that paladins proc chance being 100% when used with seals.
> 
> **Steps to reproduce the behavior with as much detail as possible:**
> 
>     1. equip the item
> 
>     2. apply seal of crusader and cast them on your opponent
> 
>     3. procs every time and you are dazed 10 seconds - If 10 seconds are over - repeat...
> 
> 
> **IDs of affected creatures, items, quests or spells with a link to the relevant page:**
> 
> NPC: https://database.turtle-wow.org/?npc= Item: https://database.turtle-wow.org/?item=4090 Quest: https://database.turtle-wow.org/?quest= Spell: https://database.turtle-wow.org/?spell= Object: https://database.turtle-wow.org/?object=
> 
> **Expected behavior. Describe how it should work:** Doubt it is supposed to be 100% proc chance.

**Comment by welpenhund** [comment]
> P. S. Mug of hurt in pvp isn't rly thaz strong, since you lose the dmg from judging a proper seal, you also don't have SoR or seal of command active which actually, do dmg unlike seal of crusader, and you lose a lot of gcd switching seals around otherwise.

It sadly is in Warsong Gulch very overpowered, because as a flagcarry (for example a mage with rocket boots popped or a druid in travel form) you are permanent dazed once the paladin applied it on you. Can't be dispelled, can't be shifted out, can't be dodged by free action potion.

**Comment by Sringaram** [comment]
The whole development department behind paladins is truly a circus.

**Comment by welpenhund** [comment]
> The procc chance is not 100% But it must be above 80% from my tests

then this paladin was very very lucky, cause it procced every time in the bg on everyone who carried the flag on my team. (not just on me) ^^
