### ISSUE TITLE
Invisible Flame in Forest Song

### ISSUE THREAD

**Issue by AyleeJenn** [slowtorta/turtlewow-bug-tracker#3606]
**Please, provide a clear description what the bug is:**
I don't have a good description for this other than it probably shouldn't be happening. Here is an image.

![firebug](https://github.com/slowtorta/turtlewow-bug-tracker/assets/87241085/cca5cedd-0ebe-4520-9a76-a3c011765326)

Yes, when you stand there in forest song (at near where Brothan Ironglade is you randomly get fire damage. Again, not game breaking I just happened to notice it

**Steps to reproduce the behavior with as much detail as possible:**

1. Stand where I was in the image
2. Feel the heat!
3. 

**Expected behavior. Describe how it should work:**
If I had to guess I would say someone removed the brazier but forgot to remove what ever causes fire but that might not be how things work on WoW. Never modded that.

**Comment by Daribon** [comment]
Someone forgot to delete the campfire.
An image from unmodified vanilla:
![WoW_QSvFzmtlOx](https://github.com/slowtorta/turtlewow-bug-tracker/assets/6137576/8f0651db-9fd3-4ad2-b9c2-182c99966046)
