### ISSUE TITLE
Horn of Engryss Missing Cooldown Indicator

### ISSUE THREAD

**Issue by Aegael** [slowtorta/turtlewow-bug-tracker#3608]
Horn of Engryss sometimes has a missing cooldown indicator for some reason. Changing instances and swapping trinkets will sometimes cause the cooldown indicator to disappear prematurely, making it difficult to tell when the trinket is coming off cooldown.

**IDs of affected creatures, items, quests or spells with a link to the relevant page:**

Item: https://database.turtle-wow.org/?item=83224

**Comment by slowtorta** [comment]
I'm sorry, I couldn't reproduce this issue. Probably it's your local addon-related bug :(
