### ISSUE TITLE
Jed Runewatcher dmg values

### ISSUE THREAD

**Issue by Riske922** [slowtorta/turtlewow-bug-tracker#3609]
Not sure if this was a change that wasn't mentioned or a bug

**Please, provide a clear description what the bug is:**

Jed Runewatcher has new dmg values; from 530-630 to 1,664-1,784

**Steps to reproduce the behavior with as much detail as possible:**

1. Fight Jed and get smacked
2. Twow Database dmg values
3. Use of a find dmg script/macro

**IDs of affected creatures, items, quests or spells with a link to the relevant page:**

NPC: https://database.turtle-wow.org/?npc=10509
Classic Version: https://classicdb.ch/?npc=10509

**Expected behavior. Describe how it should work:**

dmg value should be much lower, instead of being higher than the last boss of the dungeon
(Drakkisath has a dmg range of 1,129-1,481)

**Comment by Gurky-Turtle** [comment]
fix will be applied in the next update.

**Comment by Gurky-Turtle** [comment]
Actually after further research [https://classicdb.ch] has been found to not be a reliable source of information so for now this will not be changed.

**Comment by balakethelock** [comment]
![image](https://github.com/slowtorta/turtlewow-bug-tracker/assets/111737968/f383a95a-ee2d-40c9-92c4-7f9c2b98dc8c)
In classic sniffs his damage is 410 at its lowest and 537 at its highest (2 hits sample size but luckily the guy sniffing got one auto at the bottom and one at the top of his variance _-most mobs in vanilla have 1.14 variance in swing damage-_)

a default level 59 mob does on average 102-135 damage in classic (this information is verifiable in the [bestiary](https://files.gw2archive.eu/World%20of%20Warcraft%20Bestiary%20Searchable.pdf) but vmangos already did all the work so we can take accurate numbers directly from it.)

Going from the melee damage value of a default mob to the melee damage value of jed in sniffs, we can reasonably assume blizzard did it simply multiplying by 4, so his melee damage **should be 408-540**

**Comment by TWShang** [comment]
We do not use classic wow numbers as a reference for terms of damage/armor/resistance.

**Comment by balakethelock** [comment]
> We do not use classic wow numbers as a reference for terms of damage/armor/resistance.

Still, seems like an accidental change. It's tripling of his auto damage, not documented in the patchnotes, on a mob that has a strike and a charge based on weapon damage. Makes him hurt a lot more than one expects from a level 59 rare.

**Comment by Riske922** [comment]
I made this post after a patch day, where we had just done ubrs the week before. If you want to double check, try an older version of Twow

Either way, the numbers were def changed for no discernable reason, and my grabbing of classic values was an attempt to return them, as how would i have the old numbers available unless looking at a past twow version
