### ISSUE TITLE
Salve Via Hunting broken

### ISSUE THREAD

**Issue by Divinum45** [slowtorta/turtlewow-bug-tracker#3610]
**Please, provide a clear description what the bug is:**

the repeatable quest "Salve Via Hunting" no longer is offered by Arathandris Silversky

**Steps to reproduce the behavior with as much detail as possible:**

1. go to questgiver after completing the prereqs and completing the quest at least once
2. 
3. 

**IDs of affected creatures, items, quests or spells with a link to the relevant page:**

NPC: https://database.turtle-wow.org/?npc=
Item: https://database.turtle-wow.org/?item=
Quest: https://database.turtle-wow.org/?quest= Salve Via Hunting
Spell: https://database.turtle-wow.org/?spell=
Object: https://database.turtle-wow.org/?object=

**Expected behavior. Describe how it should work:**

turn in Corrupted Soul Shards to get Cenarian Plant Salve
![1salve via hunting](https://github.com/slowtorta/turtlewow-bug-tracker/assets/135437599/90bf38c9-de4c-4f23-a61d-8dc3c383ed5f)

**Comment by colthalter** [comment]
Broken for me too.

**Comment by Gurky-Turtle** [comment]
This is working as it should in my tests, please clear your wdb folder and make sure to try without any addons.

**Comment by Gurky-Turtle** [comment]
![image](https://github.com/slowtorta/turtlewow-bug-tracker/assets/90982783/8c88d6c7-d197-44e4-ba74-2d829252e7b4)
