### ISSUE TITLE
Magram rep elemental doing way, way too much damage

### ISSUE THREAD

**Issue by Dualityz** [slowtorta/turtlewow-bug-tracker#3612]
**Please, provide a clear description what the bug is:**

Baelfyr, the lvl 41 Elite fire Elemental that you have to kill for the Magram rep quest Fear Incarnate 
(https://database.turtle-wow.org/?quest=40615) does 336 - 432 fire damage on hit. That's as much damage as some Blackrock Depths bosses ( Bael'Gar notably, as level 54 Elite does exactly 335 - 432, but physical which means mitigated by armor ). 
Unless this is supposed to be a gimmicky burst fight with a mandatory tank death, it looks as if the damage is much higher than expected of a lvl 41 Elite, even for the target of a 5 man Elite quest.

**Steps to reproduce the behavior with as much detail as possible:**

1. Hit Baelfyr with +5 levels on him
2. Scream very high at your hp melting away unmitigated by armor
3. 

**IDs of affected creatures, items, quests or spells with a link to the relevant page:**

NPC: https://database.turtle-wow.org/?npc=61043
https://database.turtle-wow.org/?npc=9016 for comparison
Quest: https://database.turtle-wow.org/?quest=40615

**Expected behavior. Describe how it should work:**

Half that damage if you wanna keep it fire damage ? Definitely should be toned down

**Comment by Gurky-Turtle** [comment]
should be fixed next update
