### ISSUE TITLE
Magram Reputation questchain giving no reputation

### ISSUE THREAD

**Issue by Dualityz** [slowtorta/turtlewow-bug-tracker#3613]
**Please, provide a clear description what the bug is:**

I'm unsure if this is intended or not, but a GM told me to open a bug ticket for it so here goes. 
None of the quests from he questchain from Warug ( Broken Tears, Gizmo for Warug, Khan Shaka, Khan Hratha ), one of the quest givers at Magram Village, give Magram rep. 

**Steps to reproduce the behavior with as much detail as possible:**

1. Take all the aforementioned quests and turn them in
2. No rep
3. 

**IDs of affected creatures, items, quests or spells with a link to the relevant page:**

Quests: https://database.turtle-wow.org/?quest=1369
https://database.turtle-wow.org/?quest=1371
https://database.turtle-wow.org/?quest=1375
https://database.turtle-wow.org/?quest=1381

**Expected behavior. Describe how it should work:**
Give some sort of rep for each quest I suppose

**Comment by Gurky-Turtle** [comment]
None of these quests give rep it seems on wowhead, I will leave this seeing we made changes to this rep.
