### ISSUE TITLE
Tower of lapidis

### ISSUE THREAD

**Issue by Szabo111** [slowtorta/turtlewow-bug-tracker#3614]
**Please, provide a clear description what the bug is:**

**Steps to reproduce the behavior with as much detail as possible:**

1.Quest not letting me pick up
2. Completed all other prerequisites
3. Handed in tower of lapidis 9 and was told to hand in the enchanted key to hydromancer flakereef and i did that and now it says he has the tenth quest but when i talk to him there's nothing.

**IDs of affected creatures, items, quests or spells with a link to the relevant page:**

NPC: https://database.turtle-wow.org/?npc=
Item: https://database.turtle-wow.org/?item=
Quest: https://database.turtle-wow.org/?quest=
Spell: https://database.turtle-wow.org/?spell=
Object: https://database.turtle-wow.org/?object=

**Expected behavior. Describe how it should work:**

**Comment by Gurky-Turtle** [comment]
will be fixed in the next update.
