### ISSUE TITLE
Warlock Item: Grimoire of Avoidance, Item non-functional.

### ISSUE THREAD

**Issue by Loral-Niran** [slowtorta/turtlewow-bug-tracker#3617]
Grimoire of Avoidance is to be used to teach Avoidance to Warlock Pets.

1. Purchase Grimoire of Avoidance from Demon Trainer NPC.
2. Summon Demon. (Imp, Void Walker, Succubus, Felhunter) / (Infernal, Felguard, Doomguard)
3. Use Grimoire of Avoidance
4. Pet/Demon is taught Avoidance

Item: https://database.turtle-wow.org/?item=83584

Grimoire of Avoidance should teach Avoidance to the currently Summoned Demon. 

![Imp](https://github.com/slowtorta/turtlewow-bug-tracker/assets/135467386/fda36ab6-b273-47dd-90fb-70ac0076a614)

![Void Walker](https://github.com/slowtorta/turtlewow-bug-tracker/assets/135467386/f3393a34-ce5b-4f01-880a-9421d327c800)

![Succubus](https://github.com/slowtorta/turtlewow-bug-tracker/assets/135467386/e7d53246-23fa-4291-9f78-3e63aff0c07d)

![Felhunter](https://github.com/slowtorta/turtlewow-bug-tracker/assets/135467386/53f38e65-6285-4fc8-99e3-87795e413426)

![Infernal](https://github.com/slowtorta/turtlewow-bug-tracker/assets/135467386/c453b09e-ff01-4344-8529-4ab2dc326729)

![Felguard](https://github.com/slowtorta/turtlewow-bug-tracker/assets/135467386/f4af2527-a942-4b55-9534-d1e606fc5ce0)

![Doomguard](https://github.com/slowtorta/turtlewow-bug-tracker/assets/135467386/ec31e28c-3232-444d-beb6-f2d6967d9be2)

Grimoire does not function as intended.

**Comment by Gurky-Turtle** [comment]
https://github.com/slowtorta/turtlewow-bug-tracker/issues/3383
