### ISSUE TITLE
The woman from the "A Warden Of The Alliance" is gone

### ISSUE THREAD

**Issue by Vinzent22** [slowtorta/turtlewow-bug-tracker#3618]
**Please, provide a clear description what the bug is:**

Orphan Matron Nightingale is gone in Stormwind. She's not on the place since 04/06/23 evening and there is no way to return the quest "A Warden Of The Alliance"
Also not spawning after 15 minutes.

**IDs of affected creatures, items, quests or spells with a link to the relevant page:**

NPC: https://www.wowhead.com/classic/npc=14450/orphan-matron-nightingale#sells

**Expected behavior. Describe how it should work:**

**Comment by Gurky-Turtle** [comment]
![image](https://github.com/slowtorta/turtlewow-bug-tracker/assets/90982783/546c10e4-7b8d-453a-9a81-21494e0c682c)
also with a very short respawn timer.
