### ISSUE TITLE
[Quest Bug] Scarlet Diversions Quest in Western Plaguelands doesn't get updated after using quest items.

### ISSUE THREAD

**Issue by EvaNikolaeva** [slowtorta/turtlewow-bug-tracker#3619]
**Please, provide a clear description what the bug is:**
Bugged Quest [Scarlet Diversions] in Western Plaguelands for Horde. Quest says to get Flame in a bottle from the horde camp, go to the Scarlet Forward Camp (east from Felstone Cauldron and west from Dalson's Tears), use the Flame in a bottle to burn the tent and then plant the banner in the same place. After two tries with my duo none of us got a quest update for completion and we couldn't plant the banner, having a message "You must be in Scarlet Forward Camp".  This proves to be a big problem for advancing in plaguelands, because this quest is prerequisite for all the Cauldron quests.

**Steps to reproduce the behavior with as much detail as possible:**

1. Grab Flame in a bottle from the Tirisfal Glades Horde Camp and head to the Scarlet Camp (east from Felstone Cauldron and west from Dalson's Tears)
2. Use Flame Oil on the tent. There should be no update message from the quest, nothing happens after usage.
3. Try to use the quest item "Scourge Banner". After usage, a message says "You must be in Scarlet Forward Camp"

**IDs of affected creatures, items, quests or spells with a link to the relevant page:**

NPC: https://database.turtle-wow.org/?npc=10837
Item: https://database.turtle-wow.org/?item=12814
Item: https://database.turtle-wow.org/?item=12807
Quest: https://database.turtle-wow.org/?quest=5096

**Expected behavior. Describe how it should work:**
After using the Flame in a bottle item, I expect to receive a quest update message. After that, I will use the Scourge Banner either from my inventory or right-clicking on the already existing banner in the camp to replace it. After that, quest should be completed.

**Comment by Gurky-Turtle** [comment]
![image](https://github.com/slowtorta/turtlewow-bug-tracker/assets/90982783/81911c53-b381-49ee-b519-d8778986414a)
You need to stand around where the tent was to drop the banner. It works as it should from my tests.
