### ISSUE TITLE
Quest Mastering the Arcane not available for trolls

### ISSUE THREAD

**Issue by Tinyfin-github** [slowtorta/turtlewow-bug-tracker#362]
Quest Mastering the Arcane not available for trolls.
It should be available for all horde races that are able to have the mage class

https://database.turtle-wow.org/?quest=80311 Mastering the Arcane

![image](https://user-images.githubusercontent.com/83077166/136366637-d9e022fc-ba8a-4886-b47b-56e973e145d1.png)

**Comment by slowtorta** [comment]
This will be fixed on the next server update.
