### ISSUE TITLE
Bugged quest wont let me pickup (tower of lapidis)

### ISSUE THREAD

**Issue by Szabo111** [slowtorta/turtlewow-bug-tracker#3620]
**Please, provide a clear description what the bug is:**

**Steps to reproduce the behavior with as much detail as possible:**

1.complete all other 9 quests that lead up to 10
2. hand in 9 to get to ten
3. ten is being given by the quest giver, thats it theres no war going on or aliens messing with me its just the quest not being able to be picked up and yet i still cant get any fucking help from you guys!

**IDs of affected creatures, items, quests or spells with a link to the relevant page:**

NPC: https://database.turtle-wow.org/?npc=
Item: https://database.turtle-wow.org/?item=
Quest: https://database.turtle-wow.org/?quest=
Spell: https://database.turtle-wow.org/?spell=
Object: https://database.turtle-wow.org/?object=

**Expected behavior. Describe how it should work:**
you should be able to pick up "tower of lapidis X" but its not there

**Comment by Gnawbone** [comment]
I have the same issue, handed in IX to Hydromancer Flakereef, advanced to Friendly with Kul Tiras, and could not pick up X. 
I haven't finished "The Aqua Stone" or "The Hermit's Wrath" on Lapidis Isle, if that matters.

**Comment by Gurky-Turtle** [comment]
Will be fixed in the next update.
