### ISSUE TITLE
Naxxramas Slime does not place the debuff on players

### ISSUE THREAD

**Issue by Zebouski** [slowtorta/turtlewow-bug-tracker#3624]
**Please, provide a clear description what the bug is:**
The green toxic slime all around naxx is meant to place a debuff on players that stand inside it.

This importantly comes up on patchwerk trash where the river is a consideration you must make when working on the trash. 
Also, when Patchwerk is engaged, having the slime working allows warriors to significantly lower their hp, avoiding taking hatefuls as a dps in the event there are less than 3 tanks in hateful range. 

Operational slime will also make skipping trash routes significantly more risky and will break invis pots, making invis skips significantly more impractical. https://github.com/slowtorta/turtlewow-bug-tracker/issues/3622

**Steps to reproduce the behavior with as much detail as possible:**

1. Stand in naxx slime
2. nothing happens

**IDs of affected creatures, items, quests or spells with a link to the relevant page:**

Spell: https://www.wowhead.com/classic/spell=28801/slime

**Expected behavior. Describe how it should work:**
Standing still in the slime should place the debuff

HOWEVER, players who run and jump over the slime, should NOT be hit by it. this is important!!! If it is not consistently possible to jump over the slime, this will be a major QoL down as everyone needs to spend time healing and regenning from the hp/mana cap reduction. This sucks and nobody wants this part back, which is why this bug hasn't been reported in the 2 years of naxx being online.

**Comment by twowTurtReynolds** [comment]
Fixed :)
