### ISSUE TITLE
Rend Buff Does Not Affect Players in Valley of Honor

### ISSUE THREAD

**Issue by Quackmandan** [slowtorta/turtlewow-bug-tracker#3626]
**Please, provide a clear description what the bug is:**
Rend buff does not reach players in Orgrimmar when they're in The Valley of Honor section of the city.  You can clearly see this bug yourself if you target the npc's in this part of the city.  The guards just outside this part of Orgrimmar have the buff.  All of the npc's inside do not.
**Steps to reproduce the behavior with as much detail as possible:**

1. Turn in quest for rend buff
2. Check npc's in valley of honor
3. notice the buff is missing there

**IDs of affected creatures, items, quests or spells with a link to the relevant page:**

NPC: https://database.turtle-wow.org/?npc=
Item: https://database.turtle-wow.org/?item=
Quest: https://database.turtle-wow.org/?quest=
Spell: https://database.turtle-wow.org/?spell=
Object: https://database.turtle-wow.org/?object=

**Expected behavior. Describe how it should work:**
Rend buff should affect all parts of Orgrimmar and The Crossroads.

**Comment by Zebouski** [comment]
Not just rend, but ony/nef too have a very small radius in org and stormwind

**Comment by Quackmandan** [comment]
Ah I guess you're right. I never remembered that being an issue in original
vanilla or classic WoW, but I mained alliance so it never came up. I just
assumed it was a bug. Thank you.
