### ISSUE TITLE
Goblin Racial for Mace skill not applying to 2-hand Maces

### ISSUE THREAD

**Issue by Quackmandan** [slowtorta/turtlewow-bug-tracker#3627]
**Please, provide a clear description what the bug is:**
The Goblin racial for +5 to maces does not apply to 2-handed maces. 
**Steps to reproduce the behavior with as much detail as possible:**

1. Login to a goblin
2. open the skills tab
3. check the max skill of 2-handed mace vs 1-handed mace

**IDs of affected creatures, items, quests or spells with a link to the relevant page:**

NPC: https://database.turtle-wow.org/?npc=
Item: https://database.turtle-wow.org/?item=
Quest: https://database.turtle-wow.org/?quest=
Spell: https://database.turtle-wow.org/?spell=
Object: https://database.turtle-wow.org/?object=

**Expected behavior. Describe how it should work:**
Both 2-handed and 1-handed maces should receive +5 to max weapon skill for goblins.

**Comment by balakethelock** [comment]
Not a bug, auras that increase two handed skill explicitly say "increased two-handed maces" for example https://database.turtle-wow.org/?item=81223

When they made goblins they decided to only give one handed mace skill, not two handed
I guess because goblins are tiny and can't swing big weapons? idk, not agreeing or disagreeing with the decision, just saying is not a bug.

**Comment by Quackmandan** [comment]
This is inconsistent with other racial weapon skills. Humans mace & sword
specializations affects one- and two-handed weapons. Same for orcs and
axes.  The goblin racial is listed as "mace specialization" just like the
humans. So why would one only affect one-handed mace while the other
affects both? You can argue the physical size as an excuse, but it is
inconsistent with how the racial is listed and explained. The racial should
specify as "one-handed maces" if that is really how it was intended but
this definitely is misleading. To me as a player, this comes across as an
unintended bug that could be easily fixed.

**Comment by Zmitrok1984** [comment]
Why did you decide that the Goblin should be able to have +5 skil for two-handed mace?
![image](https://github.com/slowtorta/turtlewow-bug-tracker/assets/99164611/65bb85f4-5e55-4952-aed0-d48c1bc924cf)

**Comment by twowTurtReynolds** [comment]
Well, this suggestion has been added.
![image](https://github.com/slowtorta/turtlewow-bug-tracker/assets/151180101/6f915776-ad83-4351-8e3f-7ac71b522ab8)
And the spell text has been updated.
![image](https://github.com/slowtorta/turtlewow-bug-tracker/assets/151180101/3437a9a6-4d61-4540-98a8-774a38a46d6b)
