### ISSUE TITLE
https://turtle-wow.org/expansion (404)

### ISSUE THREAD

**Issue by wezlol** [slowtorta/turtlewow-bug-tracker#3629]
The URL: https://turtle-wow.org/expansion

gives a 404 error.

Link to this from:
https://forum.turtle-wow.org/viewtopic.php?t=728   _You can read about it here: https://turtle-wow.org/expansion_

**Comment by slowtorta** [comment]
This link is outdated and doesn't exist on the new version of our website :) You can read about our features if you open a drop-down menu on our main page.

**Comment by wezlol** [comment]
I know, but you link to it in the post
