### ISSUE TITLE
Jubjub won't move when placing Dark Iron Ale 

### ISSUE THREAD

**Issue by Fin9622** [slowtorta/turtlewow-bug-tracker#363]
Jubjub won't move when placing Dark Iron Ale 

To get the quest Spawn of Jubjub you need to first lure JubJub to Morja with Dark Iron Alie
What does not work: When placing the Dark Iron Ale Jubjub does not follow.

https://database.turtle-wow.org/?npc=14867 Jubjub
https://database.turtle-wow.org/?quest=7946 Spawn of Jubjub
https://database.turtle-wow.org/?npc=14871 Morja
https://database.turtle-wow.org/?item=11325 Dark Iron ale

**Comment by NickTyrer** [comment]
See https://github.com/vmangos/core/commit/8f2af5dff4c61ec58b118bd15399a5dfd775e83a

**Comment by geojak** [comment]
hello, this is not fixed
![WoWScrnShot_032122_215733](https://user-images.githubusercontent.com/25199983/159362636-71481997-f001-4cac-9fe3-3eee83522a75.jpg)

pls reopen @Tinyfin-github 
unless its just not life yet??

**Comment by Lexiebean** [comment]
Spawn of Jubjub quest also cannot be turned in if it has been manually added.

**Comment by geojak** [comment]
it seems i cannot accept a quest for jub jub if it exists. jub jub wont react to beer still

**Comment by redmagejoe** [comment]
This quest is still not scripted properly. The frog does not move at all.

**Comment by DerpyDooHooves** [comment]
I'm afraid the specter of this quest being bugged has come up again, I've put all my 10 mugs down trying to coax Jubjub from under the wagon, and it won't move.

**Comment by Giperion** [comment]
Quest is not bugged. And it's scripted the same way as in Blizzard server, which is.... actually a problem. Let me explain:
On screenshot above you placed ale mug near frog, thinking that it will be attracted to the mug. In reality you should place mug near the "Morja" since technically it's "Morja" who invoke script that attract "Jubjub".

**Comment by Muigin** [comment]
> Quest is not bugged. And it's scripted the same way as in Blizzard server, which is.... actually a problem. Let me explain: On screenshot above you placed ale mug near frog, thinking that it will be attracted to the mug. In reality you should place mug near the "Morja" since technically it's "Morja" who invoke script that attract "Jubjub".

Confirmed, Working as Intended.
