### ISSUE TITLE
AQ40 Post-Twin Emperors' Trash is severely overtuned

### ISSUE THREAD

**Issue by Zebouski** [slowtorta/turtlewow-bug-tracker#3633]
**Please, provide a clear description what the bug is:**
From what I've been told, the trash packs after twin emps in aq40, all do their abilities at the same time, including multiple mind controls. This has made this stretch of trash so insanely hard and unfun to do, that _every single aq40 guild_ will just use invisibility potions to skip this trash. In the 2+ years of raiding I personally have never seen this trash pulled

This is related to the big bug https://github.com/slowtorta/turtlewow-bug-tracker/issues/1142 , this is just the worst case of it.

**Steps to reproduce the behavior with as much detail as possible:**

1. Pull twin emps trash with 10+ people
2. See the person pulling get oneshot
3. See multiple MCs go off right away

**Expected behavior. Describe how it should work:**
These mobs are meant to use their abilities not at the same time, and the MCs are meant to be rare. Plentiful footage from Classic exists that shows this trash isn't meant to be too hard.

The ideal play should be for guilds to pull these trash and quickly get through them, and the invisibility skip method should be a much slower, last resort trick. With this fixed, this will effectively add content to Turtle WoW, as right now this stretch of content is 100% dead, and not in a good way.

**Comment by ratkosrb** [comment]
Please provide db links for all creatures you want nerfed to save developer time.

Like this:
https://database.turtle-wow.org/?npc=15276

**Comment by Zebouski** [comment]
Well that's the thing, I don't know the names of these mobs. I've never once killed them on this server...

**Comment by TatkaS1** [comment]
Here are the after-Twins trash mobs that my guild successfully clears every AQ40 run (every single pack):
https://database.turtle-wow.org/?npc=15250 Qiraji Slayer
https://database.turtle-wow.org/?npc=15246 Qiraji Mindslayer
https://database.turtle-wow.org/?npc=15252 Qiraji Champion

If your raid isn't good enough to kill them without many casualties which are a big time loss on every pack, you can also use pathing+safe spot skip to avoid most of them.

**Comment by Zebouski** [comment]
> Skipping the trash is fun and takes some amount of skill. These mobs are also the only ones that drop the meteor trinket so there is a downside to skipping them. I think more raids should have trash like this where they're possible to skip if you can time their pathing just right. Please don't remove the ability to skip them.

Skipping the trash might be fun for the handful of people doing the skip, but the rest just afk for 10 minutes. It's not fun for the majority, its a major pace break.

But that's not what this ticket is about. It's about making the trash actually doable, so that clearing the trash could be even faster than waiting for the skippers to complete. More gameplay, more loot, save consumes, and less afking. A general improvement to the game.

**Comment by ConcernedTurtler** [comment]
Everyone in our guild does the skip, we don't use summons.

**Comment by Zebouski** [comment]
> Everyone in our guild does the skip, we don't use summons.
> 
> That may be what your ticket is about but you know how devs are. They'll nerf the trash and think, "well this shouldn't be skippable anymore now that it's easy" and make it so you have to go through them.

The purpose of this bug report is to get the state of the trash actually playable, so that skipping becomes optional instead of the only reasonable way of doing things.

Whether or not invis skipping should be viable here  (and elsewhere)  is a totally different matter.
