### ISSUE TITLE
A Husband's Revenge Quest is bugged

### ISSUE THREAD

**Issue by imSaltie** [slowtorta/turtlewow-bug-tracker#3639]
**Please, provide a clear description what the bug is:**
The quest "A Husband's Revenge" cannot be obtained by my Undead Mage. An error pops up in chat stating: That quest is not available for your race.
**Steps to reproduce the behavior with as much detail as possible:**

1. Turn in the quest "Raleigh and the Undercity
2. Click accept on the quest "A Husband's Revenge" after it pops up
3. Quest errors out

**IDs of affected creatures, items, quests or spells with a link to the relevant page:**

NPC: https://database.turtle-wow.org/?npc=2050
Quest: https://database.turtle-wow.org/?quest=530

**Expected behavior. Describe how it should work:**
You should be able to accept the quest if you are Horde.

**Comment by Gurky-Turtle** [comment]
Should be fixed next update.
