### ISSUE TITLE
Wand damage is reduced with Spell Damage (Not a bug, new ticket @ 3648)

### ISSUE THREAD

**Issue by imSaltie** [slowtorta/turtlewow-bug-tracker#3645]
**Please, provide a clear description what the bug is:**
Spell Damage from equipped gear does not apply correctly to Wands. It reduces the base damage of the Wand by the same amount as your Spell Damage, and applies the Spell Damage as a bonus.
**Steps to reproduce the behavior with as much detail as possible:**

1. Equip a Greater Magic Wand.
2. As a Mage, grab the Wand Specialization talent from the Arcane tree.
3. Check the base damage of the wand, it should be 29-54 damage.
4. Equip Staff of the Arcane Path and Signet of Durotar.
5. The Wand's damage should remain the same, 29-54, but hovering over the damage shows it as 16-41+13.

**IDs of affected creatures, items, quests or spells with a link to the relevant page:**

Item: https://database.turtle-wow.org/?item=11288
Item: https://database.turtle-wow.org/?item=60916
Item: https://database.turtle-wow.org/?item=80860

**Expected behavior. Describe how it should work:**
Spell Damage should not reduce Wand base damage, and should increase the damage you deal with your wand.

![wand talent](https://github.com/slowtorta/turtlewow-bug-tracker/assets/135771375/cdcb31fa-ce88-4aac-ab7b-55fd00834921)

![bugged wand](https://github.com/slowtorta/turtlewow-bug-tracker/assets/135771375/954cac71-98a2-4169-87a4-12b5627125b4)

**Comment by welpenhund** [comment]
Pretty sure that spell damage never increased the damage of wands

![grafik](https://github.com/slowtorta/turtlewow-bug-tracker/assets/30401521/780bf08f-d246-4a63-be4e-3148c55de99f)

**Comment by imSaltie** [comment]
Ah, then it's just a visual bug then with spell damage being applied.

**Comment by welpenhund** [comment]
> Ah, then it's just a visual bug with spell damage being applied.

No, the +13 dps is not from spellpower it is the bonus from your "Wand specialization" :-)

**Comment by imSaltie** [comment]
> No, the +13 dmg is not from spellpower it is the bonus from your "Wand specialization" :-)

The Wand Spec was already applied, that's my spell damage that's showing.

**Comment by imSaltie** [comment]
This issue can be closed. I'll make a new bugtracker report.
