### ISSUE TITLE
Wand Damage is being displayed as modified by Spell Damage

### ISSUE THREAD

**Issue by imSaltie** [slowtorta/turtlewow-bug-tracker#3648]
**Please, provide a clear description what the bug is:**
Spell Damage is showing as being applied to wands in the tooltip of Wand Damage on the Character Sheet. This is a visual bug.
**Steps to reproduce the behavior with as much detail as possible:**

1. Equip a Wand
2. Check Wand Damage in Character Sheet
3. Equip a piece of gear with Spell Damage
4. Hover over Wand Damage on character sheet
5. Wand Base Damage is now reduced by Spell Damage and modified by Spell Damage by the same amounts.

**IDs of affected creatures, items, quests or spells with a link to the relevant page:**

Any Wand and any equipment with Spell Damage

**Expected behavior. Describe how it should work:**
The tooltip and display on the Character Sheet for Wand Damage should not be modifiable by Spell Damage.

![bugged wand](https://github.com/slowtorta/turtlewow-bug-tracker/assets/135771375/904aab17-159f-4ff8-8bd9-296aa96bab7f)

>Pretty sure that spell damage never increased the damage of wands
>
>Source: https://vanilla-wow-archive.fandom.com/wiki/Wand
>
>![grafik](https://github.com/slowtorta/turtlewow-bug-tracker/assets/30401521/9d6cf740-8968-4854-9b6b-da10f8807360)
>
>_Originally posted by @welpenhund in https://github.com/slowtorta/turtlewow-bug-tracker/issues/3645#issuecomment/1581489765_

**Comment by octav3k** [comment]
This was an issue back in original vanilla too, so it's probably inherited from the 1.12 client. I'm not saying it shouldn't be fixed, just offering extra info, which may help point the devs in the right direction.

**Comment by SimenSch** [comment]
this is not an issue, also a nice way to check your spellpower if you dont have the addons

**Comment by twowTurtReynolds** [comment]
We could polish this Blizzard UI bug, but we risk breaking UI addons for this, something that most people will overlook.
