### ISSUE TITLE
crescent grove staff

### ISSUE THREAD

**Issue by alemo1992** [slowtorta/turtlewow-bug-tracker#3649]
**Please, provide a clear description what the bug is:**
https://database.turtle-wow.org/?item=83231
crescent grove staff does not give 6 nature spell damage, I use BetterCharacterStats addon, and it shows 0 nature spell damage when wear, I do delete WDB folder.
**Steps to reproduce the behavior with as much detail as possible:**

1.
2. 
3. 

**IDs of affected creatures, items, quests or spells with a link to the relevant page:**

NPC: https://database.turtle-wow.org/?npc=
Item: https://database.turtle-wow.org/?item=
Quest: https://database.turtle-wow.org/?quest=
Spell: https://database.turtle-wow.org/?spell=
Object: https://database.turtle-wow.org/?object=

**Expected behavior. Describe how it should work:**

**Comment by slowtorta** [comment]
The server does not send spell power values to the client before 2.0, we tested this spell and it's working as intended. Most spells do not scale at 100% of spell power, especially lower ranks of spells.
