### ISSUE TITLE
An Infinite Hunt - Crystal at Seradane is bugued

### ISSUE THREAD

**Issue by Goulibi** [slowtorta/turtlewow-bug-tracker#3650]
Hello, please fix this asap, custom quests are what make your server interesting.

1.Got An Infinite Hunt in quest log
2. Go to Seradane - Hinterland on the temple where the red crystal is and where CHromie should appear when you interact with the crystal
3. YOU CAN'T INTERACT AT ALL with the crystal
4. Reported few times on discord by several users in support channel

**IDs of affected creatures, items, quests or spells with a link to the relevant page:**

Quest: https://database.turtle-wow.org/?quest=80411

**Expected behavior. Describe how it should work:**

You should be able to interact on right click with the crystal

**Comment by gene314159** [comment]
got the same issue kindly look after this

**Comment by StayTuned2k** [comment]
Same here, thanks for addressing it

**Comment by ratkosrb** [comment]
I made a new attempt to fix this. Not sure how it's breaking since it always works locally. Let's see if the changes fix it next week.
