### ISSUE TITLE
Arathandris Silversky NPC is bugged

### ISSUE THREAD

**Issue by bebraveorbeslave** [slowtorta/turtlewow-bug-tracker#3652]
Arathandris Silversky NPC will not accept Corrupted Soul Shards or Patches of Tainted Skin to reward with Cenarion Plant Salves.

NPC: https://database.turtle-wow.org/?npc=9528
Quest: https://database.turtle-wow.org/?quest=4103
Quest: https://database.turtle-wow.org/?quest=4106

**Comment by ratkosrb** [comment]
This was already fixed last week. I tested it again and it works.


https://github.com/slowtorta/turtlewow-bug-tracker/assets/35845488/700d476d-f524-4ff7-ba95-b4c82f3408af
