### ISSUE TITLE
Spirits of Southwind quest not available to my night elf druid

### ISSUE THREAD

**Issue by JanusMD** [slowtorta/turtlewow-bug-tracker#3653]
Layo Starstrike in Valor rest did not give the quest "The Spirits of Southwind" to my night elf druid. I received the error "This quest is not available to your race".

I turned in the prior quest "Wasteland" to Layo Starstrike and received the above error when trying to pick up the follow-up The Spirits of Southwind. 

1. Turned in prior quest in the chain (https://database.turtle-wow.org/?quest=1124)
2. Could not pick up the quest (https://database.turtle-wow.org/?quest=1125)
3. The quest is not available for pick-up at the NPC

NPC Layo Startrike: https://database.turtle-wow.org/?npc=13220
Quest The Spirits of Southwind: https://database.turtle-wow.org/?quest=1125

The quest should be available to the Alliance/Night Elves 

PS: I tried deleting the WDB folder, relog and speak to NPC again but the quest isn't available

**Comment by Mirisimus** [comment]
I had the same problem on my paladin today.
Also deleted WDB folder, reloged. Nothing.

**Comment by Fidget16** [comment]
I also had the same error on my human paladin. I also deleted WDB and relogged, did not resolve for me either.

**Comment by Azgaardian** [comment]
same here, human warrior

**Comment by slowtorta** [comment]
Presently this one is working as intended. 
![image](https://github.com/slowtorta/turtlewow-bug-tracker/assets/66763404/f5b01bd5-bec4-4ef4-8d13-436b879649e8)

**Comment by JanusMD** [comment]
![twowquest](https://github.com/slowtorta/turtlewow-bug-tracker/assets/135970012/7439ab64-cc8f-4902-934b-b5b2d04df57e)

I just took this screenshot, still no quest. Anyway... thanks for looking into this.
