### ISSUE TITLE
druid trainer: spelling mistake

### ISSUE THREAD

**Issue by SMILEWHENYOUDIE** [slowtorta/turtlewow-bug-tracker#3654]
**Please, provide a clear description what the bug is:**

spelling mistake

**Steps to reproduce the behavior with as much detail as possible:**

1. visit druid trainer (for me it was in Moonglade)
2. spell Savage Bite (Rank 1)

**IDs of affected creatures, items, quests or spells with a link to the relevant page:**

NPC: https://database.turtle-wow.org/?npc=12042
Item: https://database.turtle-wow.org/?item=
Quest: https://database.turtle-wow.org/?quest=
Spell: https://database.turtle-wow.org/?spell=45736
Object: https://database.turtle-wow.org/?object=

**Expected behavior. Describe how it should work:**

Change "Taches..." to "Savagely bite the target, dealing normal damage plus XX"

**Comment by Muigin** [comment]
This has been fixed as of a previous update.
