### ISSUE TITLE
[Scarlet Diversions] quests where you must take Flame in A Bottle from the box. The box is not clickable. Is this a commonly known issue?

### ISSUE THREAD

**Issue by Konspaul** [slowtorta/turtlewow-bug-tracker#3663]
**Please, provide a clear description what the bug is:**

**Steps to reproduce the behavior with as much detail as possible:**

1.
2. 
3. 

**IDs of affected creatures, items, quests or spells with a link to the relevant page:**

NPC: https://database.turtle-wow.org/?npc=
Item: https://database.turtle-wow.org/?item=
Quest: https://database.turtle-wow.org/?quest=5096
Spell: https://database.turtle-wow.org/?spell=
Object: https://database.turtle-wow.org/?object=

**Expected behavior. Describe how it should work:**

**Comment by Konspaul** [comment]
[Scarlet Diversions] quests where you must take Flame in A Bottle from the box. The box is not clickable. Is this a commonly known issue?

**Comment by twowTurtReynolds** [comment]
![image](https://github.com/slowtorta/turtlewow-bug-tracker/assets/151180101/0226fbf5-ea88-4a12-be95-cf1d02d907bd)
Works fine.
