### ISSUE TITLE
male high elf character melee special attack animation with a 2-handed weapon seems bugged. 

### ISSUE THREAD

**Issue by szl910104** [slowtorta/turtlewow-bug-tracker#3665]
**Please, provide a clear description what the bug is:**
male high elf character melee special attack animation with a 2-handed weapon is bugged. the 2H weapon stays at right hand during the whole animation, while it's supposed to switch between left and right hand. tested on a lvl 8 high elf paladin using crusader strike lvl 1.
**Steps to reproduce the behavior with as much detail as possible:**

1.find a male high elf character who can perform any kind of melee special attack, eg a worrior's heroic strike or a paladin's crusader strike.
2. equip him with a 2-handed weapon.
3. use melee ability agianst a target, and see the animation.

**IDs of affected creatures, items, quests or spells with a link to the relevant page:**

NPC: https://database.turtle-wow.org/?npc=
Item: https://database.turtle-wow.org/?item=
Quest: https://database.turtle-wow.org/?quest=
tested on a lvl 8 high elf paladin using crusader strike lvl 1:
Spell: https://database.turtle-wow.org/?spell=2537          
Object: https://database.turtle-wow.org/?object=

**Expected behavior. Describe how it should work:**
the 2H weapon it's supposed to switch between left and right hand after the fancy flipping cut during the special attack animation.

**Comment by twowTurtReynolds** [comment]
Me and the modeling team fail to understand exactly what is wrong. Can you take detailed footage of the part that looks wrong, and how on the TBC blood elf model it looks correct? That's the one we're using and it should be 1:1.

**Comment by Muigin** [comment]
Fixed in 1.17.1
