### ISSUE TITLE
Priest shadow spells resisted.

### ISSUE THREAD

**Issue by Valquirion** [slowtorta/turtlewow-bug-tracker#3669]
**Please, provide a clear description what the bug is:**

I know Grounding Totem can be really weird sometimes but Horde are resisting too much my shadow spells even with 5 points in shadow focus, may be because of resisting blackout but the problem is that if blackout is resisted the spell also does not apply damage, example: if my shadow word pain procs blackout and gets resisted it doesnt put the dot on the enemy, its a full resisted spell that does nothing and i need to recast again. I tried to be clear as much as possible.

**Steps to reproduce the behavior with as much detail as possible:**

1.Cast priest shadow spells with blackout talent on orcs (because of racial can resist more blackout proc).
2.See if the enemy full resist the damage when blackout is resisted.

**IDs of affected creatures, items, quests or spells with a link to the relevant page:**

NPC: https://database.turtle-wow.org/?npc=
Item: https://database.turtle-wow.org/?item=
Quest: https://database.turtle-wow.org/?quest=
Spell: https://database.turtle-wow.org/?spell=
Object: https://database.turtle-wow.org/?object=

**Expected behavior. Describe how it should work:**

Shadow spells damage may not be full resisted when blackout is resisted.

**Comment by balakethelock** [comment]
Why don't you test it out with an orc friend, get in a duel and spam rank 1 mindflays see what happens, also give your friend the 60+ shadow resist buff then test again.

**Comment by ratkosrb** [comment]
Blackout getting resisted does not impact the spell that proced it.
