### ISSUE TITLE
Entities clipping into ground when walking up slopes while exiting water 

### ISSUE THREAD

**Issue by Soulex23** [slowtorta/turtlewow-bug-tracker#367]
**Please, provide a clear description what the bug is:**
_Whenever there is a ground slope connected to water, and a mob walks out from it, it begins to clip through the ground in a stutter, or just going into it completely if the slope is steep enough. I have witnessed this occur with the Devilsaurs in Un'goro Crater, some of the Sea Sprays/Sea Elementals on the coast of Feralas, and a few of the Ogres in Feralas as well. Luckily I do not believe that players have it occur to them, though there may be a possibility._

**Steps to reproduce the behavior with as much detail as possible:**

_1. Procure a mob with a set path across water up a slope_
_2. Find a slope next to water, preferably one with corners in/against the water_ 
_3. Set the mob's path through the water then up the slope, perhaps directly on the vertices of the slope at the water's edge and/or at different angles up the slope._ 

**IDs of affected creatures, items, quests or spells with a link to the relevant page:**

NPC: https://database.turtle-wow.org/?npc=
Item: https://database.turtle-wow.org/?item=
Quest: https://database.turtle-wow.org/?quest=
Spell: https://database.turtle-wow.org/?spell=
Object: https://database.turtle-wow.org/?object=

**Expected behavior. Describe how it should work:**
_Once the mob moves up the slope, it should start clipping into the ground in some fashion, with more drastic effects depending on the angle of the slope._

**Comment by slowtorta** [comment]
Private servers cannot easily fix this kind of issue, sorry.
