### ISSUE TITLE
The quest The Raging Oceans Blue is not tagged as Elite (Group)

### ISSUE THREAD

**Issue by octav3k** [slowtorta/turtlewow-bug-tracker#3673]
**Please, provide a clear description what the bug is:**
The quest The Raging Oceans Blue is not tagged as Elite (Group).

**Steps to reproduce the behavior with as much detail as possible:**
1. Acquire the quest
2. Check its status
3. Find Fontenus, the elemental you're asked to kill and see that it's elite

**IDs of affected creatures, items, quests or spells with a link to the relevant page:**

NPC: https://database.turtle-wow.org/?npc=61046
Quest: https://database.turtle-wow.org/?quest=40628

**Expected behavior. Describe how it should work:**
The quest should be marked as Elite (Group).

**Comment by Gurky-Turtle** [comment]
fixed in the next update
