### ISSUE TITLE
Cenarion Circle rep gain from AQ20 is undertuned

### ISSUE THREAD

**Issue by balakethelock** [slowtorta/turtlewow-bug-tracker#3676]
**Please, provide a clear description what the bug is:**
Cenarion circle reputation gain from AQ20 is much less than it should be, this is because back in the early days of private servers, devs didn't have accurate numbers so relied on guesswork. Now we have the real numbers and it's shown that aq20 gave much better rep, so it should be changed to reflect that.

**Steps to reproduce the behavior with as much detail as possible:**

1. Enter AQ20 and kill mobs inside
2. See cenarion circle rep increase at a slower rate than it does on classic

**IDs of affected creatures, items, quests or spells with a link to the relevant page:**
NPC: big list of npcs

**Expected behavior. Describe how it should work:**

```
-- AQ20 second boss adds all give 5 reputation with Cenarion Circle.
INSERT INTO `creature_onkill_reputation` VALUES (15343, 0, 609, 0, 7, 0, 5, 0, 0, 0, 0); -- Qiraji Swarmguard
INSERT INTO `creature_onkill_reputation` VALUES (15385, 0, 609, 0, 7, 0, 5, 0, 0, 0, 0); -- Colonel Zerran
INSERT INTO `creature_onkill_reputation` VALUES (15386, 0, 609, 0, 7, 0, 5, 0, 0, 0, 0); -- Major Yeggeth
INSERT INTO `creature_onkill_reputation` VALUES (15387, 0, 609, 0, 7, 0, 5, 0, 0, 0, 0); -- Qiraji Warrior
INSERT INTO `creature_onkill_reputation` VALUES (15388, 0, 609, 0, 7, 0, 5, 0, 0, 0, 0); -- Major Pakkon
INSERT INTO `creature_onkill_reputation` VALUES (15389, 0, 609, 0, 7, 0, 5, 0, 0, 0, 0); -- Captain Drenn
INSERT INTO `creature_onkill_reputation` VALUES (15390, 0, 609, 0, 7, 0, 5, 0, 0, 0, 0); -- Captain Xurrem
INSERT INTO `creature_onkill_reputation` VALUES (15391, 0, 609, 0, 7, 0, 5, 0, 0, 0, 0); -- Captain Qeez
INSERT INTO `creature_onkill_reputation` VALUES (15392, 0, 609, 0, 7, 0, 5, 0, 0, 0, 0); -- Captain Tuubid

-- All mobs that currently give 3 reputation are AQ20 trash mobs. All of them except Flesh Hunter (15335) should give 5 reputation.
UPDATE `creature_onkill_reputation` SET `RewOnKillRepValue1`=5 WHERE `RewOnKillRepFaction1`=609 && `RewOnKillRepValue1`=3 && `creature_id`!=15335;
-- Affected IDS are 15168, 15318, 15319, 15320, 15323, 15324, 15325, 15327, 15333, 15336, 15338, 15461, 15462, 15505, 15521, 15537, 15538, 15555, 15934

-- AQ20 Bosses give too much reputation except Rajaxx who doesn't give any. Ossirian should give 100, all else give 50.
UPDATE `creature_onkill_reputation` SET `RewOnKillRepValue2`=100 WHERE `creature_id`=15339 AND `patch`=0; -- Ossirian
UPDATE `creature_onkill_reputation` SET `RewOnKillRepValue2`=50 WHERE `creature_id`=15348 AND `patch`=0; -- Kurinnaxx
UPDATE `creature_onkill_reputation` SET `RewOnKillRepValue2`=50 WHERE `creature_id`=15370 AND `patch`=0; -- Buru the Gorger
UPDATE `creature_onkill_reputation` SET `RewOnKillRepValue2`=50 WHERE `creature_id`=15340 AND `patch`=0; -- Moam
UPDATE `creature_onkill_reputation` SET `RewOnKillRepValue2`=50 WHERE `creature_id`=15369 AND `patch`=0; -- Ayamiss the Hunter
UPDATE `creature_onkill_reputation` SET `RewOnKillRepFaction2`=609, `MaxStanding2`=7, `RewOnKillRepValue2`=50 WHERE `creature_id`=15341 AND `patch`=0; -- General Rajaxx

-- These ones are AQ40, not AQ20, but still undertuned rep that should be fixed; twin emperors and trash mobs in their room give reputation with Cenarion Circle.
UPDATE `creature_onkill_reputation` SET `RewOnKillRepFaction2`=609, `MaxStanding2`=7, `RewOnKillRepValue2`=33 WHERE `creature_id`=15275; -- Emperor Vek'nilash
UPDATE `creature_onkill_reputation` SET `RewOnKillRepFaction2`=609, `MaxStanding2`=7, `RewOnKillRepValue2`=33 WHERE `creature_id`=15276; -- Emperor Vek'lor
INSERT INTO `creature_onkill_reputation` VALUES (15316, 0, 609, 0, 7, 0, 5, 0, 0, 0, 0); -- Qiraji Scarab
INSERT INTO `creature_onkill_reputation` VALUES (15317, 0, 609, 0, 7, 0, 5, 0, 0, 0, 0); -- Qiraji Scorpion
```
All of these can be confirmed in classic wowhead.

**Comment by Zebouski** [comment]
I would ask @geojak why they have downthumbed this post

as far as I see it this is an objective blizzlike deviation, and one that hurts new players gearing up. Only those geared enough to make it into aq40 get to elude this bug, and that's not really okay.

**Comment by davmon01** [comment]
Rep grinds should not be defined by their difficulty but rather by their rewards / utility. All rep grinds are easy, it's just a time sink. Nothing more. But AQ20 drops tokens which have specific rep requirements. It's not unreasonable to expect that doing the activity which gave you those tokens would also provide the means with which to use those tokens. Scarabs, Idols, and rep in this case.

**Comment by Ducky-twow** [comment]
Rep grinds should not be defined by their difficulty but rather by their rewards / utility. All rep grinds are easy, it's just a time sink. Nothing more. But AQ20 drops tokens which have specific rep requirements. It's not unreasonable to expect that doing the activity which gave you those tokens would also provide the means with which to use those tokens. Scarabs, Idols, and rep in this case.

**Comment by Zebouski** [comment]
Me personally i found it extremely difficult to get exalted until i stpeped into aq40 and wooop my rep went right up. I did maybe 10-15 aq20 runs in 2021 on zaas. Only got into revered. And only today did i learn that i was playing with bugged not-blizzlike rep.

Regardless, even if rep is completely trivialized, _which this wont do,_ Twilight texts will always carry inherent value due to the quest that turns it into consume goodie bags.

and even if they didn't... a horribly inbalanced rep grind that means getting exalted for the weapon, isnt something you can really easily do until aq40.... to access a MC ilvl weapon that late.... yeah it makes for this part of the game being a broken experience. The fact is that, who cares about the twilight text market. The damage this bug does is significant.

**Comment by Gurky-Turtle** [comment]
fix will be applied in the next server update.
