### ISSUE TITLE
"Get me out of here!" Bugged Quest

### ISSUE THREAD

**Issue by Quackmandan** [slowtorta/turtlewow-bug-tracker#3679]
**Please, provide a clear description what the bug is:**
End step of the escort spawns double the expected mobs when leaving the valley of spears.  It spawns 4 Maraudine Wranglers and 4 Maraudine Bonepaws.  At most, half of this should be spawning for a lvl 39 "soloable" escort quest.  Maraudine Wranglers are also incorrectly scripted.  They use a 10 second disarm every 15 seconds (leaving only 5 seconds where you aren't disarmed).  Ontop of that, they are using an 10 second net every 15-17 seconds.  This encounter leaves any melee class effectively PERMANENTLY disarmed.
**Steps to reproduce the behavior with as much detail as possible:**

1. Start  "Get me out of Here!" escort quest in valley of spears in desolace.
2. Clear initial pack that spawns from the quest.
3. The second pack (described above) double spawns and comes charging out of the exit of the valley of spears.

**IDs of affected creatures, items, quests or spells with a link to the relevant page:**
https://database.turtle-wow.org/?npc=4655#abilities
https://database.turtle-wow.org/?npc=4660
https://database.turtle-wow.org/?quest=6132

NPC: https://database.turtle-wow.org/?npc=
Item: https://database.turtle-wow.org/?item=
Quest: https://database.turtle-wow.org/?quest=
Spell: https://database.turtle-wow.org/?spell=
Object: https://database.turtle-wow.org/?object=

**Expected behavior. Describe how it should work:**
Exiting the Valley of Spears, 4 TOTAL mobs should spawn (two wranglers and two bonepaws).  The disarm/net rates either have to be heavily retuned (cast way less often) or need some form of diminishing return.

**Comment by octav3k** [comment]
When I did it, it only spawned 3 centaur and 3 hyenas, which is very close to how it is in Classic and how it probably was in vanilla.
Here's a clip from a video of a (somewhat) famous youtuber warning about the quest and you can see in the video the amount of mobs that spawn + he speaks about how difficult of a time melee have: https://youtube.com/clip/UgkxIrRElvlNOY8iUppG5qbIAT_TaDKCQnLK

The only real difference I see between the way it works on Turtle and Classic is that the final pack automatically aggros on the player doing the quest, which is inconsistent with the previous wave, but was probably an intended change to prevent mobs spawning randomly with no target outside of that centaur area and killing someone walking by.
I'd say this is all working as intended.
