### ISSUE TITLE
Hero of the Frostwolf bug

### ISSUE THREAD

**Issue by Rowrow213** [slowtorta/turtlewow-bug-tracker#3681]
**Please, provide a clear description what the bug is:**
Once you finish the quest https://www.wowhead.com/classic/quest=7142/the-battle-for-alterac on Horde side you should be able to get the quest https://www.wowhead.com/classic/quest=8272/hero-of-the-frostwolf In order to get the rewards, one of the, the https://www.wowhead.com/classic/item=19108/wand-of-biting-cold but you can't, with the wand only coming from two quests https://database.turtle-wow.org/?quest=8272 https://database.turtle-wow.org/?quest=7202 to kill Korrak the Bloodrager, which nobody does in this server.

Here are the links to both the classic version of the wand and the turtle wow version, note how the Hero fo the Frostwolf quest in classic only has you kill Vannadar as a prerequisit.
https://www.wowhead.com/classic/item=19108/wand-of-biting-cold
https://database.turtle-wow.org/?item=19108
**Steps to reproduce the behavior with as much detail as possible:**

1.
2. 
3. 

**IDs of affected creatures, items, quests or spells with a link to the relevant page:**

NPC: https://database.turtle-wow.org/?npc=
Item: https://database.turtle-wow.org/?item=
Quest: https://database.turtle-wow.org/?quest=
Spell: https://database.turtle-wow.org/?spell=
Object: https://database.turtle-wow.org/?object=

**Expected behavior. Describe how it should work:**
Please fix the quests so you can get the wand and the rest of the rewards from winning AV, instead of killing a raid boss nobody ever kills. It's already hard enough to get those as Horde.

**Comment by ratkosrb** [comment]
This is not a bug. Turtle uses the original version of AV, not the 1.12 version, and in it those rewards were for killing Korrak, not for winning the battleground. It's unfortunate that people ignore Korrak as you say. I have reduced his health and increased the amount of loot that drops from him, to hopefully convince people to start killing him.
