### ISSUE TITLE
Neretzek, The Blood Drinker - not scaling with spell power

### ISSUE THREAD

**Issue by mayhemz7** [slowtorta/turtlewow-bug-tracker#3682]
**Neretzek, The Blood Drinker - proc not scaling with spell power!**

Items with similar proc that scales with spell dmg -

Scythe of the Harvest - https://database.turtle-wow.org/?item=60787
Ancient Hakkari Manslayer - https://database.turtle-wow.org/?item=19852
Wraith Scythe - https://database.turtle-wow.org/?item=11920
Fist of the Damned - https://database.turtle-wow.org/?item=10804

And this item doesnt scales but have the same proc -

Neretzek, The Blood Drinker - https://database.turtle-wow.org/?item=21856
Corrupted Ashbringer - https://database.turtle-wow.org/?item=22691

Why it doesnt work? And when its gonna be fixed so i can use Neretzek or Ashbringer on my SPaladin build?

**Comment by ratkosrb** [comment]
When there is no comment, it means the issue is fixed internally and will go live soon.
