### ISSUE TITLE
Dark Edge of Insanity procs too frequently

### ISSUE THREAD

**Issue by JanusMD** [slowtorta/turtlewow-bug-tracker#3684]
Dark Edge of Insanity disorient effect proc rate is way too high. 

**Steps to reproduce the behavior with as much detail as possible:**

1. Disorient effect procs too often
2. Can have another proc while the effect of the previous one has not yet worn off 
3. Can nearly stunlock targets to death with super long disorient chains

**IDs of affected creatures, items, quests or spells with a link to the relevant page:**

Item: https://database.turtle-wow.org/?item=21134

**Expected behavior. Describe how it should work:**
The proc should occur sparingly to make sure the item is not totally overpowered.

**Comment by JanusMD** [comment]
No, this weapon effect is unique and does not break on damage despite being called a disorient.

**Comment by Zebouski** [comment]
OP it's your responsibility to find out the classic PPM, and to figure out the PPM here. If there isn't a classic disrepnancy, then this is a rebalancing post whihc belongs on the suggestions forum

**Comment by JanusMD** [comment]
Look, they can either fix this bug if they want to or leave it like this if they prefer. What you ask is impossible for me as player and a 5 minute job for a dev (hit something with the axe in a test enviro).

**Comment by Zebouski** [comment]
Well moreso finding the classic PPM is your job. Yes it's easy for a turtle dev to confirm and adjust or not the turtle ppm.

**Comment by JanusMD** [comment]
If you are not a dev, please get out of my thread

**Comment by afizzler** [comment]
it’s working as intended

**Comment by Dragunovi** [comment]
Applied the PPM again just to be safe but I pretty much doubt there's an issue.
