### ISSUE TITLE
Devilsaur set not giving set bonuses

### ISSUE THREAD

**Issue by Queffear** [slowtorta/turtlewow-bug-tracker#3685]
**Please, provide a clear description what the bug is:**
After equipping Devilsaur Gauntlets and Devilsaur Leggins, I do not get the set bonus for 2% hit.

**Steps to reproduce the behavior with as much detail as possible:**

1. I just equipped those items and nobus set is not counting.
2. This might have occured after the transmog. I did not notice if this was before the transmog.
3. I have deleted WDB and WTF folder to see if I can solve the issue by this, it did not help.

**IDs of affected creatures, items, quests or spells with a link to the relevant page:**

https://database.turtle-wow.org/?item=15063
https://database.turtle-wow.org/?item=15062

**Expected behavior. Describe how it should work:**

After equpping both items the wearer should receive 2% hit as a set bonus.

**Comment by Queffear** [comment]
EDIT: The issue is occuring when the items are transmogged. If you reset the transmog, it works as intended. However after applying the transmog again, it does not work.

**Comment by ahansen87** [comment]
This is a visual glitch.  While the set bonus text will remain unhighlighted, the actual bonus will still be applied to your character.
