### ISSUE TITLE
[Hunter] Items that increase pet damage don't stack

### ISSUE THREAD

**Issue by kravis** [slowtorta/turtlewow-bug-tracker#3688]
**Please, provide a clear description what the bug is:**
Items that increase pet damage don't stack, I spent 1000g getting Breastplate of Beast Mastery and doing the T0.5 quest chain to get the Beastmaster's Boots 

**Steps to reproduce the behavior with as much detail as possible:**

1. Equip Breastplate of Beast Mastery or Beastmaster's Boots and your pets DPS will increase
2. Equip both at the same time and there won't be an increase

**IDs of affected creatures, items, quests or spells with a link to the relevant page:**

Item: 
https://database.turtle-wow.org/?item=60784
https://database.turtle-wow.org/?item=22061
I don't have Charm of Dark Domination but I'm pretty sure it doesn't stack either https://database.turtle-wow.org/?item=83233

Spell: https://database.turtle-wow.org/?spell=27206

**Expected behavior. Describe how it should work:**
If you equip Breastplate of Beast Mastery, Beastmaster's Boots, and Charm of Dark Domination your pet should get a 9% increased damage total. However I think all these items are tied to this spell(Increased Pet Damage +3%: https://database.turtle-wow.org/?spell=27206) so only one item works at a time.

![1](https://github.com/slowtorta/turtlewow-bug-tracker/assets/2722656/05092708-8dd3-4e67-b0a0-b45ebc60134b)
![2](https://github.com/slowtorta/turtlewow-bug-tracker/assets/2722656/72df7d07-7ad7-4eed-a76b-83d3f1ca20f1)
![3](https://github.com/slowtorta/turtlewow-bug-tracker/assets/2722656/b9770966-d6ba-4c35-85a2-ea735083b1c1)
![4](https://github.com/slowtorta/turtlewow-bug-tracker/assets/2722656/4615282f-b766-4419-a7c0-4fb0f3db3af6)

**Comment by Dragunovi** [comment]
Noted this down for our client tracker as the effect needs a custom spell that's different from the original pet buff effects, should be fixed in 1.16.6.
