### ISSUE TITLE
Some of the polearms are upside down (on Undead Male Warrior at least)

### ISSUE THREAD

**Issue by ahungry** [slowtorta/turtlewow-bug-tracker#3689]
**Please, provide a clear description what the bug is:**

Certain polearm class weapons are oriented upside down, such that the pointy end is on the character's butt, instead of up in the air.

Two examples:

https://database.turtle-wow.org/?item=60787 (this one looks especially bad)
https://database.turtle-wow.org/?item=19874

**Steps to reproduce the behavior with as much detail as possible:**

1. Equip the item
2. Observe the orientation
3. Laugh at how silly it looks

**IDs of affected creatures, items, quests or spells with a link to the relevant page:**

Item: https://database.turtle-wow.org/?item=60787
Item: https://database.turtle-wow.org/?item=19874

**Expected behavior. Describe how it should work:**

Item should be right side up.  Curiously (or perhaps not so much) if you transmog a properly oriented item (https://database.turtle-wow.org/?item=80638) into one of the afflicted items, it appears as you'd expect (a scythe that looks similar to the warlock one - the reaping/blade end at the top above the character's head, vs at their butt).

I'm sure there are other polearm based weapons that have a flipped orientation and need a similar correction (there are only a handful of polearms in the game, but I don't have a way to test in the dressing room the sheathed/back orientation look of the rest).

**Comment by Dragunovi** [comment]
Should be fixed in the next scheduled server restart.
