### ISSUE TITLE
Voidwalker Suffering Ability

### ISSUE THREAD

**Issue by ScubaV** [slowtorta/turtlewow-bug-tracker#369]
The warlock's voidwalker suffering ability (AOE threat ability) does not appear to function properly.  Example: Was doing https://database.turtle-wow.org/?quest=1447 and aggroed three mobs.  Only one had player damage and all were in melee range of player and voidwalker.  After using suffering, none aggroed onto the voidwalker.

**Steps to reproduce the behavior with as much detail as possible:**

1.  Aggro multiple mobs with the player character.
2. Use suffering ability in melee range of VW.
3. Watch as mob is not taunted.

**IDs of affected creatures, items, quests or spells with a link to the relevant page:**

NPC: https://database.turtle-wow.org/?npc=
Item: https://database.turtle-wow.org/?item=
Quest: https://database.turtle-wow.org/?quest=
Spell: https://database.turtle-wow.org/?spell=
Object: https://database.turtle-wow.org/?object=

Suffering should taunt mobs or at least cause enough threat to aggro mobs that have not received any player damage.

**Comment by jameyboor** [comment]
Fixed on next update.
