### ISSUE TITLE
Silver Sun mine: Enemies rise and clip through the ceiling

### ISSUE THREAD

**Issue by AeternusDoleo** [slowtorta/turtlewow-bug-tracker#3690]
**Please, provide a clear description what the bug is:**
In the Silver Sun mine in Alah'Thalas, there are a number of 'Malfunctioning Arcane Construct' spawning. These used to stick to the cave floor, but now end up floating up in small shocks and then clip through the ceiling, eventually ending up outside of the mine on the mountainside.

**Steps to reproduce the behavior with as much detail as possible:**
1. Go into the silver sun mine
2. Wait for the enemies to spawn (might need to kill the ones on the hillside so they respawn)
3. Admire the levitation and selective immaterial nature of the golems as they rise through the cave ceiling.

**IDs of affected creatures, items, quests or spells with a link to the relevant page:**
Malfunctioning Arcane Construct: Display ID: 18022

NPC: https://database.turtle-wow.org/?npc=80241

**Expected behavior. Describe how it should work:**
These constructs should be an obstacle for players on a repeatable reputation quest for the Sun Elf faction, and should stay in the mine.

**Comment by slowtorta** [comment]
Fixed in the next patch.
