### ISSUE TITLE
Ressurection in BG's, especialy AV

### ISSUE THREAD

**Issue by lazarce** [slowtorta/turtlewow-bug-tracker#3691]
**Please, provide a clear description what the bug is:**

**Steps to reproduce the behaviour with as much detail as possible:**

1. The game wont resurrect me in AV in alliance base graveyard, take about 2-4 resurrection timers
2. I think i figured it out you cant resurrect if you hold right mouse button and try to look around while dead
3. I'm not sure if this is the fix but it shouldn't happen even if you hold right mouse button
4. I have experience in coding and you should hire me to help you fixing bugs, I would do it for free of course.

**IDs of affected creatures, items, quests or spells with a link to the relevant page:**

NPC: https://database.turtle-wow.org/?npc=
Item: https://database.turtle-wow.org/?item=
Quest: https://database.turtle-wow.org/?quest=
Spell: https://database.turtle-wow.org/?spell=
Object: https://database.turtle-wow.org/?object=

**Expected behavior. Describe how it should work:**
I should resurrect

**Comment by ratkosrb** [comment]
This should be fixed already.
