### ISSUE TITLE
Unable to Disenchant [Gnomish Universal Remote]

### ISSUE THREAD

**Issue by syrathegreat** [slowtorta/turtlewow-bug-tracker#3692]
**Please, provide a clear description what the bug is:**
Similar to https://github.com/slowtorta/turtlewow-bug-tracker/issues/3560, [Gnomish Universal Remote] cannot be disenchanted, despite it being an Uncommon (Green) item. This was still replicated after clearing WDB folder. Similar to the previous issue, [Gnomish Universal Remote] is perhaps missing a disenchant ID?

**Steps to reproduce the behavior with as much detail as possible:**

1. Craft [Gnomish Universal Remote] Trinket item.
2. Attempt to disenchant said item.
3. Should get a warning "Item cannot be disenchanted"

**IDs of affected creatures, items, quests or spells with a link to the relevant page:**

https://database.turtle-wow.org/?item=7506
https://database.turtle-wow.org/?spell=13262

**Expected behavior. Describe how it should work:**

Item should be disenchanted successfully like all other Uncommon (Green) items.

**Comment by slowtorta** [comment]
This item isn't supposed to be disenchantable. https://www.wowhead.com/classic/item=7506/gnomish-universal-remote

**Comment by syrathegreat** [comment]
@slowtorta is there any reason why this shouldn't be disenchantable? The same has been the case with other green+ items inconsistently missing disenchant IDs - seems more like an oversight by Blizzard since disenchanting is designed to be universal based on rarity: https://www.wowhead.com/classic/spell=13262/disenchant
