### ISSUE TITLE
"All Along the Watchtowers" bug

### ISSUE THREAD

**Issue by hyakutaroichimunji** [slowtorta/turtlewow-bug-tracker#3694]
**The quest is supposed to use the quest item "Beacon Torch" on specific grids on Andorhal. I am able to use the Beacon Torch on other grids except on the "Tower Three" grid.**

**Steps to reproduce the behavior with as much detail as possible:**

1. I am currently not in raid and I have repeatedly retaken the quest to see if it unbugs it. It did not.
2. The quest item is supposed to cast a spell for about 5 secs to trigger the quest prerequisite. I didn't even get a single cast on Tower Three. 
3. The cast did trigger on other towers.

**IDs of affected creatures, items, quests or spells with a link to the relevant page:**

NPC: None involved.
Item: https://database.turtle-wow.org/?item=12815
Quest: https://database.turtle-wow.org/?quest=5098
Spell: https://database.turtle-wow.org/?spell=17016
Object: None involved since the bug in question is a specific area/grid.

**The Beacon Torch should start a 5-sec cast spell when in the correct quest zone. After the cast, it prompts a burn effect on the corresponding tower and quest prerequisite is achieved. This is done on 4 Towers in Andorhal**
![questbug](https://github.com/slowtorta/turtlewow-bug-tracker/assets/38785714/0cb597ac-11f3-4da6-b1a8-e5ada647205f)
Pic-related: My Questie addon is registered an "Unknown" objective where the "All Along the Watchtowers" quest objectives are.

**Comment by Gurky-Turtle** [comment]
Just tested this, if you drop each one in the doorway it will trigger about 1-3 seconds after you drop it in the door way. I cannot reproduce the trigger not working.
