### ISSUE TITLE
Shaman Totems which buff party don't work in parties

### ISSUE THREAD

**Issue by AtomicTyper** [slowtorta/turtlewow-bug-tracker#3697]
**Please, provide a clear description what the bug is:**
When I am in a party as a shaman, my totems which give buffs (e.g. strength of earth, mana spring) don't work. The totems of other shamans also don't work. Another shaman in the group deleted his WDB folder and after that, all totems work again, his and mine.

**Steps to reproduce the behavior with as much detail as possible:**

1. Be a shaman
2. Enter a party
3. Place a buff totem like strength of earth totem

**Expected behavior. Describe how it should work:**
Shamans enter a party and their party-wide buff totems

**Comment by AtomicTyper** [comment]
Alright the totems don't work for me only in parties. It is likely that some addons create this problem, I try to find out which one does this.

**Comment by balakethelock** [comment]
It's possibly because of some members being pvp flagged and others no. Not an addon.

**Comment by AtomicTyper** [comment]
Yes you are right! I have warmode on. If I manually flag myself with /pvp everything works.
