### ISSUE TITLE
quest "redemption" us bugged

### ISSUE THREAD

**Issue by Leinadkat** [slowtorta/turtlewow-bug-tracker#37]
By opening this Issue, I admit to having done the pertinent research using sources from Vanilla (preferably) or Classic. I also understand that sources from other private servers are not acceptable.

**Current behavior**: you start the quest and the npc just stands there, occasionaly doing the "talking" emote, but no text appears. i have deleted my WDB folder but nothing changes

**Expected behavior**: he should start talking and prompting the player to respond

**Proofs**:https://classicdb.ch/?quest=5742 
![Screenshot (311)](https://user-images.githubusercontent.com/85810009/121806655-04360b00-cc51-11eb-9e8a-6c87a2a9b218.png)

**Steps to reproduce**:

1. start the quest
2. 
3.

**Comment by CosminPOP** [comment]
as the quest says, sit and listen/talk
/sit and try again

**Comment by nonameform** [comment]
Been there. You do actually need to sit like mentioned above. Suddenly actual roleplay :)

**Comment by Leinadkat** [comment]
ok thanks
