### ISSUE TITLE
[Naxxramas] Kel'thuzad Frost Blast should be 4 ticks, not 5 ticks.

### ISSUE THREAD

**Issue by Velite12** [slowtorta/turtlewow-bug-tracker#370]
**Please, provide a clear description what the bug is:**

Kel'thuzad Frost Blast should be 4 ticks, not 5 ticks. It is currently 5 Ticks of 24-28% of the target's total hp in damage and it will always kill players.

![image](https://user-images.githubusercontent.com/45871932/136714261-aba4a92e-8746-4d17-86d4-e6672c9d2db5.png)

**Steps to reproduce the behavior with as much detail as possible:**

1. Do the Kel'thuzad fight until phase 2
2. Get Frost Blast and get healed
3. You will take 5 ticks of damage, not 4

**IDs of affected creatures, items, quests or spells with a link to the relevant page:**

NPC: https://database.turtle-wow.org/?npc=
Item: https://database.turtle-wow.org/?item=
Quest: https://database.turtle-wow.org/?quest=
Spell: https://database.turtle-wow.org/?spell=27808
Object: https://database.turtle-wow.org/?object=

**Expected behavior. Describe how it should work:**

https://youtu.be/6BIuoR3mt7U?t=615

Take a look at Verac, Pomfer, and Slanderer. Notice that they each take 24-28% ticks 4 times, with a 1 sec delay when the spell first lands. It only ticks 4 times, not 5.

![image](https://user-images.githubusercontent.com/45871932/136714335-70731d42-182d-4535-910c-2ecb9364c4bc.png)

In fact, Verac manages to survive without getting any healing.

https://vanilla.warcraftlogs.com/reports/WVgw37kjAL2MQv1F#fight=123&type=damage-taken&target=291&ability=29879

**Comment by slowtorta** [comment]
It was adjusted in a different way:
•  Fixed a bug where Kel Thuzad's Frost Blast would tick for 130% of total HP instead of the intended 105%.
