### ISSUE TITLE
Unable to disenchant [Sentinel's Pauldrons]

### ISSUE THREAD

**Issue by syrathegreat** [slowtorta/turtlewow-bug-tracker#3700]
**Please, provide a clear description what the bug is:**
Similar to https://github.com/slowtorta/turtlewow-bug-tracker/issues/3560, [Sentinel's Pauldrons] cannot be disenchanted, despite it being an Uncommon (Green) item. This was still replicated after clearing WDB folder. Similar to the previous issue, [Sentinel's Pauldrons] is perhaps missing a disenchant ID? This may extend to the other Darnassus reputation items, however I have not yet checked myself.

**Steps to reproduce the behavior with as much detail as possible:**

1. Purchase [Sentinel's Pauldrons] from the Darnassus reputation vendor upon reaching Honored.
2. Attempt to disenchant said item.
3. Should get a warning "Item cannot be disenchanted"

**IDs of affected creatures, items, quests or spells with a link to the relevant page:**

https://database.turtle-wow.org/?item=60751
https://database.turtle-wow.org/?spell=13262

**Expected behavior. Describe how it should work:**

Item should be disenchanted successfully like all other Uncommon (Green) items as per the spell description, and as evidenced by even items missing disenchant ID's in Blizzard Classic, gaining one in TBC, implying an oversight.

**Comment by Gurky-Turtle** [comment]
Should be fixed in the next update.
