### ISSUE TITLE
Transmog bug - phantom blade should be on your back when used as transmog

### ISSUE THREAD

**Issue by Trinax11** [slowtorta/turtlewow-bug-tracker#3701]
**Please, provide a clear description what the bug is:**
One handed swords that are on you back when used as transmog will be as your normal weapon by your side. 

For instance I have [Sharpened Silithid Femur] equiped and I transmog it with my Phantom Blade which is normally on your back. But when transmoged it is not on your back. 

**Steps to reproduce the behavior with as much detail as possible:**

1. Transmog normal sword with Phantom blade or other similar sword that is on your back. 
2. See it is on your side.
3. 

**IDs of affected creatures, items, quests or spells with a link to the relevant page:**

Item: https://database.turtle-wow.org/?item=7961

**Expected behavior. Describe how it should work:**
Transmoging sword with phantom blade should make the phantom blade put on your back not side.

**Comment by balakethelock** [comment]
The sheath placement is based on the original weapon you have equipped, not the transmog appearance you are using.
Means if sharpened silithid femur sheathes on the side, your weapon will always sheathe on the side even if you transmog to a weapon that sheathes on the back.

**Comment by Zebouski** [comment]
Ideally let us choose mounting location, but this entire report is more of a suggestion than a bug report.

**Comment by Trinax11** [comment]
Lets theoretically assume you want to transmog your swords into warglaives from azzinoth, do you really want them to be sheated on your side?  Some swords just belong on the back...

**Comment by Zebouski** [comment]
Then some weapons like Thunderfury look great sheathed on the side. OR some would disagree with me there and want it on their back.

It is better to leave this up to personal choice. Properly fixed, this would be a suggestion to add a feature to allow us to pick.

**Comment by Dragunovi** [comment]
Should be fixed with next restart, as in the sword should display when sheathed.
