### ISSUE TITLE
Cannot Make Forum Account

### ISSUE THREAD

**Issue by Quackmandan** [slowtorta/turtlewow-bug-tracker#3703]
**Please, provide a clear description what the bug is:**
The Website will not let me make a forum account despite having an active ingame account with the server.  Whenever I try to "login" to the forum, it tells me my info is wrong.  That same info lets me log in to the rest of the website.  If I choose, "forgot my password", option on the forum login screen, it sends me to a 404 error page
**Steps to reproduce the behavior with as much detail as possible:**

1.
2. 
3. 

**IDs of affected creatures, items, quests or spells with a link to the relevant page:**

NPC: https://database.turtle-wow.org/?npc=
Item: https://database.turtle-wow.org/?item=
Quest: https://database.turtle-wow.org/?quest=
Spell: https://database.turtle-wow.org/?spell=
Object: https://database.turtle-wow.org/?object=

**Expected behavior. Describe how it should work:**

**Comment by slowtorta** [comment]
You can see your forum account name in your Account Management page on our website.
