### ISSUE TITLE
Verog the Dervish Issue

### ISSUE THREAD

**Issue by Strangyone** [slowtorta/turtlewow-bug-tracker#3704]
In  location Barrens quest "Verog the Dervish". In this quest Verog must spawns near tent when you killing another centaur NPC's. On our server he doesn't swapns there. I wait two times about 30 mins. That issue have all another players.

1. Quest: https://database.turtle-wow.org/?quest=851
2. NPC: https://database.turtle-wow.org/?npc=3395

Thx for your wok this server are awesome) Have a nice day)

**Comment by Gurky-Turtle** [comment]
![image](https://github.com/slowtorta/turtlewow-bug-tracker/assets/90982783/10a5c134-fc8a-430c-b1c0-d5aee66eecf9)
He spawns, and you have to trigger the spawn by killing centars in the area.
