### ISSUE TITLE
Shadowfang Keep aggro bug

### ISSUE THREAD

**Issue by TeiBei** [slowtorta/turtlewow-bug-tracker#371]
**Please, provide a clear description what the bug is:**

Room in Shadowfang Keep with Wolf Master Nandos, all adds aggro at once

**Steps to reproduce the behavior with as much detail as possible:**

1. Do Shadowfang Keep, get to Wolf Master Nandos and aggro one of the adds
2. 
3. 

**IDs of affected creatures, items, quests or spells with a link to the relevant page:**

NPC: https://database.turtle-wow.org/?npc=
Item: https://database.turtle-wow.org/?item=
Quest: https://database.turtle-wow.org/?quest=
Spell: https://database.turtle-wow.org/?spell=
Object: https://database.turtle-wow.org/?object=

**Expected behavior. Describe how it should work:**

The adds should be aggroed separately in groups since theyre also spread out along the left and right sides of the room respectively, but instead all of them aggro simultaneously, creating a VERY difficult scenario that requires cheesing to complete

**Comment by slowtorta** [comment]
Sorry, this encounter is supposed to work like this, see the video from Classic: https://www.youtube.com/watch?v=PZsdCVCAcmc&t=1238s
