### ISSUE TITLE
Dalaran reputation hand-ins arent repeatable.

### ISSUE THREAD

**Issue by Thilass** [slowtorta/turtlewow-bug-tracker#3711]
Hey, appearently the Dalaran hand-in quests for rep gain, are non repeatable at the moment. The most possible reputation you can gain from other quests are about 2K rep into Honored atm. Rewards are starting from Revered.

Quests:
**NPC: Magus Palon** (ID: https://database.turtle-wow.org/?npc=61065 )
--Major Magical Fortifications--
https://database.turtle-wow.org/?quest=40711
--Medium Magical Fortifications--
https://database.turtle-wow.org/?quest=40710
--Minor Magical Fortifications--
https://database.turtle-wow.org/?quest=40709

Quest:
**NPC: Archmage Talyvanah** (ID: https://database.turtle-wow.org/?npc=61064 )
--The Nexus of Dalaran--
https://database.turtle-wow.org/?quest=40708

Theese quests should be repeatable, so we can earn Dalaran reputation, currently they can only be done once.
The Picture shows, that i handed them in, and i cant accept them again.
![image](https://github.com/slowtorta/turtlewow-bug-tracker/assets/136903637/cfe7034a-38a2-4071-b477-ac9c83401946)

**Comment by Gurky-Turtle** [comment]
closing due to duplicate
