### ISSUE TITLE
Soothsaying for Dummies not interactive

### ISSUE THREAD

**Issue by Kfxd** [slowtorta/turtlewow-bug-tracker#3714]
**Please, provide a clear description what the bug is:**
The book/item "Soothsaying for Dummies" is not interactive. The quest "show of your work" has been completed in order to choose my first specialization, then engineering was dropped and relearned, membership card has been deleted and WDB folder has been deleted.

**IDs of affected creatures, items, quests or spells with a link to the relevant page:**

NPC: https://database.turtle-wow.org/?npc=11811
Object: https://database.turtle-wow.org/?object=177226

**Expected behavior. Describe how it should work:**
After learning a specialization within a profession, competing the show off your work quest. You should be able to unlearn the profession, redo it at pick another specialization after using this book.
I have done this on several servers in the past and i am familiar with the steps taken.

**Comment by Gurky-Turtle** [comment]
https://github.com/slowtorta/turtlewow-bug-tracker/issues/520
