### ISSUE TITLE
PALADIN - HAMMER OF WRATH CRIT CHANCE BUG

### ISSUE THREAD

**Issue by xiaoxaxo** [slowtorta/turtlewow-bug-tracker#3716]
**PALADIN - Hammer of Wrath SPELL CRIT vs. MELEE CRIT CHANCE BUG:**

**Put on a set of melee crit gear, and you will see, hammer of wrath will almost never crit. However, if you start putting on some spell crit/INTELLECT, you will see that it will begin to start critting, A LOT MORE. This is abnormal behavior, hammer of wrath's crit chance is supposed to be based on melee crit % and not spell crit %. I am unsure if this is an intentional Turtle WoW feature, but I decided to report it, since it is quite a significant nerf to the Paladin class as a whole.**

1. -
2. -
3. -

**IDs of affected creatures, items, quests or spells with a link to the relevant page: READ THE COMMENTS FROM https://www.wowhead.com/classic/spell=24275/hammer-of-wrath#comments YOU WILL SEE MULTIPLE COMMENTS STATING IT IS BASED UPON MELEE CRIT CHANCE**

**Expected behavior: In original Vanilla WoW and Classic WoW, Hammer of Wrath's crit chance was always based upon your melee crit % and never on your spell crit %.**

**Comment by ratkosrb** [comment]
I cannot reproduce the issue. It is definitely using Melee crit, not Spell crit. Please look at the following tests.

When modifying my agility, which increases melee crit, it always crits.

https://github.com/slowtorta/turtlewow-bug-tracker/assets/35845488/99552643-0ff3-4a56-91a7-cdc01e9dbc9e

But when I modify my intellect instead, which gives spell crit, it does not crit.

https://github.com/slowtorta/turtlewow-bug-tracker/assets/35845488/3d6b6508-a5d9-455b-b6ab-c1c0d822d233

**Comment by Gurky-Turtle** [comment]
https://github.com/slowtorta/turtlewow-bug-tracker/issues/3254

**Comment by twowTurtReynolds** [comment]
![image](https://github.com/slowtorta/turtlewow-bug-tracker/assets/151180101/833fba3e-a1d3-450c-afc5-3685eaaf68e5)
Indeed, hammer of wrath uses meele crit.
![image](https://github.com/slowtorta/turtlewow-bug-tracker/assets/151180101/a8b3a27a-56d7-49cd-b40c-13df54294522)
