### ISSUE TITLE
Logouts in SM area result in teleport to last taxi node on login

### ISSUE THREAD

**Issue by azolom** [slowtorta/turtlewow-bug-tracker#3718]
**Please, provide a clear description what the bug is:**

Logging out inside the SM portal area or outside of SM in Tirisful Glades frequently (~ 1/2 or 1/3 times) results in being teleported to my last flight taxi destination upon login. I've been experiencing this for weeks. Last night, I logged out at 68,27 on the SM map (inside the area with several portals, essentially outside the GY portal). When I logged in, it said my character was in "Scarlet Monastery Library" on the character select screen, and after I selected my character and logged in I was at 43,85 in WPL (the Chillwind Camp flight node). 

**Steps to reproduce the behavior with as much detail as possible:**

I suspect this can happen to anyone logging out near SM, but this is the specific chain of events that tends to land me here: 

1. Fly to Chillwind Camp
2. Run to SM, enter a SM GY instance
3. Exit GY instance, logout nearby 
4. Login and find yourself in WPL?

**IDs of affected creatures, items, quests or spells with a link to the relevant page:**

N/A

**Expected behavior. Describe how it should work:**

I expect to login and be in the same location I logged out at.

**Comment by slowtorta** [comment]
Fixed in 1.16.6.
