### ISSUE TITLE
problem with the respawn time of this quest object

### ISSUE THREAD

**Issue by sniper-sin** [slowtorta/turtlewow-bug-tracker#3721]
**Please, provide a clear description what the bug is:**
After rebooting the server, there was a problem with the respawn time of the quest object.

**IDs of affected creatures, items, quests or spells with a link to the relevant page:**

Item: https://database.turtle-wow.org/?item=16313
Quest: https://database.turtle-wow.org/?quest=3361
Object: https://database.turtle-wow.org/?object=178084

**Expected behavior. Describe how it should work:**
The objects in this quest have a respawn time of 5 seconds, but only the Felix's Chest object has bug a respawn time of 5 to 10 minutes.

**Comment by vsevolodivanov289** [comment]
respawn time is 6min 15sec - there're queues of players to this quest's time

**Comment by Gurky-Turtle** [comment]
https://github.com/slowtorta/turtlewow-bug-tracker/issues/3735
