### ISSUE TITLE
high elves glyph master

### ISSUE THREAD

**Issue by iljajakush** [slowtorta/turtlewow-bug-tracker#3723]
**Please, provide a clear description what the bug is:**
In the database shows two times mulgore, and the absence of high elves in the zone. Glyph master missing
**Steps to reproduce the behavior with as much detail as possible:**

1.
2. 
3. 

**IDs of affected creatures, items, quests or spells with a link to the relevant page:**

NPC: https://database.turtle-wow.org/?npc=
Item: https://database.turtle-wow.org/?item=
Quest: https://database.turtle-wow.org/?quest=
Spell: https://database.turtle-wow.org/?spell=
Object: https://database.turtle-wow.org/?object=

**Expected behavior. Describe how it should work:**

**Comment by Gurky-Turtle** [comment]
In the future please add links to your bug https://database.turtle-wow.org/?npc=51546

**Comment by Gurky-Turtle** [comment]
It looks like this has been fixed the web database is just out of date currently
