### ISSUE TITLE
Bug report: Quest "They're In The Way!" wrong reward

### ISSUE THREAD

**Issue by Sdacm** [slowtorta/turtlewow-bug-tracker#3725]
**Please, provide a clear description what the bug is:**

Quest reward differed from what it said it was in the quest log and turtle wow database.
Reward was supposed to be a Silksand Cape but was 30 silver instead.
Here is a video of me delivering the quest and receiving 30 silver:

https://github.com/slowtorta/turtlewow-bug-tracker/assets/18186105/467c074c-ea27-4285-bdb8-54248bf29bf4

**Steps to reproduce the behavior with as much detail as possible:**

1. Accept Horde quest They're In The Way! in Hammerfall (Arathi Highlands)
2. Check the reward
3. Kill the 20 spiders as indicated by the quest
4. Deliver quest and compare the reward that was there when accepting/doing the quest to the actual reward you receive

**IDs of affected creatures, items, quests or spells with a link to the relevant page:**

NPC: https://database.turtle-wow.org/?npc=9555
Item: https://database.turtle-wow.org/?item=14420
Quest: https://database.turtle-wow.org/?quest=60132

**Expected behavior. Describe how it should work:**

Either the quest should say the reward is 30 silver or the player should actually receive Silksand Cape upon delivering the quest

*****

Thank you!
Ceu

**Comment by Gurky-Turtle** [comment]
This was changed on May 29th "Replace Quest 60132 Reward Item with Money" this is intended the web database just has not been updated to reflect this change yet.

**Comment by Sdacm** [comment]
@Gurky-Turtle sorry, but it was not just in the web database. When accepting the quest and also when opening the quest menu (before delivering the quest) it also mentions the cloak as the quest's reward. Unfortunately I could not get this on video, but this was the matter that led me to report this issue.
Thank you for your work.

**Comment by Gurky-Turtle** [comment]
I'll check it out but it could be a result of old wdb data as well lingering.
