### ISSUE TITLE
The balance of holy and shadow, Can't Turn IN!!!!!!!!!

### ISSUE THREAD

**Issue by dominicous** [slowtorta/turtlewow-bug-tracker#3726]
I Completed the balance of holy and shadow, and i CANT TURN IT IN. It says its completed, and when I talk to Eris Havenfire the red completed quest button is red and i can click it. it even makes the classic trumpet completed noise, Yet nothing happens. I've spent just about all of my gold on this it is driving me up a wall. I can't go through that stress again. I just want my staff.
**Steps to reproduce the behavior with as much detail as possible:**

I just cant turn the quest in. I press complete quest and nothing happens.

**IDs of affected creatures, items, quests or spells with a link to the relevant page:**

NPC: https://database.turtle-wow.org/?npc= [Eris Havenfire](https://database.turtle-wow.org/?npc=14494)
Item: https://database.turtle-wow.org/?item= https://database.turtle-wow.org/?quest=7622
Quest: https://database.turtle-wow.org/?quest= [The balance of holy and shadow](https://database.turtle-wow.org/?quest=7622)

**Expected behavior. Describe how it should work:**
I should press complete quest and get Splinter of Nordrassil to combine with the eye of shadow in my bag and the eye trinket to receive Benediction.

Forgot my name: Dominicous

**Comment by dominicous** [comment]
https://database.turtle-wow.org/?quest=7622

**Comment by Oolaatris** [comment]
You are cited in another report as having done this quest in a group which is not what the quest design is.  In fact if anyone helps the priest doing the quest or even gets close it's supposed to trigger The Cleaner to come and one shot everyone.  Doing it as a group completely trivializes the event.  You should be able to abandon the quest and pick it up again from Eris and do the quest yourself and get credit.

**Comment by Gurky-Turtle** [comment]
Only the priest to do the event will get completion credit for this quest.
