### ISSUE TITLE
Technician's Servoshield does not return magic damage

### ISSUE THREAD

**Issue by Konspaul** [slowtorta/turtlewow-bug-tracker#3729]
**Please, provide a clear description what the bug is:**
I believe Technician's Servoshield (from Razzle Longpipe) does not return magic damage. The combat log appear it as physical damage while the shield should return 1 arcane spell damage. Please check this.

**Steps to reproduce the behavior with as much detail as possible:**

1.
2. 
3. 

**IDs of affected creatures, items, quests or spells with a link to the relevant page:**

NPC: https://database.turtle-wow.org/?npc=
Item: https://database.turtle-wow.org/?item=
Quest: https://database.turtle-wow.org/?quest=
Spell: https://database.turtle-wow.org/?spell=
Object: https://database.turtle-wow.org/?object=

**Expected behavior. Describe how it should work:**

**Comment by Gurky-Turtle** [comment]
![image](https://github.com/slowtorta/turtlewow-bug-tracker/assets/90982783/ddfb03ec-4380-4a41-95cb-729cb001081f)
It works like thorns with the school of Arcane
