### ISSUE TITLE
Ironforge  - Stormwind third car of the tram went into the opossite direction and into a wall

### ISSUE THREAD

**Issue by Tinyfin-github** [slowtorta/turtlewow-bug-tracker#373]
Ironforge  - Stormwind third car of the tram went into the opossite direction and into a wall

https://user-images.githubusercontent.com/83077166/136943853-780a50c4-3160-4a5a-a930-6901bc1af183.mp4

**Comment by jameyboor** [comment]
Fixed on next update.
