### ISSUE TITLE
Imperial Plate Armor Set bonuses don't work with transmoged pieces

### ISSUE THREAD

**Issue by Scaryn** [slowtorta/turtlewow-bug-tracker#3730]
**Please, provide a clear description what the bug is:**

The armor set doesn't give set bonus when they are transmog into another skin. I have five piece of Imperial plate armor set and belt, shoulders and feet are transmoged into another skin items. I should have bonus +28 attack power but I don't have that, only +100 armor

**Steps to reproduce the behavior with as much detail as possible:**

1. Bought parts of the Imperial plate armor set from Auction House
2. Used Fashion Coins on Imperial Plate Belt, Imperial Plate Boots and Imperial Plate Shoulders
3. The 2nd set bonus don't count even that I reached number of piece of equiped items on me  

**IDs of affected creatures, items, quests or spells with a link to the relevant page:**

Item: 
Imperial Plate Belt - https://database.turtle-wow.org/?item=12424
Imperial Plate Boots - https://database.turtle-wow.org/?item=12426
Imperial Plate Shoulders - https://database.turtle-wow.org/?item=12428
Fashion Coin - https://database.turtle-wow.org/?item=51217

**Expected behavior. Describe how it should work:**

The set bonuses should work even with transmoged gear.  

Screenshots: 

![WoWScrnShot_061923_142810](https://github.com/slowtorta/turtlewow-bug-tracker/assets/137070231/9780093b-f065-4520-9df9-da6580327ffb)
![WoWScrnShot_061923_142812](https://github.com/slowtorta/turtlewow-bug-tracker/assets/137070231/94ee587b-a05b-49ba-8f4c-afcd7f8c3741)
![WoWScrnShot_061923_142808](https://github.com/slowtorta/turtlewow-bug-tracker/assets/137070231/11305054-3094-4372-ae50-5796dd416e45)

**Comment by Gurky-Turtle** [comment]
This is just a visual bug you still get the set bonus
