### ISSUE TITLE
High Elf's are unable to get more than 19399 Revered with Darnassus.

### ISSUE THREAD

**Issue by Rinsedd** [slowtorta/turtlewow-bug-tracker#3731]
**Gurky's Edit:**

**Please, provide a clear description what the bug is:**
High Elf's cannot further their reputation with Darnassus past 19399 Revered.

**Steps to reproduce the behavior with as much detail as possible:**

1. Hit 19399 reputation (Revered) with Darnassus
2. Notice you can no longer gain any further reputation for this faction.

**IDs of affected creatures, items, quests or spells with a link to the relevant page:**

NPC: https://database.turtle-wow.org/?npc=14725
Quest: https://database.turtle-wow.org/?quest=7801

**Expected behavior. Describe how it should work:**
High Elf's should be able to hit Exalted like everyone else. 

**Report before finding the issue:**

> **Please, provide a clear description what the bug is:**
> Character: Inserd
> Raedon Duskstriker, the alliance cloth quartermaster is not giving out rep upon completing "Additional Runecloth: Darnassus"
> 
> **Steps to reproduce the behavior with as much detail as possible:**
> 
> 1. Turn in Runecloth in Darnassus, no rep is given
> 2. Quit client deleted WDB, still no rep given
> 
> **IDs of affected creatures, items, quests or spells with a link to the relevant page:**
> 
> NPC: https://database.turtle-wow.org/?npc=14725
> Quest: https://database.turtle-wow.org/?quest=7801
> 
> **Expected behavior. Describe how it should work:**
> each turn in of Additional Runecloth: Darnassus should give 50 rep
> 
> Edit: I tried to turn in some morrowgrain, that yielded zero reputation aswell
> Edit 2: Tried Pristine Yeti Hide repeatable, no rep, game must think I am exalted yet I'm only revered.

**Comment by Rinsedd** [comment]
> ![image](https://user-images.githubusercontent.com/90982783/248849006-2696f7f0-5d15-456b-bf34-c6414eb60fc4.png) Cannot reproduce seems to give rep.

what should i do then? ive tried 2 tickets, really sucks being stuck at 19339 with this being the only city faction im missing :(

**Comment by Rinsedd** [comment]
heres a video
https://youtu.be/v07GSw_uUEE

**Comment by Gurky-Turtle** [comment]
Ah ill look into it again so what it looks like you are really high rep I wonder if the turn ins have a cap where it stops (which would be incorrect) ill check tomorrow and get back with you.

**Comment by Gurky-Turtle** [comment]
I think I found the issue, 
![image](https://github.com/slowtorta/turtlewow-bug-tracker/assets/90982783/31166e77-f74f-48e4-a430-44dc6aca88f4)

It looks like for some reason this is the max rep you can obtain will need to look into this but the quest isnt the issue.

**Comment by Lexiebean** [comment]
For what it's worth, it's a visual bug. You can still hit Exalted.

**Comment by Chokladaren** [comment]
> For what it's worth, it's a visual bug. You can still hit Exalted.

It doesn't seem to be entirely visual, as I can buy mounts which would indicate I'm exalted, but not the darnassus tabard

**Comment by Rinsedd** [comment]
nice findings Gurky thanks for ur work

**Comment by Lexiebean** [comment]
> It doesn't seem to be entirely visual, as I can buy mounts which would indicate I'm exalted, but not the darnassus tabard

![image](https://github.com/slowtorta/turtlewow-bug-tracker/assets/6937574/98be8161-a029-49fa-bd85-d9b36ae28104)

**Comment by Lexiebean** [comment]
> It doesn't seem to be entirely visual, as I can buy mounts which would indicate I'm exalted, but not the darnassus tabard

![image](https://github.com/slowtorta/turtlewow-bug-tracker/assets/6937574/e1a7cb7e-ffee-4e3a-804b-52ed7d50642b)

**Comment by Gurky-Turtle** [comment]
Should be fixed in 1.16.6
