### ISSUE TITLE
Reckoning Talent - Paladin

### ISSUE THREAD

**Issue by ranevian** [slowtorta/turtlewow-bug-tracker#3732]
**Please, provide a clear description what the bug is:**

Paladin protection spec Reckoning talent does not function as expected. Upon being crit, the paladin should be getting an extra attack off. The attack animation plays out for an extra attack and the combat log shows an extra attack occurring, but there is no damage associated with the extra attack. (Note: these crits received are not forced crits using /sit but, in fact, are proper crits from fighting enemies normally).

**Steps to reproduce the behavior with as much detail as possible:**

1. Talent into Reckoning as paladin
2. Get crit from an enemy creature to proc the effect
3. See attack animation play out but no damage to follow

**Expected behavior. Describe how it should work:**

Upon being critically hit, the paladin should have a free auto attack. Critical hits that are forced using /sit will not proc the Reckoning effect.

**Comment by twowTurtReynolds** [comment]
I wasn't able to replicate this. Please provide a video of the issue if it is still an issue.
