### ISSUE TITLE
Panther Hide Sack drop rate too low

### ISSUE THREAD

**Issue by balakethelock** [slowtorta/turtlewow-bug-tracker#3733]
**Please, provide a clear description what the bug is:**
Drop rate is 12%, should be 18%
**Steps to reproduce the behavior with as much detail as possible:**

1. Check database for its droprate

**IDs of affected creatures, items, quests or spells with a link to the relevant page:**

NPC: https://database.turtle-wow.org/?npc=14515
Item: https://database.turtle-wow.org/?item=19914

**Expected behavior. Describe how it should work:**
Should be 18% drop rate. Source:
https://www.wowhead.com/classic/item=19914/panther-hide-sack#dropped-by

**Comment by Gurky-Turtle** [comment]
Should be fixed next update
