### ISSUE TITLE
A bug(maybe) of the quest "Supplies We Need" or the item "Scarlet Crusade Insignia"

### ISSUE THREAD

**Issue by Heteroi** [slowtorta/turtlewow-bug-tracker#3734]
**Please, provide a clear description what the bug is:**
Hi,dear developer.I'm poor English.I have to use a translator to read and write.sorry for that.But that doesn't stop me from loving turtles WOW.
I finish the quest "Supplies We Need" and reward "Scarlet Crusade Insignia",but the item is not in my bag.It's disappeared.

**Steps to reproduce the behavior with as much detail as possible:**

1.I use "Illusion: Scarlet Crusade" and speak to Mavel Brightwood to take in the queset "Supplies We Need"
2. I cheak my bag didn't find "Scarlet Crusade Insignia"
3. I spoke to her again and got no information

**IDs of affected creatures, items, quests or spells with a link to the relevant page:**

NPC: https://database.turtle-wow.org/?npc=50677
Item: https://database.turtle-wow.org/?item=53005
Quest: https://database.turtle-wow.org/?quest=80711
Spell: https://database.turtle-wow.org/?spell=
Object: https://database.turtle-wow.org/?object=

**Expected behavior. Describe how it should work:**
I think the item "Scarlet Crusade Insignia" will give to me when I finish the quest "Supplies We Need" and reward ".I can see it in my bag.And I read the quest Description,she will give you a map,but I didn't see it in quest Reward.I don't know what it means.

**Comment by Heteroi** [comment]
My character's name is Heteroi.A level 60 mage.my account is kellywlyxbsb.

**Comment by Heteroi** [comment]
oh I found it. It's a key in Key chain.sorry to bother you.Could you tell me What does this thing do?

**Comment by Gurky-Turtle** [comment]
It doesn't do anything currently was planned for a future raid.

**Comment by Heteroi** [comment]
Thank you for your answer.I'm looking forward to future versions.



| |
***@***.***
|
|
***@***.***
|




---- Replied Message ----
| From | ***@***.***> |
| Date | 06/23/2023 00:25 |
| To | ***@***.***> |
| Cc | ***@***.***>***@***.***> |
| Subject | Re: [slowtorta/turtlewow-bug-tracker] A bug(maybe) of the quest "Supplies We Need" or the item "Scarlet Crusade Insignia" (Issue #3734) |

It doesn't do anything currently was planned for a future raid.
