### ISSUE TITLE
Quest: 'A Refugee's Quandary' box respawn timer too long

### ISSUE THREAD

**Issue by luskanek** [slowtorta/turtlewow-bug-tracker#3735]
**Please, provide a clear description what the bug is:**
The respawn timer of the affected quest object is way too long. The other two objects needed for the quest respawn within 10 seconds, but the respawn time of the box seems to be longer than 5 minutes.

**IDs of affected creatures, items, quests or spells with a link to the relevant page:**

Item: https://database.turtle-wow.org/?item=10438
Quest: https://database.turtle-wow.org/?quest=3361
Object: https://database.turtle-wow.org/?object=148499

**Expected behavior. Describe how it should work:**
Set the respawn timer to match the two other items.

**Comment by Gurky-Turtle** [comment]
looks like this has been fixed has the same respawn timers as all other objects for this quest.
