### ISSUE TITLE
Character can not open portal to Amani`Alor Trolls any more. 

### ISSUE THREAD

**Issue by Ttourro** [slowtorta/turtlewow-bug-tracker#3736]
The problem occured suddenly, i was able to open portal in Orgrimar from troll portal trainer to Amani`Alor troll. But after some point i`m not able do that any more. This option for me is no longer existing in a trainer dialog. Also if some one opened portal arleday i cannot enter it. Reported to GM, he said to create here issue. (Character Tourro)

**Comment by Gurky-Turtle** [comment]
![image](https://github.com/slowtorta/turtlewow-bug-tracker/assets/90982783/858bc2f4-621b-42f6-8e07-c015be2687bb)
Just tested this and it works correctly. you must complete the chain first to summon the portal: https://database.turtle-wow.org/?quest=80300
