### ISSUE TITLE
Deadwood Furbolgs evading

### ISSUE THREAD

**Issue by JikukanIdo** [slowtorta/turtlewow-bug-tracker#3738]
Deadwood Furbolgs evading constantly/broken pathfinding in northern Felwood

**Steps to reproduce the behavior with as much detail as possible:**

1. Go to Northern Felwood
2. Target any furbolg around the green pond with ranged attacks
3. Watch them get stuck, evade everything and reset aggro after about 15 seconds

**IDs of affected creatures, items, quests or spells with a link to the relevant page:**

NPC: https://database.turtle-wow.org/?npc=7157
https://database.turtle-wow.org/?npc=7156
https://database.turtle-wow.org/?npc=7158

Item: N/A
Quest: N/A
Spell: N/A
Object: N/A

**Expected behavior. Describe how it should work:**

Not evade, not get stuck and simply work as every other NPC does in the game

**Comment by YamaYAML** [comment]
I'll have a look.

**Comment by YamaYAML** [comment]
Closed because of duplicate with https://github.com/slowtorta/turtlewow-bug-tracker/issues/3051 - will continue updates there.
