### ISSUE TITLE
Horde Battleground Rep too low for 9x Mark Turnin

### ISSUE THREAD

**Issue by Jeradooka** [slowtorta/turtlewow-bug-tracker#3739]
**Please, provide a clear description what the bug is:**
Alliance get TRIPLE rep gain when they turn in the 9 mark combo.
Horde only get DOUBLE rep gain when they turn in the 9 mark combo.

**Steps to reproduce the behavior with as much detail as possible:**

1. Have 3 marks of Honor from all 3 Battlegrounds
2. Turn in Horde version. Note reputation gains.
3. Turn in Alliance version. Note reputation gains.
4. Compare discrepancy.

**IDs of affected creatures, items, quests or spells with a link to the relevant page:**

Quest (Horde): https://database.turtle-wow.org/?quest=8388
Quest (Alliance): https://database.turtle-wow.org/?quest=8371

**Expected behavior. Describe how it should work:**
Horde players should receive comparable reputation gains (and back-credit for old turnins)

**Comment by Gurky-Turtle** [comment]
There is not a bug here, you are comparing the first turnin to a repeatable

Horde first turn in - https://database.turtle-wow.org/?quest=8367
Alliance first turn in - https://database.turtle-wow.org/?quest=8371

see both have the same values 
8300 Experience
200 Reputation with [Frostwolf Clan](https://database.turtle-wow.org/?faction=729)
150 Reputation with [The Defilers](https://database.turtle-wow.org/?faction=510)
150 Reputation with [Warsong Outriders](https://database.turtle-wow.org/?faction=889)

8300 Experience
200 Reputation with [Silverwing Sentinels](https://database.turtle-wow.org/?faction=890)
150 Reputation with [Stormpike Guard](https://database.turtle-wow.org/?faction=730)
150 Reputation with [The League of Arathor](https://database.turtle-wow.org/?faction=509)

Horde repeatable - https://database.turtle-wow.org/?quest=8388
Alliance repeatable - https://database.turtle-wow.org/?quest=8385

6600 Experience
150 Reputation with [Frostwolf Clan](https://database.turtle-wow.org/?faction=729)
100 Reputation with [The Defilers](https://database.turtle-wow.org/?faction=510)
100 Reputation with [Warsong Outriders](https://database.turtle-wow.org/?faction=889)

6600 Experience
150 Reputation with [Silverwing Sentinels](https://database.turtle-wow.org/?faction=890)
100 Reputation with [Stormpike Guard](https://database.turtle-wow.org/?faction=730)
100 Reputation with [The League of Arathor](https://database.turtle-wow.org/?faction=509)
