### ISSUE TITLE
Transmogrification Ancestral War Totem

### ISSUE THREAD

**Issue by skleny90** [slowtorta/turtlewow-bug-tracker#3740]
**Please, provide a clear description what the bug is:**

I used Ancestral War Totem appearance for transmogrification, but it looks different. I used it to change the appearance of my Manual Crowd Pummeler, but it doesn't look like the original Ancestral War Totem, it looks upside-down sticking high above my character's right shoulder. I was wondering if it's possible to make it look exactly like the original Ancestral War Totem.

**Steps to reproduce the behavior with as much detail as possible:**

1. Use transmogrification to change the appearance of Manual Crowd Pummeler to Ancestral War Totem
2. Equip Manual Crowd Pummeler 
3. 

**IDs of affected creatures, items, quests or spells with a link to the relevant page:**

Ancestral War Totem ID:5415 https://database.turtle-wow.org/?item=81199
Manual Crowd Pummeler ID:19645 https://database.turtle-wow.org/?item=9449

**Expected behavior. Describe how it should work:**

In my opinion, it should look exactly like original Ancestral War Totem and not upside down.

**Comment by skleny90** [comment]
![1](https://github.com/slowtorta/turtlewow-bug-tracker/assets/137187794/6cf10398-7a5a-4e6c-883e-ba16616a209b)

**Comment by skleny90** [comment]
<img src="![1](https://github.com/slowtorta/turtlewow-bug-tracker/assets/137187794/d24d8e8c-bbda-4c8a-9552-eeae37cf699f)" width="100" height="100">

**Comment by skleny90** [comment]
<img src="https://github.com/slowtorta/turtlewow-bug-tracker/assets/137187794/4b063337-fc36-4896-a4f1-1cef98a48a04" width=200% height=200%>

**Comment by skleny90** [comment]
![1](https://github.com/slowtorta/turtlewow-bug-tracker/assets/137187794/00e11faa-7e44-486b-9734-bce291d94fdb)

**Comment by Jammyxx** [comment]
It's not just specific to this item... All weapons retain their original positon when transmogged... Example, Phantom Blade, is one that goes on your back... However if you transmog it into a weapon that's sheathed at the side, Phantom blade will appear sheathed at the side.... Another example is someoff hand held items appear when sheathed away, however when you use these for transmog on an offhand that doesn't show up sheathed it will not show up also.

**Comment by luskanek** [comment]
There have been efforts to implement a system that could let you set the sheath position of the transmogrified weapon, but without luck. Can't fix.
