### ISSUE TITLE
Spiked Collar/ Guardian Felhunter bug?

### ISSUE THREAD

**Issue by montypup** [slowtorta/turtlewow-bug-tracker#3741]
**Please, provide a clear description what the bug is:**
So I noticed that sometimes when i use my spiked collar trinket for summoning a guardian fel, it will sometimes randomly attack alternate faction players, which sets me to pvp even tho i am not pvp set, im wondering if thats a bug
**Steps to reproduce the behavior with as much detail as possible:**

1.
2. 
3. 

**IDs of affected creatures, items, quests or spells with a link to the relevant page:**
Spiked Collar Trinket
NPC: https://database.turtle-wow.org/?npc=
Item: https://database.turtle-wow.org/?item=
Quest: https://database.turtle-wow.org/?quest=
Spell: https://database.turtle-wow.org/?spell=
Object: https://database.turtle-wow.org/?object=

**Expected behavior. Describe how it should work:**
Defend only against aggressive npcs or players if set to pvp

**Comment by Gurky-Turtle** [comment]
![image](https://github.com/slowtorta/turtlewow-bug-tracker/assets/90982783/05c98084-fc4e-44d7-a29b-2f6660e1f1d6)
not a bug
