### ISSUE TITLE
Turtle Wow The Spirits of Southwind Quest Bug Report

### ISSUE THREAD

**Issue by AkanetheTengu** [slowtorta/turtlewow-bug-tracker#3742]
Hello!

My in-game character name is Kuroitengu, level 59 high elf mage, and it seems that I cannot accept the quest "The Spirits of Southwind" in Silithus from questgiver Layo Starstrike (all the database links below).

1. I tried picking this quest up after completing the prerequisite quest "Wasteland", and I received the following text error: "This quest isn't available on your race".
2. After the initial failure I couldn't attempt to accept the quest as the NPC was not offering it.

IDs of affected creatures, items, quests or spells with a link to the relevant page:

NPC: https://database.turtle-wow.org/?npc=13220
Quests: https://database.turtle-wow.org/?quest=1124; https://database.turtle-wow.org/?quest=1125

The DB links provided above mention that the quest should be available for all races, so I believe this is a bug. Please let me know if you need any further information on the subject.

Thank you in advance and have a nice day!

**Comment by Gurky-Turtle** [comment]
Should be fixed next update.
