### ISSUE TITLE
Stormwind Vault questgivers inactive for Horde

### ISSUE THREAD

**Issue by tortlefan** [slowtorta/turtlewow-bug-tracker#3745]
**Please, provide a clear description what the bug is:**
The SW Vault questgivers Pepin Ainsworth and Koli Steamheart are not active as quest providers for Horde players.  They are non-hostile, but have no quests to give.

**Steps to reproduce the behavior with as much detail as possible:**

1. Be a horde character at level 60
2. Try talking to either of these NPCs outside SW vaults -- they have no quests available.

**IDs of affected creatures, items, quests or spells with a link to the relevant page:**

NPCs: [Pepin Ainsworth](https://database.turtle-wow.org/?npc=80450), 80450
[Koli Steamheart](https://database.turtle-wow.org/?npc=80451), 80451

Quests: [Recovering Vault Shackles](https://database.turtle-wow.org/?quest=40426), 40426
[Ending Arc'Tiras](https://database.turtle-wow.org/?quest=40427), 40427

Additional source: [Past forums post](https://forum.turtle-wow.org/viewtopic.php?f=4&t=4932&p=29759#p29759)

**Expected behavior. Describe how it should work:**
The SW Vault questgivers Pepin Ainsworth and Koli Steamheart are supposed to offer quests to Horde players.

**Comment by Gurky-Turtle** [comment]
Should be fixed next update.
