### ISSUE TITLE
Item Bug: Cannot be Disenchanted (Mithril Scale Gloves)

### ISSUE THREAD

**Issue by AyleeJenn** [slowtorta/turtlewow-bug-tracker#3747]
**Please, provide a clear description what the bug is:**
Your standard, straight forward "Cannot be disenchanted" oversight. A disenchantment addon shows it *should* be disenchantable and there is nothing to suggest othewise so I am reporting this as a bug. Further details below.

**Steps to reproduce the behavior with as much detail as possible:**

1. Fashion "Mithril Scale Gloves" from the blacksmithing profession
2. Attempt to disenchant "Mithril Scale Gloves"
3. Observes as the error "Cannot be disenchanted" appears

**IDs of affected creatures, items, quests or spells with a link to the relevant page:**

Item: https://database.turtle-wow.org/?item=7925

**Expected behavior. Describe how it should work:**
Naturally, this item should disenchant into a disenchanting table of the appropriate level range. According to my addon that would be ... 
75% Vision dust (2 - 5)
20% Lesser Nether Essence (1 - 2)
5% Small Radiant Shard (1 - 1)

Thank you for your continued work and dedication and commitment to this project.

**Comment by slowtorta** [comment]
Thank you for your report. However, this is a Blizzlike behavior: some of the crafted items in vanilla and Classic cannot be disenchanted. We don't know if it's an oversight or intended behavior, but we usually just leave this as it is. 

https://www.wowhead.com/classic/item=7925/mithril-scale-gloves#created-by-spell

**Comment by slowtorta** [comment]
After discussing this issue with the team, we've decided to assign a disenchant loot table to this item.
