### ISSUE TITLE
Cone of cold doesn’t apply slow if already slowed! CRITICAL

### ISSUE THREAD

**Issue by DannyPuncake** [slowtorta/turtlewow-bug-tracker#3749]
**Please, provide a clear description what the bug is: Cone of cold slow doesn’t apply on targets slowed by blizzard.

**Steps to reproduce the behavior with as much detail as possible:

1. Mage level 26, learn cone of cold, and get permafrost 3/3 in frost tree.
2. Slow mob with blizzard.
3. Cone of cold while targets are slowed. 
4. No visual debuff about cone of cold slow, only blizzard slow.
**IDs of affected creatures, items, quests or spells with a link to the relevant page:**

Spell: https://database.turtle-wow.org/?spell=120 cone of cold

https://database.turtle-wow.org/?spell=12571 permafrost r3

https://database.turtle-wow.org/?spell=10
Blizzard

**Expected behavior. Describe how it should work:**

Mage should be able to apply cone slow after blizzard to continue the kite.

Cone of cold is a 10sec cd spell that should stack (duration vise) with other slows and also should slow for 11sec with permafrost 3/3. So a mage should be able to kite a pack of mobs using cone of cold every cd. 

https://youtu.be/G_MJIGbFCOs

**Comment by xhummerx** [comment]
that is actualy blizzlike atleast compared to classic retail unless you got a clip from classic that shows it
if you want to do this to is nova them at the end of blizzard and then wait for debuff to fade and cone then

**Comment by Gurky-Turtle** [comment]
https://us.forums.blizzard.com/en/wow/t/mage-cone-of-cold-blizzard-bug-slowing-effects/291874/4

Not a bug
