### ISSUE TITLE
Honor Rank Gear & Requirements

### ISSUE THREAD

**Issue by GrizB37** [slowtorta/turtlewow-bug-tracker#3753]
**Please, provide a clear description what the bug is:*

Recently due to the honor miscalculation, alot of people got a rank and subsequently the gear they shouldn't have technically got. 

This created an issue where people have the R13 Gear for example but their max rank still reads as R12. 

On Turtle Wow the description on the gear for required rank is not present. 

EDIT:

You will still have the gear equip in your slots if you bought it and put on during the bugged calculation but if you deranked with the fixed honor calculations and take gear off you cannot use it! 

But this is not apparent until you take it off! 

**Steps to reproduce the behavior with as much detail as possible:**

1. Have E.g R13 during bugged calculation, buy and equip the gear. 
2. Be R12 after fixed calculation. 
3. R13 gear useable until taken off

**IDs of affected creatures, items, quests or spells with a link to the relevant page:**

NPC: https://database.turtle-wow.org/?npc=
Item: https://database.turtle-wow.org/?item=
Quest: https://database.turtle-wow.org/?quest=
Spell: https://database.turtle-wow.org/?spell=
Object: https://database.turtle-wow.org/?object=

**Expected behavior. Describe how it should work:**
The gear should say Requires: Rank, on it.

**Comment by GrizB37** [comment]
Update: After taking gear off and trying to reequip. Can no longer use.... The Requires: Rank is working but not shown on the item, Please consider adding the Requires:Rank back visually so people don't finish ranking thinking they can use the gear indefinitely

**Comment by twowTurtReynolds** [comment]
All has been looking good with the honor calc scripts and no fallout from this old incident persists.
