### ISSUE TITLE
you are in combat issue

### ISSUE THREAD

**Issue by morporkian** [slowtorta/turtlewow-bug-tracker#3756]
This happens randomly - after being in combat and killing the target my character stays 'in combat' i.e. cannot eat or drink to restore health (health stays at current level indefinitely), but bandages can be used. Can't log out as it thinks I'm in combat. The effect remains after further combat kills. I have to kill the program via task manager to exit or hearthstone out which seems to clear the combat state. Teleporting is greyed out also. Leaving the area by foot doesn't clear the issue.

**Steps to reproduce the behavior with as much detail as possible:**

1. Random, with no obvious pattern
2. 
3. 

**IDs of affected creatures, items, quests or spells with a link to the relevant page:**

Various npcs & creatures

**After killing the targeted npc/creature the combat state should be removed allowing restoration of health/mana etc:**

**Comment by slowtorta** [comment]
Too little information, impossible to fix w/o knowing a way to actually reproduce it.
