### ISSUE TITLE
Venomous Jungle Serpent, Venomflayer Serpent cannot be skinned

### ISSUE THREAD

**Issue by zeress** [slowtorta/turtlewow-bug-tracker#3757]
**Please, provide a clear description what the bug is:**
Despite being a beast and other similar Wind Serpents being skinable, these cannot.

**Steps to reproduce the behavior with as much detail as possible:**

1. Kill one
2. Note that you cannot skin it
**IDs of affected creatures, items, quests or spells with a link to the relevant page:**

NPC: https://database.turtle-wow.org/?npc=91966 https://database.turtle-wow.org/?npc=61096

**Expected behavior. Describe how it should work:**
The should provide similar skinning drops as other mobs of a similar level. Example of a Wind Serpent that can be skinned: https://database.turtle-wow.org/?npc=4118

**Comment by Gurky-Turtle** [comment]
![image](https://github.com/slowtorta/turtlewow-bug-tracker/assets/90982783/ae985e18-0a32-46dc-be78-ce2f2d72d048)
![image](https://github.com/slowtorta/turtlewow-bug-tracker/assets/90982783/581a7db0-60c7-4a31-9f10-156b1f8d59f3)

looks like Venomous Jungle Serpent is the only one without skinning

**Comment by Gurky-Turtle** [comment]
will be fixed next update.
