### ISSUE TITLE
Holy Fire and Holy Nova still using old scaling values.

### ISSUE THREAD

**Issue by ConcernedTurtler** [slowtorta/turtlewow-bug-tracker#3758]
According to the priest changes page on turtle-wow:
Holy Fire initial damage component scaling has been adjusted: (0.75 → 0.857)
Holy Nova talent damage component scaling has been adjusted: (0.107 → 0.161)

These changes have not been implemented as the spells are still using their old spell damage scaling values.

Steps to reproduce the behavior with as much detail as possible:

Equip some spell damage gear (100+)
Cast low ranks of Holy Fire/ Holy Nova
IDs of affected creatures, items, quests or spells with a link to the relevant page:

https://database.turtle-wow.org/?spell=15261
https://database.turtle-wow.org/?spell=27801

Expected behavior. Describe how it should work:
Holy Fire and Holy Nova should use the updated spell damage scaling values shown on the priest changes page:
https://turtle-wow.org/#/priest

**Comment by schanzee** [comment]
Can confirm the damage scaling for Holy Nova is still 0.107.
Could just be that the https://turtle-wow.org/#/priest page is not up to date it has a lot of errors like 15 second Pain Spike CD and Champion’s Grace which never made it into the game.

**Comment by Gurky-Turtle** [comment]
Will be fixed in the next update
