### ISSUE TITLE
Kirith the Damned immune to enslave

### ISSUE THREAD

**Issue by balakethelock** [slowtorta/turtlewow-bug-tracker#3759]
**Please, provide a clear description what the bug is:**
Kirith the Damned is incorrectly immune to Enslave, in classic it was enslaveable. 

**Steps to reproduce the behavior with as much detail as possible:**

1. Go to blasted lands eastern cave
2. Try to enslave Kirith
3. Find that it's immune

**IDs of affected creatures, items, quests or spells with a link to the relevant page:**

NPC: https://database.turtle-wow.org/?npc=7728

**Expected behavior. Describe how it should work:**
can be enslaved. Proof:
Wowhead comments https://www.wowhead.com/classic/npc=7728/kirith-the-damned#comments
Warlock discord message https://discord.com/channels/253210018697052162/498619347778928661/627834154066771998
![image](https://github.com/slowtorta/turtlewow-bug-tracker/assets/111737968/3a36a12e-8de4-4011-9f72-f08f06c1e9b5)

**Comment by Gurky-Turtle** [comment]
https://github.com/vmangos/core/commit/f8a50e33edd59b0986205fccda1d3b01ced32bc7

Doesn't look like a bug after vmangos took a deep dive into it.
