### ISSUE TITLE
Make Unstuck feature on site also revive you

### ISSUE THREAD

**Issue by Madliv21** [slowtorta/turtlewow-bug-tracker#3760]
**Please, provide a clear description of what the bug is:**
Hello, when the player submits an unstuck request, if they are dead/ ghost they will not be revived, which doesn't fix the issue. Cuz most of the time the player is far away from their heartstone and teleporting their ghost to heartstone only stuck them more. Which requires GM assistance. Since the unstuck has a 7 days cooldown, can we also make sure the player is also revived, like on the other private servers?
**Steps to reproduce the behaviour with as much detail as possible:**

1. Go on-site,
2.  Hit unstuck
3.

**Comment by slowtorta** [comment]
What we can do is make this function unavailable if the character is dead :)

**Comment by Madliv21** [comment]
That works as well, cuz right now if you are dead and use it, you brick your char and unless a GM revives you...you gonna walk for hours in some cases.
