### ISSUE TITLE
Can't send gold to alt... "You don't have enough money"

### ISSUE THREAD

**Issue by erokbud** [slowtorta/turtlewow-bug-tracker#3761]
**Please, provide a clear description what the bug is:**

When I try to send mail to my alt 'Sweetcheese', I'm presented with the message "You don't have enough money" and I'm unable to send.

**Steps to reproduce the behavior with as much detail as possible:**

1. Interact with a mailbox
2. send gold to Sweetcheese
3.  

**IDs of affected creatures, items, quests or spells with a link to the relevant page:**

NPC: https://database.turtle-wow.org/?npc=
Item: https://database.turtle-wow.org/?item=
Quest: https://database.turtle-wow.org/?quest=
Spell: https://database.turtle-wow.org/?spell=
Object: https://database.turtle-wow.org/?object=

**Expected behavior. Describe how it should work:**
It should let me send gold to my character...
![image](https://github.com/slowtorta/turtlewow-bug-tracker/assets/137457634/8c006203-4bca-4386-b8ad-024f29dc1503)

**Comment by Gurky-Turtle** [comment]
Try clearing your WDB folder

**Comment by erokbud** [comment]
Hello,

Thank you for the suggestion – I tried that and it did not help.

**Comment by Gurky-Turtle** [comment]
I cannot reproduce this issue. Maybe try changing your email body and subject text. 

Does a lower amount of gold allow you to send?

**Comment by RaeNidae** [comment]
If this hasn't yet been resolved, I had a very similar issue myself. Attaching a random item to the mail seemingly allowed it to be sent properly

**Comment by Gurky-Turtle** [comment]
I would try the suggestion above or try a freshly downloaded client without any modifications. I have tested this with many characters and everything seems to work even at the mailbox above.
