### ISSUE TITLE
A Thief's Reward fire festival quest not avaliable

### ISSUE THREAD

**Issue by testening** [slowtorta/turtlewow-bug-tracker#3762]
**Please, provide a clear description what the bug is:**

The quest A Thief's Reward is not avaliable.

**Steps to reproduce the behavior with as much detail as possible:**

1. Complete _Stealing (Stormwind/Ironforge/Darnassus or Orgrimmar/Thunder Bluff/Undercity)'s Flame_ quests
2. Talk to any Festival Talespinner
3. There is no _A Thief's Reward_ quest avaliable

**IDs of affected creatures, items, quests or spells with a link to the relevant page:**

  Quest: https://database.turtle-wow.org/?quest=9365
  Quest: https://database.turtle-wow.org/?quest=9339

  Quest: https://database.turtle-wow.org/?quest=9330
  Quest: https://database.turtle-wow.org/?quest=9331
  Quest: https://database.turtle-wow.org/?quest=9332

**Expected behavior. Describe how it should work:**

  Completing all _Steal (city)'s Flame_ quests should unlock _A Thief's Reward_.

  If the Turtle Database is correct, both faction's _A Thief's Reward_ quests are currently switched - you have to complete the alliance _Steal-Flame_ quests to unlock horde's _A Thief's Reward_, and vice-versa. As they are race-locked, no one can access _A Thief's Reward_.

**Comment by Gniltag** [comment]
Woud be great if this coud get fixed while the event is still up :3

**Comment by Gniltag** [comment]
Please fix :x

**Comment by TehN1k0** [comment]
Can confirm, stole all 3 city's flames but no quest "A Thief's Reward" is offered...

**Comment by TehN1k0** [comment]
Just stole all 3 city's flames again, still no A Thief's Reward quest... does not look solved?

The quest which gives the pet is now there tho... which was not b4 either.

**Comment by slowtorta** [comment]
You have to wait for a server update this Wednesday.

**Comment by TehN1k0** [comment]
Roger torta thanks.
