### ISSUE TITLE
Midsummer festival quest bugged.

### ISSUE THREAD

**Issue by Klevdud** [slowtorta/turtlewow-bug-tracker#3763]
After turning in the 3 flames of the horde capitals I was not able to pick up the last quest: A thiefs reward. (https://www.wowhead.com/classic/quest=9339/a-thiefs-reward)

**Comment by slowtorta** [comment]
Fixed on the next update. 
https://github.com/slowtorta/turtlewow-bug-tracker/issues/3762
https://github.com/slowtorta/turtlewow-bug-tracker/issues/3790
