### ISSUE TITLE
fire festival qeust not availabel to allaince

### ISSUE THREAD

**Issue by geojak** [slowtorta/turtlewow-bug-tracker#3764]
**Please, provide a clear description what the bug is:**

https://database.turtle-wow.org/?quest=9368 allaicne equivalent is compeltely missing, also on db

**Steps to reproduce the behavior with as much detail as possible:**

https://www.wowhead.com/classic/quest=9367/the-festival-of-fire

**Expected behavior. Describe how it should work:**

quest should be available

**Comment by slowtorta** [comment]
This will be fixed on the next server update.
