### ISSUE TITLE
"Supplies we Need" in EPL, quest not working

### ISSUE THREAD

**Issue by kroogz** [slowtorta/turtlewow-bug-tracker#3765]
**Please, provide a clear description what the bug is:**
Handed in required items but did not receive the required quest item from npc. Nor does npc offer the next quest (checked and confirmed in game by GM). Quest response quotes "Cannot complete, Duplicate item found"

**Steps to reproduce the behavior with as much detail as possible:**

1.
2. 
3. 

**IDs of affected creatures, items, quests or spells with a link to the relevant page:**

NPC: https://database.turtle-wow.org/?npc=
Item: https://database.turtle-wow.org/?item=
Quest: https://database.turtle-wow.org/?quest=
Spell: https://database.turtle-wow.org/?spell=
Object: https://database.turtle-wow.org/?object=

**Expected behavior. Describe how it should work:**
Npc should give Scarlet Crusade Insignia to allow the chain to continue, but item does not appear in bag. Nor does npc offer any follow on quest

**Comment by Gurky-Turtle** [comment]
There is no quest after Supplies we Need that is where the chain ends. 

As for the item it sounds like you already have it in your keyring. Please check your key ring and see if it exists there.
