### ISSUE TITLE
scholo fire counts as startholme

### ISSUE THREAD

**Issue by geojak** [slowtorta/turtlewow-bug-tracker#3766]
**Please, provide a clear description what the bug is:**

in the fire festival qeust a lifght in dark palces, we need to visit stratholme scholo, diremaul and lbrs
i was just scholo and clocked the fire there, but the qeust counter tracked it as the strat fire

**Steps to reproduce the behavior with as much detail as possible:**

1. get a light in dark palces
2. go scholo and use the fire
3. see the quest tracker ticked strathole fire instead

**IDs of affected creatures, items, quests or spells with a link to the relevant page:**

https://database.turtle-wow.org/?quest=9319

**Expected behavior. Describe how it should work:**

scholo fire should count for scholo objective and not stratholme

**Comment by slowtorta** [comment]
Fixed.
