### ISSUE TITLE
Field Duty quest Horde

### ISSUE THREAD

**Issue by MrShmiTT** [slowtorta/turtlewow-bug-tracker#3768]
**Please, provide a clear description what the bug is:**

**Steps to reproduce the behavior with as much detail as possible:**

1. Take quest Field Duty for Horde
2. Talk  with Krug Skullsplit
3. When a big bug arrives other npcs in the camp don't fight the bug and Krug dies

[Quest: https://database.turtle-wow.org/?quest=](https://database.turtle-wow.org/?quest=8731)

**Expected behavior. Describe how it should work:**
Other npcs in Horde camp fight with the bug and help to kill. Alse Axe Throwers located too far and don't agro to the bug.
![Big Bug](https://github.com/slowtorta/turtlewow-bug-tracker/assets/48833977/356b56bd-01f3-45e4-830b-db2f667ed4f5)

**Comment by Gurky-Turtle** [comment]
https://github.com/slowtorta/turtlewow-bug-tracker/issues/2405
