### ISSUE TITLE
Fishliver Oil is Bind on Pickup, and it shouldn't be.

### ISSUE THREAD

**Issue by Altgf1** [slowtorta/turtlewow-bug-tracker#3770]
**Please, provide a clear description what the bug is:**

Fishliver oil from a quest in Redridge Mountains isn't BoP on other private servers, nor is on classic wow. However, on Turtle wow it is BoP, which is kinda sad.

You can obtain five pieces of that item, which upon use grant you 10% melee attack speed for 30 seconds. This effect shares 2 min cooldown with potions of all kind.

I am not sure, if this item specificly was changed to be BoP or was part of some older patch, where multiple items like this got changed.
Considering, that warriors have Mighty Rage Potion as a consumable, that increases their damage, it would be fair to give such a chance to other classes as well. It opens another option to people, who want to push their limits to increase their raid dps.

It's also a good idea to add such a thing to Alchemy and allow people to farm it without camping poor murlocs in Redridge. However, changing item to not be BoP is a good start.

**IDs of affected creatures, items, quests or spells with a link to the relevant page:**

Item: https://database.turtle-wow.org/?item=1322
Quest: https://database.turtle-wow.org/?quest=127

**Comment by balakethelock** [comment]
It's clearly bind on pickup in classic wowhead.. https://www.wowhead.com/classic/item=1322/fishliver-oil

This is an item that was not bound early in vanilla life, and was made soulbound later. The servers where its tradeable use progressive itemization.

Turtle wow is on final patch, so according to that, the item is correctly soulbound.

**Comment by Altgf1** [comment]
> It's clearly bind on pickup in classic wowhead.. https://www.wowhead.com/classic/item=1322/fishliver-oil
> 
> This is an item that was not bound early in vanilla life, and was made soulbound later. The servers where its tradeable use progressive itemization.
> 
> Turtle wow is on final patch, so according to that, the item is correctly soulbound.

hmmm strange, I was leveling on Everlook some time ago and it was also on the Auction House.

**Comment by balakethelock** [comment]
> hmmm strange, I was leveling on Everlook some time ago and it was also on the Auction House.

One of Everlook's selling points is that it uses progressive itemization. You'll see many items very different from how they became in 1.12.1
For example, look at old [Spirit of Aquementas](https://classicdb.ch/?item=11904-0) before they added spellpower

**Comment by slowtorta** [comment]
The item has a correct bonding flag :)
