### ISSUE TITLE
Pyroblast (casted) + Presence of Mind + Pyroblast bug (any spell combo with Presence of Mind makes this bug, Pyro is just part of the combo)

### ISSUE THREAD

**Issue by Nettngale** [slowtorta/turtlewow-bug-tracker#3771]
**Please, provide a clear description what the bug is:**
When using Pyroblast, Presence of Mind, Pyroblast to combo,  sometimes the character stop using any spell and have to wait the cast time of the last spell used to start casting again.
Pyroblast is just part of the combo, this happens with Fireball too, the difference was I had to wait less time to be able to cast normally again since the cast time for fireball is smaller, seems something with Presence of Mind.
**Steps to reproduce the behavior with as much detail as possible:**

1. Cast Pyroblast and use Presence of Mind, cast Pyroblast again.
2. Repeat this process till the bug happens, 1/3 times it will happen 
3. Then the character will not be able to use any spell in the action bars, and wait the last spell cast time to be able cast again.

**IDs of affected creatures, items, quests or spells with a link to the relevant page:**

NPC: https://database.turtle-wow.org/?npc=
Item: https://database.turtle-wow.org/?item=
Quest: https://database.turtle-wow.org/?quest=
Spell: https://database.turtle-wow.org/?spell=12043
Object: https://database.turtle-wow.org/?object=

**Expected behavior. Describe how it should work:**
It should be able to cast an instant spell after using presence of mind, which happens, then after that, be able to cast normally any other spell.

**Comment by Nettngale** [comment]
To add an observation I removed addons and played the game without them, then I tested on other skills, proving there is nothing to do with Pyroblast.
I used Fireball to test, using Fireball - Presence of Mind - Fireball. What I learned from that is: using repeated spells (Fireball), the bug happens, making me unable to cast anything for (Fireball cast time) after using this combination. So, the bug seems to happen with multiple spells but till now it only happens when I use 2 instances of the same spell (Fireball), if I use Fireball - Presence of Mind - Pyroblast the bug does not happen.

**Comment by Zebouski** [comment]
This sounds a lot to me like a known visual bug in nampower... are you sure you dont have that installed?

**Comment by Nettngale** [comment]
> This sounds a lot to me like a known visual bug in nampower... are you sure you dont have that installed?

I do have it installed, but it is not visual at all, it is mechanic, I literally cannot cast anything till the supposed cast time is finished.

**Comment by Zebouski** [comment]
Yeah uninstall nampower and see if you can replicate this bug. i dont think you can.

If you think its losing you dps because of this, hit up https://github.com/namreeb/nampower 's bug reports and let them know

**Comment by Gurky-Turtle** [comment]
going to close this for now will reopen if it happens without nampower.
