### ISSUE TITLE
UBRS key

### ISSUE THREAD

**Issue by UBRSkeyisfucked** [slowtorta/turtlewow-bug-tracker#3773]
**Please, provide a clear description what the bug is:**
UBRS key is still having the issue dating back to november 2021 on these forums see post #467 and post #3737 
attempted the quest and had emberstrife breathe fire naturally over the seals, as well as MC'd him to breathe fire.
got the orange text and everything saying the seal had been forged but couldn't click or loot the seal.
the remaining seals/MC orb were removed from my bag so i cant even reattempt. Would really appreciate the seal if possible as it took me awhile to grind the gems and i would really rather not go through that all over again.
**Steps to reproduce the behavior with as much detail as possible:**

1.
2. 
3. 

**IDs of affected creatures, items, quests or spells with a link to the relevant page:**

NPC: https://database.turtle-wow.org/?npc=
Item: https://database.turtle-wow.org/?item=
Quest: https://database.turtle-wow.org/?quest=
Spell: https://database.turtle-wow.org/?spell=
Object: https://database.turtle-wow.org/?object=

**Expected behavior. Describe how it should work:**

**Comment by Gurky-Turtle** [comment]
https://github.com/slowtorta/turtlewow-bug-tracker/issues/3842

**Comment by Muigin** [comment]
Cannot reproduce on current version. Seal forges properly when Emberstrife breathes fire on it.
