### ISSUE TITLE
Festival Loremaster missing final Midsummer Fire Festival quest

### ISSUE THREAD

**Issue by fatnerdynerd** [slowtorta/turtlewow-bug-tracker#3786]
**Please, provide a clear description what the bug is:**
A Thief's Reward quest doesn't appear to exist on Turtle.
**Steps to reproduce the behavior with as much detail as possible:**

1. Capture all opposing faction's capital flames.
2. Go to Ironforge/Orgrimmar and speak to Festival Loremaster
3. the Festival Loremaster NPC should offer the quest A Thief's Reward, but he does not.

**IDs of affected creatures, items, quests or spells with a link to the relevant page:**

NPC: https://www.wowhead.com/classic/npc=16817/festival-loremaster
Quest: https://www.wowhead.com/classic/quest=9339/a-thiefs-reward
Quest Reward: https://www.wowhead.com/classic/item=23323/crown-of-the-fire-festival

**Expected behavior. Describe how it should work:**
Once you hand in all 3 quests A Thief's Reward should be unlocked, granting you the final Midsummer quest reward: Crown of the Fire Festival.

**Comment by MaurisLV** [comment]
Yes! I'm having a same problem! Quest is missing for "Crown of the Fire Festival". I even did all quests, still nothing ..

**Comment by slowtorta** [comment]
Fixed on the next update.
