### ISSUE TITLE
captured flame pet does not go into the spellbok

### ISSUE THREAD

**Issue by geojak** [slowtorta/turtlewow-bug-tracker#3787]
**Please, provide a clear description what the bug is:**

the fire festival spirit pet does not go inside the spellbok and stays as an item in your bag

**Steps to reproduce the behavior with as much detail as possible:**

1.  fire festival ongoing
2. do qeust a ligh in dark palces
https://database.turtle-wow.org/?quest=9319
4. get the pet rewards captured flame https://database.turtle-wow.org/?item=23083
5. use it and see its still in your invetory

**IDs of affected creatures, items, quests or spells with a link to the relevant page:**

https://database.turtle-wow.org/?item=23083

**Expected behavior. Describe how it should work:**
should go inside the book and free up inveotry space

**Comment by slowtorta** [comment]
Fixed in the next client update.
