### ISSUE TITLE
bug in desolace 

### ISSUE THREAD

**Issue by sljp1107** [slowtorta/turtlewow-bug-tracker#3789]
**Please, provide a clear description what the bug is:**
good afternoon, I am here in desolace and I have completed the 2 missions "our mortal enemies" and "collapse of the maraudine" and when I want to claim the reward for finishing them it is impossible for me to interact with the npc who gave me the missions in a First, what solution can the npc give me is "warleader temukar", currently I abandoned both missions (which I had already completed) to try to see if the problem was solved and nothing happened, the npc in general would not let me interact with him

**Steps to reproduce the behavior with as much detail as possible:**

1.
2. 
3. 

**IDs of affected creatures, items, quests or spells with a link to the relevant page:**

NPC: https://database.turtle-wow.org/?npc=
Item: https://database.turtle-wow.org/?item=
Quest: https://database.turtle-wow.org/?quest=
Spell: https://database.turtle-wow.org/?spell=
Object: https://database.turtle-wow.org/?object=

**Expected behavior. Describe how it should work:**
It should let me interact normally like I do with any npc, since at first I was able to acquire the quest, the logical thing is that it allows me to deliver it once completed, sorry but I'm not going to search in each item quest npc object box, I have already given enough information It is located south of Desolace, you can go there and check it out if you are interested, sincerely: Leignt

**Comment by slowtorta** [comment]
Please make sure you aren't at war with this NPC's faction. Open your reputation tab and locate the faction, unclick At War flag.
