### ISSUE TITLE
Warrior over-charge target.

### ISSUE THREAD

**Issue by gh-borz** [slowtorta/turtlewow-bug-tracker#379]
**Please, provide a clear description what the bug is:**

when you use warrior “charge” ability, it frequently over-charges the target, which brings up a “you are facing the wrong way” alert, and opens you up for an immediate strike from behind.

I have appended a screenshot of combat log showing that immediately after charge, I get backstabbed.

I have tried deleting WBD folder with no change.

**Steps to reproduce the behavior with as much detail as possible:**

1. Find a mob as a warrior, you can try making sure both you and the mob are standing still if you want. A mob capable of backstab, such as the Defias Highwaymen in The Dagger Hills region of southern part of Westfall, is ideal.
2. Charge the target.
3. Frequently you will see a “you are facing the wrong way alert”.

**IDs of affected creatures, items, quests or spells with a link to the relevant page:**

NPC: https://database.turtle-wow.org/?npc=
Item: https://database.turtle-wow.org/?item=
Quest: https://database.turtle-wow.org/?quest=
Spell: https://database.turtle-wow.org/?spell=
Object: https://database.turtle-wow.org/?object=

**Expected behavior. Describe how it should work:**

When a warrior charges a target, you should come to a stop in front of your target, unless it is resisted. You should not be over-charging the target so you end up facing the wrong way.

**Comment by gh-borz** [comment]
![CE92AF3F-170E-43CA-9072-314863E407DB](https://user-images.githubusercontent.com/91382132/137491231-bcc31f9e-1e84-4aee-afd3-f1d3835b059c.jpeg)

**Comment by slowtorta** [comment]
I couldn't reproduce this problem. Is this report is still relevant?
