### ISSUE TITLE
Alah'thalas Crystal Mine Constructs Missing

### ISSUE THREAD

**Issue by Vikarec** [slowtorta/turtlewow-bug-tracker#3791]
**Please, provide a clear description what the bug is:**

The high elf crystal mine for the daily quest is full of Malfunctioning Arcane Constructs. Now, they have all left the mine and are instead wandering in the skies and mountains above it so the mine is empty. They are truly beyond malfunctioning now.

**Steps to reproduce the behavior with as much detail as possible:**

1. Go to Alah'thalas' mine.
2. There are no constructs.
3. Look outside and see them all on the mountaintops.

**IDs of affected creatures, items, quests or spells with a link to the relevant page:**

https://database.turtle-wow.org/?npc=80241

**Expected behavior. Describe how it should work:**

They should be inside the crystal mine.

**Comment by slowtorta** [comment]
Fixed in 1.16.6!
