### ISSUE TITLE
Cast time Corruption bug.

### ISSUE THREAD

**Issue by suunset** [slowtorta/turtlewow-bug-tracker#3793]
**Please, provide a clear description what the bug is:** (Gnome) Warlock's Corruption ability at talent level 5 takes 2 seconds to cast.

**Steps to reproduce the behavior with as much detail as possible:**

1. Gnome, warlock, lvl 15.
2. Rank 2 corruption. (Rank 1 is also not instant)

**IDs of affected creatures, items, quests or spells with a link to the relevant page:**

NPC:
Item:
Quest: 
Spell: https://database.turtle-wow.org/?spell=6222
Object:

**Expected behavior. Describe how it should work:**

Instead of being an instant cast. (At talent level 4 it was working as intended, with a lower cast time)

**Comment by ratkosrb** [comment]
I don't see the issue. All ranks are instant when you have the talent.


https://github.com/slowtorta/turtlewow-bug-tracker/assets/35845488/52f1c74b-d6b7-4a4b-a5e3-0d742af4a0d0

**Comment by suunset** [comment]
I found a fix by deleting all cache files in the WDB folder, thanks anyways.
