### ISSUE TITLE
Quest an Infinite Hunt cannot be completed

### ISSUE THREAD

**Issue by StayTuned2k** [slowtorta/turtlewow-bug-tracker#3795]
**Please, provide a clear description what the bug is:**

**Steps to reproduce the behavior with as much detail as possible:**

1. Be alliance
2. Accept the quest An Infinite Hunt
3. Go to the right spot (Seradane, red crystal)
4. Try to click the red crystal
5. Nothing happens, object cannot be interacted with

**IDs of affected creatures, items, quests or spells with a link to the relevant page:**

https://database.turtle-wow.org/?quest=80411

**Expected behavior. Describe how it should work:**

An NPC should spawn when you click the red crystal in order to progress the quest

**Comment by Gurky-Turtle** [comment]
https://github.com/slowtorta/turtlewow-bug-tracker/issues/3650
