### ISSUE TITLE
Physical abilities don't benefit from weapon skill.

### ISSUE THREAD

**Issue by balakethelock** [slowtorta/turtlewow-bug-tracker#3796]
**Please, provide a clear description what the bug is:**
Physical abilities that don't require a weapon, such as Bloodthirst or Pummel, are incorrectly excluded from using equipped weapon skill. Instead they use (level * 5)

**Steps to reproduce the behavior with as much detail as possible:**
1. Level 60 warrior with low skill in one weapon and high skill in another
2. Hit a level 60 mob with bloodthirst, a bit with the high skill weapon and a bit with the low skill weapon, find that your weapon skill is not taken into account at all.

**Expected behavior. Describe how it should work:**
[Image from fight club discord](https://user-images.githubusercontent.com/111737968/248505592-affd7030-86bd-46c5-9964-f892ec5943e3.png)

More proof in inside
https://github.com/vmangos/core/pull/1983 

**How to fix:**
Search AttackerWeaponSkill to find the line that looks similar, since I don't know how old twow's fork from vmangos is, it could be in either Unit.cpp or Object.cpp
After that simply remove the conditional for using equipped weapon skill, so that it's always used.

**Comment by sarenraee** [comment]
damn, that's a big bug!

**Comment by balakethelock** [comment]
From asking players with practical experience, this bug affects many abilities including but not limited to: Bloodthirst, Pummel, Revenge, Seal of Command, Crusader Strike, all judgements.

**Comment by lyssebabz** [comment]
Bloodthirst now deals less dmg, it says 45% of ap but it only does around 26-28 according to discord and my own findings

**Comment by twowTurtReynolds** [comment]
> Bloodthirst now deals less dmg, it says 45% of ap but it only does around 26-28 according to discord and my own findings

I tested on PTR and versus a 0 armor target. Bloodthirst works correctly. You probably were testing versus armored mobs where indeed bloodthirst has its damage reduced.
