### ISSUE TITLE
Container for "Henrig Lonebrow's Journal" missing

### ISSUE THREAD

**Issue by FreshFunman** [slowtorta/turtlewow-bug-tracker#3798]
**Please, provide a clear description what the bug is:**
The item "Henrig Lonebrow's Journal", which is needed to start a quest, should be lootable from a Container in Thousands Needles (the book in the Hand of a dead dwarf) but the container is not lootable. The book is visually there but it is not possible to interact with it. I waited for 20 minutes and revisited the place a few times but it does not become lootable.

**Steps to reproduce the behavior with as much detail as possible:**

1. Go the Container
2. Try to interact with it.
3. Wait for a respawn of the container.
4. Wait forever.

**IDs of affected creatures, items, quests or spells with a link to the relevant page:**

Item: https://database.turtle-wow.org/?item=5791
Quest: https://database.turtle-wow.org/?quest=1100

Object: https://database.turtle-wow.org/?object=19861

**Expected behavior. Describe how it should work:**
You should be able to loot the book from the container. The container should respawn after some time.

**Comment by Dragunovi** [comment]
Maybe your level being lower than the required level to start the quest from the book is stopping you from looting it?

**Comment by Gurky-Turtle** [comment]
I just tested this and it works as intended and the book respawns after a very short time and is still useable. 
No bug here.
