### ISSUE TITLE
NPC - Simone the Inconspicuous

### ISSUE THREAD

**Issue by Ninetales0019** [slowtorta/turtlewow-bug-tracker#3799]
**Please, provide a clear description what the bug is:**

I have noticed that the NPC - Simone the Inconspicuous, a demon troll located in Un Goro Crater does not roam or path around the west of the map, typically around the lakes, hot springs and takes a route south towards the Hive. Simone and her Pet are both fixed/rooted in the same position, roughly (30.6  40.8).  I have observed this over the past 2 days. There was a Realm restart yesterday (26/06/23), which did not reset the annomly. I have attempted to try and kill her for my Hunter Class Quest, however due to her bad postioning and dense mob field, it is not ideal and very difficult.  There doesnt seem to be any issues affecting the other 3 demon NPCs involved with this Rhok'delar hunter class quest. They all roam and path around there repective maps.

Would it be possible to fix this issue? 

**IDs of affected creatures, items, quests or spells with a link to the relevant page:**

https://www.wowhead.com/classic/npc=14527/simone-the-inconspicuous

**Comment by Glaszstaff** [comment]
Is there any update to this? As of 07/16 this is still an issue
