### ISSUE TITLE
Menethil Keep

### ISSUE THREAD

**Issue by nonameform** [slowtorta/turtlewow-bug-tracker#38]
**Current behavior**: 
When you enter Menethil Keep, some quest NPCs become invisible. As you can see on screenshots below, for the NPC at the entrance, you might see it with certain camera angle and not with the other. However, the same did not work on the second floor, so I was unable to turn in _[Report to Captain Stoutfist](https://database.turtle-wow.org/?quest=473)_.

**Expected behavior**: 
The NPCs should be visible under any angle or video setup.

**Proofs**:
![WoWScrnShot_061321_021952](https://user-images.githubusercontent.com/34381716/121806598-32b7e400-cc59-11eb-91b3-0cec5a61c8be.jpg)
![WoWScrnShot_061321_021957](https://user-images.githubusercontent.com/34381716/121806600-36e40180-cc59-11eb-9eb6-e2f545a1eafb.jpg)

**Steps to reproduce**:

1. Enter the Keep.
2. Some NPCs will become invisible.
3. Impossible to start or turn in quests.

**Comment by Nolin7777** [comment]
Dev Note: Broken maps most likely.
