### ISSUE TITLE
Hunter pet disappeared after taking a flight

### ISSUE THREAD

**Issue by Nylen93** [slowtorta/turtlewow-bug-tracker#380]
**Please, provide a clear description what the bug is:**

Hunter pet (loyalty level 6) disappeared after taking a flight from Sentinell Hill (Westfall) to Stormwind City. Tried to summon it several without response, then checked with a stable master to find it was nowhere. 

**Steps to reproduce the behavior with as much detail as possible:**

1. Took a flight from point A to point B, hunter pet was summoned at that moment. 
2. Arrived to point B, pet wasn't summoned when arrived 
3. Casted "Call pet" but pet got not summoned, even after several re-casts.

**IDs of affected creatures, items, quests or spells with a link to the relevant page:**

Spell: https://database.turtle-wow.org/?spell=883

**Expected behavior. Describe how it should work:**
Hunter pets should remain summoned after arriving from a flight. Also, casting "Call pet" should summon hunter's current pet. Pets with a high level of loyalty (level 6) and happiness, shouldn't abandon the player.

**Comment by Nolin7777** [comment]
Hello and thank you for your report!

For comparison please add any evidence in form of a video captured from Blizzard's Classic server.

This ticket will be closed until more information added.

**Comment by Nolin7777** [comment]
I misread.

**Comment by slowtorta** [comment]
Related to: https://github.com/slowtorta/turtlewow-bug-tracker/issues/1207
