### ISSUE TITLE
Cannot loot any mobs

### ISSUE THREAD

**Issue by RaeNidae** [slowtorta/turtlewow-bug-tracker#3801]
Killing any mob does not produce loot despite the continued ability to loot them.
![Untitled](https://github.com/slowtorta/turtlewow-bug-tracker/assets/114691249/0c986174-895b-4e6b-ab13-4005fefd4273)
Example: humanoid mobs should at least drop money when killed, but they also drop nothing and cannot be looted despite the apparent ability to do so.

And yes, I already tried deleting WDB. Didn't fix the issue.

**Comment by Gurky-Turtle** [comment]
No gold or anything? I just spent time killing about 60 of them and they always dropped gold and sometimes would drop other items along with it.

**Comment by RaeNidae** [comment]
Nothing whatsoever. Previously was having a similar issue, but after attempting to loot a mob like five or so times I could actually receive items from them. But now it seems like they won't drop anything at all no matter how many attempts I make. And the mob is still perpetually "lootable" as if it has yet to be looted, but it still has nothing

**Comment by RaeNidae** [comment]
Ran a few more tests. While I had the same issue when trying it out on other pre-existing characters, I _didn't_ have it when trying it with a brand new character.
![Untitled](https://github.com/slowtorta/turtlewow-bug-tracker/assets/114691249/80621a71-f694-4908-83d4-036d13467b5d)
I have no idea what this means in terms of a potential resolution.

**Comment by Gurky-Turtle** [comment]
try clearing both your wdb folder and wtf folder and disable all addons and see what happens on your character with the issue.

**Comment by RaeNidae** [comment]
Yep. Did all that and I'm still having the same issue unfortunately.

**Comment by Gurky-Turtle** [comment]
The only other thing I can recommend is redownloading a new client and try it on the new download without changing anything on it and see what happens.

**Comment by RaeNidae** [comment]
Redownloading the client seems to have fixed the issue. I was even able to import all my old settings over via my original WTF folder, meaning that definitely wasn't the issue. Appreciate the help!

**Comment by Gurky-Turtle** [comment]
AWESOME! Have fun :)
