### ISSUE TITLE
Black Screen on Login Page

### ISSUE THREAD

**Issue by Chayse0** [slowtorta/turtlewow-bug-tracker#3802]
**Please, provide a clear description what the bug is:**
Black Screen on Login / When opening the application (WoW.exe)
**Steps to reproduce the behavior with as much detail as possible:**

1. Open WoW.exe
2. You then load the login page.
3. After you get a black screen and cant see the login page.

**IDs of affected creatures, items, quests or spells with a link to the relevant page:**

NPC: https://database.turtle-wow.org/?npc=
Item: https://database.turtle-wow.org/?item=
Quest: https://database.turtle-wow.org/?quest=
Spell: https://database.turtle-wow.org/?spell=
Object: https://database.turtle-wow.org/?object=

**Expected behavior. Describe how it should work:**

You should be able to open the game and see the login page.

![NVIDIA_Share_iTTDk7AiUI](https://github.com/slowtorta/turtlewow-bug-tracker/assets/137958193/2d90b86f-8161-4f4f-93b8-d675a207757b)

**Comment by slowtorta** [comment]
[If your game displays nothing but a black screen]

Please find the config located in your game folder: WoW/WTF/Config.wtf
Open it and add the following lines: 
SET gxWindow "1"
SET gxMaximize "1"

Save it and close it.
