### ISSUE TITLE
Survival Tent Can Block Certain Races from Entering/Exiting Entrances (i.e. inns)

### ISSUE THREAD

**Issue by tuccimon** [slowtorta/turtlewow-bug-tracker#3803]
**Please, provide a clear description what the bug is:**
Survival tent can block players from entering/exiting inns.

**Steps to reproduce the behavior with as much detail as possible:**

1. Someone sets up tent in front of inn entrance (Hillsbrad foothills).
2. Night elf height and taller players cannot pass through it and are blocked.
3. 

**IDs of affected creatures, items, quests or spells with a link to the relevant page:**

NPC: https://database.turtle-wow.org/?npc=
Item: https://database.turtle-wow.org/?item=
Quest: https://database.turtle-wow.org/?quest=
Spell: https://database.turtle-wow.org/?spell=
Object: https://database.turtle-wow.org/?object=1100000

**Expected behavior. Describe how it should work:**
Tents should have a minimum distance to be able to place away from entrance ways.
![tent_blockage](https://github.com/slowtorta/turtlewow-bug-tracker/assets/27434529/8ba0ffdd-60c1-4c83-8cda-ff52948eac02)

**Comment by slowtorta** [comment]
Impossible to implement any reasonable way.

**Comment by tuccimon** [comment]
How about turning off "clipping"/collision detection for tents so players can just pass through them?
