### ISSUE TITLE
Spirit of Summer is in the wrong tab of the Spellbook

### ISSUE THREAD

**Issue by Squirreled** [slowtorta/turtlewow-bug-tracker#3804]
Spirit of Summer is in the wrong tab of the Spellbook

When Learning Captured Flame the companion shows up in the General tab of the Spellbook

Item: https://database.turtle-wow.org/?item=23083
Quest: https://database.turtle-wow.org/?quest=9319
Spell: https://database.turtle-wow.org/?spell=28871

Spirit of Summer should instead appear in the Companions tab of the Spellbook

**Comment by slowtorta** [comment]
This will be fixed in patch 1.16.6
