### ISSUE TITLE
Shadow Mend has no interaction with Inner Focus

### ISSUE THREAD

**Issue by schanzee** [slowtorta/turtlewow-bug-tracker#3805]
Inner Fire is not working with Shadow Mend

**Steps to reproduce the behavior with as much detail as possible:**

1. Buff Inner Focus
2. Cast Shadow Mend
3. Mana for Shadow Mend is spend and Inner Focus remains on the player

https://database.turtle-wow.org/?spell=14751
https://database.turtle-wow.org/?spell=45554

**Expected behavior. Describe how it should work:**

Same issue was opened and closed here https://github.com/slowtorta/turtlewow-bug-tracker/issues/1967 but the bug is still or again in the game.

**Comment by Gurky-Turtle** [comment]
https://github.com/slowtorta/turtlewow-bug-tracker/issues/2310
