### ISSUE TITLE
Blade of Eternal Darkness doenst scale

### ISSUE THREAD

**Issue by Alorgg** [slowtorta/turtlewow-bug-tracker#3806]
Hey dear Turlte Wow Team

i thought the Proc of Blade of Eternal Darkness (https://database.turtle-wow.org/?item=17780) scales 100% with spelldmg, i just tested it. 
It is not scaling.

If it should work like this i`m sorry for the Threat.

Thank you in advance!

**Comment by balakethelock** [comment]
not a bug. It is not supposed to scale
