### ISSUE TITLE
Fallen Hero of the Horde does not offer Fel Salve

### ISSUE THREAD

**Issue by SaxxonPike** [slowtorta/turtlewow-bug-tracker#3807]
**Please, provide a clear description what the bug is:**

The quest, "Uniting the Shattered Amulet" (quest ID 3627), requires the effects of a weapon that is provided by the quest, "Enchanted Azsharite Fel Weaponry" (quest ID 3625). However, there is supposed to be a dialog option in case you have lost or sold the provided weapon provided by Fallen Hero of the Horde (npc ID 7572).

**Steps to reproduce the behavior with as much detail as possible:**

1. Complete all quests up until you are able to obtain "Uniting the Shattered Amulet" (quest ID 3627)
2. Interact with Fallen Hero of the Horde while you have this quest in your log.
3. Notice that there is no gossip option to gain the replacement salve (item ID 11582).

**IDs of affected creatures, items, quests or spells with a link to the relevant page:**

NPC: https://database.turtle-wow.org/?npc=7572 (quest giver with the missing gossip option)
Item: https://database.turtle-wow.org/?item=11582 (salve that is supposed to be given)
Quest: https://database.turtle-wow.org/?quest=3627 (quest which is required)
Spell: https://database.turtle-wow.org/?spell=15247 (spell that creates the salve)

**Expected behavior. Describe how it should work:**

Video source from Classic: https://www.youtube.com/watch?v=jSoHkn6fohY

At 5:19 in that video, you will see that there is a gossip option with the text "I have destroyed my Azsharite weaponry! I need your assistance in defeating the triad of power." This is supposed to be available as long as you have the quest. The spell effect from either the salve or weapon is required in order to defeat any of the enemies mentioned in the quest. If the weapon has been sold or destroyed, unless the Fel Salve is available, the quest can *never* be completed even if abandoned and reaccepted.

**Comment by Gurky-Turtle** [comment]
<img width="260" alt="Screenshot 2023-06-28 at 9 17 45 AM" src="https://github.com/slowtorta/turtlewow-bug-tracker/assets/90982783/21452691-7a21-4980-9958-362f1222ddb7">
