### ISSUE TITLE
New high level spells taught at starting trainers

### ISSUE THREAD

**Issue by TatkaS1** [slowtorta/turtlewow-bug-tracker#3808]
### **Starting area shaman trainers teach new (high level) abilities**

**Steps to reproduce the behavior with as much detail as possible:**

1. Talk to the shaman trainer in the Valley of Trials or Red Cloud Mesa
2. See the list of spells offered for training
3. See that there are the new spells learnable at lvl 30 to 60

**IDs of affected creatures, items, quests or spells with a link to the relevant page:**

NPC: https://database.turtle-wow.org/?npc=3062 Meela Dawnstrider
NPC: https://database.turtle-wow.org/?npc=3157 Shikrik
Spell: https://database.turtle-wow.org/?spell=47267 Water Shield
Spell: https://database.turtle-wow.org/?spell=47265 Stormstrike (rank 2)
Spell: https://database.turtle-wow.org/?spell=45520 Feral Spirit (rank 2)
Spell: https://database.turtle-wow.org/?spell=47266 Earth Shield
Spell: https://database.turtle-wow.org/?spell=47268 Calm Elements
Spell: https://database.turtle-wow.org/?spell=47264 Bloodlust (rank 2)

**Expected behavior. Describe how it should work:**

Those trainers shouldn't teach abilities higher than lvl 6.

![image](https://github.com/slowtorta/turtlewow-bug-tracker/assets/87695943/983e1384-b6e6-4590-9bcc-971d17a466c8)

**Comment by Gurky-Turtle** [comment]
Should be fixed in the next update.
