### ISSUE TITLE
Blood Fury and Rockbiter Weapon effects do not stack

### ISSUE THREAD

**Issue by TatkaS1** [slowtorta/turtlewow-bug-tracker#3809]
**Please, provide a clear description what the bug is:**

Blood Fury racial spell's and Rockbiter Weapon shaman spell's attack power do not stack

**Steps to reproduce the behavior with as much detail as possible:**

1. Be orc shaman (I am lvl 3)
2. Use Rockbiter Weapon to enchant your weapon with extra attack power
3. Use Blood Fury
4. See in your stat window that your attack power and weapon damage has not changed (both with and without an addon to show stats)

**IDs of affected creatures, items, quests or spells with a link to the relevant page:**

Spell: https://database.turtle-wow.org/?spell=20572 Blood Fury (rank 1)
Spell: https://database.turtle-wow.org/?spell=8017 Rockbiter Weapon

**Expected behavior. Describe how it should work:**

Since Blood Fury gives 25% of base attack power and Rockbiter Weapon adds set amount of bonus attack power, there is no reason for the buffs to not stack.

![without rage](https://github.com/slowtorta/turtlewow-bug-tracker/assets/87695943/2bc87ccc-0b47-4fb1-b121-65dece2e51a8)

![with rage](https://github.com/slowtorta/turtlewow-bug-tracker/assets/87695943/6ea290f9-a9bd-4959-b4bb-43a1545c4e09)

**Comment by Gurky-Turtle** [comment]
https://github.com/slowtorta/turtlewow-bug-tracker/issues/2436
