### ISSUE TITLE
Guild Tabard - teleport

### ISSUE THREAD

**Issue by d-u-b** [slowtorta/turtlewow-bug-tracker#381]
https://database.turtle-wow.org/?item=5976 teleport function on this item work 1 time only and now nothing happens then use

**Comment by slowtorta** [comment]
There's a 1 hours cooldown for this teleport, item is working as intended :)

**Comment by slowtorta** [comment]
I tested it multiply times. It works. Probably you guild doesn't have a Guild House, so that's why?

**Comment by d-u-b** [comment]
> I tested it multiply times. It works. Probably you guild doesn't have a Guild House, so that's why?

guild Still Alive

**Comment by slowtorta** [comment]
They don't have a Guild House :)

**Comment by d-u-b** [comment]
but when i used it in the first time, i was ported to Stormwind city GH

**Comment by slowtorta** [comment]
It was probably a Wormhole: https://database.turtle-wow.org/?item=51310

**Comment by d-u-b** [comment]
> It was probably a Wormhole: https://database.turtle-wow.org/?item=51310

it teleport to Inn

**Comment by slowtorta** [comment]
It is not. Hearthstone teleports you to the Inn.

**Comment by d-u-b** [comment]
ohh  yes. Wormhole teleport in middle of the city
then i used tabard 1st time it port me to https://database.turtle-wow.org/?npc=5193

**Comment by slowtorta** [comment]
It could not happen. Anyway, Still Alive guiled does not have a guild house, so tabard should not work, it's intended.
