### ISSUE TITLE
Terrain on Gillijim's isle has a hole 

### ISSUE THREAD

**Issue by KomDotExe** [slowtorta/turtlewow-bug-tracker#3810]
There is a thin line about 1 pixel long that goes across Gillijim's isle.
The line can be seen at [58.4, 84.7]

here is the video to see what I mean.
https://cdn.discordapp.com/attachments/1123578452033933322/1123579137353859132/20230628-1141-28.0484614.mp4

**Comment by slowtorta** [comment]
Moved it to the internal tracked for client bugs.

**Comment by twowTurtReynolds** [comment]
![image](https://github.com/slowtorta/turtlewow-bug-tracker/assets/151180101/e37015dd-271f-44b4-b727-3b54bba4854f)
