### ISSUE TITLE
Lil Timmy in SW is not following his path, and assigned spawn patterns. 

### ISSUE THREAD

**Issue by Tiladon** [slowtorta/turtlewow-bug-tracker#3811]
**Please, provide a clear description what the bug is:**

Lil Timmy <Boy with Kittens> is not following his path, despawning, and respawning with his kitten for sale. 

**Steps to reproduce the behavior with as much detail as possible:**

No steps are needed to reproduce this effect. I noticed this effect on 28 Jun 2023. I watched him for over 6 hours before making this report. 

**IDs of affected creatures, items, quests or spells with a link to the relevant page:**

NPC: https://database.turtle-wow.org/?npc=8666

**Expected behavior. Describe how it should work:**

Lil Timmy <Boy with Kittens> is supposed to follow a set path starting near the entrance of SW docks near the Cathedral Square, make a lap around most of the Dwarven District of SW before returning to his spawn point to despawn. He is meant to Spawn, walk his path (Which takes about 15 minutes) go back, despawn and after 2 hours respawn and do it all over again. Along with this each time he spawns he should hold 1 White Kitten (Cage for learning this associated Animal Companion).

**Comment by Tiladon** [comment]
Yes, that is the correct path that he takes, I suppose I was confused as to why he did not despawn or respawn as I was attempting to get the kitten. Cant trust all the forums you see online. Thank you for the reply, I will just have to hang around and get that restock. Thank you!

**Comment by Gurky-Turtle** [comment]
No problem, happy farming!
