### ISSUE TITLE
Green Dragonscale Set bonus not stacking with the stats from the set.

### ISSUE THREAD

**Issue by alexilaiho1** [slowtorta/turtlewow-bug-tracker#3812]
**Please, provide a clear description what the bug is:**

I crafted a 3/3 piece Green Dragonscale set with Leatherworking. Each piece gives you "allows 5% mana regen while casting", and if you complete the set, there's a set bonus that says "3 pieces -> allows 15% mana regen while casting". 
But when I equip everything, I only get 15% regen while casting, those stats aren't being added together, like they're supposed to. 

Any set bonus in the game gets added with the bonuses from the individual pieces of that set. This one doesn't.

**IDs of affected creatures, items, quests or spells with a link to the relevant page:**

https://database.turtle-wow.org/?item=15045
https://database.turtle-wow.org/?item=20296
https://database.turtle-wow.org/?item=15046

**Expected behavior. Describe how it should work:**

Each piece gives 5% mana regeneration, so 3 pieces should give 15%, then you add the set bonus, which is also 15% -> 30% mana regeneration while casting in total.

**Comment by Gurky-Turtle** [comment]
> But when I equip everything, I only get 15% regen while casting, those stats aren't being added together, like they're supposed to. 

What are you using to see this information?

**Comment by alexilaiho1** [comment]
> What are you using to see this information?

BetterCharacterStats addon.  But if you'd like to try with another addon let me know how it goes.

When grinding mobs, I don't see much of a difference between using the whole set or only using 2pieces, because I only lose 5%, not 20%.

**Comment by alexilaiho1** [comment]
To add to this, I've done a bit of research on vanilla/classic items, compared this to the ones in Wowhead classic, ClassicDb and on Twinstar, and they all agree on one thing, none of the set pieces give 5% mana regen independently, you just get the 15% from completing the set.

So my guess is that the item tooltip is wrong?

**Comment by Gurky-Turtle** [comment]
You can't rely on Bettercharacterstats due to the way it works, I would recommend checking your mana regen manually through the combat log and comparing it with pieces off and on. Bettercharacterstats has to be specifically scripted to read the item text and know if they are allowed to stack or not to show correct values.

**Comment by alexilaiho1** [comment]
>  would recommend checking your mana regen manually through the combat log
I can't find a way to show mana regen in the combat log.

**Comment by Gurky-Turtle** [comment]
You can use some sort of addon like MikScrollingBattleText and just make it show mana regen ticks then youll see if it goes up or not.

**Comment by alexilaiho1** [comment]
I used MikScrollingBattleText, and it turned out it's indeed only an addon issue, as I've noticed the regen I was getting was first aligned with the addon as I was equipping gear and casting, until I equipped the 3rd piece, where I got the full amount while the addon still showed only the 15% amount.

The item is indeed working, thanks Gurky for helping out!
