### ISSUE TITLE
Evading issues Felpaw Village

### ISSUE THREAD

**Issue by Vliqta** [slowtorta/turtlewow-bug-tracker#3813]
**Please, provide a clear description what the bug is:**
In Felpaw Village north of Felwood, 80% of the deadwood mobs have a lot of evade issues. A pet hunter cannot run up to them or you can only range them down before they start to evade. 
**Steps to reproduce the behavior with as much detail as possible:**

1. Target Deadwood mob, try the ones around tents or structures preferably.
2. Try to send pet attack the target mob, pet stands still. Cannot find a path towards it. Shooting the mob only last for couple of seconds before it starts to evade.
3. Target evades and resets. Keeps you in combat for some time.

**IDs of affected creatures, items, quests or spells with a link to the relevant page:**

NPC: https://database.turtle-wow.org/?npc=7157 , https://database.turtle-wow.org/?npc=7156 , https://database.turtle-wow.org/?npc=7158
Item: https://database.turtle-wow.org/?item=21377 , https://database.turtle-wow.org/?item=20741
Quest: https://database.turtle-wow.org/?quest=8461 , https://database.turtle-wow.org/?quest=8470
Spell: https://database.turtle-wow.org/?spell=75 , Pet attack
Object: ...

**Expected behavior. Describe how it should work:**

Pets should run up to the mob and start attack it, shooting the targets should be possible until the mob dies.

**Comment by Gurky-Turtle** [comment]
https://github.com/slowtorta/turtlewow-bug-tracker/issues/3051

**Comment by Gurky-Turtle** [comment]
closing as duplicate
