### ISSUE TITLE
Noboru's Cudgel

### ISSUE THREAD

**Issue by Cheesebreath** [slowtorta/turtlewow-bug-tracker#3814]
**Please, provide a clear description what the bug is:**

Can't get a quest from Noboru's Cudgel after you looted the item. If you click on the item after you looted you get the information: "You do not have the required proficiency for that item.". I haven't looted the item on a class that can wield mace yet. But should still be able to take the quest on any class.

**Steps to reproduce the behavior with as much detail as possible:**

1. Kill Noboru the Cudgel
2. Loot Noboru's Cudgel
3. Can't right click the Cudgel.
4: Instead of a quest popping up you get the information: "You do not have the required proficiency for that item."

**IDs of affected creatures, items, quests or spells with a link to the relevant page:**

NPC: https://database.turtle-wow.org/?npc=5477
Item: https://database.turtle-wow.org/?item=6196
Quest: https://database.turtle-wow.org/?quest=1392

**Expected behavior. Describe how it should work:**

After looting the cudgel, you should be able to right click on it to get a quest even if you don't have mace skill

**Comment by Gurky-Turtle** [comment]
This is intended the quest has been changed.

https://database.turtle-wow.org/?quest=1392 no longer exists and was replaced by https://database.turtle-wow.org/?quest=40030
