### ISSUE TITLE
Spirit of Summer (companion)

### ISSUE THREAD

**Issue by welpenhund** [slowtorta/turtlewow-bug-tracker#3815]
**Please, provide a clear description what the bug is:**
When clicked the companion spell is not put in your companion tab, instead it is learned in the "General" in your spellbook
![grafik](https://github.com/slowtorta/turtlewow-bug-tracker/assets/30401521/9371f5f8-2c4f-487b-a50f-a39960ba0c74)

**Steps to reproduce the behavior with as much detail as possible:**

1. Get the companion
2.  Learn it
3.  Check your spellbook

**IDs of affected creatures, items, quests or spells with a link to the relevant page:**

NPC: https://database.turtle-wow.org/?npc=
Item: https://database.turtle-wow.org/?item=
Quest: https://database.turtle-wow.org/?quest=
Spell: https://database.turtle-wow.org/?spell=
Object: https://database.turtle-wow.org/?object=

**Expected behavior. Describe how it should work:**
I suppose it is supposed to be put into the "Companions" tab? :-)

**Comment by Gurky-Turtle** [comment]
This will be fixed in patch 1.16.6 it requires a client modification.
