### ISSUE TITLE
Weapon "Ragehammer" is giving 20 AP instead of 20 Damage

### ISSUE THREAD

**Issue by gotmilk0112** [slowtorta/turtlewow-bug-tracker#3816]
https://database.turtle-wow.org/?item=10626

The proc on this says that it increases "damage done" by 20. But when I look at my character sheet during the proc, my weapon damage is only increased by 5...my Attack Power is getting increased by 20, however.

So it seems the proc is not increasing Weapon Damage by 20, rather, it is just giving +20 attack power.

https://i.imgur.com/6CSnDrC.png

As per the text on the proc, it should be increasing weapon damage by 20.

**Comment by Gurky-Turtle** [comment]
This should be fixed in the next update
