### ISSUE TITLE
Darkmoon Faire Fortune wont open

### ISSUE THREAD

**Issue by thisiskt** [slowtorta/turtlewow-bug-tracker#3817]
**Please, provide a clear description what the bug is:**
Darkmoon Faire Fortune wont open.
**Steps to reproduce the behavior with as much detail as possible:**

1. Obtain Darkmoon Faire Fortune from Sayge in DMF.
2. Somehow get it stuck so it wont open.

**IDs of affected creatures, items, quests or spells with a link to the relevant page:**

NPC: https://database.turtle-wow.org/?npc=14822
Item: https://database.turtle-wow.org/?item=19422

**Expected behavior. Describe how it should work:**

**Comment by Gurky-Turtle** [comment]
@thisiskt I had this happen before its random and has something to do with the installation on your device. Make a ticket in game and they should be able to remove it and grant you a new one.

**Comment by thisiskt** [comment]
> @thisiskt I had this happen before its random and has something to do with the installation on your device. Make a ticket in game and they should be able to remove it and grant you a new one.

I wrote a ticket and was sent here... to write a github ticket...

**Comment by Gurky-Turtle** [comment]
i'll reopen this for now.
