### ISSUE TITLE
quel serrar quest

### ISSUE THREAD

**Issue by Rowenen** [slowtorta/turtlewow-bug-tracker#3818]
**Please, provide a clear description what the bug is:**

**Steps to reproduce the behavior with as much detail as possible:**

1.killed ony and had heated blade wont let me drive into corpse had gm help resolve issue and gave me item and quest back to start over and still wont let me drive blade into onys corpse
2. 
3. 

**IDs of affected creatures, items, quests or spells with a link to the relevant page:**

NPC: https://database.turtle-wow.org/?npc=
Item: https://database.turtle-wow.org/?item=
Quest: https://database.turtle-wow.org/?quest=
Spell: https://database.turtle-wow.org/?spell=
Object: https://database.turtle-wow.org/?object=

**Expected behavior. Describe how it should work:**

**Comment by Gurky-Turtle** [comment]
Did you put it on the ground and have her breath on it to get the Heated Ancient Blade https://database.turtle-wow.org/ ?item=18488? You need to do this before trying to plunge it into her corpse.

**Comment by Gurky-Turtle** [comment]
Do you have any videos or anything of what happened?

I am unable to reproduce this:
![image](https://github.com/slowtorta/turtlewow-bug-tracker/assets/90982783/0eef4f79-e495-4b8b-a678-b57eb7e0058b)

**Comment by Dragunovi** [comment]
Can't replicate.
