### ISSUE TITLE
Frost Warding doesnt reflect frost spells

### ISSUE THREAD

**Issue by mambo1986** [slowtorta/turtlewow-bug-tracker#3819]
**Please, provide a clear description what the bug is:**
Frost Warding doesnt reflect frost spells
**Steps to reproduce the behavior with as much detail as possible:**

1. cast frost ward
2. get frsotbolt casted on you by skeleton sorcerer in western plaguelands
3. never get frost spell reflect

**IDs of affected creatures, items, quests or spells with a link to the relevant page:**

NPC: https://database.turtle-wow.org/?npc=1784
Item: https://database.turtle-wow.org/?item=
Quest: https://database.turtle-wow.org/?quest=
Spell: https://database.turtle-wow.org/?spell=
Object: https://database.turtle-wow.org/?object=

**Expected behavior. Describe how it should work:**
Should reflect frost spells 20% of time

**Comment by ratkosrb** [comment]
![WoWScrnShot_071823_234406](https://github.com/slowtorta/turtlewow-bug-tracker/assets/35845488/3494e6b5-5f9d-43dc-bb4f-931ace73086e)

Cannot reproduce. I learned the talent, activated Frost Ward, and after casting a few Frostbolts on the character, it got reflected, so it correctly has a chance to reflect spells.
