### ISSUE TITLE
Server API for tracking completed quests

### ISSUE THREAD

**Issue by alexismoulin** [slowtorta/turtlewow-bug-tracker#3820]
I would suggest this Quality of Life improvement for people who want to complete the quests of the game for the Seeker of Knowledge title.

**Steps to reproduce the behavior with as much detail as possible:**

Would it be possible to have a server API like in WoW Classic to check whether or not a quest has been completed:

`/run print(C_QuestLog.IsQuestFlaggedCompleted(XXXX))`

pfQuest addon is client side and really suboptimal as it resets sometimes for no reason, so it is extremely difficult to find out the remaining quests to complete

Will it be a lot of work from your side to implement such a nice feature?

**Comment by twowTurtReynolds** [comment]
Please post this suggestion on the Suggestions forum instead of the bug tracker.

And yes, this would be indeed a LOT of work.

**Comment by cyaohiri** [comment]
There is already a command that does this. It's `.quest status <ID>`, but it's a GM-only command. I guess this could be modified and added as a command for regular players.
