### ISSUE TITLE
fire festival companion

### ISSUE THREAD

**Issue by Ragnaris** [slowtorta/turtlewow-bug-tracker#3826]
**Please, provide a clear description what the bug is:**

**Steps to reproduce the behavior with as much detail as possible:**

1.The fire elemental companion from the quest "A light in dark places" didnt appear in my companion page after using the item "bottled flame"
2. 
3. 

**IDs of affected creatures, items, quests or spells with a link to the relevant page:**

NPC: https://database.turtle-wow.org/?npc=
Item: https://database.turtle-wow.org/?item=
Quest: https://database.turtle-wow.org/?quest=
Spell: https://database.turtle-wow.org/?spell=
Object: https://database.turtle-wow.org/?object=

**Expected behavior. Describe how it should work:**

**Comment by slowtorta** [comment]
It's currently in your general tab. The positioning of this spell in the client will be fixed in the next client update.
