### ISSUE TITLE
Issue with Sentinel's Moonslicer's Damage

### ISSUE THREAD

**Issue by TheYellowbro** [slowtorta/turtlewow-bug-tracker#3827]
I believe there may be a bug with the item dropped from Crescent Grove called Sentinel's Moonslicer. I am level 37 paladin with both that weapon and Verigan's Fist. Verigan's Fist's base damage is 65-99 while Sentinel's Moonslicer's base damage is 75-113. When equipping Verigan's Fist my damage 170-207. When equipping Sentinel's Moonslicer my damage is 168-210. Screenshots attached.

![VerigansFist](https://github.com/slowtorta/turtlewow-bug-tracker/assets/138157359/df12c84f-d95f-4d10-a791-16f7bf2bd5d0)
Verigan's Fist: https://database.turtle-wow.org/?item=6953

![SentinelsMoonslicer](https://github.com/slowtorta/turtlewow-bug-tracker/assets/138157359/288ba64c-f905-4f43-bc41-d7869461b43f)
Sentinel's Moonslicer: https://database.turtle-wow.org/?item=83209

This doesn't seem right as I would expect the axe to have a higher min damage than the mace. I have 3 points in Two-Handed Weapon Specialization if that makes any difference, though they should be applying to both weapons.

**Comment by balakethelock** [comment]
There's no bug, attack power increases swing damage based on swing speed
