### ISSUE TITLE
Weapon Skills Are Set Incorrectly When Race Changing

### ISSUE THREAD

**Issue by imcdermott13** [slowtorta/turtlewow-bug-tracker#383]
When changing races, there appears to be two ways that weapons skills levels are incorrectly set.

1. If you are changing from a race that has a weapon skill racial bonus to any race, the racial bonus you originally had remains applied to your base skill level, potentially giving the player a higher base skill level than their new race can allow.

2. If you are equipping gear the increases a weapon skill when the race change occurs, the gear bonus remains applied to your base skill level, potentially giving the player a higher base skill level then is possible (only tested with Defense skill so far).

![WeaponSkills1](https://user-images.githubusercontent.com/52016320/137631712-70f2b512-d317-44ab-85a7-03f101b58d4a.jpg)
![WeaponSkills2](https://user-images.githubusercontent.com/52016320/137631715-9c238adc-ebff-4a62-a192-e1519bbf3a68.jpg)

Steps to reproduce the first issue

1. On a race with a racial bonus to any weapon skill, level up that weapon skill to the maximum of 305
2. Use a race change token to change to a race without that weapon skill
3. Log into the affected character, and notice that weapon skill is 305/300

Steps to reproduce the second issue

1. Level up defense skill to 300
2. Equip gear that applies bonus defense (Say 50 defense)
3. Use a race change token to change the character's race
4. Log into the affected character, and notice that Defense skill is 350 (+50)/300

Expected behavior:

Base Weapon Skill level should not be able to be higher than a race's allowed skill level.

**Comment by jameyboor** [comment]
This will be fixed on the next update, thanks for the report.
