### ISSUE TITLE
TW original quests do not show quest rewards properly

### ISSUE THREAD

**Issue by burmanj** [slowtorta/turtlewow-bug-tracker#3830]
**Please, provide a clear description what the bug is:**
I believe all TW original quests are bugged in that they don't display the item rewards in the quest from either the quest giver or when it is in the quest log, only when you turn it in and select the rewards.

**Steps to reproduce the behavior with as much detail as possible:**
Look at quest from quest giver.
Look at quest in quest log.

**IDs of affected creatures, items, quests or spells with a link to the relevant page:**
Picture from quest log: https://ibb.co/dj8NVM5
Quest in database: https://database.turtle-wow.org/?quest=55201

**Expected behavior. Describe how it should work:**
The quest from the giver and in the quest log should display the item rewards, such as Mountain Watcher\'s Crown here. If this bug is not in all TW original quests, it is in very many of them.

**Comment by slowtorta** [comment]
This is working as intended, for some quests you aren't supposed to know what you're getting until you're done with your task.
