### ISSUE TITLE
Zulian Crocolisks apply Rend and Tendon Rip from further than Melee range. Rend shouldn't even be an ability they cast.

### ISSUE THREAD

**Issue by fatnerdynerd** [slowtorta/turtlewow-bug-tracker#3831]
**Please, provide a clear description what the bug is:**
Zulian Crocolisks apply Tendron Rip and Rend from further than melee range.
**Steps to reproduce the behavior with as much detail as possible:**

1. Pull Crocolisks to aoe farm
2. Run around 5 yards near them while running on a mount. 
3. They sometimes (often while player is jumping) Will apply Tendon Rip or Rend.

According to https://www.wowhead.com/classic/npc=15043/zulian-crocolisk#abilities;mode:n They should only have Tendon Rips a spell, (yet they also have Rend) https://www.wowhead.com/classic/spell=3604/tendon-rip Tendon Rip is a melee range spell.

**IDs of affected creatures, items, quests or spells with a link to the relevant page:**

NPC: https://www.wowhead.com/classic/npc=15043/zulian-crocolisk#abilities;mode:n
Spell: https://www.wowhead.com/classic/spell=3604/tendon-rip

**Expected behavior. Describe how it should work:**
Zulian Crocolisks should cast only 1 spell and have it be cast when they are in melee range not further away.

**Comment by TatkaS1** [comment]
1. This is not classic and that's why people play here. Things are as they should've been on classic - croc bite can cause bleeding - logical.
2. When in the air during jumping server doesn't register your position the same way, so don't jump when near enemies, if you want to kite.

**Comment by afizzler** [comment]
> 1. This is not classic and that's why people play here. Things are as they should've been on classic - croc bite can cause bleeding - logical.
> 
>     2. When in the air during jumping server doesn't register your position the same way, so don't jump when near enemies, if you want to kite.

no one should give a fuck about making the difficulty harder. it is simply a buggy game mechanic that increases the range of tendon rip which should be fixed

**Comment by fatnerdynerd** [comment]
easy workaround for server mess would be to make these mobs not use Tendon Rip until X seconds into combat then? also adding new spells to mobs should warrant a patch note or something, you cant just say a bug is a feature without showing what patch was this changed in.

**Comment by twowTurtReynolds** [comment]
These mobs are now custom, and their abilities do not pose a problem in fully manned raids.
