### ISSUE TITLE
Un'Goro Soil for Horde not working correctly.

### ISSUE THREAD

**Issue by a-saye** [slowtorta/turtlewow-bug-tracker#3836]
**Please, provide a clear description what the bug is:**

**Steps to reproduce the behavior with as much detail as possible:**

1.  Un'Goro Soil quest in Thunder Bluff doesnt allow me to complete the turn in of 20 soil samples to Ghede. I currently have 115 in my inventory.
2.  In order to allow it to complete you must abandon the quest before turn in.
3. You guys rock keep doing what youre doing I love turtle wow.

**IDs of affected creatures, items, quests or spells with a link to the relevant page:**

NPC: https://database.turtle-wow.org/?npc=
Item: https://database.turtle-wow.org/?item=
Quest: https://database.turtle-wow.org/?quest=3761
Spell: https://database.turtle-wow.org/?spell=
Object: https://database.turtle-wow.org/?object=

**Expected behavior. Describe how it should work:**

You give Ghede the soil and he says hey thanks bro heres some xp + gold or whatevs.

**Comment by twowTurtReynolds** [comment]
Please see https://github.com/slowtorta/turtlewow-bug-tracker/issues/6042
