### ISSUE TITLE
Change forum password not possible 

### ISSUE THREAD

**Issue by geojak** [slowtorta/turtlewow-bug-tracker#3839]
**Please, provide a clear description what the bug is:**

Its,currently not possible to change the forum password 

**Steps to reproduce the behavior with as much detail as possible:**

1. Go to forum login page
2. Click forgot my, password
3. Get redirect to 404
4. 
**Expected behavior. Describe how it should work:**
It shoidl be possible to Change the forum password due to safety reasons with hackers everywhere

**Comment by slowtorta** [comment]
Currently no solutions for that. Long-term we're looking into replacing this forum with something modern.
