### ISSUE TITLE
Cleansed Timberling Heart ( rare spawn item ) not being made into a trinket as stated

### ISSUE THREAD

**Issue by Dualityz** [slowtorta/turtlewow-bug-tracker#3840]
I'm not sure if that is normal or not, but a recent update upgraded many flavorful, lower level on use items into trinkets ( like the sabercat figurine in Darkshore ). 
A similar but less common item, the Cleansed Timberling Heart, is obtained on a rare spawn in Teldrassil, Blackmoss the Fetid. 
It summons a timberling. 
This has not been made into a trinket. Is this normal ? It's a one time use item, and I would not like to waste it if it's just an overlook. Thanks !

**Steps to reproduce the behavior with as much detail as possible:**

1. Wait for Blackmoss the Fetid to spawn along the Wellspring lake / river. 
2. Kill it
3. Drop the Moss-twined Heart ( https://database.turtle-wow.org/?item=5179 ) and complete its questline, receiving a single use item called the Cleansed Timberling Heart.
( https://database.turtle-wow.org/?item=5218 ) 

**IDs of affected creatures, items, quests or spells with a link to the relevant page:**

NPC: https://database.turtle-wow.org/?npc=3535
Items: 
https://database.turtle-wow.org/?item=5218
https://database.turtle-wow.org/?item=5179
Quest: https://database.turtle-wow.org/?quest=941

**Comment by Dragunovi** [comment]
Converted into a trinket with the next update.
