### ISSUE TITLE
Seal of Ascension Quest Bugged if Multiple People are doing it Together

### ISSUE THREAD

**Issue by Quackmandan** [slowtorta/turtlewow-bug-tracker#3842]
**Please, provide a clear description what the bug is:**
Seal of Ascension quest bugs out if multiple people are trying to complete it together.  For context, Emberstrife is to be brought down to 10% hp where he needs to be MC'd by the Orb of Draconic Energy.  The player needs to place their Unforged Seal of Ascension on the ground, MC Emberstrife, and then use his flamebreath skill to "forge" the seal.  The player then needs to click on the "Forged Seal of Ascension" to loot the quest item needed to complete the quest.  HOWEVER, the other person on this quest also in my group looted this "Forged Seal of Ascension", which caused my Unforged Seal of Ascension & Orb of Draconic Energy to disappear.  He still had his unforged seal + orb so we waited 15minutes for Emberstrife to respawn.  However, when we attempted this again, the unforged seal simply disappeared when Emberstrife breathed on it.  So now I am left without the unforged seal or orb, and I have no way of completing the quest.
**Steps to reproduce the behavior with as much detail as possible:**

1. Have multiple members with Seal of Ascension quest killing Emberstrife
2. Have Emberstrife breath on the unforged seal to make it a forged seal
3. Witness as quest items disappear from other people's inventory despite not looting the forged seal

**IDs of affected creatures, items, quests or spells with a link to the relevant page:**

NPC: https://database.turtle-wow.org/?npc=
https://database.turtle-wow.org/?npc=10321

Item: https://database.turtle-wow.org/?item=
https://database.turtle-wow.org/?item=12323
https://database.turtle-wow.org/?item=12324
https://database.turtle-wow.org/?item=12300

Quest: https://database.turtle-wow.org/?quest=
https://database.turtle-wow.org/?quest=4743

Object: https://database.turtle-wow.org/?object=
https://database.turtle-wow.org/?object=175321
https://database.turtle-wow.org/?object=175322

**Expected behavior. Describe how it should work:**
Either multiple people should be able to interact & loot the "Froged Seal of Ascension", or the quest items (orb of draconic energy + unforged seal of ascension) should not disappear from your inventory UNTIL you have looted the forged seal of ascension.

**Comment by Gurky-Turtle** [comment]
https://github.com/slowtorta/turtlewow-bug-tracker/issues/3773

**Comment by UBRSkeyisfucked** [comment]
so you linked me to this but there's no solution?

**Comment by redmagejoe** [comment]
> so you linked me to this but there's no solution?

You seem to be new to how GitHub works, so allow me to explain:  Tickets pertain to single issues, bugs, reproducible problems.  These are not "support tickets", these are for bugtracking.  Your issue was linked because it is a duplicate, and would usually be closed that discussion and information pertaining to the bug may be consolidated in one thread.

**Comment by UBRSkeyisfucked** [comment]
i see, this appears to be an issue since november of 2019 so is there any consensus on a fix?

**Comment by redmagejoe** [comment]
@ratkosrb may be able to provide insight on addressing this issue as it sounds to be script related.

**Comment by Muigin** [comment]
Cannot reproduce on current version. Seal forges properly when Emberstrife breathes fire on it.
