### ISSUE TITLE
Cinder Bracers is still it's normal state, should be a trinket per TWow's idea

### ISSUE THREAD

**Issue by jlabranche** [slowtorta/turtlewow-bug-tracker#3843]
**Please, provide a clear description what the bug is:**

**Steps to reproduce the behavior with as much detail as possible:**

1. All items that summon pets were decidedly chosen to become trinkets
2. Cinder Bracers from the fire festival is still an item that can sit in your inventory and be used.
3. Use Cinder Bracer from your inventory

**IDs of affected creatures, items, quests or spells with a link to the relevant page:**

NPC: https://database.turtle-wow.org/?npc=[
Item: https://database.turtle-wow.org/?item=](https://database.turtle-wow.org/?item=23379)[
Quest: https://database.turtle-wow.org/?quest=[](https://database.turtle-wow.org/?quest=9322)
Spell: https://database.turtle-wow.org/?spell=](https://database.turtle-wow.org/?spell=29305)
Object: https://database.turtle-wow.org/?object=

**Expected behavior. Describe how it should work:**

Need admins to turn it in to a trinket and remove the 10 day duration

**Comment by Gurky-Turtle** [comment]
will be applied in the next patch
