### ISSUE TITLE
Bug in quest "Repair the fizz disk"

### ISSUE THREAD

**Issue by gb0519** [slowtorta/turtlewow-bug-tracker#3845]
**Please, provide a clear description what the bug is:**

**Steps to reproduce the behavior with as much detail as possible:**

1. quest name: "Repair the fizz disk"
2. I take all the needed items, but the quest can not be done. the mark on the npc is still a question mark. it should be a exclamation mark
![1](https://github.com/slowtorta/turtlewow-bug-tracker/assets/14720454/38706904-7c4f-4b3c-93ba-585b62342d32)

3. 

**IDs of affected creatures, items, quests or spells with a link to the relevant page:**

NPC: https://database.turtle-wow.org/?npc=
Item: https://database.turtle-wow.org/?item=
Quest: https://database.turtle-wow.org/?quest=
Spell: https://database.turtle-wow.org/?spell=
Object: https://database.turtle-wow.org/?object=

**Expected behavior. Describe how it should work:**

**Comment by Gurky-Turtle** [comment]
clear your WDB folder and also retake the quest. Tested this and it works as it should.
