### ISSUE TITLE
AQ40 Vek'Nilash bug

### ISSUE THREAD

**Issue by Moobca** [slowtorta/turtlewow-bug-tracker#3846]
The Vek'nilash takes holy damage which he shouldnt.

When you hit Vek'Nilash with holy damage attack which is magic that he should be immune to, hes taking the damage.

1.
2. 
3. 

Faction: [Monster](https://database.turtle-wow.org/?faction=14)
Faction ID: 16

https://database.turtle-wow.org/?npc=15275
https://www.youtube.com/watch?v=TOfsHcM9De8, Here you can see the boss being immune for holy damage on time 1:54-2:00.

He should be immune to all kinds of magical attacks, including holy damage done by holy strike, crusader strike, even procs from items like essence of pure flame or storm gauntlets. He only should be vulnerable to melle attacks

**Comment by balakethelock** [comment]
That's [Dragonbreath Chili](https://www.wowhead.com/classic/item=12217/dragonbreath-chili) that he's immune to. Fire damage.
He correctly takes holy damage in classic.

**Comment by Moobca** [comment]
But still, magic is magic, even holy is magic, shadow is magic, fire is magic etc etc.

**Comment by balakethelock** [comment]
What are you talking about??? Blizzard excluded specifically holy damage from vek'nilash immunity. Is this a bug report or a personal opinion

**Comment by afizzler** [comment]
this is not a bug as holy damage is dealt to vek'nilash as blizzard intended
