### ISSUE TITLE
Durotar Labour Union not showing up in my reputation tab

### ISSUE THREAD

**Issue by JikukanIdo** [slowtorta/turtlewow-bug-tracker#3847]
**Please, provide a clear description what the bug is:**
for some reason durotar labour union isn't showing up in my rep list, but i just earned rep for it (it's not under other, only cenarion circle, dalaran and kul tiras)
I've tried making a ticket about this, and was told to delete my WBD folder, which I already tried last night to no avail. I tried again and to double-check went to Sparkwater Port to try to "discover" the faction with no success.
https://i.gyazo.com/672370108d9a052eeb5b07ea7b270346.png
https://i.gyazo.com/f302a3c0ff8a00c63d9bf43e4d21d839.png
**Steps to reproduce the behavior with as much detail as possible:**

1. I have absolutely no clue how to reproduce this issue as I have no idea what started it in the first place
2. 
3. 

**IDs of affected creatures, items, quests or spells with a link to the relevant page:**
Issue only affects a single character from what I can tell, char name Darkdawg
https://armory.turtle-wow.org/#!/character/Darkdawg
Durotar Labour Union, the entire faction

**Expected behavior. Describe how it should work:**
Presumably it should simply show up in my Reputation tab and allow me to track my progress.

**Comment by slowtorta** [comment]
Will be fixed in patch 1.16.6
