### ISSUE TITLE
Animation Bug: Skeletal Fiend (can reproduce, see video)

### ISSUE THREAD

**Issue by AyleeJenn** [slowtorta/turtlewow-bug-tracker#3848]
**Please, provide a clear description what the bug is:**
When you defeat an enemy a defeat-animation is supposed to play. On "Skeletal Fiends" this animation is skipped and the enemy goes straight to laying on the ground which looks a bit weird.

Edit: **Upon closer examination the bug only appears to happen when they activate their rage ability.**

**Steps to reproduce the behavior with as much detail as possible:**

1. In Duskwood find Skeletal Fiend and fight it and defeat it while its rage ability is active
2. Upon defeating it (while its rage ability is active), observe as the enemy just instantly lays on the ground without defeat animation

**IDs of affected creatures, items, quests or spells with a link to the relevant page:**

NPC: https://database.turtle-wow.org/?npc=531

**Expected behavior. Describe how it should work:**
Upon defeating this enemy a defeat animation should play as opposed to the enemy instantly laying on the ground. Since this does look like a bug I am reporting it here.

**Comment by ratkosrb** [comment]
https://github.com/slowtorta/turtlewow-bug-tracker/assets/35845488/9b41350d-f1bf-487e-a066-a6789417018d

Can't reproduce the issue. He plays his death animation normally.

**Comment by AyleeJenn** [comment]
Then, why can I reproduce it?


https://github.com/slowtorta/turtlewow-bug-tracker/assets/87241085/4dc0b63e-6ea5-4607-a8d4-a7e373e5fc7b

You may have missed the most important detail. The condition of this bug.

What condition?

The condition that it only happens when the enemy activates its rage ability.

**Comment by Muigin** [comment]
This and many issues like it are intermittent client desync issues that the vanilla client is, sadly, infamous for. There's no way to truly "fix" this so that it never ever happens so long as we are using 1.12 EXE.
