### ISSUE TITLE
Ranged Slow for Paladins from Frost Oil via Judgement of the Crusader

### ISSUE THREAD

**Issue by feisgithub** [slowtorta/turtlewow-bug-tracker#3850]
**Please, provide a clear description what the bug is:**
Paladins can proc their weapon oils from range with judgement

**Steps to reproduce the behavior with as much detail as possible:**

1. apply frost oil to weapon
2. cast seal of the crusader, use judgement from range
3. paladins now have a ranged slow ability (instant cast frostbolt) every 10 seconds

**IDs of affected creatures, items, quests or spells with a link to the relevant page:**

NPC: https://database.turtle-wow.org/?npc=
Item: https://database.turtle-wow.org/?item=
Quest: https://database.turtle-wow.org/?quest=
Spell: https://database.turtle-wow.org/?spell=
Object: https://database.turtle-wow.org/?object=

**Expected behavior. Describe how it should work:**
Paladins are not supposed to have a ranged slow, it makes battlegrounds even more unbearable.
Make Judgement not proc weapon oils outside of melee range!

**Comment by jlabranche** [comment]
Haven't tested it so can't say one way or the other. But if it affects Frost Oil, it may affect Shadow Oil as well.

**Comment by Sringaram** [comment]
This whole change to judgement has brought nothing but issues. Procs are procs for a reason and being able to force them is just broken.

**Comment by ratkosrb** [comment]
But Judgement has a 10 yard range, so how do they use it to proc the frost oil from long range?

**Comment by feisgithub** [comment]
10yd IS ranged and not melee. with leeway and ping delay it's more than enough
Melee weapon enchants and weapon oils are not supposed to proc from anything outside of melee range.

**Comment by welpenhund** [comment]
That explains why i seen a frost bolt hitting me while fighting a paladin. I thought there was a mage hiding near shooting them, lol...

**Comment by Gurky-Turtle** [comment]
https://github.com/slowtorta/turtlewow-bug-tracker/issues/3889
https://github.com/slowtorta/turtlewow-bug-tracker/issues/3860
https://github.com/slowtorta/turtlewow-bug-tracker/issues/3850
https://github.com/slowtorta/turtlewow-bug-tracker/issues/3045

**Comment by GrizB37** [comment]
Please remove this rubbish. Makes paladins even more degen in PvP

**Comment by burner1024** [comment]
Now paladins are running around with Earthshaker, doing aoe stuns at will.
Bravissimo. Bravissimo.
