### ISSUE TITLE
shard of fallen sky aq40 trinekt doesnt scale with sp

### ISSUE THREAD

**Issue by geojak** [slowtorta/turtlewow-bug-tracker#3851]
**Please, provide a clear description what the bug is:**

the shard of the scale aq40 meteor trinekt does not scale on twow with sp
https://database.turtle-wow.org/?item=21891

According to https://www.youtube.com/watch?v=iH_HnGyFplI this is the same on blizzards classic wow BUT
According to multiple wowhead comments 
https://www.wowhead.com/classic/item=21891/shard-of-the-fallen-star
and 
https://www.youtube.com/watch?v=cvWFOvGfbH8

the trinekt acutally did scale in real original vanilla

**Expected behavior. Describe how it should work:**

dragunovi said to make a ticket, so here it is. pls consider changing the trinekt to scale with sp again as you have done for drain life weapons arleady to match real vanilla

also make six deamon bag fully scale on all possible spells not just some of them.
https://database.turtle-wow.org/?item=7734

**Comment by balakethelock** [comment]
Does completed mean it was made to scale? I hope the coefficient is not too high, paladin/caster burst in pvp is already a bit of a problem

**Comment by HoodyWood** [comment]
> 

not like many people actually have this item, but hoefuly it will scale at least to some point
