### ISSUE TITLE
Item: Viewing Room Key

### ISSUE THREAD

**Issue by Sringaram** [slowtorta/turtlewow-bug-tracker#3852]
ID: https://database.turtle-wow.org/?item=13873

The key isn't a 100% drop rate and this is quite an old bug that's been around. You cannot progress with the instance when it happens.

**Comment by Gurky-Turtle** [comment]
this item definitely has a 100% drop chance.

**Comment by Sringaram** [comment]
Just today I had it not drop and I recall people reporting the same issue.
