### ISSUE TITLE
Trash collector mob

### ISSUE THREAD

**Issue by Myguytyty** [slowtorta/turtlewow-bug-tracker#3853]
The buyback mob in ratchet doesn't let you buy back items i tried it with each quality to make sure but i accidentally sold a sword that i use and was unable to get it back which led me to try testing the mob i recorded a video with an epic weapon and it was not able to find any item that was recoverable i understand its my fault i should have been paying attention but the GM said they were unable to help because this mob is supposed to do that but i couldn't get it to work.

1.Went and sold an item of each rarity to see what ones could be recovered (none of them could) well i only went up to epic because I'm a coward.
2. 
3. 

**IDs of affected creatures, items, quests or spells with a link to the relevant page:**

NPC: https://https://database.turtle-wow.org/?npc=8
Item: https://database.turtle-wow.org/?item=
Quest: https://database.turtle-wow.org/?quest=
Spell: https://database.turtle-wow.org/?spell=
Object: https://database.turtle-wow.org/?object=

From my understanding you should be able to buy back items that you had mistakenly sold i assume by a certain quality but i tried it with up to an epic and nothing was able to be restored

**Comment by ratkosrb** [comment]
The trash collector does not sell back items you've sold to vendors. It sells items you have **destroyed**, meaning thrown away. Talk to a normal vendor to see the regular buyback menu.
