### ISSUE TITLE
Shadowforge Flame Keeper's Torch Drop Rate is Incorrect

### ISSUE THREAD

**Issue by Quackmandan** [slowtorta/turtlewow-bug-tracker#3854]
**Please, provide a clear description what the bug is:**
Shadowforge Flame Keeper's torch drop rate on og vanilla, blizzard classic vanilla, and all other private servers i have played on (warmane, nostalrius, etc.) are 100%.  This is the ONLY server without this.  Our group cleared ALL flame keepers in our lyceum but only 1 out of 5 dropped  a torch. this meant we had to sit around for 15min in the lyceum waiting for the flame keepers to respawn.  This is NOT intended behavior.
**Steps to reproduce the behavior with as much detail as possible:**

1. Enter the Lyceum in BRD
2. Witness the buggy drop rate for torches off Flame Keepers
3. 

**IDs of affected creatures, items, quests or spells with a link to the relevant page:**

NPC: https://database.turtle-wow.org/?npc=
https://database.turtle-wow.org/?npc=9956

Item: https://database.turtle-wow.org/?item=
https://database.turtle-wow.org/?item=11885

Quest: https://database.turtle-wow.org/?quest=
Spell: https://database.turtle-wow.org/?spell=
Object: https://database.turtle-wow.org/?object=

**Expected behavior. Describe how it should work:**
Shadowforge Flame Keeper should have a 100% torch drop rate.  This is how it is scripted everywhere else.  If you want to argue it should still be 80%, then the respawn timer for them should match the rest of the mobs in the room incase a group (like mine) gets needlessly stuck for 15minutes in a single room.  This is not intended behavior.  This is a bug.  This is not fun.

**Comment by Gurky-Turtle** [comment]
Fix will be applied next update.

**Comment by Quackmandan** [comment]
Awesome, thank you!
