### ISSUE TITLE
Armory Issues (https://armory.turtle-wow.org/)

### ISSUE THREAD

**Issue by Meridaw** [slowtorta/turtlewow-bug-tracker#3856]
**Please, provide a clear description what the bug is:**

**Steps to reproduce the behavior with as much detail as possible:**

1. The talent links to wowhead's talent calc and not turtle wow talent calc.
2. if you mouseover the items it tries to link to wowhead items and fail.

**IDs of affected creatures, items, quests or spells with a link to the relevant page:**
https://armory.turtle-wow.org/#!/home
![image](https://github.com/slowtorta/turtlewow-bug-tracker/assets/26133646/dc6e7b27-895f-407e-83a4-aa25d34236fd)
![image](https://github.com/slowtorta/turtlewow-bug-tracker/assets/26133646/559c9282-7398-4996-b429-30abf8b7330e)

**Expected behavior. Describe how it should work:**
The talents should link to: https://talents.turtle-wow.org/
If you mouseover items. It should show you the items in the turtle wow database. It does if you click on them.

**Comment by slowtorta** [comment]
We're currently working on a new version of the website, so the any issues related to a present one are not being looks into.
