### ISSUE TITLE
Prototype Thievery not working

### ISSUE THREAD

**Issue by DzikCrakehall** [slowtorta/turtlewow-bug-tracker#3858]
The quest does not work, I killed the boss 3 times, the item did not drop out, neither from the crusher nor from the goblin

1.  go to Deadmines
2.  kill Sneed
3.  get nothing. even though the droprate is set to 100% on the database

**IDs of affected creatures, items, quests or spells with a link to the relevant page:**

NPC: https://database.turtle-wow.org/?npc=643
Item: https://database.turtle-wow.org/?item=81315
Quest: https://database.turtle-wow.org/?quest=55005

the item should drop, but it doesn't drop

**Comment by Gurky-Turtle** [comment]
Try abandoning the quest and retaking it.

**Comment by twowTurtReynolds** [comment]
![image](https://github.com/slowtorta/turtlewow-bug-tracker/assets/151180101/6737afa9-1587-47ae-96d8-5db4fa0ddaa6)
Works fine.
