### ISSUE TITLE
Westfall Chicken not available

### ISSUE THREAD

**Issue by DzikCrakehall** [slowtorta/turtlewow-bug-tracker#3859]
i wanted to get westfall chicken like on 6 characters before but this time it doesn't work

1.  go to the chicken, write /chicken several times, wait until it is green
2.  after she turned green, she should give the quest CLUCK!, but she does not give it, the GM gave me this quest
3.  i turned it in after which an "egg" should appear which, looted, we get a pet, at the moment the egg does not spawn, did 3 times with GM

NPC: https://database.turtle-wow.org/?npc=620
Item: https://database.turtle-wow.org/?item=11109 ; https://database.turtle-wow.org/?item=11110
Quest: https://database.turtle-wow.org/?quest=3861

the chicken should give the quest, the egg should spawn

**Comment by Gurky-Turtle** [comment]
You might need to write /chicken 30+ times its random. Also to turn in the quest you have to use /cheer at the chicken. 

![image](https://github.com/slowtorta/turtlewow-bug-tracker/assets/90982783/02d3bda1-5a77-45ce-9ba6-42cc487b178a)
![image](https://github.com/slowtorta/turtlewow-bug-tracker/assets/90982783/4c870591-91f2-4d4b-bbc2-6e7702cdef2c)
![image](https://github.com/slowtorta/turtlewow-bug-tracker/assets/90982783/a24b42bd-a264-4c05-8e1b-db0014c4b6fc)
![image](https://github.com/slowtorta/turtlewow-bug-tracker/assets/90982783/e3a14e53-ad18-4783-9f51-db69f8beccfb)
Works as it should
