### ISSUE TITLE
Ranged Frostbolt for Paladins

### ISSUE THREAD

**Issue by Blank3ts** [slowtorta/turtlewow-bug-tracker#3860]
**Please, provide a clear description what the bug is:**
Paladins can use Frost Oil with Judgement of the Crusader to proc frostbolts when at range which is insanely powerful in PvP because it can be applied once every 10 seconds (and paladins biggest downside is mobility so it makes them even better)
**Steps to reproduce the behavior with as much detail as possible:**

1. Attach Frost Oil to weapon
2. Cast Seal of the Crusader
3. Target enemy player
4. Cast Judgement of Crusader with Frost Oil attached

**IDs of affected creatures, items, quests or spells with a link to the relevant page:**

NPC: https://database.turtle-wow.org/?npc=
Item: https://database.turtle-wow.org/?item=
Quest: https://database.turtle-wow.org/?quest=
Spell: https://database.turtle-wow.org/?spell=
Object: https://database.turtle-wow.org/?object=

**Expected behavior. Describe how it should work:**
Shouldn't happen at all, in vanilla this did not work

**Comment by TCMMatthiasFankhauser** [comment]
Thats as of now intentional since seal of the crusader is specifically changed to proc weapon effects & temporary as well as permanent enchants. Wether that's a good thing or not is up for debate, but thats sadly not a bug

**Comment by Gurky-Turtle** [comment]
https://github.com/slowtorta/turtlewow-bug-tracker/issues/3889
https://github.com/slowtorta/turtlewow-bug-tracker/issues/3860
https://github.com/slowtorta/turtlewow-bug-tracker/issues/3850
https://github.com/slowtorta/turtlewow-bug-tracker/issues/3045
