### ISSUE TITLE
Mr. Bigglesworth

### ISSUE THREAD

**Issue by vkekd** [slowtorta/turtlewow-bug-tracker#3861]
This changelog https://forum.turtle-wow.org/viewtopic.php?t=7904 says that the cat can now attack nearby maggots but if a player pulls aggro it will attack players as well
![image](https://github.com/slowtorta/turtlewow-bug-tracker/assets/110942912/0db816f2-34de-4c9f-9d8f-f3105b4d4c22)

**Comment by SabineWren** [comment]
Biggles roars when attacking you 😻. May this bug never be fixed.

**Comment by slowtorta** [comment]
Don't anger the cat.
