### ISSUE TITLE
Transmog bug

### ISSUE THREAD

**Issue by Konspaul** [slowtorta/turtlewow-bug-tracker#3866]
**Please, provide a clear description what the bug is:**

The gear transmog give visual bug and makes the gear or weapon appear as original when the gear has taken damage. To change it back to the transmogged look I must swap off and back on the gear. /reload the client does not help. Deleting WDB folder does not help either. How do I prevent the transmogged look to wear off? This is a very frustrating visual bug.

**Comment by twowTurtReynolds** [comment]
Duplicate of https://github.com/slowtorta/turtlewow-bug-tracker/issues/1400
