### ISSUE TITLE
Fashion Demands Sacrifice Quest bug

### ISSUE THREAD

**Issue by QuinZooo** [slowtorta/turtlewow-bug-tracker#3868]
**Please, provide a clear description what the bug is:**

**Steps to reproduce the behavior with as much detail as possible:**

1. Accepted quest in lvl 20+, finished it.
2. Turned it in. Got the fashion token.
3. Tried doing the quest again in lvl 40+ can't accept the quest. "Continue" button grayed out

**IDs of affected creatures, items, quests or spells with a link to the relevant page:**

NPC: https://database.turtle-wow.org/?npc=
Item: https://database.turtle-wow.org/?item=
Quest: https://database.turtle-wow.org/?quest=
Spell: https://database.turtle-wow.org/?spell=
Object: https://database.turtle-wow.org/?object=

**Expected behavior. Describe how it should work:**

**Comment by Gurky-Turtle** [comment]
drop the quest and delete your wdb folder and try turning it in after. This should fix your issue.
