### ISSUE TITLE
Fashion Demands Sacrifice - Zora Bug (Horde)

### ISSUE THREAD

**Issue by Lichbanez** [slowtorta/turtlewow-bug-tracker#3870]
The quest now starts as repeatable even before the first completition. Every 10 Levels the NPC Zora had a yellow exclamation mark that turned into a blue question mark after the first completion now this doesn't happen anymore. I logged a couple of days ago and the exclamation mark just disappeared but I never took the quest.

1. Reached level 40
2. Checked the NPC Zora
3. The quest just disappeared now only the repeatable is available

NPC: https://database.turtle-wow.org/?npc=51293
Quest: https://database.turtle-wow.org/?quest=60033

I should be able to take the quest for the first time like any other quest instead of just turning in the repeatable right off the bat.
I didn't find mention of any change about it anywhere so I suppose this isn't intended.

**Comment by Gurky-Turtle** [comment]
These quests were changed to be repeatable so they work differently than before.
