### ISSUE TITLE
'Eye of Kilrogg' dismissing summoned demon and erasing taught spells

### ISSUE THREAD

**Issue by JPMerdu** [slowtorta/turtlewow-bug-tracker#3871]
Hello,

I would like to report a bug which leads to losing all spells taught to summoned demon after casting the spell 'Eye of Kilrogg'.

I'm sharing what happened with steps down below :

1. I had an imp summoned with all skills until lvl 34 (my level) after finishing RFK dungeon while I was waiting for the 1 minute timer to summon me back outside dungeon,
2. I cast the spell 'Eye of Kilrogg',
3. After I cast the spell, my summoned demon is dismissed because 'Eye of Kilrogg' is summoned as a demon which replaces it,
4. I was summoned back from dungeon when I was controlling Eye of Kilrogg.
5. I had no demon or Eye of Kilrogg summoned when I was summoned outside dungeon,
6. When I summoned my imp, I've realized that all spells I've taught until lvl 34 were gone from spellbook and its castbar, only Firebolt Rank 1 remains.
7. All other demons still have their spells, this only affected my imp, which was my summoned demon before casting 'Eye of Kilrogg'.

I've my problem solved thanks to the GM Zinwrath and I'm openning this issue at his/her request.

**Comment by twowTurtReynolds** [comment]
![image](https://github.com/slowtorta/turtlewow-bug-tracker/assets/151180101/942ce9f8-e1ab-4e57-8e68-d1c7435b0cea)
![image](https://github.com/slowtorta/turtlewow-bug-tracker/assets/151180101/8086c242-771f-408b-b6cd-9704d6502ec8)
![image](https://github.com/slowtorta/turtlewow-bug-tracker/assets/151180101/68626128-ac85-4d28-afa2-e42a6b72a688)
I'm not able to replicate this issue without the "instanced and being summoned" part. I'll need staff help to make that testing easy.

I do hope this, very rarely but a good amount of people have reported suffering their pet skill loss, but nobody knew how.

**Comment by twowTurtReynolds** [comment]
You got it!
![image](https://github.com/slowtorta/turtlewow-bug-tracker/assets/151180101/88eee757-e5cf-403e-a54e-db4d1562f5c9)

Have an imp out in an instance, summoning and then control the eye, using GM `.tele` to leave the instance, resummon the imp and discover he has lost his spells!

**Comment by ratkosrb** [comment]
Thanks for the detailed instructions how to reproduce it. It should be fixed in the next update.

**Comment by JPMerdu** [comment]
Hello,

I hope the instructions were helpful. I was afraid to try this scenario on
other warlock pets, but loss of pet skills can be an issue for other
warlock pets too.

Don't hesitate to ask for help if needed.

Thank you for working on it,

Mertcan Sevil

ratkosrb ***@***.***>, 5 Ara 2023 Sal, 14:28 tarihinde şunu
yazdı:
