### ISSUE TITLE
Goblin ranged weapon model not loading while out of combat

### ISSUE THREAD

**Issue by SaltySw33t** [slowtorta/turtlewow-bug-tracker#3872]
Hello :)

I would like to report a bug.

My Goblin Hunter (lvl 10) doesn't hold its ranged weapon model when out of combat. I 've tried using other weapons like guns but it still doesn't work.

Here are the steps:

1. Make sure you have a goblin character with a ranged weapon and quiver with ammunition.
2. It should also have a melee weapon.
3. Press the Unsheathe shortcut twice to attempt to see the bug.

When I unsheathe my weapons the character should pull out the ranged weapon item model.

Thanks for reading!

**Comment by Aindoros** [comment]
I have a similar problem on the rogue. My throwing knives are not displayed in my hand. I thought it was an old problem or not solvable. I would like it to be solved :)

**Comment by Muigin** [comment]
This has been fixed and will be pushed in our next client patch (1.17.1)
