### ISSUE TITLE
Can't pick up fashion coin quests.

### ISSUE THREAD

**Issue by unowien** [slowtorta/turtlewow-bug-tracker#3873]
I can't pick up the fashion coin quests.  I deleted the WDB folder, disabled all addons, I do not have the quests already, and there is space in my log.  A GM asked me to make a post here.

**Comment by unowien** [comment]
The GM also tried resetting the NPC, for me.  That did not fix the issue.

**Comment by redmagejoe** [comment]
The quests are no longer picked up. It looks like they were changed to "just bring the items to the NPC" quick turn-in style quests.

**Comment by unowien** [comment]
Oh really?  I did not know that.  Let me try, real quick.  Thanks!

**Comment by unowien** [comment]
Yep that was the "issue".  Thanks.
