### ISSUE TITLE
Quest: "The Scales of War" does not appear from Lieutenant Alverold

### ISSUE THREAD

**Issue by Aeliren** [slowtorta/turtlewow-bug-tracker#3874]
**Please, provide a clear description what the bug is:**

The Alliance quest "The Scales of War" does not appear to be available from Lieutenant Alverold at Anchor's Edge in the Barrens, despite my having the prerequisite level of 15 and having completed all other quests at Anchor's Edge. Prior to this report, I submitted a ticket about it and was told that the NPC had been reset, and I further cleared my WDB to no avail.

**Steps to reproduce the behavior with as much detail as possible:**

1. Go to Anchor's Edge as a level 15 Alliance character.
2. Speak with Lieutenant Alverold to pick up the quest.

![image](https://github.com/slowtorta/turtlewow-bug-tracker/assets/96898927/47f5eab0-23f8-43c1-860a-e003ff843d24)

**IDs of affected creatures, items, quests or spells with a link to the relevant page:**

NPC: https://database.turtle-wow.org/?npc=60901
Quest: https://database.turtle-wow.org/?quest=40794

**Expected behavior. Describe how it should work:**

Lieutenant Alverold should be offering me this quest at some point, whether it has no prerequisites or whether it requires the completion of any of the other Anchor's Edge quests.

**Comment by Gurky-Turtle** [comment]
You need to have friendly reputation with Kul Tiras.

**Comment by Aeliren** [comment]
I would then like to suggest lowering the reputation requirement. As of current, it is impossible to achieve friendly status with Kul Tiras without completing quests in Lapidis Isle, a level 48-53 zone. Being a significantly higher level area than the ~20-30 quests you complete on Anchor's Edge, it breaks the sequence having to come back nearly twenty levels later, almost at level cap, for a quest listed as being within the early-to-mid levels. Even as a human with the 10% reputation bonus, completing all quests in Anchor's Edge and Davenport (Stormwind Harbor) leaves a character at 2146/3000 into neutral.

So that it can't simply be immediately accepted and so that it must require some form of investment in the faction as implied by the original requirements and the overall tone of the Anchor's Edge quests being that they recognize you as an ally of Kul Tiras for your assistance, my recommendation would be to, if possible, make the required reputation to accept the quest be 2000/3000 neutral; a nice round number that requires you to do every Kul Tiras quest available at that level.

**Comment by Gurky-Turtle** [comment]
I'll reopen this as you are probably correct seeing it's a level 15 quest.

**Comment by Gurky-Turtle** [comment]
Should be fixed in the next update.
