### ISSUE TITLE
Turtle WoW female Goblin hair and face clipping.

### ISSUE THREAD

**Issue by spragual** [slowtorta/turtlewow-bug-tracker#3876]
**Please, provide a clear description what the bug is:**
Head gear clipping through female Goblin hair.
**Steps to reproduce the behavior with as much detail as possible:**

1. Be a female Goblin.
2. Put on certain helms.
3. Watch your hair or other facial features clip through.

**IDs of affected creatures, items, quests or spells with a link to the relevant page:**
I have only found a few instances of helms clipping through so there are more than likley a lot more. Reskins of the items that I list below most likley have the same issues. The pieces listed below are the only ones that I have found. I did not check how these items look on the male Goblins only the female. I checked some items on Atlas Loot to find a few that is not a reskin but still clips through the hair/head.

![Turtle WoW bug report](https://github.com/slowtorta/turtlewow-bug-tracker/assets/138624164/4ea5338b-51c1-4399-aa6a-1ea288c22658)
 This picture is an example of the clipping

https://database.turtle-wow.org/?item=3732 Hair clipping through front
https://database.turtle-wow.org/?item=16698 Nose clipping through shrouded front
https://database.turtle-wow.org/?item=16731 Hair clipping through back
https://database.turtle-wow.org/?item=81007 Mask clipping through face
https://database.turtle-wow.org/?item=9492 Hair clips through top
https://database.turtle-wow.org/?item=6686 Hair clipping through top
https://database.turtle-wow.org/?item=10763 Hair clipping through back of the helm
https://database.turtle-wow.org/?item=9394 Hair clipping through top
https://database.turtle-wow.org/?item=9431 Slight clipping through back
https://database.turtle-wow.org/?item=9420 Slight clipping at the very top
https://database.turtle-wow.org/?item=17734 Slight clipping at the very top

**Expected behavior. Describe how it should work:**
There should be no clipping through the head or item on head

**Comment by twowTurtReynolds** [comment]
Duplicate of https://github.com/slowtorta/turtlewow-bug-tracker/issues/3368
