### ISSUE TITLE
Clampjaw classified as a Humanoid

### ISSUE THREAD

**Issue by bitchqueenoftheuniverse** [slowtorta/turtlewow-bug-tracker#3879]
Clampjaw (level 44) NPC in Dustwallow Marsh, is described as a crocolisk (therefore a Beast) in its associated quest, but it's actually classified as a humanoid.

NPC: https://database.turtle-wow.org/?npc=60632

**Comment by Gurky-Turtle** [comment]
Should be fixed in the next update.
