### ISSUE TITLE
Gnome hunters are missing the gnome racial passive Arcane Resistance

### ISSUE THREAD

**Issue by Tinyfin-github** [slowtorta/turtlewow-bug-tracker#388]
Gnome hunters are missing the gnome racial passive Arcane Resistance

https://database.turtle-wow.org/?spell=20592  Arcane Resistance

![image](https://user-images.githubusercontent.com/83077166/137848081-abcf1959-9ccf-4f6a-934b-ce32b733a59a.png)

**Comment by slowtorta** [comment]
This will be fixed on the next server update.
