### ISSUE TITLE
Quest "The Price of Leadership" has abruptly ended quest text.

### ISSUE THREAD

**Issue by burmanj** [slowtorta/turtlewow-bug-tracker#3882]
**Please, provide a clear description what the bug is:**
Image from in game quest log:  https://ibb.co/m6GCHfK
The quest text is ending very abruptly, not how it is supposed to be as seen in the database.

**IDs of affected creatures, items, quests or spells with a link to the relevant page:**
Quest: https://database.turtle-wow.org/?quest=40805

**Comment by Gurky-Turtle** [comment]
Fixed in the next update
