### ISSUE TITLE
Steelsnap's fear ability causes permanent speed boost to character

### ISSUE THREAD

**Issue by MelvinMeru** [slowtorta/turtlewow-bug-tracker#3884]
**Please, provide a clear description what the bug is:** My character runs like the flash after being feared by Steelsnap.

**Steps to reproduce the behavior with as much detail as possible:**

1. Did the quest Steelsnap in Thousand Needles.
2. Steelsnap used it's fear howl.
3. Howl makes player run real quick along with fear.
4. After fear effect is gone, the speed boost remains.

**IDs of affected creatures, items, quests or spells with a link to the relevant page:**

NPC: https://database.turtle-wow.org/?npc=4548
Item: https://database.turtle-wow.org/?item=
Quest: https://database.turtle-wow.org/?quest=1131
Spell: https://database.turtle-wow.org/?spell=
Object: https://database.turtle-wow.org/?object=

**Expected behavior. Describe how it should work:**
Speed boost should not apply after fear wears off.

**Comment by Gurky-Turtle** [comment]
I am unable to reproduce this also the fear is not done by Steelsnap his adds (Pesterhide Snarler) do the fear. 

The fear's name is Intimidating Growl.

I attempted to reproduce this over 20 times and each time the speed fell off when the debuff did.
