### ISSUE TITLE
Agal's ambusher has no sheathe model

### ISSUE THREAD

**Issue by Hirvi199** [slowtorta/turtlewow-bug-tracker#3885]
**Please, provide a clear description what the bug is:**

When you equip Agal's ambusher, theres no model of the dagger. It looks like you have nothing equipped

**Steps to reproduce the behavior with as much detail as possible:**

1. Finish level 10 quest "A Decisive Blow" in Teldrassil
2. Equip "Agal's Ambusher" dagger 

**IDs of affected creatures, items, quests or spells with a link to the relevant page:**

[Item: https://database.turtle-wow.org/?item=](https://database.turtle-wow.org/?item=51818)

**Expected behavior. Describe how it should work:**

Dagger should be visible when equipped

**Comment by Dragunovi** [comment]
Fixed with Patch 1.17.1.
