### ISSUE TITLE
Please fix paladins in PvP

### ISSUE THREAD

**Issue by jaimmortal** [slowtorta/turtlewow-bug-tracker#3889]
**Please, provide a clear description what the bug is:**

Paladins are extremely overpowered in PvP.

**Steps to reproduce the behavior with as much detail as possible:**

1. Paladins have bubble, they are the only class that can become complete invulnerable to literally all effects in the entire game.
2. Paladins do extremely high burst DPS. With the paladin rework, I regularly get crit for a total of 3000 dmg in one global.
3. Paladins have BoF, two instant cast ranged stuns, and now with frost oil they have a 10 second cooldown, instant cast, ranged slow.
4. Paladins can instant cast cleanse dots on themselves.

**IDs of affected creatures, items, quests or spells with a link to the relevant page:**

**Expected behavior. Describe how it should work:**

Paladins are completely overpowered in PvP. It is not fun. 50% of alliance pvp players are paladins. You MUST understand that there is a reason why 50% of alliance PvPers are RET/SHOCK paladins. The class is OP. Nobody plays holy paladins. It's because the class is horribly OP, and horribly unfun to play against. Pleaaaaaaaase do something about this. It's insanity.

**Comment by jaimmortal** [comment]
There is this thread on the forums which says to report here:

https://forum.turtle-wow.org/viewtopic.php?t=8090

**Comment by Gurky-Turtle** [comment]
https://github.com/slowtorta/turtlewow-bug-tracker/issues/3889
https://github.com/slowtorta/turtlewow-bug-tracker/issues/3860
https://github.com/slowtorta/turtlewow-bug-tracker/issues/3850
https://github.com/slowtorta/turtlewow-bug-tracker/issues/3045
