### ISSUE TITLE
Gnome hunters  can't speak gnomish but can speak dwarven

### ISSUE THREAD

**Issue by Tinyfin-github** [slowtorta/turtlewow-bug-tracker#389]
Gnome hunters  can't speak gnomish but can speak dwarven

![WoW_OXCXWDjQXv](https://user-images.githubusercontent.com/83077166/137964965-eb5ea27e-162a-46ae-86b5-b28b717636d5.png)

**Comment by slowtorta** [comment]
Thank you. This will be fixed on the next server update.
