### ISSUE TITLE
Honor Rank still 0 for character

### ISSUE THREAD

**Issue by Heimdallr666** [slowtorta/turtlewow-bug-tracker#3890]
**Please, provide a clear description what the bug is:**
Character name Garod, after the bug with removal of PVP ranks, still didn't get them back. I literally have rank 0, after 2 or 3 honor resets I got nothing more, still stuck at 0

**Steps to reproduce the behavior with as much detail as possible:**

n/a

**IDs of affected creatures, items, quests or spells with a link to the relevant page:**
n/a

**Expected behavior. Describe how it should work:**

I should have proper honor rank

**Comment by Gurky-Turtle** [comment]
Can you clear your wdb folder and then take a screenshot of your Honor window?

**Comment by GrizB37** [comment]
You talked to an NPC and then hid your rank... This might have been unintentional.

**Comment by Heimdallr666** [comment]
> You talked to an NPC and then hid your rank... This might have been unintentional.

Ok...My intention was to hide my PVP title above my head, what you're saying is that it also hides PVP rank in Honor window along with bar progress?

**Comment by GrizB37** [comment]
> > You talked to an NPC and then hid your rank... This might have been unintentional.
> 
> Ok...My intention was to hide my PVP title above my head, what you're saying is that it also hides PVP rank in Honor window along with bar progress?
> 
> After WDB folder cleanup:
> 
> ![obraz](https://user-images.githubusercontent.com/106585270/252263443-d659775e-9233-45b6-aba4-c4d214464435.png)

Yes, if you hide Rank, you can't see your own progress... Only way is to make rank available again, if you want to hide it above your head, go into options and unstick "Player Titles"

**Comment by Heimdallr666** [comment]
Ok, then I don't think it's a problem, just a bigger inconvenience - If you got any title in the game(while we  have only few, but it's fun to have them) the PVP title doesn't mix with up well, so the only option to make it somehow work is stop seeing your PVP progress, that's...inconvenient

**Comment by Heimdallr666** [comment]
Closing as this is not an issue, however would be great to be able to hide just the PVP title, so instead of knight Lieutenant Immortal a Character could be just Immortal or similar.
