### ISSUE TITLE
Unopenable Darkmoon Faire Fortune

### ISSUE THREAD

**Issue by tojothethief** [slowtorta/turtlewow-bug-tracker#3891]
**Please, provide a clear description what the bug is:**
If you already have a particular Sayge's Fortune (in my case it was the one leading to the Deadmines for treasure), and then attempt to open a DMF fortune with the same Sayge's Fortune, DMF fortunes from thereon become entirely unopenable.
This may also mean other openable items involving unique items can suffer from the same bug

**Steps to reproduce the behavior with as much detail as possible:**

1. Have a particular Sayge's Fortune
2. Try to open a DMF fortune with the same Sayge's Fortune
3. Profit

**IDs of affected creatures, items, quests or spells with a link to the relevant page:**

https://database.turtle-wow.org/?item=19422
https://database.turtle-wow.org/?item=19424

**Expected behavior. Describe how it should work:**
Should always be able to open fortunes (though not loot additional unique items of course)

**Comment by Gurky-Turtle** [comment]
This only happens for the quest fortunes and it working as intended https://www.wowhead.com/classic/item=19424/sayges-fortune-24

The quest fortunes are unique so you can only have 1 of the same item.
