### ISSUE TITLE
AQ20 pre-60 wrong message display while entering

### ISSUE THREAD

**Issue by marctorne** [slowtorta/turtlewow-bug-tracker#3892]
AQ20 is showing a wrong message while entering if you are not 60.
![aq20](https://github.com/slowtorta/turtlewow-bug-tracker/assets/31748821/95a1307c-7e0f-47f2-921e-93f3016da21e)

**Comment by marctorne** [comment]
Forgot to mention, I'm 59.

**Comment by Gurky-Turtle** [comment]
Fixed in the next update, aq20 and aq40 require level 60 to enter.
