### ISSUE TITLE
wrong drop rate: AQ40

### ISSUE THREAD

**Issue by beberexha102** [slowtorta/turtlewow-bug-tracker#3894]
related to:
https://github.com/slowtorta/turtlewow-bug-tracker/issues/3822

Drop Rates for Imperial Qiraji Regalia and Imperial Qiraji Armaments are less than classic.  It's 4% in Turtle WoW.

Blizzlike drop rate is 6%
https://www.wowhead.com/classic/item=21232/imperial-qiraji-armaments
https://www.wowhead.com/classic/item=21237/imperial-qiraji-regalia

This is a critical bug considering large numbers of AQ40 runs each week.

**Comment by twowTurtReynolds** [comment]
Wowhead's drop rates are crowdsourced and are not a source of truth. If you do think this should be changed, put in a post in the suggestions forum.
