### ISSUE TITLE
Still Believing Quest (turn in) Bugged No Rewards after short maintenance

### ISSUE THREAD

**Issue by Backtoroots1** [slowtorta/turtlewow-bug-tracker#3895]
**Please, provide a clear description what the bug is:**

**Steps to reproduce the behavior with as much detail as possible:**

1.i turned 160 texts in for like 4-5hrs
2. waited relog send from alt some items may something stuck in mail
3. still nothing gain (no bags of encryption)

**IDs of affected creatures, items, quests or spells with a link to the relevant page:**

NPC: https://database.turtle-wow.org/?npc=15194
Item: https://database.turtle-wow.org/?item=20469
Quest: https://database.turtle-wow.org/?quest=8324
Spell: https://database.turtle-wow.org/?spell=
Object: https://database.turtle-wow.org/?object=

**Expected behavior. Describe how it should work:**
You turn in 10 texts and after a time you  get a bag. Its not working also i did the 16x turn ins before the short maintenance today

**Comment by Gurky-Turtle** [comment]
You should have the item by now, it takes longer than 4-5 hours before the mail is sent. 

@Backtoroots1 let me know
