### ISSUE TITLE
Life Giving Gem has a wrong effect

### ISSUE THREAD

**Issue by balakethelock** [slowtorta/turtlewow-bug-tracker#3897]
**Please, provide a clear description what the bug is:**
Life Giving Gem does not increase current health on use, and does not remove any on running out either. (Yes it heals, but that's not the same as increasing current health)
Essentially the ability has three components on use. two are working fine (increase max health, heal). one is missing (increase current health)

**Steps to reproduce the behavior with as much detail as possible:**

1. Be low health
2. Use lifegiving gem
3. Find that your hp only increases by what you were healed for. This is incorrect. It should be a bit more than that
4. Find that when it runs out, you don't lose any current health. This is also incorrect. When lifegiving gem runs out, the warrior should lose some health.

**IDs of affected creatures, items, quests or spells with a link to the relevant page:**

Item: https://database.turtle-wow.org/?item=19341
spells: https://database.turtle-wow.org/?search=gift+of+life

**Expected behavior. Describe how it should work:**
[like in the video](https://www.youtube.com/watch?v=abQwo1wM0Ec)
More details [here](https://github.com/vmangos/core/pull/2064) vmangos/core#2064

**Comment by boyolad** [comment]
![image](https://github.com/slowtorta/turtlewow-bug-tracker/assets/115322800/3132357a-90c9-4ab5-85f8-03034675751a)
Before Using Lifegiving Gem. 
![image](https://github.com/slowtorta/turtlewow-bug-tracker/assets/115322800/99f25f0e-077d-4568-bf38-a1c2befab321)
Used Lifegiving Gem. Maximum Health Increased by the amount healed.
![image](https://github.com/slowtorta/turtlewow-bug-tracker/assets/115322800/c733776b-72fd-41ed-b758-668ab43abb3c)
When Lifegiving Gem Ran Out.


Secondary Test Looking at Max HP.
![image](https://github.com/slowtorta/turtlewow-bug-tracker/assets/115322800/3a4647b1-3933-42ba-acde-5678d2d5917e)
Before Lifegiving Gem.
![image](https://github.com/slowtorta/turtlewow-bug-tracker/assets/115322800/8aae134e-0be3-4778-9fda-2fad84d2c69f)
Using Lifegiving Gem.

Tested.
