### ISSUE TITLE
Tome of Valor quest

### ISSUE THREAD

**Issue by Rakuhuji** [slowtorta/turtlewow-bug-tracker#3899]
**Please, provide a clear description what the bug is:**
I cant retake the failed quest. Even after I abandoned the failed quest and even deleted the Book of Valor item and game cache folder the NPC in SW still doesn't show up with the quest.

**Steps to reproduce the behavior with as much detail as possible:**

1. I picked up the quest in Cathedral of Light from NPC Duthorian Rall. He gave me a quest item the Book/Tome of Valor which when clicked gave me a new quest to go to Westfall and speak to the NPC Daphne Stilwell.
2. When I got to Daphne Stilwell in Westfall I talked to her and started the quest. I was in a party with one more paladin. We failed to protect Daphne and she died and it said in my quest log that I failed my quest.
3. So I had the quest failed but the other paladin decided to start the quest again because a hunter came to help us, but now he was the one who talked to Daphne.
4. This time we finished the quest and a golden question marker popped up on my minimap but it didnt pop up above Daphne it was just on the minimap. So basically I couldn't turn it in.
5. In the log it said it was failed but it also said I completed it. So I went back to Cathedral of Light, abandoned the quest and deleted the quest item so I could take the quest again from Duthorian Rall. But the quest didn't even come up.
6. I deleted the cache folder, reseted the game, abandoned the quest, deleted the quest item and the quest still doesn't show up.
**IDs of affected creatures, items, quests or spells with a link to the relevant page:**

NPC: https://database.turtle-wow.org/?npc=Duthorian Rall
Item: https://database.turtle-wow.org/?item=Tome of Valor
Quest: https://database.turtle-wow.org/?quest=The Tome of Valor
Spell: https://database.turtle-wow.org/?spell=
Object: https://database.turtle-wow.org/?object=

**Expected behavior. Describe how it should work:**
I was expecting the quest to show up at Duthorian Rall. The NPC who started this quest chain for me but it did not.

**Comment by redmagejoe** [comment]
https://database.turtle-wow.org/?quest=1651

You seem confused.  The quest you failed starts from Daphne.  You have already turned in the quest started from the book, which leads to the quest started from Duthorian, which leads to Daphne who starts the quest you failed.  You have to wait for Daphne to respawn to retry the quest.

**Comment by Rakuhuji** [comment]
That is correct. I didn't abandon the quest when I was near Daphne but when I was near Duthorian thinking he is the quest starter. My bad im just a moron

**Comment by redmagejoe** [comment]
Be sure to close your ticket if the issue is resolved to help out the devs trying to keep this todo list organized.

**Comment by Rakuhuji** [comment]
Got it. Ill do it now and if it works ill close it
