### ISSUE TITLE
Randal Portman is part of the Orgrimmar faction

### ISSUE THREAD

**Issue by bitchqueenoftheuniverse** [slowtorta/turtlewow-bug-tracker#3900]
I'm not exactly sure if this is a bug, but i'm reporting it.
Randal Portman an undead vendor in Steepcliff Port (Undercity faction hub) in Tirisfal Glades is marked as part of the Orgrimmar faction.

NPC: https://database.turtle-wow.org/?npc=91983

**Comment by Gurky-Turtle** [comment]
fixed in the next update
