### ISSUE TITLE
Gijillim Island has no spirit healer, you revive in Booty Bay

### ISSUE THREAD

**Issue by Lilithian** [slowtorta/turtlewow-bug-tracker#3903]
When you die on Gijillim Island (custom content) you revive by Booty Bay spirit healer.
This forces you to either revive on spirit healer, taking ressurection sickness and item damage, or to run across ocean and risk falling through texture.
Gijillim Island needs it's own spirit healer to be linked to.

How to reproduce the bug? Die on Gijillim Island.

Expected behaviour? Appear on Gijillim Island spirit healer, which needs to be added to the game as of now.

**Comment by slowtorta** [comment]
Fixed in 1.17.0.
