### ISSUE TITLE
The quest "Shellcoins" doesn't start

### ISSUE THREAD

**Issue by Lichbanez** [slowtorta/turtlewow-bug-tracker#3907]
The NPC in Tanaris no longer start this quest.

1. Go to Tanaris
2. Talk to Elodia 

NPC: https://database.turtle-wow.org/?npc=80999
Quest: https://database.turtle-wow.org/?quest=80381

The quest should start normally, without it it will be impossible to complete the summer outfit.

**Comment by slowtorta** [comment]
This quest is no longer available for players.
