### ISSUE TITLE
Turtle WoW quest 'WANTED: Hole Escapee' does not immediately turn the mob friendly after following you

### ISSUE THREAD

**Issue by Reiiama** [slowtorta/turtlewow-bug-tracker#3908]
**Please, provide a clear description what the bug is:**

**Steps to reproduce the behavior with as much detail as possible:**

1. Take 'WANTED: Hole Escapee' from Sparkwater Port's WANTED board
2. Travel to Farwatch Post in the Barrens and talk to Baxxil.
3. Fight Baxxil until he gets low enough to surrender, then speak to him again.
4. Baxxil will begin to follow you, but he will attack you while he follows you 5-10 times before becoming non-hostile. You cannot attack him while he attacks you. Other players can actually get aggro from him in this state by healing the person being attacked.

**IDs of affected creatures, items, quests or spells with a link to the relevant page:**

NPC: https://database.turtle-wow.org/?npc=91297
Quest: https://database.turtle-wow.org/?quest=55048

**Expected behavior. Describe how it should work:**
Baxxil should follow you without attacking you, and not attack others.

**Comment by twowTurtReynolds** [comment]
He is not being naughty with me...
![image](https://github.com/slowtorta/turtlewow-bug-tracker/assets/151180101/eb667265-1186-4e80-9442-3057a2c4d56c)

**Comment by Reiiama** [comment]
This was fixed in a prior update.
