### ISSUE TITLE
Holy Diadem drop chance

### ISSUE THREAD

**Issue by Seidaken** [slowtorta/turtlewow-bug-tracker#3914]
Holy diadem has lower drop chance than it should.
Wowhead says, that it must be 5%, 4% and 3%, but we have 1.2% on every NPC.
Also this NPCs drop lots of another loot, like common NPCs in the zone, that they mustn't drop.

**IDs of affected creatures, items, quests or spells with a link to the relevant page:**

NPC: 
Caretaker Nevlin must have 5%
https://database.turtle-wow.org/?npc=2780
https://www.wowhead.com/classic/npc=2780/caretaker-nevlin

Caretaker Weston 3%
https://database.turtle-wow.org/?npc=2781
https://www.wowhead.com/classic/npc=2781/caretaker-weston

Caretaker Alaric 4%
https://database.turtle-wow.org/?npc=2782
https://www.wowhead.com/classic/npc=2782/caretaker-alaric

Item: 
Holy diadem
https://database.turtle-wow.org/?item=2623
https://www.wowhead.com/classic/item=2623/holy-diadem

**Expected behavior. Describe how it should work:**
They should have another Diadem's drop chance and shorter loot table.

**Comment by Gurky-Turtle** [comment]
https://web.archive.org/web/20060613220942/http://wow.allakhazam.com/db/mob.html?wmob=2780
https://web.archive.org/web/20060613220942/http://wow.allakhazam.com/db/mob.html?wmob=2781
https://web.archive.org/web/20060515045242/http://wow.allakhazam.com/db/mob.html?wmob=2782

If you check your links again you can see the wowhead numbers change. I will leave this open but the values on wowhead are not accurate it seems and fluctuate as more of a guess.
