### ISSUE TITLE
High elf cannot do the quest "Investigate the Blue Recluse"

### ISSUE THREAD

**Issue by leisiling** [slowtorta/turtlewow-bug-tracker#3919]
**Please, provide a clear description what the bug is:**

I am a high elf mage. I cannot do a quest named "Investigate the Blue Recluse". Because I cant use a item named "Cantation of Manifestation" that must be used for this quest. It can be used by 'Human, Orc, Dwarf, Night Elf, Undead, Tauren, Gnome, Troll'.

**Steps to reproduce the behavior with as much detail as possible:**
1.
2. 
3. 

**IDs of affected creatures, items, quests or spells with a link to the relevant page:**
Item: https://database.turtle-wow.org/?item=7308
Quest: https://database.turtle-wow.org/?quest=1920

**Expected behavior. Describe how it should work:**
High elf mages should be able to use this item, so we can do the quest. 
If it is a bug, please fix it.  
If someone already reported, please forgive me report it again. I dont kown how to check if this bug is already reported by others.  
Thank you very much. Turtle wow is great. You are doing a great job.

**Comment by slowtorta** [comment]
The item doesn't exclude High Elves, please make sure to clear your WDB folder and try again!
