### ISSUE TITLE
Quest Falrin's Vendetta

### ISSUE THREAD

**Issue by Ttourro** [slowtorta/turtlewow-bug-tracker#3924]
According to data base, the drop chance of quest item [Ogre Warbeads] mush be 80 %  (https://classicdb.ch/?item=21982)
I killed maybe 100 of ogres and get only 3 quest items. in tWow sserver drop chanse is incorrect.

**Comment by Gurky-Turtle** [comment]
That database is not accurate the drop chance is far lower than that. Please use our database website.
