### ISSUE TITLE
Enchant Gloves - Greater Agility Bug

### ISSUE THREAD

**Issue by Saviorr** [slowtorta/turtlewow-bug-tracker#3926]
**Please, provide a clear description what the bug is:**
enchant gloves - greater agility +7 agility to gloves doesnt work 
**Steps to reproduce the behavior with as much detail as possible:**
when im trying to enchant glove it occurs an error  
1.  Enchant Gloves - Greater Agility
2. 
3. 

**IDs of affected creatures, items, quests or spells with a link to the relevant page:**

NPC: https://database.turtle-wow.org/?npc=
Item: https://database.turtle-wow.org/?item=
Quest: https://database.turtle-wow.org/?quest=
Spell: https://database.turtle-wow.org/?spell=
Object: https://database.turtle-wow.org/?object=

**Expected behavior. Describe how it should work:**
it should enchant gloves to +7 agility as intended

**Comment by Gurky-Turtle** [comment]
This will need more information, I cannot reproduce this. 

I have a feeling you are relaying on a addon that isnt programmed to look for this enchant.
