### ISSUE TITLE
Hinterlands Eagle pets incorrectly use their idle animation while moving at default speed

### ISSUE THREAD

**Issue by patrycos** [slowtorta/turtlewow-bug-tracker#3928]
**Please, provide a clear description what the bug is:**
Hinterlands Eagle pets use the idle animation while moving exactly at default speed. Any increases or reductions to the pet's movement speed cause the correct animation to be played.
Bug showcase: https://www.youtube.com/watch?v=Ldm2OQoaTMU

**Steps to reproduce the behavior with as much detail as possible:**

1. Tame a Hinterlands Eagle in the Hinterlands
2. Have the bird follow you, send it after enemy target or use Eyes of the Beast to directly control the pet
3. The pet will incorrectly use its idle animation if moving while not under effect of any modifiers to movement speed
4. The pet will use correct animations if moving at non-default speed - for example while catching up with the Hunter out of combat, with Dash active (Hinterlands Eagles know Dash Rank 2 by default) or while controlled with Eyes of the Beast and moving with RP walk speed (by default RP walk is toggled with the "/" key)

**IDs of affected creatures, items, quests or spells with a link to the relevant page:**
Hinterlands Eagle NPC: https://database.turtle-wow.org/?npc=80816

**Expected behavior. Describe how it should work:**
Pet should not ever use its idle animation while moving, and instead use its default flight animation

**Comment by ProfGiggles** [comment]
I am bumping this as I have observed that this issue still exists as of today. The Amani Eagle found near the Stonetalon mountains has the same issue of defaulting to its idle animation while moving, and not under effect of any modifier.
Furthermore I have observed that both of these birds fly really low to the ground. It would look better if their minimum altitude was increased.

**Comment by Muigin** [comment]
This will be fixed in the next client patch (1.17.1)
