### ISSUE TITLE
Warlord's Dragonhide Epaulets wrong model

### ISSUE THREAD

**Issue by Melvsta** [slowtorta/turtlewow-bug-tracker#3929]
**Please, provide a clear description what the bug is:**
The rank 13 druid pvp shoulders, [Warlord's Dragonhide Epaulets] currently use the rogue version of the set [Warlord's Leather Spaulders].

**Steps to reproduce the behavior with as much detail as possible:**

1. Check the set in game via atlasloot or any other means and you will notice all the pieces except the shoulders have blue stripes though them, because that's the rogue version.
2. https://i.imgur.com/hTFnXch.png here is a link to the correct looks
3. https://i.imgur.com/5ArVwgB.png here is a link to the rogue version, as you can see the shoulders are the same.

**IDs of affected creatures, items, quests or spells with a link to the relevant page:**

NPC: https://database.turtle-wow.org/?npc=
Item: https://database.turtle-wow.org/?item=16551 , https://database.turtle-wow.org/?item=16562
Quest: https://database.turtle-wow.org/?quest=
Spell: https://database.turtle-wow.org/?spell=
Object: https://database.turtle-wow.org/?object=

**Expected behavior. Describe how it should work:**
The Warlord's Dragonhide Epaulets should have a different model as it currently uses the rogue one.

**Comment by GrizB37** [comment]
It's also the Helmet. 
Another post here https://github.com/slowtorta/turtlewow-bug-tracker/issues/3901

It was actually this way in Vanilla, and wasn't fixed by Blizzard until Tbc, where they recoloured the rest of the Druid set to match. So the Blue/Red versions probably isn't in the files for 1.12 client for the Devs to change... They'd have to pull it from Tbc client

**Comment by GrizB37** [comment]
Would be nice if the Devs could update the look so druids on horde don't look like mismatched rogue set copiers XD Even thought I do realise bug wasn't fixed until Tbc.

**Comment by Dragunovi** [comment]
Attempted a fix which should come with 1.16.6, reopen if it stays the same after the patch is released.

**Comment by GrizB37** [comment]
> Attempted a fix which should come with 1.16.6, reopen if it stays the same after the patch is released.

Didn't work, Still using Rogue Colours :(
