### ISSUE TITLE
Lard not granting rested status when nearby & trick or treating not working

### ISSUE THREAD

**Issue by tazdinger** [slowtorta/turtlewow-bug-tracker#393]
**Please, provide a clear description what the bug is:**
 Lard the innkeeper at Revantusk Village is not granting rested status when standing next to him. (You only get rested status when you go upstairs from the innkeeper) He also won't let you trick or treat despite having the dialogue option to do so. (nothing happens when you click on the option)
**Steps to reproduce the behavior with as much detail as possible:**

1. Stand next to Lard at Revantusk Village
2. Talk to him and choose the "Trick or Treat" option.
3. 

**IDs of affected creatures, items, quests or spells with a link to the relevant page:**

NPC: https://database.turtle-wow.org/?npc=14731
Item: https://database.turtle-wow.org/?item=
Quest: https://database.turtle-wow.org/?quest=
Spell: https://database.turtle-wow.org/?spell=24751
Object: https://database.turtle-wow.org/?object=

**Expected behavior. Describe how it should work:**
Standing within interact distance of an innkeeper should give you rested status and the innkeeper should give you a treat bag or trick you when choosing the 'trick or treat' dialogue option.

**Comment by slowtorta** [comment]
Resting is working as intended, NPCs don't give it, areas do. Halloween issues are known, to be fixed till the next year.
