### ISSUE TITLE
wrong drop rate: BWL

### ISSUE THREAD

**Issue by beberexha102** [slowtorta/turtlewow-bug-tracker#3931]
Elementium Ore drop rate is wrong. in turtle wow, it's only 8%. (https://database.turtle-wow.org/?item=18562)
Blizzard like should be: 34%

https://www.wowhead.com/classic/item=18562/elementium-ore

please fix.

**Comment by Gurky-Turtle** [comment]
view this page https://www.wowhead.com/classic/npc=13996/blackwing-technician it says 7% I don't think this is a bug. 

You can even see here it is not 34% https://web.archive.org/web/20060720204600/http://wow.allakhazam.com/db/mob.html?wmob=13996
