### ISSUE TITLE
Created a character and after a day appearance changed

### ISSUE THREAD

**Issue by Zatez** [slowtorta/turtlewow-bug-tracker#3933]
**Please, provide a clear description what the bug is:**

After install and setup I created a character, Zatez, after I logged out for a day his appearance has changed.
**Steps to reproduce the behavior with as much detail as possible:**

I created a character, undead warlock, bald hair, jaw missing detail. I played for an hour or so.
 A friend hopped on, and I created a character to play with them, druid, I accidently enabled hardcore mode on that druid, so I created another druid. Played on that yesterday and today. 
I installed addons today, PFui, Atlasloot, AUX, bettercharachterstats, mail, and pfquest.
Went offline, then came back to lvl warlock and noticed his appearance in character select was different. Logged inot him anyway just in case and saw his appearance was the same as select screen. Hair with a tilted jaw detail.
I opened a ticket and deleted the WDB folder and sadly it didn't fix the issue.

**IDs of affected creatures, items, quests or spells with a link to the relevant page:**

NPC: https://database.turtle-wow.org/?npc=
Item: https://database.turtle-wow.org/?item=
Quest: https://database.turtle-wow.org/?quest=
Spell: https://database.turtle-wow.org/?spell=
Object: https://database.turtle-wow.org/?object=

**Expected behavior. Describe how it should work:**

**Comment by twowTurtReynolds** [comment]
Please contact a GM.
