### ISSUE TITLE
Cure Poison curing more than one poison

### ISSUE THREAD

**Issue by Raapho** [slowtorta/turtlewow-bug-tracker#3936]
**Please, provide a clear description what the bug is:**

Druid Spell Cure Poison 
https://database.turtle-wow.org/?spell=526
cleared two different poisons at once.

**Steps to reproduce the behavior with as much detail as possible:**

1. Find Defias Night Blade (Addle's Stead, Duskwood)
2. Get poisoned by Poison (https://database.turtle-wow.org/?spell=744) and Slowing Poison (https://database.turtle-wow.org/?spell=8601)
3. Cast Cure Poison (https://database.turtle-wow.org/?spell=526)

**IDs of affected creatures, items, quests or spells with a link to the relevant page:**

NPC: https://database.turtle-wow.org/?npc=909
Spell: https://database.turtle-wow.org/?spell=526

**Expected behavior. Describe how it should work:**
Cure Poison should, per description, only cure one instance of poison per cast.

**Comment by Raapho** [comment]
I might be wrong here, as Slowing Poison is cleared when shifting out of Cat Form, so it might just have seemed as if Cure Poison cleared both different poisons.

**Comment by Gurky-Turtle** [comment]
it only cures one, it is most likely what the person above said.
