### ISSUE TITLE
Several Warlock Pet spells suddenly are not working anymore on "auto-cast-mode"

### ISSUE THREAD

**Issue by Marschierpulver** [slowtorta/turtlewow-bug-tracker#3938]
**Warlock Pets are not summoning certain spells automatically again. For example Imp is not phase shifting anymore. And also not giving automatic blood pact. But still casting automatic fire shields. Succubus is not going invesible anymore again automatically. Automatic spells casting (golden frame) was activated and deactivated several times already.:**

**Steps to reproduce the behavior with as much detail as possible:**

1. For example: Summon Succubus // Summon imp
2. Activate automatic invisibility // activate automatic phase shift (golden frame)
3. Wait for automatic action by pet - nothing happens
4. Manual acitivation of pet spells still does work
5. Pet is still autocasting some spells e.g. fire shield with imp. No clear reason why to identify for me.

**IDs of affected creatures, items, quests or spells with a link to the relevant page:**

NPC: https://database.turtle-wow.org/?npc=
Item: https://database.turtle-wow.org/?item=
Quest: https://database.turtle-wow.org/?quest=
Spell:
https://database.turtle-wow.org/?spell=4511
https://database.turtle-wow.org/?spell=11769
https://database.turtle-wow.org/?spell=11769

Object: https://database.turtle-wow.org/?object=

**Expected behavior. Describe how it should work:**
Usually when you set the pet's spell on auto-cast (golden frame as mark) the pet uses the spell by itself in an adaquate situation. For some reason this suddenly stopped working now for me at level 57.

**Comment by jameyboor** [comment]
Fixed on next update.
