### ISSUE TITLE
Riding skill 75/75 not working

### ISSUE THREAD

**Issue by Steco76** [slowtorta/turtlewow-bug-tracker#3939]
Hi there,
**Please, provide a clear description what the bug is:**

1. riding skill for 60% is not working (https://database.turtle-wow.org/?spell=33389)
2. Mountspeed is Level/2 for turtle mount and the regular mount

**Steps to reproduce the behavior with as much detail as possible:**

1. bought the riding skill (see screenshots)
2. bought the mount 
3. slow speed (tried relogging and all other stuff) 

![SCR-20230716-icuh](https://github.com/slowtorta/turtlewow-bug-tracker/assets/139595906/dad2e5f9-7dff-4149-bd49-7420107229b2)
![SCR-20230716-ifzd](https://github.com/slowtorta/turtlewow-bug-tracker/assets/139595906/acbf3c7f-f8ac-4463-ba4d-9d722bf50339)
![SCR-20230716-igdd](https://github.com/slowtorta/turtlewow-bug-tracker/assets/139595906/f921dee5-ca92-492d-9e2d-4ae6ef4f7308)
![SCR-20230716-ifqg](https://github.com/slowtorta/turtlewow-bug-tracker/assets/139595906/d0579760-8a96-4d33-89c5-6eb0dfcf0060)

**Comment by Gurky-Turtle** [comment]
Create a ticket with the gms it looks like you are missing either the spell or the skill you have to have both in order to get the riding bonus. They can fix this for you. 

I have not been able to reproduce this.
