### ISSUE TITLE
Ravenclaw Servant in Silverpine Forest

### ISSUE THREAD

**Issue by Footstomp** [slowtorta/turtlewow-bug-tracker#3940]
**Please, provide a clear description what the bug is:**
In Silverpine forest leaving the pathway across the road is a mob called Ravenclaw Servant. On WowWiki the spell "Soul Siphon" that this mob casts on you does 9-10 damage over 10 seconds and in the game does 90-100 dmg over 10 seconds. Makes the mob pretty much unkillable cause its a leech spell.

**Steps to reproduce the behavior with as much detail as possible:**

1. Just pull the mob Ravenclaw Servant in Silverpine forest.
2. After a couple seconds it will cast "Soul Siphon" spell on the target.
3. 
4. 

**IDs of affected creatures, items, quests or spells with a link to the relevant page:**
https://www.wowhead.com/classic/npc=1868/ravenclaw-servant
https://www.wowhead.com/classic/spell=7290/soul-siphon

NPC: https://database.turtle-wow.org/?npc=
Item: https://database.turtle-wow.org/?item=
Quest: https://database.turtle-wow.org/?quest=
Spell: https://database.turtle-wow.org/?spell=
Object: https://database.turtle-wow.org/?object=

**Expected behavior. Describe how it should work:**
Should only be doing 9-10 dmg over 10 seconds not 90-100 dmg over 10 seconds.

**Comment by Gurky-Turtle** [comment]
It looks like they are scaling the spell based on their level by 0.7 so if they are level 14 then it would be 14 * 0.7 = 9.8 rounded to 10 per tick and if level 13 it would be 13*0.7 = 9.1 rounded to 9 per tick. 

This seems to be how the spell works on classic https://www.youtube.com/watch?v=pjgBL3OcCMk (Fizzle uses the same spell)

You have to watch in like .25 speed but around 4:20 he gets the siphon life debuff and has 155 hp the tick of it goes off at the same time the imp firebolt hits him for 14 hp which puts him to 133 hp 

So if you do the math seeing he is level 12 so 12*0.7= 8.4 so round to 8 then take 8 + 14 (Fireball) = 22 damage total 155-133 = 22

This is not a bug the spell is supposed to scale to their level
