### ISSUE TITLE
Unreachable/Closed locations in .car command list

### ISSUE THREAD

**Issue by Ilyanov96** [slowtorta/turtlewow-bug-tracker#3944]
**Please, provide a clear description what the bug is:**
This bug is related to .car chat command showing yet unexplored locations. The thing is that it can show you unreachable/closed or removed from the Cartographer Title requirements. Personally the next location to explore for me is Scarlet Basilica which was removed from the required list on January, 18th hotfix. I've seen ppl reporting Black Morass as well. The issue is that when stuck with unreachable location you don't know where to go next.

<img width="210" alt="Screen Shot 2023-07-15 at 19 38 57" src="https://github.com/slowtorta/turtlewow-bug-tracker/assets/136089422/927f38e1-14ef-4ff7-9cae-b434e234f71f">

**Steps to reproduce the behavior with as much detail as possible:**

1. There should be a lot of already explored locations. Personally i have only 21 unexplored left.
2. type .car in chat (/say)

**IDs of affected creatures, items, quests or spells with a link to the relevant page:**

Only the character itself.

**Expected behavior. Describe how it should work:**
After typing .car in chat it should show you the accessible locations excluding Black Morass, Scarlet Basilica.

**Comment by Gurky-Turtle** [comment]
https://github.com/slowtorta/turtlewow-bug-tracker/issues/3948

**Comment by Gurky-Turtle** [comment]
I merged this with another bug report, nothing has really been looked into yet. I did notice I wasn't getting the explore for this in the zone it says its in online.

**Comment by Ghartadir** [comment]
Hi, I also ran into this problem! How do you solve this?

**Comment by GrizB37** [comment]
Please fix this. Still not working.
