### ISSUE TITLE
Magister's Letter shows wrong classes' text

### ISSUE THREAD

**Issue by Raapho** [slowtorta/turtlewow-bug-tracker#3946]
**Please, provide a clear description what the bug is:**
The Magister's Letter you get for the quest Magister's Letter (High Elf, Mage, Level 2) has the text of the Level 2 High Elf Paladin letter.
Furthermore the database entry for the aforementioned quest links to the Priest's Letter (https://database.turtle-wow.org/?item=80229) instead of the Mage's one (https://database.turtle-wow.org/?item=80227)
**Steps to reproduce the behavior with as much detail as possible:**

1. Accept quest 
2. Read letter

**IDs of affected creatures, items, quests or spells with a link to the relevant page:**

Item: https://database.turtle-wow.org/?item=80227
Quest: https://database.turtle-wow.org/?quest=80214

**Expected behavior. Describe how it should work:**
Mage's letter should show it's own text, not the Paladin's one.

**Comment by Gurky-Turtle** [comment]
> Furthermore the database entry for the aforementioned quest links to the Priest's Letter (https://database.turtle-wow.org/?item=80229) instead of the Mage's one (https://database.turtle-wow.org/?item=80227)

This has been already fixed ingame, However, it looks like the text of the letter was incorrect as well.

**Comment by Gurky-Turtle** [comment]
Should be fixed in the next update.
