### ISSUE TITLE
The Scarlet Basilica (discover point) inexistant

### ISSUE THREAD

**Issue by boulzorman** [slowtorta/turtlewow-bug-tracker#3948]
**Please, provide a clear description what the bug is:**

The scarlet basilica is a supposed area meant to be discovered. And it can't be.

**Steps to reproduce the behavior with as much detail as possible:**

1. try to discover "The scarlet basilica" which is situated at Tyr's Hand (eastern plaguelands) by going to the place.

2. Figure out the only places availables are "scarlet enclave" and "tyr's hand" by being inside "the scarlet basilica"

3. Guess the implementation of the WOTLK map changed the possibility to discover this place. So it's impossible to get this "achievement" (principaly willing to do that for the "Cartographer" title. which was my goal by discovering this area)
By typing .cartographer, it sent me to this area. And nothing named "the scarlet basilica" was findable.

**IDs of affected creatures, items, quests or spells with a link to the relevant page:**

https://wowpedia.fandom.com/wiki/Scarlet_Basilica

**Expected behavior. Describe how it should work:**

By going to the place, "the scarlet basilica should be discovered. Simply.

**Comment by Ilyanov96** [comment]
Still no update on the issue? I've thought that it was a minor bug

**Comment by MaurisLV** [comment]
Hey, i'm having same problem here, any plans on fix ?

**Comment by Ilyanov96** [comment]
Sadly the issue remains for me for almost a month. I thought that it would be a minor fix - just remove one location from the list - but looks like it's smth more complicated.

**Comment by MaurisLV** [comment]
> 

I mean it took 6 months to remove black morass from list, someone said they removed this one from list too but added it back, still it doesn't work, hopes for remove.

**Comment by Ghartadir** [comment]
Hi, I also ran into this problem! How do you solve this?

**Comment by Ilyanov96** [comment]
> Hi, I also ran into this problem! How do you solve this?

Hey, sadly it isn't fixed yet, mate. All we can do now is kindly remind devs to fix it. 

As a temporary solution i recommend you to visit all the instances you haven't been (including SW Vaults and Crescent Groove) and swim along the shore of all seas (you could probably have missed some).

**Comment by GrizB37** [comment]
Not working. Fix ASAP please Devs.

**Comment by slowtorta** [comment]
Fixed on the next update.

**Comment by Ilyanov96** [comment]
Finally! Thx Torta!
