### ISSUE TITLE
unlootable power crystall in ungoro

### ISSUE THREAD

**Issue by geojak** [slowtorta/turtlewow-bug-tracker#3951]
**Please, provide a clear description what the bug is:**

this specific blue power crystall is bugged. i have seen this one being bugged over the years more than once so i assume its not jsuta random glitch
![WoW 2023-07-16 14-11-01](https://github.com/slowtorta/turtlewow-bug-tracker/assets/25199983/d105ce17-7356-4ca3-a84b-6bca3c2acfab)

![WoW 2023-07-16 14-10-55](https://github.com/slowtorta/turtlewow-bug-tracker/assets/25199983/1f5c8ea2-d724-4641-9583-482d9db022e6)

what happen is this laoction 2 two power crystall spanws. one that works and when you loot is it dispareas. and another one always up that can not be looted and always there

**Expected behavior. Describe how it should work:**

crystall lootable and when you do it dispears

**Comment by Gurky-Turtle** [comment]
![image](https://github.com/slowtorta/turtlewow-bug-tracker/assets/90982783/41f3392c-57b4-4551-8fa9-4f90fe5e148e)
![image](https://github.com/slowtorta/turtlewow-bug-tracker/assets/90982783/8056fc26-6349-478a-99e3-6f1d7110ee82)
I cannot reproduce this.

**Comment by Gurky-Turtle** [comment]
Also, checked on the live server and the crystal despawned when looted.
