### ISSUE TITLE
mining node not showing up in minimap unless really close

### ISSUE THREAD

**Issue by brenomechazawa** [slowtorta/turtlewow-bug-tracker#3952]
The minimum distance to track a mining node seems to be wayyy smaller now. I think its a bug. Its really bad. I know there's another post about it, but I recorded a video to help showing this issue. The hunter's tracking skills are still working normaly btw.
Recorded video:https://youtu.be/8f5BFdf7Pl4
Old post from another guy: https://github.com/slowtorta/turtlewow-bug-tracker/issues/3046#issue-1632537014

**Comment by Gurky-Turtle** [comment]
No need to make another bug for this could have commented on the other one.
