### ISSUE TITLE
Kobolds in AV armor scrap drop % is too low. Some mine mobs do not have armor scraps on loot table.

### ISSUE THREAD

**Issue by discer** [slowtorta/turtlewow-bug-tracker#3953]
**Please, provide a clear description what the bug is:**
Turtle Database says the Armor Scraps drop rate should be 80% but it is much lower than that on the Kobolds at Cold Tooth Mine. I have gone 10 kills in a row without getting a single armor scrap. If the drop rate was 80% this would not be possible.
Additionally the Whitewhisker Vermin mobs outside of the cave do not have Armor Scraps as an option on their drop table.

**Steps to reproduce the behavior with as much detail as possible:**

1. Go kill kobolds at cold tooth mine
2. Don't receive armor scraps at an 80% drop rate
3. 

**IDs of affected creatures, items, quests or spells with a link to the relevant page:**

NPC: https://database.turtle-wow.org/?npc=11605
https://database.turtle-wow.org/?npc=11604
https://database.turtle-wow.org/?npc=11603
https://database.turtle-wow.org/?npc=10982

Item: https://database.turtle-wow.org/?item=17422

**Expected behavior. Describe how it should work:**
Armor scraps drop at stated %

**Comment by balakethelock** [comment]
You're in a bg with group loot enabled. Looting the mobs will take turns by all the players in range even if they don't participate in the kill at all.

**Comment by discer** [comment]
> You're in a bg with group loot enabled. Looting the mobs will take turns by all the players in range even if they don't participate in the kill at all.

This is not how it works in the alliance mine

**Comment by balakethelock** [comment]
White items are still group looted. You'll notice for example when you're killing mobs with a friend that while Greens and blues are rolled, for gray and white items you take turns taking everything that is in the corpse. This is most likely what is happening here. as for alliance dropping it at the appropriate rate, there's probably nobody else with you in the cave at the moment you tested.

**Comment by discer** [comment]
> White items are still group looted. You'll notice for example when you're killing mobs with a friend that while Greens and blues are rolled, for gray and white items you take turns taking everything that is in the corpse. This is most likely what is happening here. as for alliance dropping it at the appropriate rate, there's probably nobody else with you in the cave at the moment you tested.

This is a disingenuous example assuming there are other people in one instance but not another, regardless you can easily test it by killing mobs at both locations and seeing you get significantly more scraps at the north mine. This also does not explain why there are mobs at the mine that do not have armor scraps on the loot table.

**Comment by balakethelock** [comment]
> This is a disingenuous example assuming there are other people in one instance but not another, regardless you can easily test it by killing mobs at both locations and seeing you get significantly more scraps at the north mine. This also does not explain why there are mobs at the mine that do not have armor scraps on the loot table.

I simply assumed you're testing on a horde character, the south mine will have horde players nearby not letting you loot everything you kill. Meanwhile when you do it at the north mine there won't be horde players around you and you get 100% of what drops.

As for the mobs that are missing the scraps in the loot table, that one is true and should be fixed.

**Comment by discer** [comment]
I have tested both 60 horde and ally at each location with the same result

**Comment by GrizB37** [comment]
Would explain how the alliance get champion units alot faster than horde.

**Comment by Gurky-Turtle** [comment]
They are indeed 80% Whitewhisker Geomancer and Whitewhisker Vermin will drop them in the next update.
