### ISSUE TITLE
Death from Fall Charred Vale

### ISSUE THREAD

**Issue by Battlefrog71** [slowtorta/turtlewow-bug-tracker#3954]
While running through the Charred Vale in the Stone Talon Mountains, I suddenly fell to my death, losing 1848 health.  It was on relatively flat terrain, and certainly nothing of height.  I do not have coordinates, but took some screenshots.  I guess this wouldn't hurt a HC character but it was a serious pain in the butt to get back to my body from the cemetery.  

![Screenshot (4)](https://github.com/slowtorta/turtlewow-bug-tracker/assets/139710178/5cfcd323-aa3c-4562-a418-bf3309e7b593)
![Screenshot (5)](https://github.com/slowtorta/turtlewow-bug-tracker/assets/139710178/0b97d1c0-d038-4aee-af1d-9ed22e710aa4)

**Comment by balakethelock** [comment]
It's a bug with **charge/intercept/intervene**. After using these abilities, the warrior will take 100% falll damage from even the smallest 1 yard drop. Happens a lot in winterspring and aq40 for some reason but it can theoretically happen anywhere.

**Comment by twowTurtReynolds** [comment]
![image](https://github.com/slowtorta/turtlewow-bug-tracker/assets/151180101/09c8190a-c7d9-436d-94c8-a8b91c6379d6)
If someone ever learns of a fix, it will be applied, I guarantee it.
