### ISSUE TITLE
sunnyglade spark hand in broke

### ISSUE THREAD

**Issue by geojak** [slowtorta/turtlewow-bug-tracker#3956]
I**Please, provide a clear description what the bug is:**

the more sparks you hand in the weaker the boss becomes
you can only hand in sparks when controlling the middle
at 80 or so sparks the bosses first spawn
after the bosses spawned, the hand in the center breaks and you cant further decrease the hp of the bosses with spakrs
this leaves you with a 200k - 1 Million unkillable boss, noone can win, if the other side doesnt let them. 

**Expected behavior. Describe how it should work:**
lets us contineu to hand in sparks, i beleive this is a bug and was the acutal inteded way to win this, by getting spakrs until the boss is weak enough. I can't belive you intend a 10 man bg groip fight a Riad boss with 300k+ hp while getting attacked by the enemy faction.

p.s. pelase look into this https://forum.turtle-wow.org/viewtopic.php?f=14&t=8328

**Comment by ratkosrb** [comment]
After the next update, it should be possible to continue turning in sparks once the basses are summoned, and they will affect their max health.
