### ISSUE TITLE
Hunter and Warlock Pets  Broken - some abilities no longer auto-casting

### ISSUE THREAD

**Issue by xinmpg** [slowtorta/turtlewow-bug-tracker#3959]
Not all Hunter and Warlock pet abilities are no longer all autocasting anymore, even if enabled.  I play both classes and noticed a number of cases. Guildies and people on the forums and in /world have also been complaining about this.

I've personally noticed these don't work:

Imp - Blood Pact and Phase shift need to be manually triggered. Possibly fire shield also, didn't get a chance to try that.
Succubus - Invisibility
Hunter cats and birds - Dash/Dive are not working unless manually triggered.  

I've observed abilities used actively in combat such as Imp Fireball, VW Torment and suffering,  hunter pets growl, bite, crawl, all *seem* to be working still.  It seems focused on pet abilities which they would trigger on their own outside combat/in combat just before actually engaging a mob.  

These are just my observations and there could be more cases i haven't listed.

**Comment by xinmpg** [comment]
OK Update -
My Owl had Dive, Growl, and Screech, Growl and Screech were working.  I just taught it Claw 6, and now it won't use screech or claw on auto. It's not a focus issue, it has plenty.

**Comment by Gurky-Turtle** [comment]
https://github.com/slowtorta/turtlewow-bug-tracker/issues/3923
https://github.com/slowtorta/turtlewow-bug-tracker/issues/3964
https://github.com/slowtorta/turtlewow-bug-tracker/issues/3913
