### ISSUE TITLE
Pet autocast doesn't work

### ISSUE THREAD

**Issue by Infil0405** [slowtorta/turtlewow-bug-tracker#3964]
Imp does not cast autocast spells such as Blood pact and Phase shift , even tho autocast is enabled. 
Voidwalker taunt timing feels off also, need to spam it maually at a beginning of combat,  then it works correctly.
I suppose other pet abilities also broken after last update.

**Comment by Kwall29** [comment]
This is still happening. I opened a new one since this is closed. I also have to spam my hunter pets abilities at the beginning of a fight because they wait too long to use them on their own.
