### ISSUE TITLE
Missing unlocked tmog for Bonespike Shoulder.

### ISSUE THREAD

**Issue by a-saye** [slowtorta/turtlewow-bug-tracker#3966]
**Please, provide a clear description what the bug is:**

**Steps to reproduce the behavior with as much detail as possible:**

1. Loot and equip Bonespike Shoulder.
2. Use it at the fashionista.
3. Try to use it again and see that its missing from your unlocked tmogs.

**IDs of affected creatures, items, quests or spells with a link to the relevant page:**

NPC: https://database.turtle-wow.org/?npc=
Item: https://database.turtle-wow.org/?item=12588#dropped-by
Quest: https://database.turtle-wow.org/?quest=
Spell: https://database.turtle-wow.org/?spell=
Object: https://database.turtle-wow.org/?object=

**Expected behavior. Describe how it should work:**
I should be able to use it at the fashionista for tmog indefinitely.

**Comment by a-saye** [comment]
So i tried equipping and unequipping the shoulders to see if the tmog would be reapplied. Didnt work. I also cleared wdb folder and restarted multiple times and still nothing. Ive talked with a GM a few times as well and she told me to reach out here to update you guys at the dev dept. I just wanna make sure my entire tmog collection isnt broken mainly but if its just this shoulder item thats broken for me in tmog im really not super hung up about it. Thank you for the help!

**Comment by Gurky-Turtle** [comment]
![image](https://github.com/slowtorta/turtlewow-bug-tracker/assets/90982783/b4785784-543b-4213-af57-4eb0f7d50339)
![image](https://github.com/slowtorta/turtlewow-bug-tracker/assets/90982783/3ae8bea1-0ee1-49a0-b278-1e1c0265c282)
Cannot reproduce this please make a video of what you are seeing and share it here.

**Comment by a-saye** [comment]
https://drive.google.com/file/d/1YSqEl3ygDCVUZa5djjdu9nOrrrE_SJa_/view?usp=drive_link

**Comment by Gurky-Turtle** [comment]
Cannot access

**Comment by a-saye** [comment]
https://drive.google.com/file/d/1YSqEl3ygDCVUZa5djjdu9nOrrrE_SJa_/view?usp=sharing

That should work now sorry forgot to grant access.

**Comment by balakethelock** [comment]
![image](https://github.com/slowtorta/turtlewow-bug-tracker/assets/111737968/c9128b5a-4136-4242-8b65-7c292b681457)
Is this not it?
