### ISSUE TITLE
Lighting the Pyres's object clicking bug

### ISSUE THREAD

**Issue by SissyTrashQueen** [slowtorta/turtlewow-bug-tracker#3967]
Lighting the Pyres quest's objects (Spirit Pyres) can be clicked quickly to complete more than one objective, depending on how quick they are clicked.

Quest: https://database.turtle-wow.org/?quest=80301
Object: https://database.turtle-wow.org/?object=3000242

**Expected behavior. Describe how it should work:**
Clicking a Spirit Pyre should only complete 1 of the 8 objectives.

**Comment by twowTurtReynolds** [comment]
![image](https://github.com/slowtorta/turtlewow-bug-tracker/assets/151180101/d36df52d-cb2d-449d-97fa-9cf150896f4c)
It looks like this error is now sent to players who tried to abuse this.
