### ISSUE TITLE
Welcome to Amani'Alor zone location is wrong

### ISSUE THREAD

**Issue by bitchqueenoftheuniverse** [slowtorta/turtlewow-bug-tracker#3968]
Welcome to Amani'Alor quest location is in Orgrimmar, but the quest is given and turned in at Amani'alor.

**IDs of affected creatures, items, quests or spells with a link to the relevant page:**
Quest: https://database.turtle-wow.org/?quest=80313

**Expected behavior. Describe how it should work:**
Welcome to Amani'Alor location should be in Amani'alor or Stonetalon Mountains.

**Comment by Gurky-Turtle** [comment]
This has already been fixed. You will need to delete your wdb folder.

**Comment by bitchqueenoftheuniverse** [comment]
I deleted my wdb folder anyways and the Quest Log's category for the quest is still Orgrimmar.
What I meant by "location" is the Quest Log's header/category this quest falls into, which can also be seen in the Database. I think my report was taken as duplicate of #3173 yet i'm speaking of a different issue.
In-game image:
![image](https://github.com/slowtorta/turtlewow-bug-tracker/assets/55768134/9bc9572a-bc5b-421c-be67-8ffb5ea0c5a1)
Database:
![image](https://github.com/slowtorta/turtlewow-bug-tracker/assets/55768134/22a6e0d1-ef5c-4726-a458-d8eaa92f8d02)

This is the same issue with "Scratching Each Other's Back", its Quest Log's category is Orgrimmar, yet its quest giver is in Amani'alor and the quest sends you to Durotar.
https://database.turtle-wow.org/?quest=80314
