### ISSUE TITLE
Anubisath Warder incredibly overtuned

### ISSUE THREAD

**Issue by sarenraee** [slowtorta/turtlewow-bug-tracker#3969]
The Anubisath Warder in AQ40 are so overpowered that all guilds have to skip them.

If you enter combat with one, you will find that they immediately spam the incorrect Fire Nova spell, shredding the entire raid for thousands of damage rapidly. Also, instead of picking their random spells, they use all of them. 

NPC: https://database.turtle-wow.org/?npc=15311
Spell: https://classicdb.ch/?spell=26069 https://database.turtle-wow.org/?spell=26070 https://database.turtle-wow.org/?spell=26071 https://database.turtle-wow.org/?spell=26072 https://database.turtle-wow.org/?spell=26073 

Firstly, the Anubisath Warder should, instead of having both, choose between Entangling Roots and Fire Nova as their damaging AOE. This is cast every couple seconds instead of the intended every fifteen-thirty seconds after the pull begins and should only deal a couple hundred damage instead of the current couple thousand. The reason these abilities are intended as doing so little damage is because, when combined with the Nullifiers they are with, it can wipe the debuffed raid immediately.

Second, the Anubisath Warder should, instead of having all three of these buffs, choose between any two of Dust Cloud, Fear, and Silence, and cast them less frequently (also about every fifteen-thirty seconds, and not at the same time).

I have timestamped proof of how the Anubisath Warder should be below, showcasing their tighter pick of abilities and heavily nerfed Fire Nova.

VOD 1:
https://youtu.be/-tNMCO7_LiY?t=4653
https://youtu.be/-tNMCO7_LiY?t=4727
https://youtu.be/-tNMCO7_LiY?t=5024
https://youtu.be/-tNMCO7_LiY?t=5361
VOD 2:
https://youtu.be/0MnMauoKYh8?t=2187
https://youtu.be/0MnMauoKYh8?t=2449
https://youtu.be/0MnMauoKYh8?t=2485

What with Shard of the Fallen Star being given PVE stats, these mobs being impossible to kill presents an unnecessary hurdle that encourages skipping trash. Even without the buff, this is a huge, huge bug with this mob.

**Comment by lyssebabz** [comment]
they are waaaay to overtuned

**Comment by Wronggock** [comment]
Or just buy us the Potions of invis for free at a vendor after twins?
