### ISSUE TITLE
Client issue

### ISSUE THREAD

**Issue by Tobbsu** [slowtorta/turtlewow-bug-tracker#397]
Hey is me Tobbsu I have a problem with error: 132 - More Info here -->
==============================================================================
World of WarCraft (build 5875)

Exe:      E:\Spel\Turtle Wow Privit Server\Turtle WoW\WoW.exe
Time:     Sep 24, 2021  4:14:40.181 PM
User:     Tobbsu
Computer: DESKTOP-BVVJSUT
------------------------------------------------------------------------------

This application has encountered a critical error:

ERROR #132 (0x85100084) Fatal Exception
Program:	E:\Spel\Turtle Wow Privit Server\Turtle WoW\WoW.exe
Exception:	0xC0000005 (ACCESS_VIOLATION) at 0023:006D62EC

The instruction at "0x006D62EC" referenced memory at "0x00000004".
The memory could not be "read".

WoWBuild: 5875
------------------------------------------------------------------------------

----------------------------------------
    x86 Registers
----------------------------------------

EAX=00000724  EBX=00000724  ECX=0019F8B8  EDX=00000724  ESI=00000000
EDI=11D34268  EBP=0019F890  ESP=0019F878  EIP=006D62EC  FLG=00210212
CS =0023      DS =002B      ES =002B      SS =002B      FS =0053      GS =002B

----------------------------------------
    Stack Trace (Manual)
----------------------------------------

Address  Frame    Logical addr  Module

006D62EC 0019F890 0001:002D52EC E:\Spel\Turtle Wow Privit Server\Turtle WoW\WoW.exe
006D64F4 0019F8B0 0001:002D54F4 E:\Spel\Turtle Wow Privit Server\Turtle WoW\WoW.exe
006D2FD6 0019FA38 0001:002D1FD6 E:\Spel\Turtle Wow Privit Server\Turtle WoW\WoW.exe
006D25D9 0019FB7C 0001:002D15D9 E:\Spel\Turtle Wow Privit Server\Turtle WoW\WoW.exe
006D2233 0019FBA0 0001:002D1233 E:\Spel\Turtle Wow Privit Server\Turtle WoW\WoW.exe
0067C13D 0019FBD0 0001:0027B13D E:\Spel\Turtle Wow Privit Server\Turtle WoW\WoW.exe
0066FF0B 0019FBE0 0001:0026EF0B E:\Spel\Turtle Wow Privit Server\Turtle WoW\WoW.exe
0048329C 0019FC84 0001:0008229C E:\Spel\Turtle Wow Privit Server\Turtle WoW\WoW.exe
00482E73 0019FD10 0001:00081E73 E:\Spel\Turtle Wow Privit Server\Turtle WoW\WoW.exe
0076FC31 0019FD2C 0001:0036EC31 E:\Spel\Turtle Wow Privit Server\Turtle WoW\WoW.exe
007658E7 0019FD50 0001:003648E7 E:\Spel\Turtle Wow Privit Server\Turtle WoW\WoW.exe
0076434C 0019FD5C 0001:0036334C E:\Spel\Turtle Wow Privit Server\Turtle WoW\WoW.exe
0044264E 0019FE24 0001:0004164E E:\Spel\Turtle Wow Privit Server\Turtle WoW\WoW.exe
004246B0 0019FE58 0001:000236B0 E:\Spel\Turtle Wow Privit Server\Turtle WoW\WoW.exe
0042106F 0019FEC8 0001:0002006F E:\Spel\Turtle Wow Privit Server\Turtle WoW\WoW.exe
00420BF1 0019FEE0 0001:0001FBF1 E:\Spel\Turtle Wow Privit Server\Turtle WoW\WoW.exe
0040411E 0019FF70 0001:0000311E E:\Spel\Turtle Wow Privit Server\Turtle WoW\WoW.exe
7671FA29 0019FF80 0001:0000FA29 C:\WINDOWS\System32\KERNEL32.DLL
77A07A9E 0019FFDC 0001:00066A9E C:\WINDOWS\SYSTEM32\ntdll.dll
77A07A6E 0019FFEC 0001:00066A6E C:\WINDOWS\SYSTEM32\ntdll.dll

----------------------------------------
    Stack Trace (Using DBGHELP.DLL)
----------------------------------------

006D62EC WoW.exe      <unknown symbol>+0 (0x00000000,0x00000000,0x2CEC6C80,0x00000000)

----------------------------------------
    Loaded Modules
----------------------------------------

0x00400000 - 0x00D06000  E:\Spel\Turtle Wow Privit Server\Turtle WoW\WoW.exe
0x02C40000 - 0x02CD6000  E:\Spel\Turtle Wow Privit Server\Turtle WoW\fmod.dll
0x05D50000 - 0x05E09000  C:\WINDOWS\SYSTEM32\textinputframework.dll
0x10000000 - 0x10069000  E:\Spel\Turtle Wow Privit Server\Turtle WoW\DivxDecoder.dll
0x17E50000 - 0x17F68000  E:\Spel\Turtle Wow Privit Server\Turtle WoW\dbghelp.dll
0x50200000 - 0x5023A000  C:\WINDOWS\SYSTEM32\wdmaud.drv
0x50240000 - 0x502BF000  C:\WINDOWS\SYSTEM32\dsound.dll
0x502C0000 - 0x50616000  C:\Program Files\NVIDIA Corporation\Ansel\d3dcompiler_47_32.dll
0x50620000 - 0x50CDD000  C:\Program Files\NVIDIA Corporation\Ansel\NvCamera32.dll
0x50CE0000 - 0x50FE3000  E:\Spel\Turtle Wow Privit Server\Turtle WoW\discord_game_sdk.dll
0x50FF0000 - 0x510D9000  C:\WINDOWS\SYSTEM32\DDRAW.dll
0x52280000 - 0x522B2000  C:\Windows\System32\Windows.Internal.Graphics.Display.DisplayColorManagement.dll
0x522C0000 - 0x52337000  C:\WINDOWS\SYSTEM32\AcSpecfc.DLL
0x55C70000 - 0x55E87000  C:\WINDOWS\system32\nvspcap.dll
0x55E90000 - 0x58464000  C:\WINDOWS\System32\DriverStore\FileRepository\nv_dispi.inf_amd64_60daf66a00f2e0b6\nvwgf2um.dll
0x592A0000 - 0x592AF000  C:\WINDOWS\SYSTEM32\resourcepolicyclient.dll
0x5B010000 - 0x5B04F000  C:\WINDOWS\SYSTEM32\GLU32.dll
0x5B050000 - 0x5B153000  C:\WINDOWS\SYSTEM32\OPENGL32.dll
0x601E0000 - 0x60316000  C:\WINDOWS\SYSTEM32\AUDIOSES.DLL
0x60A40000 - 0x60BCF000  C:\WINDOWS\SYSTEM32\d3d9.dll
0x60DF0000 - 0x60DF8000  C:\WINDOWS\SYSTEM32\midimap.dll
0x60E00000 - 0x60E0A000  C:\WINDOWS\SYSTEM32\msacm32.drv
0x60E10000 - 0x60E2E000  E:\Spel\Turtle Wow Privit Server\Turtle WoW\DiscordOverlay.dll
0x61320000 - 0x61329000  C:\WINDOWS\SYSTEM32\ktmw32.dll
0x61330000 - 0x61349000  C:\Program Files (x86)\Razer\InGameEngine\32bit\RazerHook32.dll
0x61350000 - 0x61358000  C:\WINDOWS\SYSTEM32\WSOCK32.dll
0x61360000 - 0x61367000  C:\WINDOWS\SYSTEM32\DCIMAN32.dll
0x61A00000 - 0x61A8D000  C:\WINDOWS\WinSxS\x86_microsoft.windows.common-controls_6595b64144ccf1df_5.82.19041.1110_none_c0da534e38c01f4d\COMCTL32.dll
0x61AB0000 - 0x61AB7000  C:\WINDOWS\SYSTEM32\ksuser.dll
0x66C00000 - 0x66C36000  C:\Program Files\WIDCOMM\Bluetooth Software\SysWOW64\BtMmHook.dll
0x67D90000 - 0x67E65000  C:\WINDOWS\System32\DriverStore\FileRepository\nv_dispi.inf_amd64_60daf66a00f2e0b6\nvldumd.dll
0x69380000 - 0x69413000  C:\WINDOWS\SYSTEM32\mscms.dll
0x69420000 - 0x69591000  C:\WINDOWS\SYSTEM32\WindowsCodecs.dll
0x69920000 - 0x69B00000  C:\WINDOWS\SYSTEM32\d3d11.dll
0x69CA0000 - 0x69E2F000  C:\Windows\System32\twinapi.appcore.dll
0x69E30000 - 0x69EA3000  C:\Windows\System32\WindowManagementAPI.dll
0x69EB0000 - 0x69FA3000  C:\Windows\System32\Windows.UI.dll
0x6A000000 - 0x6A12A000  C:\Program Files (x86)\Razer\InGameEngine\32bit\rzdspsrv.dll
0x6B000000 - 0x6B27E000  C:\WINDOWS\SYSTEM32\CoreUIComponents.dll
0x6B280000 - 0x6B35B000  C:\WINDOWS\SYSTEM32\wintypes.dll
0x6B360000 - 0x6B3FB000  C:\WINDOWS\SYSTEM32\CoreMessaging.dll
0x6B400000 - 0x6B4ED000  C:\WINDOWS\SYSTEM32\inputhost.dll
0x6B5A0000 - 0x6B60B000  C:\WINDOWS\System32\MMDevApi.dll
0x6B610000 - 0x6B63B000  C:\WINDOWS\System32\DEVOBJ.dll
0x6B640000 - 0x6B64C000  C:\WINDOWS\SYSTEM32\ColorAdapterClient.dll
0x6B6C0000 - 0x6B6F7000  C:\WINDOWS\SYSTEM32\DINPUT8.dll
0x6B700000 - 0x6B708000  C:\WINDOWS\SYSTEM32\AVRT.dll
0x6BC10000 - 0x6BC17000  C:\WINDOWS\SYSTEM32\XINPUT9_1_0.dll
0x6BC20000 - 0x6BC2A000  C:\WINDOWS\SYSTEM32\HID.DLL
0x6C3A0000 - 0x6C90F000  C:\Program Files (x86)\NVIDIA Corporation\NvContainer\MessageBus.dll
0x6CA80000 - 0x6CB43000  C:\WINDOWS\SYSTEM32\dxgi.dll
0x6D4F0000 - 0x6D501000  C:\Program Files\Avast Software\Avast\x86\aswhook.dll
0x6D510000 - 0x6D53C000  C:\WINDOWS\SYSTEM32\dxcore.dll
0x6D5E0000 - 0x6D6A2000  C:\WINDOWS\SYSTEM32\PROPSYS.dll
0x6DA50000 - 0x6DA6E000  C:\WINDOWS\SYSTEM32\gpapi.dll
0x6DB40000 - 0x6DB84000  C:\WINDOWS\SYSTEM32\powrprof.dll
0x6E140000 - 0x6E15F000  C:\WINDOWS\system32\ncryptsslp.dll
0x6E160000 - 0x6E181000  C:\WINDOWS\SYSTEM32\ncrypt.dll
0x6E190000 - 0x6E1B6000  C:\WINDOWS\SYSTEM32\cryptnet.dll
0x6E1C0000 - 0x6E1C8000  C:\WINDOWS\SYSTEM32\DPAPI.DLL
0x6E1D0000 - 0x6E1F8000  C:\WINDOWS\SYSTEM32\NTASN1.dll
0x6E200000 - 0x6E210000  C:\WINDOWS\SYSTEM32\mskeyprotect.dll
0x6E210000 - 0x6E288000  C:\WINDOWS\System32\schannel.dll
0x6E2A0000 - 0x6E2B6000  C:\WINDOWS\SYSTEM32\dhcpcsvc.DLL
0x6E350000 - 0x6E35E000  C:\WINDOWS\System32\winrnr.dll
0x6E360000 - 0x6E376000  C:\WINDOWS\system32\NLAapi.dll
0x6E380000 - 0x6E390000  C:\WINDOWS\system32\wshbth.dll
0x6E390000 - 0x6E3A6000  C:\WINDOWS\system32\pnrpnsp.dll
0x6E3B0000 - 0x6E3C1000  C:\WINDOWS\system32\napinsp.dll
0x6F4C0000 - 0x6F518000  C:\WINDOWS\System32\fwpuclnt.dll
0x6F520000 - 0x6F528000  C:\Windows\System32\rasadhlp.dll
0x6F530000 - 0x6F5C1000  C:\WINDOWS\SYSTEM32\DNSAPI.dll
0x6F5E0000 - 0x6F5ED000  C:\WINDOWS\SYSTEM32\UMPDC.dll
0x70710000 - 0x7071A000  C:\WINDOWS\SYSTEM32\CRYPTBASE.DLL
0x70720000 - 0x7074F000  C:\WINDOWS\system32\rsaenh.dll
0x711B0000 - 0x711C3000  C:\WINDOWS\SYSTEM32\CRYPTSP.dll
0x712B0000 - 0x712C2000  C:\WINDOWS\SYSTEM32\ondemandconnroutehelper.dll
0x712D0000 - 0x712D8000  C:\WINDOWS\SYSTEM32\WINNSI.DLL
0x712E0000 - 0x71332000  C:\WINDOWS\SYSTEM32\mswsock.dll
0x736E0000 - 0x736F8000  C:\WINDOWS\SYSTEM32\profapi.dll
0x73A30000 - 0x73E80000  C:\WINDOWS\SYSTEM32\WININET.dll
0x73E90000 - 0x73EB9000  C:\WINDOWS\SYSTEM32\ntmarta.dll
0x74150000 - 0x7416D000  C:\WINDOWS\SYSTEM32\srvcli.dll
0x74170000 - 0x7439B000  C:\WINDOWS\SYSTEM32\iertutil.dll
0x743A0000 - 0x743BD000  C:\WINDOWS\SYSTEM32\winmmbase.dll
0x743C0000 - 0x743E1000  C:\WINDOWS\SYSTEM32\SspiCli.dll
0x743F0000 - 0x74409000  C:\WINDOWS\SYSTEM32\MPR.dll
0x74410000 - 0x7447D000  C:\WINDOWS\SYSTEM32\WINSPOOL.DRV
0x74480000 - 0x74628000  C:\WINDOWS\SYSTEM32\urlmon.dll
0x74630000 - 0x74656000  C:\WINDOWS\SYSTEM32\dwmapi.dll
0x74660000 - 0x74679000  C:\WINDOWS\SYSTEM32\MSACM32.dll
0x746A0000 - 0x746C8000  C:\WINDOWS\SYSTEM32\WINMM.dll
0x746D0000 - 0x74744000  C:\WINDOWS\system32\uxtheme.dll
0x749B0000 - 0x74A4F000  C:\WINDOWS\SYSTEM32\apphelp.dll
0x74B80000 - 0x74BA4000  C:\WINDOWS\SYSTEM32\Wldp.dll
0x74BD0000 - 0x751D8000  C:\WINDOWS\SYSTEM32\windows.storage.dll
0x751E0000 - 0x751EF000  C:\WINDOWS\SYSTEM32\kernel.appcore.dll
0x751F0000 - 0x751FE000  C:\WINDOWS\SYSTEM32\msasn1.dll
0x75200000 - 0x7520B000  C:\WINDOWS\SYSTEM32\netutils.dll
0x75220000 - 0x752E8000  C:\WINDOWS\SYSTEM32\winhttp.dll
0x75500000 - 0x75532000  C:\WINDOWS\SYSTEM32\IPHLPAPI.DLL
0x75560000 - 0x757F1000  C:\WINDOWS\SYSTEM32\msi.dll
0x75800000 - 0x75808000  C:\WINDOWS\SYSTEM32\VERSION.DLL
0x75810000 - 0x75835000  C:\WINDOWS\SYSTEM32\USERENV.dll
0x75860000 - 0x758DB000  C:\WINDOWS\System32\msvcp_win.dll
0x758E0000 - 0x758E6000  C:\WINDOWS\System32\psapi.dll
0x759B0000 - 0x75C31000  C:\WINDOWS\System32\combase.dll
0x75C40000 - 0x75CFF000  C:\WINDOWS\System32\msvcrt.dll
0x75D00000 - 0x75D3B000  C:\WINDOWS\System32\cfgmgr32.dll
0x75D40000 - 0x75D65000  C:\WINDOWS\System32\IMM32.dll
0x75D70000 - 0x75DB7000  C:\WINDOWS\System32\WINTRUST.DLL
0x75DC0000 - 0x75EBA000  C:\WINDOWS\System32\CRYPT32.dll
0x75EC0000 - 0x75ED9000  C:\WINDOWS\System32\imagehlp.dll
0x75EE0000 - 0x75F04000  C:\WINDOWS\System32\GDI32.dll
0x75F10000 - 0x7634C000  C:\WINDOWS\System32\SETUPAPI.DLL
0x76350000 - 0x763D7000  C:\WINDOWS\System32\shcore.dll
0x763E0000 - 0x76500000  C:\WINDOWS\System32\ucrtbase.dll
0x76700000 - 0x767F0000  C:\WINDOWS\System32\KERNEL32.DLL
0x767F0000 - 0x76865000  C:\WINDOWS\System32\sechost.dll
0x76870000 - 0x76953000  C:\WINDOWS\System32\ole32.dll
0x76960000 - 0x769C3000  C:\WINDOWS\System32\WS2_32.dll
0x769D0000 - 0x76AA3000  C:\WINDOWS\System32\MSCTF.dll
0x76AB0000 - 0x76B8C000  C:\WINDOWS\System32\gdi32full.dll
0x76B90000 - 0x76B97000  C:\WINDOWS\System32\NSI.dll
0x76BA0000 - 0x76BB8000  C:\WINDOWS\System32\win32u.dll
0x76BC0000 - 0x76BD9000  C:\WINDOWS\System32\bcrypt.dll
0x76BE0000 - 0x76C25000  C:\WINDOWS\System32\SHLWAPI.dll
0x76C30000 - 0x76DD1000  C:\WINDOWS\System32\USER32.dll
0x76DE0000 - 0x76E5A000  C:\WINDOWS\System32\ADVAPI32.dll
0x76E60000 - 0x76EF6000  C:\WINDOWS\System32\OLEAUT32.dll
0x76F00000 - 0x77115000  C:\WINDOWS\System32\KERNELBASE.dll
0x77120000 - 0x771CF000  C:\WINDOWS\System32\COMDLG32.dll
0x771D0000 - 0x7724E000  C:\WINDOWS\System32\clbcatq.dll
0x77250000 - 0x7730F000  C:\WINDOWS\System32\RPCRT4.dll
0x77310000 - 0x7736F000  C:\WINDOWS\System32\bcryptPrimitives.dll
0x773D0000 - 0x77983000  C:\WINDOWS\System32\SHELL32.dll
0x779A0000 - 0x77B43000  C:\WINDOWS\SYSTEM32\ntdll.dll
0x785D0000 - 0x79BE2000  C:\WINDOWS\System32\DriverStore\FileRepository\nv_dispi.inf_amd64_60daf66a00f2e0b6\nvd3dum.dll
0x7B1A0000 - 0x7B778000  C:\WINDOWS\SYSTEM32\nvapi.dll

----------------------------------------
    Memory Dump
----------------------------------------

Code: 16 bytes starting at (EIP = 006D62EC)

006D62EC: 8B 56 04 85  D2 57 8B F9  75 10 C7 07  00 00 00 FF  .V...W..u.......

Stack: 1024 bytes starting at (ESP = 0019F878)

* = addr                            **                                *       
0019F870: B0 64 6D 00  28 92 D7 11  C8 F8 19 00  90 F8 19 00  .dm.(...........
0019F880: A0 05 00 00  58 F9 19 00  9F F4 89 3E  00 00 00 00  ....X......>....
0019F890: B0 F8 19 00  F4 64 6D 00  00 00 00 00  00 00 00 00  .....dm.........
0019F8A0: 80 6C EC 2C  00 00 00 00  40 2F 6D 00  00 00 80 3F  .l.,....@/m....?
0019F8B0: 38 FA 19 00  D6 2F 6D 00  68 42 D3 11  6C FA 19 00  8..../m.hB..l...
0019F8C0: 08 6C EC 2C  00 00 00 00  00 00 00 00  00 00 00 00  .l.,............
0019F8D0: 00 00 00 00  00 00 00 00  00 00 00 00  00 00 00 00  ................
0019F8E0: 00 00 00 00  00 00 00 00  00 00 00 00  00 00 00 00  ................
0019F8F0: 00 00 00 00  00 00 00 00  00 00 00 00  00 00 00 00  ................
0019F900: 00 00 00 00  00 00 00 00  00 00 00 00  8E E3 8A 43  ...............C
0019F910: 00 00 00 BF  00 00 00 00  00 00 00 00  00 00 80 3F  ...............?
0019F920: 33 33 73 3F  00 00 00 00  00 00 80 3F  00 00 00 3F  33s?.......?...?
0019F930: 00 00 00 3F  00 00 80 3F  00 00 40 3F  00 00 80 3F  ...?...?..@?...?
0019F940: 00 00 00 00  00 00 00 00  00 00 00 00  00 00 00 00  ................
0019F950: 00 00 00 00  00 00 00 00  00 28 83 FF  54 6E 75 FF  .........(..Tnu.
0019F960: 1C 30 34 FF  20 3B 40 FF  2E 57 61 FF  23 5A 78 FF  .04. ;@..Wa.#Zx.
0019F970: 22 53 6F FF  24 53 6E FF  6E 8C 8F FF  13 2F 41 FF  "So.$Sn.n..../A.
0019F980: 07 45 60 FF  32 32 32 FF  38 38 38 FF  00 00 00 FF  .E`.222.888.....
0019F990: 00 00 00 FF  1F 51 77 FF  38 48 3E FF  BE C4 47 43  .....Qw.8H>...GC
0019F9A0: 98 BA DC 3C  53 53 53 FF  00 00 00 00  00 00 80 3F  ...<SSS........?
0019F9B0: 6F 7F 20 3F  33 33 73 3F  00 00 80 3F  9A 99 19 3F  o. ?33s?...?...?
0019F9C0: 00 00 00 3F  00 00 80 3F  00 00 40 3F  00 00 80 3F  ...?...?..@?...?
0019F9D0: 00 00 00 00  00 00 80 3F  00 00 00 00  00 00 00 00  .......?........
0019F9E0: 00 00 00 00  00 00 80 3F  00 00 00 00  24 07 00 00  .......?....$...
0019F9F0: DC FA 19 00  24 07 00 00  50 A5 B8 44  2D B3 50 44  ....$...P..D-.PD
0019FA00: 80 6C EC 2C  34 16 81 00  08 06 44 25  00 01 00 00  .l.,4.....D%....
0019FA10: 08 06 44 25  00 01 00 00  20 00 00 00  20 00 00 00  ..D%.... ... ...
0019FA20: 01 00 00 00  00 00 00 00  2D B3 50 44  80 6C EC 2C  ........-.PD.l.,
0019FA30: FC A2 D1 3E  8A 81 E4 44  7C FB 19 00  D9 25 6D 00  ...>...D|....%m.
0019FA40: 1F 00 00 00  08 AE 3D 15  01 00 00 00  65 65 65 FF  ......=.....eee.
0019FA50: 5F 4E 4E FF  6F 6F 6F FF  6D 6D 6D FF  6F 6F 6F FF  _NN.ooo.mmm.ooo.
0019FA60: 67 67 67 FF  52 53 52 FF  52 54 52 FF  58 58 58 FF  ggg.RSR.RTR.XXX.
0019FA70: B5 C3 C3 FF  3E 3F 3D FF  00 00 00 FF  00 00 00 FF  ....>?=.........
0019FA80: 4D 4D 4D FF  43 43 43 FF  4D 4D 4D FF  43 43 43 FF  MMM.CCC.MMM.CCC.
0019FA90: 8E E3 8A 43  00 00 00 BF  38 38 38 FF  00 00 00 00  ...C....888.....
0019FAA0: 00 00 80 3F  33 33 73 3F  00 00 00 00  00 00 80 3F  ...?33s?.......?
0019FAB0: 00 00 00 3F  00 00 00 3F  00 00 80 3F  00 00 40 3F  ...?...?...?..@?
0019FAC0: 00 00 80 3F  00 00 00 00  00 00 80 3F  00 00 00 00  ...?.......?....
0019FAD0: 00 00 00 00  00 00 00 00  00 00 80 3F  25 82 E1 FF  ...........?%...
0019FAE0: 73 64 5C FF  34 1B 0E FF  87 6F 38 FF  9A 96 76 FF  sd\.4....o8...v.
0019FAF0: 99 A1 94 FF  6C 80 83 FF  60 54 3E FF  C8 EA EE FF  ....l...`T>.....
0019FB00: A3 C8 DB FF  60 65 4A FF  00 00 00 FF  57 47 4D FF  ....`eJ.....WGM.
0019FB10: 41 42 28 FF  33 2F 18 FF  3C 42 26 FF  38 3B 25 FF  AB(.3/..<B&.8;%.
0019FB20: 4B 61 EB 43  BC 20 15 3E  53 53 53 FF  00 00 80 3F  Ka.C. .>SSS....?
0019FB30: 00 00 80 3F  3F 08 11 3F  33 33 73 3F  00 00 80 3F  ...??..?33s?...?
0019FB40: 65 9B 16 3F  00 00 00 3F  00 00 80 3F  00 00 40 3F  e..?...?...?..@?
0019FB50: 00 00 80 3F  00 00 00 00  00 00 80 3F  00 00 00 00  ...?.......?....
0019FB60: 00 00 00 00  00 00 00 00  FC A2 D1 3E  24 07 00 00  ...........>$...
0019FB70: 8A 81 E4 44  00 00 00 00  0F 00 00 00  A0 FB 19 00  ...D............
0019FB80: 33 22 6D 00  00 00 00 00  77 BD 67 00  FF FF FF FF  3"m.....w.g.....
0019FB90: 08 AE 3D 15  00 00 D4 27  1F 00 00 00  00 00 00 00  ..=....'........
0019FBA0: D0 FB 19 00  3D C1 67 00  00 00 00 00  00 00 00 00  ....=.g.........
0019FBB0: 08 00 D4 27  08 80 54 15  08 00 D4 27  B8 03 5B 44  ...'..T....'..[D
0019FBC0: 20 53 BB C4  B2 7C CE 42  EE 29 F0 43  08 00 D4 00   S...|.B.).C....
0019FBD0: E0 FB 19 00  0B FF 66 00  68 FC 19 00  F8 FB 19 00  ......f.h.......
0019FBE0: 84 FC 19 00  9C 32 48 00  2E DE 96 C4  24 2E 43 15  .....2H.....$.C.
0019FBF0: 08 80 54 15  68 91 62 17  71 E8 57 44  35 83 BA C4  ..T.h.b.q.WD5...
0019FC00: 99 69 DF 42  02 00 00 00  90 FC 19 00  24 07 77 0E  .i.B........$.w.
0019FC10: F0 F1 A9 60  88 76 57 15  5C FC 19 00  A5 F1 A9 60  ...`.vW.\......`
0019FC20: 20 07 77 0E  02 00 00 00  90 FC 19 00  D3 F3 1C 61   .w............a
0019FC30: 90 FC 19 00  20 07 77 0E  88 76 57 15  24 07 77 0E  .... .w..vW.$.w.
0019FC40: 00 00 00 00  B8 03 5B 44  20 53 BB C4  B2 7C CE 42  ......[D S...|.B
0019FC50: B8 03 5B 44  20 53 BB C4  B2 7C CE 42  B8 03 5B 44  ..[D S...|.B..[D
0019FC60: 20 53 BB C4  26 EA DE 42  9F B6 57 44  2F 76 BA C4   S..&..B..WD/v..
0019FC70: 4C 5E E0 42  00 00 00 00  25 06 81 3D  01 00 00 00  L^.B....%..=....

------------------------------------------------------------------------------

======================================================================
Hardware/Driver Information:
Processor:              0x0
Page Size:              4096
Min App Address:        0x10000
Max App Address:        0x7ffeffff
Processor Mask:         0xf
Number of Processors:   4
Processor Type:         586
Allocation Granularity: 65536
Processor Level:        6
Processor Revision:     24067

Percent memory used:    31
Total physical memory:  2147483647
Free Memory:            2147483647
Page file:              -1
Total virtual memory:   2147352576
<--
Let me now in discord if it fixed I am Tobbsu(#4772) ps: have good day^^.

**Comment by slowtorta** [comment]
Included in https://github.com/slowtorta/turtlewow-bug-tracker/issues/449

**Comment by LeopoldHock** [comment]
Hey @Tobbsu,

we believe that this is an issue possibly related to the Discord overlay. I remember you using a modified executable that enables the Discord overlay. Could you try reverting back to the default executable and check whether the error still shows up?
