### ISSUE TITLE
"Mother's Milk" is not available to complete

### ISSUE THREAD

**Issue by Ceibhfhionn** [slowtorta/turtlewow-bug-tracker#3970]
**Please, provide a clear description what the bug is:**

**Steps to reproduce the behavior with as much detail as possible:**

1. Get the quest
2. Get poisoned by Mother Smolderweb with Mother's Milk
3. Go to the Karfang hold using "Astral Recall"
4. Pay the attention that there is no chance to track the quest
5. Get on mount (kodo) and run to Ragged John
6. Try to pass the quest
7. Pay attention that you ate still poisoned but the question mark upon the npc is grey
8. See the message <Ragged John pinches you.>
9. Realize that you cant complete the quest

**IDs of affected creatures, items, quests or spells with a link to the relevant page:**

NPC: https://database.turtle-wow.org/?npc=10596
NPC: https://database.turtle-wow.org/?npc=9563
Quest: https://database.turtle-wow.org/?quest=4866
Spell: https://database.turtle-wow.org/?spell=16468

**Expected behavior. Describe how it should work:**
After getting poisoned by mother's milk the quest should be in Completion stage. Coming to Ragged John and talking to npc should complete the quest.
![image](https://github.com/slowtorta/turtlewow-bug-tracker/assets/139871451/78ae0dc8-5450-49a1-b960-7157a2fb17a0)

**Comment by Jasonstotem** [comment]
Was able to complete the quest by exiting the instance by foot and going to the NPC. Maybe the bug has to do with you using Astral Recall.

**Comment by Jasonstotem** [comment]
I am not a tank nor the first poisoned, however I was the only one delivering the quest.
