### ISSUE TITLE
Spider tank. "Scrapforged Mechaspider" unusable in towns

### ISSUE THREAD

**Issue by boulzorman** [slowtorta/turtlewow-bug-tracker#3971]
**Please, provide a clear description what the bug is:**

Spider tank (exalted gnomeregan mount) can't be mounted on capitals. it works everywhere except in towns

**Steps to reproduce the behavior with as much detail as possible:**

1. Mount on a spider tank
2. Get to a town
3.  See that your are automatically dismounted and can't mount this special one inside towns.

**IDs of affected creatures, items, quests or spells with a link to the relevant page:**

Object: https://database.turtle-wow.org/?object=](https://database.turtle-wow.org/?item=81193)
(this one is blue but exist 3 other colors)

**Expected behavior. Describe how it should work:**

This mount should be available to use inside towns.

**Comment by Gurky-Turtle** [comment]
This is not a bug but is an intended change.
