### ISSUE TITLE
Alliance Quest 'Young and Foolish" not working

### ISSUE THREAD

**Issue by tweak17emon** [slowtorta/turtlewow-bug-tracker#3972]
**Please, provide a clear description what the bug is:**
Alliance Quest Young and Foolish (level 60) does not work properly. It instructs you to go to Lakeshire and talk to residents. The dialog chain is there to talk to the residents but when you do it does not trigger the completion of the task for the quest. All 3 residents you are to talk to can be talked to, but do not trigger the completion. The NPCs are Foreman Oslow, Dorin Songblade, and Magistrate Solomon.

**Steps to reproduce the behavior with as much detail as possible:**

1. Accept quest and fly to Lakeshire
2.  Talk to residents required by quest
3.  Quest does not trigger to move forward, remains 0/1 

**IDs of affected creatures, items, quests or spells with a link to the relevant page:**

Quest: https://database.turtle-wow.org/?quest=80702

**Expected behavior. Describe how it should work:**

When speaking to the NPCs, the quest should trigger complete for each task.

**Comment by Gurky-Turtle** [comment]
![image](https://github.com/slowtorta/turtlewow-bug-tracker/assets/90982783/24df19dc-f91c-4d04-b095-fa78f54907c8)
unable to reproduce this try clearing your wdb folder and retaking the quest

**Comment by Gurky-Turtle** [comment]
![image](https://github.com/slowtorta/turtlewow-bug-tracker/assets/90982783/c9c8845b-b887-47ed-8c7b-2403ecf4d49a)

**Comment by tweak17emon** [comment]
Thank you i will clear wdb folder and retest
