### ISSUE TITLE
Sort Bags Addon

### ISSUE THREAD

**Issue by MasterBruin** [slowtorta/turtlewow-bug-tracker#3973]
Hi, I've wanted to ask if it's possible to adjust the sorting for the larger Turtle WoW Donation Bags, like the 30 slot Bag and the 36 slot Bag for the Sort Bags Addon.
I have three times the 36 slot bag, plus a 24 slot herb bag, and it happens from time to time if I have a large amount of items, that they are greyed out after the sorting.
Another issue I've found, is that both Items [Packet of Tharlendris Seeds] https://database.turtle-wow.org/?item=11022
and [Morrowgrain] https://database.turtle-wow.org/?item=11040 are not sorted into the the herb bag.
But you can definitely put them into it.

**Comment by Gurky-Turtle** [comment]
You will need to ask the author of the addon or ask int eh #addons channel in discord. Sorry this is not a server bug related question.

**Comment by MasterBruin** [comment]
I did. No answer after two weeks lol.

> You will need to ask the author of the addon or ask in the #addons channel in discord. Sorry this is not a server bug related question.

**Comment by McPewPew** [comment]
I tried to find your question on Discord but no amount of searching helped.
This may help -

Open sortbags.lua 
Change the delay on line 139 from 0.2 to a larger figure (perhaps 0.6). This will make the sorting slower, but should reduce errors.
Also change the word "break" on line 269 to "return"

**Comment by MasterBruin** [comment]
> I tried to find your question on Discord but no amount of searching helped. This may help -

Normaly I don't use discord that much, I've asked the author directly on his github page.

> Open sortbags.lua Change the delay on line 139 from 0.2 to a larger figure (perhaps 0.6). This will make the sorting slower, but should reduce errors. Also change the word "break" on line 269 to "return"

Thank you so much, for this information!

I've looked over the lua. file and found out, that I can easily add the item IDs from the missing herbs, under the herb section,  and it totally works!
Now everything, that can be put into the herb bag, will be sorted into the herb bag. I'm so happy right now, I can't describe xD
