### ISSUE TITLE
Pierces Instructions item: typo in its name

### ISSUE THREAD

**Issue by bitchqueenoftheuniverse** [slowtorta/turtlewow-bug-tracker#3974]
Pierces Instructions should be called Pierce's Instructions, since it comes from Pierce Shackleton.

**IDs of affected creatures, items, quests or spells with a link to the relevant page:**
Item: https://database.turtle-wow.org/?item=60391

**Comment by Gurky-Turtle** [comment]
Should be fixed in the next update.
