### ISSUE TITLE
Can't unstealth Hunter pet while controlling it using Eyes of the Beast

### ISSUE THREAD

**Issue by Aegael** [slowtorta/turtlewow-bug-tracker#3977]
When using Eyes of the Beast to control a cat pet with the Prowl (stealth) ability, if you stealth, you aren't unable to unstealth by pressing Prowl a second time. The ability works normally as expected when not controlling the pet with Eyes of the Beast.

**Comment by twowTurtReynolds** [comment]
I think this is just how the client works, works the same way on vmangos. You can right click an enemy and it attacks if you wish.

If you can prove to us that it worked correctly on the 1.12 client back in 2006, do reply.
