### ISSUE TITLE
Sunnyglade valley

### ISSUE THREAD

**Issue by vkekd** [slowtorta/turtlewow-bug-tracker#3978]
The guards at the towers in sunnyglade valley dont attack you if you start capping the flag

- Get to the enemy tower
- Aggro some guards and start capping it
- Mobs will walk all the way to you but they wont attack you

**Comment by twowTurtReynolds** [comment]
![image](https://github.com/slowtorta/turtlewow-bug-tracker/assets/151180101/19fd1456-7b51-4913-979b-51a079c3c5f0)
They seem to be quite intent on killing me.
![image](https://github.com/slowtorta/turtlewow-bug-tracker/assets/151180101/e72a4a8d-7005-42f6-a05d-c0a3d5774e83)
