### ISSUE TITLE
Shadowform MC bug

### ISSUE THREAD

**Issue by Ezzerial** [slowtorta/turtlewow-bug-tracker#3981]
When mind controlled by a mob, after the duration of MC u are out of Shadowform and unable to enter it until logout and log back in (The message on the screen infinitely says Ability is not ready). Happened to me 3 times with same exact pattern (Happened with last boss in Stormwind Vault and "Jadefire Trickster" in Felwood, pretty much sure it will work with various mobs with MC as well, maybe even in pvp)

Steps to reproduce:

1. Being Mind Controlled(within MC i was forced to use Mind Flay or Autoattack on closest allied player)
2. After the duration of MC you are out of Shadowform and unable to turn it on.

**IDs of affected creatures, items, quests or spells with a link to the relevant page:**

NPC: https://database.turtle-wow.org/?npc=93107, https://database.turtle-wow.org/?npc=7107#abilities
Spell: https://database.turtle-wow.org/?spell=12888, https://database.turtle-wow.org/?spell=15473

Expected behavior:

After being MCed u don't leave Shadowform and turning it on and off works normally as intended.

**Comment by Gurky-Turtle** [comment]
duplicate https://github.com/slowtorta/turtlewow-bug-tracker/issues/3592
