### ISSUE TITLE
Shadowform visual bug

### ISSUE THREAD

**Issue by Ezzerial** [slowtorta/turtlewow-bug-tracker#3982]
Shadowform becomes visibly lighter and more transparent after using a mount or taking flight path. If u relog when on a mount your Shadowform gets back to normal but the mount is still in that light transparent state.

**Steps to reproduce the behavior with as much detail as possible:**

1. Use Shadowform
2. Use any mount or flight path

**IDs of affected creatures, items, quests or spells with a link to the relevant page:**

Spell: https://database.turtle-wow.org/?spell=15473

**Expected behavior. Describe how it should work:**
After using any mount in Shadowform it must work as intended (files attached):

![intended 2](https://github.com/slowtorta/turtlewow-bug-tracker/assets/134404400/e68da5e8-a15a-47f8-9338-954a11459746)
![normal](https://github.com/slowtorta/turtlewow-bug-tracker/assets/134404400/5e6c657b-a85b-4868-9c3f-84a5d2b023d5)
![bug mounted](https://github.com/slowtorta/turtlewow-bug-tracker/assets/134404400/952d878a-f49e-43f0-80bc-54e065245efa)
![relog bug](https://github.com/slowtorta/turtlewow-bug-tracker/assets/134404400/38093ea7-8f01-44a9-9b84-6bab2e54c702)
![default mount](https://github.com/slowtorta/turtlewow-bug-tracker/assets/134404400/949fb9ed-6169-4fb0-afac-7e8acbcee0f0)
![intended](https://github.com/slowtorta/turtlewow-bug-tracker/assets/134404400/632ee5e6-f7ae-48c3-afca-ad7f38511afe)
![flight bug](https://github.com/slowtorta/turtlewow-bug-tracker/assets/134404400/c09bede8-81ed-45c6-8917-fdcc86578c70)
![image](https://github.com/slowtorta/turtlewow-bug-tracker/assets/134404400/8448d7e8-3b3a-4fca-862a-99bd764018f4)

**Comment by GrizB37** [comment]
Always been like this even back in 2005 vanilla. was fixed in TBC.
Not sure what causes the issue when you mount, would be nice to fix this as it kinda ruins the Shadow Priest class fantasy a little

**Comment by Muigin** [comment]
This has been fixed and will be pushed in our next client patch (1.17.1)
