### ISSUE TITLE
hammer of warth miss chance bugged

### ISSUE THREAD

**Issue by geojak** [slowtorta/turtlewow-bug-tracker#3983]
**Please, provide a clear description what the bug is:**

since the last restart this ability now misses all the time. multiple people noticed somthing changed

**Expected behavior. Describe how it should work:**

pelase investiage what happened to hammer of warths missing too much suddenly

**Comment by Gurky-Turtle** [comment]
duplicate https://github.com/slowtorta/turtlewow-bug-tracker/issues/3716

**Comment by Gurky-Turtle** [comment]
Could be the grunts seeing I am not seeing anything changed recently with it.

**Comment by balakethelock** [comment]
Not a duplicate, This is a new bug. most likely related to the recent fix to weapon skill on abilities

**Comment by balakethelock** [comment]
> ok i think i understood it now the miss changed until very recentl was meele hit based and the crit chance was spell crit based (barely ever critted) this has flipped now to spell hit (therefor alot of more misses) but the crit chance seems to be meele crit now (more crit) the current new behaviour is the blizzlike behaviour. this explains the other issue too

Are you absolutely sure? hammer of wrath is a ranged attack, works like arcane shot. It's supposed to use physical hit chance.

**Comment by balakethelock** [comment]
@geojak should be reopened. Like I guessed, fix to weapon skills on abilities broke hammer of wrath. But we cought that already and made a fix in vmangos, so it's weird that its bugged here https://github.com/vmangos/core/pull/2086
