### ISSUE TITLE
wastewander in tanaris rep gain bugged

### ISSUE THREAD

**Issue by geojak** [slowtorta/turtlewow-bug-tracker#3984]
**Steps to reproduce the behavior with as much detail as possible:**

1. note down your rep with all steemwhedle cartel factions
2. kill a wastewanderer in tanrais dessert
3. see a message pop up ++5 rep to steemwheedle cartel
4. chec kyour repuation, see you gained zero rep to all factions

**Expected behavior. Describe how it should work:**
should rpobaly be changed to +5 gatgetzan rep only and this is probabyl what is bugging this

**Comment by Gurky-Turtle** [comment]
Double https://github.com/slowtorta/turtlewow-bug-tracker/issues/2147
