### ISSUE TITLE
Sunny Glade NPCS Demo Shout

### ISSUE THREAD

**Issue by GrizB37** [slowtorta/turtlewow-bug-tracker#3988]
**Please, provide a clear description what the bug is:**
SInce the Sunnyglade 'fixes' the alliance and *only* the alliance NPCs use a demo shout that has like a 300 yard range, which pulls any stealth class out of stealth... this is very annoying as the debuff is -300 AP....

Also its kinda annoying the horde grunts dont debuff alliance players.

**Steps to reproduce the behavior with as much detail as possible:**

1. Go in sunnyglade, get near an alliance NPC and get demo shouted a mile away.
2. 
3. 

**IDs of affected creatures, items, quests or spells with a link to the relevant page:**

NPC: https://database.turtle-wow.org/?npc=
Item: https://database.turtle-wow.org/?item=
Quest: https://database.turtle-wow.org/?quest=
Spell: https://database.turtle-wow.org/?spell=
Object: https://database.turtle-wow.org/?object=

**Expected behavior. Describe how it should work:**

Reduce the range of this demo shout, and for petes sake give the horde grunts it too to stop this imbalance.

TY

**Comment by ratkosrb** [comment]
This was already changed and they use a much weaker version of demo shout now.
