### ISSUE TITLE
Rotting Slime in Ashenvale gives persistent movement speed debuff

### ISSUE THREAD

**Issue by ConnorCable** [slowtorta/turtlewow-bug-tracker#3989]
**Please, provide a clear description what the bug is:**

Rotting Slime gives persistent speed debuff if character relogs during the debuff

**Steps to reproduce the behavior with as much detail as possible:**

1. Allow Rotting Slime to attack and give you disease
2. I lost my internet connection, then relogged
3.  The movement speed debuff persisted after relogging

**IDs of affected creatures, items, quests or spells with a link to the relevant page:**

NPC: https://database.turtle-wow.org/?npc=3928

**Expected behavior. Describe how it should work:**

Debuff should go away after specified time

**Comment by twowTurtReynolds** [comment]
I let the debuff get to 15s left, disconnected my internet, restarted the client, reconnected, and I no longer have the debuff but also have full movespeed.
