### ISSUE TITLE
Wrong Ability, Spell Improved Info & Mount Sound.

### ISSUE THREAD

**Issue by Tobbsu** [slowtorta/turtlewow-bug-tracker#399]
(1) Hey Is Tobbsu Again I have see that the Improved Info on Ability´s & spells not show the Right Info and stays with old info any way you guys can fix that.
(2) It be nice if mount make sound when you stay still and hit space bar it make sound but it don't.

**Comment by slowtorta** [comment]
Included in https://github.com/slowtorta/turtlewow-bug-tracker/issues/449
