### ISSUE TITLE
Quest: Libram of Voracity is undoable

### ISSUE THREAD

**Issue by nightsage217** [slowtorta/turtlewow-bug-tracker#3991]
"Libram of Voracity" is a repeatable quest, by given correct materials, players will be given a respective Lesser Arcanum of Voracity. Yet, the quest dialogue is unable to proceed via clicking "continue" button.

1. Collect at least 4 crystal force, 1 Libram of voracity, 4 Runn Tum Tuber, 1 Black Diamond and 30gold from farming, dungeon, trading, and or auction house purchase.
2. The player travels to Eastern Kingdom - Burning Steppes, and meet an NPC called Mathredis Firestar in open world landscape.
3. Take a conversation with the named NPC and select respective named quest - Libram of Voracity.
4. The dialogue is not proceed able with "continue" button" despite the character has items (step 1) in the bag.

ID:
Quest: https://database.turtle-wow.org/?quest=4484
Quest NPC: https://database.turtle-wow.org/?npc=9836
Quest Reward: https://database.turtle-wow.org/?item=11645

Quest Materials:
https://database.turtle-wow.org/?item=11737
https://database.turtle-wow.org/?item=11754
https://database.turtle-wow.org/?item=11951
https://database.turtle-wow.org/?item=11563

Expected behavior:
1. Collect at least 4 crystal force, 1 Libram of voracity, 4 Runn Tum Tuber, 1 Black Diamond and 30g from farming, dungeon, trading, and or auction house purchase.
2. The player travels to Eastern Kingdom - Burning Steppes, and meet an NPC called Mathredis Firestar in open world landscape.
3. Take a conversation with the named NPC and select respective named quest - Libram of Voracity.
4.  If the required quest materials are in place in the bag of the character, the player can choose 1 type of Lesser Arcanum of Voracity out of 5.
5. After select 1 type of Lesser Arcanum of Voracity, the required quest materials will be deducted from the cahracter's bag and replaced with single(1) selected  Lesser Arcanum of Voracity.
6. The quest itself is repeatable, and player may repeat the process 1~5.

Picture:
![Untitled](https://github.com/slowtorta/turtlewow-bug-tracker/assets/140063176/b1dffd10-3751-4e5e-932a-1dc8a4b692db)

**Comment by Gurky-Turtle** [comment]
Remove the quest if it's in your log then quit wow and delete your wdb folder
