### ISSUE TITLE
Blackflame Wand has no model/Only does shadow damage.

### ISSUE THREAD

**Issue by ConcernedTurtler** [slowtorta/turtlewow-bug-tracker#3993]
**Please, provide a clear description what the bug is:**

The blackflame wand from crescent grove has no model and only does shadow damage.  The item description says it does both shadow and fire damage.

**Steps to reproduce the behavior with as much detail as possible:**

1. Get blackflame wand.
2. use it on an enemy.
3. check combat log.

**IDs of affected creatures, items, quests or spells with a link to the relevant page:**

https://database.turtle-wow.org/?item=83215

**Comment by balakethelock** [comment]
Works according to the technical limits of vanilla wow the server is built on
Source: https://www.wowhead.com/classic/news/blizzard-clarifies-that-extra-elemental-damage-from-weapons-is-working-as-316707

**Comment by ConcernedTurtler** [comment]
I don't they said it was a technical limitation, just the way they were designed in classic.

**Comment by twowTurtReynolds** [comment]
This is an oddball design for a wand, but that is rather cool, don't you agree? It works as it is designed.

As for the model issue, that will be tracked under https://github.com/slowtorta/turtlewow-bug-tracker/issues/4211
