### ISSUE TITLE
TWoW Sunken Temple trash mobs missing loot from table

### ISSUE THREAD

**Issue by Jurwah** [slowtorta/turtlewow-bug-tracker#3998]
Elite trash mobs in Sunken Temple no longer drop Hakkari Shroud or Hakkari Breastplate, and Mark of Hakkar no longer drops from Oozelings in the instance. According to TurtleDB, The breastplate is only obtainable through the quest reward Hakkari Urn and the shroud is the same except for one rare mob spawn in EPL, Baron Bloodbane, at a ~0.1% drop chance. I cannot find any other items missing from the trash loot tables. On Classic DB, it says all three are obtainable through ST trash mobs as well as Hakkari Urn, Steel Lockbox, and Sturdy Junkbox.

Steps to reproduce:
1a. Kill any of the following trash mobs:
- Oozeling   https://database.turtle-wow.org/?npc=8257
- Murkworm   https://database.turtle-wow.org/?npc=5226
- Deep Lurker   https://database.turtle-wow.org/?npc=8384
- Saturated Ooze   https://database.turtle-wow.org/?npc=5228
- Atal'ai Witch Doctor   https://database.turtle-wow.org/?npc=5259
- Unliving Atal'ai   https://database.turtle-wow.org/?npc=5267
- Atal'ai Corpse Eater   https://database.turtle-wow.org/?npc=5270
- Nightmare Wyrmkin   https://database.turtle-wow.org/?npc=5280
- Jaedenar Adept   https://database.turtle-wow.org/?npc=7115
- Slime Maggot   https://database.turtle-wow.org/?npc=8311
- Nightmare Whelp   https://database.turtle-wow.org/?npc=8319
- Hakkari Sapper   https://database.turtle-wow.org/?npc=8336
- Hakkari Bloodkeeper   https://database.turtle-wow.org/?npc=8438

1b. Loot any of the following:
- Steel Lockbox   https://database.turtle-wow.org/?item=4637
- Sturdy Junkbox   https://database.turtle-wow.org/?item=16884

2. Do not find the following items:
- Hakkari Shroud   https://database.turtle-wow.org/?item=10782
- Hakkari Breastplate   https://database.turtle-wow.org/?item=10781
- Mark of Hakkar   https://database.turtle-wow.org/?item=10780

Classic DB links for items with listed mobs and containers:
https://classicdb.ch/?item=10780
https://classicdb.ch/?item=10781
https://classicdb.ch/?item=10782

Requesting these items to be reinstated to either all of their classic DB loot table locations and percentages or at least to the Sunken Temple trash mobs indicated so it's possible to obtain more than just one from the one-time urn quest.

**Comment by Gurky-Turtle** [comment]
Hakkari Shroud can no longer drop from creatures.

https://forum.turtle-wow.org/viewtopic.php?p=51551&hilit=Hakkari#p51551

Just so you are also aware [https://classicdb.ch](https://classicdb.ch/?item=10780) is not a reliable source that is Vanilla Gaming's DB (another private server)
