### ISSUE TITLE
High Elf, Revered Level 60 Want

### ISSUE THREAD

**Issue by Emmizabeth** [slowtorta/turtlewow-bug-tracker#4]
By opening this Issue, I admit to having done the pertinent research using sources from Vanilla (preferably) or Classic. I also understand that sources from other private servers are not acceptable.

**Current behavior**: 
Has no spell animation, sound or even character animation - My character just stands still while the monster is loosing health

**Expected behavior**: 
To shoot visual magic like other wands and have my character using the proper animations

**Proofs**:

**Steps to reproduce**:

1. 
2. 
3.

**Comment by slowtorta** [comment]
I don't understand what is this report about. What's broken: spells, reputation, character model?

**Comment by slowtorta** [comment]
https://database.turtle-wow.org/?npc=10181 It looks like GM morphed you into this creature model. This is not meant to be a player's model, nor it has all required animations. Your problem will solve itself upon the next logout.

**Comment by Emmizabeth** [comment]
I’ve tested it without sylv morph, and
Again today, while not being morphed, its still an issue 😊

Emmi
Sendt fra Mail<https://go.microsoft.com/fwlink/?LinkId=550986> til Windows 10

Fra: Torta<mailto:notifications@github.com>
Sendt: 5. februar 2021 12:37
Til: slowtorta/turtlewow-bug-tracker<mailto:turtlewow-bug-tracker@noreply.github.com>
Cc: Emmizabeth<mailto:sorend@live.dk>; Author<mailto:author@noreply.github.com>
Emne: Re: [slowtorta/turtlewow-bug-tracker] High Elf, Revered Level 60 Want (#4)


https://database.turtle-wow.org/?npc=10181 It looks like GM morphed you into this creature model. This is not meant to be a player's model, nor it has all required animations. Your problem will solve itself upon the next logout.

**Comment by slowtorta** [comment]
Alright. Please provide the item name or ID.

**Comment by Emmizabeth** [comment]
Dont know ID, but item name is Quel’ Dorei Magister’s Spellflinger – Its a blue wand sold at the Helf quartermaster

Emmi

Sendt fra Mail<https://go.microsoft.com/fwlink/?LinkId=550986> til Windows 10

Fra: Torta<mailto:notifications@github.com>
Sendt: 5. februar 2021 13:44
Til: slowtorta/turtlewow-bug-tracker<mailto:turtlewow-bug-tracker@noreply.github.com>
Cc: Emmizabeth<mailto:sorend@live.dk>; Author<mailto:author@noreply.github.com>
Emne: Re: [slowtorta/turtlewow-bug-tracker] High Elf, Revered Level 60 Want (#4)


Alright. Please provide the item name or ID.
