### ISSUE TITLE
Taming the Beast questline done twice

### ISSUE THREAD

**Issue by nonameform** [slowtorta/turtlewow-bug-tracker#40]
**Current behavior**: 
I was able to complete _Taming the Beast_ questline twice at Razor Hill. Once with Orcs, once with Goblins.

**Expected behavior**: 
You are only supposed to learn how to tame beasts once. However, you can tame them twice for extra XP. I was able to finish the second questline after I already got my Tame Beast ability as a Hunter.

**Steps to reproduce**:
1. Do questline with [Thotar](https://database.turtle-wow.org/?npc=3171).
2. Do questline with [Viz Fizbeast](https://database.turtle-wow.org/?npc=80903).

P.S. On Alliance side I was able to pick up _[The Hunter's Path](https://database.turtle-wow.org/?quest=6076)_ at SW after I have done the questline as well. It is supposed to be only a breadcrumbs quest and as a result the NPCs should not offer it to you once you are done with the main questline.

**Comment by slowtorta** [comment]
Thanks for reporting it. It's fixed and will be deployed on the next server update.
