### ISSUE TITLE
Booty Bay Alchemist willing to teach non-alchemists

### ISSUE THREAD

**Issue by AyleeJenn** [slowtorta/turtlewow-bug-tracker#400]
**Please, provide a clear description what the bug is:**

The expert alchemist in booty bay by the name of "Jaxin Chong" is willing to teach alchemy recipes to people who do not have the alchemy profession. **_There seems to be no requirement to have alchemy profession to learn alchemy recipes!!_**

![booty_bay_alchemist1](https://user-images.githubusercontent.com/87241085/138899181-feb34335-5874-4140-99a7-2a8800b14075.jpg)

![booty_bay_alchemist2](https://user-images.githubusercontent.com/87241085/138899858-3eb0e17d-a986-433b-b8fb-7d6000691e53.jpg)

However ... talking to the alchemist a second time will turn the recipes to red. This only seems to happen if a player deletes their WDB folder prior to this. So, this only happens if a player logs in and talks to the alchemist the first time after deleting their WDB folder.

**Steps to reproduce the behavior with as much detail as possible:**

1. Make sure you are not an alchemist and then travel to Booty Bay and find "Jaxin Chong" in one of the upper huts
2. Talk to him and select "Train Me".
3. Observe a list of green (Learnable!) alchemy recipes you should not have access to (since you are not an alchemist)

**IDs of affected creatures, items, quests or spells with a link to the relevant page:**

NPC: https://database.turtle-wow.org/?npc=2837
Item: https://database.turtle-wow.org/?item=
Quest: https://database.turtle-wow.org/?quest=
Spell: https://database.turtle-wow.org/?spell=
Object: https://database.turtle-wow.org/?object=

**Expected behavior. Describe how it should work:**
What you would expect here is that the alchemist would prompt non-alchemists to learn "Journeyman Alchemist" first before making recipes available. Despite the aforementioned second attempt of talking to the alchemist (after deleting WDB folder) turnnig recipes red, the alchemist still does not offer to teach "Journeyman Alchemist".

**Comment by slowtorta** [comment]
Thank you. This will be fixed on the next server update.
