### ISSUE TITLE
Basilisk Brain Not dropping

### ISSUE THREAD

**Issue by ChanningTotem** [slowtorta/turtlewow-bug-tracker#4002]
**Please, provide a clear description what the bug is:**

**Steps to reproduce the behavior with as much detail as possible:**

1. Basilisk Brain (https://database.turtle-wow.org/?item=8394) doesn't drop from saltjaw basilisk and deepstone basilisk, but according to the turtle wow database it drops from those mobs. Just wanted to know if the item was omitted from those mobs. cause i farmed the entire cave for atleast 30 minutes and it never dropped and my guildmates can also confirm that it doesnt drop anymore. thanks 
2. 
3. 

**IDs of affected creatures, items, quests or spells with a link to the relevant page:**

NPC: https://database.turtle-wow.org/?npc=8802 
NPC: https://database.turtle-wow.org/?npc=2174
Item: https://database.turtle-wow.org/?item=10923
Quest: https://database.turtle-wow.org/?quest=2602

**Expected behavior. Describe how it should work:**

the item should drop from those NPC's for the quest Infallible mind from blasted lands.

**Comment by Gurky-Turtle** [comment]
https://github.com/slowtorta/turtlewow-bug-tracker/issues/3310

looks like someone reported it dropping from them and was fixed in an old update. The Web database will be out of date until after the next patch.
