### ISSUE TITLE
Bloodthirst Do not Work Correct Anymore !! Need Fix Asap pls

### ISSUE THREAD

**Issue by Backtoroots1** [slowtorta/turtlewow-bug-tracker#4004]
**Please, provide a clear description what the bug is:**

**Steps to reproduce the behavior with as much detail as possible:**

1. no steps required
2. unbuffed testing 
3. unbuffed 948 Ap each bloodthirst without anything up dmg for 256 dmg (non crit) thats not 45% of Ap ! 45% of 948 are 426,6... ! https://www.wowhead.com/classic/spell=23881/bloodthirst So what Exactily got Changed ?
Bloodthirst now correctly uses weapon skill. <- ? That the Dmg lowered.

**IDs of affected creatures, items, quests or spells with a link to the relevant page:**

NPC: https://database.turtle-wow.org/?npc=
Item: https://database.turtle-wow.org/?item=
Quest: https://database.turtle-wow.org/?quest=
Spell: https://database.turtle-wow.org/?spell=23881/bloodthirst
Object: https://database.turtle-wow.org/?object=

**Expected behavior. Describe how it should work:**
its 27-28% AP right now not 45% ! pls fix it asap :( cheers

**Comment by lyssebabz** [comment]
i can confirm this. had AP at 2.7k and my bloodthirst didn't go over 2.2k crit and 1k non crit
