### ISSUE TITLE
Rogue talent [Vile Poisons] is broken

### ISSUE THREAD

**Issue by Phobos-Programmer** [slowtorta/turtlewow-bug-tracker#4006]
**Please, provide a clear description what the bug is:**
Rogue talent [Vile Poisons] does not add addition dispel resist effect. With 5/5 it should grant +40% to resist dispel, but on TW for some reason it does not add any additional dispel resistance. I tested it with the druid "Cure Poison", "Abolish Poison", "Poison Cleansing Totem", shaman "Cure Poison" and all these abilities each time dispel poison without any resistance. I want to mention that the main destination of this talent is dispel resistance because poison damage in vanilla classic is very low and useless.
**Steps to reproduce the behavior with as much detail as possible:**
1. Invest 5 talents Vile Poisons 
2. Apply a debuff poison like from .learn 3408
3. attack target, apply a poison, then type .cast self 526
4. repeat a bunch and see no times where the cure poison spell fails.

**IDs of affected creatures, items, quests or spells with a link to the relevant page:**
https://database.turtle-wow.org/?spell=3212
https://database.turtle-wow.org/?spell=2897
https://database.turtle-wow.org/?spell=2893
https://database.turtle-wow.org/?spell=1315

**Expected behavior. Describe how it should work:**
When rogue invests in Vile Poisons talents it should give additional 40% to resist poison dispel

**Comment by twowTurtReynolds** [comment]
Updated your replication steps. It seems to be working as expected on both vmangos and TWoW.
