### ISSUE TITLE
Trash Collector Gaston Blue items buyback

### ISSUE THREAD

**Issue by cesar-pix** [slowtorta/turtlewow-bug-tracker#4011]
**Please, provide a clear description what the bug is:**
As I understand and was told by a GM, Trash Collector Gaston should be able to sell you the 140 last items I had destroyed or sold, including blue equipment, but it only shows me old quest items I discarded.

**Steps to reproduce the behavior with as much detail as possible:**

1. Go to Ratchet
2. Speak to Trash Collector Gaston
3. Look at his wares

**IDs of affected creatures, items, quests or spells with a link to the relevant page:**

NPC: https://database.turtle-wow.org/?npc=8

**Expected behavior. Describe how it should work:**
Buy for him blue equipment sold to a vendor

**Comment by twowTurtReynolds** [comment]
![image](https://github.com/slowtorta/turtlewow-bug-tracker/assets/151180101/37857f2a-18df-4f38-a8f2-46b43b0df412)
Replicated. I sold a few blue items, sold a bunch of greens to fill the buyback tab, relogged, and the blue items are not for sale. I will check with the staff if this is intended.

**Comment by twowTurtReynolds** [comment]
Confirmed with management, working as intended. Sold items are not available on Gaston, only deleted items.
