### ISSUE TITLE
Bonescythe Glitch

### ISSUE THREAD

**Issue by Jorrak** [slowtorta/turtlewow-bug-tracker#4012]
**Please, provide a clear description what the bug is:**
When wearing the Bonescythe Gauntlets and Bracers, the gloves can become very large. As if the bracers are showing outside of the gauntlets.
**Steps to reproduce the behavior with as much detail as possible:**

1. Happens after repairing.
2. Happens randomly in combat.
3. Taking the bracers or gauntlets off and reequipping them fixes the glitch.

**IDs of affected creatures, items, quests or spells with a link to the relevant page:**
https://database.turtle-wow.org/?item=22481
https://database.turtle-wow.org/?item=22483

NPC: https://database.turtle-wow.org/?npc=
Item: https://database.turtle-wow.org/?item=
Quest: https://database.turtle-wow.org/?quest=
Spell: https://database.turtle-wow.org/?spell=
Object: https://database.turtle-wow.org/?object=

**Expected behavior. Describe how it should work:**
How it should look.
![image](https://github.com/slowtorta/turtlewow-bug-tracker/assets/140275536/10cdbcef-0a8f-48ee-8c3f-5e78f93c0d45)
How it looks when it glitches.
![image](https://github.com/slowtorta/turtlewow-bug-tracker/assets/140275536/bc88b34a-adc1-4487-99ed-00cdffb6d7b0)

**Comment by RUTHINAS** [comment]
This tends to happen when the character is wearing a shirt with flared sleeves.

**Comment by slowtorta** [comment]
Won't be fixed.
