### ISSUE TITLE
Bug report

### ISSUE THREAD

**Issue by Juseer01** [slowtorta/turtlewow-bug-tracker#4014]
**Please, provide a clear description what the bug is:**
When I do the quest 《The Terrors of the Webweavers》, I've been waiting the target《Nerubian Overseer》 for a real long time.    I saw its body before the server restart, after that I waited for more than 3 hours, but he did not refresh.

**Steps to reproduce the behavior with as much detail as possible:**

1.I do the quest 《The Terrors of the Webweavers》
2. I wait for the target《Nerubian Overseer》
3. It hasn't appeared for a long, long time

**IDs of affected creatures, items, quests or spells with a link to the relevant page:**
NPC ID:14698
NPC: https://database.turtle-wow.org/?npc=
Item: https://database.turtle-wow.org/?item=
Quest: https://database.turtle-wow.org/?quest=
Spell: https://database.turtle-wow.org/?spell=
Object: https://database.turtle-wow.org/?object=

**Expected behavior. Describe how it should work:**
Please let it refresh

**Comment by OonaFae** [comment]
Nerubian Overseer is a 40 man world boss and only spawns once a week. The spawn times are as expected.

**Comment by twowTurtReynolds** [comment]
Notice the (Raid) designation too!
