### ISSUE TITLE
 Diamond Flask abuse

### ISSUE THREAD

**Issue by Phobos-Programmer** [slowtorta/turtlewow-bug-tracker#4018]
**Please, provide a clear description what the bug is:**
Nowadays everyone on the Blood Ring starts abusing the item named "Diamond Flask". People (usually warriors) make rich healing gear set (big +healing effects score) and use this trinket in pvp (usually in Blood Ring before arena gates are opened) and get on next 60 sec hot which heals character each 5 seconds for ~1500 HP during next 60 seconds. So, in total the abuser will get free 18000 healing in one minute. Someone can say it's not a bug, but guys, healing on 18000+ HP for non-healer spec in classic is a mega big number and for my opinion is disbalanced. 
According to comments from discord: "Basically the returns on +heal gear are between 1200% and 1400%". Also with BIS  healing it is possible to reach ~2000 hp healing per tick.

**Steps to reproduce the behavior with as much detail as possible:**
1) get this trinket from quest
2) make a gear set with rich + healing stats
3) in a few seconds till the BR gate opens, wear healing set and use this trinket, now you get mega healing in the next 1 minute. Also you don't have to use it right before gates are opened. You can do it later when you are not in combat.
4) after you used Diamond Flask, gear you usual set and do damage as usual with powerful free healing for next 1 minute 

**IDs of affected creatures, items, quests or spells with a link to the relevant page:**
https://database.turtle-wow.org/?item=20130
https://database.turtle-wow.org/?quest=8425

**Expected behavior. Describe how it should work:**
heal numbers for non healer spec characters should be much lower than 18000 healing. I suggest to calculate heal score right on each tick, in that case healing will be still strong, but at least damager specs won't abuse it

**Comment by GrizB37** [comment]
This needs to be removed ASAP... Blizzard I'm sure never intended this, which is why it was removed in Tbc... At the very least let warriors keep their set but remove in arena and possibly BG's. 

Thanks.

**Comment by Muigin** [comment]
This issue is no longer relevant in current version.
