### ISSUE TITLE
Demonic Aegis Talent not properly working

### ISSUE THREAD

**Issue by OriginalNicName** [slowtorta/turtlewow-bug-tracker#4019]
**Please, provide a clear description what the bug is:**
I believe the Demonic Aegis talent is not properly applying the % bonus to Demon armor and Demon skin as intended. The spell displays the improved stats, however the corresponding buff it applies shows the default numbers. To clarify I don't actually know if the talent is bugged, but the tooltips for the buff are certainly not correct, additionally, as I am only lvl 30, I can only report the spells/ talents at the ranks I have unlocked.  

**Steps to reproduce the behavior with as much detail as possible:**

1. Add talent point into Demonic Aegis, found in the warlock demonology talent tree. 
2. cast Demon armor or Demon skin, any rank.
3. compare stats bonuses in spell tooltip and buff tooltip. if bugged, you'll notice differing stats.

**IDs of affected creatures, items, quests or spells with a link to the relevant page:**

Demonic Aegis Rank 1: https://database.turtle-wow.org/?spell=45921
Demon Skin Rank 1: https://database.turtle-wow.org/?spell=687
Demon Skin Rank 2: https://database.turtle-wow.org/?spell=696
Demon Armor Rank 1: https://database.turtle-wow.org/?spell=706
Demon Armor Rank 2: https://database.turtle-wow.org/?spell=1086

**Expected behavior. Describe how it should work:**
Talent should apply the improved stats on both the affected spells and the respective buffs they create, and those stats should be correctly implemented.

**Comment by TatkaS1** [comment]
It's just the buff tooltip that doesn't update. The spell tooltip and what you actually get is correct. I tested it with all ranks of Demon Skin and Demon Armor. Works perfectly.
