### ISSUE TITLE
Mobs don't give exp

### ISSUE THREAD

**Issue by TatkaS1** [slowtorta/turtlewow-bug-tracker#4021]
**Please, provide a clear description what the bug is:**
2 types of imps (Flamekin Ragers and Torchers) in Burning Steppes do not give experience.

**Steps to reproduce the behavior with as much detail as possible:**

1. Kill Flamekin Rager/Torcher in Burning Steppes.
2. Don't get rewarded experience.
3. Don't get a soul shard if Drain Soul (because it only rewards Soul Shard if the enemy would give exp/hk).

**IDs of affected creatures, items, quests or spells with a link to the relevant page:**

NPC: https://database.turtle-wow.org/?npc=9778
NPC: https://database.turtle-wow.org/?npc=9779

**Expected behavior. Describe how it should work:**
Those mobs should give experience as the other types of Flamekin (Flamekin Spitters and Sprites) do.

**Comment by xhummerx** [comment]
those mobs should give 1/5 of the xp i recall, but they were giving 100 % so they removed the xp completly

**Comment by TatkaS1** [comment]
Woah there with the closing, it's clearly still bugged either way. Should be giving 20% of whatever exp then.
