### ISSUE TITLE
Cannot ressurect party members when they release if they are from the opposite faction

### ISSUE THREAD

**Issue by JohnDogson** [slowtorta/turtlewow-bug-tracker#4023]
Party member died and released, wasn't able to be ressurected by mouseover

**Comment by ratkosrb** [comment]
The only way to make enemy faction corpse targetable by resurrection spells, is to report the wrong race to the client, but this will cause the wrong textures to be used on the corpse model.

![WoWScrnShot_072523_074956](https://github.com/slowtorta/turtlewow-bug-tracker/assets/35845488/d72059c7-8e99-46a5-90a2-f2f48b39f972)

Corpse update fields do not contain a faction id, and instead the client uses the race to determine if its a friendly corpse or not. Is having corpses use wrong textures in cross faction groups an acceptable trade off, to be able to resurrect them, or do you prefer things to remain as they are now?

**Comment by GrizB37** [comment]
Not a bug, client limitation, not a huge deal, just don't release spirit.

**Comment by twowTurtReynolds** [comment]
The staff have decided this indeed will not be fixed. Always remember to teach new players to groups and raids of this unfortunate bug.
