### ISSUE TITLE
HC Character Death Due To Possible Hearth Bug

### ISSUE THREAD

**Issue by bryanargg** [slowtorta/turtlewow-bug-tracker#4024]
I hearthed while on the surface of water, 100% breath and NOT losing breath. Not in combat in Desolace.

Upon the hearth going through back to Thunderbluff, after the loading screen, my character died. (Name was Rhythmalism Lvl 33 Hunter)

I made sure I was on the surface and not underwater and/or losing breath. I hearthed as normal and it am still clueless as to why I died. 

If you hearth, I don't see why you would suddenly die (unless maybe you're underwater and losing breath maybe?) I was in Northwest desolace near the Naga island doing quests and clearing mobs. Everything seemed normal, and when I was done, I decided to hearth.

I did not take any screenshots and I don't stream while I play, so It's definitely something I would look into. I told everyone in the Still Alive Guild chat to warn them, but I hope it doesn't happen again. Losing a character like that to no fault of my own is frustrating.

Happened last night around 10:30pm EST (not server time)

Thank you.

**Comment by cyaohiri** [comment]
It's hard to say what happened if you didn't have look at the combat log; the damage would've been logged there, but it could be the elite giant that roams around there.

**Comment by bryanargg** [comment]
Was not in combat. Died when hearth loaded in TB.

**Comment by twowTurtReynolds** [comment]
![image](https://github.com/slowtorta/turtlewow-bug-tracker/assets/151180101/adf16ed2-b6e2-4d90-b2c5-d35ba6d9c364)
![image](https://github.com/slowtorta/turtlewow-bug-tracker/assets/151180101/cda11251-1be1-4045-9f83-572801a9591e)
I'm sorry, I really absolutely have no idea how you possibly died from this.

If you can replicate this on a softcore, do tell.
