### ISSUE TITLE
Slavering ghouls have thrash, with no cooldown

### ISSUE THREAD

**Issue by CmonMan1** [slowtorta/turtlewow-bug-tracker#4026]
**Please, provide a clear description what the bug is:**
In south western plaugelands there is Skeletal Flayers and Slavering ghouls, (according to information I can find online) only the Skeletal Flayers should have Thrash, but both the ghouls and the flayers have it, I think the ghouls are only supposed to have a venom. Im not sure if thrash supposed to have a cooldown, but I get hit 5 times from a single auto attack. I believe it may be more of a mistake than a bug, but I do not know the proper way to report it.
**Steps to reproduce the behavior with as much detail as possible:**

1.Fight a slavering ghoul
2. 
3. 

**IDs of affected creatures, items, quests or spells with a link to the relevant page:**

NPC: https://database.turtle-wow.org/?npc=
Item: https://database.turtle-wow.org/?item=
Quest: https://database.turtle-wow.org/?quest=
Spell: https://database.turtle-wow.org/?spell=
Object: https://database.turtle-wow.org/?object=

**Expected behavior. Describe how it should work:**

**Comment by ratkosrb** [comment]
I checked my packet sniffs from classic, and Slavering Ghoul is supposed to cast Thrash. It's not a bug.
![Untitled](https://github.com/slowtorta/turtlewow-bug-tracker/assets/35845488/4ebe3f7f-025a-4958-9584-c784423a076c)

**Comment by CmonMan1** [comment]
Ah, sorry to take you're time, like I said I was going off of what I seen online, I looked up after I got pretty much instantly killed, when I seen the information, I figured it was an easy mistake to me, but apparently the site (and myself) are mistaken.
