### ISSUE TITLE
Respawn Time Bug: Roaming Felguard

### ISSUE THREAD

**Issue by AyleeJenn** [slowtorta/turtlewow-bug-tracker#4027]
**Please, provide a clear description what the bug is:**
In the Dungeon "Crescent Grove" there appear to be two groups of "Roaming Felguard" that respawn in a five minute interval, as opposed to a regular two hour interval. I have tried to screenshot the two groups and I am adding the screenshots to this report for further clarity

![Crescent Grove 5 Minute 1a](https://github.com/slowtorta/turtlewow-bug-tracker/assets/87241085/871b29e5-f639-4156-957b-19ed58efcc37)
The first group is a set of three roaming felguards located at the junction of where you can choose your route to go either to the satyr, the burning legion chief or the undead ghost route leading to the undead night elf priestess.
We waited around to verify this and indeed after five minutes the set of three roaming felguards respawned. Here is the evidence of this in the following screenshot ...

![Crescent Grove 5 Minute 3a](https://github.com/slowtorta/turtlewow-bug-tracker/assets/87241085/89dcad9d-7a2b-452f-be47-7b83308694e9)
Note that the remains of the previous felguard haven't even despawned yet and the group of three is already back ...

![Crescent Grove 5 Minute 2a](https://github.com/slowtorta/turtlewow-bug-tracker/assets/87241085/e0f49dbb-e65b-48b2-a0a9-41bb6d460299)
The second group of roaming felguards exhibiting this irregular respawn timer is located directly near the previously mentioned group of three felguards. My team and I also waited around to verify this group and, indeed, after only five minutes this group also respawned. And in the following screenshot you can see the group of two roaming felguards having respawned again as well.

![Crescent Grove 5 Minute 4a](https://github.com/slowtorta/turtlewow-bug-tracker/assets/87241085/e7a430df-30c2-4897-89e1-dc7b08cd0259)

**Steps to reproduce the behavior with as much detail as possible:**

1. Enter Crescent Grove and fight your way to the vilethorn region to the junction where you can choose the routes to either the satyrs, the burning legion or the undead
2. Fight the group of three roaming felguards and the group of two roaming felguards shown on the screenshot
3. Observe as they respawn in a very short interval possibly even shorter than five minutes

**IDs of affected creatures, items, quests or spells with a link to the relevant page:**

NPC: https://database.turtle-wow.org/?npc=92120

**Expected behavior. Describe how it should work:**
The regular respawn interval for npc enemies within dungeon instances appears to be two hours. I believe that the roaming felguards highlighted on the screenshots should adhere to this regular dungeon instance respawn interval of two hours.

**Comment by AyleeJenn** [comment]
Found another roaming Felguard with the wrong respawn timer. It is located near the undead moonpriestess A'lathea on the left side near a skeletal remains when you approach and on the right side when you leave. Screenshot following.

![roaming felguard near priestess](https://github.com/slowtorta/turtlewow-bug-tracker/assets/87241085/d636d2b5-2db2-4e79-9d5f-cf03e8a951e0)

**Comment by twowTurtReynolds** [comment]
This week we put out an update that bulk updates . Please let us know if this persists.
