### ISSUE TITLE
Bug:  I Completed the Calling/Dearest Natalia Quest chain and i didn't got my reward.

### ISSUE THREAD

**Issue by Bittermens** [slowtorta/turtlewow-bug-tracker#4029]
**Please, provide a clear description what the bug is:**
I Completed Armaments of War(Plate)/The Calling/Dearest Natalia quest Chain a some time ago and i didn't got the Rewards.
Now the GM's stated that my character didn't complete said quest chain when i did and the NPC's doesn't have them

I even got in contact with 2 gm's who pointed me to post here about this issue, i don't know what to do anymore.

**Steps to reproduce the behavior with as much detail as possible:**

1. I did the entire quest chain
2. I delivered the last part
3. I didn't got the rewards because of players overloading the NPC and causing it to go into cutscene mode, thus impossible to interact.

**IDs of affected creatures, items, quests or spells with a link to the relevant page:**

NPC: https://database.turtle-wow.org/?npc=15183
Item: https://database.turtle-wow.org/?item=20699
Quest: https://database.turtle-wow.org/?quest=8316
Spell: https://database.turtle-wow.org/?spell=
Object: https://database.turtle-wow.org/?object=

**Expected behavior. Describe how it should work:**
I should had got both my gold and NR plate legs, but due to people overloading the NPC to deliver the quest didn't got it due to its cutscene behavior, and now the server database claims that i didn't do the quest, when i did and the NPC's doesn't even have the quest anymore.

**Comment by twowTurtReynolds** [comment]
![image](https://github.com/slowtorta/turtlewow-bug-tracker/assets/151180101/61ec9f1b-620a-45c5-a344-bae831da3d63)
Seems to work fine...
