### ISSUE TITLE
Undead male cry emote bugged

### ISSUE THREAD

**Issue by gh-borz** [slowtorta/turtlewow-bug-tracker#403]
**Please, provide a clear description what the bug is:**

the /cry emote for undead male appears bugged.  At the start during the animation, it cycles a glitched sound, and then when the physical animation ends, only then does the crying sound start.

**Steps to reproduce the behavior with as much detail as possible:**

1. Create an undead male
2. Type “/cry”

**IDs of affected creatures, items, quests or spells with a link to the relevant page:**

NPC: https://database.turtle-wow.org/?npc=
Item: https://database.turtle-wow.org/?item=
Quest: https://database.turtle-wow.org/?quest=
Spell: https://database.turtle-wow.org/?spell=
Object: https://database.turtle-wow.org/?object=

**Expected behavior. Describe how it should work:**

when you type /cry you should hear the crying sound plus an accompanying physical animation on your character at the same time.

**Comment by slowtorta** [comment]
Included in https://github.com/slowtorta/turtlewow-bug-tracker/issues/449
