### ISSUE TITLE
Small seaforium charge unable to target and blow up a chest in The Stockades?

### ISSUE THREAD

**Issue by Dalzedur** [slowtorta/turtlewow-bug-tracker#4030]
**Please, provide a clear description what the bug is:**
Small seaforium charge unable target and thus blow open a locked chest's lock in The Stockades.

**Steps to reproduce the behavior with as much detail as possible:**

1. Encounter a locked chest, have a small seaforium charge
2. Right click on the charge, move your mouse pointer over the chest to be unlocked
3. ...and you can't actually target the chest with it.

**IDs of affected creatures, items, quests or spells with a link to the relevant page:**

Item: https://database.turtle-wow.org/?item=4367
Spell: https://database.turtle-wow.org/?spell=4056
Object: Can't remember the exact name of the chest in question, but one that can be opened by a silver skeleton key, afaik. 

**Expected behavior. Describe how it should work:**
From how I remember them to work, maybe added in a later patch/expansion, seaforium charges could 100% be able to open locked chests and lockboxes in an inventory or in trade window, provided that the item was strong enough, not only doors. Now - at least in this case - the targeting cursor will stay greyed out when trying to target a locked chest. It won't even let you click on it to receive a message that the charge is not strong enough for that. Traded the charge to another player with engineering - they have the same issue.

**Comment by TatkaS1** [comment]
![image](https://github.com/slowtorta/turtlewow-bug-tracker/assets/87695943/d5c36c37-b46d-4c90-8ef5-4a4dc4af0061)

**Comment by Dalzedur** [comment]
Ok, did some digging and apparently the charges were made to work on chests in patch 2.10, which was after TBC was launched, so they did work - just not yet in vanilla.
