### ISSUE TITLE
deadwood avengers, and other deadwood melee mobs

### ISSUE THREAD

**Issue by dragonice246246** [slowtorta/turtlewow-bug-tracker#4036]
**Please, provide a clear description what the bug is:**
ive been pulling the deadwood mobs for the timbermaw rep grind and if im not im mellee range they go avade, reset health bar and cant be hit until i walk into range they can hit me without spells.  its like a 80% chance they dont come at me and go evade

**Steps to reproduce the behavior with as much detail as possible:**

1.use a spell caster and attack a mob.
2. dont go into melee range of them
3.  if their a spellcaster use an interrupt and it doesnt happen all the time just most of the time

**IDs of affected creatures, items, quests or spells with a link to the relevant page:**

NPC: https://database.turtle-wow.org/?npc=deadwood_avenger
Item: https://database.turtle-wow.org/?item=
Quest: https://database.turtle-wow.org/?quest=
Spell: https://database.turtle-wow.org/?spell=frostbolt
Object: https://database.turtle-wow.org/?object=

**Expected behavior. Describe how it should work:**
well im hitting them with frostbolt so they should be slowly walking towards me.

**Comment by nickgreyden** [comment]
Already being worked on via https://github.com/slowtorta/turtlewow-bug-tracker/issues/3051
