### ISSUE TITLE
Bugged mask(s) on Goblins

### ISSUE THREAD

**Issue by PopovavCz** [slowtorta/turtlewow-bug-tracker#404]
I met a Goblin in OG, he had a missing texture on his head, after inspecting I found out that his headpiece was "Flimsy Male Human Mask"

**Steps to reproduce the behavior with as much detail as possible:**

1. Have a Goblin
2. Equip "Flimsy Male Human Mask" (possibly any other)
3. profit

![unknown](https://user-images.githubusercontent.com/93488803/139596815-54ccb3cc-dbbc-4269-9e0a-f87a7c6f4aba.png)

**Expected behavior. Describe how it should work:**
Flimsy Male Human Mask should be displayed instead of a missing texture cube

**Comment by slowtorta** [comment]
Included in https://github.com/slowtorta/turtlewow-bug-tracker/issues/449
