### ISSUE TITLE
https://github.com/slowtorta/turtlewow-bug-tracker

### ISSUE THREAD

**Issue by dh-orko** [slowtorta/turtlewow-bug-tracker#4040]
**Please, provide a clear description what the bug is:**

**Steps to reproduce the behavior with as much detail as possible:**

1.
2. 
3. 

**IDs of affected creatures, items, quests or spells with a link to the relevant page:**

NPC: https://database.turtle-wow.org/?npc=
Item: https://database.turtle-wow.org/?item=
Quest: https://database.turtle-wow.org/?quest=
Spell: https://database.turtle-wow.org/?spell=
Object: https://database.turtle-wow.org/?object=

**Expected behavior. Describe how it should work:**

**Comment by konungr10** [comment]
Cannot use Invocation of Greater Protection (2% dodge helm/leg enchant) 
https://database.turtle-wow.org/?search=invocation+of+greater+protection
Item highlights when right clicked, but when one clicks on the helm or legs to apply the buff, it does nothing.  WDB folder has been emptied to no avail.  Not sure if it makes a difference, but the helm I tried to enchant currently has a 1% attack speed enchant on it.
