### ISSUE TITLE
In-game cap of unique mail recipients for alts on same account?

### ISSUE THREAD

**Issue by blehz-be** [slowtorta/turtlewow-bug-tracker#4041]
I get the message "You have reached the in-game cap of unique mail recipients" when trying to send mail to a character. This is going on for almost, or more than, a month now. It's just one of my alts, all the others I can mail to. So is this cap set at 6 or something (I have 8 chars)?
I understand from the Discord Support channel that there's some kind of limitation to prevent gold/RMT sellers to send mails to many characters? But isn't there a way to check if you're sending a mail to your own character, on the same account?

1. Send mails to multiple bank alts
2. More than 6?

Actual:
Can't send mails to all bank alts or characters on the same account. An error is shown "You have reached the in-game cap of unique mail recipients".

Expected:
Can send mails to all bank alts or characters on the same account. Or loosen the maximum number of unique characters you can send a mails.

**Comment by twowTurtReynolds** [comment]
This is a misleading text, usually another issue like the destination mailbox being full is the cause.
