### ISSUE TITLE
Attack power inconsistency on wand's damage scaling

### ISSUE THREAD

**Issue by Szalor** [slowtorta/turtlewow-bug-tracker#4043]
**Please, provide a clear description what the bug is:**
Attack Power and Ranged Attack Power so far do not seem to scale wand damage at all. 
However, for some reason, the Rallying Cry of the Dragonslayer buff scales wand damage by what looks like exactly +140 attack power would buff them.
My point of comparison is the priest's Inner Fire buff, which grants Attack Power that does NOT buff wand's damage at all.

**Steps to reproduce the behavior with as much detail as possible:**

0. Disregard critical strikes for all the upcoming tests, only consider regular non critical damage. On a priest, have a wand equipped and any rank of Inner Fire(results are much easier to see on a low damage low level wand because the difference in damage would be huge and VERY noticeable). 
1. Check the base damage of your wand in the stat sheet, as well as on a training dummy.
2. Buff yourself with Inner Fire, check that the wand's damage in the character sheet didn't change compared to test 1. Check the real damage on training dummies and acknowledge that the Attack Power buff from Inner Fire indeed did NOT change the wand's damage at all compared to the damage of the test 1.
3. Remove the Inner Fire buff. Get the Rallying Cry of the Dragonslayer buff. Check in the character sheet that the wand's damage has been increased when compared to tests 1 and 2. Check that the wand's damage has been increased on a target dummy when compared to tests 1 and 2.

**IDs of affected creatures, items, quests or spells with a link to the relevant page:**

Spell: https://database.turtle-wow.org/?spell=22888
Spell: https://database.turtle-wow.org/?spell=10952 (any other rank of Inner Fire would work, or alternatively, any other item or buff that gives Attack Power outside the Rallying Cry of the Dragonslayer buff).

**Expected behavior. Describe how it should work:**
So far, it looks like the Rallying Cry of the Dragonslayer's 140 Attack Power buff boosts wand's damage, while other regular Attack Power or Ranged Attack Power do not buff wand's damage at all. For the sake of consistency, the attack power granted by the Rallying Cry of the Dragonslayer should either not buff wand's damage, or all the other sources of Attack Power and Ranged Attack Power should buff wand's damage. 
If i were to suggest one of the 2 outcomes, i'd rather all sources of Ranged Attack Power (including but not limited to the Ranged Attack Power granted by the agility stat) and regular Attack Power actually buff all wand's damage, that way this stat would have at least some (if limited) use to casters and could be played around with some more exotic / hybrid itemization choices (after all, the Inner Fire's extra Attack Power was kind of supposed to lean that way already).

**Comment by ConcernedTurtler** [comment]
wands getting bonuses from attack power/agility/melee hit is really weird even if it is blizzlike. would make more sense if they got a small bonus from spellpower and benefitted from spell hit instead.

**Comment by twowTurtReynolds** [comment]
Vmangos:
![image](https://github.com/slowtorta/turtlewow-bug-tracker/assets/151180101/a16a49c5-5db1-4dc7-9001-c3fc1ebf129d)
![image](https://github.com/slowtorta/turtlewow-bug-tracker/assets/151180101/cff0d0cc-f93e-4938-891e-ab49873f9c28)

Turtle:
![image](https://github.com/slowtorta/turtlewow-bug-tracker/assets/151180101/5b164948-8777-45a7-a0a6-b86f3addb9ff)
![image](https://github.com/slowtorta/turtlewow-bug-tracker/assets/151180101/8c47e1f7-3cdc-45d1-b4ec-5c5de03ba2ea)

Looks like wand scaling is actually working more than intended on Turtle? These are both with Lesser Magic Wands.

This probably isn't worth the effort to nerf to match.
