### ISSUE TITLE
Azuresong Mageblade/Phantom Blade [Transmog Issue]

### ISSUE THREAD

**Issue by tognazzij** [slowtorta/turtlewow-bug-tracker#4046]
**Please, provide a clear description what the bug is:**

Azuresong Mageblade transmogged as Phantom Blade does not sheath on back.

**Steps to reproduce the behavior with as much detail as possible:**

1. Put Phantom Blade Transmog on Azuresong Mageblade as Gnome Mage

**IDs of affected creatures, items, quests or spells with a link to the relevant page:**

Item: https://database.turtle-wow.org/?item=7961
Item: https://database.turtle-wow.org/?item=17103

**Expected behavior. Describe how it should work:**

Phantom Blade sheaths on player's back, item transmogged to look like Phantom Blade should also sheath on player's back.

**Comment by Otari98** [comment]
As far as i know sheath determend by the original item (in this case azuresong).

**Comment by twowTurtReynolds** [comment]
The team is aware that mount points are determined by the source weapon and not the skin.
