### ISSUE TITLE
quest   "mirage raceway:gobin's team  bug

### ISSUE THREAD

**Issue by limaniit** [slowtorta/turtlewow-bug-tracker#4047]
This is a repetitive task but it has bugs.  I can’t complete it. It was normal yesterday. The racing car for the mission couldn’t appear, and the mission couldn’t be completed. 
Normally, after a 20-second countdown, a car will appear and start the race, and the Mission Control car will finish the race.  But now after the countdown of 20 seconds, the car disappeared directly, and the task could not be completed.

**Comment by Holymeats** [comment]
I am having this issue as well

**Comment by jameyboor** [comment]
Fixed on next update.
