### ISSUE TITLE
Alah'Thalas to Chillwind Camp to Southshore Underground Flying

### ISSUE THREAD

**Issue by 22sunseeker** [slowtorta/turtlewow-bug-tracker#4050]
**Please, provide a clear description what the bug is:**
After leaving on a gryphon from Alah'Thalas to Chillwind Camp (through the loading screen into Eastern Plaguelands and then to Chillwind, as normal), I then landed and then selected to fly to Southshore, which then kept going as it clipped me flying under the ground and in a straight line back to Alah'Thalas, which I did not select to do. After reaching Alah'Thalas, it then took me to Eastern Plaguelands Light's Hope Chapel, which at no point did I select to land at.

**Steps to reproduce the behavior with as much detail as possible:**

1. Take the portal from Stormwind to Alah'Thalas.
2. Visit the Alah'Thalas Gryphon Master, and then select Chillwind Camp.
3. Immediately after reaching Chillwind Camp, use the Gryphon Master services again and fly to Southshore, Hillsbrad.

**IDs of affected creatures, items, quests or spells with a link to the relevant page:**

NPC: https://database.turtle-wow.org/?npc=2432
NPC: https://database.turtle-wow.org/?npc=93100
NPC: https://database.turtle-wow.org/?npc=12617
NPC: https://database.turtle-wow.org/?npc=12596

**Expected behavior. Describe how it should work:**
After selecting to fly to Southshore from Chillwind Camp, I expected the gryphon to path and land me there.
![2](https://github.com/slowtorta/turtlewow-bug-tracker/assets/140914958/4965e6de-41aa-4cf6-a578-1bb223c31dd4)
![3](https://github.com/slowtorta/turtlewow-bug-tracker/assets/140914958/b28eb533-8e86-4126-bf09-3c07bbeeaa3f)
![4](https://github.com/slowtorta/turtlewow-bug-tracker/assets/140914958/a35d2c4e-f17f-40f7-8abc-c688bdd61a20)
![5](https://github.com/slowtorta/turtlewow-bug-tracker/assets/140914958/323f569f-0e33-49e7-8cb2-f0cf18ab11f0)
![1](https://github.com/slowtorta/turtlewow-bug-tracker/assets/140914958/c907b84e-7479-4719-aa07-ad85a0b1b159)

**Comment by 22sunseeker** [comment]
I was able to reproduce the bug by doing the steps mentioned above.

Again, I started in Stormwind and took the portal to Alah'Thalas, and then jumped down from the portal and took the flight path to Chillwind. When I got there, I immediately flew to Southshore, which again lead to the same issue.

Just posting this and these images here to confirm I reproduced it.

![WoW 2023-07-29 15-02-23](https://github.com/slowtorta/turtlewow-bug-tracker/assets/140914958/0124962b-6c38-45fa-bc6e-0c071aa3ef2e)
![WoW 2023-07-29 15-02-30](https://github.com/slowtorta/turtlewow-bug-tracker/assets/140914958/227e8c1f-7b57-49d2-b2d1-3bcd6e414697)
![WoW 2023-07-29 15-02-34](https://github.com/slowtorta/turtlewow-bug-tracker/assets/140914958/abef3eee-5a98-4b04-8ef0-cdcc37014af6)
![WoW 2023-07-29 15-02-44](https://github.com/slowtorta/turtlewow-bug-tracker/assets/140914958/e73d2b55-c779-40ca-b7aa-ad09a082f0a5)
![WoW 2023-07-29 15-02-54](https://github.com/slowtorta/turtlewow-bug-tracker/assets/140914958/b9b3599a-4041-4abc-8c6c-09e0fce78512)
![WoW 2023-07-29 14-59-54](https://github.com/slowtorta/turtlewow-bug-tracker/assets/140914958/bbab9e47-68ba-43d8-83de-9db4084bf9e9)
![WoW 2023-07-29 15-00-29](https://github.com/slowtorta/turtlewow-bug-tracker/assets/140914958/59c31408-9fc8-4a19-b500-94acaed7e848)
![WoW 2023-07-29 15-00-51](https://github.com/slowtorta/turtlewow-bug-tracker/assets/140914958/8c15a8cd-ff61-4170-afd8-9669b3732f87)
![WoW 2023-07-29 15-00-59](https://github.com/slowtorta/turtlewow-bug-tracker/assets/140914958/117908e7-49c9-4061-8000-81bf4deb1113)
![WoW 2023-07-29 15-01-21](https://github.com/slowtorta/turtlewow-bug-tracker/assets/140914958/35bf3819-3157-4d3a-b41d-89b01b697a56)
![WoW 2023-07-29 15-01-28](https://github.com/slowtorta/turtlewow-bug-tracker/assets/140914958/c41820f0-c442-44f8-8d3f-efd4918cff1c)
![WoW 2023-07-29 15-01-49](https://github.com/slowtorta/turtlewow-bug-tracker/assets/140914958/cef477e0-514e-49fe-a28f-9c71f4fc7fe7)
![WoW 2023-07-29 15-01-53](https://github.com/slowtorta/turtlewow-bug-tracker/assets/140914958/efb0860e-94cd-4019-91a2-388a0847e2d7)
![WoW 2023-07-29 15-02-07](https://github.com/slowtorta/turtlewow-bug-tracker/assets/140914958/c335cf09-2b28-49d2-b152-d387bc90a696)
![WoW 2023-07-29 15-02-08](https://github.com/slowtorta/turtlewow-bug-tracker/assets/140914958/182fc098-0da3-479c-8d91-cf7a1791aa1c)
![WoW 2023-07-29 15-02-10](https://github.com/slowtorta/turtlewow-bug-tracker/assets/140914958/05539c06-b8c4-4e82-9d45-b79e306e1360)

**Comment by slowtorta** [comment]
Fixed in 1.17.0
