### ISSUE TITLE
Red Flag over the Sea

### ISSUE THREAD

**Issue by MagpieEnjoyer** [slowtorta/turtlewow-bug-tracker#4051]
**Please, provide a clear description what the bug is:**

The quest "Red Flag over the Sea" is working incorrectly for anyone who already has built up Bloodsail reputation prior to completing it.

On my warlock (called Badelynn), I had 4901/6000 Friendly Bloodsail reputation from killing NPCs at Faldir's Cove while levelling, and I'd already done various Bloodsail quests prior to level 45. When I completed the Red Flag over the Sea quest, my reputation was SET to 0/3000 neutral, taking 7901 reputation away from me. 

**Steps to reproduce the behavior with as much detail as possible:**

1. Get greater than 0/3000 Bloodsail Buccaneers reputation on any character. 
2. Complete the "Red Flag over the Sea" quest. 
3. The character's Bloodsail Buccaneers reputation is now set to 0/3000.

**IDs of affected creatures, items, quests or spells with a link to the relevant page:**

NPC: https://database.turtle-wow.org/?npc=60453
Quest: https://database.turtle-wow.org/?quest=40172

**Expected behavior. Describe how it should work:**
For a starting reputation greater than 0/3000 neutral, the quest shouldn't affect the player's reputation at all, such that no Bloodsail Buccaneers reputation is lost. Or, even better, it should ADD 500 Bloodsail Buccaneers reputation to be in line with the other Bloodsail Buccaneers quests.

<img width="960" alt="bloodsail rep" src="https://github.com/slowtorta/turtlewow-bug-tracker/assets/103045707/d547fd0b-63dd-493b-8790-ff8992f78293">

**Comment by twowTurtReynolds** [comment]
![image](https://github.com/slowtorta/turtlewow-bug-tracker/assets/151180101/313b25a7-772c-499b-a088-9f00c83921e1)
Looks like this has been fixed. I am sorry you were hit by this bug.
