### ISSUE TITLE
Finkle's Skinner Cannot be used for peeling

### ISSUE THREAD

**Issue by 6556004** [slowtorta/turtlewow-bug-tracker#4052]
**Please, provide a clear description what the bug is:**
Finkle's Skinner
Binds when picked up
Main Hand	Dagger
37 - 70 Damage	Speed 1.30
(41.2 damage per second)
Durability 65 / 65
Requires Level 58
Equip: Skinning +10.
Equip: +45 Attack Power when fighting Beasts.

Cannot be used for peeling
Cannot be used for peeling
Cannot be used for peeling

**Steps to reproduce the behavior with as much detail as possible:**

1.
2. 
3. 

**IDs of affected creatures, items, quests or spells with a link to the relevant page:**

Item: https://database.turtle-wow.org/?item=12709

**Expected behavior. Describe how it should work:**

inkle's Skinner
Binds when picked up
Main Hand	Dagger
37 - 70 Damage	Speed 1.30
(41.2 damage per second)
Durability 65 / 65
Requires Level 58
Equip: [Skinning +10.](https://database.turtle-wow.org/?spell=16718)
Equip: [+45 Attack Power when fighting Beasts.](https://database.turtle-wow.org/?spell=18067)

**Comment by ratkosrb** [comment]
This is not a bug. Vanilla does not support the TBC functionality where an item can be a substitute for a different reagent. Like how you can't have higher level enchanting rods be used for recipes that require a different item. The client does not support this feature.
