### ISSUE TITLE
Unable to equip Blackwater Cutlass to offhand slot

### ISSUE THREAD

**Issue by BatuKhan** [slowtorta/turtlewow-bug-tracker#4053]
**Please, provide a clear description what the bug is:**
I bought Blackwater Cutlass off the AH. It is labelled as a One-Hander. I have proficiency with one-handed swords. When I try to equip the Cutlass in the offhand slot, it says I can't equip it. I can equip it as a mainhand sword though.

**Steps to reproduce the behavior with as much detail as possible:**

1. Drag sword from inventory to paper doll, or click offhand, click sword, click offhand again.
2. Character says "I can't equip that" and red text "This item cannot be equipped." comes up. 

**IDs of affected creatures, items, quests or spells with a link to the relevant page:**

Item: https://database.turtle-wow.org/?item=1951

**Expected behavior. Describe how it should work:**

Drag sword from inventory to paper doll, it equips to offhand slot.

**Comment by Kwall29** [comment]
I know this silly but do you have dual wield? Rogues learn it at 10 hunters at level 20 not sure about other classes.

**Comment by twowTurtReynolds** [comment]
@Kwall29 You are not silly, I think you have correctly identified his issue.

![image](https://github.com/slowtorta/turtlewow-bug-tracker/assets/151180101/bc2507e7-40ce-473e-a5df-8393588b971b)

It works fine.
