### ISSUE TITLE
Way too many Baxxils

### ISSUE THREAD

**Issue by BatuKhan** [slowtorta/turtlewow-bug-tracker#4055]
**Please, provide a clear description what the bug is:**
There are tens of Baxxils at Farwatch Post. Baxxil will still follow you as intended when you defeat him, but he only exists in Barrens. If you cross the Durotar river you rezone, and he disappears. However, it is still possible to return to Hizzle and complete the quest.

**Steps to reproduce the behavior with as much detail as possible:**

1. Accept WANTED: Hole Escapee from Sparkwater Port wanted poster.
2. Go to Farwatch Post.
3. See way too many Baxxils
4. Cross the Durotar river and he zones out.

![image](https://github.com/slowtorta/turtlewow-bug-tracker/assets/5974112/16aad044-9100-4c1c-b645-b78c8fca4f39)

**IDs of affected creatures, items, quests or spells with a link to the relevant page:**

NPC: https://database.turtle-wow.org/?npc=91297
Quest: https://database.turtle-wow.org/?quest=55048

**Expected behavior. Describe how it should work:**
I would assume there should only be one Baxxil, and you should still have him in tow when you cross to Durotar.

**Comment by AKryukov92** [comment]
There were patchnote as of 1 august https://forum.turtle-wow.org/viewtopic.php?t=8619 but it seems it didn't help. Baxxils are still there in multiple numbers.
![image](https://github.com/slowtorta/turtlewow-bug-tracker/assets/24266616/d52715e1-3a7e-4722-bda9-a8d94ada595c)
