### ISSUE TITLE
Enchant Gloves - Minor Haste Only gives physical haste

### ISSUE THREAD

**Issue by Rowrow213** [slowtorta/turtlewow-bug-tracker#4056]
**Please, provide a clear description what the bug is:**
Enchant Gloves - Minor Haste only gives 1% attack speed despite promising 1% casting speed on the tooltip
![image](https://github.com/slowtorta/turtlewow-bug-tracker/assets/136415778/242a86f2-aab5-44a8-9530-8b7baf1175fa)

**Steps to reproduce the behavior with as much detail as possible:**

1. Enchant Gloves with Minor Haste enchant
2. Look at the enchanted gloves and see if you are reciving casting speed
3. 

**IDs of affected creatures, items, quests or spells with a link to the relevant page:**

NPC: https://database.turtle-wow.org/?npc=
Item: https://database.turtle-wow.org/?item=
Quest: https://database.turtle-wow.org/?quest=
Spell: https://database.turtle-wow.org/?spell=
Object: https://database.turtle-wow.org/?object=
https://database.turtle-wow.org/?spell=13948
**Expected behavior. Describe how it should work:**
It should give the casting speed as well

**Comment by balakethelock** [comment]
Look at your spell tooltips and see if they're reduced by 1%

**Comment by Rowrow213** [comment]
> Look at your spell tooltips and see if their casting speed is reduced when you wear the gloves.

**Comment by Rowrow213** [comment]
It didn't
