### ISSUE TITLE
Kargath Zeppelin Phasing Issue

### ISSUE THREAD

**Issue by Nimawei** [slowtorta/turtlewow-bug-tracker#4058]
**Please, provide a clear description what the bug is:**
The zeppelin that leads to Kargath from the tower in Durotar is phasing out of the world as soon as lands in front of the Durotar tower (the moment it stops moving). So in order to land on it, you have to jump on it while it's still moving. You will then notice how you're phasing out and everyone on the zeppelin tower will now be gone, and you will be only able to see the players who are also on the zeppelin. If you're on the zeppelin tower, you will see how the zeppelin just disappears from existence until you see it arriving again.

**Steps to reproduce the behavior with as much detail as possible:**

1. Go to zeppelin tower to the west of Orgrimmar's entrance.
2. See zeppelin arriving from Kargath to Durotar.
3. You can either jump on the zeppelin while it's still in motion or witness it disappear when it stops moving.

**IDs of affected creatures, items, quests or spells with a link to the relevant page:**

https://database.turtle-wow.org/?object=190552

**Expected behavior. Describe how it should work:**
Zeppelin should not be phasing out - players are forced to hop on it while it's still in motion or have to wait for the next zeppelin to arrive.

**Comment by cesar-pix** [comment]
Please fix it!

**Comment by cesar-pix** [comment]
It's fixed, change the status on this one please
