### ISSUE TITLE
Eremzion  does not  teleport you inside the Caverns of Time.

### ISSUE THREAD

**Issue by Tinyfin-github** [slowtorta/turtlewow-bug-tracker#406]
Eremzion  does not  teleport you inside the Caverns of Time.

https://database.turtle-wow.org/?npc=65000 Eremzion

![image](https://user-images.githubusercontent.com/83077166/140081294-eb7f8c34-c774-48c0-883a-5777a2e9032e.png)

**Comment by slowtorta** [comment]
He should not before 1.15.2!
