### ISSUE TITLE
In Dreams Questline bugged after failed escort

### ISSUE THREAD

**Issue by DieTrommel** [slowtorta/turtlewow-bug-tracker#4065]
**Please, provide a clear description what the bug is:**
I was doing the last part of the Questline for "In Dreams". I did fail the escort and the quest status was "failed". Usually you can abandon and re-do the quest. However after abandoning, I could not take any quests from any related NPCs. A GM reset the Quest "In Dreams" and the result was that I could talk to neither Highlord Taelan Fordring or Tirion Fordring. The disguise from Myranda the Hag always worked at all stages. Antoher try of a GM was to reset the whole questline, starting again with Blood Tinged Skies, Carrion Grubbage and Demon Dogs. However, I could not take these quests from Tirion. They did appear on my minimap via the questy add-on. Then we tried to activate In Dreams again, to no avail. We also put Tirions Gift in my Inventory. But again I couldn't talk to Highlord Taelan Fordring, even with In Dreams active and the Quest Item in my inventory. 

My Charactername is Jesux, by the way. 

**Steps to reproduce the behavior with as much detail as possible:**

1. GM clears quest
2. GM starts quest In Dreams or Blood Tinged Skies, Carrion Grubbage and Demon Dogs.
3. Not able to talk to either Hightlord Taelan for In Dreams or Tirion for the three quests. 

**IDs of affected creatures, items, quests or spells with a link to the relevant page:**

NPC: [Highlord Taelan Fordring Display ID: 10341](https://database.turtle-wow.org/?npc=1842)
[Tirion Fordring Display ID: 9477](https://database.turtle-wow.org/?npc=1855)
Item: https://database.turtle-wow.org/?item=14872
Quest: https://database.turtle-wow.org/?quest=5944

**Expected behavior. Describe how it should work:**
I should be able to start "In Dreams" again, talking to Highlord Taelan. 
Alternatively starting the whole questline would be acceptable. 

If that is in any case possible when the quest is severly bugged, is it possible to close down the quest for me and add https://database.turtle-wow.org/?item=16058 to my inventory?

**Comment by DieTrommel** [comment]
Has this been seen? 

best reagards! :-)

**Comment by twowTurtReynolds** [comment]
![image](https://github.com/slowtorta/turtlewow-bug-tracker/assets/151180101/d901d729-8f05-455f-a42a-36531ff4bd12)
![image](https://github.com/slowtorta/turtlewow-bug-tracker/assets/151180101/293b9c7d-568d-4366-a9d4-cceccebc6bc8)
Abandonded, then it works fine:
![image](https://github.com/slowtorta/turtlewow-bug-tracker/assets/151180101/56233742-b1fa-4d61-b59f-ba4d87ebe068)
