### ISSUE TITLE
Commander Ashlam Valorfist

### ISSUE THREAD

**Issue by StandInTheRiver** [slowtorta/turtlewow-bug-tracker#4068]
**Please, provide a clear description what the bug is:**
Commander Ashlam Valorfist in the western plaguelands doesn't give me any quests even though I am the appropriate level and his quests have no pre-requisites
**Steps to reproduce the behavior with as much detail as possible:**

1. be level 58
2. Speak to commander ashlam valorfist
3. No quests available

**IDs of affected creatures, items, quests or spells with a link to the relevant page:**

NPC: https://database.turtle-wow.org/?npc=
Item: https://database.turtle-wow.org/?item=
Quest: https://database.turtle-wow.org/?quest=
Spell: https://database.turtle-wow.org/?spell=
Object: https://database.turtle-wow.org/?object=

**Expected behavior. Describe how it should work:**
Should give me quest https://www.wowhead.com/classic/quest=5215/the-scourge-cauldrons

**Comment by twowTurtReynolds** [comment]
https://www.wowhead.com/classic/quest=5215/the-scourge-cauldrons#comments:id=2741656:reply=1180386
