### ISSUE TITLE
Hunter trap Line of Sight

### ISSUE THREAD

**Issue by dole555** [slowtorta/turtlewow-bug-tracker#407]
**Please, provide a clear description what the bug is:**
When a mob steps on a hunter trap and is not in line of sight with the hunter, the trap fails.

**Steps to reproduce the behavior with as much detail as possible:**

1. Place Frost / Freezing / Immolate / Explosive trap.
2. Be out of sight of the trap when a mob steps on the trap.
3. See in combat log "You fail to cast Frost Trap Aura: Target not in line of sight"

**IDs of affected creatures, items, quests or spells with a link to the relevant page:**

NPC: https://database.turtle-wow.org/?npc=
Item: https://database.turtle-wow.org/?item=
Quest: https://database.turtle-wow.org/?quest=
Spell: https://database.turtle-wow.org/?spell=
Object: https://database.turtle-wow.org/?object=

**Expected behavior. Describe how it should work:**
The trap should work regardless of if it is in sight of the hunter or not.

**Comment by jameyboor** [comment]
![afbeelding](https://user-images.githubusercontent.com/1365563/140166024-fb6fa643-de9d-4866-9b19-e9f0794a728c.png)
I've tried to reproduce this but haven't been able to. Do you have a location for me to work with?

**Comment by dole555** [comment]
Hi,

It seems to only fail with the AoE traps (Frost trap and Explosive trap). The Freezing trap and immolation trap work if out of LoS.
I also have the Entrapment and Clever Traps talents. I haven't tested without them.

![WoWScrnShot_110421_100303](https://user-images.githubusercontent.com/80955822/140279324-dd381517-9931-4950-be48-1359c7dd6133.jpg)
![WoWScrnShot_110421_100308](https://user-images.githubusercontent.com/80955822/140279327-44a0273b-9b22-4138-947e-f8441b39e1bd.jpg)

**Comment by jameyboor** [comment]
This is fixed in the next update.
