### ISSUE TITLE
Can't get Cooldown of Nature's Grasp(Druid telant spell)

### ISSUE THREAD

**Issue by leenux** [slowtorta/turtlewow-bug-tracker#4079]
**Please, provide a clear description what the bug is:**
Can't get Cooldown of Nature's Grasp(Druid telant spell)

**Steps to reproduce the behavior with as much detail as possible:**

1.Env:Roid-macros
2. `/cast [nocooldown:Nature's_Grasp]Nature's Grasp` no effect

**IDs of affected creatures, items, quests or spells with a link to the relevant page:**

Spell: https://database.turtle-wow.org/?spell=16689

**Expected behavior. Describe how it should work:**
Expected:`/cast [nocooldown:Nature's_Grasp]Nature's Grasp` will work fine

**Comment by leenux** [comment]
btw:env in roid-macros, `/cast [nomybuff:Nature's_Grasp]Nature's Grasp` work fine

**Comment by balakethelock** [comment]
Are you sure this is how it's supposed to work in the first place? The spellid of war stomp isn't even 45. It's 20549. So it's illogical that the command would return war stomp cd for you correctly.

**Comment by leenux** [comment]
> 

You are right,`/run local start, duration, enabled = GetSpellCooldown(20549,"spell") print("dur=".. duration)` same work no effect

**Comment by Meridaw** [comment]
you need to use the spells number in the spellbook. you can check what the spell number for War stomp is by using this macro `/run for id = 1, 180, 1 do local spellName, subSpellName = GetSpellName(id, SpellBookFrame.bookType);if spellName and string.find(spellName, "War Stomp", 1, true) then ChatFrame1:AddMessage("ID is "..id, 1.0, 1.0, 0.5); end; end;`
also `print` is not a function in turtle client. but if you use pfui or shagutweaks then those addons will add the function.
