### ISSUE TITLE
Winterspring furblog: Bead drop

### ISSUE THREAD

**Issue by hazlema** [slowtorta/turtlewow-bug-tracker#408]
**Please, provide a clear description what the bug is:**

Killed a few days of play time winterspring furblogs (probably well over 100) have never had a bead drop.  I can get the feathers from the felwood furblogs. 

**Steps to reproduce the behavior with as much detail as possible:**

1. Kill Furblogs in Winterspring
2. 
3. 

**IDs of affected creatures, items, quests or spells with a link to the relevant page:**

NPC: https://database.turtle-wow.org/?npc=11556
Item: https://database.turtle-wow.org/?item=
Quest: https://database.turtle-wow.org/?quest=8469
Spell: https://database.turtle-wow.org/?spell=
Object: https://database.turtle-wow.org/?object=21383

**Expected behavior. Describe how it should work:**

When you kill Furblogs you sometimes get a bead to drop

**Comment by slowtorta** [comment]
Beads have a condition for drop: players must have this quest completed and rewarded: https://database.turtle-wow.org/?quest=8464. I just tested and and it's workign as intended :) What I can do is two link those 2 quests in chain, so nobody gets confused about drops.
