### ISSUE TITLE
Aggressive pets don't always attack the closest available target

### ISSUE THREAD

**Issue by patrycos** [slowtorta/turtlewow-bug-tracker#4085]
**Please, provide a clear description what the bug is:**

Hunter pets with Aggressive setting enabled don't always attack the closest available target while there are multiple potential targets within their aggro radius.

**Steps to reproduce the behavior with as much detail as possible:**

1. Tame any pet, ideally much higher level than the targets' so its aggro radius is large
2. Click the Aggressive button on pet's cast bar
3. Have multiple hostile targets near your pet
4. Pet will often ignore the closest enemy and attack another target

**IDs of affected creatures, items, quests or spells with a link to the relevant page:**

**Expected behavior. Describe how it should work:**

Aggressive pets should always go for the closest target.

**Comment by ratkosrb** [comment]
They do not search for the furthest away target. They attack whatever unit first moves inside their aggro radius while aggressive.
