### ISSUE TITLE
inconsistent attackpeed encahnt tooltip

### ISSUE THREAD

**Issue by geojak** [slowtorta/turtlewow-bug-tracker#4088]
**Please, provide a clear description what the bug is:**

the glovves enchant has finally been fixed to also affect casting speed, which is reflected in the echanting progffesion tooltip.
the helm and leg attackspeed libram do not affect the casting speed
on the itmes themselfes its not differentiate.

![image](https://github.com/slowtorta/turtlewow-bug-tracker/assets/25199983/eada2eb3-39c9-466a-b4c5-aa6258e6d2e5)
this affects casting speed

![image](https://github.com/slowtorta/turtlewow-bug-tracker/assets/25199983/53233dd1-a07c-4fe0-b099-fe737c84b849)
this doesnt

**Expected behavior. Describe how it should work:**

tooltip on gloves changed from attackspeed to haste
helm and pants libram also changed from attackspeed to haste and affecting cast

**Comment by twowTurtReynolds** [comment]
With head:
![image](https://github.com/slowtorta/turtlewow-bug-tracker/assets/151180101/92d83d62-9810-4536-bdfa-3871de5e0282)
With gloves and head:
![image](https://github.com/slowtorta/turtlewow-bug-tracker/assets/151180101/7d79ee07-7908-4fc0-a82b-e078a3f5cef8)
Looks like this was fixed.
