### ISSUE TITLE
Roetten Stonehammer dialog text

### ISSUE THREAD

**Issue by domne21** [slowtorta/turtlewow-bug-tracker#409]
The NPC Roetten Stonehammer in Ironforge - Hall of Explorers ( https://database.turtle-wow.org/?npc=5637 ) has the dialog text "My wind riders are trained to flu quickly through the hot Barrens air."

![image](https://user-images.githubusercontent.com/43964249/140466483-8c2b2c93-e8e9-4e83-9b71-426a98195504.png)

**Comment by slowtorta** [comment]
Thank you. This will be fixed on the the next server update.
