### ISSUE TITLE
Mirage Raceway Tutorial Quests aren't working at all!

### ISSUE THREAD

**Issue by Ilyanov96** [slowtorta/turtlewow-bug-tracker#4090]
**Please, provide a clear description what the bug is:**
The bug is related to Mirage Raceway World Event. The event starts with the tutorial race. You have to pick up the quest from gnome or goblin garage. Then you should go to Dolores to register for the test race. After speaking with Dolores she starts the countdown. It goes as a raid warning from 10 to 0. At 0 rw says "Go! Go! Go!" and nothing happens. You simply keep standing near Dolores, you don't get into car and explosive sheeps that appeared earlier for literally 1-2 sec disappears.

I tried it to complete the quest in different ways: mounted, dismounted, pvp-flagged. Nothing helped sadly

**Steps to reproduce the behavior with as much detail as possible:**

1. Go to the Mirage Raceway in Shimmering Flats in Thousand Needles
2a. Accept the quest "Goblin Engineering At Its Finest" (https://database.turtle-wow.org/?quest=50310) from Jizzle Grikbot
or
2b. Accept the quest "Gnomes Are Genuine Inventors" (https://database.turtle-wow.org/?quest=50312) from Gregor Fizzwuzz
3. Go to Dolores (https://database.turtle-wow.org/?npc=50533) and speak with here. There will be dialogue option to test drive for one (or both) teams. Dismount and then click this option.
4. Dolores will count from 10 to 0 (as a raid warning) and afterwards nothing will happen (you won't get into the car or smth).

**IDs of affected creatures, items, quests or spells with a link to the relevant page:**

Quests:
Gnome team quest - https://database.turtle-wow.org/?quest=50312
Goblin team quest - https://database.turtle-wow.org/?quest=50310

NPC:
Dolores - https://database.turtle-wow.org/?npc=50533

**Expected behavior. Describe how it should work:**
As far as i know, after speaking with Dolores you should get into the car and be able to race.

**Notes:**
The bug is related to single tutorial race which is some kind of attunement to normal single and duo race. So with this bug you kinda stuck and can't progress further in the World Event.

**Comment by Holymeats** [comment]
This has been bugged for weeks. Would really appreciate the developers to fix it

**Comment by jameyboor** [comment]
Fixed on next update.
