### ISSUE TITLE
(Warrior) Furen's Notes Quests have lost their race restrictions

### ISSUE THREAD

**Issue by Zokan31** [slowtorta/turtlewow-bug-tracker#4092]
**Please, provide a clear description what the bug is: 
After completing the quest "Firehardened Mail" given by Furen Longbeard, he gives you three new quests. 

"Grimand Elmore; 1700", "Klockmort Spannerspan; 1704" and "Mathiel; 1703". 
Each of these quests require "Furen's Notes; 6926" to be delivered to these NPC's. 

The bug is that Furen only gives you one "Furen's Notes". You can't complete the quest this way. You have to make your way to each individual quest NPC, deliver "Furen's Notes" and then go back to Furen, and start the next one to get "Furen's Notes" again. Then make your journey to the next quest and repeat once more to get all three quests; 1700, 1704 and 1703 completed. 

Furen should give you three notes or "Furen's Notes" should not be taken from you by each individual NPC's you visit in these three quests. 

**Steps to reproduce the behavior with as much detail as possible:**

1. I tried deleting my WBD folder. This did not make a difference.
2.  I also tried abandoning one of the three quests and retaking it in order to get two "Furen's Notes" this didn't work either.
3.  The only way I was able to do this quest is to go back and forth 3 times to Furen cause he won't give me three "Furen's Notes". 

**IDs of affected creatures, items, quests or spells with a link to the relevant page:**

NPC: https://database.turtle-wow.org/?npc=5413
Item: https://database.turtle-wow.org/?item=6926
Quest: https://database.turtle-wow.org/?quest=1700, 1703, 1704
Spell: https://database.turtle-wow.org/?spell=
Object: https://database.turtle-wow.org/?object=

**Expected behavior. Describe how it should work: 
As mentioned, either the three quest NPC's should not take "Furen's Notes" from you or Furen should give you three "Furen's Notes" so it can be done in one go without having to play around with the quests or going back and forth three times from the same NPC.

**Comment by twowTurtReynolds** [comment]
![image](https://github.com/slowtorta/turtlewow-bug-tracker/assets/151180101/0dfdf96c-a246-431c-8f21-1f08a054888f)

Apparently these 3 are supposed to be race locked: https://www.wowhead.com/classic/quest=1703/mathiel#comments:id=2952010 That explains it. 

Perhaps in the addition of high elves, a dev added everyone to everything on accident.

**Comment by Muigin** [comment]
This was a deliberate decision as there is no practical reason for these to be race-locked, such as with the level 10 class quests which are race-specific.  We will remove Unique from the Furen's Notes items soon to better facilitate this.

Won't fix.
