### ISSUE TITLE
Paladin Cleanse doesnt removing Magic

### ISSUE THREAD

**Issue by marcelafgr** [slowtorta/turtlewow-bug-tracker#41]
By opening this Issue, I admit to having done the pertinent research using sources from Vanilla (preferably) or Classic. I also understand that sources from other private servers are not acceptable.

**Current behavior**: Paladin Cleanse is not removing Magic, as described in the skill, tried to remove different Magics at me and other people and it didnt worked

**Expected behavior**: 

**Proofs**: https://cdn.discordapp.com/attachments/273904958036901888/853859998399987732/magic1.png

**Steps to reproduce**:

1.  take any magic debuff (i tried the print one, and shadow word:pain)
2. try to remove with cleanse high level (the one that have removes poison, disease, and magic)
3.

**Comment by CosminPOP** [comment]
As your UI also say, Curse of Weakness is a curse.
Shadow Word: Pain was dispelled (or faded), that was a magic debuff.

**Comment by marcelafgr** [comment]
Uh okay that was a bad print, but I tried to use Cleanse when me or my friend were affected by shadow word:pain and it's says nothing to dispel message, so not sure it's working the removing magic

**Comment by Nolin7777** [comment]
Cannot reproduce
