### ISSUE TITLE
High Elf fishing bug

### ISSUE THREAD

**Issue by JustVityok** [slowtorta/turtlewow-bug-tracker#410]
When fishing, high elf model acts weird like on image
![WoWScrnShot_110521_114518](https://user-images.githubusercontent.com/93767462/140493301-20b78f54-ee60-42fe-b276-cd75f11ee499.jpg)

**Comment by slowtorta** [comment]
Included in https://github.com/slowtorta/turtlewow-bug-tracker/issues/449
