### ISSUE TITLE
Silver Sun Mine Environment/Character Issue

### ISSUE THREAD

**Issue by zesilo** [slowtorta/turtlewow-bug-tracker#4101]
**Please, provide a clear description what the bug is:**

**Steps to reproduce the behavior with as much detail as possible:**

1. Stand on high enough spot in specific coords in Silver Sun Mine
2. Jump forward
3. Start no clipping/flying above the cave

**IDs of affected creatures, items, quests or spells with a link to the relevant page:**

**Expected behavior. Describe how it should work:**
Should land on the ground and not fly.
![image_2023-08-06_172255873](https://github.com/slowtorta/turtlewow-bug-tracker/assets/106992411/6ed8370b-5df0-48bb-baea-9194ae0714c7)

**Comment by zesilo** [comment]
![image](https://github.com/slowtorta/turtlewow-bug-tracker/assets/106992411/b647c637-3f23-4f77-b0c6-a4ba51216274)

**Comment by twowTurtReynolds** [comment]
I don't even see the mine anymore in the revamped Thalassian Highlands :)
