### ISSUE TITLE
Scythe of the Harvest scaling with Spell Power

### ISSUE THREAD

**Issue by Blank3ts** [slowtorta/turtlewow-bug-tracker#4102]
**Please, provide a clear description what the bug is:**
Scythe of the Harvest is a custom weapon that Paladins are currently using in PvP to destroy people. The chance on hit effect reads "Steals 45 life from target enemy." but since this weapon scales with SP, holy paladins can use it for not only more burst, but more healing as well. Quite a time to be a holy paladin, if your holy shock / holy strike doesn't crit for 1-2k, just fish for a proc! Here's a screenshot of the proc life-stealing almost 1k health
https://media.discordapp.net/attachments/1038050060606394442/1137887621574557756/image.png?width=467&height=176
**Steps to reproduce the behavior with as much detail as possible:**

1. Obtain Scythe of the Harvest
2. Stack spell-power gear
3. Watch as the proc jumps from a mere 45 health, all the way to almost 1k

**IDs of affected creatures, items, quests or spells with a link to the relevant page:**

NPC: https://database.turtle-wow.org/?npc=
Item: https://database.turtle-wow.org/?item=
Quest: https://database.turtle-wow.org/?quest=
Spell: https://database.turtle-wow.org/?spell=
Object: https://database.turtle-wow.org/?object=

**Expected behavior. Describe how it should work:**
This is a custom item, I don't know whether it is supposed to scale with SP or not. That being said, in original vanilla, VERY few items scaled with SP for this very reason - its a bit difficult to balance.

**Comment by Zmitrok1984** [comment]
This is correct behaviours.
Furthermore added SP scaling for Ashbringer and Blood Drinker. 
See changelog from 14 June. https://forum.turtle-wow.org/viewtopic.php?t=7795

**Comment by ConcernedTurtler** [comment]
devs I beg you make some caster weapons with broken "on spellcast" procs please.

**Comment by TatkaS1** [comment]
Making items with 1:1 sp scaling sure is asking for trouble when overgeared players get their hands on them 💯

**Comment by twowTurtReynolds** [comment]
Rebalancing suggestions belong on the appropriate forum.
