### ISSUE TITLE
Ravenholdt Reputation Gain

### ISSUE THREAD

**Issue by Twili1** [slowtorta/turtlewow-bug-tracker#4103]
**Please, provide a clear description what the bug is:**
Killing syndicate mobs currently does not given reputation for the Ravenholdt faction.

**Steps to reproduce the behavior with as much detail as possible:**

1. Kill any syndicate npc (Hillsbrad, arathi, alterac etc.)
2.  No ravenholdt reputation gain
3. 

**IDs of affected creatures, items, quests or spells with a link to the relevant page:**
All of these mobs: https://database.turtle-wow.org/?search=syndicate#npcs

**Expected behavior. Describe how it should work:**
Killing Syndicate mobs should give 5 reputation towards Ravenholdt, according to classic wowhead - https://www.wowhead.com/classic/faction=349/ravenholdt
'Syndicate [humanoids](https://www.wowhead.com/classic/npcs=7&filter=na=syndicate;cr=3;crs=70;crv=0) give 5 reputation points per kill, though only through 11999/12000 Honored.'

**Comment by Twili1** [comment]
Worth noting that without this in the game, there is no way to reset your Ravenholdt reputation since you can't get back to neutral to talk to their npcs.

(Did syndicate rep for their mask and now can't reset)

**Comment by twowTurtReynolds** [comment]
Confirmed in https://github.com/slowtorta/turtlewow-bug-tracker/issues/5011 that this is blizzlike Vanilla behavior.

If you want the TBC behavior that you have mentioned, please open a Suggestions Forum post.
