### ISSUE TITLE
Manual Crowd Pummeler - 1 use emptied all 10 charges

### ISSUE THREAD

**Issue by Kote21** [slowtorta/turtlewow-bug-tracker#4104]
1. Get a MCP
2. Run UBRS and fight The Beast
3. Use the active ability of MCP for the first time in cat form
4. Have no charges left?

https://database.turtle-wow.org/?item=9449

Expected it to just use 1 charge, not all 10.

**Comment by twowTurtReynolds** [comment]
![image](https://github.com/slowtorta/turtlewow-bug-tracker/assets/151180101/4a8f247c-6097-49c7-88e6-2938bc927df7)
![image](https://github.com/slowtorta/turtlewow-bug-tracker/assets/151180101/be374a73-24cf-49b6-94ec-a734817a4df3)

I have no clue how that happened to you, I'm sorry.
