### ISSUE TITLE
Good god there's so many baxxils

### ISSUE THREAD

**Issue by Kharkov72** [slowtorta/turtlewow-bug-tracker#4109]
![Untitled](https://github.com/slowtorta/turtlewow-bug-tracker/assets/25846834/c4fe7980-39cd-4195-a334-8ca4feaf2bb1)
this is far watch post, its the quest where you escort this guy back to the goblin town in durotar right? There's so many of him holy shit.

**Comment by twowTurtReynolds** [comment]
Duplicate of https://github.com/slowtorta/turtlewow-bug-tracker/issues/4055
