### ISSUE TITLE
Incorrect/Missing Sound Effects for Magic Rooster

### ISSUE THREAD

**Issue by Damagedfate** [slowtorta/turtlewow-bug-tracker#411]
**Please, provide a clear description what the bug is:**

Swift Magic Rooster has incorrect or missing sound effects. 

**Steps to reproduce the behavior with as much detail as possible:**

1. Summoning - Sound effect for summoning Magic Rooster is from a Cat/Saber mount. 
2. Falling - Sound effect for falling is from a normal chicken companion/NPC.
3. Mountspecial - Missing sound effect when pressing the spacebar while mounted.

**IDs of affected creatures, items, quests or spells with a link to the relevant page:**

Item: https://database.turtle-wow.org/?item=80431

**Expected behavior. Describe how it should work:**

Magic Rooster should have its own unique sound effects, similar to retail WoW.

Thank you for time and all your effort in making the best possible World of Warcraft experience.

**Comment by mrrosh** [comment]
[Video showing the wrong sound playing when mounting up.](https://youtu.be/exPely2aHCI)

**Comment by slowtorta** [comment]
Included in https://github.com/slowtorta/turtlewow-bug-tracker/issues/449
