### ISSUE TITLE
Game doesn't register Mudsprocket GY

### ISSUE THREAD

**Issue by LachtanCesky** [slowtorta/turtlewow-bug-tracker#4110]
**Please, provide a clear description what the bug is:**
People don't get ressurected at Mudsprocket GY when they die around southern part of the Dustwallow Marsh. There is spirit healer at local gy, but no matter that, Horde person always get ressurected at Brackenwell Village.
**Steps to reproduce the behavior with as much detail as possible:**

1. Die anywhere around Wyrmbog, Stonemaul Ruins or Onyxia's Lair
2. Click "Release Spirit"

**IDs of affected creatures, items, quests or spells with a link to the relevant page:**
NPC: https://database.turtle-wow.org/?npc=6491

**Expected behavior. Describe how it should work:**
If you ressurect anywhere around southern part of Dustwallow Marsh (Wyrmbog, Stonemaul Ruins, Den of Flame, Onyxia's Lair) game should be able to register nearest GY as the one at Mudsprocket and make you respawn thereinstead of Brackenwell Village.

**Comment by twowTurtReynolds** [comment]
![image](https://github.com/slowtorta/turtlewow-bug-tracker/assets/151180101/ebd20068-fa27-4c26-ae78-407647e460d6)
Replicated. I am in eyeshot of the spirit healer yet it sent me to theramore, had to .tele back.
