### ISSUE TITLE
Daisy and Dolores from the shimmering flat race questlines completely bugged

### ISSUE THREAD

**Issue by Dualityz** [slowtorta/turtlewow-bug-tracker#4112]
**Please, provide a clear description what the bug is:** 
 
The Npc Daisy from the Shimmering Flats race questlines is not offering any quest or dialogue, despite having a "!" marker. She should have a dialogue option to start the race for either team. She currently offers none, only her base NPC chatter text. 

The Npc Dolores from the same questlines is offering the appropriate dialogue for each first quest ( the goblin one and the gnome one), you do get her whispers about the race starting soon but it never does and you're never given a car, be it Gnome or Goblin, making this quest not possible to complete. 
 It looks like the very mechanic used is broken. 
If given the chance to complete, you would still have to talk to Daisy afterwards to complete both quests "Mirage Raceway" ( goblin & gnome team ), which would not be possible as long as Daisy is broken.

**Steps to reproduce the behavior with as much detail as possible:**

1. Walk up to Daisy. She has a quest marker. She does not offer any dialogue option except her NPC chatter text.

2. Accept both the goblin and the gnome quest ( Gnomes Are Genuine Inventors and Goblin Engineering At Its Finest! ). 
Walk up to Dolores. She does offer both dialogue options ( test drive each team's racecar ). Click on either of those.
You get NPC whispers and a Raid Warning timer about the race, but you're never ported in either car and thus cannot complete this quest.

**IDs of affected creatures, items, quests or spells with a link to the relevant page:**

NPC: 
https://database.turtle-wow.org/?npc=4507 -Daisy
https://database.turtle-wow.org/?npc=50533 -Dolores
https://database.turtle-wow.org/?npc=50522 -Gregor Fizzwuzz ( Gnomes Are Genuine Inventors and Mirage Raceway: Gnome's Team )
https://database.turtle-wow.org/?npc=50521 -Jizzle Grikbot ( Goblin Engineering At Its Finest! and Mirage Raceway: Goblin's Team )

Quest: 
https://database.turtle-wow.org/?quest=50316 - "Race Against Time!" 
https://database.turtle-wow.org/?quest=50312 -"Gnomes Are Genuine Inventors"
https://database.turtle-wow.org/?quest=50310 -"Goblin Engineering At Its Finest!"
https://database.turtle-wow.org/?quest=50313 -"Mirage Raceway: Gnome's Team"
https://database.turtle-wow.org/?quest=50311 -"Mirage Raceway: Goblin's Team"

**Expected behavior. Describe how it should work:**

Clicking Dolores' dialogue options should turn you into a racecar driver and allow you to complete either quests ( "Gnomes Are Genuine Inventors" and "Goblin Engineering At Its Finest!" ). 
Daisy should offer a dialogue option to start the race quest.

**Comment by jameyboor** [comment]
Fixed on next update.
