### ISSUE TITLE
Game crashing when phasing in Southfury River between Durotar & Barrens

### ISSUE THREAD

**Issue by Theilendra** [slowtorta/turtlewow-bug-tracker#4113]
**Please, provide a clear description what the bug is:**
While moving between Durotar and The Barrens in the Southfury River just south of Fire Watch Post, the game crashes and continues to crash, resulting in needing to use the Unstuck website service.

**Steps to reproduce the behavior with as much detail as possible:**

1. Cross back and forth in the river just south of Fire Watch Post
2. 
3. 

**IDs of affected creatures, items, quests or spells with a link to the relevant page:**

NPC: https://database.turtle-wow.org/?npc=
Item: https://database.turtle-wow.org/?item=
Quest: https://database.turtle-wow.org/?quest=
Spell: https://database.turtle-wow.org/?spell=
Object: https://database.turtle-wow.org/?object=

**Expected behavior. Describe how it should work:**
Just move from one side to the other and it should crash. I was jumping out of the water, so that may contribute.

[2023-08-08 05.13.00 Crash.txt](https://github.com/slowtorta/turtlewow-bug-tracker/files/12289577/2023-08-08.05.13.00.Crash.txt)

**Comment by twowTurtReynolds** [comment]
It is likely one of your mods or addons is responsible. Type .crash on discord for assistance.
