### ISSUE TITLE
Hi, I'm im lvl 54 now, ally, and lvled gnome engy to 250, but there's no new recipe from trainers

### ISSUE THREAD

**Issue by litheo** [slowtorta/turtlewow-bug-tracker#4117]
**Please, provide a clear description what the bug is:**

**Steps to reproduce the behavior with as much detail as possible:**

1. Get gnome engy 250
2. talk to both Gnome Artistan / Goblin Artisan engy trainer, now avail/unavail recipe, not even blasting powder

**IDs of affected creatures, items, quests or spells with a link to the relevant page:**

NPC: https://database.turtle-wow.org/?npc=
Item: https://database.turtle-wow.org/?item=
Quest: https://database.turtle-wow.org/?quest=
Spell: https://database.turtle-wow.org/?spell=
Object: https://database.turtle-wow.org/?object=

**Expected behavior. Describe how it should work:**

**Comment by Dalzedur** [comment]
They only teach you the specialized engineering recipes, not the basic engineering 225-300 stuff. For that you actually need to go talk to a master engineer, like the one in Gadgetzan.
