### ISSUE TITLE
Drakin Swiftaxe does not give his quests.

### ISSUE THREAD

**Issue by Tinyfin-github** [slowtorta/turtlewow-bug-tracker#412]
Drakin Swiftaxe does not give his quests. he has just a yellow Exclamation Mark over his head and says greetings

https://database.turtle-wow.org/?npc=51566 Drakin Swiftaxe

![WoW_Oe42H1zeMT](https://user-images.githubusercontent.com/83077166/140518499-059f533a-6f5d-45a9-83e5-69a1a153377e.png)

![WoW_CL2eGMspqJ](https://user-images.githubusercontent.com/83077166/140518508-741f59da-7e63-4376-a2c0-7537f8ba741e.png)

**Comment by slowtorta** [comment]
Tested as gnome, working as intended. His quests have max. level 60 (pointless value but it is what it is), so if your test character is 70 or around, they won't show up. 

![image](https://user-images.githubusercontent.com/66763404/140700925-517a915d-8b3c-445f-997d-6cf546599253.png)
