### ISSUE TITLE
Invisible Zeppelin Bug

### ISSUE THREAD

**Issue by Jdavidlol** [slowtorta/turtlewow-bug-tracker#4121]
**Please, provide a clear description what the bug is:** 
Some of the custom Zeppelins go invisible for players. They can not be interacted with but you can see other players floating in the air... if you try to jump on the invisible Zeppelin you fall to the ground and die or take damage.

**Steps to reproduce the behavior with as much detail as possible:**

1. Travel from Orgrimmar to Thunderbluff Via Zeppelin (or Kargath as it has been reported there too)
2. Once you have arrived walk off the Zeppelin and let it leave without you.
3. See if it returns invisible when players are floating in mid air in front of you.
4. Try to board invisible boat and fall.

**IDs of affected creatures, items, quests or spells with a link to the relevant page:**
It is an issue with the custom Zeppelin Routes. Reports are regarding Kargath and Thunder Bluff

**Expected behavior. Describe how it should work:**
You should be able to leave the Zeppelin, pick up quests, and go back and see the Zeppelin even if it leaves on its route and comes back to return.

**Note:** 
Restarting the game entirely seems to fix the issue for some.

**Comment by twowTurtReynolds** [comment]
Tracking this under https://github.com/slowtorta/turtlewow-bug-tracker/issues/4691 now
