### ISSUE TITLE
Don't benefit from 2/2 talent points in "Improved Ghost Wolf"

### ISSUE THREAD

**Issue by snubbenn** [slowtorta/turtlewow-bug-tracker#4128]
SHAMAN TALENT BUG

After turning level 20 I specced 1/2 into "Improved Ghost Wolf" (shaman talent) - BEFORE LEARNING THE ACTUAL SPELL

After learning the spell I noticed that I didn't get any casting time reduction from the talent point. At level 21 I specced 2/2 into improved ghost wolf which should make the casting instant. Instead I just got a 1 sec casting time reduction.

Tried deleting my WDB folder. Didn't do any difference.

**Comment by SuqMadiqM8** [comment]
Vanilla Ghostwolf has a 3 second cast time that you can only reduce to 1 seconds (-1 second per talent point). This is not a bug.
