### ISSUE TITLE
Fixing "Insignia of the Horde" Trinket

### ISSUE THREAD

**Issue by alexei5071** [slowtorta/turtlewow-bug-tracker#4131]
**Please, provide a clear description what the bug is:**

**Steps to reproduce the behavior with as much detail as possible:**

1. Encounter a Paladin.
2. Wait for the Paladin to dismount and run towards you, then stun you.
3. Wait for the Paladin to kill you without being able to remove the stun effect off of you, due to the Insignia of the Horde not removing the Paladin stun effect.

**IDs of affected creatures, items, quests or spells with a link to the relevant page:**

Item: https://database.turtle-wow.org/?item=18845

**Expected behavior. Describe how it should work:**

> "Use: Dispels **ALL** Immobilizing, Slowing and Stun effects. (5 Min Cooldown)".

**Comment by D4nSch** [comment]
the insignia effect is not the same for all classes, like warlock cannot remove any stuns but charms!

**Comment by twowTurtReynolds** [comment]
Gameplay suggestions do NOT belong on the bug tracker.
