### ISSUE TITLE
Corrupted Night Dragon

### ISSUE THREAD

**Issue by ContractViking** [slowtorta/turtlewow-bug-tracker#4135]
The 'Corrupted Night Dragon' at coords (40, 78) upon cleansing disappeared losing time consuming 'Cenarion Plant Salve' and I did not receive any 'Night Dragon's Breath' which should be received at random from 3 to 7 at a time.

Item's lost: "https://database.turtle-wow.org/?item=11516"
Game object: "https://database.turtle-wow.org/?object=164885"

**Comment by twowTurtReynolds** [comment]
![image](https://github.com/slowtorta/turtlewow-bug-tracker/assets/151180101/ba5b3c80-cc19-4d6f-a810-9f5742789b1b)
I went to that exact object ID. Works fine.
