### ISSUE TITLE
Blasted lands buff removed after druid shapeshifting

### ISSUE THREAD

**Issue by Kangaroux** [slowtorta/turtlewow-bug-tracker#4138]
**Please, provide a clear description what the bug is:**

It removed my buff from the quest turn-in, not sure if it will also remove the buff from the consumable.

**Steps to reproduce the behavior with as much detail as possible:**

1. Be druid
2. Turn in quest for 25 agi Ground Scorpok Assay, get buff from quest npc (only have tested agi)
3. Shapeshift, buff is removed

**Comment by cyaohiri** [comment]
If it happens when leaving forms, see #2511.
