### ISSUE TITLE
Alliance pvp mounts are usable by horde

### ISSUE THREAD

**Issue by Tinyfin-github** [slowtorta/turtlewow-bug-tracker#414]
Alliance pvp mounts are usable by horde

https://database.turtle-wow.org/?item=18241 Armored Black War Steed
https://database.turtle-wow.org/?item=18243 Black Battlestrider
https://database.turtle-wow.org/?item=18244  Black War Ram
https://database.turtle-wow.org/?item=18242  Reins of the Black War Tiger
https://database.turtle-wow.org/?item=19030 Stormpike Battle Charger

**Comment by slowtorta** [comment]
This will be fixed on the next server update!
