### ISSUE TITLE
Lost Defender's Helmet Fails to hide character's hair properly

### ISSUE THREAD

**Issue by Laetholdus** [slowtorta/turtlewow-bug-tracker#4145]
![LostDefendersHelmetHairBug](https://github.com/slowtorta/turtlewow-bug-tracker/assets/142276182/0133ec98-b35c-4f28-99d0-11034ea3bf2a)
**Please, provide a clear description what the bug is:**

**Steps to reproduce the behavior with as much detail as possible:**

1. Helmet doesn't hide hair properly.

**IDs of affected creatures, items, quests or spells with a link to the relevant page:**

Item: https://database.turtle-wow.org/?item=https://database.turtle-wow.org/?item=80810

**Expected behavior. Describe how it should work:**
You could try changing the display ID to Display ID: 22908 [Helm of the great chief], which is the exact same helmet but it hides hair properly.

**Comment by twowTurtReynolds** [comment]
Fixed in 1.17.1
