### ISSUE TITLE
Quest "Making a Statement" made me lose reputation with Bloodsail Buccaneers

### ISSUE THREAD

**Issue by FaustJo** [slowtorta/turtlewow-bug-tracker#4146]
**Please, provide a clear description what the bug is:**
I turned in the quest "Making a Statement" and suddenly my reputation with the Bloodsail Buccaneers was "Unfriendly" so that i cannot accept or complete any quests for them. Booty Bay is now "Hated" of course.

**IDs of affected creatures, items, quests or spells with a link to the relevant page:**

Quest: https://database.turtle-wow.org/?quest=40180

**Expected behavior. Describe how it should work:**
Pretty sure my reputation with the Bloodsails is not supposed to decrease as well.

Edit: There may have been some confusion. What i meant it "Booty Bay reputation is "Hated" too, so i basically screwed over two factions instead of the one i intended to be hated within.

**Comment by StasyaLyova** [comment]
https://github.com/slowtorta/turtlewow-bug-tracker/issues/5935
