### ISSUE TITLE
Unable to Hand in Overlord Mok'Morokk's Concern

### ISSUE THREAD

**Issue by garry-henshaw** [slowtorta/turtlewow-bug-tracker#4152]
Character name: Bunniee

Upon collecting all 3 items for the following quest, I am unable to hand them in. When speaking to the NPC, I get the generic message when speaking to an NPC that has no quests for you. There is no question mark to click to hand in the quest. No issues collecting the items at all, just turning in. Multiple players in the area had the same issue and still are. 

NPC: https://database.turtle-wow.org/?npc=4500
Quest: https://database.turtle-wow.org/?quest=1166

**Comment by twowTurtReynolds** [comment]
Please see https://github.com/slowtorta/turtlewow-bug-tracker/issues/6042
