### ISSUE TITLE
Killed by someone not in warmode, Cant attack back

### ISSUE THREAD

**Issue by Hambeast324** [slowtorta/turtlewow-bug-tracker#4155]
Level 50 priest in Tanaris, mind controlling elite trolls. I used one of the elite trolls to pvp a warmode flagged alliance member. After i killed him, an unflagged non warmode level 60 was able to continuously kill me for an hour and i couldnt attack him back. He is flagged blue/non-warmode until he charges over and kills me. I have screenshots of conversation between me and the non warmode toon.
i completely relogged and had the alliance guy test it again. He explained to me that he leveled up in warmode but at 60 turned warmode off and it had been off for a long time. I am unable to attack him, but he can attack me. As soon as he attacks me, i can fight back and his name tag changes to red. 

My toons name is Ditchpig, the 60 that is non-warmode his name is Izumi.

**Comment by Nicorus49** [comment]
That is just the normal pvp flagging system for any wow pve server. A pve player isn’t flagged for pvp until they actually attack you, at that point they are flagged for around 5 minutes until the flag drops off again.
