### ISSUE TITLE
Missing quest Rewards

### ISSUE THREAD

**Issue by Radsvidan** [slowtorta/turtlewow-bug-tracker#4160]
**Please, provide a clear description what the bug is:**
I've turned in 2 quests now that have recipes as rewards and have not gotten them
**Steps to reproduce the behavior with as much detail as possible:**

1. get a quest with a recipe
2. turn in the quest, quest was tracked in both cases
3. do not receive the item

**IDs of affected creatures, items, quests or spells with a link to the relevant page:**

NPC: https://database.turtle-wow.org/?npc=6031
NPC: https://database.turtle-wow.org/?npc=415
Item: https://database.turtle-wow.org/?item=6735
Quest: https://database.turtle-wow.org/?quest=1618
NPC: https://database.turtle-wow.org/?npc=235
Item: https://database.turtle-wow.org/?item=2697
Quest: https://database.turtle-wow.org/?quest=22

**Expected behavior. Describe how it should work:**
Completion should aware the recipe

Please reach out to Beoram or Obyrell (characters involved) if there are more questions.

**Comment by twowTurtReynolds** [comment]
![image](https://github.com/slowtorta/turtlewow-bug-tracker/assets/151180101/7625b782-9fc6-44e5-8578-f4308e7c036e)
![image](https://github.com/slowtorta/turtlewow-bug-tracker/assets/151180101/13f40c68-e5f4-43a7-b6cd-aa31a885158d)
Works fine.
