### ISSUE TITLE
Feral druid's Frenzied Regeneration formula

### ISSUE THREAD

**Issue by TatkaS1** [slowtorta/turtlewow-bug-tracker#4161]
**Please, provide a clear description what the bug is:**
Class change overview says: "Frenzied Regeneration now also heals for 1% of your Stamina."
![image](https://github.com/slowtorta/turtlewow-bug-tracker/assets/87695943/65340530-e94f-4d9a-a3f4-9d3ebcac592b)
Spell description says "Converts up to 10 rage per second into health for 10 sec. Each point of rage is converted into 20 plus 10% of your stamina as health."
![image](https://github.com/slowtorta/turtlewow-bug-tracker/assets/87695943/3aec573c-4044-4399-a521-77256d45755f)

Instead of the spell converting a point of rage to 20 hp (up to 200 per tick) and then adding 10% of druid's stamina (for example 40 hp at 400 stamina) healing 240 per tick so 2400 over 10 sec, it also multiplies the stamina contribution times 10 making druid heal crazy amounts of 500-800 per second for 10 second effectively healing him back to full each 3 mins even without his HoTs.
**2000 hp+1000%** of the druid's huge stamina over 10 sec is more than paladin's Lay on Hands which has 1h cd and is disabled in Blood Ring. That, together with his own pre-hots, makes the druid in bear form unkillable for the time unless vastly outnumbered while still dishing out respectable damage and long lasting stuns.

**Steps to reproduce the behavior with as much detail as possible:**

1. Pop Frenzied Regeneration.
2. Get 500-800 hp/sec regen for 10 sec ultimately healing for your full huge tank health pool while safely fighting in bear form.

**IDs of affected creatures, items, quests or spells with a link to the relevant page:**

Spell: https://database.turtle-wow.org/?spell=22842
Spell: https://database.turtle-wow.org/?spell=22895
Spell: https://database.turtle-wow.org/?spell=22896

**Expected behavior. Describe how it should work:**
It was previously broken so that formula multiplied 20 by 10 and then added 1% of stamina for results like 204 hp/sec and now it's the other extreme, not only it's 10% but also stamina value is further multiplied by 10 resulting in overwhelming numbers like 700 hp/sec.
Instead it should be: consume up to 10 rage and for each point gain (20 + 1% of stamina) hp per second.

**Comment by GrizB37** [comment]
Pretty simple, you just don't attack the bear then he regains 0 health with 0 rage. Only noobs don't know how to counter frenzied regen.

**Comment by Datedb** [comment]
Don't trust the websites class changes to reflect properly ingame. 1% stamina ain't shit.

**Comment by TatkaS1** [comment]
> Pretty simple, you just don't attack the bear then he regains 0 health with 0 rage. Only noobs don't know how to counter frenzied regen.

By putting his hp down to where he needs to pop the spell you gave him all the rage he needs already. Also he can attack you, in one of his 4 sec stuns even.

**Comment by welpenhund** [comment]
it's actually exactly how it is supposed to work. Druids have no shields nor block rating and their only surviability as last "panic button" is frenzied regeneration while tanking bosses in dungeons.

**Comment by twowTurtReynolds** [comment]
The website needs updating to match how the spell works ingame.
