### ISSUE TITLE
Aspect of the cheetha and minor speed dosent stack

### ISSUE THREAD

**Issue by Gensclassic** [slowtorta/turtlewow-bug-tracker#4166]
**Please, provide a clear description what the bug is:**

Minors speed dosent stack with aspect of the cheetha

**Steps to reproduce the behavior with as much detail as possible:**

1. Get minor speed
2. Active aspecft of the cheetha
3. On aspect talent it sais "Increases movement speed by 30%" so it should stack!!!!!!

**IDs of affected creatures, items, quests or spells with a link to the relevant page:**

NPC: https://database.turtle-wow.org/?npc=
Item: https://database.turtle-wow.org/?item=
Quest: https://database.turtle-wow.org/?quest=
Spell: https://database.turtle-wow.org/?spell=
Object: https://database.turtle-wow.org/?object=

**Expected behavior. Describe how it should work:**

**Comment by AyleeJenn** [comment]
Yep, that is indeed by design and intentional. These speed boni do not stack and are not supposed to stack either.
This can be closed. :)
