### ISSUE TITLE
Cant advance past 75 in mining for a 2nd time.

### ISSUE THREAD

**Issue by duurland** [slowtorta/turtlewow-bug-tracker#4168]
**Please, provide a clear description what the bug is:**

A while back I dropped mining (300 in skill) for another profession.
Now I'd like to pick it back up again, but I've ran into a problem.
I learned mining and leveled it up to 75/75 skill, but now there's no way for me to advance.
"Journeyman Miner" (75-150) and "Expert Miner" (150-225) is both grey'd out and listed under "Already Known", the trainer does not allow me to advance past 75 in skill.

I've tried deleting my WDB folder but no result.
I also noted I already knew how to smelt Dark Iron the 2nd time I picked up mining.

**Expected behavior. Describe how it should work:**
At 50 in skill the trainer should offer me to learn Journeyman Mining (75-150)

**Comment by twowTurtReynolds** [comment]
![image](https://github.com/slowtorta/turtlewow-bug-tracker/assets/151180101/6d503ada-b69c-47d1-9ffc-fdf9dbe519e1)
I was able to train this spell. Please contact a GM.
