### ISSUE TITLE
3 party menbers were killed in a flash with Full HP in Gnomeregan without any reason

### ISSUE THREAD

**Issue by ian170311** [slowtorta/turtlewow-bug-tracker#4169]
**Please, provide a clear description what the bug is:**
I think i met a bug in Gnomeregan, after we killed the first boss Grubbis, suddenly 3 party menbers were killed in a flash without any reason （killed in Full HP status）and other two menbers stay at the same posion but they were no any injured, and i checked Battle record, there no any information to show how we were killed,  and the whole team menbers are old player and we have not faced the situation in the past, so is there any posible to ask GM to help us to check if it is a bug, if so could GM restore our character, many thanks in advance, it's really hard to accept it if it caused by a bug.

**Steps to reproduce the behavior with as much detail as possible:**

1. Kill the Boss Grubbis in Gnomeregan
2.  Drop  a weapon of Rockbiter and done the loot
3. Stay the position as the picture shows, 3 menbers dead in a flash with Full HP status , and 2 menbers are alive without any injured ,actually they stood very closed before i catched the screenshot
![BUG](https://github.com/slowtorta/turtlewow-bug-tracker/assets/142684325/0d18ed94-b7e8-4a7d-8f71-7badfd3afef1)

**IDs of affected creatures, items, quests or spells with a link to the relevant page:**

NPC: https://database.turtle-wow.org/?npc=Grubbis
Item: https://database.turtle-wow.org/?item=
Quest: https://database.turtle-wow.org/?quest=
Spell: https://database.turtle-wow.org/?spell=
Object: https://database.turtle-wow.org/?object=

**Expected behavior. Describe how it should work:**
No one should be killed without any reason

**Comment by Ezzerial** [comment]
Yes its not a bug its an explosion that u need to stand away
