### ISSUE TITLE
Necromancer (for Night Elves, male only) become a Human only skin

### ISSUE THREAD

**Issue by mko2009** [slowtorta/turtlewow-bug-tracker#4172]
**Please, provide a clear description what the bug is:**

**Steps to reproduce the behavior with as much detail as possible:**

1.Necromancer Ⅱ is a skin for night elf. 
https://forum.turtle-wow.org/viewtopic.php?t=7665
Necromancer (for Night Elves, male only) become Necromancer Ⅱ (for Human, male only) in my bag.

2. Its race is human now，night elf player can't use the skin.
3. I've tried deleting my WDB folder but no result.

**Expected behavior. Describe how it should work:
It is a night elf skin.pls fix the bug.thx.

**Comment by slowtorta** [comment]
Fixed in 1.17.0
