### ISSUE TITLE
Eye of the Dead trinket bug

### ISSUE THREAD

**Issue by ZugZug11** [slowtorta/turtlewow-bug-tracker#4175]
Healing spells such as Chain Heal consume more than one charge of Eye of the Dead trinket bonus heal buff (also possibly Prayer of Healing, but i have no way of testing that)
Here's some screenshots of logs 
![Screenshot](https://cdn.discordapp.com/attachments/1140107644502290675/1142969022095306812/qwe123.png)

1. Stack several friendly players or NPC's without full hp in a 10 yard range
2. Equip trinket Eye of the Dead  https://database.turtle-wow.org/?item=23047  and use it 
3. Cast Chain Heal on a friendly NPC or player without full hp without full HP (at least 2)
4. Notice dissapearing of buff stacks equal to number of targers healed 

Item: https://database.turtle-wow.org/?item=23047 , https://database.turtle-wow.org/?spell=28780 

Spell: https://database.turtle-wow.org/?spell=10623 

Only single stack of a buff should be consumed on single healing spell, fix on retail servers was implemented 
https://us.forums.blizzard.com/en/wow/t/wow-classic-version-1137-ptr-is-now-available/838945/169
items subsection last part - Resolved several issues with the Eye of the Dead trinket:
Spells such as Chain Heal and Prayer of Healing now only consume a single charge.
Heal-Over-Time spells now properly consume a charge when used.

**Comment by ZugZug11** [comment]
did some math 
30% is from shaman t2 3p set bonus
https://cdn.discordapp.com/attachments/1140107644502290675/1143322819116159097/reeeee.png

fix is either 1 charge consumed or 3, but with correct calculation

**Comment by twowTurtReynolds** [comment]
Thanks, tracking this under https://github.com/slowtorta/turtlewow-bug-tracker/issues/5137
