### ISSUE TITLE
Timbermaw ancestor doesn't heal anymore again. 

### ISSUE THREAD

**Issue by GrizB37** [slowtorta/turtlewow-bug-tracker#4177]
**Please, provide a clear description what the bug is:**
The Timbermaw ancestor no longer heals in or out of combat after the new update today whish said 'Made Timbermaw ancestor heal out of combat' 
**Steps to reproduce the behavior with as much detail as possible:**

1.summon the ancestor 
2. Have less than 100% hp 
3. Doesn't heal in or out combat

**IDs of affected creatures, items, quests or spells with a link to the relevant page:**

NPC: https://database.turtle-wow.org/?npc=
Item: https://database.turtle-wow.org/?item=
Quest: https://database.turtle-wow.org/?quest=
Spell: https://database.turtle-wow.org/?spell=
Object: https://database.turtle-wow.org/?object=

**Expected behavior. Describe how it should work:**
It appears it's gone back to not healing again before the patch that fixed him healing.

**Comment by ratkosrb** [comment]
He was changed to only heal if you are below 50% health.
