### ISSUE TITLE
After a race change between Alliance and Horde attunements get lost

### ISSUE THREAD

**Issue by Tinyfin-github** [slowtorta/turtlewow-bug-tracker#418]
After a race change between Alliance and Horde attunements get lost

Molten Core attunement 
https://database.turtle-wow.org/?search=Attunement+to+the+Core  Attunement to the Core

Blackwing Lair Attunement
https://database.turtle-wow.org/?quest=7761  Blackhand's Command
https://database.turtle-wow.org/?object=179880 Drakkisath's Brand

Naxxramas Attunement
https://database.turtle-wow.org/?search=The+Dread+Citadel+-+Naxxramas

**Comment by slowtorta** [comment]
*Probably* fixed. Please-reopen this issue if the trouble perists.
