### ISSUE TITLE
Goblin Brainwashing Device - resetting specialization: ranks 2 not available automatically

### ISSUE THREAD

**Issue by alexei5071** [slowtorta/turtlewow-bug-tracker#4180]
**Please, provide a clear description what the bug is:**
When using the Goblin Brainwashing Device to reset specialization, and putting talents points in the enhancement (shaman) talent tree, the following spells are not made available automatically:
Bloodlust (Rank 2)
Stormstrike (Rank 2)

One has to travel to a capital city in order to buy these spells from a shaman class trainer, everythime one wants to respecc.
Please make these spells available to the player automatically when respecc is made into those talents.

**Steps to reproduce the behavior with as much detail as possible:**

1. Use the Goblin Brainwashing Device to reset specialization
2.  Put talents points in the enhancement (shaman) talent tree to select Bloodlust and Stormstrike
3.  You will notice that you only have rank 1 for those two spells, and the ranks 2 are available form the shaman class trainer

**IDs of affected creatures, items, quests or spells with a link to the relevant page:**

Spell: https://database.turtle-wow.org/?spell=45511
Spell: https://database.turtle-wow.org/?spell=45521

**Expected behavior. Describe how it should work:**
The ranks 2 of those spells should be made available automatically to the player upon respecc after selecting these talents in the talent tree.

**Comment by testening** [comment]
There must be something more to this bug, I just tested it and both rank 2 spells were avaliable after using brainwash device.

![Untitled](https://github.com/slowtorta/turtlewow-bug-tracker/assets/86748745/cb7a07b2-88dc-456c-92e5-030e334d3da4)

**Comment by alexei5071** [comment]
Hello, thanks for your quick reply.

Did you have a secondary specialization already ready to activate, with all talents implemented?
In my case, as I said, this happened when resetting the tree completely, and THEN inputting the talent points into those abilities.

Maybe that's why we have a different outcome, but this is just a supposition.
Keep up the good work.

**Comment by testening** [comment]
> Did you have a secondary specialization already ready to activate, with all talents implemented?
Yeah.
I tried a full respec then manually inputting the talent points, same result, both r2 skills showed up. I can't tell why this is happening to you.

**Comment by Muigin** [comment]
Cannot reproduce on current version.
