### ISSUE TITLE
Gelkis Magram Reputation Bug

### ISSUE THREAD

**Issue by Ezzerial** [slowtorta/turtlewow-bug-tracker#4181]
So its should be possible to farm both of the tribes rep at once by killing centaurs near the Maraudon. But i`ve found a weird bug - when u have Honored with one Gelkis and Hated with Magram(and vise versa i guess) after killing the centaurs near the Maraudon u will actually lose reputation with Hated tribe even further(all screenshots attached). Also this is stuck position because I've tried to take a quest for killing the Gelkis members and the situation is the same - you are just ruining two reputations at once!
GM suggested clicking off "At War" with Magram, but it's impossible on Hated (the button is grayed out)

**Steps to reproduce the behavior with as much detail as possible:**

1. Grind 1 tribe rep to Honored, the other should be hated
2. 1)Kill the centaurs near the Maraudon, 
    2) or allied centaurs
3. U will lose reputation in Hated tribe in first case, in second u will lose reputation in two tribes at once

Expected behavior. 
If the centaur is the enemy of one of the factions (or both) killing him must give +rep with his enemies tribe

**Rep before the kill**
Magram
![image](https://github.com/slowtorta/turtlewow-bug-tracker/assets/134404400/48d6082b-9468-4880-8052-2f67821a1fa2)
Gelkis
![image](https://github.com/slowtorta/turtlewow-bug-tracker/assets/134404400/1cb16dd4-1c00-47a3-8363-4a318f545054)

Message in a chat about rep
![image](https://github.com/slowtorta/turtlewow-bug-tracker/assets/134404400/1cc7fed3-94e6-4883-8894-c9e78fbdf7f9)

**Rep after the kill**
Magram
![image](https://github.com/slowtorta/turtlewow-bug-tracker/assets/134404400/4ea83adb-69b5-4401-999f-5c5e164b986c)
Gelkis
![image](https://github.com/slowtorta/turtlewow-bug-tracker/assets/134404400/191754a9-da4a-44d1-aab7-c15a33604f3c)
Grayed out button
![image](https://github.com/slowtorta/turtlewow-bug-tracker/assets/134404400/2f6d2759-3e57-4366-901a-3297193ce290)

**Comment by twowTurtReynolds** [comment]
I know, it's not intuitive, but being 0/36000 means that you are rock bottom in the pit of hated. being 35999/36000 means that you are about to become unhated.
