### ISSUE TITLE
Combo Points drop a split second after opening if you are holding down the mouse/camera controls using mouse.

### ISSUE THREAD

**Issue by ShiraZen** [slowtorta/turtlewow-bug-tracker#4182]
**Please, provide a clear description what the bug is:**
Opening using a Rogue Opener from Stealth - if you are holding down M1+M2, or M2 (mouse walk or mouse camera turn) your first combo points will disappear the moment the ability hits the opponent.

I have had probably 20 Cheap Shots in the last week stun - I see 2/3 Combo Points on the target, then about a millisecond afterwards the Combo Points magically disappear off the target.

**Steps to reproduce the behavior with as much detail as possible:**

1. Happens at complete random to both NPCs and Players.

**IDs of affected creatures, items, quests or spells with a link to the relevant page:**

NPC: https://database.turtle-wow.org/?npc=
Item: https://database.turtle-wow.org/?item=
Quest: https://database.turtle-wow.org/?quest=
Spell: https://database.turtle-wow.org/?spell=
Object: https://database.turtle-wow.org/?object=

**Expected behavior. Describe how it should work:**

**Comment by twowTurtReynolds** [comment]
I can't replicate this. Try with a fresh client yourself.
