### ISSUE TITLE
Unable to move underwater and die

### ISSUE THREAD

**Issue by lilianyang** [slowtorta/turtlewow-bug-tracker#4185]
**Please, provide a clear description what the bug is:Unable to move underwater and die

**Steps to reproduce the behavior with as much detail as possible:**

1.I am level eight or nine, and have accepted a task

2. I want to find tools underwater

3. I found a location that could not be moved and died

4. my Account number is outlook0311,and The character name is hashake,can u help me if you can resurrect me

**IDs of affected creatures, items, quests or spells with a link to the relevant page:**

NPC: https://database.turtle-wow.org/?npc=
Item: https://database.turtle-wow.org/?item=
Quest: https://database.turtle-wow.org/?quest=
Spell: https://database.turtle-wow.org/?spell=
Object: https://database.turtle-wow.org/?object=

**Expected behavior. Describe how it should work:**

**Comment by AyleeJenn** [comment]
This bug-tracker is for bugs not for ingame help. You may want to ask on discord instead :)
This can be closed I think.
