### ISSUE TITLE
Leash issues in Gillijim and Lapidis isles

### ISSUE THREAD

**Issue by Szalor** [slowtorta/turtlewow-bug-tracker#4187]
**Please, provide a clear description what the bug is:**
The monsters throughout Lapidis and Gilijim isles do not leash as regular Vanilla wow monsters in other zones. They reset to their normal position after being kited for more than 20 to 30y of distance from their position.

**Steps to reproduce the behavior with as much detail as possible:**

1. Go the island where Hargul the Hardy giant is.
2. Pull him and try to kite / bring him to the opposite side of the little island where he stands.
3. Check that after running some short distance, he simply resets.

**IDs of affected creatures, items, quests or spells with a link to the relevant page:**

NPC: https://database.turtle-wow.org/?npc=92937 (this is an example NPC, but any monster in these entire zones is affected).

**Expected behavior. Describe how it should work:**
All the monsters should have the same vanilla wow leash patterns, making them kitable "infinitely" and the resets have to only occur naturally after not performing any actions towards the monster(s) being leashed.

**Comment by Jasonstotem** [comment]
I also want to point this out as a major problem on the server. Mob leashing is not standard to all mobs, especially for the custom ones, many of them have very short leashes and they reset very fast back to their positions after you run away. 

Apart from the fact that this looks sloppy and doesn’t make sense, it also introduce other problems that are important especially for the HC players. They should be able to do things like mob split pulling, which can’t be done properly with small leash ranges.

Probably multiple people worked on different mobs and they didn’t apply the same logic, but mob leashing should be standardized.

**Comment by twowTurtReynolds** [comment]
![image](https://github.com/slowtorta/turtlewow-bug-tracker/assets/151180101/2acf64e0-afd9-433b-9f90-e4ef5cafc55a)
I don't see the issue, I'm even able to take him off the island:
![image](https://github.com/slowtorta/turtlewow-bug-tracker/assets/151180101/40d8df33-8bd0-4496-8deb-8b4ffa37cc4e)
