### ISSUE TITLE
TAQ BUG FAMLIY ISSUES

### ISSUE THREAD

**Issue by loslos35** [slowtorta/turtlewow-bug-tracker#4188]
we done the TAQ bug family but have no loots. the last killed was Vem,his korpse  disappeared after done.
We are stilling running the TAQ atm ,waiting for GMs help,our Raid leader is Biobio(Paladin)

**Comment by AyleeJenn** [comment]
Please be advised that being in a raid prevents the raid members from getting quest items from normal quests that are not listed as raid instance quests. :)
