### ISSUE TITLE
paladin frost oil

### ISSUE THREAD

**Issue by ozzymagnum** [slowtorta/turtlewow-bug-tracker#4189]
**Please, provide a clear description what the bug is:**

**Steps to reproduce the behavior with as much detail as possible:**

1. frost oil is proccing all the time when paladin use abilities making it ooverpower and impossible to get away from.
2. 
3. 

**IDs of affected creatures, items, quests or spells with a link to the relevant page:**

NPC: https://database.turtle-wow.org/?npc=
Item: https://database.turtle-wow.org/?item=
Quest: https://database.turtle-wow.org/?quest=
Spell: https://database.turtle-wow.org/?spell=
Object: https://database.turtle-wow.org/?object=

**Expected behavior. Describe how it should work:**

**Comment by AyleeJenn** [comment]
This can be closed I think. :)

**Comment by Hambeast324** [comment]
it is a bug. They are casting frostbolt rank 2 at range with auto attack turned on.

**Comment by twowTurtReynolds** [comment]
Balance suggestions do NOT belong on the bug tracker.
