### ISSUE TITLE
Guild Charter becomes unusable after hardcore character signs and dies/deletes character

### ISSUE THREAD

**Issue by Christopher-L-Massie** [slowtorta/turtlewow-bug-tracker#4192]
**Please, provide a clear description what the bug is:**

**Steps to reproduce the behavior with as much detail as possible:**

1. Open a guild charter on a normal (Non-HC) character
2. Have a hardcore character sign the charter
3. Have the signing hardcore character die before completing the guild charter
4? Delete the hardcore character
5? Remake a new character with the same name as the dead hardcore that signed
6. The guild charter should now be unusable

?* represents steps that I am unsure if they need to be taken

**IDs of affected creatures, items, quests or spells with a link to the relevant page:**
Guild charter - https://database.turtle-wow.org/?item=5863

**Expected behavior. Describe how it should work:**
You should be able to right click and view the details of the guild charter including the guild name and a list of those who have signed will appear in a UI similar to the quest text UI.

**Comment by Christopher-L-Massie** [comment]
This could be unrelated to the character being hardcore and could be solely related to the character being deleted after signing the charter.

**Comment by slowtorta** [comment]
This is the correct behavior.
