### ISSUE TITLE
transmog bug

### ISSUE THREAD

**Issue by favoriteuncle** [slowtorta/turtlewow-bug-tracker#4194]
**Please, provide a clear description what the bug is:**
Two items that my character (Ravenclaw) has wore, do not show up when accessing transmog. 
Those two items are: Hellion Boots and Shimmering Gloves of the Whale. 
**Steps to reproduce the behavior with as much detail as possible:**

1.
2. 
3. 

**IDs of affected creatures, items, quests or spells with a link to the relevant page:**

NPC: https://database.turtle-wow.org/?npc=
Item: https://database.turtle-wow.org/?item=
Quest: https://database.turtle-wow.org/?quest=
Spell: https://database.turtle-wow.org/?spell=
Object: https://database.turtle-wow.org/?object=

**Expected behavior. Describe how it should work:**

**Comment by AyleeJenn** [comment]
I have seen this happen before especially with older characters who had a transmogged item from long ago. One of the previous updates to the client caused this for everyone who had transmogged items prior to that updated that caused it. The solution unfortunately is to re-transmog it with a fashion coin.
That will solve your issue :)
