### ISSUE TITLE
Cannot perform skinning action of Onyxia

### ISSUE THREAD

**Issue by fillflowz** [slowtorta/turtlewow-bug-tracker#4198]
**Please, provide a clear description what the bug is:**
Hey, Oitestingpvp here, rogue in turtlewow. This was the 2nd time I killed Onyxia with a group and have soft-res the skinning of her only to find that the skinning action of her is bugged and cant be done. It says the creature must be looted, even though we gave out all the loot. I tried to relog and I still cannot skin her. Raid id 9597.

I would like to receive prefferably 8 Scale of Onyxia as i shouldve been able to get.

Thanks in advance for ur help or forward msg to GM's who can send me items if possible! 

**Steps to reproduce the behavior with as much detail as possible:**

1. Kill Onyxia 
2.  Give out loot
3.  Try to skin her

**IDs of affected creatures, items, quests or spells with a link to the relevant page:**

NPC: https://database.turtle-wow.org/?npc=10184
Item: https://database.turtle-wow.org/?item=15410
Quest: https://database.turtle-wow.org/?quest=
![cant skin with ID onyxia 9597](https://github.com/slowtorta/turtlewow-bug-tracker/assets/143012372/0a4137c4-40ae-4091-bfab-e12761395b9f)

Spell: https://database.turtle-wow.org/?spell=
Object: https://database.turtle-wow.org/?object=

**Expected behavior. Describe how it should work:**

**Comment by fillflowz** [comment]
I looted both heads
About that quest, i didnt know about that but that, if thats the problem that sucks because thats out of my hands and I should be able to skin her if I kill her even if the person with the quest ports out imo

**Comment by AyleeJenn** [comment]
It appears that this is not a bug afterall but rather an oversight by the player. I believe this may be closed for that reason as the skinning only did not work because the remains were not fully looted, however unfortunate.
