### ISSUE TITLE
Quest Mirage Raceway Gnomes Team Bugged

### ISSUE THREAD

**Issue by Flaschenoffner** [slowtorta/turtlewow-bug-tracker#4199]
**Please, provide a clear description what the bug is:**
First Off I started the first part of this quest you get from Gregor Fizzwuzz in which you have to talk to deloras and test to see if the gnomish machine works and this quest was bugged as soon as you get into the machine nothing happens and you get stuck in place, Then I contacted a GM about this issue and he was able to complete the quest for me. Then I started the next part of the quest which is the quest Im currently trying to do which is Mirage Raceway Gnome Team, the same thing happens when you start the quest. You get put into the Car nothing happens and then your just stuck in place and cant do anything and then to get unstuck I need to Log out.

**Steps to reproduce the behavior with as much detail as possible:**

1. Start Quest
2. Wait for Quest to start
3. Nothing happens and your just stuck in place unable to do anything

**IDs of affected creatures, items, quests or spells with a link to the relevant page:**

NPC: https://database.turtle-wow.org/?npc=50522
Item: https://database.turtle-wow.org/?item=51005
Quest: https://database.turtle-wow.org/?quest=50313
Spell: https://database.turtle-wow.org/?spell=
Object: https://database.turtle-wow.org/?object=

**Expected behavior. Describe how it should work:**
Once you start the quest you get put into a gnomish car or a goblin car depending on which side you choose then the race counts down from 10 and then when the timer hits zero the race starts and then the race ends when you cross the finish Line.

**Comment by slowtorta** [comment]
Fixed.
