### ISSUE TITLE
Selling Fish Quest Glitch

### ISSUE THREAD

**Issue by gitmeupbaby** [slowtorta/turtlewow-bug-tracker#42]
By opening this Issue, I admit to having done the pertinent research using sources from Vanilla (preferably) or Classic. I also understand that sources from other private servers are not acceptable.

 
**Current behavior**: 
Quest "Selling Fish" (Lakeshire) - Quest log showed complete (collected 10 spotted sunfish), but bag only showed 8.
Quest giver had golden "?" symbol but I could not hand in, and mobs would no longer drop sunfish. 

**Expected behavior**: either quest incomplete, or able to hand-in

**Proofs**:  Tried to abandon and restart quest (whilst retaining the 8 sunfish), quest immediately showed as completed again.
Tried to mail items to myself so I could accept the quest with 0 in inventory, but I was "unable to post quest items".

**Steps to reproduce**:
eventually abandoned quest and destroyed items.

******nb: WDB folder had been deleted immediately prior to playing***********************

1. 
2. 
3.

**Comment by slowtorta** [comment]
Cannot reproduce. Working as intended.
