### ISSUE TITLE
cant enter CoT for ANACHRONOS

### ISSUE THREAD

**Issue by Pahacsinta** [slowtorta/turtlewow-bug-tracker#420]
**Please, provide a clear description what the bug is:**

**Steps to reproduce the behavior with as much detail as possible:**

1.I cant enter caverns of time via the npc
2. 
3. 

**IDs of affected creatures, items, quests or spells with a link to the relevant page:**

NPC: https://database.turtle-wow.org/?npc=
Item: https://database.turtle-wow.org/?item=
Quest: https://database.turtle-wow.org/?quest=
Spell: https://database.turtle-wow.org/?spell=
Object: https://database.turtle-wow.org/?object=

**Expected behavior. Describe how it should work:**

**Comment by slowtorta** [comment]
This will be fixed on the next server update.
