### ISSUE TITLE
Why can't my pet learn skills?

### ISSUE THREAD

**Issue by crqbb** [slowtorta/turtlewow-bug-tracker#4200]
Why can't my pet learn skills? Always display target level too low. 
1. I have learned to use 'training beasts'; 
2. My pet has sufficient training points; 
3.The skills that need to be learned meet the level requirements.
![c0c495fdebdbe0f229ecaa5d9fc7705d](https://github.com/slowtorta/turtlewow-bug-tracker/assets/143061689/53e235ec-8b68-4195-b47e-4d57558b71e2)

My email is crqbb1019@gmail.com
My account name is crqbb
My character name is Rickychan

**Comment by twowTurtReynolds** [comment]
Your target is probably too low level.
