### ISSUE TITLE
Illusion:Two-headed Ogre  have a bug

### ISSUE THREAD

**Issue by HomelyLiu** [slowtorta/turtlewow-bug-tracker#4201]
I have purchased Illusion:two-headed ogre.
i found one BUG.
This item will change into three different colors of ogres, 1. Red, 2. White, 3. blue
In the red state everything is normal, there are spellcasting actions, there are seated eating and drinking actions.
White and blue will not work, appeal neither action, I am the undead fs change.
Can gm take a minute to try and see if this problem exists? I'm trying to decide if it's me or the client.

**Comment by Herdon** [comment]
These are ancient Ogre models from back in WoW Beta. They were NOT meant for players hence, missing animations for Jump, Walkback etc. NPC's usually don't have 50+ animations. This is NOT a bug, just a old model that was never meant for player use.
