### ISSUE TITLE
Persistent ground effects are missing visual effect and scrolling text cue

### ISSUE THREAD

**Issue by balakethelock** [slowtorta/turtlewow-bug-tracker#4202]
**Please, provide a clear description what the bug is:**
Persistent ground effects don't get sent from server to client. This was done in the past to avoid them taking an invisible debuff slot. Now since turtle-wow upped the debuff limit, we should re-enable sending them because the lack of visual effect and scrolling combat text cue makes things unnecessarily confusing (especially since for a lot of people, effects like rain of fire are invisible or take too long to show up)

**Steps to reproduce the behavior with as much detail as possible:**

1. Use rain of fire of a warlock character on a mob.
2. The is no visual effect of your rain of fire on the mob.
3. This is normally not a big deal, but raid mobs have rain of fire as a mechanicn and a lot of the time the visual effect is the only way to tell if you're inside the aoe or not.

**IDs of affected creatures, items, quests or spells with a link to the relevant page:**

IDs not relevant, this is a core issue.

**Expected behavior. Describe how it should work:**
https://github.com/vmangos/core/pull/2173 more detail here

Video proof that persistent ground effects must be sent to the client:
[classic bwl](https://youtu.be/UwVNpHaFhUI?si=8TtPFAYF3qbJZLKR&t=2711)
[2005 vanilla bwl](https://youtu.be/HfvHFo7wEVk?si=cBqLsIDqQ23FkOXJ&t=4819)

And here's how it is in private server in the bugged state then after the fix in the pull request
https://github.com/slowtorta/turtlewow-bug-tracker/assets/111737968/94dcd8e9-b61e-40a4-8f2f-cab3f783cdcf

**Comment by jameyboor** [comment]
Updated on next server update.
