### ISSUE TITLE
Frost Oil is bugged

### ISSUE THREAD

**Issue by kravis** [slowtorta/turtlewow-bug-tracker#4204]
**Please, provide a clear description what the bug is:**
Paladins can spam certain abilities on target without needing to land a spell or melee hit to trigger frost oil on command without cooldown

**IDs of affected creatures, items, quests or spells with a link to the relevant page:**

Item:https://database.turtle-wow.org/?item=3829

**Expected behavior. Describe how it should work:**
Use: When applied to a melee weapon it gives a 10% chance of casting Frostbolt at the opponent when it hits. Lasts 30 minutes.

Frost oil should apply on melee hits and not ranged abilities

**Comment by Hambeast324** [comment]
This cannot be a feature. You have broken BGs like Blood Ring due to this.
