### ISSUE TITLE
Scrolls of Binding light potentially bugged.

### ISSUE THREAD

**Issue by Degar17** [slowtorta/turtlewow-bug-tracker#4206]
**Please, provide a clear description what the bug is:**

**Steps to reproduce the behavior with as much detail as possible:**

1. Scrolls of Blinding Light (Item ID 31847) Being a trinket should only incur a trinket GCD
2. I attempted to combine the use of Scrolls and Cloudkeeper Legplates (ID 25343) for a paladin nuke.
3. Scrolls puts Cloudkeepers on an internal cooldown whereas using a trinket such as Fetish of The Sand Reaver (34261) does not incur the Cloudkeeper internal cooldown.

**IDs of affected creatures, items, quests or spells with a link to the relevant page:**

NPC: https://database.turtle-wow.org/?npc=
Item: https://database.turtle-wow.org/?item=
Quest: https://database.turtle-wow.org/?quest=
Spell: https://database.turtle-wow.org/?spell=
Object: https://database.turtle-wow.org/?object=

**Expected behavior. Describe how it should work:**
It should work the same as Fetish of the Sand Reaver, so i should be able to stack scrolls and Cloudkeepers for a nuke option. However it does not.

**Comment by twowTurtReynolds** [comment]
Fetish is IIRC the one single exception to the 1.12 rules for stacking offensive trinkets. If you can prove otherwise, reply here please.
