### ISSUE TITLE
Quest "Race Against Time!" is bugged again.

### ISSUE THREAD

**Issue by Tugryn** [slowtorta/turtlewow-bug-tracker#4207]
I take quest and get in the racing car, quest timer is ticking, but i don't see racing announce and car doesn't move.

NPC: https://database.turtle-wow.org/?npc=4507
Quest: https://database.turtle-wow.org/?quest=50316

**Comment by Husmeador12** [comment]
The quest is not bugged again because it wasn't fixed before. Your ticket https://github.com/slowtorta/turtlewow-bug-tracker/issues/4122 still open.

**Comment by slowtorta** [comment]
Fixed.
