### ISSUE TITLE
BUG of Thaddius in NAXX

### ISSUE THREAD

**Issue by caijiaweii** [slowtorta/turtlewow-bug-tracker#4209]
**Please, provide a clear description what the bug is:**
hi gm we have a terrible bug need to reported
when we farm Thaddius in NAXX, the boss will spell lighting ball to the tank and kill the tank. we know the tanks should be melee. but the boss still spell the light ball

**Steps to reproduce the behavior with as much detail as possible:**

1.we even used winterfall firewater made the tanks bigger but it didn't work. the lighting ball still kill the tanks
2. 
3. 

**IDs of affected creatures, items, quests or spells with a link to the relevant page:**

NPC: https://database.turtle-wow.org/?npc=
Item: https://database.turtle-wow.org/?item=
Quest: https://database.turtle-wow.org/?quest=
Spell: https://database.turtle-wow.org/?spell=
Object: https://database.turtle-wow.org/?object=

**Expected behavior. Describe how it should work:**
Thaddius no more lighting balls killing the tanks

**Comment by twowTurtReynolds** [comment]
I am unable to reproduce this. Could you upload current footage to help illustrate the problem?
