### ISSUE TITLE
Naxx attunement quest does not grand reputation.

### ISSUE THREAD

**Issue by BosBeest** [slowtorta/turtlewow-bug-tracker#421]
The quest "The Dread Citadel - Naxxramas"(Reverted rep , https://database.turtle-wow.org/?quest=9122) does not award "500" Argent Dawn rep on completion as is noted on the database.

**Comment by slowtorta** [comment]
I justed tested it and it's working as intended. Those notifications appear in your combat log by default, you probably missed it :) 
![image](https://user-images.githubusercontent.com/66763404/140705975-713a37af-0146-489e-a453-8ba5e1a38b4b.png)

**Comment by BosBeest** [comment]
There was nothing in my combat log and the same amount of reputation remained after completion. thanks for checking though.
