### ISSUE TITLE
Blackflame Wand in wrong hand

### ISSUE THREAD

**Issue by Squirreled** [slowtorta/turtlewow-bug-tracker#4211]
The Blackflame Wand model is in the left hand, but when the wand animation plays the character is still swinging the right hand and wand projectiles appear out of the empty right hand.

The blackflame wand model should be in the right hand, like other wands.

https://database.turtle-wow.org/?item=83215

**Comment by twowTurtReynolds** [comment]
![image](https://github.com/slowtorta/turtlewow-bug-tracker/assets/151180101/209c76f4-d63b-4535-91c0-0d61bb15d01f)
The fireballs are flung with the right hand indeed.

**Comment by twowTurtReynolds** [comment]
Same issue as https://github.com/slowtorta/turtlewow-bug-tracker/issues/3865
