### ISSUE TITLE
Game is unplayable for anyone outside of EU at the current population cap(12k)

### ISSUE THREAD

**Issue by ametc1** [slowtorta/turtlewow-bug-tracker#4213]
**Steps to reproduce the behavior with as much detail as possible:**

1. Try to do any form of raid with 1000ms+ 
2. Realize that any boss with mechanics beyond tank and spank are almost impossible to kill due to massive lag spikes on top of the already 1000ms most of your raid is experiencing
3. Feel like the devs don't care about the player experience and are just trying to squeeze as many people on the servers as possible

**Expected behavior. Describe how it should work:**

Game was playable at 10k population, but even that was pushing the limits of latency for people outside of EU. At 8k pop, we would get 300ms average. At 10k pop, up to 500ms. At 11k pop, closer to 1000ms. At 12k pop, we get 1100ms with upwards of 4000ms happening regularly, and massive unpredictable lag spikes as soon as any one tries to fight mobs in raids.

Please either drop the population cap back to 10k, or launch the China server now and provide resources for players to use translation services on their end while you get the client stuff translated. This isn't a race issue, don't gaslight your long term dedicated player base by saying its not due to one massive demographic of players joining en masse. This is about the enjoyment and playability of your server. If it was playable at 20k population I couldn't care. We just want to be able to raid, play together without waiting for 10 seconds to see if you died in a raid. It is a demoralizing and awful experience. Please, do something to address this obvious issue.

**Comment by Naonak1945** [comment]
Bigger the population. Higher chance of more donations.

**Comment by AyleeJenn** [comment]
I believe that this thread honestly belongs on the forum at least I don't see a bug mentioned anywhere in this heartfelt plea. For that reason I would advise to bring this to forum instead as this is for bugs and this does not appear to be a bug. :)

**Comment by ConcernedTurtler** [comment]
all that matters is spectral tigers
