### ISSUE TITLE
Quest "Speaking with Gan'zulah" is bugged

### ISSUE THREAD

**Issue by Tinyfin-github** [slowtorta/turtlewow-bug-tracker#422]
Quest "Speaking with Gan'zulah" is bugged

How it should work: after completing all the objectives you should be able to interact with the Bubbling Cauldron to complete the quest

What does not work: after completing all the objectives you can't interact with the Bubbling Cauldron to complete the quest

https://database.turtle-wow.org/?quest=586 Speaking with Gan'zulah
https://database.turtle-wow.org/?object=2076 Bubbling Cauldron

**Comment by slowtorta** [comment]
Just tested, no problems.
