### ISSUE TITLE
Resource Node Bugged: Small Thorium Vein

### ISSUE THREAD

**Issue by AyleeJenn** [slowtorta/turtlewow-bug-tracker#4222]
**Please, provide a clear description what the bug is:**
Upon mining a small thorium resource node the player is supposed to be presented with a loot window that has contents in it. The loot window appears but it has no contents, nothing can be looted as there is nothing there to loot. Many attempts have been. A screenshot with the exact location of the ore node will be provided.

We had the fortune of another player traveling to the same node and attempting to mine it and that player was also unable to mine the node at all. Which means that this can be reproduced by other players well.

![bugged throium node2](https://github.com/slowtorta/turtlewow-bug-tracker/assets/87241085/e2b12ca5-020f-4121-a2a9-edcb7d26b33e)

And here is the screenshot of the party member who attempted to mine the node as a verification for the bug.

![WoWScrnShot_082723_201808_-_Miningbug](https://github.com/slowtorta/turtlewow-bug-tracker/assets/87241085/c7a907c0-4461-4675-8781-c1f20a3364d1)

_**I was able to find the exact coordinates of the node the data base. The exact coordinates are ...
64.3, 12.8**_

**Steps to reproduce the behavior with as much detail as possible:**

1. Travel to Northern Felwood near the Furbolg village to the exactl location shown in the screenshot
2. Attempt to mine the small thorium vein
3. Observe as no loot appears in the loot window

**IDs of affected creatures, items, quests or spells with a link to the relevant page:**

Object: https://database.turtle-wow.org/?object=324

**Expected behavior. Describe how it should work:**
Loot should appear in the loot window when a resource node is interacted with. We attempted to log out and clear the WDB folder to exclude the possibility of this being a client side error. Deleting the WDB folder did not help. The error could reliably be verified and reproduced.

**Comment by twowTurtReynolds** [comment]
![Uploading image.png…]()
Works fine. Maybe that one just somehow ended up bugged for that week and was fixed with reset.
