### ISSUE TITLE
Warrior Rage bug, and Berserker Rage bug

### ISSUE THREAD

**Issue by BuOnGit** [slowtorta/turtlewow-bug-tracker#4227]
**Please, provide a clear description what the bug is:**
If you are playing a warrior, you should be able to generate rage through getting hit, which does not happen. You gain the standard 1 rage while in combat, but do not generate any rage through just getting hit.
Similarly, it says on the tooltip of Berserker Rage that you should gain additional rage when taking damage while the effect is active.
This does not work either, and you still only generate 1 rage every second or few seconds.

**Steps to reproduce the behavior with as much detail as possible:**

1. Make a Warrior.
2.  Get a monster to hit you, see that you get 1 rage periodically without generating extra through the normal hits.
3. Activate Berserker Rage, see that you still do not get additional rage.

**IDs of affected creatures, items, quests or spells with a link to the relevant page:**

Spell: https://database.turtle-wow.org/?spell=18499

**Expected behavior. Describe how it should work:**

The monster hits should give you more rage than normal generation.
And the Berserker Rage should do the same, giving you additional rage during the duration of the spell effect.

Edit: "Rage can be generated with several different methods. The primary cause of rage generation is by being attacked, which varies based on damage taken." (vanilla-wow-archive.fandom.com/wiki/rage)

**Comment by balakethelock** [comment]
I can't reproduce. I generate rage from damage taken normally. The periodic rage generation is because of the talent "Anger Management" and it's added on top of the normal rage gen without affecting it at all.

**Comment by twowTurtReynolds** [comment]
I am at a loss at how you experienced this bug.
