### ISSUE TITLE
Item Bug: Item cannot be disenchanted (Thorium Greatsword)

### ISSUE THREAD

**Issue by AyleeJenn** [slowtorta/turtlewow-bug-tracker#4228]
**Please, provide a clear description what the bug is:**
The blacksmithing item "Thorium Greatsword" cannot be disenchanted.
The disenchantment distribution can be seen in the screenshot.

![thorium greatsword](https://github.com/slowtorta/turtlewow-bug-tracker/assets/87241085/4c93ddd9-69f4-4ea8-b8ca-831905b15e5f)

**Steps to reproduce the behavior with as much detail as possible:**

1. Smith or acquire a Thorium Greatsword
2. Attempt to disenchant it
3. Observe as the error "item cannot be disenchanted" reports back

**IDs of affected creatures, items, quests or spells with a link to the relevant page:**

Item: https://database.turtle-wow.org/?item=12764

**Expected behavior. Describe how it should work:**
The item "Thorium Greatsword" should be disenchantable. Like shown in the above screenshot.

**Comment by slowtorta** [comment]
Fixed on the next update. However, this item wasn't supposed to be disenchanted, it is the same in Classic Era at Blizzard. Your add-on is not providing the accurate info.

**Comment by AyleeJenn** [comment]
Oh my o.o I am sorry, I had no idea it is not supposed to be disenchanted. I don't know why I thought that maybe because every green or better item can (usually?) be disenchanted. Sorry if this was wrong v.v
