### ISSUE TITLE
All the tin ore i gathered disappeared after finishing deadmines run.

### ISSUE THREAD

**Issue by raulcastr** [slowtorta/turtlewow-bug-tracker#4229]
**Please, provide a clear description what the bug is:**

We finished deadmines run at around 1:45 - 2:00 am (GMT+2) .
Basically what happened is that all the tin I had gathered dissappeared from my bags at some point (I realised of having 0 tin ore in my bags right after using HearthStone and selling useless items, and i am sure i did not sell the tin ore).  Some of the tin i had was given to me traded by other party members because i was the only miner and lots of mobs drop tin ore at that dungeon ( i believe i had around 20 didn't really check at any point). 

Also im sure my mining skill and character xp remained the same than i had before starting the deadmines run.

My character is lvl 26 paladin and i played tank role during the run.

**Steps to reproduce the behavior with as much detail as possible:**

1. We made a group of 5 (2 mages, 1 hunter, 1 priest and me as Paladin tank), our tactic during the dungeon was to do aoe damage  most of the time. We had 0 wipes and we finished pretty quick.
2. During the run i mined every copper&tin vein because i was the only miner ( also some party members traded me the tin ore they found on the npc bodies)
3. After killing vancleef ( last boss ) i used HS and while selling the useless items i realised i had 0 tin ore, which is impossible that i had 0 tin ore (should have around 20).
4. Also later i found out that i had the same mining skill and character xp than before entering the dungeon which is weird.

**IDs of affected creatures, items, quests or spells with a link to the relevant page:**

Item: https://database.turtle-wow.org/?item=2771

PD: I am a very experienced player in wow classic, and normally i would not bother with this kind of stuff, but i am very poor in this server, don't even have enough gold to buy skills and it's my main character, so that tin ore is a big deal to me atm :( 

Thanks anyway!!

**Comment by twowTurtReynolds** [comment]
I'm sorry, i'm going to have to chalk this up to you accidentally deleting or vendoring these items. I nor the staff have ever heard of this being a real bug.
