### ISSUE TITLE
Mobs are not droping quest items for Noggle's Last Hope

### ISSUE THREAD

**Issue by cesar-pix** [slowtorta/turtlewow-bug-tracker#4232]
1. Noggle's Last Hope is not working, [Rock Stalker](https://database.turtle-wow.org/?npc=11739) and [Stonelash Flayer](https://database.turtle-wow.org/?npc=11737) doesn't drop the quest items in Silithus

NPC: https://database.turtle-wow.org/?npc=
Item: 
https://database.turtle-wow.org/?item=20377
https://database.turtle-wow.org/?item=20375
Quest:
https://database.turtle-wow.org/?quest=8278

The quest items should have a 80% drop rate according to the Database and they never drop

**Comment by twowTurtReynolds** [comment]
![image](https://github.com/slowtorta/turtlewow-bug-tracker/assets/151180101/be4982ca-f1d9-4892-a9f0-7852a386c069)
![image](https://github.com/slowtorta/turtlewow-bug-tracker/assets/151180101/3dd06179-e719-4000-b537-c8c53d89724f)

I'm not sure why you weren't seeing this work. Maybe you were in a raid group at the time?
