### ISSUE TITLE
Gardening | Planter spawned in model, clickable items not in line of sight

### ISSUE THREAD

**Issue by YamaYAML** [slowtorta/turtlewow-bug-tracker#4234]
**Please, provide a clear description what the bug is:**

Mushrooms (and probably other growables) can't be picked from planter because of LOS issue. 
Reproduced on GM account.

GPS:
You are OUTdoor
Map: 1 (Kalimdor) Zone: 14 (Durotar) Area: 1296 (Rocktusk Farm)
X: 1279.541138 Y: -4209.870117 Z: 27.127497 Orientation: 2.535379
grid[24,34]cell[1,6] InstanceID: 12
 ZoneX: 42.503456 ZoneY: 15.001195
GroundZ: 27.128519 FloorZ: 27.128519 Have height data (Map: 1 VMap: 1)

**Steps to reproduce the behavior with as much detail as possible:**

1. Tele
2. Plant some mushrooms (optional)
3. Try to pick from the planter, 1/5 in the fence's pole. 

**Expected behavior. Describe how it should work: Should not get error 'Target not in line of sight' when trying to pick the item growing from the planter. Reproduced, tried several positions.

![image](https://github.com/slowtorta/turtlewow-bug-tracker/assets/73019779/7ceae529-8879-4431-820f-2cda060ac56e)

**Comment by slowtorta** [comment]
I think it might be because it's spawned in the fence... Works fine for me. Please reopen if the issue reoccurs in a flat spot.

**Comment by YamaYAML** [comment]
Hehe, fair enough. Thanks.
