### ISSUE TITLE
honor rank bug

### ISSUE THREAD

**Issue by benjurry250** [slowtorta/turtlewow-bug-tracker#4237]
**Please, provide a clear description what the bug is:**

**Steps to reproduce the behavior with as much detail as possible:**

1.my mage name sctv , last week have 155k honor, and this week is rank0.
2. 
3. 

**IDs of affected creatures, items, quests or spells with a link to the relevant page:**

NPC: https://database.turtle-wow.org/?npc=
Item: https://database.turtle-wow.org/?item=
Quest: https://database.turtle-wow.org/?quest=
Spell: https://database.turtle-wow.org/?spell=
Object: https://database.turtle-wow.org/?object=

**Expected behavior. Describe how it should work:**

**Comment by GrizB37** [comment]
You disabled your rank at the NPC in either Stormwind or Orgrimmar, Join a BG and look at your name in the scoreboard, this will show your rank, or enable showing your title/rank again.

Not a bug.

**Comment by GrizB37** [comment]
https://armory.turtle-wow.org/#!/character/Sctv

You're Rank 7.

**Comment by benjurry250** [comment]
what's the name of the NPC who can enable showing your title/rank again in org.  tyvm.

获取Outlook for Android<https://aka.ms/AAb9ysg>
________________________________
