### ISSUE TITLE
enter moonkin form the skill bar does not automatically switch

### ISSUE THREAD

**Issue by Spirit2011** [slowtorta/turtlewow-bug-tracker#4238]
**Please, provide a clear description what the bug is:**
    I am a balance druid. When I enter moonkin form, the skill bar does not automatically switch, it is still in human form, but it will switch when I enter bear form or cat form.
**Steps to reproduce the behavior with as much detail as possible:**

1.
2. 
3. 

**IDs of affected creatures, items, quests or spells with a link to the relevant page:**

NPC: https://database.turtle-wow.org/?npc=
Item: https://database.turtle-wow.org/?item=
Quest: https://database.turtle-wow.org/?quest=
Spell: https://database.turtle-wow.org/?spell=
Object: https://database.turtle-wow.org/?object=

**Expected behavior. Describe how it should work:**

**Comment by slowtorta** [comment]
It's not supposed to do this in Vanilla.
