### ISSUE TITLE
Swoops in Mulgore cast

### ISSUE THREAD

**Issue by TeiBei** [slowtorta/turtlewow-bug-tracker#424]
**Please, provide a clear description what the bug is:** 
Swoops in Mulgore casts their Swoop ability FAR too often, seemingly without cooldown, rendering Tauren Hunters' taming quest impossible to do solo, as the Swoop ability stuns for 2 seconds every time, cancelling the taming process. In order for Tauren Hunters to complete this quest, they MUST ask for help on their own initiative from strangers, unlike any other hunters' taming quests, which can be done entirely solo.

**Steps to reproduce the behavior with as much detail as possible:**

1. Attack a swoop in mulgore around the relevant or equal level

**IDs of affected creatures, items, quests or spells with a link to the relevant page:**

NPC: https://database.turtle-wow.org/?npc=2970
Spell: https://database.turtle-wow.org/?spell=5708

**Expected behavior. Describe how it should work:**

The swoops should have a cd on their Swoop ability, long enough for them to only cast it once in a while and not constantly. Maybe with a 20 or 30 seconds cd, enabling Tauren Hunters to complete their quests solo, as intended.

**Comment by LeopoldHock** [comment]
Could be Vanilla behavior.
