### ISSUE TITLE
Black Scrapforged Mechaspider 1.Item: https://database.turtle-wow.org/?item=81192  in the city it is impossible to summon a riding animal (a black mechaspider forged from scrap metal), why is there such a restriction?

### ISSUE THREAD

**Issue by Zhnetc** [slowtorta/turtlewow-bug-tracker#4242]
**Please, provide a clear description what the bug is:**

**Steps to reproduce the behavior with as much detail as possible:**

1.
2. 
3. 

**IDs of affected creatures, items, quests or spells with a link to the relevant page:**

NPC: https://database.turtle-wow.org/?npc=
Item: https://database.turtle-wow.org/?item=
Quest: https://database.turtle-wow.org/?quest=
Spell: https://database.turtle-wow.org/?spell=
Object: https://database.turtle-wow.org/?object=

**Expected behavior. Describe how it should work:**

**Comment by slowtorta** [comment]
Some mounts are too big to be allowed in over-crowded areas.

**Comment by Zhnetc** [comment]
well, maybe, but with such success it is impossible then to ride around the city on an Amani battle bear because it is also big. Okay, if you can't ride it in cities where at least information about it, I've wasted a lot of gold and I can't even ride it around the city and show off what a good fellow I am, I bought myself such a beautiful riding animal and earned gold myself. No, I'm a fool because I wasted a lot of money, it's beautiful but not very convenient for a hard worker like me. Forgive me, but it's not fair. I'm sorry for my English I don't know him well.
