### ISSUE TITLE
Shimmer Stout quest unavailable after turning in A Perfect Stout

### ISSUE THREAD

**Issue by dkmnllth** [slowtorta/turtlewow-bug-tracker#4246]
**Please, provide a clear description what the bug is:**

Turned in A Perfect Stout and am above level 8 (the minimum level required to accept Shimmer Stout). There is no quest available from Rejold Barleybrew, who is the turn-in NPC for A Perfect Stout and the questgiver for Shimmer Stout. Bug found on a level 8-9 Gnome Warlock (if that's relevant).

**Steps to reproduce the behavior with as much detail as possible:**

1. Turn in A Perfect Stout.
2. Be level 8 or higher.
3. No follow-up quest available.

**IDs of affected creatures, items, quests or spells with a link to the relevant page:**

NPC: https://database.turtle-wow.org/?npc=1374
Quest: https://database.turtle-wow.org/?quest=413

**Expected behavior. Describe how it should work:**

Completion of A Perfect Stout quest should open up Shimmer Stout quest.

**Comment by twowTurtReynolds** [comment]
![image](https://github.com/slowtorta/turtlewow-bug-tracker/assets/151180101/58472cf5-1109-4774-8697-801762d71df2)

Look at the DB. Shimmer stout has a prereq, and it is not the Perfect Stout quest.
