### ISSUE TITLE
Cartographer Title Impossible - Scarlet Bascillica Zone Not There.

### ISSUE THREAD

**Issue by GrizB37** [slowtorta/turtlewow-bug-tracker#4247]
**Please, provide a clear description what the bug is:**
When typing .cart .cartographer command it tells you to go to the Scarlet Bascillica.
You go there and this subzone isnt even in the game and never was apparently:

Notes and trivia
The Scarlet Basilica is built very much like the [Cathedral of Light]
At some point, the subzone was removed, but the building itself was not affected.

**Steps to reproduce the behavior with as much detail as possible:**

1. Go to Tyrs hand
2. The Subzone Scarlet Bascillica is no where to be found
3. This makes the title almost impossible to acheive.

**Expected behavior. Describe how it should work:**
Remove the requirement from this zone from the Next:  list or just remove this title from the game as its near impossible to find your missing spots.

Christ knows why the devs have closed the previous bug reports on this when its clearly not been fixed??

Very frustrating to spend hours doing this and days exploring all the seas then you get to this point and unable to progress.

Thank you.

**Comment by slowtorta** [comment]
Fixed on the next update.
