### ISSUE TITLE
Dying on HC lvl 50 duo the instant 50% hp shot kill from lower lvl monster

### ISSUE THREAD

**Issue by Perkana92** [slowtorta/turtlewow-bug-tracker#4248]
**Please, provide a clear description what the bug is:**

Well, I died on my gnome warlock HC lvl 50 named Andreya while doing an escort quest https://database.turtle-wow.org/?quest=836, while following mechanical chicken, we stumbled upon 3 Owlbeasts that spawn ( probably because of the quest), I killed them yesterday easily, because they are easy to kill, but, I failed quest and started it again today. Ofc as a warlock, I taunt them with my voidwalker and kill 1 by 1. When there was only 1 owlbeast left, I was casually shooting it with wand, when all the suddenly BOOM, I lost instantly over 1.2k hp, while in combat log said I only suffered 148 dmg if I can recall correctly. So yeah, please if it's possible I know it's not in the rules, but, dying now wasn't my fault and this server should compensate for my lost time by restoring my character, if it was my fault, I would let it go, but it really wasn't. So please check logs or something..

**Steps to reproduce the behavior with as much detail as possible:**

1. 
2. 
3. 

**IDs of affected creatures, items, quests or spells with a link to the relevant page:**

NPC: https://database.turtle-wow.org/?npc=2929#drop probably these
Item: https://database.turtle-wow.org/?item=
Quest: https://database.turtle-wow.org/?quest=836
Spell: https://database.turtle-wow.org/?spell=
Object: https://database.turtle-wow.org/?object=

**Expected behavior. Describe how it should work:**

**Comment by ratkosrb** [comment]
Dead characters are not restored ever for any reason. There are no death appeals on turtle.

**Comment by Kangaroux** [comment]
The owlbeasts that spawn during the escort have an enrage that increases their damage. Those escorts are notoriously dangerous. As the player, it's your responsibility to ask around if you're unfamiliar with the quest, and/or have the tools to escape if something goes wrong.

**Comment by GrizB37** [comment]
Not a bug, the owl beasts enrage, considerably increasing their damage.
