### ISSUE TITLE
Inferno death message does not include player name

### ISSUE THREAD

**Issue by Kangaroux** [slowtorta/turtlewow-bug-tracker#4249]
Example from yesterday:

> A tragedy has occured. Inferno character has fallen to Hazzuri Troll (level 48) at level 60. They laughed in the face of death, but have learnt that death always has the last laugh.

This causes a lot of confusion for other HC60 players as we try and track down who died. It seems like a straightforward fix that would be very appreciated.

We'd expect it to include the player name after "Inferno character", like how it is for non-60 deaths:

> A tragedy has occurred. Hardcore character **Skabbs** has fallen to Cliff Walker (level 52) at level 50. May this sacrifice not be forgotten.

**Comment by slowtorta** [comment]
Fixed.
