### ISSUE TITLE
Crying emote for Tauren female is bugged

### ISSUE THREAD

**Issue by TeiBei** [slowtorta/turtlewow-bug-tracker#425]
**Please, provide a clear description what the bug is:**
The audio played when doing /cry as tauren female 'lags' for a better lack of a word, and replays the first 0,2 seconds of the audio over and over roughly 8 times, and it isn't until the emote nears its end that the full audio plays out uninterrupted.

**Steps to reproduce the behavior with as much detail as possible:**

1. Play Tauren female
2. Do /cry

**Expected behavior. Describe how it should work:**
The audio for the emote should play uninterrupted from the moment you start the emote.

**Comment by slowtorta** [comment]
Included in https://github.com/slowtorta/turtlewow-bug-tracker/issues/449

**Comment by slowtorta** [comment]
Fixed in 1.16.1.
