### ISSUE TITLE
Shadowstrike Weapon

### ISSUE THREAD

**Issue by welpenhund** [slowtorta/turtlewow-bug-tracker#4252]
**Please, provide a clear description what the bug is:**

**Steps to reproduce the behavior with as much detail as possible:**

1. Equip shadowstrike
2. Have lots of Spellpower gear on
3. Make the weapon proc with Judgement of the Crusader - The person lifesteals like 1.5k (seems to be bugged and scale  with spellpower?)

**IDs of affected creatures, items, quests or spells with a link to the relevant page:**

NPC: https://database.turtle-wow.org/?npc=
Item: https://database.turtle-wow.org/?item=17074
Quest: https://database.turtle-wow.org/?quest=
Spell: https://database.turtle-wow.org/?spell=
Object: https://database.turtle-wow.org/?object=

**Expected behavior. Describe how it should work:**
Correct me if i am wrong, but that steal should be a fixed amount and not scale with anything, right? (Propably same with thunderstrike)

**Comment by Nicorus49** [comment]
All lifetap weapons generally scale with spellpower at a 1:1 ratio. This is intentional on turtle and vanilla behavior so this is a balance issue for the forums not a bug.

**Comment by welpenhund** [comment]
> All lifetap weapons generally scale with spellpower at a 1:1 ratio. This is intentional on turtle and vanilla behavior so this is a balance issue for the forums not a bug.

https://forum.turtle-wow.org/viewtopic.php?p=53905&hilit=Shadowstrike#p53905 <- already was reported on forums and ignored. And it's obviously a bug when it scales with spellpower.

**Comment by Nicorus49** [comment]
> > All lifetap weapons generally scale with spellpower at a 1:1 ratio. This is intentional on turtle and vanilla behavior so this is a balance issue for the forums not a bug.
> 
> https://forum.turtle-wow.org/viewtopic.php?p=53905&hilit=Shadowstrike#p53905 <- already was reported on forums and ignored. And it's obviously a bug when it scales with spellpower. Only class benefitting and able to abuse it here is paladins with their ability "Judgement of the Crusader"

If you read the patch notes corrupted ashbringer was even changed recently to have the same scaling.  It can’t be a bug if they are intentionally changing weapons to scale like this.
