### ISSUE TITLE
Waters of vision Off-Hand having no CD on Equip

### ISSUE THREAD

**Issue by Bestoriop** [slowtorta/turtlewow-bug-tracker#4254]
**Please, provide a clear description what the bug is: Waters of vision item doesn't have any CD when it is equipped**

**Steps to reproduce the behavior with as much detail as possible:When an item with an activation effect is equipped, it needs to go on a 30 sec cooldown before you can use it. Waters of vision doesn't have this 30 sec cooldown which allow any mana class to equip it, use it, and then replace it by a stronger item during the 2 min CD**

1. Equip Waters of vision in Off-hand
2. Use it instantly
3. Notice there is no 30 sec cooldown

**IDs of affected creatures, items, quests or spells with a link to the relevant page:

Item (Waters of Vision): https://database.turtle-wow.org/?item=51861
Quest (Preventing Poison: https://database.turtle-wow.org/?quest=60134
Spell (Restore Mana effect): https://database.turtle-wow.org/?spell=438 **

**Expected behavior. Describe how it should work: A 30 sec cooldown should exist when you equip that item**

**Comment by twowTurtReynolds** [comment]
Replicated. This issue makes this item a bit too good, and players will have a hard time freeing this bag slot for far far longer than anywhere else. It is already good as a free cheap mana potion.

**Comment by Dragunovi** [comment]
Should be fixed in the next scheduled server restart.
