### ISSUE TITLE
Charred Vale Grunt too down from the hill

### ISSUE THREAD

**Issue by Tuadii** [slowtorta/turtlewow-bug-tracker#4255]
**Please, provide a clear description what the bug is:**
36.6  68.3 a grunt from Charred Vale in Stonetalon peak killed my mage out of nowhere because an harpie  hit him with a spell while i was attacking the harpie and then it attacke me like if the mob was my pet.The harpie aimed the grunt when i first attacked it , i was fighting it but it decided to attack the grunt when the grunt wasnt even there

**Steps to reproduce the behavior with as much detail as possible:**

1.The grunt should be at 38.6 68.6 up the hill no at the bottom
2. The harpie damage it when it was casting me the spell
3. 

**IDs of affected creatures, items, quests or spells with a link to the relevant page:**

NPC: https://www.wowhead.com/classic/npc=7730/stonetalon-grunt and https://www.wowhead.com/classic/npc=4027/bloodfury-storm-witch#abilities
Item: https://database.turtle-wow.org/?item=
Quest: https://database.turtle-wow.org/?quest=
Spell: https://www.wowhead.com/classic/spell=1324/lightning-bolt
Object: https://database.turtle-wow.org/?object=

**Expected behavior. Describe how it should work:**
The grunt should be at the top of the road no so down , and the harpie aim the grunt when i first attacked the mob , i was fighting it but it decided to attack the grunt when the grunt wasnt even there at should never be in those coordinates

**Comment by twowTurtReynolds** [comment]
![image](https://github.com/slowtorta/turtlewow-bug-tracker/assets/151180101/24a34d53-6437-4ac7-8527-ee571a4d0d24)
On turtle and vmangos, the mobs are up the hill. This seems correct, but you didn't take any pictures for me to show exactly what you mean. Can you explain?
