### ISSUE TITLE
Horde AV backdoor still exist...

### ISSUE THREAD

**Issue by XiJongYeu** [slowtorta/turtlewow-bug-tracker#4257]
Since mountain jumping backdoor to get into Dun Baldar's alliance base in Alterac Valley has been solved, now some horde players have managed to keep doing it. Basically any class that have a "charge" ability, like warrior and druids, or even any engineer with goblin rocket helmet, can just charge to an npc near a hill in Dun Baldar, getting way too faster in to alliance Stormpike Aid Station. If it was already unfair with horde "backdoor jump" in Dun Baldar North Bunker now its much worse.

**Steps to reproduce the behavior with as much detail as possible:**

1. Go to av, near Dun Baldar's south bunker.
2. Target a random enemy npc in a hill.
3. Use your charge ability.
4. Or just do what druid akrapovic does.

https://github.com/slowtorta/turtlewow-bug-tracker/assets/108291948/54cfe490-df10-4ed6-be29-b0bcf57a04a8

**IDs of affected creatures, items, quests or spells with a link to the relevant page:**

NPC: https://database.turtle-wow.org/?npc=
Item: https://database.turtle-wow.org/?item=
Quest: https://database.turtle-wow.org/?quest=
Spell: https://database.turtle-wow.org/?spell=
Object: https://database.turtle-wow.org/?object=

It shouldnt be able.

**Comment by fatnerdynerd** [comment]
are there any other cases in the game where charge allows you to reach your target? I think the ability is broken like that. I suspect it will need a server restart to *checks notes* make charge not charge you towards an enemy in LoS anymore...?

**Comment by ConcernedTurtler** [comment]
An NPC should probably be moved but if they manage to do it to a player I think it's fine.

**Comment by twowTurtReynolds** [comment]
PVP Balancing suggestions belong on the suggestions forum.
