### ISSUE TITLE
Item duplication bug

### ISSUE THREAD

**Issue by Winningone** [slowtorta/turtlewow-bug-tracker#4258]
**Please, provide a clear description what the bug is:**
The Blackwater Cutlass was duplicated twice during my most recent group run through Deadmines. 

**Steps to reproduce the behavior with as much detail as possible:**

1. Any group member loots dead NPC and the group all selects greed to roll for the item
2. Second player shift+right clicks NPC with item at the same time the roll is determined by the server
3. The player who won the roll and the player who followed step 2 each get a copy of the item. In our group the same two players won both times. One was the tank who initially looted the dead NPC and the copy of the item went to the player who shift+right clicked on the NPC so this bug could also be effecting loot rolls.

**IDs of affected creatures, items, quests or spells with a link to the relevant page:**

NPC:
These are the NPC's which drop the item:
Defias Pirate: https://database.turtle-wow.org/?npc=657
Defias Squallshaper: https://database.turtle-wow.org/?npc=1732

Item:
Blackwater Cutlass - Item ID 1951
https://database.turtle-wow.org/?item=1951

**Expected behavior. Describe how it should work:**
Expected behavior is only a single version of the item is received by whichever player won the loot roll.

**Comment by twowTurtReynolds** [comment]
The staff haven't heard of a single other case of this race condition that you pulled off. Congrats on your one in a million experience.
