### ISSUE TITLE
Lost defender's Helmet clipping through human female hair.

### ISSUE THREAD

**Issue by IonizedRain** [slowtorta/turtlewow-bug-tracker#4259]
Hair clips straight through helmet.

**Steps to reproduce the behavior with as much detail as possible:**

1. Wear the helmet
2. N/A
3. N/A

Player
![report](https://github.com/slowtorta/turtlewow-bug-tracker/assets/116537123/edfea911-305e-4b38-9409-c7406dafee1d)

NPC: https://database.turtle-wow.org/?npc=
Item: https://database.turtle-wow.org/?item=
Quest: https://database.turtle-wow.org/?quest=
Spell: https://database.turtle-wow.org/?spell=
Object: https://database.turtle-wow.org/?object=

**Expected behavior. Describe how it should work:**

**Comment by twowTurtReynolds** [comment]
![image](https://github.com/slowtorta/turtlewow-bug-tracker/assets/151180101/260e5c29-9af5-4d41-a7f8-90c3b6556a7a)
