### ISSUE TITLE
[Skin Change Token: Blood Elf] does nothing.

### ISSUE THREAD

**Issue by Zangatsu** [slowtorta/turtlewow-bug-tracker#426]
The [Skin Change Token: Blood Elf] seems to do very very little, bordering on nothing at all. If the Dark Ranger skin is able to drastically alter every part of the model and give them dark orange eyes, I would hope that the blood elf token could at least give me green eyes. The only difference I notice is it gives me.. green eyeshadow.

https://forum.turtle-wow.org/viewtopic.php?f=14&t=2208

**Comment by slowtorta** [comment]
Thanks for repoting it. It'll be fixed on the next server update.
