### ISSUE TITLE
Fall of the Prophet item set class restriction

### ISSUE THREAD

**Issue by SabineWren** [slowtorta/turtlewow-bug-tracker#4260]
The Fall of the Prophet (aka Fallen Prophet) set is a Turtle custom three-piece set where the gloves include a shaman class restriction, but the other two pieces don't. This inconsistency appears an oversight. Either the boots and shoulders should both gain a shaman class restriction, or the gloves should lose the restriction.

https://database.turtle-wow.org/?item=21890
https://database.turtle-wow.org/?item=21705
https://database.turtle-wow.org/?item=21684

Related issue https://github.com/slowtorta/turtlewow-bug-tracker/issues/3695

**Comment by balakethelock** [comment]
The items existed in vanilla, they are not custom.
This is how they are supposed to be, only the gloves are restricted to shamans.

**Comment by SabineWren** [comment]
No, the vanilla gloves have healing instead of damage, and the shoulders aren't even related. This is a completely new spell damage set with new models and renamed shoulders. The class restriction is probably an artifact of vanilla faction loot balance for healing gear since Horde didn't have paladins and shamans can't wear plate.

**Comment by SabineWren** [comment]
Patch 1.17 [Changed](https://forum.turtle-wow.org/viewtopic.php?t=8230) the Girdle of Elemental Fury "Shaman Only restriction added in line with other pieces." i.e it was the only piece of the set that wasn't class restricted, which was inconsistent. By that same logic, Gloves of the Fallen Prophet are the odd one out of their set by having a class restriction.

**Comment by Dragunovi** [comment]
Removed class restrictions from both the plate and mail gauntlets. Should be applied in the next scheduled server restart.
