### ISSUE TITLE
Relearn Leatherworking Bug

### ISSUE THREAD

**Issue by Kirchlive** [slowtorta/turtlewow-bug-tracker#4262]
**Please, provide a clear description what the bug is:**

I unlearn Leatherworking skill, to change specialization. After relearn Leatherworking i get all Leatherworking devskills in my spellbook, see screenshot. After skilling Leatherworking to 75/75 i was unable to learn Journeyman/Expert Leatherworking due to because I "already known" it. 

**Steps to reproduce the behavior with as much detail as possible:**

I have to unlearn Leatherworking a second time before everything has been completely reset and able to relearn Leatherworking normaly.

**IDs of affected creatures, items, quests or spells with a link to the relevant page:**

[Screenshot](https://i.imgur.com/pavgZ7g.png)

**Comment by twowTurtReynolds** [comment]
Looks like I can no longer replicate:
![image](https://github.com/slowtorta/turtlewow-bug-tracker/assets/151180101/3f21f208-015f-4fd7-8071-b5726d97e229)
![image](https://github.com/slowtorta/turtlewow-bug-tracker/assets/151180101/dcf5c249-cd91-497f-b259-7de84de21044)
![image](https://github.com/slowtorta/turtlewow-bug-tracker/assets/151180101/da91d252-91c9-4eed-a7a0-2f95753cdb59)
