### ISSUE TITLE
Gurubashi Arena glitch

### ISSUE THREAD

**Issue by Jet1511** [slowtorta/turtlewow-bug-tracker#4264]
**Please, provide a clear description what the bug is:**

Players in the arena aren't flagged for pvp sometimes, this maybe cus ppl get unflagged after being in there for a while without attacking anyone.

**Steps to reproduce the behavior with as much detail as possible:**

1. Run in and out might trigger this
2. staying in there without attacking might
3. this ruins it as the chest gets looted by whoever can click it the fastest

**Expected behavior. Describe how it should work:**

I hope the arena flags everyone who enters for pvp, otherwise its cheating to be able to loot the chest without being flagged. 

![image](https://github.com/slowtorta/turtlewow-bug-tracker/assets/143958921/1c8700b6-9035-4fdc-8508-5b092f6491c6)

**Comment by Northyn** [comment]
"Players in the arena aren't flagged for pvp **sometimes**," The FFA effect doesn't apply to anyone from what I've noticed being at the arena for BR queues. Haven't seen the FFA effect apply at any given moment when attempting to grab the chest.

**Comment by Gnomestabber2** [comment]
Can confirm I've been FFA flagged outside of the of the arena and only been able to attack other players who also had the bug. If I went into the arena I became "ordinary" flagged.

**Comment by Rangtuk** [comment]
Also confirmed the same bug happens in the dire maul arena, something to due with server/client player location not properly detecting when someone passes the trigger wall to change their flags, possible solution is to have constant checking of someone's flag in their location/zone, as opposed to just whether they pass a trigger plane
