### ISSUE TITLE
+Elemental Dmg not procing JoW after Sept 4th reset

### ISSUE THREAD

**Issue by Bralbir** [slowtorta/turtlewow-bug-tracker#4270]
**Please, provide a clear description what the bug is:**

reset Paladins have been benefitting from getting JoW procs from +Elemental Dmg, ie Blazefury Medallion, Crimson Spellblade, Repaired Electro-Lantern, etc. Is this an intended stealth patch from reset?

**Steps to reproduce the behavior with as much detail as possible:**

1. equip +elemental damage weapons/armor
2. Judge target with Seal of Wisdom
3. Melee attacks should proc extra JoW mana regen with the +elemental damage from gear

**IDs of affected creatures, items, quests or spells with a link to the relevant page:**

**Expected behavior. Describe how it should work:**

Paladins have been benefitting from getting JoW procs on melee hits from +Elemental Dmg, ie Blazefury Medallion, Crimson Spellblade, Repaired Electro-Lantern, etc.

**Comment by Vynora** [comment]
I would like to add that they dont proc anything, including vengeance, clearcasting, wrath of cenarius, the +elemental damage is no longer considered as a spell hit.

**Comment by Vynora** [comment]
It is apparently fixed now. I could not test myself yet.
