### ISSUE TITLE
Warrior Whirlwind Quest NPC bugged

### ISSUE THREAD

**Issue by ptolememe** [slowtorta/turtlewow-bug-tracker#4279]
npc id: 6176
npc name: Bath'rah the Windwatcher
Quest: Cyclonian

NPC needs to be killed by a gm in order to reset. Then 1 person can start the quest or multiple people can turn it in.
Once somebody starts the quest a gm needs to reset it again.

**Comment by Haaxor1689** [comment]
Fixed
