### ISSUE TITLE
“Snatch and Grab”—Rogue Sub-quest Bug

### ISSUE THREAD

**Issue by Gallanthound** [slowtorta/turtlewow-bug-tracker#428]
**Please, provide a clear description what the bug is:**

**Steps to reproduce the behavior with as much detail as possible:**

1. There’s a bug during the rogue quest “Snatch and Grab in Goldshire that immediately alerts the npc while stealthed, which resulted in the death of my hardcore rogue. I want it confirmed and my hardcore status restored.

**IDs of affected creatures, items, quests or spells with a link to the relevant page:**

NPC: https://database.turtle-wow.org/?npc=
Item: https://database.turtle-wow.org/?item=
Quest: https://database.turtle-wow.org/?quest=
Spell: https://database.turtle-wow.org/?spell=
Object: https://database.turtle-wow.org/?object=

**Expected behavior. Describe how it should work:**

**Comment by gh-borz** [comment]
The bug is that stealth is broken on turtle wow. The issue is not the quest.

**Comment by Gallanthound** [comment]
Well I want it fixed. That’s ridiculous

**Comment by jameyboor** [comment]
Fixed.
