### ISSUE TITLE
Whirlwind Axe NPC, Bath'rah the Windwatcher, is not interactable. Warriors currently cannot do the quest(s).

### ISSUE THREAD

**Issue by stickymouth** [slowtorta/turtlewow-bug-tracker#4282]
Please, provide a clear description what the bug is:

Bath'rah the Windwatcher in Alterac Mountains cannot be interacted with in any way, whether to turn in steps of the Whirlwind weapon quest or to pick up new steps. Multiple warriors attempting to proceed with their quests noted this behavior. We all deleted WDB folders, relogged, disabled addons, and could not get the NPC to become responsive again.
_GMs are now informing players to submit tickets here on GitHub to escalate the issue to devs._

**Steps to reproduce the behavior with as much detail as possible:**

    1. Pick up final step of Whirlwind weapon quest to summon Cyclonian.
    2. Bath'rah will route towards the ruins, summon Cyclonian, then return to his original point.
    3. After this point, Bath'rah will be non-interactive to all players, regardless of which part of the chain they are on.

**IDs of affected creatures, items, quests or spells with a link to the relevant page:**

NPC: https://database.turtle-wow.org/?npc=6176
Quest: https://database.turtle-wow.org/?quest=1712
https://database.turtle-wow.org/?quest=1713
https://database.turtle-wow.org/?quest=1792

**Expected behavior. Describe how it should work:**

Bath'rah upon returning to his original point should resume his original NPC behavior, allowing players to speak with him and permitting the pickup and turnin of quests.

**Comment by twowTurtReynolds** [comment]
If this crops up again, please let us know.
