### ISSUE TITLE
Evermoon Staff can't be dischanted

### ISSUE THREAD

**Issue by hxlich** [slowtorta/turtlewow-bug-tracker#4289]
Evermoon Staff https://database.turtle-wow.org/?item=60112 can't be dischanted.

**Comment by twowTurtReynolds** [comment]
![image](https://github.com/slowtorta/turtlewow-bug-tracker/assets/151180101/103b2575-c0c8-4c60-a315-8228d4a91056)
Indeed. Since this is a one time quest reward, it should get the flag added.

**Comment by Dragunovi** [comment]
Should be fixed in the next scheduled server restart.
