### ISSUE TITLE
High Elf Capes visual bug

### ISSUE THREAD

**Issue by JustVityok** [slowtorta/turtlewow-bug-tracker#429]
https://database.turtle-wow.org/?item=50236
Visual bug with High Elf model as on screenshots
![WoWScrnShot_111021_084036](https://user-images.githubusercontent.com/93767462/141063443-494a82f7-99d7-414a-be1e-190a269ca58d.jpg)
![WoWScrnShot_111021_084030](https://user-images.githubusercontent.com/93767462/141063453-028147cf-1135-4f05-8e7a-7b75815fa119.jpg)
![Untitled-1](https://user-images.githubusercontent.com/93767462/141063816-378be898-9216-4e28-ba8b-7f98127092db.jpg)

It looks like ripped in half, and there were no such issues on other races (at least not on human)
UPD: I noticed that it happens with all long capes, not only Stormborn's one

**Comment by slowtorta** [comment]
Included in https://github.com/slowtorta/turtlewow-bug-tracker/issues/449
