### ISSUE TITLE
Shimmering Flats Racing Quests

### ISSUE THREAD

**Issue by Loon15** [slowtorta/turtlewow-bug-tracker#4290]
**Please, provide a clear description what the bug is:**
"Gnomes Are Genuine Inventors" and "Goblin Engineering at its Finest" both when accepted cannot be turned in to Dolores at the Shimmering Flats Raceway. 
**Steps to reproduce the behavior with as much detail as possible:**

1.Accept either quests
2. Go to Dolores for turn in
3. She is not spawned at her turn in location

**IDs of affected creatures, items, quests or spells with a link to the relevant page:**

NPC: https://database.turtle-wow.org/?npc=50533

Quest: https://database.turtle-wow.org/?quest=50312 and https://database.turtle-wow.org/?quest=50310

**Expected behavior. Describe how it should work:**
Should be able to complete at Dolores.

**Comment by twowTurtReynolds** [comment]
Tracking this under the dupe https://github.com/slowtorta/turtlewow-bug-tracker/issues/4813
