### ISSUE TITLE
T0.5 Mission - Vatarak Trinket Missing Top Half Cannot Craft Trinket to Complete Mission Help

### ISSUE THREAD

**Issue by Niuzijuda** [slowtorta/turtlewow-bug-tracker#4291]
**The top of Lord Valtarak's amulet is missing:**

**Steps to reproduce the behavior with as much detail as possible:**

1.When the boss summoned by the flag returned to the front door of the Eastern Plague Stansom to hand over the task after completing the request to go to the Blackstone Abyss Arena to kill and release the flag, the NPC took away the mission item The top of Lord Valtarak's amulet that the quest boss who killed in the Blackstone Abyss at that time 
2. After receiving the task of returning to Ogg with three career parts of the leg, shoulder, and shoe upgrade, during the mission, the NPC did not return the quest item obtained in the Blackstone Abyss from the previous mission, the top of the Lord Valtarak amulet
3. At the time, I didn't pay attention to it, thinking that it was a mission, so I continued with the following tasks, and when I did the task that required Stansom to kill two summoned bosses and Vatarak Trinkets 3 T0.5, it was stuck, and after summoning the boss to kill, I wanted Wattarak Trinkets left, right, and upper 3 parts to combine into one Vatarak Trinket to complete this task, and there was a missing upper prop

**IDs of affected creatures, items, quests or spells with a link to the relevant page:**

NPC: https://database.turtle-wow.org/?npc=16016
Item: https://database.turtle-wow.org/?item=22047
Quest: https://database.turtle-wow.org/?quest=9015
**This quest prop, Top Piece of Lord Valthalak's Amulet, is needed for subsequent missions**

**Comment by twowTurtReynolds** [comment]
I completed the quest that you linked, but what you described as to missing a side to complete the amulet, is not a part of that quest. Could you please clarify which exact quest you are on with a correct DB link?

You may also wish to contact a GM, as I don't think other players suffer from this problem.
