### ISSUE TITLE
Druid spell [Ferocious Bite] (Rank 5) are Bugged (solved)

### ISSUE THREAD

**Issue by Kirchlive** [slowtorta/turtlewow-bug-tracker#4292]
**Please, provide a clear description what the bug is:**

The Druid spell Ferocious Bite (Rank 5) are bugged. 
I'm assuming it only affects Rank 5 will be learned from Book of Ferocious Bite V.

By cast Ferocious Bite (min. of 35 energy to cast), all your energy will be drained to 0, no matter how much you have up to 100 energie. 
Even if in Clearcasting from Omen of Clarity skill. Which should allow you to cast it without energy use.

**Steps to reproduce the behavior with as much detail as possible:**

1. Attacking mob in Feral form to build combo points.
2. Have 1 to 5 combo points on mob and up to 35 to 100 energie.
3. Using Ferocious Bite (Rank 5). Energie is every time on 0 after using it. Even if in Clearcasting from Omen of Clarity skill.

**IDs of affected creatures, items, quests or spells with a link to the relevant page:**

Ferocious Bite Rank 5 - https://database.turtle-wow.org/?spell=31018
Book of Ferocious Bite V - https://database.turtle-wow.org/?item=24101
Omen of Clarity - https://database.turtle-wow.org/?spell=16864
Clearcasting - https://database.turtle-wow.org/?spell=12536

**Expected behavior. Describe how it should work:**

Like all other Ferocious Bite ranks, Ferocious Bite (Rank 5) should always subtract 35 energy from the total energy by cast.
Like all other Ferocious Bite ranks, Ferocious Bite (Rank 5) should cast without energy use if in Clearcasting from Omen of Clarity skill.

**Comment by Kirchlive** [comment]
Looking on wowhead its not a turtle spell. Just a normal classic spell but still bugged.

**Comment by Kirchlive** [comment]
no bug, mb.

**Comment by twowTurtReynolds** [comment]
> no bug, mb.

No bug? Was it just a misunderstanding? Ping me if it really is something to look into.
