### ISSUE TITLE
Grifter's boots soulbinds automatically making it impossible to trade to other players wanting it 

### ISSUE THREAD

**Issue by nachomantaco** [slowtorta/turtlewow-bug-tracker#4293]
**Please, provide a clear description what the bug is:**
Grifter's boots soul binds automatically making it impossible to trade to other players wanting it 

https://database.turtle-wow.org/?item=83405

Rest of the set is tradable is this bug? 

How are you supposed to play with the entire set combo if you cant equip the missing piece as a non LW  

Thank you goodbye <3

**Comment by Oolaatris** [comment]
This has happened to at least one other custom crafted set, the idea is to have the full set be a bonus for players with that crafting profession while not locking other people from the whole set.  So one piece is BOP while the rest is BOE.

**Comment by nachomantaco** [comment]
Stupid way

**Comment by cyaohiri** [comment]
This is intended. See #1805.

**Comment by twowTurtReynolds** [comment]
Duplicate of https://github.com/slowtorta/turtlewow-bug-tracker/issues/1805
