### ISSUE TITLE
Bael Hardul Inn does not grant rested exeprience

### ISSUE THREAD

**Issue by Sylvare3** [slowtorta/turtlewow-bug-tracker#4294]
**Please, provide a clear description what the bug is:**
The inn in Bael Hardul does not grant rested experience, this is despite being able to set your Hearthstone here, with it presumably meant to act like a inn anywhere else in Azeroth.
**Steps to reproduce the behavior with as much detail as possible:**

1. Inn building in Bael Hardul, Stonetalon Mountains. Go there

**IDs of affected creatures, items, quests or spells with a link to the relevant page:**

NPC: https://database.turtle-wow.org/?npc=60991

**Expected behavior. Describe how it should work:**
If this is not intentional or a issue with custom content inns, it should allow the player to generate rested exp as the other inns and taverns in the game do.

**Comment by Dragunovi** [comment]
Fixed in 1.17.0.
