### ISSUE TITLE
Gillijim Isle zone bug

### ISSUE THREAD

**Issue by Zolef1** [slowtorta/turtlewow-bug-tracker#4297]
**Please, provide a clear description what the bug is: When swimming near the boats in Gillijim isle for the quest to kill 3 different pirate leaders, you zone into Stranglethorn vale. If you die on the boat/when zoned into STV, you get ported to Booty bay as a ghost. 

This means you must take ressurection sickness.

**Steps to reproduce the behavior with as much detail as possible:**

1. Swim close to the boats
2. Check if you get the "entering STV" text
3. Die

**IDs of affected creatures, items, quests or spells with a link to the relevant page: no real items or anything involved

NPC: https://database.turtle-wow.org/?npc=
Item: https://database.turtle-wow.org/?item=
Quest: https://database.turtle-wow.org/?quest=
Spell: https://database.turtle-wow.org/?spell=
Object: https://database.turtle-wow.org/?object=

**Expected behavior. Describe how it should work: probably make it so that your ghost spawns next to your corpse, like in the rest of the zone

**Comment by twowTurtReynolds** [comment]
The water outside the boats seem fine though:
![image](https://github.com/slowtorta/turtlewow-bug-tracker/assets/151180101/e2488191-8dbe-4cff-aa9c-3a9da1dcdd75)

If you can show me exactly where the issue is, please reply.
