### ISSUE TITLE
Vengeance rank 4/5 not working

### ISSUE THREAD

**Issue by redlynx** [slowtorta/turtlewow-bug-tracker#43]
**Current behavior**: 
Vengeance rank 4 does not proc on critical hits. Sample screenshots attached. Happened with a Dwarf Paladin in the Badlands (just tested there)
![rank4of5](https://user-images.githubusercontent.com/2453570/121843489-2c485d00-cc97-11eb-8d43-7b11e18d6b4f.png)

**Expected behavior**: 
Vengeance should proc on every critical hit.
![rank5of5](https://user-images.githubusercontent.com/2453570/121843498-32d6d480-cc97-11eb-80e8-833d93dbb00f.png)

**Proofs**:
See screenshots above. Issue captured on  2021-06-11 at approx. 2pm PDT.

**Steps to reproduce**:

1. Invest 4 skill points in Vengeance
2. Score a critical hit
3. Observe Vengeance buff not being applied to character.

**Comment by Velite12** [comment]
It did work for me I just tested with 4/5, got it to proc on a crit.

**Comment by Nolin7777** [comment]
Cannot reproduce
