### ISSUE TITLE
Cannot Interact with Niby the Almighty (Warlock Infernal Quest)

### ISSUE THREAD

**Issue by BinarySoup** [slowtorta/turtlewow-bug-tracker#4301]
**Please, provide a clear description what the bug is:**

Unable to interact with Niby the Almighty in Felwood, preventing the turn in of Warlock Infernal Quest.

The first in-game ticket I opened, a GM manually added the starting quest to my quest log. Now I am unable to turn in the final quest: "Kroshius' Infernal Core".

**Steps to reproduce the behavior with as much detail as possible:**

1. Be Warlock
2. Be over level 50
3. Attempt to interact with Niby the Almighty (Yellow Question Mark Above Head). 
4. No dialog box appears when clicked.

**IDs of affected creatures, items, quests or spells with a link to the relevant page:**

NPC: https://database.turtle-wow.org/?npc=14469
Item: https://database.turtle-wow.org/?item=18625
Quest: https://database.turtle-wow.org/?quest=7603
Spell: https://database.turtle-wow.org/?spell=
Object: https://database.turtle-wow.org/?object=

**Expected behavior. Describe how it should work:**

I should be able to interact  with the NPC, and complete the quest as I meet all of the prerequisites.

**Comment by cyrylkuzmin** [comment]
I've got the same problem today

**Comment by arsxgoetia** [comment]
Same issue with my lock lvl 56.
@BinarySoup @cyrylkuzmin

**Comment by twowTurtReynolds** [comment]
![image](https://github.com/slowtorta/turtlewow-bug-tracker/assets/151180101/a3a97ee3-8f15-4665-84c7-89b846a432b6)

I believe you two, but these replication steps do not work. Please let me know if you can figure them out.
