### ISSUE TITLE
In Dreams Quest Turn in bug

### ISSUE THREAD

**Issue by Hightimes504** [slowtorta/turtlewow-bug-tracker#4302]
**Please, provide a clear description what the bug is:** Once I completed the escort and the battle at the tower happened Tieron (not sure how to spell) did not show up for me to turn in quest. The quest shows complete in my quest log but wasnt able to turn in.

**Steps to reproduce the behavior with as much detail as possible:**

1. Im not sure as the quest did not play alll the way out for me to turn in
2. 
3. 

**IDs of affected creatures, items, quests or spells with a link to the relevant page:**

NPC: https://database.turtle-wow.org/?npc=12126
Item: https://database.turtle-wow.org/?item=
Quest: https://database.turtle-wow.org/?quest=5944
Spell: https://database.turtle-wow.org/?spell=
Object: https://database.turtle-wow.org/?object=

**Expected behavior. Describe how it should work:**

**Comment by ratkosrb** [comment]
How did you even complete it if Tirion didn't show up? It only completes once Tirion kills Issilien.

**Comment by twowTurtReynolds** [comment]
Closing, no response in 3 months.
