### ISSUE TITLE
Safe spots Zul'Farrak dont work, Please have a look it. This is a very important farming spot for mages!

### ISSUE THREAD

**Issue by legion420** [slowtorta/turtlewow-bug-tracker#4307]
**Please, provide a clear description what the bug is:**

In classic wow you should be able to run trough ZF (Zul'Farrak) and hide at different safe spots for the mobs to reset. After this you can continue your way to the graveyard, activate boss pull the graves mobs should go to the bos and you hide at a save spot agian. This way a mage should be able to pull it. Now i tried it a vew times but none of these safe sport work. I link a youtube video of the pull https://www.youtube.com/watch?v=eBx8xOh_Qro&t

**Expected behavior. Describe how it should work:**

it should work like this: https://www.youtube.com/watch?v=eBx8xOh_Qro&t

**Comment by balakethelock** [comment]
This is intended to deter from crazy aoe pulling and skipping long stretches of dungeon zones.

Besides it would be almost impossible to replicate classic wow's pathing because private servers have to use an open source program to generate pathing maps, blizzard has its own closed source method.

**Comment by legion420** [comment]
Thanks for the info. This explanes alot! So it has been nerfed in short XD. Now i know i dont have to try it agian :)

**Comment by legion420** [comment]
> This is intended to deter from crazy aoe pulling and skipping long stretches of dungeon zones.
> 
> Besides it would be almost impossible to replicate classic wow's pathing because private servers have to use an open source program to generate pathing maps, blizzard has its own closed source method.

Thanks for the info. This explanes alot! So it has been nerfed in short XD. Now i know i dont have to try it agian :)

**Comment by ratkosrb** [comment]
It is impossible to recreate Blizzard's pathing algorithm exactly. You should not expect pathing behavior to be exactly the same.
