### ISSUE TITLE
Hateforge Quarry mob's stealth detection

### ISSUE THREAD

**Issue by Sringaram** [slowtorta/turtlewow-bug-tracker#4308]
Everything inside has abnormally high stealth detection for their level and also seems to ignore all +stealth skill bonuses.

Even the level <50 mobs have higher stealth detection than most level 60 stuff and often times will detect you even when you're moving behind them, this seems to happen often with the overseers.

Stealth skill bonuses from talents, gear and the improved stealth buff from vanish do not seem to help in any way, as if those bonuses are simply ignored.

**Comment by Datedb** [comment]
i have never had issues stealthing thru HFQ

**Comment by Aegael** [comment]
I noticed the mobs outside having irregular stealth detection. I wasn't sure if it was latency but there was something noticeable there. I didn't have any problems with the mobs inside the instance, but didn't really test either.

**Comment by Sringaram** [comment]
> i have never had issues stealthing thru HFQ

Could it be that druid's prowl is treated the differently?

**Comment by Sringaram** [comment]
Anyway my report stands true. Mobs in this instance both have abnormally high stealth detection, higher than level 60 mobs and completely ignore stealth level bonuses.

I've tried with 5/5 MoD and +16 from gear and it makes zero difference.

**Comment by Sringaram** [comment]
I feel like this may be linked not so much to the stealth detection itself but the timers responsible for the detection. 
I noticed that sprinting past those same mobs doesn't make them turn around towards me like it happens when moving normally.

Maybe the timers responsible for the mobs gradually detecting you when you're close are way shorter than they should be. It would explain the spastics behavior.

**Comment by Sringaram** [comment]
So will this be fixed?
