### ISSUE TITLE
The Widow's embrace has the wrong colour

### ISSUE THREAD

**Issue by l453rl453r** [slowtorta/turtlewow-bug-tracker#4309]
The model of the healing mace, The Widow's Embrace (https://database.turtle-wow.org/?item=22942) has wrong colours. it supposed to be golden, not bronze.
this is how it looks on twow:
![image](https://github.com/slowtorta/turtlewow-bug-tracker/assets/24902382/72eae5be-4b3c-4e0b-b288-2d2ed2072c31)
this is how it's supposed to look:
![3091-the-widows-embrace](https://github.com/slowtorta/turtlewow-bug-tracker/assets/24902382/3ae75c94-af4d-4216-b032-d1e87b5e9f2b)

**Comment by balakethelock** [comment]
The screenshots are using different enchants, they glow differently. Also the lighting is different.

The color of the weapon is the same, it only looks different to you.

**Comment by l453rl453r** [comment]
Nope, same enchants. And no, it's not just me, everyone can see it, it's very obvious. Im the character screen it also gets displayed correctly.

**Comment by ratkosrb** [comment]
The item is using the correct display id. Any differences you see are due to lighting.
