### ISSUE TITLE
Mulgore underground copper vein

### ISSUE THREAD

**Issue by Yurius1** [slowtorta/turtlewow-bug-tracker#4310]
**Please, provide a clear description what the bug is:**

**Steps to reproduce the behavior with as much detail as possible:**

1. Go to Mulgore 33.4, 70.2
2. Swich on "Find minerals"
3. I cant see vein, but if I see change in mouse cursor, that shows me mining - i can mine it

https://database.turtle-wow.org/?object=1731

**Expected behavior. Describe how it should work:**
Vein must be visible

**Comment by Muigin** [comment]
Please make a ticket in-game when you find these nodes so a GM can fix them in real-time.
