### ISSUE TITLE
It's possible to have more than one ring from Brood of Nozdormu rep [... of Bronze Dragonflight]

### ISSUE THREAD

**Issue by gala320** [slowtorta/turtlewow-bug-tracker#4315]
**Please, provide a clear description what the bug is:**
It is possible to have more than one ring from Brood of Nozdormu in your inventory, on different rep level. Just saw a player have TWO +defense rings equipped, respectively from Revered and Exalted reputation tier.
I was instructed to post the issue here by a GM as well regarding this issue.

**Steps to reproduce the behavior with as much detail as possible:**

I have no idea how that specific person managed to achieve that. I just know you are not supposed to have two of those rings :P

**IDs of affected creatures, items, quests or spells with a link to the relevant page:**

NPC: https://database.turtle-wow.org/?npc=50550
Item: https://database.turtle-wow.org/?item=21200
Quest: https://database.turtle-wow.org/?quest=8747 or any other related to the ring reward from Anachronos NPC.

**Expected behavior. Describe how it should work:**
The player should be able to receive only ONE ring as a reward for reaching respective Brood of Nozdormu rep level.

**Comment by balakethelock** [comment]
It uses the item restoration npc in ratchet
