### ISSUE TITLE
Mirage Raceway Won't start

### ISSUE THREAD

**Issue by Feelsfunky** [slowtorta/turtlewow-bug-tracker#4316]
**Please, provide a clear description what the bug is:**
I just tried playing first Mirage Raceway race ever. I tried getting into either Goblin or Gnome race car, but NPC "Dolores" won't show me clickable dialog option to actually get into a car.

**Steps to reproduce the behavior with as much detail as possible:**

1.
2. 
3. 

**IDs of affected creatures, items, quests or spells with a link to the relevant page:**

NPC: https://database.turtle-wow.org/?npc=
Item: https://database.turtle-wow.org/?item=
Quest: https://database.turtle-wow.org/?quest=
Spell: https://database.turtle-wow.org/?spell=
Object: https://database.turtle-wow.org/?object=

**Expected behavior. Describe how it should work:**

**Comment by slowtorta** [comment]
Duplicate bug.
