### ISSUE TITLE
The Inn at Tel. co Basecamp

### ISSUE THREAD

**Issue by Zolef1** [slowtorta/turtlewow-bug-tracker#4318]
**Please, provide a clear description what the bug is: No rested from the inn

**Steps to reproduce the behavior with as much detail as possible:**

1. Go into the inn
2.  Im not getting rested status
3. 

**IDs of affected creatures, items, quests or spells with a link to the relevant page:**

NPC: https://database.turtle-wow.org/?npc=
Item: https://database.turtle-wow.org/?item=
Quest: https://database.turtle-wow.org/?quest=
Spell: https://database.turtle-wow.org/?spell=
Object: https://database.turtle-wow.org/?object=

**Expected behavior. Describe how it should work: The Inn should most likely give rested xp status, like all other inns in Azeroth.

**Comment by slowtorta** [comment]
![image](https://github.com/slowtorta/turtlewow-bug-tracker/assets/66763404/879ccccb-1460-4bdb-ad3d-a6dcf4b07f91)
The inn is the other building on the left.
