### ISSUE TITLE
Hurricane pushback with Owlkin Frenzy

### ISSUE THREAD

**Issue by Artalos330** [slowtorta/turtlewow-bug-tracker#4319]
**Please, provide a clear description what the bug is:**
As a Druid, when being in Moonkin Form and having the buff "Owlkin Frenzy", Hurricane still gets pushback when hit. I know it's a different wording on Barkskin. But while Barkskin is active, there's no pushback on Hurricane.
**Steps to reproduce the behavior with as much detail as possible:**

1. Be in Moonkin Form and get hit until Owlkin Frenzy procs.
2. Channel Hurricane.
3. Get hit.
4. "Suffer" pushback.

**IDs of affected creatures, items, quests or spells with a link to the relevant page:**

Owlkin Frenzy: https://database.turtle-wow.org/?spell=45734
Huricane: https://database.turtle-wow.org/?spell=17402

**Expected behavior. Describe how it should work:**
There should be no pushback on Hurricane with Owlkin Frenzy.

**Comment by twowTurtReynolds** [comment]
![image](https://github.com/slowtorta/turtlewow-bug-tracker/assets/151180101/5c31d161-8a67-4deb-9fff-66d7c5ce0c27)
![image](https://github.com/slowtorta/turtlewow-bug-tracker/assets/151180101/3816b43e-5fd7-4be4-9a6c-21799e9b6f8e)

Seems like this was fixed now? Both rank 1 and rank 3 work.
