### ISSUE TITLE
Blackwing Taskmasters Healing Circle heals players

### ISSUE THREAD

**Issue by Lunkdunk** [slowtorta/turtlewow-bug-tracker#432]
**Please, provide a clear description what the bug is:**
Blackwing Taskmasters now heal players for 20k with Healing Circle. They should only heal other mobs.
**Steps to reproduce the behavior with as much detail as possible:**
Go into supression room, see if you get healed. Logs: https://legacyplayers.com/viewer/14390/base?history_state=1
**IDs of affected creatures, items, quests or spells with a link to the relevant page:**

NPC: https://database.turtle-wow.org/?npc=12458
Item: https://database.turtle-wow.org/?item=
Quest: https://database.turtle-wow.org/?quest=
Spell: https://database.turtle-wow.org/?spell=22458
Object: https://database.turtle-wow.org/?object=

**Expected behavior. Describe how it should work:**

**Comment by perl1743** [comment]
Looks like it's *only* healing hostile-to-caster targets (as opposed to the spell targeting every entity).
![image](https://user-images.githubusercontent.com/2818608/141349929-f78e43ac-695a-46e2-9649-63f758cee141.png)
11/10 12:30:42.080  Nook gains 39 Mana from Heaven 's Greater Blessing of Wisdom.
11/10 12:30:42.080  Blackwing Taskmaster 's Healing Circle fails. Fire Resistance Totem III is immune.
11/10 12:30:42.080  Blackwing Taskmaster 's Healing Circle fails. Strength of Earth Totem IV is immune.
11/10 12:30:42.080  Blackwing Taskmaster 's Healing Circle fails. Fire Resistance Totem III is immune.
11/10 12:30:42.080  Blackwing Taskmaster 's Healing Circle fails. Windfury Totem III is immune.
11/10 12:30:42.080  Blackwing Taskmaster 's Healing Circle fails. Strength of Earth Totem IV is immune.
11/10 12:30:42.080  Blackwing Taskmaster 's Healing Circle fails. Windfury Totem III is immune.
11/10 12:30:42.080  Blackwing Taskmaster 's Healing Circle fails. Fire Resistance Totem III is immune.
11/10 12:30:42.080  Blackwing Taskmaster 's Healing Circle fails. Strength of Earth Totem IV is immune.
11/10 12:30:42.080  Blackwing Taskmaster 's Healing Circle fails. Windfury Totem III is immune.
11/10 12:30:42.080  Blackwing Taskmaster 's Healing Circle heals Asghan for 20000.
11/10 12:30:42.080  Blackwing Taskmaster 's Healing Circle heals Legenjerry for 20000.
11/10 12:30:42.080  Blackwing Taskmaster 's Healing Circle heals Shivva for 20000.
11/10 12:30:42.080  Blackwing Taskmaster 's Healing Circle heals Special for 20000.
11/10 12:30:42.080  Blackwing Taskmaster 's Healing Circle heals Lavender for 20000.
11/10 12:30:42.080  Blackwing Taskmaster 's Healing Circle heals Dragunovi for 20000.
11/10 12:30:42.080  Blackwing Taskmaster 's Healing Circle heals Shamhammer for 20000.
11/10 12:30:42.080  Blackwing Taskmaster 's Healing Circle heals Talida for 20000.
11/10 12:30:42.080  Blackwing Taskmaster 's Healing Circle heals Grend for 20000.
11/10 12:30:42.080  Blackwing Taskmaster 's Healing Circle heals Schwarz for 20000.
11/10 12:30:42.080  Blackwing Taskmaster 's Healing Circle heals Galpala for 20000.
11/10 12:30:42.080  Blackwing Taskmaster 's Healing Circle heals Fallout for 20000.
11/10 12:30:42.080  Blackwing Taskmaster 's Healing Circle heals Reman for 20000.
11/10 12:30:42.080  Blackwing Taskmaster 's Healing Circle heals Razzor for 20000.
11/10 12:30:42.080  Blackwing Taskmaster 's Healing Circle heals Nook for 20000.
11/10 12:30:42.095  Blackwing Taskmaster 's Healing Circle heals Sectivara for 20000.
11/10 12:30:42.095  Blackwing Taskmaster 's Healing Circle heals Gclipse for 20000.
11/10 12:30:42.095  Blackwing Taskmaster 's Healing Circle heals Amelyna for 20000.
11/10 12:30:42.095  Blackwing Taskmaster 's Healing Circle heals Frostyfyre for 20000.
11/10 12:30:42.095  Blackwing Taskmaster 's Healing Circle heals Emerelle for 20000.
11/10 12:30:42.095  Blackwing Taskmaster 's Healing Circle heals Bagz for 20000.
11/10 12:30:42.095  Blackwing Taskmaster 's Healing Circle heals Piranesi for 20000.
11/10 12:30:42.095  Blackwing Taskmaster 's Healing Circle heals Urd for 20000.
11/10 12:30:42.095  Blackwing Taskmaster 's Healing Circle heals Fruyan for 20000.
11/10 12:30:42.095  Blackwing Taskmaster 's Healing Circle heals Heaven for 20000.
11/10 12:30:42.095  Blackwing Taskmaster 's Healing Circle heals Alde for 20000.
11/10 12:30:42.095  Blackwing Taskmaster 's Healing Circle heals Ogga for 20000.
11/10 12:30:42.095  Blackwing Taskmaster 's Healing Circle heals Midgarean for 20000.
11/10 12:30:42.095  Blackwing Taskmaster 's Healing Circle heals Dole for 20000.
11/10 12:30:42.095  Blackwing Taskmaster 's Healing Circle heals Taliya for 20000.
11/10 12:30:42.095  Blackwing Taskmaster 's Healing Circle heals Tobbsu for 20000.
11/10 12:30:42.095  Blackwing Taskmaster 's Healing Circle heals Mauler for 20000.
11/10 12:30:42.095  Blackwing Taskmaster 's Healing Circle heals Morbide for 20000.
11/10 12:30:42.095  Blackwing Taskmaster 's Healing Circle heals Llimme for 20000.
11/10 12:30:42.224  Dragunovi gains 39 Mana from Heaven 's Greater Blessing of Wisdom.
