### ISSUE TITLE
quest bug

### ISSUE THREAD

**Issue by Zedoggy** [slowtorta/turtlewow-bug-tracker#4322]
**Please, provide a clear description what the bug is:i can't pick up any quests from the NPC called Inunquaq at darkshore...i do't know why...i search it on Twow datebase..and it said there is a quest called Crawling for Meat from Inunquaq...and my friend had done this quest ..but for me .i even can't pick up...Inunquaq gives me no quest

**Steps to reproduce the behavior with as much detail as possible:*

1.can't pick up any quests from the NPC called Inunquaq at darkshore
2. quest called Crawling for Meat
3. 

**IDs of affected creatures, items, quests or spells with a link to the relevant page:**

NPC: https://database.turtle-wow.org/?npc=81046
Item: https://database.turtle-wow.org/?item=60470
Quest: https://database.turtle-wow.org/?quest=80391
Spell: https://database.turtle-wow.org/?spell=
Object: https://database.turtle-wow.org/?object=

**Expected behavior. Describe how it should work:**  i want to pick the quest <Crawling for Meat>
>

**Comment by Muigin** [comment]
Not enough information to reproduce.
