### ISSUE TITLE
An Infinite Hunt

### ISSUE THREAD

**Issue by seryah** [slowtorta/turtlewow-bug-tracker#4329]
Cannot trigger event of the quest. Cannot finish the quest.

1.  Accept the quest
2.  Go to the crystal
3.  Cannot trigger the event, crystal is not clickable.

NPC: https://database.turtle-wow.org/?npc=Antnormi](https://database.turtle-wow.org/?npc=60373
Quest: https://database.turtle-wow.org/?quest=](https://database.turtle-wow.org/?quest=80411

You're supposed to click the crystal to trigger the event for Antnormi to spawn in.

**Comment by Muigin** [comment]
Duplicate of #3650
