### ISSUE TITLE
Bloodscalp Clan Heads quest npc "Gan'zulah" seems broken or overtuned.

### ISSUE THREAD

**Issue by BigHead2615** [slowtorta/turtlewow-bug-tracker#433]
**Please, provide a clear description what the bug is:**
I lost my level 39 hardcore shaman (along with my friend and her level 39 hc druid) to the level 41 non-elite NPC "Gan'zulah" in Stranglethorn Vale while working on the quest "Bloodscalp Clan Heads", after 2 or 3 hits I was 2/3 dead and couldn't heal either of us through it before we died.
**Steps to reproduce the behavior with as much detail as possible:**
I mean, I asked about this on the discord and someone else, Zaas, took their level 60 out there to fight the NPC and confirmed it is too hard or broken or what ever (suggested I report it), was killed in about 30 seconds, apparently "he's doing like 10x the damage of the surrounding mobs", and "his mainhand hitting 120s and offhand 90s, every 1 second each"; I suppose go and fight the NPC for yourself, might get more accurate info or details.

**IDs of affected creatures, items, quests or spells with a link to the relevant page:**

NPC: https://database.turtle-wow.org/?npc=1061
Item: https://database.turtle-wow.org/?item=
Quest: https://database.turtle-wow.org/?quest=584
Spell: https://database.turtle-wow.org/?spell=
Object: https://database.turtle-wow.org/?object=

**Expected behavior. Describe how it should work:**
I guess I just don't understand how two level 39 hc's can't live through a non-elite quest involving a level 41 NPC (we were able to kill level 42 and 43 mobs out in Tanaris at level 39 with no issues, while attempting to work on cooking quest), and no, not asking to get our hc's revived or anything, but it would be nice to be able to quest and level without having to be scared or paranoid if a non-elite quest will kill us or not, and having to check the turtle wow database on everything.

**Comment by Kangaroux** [comment]
Can confirm. Almost lost a 46 HC priest to him.

**Comment by slowtorta** [comment]
Thanks fo reporting it. This will be fixed on the next server update!
