### ISSUE TITLE
AB bonus honor not working

### ISSUE THREAD

**Issue by kepilifb** [slowtorta/turtlewow-bug-tracker#4332]
**Please, provide a clear description what the bug is:**

When there is Arathi Basin battleground day, reputation nor honor is doubled as it should be.

**Steps to reproduce the behavior with as much detail as possible:**
Queue Arathi Basin, observe honor/reputation ticks.

1. no AB bonus day 227 honor/11 rep
2. AB bonus day 227 honor/11 rep
3. 

**IDs of affected creatures, items, quests or spells with a link to the relevant page:**

NPC: https://database.turtle-wow.org/?npc=
Item: https://database.turtle-wow.org/?item=
Quest: https://database.turtle-wow.org/?quest=
Spell: https://database.turtle-wow.org/?spell=
Object: https://database.turtle-wow.org/?object=

**Expected behavior. Describe how it should work:**
O AB bonus day ticks should be 454/22

**Comment by ratkosrb** [comment]
https://github.com/slowtorta/turtle-wow/commit/258fefe92c105705f690f5ed0cf95e7c46a0cd11
