### ISSUE TITLE
Elemental Sharpening Stones Not Working

### ISSUE THREAD

**Issue by Trixminnie** [slowtorta/turtlewow-bug-tracker#4333]
Elemental Sharpening Stones Not Working

**Steps to reproduce the behavior with as much detail as possible:**

1. Whenever you apply an elemental sharpening stone to a weapon, it doesn't give you the 2% critical strike.
2. You can apply the sharpening stone to your weapon but when you look at your stats, it doesn't add the 2% crit.
3. 

Elemental Sharpening Stone - Display ID: 21072

NPC: https://database.turtle-wow.org/?npc=
Elemental Sharpening Stone - Display ID: 21072
Quest: https://database.turtle-wow.org/?quest=
Spell: https://database.turtle-wow.org/?spell=
Object: https://database.turtle-wow.org/?object=

When you use an elemental sharpening stone and then look at your stats it should add 2% to your critical strike stat.

**Comment by ratkosrb** [comment]
https://github.com/slowtorta/turtle-wow/commit/2cfa7366abb2842de2016b02f8c65a75add86ace

**Comment by Trixminnie** [comment]
Is this fixed or not? This link doesn't work.

**Comment by balakethelock** [comment]
> Is this fixed or not? This link doesn't work.

wait for the maintenance patch. Usually happens in wednesday but it seems they delayed it this time.

**Comment by Trixminnie** [comment]
o ok, ty
