### ISSUE TITLE
No quests for Stormwind Vault available for Horde players.

### ISSUE THREAD

**Issue by wemo228** [slowtorta/turtlewow-bug-tracker#4334]
**Please, provide a clear description what the bug is:**

**Steps to reproduce the behavior with as much detail as possible:**

1. As a horde player i tried to pick up quests listed down below and didn't get any success.
2.  Other horde players also tried to pick up quests - no luck. Alliance player tried to share it with us (he was successful at picking it up) and nothing happened.
3. I delete WDB, I do relogging, I wasn't in a raid. 

**IDs of affected creatures, items, quests or spells with a link to the relevant page:**

NPC: https://database.turtle-wow.org/?npc=80450
NPC: https://database.turtle-wow.org/?npc=80451

Quest: https://database.turtle-wow.org/?quest=40427
Quest: https://database.turtle-wow.org/?quest=40426

**Expected behavior. Describe how it should work:**

**Comment by ratkosrb** [comment]
https://github.com/slowtorta/turtle-wow/commit/5309ce36c8151a40479e617a45e74d40c99012c1

**Comment by wemo228** [comment]
404 - can't open this link.

**Comment by balakethelock** [comment]
> 404 - can't open this link.

The link is for the other twow devs when they check this issue to know the exact commit.
Means the bug is fixed and the fix will be implemented in the next maintenance patch.
