### ISSUE TITLE
Darnassus Reputation - Unable to Gain

### ISSUE THREAD

**Issue by lilcrinkle** [slowtorta/turtlewow-bug-tracker#4335]
**Please, provide a clear description what the bug is:**
I am stuck at 19399/21000 (revered) reputation with Darnassus. Turning in Morrowgrain and Runecloth do not increase my reputation any farhtter. I've already deleted WDB folder and nothing has changed. I wasted a decent amount of gold buying the turn in items without noticing I wasn't gaining any reputation.

**Steps to reproduce the behavior with as much detail as possible:**

1.
2. 
3. 

**IDs of affected creatures, items, quests or spells with a link to the relevant page:**

NPC: https://database.turtle-wow.org/?npc=
Item: https://database.turtle-wow.org/?item=
Quest: https://database.turtle-wow.org/?quest=
Spell: https://database.turtle-wow.org/?spell=
Object: https://database.turtle-wow.org/?object=

**Expected behavior. Describe how it should work:**

**Comment by ratkosrb** [comment]
https://github.com/slowtorta/turtlewow-bug-tracker/assets/35845488/fac9ead6-38ed-4cc1-94a9-9412796a096a

I can't reproduce the problem. I turned in Runecloth all the way to exalted.
