### ISSUE TITLE
frost oil

### ISSUE THREAD

**Issue by ozzymagnum** [slowtorta/turtlewow-bug-tracker#4336]
**Please, provide a clear description what the bug is:**

**Steps to reproduce the behavior with as much detail as possible:**

1. frost oil is proccing all the time when you play paladin making it impossible to run away
2. 
3. 

**IDs of affected creatures, items, quests or spells with a link to the relevant page:**

NPC: https://database.turtle-wow.org/?npc=
Item: https://database.turtle-wow.org/?item=
Quest: https://database.turtle-wow.org/?quest=
Spell: https://database.turtle-wow.org/?spell=
Object: https://database.turtle-wow.org/?object=

**Expected behavior. Describe how it should work:**

**Comment by Hambeast324** [comment]
The code needs fixed on Frost Oil. Its proccing at frost bolt range when paladins just have auto attack on. Its making Battlegrounds like Blood Ring completely unplayable.

**Comment by twowTurtReynolds** [comment]
The bug tracker is **not** the place for gameplay balance suggestions.
