### ISSUE TITLE
Skill Bugs

### ISSUE THREAD

**Issue by skysskyddd** [slowtorta/turtlewow-bug-tracker#4337]
**Please, provide a clear description what the bug is:**
I learned Great Stamina and Natural Stamina Rank 1 and 2 from my pet trainer, but these skills are not in my character's training beasts
 my account：sun635210                   character name：Kpamumu
**Steps to reproduce the behavior with as much detail as possible:**
1.First  learn the skills of rank 2, 
2. then  learn the skills of rank 1
3. I was trying to learn for my pet when I realized there was no

**IDs of affected creatures, items, quests or spells with a link to the relevant page:**

NPC: https://database.turtle-wow.org/?npc=
Item: https://database.turtle-wow.org/?item=
Quest: https://database.turtle-wow.org/?quest=
Spell: https://database.turtle-wow.org/?spell=
Object: https://database.turtle-wow.org/?object=

**Expected behavior. Describe how it should work:**
![image](https://github.com/slowtorta/turtlewow-bug-tracker/assets/145224691/7f21d25d-0b5f-49ba-a4e1-e7400b123291)

**Comment by Muigin** [comment]
Cannot reproduce on current version.  Please be sure to delete your WDB after every update.
