### ISSUE TITLE
Missing campfire in Dustallow Marsh

### ISSUE THREAD

**Issue by Relmer08** [slowtorta/turtlewow-bug-tracker#4338]
In Dustwallow Marsh, on the murloc island (64.2, 27.8), there is a patch of grass where if you stay you get fire damage.
![image](https://github.com/slowtorta/turtlewow-bug-tracker/assets/35612045/24382d57-031d-4ad4-89f3-6e6c58c95307)
The campfire should be right where my mouse cursor is in the posted screenshot. I have HD Mod but I asked someone without the mod to check this out and he says he can't see the campfire either.

**Comment by twowTurtReynolds** [comment]
![image](https://github.com/slowtorta/turtlewow-bug-tracker/assets/151180101/867d10ef-31bb-4da9-9e6e-cef9679d70af)
I am not taking damage here.

**Comment by twowTurtReynolds** [comment]
Oh, there it is.
![image](https://github.com/slowtorta/turtlewow-bug-tracker/assets/151180101/47ff16f3-585e-43d8-b5cf-7fc0e85e0f70)
