### ISSUE TITLE
Quest Wont Track To The RIght Of Screen

### ISSUE THREAD

**Issue by Makazestorm** [slowtorta/turtlewow-bug-tracker#434]
**Please, provide a clear description what the bug is:**
When you track a quest so that it shows up to the right of the screen.
It wont track some quests but it will others. Its fixed by relogging
into the account on the client.

**Steps to reproduce the behavior with as much detail as possible:**

1. Open Quest Log
2.  Shift + Mouse Click Quest
3. It should track it but it doesnt

**IDs of affected creatures, items, quests or spells with a link to the relevant page:**

NPC: https://database.turtle-wow.org/?npc=
Item: https://database.turtle-wow.org/?item=
Quest: https://database.turtle-wow.org/?quest=
Spell: https://database.turtle-wow.org/?spell=
Object: https://database.turtle-wow.org/?object=

**Expected behavior. Describe how it should work:**
It should just track up to five quests to the right of the screen.
Sometimes it bugs out and only tracks three. Its fixed if you
relogin to the account.

**Comment by slowtorta** [comment]
I'm sorry, It's some client glitch, we cannot fix it.
