### ISSUE TITLE
Eris Havenfire NPC takes hours to respawn

### ISSUE THREAD

**Issue by GikikCrowchew** [slowtorta/turtlewow-bug-tracker#4343]
**Please, provide a clear description what the bug is:**

**Steps to reproduce the behavior with as much detail as possible:**

1. Failed [The Balance of Light and Shadow] quest

**IDs of affected creatures, items, quests or spells with a link to the relevant page:**

NPC: https://database.turtle-wow.org/?npc=14494
Item: https://database.turtle-wow.org/?item=18659
Quest: https://database.turtle-wow.org/?quest=7622

**Expected behavior. Describe how it should work:**

Please, blizard also corrected this to 15 minutes in later patches, so at least correct that way, but this is so annoying on over-populated server others are failing quest

**Comment by ratkosrb** [comment]
It will be reduced in the next patch.
