### ISSUE TITLE
Frost oil

### ISSUE THREAD

**Issue by Hambeast324** [slowtorta/turtlewow-bug-tracker#4345]
**Please, provide a clear description what the bug is:**

**Steps to reproduce the behavior with as much detail as possible:**

1. Fix Frost oil. The whole letting paladins run around auto attacking and casting frostbolt rank 2 at max range is not a feature, its breaking pvp and fairness. Battlegrounds like blood ring are completely unbalanced with paladins casting frostbolt nonstop.
2. 
3. 

**IDs of affected creatures, items, quests or spells with a link to the relevant page:**

NPC: https://database.turtle-wow.org/?npc=
Item: https://database.turtle-wow.org/?item=
Quest: https://database.turtle-wow.org/?quest=
Spell: https://database.turtle-wow.org/?spell=
Object: https://database.turtle-wow.org/?object=

**Expected behavior. Describe how it should work:**

**Comment by twowTurtReynolds** [comment]
Please take this suggestion to the forums.
