### ISSUE TITLE
Bug with Crusader Strike

### ISSUE THREAD

**Issue by Micfild7** [slowtorta/turtlewow-bug-tracker#4348]
**Please, provide a clear description what the bug is:**
The damage increase portion of Crusader Strike (Paladin) doesn't seem to be working with Judgment of Righteousness or Holy Strike. It does however, appear to be working with Consecration.

**Steps to reproduce the behavior with as much detail as possible:**

1. Use Seal of Righteousness followed by Judgement. Check the damage.
2. Stack Crusader Strike on target. (3-5 times)
3. Use Seal of Righteousness followed by Judgement. Check the new damage.
4. Repeat steps 1 through 3 for Holy Strike

**IDs of affected creatures, items, quests or spells with a link to the relevant page:**

Spell - Crusader Strike: https://database.turtle-wow.org/?spell=45410
Spell Seal of Righteousness: https://database.turtle-wow.org/?spell=25733
Spell Holy Strike: https://database.turtle-wow.org/?spell=678

**Expected behavior. Describe how it should work:**
I assumed it should work increasing the damage of these 2 abilities, i.e. If it says if will increase by 30, when i use Holy Strike or Judgement of Righteousness, the damage should go up by 30 from baseline.

I hope this helps.
Thank you!

**Comment by ratkosrb** [comment]
https://streamja.com/JjvlX

Cannot reproduce the issue. Both Judgement of Righteousness and Holy Strike damage goes up after stacking Crusader Strike.

**Comment by Micfild7** [comment]
I see. Fair enough. I thought the increase would be flat. That is why when i didn't see a flat increase i thought it was bugged. Thank you! Then this thread can be closed.
