### ISSUE TITLE
Paladin Protection talent : Reckoning  - No additional hit after being the victim of a critical strike.

### ISSUE THREAD

**Issue by Scrubbey** [slowtorta/turtlewow-bug-tracker#4349]
**Please, provide a clear description what the bug is:**
After being critically hit by a creature you will not get a additional hit on your next auto-attack on the creature you are currently auto-attacking. However after being being critically hit twice before your next auto-attack you will get 1 additional hit on your next auto-attack

**Steps to reproduce the behavior with as much detail as possible:**
Be specced into the protection talent Reckoning. 5/5 to speed testing up.
1. Get crit by a creature once and hit it back. No extra attack will register
2. Get critically hit twice before auto-attacking. 1 additional extra attack will register.

**IDs of affected creatures, items, quests or spells with a link to the relevant page:**
Spell: https://database.turtle-wow.org/?spell=20182

**Expected behavior. Describe how it should work:**
Just as it is described in the tooltip in the game.
After being the victim of a critical hit you will get an extra attack on your next swing.

*Things I have tried to do to remedy this.*
Delete WDB folder. 
Run the game without any addons enabled.
Run a fresh install of world of warcraft from the Turtle website.

I have also recorded a video showcasing the issue I am experiencing. 
[https://www.youtube.com/watch?v=doZoJpK7pCI](https://www.youtube.com/watch?v=doZoJpK7pCI)

**Comment by Scrubbey** [comment]
From what I have read on the forums you must be auto-attacking the same mob you want to spend your reckoning stack on. You cant start attacking a different mob after being critically hit. Same with cancelling your auto-attack and starting it again.
I am aware of this and it is showcased in the video that even while keeping auto-attack enabled on the same mob that it doesnt help the talent work as it is described.

**Comment by ratkosrb** [comment]
https://github.com/slowtorta/turtle-wow/commit/57e39ba4fc1dadc2726855c9a4b7de77897f75fd

**Comment by Scrubbey** [comment]
@ratkosrb Should I assume the link to a private repository I cant view means it is being worked on or is already fixed in an upcoming update?

**Comment by ratkosrb** [comment]
It will be fixed in the next patch.

**Comment by Scrubbey** [comment]
Thank you for the response! :)
