### ISSUE TITLE
Can't take Snapshot of Gammerita

### ISSUE THREAD

**Issue by Tinyfin-github** [slowtorta/turtlewow-bug-tracker#435]
Can't take Snapshot of Gammerita

How it should work:: For quest  The Super Snapper FX you need to take a Snapshot of Gammerita using Super Snapper FX
What does it not work: When using the item Super Snapper FX you need get the message invalid target.

https://database.turtle-wow.org/?quest=2944 The Super Snapper FX 
https://database.turtle-wow.org/?item=9330#created-by  Snapshot of Gammerita 
https://database.turtle-wow.org/?item=9328 Super Snapper FX

![WoW_ABNCaYZQKO](https://user-images.githubusercontent.com/83077166/141271673-aee49db3-cadc-4cd9-857a-c76b39368a76.jpg)

**Comment by slowtorta** [comment]
Couldn't reproduce, working as intended. 
![image](https://user-images.githubusercontent.com/66763404/141694053-23d83343-f6a7-4290-a149-53361e32be59.png)

**Comment by jongdetim** [comment]
Should be reopened. The item is usable from close up, but only when the turtle is alive. It can't be used on it's corpse, and when used on the live turtle, it doesn't complete the quest, no matter how many times you use the item. Had to abandon the quest as it is incompletable.

**Comment by jongdetim** [comment]
Well, after it respawned, it did finally work.
