### ISSUE TITLE
High Elf Bow Skill not showing up

### ISSUE THREAD

**Issue by swesora** [slowtorta/turtlewow-bug-tracker#4350]
**Please, provide a clear description what the bug is:**

**Steps to reproduce the behavior with as much detail as possible:**

1. In lists of skills, bow skill is not added. 
2. Is the bow skill then applied properly?

**IDs of affected creatures, items, quests or spells with a link to the relevant page:**

Spell: https://database.turtle-wow.org/?spell=26290

**Expected behavior. Describe how it should work:**
Should appears as a 300 +5 in the skills list.

**Comment by twowTurtReynolds** [comment]
![image](https://github.com/slowtorta/turtlewow-bug-tracker/assets/151180101/54b89229-aac9-40a8-a025-872239a7ac8a)
![image](https://github.com/slowtorta/turtlewow-bug-tracker/assets/151180101/e0cd319a-3273-4e58-9234-28226228c2a1)
This is how it works, racials increase the cap and add 5 points. The +5 text is if you have gear further augmenting it.
