### ISSUE TITLE
Can't Complete Horde Triage Quest

### ISSUE THREAD

**Issue by Thalvin** [slowtorta/turtlewow-bug-tracker#4352]
**Please, provide a clear description what the bug is:**
I've saved more than 15 patients but the quest would not complete/allow me to turn in. I cleared WDB, abandoned the quest, and did it again - same result. 

**Steps to reproduce the behavior with as much detail as possible:**

Do the quest as normal, but unable to turn it in

**Comment by twowTurtReynolds** [comment]
Please see https://github.com/slowtorta/turtlewow-bug-tracker/issues/6042
