### ISSUE TITLE
Custom Item Drape of Westfall unenchantable

### ISSUE THREAD

**Issue by Shambler5** [slowtorta/turtlewow-bug-tracker#4355]
The custom item Drape of Westfall quest reward from The Old Church of Westfall X gives the error "Must have a Cloth Equipped" to the player trying to enchant it. Gives the same message for multiple players.

Display ID: 26173

https://database.turtle-wow.org/?quest=40602

Should get the error message "Must have a cloth equipped" when trying to enchant the cloak.

**Comment by twowTurtReynolds** [comment]
"Unenchantable"... I was able to disenchant it, and enchant it.
![image](https://github.com/slowtorta/turtlewow-bug-tracker/assets/151180101/ba3e528e-0e40-4d5c-a7ff-e48d1513bf2e)
