### ISSUE TITLE
Egg-O-Matic, cannot interact

### ISSUE THREAD

**Issue by veryboxes** [slowtorta/turtlewow-bug-tracker#4357]
the Egg-O-Matic in Gadgetzan cannot be interacted with. there is no dialogue. the dialogue for Curgle Cranklehop is present but the options do nothing.

Curgle Cranklehop: https://database.turtle-wow.org/?npc=7763
Hippogryph Egg: https://database.turtle-wow.org/?item=8564
The Super Egg-O-Matic: https://database.turtle-wow.org/?quest=2741
Egg-O-Matic: https://database.turtle-wow.org/?object=142071

hovering over the Egg-O-Matic should give a cog cursor.
right click should open a quest dialogue.

**Comment by ratkosrb** [comment]
Will be fixed in the next patch.
