### ISSUE TITLE
Forest Wisp NPC Buggy

### ISSUE THREAD

**Issue by Ryumatou** [slowtorta/turtlewow-bug-tracker#4358]
**Please, provide a clear description what the bug is:**
Forest Wisp won't give me a quest because of the wrong race
**Steps to reproduce the behavior with as much detail as possible:**

1.Accepted the quest from Malfurion in Temple
2. Traveled to Teldrassil
3. Quest turned in at Forest Wisp and didn't get a new one because race is wrong

**IDs of affected creatures, items, quests or spells with a link to the relevant page:**
https://database.turtle-wow.org/?quest=8734
NPC: https://database.turtle-wow.org/?npc=https://database.turtle-wow.org/?npc=15624
Item: https://database.turtle-wow.org/?item=
Quest: https://database.turtle-wow.org/?quest=https://database.turtle-wow.org/?quest=8734
Spell: https://database.turtle-wow.org/?spell=
Object: https://database.turtle-wow.org/?object=

**Expected behavior. Describe how it should work:**
The quest display should appear again so I can continue/finish quests for both races

**Comment by ratkosrb** [comment]
https://github.com/slowtorta/turtle-wow/commit/aadfe73b838236e2f690045afa1aa6bcf22d5e6d

**Comment by Ryumatou** [comment]
Hi what is dat? Page not found
