### ISSUE TITLE
'Alterac Valley' zone name inside a Winterspring cave.

### ISSUE THREAD

**Issue by perl1743** [slowtorta/turtlewow-bug-tracker#436]
**Please, provide a clear description what the bug is:**
The inside of Winterfall Village's cave is considered as Alterac Valley.
Coordinates: 69.9, 37.9
![image](https://user-images.githubusercontent.com/2818608/141351090-270be426-24a1-46cc-859a-aaed72f69a69.png)

**Steps to reproduce the behavior with as much detail as possible:**

1. Travel to location.
2. Check what zone you're in, such as with /who.
3. Ponder this minor bug.

**IDs of affected creatures, items, quests or spells with a link to the relevant page:**

N/A

**Expected behavior. Describe how it should work:**
Zone name should still be Winterspring.

**Comment by slowtorta** [comment]
Included in https://github.com/slowtorta/turtlewow-bug-tracker/issues/449
