### ISSUE TITLE
Seal of Ascension ring not working during Rend Blackhand Fight

### ISSUE THREAD

**Issue by Azeron223** [slowtorta/turtlewow-bug-tracker#4362]
The item [Seal of Ascension](https://database.turtle-wow.org/?item=12344) does not currently have any effect during the Rend Blackhand fight when used.

If the ring is clicked / used when [Rend Blackhand](https://database.turtle-wow.org/?npc=10429) spawns, there seems to be no effect at all.

Orignally when used during the fight, it would spawn [Vaelastrasz](https://database.turtle-wow.org/?npc=10538) to assist you during the fight, also complete with dialogue from Nefarion on how Vaelastrasz becomes corrupted for the Blackwing Lair fight [Vaelastrasz the Corrupt](https://database.turtle-wow.org/?npc=13020)

**Comment by ratkosrb** [comment]
It will be implemented in the next patch.
