### ISSUE TITLE
Guards in Ratchet not attacking players engaging in pvp

### ISSUE THREAD

**Issue by Thor-Han** [slowtorta/turtlewow-bug-tracker#4363]
**Please, provide a clear description what the bug is:**
Typically hunters or warlocks are corpse camping warmode players in ratchet without being attacked by ratchet bruisers.
**Steps to reproduce the behavior with as much detail as possible:**

1. Be pvp activated in Ratchet.
2.  Get DoTs put on you or a pet attacking you by another player.
3. Guards will not attack or spawn on the attacking player.

**IDs of affected creatures, items, quests or spells with a link to the relevant page:**

NPC: https://database.turtle-wow.org/?npc=3502
Item: https://database.turtle-wow.org/?item=
Quest: https://database.turtle-wow.org/?quest=
Spell: https://database.turtle-wow.org/?spell=
Object: https://database.turtle-wow.org/?object=

**Expected behavior. Describe how it should work:**
Guards should attack players engaging in pvp in Ratchet. It should generally be a safer area for pvp activated players to use the bank and auction house as well as pick up quests.

**Comment by ratkosrb** [comment]
https://github.com/slowtorta/turtlewow-bug-tracker/assets/35845488/3f0dfc8f-cb02-4c04-81a7-57775bec151f

Guards attack me when casting dots of on players.

**Comment by ratkosrb** [comment]
Perhaps you were too far away from any guards. I noticed there's a bit of a blind spot in the center of town with no guards, so I'll add a new guard spawn there and increase the bruisers' detection range.
