### ISSUE TITLE
[Store Mount] Black Zulian Panther

### ISSUE THREAD

**Issue by DonDonnyDon** [slowtorta/turtlewow-bug-tracker#4371]
**Please, provide a clear description what the bug is:**

Bought a Black Zulian Panther on the store mount. The mount speed doesn't correlate with the characters riding skill. The mount only goes to 60% riding speed whilst my character has 150 riding skill.

Please look into it.

Regards

**Steps to reproduce the behavior with as much detail as possible:**

1. Ride the mount : 60% riding speed
2. 
3. 

**IDs of affected creatures, items, quests or spells with a link to the relevant page:**

NPC: https://database.turtle-wow.org/?npc=
Item: https://database.turtle-wow.org/?item=
Quest: https://database.turtle-wow.org/?quest=
Spell: https://database.turtle-wow.org/?spell=
Object: https://database.turtle-wow.org/?object=

**Expected behavior. Describe how it should work:**
Should be set to "increases speed based on riding skill.

**Comment by twowTurtReynolds** [comment]
I can't replicate this issue, at 150 riding this mount runs at +100% speed for me.
