### ISSUE TITLE
Item: Danonzo's Tel'Abim Medley No Casting Speed

### ISSUE THREAD

**Issue by PashaKova** [slowtorta/turtlewow-bug-tracker#4372]
Danonzo's Tel'Abim Medley Haste “Well Fed” buff doesn’t give an increase in casting speed, unlike Haste enchants and items with a “haste” bonus. 

1. Eat the Danonzo's Tel'Abim Medley for 10 seconds to get the Well Fed buff 
2. Look at the casting speed of Flash Heal
3. It remains the same with The Well Fed buff 

Spell: https://database.turtle-wow.org/?spell=57046
Object: https://database.turtle-wow.org/?item=60978

The “Well Fed” buff should give +2% casting speed, besides melee attacks and range attack speed.

In the database it doesn’t have the “spell haste” attribute. Compare two pictures.
![5BD37D5B-B577-4A80-A004-0394F7CA6868](https://github.com/slowtorta/turtlewow-bug-tracker/assets/97367379/42e7ce00-67fe-454a-b306-a3a47d51eaff)
![DADCF994-EA9E-44D1-8754-2D5EAB8DF552](https://github.com/slowtorta/turtlewow-bug-tracker/assets/97367379/ee63e054-4d4c-415b-b040-ff948eb14213)

**Comment by twowTurtReynolds** [comment]
The database isn't always to be trusted with aspects like this.
It seems to be working fine ingame:
![image](https://github.com/slowtorta/turtlewow-bug-tracker/assets/151180101/5af9bb86-9544-405b-9aec-a330304cfeda)
