### ISSUE TITLE
Missing sound of mount moving, bag opening etc

### ISSUE THREAD

**Issue by yogorus** [slowtorta/turtlewow-bug-tracker#4374]
**Please, provide a clear description what the bug is:**
So my game missing few sounds, like the sound of horse footstep when moving (spacebar mount special does work, tho, at least with Red Skeletal Horse, turtle is silent but i thought that was intended, now im not sure), sound of bag opening, moving items inside of it, cooking produces no sound either. But if i disable pfUI, sound of bag opening is here, but mount is still silent. 

I play with vanillafixes and vanillatweaks so sound channels number is not the problem. I tried setting sound channels manually through console commands but that does not help either. Deleting WDB does not do anything, too

**Steps to reproduce the behavior with as much detail as possible:**

1. Open game
2. Ride horse
3. No sound!

**IDs of affected creatures, items, quests or spells with a link to the relevant page:**
Spell: https://database.turtle-wow.org/?spell=17462

**Expected behavior. Describe how it should work:**
My horse should be making hoof sound while moving

**Comment by twowTurtReynolds** [comment]
Please work with discord #support who will likely tell you to test again on a fresh unmodified client.
