### ISSUE TITLE
cant increase reputation with Booty Bay by killing members of the Venture Company

### ISSUE THREAD

**Issue by neopumpki** [slowtorta/turtlewow-bug-tracker#4376]
**Please, provide a clear description what the bug is:**

**Steps to reproduce the behavior with as much detail as possible:**

1.if player's reputation with Booty Bay was hate, u olny can "increase" reputation  by killing members of the Venture Company
2. Killing members of the Venture Company should normally increase reputation, but when the player's reputation is already at the Hatred level, it should  decrease the Hatred value. However, at present, it only increases Hatred without any decrease
3. 

**IDs of affected creatures, items, quests or spells with a link to the relevant page:**

NPC: https://database.turtle-wow.org/?npc=
Item: https://database.turtle-wow.org/?item=
Quest: https://database.turtle-wow.org/?quest=
Spell: https://database.turtle-wow.org/?spell=
Object: https://database.turtle-wow.org/?object=

**Expected behavior. Describe how it should work:**

**Comment by neopumpki** [comment]
by the way, the other quests I've been doing have also increased my Hatred level in Booty Bay.

**Comment by cyaohiri** [comment]
Keep in mind that the higher the number in your reputations tab, the closer you are to being Exalted. The wording is confusing.
For example, if you are Hated at 32000/36000 reputation, then you need to get 4k more reputation to get to Hostile.

**Comment by twowTurtReynolds** [comment]
Thank you, on my second reading, indeed that sounds like the confusion here.
