### ISSUE TITLE
[Warlock] Warlock AQ20 3 Piece Set Not Applying Damage Bonus

### ISSUE THREAD

**Issue by triana2021** [slowtorta/turtlewow-bug-tracker#438]
After extensive testing I can confirm that the 3 piece pet damage bonus from the warlock set 'Unspoken' (+5% damage from physical and magical damage) is not being applied anywhere. Base damage values are still reflected in the real world. The 5% value should be applied across pet damaging abilities, spells, and auto-attacks.

Continues testing with imp shows values do not change.

**Comment by triana2021** [comment]
As of 1/11/2022 issue persists.

**Comment by itswicky** [comment]
There is a similar issue posted regarding Orc racial. Iirc, this is supposed to be handled in spell.dbc with aura 107 or 108 modifying the warlock pet dummy auras which are then handled in either pet.cpp or warlock.cpp.

**Comment by ratkosrb** [comment]
I cannot reproduce the issue. The damage bonus is applied correctly. You can see the damage goes up.
https://streamja.com/3mG0Q
