### ISSUE TITLE
Flying gryphons buff started appearing on buff bar and causes a dc when the player sends a "cancel aura" request

### ISSUE THREAD

**Issue by balakethelock** [slowtorta/turtlewow-bug-tracker#4380]
**Please, provide a clear description what the bug is:**
Title. Flying gryphons buff started appearing on buff bar and causes a dc when the player sends a "cancel aura" request

**Steps to reproduce the behavior with as much detail as possible:**

1. Use the gryphon in elwynn forest
2.  See that you now get a buff of its duration, this is a recent addition
3. The buff is invisible, probably cause there's no dbc data on the spell id they're using for the flight.
4. Trying to click off the buff crashes your game

**IDs of affected creatures, items, quests or spells with a link to the relevant page:**

Spell: I can't know that, list auras command is disabled in the live server.

**Expected behavior. Describe how it should work:**
The spell should have an entry in the dbc probably (client side fix) OR you could go back to hiding it from the player

**Comment by balakethelock** [comment]
https://github.com/slowtorta/turtlewow-bug-tracker/assets/111737968/4cb3ac6a-d162-4806-ae35-e8fa4749c33d

**Comment by lyssebabz** [comment]
https://github.com/slowtorta/turtlewow-bug-tracker/assets/20995435/b0ca9415-7fdc-400e-9514-2657fb7df807

easy to reproduce

**Comment by balakethelock** [comment]
Seems to not happen anymore. Closing until further notice
