### ISSUE TITLE
Orc Shaman Bug

### ISSUE THREAD

**Issue by jainst** [slowtorta/turtlewow-bug-tracker#4384]
**Please, provide a clear description what the bug is:**

**Steps to reproduce the behavior with as much detail as possible:**

1.  Blood Fury (id:20572) doesn't stack with Rockbiter Weapon (id:8017)
2.  attack certain mob several times without any buff, log the damage
3.  cast Blood Fury (id:20572) and attack the mob (without rockbiter weapon), log the damage (increased)
4.  cast Rockbiter Weapon (id:8017) and attack the mob (without blood fury), log the damage (increased)
5.  cast Blood Fury and Rockbiter Weapon and attack the mob, log the damage (the blood fury effect be ignored)

**IDs of affected creatures, items, quests or spells with a link to the relevant page:**

NPC: https://database.turtle-wow.org/?npc=
Item: https://database.turtle-wow.org/?item=
Quest: https://database.turtle-wow.org/?quest=
Spell: https://database.turtle-wow.org/?spell=
Object: https://database.turtle-wow.org/?object=

**Expected behavior. Describe how it should work:**

**Comment by balakethelock** [comment]
https://github.com/slowtorta/turtlewow-bug-tracker/issues/3994 and https://github.com/slowtorta/turtlewow-bug-tracker/issues/2436
