### ISSUE TITLE
npc=7461 can't be looted

### ISSUE THREAD

**Issue by Reaperium** [slowtorta/turtlewow-bug-tracker#4388]
**Please, provide a clear description what the bug is:**

**Steps to reproduce the behavior with as much detail as possible:**

1. attack the mob/creep
2. kill it
3. try to loot, it cant be looted

**IDs of affected creatures, items, quests or spells with a link to the relevant page:**

NPC: https://database.turtle-wow.org/?npc=7461
Item: https://database.turtle-wow.org/?item=
Quest: https://database.turtle-wow.org/?quest=
Spell: https://database.turtle-wow.org/?spell=
Object: https://database.turtle-wow.org/?object=

**Expected behavior. Describe how it should work:**

**Comment by Reaperium** [comment]
i tried one more time, you have to be close to it to loot, if you are a caster and kill it from distance, you cant loot.

**Comment by Muigin** [comment]
Cannot reproduce.
