### ISSUE TITLE
FPS drop in a certain area

### ISSUE THREAD

**Issue by cvendacz** [slowtorta/turtlewow-bug-tracker#4391]
FPS drops bellow 1 as soon as anybody walks into an area of south Dun-Morogh near a quest NPC

![image-1](https://github.com/slowtorta/turtlewow-bug-tracker/assets/83541495/d9f6ef2e-fe51-4592-9ca2-6e097ce3f68e)

**Comment by twowTurtReynolds** [comment]
We provided you with a template, please use it. I have no idea where to go to reproduce this.
