### ISSUE TITLE
Soul Link not affecting enslaved demons. 

### ISSUE THREAD

**Issue by bellmountain** [slowtorta/turtlewow-bug-tracker#4392]
According to the tooltip 'Soul Link'  should work on enslaved demons. (blizzlike, always has been)
But for me it doesnt.  I tried a bunch of satyrs in dire maul and none got soul linked to me.
I cast the spell, animation goes off but no buffs get applied to me or the enslaved demon.
Should work exactly like on summoned demon.
Cheers

**Comment by Muigin** [comment]
Duplicate of #2497
