### ISSUE TITLE
Druid hit talents do not work for spell hit

### ISSUE THREAD

**Issue by DRepetsky** [slowtorta/turtlewow-bug-tracker#4393]
63 boss have 17% chanse to be missed. Having 5% spell hit from gear + 3% from talents i expect missing 9% of spells, but according to logs it is ~12%, some times ranging 10 to 14 but never 9. So my assumption is that druid talent Natural Weapons does not work on spell hit.
There no boss target dummy in capitals any more, so i can't test it any better. I do have raid logs and can provide them, but you'll need to trust me there was 5% from gear

**Comment by Datedb** [comment]
every spell has a 1% chance to be missed.

**Comment by balakethelock** [comment]
> every spell has a 1% chance to be missed.

Not relevant to his described issue.

I can't speak on whether the thing is really bugged or not, in the database it seems to have the correct effect and I don't have a druid to test it.

**Comment by DRepetsky** [comment]
![image](https://github.com/slowtorta/turtlewow-bug-tracker/assets/52487427/7c3be9a9-6311-470f-8bfd-c4465a4f68cc)
With return of SW trainig dummies I did large test and bug seem to be there
I have 7% hit from equip and latest BetterCharacterStats seem to understand i have +3% from talents
But in logs, after doing over 600 spell casts it is clearly seen i miss ~10% while it should be 7%

**Comment by Muigin** [comment]
Looking at the internal behavior, Natural Weapons talent is indeed applying Aura #55: Mod Spell Hit Chance (+3%) as used by other spells which work properly. As this is a working aura and is attached to the spell, if it were not working, no other +spell hit talents or bonuses would be working.

Working as intended.
