### ISSUE TITLE
shape the waters bug

### ISSUE THREAD

**Issue by hdk68** [slowtorta/turtlewow-bug-tracker#4394]
**Please, provide a clear description what the bug is:**

**Steps to reproduce the behavior with as much detail as possible:**

1.using database for shape the waters spell 
2. i used abyssal wave and unyielding gust
3. it did NOT create the depthstalker helm but it created windwalker boots - i thought i made a mistake so i did it again and same result.. I need the correct pattern and mats for the 2nd boots refunded please and thank you

**IDs of affected creatures, items, quests or spells with a link to the relevant page:**

NPC: https://database.turtle-wow.org/?npc=
Item: https://database.turtle-wow.org/?item=
Quest: https://database.turtle-wow.org/?quest=
Spell: https://database.turtle-wow.org/?spell=
Object: https://database.turtle-wow.org/?object=

**Expected behavior. Describe how it should work:**

**Comment by Muigin** [comment]
This has since been fixed.
