### ISSUE TITLE
Attack Power reduction effects from Screech and Demoralizing Shout do not stack

### ISSUE THREAD

**Issue by patrycos** [slowtorta/turtlewow-bug-tracker#4395]
**Please, provide a clear description what the bug is:**
Screech used by Owl/Bat pets does not stack with Warrior's Demoralizing Shout. Both debuffs are active on the target, but only the stronger one applies the Attack Power reduction. It doesn't matter whether Screech or Demoralizing Shout is applied first, the outcome is the same.
[Video](https://www.youtube.com/watch?v=5AzvGM3UcDE)

**Steps to reproduce the behavior with as much detail as possible:**
1. Engage an enemy with high enough AP for testing purposes
2. Use Demoralizing Shout
3. Demoralizing Shout will be active on the target and its Attack Power correctly reduced
4. Use Screech
5. Screech will be active on the target, Demoralizing shout will remain active on the target, but target Attack Power will remain unchanged compared to step 3

**IDs of affected creatures, items, quests or spells with a link to the relevant page:**
Screech (Rank 4): https://database.turtle-wow.org/?spell=24579
Demoralizing Shout (Rank 5): https://database.turtle-wow.org/?spell=11556
Both spells apply the effect `(6) Apply Aura #99: Mod Attack Power`

**Expected behavior. Describe how it should work:**
Screech Attack Power reduction should stack with effects such as Demoralizing Shout or Demoralizing Roar.

**Comment by balakethelock** [comment]
https://github.com/slowtorta/turtlewow-bug-tracker/issues/4148
Thanks for testing hunter screech as well

**Comment by twowTurtReynolds** [comment]
Thank you for the video. We will track this under @balakethelock 's ticket.
