### ISSUE TITLE
Conqueror's Set Bonus actually lowers thunderclap damage instead of increasing it

### ISSUE THREAD

**Issue by Faerrum** [slowtorta/turtlewow-bug-tracker#4398]
When I have 5/5 Conqueror's Equipped on a warrior my thunderclap damage should increase 50% but it actually goes down 50%. I am consistently thunderclapping for about 88 damage in defensive stance.

**Steps to reproduce the behavior with as much detail as possible:**

1. Wear conqueror's set
2. Thunderclap

The tier 2.5 set for warriors - Conqueror's Set - should increase Thunderclap damage by 50% and in fact lowers it instead. Confirmed by multiple warriors with 5/5 set.

**Comment by twowTurtReynolds** [comment]
I think you have misunderstood, and not known that thunderclap is a physical (affected by armor) attack.

The combinations of imp tclap and 5/5 t2.5 seem to work correctly:

![image](https://github.com/slowtorta/turtlewow-bug-tracker/assets/151180101/82cacad9-816b-4821-96ac-dc3b6999cbcb)
![image](https://github.com/slowtorta/turtlewow-bug-tracker/assets/151180101/d00595b5-c8a3-4c20-9bd3-4c919b01b3c9)
![image](https://github.com/slowtorta/turtlewow-bug-tracker/assets/151180101/63b2c571-5f89-4992-8ae4-2b1a1889982f)
![image](https://github.com/slowtorta/turtlewow-bug-tracker/assets/151180101/6fdcd95a-1238-4928-af15-2d302b97d675)
