### ISSUE TITLE
"Thandol Span" Quest bugged

### ISSUE THREAD

**Issue by catsnakey** [slowtorta/turtlewow-bug-tracker#4399]
**Please, provide a clear description what the bug is:**
You cannot progress the quest as the NPC (Vladeus Springriver) is incapable of moving past the loading zone that takes you into the Wetlands from Arathi. He disappears and does not follow through, thus you cannot complete that portion of the quest. He is present in the basement of Menethil Hold but he cannot be interacted with. The Scarlet NPCs are also bugged, they spam Hammer of Justice too often and they seemed to continuously spawn the first 5 times I tried to do this quest.
**Steps to reproduce the behavior with as much detail as possible:**

1. Accept the quest.
2. Go to the bridge and fight Vladeus
3. Attempt to bring him back to Menethil as the quest suggests.

**IDs of affected creatures, items, quests or spells with a link to the relevant page:**

NPC: https://database.turtle-wow.org/?npc=50674
Item: https://database.turtle-wow.org/?item=
Quest: https://database.turtle-wow.org/?quest=80703
Spell: https://database.turtle-wow.org/?spell=
Object: https://database.turtle-wow.org/?object=

**Expected behavior. Describe how it should work:**
The NPCs should be a lot more reasonable in terms of spawning and spamming their abilities and Vladeus should follow you to the end point with no issues.

**Comment by catsnakey** [comment]
I was really invested in the quest chain once I got the letter and was excited to see it through, and then promptly disappointed to find out I couldn't do the quest. I'm not 100% sure how easy it is to resolve this, but I request it be done as soon as possible as I would love to finish it.

**Comment by drstrainge** [comment]
Same thing here
