### ISSUE TITLE
LBRS boss not dropping loot/ Scorpions in LBRS

### ISSUE THREAD

**Issue by triana2021** [slowtorta/turtlewow-bug-tracker#440]
As stated, the final boss in Lower Blackrock Spire is not dropping any loot. Have been twice in the last two days and have encountered this issue.

Secondly, LBRS is bugged. Scorpions aggro from below due to an issue of vertical pathing. This makes the dungeon nigh impossible for a group of new 60s and leads to a shutting down of a needed progression dungeon.

**Comment by jameyboor** [comment]
Couldn't reproduce the bugged loot, you might've just been very unlucky, will look into the Scorpions.
