### ISSUE TITLE
Mob killed solely by hunter's pet, can't be looted/doesn't count for quest

### ISSUE THREAD

**Issue by Orion5000** [slowtorta/turtlewow-bug-tracker#4401]
If the hunter's pet goes to kill anything by itself, either by commanding him to attack or because he is set to aggressive, the body of the killed mob will be unlootable as if it had been killed by someone else

**Steps to reproduce the behavior with as much detail as possible:**

1. Use hunter
2. Find a quest mob to kill for proper observation
3. command your pet to kill it or let him agro the mob, don't intervene

Expected behavior : Mobs killed solely by the pet should still be lootable and count toward quests

**Comment by Muigin** [comment]
Working as intended. A hunter MUST participate in a kill in order to receive experience, loot, reputation, etc. This is to prevent AFK farming abuse.
