### ISSUE TITLE
Makes veins be lootable by everyone nearby to prevent abuse

### ISSUE THREAD

**Issue by Boomdrawzz** [slowtorta/turtlewow-bug-tracker#4402]
Im not sure if this is a bug, or if this is a turtle wow special. If you farm veins and another person clicks that vein before you then it states that this item is already been used. To annoy other farmers you can stay on that vein for many minutes. The intend might have been good, but people abuse this frequently. 

exemplary ID: https://database.turtle-wow.org/?object=175404

Just make it so that you have to loot it or you lose the vein like it should be. This prevents abusing this bug/"feature".

https://clipchamp.com/watch/F0uZd3qHXEc  short example to make this video not last 20 minutes

**Comment by Muigin** [comment]
This is working as intended. If you would like to make a suggestion, please post in the suggestions section of the forum. This is for bugs.
