### ISSUE TITLE
Quest: The Stones That Bind Us

### ISSUE THREAD

**Issue by Zergvl** [slowtorta/turtlewow-bug-tracker#4407]
Quest: The Stones That Bind Us

quest goal is to kill servants (of Grol, Sevine, etc),
When attacking quest mobs, when they have 10-15% health remaining, an invulnerability buff  ([spirit shock](https://database.turtle-wow.org/?spell=10794)) is applied to the mobs.
there is a stone of binding next to the mobs that should remove this invulnerability buff if the stone is broken.
But if you destroy the stone invulnerability does not disappear, although there is a flash animation on the mob.

https://youtu.be/0UJ7CC-QtkU

**Steps to reproduce the behavior with as much detail as possible:**
1. find servant of *
2. attack it
3. wait untill mob will get invulnerability 
4. destroy stone of binding
5. look thet invulnerability  does not disappear

**IDs of affected creatures, items, quests or spells with a link to the relevant page:**

NPC: 
  https://database.turtle-wow.org/?npc=7668
  https://database.turtle-wow.org/?npc=7669
  https://database.turtle-wow.org/?npc=7670
  https://database.turtle-wow.org/?npc=7671
Quest: 
  https://database.turtle-wow.org/?quest=2681
Item:
  https://database.turtle-wow.org/?object=141812
  https://database.turtle-wow.org/?object=141857
  https://database.turtle-wow.org/?object=141858
  https://database.turtle-wow.org/?object=141859
Buff:
  https://database.turtle-wow.org/?spell=10794

**Expected behavior. Describe how it should work:**
Destroing of "stone of binding" should dispell invulnerability

**Comment by twowTurtReynolds** [comment]
Duplicate of https://github.com/slowtorta/turtlewow-bug-tracker/issues/3642
