### ISSUE TITLE
Aqual Quintessence unusable when Eternal Quintessence on cooldown

### ISSUE THREAD

**Issue by Scrubbey** [slowtorta/turtlewow-bug-tracker#4409]
If you use your Aqual Quintessence and your Eternal Quintessence, then go pick up another Aqual Quintessence it will remain unusable until the Eternal Quintessence comes off cooldown. There is no cd indication on Aqual Quintessence, and they are not supposed to share a cooldown.

Steps to reproduce the behavior with as much detail as possible:

    Use Aqual Quintessence and Eternal Quintessence to douse two runes in molten core
    Pick up another Aqual Quintessence and attempt to douse another rune
    It will remain unusable and giving you a spell not ready yet error until the Eternal Quintessence cooldown is up

Aqual Quintessence and Eternal Quintessence is not supposed to share a cooldown.

**Comment by ratkosrb** [comment]
It will be fixed in the next patch.
