### ISSUE TITLE
Item Bug: Horde Defender's Axe (does not disenchant)

### ISSUE THREAD

**Issue by AyleeJenn** [slowtorta/turtlewow-bug-tracker#4410]
**Please, provide a clear description what the bug is:**
The item "Horde Defender's Axe" does not appear to be disenchant-able. When you try, you get an error "Item cannot be disenchanted".

This item needs disenchant ID 41 (currently it is set to 0)

**Steps to reproduce the behavior with as much detail as possible:**

1. Run the final quest of the PvP quest "Horde Defender's Axe"
2. Attempt to disenchant the item "Horde Defender's Axe"
3. Observe the error "Item cannot be disenchanted"

**IDs of affected creatures, items, quests or spells with a link to the relevant page:**

Item: https://database.turtle-wow.org/?item=40065
Quest: https://database.turtle-wow.org/?quest=39999

**Expected behavior. Describe how it should work:**
The item should honestly disenchant. My guess would be either a small radiant shard which is what other blue quality items of similar level disenchant into.

**Comment by luskanek** [comment]
Fixed in next update.
