### ISSUE TITLE
Extinguishing the Idol event in Razorfen Downs

### ISSUE THREAD

**Issue by Azeron223** [slowtorta/turtlewow-bug-tracker#4411]
During the escort quest in Razorfen Downs, [Extinguishing the Idol](https://database.turtle-wow.org/?quest=3525), the escort NPC  [Belnistrasz](https://database.turtle-wow.org/?quest=3525) never recovers health from damage taken, much of which is extremely hard to avoid as mobs will always instantly aggro onto him and immediately cast spells on him.

From memory, after each wave of mobs initiates combat with [Belnistrasz](https://database.turtle-wow.org/?quest=3525), if he takes damage during combat his HP should reset just as any other mob would after dropping combat, it's also _possible_ he's intended to be a friendly target for the purposes of being able to heal him, though I cannot confirm this.

It also beleive that the mobs should also not instantly target and attack [Belnistrasz](https://database.turtle-wow.org/?quest=3525), but rather should spawn randomly in one of 3 locations out of combat and naturally aggro onto whatever is within their aggro range, I distinctly remember wiping on this event due to healers being unlucky enough to be drinking on top of a mob spawn while not paying attention (though as is usual with mob spawns, anyone should have a few seconds after the mobs spawns before it aggros onto a nearby hostile target)

**Comment by ratkosrb** [comment]
He will be able to regen after the next patch.
