### ISSUE TITLE
Glyph of the Stag inaccurate sound

### ISSUE THREAD

**Issue by Lichbanez** [slowtorta/turtlewow-bug-tracker#4412]
I can still hear the roar sound upon entering the travel form and when hit by mobs even with the Glyph of the Stag.

1. Having the Glyph of the Stag in the keyring
2. Activating the Travel Form

Item: https://database.turtle-wow.org/?item=51056
Spell: https://database.turtle-wow.org/?spell=783

I don't know if it's purposely left unaddressed but I think that the glyph is supposed to replace or at least remove the feline sounds of the travel form.

**Comment by luskanek** [comment]
Working as intended.

**Comment by twowTurtReynolds** [comment]
I currently hear
