### ISSUE TITLE
LM 40 multi-level mission "A Troubling Breeze"

### ISSUE THREAD

**Issue by kriou** [slowtorta/turtlewow-bug-tracker#4413]
https://database.turtle-wow.org/?quest=475

This quest found the NPC, the NPC was lying on the ground and clicking on the NPC didn't respond. The quest says you need 8 Cores of Lightness, but I don't know how to get them, the auction house doesn't sell them.

**Comment by ratkosrb** [comment]
https://github.com/slowtorta/turtlewow-bug-tracker/assets/35845488/ad22de64-2af3-4ea6-b8e1-db890fb1a140

I cannot reproduce the issue. This quest does not require any items. Try clearing your cache.
