### ISSUE TITLE
Execute (spell) costs all of my rage on my warr

### ISSUE THREAD

**Issue by Paulycze** [slowtorta/turtlewow-bug-tracker#4414]
**Please, provide a clear description what the bug is:**
Execute (spell) costs all of my rage on my warr
**Steps to reproduce the behavior with as much detail as possible:**

1. When i have for example 70 rage and i use execute so i lost all of my rage
2. 
3. 

**IDs of affected creatures, items, quests or spells with a link to the relevant page:**

NPC: https://database.turtle-wow.org/?npc=
Item: https://database.turtle-wow.org/?item=
Quest: https://database.turtle-wow.org/?quest=
Spell: https://database.turtle-wow.org/?spell=
Object: https://database.turtle-wow.org/?object=

**Expected behavior. Describe how it should work:**

**Comment by luskanek** [comment]
Working as intended. Execute costs 15 rage and additional rage that you have is converted into damage.
