### ISSUE TITLE
Is thornpod intended to scale with spellpower?

### ISSUE THREAD

**Issue by Darthblaider** [slowtorta/turtlewow-bug-tracker#4416]
I'm trying to understand better about this Thornpod item from Maraudon that drops off trash. It's a BOE trinket that does a ranged aoe stun for 2 seconds. The tooltip says it should do 75 damage. In a blood ring match, a played used this and did nearly 800 damage to myself and my partner while landing the stun. I'm just trying to figure out if this is spellpower scaling, and if so, is it intended. 

Either way, this makes the trinket incredibly powerful and personally I feel its very unbalanced. Every time you enter blood rings, all your cooldowns including trinkets are reset so this is usable every single game.

I'm currently working towards farming one of my own to do more specific testing.

Does anyone know more about this and how its intended to work?

Item: https://database.turtle-wow.org/?spell=21748

**Comment by welpenhund** [comment]
Tested it, it seems to scale 1:1 with spellpower ye - Not sure if that is intended.

**Comment by twowTurtReynolds** [comment]
Nerfed!
