### ISSUE TITLE
Unable to loot Logistics Assignment Scrolls out of Envelopes

### ISSUE THREAD

**Issue by discer** [slowtorta/turtlewow-bug-tracker#4417]
**Please, provide a clear description what the bug is:**

I am unable to get the Logistics Scrolls out of the Logistics Assignments envelopes for the Silithus quests. 
I have no Logistics quests in my quest tracker or Logistics Assignment scrolls currently in my inventory or bank.

**Steps to reproduce the behavior with as much detail as possible:**

1. Open Logistics Assignment Envelope
2. Right click scroll to loot
3. Window closes and no scroll appears in inventory

**IDs of affected creatures, items, quests or spells with a link to the relevant page:**

Character Name bug is ocurring on is im

**Expected behavior. Describe how it should work:**
![Logbug](https://github.com/slowtorta/turtlewow-bug-tracker/assets/139697479/cd582bc5-5236-44ce-b33c-2f5af318d6ac)
Only items with log in name is the envelopes in inventory and bank
![Questlogbug](https://github.com/slowtorta/turtlewow-bug-tracker/assets/139697479/761e598d-2d41-48b0-a487-059f78e3b080)
No Logistics quests only 2 tactical

**Comment by Muigin** [comment]
Cannot reproduce on current version.

**Comment by discer** [comment]
What does cannot reproduce have to do with this? It is only occurring on that specific character

**Comment by discer** [comment]
Had to delete current envelopes but new ones appear to be working correctly
