### ISSUE TITLE
Wrong soundbite

### ISSUE THREAD

**Issue by Icember** [slowtorta/turtlewow-bug-tracker#4418]
**Please, provide a clear description what the bug is:**
As human, /mourn while in motion plays the /chicken soundbite. Tried replicating it on orc & High Elf but only happened on my male human char. Can hear beginning of crying soundbite but immediately turns to chicken one. Thought it might be related to the targeted mob, improved sprint, or auto run but was able to recreate it on warrior with nothing targeted & using manual run. Also didn't seem to affect /cry, just /mourn.

**Steps to reproduce the behavior with as much detail as possible:**

1. begin running in a direction & don't stop.
2. type /mourn
3. 

**IDs of affected creatures, items, quests or spells with a link to the relevant page:**

NPC: https://database.turtle-wow.org/?npc=
Item: https://database.turtle-wow.org/?item=
Quest: https://database.turtle-wow.org/?quest=
Spell: https://database.turtle-wow.org/?spell=
Object: https://database.turtle-wow.org/?object=

**Expected behavior. Describe how it should work:**
Should play the human crying sound, not the chicken one.

**Comment by Frechfuchs** [comment]
Can confirm, on human male newly created character /mourn plays the chicken sound. For whatever reason

**Comment by Dragunovi** [comment]
Fixed in 1.17.0.

**Comment by twowTurtReynolds** [comment]
I'm QAing patch-5.mpq and I see this fix applied :+1:
