### ISSUE TITLE
Seal of the Dawn trinket

### ISSUE THREAD

**Issue by badgermaster** [slowtorta/turtlewow-bug-tracker#4419]
**Please, provide a clear description what the bug is:**

**Steps to reproduce the behavior with as much detail as possible:**

1. while being equipped, this trinket doesn't allow players to pick up Scourgestones
2. https://database.turtle-wow.org/?item=13209
3. 

**IDs of affected creatures, items, quests or spells with a link to the relevant page:**

NPC: https://database.turtle-wow.org/?npc=
Item: https://database.turtle-wow.org/?item=
Quest: https://database.turtle-wow.org/?quest=
Spell: https://database.turtle-wow.org/?spell=
Object: https://database.turtle-wow.org/?object=

**Expected behavior. Describe how it should work:**

**Comment by Muigin** [comment]
Cannot reproduce. Working as intended.
