### ISSUE TITLE
Maybe an aggro problem with the demons in the dungeon "Crescent Grove"

### ISSUE THREAD

**Issue by feifeiyu12345** [slowtorta/turtlewow-bug-tracker#4420]
I was with my team having a "Crescent Grove" run,it was all successful and we were right at the front of the elf spirit ghost boss,and that somehow those demon guards right near the dungeon entrance all run into our face from the back.Causing the whole team to panic and I died unfortunately because HS still in CD.My teammates and I have been always closely together and there is no chance that was someone's ADD behavior.Besides those who attack from our back comes from a place that near the very entrance of the dungeon.

We were just doing a normal Crescent Grove run,and I remember nothing special or suspicious.But I remember our team structure:2 Paladins,1 Druid, 1 Shaman,1 Rogue.And one detail that may help is that only those demons with a big broadsword were pulled.

1.Do a normal Crescent Grove run,finish 1st bear boss, 2nd stag druid and the 3rd Satyr boss, finish the 2 Elite and arrive at the front of the 4th boss.
2. When you do as the 1st step describes,clear the monsters only those who stand in your way to bosses.(Clear all treants before stag druid.)
3. Pay attention to the demon guards nearest to the entrance,see if something will happen. 

**IDs of affected creatures, items, quests or spells with a link to the relevant page:**

NPC: https://database.turtle-wow.org/?npc=92124
Item: https://database.turtle-wow.org/?item=
Quest: https://database.turtle-wow.org/?quest=
Spell: https://database.turtle-wow.org/?spell=
Object: https://database.turtle-wow.org/?object=

Those broadsword demons should be standing still where they originally were,but they somehow charge at our backsides.This is something that should never make sense.
Is there any chance that my character could be bring back?

**Comment by Muigin** [comment]
There are patrols with a low respawn timer that may have respawned behind you.

Working as intended.
