### ISSUE TITLE
transmorg NPC not opening transmorg window in Ogrimmar

### ISSUE THREAD

**Issue by cherryblue1** [slowtorta/turtlewow-bug-tracker#4425]
**Please, provide a clear description what the bug is:**

**Steps to reproduce the behavior with as much detail as possible:**

1. my friend asked me to report this bug as he is not able to access github. He is a level 21 Horde Shaman Tauren and is not able to talk to the fashion NPC where you do transmorg. He has talked to the fashion coin NPC and handed in mats and she gave him fashion coins which he has in his bag and he has the armor in his bag that he wants to transmorg to but the transmorg NPC doesn't open the transmorg window for him. He has tried deleting his WDB folder when he exits the game and then opens it again but he is still unable to get the NPC to open the transmorg window. He opened a ticket ingame but the GM was unable to resolve the issue.
2. My friends ingame name is meteorship if that helps at all?
3. the expected behaviour is - hand in mats for fashion coins, get given fashion coins then go to the transmorg NPC and when you click on her she should open the transmorg window. I don't think he is doing any of the steps wrong as he has used transmorg in sw on his alliance character many times.

**IDs of affected creatures, items, quests or spells with a link to the relevant page:**

NPC: https://database.turtle-wow.org/?npc=
Item: https://database.turtle-wow.org/?item=
Quest: https://database.turtle-wow.org/?quest=
Spell: https://database.turtle-wow.org/?spell=
Object: https://database.turtle-wow.org/?object=

**Expected behavior. Describe how it should work:**

**Comment by Frechfuchs** [comment]
Is your friend using any UI addons that my interfere with the turtle UI?

**Comment by Muigin** [comment]
Cannot reproduce on current version.
