### ISSUE TITLE
Cluck! 

### ISSUE THREAD

**Issue by KentaiH** [slowtorta/turtlewow-bug-tracker#4426]
**Please, provide a clear description what the bug is:**
The Quest Cluck! doesnt give you an chicken egg after completion... i even had issues getting the quest. No question mark appeared after doing the /chicken emote 
**Steps to reproduce the behavior with as much detail as possible:**

1.Find a chicken
2. use /chicken until the chicken becomes friendly
3. a question mark should appear but it never appeared. i wrote to a GM and got the quest 
4. find Special Chicken Feed
5. Give chicken the Special chicken feed and complete the quest and a chicken egg should appear. No chicken egg apeared for me. idk if did anything wrong or.

**IDs of affected creatures, items, quests or spells with a link to the relevant page:**

NPC: https://database.turtle-wow.org/?npc=
Item: https://database.turtle-wow.org/?item=
Quest: https://database.turtle-wow.org/?quest=3861
Spell: https://database.turtle-wow.org/?spell=
Object: https://database.turtle-wow.org/?object=

**Expected behavior. Describe how it should work:**

**Comment by Muigin** [comment]
Cannot reproduce on current version.  The chicken egg is rather small and appears under your character's feet, so be sure you look closely.
