### ISSUE TITLE
Horde's TBC Midsummer fire persisting in Silithus

### ISSUE THREAD

**Issue by Azeron223** [slowtorta/turtlewow-bug-tracker#4432]
The Burning Crusade and beyond version of the [Horde's Midsummer Bonfire](https://database.turtle-wow.org/?object=187950) is currently persisting in Silithus just below Cenarion Hold on the path towards AQ.

I beleive this would be a minor issue from using some of the TBC databases in the early days of the server and should be removed.

**Comment by Muigin** [comment]
This gameobject was not properly linked to the Midsummer Fire Festival. It will be fixed in an upcoming maintenance.
