### ISSUE TITLE
Fullscreen

### ISSUE THREAD

**Issue by olejrgen** [slowtorta/turtlewow-bug-tracker#4436]
**Please, provide a clear description what the bug is:**
Put the game off windowed mode, and now the game is just a black screen
**Steps to reproduce the behavior with as much detail as possible:**
1920x1080 res, and take off windowed mode.
1.
2. 
3. 

**IDs of affected creatures, items, quests or spells with a link to the relevant page:**

NPC: https://database.turtle-wow.org/?npc=
Item: https://database.turtle-wow.org/?item=
Quest: https://database.turtle-wow.org/?quest=
Spell: https://database.turtle-wow.org/?spell=
Object: https://database.turtle-wow.org/?object=

**Expected behavior. Describe how it should work:**

**Comment by slowtorta** [comment]
Please find the config located in your game folder: WoW/WTF/Config.wtf
Open it and add the following lines: 

SET gxWindow "1"
SET gxMaximize "1"

Save it and close it.
