### ISSUE TITLE
玩家-黑粗硬 萨满的地震术不能打断施法  风暴打击后续两次增加伤害无法触发

### ISSUE THREAD

**Issue by KevinZHOUZHEN** [slowtorta/turtlewow-bug-tracker#4437]
**Please, provide a clear description what the bug is:**

**Steps to reproduce the behavior with as much detail as possible:**

1.在敌人读条的时候 使用地震术无法打断施法
2. 风暴打击使用之后 有两次次数 敌人头像上永远显示两次次数 在期间使用技能没法触发增加20%孜然伤害的特效
3. 从1级到现在都一直无法触发

**IDs of affected creatures, items, quests or spells with a link to the relevant page:**

NPC: https://database.turtle-wow.org/?npc=
Item: https://database.turtle-wow.org/?item=
Quest: https://database.turtle-wow.org/?quest=
Spell: https://database.turtle-wow.org/?spell=
Object: https://database.turtle-wow.org/?object=黑粗硬

**Expected behavior. Describe how it should work:**

**Comment by Muigin** [comment]
请用英文提交问题。我们无法通过自动翻译准确地翻译中文提交的错误报告，这使得我们难以理解问题的确切性质。谢谢！

Please submit the issues in English. We're unable to accurately translate bug reports submitted in Chinese through automatic translation, which makes it difficult for us to understand the exact nature of the issue. Thank you!
