### ISSUE TITLE
Pyrewood Ambush Quest Credit for Shapeshifted Druids

### ISSUE THREAD

**Issue by Yakattack1466** [slowtorta/turtlewow-bug-tracker#4438]
**At the end of the quest, Pyrewood Ambush, you do not get quest credit if your character is in shapeshifted form:**

**Steps to reproduce the behavior with as much detail as possible:**

1. Start and progress the ambush quest as normal.
2. Remain in shapeshift form when quest NPC states "Well done. A blow to Arugal no doubt!"
3. Receive no credit when in shapeshift form.

**IDs of affected creatures, items, quests or spells with a link to the relevant page:**

NPC: https://database.turtle-wow.org/?npc=2058
Quest: https://database.turtle-wow.org/?quest=452

**Receive credit at the end of the quest objective regardless if you are shapeshifted or not:**

**Comment by Muigin** [comment]
Unaffected by shapeshift. Duplicate of #1708
