### ISSUE TITLE
Drop to 0 FPS coldridge valley

### ISSUE THREAD

**Issue by YamaYAML** [slowtorta/turtlewow-bug-tracker#4443]
**Please, provide a clear description what the bug is:**

DPS drop to 0 FPS Coldridge valley after tunnel going out of Coldridge Valley, reproduced on three characters. Reproduced with a fresh client by other player. Screenshots of location on map below.

**Steps to reproduce the behavior with as much detail as possible:**

1. Please move to approximate location on map (screemshots below) or per description with fresh client
2. Reproduce .gps

![dropfpslocation (1)](https://github.com/slowtorta/turtlewow-bug-tracker/assets/73019779/6caae87d-247e-41ca-9d3c-8de16eb2b14e)

![image](https://github.com/slowtorta/turtlewow-bug-tracker/assets/73019779/ba3e1d7d-ba43-4772-8422-1ec9614fa734)

**Expected behavior. Describe how it should work:**
Following should not have been reported by two users at the same location, reproduced with a fresh install: 

Raijinshi — Today at 10:32 PM
Are you asking me? As I've said, the dip down to 0 FPS starts after the tunnel going out of Coldridge Valley. I have reproduced this with 3 other characters, and the problem starts right before the tank with the NPC Mortar Squad. Everything else was buttery smooth up until that point

Anduin — Today at 10:33 PM
@Niral This is my location. I'm now playing on a fresh install
Image

Raijinshi — Today at 10:16 PM
Edit: Installed VanillaFixes, didn't work either. Running Windows 11, 4070 Ti, i7-13700kf, 32gb RAM. Still stumped. Changing nVidia Control Panel settings didn't help either (Power Management Maximum, OpenGL Rendring GPU to my GPU)

Has anyone else been getting this weird sudden dip in FPS? I went from basically 200+ all the way to 1-3 FPS and it seems like this problem is triggered ONLY when I advance past the tunnel in Coldridge Valley. Literally right before the tank with all the NPCs is the point where my game is essentially frozen. I created a new character to see whether was this just a fluke and everything is smooth up to the same area. Does anyone else have this issue? Tried it with both fresh installs and with my addons, nothing fixes or makes it any better/worst.

**Comment by YamaYAML** [comment]
Raijinshi — Today at 10:40 PM
The area the problem starts at!

https://cdn.discordapp.com/attachments/691438750185553950/1158141297106890792/image.png?ex=651b2aa2&is=6519d922&hm=c066fd159a4ff4a8307c53c099eadb7eba58e081a4c46f0a038bb5753ff9599b&

**Comment by YamaYAML** [comment]
https://cdn.discordapp.com/attachments/691438750185553950/1158139701522333867/dropfpslocation.png?ex=651b2926&is=6519d7a6&hm=c49b95d09f2fc0fb1f0142b694aca5494cfb3e7c91b6ab53c106ea2a323b1970&

**Comment by slowtorta** [comment]
Probably something summoned 100500 instances of GO or creatures that lag in one place.

**Comment by slowtorta** [comment]
Can't open Discord links.

**Comment by YamaYAML** [comment]
Thanks for the prompt action. Added as attachments, sorry.

**Comment by YamaYAML** [comment]
That wass twice the same, corrected attachments.

![dropfpslocation (1)](https://github.com/slowtorta/turtlewow-bug-tracker/assets/73019779/6caae87d-247e-41ca-9d3c-8de16eb2b14e)

![image](https://github.com/slowtorta/turtlewow-bug-tracker/assets/73019779/ba3e1d7d-ba43-4772-8422-1ec9614fa734)

**Comment by YamaYAML** [comment]
Reproduced myself. Niraltaz is at location, I'll leave a cli client running. ;)

**Comment by YamaYAML** [comment]
Confirmed issue is fixed. Can be closed. Tyvm!

Evidence: 
 - Logged in, inspected reported area 
 
![image](https://github.com/slowtorta/turtlewow-bug-tracker/assets/73019779/b15cda9a-55ef-45c0-9782-76797b9e8084)

**Comment by YamaYAML** [comment]
Fix confirmed! Thank you very much _o_
