### ISSUE TITLE
Pet shows happy all the time and abandons over time.

### ISSUE THREAD

**Issue by Fehrzie** [slowtorta/turtlewow-bug-tracker#4446]
**Please, provide a clear description what the bug is:**
I have a level 32 hunter. My pet has been always showing that he is happy even after death and being revived. I have fed him occasionally anyway. But even when showing happy and not being fed for about 30 minutes he will abandon me. After this happened with the first, I went into RFK to tame a bat. Bat instantly showed happy as well, but i was feeding often in order to increase loyalty. While trying to level, I had not fed for about 30 minutes and he abandoned me even after showing happy the entire time.

**Steps to reproduce the behavior with as much detail as possible:**

1. Tame pet
2. dont feed for short period of time
3. Pet abandons me

**IDs of affected creatures, items, quests or spells with a link to the relevant page:**

NPC: https://database.turtle-wow.org/?npc=
Item: https://database.turtle-wow.org/?item=
Quest: https://database.turtle-wow.org/?quest=
Spell: https://database.turtle-wow.org/?spell=
Object: https://database.turtle-wow.org/?object=

**Expected behavior. Describe how it should work:**
I would like to see when my pet is not happy, or know why he is abandoning me even when I feed the right food and he shows happy.

**Comment by Frechfuchs** [comment]
Did you try to clear your WDB folder? It may be an issue with your cache or addons. 
If you have any UI addons, try deactivating and see if you can reproduce the same error.
Trying with a level 14 hunter, taming and feeding works as intended.

**Comment by twowTurtReynolds** [comment]
Indeed, it could be an addons issue that wasn't displaying an unhappy pet indicator. Low loyalty rank pets require a _lot_ of food.
