### ISSUE TITLE
Steepcliff port inn not working

### ISSUE THREAD

**Issue by MrWackyPeanut** [slowtorta/turtlewow-bug-tracker#4447]
**Please, provide a clear description what the bug is:**
The Steepcliff port does not provide rested status and the fire in the fireplace does not allow cooking, which is especially egregious given that there is a cooking trainer right in front of it.

**Expected behavior. Describe how it should work:**

- The inn should provide rested xp.
- The fire in the fireplace should allow cooking.

**Comment by slowtorta** [comment]
Confirmed, not working.

**Comment by slowtorta** [comment]
This village isn't supposed to have an inn.
