### ISSUE TITLE
骑士职业任务BUG

### ISSUE THREAD

**Issue by hipniuw** [slowtorta/turtlewow-bug-tracker#4449]
**Please, provide a clear description what the bug is:**

**Steps to reproduce the behavior with as much detail as possible:**

1.骑士职业救赎任务取消重接以后，去救人以后，没有后续学技能的任务
2. 骑士20职业任务放弃后不能重接

**IDs of affected creatures, items, quests or spells with a link to the relevant page:**

NPC: https://database.turtle-wow.org/?npc=
Item: https://database.turtle-wow.org/?item=
Quest: https://database.turtle-wow.org/?quest=
Spell: https://database.turtle-wow.org/?spell=
Object: https://database.turtle-wow.org/?object=

**Expected behavior. Describe how it should work:**

**Comment by Frechfuchs** [comment]
To save some time, here are google translations:
title: "Warrior class quest BUG"
1. "After taking and abandoning the class quest for warriors, and after rescuing the people, there is no quest after to learn the actual skill"
2. "Warrior lv 20 quest can not be taken again after abandoning it"

**Comment by Muigin** [comment]
请用英文提交问题。我们无法通过自动翻译准确地翻译中文提交的错误报告，这使得我们难以理解问题的确切性质。谢谢！

Please submit the issues in English. We're unable to accurately translate bug reports submitted in Chinese through automatic translation, which makes it difficult for us to understand the exact nature of the issue. Thank you!
