### ISSUE TITLE
Warlock pet hitbox/auto attack range issue.

### ISSUE THREAD

**Issue by triana2021** [slowtorta/turtlewow-bug-tracker#445]
Warlock pets, apparently due to pathing and or hitbox size changes, are not able to properly auto attack a pursued target. 

The issue seems to extend to Lash of Pain which in Vanilla had a range just beyond that of melee, giving the succubus a  "chasing" power that was notable for a class with little otherwise. 

Furthermore, it seems that each attack is treated as having a cast time, meaning that the pet will need to stop briefly before  attacking. This means that the pet will get further and further behind with each melee strike until not being in range. The reduced effectiveness cannot be overstated.

The range of warlock pets melee attacks in general seems severely reduced from vanilla levels. This is very easily verified by watching any vanilla era pvp videos. Pet chases and continues to attack. On turtle wow this is most often not the case, with our pets stopping then attacking. Even in the open world fighting feared mobs pets are unable to maintain auto attacking as they should. 

This issue may well be related to pet movement speed.

**Comment by triana2021** [comment]
As of 3/26 issue persists.

**Comment by jameyboor** [comment]
Fixed on next update.
