### ISSUE TITLE
‘Glyph of Stars’ Functional failure

### ISSUE THREAD

**Issue by yinweiisme** [slowtorta/turtlewow-bug-tracker#4454]
**Please, provide a clear description of what the bug is:**
‘Glyph of Stars’ Functional failure

**Steps to reproduce the behavior with as much detail as possible:**

1.Glyph of Stars no effect

**IDs of affected creatures, items, quests or spells with a link to the relevant page:**
character name “saddream”
NPC: https://database.turtle-wow.org/?npc=
Item: https://database.turtle-wow.org/?item=
Quest: https://database.turtle-wow.org/?quest=
Spell: https://database.turtle-wow.org/?spell=
Object: https://database.turtle-wow.org/?object=

**Expected behavior. Describe how it should work:**

**Comment by slowtorta** [comment]
Delete your WDB folder while you clien is completely closed.
Right click on your glyhp items to learn them, new spells will appear in your spellbook.
Ensure that your client isn't using any modifications.
