### ISSUE TITLE
Glyph of the ice bear is not loading.

### ISSUE THREAD

**Issue by gcarof** [slowtorta/turtlewow-bug-tracker#4455]
**Please, provide a clear description what the bug is:**
Bear form uses the default model. I already grabbed and used the new glyph from my mail.

**Steps to reproduce the behavior with as much detail as possible:**

1. Delete the WBD folder and restarted the game, several times
2. Tried loading the game without Vanilla Fixes

**Comment by gcarof** [comment]
Character name: Stylian

**Comment by slowtorta** [comment]
Delete your WDB folder while you clien is completely closed.
Right click on your glyhp items to learn them, new spells will appear in your spellbook.
Ensure that your client isn't using any modifications.
