### ISSUE TITLE
"This account is already logged into World of Warcraft. Please check the spelling and try again."

### ISSUE THREAD

**Issue by Motnoir** [slowtorta/turtlewow-bug-tracker#4456]
**Please, provide a clear description what the bug is:**

**Steps to reproduce the behavior with as much detail as possible:**

1 I was disconnected  after patch and get this message every time im in.
2
![12](https://github.com/slowtorta/turtlewow-bug-tracker/assets/146815307/bdeb9ec0-9bee-4419-8942-59711ee5dbbe)
.I changed the password in my personal account but it didn't help
3. 

**IDs of affected creatures, items, quests or spells with a link to the relevant page:**

NPC: https://database.turtle-wow.org/?npc=
Item: https://database.turtle-wow.org/?item=
Quest: https://database.turtle-wow.org/?quest=
Spell: https://database.turtle-wow.org/?spell=
Object: https://database.turtle-wow.org/?object=

**Expected behavior. Describe how it should work:**

**Comment by spiff0** [comment]
Same issue. DC'ed and get same message on both accounts that were disconnected. Logging into a third account shows both characters are still online where they were dc'ed. Waited an hour to see if the afk timer would get my characters offline, both still online and both accounts still show same error

**Comment by twowTurtReynolds** [comment]
Please contact GMs about these issues.
