### ISSUE TITLE
The skills of Rogue have serious bug

### ISSUE THREAD

**Issue by xuanyepan** [slowtorta/turtlewow-bug-tracker#4457]
**Please, provide a clear description what the bug is: the flourish skill have a 6.67 min cooldown ??**

**Steps to reproduce the behavior with as much detail as possible:**

1.
![bug](https://github.com/slowtorta/turtlewow-bug-tracker/assets/66071818/1c3c1d9e-11aa-4b33-9db2-8aeed12189fb)

2. 
3. 

**IDs of affected creatures, items, quests or spells with a link to the relevant page:**

NPC: https://database.turtle-wow.org/?npc=
Item: https://database.turtle-wow.org/?item=
Quest: https://database.turtle-wow.org/?quest=
Spell: https://database.turtle-wow.org/?spell=
Object: https://database.turtle-wow.org/?object=

**Expected behavior. Describe how it should work:**

**Comment by MrTmp** [comment]
There is definitely something wrong with flourish's cooldown.
![image](https://github.com/slowtorta/turtlewow-bug-tracker/assets/134160202/d2ccd82b-624d-4b93-8291-f582ec242c28)

**Comment by Muigin** [comment]
This behavior should now be fixed serverside, but the client may display an incorrect cooldown until a clientside update can be pushed.
