### ISSUE TITLE
Reinstate Maximum PvP Rank 1.17.0

### ISSUE THREAD

**Issue by GrizB37** [slowtorta/turtlewow-bug-tracker#4458]
**Please, provide a clear description what the bug is:**
With this new change now once you achieve a certain rank you cannot fall below it, this will make the grind easier aswel as allowing to take brakes.

Unfortuantly the people who grinded their ass off for Rank14 are now left with the lower ranks like Knight-Captain.

This is a slap to the face for those that farmed to a high Rank back in the day.

**Expected behavior. Describe how it should work:**

Please enable an option at the NPC that disables PvP Rank to reinstate maximum PvP Rank again, or this shits on the old rankers big time.

Please don't make us go through the hell that is R13-14 again just to display a title we earned the hard way (over these new rankers)

Thanks

**Comment by Muigin** [comment]
This issue has been resolved.
