### ISSUE TITLE
Glyphs skins dosent work

### ISSUE THREAD

**Issue by neopumpki** [slowtorta/turtlewow-bug-tracker#4459]
**Please, provide a clear description what the bug is:**
Druid Glyphs skins cant worked properly even though it's in my inventory, and I can't put it on my keyring like before.
**Steps to reproduce the behavior with as much detail as possible:**

1.i do everyting that i was told byGM（delete WDB ）
2. I put all of them at my package and I cant put it on my keyring like before.
3. It not affect me

**IDs of affected creatures, items, quests or spells with a link to the relevant page:**
character name “neopumpkin”，item name“Glyph of the Forstsaber”，“Glyph of Stars”,“Glyph of the Ice Bear”,“Glyph of the Orca”
NPC: https://database.turtle-wow.org/?npc=
Item: https://database.turtle-wow.org/?item=
Quest: https://database.turtle-wow.org/?quest=
Spell: https://database.turtle-wow.org/?spell=
Object: https://database.turtle-wow.org/?object=

**Expected behavior. Describe how it should work:**

**Comment by slowtorta** [comment]
Delete your WDB folder while you clien is completely closed.
Right click on your glyhp items to learn them, new spells will appear in your spellbook.
Ensure that your client isn't using any modifications.
