### ISSUE TITLE
Can't gather Vessel of Dragon's Blood 

### ISSUE THREAD

**Issue by Tinyfin-github** [slowtorta/turtlewow-bug-tracker#446]
Can't gather Vessel of Dragon's Blood 

How it should work : For the quest Badlands Reagent Run II you use empty thaumaturgy vessels  on Scorched Guardian and you get Vessel of Dragon's Blood

What does not work: When you use empty thaumaturgy vessels  on Scorched Guardian you don't  get Vessel of Dragon's Blood but you get the message Invalid Target

Notes: Issue is similar to  https://github.com/slowtorta/turtlewow-bug-tracker/issues/435

https://database.turtle-wow.org/?quest=2501 Badlands Reagent Run II
https://database.turtle-wow.org/?npc=2726 Scorched Guardian
https://database.turtle-wow.org/?item=7866 Empty Thaumaturgy Vessel
https://database.turtle-wow.org/?item=7867#created-by Vessel of Dragon\'s Blood

![image](https://user-images.githubusercontent.com/83077166/141479681-efdcdb80-b044-463d-bfb9-7a77aa8c8c3b.png)

**Comment by slowtorta** [comment]
Fix one the next update.
