### ISSUE TITLE
Armorsmithing  unlearned

### ISSUE THREAD

**Issue by Zulsarok** [slowtorta/turtlewow-bug-tracker#4461]
**Please, provide a clear description what the bug is:**

**Steps to reproduce the behavior with as much detail as possible:**

1. Seen a lot of ppl talking about enw blacksmith rezepies in chat so i went to Org and bought all i could see
2. i may hit the Weaponspecialisation Blacksmith and unlearned Armorssmith specialisation
3. Ingame tells me im still Armorsmith and i checked i can buy  Armorsmithing Rezepies  and i did confirm by buying Stormgauntilets of sholomance Blacksmith npc

**IDs of affected creatures, items, quests or spells with a link to the relevant page:**

NPC: https://database.turtle-wow.org/?npc=     "Krathok Moltenfist" your DB side is off lol.. 
Quest: https://database.turtle-wow.org/?quest=
Spell: https://database.turtle-wow.org/?spell=
Object: https://database.turtle-wow.org/?object=

**Expected behavior. Describe how it should work:**
just pls help me out and mayby u can give me my previuous state of profession back so i dont lose months of rep grind and rezepies.  made already a vew GM tickets mentioning it not may an BUG ehre just a simple missclicking on a NPC that messed this all up.

**Comment by Muigin** [comment]
Working as intended.
