### ISSUE TITLE
Fiery Chain Girdle and Fiery Chain Shoulders being locked behind armorsmith

### ISSUE THREAD

**Issue by misandria69** [slowtorta/turtlewow-bug-tracker#4462]
In the 1.17 item changelog two thorium brotherhood blacksmithing items were suppose to change from being armorsmith to any blacksmith. The Fiery Chain Breastplate change has worked and I've obtained the pattern, the Fiery Chain Girdle AND Fiery Chain Shoulders are still locked to armorsmith.

https://puu.sh/JRp9n/b783043d26.png

https://puu.sh/JRpbg/1339f1aa39.jpg

**Comment by Dragunovi** [comment]
Should be fixed in the next scheduled server restart.
