### ISSUE TITLE
Moonkin Aura and Power of the Guardian don't stack

### ISSUE THREAD

**Issue by Velite12** [slowtorta/turtlewow-bug-tracker#447]
![image](https://user-images.githubusercontent.com/45871932/141522003-02eb08a8-1e17-4a76-a41e-3ac5e16b89d4.png)

Moonkin aura will remove atiesh "power of the guardian" when it is applied. They should stack.

Spell:
https://database.turtle-wow.org/?spell=28142
https://database.turtle-wow.org/?spell=28143
https://database.turtle-wow.org/?spell=28144
https://database.turtle-wow.org/?spell=28145
https://database.turtle-wow.org/?spell=24907

**Expected behavior. Describe how it should work:**
 
https://classic.warcraftlogs.com/reports/6kj9advbTQHfNFh4#fight=10&type=auras&pins=0%24Separate%24%23244F4B%24damage%240%240.0.0.Any%2432021719.0.0.Mage%24true%240.0.0.Any%24false%240&source=4

Mage with atiesh is able to receive moonkin aura

![image](https://user-images.githubusercontent.com/45871932/141522449-7b4a6773-d5f3-444d-a696-7aa517e2ec4b.png)

**Comment by slowtorta** [comment]
This will be fixed on the next update, thank you. 
![image](https://user-images.githubusercontent.com/66763404/159123754-3156b14d-45af-4fb3-8cc0-fa39f9204dc0.png)
![image](https://user-images.githubusercontent.com/66763404/159123760-19f49f89-38aa-4cb2-a1ea-1d75defb46ee.png)
