### ISSUE TITLE
Rested status is broken

### ISSUE THREAD

**Issue by Ennea** [slowtorta/turtlewow-bug-tracker#4474]
**Please, provide a clear description what the bug is:**

Thunder Bluff does not correctly grant the "rested" status to players, with mixed effects when logging out and back in in Thunder Bluff.

**Steps to reproduce the behavior with as much detail as possible:**

1. be in Mulgore
2. walk into Thunder Bluff
3. observe that you don't have the rested status

Additionally:

1. be in Thunder Bluff without rested status
2. walk out into Mulgore
3. observe that you're suddenly rested

**Expected behavior. Describe how it should work:**

Players should be properly rested when being inside Thunder Bluff :)

The steps above were tested with an empty WDB folder.

**Edit:** I've tested some more, and rested status feels broken in general. I could reproduce a similar issue in Orgrimmar as well, and I'm wondering if it's relates to tents. A tent was placed in front of OG, and I did not lose rested status after moving away from it. I then logged out in Durotar, logged back in and moved closer to the tent again until I got rested status again. I then moved away from the tent once more but did once again not lose my rested status.

Very strange!

**Comment by slowtorta** [comment]
Cannot reproduce, working as intended.

**Comment by Ennea** [comment]
Thanks for checking, but I can still reproduce this. Here's a video of it in action. In the beginning, I'm still in TB and resting. Then I move into Mulgore, am _still_ resting. Then go back to TB and am not resting. And, what I've found it: when in the city and not resting, moving into a building and back out sets my state to resting properly.

https://github.com/slowtorta/turtlewow-bug-tracker/assets/3466414/c6160a5f-8ada-4ec8-a225-74f6dae09ed2
