### ISSUE TITLE
"Welcome to Amani'Alore" does not work

### ISSUE THREAD

**Issue by DzikCrakehall** [slowtorta/turtlewow-bug-tracker#4475]
The quest "Welcome to Amani'Alore" does not work, taking the quest from the troll in Razor Hill, completing it next to the Thrall in Warchief room, I was sent to "The Valley of Spirits", completing the quest, NPC "Deino" does NOT GIVE the new quest that it should give , the teleport is ALREADY active, and I can get to Amani'Alore. You can’t talk to anyone in the location (previously, having taken a new quest from “Deino”, I completed it from the NPC “Guay’Jin” and could already complete daily quests, and I could also take the quest to “take the doll” from the troll upstairs) now Well, I was able to take the quest from the troll upstairs, but it led to the NPC "Guay'Jin", she didn’t want to accept the quest, the GM advised me to delete the WDB folder, it didn’t help, canceling this quest I can’t even take it again.

The database is not available, I can’t specify anything. What a brilliant decision not to limit new content, but to completely close the database :)

**Comment by slowtorta** [comment]
Should be fixed.
