### ISSUE TITLE
Warlock t2 itemization

### ISSUE THREAD

**Issue by Envasion** [slowtorta/turtlewow-bug-tracker#4476]
Warlock’s t2 Nemesis gloves lack +1% hit chance which is enlisted in itemization changelog (can’t link db because it’s not working right now).

**Comment by xmortex** [comment]
Gloves are still showing the vanilla values instead of the updated patch notes: Nemesis Gloves: [+15 Intellect, +20 Stamina, +1% Spell Hit, +20 Spellpower, +10 Shadow Resistance]  Any updates?
