### ISSUE TITLE
.exe files missing

### ISSUE THREAD

**Issue by KanyonWyman** [slowtorta/turtlewow-bug-tracker#4477]
**Please, provide a clear description what the bug is:**

Since 1.17 when playing the game it will suddenly close, no errors or anything.
When I try to open the game from the shortcut it says the path cannot be found.
Check the twow folder and all .exe applications are gone
reinstall the entire client 
.exes are still missing from the folder

**Steps to reproduce the behavior with as much detail as possible:**

1. Reinstall
2. 
3. 

**IDs of affected creatures, items, quests or spells with a link to the relevant page:**

NPC: https://database.turtle-wow.org/?npc=
Item: https://database.turtle-wow.org/?item=
Quest: https://database.turtle-wow.org/?quest=
Spell: https://database.turtle-wow.org/?spell=
Object: https://database.turtle-wow.org/?object=

**Expected behavior. Describe how it should work:**

**Comment by KanyonWyman** [comment]
I think the problem was with windows defender thinking the the file was a virus. Will report back if anything happens again.

**Comment by slowtorta** [comment]
That's correct, I hope it's resolved now :)
