### ISSUE TITLE
Human hunter attack not working correctly

### ISSUE THREAD

**Issue by Micknator** [slowtorta/turtlewow-bug-tracker#4479]
**Please, provide a clear description what the bug is:**
Odd question maybe, but I made a human hunter but when I attack a target at range, it does nothing (except for saying I'm too far away, for melee), I need to use the autoshot ability for ranged and switch to normal attack when the enemy is closeby. Now from what I remember from playing a hunter on WoW Classic is that an attack is an attack and will automatically change between ranged and melee.

**Steps to reproduce the behavior with as much detail as possible:**

1. Make a human hunter
2. Attack your target
3. 

**IDs of affected creatures, items, quests or spells with a link to the relevant page:**

NPC: https://database.turtle-wow.org/?npc=
Item: https://database.turtle-wow.org/?item=
Quest: https://database.turtle-wow.org/?quest=
Spell: https://database.turtle-wow.org/?spell=
Object: https://database.turtle-wow.org/?object=

**Expected behavior. Describe how it should work:**
Normally you'd expect the attack to decide by itself whether it should be ranged or melee and switch on the fly if the target comes closer.

**Comment by Haaxor1689** [comment]
This is how it works on all hunters, right-clicking on vanilla doesn't start auto-shot
