### ISSUE TITLE
Night elfs start at hated , at lv 1, with Durotar Labour Union without discovering them

### ISSUE THREAD

**Issue by Tinyfin-github** [slowtorta/turtlewow-bug-tracker#448]
Night elfs start at hated , at lv 1, with Durotar Labour Union without discovering them

No other factions starts at hated at lv 1 without encountering the faction.

Faction id 1001 - Durotar Labor Union 

![WoW_ROSomvIBoM](https://user-images.githubusercontent.com/83077166/141668441-77e0e6e8-d838-4959-a1b4-160472a6a016.png)

**Comment by slowtorta** [comment]
Included in https://github.com/slowtorta/turtlewow-bug-tracker/issues/449
