### ISSUE TITLE
Glyph of Self-Restraint

### ISSUE THREAD

**Issue by GoldenSpatula69** [slowtorta/turtlewow-bug-tracker#4484]
**This glyph seems not to work at all, as it cannot be applied on the player and has no explanation on what it does on glyph vendors. The glyph is, for some reason, unusable and stored in the keyring.**

**Steps to reproduce the behavior with as much detail as possible:**

1. Go to any glyph vendor.
2. Notice that, despite no description (Gossip option to get a deeper explanation) it can be purchased.
3. Purchase it, only to notice it has no effect whatsoever.
4. Unlike other glyphs, it won't have a "on-use" effect.

**IDs of affected creatures, items, quests or spells with a link to the relevant page:**

**Expected behavior. Describe how it should work:** The item should allow to accept the additional challenge, which renders you unable to use the gambling npcs.

![image](https://github.com/slowtorta/turtlewow-bug-tracker/assets/130491945/790bed33-89c6-488c-a1d9-77932748c8bb)
![image](https://github.com/slowtorta/turtlewow-bug-tracker/assets/130491945/c2b55e53-3980-4f1b-b182-cd513f9de85f)

**Comment by cyaohiri** [comment]
It probably works similar to how stag form works for druids. It's applied as long as you have it in your bags. See if you can gamble with it in your keyring, and then try to move it to your bank or destroy it, and try again.
Whether this was intended or not, I do not know.

**Comment by slowtorta** [comment]
This is the intended behavior.
