### ISSUE TITLE
Brutal Armor quest not completable

### ISSUE THREAD

**Issue by srp92580** [slowtorta/turtlewow-bug-tracker#4486]
**Please, provide a clear description what the bug is:**
unable to turn in warrior class quest 'Brutal Armor'
**Steps to reproduce the behavior with as much detail as possible:**

1.accept quest
2. gather materials
3. attempt to turn in

**IDs of affected creatures, items, quests or spells with a link to the relevant page:**

NPC: https://database.turtle-wow.org/?npc=5878
Item: https://database.turtle-wow.org/?item=7126, 7127, 3575, 6841, 7587
Quest: https://database.turtle-wow.org/?quest=1838
Spell: https://database.turtle-wow.org/?spell=
Object: https://database.turtle-wow.org/?object=

**Expected behavior. Describe how it should work:**
I should be able to turn in the quest and receive the next quests in the chain to get my set of brutal armor.  Character: Medad

**Comment by Muigin** [comment]
Cannot reproduce on current version.  Please be sure to clear WDB and try again.
