### ISSUE TITLE
Gnome Hunter's Level 10 quest taming Invalid Target

### ISSUE THREAD

**Issue by Drizzens** [slowtorta/turtlewow-bug-tracker#4489]
**Please, provide a clear description what the bug is:**
Gnome Hunter's Level 10 quest unable to progress due to taming an "invalid target"
**Steps to reproduce the behavior with as much detail as possible:**

1. Started Gnome Hunter's level 10 Quest at Ironforge
2. Walked back into Kharanos to start the Taming quest chain
3. Unable to tame Large Crag Boar because its a Invalid Target

**IDs of affected creatures, items, quests or spells with a link to the relevant page:**

NPC: https://www.wowhead.com/classic/npc=1126/large-crag-boar
Item: https://www.wowhead.com/classic/item=15911/taming-rod

**Expected behavior. Describe how it should work:**
It should work like every other race hunter quests. Ask your trainer for quest, start taming once you have the taming rod(s), go back to trainer then back to City to finish it all up.
![WoWScrnShot_100323_153140](https://github.com/slowtorta/turtlewow-bug-tracker/assets/103557609/58e12245-43c4-4d70-b962-d2440c3ff943)

**Comment by slowtorta** [comment]
Clear your WDB folder, this issue has been resolved.
