### ISSUE TITLE
Bug with vanilla quest called The Woodpaw Gnolls

### ISSUE THREAD

**Issue by TehDanny** [slowtorta/turtlewow-bug-tracker#4491]
**Please, provide a clear description what the bug is:**
A few minutes ago I completed a quest called "The Woodpaw Gnolls", where I followed the tips written by killbillone in a comment. There is nothing hanging on the side of the large tree. I clicked on the correct area and completed the quest, but nothing is hanging there. I should add that I looked at the images on wowhead and saw how it was supposed to look like.

**Steps to reproduce the behavior with as much detail as possible:**
I don't know if you're required to have the quest or not in order to see the thing on the tree, all I know is going to the location and noticing that nothing is there.

**IDs of affected creatures, items, quests or spells with a link to the relevant page:**
https://www.wowhead.com/classic/quest=4131/the-woodpaw-gnolls
https://www.wowhead.com/classic/quest=4131/the-woodpaw-gnolls#screenshots

**Expected behavior. Describe how it should work:**
There should be a thing on the tree which is interactable, but although it was interactable it wasn't there, or it was invisible.

**Comment by Muigin** [comment]
The quest object has been moved to its proper place.

Fixed.
