### ISSUE TITLE
certain items n ot reflecting patch note changes

### ISSUE THREAD

**Issue by oMahka** [slowtorta/turtlewow-bug-tracker#4492]
**Please, provide a clear description what the bug is:**
some of my items are not reflecting the changes that were stated in the patch notes. most notably my nemesis gloves.
**Steps to reproduce the behavior with as much detail as possible:**

1.
2. 
3. 

**IDs of affected creatures, items, quests or spells with a link to the relevant page:**

NPC: https://database.turtle-wow.org/?npc=
Item: https://database.turtle-wow.org/?item=Nemesis Gloves
Quest: https://database.turtle-wow.org/?quest=
Spell: https://database.turtle-wow.org/?spell=
Object: https://database.turtle-wow.org/?object=

**Expected behavior. Describe how it should work:**

**Comment by oMahka** [comment]
due to the database being down i was unable to link the gloves sorry

**Comment by Frechfuchs** [comment]
What is the expected behaviour?

**Comment by oMahka** [comment]
Nemesis Gloves: [+15 Intellect, +20 Stamina, +1% Spell Hit, +20 Spellpower, +10 Shadow Resistance]

from the patch notes

**Comment by oMahka** [comment]
is this a known problem or were the patch notes incorrect?

**Comment by oMahka** [comment]
any word on if this will be a bug fix in the future? or will the gloves stay as they are?

**Comment by luskanek** [comment]
Will be fixed in the next maintenance update.
