### ISSUE TITLE
All skins of purchased druids cannot be displayed properly, and the glyph cannot be used

### ISSUE THREAD

**Issue by 610266657** [slowtorta/turtlewow-bug-tracker#4493]
**Please, provide a clear description what the bug is:**

**Steps to reproduce the behavior with as much detail as possible:**

1.All skins of purchased druids cannot be displayed properly, and the glyph cannot be used
2. 
3. 

**IDs of affected creatures, items, quests or spells with a link to the relevant page:**

NPC: https://database.turtle-wow.org/?npc=
Item: https://database.turtle-wow.org/?item=
Quest: https://database.turtle-wow.org/?quest=
Spell: https://database.turtle-wow.org/?spell=
Object: https://database.turtle-wow.org/?object=

**Expected behavior. Describe how it should work:**

**Comment by luskanek** [comment]
Try deleting your WDB folder. Druid glyphs are now spells that can be learned and have a custom tab in the spellbook, check there.

**Comment by slowtorta** [comment]
Delete your WDB folder while you clien is completely closed.
Right click on your glyhp items to learn them, new spells will appear in your spellbook.
Ensure that your client isn't using any modifications.
