### ISSUE TITLE
Hostile Questgiver in Grommash

### ISSUE THREAD

**Issue by Stainelemange** [slowtorta/turtlewow-bug-tracker#4495]
**Please, provide a clear description what the bug is:**
Questgiver Volz'draza in Grommash Hold is hostile to some players.  I have witnessed her kill at least one HC character (not me), but let others turn in quests without issue.  On my screen, ShaguPlates indicates she is yellow nuetral which would turn hostile if you right click.  The same right click as trying to talk to the NPC.  Level indicator for her is in red.

**Steps to reproduce the behavior with as much detail as possible:**

1.  Walk up to questgiver.
2.  Attempt to turn in quest.
3.  Get killed by her.

**IDs of affected creatures, items, quests or spells with a link to the relevant page:**

NPC: https://database.turtle-wow.org/?npc=
Item: https://database.turtle-wow.org/?item=
Quest: https://database.turtle-wow.org/?quest=
Spell: https://database.turtle-wow.org/?spell=
Object: https://database.turtle-wow.org/?object=

**Expected behavior. Describe how it should work:**
Questgiver should allow all horde players to obtain or turn in quest without being attacked by the questgiver.

**Comment by Muigin** [comment]
This behavior has been fixed in a previous update.
