### ISSUE TITLE
Vampirism not additive.

### ISSUE THREAD

**Issue by Despacitogang** [slowtorta/turtlewow-bug-tracker#4497]
Please, provide a clear description what the bug is:
Vampirism stat does not work as intended. Instead of stacking (3 piece's of 1% vampirism gear additive and 1 peice of 2% vampirism gear -> 5% total vampirism) it instead just applies whichever peices is highest, essentially rendering the stat worthless. (3 piece's of 1% vampirism gear additive and 1 peice of 2% vampirism gear -> 2% total vampirism)

Steps to reproduce the behavior with as much detail as possible:

Equip Greymane Spaulders
Equip Darkmoon Ring
Equip Greymane Helmet.
Attempt to turn in quest.
Observe 2% vampirism when should be 4%

Turtle wow Database is down for the public so I cannot link the proper items :(
IDs of affected creatures, items, quests or spells with a link to the relevant page:

NPC: https://database.turtle-wow.org/?npc=
Item: https://database.turtle-wow.org/?item=
Quest: https://database.turtle-wow.org/?quest=
Spell: https://database.turtle-wow.org/?spell=
Object: https://database.turtle-wow.org/?object=

Expected behavior. Describe how it should work:
Vampirism should follow the additive property.

**Comment by TWShang** [comment]
I recently tested this on live, the effects are additive, but they do not show up in the combat log, and do not show up over the character portrait in green text. This is because every stat is individually calculated and done separately. We removed it from the combat log due to the absolute spam of the effect but it does work properly.

**Comment by XanderScotton** [comment]
> I recently tested this on live, the effects are additive, but they do not show up in the combat log, and do not show up over the character portrait in green text. This is because every stat is individually calculated and done separately. We removed it from the combat log due to the absolute spam of the effect but it does work properly.

I have run a few tests and cannot get Vampirism to stack, and it even seems to conflict based on gear slot go overwrite previous values (see last test).

I have 3 pieces of gear, 2x Darkmoon Rings, and Bracers with 1% vampirism enchant.

The below tests were run on a warrior, using bloodrage to self inflict damage and to enter combat disabling regen.
Calculations were done using real health numbers, ignoring the portrait green text.

Test 1 :
1x Darkmoon Ring Equipped (2% total)
Mele Swing for 309, health goes from 3432  to 3438. Expected heal for 6, heals for 6 (2% healing as expected)

Test 2:
2x Darkmoon ring equipped (4% total)
Mele swing for 342, health goes from 3532 to 3538. Expected heal for 13,  **heals for 6** (only 2%, should be 4%)

Test 3:
2x Darkmoon + Vampirism Brace (5% total) 
Mele swing for 332, health goes from 3632 to  3635 expected heal for 16, **heals for 3** (1% total)

**Comment by dkmnllth** [comment]
I just tested this as well. Vampirism is not stacking. With 8% vampirism equipped I was only getting 2% vampirism. For example, a 1k Holy Shock crit healed me for about 20 hit points, which lines up w/ a 2% vampirism rate (from my highest vampirism item).

**Comment by dkmnllth** [comment]
> I recently tested this on live, the effects are additive, but they do not show up in the combat log, and do not show up over the character portrait in green text. This is because every stat is individually calculated and done separately. We removed it from the combat log due to the absolute spam of the effect but it does work properly.

Can you go into more detail on this? What you did to test? Because we are not getting the same results on live and the issue was closed due to your comment. @TWShang
