### ISSUE TITLE
Orvan Darkeye bugged questgiver in Gilneas

### ISSUE THREAD

**Issue by Niqlo** [slowtorta/turtlewow-bug-tracker#4498]
**Please, provide a clear description what the bug is:**

**Steps to reproduce the behavior with as much detail as possible:**

1. pick up quest to kill lingering skeletons and shambling dead
2. don't pick up vilewing blood quest
3. after finishing you will be locked out of any of the quest giver's other quests

**Expected behavior. Describe how it should work:**
Originally I could see a follow up quest that it said I do not meet the requirements to pick up. That too has disappeared now. He currently has no quests available to me but I've seen him offer two others that I was unable to pick up

**Comment by Tlaklife** [comment]
Just happend to me too, still not fixed.
