### ISSUE TITLE
A hidden buff with 0 seconds remaining, cancels it and the game reports an error 

### ISSUE THREAD

**Issue by YoungMrMau** [slowtorta/turtlewow-bug-tracker#4499]
**Please, provide a clear description what the bug is:**

My druid has an extra buff with 0 seconds remaining, and if I cancel this buff, the game will report an error and automatically close. To add, after I updated the game, the Glyph of Bucks ran from the keychain to the backpack and I used it. （character : Frappe）
![BUG](https://github.com/slowtorta/turtlewow-bug-tracker/assets/146922842/0e7f48a3-8ddf-48a0-a606-26f112324b53)
![BUG1](https://github.com/slowtorta/turtlewow-bug-tracker/assets/146922842/9c759e24-7e36-41d8-aaa6-474c9f55b64e)

**Steps to reproduce the behavior with as much detail as possible:**

1. After the character enters the world, a buff is stationed in the upper right corner, and the remaining time is 0 seconds
2. If you cancel the buff, the game will report an error and crash
3. I think the problem might be that I'm using the Glyph of Bucks
4. character : Frappe

**IDs of affected creatures, items, quests or spells with a link to the relevant page:**

NPC: https://database.turtle-wow.org/?npc=
Item: https://database.turtle-wow.org/?item=
Quest: https://database.turtle-wow.org/?quest=
Spell: https://database.turtle-wow.org/?spell=
Object: https://database.turtle-wow.org/?object=

**Expected behavior. Describe how it should work:**

**Comment by cyaohiri** [comment]
Have you tried moving the glyph to your bank first? If appropriate, see if the buff will be removed properly if your character dies.

**Comment by twowTurtReynolds** [comment]
What is this glyph of bucks you speak of? I cannot find it: https://database.turtle-wow.org/?search=glyph+of

Other glyphs don't seem to have this problem.

If you can provide clear replication steps, ping me so I can test them.

**Comment by cyaohiri** [comment]
> What is this glyph of bucks you speak of? I cannot find it: https://database.turtle-wow.org/?search=glyph+of

They're probably referring to [Glyph of the Stag](https://database.turtle-wow.org/?item=51056).

**Comment by twowTurtReynolds** [comment]
Right, of course.

![image](https://github.com/slowtorta/turtlewow-bug-tracker/assets/151180101/cf29beaa-35d4-4a28-8835-06a0eff65451)

I am unable to reproduce the issue however, I have no clue how they got themselves into that state.

![image](https://github.com/slowtorta/turtlewow-bug-tracker/assets/151180101/dcd5c974-0487-4afb-b08f-157243249ab7)

The first spell seems to be the item's spell to learn once.
The second is the aura that the spellbook applies. This doesn't have that issue in the report.
The third is the spell that sits in the spellbook, to toggle the second.
All seem to work fine.
