### ISSUE TITLE
Minor Error when using flight masters.

### ISSUE THREAD

**Issue by Strongbone101** [slowtorta/turtlewow-bug-tracker#45]
By opening this Issue, I admit to having done the pertinent research using sources from Vanilla (preferably) or Classic. I also understand that sources from other private servers are not acceptable.

**Current behavior**: When I use a Flight Path on my Goblin Rouge, I end up getting an error that states "Can't fly while looting" even though I'm not looting anything, and proceed to instead Swim through the Air vigorously to my chosen location

**Expected behavior**: The get on a flying mount and fly their normally, and not receive the error message

**Proofs**: 
![image](https://user-images.githubusercontent.com/85890157/121915438-343ce700-cd01-11eb-8757-dd282198aa07.png)

**Steps to reproduce**:

1. (Optional) Sell items to a nearby vendor, go to the buyback window, and then close the vendor window (It's the one thing I could think of me doing before choosing a flight path)
2. Pick a Flight Path from a Flight Master
3. Vigorously swim to your location

**Comment by Nolin7777** [comment]
Tested on various vendors and flight master, sadly not reproducable
