### ISSUE TITLE
the gnome hunter's taming quest out of work

### ISSUE THREAD

**Issue by arthurlxf** [slowtorta/turtlewow-bug-tracker#4501]
**Please, provide a clear description what the bug is:**
the gnome hunter cant do the lv10 hunter taming quest cause the quest item cant work and always tips invalid target
**Steps to reproduce the behavior with as much detail as possible:**

1.the gnome hunter at lv10 get the quest named Taming the beast
2. get the quest item to taming a large crag boar
3. select the large crag boar and use the quest item then it not work and will tips invalid target
4. I've tried delete the wdb dir, reget the quest, still not work

**IDs of affected creatures, items, quests or spells with a link to the relevant page:**

NPC: https://database.turtle-wow.org/?npc=
Item: https://database.turtle-wow.org/?item=
Quest: https://database.turtle-wow.org/?quest=
Spell: https://database.turtle-wow.org/?spell=
Object: https://database.turtle-wow.org/?object=

**Expected behavior. Describe how it should work:**

**Comment by Drizzens** [comment]
I already made a issue about this quest yesterday.  No answer about it yet.  My assumption is because the entity of the boar is changed due to the recent patch or something went wrong with the quest due to Human Hunters which are of the same faction and originally not included in vanilla.

**Comment by slowtorta** [comment]
Clear your WDB folder, this issue has been resolved.
