### ISSUE TITLE
Ornate Bloodstone Dagger on Druid

### ISSUE THREAD

**Issue by LiviuOLV** [slowtorta/turtlewow-bug-tracker#4504]
Ornate Bloodstone Dagger

Equip: Your landing damaging spells have a chance on sacrificing 250 of your health and dealing 250 Fire damage.

On druid, the dagger doesn't do damage to the target. As a matter of fact, the dagger instead only works when a druid changes forms and it takes 500 fire damage, meaning I believe both parts of the weapon effect, the sacrifice HP effect and the fire damage part, assuming the spell (Shapeshift) counts as the druid being the target of the spell.

**Steps to reproduce the behavior with as much detail as possible:**

Equip Ornate Bloodstone Dagger with the "Elemental Cat Build", which requires the following items: Incendosaur Skin Set (Gloves, Boots, Shoulders), Repaired Electro-Lantern. These are the core items, you can also equip Blazefury Medallion (Kazzak) and Hide of the Thunder Lizard (H) but are not a must. Use the dagger in main hand and test on any target. Checking combat log will show that the dagger is not procing on the target

1. Equip Ornate Bloodstone Dagger with the "Elemental Cat Build", which requires the following items: Incendosaur Skin Set (Gloves, Boots, Shoulders), Repaired Electro-Lantern. These are the core items, you can also equip Blazefury Medallion (Kazzak) and Hide of the Thunder Lizard (H) but are not a must.
2. Use the dagger in main hand and test on any target with melee attacks. Checking combat log will show that the dagger is not procing on the target, even tho the spell damage landed by the item procs does.  Spells WILL NOT proc the dagger effect either (Moonfire, Wrath, Starfire, Insect Swarm).
3. Using Shapeshift abilities will make the druid take 500 damage from the dagger, both the sacrifice part of the dagger and the damage part, all taken as fire damage.

Judging that Ornate Bloodstone Dagger has the same wording and effect as Blade of Eternal Darkness (Equip: Chance on landing a damaging spell to deal 100 Shadow damage and restore 100 mana to you), I would assume they should work close to the same extent. Even if it's not working with the "Elemental Cat" build, the dagger itself IT's NOT procing on spells either. I only tested on a druid, not sure if other classes have the same issues.

**IDs of affected creatures, items, quests or spells with a link to the relevant page:**

At this given moment we are not allowed to check Turtle WoW Database, as such I cannot provide any links (or at least I as a user cannot).

**Expected behavior. Describe how it should work:**

Not having this item before it's a bit tricky to specify this, but if we are to take Blade of Eternal Darkness as an example, given they have the same wording, when you're attacking in shapeshift form using the stated gear from earlier, there should be a chance, when the spell damage provided by the items occur a proc on melee damage dealt (auto attacks, shred, claw) those magic damage procs SHOULD have a chance to proc the dagger effect. The dagger effect being sacrificing 250 of the playable character HP (most probably intended as fire damage, working as a form of life tap if you would) and dealing 250 fire damage to the target to which you had dealt the magic damage to. 

If further materials are needed to fix this issues I will be happy to procure such materials.

Thank you for your time, love the new patch, hope to see this issue fixed soon, I believe in the Dev Team <3

**Comment by OonaFae** [comment]
Can you confirm if this is still an issue? A recent update I believe should have fixed this issue. 
https://forum.turtle-wow.org/viewtopic.php?t=10588
If its not fixed it would be a good additional note on this thread.

**Comment by LiviuOLV** [comment]
> Can you confirm if this is still an issue? A recent update I believe should have fixed this issue. https://forum.turtle-wow.org/viewtopic.php?t=10588 If its not fixed it would be a good additional note on this thread.

Yes. This is still an ongoing problem.

**Comment by VSReyden** [comment]
> Can you confirm if this is still an issue? A recent update I believe should have fixed this issue. https://forum.turtle-wow.org/viewtopic.php?t=10588 If its not fixed it would be a good additional note on this thread.

Yes. Nothing has changed so far. Still waiting for the fix. It's impossible to play normally with this dagger.

**Comment by OonaFae** [comment]
I got this dagger on my shaman and confirmed that the proc only occurs when the dagger is equipped. No attacks or spells are triggering the effect. Definitely hoping for a higher priority on getting this fixed as it is quite a costly item to have crafted.
