### ISSUE TITLE
Female orc uses wrong animation when falling

### ISSUE THREAD

**Issue by StrawberryBrains** [slowtorta/turtlewow-bug-tracker#4505]
**Please, provide a clear description what the bug is:**

**Steps to reproduce the behavior with as much detail as possible:**

1. be female orc
2. jump from a height
3. watch as your falling animation is just the being stunned animation

**IDs of affected creatures, items, quests or spells with a link to the relevant page:**

female orcs

**Expected behavior. Describe how it should work:**

the falling animation should be shown instead of the being stunned animation

**Comment by luskanek** [comment]
I was not able to replicate this issue. Can you please post a video? Are you using the HD patch by any chance?
