### ISSUE TITLE
New Shield (Marshal's Blocker) drop from Gilneas City doesnt have a Block Value

### ISSUE THREAD

**Issue by kugelfisch1992** [slowtorta/turtlewow-bug-tracker#4506]
**Please, provide a clear description what the bug is:**
New Shield (Marshal's Blocker) drop from Gilneas City doesnt have a Block Value. 

**Steps to reproduce the behavior with as much detail as possible:**

1. Find Item
2. Equip Item

**IDs of affected creatures, items, quests or spells with a link to the relevant page:**

Cannot access turte database atm

NPC: The Marshal something Boss from Gilneas City
Item: Marshal's Blocker

**Expected behavior. Describe how it should work:**

Item should have a block value 

PS: I'd love to get the working item again if it is fixed fast or maybe get a similar shield in exchange my characters name is Snagr

**Comment by SignOfTheRaven** [comment]
I've found the same issue with Marshal's Blocker not having block value.
![Marshal's Blocker](https://github.com/slowtorta/turtlewow-bug-tracker/assets/122130391/b24699c9-2e88-4e02-9bba-e52fe7cfe85a)

**Comment by Muigin** [comment]
This has been fixed in a previous update.
