### ISSUE TITLE
Learned Cleaning Cloth Recipe but it does not show in survival profession window

### ISSUE THREAD

**Issue by Oxydrene** [slowtorta/turtlewow-bug-tracker#4508]
**Please, provide a clear description what the bug is:**
My character Oxyydrena learned the cleaning cloth recipe for the survival profession but it does not show in my professions window.

**Steps to reproduce the behavior with as much detail as possible:**

1. Purchased the cleaning cloth recipe on character Oxyydrena
2. Learned the recipe
3.  Open the Survival profession window and it is not there but I can not learn the recipe again.

**IDs of affected creatures, items, quests or spells with a link to the relevant page:**

NPC: https://database.turtle-wow.org/?npc=
Item: https://database.turtle-wow.org/?item=
Quest: https://database.turtle-wow.org/?quest=
Spell: https://database.turtle-wow.org/?spell=
Object: https://database.turtle-wow.org/?object=

**Expected behavior. Describe how it should work:**

**Comment by slowtorta** [comment]
Will be fixed in patch 1.17.1.
