### ISSUE TITLE
Blacksmithing trainers in UC/OG/TB do not teach belt buckles

### ISSUE THREAD

**Issue by ghazette** [slowtorta/turtlewow-bug-tracker#4509]
**Please, provide a clear description what the bug is:**
Blacksmithing trainers in UC/OG/TB do not teach belt buckles

**Steps to reproduce the behavior with as much detail as possible:**

1.
2. 
3. 

**IDs of affected creatures, items, quests or spells with a link to the relevant page:**

NPC: https://database.turtle-wow.org/?npc=
Item: https://database.turtle-wow.org/?item=
Quest: https://database.turtle-wow.org/?quest=
Spell: https://database.turtle-wow.org/?spell=
Object: https://database.turtle-wow.org/?object=

**Expected behavior. Describe how it should work:**

**Comment by Muigin** [comment]
There are new vendors in new shops in Stormwind and Undercity who sell the recipes for the 4 starter belt buckles.  These spells are not taught by trainers.

Working as intended.
