### ISSUE TITLE
Unable to leave hardcore channel - auto-ticked on channel changes

### ISSUE THREAD

**Issue by robs898** [slowtorta/turtlewow-bug-tracker#4511]
**Please, provide a clear description what the bug is:**
The new Hardcore chat channel added in 1.17.0 is bugged as it is impossible to leave it (remove from chat window). If you uncheck it from chat it will comeback when you change channel e.g. general channel or join guild recruitment.

**Steps to reproduce the behavior with as much detail as possible:**

1. Be hardcore character
2. Dont be in a guild
3. Stand in capital city e.g. stormwind
4. Go to chat settings -> channels -> untick Hardcore and guild recruitment and General
5. Enable auto-join guild recruitment in interface settings
6. go to chat settings -> channels -> see that Hardcore is ticked again (as well as guild recruitment - which is expected) but General remains unticked

**Expected behavior. Describe how it should work:**
You should auto-join Guild recruitment channel but you should not have Hardcore channel re-ticked, that should be unticked.

**Comment by cyaohiri** [comment]
Use this addon until the bug gets fixed: https://github.com/Lexiebean/TurtleHCFilter
You can also use the _.hcchat_ command to disable it entirely.

**Comment by twowTurtReynolds** [comment]
Confirmed this issue still persist on PTR with latest patch-5

**Comment by Muigin** [comment]
Fixed in the next patch.
