### ISSUE TITLE
Old glyph of the ice bear is gone

### ISSUE THREAD

**Issue by uixandy** [slowtorta/turtlewow-bug-tracker#4516]
**Please, provide a clear description what the bug is:**
I bought the old glyph of the ice bear before the new patch was released, the white one that looks like a mob and not the new white one that is the recolored original bear form one. But since the patch my old glyph is gone and nowhere to find, not in my bags, nor bank nor in collections tab. I only got the new one. Is this meant to be? So the new glyph replaces the old one? That would be sad as it makes it even more exciting to buy them when we know they will become legacy content.

Thats the glyph I bought some days ago, before the new content patch released
![image](https://github.com/slowtorta/turtlewow-bug-tracker/assets/74785449/94545c3a-e31f-4953-8b80-df5aaf8f9c17)

Character name: Jimyapey

**Comment by slowtorta** [comment]
The glyph sholdu've returned to you via mailbox. If not, create a ticket in game.
