### ISSUE TITLE
Amani' Alor quest not populating at portal giver

### ISSUE THREAD

**Issue by 7hirteen** [slowtorta/turtlewow-bug-tracker#4517]
I accepted and turned in the quest to Volz'draza. 
She sent me to turn in a quest to Deino. Deino is supposed to give me another quest to turn into herself, then give me another to give to Mystic. Theses 2nd set of quests never show up. 
Mystic Guay'Jin doesnt populate daily quest. 
I closed the game and deleted the contents of WDB folder with no luck.
I am on a Troll warlock is that helps.

**Please, provide a clear description what the bug is:**

**Steps to reproduce the behavior with as much detail as possible:**

1.
2. 
3. 

**IDs of affected creatures, items, quests or spells with a link to the relevant page:**

NPC: https://database.turtle-wow.org/?npc=
Item: https://database.turtle-wow.org/?item=
Quest: https://database.turtle-wow.org/?quest=
Spell: https://database.turtle-wow.org/?spell=
Object: https://database.turtle-wow.org/?object=

**Expected behavior. Describe how it should work:**

**Comment by nrichard680** [comment]
I can confirm I am also seeing the same thing... suppose to be able to accept "Welcome to Amani'Alor" at level 10, but unable to do so. I am also a Troll Warlock

**Comment by 7hirteen** [comment]
We are not the only ones, no one is speaking up about it. And when i sumbit in game they tell me the same old thing EVEN after i told them i closed client and deleted WDB folder, they still tell me to do it. So they arent reading our problems anymore and doing some automated copout msg.

**Comment by shilei175** [comment]
I had the same problem, deleting WDB didn't work.

**Comment by norstromo** [comment]
Same problem, undead priest and or shaman. deleting WDB didn't work.

**Comment by luskanek** [comment]
Will be fixed in the next maintenance update.
