### ISSUE TITLE
cant learn patterns from master engineering trainer in tanaris after gold is paid.

### ISSUE THREAD

**Issue by yinjunqian0326** [slowtorta/turtlewow-bug-tracker#4518]
**Please, provide a clear description what the bug is:**

**Steps to reproduce the behavior with as much detail as possible:**

1. my druid charactor went to tanaris to learn master engineering from the trainer
2. when i got to the trainer, i learnt several patterns sucsessfully.
3. after my skill point reach 260 , i went to the trainer again and try to learn new patterns.
4. but this time i failed learning new patterns, even the gold is paid like more than 10 golds.

**IDs of affected creatures, items, quests or spells with a link to the relevant page:**

NPC: https://database.turtle-wow.org/?npc=buzzec bracketswing
Item: https://database.turtle-wow.org/?item=
Quest: https://database.turtle-wow.org/?quest=
Spell: https://database.turtle-wow.org/?spell=schematic:Thorium Grenade /  schematic:Thorium Widget/ schematic: Truesilver transformer
Object: https://database.turtle-wow.org/?object=

**Expected behavior. Describe how it should work: just let me learn those three patterns correctly and give my money which is spent for nothing back. it is too hard to gain golds here. my charactor ID is fiercekitty.

**Comment by Zulu-Solarity** [comment]
I can confirm this bug, also had trouble with it and wasted gold on it. would be nice if the wasted gold can get refunded, (~5 gold) Characted ID: Solarity

**Comment by twowTurtReynolds** [comment]
Handled in https://github.com/slowtorta/turtlewow-bug-tracker/issues/4579
