### ISSUE TITLE
Can't start quest to lead at Ronae'Thalas

### ISSUE THREAD

**Issue by Zmitrok1984** [slowtorta/turtlewow-bug-tracker#4519]
According to patch notes:

- Ronae'Thalas, a new questing area, is available for adventurers at level 54.
- To unlock Ronae'Thalas, speak to Azj'tordin in the Lariss Pavillon in Feralas after completing his quest: "Pusillin and the Elder Azj'Tordin."

**Actual situation:**
I can't speak with NPC Azj'tordin. He isn't clickable to open dialog window.
I completed quest "Pusillin and the Elder Azj'Tordin." long time ago.
Additionally I have no any quests at Ronae'Thalas area too.

![image](https://github.com/slowtorta/turtlewow-bug-tracker/assets/99164611/d4afe955-9daf-48cf-9b21-4ba5024ab03d)

**Expected behavior. Describe how it should work:**
Azj'tordin should start quest that lead's to Ronae'Thalas.

**Comment by bellmountain** [comment]
wrote a ticket for the same issue. 
Gm response was: "delete wdb folder then write another ticket", told him i already did that. Ticket closed anyway.
Wrote a second ticket and mentioned i had wdb deleted already. Ticket got closed even faster this time and without any gm interacting with me at all, just got a letter IN the mail that basically said "ask your friends! or explore yourself! we don't spoil!"

**Comment by slowtorta** [comment]
The questing in this zone isn't available yet.
