### ISSUE TITLE
Cannot learn certain schematics from engineering trainer

### ISSUE THREAD

**Issue by QSADCA** [slowtorta/turtlewow-bug-tracker#4520]
**Please, provide a clear description what the bug is:**
Cannot learn [Schematic: Thorium Grenade] [Schematic: Thorium Widget] [Schematic: Truesilver Transformer] from Buzzek Bracketswing <Master Engineer> in Gargetzan, Tanaris.
**Steps to reproduce the behavior with as much detail as possible:**

1. Reach Level 260 in Engineering.
2. Find Buzzek Bracketswing <Master Engineer> in Gargetzan, Tanaris, to learn schematics
3. Select any of the following and click on "Train" button, the fees are paid but the schematics are not learned (still shown as available), : 
[Schematic: Thorium Grenade] 
[Schematic: Thorium Widget] 
[Schematic: Truesilver Transformer]
4. Tried disable pfUI and delete WDB folder, the issue persists. 

**IDs of affected creatures, items, quests or spells with a link to the relevant page:**

NPC: https://database.turtle-wow.org/?npc=8736/buzzek-bracketswing
Item: https://database.turtle-wow.org/?item=
Quest: https://database.turtle-wow.org/?quest=
Spell: https://database.turtle-wow.org/?spell=
Object: https://database.turtle-wow.org/?object=

**Expected behavior. Describe how it should work:**

**Comment by Timpietim** [comment]
+1

**Comment by twowTurtReynolds** [comment]
Handled in https://github.com/slowtorta/turtlewow-bug-tracker/issues/4579
