### ISSUE TITLE
Loot is missing after killing Onyxia

### ISSUE THREAD

**Issue by fletchru** [slowtorta/turtlewow-bug-tracker#4522]
**Please, provide a clear description what the bug is:**

**Steps to reproduce the behavior with as much detail as possible:**

1. Kill Onyxia
2. Unable to loot anything, loot is completely missing
3. Instance ID 15483 04.10.2023

**IDs of affected creatures, items, quests or spells with a link to the relevant page:**

NPC: https://database.turtle-wow.org/?npc=
Item: https://database.turtle-wow.org/?item=
Quest: https://database.turtle-wow.org/?quest=
Spell: https://database.turtle-wow.org/?spell=
Object: https://database.turtle-wow.org/?object=

**Expected behavior. Describe how it should work:**

**Comment by twowTurtReynolds** [comment]
![image](https://github.com/slowtorta/turtlewow-bug-tracker/assets/151180101/b7a5f75a-4536-4cd3-b46b-bdcac9789517)
I have killed onyxia and she drops loot. If you can find specific replication steps that show us this issue, please reply.
