### ISSUE TITLE
level 10 hunter quest tame beast bugged

### ISSUE THREAD

**Issue by jaybst** [slowtorta/turtlewow-bug-tracker#4523]
**Please, provide a clear description what the bug is:**

**Steps to reproduce the behavior with as much detail as possible:**

1. Level 10 hunter quest, gnome, tame large crag boar.
2. just says invalid when attempting to tame.
3. cannot continue character, feel like its a game ending bug.
4. probably needs to be addressed 
5. 
6. 

**IDs of affected creatures, items, quests or spells with a link to the relevant page:**

NPC: https://database.turtle-wow.org/?npc=
Item: https://database.turtle-wow.org/?item=
Quest: https://database.turtle-wow.org/?quest=
Spell: https://database.turtle-wow.org/?spell=
Object: https://database.turtle-wow.org/?object=

**Expected behavior. Describe how it should work:** by allowing the boar to be tamed

**Comment by slowtorta** [comment]
Fixed, please clear your WDB cache.
