### ISSUE TITLE
Hawk's Vigil music

### ISSUE THREAD

**Issue by burningfenix1** [slowtorta/turtlewow-bug-tracker#4524]
**Please, provide a clear description what the bug is:**
Hawk's vigil music isn't playing
**Steps to reproduce the behavior with as much detail as possible:**

1. Go to Hawk's Vigil
2. I used to relog when I wanted to listen to the song again, but not it never plays
3. 

**IDs of affected creatures, items, quests or spells with a link to the relevant page:**

NPC: https://database.turtle-wow.org/?npc=
Item: https://database.turtle-wow.org/?item=
Quest: https://database.turtle-wow.org/?quest=
Spell: https://database.turtle-wow.org/?spell=
Object: https://database.turtle-wow.org/?object=

**Expected behavior. Describe how it should work:**
Hawk's Vigil should play it's custom song, but it just has the normal Elwynn Forest music.

**Comment by luskanek** [comment]
A new custom theme will be added to the zone in the future, for now the Elwynn Forest theme will stay.
