### ISSUE TITLE
Paladin Judgment of Wisdom and Vengence no longer being proc'd by +hit items.

### ISSUE THREAD

**Issue by Destroses5100** [slowtorta/turtlewow-bug-tracker#4526]
**Please, provide a clear description what the bug is:** 

Items such as the Crimson Spellblade and Fiery Plate Gauntlets are now no longer procing judged wisdom on a target and also no longer procing Vengeance upon criting. This also includes the nature version of these items, such as the Storm Gauntlets and the new ring from Gilneas City, Ring of Electrical Binding.

**Steps to reproduce the behavior with as much detail as possible:**

1. Equip one (or as many as you can) of the "Fire Strike" and "Lightning Strike" items such as the Crimson Spellblade or Fiery Plate Gauntlets.
2. Judge an enemy mob with Seal of Wisdom.
3. Attack the mob (use Seal of Righteousness for faster testing)
4. Observe no extra mana return and lack of higher Vengeance uptime.

**IDs of affected creatures, items, quests or spells with a link to the relevant page:**

Item: https://database.turtle-wow.org/?item=19968
Item: https://database.turtle-wow.org/?item=81018
Item: https://database.turtle-wow.org/?item=12631
Item: https://database.turtle-wow.org/?item=12632
Item: https://database.turtle-wow.org/?item=17111
Item: https://database.turtle-wow.org/?item=60568
Item: https://database.turtle-wow.org/?item=60582
Item: https://database.turtle-wow.org/?item=60572

Spell: https://database.turtle-wow.org/?spell=

Can't fill out all of the above as the database is currently down.
Missing items I cant use the atlasloot addon for are: Thunder Lizard Cloak from the vendor in Sparkwater Port and the Ring of Electrical Binding.

**Expected behavior. Describe how it should work:**

Each item should add a separate chance at procing Judged Wisdom and their crits should also add a separate proc of Vengeance.

**Comment by ISAACLNELSON** [comment]
I know you guys are dealing with a plethora of bugs since patch day, but I just wanted to stress the impact of this bug on Rets and Prot pallys.This bug happened back in Sept too, here's the link. Hope it helps.  

https://github.com/slowtorta/turtlewow-bug-tracker/issues/4270

And thanks for all you guys do.

**Comment by twowTurtReynolds** [comment]
It looks like this was fixed. I am seeing double procs with JoW up, no SoR, and the spellblade equipped, while I do not see this with another fast sword.
