### ISSUE TITLE
Turtle WoW fresh client - Some mobs are invisible

### ISSUE THREAD

**Issue by whtmst** [slowtorta/turtlewow-bug-tracker#4529]
Hello everyone.
I encountered a problem in 3 out of 4 wings in the Scarlet Monastery dungeon (so far only there, I don't know about further areas): the Library, Armory, and Cathedral. As you can see from the video ([https://youtu.be/Nm1rOkAwTf8](https://youtu.be/Nm1rOkAwTf8)), some mobs in these wings are simply invisible until they move or kill me.
Initially, I thought the issue was related to the HD patch, then I suspected addons, but eventually, I got tired of searching for the problem specifically and completely deleted the entire client and everything related to it.
I downloaded an entirely new client version 1.17.0 from the forum link ([https://forum.turtle-wow.org/viewtopic.php?t=7709](https://forum.turtle-wow.org/viewtopic.php?t=7709)), launched the WoWFoV.exe file, entered the game, set the Full HD resolution (settings are visible at the end of the video), and decided to test the dungeon. As shown in the video, the problem persisted.

```
Fresh client, without any mods or addons. Launched by WoWFoV.exe
Dungeon: Scarlet Monastery (Wings: Library, Armory, and Cathedral)
Dungeon in video: Scarlet Monastery Library
```

---
```
System: Windows 11 22H2 (22621.2283)
Video Card: GeForce GTX 1650 (Driver version - 537.42)
Processor: Intel Core i7-9750H
Internet: 45+ Mbps Download / 90+ Mbps Upload
Ping: Around 60-90 ms in-game
Game on SSD: Path - C:\GAMES ON SSD\Turtle WoW - Mysteries of Azeroth
```

**Comment by cyaohiri** [comment]
I had someone in my group have the same issue; they could only see the enemies once they moved/attacked. This happened months ago, so it's not caused by this patch specifically, and is an older issue.

**Comment by whtmst** [comment]
> I had someone in my group have the same issue; they could only see the enemies once they moved/attacked. This happened months ago, so it's not caused by this patch specifically, and is an older issue.

Possibly. I've only been playing for 10 days, so I've encountered this issue in 3 out of 4 wings of the SM dungeon. I hope they will fix it rather than leaving it as it is because it's quite a significant issue, especially for Hardcore mode players, as this bug could cost a character's life.

**Comment by Bestoriop** [comment]
I had the same problem in scarlet monastery 15 days ago so it isn't the new client

**Comment by twowTurtReynolds** [comment]
![image](https://github.com/slowtorta/turtlewow-bug-tracker/assets/151180101/18816223-c893-4a37-adc5-9673ec2cb931)

I cannot reproduce this.

I will reopen this ticket if provided with replication steps that work.
