### ISSUE TITLE
No nightfins (or sunscales) are being fished out of moonglade.

### ISSUE THREAD

**Issue by Epickalen** [slowtorta/turtlewow-bug-tracker#4530]
**Please, provide a clear description what the bug is:**

Titles suggests. Fished in two separate spots within Moonglade, totaling over 100 casts, correctly getting the average amount of Raw Mithril Head Trout and Oily Blackmouths and Raw Redgills, with no sunscales or nightfins.

**Steps to reproduce the behavior with as much detail as possible:**

1. level 300 fishing with [Big Iron Fishing Pole].
2. Fish in Lake Elune'ara and Nighthaven between 14:00 - 17:00 zone time.
3. catch no Nightfins or Sunscales.

**Expected behavior. Describe how it should work:**

Should be between 10-20% of the fish caught in these zones should be the time reliant fish. Been fishing here for 400+ hours for nightfins pre-update.

**Comment by Muigin** [comment]
Confirmed.  We are looking into this as it relates to a recent change in time-of-day behavior of Sunscale and Nightfin.

**Comment by ratkosrb** [comment]
https://github.com/slowtorta/turtlewow-bug-tracker/assets/35845488/ea5c4443-2418-46ff-ad28-97ba92ec6e57

It's working locally for me. Maybe something is missing in the live server db.

**Comment by Based-Ranxeii** [comment]
From my experience, fishing at 4AM zone time in Moonglade, at around 300 fishing skill with lures, I've gotten 0 Nightfin drops (around 50 casts total, my tracking bugged out so I don't have a precise number), with occasional empty drops, without any "Fish got away" notifications, not even a loot prompt popping up. However, fishing in WPL at 00:30 zone time I managed to catch nightfin at around 10% drop chance (3 out of 28 casts), which is still lower than the expected chance, but it's something. I'll test out some more fishing in WPL this afternoon and share the results.

**Comment by Based-Ranxeii** [comment]
I managed to catch Nightfin snapper at a 10% chance in WPL at 00:30 server time (28 casts), the bug appears to be exclusive to fishing in Kalimdor. I've gotten empty catches, without a loot screen popping up and without a fish ran away notification, in Moonglade at 4AM zone time.

**Comment by Muigin** [comment]
This is now functioning properly on current version.

**Comment by craigdbarber** [comment]
This issue is still occurring on live.
