### ISSUE TITLE
problem with glyphs

### ISSUE THREAD

**Issue by Maug666** [slowtorta/turtlewow-bug-tracker#4531]
**Please, provide a clear description what the bug is:** my druid glyphs for Tellagann were not sent in the mail

**Steps to reproduce the behavior with as much detail as possible:**

1.
2. 
3. 

**IDs of affected creatures, items, quests or spells with a link to the relevant page:** Tellagann

NPC: https://database.turtle-wow.org/?npc=
Item: https://database.turtle-wow.org/?item=
Quest: https://database.turtle-wow.org/?quest=
Spell: https://database.turtle-wow.org/?spell=
Object: https://database.turtle-wow.org/?object=

**Expected behavior. Describe how it should work:** i would like my druid glyphs sent to me by mail because i payed real money for them

**Comment by luskanek** [comment]
Please open an in-game ticket with the details, a GM will assist you.
