### ISSUE TITLE
创建的公会消失了

### ISSUE THREAD

**Issue by gaojie1592** [slowtorta/turtlewow-bug-tracker#4532]
**Please, provide a clear description what the bug is:**

**Steps to reproduce the behavior with as much detail as possible:**

1.在服务器<stormstout>中,名字:<一个星期一次>,创建公会<再续前缘>
2. 收人入会,人数突破848人以后,数字保持在848人不变了.
3. 只有我一个会长,没有副会长.公会其他所有人都是会员级别
4. 昨天大约晚上23点左右,我这里停电了,
5. 第二天早上11点左右上线发现公会解散了,无法找到任何一个公会成员.
6. 才发现邮箱中有GM询问是否使用 强制收人入会的插件,
7. 我以为是GM解散了我的公会,所以通过咨询GM才来到这里提交BUG
8. 请问我的公会能够恢复吗?

**IDs of affected creatures, items, quests or spells with a link to the relevant page:**

NPC: https://database.turtle-wow.org/?npc=
Item: https://database.turtle-wow.org/?item=
Quest: https://database.turtle-wow.org/?quest=
Spell: https://database.turtle-wow.org/?spell=
Object: https://database.turtle-wow.org/?object=

**Expected behavior. Describe how it should work:**

**Comment by gaojie1592** [comment]
服务器 :stormstout

**Comment by Muigin** [comment]
请用英文提交问题。我们无法通过自动翻译准确地翻译中文提交的错误报告，这使得我们难以理解问题的确切性质。谢谢！

Please submit the issues in English. We're unable to accurately translate bug reports submitted in Chinese through automatic translation, which makes it difficult for us to understand the exact nature of the issue. Thank you!
