### ISSUE TITLE
Raw Nightfin Snapper No Longer Catchable 00:00 (12:00 AM) to 06:00 (6:00AM) server time

### ISSUE THREAD

**Issue by lichelordgodfrey** [slowtorta/turtlewow-bug-tracker#4533]
**Please, provide a clear description what the bug is:**

**Steps to reproduce the behavior with as much detail as possible:**

1. Between Midnight and 6AM, I attempt to fish in the Hinterlands. In the lake by the Quel'Danil Lodge, and the lake that outflows into the ocean.
2. After spending almost 3 hours fishing, I have not caught any Raw Nightfin Snapper
3. I presume after this that it is no longer catchable. The Auction House also shows a dearth of Raw Nightfin Snapper and Nightfin Soup (both have shot up in price dramatically). This appears to be the case post-patch 1.17.

**IDs of affected creatures, items, quests or spells with a link to the relevant page:**

Item: https://database.turtle-wow.org/?item=13759

**Expected behavior. Describe how it should work:** I should have caught at least one Raw Nightfin Snapper within that nearly 3 hours of fishing.

**Comment by Muigin** [comment]
#4530
