### ISSUE TITLE
World  underside glitch

### ISSUE THREAD

**Issue by Vailure** [slowtorta/turtlewow-bug-tracker#4534]
**Please, provide a clear description what the bug is:**

**Steps to reproduce the behavior with as much detail as possible:**

1. Running around in world, seems more common in caves
2. Toon occasionally disappears reappears, less common in 1.17
3. This happens with both in wow.exe and wowfov.exe

![Screenshot from 2023-10-04 20-14-50](https://github.com/slowtorta/turtlewow-bug-tracker/assets/47408510/068c6fce-539d-491e-91f8-fc4a6998dae8)
![Screenshot from 2023-10-04 20-00-18](https://github.com/slowtorta/turtlewow-bug-tracker/assets/47408510/462fe341-2d2b-439b-8159-1069966aa921)

**Expected behavior. Describe how it should work:**

Not seeing the underside of the world :)

**Comment by twowTurtReynolds** [comment]
After convening with staff, they've seen this before only as an issue with the unofficial HD patch.
