### ISSUE TITLE
No Nightfins, Plated Armorfish are being fished from Winterspring

### ISSUE THREAD

**Issue by Epickalen** [slowtorta/turtlewow-bug-tracker#4535]
**Please, provide a clear description what the bug is:**

No Raw Nightfin Snapper, or Plated armorfish seem to be in the loot table for Winterspring. In 50 casts, i got 48 Raw Whitescale Salmon, 2 Raw Redgill. Nightfins and plated armorfish both have 20% droprate normally, to not get a single one out of chance, along with no nightfins from a 100 from moonglade, would be exceptional.

**Steps to reproduce the behavior with as much detail as possible:**

1. 300fishing + Big Iron Fishing Pole + Bright Bauble + Fishing Boat in Frostfire Hot Springs.
2. Fish between zone time of 1500-1530
3. Not catch the aforementioned fish.

**IDs of affected creatures, items, quests or spells with a link to the relevant page:**

**Expected behavior. Describe how it should work:**

Reported 20% catch rate of Raw Nightfin Snapper and 20% catch rate of Plated Armorfish. Should catch at least one of either within 50 casts.

**Comment by Muigin** [comment]
#4530
