### ISSUE TITLE
After the 1.17 revision, there is no druid's travel (stag) form

### ISSUE THREAD

**Issue by lengyun925** [slowtorta/turtlewow-bug-tracker#4536]
I completed the druid's travel form (stag form), but after version 1.17, it was restored to (leopard form).
In the game, I received a letter from the system, which was a variant glyph of (stag Form) that disappeared after use, but did not change to stag form.
Please help solve the problem！

**Comment by slowtorta** [comment]
Delete your WDB folder while you clien is completely closed.
Right click on your glyhp items to learn them, new spells will appear in your spellbook.
Ensure that your client isn't using any modifications.
