### ISSUE TITLE
No Nightfins: Felwood.

### ISSUE THREAD

**Issue by Epickalen** [slowtorta/turtlewow-bug-tracker#4538]
**Please, provide a clear description what the bug is:**

Nightfins missing from loottable in Felwood. 50 fish. 46 redgills. 4 Mithril trout.

**Steps to reproduce the behavior with as much detail as possible:**

1. 300 fishing + Big Iron Fishing Pole, fishing in the pool in Talonbranch Glade.
2. 15:30-16:00 zone time.
3. the nightfins. theyre gone. Pretty sure i fished them to extinction.

**Expected behavior. Describe how it should work:**
expected 20% catchrate for nightfins. 0 fished in 50. Also expected some oily blackmouths as they have the same rate as mithril trout, but that could be variance.

**Comment by Muigin** [comment]
#4530
