### ISSUE TITLE
'Golemagg's Trust' spell target flag flipped

### ISSUE THREAD

**Issue by perl1743** [slowtorta/turtlewow-bug-tracker#454]
**Please, provide a clear description what the bug is:**
Boss is casting this buff on the raid.
![image](https://user-images.githubusercontent.com/2818608/141840220-2626fafb-5087-423b-b505-7e647d0dacb4.png)

**Steps to reproduce the behavior with as much detail as possible:**

1. Fight Golemagg the Incinerator, stand within 30 yards, check buffs.

**IDs of affected creatures, items, quests or spells with a link to the relevant page:**

NPC: https://database.turtle-wow.org/?npc=11988
Spell: https://database.turtle-wow.org/?spell=20553

**Expected behavior. Describe how it should work:**
Buff should only affect the boss's core hounds.

**Comment by perl1743** [comment]
This issue seems to effect AoE based buffs/heals in general, mobs cast them on their enemies instead of their allies.
BWL: Blackwing Taskmaster - Healing Circle
MC: Majordomo Executus - Magic Reflection
MC: Golemagg the Incinerator - Golemagg's Trust

**Comment by jameyboor** [comment]
Fixed on next update.
