### ISSUE TITLE
No "Shoot" ability

### ISSUE THREAD

**Issue by aksnowshadow** [slowtorta/turtlewow-bug-tracker#4540]
I no longer have the ability "Auto Shot" on my Dwarf Hunter.

**Steps to reproduce the behavior with as much detail as possible:**

1. Login
2. Look at spell book and notice a distinct lack of "shoot" under the general tab.
3. Look for "Auto Shot" under the other tabs.
4. Cannot find "Auto Shot".
5. Cry.

**IDs of affected creatures, items, quests or spells with a link to the relevant page:**
Database is disabled so I can't.
NPC: https://database.turtle-wow.org/?npc=
Item: https://database.turtle-wow.org/?item=
Quest: https://database.turtle-wow.org/?quest=
Spell: https://database.turtle-wow.org/?spell=
Object: https://database.turtle-wow.org/?object=

**Expected behavior. Describe how it should work:**
I should have a "Auto Shot" ability so I can shoot without using a skill like "Arcane Shot".
![Screenshot 2023-10-05 005113](https://github.com/slowtorta/turtlewow-bug-tracker/assets/147022757/b552ef9c-7753-43e5-8d68-61e4ab13f925)
![Screenshot 2023-10-05 005116](https://github.com/slowtorta/turtlewow-bug-tracker/assets/147022757/ffb1ba3c-eb9b-4ce5-b8da-4fec4adc68d1)

**Comment by cyaohiri** [comment]
It should be in the Marksmanship tab.

**Comment by Muigin** [comment]
Autoshot is in your Marksmanship tab.

Working as intended.
