### ISSUE TITLE
Crashing when I go to the graveyard

### ISSUE THREAD

**Issue by nickjc333** [slowtorta/turtlewow-bug-tracker#4542]
**Please provide a clear description of what the bug is:**
Turtle, wow crashing when I die and go to a graveyard 70% of the time
**Steps to reproduce the behaviour with as much detail as possible:**

1. Die
2. Release 
3. Crashes during loading 

**IDs of affected creatures, items, quests or spells with a link to the relevant page:**
Me
NPC: https://database.turtle-wow.org/?npc=
Item: https://database.turtle-wow.org/?item=
Quest: https://database.turtle-wow.org/?quest=
Spell: https://database.turtle-wow.org/?spell=
Object: https://database.turtle-wow.org/?object=

**Expected behaviour. Describe how it should work:**
Teleport to the graveyard without crashing.

**Comment by slowtorta** [comment]
Please submit a ticket in game.

**Comment by nickjc333** [comment]
I did they said report it to this
