### ISSUE TITLE
Marshal' Blocker Item From Gilneas City Dungeon

### ISSUE THREAD

**Issue by strpol** [slowtorta/turtlewow-bug-tracker#4543]
The shield "Marshal's Blocker" from the new Gilneas City dungeon is missing the block value. Its stats also suck. I made a Github account so I can tell you how much this shield sucks. Also, the bosses are way too easy. I did this dungeon on hardcore.

![marshal's blocker](https://github.com/slowtorta/turtlewow-bug-tracker/assets/147033858/481adfd3-1828-423b-a955-e5e4942343e0)

**Comment by Muigin** [comment]
This has been fixed.
