### ISSUE TITLE
Gnome hunter Taming the Beast quest

### ISSUE THREAD

**Issue by Sanholo13** [slowtorta/turtlewow-bug-tracker#4545]
**Please, provide a clear description what the bug is:**

**Steps to reproduce the behavior with as much detail as possible:**

1.Take the Taming the Beast quest
2. Trying to do the first step that is taming Large Crag Boar
3. Targeting the said boar then cast the spell using the rod that provided by quest giver
4. It failed, it said 'invalid target'

**IDs of affected creatures, items, quests or spells with a link to the relevant page:**

NPC: https://database.turtle-wow.org/?npc=
Item: https://database.turtle-wow.org/?item=
Quest: https://database.turtle-wow.org/?quest=
Spell: https://database.turtle-wow.org/?spell=
Object: https://database.turtle-wow.org/?object=

**Expected behavior. Describe how it should work:**

**Comment by slowtorta** [comment]
Clear your WDB folder, this issue has been resolved.
