### ISSUE TITLE
Waterfall/Back entrance to Stormwind Vault is not working.

### ISSUE THREAD

**Issue by Theonedp1** [slowtorta/turtlewow-bug-tracker#4546]
**Please, provide a clear description what the bug is:**
Waterfall/Back entrance to Stormwind Vault is not working.

**Steps to reproduce the behavior with as much detail as possible:**

1. Walk into the instance portal and you do not get zoned into the instance.

**Expected behavior. Describe how it should work:**
You should get zoned into the dungeon.

**Comment by Muigin** [comment]
This will be fixed in an upcoming maintenance.
