### ISSUE TITLE
could you help me?

### ISSUE THREAD

**Issue by vivii1986** [slowtorta/turtlewow-bug-tracker#4547]
**Please, provide a clear description what the bug is:**

**Steps to reproduce the behavior with as much detail as possible:**

1.i didnt open pvp.
2. After the totems of the opposing shaman attacked me, I entered a PVP state.
3.i am dead,i am a hc player
4.Can you restore my character（luohong）？

**IDs of affected creatures, items, quests or spells with a link to the relevant page:**

NPC: https://database.turtle-wow.org/?npc=
Item: https://database.turtle-wow.org/?item=
Quest: https://database.turtle-wow.org/?quest=
Spell: https://database.turtle-wow.org/?spell=
Object: https://database.turtle-wow.org/?object=luohong

**Expected behavior. Describe how it should work:**

**Comment by slowtorta** [comment]
I'm sorry, but Harcore characters cannot be returned to life for any reason.
