### ISSUE TITLE
cleaning cloth not craftable.

### ISSUE THREAD

**Issue by guruvex** [slowtorta/turtlewow-bug-tracker#4548]
**Please, provide a clear description what the bug is:**
learned the cleaning cloth outline and it dont appear in the crafting window
 
**Steps to reproduce the behavior with as much detail as possible:**

1.buy it, learn it.
2. pattern says already known
3. dont appear in the crafting window or the spell book at all.

Spell: https://database.turtle-wow.org/?spell= dont have access to database to tell you.

**Expected behavior. Describe how it should work:**
should put the craft-able cleaning cloth in the crafting window

**Comment by slowtorta** [comment]
Will be fixed in patch 1.17.1.
