### ISSUE TITLE
Human paladin not showing blocking animation

### ISSUE THREAD

**Issue by Galuur** [slowtorta/turtlewow-bug-tracker#455]
I have noticed that my human paladin (ingame name Loopy) does not show the blocking animation when blocking attacks. He is simply continuing with his normal attacking animations and never raises the shield. Other defensive animations such as dodge or parry are properly animated, but shield blocking isn't.

Refer to the video showing the issue: https://www.youtube.com/watch?v=3vBUh3Nh0fc 

You can see in the combat log that the boar's attacks are being blocked, confirmed via consumption of Redoubt charges, however my paladin never raises the shield or visually blocks the attack. 

I am able to replicate this without any addons as well as with them.

**Comment by slowtorta** [comment]
Moving this issue to the internal tracker for client-related problems, thank you.
