### ISSUE TITLE
Blacktooth Grin guild base in Stonard is missing guards and npcs after 1.17x update

### ISSUE THREAD

**Issue by Slimthegrim** [slowtorta/turtlewow-bug-tracker#4550]
**Please, provide a clear description what the bug is:**
Blacktooth Grin guild base lost its NPCs like the last major content update in Swamp of Sorrows. Guards, vendors, etc are removed, though the base still stands. Have confirmed other guild bases have not suffered this issue. Blackwing Guard for instance has their NPCs.

**Steps to reproduce the behavior with as much detail as possible:**

1. Go to Stonard, travel over to Blacktooth camp.
2. Peer around and see NPCs, guards, vendors missing from camp.

**NPCs missing from center tent:**
![image](https://github.com/slowtorta/turtlewow-bug-tracker/assets/110629519/0eb2e58b-65d8-4732-8758-f43f3bb4d6f8)

Blacktooth tabard guards missing from the line to the outhouses:
![image](https://github.com/slowtorta/turtlewow-bug-tracker/assets/110629519/675b41cf-ee5f-412a-ba50-7c6585f6b2e4)

Harold our green haired gnome vendor is missing from his tent:
![image](https://github.com/slowtorta/turtlewow-bug-tracker/assets/110629519/7ba4bb72-61bb-47f4-b5f0-91493e1286a0)

The guards appear to have been kidnapped which had our tabards outside of each doorway:
![image](https://github.com/slowtorta/turtlewow-bug-tracker/assets/110629519/df8fe801-375a-4787-867e-e43ee86f4ae3)

(just some samples, there's obviously more npcs missing)

**IDs of affected creatures, items, quests or spells with a link to the relevant page:**
The database is not available at the moment. A GM recovered our npcs in guild base last time though. I'll avoid naming them here, can share who via other means.

**Expected behavior. Describe how it should work:**
Here's screenshots where we had npcs before 1.17 update:
![image](https://github.com/slowtorta/turtlewow-bug-tracker/assets/110629519/2b47d415-f78c-4a3f-8474-fc0a0ea500d5)

![image](https://github.com/slowtorta/turtlewow-bug-tracker/assets/110629519/2ff10809-7e28-4f2b-9eeb-345cec962fa6)

![image](https://github.com/slowtorta/turtlewow-bug-tracker/assets/110629519/b5193985-c457-41a9-a71c-87927ca2f12e)

**Theory for resolution:**
Well I think what's going on here is that NPCs were spawned into the world, not into the dev build pipeline world upstream. This is the second major content update which nukes just our npcs/vendors and the like but not the entire base. 
Because it's not impacting other guild bases, I believe our npcs were spawned in by GM and need to be added upstream into dev side like Blackwing Guard's are. 

A GM fixed this last time via a ticket and I believe the time before.

**Comment by slowtorta** [comment]
This is a RPGM issue, please contact Gheor on Discord.
