### ISSUE TITLE
New Bloody Belt Buckle is not applyable in trade windows to others.

### ISSUE THREAD

**Issue by misandria69** [slowtorta/turtlewow-bug-tracker#4551]
**Please, provide a clear description what the bug is:**
All other belt buckles work like Mithril Spurs, being apply able in a trade window, Bloody Belt Buckle can only be put on the BS that made it.
**Steps to reproduce the behavior with as much detail as possible:**

1. Make all belt buckles and try to apply them on others and realize Bloody is the odd one out.
2. Bloody Belt buckle is a ~150 arena win reward so not many have it.
3. Forces paladins and druids to go Blacksmithing to get a bis tanking enchant when they likely dont want to.

**IDs of affected creatures, items, quests or spells with a link to the relevant page:**

NPC: https://database.turtle-wow.org/?npc=
Item: https://database.turtle-wow.org/?item=
Quest: https://database.turtle-wow.org/?quest=
Spell: https://database.turtle-wow.org/?spell=
Object: https://database.turtle-wow.org/?object=

**Expected behavior. Describe how it should work:**
It should be applicable to anyone who trades you the mats to make it for them.

**Comment by Northyn** [comment]
Just tried this today with a guild member, it cannot be applied in the trade window, and you receive an error message that "You can only use this on an object you own." in response. 

Really hope this isn't intended : /

**Comment by Muigin** [comment]
#4757

**Comment by Muigin** [comment]
This is known and will be fixed in a future maintenance.  This requires a spell tweak.  ETA unknown.

**Comment by GitsGift** [comment]
isnt it just copy paste from any other belt buckle? 1 month passed  :/

**Comment by cyaohiri** [comment]
> isnt it just copy paste from any other belt buckle? 1 month passed :/

Even if it is, those changes need to be made on the client side, which means we will only get the update once the client updates, so in 1.17.1.

**Comment by twowTurtReynolds** [comment]
![image](https://github.com/slowtorta/turtlewow-bug-tracker/assets/151180101/17397988-a9c2-47cc-bf66-3b418e41acab)
![image](https://github.com/slowtorta/turtlewow-bug-tracker/assets/151180101/ca3458d9-0a67-44c8-83b3-b16bb0eda7db)

Will be fixed with the release of 1.17.1, hang tight folks!
