### ISSUE TITLE
Cant learn the last ENGI skills in Gadgetzan . Lost much gold by trying it .

### ISSUE THREAD

**Issue by hansiwursti13345** [slowtorta/turtlewow-bug-tracker#4552]
hey team,

 i cant learn the last skills from the engi trainer in gadz.

 there are green for me but if i want to learn:

THORIUM GRENADE
THORIUM WIDGET
TRUESILVER TRANSFORMER

the NPC just got my gold but dont give me the skills... tried it many times now but only lost gold .. thats not good :(

NPC name is : BUZZEK BRACKETSWING

pls help
/

**Comment by twowTurtReynolds** [comment]
Handled in https://github.com/slowtorta/turtlewow-bug-tracker/issues/4579
