### ISSUE TITLE
Tinyhoof's Shrinking Balm

### ISSUE THREAD

**Issue by welpenhund** [slowtorta/turtlewow-bug-tracker#4555]
**Please, provide a clear description what the bug is:**
Not sold anymore by Lansa Skyseer

**Steps to reproduce the behavior with as much detail as possible:**

1. Go to the vendor
2.  Try to buy [Tinyhoof's Shrinking Balm]

**IDs of affected creatures, items, quests or spells with a link to the relevant page:**

DATABASE IS DOWN

**Expected behavior. Describe how it should work:**
It should be sold by the vendor named: Lansa Skyseer

**Comment by luskanek** [comment]
I checked and the NPC still sells the item. Try deleting your WDB folder.

**Comment by welpenhund** [comment]
Confirmed - it is sold again (but it had nothing to do with my cache, on the newest patch it was gone)
Before starting wow i use a batch file that automatically always clears my WDB folder content
