### ISSUE TITLE
Rich thorium vein 'failed attempt'

### ISSUE THREAD

**Issue by Timpietim** [slowtorta/turtlewow-bug-tracker#4556]
**Please, provide a clear description what the bug is:**

My character who has just reached the cap for mining rich thorium went into Dire Maul east to mine the veins after the last boss. Out of the two veins that spawned one was bugged and didn't allow my character to start the mining animation, giving the 'failed attempt' prompt before the mining animation started.

Failed attempt is a message you receive when the mining action fails when you're mining with relatively low skill, but in this case the message was given before the animation started

**Steps to reproduce the behavior with as much detail as possible:**

1. Clear to the Dire Maul East rich thorium veins
2. Have only limited skill just enough to mine the vein
3. Mine it

**IDs of affected creatures, items, quests or spells with a link to the relevant page:**

https://www.wowhead.com/classic/object=175404/rich-thorium-vein

**Expected behavior. Describe how it should work:**

Rich thorium veins have a 275 skill requirement, once you have that skill you should be able to mine the vein
In this instance it fails before the mining animation starts

**Comment by Muigin** [comment]
Cannot reproduce. Please clear your WDB and ensure you are not using any addons that would affect spell behaviors.
