### ISSUE TITLE
Typos and Grammatical Errors in T3 Quest Text Descriptions

### ISSUE THREAD

**Issue by EyeOfTheBeast** [slowtorta/turtlewow-bug-tracker#4559]
**Please, provide a clear description what the bug is:**
The T3 quest text descriptions are poorly worded, have typos and grammatical errors in them.

**Steps to reproduce the behavior with as much detail as possible:**
1. Do the Frostfire T3 quests at Light's Hope Chapel by talking to Archmage Angela Dosantos. This may happen with the other classes T3 quest descriptions as well. I recall Korfax having some bad grammar dialog too.

**IDs of affected creatures, items, quests or spells with a link to the relevant page:**
Archmage Angela Dosantos NPC: https://www.wowhead.com/classic/npc=16116/archmage-angela-dosantos

**Expected behavior. Describe how it should work:**
The proper quest text for the T3 mage quests and other T3 class quests can be found on Wowhead Classic: https://www.wowhead.com/classic/quest=9100/frostfire-gloves

**Comment by luskanek** [comment]
Please use the 'text-edits' channel on the community discord to report typos or other issues regarding text. I will take a look at the quests you reported.
