### ISSUE TITLE
Incorrect Nightbane Worgen spawn in the Wetlands.

### ISSUE THREAD

**Issue by sailorVEVO** [slowtorta/turtlewow-bug-tracker#4560]
**Nightbane Worgen (Duskwood Mob) found in the Wetlands, in the Raptor Ridge subzone.**

**Steps to reproduce the behavior with as much detail as possible:**

1. Go to Raptor Ridge in the Wetlands.
2. Go to the location on the map as seen in the second attached file.
3. Wonder to yourself if you are playing on a Cataclysm server, since Worgen don't belong in the Wetlands.

**IDs of affected creatures, items, quests or spells with a link to the relevant page:**

NPC: https://database.turtle-wow.org/?npc=898
(With the DB being down, I can't be certain that this is the correct ID.)

**Expected behavior. Describe how it should work: Nightbane Worgen are a Duskwood mob, and shouldn't be in the Wetlands.**

Picture evidence of the Worgen spawn: 
![image_2023-10-05_223524835](https://github.com/slowtorta/turtlewow-bug-tracker/assets/147120030/fd7c10aa-ceb7-4294-9ca7-d8aaed5ded80)

Location on the map: 
![image_2023-10-05_223452111](https://github.com/slowtorta/turtlewow-bug-tracker/assets/147120030/fec68ac7-f7b3-46d7-967f-e342260047c8)

**Comment by twowTurtReynolds** [comment]
Bye bye.
![image](https://github.com/slowtorta/turtlewow-bug-tracker/assets/151180101/98c09222-a2d2-4a97-970f-984173e51b1c)

This should hit live next restart :)
