### ISSUE TITLE
Horde new teleport Stonard issue

### ISSUE THREAD

**Issue by popocrazy** [slowtorta/turtlewow-bug-tracker#4561]
Greetings! I have done the quest about "teleport: Stonard" several days ago, but till now I can't find the teleport in Spellbook. I use the 1.17.0(7075) version. Please check this issue. thanks.

![image](https://github.com/slowtorta/turtlewow-bug-tracker/assets/147123535/fa2fe77e-27c0-4576-98b7-1bfe4aa02df5)
![image](https://github.com/slowtorta/turtlewow-bug-tracker/assets/147123535/03ab31dc-3638-403f-b67b-9f45cef630bf)

**Comment by slowtorta** [comment]
Please contact GMs in game about it.
