### ISSUE TITLE
A Tusken Affair quest

### ISSUE THREAD

**Issue by baarabashka** [slowtorta/turtlewow-bug-tracker#4563]
Hello. There is no continuation of the A Tusken Affair quest. Cuts off at the magician trainer. Teleports to a new location, but does not give the quest. It is not available. The chain of tasks is completed. There were no problems before. No way to make a reputation

**Comment by 7hirteen** [comment]
Are you a Troll Warlock?

**Comment by baarabashka** [comment]
No. Turtle quest. He is not classist. It's for everyone.


пт, 6 окт. 2023 г. в 08:30, 7hirteen ***@***.***>:

**Comment by 7hirteen** [comment]
Yes i know that, Me and a few others are having this issue only on Troll Locks

**Comment by baarabashka** [comment]
Priest Troll. Can you help me continue completing the quest?

**Comment by 7hirteen** [comment]
It may be glitched for everyone

**Comment by baarabashka** [comment]
need to wait?

**Comment by 7hirteen** [comment]
Ok confirmed the daily quest still works on other chars. It seems the quest giver at mage portal no longer gives the quest that guides you to the daily quest giver. This is the glitch. There are reports of the initial quest giver in Grom hold goes hostile at times and kills u. So maybe there are sever things wrong.

**Comment by baarabashka** [comment]
Yes. It is so indeed. My other characters had no problems with this quest. The problems started after the update. Hope they fix it soon. Thank you.
