### ISSUE TITLE
Ritual of Souls in spellbook misplaced in General tab

### ISSUE THREAD

**Issue by NoelHG** [slowtorta/turtlewow-bug-tracker#4565]
**Please, provide a clear description what the bug is:**

Two bugs that might be related:

Ritual of Souls doesn't benefit from the demonology talent "Master Conjuror"

Ritual of Souls appears in the "generic" section of the spellbook, instead of Demonology.

**Steps to reproduce the behavior with as much detail as possible:**

1. Spec into Master Conjuror and check the healthstones from Ritual of Souls (requires multiple players)

**Expected behavior. Describe how it should work:**

Ritual of Souls should at least appear in the demonology spellbook, and ideally also benefit from MC.

**Comment by twowTurtReynolds** [comment]
The talent issue is here: https://github.com/slowtorta/turtlewow-bug-tracker/issues/2381

I've replicated that the misclassification of Ritual of Souls persists. I think we should move it.

**Comment by luskanek** [comment]
Fixed. The fix will be applied with the next client patch.
