### ISSUE TITLE
Restore character's items

### ISSUE THREAD

**Issue by tedeev98** [slowtorta/turtlewow-bug-tracker#4567]
SCUM, i dk how

someone hacked my account and my friends' accounts were also hacked. 

I know that you either had a leak of user data or something else

someone took off all my character's items and deleted, spent all gold, and then deleted my character. The character has been restored, is it possible to restore my items and gold too? Please

Character's Name "Faralon"

**Comment by luskanek** [comment]
Open an in-game ticket and don't forget to use strong passwords and change them once in a while.
