### ISSUE TITLE
Feralas drowning on land.

### ISSUE THREAD

**Issue by pierremarteaudc** [slowtorta/turtlewow-bug-tracker#4568]
A little space near the orc shaman racial quest area treats the player as being underwater while being on land. See the screenshot for the exact location.

![WoWScrnShot_100523_175659](https://github.com/slowtorta/turtlewow-bug-tracker/assets/147144351/774e8470-d8ac-4cb3-b025-41e54efae089)

**Comment by Muigin** [comment]
#4800

**Comment by twowTurtReynolds** [comment]
![https://user-images.githubusercontent.com/85698173/284000601-bc535859-e802-4c98-8f55-4b3541440d73.png](https://user-images.githubusercontent.com/85698173/284000601-bc535859-e802-4c98-8f55-4b3541440d73.png)
![](https://user-images.githubusercontent.com/85698173/284000605-e48c95ce-c038-4e89-bbbb-4ffa95d7f583.png)
![](https://user-images.githubusercontent.com/85698173/284000870-d2368f40-ccc0-4464-8896-95fc17a2438f.png)

**Comment by khoopek** [comment]
I found 2 spots near there that has drowning:
78.7, 47.0
76.9, 48.5

hope this coordinates helped.

**Comment by twowTurtReynolds** [comment]
@khoopek Can you take screenshots please? As far as I understand, map coordinates are the invention of addons and we don't want to rely on that.

**Comment by cyaohiri** [comment]
> @khoopek Can you take screenshots please? As far as I understand, map coordinates are the invention of addons and we don't want to rely on that.

You can use `.t feralas` and then `.go zonexy 78.7 47.0`.

**Comment by twowTurtReynolds** [comment]
I'm not able to replicate any of these on the PTR. Disabled patch 1.17.1, GM off, God off.

**Comment by twowTurtReynolds** [comment]
Closing, tracking this under https://github.com/slowtorta/turtlewow-bug-tracker/issues/5811 now.
