### ISSUE TITLE
Multiple companion items summon Poley the bear instead of their pets

### ISSUE THREAD

**Issue by Tinyfin-github** [slowtorta/turtlewow-bug-tracker#457]
Multiple pet items summon Poley the bear instead of their pets

https://database.turtle-wow.org/?spell=28505 - Summon Poley spell

Some examples: 
https://database.turtle-wow.org/?item=50202 Egg of Turtlhu
https://database.turtle-wow.org/?item=83272  Mr. Tails

**Comment by slowtorta** [comment]
It is fixed partially now. Please clear WDB and try to summon some pets. Some of the pets will remain broken till 1.15.2 release because right now we removed old hacky solution for custom pets and items actually require proper spells to work.
