### ISSUE TITLE
Aquitus Rare Mob Respawn Interval

### ISSUE THREAD

**Issue by mrkajito** [slowtorta/turtlewow-bug-tracker#4570]
**Please, provide a clear description what the bug is:**

the new rare mob Aquitus in Lapidis Isle has a respawn rate of 5minutes, this is possibly not intended and invites to farming said enemy.

**Steps to reproduce the behavior with as much detail as possible:**

1. Kill the rare spawn
2. wait 5min => respawn
3. rinse and repeat

**IDs of affected creatures, items, quests or spells with a link to the relevant page:**

no access to wow turtle db atm

**Expected behavior. Describe how it should work:**
sensible respawn rate according to other rare mobs

**Comment by twowTurtReynolds** [comment]
https://github.com/slowtorta/turtlewow-bug-tracker/issues/4570
https://github.com/slowtorta/turtlewow-bug-tracker/issues/4571
https://github.com/slowtorta/turtlewow-bug-tracker/issues/4572
https://github.com/slowtorta/turtlewow-bug-tracker/issues/4573

All four of these remain dead for 15 minutes after I have killed them. Likely someone also noticed and fixed.
