### ISSUE TITLE
Mob count for killed mobs in quest changed from 10 to 1

### ISSUE THREAD

**Issue by HenElten** [slowtorta/turtlewow-bug-tracker#4574]
I was doing one of the new quests in Feralas; "Woodpaw Disarray", and had finished killing the mobs it required. I then moved on to do another quest, and suddenly noticed, that the counter for amount of "Woodpaw Mongrels" I had to kill for the quest had changed from 10/10 to 1/10

I have no idea if I can recreate the bug - I honestly don't intent to try...

I can't give you a link to the quest in the database, for obvious reasons

I think it seems somewhat obvious how it was supposed to work :-)

**Comment by cyaohiri** [comment]
This is usually fixed by deleting all files inside your WDB folder while the game is not running.

**Comment by twowTurtReynolds** [comment]
Can't replicate.
![image](https://github.com/slowtorta/turtlewow-bug-tracker/assets/151180101/396d638d-7d1f-4340-893a-4ff4672b0641)
