### ISSUE TITLE
2 LDF icons

### ISSUE THREAD

**Issue by gnorfix** [slowtorta/turtlewow-bug-tracker#4575]
**Please, provide a clear description what the bug is:**

**Steps to reproduce the behavior with as much detail as possible:**

1.  When I updated the game it launched with 2 LFD icons for me and my friends when we qued for dungeon it went for 1 healer 4 dps  ( 1shaman 2 warl 1 mage 1 hunter) for some reason, in chat it doubles all messages.

**Comment by luskanek** [comment]
Delete the LFT folder from your Interface/AddOns folder. LFT is not a part of the client, you do not need to have it as a standalone addon anymore.
