### ISSUE TITLE
An error in the set of items

### ISSUE THREAD

**Issue by Naartt** [slowtorta/turtlewow-bug-tracker#4576]
![ГМ](https://github.com/slowtorta/turtlewow-bug-tracker/assets/147137597/8a5670df-22a8-43ec-869a-007e6fa1445c)
Good afternoon, a set of Mail Shoulder quality items has + to intellect twice (+9 and +15) but do not have strength.
Hands do not fall into the dungeon for shaman and paladin (I went to the dungeon for six months and they never fell)
The database doesn't work until October 24, so I can't attach links (set from dungeon AQ40)
Check the bonus from the +12 defense item set, maybe it is also wrong because the classes that carry MAIL are not tanks.
(Добрый день, набор предметов качества Mail Shoulder имеет + к intellect два раза (+9 и +15) но не имеют силы.
Hands не падают в подземелье для шамана и паладина (я в течение шести месяцев ходил в подземелье и они ни разу не упали)
База данных не работает до 24 октября поэтому я не могу приложить ссылки (набор из подземелья AQ40)
Проверьте бонус с набора предметов +12 defence возможно он тоже ошибочен потому что классы которые носят MAIL не являются танками.)

**Comment by twowTurtReynolds** [comment]
Mantle is now fixed: https://github.com/slowtorta/turtlewow-bug-tracker/issues/3695

![image](https://github.com/slowtorta/turtlewow-bug-tracker/assets/151180101/3f6eda47-89a2-4bd8-9855-6ee7e012a1a5)
The gloves do drop.

**Comment by Naartt** [comment]
> Mantle is now fixed: #3695
> 
> ![image](https://private-user-images.githubusercontent.com/151180101/288510397-3f6eda47-89a2-4bd8-9855-6ee7e012a1a5.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTEiLCJleHAiOjE3MDM0MjUzMzUsIm5iZiI6MTcwMzQyNTAzNSwicGF0aCI6Ii8xNTExODAxMDEvMjg4NTEwMzk3LTNmNmVkYTQ3LTg5YTItNGJkOC05ODU1LTZlZTdlMDEyYTFhNS5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBSVdOSllBWDRDU1ZFSDUzQSUyRjIwMjMxMjI0JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDIzMTIyNFQxMzM3MTVaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT1lYTdkODA1NTQwZDExYmJmNWJiODhjYjRmMjhmOTZhZjc1YmU1ZWEzNmVkZjdhZWZkMzcwNDYwYzRmZjU4YmM0JlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.gj2nESFWgTvlwH9ZBWw5jynuVWbGoXlCtGNE_xZjbyU) The gloves do drop.

![19](https://github.com/slowtorta/turtlewow-bug-tracker/assets/147137597/89b10c9e-f86a-43a5-a155-c3cdc85028eb)
