### ISSUE TITLE
Not able to learn schematics from Buzzek

### ISSUE THREAD

**Issue by IsaachuntUK** [slowtorta/turtlewow-bug-tracker#4577]
**Please, provide a clear description what the bug is:**

So I have 260 engi and down in Gadgetzan. I can see Buzzek has the 3 Schematics for sale. I buy them, it takes my money but the plans don't appear in my backpack and I don't seem to have them in my engineering list of learnt plans

I have tried relogging and deleting WDB folder

**Steps to reproduce the behavior with as much detail as possible:**

1.
2. 
3. 

**IDs of affected creatures, items, quests or spells with a link to the relevant page:**

NPC: https://database.turtle-wow.org/?npc=
Item: https://database.turtle-wow.org/?item=
Quest: https://database.turtle-wow.org/?quest=
Spell: https://database.turtle-wow.org/?spell=
Object: https://database.turtle-wow.org/?object=

**Expected behavior. Describe how it should work:**

**Comment by IsaachuntUK** [comment]
The schematics in question are:

Thorium Grenade
Thorium Widget
Truesilver Transformer

**Comment by twowTurtReynolds** [comment]
Do you mean Bimock? Sovik? Buzzek does not teach you this.
https://database.turtle-wow.org/?item=16042
https://database.turtle-wow.org/?item=16041

![image](https://github.com/slowtorta/turtlewow-bug-tracker/assets/151180101/22d111af-5ef8-4766-92f3-046e0e495c5e)
It seems to be working fine.

**Comment by twowTurtReynolds** [comment]
Oh. Handled already in https://github.com/slowtorta/turtlewow-bug-tracker/issues/4579
