### ISSUE TITLE
Soul Ashes of the Banished does not drop

### ISSUE THREAD

**Issue by Tinyfin-github** [slowtorta/turtlewow-bug-tracker#458]
Soul Ashes of the Banished does not drop 

Soul Ashes of the Banished  has a 100 drop rate

 https://database.turtle-wow.org/?item=22229#dropped-by Soul Ashes of the Banished  

![image](https://user-images.githubusercontent.com/83077166/142445384-29c8f87c-aaef-4589-9177-2d01b965b2a8.png)

![WoW_WxYkr5kOXO](https://user-images.githubusercontent.com/83077166/142446076-c0a1812c-0cfd-4c4f-9ab0-abc4e6760546.jpg)

![WoW_Z9Iq1UNAp3](https://user-images.githubusercontent.com/83077166/142446080-4eb2f52e-85af-40f7-bf50-c5c5b843e989.jpg)

![WoW_AxL3FENvBL](https://user-images.githubusercontent.com/83077166/142446068-180c38e5-0f7b-424d-93c7-80247a11e254.jpg)

**Comment by slowtorta** [comment]
Fixed in the next revision, thank you.
