### ISSUE TITLE
Annihilator has a low PPM.

### ISSUE THREAD

**Issue by fatnerdynerd** [slowtorta/turtlewow-bug-tracker#4587]
**Please, provide a clear description what the bug is:**
Annihilator was nerfed this patch JUST FOR PALADIN JUDGEMENT but instead the proc chance is lowered for EVERYBODY! Making it impossible to even apply 3 stacks AS A GROUP OF 5!
**Steps to reproduce the behavior with as much detail as possible:**

1. Equip the axe Annihilator along with friends.
2. Swing at a boss.
3. IT BARELY PROCS, can drop off any second.

**IDs of affected creatures, items, quests or spells with a link to the relevant page:**

**Expected behavior. Describe how it should work:**
If 10-ish players have Annihilator it's GOT TO APPLY in SECONDS. Instead this 45 second duration debuff even EXPIRES.

**Comment by jlabranche** [comment]
Had 5 warriors and 2 paladins applying annihilator to Loatheb and it fell off before we got the 3rd stack.

**Comment by AdmiralAwsum** [comment]
I was able to reproduce this problem as well

**Comment by twowTurtReynolds** [comment]
As far as I am aware, it is currently at the blizzlike 1ppm, while an item dev attempted to buff it to two, but unsuccessfully? I will poke them again.

**Comment by melbaa** [comment]
The proc rate is still really bad.

**Comment by twowTurtReynolds** [comment]
After further research, it looks like previously we had a higher rate of 2ppm, and now it is confirmed we have the correct ppm of of 1 seen on blizz Classic.

Further changing of Annihilator is no longer a bug report, but something for the suggestions forum.
