### ISSUE TITLE
spear of the endless hunt does not sheet on the back

### ISSUE THREAD

**Issue by geojak** [slowtorta/turtlewow-bug-tracker#4590]
**Please, provide a clear description what the bug is:**
equip the spear of the endless hunt. it s not visible on your back when not used

**Expected behavior. Describe how it should work:**
should be carried on your back like other polearms

**Comment by Herdon** [comment]
What race are you playing? At the moment (Dec 5) only Goblins have this issue

**Comment by twowTurtReynolds** [comment]
I replicated the fact you couldn't press Z to sheathe and sheathe.

![image](https://github.com/slowtorta/turtlewow-bug-tracker/assets/151180101/7b4a70a5-ecf2-4d2d-85ba-5cf232a7abb8)
![image](https://github.com/slowtorta/turtlewow-bug-tracker/assets/151180101/3e8ce6b5-ea41-49d2-bd08-bd8852cae483)
Looks good on latest patch-5.
