### ISSUE TITLE
Unable to train Survival past level 75/75

### ISSUE THREAD

**Issue by hamoneaster** [slowtorta/turtlewow-bug-tracker#4594]
**Please, provide a clear description what the bug is:**

My character Onlybears cannot learn survival skill past 75/75. The trainer does not have it available to train and WIki says its automatically increased when you get 55/75 to 55/150.

**Steps to reproduce the behavior with as much detail as possible:**

1. Open Character Info
2. Go to Skills
3.  Survival stuck at 75/75 and trainer does not have any more training to do. Rufus Hardwick at NSGY Camp only is a vendor to me.

**Comment by slowtorta** [comment]
Please submit a ticket in game and request remova and manual re-learning of this abiity for your character.
