### ISSUE TITLE
Windfury no longer resets swingtimer

### ISSUE THREAD

**Issue by Niqlo** [slowtorta/turtlewow-bug-tracker#4599]
**Please, provide a clear description what the bug is:**
When windfury procs as a result of stormstrike, crusader strike, hamstring, wing clip etc. it no longer resets your swing timer. This occurs with both the windfury totem and the shaman's personal windfury.

**Steps to reproduce the behavior with as much detail as possible:**

1. acquire windfury
2. spam any ability that procs windfury
3.  your autoattack swing timer will be unaffected regardless of procs

Easiest way to test this is to queue holystrike on a paladin and spam crusader strike with windfury. In the past, your holy strike would not go off if windfury was proccing. Now it will regardless.

**Expected behavior. Describe how it should work:**
If windfury procs, it should immediately cause your swingtimer to reset to its full duration. Essentially, proccing windfury off a hamstring right before an autoattack should nullify the upcoming autoattack and start your swing timer over

it functioned this way until sometime in the past two weeks. My guess is a side effect of fixing a reckoning bug as noted in the patch notes on september 25th.

**Comment by Niqlo** [comment]
they also added an icd to wf in tbc

**Comment by Muigin** [comment]
This behavior has been fixed as of a recent update.
