### ISSUE TITLE
Broodlord Mandokir: Threatening Gaze

### ISSUE THREAD

**Issue by dkwarren** [slowtorta/turtlewow-bug-tracker#46]
By opening this Issue, I admit to having done the pertinent research using sources from Vanilla (preferably) or Classic. I also understand that sources from other private servers are not acceptable.

**Current behavior**: 
If a player has dots on broodlord while his threatening gaze debuff is up, he will kill the target anyway. Also, if you do damage during threatening gaze and you LOS on the wall or some other object, he will not guillotine the target.

**Expected behavior**: 
Threatening gaze should only proc guillotine if the target has moved or performed an action, i.e. sunder armor.

**Proofs**:
It happened twice on the live servers, and it was reproduced on the PTR with Creedence.

**Steps to reproduce**:

1. Have 2 people fight broodlord, one tank, the other put a dot on broodlord. 
2. Once the gaze happens and the dot ticked at least once during the 10 seconds, he should kill the target that produced the dot.
3.

**Comment by dkwarren** [comment]
I'm Daave, the warrior, from TABC btw.

**Comment by Nolin7777** [comment]
Should be fixed at next update
