### ISSUE TITLE
Item: Teresa's Copper Coin

### ISSUE THREAD

**Issue by zesilo** [slowtorta/turtlewow-bug-tracker#460]
**Please, provide a clear description what the bug is:**
You can spam right click the coin making the visual go bonkers if clicked fast enough

**Steps to reproduce the behavior with as much detail as possible:**
1. Pick up quest: Lucky Coin
2. Spam Right Click [Teresa's Copper Coin]

**IDs of affected creatures, items, quests or spells with a link to the relevant page:**
Item: https://database.turtle-wow.org/?item=51425

**Expected behavior. Describe how it should work:**
Probably just needs a 20 second - 60 second cooldown.

**Comment by slowtorta** [comment]
Fixed in the next revision, thank you.
