### ISSUE TITLE
Druid glyphs not working

### ISSUE THREAD

**Issue by Advocatz75** [slowtorta/turtlewow-bug-tracker#4600]
**Please, provide a clear description what the bug is:**
After a recent update/patch, all my druid glyphs were removed from my bags and then later on returned via mail, that's fine. However, now, none of the glyphs work. They are all in my bags just like before but aren't altering my druids appearance. They are unable to go into the keyring and when I try I'm given a message saying 'Item doesn't go in there'. It's not an addon issue as I turned off all addons to test it.

The glyphs I have are; Glyph of the frostsaber, ice bear, stag.

**Steps to reproduce the behavior with as much detail as possible:**

1.
2. 
3. 

**IDs of affected creatures, items, quests or spells with a link to the relevant page:**

NPC: https://database.turtle-wow.org/?npc=
Item: https://database.turtle-wow.org/?item=
Quest: https://database.turtle-wow.org/?quest=
Spell: https://database.turtle-wow.org/?spell=
Object: https://database.turtle-wow.org/?object=

**Expected behavior. Describe how it should work:**

**Comment by welpenhund** [comment]
> **Please, provide a clear description what the bug is:** After a recent update/patch, all my druid glyphs were removed from my bags and then later on returned via mail, that's fine. However, now, none of the glyphs work. They are all in my bags just like before but aren't altering my druids appearance. They are unable to go into the keyring and when I try I'm given a message saying 'Item doesn't go in there'. It's not an addon issue as I turned off all addons to test it.
> 
> The glyphs I have are; Glyph of the frostsaber, ice bear, stag.
> 
> **Steps to reproduce the behavior with as much detail as possible:**
> 
> 
> **IDs of affected creatures, items, quests or spells with a link to the relevant page:**
> 
> NPC: https://database.turtle-wow.org/?npc= Item: https://database.turtle-wow.org/?item= Quest: https://database.turtle-wow.org/?quest= Spell: https://database.turtle-wow.org/?spell= Object: https://database.turtle-wow.org/?object=
> 
> **Expected behavior. Describe how it should work:**

Right click them, they have to be "learned" now and will appear as glyphs in your spellbook. They work fine :-)

**Comment by Advocatz75** [comment]
Oh, I see. Thank you.
The tooltip still says 'keep this in your bag'. That's what confused me.

________________________________
