### ISSUE TITLE
关于人类战士无法接取《战士的训练》10级防御姿态职业任务!

### ISSUE THREAD

**Issue by xiaobaiyunQAQ** [slowtorta/turtlewow-bug-tracker#4601]
**Please, provide a clear description what the bug is:**关于人类战士无法接取《战士的训练》职业任务，NPC处未显示该任务（本人已经查找过三个主城的NPC与各个任务环节，均未显示有可接取初始任务或后续任务），现在具体表现为战士训练师NPC处无《战士的职训练》任务，无法接取。本人人物ID 守护最好坤坤，服务器 血环。目前该账号已经满级，请求及时处理！

**Steps to reproduce the behavior with as much detail as possible:**

1.人类战士职业达到10级
2. 职业训练师处自动出现战士的训练任务
3. 前往接取任务《战士的训练》

**IDs of affected creatures, items, quests or spells with a link to the relevant page:**

NPC: https://database.turtle-wow.org/?npc=伊尔萨·考宾
Item: https://database.turtle-wow.org/?item=
Quest: https://database.turtle-wow.org/?quest=《战士的训练》
Spell: https://database.turtle-wow.org/?spell=
Object: https://database.turtle-wow.org/?object=

**Expected behavior. Describe how it should work:**
![image](https://github.com/slowtorta/turtlewow-bug-tracker/assets/147226231/cd543554-ca4e-43d1-a60f-f38a063eb9c6)

**Comment by Muigin** [comment]
请用英文提交问题。我们无法通过自动翻译准确地翻译中文提交的错误报告，这使得我们难以理解问题的确切性质。谢谢！

Please submit the issues in English. We're unable to accurately translate bug reports submitted in Chinese through automatic translation, which makes it difficult for us to understand the exact nature of the issue. Thank you!
