### ISSUE TITLE
Maw not dropping the blue septer shard

### ISSUE THREAD

**Issue by nickgreyden** [slowtorta/turtlewow-bug-tracker#4602]
Killed Maw. Nothing to loot in body. Arcane buoy is gone. I was master looter so no one else took it. Attempted to switch people, change loot to free for all, and switch back. No one, at any time, saw the body sparkle. Mob just didn't drop it. Could not resummon mob because buoy was used.

**Steps to reproduce the behavior with as much detail as possible:**

1. Be on Wrath of Neptune quest.
2. Use bouy spawn Maw
3. Kill Maw
4. Worked for another guild mate 5 mins earlier with his bouy so you probably can't reproduce it. But GM told me they can't do anything and I have to report it as a bug. Here is to the off chance this actually works.

**IDs of affected creatures, items, quests or spells with a link to the relevant page:**

Turtle Database is down until Oct 27th
NPC: Wowhead data base is https://www.wowhead.com/classic/npc=15571/maws
Item: https://www.wowhead.com/classic/item=21136/arcanite-buoy
Item: https://www.wowhead.com/classic/item=21137/blue-scepter-shard
Quest: https://www.wowhead.com/classic/quest=8729/the-wrath-of-neptulon

**Expected behavior. Describe how it should work:**
Blue secpter shard should be a 100% drop rate. Should be on the body to loot. Body had nothing to loot. But worked just fine 5 mins previously for another guildmate.

Update: Dropped the quest and picked it back up. Arcane buoy back in inventory. Can attempt again... whenever I can get people to try again.

**Comment by twowTurtReynolds** [comment]
![image](https://github.com/slowtorta/turtlewow-bug-tracker/assets/151180101/a38df2a1-e61f-439c-8e2b-add1e99ec5e0)
Works fine. Perhaps there were some master looter shenanigans?

**Comment by StasyaLyova** [comment]
> ![image](https://private-user-images.githubusercontent.com/151180101/287924676-a38df2a1-e61f-439c-8e2b-add1e99ec5e0.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDUwMzE2NDAsIm5iZiI6MTcwNTAzMTM0MCwicGF0aCI6Ii8xNTExODAxMDEvMjg3OTI0Njc2LWEzOGRmMmExLWU2MWYtNDM5Yy04ZTJiLWFkZDFlOTllYzVlMC5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwMTEyJTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDExMlQwMzQ5MDBaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT05N2VmNDE3ZDNkZDgzYmVhMDhiYWRjZTI4ZDJiMjE0ZGJhN2VjZWI4NDcxNGVlYjI5ZmIyNzFlNTI5YTgwNGMyJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.HpoCxEDlw163Icd2QtpC7ttabGAO2w0VxdqCOBNlphU) Works fine. Perhaps there were some master looter shenanigans?

Seems trouble is Draconic for Dummies and Scepter Shards (green, blue, red) - all is white, quest loot but it can get only one in raid, only one person (who is faster or closer to body and have quest) and that's not fair.
