### ISSUE TITLE
1. My goblin character stuck on Ogrimmar's quest, Welcome to Amani Alor. I cannot get the quest and there is no quest for me to abandon and reset it. If I cannot get this quest, I cannot get the reputation quest of Revantask troll

### ISSUE THREAD

**Issue by InvidiaAngel** [slowtorta/turtlewow-bug-tracker#4604]
**Please, provide a clear description what the bug is:**

**Steps to reproduce the behavior with as much detail as possible:**

1.
2. 
3. 

**IDs of affected creatures, items, quests or spells with a link to the relevant page:**

NPC: https://database.turtle-wow.org/?npc=
Item: https://database.turtle-wow.org/?item=
Quest: https://database.turtle-wow.org/?quest=
Spell: https://database.turtle-wow.org/?spell=
Object: https://database.turtle-wow.org/?object=

**Expected behavior. Describe how it should work:**

**Comment by InvidiaAngel** [comment]
My goblin character stuck on Ogrimmar's quest, Welcome to Amani Alor. I cannot get the quest and there is no quest for me to abandon and reset it. If I cannot get this quest, I cannot get the reputation quest of Revantask troll

**Comment by shilei175** [comment]
I had the same problem, and deleting WDB didn't work. It is a BUG, clear technical personnel as soon as possible to fix.

**Comment by norstromo** [comment]
Same problem
