### ISSUE TITLE
The item Spicy Beef Burrito imposes a 1 min cd on all foods

### ISSUE THREAD

**Issue by balakethelock** [slowtorta/turtlewow-bug-tracker#4605]
**Please, provide a clear description what the bug is:**
Title is self explanatory, this food puts all foods on a 1 min cd which is inconsistent with every other food item in the game

**Steps to reproduce the behavior with as much detail as possible:**

1. Fill your inventory with different types of food, mage oranges.
2. Eat a "pizza bottle"
3. See that all foods are put on a cd

**Expected behavior. Describe how it should work:**
Foods don't have a cooldown

**Comment by twowTurtReynolds** [comment]
https://database.turtle-wow.org/?item=51267

**Comment by Dragunovi** [comment]
Should be fixed in the next scheduled server restart.
