### ISSUE TITLE
[Headmaster's Charge] Use Buff does not stack with Arcane Brilliance (Mage buff)

### ISSUE THREAD

**Issue by KreepAK** [slowtorta/turtlewow-bug-tracker#4607]
Buff provided by using [Headmaster's Charge], epic staff from last boss in Scholo, does not stack with mage intellect buff.

STR:

1. Right click on [Headmaster's Charge]

Expected result:

Buff should stack since they come from different sources. Its like Crusader wont stack with Juju Might.

**Comment by ratkosrb** [comment]
https://github.com/slowtorta/turtlewow-bug-tracker/assets/35845488/f96fe5a2-153f-4721-bfec-505004d35d0c

Can't reproduce the issue. They do stack.
