### ISSUE TITLE
[Wrath of Cenarius] proc rate%

### ISSUE THREAD

**Issue by KreepAK** [slowtorta/turtlewow-bug-tracker#4609]
I am an Elemental Shaman and was happy to get [Wrath of Cenarius] ring. But, after doing some testing, to be specific - I was hitting Target Dummy in OG with Rank 1 Lightning Bolt so my 6k mana pool would go down slower, I didnt get any proc at all. However, there was an Enhancement shammy next to me, equipped with the same ring, geared on elemental procs (items that give 1-5 elemental dmg on melee hit), and he had 100% uptime from [Wrath of Cenarius]. 
Another class is Warlock, who benefits from that ring. All warlocks have DoT abilities and said that each DoT has a chance to proc [Wrath of Cenarius] ring and its pretty decent for them. Especially if you are going with SM/RUIN build.

So, my questions would be:

1. Does it or does it not proc from casting spells?
2. Does it proc only from melee spell hit such as described above.
3. Does it proc only from DoTs?
4. Why proc% is so misarable? Item is really hard to get and I am really disappointed with it.

Could you please explain this? I dont understand why it cant proc more often, and if you think thats too OP (which is not) add some internal CD on procs. For example, make proc rate super high (or just higher that it is right now), but it can proc once in 30s-60s. Something like a trinket usage. 

Looking forward to hearing from you.

**Comment by twowTurtReynolds** [comment]
![image](https://github.com/slowtorta/turtlewow-bug-tracker/assets/151180101/52b94e1f-2cc5-4f23-a085-4dbfc1ed9a2b)
On my third cast of lightning bolt rank 1, I have a proc. All seems to be working.
