### ISSUE TITLE
Polearm training unavailable for goblin

### ISSUE THREAD

**Issue by dumbnwah** [slowtorta/turtlewow-bug-tracker#461]
**Please, provide a clear description what the bug is:**Polearm training unavailable for goblin

**Steps to reproduce the behavior with as much detail as possible:**

1.
2. 
3. 

**IDs of affected creatures, items, quests or spells with a link to the relevant page:**
NPC: https://database.turtle-wow.org/?npc=
Item: https://database.turtle-wow.org/?item=
Quest: https://database.turtle-wow.org/?quest=
Spell: https://database.turtle-wow.org/?spell=
Object: https://database.turtle-wow.org/?object=
**Expected behavior. Describe how it should work:**

**Comment by Tinyfin-github** [comment]
Can you please provide more information?
We have tested and we were unable to reproduce the problem.
Weapons are not race locked,  they are class locked. Only  Hunters, Paladins, and Warrior can learn Polearms
Make sure you are the correct NPC : https://database.turtle-wow.org/?npc=11870 Archibald in Undercity  and have the required silver and level 5.
Check at the trainer Filter that Available is turned on.

Please make  proper report with screenshots or videos that will show us how to reproduce the bug and sources that show the correct behavior


![WoW_FPVv72M5L1](https://user-images.githubusercontent.com/83077166/142563808-50a75739-4190-42ad-a79c-c635577e3891.png)


https://user-images.githubusercontent.com/83077166/142563866-2b09694f-8a4f-4f0b-ad5c-19e6fa240c2f.mp4

 
![image](https://user-images.githubusercontent.com/83077166/142563906-196ea4da-7340-4b8f-843a-bcf0a112bbb7.png)
