### ISSUE TITLE
Consecration seems to have no above/below range and can pull mobs far below.

### ISSUE THREAD

**Issue by Tobbsu** [slowtorta/turtlewow-bug-tracker#4610]
* Umm the the (X, and Y Is fine but the Z do not have range yd) .
* Consecation some how can pull from floor below or top bc it do not have yd range in dme or that some how is buged you pull full of enemys that you was not even close too?.

**Comment by twowTurtReynolds** [comment]
Please provide an example on how this can be replicated. We provided you with a template, and you should use it.

**Comment by twowTurtReynolds** [comment]
Closing until reply.
