### ISSUE TITLE
BWL: Blackwing Warlocks' summoning portals remain after death

### ISSUE THREAD

**Issue by Zebouski** [slowtorta/turtlewow-bug-tracker#462]
**Please, provide a clear description what the bug is:**
In BWL, the Blackwing Warlocks each create a red portal to port in an additional mob. These remain after the warlock is killed, and will inevitably spawn the add.

**Steps to reproduce the behavior with as much detail as possible:**

1. Go to the raid section after broodlord lashslayer
2. pull the pack, allow the red circle to appear
3. kill the warlock, see it remain

**IDs of affected creatures, items, quests or spells with a link to the relevant page:**

https://database.turtle-wow.org/?npc=12459

**Expected behavior. Describe how it should work:**

When the blackwing warlock is killed before the portal's 15 or so second completion time, the portal should despawn and no add spawns. Can be seen here in this 2006 video https://youtu.be/UbdQemDW66w?t=4903

**Comment by Zebouski** [comment]
I'm hearing this got fixed recently?

**Comment by ratkosrb** [comment]
Indeed.
