### ISSUE TITLE
[The Super Egg-O-Matic] quest series

### ISSUE THREAD

**Issue by Bravian-XP** [slowtorta/turtlewow-bug-tracker#4623]
Please check the functionality of the NPC [[Curgle Cranklehop]](https://database.turtle-wow.org/?npc=7763). She should receiving eggs after [[The Super Egg-O-Matic]](https://database.turtle-wow.org/?quest=8893)  machine has cleared [[Hippogryph Egg]](https://database.turtle-wow.org/?item=8564).

Must have quests:
[A Bad Egg](https://database.turtle-wow.org/?quest=2750)
[A Fine Egg](https://database.turtle-wow.org/?quest=2748)
[An Ordinary](https://database.turtle-wow.org/?quest=2749)
[An Extraordinary](https://database.turtle-wow.org/?quest=2747)

But the NPC doesn't offer any quests. Previously I done 2 quests from the list, but they should be repetable.
![World-of-Warcraft-230925155404](https://github.com/slowtorta/turtlewow-bug-tracker/assets/146672371/e439fac7-d938-4f33-8cd9-e9d000ebac1d)

I can only use he Super Egg-O-Matic for the first stage. I already have a few eggs in my bag.
![World-of-Warcraft-230925155436](https://github.com/slowtorta/turtlewow-bug-tracker/assets/146672371/6cc4b201-dd10-4548-961d-3514968cd8c8)

**Comment by Muigin** [comment]
These quests have been fixed as of a recent update.
