### ISSUE TITLE
In Dreams Quest Bugged

### ISSUE THREAD

**Issue by fleezuschrist6** [slowtorta/turtlewow-bug-tracker#4628]
**Please, provide a clear description what the bug is:**
Doing the "In Dreams" quest in Western Plaguelands. I died while doing the final boss, came back and Taelon was still there. When I arrived back there was an elite still next to him so I tried to kite him. I ended up kiting the mob but Taelon disappeared. The quest is completed in my quest log.
**Steps to reproduce the behavior with as much detail as possible:**

1. Follow Taelon to tower
2. Die mid fight, come back
3. Kite mob out of Taelon's area and come back

**IDs of affected creatures, items, quests or spells with a link to the relevant page:**

NPC: https://database.turtle-wow.org/?npc=HighlordTaelanFordring
Item: https://database.turtle-wow.org/?item=
Quest: https://database.turtle-wow.org/?quest=InDreams
Spell: https://database.turtle-wow.org/?spell=
Object: https://database.turtle-wow.org/?object=

**Expected behavior. Describe how it should work:**
Should still be there when you leave the area.

**Comment by ratkosrb** [comment]
You took too long to turn in the quest. Tirion is not meant to stay there forever. It's not a bug that he despawned eventually. Either wait there for somebody else to do the quest and then turn it in when Tirion comes, or abandon it and start it again.
