### ISSUE TITLE
Druid glyphs still not working

### ISSUE THREAD

**Issue by Advocatz75** [slowtorta/turtlewow-bug-tracker#4629]
**Please, provide a clear description what the bug is:**
This was my previous ticket:
After a recent update/patch, all my druid glyphs were removed from my bags and then later on returned via mail, that's fine. However, now, none of the glyphs work. They are all in my bags just like before but aren't altering my druid's appearance. They are unable to go into the keyring and when I try I'm given a message saying 'Item doesn't go in there'. It's not an addon issue as I turned off all addons to test it.

The glyphs I have are; Glyph of the frostsaber, ice bear, stag.

I received a reply telling me I needed to right-click on the glyphs:
"Right-click them, they have to be "learned" now and will appear as glyphs in your spellbook. They work fine :-)"

However, the glyphs remain 'unclickable', and nothing happens. What is the next thing to try?

**Steps to reproduce the behavior with as much detail as possible:**

1.
2. 
3. 

**IDs of affected creatures, items, quests or spells with a link to the relevant page:**

NPC: https://database.turtle-wow.org/?npc=
Item: https://database.turtle-wow.org/?item=
Quest: https://database.turtle-wow.org/?quest=
Spell: https://database.turtle-wow.org/?spell=
Object: https://database.turtle-wow.org/?object=

**Expected behavior. Describe how it should work:**

**Comment by SignOfTheRaven** [comment]
After I deleted the WDB folder, I received all of my purchased glyphs in the mail. I then right clicked each of them to learn them. They appeared in a newly created spell book tab called Glyphs. I then had to left click each of the newly learned spells to make the druid form appearances work. Hopefully that helps you in some way.

**Comment by Advocatz75** [comment]
I appreciate everyone's assistance on this. Unfortunately, even after deleting the WDB folder, shutting everything down, turning off all addons, and rebooting wow, all the glyphs remain unclickable and still say "Has effect as long as this glyph is in your bag".

Could there be an issue with the glyphs themselves? Old glyphs still operating under the old stipulations?

Thank you

**Comment by cyaohiri** [comment]
Duplicate of #4600.

**Comment by Advocatz75** [comment]
I viewed #4536 and the person said "I received a letter from the system, which was a variant glyph of (stag Form) that disappeared after use". I also received my 3 glyphs back via mail but were not variants, they are the exact same glyphs with the old stipulations. My glyphs are not interactable, they do nothing when left or right clicked, no new tab is created, and the tooltip on each glyph still reads 'Has effect as long as this is in your bag'.

**Comment by Advocatz75** [comment]
Should I re-ticket this?
I don't know what the problem is or how to fix it.

**Comment by luskanek** [comment]
Did you try to delete your WDB folder?

**Comment by Advocatz75** [comment]
I had previously deleted the WDB folder twice following other people's advice. However, this time, I deleted the WDB folder for a third time but I also created a new empty WDB folder in the Twow folder. When I logged into Twow all the glyphs were clickable. Weird that worked but it worked nonetheless.

Thank you
________________________________

**Comment by luskanek** [comment]
The folder was probably cached somehow, no idea if that's possible, nonetheless I'm glad it works for you now.
