### ISSUE TITLE
Phoenix Hatchling turned into Poley

### ISSUE THREAD

**Issue by DulceSwordfish** [slowtorta/turtlewow-bug-tracker#463]
**Please, provide a clear description what the bug is:**

The shop critter pet [Phoenix Hatchling] is in fact an ice bear cub on summoning.

**Steps to reproduce the behavior with as much detail as possible:**

Use Phoenix Hatchling

**IDs of affected creatures, items, quests or spells with a link to the relevant page:**

https://database.turtle-wow.org/?npc=81008

**Expected behavior. Describe how it should work:**

Summons Phoenix Hatchling

https://user-images.githubusercontent.com/94675056/142585781-7eeecb49-1ceb-4811-b8c1-901beb93091e.mp4

**Comment by Tinyfin-github** [comment]
https://github.com/slowtorta/turtlewow-bug-tracker/issues/457

It will be fixed with the release of 1.15.2.

**Comment by DulceSwordfish** [comment]
how did I miss #457 when scrolling through? ^^;; thanks for the heads up!
