### ISSUE TITLE
Seal of Ascension won't complete

### ISSUE THREAD

**Issue by EnriqueFerrerMelian** [slowtorta/turtlewow-bug-tracker#4630]
**Please, provide a clear description what the bug is:**
I have finished to complete the quest line for the UBRS key, "Seal of Ascension". When i went to the NPC (Scarshield Infiltrator), he won't open the quest window to complete it.

**Steps to reproduce the behavior with as much detail as possible:**

1. Get the Forged Seal of Ascension
2. Interact to the NPC Scarshield Infiltrator
3. 

**IDs of affected creatures, items, quests or spells with a link to the relevant page:**
Scarshield Infiltrator

NPC: https://database.turtle-wow.org/?npc=10299
Item: https://database.turtle-wow.org/?item=12324
Quest: https://database.turtle-wow.org/?quest=4743
Spell: https://database.turtle-wow.org/?spell=
Object: https://database.turtle-wow.org/?object=12344

**Expected behavior. Describe how it should work:**
You talk to the NPC, the window with the "complete" button should appear. You complete the quest and receive Seal of Ascension (12344)

**Comment by byvide** [comment]
**same issue here**

A have the quest and the quest item to complete the quest. 
A gm tried to "reset" the npc, but same behavior: he only offers the speaking-his-story option, no sign of any quest option.

**Comment by twowTurtReynolds** [comment]
Couldn't reproduce in newer ticket https://github.com/slowtorta/turtlewow-bug-tracker/issues/4661

**Comment by EnriqueFerrerMelian** [comment]
Ok, then what can we do?
