### ISSUE TITLE
Invocation enchants (Kara 10) not enchanting correct item slot

### ISSUE THREAD

**Issue by Smileybob1** [slowtorta/turtlewow-bug-tracker#4631]
The new enchants available from the new NPC outside Kara do not enchant the correct slot. The  green text currently reads that it will enchant a LEG or HEAD slot.

I have tried with an Invocation of Greater Protection and it returns "That item is not a valid target". However the Invocation WILL work when attempted to use on a shoulder item. It appears that either the item description is wrong, or the item is wrongly coded as a shoulder enchant and a head/leg enchant.

Have not yet tested with other invocations as the Invocation of Greater Protection is all I have.

Furthermore the quest to receive the invocation is not repeatable meaning you can currently only get one of each type.

**Comment by kdla90** [comment]
Can confirm Invocation of Shattering also only works on shoulders. Hope it will be fixed to enchant what the text says Head and Leg. Atleast Quest is repeatable for me.
