### ISSUE TITLE
Account getting on queue even when the server is not full

### ISSUE THREAD

**Issue by SeguisDumble** [slowtorta/turtlewow-bug-tracker#4633]
**Please, provide a clear description what the bug is:**
My wife and I are playing together in Turtle WoW. Our issue is that my wife's account gets queued sometimes, even when the server is not full. Her number on the queue usually gets up instead of going down. Obviously, we are playing on different PCs but in the same house with the same router. I don't think our issue is because of veteran prioritization because my account is like 2 or 3 months old only

**Steps to reproduce the behavior with as much detail as possible:**
1. I log into the game without issues.
2. Using `.server info` I can confirm the server is not full.
3. My wife tries to log in and get into the queue.
4. Her queue number usually goes up.

**Comment by Junka00** [comment]
I think it is beacuse you are on the same network, when a second account tries logging in, the queue priority system thinks you are trying to login with alt account and therefore it places your wife lower on queue priority. 
   One workaround that often works is clicking the "change realm" button on the log in screen. Sometimes you have to click it multiple times to successfully skip the queue (My record is clicking the "change realm" button 9 times before getting in).
   Hope this helps!

**Comment by twowTurtReynolds** [comment]
Queues are gone :)

We had extreme measures in place around that time period to handle everyone.
