### ISSUE TITLE
Cleaning cloth not working

### ISSUE THREAD

**Issue by Kisangi** [slowtorta/turtlewow-bug-tracker#4636]
**Please, provide a clear description what the bug is:**
Cleaning cloth not showing up in survival profession, tried learning it from recipe twice, deleting WTF-folder.
**Steps to reproduce the behavior with as much detail as possible:**

1. 
2. 
3. 

**IDs of affected creatures, items, quests or spells with a link to the relevant page:**

NPC: https://database.turtle-wow.org/?npc=
Item: https://database.turtle-wow.org/?item=
Quest: https://database.turtle-wow.org/?quest=
Spell: https://database.turtle-wow.org/?spell=
Object: https://database.turtle-wow.org/?object=

**Expected behavior. Describe how it should work:**

**Comment by slowtorta** [comment]
Will be fixed in patch 1.17.1.
