### ISSUE TITLE
[QUEST] Noboru the Cudgel

### ISSUE THREAD

**Issue by Awkakelen** [slowtorta/turtlewow-bug-tracker#4637]
PROBLEM:

I had a problem with quest called [Noboru the Cudgel]; before taking the quest I have had killed the required mob and looted the cudgel from him. When I took the quest (had a required item for completing the quest).

**Steps to reproduce the behavior with as much detail as possible:**

STEPS TO REPRODUCE BUG:

1. Find Noboru
2. Kill him and loot cudgel 
3. Get quest and find that you can't turn in the quest despite having required item

REQUIRED IDS:

NPC: https://www.wowhead.com/classic/npc=5477/noboru-the-cudgel
ITEM: https://www.wowhead.com/classic/item=6196/noborus-cudgel
Quest: https://www.wowhead.com/classic/quest=1392/noboru-the-cudgel

EXPECTED BEHAVIOR:
Having an item already should be enough to complete a quest, something like having cloth to complete quartermaster quests.

**Comment by cyaohiri** [comment]
There are two different items. One is the gray mace, and the other is the item for the actual quest. This is intended; see #3814.
