### ISSUE TITLE
Crippling poison II missing from regeants vendor in Alterac Valley

### ISSUE THREAD

**Issue by MrTmp** [slowtorta/turtlewow-bug-tracker#4638]
Crippling poison II is missing from Yaelika Farclaw the <Reagents & Poisons> vendor in Alterac Valley.

**Comment by byvide** [comment]
I think you meant the reagent for it, [Essence of Agony](https://database.turtle-wow.org/?item=8923#sold-by:0+3+1)

**Comment by MrTmp** [comment]
> I think you meant the reagent for it, [Essence of Agony](https://database.turtle-wow.org/?item=8923#sold-by:0+3+1)

https://database.turtle-wow.org/?npc=10364

**Comment by byvide** [comment]
Im confused, arent you talking about [Yaelika Farclaw](https://database.turtle-wow.org/?npc=10364) not selling [Essence of Agony](https://database.turtle-wow.org/?item=8923#sold-by:0+3+1) despite the alliance counterpart does? As far as i know "Crippling poison II" is crafted, not sold.

**Comment by MrTmp** [comment]
> Im confused, arent you talking about [Yaelika Farclaw](https://database.turtle-wow.org/?npc=10364) not selling [Essence of Agony](https://database.turtle-wow.org/?item=8923#sold-by:0+3+1) but the alliance counterpart does? As far as i know "Crippling poison II" is crafted, not sold.

Check her vendor table dumbass. On turtle she sells already crafted poisons and crippling 2 is missing.

**Comment by byvide** [comment]
> > Im confused, arent you talking about [Yaelika Farclaw](https://database.turtle-wow.org/?npc=10364) not selling [Essence of Agony](https://database.turtle-wow.org/?item=8923#sold-by:0+3+1) but the alliance counterpart does? As far as i know "Crippling poison II" is crafted, not sold.
> 
> Check her vendor table dumbass. On turtle she sells already crafted poisons and crippling 2 is missing.

What i see is that [Crippling Poison II](https://database.turtle-wow.org/?item=3776) is only crafted and no npc in the game is selling it directly. If this poison was sold by vendors back in the day, then some kind of proof would be nice.

On the other hand, the [the alliance poison vendor](https://database.turtle-wow.org/?npc=5139) is selling more items than the [horde one](https://database.turtle-wow.org/?npc=10364), including [Essence of Agony](https://database.turtle-wow.org/?item=8923#sold-by:0+3+1), the reagent for "Crippling Poison II".

**Comment by MrTmp** [comment]
> > > Im confused, arent you talking about [Yaelika Farclaw](https://database.turtle-wow.org/?npc=10364) not selling [Essence of Agony](https://database.turtle-wow.org/?item=8923#sold-by:0+3+1) but the alliance counterpart does? As far as i know "Crippling poison II" is crafted, not sold.
> > 
> > 
> > Check her vendor table dumbass. On turtle she sells already crafted poisons and crippling 2 is missing.
> 
> What i see is that [Crippling Poison II](https://database.turtle-wow.org/?item=3776) is only crafted and no npc in the game is selling it directly. If this poison was sold by vendors back in the day, then some kind of proof would be nice.
> 
> On the other hand, the [the alliance poison vendor](https://database.turtle-wow.org/?npc=5139) is selling more items than the [horde one](https://database.turtle-wow.org/?npc=10364), including [Essence of Agony](https://database.turtle-wow.org/?item=8923#sold-by:0+3+1), the reagent for "Crippling Poison II".

Are you part of the dev team and triaging bugs or just a bored individual with nothing better to do than post irrelevant information on 4 months old bug tickets?

Why would I need to provide any proof over the obvious that this specific rank of crippling is missing from the vendor table when EVERY OTHER ONES are available. On live classic these NPCs sell the base materials while on turtle they sell the final products. A great change considering when you're in a BATTLEGROUND you should be fighting, not sitting there crafting shit.

If you're that bored, open a ticket over the fact that the alliance counterpart sells base reagents when he shouldn't, as it's obviously not intended, since there are no other base reagents (like death weed, essence of pain) for all other poisons.

**Comment by MrTmp** [comment]
> > > Im confused, arent you talking about [Yaelika Farclaw](https://database.turtle-wow.org/?npc=10364) not selling [Essence of Agony](https://database.turtle-wow.org/?item=8923#sold-by:0+3+1) but the alliance counterpart does? As far as i know "Crippling poison II" is crafted, not sold.
> > 
> > 
> > Check her vendor table dumbass. On turtle she sells already crafted poisons and crippling 2 is missing.
> 
> What i see is that [Crippling Poison II](https://database.turtle-wow.org/?item=3776) is only crafted and no npc in the game is selling it directly. If this poison was sold by vendors back in the day, then some kind of proof would be nice.
> 
> On the other hand, the [the alliance poison vendor](https://database.turtle-wow.org/?npc=5139) is selling more items than the [horde one](https://database.turtle-wow.org/?npc=10364), including [Essence of Agony](https://database.turtle-wow.org/?item=8923#sold-by:0+3+1), the reagent for "Crippling Poison II".

Are you part of the dev team and triaging bugs or just a bored individual with nothing better to do than post irrelevant information on 4 months old bug tickets?

Why would I need to provide any proof over the obvious that this specific rank of crippling is missing from the vendor table when EVERY OTHER ONES are available. On live classic these NPCs sell the base materials while on turtle they sell the final products. A great change considering when you're in a BATTLEGROUND you should be fighting, not sitting there crafting shit.

If you're that bored, open a ticket over the fact that the alliance counterpart sells base reagents when he shouldn't, as it's obviously not intended, since there are no other base reagents (like death weed, essence of pain) for all other poisons.

**Comment by byvide** [comment]
The devs have "collaborator" title, im just a "bored individual" who stumbled upon this, and why not ask for clarification if that makes the devs job easier and resolve faster?

I think i described why i think what in 2 sentences, while you throw me a dislike, an npc link, and now this. I didnt know about this change, thanks for sharing.

**Comment by MrTmp** [comment]
Resolved in https://forum.turtle-wow.org/viewtopic.php?t=13178
