### ISSUE TITLE
Gurubashi doesn't give honor, ghost spawns at Booty Bay

### ISSUE THREAD

**Issue by DulceSwordfish** [slowtorta/turtlewow-bug-tracker#464]
**Please, provide a clear description what the bug is:**

Killing other players of the same faction in Gurubashi Arena doesn't give honor. After releasing your ghost you get taken to Booty Bay instead of to the spirit healers at the side of the Arena. (Only tested on alliance side)

**Steps to reproduce the behavior with as much detail as possible:**

Kill player within xp range and of same faction in Gurubashi Arena pit

Die in Gurubashi Arena pit and release spirit.

**IDs of affected creatures, items, quests or spells with a link to the relevant page:**

**Expected behavior. Describe how it should work:**

After killing a non trivial player within the pit you should get honor.
After releasing your spirit in the pit you should get a trip to the spirit healers right next to it.

**Comment by GrenderG** [comment]
Will be fixed on next restart.
