### ISSUE TITLE
Spell: Vagrant's Endeavor

### ISSUE THREAD

**Issue by cyaohiri** [slowtorta/turtlewow-bug-tracker#4642]
Unlike all other challenges that are started with a glyph, Vagrant's Endeavor cannot be cancelled. This seems unintentional as even Slow and Steady challenge, that gives you rewards, can be cancelled after getting the rewards, but Vagrant's Endeavor, which doesn't, cannot.

**Comment by luskanek** [comment]
Fixed in the next update - added an option to quit the challenge.
