### ISSUE TITLE
Other: Whisper level requirement

### ISSUE THREAD

**Issue by cyaohiri** [slowtorta/turtlewow-bug-tracker#4645]
As the population increased, the minimum character level required to whisper others was set to 5, probably to reduce the spam from bad actors.
Unfortunately, this restriction is present even if the account is old and has high level characters on it, which seems like an oversight.
It seems reasonable to be able to whisper at level 1 if there are high level characters on the same account.
In my case, I have multiple lv50+ characters, and the account is over a year old, but I'm still unable to whisper on a new character until level 5.
In contrast, global channels, such as /world, can be used even at level 1, at least on my account.

**Comment by luskanek** [comment]
I forwarded your suggestion to the team and we'll have to discuss this. I think you're right and I'm in favor for lifting the restrictions for veteran players.

In the future please use the 'Suggestions' section on the forums to make suggestions.
