### ISSUE TITLE
Bugged skin in the Donation shop

### ISSUE THREAD

**Issue by Cinnamon227** [slowtorta/turtlewow-bug-tracker#4646]
**Please, provide a clear description what the bug is:**
The skin Necromancer II, Night elf, male only item within the donation shop has a bug where its only for Humans, causing you to not be able to activate for Night elves
**Steps to reproduce the behavior with as much detail as possible:**

1.
2. 
3. 

**IDs of affected creatures, items, quests or spells with a link to the relevant page:**

NPC: https://database.turtle-wow.org/?npc=
Item: https://database.turtle-wow.org/?item=
Quest: https://database.turtle-wow.org/?quest=
Spell: https://database.turtle-wow.org/?spell=
Object: https://database.turtle-wow.org/?object=

**Expected behavior. Describe how it should work:**
Should alter your skin as a Night elf Male

**Comment by slowtorta** [comment]
Fixed.
