### ISSUE TITLE
Nightfin Snapper no longer seems to exist in Moonglade or Winterspring.

### ISSUE THREAD

**Issue by OlWeigand** [slowtorta/turtlewow-bug-tracker#4651]
**Please, provide a clear description what the bug is:**
Since the October 7 patch that adds fishing to Hyjal, Nightfin Snapper and Sunscale Salmon can no longer be caught in either Moonglade or Winterspring.

**Steps to reproduce the behavior with as much detail as possible:**
1. Measured over 50 casts in Moonglade and Winterspring.
2. Within this time, no Nightfin Snapper or Sunscale Salmon was caught. This is statistically possible, but not likely.
3. Similar behavior was reported (second-hand) in Feralas.

**Expected behavior. Describe how it should work:**
Usually, you'd have a ~12,5% chance to catch either Nightfin Snapper or Sunscale Salmon in Moonglade, or a 25% chance in Winterspring. The exact ratios vary by the time of day, but some chance of catching either is expected.

**Comment by 23306599-5** [comment]
Came here to say exactly this. Didnt catch Nightfin Snapper nor Sunscale Salmon on Moonglade.
I tried more than 30 times.

**Comment by hlamonix** [comment]
It appears that the skill required has been increased drastically, idk whether intentional or by mistake. Before the patch i (almost) never encountered "the fish got away" message in Moonglade. Right now with my current skill level, it's ~20% of all my casts.

**Comment by Muigin** [comment]
#4530
