### ISSUE TITLE
Used recipies on the auction house 

### ISSUE THREAD

**Issue by ClairicalError** [slowtorta/turtlewow-bug-tracker#4652]
The database is inaccessible at the moment so please forgive the lack of links.
I purchased the recipes for Rune-etched greaves and Rune-etched off of the auction house on my character Essira. Upon receiving the plans I discovered that they both had 0 charges remaining and were unusable. The items are still in my inventory, and upon closer inspection more plans with 0 charges can be found on the auction house including one for Rune-etched crown. I found the plans for Rune-etched Breastplate myself as a dungeon drop and it functioned normal as did the legplates and mantle recipes, though I also see 0 charge recipes for those on the auction house as well. This leads me to the conclusion that their is a way to use the plans without the item deleting, allowing the useless plans to then be sold on the auction house at full price.

**Comment by Muigin** [comment]
This behavior has been fixed as of a recent update.
