### ISSUE TITLE
new [Thorium Spurs] don't work

### ISSUE THREAD

**Issue by Kirchlive** [slowtorta/turtlewow-bug-tracker#4654]
**Please, provide a clear description what the bug is:**
The new Thorium Spurs don't work. You have 200% speed with and without Thorium Spurs boots.

**Steps to reproduce the behavior with as much detail as possible:**
1. If you put the Thorium Spurs boots on while riding, the speed snaps to 214% and immediately goes back to 200%.
2. Mithril Spurs continues work normal like intended with 208% riding speed.

**IDs of affected creatures, items, quests or spells with a link to the relevant page:**
Item ID: 61182

**Expected behavior. Describe how it should work:**
https://i.imgur.com/yr5EGbG.png
Measured with MonkeySpeed addon.

**Comment by ConcernedTurtler** [comment]
yeah I've noticed no noticeable speed increase while using these as well.

**Comment by afizzler** [comment]
they don't work i noticed no speed increase

**Comment by kravis** [comment]
Tried it with monkey speed too, no change in speed with the Thorium Spurs.
