### ISSUE TITLE
Gilneas quest 'The Evil Made Me Do It' has a long respawn on the quest item

### ISSUE THREAD

**Issue by Reiiama** [slowtorta/turtlewow-bug-tracker#4655]
**Please, provide a clear description what the bug is:** The item 'On the Powers of Blood' needed for the quest 'The Evil Made Me Do It' has a long respawn time, about 5 minutes, within the instance itself. There is no reason to have a respawn this long for an item inside an instance.

**Steps to reproduce the behavior with as much detail as possible:**

1. Finish Gilneas up to Greymane Tower's Mr. & Mrs. Harlow boss battle
2. Loot 'On the Powers of Blood' from the table
3. Realize the book has a 5 minute respawn, meaning a player may have to sit in the instance for 20 minutes waiting for the book
4. Try not to cry.
5. Cry a lot.

**IDs of affected creatures, items, quests or spells with a link to the relevant page:**
Not available

**Expected behavior. Describe how it should work:** The book should respawn instantly.

**Comment by Muigin** [comment]
All unique gameobjects that are quest items have had their respawn times drastically reduced as of a recent update.
