### ISSUE TITLE
Finkle's Lava Dredger Bugged Stat 

### ISSUE THREAD

**Issue by yraelyiwe** [slowtorta/turtlewow-bug-tracker#4656]
**Please, provide a clear description what the bug is:**
Finkle's Lava Dredger Bugged Stat , The ap Atk for drood in the weapon is on use , so we dont receive the stat and the mp5 is on hit 

**IDs of affected creatures, items, quests or spells with a link to the relevant page:**

NPC: https://database.turtle-wow.org/?npc=
Item: https://database.turtle-wow.org/?item=
Quest: https://database.turtle-wow.org/?quest=
Spell: https://database.turtle-wow.org/?spell=
Object: https://database.turtle-wow.org/?object=

**Expected behavior. Describe how it should work:**

**Comment by Muigin** [comment]
This has been fixed as of a recent update.
