### ISSUE TITLE
The Key for the Opper Blackrock Spire have a problem

### ISSUE THREAD

**Issue by Silentest** [slowtorta/turtlewow-bug-tracker#4661]
**Please, provide a clear description what the bug is:**

**Steps to reproduce the behavior with as much detail as possible:**

1.The Key for the Opper Blackrock Spire have a problem
2. I completed the task, got the quest item, and now go back to Blackrock Spire to hand in the task, the NPC did not provide the task completion button, I abandoned the task, and destroyed the quest item plan to re-pick up, and the NPC does not provide the task pickup,The GM said let me to Del WDB ,i done but the same problem.

**IDs of affected creatures, items, quests or spells with a link to the relevant page:**

NPC: https://database.turtle-wow.org/?npc=
Item: https://database.turtle-wow.org/?item=
Quest: https://database.turtle-wow.org/?quest=
Spell: https://database.turtle-wow.org/?spell=
Object: https://database.turtle-wow.org/?object=

**Expected behavior. Describe how it should work:**

**Comment by twowTurtReynolds** [comment]
![image](https://github.com/slowtorta/turtlewow-bug-tracker/assets/151180101/5f000779-54b8-4240-8030-c4058ee8d8ab)
Works fine. Here I am arriving back with the gemstones in hand.

**Comment by twowTurtReynolds** [comment]
Please see https://github.com/slowtorta/turtlewow-bug-tracker/issues/6042
