### ISSUE TITLE
High Elf Animation/Sound problem

### ISSUE THREAD

**Issue by MagnaTronz** [slowtorta/turtlewow-bug-tracker#4669]
**Please, provide a clear description what the bug is:**
My high elf character, does often not show the animation and sound of spells, he just stand still and the spell goes off after the cast time.
**Steps to reproduce the behavior with as much detail as possible:**

1.Casting frostbolt for example, he will just stand there and the spell goes off after cast time.
2. 
3. 

**IDs of affected creatures, items, quests or spells with a link to the relevant page:**

NPC: https://database.turtle-wow.org/?npc=
Item: https://database.turtle-wow.org/?item=
Quest: https://database.turtle-wow.org/?quest=
Spell: https://database.turtle-wow.org/?spell=
Object: https://database.turtle-wow.org/?object=

**Expected behavior. Describe how it should work:**
Use the animation and sounds as normal

**Comment by twowTurtReynolds** [comment]
![image](https://github.com/slowtorta/turtlewow-bug-tracker/assets/151180101/3a1810b7-8062-472d-9260-544325eb6d28)
Works fine.
