### ISSUE TITLE
Reputation/daily issues with Revantusk Trolls

### ISSUE THREAD

**Issue by Dalzedur** [slowtorta/turtlewow-bug-tracker#4670]
**Please, provide a clear description what the bug is:**
After the patch/update, there seems to be an issue with reputation gain with Revantusk trolls.
Firstly, their daily quests don't manifest, so you can't get the quests. Taking the doll to Sen'jin village quest did work but I wasn't paying attention then to see if it actually gave reputation or not, but that isn't a daily afaik. My character is currently at 2800/3000 reputation, 200 short of reaching friendly with them. I turned in 60 wool cloth for its reputation gain to push it over to the friendly side, and I only received 650xp and no reputation for doing so.

Secondly, I did the children's week quest thoroughly, turned in the Warden of the Horde quest and received 0 reputation. I am under the impression that it should give a faction wide reputation reward. Can't take a look at turtlewow database because it is shut down to not spoil the update contents, so I can't confirm if that is working as intended. Classic WoWhead, however, says that warden of the horde should give 200 horde reputation.

Do any faction-wide reputation gains (You gained 50 reputation with horde etc) work right now? Is Revantusk troll reputation somehow breaking it? Cloth quartermaster turn-ins should give reputation, so it not giving to Revantusk trolls seems very fishy to me.

What about quests that have a minimum revantusk troll reputation to appear? Are there any? Are they broken? Is there some fault in the revantusk reputation object(?) that returns errors whenever something tries to call it to increase the reputation?

**Steps to reproduce the behavior with as much detail as possible:**
1. Do something that should give either revantusk troll or horde reputation. See that it does not.

**IDs of affected creatures, items, quests or spells with a link to the relevant page:**
Turtle WoW's Database is down for two weeks, can't link anything because I can't see their IDs.

**Expected behavior. Describe how it should work:**
The dailies should be there up for grabs. The reputation gain for the faction should be made to work as intended.

**Comment by 008512365** [comment]
Same problem.
Revantusk starting quests are bugged making you unable to reach friendly.
After the introductory quests (all available) you are stuck att 2800/3000 friendly.
If you hand in one cloth quest you are at 2950/3000 and after that you cannot hand in any more. Meaning stuck at 2950/3000 without any way to progress. 
At least I got 150 for the cloth quest, but after that I am stuck.

**Comment by norstromo** [comment]
have the same problem, and it seems that it will be a reason to drop turtle wow gaming. Good luck guys. Wanted to make some donation to developers amd now i'm so happy that i did not.

**Comment by luskanek** [comment]
Will be fixed in next update.
