### ISSUE TITLE
Worgen Hunter Grips do NOT increase range crit chance despite the tooltip saying they do

### ISSUE THREAD

**Issue by daniel-hauke** [slowtorta/turtlewow-bug-tracker#4673]
**Please, provide a clear description what the bug is:**
The "Worgen Hunter Grips" (new item) are supposed to increase ranged crit chance, but my interface addon betterstats does not show the crit increase. The gloves seem to be buggy.

**Steps to reproduce the behavior with as much detail as possible:**

1. Install BetterCharacterStats Addon active (https://github.com/yutsuku/BetterCharacterStats)
2. Equip "Worgen Hunter Grips"

**IDs of affected creatures, items, quests or spells with a link to the relevant page:**

NPC: https://database.turtle-wow.org/?npc=
Item: https://database.turtle-wow.org/?item=
Quest: https://database.turtle-wow.org/?quest=
Spell: https://database.turtle-wow.org/?spell=
Object: https://database.turtle-wow.org/?object=

**Expected behavior. Describe how it should work:**
The "Worgen Hunter Grips" should increase range crit chance by 1%.

**Comment by cyaohiri** [comment]
You can't rely on the addon to calculate this correctly because this is a custom item that might not be properly parsed by the addon. The way to check if it actually works is by attacking a target dummy, though that might take a while.

You can report the visual issue here: https://github.com/Lexiebean/BetterCharacterStats

**Comment by Muigin** [comment]
This is an issue with a third party addon that DOES NOT pull the data from the server, but relies on manual programming of specific items and spells into the addon.

The item itself is working as intended.
