### ISSUE TITLE
Herbs being obstructed by terrain

### ISSUE THREAD

**Issue by PapaChinoDev** [slowtorta/turtlewow-bug-tracker#4674]
**Please, provide a clear description what the bug is:**
Various instances of herbalism profession herbs marked on the minimap being inaccessible

**Steps to reproduce the behavior with as much detail as possible:**

1. Cast find herbs and go to a spot on the minimap of where an herb should be

**IDs of affected creatures, items, quests or spells with a link to the relevant page:**

NPC: https://database.turtle-wow.org/?npc=
Item: https://database.turtle-wow.org/?item=
Quest: https://database.turtle-wow.org/?quest=
Spell: https://database.turtle-wow.org/?spell=
Object: https://database.turtle-wow.org/?object=

**Expected behavior. Describe how it should work:**
Herbs not being obstructed inside or under terrain

**Comment by cyaohiri** [comment]
Post their locations on the minimap or the map so they can be found and fixed, or even better, post the coordinates.

**Comment by Muigin** [comment]
Please report these nodes when you find them to a GM in-game that they may fix the node spawns in real time.
