### ISSUE TITLE
Ornate bloodstone dagger does not proc ever.

### ISSUE THREAD

**Issue by Parabullet** [slowtorta/turtlewow-bug-tracker#4675]
**Please, provide a clear description what the bug is:**
The new knife from bloodring "Ornate Bloodstone Dagger" with the equip effect that is "Your landing damaging spells have a chance on sacrificing 250 of your health and dealing 250 Fire damage." never occurs.

I'm a shaman elemental build and tested doing 500k damage on a training dummy with "Lightning bolt (rank 1)" with the knife equipped with TW threatmeter 1.2.3 installed to log the damage sources and never once the proc occurred, this cant be right.

**Steps to reproduce the behavior with as much detail as possible:**

1.Equip the ornate bloodstone dagger
2.Keep casting spells on enemy mobs/training dummy
3.Wait for the proc (repeat step 2)

**IDs of affected creatures, items, quests or spells with a link to the relevant page:**
As of currently 10/10/2023 the database is closed and i cant link the weapon.

**Expected behavior. Describe how it should work:**
The expected behavior its to proc, even if the chances are extremely low it should occur once or twice for that amount of hits.

**Comment by Galpala** [comment]
I also have the dagger on my druid. It doesn't work on my spells but it does hurt me for 505 dmg when I shapeshift.

**Comment by OonaFae** [comment]
Yes, this weapon is currently bugged, there is an additional issue opened here.
https://github.com/slowtorta/turtlewow-bug-tracker/issues/4504
