### ISSUE TITLE
Escape artist does not work on hollow web spiders in hollow web cemetary

### ISSUE THREAD

**Issue by Stevealandt** [slowtorta/turtlewow-bug-tracker#4676]
**Please, provide a clear description what the bug is:**
Escape artist does not work on hollow web spiders in hollow web cemetary
**Steps to reproduce the behavior with as much detail as possible:**

1.Go to hollow web cemetary, gilneas with a gnome
2.  Get webbed by a Hollow web spider
3. Use escape artist
Result: escape artist does not work

**IDs of affected creatures, items, quests or spells with a link to the relevant page:**

NPC: https://database.turtle-wow.org/?npc=
Item: https://database.turtle-wow.org/?item=
Quest: https://database.turtle-wow.org/?quest=
Spell: https://database.turtle-wow.org/?spell=
Object: https://database.turtle-wow.org/?object=

**Expected behavior. Describe how it should work:**
escape artist works and i am free from the web

**Comment by cyaohiri** [comment]
Same issue as #2029.

**Comment by Muigin** [comment]
Duplicate issue.
