### ISSUE TITLE
Chromie's Broken Pocket Watch is giving +10 haste% instead of -10% haste

### ISSUE THREAD

**Issue by Destroses5100** [slowtorta/turtlewow-bug-tracker#4679]
**Please, provide a clear description what the bug is:**
According to how the tooltip is written, this item should be giving -10% haste. It is currently giving +10 haste. "Equip: Your direct damaging spells have a 10% chance to reduce your casting speed by 10% for 15 sec." If you are reducing "speed" it will take longer for a cast to come out. If the design intention is correct, and the tooltip is wrong, it should say "time" instead of "speed". If you reduce "speed" you go slower, if you reduce "time" you go faster.

**Steps to reproduce the behavior with as much detail as possible:**

1. Have Chromie's Broken Pocket Watch equipped.
2. Cast direct dmg spells at a target until it procs.
3. Proc reduces cast "time" instead of reducing "speed"

**IDs of affected creatures, items, quests or spells with a link to the relevant page:**

Database is down as of submission, can't find id since its a custom item.

**Expected behavior. Describe how it should work:**

As per the tooltip, it should give -10% haste. If the design is correct, the tooltip should change the word "speed" to "time".
https://i.imgur.com/F8VfEg6.png - I know this isn't definitive proof that I am correct, but i feel Ques, a member of the item dev team would correct me otherwise instead of a memey shhhh emoji to my statement.

**Comment by twowTurtReynolds** [comment]
This has been given a stopgap fix of removing the hit with spirit, until it can be properly fixed with 1.17.1.
