### ISSUE TITLE
No longer possible to enable or disable addons in character menu and ingame

### ISSUE THREAD

**Issue by ZipCode93** [slowtorta/turtlewow-bug-tracker#468]
**Please, provide a clear description what the bug is:**

I´m using pfUI with few addons that are compactible with it and they are working just fine. But some time recently I have encountered a problem where I can no longer enable or disable any addon. That includes both the character menu and in-game pfUI menu window.
 
**Problem 1: All the addons that I had enabled before this problem occurred I can now only enable or disable by moving the folders in and out of "AddOns" folder when my game is closed and then launch the game.**

**Problem 2: All the addons that I had disabled before the problem occurred I can no longer enable in any way. I tried doing the same thing that I do in Problem 1 case but they still appear disabled when I launch the game again.** 

I don´t think that this is either an outdated addon problem or a pfUI problem because:

- I˙m using the current version of every addon that I have and I even decided to test what happens when I only have one or two addons in my "AddOns" folder (I chose the most recent updated ones). 

- In some cases I removed pfUI from "AddOns" and I tested the situation with default Blizz UI. 

- And then finally, I even tested it by having LFT as the only addon in the game (cause that´s the only addon that I had when I logged in to the client for the very first time). 

Basically, in every single one of these situations, the problem is still there.

**Steps to reproduce the behavior with as much detail as possible:**

![turtlewow1](https://user-images.githubusercontent.com/94743820/142728249-ee5b5c73-5eb5-4e3a-b51f-abf52543bb49.jpg)

![turtlewow2](https://user-images.githubusercontent.com/94743820/142728250-0a5d9ef7-9a96-4840-bbda-0aa69dd5f00b.png)

These are the screenshots of both character menu and in-game settings. No matter which addon I check or uncheck, it will all look exactly like this after logging back or reloading UI.

Here is how my situation looks like right now.

BigWigs was working fine just like all these other addons, but I decided to disable it because I felt I will only need it sometimes later in the game. And then this problem occurred and now I can no longer enable it (I even tried downloading it again but that didn´t work either).

**Expected behavior. Describe how it should work:**

With character menu it is supposed to be working how it always works. Go to "Addons" in the bottom left, check or uncheck and then log back in.

With in-game pfUI menu window you will get a message that UI needs to reload after checking or unchecking and after the reload the changes are supposed to occur.

**Comment by perl1743** [comment]
Sounds like your World of Warcraft\WTF\ folder is marked as read-only

**Comment by ZipCode93** [comment]
I didn´t reply right away cause I wanted to test this a bit. 
Anyways, I tested it both for addons and macros and its all now working nicely now! 

Thank you for your help! I appreciate it! 👍
