### ISSUE TITLE
Cannot connect the server which create roles on the different PC

### ISSUE THREAD

**Issue by gtzsg1987** [slowtorta/turtlewow-bug-tracker#4682]
**Please, provide a clear description what the bug is:**
I am an Asian server player, home and company are different cities, I took time off at home to create a character on the Storm Spirits server on my home computer and played normally. When I return to the company after taking a vacation and log in to my account with another computer, I can see the number of characters created by Storm Spirits in the server list, but I can't connect to the Storm Spirits server to play the characters I created at home, and other servers can connect and create characters normally.
**Steps to reproduce the behavior with as much detail as possible:**

1.
2. 
3. 

**IDs of affected creatures, items, quests or spells with a link to the relevant page:**

NPC: https://database.turtle-wow.org/?npc=
Item: https://database.turtle-wow.org/?item=
Quest: https://database.turtle-wow.org/?quest=
Spell: https://database.turtle-wow.org/?spell=
Object: https://database.turtle-wow.org/?object=

**Expected behavior. Describe how it should work:**

**Comment by slowtorta** [comment]
The server was probably under the maintenance :)
