### ISSUE TITLE
Veil of Nightmare - Not enchantable

### ISSUE THREAD

**Issue by beanwiener** [slowtorta/turtlewow-bug-tracker#4684]
Emerald Sanctum Loot - Veil of Nightmare is not enchantable with lesser agility. Gives an error message  "Must have a Cloth Equipped" to enchanters.

**Comment by edguix** [comment]
Yes, having the same issue. I tried getting +3 Agility to cloak, and my enchanter said he could not do it. I  tried with two different enchanters. First one was cross-faction (I am horde troll, he was alliance human). Today this morning I tried with a fellow hordie and had the same result.

**Comment by twowTurtReynolds** [comment]
![image](https://github.com/slowtorta/turtlewow-bug-tracker/assets/151180101/86817bc1-2adc-4e9c-872d-0dc8976d4186)
Looks to be fixed in patch-5.mpq
