### ISSUE TITLE
Band of Infinite Possibilities

### ISSUE THREAD

**Issue by selax1** [slowtorta/turtlewow-bug-tracker#4687]
The ring Band of Infinite Possibilities has the wording "Increases damage and healing done by magical spells and effects by up to 1 to 35". All other spellpower items just say "up to X". Assuming this isn't a typo, this seems like it should mean it's a random damage modifier each time you use a spell affected by spellpower, but it doesn't work like that. I've tested it dozens of times on a paladin and it always provides the same damage ticks for SoR or Consecrate. If this is intended, what is the point of the wording on the ring? Why is it worded like that? Also, I haven't tested this extensively yet, but it doesn't seem to provide 35 spell damage. It's more in the range of 20ish. Is this intended also?

**Steps to reproduce the behavior with as much detail as possible:**

1. Equip the ring. Use a spell damage effect. It's always the same flat damage increase (within 1-2 damage on SoR or Consecrate) 
2.  It's not a 35 spellpower increase
3. 

**IDs of affected creatures, items, quests or spells with a link to the relevant page:**

(database not open again yet. Can't link item but it drops in Black Morass)
Item: https://database.turtle-wow.org/?item=

**Expected behavior. Describe how it should work:**
Unsure if expected or intended behavior. Why is it worded the way it is? Seems like it should either be a 35 damage spellpower ring or it should be some sort of random effect each time, but it's a flat spellpower increase that's less than 35. I'm confused. 

Thanks!

**Comment by twowTurtReynolds** [comment]
This was changed to a working spell ID:
https://database.turtle-wow.org/?item=61032
