### ISSUE TITLE
TOKENS is missing！！！！

### ISSUE THREAD

**Issue by wolfcbimy** [slowtorta/turtlewow-bug-tracker#4688]
**Please, provide a clear description what the bug is:**

**Steps to reproduce the behavior with as much detail as possible:**

1.I donated a total of 2 times and received 234 TOKENS and 94 TOKENS respectively, for a total of 328 TOKENS.
2.my HC character died, the 200 TOKENS I spent did not return to my account, but disappeared.I created another HC character and 
   died again, but the 100 TOKENS I used disappeared again. Now my account only has 28 TOKENS.
3.I don't know what causes this.I hope this can be resolved.

**IDs of affected creatures, items, quests or spells with a link to the relevant page:**

NPC: https://database.turtle-wow.org/?npc=
Item: https://database.turtle-wow.org/?item=
Quest: https://database.turtle-wow.org/?quest=
Spell: https://database.turtle-wow.org/?spell=
Object: https://database.turtle-wow.org/?object=

**Expected behavior. Describe how it should work:**

**Comment by cyaohiri** [comment]
Create an in-game ticket. A GM should be able to resolve this.
