### ISSUE TITLE
Righteous Fury buff tooltip does not show value increased by talents

### ISSUE THREAD

**Issue by Tinyfin-github** [slowtorta/turtlewow-bug-tracker#469]
Righteous Fury buff tooltip does not show value increased by talents

https://database.turtle-wow.org/?spell=25780 Righteous Fury
https://database.turtle-wow.org/?spell=20470 Improved Righteous Fury

![WoW_v89Sfp9hsp](https://user-images.githubusercontent.com/83077166/142748181-f9c166dd-2a85-4576-a286-375e1a92dab4.png)

The tooltip from the skill shows the correct values:

![image](https://user-images.githubusercontent.com/83077166/142748208-076afc63-b318-42bd-a6c2-4016c665d361.png)

**Comment by Tobbsu** [comment]
The most Improved buff don't show the right info make it hard to tell if is Improved or not.

**Comment by Velite12** [comment]
Buff tooltips don't show adjusted values, only the base. That is blizzlike. Misleading yes, but blizzlike. You go on classic and the buff tooltips also only show the base value.

**Comment by jaywalker15262** [comment]
Velite that is usually not applied to tooltip text of skills in your textbar but the aura tooltip.

**Comment by jaywalker15262** [comment]
Improved PW: fortitude woulda ctually show the new values. Just not on the aura tooltip.
