### ISSUE TITLE
The zeppelin from Undercity to Stranglethron is disappearing again

### ISSUE THREAD

**Issue by Slimthegrim** [slowtorta/turtlewow-bug-tracker#4691]
**Please, provide a clear description what the bug is:**
The zepp comes and goes from the UC tower without being visible.

**Steps to reproduce the behavior with as much detail as possible:**

1. Updated to 1.17, be a goblin, having a good time.
2. Watch another character walk onto air and be swept away by invisible zepp.
3. Note having deleted wdb multiple times since patch.
4. Take picture:
![image](https://github.com/slowtorta/turtlewow-bug-tracker/assets/110629519/5914e13c-6b33-4a66-8fd7-f2e9c02ecd81)

**IDs of affected creatures, items, quests or spells with a link to the relevant page:**

I don't think you can link to zeppelins from database. DB is locked for patch last I checked too.

**Expected behavior. Describe how it should work:**
Zeppelin should not be invisible? I can jump through invisible zeppelin while others stand in air.

**Comment by twowTurtReynolds** [comment]
This bug did appear before, but it's come back with a vengeance now that turtle uses the multithreading world instancing feature of vmangos. Until this is fixed, there's no real workarounds other than relogging...

**Comment by twowTurtReynolds** [comment]
So yes, thank you and others for the report of these zeppelin issues. 

I'll be closing this thread and all other duplicates, but I've attached these issue to the master issue https://github.com/slowtorta/turtlewow-bug-tracker/issues/5312 affecting not only the zeplins but also NPCs and gathering nodes.
