### ISSUE TITLE
Barrens lay issue

### ISSUE THREAD

**Issue by zoomkaa** [slowtorta/turtlewow-bug-tracker#4693]
**Please, provide a clear description what the bug is:**
In the Barrens location, there is a transition from one layer to another, crossing which objects from the previous layer disappear, as well as mobs and even exit from the battle
**Steps to reproduce the behavior with as much detail as possible:**

1. Open video https://youtu.be/yxbQri0tPC4
2. Watch the video
3. Fix it

**IDs of affected creatures, items, quests or spells with a link to the relevant page:**

NPC: https://database.turtle-wow.org/?npc=
Item: https://database.turtle-wow.org/?item=
Quest: https://database.turtle-wow.org/?quest=
Spell: https://database.turtle-wow.org/?spell=
Object: https://database.turtle-wow.org/?object=

**Expected behavior. Describe how it should work:**
when moving from one layer to another, items and mobs should not disappear

**Comment by twowTurtReynolds** [comment]
https://github.com/slowtorta/turtlewow-bug-tracker/issues/5312
