### ISSUE TITLE
Bugged iron deposit in Arathi Highlands

### ISSUE THREAD

**Issue by VelikiyVoinSveta** [slowtorta/turtlewow-bug-tracker#4696]
**Please, provide a clear description what the bug is:**

**Steps to reproduce the behavior with as much detail as possible:**

1. Bugged iron deposit in Arathi Highlands that appeared under the textures at 31.6, 17,6 
![WoWScrnShot_101123_203719](https://github.com/slowtorta/turtlewow-bug-tracker/assets/147649730/fcfde52c-e793-41ff-bd5e-ff5ee81c54d8)

**Expected behavior. Describe how it should work:**

**Comment by Muigin** [comment]
Please report this via in-game ticket when you see it so a GM can fix the bugged node in real-time.
