### ISSUE TITLE
Help me use the glyph of transformation but it has no effect.

### ISSUE THREAD

**Issue by xhz168898** [slowtorta/turtlewow-bug-tracker#4697]
**Please, provide a clear description what the bug is:**

**Steps to reproduce the behavior with as much detail as possible:**

1.After the version update, my Glyph of Druid Transformation cannot be used. ID: xhz168898
2. please help me solve it
3. id：xhz168898  druid niudaren

**IDs of affected creatures, items, quests or spells with a link to the relevant page:**

NPC: https://database.turtle-wow.org/?npc=
Item: https://database.turtle-wow.org/?item=
Quest: https://database.turtle-wow.org/?quest=
Spell: https://database.turtle-wow.org/?spell=
Object: https://database.turtle-wow.org/?object=

**Expected behavior. Describe how it should work:**

**Comment by luskanek** [comment]
Did you try deleting your WDB folder and restarting the game afterwards?

**Comment by slowtorta** [comment]
Delete your WDB folder while you clien is completely closed.
Right click on your glyhp items to learn them, new spells will appear in your spellbook.
Ensure that your client isn't using any modifications.
