### ISSUE TITLE
Antler's Guidance quest bug question

### ISSUE THREAD

**Issue by Croziff** [slowtorta/turtlewow-bug-tracker#4698]
**Please, provide a clear description what the bug is:**
Hello, I did the "Antler's Guidance" Turtle custom quest for Horde side, but I didn't get any reward or any follow-up. I asked the Turtle WOW discord server if this is normal and the community manager told me to contact a GM. The GM didn't tell me if this is a bug or not, but they told me to submit a ticket here.

So, I picked up the  quest Antler's Guidance in Moonglade. After searching for 2 hours I found the objective NPC. I talked to her and pressed the button to complete the quest. Then I didn't get any XP, no items and no follow-up quest.

**Steps to reproduce the behavior with as much detail as possible:**

1. I accepted the quest.
2. I found the appropriate NPC which was the quest objective.
3. I completed the quest.
4. I didn't get anything nor a follow-up quest.

**IDs of affected creatures, items, quests or spells with a link to the relevant page:**

Database is closed and I can't see it at all. All I have is names.

NPC: Ilyara Skyvault
Quest: Antler's Guidance 

**Expected behavior. Describe how it should work:**
I don't know how it should work, that's why I asked in chat but got told off by the community manager.

**Comment by slowtorta** [comment]
This is a deprecated quest that is no longer available.
