### ISSUE TITLE
Deathmist Wraps Not Registering Set

### ISSUE THREAD

**Issue by Raskolnik23** [slowtorta/turtlewow-bug-tracker#4699]
Deathmist Wraps (Warlock Dungeon Set 2 gloves) don't appear to be correctly applying all of the stats. Gloves currently appear to be applying 20 Stamina and 14 Intellect, while also not registering as being part of the set when equipped (have Deathmist Wraps and Deathmist Bracers equipped, tooltip shows 1/8 rainment w/ only Bracers highlighted)

Have equipped & re-equipped multiple times to confirm oddity, deleting WDB didn't change.

Item: https://classicdb.ch/?item=22077

Needs set ID registering updated, and possible stat # corrections.

**Comment by twowTurtReynolds** [comment]
![image](https://github.com/slowtorta/turtlewow-bug-tracker/assets/151180101/aa9a1c33-9658-4979-94fc-c72783de7366)
Works fine.

It sounds like you were confused by not clearing WDB, and also by not knowing of the xmog visual set display bug.
