### ISSUE TITLE
Stormwind Plane to EPL Bugged Destination

### ISSUE THREAD

**Issue by Zebouski** [slowtorta/turtlewow-bug-tracker#47]
By opening this Issue, I admit to having done the pertinent research using sources from Vanilla (preferably) or Classic. I also understand that sources from other private servers are not acceptable.

**Current behavior**: Take the plane from stormwind, and end up falling through the ground underneath dalaran. Slowfall on, but no plane. Game will teleport you to the southshore graveyard with half health.

**Expected behavior**: Take the plane from stormwind, and end up flying down to southwest EPL

**Proofs**:
https://media.discordapp.net/attachments/595993787692613643/852961708796411944/unknown.png?width=1200&height=666
Happened 3 times to me this week, out of 5 attempts (the other two worked just fine). I saw it happen to another raider too, right after me. The majority of our raid (like 30 other people) were unaffected and made it to the correct destination just fine.

**Steps to reproduce**:

1. Install lazypig addon and have it automatically click through gossip
2. Open the plane dialogue 
3. For good measure, spam click the fly option
4. End up falling down below dalaran

**Comment by Zebouski** [comment]
Happened again today
https://media.discordapp.net/attachments/595993787692613643/855844471907811358/unknown.png
The teleporter worked properly about 5 times before this. It's just inconsistent.

**Comment by Zebouski** [comment]
I've been able to consistently replicate it by spamming the right click on the guy. The game will freeze for 2 seconds when above EPL, then teleport again. Likely need to find a way to make only 1 of these teleports activate with a 5 second cooldown or something

**Comment by Nolin7777** [comment]
Will be fixed in next client patch.
