### ISSUE TITLE
Thorium spurs not giving bonus

### ISSUE THREAD

**Issue by Shakesthesham** [slowtorta/turtlewow-bug-tracker#4700]
**Please, provide a clear description what the bug is:**

**Steps to reproduce the behavior with as much detail as possible:**

1.I've used monkey speed to test the bonus of thorium spurs, compared to mithril spurs, and found they aren't giving any riding speed bonus at all. 
2. 
3. 

**IDs of affected creatures, items, quests or spells with a link to the relevant page:**

NPC: https://database.turtle-wow.org/?npc=
Item: https://database.turtle-wow.org/?item=
Quest: https://database.turtle-wow.org/?quest=
Spell: https://database.turtle-wow.org/?spell=
Object: https://database.turtle-wow.org/?object=

**Expected behavior. Describe how it should work:**

**Comment by Kirchlive** [comment]
Requst already set
https://github.com/slowtorta/turtlewow-bug-tracker/issues/4654
