### ISSUE TITLE
Rogue poison quest (horde)

### ISSUE THREAD

**Issue by manowarfare** [slowtorta/turtlewow-bug-tracker#4701]
Was doing the rogue quest called: Deep Cover. With an accident i deleted the flare needed for the quest.
Afterwards i tried to re-take the quest, but the quest giver would not have the quest anymore.
Now I am completely stuck without the poisons for my rogue, FML...
https://www.wowhead.com/classic/quest=2458/deep-cover

**Comment by ratkosrb** [comment]
https://github.com/slowtorta/turtlewow-bug-tracker/assets/35845488/b96346d5-053b-45dd-870e-4b2f15c79eab

I can't reproduce the issue. I can retake the quest after abandoning it. Try asking a GM to add the quest to you.

**Comment by Muigin** [comment]
Unable to reproduce.
