### ISSUE TITLE
Ornate Bloodstone Dagger not proc'ing weapon effect off spell hits

### ISSUE THREAD

**Issue by bebraveorbeslave** [slowtorta/turtlewow-bug-tracker#4703]
The Ornate Bloodstone Dagger is not proc'ing it's weapon effect from successful spell hits.

Please fix <3

I cannot link it since the database is currently offline.

**Comment by OonaFae** [comment]
There are two other issues open describing this currently if you would like to post in them as well:
https://github.com/slowtorta/turtlewow-bug-tracker/issues/4504
https://github.com/slowtorta/turtlewow-bug-tracker/issues/4675

**Comment by ratkosrb** [comment]
It will be fixed in the next update, but you wont be able to see the damage in combat log until the next client patch, as it requires making a new spell.
