### ISSUE TITLE
Invocation of shattering will not apply to helmet

### ISSUE THREAD

**Issue by reynolds11234** [slowtorta/turtlewow-bug-tracker#4705]
**Please, provide a clear description what the bug is:**
invocation of shattering will not apply to darkflame helm
**Steps to reproduce the behavior with as much detail as possible:**

1.
2. 
3. 

**IDs of affected creatures, items, quests or spells with a link to the relevant page:**

NPC: https://database.turtle-wow.org/?npc=
Item: https://database.turtle-wow.org/?item=
Quest: https://database.turtle-wow.org/?quest=
Spell: https://database.turtle-wow.org/?spell=
Object: https://database.turtle-wow.org/?object=

**Expected behavior. Describe how it should work:**

**Comment by ratkosrb** [comment]
It will be fixed server side after the next update, but client will still not allow you to use the invocation unless you download a [patch](https://www.mediafire.com/file/uk27h9pyzbz31gy/patch-Z.mpq/file) to correct the bad spell targeting data client side.
