### ISSUE TITLE
[Quest][Item]Nightmare Effigy for quest Into the Dream II continuing to drop after completion

### ISSUE THREAD

**Issue by CasualNerdity** [slowtorta/turtlewow-bug-tracker#4706]
**Please, provide a clear description what the bug is:**
Vilemusk satyrs in Hyjal continue to drop Nightmare Effigy quest items for the quest "Into the Dream II"
**Steps to reproduce the behavior with as much detail as possible:**

1. Start and complete the Hyjal quest "Into the Dream II" from Ralathius
2. Kill Vilemusk satyrs in Hyjal
3. Nightmare Effigy continues to drop

![Capture4](https://github.com/slowtorta/turtlewow-bug-tracker/assets/79479148/cf7702ae-9970-40a2-9ebe-d63b3bb18fdf)
**IDs of affected creatures, items, quests or spells with a link to the relevant page:**
Database currently set to require login, cannot access npc/quest/item IDs

**Expected behavior. Describe how it should work:**
Nightmare Effigy should stop dropping after players complete "Into the Dream II."

**Comment by twowTurtReynolds** [comment]
![image](https://github.com/slowtorta/turtlewow-bug-tracker/assets/151180101/35d9c040-14c5-41fc-8b2a-14d517cd92f4)
Unable to replicate. I killed all the satyrs in the area around 3 times, and got this much loot. The effigies did not incorrectly drop before or after the quest.
