### ISSUE TITLE
Furen's note

### ISSUE THREAD

**Issue by Huntshorde** [slowtorta/turtlewow-bug-tracker#4708]
**Please, provide a clear description what the bug is:**

**Steps to reproduce the behavior with as much detail as possible:**

1.Alliance Warrior quest Fire Harden Mail completed
2. Open a chain quest for 3 additional quests to complete.
3.  I completed the Stormwind quest by getting the burning rocks from Duskwood and returning, got my quest reward.
4. Then went to Iron Forge to do quest "Klockmort Spannerspan" but the Furens Note was removed from my inventory as I handed it in to the first NPC in Stormwind.

**IDs of affected creatures, items, quests or spells with a link to the relevant page:**

NPC: https://database.turtle-wow.org/?npc=Klockmort Spannerspan
Item: https://database.turtle-wow.org/?item=Furen's Note
Quest: https://database.turtle-wow.org/?quest=Fire Harden Mail chain
Spell: https://database.turtle-wow.org/?spell= N/A
Object: https://database.turtle-wow.org/?object= Furen's Note

**Expected behavior. Describe how it should work:**
Note to remain inside inventory to hand into Stormwind, Ironforge and Darnassus NPCs

**Comment by Huntshorde** [comment]
![Uploading wow.exe Screenshot 2023.10.12 - 14.31.47.48.png…]()

**Comment by Huntshorde** [comment]
![Uploading wow.exe Screenshot 2023.10.12 - 14.31.59.62.png…]()

**Comment by Huntshorde** [comment]
A very kind and helpful Darucil spawn a Furen's Notes for me into my bag. I handed this note to the gnome NPC Klockmort Spannerspan, who then took the note away from my bags and gave me a quest. However I still need that note as its also got to be taken to Mathiel in darnassus. Its a 3 way quest. Once you complete Fire Hardened Mail quest, Furen gives you his Notes and needs you to take them to Stormwind, Ironforge and Darnassus, but as it appears as soon as I hand in the note to one of the three, the note is taken away and then you can no longer finish the other two quests. Darucil was very kind and gave me another Note so that I can carry onward to Darnassus to speak with Methiel

**Comment by Muigin** [comment]
After completing Fire Hardened Mail (Quest 1701), 4 quests which each give a copy of Furen's Notes unlock on Furen Longbeard. The item is unique, however, which means you will have to take 1 quest at a time to the 3 NPCs, then come back to Furen to pursue the other quests. Each quest will provide you a copy, nonetheless.

Working as intended.
