### ISSUE TITLE
Quest [The Stolen Note] ID mistake. Is quest working?

### ISSUE THREAD

**Issue by Bravian-XP** [slowtorta/turtlewow-bug-tracker#4709]
I found the quest [The Stolen Note] in Felwood. But it shows up for everyone as warlock class quest [The Stolen Tome]. That is when linking and in the pfUI interface.

This wouldn't be a problem if I hadn't been trying to do it for an hour following the description. Maybe this ID mistake could be the reason for the quest not working?

![World of Warcraft_231012031730](https://github.com/slowtorta/turtlewow-bug-tracker/assets/146672371/4bab276c-ce3d-43d9-ba92-04c2005ceea5)

**Comment by Muigin** [comment]
This appears to be a bug with one of your addons. These are two different quests. Please delete your WDB and ensure that you aren't using a questing addon that "auto-corrects".

The quest iteself is working as intended.
