### ISSUE TITLE
Quest The Attack is buggy

### ISSUE THREAD

**Issue by Tinyfin-github** [slowtorta/turtlewow-bug-tracker#471]
•  Overhear Lescovar and Marzon's Conversation completes earlier, It should complete when you overhear the conversation.
•  Tyrons Spybot should not transform back in front of Lescovar, he should be out of sight first.
•  Priestess Tyriona should not be standing there, shes actually Tyron's spybot.

https://database.turtle-wow.org/?quest=434 The Attack!
https://database.turtle-wow.org/?npc=7779  Priestess Tyriona

![image](https://user-images.githubusercontent.com/83077166/142775736-a4b698fd-96d4-4781-8a21-cd283ea45040.png)

![image](https://user-images.githubusercontent.com/83077166/142775798-5703f4f3-85ff-4c1b-9156-a3bcfa1f949f.png)

Source for correct behavior: https://www.youtube.com/watch?v=BK7ynRCp4KM

**Comment by redmagejoe** [comment]
Add to this that the name should change along with the display ID. It still reads "Tyrion's Spybot" when it should read "Priestess Tyriona".

**Comment by slowtorta** [comment]
Possibly fixed on a previous update.
