### ISSUE TITLE
Item: https://database.turtle-wow.org/?item=

### ISSUE THREAD

**Issue by Bobojib** [slowtorta/turtlewow-bug-tracker#4710]
**Please, provide a clear description what the bug is:**

**Steps to reproduce the behavior with as much detail as possible:**

1.The Item SHOULDERGUARDS OF THE DEFILER seems not improve enough chances (2% as the item describetion) to hit.  
2. I want to know how many chances it exactly improves to hit?
3. Thank you!

**IDs of affected creatures, items, quests or spells with a link to the relevant page:**

NPC: https://database.turtle-wow.org/?npc=
Item: https://database.turtle-wow.org/?item=
Quest: https://database.turtle-wow.org/?quest=
Spell: https://database.turtle-wow.org/?spell=
Object: https://database.turtle-wow.org/?object=

**Expected behavior. Describe how it should work:**

**Comment by Herdon** [comment]
Mate how hard is it to follow the template provided to you for reporting a bug? What is this even?

**Comment by Bobojib** [comment]
The new item from new dungeon of Karazan which name is Shoulderguards of the Defiler may not improve enough chance to hit. It said that this item should improve 2% chance to hit. But I think it is lesser.
