### ISSUE TITLE
Gnomish Mind Control Cap

### ISSUE THREAD

**Issue by welpenhund** [slowtorta/turtlewow-bug-tracker#4711]
**Please, provide a clear description what the bug is:**
On Classic and also in Vanilla when you had mind controlled your opponent they would cast abilitys, buff you, cast spells on the enemy (related to their class, so for example a shadow priest casted shadow spells but a holy priest smite etc...)
On T-wow the mind control effect only functions like a brainless pet that autohits (no matter which class you mind control)

**Steps to reproduce the behavior with as much detail as possible:**

1. Wear [Gnomish Mind Control Cap]
2.  Mind control an opponent.
3. Make them attack something.

**IDs of affected creatures, items, quests or spells with a link to the relevant page:**

NPC: https://database.turtle-wow.org/?npc=
Item: https://database.turtle-wow.org/?item=10726
Quest: https://database.turtle-wow.org/?quest=
Spell: https://database.turtle-wow.org/?spell=
Object: https://database.turtle-wow.org/?object=

**Expected behavior. Describe how it should work:**
The mind controlled target should cast spells/abilitys on you (like buffs) and damaging spells/abilitys on the target you make them attack.
Example 1: https://www.youtube.com/watch?v=T-7oB-UVfE8
Example 2: https://www.youtube.com/watch?v=j20aDN5zyew

> Is not like Priest mind control, you cannot use it to throw people off cliffs, zepplins, or into lava.
> 
> It turns the target into your pet for 20s, or turns you into their pet for 20s.  So far the backfire rate is pretty low, not worse than 1 in 4 I think. 
> 
> Even if it backfires against a player, they probably won't know how to take advantage of it, and you're on their side at that point, so worse case you're immune to their attacks for 20s (and immobilized).
> 
> On success (or failure) the one mind controlled target will turn into a pet just like a hunter's pet.  They will run over to the side of the controller.
> 
> You get a pet bar for them that's exactly like a hunter pet bar.  You can click a target and send them to attack it.  You get a small number (3-4?) skills that you can tell them to use but only if the target is an NPC, if it is a player it will automatically cast random spells from their class. 
> 
> Because you only get 20s to look at the abilities and you can only do it once per 30m, it takes a while to learn how to use it.  Generally you just target an enemy mob and hit the pet attack button.  You're free to take other actions while the 20 seconds of effect is running, so you can just "fire and forget".
> 
> You can target a faraway mob as a way of getting rid of the controlled mob for the time it will take them to run back after it wears off.  They follow normal pet pathing to get where you send them.
> 
> I just used this twice against a pair of horde who were camping out corpses today.  MCed the lvl 60 priest and sent him to kill his level 51 friend.

**Comment by welpenhund** [comment]
sorry to ask, but are there any updates? i seen a dev were assigned for it

**Comment by ConcernedTurtler** [comment]
Yeah it would be cool if it actually worked the way it did on classic.

**Comment by ratkosrb** [comment]
Charmed players will cast spells while controlled after the next update.
