### ISSUE TITLE
I can't interact with any NPC in Amani'Alor and i can`t get any quests there aswell

### ISSUE THREAD

**Issue by Amaralein** [slowtorta/turtlewow-bug-tracker#4714]
**Please, provide a clear description what the bug is:**
Hello everyone! =)

I have a problem with the Quest-Chain "A Tusken Affair". I am a Lvl 21 Hunter and I did this chainquests a while ago. I can speak to Deino (NPC Orgrimmar) to open me a portal to Amani'Alor but when I am there, I can only interact with the traders and the wool-guy. There are no quests or daily quest visible or interactable for me. 
Above Deinos Head I can see a blurry exclamation mark but i got no quest from her or anything else only the line, that she opens the portal for me.

I already deleted the files in the WDB folder and startet the client new. But this changed nothing

Is it possible to reset the quest chain or anything that i can also get reputation there and do the daily quests?

With kind regards
Amy

**Comment by luskanek** [comment]
Fixed in the next update.
