### ISSUE TITLE
The cloth reputation turn-in for the Gnomeregan Exiles is bugged 

### ISSUE THREAD

**Issue by Tinyfin-github** [slowtorta/turtlewow-bug-tracker#472]
The cloth reputation turn-in for the Gnomeregan Exiles is bugged 

Bubulo Acerbus does not give A Donation of Silk and A Donation of Runecloth.

https://database.turtle-wow.org/?quest=7809 A Donation of Mageweave
https://database.turtle-wow.org/?quest=7811 A Donation of Runecloth
https://database.turtle-wow.org/?npc=14724 Bubulo Acerbus 

The quests seem to have quest prerequisites as  requirement when they should only have levels because they are not a quest chain
https://database.turtle-wow.org/?quest=7807 A donation of wool opens a A Donation of Silk to https://database.turtle-wow.org/?quest=7803 to Mistina Steelshield  the Ironforge cloth turn.

Source for correct behavior: https://classic.wowhead.com/npc=14724/bubulo-acerbus

![image](https://user-images.githubusercontent.com/83077166/142891435-4f85e56b-5736-4387-85a0-cfeab3be06cf.png)

**Comment by Bennouhan** [comment]
same problem
