### ISSUE TITLE
Revantusk reputation quest bugged

### ISSUE THREAD

**Issue by Alex1128AA** [slowtorta/turtlewow-bug-tracker#4720]
**Please, provide a clear description what the bug is:**

**Steps to reproduce the behavior with as much detail as possible:**

1. No quest can be accepted from Mystic Guay'Jin
2. No way for characters to reach "friendly"
3. 

**IDs of affected creatures, items, quests or spells with a link to the relevant page:**

NPC: https://database.turtle-wow.org/?npc=Mystic Guay'Jin
Item: https://database.turtle-wow.org/?item=
Quest: https://database.turtle-wow.org/?quest=
Spell: https://database.turtle-wow.org/?spell=
Object: https://database.turtle-wow.org/?object=

**Expected behavior. Describe how it should work:**

**Comment by shilei175** [comment]
This has been a problem since the update to version 1.17. The techs haven't been able to fix it and I've given up on the tribe.

**Comment by luskanek** [comment]
Fixed in the next update.
