### ISSUE TITLE
Blue Dragonscale armor's 4-set bonus does not work for Hunter's "spells"

### ISSUE THREAD

**Issue by bebraveorbeslave** [slowtorta/turtlewow-bug-tracker#4722]
The 4-set bonus for the newly revised Blue Dragonscale armor: "Chance of landing a damaging spell to deal 75-85 Arcane damage and increase the target's Arcane damage taken by 10 for 15 sec. This stacks up to 3 times." is not triggered by any hunter ability. This is a mistake, right?

This MUST be an oversight, correct? This set bonus is clearly intended as a kind gesture to us spell hunters, is it not? Am I crazy?!

Pls fix <3

**Comment by ratkosrb** [comment]
The spell description said "spell" not "ranged ability", and those are two completely different spell proc categories, so the spell was only made to proc from regular damage spells, which hunters have none of. It will be corrected at the next update.
