### ISSUE TITLE
Wolfblood 2h sword broken, cant repair it, cant use it but i can sell it at full price

### ISSUE THREAD

**Issue by Triffouillax** [slowtorta/turtlewow-bug-tracker#4723]
**Please, provide a clear description what the bug is:**

**Steps to reproduce the behavior with as much detail as possible:**

1. i used the resurect sickness multiple time
2.  my sword wolfblood get to 0/100 durability
3. i cant repair it but can sell it at full prices despite beeing broken

**IDs of affected creatures, items, quests or spells with a link to the relevant page:**

NPC: https://database.turtle-wow.org/?npc=
Item: https://database.turtle-wow.org/?item=61328
Quest: https://database.turtle-wow.org/?quest=
Spell: https://database.turtle-wow.org/?spell=
Object: https://database.turtle-wow.org/?object=

**Expected behavior. Describe how it should work:**
i sould be able to repair it to use it

**Comment by twowTurtReynolds** [comment]
![image](https://github.com/slowtorta/turtlewow-bug-tracker/assets/151180101/d0b582f4-d3f6-43f7-beb2-f0c56ff6f430)
![image](https://github.com/slowtorta/turtlewow-bug-tracker/assets/151180101/0982dd15-fd83-4786-a500-4eeb156b05ac)
![image](https://github.com/slowtorta/turtlewow-bug-tracker/assets/151180101/7d928ed0-5cad-4470-8be7-e2724973fd7a)
Works fine. Perhaps it was fixed earlier.
