### ISSUE TITLE
Invocation of greater protection 2 MAJOR BUGS

### ISSUE THREAD

**Issue by Chourin** [slowtorta/turtlewow-bug-tracker#4725]
Invocation of greater protection cant be applied on head on shoulders slot.
Also u cant repeat the quest again.

1st Bug
1. Right click the item and try to place it on a leg slot
2. It say "The item is not a valid target"

2nd bug
1. Picture as attached. I cant pick up the other 3 quests but not the quest i just done. it should be repeatable.

![image](https://github.com/slowtorta/turtlewow-bug-tracker/assets/52112645/ec9239ec-709f-409f-80c3-5c644028911c)

**Comment by Tobbsu** [comment]
I agree with you. Did bug report in: ( Quest : Invocation of Greater Protection - Can only be completed ones ) but was closed and this as completed as yesterday with zero explanation leaving me in the dark.

**Comment by ratkosrb** [comment]
This was already fixed internally, wait for the server to be updated! The spell targets however are bugged in the client files, so the game won't let you apply the enchants even after the update, unless you download a [patch](https://www.mediafire.com/file/uk27h9pyzbz31gy/patch-Z.mpq/file) file to correct the spell data.

**Comment by Chourin** [comment]
It is still bugged.
