### ISSUE TITLE
The copy of Crescent Grove cannot be entered, and it is still inaccessible after deleting the "WDB" file

### ISSUE THREAD

**Issue by Hnjrj-Chen** [slowtorta/turtlewow-bug-tracker#4726]
**Please, provide a clear description what the bug is:**

**Steps to reproduce the behavior with as much detail as possible:**

1.When teaming up to enter the game replica Crescent Grove, my game characters cannot enter, and those who leave the party cannot enter alone
2. After exiting the game and deleting the "WDB" folder, I still can't enter the copy
3. My game character ID: yanwangsa
4. This is my first time entering a copy of Crescent Grove that I hadn't entered before

**IDs of affected creatures, items, quests or spells with a link to the relevant page:**

NPC: https://database.turtle-wow.org/?npc=
Item: https://database.turtle-wow.org/?item=
Quest: https://database.turtle-wow.org/?quest=
Spell: https://database.turtle-wow.org/?spell=
Object: https://database.turtle-wow.org/?object=

**Expected behavior. Describe how it should work:**

**Comment by twowTurtReynolds** [comment]
It is likely that you have run into the 5 instances per hour limit.
