### ISSUE TITLE
Bugged Quest: Imbued Stone

### ISSUE THREAD

**Issue by justkasper** [slowtorta/turtlewow-bug-tracker#4727]
I received quest Imbued Stone (which lead to Tel'abim as far as i remember), but when i landed there the quest text changed. New quest leads to Badlands and is called Liquid Stone. When I arrived there NPC won't talk to me and that made me think that i'm not retarded and initially it was other quest.

**Steps to reproduce the behavior with as much detail as possible:**

1. Start making quest for tauren in Hijal.
2. Take ashes from satiers from all over Azeroth, return to this guy.
3. Take new quest called Imbued Stone
4. Fly there.
5. When arrived check your Quest Log, possible this quest would have another description starting from Liquid Stone.

DB is locked atm.

It should be the same quest ^__^

**Comment by twowTurtReynolds** [comment]
![image](https://github.com/slowtorta/turtlewow-bug-tracker/assets/151180101/10b53f10-0fe8-4c77-a21e-da47a7346515)
Unable to replicate, it may have been fixed since I got to check this
