### ISSUE TITLE
Ironforge Artisian Engineer Trainer Missing

### ISSUE THREAD

**Issue by trf03820** [slowtorta/turtlewow-bug-tracker#4728]
**Please, provide a clear description what the bug is:**
Springspindle Fizzlegear is missing. Have checked back multiple days in a row. Have had other players confirm that he is not there. 

**Steps to reproduce the behavior with as much detail as possible:**

1. Visit Iron Forge and missing NPC is not in his location

**IDs of affected creatures, items, quests or spells with a link to the relevant page:**
Cant use this DB tool as it appears to require a login.

**Expected behavior. Describe how it should work:**
NPC should be there to train engineering.

**Comment by luskanek** [comment]
NPC has been moved to Gnomeregan Reclamation Facility. Working as intended.

**Comment by trf03820** [comment]
Thanks Lukas! I thought he was missing as the Ironforge guards still direct you to him at his original location!



Sent from my Verizon, Samsung Galaxy smartphone



-------- Original message --------
From: Lukáš ***@***.***>
Date: 10/14/23 9:48 AM (GMT-05:00)
To: slowtorta/turtlewow-bug-tracker ***@***.***>
Cc: Tanner Frost ***@***.***>, Author ***@***.***>
Subject: Re: [slowtorta/turtlewow-bug-tracker] Ironforge Artisian Engineer Trainer Missing (Issue #4728)

You don't often get email from ***@***.*** Learn why this is important<https://aka.ms/LearnAboutSenderIdentification>

CAUTION: This email originated from outside of the University System. Do not click links or open attachments unless you recognize the sender and know the content is safe.


NPC has been moved to Gnomeregan Reclamation Facility. Working as intended.

**Comment by luskanek** [comment]
The guard's directions will also be fixed in the next maintenance update to reflect the changes.
