### ISSUE TITLE
Ironforge cloth turn is bugged

### ISSUE THREAD

**Issue by Tinyfin-github** [slowtorta/turtlewow-bug-tracker#473]
Ironforge cloth turn is bugged

It only gives a donation of wool

https://database.turtle-wow.org/?quest=7802   a donation of wool
https://database.turtle-wow.org/?quest=7803 A Donation of Silk
https://database.turtle-wow.org/?quest=7804 A Donation of Mageweave
https://database.turtle-wow.org/?quest=7805 A Donation of Runecloth
https://database.turtle-wow.org/?npc=14723 Mistina Steelshield 

![image](https://user-images.githubusercontent.com/83077166/142899376-7ee345d6-b091-497c-98dd-cbb96891d274.png)

**Comment by Matuselah** [comment]
This is still not fixed. I understand that you probably have different priority right now. But this just some silly easy fix quest. Beside fact that is one month old.
