### ISSUE TITLE
[ITEM] "Recipe: Alchemists' Stone" item cannot be destroyed

### ISSUE THREAD

**Issue by valentynpozniakov** [slowtorta/turtlewow-bug-tracker#4733]
**Please, provide a clear description what the bug is:
"Recipe: Alchemists' Stone" item cannot be destroyed**

**Steps to reproduce the behavior with as much detail as possible:**

1. Get "Recipe: Alchemists' Stone" item from Lower Halls of Karazhan
2. Try to destroy it

**Expected behaviour: That item cannot be destroyed error message is displayed**

**Expected behaviour: Confirmation window should be displayed and user should be able to destroy an item**

![image](https://github.com/slowtorta/turtlewow-bug-tracker/assets/67410840/432f6183-0799-4cc3-944b-a1e50398f8fa)

**Comment by ratkosrb** [comment]
It will be fixed in the next update. Remember to delete your WDB folder afterwards.
