### ISSUE TITLE
NPC Haruhiko Yoshino Missing

### ISSUE THREAD

**Issue by Loon15** [slowtorta/turtlewow-bug-tracker#4734]
**Please, provide a clear description what the bug is:**
The NPC isn't located at their camp in Dustwallow Marsh, located on the east coast by Mirefin camps. She has the quest "Searching for Mudrock Meat".

**IDs of affected creatures, items, quests or spells with a link to the relevant page:**
**DB not currently active.** 
NPC: https://database.turtle-wow.org/?npc=
Item: https://database.turtle-wow.org/?item=
Quest: https://database.turtle-wow.org/?quest=
Spell: https://database.turtle-wow.org/?spell=
Object: https://database.turtle-wow.org/?object=

**Expected behavior. Describe how it should work:**
Haruhiko should be at her camp and quest available.
![haruhiko bugged](https://github.com/slowtorta/turtlewow-bug-tracker/assets/96853660/5bc4201f-1cf8-4e85-b17d-6f2f098191ae)

**Comment by ratkosrb** [comment]
It will be fixed in the next update.
