### ISSUE TITLE
Your new weapons dont work and I'm owed 5 tokens

### ISSUE THREAD

**Issue by Kishimpl** [slowtorta/turtlewow-bug-tracker#4736]
**Please, provide a clear description what the bug is:**

**Steps to reproduce the behavior with as much detail as possible:**

1.  Wolfblood can't be repaired or displays durability incorrectly
2. Repair cost didn't show up since I got it days ago
3.  

**IDs of affected creatures, items, quests or spells with a link to the relevant page:**

NPC: https://database.turtle-wow.org/?npc=
Item: https://database.turtle-wow.org/?item= database is locked
Quest: https://database.turtle-wow.org/?quest=
Spell: https://database.turtle-wow.org/?spell=
Object: https://database.turtle-wow.org/?object=

**Expected behavior. Describe how it should work:**

**Comment by ratkosrb** [comment]
It will be fixed in the next update.
