### ISSUE TITLE
Random lightning shield buff in Barrens

### ISSUE THREAD

**Issue by Zerthy** [slowtorta/turtlewow-bug-tracker#4737]
**Please, provide a clear description what the bug is:**
Well lets say I believe it is a bug. Around place with Razormane adds 10-13 lvl on north-east of barrens, Ive started getting lightning shield (shaman spell), however 20x stronger than normally (in short, when add hit me, I reflected 196 damage), as it got depleted by 3 stacks, I regained it again and again (in total like 15x). As soon as I left the place, it disappeared even tho it had 8 min more duration.
**Steps to reproduce the behavior with as much detail as possible:**

1. I guess it should not appear at all. Ive checked my bags, quests, if something can give it to me, or even adds around if they cast it on me. None of that was it.

**IDs of affected creatures, items, quests or spells with a link to the relevant page:**
Probably only me, Ive been asking players around, if it happens to them too. It appears I am alone.

Database is unavaliable for now, so I cant post link, however I can atleast send a screen of particular buff on myself

Screens: https://imgur.com/a/KqIFa0A

NPC: https://database.turtle-wow.org/?npc=
Item: https://database.turtle-wow.org/?item=
Quest: https://database.turtle-wow.org/?quest=
Spell: https://database.turtle-wow.org/?spell=
Object: https://database.turtle-wow.org/?object=

**Expected behavior. Describe how it should work:**

**Comment by Dragunovi** [comment]
A max level Enhancement Shaman buffed you using their new cornerstone talent "Thunderhead" which allows them to grant Lightning Shield to friendly players.
![image](https://github.com/slowtorta/turtlewow-bug-tracker/assets/86127352/a81b9f0c-ce60-45e1-aac6-60c2429b7bb7)
