### ISSUE TITLE
invocations

### ISSUE THREAD

**Issue by reynolds11234** [slowtorta/turtlewow-bug-tracker#4738]
**Please, provide a clear description what the bug is:**
invocation of shattering STILL will not apply to helment slot'

**Steps to reproduce the behavior with as much detail as possible:**

1.
2. 
3. 

**IDs of affected creatures, items, quests or spells with a link to the relevant page:**

NPC: https://database.turtle-wow.org/?npc=
Item: https://database.turtle-wow.org/?item=
Quest: https://database.turtle-wow.org/?quest=
Spell: https://database.turtle-wow.org/?spell=
Object: https://database.turtle-wow.org/?object=

**Expected behavior. Describe how it should work:**

**Comment by Muigin** [comment]
#4814 
#4810 
#4790 
#4788 
#4759 
#4753
