### ISSUE TITLE
Outline: Cleaning cloth

### ISSUE THREAD

**Issue by RaubZar** [slowtorta/turtlewow-bug-tracker#4739]
Learned Outline: Cleaning cloth, but it didnt appear in survival tab.

1.Learned Outline: Cleaning cloth

Expected behavior - should appear in survival tab
(Cleaning WDB folder didnt help)
Screenshot: 
![Безымянный](https://github.com/slowtorta/turtlewow-bug-tracker/assets/107718065/33ec0d33-03f7-400f-8b33-5191fec2e3d6)

**Comment by luskanek** [comment]
The item has been temporally removed, it will return in a future update.

**Comment by RaubZar** [comment]
ty
