### ISSUE TITLE
The inn in Alah'Thalas is not a rest area

### ISSUE THREAD

**Issue by StrawberryBrains** [slowtorta/turtlewow-bug-tracker#474]
**Please, provide a clear description what the bug is:**
The inn in Alah'Thalas with innkeeper Joalar Solar does not grant the player rested XP like all other inns in-game do. Is this a deliberate choice or an oversight?

**Steps to reproduce the behavior with as much detail as possible:**
1. Go to the inn in Alah'Thalar
2. You will notice there is no ''zzz'' on the character frame and it is not glowing either because the character is not gaining rested XP
3. You can also try logging out which is instant in rest areas but not in the Alah'Thalas inn

**Expected behavior. Describe how it should work:**
Characters should gain rested XP in inns and be able to log out instantly.

**Comment by slowtorta** [comment]
It's not something what we can easily fix, so it'll be left as it is, sadly.
