### ISSUE TITLE
New First Aid Recipe dropped from Moroes in Karazhan dont create items, it supose to

### ISSUE THREAD

**Issue by Bashmakss** [slowtorta/turtlewow-bug-tracker#4741]
**Please, provide a clear description what the bug is:**

**Steps to reproduce the behavior with as much detail as possible:**

1.New First Aid Recipe dropped from Moroes in Karazhan dont create items, it supose to
2. Got recipe, learned it, have reagents, after using, first aid skill, recieve error: Item is not ready yet
3. Database links is impossible right now.
I supose it should create Powerfull smelling salt as intended, without error message

**IDs of affected creatures, items, quests or spells with a link to the relevant page:**

NPC: https://database.turtle-wow.org/?npc=
Item: https://database.turtle-wow.org/?item=
Quest: https://database.turtle-wow.org/?quest=
Spell: https://database.turtle-wow.org/?spell=
Object: https://database.turtle-wow.org/?object=

**Expected behavior. Describe how it should work:**

**Comment by Bashmakss** [comment]
![image1](https://github.com/slowtorta/turtlewow-bug-tracker/assets/147941830/d3a23731-bd62-42b3-b5f9-501e1621f437)
When pressing to create salt, recieve error messade: item is not ready yet.

**Comment by Bashmakss** [comment]
Recipe link: https://database.turtle-wow.org/?item=8547
Reagent it should create: https://database.turtle-wow.org/?item=8546
Ingame requirements as you can see on screenshot - 4 Deeprock salt: https://database.turtle-wow.org/?item=8150
But in database are much more expencive reagents described - 4 Deeprock salt: https://database.turtle-wow.org/?item=8150, 2 Essence of Fire https://database.turtle-wow.org/?item=7078, and 1 Larval Acid https://database.turtle-wow.org/?item=18512

**Comment by Bashmakss** [comment]
Problem presists only when applying NEW GRAPHICS models patches.
when removing files, all new and changed recipes like Tel'abim Medley: https://database.turtle-wow.org/?quest=40754
and Powerful Smelling Salts: https://database.turtle-wow.org/?item=8546
![image](https://github.com/slowtorta/turtlewow-bug-tracker/assets/147941830/7425dbb4-4a3c-4cae-8cee-37015beb449c)
works fine. can you please fix it ?

**Comment by redmagejoe** [comment]
I have reviewed my Spell.DBC in my Turtle HD patch-A and found that the spell for Powerful Smelling Salts is precisely the same as that in patch-4 (official Turtle patch).  They are identical.  This seems more like a cache issue, so you should try deleting your WDB folder.

This is NOT caused by Turtle HD.

**Comment by twowTurtReynolds** [comment]
Works fine:
![image](https://github.com/slowtorta/turtlewow-bug-tracker/assets/151180101/6e866bc6-cd7e-47b8-af7b-a8ac2de3450f)

Indeed, likely a cache issue.
