### ISSUE TITLE
Uldaman entrance fall damage error

### ISSUE THREAD

**Issue by kpbendi** [slowtorta/turtlewow-bug-tracker#4742]
**Please, provide a clear description what the bug is:**

At the Uldaman cave entrance outside if you jump down from the small ramp, you get 1500 fall damage.

**Steps to reproduce the behavior with as much detail as possible:**

1. stay at the small ramp where the mage dwarf npc is
2. move towards the cave by jumping down
3. you get 1500 fall damage

**IDs of affected creatures, items, quests or spells with a link to the relevant page:**

NPC: https://database.turtle-wow.org/?npc=
Item: https://database.turtle-wow.org/?item=
Quest: https://database.turtle-wow.org/?quest=
Spell: https://database.turtle-wow.org/?spell=
Object: https://database.turtle-wow.org/?object=

**Expected behavior. Describe how it should work:**

**Comment by twowTurtReynolds** [comment]
![image](https://github.com/slowtorta/turtlewow-bug-tracker/assets/151180101/b8367264-e50c-4db9-921e-ebe6759c5ab7)
Where exactly does this issue occur? Please provide pictures.

**Comment by twowTurtReynolds** [comment]
I'll mark this closed until blizzlike proof is provided.
