### ISSUE TITLE
Grey enchants

### ISSUE THREAD

**Issue by Lexiebean** [slowtorta/turtlewow-bug-tracker#4744]
[Enchant Bracer - Spell Power]
[Enchant Bracer - Greater Agility]

These show up as being grey in my enchanting tab, despite them being learned at level 300.

**Comment by Muigin** [comment]
This issue has been brought to the attention of our Spell Dev.

**Comment by 0Moon01** [comment]
Sent in the correction for this issue to testing. SkillLineAbility oversight.
