### ISSUE TITLE
the bug for human Hunter

### ISSUE THREAD

**Issue by sageskr** [slowtorta/turtlewow-bug-tracker#4746]
**Please, provide a clear description what the bug is:**

**Steps to reproduce the behavior with as much detail as possible:**

1. I can't use the Taming Rod for the class task of L10 HUnter (task name: Taming the Beast)
2. ID: Shter Class: Human
3.  

**IDs of affected creatures, items, quests or spells with a link to the relevant page:**

NPC: https://database.turtle-wow.org/?npc= DaisyWindhelm
Item: https://database.turtle-wow.org/?item=Taming Rod
Quest: https://database.turtle-wow.org/?quest=Taming the Beast
Spell: https://database.turtle-wow.org/?spell=
Object: https://database.turtle-wow.org/?object=

**Expected behavior. Describe how it should work:**

**Comment by slowtorta** [comment]
Clean your WDB folder please and try again.
