### ISSUE TITLE
Horde portal entrance into Stormwind Vaults broken with 1.17

### ISSUE THREAD

**Issue by Slimthegrim** [slowtorta/turtlewow-bug-tracker#4747]
**Please, provide a clear description what the bug is:**
Horde can no longer zone into Stormwind Vaults via the external horde portal instance entrance in Elwynn Forest at Mirror Lake.

**Steps to reproduce the behavior with as much detail as possible:**

1. Be Horde.
2. Try Zone in.
![image](https://github.com/slowtorta/turtlewow-bug-tracker/assets/110629519/61f23494-4043-4f16-bd2e-4800c13ff07b)

**IDs of affected creatures, items, quests or spells with a link to the relevant page:**

I don't believe instance portals have ID's? But the coordinates are the portal instance entrance at Mirror Lake 28,61 Elwynn.

**Expected behavior. Describe how it should work:**
This was working before the big content drop.

**Comment by Muigin** [comment]
This has been fixed as of our last maintenance.
