### ISSUE TITLE
Dueling not working, invalid target.

### ISSUE THREAD

**Issue by kalotko** [slowtorta/turtlewow-bug-tracker#4749]
**Please, provide a clear description what the bug is:**
When trying to duel, I become "invalid target" to my challenger and they are the same for me. Cannot attack or use spells in any way against them.
**Steps to reproduce the behavior with as much detail as possible:**

1. Deactivating War Mode (?)
2. /duel someone
3. 

**IDs of affected creatures, items, quests or spells with a link to the relevant page:**

**Expected behavior. Describe how it should work:**
Should be able to attack someone engaged in a duel with you.

**Comment by Muigin** [comment]
Dueling parties cannot be in a player party.

Duels are working as intended.
