### ISSUE TITLE
Jasperlode Infestation

### ISSUE THREAD

**Issue by zesilo** [slowtorta/turtlewow-bug-tracker#475]
**Please, provide a clear description what the bug is:**

Can not turn in the quest "Jasperlode Infestation"

**Steps to reproduce the behavior with as much detail as possible:**

1. Kill more than the 8 required spiders for the quest.

**IDs of affected creatures, items, quests or spells with a link to the relevant page:**

Quest: https://database.turtle-wow.org/?quest=60154

**Expected behavior. Describe how it should work:**

Turn in to complete even if you kill more than 8 spiders.

**Comment by Tinyfin-github** [comment]
Greetings! I have tested and i have been unable to reproduce the bug.
 You can complete the quest even after you kill more then 8 spiders.

For a bug report always post screenshots or videos to help us replicate the bug .
Remember to always clean your WDB folder while the game is closed before submitting a bug.

https://user-images.githubusercontent.com/83077166/143079246-b419a9fa-11d8-4f24-8891-10f78a741095.mp4
