### ISSUE TITLE
 Raw Nightfin Snapper no exist in Un'Goro Crater

### ISSUE THREAD

**Issue by Hajache** [slowtorta/turtlewow-bug-tracker#4751]
**Please, provide a clear description what the bug is:**

After fishing for 30 minutes I haven't managed to catch any.

**Steps to reproduce the behavior with as much detail as possible:**

1.fish skill 300 +20 pole +100 lure (420)
2. some loot windows after fishing are empty without loot
3. 

**IDs of affected creatures, items, quests or spells with a link to the relevant page:**

**Comment by Muigin** [comment]
#4530
