### ISSUE TITLE
Kara 10 Invocation still not correct, after applying patch-Z.mpq

### ISSUE THREAD

**Issue by Smileybob1** [slowtorta/turtlewow-bug-tracker#4753]
The new Kara 10 Invocation enchants still appear to be buggy. I have downloaded and applied the patch-Z.mpq and it has had some effect. The Enchant will now no longer target shoulders and will now target head and leg slot, as intended. However It does not apply, or at least it will not overwrite a previous enchant.

Attempting to use Invocation of Greater Protection
![image](https://github.com/slowtorta/turtlewow-bug-tracker/assets/147317219/8099aa95-34fe-4460-b9c4-0a2171c1b143)

Attempted to apply to Guise of the Devourer and/or Leggings of the Inferno
![image](https://github.com/slowtorta/turtlewow-bug-tracker/assets/147317219/29eb71e0-96e7-410a-b9d5-1f578969846e)
![image](https://github.com/slowtorta/turtlewow-bug-tracker/assets/147317219/ef1c1c01-4e0e-4415-8a22-5de4e6b60992)

Prompted with confirmation dialogue box
![image](https://github.com/slowtorta/turtlewow-bug-tracker/assets/147317219/690daa97-6e07-4d37-a659-c28b870b00f6)

Enchant fails to apply and the message: "Must have a Cloth equipped" is displayed.
![image](https://github.com/slowtorta/turtlewow-bug-tracker/assets/147317219/7932c224-c28d-4841-8e9d-c687184bbee5)

I have tried with either item equipped or not equipped but still get the same error message and the enchant fails to apply.
I have also tried with a head or leg item that has no previous enchantment and still get the "Must have a Cloth equipped" error message.

**Comment by Chourin** [comment]
Yes this error is still not fixed even though issues were closed and said to be fixed.

**Comment by Muigin** [comment]
This issue will be fixed in a future maintenance.  ETA unknown.
#4814 
#4810 
#4790 
#4788
