### ISSUE TITLE
quest Controlling Sailors bugged

### ISSUE THREAD

**Issue by makilahy** [slowtorta/turtlewow-bug-tracker#4755]
After talking to and fighting Sailor Pardol, no credit is given (typically), so the quest cannot be completed. This happens even after the client has been rebooted and the WDB folder has been deleted.

**Steps to reproduce the behavior with as much detail as possible:**

1. Get the quest: Controlling Sailors
2. Talk to the other sailors: Sailor Hylreth & Sailor Brewen
3. Talk to Sailor Pardol and fight him. At 50% health, he will give up and he will yield. Very often, credit is not given. After attempting many times, credit is sometimes given.

**IDs of affected creatures, items, quests or spells with a link to the relevant page:**

NPC: https://database.turtle-wow.org/?npc=61016
Quest: https://database.turtle-wow.org/?quest=40660

**Expected behavior. Describe how it should work:**

After the fight, credit should be given 100% of the time. However, I had to fight him seven times, even when no other players were around the interfere.

**Comment by twowTurtReynolds** [comment]
![image](https://github.com/slowtorta/turtlewow-bug-tracker/assets/151180101/b79131fb-cf6b-435e-8441-5fdb8c0789e5)

It worked the first time for me.
