### ISSUE TITLE
Garr adds can explode for 12k after boss is dead

### ISSUE THREAD

**Issue by Kangaroux** [slowtorta/turtlewow-bug-tracker#4756]
We lost an inferno char today after an add (Firesworn) exploded for 12k. Garr was dead before we started killing adds.

The adds have separation anxiety but that should only affect their melee damage and should only happen while Garr is still alive.

**Comment by twowTurtReynolds** [comment]
I set garr's speed to 0, and pulled the adds away into the next tunnel... and they don't seem to have separation anxiety:
![image](https://github.com/slowtorta/turtlewow-bug-tracker/assets/151180101/7297ce1f-c724-4f62-be34-4def9cc2f4cd)

I went back to kill garr, and I see the adds gain their buff:
![image](https://github.com/slowtorta/turtlewow-bug-tracker/assets/151180101/3d9baa96-0e21-475e-a2aa-1ff6628e82a0)

I killed garr, and I see the adds still losing and gaining the buff: 
![image](https://github.com/slowtorta/turtlewow-bug-tracker/assets/151180101/450c077a-97f0-4de0-9729-06858a56f683)

But I haven't seen a single one blow up for 12k damage....

I'm sorry for the loss of the Inferno player. If you have any further tests I could try, please let me know.
