### ISSUE TITLE
Blood ring buckle not applying

### ISSUE THREAD

**Issue by Largid0** [slowtorta/turtlewow-bug-tracker#4757]
Hello.

Blood ring buckle is BoP item which allows blacksmiths to use it on belt for -1% crit taken enchantment. 
However, unlike every other buckle, they cant use it on other players items.
There isnt anything stated on that in patch notes, item description or crafting spell.
Only difference between other buckles and blood ring one is being BoP, thus you cant trade/sell it directly.
But arcanums are also soulbound, yet you can use any of them on other players items. 

1. Craft Blood ring buckle via blacksmithing.
2. Open trade window with other player.
3. There will be a message popping when trying to enchant other player item, stating you can only use this buckle on your items.
 
Cant point the IDs since database isnt working RN.

It should either be stated in item that you cant enchant other players items so people wont spend time farming it for selling, 
or it should work same way Arcanums do - cant trade this item, but can enchant items via trade window.

Thanks in advance,
Orentored.

**Comment by Largid0** [comment]
I found out that in item effect it's stated "your belt", but still there are two issues:
1. You have to be a specific profession willing to grind arena marks, and that enchantment is only needed for tanks and pvpers + you're locked to that proffession since you will have to grind it back again should you change it.
2. That description isnt enough to clarify uselessness of this item in trading with other players.

**Comment by Muigin** [comment]
#4551
