### ISSUE TITLE
Emerald Blessing makes AQ40 mounts slow.

### ISSUE THREAD

**Issue by Kharkov72** [slowtorta/turtlewow-bug-tracker#4758]
**Please, provide a clear description what the bug is:**
For some reason, aq40 mounts do not go full speed while under the effect of Emerald Blessing

**IDs of affected creatures, items, quests or spells with a link to the relevant page:**

blackout lmao

**Expected behavior. Describe how it should work:**
shouldn't slow you while mounted, shouldn't have any effect tbh

**Comment by twowTurtReynolds** [comment]
![image](https://github.com/slowtorta/turtlewow-bug-tracker/assets/151180101/a38b7735-7563-47e2-a3a9-61c8e67a3801)
I put one toon on follow. Neither in same group. The follower that didnt have the buff wasn't any different speed.
