### ISSUE TITLE
invocation of shattering STILL doesnt work

### ISSUE THREAD

**Issue by reynolds11234** [slowtorta/turtlewow-bug-tracker#4759]
**Please, provide a clear description what the bug is:**
Invocation of shattering still wont work. when attempted to be applied it says "that is not a valid target"
**Steps to reproduce the behavior with as much detail as possible:**

1.right click to activate invocation of shattering
2. left click on helm to apply invocation
3. warning that says 'that item is not a valid target'

**IDs of affected creatures, items, quests or spells with a link to the relevant page:**

NPC: https://database.turtle-wow.org/?npc=
Item: https://database.turtle-wow.org/?item=
Quest: https://database.turtle-wow.org/?quest=
Spell: https://database.turtle-wow.org/?spell=
Object: https://database.turtle-wow.org/?object=

**Expected behavior. Describe how it should work:**

**Comment by Chourin** [comment]
![image](https://github.com/slowtorta/turtlewow-bug-tracker/assets/52112645/2332ecc3-e58e-4281-aa17-4e7595427d5e)

U also cant pick up the quest for greater protection again. Even with the new patch added to data it cant apply as well - just says u must have a cloth equipped.

**Comment by Chourin** [comment]
![image](https://github.com/slowtorta/turtlewow-bug-tracker/assets/52112645/f6e029ce-2540-415b-b8c6-6a511b1f0289)

**Comment by Muigin** [comment]
#4814 
#4810 
#4790 
#4788
