### ISSUE TITLE
1

### ISSUE THREAD

**Issue by donglike78** [slowtorta/turtlewow-bug-tracker#4761]
**Please, provide a clear description what the bug is:**

**Steps to reproduce the behavior with as much detail as possible:**

1.After killing Red, the BOSS on the upper level of the Blackrock Tower, nothing is dropped from the BOSS. Please help with this. thank you
2. 
3. 

**IDs of affected creatures, items, quests or spells with a link to the relevant page:**

NPC: https://database.turtle-wow.org/?npc=
Item: https://database.turtle-wow.org/?item=
Quest: https://database.turtle-wow.org/?quest=
Spell: https://database.turtle-wow.org/?spell=
Object: https://database.turtle-wow.org/?object=

**Expected behavior. Describe how it should work:**

**Comment by Muigin** [comment]
Insufficient information.
