### ISSUE TITLE
Mirage Raceway Mini game racing 

### ISSUE THREAD

**Issue by Dragoonduneman** [slowtorta/turtlewow-bug-tracker#4762]
I just got the quest to start a test race , on either goblin or gnomes 
I go find the girl dolores, dialogue appears .. and im registered for the race ... but that it ... just will not start the race.   I have no clue to what the heck im doing wrong  

**IDs of affected creatures, items, quests or spells with a link to the relevant page:**

NPC: https://database.turtle-wow.org/?npc=
Item: https://database.turtle-wow.org/?item=
Quest: https://database.turtle-wow.org/?quest=
Spell: https://database.turtle-wow.org/?spell=
Object: https://database.turtle-wow.org/?object=

**Expected behavior. Describe how it should work:**

**Comment by Muigin** [comment]
This race minigame requires two players in order for the race to begin. One must register for the Goblin Team, one must register for the Gnome Team. After that, the race will begin proper.

Working as intended.
