### ISSUE TITLE
Rotting Dead is not dropping Putrid Claw

### ISSUE THREAD

**Issue by Sejolino** [slowtorta/turtlewow-bug-tracker#4763]
**Description**

It seems that Rotting Dead is not dropping Putrid Claw for the quest The Putrid Task. I killed about 20 of them without a single drop, but when I killed the Ravaged Corpse, it was dropping one every two kills.

**IDs of affected creatures, items, quests or spells with a link to the relevant page:**

NPC: https://www.wowhead.com/classic/npc=1525/rotting-dead
Item: https://www.wowhead.com/classic/item=2855/putrid-claw
Quest: https://www.wowhead.com/classic/quest=404/a-putrid-task

**Comment by Muigin** [comment]
According to internal DB, Rotting Dead does indeed drop Putrid Claw. Please be aware that both Ravaged Corpse and Rotting Dead have only a 33% chance per kill to drop the quest item.

Working as intended.
