### ISSUE TITLE
塔纳利斯，奥丹姆任务BUG

### ISSUE THREAD

**Issue by anan0923** [slowtorta/turtlewow-bug-tracker#4764]
塔纳利斯，奥丹姆，联盟任务，拭目以待，无法交接任务，任务目标一直现实一个矮人影像

**Comment by Muigin** [comment]
请用英文提交问题。我们无法通过自动翻译准确地翻译中文提交的错误报告，这使得我们难以理解问题的确切性质。谢谢！

Please submit the issues in English. We're unable to accurately translate bug reports submitted in Chinese through automatic translation, which makes it difficult for us to understand the exact nature of the issue. Thank you!
