### ISSUE TITLE
Incendosaur Scale: No sell price

### ISSUE THREAD

**Issue by dominiksramko** [slowtorta/turtlewow-bug-tracker#4765]
**Please, provide a clear description what the bug is:**
The item [Incendosaur Scale](https://www.wowhead.com/classic/item=18944/incendosaur-scale)  has no vendor sell price.

**Steps to reproduce the behavior with as much detail as possible:**

1. Walk to any vendor
2. Hover over said item to retrieve ItemInfo sellPrice
3. It reports 0

**IDs of affected creatures, items, quests or spells with a link to the relevant page:**

Item: https://database.turtle-wow.org/?item=18944
Item: https://www.wowhead.com/classic/item=18944/incendosaur-scale

**Expected behavior. Describe how it should work:**
It should have a sell price of 123 (1s 23c)

**Comment by Muigin** [comment]
Working as intended. These items had no sell price in vanilla, and only had a sell price added to them in Cataclysm when the relevant quests were removed.  Classic (NOT Vanilla Retail) most likely kept the sell price as an added convenience.
