### ISSUE TITLE
Ashenvale: King of the Foulweald quest is not working

### ISSUE THREAD

**Issue by Buncaman** [slowtorta/turtlewow-bug-tracker#4767]
**King of the Foulweald quest is not working:**

**Steps to reproduce the behavior with as much detail as possible:**

1. I place the flag on the hill as I have to.
2. Than nothing happens. (No mob spawns, not any)
3. We tried placing more flags as a team and waited for like 5-10 minutes....

**IDs of affected creatures, items, quests or spells with a link to the relevant page:**

NPC: https://www.wowhead.com/classic/npc=12918/chief-murgut
Item: https://www.wowhead.com/classic/item=16976/murguts-totem
Quest: [King of the Foulweald](https://www.wowhead.com/classic/quest=6621/king-of-the-foulweald)

**Expected behavior. Describe how it should work:
As far as I know, after i place the Banner on the hill, 2 or 3 waves of mobs should spawn and attack us. Than, in the end we have to kill the Chief to loot the item. I am not sure if I have to loot it from him or it will spawn where he dies.**

**Comment by Muigin** [comment]
Cannot reproduce.  Upon placing the banner, 1-2 Enraged Foulweald spawn and approach the hill, with another one spawning every kill.  This results in 20+ Enraged Foulweald before Chief Murgut spawns.

It's possible that there is a cooldown on the script, but I have no way of testing this.  Please try abandoning the quest and attempting it once more.
