### ISSUE TITLE
Elemental Focus doesn't work with Earth Shock

### ISSUE THREAD

**Issue by Bluecow89** [slowtorta/turtlewow-bug-tracker#4770]
**Please, provide a clear description what the bug is:**
Elemental Focus doesn't work with Earth Shock, When i proc elemental focus so that i should only use 20% of the mana from earth shock, however it takes all of it. 

**Steps to reproduce the behavior with as much detail as possible:**

1. Get a spell crit to proc Elemental focus
2. Use earth shock ( For me it was rank 5)
3. See it not work

**IDs of affected creatures, items, quests or spells with a link to the relevant page:**

**Expected behavior. Describe how it should work:**
When i have elemental focus i should only be using 20% of the original mana cost from earth shock

**Comment by Muigin** [comment]
#4812

**Comment by Muigin** [comment]
Working as intended.  Correctly discounts 40% of mana cost on 2 spells, regardless of their rank or type.
