### ISSUE TITLE
After learning "Outline: Cleaning Cloth", the skill does not appear on my Survival crafting window.

### ISSUE THREAD

**Issue by dufftime** [slowtorta/turtlewow-bug-tracker#4772]
**Please, provide a clear description what the bug is:**
Title describes issue.  Please note I already tried deleting all the files inside my "WDB" folder and restarting.  I tried twice for good measure.

**Steps to reproduce the behavior with as much detail as possible:**

1.  Level Survival skill to 50.  I exclusively used "Dim Torch" but probably unrelated.
2.  I bought all the recipes/outlines from the Survival vendor "Rufus Hardwick" at Nesingwary's Expedition in STV.
3.  Click on all outlines to learn them, and all played the "learned new skill" sound.
4.  Opened the Survival crafting window from spellbook.  I see "Traveler's Tent", "Dim Torch", and "Iron Lantern" but no "Cleaning Cloth".  I apologize as I don't recall which order I learned them.

**IDs of affected creatures, items, quests or spells with a link to the relevant page:**

Unable to provide as there the DB is currently unavailable.

NPC: https://database.turtle-wow.org/?npc=
Item: https://database.turtle-wow.org/?item=
Quest: https://database.turtle-wow.org/?quest=
Spell: https://database.turtle-wow.org/?spell=
Object: https://database.turtle-wow.org/?object=

**Expected behavior. Describe how it should work:**

The "Cleaning Cloth" skill/recipe is available in Survival crafting window.

Please see screenshot showing issue.

![Cleaning Cloth bug](https://github.com/slowtorta/turtlewow-bug-tracker/assets/85697385/c5d9c915-fc0c-4fff-b6bb-4873896b45da)

**Comment by cyaohiri** [comment]
See #4739.
