### ISSUE TITLE
After enchanting "Anasterian's Legacy" 1h sword, enchanting glow is not visible.

### ISSUE THREAD

**Issue by dufftime** [slowtorta/turtlewow-bug-tracker#4773]
I acquired the 1h sword "Anasterian's Legacy" from Lower Karazhan Halls yesterday, and after enchanting with +15 agility, it does not have the familiar green glow.  I think this is just a visual bug 

**Steps to reproduce the behavior with as much detail as possible:**

1.  Equip "Anasterian's Legacy" sword in off-hand.  I am an female undead rogue if it matters.
2.  Apply "+15 agility" to sword.
3.  Although the sword is enchanted, sword does not glow green.
![sword no enchant glow](https://github.com/slowtorta/turtlewow-bug-tracker/assets/85697385/bf601384-c226-459e-aba4-bba7d3b83306)

**IDs of affected creatures, items, quests or spells with a link to the relevant page:**

NPC: https://database.turtle-wow.org/?npc=
Item: https://database.turtle-wow.org/?item=
Quest: https://database.turtle-wow.org/?quest=
Spell: https://database.turtle-wow.org/?spell=
Object: https://database.turtle-wow.org/?object=

**Expected behavior. Describe how it should work:**

**Comment by twowTurtReynolds** [comment]
![image](https://github.com/slowtorta/turtlewow-bug-tracker/assets/151180101/abcfb306-ffb6-4384-ae15-7adf1906c942)
Fixed next update :)

**Comment by twowTurtReynolds** [comment]
![image](https://github.com/slowtorta/turtlewow-bug-tracker/assets/151180101/2d09ab2a-1e5e-4a20-8093-0e59db3c5baf)
