### ISSUE TITLE
Shaman talent Enhancing Totems does not show correct agi and str amount on character buff.

### ISSUE THREAD

**Issue by Konspaul** [slowtorta/turtlewow-bug-tracker#4775]
**Please, provide a clear description what the bug is:**

Shaman talent Enhancing Totems does not show correct agi and str amount on character buff. Talent not select totem buff is 77. Talent selected buff should be 88. But character buff still indicates 77.

**Steps to reproduce the behavior with as much detail as possible:**

1.
2. 
3. 

**IDs of affected creatures, items, quests or spells with a link to the relevant page:**

NPC: https://database.turtle-wow.org/?npc=
Item: https://database.turtle-wow.org/?item=
Quest: https://database.turtle-wow.org/?quest=
Spell: https://database.turtle-wow.org/?spell=
Object: https://database.turtle-wow.org/?object=

**Expected behavior. Describe how it should work:**

**Comment by cyaohiri** [comment]
Check by how much the stats change on your character. It could be just a visual error on the buff.

**Comment by Muigin** [comment]
This is not a bug.  The vanilla client did not support character-side buffs to their abilities appearing in the buff tooltips.  The only place a change would be reflected is on the tooltip of the character's own spells, and the aftereffects of stats in any affected characters' stat windows.

Working as intended.
