### ISSUE TITLE
Shaman talent Thunderhead is not castable on alliance player.

### ISSUE THREAD

**Issue by Konspaul** [slowtorta/turtlewow-bug-tracker#4776]
**Please, provide a clear description what the bug is:**

Shaman talent Thunderhead is not castable on alliance player. I wish it was. We are playing on xfaction server.

**Steps to reproduce the behavior with as much detail as possible:**

1.
2. 
3. 

**IDs of affected creatures, items, quests or spells with a link to the relevant page:**

NPC: https://database.turtle-wow.org/?npc=
Item: https://database.turtle-wow.org/?item=
Quest: https://database.turtle-wow.org/?quest=
Spell: https://database.turtle-wow.org/?spell=
Object: https://database.turtle-wow.org/?object=

**Expected behavior. Describe how it should work:**

**Comment by ratkosrb** [comment]
You can cast it on Alliance, you just have to invite them to your group.
