### ISSUE TITLE
Sealed Azure Bag, level 50 Rogue quest. No quest item.

### ISSUE THREAD

**Issue by Mashadeve** [slowtorta/turtlewow-bug-tracker#4777]
I spent a great amount of time (2-3hours) farming Timbermaw Shamans at Azshara for level 50 Rogue quest "Sealed Azure Bag"
without having it drop. This probably shouldn't be this way? Although it took some dringing in Classic wow to get it didn't take nearly as long as this and still no quest item.

Turtle database not working atm so can't link the items or quest.

Drop chance described in wowhead is 3.55%. I've spent whole level farming and nothing.

**Comment by SuqMadiqM8** [comment]
I dont know if they are supposed to drop at all, they are obtained via pickpocket from the shamans at 100% even if you're not on the quest (anymore).
