### ISSUE TITLE
Totem of Crackling Thunder not working correctly

### ISSUE THREAD

**Issue by VrogragFishslayer** [slowtorta/turtlewow-bug-tracker#4778]
The new "Totem of Crackling Thunder" seems to have an incorrect proc rate. 
![totem](https://github.com/slowtorta/turtlewow-bug-tracker/assets/139925005/eb95e75a-de49-4616-9394-a13979555f77)

Elemental Shaman
1. Cast any rank of lightning bolt
2. See the haste buff only procs once every 20 - 30 lightning bolts (tested for 10 minutes)
3. Wonder why a world drop blue (totem of the storm) is still miles better

Enhancement Shaman
1. Cast stormstrike, wait for it to come off CD
2. See that the haste buff only procs once every 20 - 30 storm strikes (tested for 10 minutes)
3. Go get a different totem

Item: https://database.turtle-wow.org/?item=61292
I'd look up the haste buff applied but DB is still down, sorry. 

A relic slot totem like this should be proc'ing more often to make it in anyway shape or form an alternative for elemental shaman. After thorough testing against totem of the storm, this is a direct damage decrease despite the item being of rarer quality and harder to get. From an enhancement point of view this seems just downright broken. A spell that has a long cooldown like storm strike should not have a proc rate this low, it will not feasibly be usable at all to enhancement shamans. 

Potential fixes: Fix the proc rate for either spell. Arguably the rate for lightning bolt doesn't need a huge increase, but currently it is too low. For storm strike it needs to be drastically increased. Another potential fix is to use chain lightning as the spell that can proc the haste buff for elemental, but the proc rate would still need to be increased a good deal more. 

Thanks dev team!

**Comment by LachtanCesky** [comment]
I can confirm, the proc rate of the totem VERY low. I'd suggest increasing the proc rate to 15-20% to make actualy good/wanted item.

**Comment by VrogragFishslayer** [comment]
Just adding to this, I did run some tests specifically for lightning bolt to show what an abysmal proc rate means, and at least back up my claim with some hard data. I used the addon "proc watch" and cast rank 1 LB for 5 minutes straight. As you can see a measly 2 procs per minute average means, at best, and with a lightning bolt only rotation for elemental you can only squeeze out only one extra lightning bolt every minute. Compared to the flat 30 (or 60 when crit) from totem of the storm, and the fact that chain lightning is also in the elemental shaman rotation the only conclusion is that the totem of crackling thunder is a straight DPS loss. 
![lightningspeed](https://github.com/slowtorta/turtlewow-bug-tracker/assets/139925005/09094284-5cdd-44a7-848e-d2ede76cd944)

**Comment by twowTurtReynolds** [comment]
Should be fixed as per https://github.com/slowtorta/turtlewow-bug-tracker/issues/4984
