### ISSUE TITLE
The rare Barksin Fisher seems to be not respawning anymore

### ISSUE THREAD

**Issue by EgonXY** [slowtorta/turtlewow-bug-tracker#4779]
**The rare Barksin Fisher seems to be not respawning anymore**

**Steps to reproduce the behavior with as much detail as possible:**

1. Waited 24h on the spot to be sure that the rare mob spawn
2. After several time camping him on different day times for 24 hours still no repawn
3. After several time camping him with 2 people on different day times for 24 hours still no repawn

**IDs of affected creatures, items, quests or spells with a link to the relevant page:**

NPC: https://database.turtle-wow.org/?npc=Barkskin Fisher
Item: https://database.turtle-wow.org/?item=Fishing Rod ?
Quest: https://database.turtle-wow.org/?quest=
Spell: https://database.turtle-wow.org/?spell=
Object: https://database.turtle-wow.org/?object=Fishing Rod

**Expected behavior. Describe how it should work:**Barksin Fisher should spawn and being possible to be killed for the new fishing rod.

**Comment by Muigin** [comment]
This rare spawn has an excessively high respawn timer! (can't tell you exactly how long, of course)

Working as intended.
