### ISSUE TITLE
Hunter pet skill dive has no cooldown

### ISSUE THREAD

**Issue by dole555** [slowtorta/turtlewow-bug-tracker#478]
**Please, provide a clear description what the bug is:**
The hunter pet skill "Dive" should have a 30second cooldown (which is indeed noted on the tooltip). The problem is the skill can be used again after about 2 seconds, even though it still shows 28seconds cooldown left.
Currently tested with dive rank 3. Haven't tested other ranks of dive.

**Steps to reproduce the behavior with as much detail as possible:**

1. Tame an owl with dive rank 3.
2. Use skill dive rank 3
3. Use the skill again in rapid succession, before cooldown is finished.

**IDs of affected creatures, items, quests or spells with a link to the relevant page:**

NPC: https://database.turtle-wow.org/?npc=7456/winterspring-screecher
Item: https://database.turtle-wow.org/?item=
Quest: https://database.turtle-wow.org/?quest=
Spell: https://database.turtle-wow.org/?spell=
Object: https://database.turtle-wow.org/?object=

**Expected behavior. Describe how it should work:**
It should not be able to be used again until the 30 seconds cooldown has passed.

**Comment by CosminPOP** [comment]
I believe this was fixed when dash was fixed too, a while ago. Reopen if i'm wrong.
