### ISSUE TITLE
Minning bug after leveling it second time

### ISSUE THREAD

**Issue by Zapodlol** [slowtorta/turtlewow-bug-tracker#4780]
Recently i did reset my profession to get back to mining, and i stuck at 75. Can't learn further, because all trainers show that i know all mining skills already.

1. I had mining + engi long time ago, then i reset mining to get herbalism + engi. 
2. Recently i decided to level mining again and now it stuck at 75.
3.Can't learn any further because it says that i know Journeyman and expert already

Name of character Eltoxico (orc, warrior)

![Mining Bug](https://github.com/slowtorta/turtlewow-bug-tracker/assets/148156434/f61619f3-04a0-4268-b12f-37b022b7bbec)

**Comment by cyaohiri** [comment]
Delete your WDB folder while the game is closed and then visit the trainer. It might help.

**Comment by Zapodlol** [comment]
thanks it worked. Dunno if i face problem when i achieve 225 skill. will let yoy know =)
