### ISSUE TITLE
Maraudon Princess blade of eternal darkness drop chance is 0.2% it should be 2% 

### ISSUE THREAD

**Issue by soundflow** [slowtorta/turtlewow-bug-tracker#4784]
**Please, provide a clear description what the bug is:**
Maraudon Princess blade of eternal darkness drop chance is 0.2%
it should be 2% since.
It was changed from 2% to 0.2% in classic Wow (not vannila)

**Steps to reproduce the behavior with as much detail as possible:**

1. Atlass loot shows the drop chance
2.  
3.  

**IDs of affected creatures, items, quests or spells with a link to the relevant page:**

NPC: https://database.turtle-wow.org/?npc=
Item: https://database.turtle-wow.org/?item=
Quest: https://database.turtle-wow.org/?quest=
Spell: https://database.turtle-wow.org/?spell=
Object: https://database.turtle-wow.org/?object=

**Expected behavior. Describe how it should work:**
Drop chance should be higher

**Comment by cyaohiri** [comment]
Make sure you have the right version of AtlasLoot. The drop chance shown there is 1%.
https://github.com/Lexiebean/AtlasLoot
