### ISSUE TITLE
Unable to complete Removing Leper Leadership

### ISSUE THREAD

**Issue by Undisturbed1** [slowtorta/turtlewow-bug-tracker#4785]
**Please, provide a clear description what the bug is:**
Unable to complete Removing Leper Leadership quest from Teezle Dualflash in the new gnomer area. Upon attempting to hand in the quest, both quest completion and failed sounds will play at the same time, and clicking complete quest does not work.
**Steps to reproduce the behavior with as much detail as possible:**

1. Accept Removing Leper Leadership
2.  Kill Neevan Gubblewire
3. Attempt to complete quest

**IDs of affected creatures, items, quests or spells with a link to the relevant page:**

Quest: https://database.turtle-wow.org/?quest=40857

**Expected behavior. Describe how it should work:**
should be able to complete quest

**Comment by Muigin** [comment]
Please check that you still have the quest in your log. There is a very rare bug that occurs where a quest completes and gives you the credit and rewards, but does not close the dialog box automatically when clicking "Complete Quest". The quest is usually removed from your log and you have been given appropriate credit for it.

Comment here again if this is not the case. Also be sure that you delete your WDB folder.

**Comment by Undisturbed1** [comment]
Quest was not removed from log, rewards/exp were not given. Deleted WDB folder 2 times

**Comment by twowTurtReynolds** [comment]
The issue here is that the quest makes you pick a reward, but there's only one reward... which is confusing.

**Comment by Muigin** [comment]
Fixed on next update.
