### ISSUE TITLE
addon turtlewow "Group finder"

### ISSUE THREAD

**Issue by hokagegaara** [slowtorta/turtlewow-bug-tracker#4787]
addon turtlewow "Group finder"
https://cdn.discordapp.com/attachments/484376201272754176/1163798518587207711/image.png
https://cdn.discordapp.com/attachments/484376201272754176/1163798637709623336/image.png
https://cdn.discordapp.com/attachments/484376201272754176/1163798701437894707/image.png
https://cdn.discordapp.com/attachments/484376201272754176/1163798741384429638/image.png

**Comment by welpenhund** [comment]
the addon is not needed anymore on t-wow. it is integrated in the client now. delete the addon in your folder and it gets fixed

> addon turtlewow "Group finder" https://cdn.discordapp.com/attachments/484376201272754176/1163798518587207711/image.png https://cdn.discordapp.com/attachments/484376201272754176/1163798637709623336/image.png https://cdn.discordapp.com/attachments/484376201272754176/1163798701437894707/image.png https://cdn.discordapp.com/attachments/484376201272754176/1163798741384429638/image.png

**Comment by twowTurtReynolds** [comment]
If you can replicate this issue, and prove you have the old LFT addon uninstalled, please let us know here.
