### ISSUE TITLE
Kara Head/Legs Enchants not able to be applied

### ISSUE THREAD

**Issue by TheKagarin** [slowtorta/turtlewow-bug-tracker#4788]
**Please, provide a clear description what the bug is:**

Just obtained the Invocation of Greater Protection behind Karazhan, when trying to use on the mail Bloody Gladiator's Helmet I get told "That is not a Valid Target" both equipped and in bags. I really hope we can use them on this gear! Thank you for any help!

**Steps to reproduce the behavior with as much detail as possible:**

1. Invocation of Greater Protection (Karazhan head/leg enchant)
2. Bloody Gladiator's Helment (Mail)
3. 

**IDs of affected creatures, items, quests or spells with a link to the relevant page:**

NPC: https://database.turtle-wow.org/?npc=
Item: https://database.turtle-wow.org/?item=
Quest: https://database.turtle-wow.org/?quest=
Spell: https://database.turtle-wow.org/?spell=
Object: https://database.turtle-wow.org/?object=

**Expected behavior. Describe how it should work:**

**Comment by Muigin** [comment]
This is known and requires a spell tweak.  Will be fixed in a future maintenance.  ETA unknown.

**Comment by Muigin** [comment]
This is known and requires a spell tweak.  Will be fixed in a future maintenance.  ETA unknown.

**Comment by twowTurtReynolds** [comment]
As per https://github.com/slowtorta/turtlewow-bug-tracker/issues/4705 this bug will be fixed with the release of 1.17.1. Until then, you can opt to install a patch by hand to fix this issue for yourself. Do remember to make sure this patch is removed when 1.17.1 launches.

**Comment by vill8** [comment]
Please PSA others that you can apply the enchants on other players' items in trade window

**Comment by twowTurtReynolds** [comment]
Using the 1.17.1 patch-5.mpq currently in testing: I confirm these enchants work out of the box correctly with this patch.
![image](https://github.com/slowtorta/turtlewow-bug-tracker/assets/151180101/11895d7b-bc3a-431a-a72b-ac9f16cd1f97)
![image](https://github.com/slowtorta/turtlewow-bug-tracker/assets/151180101/a5417db9-b7c9-4420-9971-8a9b3d03b7d2)
