### ISSUE TITLE
Invocation of Shattering does not apply on Crown of Destruction

### ISSUE THREAD

**Issue by TheKagarin** [slowtorta/turtlewow-bug-tracker#4790]
**Please, provide a clear description what the bug is:**

Just in case these are isolated items not working with the enchants, I also turned in the quest for Invocation of Shattering from behind Karazhan and tried to apply it to the Crown of Destruction and was met with the "That is not a valid target" Same as my previous posting about Invocation of Greater Protection not working on Bloody Gladiator's Helmet(mail). Shattering quest re-appeared, Protection did not. I cleared my WDB just before hand in case as well. Thank you for assistance and have been loving the content so far!
 
![Screenshot (307)](https://github.com/slowtorta/turtlewow-bug-tracker/assets/148221077/ce79a07f-f287-416b-857d-bc6152b62411)

**Steps to reproduce the behavior with as much detail as possible:**

1. Invocation of Shattering
2. Crown of Destruction
3. 

**IDs of affected creatures, items, quests or spells with a link to the relevant page:**

NPC: https://database.turtle-wow.org/?npc=
Item: https://database.turtle-wow.org/?item=
Quest: https://database.turtle-wow.org/?quest=
Spell: https://database.turtle-wow.org/?spell=
Object: https://database.turtle-wow.org/?object=

**Expected behavior. Describe how it should work:**

**Comment by Muigin** [comment]
This is known and requires a spell tweak.  Will be fixed in a future maintenance.  ETA unknown.
#4788 
#4810 
#4814
