### ISSUE TITLE
Suppression

### ISSUE THREAD

**Issue by blueberryg1rl** [slowtorta/turtlewow-bug-tracker#4791]
**The class quest **_Suppression_** is not available for _troll warlocks_.**

**Steps to reproduce the behavior with as much detail as possible:**

1.Two prequisite quests: [The Prison's Bindings] ID: 7581  _(https://classicdb.ch/?quest=7581)_
2. [The Prison's Casing] ID:7582 _(https://classicdb.ch/?quest=7582)_
3. [Suppression] ID: 7583_(https://classicdb.ch/?quest=7583)_

**NPC ID: 14463 Quest ID: 7583**

NPC: https://www.wowhead.com/classic/npc=14463/daio-the-decrepit
Item: -
Quest: https://www.wowhead.com/classic/quest=7583/suppression
Spell: -
Object: -

**Expected behavior. Describe how it should work:**

**Comment by Muigin** [comment]
Cannot reproduce. This appears to be working as intended. If you complete both prequests, you can accept this quest as a Troll Warlock.

However, it does appear that The Prison's Casing is incorrectly "chaining" into Suppression, when this is not official behavior. Chaining should never be used to offer a quest that has multiple prerequisite quests, as this behavior you probably encountered can happen. The chaining will be removed in a future maintenance.
