### ISSUE TITLE
Anvil & Forge in Object's: Remove/Move Anvil ouside barrels

### ISSUE THREAD

**Issue by hokagegaara** [slowtorta/turtlewow-bug-tracker#4793]
Remove/Move Anvil ouside barrels and Forge ouside crate
How to do it better:
Anvil put in place forge
Place forge instead of deathguard.
https://cdn.discordapp.com/attachments/484376201272754176/1163855985492901959/image.png
https://cdn.discordapp.com/attachments/484376201272754176/1163856596003201044/image.png

**Comment by Muigin** [comment]
This will be fixed in a future maintenance.
