### ISSUE TITLE
Instant disconnect when logging in without the use of VPN

### ISSUE THREAD

**Issue by Relgando** [slowtorta/turtlewow-bug-tracker#4795]
Been playing the last 1.5 month on twow. Before the gilneas patch i used to get DC when i would log into the game the first time, spam the log in button once or twice and eventually get into the game with no further issues. 

Ever since the new patch came, the problem is now more severe. I cant log in no matter what, without the use of VPN. I have contacted GMs about this ( PepeSmite ) and told me to make an issue here, since 30 other similar cases have been resolved. ( Couldnt find a similar issue tho when i tried ).

**Comment by twowTurtReynolds** [comment]
I'm not sure why you were directed here. This is an issue only GMs can help you with.
