### ISSUE TITLE
My engineering upgrade to 75 does not allow me to study intermediate engineering

### ISSUE THREAD

**Issue by wynnlol** [slowtorta/turtlewow-bug-tracker#4797]
**Please, provide a clear description what the bug is:**

**Steps to reproduce the behavior with as much detail as possible:**

1.I first upgraded the project to 242 and learned about dwarf, then I deleted it. Now I am relearning engineering and upgrading to 75. I am not allowed to study intermediate engineering, and my engineering skills disappeared, but my major is still here 75/75.
2. server is blood ring.
3. my account number:wzj1984530.role name:Wynn

**IDs of affected creatures, items, quests or spells with a link to the relevant page:**

NPC: https://database.turtle-wow.org/?npc=
Item: https://database.turtle-wow.org/?item=
Quest: https://database.turtle-wow.org/?quest=
Spell: https://database.turtle-wow.org/?spell=
Object: https://database.turtle-wow.org/?object=

**Expected behavior. Describe how it should work:**

**Comment by Muigin** [comment]
Cannot reproduce.  Please be sure you delete your WDB folder, as this is your cache.  The game has likely cached that you "already know this spell" because you learned it previously.  This should solve your issue.

Please never post your account name in a bug report on this repo, ever.
