### ISSUE TITLE
Character honor has not been settled

### ISSUE THREAD

**Issue by Surelysun** [slowtorta/turtlewow-bug-tracker#4799]
**Please, provide a clear description what the bug is:**

**Steps to reproduce the behavior with as much detail as possible:**

I am on the turtle Asia server Stormstout server, account is surelyz. 

1. My character '息刀' killed 57 last week, honor 1877, ranked 314, but the honor level did not change at all. 
2. It was rank 3, 29.8% before, and it still is now. 

**IDs of affected creatures, items, quests or spells with a link to the relevant page:**

NPC: https://database.turtle-wow.org/?npc=
Item: https://database.turtle-wow.org/?item=
Quest: https://database.turtle-wow.org/?quest=
Spell: https://database.turtle-wow.org/?spell=
Object: https://database.turtle-wow.org/?object=

**Expected behavior. Describe how it should work:**
Rank 4 at least.

**Comment by Muigin** [comment]
Please make appeals to GMs ingame, not through the bugtracker which is reserved for bugs that are universal.

**Comment by yummyza** [comment]
> Please make appeals to GMs ingame, not through the bugtracker which is reserved for bugs that are universal.

However, GMs ingame replied with an email for us to come here to bugtracker to submit this bug.
The Asian GMs are kicking each other around and don't care about the players at all.
This is a bit disappointing for us players.
