### ISSUE TITLE
Broodlord mandokir kills people being "gazed"

### ISSUE THREAD

**Issue by Badling** [slowtorta/turtlewow-bug-tracker#48]
This is new from current patching as far as i can tell, as it used to work flawlessly

**Current behavior**: 
Kills players even if they do nothing, hands off the keyboards when they get the gaze or being watched mechanic

**Expected behavior**: 
Should NOT kill people with Gaze machanic when they stop all attacks and movement

**Proofs**:
Any Classic guide example

**Steps to reproduce**:

1. pull 
2. get gazed
3. Die

**Comment by Nolin7777** [comment]
Duplicate. Will be fixed at next update.
