### ISSUE TITLE
Characters can't complete VIP Invites if they complete all quests from Gazlowe because they won't be able to interact with Gazlowe 

### ISSUE THREAD

**Issue by Tinyfin-github** [slowtorta/turtlewow-bug-tracker#480]
Characters can't complete VIP Invites if they complete all quests from Gazlowe because they won't be able to interact with Gazlowe 

Alliance characters can't complete VIP Invite ( https://database.turtle-wow.org/?quest=80382 ) if they complete Stolen Booty ( https://database.turtle-wow.org/?quest=888 )because they won't be able to interact with  Gazlowe ( https://database.turtle-wow.org/?npc=3391 ) 

Upon accepting the quest The Missing Shipment ( https://database.turtle-wow.org/?quest=890 ) You won't get the dialog to give Gazlowe ( https://database.turtle-wow.org/?npc=3391 ) the invite for the complete of the VIP Invite ( https://database.turtle-wow.org/?quest=80382 )

https://user-images.githubusercontent.com/83077166/143594991-e5ebe98e-18f7-49e3-8a5e-7a968bae1720.mp4

After you return with the part 2 of The Missing Shipment ( https://database.turtle-wow.org/?quest=892 ) You can interact with Gazlowe ( https://database.turtle-wow.org/?npc=3391 )to give the invite again.

https://user-images.githubusercontent.com/83077166/143595137-7d93c391-98bc-4a7c-b81f-9e03fe020da1.mp4

After you complete the final quest of the chain Stolen Booty ( https://database.turtle-wow.org/?quest=888 )  is no longer possible to give Gazlowe ( https://database.turtle-wow.org/?npc=3391 ) The invite.

https://user-images.githubusercontent.com/83077166/143595277-ac45cbc2-a71d-43ff-b4b4-e58bb39fb796.mp4

Horde character can complete  the quest  VIP Invite ( https://database.turtle-wow.org/?quest=80382 ) after hey complete Stolen Booty ( https://database.turtle-wow.org/?quest=888 ) if Letter to Mudsprocket (https://database.turtle-wow.org/?quest=80390) is not accepted.

https://user-images.githubusercontent.com/83077166/143596018-7f9ac81e-98e9-444d-b10e-b02f385162ae.mp4

 if Letter to Mudsprocket (https://database.turtle-wow.org/?quest=80390) is accepted they won't be able to complete VIP Invite ( https://database.turtle-wow.org/?quest=80382 ) after hey complete Stolen Booty ( https://database.turtle-wow.org/?quest=888 )
 
 
https://user-images.githubusercontent.com/83077166/143600473-5d7f6cf3-c32d-46e4-93a0-57b5a6dbaae3.mp4

**Comment by slowtorta** [comment]
Will be fixed in the next update!
