### ISSUE TITLE
Nexus Shoulderpads, effect not working.

### ISSUE THREAD

**Issue by LiviuOLV** [slowtorta/turtlewow-bug-tracker#4804]
**Please, provide a clear description what the bug is:**
Nexus Shoulderpads

Drops in Black Morass
174 Armor
17 Agi
17 Stamina

!! Equip: When struck in combat has a 1% of inflicting 30 to 50 Shadow damage to the attacker. !!

I let myself get hit around ~1000 times by different mob types, in different instances and open world. They never proc. 

They only do an animation which occurs only when I equip them (like I shadow bolt myself). This effect is happening to other items added in this patch as well. It can be fun to RP the animation that should be possible for my class (druid) but that's about it.

Thank you!

**Comment by twowTurtReynolds** [comment]
![image](https://github.com/slowtorta/turtlewow-bug-tracker/assets/151180101/6c69fc67-c16a-458a-967c-44948f5b3553)
It's a lot easier for me to test this with GM god mode. I am seeing some procs for 65 to 80 damage, it does feel around 1 in 100.

The procs do not show in the combat log, unfortunately.
