### ISSUE TITLE
warlock`s task of  Summon Succubus

### ISSUE THREAD

**Issue by jeffnantong** [slowtorta/turtlewow-bug-tracker#4805]
**Please, provide a clear description what the bug is:**

**Steps to reproduce the behavior with as much detail as possible:**

1.i forget to take  warlock`s career task in a suitable grade,now i am 60 ,i could`t get the task of Summon Succubus
2. there is no such task nethier in AG nor in UA
3. there is no such exclamation in the warlock train area

**IDs of affected creatures, items, quests or spells with a link to the relevant page:**

NPC: https://database.turtle-wow.org/?npc=
Item: https://database.turtle-wow.org/?item=
Quest: https://database.turtle-wow.org/?quest=
Spell: https://database.turtle-wow.org/?spell=
Object: https://database.turtle-wow.org/?object=

**Expected behavior. Describe how it should work:**

**Comment by Muigin** [comment]
Cannot reproduce.  Please be sure you did not start one part of the quest chain and leave off somewhere in the middle.  This means you will likely have to go to each NPC on each step of the quest (refer to Classic WoWhead) to find what part of the quest you left off on.

Working as intended.
