### ISSUE TITLE
Ornate Bloodstone Dagger does not work with damage proc items.

### ISSUE THREAD

**Issue by OonaFae** [slowtorta/turtlewow-bug-tracker#4809]
Since the Ornate Bloodstone Dagger shares the same text with Blade of Eternal Darkness it should be able to proc off of additional damage items such as Thunder Lizard's Hide, Incendosaur Set, Repaired Electro-Lantern, Ring of Electrical Binding.

However it does not.

I have tested it and the weapon seems to be working on spellcasts but not on these proc effects.

Testing:
Equip Bloodstone Dagger and a number of proc items. 
Attack Mob, see the procs applying but the mob never takes additional damage nor do you receive damage from the Dagger proc

Attack the same mob using a spell such as Wrath/Lightning Bolt/Frostbolt
See the dagger drain HP and apply additional damage.

**Comment by Muigin** [comment]
Duplicate, linking to previous issue.
#4802
