### ISSUE TITLE
Player/Officer's Guild Note Entry Swapped

### ISSUE THREAD

**Issue by perl1743** [slowtorta/turtlewow-bug-tracker#481]
**Please, provide a clear description what the bug is:**
Entering a note into the Officer's Note prompt applies it to the regular Note
(and entering a note into the regular note prompt applies it to the Officer's Note.)
Thanks for fixing notes in larger guilds but there's a small issue. (This happened in a guild with 559 members, haven't tested smaller guilds)
![image](https://user-images.githubusercontent.com/2818608/143611584-2abf3eac-79ad-44f2-8a7e-c9d1680fe69d.png)
![image](https://user-images.githubusercontent.com/2818608/143611557-e04d8339-2442-42d3-a434-1e385d329679.png)

**Steps to reproduce the behavior with as much detail as possible:**
1. Try entering officer's notes or regular notes
2. Check where they end up

**IDs of affected creatures, items, quests or spells with a link to the relevant page:**
N/A

**Expected behavior. Describe how it should work:**
Officer's Note Prompt -> Officer's Note
Player Note Prompt -> regular Note

**Comment by jameyboor** [comment]
Fixed on next update.
