### ISSUE TITLE
Karazhan enchant dont work

### ISSUE THREAD

**Issue by Stealsik** [slowtorta/turtlewow-bug-tracker#4810]
**Please, provide a clear description what the bug is:**
Karazhan enchant ( Invocation of Shattering ) i cant use on legs or head slot items
**Steps to reproduce the behavior with as much detail as possible:**

1.
2. 
3. 

**IDs of affected creatures, items, quests or spells with a link to the relevant page:**

NPC: https://database.turtle-wow.org/?npc=
Item: https://database.turtle-wow.org/?item=
Quest: https://database.turtle-wow.org/?quest=
Spell: https://database.turtle-wow.org/?spell=
Object: https://database.turtle-wow.org/?object=

**Expected behavior. Describe how it should work:**

**Comment by Muigin** [comment]
This is known and requires a spell tweak.  Will be fixed in a future maintenance.  ETA unknown.
#4814
