### ISSUE TITLE
"A Dusty Tome" object doesn't appear to spawn in Dire Maul East

### ISSUE THREAD

**Issue by ChiefMoose** [slowtorta/turtlewow-bug-tracker#4811]
[A Dusty Tome](https://www.wowhead.com/classic/object=179547/a-dusty-tome) doesn't appear to be spawning on the ground in Dire Maul East, is this intended? 

Steps to Repo:
1. Spawn into Dire Maul East 
2. Check known spawn locations for A Dusty Tome
3. Reset instance

Expected behavior:
Books should have a chance to spawn on the ground in Dire Maul East (and maybe other zones)

**Comment by vkekd** [comment]
The dusty tome always spawns once per instance but keep in mind that DMW, DMN and DME counts as the same instance

**Comment by ChiefMoose** [comment]
Okay, thanks for the clarification I didn't know that, I'll close this out.
