### ISSUE TITLE
Elemental Focus does not work

### ISSUE THREAD

**Issue by Bluecow89** [slowtorta/turtlewow-bug-tracker#4812]
**Please, provide a clear description what the bug is:**
Elemental Focus does not give mana reduction when elemental spell is used
**Steps to reproduce the behavior with as much detail as possible:**

1. Get a crit & proc Elemental focus
2. Use an elemental spell and see Elemental focus buff be removed
3. Notice that the mana reduction on the spell is not happening

**IDs of affected creatures, items, quests or spells with a link to the relevant page:**

Well the database is shut down rn but it is the elemental shaman talent.

**Expected behavior. Describe how it should work:**
When you proc Elemental focus & use a elemental spell it should cost 40% / 80% less mana

**Comment by Muigin** [comment]
#4770
