### ISSUE TITLE
Invocation of Greater Protection - don't work on legs or head.

### ISSUE THREAD

**Issue by Tobbsu** [slowtorta/turtlewow-bug-tracker#4814]
1. Quest works fine now you can retake it. +1
2. Quest Item: Invocation of Greater Protection:
 * Don't not work on the legs or head if you try you get text "That item is not a valid target". -1

**Comment by Muigin** [comment]
This is known and requires a spell tweak.  Will be fixed in a future maintenance.  ETA unknown.
#4810

**Comment by 0Moon01** [comment]
I believe this was an issue of them missing the Miscellaneous item class mask. Testing to make sure.
