### ISSUE TITLE
亚服血环服务器工程专业bug问题

### ISSUE THREAD

**Issue by laze3695** [slowtorta/turtlewow-bug-tracker#4816]
**Please, provide a clear description what the bug is:**

**Steps to reproduce the behavior with as much detail as possible:**

1.我需要反应我的工程bug问题，不能学习传送装置  请问怎么解决啊
2. 我工程专业侏儒专精遗忘专业之后，重新学习了地精专精，NPC不能学习致密炸药，不能学习传送装置。
3. 

**IDs of affected creatures, items, quests or spells with a link to the relevant page:**

NPC: https://database.turtle-wow.org/?npc=
Item: https://database.turtle-wow.org/?item=
Quest: https://database.turtle-wow.org/?quest=
Spell: https://database.turtle-wow.org/?spell=
Object: https://database.turtle-wow.org/?object=

**Expected behavior. Describe how it should work:**

**Comment by wynnlol** [comment]
我工程洗了也出BUG了，75就封顶了，不让学中级，哎，也不知道什么时候能解决

**Comment by Muigin** [comment]
请用英文提交问题。我们无法通过自动翻译准确地翻译中文提交的错误报告，这使得我们难以理解问题的确切性质。谢谢！

Please submit the issues in English. We're unable to accurately translate bug reports submitted in Chinese through automatic translation, which makes it difficult for us to understand the exact nature of the issue. Thank you!
