### ISSUE TITLE
The Bloody Belt Buckle is bugged when applied to other people's belts.

### ISSUE THREAD

**Issue by YeahWhiplash** [slowtorta/turtlewow-bug-tracker#4817]
The Bloody Belt Buckle is bugged when applied to other people's belts.

Was reported in this thread earlier today and a link to an earlier issue 2 weeks ago.
https://github.com/slowtorta/turtlewow-bug-tracker/issues/4583

**Comment by Muigin** [comment]
Please do not make duplicate bug reports.
