### ISSUE TITLE
My equipment attributes display error

### ISSUE THREAD

**Issue by linhaitingchao** [slowtorta/turtlewow-bug-tracker#4818]
**Please, provide a clear description what the bug is:**
My chest armor displays incorrect attributes
**Steps to reproduce the behavior with as much detail as possible:**

1.My game ID is Yangyoujicn
2. The first attribute of the breastplate
![微信截图_20231019021739](https://github.com/slowtorta/turtlewow-bug-tracker/assets/148379249/e3213600-6a4d-4bf8-841f-4f2bc316ec32)
 should be 2 critical strikes, with an error displaying that the attack ignores the target's 35 armor.
3. 

**IDs of affected creatures, items, quests or spells with a link to the relevant page:**

NPC: https://database.turtle-wow.org/?npc=
Item: https://database.turtle-wow.org/?item=61275
Quest: https://database.turtle-wow.org/?quest=
Spell: https://database.turtle-wow.org/?spell=
Object: https://database.turtle-wow.org/?object=

**Expected behavior. Describe how it should work:**

**Comment by Muigin** [comment]
#4823 
#4822 
#4819 

This item is working as intended. Please remember that addons do not accurately track your stats that are not displayed in addon-free WoW, as they do NOT pull data from the server, but rely on  a comprehensive pre-programmed library of items and buffs. Likewise, the critical chance displayed on the Attack spell is not an accurate reflection of your actual critical chance.

This item uses the vanilla spell that gives 2% crit such as Foror's Eyepatch, Hunter Tier3 Helm, and a number of other epic items. We will try to make clientside adjustments that will better reflect this, and we encourage you to reach out to the makers of the stats addons to update their LUAs with the new content.

Working as intended.
