### ISSUE TITLE
Item stats bug

### ISSUE THREAD

**Issue by Emmaris9** [slowtorta/turtlewow-bug-tracker#4819]
Hello. On 18.10.23 in morning i got from Karazan 10 man Moroes drop [Breastplate of Earthen Might]
The item shows that it give 2 % crit but its not count in my hero.
![bugturtle](https://github.com/slowtorta/turtlewow-bug-tracker/assets/148383745/7034c32b-65ed-4f94-978c-5666847dbb01)

**Comment by tbone2311** [comment]
Also have this bug and item stats are not displayed correctly

**Comment by Muigin** [comment]
This item is working as intended. Please remember that addons do not accurately track your stats that are not displayed in addon-free WoW, as they do NOT pull data from the server, but rely on  a comprehensive pre-programmed library of items and buffs. Likewise, the critical chance displayed on the Attack spell is not an accurate reflection of your actual critical chance.

This item uses the vanilla spell that gives 2% crit such as Foror's Eyepatch, Hunter Tier3 Helm, and a number of other epic items. We will try to make clientside adjustments that will better reflect this, and we encourage you to reach out to the makers of the stats addons to update their LUAs with the new content.

Working as intended.
