### ISSUE TITLE
Goblin sheathe/unsheathe animation does not work correctly 

### ISSUE THREAD

**Issue by Reddykjp1617** [slowtorta/turtlewow-bug-tracker#4820]
**Please, provide a clear description what the bug is:**

Weapons/shields do not sheathe/unsheathe when pressing the button to do so. 

**Steps to reproduce the behavior with as much detail as possible:**

1. Equip a weapon and shield (or a two hander) as a Goblin
2. Press your sheathe button (Z by default to equip and unequip)

**Expected behavior. Describe how it should work:**

Item should be in characters hands once the button is pressed. Item is instead in sheathe mode, if a shield is equipped, shield is also stuck in equipped position (stuck from being in combat) or stuck on characters back until combat is initiated.

**Comment by slowtorta** [comment]
This will be adressed in the patch 1.7.1: https://forum.turtle-wow.org/viewtopic.php?f=63&t=10910
