### ISSUE TITLE
Breastplate of earthen might is bugged

### ISSUE THREAD

**Issue by Icfre** [slowtorta/turtlewow-bug-tracker#4823]
**Please, provide a clear description what the bug is:**
Equipping breastplate of earthen might is not granting 2% crit.

**Steps to reproduce the behavior with as much detail as possible:**

1.  Equip Breastplate of earthen might
2.  Notice % chance to crit is not changing
3. 

**IDs of affected creatures, items, quests or spells with a link to the relevant page:**

NPC: https://database.turtle-wow.org/?npc=
Item: https://database.turtle-wow.org/?item=
Quest: https://database.turtle-wow.org/?quest=
Spell: https://database.turtle-wow.org/?spell=
Object: https://database.turtle-wow.org/?object=

![image](https://github.com/slowtorta/turtlewow-bug-tracker/assets/148420922/b6705d65-8723-490d-ac10-a5df0998d4d6)
![image](https://github.com/slowtorta/turtlewow-bug-tracker/assets/148420922/7fb43bfa-21f3-43bb-b815-8fc805f866ee)
![image](https://github.com/slowtorta/turtlewow-bug-tracker/assets/148420922/ffbc94db-8e59-4292-b3c4-d29ce5ec5fcd)

**Expected behavior. Describe how it should work:**

**Comment by Muigin** [comment]
This item is working as intended. Please remember that addons do not accurately track your stats that are not displayed in addon-free WoW, as they do NOT pull data from the server, but rely on  a comprehensive pre-programmed library of items and buffs. Likewise, the critical chance displayed on the Attack spell is not an accurate reflection of your actual critical chance.

This item uses the vanilla spell that gives 2% crit such as Foror's Eyepatch, Hunter Tier3 Helm, and a number of other epic items. We will try to make clientside adjustments that will better reflect this, and we encourage you to reach out to the makers of the stats addons to update their LUAs with the new content.

Working as intended.
