### ISSUE TITLE
quest bug

### ISSUE THREAD

**Issue by jiaweixuvincet** [slowtorta/turtlewow-bug-tracker#4825]
**Please, provide a clear description what the bug is:**

**Steps to reproduce the behavior with as much detail as possible:**

1.I got the quest :taming the beast, which is using the rod to tame a large crag boar, but the rod is unusable item. it doest let me click it. anyone can help me out, BTW it is Gnome hunter.
2. 
3. 

**IDs of affected creatures, items, quests or spells with a link to the relevant page:**

NPC: https://database.turtle-wow.org/?npc=claover spinpistol
Item: https://database.turtle-wow.org/?item=taming rod
Quest: https://database.turtle-wow.org/?quest=taming the beast
Spell: https://database.turtle-wow.org/?spell=
Object: https://database.turtle-wow.org/?object=using the rod on the boar

**Expected behavior. Describe how it should work:**

**Comment by ratkosrb** [comment]
![WoWScrnShot_101923_154256](https://github.com/slowtorta/turtlewow-bug-tracker/assets/35845488/e8030c28-0102-4081-a00b-08cf26f5bd6c)

Unable to reproduce the issue. Try clearing your cache.

**Comment by jiaweixuvincet** [comment]
here is the issue, 
![Screenshot (1)](https://github.com/slowtorta/turtlewow-bug-tracker/assets/148425597/13e81c9e-c694-4221-9fdc-984fc9ab73c4)
need help

**Comment by ratkosrb** [comment]
Delete the WDB folder and check again.

**Comment by slowtorta** [comment]
Your client is outdated. Please download a new version from our website.
