### ISSUE TITLE
The character "自由" encountered a bug and his rank was not settled

### ISSUE THREAD

**Issue by yummyza** [slowtorta/turtlewow-bug-tracker#4826]
**Please, provide a clear description what the bug is:**
The character "自由" encountered a bug and his rank was not settled

**Steps to reproduce the behavior with as much detail as possible:**

The character "自由" encountered a bug and his rank was not settled.
After the restart on Wednesday, October 18th, everyone else has updated their ranks.
However, my honorary rank has not been updated.
I completed 280 honor kills in the last week (between Oct 11th and Oct 18th).
I am permanently parked at RANK 3, which was settled on October 11th.
Server: Ring of Blood
Character Name: 自由
Evidence: In-game screenshot
https://img.kookapp.cn/assets/2023-10/frJtLCewNd1hc0u0.png

![frJtLCewNd1hc0u0](https://github.com/slowtorta/turtlewow-bug-tracker/assets/148425615/e2b797e9-5c07-484a-9682-f561e2e435ac)

**Comment by Muigin** [comment]
Please make a ticket in-game to a GM. The bugtracker is reserved for universal bugs that can be reproduced.

**Comment by yummyza** [comment]
> Please make a ticket in-game to a GM. The bugtracker is reserved for universal bugs that can be reproduced.

However, GMs ingame replied with an email for us to come here to bugtracker to submit this bug.
The Asian GMs are kicking each other around and don't care about the players at all.
This is a bit disappointing for us players.

After the Asian players encountered the bug.
There is nowhere to go and no one to fix it.

**Comment by GrizB37** [comment]
You're level 19, you can not rank past Rank 3... The ranks have level requirements. Not a bug.
