### ISSUE TITLE
Unable to apply Invocation of Shattering to t3 pieces.

### ISSUE THREAD

**Issue by Illasei** [slowtorta/turtlewow-bug-tracker#4828]
When attempting to apply the new armor penetration enchant called "Invocation of Shattering" to my newly acquired tier 3 Bonescythe Helmet and Bonescythe Legplates the game refuses to do so and instead prompts the red error text "That is an invalid target."

The items in question have never been enchanted with anything else. My personal best guess as to why this bug occurs is that since the tier 3 pieces are acquired from a quest reward they do not have a level requirement on them. The enchant however has a level requirement of lvl 58. Does this perhaps mean that the enchant is unable to be applied since it doesn't recognize the tier 3 pieces of being high enough level?

I am assuming this is meant to be a high level enchant and should be applicable to end game gear like tier 3. Personally I consider this enchant amazing for rogues hence why I was attempting to put it on my best in slot helm and legs.

That is all! Have a nice day to whoever reads this. :)

**Comment by Muigin** [comment]
#4788
