### ISSUE TITLE
[AQ40] Anubisath Defender, Sentinel, Warder AND Obsidian Eradicator & Obsidian Nullifier should all drop Large Obsidian Chunks for mining upon death

### ISSUE THREAD

**Issue by faralynn** [slowtorta/turtlewow-bug-tracker#483]
As it is now, Obsidian Chunks can ONLY be mined in AQ20. This is not how it should be and has caused a major drought on Large Obsidian Shards. 

The following is proof pictures & video from WoW Classic where these mobs DO drop those nodes on death:

![image](https://user-images.githubusercontent.com/2092314/143656639-88982181-e905-4353-9544-77371b4eab16.png)
_under the threat meter, AQ40 Anubisaths before Skeram on the ramp_

![image](https://user-images.githubusercontent.com/2092314/143656662-320e8505-6f00-4f29-b31d-562d56ed98bb.png)
_closeup. Yep, in this grainy JPG we see not a UFO but an Obsidian Chunk, ready and waiting to be mined._

Video the above two pics are from:
https://www.youtube.com/watch?v=oq9WvcTvZGk&t=790s

![image](https://user-images.githubusercontent.com/2092314/143656763-7be11670-5ee9-4169-baf0-f7654df7f19b.png)
_Screenshot of an Anubisath dying. Nothing there right? Wait until the next frame below.._

![image](https://user-images.githubusercontent.com/2092314/143656786-680d3568-1174-47c5-a2af-ec503ffd4f6b.png)
_Right there it is. Right at his fist._

![image](https://user-images.githubusercontent.com/2092314/143656840-4c4ef922-ec2e-44eb-b4de-5071a1c77584.png)
_Dead Obsidian Eradicator right here with the Node protruding from the ground a little above the Battle Shout icon_

Video the above picture is from:
https://www.youtube.com/watch?v=czNs5L2LQ4M

------

Misc links to ancient comments stating that these mobs should drop mining nodes on death:

https://classic.wowhead.com/item=22203/large-obsidian-shard#comments
http://web.archive.org/web/20060616193926/http://thottbot.com/?i=53172

**Comment by sewlek** [comment]
would be very nice if this could get fixed
