### ISSUE TITLE
Grifter's Boots should be Bind on Equipped

### ISSUE THREAD

**Issue by Saviorr** [slowtorta/turtlewow-bug-tracker#4830]
**Please, provide a clear description what the bug is:**
Hello GM, Grifter's Boots should be BoE  just like the rest of their items... not Bind on Pickup (BoP)

**Steps to reproduce the behavior with as much detail as possible:**

1. when crafting Grifter's Boots it bind on pickup (soulbounded) but not Bind on Equips
2. 
3. 

**IDs of affected creatures, items, quests or spells with a link to the relevant page:**

NPC: https://database.turtle-wow.org/?npc=
Item: https://database.turtle-wow.org/?item=
Quest: https://database.turtle-wow.org/?quest=
Spell: https://database.turtle-wow.org/?spell=
Object: https://database.turtle-wow.org/?object=

**Expected behavior. Describe how it should work:**
Change Bind on Pickup to Bind on Equip on Grifter's Boots

**Comment by cyaohiri** [comment]
This is intended. See #1805.
