### ISSUE TITLE
Invocation of Shattering unusable on Darkflame Helm

### ISSUE THREAD

**Issue by n1gh8w0lf** [slowtorta/turtlewow-bug-tracker#4831]
"Invocation of Shattering" unusable on "Darkflame Helm"

gives an error message "That item is not a valid target."

Also "Breastplate of Earthen Might" is missing 2% critical chance but has arp twice (35 and 50)
same with "Tooth of the Packlord" has arp values twice (50 and 100)

**Comment by ratkosrb** [comment]
This was already fixed server side, but it requires a client side update.
https://github.com/slowtorta/turtle-wow/commit/97058c5a8b21ca3f46fab3f41c7cfc47415a919d
https://github.com/slowtorta/turtlewow-bug-tracker/issues/4705
