### ISSUE TITLE
Reopen - Vampirism Does Not Scale

### ISSUE THREAD

**Issue by XandyCode** [slowtorta/turtlewow-bug-tracker#4836]
This references a previously closed and unresolved issue: https://github.com/slowtorta/turtlewow-bug-tracker/issues/4497#issue-1925379014

**Please, provide a clear description what the bug is:**
Equipping multiple pieces of gear with the Vampirism stat does not increase the percentage healed.

**Steps to reproduce the behavior with as much detail as possible:**

1. Equip multiple pieces of Vampirism gear (eg 2x Darkmoon Ring, Bracers with Vampirism Enchant )
2.  Enter combat and take damage 
3.  Deal damage and observe differences in life total to calculate amount healed.

**Expected behavior. Describe how it should work:**

Equipping multiple pieces of gear should increase the amount healed. 

The below tests were run on a warrior, using bloodrage to self inflict damage and to enter combat disabling regen.
Calculations were done using real health numbers.

Test 1 :
1x Darkmoon Ring Equipped (2% total)
Mele Swing for 309, health goes from 3432 to 3438. Expected heal for 6, heals for 6 (2% healing as expected)

Test 2:
2x Darkmoon ring equipped (4% total)
Mele swing for 342, health goes from 3532 to 3538. Expected heal for 13, heals for 6 (only 2%, should be 4%)

Test 3:
2x Darkmoon + Vampirism Brace (5% total)
Mele swing for 332, health goes from 3632 to 3635 expected heal for 16, heals for 3 (1% total)

With the results from test 3, it seems different pieces of gear are overwriting vampirism in other gear slots, effectively nullifying vampirism on other pieces of gear.

**Comment by dkmnllth** [comment]
Can confirm this. On my paladin, with 8% vampirism equipped, I am only getting the effects of 2% vampirism from my highest vampirism item. A Holy Shock crit that deals 1k damage is only giving me 20 health, which lines up with a 2% vampirism rate.
