### ISSUE TITLE
Quest [Race Against Time!] and other Race in Thousande Neddle

### ISSUE THREAD

**Issue by hokagegaara** [slowtorta/turtlewow-bug-tracker#4838]
Quest [Race Against Time!] and other Race in Thousande Neddle
I complete the race and I have 5-20 seconds left, I just don’t have time to turn in the quest because it is canceled even though the conditions have been met.
Also, 2-4 times I had a bug/lag/ping related to the fact that I did not have time to pass the quest due to the fact that the communication interface did not open or took a long time to respond.

I think it’s better if the quest auto-completes and you get a gift for your character right away or by mail if the inventory slots are occupied.
1-2s not enough to reach the finish line but after finish im have 10seconds and use [Aspect of the Cheetah]
https://cdn.discordapp.com/attachments/484376201272754176/1164765839719927868/WoWScrnShot_102023_062205.png
https://cdn.discordapp.com/attachments/484376201272754176/1164765844467875890/WoWScrnShot_102023_062206.png
https://cdn.discordapp.com/attachments/484376201272754176/1164765845281574952/WoWScrnShot_102023_062209.png
Also the finish is too far from the finish flag.

**Comment by slowtorta** [comment]
Duplicate report.
