### ISSUE TITLE
PVP Warlock able to kill players in Ratchet and not getting aggro by Guards

### ISSUE THREAD

**Issue by Smerpazoid** [slowtorta/turtlewow-bug-tracker#4840]
**Please, provide a clear description what the bug is:**

Warlock DoT's are able to be applied to opposing faction players that have PVP enabled in Ratchet without the guards aggroing to the caster. I don't know if it's exclusively warlock DoTs or if other classes can do this too. Curse of Agony, Corruption, Siphon Life are ones I tried and the goblin guards did not aggro to me at all. I do not know if this is unique to ratchet or if all goblin guards react this way.

**Steps to reproduce the behavior with as much detail as possible:**

1. Apply Curse of Agony/Corruption/Siphon Life on opposing faction player with PVP on in Ratchet
2. They die.
3. Guards do not aggro to the caster.

**IDs of affected creatures, items, quests or spells with a link to the relevant page:**

The turtlewow database is not accessible.

**Expected behavior. Describe how it should work:**

The guards should aggro like when attacking other players in a town as normal.

**Comment by twowTurtReynolds** [comment]
Works fine from here.
![image](https://github.com/slowtorta/turtlewow-bug-tracker/assets/151180101/e054896d-6e2c-4e7b-a6c6-d33aa1e82593)
And here:
![image](https://github.com/slowtorta/turtlewow-bug-tracker/assets/151180101/17e5800b-f7ad-4c81-95ec-e0e518c5ae55)

This is a safespot, just like in 1.12:
![image](https://github.com/slowtorta/turtlewow-bug-tracker/assets/151180101/959fee75-6c43-4d9b-b447-6557af41da7b)

But it has nothing to do with class specific spells:
![image](https://github.com/slowtorta/turtlewow-bug-tracker/assets/151180101/92bdaed5-e638-43f9-8b28-60a6bce107ad)
