### ISSUE TITLE
Ingame quest bug

### ISSUE THREAD

**Issue by imKevinFlynn** [slowtorta/turtlewow-bug-tracker#4841]
Hi there , i have some issue with quest and hope you can resolve this.

**Please, provide a clear description what the bug is:**

**Steps to reproduce the behavior with as much detail as possible:**

1. Quest in Yojamba Isle called "Paragons of power: The Illusionist's Robes" , quest database link - https://database.turtle-wow.org/?quest=8069.

**IDs of affected creatures, items, quests or spells with a link to the relevant page:**

NPC name: Al'tabim the All-Seeing
Item: Primal Hakkari Kossac (token) 
Quest: https://database.turtle-wow.org/?quest=8069

**Expected behavior. Describe how it should work:**

I have honored rep with Zandalarian Tribe and the token called Primal Hakkari Kossac that i should turn into The Illusionist's Robe from the quest Paragons of power, but i just cant do it for some reason. I cleared WDB folder, tried reload the game, also tried abandon the quest multiple times , but it doesn't help. I applied the screenshot to this msg , so you can see, just cant press continue even with honor rep and token in my pocket.
![Quest-bug](https://github.com/slowtorta/turtlewow-bug-tracker/assets/109181298/3574a132-573c-47b4-8eff-24500b244d85)

**Comment by Zmitrok1984** [comment]
But you need to be Revered with Zandalary for that quest 
https://www.wowhead.com/classic/quest=8069

**Comment by imKevinFlynn** [comment]
I got it , it show's current rep/ needed rep :D , sorry my bad here.
