### ISSUE TITLE
lootwindow empty fishing

### ISSUE THREAD

**Issue by Kodama420** [slowtorta/turtlewow-bug-tracker#4842]
**Please, provide a clear description what the bug is:**
Lootwindow while fishing being empty without fish got away message
**Steps to reproduce the behavior with as much detail as possible:**

1. Trying to fish Nightfin / Sunscale with fishing 230 + 20 + 100 = 350 
2. Every other fish i can loot 
3. 

**IDs of affected creatures, items, quests or spells with a link to the relevant page:**

NPC: https://database.turtle-wow.org/?npc=
Item: https://database.turtle-wow.org/?item=
Quest: https://database.turtle-wow.org/?quest=
Spell: https://database.turtle-wow.org/?spell=
Object: https://database.turtle-wow.org/?object=

**Expected behavior. Describe how it should work:**

**Comment by OonaFae** [comment]
Experienced this as well while fishing in Hyjal
![image](https://github.com/slowtorta/turtlewow-bug-tracker/assets/105398809/7ee3a6ed-2ac2-4f8f-9032-e33527e6c6b4)

**Comment by SaxxonPike** [comment]
This is happening in Moonglade as well.

**Comment by ratkosrb** [comment]
Fishing Nightfin and Sunscale in Kalimdor should be fixed after the next update.
