### ISSUE TITLE
Shimmering Flats race quests still not working

### ISSUE THREAD

**Issue by Dualityz** [slowtorta/turtlewow-bug-tracker#4845]
**Please, provide a clear description what the bug is:**

The Shimmering Flats basic quests "Gnomes are genuine inventors" & "Goblin Engineering at its Finest" arent working.
No dialogue option are available from Dolores.

**Steps to reproduce the behavior with as much detail as possible:**

1. Accept both quests
2. Talk to Dolores
3. No dialogue.

**IDs of affected creatures, items, quests or spells with a link to the relevant page:**

Can't provide this as the DB isn't open due to patch.

NPC: Dolores ( race starter girl )
Quest: Gnomes Are Genuine Inventors and Goblin Engineering At Its Finers

**Expected behavior. Describe how it should work:** 

Dialogue should be available to pop you into a car, Gnome or Goblin. I saw several players getting popped into cars from the other NPC, Daisy, for the following quests; it's probably just Dolores that's bugged for these quests.

**Comment by Muigin** [comment]
Added to #4813
