### ISSUE TITLE
Could not loot item after roll timer timed out.

### ISSUE THREAD

**Issue by Dark-Medicine** [slowtorta/turtlewow-bug-tracker#4846]
**Please, provide a clear description what the bug is:**Could not loot item after roll timer timed out.

**Steps to reproduce the behavior with as much detail as possible:**

1.We wiped after killing boss 4/5 people rolled on item and when we got back to dungeon the roll timer timed out. 5th person never rolled when trying to loot boss i got "item is still being rolled for" message within 30 seconds the boss despawned.
2. Was in ShadowFang Keep on Wolf Master Nandos boss. Item Drop was the Claw of Nandos I was the only person to need roll.
3. Turtle Wow Database is down for the update, cannot provide ID numbers.

**IDs of affected creatures, items, quests or spells with a link to the relevant page:**

NPC: https://database.turtle-wow.org/?npc=
Item: https://database.turtle-wow.org/?item=
Quest: https://database.turtle-wow.org/?quest=
Spell: https://database.turtle-wow.org/?spell=
Object: https://database.turtle-wow.org/?object=

**Expected behavior. Describe how it should work:**Auto pass on 5th person that did not roll for item.

**Comment by twowTurtReynolds** [comment]
Blisslike, Boss corpses last quite a bit to avoid this problem. I'm sorry that you were hit by this bug and lost the drop.
