### ISSUE TITLE
[Naxxramas] Kel'thuzad's Phase 3 adds -- Guardians of Icecrown, should NOT be immune to Turn Undead, Frost Trap, Goblin Rocket Helm, Stun nor Taunt

### ISSUE THREAD

**Issue by faralynn** [slowtorta/turtlewow-bug-tracker#485]
I do not have verification on Taunt working or not, but I have spoken to Paladin's that tried to use Turn Undead on them and they said they were immune.

This is not working as intended. Please see the video below:

https://clips.twitch.tv/SilkyRudeDragonfruitTebowing

Please also see the following discussions on Reddit discussing strategies for dealing with these adds:
https://www.reddit.com/r/classicwow/comments/ktsw7b/top_10_naxx_speed_runs_as_of_today/giomfpd/
https://www.reddit.com/r/classicwow/comments/kvfhtv/question_about_kelthuzad_adds/

Quotes of interest:
![image](https://user-images.githubusercontent.com/2092314/143669734-bff706b3-168f-4713-a7e0-194076a65749.png)
![image](https://user-images.githubusercontent.com/2092314/143669740-6d4aed9d-3b56-4377-bf0e-c23deb6da365.png)
![image](https://user-images.githubusercontent.com/2092314/143669749-69f5bfa9-b9a4-4423-8d99-9ba8149c810b.png)
_The only false claim here is Magic Dust_

_PS: I'd have asked the Paladins that relayed to me that Turn Undead didn't work if taunt worked as well but they do not have one. (:_

**Comment by slowtorta** [comment]
Fixed. Please let me know if some of the effects are still not getting through thr immune mask.
