### ISSUE TITLE
Unable to fish Raw Nightfin Snapper in Feralas since 1.17 patch release

### ISSUE THREAD

**Issue by Drazsee** [slowtorta/turtlewow-bug-tracker#4850]
**Please, provide a clear description what the bug is:**

Since the new 1.17 patch release I am unable to fish Raw Nightfin Snappers in Feralas. My used to go spot from before patch was the lake under Gorduni Outpost. For a 50 min fishing with 400 skill what i got:

- 5x Raw Whitescale Salmon
- 7x Raw Mithril Head Trout
- 13x Oily Blackmouth
- 31x Raw Redgill
- 7x Raw Rockscale Cod
- 35x Raw Spotted Yellowtail
- 4x Winter Squid
- 13x Firefin Snapper
- 15x Stonescale Eel
- 7x Big-mouth Clam
- 10x Raw Glossy Mightfish
- 3x Mithril Bound Trunk
- 2x Rumsey Rum Black Label
- around 15x catch without loot window and error message, but with loot window open sound, couldn't loot it
- **0x Raw Sunscale Salmon**
- **0x Raw Nightfin Snapper**

Server time was: 7:15-8:15 am

In 1.16 patch i got around ~10 Raw Sunscale Salmon and ~10 Raw Nightfin Snapper, same server time.

**Steps to reproduce the behavior with as much detail as possible:**

1.Exact spot: Feralas lake under Gordunni Post, right where it turns into a river.
2. Fishing skill: 300 base skill + 25 skill from Nat Pagle's Extreme Angler FC-5000 + 75 skill from Bright Baubles = total 400 skill
3. 

**IDs of affected creatures, items, quests or spells with a link to the relevant page:**

NPC: https://database.turtle-wow.org/?npc=
Item: https://database.turtle-wow.org/?item=
Quest: https://database.turtle-wow.org/?quest=
Spell: https://database.turtle-wow.org/?spell=
Object: https://database.turtle-wow.org/?object=

**Expected behavior. Describe how it should work:**
In this time period, i should be able to catch Raw Sunscale Salmon and Raw Nightfin Snapper in Feralas.

**Comment by Muigin** [comment]
#4530

**Comment by Hajache** [comment]
Same bug at diferents maps l
