### ISSUE TITLE
Glyph of the Honorless

### ISSUE THREAD

**Issue by Lichbanez** [slowtorta/turtlewow-bug-tracker#4852]
This glyph is present in the database but not in game or at least I can't find it anywhere.

ITEM: https://database.turtle-wow.org/?item=50746

There's an announcement on discord by Torta dated 16/02/2022 who said "Added Glyph of the Honorless for players who do not want to be part of PvP standing, yet still want to PvP for fun" so it should be in the glyph vendor but it isn't.

**Comment by Lichbanez** [comment]
Any news? I keep getting honor and therefore the unremovable PvP title on my characters just by being grouped with warmode people in PvE.

**Comment by twowTurtReynolds** [comment]
Please do not waste your time in the DB, there are countless things in there that are never implemented, or deprecated. Also, do not post bug reports before asking the community on how to achieve your goal. They would have told you that NPCs do this for you:

![image](https://github.com/slowtorta/turtlewow-bug-tracker/assets/151180101/759e02f3-6af6-4fa9-a8be-8f47ba4a3e2a)

**Comment by Lichbanez** [comment]
But this was implemented and then removed without a reason, I tried to gather information about it in the game but no-one answered. I only found a guy who claimed to have used it back then and that the effect has remained active to this day (no kills or honor gains in PvP) and that's exactly what I'd like.
