### ISSUE TITLE
The Pumpkin Thieves [8] seems to be bugged at 6/7 drops

### ISSUE THREAD

**Issue by Mamekuma** [slowtorta/turtlewow-bug-tracker#4855]
**Please, provide a clear description what the bug is:**

**Steps to reproduce the behavior with as much detail as possible:**

1. Killed gnolls in Forest's Edge for a few minutes to get 6/7 pumpkins
2. Killed gnolls for an additional 20+ minutes, but it's not dropping--appears to be bugged, or I'm the most unluckiest paladin on the server
3. no profit :(

**IDs of affected creatures, items, quests or spells with a link to the relevant page:**

NPC: https://database.turtle-wow.org/?npc= 
Item: https://database.turtle-wow.org/?item=
Quest: https://database.turtle-wow.org/?quest=
Spell: https://database.turtle-wow.org/?spell=
Object: https://database.turtle-wow.org/?object=

**Expected behavior. Describe how it should work:**

**Comment by cyaohiri** [comment]
Gnolls north of the Stone Cairn Lake can drop them, but you can also look them from the ground there. If you can't, abandon and retake the quest. That should fix it.

**Comment by Muigin** [comment]
Pumpkins are both drops and lootable from pumpkin objects littering the gnoll camps.  Likewise, cannot reproduce gnolls no longer dropping pumpkins at 6 of 7.

Working as intended.

**Comment by Mamekuma** [comment]
> Gnolls north of the Stone Cairn Lake can drop them, but you can also loot them from the ground there. If you can't, abandon and retake the quest. That should fix it.

Ah, yup, if I just followed the pfQuest to the north I would've had this done ages ago. Thank you everyone!
