### ISSUE TITLE
The Defias Brotherhood Quest Chain

### ISSUE THREAD

**Issue by Liadelza** [slowtorta/turtlewow-bug-tracker#4856]
**Please, provide a clear description what the bug is:** Next part of quest chain is not given.

**Steps to reproduce the behavior with as much detail as possible:**

1. Take Wiley's Note to Gyran Stoutmantle in Westfall.
2. Take Wiley's Note to Mathias Shaw.
3. 

**IDs of affected creatures, items, quests or spells with a link to the relevant page:**: The database is currently down.

NPC: https://database.turtle-wow.org/?npc= Gryan Stoutmantle
Item: https://database.turtle-wow.org/?item= Wiley's Note
Quest: https://database.turtle-wow.org/?quest= The Defias Brotherhood 
Spell: https://database.turtle-wow.org/?spell=
Object: https://database.turtle-wow.org/?object=

**Expected behavior. Describe how it should work:**  Gryan Stoutmantle should give Wiley's Note and the quest to take the note to Mathias Shaw.

**Comment by twowTurtReynolds** [comment]
![image](https://github.com/slowtorta/turtlewow-bug-tracker/assets/151180101/c674364a-8eae-4a81-86bc-c119200235fe)
Works fine.
