### ISSUE TITLE
NPC use Broken texture "Overwatch Mark I <Protector>"

### ISSUE THREAD

**Issue by hokagegaara** [slowtorta/turtlewow-bug-tracker#4858]
https://www.wowhead.com/classic/npc=3538/overwatch-mark-i
NPC use broken texture "golemharveststage2.m2".
Or rather, they use body texture on head.
https://cdn.discordapp.com/attachments/484376201272754176/1165517645941051432/image.png
https://cdn.discordapp.com/attachments/484376201272754176/1165518130420920320/image.png
https://cdn.discordapp.com/attachments/484376201272754176/1165518130739675156/image.png - Standart not broken texture

**Comment by Muigin** [comment]
This has been fixed and will be pushed in our next client patch (1.17.1)
