### ISSUE TITLE
Shaman talent Nature's Guidance not providing melee or spell hit

### ISSUE THREAD

**Issue by discslack** [slowtorta/turtlewow-bug-tracker#486]
**Please, provide a clear description what the bug is:**
Shaman talent Nature's Guidance not providing melee or spell hit
**Steps to reproduce the behavior with as much detail as possible:**

1. Took 3/3 talent points in nature's guidance
2. Had no hit on gear
3. Character stats showing 0% hit

https://imgur.com/a/vkqEa7n

**IDs of affected creatures, items, quests or spells with a link to the relevant page:**
Talent: https://classic.wowhead.com/spell=16180/natures-guidance

**Expected behavior. Describe how it should work:**
Each point should provide 1% spell hit and melee hit

**Comment by rosen40** [comment]
um, i don't think the Vanilla client shows hit % by default, are you sure its not your addon that is not able to register the hit from talent(s) ?

**Comment by discslack** [comment]
Yes it shows appropriately on my mage with the talents

**Comment by rosen40** [comment]
Yes but its an addon, so it does not prove at all whether server side you do or do not receive the bonus hit. I don't know how the addon works but the way it detects hit % sources might be flawed and not able to pick up Nature's Guidance. The difference is that it affects both melee and spell hit so its a different type of spell effect(s) so the addon might not be able to pick that up. Anyways a dev would have to debug and see if it actually works or not.

**Comment by LeopoldHock** [comment]
The addon display is not enough to confirm this behavior. BetterStats is confirmed to not show other shaman talent effects like e.g. increased crit chance. I'll close this for now. If you include proof that the Hit chance is actually not applied (by doing some tests), I'll reopen.
