### ISSUE TITLE
Problem with textures on shore Gilneas where located Spitecrest Netters

### ISSUE THREAD

**Issue by OYariO** [slowtorta/turtlewow-bug-tracker#4860]
**Please, provide a clear description what the bug is:**

**Steps to reproduce the behavior with as much detail as possible:**

1. Problems with textures
2. Accordingly from 1st have problems with mobs 
3. And spells like (Blink mage's)

**IDs of affected creatures, items, quests or spells with a link to the relevant page:**

NPC: https://database.turtle-wow.org/?npc= Spitecrest Netter
Item: https://database.turtle-wow.org/?item= -
Quest: https://database.turtle-wow.org/?quest= Spitecrest Incursions
Spell: https://database.turtle-wow.org/?spell= mages' blink
Object: https://database.turtle-wow.org/?object= invisible walls ( bug of textures ) 

**Expected behavior. Describe how it should work:**
Just rewatch textures on this shore and fix problems texture's
[Untitled22.zip](https://github.com/slowtorta/turtlewow-bug-tracker/files/13063245/Untitled22.zip)

**Comment by Muigin** [comment]
Duplicate
