### ISSUE TITLE
New Kara Helm / Leg enchants not working on Kara gear

### ISSUE THREAD

**Issue by Geoffrey907** [slowtorta/turtlewow-bug-tracker#4862]
**Please, provide a clear description what the bug is:**

**Steps to reproduce the behavior with as much detail as possible:**

1. Purchased Invocation of Shattering (Armor Pen Enchant from Kara)
2. Tried to use it on "Darkflame Helm" New Armor Pen Helmet from Kara, Does not work i get notified this is not a Valid Target
3. i have cleared my WDB and relogged multiple times

**IDs of affected creatures, items, quests or spells with a link to the relevant page:**

NPC: https://database.turtle-wow.org/?npc=
Item: https://database.turtle-wow.org/?item=
Quest: https://database.turtle-wow.org/?quest=
Spell: https://database.turtle-wow.org/?spell=
Object: https://database.turtle-wow.org/?object=

**Expected behavior. Describe how it should work:**

**Comment by Geoffrey907** [comment]
update the enchant doesnt work on any pieces

**Comment by Muigin** [comment]
Please do not make duplicate reports.
