### ISSUE TITLE
Glyph of the Emerald Bear

### ISSUE THREAD

**Issue by Andcone** [slowtorta/turtlewow-bug-tracker#4864]
**Please, provide a clear description what the bug is:**
- I turned in all the required items in Hyjal to obtain the Glyph of the Emerald Bear from the quest.
- I learned the Glyph of the Emerald Bear from the inventory.
- Glyph of the Emerald Bear activated from the Spellbook.
- Shift into bear form. Character does not appear as Emerald Bear.
- Note: I also have Glyph of the Ice Bear.
- Every time I shift into bear it appear of Ice Bear.
- I have deleted WDB folder multiple times. Restarted game many times.

**Steps to reproduce the behavior with as much detail as possible:**

1. Learn the Glyph of the Emerald Bear located in inventory.
2. Go to Spellbook>Glyphs>Activate Glyph of the Emerald Bear.
3. Shift character into Dire Bear Form. Character does not appear as Emerald Bear.

**IDs of affected creatures, items, quests or spells with a link to the relevant page:**

NPC: https://database.turtle-wow.org/?npc=
Item: https://database.turtle-wow.org/?item=
Quest: https://database.turtle-wow.org/?quest=
Spell: https://database.turtle-wow.org/?spell=
Object: https://database.turtle-wow.org/?object=

**Expected behavior. Describe how it should work:**
- Character is suppose to appear Emerald when Glyph of the Emerald Bear is activated while in Bear form.

**Comment by GrizB37** [comment]
Click the ice bear again to deactivate it first.

**Comment by twowTurtReynolds** [comment]
These are hidden buffs and indeed one must be cancelled before another is applied. This should be fairly intuitive though I understand the confusion.
