### ISSUE TITLE
装备幻化后，不触发装备的套装效果了

### ISSUE THREAD

**Issue by apopopzkxcpo** [slowtorta/turtlewow-bug-tracker#4865]
**Please, provide a clear description what the bug is:**
血环服务器，id落日的晚霞，魔暴龙护腿幻化后，不触发2件套效果，联系gm后，gm给了我这个网站
**Steps to reproduce the behavior with as much detail as possible:**

1.魔暴龙护腿幻化后不触发套装效果
2. 
3. 

**IDs of affected creatures, items, quests or spells with a link to the relevant page:**
魔暴龙护腿
NPC: https://database.turtle-wow.org/?npc=
Item: https://database.turtle-wow.org/?item=
Quest: https://database.turtle-wow.org/?quest=
Spell: https://database.turtle-wow.org/?spell=
Object: https://database.turtle-wow.org/?object=

**Expected behavior. Describe how it should work:**

**Comment by Muigin** [comment]
请用英文提交问题。我们无法通过自动翻译准确地翻译中文提交的错误报告，这使得我们难以理解问题的确切性质。谢谢！

Please submit the issues in English. We're unable to accurately translate bug reports submitted in Chinese through automatic translation, which makes it difficult for us to understand the exact nature of the issue. Thank you!
