### ISSUE TITLE
Breastplate of Earthen Might shows and give wrong stats

### ISSUE THREAD

**Issue by Lionheartse** [slowtorta/turtlewow-bug-tracker#4866]
**Please, provide a clear description what the bug is:**

**Steps to reproduce the behavior with as much detail as possible:**

1. Item Breastplate of Earthen Might showed right stats when it dropped, then after a couple of days it started the wrong stats. It also gives  the wrong stats when equipped.
![Breastplate of Earthen Might](https://github.com/slowtorta/turtlewow-bug-tracker/assets/148728451/8aef9953-754d-4170-bcad-b69fd2d327d6)

2.  Character name Sonofthunder, Shaman
3. Dont have the ID of the item yet since the database is not open. 

**IDs of affected creatures, items, quests or spells with a link to the relevant page:**

NPC: https://database.turtle-wow.org/?npc=
Item: https://database.turtle-wow.org/?item=
Quest: https://database.turtle-wow.org/?quest=
Spell: https://database.turtle-wow.org/?spell=
Object: https://database.turtle-wow.org/?object=

**Expected behavior. Describe how it should work:**

**Comment by Azuredrak0** [comment]
Having same problem as above.
Character name - Roshas, Hunter.  I believe the item ID is showing 19904 with my addon

**Comment by OonaFae** [comment]
+1

**Comment by Dragunovi** [comment]
Should be fixed next restart.
