### ISSUE TITLE
The Lord of Blackrock

### ISSUE THREAD

**Issue by Rambofevil** [slowtorta/turtlewow-bug-tracker#4867]
**Please, provide a clear description what the bug is:**

**Steps to reproduce the behavior with as much detail as possible:**

Hi, I've  been  trying for hours to turn in the quest THe Lord of Blackrock to Saurfang but doesn't work, some other people have haad the same  issue.

**IDs of affected creatures, items, quests or spells with a link to the relevant page:**

NPC: https://database.turtle-wow.org/?npc=
Item: https://database.turtle-wow.org/?item=
Quest: https://database.turtle-wow.org/?quest=
Spell: https://database.turtle-wow.org/?spell=
Object: https://database.turtle-wow.org/?object=

**Expected behavior. Describe how it should work:**

**Comment by twowTurtReynolds** [comment]
![image](https://github.com/slowtorta/turtlewow-bug-tracker/assets/151180101/02c4bcdb-17a3-4a40-8dda-7794438f2c4a)
I'm not sure what the issue is here. Perhaps the npc was bugged that week? Let me know if it is still happening.
