### ISSUE TITLE
my legendary weapon in not increasing attack power in bear/cat form,please help!

### ISSUE THREAD

**Issue by yinjunqian0326** [slowtorta/turtlewow-bug-tracker#4872]
**Please, provide a clear description what the bug is:**
my legendary weapon in not increasing attack power in bear/cat form

**Steps to reproduce the behavior with as much detail as possible:**

1. all the maces and polearms can be equipped by druid is increasing attack power when in bear/cat form.
2. but my fresh legendary weapon in not increasing attack power in bear/cat form

**IDs of affected creatures, items, quests or spells with a link to the relevant page:** 
id fiercekitty, horde, tauren druid. turtle server.

NPC: https://database.turtle-wow.org/?npc=
Item: https://database.turtle-wow.org/?item= Sulfuras, Hand of Ragnaros
Quest: https://database.turtle-wow.org/?quest=
Spell: https://database.turtle-wow.org/?spell=
Object: https://database.turtle-wow.org/?object=

**Expected behavior. Describe how it should work:** it should increase attack power when in bear/cat form like other maces do

**Comment by Zmitrok1984** [comment]
`all the maces and polearms can be equipped by druid is increasing attack power when in bear/cat form.` 
This is not true.
In [patch notes](https://forum.turtle-wow.org/viewtopic.php?t=8230) writen: 
Most Two-Handed Maces, Polearms and the few physical damage oriented Staves now grant Feral Attack Power, granting 14 for every item level above 60.

**Comment by yinjunqian0326** [comment]
> `all the maces and polearms can be equipped by druid is increasing attack power when in bear/cat form.` This is not true. In [patch notes](https://forum.turtle-wow.org/viewtopic.php?t=8230) writen: Most Two-Handed Maces, Polearms and the few physical damage oriented Staves now grant Feral Attack Power, granting 14 for every item level above 60.

so u mean this weapon dont grant feral attack power is correct?

**Comment by twowTurtReynolds** [comment]
Working as intended.
