### ISSUE TITLE
[ War on Worgen ] 

### ISSUE THREAD

**Issue by frshbnthg** [slowtorta/turtlewow-bug-tracker#4874]
https://database.turtle-wow.org/?quest=40976
**Steps to reproduce the behavior with as much detail as possible:**

1. The quest works fine, just turn in is akward.

**Expected behavior. Describe how it should work:**

The quests offers just one reward ( a green ring ) but asks the player to choose it. Maybe there has to be added another reward ?

**Comment by twowTurtReynolds** [comment]
Same issue as https://github.com/slowtorta/turtlewow-bug-tracker/issues/4785

**Comment by Muigin** [comment]
Fixed on next update.
