### ISSUE TITLE
Goblin Mage's Olympian missile spell cannot see trajectory

### ISSUE THREAD

**Issue by bburbbq** [slowtorta/turtlewow-bug-tracker#4877]
Goblin Mage's Olympian missile spell cannot see trajectory

1.Since the beginning of level training, my Goblin Mage's Aoshu missiles have not seen their trajectory, but the damage is correct.
2. At the end of skill guidance, you can occasionally see the trajectory of the Olympian missile.
3.I'm not sure if other players can see my trajectory, but I can't see it myself.

Spell: https://database.turtle-wow.org/?spell=

**Comment by Muigin** [comment]
This has been fixed and will be pushed in our next client patch (1.17.1)
