### ISSUE TITLE
I cant put any points into my talent tree 

### ISSUE THREAD

**Issue by ezdawgg** [slowtorta/turtlewow-bug-tracker#4878]
I cant put any points into my talent tree

**Steps to reproduce the behavior with as much detail as possible:**

1.  I CANT PUT ANY POINTS INTO MY TALENT TREE 
2. 
3. 

**IDs of affected creatures, items, quests or spells with a link to the relevant page:**

NPC: https://database.turtle-wow.org/?npc=
Item: https://database.turtle-wow.org/?item=
Quest: https://database.turtle-wow.org/?quest=
Spell: https://database.turtle-wow.org/?spell=
Object: https://database.turtle-wow.org/?object=

**Expected behavior. Describe how it should work:**

**Comment by Lexiebean** [comment]
Download a fresh client from https://turtle-wow.b-cdn.net/twmoa_1170.zip with no other patches or modifications.
