### ISSUE TITLE
Moroes doesn't turn hostile after the RP

### ISSUE THREAD

**Issue by TheSyg** [slowtorta/turtlewow-bug-tracker#4879]
**Please, provide a clear description what the bug is:**
Moroes, last boss of Lower Karazhan Halls, doesn't turn hostile towards the players once interacted with him and once talked to he won't allow any other interaction with the player.
**Steps to reproduce the behavior with as much detail as possible:**

Describing what we did as a raid
1. First we cleared the Blacksmith NPC Rolf
2. We turned around and went upstairs, turned left and cleared all the way to Lord Blackwald II.
3. After Blackwald, we went back through the dining room and upstairs to kill Clawlord.
4. After Clawlord we went through the imp rooms and killed Grizikil.
5. We then turned around and to the basement to kill the spider boss.
6. Turned back and around to clear space for Moroes.
7. We interacted with him, his RP started but he never turned hostile and it won't let us interact with him in anyway.

**IDs of affected creatures, items, quests or spells with a link to the relevant page:**

Moroes from Karazhan 10

**Expected behavior. Describe how it should work:**
The boss should activate once interacted with.
![WoWScrnShot_102323_215501](https://github.com/slowtorta/turtlewow-bug-tracker/assets/89550040/f1dc707c-bb17-43f8-84c9-c683bbc83efe)
![WoWScrnShot_102323_215442](https://github.com/slowtorta/turtlewow-bug-tracker/assets/89550040/fb945762-251c-49a1-8417-d4602442f1f0)

**Comment by discer** [comment]
Additionally when he does become hostile if a spell is mid flight when he turns back to friendly he will continue to attack players for about 5 seconds while being unable to be attacked himself

**Comment by lyssebabz** [comment]
https://streamable.com/orqf8q

**Comment by AkalixFrost** [comment]
Fixed in previous update.
