### ISSUE TITLE
Melee Range Bug

### ISSUE THREAD

**Issue by rosen40** [slowtorta/turtlewow-bug-tracker#488]
1. Player simply seems to have higher melee range than mobs
2. This means if the mob is slowed, you can hit him without it hitting you back
3. You can watch a video where i kill a mob on a warrior and i only get hit once.

https://youtu.be/KW_qxJ3DU5o     <--- Demo 

Mobs should be able to hit back, when you hit them.

Yes this affects all mobs.

**Comment by jameyboor** [comment]
Fixed.
