### ISSUE TITLE
Libram of Fervor is not applying bonus holy damage stacks (stuck at 150)

### ISSUE THREAD

**Issue by Felenor** [slowtorta/turtlewow-bug-tracker#4880]
**Please, provide a clear description what the bug is:**

**Steps to reproduce the behavior with as much detail as possible:**

1. apply 5 stacks of crusader strike debuffs (caps out at 150)
2. libram of fervor doesnt offer any bonus holy damage (caps out at 150)
3. tooltip says 48 per stack (doesnt even apply 1 bonus damage)

**IDs of affected creatures, items, quests or spells with a link to the relevant page:**

NPC: https://database.turtle-wow.org/?npc=
Item: https://database.turtle-wow.org/?item=
Quest: https://database.turtle-wow.org/?quest=
Spell: https://database.turtle-wow.org/?spell=
Object: https://database.turtle-wow.org/?object=

**Expected behavior. Describe how it should work:**
libram of fervor should be applying more holy damage than make rank/stacks of crusader strike and it doesnt.

**Comment by twowTurtReynolds** [comment]
On the PTR, My consecrate is doing 77 per tick with 5x stacks of CS with the libram equipped, and when taking the item off and repeating, 74 damage. Working as intended.
