### ISSUE TITLE
小退了以后上来发现物品变成了灵魂绑定物品

### ISSUE THREAD

**Issue by chensheng0001** [slowtorta/turtlewow-bug-tracker#4884]
服务器血环，角色名：ddff，祖尔格拉布副本，团长名字：初與風歌丶，时间：2023年10月24日，大约北京时间晚上23点左右。打了一根玛尔里之触魔杖，团长可能因为插件问题交易不了我，小退了以后上来发现这根魔杖已经变成了灵魂绑定物品，无法交易了，请求帮助

**Comment by Muigin** [comment]
请用英文提交问题。我们无法通过自动翻译准确地翻译中文提交的错误报告，这使得我们难以理解问题的确切性质。谢谢！

Please submit the issues in English. We're unable to accurately translate bug reports submitted in Chinese through automatic translation, which makes it difficult for us to understand the exact nature of the issue. Thank you!
