### ISSUE TITLE
Item: Ebonmere Vambracers - missing icon

### ISSUE THREAD

**Issue by frshbnthg** [slowtorta/turtlewow-bug-tracker#4887]
**Please, provide a clear description what the bug is:**

The item [ Ebonmere Vambracers ] appear as a question mark icon when checking the quest reward of [ Ebonmere Affairs ] 

**Steps to reproduce the behavior with as much detail as possible:**

1.
2. 
3. 

**IDs of affected creatures, items, quests or spells with a link to the relevant page:**

NPC: https://database.turtle-wow.org/?npc=
Item: https://database.turtle-wow.org/?item=
Quest: https://database.turtle-wow.org/?quest=
Spell: https://database.turtle-wow.org/?spell=
Object: https://database.turtle-wow.org/?object=

**Expected behavior. Describe how it should work:**

**Comment by twowTurtReynolds** [comment]
![image](https://github.com/slowtorta/turtlewow-bug-tracker/assets/151180101/48e7c315-f866-46bc-848f-c9b1233415bd)

**Comment by Dragunovi** [comment]
Should be fixed in the next scheduled server restart.
