### ISSUE TITLE
No quest item dropping from Hakkar for the Soulwell quest

### ISSUE THREAD

**Issue by xankg** [slowtorta/turtlewow-bug-tracker#4888]
**Please, provide a clear description what the bug is:**

**Steps to reproduce the behavior with as much detail as possible:**

1. I was trying to do the warlock quest for the Soulwell spell, Draining the Soulflayer, where you are supposed to kill Hakkar and loot the Well Essence from him. We killed him, and another warlock in the raid could loot the item, but I could not. I contacted a GM, and he wasnt sure it was a bug, or that Hakkar only drops 1 Well Essence per kill and told me to submit a bug report.

My character name is Receptor on the server Turtle WoW (RP)

**IDs of affected creatures, items, quests or spells with a link to the relevant page:**

NPC: https://database.turtle-wow.org/?npc=14834
Item: https://database.turtle-wow.org/?item=83006
Quest: https://database.turtle-wow.org/?quest=70003
Spell: https://database.turtle-wow.org/?spell=
Object: https://database.turtle-wow.org/?object=

**Expected behavior. Describe how it should work:**
I guess I would just loot it off him like any kill the last boss quest.

**Comment by twowTurtReynolds** [comment]
Moam also drops only one of these per raid ID, working as intended.
