### ISSUE TITLE
"A Warm Feeling" Showing As Ready To Turn In, Yet Missing From My Quest Log

### ISSUE THREAD

**Issue by SinisterRewind** [slowtorta/turtlewow-bug-tracker#4889]
When I talk to Salfa (the questgiver for the quest "A Warm Feeling") in Winterspring, their dialogue shows that the quest "A Warm Feeling" is ready for turn-in, however, the quest is not in my quest log, and the items required to turn in the quest (20 Winterspring Tea Leaves) are neither in my inventory, nor are they dropping off the appropriate enemies.

**Steps to reproduce the behavior with as much detail as possible:**

1. I apologize, I'm not sure how to reproduce this bug.

**IDs of affected creatures, items, quests or spells with a link to the relevant page:**

NPC: https://database.turtle-wow.org/?npc=11556
Item: https://database.turtle-wow.org/?item=80880
Quest: https://database.turtle-wow.org/?quest=80369

**Expected behavior. Describe how it should work:**

When I open Salfa's dialogue window, I should be able to see the quest "A Warm Feeling" is ready to be picked up, or I should be able to see the quest already in my quest log.

![WoWScrnShot_102423_135628](https://github.com/slowtorta/turtlewow-bug-tracker/assets/59970220/e10c3318-b3d8-4fb8-97f9-db00e7ad4d52)
![WoWScrnShot_102423_135635](https://github.com/slowtorta/turtlewow-bug-tracker/assets/59970220/07aab72c-c56e-41d8-8124-3f365cdc6dd7)

**Comment by twowTurtReynolds** [comment]
Is this still happening to you? Maybe contact a GM. I haven't seen others with this issue.

Unless we can figure out replication steps, this doesn't belong as a bug report.
