### ISSUE TITLE
[Rhok'delar Questline] Demons leash at a fixed range, hindering tactics used to defeat them

### ISSUE THREAD

**Issue by cydith** [slowtorta/turtlewow-bug-tracker#489]
During the Rhok'delar questline, hunters are asked to kill 4 demons. These demons required pretty specific tactics to defeat, especially the one in Winterspring, which has to be kited a prolonged period. As the leash range on the server is fixed, this is no longer possible. 

1. Have the Rhok'delar questline active (specific quest is "Stave of the Ancients". 
2. Find any of the four demons required by the quest and engage them
3. Attempt to kite more than 200-250 yards (keep hitting them at least once every 5-6 seconds). 

Artorius the Doombringer: https://database.turtle-wow.org/?npc=14535
Simone the Seductress: https://database.turtle-wow.org/?npc=14533
Klinfran the Crazed: https://database.turtle-wow.org/?npc=14534
Solenor the Slayer: https://database.turtle-wow.org/?npc=14530

Quest: https://database.turtle-wow.org/?quest=7636

These mobs should be kitable for a prolonged period of time, in order to facilitate killing them. At the moment, as specified earlier, Artorius specifically is very hard to kill, as his mechanic requires the hunter to not be in 30 yards or closer and the area he patrols has a high mob density.

**Comment by OrnsteinHunter** [comment]
I can confirm this. I was helping another hunter with Artorius and i had to practically spam serpent sting after every arcane shot to keep him leashed.

**Comment by CasualNerdity** [comment]
Also confirming. Klinfran cannot be kited further than the west side of the Pillar of Ash subzone. Artorius evades at the same tree close to the road, even if I allow him to get into melee and backpedal.

**Comment by Steevo2** [comment]
So apparently they plan to tweak leashing next patch. They also say the current changes are intended and also only minor which is laughable as I've seen mobs evade within 40 yards of where they were pulled while being shot and attacked by my pet, but we'll see what they've come up with.

**Comment by SabineWren** [comment]
Circle kiting works against Artorius and Simone, and I used a Classic guide for Klinfran without any changes.

Solenor seems bugged, as he casts fear without being wingclipped, and none of the Classic guides show that behaviour. It doesn't make sense for him to be so difficult solo when a warlock assisting trivializes the fight.
