### ISSUE TITLE
Brigade Footman only has a male human model

### ISSUE THREAD

**Issue by Aeliren** [slowtorta/turtlewow-bug-tracker#4890]
The Brigade Footman NPC of the Gilneas Brigade, located in Ravenshire, Theramore Isle and outside the Shademore Inn, only has a male human model.

![image](https://github.com/slowtorta/turtlewow-bug-tracker/assets/96898927/b1a8721c-6863-4e23-a9ec-3ebc219ffb8e)

This is in sharp contrast to the Ravenshire Guard NPC, which has both male and female models. It is also odd that the Brigade only has human representation when the Gilneas Brigade was explicitly comprised of both humans and dwarves in Warcraft III, the latter of which being explained in Turtle WoW through the city of Gelnor mentioned in lore books in Gilneas (the city itself currently isn't visible in Turtle WoW).

**Steps to reproduce the behavior with as much detail as possible:**

1. Find a Brigade Footman in one of the following locations: Ravenshire or the Shademore Inn in Gilneas, or Theramore Isle in Dustwallow Marsh.
2. View their identical models in all locations.

**IDs of affected creatures, items, quests or spells with a link to the relevant page:**
NPC: https://database.turtle-wow.org/?npc=61541

**Expected behavior. Describe how it should work:**
Like with all other human guards portrayed in-game including their militia counterparts in the Ravenshire Guards, they should likely have a female variant unit. Furthermore, being accurate to their portrayal in Warcraft III and through the lore established in Turtle WoW, there should likely be dwarven models attached to the same unit or dwarven units of the Gilneas Brigade present in the same locations.

**Comment by twowTurtReynolds** [comment]
After convening with staff, unfortunately we won't be adding a female model for this NPC faction.
