### ISSUE TITLE
Stormwind Vault chest can be looted before killing Arc'tiras

### ISSUE THREAD

**Issue by N1cc3** [slowtorta/turtlewow-bug-tracker#4892]
I do not know how to reproduce but a mage in our group could loot the chest in the end (https://database.turtle-wow.org/?object=2010867) before we even engaged Arc'tiras (https://database.turtle-wow.org/?npc=93107). Is that supposed to be possible?

**Comment by twowTurtReynolds** [comment]
![image](https://github.com/slowtorta/turtlewow-bug-tracker/assets/151180101/7ba2aca7-6c64-405c-bee1-22f90a51ab16)
I blinked through the ice barrier, but no chests awaited me.

Killed the boss, and all seems well.

![image](https://github.com/slowtorta/turtlewow-bug-tracker/assets/151180101/359d8588-38d0-41a2-809a-25ac04fe9a83)

And then I found that this was fixed 2 weeks ago in a duplicate ticket https://github.com/slowtorta/turtlewow-bug-tracker/issues/5115
