### ISSUE TITLE
Hunter AQ20 ring [Signet of the Unseen Path] has a "use" effect of improving chance of hit by 1% instead of "equip"

### ISSUE THREAD

**Issue by shijiexug2016** [slowtorta/turtlewow-bug-tracker#4895]
**Please, provide a clear description what the bug is:**
Hunter AQ20 ring [Signet of the Unseen Path] has a "use" effect of improving chance of hit by 1% instead of "equip"

**Steps to reproduce the behavior with as much detail as possible:**
When equipping the ring there is no hit rate increase.

**IDs of affected creatures, items, quests or spells with a link to the relevant page:**

NPC: https://database.turtle-wow.org/?npc=
Item: https://database.turtle-wow.org/?item=21402
Quest: https://database.turtle-wow.org/?quest=
Spell: https://database.turtle-wow.org/?spell=
Object: https://database.turtle-wow.org/?object=

**Expected behavior. Describe how it should work:**
Equipping the ring should increase hit rate by 1%.

**Comment by twowTurtReynolds** [comment]
![image](https://github.com/slowtorta/turtlewow-bug-tracker/assets/151180101/8ae1f239-00d6-48b7-811a-dc06109336e9)
Looks like this has already been fixed :)
