### ISSUE TITLE
术士无法接灵魂之井任务

### ISSUE THREAD

**Issue by xiexiedex** [slowtorta/turtlewow-bug-tracker#4897]
霍格服务器，部落兽人术士（Meek），诅咒之地（衰老的戴奥）的任务已完成，没有后续，回到主城训练师处，也无法接到任何任务，望尽快解决！

**Comment by Muigin** [comment]
请用英文提交问题。我们无法通过自动翻译准确地翻译中文提交的错误报告，这使得我们难以理解问题的确切性质。谢谢！

Please submit the issues in English. We're unable to accurately translate bug reports submitted in Chinese through automatic translation, which makes it difficult for us to understand the exact nature of the issue. Thank you!
