### ISSUE TITLE
Blade of Eternal Justice got nerfed instead buffed

### ISSUE THREAD

**Issue by Zmitrok1984** [slowtorta/turtlewow-bug-tracker#4898]
From  [Midpatch Itemization Changes Changelog](https://forum.turtle-wow.org/viewtopic.php?t=10971)
AQ20 Set Reworks:
All set weapons' item level has been increased from 70 to 74 and turned into Uniques, increasing their stats and DPS/Healing Power/Spellpower.

**Please, provide a clear description what the bug is:**
Actually Blade of Eternal Justice got nerfed in comparison of other classes weapon.
Weapon DPS increased but Spell power reduced.

Before
![image](https://github.com/slowtorta/turtlewow-bug-tracker/assets/99164611/6fe5889d-6f1a-43b7-b879-f71073570ad9)
After
![image](https://github.com/slowtorta/turtlewow-bug-tracker/assets/99164611/a0a2d853-7157-4449-b92a-dd4d48548d86)

That weapon definitely for protection paladin, because it is one-handed weapon, has 1% dodge. Retribution paly used two-handed weapons. Holy paly will look for weapon with a large number healing power.
Prot paladins used in own rotations  for tanking ability like Consecration, Seal of Righteousness, Holy strike, Holy shield (threat from holy damage increased by Righteous Fury). 
Spell power reduction decreases yellow damage/TPS as well. 
For prot paladin buffing weapon DPS did very low effort.

Item: https://database.turtle-wow.org/?item=21395

**Expected behavior. Describe how it should work:**
Please refactore that changes.
Keep DPS as was before but increase spell power according to other caster weapon.

**Remarks:**
Looks into new prot paladin armors from Lower Kara -> all pieces have Stamina/Intellect/**Spell power**/Defense and have no Strength.
Protection paladin is caster, not melee DD.

**Comment by Zmitrok1984** [comment]
If check any guide for protection paladin for WOW Classic or TBC, they propose to you use weapon with spell power for near to the End-game gear.

**Comment by Niqlo** [comment]
> Every other class will look to gain reputation with Cenarion Circle and get their weapon from AQ20 for at least one of their specs, but not the Paladin.

not even close to true

**Comment by Muigin** [comment]
Bugtracker is for bugs, not discussions about item changes.  Please post this in the appropriate forum section.
