### ISSUE TITLE
when editing public notes in the guild, officers' notes are changed

### ISSUE THREAD

**Issue by TorTun** [slowtorta/turtlewow-bug-tracker#490]
**Please, provide a clear description what the bug is:**

**Steps to reproduce the behavior with as much detail as possible:**

1. when editing public notes in the guild, officers' notes are changed
2. 
3. 

**IDs of affected creatures, items, quests or spells with a link to the relevant page:**

NPC: https://database.turtle-wow.org/?npc=
Item: https://database.turtle-wow.org/?item=
Quest: https://database.turtle-wow.org/?quest=
Spell: https://database.turtle-wow.org/?spell=
Object: https://database.turtle-wow.org/?object=

**Expected behavior. Describe how it should work:**

**Comment by Tinyfin-github** [comment]
Greetings! Thank you for the report.

The issue will be fixed at the next server maintenance.

https://github.com/slowtorta/turtlewow-bug-tracker/issues/481
