### ISSUE TITLE
Hyjal quest

### ISSUE THREAD

**Issue by vkekd** [slowtorta/turtlewow-bug-tracker#4900]
Currently this quest https://database.turtle-wow.org/?quest=41021 is not repeatable
Assuming this is a bug since the whole place is filled with repeatable kill/gather quests to farm shards

**Comment by twowTurtReynolds** [comment]
![image](https://github.com/slowtorta/turtlewow-bug-tracker/assets/151180101/19932b69-8341-416b-8a1f-5c14d38264e5)

It's repeatable.
