### ISSUE TITLE
Bael Dun (new dwarf town in Stonetalon) flightpath bug

### ISSUE THREAD

**Issue by AeternusDoleo** [slowtorta/turtlewow-bug-tracker#4905]
**Please, provide a clear description what the bug is:**
The flightpath from Bael Dun is not working right. It's only connection is to Astranaar, and it will work good only if you fly directly to Astranaar. If you select a flightpath further then that (for instance to Ruth'Theran Village, Teldrassil) then the player will bug out in Astranaar with the character remaining mounted on a hippogriff but back under manual control, "walking" on the ground at normal speed while mounted, unable to do anything else. Logging out and back in fixes this and gets you back in flight to whichever next point is on the trip (in my case Auberdine) and you stop there. Oddly, there is no 20 second stand down while logging out either.

**Steps to reproduce the behavior with as much detail as possible:**
1. Go to Bael Dun by any available means.
2. Take the flightpoint and travel to Darnassus/Ruth'Theran
3. Observe as it glitches out in Astranaar.
4. Log out and back in again and observe the flight continuing to the next destination and stop there.

**IDs of affected creatures, items, quests or spells with a link to the relevant page:**
Due to the database being down I am unable to get the relevant IDs.

**Expected behavior. Describe how it should work:**
Expected behavior is that the flight would continue to the selected destination.

**Comment by twowTurtReynolds** [comment]
Closing as dupe https://github.com/slowtorta/turtlewow-bug-tracker/issues/4619
