### ISSUE TITLE
Southshore Syndicate Assassin's event not working

### ISSUE THREAD

**Issue by Lightsentinel** [slowtorta/turtlewow-bug-tracker#4907]
**Please, provide a clear description what the bug is:**

**Steps to reproduce the behaviour with as much detail as possible:**

1. Wait in Southshore for the Southshore Crier to announce the event in /yell
2. Shadowy Assassin's do not spawn whatsoever, either in Blizz-like locations or in any visible custom ones.
3. Southshore Crier just stands outside the Inn for about ten minutes after announcing the attack.
4. As the Shadowy Assassin's do not spawn, the Assassin's Contract item cannot be looted to begin the quest chain of the same name which leads to killing Baron Vardus in Alterac Mountains.

**IDs of affected creatures, items, quests or spells with a link to the relevant page:**

NPC: https://database.turtle-wow.org/?npc=2435
NPC: https://database.turtle-wow.org/?npc=2434
Item: https://database.turtle-wow.org/?item=3668
Quest: https://database.turtle-wow.org/?quest=522

**Expected behaviour. Describe how it should work:**

The Shadowy Assassin's should spawn in multiple locations across the town, including behind the town hall, behind the inn and next to the cattle field. If memory serves me right, some also spawn inside the town hall to attack Henry Maleb(their target). They should spawn in groups of at least 3 so that players get a chance to kill them before the guards finish them all off

**Comment by Lichbanez** [comment]
I can confirm, the crier doesn't progress the event and it seems bugged.

**Comment by Muigin** [comment]
Confirmed, pushing to a Core Dev

**Comment by Muigin** [comment]
#4922 
#3675
