### ISSUE TITLE
Sorcerer's Leggings (mage t0.5 pants) has an on-use ability that can't be triggered

### ISSUE THREAD

**Issue by w0lf3h** [slowtorta/turtlewow-bug-tracker#4908]
New update to Sorcerer's Leggings (mage t0.5 set pants) has an on-use rather than I believe an on-equip bonus.

Use: Increases damage and healing done by magical spells and effects by up to 24. 

I believe this is supposed to be an Equip bonus? Either way, this item is not clickable for the on-use effect either and gives no spell damage increase.

https://database.turtle-wow.org/?item=22067

![Screenshot 2023-10-25 094415](https://github.com/slowtorta/turtlewow-bug-tracker/assets/1549104/5170bb8c-77ca-4c38-b4e6-7316a3339f22)

**Comment by Ladiev** [comment]
Devs pls? should be a quick fix right? right? :(

**Comment by Dragunovi** [comment]
The fix is on its way to a scheduled restart near you.
