### ISSUE TITLE
Intercepting Wavecrest quest bug?

### ISSUE THREAD

**Issue by Sty0pa1** [slowtorta/turtlewow-bug-tracker#4909]
**Please, provide a clear description what the bug is:**
Just a note, it seems the Intercepting Wavecrest quest in Tel'abim may not be working properly?
You have to gather 20 scales from Naga, and usually with Turtle quests, when there is a quest item dropped, it's dropped for everyone.
In this case, it's behaving like an OLD WoW quest where quest items drop only for individuals.
So with a drop rate of something around 80%, as our group of 4 players, we couldn't finish the quest with only 20-30 kills, but would have had to kill something like A HUNDRED nagas.
That's so unusual for Turtle quest design, it seemed like something wasn't working as intended.

**ALSO** just noticed the turtle public database shows the reward from this quest is a choice of 2 green items.  At least last night, the (in progress) quest text in game DID NOT offer a listed reward, which would suggest a followon quest when completed.

THANKS! 
**Steps to reproduce the behavior with as much detail as possible:**

1.  Take Intercepting wavecrest quest as a group of 2+ people.
2.  Kill naga
3.  For nagas that drop a quest item, it can only be picked up by one person (and that seems to go round-robin around the party as to whom it's "for".

**IDs of affected creatures, items, quests or spells with a link to the relevant page:**

NPC: https://database.turtle-wow.org/?npc=
Item: https://database.turtle-wow.org/?item=
Quest: https://database.turtle-wow.org/?quest=40768
Spell: https://database.turtle-wow.org/?spell=
Object: https://database.turtle-wow.org/?object=

**Expected behavior. Describe how it should work:**
Each naga should drop a scale that is lootable by all players in the party with the quest.

**Comment by Muigin** [comment]
I have pushed a fix for this, and the item will be party lootable after the next maintenance.
