### ISSUE TITLE
Карта безопасного доступа ДЕЛЬТА

### ISSUE THREAD

**Issue by UlukayOutkastov** [slowtorta/turtlewow-bug-tracker#491]
Не вышло изучить рецепт инженерии "анти-перенаправляющий луч" с помощью "Карта безопасного доступа ДЕЛЬТА" в Гномреган.

1. Я нашел "Карта безопасного доступа ДЕЛЬТА"
2. Пытался использовать все устройства "Матричный перфограф" в Гномреган
3. Не один "Матричный перфограф" не воспринимал "Карта безопасного доступа ДЕЛЬТА"

Item: https://database.turtle-wow.org/?item=9327
Spell: https://database.turtle-wow.org/?item=4413
Object: https://database.turtle-wow.org/?item=9327

Чтобы изучить "анти-перенаправляющий луч" с помощью "Матричный перфограф 3005-D", вы должны иметь "Карта безопасного доступа ДЕЛЬТА" и инженерные навыки 160.

Item: 
https://ru.classic.wowhead.com/item=9327/%D0%BA%D0%B0%D1%80%D1%82%D0%B0-%D0%B1%D0%B5%D0%B7%D0%BE%D0%BF%D0%B0%D1%81%D0%BD%D0%BE%D0%B3%D0%BE-%D0%B4%D0%BE%D1%81%D1%82%D1%83%D0%BF%D0%B0-%D0%B4%D0%B5%D0%BB%D1%8C%D1%82%D0%B0
Object: 
https://ru.classic.wowhead.com/object=142696/%D0%BC%D0%B0%D1%82%D1%80%D0%B8%D1%87%D0%BD%D1%8B%D0%B9-%D0%BF%D0%B5%D1%80%D1%84%D0%BE%D0%B3%D1%80%D0%B0%D1%84-3005-d
Spell: 
https://ru.classic.wowhead.com/item=4413/%D1%87%D0%B5%D1%80%D1%82%D0%B5%D0%B6-%D0%B0%D0%BD%D1%82%D0%B8-%D0%BF%D0%B5%D1%80%D0%B5%D0%BD%D0%B0%D0%BF%D1%80%D0%B0%D0%B2%D0%BB%D1%8F%D1%8E%D1%89%D0%B8%D0%B9-%D0%BB%D1%83%D1%87#dropped-by

**Comment by slowtorta** [comment]
Fixed in the next revision, thank you.
