### ISSUE TITLE
Gilneas drowning 

### ISSUE THREAD

**Issue by Scarecrow4012** [slowtorta/turtlewow-bug-tracker#4911]
**Please, provide a clear description what the bug is:**
   In a Zone closer to the Bloodclaw Worgens in Gilneas, you start drowning if you stand in a specific place in a mountain for no reason.
**Steps to reproduce the behavior with as much detail as possible:**

1. Go to the mountain closer to Worgen Bloodclaw camp.
2. Simply stand there
3. The bar of breath will appear for no reason

**Expected behavior. Describe how it should work:**
Well, I guess you don't need to drown there, it's terrain, no water.

Link for reference:
https://drive.google.com/file/d/1iUyv4bCJ0nA8Tu6Xtyhv9icZmX5hO6Ib/view?usp=sharing

![image](https://github.com/slowtorta/turtlewow-bug-tracker/assets/151180101/f415fbc9-0882-460a-8a5a-2bf6cb754971)

**Comment by twowTurtReynolds** [comment]
38.8, 41.3
![image](https://github.com/slowtorta/turtlewow-bug-tracker/assets/151180101/6da8f61b-e3a4-4d4f-9654-e266e0490dc3)
![image](https://github.com/slowtorta/turtlewow-bug-tracker/assets/151180101/7fcaee82-7558-4c32-b033-7d711afb0ad4)

Closing, tracking this under https://github.com/slowtorta/turtlewow-bug-tracker/issues/5811 now.
