### ISSUE TITLE
High Elf Ears

### ISSUE THREAD

**Issue by Scarecrow4012** [slowtorta/turtlewow-bug-tracker#4912]
**Please, provide a clear description what the bug is:**
Well, the ears of the High Elves not show when they wear helmets, only a hole is seen and it looks bad.
**Steps to reproduce the behavior with as much detail as possible:**

1. Look for a helmet in-game.
2. Fight with the party members for it and win if you can.
3. Use the helmet.

**IDs of affected creatures, items, quests or spells with a link to the relevant page:**
 Every character who is High Elf in-game.

**Expected behavior. Describe how it should work:**
The High Elf ears can be seen with the helmet.

**Link for reference:**
![https://lh3.googleusercontent.com/u/0/drive-viewer/AK7aPaD6fGAyBoXI5Ds_xxexRYysypwePUaDfOiFZ_B1nVQFA4x2zOKZuT4xsvy4WBtFZADOE8NJQDG0P55Snu4mghL320O9hw=w1689-h987](https://lh3.googleusercontent.com/u/0/drive-viewer/AK7aPaD6fGAyBoXI5Ds_xxexRYysypwePUaDfOiFZ_B1nVQFA4x2zOKZuT4xsvy4WBtFZADOE8NJQDG0P55Snu4mghL320O9hw=w1689-h987)

**Comment by twowTurtReynolds** [comment]
Indeed, it seems this type of modeled helmet has this bug with female helves:
![image](https://github.com/slowtorta/turtlewow-bug-tracker/assets/151180101/b8d385b7-3a5f-4c92-b251-a1485bb625a6)

While other helmets seem fine
![image](https://github.com/slowtorta/turtlewow-bug-tracker/assets/151180101/1f8f02b9-70fd-4c43-a743-00d486b6cd6f)

**Comment by twowTurtReynolds** [comment]
Here's 7719 raging berserker's helm:
![image](https://github.com/slowtorta/turtlewow-bug-tracker/assets/151180101/d2cc1777-f525-4e86-adad-b5645414e369)
Much better.

Fixed in 1.17.2
