### ISSUE TITLE
Quest item not dropping for quest "snatch and grab"

### ISSUE THREAD

**Issue by maxdizgun** [slowtorta/turtlewow-bug-tracker#4913]
**Please, provide a clear description what the bug is:**

**Steps to reproduce the behavior with as much detail as possible:**

1. supposed to kill the dockmaster
2. hes supposed to drop the shipping schedule
3. no drop item

**IDs of affected creatures, items, quests or spells with a link to the relevant page:**
https://www.wowhead.com/classic/quest=2206/snatch-and-grab

NPC: https://database.turtle-wow.org/?npc=
Defias Dockmaster
Item: https://database.turtle-wow.org/?item=
Defias shipping schedule
Quest: https://database.turtle-wow.org/?quest=
snatch and grab, rogue quest
Spell: https://database.turtle-wow.org/?spell=
none
Object: https://database.turtle-wow.org/?object=
none

**Expected behavior. Describe how it should work:**
The dockmaster isnt dropping the required item. tried killing him multiple times.

**Comment by luskanek** [comment]
You're supposed to pick-pocket the item from the dockmaster. Working as intended.
