### ISSUE TITLE
Vial of Potent Venoms deals less damage than stated on the tooltip

### ISSUE THREAD

**Issue by patrycos** [slowtorta/turtlewow-bug-tracker#4917]
**Please, provide a clear description what the bug is:**
Vial of Potent Venoms' tooltip states [Your melee and ranged attacks have a chance to inject poison into your target that deals 100 Nature damage over 8 sec. Stacks up to 5 times.](https://database.turtle-wow.org/?spell=45417) which translates to 25 damage every 2 seconds per stack, up to 125 damage every 2 seconds at 5 stacks. Instead, it currently deals 20 damage every 2 seconds per stack, up to 100 damage every 2 seconds at 5 stacks. There is no mention of any changes to the trinket in patch notes so I'm assuming it's a bug and not an intentional change.

**Steps to reproduce the behavior with as much detail as possible:**
1. Have Vial of Potent Venoms equipped
2. Attack any target with 0 Nature Resistance such as Apprentice Target Dummy
3. The damage over time effect from the trinket will deal less damage than it's supposed to

**IDs of affected creatures, items, quests or spells with a link to the relevant page:**
Vial of Potent Venoms: https://database.turtle-wow.org/?item=61243
Potent Venom: https://database.turtle-wow.org/?spell=45417

**Expected behavior. Describe how it should work:**
Vial of Potent Venoms is supposed to deal 25 damage every 2 seconds per stack, up to 125 damage every 2 seconds at 5 stacks.

**Comment by ratkosrb** [comment]
The effect has been changed server side. Tooltip in client can't be updated without a new patch.

**Comment by ratkosrb** [comment]
database.turtle-wow.org does not read the spell_template table directly, it requires the data to be copied and transformed into a different format, so its often outdated
