### ISSUE TITLE
Crazy Cat Lady title

### ISSUE THREAD

**Issue by fickle1512** [slowtorta/turtlewow-bug-tracker#4921]
**Please, provide a clear description what the bug is:**

**Steps to reproduce the behavior with as much detail as possible:**

1.I collected all the cats, but I didn't get the Crazy Cat Lady title
2. I now have [Black Tabby][Cornish Rex][Orange Tabby][Siamese][Silver Tabby][White Kitten][Mr. Bigglesworth][Midnight][Corrupted Kitten]
3. 

**IDs of affected creatures, items, quests or spells with a link to the relevant page:**

NPC: https://database.turtle-wow.org/?npc=
Item: https://database.turtle-wow.org/?item=
Quest: https://database.turtle-wow.org/?quest=
Spell: https://database.turtle-wow.org/?spell=
Object: https://database.turtle-wow.org/?object=

**Expected behavior. Describe how it should work:**

**Comment by slowtorta** [comment]
You don't have enough cats 🐱

**Comment by fickle1512** [comment]
> 你没有足够的猫 🐱

Can you tell me which cat I still need

**Comment by slowtorta** [comment]
No, you have to ask other cat lovers :o

**Comment by fickle1512** [comment]
> 不，你必须问其他爱猫人士：o

Okay, thank：|

**Comment by fickle1512** [comment]
> 不，你必须问其他爱猫人士：o

Isn't it enough for me to have 10 cats now？：）

**Comment by lyssebabz** [comment]
you're missing white winter cub

**Comment by fickle1512** [comment]
> you're missing white winter cub

I think we can hit the snow leopard white winter cub

**Comment by fickle1512** [comment]
> 不，你必须问其他爱猫人士：o

May I ask if Snow Leopard will produce a White Tiger Cube now?Thank you very much

**Comment by lyssebabz** [comment]
> > 不，你必须问其他爱猫人士：o
> 
> May I ask if Snow Leopard will produce a White Tiger Cube now?Thank you very much

it does :D
