### ISSUE TITLE
Assasin's Contract quest item in southshore

### ISSUE THREAD

**Issue by Senjan90** [slowtorta/turtlewow-bug-tracker#4922]
**Please, provide a clear description what the bug is:**

**Steps to reproduce the behavior with as much detail as possible:**

1.Assasins in soutshore does not appear never.
2. they drop quest item "assasin's contract"
3.  camping it for a month and the event with assasins didnt happened, im 99% sure that this event does not working on turtle wow server. they should spawn after doing the syndicate members killing quest line

**IDs of affected creatures, items, quests or spells with a link to the relevant page:**

NPC: https://database.turtle-wow.org/?npc=
Item: https://database.turtle-wow.org/?item=
Quest: https://database.turtle-wow.org/?quest=
Spell: https://database.turtle-wow.org/?spell=
Object: https://database.turtle-wow.org/?object=

**Expected behavior. Describe how it should work:**
https://www.wowhead.com/classic/quest=522/assassins-contract
its about this item, is it possible to get in on my mail if the event in southshore not working?

**Comment by Lichbanez** [comment]
I'm also camping this event and it seems to be bugged. The crier just stop in front of the Town Hall after yelling just the first part of the dialogue ("Help me! Help! Assassins in the Hills! To arms! To arms!") and despawn about 30 minutes later.

**Comment by Muigin** [comment]
#4907 
#3675

**Comment by Senjan90** [comment]
is it possible to get "assasin's contract" from shadowy assasin in hillsbrad on mail? because event not working? my nick in game is Bobek on the pvp server
