### ISSUE TITLE
Felstriker！Weapon effects not working properly

### ISSUE THREAD

**Issue by seybrew001** [slowtorta/turtlewow-bug-tracker#4925]
1.when the weapon effect is triggered. Cannot display the effect correctly
2. The weapon effect description is. The next three attacks will always hit and ctri strike, but I have found in team dummy tests and actual raids. The weapon effect does not work correctly. It doesn't ctri strike when triggered.
3. On the Turtle server the Felstriker weapon effect priority sucks. It will be blocked, dodged and blocked. This is completely different from its weapon effect description.

**Comment by balakethelock** [comment]
not a bug, this is how the weapon always works since 2004
You can still get dodged, parried, or glanced.

**Comment by seybrew001** [comment]
> not a bug, this is how the weapon always works since 2004 You can still get dodged, parried, or glanced.

But the description of the weapon confuses me...
Is it worth... The next three attacks must hit... And the blasts...
Which means it's impossible to dodge or parry.
