### ISSUE TITLE
Missing texture for hat

### ISSUE THREAD

**Issue by gepetotati** [slowtorta/turtlewow-bug-tracker#4929]
**Please, provide a clear description what the bug is:**

**Steps to reproduce the behavior with as much detail as possible:**
![image](https://github.com/slowtorta/turtlewow-bug-tracker/assets/49960050/6d2e3218-299b-4402-bcd5-8c04e04b5bb8)
wearing that hat

**IDs of affected creatures, items, quests or spells with a link to the relevant page:**
https://database.turtle-wow.org/?item=20392
NPC: https://database.turtle-wow.org/?npc=
Item: https://database.turtle-wow.org/?item=
Quest: https://database.turtle-wow.org/?quest=
Spell: https://database.turtle-wow.org/?spell=
Object: https://database.turtle-wow.org/?object=

**Expected behavior. Describe how it should work:**

**Comment by Muigin** [comment]
This will be fixed in the next client update as it required new assets.
