### ISSUE TITLE
Wyvern Sting not breaking on damage

### ISSUE THREAD

**Issue by OrnsteinHunter** [slowtorta/turtlewow-bug-tracker#493]
**Please, provide a clear description what the bug is:**

Wyvern sting is not breaking on any damage when it's supposed to be a sleep. Instead its a 12 second stun.

**Steps to reproduce the behavior with as much detail as possible:**

1. spec survival hunter into wyvern sting
2. use wyvern sting on a mob and attack it
3. notice it doesnt break.

**IDs of affected creatures, items, quests or spells with a link to the relevant page:**

https://database.turtle-wow.org/?spell=24133

**Expected behavior. Describe how it should work:**
Wyvern sting should break on any damage done to the target.

**Comment by jameyboor** [comment]
Fixed.
