### ISSUE TITLE
Rod of Resuscitation visual display upside down

### ISSUE THREAD

**Issue by Irksom** [slowtorta/turtlewow-bug-tracker#4932]
**Please, provide a clear description what the bug is:**

Visual graphic for Rod of Resuscitation appears to be backwards and upside down when equipped and slung over character's back.  Displays oddly for not just me, but other players as well despite un equipping and re equipping

**Steps to reproduce the behavior with as much detail as possible:**

1.  Equip Rod of Resuscitation

**Expected behavior. Describe how it should work:**

I believe the top should be pointed upwards and angled diagonally pointing to the top left shoulder.
![staff](https://github.com/slowtorta/turtlewow-bug-tracker/assets/148688578/9f3b8a39-76dc-451d-ad56-c933f270afb4)

**Comment by twowTurtReynolds** [comment]
![image](https://github.com/slowtorta/turtlewow-bug-tracker/assets/151180101/b4580ea2-4f2d-4fc5-ba69-00352f8b01ad)
![image](https://github.com/slowtorta/turtlewow-bug-tracker/assets/151180101/5bebacfc-6d09-4a9b-8398-5d3cc388d69f)

It also doesnt seem to have a model when used to attack.

**Comment by RUTHINAS** [comment]
The effect persists through transmogrification.
