### ISSUE TITLE
Bugged pet food

### ISSUE THREAD

**Issue by xoxoFinn** [slowtorta/turtlewow-bug-tracker#4933]
**Please, provide a clear description what the bug is:**

My hunter pet gets instantly hungry and consumes way to much food.

ingame name: xoxo

**Steps to reproduce the behavior with as much detail as possible:**

1. Tame pet
2. fight with it
3. instantly gets hungry

**IDs of affected creatures, items, quests or spells with a link to the relevant page:**

**Expected behavior. Describe how it should work:**

Less food consumption

**Comment by Muigin** [comment]
Working as intended.  When you tame a new pet, it's Loyalty is extremely low, and this impacts its food consumption.

Your pet loses Happiness at a fixed amount every "tick", with the length of the ticks being based upon your pet's Loyalty level.  This leads to new pets needing to be fed roughly every 5 minutes to not immediately become Unhappy.
