### ISSUE TITLE
Wrong Objective Text for Quest "The Divination"

### ISSUE THREAD

**Issue by Winningone** [slowtorta/turtlewow-bug-tracker#4935]
**Please, provide a clear description what the bug is:**
The objective text description for the quest "The Divination" is incorrect. It is currently showing the objective text for the quest to retrieve Techbot's brain from Gnomeregan.
**Steps to reproduce the behavior with as much detail as possible:**

1. Turn in the quest ""Nekrum's Medallion" to Thadius Grimshade in the Blasted Lands
2. Read quest description for "The Divination"

Link to effected quest:

Quest: https://database.turtle-wow.org/?quest=2992

**Comment by Muigin** [comment]
Thank you for catching this oversight!  I will resolve this myself and push the fix for next maintenance.
