### ISSUE TITLE
Database: Missing items

### ISSUE THREAD

**Issue by cyaohiri** [slowtorta/turtlewow-bug-tracker#4936]
Inspired by #4927, I found more items that are missing from the listing in the database. Here is a comparison of two identical searches on our database and Wowhead. Ignoring custom items, the search only returns 3 of 12 items, which are shown on Wowhead. There are probably a lot more items missing. This is just one category of one item rarity, but points to a more general issue.

The items are only missing in the listings when applying some filters, but they are present in the online database if searched by name. It looks like there's a problem with the item filters.

Turtle WoW Database:
![Screenshot 2023-10-28 Items - Turtle WoW Database](https://github.com/slowtorta/turtlewow-bug-tracker/assets/86041826/4bfab48c-7ff0-4f08-a8f0-e7a5ca54ad99)

Wowhead:
![Screenshot 2023-10-28 Classic Rare Cloth Chest Armor](https://github.com/slowtorta/turtlewow-bug-tracker/assets/86041826/2ff1663a-3779-4d11-b1e3-50687a26ba07)

**Comment by slowtorta** [comment]
Same issues: https://github.com/slowtorta/turtlewow-bug-tracker/issues/4927
