### ISSUE TITLE
Dying in Karazhan Crypt will randomly spawn you at Darkshire graveyard

### ISSUE THREAD

**Issue by krautchanpro** [slowtorta/turtlewow-bug-tracker#4937]
**Please, provide a clear description what the bug is:**
When you die in Karazhan Crypt, it will sometimes spawn you at the Darkshire graveyard. It seems to happen more often when you are far in the instance.

**Steps to reproduce the behavior with as much detail as possible:**

1. Die in Karazhan Crypt far in the instance
2. Sometimes you will spawn at Darkshire instead of the graveyard in front of Karazhan Crypt

**IDs of affected creatures, items, quests or spells with a link to the relevant page:**
Yourself

**Expected behavior. Describe how it should work:**
You should always spawn at the Karazhan Crypt graveyard in front of the instance when you die.

**Comment by Muigin** [comment]
This is already known and the solution is being worked on for the next client patch.  There was an oversight in painting the copies of overworld sections of Karazhan Crypts with unique Area IDs, rather then their vanilla default of "Duskwood" in places and "Deadwind Pass" in others. This results in incorrect graveyard assignment.

**Comment by twowTurtReynolds** [comment]
![image](https://github.com/slowtorta/turtlewow-bug-tracker/assets/151180101/f8f746fb-a0e5-44a8-a3d8-0672152ac5a9)
Dying at front door is fine.

![image](https://github.com/slowtorta/turtlewow-bug-tracker/assets/151180101/306007d6-e567-4dee-8c0b-156a51b44f98)
Dying by corpsemuncher sends you here...

**Comment by twowTurtReynolds** [comment]
Fixed in 1.17.1
