### ISSUE TITLE
Moroes Phase 1 in Lower Karazhan Halls doesn't transition to the next phase and instead continues to attack the players and instantly heals to full at low HP

### ISSUE THREAD

**Issue by patrycos** [slowtorta/turtlewow-bug-tracker#4941]
**Please, provide a clear description what the bug is:**
Moroes in Lower Karazhan Halls does not turn friendly after saying his line "Most impressive, it would appear your skills do match your bravery." and instead continues to fight the players. When he's reduced to about 10% health, he instantly heals to full. The cycle continues indefinitely. The situation occured in 2 separate attempts.

**Steps to reproduce the behavior with as much detail as possible:**
1.  Fight Moroes
2.  Reduce him to about 40-50% health
3.  Moroes does not transition, instead he remains hostile and keeps attacking players

**IDs of affected creatures, items, quests or spells with a link to the relevant page:**
Moroes Phase 1: https://database.turtle-wow.org/?npc=61225
Instance ID: 25700

**Expected behavior. Describe how it should work:**
Moroes is supposed to turn friendly after losing a portion of his health and transition to Phase 2.

**Comment by AkalixFrost** [comment]
Fixed in previous update.
