### ISSUE TITLE
Item: [Invocation of Arcane Fortitude] cannot be used.

### ISSUE THREAD

**Issue by HollsEnd** [slowtorta/turtlewow-bug-tracker#4944]
The item [Invocation of Arcane Fortitude] cannot be used. Trying to apply it to any leg or head piece tells the player "That item is not a valid target."
Clearing WDB cache did not change anything.

1. Use the enchant on a Head or Leg armor piece.
2. Game tells you: "That item is not a valid target."

Item: https://database.turtle-wow.org/?item=92008
Spell: https://database.turtle-wow.org/?spell=57154

The enchant should be able to be applied to any leg or head armor piece.

**Comment by Muigin** [comment]
Duplicate of #4788
