### ISSUE TITLE
My character can't train mining.

### ISSUE THREAD

**Issue by PumpkinKingBG** [slowtorta/turtlewow-bug-tracker#4946]
**Please, provide a clear description what the bug is:**
My warrior can't click on mining training even tho it comes up as green.
On top of all I randomly have leatherworking, which I haven't traded.
**Steps to reproduce the behavior with as much detail as possible:**

1.Went to trainer.
2. Saw basic mining in green.
3. Could not train it.

**IDs of affected creatures, items, quests or spells with a link to the relevant page:**

NPC: Mining old town Stormwind

**Expected behavior. Describe how it should work:**
When you click on mining train it should train your char.
If you have 2 proffs it should remove one in its place.
I randomly have leatherworking which I don't need or have taken.

**Comment by PumpkinKingBG** [comment]
Char name JackOLantern EU server

**Comment by PumpkinKingBG** [comment]
![WoWScrnShot_102823_232619](https://github.com/slowtorta/turtlewow-bug-tracker/assets/88507179/245ff5fb-2148-449f-82f2-6f93472c1204)

**Comment by Muigin** [comment]
https://armory.turtle-wow.org/#!/character/jackolantern
You have Alchemy and Herbalism trained.  You cannot train more than 2 primary professions.  Unlearn one in order to learn Mining.

Working as intended.
