### ISSUE TITLE
Lady Illucia Barov in Scholomance is missing her Skin of Shadow loot

### ISSUE THREAD

**Issue by Azeron223** [slowtorta/turtlewow-bug-tracker#4947]
In Scholomance after killing [Lady Illucia Barov](https://database.turtle-wow.org/?npc=10502) (NPC ID: 10502) she is supposed to have a [Skin of Shadow Container](https://database.turtle-wow.org/?object=175964)  (Object ID: 175964) to the right as you look at her, however this item does not spawn at all.

I beleive the item is either supposed to either be there at all times, or there's a script to spawn it upon her death.

**Comment by twowTurtReynolds** [comment]
Skin of Shadows are a bit confusing, the method to obtain them changed from early to late vanilla.

According to https://www.wowhead.com/classic/item=12753/skin-of-shadow#comments:id=3229337 the object is removed with late vanilla, and turtle is on naxx patch.
