### ISSUE TITLE
[A Diplomatic Mission]  quest bug

### ISSUE THREAD

**Issue by 66wudi** [slowtorta/turtlewow-bug-tracker#4951]
**Please, provide a clear description what the bug is:**

**Steps to reproduce the behavior with as much detail as possible:**

1.  I accepted the mission [A Diplomatic Mission] in Slivermoon Remnant
2.  The quest requires me to find the four leaders of the alliance. But since I couldn’t find the dwarf leader and there was no space in my backpack, I deleted the completed letters to the human and dwarf leaders.  Although the quest of signing letters from the leaders of humans and dwarves has been completed, I still deleted 2 letters from my backpack.
3.  When I have time, when I want to start the quest again.
The letter quests for humans, dwarves, and elves are no longer available.  This also resulted in the inability to find and complete the letters required in quest [A Diplomatic Mission]  .

**IDs of affected creatures, items, quests or spells with a link to the relevant page:**

NPC: https://database.turtle-wow.org/?npc=  Ranger-General Damilara Sunsorrow
Item: https://database.turtle-wow.org/?item=
Quest: https://database.turtle-wow.org/?quest=  [A Diplomatic Mission]
Spell: https://database.turtle-wow.org/?spell=
Object: https://database.turtle-wow.org/?object=  Letter lost

**Expected behavior. Describe how it should work:**
If the letter is deleted, the tasks signed by the leader will not be shown as completed.
To prevent BUG problems

I am Human paladin HC player :  Sixdancer

**Comment by Muigin** [comment]
Pushing this to the devs to request a... user-protection solution be incorporated into each of the Alliance leaders.

Please be more careful with your quest items from now on.
