### ISSUE TITLE
The quest Snarlclaw is not marked as Elite

### ISSUE THREAD

**Issue by octav3k** [slowtorta/turtlewow-bug-tracker#4959]
**Please, provide a clear description what the bug is:**
The quest Snarlclaw is not marked as Elite, even though the NPC you need to kill for it is.

**Steps to reproduce the behavior with as much detail as possible:**
1. Travel to Gilneas
2. Acquire the quest
3. Clear into the cave until you find Snarlclaw

**IDs of affected creatures, items, quests or spells with a link to the relevant page:**
NPC: https://database.turtle-wow.org/?npc=61405
Quest: https://database.turtle-wow.org/?quest=40945

**Expected behavior. Describe how it should work:**
The quest should be marked as Elite, as it requires you to kill an Elite NPC.

**Comment by Muigin** [comment]
This will be fixed in the next maintenance.
