### ISSUE TITLE
The quest Rise, Obsidion! does not share with the whole group when accepted

### ISSUE THREAD

**Issue by octav3k** [slowtorta/turtlewow-bug-tracker#4960]
**Please, provide a clear description what the bug is:**
The quest Rise, Obsidion! does not get shared to the whole group when one player accepts it.

**Steps to reproduce the behavior with as much detail as possible:**
1. Group up and have everyone turn in the previous quest (Release Them)
2. Start the quest Rise, Obsidion
3. Notice that you have to repeat the event for every player in the group

**IDs of affected creatures, items, quests or spells with a link to the relevant page:**
Quest: https://database.turtle-wow.org/?quest=3566

**Expected behavior. Describe how it should work:**
The quest should be shared to the entire group, similar to other escort/event quests.

**Comment by cyaohiri** [comment]
Replicated on VMaNGOS.

**Comment by twowTurtReynolds** [comment]
It seems to be the same on PTR, where everyone has about a 30 second window to pick up the two quests.

![image](https://github.com/slowtorta/turtlewow-bug-tracker/assets/151180101/305cf0dc-fa36-4974-9585-65b4efee9cdf)

If you can demonstrate otherwise OP, please let us know.
