### ISSUE TITLE
turtlewow-asia  hogger

### ISSUE THREAD

**Issue by kunlunwong** [slowtorta/turtlewow-bug-tracker#4961]
**Please, provide a clear description what the bug is:**

**Steps to reproduce the behavior with as much detail as possible:**
服务器:霍格
1.安其拉废墟，无疤者奥斯里安打完，没有掉落任何物品
人员：bestxp（RL）      力哥无敌    饮水机一号     残留下的温度    傻蛋   疼三命   老子不讲武德    Jibochu      Weisiji    傻蛋    箭羽吉光   招财猫猫   奥德膘    Pitoff      饮水机一号   磊爷无敌       巴布耳   百事阔落   向原平冲锋      
副本ID：11278

**IDs of affected creatures, items, quests or spells with a link to the relevant page:**

NPC: https://database.turtle-wow.org/?npc=
Item: https://database.turtle-wow.org/?item=
Quest: https://database.turtle-wow.org/?quest=
Spell: https://database.turtle-wow.org/?spell=
Object: https://database.turtle-wow.org/?object=

**Expected behavior. Describe how it should work:**

**Comment by terrysqzr** [comment]
我昨天TAQ二号打完也是，维姆尸体也消失了，拾取都没看到

**Comment by twowTurtReynolds** [comment]
请用英文提交问题。我们无法通过自动翻译准确地翻译中文提交的错误报告，这使得我们难以理解问题的确切性质。谢谢！

Please submit the issues in English. We're unable to accurately translate bug reports submitted in Chinese through automatic translation, which makes it difficult for us to understand the exact nature of the issue. Thank you!
