### ISSUE TITLE
Quest disappears in quest log

### ISSUE THREAD

**Issue by kazabian** [slowtorta/turtlewow-bug-tracker#4962]
**Please, provide a clear description what the bug is:**

Hello. My name is Revain and I am a level 12 high elf Paladin in Turtle Wow "Original Server." I was questing in Teldrassil when I suddenly lost all my quests in the quest log. I am using pfQuest. I tried closing Wow and logging back again. It worked. From here on, whenever I loot a quest item, kill a quest target or turn in a quest; the quest log disappears. Using "Reset Everything" in pfQuest config is much faster in getting the quests back than closing the game and logging back. Thank you!

**Steps to reproduce the behavior with as much detail as possible:**

1. 
2. 
3. 

**IDs of affected creatures, items, quests or spells with a link to the relevant page:**

NPC: https://database.turtle-wow.org/?npc=
Item: https://database.turtle-wow.org/?item=
Quest: https://database.turtle-wow.org/?quest=
Spell: https://database.turtle-wow.org/?spell=
Object: https://database.turtle-wow.org/?object=

**Expected behavior. Describe how it should work:**

**Comment by Muigin** [comment]
Could not reproduce.

This sounds like an addon issue.  This section is for reports related to base game behavior.
