### ISSUE TITLE
Vial of Potent Venoms won't proc with Druid's Swipe

### ISSUE THREAD

**Issue by torrenteeselkmanda** [slowtorta/turtlewow-bug-tracker#4964]
**Please, provide a clear description what the bug is:**

Vial of Potent Venoms won't proc with Druid's Swipe. It does proc with warrior's Cleave

**Steps to reproduce the behavior with as much detail as possible:**

1. have Vial of Potent Venom equipped as a Druid https://database.turtle-wow.org/?item=61243
2. Go bear form on a target dummy and face sideways so you won't autoattack but can swipe
3. Swipe and watch trinket not proccing

**IDs of affected creatures, items, quests or spells with a link to the relevant page:**

Item: https://database.turtle-wow.org/?item=61243

Spell: https://database.turtle-wow.org/?spell=9908

**Expected behavior. Describe how it should work:**

It should proc off swipe i guess? i lack info about this

**Comment by welpenhund** [comment]
Tooltip clearly says "Your melee and ranged attacks" (aka autohits) have a chance to apply this.
Swipe is an ability/spell and should not proc it, else the tooltip would say "Your melee and ranged abilitys have a chance...."

**Comment by Dragunovi** [comment]
This interaction originally existed but had to be removed due to being too powerful, the trinket should only proc from single target abilities and attacks.
