### ISSUE TITLE
The Pariah's Instructions gems loot

### ISSUE THREAD

**Issue by darkhorror1984** [slowtorta/turtlewow-bug-tracker#4968]
You can loot gems from Khans with completed or without quest The Pariah's Instructions

**Steps to reproduce the behavior with as much detail as possible:**

1. Go to Maraudon without quest The Pariah's Instructions
2. Kill Khans with friend who have The Pariah's Instructions quest
3. You can loot gems from coarses.

**IDs of affected creatures, items, quests or spells with a link to the relevant page:**

NPC: https://database.turtle-wow.org/?npc=13742
         https://database.turtle-wow.org/?npc=13741
         https://database.turtle-wow.org/?npc=13740
         https://database.turtle-wow.org/?npc=13739
         https://database.turtle-wow.org/?npc=13738
Item: https://database.turtle-wow.org/?item=17761
         https://database.turtle-wow.org/?item=17762
         https://database.turtle-wow.org/?item=17763
         https://database.turtle-wow.org/?item=17764
         https://database.turtle-wow.org/?item=17765
Quest: https://database.turtle-wow.org/?quest=7067

You can't loot gems if u completed or haven't quest The Pariah's Instructions.

**Comment by Muigin** [comment]
This is working as intended.  You do not need to be on the quest to acquire the gems, but you do need to be on the quest to acquire the Amulet of Spirits which would allow you to engage the Khans.  This is similar to how you can acquire the Seal of Ascension gems without being on the quest first.
