### ISSUE TITLE
Warlock Pet Abilities Not Having Manual Cooldown (Second Attempt at Ticket)

### ISSUE THREAD

**Issue by triana2021** [slowtorta/turtlewow-bug-tracker#497]
Issue:
Warlock pet ability cooldowns not applying to manually pressing  pet ability buttons.
I opened a ticket about this 20 days ago and it was closed due to formatting issues. 

To reproduce:
1. Summon Succubus
2. Press Lash of pain every 1.5 seconds
3. See that cooldown is not applied; try with other pets.

Expected behavior:
1. Cooldowns apply both to auto-engage spell and manually pressing them.

**Comment by Velite12** [comment]
This is possibly part of a larger issue in vmangos where NPCs do not follow the listed spell cooldowns and just cast constantly.

**Comment by CosminPOP** [comment]
fixed a few weeks back.
