### ISSUE TITLE
Nordanaar Herbal Tea is infinite

### ISSUE THREAD

**Issue by Kharkov72** [slowtorta/turtlewow-bug-tracker#4971]
Probably because of possibly unintended stacking behavior, where they can stack up to 5 a slot. When it's stacked, using it will not consume a charge.
https://database.turtle-wow.org/?item=61675
just stop them from stacking in the inventory would probably bandaid fix it idk

**Comment by Muigin** [comment]
A fix for this has already been made and is being tested to be pushed on our next maintenance.

**Comment by Kharkov72** [comment]
@Muigin bug not fixed properly, lots of varying errors caused by this, from teas (when stacked) figuring their charges incorrectly (haven't tested duping, but charges will get eaten), including when it uses one of the stacked teas, going to the next with only a single charge.
![Untitled](https://github.com/slowtorta/turtlewow-bug-tracker/assets/25846834/24497b52-fd6c-40bb-a123-10095fe9f8b7)

on the flipside, if each tea is meant to be a single use like potions, then teas obtained prior to this update will have not been updated correctly, and will still have 3 charges. None will be consumed on use.
![Untitled](https://github.com/slowtorta/turtlewow-bug-tracker/assets/25846834/f491147d-5d47-4354-bdce-9ee299c01158)

if you want them to stack, make them single use. if you don't, make them three like the other tea. idk. or you need to push something to update all teas to the correct amount of charges.
