### ISSUE TITLE
Greathorn Howl dropping incorrect items.

### ISSUE THREAD

**Issue by OonaFae** [slowtorta/turtlewow-bug-tracker#4973]
**Please, provide a clear description what the bug is:**
When killing a Greathorn Owl occasionally you will find it droping Misthoof Hide, this is incorrect.
**Steps to reproduce the behavior with as much detail as possible:**

1. Kill Greathorn Owl
2. See they occasionally drop Misthoof Hide
3. Assume that the owl ate the stag I guess?
![image](https://github.com/slowtorta/turtlewow-bug-tracker/assets/105398809/d8739805-e661-4cb1-81a9-16930b0f39b9)

**IDs of affected creatures, items, quests or spells with a link to the relevant page:**

NPC: https://database.turtle-wow.org/?npc=61336
Item: https://database.turtle-wow.org/?item=61712

**Expected behavior. Describe how it should work:**
I would assume this is only supposed to drop from the Stag, unsure about the other variations of owls in Hyjal or the Stags, just ran across this one so far but its probably worth checking..

**Comment by twowTurtReynolds** [comment]
DB right now says it only drops from the misthoof mobs now, a dev must have already fixed this.

![image](https://github.com/slowtorta/turtlewow-bug-tracker/assets/151180101/2f613562-dcd9-4b1a-b589-4df119c64e6e)
Killed some birds, looks good.
