### ISSUE TITLE
Pvp Rank 0

### ISSUE THREAD

**Issue by Allmisc** [slowtorta/turtlewow-bug-tracker#4978]
My pvp rank is 0. Although I've been told that with the new pvp system in place you're supposed to have your highest rank which in my case is Knight- Captain. I've been offline for a long time. Before the implementation I had my rank Hidden from view.

1. I logged in Ive been offline for a few months.
3. I have a hidden Pvp rank.
4. I removed WDB without affect according to GM's orders through ticket.

![screenshot 15](https://github.com/slowtorta/turtlewow-bug-tracker/assets/34582665/3fb34017-09f8-470b-bf5a-0c33d3a9f8f4)

**Comment by Muigin** [comment]
There is an NPC that hides and unhides your PvP rank called <Wheeler Dealer>.  Please locate this NPC to unhide your PvP rank.
