### ISSUE TITLE
Alah'thalas missing Shady Dealer and proper signposting/guard dialogue, and further suggestions.

### ISSUE THREAD

**Issue by PotatoKnight** [slowtorta/turtlewow-bug-tracker#4979]
**Please, provide a clear description what the bug is:**

I'm not sure this is a bug more than it is a glaring omission but I wasn't sure how else or where else to inform you of it. 

Alah'thalas, the High Elf capital equivalent , lacks a Shady Dealer (the NPCs that sell reagents for poisons). Given it has a rogue trainer, it seems reasonable to me that it should also have a Shady Dealer. Further, Alah'thalas needs better sign posting and ideally the ability to speak with guards there to be able to find your way around.

_**As a second, separate point, and the rest is more of a suggestion than an accusation of glaring omission. Alah'thalas could also do with the following:**_

An auctioneer.
A bank.
In general all the facilities a capital city offers.

I put these in more of a 'suggestion' tier because of the effective adjacency to Stormwind, but I think it's justified given Ironforges effective adjacency to Stormwind but also being fully stocked with these things.

**Steps to reproduce the behavior with as much detail as possible:**

1. Go to Alah'thalas
2. Mourn for better facilities there.
3. Weep.

**Expected behavior. Describe how it should work:**

Alah'thalas should have everything it logically should have, with the Shady Dealer and better signposting, and more of a suggestion: be a fully functioning capital city.

**Comment by Zmitrok1984** [comment]
Looks into new High Elf starting zone and capital city rewamp in patch 1.17.1.
Think that all will be here

**Comment by twowTurtReynolds** [comment]
The current indev Alahthalas rework still doesn't have one. I am bringing this to the team.

**Comment by twowTurtReynolds** [comment]
He's in!
