### ISSUE TITLE
Blessing of Wisdom and mp5 Food buffs do not stack

### ISSUE THREAD

**Issue by discslack** [slowtorta/turtlewow-bug-tracker#498]
**Please, provide a clear description what the bug is:**

Paladin spell Blessing of Wisdom providing mp5 should stack with mp5 food buff. It currently does not.

**Steps to reproduce the behavior with as much detail as possible:**

1. Apply max rank Blessing of Wisdom
2.  Eat mp5 food i.e. nightfin soup
3.  Notice mp5 does not increase on character sheet

**IDs of affected creatures, items, quests or spells with a link to the relevant page:**

Item: https://database.turtle-wow.org/?item=13931

Spell: https://database.turtle-wow.org/?spell=25961

**Expected behavior. Describe how it should work:**

The mp5 effect from food buff should stack with Blessing of Wisdom

**Comment by Velite12** [comment]
![image](https://user-images.githubusercontent.com/45871932/144495659-1017acbe-f38c-4d33-b32e-3ed19bb486c2.png)
It does though.

**Comment by discslack** [comment]
![mp5 bug](https://user-images.githubusercontent.com/95150426/144512108-93874bcf-7a82-4cb5-987d-d6d31f036aa1.JPG)

I have food buff and wisdom but only wisdom shows in the combat log

**Comment by Velite12** [comment]
The sagefish buff is like Mp5 gear it won't show in the combat log, but it is there, I tested and everything does stack.

**Comment by discslack** [comment]
You say it won't show in the combat log but you have a screenshot showing 8 mana from "Mana Regneration"? 
What testing proved it stacks?

**Comment by Velite12** [comment]
Well fed and nightfin are both "buffs" sure in that regard, but the actual effect of the buff of nightfin is actually shown in the log which is what I mean, the general "Well Fed" effect is always passive and not shown on combat log. But the Nightfin buff is not well fed it's "Mana Regeneration". 

![image](https://user-images.githubusercontent.com/45871932/144522901-974f80f0-de76-4235-b8c9-5443203e3167.png)

**Comment by discslack** [comment]
Ok that is strange that they are classified differently but thank for clarifying and explaining the method
