### ISSUE TITLE
The Lion Horn of Stormwind

### ISSUE THREAD

**Issue by MpTFridge** [slowtorta/turtlewow-bug-tracker#4980]
**Please, provide a clear description what the bug is:**
The Lion Horn of Stormwind trinket is not providing casting speed like the item tooltip suggests. The item description describes an increase to party's attack speed and cast speed by 5%. When the buff is active, the buff tooltip only mentions attack speed and a priest I regularly play with has expressed they are not getting faster attack speeds when the horn is active for the group.

**Steps to reproduce the behavior with as much detail as possible:**
1. Equip the trinket.
2. Enemies attack trinket wearer to produce the trinket activation.
3. Mouse over buff to read it, or mouse over casting speed to verify.

**IDs of affected creatures, items, quests or spells with a link to the relevant page:**
Item: https://database.turtle-wow.org/?item=14557

**Expected behavior. Describe how it should work:**
Expect the trinket to also increase casting speed by 5% as the item tooltip suggests. If it is not intended for casting speed to be affected, then removal of the text from the item to not be misleading.

Thanks!!

**Comment by 0Moon01** [comment]
The issue was the aura from the proc was not properly applying the 3 of the buffs to the party. Will be fixed.

**Comment by Muigin** [comment]
Moon's fix has been pushed and will take effect on the next maintenance.

Thank you for your report.
