### ISSUE TITLE
Fishing empity nodes

### ISSUE THREAD

**Issue by Wilsonsds** [slowtorta/turtlewow-bug-tracker#4981]
**Please, provide a clear description what the bug is:**

**Steps to reproduce the behavior with as much detail as possible:**

1. Telabin and some places in winterlands, may be in other high level pools as well
2. you fish an empity node
3. frustrating

![Captura de tela 2023-10-30 172553](https://github.com/slowtorta/turtlewow-bug-tracker/assets/148484120/d993532e-4fab-4cea-a12b-46f100dbb177)

**IDs of affected creatures, items, quests or spells with a link to the relevant page:**

NPC: https://database.turtle-wow.org/?npc=
Item: https://database.turtle-wow.org/?item=
Quest: https://database.turtle-wow.org/?quest=
Spell: https://database.turtle-wow.org/?spell=
Object: https://database.turtle-wow.org/?object=

**Expected behavior. Describe how it should work:**

**Comment by twowTurtReynolds** [comment]
tracking this under the dupe https://github.com/slowtorta/turtlewow-bug-tracker/issues/4981
