### ISSUE TITLE
Can't use fishing lures as vagrant

### ISSUE THREAD

**Issue by Kangaroux** [slowtorta/turtlewow-bug-tracker#4983]
Fishing lures should not count as enchantments IMO. They don't provide any combat advantage. It simply makes leveling the profession even more tedious.

![image](https://github.com/slowtorta/turtlewow-bug-tracker/assets/2302541/953c2d6b-cd9f-4873-94c0-c0fb096b8d95)
![image](https://github.com/slowtorta/turtlewow-bug-tracker/assets/2302541/e6e7c497-453e-4c0c-9deb-e290c69db9e0)

**Comment by Muigin** [comment]
A fix has been pushed by Jamey and these temporary enchants should work on Vagrants after the next maintenance.

Thank you for your report.
