### ISSUE TITLE
Totem of Crackling Thunder Procrate Unchanged after October 30th

### ISSUE THREAD

**Issue by Niqlo** [slowtorta/turtlewow-bug-tracker#4984]
**Please, provide a clear description what the bug is:**
In the October 30th patch notes, totem of crackling thunder proccing off a lightning bolt was listed as having been increased to a 10% proc chance. However, the proc chance still seems to be 5%.

![image](https://github.com/slowtorta/turtlewow-bug-tracker/assets/109690174/9e4dbc68-85d1-4414-bf5b-14c0bec4ce89)

24/500 = 4.8%

**Steps to reproduce the behavior with as much detail as possible:**

1. equip totem of crackling thunder
2. cast spells until you gather a decent data set
3. calculate proc rate

**IDs of affected creatures, items, quests or spells with a link to the relevant page:**

Item: https://database.turtle-wow.org/?item=61292
Spell: https://database.turtle-wow.org/?spell=15208

**Expected behavior. Describe how it should work:**
proc chance should be 10% as listed in October 30th patch notes.

**Comment by twowTurtReynolds** [comment]
Tested on the PTR for 2 mins, felt like I was getting a proc every 7 casts. Let me know if there are further issues with further tests.
