### ISSUE TITLE
I didn't give me ice pear of kaneq\'nuun after completing Tarqsiku slain for Panukuki

### ISSUE THREAD

**Issue by yinzhao77** [slowtorta/turtlewow-bug-tracker#4986]
I didn't give me ice pear of kaneq\'nuun after completing Tarqsiku slain for Panukuki

1.I killed the crab
2. l killed tarqsiku
3. no task rwards

NPC: panukuki
Item: ice pearl of kaneq\'nuun
Quest:Tarqsiku slain
Spell:
Object:yinyuef

Please note that the ID of this item in your database is preceded by a capital letter i and the full name is <ice pearl of kaneq\'nuun>

**Comment by yinzhao77** [comment]
Ice Pearl of Kaneq\'nuun

**Comment by Muigin** [comment]
Could not reproduce just now on test realm.  Please close the game, delete your WDB (cache) folder, and log back in.  Ensure you have no quest addons enabled, and see if you did, in fact, complete the quest or receive the reward.

If this does not help, please make a GM ticket.

**Comment by yinzhao77** [comment]
Ice Pearl of Kaneq\'nuun add before\'
