### ISSUE TITLE
[Suggestion thread] Shaman Restoration tree Healing Grace talent improvement.

### ISSUE THREAD

**Issue by KreepAK** [slowtorta/turtlewow-bug-tracker#4988]
Greetings,

I want to suggest a small change to the talent [Healing Grace].

How it works right now: Reduces the threat generated by your heaking spells by 5% 0/3. 15% 3/3.

My suggestion is: Reduces the threat generated by your spells and abilities by 3% 0/3. 10% 3/3.

Basically, make threat reduction available for Enhancement and Elemental builds too.

Thank you!

UPDATE!!!

This is final adjustment to this thread. I visualized the sync in row 2 with between Healing Grace and Natures Guidance (3% hit talent). In the first glance, this small reconstruction in Restoration Tree might look useless, but I'm sure it will become profitable in the long run.

P.S. This is a copy of a topic on Suggestion forum https://forum.turtle-wow.org/viewtopic.php?t=11108. A copy paste it here because I see no reaction to it. Thank you for understanding.

**Comment by Muigin** [comment]
The bugtracker is for posting bugs.  Please make suggestions on the appropriate section of the forums.
