### ISSUE TITLE
Shredder Operating Manual  pages  does not drop.

### ISSUE THREAD

**Issue by Tinyfin-github** [slowtorta/turtlewow-bug-tracker#499]
Shredder Operating Manual  pages  does not drop.

Issue discovered from reports from multiple players and attempts to reproduce the proper behavior by aoe farming  on a gm character abusing the respawn command and aoe insta kill. I was unable to get any pages to drop. Even with the low drop rate, i should have been able to get at least 1random page to drop.

As the farming location for testing purpose  i used the  Satyrs in Satyrnaar  and the Furbolgs in the Thistlefur Village and Hold

https://database.turtle-wow.org/?search=bleakheart  -Satyrs in Satyrnaar 
https://database.turtle-wow.org/?search=Thistlefur#npcs Furbolgs in the Thistlefur Village and Hold

https://database.turtle-wow.org/?search=Shredder+Operating+Manual  Shredder Operating Manual  pages

https://database.turtle-wow.org/?quest=6504 Quest the lost pages.

**Comment by RainElysium** [comment]
Fixed.
