### ISSUE TITLE
Getting exp from grey mobs on Tel'Abim realm

### ISSUE THREAD

**Issue by Khagrim** [slowtorta/turtlewow-bug-tracker#4994]
**Please, provide a clear description what the bug is:**
Was doing a low lvl quests in Durotar on Tel'Abim realm and noticed i am getting full experience from grey level mobs. I have rested exp
**Steps to reproduce the behavior with as much detail as possible:**

1.
2. 
3. 

**IDs of affected creatures, items, quests or spells with a link to the relevant page:**

NPC: https://database.turtle-wow.org/?npc=
Item: https://database.turtle-wow.org/?item=
Quest: https://database.turtle-wow.org/?quest=
Spell: https://database.turtle-wow.org/?spell=
Object: https://database.turtle-wow.org/?object=

**Expected behavior. Describe how it should work:**

**Comment by twowTurtReynolds** [comment]
Which mobs? I'll test a few at random.

**Comment by twowTurtReynolds** [comment]
Killed some lv 6 scorpids and boars at lv 12 with rested. No XP.
