### ISSUE TITLE
Brainwashing device upon server restart

### ISSUE THREAD

**Issue by baddecisiondan** [slowtorta/turtlewow-bug-tracker#4995]
**Please, provide a clear description what the bug is:**
Brainwashing device removed one of my specs upon server restart because i leveled before restart and didn't switch specs to put a point in and save the other spec........ lost gold invested into using the device, now have no gold, can't use device again because it increases in expense to set talents.

**Steps to reproduce the behavior with as much detail as possible:**

1.  Used brainwashing device to save spec (balance druid primary).
2.  forced to spend gold in order to save secondary spec (resto druid secondary)
3.  was healing a dungeon and leveled up before server restart and added points into active spec (resto)
4.  Logged back in, because i did not put points into balance and save it yet, it removed primary spec, made resto (because it was my active spec) my primary.
5. Now my balance spec is gone, I don't have gold to respec in order to save another spec, so my gold is gone and the goblin brainwashing device is now useless for me because server restart scuffed it.

**IDs of affected creatures, items, quests or spells with a link to the relevant page:**

NPC: https://database.turtle-wow.org/?npc=
Item: https://database.turtle-wow.org/?item=
Quest: https://database.turtle-wow.org/?quest=
Spell: https://database.turtle-wow.org/?spell=
Object: https://database.turtle-wow.org/?object=

**Expected behavior. Describe how it should work:**
Set talents and save talents as primary.  Activate a secondary spec that is 0/0/0, spend talents and save secondary spec....

**Comment by Jianthawiian** [comment]
Having the same issue, would love to have the gold and respec counter refunded!

**Comment by Muigin** [comment]
This has been fixed as of today's maintenance.
