### ISSUE TITLE
Desolace Centaur bug

### ISSUE THREAD

**Issue by khuongdo0214** [slowtorta/turtlewow-bug-tracker#4996]
**Please, provide a clear description what the bug is:**
Character cannot talk to the Magram centaur quest givers in Desolace even though I'm honored with them. Also when I hover over the other centaurs there's a sword icon which should not happen.

**Steps to reproduce the behavior with as much detail as possible:**

1. Go to the Magram village in Desolace.
2.  Hover on any centaur.
3.  Try talking to the centaur quest givers.

**IDs of affected creatures, items, quests or spells with a link to the relevant page:**

NPC: https://database.turtle-wow.org/?npc=5398
Item: https://database.turtle-wow.org/?item=
Quest: https://database.turtle-wow.org/?quest=1371
Spell: https://database.turtle-wow.org/?spell=
Object: https://database.turtle-wow.org/?object=

**Expected behavior. Describe how it should work:**
I should be able to talk to the quest givers there since I am honored.

**Comment by Muigin** [comment]
Go to your Reputation tab, find Magram, turn off At War.

Working as intended.

**Comment by khuongdo0214** [comment]
thanks for the fast response! Extremely happy I donated
