### ISSUE TITLE
Quest item not dropping for quest progression - Jadefire Revenge

### ISSUE THREAD

**Issue by yrazu05** [slowtorta/turtlewow-bug-tracker#4997]
**Please, provide a clear description what the bug is:**

Quest name - "Jadefire Revenge" 
Killing specific mobs tagged as "Jadefire" satyrs does not drop Jadefire Felhorn for quest progression

**Steps to reproduce the behavior with as much detail as possible:**

1. Killing specific mobs tagged as "Jadefire" satyrs does not drop Jadefire Felhorn for quest progression
2. 
3. 

**IDs of affected creatures, items, quests or spells with a link to the relevant page:**

NPC: https://database.turtle-wow.org/?npc=7111
NPC: https://database.turtle-wow.org/?npc=7107
NPC: https://database.turtle-wow.org/?npc=7108
NPC: https://database.turtle-wow.org/?npc=7109
NPC: https://database.turtle-wow.org/?npc=7105
NPC: https://database.turtle-wow.org/?npc=7106
Item: https://database.turtle-wow.org/?item=60295
Quest: https://database.turtle-wow.org/?quest=40211
Spell: https://database.turtle-wow.org/?spell=
Object: https://database.turtle-wow.org/?object=

**Expected behavior. Describe how it should work:**
Item should drop at specific percentages for these mobs after a number of certain kills

**Comment by twowTurtReynolds** [comment]
Took me about 50 kills but I got the quest complete on the PTR. All is working correctly to match the DB :)
