### ISSUE TITLE
Quest "In dreams" is bugged

### ISSUE THREAD

**Issue by WarwaraQxey** [slowtorta/turtlewow-bug-tracker#5]
By opening this Issue, I admit to having done the pertinent research using sources from Vanilla (preferably) or Classic. I also understand that sources from other private servers are not acceptable.

**Current behavior**: 
Quest "In dreams" seems to be broken. I got to the part, when i should talk to Highlord Tielan, but right clicking him does not open dialog window.
**Expected behavior**: 
dialog window and further scripted quest
**Proofs**:
![image](https://user-images.githubusercontent.com/78602360/107041002-3e356300-67c0-11eb-9762-75b8ccf83587.png)

**Steps to reproduce**:

1. get scarlet crusader disguise
2. get to Mardenholde Keep
3. right click Highlord Tielan

btw I have a script that clears my WBD folder each launch of the game. So I do not think that WDB can be causing this issue.

**Comment by slowtorta** [comment]
Hello. Sorry for slow response. This bug is related to our client modifications and it's fixed in the upcoming 1.15.1 update. I have no ETA on when it's ready. For now GMs are solving this manually for each player.

**Comment by WarwaraQxey** [comment]
ok, i see, i will raise a ticket then
