### ISSUE TITLE
Stormborn's Cape model broken

### ISSUE THREAD

**Issue by JvMarchetti** [slowtorta/turtlewow-bug-tracker#50]
The custom cape "Stormborn's Cape" model is broken, it is easily seen when walking 

**Current behavior**: 

Broken model

**Expected behavior**: 

Not broken model

**Proofs**:

![Screenshot_1](https://user-images.githubusercontent.com/85771279/121971931-4db94f80-cd50-11eb-9007-82dd12841846.png)
![Screenshot_2](https://user-images.githubusercontent.com/85771279/121971940-4e51e600-cd50-11eb-8778-b87b533799e8.png)

**Steps to reproduce**:

1. Equip the Stormborn's Cape
2. Walk

**Comment by slowtorta** [comment]
This is a general model problem for High Elven cloaks.

Thanks for reporting it. It'll be fixed in some very distant client update. 
We do not know how to do it yet.
