### ISSUE TITLE
There is no hint of reward allocation

### ISSUE THREAD

**Issue by Weitian0620** [slowtorta/turtlewow-bug-tracker#5000]
**Please, provide a clear description what the bug is:**

**Steps to reproduce the behavior with as much detail as possible:**

1.ID Himula
2.  When I killed the Dark Master Gandin, there was no pick-up reward, so I had no pick-up option, neither greed nor need
3. 

**IDs of affected creatures, items, quests or spells with a link to the relevant page:**

NPC: https://database.turtle-wow.org/?npc=1853
Item: https://database.turtle-wow.org/?item=16731
Quest: https://database.turtle-wow.org/?quest=
Spell: https://database.turtle-wow.org/?spell=
Object: https://database.turtle-wow.org/?object=

**Expected behavior. Describe how it should work:**

**Comment by twowTurtReynolds** [comment]
Sounds to me like your party leader set it to master loot and you didn't notice. We will need video proof from you of this bug happening with group loot on before the kill completes, for us to reopen.
