### ISSUE TITLE
Rugged armor kit item level restriction don't work

### ISSUE THREAD

**Issue by AKryukov92** [slowtorta/turtlewow-bug-tracker#5002]
Rugged armor kit now has description "Only usable on items level 35 and above."
Tested as of 2023-11-01 11:27:00 (Kalimdor server time)
You can apply this armor kit to low level item.
![image](https://github.com/slowtorta/turtlewow-bug-tracker/assets/24266616/373442ad-4c39-4c23-acb4-71a4c62e1622)
If you equip item, it still work
![image](https://github.com/slowtorta/turtlewow-bug-tracker/assets/24266616/0e3791ba-120e-45ce-b9b0-ae724173f671)
It actually add those 5 stamina.

[Rugged Armor Kit](https://database.turtle-wow.org/?item=15564)
[Handstitched Leather Vest](https://database.turtle-wow.org/?item=5957) item level 8

Expected behavior: You should have some error message on enchant attempt.

**Comment by jameyboor** [comment]
Fixed.
