### ISSUE TITLE
Exalted Blood Ring title not appearing

### ISSUE THREAD

**Issue by drillionfordring** [slowtorta/turtlewow-bug-tracker#5003]
**Please, provide a clear description what the bug is:**
I did not get the Warchief title after reaching exalted reputation with Steamwheedle Blood Ring.
![image](https://github.com/slowtorta/turtlewow-bug-tracker/assets/149566778/9f0894c2-02fb-4ad2-86a5-43b4ab9ff462)
![image](https://github.com/slowtorta/turtlewow-bug-tracker/assets/149566778/be092d80-a6bf-40eb-b77c-09e0e0ed14a3)

**Steps to reproduce the behavior with as much detail as possible:**

1. Reached exalted reputation with Steamwheedle Blood Ring
2. Waited for honor reset day
3. Restarted the client and cleared the WDB folder multiple times as GMs suggested
4. Still no title

**IDs of affected creatures, items, quests or spells with a link to the relevant page:**

NPC: https://database.turtle-wow.org/?npc=
Item: https://database.turtle-wow.org/?item=
Quest: https://database.turtle-wow.org/?quest=
Spell: https://database.turtle-wow.org/?spell=
Object: https://database.turtle-wow.org/?object=

**Expected behavior. Describe how it should work:**

**Comment by slowtorta** [comment]
Fixed in 1.17.1.

**Comment by lyssebabz** [comment]
Still not working

**Comment by slowtorta** [comment]
You have to wait for the patch release.

**Comment by twowTurtReynolds** [comment]
![image](https://github.com/slowtorta/turtlewow-bug-tracker/assets/151180101/a8a9acee-2720-4129-9a57-40186f003484)
The fix doesn't seem to have worked.

**Comment by Egirlwithrpg** [comment]
a simple title... how the hell is that possible?
Legolas' RP hat has been debugged in all patches

**Comment by slowtorta** [comment]
Re-scheduled for 1.17.2. Unfrotunatelly it was forgotten during the devleopment of the previous patch!
Fixed in the internal build.
