### ISSUE TITLE
纳特 帕格的鱼类终结者 ，武器是一把法杖，但是被系统认定为鱼竿，无法正确的做出攻击动作，请修复

### ISSUE THREAD

**Issue by Mingyunzhizhen** [slowtorta/turtlewow-bug-tracker#5004]
**Please, provide a clear description what the bug is:**

**Steps to reproduce the behavior with as much detail as possible:**

1.纳特 帕格的鱼类终结者 ，武器是一把法杖，但是被系统认定为鱼竿，无法正确的做出攻击动作，请修复
2. 
3. 

**IDs of affected creatures, items, quests or spells with a link to the relevant page:**

NPC: https://database.turtle-wow.org/?npc=
Item: https://database.turtle-wow.org/?item=
Quest: https://database.turtle-wow.org/?quest=
Spell: https://database.turtle-wow.org/?spell=
Object: https://database.turtle-wow.org/?object=

**Expected behavior. Describe how it should work:**

**Comment by Muigin** [comment]
Please submit the issues in English. We're unable to accurately translate bug reports submitted in Chinese through automatic translation, which makes it difficult for us to understand the exact nature of the issue. Thank you!
