### ISSUE TITLE
Paladin Consecration SP coeff is incorrect on website

### ISSUE THREAD

**Issue by Destroses5100** [slowtorta/turtlewow-bug-tracker#5006]
**Please, provide a clear description what the bug is:**

Paladin Consecration SP coeff is supposed to be .119, but is currently .08.
https://i.imgur.com/n7lOxBC.png

**Steps to reproduce the behavior with as much detail as possible:**

1. Have 0 SP, and cast Consecration
2. Note that it does 48 damage each tick.
3. Have 100 SP, and cast Consecration
4. Note that it does 56 damage each tick.
5. See 100 SP adds 8 damage (0.08 scaling)

**IDs of affected creatures, items, quests or spells with a link to the relevant page:**

Spell: https://database.turtle-wow.org/?spell=20924

**Expected behavior. Describe how it should work:**

Scaling should be .119, so with 100 SP, Consecration should tick for 60 (59.9)

**Comment by twowTurtReynolds** [comment]
Just checked with the team. I'm sorry to inform you, we're breaking the promise of the first Class Changes initiative and will instead, be updating the website to reflect this current 0.08 value. I'll be updating this report to track that work.

You may debate this decision on the suggestions forum or the discord class channel (Yes, the staff do read there), please not here.
