### ISSUE TITLE
Dragonkin Elites in dustwallow have the same hp as normal mobs but with elite dmg and xp

### ISSUE THREAD

**Issue by JohnnyBravo11** [slowtorta/turtlewow-bug-tracker#5007]
**Please, provide a clear description what the bug is:**

**Steps to reproduce the behavior with as much detail as possible:**

1.
2. 
3. 

**IDs of affected creatures, items, quests or spells with a link to the relevant page:**

NPC: https://database.turtle-wow.org/?npc=
Item: https://database.turtle-wow.org/?item=
Quest: https://database.turtle-wow.org/?quest=
Spell: https://database.turtle-wow.org/?spell=
Object: https://database.turtle-wow.org/?object=

**Expected behavior. Describe how it should work:**

**Comment by twowTurtReynolds** [comment]
Should be fixed as per https://forum.turtle-wow.org/viewtopic.php?p=76368
