### ISSUE TITLE
Tree of Life form prevents movement for a time after stuns wear off

### ISSUE THREAD

**Issue by SaxxonPike** [slowtorta/turtlewow-bug-tracker#5009]
**Please, provide a clear description what the bug is:**

While in Tree of Life form, stuns are noticeably longer. Tail lash is a simple example, but I have noticed this with other kinds of stuns as well. When I think of them, I will add them to this report.

Using the Nefarian fight as an example, it is fairly typical to get into a situation where you might be in the Tail Lash range and, without the ability to move for extra time even after the stun has worn off, it is likely that you will be affected again by Tail Lash, which will then restart the process and exhibit the bug again.

**Steps to reproduce the behavior with as much detail as possible:**

1. As a druid, be in Tree of Life form
2. Engage in a fight with Nefarian (or other creature with a stun ability)
3. Become affected by the stun ability (in this example, Tail Lash)
4. Notice that the client does not permit movement for a time even after the stun has worn off, sometimes even up to double the length of the stun

**IDs of affected creatures, items, quests or spells with a link to the relevant page:**

NPC: https://database.turtle-wow.org/?npc=11583
Spell: https://database.turtle-wow.org/?spell=23364

**Expected behavior. Describe how it should work:**

The movement-prohibiting effect of stuns should last the same amount of time regardless of the shapeshifting form.

**Comment by twowTurtReynolds** [comment]
Stuns in general on the 1.12 client are in my experience much more brutal than they were on classic, the networking seems to add your latency one or two times into the duration.

We will test and see if this is that general (maybe unfixable) client issue, or if tree of life is specifically bugged and can be fixed.

**Comment by SaxxonPike** [comment]
I have some upcoming raids I can record to demonstrate the effect of it. I will update this issue to show in realtime.

**Comment by SaxxonPike** [comment]
@twowTurtReynolds Here ya go:
https://www.youtube.com/watch?v=vwiZXRNwW3M

This was a deliberate reproduction - I am spamming movement after Tail Lash ends, and it will let me cast spells, but it takes a few more seconds to be allowed to move again. If Nef had not been moved, I probably would have been chained into another Tail Lash, pretty much impossible to escape in this form.

**Comment by Muigin** [comment]
Can confirm this behavior can also be observed in Travel Form with the GLyph of the Stag, possibly other appearance changing auras that are not part of base vanilla.

**Comment by Muigin** [comment]
#3069
