### ISSUE TITLE
Mass harmonization quest is bugged

### ISSUE THREAD

**Issue by UrielNicolas** [slowtorta/turtlewow-bug-tracker#5012]
**Please, provide a clear description what the bug is:**

This quest https://database.turtle-wow.org/?quest=40973 on the DB it says you trade 15 small shards for 1 bright shard, which makes no sense.
In the ingame description it says 15 small shards for 5 bright shards, but the reward is 1 bright shard.

**Steps to reproduce the behavior with as much detail as possible:**

1. Mass harmonization quest
2. Turn in
3. Lose 15 small shards for 1 bright shard.

**Comment by twowTurtReynolds** [comment]
The team was aware of the oversights with these, I will check and see if they have been fixed yet.

**Comment by twowTurtReynolds** [comment]
![image](https://github.com/slowtorta/turtlewow-bug-tracker/assets/151180101/e2ae1d1c-de91-418b-ab1a-b0acdd3829a3)
Yep looks all good now. I was rewarded 5 correctly as well.
