### ISSUE TITLE
Store item - Goblin brainwashing device

### ISSUE THREAD

**Issue by Tawayx** [slowtorta/turtlewow-bug-tracker#5013]
**Please, provide a clear description what the bug is:**

**Steps to reproduce the behavior with as much detail as possible:**

1. Store item - Goblin brainwashing device
2. Dual spec not working, keeps erasing specs - character Sgtfriendly Rogue
3. Bug or item description is misleading - unsure what its point is if not to keep your spec.

**IDs of affected creatures, items, quests or spells with a link to the relevant page:**

NPC: https://database.turtle-wow.org/?npc=
Item: https://database.turtle-wow.org/?item=
Quest: https://database.turtle-wow.org/?quest=
Spell: https://database.turtle-wow.org/?spell=
Object: https://database.turtle-wow.org/?object=

**Expected behavior. Describe how it should work:**

Expected dual spec so I could switch between retained PVE / PVP specs.

**Comment by Muigin** [comment]
This item should be working properly as of the recent maintenance.
