### ISSUE TITLE
Vanish bug after maintenance 

### ISSUE THREAD

**Issue by wexio** [slowtorta/turtlewow-bug-tracker#5015]
**Please, provide a clear description what the bug is:**

After you guys did the mainteneace today i had error like 20 times nothing helped so i unistalled game. Also  when i used Vanish after came out from stealth my evicerate thinks its Backstab. No BILITY WORKS NO TRIKETS RACIAL EVICERATE NOTHING. I have to rebott game detele folder and ithappens nonstop nothing helps. 

**Steps to reproduce the behavior with as much detail as possible:**

1.
2. 
3. 

**IDs of affected creatures, items, quests or spells with a link to the relevant page:**

NPC: https://database.turtle-wow.org/?npc=
Item: https://database.turtle-wow.org/?item=
Quest: https://database.turtle-wow.org/?quest=
Spell: https://database.turtle-wow.org/?spell=
Object: https://database.turtle-wow.org/?object=

**Expected behavior. Describe how it should work:**

**Comment by AkalixFrost** [comment]
Greetings.

We require more information than this to identify an issue and solution. Please re-open the issue if it is still occurring, and include as much information as possible.
