### ISSUE TITLE
Unable to enchant Drape of Nordrassil

### ISSUE THREAD

**Issue by mambo1986** [slowtorta/turtlewow-bug-tracker#5020]
**Please, provide a clear description what the bug is:**

Unable to enchant Drape of Nordrassil when you try it says must have cloth?

**Steps to reproduce the behavior with as much detail as possible:**

1. Trade an enchanter while you have drape of nordrassil equipped
2.  Try to put on Enchant cloak - resistances in the will not be traded window as usual.
3. Notice it doesnt work and the error says something about cloth.

**IDs of affected creatures, items, quests or spells with a link to the relevant page:**

NPC: https://database.turtle-wow.org/?npc=
Item: https://database.turtle-wow.org/?item=61753
Quest: https://database.turtle-wow.org/?quest=
Spell: https://database.turtle-wow.org/?spell=
Object: https://database.turtle-wow.org/?object=

**Expected behavior. Describe how it should work:**
When opening window with enchanter they should be able to enchant your cloak in the non trade window.

**Comment by RUTHINAS** [comment]
The case seems to be that Drape of Nordrassil has no assigned armor class.

Shifting Cloak, for example, is classified as cloth: https://database.turtle-wow.org/?item=18511

**Comment by Dragunovi** [comment]
Should be fixed in the next scheduled server restart.

**Comment by twowTurtReynolds** [comment]
It has been reported that this fix isn't working.

**Comment by twowTurtReynolds** [comment]
![image](https://github.com/slowtorta/turtlewow-bug-tracker/assets/151180101/e50b0d84-f674-44ab-bb7b-6b4f9aae9bf6)
Working now.
