### ISSUE TITLE
Error 132

### ISSUE THREAD

**Issue by japer85** [slowtorta/turtlewow-bug-tracker#5021]
WoW.exe Error #132

1. can happen before or after I login to the game
2. after choosing a toon

There are tears in the game for short time before clashing as well

I havent had this issue when I had GTX960.

My PC specs:

R7-5800X
32GB ram
RX 6700 XT  Driver: 31.0.22017.3004 updated 16/10/23     (was GTX 960)
SSD

2X 27 inch QHD LG monitor Both works for G-sync, and freesync

![Turtle wow 02](https://github.com/slowtorta/turtlewow-bug-tracker/assets/20633874/c29184e8-573f-4549-8560-7e8b7ac79756)

![Turtle wow 01](https://github.com/slowtorta/turtlewow-bug-tracker/assets/20633874/a8548bee-3a4a-4beb-a44f-06c5e65a6592)

**Comment by RUTHINAS** [comment]
Are you using the addon Minimap Button Frame? Sometimes it causes a crash like this at startup.

**Comment by japer85** [comment]
nope

**Comment by japer85** [comment]
![image](https://github.com/slowtorta/turtlewow-bug-tracker/assets/20633874/7f510d4b-bfa3-46e8-92c0-8895e9ad8b10)

**Comment by japer85** [comment]
can anyone help plz~~~

**Comment by twowTurtReynolds** [comment]
Hardware and software setups can be responsible for these issues. This isn't really a bug fixable by the turtle staff.
