### ISSUE TITLE
Karazhan raid ,boss issue.

### ISSUE THREAD

**Issue by imKevinFlynn** [slowtorta/turtlewow-bug-tracker#5023]
**Please, provide a clear description what the bug is:**
Karazhan raid , bugged Boss Moroes. 

**Steps to reproduce the behavior with as much detail as possible:**

Our group of 10 people tried to kill Moroes boss in Karazhan raid, but he bugged and had more than 2 lives so we wiped , than we tried to stop dps at 20% of his hp at second time of trying it worked and Moroes tped to arena. But than we died and boss resets at first place with same bugged mechanics. 
My ingame name Voodoojester you can contact me ingame if needed.

**IDs of affected creatures, items, quests or spells with a link to the relevant page:**

NPC: https://database.turtle-wow.org/?npc=61225

**Expected behavior. Describe how it should work:**

Expected it to work correct , without stoping dps or killing the same boss 3 times.

**Comment by Zmitrok1984** [comment]
When you killed Moroes first time, before he teleported, do not stand on chairs or benches.
If boss targeted to people, who stand on bench, ecounter will reset.
When we killed him at our run, he recovered like this 3 times until we understood the logic in his actions.

**Comment by imKevinFlynn** [comment]
Is this ingame Boss mechanics and not a bug  ?

**Comment by imKevinFlynn** [comment]
Ah i was thinking u are dev. Okay , thanks.

**Comment by imKevinFlynn** [comment]
If some of devs wants to bring interesting mechanics to the game without insulting people with casuality (1 mechanics per boss without any challenge) or bug looking bosses, let me know, i probably can provide some good ideas.

**Comment by imKevinFlynn** [comment]
Tried another Kara, no one stay on bench or other obsticle and we just killed him twice at same place and than we be able to loot him.

**Comment by lyssebabz** [comment]
https://streamable.com/orqf8q

**Comment by AkalixFrost** [comment]
Fixed in previous update.
