### ISSUE TITLE
称号和荣誉军衔问题

### ISSUE THREAD

**Issue by zblyangqiao** [slowtorta/turtlewow-bug-tracker#5027]
**Please, provide a clear description what the bug is:**

**Steps to reproduce the behavior with as much detail as possible:**

1.血环服务器联盟人类盗贼，ID：忘羡一曲远，军衔总显示None，没有下士等称号
2. 血环服务器联盟人类盗贼，ID：忘羡一曲远，荣誉界面上方荣誉经验总显示无（级别0）
3. 荣誉界面总计最高级别显示中士，但上述两个问题并无任何显示。

**IDs of affected creatures, items, quests or spells with a link to the relevant page:**

NPC: https://database.turtle-wow.org/?npc=
Item: https://database.turtle-wow.org/?item=
Quest: https://database.turtle-wow.org/?quest=
Spell: https://database.turtle-wow.org/?spell=
Object: https://database.turtle-wow.org/?object=

**Expected behavior. Describe how it should work:**

**Comment by Muigin** [comment]
Please submit the issues in English. We're unable to accurately translate bug reports submitted in Chinese through automatic translation, which makes it difficult for us to understand the exact nature of the issue. Thank you!
