### ISSUE TITLE
Fashion Demands Sacrifices quest bug

### ISSUE THREAD

**Issue by ashphoenixblack** [slowtorta/turtlewow-bug-tracker#5028]
Description of issue:
Unable to accept quest "Fashion Demands Sacrifices"

-When quest pops up, the "continue" option is 
 greyed out & not selectable. 

-It affects all my characters & has been happening for months now. Any char, either faction, both servers. I abandoned the quest once (on the twow server) & ever since, the "continue" for "Fashion Demands Sacrifices" is always greyed out & cant be selected. 

-Clearing WDB folder is standard practice for me prior to each launch of the game. 

-On 2 occasions (1 char each server) a kind mod has been able to just give me the quest. Once I have the quest, it works fine (gathering required items & turning them in allows me to complete the quest & the fashion coin is awarded). However this doesn't resolve the bug. 

I'm especially disappointed by this issue following me to the new server, where there is no turtle mode & the server began after the 5yr anniversary... so it's basically impossible to get any coins without buying a bag from the donation shop. I just spent a lot there during the mist recent sale & can't justify spending more for a while.

**IDs of affected creatures, items, quests or spells with a link to the relevant page:**

NPC: 
• https://database.turtle-wow.org/?npc=51293
• https://database.turtle-wow.org/?npc=51292
Quest: https://database.turtle-wow.org/?quest=60032

**Expected behavior. Describe how it should work:**
Click "continue" to accept quest

I've gotten a response suggesting i clear the WTF & interface folders. I've tried different combinations of Clearing &/or removing these folders & I'm not sure how I should be doing it, but every attempt has just seemed to break the entire game. I've restored everything & the issue persists

**Comment by ashphoenixblack** [comment]
Can anyone further advise how to clear WTF & interface (without breaking the game) ? Should I try uninstalling & reinstalling?

**Comment by cyaohiri** [comment]
Could you record a video of this happening? Your WTF should not be the cause, but you can always move it elsewhere temporarily, run the game, and see if you can take the quest then. If you still can't, it's probably not that folder. Then you can return in back where it was.

**Comment by Muigin** [comment]
This is not a quest you "accept".  You need to bring the items requested to the NPC and simply turn them in, which is when Continue will be selectable.

Working as intended.
