### ISSUE TITLE
I can't take class quest once again after abandoning it

### ISSUE THREAD

**Issue by salibardo** [slowtorta/turtlewow-bug-tracker#503]
**Please, provide a clear description what the bug is:** i cant take paladin class quest again because the npc that i have quest from is dead and i dont have a rez item 

**Steps to reproduce the behavior with as much detail as possible:**

1.
2. 
3. 

**IDs of affected creatures, items, quests or spells with a link to the relevant page:**

NPC: https://database.turtle-wow.org/?npc=6172
Item: https://database.turtle-wow.org/?item=6866
Quest: https://database.turtle-wow.org/?quest=1643
Spell: https://database.turtle-wow.org/?spell=7328
Object: https://database.turtle-wow.org/?object=

**Expected behavior. Describe how it should work:** just send me https://database.turtle-wow.org/?item=1146 this item at chara Orichal and thats it sorry

**Comment by Tinyfin-github** [comment]
Greetings!

Please make a proper bug report with screenshot and videos that help us reproduce the bug and sources the show the proper behavior.

For GM assistance for character problems and quest issues the proper channel is in game tickets. 

I have send character Orichal  another Symbol of Life to revive Henze Faulk and continue the quest chain.
