### ISSUE TITLE
Flighing path error

### ISSUE THREAD

**Issue by Husmeador12** [slowtorta/turtlewow-bug-tracker#5030]
**Please, provide a clear description what the bug is:**
I was fliying from _Stonetalon Mountains, Bael Hardul_ to _Auberdine_ and the gryphon fall in the middle of the air in the fly point of _Astranaar_ in Ashenvale.
![Animation](https://github.com/slowtorta/turtlewow-bug-tracker/assets/7702430/d096cfb0-f1b1-4310-8fd7-769161f4ceae)

**Steps to reproduce the behavior with as much detail as possible:**

1. Take a fly from Bael Hardul, Stonetalon Mountains
2.  Fly to Auberdine, Darkshore.
3.  You will fall on the fly point of Astranaar.
4.  Disconnect and reconnect to get again flying to Auberdine, Darkshore.

**IDs of affected creatures, items, quests or spells with a link to the relevant page:**

**Expected behavior. Describe how it should work:**
I don't know.

**Comment by twowTurtReynolds** [comment]
Closing as dupe https://github.com/slowtorta/turtlewow-bug-tracker/issues/4619

Thank you for the footage
