### ISSUE TITLE
Respawn times are off (WAY too fast)

### ISSUE THREAD

**Issue by Adso777** [slowtorta/turtlewow-bug-tracker#5031]
**Please, provide a clear description what the bug is:**
I was in the Burrow Den in Teldrassil doing the relics quests and respawns were out of control. We are in 2 and we kill Greenpaw and literally 10 sec after he respawned again. I don't know if dynamic respawn is enable but if it is it's way too fast. NPCs can't respawn in 10 seconds. We kept dying in Burrow Den. After further examination it seems to me all the respawns are way too fast. Maybe they were set so fast when there was an 8k+ population and it stayed that way since but now some areas are next to impossible to play solo or in 2.
**Steps to reproduce the behavior with as much detail as possible:**

1.
2. 
3. 

**IDs of affected creatures, items, quests or spells with a link to the relevant page:**

NPC: https://database.turtle-wow.org/?npc=
Item: https://database.turtle-wow.org/?item=
Quest: https://database.turtle-wow.org/?quest=
Spell: https://database.turtle-wow.org/?spell=
Object: https://database.turtle-wow.org/?object=

**Expected behavior. Describe how it should work:**
Respawn shouldn't be so fast. Take the Burrow Den example - we cleared an area and by the time we killed the last NPC on that area the whole SAME area is respawning again, therefore you can hardly advance. 
Or Greenpaw: we killed him and the other mob there with him. I then loot the chest and when my partner starts to loot the chest (for the relic) Greenpaw is there already again?! This is way off. How many time we need to kill the same named NPC to do a stage of one quest? And it's not that it was full of people (if dynamic respawn is a thing in this server), we were just in 2.

**Comment by Adso777** [comment]
I forgot to mention this is on the new pvp server.

**Comment by AkalixFrost** [comment]
Has been changed a number of times to fit population, should be good currently, reopen if issue persists.
