### ISSUE TITLE
My ring diseaperd (I come from Hogger)

### ISSUE THREAD

**Issue by yanhansome** [slowtorta/turtlewow-bug-tracker#5033]
**Please, provide a clear description what the bug is:**
My leader ring(get from Zul'Gurub NO.1) equiped has been somedays,but disappeared，please help me。
My account ：kk50255244

**IDs of affected creatures, items, quests or spells with a link to the relevant page:**

NPC: https://database.turtle-wow.org/?npc=
Item: https://database.turtle-wow.org/?item=
Quest: https://database.turtle-wow.org/?quest=
Spell: https://database.turtle-wow.org/?spell=
Object: https://database.turtle-wow.org/?object=

**Expected behavior. Describe how it should work:**

**Comment by twowTurtReynolds** [comment]
Contact a GM if you haven't already, and see if they can or cannot help. Doesn't belong in the bug tracker.
