### ISSUE TITLE
The key to karazhan III can not completed

### ISSUE THREAD

**Issue by markmarksan** [slowtorta/turtlewow-bug-tracker#5034]
hi,

I can not complete the quest named the key to karazhan III. I have found the NPC in Alterac Mountains, but I am not able to talk to him. Becasue he is in red. He will attack me.

My character named marksan

**Comment by RUTHINAS** [comment]
Your character appears to be Horde. The NPC in Alterac is the quest end point for the Alliance version of The Key to Karazhan III. Horde members should look in the Undercity.

**Comment by AkalixFrost** [comment]
Working as intended, Horde version and Alliance version in different places.
