### ISSUE TITLE
No loot roll option (need/greed) or logs of loot/rolls - Gilneas City

### ISSUE THREAD

**Issue by Korgish** [slowtorta/turtlewow-bug-tracker#5035]
**Please, provide a clear description what the bug is:**
Per GM Roomba
Turtlefinder Group in Cilneas City - 3rd boss in I stopped getting drop/loot roll options (loot/rolls also did not show up in chat logs)
          Ex.    Entername rolled 91 
                  Entername received loot [Funny Hat]
                  etc etc

Issue persisted through end of instance 
No new Addons were added prior to issue occurring 

**Steps to reproduce the behavior with as much detail as possible:**

1. Kill a boss 
2. Get a trash mob drop
3.  - restarted client/cleared WDB folder
worked for 1 round of looting, started again
4. - restarted client/cleared WDB folder
Issue persisted, had 1-2 members in group also not receive roll option for loot

**IDs of affected creatures, items, quests or spells with a link to the relevant page:**

NPC: https://database.turtle-wow.org/?npc=
Item: https://database.turtle-wow.org/?item=
Quest: https://database.turtle-wow.org/?quest=
Spell: https://database.turtle-wow.org/?spell=
Object: https://database.turtle-wow.org/?object=

**Expected behavior. Describe how it should work:**
Option to roll Need/Greed should be available when a loot item is dropped from boss/trash mob
Chat(s) should reflect what item was dropped, who rolled what (need/greed), and the resulting dice roll (1-100) 
Chat should show who won roll/what winning roll number was

**Comment by twowTurtReynolds** [comment]
It definitely sounds like an addons issue. I have other players reporting this works just fine for them.
