### ISSUE TITLE
荣誉问题

### ISSUE THREAD

**Issue by zblyangqiao** [slowtorta/turtlewow-bug-tracker#5038]
**Please, provide a clear description what the bug is:**

**Steps to reproduce the behavior with as much detail as possible:**

1.血环联盟人类盗贼ID：忘羡一曲远，军衔级别一直是0
![blkPGyNkmU0950a9 webp](https://github.com/slowtorta/turtlewow-bug-tracker/assets/149703189/54c7c46f-140e-49bd-8195-408fa7b8e46a)

2. 
3. 

**IDs of affected creatures, items, quests or spells with a link to the relevant page:**

NPC: https://database.turtle-wow.org/?npc=
Item: https://database.turtle-wow.org/?item=
Quest: https://database.turtle-wow.org/?quest=
Spell: https://database.turtle-wow.org/?spell=
Object: https://database.turtle-wow.org/?object=

**Expected behavior. Describe how it should work:**

**Comment by Muigin** [comment]
Please submit the issues in English. We're unable to accurately translate bug reports submitted in Chinese through automatic translation, which makes it difficult for us to understand the exact nature of the issue. Thank you!
