### ISSUE TITLE
Moroes bugged 

### ISSUE THREAD

**Issue by eryx112** [slowtorta/turtlewow-bug-tracker#5046]
**Please, provide a clear description what the bug is:**
we doing the raiding in Karazhan for Moroes. He bugged. We cannot talked to him seconde time. So we can not attack him at Phase 2
**Steps to reproduce the behavior with as much detail as possible:**

1.we doing the raiding in Karazhan for Moroes. He bugged. We cannot talked to him seconde time. So we can not attack him at Phase 2
2. 
3. 

**IDs of affected creatures, items, quests or spells with a link to the relevant page:**

NPC: https://database.turtle-wow.org/?npc=61225
Item: https://database.turtle-wow.org/?item=
Quest: https://database.turtle-wow.org/?quest=
Spell: https://database.turtle-wow.org/?spell=
Object: https://database.turtle-wow.org/?object=

**Expected behavior. Describe how it should work:**
we doing the raiding in Karazhan for Moroes. He bugged. We cannot talked to him seconde time. So we can not attack him at Phase 2

**Comment by lyssebabz** [comment]
https://streamable.com/orqf8q

**Comment by twowTurtReynolds** [comment]
Moroes issues should be all fixed now. Open 1 new report if issues with him crop back up.
