### ISSUE TITLE
Moroes bugged again

### ISSUE THREAD

**Issue by pelliaborealis** [slowtorta/turtlewow-bug-tracker#5053]
Karazhan raid ID 14459, Moroes is bugged again. Instead of going to the stage and staying there he blinked, became non-aggressive, then ran all the way back to us, murdered our Paladin and kept the rest of us in combat, then just stood there like an idiot. We can't re-aggro him, he's just stood by the stairs. Spoke to Greena who told us to raise a bug ticket.

We've left group and remade the raid, nothing helped.

NPC: https://database.turtle-wow.org/?npc=61225

**Comment by lyssebabz** [comment]
https://streamable.com/orqf8q

**Comment by twowTurtReynolds** [comment]
Moroes issues should be all fixed now.
