### ISSUE TITLE
Fist weapon "Remnants of an Old God" cannot be sheathed/hidden

### ISSUE THREAD

**Issue by hokanoma** [slowtorta/turtlewow-bug-tracker#5054]
When sheathed, or riding, or doing anything that normally hides fist weapons, now it is misaligned and cannot be hidden. 
![image](https://github.com/slowtorta/turtlewow-bug-tracker/assets/149842006/2887c29d-b6fa-4905-9cc2-32bd9e22f897)
![image](https://github.com/slowtorta/turtlewow-bug-tracker/assets/149842006/1ab04f8d-e3a9-4ce0-ba68-4f63c10f422e)
![image](https://github.com/slowtorta/turtlewow-bug-tracker/assets/149842006/4b6f2040-b4ba-4fc2-9382-28bff235fac4)
![image](https://github.com/slowtorta/turtlewow-bug-tracker/assets/149842006/dad0b2a7-060d-45c4-915f-bd44bc1db711)

When unsheathed, the fist is working fine:
![image](https://github.com/slowtorta/turtlewow-bug-tracker/assets/149842006/29f5cefb-b2ce-482f-8057-72211af8b60b)

Getting mobbed at by guildies
![image](https://github.com/slowtorta/turtlewow-bug-tracker/assets/149842006/7f60f523-54e0-400a-91ba-74f2d7361f4f)

**Steps to reproduce the behavior with as much detail as possible:**
1. Un-equip both weapons
2. Equip "Remnants of an Old God" the fist weapon
3. It is now visible on the character by default
4. Equip any other fist weapon in the off-hand
5. The other weapon is hidden by default
6. Do sheath/unsheath on the character
7. The "Remnants of an Old God" is always visible

**IDs of affected creatures, items, quests or spells with a link to the relevant page:**

Item: https://database.turtle-wow.org/?item=60003

**Expected behavior. Describe how it should work:**

The fist weapons should be hidden by default when wearing. Doing sheath/unsheath will make them appear visible/invisible.

**Comment by hokanoma** [comment]
@twowTurtReynolds I noticed that Nature's Gift's sheathing got fixed in 1.17.1, any plan to fix this one soon as well?

**Comment by twowTurtReynolds** [comment]
We're in 1.17.1 crunch right now. This is a core issue we can solve after the fact. Also, holidays. No ETA :)

**Comment by hokanoma** [comment]
Noice!! Ty for the help!

**Comment by hokanoma** [comment]
This seems to have been resolved 2 weeks ago, perhaps unintentionally together with other similar cosmetic fixes.

**Comment by twowTurtReynolds** [comment]
Indeed, all looks well now.
