### ISSUE TITLE
Donation Rewards shop bugged

### ISSUE THREAD

**Issue by bonejob147** [slowtorta/turtlewow-bug-tracker#5055]
Item icons missing from shop, I can open the rewards shop but there is nothing there.
![image](https://github.com/slowtorta/turtlewow-bug-tracker/assets/149843313/2e5f852c-e200-4619-bbf8-e5eb575253fc)

**Comment by twowTurtReynolds** [comment]
I see you have addons enabled, please don't. Those can very much break the UI.

If you are still replicating this bug with all addons disabled, please redownload a fresh turtle client, and try again. If even then the issue persists, take a full game screenshot and share here.
