### ISSUE TITLE
Moroes bugged

### ISSUE THREAD

**Issue by Smileybob1** [slowtorta/turtlewow-bug-tracker#5056]
Moroes bugged out in our raid ID 15318.

Got the first phase of the fight, but after teleporting to the stage he ran to us still in "combat" but green and not attacking. Can no longer talk to him to start the second phase.

GM to reset him would be appreciated!

**Comment by lyssebabz** [comment]
https://streamable.com/orqf8q

**Comment by twowTurtReynolds** [comment]
Moroes issues should be all fixed now. Open 1 new report if issues with him crop back up.
