### ISSUE TITLE
Moroes wont reset

### ISSUE THREAD

**Issue by Tornado2k5** [slowtorta/turtlewow-bug-tracker#5057]
**Please, provide a clear description what the bug is:**

**Steps to reproduce the behavior with as much detail as possible:**

1.Moroes reset after first time killing him and will not reset
2. Veil of Nightmare is not able to be enchanted
3. 

**IDs of affected creatures, items, quests or spells with a link to the relevant page:**

NPC: https://database.turtle-wow.org/?npc= 61226
Item: https://database.turtle-wow.org/?item= 61210
Quest: https://database.turtle-wow.org/?quest=
Spell: https://database.turtle-wow.org/?spell=
Object: https://database.turtle-wow.org/?object=

**Expected behavior. Describe how it should work:**

**Comment by Tornado2k5** [comment]
Character name is Wildhammerin

**Comment by lyssebabz** [comment]
https://streamable.com/orqf8q

**Comment by AkalixFrost** [comment]
Fixed in previous update.
