### ISSUE TITLE
Blood Ring Bugged Portals Issue

### ISSUE THREAD

**Issue by Meridaw** [slowtorta/turtlewow-bug-tracker#5061]
**Please, provide a clear description what the bug is:**
After joining a blood ring game you cannot zone into dungeons portals or city portals such as the Darnassus entrance portal. Then you will be forced to re-log in first. 
**Steps to reproduce the behavior with as much detail as possible:**

1. Enter Blood ring.
2. Try to enter dungeon portal.

**Expected behavior. Describe how it should work:**
It should be possible to go through the portals even if you have been in the blood ring.

**Comment by Meridaw** [comment]
Joining Blood ring games also bug exploring area quests such as "How Big a Threat?"

**Comment by Zebouski** [comment]
Same bug as https://github.com/slowtorta/turtlewow-bug-tracker/issues/3445 which should have been fixed with 1.17... are you by chance playing on SEA realms under 1.16.5 ? Or is this actually still happening on 1.17

**Comment by Meridaw** [comment]
> Same bug as #3445 which should have been fixed with 1.17... are you by chance playing on SEA realms under 1.16.5 ? Or is this actually still happening on 1.17

I play on the new pvp server for eu players. 
also, probably are rare thing, but if you heartstone just as a game of blood ring starts you cannot enter the blood ring.

**Comment by slowtorta** [comment]
Fixed in 1171.
