### ISSUE TITLE
Typo in quest text of Blackrock and Roll

### ISSUE THREAD

**Issue by darkhorror1984** [slowtorta/turtlewow-bug-tracker#5063]
Incorrect position for reward in quest text of Blackrock and Roll

**Steps to reproduce the behavior with as much detail as possible:**

1. Take quest Bloodfury Bloodline
2. Hand 20 Blackrock Signets.
3. Say with Tarsokk.

![WoWScrnShot_110423_124344](https://github.com/slowtorta/turtlewow-bug-tracker/assets/108156692/74ddbd79-f8d9-4679-aa3b-15099b0e3ba9)

**IDs of affected creatures, items, quests or spells with a link to the relevant page:**

Quest: https://database.turtle-wow.org/?quest=40256

**Expected behavior. Describe how it should work:**

**Comment by twowTurtReynolds** [comment]
One of your addons or something is breaking your game. Confirmed this doesn't without addons.
![image](https://github.com/slowtorta/turtlewow-bug-tracker/assets/151180101/f2824e74-440a-46ef-943e-fcd06ffacebc)
