### ISSUE TITLE
骑士防御天赋2-1精确天赋，亚服没有3点法术命中

### ISSUE THREAD

**Issue by moonquake125** [slowtorta/turtlewow-bug-tracker#5065]
骑士防御天赋2-1精确天赋，之前是3点法术命中和3点物理命中，现在亚服的没有3点法术命中

**Comment by Muigin** [comment]
Please submit the issues in English. We're unable to accurately translate bug reports submitted in Chinese through automatic translation, which makes it difficult for us to understand the exact nature of the issue. Thank you!
