### ISSUE TITLE
Feed pet bugged? 

### ISSUE THREAD

**Issue by Mansen229** [slowtorta/turtlewow-bug-tracker#5066]
**Please, provide a clear description what the bug is:**

**Steps to reproduce the behavior with as much detail as possible:**

1. Feeding pet spell
2. when I try to feed my pet with meat my character eats instead.
3. 

**IDs of affected creatures, items, quests or spells with a link to the relevant page:**

Spell: https://database.turtle-wow.org/?spell=https://database.turtle-wow.org/?spell=6991

**Expected behavior. Describe how it should work:**

**Comment by twowTurtReynolds** [comment]
I, the staff, and others on discord are unable to replicate this. It's very likely an issue caused by addons or mods of yours.
