### ISSUE TITLE
Hunter pets attack new targets without instruction

### ISSUE THREAD

**Issue by makilahy** [slowtorta/turtlewow-bug-tracker#5067]
**Please, provide a clear description what the bug is:**

Sometimes when fighting, as soon at the pet's target dies, a hunter's pet will take off and attack another target without being instructed to do so. This happens even when tabbed targeting is not used and the pet is set to "Passive." Today, I was fighting on the plains of The Barrens (flat surface, with no "floors" above or below me, so not a "path issue"), and my bird took off after a fight and disappeared completely (flying far out of sight). I called it back, and it brought the mob it had targeted. There's no way I could have targeted something that was too far away to display on my screen. Not only that, my cursor had not been pointing anywhere near that direction the entire fight.

So far, this has happened at least three times in two days with my bird. I don't recall seeing it happen with my boar, though I have wondered at times why my various pets targeted another mob immediately after a fight. I assumed then that it was because it was set to "Defensive" mode and I had gotten aggro. But in the most recent cases, I know this could not have been the case.

**Steps to reproduce the behavior with as much detail as possible:**

1. Fight mobs with pet, and avoid using tabbed targeting.
2. Kill the mob.
3. On rare occasions, the pet will take off to fight a random, remote target.

**IDs of affected creatures, items, quests or spells with a link to the relevant page:**

N/A

**Expected behavior. Describe how it should work:**

Pets should only attack when instructed and not find their own targets. This can (and has) caused problems in dungeons. While some hunters do make mistakes and are careless with their pets, this bug can give even good hunters a bad rap.

Update: I have not seen this bug with my boar, but only with my bird so far. Since my bird is a bald eagle, there is a chance that this is somehow related to its new skin.

**Comment by twowTurtReynolds** [comment]
This really sounds like to me like an issue in one of your addons, especially considering other users and staff haven't seen this themselves when I asked. Please disable all addons (for real, all of them except maybe your quest helper) and play a session and see if it crops up. Closing as very likely not a turtle bug.
