### ISSUE TITLE
Rejuvenation scarab brooch interaction 

### ISSUE THREAD

**Issue by NoobiksCube** [slowtorta/turtlewow-bug-tracker#5069]
**Please, provide a clear description what the bug is:**
When the trinket Scarab Brooch is active rejuvenation apply the target the shield buff Persistent Shield, but it only absorbs 1 damage.

**Steps to reproduce the behavior with as much detail as possible:**

1. Activate Scarab Brooch
2. Apply Rejuvenation to target
3. Persistent shield applies to target but fades after taking 1 damage

**IDs of affected creatures, items, quests or spells with a link to the relevant page:**

Item: https://www.wowhead.com/classic/item=21625/scarab-brooch

**Expected behavior. Describe how it should work:**
It used to apply a shield equal to rejuvenations total healing. So if rejuvenation would heal for 2000 over the course of the HoT it would apply a shield for 300.

**Comment by twowTurtReynolds** [comment]
[This guy from 2006 says no, it doesn't work on hots. ](https://www.wowhead.com/classic/item=21625/scarab-brooch#comments:id=2653818)

Let me know if you can prove otherwise with 2006 evidence.
