### ISSUE TITLE
Quest Rise, Obsidion! is bugged, the event does not start

### ISSUE THREAD

**Issue by Tinyfin-github** [slowtorta/turtlewow-bug-tracker#507]
Quest Rise, Obsidion! is bugged, the event does not start

https://user-images.githubusercontent.com/83077166/144700222-f14dca70-45bb-427b-a1c8-facccab9b203.mp4

How it should work:

https://www.youtube.com/watch?v=leraa1Dtzng

https://database.turtle-wow.org/?quest=3566 Rise, Obsidion!
https://database.turtle-wow.org/?npc=8417 Dying Archaeologist
https://database.turtle-wow.org/?npc=8421 Dorius
https://database.turtle-wow.org/?npc=8400 Obsidion
https://database.turtle-wow.org/?npc=8391 Lathoric the Black

**Comment by sjwoodr** [comment]
I encountered this same bug last night and came here to report it... i see its been reported previously at least a couple of times.  :)

**Comment by Zulmamwe** [comment]
Still bugged
Bump
