### ISSUE TITLE
物品丢失

### ISSUE THREAD

**Issue by zlh520sj** [slowtorta/turtlewow-bug-tracker#5071]
**Please, provide a clear description what the bug is:**

**Steps to reproduce the behavior with as much detail as possible:**

1.乌龟服 风暴烈酒 10级小号 圣骑士 侯爷邮寄给60级圣骑士 大罪武装 的14个奥金锭，服务器重启后没有了
2. 
3. 

**IDs of affected creatures, items, quests or spells with a link to the relevant page:**

NPC: https://database.turtle-wow.org/?npc=
Item: https://database.turtle-wow.org/?item=
Quest: https://database.turtle-wow.org/?quest=
Spell: https://database.turtle-wow.org/?spell=
Object: https://database.turtle-wow.org/?object=

**Expected behavior. Describe how it should work:**

**Comment by Muigin** [comment]
Please submit the issues in English. We're unable to accurately translate bug reports submitted in Chinese through automatic translation, which makes it difficult for us to understand the exact nature of the issue. Thank you!
