### ISSUE TITLE
亚服 风暴烈酒 邮箱发送物品 服务器重启后物品丢失了 求恢复

### ISSUE THREAD

**Issue by zlh520sj** [slowtorta/turtlewow-bug-tracker#5072]
**Please, provide a clear description what the bug is:**

**Steps to reproduce the behavior with as much detail as possible:**

1.风暴烈酒 10级圣骑士 侯爷 给60级圣骑士发邮件的奥金锭14及其他物品卡掉了 没有了
2. 
3. 

**IDs of affected creatures, items, quests or spells with a link to the relevant page:**

NPC: https://database.turtle-wow.org/?npc=
Item: https://database.turtle-wow.org/?item=
Quest: https://database.turtle-wow.org/?quest=
Spell: https://database.turtle-wow.org/?spell=
Object: https://database.turtle-wow.org/?object=

**Expected behavior. Describe how it should work:**

**Comment by Muigin** [comment]
Please submit the issues in English. We're unable to accurately translate bug reports submitted in Chinese through automatic translation, which makes it difficult for us to understand the exact nature of the issue. Thank you!
