### ISSUE TITLE
Finding Private Holson II

### ISSUE THREAD

**Issue by Schwrop** [slowtorta/turtlewow-bug-tracker#5073]
**Please, provide a clear description what the bug is:**
Droprate of quest item [Holson's amulet](https://database.turtle-wow.org/?item=60638) seems to be too low or unobtainable. Killed all ogres in the area three times and it didn't drop.
Also tried to retake quest and kill all ogres again.

EDIT:
Tried taking quest next day for the third time. It eventually dropped.
In sum, there were ~70 kills, which does not correspond to 30% droprate.

**Steps to reproduce the behavior with as much detail as possible:**

1. Kill ogres
2. No quest item drops
3. ??? = PROFIT ???

**IDs of affected creatures, items, quests or spells with a link to the relevant page:**

NPC: https://database.turtle-wow.org/?npc=60862
Item: https://database.turtle-wow.org/?item=60638#dropped-by
Quest: https://database.turtle-wow.org/?quest=40437

**Expected behavior. Describe how it should work:**
Droprate should be 30% as written in the database

**Comment by cyaohiri** [comment]
Are you using Atlas for Turtle WoW? You can get it here: https://github.com/Nonameby/Atlas

**Comment by twowTurtReynolds** [comment]
![image](https://github.com/slowtorta/turtlewow-bug-tracker/assets/151180101/00a82eb6-454a-4ef7-b73e-9b5f8fa596ad)

Are you sure something else wasn't going on? I got the drop the very first kill. Tried it again, got it on the 6th kill. Seems to be working fine.
