### ISSUE TITLE
Request help from game manager

### ISSUE THREAD

**Issue by cokle520** [slowtorta/turtlewow-bug-tracker#5074]
**Please, provide a clear description what the bug is:**
I encountered a bug while doing the task.The 'Top Piece of Lord Valthalak's Amulet' obtained from the previous task disappeared from the backpack.Resulting in the inability to successfully synthesize 'Lord Valthalak's Amulet'.I once tried to contact the game manager and he asked me to go to  find the NPC "Trash Collector Gaston<Lost and Found>".But this NPC did not sell the items I needed to restore。
**Steps to reproduce the behavior with as much detail as possible:**

1.Current task name that cannot be completed:The Right Piece of Lord Valthalak's Amulet     “https://database.turtle-wow.org/?quest=8991”
2. Missing task props：Top Piece of Lord Valthalak's Amulet         “https://database.turtle-wow.org/?spell=27739”
3. Affected related roles：Turtle suit Asian suit-Emerald Dream-语安与风

**IDs of affected creatures, items, quests or spells with a link to the relevant page:**

NPC: https://database.turtle-wow.org/?npc=
Item: https://database.turtle-wow.org/?item=
Quest: https://database.turtle-wow.org/?quest=
Spell: https://database.turtle-wow.org/?spell=
Object: https://database.turtle-wow.org/?object=

**Expected behavior. Describe how it should work:**
Request to restore props：Top Piece of Lord Valthalak's Amulet，So much so that I could successfully complete this task.Thank you！

**Comment by AkalixFrost** [comment]
Greetings.

Please try either abandoning and retaking the quest, if this does not restore the missing item, please open another ticket with support.
