### ISSUE TITLE
Curse of doom doesn't summon anything if you control a pet

### ISSUE THREAD

**Issue by NoelHG** [slowtorta/turtlewow-bug-tracker#5077]
**Please, provide a clear description what the bug is:**

Curse of doom doesn't summon anything if you control a pet. This is a bug 100% because guides in classic talk about using a voidwalker to help summon it.

**Expected behavior. Describe how it should work:**

It should summon a hostile Doom Guard regardless.

**Comment by twowTurtReynolds** [comment]
I trust ya, but we need some proof.

I found some 2007 tbc footage: https://www.youtube.com/watch?app=desktop&v=3tYPzOyUPm4 

Can you help find some 2006 or 2019 classic footage?

**Comment by twowTurtReynolds** [comment]
Upon further review, this post is a duplicate of https://github.com/slowtorta/turtlewow-bug-tracker/issues/2442. Closing this and tracking the problem there.
