### ISSUE TITLE
Its not a Bug but it is as Bad as my English :D (Scorch/Fire Vulnerability).

### ISSUE THREAD

**Issue by Poolturtle** [slowtorta/turtlewow-bug-tracker#5079]
''Improved Scorch'' can attach a ''Fire Vulnerability debuff'' on a Target and it can stack up to 5 times. Fire Vulnerability can be resisted from a Target even if ur Scorch was successful (many ppl dont know about this). Same with Winterchill and other Debuffs from Attacks.

If u hit a Target with Scorch the first 5 times, the Combatlog will track these Fire Vulnerability debuffs perfect which is important to create working tracking addons. After the 1st Scorch the Combatlog will tell u ''Mob is afflicted by Fire Vulnerability''. After the 2nd Scorch it will tell u ''Mob is afflicted by Fire Vulnerability(2) and so on. But after the 5th cast ''Mob is afflicted by Fire Vulnerability(5)'' it wont show u a Message like ''Mob is afflicted by Fire Vulnerability(5)'' again. It wont track anything if there are already 5 Stacks(Max amount) of Fire Vulnerability on the Target. Thats a 1.12 Client Combatlog Thing.

All Addons, All Interfaces are just tracking the ''Scorch-Hits''. So even if ur Fire Vulnerability has been resistet the Timer (BigWigs and so on) will jump back to 30sec after ur Scorch did Damage. But no Mage want to track Scorch. They want to track the Fire Vulnerability debuff attached from the Scorch and they dont want the timer to jump back to 30 when that Fire Vulnerability debuff has been resistet. They have Addons for this in the Classic remake (not a 1.12 Client) which can track resisted Fire Vulnerability debuffs.

Just imagen. U have 5 Stacks on a Boss and they run out in 5 sec > U cast a Scorch to refresh it > Ur Scorchtimer jumps back to 30 sec bc ur Scorch was hitting the Target but the Fire Vulnerability has been resists so u just loose all ur Stacks of Fire Vulnerability bc there is no way to track resisted Fire Vulnerability debuffs. Atm i just cast Scorch 2 times to refresh the Fire Vulnerability as a workaround.

As u all know Turtle wow has more than 16 debuff slots. I see Debuffs on the Mob but i cant see Stacks of the 17th applied debuff (Shagu-Tweaks). If my 5 Stacks run out, there are already to many debuffs on the mob (in Bossfights) from other player so i cant see any of my Fire Vulnerability stacks it event wont show me a single Fire Vulnerability if there are already to many debuffs on the Target. Atm i just cast 5x Scorch blind as workaround.

As a Frostmage u just dont have to care about this Problem bc Winterchill will get applied by Frostbolt and u spam Frostbolts all day but as Fire Mage where u have to us a specific cast (Scorch) for that its rly suboptimal.

Can we fix the Combatlog somehow on that 1.12 client to make it show Stack tracking after (5/Max amount)? Or can we change the Mage Firebolt to make it not attach but at least refresh that fire vulnerability?. Can we make Fire Vulnerability unresistable?. Its not like its unplayable but i understand why many mages rater spamming frostbolts than haveing problems with debuffsstacks running out.

On Nostalrius we had the same Problem but if the Fire Vulnerability stacks did run out we where able to see how many Fire Vulnerability Stacks we reapplied bc other ppl where not allowed to use dots. I cant see Stacks if there are more then 16 debuffs and i cant see any debuff it there are more than 32 debuffs on the Target. (Shagun-Tweaks / Debufffilter / BigWigs).

I was talking to many mages and most of them didnt even realised the Problem with the resistance of Fire Vulnerability. I have no clue how highend raider faceing this problem. I saw that 5 Stacks of Fire Vulnerability running out in Raid which had 3+ Fire Mages bc they think its enough if only 1 mage reapplied that Fire Vulnerability(which can be resisted) Stacks by casting 1 single Scorch. The Talentstree tells u ''Improved Scorch 3/3 = 100% Chance to attach a Fire Vulnerability'' and if they dont know that this debuff can be resisted they trust the blizzard tooltips and loose 15% of fire dmg.

**Comment by AkalixFrost** [comment]
Greetings.

Suggestions belong on our forums, not the bugtacker:
https://forum.turtle-wow.org/viewforum.php?f=14
