### ISSUE TITLE
Insect Swarm not improved by Moonfury and Moonglow talents (while Nature's Reach talent is improving it)

### ISSUE THREAD

**Issue by Bestoriop** [slowtorta/turtlewow-bug-tracker#5082]
**Please, provide a clear description what the bug is:** Insect Swarm is not improved by Moonglow and Moonfury talents while it is a balance spell and Nature's Reach talent is correctly improving it.

**Steps to reproduce the behavior with as much detail as possible:**

1. Be a level 33+ druid
2. Have Insect Swarm spell and moonglow/moonfury talents
3. Test mana/damage with or without talents

**IDs of affected creatures, items, quests or spells with a link to the relevant page:** 

Spell: https://database.turtle-wow.org/?spell=5570
Talent Nature's reach (affecting Insect Swarm in game) : https://database.turtle-wow.org/?spell=16819
Talent Moonfury : https://database.turtle-wow.org/?spell=16896
Talent Moonglow : https://database.turtle-wow.org/?spell=16845

**Expected behavior. Describe how it should work:** Moonfury and Moonglow talents should improve Insect Swarm as Nature's Reach talent.

**Comment by Zebouski** [comment]
The tooltips of moonfury and moonglow as found ingame do not include insect swarm.

These would be welcome changes for the class changes team to act upon but this does not belong in the bug tracker.

**Comment by Muigin** [comment]
Please use the bugtracker for reporting bugs.  If you would like to make a QoL suggestion for class changes, please reach out to the devs through other channels, including via applying for class change discussions.
