### ISSUE TITLE
Goblin brainwashing device resetting specs

### ISSUE THREAD

**Issue by vill8** [slowtorta/turtlewow-bug-tracker#5084]
**Please, provide a clear description what the bug is:**
Goblin brainwashing device is reseting the saved specs despite me being level 60 for over two weeks now, having spent all the available talent points in both specs. I have not used 2nd spec for over 2 days now.
**Steps to reproduce the behavior with as much detail as possible:**

1. Log in to the game
2. Choose the toon
3. See the "Your saved dual spec has been reset" message

**IDs of affected creatures, items, quests or spells with a link to the relevant page:**

Item: https://database.turtle-wow.org/?item=51715

**Expected behavior. Describe how it should work:**

It should not reset the saved specs for no reason.

**Comment by Muigin** [comment]
Fixed as of today's maintenance.
