### ISSUE TITLE
Dream's Herald +3-5 Nature Damage Not Working

### ISSUE THREAD

**Issue by Patryvius** [slowtorta/turtlewow-bug-tracker#5085]
**Please, provide a clear description what the bug is:**

When you use Dream's Herald it should cause +3-5 Nature Damage on hit, problem is that this never happens, you only get the normal melee damage, which you can see in the combat log.

**Steps to reproduce the behavior with as much detail as possible:**

1. Get Dream's Herald.
2. Swing it at target!
3. Hit the target!
4. Experience sadness when you don't see any electrical effect + nature damage on hit but at least the DoT still works when it procs.

**IDs of affected creatures, items, quests or spells with a link to the relevant page:**

Item: https://database.turtle-wow.org/?item=65008

**Expected behavior. Describe how it should work:**

When you hit the target you should get the nature/electrical discharge effect (just like when using Storm Gauntlets) and +3-5 Nature Damage should be dealt on hitting the target just like the description says.

**Comment by Zebouski** [comment]
No no, I know it is not intuitive but the the "Adds X School damage to your attacks" stat is a completely different stat than the +ele damage on weapons like thunderfury... the latter will combine the phys and spell damage into a single hit. While the Adds stat will literally have a separate damage number show up when you attack.

Not a bug
