### ISSUE TITLE
Open tents give LoS ?!

### ISSUE THREAD

**Issue by Adso777** [slowtorta/turtlewow-bug-tracker#5087]
**Please, provide a clear description what the bug is:**
I noticed open tents (the simple tents that are just 4 poles and a cover above) give LoS. I'd understand full tents (the close ones for example) giving LoS cause you can't in fact see through but the open one shouldn't give any LoS. You literally could shoot or spell cast through it.
**Steps to reproduce the behavior with as much detail as possible:**

1.
2. 
3. 

**IDs of affected creatures, items, quests or spells with a link to the relevant page:**

NPC: https://database.turtle-wow.org/?npc=
Item: https://database.turtle-wow.org/?item=
Quest: https://database.turtle-wow.org/?quest=
Spell: https://database.turtle-wow.org/?spell=
Object: https://database.turtle-wow.org/?object=

**Expected behavior. Describe how it should work:**

**Comment by twowTurtReynolds** [comment]
Where can I find one of these tents in the world to test at? You ignored our template that asked you for this info.

**Comment by Adso777** [comment]
Sorry for the missing info. Dwarven tents for example present in virtually all the mining or archeological sites (like the ones in Darkshore, Badlands, Loch Modan to name a few).

**Comment by twowTurtReynolds** [comment]
![image](https://github.com/slowtorta/turtlewow-bug-tracker/assets/151180101/c6e746c9-dcd7-4f9f-b721-87762d778d3b)
Please provide more evidence. I don't see any issues here.

**Comment by twowTurtReynolds** [comment]
I'll mark this closed until replication steps are provided.
