### ISSUE TITLE
Wailing caverns doesnt give exp

### ISSUE THREAD

**Issue by overtyped1** [slowtorta/turtlewow-bug-tracker#509]
I did wailing caverns and found I was getting 30 exp per elite kill, and 7 exp for non elites. Meanwhile, without a group, i get more than 100 exp for non elites. This seems INSANELY bad. Even the exp u get from dungeon quests doesn't justify EVER doing a dungeon.

**Comment by Tinyfin-github** [comment]
Greetings!

Please make a proper bug report with sources that show the correct behavior.
