### ISSUE TITLE
一个BUG反馈

### ISSUE THREAD

**Issue by genji1031** [slowtorta/turtlewow-bug-tracker#5092]
**Please, provide a clear description what the bug is:**
血环竞技场中，关于术士的某些技能不能重置冷却时间的问题  ----  恶魔支配技能

**Steps to reproduce the behavior with as much detail as possible:**

1.该技能在竞技场使用后，再次进入竞技场时，不会重置冷却时间
2. 
3. 

**IDs of affected creatures, items, quests or spells with a link to the relevant page:**

NPC: https://database.turtle-wow.org/?npc=
Item: https://database.turtle-wow.org/?item=
Quest: https://database.turtle-wow.org/?quest=
Spell: https://database.turtle-wow.org/?spell=
Object: https://database.turtle-wow.org/?object=

**Expected behavior. Describe how it should work:**

**Comment by twowTurtReynolds** [comment]
请用英文提交问题。我们无法通过自动翻译准确地翻译中文提交的错误报告，这使得我们难以理解问题的确切性质。谢谢！

Please submit the issues in English. We're unable to accurately translate bug reports submitted in Chinese through automatic translation, which makes it difficult for us to understand the exact nature of the issue. Thank you!
