### ISSUE TITLE
Nerubian Overseer Respawn

### ISSUE THREAD

**Issue by Perse-V** [slowtorta/turtlewow-bug-tracker#5093]
Been waiting for 2hours or more, Neruian Overseer corpse still not gone and not respawning

**Steps to reproduce the behavior with as much detail as possible:**

1.
2. 
3. 

**IDs of affected creatures, items, quests or spells with a link to the relevant page:**

NPC: Nerubian Overseer (https://database.turtle-wow.org/?npc=16184#objective-of)
Item: 
Quest: The Terrors of the Webweavers (https://database.turtle-wow.org/?quest=60065)
Spell: 
Object: 

PFQuest says 1hr 26min respawn time

**Comment by SabineWren** [comment]
pfQuest has its own repo for Turtle issues
https://github.com/shagu/pfQuest-turtle/issues

**Comment by Sringaram** [comment]
Overseer is a raid boss with a respawn timer of 1 week +/-.
