### ISSUE TITLE
Asia service area,Paladin Crusader Strike bonus issue

### ISSUE THREAD

**Issue by Moremoreman** [slowtorta/turtlewow-bug-tracker#5094]
Asia service area
Libram of Fervor ItemID:23203 and Knight-Lieutenant's Lamellar Gauntlets ItemID:23274,not work well.
There is no point bonus.

**Comment by twowTurtReynolds** [comment]
These items imrpove the power of your crusader strike. Try seal of righteousness, use crusader strike once, and see how much damage is added to SoR. Then, try again with the gloves and the libram on. The cruasder strike debuff will add more damage and the SoR number should be higher. I have confirmed this works.
