### ISSUE TITLE
Quest Item [Scroll of Return] 

### ISSUE THREAD

**Issue by ArnasM1** [slowtorta/turtlewow-bug-tracker#5095]
Quest Item [Scroll of Return] (horde) crashes the client if right clicked, even if does not display any right click action available - right clicking it always crashes the client.

**Comment by Mosch0512** [comment]
I had the same error.

**Comment by twowTurtReynolds** [comment]
Closing this as duplicate, will be tracked here https://github.com/slowtorta/turtlewow-bug-tracker/issues/4992
