### ISSUE TITLE
乌龟服魔兽世界回档后油箱里的6个奥术水晶消失，请GM处理一下，账号亚服血环PVP，角色圣骑士，名字：真的很哇塞

### ISSUE THREAD

**Issue by wswjh11** [slowtorta/turtlewow-bug-tracker#5099]
乌龟服魔兽世界回档后油箱里的6个奥术水晶消失，请GM处理一下

**Comment by wswjh11** [comment]
乌龟服魔兽世界回档后油箱里的6个奥术水晶消失，请GM处理一下，账号亚服血环PVP，角色圣骑士，名字：真的很哇塞

**Comment by Muigin** [comment]
Please submit the issues in English. We're unable to accurately translate bug reports submitted in Chinese through automatic translation, which makes it difficult for us to understand the exact nature of the issue. Thank you!
