### ISSUE TITLE
Bug: Wing clip is being removed for 1st target after applying to 2nd/Wing clip is only applying to 1 target.

### ISSUE THREAD

**Issue by vaelen-turtle** [slowtorta/turtlewow-bug-tracker#51]
By opening this Issue, I admit to having done the pertinent research using sources from Vanilla (preferably) or Classic. I also understand that sources from other private servers are not acceptable.

**Current behavior**:  After wing clipping a 2nd target, the debuff is removed from the first.

**Expected behavior**:  Wing clip should apply to all targets it is casted on for the full duration.

**Proofs**: 
![image](https://user-images.githubusercontent.com/85910069/121972564-4c4d4e80-cd73-11eb-8239-7dcdcdc45492.png)

**Steps to reproduce**:

1.  Apply wing clip to a target
2.  Apply wing clip to a 2nd target
3.  Check first target to see if it still has the debuff (within the time it should still have the debuff).

**Comment by Nolin7777** [comment]
Closed until proof added.
