### ISSUE TITLE
Warsong Gultch appears to 'defualt' to Alliance wins.

### ISSUE THREAD

**Issue by thrassoss** [slowtorta/turtlewow-bug-tracker#510]
**Please, provide a clear description what the bug is:**
Today Tuesday the 7th of December 2021 at just after 8pm server time I had the 1st Warsong gulch that 

1) did not have enough players and 
2) the side with the least players was Alliance. (The entire game was 3 Horde v. 1 Alliance.)

 I have had this happen dozens of times where Alliance outnumbered Horde but never when Horde outnumbered Alliance.

What normally happens is Alliance run all over Horde and get 2 quick caps and the games ends when the 5 minute timer runs down with a score of 2-0 and the game recording 'Alliance wins'.   This is only what I 'remember' happening.  I don't have screenshots because it seemed to be the proper outcome and didn't strike me as odd.  Moreover I could be misremembering something.  It is possible the alliance players actually got 3 caps in the 5 minutes and I was just screwing around mid-field, pvping with some random dude and didn't notice.  Again this seemed to be the proper outcome.  In this, much more common scenario, both sides get 3 (alliance, the winners) marks and 1(horde, the losers) mark.  

However when this 'black swan event' of Horde outnumbering Alliance in Warsong gulch happened, the game ended when the 5 minute timer ran out, and no marks were awarded.  The score was 0-2.  The 3rd flag was captured and being ran down the field by Horde, in a mirror to what typically happens in an Alliance heavy game when the game ended.  No marks were awarded.  I'm unsure if bonus honor was awarded as I had not noted what my 'this week' honor was before and after the battleground.  I had 13 marks of honor in my bank so it couldn't be a full stack issue.  I checked my mailbox an hour later and nothing.  No marks were in my backpack.

I can't remember who the other 2 hordes were but Mikiman was the only alliance player in the bg.  Again I could be misremembering how it works out or conflating multiple things happening.  But the real problem is it adds to an impression of Alliance favoritism.  Even if it turns out to be an incorrect remembering of events on my part, a clear policy of what 'should' happen might be useful.  When asking about the underlying rules for when/how marks get handed out during incomplete games several people from /world messaged me saying 'this is just intended behavior' with each having a different idea of which portion of the behavior was responsible.

Even if 'alliance wins by default' is true it should be easier to find in some FAQ.

**Steps to reproduce the behavior with as much detail as possible:**

1. Have a 3 Alliance v. 1 Horde Warsong gultch game and have the 3 Alliance get 2 'flag captures' within the 5 minute time frame.  See who gets what marks.
2. Have 3 Horde v. 1 Alliance WSG and have the 3 Horde get 2 'flag captures' within the 5 minute timeout period.  See who gets marks.
3. 

**IDs of affected creatures, items, quests or spells with a link to the relevant page:**

NPC: https://database.turtle-wow.org/?npc=
Item: https://database.turtle-wow.org/?item=20558
Quest: https://database.turtle-wow.org/?quest=
Spell: https://database.turtle-wow.org/?spell=
Object: https://database.turtle-wow.org/?object=

**Expected behavior. Describe how it should work:**
I would expect it to work so that when a timeout occurs due to too few players, if a one side has more 'flag captures' in the 'capture the flag' battleground, that side should be declared winner and marks awarded to the winners and losers as normal.
Alternatively it maybe it's suppose to work where a game ended by the 5 minute countdown with insufficient players no honor or marks are suppose to be awarded and since Alliance so typically wins those it was simply assumed to work a different way.

**Comment by thrassoss** [comment]
![WoWScrnShot_122721_123211](https://user-images.githubusercontent.com/3641804/147496340-ed05dd28-9f30-4a4f-bf33-1d3825af63b5.jpg)

This is a screenshot  of the win screen.  Note the 3rd flag is not capped by alliance.  The game timed out after the 5 min countdown.  Alliance had 2 flag captures Horde had none.

![WoWScrnShot_122721_123307](https://user-images.githubusercontent.com/3641804/147496514-06d49524-5795-4bdf-bb6a-146e414d3625.jpg)

Lucent an Alliance who was in that BG said they reieved marks.  Horde did not receive marks.

Whatever the complex system is that decides who should receive marks and honor and when just needs posted.  

After asking about this in channels again, someone tried telling me that it's not 'flag captures' that determines a win during a timeout it's whichever side has the most players and the losing team gains no marks if it has less than 4 members.  If this is the case it should really be documented.  It seems very much like more and more elaborate explanations are needed to explain witnessed behavior.

If it was just documented somewhere that people could link to easily it wouldn't seem so buggy perhaps.  Also some explanation to what to why this is the way it is could be helpful.  As it stands it appears rather capricious.

**Comment by jameyboor** [comment]
The mechanics are as follows:

The team with the most players at the moment of the game ending will be considered the winner.

The losing team will only be eligible to receive rewards after at least 10 minutes has passed. As stated in WoW Patch 1.8.4.
