### ISSUE TITLE
 honor value BUG

### ISSUE THREAD

**Issue by yejincao** [slowtorta/turtlewow-bug-tracker#5102]
Yesterday I played the Blood Ring Arena for a day (enjoying double the honor value), but the honor value only gave me 5W. I played with a friend this week. His honor value was already 11W, and mine was only 8W, and I The time spent playing in the Blood Ring Arena is longer than his.

**Comment by yejincao** [comment]
server: Asia-Blood Ring
ID:石头丶
Please check my honor value,Compensate my honor value

**Comment by twowTurtReynolds** [comment]
The team has done a deep dive and confirmed honor calculations to be working correctly.

I do not understand the terms 5W 11W 8W. 

Please watch the honor gains in chat, write them down if you need to, keeping in mind that successive kills on the same players has diminishing returns, and observe the total calculating correctly the next day.
