### ISSUE TITLE
Netherwind Belt's stamina was nerfed instead of spirit as announced

### ISSUE THREAD

**Issue by mylonelywow** [slowtorta/turtlewow-bug-tracker#5104]
**Please, provide a clear description what the bug is:**
Netherwind belt has 5 stamina when mage's T1 belt has 11 ?
**Steps to reproduce the behavior with as much detail as possible:**

1.
2. 
3. 

**IDs of affected creatures, items, quests or spells with a link to the relevant page:**

NPC: https://database.turtle-wow.org/?npc=
Item: https://database.turtle-wow.org/?item=16818 
Quest: https://database.turtle-wow.org/?quest=
Spell: https://database.turtle-wow.org/?spell=
Object: https://database.turtle-wow.org/?object=

**Expected behavior. Describe how it should work:**

**Comment by twowTurtReynolds** [comment]
Should be fixed next server restart :)
