### ISSUE TITLE
Ring of Holy Sacrement does not affect Retribution Aura

### ISSUE THREAD

**Issue by Denten93** [slowtorta/turtlewow-bug-tracker#5106]
The item "Ring of Holy Sacrement" from a custom quest "Scarlet Corruption" in Gilneas provided by Brother Elias in the Shademore Tavern, does not effect the holy damage done by Retribution Aura. The item's description states, "Increases damage done by Holy spells and effects by up to 16." I tested it on multiple mobs, but the damage inflicted only equaled the base damage from retribution aura, despite retribution aura dealing holy damage.

**Steps to reproduce the behavior with as much detail as possible:**

1. Equip Ring of Holy Sacrement while Retribution Aura is active.
2. Allow enemy mobs to strike you.
3. The damage inflicted against attacking mobs only equals the base damage from retribution aura.

**IDs of affected creatures, items, quests or spells with a link to the relevant page:**

NPC: https://database.turtle-wow.org/?npc=61387
Item: https://database.turtle-wow.org/?item=61478
Quest: https://database.turtle-wow.org/?quest=40935
Spell: https://database.turtle-wow.org/?spell=10300
Object: n/a

**Expected behavior. Describe how it should work:**
The item's description states, "Increases damage done by Holy spells and effects by up to 16." I tested it on multiple mobs, but it the damage inflicted only equaled the base damage from retribution aura, despite retribution aura dealing holy damage.

**Comment by Zebouski** [comment]
Spells are not guaranteed to have scaling to them. Is ret aura scaling on your general spellpower? Are other spells like SoR scaling on this ring?

**Comment by twowTurtReynolds** [comment]
It works fine, not a bug. Ret aura's scaling is just so low that rounding can hide 16 spell damage. It seems it takes roughly 25 spellpower to get a full point more of damage per reflect.

![image](https://github.com/slowtorta/turtlewow-bug-tracker/assets/151180101/493c6a58-f64f-4626-93b9-6bf14e9194c7)

Here's me with it on, then off. 23, then 22.
