### ISSUE TITLE
[祝福珠串]使用无法触发法伤效果

### ISSUE THREAD

**Issue by rongfei1982** [slowtorta/turtlewow-bug-tracker#5107]
[祝福珠串]使用无法触发法伤效果

**Comment by rongfei1982** [comment]
MS职业任务奖励饰品

**Comment by Muigin** [comment]
Please submit the issues in English. We're unable to accurately translate bug reports submitted in Chinese through automatic translation, which makes it difficult for us to understand the exact nature of the issue. Thank you!
