### ISSUE TITLE
Transmog reverts back to appearance of original item if taken any durability damage.

### ISSUE THREAD

**Issue by mambo1986** [slowtorta/turtlewow-bug-tracker#5112]
**Please, provide a clear description what the bug is:**
After applying transmog to slots not including weapons for some reason. When taking any durability damage ie. 99/100 the item will change in appearce to the item without transmog.
**Steps to reproduce the behavior with as much detail as possible:**

1. Transmog a shoulder/chest/belt/gloves/head item for example to anything
2.  go and get hit by some mobs and take 1 point of durability damage
3.  watch item change to item as if it wasnt transmogged.

**IDs of affected creatures, items, quests or spells with a link to the relevant page:**

NPC: https://database.turtle-wow.org/?npc=
Item: https://database.turtle-wow.org/?item=
Quest: https://database.turtle-wow.org/?quest=
Spell: https://database.turtle-wow.org/?spell=
Object: https://database.turtle-wow.org/?object=

**Expected behavior. Describe how it should work:**
After taking durability damage the item maintains its set transmog.

**Comment by twowTurtReynolds** [comment]
Duplicate of https://github.com/slowtorta/turtlewow-bug-tracker/issues/1400
