### ISSUE TITLE
Quest Magical Presence is wrong in Quest Log

### ISSUE THREAD

**Issue by Siventt** [slowtorta/turtlewow-bug-tracker#5114]
**Please, provide a clear description what the bug is:**
The quest "Magical Presence" from Gilneas does not show correctly on the quest log, instead another quest called "Rival Presence" is displayed.

**Steps to reproduce the behavior with as much detail as possible:**
1. Pick up the quest
2. Check Quest Log

**IDs of affected creatures, items, quests or spells with a link to the relevant page:**

NPC: https://database.turtle-wow.org/?npc=61271
Quest: https://database.turtle-wow.org/?quest=40941

**Expected behavior. Describe how it should work:**
I expect the correct quest to show up.

**Comment by ratkosrb** [comment]
https://github.com/slowtorta/turtlewow-bug-tracker/assets/35845488/2cc1ab9f-e5cf-4629-ac1e-a7e0a6812e55

Cannot reproduce the issue. Try clearing your WDB cache.

**Comment by Siventt** [comment]
Yes, it is fixed now. Thanks
