### ISSUE TITLE
Sweeping strikes does far more damage than 1.12 blizzlike

### ISSUE THREAD

**Issue by Zebouski** [slowtorta/turtlewow-bug-tracker#512]
**Please, provide a clear description what the bug is:**
When using sweeping strikes, the sweeping strikes copies of damage are far higher in damage than they should be
![image](https://user-images.githubusercontent.com/11151284/145271887-33b8780d-3c20-47f8-8635-4436474aae25.png)

This seems to be a function of the target's armor, as in PVP, warriors are now using SS and targeting hunter pets (which have high armor) in order to copy extremely high damage to the hunter themselves.

**Steps to reproduce the behavior with as much detail as possible:**

1. spec into sweeping strikes
2. pull 2 mobs
3. autoattack the first mob, see the copied damage be higher

**IDs of affected creatures, items, quests or spells with a link to the relevant page:**

Spell: https://database.turtle-wow.org/?spell=12292

**Expected behavior. Describe how it should work:**
the copied damage should correctly follow armore values

https://hilbert.wordpress.com/sweeping-strikes-guide/
```
This will usually work well. An easy test to verify this is finding two identical mobs (same level, armor and type), sunder one, pop SS and then hit them with your base fists. The sundered target will take the same amount of higher damage regardless of which mob you attack first. Your combat log would look something like this (with A having one sunder):

You hit A for 91.
Your Sweeping Strikes hits B for 86.

You hit B for 86.
Your Sweeping Strikes hits A for 91.

The total damage is the same.

What’s ironic is that armor still plays a big role in making SS so good, but we’ll cover this later. For now we can assume that without any buffs, your total damage will always be the same regardless of which mob you hit. 
```

**Comment by CosminPOP** [comment]
![image](https://user-images.githubusercontent.com/7255825/149026541-7a81fc38-8770-4967-9148-d5745399585a.png)

should be fixed soon
