### ISSUE TITLE
Triskelion of Roving Elements doesn't stack with minor speed enchant

### ISSUE THREAD

**Issue by Skaryna3** [slowtorta/turtlewow-bug-tracker#5126]
Triskelion of Roving Elements doesn't stack with minor speed boots enchant.

Equip both and run.

Triskelion of Roving Elements 60860

They used to work together. I liked to flex my running speed by equipping both boots with enchant and trinket. Now I run with the same speed as without the trinket.

**Comment by twowTurtReynolds** [comment]
Blizzard demonstrated a policy with wow that no movespeed enchants or talents would ever stack. TWoW is sticking with this design and while I cannot find a public report, this was likely fixed on purpose.
