### ISSUE TITLE
Проблема с петом Варлока Voidwalker

### ISSUE THREAD

**Issue by Tenb101** [slowtorta/turtlewow-bug-tracker#5127]
Сервер PvP Telabim
Чернокнижник - Shadowsun
Второй раз у меня изменился питомец демон Voidvalker на другого, соответственно все его способности исчезли, случилось это после использования скилла Жертва, В итоге ему опять нужно покупать книги с талантами в данный момент это 5+ голды. Я так не смогу играть))). Я бился с мобами, использовал по надобности скилл Войда Жертва, Отбился от мобов, вызвал его снова и он уже другой, без скилов(((, теперь нужно опять лететь в город и покупать ему книги со способностями, такое происходит уже второй раз.
![Без2ымян3ный](https://github.com/slowtorta/turtlewow-bug-tracker/assets/150248992/e070733d-d065-4b66-81d7-69e41b2eff68)
Вот питомец вчерашний
![Безымян222ый](https://github.com/slowtorta/turtlewow-bug-tracker/assets/150248992/b17b3982-bdb4-4133-8013-235b52902d42)
Вот уже другой сегодня, а перед этим был вообще другой.
Ведь демоны Лока не должны меняться на других вообще, иначе это будет ужас а не игра, в виду того что придётся каждый раз покупать кучу скиллов.

**Comment by twowTurtReynolds** [comment]
Looks like https://github.com/slowtorta/turtlewow-bug-tracker/issues/5218, will follow this up with the team.

**Comment by twowTurtReynolds** [comment]
Turns out, it was likely this bug: https://github.com/slowtorta/turtlewow-bug-tracker/issues/3871
