### ISSUE TITLE
ZG Axethrowers incorrectly cause 10-15 second stunlocks

### ISSUE THREAD

**Issue by Zebouski** [slowtorta/turtlewow-bug-tracker#513]
**Please, provide a clear description what the bug is:**
In ZG, the axethrowers will stun the entire raid back to back, without DRs, so everyone is chainstunned and cannot do anything. only a preemtive disarm or sheep spam can stop this

ZG headhunters have a similar problem but not nearly as problematic, they dont chainstun for very long

**Steps to reproduce the behavior with as much detail as possible:**

1. enter ZG, pull axe throwers 
2. once they start casting the axe throw spin, find yourself unable to do anything until they stop casting

**IDs of affected creatures, items, quests or spells with a link to the relevant page:**

NPC: https://database.turtle-wow.org/?npc=11350
https://database.turtle-wow.org/?npc=11351

**Expected behavior. Describe how it should work:**
when the npc spins, random people should be hit by axes, stunning them, but this shouldnt occur very often
https://youtu.be/8uXBvAi40hY?t=7792
see how on this vid, a few people like the mage were hit once, but not the entire raid chainstunned, as everyone keeps moving around doing as they do

**Comment by redmagejoe** [comment]
This behavior appears to still be prevalent. Requires immediate investigation.

**Comment by Zebouski** [comment]
I'm not sure if the stun has DRs on classic. But there is no DR on turtle, so the stunlock persists for the full duration.

But yeah check the classic footage, only a few people get hit by it, and theres a gap where nobody gets hit. This makes for a huge difference.

**Comment by Zeyla-TW** [comment]
From a quick glance at the file, I believe one of the effects on spell 24019 is applying as an AoE rather than to a random enemy within range, but I think there's also some sort of dummy script attached from what I could see. Would require further trial and error with the spell settings to fix it.

**Comment by Zeyla-TW** [comment]
After looking a little closer, it seems 24019's radius is 30 yards but there is no target cap currently, so it's constantly reapplying the effect to all targets within 30 yards. This should be a simple fix once someone gets around to it.
