### ISSUE TITLE
Onyxia 

### ISSUE THREAD

**Issue by HellToDawn** [slowtorta/turtlewow-bug-tracker#5130]
**Please, provide a clear description what the bug is:**

**Steps to reproduce the behavior with as much detail as possible:**

1.took quest warlords command in kargath
2. went to LBRS in 10 man raid and nothing dropped form bosses
3. went to orgrimmar and back to kargath, abandonned the quest and took it again.
4. went back to LBRS and one head dropped but couldent loot it due to " to many of that item in inventory" i had none of those items.
5. papers or heads fgrom the othe rbosses dident spawn

**IDs of affected creatures, items, quests or spells with a link to the relevant page:**

NPC: https://database.turtle-wow.org/?npc=
Item: https://database.turtle-wow.org/?item=
Quest: https://database.turtle-wow.org/?quest=
Spell: https://database.turtle-wow.org/?spell=
Object: https://database.turtle-wow.org/?object=

**Expected behavior. Describe how it should work:**

**Comment by Muigin** [comment]
Working as intended.

You cannot receive Group / Elite / Dungeon quest items while in a Raid (10 man is a raid group).  If you wish to obtain any of these items or make progress on LBRS quests, you will have to do so as a 5-man party.
