### ISSUE TITLE
我因为一个游戏bug导致冤死——潜水头盔（工程制作）I died unfairly due to a game bug — the Diving Helmet (by engineered)

### ISSUE THREAD

**Issue by waffle105** [slowtorta/turtlewow-bug-tracker#5133]
**Please, provide a clear description what the bug is:**
当我戴上潜水头盔下水后，并没有出现呼吸条，但时间到了以后，直接开始掉血，只是当时我潜水很深，游到水面上已经来不及了！这属于游戏bug，潜水头盔上并没有描述存在效果概率的情况，而且我下水再三确认没有呼吸条，已经正确佩戴头盔了.
我是工程专业，做了这个头盔之前尚未长时间在水下待过~ 

**Steps to reproduce the behavior with as much detail as possible:**

1.我已经准确佩戴了潜水头盔下水
2. 再三确认没有憋气的呼吸条
3. 在水下游玩了一会儿以后，直接开始掉血，由于潜水很深，当发现掉血已经无力回天
4. 这是一个龟速+HC的战士，已经是我第五个角色，ID是  战伍渣，服务器是拉文郡
5. 这个角色我投入了前后一个多月的时间进行培养，如果是因为bug导致我的角色死亡，也太冤枉了

**IDs of affected creatures, items, quests or spells with a link to the relevant page:**

NPC: https://database.turtle-wow.org/?npc=none
Item: https://database.turtle-wow.org/?item= i have no idea 
Quest: https://database.turtle-wow.org/?quest=none
Spell: https://database.turtle-wow.org/?spell=none
Object: https://database.turtle-wow.org/?object=

**Expected behavior. Describe how it should work:**
请检查并修复这个bug，并且复活我的角色，带上潜水头盔不能下水呼吸，也太bug了！
头戴潜水头盔 下水没有呼吸条，但是时间到了直接开始掉血，这是游戏bug啊~~~！！！！ 我玩了一个多月的乌龟+hc战士，因为一个bug死也太冤了！！！！就算因为服务器卡死的我也认！！！！如果我头盔没带好，下水是会有呼吸条的，但我确认没有呼吸条才下水游玩的，结果时间一到直接呼吸条出现空的开始掉血！！！根本没有反应时间了！！！请速速给我一个解释！而且我几次提交工单都莫名其妙消失了！！！请速度回复我！！！谢谢！！！！

【If you need me to translate it into English, you can contact my email [zyihong813@163.com](mailto:zyihong813@163.com). I would be happy to communicate with you in English during my free time to help Turtle WoW grow better!
![微信图片_20231109010007](https://github.com/slowtorta/turtlewow-bug-tracker/assets/24437265/e593307f-e044-4c1e-81ea-446ebd98e1bc)
】

**Comment by waffle105** [comment]
![微信截图_20231109010540](https://github.com/slowtorta/turtlewow-bug-tracker/assets/24437265/afd22a07-b636-4c81-a516-5bcf6cb4363b)
戴着潜水头盔还会淹死，真是天大的笑话！！！

**Comment by waffle105** [comment]
请问，什么时候才能解决？

**Comment by Muigin** [comment]
Please make all bugtracker tickets in clear and concise English.

**Comment by waffle105** [comment]
Certainly! Here's the translated text:

---

"On Wednesday evening, when I went underwater at a desolate place wearing a diving helmet, there was no breath bar displayed, which is normal. However, after a while, I started losing health directly without warning. At that time, I was deep underwater, and it was too late to swim back to the surface! This seems to be a game bug. The diving helmet does not mention any probability of underwater breathing effect, and I double-checked that there was no breath bar when I dived in, confirming that the helmet was correctly worn. This can be seen in the picture.
I'm an engineering major and had not spent a long time underwater before making this helmet.

Steps to reproduce the behavior with as much detail as possible:

1. I correctly wore the diving helmet before going underwater.
2. I repeatedly confirmed that there was no breath bar for holding breath.
3. After playing underwater for a while, I started losing health directly. Due to the depth of my dive, it was too late when I realized I was losing health.
4. This character is a slow + HC warrior, my fifth character, with the ID 'Zhan Wu Zha' on the Raven County server.
5. I have invested over a month in developing this character. If my character dies due to a bug, it would be very unfair.

IDs of affected creatures, items, quests, or spells with a link to the relevant page:

NPC: https://database.turtle-wow.org/?npc=none
Item: https://database.turtle-wow.org/?item= I have no idea
Quest: https://database.turtle-wow.org/?quest=none
Spell: https://database.turtle-wow.org/?spell=none
Object: https://database.turtle-wow.org/?object=

Expected behavior. Describe how it should work:
Please check and fix this bug, and revive my character. It's a bug that you can't breathe underwater with a diving helmet! Wearing a diving helmet and going underwater without a breath bar, but starting to lose health when the time is up, is a game bug! My turtle + HC warrior, which I played for over a month, dying due to a bug is too unjust!! Even if it’s due to server lag, I would accept it! If my helmet was not worn properly, there would be a breath bar when I went underwater, but I confirmed there was no breath bar before diving in. When the time was up, the breath bar suddenly appeared empty, and I started losing health! There was no time to react! Please give me an explanation urgently! Also, my several ticket submissions mysteriously disappeared! Please respond to me quickly! Thank you!!

Additionally, after I submitted several tickets to GMs and didn't receive a response, my account was unexpectedly banned for 7 days. I find this unreasonable and request a response from the headquarters!"

 thank you!!!
![Uploading IMG_4532.png…]()
