### ISSUE TITLE
Pvp rank haven't updated for my character today

### ISSUE THREAD

**Issue by PavelStanek** [slowtorta/turtlewow-bug-tracker#5134]
**Please, provide a clear description what the bug is:** high elf Eiriel on new pvp server has same pvp rank and progress as last week (rank 3 29%) even that I played pvp last week (ended up standing 242.

**Steps to reproduce the behavior with as much detail as possible:**

1.
2. 
3. 

**IDs of affected creatures, items, quests or spells with a link to the relevant page:**

NPC: https://database.turtle-wow.org/?npc=
Item: https://database.turtle-wow.org/?item=
Quest: https://database.turtle-wow.org/?quest=
Spell: https://database.turtle-wow.org/?spell=
Object: https://database.turtle-wow.org/?object=

**Expected behavior. Describe how it should work:** Improve Eiriel's pvp rank

**Comment by twowTurtReynolds** [comment]
The team has done a deep dive and confirmed honor calculations to be working correctly.
