### ISSUE TITLE
Plans Rune- Etched Crown 0 charge bug

### ISSUE THREAD

**Issue by Deadlyshadows87** [slowtorta/turtlewow-bug-tracker#5136]
**Please, provide a clear description what the bug is:**
Plans Rune- Etched Crown
**Steps to reproduce the behavior with as much detail as possible:**

1. Plans Rune- Etched Crown shows 0 charges
2. 
3. 

**IDs of affected creatures, items, quests or spells with a link to the relevant page:**
shows 0 charges will not let me learn this plan for BS.
NPC: https://database.turtle-wow.org/?npc=
Item: https://database.turtle-wow.org/?item=
Quest: https://database.turtle-wow.org/?quest=
Spell: https://database.turtle-wow.org/?spell=
Object: https://database.turtle-wow.org/?object=

**Expected behavior. Describe how it should work:**
Should let me use it. lol

**Comment by Muigin** [comment]
Please be sure to clear your WDB and attempt to use this item again.
