### ISSUE TITLE
Zandalarian Hero Charm and Eye of The Dead Bug

### ISSUE THREAD

**Issue by Shockhoof** [slowtorta/turtlewow-bug-tracker#5137]
Please, provide a clear description what the bug is:
Zandalarian Hero Charm and Eye of the Dead activates on each target of a chain heal, instead of on each cast of chain heal. See video: https://youtu.be/iv4TPmwr8xg
Note: this video is of Talisman of Ascendance; the bug behavior is similar to the old TOA bug, https://github.com/slowtorta/turtlewow-bug-tracker/issues/1496

Steps to reproduce the behavior with as much detail as possible:

Activate trinket
Activate Chain Heal on hurt zugs
Each chain will take 3 charges of the activation of Eye of the Dead or Zandalarian Hero Charm, instead of each cast.

Item: https://database.turtle-wow.org/?item=19950, https://database.turtle-wow.org/?item=23047
[References.docx](https://github.com/slowtorta/turtlewow-bug-tracker/files/8887244/References.docx)

Expected behavior. Describe how it should work:
Zandalarian Hero Charm and Eye of the Dead should gain a new charge / lose stacks after each spell cast of chain heal, instead of each hit in the chain of chain heal.

**Comment by Shockhoof** [comment]
The fix does NOT work for ZHC.  I have not confirmed if the fix worked for EOTD.

**Comment by Muigin** [comment]
@ratkosrb

**Comment by ratkosrb** [comment]
https://github.com/slowtorta/turtlewow-bug-tracker/assets/35845488/180545f9-14e3-45e1-a1ff-6dd6c9d0de16

**Comment by ratkosrb** [comment]
https://github.com/slowtorta/turtlewow-bug-tracker/assets/35845488/50560196-07d2-4595-9338-3e59e6b2c24f

**Comment by twowTurtReynolds** [comment]
Further evidence in https://github.com/slowtorta/turtlewow-bug-tracker/issues/4175

**Comment by ratkosrb** [comment]
@twowTurtReynolds The comments in the linked post are from before my changes.

**Comment by twowTurtReynolds** [comment]
![image](https://github.com/slowtorta/turtlewow-bug-tracker/assets/151180101/7a36a3a8-1ccf-42ba-b6ca-42af0c6e8942)
Confirmed fixed.
