### ISSUE TITLE
Possible issue with crumpled note quest in BRD.

### ISSUE THREAD

**Issue by DrRockz0** [slowtorta/turtlewow-bug-tracker#5139]
**Please, provide a clear description what the bug is:**

**Steps to reproduce the behavior with as much detail as possible:**

1. Looted crumpled note.
2. Went to turn in note (verified that yellow ? was over Marshall's head).
3. Received error "You are not eligible for this quest". Group proceeded to kill/loot Angerforge and Golem boss. Note is no longer in my inventory. Verified that quest is not available in quest log or on Marshall.

Apologies if this is incorrect format.. new to this. Appreciate all you guys do!

**IDs of affected creatures, items, quests or spells with a link to the relevant page:**

NPC: https://database.turtle-wow.org/?npc=
Item: https://database.turtle-wow.org/?item=
Quest: https://database.turtle-wow.org/?quest=
Spell: https://database.turtle-wow.org/?spell=
Object: https://database.turtle-wow.org/?object=

**Expected behavior. Describe how it should work:**

**Comment by ratkosrb** [comment]
I assume you are talking about this quest: https://classicdb.ch/?quest=4264

This is an Alliance quest. Are you sure you weren't on a horde character when you looted the item?

**Comment by ratkosrb** [comment]
I've assigned a race requirement to the item itself as well to make it clear this is an Alliance quest item.
