### ISSUE TITLE
High Elf Dailies Bug

### ISSUE THREAD

**Issue by Zangatsu** [slowtorta/turtlewow-bug-tracker#514]
Relics in Feralas, and Tears of the Poppy, were completed in my quest log.  We arrived in Alah'thalas at 12:02 Server Time (2 minutes after the daily reset time) to find that the quests has been removed from our log, and the quest items deleted.

**Comment by slowtorta** [comment]
That's correct behavior. Dailies and weeklies reset at midnight.
