### ISSUE TITLE
Nature Protection Potion Overwrites Elixir of Greater Nature Power

### ISSUE THREAD

**Issue by Niqlo** [slowtorta/turtlewow-bug-tracker#5140]
**Please, provide a clear description what the bug is:**
The smaller nature protection potions (not GNPP) overwrite elixir of greater nature power.

**Steps to reproduce the behavior with as much detail as possible:**

1. drink elixir of greater nature power
2. drink nature protection potion

**IDs of affected creatures, items, quests or spells with a link to the relevant page:**

Item: https://database.turtle-wow.org/?item=50237
Item: https://database.turtle-wow.org/?item=6052

**Expected behavior. Describe how it should work:**
nature protection potion should not remove elixir of greater nature power as the buffs are unrelated.

**Comment by ratkosrb** [comment]
Will be fixed by https://github.com/slowtorta/turtle-wow/commit/25e06f1a7486d5037971126fbb43aabc82d2cdda
