### ISSUE TITLE
'Complete' button doesn't activate

### ISSUE THREAD

**Issue by Siachaaton** [slowtorta/turtlewow-bug-tracker#5142]
The same bug on two characters and two different quests.
Mehityaa, lvl 60 troll warrior - Betrayed pt. II in Azshara; Abstinency, lvl 46 undead priest.- Clamlette surprise

1.  I take the quest 
2. I complete the tasks
3. i return to the NPC (Clamlette)
4. the question mark lights up in yellow meaning i can hand the quest
5. as i speak to the NPC, the 'Complete' button remains grey.

As for the warrior, it's the book one has to use after killing the blood elves. As i Click it, the button also remains unclickable, even though the other conditions are met. 

Tried re-logging, abandonming the quest and taking it again, clearing the WDB folder - nothing helps.

![image](https://github.com/slowtorta/turtlewow-bug-tracker/assets/110936958/0dc3f94b-adb9-4db2-b6e3-bff9a6703283)

**Steps to reproduce the behavior with as much detail as possible:**

1.
7. 
8. 

**IDs of affected creatures, items, quests or spells with a link to the relevant page:**

NPC: https://database.turtle-wow.org/?npc=
Item: https://database.turtle-wow.org/?item=
Quest: https://database.turtle-wow.org/?quest=
Spell: https://database.turtle-wow.org/?spell=
Object: https://database.turtle-wow.org/?object=

**Expected behavior. Describe how it should work:**

**Comment by Zebouski** [comment]
I see you have some addons enabled which very well can interfere and damage this blizzard UI. 

Please disable them all, _then_ do the wdb, do the abandon retake and try again.

**Comment by ratkosrb** [comment]
Have you at any point put any of the required items by the quest in your bank? I think it was concluded before that not being able to turn in quests was related to doing that.

**Comment by Siachaaton** [comment]
> Have you at any point put any of the required items by the quest in your bank? I think it was concluded before that not being able to turn in quests was related to doing that.

Well , by the time I came to thew NPC all of the items were in my bags with me.

**Comment by Siachaaton** [comment]
> Have you at any point put any of the required items by the quest in your bank? I think it was concluded before that not being able to turn in quests was related to doing that.

Will try to. thanks!

**Comment by Siachaaton** [comment]
It somehow worked without disabling the addons.
