### ISSUE TITLE
Reel unavailable

### ISSUE THREAD

**Issue by donglike78** [slowtorta/turtlewow-bug-tracker#5144]
**Please, provide a clear description what the bug is:**

**Steps to reproduce the behavior with as much detail as possible:**

1.I have deleted the WDB folder and logged back into the game, but still can't use the quest items
2. To interfere with Naga's mission
3. Reel unavailable

**IDs of affected creatures, items, quests or spells with a link to the relevant page:**

NPC: https://database.turtle-wow.org/?npc=
Item: https://database.turtle-wow.org/?item=
Quest: https://database.turtle-wow.org/?quest=
Spell: https://database.turtle-wow.org/?spell=
Object: https://database.turtle-wow.org/?object=

**Expected behavior. Describe how it should work:**

**Comment by Muigin** [comment]
Please provide more information.  Please use the template to actually link the IDs of relevant NPCs, quests, items, spells, etc.
