### ISSUE TITLE
训练野兽技能BUG

### ISSUE THREAD

**Issue by yxshow7** [slowtorta/turtlewow-bug-tracker#5146]
亚服 血环服务器 暗夜精灵猎人 名字 千羽花翎   训练野兽技能BUG 已经学了宠物被动技能 但是训练野兽技能栏里面无法显示被动技能 宠物无法训练自然护甲、持久耐力等被动技能

**Comment by Muigin** [comment]
请用英文提交问题。我们无法通过自动翻译准确地翻译中文提交的错误报告，这使得我们难以理解问题的确切性质。谢谢！

Please submit the issues in English. We're unable to accurately translate bug reports submitted in Chinese through automatic translation, which makes it difficult for us to understand the exact nature of the issue. Thank you!
