### ISSUE TITLE
Goblin Brainwashing Device still bugged

### ISSUE THREAD

**Issue by fat4free** [slowtorta/turtlewow-bug-tracker#5149]
**Please, provide a clear description what the bug is:**

**Steps to reproduce the behavior with as much detail as possible:**

1. Specs do not save while leveling
2. I've spent 20g respecing my character over the last couple weeks trying to get dual spec to actually work.
3. I logged into today hoping to have two free respecs, but it still cost me 5g.
4. I can't afford a mount because I've wasted so much gold trying to get this to work.

**IDs of affected creatures, items, quests or spells with a link to the relevant page:**

NPC: https://database.turtle-wow.org/?npc=
Item: https://database.turtle-wow.org/?item=
Quest: https://database.turtle-wow.org/?quest=
Spell: https://database.turtle-wow.org/?spell=
Object: https://database.turtle-wow.org/?object=

**Expected behavior. Describe how it should work:**
I know how it works. I use it on the PVE realm as intended.

**Comment by ratkosrb** [comment]
I can't reproduce the issue. The saved specs do not get reset while leveling up below 60.

**Comment by fat4free** [comment]
It hasn't happened exactly when I level. It happens sometimes after logging in having leveled before logging out previously and not saving specs with the new number of talents points. Then I go to use the second dual spec. It says none is saved despite having the option to 'activate' on the device. Then I've hit 'reset my talents' thinking it will use one of my free respecs and ill just go save an offspec again, and it costs me 5g.

**Comment by ratkosrb** [comment]
I understand that the reset happens on the next login, but the fact is there is an explicit check for the player level before that happens now, and it does not reset specs of characters below 60 anymore. I tested logging out and my specs were not wiped after having changed my level. So the only conclusion I can make is that the change to add a level check is not currently live on the server, since it works as intended locally. Perhaps if you wait a week for the next server update, it will no longer reset your spec upon level up.

**Comment by m-hicks-OH** [comment]
I can confirm this is STILL an issue.  I understand you say you can't reproduce, but it is still happening.  It just happened to me last night.  Everything was working correctly, I was periodically changing specs between my PROT and RET builds (points spent).  I leveled up to 50, exited game, came back this morning and both specs were gone..... So... it's 100% happening.

**Comment by fat4free** [comment]
I'm out 20g and no 2x free respecs. Disaster

**Comment by m-hicks-OH** [comment]
like... how hard is it to find out what's happening?  Clearly, there is code in multiple places resetting specs.  Just find it.

**Comment by m-hicks-OH** [comment]
Heck... open source it, and I'll find it for you.

**Comment by fat4free** [comment]
Here's a capture of the device after I spawned it to switch to healer. Both specs are randomly forgotten. I cannot switch to secondary/healer spec. I save the primary spec AGAIN and would have pay another 5g to make a healer spec to save as secondary only to have it forgotten later.

https://youtu.be/2cF2SS7slpo

This is ridiculous. I want my free respecs, the issue fixed, and my wasted gold returned.

**Comment by fat4free** [comment]
Here's an even more obvious video following the last post - https://youtu.be/PEtg2szd04A. I log in and it says the infamous "Your saved dual spec has been reset". I leveled from 53 to 54 between videos. I open GBD to see even spec 1 is reset that you saw me set in the previous video. Of course, spec 2 didn't change because i didn't want to waste 5g again.

What more evidence do you need that this is still a problem?

**Comment by fat4free** [comment]
Oh here's a third video. I logged off for one sec, and it reset again. I guess it doesn't even take leveling.

https://youtu.be/fLpxI7V9njI

**Comment by fat4free** [comment]
For the final prestige, here's an uninterrupted video of me going to just char select and still getting a reset.

https://www.youtube.com/watch?v=WK0fhdAJZzo&ab_channel=Abovethelaw

**Comment by RedDragoCZ** [comment]
Happened to me as well, lost both my specs, cant activate 2nd one. lvl 47, was working fine till today
