### ISSUE TITLE
TWOW | Pet Attack ability has been removed from the Pet Bar

### ISSUE THREAD

**Issue by Magnormous** [slowtorta/turtlewow-bug-tracker#515]
**Please, provide a clear description what the bug is:**

The Pet Attack ability has been removed from the Pet Action Bar, and is not available to re-slot from the Spellbook & Abilities tab.

**Steps to reproduce the behavior with as much detail as possible:**

1.  Pet Attack no longer exists on the Pet Action Bar
2.  Cannot toggle Pet Attack
3.  Inconvenient need to script the Pet Attack action in order to use pet

**IDs of affected creatures, items, quests or spells with a link to the relevant page:**

Player: Beastwood

NPC: https://database.turtle-wow.org/?npc=
Item: https://database.turtle-wow.org/?item=
Quest: https://database.turtle-wow.org/?quest=
Spell: https://database.turtle-wow.org/?spell=
Object: https://database.turtle-wow.org/?object=

**Expected behavior. Describe how it should work:**

The Pet Attack ability should be available for toggle along with other pet action abilities such as Passive, Defensive, and Aggressive abilities.

**Comment by slowtorta** [comment]
Please submit a ticket. It's a GM issue.
