### ISSUE TITLE
The escort quest Rescue From Jaedenar doesn't work

### ISSUE THREAD

**Issue by octav3k** [slowtorta/turtlewow-bug-tracker#5150]
**Please, provide a clear description what the bug is:**
The escort quest Rescue From Jaedenar doesn't work. When someone in the group accepts it, it is correctly shared with those that are on the same stage, but the NPC doesn't start moving.

**Steps to reproduce the behavior with as much detail as possible:**
1. Acquire the Blood Red Key and accept its quest
2. Turn in "A Strange Red Key"
3. Accept Rescue From Jaedenar

**IDs of affected creatures, items, quests or spells with a link to the relevant page:**
NPC: https://database.turtle-wow.org/?npc=11016
NPC: https://database.turtle-wow.org/?npc=11018
Quest: https://database.turtle-wow.org/?quest=5203

**Expected behavior. Describe how it should work:**
The elf (Captured Arko'narin should start slowly walking to the back of the cave, to the chest near the last brazier for the quest Dousing the Flames of Protection), after which she should transform into Arko'narin (she should despawn and the NPC Arko'narin should take her place) and start walking out.

**Comment by octav3k** [comment]
Tried it again today and it worked flawlessly. I don't know why it didn't work 4 days ago.

**Comment by twowTurtReynolds** [comment]
Weird, @octav3k or if anyone else sees this bug reappear, comment here and ping me and we'll try to test and debug asap.
