### ISSUE TITLE
Vial of Potnet Venoms is broken right now< and apply only 2 stacks instead of 5.

### ISSUE THREAD

**Issue by Notaric** [slowtorta/turtlewow-bug-tracker#5152]
**Please, provide a clear description what the bug is:**
Vial of Potent Venoms is broken right now. It stacks 2 times only, but animation keep going like you applying stacks but still only 2 stacks are on target. Tested on different characters.

**Steps to reproduce the behavior with as much detail as possible:**

1. Equip Vial of Potent Venoms
2. Go to target Dummy.
3. Check.

**IDs of affected creatures, items, quests or spells with a link to the relevant page:**
Item: https://database.turtle-wow.org/?item=61243
Spell: https://database.turtle-wow.org/?spell=45521

**Expected behavior. Describe how it should work:**
I guess it should work as intended and apply 5 stacks.

**Comment by Zmitrok1984** [comment]
Looks into [Changelog from 30 October](https://forum.turtle-wow.org/viewtopic.php?t=11294)
Potent Venom now stacks only 2 times, ticks every 3 seconds instead of 2 seconds, lasts 12 seconds instead of 10 seconds and the damage per tick has been increased to 30.

**Comment by Muigin** [comment]
Working as intended.

**Comment by Notaric** [comment]
Equip: Your melee and ranged attacks have a chance to inject poison into your target that deals 100 Nature damage over 8 sec. Stacks up to 5 times. 

It is actually was 8 sec before? Where we took 10?

**Comment by balakethelock** [comment]
Clear your WDB

**Comment by Zebouski** [comment]
Not a WDB issue, as the green text of spells cannot be updated serverside. The text correction will need to arrive with the next client patch.
