### ISSUE TITLE
Crystal Sword of the Blossom No Sheathe Model

### ISSUE THREAD

**Issue by Judo101** [slowtorta/turtlewow-bug-tracker#5153]
Crystal Sword of the Blossom has no sheathe model. It appears when you unsheathe your weapons (default key Z), but is otherwise invisible.

This issue occurs with and without it being transmogged. It occurs in main hand and off hand.

ID: https://database.turtle-wow.org/?item=61523

Pics:

Sheathed, no offhand equipped
![image](https://github.com/slowtorta/turtlewow-bug-tracker/assets/17147536/86df3251-49a2-42bd-b60b-e58abe4ae188)

Unsheathed, no offhand equipped
![image](https://github.com/slowtorta/turtlewow-bug-tracker/assets/17147536/f8989793-820b-43ab-9376-13f3e4e12fc6)

**Comment by Dragunovi** [comment]
Should be fixed with next server restart.
