### ISSUE TITLE
Hateforge Quarry mining nodes

### ISSUE THREAD

**Issue by Dwordis** [slowtorta/turtlewow-bug-tracker#5154]
**Please, provide a clear description what the bug is:**
Hateforge Quarry (possibly other instances) has thorium nodes that respawn after a short time allowing players to clear the instance and infinitely farm thorium with no risk. This will affect the arcane crystal and thorium market.

**Steps to reproduce the behavior with as much detail as possible:**

1. Enter Hateforge Quarry
2.  Mine node
3.  Wait for respawn

**IDs of affected creatures, items, quests or spells with a link to the relevant page:**

NPC: https://database.turtle-wow.org/?npc=
Item: https://database.turtle-wow.org/?item=
Quest: https://database.turtle-wow.org/?quest=
Spell: https://database.turtle-wow.org/?spell=
Object: https://database.turtle-wow.org/?object=

**Expected behavior. Describe how it should work:**

**Comment by Muigin** [comment]
The timer on these nodes was indeed 45 minutes, at odds with the 7 day respawn times on vanilla dungeon mining nodes. I have submitted a fix for this which will be applied on the next server maintenance.
