### ISSUE TITLE
Impossible to train Bite above rank 1 on a plainstrider lvl 40

### ISSUE THREAD

**Issue by CptMcNash** [slowtorta/turtlewow-bug-tracker#5155]
So it's an issue that I thought would fix itself but never did.
I have the pink plainstrider, Mazzranache, that you get around lvl 9. He comes with Bite rank 1, Growl rank 1 and Cower rank 1.
He is now lvl 40, with plenty of training points - but on the beast training menu, all I have is Bite (rank 1) greyed out. No way to upgrade bite, but no issue with all the other spells - Growl is at rank 4, and I can train it to rank 5. Bite, on the other hand, is completely locked.

![WoWScrnShot_111023_094206](https://github.com/slowtorta/turtlewow-bug-tracker/assets/150428726/9772320f-e8cb-4918-9a3f-9bac9898f689)

Picture for context.

Help a goblin out and give more bite to my pink flamingo. Sorry code monkeys if this is is a hassle.
Love you team Turtle.

**Comment by CptMcNash** [comment]
To make it clearer, my WDB folder has been cleared many times through my lvling, this has never fixed the issue.

**Comment by Muigin** [comment]
Have you tamed another beast that knows Bite Rank 2, Rank 3, Rank 4, etc? You cannot teach any pet these spells until you first acquire them from the wild. Your screenshot does not show whether or not you have learned these spells already.

**Comment by CptMcNash** [comment]
I did not know that about classic hunters, that you had to gather the ranks in the wild first !
I apologize for my noob post then, this can be closed ! I am sure this will be it.

**Comment by CptMcNash** [comment]
Thank you very much

**Comment by Muigin** [comment]
Here is a reference of all the different abilities from wild beasts and which beasts have what ranks:  https://www.wow-petopia.com/classic/abilities.php

Happy hunting!
