### ISSUE TITLE
Spear of the Endless Hunt has more than the 1% crit bonus shown in tooltip.

### ISSUE THREAD

**Issue by distr0m** [slowtorta/turtlewow-bug-tracker#5157]
**Please, provide a clear description what the bug is:**
The item [Spear of the Endless Hunt] has around 3% crit bonus instead of the 1% shown in tooltip.

**Steps to reproduce the behavior with as much detail as possible:**

1. Install the Addon "BetterCharacterStats", to see the crit% stat change
2. Have [Spear of the Endless Hunt] equipped
3. Equip any other 2 handers, then un-equip it, leaving you with no weapon equipped
4. Re-equip the Spear, and you should see the crit% gain be a lot more than 1.

**IDs of affected creatures, items, quests or spells with a link to the relevant page:**

Item: https://database.turtle-wow.org/?item=50429

**Expected behavior. Describe how it should work:**
When equipping the [Spear of the Endless Hunt], I should gain only 1% crit, as shown in the tooltip.

NOTE : I asked another Hunter with the same spear AND the Addon to test it, and he confirmed the bug. The issue MIGHT be with the Addon, but since all other items are calculated fine, it leads me to believe the issue is with the item.

**Comment by mrkajito** [comment]
Seems to be an issue on your end and/or a display bug, i use the addon, and the weapon gives me the correct amount of %crit.

**Comment by distr0m** [comment]
> Seems to be an issue on your end and/or a display bug, i use the addon, and the weapon gives me the correct amount of %crit.

Seems to be fixed now...
