### ISSUE TITLE
TWOW | Aspect of the Cheetah Buff is removed when hit\damage taken.

### ISSUE THREAD

**Issue by Magnormous** [slowtorta/turtlewow-bug-tracker#516]
**Please, provide a clear description what the bug is:**

The Aspect of the Cheetah buff is completely removed when damaged.  

**Steps to reproduce the behavior with as much detail as possible:**

1. When damaged the Aspect of the Cheetah buff is completely removed requiring a re-cast.
2. Buff penalty when damaged remains, but the buff does not.
3. The need to re-cast Aspect of the Cheetah causes excess depletion of mana.

**IDs of affected creatures, items, quests or spells with a link to the relevant page:**

Player:  Beastwood

NPC: https://database.turtle-wow.org/?npc=
Item: https://database.turtle-wow.org/?item=
Quest: https://database.turtle-wow.org/?quest=
Spell: https://database.turtle-wow.org/?spell=
Object: https://database.turtle-wow.org/?object=

**Expected behavior. Describe how it should work:**

Up until the past couple of months the Aspect of the Cheetah buff did not get removed from applied buffs when damaged.  The buff penalty was applied, but the buff remained.

**Comment by Velite12** [comment]
Have all your addons been disabled and it still continues to be removed on daze?

**Comment by Tinyfin-github** [comment]
Greetings!  I have checked and i have been unable to reproduce the issue.
Please try to disable all addons and clear your WDB folder while the game is closed.

https://user-images.githubusercontent.com/83077166/145669032-cf0867fb-6f8b-4f0a-8345-caaf50f18b68.mp4

**Comment by Magnormous** [comment]
Hello,

I've turned off ALL of my addons (LFT included), and have cleared my WDB
folder.  It works. I'm going to test all add-ons.

While I have you though. I put in a bug report for my missing pet attack
ability on my pet bar. And it's not available to re add. Thoughts?

Beast

**Comment by Lawmonark** [comment]
This sounds like "Anti-Daze" from "Hunter Swiss Knife" addon.

If you want to disable it, type "/hsk"  ingame and disable that feature.
