### ISSUE TITLE
Priest class call on Nefarian fight make Renew do damage too

### ISSUE THREAD

**Issue by DRepetsky** [slowtorta/turtlewow-bug-tracker#5162]
Renew should not do damage during priest class call, only direct heals should

https://bpa.st/raw/3IYA
summary generated using this tool https://github.com/melbaa/summarize_consumes

logs from that raid
http://monkeylogs.com/viewer/5461/base?history_state=1

**Comment by ratkosrb** [comment]
https://github.com/slowtorta/turtlewow-bug-tracker/assets/35845488/3903e2a9-9550-499d-b4a6-a0b8d1bb6531

Cannot reproduce the issue. It does not trigger the damage when using Renew.
