### ISSUE TITLE
Hateforge Watcher kill AFK/Loading players near Enter  Hateforge dungeon

### ISSUE THREAD

**Issue by hokagegaara** [slowtorta/turtlewow-bug-tracker#5163]
Remove 1 Hateforge Watcher who walk near Enter to Hateforge dungeon
NPC: https://database.turtle-wow.org/?npc=60716
![изображение](https://github.com/slowtorta/turtlewow-bug-tracker/assets/7520527/5f481999-1693-428b-b727-9cd33e1d8dd2)
This NPC walk/patrol near exit dungeon and kill AFK/Loading players. Players who left the Dungeon and often some simply do not have time to load and react to it
![изображение](https://github.com/slowtorta/turtlewow-bug-tracker/assets/7520527/c9493503-f479-458d-a865-2d1511e9ddd3)
![изображение](https://github.com/slowtorta/turtlewow-bug-tracker/assets/7520527/bb944391-ab5c-43cc-92f5-0cf2add974f9)

**Comment by hokagegaara** [comment]
This really infuriates the players, I saw a bunch of people in fabric sets just leave the dungeon and die after taking a couple of steps when they saw that they were being attacked and some couldn’t even do anything because “Hateforge Watcher” deals 200-400 damage (10 hits for a kill and that’s 10 -15s).

**Comment by hokagegaara** [comment]
![изображение](https://github.com/slowtorta/turtlewow-bug-tracker/assets/7520527/4e7956ef-311c-4d41-b597-2e736f4226e8)

**Comment by hokagegaara** [comment]
3 body...2 body in one position and skeleton
![изображение](https://github.com/slowtorta/turtlewow-bug-tracker/assets/7520527/692e1c3a-283d-4053-84ad-e2eca3d72f1f)

**Comment by balakethelock** [comment]
I guess the question to answer is, do dungeons in vanilla wow have mobs right at the exit? If they don't, then this behavior is unblizzlike (for good reason, mobs attack you while you are still loading into the uninstanced world) and should be removed.
But if there are dungeons in vanilla with mobs right outside the entrance at aggro range, I don't see why this specific case of it should be removed.

**Comment by hokagegaara** [comment]
> I guess the question to answer is, do dungeons in vanilla wow have mobs right at the exit? If they don't, then this behavior is unblizzlike (for good reason, mobs attack you while you are still loading into the uninstanced world) and should be removed. But if there are dungeons in vanilla with mobs right outside the entrance at aggro range, I don't see why this specific case of it should be removed.
Yes, there are, but they do not aggro on those who enter or exit the dungeon, but are located a little further from the entrance or exit. But it’s very annoying when you’re loading or waiting to find a group.
![изображение](https://github.com/slowtorta/turtlewow-bug-tracker/assets/7520527/15778649-d266-45a8-8092-10a73f87160e)
