### ISSUE TITLE
Goblin Brainwashing Device - Not listing Talent Points on Saved Specs

### ISSUE THREAD

**Issue by Bang1726528** [slowtorta/turtlewow-bug-tracker#5164]
**Please, provide a clear description what the bug is:**

My Goblin Brainwashing Device does not display the talent points for my saved specs and never has ever since I bought it from Store tokens about 4-5 months ago. I didn't even realise this was a bug until I was playing on my friends account and used his Goblin Brainwashing Device and saw that his saved specs show the talent points next to each saved spec.

**Steps to reproduce the behavior with as much detail as possible:**

1. Simply opening my Goblin brainwashing device will always reproduce this error. Another person in my guild also experiences this issue but only on some of their characters. On their main character the bug is not present. 
2. I have also contacted a GM who replaced my Goblin Brainwashing Device (it was removed from my bags in real time and replaced) and the issue still persisted.
3.  I have tried logging into the game with a completely default UI, and still there are no talent points listed. Even when creating a new spec and saving it while on a default UI.
4. I have deleted my WDB folder many times as I always like keeping in-game items listed correctly to the current patch, so it's not related to WDB.

Here is what mine looks like. And keep in mind it has been like this for 5 months, even before the recent changes to add 2 more slots / fix the "bug " of free respecs.

![image](https://github.com/slowtorta/turtlewow-bug-tracker/assets/150500603/1b0e9615-be37-430d-96b4-0b6eedf27653)

**IDs of affected creatures, items, quests or spells with a link to the relevant page:**

Item: https://database.turtle-wow.org/?item=51715

**Expected behavior. Describe how it should work:**

Here is how it's supposed to work, taken on my friends account.  

![image](https://github.com/slowtorta/turtlewow-bug-tracker/assets/150500603/19ad51b3-1334-4520-b8c2-1b4984452bcd)

My friends was purchased using in game GOLD. Whereas mine was purchased via store currency. Could this be the reason for it?

**Comment by Bang1726528** [comment]
Also just had my friend log in my account and check my device for me himself, and it shows exactly the same for him on his client. Even though his brainwashing device does work fine on that same client on his own account/character.

So it's some sort of server side issue, possibly related to it being a store purchased device instead of using gold? I believe there is some sort of quest related to the gold version, so maybe it's to do with that?

![image](https://github.com/slowtorta/turtlewow-bug-tracker/assets/150500603/e7f839e0-4eb6-426d-81b5-bddf49555ba4)

**Comment by ratkosrb** [comment]
Are you a Mage? I notice there's a comment in the code saying mage trees are broken and points cant be calculated correctly for them.

**Comment by ratkosrb** [comment]
It seems the bug this was referring to has already been fixed. I removed the check and everything works fine. You will be able to see your talent points on the saved specs next week.
https://github.com/slowtorta/turtle-wow/commit/d78e72834b6028f9bce8d2835776222c20277c06

**Comment by Bang1726528** [comment]
> Are you a Mage? I notice there's a comment in the code saying mage trees are broken and points cant be calculated correctly for them.

Yes I am a mage. and another mage in my guild has the same issue. So yes thanks for the update it's related to mages!

**Comment by Bang1726528** [comment]
> It seems the bug this was referring to has already been fixed. I removed the check and everything works fine. You will be able to see your talent points on the saved specs next week. https://github.com/slowtorta/turtle-wow/commit/d78e72834b6028f9bce8d2835776222c20277c06

Not sure why but this commit you have linked me is not working.
