### ISSUE TITLE
I died unfairly due to a game bug — the Diving Helmet (by engineered)

### ISSUE THREAD

**Issue by waffle105** [slowtorta/turtlewow-bug-tracker#5165]
"On Wednesday evening, when I went underwater at a desolate place wearing a diving helmet, there was no breath bar displayed, which is normal. However, after a while, I started losing health directly without warning. At that time, I was deep underwater, and it was too late to swim back to the surface! This seems to be a game bug. The diving helmet does not mention any probability of underwater breathing effect, and I double-checked that there was no breath bar when I dived in, confirming that the helmet was correctly worn. This can be seen in the picture.
I'm an engineering major and had not spent a long time underwater before making this helmet.

Steps to reproduce the behavior with as much detail as possible:

1. I correctly wore the diving helmet before going underwater.
2. I repeatedly confirmed that there was no breath bar for holding breath.
3. After playing underwater for a while, I started losing health directly. Due to the depth of my dive, it was too late when I realized I was losing health.
4. This character is a slow + HC warrior, my fifth character, with the ID 'Zhan Wu Zha' on the Raven County server.
5. I have invested over a month in developing this character. If my character dies due to a bug, it would be very unfair.

![](https://user-images.githubusercontent.com/24437265/281483503-e593307f-e044-4c1e-81ea-446ebd98e1bc.png)

IDs of affected creatures, items, quests, or spells with a link to the relevant page:

NPC: https://database.turtle-wow.org/?npc=none
Item: https://database.turtle-wow.org/?item= I have no idea
Quest: https://database.turtle-wow.org/?quest=none
Spell: https://database.turtle-wow.org/?spell=none
Object: https://database.turtle-wow.org/?object=

Expected behavior. Describe how it should work:
Please check and fix this bug, and revive my character. It's a bug that you can't breathe underwater with a diving helmet! Wearing a diving helmet and going underwater without a breath bar, but starting to lose health when the time is up, is a game bug! My turtle + HC warrior, which I played for over a month, dying due to a bug is too unjust!! Even if it’s due to server lag, I would accept it! If my helmet was not worn properly, there would be a breath bar when I went underwater, but I confirmed there was no breath bar before diving in. When the time was up, the breath bar suddenly appeared empty, and I started losing health! There was no time to react! Please give me an explanation urgently! Also, my several ticket submissions mysteriously disappeared! Please respond to me quickly! Thank you!!

From the screenshot, it is evident that I was correctly wearing the helmet.

![](https://user-images.githubusercontent.com/24437265/281485035-afd22a07-b636-4c81-a516-5bcf6cb4363b.png)

Additionally, after I submitted several tickets to GMs and didn't receive a response, my account was unexpectedly banned for 7 days. I find this unreasonable and request a response from the headquarters!"

![IMG_4532](https://github.com/slowtorta/turtlewow-bug-tracker/assets/24437265/9fd96776-301e-43f5-8f1a-2d2e25f1916e)

**Comment by waffle105** [comment]
my id is waffle105
my character id is 战伍渣

**Comment by ratkosrb** [comment]
Dead hardcore characters are never revived. If you tell me the item id or the item name in english, I can test the helmet in question. There is no item by the name "Diving Helmet", so I don't know what item it is.

**Comment by waffle105** [comment]
![image](https://github.com/slowtorta/turtlewow-bug-tracker/assets/24437265/bf17678e-8049-4844-a7fa-34e1624a08a7)
it's deepdive Helmet


Turtle WoW is indeed a good game, but the operation team in Asia is really not very good——

Even if you can't resolve this bug, you could at least give me an explanation and some consolation!
Even without empathy, there's no need to ban my account!
If you must ban my account, at least give me a reason!
Now, my appeal tickets are also being ignored, and there's nothing unreasonable in my expression. Please make sure to investigate thoroughly. This kind of arbitrary enforcement is damaging the reputation of Turtle WoW.

【So, can you first unfreeze my account? Or at least tell me why my account was frozen.】

My ID is waffle105 in Asia server.

**Comment by AchyllesTurtleWoW** [comment]
have u checked if u had died from exhaustion or drowning?
exhaustion would indeed be the "too deep water" thing and not the "beeing under water for too long".
When reaching into the great ocean theres a darker and deeper water that will slowly but surely make your charakter die ffrom exhaustion over time.

**Comment by ratkosrb** [comment]
I cannot reproduce the issue. I equipped the helmet and stayed underwater for a very long time and I did not drown. You must have died from Fatigue damage, not from drowning.

**Comment by waffle105** [comment]
I made sure I was wearing the helmet correctly, as you can see in the picture. I was doing a master-level fishing mission in a desolate place, and after completing it, I wanted to go underwater (right at the coast) to play with a cage. However, when I finished opening the first one and was about to go to the second one, I started drowning, and I didn't make it to the surface in time.

**Comment by waffle105** [comment]
it's in Desolace,near by Shadowprey Village

**Comment by waffle105** [comment]
please check again.


"My character had 'Show Helm' enabled, which made it easy for me to confirm that I was wearing the correct helmet. Before I went into the water, I even told my friends that I was going to use my new deepdive helmet. They jokingly said, 'Are you sure that helmet doesn't leak?' Well, their joke turned out to be true. 😥"
