### ISSUE TITLE
Horde defender's Axe parchment bug

### ISSUE THREAD

**Issue by Krabator** [slowtorta/turtlewow-bug-tracker#5166]
**Please, provide a clear description what the bug is:**
One I have receive the parchment allonwing me to TP to westfall, I have use it (it has worked) and than I have tp back to Crossroad.
Once in crossroad, i have click on the parchment to tp again... the parchment was on CD... and the game crashed
After some times, the parchment dissappered completly from my inventory, and now I have abandon the quest to reinitialize it but it can't be taken again from NPC in crossroad.

**Steps to reproduce the behavior with as much detail as possible:**

1. doing the "Horde defender's Axe" quest up to the parchment give by NPC
2. click on parchment when it is on CD 
3. game crash
4. after some times, the parchment dissappered completly from my inventory

**IDs of affected creatures, items, quests or spells with a link to the relevant page:**

NPC: https://database.turtle-wow.org/?npc=
Item: https://database.turtle-wow.org/?item=
Quest: https://database.turtle-wow.org/?quest=39998 (or maybe the one before)
Spell: https://database.turtle-wow.org/?spell=
Object: https://database.turtle-wow.org/?object=

**Expected behavior. Describe how it should work:**
I thin k the shit has hit the fan when the parchment has bugged... so i would expect that the parchment does not bug :)

**Comment by AchyllesTurtleWoW** [comment]
u get the quest in Thunderbluff at the portal teacher. not in crossroads. try erasing it from your logg and retaking it in thunderbluff.

**Comment by Krabator** [comment]
ok i have been able to complete the quest but the bug is still here :)
![image](https://github.com/slowtorta/turtlewow-bug-tracker/assets/14138462/d14c9f8d-d6bf-4cac-a7db-715fc9ececd8)

**Comment by twowTurtReynolds** [comment]
@Krabator Please head onto discord and type .crash, make sure you follow all steps there, which I can see that you did not do here in this image.

**Comment by twowTurtReynolds** [comment]
However, seeing now that you are not the only one experiencing this, I suspect it might be a client bug with the 1.17 update. Closing this as duplicate, will be tracked here https://github.com/slowtorta/turtlewow-bug-tracker/issues/4992
