### ISSUE TITLE
Custom Witherbark mobs in custom subzone Ruines of Zul'Rasaz do not reward rep bonuses nor items like their blizzlike namesakes do

### ISSUE THREAD

**Issue by Duranin1989** [slowtorta/turtlewow-bug-tracker#5167]
Normal mobs:
https://database.turtle-wow.org/?npc=91786
https://database.turtle-wow.org/?npc=91784
https://database.turtle-wow.org/?npc=91788
https://database.turtle-wow.org/?npc=91787

Named: https://database.turtle-wow.org/?npc=91790
Elite: https://database.turtle-wow.org/?npc=91789
Rare: https://database.turtle-wow.org/?npc=61502

For comparison, blizzlike:
Normal: https://database.turtle-wow.org/?npc=2653
Rare: https://database.turtle-wow.org/?npc=8216
Elite: https://database.turtle-wow.org/?npc=7996

**Comment by Duranin1989** [comment]
Display ID: 6535
Equipment ID: 55079
https://database.turtle-wow.org/?npc=91786

Display ID: 6508
Equipment ID: 55077
https://database.turtle-wow.org/?npc=91784

Display ID: 4000
Equipment ID: 55081
https://database.turtle-wow.org/?npc=91788

Display ID: 3992
Equipment ID: 55080
https://database.turtle-wow.org/?npc=91787

**Comment by Duranin1989** [comment]
Display ID: 1157
Equipment ID: 0
https://database.turtle-wow.org/?npc=2686

**Comment by hokagegaara** [comment]
Also then not drop https://database.turtle-wow.org/?item=9259

**Comment by twowTurtReynolds** [comment]
Confirmed these do not reward rep and don't drop the token. This does look to be an oversight, I don't see why this shouldn't be added.

These Named NPCs should also be added:
https://database.turtle-wow.org/?npc=91790
https://database.turtle-wow.org/?npc=91789
https://database.turtle-wow.org/?npc=61502

**Comment by Muigin** [comment]
This will be resolved in the next maintenance.
