### ISSUE TITLE
NPC(Vorthos Everbreeze)in Mount Hyjal （Asia serve)has a bug

### ISSUE THREAD

**Issue by fingo5321** [slowtorta/turtlewow-bug-tracker#5168]
NPC(Vorthos Everbreeze)in Mount Hyjal （Asia serve)has a bug

1.There is no Arcanite Rod selling by NPC(Vorthos Everbreeze) in Mount Hyjal.Acoording to the database the amount is ∞.

NPC: https://database.turtle-wow.org/?npc=61525
Item: https://database.turtle-wow.org/?item=16206

**Comment by ratkosrb** [comment]
@slowtorta Do we actually want the npc to sell this item, cause it seems kinda trivial way to obtain it, compared to having to craft it with Arcanite Bars?

**Comment by slowtorta** [comment]
This will be fixed on the next server update.
