### ISSUE TITLE
Guild Charter won't register

### ISSUE THREAD

**Issue by SteveT732** [slowtorta/turtlewow-bug-tracker#517]
**Please, provide a clear description what the bug is:**
I have all the signatures for guild charter, but clicking on option at NPC to register guild does nothing.
**Steps to reproduce the behavior with as much detail as possible:**

1. I made sure every signature is still guildless
2. I went to different cities to try and register guild
3. *can't do anything else to troubleshoot, I am a hardcore mode player though not sure if that matters which it should not*

**IDs of affected creatures, items, quests or spells with a link to the relevant page:**

NPC: https://database.turtle-wow.org/?npc=
Item: https://database.turtle-wow.org/?item=
Quest: https://database.turtle-wow.org/?quest=
Spell: https://database.turtle-wow.org/?spell=
Object: https://database.turtle-wow.org/?object=

**Expected behavior. Describe how it should work:**
I should be able to register my guild, hardcore mode should not prevent that from happening.

**Comment by Tinyfin-github** [comment]
Greetings! Hardcore players can register guilds.

Please move the guild charter to your default bag.

If the issue persists open an in game ticket  for GM assitance
