### ISSUE TITLE
附魔bug

### ISSUE THREAD

**Issue by AOshandamowang** [slowtorta/turtlewow-bug-tracker#5170]
血环服务器 部落 亡灵法师 卷王 护腕附魔12法伤 无效果！请GM尽快给我解决，已经好多天了，

**Comment by twowTurtReynolds** [comment]
请用英文提交问题。我们无法通过自动翻译准确地翻译中文提交的错误报告，这使得我们难以理解问题的确切性质。谢谢！

Please submit the issues in English. We're unable to accurately translate bug reports submitted in Chinese through automatic translation, which makes it difficult for us to understand the exact nature of the issue. Thank you!
