### ISSUE TITLE
The  Incendosaur Skin Set does not trigger Paladin's Vengeance Talent

### ISSUE THREAD

**Issue by simonfloy** [slowtorta/turtlewow-bug-tracker#5171]
**Please, provide a clear description what the bug is:**
The Incendosaur Skin Set does not trigger Paladin's Vengeance Talent
**Steps to reproduce the behavior with as much detail as possible:**

1.Equipped with Incendosaur Skin Gloves and Boots of Burning Dragon Skin.
2. Attacks the target and three flame damage numbers appear
3. Can't trigger paladin's vengeance talent on fire damage killing blow
4. When wearing the suit, there are a total of 3 flame attack damage, 1 of which failed to trigger the vengeance of the fatal blow, after testing, in the unloading of the suit alone wearing gloves or shoes when the vengeance triggered normal!
5. Vengeance cannot be triggered on the 2 extra points of flame damage lethal strike provided by the Incendosaur Skin set, and is triggered normally on the flame damage lethal strike provided by the equipment itself.
**IDs of affected creatures, items, quests or spells with a link to the relevant page:**

NPC: https://database.turtle-wow.org/?npc=
Item: https://database.turtle-wow.org/?item=60582
         https://database.turtle-wow.org/?item=60568

Quest: https://database.turtle-wow.org/?quest=
Spell: https://database.turtle-wow.org/?spell=
Object: https://database.turtle-wow.org/?object=

**Expected behavior. Describe how it should work:**
The additional Flame Strike damage provided by the Incendosaur Skin set effect should trigger Vengeance in the paladin talent on the fatal blow

**Comment by ratkosrb** [comment]
The effect on the gloves and on the 2 piece set bonus is the same. So if 1 can trigger it so can the other.
https://database.turtle-wow.org/?spell=7711

**Comment by simonfloy** [comment]
> 对手套和 2 件套奖励的影响是一样的。因此，如果一个可以触发它，那么另一个也可以。 https://database.turtle-wow.org/?spell=7711

Yes, he was originally supposed to work like that, but from time to time in combat I noticed that I didn't get the Vengeance talent when Flame Damage Fatal Strike was applied, so I tested it by attacking the stake in the main city, and there was no Flame Damage Fatal Strike not triggering Vengeance when wearing one piece of gear, but the bug of not triggering Vengeance reappeared when I wore 2 parts of the set to get the set effect, so I'm assuming that it's the Flame Damage provided by the set that's not triggering Vengeance

**Comment by ratkosrb** [comment]
It will be fixed after the next update.

**Comment by ratkosrb** [comment]
Update: It will not be fixed. It has been decided to keep it like it is, and not have item set bonuses able to proc things. Don't report it as a bug again, it is intentional behavior.

**Comment by Niqlo** [comment]
oh boy you get a whole 2 damage than! what's the point of the set bonus if it doesn't proc anything that's the whole reason people use these items
