### ISSUE TITLE
Warleader Temukar can't be interacted with (for quests); can also attack friendly/honored Gelkis NPC's

### ISSUE THREAD

**Issue by pumear** [slowtorta/turtlewow-bug-tracker#5172]
**Please, provide a clear description what the bug is:**
After the most recent server restart, November 10, I could no longer interact with the Gelkis' quartermaster or quest giver, even at friendly or honored reputation with Gelkis. The game was also allowing me to attack the friendly Gelkis NPC's. This issue was happening to the 4 other players in the area at the time.

**Steps to reproduce the behavior with as much detail as possible:**

1. Be friendly or honored with Gelkis
2. Try to talk to the Gelkis quartermaster or quest givers, or any other interactable Gelkis NPC
3. Try to attack friendly/honored Gelkis NPC's

**IDs of affected creatures, items, quests or spells with a link to the relevant page:**

NPC: https://database.turtle-wow.org/?npc=80941
NPC: https://database.turtle-wow.org/?npc=61045
NPC: https://database.turtle-wow.org/?npc=4648
Quest: https://database.turtle-wow.org/?quest=40630

**Expected behavior. Describe how it should work:**
A player with friendly or honored should not be allowed to attack Gelkis NPC's, and the player should also be able to interact with quest givers and the quartermaster (if honored or higher).

**Comment by ratkosrb** [comment]
I can't reproduce the issue. Make sure you haven't clicked "At War" in the reputation tab.
![Untitled](https://github.com/slowtorta/turtlewow-bug-tracker/assets/35845488/4d10afa2-45ee-4572-b1db-e6d107d0ad85)


![Untitled](https://github.com/slowtorta/turtlewow-bug-tracker/assets/35845488/5d1148ed-16ac-4090-933c-6fdb20106c73)

**Comment by AchyllesTurtleWoW** [comment]
Press K - Check your Gelkis Reputation by leftclickting it.   UNCHECK THE BOX THAT SAYS "AT WAR".

always glad i can help,

**Comment by pumear** [comment]
i feel so stupid.. THANK YOU
