### ISSUE TITLE
Deadwood Headdress Feather does not drop

### ISSUE THREAD

**Issue by Snow22** [slowtorta/turtlewow-bug-tracker#5175]
Deadwood Headdress Feather does not drop. Did the pre quest to unlock the hand in. Did it in a party and solo. Re logged. deleted folders, logged back in, did it solo and a party, still can't loot them. I can loot a mob that drops it and not see the feather but a party member can still see the feather and loot it. So the bug seems to be the flag for being able to see / loot the feathers isn't activating. I attempted to explain this to a gm but there may have been a language barrier. Even after manually adding the quest to my log, normally the feather hand in cant be added to your quest log, the feathers still wouldn't drop.
Just listed 3 npcs below but its all deadwood furbolgs.

**Steps to reproduce the behavior with as much detail as possible:**

1. Kill deadwood furbolgs that drop feathers.
2. Unable to see or loot feathers.

(https://database.turtle-wow.org/?npc=7158)
https://database.turtle-wow.org/?npc=7156
https://database.turtle-wow.org/?npc=7157
(https://database.turtle-wow.org/?item=21377)
https://database.turtle-wow.org/?quest=8467

**Comment by ratkosrb** [comment]
In order to loot the item you must have completed one of these 2 quests.
https://database.turtle-wow.org/?quest=6131
https://database.turtle-wow.org/?quest=8460
Also you should not be in a raid group. Quest items cant be looted in raids unless its a raid quest.

**Comment by Snow22** [comment]
I was looking at wrong pre quest requirement from the old classic wow database. ty!
