### ISSUE TITLE
Cloak of the dark veil doesn't drop

### ISSUE THREAD

**Issue by Skaryna3** [slowtorta/turtlewow-bug-tracker#5177]
I had like 60 runs and no cloak. Another rogue had like 200+ runs and no cloak, all the others also couldn't get it.
It is supposed to drop with a 5% chance. Something's not right.

https://database.turtle-wow.org/?item=61334

**Comment by twowTurtReynolds** [comment]
![image-e8hijypzqbg3xcyhqe1g33rnjy](https://github.com/slowtorta/turtlewow-bug-tracker/assets/151180101/2de6468f-9049-481f-850c-0d58cbd397b7)
Confirmed dropping. Now you just have to be lucky :)

**Comment by Skaryna3** [comment]
Thank you!
