### ISSUE TITLE
Flight bug Rutheran (probably due to new FP in Stonetalon)?

### ISSUE THREAD

**Issue by Sty0pa1** [slowtorta/turtlewow-bug-tracker#5178]
**Please, provide a clear description what the bug is:**
Was flying from Rutheran fp to Bael Hardul fp
Stepped away from computer
Came back, character was sitting on griffon just short of the Ashenvale fp, facing east.  The griffon was on the ground, and I could move around at walking speed, was not flying, could not use abilities, went into buildings was not dismounted.
There was no mount icon, so I couldn't manually dismount
Tried to /reloadui, but came back in same state.
Logged out to charselect, re-entered, and I was immediately flying as if I'd just left the Ashenvale FP.

**Steps to reproduce the behavior with as much detail as possible:**

1. Fly from Rutheran
2.  Select Bael Hardul as destination
3. 

**IDs of affected creatures, items, quests or spells with a link to the relevant page:**

NPC: https://database.turtle-wow.org/?npc=
Item: https://database.turtle-wow.org/?item=
Quest: https://database.turtle-wow.org/?quest=
Spell: https://database.turtle-wow.org/?spell=
Object: https://database.turtle-wow.org/?object=

**Expected behavior. Describe how it should work:**
I'd expect to fly past ashenvale and end at Bael Hardun.

**Comment by twowTurtReynolds** [comment]
Closing as dupe https://github.com/slowtorta/turtlewow-bug-tracker/issues/4619
