### ISSUE TITLE
Cant loot quest item

### ISSUE THREAD

**Issue by henjoh84** [slowtorta/turtlewow-bug-tracker#518]
Cant loot the gatekeepers key from the lantern for this quest.
https://database.turtle-wow.org/?quest=1089

**Comment by Tinyfin-github** [comment]
Greetings! I have unchecked and i have been unable to find any issue with the quest.

Please disable Addons and clear your WDB folder while the game is closed and try to complete the quest again.

https://user-images.githubusercontent.com/83077166/145668778-7c91990d-7d11-4d9f-9c69-41ce3056cd61.mp4
