### ISSUE TITLE
Missing NPCs in Dustwallow Marsh/Desolace and all their related quests

### ISSUE THREAD

**Issue by Lichbanez** [slowtorta/turtlewow-bug-tracker#5181]
The following NPCs are currently missing: Mikoto Shiina, Shizuru Yamada, Haruhiko Yoshino, Yasu Ping and Dae-woong Kim

1. Explore every inch of the map
2. Realize their camps are empty

https://database.turtle-wow.org/?npc=61410 
https://database.turtle-wow.org/?npc=61414
https://database.turtle-wow.org/?npc=61411
https://database.turtle-wow.org/?npc=61413
https://database.turtle-wow.org/?npc=61412

These NPC and their related quests should be in the game as suggested by the database.

**Comment by Muigin** [comment]
These NPCs and their related quests were removed deliberately by the Narrative Team for 1.17.0.  This content is deprecated, and is thus no longer available.
