### ISSUE TITLE
Goblin Brain Washing Device

### ISSUE THREAD

**Issue by favoriteuncle** [slowtorta/turtlewow-bug-tracker#5182]
**Please, provide a clear description what the bug is:**
Good Morning. I have a lvl 25 toon attempting to buy the Goblin Brain Washing Device from Vizlow at Gurubashi Arena. Unfortunately, the only option available with Vizlow is donating #5 Tokens of Blood. 
**Steps to reproduce the behavior with as much detail as possible:**

1.
2. 
3. 

**IDs of affected creatures, items, quests or spells with a link to the relevant page:**

NPC: https://database.turtle-wow.org/?npc=
Item: https://database.turtle-wow.org/?item=
Quest: https://database.turtle-wow.org/?quest=
Spell: https://database.turtle-wow.org/?spell=
Object: https://database.turtle-wow.org/?object=

**Expected behavior. Describe how it should work:**

**Comment by favoriteuncle** [comment]
Bbqribs is the lvl 25 shaman toon

**Comment by Muigin** [comment]
https://database.turtle-wow.org/?quest=39000
The quest has a minimum requirement of level 50.  This is working as intended.
However, given that the item only requires level 10 and can also be donated for, I will put this to the rest of the team and see about lowering the minimum level to 10 for the quest.
