### ISSUE TITLE
<SHIFT> + <CLICK> on player's name works only once

### ISSUE THREAD

**Issue by Gasan918** [slowtorta/turtlewow-bug-tracker#5184]
**Please, provide a clear description what the bug is:**

If you SHIFT and CLICK on player's name in chat you get player's info only once. If you SHIFT and CLICK again (on this or on any other player's name) you got no info this time. SHIFT and CLICK start working again after 15 minutes or so. And only once, again.

**Steps to reproduce the behavior with as much detail as possible:**

1. Shift and Click in name in chat. Get player's info
2. Shift and Click on other name again. And you get no info now

*Expected behavior. Describe how it should work:**

Shift and Click must work always.

**Comment by cyaohiri** [comment]
Shift clicking on a player's name does the same thing as `/who NAME`, which has a 30 second cooldown.

**Comment by Gasan918** [comment]
OK close it pls

**Comment by AkalixFrost** [comment]
Working as intended as described by cyaohiri.
