### ISSUE TITLE
windtalker cape dont have res nature stat

### ISSUE THREAD

**Issue by masmas1337** [slowtorta/turtlewow-bug-tracker#5185]
**Please, provide a clear description what the bug is:**

https://database.turtle-wow.org/?item=61709

windtalker cape should have +10 res nature, as listed in the database, but in game it has none on the description and no res nature added when equipped

**Steps to reproduce the behavior with as much detail as possible:**

1.
2. 
3. 

**IDs of affected creatures, items, quests or spells with a link to the relevant page:**

NPC: https://database.turtle-wow.org/?npc=
Item: https://database.turtle-wow.org/?item=
Quest: https://database.turtle-wow.org/?quest=
Spell: https://database.turtle-wow.org/?spell=
Object: https://database.turtle-wow.org/?object=

**Expected behavior. Describe how it should work:**

**Comment by ratkosrb** [comment]
Update: This was reverted and the item will stay without the resistance bonus. I'm sorry.
