### ISSUE TITLE
Thornpod Deletion

### ISSUE THREAD

**Issue by afizzler** [slowtorta/turtlewow-bug-tracker#5188]
It should not be deleted from people's inventories. 

Thornpod: https://database.turtle-wow.org/?item=80757

**Comment by ratkosrb** [comment]
The id of this item was changed to 62008, but it was forgotten to run a character db migration that i had prepared to update the item in player's inventory during the server update, so that is why it disappeared. I cannot restore it for you. Try opening a ticket and asking a GM.

**Comment by twowTurtReynolds** [comment]
Indeed, anyone who lost their Thornpod due to this bug, please contact a GM.
