### ISSUE TITLE
Tome of Valor - Quest bug

### ISSUE THREAD

**Issue by Jonathan-Pires** [slowtorta/turtlewow-bug-tracker#5193]
**Please, provide a clear description what the bug is:**

**Steps to reproduce the behavior with as much detail as possible:**

1. Failed Tome of Valor, Tried resetting the quest which did not work
2. Tried Abandoning the quest, so I could pick it up again from Duthorian Rall (Quest Giver from Cathedral of Light) and start it again, that did not work either (still a grey " ! " symbol above his head) 
3. Tried picking it up again from the item Tome of Valor itself, that also did not work bc I get a message stating "you are already on that quest" Which is not true since I no longer have the quest in my quest log either. 

**IDs of affected creatures, items, quests or spells with a link to the relevant page:**

NPC: https://database.turtle-wow.org/?npc=
Item: https://database.turtle-wow.org/?item=
Quest: https://database.turtle-wow.org/?quest=
Spell: https://database.turtle-wow.org/?spell=
Object: https://database.turtle-wow.org/?object=

**Expected behavior. Describe how it should work:**

**Comment by twowTurtReynolds** [comment]
@Jonathan-Pires  I'm guessing you figured the problem out?
