### ISSUE TITLE
Hunter Leaf Quest

### ISSUE THREAD

**Issue by Deepdean** [slowtorta/turtlewow-bug-tracker#5195]
**Please, provide a clear description what the bug is:**
While doing the Leaf quest - I start attacking Klinfran the Crazed and after 2sec he transforms in 'The Cleaner'
**Steps to reproduce the behavior with as much detail as possible:**

1.Talk to Franklin the Friendly
2. Attack Klinfran the Crazed. After 2-3sec, he transforms into 'The Cleaner', who's immune to everything.
3. Get killed by 'The Cleaner'

https://streamable.com/ev0tjx

**IDs of affected creatures, items, quests or spells with a link to the relevant page:**

NPC: https://database.turtle-wow.org/?npc=9018
Item: https://database.turtle-wow.org/?item=31148
Quest: https://database.turtle-wow.org/?quest=59700
Spell: https://database.turtle-wow.org/?spell=
Object: https://database.turtle-wow.org/?object=

**Expected behavior. Describe how it should work:**
Klinfran the Crazed shouldn't transform into The Cleaner

**Comment by Gutschy89** [comment]
Hi you are not allowed to use your pet to do the quest. Just dismiss your pet and the cleaner will no more transform into The Cleaner.
