### ISSUE TITLE
but cannot catch a new pet

### ISSUE THREAD

**Issue by nuncaut** [slowtorta/turtlewow-bug-tracker#5197]
**Please, provide a clear description what the bug is:**

**Steps to reproduce the behavior with as much detail as possible:**
![Schermafbeelding 2023-11-13 120920](https://github.com/slowtorta/turtlewow-bug-tracker/assets/34606371/9f0f980d-1bba-4810-ab66-22edf43c52e0)

I am working on a quest for the hunter to catch an animal, this went well until I was able to get on a fly mount for 30 seconds.
Now the pet is gone when I try to catch a new one, this is no longer possible, even if I do the Quest again, I get the Quest item but cannot catch a new pet

**IDs of affected creatures, items, quests or spells with a link to the relevant page:**

NPC: https://database.turtle-wow.org/?npc=113
Item: https://database.turtle-wow.org/?item=15921
Quest: https://database.turtle-wow.org/?quest=6063

**Comment by ratkosrb** [comment]
As the item description says, this Taming Rod is for catching a "Prowler" and you are targeting a "Boar". Those are different animals.
