### ISSUE TITLE
Shaman fire totem quest HC 

### ISSUE THREAD

**Issue by wowchevywarmane** [slowtorta/turtlewow-bug-tracker#5198]
I have done a quest for  Sham Fire Totem but i still got it in my quest list and i catn't pass it .
Attaching screenshots.

![WoWScrnShot_111323_141403](https://github.com/slowtorta/turtlewow-bug-tracker/assets/150673704/cf37a31f-ef41-47df-b691-4e0855fa2332)
![WoWScrnShot_111323_140246](https://github.com/slowtorta/turtlewow-bug-tracker/assets/150673704/d72cc742-ad86-4816-b565-6b1e600da6d4)

**Comment by wowchevywarmane** [comment]
![Uploading WoWScrnShot_111323_141315.png…]()

**Comment by roguestep16** [comment]
ehm turn it in in Barrens? not in Durotar? lol

**Comment by twowTurtReynolds** [comment]
You are on part 5 https://www.wowhead.com/classic/quest=1527/call-of-fire which takes you back to the barrens. Go there :)
