### ISSUE TITLE
Poison Water

### ISSUE THREAD

**Issue by Pangoken** [slowtorta/turtlewow-bug-tracker#52]
By opening this Issue, I admit to having done the pertinent research using sources from Vanilla (preferably) or Classic. I also understand that sources from other private servers are not acceptable.

**Current behavior**: 
The quest Poison Water is available to every race.

**Expected behavior**: 
The quest Poison Water is available to tauren only.

**Proofs**:
https://classic.wowhead.com/quest=748/poison-water
![renwu](https://user-images.githubusercontent.com/50700937/121983043-f1c2eb00-cd90-11eb-83b6-1558bf0fd447.png)

**Steps to reproduce**:

1. Interact with Mull Thunderhorn

**Comment by slowtorta** [comment]
Thanks for reporting it. It's fixed and will be deployed on the next server update.
