### ISSUE TITLE
Turtle meat in Southshore 

### ISSUE THREAD

**Issue by xelitox** [slowtorta/turtlewow-bug-tracker#5201]
**Please, provide a clear description what the bug is:**

**Steps to reproduce the behavior with as much detail as possible:**

1.Soothing Turtle Bisque quest 
2. The snapjaw quest turtle mobs are are not dropping the turtle meat as quest intended, but dropping clams shells that opens up tangy clam meat. i have almost killed 50 and recieved 0 turtle meat. 
3. 

**IDs of affected creatures, items, quests or spells with a link to the relevant page:**

NPC: https://database.turtle-wow.org/?npc=
Item: https://database.turtle-wow.org/?item=
Quest: https://database.turtle-wow.org/?quest=
Spell: https://database.turtle-wow.org/?spell=
Object: https://database.turtle-wow.org/?object=

**Expected behavior. Describe how it should work:**

**Comment by ratkosrb** [comment]
You must be killing the wrong mobs. Please link the npc from the database which you would like to drop the item.

**Comment by AkalixFrost** [comment]
https://database.turtle-wow.org/?item=3712#dropped-by:0+1-7 is the required item

**Comment by twowTurtReynolds** [comment]
@xelitox we may close this soon if you do not clarify.

**Comment by mikefirefly** [comment]
I killed over 10 Snapjaws in the Southshore river today - received zero meat drops.

**Comment by twowTurtReynolds** [comment]
I'll hop on the PTR and see whats the deal here.

**Comment by twowTurtReynolds** [comment]
![image](https://github.com/slowtorta/turtlewow-bug-tracker/assets/151180101/a13f6185-e3c1-47e4-8251-cdf3eebbae35)
I killed 3 of these guys and 1, 0, and 2 pieces respectively

Unless you can further clarify what you are experiencing, this looks to be working correctly.
