### ISSUE TITLE
Honor statistic error

### ISSUE THREAD

**Issue by kongccc** [slowtorta/turtlewow-bug-tracker#5202]
GM Hello, I am a loyal player in turtle suit, to reflect to you on the honor of a statistical error. My account fengchen3669 character name stefan Blood Ring Server, tribal thieves. Between October 25th and November 1st, during this CD period, I hit over 320,000 with honors. When I settled on Wednesday, November 1st, it showed that I had 161241 honors last week, less than 160,000 honors (screenshots of all the above) . On November 1, I told GM in-game that there was a problem with honor. GM emailed me back in-game saying, “The server wasn't offline when it was updated. I'll make it up next time.” On November 2, after the server was updated, I was awarded 164868 Honours, which were later deducted when the server was rebooted. Playing more than 160,000 honors a week, and playing online for an average of 10 hours a day. As an individual player, I have put in a lot of effort, and it is not easy to ask GM to add 160,000 honors to my account. Thank you very much, i sincerely wish the turtle suit better and better. I have screenshots of all of the above and can provide them if needed.

**Comment by kongccc** [comment]
![947ece5a94af653e4cd96f452d729fe](https://github.com/slowtorta/turtlewow-bug-tracker/assets/46598392/263ee3b1-ea0f-4184-ab20-12df6c9e0a57)
![7a4ed0e26c81d710dbb579b08d7559c](https://github.com/slowtorta/turtlewow-bug-tracker/assets/46598392/40a63b4e-1a22-46e6-8a29-4b9ee23d679a)

**Comment by twowTurtReynolds** [comment]
The team has done a deep dive and confirmed honor calculations to be working correctly.
