### ISSUE TITLE
Rich thorium veins in dire maul east no longer drop arcane crystals

### ISSUE THREAD

**Issue by Icfre** [slowtorta/turtlewow-bug-tracker#5203]
**Please, provide a clear description what the bug is:**
The rich thorium veins in dire maul east no longer drop arcane crystals

**Steps to reproduce the behavior with as much detail as possible:**

1. Clear dire maul east
2. Mine rich thorium veins
3. Repeat 20 times and never get an arcane crystal

**IDs of affected creatures, items, quests or spells with a link to the relevant page:**

NPC: https://database.turtle-wow.org/?npc=
Item: https://database.turtle-wow.org/?item=
Quest: https://database.turtle-wow.org/?quest=
Spell: https://database.turtle-wow.org/?spell=
Object: https://database.turtle-wow.org/?object=

**Expected behavior. Describe how it should work:** - I would expect rich thorium veins to drop at least one arcane crystal in 20 runs of dire maul east

**Comment by Muigin** [comment]
https://i.imgur.com/KiAoQlK.jpeg

Cannot reproduce.
