### ISSUE TITLE
冲破牢笼任务无法完成

### ISSUE THREAD

**Issue by a779631982** [slowtorta/turtlewow-bug-tracker#5208]
黑龙门系列任务任务《冲破牢笼》元帅离开副本后任务显示未完成，无法提交任务。

**Comment by Muigin** [comment]
请用英文提交问题。我们无法通过自动翻译准确地翻译中文提交的错误报告，这使得我们难以理解问题的确切性质。谢谢！

Please submit the issues in English. We're unable to accurately translate bug reports submitted in Chinese through automatic translation, which makes it difficult for us to understand the exact nature of the issue. Thank you!
