### ISSUE TITLE
Goblin Brainwashing Device Bug?

### ISSUE THREAD

**Issue by Grimortron** [slowtorta/turtlewow-bug-tracker#5210]
**Please, provide a clear description what the bug is:**
Goblin Brainwashing Device Reset?
**Steps to reproduce the behavior with as much detail as possible:**

1. I logged in and saw my device was reset, I created my Combat specialization build on Primary Talents.
2. Tried to Activate empty Secondary Build but it would not let me.
3. Accidentally saved Primary Talent Build (Combat) onto my Secondary as well. 

**IDs of affected creatures, items, quests or spells with a link to the relevant page:**

Item: https://database.turtle-wow.org/?item=51715

**Expected behavior. Describe how it should work:**
From my previous experience and what I understand, it should allow me to set up a second talent build without requiring a full reset of my talents with gold, which I unfortunately do not have right now. Is it possible for this to be fixed or was this intention? I just don't have the gold to reset my talents again to fix it this time and I really need my Subtlety talent build to actually make gold for my character.

**Comment by Muigin** [comment]
This has been fixed as of today's maintenance.
