### ISSUE TITLE
+75 Armor Penetration enchant BUG

### ISSUE THREAD

**Issue by Mcfury777** [slowtorta/turtlewow-bug-tracker#5211]
I put +75 Armor Penetration on my Bloodsoaked Paulrons shoulder but i have only +40?
I clear my WBD folder and i put again this Enchant but i still have + 40? Can fix pls? Can return my gold pls? :) Sry for my bad eng.
![+75 BUG](https://github.com/slowtorta/turtlewow-bug-tracker/assets/150521647/bcc376c1-6f5a-4f42-94c1-2283591fc317)

**Comment by Sringaram** [comment]
Not a bug, all ARP was halved globally.

**Comment by Mcfury777** [comment]
Ok, can you rename all enchants description soon?

**Comment by Muigin** [comment]
This requires a client patch, and will be resolved in 1.17.1.
