### ISSUE TITLE
Cannot create a guild bank

### ISSUE THREAD

**Issue by SuqMadiqM8** [slowtorta/turtlewow-bug-tracker#5213]
**Please, provide a clear description what the bug is:**

I'm trying to create a guild bank but the game wont let me. If I try to talk to 'Are' Guild Vault Keeper in Orgrimmar he turns to me and instantly turns away again. This can be fixed by rapidly right-clicking him between 15-30 times. He then brings up the dialogue window but all that shows is 'Greetings, Myname'. No options to create a guild bank. 

The toon is a hc lvl 59 goblin if that matters. I am the guildmaster and I have the necessary 2k gold on me.

**Steps to reproduce the behavior with as much detail as possible:**

1. Be a hc toon, be a goblin, be the guildmaster.
2. Right-click Are the Guild Vault Keeper in Orgrimmar.
3. Get only one line of dialogue and no options to create the guild bank.

**Expected behavior. Describe how it should work:**

Should be able to create a guild bank. When I talked to Are with a non-hc toon guildmaster, he had the option to open the guild bank (I dont have 2k gold in non-hc, so that's not a solution)

Edit: Tried disabling addons, deleting wdb folder, none helped.

**Comment by SuqMadiqM8** [comment]
Same thing with a 59 hc nightelf in Stormwind while attempting to create a guild bank at Teller Plushner.

**Comment by twowTurtReynolds** [comment]
Guild bank access would defeat the 1-59 hardcore rule of restricted trading by level. Once you obtain Inferno mode, or you ding 60 for immortal mode, you will be able to use and purchase gbanks again.

Not a bug.
