### ISSUE TITLE
Automatical Loot given to Masterlooter on Majordomo Loot Chest

### ISSUE THREAD

**Issue by juicywow** [slowtorta/turtlewow-bug-tracker#5214]
**Please, provide a clear description what the bug is:**

**Steps to reproduce the behavior with as much detail as possible:**

1. Kill Boss
2.  Masterlooter opens the Chest (with Autoloot on)
3.  Loot was instantly in the bag (Pressed decline on the prompt)
4. Could trade the item bag.

**IDs of affected creatures, items, quests or spells with a link to the relevant page:**

NPC: https://database.turtle-wow.org/?npc=12018
Item: https://database.turtle-wow.org/?item=18646
Quest: https://database.turtle-wow.org/?quest=
Spell: https://database.turtle-wow.org/?spell=
Object: https://database.turtle-wow.org/?object=

**Expected behavior. Describe how it should work:**
It should not instantly go to the master looters bag. Neither should it still go when pressing "decline"

**Comment by twowTurtReynolds** [comment]
Autoloot is only present in the game for two reasons:
1. You held Shift when looting
2. You used the vanilla-tweaks hack to make it happen automatically and not require shift
Which type of autoloot was this?

**Comment by twowTurtReynolds** [comment]
I'll mark this closed until replication steps are provided.
