### ISSUE TITLE
Rare enemy - M-0L1Y <Weather Tracking Unit> - no assigned loot drops

### ISSUE THREAD

**Issue by mrkajito** [slowtorta/turtlewow-bug-tracker#5217]
**Please, provide a clear description what the bug is:**

The rare enemy M-OL1 Y at Icepoint Rock doesn't have any assigned drops other than a few silver coins.

**Steps to reproduce the behavior with as much detail as possible:**

1. Go to Icepoint Rock
2. Kill M-0L1Y <Weather Tracking Unit>
3. No loot except silver coins
4. Be sad

**IDs of affected creatures, items, quests or spells with a link to the relevant page:**

NPC: https://database.turtle-wow.org/?npc=](https://database.turtle-wow.org/?npc=61498

**Expected behavior. Describe how it should work:**
ItemDrops as expected from rare enemies.

**Comment by mrkajito** [comment]
Also: Respawn rate of the enemy is unexpected low - around 5 minutes.

**Comment by Dragunovi** [comment]
Both respawn timer and loot should be fixed with the next restart, she should now have four new drops.
