### ISSUE TITLE
Warlock pet issue

### ISSUE THREAD

**Issue by K3skin** [slowtorta/turtlewow-bug-tracker#5218]
After the last reset my voidwalkers name was changed and all the skills are gone. I checked it for all my other pets but its only my voidwalker. So all the latest skills that my pet had are gone. My characters name is  ghull in tel'abim

**Comment by twowTurtReynolds** [comment]
It seems you are the only player who experienced this, and nobody else is reproducing. I assume you have gotten with a GM or taken a hit on your own gold to retrain the pet.

Let us know here if it happens again, and if anything you did was out of the ordinary that might have triggered this.

**Comment by twowTurtReynolds** [comment]
Turns out, it was likely this bug: https://github.com/slowtorta/turtlewow-bug-tracker/issues/3871
