### ISSUE TITLE
Striders don't flee

### ISSUE THREAD

**Issue by geojak** [slowtorta/turtlewow-bug-tracker#522]
**Please, provide a clear description what the bug is:**

The strider fledglings in dark shore are supposed to flee on low hp. Possibly barren strider too. 

**Steps to reproduce the behavior with as much detail as possible:**

1. Attack a strider in dsekshore
2.  Bring it to low hp
3. It does not attempt to flee

**IDs of affected creatures, items, quests or spells with a link to the relevant page:**

NPC: https://database.turtle-wow.org/?npc=
Item: https://database.turtle-wow.org/?item=
Quest: https://database.turtle-wow.org/?quest=
Spell: https://database.turtle-wow.org/?spell=
Object: https://database.turtle-wow.org/?object=

**Expected behavior. Describe how it should work:**

Striders in dark shore should flew on low hp

**Comment by slowtorta** [comment]
Please stop making reports wtihout a single creature/item or spell ID in them.

**Comment by geojak** [comment]
Alright, I will put the id next time instead of just naming the npc name and location in the future

**Comment by geojak** [comment]
If you happen to come across and old issue of mine without ids, then pls just comment there, I will try to fix the missing ids in a day.
