### ISSUE TITLE
Gilneas Naga don't chase

### ISSUE THREAD

**Issue by MidnightPulses** [slowtorta/turtlewow-bug-tracker#5220]
**Please, provide a clear description what the bug is:**

When pulling the Naga mobs along the Gilneas coast, they have a tendency to not run after you and instead stay put while keeping you in combat indefinitely. Not always, but definitely noticeable enough.

**Steps to reproduce the behavior with as much detail as possible:**

It mostly happens while body pulling. Run up to their aggro range, and once in combat, if you try to run to another one, the first one has a fairly high chance that it will not follow you.

**IDs of affected creatures, items, quests or spells with a link to the relevant page:**

NPC: 
https://database.turtle-wow.org/?npc=61408
https://database.turtle-wow.org/?npc=61407

I have only confirmed it on those two for now

**Expected behavior. Describe how it should work:**

Like any other mob, if you engage in combat with it, it should be chasing after you until the end of its' leash range.

**Comment by twowTurtReynolds** [comment]
Are they evading when they are stuck unable to follow? Sounds like modeling -> mmap issues.

**Comment by twowTurtReynolds** [comment]
I aggroed every netter on the west side. All of them pathed correctly. If you are still reproducing this, Show me a pic of your map where you are and which one is doing it.
