### ISSUE TITLE
pseudo random code problem

### ISSUE THREAD

**Issue by Gemso** [slowtorta/turtlewow-bug-tracker#5224]
**Please, provide a clear description what the bug is:**
 I have tried more than 30 times to get [Shadowcraft Pants] through defeat Baron Rivendare in Stratholme In the past two days.  
Just no one [Shadowcraft Pants] but many other class's pant.  In probability view,  11% drop ratio（quote by turtle database）represent just 0.0303% (0.89^30) non-drop probability in 30 consecutive times, but It's happended.  I always observe that one class T0 pant continuous occurrence 3 time.  dose any pseudo random code bugged?  30 times !  i don't believe it is just unlucky

**Steps to reproduce the behavior with as much detail as possible:**

1. more than 30 times non-drop  [Shadowcraft Pants]  but  all another class's pant
2. always observe that one class T0 pant continuous occurrence 3 time， it dose not obey uniform distribution 

**IDs of affected creatures, items, quests or spells with a link to the relevant page:**
Item: https://database.turtle-wow.org/?item=16709
Quest: https://database.turtle-wow.org/?quest=9020

**Expected behavior. Describe how it should work:**
drop ratio should obey uniform distribution

**Comment by Muigin** [comment]
1.  Computer RNG is not Theoretical Probability
2.  Your sample size is far too small.  The drop rates listed in the pants drop group on the database is accurate.  If you would like test this properly, you would need a much larger sample size.

Working as intended.

**Comment by Gemso** [comment]
> 1. Computer RNG is not Theoretical Probability
> 2. Your sample size is far too small.  The drop rates listed in the pants drop group on the database is accurate.  If you would like to test this properly, you would need a much larger sample size.
> 
> Working as intended.

 much larger sample size？ so how many sample size you can admit?
