### ISSUE TITLE
Beastmaster's Gloves have wrong stats

### ISSUE THREAD

**Issue by Manaci** [slowtorta/turtlewow-bug-tracker#5225]
So this is how the Beastmaster's Gloves currently look
![Screenshot 2023-11-15 180913](https://github.com/slowtorta/turtlewow-bug-tracker/assets/26745981/be7b47f7-bf2a-4d8a-b225-15bc451e9b56)

This is how a normal pair of Beastmaster's Gloves should look on a non-custom server
![Screenshot 2023-11-15 180625](https://github.com/slowtorta/turtlewow-bug-tracker/assets/26745981/1b9eea49-caa5-46ba-8c00-afec7e7ff400)

In the **[Midpatch Itemization Changes Changelog](https://forum.turtle-wow.org/viewtopic.php?t=10971)** the change described for these gloves were "Beastmaster's Gloves: Added 1% Hit" which has happened....but the effect is "USE" not "EQUIP" = it's not working and gives no hit %. Furthermore, the old [2% pet crit effect](https://database.turtle-wow.org/?spell=27043) is also missing when it should be there along with the "EQUIP" 1% crit effect. Seems like a very easy thing to fix and would be appreciated cause currently these gloves have become pretty nerfed when the update was supposed to buff them a month ago.

**Comment by Zebouski** [comment]
dup of https://github.com/slowtorta/turtlewow-bug-tracker/issues/4893 but indeed doesn't look like that fix went through

**Comment by Dragunovi** [comment]
The fix is on its way to a scheduled restart near you.

**Comment by Manaci** [comment]
![Screenshot 2023-11-22 020624](https://github.com/slowtorta/turtlewow-bug-tracker/assets/26745981/6193ba12-7e08-41c4-b77e-ad42fb3c7cf2)

Well the pet crit effect is back after server restart....but hit effect is still the bugged "Use:" and not "Equip:" as it should

**Comment by twowTurtReynolds** [comment]
Confirmed. Please mention that you have cleared WDB as I have.

**Comment by Muigin** [comment]
I've pushed a fix, and this should be cleared up on the next Tuesday maintenance. At that time, please delete your cache (WDB folder).

**Comment by Manaci** [comment]
@Muigin The 1% Hit is still a bugged "Use:" effect instead of the normal "Equip:" effect after weekly restart once again, did the fix not apply? (Yes I deleted my WDB)

**Comment by twowTurtReynolds** [comment]
![image](https://github.com/slowtorta/turtlewow-bug-tracker/assets/151180101/cdc5e3b7-6cfa-4c28-9072-98e66bb096b5)
Clear WDB if you still see issues. This one is finally put to rest.
