### ISSUE TITLE
无法附魔

### ISSUE THREAD

**Issue by 13972355599** [slowtorta/turtlewow-bug-tracker#5226]
**Please, provide a clear description what the bug is:**
无法附魔！
**Steps to reproduce the behavior with as much detail as possible:**

1.KLZ新附魔无法给自己附魔！
2. KLZ新附魔无法给自己附魔！
3. KLZ新附魔无法给自己附魔！

**IDs of affected creatures, items, quests or spells with a link to the relevant page:**

NPC: https://database.turtle-wow.org/?npc=
Item: https://database.turtle-wow.org/?item= 物品强效保护符咒 92006
Quest: https://database.turtle-wow.org/?quest=
Spell: https://database.turtle-wow.org/?spell=
Object: https://database.turtle-wow.org/?object=

**Expected behavior. Describe how it should work:**
正常给自己附魔

**Comment by 13972355599** [comment]
物品显示是给头腿附魔，现在怎么也附魔不上去！

**Comment by Muigin** [comment]
请用英文提交问题。我们无法通过自动翻译准确地翻译中文提交的错误报告，这使得我们难以理解问题的确切性质。谢谢！

Please submit the issues in English. We're unable to accurately translate bug reports submitted in Chinese through automatic translation, which makes it difficult for us to understand the exact nature of the issue. Thank you!
