### ISSUE TITLE
强效毒药瓶无法正常叠加BUFF！

### ISSUE THREAD

**Issue by 13972355599** [slowtorta/turtlewow-bug-tracker#5227]
**Please, provide a clear description what the bug is:**
卡拉赞强效毒药瓶饰品现在只叠加2层BUFF，与描述不符合，出现严重BUG！
**Steps to reproduce the behavior with as much detail as possible:**

1.不管任何怪都是叠加2层BUFF，正确应该是5层！
2. 
3. 

**IDs of affected creatures, items, quests or spells with a link to the relevant page:**

NPC: https://database.turtle-wow.org/?npc=
Item: https://database.turtle-wow.org/?item=物品 强效毒药瓶 61243
Quest: https://database.turtle-wow.org/?quest=
Spell: https://database.turtle-wow.org/?spell=
Object: https://database.turtle-wow.org/?object=

**Expected behavior. Describe how it should work:**
它应该正常叠加5层BUFF！

**Comment by Muigin** [comment]
请用英文提交问题。我们无法通过自动翻译准确地翻译中文提交的错误报告，这使得我们难以理解问题的确切性质。谢谢！

Please submit the issues in English. We're unable to accurately translate bug reports submitted in Chinese through automatic translation, which makes it difficult for us to understand the exact nature of the issue. Thank you!
