### ISSUE TITLE
Paladin thorn aura doesn't deal yellow damage

### ISSUE THREAD

**Issue by geojak** [slowtorta/turtlewow-bug-tracker#523]
**Please, provide a clear description what the bug is:**

The paladin thorn aura is supposed to deal holy dmasge. The numbers are white not yellow and the dmasge does not scale with the holy dmasge increase from the crusader judgement debuff. 

**Steps to reproduce the behavior with as much detail as possible:**

1. Activate the paladin thorn aura
2.  Get hit
3.  Damage is not yellow 

**IDs of affected creatures, items, quests or spells with a link to the relevant page:**

NPC: https://database.turtle-wow.org/?npc=
Item: https://database.turtle-wow.org/?item=
Quest: https://database.turtle-wow.org/?quest=
Spell: https://database.turtle-wow.org/?spell=
Object: https://database.turtle-wow.org/?object=

**Expected behavior. Describe how it should work:**

Arua should deal holy dmasge

**Comment by Velite12** [comment]
Ret aura doesn't scale with anything. And it is dealing holy damage if you check the combat log. It's just that Damage Shields (thorns) in vmangos show as white numbers.

**Comment by Velite12** [comment]
Difference being that thorns damage is resistable in classic
