### ISSUE TITLE
(TEL A BIM))   Wrath / Starfire / Partial resists

### ISSUE THREAD

**Issue by marcinb12500** [slowtorta/turtlewow-bug-tracker#5231]
NOTE THIS IS ON TELABIM REALM, TESTS WILL BE CARRIED OUT ON BOTH REALMS AND PUT INTO COMMENTS

ISSUE > Wrath and Starfire often partially resist on targets at lvl 61 and above ( TARGETS HAVE 0 RESIST)

**Steps to reproduce the behavior with as much detail as possible:**

1.  use this script to get mob resistance  /script u=UnitResistance y="target" a=u(y ,0) h=u(y ,1) f=u(y ,2) n=u(y ,3) fr=u(y ,4) s=u(y ,5) z=u(y ,6) SendChatMessage(UnitName(y).." has "..a.." Armor, "..f.." Fire, "..n.." Nature, "..z.." Arcane, "..fr.." Frost and "..s.." Shadow res.", "Emote"); 
2.  Cast wrath or starfire constantly
3.  check combat log for partial resists

**IDs of affected creatures, items, quests or spells with a link to the relevant page:**

![Screenshot 2023-11-15 195747](https://github.com/slowtorta/turtlewow-bug-tracker/assets/16656618/e77508f5-2409-4cb2-b155-8ddfb409402d)
![Screenshot 2023-11-15 195752](https://github.com/slowtorta/turtlewow-bug-tracker/assets/16656618/442e9a23-4498-4114-807a-f0f464adc604)
![Screenshot 2023-11-15 195805](https://github.com/slowtorta/turtlewow-bug-tracker/assets/16656618/32dd27cb-134c-46de-82fa-9b65b378114f)
![Screenshot 2023-11-15 195810](https://github.com/slowtorta/turtlewow-bug-tracker/assets/16656618/22424b1d-4a5b-4f23-a362-daefa3091fc8)
![Screenshot 2023-11-15 204713](https://github.com/slowtorta/turtlewow-bug-tracker/assets/16656618/42d33913-35f8-46e8-81b1-82b3437c76d6)
![Screenshot 2023-11-15 205124](https://github.com/slowtorta/turtlewow-bug-tracker/assets/16656618/881f3a0b-3cfe-42e2-93f2-2f75a120a7a1)
![Screenshot 2023-11-15 205911](https://github.com/slowtorta/turtlewow-bug-tracker/assets/16656618/0bff84ca-ad34-442a-87b7-3cb743236646)
![Screenshot 2023-11-15 205918](https://github.com/slowtorta/turtlewow-bug-tracker/assets/16656618/0db7be69-16a9-4e96-ae36-408db59796a4)
![Screenshot 2023-11-15 210554](https://github.com/slowtorta/turtlewow-bug-tracker/assets/16656618/29e7ec3d-985f-4207-883b-524a7123a708)
![Screenshot 2023-11-15 210557](https://github.com/slowtorta/turtlewow-bug-tracker/assets/16656618/4bce415b-ba59-4459-ae2e-531880313420)
![Screenshot 2023-11-15 210908](https://github.com/slowtorta/turtlewow-bug-tracker/assets/16656618/d6684c03-6f31-4cad-893e-4d9ead29e3fa)
![Screenshot 2023-11-15 211017](https://github.com/slowtorta/turtlewow-bug-tracker/assets/16656618/cd8bbd15-2719-4e16-8617-c5a6d2c86aa3)
![Screenshot 2023-11-15 211020](https://github.com/slowtorta/turtlewow-bug-tracker/assets/16656618/2b130715-e437-40ba-941f-021e66f4ab3d)
![Screenshot 2023-11-15 211254](https://github.com/slowtorta/turtlewow-bug-tracker/assets/16656618/53e2ead2-50e1-4281-8b8c-d65e9b6ba7f9)
![Screenshot 2023-11-15 224341](https://github.com/slowtorta/turtlewow-bug-tracker/assets/16656618/38f6d352-394b-4af7-99c7-3b2e2f94edd7)
![Screenshot 2023-11-15 224348](https://github.com/slowtorta/turtlewow-bug-tracker/assets/16656618/1d2af066-9e6b-4614-8e97-10de20e9496b)
![Screenshot 2023-11-15 224619](https://github.com/slowtorta/turtlewow-bug-tracker/assets/16656618/b942a2ff-7a6e-4c82-9d7c-78ed3fc0ca73)
![Screenshot 2023-11-15 224631](https://github.com/slowtorta/turtlewow-bug-tracker/assets/16656618/82faf753-4369-4fed-b764-0c20ab0651e7)
![Screenshot 2023-11-15 224711](https://github.com/slowtorta/turtlewow-bug-tracker/assets/16656618/ff71a6d6-566c-4686-a833-e808ab1b855a)
![Screenshot 2023-11-15 225258](https://github.com/slowtorta/turtlewow-bug-tracker/assets/16656618/563a7d14-aed5-4022-9ab0-4301453a525a)

Item: https://database.turtle-wow.org/?item= 
Quest: https://database.turtle-wow.org/?quest=
Spell: https://database.turtle-wow.org/?spell=spell=5177 (wrath)
Object: https://database.turtle-wow.org/?object=

if there is no resistance it should hit or miss, not partially resist

attaching pictures

**Comment by marcinb12500** [comment]
Just had a starfire do 200 dmg 800 resisted on a target with 5 arcane resistance

**Comment by marcinb12500** [comment]
![Screenshot 2023-11-15 205911](https://github.com/slowtorta/turtlewow-bug-tracker/assets/16656618/9c8ec56a-b66a-4709-ba72-f4ce6319fad6)
![Screenshot 2023-11-15 205918](https://github.com/slowtorta/turtlewow-bug-tracker/assets/16656618/8a08c0c7-7fd6-4f63-92f3-e54629afa14a)

**Comment by marcinb12500** [comment]
![Screenshot 2023-11-15 211017](https://github.com/slowtorta/turtlewow-bug-tracker/assets/16656618/c9c81b8c-9189-4de5-af57-f5b3f9dd04dc)
![Screenshot 2023-11-15 211020](https://github.com/slowtorta/turtlewow-bug-tracker/assets/16656618/2d99c714-5fba-442c-98a1-6800876a096c)

**Comment by marcinb12500** [comment]
![Screenshot 2023-11-15 211254](https://github.com/slowtorta/turtlewow-bug-tracker/assets/16656618/6a8686c6-6f4b-451f-a05c-07b859f8b961)
![Screenshot 2023-11-15 211257](https://github.com/slowtorta/turtlewow-bug-tracker/assets/16656618/83f060fc-d7e9-49a1-8d4f-63bf710b65fc)

**Comment by marcinb12500** [comment]
![Screenshot 2023-11-15 224341](https://github.com/slowtorta/turtlewow-bug-tracker/assets/16656618/0e5b47cd-febb-4866-9c64-60e596fd7b59)
![Screenshot 2023-11-15 224348](https://github.com/slowtorta/turtlewow-bug-tracker/assets/16656618/6718c8b2-b1a9-4e9e-82a0-46f9201d9be6)

**Comment by marcinb12500** [comment]
![image_2023-11-15_224741604](https://github.com/slowtorta/turtlewow-bug-tracker/assets/16656618/18c54247-44e9-4faa-bee0-ca43da722671)

**Comment by marcinb12500** [comment]
![Uploading image_2023-11-15_225304748.png…]()

**Comment by marcinb12500** [comment]
![image_2023-11-15_225401018](https://github.com/slowtorta/turtlewow-bug-tracker/assets/16656618/c46650fb-7d19-44ae-aa14-bd1168910bc2)

**Comment by marcinb12500** [comment]
Target dummy test on lvl 60 target dummy with 0 resistances 
![image_2023-11-15_230536749](https://github.com/slowtorta/turtlewow-bug-tracker/assets/16656618/d0cbefc6-073e-4feb-96d9-8d1dfcf52deb)

**Comment by marcinb12500** [comment]
test 2, heroic target dummy skull with 0 resistances 
![Screenshot 2023-11-15 225258](https://github.com/slowtorta/turtlewow-bug-tracker/assets/16656618/ed9a6ecd-4807-46b9-abb0-1cd041abc45f)

**Comment by balakethelock** [comment]
each level difference between you and mobs gives the higher level target +8 invisible magic resistance that can never be penetrated by any means
So yeah you can get rarely partial resists vs a mob higher level than you even if it has 0 visible magic resist

**Comment by marcinb12500** [comment]
> each level difference between you and mobs gives the higher level target +8 invisible magic resistance that can never be penetrated by any means So yeah you can get rarely partial resists vs a mob higher level than you even if it has 0 visible magic resist

This is evidently not rare.

**Comment by marcinb12500** [comment]
If you are saying that 8 percent gives me 30% chance to resist then please provide evidence or conduct testing and post findings below. I will happily replicate these effects

**Comment by marcinb12500** [comment]
THIS Test was conducted by another druid on the PVE realm 

![image](https://github.com/slowtorta/turtlewow-bug-tracker/assets/16656618/818ae55d-c6d0-4163-9ea3-bacec0cb0103)
![image1](https://github.com/slowtorta/turtlewow-bug-tracker/assets/16656618/83289e01-fd31-443c-963c-97d4a7782d00)
![image2](https://github.com/slowtorta/turtlewow-bug-tracker/assets/16656618/f60f90ad-8f6b-4797-a2c4-3333216484cb)

**Comment by marcinb12500** [comment]
BELOW PICTURE IS ON TELABIM WITH CURSE OF SHADOWS 



![image_2023-11-16_174746032](https://github.com/slowtorta/turtlewow-bug-tracker/assets/16656618/c1d5c613-dfd5-428c-89ab-78ee2a184a5c)

**Comment by balakethelock** [comment]
Seems about right to me, this is with 24 magic resistance (8 per level)
You should have noticed this everywhere from blizzlike private projects (lights hope, everlook) and classic. all have the same behavior as far as I know

**Comment by Zebouski** [comment]
I think the question here is, is it a bug if the level-based resist is not showing via the UnitResistance() API call. 

As far as I understand, in 2006 and classic the only time this API call is meant to function is when checking your lock or hunter pet, and when checking a NPC beast lore. A few pservers have enabled it as has turtle, so this is a custom feature.

Should UnitResistance() stay as is and not include level-based resist, and potentially confuse players who expect 0 resistance to really _mean_ 0? 
Or should it show level-based resist and potentially confuse people that they could make use of further spellpen gear/curses when in truth this type of resist is not removable?

**Comment by balakethelock** [comment]
It's not a bug. This level-based resist is not a stat on the enemy but rather just a part of the resistance calculation formula.
UnitResistance tells you how much resistance stat this mob has, not how much it will resist YOUR spells. The innate stat of the mob stays the same no matter your level.
