### ISSUE TITLE
mail system

### ISSUE THREAD

**Issue by LSDaxism** [slowtorta/turtlewow-bug-tracker#5232]
**Please, provide a clear description what the bug is:**

**Steps to reproduce the behavior with as much detail as possible:**

1. the character i have leveled up to 7 can not send mail.
2. it says i have reach the max number of mail recipients
3. i can still receive mail on said character
4. i can still send mail from the first 3 i used the mail system with
5. dosaki is the character with the issue

**IDs of affected creatures, items, quests or spells with a link to the relevant page:**

NPC: https://database.turtle-wow.org/?npc=
Item: https://database.turtle-wow.org/?item=
Quest: https://database.turtle-wow.org/?quest=
Spell: https://database.turtle-wow.org/?spell=
Object: https://database.turtle-wow.org/?object=

**Expected behavior. Describe how it should work:**

**Comment by AkalixFrost** [comment]
Greetings.

Low-level characters have limited use of the Mail system to combat RMT advertisements. Working as intended.
