### ISSUE TITLE
Feral Druid Improved Shred won't cast without 60 energy despite costing 42

### ISSUE THREAD

**Issue by User456789321** [slowtorta/turtlewow-bug-tracker#5234]
**Please, provide a clear description what the bug is:**

Feral Druid Improved Shred talent reduces shred cost from 60 energy to 42
Even with full points in the talent, shred won't cast without 60 energy despite costing 42

**Steps to reproduce the behavior with as much detail as possible:**

1. Select the "Improved Shred" talent in the Feral Druid tree
2.  Spam shred in any scenario and observe when it casts vs. how much energy you have to spend
3. It seems inconsistent, but most of the time it will not cast unless you have at least 60 energy, despite now only costing 42 due to the improved shred talent. It takes the correct amount of energy when cast, but requires the original 60 to be allowed to cast it.
4. This issue has persisted across many levels and spell ranks, and multiple deletions of my WDB folder.

**IDs of affected creatures, items, quests or spells with a link to the relevant page:**

NPC: https://database.turtle-wow.org/?npc=
Item: https://database.turtle-wow.org/?item=
Quest: https://database.turtle-wow.org/?quest=
Spell: https://database.turtle-wow.org/?spell=9830
Object: https://database.turtle-wow.org/?object=

**Expected behavior. Describe how it should work:**

When 2 points are in improved shred, it should allow you to cast shred when you have at least 42 energy and not require 60 to be banked

**Comment by welpenhund** [comment]
Not confirmned, plus i gotta mention that even with improved Shred your shred costs will be 48, not 42.
Tested on PTR with "mod energy 48 48" and it works as intended.

**Comment by welpenhund** [comment]
> **Please, provide a clear description what the bug is:**
> 
> Feral Druid Improved Shred talent reduces shred cost from 60 energy to 42 Even with full points in the talent, shred won't cast without 60 energy despite costing 42
> 
> **Steps to reproduce the behavior with as much detail as possible:**
> 
>     1. Select the "Improved Shred" talent in the Feral Druid tree
> 
>     2. Spam shred in any scenario and observe when it casts vs. how much energy you have to spend
> 
>     3. It seems inconsistent, but most of the time it will not cast unless you have at least 60 energy, despite now only costing 42 due to the improved shred talent. It takes the correct amount of energy when cast, but requires the original 60 to be allowed to cast it.
> 
>     4. This issue has persisted across many levels and spell ranks, and multiple deletions of my WDB folder.
> 
> 
> **IDs of affected creatures, items, quests or spells with a link to the relevant page:**
> 
> NPC: https://database.turtle-wow.org/?npc= Item: https://database.turtle-wow.org/?item= Quest: https://database.turtle-wow.org/?quest= Spell: https://database.turtle-wow.org/?spell=9830 Object: https://database.turtle-wow.org/?object=
> 
> **Expected behavior. Describe how it should work:**
> 
> When 2 points are in improved shred, it should allow you to cast shred when you have at least 42 energy and not require 60 to be banked

Not confirmned, plus i gotta mention that even with improved Shred your shred costs will be 48, not 42.
Tested on PTR with "mod energy 48 48" and it works as intended.

**Comment by User456789321** [comment]
Sorry you are correct it's 48 not 42.
It seems to happen more in group settings, so potentially a latency issue then.
