### ISSUE TITLE
Barrens Zebra fix name in Spellbook

### ISSUE THREAD

**Issue by hokagegaara** [slowtorta/turtlewow-bug-tracker#5236]
https://database.turtle-wow.org/?item=50426
Rename spell to "Barrens Zebra" or "Riding Zebra" or "Riding Barrens Zebra"
https://database.turtle-wow.org/?spell=46446
![изображение](https://github.com/slowtorta/turtlewow-bug-tracker/assets/7520527/949e88be-09ea-48e3-a61e-64844b57ed9d) ![изображение](https://github.com/slowtorta/turtlewow-bug-tracker/assets/7520527/2ff62b03-976d-4e51-bc88-163c4665f2aa)

**Comment by hokagegaara** [comment]
It Zebra not Zhevra
![изображение](https://github.com/slowtorta/turtlewow-bug-tracker/assets/7520527/15d02dd6-cf4c-4dd8-8eab-76eb40519490)

**Comment by hokagegaara** [comment]
Also need fix Phase for "Zebrian the Mad"
https://github.com/slowtorta/turtlewow-bug-tracker/issues/5105

**Comment by hokagegaara** [comment]
Also bug in site https://database.turtle-wow.org/?item=50426
Soulbound but in game "Bind when use"
![изображение](https://github.com/slowtorta/turtlewow-bug-tracker/assets/7520527/860b1512-ff44-4296-b9ae-84ba1582c498)
![изображение](https://github.com/slowtorta/turtlewow-bug-tracker/assets/7520527/1f031492-0407-4a40-885f-8f746158c673)

**Comment by slowtorta** [comment]
Fixed in the internal build. The change will be reflected in game upon the next clent update (this can take a few months, please do not re-open this issue).
