### ISSUE TITLE
Mind quickening gem doesnt apply haste after talents

### ISSUE THREAD

**Issue by Fugger22** [slowtorta/turtlewow-bug-tracker#5238]
**Please, provide a clear description what the bug is:**

**Steps to reproduce the behavior with as much detail as possible:**

1.3 second cast with 33% haste should be 2.1 seconds long but its 2.3
2. 
3. 

**IDs of affected creatures, items, quests or spells with a link to the relevant page:**

NPC: https://database.turtle-wow.org/?npc=
Item:https://database.turtle-wow.org/?item=19339
Quest: https://database.turtle-wow.org/?quest=
Spell: https://database.turtle-wow.org/?spell=
Object: https://database.turtle-wow.org/?object=

**Expected behavior. Describe how it should work:**

**Comment by Zebouski** [comment]
The formula for haste in this case is 
3 / (1+33%) = 2.256 round up to 2.3

to bring a 3s cast down to 2.1 you'd need 7% more haste from elsewhere:
3 / ((1+33%) * (1+7%)) = 2.108

Working as intended

Haste is a bit tricky to understand, just know that +100% haste means you cut a swing or cast timer in half, not +50%. Further clarification if you ask on the discord.

**Comment by Fugger22** [comment]
thanks this explains it
