### ISSUE TITLE
The problem with Warlock Shadowburn(R4) ability

### ISSUE THREAD

**Issue by ArGer0** [slowtorta/turtlewow-bug-tracker#5239]
**Please, provide a clear description what the bug is:**
The problem with Warlock Shadowburn(R4) ability. Other ranks not tested. It says that Shadowburn uses 240Mana and instantly blasts the targt  for 352-385 shadow damage. If target dies within 5 sec of Shadowburn and yields experirnce or honor, the caster gains A Soul Shard. 
But when I use this ability on my Warlock it uses Soul Shard too with mana together. And when target dies within 5 sec, warlock gain Soul Shard.

**Steps to reproduce the behavior with as much detail as possible:**

1. Attack any target that green/yellow/red for caster. Target must be relevant for caster to gain Soul Shard
2. Hit target till 500 HP
3. Use Shadowburn ability to gain Soul Shard

**IDs of affected creatures, items, quests or spells with a link to the relevant page:**

NPC: https://database.turtle-wow.org/?npc=
Item: https://database.turtle-wow.org/?item=
Quest: https://database.turtle-wow.org/?quest=
Spell: https://database.turtle-wow.org/?spell=18869
Object: https://database.turtle-wow.org/?object=

**Expected behavior. Describe how it should work:**
In accordance of description Shadowburn must use mana only. No Soul Shard required.

Video for better understanding. Sorry for quality.
https://youtu.be/BPSJaD9v5Jk

**Comment by cyaohiri** [comment]
Shadowburn isn't a way to generate soul shards. It's a way to do instant damage without using soul shards, as long as the target dies quickly enough. The spell is working as intended. https://www.wowhead.com/classic/spell=17877/shadowburn

**Comment by Zebouski** [comment]
What has happened here is that your Theorycraft addon has removed the line of the tooltip that says Reagents: Soul Shard, so you had no idea in game.

Always disable addons, and do research like actually looking up the spell's 1.12 behavior, before you go thinking something is a bug and waste people's time with false reports.

**Comment by ArGer0** [comment]
> Shadowburn isn't a way to generate soul shards. It's a way to do instant damage without using soul shards, as long as the target dies quickly enough. The spell is working as intended. https://www.wowhead.com/classic/spell=17877/shadowburn

Then spell description in TWoW client is wrong. There is no mention about reagent for the spell.

Anyway I got it.

**Comment by Muigin** [comment]
> Then spell description in TWoW client is wrong. There is no mention about reagent for the spell.

https://database.turtle-wow.org/?search=shadowburn
It says it clear as day in the spell's description.

Working as intended.

**Comment by ArGer0** [comment]
<img width="459" alt="ShadowburnDescription" src="https://github.com/slowtorta/turtlewow-bug-tracker/assets/129500220/66ba2b2f-49d6-4898-b4ca-49f5ced17f14">
Here is the description in client. Reagent not mentioned.

**Comment by Muigin** [comment]
![?](https://i.imgur.com/VZYOg18.png)

And here it is in the client without your addons enabled, just as Zebouski above said. This conversation is now locked.  Refrain from making bug reports until you troubleshoot on your own and remove any extraneous factors like addons.
