### ISSUE TITLE
Daphne Stilwel has green cube in her hand

### ISSUE THREAD

**Issue by geojak** [slowtorta/turtlewow-bug-tracker#524]
**Please, provide a clear description what the bug is:**

The npc Daphne stilwel in westfal is displayed with a yellow cube in her hand when starting the paladin quest the tome of valor in which the player and the noc fight together waves of defias raiders

**Steps to reproduce the behavior with as much detail as possible:**

1. Be a paladin and start the quest " the tome of valor" 
2. Watch the qeustgivrr Daphne Stilwel 
3. Observe a green weapon dice in her hand

**IDs of affected creatures, items, quests or spells with a link to the relevant page:**

NPC: https://database.turtle-wow.org/?npc=
Item: https://database.turtle-wow.org/?item=
Quest: https://database.turtle-wow.org/?quest=
Spell: https://database.turtle-wow.org/?spell=
Object: https://database.turtle-wow.org/?object=

**Expected behavior. Describe how it should work:**

I do not know what weapon/weapon model she is supposed to use on blizzard classic.

**Comment by slowtorta** [comment]
Lady got a bucket.

**Comment by geojak** [comment]
redid the quest today, not fixed yet as of today. maybe after some big update?
