### ISSUE TITLE
Extra 193g removed from Tole.

### ISSUE THREAD

**Issue by Tole217** [slowtorta/turtlewow-bug-tracker#5243]
**Please, provide a clear description what the bug is:**
Just after the Goblin Brainwashing Device was changed, I purchased the two new slots. As you know, this did not charge my character "Tole" 300g, but instead awarded him 300g. As I normally do with excess funds, I sent the gold off to bank alts and left 193g on my main character, Tole. The following morning, the 193g was missing and Tole was left with 0g. I was not concerned as I figured it was an intended rake-back of the excess gold.

Stepping forward to this week, a further 600g was taken from my account, username 'Tole', in the amount of 100g from character 'Tole' and 500g from character 'Harambewithu'. This transaction by itself evens-out accounts with the benefit I obtained from the original Brainwashing Device bug. However, the first roughly 193g taken from Tole now leaves me with a net negative 193g.

I am submitting this report with the request that our accounts be made even and 193g be returned to Tole.

**Steps to reproduce the behavior with as much detail as possible:**

1. Buy 3rd and 4th Brainwashing Device slots during the five or so minutes that it was bugged.
2. Have gold taken the first time.
3. Have much more gold be taken than was gained and panic to buy consumes for raid, mostly as the consequences of your own actions.
4. Ask the wonderful Turtle WoW Support Staff to return the gold removed in excess of the 600g benefit from the bug.

**IDs of affected creatures, items, quests or spells with a link to the relevant page:**

NPC: https://database.turtle-wow.org/?npc=
Item: https://database.turtle-wow.org/?item=51715
Quest: https://database.turtle-wow.org/?quest=
Spell: https://database.turtle-wow.org/?spell=
Object: https://database.turtle-wow.org/?object=

**Expected behavior. Describe how it should work:** A total of 600g should have been removed from my account.

**Comment by twowTurtReynolds** [comment]
Please contact a GM via an ingame ticket or via #support on the discord. This doesn't belong in the bug tracker.
