### ISSUE TITLE
Chromaggus Ignite Flesh stacks multiple times

### ISSUE THREAD

**Issue by 1leonaa** [slowtorta/turtlewow-bug-tracker#5246]
Hello sir, we are attacking the Black Wing Lair. Why can Chromaggus ignite make our tanks and stack up to three layers
ID 23149

**Please, provide a clear description what the bug is:**

**Steps to reproduce the behavior with as much detail as possible:**

1.
2. 
3. 

**IDs of affected creatures, items, quests or spells with a link to the relevant page:**

NPC: https://database.turtle-wow.org/?npc=
Item: https://database.turtle-wow.org/?item=
Quest: https://database.turtle-wow.org/?quest=
Spell: https://database.turtle-wow.org/?spell=
Object: https://database.turtle-wow.org/?object=

**Expected behavior. Describe how it should work:**

**Comment by 1leonaa** [comment]
not noly 3 and more Language curse doesn't work

**Comment by twowTurtReynolds** [comment]
What was the latency/ping of the tank? I think it may be possible that this issue only happens with high latency, as with low latency the debuff will always fall off before the new one is applied. Old 2006 guides say that the debuff can and will stack.

**Comment by twowTurtReynolds** [comment]
I'll mark this closed until replication steps are provided.
