### ISSUE TITLE
Emote on non-combat and guardian pets

### ISSUE THREAD

**Issue by cyaohiri** [slowtorta/turtlewow-bug-tracker#5247]
When using an emote on pets, such as /cheer, the pet's name shows as Pet instead of their actual name in the chat log, i.e. "You cheer at Pet".
A possibly related issue is that hardcore death messages by NPC minions are shown as Pet, instead of using that minion's name.

**Comment by cyaohiri** [comment]
To clarify, this worked fine a few weeks ago, i.e. the pet's actual names was shown.

**Comment by twowTurtReynolds** [comment]
> To clarify, this worked fine a few weeks ago, i.e. the pet's actual name was shown.

OK, I believe you, but proof would be nice to minimize risk of sending a dev on a wild goose chase.

**Comment by cyaohiri** [comment]
Do you need a recording from actual vanilla or would a recording from Turtle WoW suffice?

**Comment by twowTurtReynolds** [comment]
> Do you need a recording from actual vanilla or would a recording from Turtle WoW suffice?

From twow is okay, it's enough to confirm that there was a regression, thank you.

**Comment by cyaohiri** [comment]
Here's a recording from January 2023. https://streamable.com/uyicp4

**Comment by twowTurtReynolds** [comment]
https://github.com/vmangos/core/blob/development/src/game/Handlers/ChatHandler.cpp#L739 is where the server builds the text string and requests the pets name. It seems the function it is requesting, located here https://github.com/vmangos/core/blame/development/src/game/Objects/Pet.h#L265 was modified 8 months ago, possibly what broke this.

**Comment by twowTurtReynolds** [comment]
![image](https://github.com/slowtorta/turtlewow-bug-tracker/assets/151180101/42734943-9837-4d7c-b47e-606239e61d3e)
Works on vmangos, so a turtle specific issue.

**Comment by cyaohiri** [comment]
I originally noticed it on non-combat pets, but the recording was for combat pets, as I thought it applied to them too, but turns out it doesn't. It seems like this is only affecting non-combat pets.
Here's a screenshot from January, showing the pet's name in chat.
![WoWScrnShot_012023_094900](https://github.com/slowtorta/turtlewow-bug-tracker/assets/86041826/fb194f4f-4880-417e-8d75-5176f0a1ab28)

**Comment by twowTurtReynolds** [comment]
Ah okay I'll test that.

**Comment by cyaohiri** [comment]
![image](https://github.com/slowtorta/turtlewow-bug-tracker/assets/86041826/b3ba5fa7-35e6-4783-845a-f0ff669d1c1f)
These are probably deaths by an NPC's Voidwalker or a similar minion. As mentioned in the original post, this worked before.

**Comment by cyaohiri** [comment]
Latest VMaNGOS:
https://streamable.com/woi5y8

**Comment by ratkosrb** [comment]
It was fixed by https://github.com/vmangos/core/commit/dc3c7525916e44a8a5d10935175871d36add601b
