### ISSUE TITLE
Graphics: Pixelated effects

### ISSUE THREAD

**Issue by cyaohiri** [slowtorta/turtlewow-bug-tracker#5249]
The issue described in #3055 still persists. Here are comparisons between a fresh 1.12.1 client and the Turtle WoW client.

Vanilla 1.12.1 client: https://streamable.com/5p3qme
Turtle WoW 1.17.0 client https://streamable.com/gf1xfc

**Comment by twowTurtReynolds** [comment]
If you need a ticket reopened, just comment on the old one please. Closing this one as duplicate
