### ISSUE TITLE
curse of mending not working

### ISSUE THREAD

**Issue by geojak** [slowtorta/turtlewow-bug-tracker#525]
**Please, provide a clear description what the bug is:**

the curse of mending is a spell the dark strand fanatics around the tower of athalaxx in darkshore use against the player. while affected by this curse there is a chance that the attack against an enemy heals them instead of damages them. this does not happen the the hit deals its regular damage and doesnt heal even thought the animation does proc.

**Steps to reproduce the behavior with as much detail as possible:**

1. get affected by curse of mending 
2. let it proc (animation works)
3. observe that your hit dealt its normal damage and did not heal the enemy like it is supposed to

**IDs of affected creatures, items, quests or spells with a link to the relevant page:**

NPC: https://database.turtle-wow.org/?npc=
Item: https://database.turtle-wow.org/?item=
Quest: https://database.turtle-wow.org/?quest=
Spell: https://database.turtle-wow.org/?spell=
Object: https://database.turtle-wow.org/?object=

**Expected behavior. Describe how it should work:**

see above step 3.

**Comment by geojak** [comment]
now that the cresent grove dungen is released and some mobs use this spell aswell in there. it might be a bit higher priority than before becuase of some minor lvl 15 darkshore mobs.

**Comment by geojak** [comment]
mobs in blasted lands use this too. it still heals the player isntead of the mob as it should be

**Comment by redmagejoe** [comment]
This is now working as intended, so was shadow-fixed at some point. Just tested all mobs that use this spell and it now correctly heals the enemy in combat log and in their HP bar.
