### ISSUE TITLE
Shadow Weaving BUG

### ISSUE THREAD

**Issue by Whocareslolbug** [slowtorta/turtlewow-bug-tracker#5250]
**Please, provide a clear description what the bug is:**

**Steps to reproduce the behavior with as much detail as possible:**

1. Die to pvp, 
2. res
3. ??
4. deficit

**IDs of affected creatures, items, quests or spells with a link to the relevant page:**

Spell: https://database.turtle-wow.org/?spell=
Object: **https://database.turtle-wow.org/?object=](https://database.turtle-wow.org/?spell=15334)**

**Expected behavior. Describe how it should work:**

Shadow Weaving the 15 point shadow talent (5/5) is supposed to have 100% chance to apply a stacking shadow vulnerability debuff, I've not noticed what appears to trigger this but sometimes it will stop applying this even though I have 100% chance to apply on shadow damage until I respec out of shadow and back in (using the goblin brain washing device).

**Comment by twowTurtReynolds** [comment]
Testing on PTR
![image](https://github.com/slowtorta/turtlewow-bug-tracker/assets/151180101/58d0d11b-e6a5-4f03-9754-b2a29b35d2b7)
Died to my multibox. Started flaying mobs nearby. Every signle flay that didnt resist put a SM stack on it.

I believe you, but you are going to need to really test this and find out exactly what steps to take to make this issue appear. Reply with the new replication steps and we'll reopen.
