### ISSUE TITLE
Shimmering Flat Racing Car Quest bugged.

### ISSUE THREAD

**Issue by TheRealJurki** [slowtorta/turtlewow-bug-tracker#5251]
Hi, the Quest (https://database.turtle-wow.org/?quest=50310) is not working proberly. 
I can talk to the NPC Dolores (https://database.turtle-wow.org/?npc=50533), which puts me in a queue without starting the test race. 

Abandoning the quest and deleting the wdb folder dont fix the issue.

**Comment by twowTurtReynolds** [comment]
Tracking these issues under https://github.com/slowtorta/turtlewow-bug-tracker/issues/4813, thanks.
