### ISSUE TITLE
Deckmaster\'s Commendation: mistype in desctiption 

### ISSUE THREAD

**Issue by Gasan918** [slowtorta/turtlewow-bug-tracker#5253]
**Please, provide a clear description what the bug is:**

Deckmaster\'s Commendation description say:

"In service to the Kul Tiran navy." Tiran?

![image](https://github.com/slowtorta/turtlewow-bug-tracker/assets/96973359/8f171acc-dc7b-436a-ab37-43dc890dc403)

Item: https://database.turtle-wow.org/?item=61100

**Expected behavior. Describe how it should work:**

"In service to the Kul Tiras navy."

**Comment by twowTurtReynolds** [comment]
Something belonging to the Kul Tiras would be called the Kul Tiran. Think like Darnassus vs Darnassian Bleu. Yeah?

**Comment by Gasan918** [comment]
Then it must be "Tyrant".
