### ISSUE TITLE
Rival Presence is not tagged as a Dungeon quest

### ISSUE THREAD

**Issue by octav3k** [slowtorta/turtlewow-bug-tracker#5255]
**Please, provide a clear description what the bug is:**
The quest Rival Presence is not tagged as a Dungeon quest, even though it is correctly assigned to the Hateforge Quarry category.

**Steps to reproduce the behavior with as much detail as possible:**
N/A

**IDs of affected creatures, items, quests or spells with a link to the relevant page:**
Quest: https://database.turtle-wow.org/?quest=40458
NPC: https://database.turtle-wow.org/?npc=60717

**Expected behavior. Describe how it should work:**
Rival Presence should be tagged as a Dungeon quest, since it requires killing an NPC inside Hateforge Quarry.

**Comment by twowTurtReynolds** [comment]
You are correct.

Related to https://github.com/slowtorta/turtlewow-bug-tracker/issues/1730
