### ISSUE TITLE
Resistance not stacking

### ISSUE THREAD

**Issue by oftis** [slowtorta/turtlewow-bug-tracker#5256]
I notice that when i have Mark of the Wild that increases all resistances with 5 plus Shadow resistance Aura that gives me 30 additional shadow resistance, my total resistance is 30. This persisted after i deleted my WBD folder, exited the game and logged back in.

**Comment by twowTurtReynolds** [comment]
Yep, thats how it works. https://www.google.com/search?hl=en&q=what%20does%20motw%20stack%20with
