### ISSUE TITLE
Cloak of the dark veil doesn't drop 2

### ISSUE THREAD

**Issue by Skaryna3** [slowtorta/turtlewow-bug-tracker#5257]
Already made a bug report before:
https://github.com/slowtorta/turtlewow-bug-tracker/issues/5177

Nothing changed after the server restart. Still can't get it. Had like 30 more runs. Could you please comment on this issue somehow? I really don't like being a tester for your bugs. Spending so much time on an item that exists in the database but not in the game. I already hate turtle wow.  Remove this item from the db if you can't add it.

**Comment by twowTurtReynolds** [comment]
If you need us to reopen a ticket, just comment on the old one :)

Sorry about the troubles man.
