### ISSUE TITLE
ZG camp out dont work

### ISSUE THREAD

**Issue by jackadripper** [slowtorta/turtlewow-bug-tracker#5258]
Zg camp out is not working any more why ?

**Comment by twowTurtReynolds** [comment]
ZG is a raid, and as far as I know, the only way to be sent outside is to log out and log in while a boss encounter is ongoing.

**Comment by jackadripper** [comment]
and when did you adjust this?

**Comment by jackadripper** [comment]
and if you handle everything like this, why don't you change AV to blizzerd and this?

**Comment by twowTurtReynolds** [comment]
> and when did you adjust this?

I'm not a dev, I'm QA. IDK if anything has even changed here. I'm asking you.

> and if you handle everything like this, why don't you change AV to blizzerd and this?

The general rule is that things not deliberately made to be different, are meant to be blizzlike.

**Comment by twowTurtReynolds** [comment]
@patrycos you seem to be right :) 
![image](https://github.com/slowtorta/turtlewow-bug-tracker/assets/151180101/ce116d49-d9bd-40d9-88e6-141551fb735f)

There I am in a party in a saved ZG. Then I /camp, and log back in 

![image](https://github.com/slowtorta/turtlewow-bug-tracker/assets/151180101/e5aa5bb1-02ad-4e2c-ab74-43a9c27cddae)

And indeed I'm still there.

Doing this while not in a saved ZG indeed sent me right outside.

Working as intended.

**Comment by jackadripper** [comment]
tnx helping its fix (L)
