### ISSUE TITLE
My crit chance is reduced

### ISSUE THREAD

**Issue by Chukis96** [slowtorta/turtlewow-bug-tracker#5261]
**Please, provide a clear description what the bug is:**
When I changed my weapons my critical reduced by 11%, I restarted the client, deleted my WDB folder, reinstalled the addons, tried without the WFT folder, tried on another computer... Nothing, it still shows that my crit chance is 9% when it should be 21% (before changing weapons it was 19%). My character name is Chukistrukis.

Also when I'm removing pieces of equipment, when it reaches 5% (there are still crit pieces equipped) it can't go any lower (I guess because of the talent), but even if there are pieces equipped, it doesn't seem to add up.

**Steps to reproduce the behavior with as much detail as possible:**

1. Swap Weapons
2. 
3. 

**IDs of affected creatures, items, quests or spells with a link to the relevant page:**

Item: https://database.turtle-wow.org/?item=12940

**Expected behavior. Describe how it should work:**

My crit chance should be 21%

**Comment by twowTurtReynolds** [comment]
How are you checking that you have 9% crit? The only 100% accurate way to check is by hovering over the Attack ability in your spellbook. This sounds to me like an addons issue, be sure to disable them all and only test with them off.

**Comment by balakethelock** [comment]
make sure you have 300 weapon skill then test again.
Being low on weapon skill reduces crit chance

**Comment by twowTurtReynolds** [comment]
![image](https://github.com/slowtorta/turtlewow-bug-tracker/assets/151180101/aeac9a74-6876-4ce1-bcf0-8116577c81be)


Then i hit .maxskill and relogged:
![image](https://github.com/slowtorta/turtlewow-bug-tracker/assets/151180101/cf2fa605-41ed-4f04-b1c0-c6ab59131ec4)

Thanks for the clarification @balakethelock . Not a bug.
