### ISSUE TITLE
Trinket Grace of Earth doesn't seem to work

### ISSUE THREAD

**Issue by MeteorCrush** [slowtorta/turtlewow-bug-tracker#5262]
**Please, provide a clear description what the bug is:**

I just want to confirm whether the trinket called "Grace of Earth" is working or not.

From all the times I've used this Trinket so far, as a healer Priest, I have not succeeded in getting enemies to turn away. But with Fade, it always works.

**Steps to reproduce the behavior with as much detail as possible:**

1. In a party, as a Healer, try to heal the tank enough to pull aggro from the tank, such as with a Rank 2 Heal.
2. Upon pulling aggro from tank, activate the trinket "Grace of Earth".
3. Observe whether the enemies will turn back to the tank or not.
4. Repeat the above experiment, but with "Fade". With "Fade", it always works.

**IDs of affected creatures, items, quests or spells with a link to the relevant page:**

Item: https://database.turtle-wow.org/?item=21181

**Expected behavior. Describe how it should work:**

I assume it would behave something like a priest's "Fade" ability, which would cause enemies to turn away upon triggering this trinket, if the threat needed to be reduced has been met.

**Comment by twowTurtReynolds** [comment]
Confirmed via TWThreat, No threat was reduced.
