### ISSUE TITLE
Encroachment quest bugged

### ISSUE THREAD

**Issue by ghost** [slowtorta/turtlewow-bug-tracker#5266]
**Please, provide a clear description what the bug is:**
Encroachment quest doesn't count Razormane Quilboar kills.
**Steps to reproduce the behavior with as much detail as possible:**
1.  Accept the quest "Encroachment"
2.  Kill Razormane Quillboar

**IDs of affected creatures, items, quests or spells with a link to the relevant page:**

NPC: https://database.turtle-wow.org/?npc=3111#drop
Quest: https://database.turtle-wow.org/?quest=837

**Expected behavior. Describe how it should work:**
Kills should be counted towards quest completion..

**Comment by ratkosrb** [comment]
Cannot reproduce the problem. Quest progress is properly tracked when killing the mobs. Make sure you are not in a raid group.


https://github.com/slowtorta/turtlewow-bug-tracker/assets/35845488/f995a00e-53c9-4fce-8ce9-d1f73f6dbc5f
