### ISSUE TITLE
Southshore Shadowy Assassin event still not fixed

### ISSUE THREAD

**Issue by Lightsentinel** [slowtorta/turtlewow-bug-tracker#5267]
**Please, provide a clear description what the bug is:** 
The event which is supposed to spawn Shadowy Assassin's in Southshore is currently bugged and hasn't been fixed despite several requests from the community over the past few years, both on Github and Discord. GM's used to place the item that the Shadow Assassin's drop(Assassin's contract) in your inventory, but due to the spike in server population they no longer provide that service. As such it is impossible to do the Baron Vardus quest chain. Although I am, and will continue to be highly appreciative of the hard work the Turtle WoW dev's have done, vanilla content should be fully functioning after half a decade online. 

If fixing the event requires too much work, then an alternative should be offered. For example a permanently lootable Shadowy Assassin corpse guarded by Southshore Guard's. In practice the corpse would be a container on a fast respawn which contains the Assassin's Contract.

**Steps to reproduce the behaviour with as much detail as possible:**
Wait in Southshore for the Southshore Crier to announce the event in /yell (this normally takes place around 15-20 minutes past the hour)
Shadowy Assassin's do not spawn whatsoever, either in Blizz-like locations or in any visible custom locations.
The Southshore Crier just stands outside the Inn for about ten minutes after announcing the attack.
As the Shadowy Assassin's do not spawn, the Assassin's Contract item cannot be looted to begin the quest chain of the same name which leads to killing Baron Vardus in Alterac Mountains.

**IDs of affected creatures, items, quests or spells with a link to the relevant page:**
NPC: https://database.turtle-wow.org/?npc=2435
NPC: https://database.turtle-wow.org/?npc=2434
Item: https://database.turtle-wow.org/?item=3668
Quest: https://database.turtle-wow.org/?quest=522

**Expected behaviour. Describe how it should work:**
The Shadowy Assassin's should spawn in multiple locations across the town, including behind the town hall, behind the inn and next to the cattle field. If memory serves me right, some also spawn inside the town hall to attack Henry Maleb(their target). They should spawn in groups of at least 3 so that players get a chance to kill them before the guards finish them all off.

**Comment by twowTurtReynolds** [comment]
Yep, this one is on the radar. Thanks for the detailed info though, I'm appending this to https://github.com/slowtorta/turtlewow-bug-tracker/issues/3675
