### ISSUE TITLE
Cant enchant my item

### ISSUE THREAD

**Issue by Wilsonsds** [slowtorta/turtlewow-bug-tracker#5269]
**Please, provide a clear description what the bug is:**

**Steps to reproduce the behavior with as much detail as possible:**

1. i got the [Darkflame Helm] and it is equipped
2. Then i complete the quest and recieved [Invocation of Shattering]
3. Now i cant enchant [Invocation of Shattering] in my equipped helmet.

**IDs of affected creatures, items, quests or spells with a link to the relevant page:**

NPC: https://database.turtle-wow.org/?npc=
Item: https://database.turtle-wow.org/?item=
Quest: https://database.turtle-wow.org/?quest=
Spell: https://database.turtle-wow.org/?spell=
Object: https://database.turtle-wow.org/?object=

**Expected behavior. Describe how it should work:**

**Comment by Wilsonsds** [comment]
Character Lusiena from the PVE main server

**Comment by Wilsonsds** [comment]
When i try to enchant it, i have the error message : "That item is not a valid target"

But it is a head slot item

**Comment by twowTurtReynolds** [comment]
https://github.com/slowtorta/turtlewow-bug-tracker/issues/4788 is a pinned issue, please read those before creating duplicates.
