### ISSUE TITLE
In Deadmines, the last door before the ship triggers the event even if not blasted

### ISSUE THREAD

**Issue by octav3k** [slowtorta/turtlewow-bug-tracker#5271]
**Please, provide a clear description what the bug is:**
In the Deadmines, the last door before the ship, when opened, triggers Mr. Smite to yell at his pirate crew to "check out that noise" regardless of the way in which the door is opened.

**Steps to reproduce the behavior with as much detail as possible:**
1. Go into the Deadmines
2. Lockpick the door or open it with a skeleton key from Blacksmithing

**IDs of affected creatures, items, quests or spells with a link to the relevant page:**
Object: https://database.turtle-wow.org/?object=16398 (not sure of the ID of the door)

**Expected behavior. Describe how it should work:**
The event (yell + NPCs running towards the door) should only trigger if the cannon is used to blast open the door.

**Comment by Muigin** [comment]
Please upload video evidence of this occurring and reopen this ticket if you have it.  Cannot reproduce this, and have never personally encountered this issue with a Rogue in Deadmines for months.
