### ISSUE TITLE
Mage rank 1 Ice Armor buff reads grants 6 frost resistance, when it should say 7 in buff icon bar

### ISSUE THREAD

**Issue by reichardsc** [slowtorta/turtlewow-bug-tracker#5276]
**Please, provide a clear description what the bug is:**

**Steps to reproduce the behavior with as much detail as possible:**

1. Cast rank 1 Ice Armor buff on self
2. Read description of buff in buff area by hover over (shows grants 6 frost resistance)
3. Look in character sheet and see it grants 7 correctly

**IDs of affected creatures, items, quests or spells with a link to the relevant page:**

Spell: https://database.turtle-wow.org/?spell=7302

**Expected behavior. Describe how it should work:** Either read to say it gives 7, or actually give 6 to character as it reads.

**Comment by reichardsc** [comment]
This is with the 2/2 frost warding talent, so this is just a visual display bug in the buff wording.

**Comment by Muigin** [comment]
Is the tooltip on the spell icon itself incorrect, or is it the buff tooltip in the top right corner?  Buff tooltips do not update with talents in vanilla.  As long as the spell description itself conveys the correct information, this is Working as Intended.

**Comment by reichardsc** [comment]
Buff tooltip

**Comment by Muigin** [comment]
> Buff tooltip

Working as intended.
