### ISSUE TITLE
Item invocation of Expansive Mind does not work.

### ISSUE THREAD

**Issue by Anemoneu** [slowtorta/turtlewow-bug-tracker#5277]
**Please, provide a clear description what the bug is:**

**Steps to reproduce the behavior with as much detail as possible:**

1. This Item unable to enchantment on my Leg part,  My leg part DOES NOT enchantment any other enchant before. 
2. This issue happens in Sea-server, Ravenshire.

**IDs of affected creatures, items, quests or spells with a link to the relevant page:**

item: https://database.turtle-wow.org/?item=92007

**Expected behavior. Describe how it should work:**

**Comment by Muigin** [comment]
#4788
