### ISSUE TITLE
Items "Gadgetzan Times Issue" Make this items "Junk"

### ISSUE THREAD

**Issue by hokagegaara** [slowtorta/turtlewow-bug-tracker#5278]
Make this items "Miscellaneous: Junk"(Poor) since they are not needed for anything.

https://database.turtle-wow.org/?item=51006 Gadgetzan Times Issue #1
![изображение](https://github.com/slowtorta/turtlewow-bug-tracker/assets/7520527/ce1f1332-b9c2-4e11-b36d-b4fa5385ef0a)

Remove "Quest" tag.
https://database.turtle-wow.org/?item=60661 Gadgetzan Times Issue #2
![изображение](https://github.com/slowtorta/turtlewow-bug-tracker/assets/7520527/a5f1b78e-986d-41d6-9f50-75aa93aa7738)

**Comment by twowTurtReynolds** [comment]
There is plenty of prescedent for 1.12 blizzard quests to have left you with a useless flavor item of common quality. Off the top of my head: https://www.wowhead.com/classic/item=5505/teronis-journal
