### ISSUE TITLE
blackwood fruit stores dont spawn a group of furbolgs when looted

### ISSUE THREAD

**Issue by geojak** [slowtorta/turtlewow-bug-tracker#528]
**Please, provide a clear description what the bug is:**

when doing the blackwood corrupted quest in darkshire and looting the 3 barrels in the blackwood camp for the 3 ingredient, each time when looting a group of furbolgs should spawn and attack the player.

**Steps to reproduce the behavior with as much detail as possible:**

1. get the blackwood corrupted quest in darkshire
2. go to the camp and loot the 3 ingredients
3. observe the behaviour that doesnt refelct classic

**IDs of affected creatures, items, quests or spells with a link to the relevant page:**

NPC: https://database.turtle-wow.org/?npc=
Item: https://database.turtle-wow.org/?item=
Quest: https://database.turtle-wow.org/?quest=
Spell: https://database.turtle-wow.org/?spell=
Object: https://database.turtle-wow.org/?object=

**Expected behavior. Describe how it should work:**

group of furbolgs spawn on lot

**Comment by slowtorta** [comment]
Duplicate: https://github.com/slowtorta/turtlewow-bug-tracker/issues/905

**Comment by geojak** [comment]
Hello, I would like to point out that the two issues are not 100% duplicates.

My issue is about looting the 3 barrels and no firbolgs spawbing
The other issue is about the final event when you use the ingredients to summon the satyr
