### ISSUE TITLE
invocation of shattering not for head slot and leg slot bug?!

### ISSUE THREAD

**Issue by infinatis13** [slowtorta/turtlewow-bug-tracker#5282]
**Please, provide a clear description what the bug is:**
invocation of shattering says adds 75 armor penetration permanently to legs or head slot which it does not you get that item is not a valid target
**Steps to reproduce the behavior with as much detail as possible:**

1.Left click on invocation of shattering
2. Right click to apply on Giantstalker's legging
3. That item is not a valid target

**IDs of affected creatures, items, quests or spells with a link to the relevant page:**

NPC: https://database.turtle-wow.org/?npc=
Item: https://database.turtle-wow.org/?item=invocation of shattering-ID=32831 Giantstalker's legging-ID=32029
Quest: https://database.turtle-wow.org/?quest=
Spell: https://database.turtle-wow.org/?spell=
Object: https://database.turtle-wow.org/?object=

**Expected behavior. Describe how it should work:**
Left click on invocation of shattering and then right click on Giantstalker's legging it will add 75 armor penetration to legs
you should be able to apply it to a helm the same way as well

**Comment by cyaohiri** [comment]
See #4788.

**Comment by infinatis13** [comment]
> See #4788.

thanks for the link
