### ISSUE TITLE
Macro Stopped Working with 1.17

### ISSUE THREAD

**Issue by 8EightySixed6** [slowtorta/turtlewow-bug-tracker#5283]
**Please, provide a clear description what the bug is:**

Macro: /Script SpellStopCasting(); CastSpellByName("Earth Shock")

Patch 1.16 I was able to run this macro with no issues. It would immediately stop casting any spell and cast Earth Shock.

Pre-Patch 1.17 I was able to use this macro to stop casting lightning bolt and immediately cast Earth Shock. Since 1.17 it has stopped working. Has something changed? Is this by design?

**Steps to reproduce the behavior with as much detail as possible:**

1. Create Macro listed above
2. Start casting Lightning Bolt
3. Run Macro

**IDs of affected creatures, items, quests or spells with a link to the relevant page:**

Spell: https://database.turtle-wow.org/?spell=403
Spell: https://database.turtle-wow.org/?spell=8042

**Expected behavior. Describe how it should work:**

Expected behavior should be a immediate stop of lightning bolt and instant cast Earth Shock. Currently I have to hit the macro twice for it to work. Once to have it stop Lightning Bolt and second time to cast Earth Shock.

**Comment by twowTurtReynolds** [comment]
Please disable all addons, then try again. I would appreciate video footage showing you have no addons on, no mods, and show us the macro screen, and the problem in effect.

**Comment by 8EightySixed6** [comment]
[https://drive.google.com/drive/folders/1_y74n35LA4M8i7objnh8Ac0ZmT2_Y1Fc?usp=sharing](url)

I have uploaded a video to Google Drive. Full Access to anyone who wants to view. 

I disabled all addons, showed disabled addons.
I have no HD pack or anything else installed.

I have showed the macro modified 3 different ways all with the same output.

**Comment by twowTurtReynolds** [comment]
Perfect, thank you! I will investigate.

**Comment by cyaohiri** [comment]
The macro works as long as you wait for the GCD after starting to cast the first spell.

**Comment by 8EightySixed6** [comment]
@cyaohiri It's not something I had to wait for pre 1.17. It would just stop casting the current spell casting and cast Earth Shock. 

Is it possible to change the way the GCD works with Earth Shock?

**Comment by cyaohiri** [comment]
I've tested this in a fresh 1.12.1 client, and when I start casting anything, Earth Shock is put on a 1.5s GCD, along with everything else, so I have to wait for that before the macro will work in a single click.

**Comment by twowTurtReynolds** [comment]
I dont believe that starting a cast, canceling it, and casting something else, should have a GCD's wait inbetween them? Like for example, strafing to cancel and recast healing on patchwerk. Is this a behavior specific to lightning bolt in 1.12?

**Comment by cyaohiri** [comment]
You are right. This isn't about GCD after all. It's like the server needs to acknowledge that you stopped casting before letting you cast, and that happens after you've already run your macro, so it fails on the first click.

**Comment by twowTurtReynolds** [comment]
I believe https://github.com/namreeb/nampower fixes this kind of issue for players? In general it makes the client force through requests to cast spells, even when the 1.12 client doesn't think it is allowed to.

 @8EightySixed6 give this mod a try and see if it makes this issue not a problem.

**Comment by cyaohiri** [comment]
I'm not seeing any difference on a local server. I think that mod only helps if you have high latency, for channeling and casting spells. It won't help with the GCD that doesn't get cleared quickly enough.

**Comment by 8EightySixed6** [comment]
@twowTurtReynolds  @cyaohiri  I have tried with nampower enabled and removed. Same result with it and without it.

**Comment by twowTurtReynolds** [comment]
Thanks, so nampower is out for this one, that's a shame.

At this point I think we will need to test, on latest vmangos, to see if this is lightning bolt specific. Lets see if a mage can start a fireball, cancel it and cast a blast. Or a shadowbolt cancel dot. Starfire cancel moonfire. See if this is consistent across all casters.

We should also try to find 2006 footage of how this should work, until its clear if this is a actually even a bug or intended design or not.

**Comment by 8EightySixed6** [comment]
Let me level and a mage and warlock and do some testing for ya! I will make a video of each class. No addons, no mods ect..

**Comment by cyaohiri** [comment]
I just tested on a mage, and it behaves the same as it does with Earth Shock. Double click required, unless you wait for the GCD.

**Comment by 8EightySixed6** [comment]
@cyaohiri @twowTurtReynolds  I can confirm the same on the Warlock as the mage.

I guess now I have more questions as to why it worked before and now. What has changed?

Last question, can it be modified to allow it work without the GCD? Can the cooldowns be different?

**Comment by twowTurtReynolds** [comment]
Were these tests on vmangos? Thats what we need to find out here, the big thing being that vmangos and turtle are consistent, and that both projects are based on blizzlike functionality.

**Comment by cyaohiri** [comment]
I tested it on a 2021 VMaGOS repack and on Turtle WoW. Same behaviour.

**Comment by twowTurtReynolds** [comment]
Thank you both for the work. I'm sorry Eighty but it just looks like this is both blizzlike and has been the case on turtle and vmangos for at least a while now, and it looks like your memory was mistaken on it being otherwise. 

If we can find 2006 footage proving different behavior, I would suggest opening a new ticket on vmangos/core and reference this one.
