### ISSUE TITLE
Can't see any in game give chat

### ISSUE THREAD

**Issue by Kornjacha88** [slowtorta/turtlewow-bug-tracker#5286]
Hello, I can't see any in game chat since I change that script thing from 48 to 0, I have a new updated pfQuestie
**Steps to reproduce the behavior with as much detail as possible:**

1.
2. 
3. 

My in game toon name is Blackgeorge

NPC: https://database.turtle-wow.org/?npc=
Item: https://database.turtle-wow.org/?item=
Quest: https://database.turtle-wow.org/?quest=
Spell: https://database.turtle-wow.org/?spell=
Object: https://database.turtle-wow.org/?object=

**Expected behavior. Describe how it should work:**

**Comment by Kornjacha88** [comment]
I have deleted my WDB folder

**Comment by twowTurtReynolds** [comment]
Please do not make bug reports for your technical support. See support of whoever made the software you are having trouble with.
