### ISSUE TITLE
Patch of Elemental Water only exists in Lapidis. Azhara spawns gone

### ISSUE THREAD

**Issue by roguestep16** [slowtorta/turtlewow-bug-tracker#5287]
Same as old Ticket..
https://github.com/slowtorta/turtlewow-bug-tracker/issues/5200

I checked the Screenshot from the GM and see that he is in Lapidis Isle.
So i went there and see the Patch of pure Water.. so every thing is fine..
BUT:  did u checked any spawn in Azshara.. there should be 6 spawns...
i am farmin there now for 1 and a half week.. there ar no patch of pure water in Azshara
1.
2. 
3. 
https://database.turtle-wow.org/?object=180753

**Comment by twowTurtReynolds** [comment]
This is a different issue so don't worry, its okay to have this new report.

**Comment by twowTurtReynolds** [comment]
Indeed, `.go object id 180753` only takes me to Lapidis isle.
