### ISSUE TITLE
My remote mail terminal disappeared

### ISSUE THREAD

**Issue by seraphxn** [slowtorta/turtlewow-bug-tracker#5288]
**Please, provide a clear description what the bug is: My remote mail terminal disappeared

**Steps to reproduce the behavior with as much detail as possible:**

1.Submitted a ticket to request a return of Pandaren Phantom Turtle Coins, but the remote email terminal was lost.
**IDs of affected creatures, items, quests or spells with a link to the relevant page:**

Item: https://database.turtle-wow.org/?item=50011

**Expected behavior. Describe how it should work:**
 I am a player on the Asian server Hogg server. I donated turtle coins on the official website of the Asian server and purchased Remote Mail Terminal and Illusion of Pandaren in the game. At that time, I submitted a work order to apply for the return of Illusion of Pandaren. Turtle Coin, but my Remote Mail Terminal disappeared, and the Turtle Coin was not returned. I submitted a work order again and the customer service response asked me to go to the Ratchet City NPC to retrieve it. However, there was no Remote Mail Terminal on the NPC store page, and the Turtle Coin was not returned. I submitted a work order many times but the GM did not respond or handle it. My server is: Asian server Hogg server. Asian server account: rufeng. In-game character name: 爱吃小饼干.
My current request is to return turtle coins to my account or help find it. Return to remote mail terminal
Hope to get your reply and deal with it as soon as possible, thank you

**Comment by twowTurtReynolds** [comment]
Please contact a GM the same way you have been. This doesn't belong in the bug reports.

**Comment by seraphxn** [comment]
但是GM让我过来提交BUG 也不处理
