### ISSUE TITLE
Ironhide Devilsaur in Un'goro crater

### ISSUE THREAD

**Issue by KniightYz** [slowtorta/turtlewow-bug-tracker#529]
**Please, provide a clear description what the bug is:**

The Ironhide Devilsaur is bugged, and was seen charging across the map *Un'Goro* (or visible screen area) in super speed.

The animation was bugged, where it was gliding and not walking (I had target of target on and the Devilsaur didn't have a target selected). This mob seemed to travel at an unusual speed and was clearly bugged.

I was fighting something nearby and the Devilsaur seemed to yo-yo back to its normal path and then killed me which would be an unfair death to someone on Hardcore mode.

-To note my internet connection at this time was stable

**Steps to reproduce the behavior with as much detail as possible:**

1. None, the mob seemed to do this on its own accord and was seen to do this more than once (I was questing in this zone)
2. 
3. 

**IDs of affected creatures, items, quests or spells with a link to the relevant page:**

NPC: https://database.turtle-wow.org/?npc=6499

Item: https://database.turtle-wow.org/?item=
Quest: https://database.turtle-wow.org/?quest=
Spell: https://database.turtle-wow.org/?spell=
Object: https://database.turtle-wow.org/?object=

**Expected behavior. Describe how it should work:**

Slow moving, stomping T-Rex type of Dinosaur

**Comment by Rakura1** [comment]
Can confirm saw it happen yesterday. Seems to occur at end of path and instead of pathing back he glitch runs back to start of it.

**Comment by geojak** [comment]
Saw it happen close to the eastern crystal pillaw, just across the river

**Comment by slowtorta** [comment]
Kruxis said he fixed it. Please re-open if this is still happening!
