### ISSUE TITLE
Quest "In Eranikus' Own Words" inaccessible to goblins

### ISSUE THREAD

**Issue by UnseenMystic** [slowtorta/turtlewow-bug-tracker#5298]
**Please, provide a clear description what the bug is:**
After turning in id:3374 "The Essence of Eranikus", Itharius doesn't give a followup quest in the title (id: "3512") on my goblin rogue lvl56 Theburger.
On the DB it also doesn't list goblins as an eligible race for the quest.
**Steps to reproduce the behavior with as much detail as possible:**

1. Be goblin
2. Complete first "The Essence of Eranikus" quest id:3373
3. Complete second "The Essence of Eranikus" quest id:3374
4. Itharius doesn't have any new quests to give

**IDs of affected creatures, items, quests or spells with a link to the relevant page:**

NPC: https://database.turtle-wow.org/?npc=5353
Item: https://database.turtle-wow.org/?item=10455
Quest: https://database.turtle-wow.org/?quest=3512
Spell: https://database.turtle-wow.org/?spell=
Object: https://database.turtle-wow.org/?object=

**Expected behavior. Describe how it should work:**
I turn in my trinket and he gives me quest id:3512

**Comment by twowTurtReynolds** [comment]
Indeed, we can see on the DB that the prerequisite quest says ALL races, and this one covers all 9 but Goblin.
