### ISSUE TITLE
Rude Awakening

### ISSUE THREAD

**Issue by Pangoken** [slowtorta/turtlewow-bug-tracker#53]
By opening this Issue, I admit to having done the pertinent research using sources from Vanilla (preferably) or Classic. I also understand that sources from other private servers are not acceptable.

**Current behavior**: 
The quest Rude Awakening is available to every race.

**Expected behavior**: 
The quest Rude Awakening is available to undead
 only.

**Proofs**:
https://classic.wowhead.com/quest=363/rude-awakening
![buszu](https://user-images.githubusercontent.com/50700937/122110945-70ff0000-ce1f-11eb-8d24-75f946b4db72.png)

**Steps to reproduce**:

1. Interact with Undertaker Mordo

**Comment by gheor7** [comment]
Mate I strongly believe this is intended because gray quests still give full experience.
Why race lock starting zone quests?
What if a guy flys from Durotar to level with his Undead friend.

**Comment by Vikkyne** [comment]
So I do believe the game just had that quest for Undead as part of their intro. The other quests in the chapel could be picked up by other races, but not this one. It is about story, that is all. I've never seen it open to other races before.

**Comment by slowtorta** [comment]
Thanks for reporting it. It's fixed and will be deployed on the next server update.
