### ISSUE TITLE
Quest: A New Rune-Frontier removes sword from inv

### ISSUE THREAD

**Issue by Aubreykun** [slowtorta/turtlewow-bug-tracker#5302]
**Please, provide a clear description what the bug is:** 
For the quest "A New Rune-Frontier" offered by Craftsman Wilhelm at Light's Hope Chapel, he asks you to craft an [Untempered Runeblade]. However, upon completion of the quest, the blade you have - whether it's equipped or not - is removed from your inventory. There is no indication that Wilhelm actually wants you to GIVE him the sword, and the rest of the questline is moreso about you collaborating with him on tempering the blade you already have. Multiple people have stated that this is bugged and requires a GM restoration of the item.

This sword is made via a very material-expensive process, using a pattern that drops from the end boss of Live Strat, and the stats of the sword are such that someone would craft it to use as-is. It's very possible that someone may even make the runeblade before getting to Light's Hope or seeing Wilhelm's quest, sell their old weapon, enchant the runeblade, and then lose it from the turn-in.

**Steps to reproduce the behavior with as much detail as possible:**

1. Obtain [Plans: Untempered Runeblade] off of killing Balnazzar (or the AH, if any are up)
2. Craft the [Untempered Runeblade]
3. Accept the quest "A New Rune-Frontier" from Craftsman Wilhelm at Light's Hope Chapel
4. Turn in the quest
5. See how your [Untempered Runeblade] is now missing.

**IDs of affected creatures, items, quests or spells with a link to the relevant page:**

NPC: https://database.turtle-wow.org/?npc=16376
Item: https://database.turtle-wow.org/?item=60293
Quest: https://database.turtle-wow.org/?quest=40234

**Expected behavior. Describe how it should work:**

EITHER:
A: Simply having the sword should allow the quest to be completed, it should not be removed from your inventory.

B: If this behavior is (for some insane reason) intended: Have Wilhelm state that he wants you to GIVE HIM an untempered runeblade so that he can study it. "If you can get your hands on an untempered runeblade and see it in your heart to donate it to the cause so I can study it[...]" or some similar line. The objective should also be changed from "Craft an Untempered Runeblade, and return to Craftsman Wilhelm. " to "Bring Craftsman Wilhelm an Untempered Runeblade." to make it fall in line with the format of other Blacksmithing quests. Adding a "NOTE: Wilhelm will need to hold onto the runeblade to study it.", and possibly a confirmation box of "Hand over your Untempered Runeblade?"

**Comment by twowTurtReynolds** [comment]
After convening with the staff, this will not be changed. Take care in unfamiliar quests and read them :)

**Comment by Aubreykun** [comment]
> After convening with the staff, this will not be changed. Take care in unfamiliar quests and read them :)

The quest has no indication as-written that he will take the sword, hence my pair of suggestions on what to do to fix it at the bottom. It's unclearly written.

**Comment by cyaohiri** [comment]
This could be fixed by making the next quest give you the sword back upon accepting it.

**Comment by twowTurtReynolds** [comment]
It is implied with the quest text. For further discussion, seek the suggestions forum.
