### ISSUE TITLE
Quest bug - Thadius Grimshade (https://database.turtle-wow.org/?quest=2990)

### ISSUE THREAD

**Issue by tutayanova** [slowtorta/turtlewow-bug-tracker#5306]
[Gryphon Master Talonaxe](https://database.turtle-wow.org/?npc=5636) dont give quest item. 

Can't finish quest, because i dont have quest item for [Thadius Grimshade](https://database.turtle-wow.org/?npc=8022)

Show bug: https://youtu.be/G3m6uzA2s-w

**Comment by tutayanova** [comment]
I can stream in discord if u need.

**Comment by cyaohiri** [comment]
Did you check if the item is in your bank?

**Comment by tutayanova** [comment]
problem solved.
i check bank, but i dont remember how he get there.
Sorry, I was in a hurry and dont check everything.
