### ISSUE TITLE
small Wildfeather Bracers issue

### ISSUE THREAD

**Issue by gorxen** [slowtorta/turtlewow-bug-tracker#5307]
**Please, provide a clear description what the bug is:**

Item: https://database.turtle-wow.org/?item=61321

**Expected behavior. Describe how it should work:**

Makes mail armor-like sounds when manipulated, equipped, moved, etc. but it's a leather item.

**Comment by twowTurtReynolds** [comment]
Thank you for the attention to detail on the little things like this. Helps reinforce our goal of reaching blizzard quality.

**Comment by Dragunovi** [comment]
Should be fixed in the next scheduled server restart.
