### ISSUE TITLE
Ancient Stone Keeper: Sand Storms issue

### ISSUE THREAD

**Issue by gorxen** [slowtorta/turtlewow-bug-tracker#5308]
**Steps to reproduce the behavior with as much detail as possible:**

1. Engage uldaWOMAN boss "Ancient Stone Keeper"
2. wait for him to cast Sand Storms

**Expected behavior. Describe how it should work:**

The sand storms chase people insanely fast compared to how it should actually be. Feel free to check this video so u can compare: [https://www.youtube.com/watch?v=9aMeyT_kcEw](https://www.youtube.com/watch?v=9aMeyT_kcEw)

**Comment by cyaohiri** [comment]
On VMaNGOS, their speed is 3 yd/sec, which is ~42% of your running speed. It's hard for me to say how that speed compares to the one in the video.

**Comment by twowTurtReynolds** [comment]
Indeed, on both vmangos and PTR they seem to just run at normal mob speed. And on second look, I see the same on the video. If you could be more specific as to how they are supposed to work, please let us know.
