### ISSUE TITLE
ranged npc behaviour, and behavour when rooted

### ISSUE THREAD

**Issue by geojak** [slowtorta/turtlewow-bug-tracker#531]
**Please, provide a clear description what the bug is:**

npcs with ranged attacks try to disengange from meele combat. on vmangos it seems they actively get into meele by themself. 

another similiar issue, if the players frost novas a mob that he has aggro on and then steps away, the mob wont retarget another player that is in range for his meele attack, which they should in classic or tbc. instead the mob just stares at the player that he has aggro on that is now not in range and doesnt not attack anyone, even the ones he could reach while being rooted.

**Expected behavior. Describe how it should work:**

actively try to get out of range to use their gun/cast when the play doesnt gers rooted, stunned or knockdowned.

edit: the issue got a bit reworked, belows comment has some video proof.

fixing this would make the game at little bit more interesting and challenging to play in a fun way

**Comment by LeopoldHock** [comment]
No net ability according to wowhead classic: https://classic.wowhead.com/npc=3382/southsea-cannoneer#abilities

**Comment by geojak** [comment]
yeah, i also checked and it seems i am wrong about the net.  watcehd all the barren qeusts on youtube i could find but a video proof of the behavoiur i remeber wasnt htere.

i will close the issue

**Comment by geojak** [comment]
i found a similiar npc behaviour video proof:
https://www.youtube.com/watch?v=I6x6513msec
check at 10:10-10:20
the warrior gets netted by a troll hunter and the troll caster the is atacting is stepping away to cast

this is the behavious i mean.

i was wrong about the piraves having nets, they only have a knockdown, but they should still use the same behaviour.

that is if the npc has a ranged attack and the players gets stunned or rooted, then step away and attack form range

**Comment by geojak** [comment]
the rare spawn slave master blackheart in saeing gourge has the correct behavour of netting and getting out of range.

**Comment by Megamagepal** [comment]
> if the players frost novas a mob that he has aggro on and then steps away, the mob wont retarget another player that is in range for his meele attack
I don't recall the behavior before the most recent update, but this was fixed, when my mage friend frost novas an npc and walks out of range it will start attacking me the melee user
