### ISSUE TITLE
The head of Ossirian the Unscarred disappeared after being allocated and did not appear in the designated person's backpack, and the system also did not display any allocation information.

### ISSUE THREAD

**Issue by Edroland94** [slowtorta/turtlewow-bug-tracker#5313]
**Please, provide a clear description what the bug is:**
I am a veteran player of World of Warcraft and I have encountered a bug in the game that I would like to report to the GM team. The issue is as follows:
**Steps to reproduce the behavior with as much detail as possible:**
When I was raiding the Ruins of Ahn'Qiraj with my teammates, we encountered a bug during the final boss, Viscidus. 
1.All the other loot had been distributed, and only Viscidus' head remained. 
2.I won the roll for the Head of Ossirian the Unscarred, and the raid leader confirmed on voice chat that it had been assigned to me. 
3.However, the item did not appear in my inventory, and there was no chat message indicating that the item had been assigned to me. Other members of the raid also confirmed that they did not see any loot distribution message. 
4.At this point, the boss's corpse no longer had a prompt to loot the item, indicating that the item had disappeared inexplicably.

**IDs of affected creatures, items, quests or spells with a link to the relevant page:**

NPC: https://database.turtle-wow.org/?npc=
Item: https://database.turtle-wow.org/?item=21220
Quest: https://database.turtle-wow.org/?quest=
Spell: https://database.turtle-wow.org/?spell=
Object: https://database.turtle-wow.org/?object=

**Expected behavior. Describe how it should work:**
Under normal circumstances, the raid leader allocated the item, and according to the rules of the rolling system, the item should have been placed in my backpack after being assigned to me, but it has now disappeared.

**Comment by Edroland94** [comment]
the RAID  ID is  1953，RAID name is Ahn'Qiraj Ruins。RAID time  is 2023/11/19 pm8-9 maybe

**Comment by twowTurtReynolds** [comment]
Please contact a GM about this issue, if you haven't already. A GM can reopen this report with a log of proof that this happened if there is something we can look into.
