### ISSUE TITLE
Alterac Valley PvP "trophy" quests aren't giving experience at repetable stage

### ISSUE THREAD

**Issue by istrizhakov** [slowtorta/turtlewow-bug-tracker#5318]
**Please, provide a clear description what the bug is:**
Hello,
Following quests in Alterac Valley aren't give any experience points:
Alliance:
https://database.turtle-wow.org/?quest=7428
https://database.turtle-wow.org/?quest=7424
https://database.turtle-wow.org/?quest=7426
https://database.turtle-wow.org/?quest=7425
Horde:
https://database.turtle-wow.org/?quest=7427
https://database.turtle-wow.org/?quest=7423
https://database.turtle-wow.org/?quest=7422
https://database.turtle-wow.org/?quest=7421

This quests should give a 1900 Experience each turn in

**Steps to reproduce the behavior with as much detail as possible:**

1. Complete any pre-qeusts and then complete any of following repeatable quest from list above

**IDs of affected creatures, items, quests or spells with a link to the relevant page:**

https://database.turtle-wow.org/?quest=7428
https://database.turtle-wow.org/?quest=7424
https://database.turtle-wow.org/?quest=7426
https://database.turtle-wow.org/?quest=7425
https://database.turtle-wow.org/?quest=7427
https://database.turtle-wow.org/?quest=7423
https://database.turtle-wow.org/?quest=7422
https://database.turtle-wow.org/?quest=7421

**Comment by Muigin** [comment]
Repeatable quests which have a one-time experience reward never grant EXP for all subsequent completions.  This has always been the behavior of Blizzlike repeatable quests.

Working as intended.

**Comment by cyaohiri** [comment]
> Repeatable quests which have a one-time experience reward never grant EXP for all subsequent completions. This has always been the behavior of Blizzlike repeatable quests.

A notable exception is this quest, which gives experience every time, and is repeatable indefinitely. https://www.wowhead.com/classic/quest=2881/troll-necklace-bounty
