### ISSUE TITLE
NPC: Crimson Lynx

### ISSUE THREAD

**Issue by cyaohiri** [slowtorta/turtlewow-bug-tracker#5323]
Crimson Lynx have too low armor value. They are level 10, but have only 20 armor, compared to [Mountain Boar](https://database.turtle-wow.org/?npc=1190), which has 538 armor.

NPC: https://database.turtle-wow.org/?npc=80250

**Comment by twowTurtReynolds** [comment]
TWoW isn't strictly following 1.12 armor value standards as you can see in our custom zones, but this here looks to be a wildly incorrect value.

**Comment by twowTurtReynolds** [comment]
The staff will not be changing this.
