### ISSUE TITLE
Beastmaster`s Gloves Dungeonset 2 +1% Hit Not Working

### ISSUE THREAD

**Issue by Muppets99** [slowtorta/turtlewow-bug-tracker#5324]
As you can see the hunter gloves from the D2 - Set dont provide any +hit on the char. it also says for some reason "use" on the gloves that might be the reason  to not work 
![BUG](https://github.com/slowtorta/turtlewow-bug-tracker/assets/151680508/c8235b57-bc01-4670-87dc-37dfee2f9e80)

**Comment by cyaohiri** [comment]
See #5225.

**Comment by twowTurtReynolds** [comment]
Indeed, should be fixed with the restart tonight. If not, let me know.
