### ISSUE TITLE
Greymane Armor Doesn't Appear to Return Damage as Health

### ISSUE THREAD

**Issue by Denten93** [slowtorta/turtlewow-bug-tracker#5325]
**Please, provide a clear description what the bug is:**
The Greymane Armor set from Gilneas City has multiple pieces that, on equip, return a set percentage of damage dealt to you as healing. When I initially had only the Greymane Shoulders, I would notice a purple effect on my character when dealing damage, along with a health gain over my character's portrait. Now however, I notice no effect and no health gain, neither over the portrait nor in the combat log, despite having the entire set. Others seem to report the same issue when asked in world chat.

**Steps to reproduce the behavior with as much detail as possible:**

1. Equip Greymane Armor set
2.  Deal damage, both through melee auto attacks and spells
3. There is no apparent restoration of health

**IDs of affected creatures, items, quests or spells with a link to the relevant page:**

NPC: n/a
Item: https://database.turtle-wow.org/?item=61313   https://database.turtle-wow.org/?item=61324   https://database.turtle-wow.org/?item=61376   https://database.turtle-wow.org/?item=61378   https://database.turtle-wow.org/?item=61377   https://database.turtle-wow.org/?item=61379
Quest: n/a
Spell: n/a
Object: n/a

**Expected behavior. Describe how it should work:**
The items by themselves, along with the completed set, should restore a percentage of damage done to the wearer when worn. They currently do not appear to be doing so. In the past they worked.

**Comment by twowTurtReynolds** [comment]
Vampirism has since been changed to not only not show up on the combat log, but also no longer constantly make the healing sound and the healing numbers.

Use an addon that shows your exact HP values, and you will see the stat working as intended.
