### ISSUE TITLE
人物军阶达到血卫士后在荣誉大厅内无法购买对应军阶的鞋子和手套

### ISSUE THREAD

**Issue by Hetao616** [slowtorta/turtlewow-bug-tracker#5326]
**Please, provide a clear description what the bug is:**
人物军阶达到血卫士后在荣誉大厅内购买对应军阶的鞋子和手套是提示“你未达到军阶要求”
**Steps to reproduce the behavior with as much detail as possible:**

1.军阶达到血卫士
2. 在奥格瑞玛传说大厅购买血卫士的锁甲战靴、血卫士的锁甲护手
3. 提示“你未达到军阶要求”

**IDs of affected creatures, items, quests or spells with a link to the relevant page:**

NPC: https://database.turtle-wow.org/?npc=Lady Palanseer
Item: https://database.turtle-wow.org/?item=
Quest: https://database.turtle-wow.org/?quest=
Spell: https://database.turtle-wow.org/?spell=
Object: https://database.turtle-wow.org/?object=

**Expected behavior. Describe how it should work:**

**Comment by twowTurtReynolds** [comment]
请用英文提交问题。我们无法通过自动翻译准确地翻译中文提交的错误报告，这使得我们难以理解问题的确切性质。谢谢！

Please submit the issues in English. We're unable to accurately translate bug reports submitted in Chinese through automatic translation, which makes it difficult for us to understand the exact nature of the issue. Thank you!
