### ISSUE TITLE
Incorrect display of weapons for the Anqira Ruins Hunter mission

### ISSUE THREAD

**Issue by qingtianmy** [slowtorta/turtlewow-bug-tracker#5328]
Hello, I am a hunter player. When I completed the Ankara Ruins Hunter weapon mission, I found that the appearance of the weapon could not be displayed correctly. I think this is a bug. Please fix the problem. Thank you!

**Comment by Herdon** [comment]
Any screenshots maybe? Also use the template that is provided for bug repots

**Comment by qingtianmy** [comment]
Hello, the screenshot has been taken. The image cannot be displayed correctly in this location, and the WDB file has also been deleted.
![11](https://github.com/slowtorta/turtlewow-bug-tracker/assets/151704395/f796d27c-abbc-43e3-be13-881933498ad4)
![22](https://github.com/slowtorta/turtlewow-bug-tracker/assets/151704395/66d5d51d-1a7c-419e-8202-12d1c4106b90)

**Comment by twowTurtReynolds** [comment]
I see that https://github.com/slowtorta/turtlewow-bug-tracker/issues/5454 is a dupe. Please do not create duplicate issues.
