### ISSUE TITLE
Sudden Death in Desolace

### ISSUE THREAD

**Issue by SmolShai** [slowtorta/turtlewow-bug-tracker#5330]
**Please, provide a clear description what the bug is:**

Encountered a bug.
Was riding mount through Desolace and suddenly died. Had a very small fall off the hill with the vulture while riding. Was not in combat and had no connection issues.

![dead1](https://github.com/slowtorta/turtlewow-bug-tracker/assets/151705351/27b7ad56-9fb0-4fe0-a4a6-cd52333293f6)
![dead2](https://github.com/slowtorta/turtlewow-bug-tracker/assets/151705351/3461d297-6720-4fe7-8048-80e4bffdf038)

**Comment by twowTurtReynolds** [comment]
Related to:
 https://github.com/slowtorta/turtlewow-bug-tracker/issues/3954
https://github.com/slowtorta/turtlewow-bug-tracker/issues/4324
https://github.com/slowtorta/turtlewow-bug-tracker/issues/4742

**Comment by twowTurtReynolds** [comment]
![image](https://github.com/slowtorta/turtlewow-bug-tracker/assets/151180101/09c8190a-c7d9-436d-94c8-a8b91c6379d6)
If someone ever learns of a fix, it will be applied, I guarantee it.
