### ISSUE TITLE
My role's military rank is blood guard，but i can't buy blood guard equipment.

### ISSUE THREAD

**Issue by Hetao616** [slowtorta/turtlewow-bug-tracker#5331]
**Please, provide a clear description what the bug is:**
When i buy blood guard equipment,system prompt "your military rank isn't reach blood guard"
**Steps to reproduce the behavior with as much detail as possible:**

1.
2. 
3. 

**IDs of affected creatures, items, quests or spells with a link to the relevant page:**

NPC: https://database.turtle-wow.org/?npc=
Item: https://database.turtle-wow.org/?item=
Quest: https://database.turtle-wow.org/?quest=
Spell: https://database.turtle-wow.org/?spell=
Object: https://database.turtle-wow.org/?object=

**Expected behavior. Describe how it should work:**

**Comment by twowTurtReynolds** [comment]
![image](https://github.com/slowtorta/turtlewow-bug-tracker/assets/151180101/c023d533-f8ec-4e29-b345-9199f8eb34ae)
Works fine.
