### ISSUE TITLE
Cant loot Whipper Root Tubber on Tel'Abim

### ISSUE THREAD

**Issue by Grosdodo** [slowtorta/turtlewow-bug-tracker#5332]
**Please, provide a clear description what the bug is:**
In order to get Whipper Root Tuber, I used Cenarion Plant Salve on Corrupted Whipper Root.
The plant correctly goes uncorrupted but when I try to loot it, no loot window opens and the plant disappear.
Orc - hunter - Tel'abim realm

**Steps to reproduce the behavior with as much detail as possible:**
1. Get 3 Cenarion Plant Salve
2. Clic on a corrupted whipper root to clean it
3. Try to loot the cleaned whipper root

**IDs of affected creatures, items, quests or spells with a link to the relevant page:**
Item: https://database.turtle-wow.org/?item=11951
Quest: https://database.turtle-wow.org/?quest=4444

**Expected behavior. Describe how it should work:**
I should be able to loot whipper root tuber out of the cleaned plant

Best regards,
Grums

EDIT : I did try to delete the WDB folder ;)
EDIT 2 : Cleaned Whipper Root that I tried to loot disappear for a moment and reappear still clean (uncorrupted) but still "empty"

**Comment by Length123** [comment]
Did you get this to work?

**Comment by Orioh-L** [comment]
Hi ! Just adding on to this thread, I am having the same problem on the main PVE server too. The cleansing quest doesn't offer any reward, but still cleanses the root and uses the 3 salves. This makes obtaining legs/head enchants impossible at the time for players :/
