### ISSUE TITLE
奥金锭丢失

### ISSUE THREAD

**Issue by liuwenchao123** [slowtorta/turtlewow-bug-tracker#5337]
**Please, provide a clear description what the bug is:**
服务器：风暴烈酒
阵营： 联盟 
职业：圣骑士 
角色名：上任鹅城 
事件：背包丢失14块【奥金锭】10块【巨型绿宝石】
事件：北京时间2013.11.22 .20点左右 
**Steps to reproduce the behavior with as much detail as possible:**

1.邮件收取奥金锭后小退至任务选择界面等待后续邮件
2. 上线后收取后续邮件
3. 所有收取过的邮件又重新回邮箱并且奥金锭 和巨型绿宝石丢失

**IDs of affected creatures, items, quests or spells with a link to the relevant page:**

NPC: https://database.turtle-wow.org/?npc=
Item: https://database.turtle-wow.org/?item=
Quest: https://database.turtle-wow.org/?quest=
Spell: https://database.turtle-wow.org/?spell=
Object: https://database.turtle-wow.org/?object=

**Expected behavior. Describe how it should work:**

**Comment by icenwang** [comment]
你比我还惨
