### ISSUE TITLE
[Hunter][Stealth] Hunter Track Hidden does not reveal Fen Creepers

### ISSUE THREAD

**Issue by rptb1** [slowtorta/turtlewow-bug-tracker#534]
**Please, provide a clear description what the bug is:**

The Track Hidden ability of the hunter class does not reveal Fen Creepers before they attack at character level 26.  I am very certain it did on Vanilla, as I have clear memories if this quest.

**Steps to reproduce the behavior with as much detail as possible:**

1. Level a hunter to 26.
2. Train Track Hidden.
3. Activate it.
4. Go to the Wetlands.
5. Approach the location of a Fen Creeper.
6. Fen Creeper does not appear until it decides to attack.

**IDs of affected creatures, items, quests or spells with a link to the relevant page:**

NPC: https://database.turtle-wow.org/?npc=1040
Spell: https://database.turtle-wow.org/?spell=19885

**Expected behavior. Describe how it should work:**

In vanilla I was able to spot the Fen Creepers at enough distance to be out of combat and choose whether to fight them.  I am clear on this because it was the first time I applied Track Hidden in vanilla.

**Comment by rptb1** [comment]
It also fails to reveal [Bleakheart Shadowstalkers](https://database.turtle-wow.org/?npc=3770) three levels down.  I think it's just generally broken.

**Comment by rptb1** [comment]
I tested Track Hidden on a level 31 hunter with a level 26 rogue, and it did increase the detection distance by about 20%.  This seems weaker than I remember, but I can't say for certain.

**Comment by ratkosrb** [comment]
![Untitled](https://user-images.githubusercontent.com/35845488/199127478-4620cac8-4cb8-4a1e-b7e2-124b38041910.jpg)

It shows all stealthed Fen Creepers on the mini map correctly for me. They were using a wrong stealth aura though, so maybe fixing that will resolve the issue you were having.
