### ISSUE TITLE
Forceful radio and faulty music causing crashes

### ISSUE THREAD

**Issue by olisteph90** [slowtorta/turtlewow-bug-tracker#5340]
**Please, provide a clear description what the bug is:**

****The radio feature starts up on its own, usually preceded by a general freezing of the game that lasts about 10-30 seconds. I attempted to disable the radio, and re-enable music from the game settings. However, upon doing so the game freezes again and the radio starts up, disabling music in the process. If I leave music disabled the game functions fine, but personally I prefer to play with music on loop.**** 

EDIT: At one point it seemed the issue was resolved by leaving the zone (in this case Stormwind). However, upon returning to the city the freezing issue returns. In the last two circumstances the game completely freezes, and eventually crashes completely. When I reload the game the music option is once again disabled. My conclusion is that it is an issue with the music.

**Steps to reproduce the behavior with as much detail as possible:**

1. Enable music from settings with the option to loop music set to 'on'
2. After the predicted freeze of 10-15 seconds the music is disabled, and instead the radio is turned on.
3. Disable the radio from the radio widget on the mini-map, and either continue without any music, or trying the whole process again. 

**IDs of affected creatures, items, quests or spells with a link to the relevant page:**

NPC: https://database.turtle-wow.org/?npc=
Item: https://database.turtle-wow.org/?item=
Quest: https://database.turtle-wow.org/?quest=
Spell: https://database.turtle-wow.org/?spell=
Object: https://database.turtle-wow.org/?object=

**Expected behavior. Describe how it should work:**
It is self explanatory; something about the radio function is overriding the base functionality of the music. One should be able to listen to whichever.

**Comment by twowTurtReynolds** [comment]
Changes were made a few weeks ago to the radio system, and this seems fixed by that.
