### ISSUE TITLE
Rare Turtle Cranky Beng

### ISSUE THREAD

**Issue by Sianra** [slowtorta/turtlewow-bug-tracker#5341]
**Please, provide a clear description what the bug is:**
Hello. I was expecting turtle Crenky Benj https://www.wowhead.com/classic/npc=14223/cranky-benj#drops;mode:normal. Appearance (respawn) 20+ hours. She is rare and has an attack speed of 1.4 seconds. But it turned out that she was ordinary, like all the other turtles with an attack speed of 2.0. This is on the wow turtle server. Sorry for my English
**Steps to reproduce the behavior with as much detail as possible:**

1.
2. 
3. 

**IDs of affected creatures, items, quests or spells with a link to the relevant page:**

NPC: https://database.turtle-wow.org/?npc=14223
Item: https://database.turtle-wow.org/?item=
Quest: https://database.turtle-wow.org/?quest=
Spell: https://database.turtle-wow.org/?spell=
Object: https://database.turtle-wow.org/?object=

**Expected behavior. Describe how it should work:**
She is rare and has an attack speed of 1.4 seconds.

**Comment by CasualNerdity** [comment]
Not an issue. Cranky Benj has a 2.0 attack speed when tamed, the same as other turtles.
https://www.wow-petopia.com/classic/look.php?id=seaturtleskinred
