### ISSUE TITLE
The quest "A Meeting with the Master" is missing

### ISSUE THREAD

**Issue by Lichbanez** [slowtorta/turtlewow-bug-tracker#5342]
This quest seems to be missing, the NPC only gives the repeatable one also I was unable to drop the required feathers.

1. Go to Azshara
2. Find Sanath Lim-yo

NPC: https://database.turtle-wow.org/?npc=8395
Quest: https://database.turtle-wow.org/?quest=3381
Item: https://database.turtle-wow.org/?item=10450

The NPC should give this quest before the repeatable one everything about it is in the database but not in game. I don't know if it has been intentionally removed.

**Comment by Muigin** [comment]
Not a bug.

The quest description itself indicates that the original quest was deprecated by Blizzard and replaced with the repeatable.

https://wowpedia.fandom.com/wiki/A_Meeting_with_the_Master#Patch_changes
