### ISSUE TITLE
Corrupted Sand unique up to 250

### ISSUE THREAD

**Issue by Avery1337** [slowtorta/turtlewow-bug-tracker#5343]
**Please, provide a clear description what the bug is:**
Corrupted Sand is unique up to 250 should not be.  Corrupted Sand should stack to 250 instead of 200.
**Steps to reproduce the behavior with as much detail as possible:**

1. get 250 corrupted sand
2. try to put 1 more corrupted sand in the inventory
3. Can't get sand

**IDs of affected creatures, items, quests or spells with a link to the relevant page:**

Item: https://database.turtle-wow.org/?item=50203

**Expected behavior. Describe how it should work:**
It should be an unlimited amount of sand you can get without it capping at a certain point.  Sand usually stacked up to 200 but the recent forum post made it stack up to 250 which is listed here https://forum.turtle-wow.org/viewtopic.php?t=11833. 
 The sand doesn't even stack to 250 even when it said it did.  However it should not be unique to 250.

**Comment by Muigin** [comment]
This was caused by an oversight in database column names and a fix was written immediately. However, the fix cannot be applied until tonight's maintenance.
