### ISSUE TITLE
The server restarts the archive

### ISSUE THREAD

**Issue by kobewy08** [slowtorta/turtlewow-bug-tracker#5344]
**Please, provide a clear description what the bug is:**
 
After we hit the lower levels of the black stone tower, I was already in stormwind, taking off to return to the burning plains, but when the servers were rebooted, i've got the last boss Wim Salak's Cape and the third gemstone back on file, and I'd like to request a return of these two items. Thank you

**Comment by twowTurtReynolds** [comment]
Contact a GM if you haven't already. Do not submit bug reports for this kind of thing.
