### ISSUE TITLE
Traps do not appear in northern Duskwood

### ISSUE THREAD

**Issue by rptb1** [slowtorta/turtlewow-bug-tracker#535]
**Please, provide a clear description what the bug is:**

Hunter traps placed on the hillside in northern Duskwood do not appear and mobs do not trigger them.  The cooldown activates.  A short distance away, they work.

**Steps to reproduce the behavior with as much detail as possible:**

1. Make a hunter level 26.
2. Go to the hillside in northern Duskwood north of Raven Hill cemetary.
3. Place a trap. Note nothing appears on the ground. Note cooldown.
4. Pull a mob over it.  Nothing -- no resist, just misses.

Example location: 
![image](https://user-images.githubusercontent.com/419807/146343366-4f666d4a-4219-4c19-a437-02b387d07395.png)

**IDs of affected creatures, items, quests or spells with a link to the relevant page:**

Spell: https://database.turtle-wow.org/?spell=14302
Object: https://database.turtle-wow.org/?object=164872

**Expected behavior. Describe how it should work:**

The trap should appear on the ground and the mob should trigger it.

I suspect something is wrong with the ground and the trap is going underground or in the sky or something.

**Comment by zomgits** [comment]
Same problem here:
![image](https://user-images.githubusercontent.com/97355053/148862746-361f33c6-547b-4495-b5dd-f310e0f7dc2b.png)

**Comment by zomgits** [comment]
I have found more spots where this happens near Ironband's Tomb.  These are also spots where the camera likes to go crazy and point at the sky.

This does suggest the terrain is broken.  Are there upside-down triangles?

**Comment by zomgits** [comment]
Also here on the lake slope.
![image](https://user-images.githubusercontent.com/97355053/149925898-cc0326a5-8118-44ce-b25f-7ee2f2ebfff5.png)

**Comment by zomgits** [comment]
Also here at Raven Hill.  In this location, Bright Campfires vanish when placed, and mobs often turn 180 degrees and run away from you if you step a little to the left or right as they approach you.  This suggests the terrain triangles might be upside-down, if that's how they work.
![image](https://user-images.githubusercontent.com/97355053/152277106-78f9d814-e49c-408d-a6fa-5f1f6a4d1c7a.png)

**Comment by zomgits** [comment]
Here is a video of the bizarre pathing behaviour.
https://www.youtube.com/watch?v=Ehm1A5rf9ic

**Comment by Khanz0** [comment]
Same issue in searing gorge surface. When you cast a trap i think it goes underground

**Comment by slowtorta** [comment]
This is a client map issue, moving this to the internal tracker.

**Comment by slowtorta** [comment]
Possibly fixed or at least improved on the previous server update.
