### ISSUE TITLE
the missing enchant effect on the equipment

### ISSUE THREAD

**Issue by LO0PUNT1LWHEN** [slowtorta/turtlewow-bug-tracker#5350]
**Please, provide a clear description what the bug is:**
today ive checked my equipment status and i found the enchant effect of enchanted armor kit that i used on my cloth and shoes is vanished.
**Steps to reproduce the behavior with as much detail as possible:**

1.Ive used enchanted armor kit on my cloth(Robe of the Dreamways) and my shoes(Ringo's Blizzard Boots)
2. today i check it and the effects are gone
3. ive done nothing on this two item these days.

**IDs of affected creatures, items, quests or spells with a link to the relevant page:**
Robe of the Dreamways:https://database.turtle-wow.org/?item=61206
Ringo's Blizzard Boots:https://database.turtle-wow.org/?item=19438
Enchanted Armor Kit:https://database.turtle-wow.org/?item=61183
character name is Anoosdsry

**Expected behavior. Describe how it should work:**\
i just right clicked the armor kit and used them on the equipment and after that ive done nothing to these two equipments. if u guys can check it out plz fix it and restore my equipment. thank u.

**Comment by AKryukov92** [comment]
Looks like https://github.com/slowtorta/turtlewow-bug-tracker/issues/4829

**Comment by twowTurtReynolds** [comment]
![image](https://github.com/slowtorta/turtlewow-bug-tracker/assets/151180101/b940dcef-2bf5-461c-97f8-58acc2426ede)
logged out and back in on the PTR. The enchanted armor kits appear to be working as intended. Not a bug

If you are vagrant, that's the real issue. Check the linked report above.
