### ISSUE TITLE
[60] The Upper Binding II 

### ISSUE THREAD

**Issue by Epoprocks** [slowtorta/turtlewow-bug-tracker#5355]
**Currently, I cannot turn in the quest materials for the quest Upper Binding II**

**Steps to reproduce the behavior with as much detail as possible:**

1. Acquire 5 Essence of Fire
2. Acquire 1 Fragment of Earth quest item
3. NOT ABLE TO TURN IN QUEST

**IDs of affected creatures, items, quests or spells with a link to the relevant page:**

NPC: https://database.turtle-wow.org/?npc=61570
Item: https://database.turtle-wow.org/?item=61694
Quest: https://database.turtle-wow.org/?quest=41012
Spell: https://database.turtle-wow.org/?spell=
Object: https://database.turtle-wow.org/?object=

**Expected behavior. Describe how it should work:**
I should be able to turn in my quest items.
![Capture](https://github.com/slowtorta/turtlewow-bug-tracker/assets/107639351/54c2f37f-c758-4c2d-886b-2a5762d14629)

**Comment by twowTurtReynolds** [comment]
Please see https://github.com/slowtorta/turtlewow-bug-tracker/issues/6042
