### ISSUE TITLE
Trial of the sea lion Aquatic form - air cracks not working

### ISSUE THREAD

**Issue by Chirr-Canon-Husband** [slowtorta/turtlewow-bug-tracker#5359]
**Please, provide a clear description what the bug is:**

**Steps to reproduce the behavior with as much detail as possible:**

1. Aquatic form quest chain in moonglade and westfall (Alliance)
2. Swim down near the underwater air cracks
3. Receive no air and drown

Quest: https://database.turtle-wow.org/?quest=272

**Expected behavior. Describe how it should work:**
I should swim near the cracks and it should refill my breath bar based on proximity, it doesn't. 

Additional info: Hardcore character, the air cracks did not work in moonglade for the first part of the chain or in westfall for the pendant half. 
As it stands, anyone that tries looting the chest drowns. You barely have enough air to go down and back up, no time to loot

I have talked to two non HC, PVP guys that just drowned and they experienced the same thing

Deleting WDB folder and logging back in doesn't work either

**Comment by twowTurtReynolds** [comment]
![image](https://github.com/slowtorta/turtlewow-bug-tracker/assets/151180101/c010e065-14e9-4238-88c4-d0123b1ef559)
![image](https://github.com/slowtorta/turtlewow-bug-tracker/assets/151180101/44207b62-c65d-40c1-9d16-e5df8261facb)
The buff seems to be working...

**Comment by twowTurtReynolds** [comment]
The PTR has had drowning re-enabled, and I have retested. The moonglade, Westfall, and silverpine fissures work.

![image](https://github.com/slowtorta/turtlewow-bug-tracker/assets/151180101/42c3167c-2536-4a4c-b77e-677a8b973474)
