### ISSUE TITLE
Alterac Valley guards continue spawning after towers are burned

### ISSUE THREAD

**Issue by discslack** [slowtorta/turtlewow-bug-tracker#536]
**Please, provide a clear description what the bug is:**
After towers are burned Horde NPC guards stop spawning Alliance NPC's continue to spawn regardless of towers of being burned.
**Steps to reproduce the behavior with as much detail as possible:**

1. Burn horde tower see that patrolling guard NPC's stop spawning
2. Burn alliance tower see that patrolling guard NPC's continue spawning

**Expected behavior. Describe how it should work:**
Guards should stop spawning on either side after the corresponding tower has been destroyed

**Comment by geojak** [comment]
Horde ones also spawn
