### ISSUE TITLE
Whipper Root Tubers Bugged

### ISSUE THREAD

**Issue by scheminpete** [slowtorta/turtlewow-bug-tracker#5360]
I cannot loot Whipper Root Tubers in Felwood. The "Cleansed Whipper Root" is bugged.

**Steps to reproduce the behavior with as much detail as possible:**

1. I first cleanse a Corrupted Whipper Root using Cenarian Plant Salve x3.
2. I then try to loot the Cleansed Whipper Root, which should provide me with a couple Whipper Root Tubers.
3. Nothing is looted. I've done this over 20 times.

**Comment by Length123** [comment]
Did you get this to work?

**Comment by Muigin** [comment]
Duplicate of #5332
