### ISSUE TITLE
The Hyjal shoulder buff ignores 75 armor, but when used, it shows that it ignores 40 armor

### ISSUE THREAD

**Issue by zdj521120** [slowtorta/turtlewow-bug-tracker#5361]
1.
![微信图片_20231124054005](https://github.com/slowtorta/turtlewow-bug-tracker/assets/138490423/665b4cef-43bb-4600-8a0e-40d73c1d9d92)
Here's how it works now
2. 
![微信图片_20231124054008](https://github.com/slowtorta/turtlewow-bug-tracker/assets/138490423/ab2d5e30-93cd-4710-87be-aee6676948c9)
This is the previous effect
3.
![微信图片_20231124055830](https://github.com/slowtorta/turtlewow-bug-tracker/assets/138490423/e4afc2eb-5517-4242-8adc-ea2ae0fce498)

4. I've removed the wdb and the problem persists

**IDs of affected creatures, items, quests or spells with a link to the relevant page:**

Item: https://database.turtle-wow.org/?item=61438

**Comment by twowTurtReynolds** [comment]
Intended nerf with the midpatch itemization update. The text update will arrive with the next client patch.
