### ISSUE TITLE
failed to use infinite frog and item disappeared

### ISSUE THREAD

**Issue by letsfixbug** [slowtorta/turtlewow-bug-tracker#5362]
**Please, provide a clear description what the bug is:**
I was using infinite frog and got a failure. the item disappeared and I didn't have any new companion

**Steps to reproduce the behavior with as much detail as possible:**

1. just use it
2. 
3. 

**IDs of affected creatures, items, quests or spells with a link to the relevant page:**

NPC: https://database.turtle-wow.org/?npc=
Item: https://database.turtle-wow.org/?item=54003
Quest: https://database.turtle-wow.org/?quest=
Spell: https://database.turtle-wow.org/?spell=
Object: https://database.turtle-wow.org/?object=

**Expected behavior. Describe how it should work:**
should use it successfully and add a new companion

**Comment by twowTurtReynolds** [comment]
Works fine. It's in your spellbook unlike 2006 vanilla.
![image](https://github.com/slowtorta/turtlewow-bug-tracker/assets/151180101/6e17caca-0d00-4bf7-b6bd-f34b59da14c0)
