### ISSUE TITLE
Corrupted Whipper Root drops NO loot

### ISSUE THREAD

**Issue by MorceloTW** [slowtorta/turtlewow-bug-tracker#5363]
Corrupted Whipper Root drops NO loot

1. Clean "Corrupted Whipper Root" (https://database.turtle-wow.org/?object=173284)  with 3x "Cenarion Plant salve" (https://database.turtle-wow.org/?item=11516)
and it becomes "Cleansed Whipper Root".

2. Loot it and there is NO loot. It must drop 3-10 "Whipper Root Tuber" (https://database.turtle-wow.org/?item=11951).

**Comment by Length123** [comment]
Did you get this to work?
