### ISSUE TITLE
Unable to pick up quests

### ISSUE THREAD

**Issue by Silenuviel** [slowtorta/turtlewow-bug-tracker#5364]
**I am level 60, am going back to do low level quests for Orgrimmar rep. Many quests show up on pfQuest, but I can't pick up quests from npc quest giver. I suspect this is having to do with abandoning these quests in the past** **PLEASE NOTE: BELOW QUESTS IS ONLY  3 OUT OF MANY QUESTS INACCESSIBLE.**

**Steps to reproduce the behavior with as much detail as possible:**

1. Pick up quest
2. Abandon quest
3. pfQuest shows Hidden Enemies as available on map, if you hover mouse over NPC quest giver, it will show quest available
4. NPC Quest Giver doesn't have ! mark over their head
5. Click on Quest Giver and they do not give you quest.

**IDs of affected creatures, items, quests or spells with a link to the relevant page:**

Hidden Enemies Quest:
NPC: https://database.turtle-wow.org/?npc=4949
Quest: https://database.turtle-wow.org/?quest=5726

Need for a Cure Quest (Rhinag is not even at location):
NPC: https://database.turtle-wow.org/?npc=3190
Quest: https://database.turtle-wow.org/?quest=812

March of the Silithids Quest:
NPC: https://database.turtle-wow.org/?npc=7010
Quest: https://database.turtle-wow.org/?quest=4494

**Expected behavior**
Should be able to pick up quest after having abandoned it before.

**Fixes Tried**
Checked for prequests for above 3 examples, there are no prequests
Deleted WDB folder many times
Reset User Data on pfQuest

**Comment by twowTurtReynolds** [comment]
pfquest has no way to tell if you have done a quest in the past or not... there is no server to client API for this. 
Your report is based on this misunderstanding that it is accurate. It is very likely that you have completed these quests and so cannot repeat them.
