### ISSUE TITLE
Idol of Brutality incorrectly modifies the client spell of Savage Bite

### ISSUE THREAD

**Issue by Mirakoli123** [slowtorta/turtlewow-bug-tracker#5365]
**Please, provide a clear description what the bug is:**
- if you have Idol of Brutality equipted, the Tooltip says "Savage Bite" would cost 22 Rage (without 25 Rage) and turns bright but you cant use it! 
**Steps to reproduce the behavior with as much detail as possible:**

1. Equip Idol of Brutality 
2. Get 22 Rage
3. Try to use Savage Bite (only triggers on 25 Rage)

**IDs of affected creatures, items, quests or spells with a link to the relevant page:**

NPC: 
Item: https://database.turtle-wow.org/?item=23198
Quest: 
Spell: https://database.turtle-wow.org/?spell=45736
Object: 

**Expected behavior. Describe how it should work:**
 Im not sure if Idol of Brutality should reduce the Ragecost of Savage Bite by 3 or not??? But it turns bright on 22 Rage but you can only use it on 25 Rage

**Comment by luskanek** [comment]
I can't reproduce this issue. I tried various combinations with and without the idol and the 'Ferocity' talent, but the issue you described never happened to me. @Mirakoli123, were you using any UI modifying add-ons at the time when this happened?
