### ISSUE TITLE
Visual bug - Duplicated roll on 2 identical items in loot frame

### ISSUE THREAD

**Issue by Gensoo** [slowtorta/turtlewow-bug-tracker#5367]
**Please, provide a clear description what the bug is:**
In Sunken temple, 2 shield of identical name dropped. 
Player 1 rolled need on shield 1 and greed on shield 2 but my loot frame showed he rolled need on both shield 1 and shield 2. 
I roll need on shield 1 and pass on shield 2. I win need roll on shield 1 and player 3 (warlock) wins greed roll on shield 2. 

**Steps to reproduce the behavior with as much detail as possible:**

1. Have PFUI installed
2.  Drop 2 identical items
3.  Roll on 1 of them.
4.  Observe the roll replicated for both items (visual only)

**IDs of affected creatures, items, quests or spells with a link to the relevant page:**

NPC: https://database.turtle-wow.org/?npc=5709
Item: https://database.turtle-wow.org/?item=10835
Quest: https://database.turtle-wow.org/?quest=
Spell: https://database.turtle-wow.org/?spell=
Object: https://database.turtle-wow.org/?object=

**Expected behavior. Describe how it should work:**
1 item should show need roll and the other should show greed.

![WoW_vucP0twzXy](https://github.com/slowtorta/turtlewow-bug-tracker/assets/9191645/1087be04-c9da-4c44-8d60-9e33a5848f98)

**Comment by twowTurtReynolds** [comment]
This is an addon issue. It is likely addons have no way to tell which is which.
