### ISSUE TITLE
Crusader judgment can't act on Hand of Edward the Odd

### ISSUE THREAD

**Issue by RX9001** [slowtorta/turtlewow-bug-tracker#5371]
**Please, provide a clear description what the bug is:**

**Steps to reproduce the behavior with as much detail as possible:**

1.
2. 
3. 

**IDs of affected creatures, items, quests or spells with a link to the relevant page:**

[Item: https://database.turtle-wow.org/?item=](https://database.turtle-wow.org/?item=2243)

[Spell: https://database.turtle-wow.org/?spell=](https://database.turtle-wow.org/?spell=20303)

**Expected behavior. Describe how it should work:**

**Comment by testening** [comment]
#2550

**Comment by twowTurtReynolds** [comment]
This was an intentional nerf. Many weapons have exceptions to JotC
