### ISSUE TITLE
No loot from Corrupted/Cleansed Whipper Roots

### ISSUE THREAD

**Issue by Length123** [slowtorta/turtlewow-bug-tracker#5372]
Felwood Whipper Roots are bugged. Cannot receive loots, which is a requirement to get BiS Enchant "Arcanum of Voracity"
I just tried this 3 times. Can you please fix?
Also, can you send me the 9x Whipper Root Tubers I should have received? :)

**THESE STEPS WORKS**
1. Acquire 3x Cenarion Plant Salve. (https://database.turtle-wow.org/?item=11516)
2. Locate a Corrupted Whipper Root. (https://database.turtle-wow.org/?object=174605)
3. Complete the quest to cleanse the Corrupted Whipper Root by handing in 3x Cenarion Plant Salve. (https://database.turtle-wow.org/?quest=4444)
4. The Corrupted Whipper Root disappears and a Cleansed Whipper Root appears. (https://database.turtle-wow.org/?object=174687)

**THIS IS THE BUGGED STEP**
5. Loot the Cleansed Whipper Root. Here I would expect to receive 3x Whipper Root Tubers (https://database.turtle-wow.org/?item=11951)

It's on telabim and ingame name is Length

Thanks!

**Comment by Length123** [comment]
Oh, btw. It's on Telabim and ingame name is Length.

**Comment by MorceloTW** [comment]
How many requests do you need to collect for the administration to pay attention to it? WTF

**Comment by Sheed90** [comment]
Same on the PVE Realm

**Comment by Muigin** [comment]
Duplicate of #5332
