### ISSUE TITLE
Shortsword of Vengeance's Chance on hit is not affected by Crusader Strike's holy damage taken increase debuff

### ISSUE THREAD

**Issue by Cerestie** [slowtorta/turtlewow-bug-tracker#5375]
**Please, provide a clear description what the bug is:**
Shortsword of Vengeance's Chance on hit: Smites an enemy for 30 Holy damage is not affected by Crusader Strike's holy damage taken increase debuff, even though it deals holy damage to the enemy. 

**Steps to reproduce the behavior with as much detail as possible:**
1. Equip the weapon Shortsword of Vengeance
2. Spam Crusader Strike to any enemy to stack the holy damage taken increase debuff
3. Wait for the holy smite to proc to see that the holy damage deals 30/unaffected by the Crusader Strike's debuff

**IDs of affected creatures, items, quests or spells with a link to the relevant page:**
Item: https://database.turtle-wow.org/?item=754
Spell: https://database.turtle-wow.org/?spell=13519
Spell: https://database.turtle-wow.org/?spell=10337

**Expected behavior. Describe how it should work:**
The chance on hit of Shortsword of Vengeance deals holy damage, so it should be affected by Crusader Strike's holy damage taken increase debuff. The chance on hit holy damage is affected by the skill Sanctity Aura +10% holy damage, so it should be affected by Crusader Strike's debuff too.

**Comment by twowTurtReynolds** [comment]
Crusader strike adds spellpower to a target, as if you were wearing the spellpower.

However, different Spells in the game each have their own spellpower coefficients, which is factored into:
 result damage = base damage + coeff * spellpower
 
 If the coeff is 0, then result = base damage always. This is the case of this weapon.

However, result damage does get +% buffs factored in always. I just tested sanctity aura and yes, that part works.
