### ISSUE TITLE
Klockmort Spannerspan is not where he's supposed to be

### ISSUE THREAD

**Issue by octav3k** [slowtorta/turtlewow-bug-tracker#5376]
**Please, provide a clear description what the bug is:**
Klockmort Spannerspan is not where he's supposed to be. He's currently at Tinker Town (his old location).
![Klockmort Spannerspan](https://github.com/slowtorta/turtlewow-bug-tracker/assets/30603128/96c3f1d8-b48b-49dd-80e4-04c2de008caa)

**Steps to reproduce the behavior with as much detail as possible:**
1. Go to the Gnomeregan Reclamation Facility, to try and turn in / pick up any of his quests
2. Make a GM ticket to ask if it's bugged and get a non-answer
3. Go to Tinker Town

**IDs of affected creatures, items, quests or spells with a link to the relevant page:**
NPC: https://database.turtle-wow.org/?npc=6169

**Expected behavior. Describe how it should work:**
Klockmort Spannerspan should be in the Gnomeregan Reclamation Facility, where the database shows him.

**Comment by twowTurtReynolds** [comment]
He should be all fixed up now.
