### ISSUE TITLE
Nightfin/Sunscale droprates

### ISSUE THREAD

**Issue by kevytmaito784** [slowtorta/turtlewow-bug-tracker#5378]
**Please, provide a clear description what the bug is:**
Moonglade seems to have a 0% droprate of both Nightfin/Sunscale, I've been fishing here for hours without a single drop.
Western Plaguelands has a ~5% droprate, which is considerably lower than what your own database would suggest.
(yes I delete my WDB folder everytime before launching the game, it is not that)

**Steps to reproduce the behavior with as much detail as possible:**
no steps, just go fish for 4 hours and see for yourself.
1.
2. 
3. 

**IDs of affected creatures, items, quests or spells with a link to the relevant page:**

NPC: https://database.turtle-wow.org/?npc=
Item: https://database.turtle-wow.org/?item=13760 https://database.turtle-wow.org/?item=13759
Quest: https://database.turtle-wow.org/?quest=
Spell: https://database.turtle-wow.org/?spell=
Object: https://database.turtle-wow.org/?object=

**Expected behavior. Describe how it should work:**
Around 20% droprate in both WPL and Moonglade.

**Comment by ratkosrb** [comment]
Fishing Nightfin and Sunscale in Kalimdor should be fixed after the next update.
