### ISSUE TITLE
Gains from buffs imply inifite resources

### ISSUE THREAD

**Issue by rptb1** [slowtorta/turtlewow-bug-tracker#538]
**Please, provide a clear description what the bug is:**

When a buff has a resource increase, that increase is reported in the Combat Log even if the resource is at maximum.  This is not how it was in Vanilla, where you could tell when the resource reached maximum from the message.

For example:

- "You gain 10 Mana from Blessing of Wisdom" when mana is full
- "<pet> gains 8 happiness from the Feed Pet Effect" when pet is fully happy

The latter is particularly important for knowing when your pet is at full happiness!  It's how you could tell in Vanilla.

**Steps to reproduce the behavior with as much detail as possible:**

1. Make a level 10 hunter with a pet.
2. Try feeding the pet until it stops getting happier.
3. Note the Combat Log appears to imply he gets happier forever.

**IDs of affected creatures, items, quests or spells with a link to the relevant page:**

NPC: https://database.turtle-wow.org/?npc=
Item: https://database.turtle-wow.org/?item=
Quest: https://database.turtle-wow.org/?quest=
Spell: https://database.turtle-wow.org/?spell=
Object: https://database.turtle-wow.org/?object=

**Expected behavior. Describe how it should work:**

When e.g. pet happiness reaches maximum, the message should things like:

> <pet> gains 8 happiness from the Feed Pet Effect
> <pet> gains 3 happiness from the Feed Pet Effect
> <pet> gains 0 happiness from the Feed Pet Effect

as the resource reaches maximum level.

**Comment by Velite12** [comment]
proof

**Comment by Nolin7777** [comment]
Hello and thank you for your report!

For comparison please add any evidence in form of a legit source (for example wowhead.com) or a video captured from Blizzard's Classic server.

This ticket will be closed until more information added.
