### ISSUE TITLE
Can't rename hunter pet

### ISSUE THREAD

**Issue by ChewbaccaUncircumcised** [slowtorta/turtlewow-bug-tracker#5380]
**Please, provide a clear description what the bug is:**
When I try to rename my hunter pet, I get an error that reads, "Error, invalid name entered."
**Steps to reproduce the behavior with as much detail as possible:**

1. I selected renaming the pet just before my group went into combat.
2. When I chose the name I wanted for the pet, and hit ok, I get an error that says "Error, invalid name entered."
3. 

**IDs of affected creatures, items, quests or spells with a link to the relevant page:**
Account name is Daemonias, character name is Tasmina, Server is Tel'Abim.

My gmail address is: colinharding1982@gmail.com

Thank you for your help!

NPC: https://database.turtle-wow.org/?npc=
Item: https://database.turtle-wow.org/?item=
Quest: https://database.turtle-wow.org/?quest=
Spell: https://database.turtle-wow.org/?spell=
Object: https://database.turtle-wow.org/?object=

**Expected behavior. Describe how it should work:**

**Comment by twowTurtReynolds** [comment]
...Were you entering an invalid name? It can only take Letters. I just renamed just fine on the PTR.

**Comment by ChewbaccaUncircumcised** [comment]
Was trying gmto name it Sirius
