### ISSUE TITLE
The clickable portal for Ritual of Summoning s not visible at the road right outside the Karazan instance

### ISSUE THREAD

**Issue by Michael-lindell** [slowtorta/turtlewow-bug-tracker#5381]
**Please, provide a clear description what the bug is:**

Summoning portal as Warlock does not appear right outside the entrence of Karazan (Kara 10 man).
However if you stand on the grass right beside the road, the portal appears

**Steps to reproduce the behavior with as much detail as possible:**

1. Be a warlock
2.  Get atleast two people in your raid (not tried as party).
3.  Stand at the road right outside the Karazan instance and press summon.

**IDs of affected creatures, items, quests or spells with a link to the relevant page:**

Spell: https://database.turtle-wow.org/?spell=698

**Expected behavior. Describe how it should work:**
Ritual of Summoning portal should appear as normal ( a portal to click for other players).

**Comment by twowTurtReynolds** [comment]
![image](https://github.com/slowtorta/turtlewow-bug-tracker/assets/151180101/e6a57036-c097-4dc4-a475-938ceaab2928)
Works fine.
