### ISSUE TITLE
Voidwalker lost all his learned abilities

### ISSUE THREAD

**Issue by azvin1** [slowtorta/turtlewow-bug-tracker#5382]
**Please, provide a clear description what the bug is:**
I have been leveling a warlock on Tel'Abim, and have learned all of the voidwalker books up to level 34. When I reached level 34, I purchased the book and learned consume shadows rank 3. I then had a mage port me to UC from Org, and I took a FP to tarren mill. I proceeded to quest there, and when I was in the yeti cave, I jumped down from the top after clearing the packs to the right, and wanted to sac my void walker so he wouldnt aggro all the yetis on the road down to me. Thats when i realized he didnt have his sacrifice ability.

I toughed through the several mobs he brought with him, and then summoned him again. The only spell he has learned is consume shadows rank 3. No Aoe taunt, and only the default rank 1 torment (which isnt doing a good job to hold aggro at lvl 34 lol)

I am pretty sure my voidwalker also has a new name, which makes it that much more strange.

I would also like to be compensated for the silver lost on each book, as they are quite costly as we level up on top of the other skills.

-Azvin
**Steps to reproduce the behavior with as much detail as possible:**

1. Have a lvl 33 warlock, with a voidwalker that has all skills learned through books.
2.  Level to 34, and purchase consume shadows rank 3.
3.  Take a portal from Org to UC
4. Take a FP to tarren mill.
5. If you have the voidwalker already summoned, check his skills. if not, summon him and check his skills.

**Expected behavior. Describe how it should work:**
Voidwalker should not lose all his trained abilities.

**Comment by twowTurtReynolds** [comment]
Turns out its caused by https://github.com/slowtorta/turtlewow-bug-tracker/issues/3871 , tracking there.
