### ISSUE TITLE
Dark Leather Belt recipe is taught at the wrong trainers

### ISSUE THREAD

**Issue by TheRealElysium** [slowtorta/turtlewow-bug-tracker#5383]
**Please, provide a clear description what the bug is:**
Dark Leather belt is supposed to be taught at Expert Leatherworking trainers, instead of the Artisan trainers as it is on turtle wow.

**Steps to reproduce the behavior with as much detail as possible:**

1. Interact with an any expert leatherworking trainer. 
2. Notice no training for Dark Leather Belt

**IDs of affected creatures, items, quests or spells with a link to the relevant page:**

Item: https://database.turtle-wow.org/?item=4249
Spell: https://database.turtle-wow.org/?spell=3766

**Expected behavior. Describe how it should work:**
Expert Leatherworking trainers are supposed to have Dark Leather Belt.
See: https://www.wowhead.com/classic/spell=3766/dark-leather-belt

https://github.com/slowtorta/turtlewow-bug-tracker/issues/4356

**Comment by twowTurtReynolds** [comment]
Thanks, we will track this in https://github.com/slowtorta/turtlewow-bug-tracker/issues/4356 as its scope encompasses this example.
