### ISSUE TITLE
Missing Corrupted Songflower in Felwood

### ISSUE THREAD

**Issue by Lichbanez** [slowtorta/turtlewow-bug-tracker#5384]
This flower is the only corrupted plant that doesn't spawn at all, I camped it for a couple of hours just to be sure.

1. Waste time waiting at the correct spot

Object: https://database.turtle-wow.org/?object=174597

This node should work like all the others but it's not for some reason, on wowhead it shows the right location.

**Comment by twowTurtReynolds** [comment]
List of these: https://database.turtle-wow.org/?search=corrupted+songflower

Confirmed one of these https://database.turtle-wow.org/?object=174713 works via `.go object id 174713`. Indeed `.go object id 174597` doesn't work on turtle.

On vmangos, it does:
![image](https://github.com/slowtorta/turtlewow-bug-tracker/assets/151180101/62e579b0-d90e-469c-8768-6c3b6c4db6ff)

**Comment by Lichbanez** [comment]
The node still hasn't been added, just saying.

**Comment by Muigin** [comment]
I have pushed a fix for this that will be in the next maintenance.

**Comment by Lichbanez** [comment]
Thanks for the fix, on the patch note it reads "Fixed several minor bugs with Felwood Corrupted Plants, including incorrect quest IDs" but if I completed those quests before the maintenance will they still be counted as completed with the new ID or do I have to do all of them again? I didn't check my /played before logging off.

**Comment by twowTurtReynolds** [comment]
IIRC These are repeatables which don't count towards the total quests completed count.

**Comment by Lichbanez** [comment]
You're right I just checked on a new character and I can confirm that these quests don't count for Lorekeeper still it wouldn't have hurt to know exactly which one of the IDs have been corrected, thanks.
