### ISSUE TITLE
[Item] Razor-sharp Knife displays incorrect level and faction requirements

### ISSUE THREAD

**Issue by CasualNerdity** [slowtorta/turtlewow-bug-tracker#5385]
Razor-sharp Knife is an item that starts a quest, and the in-game description shows that it can only be completed by Alliance who are level 10. I was able to start and complete the quest as a Tauren. On the database the quest shows that level 30 is required, not level 10.

Item: https://database.turtle-wow.org/?item=60895
Quest: https://database.turtle-wow.org/?quest=40659

**Expected behavior. Describe how it should work:**
The item should show that it requires level 30 to start the quest, and it should have a race/class mask of -1 instead of 589 and 32767 respectively.

![Capture](https://github.com/slowtorta/turtlewow-bug-tracker/assets/79479148/67be0376-7e06-4f92-b088-f733ccb59c24)

**Comment by Dragunovi** [comment]
Raised the item's level requirement to 30 and removed race restrictions as the finish NPC is neutral. Should be live in the next scheduled restart.
