### ISSUE TITLE
Ferra's Collar Don't give any benefits to your pet

### ISSUE THREAD

**Issue by MenelauGC** [slowtorta/turtlewow-bug-tracker#5386]
**Please, provide a clear description what the bug is:**
Ferra's  Collar should give your pet+4% damage and its not giving any damage bonus.
**Steps to reproduce the behavior with as much detail as possible:**

1.Item dont give any bonus damage to the pet.
2. Item dont give any bonus damage to the pet.
3. Item dont give any bonus damage to the pet.

**IDs of affected creatures, items, quests or spells with a link to the relevant page:**
15420
NPC: https://database.turtle-wow.org/?npc=
Item: https://database.turtle-wow.org/?item=
Quest: https://database.turtle-wow.org/?quest=
Spell: https://database.turtle-wow.org/?spell=
Object: https://database.turtle-wow.org/?object=

**Expected behavior. Describe how it should work:**
The item should give +4% damage to your pet.

**Comment by twowTurtReynolds** [comment]
https://database.turtle-wow.org/?item=18355 uses spell https://database.turtle-wow.org/?spell=22854

On the PTR I spammed .aura 22854 while my owl attacked a target dummy

![image](https://github.com/slowtorta/turtlewow-bug-tracker/assets/151180101/1ddb31a1-6605-42bf-af3b-13923ed01aef)
The owl that was attacking for 40-50 on the lv1 dummy is now attacking up to 70 with many many stacks of this aura.

Working as intended.
