### ISSUE TITLE
Lightning Shield cannot be Mouseover casting or click-casting with the "Thunderhead" talent.

### ISSUE THREAD

**Issue by galakom** [slowtorta/turtlewow-bug-tracker#5387]
**Please, provide a clear description what the bug is:**

Lightning Shield cannot be Mouseover casting or click-casting with the "Thunderhead" talent, and the same does not apply to casting on a focused target or casting on a specific target.

**Steps to reproduce the behavior with as much detail as possible:**

With the "Thunderhead" talent, you can only use Lightning Shield on a target ally by locking on to them.
Lightning Shield cannot be Mouseover casting or click-casting with the "Thunderhead" talent, and the same does not apply to casting on a focused target or casting on a specific target.
Of course this is all tested with addons support.

https://github.com/slowtorta/turtlewow-bug-tracker/assets/83994354/72172eb5-a38d-45d6-8875-a3a2a3ad2371

**IDs of affected creatures, items, quests or spells with a link to the relevant page:**

https://database.turtle-wow.org/?spell=45508

**Expected behavior. Describe how it should work:**

It was supposed to work.

[](url)

**Comment by twowTurtReynolds** [comment]
I confirmed that this lua works correctly.
```/run CastSpellByName("Lightning Shield", target)```

Addon issue. Contact the dev of whoever added /stcast
