### ISSUE TITLE
Non-Timbermaw-Locked version of Pattern: Warbear Woolies contained in Thorium Lockbox

### ISSUE THREAD

**Issue by Aubreykun** [slowtorta/turtlewow-bug-tracker#5389]
**Please, provide a clear description what the bug is:**
A strange alternate version of [Pattern: Warbear Woolies] has a high chance to drop from [Thorium Lockbox]. This version lacks the Timbermaw Hold rep requirement, but is still BoP. It can be obtained (or even traded) to people without Timbermaw Hold rep due to this. I am not sure that this item should be available to players.
I have personally obtained this, and the database loot table shows it has both a separate group (meaning it can drop in addition to the other loot) and a high drop chance of 12%.

**Steps to reproduce the behavior with as much detail as possible:**

1. Obtain a thorium lockbox
2. Unlock and open it
3. Repeat until you obtain the pattern (it should not be too many.)

**IDs of affected creatures, items, quests or spells with a link to the relevant page:**

Item: Thorium Lockbox https://database.turtle-wow.org/?item=5759
Item: Non-rep [Pattern: Warbear Woolies] https://database.turtle-wow.org/?item=15754

**Expected behavior. Describe how it should work:**
This item shouldn't even exist, as it's normally a rep-locked pattern.

**Comment by twowTurtReynolds** [comment]
I looks like https://www.wowhead.com/classic/item=15754 is a cut item with no source on wowhead. And the duplicate with a higher ID https://www.wowhead.com/classic/item=20254/pattern-warbear-woolies that has the timbermaw rep restriction is the one that players can obtain.

**Comment by twowTurtReynolds** [comment]
Fixed for next restart :)
