### ISSUE TITLE
Whipper Root Tubers in Felwood

### ISSUE THREAD

**Issue by PierreduNord** [slowtorta/turtlewow-bug-tracker#5391]
Hello, I have a chronic bug on Felwood's corrupted whipper roots. I completed quest with cenarian plant salve 3 times but the whipper root tubers don't drop when i pick it. This does it for all the corrupted whipper roots locations I tried yesterday and today. I've cleared my cache, nothing changes. I just want the item to make my voracity libram and forget about this unpleasant episode.

Item: https://database.turtle-wow.org/?item=11951

**Comment by AKryukov92** [comment]
Thank you. This is similar to https://github.com/slowtorta/turtlewow-bug-tracker/issues/5332
