### ISSUE TITLE
Fist of the Forgotten Order Strength buff does not stack with juju power

### ISSUE THREAD

**Issue by Icfre** [slowtorta/turtlewow-bug-tracker#5395]
**Please, provide a clear description what the bug is:**
The +50 strength from Fist of the forgotten order does not completely stack with juju power, the higher of the two values is used which nets you +20 strength if using both at the same time.

**Steps to reproduce the behavior with as much detail as possible:**

1. Apply juju power
2.  Use fist of the forgotten order until it procs
3.  Strength will only increase by 20

**IDs of affected creatures, items, quests or spells with a link to the relevant page:**

NPC: https://database.turtle-wow.org/?npc=
Item: https://database.turtle-wow.org/?item=
Quest: https://database.turtle-wow.org/?quest=
Spell: https://database.turtle-wow.org/?spell=
Object: https://database.turtle-wow.org/?object=

**Expected behavior. Describe how it should work:**

**Comment by twowTurtReynolds** [comment]
Thanks balakethelock. Closing as dupe
