### ISSUE TITLE
All my equipment cannot be enchanted

### ISSUE THREAD

**Issue by Keepalived19** [slowtorta/turtlewow-bug-tracker#5398]
**Please, provide a clear description what the bug is:**

**Steps to reproduce the behavior with as much detail as possible:**

1.Name: Harddly
2. am playing Wanderer and HC mode, now that I am at max level, I suddenly realize that all my equipment cannot be enchanted
3. At the same time, the materials I used to enchant 30 magic damage on my weapon were also consumed, and it was enchant twice. Please repair it. Thank you.

**IDs of affected creatures, items, quests or spells with a link to the relevant page:**

NPC: https://database.turtle-wow.org/?npc=
Item: https://database.turtle-wow.org/?item=
Quest: https://database.turtle-wow.org/?quest=
Spell: https://database.turtle-wow.org/?spell=
Object: https://database.turtle-wow.org/?object=

**Expected behavior. Describe how it should work:**

**Comment by AKryukov92** [comment]
Same as https://github.com/slowtorta/turtlewow-bug-tracker/issues/4829
