### ISSUE TITLE
Black Dragon's Head Quest Item Missing:

### ISSUE THREAD

**Issue by ningkexin0131** [slowtorta/turtlewow-bug-tracker#5399]
1. The day before yesterday, after the black dragon was distributed, the black dragon head task item, you can hand in the task on the same day, but you want to wait for a buff CD did not hand in the task, and the dragon head has been in the bag
2. The second online ready to hand in the task is to find that the task items in the bag are gone, and some friends said that the file was rolled back that night, but other items were not lost.
3. Ask the GM to reply to my Black Dragon Quest item to hand over the task, I LM Hunter.

**IDs of affected creatures, items, quests or spells with a link to the relevant page:**

Quest: https://database.turtle-wow.org/?quest=7495

**Expected behavior. Describe how it should work:**

**Comment by twowTurtReynolds** [comment]
Contact a GM, not the bug tracker.
