### ISSUE TITLE
Various enchants are broken

### ISSUE THREAD

**Issue by faralynn** [slowtorta/turtlewow-bug-tracker#54]
I'm aware it's a known issue for MCP + Iron counterwights, but this issue extends a bit past that.

**Current behavior**: 
I tested enchanting on the following:

_Enchant 2h Weapon - Minor Impact_ ----> (to item) Halberd of Smiting
_Result: Must have a Axe equipped_

_Enchant 2h Weapon - Minor Impact_ ----> (to item) Draconic Avenger
_Result: Must have a Axe equipped_

_Enchant Bracer - Superior Stamina_ ---> (to item) Bracers of Arcane Accuracy
_Result: Success._

_Enchant Shield - Greater Stamina_ ---> (to item) Malistar's Defender
_Result: Must have a Shield equipped._

Note that I also had people try to give me the enchants with their own enchanters as well. Same result.

**Expected behavior**: 
I should be able to enchant my gear if I both have the materials and the enchant is for that item type...

**Proofs**:
![ench](https://user-images.githubusercontent.com/2092314/122146915-dc4bd080-ce25-11eb-8ad1-5d44469762e1.jpg)

**Steps to reproduce**:

1. Try enchanting any of the items I listed.

**Extra information**
Enchanter character: Tarutaru - class: Warlock
Enchant recipient: Oaks - class: Paladin

Tested both with items equipped and not equipped.

**Comment by glav3r** [comment]
This is still broken - I attempted to enchant a shield that was not equipped (I'm a Warlock) and it states: Must be equipped.
