### ISSUE TITLE
Summoned robots in deadmines do not have a threat table

### ISSUE THREAD

**Issue by geojak** [slowtorta/turtlewow-bug-tracker#540]
**Please, provide a clear description what the bug is:**

the goblins in deadmines summon robots. these never change target on this server and ignore threat. this is not blizzlike.

**Steps to reproduce the behavior with as much detail as possible:**

1. go to deadmines with 2 players
2. aggro the goblins and let them summoned the robots
3. try to get aggro with the second player with any means, it wont work

**IDs of affected creatures, items, quests or spells with a link to the relevant page:**

NPC: https://database.turtle-wow.org/?npc=
Item: https://database.turtle-wow.org/?item=
Quest: https://database.turtle-wow.org/?quest=
Spell: https://database.turtle-wow.org/?spell=
Object: https://database.turtle-wow.org/?object=

**Expected behavior. Describe how it should work:**

those robots should have a threat table

additionally the fire elementals that the syndicates summon in the out of instances dungeon area of deadmines have the same problem

**Comment by geojak** [comment]
Here you go
https://m.youtube.com/watch?v=somvWsV7fQQ

At 12.10 you clearly see a robot change target after receiving dmasge. No taunt involved.

 Lear proof that a threat table should exist

Could you reopen the issue or maybe ask for further info if you need it before instant closure.

I am a bit worried Thai will just get forgotten now that it's closed

**Comment by Nolin7777** [comment]
Thanks!

**Comment by redmagejoe** [comment]
All summoned pets from NPCs appear to suffer from this lack of threat table. I can confirm this is still an issue as of today, first noticed in Deadmines with the Goblin Engineer robots.

**Comment by Zeyla-TW** [comment]
I believe if their target dies then they have a threat table as normal, so it could be some sort of fixate mechanic built into the summon spell itself. i believe deathknights in naxx summon adds without a specific target, so they function normally?

**Comment by redmagejoe** [comment]
List of affected NPCs (will update this as I find them):
https://database.turtle-wow.org/?npc=2520
https://database.turtle-wow.org/?npc=6250
