### ISSUE TITLE
I spend mats on enchanting but doesnt work, no any effects happen.

### ISSUE THREAD

**Issue by Solord1207** [slowtorta/turtlewow-bug-tracker#5402]
**Please, provide a clear description what the bug is:**

**Steps to reproduce the behavior with as much detail as possible:**

1.I've enchanted my gloves on healing spell+ 30 ,but it doesn't work . no any effects on my gloves.
2. Also happend before with my chest,brace enchanting, Alliance enchanter enchanted me as a horde. 
3. i dont remember if we are in one grp at that moment.
4. I'm a wanderer before .now im lvl 60. also i deleted the 'WDB' many times.
5. I wish I could bring my mats back or show the right effects on my euipment, that is expensive to me. Charactor name: "Blower"

**IDs of affected creatures, items, quests or spells with a link to the relevant page:**

NPC: https://database.turtle-wow.org/?npc=
Item: https://database.turtle-wow.org/?item=
Quest: https://database.turtle-wow.org/?quest=
Spell: https://database.turtle-wow.org/?spell=
Object: https://database.turtle-wow.org/?object=

**Expected behavior. Describe how it should work:**

**Comment by AKryukov92** [comment]
Same as https://github.com/slowtorta/turtlewow-bug-tracker/issues/4829
