### ISSUE TITLE
Corrupted Whipper Root

### ISSUE THREAD

**Issue by ProktorB** [slowtorta/turtlewow-bug-tracker#5407]
I've completed the quest for Corrupted Whipper Root a few time now but after cleansing it and looting it it contains no loot.

**Comment by AKryukov92** [comment]
According to https://github.com/slowtorta/turtlewow-bug-tracker/issues/5332
it is fixed, but fix is not on main server yet.

**Comment by ratkosrb** [comment]
It will be fixed soon.
