### ISSUE TITLE
one shot one kill

### ISSUE THREAD

**Issue by geojak** [slowtorta/turtlewow-bug-tracker#541]
**Please, provide a clear description what the bug is:**

the qeust one shot one kill in dakrhore you need to protect a nightelf npc from waves of furbolgs.
in classic she will help you and shoot arrows until she runs out of arrow.

on this server she will say she has run out of arrows after the second wave despite never having shot a single one
**Steps to reproduce the behavior with as much detail as possible:**

1. start one shot one kill
2.  observe the npc doesnt shoot arrows

**IDs of affected creatures, items, quests or spells with a link to the relevant page:**

NPC: https://database.turtle-wow.org/?npc=
Item: https://database.turtle-wow.org/?item=
Quest: https://database.turtle-wow.org/?quest=
Spell: https://database.turtle-wow.org/?spell=
Object: https://database.turtle-wow.org/?object=

**Expected behavior. Describe how it should work:**

npcs shoots arrows until she runs out of arrows

**Comment by slowtorta** [comment]
This will be fixed on the next server update, thank you for the report.
