### ISSUE TITLE
Marshal Windsor didn’t respwan 

### ISSUE THREAD

**Issue by tandta** [slowtorta/turtlewow-bug-tracker#5410]
**Please, provide a clear description what the bug is:**

**Steps to reproduce the behavior with as much detail as possible:**

1.I get the quest Stormwind Rendezvous from Marshal Maxwell in Morgan’s Vigil. Then I went to Stormwind,but someone already talked to Marshal Windsor. 
2. So I abandoned the Stormwind Rendezvous ang went to Morgan’s Vigil to get it again. Then I went to Stormwind city gates again. But Marshal didn’t respwan at the city borders.
3. I repeated point 2 twice, but Marshal didn’t respwan.
4. I stucked in this important chain quest. 

**IDs of affected creatures, items, quests or spells with a link to the relevant page:**

NPC: https://database.turtle-wow.org/?npc=Marshal Windsor
Item: https://database.turtle-wow.org/?item=
Quest: https://database.turtle-wow.org/?quest=Stormwind Rendezvous 
Spell: https://database.turtle-wow.org/?spell=
Object: https://database.turtle-wow.org/?object=

**Expected behavior. Describe how it should work:**
Expected the NPC Marshal Windsor respawn to start the quest.

**Comment by twowTurtReynolds** [comment]
He doesn't respawn at that part. Iirc you need to call him with the NPC at the gate.

**Comment by tandta** [comment]
I mean the NPC wasn't respawn at the gate! I can’t call him and can’t turn in the quest at the gate!

**Comment by twowTurtReynolds** [comment]
What happens when someone else calls him for you?
