### ISSUE TITLE
Cell Heater Off-hand and divine spirit conflicting? Wrong amount of spirit

### ISSUE THREAD

**Issue by Skruttis** [slowtorta/turtlewow-bug-tracker#5414]
**Please, provide a clear description what the bug is:**
Cell Heater Off-hand and Divine Spirit buff is somehow conflicting with each other and does not give you the correct total amount of spirit. 
When Cell Heater is equipped without Divine Spirit present, the amount of spirit added is correct. (+10)
When I buff myself with Divine Spirit (Rank 1) which gives +17 spirit, only +13 spirit is added to my total.

**Steps to reproduce the behavior with as much detail as possible:**

1. Unequip weapons and buffs. Check total amount of spirit.
2. Equip Cell Heater. Check total amount of spirit.
3. Buff with Divine Spirit. Check total amount of spirit.

**IDs of affected creatures, items, quests or spells with a link to the relevant page:**
https://database.turtle-wow.org/?item=80724
https://database.turtle-wow.org/?spell=7363
https://database.turtle-wow.org/?spell=14752

**Expected behavior. Describe how it should work:**
When Cell Heater is equipped and you are buffed with Divine Spirit (Rank 1) you should get 10 spirit from Cell heater and 17 from the buff.

![1](https://github.com/slowtorta/turtlewow-bug-tracker/assets/152309898/f7178d92-0280-470d-b9aa-f0631ca20912)
![2](https://github.com/slowtorta/turtlewow-bug-tracker/assets/152309898/cb22fd43-dad4-4854-98aa-8766cb193cf6)
![3](https://github.com/slowtorta/turtlewow-bug-tracker/assets/152309898/6e64da12-32a2-41af-a5c7-b83cfd343423)

**Comment by balakethelock** [comment]
The same bug is gonna keep on creeping out for every custom addition until it's given a real fix
I don't even have to link it here cause we all know what bug im talking about, it's already linked in 15 different bug reports
