### ISSUE TITLE
Rogue Stealth  CORE SKILL IS BROKEN 

### ISSUE THREAD

**Issue by xAzeroth** [slowtorta/turtlewow-bug-tracker#5415]
Hello ,  

Class : Rogue 
Skill  : Stealth    (CORE PROBLEM ) 

I am lvl  60 and Monster is lvl 54 and when you trying to pickpocketing  monster turns on you and very possible to attack you  even with my SUB talents what I will post picture +   in BRD  you will get 3 silver per mob from pickpocketing while you can get same money from Scarlet Monastery wich is around lvl  30  , I hope you fellas will fix this shit and stop trolling rogue class becouse this is  core problem of skill  if you think everything is normal than I suggest you to remove Defense Stance from warrior and tell warrior to Tank in  Berserker Stance !    
![idiotsdev](https://github.com/slowtorta/turtlewow-bug-tracker/assets/132115122/004e9b23-9844-40d5-ac94-daf4b1517172)

**Comment by xAzeroth** [comment]
still in normal classics this never happend 
 while you in high stealth

**Comment by redmagejoe** [comment]
Turtle isn't based on Classic.  It's based on Vanilla.  I wouldn't be surprised with all the dumbing down changes Classic made if this behavior of Pickpocket was removed.

**Comment by Muigin** [comment]
Not a bug.

Working as intended.
