### ISSUE TITLE
Curse of the Void not available

### ISSUE THREAD

**Issue by Josey-Wales1979** [slowtorta/turtlewow-bug-tracker#5416]
**Please, provide a clear description what the bug is:** Quest for creature of the void is not available.  Quest should be available at lvl 10.  My character is lvl 12 and it still shows greyed out.

**Steps to reproduce the behavior with as much detail as possible:**

1. Try to complete quest Curse of the void.  Exlamation point is grey not yellow.
2. 
3. 

**IDs of affected creatures, items, quests or spells with a link to the relevant page:**

NPC: https://database.turtle-wow.org/?npc=Carendin Halgar
Item: https://database.turtle-wow.org/?item= Egalins Grimoire
Quest: https://database.turtle-wow.org/?quest= Creature of the Void
Spell: https://database.turtle-wow.org/?spell=
Object: https://database.turtle-wow.org/?object=

**Expected behavior. Describe how it should work:** Should be able to right click and do quest.

**Comment by ratkosrb** [comment]
Did you complete the previous step in the quest chain? [Halgar's Summons](https://classicdb.ch/?quest=1478)

**Comment by Josey-Wales1979** [comment]
> Did you complete the previous step in the quest chain? [Halgar's Summons](https://classicdb.ch/?quest=1478)

Thank you, I am not too sharp today.  found him in Brill.
