### ISSUE TITLE
No drop limit for Dirty Old Ring

### ISSUE THREAD

**Issue by Gasan918** [slowtorta/turtlewow-bug-tracker#5418]
**Please, provide a clear description what the bug is:**

There is no drop limit for quest starting item named Dirty Old Ring. But player needs only one.

**Steps to reproduce the behavior with as much detail as possible:**

1. Start hunting murlocs near Goldshire until you get first item
2. Don't start ring quest
3. Continue hunting murlocs and get more and more rings dropped (that you cant loot however)

![image](https://github.com/slowtorta/turtlewow-bug-tracker/assets/96973359/f560c417-4859-4661-9ee7-cfe061fe058a)

**IDs of affected creatures, items, quests or spells with a link to the relevant page:**

NPC: https://database.turtle-wow.org/?npc=285
Item: https://database.turtle-wow.org/?item=51855

**Expected behavior. Describe how it should work:**

One ring is enough.

**Comment by Muigin** [comment]
This is the way most if not all quest-starting items behave if you do not start the quest they give.  Given the quest is not repeatable and the ring is unique, this is not an issue. There is not currently a method to check a player's inventory when determining whether a loot window will contain a specific quest-starting item.
