### ISSUE TITLE
Nature's Gift - inconsistent sheathe

### ISSUE THREAD

**Issue by SlackingCat** [slowtorta/turtlewow-bug-tracker#5419]
Hello,

This is not as much of a bug, but most likely an error with one of the items added in patch 1.17. I am talking about [Nature's Gift] from the raid 'Emerald Sanctum'.
https://database.turtle-wow.org/?item=84503

Its sheathe is "wrong". It's inconsistent with sheathes of every other staff in the game. I am pretty sure that it uses polearm sheathe instead of staff sheath.

I am attaching two pictures. First picture shows the [Nature's Gift] sheathe and the second shows [Ansirem's Runeweaver] sheathe. Both items are staves and yet they use different sheathes. 
Below link to [Ansirem's Runeweaver]:
https://database.turtle-wow.org/?item=61264

![Nature's gift](https://github.com/slowtorta/turtlewow-bug-tracker/assets/152332367/355887f3-e296-4f9c-bf25-0542fff25b67)
![Ansirem's Runeweaver](https://github.com/slowtorta/turtlewow-bug-tracker/assets/152332367/091e1014-8fb5-4514-a93e-0ec8cbfeba79)

It doesn't seem like a lot, but it really sticks out, looks weird and out of place. I have asked other fellow players about it and they agreed with me.

**Comment by SlackingCat** [comment]
I am also adding a picture with a similar staff that night elf druids start with. I believe that [Nature's Gift] should have its sheathe corrected as it does look more proper and is consistent with the every other staff weapon in the game.

![image](https://github.com/slowtorta/turtlewow-bug-tracker/assets/152332367/63d4252a-ad67-4d75-8000-53c29b54c983)

**Comment by twowTurtReynolds** [comment]
Looks like this and https://github.com/slowtorta/turtlewow-bug-tracker/issues/4932 are related, pointing NE instead of NW.

**Comment by twowTurtReynolds** [comment]
![image](https://github.com/slowtorta/turtlewow-bug-tracker/assets/151180101/ca8dcdbb-c88f-4fa9-b3f1-491f28d54c2e)
