### ISSUE TITLE
alliance flighpoints on easter kigndoms displayed shifted on map

### ISSUE THREAD

**Issue by geojak** [slowtorta/turtlewow-bug-tracker#542]
**Please, provide a clear description what the bug is:**

**Steps to reproduce the behavior with as much detail as possible:**

1. get irnfroge flightpoint
2. get lock modan flightpoint
3. get menethil flighpoint
3. to to stowrwind flighmaster
4. speak with the flightmaster in sw and lok at the map with the nodes
5. see that ironfroge is displayed rougly where menethil should be and menethil is in the water

**IDs of affected creatures, items, quests or spells with a link to the relevant page:**

NPC: https://database.turtle-wow.org/?npc=
Item: https://database.turtle-wow.org/?item=
Quest: https://database.turtle-wow.org/?quest=
Spell: https://database.turtle-wow.org/?spell=
Object: https://database.turtle-wow.org/?object=

**Expected behavior. Describe how it should work:**

flightpoints displayed on the map where they are and not shifted

**Comment by geojak** [comment]
i did delete WDB by the way and other peoples also experiece this issue when i asked

**Comment by geojak** [comment]
i can provide a screenshot if needed

**Comment by CosminPOP** [comment]
known, will be fixed on next patch (1.16)
