### ISSUE TITLE
[Portable Wormhole Generator: Stormwind] teleport horde characters to Orgrimmar

### ISSUE THREAD

**Issue by Shellyoung** [slowtorta/turtlewow-bug-tracker#5428]
**Please, provide a clear description what the bug is:**
[Portable Wormhole Generator: Stormwind](https://database.turtle-wow.org/?item=51312) if used by a horde character teleport him to Orgrimmar instead of Stormwind. Maybe the Orgrimmar version does not work too.

**Steps to reproduce the behavior with as much detail as possible:**
1. Use the item while being horde.

**IDs of affected creatures, items, quests or spells with a link to the relevant page:**
[Portable Wormhole Generator: Stormwind](https://database.turtle-wow.org/?item=51312)

**Expected behavior. Describe how it should work:**
I think it should teleport horde to Stormwind.

**Comment by twowTurtReynolds** [comment]
This is a holdover from when the wormhole wasn't an engineering device. I will ask the staff about if we want to keep these this way, or allow people to portal into enemy cities....

**Comment by twowTurtReynolds** [comment]
Changelog:
> Added race restrictions to Stormwind and Orgrimmar's Portable Wormhole Generators for Engineering to prevent cross-faction abuse.

This will mean you won't be able to make or have SW portals as a horde and vice versa.


As for using an enemy faction's created portal... this is under discussion

**Comment by Shellyoung** [comment]
Maybe it shouldn't be allowed to learn by horde faction characters?
I think I saw horde characters appearing in Stormwind's mage towers at the teleportation spot.

**Comment by twowTurtReynolds** [comment]
> [Added race restrictions to Stormwind and Orgrimmar's Portable Wormhole Generators for Engineering to prevent cross-faction abuse.](https://forum.turtle-wow.org/viewtopic.php?f=63&t=12065)

I have been contacted by people that have ended up wasting or will continue to waste resources in the future. We are running a migration now for next week's update to fully complete this change, and change anyone's existing wrong faction devices to the correct one.
