### ISSUE TITLE
Guardians of Icecrown at Kel'Thuzad immune to shackle

### ISSUE THREAD

**Issue by EgorShalamov** [slowtorta/turtlewow-bug-tracker#5432]
**Please, provide a clear description what the bug is:**
Hey, my guild noticed that with last update (29.11.2023) - Guardians of Icecrown at Kel'Thuzad become immune to shackle.
As we know at blizz servers (and previously) - we could shackle them

**Steps to reproduce the behavior with as much detail as possible:**

1. Go to Kel'Thuzad
2. Try to kill him
3. Wait phase with adds (40% boss HP)

**IDs of affected creatures, items, quests or spells with a link to the relevant page:**

NPC: https://database.turtle-wow.org/?npc=16441
Spell: https://database.turtle-wow.org/?spell=10955

**Expected behavior. Describe how it should work:**
Expected result: priests should be able to shackle adds
Actual result: mobs are immune to shackle

**Comment by twowTurtReynolds** [comment]
![image](https://github.com/slowtorta/turtlewow-bug-tracker/assets/151180101/a2187d3a-0f57-4f81-bd8d-b898297c34c2)

Replicated. Big issue! I'll get this escalated.

**Comment by ratkosrb** [comment]
@balakethelock The wrong ones can be counted on your fingers. I can quickly fix those reported. Soon I will make a mass update to remove wrong ones too.
