### ISSUE TITLE
Clip under slope in Boulderslide Cavern

### ISSUE THREAD

**Issue by kidddd66** [slowtorta/turtlewow-bug-tracker#5433]
**Please, provide a clear description what the bug is:**
I encountered a glitchy slope (58.5/89.4) in the cave Boulderslide Cavern in Stonetalon Mountains, under which you are able to clip. It kind of looks like one of those places that you might be able to fall off the world but I haven't tested whether that's possible. Video showing this in action https://youtu.be/FJcu9mSkM4M

**Steps to reproduce the behavior with as much detail as possible:**

1. Go to Boulderslide Cavern in Stonetalon Mountains in the exact spot (58.4/89.3) in the video near the two stone pillars.
2. Allign so that the stone pillars are on your LEFT side and you are facing the slope the following way https://i.imgur.com/VZCYA2C.png
3. Go forward. If you don't clip - go backwards, jump and try again

**IDs of affected creatures, items, quests or spells with a link to the relevant page:**

NPC: N/A
Item: N/A
Quest: N/A
Spell: N/A
Object: N/A

**Expected behavior. Describe how it should work:**
Should not be able to clip under that slope.

**Comment by twowTurtReynolds** [comment]
![image](https://github.com/slowtorta/turtlewow-bug-tracker/assets/151180101/6b229b36-ca09-48af-9b8a-c408a61c1ff5)
I can't reproduce this.
