### ISSUE TITLE
Invocation of Greater Protection Cannot be Applied to Head or Legs

### ISSUE THREAD

**Issue by Licklovingly** [slowtorta/turtlewow-bug-tracker#5434]
**Please, provide a clear description what the bug is:**
I cannot apply new +2 Dodge enchant from Karazhan to my legs or head items. Once I try to do that, I get an error "That item is not a valid target"

I can apply this item to my shoulder slot tho. But it doesn't make sense as the item description is different. 

**Steps to reproduce the behavior with as much detail as possible:**
1. Get item Invocation of Greater Protection.
2. Use it.
3. Apply enchant to Head or Legs (equipped or unequipped)

**IDs of affected creatures, items, quests or spells with a link to the relevant page:**
Item ID: 92006
Item: https://database.turtle-wow.org/?item=92006

**Expected behavior. Describe how it should work:**

Player must be able to apply the enchant produced by item=92006 to the head or legs slot items. Enchant must give +2% Dodge Chance as described in item description.

**Comment by twowTurtReynolds** [comment]
Do not create duplicate issues, especially of pinned issues.
