### ISSUE TITLE
jin'zil's stew

### ISSUE THREAD

**Issue by forrestss** [slowtorta/turtlewow-bug-tracker#5435]
**Please, provide a clear description what the bug is:**

Unable to turn in quest, Jin'Zil's Stew in Stonetalon Mountains. The quest log shows it as complete and I have all the essential items in my bags but the jin'zil npc is not showing an option for turning in the quest.

**Comment by twowTurtReynolds** [comment]
Please see https://github.com/slowtorta/turtlewow-bug-tracker/issues/6042
