### ISSUE TITLE
Quest log keeps collapsing my list of quests every time I accept a new quest

### ISSUE THREAD

**Issue by ghost** [slowtorta/turtlewow-bug-tracker#5436]
**Please, provide a clear description what the bug is:**
Quest log keeps collapsing every time I accept a new quest

**Steps to reproduce the behavior with as much detail as possible:**

1. Accept Quest
2. Quest Log Collapses
3. 

**Expected behavior. Describe how it should work:**
The quest log never did this before. Suddenly started doing it randomly and is happening on all of my characters.

Additional things ive tried that havnt worked:
-Complete reinstall
-Using addons that change the quest log interface in some way

**Comment by twowTurtReynolds** [comment]
You have some addon that is causing this. When you do a full reinstall, don't go and reinstall your addons too.

This doesn't happen without these bad addons, I and everyone else can confirm.
