### ISSUE TITLE
Hawk's Vigil and Lapidis Inn share a name

### ISSUE THREAD

**Issue by Tomagazda** [slowtorta/turtlewow-bug-tracker#5437]
**Please, provide a clear description what the bug is:**

**Steps to reproduce the behavior with as much detail as possible:**

1. The Inn name in Hawk's Vigil called Caelan's Rest Inn, when you walk in with character

**Expected behavior. Describe how it should work: **
It should have a different name, not the one from Lapidis
![image](https://github.com/slowtorta/turtlewow-bug-tracker/assets/83549873/c93f6d8e-5f35-4c76-8c32-33dcd88d03f6)

**Comment by slowtorta** [comment]
Fixed in 1171.
