### ISSUE TITLE
Invocation Of Shattering "that Item is not a valid target" 

### ISSUE THREAD

**Issue by onyxvine** [slowtorta/turtlewow-bug-tracker#5442]
Invocation Of Shattering Kara +75 armor pen head/leg slot not working

**Steps to reproduce the behavior with as much detail as possible:**

1.Get enchant
2.Click to put on either head or leg slot
3. "That Item is not a valid target" error message

**IDs of affected creatures, items, quests or spells with a link to the relevant page:**

NPC: https://database.turtle-wow.org/?npc=
Item: [https://database.turtle-wow.org/?item=92005](https://database.turtle-wow.org/?item=92005&fbclid=IwAR1T5GkPaFUMO0dqmhf6zuOXvedroFnhy8bAD2lCESzF3869MzaiqUHLzf0)
Quest: [https://database.turtle-wow.org/?quest=41079](https://database.turtle-wow.org/?quest=41079&fbclid=IwAR20HBOsfU4RPnDKk6_pphWda24DdPm0u_4aEJRdauzZc1OtoIPQY2FOW-Q)
Spell: https://database.turtle-wow.org/?spell=
Object: https://database.turtle-wow.org/?object=

Should be able to enchant both head and leg armor slots

**Comment by twowTurtReynolds** [comment]
Do not create duplicate issues, especially of pinned issues.
