### ISSUE TITLE
can't get the quest "The Long Night Is Not Over"

### ISSUE THREAD

**Issue by HenryPangu** [slowtorta/turtlewow-bug-tracker#5443]
I can't get the quest "The Long Night Is Not Over", it should be repeatable, what can i do?

character ID: Crimsonlee

**IDs of affected creatures, items, quests or spells with a link to the relevant page:**

https://database.turtle-wow.org/?quest=40221

**Expected behavior. Describe how it should work:**

**Comment by twowTurtReynolds** [comment]
Revered or higher is required. Works fine.
