### ISSUE TITLE
Thunderfury quest item not dropping off Prince Thunderaan - Possibly Master looter settingissue?

### ISSUE THREAD

**Issue by nallchan2** [slowtorta/turtlewow-bug-tracker#5444]
**Please, provide a clear description what the bug is:**
Performing the Thunderfury Final Quest in the crystal Vale (Sithlus) - When defeating Prince Thunderaan he did not drop the quest piece. It appears that "Master Looter" might prevent the quest item from dropping?

**Steps to reproduce the behavior with as much detail as possible:**

1.Kill Prince thunderaan
2. Unable to loot Quest item
3. 

**IDs of affected creatures, items, quests or spells with a link to the relevant page:**

NPC: https://database.turtle-wow.org/?npc=14435
Item: https://database.turtle-wow.org/?item=
Quest: https://database.turtle-wow.org/?quest=7787
Spell: https://database.turtle-wow.org/?spell=
Object: https://database.turtle-wow.org/?object=

**Expected behavior. Describe how it should work:**
Being able to loot the final quest item for thunderfury

**Comment by twowTurtReynolds** [comment]
Replicated. 

![image](https://github.com/slowtorta/turtlewow-bug-tracker/assets/151180101/1a790468-83de-4117-b361-5a30a139bab3)

But, you can just change the loot to FFA and it works.

![image](https://github.com/slowtorta/turtlewow-bug-tracker/assets/151180101/9821e834-e983-470b-89a4-761ae335d2d1)

This is fine.
