### ISSUE TITLE
The Ravenwood Scepter Quest Bug

### ISSUE THREAD

**Issue by Moomin82** [slowtorta/turtlewow-bug-tracker#5448]
After handing in the quest Through Greater Magic (40993), i pressed to accept the next one, The Ravenwood Sceptor (40994). During Dark Bishop Modren (19159) animation. And now the quest is gone, from both NPC, and its not in my questlog either.

Ive tried deleting my WDB folder. With no luck, I have travled to another zone, back again. Ive tried relogging. 
Nothing helps.

Maybe i shouldnt have tried to accept the quest, while he was casting his animation. But never the less. There is a bug.

I would just like to be on the Ravenwood Scepter. Tried getting one on it, to share, but its unshareable.. :(
Cant a GM give me the quest?

Character ID: Oxymorphone - Tel'abim

**Comment by twowTurtReynolds** [comment]
Contact a GM so they can `.quest add 40994` for you, if you haven't already. 

I tested this, and I was unable to pick up the quest during the RP animation, but once the animation ended, I was able to pick up the quest no problem.

Thank you for the IDs, it makes testing this really fast on us :)
