### ISSUE TITLE
[Nightmare Dreamrunner] bugginess and lack of features.

### ISSUE THREAD

**Issue by ShiraZen** [slowtorta/turtlewow-bug-tracker#5449]
**Please, provide a clear description what the bug is:**

The [Nightmare Dreamrunner] store mount's animations are broken. If you walk backwards the animation continuously bugs out and glitches all over the place, and you can't press spacebar to neigh.

This is a store mount, I feel like buying this only for it to be broken is really not a good look.

**Steps to reproduce the behavior with as much detail as possible:**

1. Walk backwards.
2. Press Spacebar.
3. Weird things happen.

**IDs of affected creatures, items, quests or spells with a link to the relevant page:**

Item: https://database.turtle-wow.org/?item=50407

**Expected behavior. Describe how it should work:**

Walking backwards shouldn't result in a glitchy mess, and pressing spacebar should cause the horse to whinny!

**Comment by ShiraZen** [comment]
Oh, and I'm not sure if this is intended, but the hoofs around the mount's feet have no effect, in spite of being the exact same as the Warlock horses who's hooves have a burning effect.

**Comment by twowTurtReynolds** [comment]
![horse](https://github.com/slowtorta/turtlewow-bug-tracker/assets/151180101/04bac891-6cce-4289-b5d4-e1aa99ff9263)
Fixed in next patch :)
