### ISSUE TITLE
captain sunders treasure map not soulbound

### ISSUE THREAD

**Issue by geojak** [slowtorta/turtlewow-bug-tracker#545]
**Please, provide a clear description what the bug is:**

captain sunders treasure map is a qeust starting drop from murlocs in westfall. it is supposed to be souldbound. my gf just started the qeust then traded it to me to also start it. this is not blizzlike.

**Steps to reproduce the behavior with as much detail as possible:**

1. loot the treasure map
2. start the quest
3. sell it in the ah trade to other players

**IDs of affected creatures, items, quests or spells with a link to the relevant page:**

NPC: https://database.turtle-wow.org/?npc=
Item: https://database.turtle-wow.org/?item=
Quest: https://database.turtle-wow.org/?quest=
Spell: https://database.turtle-wow.org/?spell=
Object: https://database.turtle-wow.org/?object=

**Expected behavior. Describe how it should work:**

item soulbound after starting the qeust

**Comment by rptb1** [comment]
I believe this item was available on the Auction House in vanilla.

**Comment by geojak** [comment]
ok, then i close this issue

**Comment by geojak** [comment]
I thought it would be souldboind after accepting the quest
