### ISSUE TITLE
Armaments of War quest not providing the correct rewards according to spec.

### ISSUE THREAD

**Issue by TehN1k0** [slowtorta/turtlewow-bug-tracker#5451]
**Please, provide a clear description what the bug is:**

**Steps to reproduce the behavior with as much detail as possible:**

1. First do all the prequests and finally the raid quest "the calling quest"
2. NPC will then show a questionmark for the followup quest "Armaments of war"
3. I then talk to the NPC again but instead of offering different quests/rewards you only get to see one. In my case its the nature ress pants with healing on them and i am a feral, so I want the feral version with AP: https://database.turtle-wow.org/?item=20703

**IDs of affected creatures, items, quests or spells with a link to the relevant page:**

NPC: https://database.turtle-wow.org/?npc=15183
Item: https://database.turtle-wow.org/?item=20704
Quest: https://database.turtle-wow.org/?quest=8378

**Expected behavior. Describe how it should work:**

I talked to GM Cringeniero and he told me the NPC should probably offer different quests/rewards so people can pick the right one according to their spec. But Ive tried everything, it doesn't matter what I do the NPC only offers the healing versions of the pants and boots while im a feral.

Right now the NPC offers me only this as reward: https://database.turtle-wow.org/?quest=8379
While I want these as rewards: https://database.turtle-wow.org/?quest=8378

But as you can see here: https://database.turtle-wow.org/?quest=8315 he should be able to give all kinds of quests/rewards. So I dont know if its a bug or just random and working as intended, please advice!

**Comment by twowTurtReynolds** [comment]
This is blizzlike, as there are many duplicates of this quest, one per 1-3 classes. Please post this to the suggestions form instead.
