### ISSUE TITLE
Farmer Getz's house walls

### ISSUE THREAD

**Issue by Hydra9268** [slowtorta/turtlewow-bug-tracker#5453]
**Please provide a clear description of what the bug is:**

In Hillsbrad Fields, Hillsbrad Foothills, I sent my pet to attack Farmer Getz and another NPC in the house. Both NPCs were able to run out of the home through its walls. I couldn't get the first kill because my pet attacked Getz and the NPC inside the walls. 

After the first attempt, I waited for Getz to respawn. I set my pet to aggressive, and this pulled a nearby farmer NPC, who ran through the walls into the house.

Location: 37,39

Screenshot of the house:

https://i.imgur.com/XDGISx3.jpeg
https://i.imgur.com/14a2sQ7.jpeg

Location on the map:

https://i.imgur.com/6kw5ID0.jpeg

**Steps to reproduce the behavior with as much detail as possible:**

1. Go inside the house at 37,39 in Hillsbrad Fields, Hillsbrad Foothills.
2. Pull an outside NPC from inside the house and position yourself to see the target run through the walls.
3. Conversely, if you have a pet, send the pet to attack the target and observe the NPC and your pet running through the walls.

**IDs of affected creatures, items, quests, or spells with a link to the relevant page:**

NPC: https://database.turtle-wow.org/?npc=2403
Quest: https://database.turtle-wow.org/?quest=527

**Expected behavior. Describe how it should work:**

No NPCs and pets should be able to run through the walls of the house.

**Comment by twowTurtReynolds** [comment]
![image](https://github.com/slowtorta/turtlewow-bug-tracker/assets/151180101/a73a0123-3baa-41de-aede-06761343c74a)
I sent my pet in and recalled him back.
I did see them spaz out a slight bit, but they seem to path around just fine.
![image](https://github.com/slowtorta/turtlewow-bug-tracker/assets/151180101/84869fe4-9fd4-4652-a979-148df4fd5bdd)
