### ISSUE TITLE
Anjira Ruins Hunter weapon displays incorrectly

### ISSUE THREAD

**Issue by qingtianmy** [slowtorta/turtlewow-bug-tracker#5454]
The WDB file has been deleted, as shown in the screenshot, the weapon model is not displayed
![11](https://github.com/slowtorta/turtlewow-bug-tracker/assets/151704395/8426b340-3654-455e-a227-63e95e5ed997)
![22](https://github.com/slowtorta/turtlewow-bug-tracker/assets/151704395/6c5f7dfd-e0a2-4fbc-9106-70b17bd5ec52)

**Comment by zdj521120** [comment]
Because this weapon is meant to be hidden
