### ISSUE TITLE
Klockmort Spannerspan is missing

### ISSUE THREAD

**Issue by nathanpaulyoung** [slowtorta/turtlewow-bug-tracker#5456]
The quest NPC Klockmort Spannerspan is missing. He should be in the Gnomeregan Reclamation Facility and is not, even after waiting nearly an hour. I submitted a ticket and GM Othram confirmed the absence of the NPC and told me to submit a bug report.

NPC: https://database.turtle-wow.org/?npc=6169

**Comment by nathanpaulyoung** [comment]
Update: Klockmort isn't missing, he is just incorrectly located in Ironforge. GM Othram teleported me to the spot where it should have been, which was where I was waiting. So Not sure what's going on here.

![image](https://github.com/slowtorta/turtlewow-bug-tracker/assets/3195542/7c645d99-ab34-48bd-9776-ce75391da7d9)

**Comment by octav3k** [comment]
I reported this a week or so ago and they fixed it, but now he's back in IF. Someone said that the NPC resets to Ironforge after turning in the warrior quest or something like that, so it needs some looking into.

**Comment by nathanpaulyoung** [comment]
Yeah, I was back in the Gnomeregan Reclamation Facility just a few hours later and saw the lil guy back home where he belongs. I had assumed that the devs had fixed it, but your explanation makes more sense.

**Comment by twowTurtReynolds** [comment]
https://github.com/slowtorta/turtlewow-bug-tracker/issues/5376 This NPC keeps bouncing back and forth, our team is aware.
![image](https://github.com/slowtorta/turtlewow-bug-tracker/assets/151180101/d09962c1-b44a-4ee4-85ba-5e765b191d1e)
On the PTR, he is correctly where he should be:
![image](https://github.com/slowtorta/turtlewow-bug-tracker/assets/151180101/86352307-0fd5-46fe-b32c-3b6b87b6044b)
If after tomorrow's restart, if he is still incorrectly in tinker town, please ping me and let me know, but it should be all good now :)
