### ISSUE TITLE
Tier drops from Rag/Ony

### ISSUE THREAD

**Issue by vesper30** [slowtorta/turtlewow-bug-tracker#5457]
Rag/Ony Still only dropping one piece of tier loot on Tel'abim. Date 01/12/23

https://database.turtle-wow.org/?npc=11502
https://database.turtle-wow.org/?npc=10184

Should drop two pieces of tier loot per kill as stated in the most recent maintenance patch notes.

**Comment by scheminpete** [comment]
This is still bugged! Rag/Ony still dropped 1 piece of tier each as of 30 Nov. 

This is very frustrating as the patch notes from 29 Nov said it was changed: "Onyxia and Ragnaros will now drop 2 tier set pieces as intended on Tel'Abim PvP." https://forum.turtle-wow.org/viewtopic.php?t=11972&sid=e2ce7f8afb9e5137734e523032d1f756
