### ISSUE TITLE
My pet's "attack" button is missing

### ISSUE THREAD

**Issue by Lifesse** [slowtorta/turtlewow-bug-tracker#5459]
**Please, provide a clear description what the bug is:**

I'm a hunter leveling 57. My ID is Lifesse of Turtle Wow server.

My pet's attack button is missing. I've tried to delete the WTF folder, all my addons and even deleted the game and downloaded it again, but they didn't work. The button wasn't supposed to be  dragged out.

I've stabled my cat and tamed a wolf, it has the "attack" button. So, it seems only my cat lost its attack button.

**Steps to reproduce the behavior with as much detail as possible:**

1. I don't know how it disappeared.
2. I was just slainning mobs in the Winterspring and it happened
3. 

**IDs of affected creatures, items, quests or spells with a link to the relevant page:**

NPC: https://database.turtle-wow.org/?npc=
Item: https://database.turtle-wow.org/?item=
Quest: https://database.turtle-wow.org/?quest=
Spell: https://database.turtle-wow.org/?spell=
Object: https://database.turtle-wow.org/?object=

**Expected behavior. Describe how it should work:**

**Comment by twowTurtReynolds** [comment]
Please let us know exactly what you did in between the moment where your pet had Attack, and when it didn't. There must have been some odd interaction that was done to cause this.

**Comment by SuqMadiqM8** [comment]
You most likely accidentially removed it from the pet bar by dragging it off instead of just clicking it. Call your pet, open the spell book (p), click on the pet tab on the bottom, find the pet action you're looking for, drag it back on the pet bar as you would with your own spells and ranks.

**Comment by cyaohiri** [comment]
It shouldn't be possible to drag off default pet action buttons. Try it with the Follow or Stay commands.

**Comment by twowTurtReynolds** [comment]
I was unable to drag any of the 6 default actions off the bar. @Lifesse if issues persist with a fresh client install and no addons, maybe contact a GM.
