### ISSUE TITLE
loch modan crocodile hunt qeust items droprate

### ISSUE THREAD

**Issue by geojak** [slowtorta/turtlewow-bug-tracker#546]
**Please, provide a clear description what the bug is:**

in loch modan you can get the crocodile hunt in the lodge where the high elfs start now.
that quest has you collect 6 crocolisk meat and 5 skins.
both of these appear to have 100% droprate
this is not blizzlike

**Steps to reproduce the behavior with as much detail as possible:**

1. get the crocolisk qeust in loch modan
2. kill crocolisk
3. after exactly 6 crocolisk the qeust is finished

**IDs of affected creatures, items, quests or spells with a link to the relevant page:**

NPC: https://database.turtle-wow.org/?npc=
Item: https://database.turtle-wow.org/?item=
Quest: https://database.turtle-wow.org/?quest=
Spell: https://database.turtle-wow.org/?spell=
Object: https://database.turtle-wow.org/?object=

**Expected behavior. Describe how it should work:**

less then 100% droprates.
its boring to compelte them that fast. i dont mind slightly increased droprates but not 100%

**Comment by Kruxis** [comment]
Item droprate is not 100%. Got a good RNG there ;)
