### ISSUE TITLE
the sleeper has awakened enemies not spawning

### ISSUE THREAD

**Issue by geojak** [slowtorta/turtlewow-bug-tracker#547]
**Please, provide a clear description what the bug is:**

when doing this quest where you need to walk the druid that falls asleep to ashenvale on the normalw stret, you are supped to get ambushed twice. once by furbolgs near the masters gleive and one time at that empty big elfen house on the street by twilighs.

both times didnt havppen which made this quest pointlessly easy.

**Steps to reproduce the behavior with as much detail as possible:**

1. take sleeper has awakened qeust
2. walk on the street directly to ashenvale
3. no ambushes happen

**IDs of affected creatures, items, quests or spells with a link to the relevant page:**

NPC: https://database.turtle-wow.org/?npc=
Item: https://database.turtle-wow.org/?item=
Quest: https://database.turtle-wow.org/?quest=
Spell: https://database.turtle-wow.org/?spell=
Object: https://database.turtle-wow.org/?object=

**Expected behavior. Describe how it should work:**

2 ambushes spawning if you dont avoiud the road.

**Comment by geojak** [comment]
I mean everyone knows they spawns. That's why all speedruners stay clear of the road, in order to not spawn them, and that's why is close to impossible to find YouTube footage of it.

IF you don't want to fix it, just close ot

**Comment by geojak** [comment]
Wait I found something
https://github.com/Atlantiss/NetherwingBugtracker/issues/1308
They have a proof video in their issue

**Comment by Nolin7777** [comment]
Thanks!

**Comment by redmagejoe** [comment]
This quest is still not properly scripted.

**Comment by redmagejoe** [comment]
Can confirm, the two scripted encounters do not occur on current version.
