### ISSUE TITLE
Weapon Stormfist uses a 1.12-unused spell Shock which when procs puts player-Shocks on cooldown.

### ISSUE THREAD

**Issue by Cocuckas** [slowtorta/turtlewow-bug-tracker#5473]
Stormfist uses rank 2, but all these likely have the same issue and should have their shared cooldown removed:

https://database.turtle-wow.org/?spell=2607
https://database.turtle-wow.org/?spell=2606
https://database.turtle-wow.org/?spell=2608
https://database.turtle-wow.org/?spell=2609
https://database.turtle-wow.org/?spell=2610

**Comment by Cocuckas** [comment]
https://database.turtle-wow.org/?item=61042

**Comment by balakethelock** [comment]
technically... https://github.com/slowtorta/turtlewow-bug-tracker/issues/1768
it's something that happens in blizzard items as well, so it's fine to exist for twow items.

**Comment by twowTurtReynolds** [comment]
Interesting. I will bring this to the designer of the item and see if they want to follow blizzard precedent of this weird interaction, or change both.

**Comment by twowTurtReynolds** [comment]
I confirmed with the item creator, we're gonna follow blizzlike precedent and set the turtlelike precedent as such, that procs very much can trigger class shared cooldowns.

**Comment by Cocuckas** [comment]
In some builds this proc can do some good damage. Thats why i want to use it and hope u can split those CDs :)

**Comment by twowTurtReynolds** [comment]
I'm sorry, as I said, we will be sticking to blizzlike precedent.
