### ISSUE TITLE
Geologist Larksbane - Silithus bugged

### ISSUE THREAD

**Issue by KniightYz** [slowtorta/turtlewow-bug-tracker#548]
**Please, provide a clear description what the bug is:**

NPC Geologist Larksbane  in Silithus [Cenarion Hold] is bugged and wont talk/interact with players (I cannot complete my quest)

**Steps to reproduce the behavior with as much detail as possible:**

1. Approach NPC, right click. No further action happens
2. 
3. 

**IDs of affected creatures, items, quests or spells with a link to the relevant page:**

NPC: https://database.turtle-wow.org/?npc=15183

Item: https://database.turtle-wow.org/?item=
Quest: https://database.turtle-wow.org/?quest=
Spell: https://database.turtle-wow.org/?spell=
Object: https://database.turtle-wow.org/?object=

**Expected behavior. Describe how it should work:**

Should allow me to hand in and complete quest, but the NPC does not interact/ allow player to progress or complete the quest.

**Comment by Tinyfin-github** [comment]
It's this case of issue: https://github.com/slowtorta/turtlewow-bug-tracker/issues/336
The npc has been fixed, you will be able to interact with the npc now.
