### ISSUE TITLE
Raid ID did not reseted 

### ISSUE THREAD

**Issue by Belugaga90** [slowtorta/turtlewow-bug-tracker#5480]
Hello hi,

Yesterday (01/12) my guild and i did a run of karazhan 10 on the Tel Abin realm, and ended it 1-2 hours before the reset time showed in https://turtle-timer.vercel.app/. The problem is that today, we are all still locked in yesterday ID (185), although a reset was supposed to happend. we made sure to leave the instance after we finished, and no one logged out inside it. 

im not sure if that was a bug or the reset timer is not accurate, could you give me more information or help me to solve this issue? my guild had planned a run for today but since we are locked, we wont be able to do that.

thank you in advance,

Beluga.

**Comment by twowTurtReynolds** [comment]
Do not trust 3rd party sources of info, they might have some details wrong.

Trust in the ingame timer, and if you have evidence of those timers being wrong, provide proof and we'll take a second look.
