### ISSUE TITLE
Embassy Blues: reward isn't fair

### ISSUE THREAD

**Issue by Gasan918** [slowtorta/turtlewow-bug-tracker#5481]
**Please, provide a clear description what the bug is:**

Embassy Blues questgiver asks to buy and bring 3 flasks of port. He offers 2s as reward but 3 flasks of port costs 4s50c itself. 

![image](https://github.com/slowtorta/turtlewow-bug-tracker/assets/96973359/43cd126e-fdfa-4b97-a7b4-530d6084197f)
![image](https://github.com/slowtorta/turtlewow-bug-tracker/assets/96973359/7b03cab0-455f-40bd-a302-cd4eb2413604)

"Quite well"?

**IDs of affected creatures, items, quests or spells with a link to the relevant page:**

Item: https://database.turtle-wow.org/?item=2593
Quest: https://database.turtle-wow.org/?quest=40663

**Expected behavior. Describe how it should work:**

The reward should be 6-7 silver. 4s50c for Port plus tips.

**Comment by balakethelock** [comment]
![image](https://github.com/slowtorta/turtlewow-bug-tracker/assets/111737968/3fae34e6-41fc-4b6d-839c-3e9567c6f7c6)

**Comment by twowTurtReynolds** [comment]
The design staff have concluded that the reward of some of the money back, XP, and Rep make up a fair reward.
