### ISSUE TITLE
Casting speed no work for "mind flay" and "Arcane Missiles"

### ISSUE THREAD

**Issue by jin846707134** [slowtorta/turtlewow-bug-tracker#5482]
**Please, provide a clear description what the bug is:**

Under normal circumstances, the cast time of the  "mind flay"  is 3 seconds, but with the casting speed a 10% Haste level, the cast time of the "mind flay" is still 3 seconds. This is also the case "Arcane Missiles" 。

**Steps to reproduce the behavior with as much detail as possible:**

1.Nothing is equip，cast "mind flay"，cast time is 3 seconds。
2. Equip Gloves of Unwinding Mystery
3. cast "mind flay"，cast time is 3 seconds。

**Expected behavior. Describe how it should work:**

When equipping that “Increases your attack and casting speed”，then cast "mind flay" and "Arcane Missiles",The cast time should be increased。

**Comment by jin846707134** [comment]
spell  ID:(https://database.turtle-wow.org/?spell=18807)](https://database.turtle-wow.org/?spell=18807)

All Channeled spell can't increased casting speed ？  IF Channeled spell can't increased casting speed，i don't collect casting speed， no more。

please answer

**Comment by twowTurtReynolds** [comment]
Channels and dots do not benefit from haste, as designed.
