### ISSUE TITLE
Elixirs for the Bladeleafs

### ISSUE THREAD

**Issue by za5adlo** [slowtorta/turtlewow-bug-tracker#5483]
**Please, provide a clear description what the bug is: The NPC Syral Bladeleaf doesnt offer quest Elixirs for the Bladeleafs to players who has Alchemy**

**EDIT. It seems quest is available since player has 20 of Alchemy. Could be nice to add this info to database atleast.**
**EDIT. Need to change rewards from 1 pcs to 6, if its bug (not sure just) - screens below.**
 
**Steps to reproduce the behavior with as much detail as possible:**

1. Right after i got Alchemy (1st level), pfquest showed me i can get this quest from this npc but i cant.
2. I tried to level my alchemy to 15 atleast, but still no quest available.
3. I rechecked database of turtle wow but havnt find any more info about requirements for this quest i could not met (tested by level 10, alchemy 15)
4. Would be nice to add requrement for quest to base - 20 Alchemy

**IDs of affected creatures, items, quests or spells with a link to the relevant page:**

NPC: https://database.turtle-wow.org/?npc=2083 
Item: there is not any item here
Quest: https://database.turtle-wow.org/?quest=1581
Spell: there is not any spell here
Object: there is not any object here

**Expected behavior. Describe how it should work: well it shall just offer the quest since player get Alchemy i guess, any level of it.**

EDIT. I just require 20 Alchemy as i got the point. Would be nice to add requirement.

![bugreport1](https://github.com/slowtorta/turtlewow-bug-tracker/assets/139398642/9c657040-e5cb-4391-918a-936e5981d5b0)
![bugreport2](https://github.com/slowtorta/turtlewow-bug-tracker/assets/139398642/80933264-99fa-4131-9a6d-ac734925dfac)
![bugreport3](https://github.com/slowtorta/turtlewow-bug-tracker/assets/139398642/f1b101fd-095a-4ded-9f29-aef63ffa80c7)

**Comment by twowTurtReynolds** [comment]
According to https://www.wowhead.com/classic/quest=1581/elixirs-for-the-bladeleafs#comments:id=14372 it is blizzlike for this to require alch 20.

Contact the dev of pfquest about this discrepancy in their addon that led you to believe otherwise.
