### ISSUE TITLE
Cannot open Large Solid chest in Dreadmaul Rock cave

### ISSUE THREAD

**Issue by Gensoo** [slowtorta/turtlewow-bug-tracker#5493]
**Please, provide a clear description what the bug is:**

Cannot open large solid chest in dreadmaul rock cave in burning steppes. No errors, no messages, character is level 55, not in combat. 
Tried reloading UI and relogging. Character starts opening animation and cancels instantly. 

Coordinates: 81.9, 44.0 Dreadmaul Rock  cave
[WoW_rxdy1lnzh8.webm](https://github.com/slowtorta/turtlewow-bug-tracker/assets/9191645/a90187cd-8cc5-40de-8446-5338600810b9)

**Comment by twowTurtReynolds** [comment]
![image](https://github.com/slowtorta/turtlewow-bug-tracker/assets/151180101/c9b09e27-a753-42f7-ab6c-d7c97165ee16)

I get a line of sight error.
