### ISSUE TITLE
The Attack! Royal Guards bugged

### ISSUE THREAD

**Issue by Kharkov72** [slowtorta/turtlewow-bug-tracker#5495]
The Stormwind Royal Guards are meant to walk away when Gregor Lescovar tells them to, and they do, but then they just immediately respawn and kill the quest mobs when you aggro them, which doesn't let you get credit on Marzon, rendering the quest basically impossible to complete.
Happened all 3 times I tried to complete the quest.

**Comment by Kharkov72** [comment]
Did it again, worked as advertised. It must be because I was doing it soon after someone else, when Marzon's body is on the ground, it makes the guards freak out since them getting dismissed and him showing up happen about the same time. Niche bug, but still a bug.

**Comment by twowTurtReynolds** [comment]
I remember losing 5 minutes to this bug too myself. It's worth fixing for sure.

**Comment by cyaohiri** [comment]
On VMaNGOS, they never even despawn. When he tells them to leave, they walk away and stay in the library. When the event is over and Lescovar dies, they just walk back to their positions.
https://streamable.com/8cl6ff

**Comment by twowTurtReynolds** [comment]
That is indeed how I remember it on Classic 2019.

But I can't replicate the issue, they seem to wander off just like on vmangos.
![image](https://github.com/slowtorta/turtlewow-bug-tracker/assets/151180101/04b006ab-3a40-4bb6-8d3d-12cb24fd511f)
No guards are anywhere near the two.
![image](https://github.com/slowtorta/turtlewow-bug-tracker/assets/151180101/401e9b69-e594-4f0b-85dc-d85d482dcca6)

And the moment you slay the two, they respawn:
![image](https://github.com/slowtorta/turtlewow-bug-tracker/assets/151180101/4d317da1-9b3e-4a14-9c43-cb17eb189302)

I'm not sure how to see it bugged out like before. Perhaps it was fixed?

**Comment by cyaohiri** [comment]
It could be that they are forcefully respawned when someone accepts the quest. The main difference is that on VMaNGOS they don't have to be respawned as they're not despawned at any point during the event.
