### ISSUE TITLE
Idol of Brutality shouldn't be a world drop

### ISSUE THREAD

**Issue by EyeOfTheBeast** [slowtorta/turtlewow-bug-tracker#5496]
**Please, provide a clear description what the bug is:**
The Idol of Brutality item shouldn't drop from mobs in the world, but it currently is dropping from random mobs. It should only be obtainable as a drop from Magistrate Barthilas in Stratholme Undead.

**Steps to reproduce the behavior with as much detail as possible:**
1. Idol of Brutality can drop from mobs in the world, including from mobs in Zul'Gurub.

**IDs of affected creatures, items, quests or spells with a link to the relevant page:**
Idol of Brutality item: https://database.turtle-wow.org/?item=23198
Magistrate Barthilas NPC: https://database.turtle-wow.org/?npc=10435
Idol of Brutality item on Wowhead Classic database: https://www.wowhead.com/classic/item=23198/idol-of-brutality

**Expected behavior. Describe how it should work:**
The Idol of Brutality item should only drop from Magistrate Barthilas in Stratholme Undead, and it shouldn't drop from anything else.

**Comment by aksnowshadow** [comment]
I can second this bug, the idol dropped for me while farming earth elementals in Silithus

**Comment by welpenhund** [comment]
https://database.turtle-wow.org/?item=23198 - Confirmed by t-wow database loot table.
