### ISSUE TITLE
Hippogryph Egg quests ("The Super Egg-O-Matic", "A Good Egg", etc.) not providing reputation

### ISSUE THREAD

**Issue by Aubreykun** [slowtorta/turtlewow-bug-tracker#5498]
**Please, provide a clear description what the bug is:**
The repeatable quest "The Super Egg-O-Matic" should provide reputation once completed. It is currently not doing so. Neither are the followup quests for handing in the egg you get from the machine.

**Steps to reproduce the behavior with as much detail as possible:**

1. Obtain a Hippogryph Egg in SW Feralas
2. Travel to Gadgetzan, hand it in to the Super Egg-O-Matic
3. See that you get no reputation, just the egg box.
4. Hand the egg from the box in to Curgle Cranklehop, standing nearby.
5. Receive only money or a container of small items, no reputation.

**IDs of affected creatures, items, quests or spells with a link to the relevant page:**

Item: https://database.turtle-wow.org/?item=8564
Quest: https://database.turtle-wow.org/?quest=8893
Object: https://database.turtle-wow.org/?object=142071

NPC: https://database.turtle-wow.org/?npc=7763
Quest: https://database.turtle-wow.org/?quest=2750
Quest: https://database.turtle-wow.org/?quest=2748
Quest: https://database.turtle-wow.org/?quest=2747
Quest: https://database.turtle-wow.org/?quest=2749
Item: https://database.turtle-wow.org/?item=8645
Item: https://database.turtle-wow.org/?item=8646
Item: https://database.turtle-wow.org/?item=8644
Item: https://database.turtle-wow.org/?item=8643

**Expected behavior. Describe how it should work:**
A very small amount of reputation with darnassus & thunder bluff should be awarded. This was previously working (and a "hidden and insane" way for people to try to grind crossfaction rep, because it's so little each time). The reputation has been missing since this quest collection broke-and-was-fixed a few months ago.

**Comment by Aubreykun** [comment]
> Indeed this was a hackfix made to prevent xfaction reputation grinding. I am checking now to see if it acceptable for the team to develop a hardcode to never give horde rep to alliance players and vice versa.

Why prevent it though? It's been a part of twow for a very, very long time and gave little enough rep that doing so would be possibly one of the most difficult things to do in the game, given that the opposite faction starts at a flat, absolute zero. Even more tedious than getting both centaurs to exalted.

**Comment by Muigin** [comment]
Won't fix.
