### ISSUE TITLE
Goblin Mount vendor and Rats Guildbase npcs hostile to Horde players

### ISSUE THREAD

**Issue by BRBScratcher** [slowtorta/turtlewow-bug-tracker#55]
By opening this Issue, I admit to having done the pertinent research using sources from Vanilla (preferably) or Classic. I also understand that sources from other private servers are not acceptable.

**Current behavior**: 
The Goblin Mount vendor in the Shimmering Flats aswell as the costum npcs in the Rats guild base have all turned hostile to Horde players,  which makes it now impossible for Goblins to get their level 40 mounts 

**Expected behavior**: 
they should either be friendly or at least have the Durotar Labor Union reputation

**Proofs**:
![Unbenannt](https://user-images.githubusercontent.com/50635128/122156320-0a063900-ce69-11eb-9020-e21e80d3609f.jpg)
![Unbenannt2](https://user-images.githubusercontent.com/50635128/122156358-18eceb80-ce69-11eb-9f2f-947a0467abed.jpg)

**Steps to reproduce**:

1.  go to the Shimmering Fats to Mirage Raceway for the mount vendor
2.  go to the north east of the Shimmering Flats for the Rats guild base

**Comment by slowtorta** [comment]
Thanks for reporting it. It's fixed and will be deployed on the next server update.
