### ISSUE TITLE
Steelsnap is stacked with its escort

### ISSUE THREAD

**Issue by rptb1** [slowtorta/turtlewow-bug-tracker#550]
**Please, provide a clear description what the bug is:**

Steelsnap is stacked on top of its escort, making it visually look like a single mob.  This has killed at least one HC.

![image](https://user-images.githubusercontent.com/419807/146805778-1c6e113b-9851-44b5-ad0e-ad5862fa14e6.png)

**Steps to reproduce the behavior with as much detail as possible:**

1. Just look at Steelsnap in Thousand Needles

**IDs of affected creatures, items, quests or spells with a link to the relevant page:**

NPC: https://database.turtle-wow.org/?npc=4548

**Expected behavior. Describe how it should work:**

Steelsnap's escorting mobs should be standing either side of it, and a little behind.

**Comment by LeopoldHock** [comment]
Winterfall Runners in Winterspring show the same behavior.

**Comment by slowtorta** [comment]
Fixed in the next revision.
