### ISSUE TITLE
Saved dual specs reset after each logon

### ISSUE THREAD

**Issue by craigdbarber** [slowtorta/turtlewow-bug-tracker#5502]
Upon logon, each of my character's saved dual specs which are not currently activated get reset. These saved dual specs had all talent points assigned. I've tried resetting talents and re-saving the specs multiple times as a work around, only to find them reset  upon the next logon.

**Steps to reproduce the behavior with as much detail as possible:**

1. Have multiple saved dual specs.
2. Logon and receive the message: "Your saved dual spec has been reset."

**Expected behavior. Describe how it should work:**
Saved dual specs not to be reset with each logon.

**Comment by Mysstt** [comment]
This is also happening to me. Clearing WDB and disabling all addons doesn't help. Have already wasted gold on resetting to respec a few times - what's the official solution for this? I don't have the gold to waste on trying anything else myself... :'(

**Comment by twowTurtReynolds** [comment]
Tracking under https://github.com/slowtorta/turtlewow-bug-tracker/issues/5582 now.
