### ISSUE TITLE
Item: Foul Effigy

### ISSUE THREAD

**Issue by cyaohiri** [slowtorta/turtlewow-bug-tracker#5503]
Foul Effigy is not unique, unlike other items that start a quest.

Item: https://database.turtle-wow.org/?item=61153

**Comment by twowTurtReynolds** [comment]
![image](https://github.com/slowtorta/turtlewow-bug-tracker/assets/151180101/29a9d99f-d9e2-4bc2-b5e2-3458b0de269d)
Indeed, this lacks a bit of blizzard polish.

**Comment by Muigin** [comment]
I have applied a fix and this will be fixed in the next maintenance.
