### ISSUE TITLE
Improved Shadowform reduces the cost of shadow spells by 14% rather than the intended 15%

### ISSUE THREAD

**Issue by schanzee** [slowtorta/turtlewow-bug-tracker#5504]
Improved Shadowform reduces the cost of shadow spells by 14% rather than the intended 15%.

1. Learn Shadowform.
2. Learn Improved Shadowform.
3. Compare mana cost of Shadowform before and after casting it.

Spell: 
Shadowform
https://database.turtle-wow.org/?spell=15473
Improved Shadowform
https://database.turtle-wow.org/?spell=45553

Shadowform costs 550 mana at level 60. With Improved Shadowform it should cost 467,5 mana but you'll observe the new mana cost is 473 mana which corresponds to a 14% cost reduction rather than intended 15%. Same with all other shadow spells.

Tiny issue all but inconsequential to gameplay.

**Comment by twowTurtReynolds** [comment]
Replicated, mind blast is at 350 - 0.14 * 350 = 301 instead of 350 - 0.15 * 350 = 297.5

This is not a visual bug either, I am unable to cast blast at 298 mana:
![image](https://github.com/slowtorta/turtlewow-bug-tracker/assets/151180101/de11d03b-9273-4f88-b1dc-f837e9319d33)
