### ISSUE TITLE
Randomly falling through boats/zeppelins

### ISSUE THREAD

**Issue by aksnowshadow** [slowtorta/turtlewow-bug-tracker#5505]
**Please, provide a clear description what the bug is:**
I have had several recent incidents, 2 with boats and 1 fatality with a zeppelin, where upon reloading after travelling I was no longer on the boat/zepp. The boat one isn't game breaking however the zepp one left me stranded mid-air until I inched forward plummeting to my death. The zepp incident was the Org->Badlands zepp, the boats were the Menethil Harbor -> Theramore and SW->Auberdine
**Steps to reproduce the behavior with as much detail as possible:**

1. Get on a boat/zepp
2. Pray
3. Get to destination maybe

**IDs of affected creatures, items, quests or spells with a link to the relevant page:**

NPC: https://database.turtle-wow.org/?npc=
Item: https://database.turtle-wow.org/?item=
Quest: https://database.turtle-wow.org/?quest=
Spell: https://database.turtle-wow.org/?spell=
Object: https://database.turtle-wow.org/?object=

**Expected behavior. Describe how it should work:**
I shouldn't be stranded in the air. Water I can work with but not certain death.

Edit: I forgot I took before/after screenshots of my death
![Before Death](https://github.com/slowtorta/turtlewow-bug-tracker/assets/147022757/b47eacb9-41d4-4c5a-9041-6bb488493e10)
![Uploading After Death.png…]()

**Comment by twowTurtReynolds** [comment]
Try moving the game to an SSD, and disabling heavy addons, for faster loading times. It seems your loading is so slow that the server doesn't even remember to keep you attached to the ride.
