### ISSUE TITLE
Not able to do the racing quests(show as world event)

### ISSUE THREAD

**Issue by snnail** [slowtorta/turtlewow-bug-tracker#5507]
**Please, provide a clear description what the bug is:**

**Steps to reproduce the behavior with as much detail as possible:**

1. AAccepted both quests and cannot turn them in 
2. https://database.turtle-wow.org/?quest=50312  / https://database.turtle-wow.org/?quest=50310 
3. 

**IDs of affected creatures, items, quests or spells with a link to the relevant page:**

NPC: https://database.turtle-wow.org/?npc=
Item: https://database.turtle-wow.org/?item=
Quest: https://database.turtle-wow.org/?quest=
Spell: https://database.turtle-wow.org/?spell=
Object: https://database.turtle-wow.org/?object=

**Expected behavior. Describe how it should work:**

**Comment by twowTurtReynolds** [comment]
Tracking under https://github.com/slowtorta/turtlewow-bug-tracker/issues/4813
