### ISSUE TITLE
[Orc] Orc Racial: Command - Is bugged at the moment

### ISSUE THREAD

**Issue by bobz120** [slowtorta/turtlewow-bug-tracker#551]
**Please, provide a clear description what the bug is:**

![Untitled](https://user-images.githubusercontent.com/96446716/146837757-3355b911-2ef7-48b9-8cd3-5b3cf910c726.jpg)

The Orc Racial: Command, isn't increasing pet damage or abilities at the moment.

**Steps to reproduce the behavior with as much detail as possible:**

1. Use a set damage ability from a pet, like Lash of Pain from a succubus
2. Use on a target dummy
3. There's no increased damage compared to the original damage of a non-Orc Warlock

**IDs of affected creatures, items, quests or spells with a link to the relevant page:**

Spell: https://database.turtle-wow.org/?spell=20575
Spell: https://database.turtle-wow.org/?spell=7815

**Expected behavior. Describe how it should work:**

Pet attacks and abilities should be increased by 5%, so a rank 2 Lash of Pain does a flat 44 damage, 44x0.05 = 2.2
A rank two Lash of Pain should be hitting at least for 46 as an Orc Warlock without talents in demonology.

On classic Wowhead the Racial Command is supposed to Modify every level of the Imps Firebolt and the Succubuses Lash of Pain.

https://classic.wowhead.com/spell=20575/command

Also I hear the Voidwalker Torment was going to deal shadow damage in patch 1.6 so this could be effected also.

**Comment by redmagejoe** [comment]
This took a LOT of time to coordinate, but I have determined that Orc's Command Racial does indeed work. Tested a 60 Dwarf Hunter with all talents reset and no gear against a 60 Orc Hunter with all talents reset and no gear, both with completely untrained, recently tamed level 49 Ashmane Boars from Blasted Lands, both boars fed to Happy and hitting Apprentice Training Dummies.

Dwarf's pet: 66-84 window damage, 80-101 combat log damage over several minutes.
Orc's pet: 69-89 window damage, 85-108 combat log damage over several minutes.

Working as intended or fixed. This can be closed.
