### ISSUE TITLE
"The Murkfisher" misclassified as a staff instead of a fishing pole

### ISSUE THREAD

**Issue by Aubreykun** [slowtorta/turtlewow-bug-tracker#5510]
**Please, provide a clear description what the bug is:**
The Murkfisher (dropped from Rotmaw in Caverns of Time: Black Morass) has an in-game model of a fishing pole. 
It requires Fishing (150) to use. 
The flavor text says "Catches fish and foe alike."
It has a proc effect.

Yet its current tooltip in-game states that it's a staff, not a fishing pole.

**Steps to reproduce the behavior with as much detail as possible:**

1. Look at The Murkfisher in-game.
2. Preview it in the Dressing Room.

**IDs of affected creatures, items, quests or spells with a link to the relevant page:**

Item: https://database.turtle-wow.org/?item=61030

**Expected behavior. Describe how it should work:**
Item should be a fishing pole. Even Nat Pagle's Fish Terminator - a staff - visibly looks like a staff, instead of a fishing pole.

**Comment by twowTurtReynolds** [comment]
Classifying this item as a staff and not a fishing pole is a gameplay concession. If it were made into a fishing pole, which it actually originally was: nobody could use it with their melee abilities, and the dev lift to add Fishing Pole to an allowable meele ability weapon type is not on the table.
