### ISSUE TITLE
Cannot open chest to loot Horn of Gerek'sa

### ISSUE THREAD

**Issue by Hydra9268** [slowtorta/turtlewow-bug-tracker#5513]
**Please provide a clear description of what the bug is:**

The chest for this item is located under an object so that it cannot be reached in any direction.

Screenshot of issue: https://i.imgur.com/yemUqva.jpeg
Screenshot of location: https://i.imgur.com/yHMzTGC.jpeg

**Steps to reproduce the behavior with as much detail as possible:**

1. Travel to the location for the quest object (The Horn of Garek'sa)
2. Try and open the chest
3. Error message: "Target not in line of site."

A simple fix would be moving the chest out from under the canopy.

**IDs of affected creatures, items, quests, or spells with a link to the relevant page:**

Object: https://database.turtle-wow.org/?object=2010806
Item: https://database.turtle-wow.org/?item=60128
Quest: https://database.turtle-wow.org/?quest=40028 Screenshot of quest: https://i.imgur.com/tysBK6U.jpeg

**Expected behavior. Describe how it should work:**

Expect to be able to open the chest to loot the Horn of Gerek'sa for the quest The Horn of Gerek'sa.

**Comment by ratkosrb** [comment]
Are you sure you're trying to open the correct chest? Because it looks different than the one you pictured.

![WoWScrnShot_120823_025329](https://github.com/slowtorta/turtlewow-bug-tracker/assets/35845488/4154d1fb-2739-448d-92ea-71203a7e27ef)

**Comment by Hydra9268** [comment]
I believe you're right. Closing as cannot reproduce.
