### ISSUE TITLE
Blackblade of shahram BUG

### ISSUE THREAD

**Issue by yuzinirvana** [slowtorta/turtlewow-bug-tracker#5515]
Greetings
2023/12/05 changelog:
The Will of Shahram buff from Blackblade of Shahram can now stack up to 5 times.

There is a BUG in this change. According to my actual test, the (Wil of Shahram] buff cannot be applied to party members. Before December 5, it can be obtained by every party member. Please pay attention to this BUG. This is a very fatal problem for the Blackblade weapon.

**Comment by twowTurtReynolds** [comment]
This is blizzlike, will is meant to only be given to the weilder. The other two buffs, the hp5/mp5 and the haste, are the partywide ones.

**Comment by yuzinirvana** [comment]
know that, Because this weapon has always been effective against party members, I thought this was a BUG. Aren't you going to restore it to the party buff it had before December 5th? I think this makes it worthless, even if it only stacks 1 layer.

Thank you again for your work!

**Comment by twowTurtReynolds** [comment]
From my understanding, Will was never a party buff on turtle, and if it was, we will not restore that blizzlike deviation now that we have fixed the deviation of no stacking.
