### ISSUE TITLE
Trinket doesnt works

### ISSUE THREAD

**Issue by Emigrantt** [slowtorta/turtlewow-bug-tracker#5516]
[Mossheart's Heart] Trinket doesnt works

1 dps - doesnt works (DEFENSIVE STAND war reduces damage - damage becomes 0) 

This Trinket  is for TANK, but in DEFENSIVE STAND  e - damage becomes 0

https://github.com/slowtorta/turtlewow-bug-tracker/issues/5517  the same situation is a big problem for TANK

**Comment by twowTurtReynolds** [comment]
Duplicate of https://github.com/slowtorta/turtlewow-bug-tracker/issues/4271
