### ISSUE TITLE
The Flame's Casing, drop rate 0%

### ISSUE THREAD

**Issue by Brunzine** [slowtorta/turtlewow-bug-tracker#5519]
**Please, provide a clear description what the bug is:**
Quest: "The Flame's Casing". Kill mobs to get drop "Symbol of Ragnaros".

Drop rate should be 15%, but seems do be 0%. Have killed 50+ Twilight Mobs and still no drop.

**Steps to reproduce the behavior with as much detail as possible:**

1. Pick up q
2. Kill Twilight mobs
3. No drop
4. Rince, repeat

**IDs of affected creatures, items, quests or spells with a link to the relevant page:**

NPC: https://database.turtle-wow.org/?npc=5861
https://database.turtle-wow.org/?npc=5860
https://database.turtle-wow.org/?npc=5862

Item: https://database.turtle-wow.org/?item=10552

Quest: https://database.turtle-wow.org/?quest=3452

**Expected behavior. Describe how it should work:**
Drop rate should be 15%.

**Comment by twowTurtReynolds** [comment]
![image](https://github.com/slowtorta/turtlewow-bug-tracker/assets/151180101/9d7ea41c-1146-4ef1-a1bf-07e3c2e69a40)
Yeah, something is up. I won a world drop epic and still didn't get the quest reward.

**Comment by ratkosrb** [comment]
![WoWScrnShot_120823_025052](https://github.com/slowtorta/turtlewow-bug-tracker/assets/35845488/85b40b63-a423-483d-a6e8-acd1f037c393)

I can't reproduce the issue. It dropped from the second mob I killed.

**Comment by twowTurtReynolds** [comment]
Sorry @ratkosrb ... I had just realize I was in a raid group from raid testing earlier... The moment I dropped my group, I got the drop in 6 kills.

@Brunzine that is likely your case too...

**Comment by Brunzine** [comment]
@twowTurtReynolds nope, soloed it with my warlock. Going back today to try.

**Comment by twowTurtReynolds** [comment]
He got the drop from an idolator. I got one from a geomancer.

**Comment by Brunzine** [comment]
@twowTurtReynolds @ratkosrb I went back yesterday and got the drop on about the 20th kill, from a Twilight Fire Guard. So, maybe just pure unluck for me (ca 70 kills in total for a 15% drop rate).
