### ISSUE TITLE
hunter pets instant heal after battle

### ISSUE THREAD

**Issue by geojak** [slowtorta/turtlewow-bug-tracker#552]
**Please, provide a clear description what the bug is:**

when a hard battle is fought and a narrow survival is acheivend, playser must lick their wounds and recover. unlike their pets which seems to recover in a flash a go back to 100% health instantlz

**Steps to reproduce the behavior with as much detail as possible:**

1. get zour pet on low health during battle
2. end the battle with low health on pet
3. observe instant heal

**IDs of affected creatures, items, quests or spells with a link to the relevant page:**

NPC: https://database.turtle-wow.org/?npc=
Item: https://database.turtle-wow.org/?item=
Quest: https://database.turtle-wow.org/?quest=
Spell: https://database.turtle-wow.org/?spell=
Object: https://database.turtle-wow.org/?object=

**Expected behavior. Describe how it should work:**

hunter pets should also need time to recover. i remeber having to banadage and heal mz pet in classic manz times to top their health bar up again.

**Comment by rptb1** [comment]
What levels are affected?

**Comment by geojak** [comment]
just saw it on my girlfriends high elf hunter. the pet was level 21, she had the cat from the cutom new elfen city area.

**Comment by discslack** [comment]
Hunter pet regens quickly out of combat but not instantly full health. Provide proof

**Comment by geojak** [comment]
i dont have recording experence but i will try

**Comment by geojak** [comment]
it doesnt heal instantly, its just rly quick
