### ISSUE TITLE
Not receiving training points when pet is max loyalty

### ISSUE THREAD

**Issue by Kangaroux** [slowtorta/turtlewow-bug-tracker#5525]
**Please, provide a clear description what the bug is:**
I've been receiving training points like usual as my pet levels, but now that it's max loyalty I've stopped getting training points. Tried clearing WDB, dismissing, and stabling.

**Comment by Kangaroux** [comment]
It looks like I'm getting 5 or 10 TP for each pet level (not sure which). My pet is lvl 33

**Comment by twowTurtReynolds** [comment]
@Kangaroux do you know what is blizzlike?

**Comment by Kangaroux** [comment]
The only resource I can find is this TP calc: https://www.wowhead.com/classic/hunter-pet-training/AQE8Bg

If you move the level slider at max loyalty it goes up by 5 TP per level. It seemed like prior to max loyalty I was getting TP equal to my pet's level. I don't know if that's intended or not.

**Comment by SuqMadiqM8** [comment]
Everything you need to know is in the above formula already.
Your pet gains 0-5 tp per level up depending on its loyalty. (5 points at max loyalty, 0 points at loyalty 1). It also gains tp equal to its current level when the loyalty increases.

You gained somewhere around 30 tp when your pet increased its loyalty. You now gain 5 tp when your pet levels up. For a max amount of 300 tp (= loyalty 6 - 1 = 5 x level 60).

It's blizzlike and also working as intended.
