### ISSUE TITLE
Greathorn Hunter and Greathorn Owl not tameable

### ISSUE THREAD

**Issue by 0wllynx** [slowtorta/turtlewow-bug-tracker#5527]
**Please, provide a clear description what the bug is:**
The owls in the Hyjal zone (Greathorn Hunter as well as Greathorn Owl) are not tameable.

**Steps to reproduce the behavior with as much detail as possible:**

1. Find Greathorn Hunter (the lvl 60 ones) or a Greathorn Owl in the Hyjal zone as lvl 60 a Hunter char.
2. Use the "Beast Lore" ability and find that it says it cannot be tamed.
3. Have no current pet and use "Tame Beast" on the Greathorn mob, to find, after the channeling is complete, the message that it cant be tamed. (Use a Freezing Trap to avoid being interrupted.)

**IDs of affected creatures, items, quests or spells with a link to the relevant page:**

NPC: https://database.turtle-wow.org/?npc=61336
NPC: https://database.turtle-wow.org/?npc=61337
Spell: https://database.turtle-wow.org/?spell=1462
Spell: https://database.turtle-wow.org/?spell=1515

**Expected behavior. Describe how it should work:**
As the Greathorn Hunter and Greathorn Owl are beasts of the owl family, I expected them to be tameable. Also, they are the only candidates in the game for the brown owl skin, whereas there were none in original vanilla, and it would be a fantastic TWoW addition if they could be tamed.

**Comment by twowTurtReynolds** [comment]
This is a suggestion, please post this to the forums instead.
