### ISSUE TITLE
Can´t use Karazhan enchant on helmet

### ISSUE THREAD

**Issue by Himosika** [slowtorta/turtlewow-bug-tracker#5529]
**Please, provide a clear description what the bug is:**
Lower Karazhan enchant (Invocation of Greater Protection) doesn´t work on Flamescorched Hood

**Steps to reproduce the behavior with as much detail as possible:**

1. Try to put  Kahzhan enchant to the helmet
2. It says that item is not valid target
3. Wonder very hard because in enchant is specifically says: can be used to leg or head slot item

**IDs of affected creatures, items, quests or spells with a link to the relevant page:**

Item: =https://database.turtle-wow.org/?item=92006
Item: https://database.turtle-wow.org/?item=61260

**Expected behavior. Describe how it should work:**
Enchant should go on the helmet without any problems

**Comment by twowTurtReynolds** [comment]
Do not create duplicate bug reports, especially of pinned reports.

**Comment by Himosika** [comment]
Support told me to write pug report so i did.

**Comment by twowTurtReynolds** [comment]
Support should not have done that, sorry. I will speak with the team.
