### ISSUE TITLE
a dark threat looms

### ISSUE THREAD

**Issue by geojak** [slowtorta/turtlewow-bug-tracker#553]
**Please, provide a clear description what the bug is:**

in loch modan on the dam their is a gquest line called a dark threat looms that is about difsuing the dark irons atempt of blowing the dam up with a bomb.

after handing in the last quest of the questrow uppon completion the questgiver npc should shout something telling everzone how great the plazer is for saving everzone. this is very similiar to the deadmines van cleef quest.

on turtle wow their is no such shout. its a minor detail missing but still adds a tinz bit to make the world feel real

**Steps to reproduce the behavior with as much detail as possible:**

1. do the a dark threat looms qeustline in lochmodan on the dam
2. hand in the last quest of the quest line
3. no shout like in classic

**IDs of affected creatures, items, quests or spells with a link to the relevant page:**

NPC: https://database.turtle-wow.org/?npc=
Item: https://database.turtle-wow.org/?item=
Quest: https://database.turtle-wow.org/?quest=
Spell: https://database.turtle-wow.org/?spell=
Object: https://database.turtle-wow.org/?object=

**Expected behavior. Describe how it should work:**

npc should shout something similiar to when handing in the van cleef quest line in westfall whic hdoes actaullz work on turtle wow

**Comment by NickTyrer** [comment]
Fixed here https://github.com/vmangos/core/pull/1409
