### ISSUE TITLE
Assisting the Children of the Sun

### ISSUE THREAD

**Issue by veljovicm** [slowtorta/turtlewow-bug-tracker#5534]
**Please, provide a clear description what the bug is:**

**Steps to reproduce the behavior with as much detail as possible:**

1. Quest giver does not showing any Quest at locations
2. WDB deleted and disabled addons
3. 

**IDs of affected creatures, items, quests or spells with a link to the relevant page:**

NPC: https://database.turtle-wow.org/?npc=80230
Item: https://database.turtle-wow.org/?item=
Quest: https://database.turtle-wow.org/?quest=80250
Spell: https://database.turtle-wow.org/?spell=
Object: https://database.turtle-wow.org/?object=

**Expected behavior. Describe how it should work:**

**Comment by twowTurtReynolds** [comment]
![image](https://github.com/slowtorta/turtlewow-bug-tracker/assets/151180101/265b6045-ad41-42c6-afef-7170fa4cf103)
This quest giver? Seems to be working.

**Comment by veljovicm** [comment]
![WoWScrnShot_120923_141737](https://github.com/slowtorta/turtlewow-bug-tracker/assets/49202872/cd7a6ac4-ea33-4b96-b9d0-ffaafb7c8408)
![WoWScrnShot_120923_142112](https://github.com/slowtorta/turtlewow-bug-tracker/assets/49202872/aa1641a3-f08e-4108-9fc3-8f33672c9952)


Not really.. Idk what else to do then re download client again

**Comment by cyaohiri** [comment]
Have you already completed this quest? Check by going to [Caledra Dawnbreeze](https://database.turtle-wow.org/?npc=1752).

**Comment by veljovicm** [comment]
Checked that already just to be sure if i missed something or dropped q.... She wont have that dialog that was supposed to be there

**Comment by cyaohiri** [comment]
Ask A GM to give you the quest then. They can also check if you've already done it and what state of the quest chain you're on.
