### ISSUE TITLE
Hunter T3 4 piece bonus not taking effect

### ISSUE THREAD

**Issue by shijiexug2016** [slowtorta/turtlewow-bug-tracker#5536]
**Please, provide a clear description what the bug is:**
The hunter T3 4 piece bonus: `Increases Attack Power by 50 for both you and your pet` is not taking effect.
**Steps to reproduce the behavior with as much detail as possible:**

1. put 4 piece t3 on a hunter
2. check the attack power in the character stats view without a pet.
3. check the attack power in the character stats view with a pet
The attack power should be different by 50 but there is not change actually.

**IDs of affected creatures, items, quests or spells with a link to the relevant page:**

NPC: https://database.turtle-wow.org/?npc=
Item: https://database.turtle-wow.org/?item=
Quest: https://database.turtle-wow.org/?quest=
Spell: https://database.turtle-wow.org/?spell=28756 found from classic
Object: https://database.turtle-wow.org/?object=

**Expected behavior. Describe how it should work:**
![Screenshot 2023-12-08 150801 - Copy](https://github.com/slowtorta/turtlewow-bug-tracker/assets/22058584/2c124ae8-1e0a-449f-8fb4-af387347a61f)
![Screenshot 2023-12-08 150928 - Copy](https://github.com/slowtorta/turtlewow-bug-tracker/assets/22058584/b7198c84-39ff-42de-b07e-5b239f77d3b6)

**Comment by balakethelock** [comment]
Are you sure it's not just giving you the AP all the time? The tooltip says "gives you and your pet", it doesn't say "when you have pet summoned, give you and your pet"

**Comment by twowTurtReynolds** [comment]
![image](https://github.com/slowtorta/turtlewow-bug-tracker/assets/151180101/38d936e2-3379-4c34-8e0a-c91ef062f33c)
367 + 50 + 33 = 450
![image](https://github.com/slowtorta/turtlewow-bug-tracker/assets/151180101/5cc2dce2-c369-4a2e-b864-06f25eb6d993)

Unless someone has blizzlike proof otherwise, all is well.
