### ISSUE TITLE
Bad ping when I am in Stormwind

### ISSUE THREAD

**Issue by RicochetedSlug** [slowtorta/turtlewow-bug-tracker#5538]
**Please, provide a clear description what the bug is:**
Whenever I am in Stormwind, my ping goes high like above 1000 ms.  This doesn't really happen before, even during the height of the Chinese players swarming the server (10k population).  I noticed this bad ping occurring even when the server population is just 6k.  Other players in my guild experience the same problem.

**Steps to reproduce the behavior with as much detail as possible:**
Here is when the problem occurs.
1. When I log in game in Stormwind
2. When I Hearthstone to Stormwind
3. When I fly or travel to Stormwind

**IDs of affected creatures, items, quests or spells with a link to the relevant page:**

NPC: https://database.turtle-wow.org/?npc=
Item: https://database.turtle-wow.org/?item=
Quest: https://database.turtle-wow.org/?quest=
Spell: https://database.turtle-wow.org/?spell=
Object: https://database.turtle-wow.org/?object=

**Expected behavior. Describe how it should work:**

**Comment by twowTurtReynolds** [comment]
Please contact a GM.

**Comment by RicochetedSlug** [comment]
Hi. GM said they can't do anything about this and to file the issue here as they cannot do anything about the bad ping experienced by many players in Stormwind.
