### ISSUE TITLE
mining node inside mountain

### ISSUE THREAD

**Issue by geojak** [slowtorta/turtlewow-bug-tracker#554]
**Please, provide a clear description what the bug is:**

i found this bugged tin vain in redridge mountain. just see the screenshots.

its not minable, but i was able to hover over it with some troubles.
![WoWScrnShot_122221_171651-min](https://user-images.githubusercontent.com/25199983/147123625-9dc717db-30d8-4565-a8a4-2a4e7012b205.jpg)
![WoWScrnShot_122221_171633-min](https://user-images.githubusercontent.com/25199983/147123630-f26a0bb5-4d3c-474d-9ce9-049522668d03.jpg)

pls get it above ground

**Comment by Neto-WoW** [comment]
Fixed. Thanks.
