### ISSUE TITLE
Zep from TB to Org is Invisible

### ISSUE THREAD

**Issue by Averdrity** [slowtorta/turtlewow-bug-tracker#5542]
**Please, provide a clear description what the bug is:**
The zep from TB to Org is invisible. ( Restarted client with WDB folder removed to try and solve it but did not work. )

**Steps to reproduce the behavior with as much detail as possible:**

1. Wait on the zep in TB
2. Wait on the zep in TB
3. Wait on the zep in TB

**IDs of affected creatures, items, quests or spells with a link to the relevant page:**

NPC: https://database.turtle-wow.org/?npc=
Item: https://database.turtle-wow.org/?item=
Quest: https://database.turtle-wow.org/?quest=
Spell: https://database.turtle-wow.org/?spell=
Object: https://database.turtle-wow.org/?object=

**Expected behavior. Describe how it should work:**
When waiting on the zep in Thunder Bluff you can sometimes see a player come out of the zep. But you cant see the zep. I tried twice to get on, but fell to the ground. It should bi visable. Thats how it should work.

**Comment by twowTurtReynolds** [comment]
Indeed this is a duplicate.
