### ISSUE TITLE
Ghost Teleporting to Capitals after ungrounping

### ISSUE THREAD

**Issue by Plainbear** [slowtorta/turtlewow-bug-tracker#5543]
You can Teleport yourself to capitals as a ghost in Stormwind Vault if you remove yourself from a party while in ghost form in the Stormwind Instance. Auto Unstuck also does not resolve the issue.

1. Die in Stormwind Vault
2. Remove yourself from Party
3. After 1 min, get teleported to a capital without any possibility to ressurect

Dying in Stormwind Vault should place you outside of Stormwind Vault and make you ressurect when you enter the instance

**Comment by twowTurtReynolds** [comment]
![image](https://github.com/slowtorta/turtlewow-bug-tracker/assets/151180101/3921c158-0a33-407a-ab51-ccac5cdb0047)
![Screenshot_20231209_110253](https://github.com/slowtorta/turtlewow-bug-tracker/assets/151180101/a5ed451d-955b-4357-8a82-677ef912a5b5)
![image](https://github.com/slowtorta/turtlewow-bug-tracker/assets/151180101/e6f88555-9469-4f6a-8a33-d25f2f055af3)

Looks like the ghost system is completely broken in this instance...

**Comment by ratkosrb** [comment]
It should be fixed on the next update.
