### ISSUE TITLE
Invocation of Greater Protection bugged out as invalid target

### ISSUE THREAD

**Issue by Fenikzart** [slowtorta/turtlewow-bug-tracker#5547]
**Please, provide a clear description what the bug is:**
I have tried to use one of the new enchants "Invocation of Greater Protection" on a leg item that already has a 40 armor/5 stam enchant already on.

When i click the item and try to put it on my leg it just says invalid target.

I have tried doing it when the pants are on my char, in my bag, relogging, deleting WDB folder and nothing works.

**Steps to reproduce the behavior with as much detail as possible:**

1. Have Leggings of the inferno with reinforced Armor +40/+5 Stamina
2. Complete the quest Contribution to the Church ( https://database.turtle-wow.org/?quest=41078 )
3. Hand in the quest Invocation of Greater Protection and get the item  ( https://database.turtle-wow.org/?quest=41080 )
4. Then try apply it to the leg armor slot.

**IDs of affected creatures, items, quests or spells with a link to the relevant page:**
https://database.turtle-wow.org/?quest=41078
https://database.turtle-wow.org/?quest=41080

**Expected behavior. Describe how it should work:**
It should override current enchant and apply the new one.

**Comment by twowTurtReynolds** [comment]
Please do not create duplicate reports of pinned issues. https://github.com/slowtorta/turtlewow-bug-tracker/issues/4788
