### ISSUE TITLE
Barrens north - weird zone or layer transition, nodes disappear and NPCs appear when I go near them

### ISSUE THREAD

**Issue by tslnox** [slowtorta/turtlewow-bug-tracker#5548]
In northern Barrens, near the road that connects to Ashenvale, you can see Mageroyal nodes. When you walk towards them, they disappear and sometimes a mob appears (Zhevra for example) I'm not sure whether it's a layer issue or what, but I can't get to the herb without it disappearing.

**Steps to reproduce the behavior with as much detail as possible:**

1. Go to Barrens, waypoint 47.6 11.6
2. Look at the Mageroyal, walk towards it.
3. It disappears.

**IDs of affected creatures, items, quests or spells with a link to the relevant page:**

**Expected behavior. Describe how it should work:**
Node shouldn't disappear or it should be placed in the zone/layer where you can actually reach it.

**Comment by twowTurtReynolds** [comment]
Tracking these in https://github.com/slowtorta/turtlewow-bug-tracker/issues/5312
