### ISSUE TITLE
Shy-rotam chain fearing

### ISSUE THREAD

**Issue by AKryukov92** [slowtorta/turtlewow-bug-tracker#5549]
**Please, provide a clear description what the bug is:**
Shy-rotam chain fears player. It literally don't let player to do anything because of it.

I also found forum thread regarding this mob. People say that any NPC with fear ability tend to chain it
https://forum.turtle-wow.org/viewtopic.php?p=49912

**Steps to reproduce the behavior with as much detail as possible:**

1. Get quest [Shy-Rotam](https://database.turtle-wow.org/?quest=5056)
2. Get [Sacred Frostsaber Meat](https://database.turtle-wow.org/?item=12733)
3. Summon [Shy-Rotam](https://database.turtle-wow.org/?npc=10737)
4. Engage Shy-Rotam in combat

**IDs of affected creatures, items, quests or spells with a link to the relevant page:**

Shy-Rotam https://database.turtle-wow.org/?npc=10737
Frenzied Pterrordax https://database.turtle-wow.org/?npc=9167
Dextren Ward https://database.turtle-wow.org/?npc=1663

**Expected behavior. Describe how it should work:**
According to wowhead comments, it uses fear approximately every 15 seconds.
https://www.wowhead.com/classic/quest=5056/shy-rotam#comments:id=18210

**Comment by twowTurtReynolds** [comment]
Tracked under: https://github.com/slowtorta/turtlewow-bug-tracker/issues/1142
