### ISSUE TITLE
Quest A New Plague

### ISSUE THREAD

**Issue by Gurky-Kronos** [slowtorta/turtlewow-bug-tracker#555]
**Please, provide a clear description what the bug is:**

The quest A New Plague requires the quester to be undead when it should be available to all horde. Keep in mind this locks 4 other quests behind it and a custom quest as well seeing it is a prerequisite. 

**Steps to reproduce the behavior with as much detail as possible:**

1. Be any race aside from undead
2. try to accept the quest. 

**IDs of affected creatures, items, quests or spells with a link to the relevant page:**

Quest: https://database.turtle-wow.org/?quest=367

**Expected behavior. Describe how it should work:**

All members of the horde should be able to take this quest: https://classic.wowhead.com/quest=367/a-new-plague

**Comment by Neto-WoW** [comment]
Fixed.
