### ISSUE TITLE
乌龟亚服翡翠梦境的玩家掉落不见的问题

### ISSUE THREAD

**Issue by erikay79** [slowtorta/turtlewow-bug-tracker#5551]
**Please, provide a clear description what the bug is:**

**Steps to reproduce the behavior with as much detail as possible:**

1.1.你好，我是乌龟亚服翡翠梦境的玩家，联盟，猎人，曹小蛮
2. 我在2023年12月9日晚参加工会活动MC团本时，二号BOSS掉落了猎人T1腿，并分配给了我，但是我的包裹、银行、邮箱都没有该物品。
3. 我已经将该问题反映给了GM，按照GM要求将视频、图片、截图等等举证资料反映到了KOOK举证频道，但没有得到任何回复和解决。
4. 我希望该问题可以得到解决，或者解决不了的答复。
5. 我在该游戏中投入了大量的时间和金钱，希望可以得到该有的服务。
6. 我希望你们可以给游戏中的GM更大的权限，可以更好的给玩家提供服务，而不是现在这种多层投诉得不到解决的问题。
![微信图片_20231209231235](https://github.com/slowtorta/turtlewow-bug-tracker/assets/153407580/88da271f-5d0a-4dd8-9450-2347bc1ae973)

**IDs of affected creatures, items, quests or spells with a link to the relevant page:**

NPC: https://database.turtle-wow.org/?npc=
Item: https://database.turtle-wow.org/?item=
Quest: https://database.turtle-wow.org/?quest=
Spell: https://database.turtle-wow.org/?spell=
Object: https://database.turtle-wow.org/?object=

**Expected behavior. Describe how it should work:**

**Comment by twowTurtReynolds** [comment]
请用英文提交问题。我们无法通过自动翻译准确地翻译中文提交的错误报告，这使得我们难以理解问题的确切性质。谢谢！

Please submit the issues in English. We're unable to accurately translate bug reports submitted in Chinese through automatic translation, which makes it difficult for us to understand the exact nature of the issue. Thank you!
