### ISSUE TITLE
lost my t1 leg ~

### ISSUE THREAD

**Issue by erikay79** [slowtorta/turtlewow-bug-tracker#5553]
**Please, provide a clear description what the bug is:**

**Steps to reproduce the behavior with as much detail as possible:**

1.Hello, I am a player from Turtle Yafu Emerald Dream, Alliance, Hunter, and NAME 曹小蛮

https://github.com/slowtorta/turtlewow-bug-tracker/assets/153407580/94026c43-593b-4e49-bca5-45be6393c83e

2.On the evening of December 9, 2023, while participating in the labor union activity MC team, the second boss dropped a Hunter T1 leg and assigned it to me, but my package, bank, and email did not have the item.
3. I have reported the issue to GM and have provided evidence materials such as videos, images, and screenshots to the KOOK evidence channel as requested by GM, but have not received any response or resolution.
4. I hope this issue can be resolved, or there can be a response that cannot be resolved.
I have invested a lot of time and money in this game, hoping to receive the necessary services.
6. I hope you can give greater permissions to the GMs in the game, which can better provide services to players, instead of the current problem of unresolved multi-level complaints.

**IDs of affected creatures, items, quests or spells with a link to the relevant page:**

NPC: https://database.turtle-wow.org/?npc=
Item: https://database.turtle-wow.org/?item=
Quest: https://database.turtle-wow.org/?quest=
Spell: https://database.turtle-wow.org/?spell=
Object: https://database.turtle-wow.org/?object=

**Expected behavior. Describe how it should work:**

**Comment by twowTurtReynolds** [comment]
Please work with the GM team, the bug tracker is not the place for helping 1 player's specific issue.
