### ISSUE TITLE
Mobs respawn with the wrong name for poison quest.

### ISSUE THREAD

**Issue by Claboth** [slowtorta/turtlewow-bug-tracker#5558]
**Please, provide a clear description what the bug is:**
the quest: Mission: Possible but not Probable. Needs 2 kills of Mutated venture Co. Drones. I'm missing 1 kill and the mobs respawn as
Venture Co. Drones, so the kills are not counted to complete the quest. I did clear Wdb and i'm not in a raidgroup.
**Steps to reproduce the behavior with as much detail as possible:**

1. Respawn the mobs for the quest as Mutated Venture Co. Drone with their correct name
2. 
3. 

**IDs of affected creatures, items, quests or spells with a link to the relevant page:**

NPC: https://database.turtle-wow.org/?npc=7310
Item: https://database.turtle-wow.org/?item=
Quest: https://database.turtle-wow.org/?quest=2478
Spell: https://database.turtle-wow.org/?spell=
Object: https://database.turtle-wow.org/?object=

**Expected behavior. Describe how it should work:**
Mobs should respawn with their correct name, so the quest can be finished.

**Comment by twowTurtReynolds** [comment]
Some mobs have shared spawns. Please continue killing the wrong mobs until the right ones spawn.

I can test this later to ensure this is the case.

**Comment by twowTurtReynolds** [comment]
![image](https://github.com/slowtorta/turtlewow-bug-tracker/assets/151180101/5a172650-f596-4d2d-8a32-9ab73dad9f33)
My guess was wrong, there's no shared spawns here. These two npcs have their own spawns just downstairs. I ran `.respawn` a dozen times and they always appear there as this npc. Working as intended.

**Comment by Claboth** [comment]
thanks for your time, going to login now and finish the quest. :)
