### ISSUE TITLE
City Protector's Medallion will not work if you lose the title even though item duration remains

### ISSUE THREAD

**Issue by discslack** [slowtorta/turtlewow-bug-tracker#556]
**Please, provide a clear description what the bug is:**
City Protector's medallion stops working even if time is left on the duration when title is lost
**Steps to reproduce the behavior with as much detail as possible:**

1. Gain city protector medallion after gaining title
2.  Lose title next honor update
3.  No longer able to use City Protector's Medallion even though duration is still available
4. Item only states that "You must become a City Protector to use this item." Not you must maintain city protector to use this item

**IDs of affected creatures, items, quests or spells with a link to the relevant page:**

Item: https://database.turtle-wow.org/?item=50056

**Expected behavior. Describe how it should work:**
Item should be usable until the duration of 7 days expires

**Comment by slowtorta** [comment]
That's correct, Medallion will not work if you've lost your title.
