### ISSUE TITLE
暴风城幸运硬币任务无法完成

### ISSUE THREAD

**Issue by falei-earnest** [slowtorta/turtlewow-bug-tracker#5560]
**Please, provide a clear description what the bug is:**

**Steps to reproduce the behavior with as much detail as possible:**

1. 暴风城幸运硬币任务无法完成，已有多人反映该问题，我的几个人类账号可以，新的高等精灵就不行
2. 喷泉没有点击按钮，点击背包里的硬币也不行
3. 尝试重启和关闭插件依然不行

**IDs of affected creatures, items, quests or spells with a link to the relevant page:**

NPC: https://database.turtle-wow.org/?npc=
Item: https://database.turtle-wow.org/?item=51425
Quest: https://database.turtle-wow.org/?quest=60050
Spell: https://database.turtle-wow.org/?spell=
Object: https://database.turtle-wow.org/?object=

**Comment by twowTurtReynolds** [comment]
请用英文提交问题。我们无法通过自动翻译准确地翻译中文提交的错误报告，这使得我们难以理解问题的确切性质。谢谢！

Please submit the issues in English. We're unable to accurately translate bug reports submitted in Chinese through automatic translation, which makes it difficult for us to understand the exact nature of the issue. Thank you!
