### ISSUE TITLE
Melee hunter with *Proc damage on melee hit* bugged with Blade of Eternal Darkness?

### ISSUE THREAD

**Issue by GekkeMannie1** [slowtorta/turtlewow-bug-tracker#5568]
Spamming Wing Clip with gear used in link below makes you do way more damage than intended.

Image 1: Damage from entire dungeon:
![Unintended 1](https://github.com/slowtorta/turtlewow-bug-tracker/assets/149955838/f8d8f42a-f5e2-47af-b965-dcf8dd58599f)

Image 2 Damage from 1 fight:
![Unintended 2](https://github.com/slowtorta/turtlewow-bug-tracker/assets/149955838/be435594-5c5b-4d1b-bcbf-4d3d13b838d1)

I watched the Hunter fight like this and he was in a perpetual state of casting animation. 

1. Use the gear used in this build https://forum.turtle-wow.org/viewtopic.php?t=6169 but be a Hunter instead of Druid.
2. Start spamming Wing Clip as a Hunter
3. 30% of all damage dealt will be from Blade of Darkness. On a druid it does ~13% of all damage which is way more in line.

NPC: n/a
Item: https://database.turtle-wow.org/?item=17780
Quest: n/a
Spell: Wing Clip
Object: n/a

Takes away every aspect of being a Hunter, there's no need to be ranged anymore if it stays like this. Every Hunter will switch to this build and absolutely MELT everything. Probably the only way to fix this is to not make BoED proc of of item effects, but no idea if that's possible. All I know is this will be the go-to build for everything; PvE and PvP.

**Comment by twowTurtReynolds** [comment]
This has been a known build for quite a while, and it is hamstrung by the fact that it does not scale, at all. Not with spell stats, not with physical stats, and you are stuck to a low dps base weapon, and so this build does not see use in late endgame raiding. The team is aware and is intentionally avoiding breaking the game by doing anything that would see the build unrestricted.

**Comment by Rowrow213** [comment]
"All I know is this will be the go-to build for everything; PvE and PvP." Everyone will want to do 300 dps
