### ISSUE TITLE
Elder Ashenvale Bear Respawn

### ISSUE THREAD

**Issue by Gurky-Kronos** [slowtorta/turtlewow-bug-tracker#557]
The respawn rate for [Elder Ashenvale Bear](https://database.turtle-wow.org/?npc=3810) might be too quick, it looks like it is currently set to 25 seconds. This means at the level you would be killing these at, the last one you killed would respawn just as you kill the next one or while you are fighting the next one. 

**Steps to reproduce the behavior with as much detail as possible:**

1. Kill [Elder Ashenvale Bear](https://database.turtle-wow.org/?npc=3810)
2. Notice it will respawn in 25 seconds.

**IDs of affected creatures, items, quests or spells with a link to the relevant page:**

NPC: https://database.turtle-wow.org/?npc=3810

**Expected behavior. Describe how it should work:**

I am not sure what is expected for this NPC but I would say maybe the normal 5-minute timer.

**Comment by Neto-WoW** [comment]
Fixed. Thanks.
