### ISSUE TITLE
Human Racial + 5 sword / mace 

### ISSUE THREAD

**Issue by xAzeroth** [slowtorta/turtlewow-bug-tracker#5570]
well I noticed playing rogue even with 11% hit and 308 sword spec I getting glancing on lvl 60-63 mobs soo 308 or 305 we can say it only works for Main hand not for offhand but also sometimes you can get glancing from Main Hand wich is really odd as Dual wielder 

I wana show you something wich should be working a bit diferent  

 if I have +5 sword and playing Human wich is  305/305 in dual wield spec but having +3 or +5 from Talents   we should get like  
 
  305 (+5 ) / 305 (+5)   not   305 (+5 ) / 305  that means offhand doing also glancing but this is generaly for all classes dual wielding and all we know when you have 305 sword/ mace you need only 6% hit  

![2023-12-12 05_12_28-World of Warcraft](https://github.com/slowtorta/turtlewow-bug-tracker/assets/132115122/124e8dab-7287-4bad-a2e9-96b30cd2aa4a)
 

as you can see what i mean that sword +3 (rogue talent , even if i have +5 ) offhand still will do glancing also soo I hope i can get  good reason why there is not     305 (+5 ) / 305 (+5)  in Human Rogue case   305 (+3 ) / 305 (+3 )

**Comment by twowTurtReynolds** [comment]
Weapon skill does not reduce the chance of getting glancing blows, as blizzard designed. Before making bug reports, please learn the game mechanics with resources such as: https://github.com/magey/classic-warrior/wiki/Attack-table#glancing-blows

**Comment by xAzeroth** [comment]
alright smart person :) than explain me how its possible to dodge  Eviscerate on moster lvl  60 with 11% hit ?

**Comment by twowTurtReynolds** [comment]
You will need +50 weapon skill before your attacks will never be dodged by a lv 60 mob.

Weapon skill applied from gear in an offhand or mainhand works exactly the same.
