### ISSUE TITLE
HC: character's grave at wrong spot.

### ISSUE THREAD

**Issue by Gasan918** [slowtorta/turtlewow-bug-tracker#5572]
**Please, provide a clear description what the bug is:**

Look at screenshot

![image](https://github.com/slowtorta/turtlewow-bug-tracker/assets/96973359/83c8d998-2d05-42e4-b725-b29841b3057b)

This character never died here. Last death was in Dead Mines at 20th lvl

**Comment by twowTurtReynolds** [comment]
Will track under https://github.com/slowtorta/turtlewow-bug-tracker/issues/4066 , we are aware the graves system is really messed up right now unfortunately
