### ISSUE TITLE
Chromaggus now changes resistances EVERY 15 seconds, it should be 40 seconds

### ISSUE THREAD

**Issue by 24194499** [slowtorta/turtlewow-bug-tracker#5573]
**Please, provide a clear description what the bug is:**
After 2023.11.29,Chromaggus changes resistances EVERY 15 seconds rather than 40 seconds.
Patch notes https://forum.turtle-wow.org/viewtopic.php?t=11972 said,"Made some tweaks to Chromaggus' script."
If it is not a bug,this is a frustrating change for the caster, hard to do DPS in such a short time.
**Steps to reproduce the behavior with as much detail as possible:**

1.fight with BWL's boss Chromaggus.
2. try to do spell damage on Chromaggus,and notice the damage figure changed.
3. it changes every 15s rather than 40 seconds.

**IDs of affected creatures, items, quests or spells with a link to the relevant page:**

NPC: https://database.turtle-wow.org/?npc=14020

**Expected behavior. Describe how it should work:**
Chromaggus changes resistances EVERY 40 seconds, the right amount of time

**Comment by balakethelock** [comment]
Not a bug. The shimmer timer is correct now.

**Comment by twowTurtReynolds** [comment]
If anyone can prove 15s is not correct, please reply to this thread. Until then...
