### ISSUE TITLE
Winter Patriarch stuck in the ground.

### ISSUE THREAD

**Issue by Bralbir** [slowtorta/turtlewow-bug-tracker#5576]
**Please, provide a clear description what the bug is:**

Winter Patriarch stuck in the ground.

**Steps to reproduce the behavior with as much detail as possible:**

1. Accept quest 'The Legend Comes To Life!"
2. Go to mulgore at this regular location
3. he's in the ground, had a priest using mind vision on him.

**IDs of affected creatures, items, quests or spells with a link to the relevant page:**

NPC: https://database.turtle-wow.org/?npc=61172
Quest: https://database.turtle-wow.org/?quest=40782

**Expected behavior. Describe how it should work:**
Kodo boi should be had his regular spot, please move :)

**Comment by twowTurtReynolds** [comment]
A GM handled this for now. I'll try and make sure it persists past restarts.
