### ISSUE TITLE
Ravenholdt faction quest "Syndicate Emblems" bug

### ISSUE THREAD

**Issue by BWills32** [slowtorta/turtlewow-bug-tracker#5577]
**Please, provide a clear description what the bug is:**

Started completing the Ravenholdt rogue faction questline "Syndicate Emblems" for reputation. As soon as i hit "friendly" with Ravenholdt, I became unable to complete the repeatable "blue question mark" rep quests. The guards wont have it as an option when i open dialogue with them.

**Steps to reproduce the behavior with as much detail as possible:**

1. Speak to Fahrad- Grand master rogue at Ravenholt
2. Farm emblems off syndicate member in durnholde
3. Hand in 30 emblems
4. reach friendly with ravenholdt faction
5. Become unable to repeat reputation quests from any quest givers

**IDs of affected creatures, items, quests or spells with a link to the relevant page:**

NPC: 
-->  https://database.turtle-wow.org/?npc=6766
Item: 
--> https://database.turtle-wow.org/?item=17124
Quest: 
--> https://database.turtle-wow.org/?quest=6701

Faction:
https://database.turtle-wow.org/?faction=349

**Expected behavior. Describe how it should work:**
I should be able to complete the repeatable quest if i have the required item.

**Comment by twowTurtReynolds** [comment]
Read https://www.wowhead.com/classic/quest=6701/syndicate-emblems 's comments which say this is blizzlike, and that this quest only brings you to friendly and you have to do other steps from here on.
