### ISSUE TITLE
shadowfang keep door didnt open 

### ISSUE THREAD

**Issue by geojak** [slowtorta/turtlewow-bug-tracker#558]
**Please, provide a clear description what the bug is:**

we were 5 alliance and talked to the archmage dude in the prison and clike the ialog option. the npc said we shall follow him while he opens the door but he never moved a single step and the droo stayed locked. since we were all aliance we had no other way

**Steps to reproduce the behavior with as much detail as possible:**

1. be all allaince
2. talk to mage npc to open the door
3. he doesnt move and door stays closed

**IDs of affected creatures, items, quests or spells with a link to the relevant page:**

NPC: https://database.turtle-wow.org/?npc=
Item: https://database.turtle-wow.org/?item=
Quest: https://database.turtle-wow.org/?quest=
Spell: https://database.turtle-wow.org/?spell=
Object: https://database.turtle-wow.org/?object=

**Expected behavior. Describe how it should work:**

npc moving and door opening for allaince

**Comment by geojak** [comment]
after instance reset it worked second try

**Comment by Neto-WoW** [comment]
Unable to reproduce. Please let us know if this occurs again.

**Comment by geojak** [comment]
someone in world chat hat the same thing happen to them. i think it might be related to players handing in the quest from somwind mage tower that has you talk with the dude
