### ISSUE TITLE
Dishonorable Kills

### ISSUE THREAD

**Issue by kyoukowet** [slowtorta/turtlewow-bug-tracker#5581]
**Please, provide a clear description what the bug is:**
Unintended dishonorable kills
**Steps to reproduce the behavior with as much detail as possible:**

1.join group with someone
2. have them kill a grey leveled player
3. dishonorable kill applies to both?

**IDs of affected creatures, items, quests or spells with a link to the relevant page:**

NPC: https://database.turtle-wow.org/?npc=
Item: https://database.turtle-wow.org/?item=
Quest: https://database.turtle-wow.org/?quest=
Spell: https://database.turtle-wow.org/?spell=
Object: https://database.turtle-wow.org/?object=

**Expected behavior. Describe how it should work:**
I was in a raid group waiting for snowball boss and i guess someone in the raid killed a grey leveled player and I got stuck with a DHK
edit: I got a second dishonorable kill while waiting for the snowball boss respawn
IGN is Plaguejak btw

**Comment by twowTurtReynolds** [comment]
I have just tested, DHKs are currently disabled.
