### ISSUE TITLE
Guild Bank Tab5 Took Items But Did Not Deposit

### ISSUE THREAD

**Issue by khucngantieu** [slowtorta/turtlewow-bug-tracker#5583]
**Please, provide a clear description what the bug is:**
While right-right clicking several items from my bag into Tab5 of Guild Bank I got disconnected from wow.  I logged back on and found only 1 cloak out of 3 was deposited.  The other 2 only cloaks were nowhere to be found.  Neither is it in my bank Tab5 nor on my character.

**Steps to reproduce the behavior with as much detail as possible:**

1.  Open bank
2.  Open player bags
3. Right-click items in succession and lag out or disconnect from wow.

**IDs of affected creatures, items, quests or spells with a link to the relevant page:**

Cloudkeeper - Normal Realm level 60 mage.  Guild Master of:  There And Back Again
Item: https://database.turtle-wow.org/?item=15138

**Expected behavior. Describe how it should work:**
Items put in guild bank Tab5 properly

**Comment by khucngantieu** [comment]
I found the issue.  False alarm.  The 2 cloaks were in another account.

**Comment by twowTurtReynolds** [comment]
Good that you found it. I couldn't replicate.
