### ISSUE TITLE
not able to interact with greatfatherwinter for winterveil quest

### ISSUE THREAD

**Issue by matanel203** [slowtorta/turtlewow-bug-tracker#5588]
**Please, provide a clear description what the bug is:**
not able to interact with greatfatherwinter for winterveil quest
clicking on him dosent give you a option to do the quest
**Steps to reproduce the behavior with as much detail as possible:**

1. take the quest
2. go to ironforge 
3.  talk with the npc

**IDs of affected creatures, items, quests or spells with a link to the relevant page:**

https://database.turtle-wow.org/?npc=13444

**Expected behavior. Describe how it should work:**
add progress towards the quest

**Comment by Zmitrok1984** [comment]
What quest are you doing? 
If that quest [Life Comes To The Legend!](https://database.turtle-wow.org/?quest=40783) , you need another [Greatfather Winter](https://database.turtle-wow.org/?npc=61171)

**Comment by matanel203** [comment]
> What quest are you doing? If that quest [Life Comes To The Legend!](https://database.turtle-wow.org/?quest=40783) , you need another [Greatfather Winter](https://database.turtle-wow.org/?npc=61171)

where do i find him? database shows its the guy in ironforge
