### ISSUE TITLE
Dashel Stonefist - The Missing Diplomat bugged

### ISSUE THREAD

**Issue by KniightYz** [slowtorta/turtlewow-bug-tracker#559]
**Please, provide a clear description what the bug is:**

NPC Dashel Stonefist in Stormwind is bugged and wont interact/speak/complete quest

**Steps to reproduce the behavior with as much detail as possible:**

1. Right click NPC, NPC appears to not have reset after fight and is at 20% HP.
2. 
3. 

**IDs of affected creatures, items, quests or spells with a link to the relevant page:**

NPC:      https://database.turtle-wow.org/?npc=4961

Item: https://database.turtle-wow.org/?item=

Quest: https://database.turtle-wow.org/?quest=1447

Spell: https://database.turtle-wow.org/?spell=
Object: https://database.turtle-wow.org/?object=

**Expected behavior. Describe how it should work:**

NPC/Questgiver

**Comment by slowtorta** [comment]
Tested, working as intended.
