### ISSUE TITLE
Winter Veil Quests Not Reset from Last Year

### ISSUE THREAD

**Issue by Oolaatris** [slowtorta/turtlewow-bug-tracker#5591]
**Please, provide a clear description what the bug is:**
The seasonal quests for Winter Veil have not been reset for players who were here last year and completed any of the quests.  As I recall, this was an issue last year and the quests were reset after the event started. 

**Steps to reproduce the behavior with as much detail as possible:**

1.  Log on a toon who completed any seasonal Winter Veil quests last year
2.  Find that you cannot pick up the quests this year that were completed last year

**Expected behavior. Describe how it should work:**
Seasonal quests are supposed to be reset every year for players to participate yearly.

**Comment by twowTurtReynolds** [comment]
Just confirmed with management: The quest reset last year was a one time thing, due to the event revamp. Going forward, we will not be resetting the quests.
