### ISSUE TITLE
Greet GM，about non-honor killing.

### ISSUE THREAD

**Issue by legendaryyyyyyyyyy** [slowtorta/turtlewow-bug-tracker#5597]
**Please, provide a clear description what the bug is:**
Hello GM, this week's update removed the non-honor killing, but I was in the winter festival activities in the mission, unknowingly received a non- honor killing, and rank from Rank13 to Rank12, is this normal? Because I saw on the official website that non-honor kills were canceled this week.
**Steps to reproduce the behavior with as much detail as possible:**

1.my accout:kakabict123
2. ID:legendaryy
3. 

**IDs of affected creatures, items, quests or spells with a link to the relevant page:**

NPC: https://database.turtle-wow.org/?npc=
Item: https://database.turtle-wow.org/?item=
Quest: https://database.turtle-wow.org/?quest=
Spell: https://database.turtle-wow.org/?spell=
Object: https://database.turtle-wow.org/?object=

**Expected behavior. Describe how it should work:**

**Comment by twowTurtReynolds** [comment]
I will ensure with the staff to check if a server accidentally did not get the DHK disable config setting applied.

Your rank 13 will re-apply next week.
