### ISSUE TITLE
Vanish/Stealth/Feign Death do not cancel casts, and allow for abilities to still hit before the casting time of said ability is done

### ISSUE THREAD

**Issue by imaglcian** [slowtorta/turtlewow-bug-tracker#56]
By opening this Issue, I admit to having done the pertinent research using sources from Vanilla (preferably) or Classic. I also understand that sources from other private servers are not acceptable.

**Current behavior**: 
When a person is casting an ability versus a rogue/hunter, stealth/feign-death/vanish do not cancel casts, remove you from stealth/feign-death and said ability hits you, wasting the cool-down, and hitting you when not supposed to What's happening with Vanish/Stealth is that it unstealthes you when the cast finishes, and hits you. This also affects gold farms like Blackrock Depth pickpocket runs, in where you'd vanish from a resisted pickpocket, but you still aggro mobs that are casting an ability after the initial vanish.
**Expected behavior**: 
The person casting, should expect to see his cast stop as soon as feign death/vanish/stealth is being used to cancel the cast. Or, the cast should finish, and you should get the message "I need a target". A rogue/hunter that use these abilities to cancel casts, should expect NOT to get hit
**Proofs**:
https://www.youtube.com/watch?v=_j4FKYpfwjo is the current behavior in the Twow server.
https://youtu.be/vdentcxaNAQ?t=410 is showcasing the same trick, done on classic servers. (How it was before in Twow servers aswell.)
**Steps to reproduce**:

1. Have a rogue/hunter & a caster; Mage, Shaman, Priest or whatever.
2. Have said caster, use an offensive ability, such as lightning bolt.
3. The rogue/hunter should try to vanish/stealth/invis/feign death before the cast finishes. Following these steps, should result in the rogue/hunter not getting hit by the ability, as seen on the clip above.

**Comment by imaglcian** [comment]
Also found out it vanish doesn't work in raids for resetting fights vs raid bosses. You can reset the fight initially, but after leaving combat (and not entering it again) the boss will still target you.

**Comment by imaglcian** [comment]
I also want to add, that I have been using the "vanish trick" since forever. Can be seen used in these clips. (please not my addon's castbar is incorrect about the chain-lightning cast time as seen on the 2nd clip.)
Vanishing a Chain Lightning cast, aprox. 0.5-1s before cast finishes: https://youtu.be/OwoaXzt6bgA?t=36
https://youtu.be/Q4gGMUklvQI?t=31 (Proof of the castbar timer being incorrect, to justify the first clip. Cast time is aprox. half of what my addon is showing)
Vanishing auto-attack/holy strike aprox. 0.1-0.3s before happening. Swing animation goes off, but vanishing removed him as the target: https://youtu.be/yGGvcJCx9lY?t=79

**Comment by tristanwagner** [comment]
I want to add that shadowmelt (night elves racial) should also have the same behavior as it does on classic

**Comment by jameyboor** [comment]
Fixed in next update.
