### ISSUE TITLE
young crocoliske skin wetlands quest

### ISSUE THREAD

**Issue by geojak** [slowtorta/turtlewow-bug-tracker#560]
**Please, provide a clear description what the bug is:**

the wetlands qeust yung crocolisk skins in wetlands that sent you out to get 4 young crocolisks skins has a wrongly set 100% dropchance. 

**Steps to reproduce the behavior with as much detail as possible:**

1. get the young crocolisk skin quest in wetlands
2. kill 4 crocodiles in front of menethil harbor
3. quest already finished

**IDs of affected creatures, items, quests or spells with a link to the relevant page:**

NPC: https://database.turtle-wow.org/?npc=
Item: https://database.turtle-wow.org/?item=
Quest: https://database.turtle-wow.org/?quest=
Spell: https://database.turtle-wow.org/?spell=
Object: https://database.turtle-wow.org/?object=

**Expected behavior. Describe how it should work:**

the dropchacne is supposed to be much lowere. in classic you needed to kill a lot of crcos. killng just 4 for 4 skins is wrong, might as well be a kill qeust then.

**Comment by geojak** [comment]
the same is the case for the follow up qeust with the giant croc skins

**Comment by geojak** [comment]
similiar for the follow quest with giant crocs

**Comment by Neto-WoW** [comment]
Adjusted to 29% as intended here: https://classic.wowhead.com/item=3397/young-crocolisk-skin

Thanks.

**Comment by geojak** [comment]
thx
