### ISSUE TITLE
Quest - The Tome of Valor - Daphne Not Beginning Event

### ISSUE THREAD

**Issue by buckthetruck** [slowtorta/turtlewow-bug-tracker#5600]
**Please, provide a clear description what the bug is:**

When attempting to begin the Paladin class quest "The Tome of Valor" in Westfall, expected behavior (start of event, waves of enemies) does not occur. Daphne does **not** run into her cottage, but rather sticks in one spot, occasionally gesturing as though someone is engaging in conversation with her every few seconds.

This is on the new Tel'Abim pvp server.

**Steps to reproduce the behavior with as much detail as possible:**

1. Starting this Paladin quest no matter where Daphne is located produces the bug.
2. Have attempted to abandon and re-start the quest mutliple times (giving a few hours in between the last attempts) to no avail.
3. Have waited several minutes for either Daphne to grab her gun and run back out to the "front lawn" or for the waves of enemies to spawn - neither happens (have done this on the standard Twow realm previously without issue.)

**IDs of affected creatures, items, quests or spells with a link to the relevant page:**

NPC: https://database.turtle-wow.org/?npc=6182
Quest: https://database.turtle-wow.org/?quest=1651

**Expected behavior. Describe how it should work:**

After starting the quest, Daphne is usually scripted to run (sometimes awkwardly) into her house to grab a gun for the forthcoming waves of mobs. The event then plays out with (3?) waves of enemies attacking player and Daphne.

Thanks for looking into this!

![Daphne Taking a Break](https://github.com/slowtorta/turtlewow-bug-tracker/assets/153791870/9f433e3c-ccab-4811-9ff2-00108d45672a)

**Comment by twowTurtReynolds** [comment]
![image](https://github.com/slowtorta/turtlewow-bug-tracker/assets/151180101/7b1b3ef4-c1dc-4aae-950d-09c92ca9b438)
I'm not sure what you mean. She goes inside, grabs a gun and comes back out. 
![image](https://github.com/slowtorta/turtlewow-bug-tracker/assets/151180101/33f155bf-6b34-48bd-b7c5-d4ca74094893)
