### ISSUE TITLE
Vampirism is not working

### ISSUE THREAD

**Issue by MenelauGC** [slowtorta/turtlewow-bug-tracker#5601]
**Please, provide a clear description what the bug is:**Any item with vampirism or enchants don't give any healing on hit.

**Steps to reproduce the behavior with as much detail as possible:**Items or enchants with "1% of damage dealt is returned as healing"
don't give any healing.

1.Items or enchants with "1% of damage dealt is returned as healing"
don't give any healing.
2. Items or enchants with "1% of damage dealt is returned as healing"
don't give any healing.
3. Items or enchants with "1% of damage dealt is returned as healing"
don't give any healing.

**IDs of affected creatures, items, quests or spells with a link to the relevant page:**Items ID's : 66374,66371,17474,7688,60979.
All items or enchants with "1% of damage dealt is returned as healing" don't give any healing.
All items with this bonus is specific to Turtle WoW.The item id's i listed are only a few but like i said before,all items with this bonus dont give any healing.
All items with this bonus is specific to Turtle WoW.The item id's below are only a few but like i said before,all items with this bonus dont give any healing.

NPC: https://database.turtle-wow.org/?npc=
Item: https://database.turtle-wow.org/?item=
Quest: https://database.turtle-wow.org/?quest=
Spell: https://database.turtle-wow.org/?spell=
Object: https://database.turtle-wow.org/?object=

**Expected behavior. Describe how it should work:**Items with  "1% of damage dealt is returned as healing" should give heal on physical melee or ranged hit.
Thank you for your time.

**Comment by twowTurtReynolds** [comment]
The healing does not show on the combat log. Watch your HP with addons, and you will notice that it is working.
