### ISSUE TITLE
The winter Patriarch does not respond to players

### ISSUE THREAD

**Issue by sivgag** [slowtorta/turtlewow-bug-tracker#5605]
**Please, provide a clear description what the bug is:**

**Steps to reproduce the behavior with as much detail as possible:**

1. The winter Patriarch does not respond to players. 
2.  Multiple players tried relog in and WDB deletion and they did not work either.
3. It happens after the server restart at 5:30 on Friday 15.12.2023

**IDs of affected creatures, items, quests or spells with a link to the relevant page:**

NPC: https://database.turtle-wow.org/?npc=The Winter Patriarch
Item: https://database.turtle-wow.org/?item=
Quest: https://database.turtle-wow.org/?quest=
Spell: https://database.turtle-wow.org/?spell=
Object: https://database.turtle-wow.org/?object=

**Expected behavior. Describe how it should work:**

**Comment by twowTurtReynolds** [comment]
He does respond correctly now, and these quests are now completable on the PTR. There may be a change that needs to hit live with the next restart, so try then.
![image](https://github.com/slowtorta/turtlewow-bug-tracker/assets/151180101/14b93fb9-30ec-48e8-a96c-fa2a1cfe98af)
