### ISSUE TITLE
Winter Veil Snowball NPC Bug

### ISSUE THREAD

**Issue by Woahmojo123** [slowtorta/turtlewow-bug-tracker#5606]
Hi, my in game name is "Misskiss" on the TurtleWoW server. ^-^

A) I managed to kill Snowball with my raid, I had the quest [Peace Comes At A Price] and upon killing the Snowball NPC did not receive quest credit for killing Snowball. I could loot Snowball and everything just find but did not get the quest credit for killing Snowball :_(

B) I'm really not sure why this occurred and rly sad not to get the 20 slot bag

**IDs of affected creatures, items, quests

NPC: https://database.turtle-wow.org/?npc=50112

Item: https://database.turtle-wow.org/?item=61089

Quest: https://database.turtle-wow.org/?quest=50330

Object: https://database.turtle-wow.org/?item=61089

**Expected behavior. Describe how it should work:**

Is there any way to see my logs? I really hope that this quest can be completed :) thanks!

**Comment by twowTurtReynolds** [comment]
![image](https://github.com/slowtorta/turtlewow-bug-tracker/assets/151180101/e4e7ced5-bd03-4657-8926-406b3ce32bbb)

The quest works fine.

You may wish to work with a GM.

**Comment by Woahmojo123** [comment]
Well, first off I really appreciate you taking the time to test this to see if it is an actual bug  that effects ofthers. I still don't understand why this "bug" happened to me when I had the tag and killed it with my raid... Just a major bummer i didn't receive quest credit after spending nearly 9 hours camping him. I love turtle wow and will continue loving it... thank you for testing to see if this is in fact effecting other people. Also to answered your statement regarding contacting a GM: I did and the GM told me to submit a support on here....Can you complete this quest for me? I promise I'm not fabricating this. I have sent multiple tickets trying to reach a GM that will help but they all say to submit a report on here. 

I'm a really nice player you can even look at my logs. Some of the players in my raid at the time were "Padrescruff", Yamka, Becleansed if that helps at all.

**Comment by twowTurtReynolds** [comment]
Please contact a GM as I said.

**Comment by Woahmojo123** [comment]
ok I understand
