### ISSUE TITLE
Ferra's Collar Trinket Not Working on Orc Hunter

### ISSUE THREAD

**Issue by Manbearboar** [slowtorta/turtlewow-bug-tracker#5607]
**Please, provide a clear description what the bug is:**
Ferra's Collar is supposed to increase the hunters pet damage by +4% but It doesn't increase orc hunters pet damage at all. I don't know about other races, I haven't found any other hunter with it.

**Steps to reproduce the behavior with as much detail as possible:**

1. Maybe it is not stacking with the racial ability called 'Command', which increases pet damage by +5%.
2. I have other pet increasing items that I tried removing and seeing if I would get the pet increase from Ferra's Collar. Didn't work
3. The problem seems to be similar what we had with 'Breastleplate of Beast Mastery' not stacking with the t0.5 set.

**IDs of affected creatures, items, quests or spells with a link to the relevant page:**

NPC: https://database.turtle-wow.org/?npc=14308
Item: https://database.turtle-wow.org/?item=18355
Quest: https://database.turtle-wow.org/?quest=
Spell: https://database.turtle-wow.org/?spell=22854
Object: https://database.turtle-wow.org/?object=

**Expected behavior. Describe how it should work:**
Ferra's Collar should increase the hunter pet's damage by +4%.

**Comment by twowTurtReynolds** [comment]
Related to https://github.com/slowtorta/turtlewow-bug-tracker/issues/5386. There I confirmed that the spell on the item stacks with itself, but I did not test for conflicting with the orc racial.

**Comment by twowTurtReynolds** [comment]
Here is Command 20576 stacked roughly 50 times
![image](https://github.com/slowtorta/turtlewow-bug-tracker/assets/151180101/0b692bbf-f60d-42d9-8d3e-add9fd89b3ba)

And then I stacked Ferra 22854 roughly 30, and here we can see: Command x50 + Ferra x30:
![image](https://github.com/slowtorta/turtlewow-bug-tracker/assets/151180101/a9a47ac7-2290-4af3-a896-f8588e0ec367)

We can see that they seem to be stacking interchangeably. All is well.

**Comment by Manbearboar** [comment]
is the pet info bugged out then? theres no damage or DPS change when I use Ferra's Collar. damage stays the same as does DPS

**Comment by cyaohiri** [comment]
> is the pet info bugged out then? theres no damage or DPS change when I use Ferra's Collar. damage stays the same as does DPS

In general, damage increases are best tested with a target dummy and the combat log. Stats on the UI can be wrong sometimes, especially if they're calculated by addons.

**Comment by Manbearboar** [comment]
Im not using any addons. All other parts that increases my pets dmg will be shown with 1 second delay on the pet info expect for Ferra's Collar.

**Comment by Manbearboar** [comment]
I just dont understand why all other items are working as intended and showing the small dmg upgrade on the UI while Ferra's Collar is doing nothing. Of all the items just this one doesnt seems to show dmg upgrade in the UI. seems weird
