### ISSUE TITLE
Unable to Learn Druid Glyphs

### ISSUE THREAD

**Issue by UnholyNAch** [slowtorta/turtlewow-bug-tracker#5609]
**Please, provide a clear description what the bug is:**

Recently Purchased Druid: Glyph of the Orca, and had Druid: Glyph of the Stag on my character Mitoria.  When right clicking the items nothing happened and nothing changed within my spell book.  The glyphs are still within my inventory.
After inputting a ticket and speaking to a GM I was instructed to try emptying my WDB folder and turning off all addons before attempting to learn the glyphs again.  Unfortunately, this did not seem to change anything.
The GM also checked if my client was modified in a way that might interfere with the new patches content and we concluded that was not happening either.

**Steps to reproduce the behavior with as much detail as possible:**

1.Right Click Druid: Glyph of the Orca
2. Nothing Happens
3. 

**IDs of affected creatures, items, quests or spells with a link to the relevant page:**

Display ID: 7694

NPC: https://database.turtle-wow.org/?npc=
Item: https://database.turtle-wow.org/?item=
Quest: https://database.turtle-wow.org/?quest=
Spell: https://database.turtle-wow.org/?spell=
Object: https://database.turtle-wow.org/?object=

**Expected behavior. Describe how it should work:**

I have been informed that when you right click the Glyph your character should then "learn" the glyphs spell.  This should then be located within your spell book and you can cast it to have a alternative skin of the designated druid form.

**Comment by twowTurtReynolds** [comment]
![image](https://github.com/slowtorta/turtlewow-bug-tracker/assets/151180101/85346f13-0068-4699-8def-36524d78feff)
Works fine. Something is up with either your character or your client, there's nothing for the dev team to fix.
