### ISSUE TITLE
Dalinda Malem - Bugged NPC

### ISSUE THREAD

**Issue by KniightYz** [slowtorta/turtlewow-bug-tracker#561]
**Please, provide a clear description what the bug is:**

Bugged NPC 'Dalinda Malem' is out of place and hasn't reset position (Escort NPC)
-Location: Desolace (Thunder Axe Fortress)

**Steps to reproduce the behavior with as much detail as possible:**

1. Interact with said NPC their position has not reset and is not standing in her normal spot.
-Gives Escort quest but walks in the wrong direction
2. 
3. 

**IDs of affected creatures, items, quests or spells with a link to the relevant page:**

NPC: https://database.turtle-wow.org/?npc=5644

Item: https://database.turtle-wow.org/?item=

Quest: https://database.turtle-wow.org/?quest=1440

Spell: https://database.turtle-wow.org/?spell=
Object: https://database.turtle-wow.org/?object=

**Expected behavior. Describe how it should work:**
Escort NPC, respawns in the Thunder Axe Fortress Citadel which is also the starting position.

**Comment by Tinyfin-github** [comment]
Issue similar to #336 

Temporarily fixed.
