### ISSUE TITLE
Website: Character list

### ISSUE THREAD

**Issue by cyaohiri** [slowtorta/turtlewow-bug-tracker#5611]
The account management panel on the website no longer lists the characters.
https://turtle-wow.org/#/ucp/characters
![image](https://github.com/slowtorta/turtlewow-bug-tracker/assets/86041826/acd697fd-3caa-412d-b945-fd05772f8ebf)

**Comment by slowtorta** [comment]
The website will receive a general overhaul in the next weeks, this one will be fixed.
