### ISSUE TITLE
Able to use opposing faction portal

### ISSUE THREAD

**Issue by Paistinpannu** [slowtorta/turtlewow-bug-tracker#5614]
**Please, provide a clear description what the bug is:**

Hello. I was able to use an alliance Stormwind portal while in a dungeon group. I am horde (Goljin, troll hunter)
I thought our gnome mage was casting oranges but it was a portal. As soon as it opened I clicked it fast and was able to teleport to SW mage tower. I killed a couple alliance while I was there, got killed and finally HS'd back home. This could be used for pvp invasions or something of the like so theres some potential to "cheat" here.

-Paistinpannu

**Steps to reproduce the behavior with as much detail as possible:**

1. Group up with opposing faction
2.  Ask for portal
3.  Click as soon as it opens

**Comment by cyaohiri** [comment]
As far as I'm aware, this is intended.

**Comment by twowTurtReynolds** [comment]
This is currently intended.
