### ISSUE TITLE
Not Getting the Contribution after wasting 14 hours waiting for Snowball

### ISSUE THREAD

**Issue by drankrabit** [slowtorta/turtlewow-bug-tracker#5617]
**Please, provide a clear description what the bug is:**

I was doing the raid to kill Snowball in Winter Veil Vale in order to get the bag "The Great Sack of Winter Veil" from the quest "Peace Comes at a Price", after him finally spawning we started the fight. We killed him at about 9:45 server time, but right as we killed him I got killed by a human paladin (I am a Forsaken Warlock) because I have War Mode enabled and had not a lot of health left from the fight. Because of the death I got removed from the contribution list of the fight and I didn't get quest completion nor access to the loot he had dropped, thus resulting in me having wasted 14 hours waiting for snowball to spawn plus having to wait 14 hours more just to have another chance at getting the damn bag.

**Steps to reproduce the behavior with as much detail as possible:**

1. Participate in a raid for Snowball where your team had tagged him and manage to kill him.
2. When the mob dies get killed by something (in my case another player).
3. Quest participation + mob drops are not given.

**IDs of affected creatures, items, quests or spells with a link to the relevant page:**

NPC: https://database.turtle-wow.org/?npc=50112
Quest: https://database.turtle-wow.org/?quest=50330

**Expected behavior. Describe how it should work:**

getting the Contribution to the killing of the mob, getting to see the inventory of the mob + getting to roll on the items, getting the quest completed

**Comment by twowTurtReynolds** [comment]
Did you release before snowball was killed? If so, that's working as intended.
