### ISSUE TITLE
Ranking Point gain on turtle wow is bugged

### ISSUE THREAD

**Issue by Capracou** [slowtorta/turtlewow-bug-tracker#5618]
Hello, last week (06.12 to 13.12) The Ranking Points gain on the Tel'Abim PVP server was bugged.
Standing 1 received 13.000 RP as he should, standing 4 received 12.822 RP, but then standing 5 received 11.080 RP when he should've received 12.000 RP exactly for being top bracket 2 spot. Not a single player in bracket 2 received more than 11.100 RP, which isn't normal.

**Comment by twowTurtReynolds** [comment]
Players do not have reliable ways to find out who is in what bracket. Honorspy commonly misleads people.

Our dev team have recently reviewed the ranking code and found it to be working as intended.
