### ISSUE TITLE
Heavy Lamellar Shield of Blocking not blocking

### ISSUE THREAD

**Issue by Mechsoap** [slowtorta/turtlewow-bug-tracker#5620]
**Please, provide a clear description what the bug is:**
with the shield equipped, my character is unable to block, even with a 70% chance of blocking. it also acts a bit weird and when comparing shields its as if its an offhand. i don't know if it effects all the variants of it, but the one of Blocking is the one i used. when i switched to another shield it worked fine.

**Steps to reproduce the behavior with as much detail as possible:**

1. equip shield
2. try to block
3. fail to block

**IDs of affected creatures, items, quests or spells with a link to the relevant page:**

Item: https://database.turtle-wow.org/?item=10204

**Expected behavior. Describe how it should work:**
it oughta block.

**Comment by twowTurtReynolds** [comment]
Please attach links when you post. https://database.turtle-wow.org/?item=10204

**Comment by twowTurtReynolds** [comment]
![image](https://github.com/slowtorta/turtlewow-bug-tracker/assets/151180101/99bf12c1-edea-48c4-9aeb-412bba4cf7ed)
Not sure what you mean. I am getting plenty of blocks with this piece of gear.

**Comment by Mechsoap** [comment]
hmm, only difference more is i had +2 block enchant on the shield, dunno if that would do anything...

**Comment by Mechsoap** [comment]
it works now, may have been WDB, sorry for wasting your time, didn't think that WDB could affect such things.

**Comment by twowTurtReynolds** [comment]
That would be weird that WDB was to cause.

Glad ya got it working for ya tho.
