### ISSUE TITLE
I passed through a chimney in Caer Darrow

### ISSUE THREAD

**Issue by Scarecrow4012** [slowtorta/turtlewow-bug-tracker#5623]
**Please, provide a clear description what the bug is:**
Well, I was casually poaching Shockwarden and suddenly I just jumped near a ruined house in Caer Darrow to go somewhere else, on one of the slopes there that has a chimney nearby, when out of nowhere I crossed that chimney and I got trapped inside it, I had to wait for my Heartstone to reset so I could go somewhere else.
**Steps to reproduce the behavior with as much detail as possible:**
1. Go to Caer Darrow and stand on one of the slopes there, make sure you are in the same approximate place on the minimap, I will attach a screenshot so you can get a rough idea of what the house was.

2. He jumps towards or near the chimney, I don't think he came out the first time, maybe it was a fluke, but I'm sure it could happen again to someone, so I'd better report it.

3. You will see that you are trapped inside it with no way out unless you use the Heartstone or the trapped character unlocker.

**IDs of affected creatures, items, quests or spells with a link to the relevant page:**

NPC: https://database.turtle-wow.org/?npc=
Item: https://database.turtle-wow.org/?item=
Quest: https://database.turtle-wow.org/?quest=
Spell: https://database.turtle-wow.org/?spell=
Object: https://database.turtle-wow.org/?object=

**Expected behavior. Describe how it should work:**
You shouldn't be able to get through the chimney, as it should be a completely solid object.

Some screenshots:
https://drive.google.com/file/d/1TJC47eZEwryXhO_oW0_C-CFqNBnERuLA/view?usp=drive_link
https://drive.google.com/file/d/1d8jyMH-_20-JMubkd925EeMiAe0nxp5m/view?usp=drive_link
https://drive.google.com/file/d/1buPoXUuhrueCb9vo6CV6l9e_i-y6q7J4/view?usp=drive_link
https://drive.google.com/file/d/1as8IsIYPFEqymVvtsyeNR_1MzUE-paQ4/view?usp=drive_link

**Comment by twowTurtReynolds** [comment]
This is just how it is on 1.12, replicated on vmangos:

![image](https://github.com/slowtorta/turtlewow-bug-tracker/assets/151180101/c7f82614-f087-4153-a6bd-177e64b0f929)

There are tons of these little clips and issues in 1.12 and our policy is generally to not change them when so minor.
