### ISSUE TITLE
Little Silvermoon doesn't have the right music+ambience

### ISSUE THREAD

**Issue by Scarecrow4012** [slowtorta/turtlewow-bug-tracker#5624]
**Please, provide a clear description what the bug is:**
Some time ago, the small alley in what is Little Silvermoon always shows the name "Little Silvermoon" and the music of Alah'thalas was reproduced, but now only shows "Cut-throat Alley" with the normal music of Stormwind.
**Steps to reproduce the behavior with as much detail as possible:**

1. Go to Stormwind
2.  Go to the Dwarven District
3.  Enter in the area of High Elves called Little Silvermoon.

**IDs of affected creatures, items, quests or spells with a link to the relevant page:**

NPC: https://database.turtle-wow.org/?npc=
Item: https://database.turtle-wow.org/?item=
Quest: https://database.turtle-wow.org/?quest=
Spell: https://database.turtle-wow.org/?spell=
Object: https://database.turtle-wow.org/?object=

**Expected behavior. Describe how it should work:**
The area needs to show the name "Little Silvermoon" and reproduce the music of Alah'thalas, as I can remember, this worked like this in the past.
EDIT: I tried deleting the Patch-4 and worked back well, so, I guess the problem it's in that file.
A screenshot:
https://drive.google.com/file/d/1w04KQL7czVO9GgtI8Op2sT1zCyuxtx_P/view?usp=sharing

Patch-4 deleted:
https://drive.google.com/file/d/12VlDsI5By9vb-k07Z56Lb2xHeBYgd20q/view?usp=sharing

**Comment by twowTurtReynolds** [comment]
I can confirm your findings for the state of 1.16.5 and 1.17.0 respectively.

Someone already fixed the zone bug in patch-5.mpq
![image](https://github.com/slowtorta/turtlewow-bug-tracker/assets/151180101/967e76c7-e7a9-4df1-83b7-cc893cf58e6c)

But the stormwind audio issue persists.

**Comment by slowtorta** [comment]
Fixed in 1.17.1

**Comment by twowTurtReynolds** [comment]
@slowtorta this didn't seem to make it into 1.17.1.

**Comment by slowtorta** [comment]
![image](https://github.com/slowtorta/turtlewow-bug-tracker/assets/66763404/52a46002-a64d-4cd0-b305-22a3a9eebda1)
The name is correct. For the music, we might need something new, create a task in the Sound Design team board.
