### ISSUE TITLE
Baron Rivendare loot table bug

### ISSUE THREAD

**Issue by Varjag1** [slowtorta/turtlewow-bug-tracker#5625]
**Please, provide a clear description what the bug is:**

**Steps to reproduce the behavior with as much detail as possible:**

1.
2. 
3. 

**IDs of affected creatures, items, quests or spells with a link to the relevant page:**

NPC: https://database.turtle-wow.org/?npc=
Item: https://database.turtle-wow.org/?item=
Quest: https://database.turtle-wow.org/?quest=
Spell: https://database.turtle-wow.org/?spell=
Object: https://database.turtle-wow.org/?object=

**Expected behavior. Describe how it should work:**

Warrior dungeon tier pants haven't dropped in over 25 runs, and another I spoke to, he's done Strat UD 35 runs and the warrior pants have never dropped. I think it's a loot table bugg because the warrior pants is in the lower slot of the table, so it hardly gets chosen. Priest + mage + warlock pants have dropped 75% of the times. This is absrud. Please send a pair of Warrior pants to my main warrior on the PvP server Tel'Abim "Varjag" orc warrior lvl 60.

**Comment by twowTurtReynolds** [comment]
Do not make demands to turtle staff to give you loot.

![image](https://github.com/slowtorta/turtlewow-bug-tracker/assets/151180101/b165e104-be4d-419a-9e08-85416636aa41)

He dropped the item on my 8th kill. Works fine.
