### ISSUE TITLE
Deepwood Pipe Trinket

### ISSUE THREAD

**Issue by welpenhund** [slowtorta/turtlewow-bug-tracker#5626]
**Please, provide a clear description what the bug is:**
Even though it counts as a stun it can not be trinketed by pvp trinkets (druid for exmaple) and bypasses free action potions. (which are supposed to prevent you from being stunned)

**Steps to reproduce the behavior with as much detail as possible:**

1.  Duel yourself and use the trinket
2.  Try to pvp trinket or pop a free action potion
3.  Be still stunned the full duration.

**IDs of affected creatures, items, quests or spells with a link to the relevant page:**

NPC: https://database.turtle-wow.org/?npc=
Item: https://database.turtle-wow.org/?item=61754
Quest: https://database.turtle-wow.org/?quest=
Spell: https://database.turtle-wow.org/?spell=
Object: https://database.turtle-wow.org/?object=

**Expected behavior. Describe how it should work:**
The item tooltip says ""Emits a cloud of smoke, stunning nearby enemies for 3 sec. and putting the caster into stealth mode.""" therefor it should be possible to trinket this stun or bypass it with a free action potion. (Else please change the tooltip to something else, cause it says stun)

**Comment by ratkosrb** [comment]
It should be fixed in the next update.
