### ISSUE TITLE
Invisible Water

### ISSUE THREAD

**Issue by Boatimus** [slowtorta/turtlewow-bug-tracker#5632]
**Please, provide a clear description what the bug is:**

In Hillsbrad Foothills at the base of the rocks just above the sea, directly to the East of Southshore, there's a patch of water that is invisible and doesn't initiate swimming, but does take away breath. It does have a pool of fish on it's edge with the visible/normal water. 

**Steps to reproduce the behavior with as much detail as possible:**

**IDs of affected creatures, items, quests or spells with a link to the relevant page:**

NPC: https://database.turtle-wow.org/?npc=
Item: https://database.turtle-wow.org/?item=
Quest: https://database.turtle-wow.org/?quest=
Spell: https://database.turtle-wow.org/?spell=
Object: https://database.turtle-wow.org/?object=

**Expected behavior. Describe how it should work:**

**Comment by cyaohiri** [comment]
Is it the same spot as in #5579?

**Comment by twowTurtReynolds** [comment]
It has got to be that. Closing as dupe.
