### ISSUE TITLE
Male Troll Levitate Visual Bug

### ISSUE THREAD

**Issue by trh-hx** [slowtorta/turtlewow-bug-tracker#5634]
**Please, provide a clear description what the bug is:**

When using Levitate on a male troll priest, there is no levitate animation. The priest just stands in midair rather than floating: https://i.imgur.com/vEXB8ab.png

**Steps to reproduce the behavior with as much detail as possible:**

1. Make male troll priest
2. Use levitate

**IDs of affected creatures, items, quests or spells with a link to the relevant page:**

Spell: https://database.turtle-wow.org/?spell=1706

**Expected behavior. Describe how it should work:**

Should have a unique float idle animation, like this: https://wow.zamimg.com/uploads/screenshots/normal/77809-levitate.jpg

**Comment by twowTurtReynolds** [comment]
Welcome to vanilla! The floating animations were added in TBC for all races.
