### ISSUE TITLE
Fimble Finespindle won't teach me new leatherworking recipes.

### ISSUE THREAD

**Issue by bluser86** [slowtorta/turtlewow-bug-tracker#564]
**Please, provide a clear description what the bug is:**

I am unable to learn leatherworking recipes from the Ironforge expert leatherworking trainer Fimble Finespindle

**Steps to reproduce the behavior with as much detail as possible:**

1. Go to Findle to learn some leatherworking stuff.
2. Nothing happens when clicking on "Train"
3. Doing the same at the expert leatherworking trainer in Stormwind, Simon Tanner, works fine.

**IDs of affected creatures, items, quests or spells with a link to the relevant page:**

Fimble Finespindle: https://database.turtle-wow.org/?npc=5127
Simon Tanner: https://database.turtle-wow.org/?npc=5564

**Expected behavior. Describe how it should work:**

When training available recipes/patterns at this NPC I expect my character to learn these recipes/patterns.

**Comment by Neto-WoW** [comment]
As you can see below, this NPC is not meant to offer Expert level leatherworking, despite his subname. 

https://classic.wowhead.com/guides/leatherworking-leveling-1-300-wow-classic

He offers Journeyman Leatherworking.
![image](https://user-images.githubusercontent.com/79717052/147858864-72e266d8-fe32-43b3-a317-e62ebe11f7f2.png)
