### ISSUE TITLE
Bugged Vilewing Batwing in NE Gilneas

### ISSUE THREAD

**Issue by thedjten4** [slowtorta/turtlewow-bug-tracker#5641]
Bugged mob at this location in Gilneas:
![image](https://github.com/slowtorta/turtlewow-bug-tracker/assets/154266870/74478edf-e0d8-45f3-9a4a-a8978a8d9e73)

1. Find mob
2. Attempt to attack, LOS is wrong and will exit fight or only work literally on top of mob
3. Mob will evade perm and then exit combat

The Duskpelt Prowler behind it, the last mob in that row before edge of the map, is also bugged.

NPC: https://database.turtle-wow.org/?npc=61230

Mob should be normally killable, LOS pretty open in that area, but is effectively invincible.

**Comment by twowTurtReynolds** [comment]
![image](https://github.com/slowtorta/turtlewow-bug-tracker/assets/151180101/b1e49f09-e3e7-4c68-9842-3f67ccd7b44b)
![image](https://github.com/slowtorta/turtlewow-bug-tracker/assets/151180101/63da59d4-278f-4118-b4ea-396c0c865477)
Everything seems to work. Please show a video.

**Comment by thedjten4** [comment]
Thank you for the reply. I have attempted to reproduce the issue again after the latest patch for video, but was unable to do so, the two mobs are OK now.
