### ISSUE TITLE
"Snowball" Mount turned Soulbound in bags overnight

### ISSUE THREAD

**Issue by Pointbp** [slowtorta/turtlewow-bug-tracker#5642]
**Please, provide a clear description what the bug is:**

So, i was the first one on the server to obtain "Snowball", the mount dropped from the Winter Veil Vale World boss. It's been in my bags ever since, becuase i do not have the required 150 riding skill to use this. 

Over the last days, i have tried to sell it for gold, and have been able to put it in trade window with other players to show them the mount, but have not been able to sell it yet. Today i found a buyer, and when we met up and i was gonna put the mount in the trade window, it said "cannot trade soulbound items" .  This is VERY strange, considering there is no way i CAN use it yet, due to my riding skill. Also, i know i haven't right-clicked it to use it, and i am assuming if i ever did, it would prompt me the window "using this item will make it soulbound" which i most definitely not have pressed accept on. 

When i link the mount to other people, it still says "Binds when used" and not Binds when Pickup, so i have NO idea what is going on here, and would very much like some help to resolve this problem. 

**Steps to reproduce the behavior with as much detail as possible:**

1. Go to sleep
2.  Wake up
3.  Be confused

**IDs of affected creatures, items, quests or spells with a link to the relevant page:**

NPC: https://database.turtle-wow.org/?npc=50112
Item: https://database.turtle-wow.org/?item=51249

**Expected behavior. Describe how it should work:**

Expected behaviour is as it has been before, Able to put in trade window and sell it to other players. It should be "Binds when Used" and not Soulbound when i don't even have the riding skill to use this item

ADDED GYAZO PICTURE LINKS;;

https://gyazo.com/d9313d2e03ba9662c67a13f5a949cdc6    -- Shows the item being soulbound, and riding skill being red (not high enough riding skill, and item in bag, next to my heartstone

https://gyazo.com/a839959188650949271a06b947e782d4   --  Shows that when linked, the mount is supposed to be "Binds when used"

**Comment by cyaohiri** [comment]
It was made BoP in today's patch. https://forum.turtle-wow.org/viewtopic.php?t=12255

**Comment by twowTurtReynolds** [comment]
This was intentional.
