### ISSUE TITLE
Four horsemen cast their mark one second too early and one second too frequently

### ISSUE THREAD

**Issue by balakethelock** [slowtorta/turtlewow-bug-tracker#5643]
**Please, provide a clear description what the bug is:**
All four horsemen cast their first mark 20 secs after pull and repeat a mark every 12 seconds.

**Steps to reproduce the behavior with as much detail as possible:**

1. Pull the boss, count the time between each mark application
2. see that its different from classic
3. hello

**IDs of affected creatures, items, quests or spells with a link to the relevant page:**

Spell: doesn't matter the boss script is core

**Expected behavior. Describe how it should work:**
The correct timer is 1st park on 21 secs after pull, a new mark every 13 seconds.
https://vanilla.warcraftlogs.com/reports/ByqpWcrk4R89TmA6#fight=84&type=casts&hostility=1&ability=28835

**Comment by twowTurtReynolds** [comment]
Confirmed 20s and 12s on latest vmangos.

https://youtu.be/hb_YpJplz8U?t=86 I'm counting 12s inbetween these marks. Looks like you have found a Classic bug!
