### ISSUE TITLE
Dishonerable kill for killing a flagged warmode player who was grey

### ISSUE THREAD

**Issue by Hydroponixx** [slowtorta/turtlewow-bug-tracker#5645]
**Please, provide a clear description what the bug is:**
I got a dishonerable kill for killing a flagged warmode player who was grey in level.

**Steps to reproduce the behavior with as much detail as possible:**

1. Flagged for pvp
2.  Kill a player who is grey level compared to you
3.  Do it inside the Winter Veil area

**IDs of affected creatures, items, quests or spells with a link to the relevant page:**

Don't remember the spell

**Expected behavior. Describe how it should work:**

Should not give Dishonerable kills. This obviously hurts you incredibily if your trying to rank, which I am. I made a ticket when it happened and the GM told me it was a bug. I just wanted to confirm if this was in fact a bug and was seeing what I could do to get it removed. Player name Hydroponixx Troll Shaman. Appreciate your time :)

**Comment by twowTurtReynolds** [comment]
DHKs should be disabled today.
