### ISSUE TITLE
wand Lodestone wrong hand

### ISSUE THREAD

**Issue by Jirouniuniu** [slowtorta/turtlewow-bug-tracker#5646]
**Please, provide a clear description what the bug is:**
Lodestone is weilded on the left instead of right hand.

**IDs of affected creatures, items, quests or spells with a link to the relevant page:**

Item: https://database.turtle-wow.org/?item=61020

**Comment by grynold** [comment]
Its one of these wrong hand wands right? Wand held in left hand and projectiles shooting out of a empty right hand. They seems really really hard to fix.

**Comment by twowTurtReynolds** [comment]
Same issue as https://github.com/slowtorta/turtlewow-bug-tracker/issues/3865 https://github.com/slowtorta/turtlewow-bug-tracker/issues/4211

Edited your post.
