### ISSUE TITLE
Serpentblooms in WC are really hard to click on

### ISSUE THREAD

**Issue by Niraf** [slowtorta/turtlewow-bug-tracker#565]
**Please, provide a clear description what the bug is:**
While doing WC yesterday i noticed that the serpentblooms are only clickable on certain pixels, also they seem to be spawn a little bit under the ground
**Steps to reproduce the behavior with as much detail as possible:**

1. Go to Wailing caverns and pick up the Serpentbloom quest https://database.turtle-wow.org/?quest=60125
2. Try to pick up a Serpentbloom
3. 

**IDs of affected creatures, items, quests or spells with a link to the relevant page:**

NPC: https://database.turtle-wow.org/?npc=
Item: https://database.turtle-wow.org/?item=5339
Quest: https://database.turtle-wow.org/?quest=60125

Object: https://database.turtle-wow.org/?object=19535

**Expected behavior. Describe how it should work:**
The flower shouldn't be that hard to click on, try to make the object clickable on all ends

**Comment by CantCastThatYet** [comment]
As of september 2022 this bug is not fixed. Collecting serpentbloom is still pixelhunting

**Comment by RUTHINAS** [comment]
This was an issue in December 2022 as well. It seems to be more prevalent on the serpentbloom spawns outside the instance proper. Farming them inside the instance isn't feasible, however, as there are not enough spawn points for all five party members.

Of note is that all the serpentblooms outside the instance _can_ be collected. It just takes searching for the exact pixel to click on, usually beyond the edges of the actually displayed flower.
