### ISSUE TITLE
The bat flight position is not centered correctly

### ISSUE THREAD

**Issue by Hydra9268** [slowtorta/turtlewow-bug-tracker#5651]
**Please, provide a clear description of what the bug is:**

The bat is not centered on the screen whenever I take a bat flight. Instead, it's positioned off-center towards the bottom.

Here are a few screenshots:

Leaving Undercity through the sewers: https://i.imgur.com/sKkPVxX.jpeg
Exiting the Undercity sewers: https://i.imgur.com/UOSSOtZ.jpeg
Typically how it looks: https://i.imgur.com/ZAUBjNw.jpeg

Here's a 40-second video showing the problem. Could you observe the camera moving downward after the flight ends?

https://www.veed.io/view/de93381b-7d8d-43e0-983b-989a5b0a26c9?panel=share

This issue doesn't occur when flying on a Wyvern.

**Steps to reproduce the behavior with as much detail as possible:**

1. Visit Undercity and use a bat flight.
2. Observe that the bat's position is off-center, towards the bottom.

**IDs of affected creatures, items, quests, or spells with a link to the relevant page:**

NPC: https://database.turtle-wow.org/?object=58597

**Expected behavior. Describe how it should work:**

The bat should be centered on the screen.

**Comment by twowTurtReynolds** [comment]
![image](https://github.com/slowtorta/turtlewow-bug-tracker/assets/151180101/48951755-4a95-4656-b184-afb1392549e7)
![image](https://github.com/slowtorta/turtlewow-bug-tracker/assets/151180101/4d3a1c67-33b1-4b9f-8ffb-5a2ee70681c5)

Looks the same on PTR as it does on vmangos. I'm not sure what the problem is.

**Comment by Hydra9268** [comment]
I'm using the Turtle HD mod; that may be the cause. I'll post a message on the project's forum.
