### ISSUE TITLE
Item Crab Catcher's Hat isn't working properly

### ISSUE THREAD

**Issue by xDeltaMirage** [slowtorta/turtlewow-bug-tracker#5654]
**Please, provide a clear description what the bug is:** The custom item Crab Catcher's Hat isn't working properly. It's supposed to provide its user with +1% chance to dodge attacks when it actually provides just 0.43% (I've checked this using the addon BetterCharacterStats and by comparing the hat to The 'Slip' Dagger, which grants the correct effect).

**Steps to reproduce the behavior with as much detail as possible:**

1. Equip the item.
2. Check with the addon.

**IDs of affected creatures, items, quests or spells with a link to the relevant page:**

Item: https://database.turtle-wow.org/?item=81014
Also mentioned: https://database.turtle-wow.org/?item=60307

**Expected behavior. Describe how it should work:** It should grant 1% chance to dodge attacks instead of grating just 0.43%

**Comment by twowTurtReynolds** [comment]
BetterCharacrerStats is not a source of truth. Please contact the dev of that addon, and do not ever report addon issues here further.

**Comment by xDeltaMirage** [comment]
So how can I check if your item is working properly?

**Comment by cyaohiri** [comment]
> So how can I check if the item is working properly?

You can use a damage meter with the target dummy, but you'll need to record it for a while to get an accurate measurement.

**Comment by twowTurtReynolds** [comment]
> So how can I check if the item is working properly?

Dodge is in your spellbook. For the record, I tested the hat, and it added a full 1.00% dodge.

**Comment by xDeltaMirage** [comment]
Much more clear now, thank you!

**Comment by cyaohiri** [comment]
Somehow I misread it as critical strike chance, hence my comment!
