### ISSUE TITLE
The name of Ivory Hawkstriders is spelled wrongly

### ISSUE THREAD

**Issue by octav3k** [slowtorta/turtlewow-bug-tracker#5655]
**Please, provide a clear description what the bug is:**
The name of Ivory Hawkstriders is missing a letter (r)

**Steps to reproduce the behavior with as much detail as possible:**
1. Read the name

**IDs of affected creatures, items, quests or spells with a link to the relevant page:**
NPC: https://database.turtle-wow.org/?npc=61695

**Expected behavior. Describe how it should work:**
Their name should be Ivory Hawkstrider

**Comment by Muigin** [comment]
Should have been fixed in a January 29th update, but we will try again with a fix I just pushed again now.
