### ISSUE TITLE
Blackstone ground texture

### ISSUE THREAD

**Issue by Plainbear** [slowtorta/turtlewow-bug-tracker#5656]
The ground texture in this spot allow you to walk inside of it
There is no collision.
![Screenshot_501](https://github.com/slowtorta/turtlewow-bug-tracker/assets/85187670/be0edc94-8283-4b0a-ba83-1f0a81f8bc9a)

**Comment by Plainbear** [comment]
![Uploading Screenshot_502.png…]()

**Comment by Plainbear** [comment]
![Uploading Screenshot_503.png…]()

**Comment by twowTurtReynolds** [comment]
Please test again with a freshly downloaded copy of the client.
