### ISSUE TITLE
[She Sells Sea Shells] sea shells not clickable

### ISSUE THREAD

**Issue by Plainbear** [slowtorta/turtlewow-bug-tracker#5659]
The sea shells on the beach next to the Sea shell quest giver are not clickable, and thus the only way to get Sea Shells is via the Shell Collectors

Item: https://database.turtle-wow.org/?item=41058
Quest: https://database.turtle-wow.org/?quest=41176
Object: https://database.turtle-wow.org/?object=2020069

**Expected behavior. Describe how it should work:**'
The sea shells should be clickable and gatherable as the quest describe
![Screenshot_504](https://github.com/slowtorta/turtlewow-bug-tracker/assets/85187670/f845a0bc-528e-4cb9-b780-811502002e6a)

**Comment by twowTurtReynolds** [comment]
On the PTR before patch, I noticed that they were clickable with no quest at all. Perhaps the data point is reversed?

**Comment by slowtorta** [comment]
Fixed in the next update.
