### ISSUE TITLE
Slow Fall effect from Colossal Parachute doesnt work

### ISSUE THREAD

**Issue by Rangtuk** [slowtorta/turtlewow-bug-tracker#566]
Grabbed a parachute from atop the twin colossals in Feralas, jumped off, popped the chute near the ground due to the 10 second duration. I floated the full 10 seconds and was barely above the ground when it ran out, upon landing I died. My best guess is my fall damage got stored before I popped the chute so when I actually landed I still got hit with it (instead of fall damage resetting upon getting slow fall effect)

**Comment by mikefirefly** [comment]
I can confirm this. Something feels fishy - my parachute slowfall ended several feet above the ground and I still took ~250 damage. This doesn't feel right - please look into it.

For now, sadly Noggenfogger > Parachute Cloak.

**Comment by redmagejoe** [comment]
Update: This effect applies to ALL Slowfall states, and not just the parachute. Proper behavior is for fall height to reset and start calculating from the moment the Slowfall effect wears off, but instead it stores your initial height and calculates the difference when you hit the ground regardless of any states you had up to that point.

**Comment by slowtorta** [comment]
Duplicate: https://github.com/slowtorta/turtlewow-bug-tracker/issues/1589
