### ISSUE TITLE
Naturalist II skintone not working for female night elves.

### ISSUE THREAD

**Issue by Nazzgorn** [slowtorta/turtlewow-bug-tracker#5660]
**Please, provide a clear description what the bug is:**
I logged in to my character with the naturalist II skin active, now she has one of the new skintones added which is available in the character creator.
![f6a553a4b01fa79282b9f4359ce8ca75](https://github.com/slowtorta/turtlewow-bug-tracker/assets/154412281/af0bcd54-673d-4a97-92cb-ed2b715aa454)

**Steps to reproduce the behavior with as much detail as possible:**

1. Buy the naturalist skin token from the donation store.
2. Right click on the token received.
3. Become a blue elf instead of a green elf.

**IDs of affected creatures, items, quests or spells with a link to the relevant page:**

https://database.turtle-wow.org/?item=83099

**Expected behavior. Describe how it should work:**
I should look like a plant elf, not an oversized smurf.

**Comment by twowTurtReynolds** [comment]
With the patch, many skins were swapped on accident. The fix rolled out today, please let us know if any issues persist.

**Comment by Nazzgorn** [comment]
The issue has been fixed, thanks a lot!
