### ISSUE TITLE
Quel'Thalas Zone Exists

### ISSUE THREAD

**Issue by MariaKilsved** [slowtorta/turtlewow-bug-tracker#5662]
**Please, provide a clear description what the bug is:**
The Quel'Thalas zone exists north of Tirisfal Glades/Western Plaguelands.

**Steps to reproduce the behavior with as much detail as possible:**

1. Start to swim (or ride a turtle) from the Tirisfal Glades coast toward the new Thalassian Highlands zone.
2. Pretty soon you will notice how the active zone channel changes, switching between The Great Sea and Quel'Thalas,

**IDs of affected creatures, items, quests or spells with a link to the relevant page:**
None

**Expected behavior. Describe how it should work:**
The zone Quel'Thalas should not exist. You should be in some other zone, such as The Great Sea or Western Plaguelands (depending on your position).

**Comment by twowTurtReynolds** [comment]
This kind of thing is a fine little quirk. In 1.12, you can swim out to where Lapidis isle was and the zone chat would work there.
