### ISSUE TITLE
Alah'thalas Skinning/LW/Enchanting/Engineering trainers broken, likely LoS issues

### ISSUE THREAD

**Issue by User456789321** [slowtorta/turtlewow-bug-tracker#5663]
**Please, provide a clear description what the bug is:**

Created a new toon today after patch
Got to alah'thalas, tried to train skinning/leatherworking. It gives me the accept dialogue box and I click accept, that box closes but the trainer chat panel stays open and it does not purchase the skill. I do have enough money to purchase it, I have not already trained other professions except for first aid.

Relogged and deleted WDB folder, did not resolve.

Got to level 10 as per GM suggestion, tried again, no change.
Relogged and deleted wdb folder again, no change.,
Reloaded console, no change.

**Steps to reproduce the behavior with as much detail as possible:**

1. Go to skinning or leatherworking trainer in alah'thalas and try to purchase the professions 
2. Shandlar Thethis and Daemar Swiftstrike cannot train professions due to this bug

**IDs of affected creatures, items, quests or spells with a link to the relevant page:**

NPC: https://database.turtle-wow.org/?npc=61840
NPC: https://database.turtle-wow.org/?npc=61839
NPC: https://database.turtle-wow.org/?npc=61822
NPC: https://database.turtle-wow.org/?npc=61837

**Expected behavior. Describe how it should work:**

Ought to get skinning and leatherworking as new skills in spellbook after clicking "accept"

**Comment by User456789321** [comment]
Update: I'd forgotten to disable all my addons for a test. This also does not resolve the issue today.

**Comment by User456789321** [comment]
Update: Due to another issue I ended up in Darnassus and was able to get skinning and leatherworking from there at those trainers. Seems to indicate it's an issue with the Alah'Thalas trainer NPC's.

**Comment by User456789321** [comment]
Update: The enchanting trainer has the same issue. The alchemy trainer however, does work.

**Comment by User456789321** [comment]
Another player in Alah'Thalas mentioned that the engineering trainer in Alah'Thalas did not interact with them. They were able to train mining but the engineering trainer was also broken.

**Comment by twowTurtReynolds** [comment]
https://github.com/slowtorta/turtlewow-bug-tracker/issues/6079 @ratkosrb These NPCs too please.

**Comment by ratkosrb** [comment]
61840 and 61822 should be fixed next week.
61839 i already fixed in my previous commit
61837 already works, doesn't have the issue
