### ISSUE TITLE
奥丹姆之门任务

### ISSUE THREAD

**Issue by XIANpengfei** [slowtorta/turtlewow-bug-tracker#5664]
**Please, provide a clear description what the bug is:**

**Steps to reproduce the behavior with as much detail as possible:**

1.奥丹姆之门任务接接到过，当时可能任务日志满了给放弃了。
2. 现在想做这个任务好召唤世界BOSS
3. 服务器：风暴烈酒
4. ID 顺德昌逆德亡
5. 

**IDs of affected creatures, items, quests or spells with a link to the relevant page:**

NPC: https://database.turtle-wow.org/?npc=
Item: https://database.turtle-wow.org/?item=
Quest: https://database.turtle-wow.org/?quest=
Spell: https://database.turtle-wow.org/?spell=
Object: https://database.turtle-wow.org/?object=

**Expected behavior. Describe how it should work:**

**Comment by XIANpengfei** [comment]
可能是当初放弃任务的时候有一个任务物品消失了，导致我现在无法接取这个任务。

**Comment by twowTurtReynolds** [comment]
请用英文提交问题。我们无法通过自动翻译准确地翻译中文提交的错误报告，这使得我们难以理解问题的确切性质。谢谢！

Please submit the issues in English. We're unable to accurately translate bug reports submitted in Chinese through automatic translation, which makes it difficult for us to understand the exact nature of the issue. Thank you!
