### ISSUE TITLE
night elf demonhunter skin BUG

### ISSUE THREAD

**Issue by yuzinirvana** [slowtorta/turtlewow-bug-tracker#5665]
Greeting
There is a bug in the night elf demonhunter skin now. The whole person has turned green and completely different from the original appearance. This only appeared after the 1.171 update. I reported it to the GM in the game and he asked me to go to github to report it. Please pay attention to this question.

![微信截图_20231220185259](https://github.com/slowtorta/turtlewow-bug-tracker/assets/153178914/6e42e443-7e5f-46e7-b236-4c09cfead9ae)

**Comment by twowTurtReynolds** [comment]
With the patch, many skins were swapped on accident. The fix rolled out today, please let us know if any issues persist.
