### ISSUE TITLE
Vampirism not showing healing done for melee or spell damage done

### ISSUE THREAD

**Issue by hotcoffeeonpants** [slowtorta/turtlewow-bug-tracker#5667]
I was using items from the Gilneas City dungeon along with the 1% vampirism wrist enchant for a total of 5% healing per dmg done. No healing is shown in the combat log, character icon, or floating combat text from the character (when enabled).   I also downloaded an addon to see if the addon could track healing done and it does not detect the healing done either.  I do about 200-300 dmg per 2 seconds so I. Should see 10hp to 15hp show up as healing done but this is not the case. 

Also, in a totally unrelated request.  Can the shaman spell "spirit link" be altered to do physical damage instead of spell damage?  It would allow shamans to use stoneskin totem to reduce damage instead of using healing stream totem to heal the displaced damage.  The shaman would then be able to use the water totem for other things like mana spring or poison/disease cleanse.

**Comment by cyaohiri** [comment]
It's not shown in the combat log for performance reasons.

**Comment by cyaohiri** [comment]
Yes, checking your HP change is reliable.

**Comment by twowTurtReynolds** [comment]
Indeed, the default UI can show you your exact HP values.

Vampirism works fine.

**Comment by hotcoffeeonpants** [comment]
I did further tested and the math isn't adding up...

No matter the dmg done regardless of crit or regular white hit it only shows up as 5 hp.

For a hit of 71 dmg = 5hp
For a crit of 161 dmg = 5hp...

Further investigation is requested.
