### ISSUE TITLE
Missing Donation Skin

### ISSUE THREAD

**Issue by Zafir111** [slowtorta/turtlewow-bug-tracker#5669]
Hello team, since the latest patch today, when logged in I doscovered that my Dark Iron dwarf skin is no longer applied to my character.
WDB file was cleared, but still no luck. You can see below attached screenshot of the character without the skin, sadly I do not have any older SS prior to the patch and the issue.

![image](https://github.com/slowtorta/turtlewow-bug-tracker/assets/154456476/b21e9d4b-1d91-4a43-91de-df36b38b0d00)

**Comment by twowTurtReynolds** [comment]
The skin mismatch issues will be addressed soon, sorry for the interruption.

**Comment by twowTurtReynolds** [comment]
With the patch, many skins were swapped on accident. The fix rolled out today, please let us know if any issues persist.

**Comment by Zafir111** [comment]
Hello team, thank you for the update. It appears that my problem still persists, today I have logged in and there is no change to the character's skin. Still the Dark Iron skin is missing. I would alo like to include that I no longer have the item which is usable fo application of the skin (the one with the Blizz icon, which is initially received upon donation). Please advise further if you need more details on my case.
Thank you!

**Comment by twowTurtReynolds** [comment]
![image](https://github.com/slowtorta/turtlewow-bug-tracker/assets/151180101/7943babb-2e3f-4b70-a574-33c793009bdc)
I just added the item myself and the skin does seem to be working.

So, if you can't find the item that applies the skin anymore, please contact a GM who can get that back to you.
