### ISSUE TITLE
1st Hunter quest on Alah'Thalas "Taming the Beast" not completable

### ISSUE THREAD

**Issue by User456789321** [slowtorta/turtlewow-bug-tracker#5673]
**Please, provide a clear description what the bug is:**

I cannot complete the first hunter quest taming the beast.

First had this issue last night in my time zone. I get the quest item taming rod to use on an elder crimson lynx, and the quest objective says elder crimson lynx.

I have tried multiple elder crimson lynx and the taming rod says invalid target.
I have tried every other creature type in the area including going farther back to just a normal Crimson Lynx, no change.
I have tried casting the item from my bag and from action bar, no change.
I've tried both from out of and in combat, no change.
I have tried from range and melee, no change.
Tried from the elder crimson lynx being at max or low health, no change.
Relogging and deleting wdb folder, no change.
Abandoning and retrying quest, no change.
Disabling all addons and retrying steps above, no change.
Yesterday and today, no change.

**Steps to reproduce the behavior with as much detail as possible:**

1. Collect "Taming the Beast" from hunter trainer Damilara Sunsorrow in Alah'Thalas after getting level 10 as a Hunter
2.  Try to use the Taming Rod on an Elder Crimson Lynx as described in the quest and on the item
3.  You will get the "Invalid Target" error

**IDs of affected creatures, items, quests or spells with a link to the relevant page:**

NPC: https://database.turtle-wow.org/?npc=80245
NPC: https://database.turtle-wow.org/?npc=61700
Item: https://database.turtle-wow.org/?item=41064
Quest: https://database.turtle-wow.org/?quest=41177

**Expected behavior. Describe how it should work:**

Casting the Taming Rod in any fashion on an Elder Crimson Lynx should cause it to channel on the Lynx and complete the objective

**Comment by User456789321** [comment]
I was told by GM Nightmare that this is having an issue due to a prequest 6071 "The Hunter's Path" not being completed. This quest is done with NPC Jocaste in Darnassus. Presently there is no quest or indication leading me to that quest as a new Hunter in Alah'Thalas, which is definitely an oversight. I'm going to go there and try to get that prequest done then update here on if it resolves my issue or not.

**Comment by User456789321** [comment]
I walked to both Jocaste in Darnassus and Dazalar in Dolanaar as they are both listed as related NPC's in "The Hunter's Path". Even after abandoning "Taming the Beast" neither of them have a quest to offer me. Seems at this point the hunter questline for HE hunters is broken outright.

**Comment by User456789321** [comment]
A GM teleported me to coldridge valley and got "The Hunter's Path" questline for me from there. I completed the dwarven questline instead.

**Comment by User456789321** [comment]
Additionally, after completing the entire questline for the dwarves, receiving all my pet abilities, and returning to Alah'Thalas, the "Taming The Beast" quest is still available from Damilara Sunsorrow. Accepting it and trying to use the rod on the Elder Crimson Lynx again yields the same Invalid Target error.

**Comment by User456789321** [comment]
I would also like to note that there does not appear to be a pet trainer at Alah'Thalas at all.

**Comment by twowTurtReynolds** [comment]
Fixed next restart, should be soon!
