### ISSUE TITLE
Guild Bug

### ISSUE THREAD

**Issue by Fjallbrynt** [slowtorta/turtlewow-bug-tracker#5675]
So there are 2 bugs.
Number 1

Guild members stopped counting after 868 members.

Number 2.
Trying to remove added rank. 
But then i've been demoting everyone at that rank to another rank.
Except one person. He got no name, it says hes a lvl 18 Warlock in Loch Modan.
Cant kick him can't demote/promote him or anything.

![bild_2023-12-20_212946802](https://github.com/slowtorta/turtlewow-bug-tracker/assets/154469137/379dc38a-b7f5-4d1b-a865-71a98e98a294)

**Comment by twowTurtReynolds** [comment]
We haven't heard of any others with this issue since. Please contact support to remove this character from your guild.
