### ISSUE TITLE
Greatfather Winter not working, atleast for me. 

### ISSUE THREAD

**Issue by spndxx** [slowtorta/turtlewow-bug-tracker#5676]
**Please, provide a clear description what the bug is:**

**Steps to reproduce the behavior with as much detail as possible:**

1. Took the quest went to the NPC in Iron Forge and it is not registed as completed.
2
3. 
4. 

**IDs of affected creatures, items, quests or spells with a link to the relevant page:**

NPC: https://database.turtle-wow.org/?npc=61171
Item: https://database.turtle-wow.org/?item=
Quest: https://database.turtle-wow.org/?quest=40783
Spell: https://database.turtle-wow.org/?spell=
Object: https://database.turtle-wow.org/?object=

**Expected behavior. Describe how it should work:**
It should register it as completed the same way as the other two NPC involed in the quest.

https://database.turtle-wow.org/?npc=61168 -Great Spirit of Winter
https://database.turtle-wow.org/?npc=61173 -Great-father Winter

In addition the NPC is standing on chair but not really it is in the air. Should be moved a bit. 

#################################################################################
1. The same NPC should give a repeatable quest but it is not working in Iron Forge.
2. However it is repeatable in Ogrimar.
3. I dont know the exact name of the quest but you have to give cookies and milk to santa in exchange for a gift. 
4. Please fix it as soon as possible as the event will last only a few days or compensate the alliance.

**Comment by twowTurtReynolds** [comment]
![image](https://github.com/slowtorta/turtlewow-bug-tracker/assets/151180101/09eef30f-f6f7-44bb-a2ff-9b53df2b11fb)

The 13444 NPC is the greatfather winter of Ironforge.

The 61171 NPC is somewhere else, that's your quest target!
