### ISSUE TITLE
Chillwind Horns Quest 4209 drop rate is too low.

### ISSUE THREAD

**Issue by mybrid** [slowtorta/turtlewow-bug-tracker#5678]
Quest "Chillwind Horns" drop rate is too low. Comment on on Wowhead, "Chimeras plentiful around coords 58, 18.  I had to kill 17 to get the 8." I had to kill them for two hours to complete his quest. Got a stack of 23 chimera leather. I'm guessing I killed at least 50.

**Steps to reproduce the behavior with as much detail as possible:**

1. Accept "Chillwind Horns" quest. 
2. The drop rate is really low. 
3. 

**IDs of affected creatures, items, quests or spells with a link to the relevant page:**

NPC: https://database.turtle-wow.org/?npc=
Item: https://database.turtle-wow.org/?item=
Quest: https://database.turtle-wow.org/?quest=4809
Spell: https://database.turtle-wow.org/?spell=
Object: https://database.turtle-wow.org/?object=

**Expected behavior. Describe how it should work:**

 had to kill 17 to get the 8

**Comment by twowTurtReynolds** [comment]
Please don't cherry pick comments!

This is pretty well known to be a slog of a quest, blizzlike.

![image](https://github.com/slowtorta/turtlewow-bug-tracker/assets/151180101/63c3828e-0bd2-4604-8b85-1a69b0dbcd38)

The 20% droprate on all 3 types, actually is _better_ than the crowdsourced wowhead data!

Working as intended.
