### ISSUE TITLE
intact elemental bracers 100% droprate

### ISSUE THREAD

**Issue by geojak** [slowtorta/turtlewow-bug-tracker#568]
**Please, provide a clear description what the bug is:**
 for the alliance ashenvale qeust elemental bracers players need to collect 5 intact elemental bracers. these appear to have 100% or near 100% dropchance which is too high and not blizzlike and makes the quest far too easy. i mean i just killed 5 and finished the quests instaed of the many in classic always hoping the next one will drop one, which is kinda more rewarding?

**Steps to reproduce the behavior with as much detail as possible:**

1. get elemental bracer quest
2.  kill 5 elemtals
3. lot an intact bracer each time

**IDs of affected creatures, items, quests or spells with a link to the relevant page:**

NPC: https://database.turtle-wow.org/?npc=
Item: https://database.turtle-wow.org/?item=
Quest: https://database.turtle-wow.org/?quest=
Spell: https://database.turtle-wow.org/?spell=
Object: https://database.turtle-wow.org/?object=

**Expected behavior. Describe how it should work:**

lower dropchance

**Comment by Neto-WoW** [comment]
Its at 80% which is intended. See here:
https://classicdb.ch/?item=12220
