### ISSUE TITLE
Night Elf Naturalist Skins Broken After Patch

### ISSUE THREAD

**Issue by Vikarec** [slowtorta/turtlewow-bug-tracker#5680]
**Please, provide a clear description what the bug is:**

The three night elf skins: Naturalist I, II, & III, are all broken after the most recent patch. They transform you into something completely wrong now.

**Steps to reproduce the behavior with as much detail as possible:**

1. Use the naturalist token to change your skin.
2. Look and compare to what they're supposed to look like.
3. Despair.

**IDs of affected creatures, items, quests or spells with a link to the relevant page:**

Item: Here's the three skin tokens.
https://database.turtle-wow.org/?item=83092
https://database.turtle-wow.org/?item=83099
https://database.turtle-wow.org/?item=83100

**Expected behavior. Describe how it should work:**

I expect that the dev team has internal screenshots of how each skin is supposed to look. But one is supposed to just give you vines around both arms. The other is supposed to make your character green on top of that. And the third is supposed to make your character dark green & orange hued with markings as well as vines. Right now the skins turn you into some fucked up demon with a hideous face.

**Comment by twowTurtReynolds** [comment]
With the patch, many skins were swapped on accident. The fix rolled out today, please let us know if any issues persist.
