### ISSUE TITLE
Set bonus now showing

### ISSUE THREAD

**Issue by Borelioza** [slowtorta/turtlewow-bug-tracker#5681]
**Please, provide a clear description what the bug is:**

**Steps to reproduce the behavior with as much detail as possible:**

1.Creating Transmog out of items: "Legplates of Ten Storms","Epaulets of Ten Storms","Earthfury Gauntlets"
2. Set Bonuses are not showing up on bonus list like it was not a set items after transmog

IDs of affected creatures, items, quests or spells with a link to the relevant page:

[https://database.turtle-wow.org/?item=16945]
[https://database.turtle-wow.org/?item=16946]
[https://database.turtle-wow.org/?item=16839]
[https://database.turtle-wow.org/?item=65021]

It should apply set bonuses and show set bonuses even after changing it's visuals

![obraz](https://github.com/slowtorta/turtlewow-bug-tracker/assets/154475835/7ebe0776-24ad-4c88-84e2-23ac7d25d288)

**Comment by twowTurtReynolds** [comment]
This is a known bug, don't worry, its just a visual glitch, your bonuses do work.
