### ISSUE TITLE
Cant tame my pet in highelf zone as Hunter so i am petless and my name is Fried lvl 11 Hunter highelf

### ISSUE THREAD

**Issue by crixxerhb** [slowtorta/turtlewow-bug-tracker#5685]
it does not work to use my taming rod on elder crimson lynx in highelf zone i tried talking to gm he said just relog a few minutes so i did and no results and i re took the quest and didnt work

NPC: https://database.turtle-wow.org/?npc=61700
Item: the item doesnt even have a id on ur database   but its for the elder crimson lynx
Quest: https://database.turtle-wow.org/?quest=6063   for highelfs
Spell: taming beasts quest item diesnt exist in data base 
Object:  to get my pet ... highelf

it should work cause it only says Invalid target

**Comment by twowTurtReynolds** [comment]
Fixed next restart, should be soon!
