### ISSUE TITLE
Odam Gate Mission

### ISSUE THREAD

**Issue by XIANpengfei** [slowtorta/turtlewow-bug-tracker#5686]
**Please, provide a clear description what the bug is:**

**Steps to reproduce the behavior with as much detail as possible:**

1.I gave up on the Odam Gate mission before and now I want to retake it, but I won't accept it.
2. I hope to receive the mission of the Odam Gate again。thank you.
3. 

**IDs of affected creatures, items, quests or spells with a link to the relevant page:**

NPC: https://database.turtle-wow.org/?npc=
Item: https://database.turtle-wow.org/?item=
Quest: https://database.turtle-wow.org/?quest=
Spell: https://database.turtle-wow.org/?spell=
Object: https://database.turtle-wow.org/?object=

**Expected behavior. Describe how it should work:**

**Comment by twowTurtReynolds** [comment]
We gave you a template, please fill it out. I cannot find this Odam Gate quest.
