### ISSUE TITLE
formal Purple Waistcoat

### ISSUE THREAD

**Issue by xevra** [slowtorta/turtlewow-bug-tracker#5689]
**formal Purple Waistcoat is misspelled**

**Steps to reproduce the behavior with as much detail as possible:**

1. Go to Undercity vendor Valentino Westwood in the Apothecarium
2. Scroll to page 5 of his store
3. Read the name of the formal purple waistcoat.

**IDs of affected creatures, items, quests or spells with a link to the relevant page:**

Item: https://database.turtle-wow.org/?item=41252

**All of the other "Formal Purple" items sold at this vendor start with a capitol letter. formal Purple Waistcoat starts with a lowercase f*

**Comment by Dragunovi** [comment]
Should be fixed in the next scheduled server restart.
