### ISSUE TITLE
Temporal Anomaly (New Shard of Eternity) Bugged

### ISSUE THREAD

**Issue by Scrybatog** [slowtorta/turtlewow-bug-tracker#5691]
**Please, provide a clear description what the bug is:**
Even after deleting WDB folder the new shard of eternity is bugged and has no icon.
**Steps to reproduce the behavior with as much detail as possible:**

1. Have Temporal Anomaly in game
2. Look at it
3. See it doesnt have icon

**IDs of affected creatures, items, quests or spells with a link to the relevant page:**

NPC: https://database.turtle-wow.org/?npc=
Item: https://database.turtle-wow.org/?item=61014
Quest: https://database.turtle-wow.org/?quest=
Spell: https://database.turtle-wow.org/?spell=
Object: https://database.turtle-wow.org/?object=

**Expected behavior. Describe how it should work:**
It should have an icon

**Comment by twowTurtReynolds** [comment]
Updated your DB link.
![image](https://github.com/slowtorta/turtlewow-bug-tracker/assets/151180101/2b05ff1e-6bc9-44a2-b326-44e00e3bf029)

**Comment by Dragunovi** [comment]
Should be fixed in the next scheduled server restart.
