### ISSUE TITLE
Plans: Blast Shield crashes the game when you try to learn it

### ISSUE THREAD

**Issue by Bombg** [slowtorta/turtlewow-bug-tracker#5694]
**Please, provide a clear description what the bug is:**
Just bought Plans: Blast Shield from the AH and the game crashed when I tried to learn it. I reloaded the game and it crashed again when I tried to learn the pattern again. The blacksmithing plan also seems to lack a tool tip that actually shows what the item it can make is. My blacksmithing skill is 300.

**Steps to reproduce the behavior with as much detail as possible:**

1. Be a blacksmith - presumably at 75 skill or higher
2. Get plans: Blast Shield
3. Attempt to learn the plans, and the game will crash.

**IDs of affected creatures, items, quests or spells with a link to the relevant page:**

NPC: https://database.turtle-wow.org/?npc=
Item: https://database.turtle-wow.org/?item=51265
Quest: https://database.turtle-wow.org/?quest=
Spell: https://database.turtle-wow.org/?spell=
Object: https://database.turtle-wow.org/?object=

**Expected behavior. Describe how it should work:**
When I attempt to right click and learn the plans, I should have the pattern show up in my blacksmithing recipe list.

**Comment by twowTurtReynolds** [comment]
![image](https://github.com/slowtorta/turtlewow-bug-tracker/assets/151180101/ab997838-7cd8-4ae1-acc9-c1189c722452)
![image](https://github.com/slowtorta/turtlewow-bug-tracker/assets/151180101/994f4c94-f6c4-454a-bea4-6daa59057115)
![image](https://github.com/slowtorta/turtlewow-bug-tracker/assets/151180101/a7521ee0-abc5-4bb0-abd0-a231303c0bc1)

Perhaps you had a mod that has destabilized your TWoW installation?
