### ISSUE TITLE
Signet of Themar wrong icon

### ISSUE THREAD

**Issue by MariaKilsved** [slowtorta/turtlewow-bug-tracker#5695]
**Please, provide a clear description what the bug is:**
The item Signet of Themar should be a ring, but has the icon of a robe.

**Steps to reproduce the behavior with as much detail as possible:**

1. Check out the item reward for the quest The House of Theron.
2. This item, Signet of Themar, is a ring with the icon of a robe.

**IDs of affected creatures, items, quests or spells with a link to the relevant page:**
Item: https://database.turtle-wow.org/?item=41185

**Expected behavior. Describe how it should work:**
It should have the icon of a ring, preferably something that looks like a signet ring.

**Comment by twowTurtReynolds** [comment]
![image](https://github.com/slowtorta/turtlewow-bug-tracker/assets/151180101/d8cb95d5-5f49-4041-9ea5-cb73e5c562cc)

**Comment by Dragunovi** [comment]
Should be fixed with the next scheduled restart.
