### ISSUE TITLE
NPC Daemar Swiftstrike does not properly teach Skinning

### ISSUE THREAD

**Issue by Justiino199** [slowtorta/turtlewow-bug-tracker#5697]
**Please, provide a clear description what the bug is:**
The Skinning Trainer Daemar Swiftstrike does not teach Skinning when you try and learn the skill.

**Steps to reproduce the behavior with as much detail as possible:**

1. Skinner in Alah'Thalas currently does not allow you to learn the skinning profession.
2. NPC is Daemar Swiftstrike
3. 

**IDs of affected creatures, items, quests or spells with a link to the relevant page:**

NPC: https://database.turtle-wow.org/?npc=61839

**Expected behavior. Describe how it should work:**
I should be able to learn the profession Skinning.

**Comment by twowTurtReynolds** [comment]
It seems maybe their sitting pose inside the object is causing LoS issues?

**Comment by Justiino199** [comment]
> It seems maybe their sitting pose inside the object is causing LoS issues?

That could be it. It is also the same issue with the LW trainer right beside him. Both of them are sitting.

**Comment by twowTurtReynolds** [comment]
Will be tracking under https://github.com/slowtorta/turtlewow-bug-tracker/issues/5663
