### ISSUE TITLE
character model issue [?]

### ISSUE THREAD

**Issue by eruth9** [slowtorta/turtlewow-bug-tracker#5699]
Hello! im not well versed in bugs so im sorry for the lack of knowledge i can only describe my experience. Since the new update my character (male high elf) seems to have changed hair color, not only that but the size of my mounts seems to have increased slightly, the shoulders also seem to be a little diferent.

thanks in advance!

**Comment by twowTurtReynolds** [comment]
I'm not sure about the hair color change. You are the only person to have reported this, and I think it is possible that you are mistaken? If you can go to the character creation screen, can you see if the hair color you want is in the list? If so, then go to your faction's barbershop and buy and use the hair dye to match.

High elves' did end up mounting lower than before which does make mounts look bigger in perspective. This has been fixed internally and should arrive with 1.17.2

As for the shoulders, we have no idea what you mean, we see no difference.
