### ISSUE TITLE
Ancient Quel'Dorei Steed sound effect

### ISSUE THREAD

**Issue by Vikkyne** [slowtorta/turtlewow-bug-tracker#57]
By opening this Issue, I admit to having done the pertinent research using sources from Vanilla (preferably) or Classic. I also understand that sources from other private servers are not acceptable.

**Current behavior**: 
When player attempts to mount the Quel'Dorei Steed, it sounds off a big cat snarl.

**Expected behavior**: 
A horsie sound?!? lol

**Proofs**:
So, not having seen this is any other version of Vanilla/Classic, the only proof is it was introduced in patch 3.2 and the Wowhead site doesn't list a sound effect with the mounting spell.

**Steps to reproduce**:

1.  Try to mount a Quel'Dorei Steed....
2. 
3.

**Comment by slowtorta** [comment]
This is a client-side issue and will be fixed in Patch 1.15.2.

**Comment by Vikkyne** [comment]
Thanks. I also suspect this is what is causing the same roar sound when the Barrens Zhevra is used (same basic model I guess)

**Comment by Vikkyne** [comment]
Wait, it's not confirmed?  -->  "_slowtorta removed the Confirmed label on Aug 2_"

**Comment by slowtorta** [comment]
It'll be fixed in 1.15.2
