### ISSUE TITLE
bugged chest in  Brakwell Pumpkin Patch

### ISSUE THREAD

**Issue by Gabbq** [slowtorta/turtlewow-bug-tracker#5703]
**Please, provide a clear description what the bug is:**
There is a chest that isnt openable in elwynn,  coords 71.4 76.6, when you try to open it it tells you "target not in lane of sight"
**Steps to reproduce the behavior with as much detail as possible:**

1. reach Brakwell Pumpkin Patch, enter the big house with a defias bandit inside 
2.  kill the defias bandit
3.  try to open the chest

**IDs of affected creatures, items, quests or spells with a link to the relevant page:**

NPC: https://database.turtle-wow.org/?npc=116
Item: https://database.turtle-wow.org/?item=
Quest: https://database.turtle-wow.org/?quest=
Spell: https://database.turtle-wow.org/?spell=
Object: https://database.turtle-wow.org/?object=106318

**Expected behavior. Describe how it should work:** 
 when i click on the chest my character should begin the process for opening it, it should open and show me the loot
<img width="1920" alt="Desktop Screenshot 2023 12 21 - 17 17 42 95" src="https://github.com/slowtorta/turtlewow-bug-tracker/assets/50996801/48649f84-e080-4bda-a093-596c29ffde60">
<img width="1920" alt="Desktop Screenshot 2023 12 21 - 17 17 56 88" src="https://github.com/slowtorta/turtlewow-bug-tracker/assets/50996801/08463f0e-c618-462b-9407-f2c234f12a11">

**Comment by twowTurtReynolds** [comment]
![image](https://github.com/slowtorta/turtlewow-bug-tracker/assets/151180101/19eb8107-08a4-432e-b0d5-9dda7b1a0994)
