### ISSUE TITLE
Thornpod No Ability

### ISSUE THREAD

**Issue by afizzler** [slowtorta/turtlewow-bug-tracker#5705]
Thornpod should retain an ability of some sorts. 

Here it is as of now:

![image](https://github.com/slowtorta/turtlewow-bug-tracker/assets/87098931/f94bd424-523c-47a4-b398-ac83db17fdfa)

https://database.turtle-wow.org/?item=62008

**Comment by Dragunovi** [comment]
The database has not been yet updated with custom spell effects. Thornpod's ability was replaced with a mostly identical custom version with a smaller radius and smaller spellpower scaling, I can assure you that the on use effect is there in-game.
