### ISSUE TITLE
Certain Flight Paths completely break, creating a temporary mount until relogging

### ISSUE THREAD

**Issue by JTayGang** [slowtorta/turtlewow-bug-tracker#5707]
**Please, provide a clear description what the bug is:**

https://www.youtube.com/watch?v=XqGFss-BqXU

You can steal the flight path hippogyphs as a temporary mount, even while under level 40.
OTHER PLAYERS CAN SEE THE MOUNT. YOU CAN TAKE IT WHERE MOUNTS ARENT ALLOWED. I thought it was funny.
The patch on 12/20/2021 fixed this specific flight path, but it may be worth checking them all. Relogging removes the mount, and you cannot get off of it.

**Steps to reproduce the behavior with as much detail as possible:**
1. Take a flight path with at least one step between start and destination
2. Some flight paths fail to connect, dropping the hippogryph to the ground with player mounted
3. Relogging continues the flight path

**IDs of affected creatures, items, quests or spells with a link to the relevant page:**
Flight paths, and the hippogryph mountss

**Expected behavior. Describe how it should work:**
The flight paths should finish as normal.

**Comment by twowTurtReynolds** [comment]
This was a known bug that only affected Bael and Astranaar: https://github.com/slowtorta/turtlewow-bug-tracker/issues/4619

We'll be checking any new flight path for this bug going forward, do not worry.

All current flight paths should be good in this regard.
