### ISSUE TITLE
Cant equip 36 slot bag

### ISSUE THREAD

**Issue by Mingg1921** [slowtorta/turtlewow-bug-tracker#5708]
**Please, provide a clear description what the bug is:**
I cant equipe the purchased 36 slot bag, it shows I can not do that right now. I have cleared WDB folder, and some GM helped to return the token and I purchased the bag again, still cant work
**Steps to reproduce the behavior with as much detail as possible:**

1.Can not equip the purchased bag, Portable Pocket Dimension
2. 
3. 

**IDs of affected creatures, items, quests or spells with a link to the relevant page:**

NPC: https://database.turtle-wow.org/?npc=
Item: https://database.turtle-wow.org/?item=
Quest: https://database.turtle-wow.org/?quest=
Spell: https://database.turtle-wow.org/?spell=
Object: https://database.turtle-wow.org/?object=

**Expected behavior. Describe how it should work:**

**Comment by twowTurtReynolds** [comment]
Bags in the 1.12 client are tough to equip!

You need to empty out the old bag, then unequip it, then you can drag in a new bag.

**Comment by Mingg1921** [comment]
Hello, not to replace the existing one, but to equip. I am level 7, that is the only bag i have.

**Comment by twowTurtReynolds** [comment]
I was unable to reproduce the problem myself, this bag works fine.

It is likely that your character is in a strange occupied state, like if you were stuck looting something. Please work with a GM on this issue.
