### ISSUE TITLE
Snowball

### ISSUE THREAD

**Issue by saintpier** [slowtorta/turtlewow-bug-tracker#5709]
**Please, provide a clear description what the bug is:**
I've been in a raid to kill snowball, we got disconnected twice before the fight, while in fight I died and didnt get mention of snowball death. I didnt release during the fight and still didnt get the mention that he was death in my quest log. So I couldnt get the 20slot bag.

**Steps to reproduce the behavior with as much detail as possible:**

1.
2. 
3. 

**IDs of affected creatures, items, quests or spells with a link to the relevant page:**

NPC: https://database.turtle-wow.org/?npc=
Item: https://database.turtle-wow.org/?item=
Quest: https://database.turtle-wow.org/?quest=
Spell: https://database.turtle-wow.org/?spell=
Object: https://database.turtle-wow.org/?object=

**Expected behavior. Describe how it should work:**

I should get the quest done even if i'm dead. If you can send the bag by mail would be really appreciated.

Thanks!

![WoWScrnShot_122123_183216](https://github.com/slowtorta/turtlewow-bug-tracker/assets/154566182/7581ba29-463d-4fd4-9c1b-f7156f8e8e38)

**Comment by twowTurtReynolds** [comment]
![image](https://github.com/slowtorta/turtlewow-bug-tracker/assets/151180101/80f0f0d9-b082-4a33-b689-d3f0540a81df)

I am unable to replicate on the PTR

If you can figure out how exactly this issue can be replicated, please do let us know.

**Comment by saintpier** [comment]
I dont know how it can be replicated, what i am saying is that i had to wait 2hrs for respawn, and didnt get my bag when he died. Dont know if massive DC that day had link to the event, but its not fun, I need to find another group again for it
________________________________
De : Turt Reynolds ***@***.***>
Envoyé : Thursday, December 21, 2023 9:10:36 PM
À : slowtorta/turtlewow-bug-tracker ***@***.***>
Cc : saintpier ***@***.***>; Author ***@***.***>
Objet : Re: [slowtorta/turtlewow-bug-tracker] Snowball (Issue #5709)


image.png (view on web)<https://github.com/slowtorta/turtlewow-bug-tracker/assets/151180101/80f0f0d9-b082-4a33-b689-d3f0540a81df>

I am unable to replicate on the PTR

If you can figure out how exactly this issue can be replicated, please do let us know.
