### ISSUE TITLE
entrance guard

### ISSUE THREAD

**Issue by XIANpengfei** [slowtorta/turtlewow-bug-tracker#5710]
**Please, provide a clear description what the bug is:**

**Steps to reproduce the behavior with as much detail as possible:**

1.《entrance guard》 The task prior to this task
2. That task is Looking for [the second ordam slate]
3. Cannot reconnect after abandonment

**IDs of affected creatures, items, quests or spells with a link to the relevant page:**

NPC: https://database.turtle-wow.org/?npc=
Item: https://database.turtle-wow.org/?item=
Quest: https://database.turtle-wow.org/?quest=
Spell: https://database.turtle-wow.org/?spell=
Object: https://database.turtle-wow.org/?object=

**Expected behavior. Describe how it should work:**

**Comment by twowTurtReynolds** [comment]
I cannot find any quest under that name.

We gave you a template, including you linking us the quest, so please fill it out.

**Comment by XIANpengfei** [comment]
![Uploading 图片20231222102227.jpg…]()

**Comment by XIANpengfei** [comment]
![Uploading 图片20231222102227.jpg…]()
