### ISSUE TITLE
Tel'abim | LOS issues prevent looting chest in Elwynn @ 71,61 in barn

### ISSUE THREAD

**Issue by Slimthegrim** [slowtorta/turtlewow-bug-tracker#5712]
**Please, provide a clear description what the bug is:**
Tel'abim server has an LOS issue prevent looting chest in Elwynn @ 71,61 in building.

![image](https://github.com/slowtorta/turtlewow-bug-tracker/assets/110629519/9ed92ff9-6036-4c3f-9d60-956308fdbabb)

![image](https://github.com/slowtorta/turtlewow-bug-tracker/assets/110629519/74f71e24-8f04-445f-9f6d-43d20081cfe1)

**Steps to reproduce the behavior with as much detail as possible:**

1. Goto Elwynn Forest, head to barn 71,61.
2. Try to interact with chest like as seen above.
3. Notice it's unlootable.

**IDs of affected creatures, items, quests or spells with a link to the relevant page:**

Battered chest at 71,61 Elwynn. 

**Expected behavior. Describe how it should work:**
ALL chests should give the bestest goblin of the all named $elim the $ultan on Telabim LOTS of gold!!

**Comment by cyaohiri** [comment]
Is it the same location as #5703? Your coordinates seem off.

**Comment by Slimthegrim** [comment]
Think you're right, I noted down wrong coords, will close as dupe.
