### ISSUE TITLE
Flying wyvern keeps disappearing after each patch

### ISSUE THREAD

**Issue by Avery1337** [slowtorta/turtlewow-bug-tracker#5713]
**Please, provide a clear description what the bug is:**
Our Macrochelys guild base has a wyvern in it that helps us get out of our guild base.  This wyvern is gone after every patch and I would like a more permanent fix to this bug.  Our guildbase is located in Azshara within The Forlorn Ridge crater. Bristlefur is a Wyvern that does the same thing as our wyvern in the guild base.  However our wyvern does not require a mutton chop to ride.  

**Expected behavior. Describe how it should work:**
Our wyvern should stay in the guild base once a patch releases so we can easily get out of our guild base.

**Comment by slowtorta** [comment]
This is a GM issue, please reach out to RP GM Gheor.
