### ISSUE TITLE
Pattern: Lynxstep Boots

### ISSUE THREAD

**Issue by Soph3X** [slowtorta/turtlewow-bug-tracker#5714]
**Please, provide a clear description what the bug is:**
When trying to use the Pattern to learn get hit with game crash error 
**Steps to reproduce the behavior with as much detail as possible:**
![image](https://github.com/slowtorta/turtlewow-bug-tracker/assets/154081619/63099e06-639d-4845-82d5-268ce1722d48)

1.Trying to learn new pattern. Item ID is 51285
2. 
3. 

**IDs of affected creatures, items, quests or spells with a link to the relevant page:**

NPC: https://database.turtle-wow.org/?npc=
Item: https://database.turtle-wow.org/?item=
Quest: https://database.turtle-wow.org/?quest=
Spell: https://database.turtle-wow.org/?spell=
Object: https://database.turtle-wow.org/?object=

**Expected behavior. Describe how it should work:**

**Comment by twowTurtReynolds** [comment]
![image](https://github.com/slowtorta/turtlewow-bug-tracker/assets/151180101/52f1cbb3-549d-4ce1-86ed-3592598df21a)
No crashes here. You might have an addon or mod issue.
