### ISSUE TITLE
Markhoppus Face Bug

### ISSUE THREAD

**Issue by Selstag** [slowtorta/turtlewow-bug-tracker#5716]
Hello, my character on the PVE server, Markhoppus, has had his appearance changed by the update. He used to have the new white-and-black skull facepaint with the blue eyes, that has since been removed and he has a basic Troll face.  I wrote a ticket in game and the GM told me to make a bug report here, I'd just like my character's face back as I'm probably going to quit playing him otherwise.

1. Updated the game
2. 
3.

**Comment by jameyboor** [comment]
Hey,

I will close this issue as this seems to be a one-off incident and not a reoccurring bug. You will be getting an appearance change for free to change this for your character.

**Comment by Herdon** [comment]
Delete your WDB folder
