### ISSUE TITLE
Spectral Wine Turn-in not working

### ISSUE THREAD

**Issue by FaceDownDagon** [slowtorta/turtlewow-bug-tracker#5720]
**Please, provide a clear description what the bug is:**
The turn-in for the quest Spectral Wine is not allowing me to complete the quest, despite having the proper items.
![image](https://github.com/slowtorta/turtlewow-bug-tracker/assets/115439761/9f850300-caa8-457d-b8d6-2d101f259d0e)

**Steps to reproduce the behavior with as much detail as possible:**

1. Gather the required reagents
2. Put them in a bank
3. Withdraw them from the bank
4. Attempt to turn in the quest

**IDs of affected creatures, items, quests or spells with a link to the relevant page:**

Quest: https://database.turtle-wow.org/?quest=41085

**Comment by twowTurtReynolds** [comment]
Please see https://github.com/slowtorta/turtlewow-bug-tracker/issues/6042
