### ISSUE TITLE
Belt  transmog screwing up setbonus

### ISSUE THREAD

**Issue by Killitoris** [slowtorta/turtlewow-bug-tracker#5721]
**Please, provide a clear description what the bug is:**

**Steps to reproduce the behavior with as much detail as possible:**

1. No setbonus displayed  i  believe  because  i have a transmog  on  the belt
2. no  bonus  spellpower from t1  bonus  gotten
3. its  not just  a  visual  bug  i  effectively  dont get the  bonus
4. please  help

**IDs of affected creatures, items, quests or spells with a link to the relevant page:**

NPC: https://database.turtle-wow.org/?npc=
Item: https://database.turtle-wow.org/?item=
Quest: https://database.turtle-wow.org/?quest=
Spell: https://database.turtle-wow.org/?spell=
Object: https://database.turtle-wow.org/?object=

**Expected behavior. Describe how it should work:**

**Comment by twowTurtReynolds** [comment]
This is a known visual bug, it doesn't actually ruin your set bonus.
