### ISSUE TITLE
Suggestion - Totem of the Stonebreaker is Undertuned

### ISSUE THREAD

**Issue by OonaFae** [slowtorta/turtlewow-bug-tracker#5724]
Currently Totem of the Stonebreaker feels fairly weak for the tier of content that it drops from (T2) the proc rate appears to be about 10% 

This means that if you cast shocks on cooldown for 1 minute (assuming 6s CD) you're looking at about a 65% chance to see it proc a single time in that minute.

Even if you do take the Talent and once again are casting shocks on CD (5s) you have just under a 72% chance of seeing it proc in that one minute. 

This does not take into consideration shocks being resisted which is extremely common for Enhancement Shamans especially in the endgame content. During the 10 seconds the buff is active your average DPS will be up by about 7pts. I would advocate for the proc rate being higher to offset the high chance that enhancement shamans have to get their shocks resisted. 

Item: https://database.turtle-wow.org/?item=61204
Spell: https://database.turtle-wow.org/?spell=48100

**Comment by twowTurtReynolds** [comment]
Gameplay balance tuning suggestions belong on the forums.
