### ISSUE TITLE
Clipping on Blackstone Island

### ISSUE THREAD

**Issue by Tyloris** [slowtorta/turtlewow-bug-tracker#5725]
**Please, provide a clear description what the bug is:** The player clips through the landscape, sinking down at different points enough to obscure a goblin player.

**Steps to reproduce the behavior with as much detail as possible:**

1. Go to 40.6, 59.5 on Blackstone Island. Walk around the ground to see the different points.

**Comment by Tyloris** [comment]
![Uploading image_2023-12-22_192258448.png…]()

**Comment by twowTurtReynolds** [comment]
![image](https://github.com/slowtorta/turtlewow-bug-tracker/assets/151180101/63dc69f4-7d83-49cf-a4e2-38e3d395b4fb)
I walked all around this little area and couldnt find the clip.

When you upload images, make sure to actually let them fully upload before posting...
