### ISSUE TITLE
Turtle donation shop Dark Iron skin is now a wildhammer dwarf.

### ISSUE THREAD

**Issue by olaftim** [slowtorta/turtlewow-bug-tracker#573]
**Please, provide a clear description what the bug is:**

Turtle donation shop Dark Iron skin is now a wildhammer dwarf.

**Steps to reproduce the behavior with as much detail as possible:**

1.
2. 
3. 

**IDs of affected creatures, items, quests or spells with a link to the relevant page:**

NPC: https://database.turtle-wow.org/?npc=
Item: https://database.turtle-wow.org/?item=
Quest: https://database.turtle-wow.org/?quest=
Spell: https://database.turtle-wow.org/?spell=
Object: https://database.turtle-wow.org/?object=

**Expected behavior. Describe how it should work:**

**Comment by Tinyfin-github** [comment]
Greetings! The issue has been fixed, please reuse the skin token to apply the correct skin.
