### ISSUE TITLE
Trimming beard as goblin with the green eyes face, turns head invisible

### ISSUE THREAD

**Issue by Pehrakgu** [slowtorta/turtlewow-bug-tracker#5730]
**Please, provide a clear description what the bug is:**
Selecting "I'd like to trim my beard." on a male goblin character makes the head invisible.
![image](https://github.com/slowtorta/turtlewow-bug-tracker/assets/154680871/a6e83a67-2061-40dc-928b-a988e94ce7db)
This is also visible for other players.
Clearing cache doesn't work.
Selecting different options or hairstyles also doesn't fix it.
This also persists in the character selection screen.

**Steps to reproduce the behavior with as much detail as possible:**

1. Create a new male goblin character with the face setting that has the green eyes
2. Go to Sparkwater Port
3. Talk to [Bebri Coifcurl](https://database.turtle-wow.org/?npc=81034)
4. Select "I'd like to trim my beard."

**IDs of affected creatures, items, quests or spells with a link to the relevant page:**

NPC: https://database.turtle-wow.org/?npc=81034

**Expected behavior. Describe how it should work:**

Your face shouldn't turn invisible.

**Comment by Siachaaton** [comment]
Any updates please? My issue's been closed as a duplicate https://github.com/slowtorta/turtlewow-bug-tracker/issues/6075 , but there's been no progress with this one either...

**Comment by slowtorta** [comment]
This NPC will be removed in the next update. No other races have their own barber availalbe, and we aren't planning on adding one. Whic NPC was added during the earlier days of devleopment when we wanted to provide a qucik fix for those playesr whos model got drastically altered in one of the updates.
