### ISSUE TITLE
The model for Greatblade of Quel'Danil clips through the character's hand (high elf female)

### ISSUE THREAD

**Issue by octav3k** [slowtorta/turtlewow-bug-tracker#5733]
**Please, provide a clear description what the bug is:**
The model for Greatblade of Quel'Danil clips through the character's hand (high elf female). Tested on a high elf female only.

**Steps to reproduce the behavior with as much detail as possible:**
1. Acquire and equip (or just ctrl+click) the Greatblade of Quel'Danil

**IDs of affected creatures, items, quests or spells with a link to the relevant page:**
Item: https://database.turtle-wow.org/?item=51766

**Expected behavior. Describe how it should work:**
The blade should probably be moved forward, so the character's hand grabs the hilt of the weapon, not clips through the handguard.

**Comment by twowTurtReynolds** [comment]
![image](https://github.com/slowtorta/turtlewow-bug-tracker/assets/151180101/7268d4e1-3351-42e2-b2b8-ec5e85277ca2)
Seems okay on goblin
![image](https://github.com/slowtorta/turtlewow-bug-tracker/assets/151180101/20471c41-7127-4f87-bccd-1295ff9d0334)
But yeah doesn't look as good here
![image](https://github.com/slowtorta/turtlewow-bug-tracker/assets/151180101/7e53e972-05d8-4d8c-9e55-16ef43eb48a7)

**Comment by twowTurtReynolds** [comment]
![image](https://github.com/slowtorta/turtlewow-bug-tracker/assets/151180101/133d3ab0-f65a-47ec-a896-c4b26e50a735)
Fixed in 1.17.2
