### ISSUE TITLE
Alliance reputation doesn't include Silvermoon Remnants

### ISSUE THREAD

**Issue by MariaKilsved** [slowtorta/turtlewow-bug-tracker#5735]
**Please, provide a clear description what the bug is:**
When completing a quest that supposedly provides Alliance reputation (e.g. Bride of the Embalmer), no reputation will be provided for Silvermoon Remnants.

**Steps to reproduce the behavior with as much detail as possible:**

1. Note the current reputation level with each of the Alliance factions.
2. It seems likely that the bug will occur for all quests that rewards Alliance reputation. For example, you may complete the quest Bride of the Embalmer which awards Alliance reputation. 
3. On quest completion, watch as the reputation level of all the Alliance factions other than Silvermoon Remnants increases.

**IDs of affected creatures, items, quests or spells with a link to the relevant page:**

Quest: https://database.turtle-wow.org/?quest=253

For a full list of all quests offering Alliance reputation as a reward, see:
https://database.turtle-wow.org/?faction=469

**Expected behavior. Describe how it should work:**
Reputation should be awarded to all sub-factions within the Alliance upon completing any quest that awards Alliance reputation.

**Comment by Zmitrok1984** [comment]
[This is intended behavior, they haven't joined Alliance officially yet.](https://github.com/slowtorta/turtlewow-bug-tracker/issues/980#issuecomment-1035092946)
