### ISSUE TITLE
High Elf Skinning Trainer

### ISSUE THREAD

**Issue by hazlema** [slowtorta/turtlewow-bug-tracker#5739]
**Please, provide a clear description what the bug is:**

Found a bug, I think.  

In the new high elf zone I trained the wrong profession then dropped it.  Went over to the skinning trainer to train, it prompted me if I really wanted to I said Yes.  It wouldn't cast the spell giving me skinning.  

I logged out and tried it again same thing.  
I quit the game and restarted same thing.  

I took the boat to Darnassis to train skinning and it worked.  

**Steps to reproduce the behavior with as much detail as possible:**

1. Train profession
2.  Drop Profession
3.  Go to high elf skinning trainer and train

**IDs of affected creatures, items, quests or spells with a link to the relevant page:**

NPC: https://database.turtle-wow.org/?npc=61839
Item: https://database.turtle-wow.org/?item=
Quest: https://database.turtle-wow.org/?quest=
Spell: https://database.turtle-wow.org/?spell=
Object: https://database.turtle-wow.org/?object=

**Expected behavior. Describe how it should work:**

Should cast the spell to train you

**Comment by twowTurtReynolds** [comment]
Same issue as https://github.com/slowtorta/turtlewow-bug-tracker/issues/5697

**Comment by twowTurtReynolds** [comment]
Will be tracking under https://github.com/slowtorta/turtlewow-bug-tracker/issues/5663
