### ISSUE TITLE
2 alliance Winter Revelers in Feralas belong to horde

### ISSUE THREAD

**Issue by Shellyoung** [slowtorta/turtlewow-bug-tracker#5744]
**Please, provide a clear description what the bug is:**
These two. One of them don't have textures.
![WoW_uLlf8vLf8u](https://github.com/slowtorta/turtlewow-bug-tracker/assets/40469927/9888f2f7-2cd8-4a6c-af07-e449fc5c3047)

Location:
![chrome_HRRg7P75OH](https://github.com/slowtorta/turtlewow-bug-tracker/assets/40469927/9086fdee-a85f-4842-9f31-2223375d6e63)

**IDs of affected creatures, items, quests or spells with a link to the relevant page:**

NPC: https://database.turtle-wow.org/?npc=15760

**Comment by twowTurtReynolds** [comment]
![image](https://github.com/slowtorta/turtlewow-bug-tracker/assets/151180101/296d982c-8e04-4e00-92d0-817d2e35402d)
I'm not sure how you saw this.

**Comment by Shellyoung** [comment]
Their PvP flags are horde

**Comment by twowTurtReynolds** [comment]
On the PTR, they are alliance.

**Comment by Shellyoung** [comment]
I figured it out They have no faction at all, according to UnitFactionGroup("target") function. Luna Unit Frames addon show no faction as horde faction.
