### ISSUE TITLE
Quest Broken Cliff Inspection - wrong rep reward

### ISSUE THREAD

**Issue by Gedodile** [slowtorta/turtlewow-bug-tracker#5745]
As Alliance you get a horde reputation reward for quest "Broken CLiff Inspection" in Stonetalons: 	"Your Durotar Labor Union reputation has increased 100".

**Comment by twowTurtReynolds** [comment]
Duplicate of https://github.com/slowtorta/turtlewow-bug-tracker/issues/5688
