### ISSUE TITLE
Pet dont take world buff after rename

### ISSUE THREAD

**Issue by rez05z** [slowtorta/turtlewow-bug-tracker#5749]
After rename my pet dont take any world buff in Orgrimmar. Checked many times. Other pets taked.
Name pet is "Kit"

**Comment by twowTurtReynolds** [comment]
![image](https://github.com/slowtorta/turtlewow-bug-tracker/assets/151180101/fb928dc5-b0bd-442a-b100-347dc5a03cd5)
There's something else the issue here, it isn't the fact the pet is renamed. If you can figure it out, let us know.
