### ISSUE TITLE
Hunter Goblin created before 20/12/2023 - class quest bugged

### ISSUE THREAD

**Issue by remilege** [slowtorta/turtlewow-bug-tracker#5750]
**Please, provide a clear description what the bug is:**

My Goblin hunter was created before the patch and it seems to be buggy.
After a 24h search looking for Viz Fizbeast, as the game thought I was an orc or Troll apparently, I was informed by a GM that the NPC was removed and advised me to go the starting zone for Goblins. Which I did.
I took the "taming the beast" quest in Blackbone Islands but cant use the taming rod, provided by the quest giver.
i decided then to use the appareance token, hoping it would tag me back as a Goblin, maybe. After the usual process (no addons, WDB deleted) the quest still doesnt work.
I'm lv 15 and cant get a pet as hunter ... *tired sigh*

**Steps to reproduce the behavior with as much detail as possible:**

1. Create a Goblin before 20/12/2023
2. Go to Durotar at level 6 before 20/12/2023
3. Try to get the "taming the beast" quest in BB Islands to work

**IDs of affected creatures, items, quests or spells with a link to the relevant page:**

NPC: https://database.turtle-wow.org/?npc=80105
Item: https://database.turtle-wow.org/?item=15911
Quest: Cant find the right quest in the database, given by Mayten Boomrifle "taming the quest"

**Expected behavior. Describe how it should work:**

I should be able to tame the required mobs IG.

I'm stuck at level 15 with no ability to have a pet as hunter ... Could it be possible to just unlock the taming ability for this character ? It's the holidays withthe XP buff, I'm very disappointed to miss this oppportunity to level my toon.

Thanks in advance and happy holidays/merry christmas.

**Comment by slowtorta** [comment]
Hello there!

  The best course of action for you is to cancel all taming quests and start them over on Blaskstone Island (you can travel there from Sparkwater Port). If for some reason you won't be able to pick up new quests, create a ticket in game and GMs w ill assist you as soon as possible!
