### ISSUE TITLE
The brood of Onyxia - Unable to turn the quest

### ISSUE THREAD

**Issue by Zerthy** [slowtorta/turtlewow-bug-tracker#5752]
**Please, provide a clear description what the bug is:**

After taking the quest, quest NPC to complete a quest does not allow to complete the quest. Usually relog works, but this time it didnt.

**Steps to reproduce the behavior with as much detail as possible:**

1. U might be able to complete it at the NPC, 

**IDs of affected creatures, items, quests or spells with a link to the relevant page:**

NPC: https://database.turtle-wow.org/?npc=4500
Quest: https://database.turtle-wow.org/?quest=1170

**Expected behavior. Describe how it should work:**

U might be able to turn the quest .D 
![image](https://github.com/slowtorta/turtlewow-bug-tracker/assets/118677544/94bfb2f5-ce97-4560-a4fc-676fd5f58319)

**Comment by twowTurtReynolds** [comment]
![image](https://github.com/slowtorta/turtlewow-bug-tracker/assets/151180101/2e2bf17a-e685-4ecc-a6f1-9a62beef5709)
Unable to replicate.

**Comment by twowTurtReynolds** [comment]
Please see https://github.com/slowtorta/turtlewow-bug-tracker/issues/6042
