### ISSUE TITLE
Tela'bim | Lost Rigger Cove | Solid Chest LOS problem unlootable 75, 46

### ISSUE THREAD

**Issue by Slimthegrim** [slowtorta/turtlewow-bug-tracker#5757]
**Please, provide a clear description what the bug is:**
On Tela'bim, in Lost Rigger Cover, the Solid Chest on dock has LOS problem which causes the chest to be unlootable from all angles. 

![image](https://github.com/slowtorta/turtlewow-bug-tracker/assets/110629519/3a93e074-3dfe-4611-be80-d791a9ea222c)

![image](https://github.com/slowtorta/turtlewow-bug-tracker/assets/110629519/3f6db818-cef2-42d5-ac75-0551b96e4610)

![image](https://github.com/slowtorta/turtlewow-bug-tracker/assets/110629519/332695ac-386e-4be2-800f-455cb36edf79)

![image](https://github.com/slowtorta/turtlewow-bug-tracker/assets/110629519/3020db3b-0887-44b9-97a4-3951d53a4031)

**Steps to reproduce the behavior with as much detail as possible:**

1. Be the $ultan $elim, goto Lost Rigger Cove.
2. Try and loot the Solid Chest on Dock.
3. See it's not interactable

**Expected behavior. Describe how it should work:**
Lootable.

**Comment by twowTurtReynolds** [comment]
![image](https://github.com/slowtorta/turtlewow-bug-tracker/assets/151180101/5ba56f87-148d-4db2-8bcb-d73170bd18c9)
I don't see a chest here, perhaps it was deleted on Nord but not Tel?

**Comment by Slimthegrim** [comment]
This report is solely for Tel'abim, please continue building up support for QA activities across all prod realms.

**Comment by slowtorta** [comment]
All our realms run on the same copy of the world database.

**Comment by slowtorta** [comment]
![image](https://github.com/slowtorta/turtlewow-bug-tracker/assets/66763404/91fc4512-b2ee-4b57-a5de-f525256c4337)
Please clean your WDB folder.

**Comment by Slimthegrim** [comment]
Thanks! WDB is read only at this point since I'm resetting it daily+.

> All our realms run on the same copy of the world database.

I imagine that's the intention, I just encounter differences regularly between world objects and intractable's like: https://github.com/slowtorta/turtlewow-bug-tracker/issues/4899. Or mailboxes still mismatching between the world's: https://github.com/slowtorta/turtlewow-bug-tracker/issues/5068 ... ?
