### ISSUE TITLE
intervene and intercept shoud not share a cooldown

### ISSUE THREAD

**Issue by elboaf** [slowtorta/turtlewow-bug-tracker#5758]
**Please, provide a clear description what the bug is:**
Intercept and Intervene have historically been on their own separate cooldown. On twow the two spells appear to share a cooldown. I believe this is a bug or oversight. 
Source: 
My memory of playing warrior in TBC, and several wowhead comments confirming my recollection: 
https://www.wowhead.com/spell=3411/intervene#comments:id=100081
https://www.wowhead.com/spell=3411/intervene#comments:id=285062

**Steps to reproduce the behavior with as much detail as possible:**

1. Acquire and use "Manual: Intervene" to learn the intervene spell/ability
2. Use the intervene spell/ability on a friendly target
3. Observe that intercept spell/ability is on cooldown when it should not be.

**IDs of affected creatures, items, quests or spells with a link to the relevant page:**

Spell: 
https://database.turtle-wow.org/?spell=45595
https://database.turtle-wow.org/?spell=27577

Object: https://database.turtle-wow.org/?item=60775

**Expected behavior. Describe how it should work:**
intervene and intercept should have each their own separate cooldowns

**Comment by twowTurtReynolds** [comment]
We are not strictly following TBC or beyond.
