### ISSUE TITLE
Snarler.

### ISSUE THREAD

**Issue by Notaric** [slowtorta/turtlewow-bug-tracker#5759]
**Please, provide a clear description what the bug is:**
Hello. I've been camping this rare creature for like 2 or 3 days in a row. One day spent about 8 hours straight semi-afk on the spot and nothing, it doesen't spawn. But it exist in database.

**IDs of affected creatures, items, quests or spells with a link to the relevant page:**
https://database.turtle-wow.org/?npc=5356

**Expected behavior. Describe how it should work:**
Do you removed it from the game? If yes then bring it back?

**Comment by twowTurtReynolds** [comment]
![image](https://github.com/slowtorta/turtlewow-bug-tracker/assets/151180101/bd4e55f0-07fd-4fa2-b09d-c6a771d5dc7e)
Here he is. Sounds like you need to compete with someone camping him :)

**Comment by Notaric** [comment]
Really interesting. Because there was no ppl beside me camping him. Your post was made 37 minutes ago. And Snarler is gone. Okay i continue camping him for another 9 hours =/

**Comment by Notaric** [comment]
And i hope this was a screenshot from Nordanaar server. Not test server for GM,s.

**Comment by twowTurtReynolds** [comment]
This is a screenshot from the PTR. The bug report dev team has no GM access to live. We cannot help you.
