### ISSUE TITLE
Invisible Goblin Model

### ISSUE THREAD

**Issue by sideblinded** [slowtorta/turtlewow-bug-tracker#576]
**Please, provide a clear description what the bug is:**

**Steps to reproduce the behavior with as much detail as possible:**

1. Goblin model is invisible. Appears as all an all white sprite in Character Info Screen. Human model works fine.

Deleted WDB file, reloaded client. No change.

**Comment by Tinyfin-github** [comment]
Greetings! 

Please contact support on discord for assistance about specific client side issues.

https://discord.com/invite/mBGxmHy
