### ISSUE TITLE
Cannot learn Formula: Enchant 2H Weapon -Minor Intellect 

### ISSUE THREAD

**Issue by SparrowWolf** [slowtorta/turtlewow-bug-tracker#5760]
**Please, provide a clear description what the bug is:**
Recipe not working correctly. Recipe requires enchanting 75, I currently have 95.

**Steps to reproduce the behavior with as much detail as possible:**

1. When trying to right click the recipe, nothing happens. No error, anything

**IDs of affected creatures, items, quests or spells with a link to the relevant page:**

Item: https://database.turtle-wow.org/?item=51286

**Expected behavior. Describe how it should work:**
Should be able to right click recipe and learn it.

![image](https://github.com/slowtorta/turtlewow-bug-tracker/assets/154775348/86be3813-373d-49fa-b009-626137cb9c9c)

**Comment by twowTurtReynolds** [comment]
![image](https://github.com/slowtorta/turtlewow-bug-tracker/assets/151180101/75d6c1a6-f7dc-4b2f-9fbb-baeda0a94476)
![image](https://github.com/slowtorta/turtlewow-bug-tracker/assets/151180101/1d1cffff-6407-4157-8cfc-545416dc523b)

Seems like an addon or mod or something is wrong on your side.

**Comment by Teknishun7** [comment]
Confirmed by player that HDpatch was causing this. Removing the HDpatch fixed it for the player.
