### ISSUE TITLE
Can't use Pattern: Gloves of Manathirst

### ISSUE THREAD

**Issue by SparrowWolf** [slowtorta/turtlewow-bug-tracker#5761]
**Please, provide a clear description what the bug is:**
Recipe not working correctly. Recipe requires enchanting 35, I currently have 122.

**Steps to reproduce the behavior with as much detail as possible:**

1. When trying to right click the recipe, nothing happens. No error, anything

**IDs of affected creatures, items, quests or spells with a link to the relevant page:**

Item: https://database.turtle-wow.org/?item=51277

**Expected behavior. Describe how it should work:**
Should be able to right click recipe and learn it.

![image](https://github.com/slowtorta/turtlewow-bug-tracker/assets/154775348/1608f2fe-9cb2-4e10-927d-3cc53c200078)

**Comment by twowTurtReynolds** [comment]
![image](https://github.com/slowtorta/turtlewow-bug-tracker/assets/151180101/8ddedbcd-a271-418f-a5d9-928ac75612a0)
Same here.

**Comment by Teknishun7** [comment]
Confirmed by player that HDpatch was causing this. Removing the HDpatch fixed it for the player.
