### ISSUE TITLE
No fish in open waters in High Elf starter zone (Alah'Thalas)

### ISSUE THREAD

**Issue by Teknishun7** [slowtorta/turtlewow-bug-tracker#5762]
- Go to fish trainer and fisherman on the dock.
- Cast your line in the water and fish.
- Bobber pops, you skill up but theres no loot.

![image](https://github.com/slowtorta/turtlewow-bug-tracker/assets/89323351/b28a4b55-87c9-4b3a-94a3-eba40af701f5)
![image](https://github.com/slowtorta/turtlewow-bug-tracker/assets/89323351/dde1a9f8-11d8-4563-addc-22750dda364a)

Expected: Getting random fish like small brilliant fish for example.

**Comment by RUTHINAS** [comment]
This seems to crop up with every new zone that is added. Perhaps a checklist of items should be added (or adjusted) for zone creation, with fishing and pick pocket loot tables also included.
