### ISSUE TITLE
New donation rewards in the "Fashion" section can not be viewed on character

### ISSUE THREAD

**Issue by RUTHINAS** [slowtorta/turtlewow-bug-tracker#5763]
**Please, provide a clear description what the bug is:**
The new items added during the 1.17.1 patch (robes, Illidari tattoos etc.) can not be ctrl-clicked on to observe their appearance on the player character. All the tabards that were previously present can be viewed like this, only the newly added items can not.

**Expected behavior. Describe how it should work:**
All Fashion-tab items should be viewable in the dressing room.

**Comment by slowtorta** [comment]
This is fixed in our internal build, please wait for the next client update for this change to be reflected in game.
