### ISSUE TITLE
Darkmoon Dancing Bear

### ISSUE THREAD

**Issue by AndrewWKim** [slowtorta/turtlewow-bug-tracker#5765]
**Please, provide a clear description what the bug is:**
Darkmoon Dancing Bear mount - does not dance.

**Steps to reproduce the behavior with as much detail as possible:**

1. Buy a mount (i did from the Turtle Store)
2. type /mountspecial or /Mountspecial or jump standing at 1 place.
3. No dancing ) 

**IDs of affected creatures, items, quests or spells with a link to the relevant page:**

https://database.turtle-wow.org/?item=81102

**Expected behavior. Describe how it should work:**
Bear should dance ))

**Comment by twowTurtReynolds** [comment]
Fixed in 1.17.2
![bear](https://github.com/slowtorta/turtlewow-bug-tracker/assets/151180101/4b96d9a7-143d-4229-92a7-49ac74c2c13f)

By the way, you dont need to type /mountspecial you can just press space while not moving :)
