### ISSUE TITLE
Winter Veil quest Ticking Present inaccessible

### ISSUE THREAD

**Issue by testening** [slowtorta/turtlewow-bug-tracker#5766]
**Please, provide a clear description what the bug is:**
Ticking Presents are not spawning, or are uninteractable.

**Steps to reproduce the behavior with as much detail as possible:**

1. Go to Orgrimmar or Ironforge Greatherfather Winter present piles
2. Wait 5+ minutes (respawn listed on twow/vanilla databases)
3. Nothing happens. 

**IDs of affected creatures, items, quests or spells with a link to the relevant page:**

Item: https://database.turtle-wow.org/?item=21327
Quest: https://database.turtle-wow.org/?quest=8769
Object: https://database.turtle-wow.org/?object=180748

**Expected behavior. Describe how it should work:**
Interactable Present objects should be spawning after server time hits 25/12.

**Comment by twowTurtReynolds** [comment]
I thought these objects don't need to respawn, but only work for people once per character and do not reset each year?

**Comment by testening** [comment]
@twowTurtReynolds You're correct. Objects became interactable a few days later.
I don't have blizzlike video proof of that happening instantly after 25/12 and not pending a server restart, closing issue.
