### ISSUE TITLE
fish is way to fast to click like 1 frame bob 

### ISSUE THREAD

**Issue by runebishop** [slowtorta/turtlewow-bug-tracker#5770]
**Please, provide a clear description what the bug is:**

**Steps to reproduce the behavior with as much detail as possible:**

1.i go to fish and the bobber is too fast 
2. i was told to clear WDB and nothing happened 
3. was told to come here and type this for you guys 

**IDs of affected creatures, items, quests or spells with a link to the relevant page:**

NPC: https://database.turtle-wow.org/?npc=
Item: https://database.turtle-wow.org/?item=
Quest: https://database.turtle-wow.org/?quest=
Spell: https://database.turtle-wow.org/?spell=
Object: https://database.turtle-wow.org/?object=

**Expected behavior. Describe how it should work:**

**Comment by cyaohiri** [comment]
Related to #5638.

**Comment by twowTurtReynolds** [comment]
Closing as duplicate.
