### ISSUE TITLE
Map Bugged in Hateforge Quarry (Player Icon)

### ISSUE THREAD

**Issue by Scarecrow4012** [slowtorta/turtlewow-bug-tracker#5771]
**Please, provide a clear description what the bug is:**
When you try to use the map in Hateforge Quarry, it gets bugged, usually ocurs after entering in the cave of the dungeon.
**Steps to reproduce the behavior with as much detail as possible:**

1. Enter in the dungeon of Hateforge Quarry
2. Go to the insides area, usually when you enter in the cave.
3. Try to see the map of the dungeon, it usually will show another map bugged instead of showing the dungeon map.

**IDs of affected creatures, items, quests or spells with a link to the relevant page:**
The map of Hateforge Quarry.
**Expected behavior. Describe how it should work:**
The map of the dungeon can be visible in every place inside the dungeon.

This is a screenshot, as you can see, the map of the world is showed instead of showing the dungeon map, you can't see the icons of the capital cities, you can't do anything here, the continents are selectable and the icons of capital cities are visible after doing a right click.
https://drive.google.com/file/d/1XdB94J4Hgep0t4fAo7jGZpWs9qH69I5Z/view?usp=sharing

**Comment by twowTurtReynolds** [comment]
So the only weirdness I could replicate, is that the moment that you step onto this object:
![image](https://github.com/slowtorta/turtlewow-bug-tracker/assets/151180101/6a52db99-d71f-43f0-a3d1-11160c599f15)
Your position no longer shows on the map.
Here is me, right at your spot, and it works fine.
![image](https://github.com/slowtorta/turtlewow-bug-tracker/assets/151180101/bbcc48c7-b074-45ae-8ef4-e855f0ef52cc)

And here is me showing the last point where the map player location works:
![Screenshot_20231225_223214](https://github.com/slowtorta/turtlewow-bug-tracker/assets/151180101/e503e9fd-a9bf-482b-a7da-c6b9a4fd4a62)

I'll be changing your ticket to this more minor issue, unless you can show me how to replicate your issue. If you have any addons, disable them.

**Comment by Scarecrow4012** [comment]
Have you tried going far inside that cave? I don't know the name of that area, but usually happens to me when you go trought that entrance, in the exterior the map works well without problem, but after going inside the map gets bugged, I will try dissabling my addons, strange cause the only addons that I have is the Roleplay addon and the Shagutweaks.
It happened to me two times in the same area and I comprobed it before making a ticket, try going to the last two bosses inside the dungeon, the orc and the golem.

**Comment by twowTurtReynolds** [comment]
Yes, i went all over the instance. I could not reproduce your issue.

**Comment by Scarecrow4012** [comment]
Mmmmm, I guess it's a problem with my client, I will try dissabling addons and deleting the WDB folder. Thanks.

**Comment by twowTurtReynolds** [comment]
Indeed, let us know if you have any updates and I can reopen if nessesary.
