### ISSUE TITLE
Polymorph issue

### ISSUE THREAD

**Issue by imKevinFlynn** [slowtorta/turtlewow-bug-tracker#5776]
**Please, provide a clear description what the bug is:**

Hi there ! I would like to mention a problem with Mage's polymorph spell. Sometimes enemy target that's sheeped keep moving pretty fast to ally target that have threat on it. For example i sheeped some enemy and this enemy keep moving towards my tank. It is a problem, since this target accidentaly can be unsheeped and cause some problems. It happens many times and not only with my own sheeping in raids/dangeons.

**Expected behavior. Describe how it should work:**
Pollymorphed target should make little steps back and forth that's it.

**Comment by twowTurtReynolds** [comment]
It sounds like you have higher latency. When I go to replicate this, mobs will be instantly sheeped and stop right in their tracks.

There's nothing really that can be done here by the dev team.

**Comment by imKevinFlynn** [comment]
Mr Reynolds this problem exist not only for me, it happens with other mage's polymorphs and everyone can see this issue. Sadly I cant provide any video to show you, cause i dont have any , but it is truth.

**Comment by imKevinFlynn** [comment]
I tried to test in what case this pollymorph following happen with my Mage and Warrior on Elite and non elite mobs in different ways of tagging the mob and i cant get this bug happen. Not sure in what scenario it happens :(
