### ISSUE TITLE
Lack of flight path between mudsprocket and brackenwall

### ISSUE THREAD

**Issue by imKevinFlynn** [slowtorta/turtlewow-bug-tracker#5777]
**Please, provide a clear description what the bug is:**

Hi there ! I mentioned that if you take flypath in Dustwallow Marsh from "Brackenwall Village" to "Mudsprocket" in same location you will fly over The Barrens to Camp Torojou and Barrens and only than you fly to "Mudsprocket". It works wise versa , if you fly from "Mudspocket" to "Brackenwall Village" it doing the same thing.

**Comment by twowTurtReynolds** [comment]
![image](https://github.com/slowtorta/turtlewow-bug-tracker/assets/151180101/659439b5-c153-45a7-94be-b5e1c3c87291)
Indeed, it doesn't make much sense these two aren't connected.
![image](https://github.com/slowtorta/turtlewow-bug-tracker/assets/151180101/2d14d5eb-3cbf-4c21-8c76-20725b359595)
You have to go from mudsprocket, to taurajo, to crossroads, to brackenwall.

**Comment by slowtorta** [comment]
This isn't a bug, but a suggestion. 

Vanilla transport routes were always goofy, and I'm not really feeling like fixing this one, sorry.
