### ISSUE TITLE
Quest did not give credit for completion - the icy menace

### ISSUE THREAD

**Issue by LordSpank** [slowtorta/turtlewow-bug-tracker#5778]
**Please, provide a clear description what the bug is:**

The Icy Menace quest. Dated finally showed up and i threw at least a dozen snowballs at him. i ran out and had to buy more snowballs from the vendor. Quest not showing completed. Dated is the last player i need to hit with a snowball to complete quest. I would like credit please. i do have a question, he was in bear form fighting everyone there. (why is hitting him with a snowball flag me for PVP ?)

does he have to be in human form for the snowball to hit ? and why was he fighting us ? not really in the spirit of the event. very atagonistic actually. and he never went into human form that i saw. but i did hit him with a snowball at least 12 times. please complete this quest for me so i can turn it in. thank you.

**Steps to reproduce the behavior with as much detail as possible:**

1. player Dated appears in WV. he is in bear form (and fighting other players)
2. throw snowball after snowball at him
3.  expect to see in quest log that the quest is completed. it is not.

**IDs of affected creatures, items, quests or spells with a link to the relevant page:**

NPC: https://database.turtle-wow.org/?npc=
Item: https://database.turtle-wow.org/?item=
Quest: https://database.turtle-wow.org/?quest= no ID shown. player names from last year. but url is https://database.turtle-wow.org/?quest=50321
Spell: https://database.turtle-wow.org/?spell=
Object: https://database.turtle-wow.org/?object=

**Expected behavior. Describe how it should work:**

the quest log should register that i completed the "throw snowball at Dated" and therefore the whole quest, so that i could turn in that quest

**Comment by twowTurtReynolds** [comment]
Did the other 3 targets work? There is a known bug that some people are ending up with the 2022 version of the quest. Exit game, clear wdb, log back in, and screenshot the 4 players on your quest list.

**Comment by LordSpank** [comment]
yes. othere 3 showed completed.

WDB folder deleted. game restarted . here is the screenshot :

[image: The Icy Menace 1.jpg]

thank you for looking into this for me.

<http://www.avg.com/email-signature?utm_medium=email&utm_source=link&utm_campaign=sig-email&utm_content=webmail>
Virus-free.www.avg.com
<http://www.avg.com/email-signature?utm_medium=email&utm_source=link&utm_campaign=sig-email&utm_content=webmail>
<#DAB4FAD8-2DD7-40BB-A1B8-4E2AA1F9FDF2>

**Comment by twowTurtReynolds** [comment]
Your screenshot did not work. Please reply on the github interface instead of email.

Also, I think you might have been in a raid group, which stops you from progressing nonraid quests. Can you show a picture of you snowballing dated, showing raid panel that confirms you are outside of raid group?

**Comment by LordSpank** [comment]
i dont know how to get a screenshot of me throwing snowballs. and i am not
in that group so cant get a screenshot of that either.
i was in a raid group. and i had added those 4 players as friends so i
could tell when they were online. i saw dated was in WV and ran out of the
cave to throw snowballs at him, while we waited on snowball to spawn.

<http://www.avg.com/email-signature?utm_medium=email&utm_source=link&utm_campaign=sig-email&utm_content=webmail>
Virus-free.www.avg.com
<http://www.avg.com/email-signature?utm_medium=email&utm_source=link&utm_campaign=sig-email&utm_content=webmail>
<#DAB4FAD8-2DD7-40BB-A1B8-4E2AA1F9FDF2>

**Comment by twowTurtReynolds** [comment]
Indeed, being in a raid group prevents nonraid quests from being completed. This is how the game works blizzlike.

Try again outside of a raid group, and you will see the quest work as intended.

**Comment by LordSpank** [comment]
thank you. that was my first raid group. and only did it for the WV quest.
