### ISSUE TITLE
Quest did not give credit for completion - Peace Comes At A Price

### ISSUE THREAD

**Issue by LordSpank** [slowtorta/turtlewow-bug-tracker#5779]
**Please, provide a clear description what the bug is:**

Raid group was waiting for Snowball to show up so we could scrap. I wasa waiting for about 3.5 hours. There was a notice the server was about to restart. AT 1 minute to restart, Snwoball showed up and we attacked. I saw him fall as i got booted out. This morning i saw that we did not get credit for the kill and the quest is still uncompleted.

**Steps to reproduce the behavior with as much detail as possible:**

1. Snowball appears. Raid group attacks. Server restart timer is at 1 minute.
2. during attack the server restarts
3. the next day, checking my quest log i see the quest is not completed

**IDs of affected creatures, items, quests or spells with a link to the relevant page:**

NPC: https://database.turtle-wow.org/?npc=
Item: https://database.turtle-wow.org/?item=
Quest: https://database.turtle-wow.org/?quest= not seeing an ID in the DB but here is the url - https://database.turtle-wow.org/?quest=50330
Spell: https://database.turtle-wow.org/?spell=
Object: https://database.turtle-wow.org/?object=

**Expected behavior. Describe how it should work:**

Raid group kills Snowball and quest log says quest is complete. PLease adjust my quest log accordingly so that i might turn in the quest. thank you.

**Comment by twowTurtReynolds** [comment]
Please contact a GM. It sounds like there is no bug for the dev team to fix here.

**Comment by LordSpank** [comment]
can i do that in game ? i cant post in Discord (because i dont own a
cellphone for them to verify me with. and there is no email option to
verify)

<http://www.avg.com/email-signature?utm_medium=email&utm_source=link&utm_campaign=sig-email&utm_content=webmail>
Virus-free.www.avg.com
<http://www.avg.com/email-signature?utm_medium=email&utm_source=link&utm_campaign=sig-email&utm_content=webmail>
<#DAB4FAD8-2DD7-40BB-A1B8-4E2AA1F9FDF2>

**Comment by twowTurtReynolds** [comment]
> [How to contact a GM and get help in-game]
> 
> Near your key ring there is a red question mark, press it to send an in-game ticket.Also you can enter the command /gm in the game chat. 
> 
> You don't need to be online for tickets to be solved. Support will respond via in-game mail.

**Comment by LordSpank** [comment]
thank you :)

happy holidays
