### ISSUE TITLE
The Hunter's Track Humanoids skill occasionally erroneously tracks beasts instead of humanoids

### ISSUE THREAD

**Issue by Hydra9268** [slowtorta/turtlewow-bug-tracker#5784]
**Please, provide a clear description of what the bug is:**

I'm using a hunter ability in Winterspring to locate Ragged Owlbeasts, but the pip target on the mini-map incorrectly identifies Fledgling Chillwinds as "Ragged Owlbeasts." This error occurs in multiple instances.

Screenshot of issue: https://i.imgur.com/kzgwSPz.jpeg
In the same spot but facing north to another mob: https://i.imgur.com/K6KkwPN.jpeg

**Steps to reproduce the behavior with as much detail as possible:**

1. Head to approximately coordinates 44,35 in Winterspring as a hunter.
2. Activate the Track Humanoids ability.
3. Observe the outcomes.

**Expected behavior. Describe how it should work:**

Tracking humanoids should track humanoids ("Ragged Owlbeast") and not beasts ("Fledgling Chillwinds").

**Comment by twowTurtReynolds** [comment]
![image](https://github.com/slowtorta/turtlewow-bug-tracker/assets/151180101/4f0a69f7-136a-442b-91f1-28ace14d61de)

I can't reproduce this. I think you either might be mistaken, or you might have addon issues.
