### ISSUE TITLE
血环部落游戏名字：尸主你别走；荣誉结算错误减少了哟的荣誉值

### ISSUE THREAD

**Issue by sznbz** [slowtorta/turtlewow-bug-tracker#5786]
**Please, provide a clear description what the bug is:**

**Steps to reproduce the behavior with as much detail as possible:**

1.首先确保角色是正常玩家而且没有获得非荣誉的
2. 12月20日荣誉值是9R.0.78%的
3. 截止现在12月27日，我的荣誉值变成了0%，这期间我一直有增加荣誉经验的，不可能是0的，请帮忙调整，谢谢。

**IDs of affected creatures, items, quests or spells with a link to the relevant page:**

NPC: https://database.turtle-wow.org/?npc=
Item: https://database.turtle-wow.org/?item=
Quest: https://database.turtle-wow.org/?quest=
Spell: https://database.turtle-wow.org/?spell=
Object: https://database.turtle-wow.org/?object=

**Expected behavior. Describe how it should work:**

**Comment by twowTurtReynolds** [comment]
请用英文提交问题。我们无法通过自动翻译准确地翻译中文提交的错误报告，这使得我们难以理解问题的确切性质。谢谢！

Please submit the issues in English. We're unable to accurately translate bug reports submitted in Chinese through automatic translation, which makes it difficult for us to understand the exact nature of the issue. Thank you!
