### ISSUE TITLE
Custom zones on world map

### ISSUE THREAD

**Issue by cyaohiri** [slowtorta/turtlewow-bug-tracker#5787]
Some custom zones come revealed on the world map from the start, and some don't. They should all be either one or the other, preferably not revealed.
This was tested on a new character after deleting the game cache and disabling addons.

Custom zones that come revealed:
Lapidis Isle, Gillijim's Isle, Tel'Abim, Gilneas, Hyjal, and Scarlet Enclave

Custom zones that do not come revealed:
Thalassian Highlands and Blackstone Island.

These last two zones were only added in the last patch (1.17.1), and that might be the reason they differ from older zones.

On a related note, custom areas within existing zones also come revealed. For example, Ruins of Corthan in Badlands.
![image](https://github.com/slowtorta/turtlewow-bug-tracker/assets/86041826/079dfe81-c0b2-41b1-a816-7fcd1b35ee2f)

**Comment by twowTurtReynolds** [comment]
Already on it. Now that we have the knowhow and tech to make custom areas discoverable, our team is doing a pass to make these subzones discoverable, and a revamp on the previous full zone maps like Gilijim. We're aiming for 1.17.2 :)
