### ISSUE TITLE
Custom Item Crashing Client Upon Death

### ISSUE THREAD

**Issue by XandyCode** [slowtorta/turtlewow-bug-tracker#5788]
**Please, provide a clear description what the bug is:**

Custom item Thornweave Mask seems to be crashing game in some scenarios.

Most notably, it seems to be related to dying and releasing spirit. I am unsure if being in a battleground makes a difference, but the issue occurs most commonly there.

I have toggled on and off every possible setting and even downloaded a new client. This issue persists on a fresh download. Dying and releasing in a BG causes a crash about 50% of the time.

Unequipping this item and putting it in the bank completely fixes the issue

**Steps to reproduce the behavior with as much detail as possible:**

1. Have Thornweave mask equipped on login 
3. Enter Battleground
4. Die/Release spirit a few times

**IDs of affected creatures, items, quests or spells with a link to the relevant page:**

Item: https://database.turtle-wow.org/?item=61060

**Expected behavior. Describe how it should work:**
Game should not crash when dying

**Comment by twowTurtReynolds** [comment]
![image](https://github.com/slowtorta/turtlewow-bug-tracker/assets/151180101/059dc11b-1f59-4623-af9e-4e0f6e0c1cd0)
![image](https://github.com/slowtorta/turtlewow-bug-tracker/assets/151180101/ef1af38c-a88f-4546-985f-7d3a172fbc3f)
![image](https://github.com/slowtorta/turtlewow-bug-tracker/assets/151180101/d223c673-afc1-45a5-b5d2-a3f9d51382e5)

Something else must be the cause. This isn't it.

**Comment by XandyCode** [comment]
I do have it transmog'd, that may make a difference.
Maybe others removing insignia upon death?

Hard to say but I go from consistent crashes to none when I remove this item.

**Comment by twowTurtReynolds** [comment]
That does make a difference, maybe your current mog is really bugged. Try removing the transmog on the helmet, then apply it again. I think you can try asking a GM for a compensated fashion token, maybe, to let you do that, in which case do link this bug report.

If it persists, let me know and what exact item you mogged it too, and then I'll try exactly that again.

**Comment by twowTurtReynolds** [comment]
We've gotten more reports about this, seemed even non-xmogged versions are having this issue, but only when combined with other gear pieces. We're remaking the model to prevent this.

**Comment by slowtorta** [comment]
Clear your WDB, the item has already been fixed a long time ago!
