### ISSUE TITLE
Bashguuder Low PPM

### ISSUE THREAD

**Issue by antonskims** [slowtorta/turtlewow-bug-tracker#5792]
**Please, provide a clear description of what the bug is:**
~~The issue with Mace Bashguuder. Faerie Fire (Feral) is replacing the debuff from the mace(Puncture Armor) and it doesn't seem correct.~~ Also, I wanted to check if the proc chance is correct, because on the official server, it was pretty easy to get 3 stacks, here, I couldn't reach 3 stacks in a long test with the mace in MH.

**Steps to reproduce the behavior with as much detail as possible:**

~~1. Equip Bashguuder
2. Hit the target until the debuff is up
3.  Cast Faerie Fire (Feral)~~

**IDs of affected creatures, items, quests, or spells with a link to the relevant page:**

Item: https://database.turtle-wow.org/?item=13204
Spell: https://database.turtle-wow.org/?spell=17392
Spell: https://database.turtle-wow.org/?spell=17315

**Expected behavior. Describe how it should work:**
~~Pretty easy to hold 3 stacks in a long fight. Faerie Fire (Feral) shouldn't replace Puncture Armor. Puncture Armor should be able to stack with Faerie Fire (Feral) AND with Exposed Armor OR Sunder~~

**Comment by cyaohiri** [comment]
The inability to stack with Faerie Fire is intended since patch 1.8: "The Puncture Armor ability found on the Bashguuder will no longer stack with Faerie Fire."
https://wowpedia.fandom.com/wiki/Bashguuder

On VMaNGOS, it stacks with Sunder Armor and Expose Armor. This is how it's supposed to be, looking at the comments on Wowhead,

As for the proc rate, it seems to happen about once every 40 attacks with unmodified attack speed.

**Comment by balakethelock** [comment]
Then it is bugged, in classic the proc rate is 2ppm equivalent to 6% per swing
source: wow armaments discord https://discord.com/channels/719591797705146488/827869676892717066/827870457096830987

**Comment by twowTurtReynolds** [comment]
After 5 quick tests with 1000% haste, procwatch is reporting 30 hits per proc at worst, 60 at best. Seems low.

**Comment by Dragunovi** [comment]
Should be fixed with the next scheduled restart. If this issue persists please reopen this issue so we look into it further.
