### ISSUE TITLE
Goblin Warlock Voidwalker Quest Unavailable

### ISSUE THREAD

**Issue by blailex** [slowtorta/turtlewow-bug-tracker#5794]
**Please, provide a clear description what the bug is:**

When doing the level 10 voidwalker quest for Warlock from the Goblin starting zone. You are taken to Orgrimmar but you are unable to access the voidwalker quest as a Goblin.

I cannot remember the name of the quest

**Comment by blailex** [comment]
You are able to obtain the quest from the Warlock trainer in Razor Hill

**Comment by twowTurtReynolds** [comment]
![image](https://github.com/slowtorta/turtlewow-bug-tracker/assets/151180101/8c020f73-0e44-4f00-9a52-d981e143de7a)
![image](https://github.com/slowtorta/turtlewow-bug-tracker/assets/151180101/0c5d1497-558b-4a64-b332-301a63150eac)
![image](https://github.com/slowtorta/turtlewow-bug-tracker/assets/151180101/199f2c93-534f-491c-a702-63aca779589f)

I'm not sure what the case with your character is, perhaps you had a pre 1.17.1 lv 9 or lower goblin warlock? In such cases, indeed just use the razor hill -> org quest instead.
