### ISSUE TITLE
Item of Asian server - Ring: Mark of the Worgen  ，it cannot cool down properly when the character enters the Hot-Sand Blood-Ring Arena

### ISSUE THREAD

**Issue by mengmengorc** [slowtorta/turtlewow-bug-tracker#5796]
<img width="436" alt="狼人印记" src="https://github.com/slowtorta/turtlewow-bug-tracker/assets/155047570/73042fdd-d42b-432f-bab2-13d4c07171c4">
**Please, provide a clear description what the bug is:**

**Steps to reproduce the behavior with as much detail as possible:**

1.
2. 
3. 

**IDs of affected creatures, items, quests or spells with a link to the relevant page:**

NPC: https://database.turtle-wow.org/?npc=
Item: https://database.turtle-wow.org/?item=
Quest: https://database.turtle-wow.org/?quest=
Spell: https://database.turtle-wow.org/?spell=
Object: https://database.turtle-wow.org/?object=

**Expected behavior. Describe how it should work:**

**Comment by twowTurtReynolds** [comment]
The cooldowns do work, in and out of blood ring:
![image](https://github.com/slowtorta/turtlewow-bug-tracker/assets/151180101/85dbf74d-d09d-403f-aa19-06148574d172)
![image](https://github.com/slowtorta/turtlewow-bug-tracker/assets/151180101/4cbea9e4-191d-46bd-aeed-d4feacc8dc85)
But indeed they do not reset.
![image](https://github.com/slowtorta/turtlewow-bug-tracker/assets/151180101/a2ef6d7c-51a5-49b4-af19-a591eb138610)

Blood ring is designed to only reset up to 9 maybe 10min cooldowns. Working as intended
