### ISSUE TITLE
Dec 27 Honor settlement error, need to be adjusted

### ISSUE THREAD

**Issue by sznbz** [slowtorta/turtlewow-bug-tracker#5797]
**Please, provide a clear description what the bug is:**
From December 20 to 27, the character's honor settlement was cleared in error. This period of time did not obtain non-honor, and has been increasing the honor score, it is impossible to be 0% of the current settlement, please GM to adjust, thank you!

**Steps to reproduce the behavior with as much detail as possible:**

1.Server: Blood Ring
Formation: Horde
Character Name: Corpse Master Don't Go（尸主你别走）
2. Honor settlements reduced, system errors
3. This is a serious loss for me, I spent a lot of labor and energy in the middle of the

**IDs of affected creatures, items, quests or spells with a link to the relevant page:**

NPC: https://database.turtle-wow.org/?npc=
Item: https://database.turtle-wow.org/?item=
Quest: https://database.turtle-wow.org/?quest=
Spell: https://database.turtle-wow.org/?spell=
Object: https://database.turtle-wow.org/?object=

**Expected behavior. Describe how it should work:**
From December 20 to 27, the character's honor settlement was cleared in error. This period of time did not obtain non-honor, and has been increasing the honor score, it is impossible to be 0% of the current settlement, please GM to adjust, thank you!

**Comment by twowTurtReynolds** [comment]
Honor is working as intended.

**Comment by sznbz** [comment]
> 荣誉正在按预期工作。

Grateful for your help, hope the game gets better and better, thanks!
