### ISSUE TITLE
Breath meter on land

### ISSUE THREAD

**Issue by cyaohiri** [slowtorta/turtlewow-bug-tracker#5798]
Breath meter appears on land in Feralas, at around `.go xy -4625 100 1`.
![image](https://github.com/slowtorta/turtlewow-bug-tracker/assets/86041826/c52bf4da-454d-4b04-8f9d-3382bdbbad4d)

**Comment by twowTurtReynolds** [comment]
Duplicate of https://github.com/slowtorta/turtlewow-bug-tracker/issues/4568
