### ISSUE TITLE
Brill/Forsaken level 10 Hunter quest stage 2

### ISSUE THREAD

**Issue by Fitzgeralldd** [slowtorta/turtlewow-bug-tracker#580]
**Please, provide a clear description what the bug is:**
Unable to tame a Greater Duskbat outside of Brill without being interrupted by their Swipe ability during the Second Forsaken Hunter quest
**Steps to reproduce the behavior with as much detail as possible:**

1. Accept the second quest of the Hunter chain at lvl 10
2. Cast the taming ability
3. Use all 3 charges trying to tame the pet

**IDs of affected creatures, items, quests or spells with a link to the relevant page:**

NPC: https://database.turtle-wow.org/?npc=
Item: https://database.turtle-wow.org/?item=
Quest: https://database.turtle-wow.org/?quest=
Spell: https://database.turtle-wow.org/?spell=
Object: https://database.turtle-wow.org/?object=

**Expected behavior. Describe how it should work:**

**Comment by Tinyfin-github** [comment]
Greetings! I have tested and i have been unable to find any issues with the quest.

The quests level of difficulty is the same as the taurens "Training the Beast" where you have to train a Swoop.

**Comment by TrangOul** [comment]
It is possible to tame a lesser bat (such as Mangy Duskbat, found in Deathknell), which does not use Ravage.
