### ISSUE TITLE
Crit chance went to 0%

### ISSUE THREAD

**Issue by Whereismycrit** [slowtorta/turtlewow-bug-tracker#5800]
**Please, provide a clear description what the bug is:**
Suddenly, I realised my crit chance is at 0% at level 22 with 95 agility.
My character name is Bup, night elf hunter.

![2](https://github.com/slowtorta/turtlewow-bug-tracker/assets/155063597/08ae8e7b-70f5-4d3c-823f-92fc52752bae)
![1](https://github.com/slowtorta/turtlewow-bug-tracker/assets/155063597/8d18abf8-f2c5-4a88-b488-cc4f33cf8858)

**Steps to reproduce the behavior with as much detail as possible:**

1. Log in (even after deleting WDB) to my character
2. Check character stats
3. Find out crit is 0%

**Expected behavior. Describe how it should work:**
I imagine at level 22, 95 agi is good (got a couple of blues from dungeons, etc) so my crit should not be 0%.
Update: finished a quest and increased my agi by 3, crit went to 0.14%.
Update2: leveled up to 23 and crit went back to 0%, which is normal since every level it decreases, but I really do not think I should be at 0%, talked to a level 25 hunter who had 80 agi and like 3.5% crit (i'm a hunter too).

Thank you and have a nice day.

**Comment by cyaohiri** [comment]
Does it happen with different types of weapons and what is your polearm skill?

**Comment by Whereismycrit** [comment]
Just as I was going to type this I saw your comment. My polearm skill is indeed 0, but if the melee weapon skill affects the ranged crit it is clearly not working as intended, right?

_The first picture would indeed be normal since my melee crit is 0% because of 0 skill, but ranged crit is a different story_

**Comment by cyaohiri** [comment]
Ranged crit chance isn't displayed anywhere without addons, so it's an issue with the addon you're using.

**Comment by Whereismycrit** [comment]
Yeah, seems like it. Thank you for the tip!
