### ISSUE TITLE
Guild bank System Turtle  Wow

### ISSUE THREAD

**Issue by Josephienvandermeersch** [slowtorta/turtlewow-bug-tracker#5803]
**Please, provide a clear description what the bug is:**
After purchasing the 2000g Guild bank, only the guild master can deposit and withdraw items, and also the Icons of the Items are not showing.

**Steps to reproduce the behavior with as much detail as possible:**

1. Log in to Officer Alt - Unable to Withdraw or Deposit
2.  Logged in to Third guild rank - unable to withdraw or deposit
3.  Viewed Guild bank - cant see icons.

**IDs of affected creatures, items, quests or spells with a link to the relevant page:**

NPC: https://database.turtle-wow.org/?npc=
Item: https://database.turtle-wow.org/?item=
Quest: https://database.turtle-wow.org/?quest=
Spell: https://database.turtle-wow.org/?spell=
Object: https://database.turtle-wow.org/?object=

**Expected behavior. Describe how it should work:**
![image](https://github.com/slowtorta/turtlewow-bug-tracker/assets/24510505/4b748539-70f0-4d96-9457-156bd4b5da27)
![image](https://github.com/slowtorta/turtlewow-bug-tracker/assets/24510505/277d220c-1f2f-45d4-976d-8d618ad61203)

**Comment by Josephienvandermeersch** [comment]
According to Gamemaster & the forums, the first 3 highest ranks should be able to withdraw or deposit.

And Clearing the Icons should be showing

Already cleared Cache etc..

**Comment by twowTurtReynolds** [comment]
The GM and the forums are out of date, the guild bank addon now has the option to let you configure each tab, and indeed, GM-only is defaulted:
![image](https://github.com/slowtorta/turtlewow-bug-tracker/assets/151180101/f8999aa5-6990-4751-a2d5-cec77cd99eb2)

As for the blank items, It is likely that you have an addon or mod that is breaking the interface. I cannot reproduce. If all else fails, try a fresh client.
![image](https://github.com/slowtorta/turtlewow-bug-tracker/assets/151180101/bad70b6f-42b0-4597-bcfd-af4d55ddf900)
