### ISSUE TITLE
Runeblade of Baron Rivendare bug

### ISSUE THREAD

**Issue by 18111144703** [slowtorta/turtlewow-bug-tracker#5805]
**Please, provide a clear description what the bug is:**
Runeblade of Baron Rivendare， Not affected by magic damage and healing effect bonus
**Steps to reproduce the behavior with as much detail as possible:**

1.
2. 
3. 

**IDs of affected creatures, items, quests or spells with a link to the relevant page:**

NPC: https://database.turtle-wow.org/?npc=
Item: https://database.turtle-wow.org/?item=
Quest: https://database.turtle-wow.org/?quest=
Spell: https://database.turtle-wow.org/?spell=
Object: https://database.turtle-wow.org/?object=

**Expected behavior. Describe how it should work:**

**Comment by twowTurtReynolds** [comment]
Working as intended.
