### ISSUE TITLE
Thalassian Drowning spot

### ISSUE THREAD

**Issue by UlukayOutkastov** [slowtorta/turtlewow-bug-tracker#5808]
**The character suffocates in this place, standing on the surface.** ~49.1, 46.3
![изображение](https://github.com/slowtorta/turtlewow-bug-tracker/assets/95168076/829beaa5-3672-4ad9-ad62-74479294eb82)

**Comment by twowTurtReynolds** [comment]
Closing, tracking this under https://github.com/slowtorta/turtlewow-bug-tracker/issues/5811 now.
