### ISSUE TITLE
Quest "Make the Right Choice" displaying requirements wrong

### ISSUE THREAD

**Issue by jonoecker** [slowtorta/turtlewow-bug-tracker#581]
Quest: Make the Right Choice

NPC:Ophelia Worthington

Description on quest accept prompt references both Righteous Orb and Flawless Draenethyst Sphere aswell as the summary text on the quest turn in prompt, but the summary text for the quest accept prompt requires 5 Righteous Orbs. The quest still requires the Flawless Draenethyst Sphere.

**IDs of affected creatures, items, quests or spells with a link to the relevant page:**

!!Database down!!

**Comment by Neto-WoW** [comment]
Fixed. Thanks.

**Comment by SabineWren** [comment]
Quest still requests 5 orbs, but requires 1 and a sphere.
