### ISSUE TITLE
In Gunther's Favor Bugged still

### ISSUE THREAD

**Issue by Necrofiend13** [slowtorta/turtlewow-bug-tracker#5813]
**Please, provide a clear description what the bug is:**
chest is not spawning behind ambermill town hall
**Steps to reproduce the behavior with as much detail as possible:**

1. accept quest
2. go to ambermill town hall rear
3. see there is no item to take or progression to attain

**Expected behavior. Describe how it should work:**

i don't know. I presume to take the locket for Gunther from a buried mound.

**Comment by twowTurtReynolds** [comment]
https://database.turtle-wow.org/?quest=80725

![image](https://github.com/slowtorta/turtlewow-bug-tracker/assets/151180101/d14227fc-0422-4005-bc15-9e569ec3a958)
Wow, this is really well hidden. But it's there! Good luck!
