### ISSUE TITLE
Drain Soul has halved spell power scaling

### ISSUE THREAD

**Issue by TatkaS1** [slowtorta/turtlewow-bug-tracker#5815]
**Please, provide a clear description what the bug is:**

Warlock's Affliction spell Drain Soul has only **50% spell power scaling** (10% every 3 seconds for 15 seconds, 50% total) while it should have **100% spell power scaling** (20% every 3 sec), as all single target spells with channel **duration 3,5 seconds or longer**. This scaling is incorrect for **ranks 2, 3 and 4**. Rank 1 scaling is correct.

![image](https://github.com/slowtorta/turtlewow-bug-tracker/assets/87695943/5f5af0e8-287c-4dd5-b826-394011752869)
455 / 5 = 91 damage per tick

![image](https://github.com/slowtorta/turtlewow-bug-tracker/assets/87695943/3536061d-e423-41dd-9e1c-28c9102fefab)
723 spell power gives only 72 damage per tick, so it's 163 instead of 235 damage per tick, making the spell ~30% weaker in my case

**Steps to reproduce the behavior with as much detail as possible:**

1. Find a suitable victim.
2. Cast Drain Soul rank 2/3/4, unbuffed/talented for clarity.
3. See that it only scales with 10% of your spell power per tick, instead of 20%.

**IDs of affected creatures, items, quests or spells with a link to the relevant page:**

Spell: https://database.turtle-wow.org/?spell=8288 rank 2
Spell: https://database.turtle-wow.org/?spell=8289 rank 3
Spell: https://database.turtle-wow.org/?spell=11675 rank 4

**Expected behavior. Describe how it should work:**

The Drain Soul ranks 2-4 should scale twice as much. Halving spell power scaling is only used for **life draining** spells like Drain Life, Siphon Life and Death Coil.

**Comment by twowTurtReynolds** [comment]
This is a blizzard spell. Please provide proof that this is how it works on classic or back in 2006 retail.

**Comment by TatkaS1** [comment]
Did some more research:
This post contains spell power coefficients for class spells gathered by TheoryCraft addon during 1.12 and is correct for many other spells that I checked https://www.reddit.com/r/classicwow/comments/95abc8/list_of_spellcoefficients_1121/
It's got Mage and even Paladin (who has often unique scaling rules) spells figured out correctly, and the logic checks out, too, so I'd expect Drain Soul, as it's a simple spell to test, to be correct. But wowhead classic database says otherwise. I couldn't find a sample from Blizzard server of warlock using Drain Soul (only PvP and raid montages out there), so I'll leave it at that.
