### ISSUE TITLE
Dire Maul West

### ISSUE THREAD

**Issue by Kraybana** [slowtorta/turtlewow-bug-tracker#5816]
**Please, provide a clear description what the bug is:**
the bug was Dire Maul West the Ghost part after the first part.. but firstly the dungeon pulled alot of mobs to us.. luckily we were able to handle majority of the part but the ghosts were hitting harder than usual and one pull pulled damn near the whole room.
**Steps to reproduce the behavior with as much detail as possible:**

1.revived and tried again and failed worse than the last
2.damage was too high to out heal it 
3. 

**IDs of affected creatures, items, quests or spells with a link to the relevant page:**
The banshee looking mobs right next to the first elderwood boss.
NPC: https://database.turtle-wow.org/?npc=
Item: https://database.turtle-wow.org/?item=
Quest: https://database.turtle-wow.org/?quest=
Spell: https://database.turtle-wow.org/?spell=
Object: https://database.turtle-wow.org/?object=

**Expected behavior. Describe how it should work:**

**Comment by twowTurtReynolds** [comment]
Vmangos:
![image](https://github.com/slowtorta/turtlewow-bug-tracker/assets/151180101/e59a1f0f-a59c-479f-b5d7-a7781a64cb7d)
Turtle:
![Uploading image.png…]()

I was able to pull just 4 at a time, and they do reasonable damage.
