### ISSUE TITLE
The icy menace

### ISSUE THREAD

**Issue by V850000** [slowtorta/turtlewow-bug-tracker#5817]
**Please, provide a clear description what the bug is:**

**Steps to reproduce the behavior with as much detail as possible:**

1.
2. 
3. 

**IDs of affected creatures, items, quests or spells with a link to the relevant page:**

NPC: https://database.turtle-wow.org/?npc=
Item: https://database.turtle-wow.org/?item=
Quest: https://database.turtle-wow.org/?quest=
Spell: https://database.turtle-wow.org/?spell=
Object: https://database.turtle-wow.org/?object=

**Expected behavior. Describe how it should work:**

**Comment by Muigin** [comment]
Please submit a proper bug report instead of a blank template.

**Comment by V850000** [comment]
The question list show it’s complete, but can’t submit it.
