### ISSUE TITLE
The Icy Menace won't complete

### ISSUE THREAD

**Issue by darqon** [slowtorta/turtlewow-bug-tracker#5818]
**Please, provide a clear description what the bug is:**
Since The Icy Menace quest has changed to remove Dated, My quest should be complete as I have hit the other 3 with snowballs. I have deleted my WDB folder. The game now shows this quest as completed, but the snowman I'm supposed to turn it into does not recognize the quest as complete, and still says "Just throw it"

**Steps to reproduce the behavior with as much detail as possible:**

1. Throw snowballs at all 3 players for the quest.
2. Go to turn it in.
3. Snowman won't let me.

**IDs of affected creatures, items, quests or spells with a link to the relevant page:**

NPC: https://database.turtle-wow.org/?npc=50662
Quest: https://database.turtle-wow.org/?quest=50321

**Expected behavior. Describe how it should work:**
I should be given the text for completing the quest, followed by my quest rewards.

**Comment by twowTurtReynolds** [comment]
I can't test this myself, the PTR has last year's quest instead. Can anyone else attest to if the new version works or not?

**Comment by darqon** [comment]
Other people in World chat say it's working now, but not me. I'm online right now if that helps, character name is the same as this username, NA server.

**Comment by LootSea** [comment]
I have the same problem as Darqon. I've snowballed the three peopled needed. The quest says it is completed. However, I am unable to turn the quest in. I have deleted my WDB but that did not help.

**Comment by Ravenya333** [comment]
I had 3/4 Chars, then Dated got removed for the Objective List and now its marked as completed but the Questgiver wont accept it. Deleting WDB didnt help.

**Comment by twowTurtReynolds** [comment]
This bug happens to people who picked up the quest earlier, when there were 4 objectives. Anyone picking up the quest now after the change to 3 is fine.

If anyone wants an immediate fix, please contact a GM letting them know you need help with your old copy of Icy Menace 40576 that can't get completed.

I'm checking with the core staff if we can maybe do a bulk fix or not to take some load off of the support staff.
