### ISSUE TITLE
乌龟服角色邮箱出现问题

### ISSUE THREAD

**Issue by amuro1126** [slowtorta/turtlewow-bug-tracker#5819]
**Please, provide a clear description what the bug is:**
My game character's(ID:JOICY,Server：Emerald Dream） email cannot correctly receive emails from auction houses。After all auction items indicate successful auction, email cannot receive emails.Gold coins that have failed bidding cannot be picked up through email.After the auction goods arrive at the time, emails containing items cannot be received in the mailbox.
**Steps to reproduce the behavior with as much detail as possible:**

1.
2. 
3. 

**IDs of affected creatures, items, quests or spells with a link to the relevant page:**

NPC: https://database.turtle-wow.org/?npc=
Item: https://database.turtle-wow.org/?item=
Quest: https://database.turtle-wow.org/?quest=
Spell: https://database.turtle-wow.org/?spell=
Object: https://database.turtle-wow.org/?object=

**Expected behavior. Describe how it should work:**

**Comment by twowTurtReynolds** [comment]
Cannot reproduce.

**Comment by amuro1126** [comment]
啥意思？？？

**Comment by amuro1126** [comment]
我的游戏角色邮箱出问题了&nbsp; 我挂在拍卖行成功卖出的东西收不到拍卖款的邮件了，拍卖到期之后的退还邮件也收不到，竞拍失败退还金币的邮件也收不到，已经重新下载过客户端、清理过WDB了，还是不行




------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "slowtorta/turtlewow-bug-tracker"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2023年12月29日(星期五) 晚上10:19
***@***.***&gt;;
***@***.******@***.***&gt;;
主题:&nbsp;Re: [slowtorta/turtlewow-bug-tracker] 乌龟服角色邮箱出现问题 (Issue #5819)





 
Cannot reproduce.
