### ISSUE TITLE
New Tirisfal Alliance NPCs Classified as Undead

### ISSUE THREAD

**Issue by Thaddian** [slowtorta/turtlewow-bug-tracker#582]
Most of the human Lordaeron NPCs, either named or generic, have undead classification. My friend was able to exorcise some of the farmers.

**IDs of affected creatures, items, quests or spells with a link to the relevant page:**
N/A.

**Comment by Neto-WoW** [comment]
Please complete with proper bug reporting format here: https://github.com/slowtorta/turtlewow-bug-tracker/issues/new
