### ISSUE TITLE
Problem with Zg NR enchant quest

### ISSUE THREAD

**Issue by LRotautas** [slowtorta/turtlewow-bug-tracker#5820]
**Please, provide a clear description what the bug is:** Just wanted to get nature ressist enchant, checked every possible information how to get it and tryed to do it, grabbed all needed items to complete quest but after coming to that npc couldnt claim any quest, did a ticket and GM: "Saelas" helped to get that one, after claiming i couldnt do any more but databases says its repeatable.

**Steps to reproduce the behavior with as much detail as possible:**

1.Hi, had problem of getting quest of Nature Resist enchant from Zul'Gurub [The Savage Guard - Arcanum of Focus] https://database.turtle-wow.org/?quest=9210
2. Checked twow database and wowhead, to claim quest and finish it you just need [Arcanum of Focus](https://database.turtle-wow.org/?item=18330)
3.  After coming to Zanza the Restless i couldnt get any of Arcanum quests.

**IDs of affected creatures, items, quests or spells with a link to the relevant page:**

NPC: https://database.turtle-wow.org/?npc=15042
Item: https://database.turtle-wow.org/?item=22635
Quest: https://database.turtle-wow.org/?quest=9210
Spell: https://database.turtle-wow.org/?spell=
Object: https://database.turtle-wow.org/?object=

**Expected behavior. Describe how it should work:**

**Comment by twowTurtReynolds** [comment]
The acranum quests have a prerequisite that you forgot to do, they aren't available right away.

**Comment by LRotautas** [comment]
Hi, you mean Dire Maul Arcanum quest to get [Arcanum of Focus] because i did this quest. I have problem with ZG raid quest to get Nature resist quest

**Comment by twowTurtReynolds** [comment]
So you have an arcanum in your bags? 
![image](https://github.com/slowtorta/turtlewow-bug-tracker/assets/151180101/66d8c995-99e3-4e5e-a9c6-839ad8527a36)
That part works fine, I can't replicate any issues.

**Comment by LRotautas** [comment]
Yes I do, after completing 1 time i cant do anymore, but database says its repeatable for that quest. 
![arcanum](https://github.com/slowtorta/turtlewow-bug-tracker/assets/146812700/83911e41-73de-4260-b8b1-9ec5e80b4be7)
![nr](https://github.com/slowtorta/turtlewow-bug-tracker/assets/146812700/e15e99b1-e3c3-4e03-b6c7-6a665e367705)

**Comment by twowTurtReynolds** [comment]
![image](https://github.com/slowtorta/turtlewow-bug-tracker/assets/151180101/8aeebd13-0f19-4a06-9eac-243f9de56f9a)
I can't replicate. Make sure your reputation is up to snuff.
