### ISSUE TITLE
Warrior Thunder Clap wont crit

### ISSUE THREAD

**Issue by Huntshorde** [slowtorta/turtlewow-bug-tracker#5822]
Thunder Clap wont deal critical strike damage.

1. Go to training dummy or low level mob. 
2. Pop recklessness.
3. Spam Thunder Clap and read combat logs.
When I read online, Arms Talent impale and Deep Wounds are meant to work with and proc off Thunder Clap, respectively.

NPC: All
Item: None
Quest: None
Spell: Thunder Clap
Object: Critical Strike Damage.

**Comment by twowTurtReynolds** [comment]
Thunderclap doesnt work on neither phys nor spell crit, on both Turtle and Vmangos.

Please provide footage of tclap being able to crit from Classic or 2006 retail. Be sure to not include TBC info where this ability was edited.

**Comment by Huntshorde** [comment]
Yes I believe i have been miss lead by false information stating that thunderclap with arms impale and deep wounds work together, but after testing it out today I couldn't get it to work. I asked around in the city of other warriors have seen thunder clap crit and they all said yes. Which left me to keep trying.
________________________________
