### ISSUE TITLE
There is a bug of Chromie's Broken Pocket Watch in asia realm

### ISSUE THREAD

**Issue by kogomooow** [slowtorta/turtlewow-bug-tracker#5823]
**Please, provide a clear description what the bug is:**

**Steps to reproduce the behavior with as much detail as possible:**

1.In database of the turtlewow official website,it says
Equip: Improves your chance to hit with spells by 2%.
Equip: Your direct damaging spells have a 10% chance to increase your casting speed by 10% for 15 sec.
**but in asia realm it says "slow your casting speed by 10%"**
2. 
3. 

**IDs of affected creatures, items, quests or spells with a link to the relevant page:**

NPC: https://database.turtle-wow.org/?npc=
Item: https://database.turtle-wow.org/?item=
Quest: https://database.turtle-wow.org/?quest=
Spell: https://database.turtle-wow.org/?spell=
Object: https://database.turtle-wow.org/?object=

**Expected behavior. Describe how it should work:**

**Comment by twowTurtReynolds** [comment]
This will be fixed once SEA gets the patch 1.17.0 -> 1.17.1

**Comment by kogomooow** [comment]
thx for relpy
