### ISSUE TITLE
Can not bind a character to Auberdine Inn

### ISSUE THREAD

**Issue by Haggis3037** [slowtorta/turtlewow-bug-tracker#5824]
**Please, provide a clear description what the bug is:**
When trying to bind my char to the inn in Auberdine /Darkshore the Innkeeper plays the cast animation but does not bind me to this inn. Tried to destroy my Hearthstone to get a new one (like I had to do once in Vanilla Retail) which I did not get either. Opened a GM Ticket, GM spawned a new Hearthstone. Told me to delete my WDB Folder, which I did. Still cannot bind in Auberdine. Made the trip to Darnassus, binding there works. Back to Auberdine, still won't bind. One thing: The Bind Animation in Darnassus included like a "sprinkle" Animation which the one in Auberdine does not. Am not able to tell if the problem comes from the patch or just random.

**Steps to reproduce the behavior with as much detail as possible:**

1.Go to Auberdine
2. Talk to Innkeeper with option "Make this inn your home"
3. 

**IDs of affected creatures, items, quests or spells with a link to the relevant page:**

NPC: https://database.turtle-wow.org/?npc=6737
Item: https://database.turtle-wow.org/?item=
Quest: https://database.turtle-wow.org/?quest=
Spell: https://database.turtle-wow.org/?spell=
Object: https://database.turtle-wow.org/?object=

**Expected behavior. Describe how it should work:**
Talk to Innkeeper in Auberdine, with option "Make this inn your home"
Hearthstone bound in Auberdine.

**Comment by twowTurtReynolds** [comment]
![image](https://github.com/slowtorta/turtlewow-bug-tracker/assets/151180101/58385064-774a-4d75-bef2-70eb21644f12)
![image](https://github.com/slowtorta/turtlewow-bug-tracker/assets/151180101/ee35753e-752d-46e8-9fce-df9f8e1500a5)

I'm not sure how you are getting this problem. Maybe you have a mod or addon breaking the game.

**Comment by Haggis3037** [comment]
Hi, have something to add to the problem identification:

I brought my only char that was not there yet (Paladin) over to Auberdine, Binding worked as expected (including blue sparks in the animation).

Logged to my Rogue (Problem char) went back over there, tried to bind, nothing. Animation is played without the blue sparks, binding location does not change to Auberdine.

Seems to be a problem with only this character. Addons are the same as on the other chars so that is kinda unlikely. WDB deleted. The strange thing about this is that

when I drop the Hearthstone I will not get a new one from only this NPC (hence the GM ticket). Because that was the solution back some years ago in vanilla retail.

If there is anything I can help you to test just contact me.If you like to witness the problem Account: Haggis3037  Char: Ezreah

Keep up the good work and have a happy new year!

lg

 

Gesendet: Freitag, 29. Dezember 2023 um 18:12 Uhr
Von: "Turt Reynolds" ***@***.***>
An: "slowtorta/turtlewow-bug-tracker" ***@***.***>
Cc: "Haggis3037" ***@***.***>, "Author" ***@***.***>
Betreff: Re: [slowtorta/turtlewow-bug-tracker] Can not bind a character to Auberdine Inn (Issue #5824)


 

image.png (view on web)
image.png (view on web)

I'm not sure how you are getting this problem. Maybe you have a mod or addon breaking the game.

**Comment by twowTurtReynolds** [comment]
Is that rouge a gnome or something? Are we dealing with line of sight issues?

**Comment by Haggis3037** [comment]
Hi, it is indeed a gnome rogue. But I don't know about line of sight as I tried it in tons of different positions.

The problem has solved itself though, I bound in Astranaar and as I returned I was able to bind in Auberdine.

Strange issue...

Have a very happy new year,

Sincerely 
H

 
 

Gesendet: Samstag, 30. Dezember 2023 um 15:24 Uhr
Von: "Turt Reynolds" ***@***.***>
An: "slowtorta/turtlewow-bug-tracker" ***@***.***>
Cc: "Haggis3037" ***@***.***>, "Author" ***@***.***>
Betreff: Re: [slowtorta/turtlewow-bug-tracker] Can not bind a character to Auberdine Inn (Issue #5824)


 

Is that rouge a gnome or something? Are we dealing with line of sight issues?

**Comment by twowTurtReynolds** [comment]
That's odd, I'll tinker around with it.

Have a goodie
