### ISSUE TITLE
Small bug in the map of Tirisfal Glades, missing structure in the map

### ISSUE THREAD

**Issue by Scarecrow4012** [slowtorta/turtlewow-bug-tracker#5825]
**Please, provide a clear description what the bug is:**
As you know, closer to the Scarlet Monastery is the Scarlet Citadel, that area is usually marked in the map, but I noticed it dissapears in unknown conditions. Usually after leaving the area.
**Steps to reproduce the behavior with as much detail as possible:**

1.  Log in and don't leave the area, look in the map of Tirisfal Glades and sometimes you will be able to see the Scarlet Citadel drawn in the map
2.  Leave the area, I tried it with Western Plaguelands
3.  Look in the map and the Scarlet Citadel dissapeared from the map
4.  This is an aproximate of what steps I followed

**IDs of affected creatures, items, quests or spells with a link to the relevant page:**
Map of Tirisfal Glades

**Expected behavior. Describe how it should work:**
The map don't changes for nothing.

Screenshot of the map and I marked the area without the structure.
![turtlewow_tirisfal_uplands](https://github.com/slowtorta/turtlewow-bug-tracker/assets/83896155/8708543c-f239-46ee-bdb1-e0f256b3a4d4)
![turtlewow_tirisfal_uplands](https://github.com/slowtorta/turtlewow-bug-tracker/assets/83896155/7cf936ca-77f1-4b7f-b65f-46d0090834b7)

https://drive.google.com/file/d/1cVAHtwSahg5FJU-U3zGmVCNQwpYneSg1/view?usp=sharing
https://drive.google.com/file/d/1BjYJGAaUEoRdR5_JH87yO0a4KBZlBq4-/view?usp=drive_link

**Comment by twowTurtReynolds** [comment]
No matter where I go around the zone, I cannot get the icon to dissappear. It is possible that you have addon or WDB issues to sort out.

The only issues I could find were the lack of icon on partial discover:
![image](https://github.com/slowtorta/turtlewow-bug-tracker/assets/151180101/6f33d6c7-50b5-4826-975a-70b924fbb9be)
![image](https://github.com/slowtorta/turtlewow-bug-tracker/assets/151180101/f92ccda5-6860-4ef3-b312-d2721ea9c65c)

**Comment by Scarecrow4012** [comment]
I will not open the issue again cause it's not a big problem, I mean, even that zone IDK if has an use so, it's not important, but I made a video showing how...it ocurs, I don't have addons or something like that, it happens to me for no reason, so, it's curious.

Sorry for the link, Github says it's too big and the program filmed it in an unsupported format, OBS filmed it .MKV.

https://drive.google.com/file/d/1srnPU9OZk3GV1ieZ4ZleBNtkhNkjbY-4/view?usp=sharing

**Comment by twowTurtReynolds** [comment]
Oh, You're right, by standing in WPL I can see the issue.
![image](https://github.com/slowtorta/turtlewow-bug-tracker/assets/151180101/79eec982-1a25-47c2-9375-62ef4c33f171)
