### ISSUE TITLE
Add the new races to the PvP Message in the interface.

### ISSUE THREAD

**Issue by Scarecrow4012** [slowtorta/turtlewow-bug-tracker#5826]
**Please, provide a clear description what the bug is:**
When you enable or enter in PvP, a small banner appears in your portrait, when you pass your mouse over it, a small message displays in a corner, that message tolds you what races are opposed to your faction, that message don't mentions the new races, add them.
**Steps to reproduce the behavior with as much detail as possible:**
1.Enter in PvP and a banner will appear
2.Pass your mouse over the banner
3. A small message will appear in a corner

**IDs of affected creatures, items, quests or spells with a link to the relevant page:**
No one.

**Expected behavior. Describe how it should work:**
The message needs to say this:
Alliance: "A proud member of the Alliance, opposed to members of the Horde (Orcs, Trolls, Tauren, Undead and Goblins)"
Horde: "A proud member of the Horde, opposed to members of the Alliance (Humans, Dwarfs, Gnomes, Night Elves and High Elves)"

Screenshot of what I say:
![image](https://github.com/slowtorta/turtlewow-bug-tracker/assets/151180101/bd06579c-e629-492a-8d96-718dd51d9c43)

**Comment by twowTurtReynolds** [comment]
Just a quick note, you can paste your screenshots into github instead of google drive, makes it nicer for everyone.

**Comment by luskanek** [comment]
Fixed. The change will be applied in the next client patch.
