### ISSUE TITLE
Death Talon Hatcher is Incorrectly able to be Distracted

### ISSUE THREAD

**Issue by OonaFae** [slowtorta/turtlewow-bug-tracker#5830]
**Please, provide a clear description what the bug is:**
Death Talon Hatchers in Suppression Room should be immune to Distract, however they are not
**Steps to reproduce the behavior with as much detail as possible:**

1. Go the the Suppression Room in BWL
2. Use Distract on a Death Talon Hatcher
3. Watch them be affected by the spell

**IDs of affected creatures, items, quests or spells with a link to the relevant page:**

NPC: https://database.turtle-wow.org/?npc=12468
Spell: https://database.turtle-wow.org/?spell=1725

**Expected behavior. Describe how it should work:**
The mob should be immune to distract

**Comment by twowTurtReynolds** [comment]
Please provide proof from classic or 2006 retail to support whether this is intended or not.

**Comment by OonaFae** [comment]
Classic allows it but I dont recall this being accurate to actual vanilla, looking through some old forums and videos trying to find an instance to confirm if that's accurate. 👍

**Comment by OonaFae** [comment]
Didn't take me as long as I thought it would to prove that this is correct and that my memory is wrong.
If anyone asks
https://youtu.be/J-vmaNUGV-Y?t=96
