### ISSUE TITLE
Blackwing Spellbinder is incorrectly stunnable

### ISSUE THREAD

**Issue by OonaFae** [slowtorta/turtlewow-bug-tracker#5832]
**Please, provide a clear description what the bug is:**

**Steps to reproduce the behavior with as much detail as possible:**

1. Use Physical based stun ability (Cheap Shot, Kidney Shot, Intercept) on Blackwing Spellbinder
2. It gets stunned

**IDs of affected creatures, items, quests or spells with a link to the relevant page:**

NPC: https://database.turtle-wow.org/?npc=12457
Spell: https://database.turtle-wow.org/?spell=8643
Spell: https://database.turtle-wow.org/?spell=1833
Spell: https://database.turtle-wow.org/?spell=20617

**Expected behavior. Describe how it should work:**
Mob should be immune to stun

**Comment by balakethelock** [comment]
Not a bug. He's supposed to be stunnable and was incorrectly immune to stuns before.

**Comment by OonaFae** [comment]
I dont recall these being stunnable on classic. But maybe im misremembering. I’ll reopen if i find more info
