### ISSUE TITLE
<error> system message

### ISSUE THREAD

**Issue by AKryukov92** [slowtorta/turtlewow-bug-tracker#5833]
**Please, provide a clear description what the bug is:**
Sometime system message looks like "<error>".
Recent was 30 january 2023 07:47:39 UTC
![image](https://github.com/slowtorta/turtlewow-bug-tracker/assets/24266616/65221edd-9724-4ac2-8896-3feaaefaf6d1)

**Steps to reproduce the behavior with as much detail as possible:**

1. Wait for message to appear

**Expected behavior. Describe how it should work:**
I think there should be some important information.

**Comment by AkalixFrost** [comment]
Internal note posted to Production task board on possible associated issue.
