### ISSUE TITLE
Cross faction ress in dungeons

### ISSUE THREAD

**Issue by Volkyte** [slowtorta/turtlewow-bug-tracker#5834]
**Please, provide a clear description what the bug is:**
Cross faction ress in dungeon not working
**Steps to reproduce the behavior with as much detail as possible:**

1.roll alliance
2. go in dungeon with horde
3. when you die you cannot be rezzed 
4. 

**IDs of affected creatures, items, quests or spells with a link to the relevant page:**

**Expected behavior. Describe how it should work:**
Happened in all leveling range since 1.7 came out. Died in many dungeons but, where I was the only ally pg and the other 4 firends hoirde, i could not be ressed as was given (invalid target) if rezzable or impossible to resss if I released spirit.

**Comment by Haaxor1689** [comment]
If you don't release then you can be ressed normally. Not being able to xfaction ress after releasing is a known issue though and not fixable as far as we know as of now.

**Comment by Volkyte** [comment]
also without ressing issue persists.

**Comment by Haaxor1689** [comment]
you mean without releasing right?

**Comment by Volkyte** [comment]
> you mean without releasing right?

tested, as per text said, with release and without release. each times healer demed impossible to rezz

**Comment by twowTurtReynolds** [comment]
![image](https://github.com/slowtorta/turtlewow-bug-tracker/assets/151180101/0718a4be-c0b8-4d64-8b23-9048dd9754bc)
![image](https://github.com/slowtorta/turtlewow-bug-tracker/assets/151180101/215f7b3b-9d34-41fe-91a1-5a66a5b4bb12)

I can't replicate. Perhaps you have mod or addon issues.

If you can find different specific replication steps I can try, let me know.
