### ISSUE TITLE
NPC: Snowball

### ISSUE THREAD

**Issue by cyaohiri** [slowtorta/turtlewow-bug-tracker#5835]
It seems like Snowball can be pulled outside of the cave, and since he has an AoE ability, he can kill nearby players.
![image](https://github.com/slowtorta/turtlewow-bug-tracker/assets/86041826/e34e629b-065b-454d-a833-fe704831254d)

There also seems to be a general issue with the line of sight check of his volley ability.
![image](https://github.com/slowtorta/turtlewow-bug-tracker/assets/86041826/5ee27a55-e1dc-486c-a353-4f8d75879335)
![image](https://github.com/slowtorta/turtlewow-bug-tracker/assets/86041826/df866839-3f54-446f-9be2-77074560ea76)

The range of Snowball's volley should be fixed and make sure it checks for line of sight.
Given the existence of the hardcore challenge, Snowball should probably not be kiteable beyond the cave,
Based on the screenshot, it's not clear whether he was kited outside, or his volley just has a very large range and ignores the line of sight.

NPC: https://database.turtle-wow.org/?npc=50112

**Comment by twowTurtReynolds** [comment]
We saw the report from last night as it came in, and added a leash to Snowball last night. He shouldn't be able to target anyone outside the cave now.
