### ISSUE TITLE
Quest A Little Slime Goes a Long Way

### ISSUE THREAD

**Issue by Kelintor** [slowtorta/turtlewow-bug-tracker#5840]
(1) NPC: https://database.turtle-wow.org/?npc=7086
(2) Item: https://database.turtle-wow.org/?item=11914
(3) Quest: https://database.turtle-wow.org/?quest=4512
(4) Spell: https://database.turtle-wow.org/?spell=15698
(5) https://database.turtle-wow.org/?item=11947

I found a problem with quest (3)

When u use item (2) on correct target npc (1), and u inventory full, the item (5) created to abyss. and u lost original item (2).
That means u need to go back to IF and retake quest

i think spell (4) must have "inventory full error" condition like most items with that mecanics.

**Comment by ratkosrb** [comment]
Should be fixed in the next update.
