### ISSUE TITLE
Issue with quest "Craftsman's Writ" (quest 9142 - with screenshot)

### ISSUE THREAD

**Issue by koontz946** [slowtorta/turtlewow-bug-tracker#5842]
**Please, provide a clear description what the bug is:**
When trying to start the quest "Craftsman's Writ", I get the message "The item was not found." while the "quest completed" music plays.

**Steps to reproduce the behavior with as much detail as possible:**

1. Talk to Dispatch Commander Metz, select (? Craftsman's Writ) as it is the only option
2. Next dialog box comes up, saying "You will receive (Sealed Craftsman's Writ)." Click (Complete Quest).
3. Red text appears stating "The item was not found." while the "quest completed" music plays. The dialog window stays open and no matter how many times I click (Complete Quest), the red text keeps appearing, and nothing is put in my inventory.

**IDs of affected creatures, items, quests or spells with a link to the relevant page:**

NPC: https://database.turtle-wow.org/?npc=16212
Item: https://database.turtle-wow.org/?item=22568
Quest: https://database.turtle-wow.org/?quest=9142

**Expected behavior. Describe how it should work:**
How it should work is I click (Complete Quest), and get (Sealed Craftsman's Writ) in my inventory.

Character affected is Linissa on Tel'Abim

Screenshot attached per previous request; all addons disabled, WDB folder write-protected, and bags not full.
<img width="730" alt="itemnotfound" src="https://github.com/slowtorta/turtlewow-bug-tracker/assets/148662006/60da6572-59e3-499e-bc18-058f78b13cf1">

**Comment by twowTurtReynolds** [comment]
Please do not create duplicate tickets.
