### ISSUE TITLE
I have an issue opening a Winter Veil Gift Box

### ISSUE THREAD

**Issue by nekoccino93** [slowtorta/turtlewow-bug-tracker#5844]
**Please, provide a clear description what the bug is:**

I have an issue opening a Winter Veil Gift Box. I right-clicked the item and saw Red Winter Hat but when I clicked to claim it nothing happened. I contacted a GM in game and they advised me to delete the WDB folder. When I logged back in game I tried opening the Winter Veil Gift Box again. This time I can see a Green Winter Vest but again I nothing happens when I click to claim it.

**Steps to reproduce the behavior with as much detail as possible:**

1. Try to open Winter Veil Gift Box
2. Try to claim the item inside
3. Nothing happens

**IDs of affected creatures, items, quests or spells with a link to the relevant page:**

Item: https://database.turtle-wow.org/?item=51060

**Expected behavior. Describe how it should work:**
Item inside Winter Veil Gift Box goes into player inventory.

![image](https://github.com/slowtorta/turtlewow-bug-tracker/assets/155269498/ea0fac7f-6996-43fb-8b2f-4c5e1d8decb6)

**Comment by twowTurtReynolds** [comment]
![image](https://github.com/slowtorta/turtlewow-bug-tracker/assets/151180101/0cc26f7b-066c-4aff-a6cd-38139812d797)
I can't replicate this. Something is wrong with your client setup. Try a fresh client.
