### ISSUE TITLE
Shard of the Gods set bonus 

### ISSUE THREAD

**Issue by buggie344** [slowtorta/turtlewow-bug-tracker#5845]
**Please, provide a clear description what the bug is:**
The set bonus from Shard of the Gods applies only 3 mp5 instead of 8 mp5.

**Steps to reproduce the behavior with as much detail as possible:**

Equip the set and check the mp5 in settings.

![Screenshot 2023-12-30 230153](https://github.com/slowtorta/turtlewow-bug-tracker/assets/155270779/c12c44e5-55a8-4cd2-bd0a-43ceaedb9a9b)

![Screenshot 2023-12-30 230235](https://github.com/slowtorta/turtlewow-bug-tracker/assets/155270779/94430c7c-58e6-439e-b78f-809835cb0f8d)

**IDs of affected creatures, items, quests or spells with a link to the relevant page:**

Item: https://database.turtle-wow.org/?item=17064
Item: https://database.turtle-wow.org/?item=17082

**Expected behavior. Describe how it should work:**

It should work as read in the description.

**Comment by buggie344** [comment]
![Screenshot 2023-12-30 230322](https://github.com/slowtorta/turtlewow-bug-tracker/assets/155270779/e2c99f0a-5d9c-4a57-9659-798a68f9d97c)

**Comment by twowTurtReynolds** [comment]
That addon is not a source of truth. Do not report addon bugs to the server tracker.
