### ISSUE TITLE
Follow up quest of the quest chain "The Black Shield" can't be picked up.

### ISSUE THREAD

**Issue by mentalxgit** [slowtorta/turtlewow-bug-tracker#5848]
**Did the quest chain "The Black Shield" up to the part https://database.turtle-wow.org/?quest=1323
The follow up quest https://database.turtle-wow.org/?quest=1276 isn't available.**

The quest chain can't be finished.

I tried restart and restart with disabled addons. The WDB folder is permanently deleted.
pfQuest shows that Krog should have the quest to pick up.

Thanks in advance. :)

**Comment by twowTurtReynolds** [comment]
Indeed.
![image](https://github.com/slowtorta/turtlewow-bug-tracker/assets/151180101/9dbebe32-b073-4275-9175-e2588abd109e)

**Comment by ratkosrb** [comment]
Should be fixed in the next update.
