### ISSUE TITLE
Essence of the Elements keeps on dropping even after quest completion.

### ISSUE THREAD

**Issue by Teknishun7** [slowtorta/turtlewow-bug-tracker#5849]
Essence of the Elements keeps on dropping even after quest completion.

The fire elementals inside BRD kept dropping the quest item even after quest completion and logging out.
Keeps dropping on every subsequent runs.

The essence of element should stop dropping after quest completion.

Fire elemental mob: 
https://database.turtle-wow.org/?npc=8909
https://database.turtle-wow.org/?npc=8910
https://database.turtle-wow.org/?npc=8911

Quest item: https://database.turtle-wow.org/?item=11129

Quest: https://database.turtle-wow.org/?quest=7201

**Comment by twowTurtReynolds** [comment]
![image](https://github.com/slowtorta/turtlewow-bug-tracker/assets/151180101/e0f7f3d5-eba9-4bb1-a8d3-ef62ef274557)
Then I killed some more mobs:
![image](https://github.com/slowtorta/turtlewow-bug-tracker/assets/151180101/a1a144bc-b3cb-407e-8a21-c4d8cfb0f44b)
![image](https://github.com/slowtorta/turtlewow-bug-tracker/assets/151180101/fc881ada-6e91-4c55-a591-4a7417c93c57)
![image](https://github.com/slowtorta/turtlewow-bug-tracker/assets/151180101/7d4efdd5-3be4-44fc-9a7a-cb7d3d389ab9)

I can't replicate. Try with a fresh client if you have to.

Maybe you have a bugged second instance of the quest on your character? Do you see it in your quest log with no addons? If not, a GM could run `.quest remove 7201` on you I believe, but I've never seen this bug happen to anyone ever before, so I'm not sure why this would be necessary.
