### ISSUE TITLE
Rogue - cold blood + eviscaret

### ISSUE THREAD

**Issue by 10gambler10** [slowtorta/turtlewow-bug-tracker#5852]
Hello ! 
It is not the first time eviscerate not critting with cold blood . It should be 100% crit with 1-2-3-4-5 combo points , and i saw it many times not critting . Please check and fix it , thank you 
https://database.turtle-wow.org/?spell=14177

**Comment by twowTurtReynolds** [comment]
![image](https://github.com/slowtorta/turtlewow-bug-tracker/assets/151180101/e623476a-85b8-4a88-9362-bc12f4d83da1)
I cannot replicate.

**Comment by 10gambler10** [comment]
yes. 90-95% its work but sometimes doesnt. Mainly in PvP .

**Comment by twowTurtReynolds** [comment]
Can you show a picture of the combat log where it is not working?

**Comment by cyaohiri** [comment]
Keep in mind you lose Cold Blood even if the attack does not land, i.e. it misses or is dodged.
