### ISSUE TITLE
Cannot use Blacksmithing [Bloody Belt Buckle] to other player's Belt on trade window

### ISSUE THREAD

**Issue by rubixluffy** [slowtorta/turtlewow-bug-tracker#5854]
**Cannot use Blacksmithing [Bloody Belt Buckle] to other player's Belt on trade window**
Error Message: You can only use this item on yourself. 

I don't know what exactly the English error message is, cause I'm using Chinese client, I'm on Asia Server. So I just translate the Chinese error message to English "You can only use this item on yourself".

**Steps**
1. Mouse right click the item [Bloody Belt Buckle], just like using other Belt Buckles.
2. Let the other player trade me, put his Belt on the buttom slot to wait for me to use  [Bloody Belt Buckle] on it's Belt.
3. Mouse left click on the Belt. Error messages shows: You can only use this item on yourself.

**Expected behavior**
It should work just like other Belt Buckles.

**Comment by twowTurtReynolds** [comment]
This was fixed in 1.17.1, which SEA hasn't gotten yet. Soon.
