### ISSUE TITLE
Quest | Thalassian Highlands - No Shortcut to Salvation cannot complete

### ISSUE THREAD

**Issue by dan-nunley** [slowtorta/turtlewow-bug-tracker#5855]
**Please, provide a clear description what the bug is:**
When attempting to complete 'No Shortcut to Salvation', there is no indication of where of the Felstone is. Aeltalor Flameshard does not spawn

**Steps to reproduce the behavior with as much detail as possible:**

1. Go to area on Island of Eternal Autumn
2. Go to area with Feltone / Aeltalor Flameshard spawn point
3. NPC does not spawn / felstone not available for pickup

**IDs of affected creatures, items, quests or spells with a link to the relevant page:**

NPC: https://database.turtle-wow.org/?npc=61895
Item: https://database.turtle-wow.org/?item=41209
Quest: https://database.turtle-wow.org/?quest=41267
Spell: https://database.turtle-wow.org/?spell=
Object: https://database.turtle-wow.org/?object=

**Expected behavior. Describe how it should work:**
Cannot find NPC at given location point, NPC not spawning

**Comment by twowTurtReynolds** [comment]
The quest text does tell you what to find and where. I found this npc without the help of the database. He has a minute respawn timer which is appropriate.
