### ISSUE TITLE
Hateforge Chemist has no cloth and scraps loot

### ISSUE THREAD

**Issue by AKryukov92** [slowtorta/turtlewow-bug-tracker#5858]
**Please, provide a clear description what the bug is:**
Loot table of Hateforge Chemist is different from any other Hateforge mobs.
They don't drop Runecloth, Dark iron scraps and scrolls.

**Steps to reproduce the behavior with as much detail as possible:**

1. Kill dozen of Hateforge Chemists
2. Loot them
3. 

**IDs of affected creatures, items, quests or spells with a link to the relevant page:**
[Hateforge Chemist](https://database.turtle-wow.org/?npc=60717)

**Expected behavior. Describe how it should work:**
Hateforge Chemist should drop cloth, dark iron scraps and scrolls.

**Comment by ratkosrb** [comment]
Should be fixed in the next update.
