### ISSUE TITLE
Inaccessible Copper Vein in Durotar on Tel'Abin at 60.1, 61.8

### ISSUE THREAD

**Issue by Sagragoth** [slowtorta/turtlewow-bug-tracker#5859]
Durotar, inaccessible Copper Vein at 60.1, 61.8, on Tel'Abim.

Visited at 5:40 PM EST on 12/31/23, appears to be below ground.  You can get the mouse cursor to change at certain angles but it's always too far away to interact with, so may be deep underground.

 Object: (https://database.turtle-wow.org/?object=1731)

**Comment by twowTurtReynolds** [comment]
![image](https://github.com/slowtorta/turtlewow-bug-tracker/assets/151180101/93e82207-1b63-4294-958c-b87db614a498)
Here? I don't see a node here on the PTR.

**Comment by balakethelock** [comment]
> Here? I don't see a node here on the PTR.

Nodes are pooled so that not all are up at the same time in the zone.
