### ISSUE TITLE
Silvermoon Remnant Quartermaster (items being sold by the Alliance cloth quartermaster) 

### ISSUE THREAD

**Issue by Simanba** [slowtorta/turtlewow-bug-tracker#5862]
Before the 1.17.1 patch there used to be two Quartermasters  of the silvermoon remnants who both sold reputation gear (one for weapons and the other for armor if i remember correctly?

 Currently there is only Soalara Dawnstar. As a paladin I can only buy weapons of her and no plate gear. A look in the database shows that she only sells weapons and the mail gear.. The plate cloth and leather gear seem to be sold by the alliance cloth quartermaster in Alah'Thalas. Unsure whether this is how it is supposed to be? 
The weapon quartermaster and mail gear.
Soalara Dawnstar <Silvermoon Remnant Quartermaster>
https://database.turtle-wow.org/?npc=80266
The npc that used to sell gear/cloaks 
Amanaria Sunblade <Silvermoon Remnant Quartermaster>
https://database.turtle-wow.org/?npc=80240
the current npc that sells the gear/cloaks 
Alinerenah Sunsparrow <Alliance Cloth Quartermaster> 
https://database.turtle-wow.org/?npc=80459

perhaps an idea is to  add all gear repuation gear to soalara dawnstar. a Cloth quartermaster selling silvermoon remnant gear feels out of touch?

**Comment by Dragunovi** [comment]
These items were intentionally removed.
