### ISSUE TITLE
Logic error in Stormwind Gate

### ISSUE THREAD

**Issue by Scarecrow4012** [slowtorta/turtlewow-bug-tracker#5864]
**Please, provide a clear description what the bug is:**
I know that this will be more of a suggestion than an error, since this is an error on Blizzard's part that few have noticed but that, for me personally, since I saw it, it causes me OCD.
At the entrance of Stormwind in the Merchant District, you will have noticed that there is a strange void above, as if it led to nothing, I know that in Vanilla the cities themselves did not exist together with the world and that is why they did various tricks so that It could be seen, well, there is an error, if you notice from the Valley of Heroes you can see a building with a blue roof over the doors, but when entering the City, that building is absent, I think it would help the immersion to place it on the other side side also for two reasons, 1. To hide that there is nothing loaded on the other side 2. to give a prettier view of that entrance.

**Steps to reproduce the behavior with as much detail as possible:**
Not much
1. Go to the Valle of Heroes, and you will see that building over the Gates, in the middle of the Towers.
2. Enter to the Trade District and that Building is missing.

**IDs of affected creatures, items, quests or spells with a link to the relevant page:**
Well...nothing, it's not an entity, object or quest.

**Expected behavior. Describe how it should work:**
The building can be seen in the two sides.

I'm sorry if this cannot be here, I saw you removed the Mountain that was bugging the Stormwind Keep, so It's only a suggestion for keep making the City better.
![WoWScrnShot_010124_105639](https://github.com/slowtorta/turtlewow-bug-tracker/assets/83896155/ae771119-8d79-4dbb-b6d6-dc3102e85446)
![WoWScrnShot_010124_104830](https://github.com/slowtorta/turtlewow-bug-tracker/assets/83896155/f341cca6-f4b5-450f-9bf3-c28faf0ac39d)

**Comment by twowTurtReynolds** [comment]
https://forum.turtle-wow.org/viewforum.php?f=14
