### ISSUE TITLE
Additional Defias mobs spawn in front of the house while doing the quest "Tome of Valor"

### ISSUE THREAD

**Issue by mentalxgit** [slowtorta/turtlewow-bug-tracker#5865]
**While helping a new player with the Paladin quest ( https://database.turtle-wow.org/?quest=1651 ) something happend that I never happened before:
The quest was started and the waves of Defias come from the path that leads to the house of Daphne Stilwell ( https://database.turtle-wow.org/?npc=6182 ) in Westfall. But while fighting the usual mobs, more and more Defias mobs spawned directly in front of the house. It continued for quite a while. Probably 5-10 Mobs**

**Comment by twowTurtReynolds** [comment]
Did you accept the quest twice really fast or something? I can't replicate.
![image](https://github.com/slowtorta/turtlewow-bug-tracker/assets/151180101/58da43aa-960f-4d2e-9ea8-1168bf925471)

**Comment by mentalxgit** [comment]
I did only help with the quest. The odd thing was that the additional Defias appeared around the spot where you are standing. Not like the Raiders on your screenshot. Maybe a hiccup.

The Paladin that startet the quest is a very new turtle, so i thought I do the task of posting the issue.

**Comment by twowTurtReynolds** [comment]
I tried again with 2 accounts, yeah I can't replicate this. If you do figure out replication steps, do let us know.
