### ISSUE TITLE
Arcane Missiles

### ISSUE THREAD

**Issue by LeonardoPfister** [slowtorta/turtlewow-bug-tracker#5866]
Hi there Turtle wow team.

Sometimes when i try to cast Arcane Missiles it wont let me. Instead it says "Spell not Ready" or "Invalid Target".
I then can switch to Frost bolt or any other cast and it works just fine. After some time it will even let me cast Arcane Missiles again.

I did make sure that i am not locked in Arcane. So i am still able to cast Arcane Explosion.
And i am not Silenced at all. I am not spaming the Buttens either.
I dont use it in a macro and i tryed different buttens as well. 

I can not realy replicate it since it seems to "just happen".  But it happens a lot, to me at least. 

Thank you in advanced for looking in to it.

**Comment by twowTurtReynolds** [comment]
A few weeks ago on the PTR I was testing arcane missiles for maybe 20 minutes. It never did this to me. Nor can I get it to do this for me after 2 mins of testing right now.

Try with a fresh client, with no addons or mods which very well can cause this problem, and if it still occurs for you, see if you can figure out what exactly is the difference, what exact step is needed to replicate, and get some footage too. Reply to me then and I can take another look.

**Comment by LeonardoPfister** [comment]
Hi Reynolds

Thank you for looking into it. I testet it a bit more and i got now a workaround for me.

What i have seen so far it never hapens on target dummys or when i am on my on only in Dungeons or Raids. And if it happens now i target me and the boss/mob again and then i can cast Missiles again.

**Comment by cyaohiri** [comment]
If you switch in and out of the game with Alt+Tab, make sure to press Alt one more time when you switch back into the game because sometimes it can get stuck pressed down, and casting a spell will try to cast it on yourself, as Alt forces your spells to be cast on yourself.
This might not be the only cause, but it's worth keeping in mind.

**Comment by twowTurtReynolds** [comment]
Indeed, this doesn't sound like anything that can be fixed by us but just how you use the client.
