### ISSUE TITLE
Firebrand Grunt Mark of Flames

### ISSUE THREAD

**Issue by Otari98** [slowtorta/turtlewow-bug-tracker#5867]
Firebrand Grunts in LBRS (https://database.turtle-wow.org/?npc=9259#abilities) have weird thing going on with theirs spells. They cast [Mark of Flames](https://database.turtle-wow.org/?spell=15128) then they do a [Mortal Strike](https://database.turtle-wow.org/?spell=13737) which CONSUMES 1 STACK OF Mark of Flames.
Mortal Strike should not interract with mark of flames. 
https://www.youtube.com/watch?v=nLQxzOrebdk

**Comment by twowTurtReynolds** [comment]
![image](https://github.com/slowtorta/turtlewow-bug-tracker/assets/151180101/552dacd6-d0e9-4a01-a723-29b38bc9b1bd)

Please provide blizzlike proof that this is incorrect.

**Comment by Otari98** [comment]
Ok so i found 3 videos from classic 
https://youtu.be/h_yB_z6-7ts?t=1765
https://youtu.be/pnOM3mBlTa0?t=3001
https://youtu.be/qUeh_vws5YE?t=1318
in first clip druid tank gets marks from one mob, then that mob dies and then tank gets mortal strike and marks do not disappear
in second clip tank gets debuff and then gets mortal strike right after from the same mob and it disappears
third clip same as second - tank gets marks and then mortal strike removes it
i couldn't find any other clips of people taking these debuffs so idk

**Comment by twowTurtReynolds** [comment]
In the first clip, he never gets mark of flames until the end, where he isn't mortal striked again. You might have mistaken the Curse for the Magic mark.

But yeah, the 2nd and 3rd clips prove that this feature we see here is working as intended. I would never have thought that this weird behavior is actually blizzlike!

Thank you for digging up the videos, we do appreciate the help solving these cases.
