### ISSUE TITLE
Greatfather winter NPC not moved on nordanar.

### ISSUE THREAD

**Issue by ghost** [slowtorta/turtlewow-bug-tracker#5869]
The quest NPC "Greatfather winter" was supposed to be moved to a new location at Northgate outpost but remains in the same location that is inaccessible to horde characters.  He has been moved on the PvP server only.
https://database.turtle-wow.org/?npc=61171
https://database.turtle-wow.org/?quest=40783

**Comment by Shellyoung** [comment]
Dude I beg you give me a location of him on PvP server!
