### ISSUE TITLE
Survival skill bugged my character ?  

### ISSUE THREAD

**Issue by Crewcabanger** [slowtorta/turtlewow-bug-tracker#587]
**Please, provide a clear description what the bug is:**

**Steps to reproduce the behavior with as much detail as possible:**

1.i Was making torches for survival skilling and in my inventori apeared fo every torch  one question mark item , 
2. after that mi characteter  disapeared from monitor , and in character prewiev  is all white like a texture or something...
3. 

**IDs of affected creatures, items, quests or spells with a link to the relevant page:**

NPC: https://database.turtle-wow.org/?npc=
Item: https://database.turtle-wow.org/?item=
Quest: https://database.turtle-wow.org/?quest=
Spell: https://database.turtle-wow.org/?spell=
Object: https://database.turtle-wow.org/?object=

**Expected behavior. Describe how it should work:**

**Comment by Crewcabanger** [comment]
Hello devs , it seems my character buged while playing after patch realeased , cant see ma character after a few restarts , reloads , it doesnt change  when my friend loged from another PC , i was lvling survival skill and making torches , in inventory for every torch i made,  appeared  another item with question mark icon , it canot be  deleted , destroyed .... cant help myself i think.

**Comment by Crewcabanger** [comment]
WDB files  deleting doesnt help , restarting doesnt help, new client doesnt help , old patchet client doesnt help

**Comment by jameyboor** [comment]
Fixed.
