### ISSUE TITLE
Barkskin Pendant (quest item) can be looted with no Barkskin Vengeance quest in quest log

### ISSUE THREAD

**Issue by Shellyoung** [slowtorta/turtlewow-bug-tracker#5871]
**Please, provide a clear description what the bug is:**
[Barkskin Pendant](https://database.turtle-wow.org/?item=61442) and maybe more can be looted from [Barkskin furbolgs](https://database.turtle-wow.org/?item=61442#dropped-by) at Barkskin Village in Hyjal with no [Barkskin Vengeance](https://database.turtle-wow.org/?quest=40893) quest in quest log.

![Untitled-1](https://github.com/slowtorta/turtlewow-bug-tracker/assets/40469927/c1d8cca9-8d0e-44fd-a26a-893a7e3a0bda)

There are also other quest items that drop with no appropriate quest in quest log: Great Beak, Misthoof Hide. Maybe more.

**Steps to reproduce the behavior with as much detail as possible:**
1. Go to Barkskin Village in Hyjal
2. Kill one of the Barkskin clan furbolgs
3. Loot [Barkskin Pendant](https://database.turtle-wow.org/?item=61442).

**IDs of affected creatures, items, quests or spells with a link to the relevant page:**
Item: https://database.turtle-wow.org/?item=61442
Quest: https://database.turtle-wow.org/?quest=40893

**Expected behavior. Describe how it should work:**
All quest items should drop only if you have a quest.

**Comment by balakethelock** [comment]
Not a bug. This is a repeatable turn in quest, the items can be looted without being on it.
https://forum.turtle-wow.org/viewtopic.php?p=73511&hilit=hyjal#p73511:~:text=for%20details.-,We%27ve,-heard%20your%20feedback

**Comment by Shellyoung** [comment]
Why don't make it not a quest item?

**Comment by Shellyoung** [comment]
Okay
