### ISSUE TITLE
A living druid after death

### ISSUE THREAD

**Issue by Bogdandengi** [slowtorta/turtlewow-bug-tracker#5872]
1. While in bear form, activate the berserk ability.
2. When health is low and the berserk ability expires, press exit from the bear form.
3. You will get a dead character who cannot move or use abilities, but is still being attacked by enemies.
4. Aggro is retained, which can be used in raids if desired and skillful.
5. All buffs on the character are saved.
6. The character's mana has been restored.
7. It was possible to change weapons.

**The druid "berserk" ability in the feral talent branch is not in the classic version of the game, which is probably why I couldn't find a reference to it on your site.

**Obviously the character is supposed to die, especially when you confirm the command to resurrect in the graveyard. But he is still being attacked by enemies for some reason. 
I was only able to exit the dungeon by force closing the game.

My nickname in the game Bogest I will be glad if you fix this bug.
![1](https://github.com/slowtorta/turtlewow-bug-tracker/assets/132904763/6c0c2a36-adf0-437b-a517-d64725d59a8a)
![2](https://github.com/slowtorta/turtlewow-bug-tracker/assets/132904763/6f3f3677-d359-4bbc-9c01-c431a5a54c2b)
![4](https://github.com/slowtorta/turtlewow-bug-tracker/assets/132904763/213ffbfb-133a-42ee-9d47-e0f9d924934b)
![5](https://github.com/slowtorta/turtlewow-bug-tracker/assets/132904763/b58626e0-26cf-4f76-9126-c5068a5eb51d)

**Comment by ratkosrb** [comment]
Can you record it on video? I'm not able to reproduce it following the instructions.

**Comment by Bogdandengi** [comment]
Need just have +-400 hp for do this.
https://github.com/slowtorta/turtlewow-bug-tracker/assets/132904763/7ec69044-dd8d-4bdc-a52f-840133b4864e


https://github.com/slowtorta/turtlewow-bug-tracker/assets/132904763/1de50cdd-11a5-43eb-9445-9bfbf8300b0b

**Comment by Bogdandengi** [comment]
https://github.com/slowtorta/turtlewow-bug-tracker/assets/132904763/bcbe8ae2-312e-45cb-9ec0-aeaf71e3c744

**Comment by Bogdandengi** [comment]
https://github.com/slowtorta/turtlewow-bug-tracker/assets/132904763/9861dfc1-e0f8-4d8f-a6de-34f2c9e9c1c8

**Comment by twowTurtReynolds** [comment]
I have no idea how or why you are experiencing this. You can see me clicking off bear and berserk when I had under 400 HP here, and no, I cannot replicate. 
![image](https://github.com/slowtorta/turtlewow-bug-tracker/assets/151180101/b3e16203-8f28-47ae-87e5-f949d81a5d07)
I've spent maybe 30 minutes on trying to attempt this.

How long did it take _you_ to get that footage? Can you try with a fresh client and then see?

**Comment by Bogdandengi** [comment]
What do you mean by a fresh client? Do I need to remove all addons?

This is the first time this happened for me specifically in stratholm. The
other time it happened in PvP mode on alterac, but also with NPCs.
Apparently I just wanted to get out of the form and squeeze the health
potion. But in the end this bug happened.

I tried different options. The last time I managed to reproduce it after 5
attempts. The problem is that the ability has a cd of 6 minutes and there
is no way to try all the time.
I don't fully understand the reason for this myself. However, I believe
that the point is the difference of 20% health that is added in bear form
when you have the berserk ability. And then taken away. I guess if at the
moment of health reduction, health will be less than a certain level of
health will go into the minus.

чт, 4 янв. 2024 г. в 10:18, Turt Reynolds ***@***.***>:

**Comment by Bogdandengi** [comment]
I have now done it on 1 attempt. I am slowly learning the craft, lol.

The trickiest way to do it in my opinion. Use this bug in a hijal raid on hard mod on a small dragon. Priests give a shield so the damage is gradual, hijal paladin uses a weak ability to gradually bring the value to minimum. A berserk command is given on discord. The hil then reduces the bear's health to the required value and gives the ability to bubble. After that, the bear quietly "dies" and the rest of the raid goes to beat the main boss.  
Also, if you put different rings and trinkets on the attacker's damage, you can simply kill the necessary mobs with the help of "bear corpse" (if the npc doesn't have debuffs).
This is what came to mind for a potential abuz.


Uploading 2 try.mp4…

**Comment by Bogdandengi** [comment]
without addons

https://github.com/slowtorta/turtlewow-bug-tracker/assets/132904763/487e0535-1a4c-457d-972d-a6b3f5cea373

**Comment by Bogdandengi** [comment]
Video without a single addon. It took 3 attempts this time. 
Another 2 times players interfered, one of the attempts I recorded in the video above.

https://github.com/slowtorta/turtlewow-bug-tracker/assets/132904763/a8c7a935-cdff-4e47-9074-28bbca8d05a8

**Comment by cyaohiri** [comment]
A comment indicating it's not just Bear Form/Berserk that's the cause:
![image](https://github.com/slowtorta/turtlewow-bug-tracker/assets/86041826/9fd289bf-86f0-40fb-8364-ad12d82f8d4e)

**Comment by twowTurtReynolds** [comment]
@Bogdandengi What are the contents of that bear form macro you were pressing?

**Comment by Bogdandengi** [comment]
Last time I used the standard client without addons. But the video was
removed for some reason.
I pulled the standard ability to the panel with the "4" button.
And in everyday play I use the following macro:
 #showtooltip
/cast [mod:shift]Frenzied Regeneration(Rank 3);[nomod]Berserk

пт, 5 янв. 2024 г. в 09:17, Turt Reynolds ***@***.***>:

**Comment by byvide** [comment]
I think the *core issue* has nothing to do with druids, because something *similar* happend to me. But these druid cases may help understand it better for the devs.

I dont want to reveal what classes i play and what i was doing so this is going to be a little mysterious. I experienced it as "being dead and cannot resurrect" because i wasnt killed by an npc, so after death i may got the damage, just didnt notice it. My case is probably way easier to reproduce so im going to give it a try if i have the opportunity in the next couple of days.

**Comment by ratkosrb** [comment]
I believe I have found the cause and fixed the issue. Let me know if it happens after the next update.
