### ISSUE TITLE
Ravenholdt Rep not being gained from killing Syndicate Humonoids 

### ISSUE THREAD

**Issue by Grimpadre** [slowtorta/turtlewow-bug-tracker#5874]
Please, provide a clear description what the bug is:
Killing syndicate mobs currently does not given reputation for the Ravenholdt faction.

Steps to reproduce the behavior with as much detail as possible:

    1.Kill any syndicate npc (Hillsbrad, arathi, alterac etc.)
    2.No ravenholdt reputation gain

IDs of affected creatures, items, quests or spells with a link to the relevant page:
All of these mobs: https://database.turtle-wow.org/?search=Syndicate#npcs

Expected behavior. Describe how it should work:
Killing Syndicate mobs should give 5 reputation towards Ravenholdt, according to classic twow Database - https://database.turtle-wow.org/?faction=349

"All Syndicate [humanoids](https://database.turtle-wow.org/?search=Syndicate#npcs) give 1-5 reputation points per kill depending on your current level."

**Comment by Zmitrok1984** [comment]
@twowTurtReynolds  Are link to www.wowhead.com/classic  can be a prove ? 
According to link [Ravenholdt](https://www.wowhead.com/classic/faction=349/ravenholdt) 
Syndicate [humanoids](https://www.wowhead.com/classic/npcs=7&filter=na=syndicate;cr=3;crs=70;crv=0) give 5 reputation points per kill, though only through 11999/12000 Honored.

**Comment by twowTurtReynolds** [comment]
No. Wowhead's guides are also not reliable. Their comments however are, and no 1.12 or earlier comment mentions this reputation.
See my response here: https://github.com/slowtorta/turtlewow-bug-tracker/issues/5011

If you'd like to see the TBC behavior backported, please open a Suggestions forum thread.
