### ISSUE TITLE
交易导致物品丢失

### ISSUE THREAD

**Issue by chencheng04** [slowtorta/turtlewow-bug-tracker#5875]
**Please, provide a clear description what the bug is:**

**Steps to reproduce the behavior with as much detail as possible:**

1.亚服风暴烈酒服务器，我的角色：最光阴，对方角色：Ustinian
2. GM，交易出现了BUG，我的角色最光阴2014年1月3日凌晨0:10左右和Ustinian交易了2个复生塑像，5个岩石甲虫，10个水晶甲虫，5黄金甲虫，5个青铜甲虫，5个陶土甲虫！显示的是交易成功，但是实际我没收到，对方包里道具也消失了
3. Ustinian是我们公会团长，我是领取刚拿的2.5套件兑换材料，麻烦核实下

**IDs of affected creatures, items, quests or spells with a link to the relevant page:**

NPC: https://database.turtle-wow.org/?npc=
Item: https://database.turtle-wow.org/?item=
Quest: https://database.turtle-wow.org/?quest=
Spell: https://database.turtle-wow.org/?spell=
Object: https://database.turtle-wow.org/?object=

**Expected behavior. Describe how it should work:**

**Comment by twowTurtReynolds** [comment]
请用英文提交问题。我们无法通过自动翻译准确地翻译中文提交的错误报告，这使得我们难以理解问题的确切性质。谢谢！

Please submit the issues in English. We're unable to accurately translate bug reports submitted in Chinese through automatic translation, which makes it difficult for us to understand the exact nature of the issue. Thank you!
