### ISSUE TITLE
Vial of Potent Venoms - Debuff not applying correctly.

### ISSUE THREAD

**Issue by jc473** [slowtorta/turtlewow-bug-tracker#5877]
**Please, provide a clear description what the bug is:**
The poison debuff from the Vial of Potent Venoms apparently can stack up to 5 times according to the tooltip. However, the debuff never goes above 2 stacks. Also, the damage is not correlating to the tooltip information. The tooltip says it "**deals 100 Nature damage over 12 secs. Stacks up to 5 times.**". The damage ticks every 3 seconds which means the first stack should be doing 4 ticks of 25 damage (100, in total). The second stack should be doing 4 ticks of 50 damage (200, in total). However, in reality, the 1st and 2nd stacks are ticking for 30 and 60 damage, respectively.

**Steps to reproduce the behavior with as much detail as possible:**
1. Druid (feral form) with nothing equipped except for Vial of Potent Venoms.
2. Attack a Stormwind Expert or Apprentice Training Dummy for a sustained period of time (e.g. 10+ minutes).
3. The debuff will never exceed 2 stacks even though you can hear the sound effect suggesting that another dose of poison has been applied.

**IDs of affected creatures, items, quests or spells with a link to the relevant page:**
Expert Training Dummy - https://database.turtle-wow.org/?npc=50516
Apprentice Training Dummy - https://database.turtle-wow.org/?npc=50515
Vial of Potent Venoms (ID - 61243) - https://database.turtle-wow.org/?item=61243

**Expected behavior. Describe how it should work:**
At one stack, I expect the damage-over-time effect to tick for 25, four times (100, in total).
At two stacks, I expect the damage-over-time effect to tick for 50, four times (200, in total).
At three stacks, I expect the damage-over-time effect to tick for 75, four times (300, in total).
At four stacks, I expect the damage-over-time effect to tick for 100, four times (400, in total).
At five stacks, I expect the damage-over-time effect to tick for 125, four times (500, in total).

I've tested this using my druid (feral form) for about 30 minutes on a Stormwind expert/apprentice training dummy and the proc rate is around 20%. Combine this with the fast attack speed of cat form (~1 attack per second), it is quite likely to to get another proc without the damage-over-time effect falling off. Therefore, I would reliably expect to reach five stacks and be able to maintain it for very long periods of time.

**Comment by Zmitrok1984** [comment]
Please use [search ](https://github.com/slowtorta/turtlewow-bug-tracker/issues?q=Potent) before creating bug.

**Comment by jc473** [comment]
> Please use [search ](https://github.com/slowtorta/turtlewow-bug-tracker/issues?q=Potent) before creating bug.

Ah, sorry! First time user here so forgive my ignorance.

I'll close this ticket but will point out that the tooltip has not been changed yet as per the comment in another ticket (https://github.com/slowtorta/turtlewow-bug-tracker/issues/5397).
