### ISSUE TITLE
The loot table for new mobs is limited to silver only

### ISSUE THREAD

**Issue by cydith** [slowtorta/turtlewow-bug-tracker#588]
**Please, provide a clear description what the bug is:** New mobs loot table is restricted to silver only or no loot whatsoever.

**Steps to reproduce the behavior with as much detail as possible:**

1. Go to any new zone or dungeon 
2. Kill humanoid mobs
3. 

**IDs of affected creatures, items, quests or spells with a link to the relevant page:** Since the database is closed for now, I cannot provide relevant links. For reference, I encountered this with all mobs in Stormwind Vaults and mobs on Lapidus Isle. 

NPC: https://database.turtle-wow.org/?npc=
Item: https://database.turtle-wow.org/?item=
Quest: https://database.turtle-wow.org/?quest=
Spell: https://database.turtle-wow.org/?spell=
Object: https://database.turtle-wow.org/?object=

**Expected behavior. Describe how it should work:**

**Comment by Zebouski** [comment]
black morass mobs didnt even drop silver at all, only their dust tokens

**Comment by Neto-WoW** [comment]
Should be resolved.
