### ISSUE TITLE
Everlook - Nordanaar flight path is not optimal

### ISSUE THREAD

**Issue by Shellyoung** [slowtorta/turtlewow-bug-tracker#5882]
**Please, provide a clear description what the bug is:**
It is this:
![this](https://github.com/slowtorta/turtlewow-bug-tracker/assets/40469927/aaf3dc2a-4efc-4277-9ab5-81618728a93e)

**Expected behavior. Describe how it should work:**
Instead of this:
![that](https://github.com/slowtorta/turtlewow-bug-tracker/assets/40469927/25ce4ad3-22bd-4b55-a1b7-d45fb69c80f8)

**Comment by slowtorta** [comment]
It's a scenic route...
