### ISSUE TITLE
Lightning Shield removing Corrupting Mind

### ISSUE THREAD

**Issue by mdmcclel** [slowtorta/turtlewow-bug-tracker#5884]
While fighting Loatheb on my shaman, I noticed that activating Lightning Shield removed the Corrupted Mind debuff.  The boss kept refreshing the debuff about every 5 seconds and it pushed off Lightning Shield.  Recasting Lightning Shield again removed Corrupted Mind again.  I tried healing and did not get the 1 minute silence.  I tried again and confirmed that I was able to freely keep healing as long as I kept recasting Lightning Shield.

If it matters, I was using Lighting Shield rank 7.  I had not talents or set bonuses that effect Lightning Shield.

After the pull, I had another shaman in the group try and he was also able to remove Corrupted Mind by casting Lighting Shield.

Loatheb:
https://database.turtle-wow.org/?npc=16011

Corrupted Mind (not sure which is the real one):
https://database.turtle-wow.org/?spell=29185
https://database.turtle-wow.org/?spell=29194
https://database.turtle-wow.org/?spell=29196
https://database.turtle-wow.org/?spell=29198

Lightning Shield (Rank 7):
https://database.turtle-wow.org/?spell=10432

Expected Behavior:
Lighting Shield should have no interaction with Corrupted Mind at all.  Both the buff and debuff should be able to be up at the same time.

**Comment by ratkosrb** [comment]
Should be fixed in the next update.
