### ISSUE TITLE
About the Blood Ring PVP suit, development

### ISSUE THREAD

**Issue by sznbz** [slowtorta/turtlewow-bug-tracker#5885]
**Please, provide a clear description what the bug is:**

**Steps to reproduce the behavior with as much detail as possible:**

1.There's no future in the game right now, and the Alliance outnumbers the Horde several times over in terms of formations because of race and superiority.

2. Field PVP Can't get everyone players like, all of them crowded inside the Ao Shan battlefield, because the honor value is more. As a result, PVP has lost the fun of field PVP.

4. Although I don't think it's helpful for me to say this, I hope the server will do a good job of suggesting that: the Ozan Battlefield can only be queued in on Sundays once a week, and no queue is given to get in on weekdays. This will allow players to be more active in outdoor PVP game heat!

**IDs of affected creatures, items, quests or spells with a link to the relevant page:**

NPC: https://database.turtle-wow.org/?npc=
Item: https://database.turtle-wow.org/?item=
Quest: https://database.turtle-wow.org/?quest=
Spell: https://database.turtle-wow.org/?spell=
Object: https://database.turtle-wow.org/?object=

**Expected behavior. Describe how it should work:**

**Comment by twowTurtReynolds** [comment]
Please post suggestions to the suggestions forum.

**Comment by sznbz** [comment]
Posted it, didn't feel like I got a response, forgot to mention it, a little disappointed.
