### ISSUE TITLE
Wand of the Eclipse is held on the wrong hand and cannot be transmogged

### ISSUE THREAD

**Issue by heschlim** [slowtorta/turtlewow-bug-tracker#5886]
**Please, provide a clear description what the bug is:**
My human female is holding "Wand of the Eclipse" in the wrong hand. When I go to select transmogs, none of my other wand appearances are available to use.

**Steps to reproduce the behavior with as much detail as possible:**

1. Equip "Wand of the Eclipse"
2. Shoot Wand
3. See that human females are holding the wand in the wrong hand.

**IDs of affected creatures, items, quests or spells with a link to the relevant page:**

Item: https://database.turtle-wow.org/?item=61019

**Expected behavior. Describe how it should work:**
The wand should be held in the "right" hand, not the "left". The projectile is coming from an empty hand.

**Comment by twowTurtReynolds** [comment]
Related to https://github.com/slowtorta/turtlewow-bug-tracker/issues/5646
