### ISSUE TITLE
Incorrect resurrection text at Gates of Ironforge spirit healer

### ISSUE THREAD

**Issue by rptb1** [slowtorta/turtlewow-bug-tracker#589]
**Please, provide a clear description what the bug is:**
The spirit healer at the Gates of Ironforge says "I've been chosen by the Fleet Commander to put you, pirates, back into shape."  I don't think that's right!

![image](https://user-images.githubusercontent.com/419807/147561255-f9f9b4b4-39c8-47bf-81eb-0584f188a2f5.png)

**Steps to reproduce the behavior with as much detail as possible:**

1. Die somewhere near Ironforge.
2. Talk to the spirit healer at the graveyard.

**IDs of affected creatures, items, quests or spells with a link to the relevant page:**

NPC: https://database.turtle-wow.org/?npc=6491 (I think)

**Expected behavior. Describe how it should work:**
This should have the generic spirit healer text, not something about pirates.

**Comment by rptb1** [comment]
This seems to affect all spirit healers.

**Comment by inxdigo** [comment]
Can confirm, also saw this in the Wetlands

**Comment by Neto-WoW** [comment]
Fixed. Thanks.
