### ISSUE TITLE
Can't discover Mazra'Alor while working on the Cartographer achievement

### ISSUE THREAD

**Issue by laintime01** [slowtorta/turtlewow-bug-tracker#5891]
**Please, provide a clear description what the bug is:**

Dear GM
![lena](https://github.com/slowtorta/turtlewow-bug-tracker/assets/16274276/f467ff2c-3195-478a-8306-3437a32fa12f)
![maza](https://github.com/slowtorta/turtlewow-bug-tracker/assets/16274276/4ecda0da-95d9-49ca-a5f0-d5e1de8b9efc)

Hello, I am working on the "Cartographer" achievement, which involves exploring every inch of Azeroth. I've reached a place called Mazra'Alor, but there's no prompt saying I've discovered it. Can you please tell me what's going on?tyvm

PS: I've already deleted WDB and re-logged in, but it's not helping

Game ID: Lenalee

**Comment by twowTurtReynolds** [comment]
Duplicate of https://github.com/slowtorta/turtlewow-bug-tracker/issues/5701
