### ISSUE TITLE
Cannot summon Lord Valthalak in UBRS with Brazier of Invocation

### ISSUE THREAD

**Issue by Afraido** [slowtorta/turtlewow-bug-tracker#5892]
**Please, provide a clear description what the bug is:** Tried several times to summon Valthalak boss in UBRS, got confirmation from other person that it doesn't work not only for me, contacted GM so it is clearly a bug. Brazier of Invocation does not work, I do not know if it works in other instances but clearly it is impossible to summon Valthalak with it.

**Steps to reproduce the behavior with as much detail as possible:**

1. Went to UBRS
2. Killed The Beast
3. Tried using Brazier of Invocation several times with no effect, only error appears: "Invalid target"

**IDs of affected creatures, items, quests or spells with a link to the relevant page:**

NPC: https://database.turtle-wow.org/?npc=16042
Item: https://database.turtle-wow.org/?item=22057
Quest: https://database.turtle-wow.org/?quest=
Spell: https://database.turtle-wow.org/?spell=
Object: https://database.turtle-wow.org/?object=

**Expected behavior. Describe how it should work:** Once I am in Haunted Location using Brazier of Invocation should summon a boss Lord Valthalak
![obraz_2024-01-04_181029156](https://github.com/slowtorta/turtlewow-bug-tracker/assets/142446653/16dbce84-b8c7-4dc8-86ee-b96b13b180cd)

**Comment by ratkosrb** [comment]
Should be fixed after the next update.

**Comment by ratkosrb** [comment]
@twowTurtReynolds You must be standing at the wrong spot. You need to be near both the crystal and the trigger npc.


https://github.com/slowtorta/turtlewow-bug-tracker/assets/35845488/2ffc080e-5225-4d5a-906a-7ff04e619734

**Comment by ratkosrb** [comment]
I made another change that should fix the short range issue. There were custom changes to the spell targets I didn't see before.
https://github.com/vmangos/core/commit/67afb5c0c523ae231992d7371a68b812605b7e85

**Comment by twowTurtReynolds** [comment]
I can confirm that when you stand within 5yd of the node, it does work right now.

And good, next week the range will be big as it is meant to be.
