### ISSUE TITLE
HC60 Immortal character cannot group with normal 60 to queue blood ring

### ISSUE THREAD

**Issue by Guopala** [slowtorta/turtlewow-bug-tracker#5893]
**Please, provide a clear description what the bug is:**
hc charac cant group with non hc charac to join blood ring battle
problem is very simple ,and the error info is "your group is too big to join the battle"
GM told me that is bcs im hc charac  while other member is not .

i think it make no sense bcs im 60 now . and can group with no hc charac for dungeons and raids .

but why cant group together for blood ring .

everyone know that although lvling is very nice in turtle ,but we always enjoy the long journey when we get 60 !!!!!!

**Steps to reproduce the behavior with as much detail as possible:**

1.inv 2 members not hc 
2. group join to blood ring battle
3. it will say "your group is too big to join the battle"

**IDs of affected creatures, items, quests or spells with a link to the relevant page:**
Guopa
NPC: https://database.turtle-wow.org/?npc=
Item: https://database.turtle-wow.org/?item=
Quest: https://database.turtle-wow.org/?quest=
Spell: https://database.turtle-wow.org/?spell=
Object: https://database.turtle-wow.org/?object=

**Expected behavior. Describe how it should work:**

**Comment by Guopala** [comment]
yes .following this can be reproduced

i tried about 4 times with different members ,always the same .

just inv 3 other normal charac ,you can reproduce the bug

**Comment by twowTurtReynolds** [comment]
Are you in a group with 2 other people, for a party of 3?
Or are you grouping with 1 other person, for a party of 2?

**Comment by Guopala** [comment]
inv 2 members i mean .... i modified it . together the group members is 3

**Comment by Otari98** [comment]
are you queueing from STV arena? i think you can only group q from there

**Comment by Guopala** [comment]
> are you queueing from STV arena? i think you can only group q from there
im not .are you suer ,why i cant group using battleground while can group STV

**Comment by twowTurtReynolds** [comment]
That is a different bug, tracked here. https://github.com/slowtorta/turtlewow-bug-tracker/issues/5078

I will be closing this as this now seems like a duplicate.

**Comment by Guopala** [comment]
> That is a different bug, tracked here. #5078
> 
> I will be closing this as this now seems like a duplicate.

i checked #5078 ,it didnt mention whether it is hc and no hc group together ,are you sure about it ?

**Comment by twowTurtReynolds** [comment]
Yes, your Immortal status has nothing to do with the real bug of 5078.

**Comment by Guopala** [comment]
ok ,so you wont close this right ? not duplicate. this bug need to be fixed

**Comment by twowTurtReynolds** [comment]
This post is closed, but 5078 is open to be fixed. I will be closing this now.
