### ISSUE TITLE
Thunderhead Claws are not dropping

### ISSUE THREAD

**Issue by Kangaroux** [slowtorta/turtlewow-bug-tracker#5894]
**Please, provide a clear description what the bug is:**

The claws are supposed to drop with a 80% drop rate. I've killed 16 mobs and none have dropped. Either quest is bugged or my luck is astronomically bad (0.00000000006%)

https://database.turtle-wow.org/?item=60402
https://database.turtle-wow.org/?quest=40291
I was farming skystormers: https://database.turtle-wow.org/?npc=6378

**Comment by twowTurtReynolds** [comment]
Are you in a raid? That's always the cause of these.

**Comment by Kangaroux** [comment]
...yes. Forgot to leave raid after a dungeon.
