### ISSUE TITLE
Heated Ancient Blade not usable on Onyxia

### ISSUE THREAD

**Issue by Grishnakk** [slowtorta/turtlewow-bug-tracker#5895]
**Please, provide a clear description what the bug is:**

Used "Unfired Ancient Blade" at Onyxia fight, got "Heated Ancient Blade", this part worked fine.
After Boss died i couldnt use the Item "Heated Ancient Blade". Tried multiple times didnt work. 
Before my Vacation around 3 or 4 weeks ago i got the same Situation, figured i had bad luck.
So i got this issue two times in a row, a few weeks apart. I have Screenshot of having "Heated Ancient Blade" in inventory.
Game Master said he cant help and i need to post issue here. 

**Steps to reproduce the behavior with as much detail as possible:**

1. Loot "Heated Ancient Blade"
2.  Kill Onyxia
3.  Use "Heated Ancient Blade" on Onyxia

**IDs of affected creatures, items, quests or spells with a link to the relevant page:**

NPC: https://database.turtle-wow.org/?npc=10184
Item: https://database.turtle-wow.org/?item=18488
Quest: https://database.turtle-wow.org/?quest=7509
Item 2: https://database.turtle-wow.org/?item=18492

**Expected behavior. Describe how it should work:**

After killing Onyxia i should be able to use "Heated Ancient Blade" while having Onyxia in target and standing close to her. And then
get the item "Treated Ancient Blade" (Item 2).

**Comment by Grishnakk** [comment]
If you want you can kill ony, take all the loot and see for youself that i cannot use it on her.

**Comment by ratkosrb** [comment]
I can't reproduce the issue.

https://github.com/slowtorta/turtlewow-bug-tracker/assets/35845488/1f3bbf71-3277-4361-9c4b-83845834fedc

**Comment by Grishnakk** [comment]
yeah i know most people dont have an issue with it. but thank you for testing. any chance you would like to test it with me together? maybe you can figure out whats keeping me from using the item?

**Comment by ratkosrb** [comment]
It worked for me on the live server as well. Perhaps you can record your attempt on video? Is there an error that shows up when you try to use it?


https://github.com/slowtorta/turtlewow-bug-tracker/assets/35845488/63d3ef8b-6ccc-4ab6-9cb3-5fa2b340243e

**Comment by Grishnakk** [comment]
i tried rightclicking the Heated Ancient Blade and i even put it on my bars and tried using it that way. It was unresponsive. Nothing happened. Next Ony would be next week i can try to record it then even if its sad to wait so long.

**Comment by ratkosrb** [comment]
Try deleting the WDB folder too.

**Comment by Grishnakk** [comment]
i did that but yeah idk what it is

**Comment by twowTurtReynolds** [comment]
@ratkosrb this seems to be the same exact issue as https://github.com/slowtorta/turtlewow-bug-tracker/issues/5892 as they both share the Invalid Target error, which you just fixed, so I guess that fix will fix this here too?

![image](https://github.com/slowtorta/turtlewow-bug-tracker/assets/151180101/d01fac0f-7b6b-44f4-8d54-310a9b743b6a)
![image](https://github.com/slowt
![image](https://github.com/slowtorta/turtlewow-bug-tracker/assets/151180101/34dd26bb-5460-4d9d-a09e-6ea03ad51745)
orta/turtlewow-bug-tracker/assets/151180101/bc9cd30a-9a22-4dce-97ca-22dcbf4908b8)

**Comment by ratkosrb** [comment]
@twowTurtReynolds Onyxia needs to be dead. You have to kill her first.

**Comment by twowTurtReynolds** [comment]
Right I know, I confirmed it works fine on lastest vmangos. She's dead in the second screenshot up here.

**Comment by ratkosrb** [comment]
For me it worked for me on latest turtle core too, and on the live turtle server, so I don't know how it gave you "Invalid Target" error. Only way I can think of is if she's not dead.

**Comment by twowTurtReynolds** [comment]
![image](https://github.com/slowtorta/turtlewow-bug-tracker/assets/151180101/20729ab6-0f3f-499e-93ec-395c1774c06f)
![image](https://github.com/slowtorta/turtlewow-bug-tracker/assets/151180101/79a8c0d1-e338-47a8-bf2c-7665d92ea130)
Perhaps PTR needs a restart.

**Comment by ratkosrb** [comment]
Please run this on the PTR server's world db and show me the result:
```
SELECT *
FROM spell_script_target
WHERE entry=22906
```

**Comment by ratkosrb** [comment]
I just tested the item on Tel'Abim too and it worked there as well. So it works on both realms for me.

**Comment by twowTurtReynolds** [comment]
![image](https://github.com/slowtorta/turtlewow-bug-tracker/assets/151180101/e7a4a392-833d-4631-a194-e58b54749445)
PTR rebuild and restart, all good. Thanks sorry.
