### ISSUE TITLE
The hateforge in a raid group

### ISSUE THREAD

**Issue by Wainerhard** [slowtorta/turtlewow-bug-tracker#5896]
Hello. I killed the specified boss in the raid group about 120+ times with the Ragzabza character (you can check by the number of Fashion Coins received from this boss), but did not get the necessary loot. I think it's a bug. Check if the drop works in the raid group, if not, then please send me this item. Since I spent a lot of energy and nerves knocking it out.

**IDs of affected creatures, items, quests or spells with a link to the relevant page:**

NPC: https://database.turtle-wow.org/?npc=60737
Har'gesh Doomcaller <Twilight's Hammer>

Item: https://database.turtle-wow.org/?item=60551
Pendant of the Faceless

Thx!

**Comment by twowTurtReynolds** [comment]
The item is a 1.2% drop chance item, which means it can easily take hundreds, even thousands of kills to see it drop. Plenty of people have farmed this item and have acquired it.

Do not use the bug tracker for loot compensation requests.

**Comment by Wainerhard** [comment]
> The item is a 1.2% drop chance item, which means it can easily take hundreds, even thousands of kills to see it drop. Plenty of people have farmed this item and have acquired it.
> 
> Do not use the bug tracker for loot compensation requests.

I'm not asking you to give it to me just like that. If I did find a bug, then I asked for a refund.
