### ISSUE TITLE
Warrior Talents: Tactical Mastery (and possibly Parry)

### ISSUE THREAD

**Issue by ThatBoiJoker** [slowtorta/turtlewow-bug-tracker#590]
Certain Warrior talents seem to not be working at all. 
Having put 3 points into Tactical Mastery, it should store 15 rage after changing stances, instead, it stores none, i have changed stances at 100 rage to check if it is percentage based though came out with 0 rage again anyway. Furthermore the Deflection talent which should boost my parry chance by 2% (Rank 2) seems to also be malfunctioning. Pre patch i had 9.06% parry chance, post patch it has become 6.96(nice)
I have checked Improved Rend and Improved Charge and they seem to be working fine. 
Possible thing to note, the character was a Ghost during the patch, not sure if its related, other Warriors might have the same problems.

**Comment by Zebouski** [comment]
5/5 tac mastery was working correctly for me today dungeoning, perhaps it only happens on partial talented?
