### ISSUE TITLE
Dali Spinflux has wrong model

### ISSUE THREAD

**Issue by Writm0nkey** [slowtorta/turtlewow-bug-tracker#5900]
**Please, provide a clear description what the bug is:**
Dali Spinflux (storyteller) is suppose to be the gnomish storyteller for the racial storytellers in Winter Veil Vale, though recently the model was incorrectly set to a dwarf female model (Henning was already the dwarf storyteller).
![Screenshot 2024-01-05 012108](https://github.com/slowtorta/turtlewow-bug-tracker/assets/34611151/1847bb4f-ddd0-42d3-9ca8-85026052465b)

**Steps to reproduce the behavior with as much detail as possible:**
1. Go to Winter Veil Vale
2. Go over by orc/goblin/dwarf storytellers (where Dali's located)

**IDs of affected creatures, items, quests or spells with a link to the relevant page:**
NPC: https://database.turtle-wow.org/?npc=61188

**Expected behavior. Describe how it should work:**
Should be a gnome female model.

**Comment by slowtorta** [comment]
She's gnome...
![image](https://github.com/slowtorta/turtlewow-bug-tracker/assets/66763404/a2bd687b-058b-47d2-803b-3be2be338975)
