### ISSUE TITLE
[Schematic: Unstable Mining Dynamite] causes crash when trying to learn

### ISSUE THREAD

**Issue by nathanpaulyoung** [slowtorta/turtlewow-bug-tracker#5901]
**When I try to learn [Schematic: Unstable Mining Dynamite], my client crashes.**

1. I am running the game through WINE on Fedora 39 Linux.
2. I use Vanilla Fixes, Vanilla Tweaks, and Nampower.
3. **Addons:** Accountant, AdvancedTradeSkillWindow, Atlas, AtlasLoot, AtlasQuest, AutoDB2, AutoMessage, aux-addon, aux_merchant_prices, BetterCharacterStats, BigWigs, !BugGrabber, BugSack, Cartographer, Cleanup, ColorSocialFrame, DebuffTimers, DiscordActionBars, DiscordActionBarsOptions, DiscordLibrary, ElkBuffBar, EngBags, EQCompare, FAQMate, FishingBuddy, LilSparkysWorkshop, LunaUnitFrames, Magnify, Mail, MapTarget, MCP, Mendeleev, MinimapButtonFrame, MissingTradeSkillsList, MobHealth, MoPGearTooltips, MoveAnything, Niagara, NotGrid, Outfitter, pfQuest, pfQuest-icons, pfQuest-turtle, Postal-Returned, Prat, QuestAnnouncer, Quiver, RecipeRadar, Roid-Macros, SafeShift, ShaguBoP, ShaguDPS, ShaguPlates, ShaguTweaks, SilverDragon, SortBags, SuperMacro, TopMeOff, TradeSkillsData, TradeSkillsData-turtle, TurtleSnacks, TWThreat, UnicodeFont, WowLuaVanilla
4. Female Night Elf Druid, level 60.
5. 300 Gnomish Engineering

**Error received:**
```
---------------------------
WoW
---------------------------
This application has encountered a critical error:

ERROR #132 (0x85100084) Fatal Exception
Program:    Z:\home\nathan\Games\turtle-wow\WoW.exe
Exception:    0xC0000005 (ACCESS_VIOLATION) at 0023:781ABD46

The instruction at "0x781ABD46" referenced memory at "0x000000F4".
The memory could not be "read".

Press OK to terminate the application.
---------------------------
OK
---------------------------
```

**IDs of affected creatures, items, quests or spells with a link to the relevant page:**

Item: https://database.turtle-wow.org/?item=51269

**Comment by twowTurtReynolds** [comment]
We do not support use of addons or mods. Please disable them all, clear WDB, and try again.

**Comment by twowTurtReynolds** [comment]
![image](https://github.com/slowtorta/turtlewow-bug-tracker/assets/151180101/3300c645-7831-48a7-9f5a-157687746338)
![image](https://github.com/slowtorta/turtlewow-bug-tracker/assets/151180101/325cf236-666d-4245-83fd-46cbf6314e69)
I can confirm this is only an issue on your end.
