### ISSUE TITLE
Quel'Serrar

### ISSUE THREAD

**Issue by umbualt** [slowtorta/turtlewow-bug-tracker#5904]
Placed the blade in front of Onyxia, got the breath on it, but after she was killed there was no blade to be found. Blade not on the floor anywhere in her lair nor in my bags, just gone. Possible to get a new blade?

https://classicdb.ch/?npc=10184
https://classicdb.ch/?quest=7509
https://classicdb.ch/?item=18489

Character name: Rambu
account name: umbualt

**Please, provide a clear description what the bug is:**

**Steps to reproduce the behavior with as much detail as possible:**

1.
2. 
3. 

**IDs of affected creatures, items, quests or spells with a link to the relevant page:**

NPC: https://database.turtle-wow.org/?npc=
Item: https://database.turtle-wow.org/?item=
Quest: https://database.turtle-wow.org/?quest=
Spell: https://database.turtle-wow.org/?spell=
Object: https://database.turtle-wow.org/?object=

**Expected behavior. Describe how it should work:**

**Comment by twowTurtReynolds** [comment]
Drop and accept the quest again for a new blade.
![image](https://github.com/slowtorta/turtlewow-bug-tracker/assets/151180101/e022cf0f-c5d9-4a80-b245-4ca49285b8e2)
I can't replicate this issue, perhaps you lost it under the corpse.

However, beware of the similar issue https://github.com/slowtorta/turtlewow-bug-tracker/issues/5895

**Comment by umbualt** [comment]
If I drop the quest, how do I get the possibility of accepting it again?

**Comment by twowTurtReynolds** [comment]
Same place you got it from. Don't worry, blizzard had you covered here.
![image](https://github.com/slowtorta/turtlewow-bug-tracker/assets/151180101/6a5636bb-53d6-47b4-a598-a3d712018557)
![image](https://github.com/slowtorta/turtlewow-bug-tracker/assets/151180101/0cac2052-1eb1-4b4b-b6b1-0471bea0e23b)

**Comment by umbualt** [comment]
ok, ty
