### ISSUE TITLE
I am very sure that I did not participate in the BWL raid this week, but my team information shows BWL raid ID 9321. Please help me resolve this. Thank you!

### ISSUE THREAD

**Issue by feifa2002** [slowtorta/turtlewow-bug-tracker#5906]
**Please, provide a clear description what the bug is:**

**Steps to reproduce the behavior with as much detail as possible:**

1.I am very sure that I did not participate in the BWL raid this week, but my team information shows BWL raid ID 9321. Please help me resolve this. Thank you!
2. My game ID is 夏一世
3. 

**IDs of affected creatures, items, quests or spells with a link to the relevant page:**

NPC: https://database.turtle-wow.org/?npc=
Item: https://database.turtle-wow.org/?item=
Quest: https://database.turtle-wow.org/?quest=
Spell: https://database.turtle-wow.org/?spell=
Object: https://database.turtle-wow.org/?object=

**Expected behavior. Describe how it should work:**

**Comment by twowTurtReynolds** [comment]
It is possible to be attached a lockout because you grouped with someone who did. This is not a bug.
