### ISSUE TITLE
Warrior's Revenge does not proc on Training Dummy

### ISSUE THREAD

**Issue by hokanoma** [slowtorta/turtlewow-bug-tracker#5908]
**Please, provide a clear description what the bug is:**
Revenge should proc after Block, Dodge, or Parry. But it doesn't proc when it happens on Training Dummy. Overpower which procs after a dodge does work correctly, but not Revenge. 

**Steps to reproduce the behavior with as much detail as possible:**

1. Be in Defensive Stance
2. Auto-attack any Training Dummy
3. Wait for a Block, Dodge or Parry
4. Revenge does not proc after any of those events.

**IDs of affected creatures, items, quests or spells with a link to the relevant page:**

Spell: https://database.turtle-wow.org/?spell=25960 as well as all of its ranks.

**Expected behavior. Describe how it should work:**

When getting a Block, Dodge or Parry in Defensive Stance, Revenge should be able to be used.

**Comment by twowTurtReynolds** [comment]
Be careful with the tooltip, revenge procs on _enemies'_ attacks being block/dodge/parried by _you_. The opposite of how overpower works.
