### ISSUE TITLE
"Invalid Target" Earth Sapta in Durotar

### ISSUE THREAD

**Issue by Shiniest-Skritt** [slowtorta/turtlewow-bug-tracker#5911]
**Please, provide a clear description what the bug is:**
On the first Shaman quest, Call of Earth, on my level 5 Orc character, when I attempt to drink the Earth Sapta at the Spirit Rock, I get red error message in the middle of my screen that says "Invalid Target". This error prevents me from obtaining my earth totem.

**Steps to reproduce the behavior with as much detail as possible:**
1. Create a new Shaman orc character (I'm not sure if this bug affects Tauren or Trolls).
2. Get to at least level 4 and get the Call of Earth quest.
3. Attempt to drink the Earth Sapta at Spirit Rock.

**IDs of affected creatures, items, quests or spells with a link to the relevant page:**

NPC: https://database.turtle-wow.org/?npc=
Item: https://database.turtle-wow.org/?item=
Quest: https://database.turtle-wow.org/?quest=
Spell: https://database.turtle-wow.org/?spell=
Object: https://database.turtle-wow.org/?object=

**Expected behavior. Describe how it should work:**
I should not get the red error message, "Invalid Target". Instead, I should be able to successfully drink the sapta, interact with the earth elemental, and progress my Call of Earth quest. This bug is blocking progression.

**Comment by twowTurtReynolds** [comment]
Anyone experiencing this, contact a GM for a quick fix.

**Comment by psaus** [comment]
Same problem with "Call of Earth" in Mulgore

https://database.turtle-wow.org/?item=6635
https://database.turtle-wow.org/?quest=1520

**Comment by twowTurtReynolds** [comment]
![image](https://github.com/slowtorta/turtlewow-bug-tracker/assets/151180101/1b1c6be9-46c1-4e4e-b878-5acf1aade0bf)
Seems fixed now.
