### ISSUE TITLE
the world effect disappeared

### ISSUE THREAD

**Issue by jinyelei001** [slowtorta/turtlewow-bug-tracker#5914]
**Please, provide a clear description what the bug is:*When I get world effect ,system prompt "Cannot benefit from Rallying Cry of the Dragonslayer, world effect already suspended." c*

**Steps to reproduce the behavior with as much detail as possible:**

1. When I get world effect
2. system prompt "Cannot benefit from Rallying Cry of the Dragonslayer, world effect already suspended.
3. and then the world effect disappeared

**IDs of affected creatures, items, quests or spells with a link to the relevant page:* ID: Karroy*

NPC: https://database.turtle-wow.org/?npc=
Item: https://database.turtle-wow.org/?item=
Quest: https://database.turtle-wow.org/?quest=
Spell: https://database.turtle-wow.org/?spell=
Object: https://database.turtle-wow.org/?object=

**Expected behavior. Describe how it should work:**

**Comment by twowTurtReynolds** [comment]
This means that in your bags or bank, you have a Chronoboon, that has saved a copy of this world buff https://database.turtle-wow.org/?item=83001

Right click this supercharged chronoboon to unleash it, recieve your buff, and let you receive another of the same world buff later.
