### ISSUE TITLE
Corporal Keeshan is completely missing.

### ISSUE THREAD

**Issue by daisysunshyne** [slowtorta/turtlewow-bug-tracker#5915]
**Please, provide a clear description what the bug is:**

**Steps to reproduce the behavior with as much detail as possible:**

1. Please put Keeshan back in the game.
2.  He is not respawning in the Caverns in redridge.
3.  Nobody is doing the escort, it's been over an hour. 

**IDs of affected creatures, items, quests or spells with a link to the relevant page:**
Corporal Keeshan
https://www.wowhead.com/classic/npc=349/corporal-keeshan
https://www.wowhead.com/classic/quest=219/missing-in-action

**Expected behavior. Describe how it should work:**

**Comment by twowTurtReynolds** [comment]
![image](https://github.com/slowtorta/turtlewow-bug-tracker/assets/151180101/dbad2b2c-4fea-4570-af05-c61fe16b15f6)
He's there on the PTR, so this isn't really rep steps for a bug that we need to do a fix. Please contact a GM.
