### ISSUE TITLE
Ralo'shan the Eternal Watcher doesn't continue dialogue

### ISSUE THREAD

**Issue by Writm0nkey** [slowtorta/turtlewow-bug-tracker#5916]
**Please, provide a clear description what the bug is:**
When talking to Ralo'shan the Eternal Watcher, you're suppose to click on the "How do you know?" option to continue listening to her story. Clicking on that option however does absolutely nothing, so she remains stuck on that text box.
![Screenshot 2024-01-06 185037](https://github.com/slowtorta/turtlewow-bug-tracker/assets/34611151/632277d3-c455-4f01-abc8-651aecb0b3ee)

**Steps to reproduce the behavior with as much detail as possible:**

1.Go up to Ralo'shan (top of tower at Staghelm Point, Silithus) and talk to her to bring up dialogue.
2. Click on the "How do you know?" option.

**IDs of affected creatures, items, quests or spells with a link to the relevant page:**

[NPC: https://database.turtle-wow.org/?npc=](https://database.turtle-wow.org/?npc=15169)

**Expected behavior. Describe how it should work:**
After selecting **"How do you know?"**, she should continue her dialogue as follows:

I have been slain a hundred times. I always wake here, alive. Some say I am cursed and others...

**"What do they say?"**

They say that I am blessed: A herald to harken in a new age.

**"And what do you say?"**

Ancient forces stir - forces that have note been seen or felt for thousands of years. The world weeps, night elf. Perhaps a new sundering comes. A sickness born from within...

The foulness has begun to seep into our lands. From the Dream comes nightmares. Nightmares to befoul us in our waking hours...

**Comment by ratkosrb** [comment]
Should be fixed in the next update.
