### ISSUE TITLE
Unable to receive “Avast Ye, Scallywag” 

### ISSUE THREAD

**Issue by qpdxwc** [slowtorta/turtlewow-bug-tracker#5918]
**Please, provide a clear description what the bug is:**
After the reputation and friendliness of the Blood Sail Pirates, we are unable to receive “Avast Ye, Scallywag” and its subsequent missions from "Pretty Boy" Duncan
**Steps to reproduce the behavior with as much detail as possible:**

1.After friendly reputation, "Pretty Boy" Duncan will not provide tasks
2. GM helps add task  “Avast Ye, Scallywag”, but cannot receive subsequent task “Avast Ye, Admiral!” after completion
3. Prompt that the conditions for accepting the task have not been met

**IDs of affected creatures, items, quests or spells with a link to the relevant page:**

NPC: https://database.turtle-wow.org/?npc="Pretty Boy" Duncan
Item: https://database.turtle-wow.org/?item=
Quest: https://database.turtle-wow.org/?quest=“Avast Ye, Scallywag” 
Spell: https://database.turtle-wow.org/?spell=
Object: https://database.turtle-wow.org/?object=

**Expected behavior. Describe how it should work:**
After the Blood Sail Pirates gained a friendly reputation, t receive “Avast Ye, Scallywag” from "Pretty Boy" Duncan.  After completing task at Fleet Master Firallon, receive task Avast Ye, Admiral!. Complete task Avast Ye, Admiral! and obtain Bloodsail Admiral's Hat

**Comment by Dormilon** [comment]
To complete these quests, you need to have level 55 and earn friendly reputation with Bloodsail Buccaneers and hated with Booty Bay. Are you sure that you have fulfilled these conditions?
