### ISSUE TITLE
I want to create [Strong Frost Protection Potion] \ [Strong Shadow Protection Potion], and the system prompts me that my item is not ready yet, but this potion has no manufacturing restrictions!

### ISSUE THREAD

**Issue by wisuas** [slowtorta/turtlewow-bug-tracker#5919]
**Please, provide a clear description what the bug is:**

**Steps to reproduce the behavior with as much detail as possible:**

1.I want to create [Strong Frost Protection Potion] \ [Strong Shadow Protection Potion], and the system prompts me that my item is not ready yet, but this potion has no manufacturing restrictions!
2. 
3. 

**IDs of affected creatures, items, quests or spells with a link to the relevant page:**

NPC: https://database.turtle-wow.org/?npc=
Item: https://database.turtle-wow.org/?item=
Quest: https://database.turtle-wow.org/?quest=
Spell: https://database.turtle-wow.org/?spell=
Object: https://database.turtle-wow.org/?object=

**Expected behavior. Describe how it should work:**

**Comment by twowTurtReynolds** [comment]
![image](https://github.com/slowtorta/turtlewow-bug-tracker/assets/151180101/ebdd059a-468f-4f9f-afe2-fecfea182aa8)
I'm not sure why these two potion crafting spells are on cooldown for you. I wasn't able to replicate this. Try with a fresh client from the website so we can rule out WDB addon and mod issues for you. Also see if you can find what item might have put you on a cooldown.
