### ISSUE TITLE
Crafting DIm torches in the survival tab gives you a Questionmark item in your inventory that you can't delete

### ISSUE THREAD

**Issue by Niraf** [slowtorta/turtlewow-bug-tracker#592]
**Please, provide a clear description what the bug is:**
Crafting DIm torches in the survival tab gives you a Questionmark item in your inventory that you can't delete
**Steps to reproduce the behavior with as much detail as possible:**

1.Take the Survival profession
2. Craft a Dim torch using the new Survival tab
3. Watch it create a duplicate item with a ? as an icon that you can't delete

**IDs of affected creatures, items, quests or spells with a link to the relevant page:**

NPC: https://database.turtle-wow.org/?npc=
Item: https://database.turtle-wow.org/?item=
Quest: https://database.turtle-wow.org/?quest=
Spell: https://database.turtle-wow.org/?spell=
Object: https://database.turtle-wow.org/?object=

**Expected behavior. Describe how it should work:**
Make it so that you can at least delete the item,
![aafef](https://user-images.githubusercontent.com/96685686/147563237-5cbf72d1-35c0-4246-a70b-016031fed2b5.png)

**Comment by jameyboor** [comment]
Fixed.
