### ISSUE TITLE
A wrong Npc Position display of the quest“Iron coral”

### ISSUE THREAD

**Issue by Jmwow** [slowtorta/turtlewow-bug-tracker#5920]
**Please, provide a clear description what the bug is:**
the location of the quest npc is shown wrongly
**Steps to reproduce the behavior with as much detail as possible:**

1.the quest npc of Iron Coral (the id of this npc is 4999,its location shown on interface and database is in the new city of Gnome which the coordinate is (25.0,30.1)[Dun Morogh],but in fact is inside of the ironforge,and the coordinate is (68,47)Tinker Town

**IDs of affected creatures, items, quests or spells with a link to the relevant page:**

NPC: https://database.turtle-wow.org/?npc=6169
Item: https://database.turtle-wow.org/?item=
Quest: https://database.turtle-wow.org/?quest=1708
Spell: https://database.turtle-wow.org/?spell=
Object: https://database.turtle-wow.org/?object=

**Expected behavior. Describe how it should work:**

**Comment by Dormilon** [comment]
The NPC is located in the same place as indicated in the database.
