### ISSUE TITLE
First Aid Bug

### ISSUE THREAD

**Issue by blailex** [slowtorta/turtlewow-bug-tracker#5921]
**Please, provide a clear description what the bug is:**

I cannot train any new bandages with Artisan First Aid skill. I completed Horde trauma prior to speaking with Arnok in Orgrimmar and the quest is gone from him when I check. Gregory Victor in Arathi does not give any options to train new bandages.

**Steps to reproduce the behavior with as much detail as possible:**

1. Completed Horde Trauma without speaking to Arnok in Ogrimmar
2. Gregory Victor does not offer First Aid training

**IDs of affected creatures, items, quests or spells with a link to the relevant page:**

NPC: https://database.turtle-wow.org/?npc=12920
Spell: https://database.turtle-wow.org/?spell=](https://database.turtle-wow.org/?spell=19902)

**Expected behavior. Describe how it should work:**

Training for new skills

**Comment by Jan125** [comment]
The way it works here is that you have to reach a certain amount of skill points, then talk to your faction doctor, and he will give you a gossip option to learn and apply bandages.

These are the caps for bandages, as far as I remember:
240 for Heavy Mageweave
260 for Runecloth Bandage
290 for Heavy Runecloth Bandage

Are you certain that you have the required skill?
