### ISSUE TITLE
Hunter “training beast" skill bug

### ISSUE THREAD

**Issue by zhanghaitao4** [slowtorta/turtlewow-bug-tracker#5922]
I cant find the "training beast" skill in my spellbook after i finished the lvl10 class quest "training the beast".
I'm a human hunter, accepted the quest in Goldshire at lvl10, and finally completed the quest in SW garden district, but i can't find the "training beast" skill in my spell book.

1. char ID: zerohomer
2. 
3.

**Comment by twowTurtReynolds** [comment]
![image](https://github.com/slowtorta/turtlewow-bug-tracker/assets/151180101/1201dde4-f17e-4a21-a21a-7aeef8caf8fa)
![image](https://github.com/slowtorta/turtlewow-bug-tracker/assets/151180101/f7632ca6-1ef3-410d-8ab3-da6b53c94168)
![image](https://github.com/slowtorta/turtlewow-bug-tracker/assets/151180101/1e03ac4d-0d2a-4af1-80bf-d1a8f46d46ce)

Works fine for me.
