### ISSUE TITLE
[Call of Flame] talent

### ISSUE THREAD

**Issue by Jarikkor** [slowtorta/turtlewow-bug-tracker#5925]
**Please, provide a clear description what the bug is:**
the talent [Call of Flame] doesn't scale with my searing totem its damage dident go up
**Steps to reproduce the behavior with as much detail as possible:**

1.
2. 
3. 

**IDs of affected creatures, items, quests or spells with a link to the relevant page:**

NPC: https://database.turtle-wow.org/?npc=
Item: https://database.turtle-wow.org/?item=
Quest: https://database.turtle-wow.org/?quest=
Spell: https://database.turtle-wow.org/?spell=
Object: https://database.turtle-wow.org/?object=

**Expected behavior. Describe how it should work:**

**Comment by twowTurtReynolds** [comment]
I have just tested, my searing totem's damage goes from:
29-33
to:
31-37
