### ISSUE TITLE
Shadowforge Torch droprate should be 100%

### ISSUE THREAD

**Issue by pierretusseau** [slowtorta/turtlewow-bug-tracker#5927]
**Please, provide a clear description what the bug is:**

**Steps to reproduce the behavior with as much detail as possible:**

1. Kill Shadowforge Flame Keeper
2. Loot 0~1 Torch
3. Lose >5 min. of your life for respawn

**IDs of affected creatures, items, quests or spells with a link to the relevant page:**

NPC: https://database.turtle-wow.org/?npc=9956
Item: https://database.turtle-wow.org/?item=11885

**Expected behavior. Describe how it should work:**
Shadowforge Flame Keeper should loot at 100% drop rate like in Vanilla and Classic

**Comment by CosminPOP** [comment]
it was never 100%, close but not 100

https://www.wowhead.com/classic/item=11885/shadowforge-torch
