### ISSUE TITLE
Princess Theradras in Maraudon - unique loot - working as intended?

### ISSUE THREAD

**Issue by Dalzedur** [slowtorta/turtlewow-bug-tracker#5931]
**Please, provide a clear description what the bug is:**
Killed Princess in Maraudon. She dropped Blackstone Ring. Was unable to pick it up, because it is treated as 'unique' and I already owned one. Should it be unique-equipped instead, because I'd imagine that people would still wish to vendor it even if they loot a duplicate one? Now it's only useful as duplicate if you can disenchant the one you already carry and replace it with the fresh one - provided that you are not in a group where someone else can loot it.

**Steps to reproduce the behavior with as much detail as possible:**

1. Kill Princess and loot her Blackstone Ring
2. Kill Princess again, see her drop another Blackstone Ring
3.  Be unable to pick up the ring, since it is unique instead of unique-equipped

**IDs of affected creatures, items, quests or spells with a link to the relevant page:**
NPC: 
Princess Theradras
https://database.turtle-wow.org/?npc=12201

Item:
Blackstone Ring
https://database.turtle-wow.org/?item=17713

By extension her other 'unique' drop is: https://database.turtle-wow.org/?item=17780
It didn't look like anything else in her drop pool was unique.

**Expected behavior. Describe how it should work:**
It seems awfully artificial that the reality prevents your hero from looting a ring from an enemy they slay, because they happen to already have one, either on their person or in their bank. There's a category of equipment known as 'unique-equipped', which means you can only wear one of them, even if you are able to own multiple ones, you tend to see it in rings, trinkets, and one-handed weapons - basically in gear that you have multiple slots it is eligible for. To be fair, I can't recall if unique-equipped was added later on, and maybe wasn't there in vanilla... Doing a quick look on wowhead, it looks like there are total of 25 unique-equipped items in classic, and 414 in TBC, so it was probably added later on in the dev cycle nearing the end of vanilla, maybe? In fact, looking at the TBC version of Blackstone ring, it has been changed to unique-equipped from unique.

So, I'm not sure if this could be regarded as a bug or working as intended. There are certainly arguments for either case. Mainly, that it should stay as unique because it was unique in vanilla and only changed in TBC. On the other hand, TBC rectified some mistakes (bugs/overlooked issues etc) that were present in vanilla, and changing it to unique-equipped could have been a change made because players discovered that if they own the ring, they cannot loot it again, adding a 'worthless' drop to Princess's drop pool if they didn't have the ability to disenchant it on the fly. I would argue that unique treasures should probably be made unique-equipped instead for the most part, simply because of how horrible it feels if you have to leave the treasure behind because of such a limitation. They are bind on pickup gear from dungeon bosses, so you can't really get them to a player character who wasn't there to loot it when the boss was killed, so vendoring and disenchanting seem to be the most common solutions to deal with soulbound unique-equipped items you can't wear.

**Comment by twowTurtReynolds** [comment]
Unique-equipped does not exist in vanilla wow.
