### ISSUE TITLE
Fragments of the Past quest turn in bugged

### ISSUE THREAD

**Issue by Hartek082** [slowtorta/turtlewow-bug-tracker#5932]
https://database.turtle-wow.org/?quest=5247

I have all the requisite items and the quest log even shows completed, yet I cannot turn the items in to the NPC. I also just saw someone else complete the quest without a problem. I deleted my WDB folder and re-logged which didn't fix the issue, either.
![image_2024-01-08_123812082](https://github.com/slowtorta/turtlewow-bug-tracker/assets/40779358/981cdcc1-e1f1-4ca9-891c-7fa0f6ebb454)
![image_2024-01-08_123952704](https://github.com/slowtorta/turtlewow-bug-tracker/assets/40779358/f39c6dcb-8e50-4ffa-889b-4d107de56299)

**Comment by twowTurtReynolds** [comment]
Please see https://github.com/slowtorta/turtlewow-bug-tracker/issues/6042
