### ISSUE TITLE
I can't buy an undead horse

### ISSUE THREAD

**Issue by 315boy3** [slowtorta/turtlewow-bug-tracker#5933]
Dear GM:
        I'm  a Goblin Rogue.I want to buy an undead horse.My UNDERCITY reputation has been worshipped.But the horse dealer wouldn't sell me a horse in BRILL. My character's name is xiaozeiren.Please help me out, thank you.

**Comment by twowTurtReynolds** [comment]
In vanilla, you need Exalted reputation.

**Comment by twowTurtReynolds** [comment]
Replicated, even with exalted it doesn't work.

**Comment by 315boy3** [comment]
I am   Exalted reputation yet
