### ISSUE TITLE
Racing Quest

### ISSUE THREAD

**Issue by tasipeter3000** [slowtorta/turtlewow-bug-tracker#5934]
Hello
The Quest "Gnomes are genuine inventors" (https://database.turtle-wow.org/?quest=50312) Does not work correctly.

**Steps to reproduce the behavior with as much detail as possible:**

1. I Accept the quest.
2. I go to talk to Dolores as said and click the dialogue option "Try Gnome Car"
3. Then nothing happens and i cant continue on the quest

NPC: https://database.turtle-wow.org/?npc=50533
Quest: https://database.turtle-wow.org/?quest=50312

**Comment by twowTurtReynolds** [comment]
Duplicate of https://github.com/slowtorta/turtlewow-bug-tracker/issues/4813
