### ISSUE TITLE
Quest Making a Statement

### ISSUE THREAD

**Issue by StasyaLyova** [slowtorta/turtlewow-bug-tracker#5935]
**Please, provide a clear description what the bug is:**

On database twow said it brings 2k reputation for buccaneers and that's all. But in real it take away 26k reputation of Booty Bay and give 0 to Buccaneers. And after get Booty Bay reputation back player still can't turn in this quest. 

**Steps to reproduce the behavior with as much detail as possible:**

1. Take quest chain on buccaneers until get Making a Statement.
2. Make quests on Booty Bay reputation until get Honored+
3. Made it and lose all reputation from all three sides to deep Hated by one click. 

**IDs of affected creatures, items, quests or spells with a link to the relevant page:**

Quest: https://database.turtle-wow.org/?quest=40180
![IMG_20240108_193531370_HDR-01](https://github.com/slowtorta/turtlewow-bug-tracker/assets/153867747/b16a0270-c7c6-4c15-aa3c-8be0d1412c14)
![IMG_20240108_193249829_HDR-01](https://github.com/slowtorta/turtlewow-bug-tracker/assets/153867747/199beb79-de76-4456-83a2-d3420c8abfca)

**Expected behavior. Describe how it should work:**

It should give reputation to Buccaneers to neutral or unfriendly because player lose ALL reputation of Booty Bay and Blackwater Raiders. Quest should be able to turn in and continue quest chain.

**Comment by twowTurtReynolds** [comment]
Rereading this report, I do not see a bug, but intended design.
