### ISSUE TITLE
A small number of mobs remain immune to CC they should be vulnurable to

### ISSUE THREAD

**Issue by balakethelock** [slowtorta/turtlewow-bug-tracker#5936]
**Please, provide a clear description what the bug is:**
Title, some npcs are still immune to some mechanics 

**IDs of affected creatures, items, quests or spells with a link to the relevant page:**

NPC: https://database.turtle-wow.org/?npc=12457
https://vanilla.warcraftlogs.com/reports/j4LhPaZ1fcA3DdRH#boss=-3&difficulty=0&type=interrupts&ability=22275
Incorrectly immune to interrupts

NPC: https://database.turtle-wow.org/?npc=15264
https://vanilla.warcraftlogs.com/reports/C281W6VmJQahxckt#boss=-3&difficulty=0&hostility=1&source=41&type=auras&spells=debuffs&ability=355
Incorrectly immune to taunts

NPC: https://database.turtle-wow.org/?npc=16447
NPC: https://database.turtle-wow.org/?npc=16244
https://youtu.be/g1ZT-wXldg4?si=c4YN382j_Kc9w7wr&t=25
Incorrectly immune to slows and roots. The only slow they should be immune to is from hunter traps
https://www.wowhead.com/classic/news/wow-classic-not-a-bug-list-naxxramas-edition-updated-dec-3-2020-319642#:~:text=Plagued%20Ghouls-,cannot,-be%20debuffed%20by

**Expected behavior. Describe how it should work:**
These mobs should be changed to be vulnurable to these spell mechanics.

**Comment by ratkosrb** [comment]
Should be fixed in the next update.
