### ISSUE TITLE
Invisible/Not showing up Zeppelin in Thunder Bluff

### ISSUE THREAD

**Issue by BlueF0xx** [slowtorta/turtlewow-bug-tracker#5948]
**Please, provide a clear description what the bug is:**

Zepplein not showing up to Thunder Bluff for me BlueF0xx
Seen players riding an invisible one coming in but waited for an hour and never seen it actually show up.

**Expected behavior. Describe how it should work:**

**Comment by twowTurtReynolds** [comment]
This is an example of https://github.com/slowtorta/turtlewow-bug-tracker/issues/5312

The workaround for now is to restart the game and clear wdb when you see this bug once.
