### ISSUE TITLE
Wrong drop rate in quest Falrin's Vendetta

### ISSUE THREAD

**Issue by TheGardak** [slowtorta/turtlewow-bug-tracker#5949]
**Please, provide a clear description what the bug is:**
Mobs inside Dire Maul North dont drop the Ogre Warbeads needed for the quest Falrin's Vendetta, and in the database shows a good droprate, I thinkk the drope rate is wrong 

**Steps to reproduce the behavior with as much detail as possible:**

1. Get quest
2. Go to Dire Maul North
3.  Kill Ogres
4. Check if the drop rate is 10%

**IDs of affected creatures, items, quests or spells with a link to the relevant page:**

NPC: https://database.turtle-wow.org/?npc=11441
         https://database.turtle-wow.org/?npc=11444
Item: https://database.turtle-wow.org/?item=21982
Quest: https://database.turtle-wow.org/?quest=8949
Spell: https://database.turtle-wow.org/?spell=
Object: https://database.turtle-wow.org/?object=

**Expected behavior. Describe how it should work:**
To have 10% drop rate like shown in the database

**Comment by twowTurtReynolds** [comment]
I can confirm that the game is matching the DB at 10% right now, however I remember doing this quest on classic and the droprate was far better, around 25%.

**Comment by twowTurtReynolds** [comment]
Not a single drop? Were you in a raid?

**Comment by TheGardak** [comment]
Nop, normal party, guess im just super unlucky!  Asked ppl around and they told me they also had low drop rates. Maybe its afected by the number of ppl in the group with the quest?

**Comment by twowTurtReynolds** [comment]
I think when they say low drop rates, they are talking about the 25% vs 10% disparity that I mentioned. Also, the uninstanced ogres have a very very low drop rate, and some people confuse that.

Whether 1 or 5 people are on the quest, each ogre has the same chance to drop the quest item, but of course with 5 people on the quest you will be only getting 1 out 5 of them. 

I'll be keeping this thread open to look into the droprate difference, but in your case, I really think it was accidentally set to a raid and nobody noticed.

**Comment by TheGardak** [comment]
Just checked! No raid, just 1 person in the group with the quest. and got 2 from normal mobs and 2 from last boss add.
Si I dont know what happened in my last couple of runs
