### ISSUE TITLE
Blackstone Island quest progression

### ISSUE THREAD

**Issue by itorch1** [slowtorta/turtlewow-bug-tracker#5955]
**Please, provide a clear description what the bug is:**

**Steps to reproduce the behavior with as much detail as possible:**

1. Simply make a goblin of any class/gender
2. The later parts of chains are available right away, ruining the quest flow. I'm only 100% certain of the first initial quests, but the first town (in the map's center) seems to have the same issue. Possibly whole zone?

**IDs of affected creatures, items, quests or spells with a link to the relevant page:**

Quest: Too much to list

**Expected behavior. Describe how it should work:**
Certain quests should be unlocked only after completion of previous parts

**Comment by twowTurtReynolds** [comment]
I checked with our dev team, this is set up as intended.

**Comment by itorch1** [comment]
Hm, this doesn't make a lot of sense, as 
-There's a quest in the initial area, which you can pick up at lvl 1, which sends you killing lvl 3-4 vulture mobs. The breadcrumb gets unlocked later (lvl 2 or 3, not sure) which would then send you to the npc who doesn't offer anything. There is a similar issue with quest from Overseer Kizzcrack leading to Balnack Copperlight.

the quest density available from the get-go in the first town, and partially in initial area, is quite overwhelming and inconsistent with the other zones. I'm not entirely certain, but I believe some quests text is hinting at previous parts which could be picked up at the same time.

Please double check, certainly regarding the first paragraph

**Comment by twowTurtReynolds** [comment]
Our dev team has confirmed as intentional.
