### ISSUE TITLE
Claw of the Black Drake, transmog to off-hand weapon, wrong model position

### ISSUE THREAD

**Issue by PlaNOid** [slowtorta/turtlewow-bug-tracker#5959]
**Please, provide a clear description what the bug is:**
Weapon in off-hand slot have same model direction like main-hand
![TWWeaponBug](https://github.com/slowtorta/turtlewow-bug-tracker/assets/26299349/ca07e21c-5f23-4d09-bad4-146e6c770ed9)
 
**Steps to reproduce the behavior with as much detail as possible:**

1. Apply transmogrifiation of Claw of The Black Drake to one-hand fist-weapon (Stormfist in my case)
2. Equip transmogrificated weapon to off-hand slot
3. Show weapon on character model by press 'z'

**IDs of affected creatures, items, quests or spells with a link to the relevant page:**

Item: https://database.turtle-wow.org/?item=19365
Item: https://database.turtle-wow.org/?item=61042

**Expected behavior. Describe how it should work:**
Off-hand equiped weapon has vertical mirroring on model relatively to main-hand equiped

**Comment by twowTurtReynolds** [comment]
The 1.12 client doesn't support horizontal mirroring based on hands.
