### ISSUE TITLE
[Goblin Engineering At Its Finest!] Quest not working

### ISSUE THREAD

**Issue by Nightstab** [slowtorta/turtlewow-bug-tracker#5960]
**Please, provide a clear description what the bug is:**

**Steps to reproduce the behavior with as much detail as possible:**

1.
2. 
3. 

**IDs of affected creatures, items, quests or spells with a link to the relevant page:**

NPC: https://database.turtle-wow.org/?npc=
Item: https://database.turtle-wow.org/?item=
Quest: https://database.turtle-wow.org/?quest=
Spell: https://database.turtle-wow.org/?spell=
Object: https://database.turtle-wow.org/?object=

**Expected behavior. Describe how it should work:**

**Comment by Nightstab** [comment]
for both sides of the mirage raceway for gnomes and goblins, dolores will not activate the race. She only says the following: Dolores whispers: You are registered for a test race.

**Comment by ratkosrb** [comment]
I see people doing Daisy's real race on the live server, and that requires you to have completed the test race first, so it must be working there too.
