### ISSUE TITLE
无尽之海 服务器  小刀会 公会银行BUG

### ISSUE THREAD

**Issue by shulanbaobao111** [slowtorta/turtlewow-bug-tracker#5961]
我是 无尽之海 小刀会 会长， 2024年1月9日 我公会银行出现了严重的BUG， 导致公会银行的页面删减成原始页面，2-3页以及物品全部消失， 第一页面大部分奥金锭材料全部消失。  此次BUG对我公会所有会员造成了严重的损失已经玩游戏的信心。 请服务器管理员帮忙恢复。  
![目前的状态](https://github.com/slowtorta/turtlewow-bug-tracker/assets/156071107/2a3d5070-6059-47fb-927a-182715017055)
![之前的状态](https://github.com/slowtorta/turtlewow-bug-tracker/assets/156071107/8124ce61-be86-4046-b9bd-d5c607a9e232)
![之前的状态1](https://github.com/slowtorta/turtlewow-bug-tracker/assets/156071107/c2f1aae5-f746-40ac-8772-1d11124280d0)
![之前的状态2](https://github.com/slowtorta/turtlewow-bug-tracker/assets/156071107/d7c7b978-a9ab-4311-91ed-bffbb515c9c3)

**Comment by twowTurtReynolds** [comment]
请用英文提交问题。我们无法通过自动翻译准确地翻译中文提交的错误报告，这使得我们难以理解问题的确切性质。谢谢！

Please submit the issues in English. We're unable to accurately translate bug reports submitted in Chinese through automatic translation, which makes it difficult for us to understand the exact nature of the issue. Thank you!

**Comment by shulanbaobao111** [comment]
I am the president of the Endless Sea Knife Club. On January 9, 2024, there was a serious bug in my guild bank, which caused the page state of the guild bank to be reduced to the original page. Pages 2-3 and all items disappeared, and most of the gold materials on the first page disappeared. This bug has caused serious losses to all members of our guild and their confidence in playing games. Please ask the server administrator to help with the recovery.

**Comment by shulanbaobao111** [comment]
I am the president of the Endless Sea Knife Club. On January 9, 2024, there was a serious bug in my guild bank, which caused the guild bank's page to be initialized to the original page. The warehouse and items on pages 2-3 disappeared, and most of the gold materials in the warehouse on page 1 disappeared. This bug has caused serious losses to all members of our guild and lost confidence in playing games. Please ask the server administrator to help with the recovery

**Comment by shulanbaobao111** [comment]
I am the president of the Endless Sea Knife Club. On January 9, 2024, there was a serious bug in my guild bank, which caused the guild bank's page to be initialized to the original page. The warehouse and items on pages 2-3 disappeared, and most of the gold materials in the warehouse on page 1 disappeared. This bug has caused serious losses to all members of our guild and lost confidence in playing games. Please ask the server administrator to help with the recovery

**Comment by jameyboor** [comment]
Hi @shulanbaobao111. We are looking into this issue for you.
