### ISSUE TITLE
Some keys don't fit onto the key ring

### ISSUE THREAD

**Issue by KlonZK** [slowtorta/turtlewow-bug-tracker#5967]
**Please, provide a clear description what the bug is:**
Some keys, such as the viewing room key from scholo, don't fit on the keyring but instead occupy a regular slot in the inventory. 

**Steps to reproduce the behavior with as much detail as possible:**

1. Aquire a key, it will land in your bags
2. Try to place it into the keyring
3. Observe

**IDs of affected creatures, items, quests or spells with a link to the relevant page:**

NPC: https://database.turtle-wow.org/?npc=
Item: https://database.turtle-wow.org/?item=13873
Quest: https://database.turtle-wow.org/?quest=
Spell: https://database.turtle-wow.org/?spell=
Object: https://database.turtle-wow.org/?object=

**Expected behavior. Describe how it should work:**
I would expect all keys to fit into the keyring, but i am not 100% certain what blizzlike behaviour is. However to my knowledge, even some temporary, stackable keys like vault keys(https://database.turtle-wow.org/?item=11078) from brd fit on the keyring, so i dont see a reason why others wouldn't.

**Comment by twowTurtReynolds** [comment]
Please provide blizzlike proof.

**Comment by KlonZK** [comment]
It appears that when the keyring was added to the game it was limited to a selection of permanent keys such as the shadowforge key or the scholo main door, and was later expanded to include the viewing room key and other temporary keys. 

https://www.wowhead.com/classic/news/keyring-coming-to-wow-classic-in-first-patch-after-launch-294460
https://breezewiki.com/wowwiki-archive/wiki/Keyring

Imo keyring support should be added as a QoL feature no matter what the blizzlike behaviour is.

**Comment by twowTurtReynolds** [comment]
Suggestions belong on the forum, not on the bug tracker. 

If this is a real deviation from blizzlike, then we can keep it here. 

Please dig up some footage from classic or 2006 retail that confirms which is the case.

**Comment by Dragunovi** [comment]
Need confirmation on this.

**Comment by Dragunovi** [comment]
Adding this to the keyring regardless if its a vanilla feature or not, but please don't make bug reports for things you are unsure of next time.
