### ISSUE TITLE
Unable to Submit Items to Galvan the Ancient in Quest: The Great Silver Deceiver

### ISSUE THREAD

**Issue by elifpoyrazoglu** [slowtorta/turtlewow-bug-tracker#5974]
**Please, provide a clear description what the bug is:**
Unable to submit items for quest, 'The Great Silver Deceiver' to Galvan the Ancient in Stranglethorn Vale. 

**Steps to reproduce the behavior with as much detail as possible:**

1. Right click on Galvan The Ancient
2. select the quest  'The Great Silver Deceiver' or it will show up automatically

**IDs of affected creatures, items, quests or spells with a link to the relevant page:**

NPC: https://database.turtle-wow.org/?npc=7802
Item: https://database.turtle-wow.org/?item=3860
Item: https://database.turtle-wow.org/?item=6037
Quest: https://database.turtle-wow.org/?quest=2762

**Expected behavior. Describe how it should work:**
Usually when you have all the items, the 'Continue' button is lit up and you can proceed with submitting the quest. It does not do that. 

![Screenshot 2024-01-10 201505](https://github.com/slowtorta/turtlewow-bug-tracker/assets/20017457/b931d528-02de-4244-bf9f-137f8985d439)

**Comment by twowTurtReynolds** [comment]
1. Log out and delete WDB folder and log back in. Try handing in the quest then.
2. If that doesn't work, try abandoning and re-taking the quest, and see if you can hand it in then.

**Comment by twowTurtReynolds** [comment]
Please also see https://github.com/slowtorta/turtlewow-bug-tracker/issues/6042
