### ISSUE TITLE
Bugs About Staff of the Dreamer & Nefarian

### ISSUE THREAD

**Issue by Yushen99** [slowtorta/turtlewow-bug-tracker#5975]
**Please, provide a clear description what the bug is:**
1.According to my test, the entry of Staff of the Dreamer "[Allows 5% of your Mana regeneration to continue while casting.](https://database.turtle-wow.org/?spell=14521)"  does not effect.
2. When fighting with Nefarian, if a priest is controlled in period 1, he cannot change to shadowform in the following battle.

**Steps to reproduce the behavior with as much detail as possible:**

**IDs of affected creatures, items, quests or spells with a link to the relevant page:**

NPC: https://database.turtle-wow.org/?npc=
Item: https://database.turtle-wow.org/?item=
Quest: https://database.turtle-wow.org/?quest=
Spell: https://database.turtle-wow.org/?spell=
Object: https://database.turtle-wow.org/?object=

**Expected behavior. Describe how it should work:**

**Comment by schanzee** [comment]
See here about the staff issue
https://github.com/slowtorta/turtlewow-bug-tracker/issues/1750

**Comment by twowTurtReynolds** [comment]
Please only write one report per issue, do not make a mess for us please.

As for the nefarian issue, I cannot reproduce.

![image](https://github.com/slowtorta/turtlewow-bug-tracker/assets/151180101/4111a30c-9833-40aa-9ca0-ae60aef215b2)
