### ISSUE TITLE
Traveler's Tent Skill Missing in spellbook

### ISSUE THREAD

**Issue by Kennewg1** [slowtorta/turtlewow-bug-tracker#5978]
**Please, provide a clear description what the bug is:**

**Steps to reproduce the behavior with as much detail as possible:**

1.  Outline Traveler's Tent Missing in Spellbook 
![Report Bug](https://github.com/slowtorta/turtlewow-bug-tracker/assets/156331160/f47ba63f-b7c3-49e4-b921-15b6c4d60cef)

**IDs of affected creatures, items, quests or spells with a link to the relevant page:**

NPC: https://database.turtle-wow.org/?npc=
Item: https://database.turtle-wow.org/?item=
Quest: https://database.turtle-wow.org/?quest=
Spell: https://database.turtle-wow.org/?spell=
Object: https://database.turtle-wow.org/?object=

**Expected behavior. Describe how it should work:**

**Comment by schanzee** [comment]
Survival as in the secondary profession (similar to first aid) not your survival skill tree which is hunter exclusive.
Check the General tab of your spellbook for the survival profession and click on it to open the crafting menu.

**Comment by twowTurtReynolds** [comment]
Schanzee is correct.

All works well:
![image](https://github.com/slowtorta/turtlewow-bug-tracker/assets/151180101/114e90fb-53f0-4335-9da4-428dc4f80063)
