### ISSUE TITLE
Sulfuras, Hand of Ragnaros ppm reverted from 3.0 to .7 ppm.

### ISSUE THREAD

**Issue by grebe360** [slowtorta/turtlewow-bug-tracker#5981]
Sulfuras, Hand of Ragnaros is not proccing at the correct rate of 3.0.  Instead, it has defaulted it its original .7 ppm.

**Steps to reproduce the behavior with as much detail as possible:**

1.  I completed two /CombatLogs:  one for 30 minutes and one for 46 minutes
2.  My warrior's talents were reset and armor removed to ensure no haste or flurry was used.
3.  I went afk and auto attacked a lvl 1 target dummy for 30 and 46 minutes.

**IDs of affected creatures, items, quests or spells with a link to the relevant bug**

Item: https://database.turtle-wow.org/?item=17182

[WoWCombatLog(1).txt](https://github.com/slowtorta/turtlewow-bug-tracker/files/13910178/WoWCombatLog.1.txt)
[WoWCombatLog.txt](https://github.com/slowtorta/turtlewow-bug-tracker/files/13910179/WoWCombatLog.txt)

Spell: Fireball
Object: Target Dummy

Hand of Ragnaros should be proccing 3.0 instead of .7 ppm.  I have attached the two CombatLogs to review.  Thank you for your time.

**Comment by grebe360** [comment]
[WoWCombatLog(1).txt](https://github.com/slowtorta/turtlewow-bug-tracker/files/13910893/WoWCombatLog.1.txt)
[WoWCombatLog.txt](https://github.com/slowtorta/turtlewow-bug-tracker/files/13910894/WoWCombatLog.txt)

**Comment by Dragunovi** [comment]
Hopefully fixed in the next restart. If this issue persists please reopen this issue and we will look into it further.

**Comment by Josephienvandermeersch** [comment]
Seems like the Proc chance is still not fixed, I've being hitting a Target dummy for a while now after the Restart/Update and it feels exactly the same

**Comment by Josephienvandermeersch** [comment]
![image](https://github.com/slowtorta/turtlewow-bug-tracker/assets/24510505/0c0b7fa2-c750-4b52-918c-7cd1530f27e9)
This is on 3.66 Speed - 6% Hit rating on Expert Dummy. I'm 70% Sure i used to do a lot more Fireballs two months ago then i am doing now. I've noticed dps decrease in raids as well and thought i was just slacking but seems there is an issue.

**Comment by Tabletop111** [comment]
![image](https://github.com/slowtorta/turtlewow-bug-tracker/assets/156868202/c53c881d-a7c3-4fff-a2b5-479ec2e7f59f)

Definitely not 3 PPM

**Comment by Tabletop111** [comment]
![image](https://github.com/slowtorta/turtlewow-bug-tracker/assets/156868202/f1a49f3b-0fca-4440-ba07-35245a784f30)
 more data

**Comment by Tabletop111** [comment]
seems like the proc rate is still 0.7

**Comment by grebe360** [comment]
https://github.com/slowtorta/turtlewow-bug-tracker/issues/6017

I'll be away from work until tomorrow before I can reproduce, but this is who helped me collect the original data.  Thank you for your assistance.

**Comment by twowTurtReynolds** [comment]
As of 1 hour ago, this has been hotfix. Close game delete wdb reopen and these changes should be seen now.

**Comment by OonaFae** [comment]
Sulfuras still seems to be lower ppm than the forum post indicates
https://forum.turtle-wow.org/viewtopic.php?t=11294

Its possible that my RNG is just poor and my sample size isn't big enough quite yet. But below is my test/observation
![image](https://github.com/slowtorta/turtlewow-bug-tracker/assets/105398809/64b69e5e-32e0-43a5-887f-29a61e999349)

**Comment by OonaFae** [comment]
@twowTurtReynolds can this be re-opened or is this the correct proc rate and it wasn't mentioned in a log somewhere. I'll continue to test when i have time to gather a larger sample to try to rule out RNG more

**Comment by twowTurtReynolds** [comment]
It's 3.
