### ISSUE TITLE
Quest items not 100% chance drop for all

### ISSUE THREAD

**Issue by StasyaLyova** [slowtorta/turtlewow-bug-tracker#5983]
**Please, provide a clear description what the bug is:**

Seems trouble with Fragment of the Nightmare's Corruption (all 4), Draconic for Dummies and Scepter Shard (green, blue, red) - all is white quality (that master loot or group loot not save), quest loot with 100% chance drop but it can get only one in raid, only one person (who is faster or closer to body and have quest) and that's not fair. Moreover it incredible hard to gather people on mobs that not have any loot, so..

**Steps to reproduce the behavior with as much detail as possible:**

1. For example summon and kill Maws by 25+ players with quest on blue shard. 
2. Doesn't matter what rule of loot you choose, only one can get it - fastest or closest to corpse. It not fair. 
3. After someone looted it nobody can get their "quest item".

**IDs of affected creatures, items, quests or spells with a link to the relevant page:**

Quest:
https://database.turtle-wow.org/?quest=8735 (4 items Nightmare's Corruption)
https://database.turtle-wow.org/?quest=8729 (blue)
https://database.turtle-wow.org/?quest=8741 (green)

Item: 
https://database.turtle-wow.org/?quest=8735 (4 items Nightmare's Corruption)
https://database.turtle-wow.org/?item=21137 (blue)
https://database.turtle-wow.org/?item=21139 (green)
https://database.turtle-wow.org/?spell=25719 (Draconic for Dummies)

**Expected behavior. Describe how it should work:**
Quest items should be quest items and be available for all on quest 🙂
Can you please make quest items personally for everyone as other quest items?

(I don't remember trouble with red shard because I was only person in raid for it, but it can be same trouble)

**Comment by twowTurtReynolds** [comment]
Quest items for the Scarab Lord questline were intended by Blizzard to be 1 drop per raid member.

If you think this should change, make a post on our suggestions forum.

**Comment by StasyaLyova** [comment]
Made on forum
https://forum.turtle-wow.org/viewtopic.php?t=12671
