### ISSUE TITLE
The rank is indefinite

### ISSUE THREAD

**Issue by lilith0800** [slowtorta/turtlewow-bug-tracker#5984]
**Please, provide a clear description what the bug is:**

**Steps to reproduce the behavior with as much detail as possible:**

1.
2. 
3. 

**IDs of affected creatures, items, quests or spells with a link to the relevant page:**

NPC: https://database.turtle-wow.org/?npc=
Item: https://database.turtle-wow.org/?item=
Quest: https://database.turtle-wow.org/?quest=
Spell: https://database.turtle-wow.org/?spell=
Object: https://database.turtle-wow.org/?object=

**Expected behavior. Describe how it should work:**
![微信截图_20240112090031](https://github.com/slowtorta/turtlewow-bug-tracker/assets/156385506/0854a039-bc73-4bb9-998b-f9bfe8377518)

**Comment by lilith0800** [comment]
The rank is indefinite
![Uploading 微信截图_20240112090031.png…]()

**Comment by lilith0800** [comment]
1.The rank is indefinite。
![Uploading 微信截图_20240112090031.png…]()

**Comment by twowTurtReynolds** [comment]
What Schanzee said.
