### ISSUE TITLE
Missing title "Seeker of Knowledge"

### ISSUE THREAD

**Issue by Krein1991** [slowtorta/turtlewow-bug-tracker#5986]
**Please, provide a clear description what the bug is:**

**Steps to reproduce the behavior with as much detail as possible:**

1. Title "seeker of knowledge" dont awarded to me after 2700 quests doned. 
2. https://forum.turtle-wow.org/viewtopic.php?t=7107
3. I complete 2700 quests needed for this title. After - nothing. Please help me with this issue
![image](https://github.com/slowtorta/turtlewow-bug-tracker/assets/156430787/587e1e28-1dde-4529-a2cf-c2192a0e41e3)

**IDs of affected creatures, items, quests or spells with a link to the relevant page:**

NPC: https://database.turtle-wow.org/?npc=
Item: https://database.turtle-wow.org/?item=
Quest: https://database.turtle-wow.org/?quest=
Spell: https://database.turtle-wow.org/?spell=
Object: https://database.turtle-wow.org/?object=

**Expected behavior. Describe how it should work:**

**Comment by twowTurtReynolds** [comment]
Can you take a picture of your title picker?

**Comment by Krein1991** [comment]
--
Отправлено из Mail.ru для Android суббота, 13 января 2024г., 00:13 +03:00 от Turt Reynolds  ***@***.*** :

**Comment by twowTurtReynolds** [comment]
We did not receive your picture. Please log into github to post it.

**Comment by Krein1991** [comment]
![image](https://github.com/slowtorta/turtlewow-bug-tracker/assets/156430787/0790185d-2a7d-4df3-940d-2bcbbf370a25)

**Comment by twowTurtReynolds** [comment]
Our core devs will be taking another look, thank you for the report.

To get your specific case fixed, please contact a GM with an ingame ticket.

**Comment by Krein1991** [comment]
Ingame GM cannot help me with my issue. Dregian proposed me to w8 until devs will resolve this problem

**Comment by Krein1991** [comment]
> Our core devs will be taking another look, thank you for the report.
> 
> To get your specific case fixed, please contact a GM with an ingame ticket.

Ingame GM cannot help me with my issue. Dregian proposed me to w8 until devs will resolve this problem
