### ISSUE TITLE
Character model randomly turns invisible indoors

### ISSUE THREAD

**Issue by itorch1** [slowtorta/turtlewow-bug-tracker#5988]
**Please, provide a clear description what the bug is:**
When indoors (inside caves/structures) character and npc models will randomly turn invisible (stop rendering in the client) at random spots. The rendering is individual to each player/npc, and depends on their position.

**Steps to reproduce the behavior with as much detail as possible:**

1. Enter a cave/structure
2. Walk around randomly until your model turns invisible

**Comment by twowTurtReynolds** [comment]
Please specify which areas.

**Comment by balakethelock** [comment]
Happens often in Naxxramas, some creatures stay invisible until they enter combat.
Especially: triple stitched spewer pack behind Grob, Shade + necro knights pack before Gothik, and the boss Gluth itself.

**Comment by twowTurtReynolds** [comment]
@balakethelock That is an unrelated bug.

@itorch1 I an unable to replicate any issues in these caves. I would suggest a fresh client.

If you still have issues on a fresh client, take a video and show me **exactly** where.

**Comment by itorch1** [comment]
Apparently it's an issue that can happen when your FPS is too high. Enabling vsync seems to solve it.
