### ISSUE TITLE
Battleground Queue Issue

### ISSUE THREAD

**Issue by sczxv** [slowtorta/turtlewow-bug-tracker#5989]
My character Named: Ulfsark got hacked about 2 months ago.
I keep Deleting WDB before log in as common.Since then no battleground popped for me i dont know if im just unlucky but maybe something's wrong , in peak hours even after 30-40 minutes in Queue nothing is popping for me for almost a month i hope its just an "evil" coincedence but i wanna be sure .Thanks for the effort and for that lovely server :))

1. Relogging and delete wdb over and over again
2. Queueing for one time
3. Keep relogging deteleting requeuing and nothing is happening for long time

**Comment by twowTurtReynolds** [comment]
As far as we are aware, there are no queue bugs. Keep in mind that leveling BGs are not popular, if you are not lv 60 yet.

If you are lv 60, try grouping with others who can get into BGs.

**Comment by sczxv** [comment]
i've become really desperate im willing to give my info so you could check this out youself honestly!

**Comment by twowTurtReynolds** [comment]
The QA team cannot and will not access your live account.
