### ISSUE TITLE
No bonus from "Improved Hunter's Mark"

### ISSUE THREAD

**Issue by free43** [slowtorta/turtlewow-bug-tracker#5990]
I skilled https://database.turtle-wow.org/?spell=19425 (Improved Hunter's mark) but I don't get the 15 % bonus from it:

![hunters_mark](https://github.com/slowtorta/turtlewow-bug-tracker/assets/63957797/9cbe2ce9-e1fa-4641-a02a-16c1b039c405)

On the picture https://database.turtle-wow.org/?spell=14324 (Hunter's mark Rank 3) spell is used (Just 75 additional ranged attack power). The description says, additional 86 ranged attack power, which is correct. But when the spell is used it isn't corret, 

I unlearned my talent's, but before I had also skilled https://database.turtle-wow.org/?spell=19425 maybe it has something to do with that. I dont know if this bug was before also there. I just regonized it after unlearning my talents.

**Comment by twowTurtReynolds** [comment]
This is a quirk of the 1.12 client. Your buffs and debuffs which are modulated by gear and talents will never represent this on the text, but be assured they do work when the damage calculation matters.
