### ISSUE TITLE
Goblin male character's face has randomly changed.

### ISSUE THREAD

**Issue by Spoonge231** [slowtorta/turtlewow-bug-tracker#5991]
**Please, provide a clear description what the bug is:**
My Goblin character, which I created after the addition of new faces and the new Goblin starting zone, has had his facial features completely changed sometime between the submission of this bug report today and when I last played on Thursday night (Australian Eastern Standard Time). He now has a goatee when he was clean shaven, his angry grimace is now the standard Goblin grin, and his ears have changed. Only his eyes (green) and his hairstyle/colour remain the same. But even then his hair has turned pure white, as if the colour is missing from the game. 
I have no HD textures for characters/world items beyond the pretty night sky mod. 

**Steps to reproduce the behavior with as much detail as possible:**
I am unsure how to reproduce this behavior but after multiple attempts to restart the game, and deleting my WDB folder, it still remains. 

**Expected behavior. Describe how it should work:**
My character should look different than he currently does.

**Comment by slowtorta** [comment]
Please submit a ticket in game and request a GM help with your appearance :)
