### ISSUE TITLE
AV has too many NPCs not like 1.12

### ISSUE THREAD

**Issue by discer** [slowtorta/turtlewow-bug-tracker#5992]
**Please, provide a clear description what the bug is:**
There are way too many NPC patrols and static around Balinda this is not like 1.12 as seen in the videos below there are very few NPCS around Balinda and mobs to the right of SH GY or the hill up toward SH GY

https://youtu.be/jwrC23yuc20?si=Wm5LFM4ZAZPsoxoO&t=148
https://youtu.be/SxrdmkxW7IY?si=werRwDFQOaMEyRun&t=583

Also too many NPCs on road between Icewing Bunker and SP GY
https://youtu.be/SxrdmkxW7IY?si=sRDS-ni5V4iYVoep&t=1007

Also too many NPCs in Dun Baldur Ally base
https://youtu.be/jwrC23yuc20?si=kC4IQjcHtHnaApnd&t=266

**Expected behavior. Describe how it should work:**
Make it like 1.12

**Comment by twowTurtReynolds** [comment]
Turtle WoW's AV is modeled after 1.5 on purpose.
