### ISSUE TITLE
Missing title "Seeker of Knowledge" 2

### ISSUE THREAD

**Issue by Krein1991** [slowtorta/turtlewow-bug-tracker#5993]
**Please, provide a clear description what the bug is:**

**Steps to reproduce the behavior with as much detail as possible:**

1.#5986
2. Our core devs will be taking another look, thank you for the report.

To get your specific case fixed, please contact a GM with an ingame ticket.
3. Ingame GM cant help me with my problem. He told me to w8 until devs will do this. What I must to do?

**IDs of affected creatures, items, quests or spells with a link to the relevant page:**

NPC: https://database.turtle-wow.org/?npc=
Item: https://database.turtle-wow.org/?item=
Quest: https://database.turtle-wow.org/?quest=
Spell: https://database.turtle-wow.org/?spell=
Object: https://database.turtle-wow.org/?object=

**Expected behavior. Describe how it should work:**

**Comment by slowtorta** [comment]
Hello :) The required quest count is 2800, are  you sure you have completed that many?

**Comment by twowTurtReynolds** [comment]
Sorry @Krein1991 for the confusion, it turns out we have conflicting information in various places. 2800 was the intended value and will be the rule for everyone else going forward. However, for your troubles, please check your in-game mail.
