### ISSUE TITLE
Bugged weapon damage

### ISSUE THREAD

**Issue by Samladimore** [slowtorta/turtlewow-bug-tracker#5994]
I am opening a ticket concerning the damage per swing of the  Obsidian Edged Blade (   https://database.turtle-wow.org/?item=18822   ) compared to my old weapon Crystal Spiked Maul  (  https://database.turtle-wow.org/?item=20696  ).  

The issue is that Obsidian Edged Blade is doing LESS damage per swing than Crystal Spiked Maul.  I have tested both weapons against a level 60 Target Dummy in Stormwind  with my main character Samladimore ( level 60 human paladin) with NO seals, auras or any other buffs whatsoever and have seen consistent results with what I have stated: Obsidian Edged Blade deals LESS damage than Crystal Spiked Maul. ( Which shoudl not be possible in my experience since the sword is superior to the mace in every respect: has more damage per swing, gives more attack power). Both my weapon skills ( Two-handed Maces and Tow-handed Swords) are maxed (300).

My damage and attack power while wielding: 
- Obsidian Egded Blade:  392 - 486, 800 AP   (base weapon damage ; 176 -264)
- Crystal Spiked Maul 937 -487, 744 AP    (base weapon damage: 168 -252).

I'd like to restate that during my testing I have disregarded critical hits and was UNbuffed during the whole testing.
I have opened a ticket and received a response from one of the GMs stating that weapon speed is involved, crits, etc. and after s short duscussion he has redirected me here.
Obsidian Edged Blade is clearly superior in every respect and I'd like to have the issue addressed, please.

Best regards,
Samladimore

P.S.: I really enjoy this server, I love how you continue the legacy of the original WoW dev team and how you stay true to the spirit and lore of Warcraft. Keep up the good work!

**Comment by twowTurtReynolds** [comment]
Using the `.gm option nodmgrng` cheat:

![image](https://github.com/slowtorta/turtlewow-bug-tracker/assets/151180101/1ddef778-2787-46c7-b225-140ff222a6cd)
![image](https://github.com/slowtorta/turtlewow-bug-tracker/assets/151180101/6d39ee2d-41f9-4077-b1a0-bcb6b824b355)

**Comment by twowTurtReynolds** [comment]
This is due to the fact that slower weapons' hits get a stronger multiplier of your AP to apply to that hit. When CSM is equipped, Your AP is being multiplied by 3.9 instead of 3.4 with OEB, for all attacks that aren't normalized.

If i unequip all +AP gear, and i run the cheat `.mod AP 1`, we can see OEB clearly shine:
OEB:
![image](https://github.com/slowtorta/turtlewow-bug-tracker/assets/151180101/8e6607f4-8866-491a-902a-f82f05ed337b)
CSM:
![image](https://github.com/slowtorta/turtlewow-bug-tracker/assets/151180101/59542683-9f5e-4225-a2e6-d01446f9aa1d)

Working as intended.

**Comment by Samladimore** [comment]
Thank you very much for this specific presentation. I really appreciate it. I'll make sure to share this info with my guildmates in case something like this happens with someone else, we can set them straight and won't have to bother you guys with stuff like this.Keep up the good work!
Respectfully,
Samladimore.

Sent from Yahoo Mail on Android 
 
  On Sat, Jan 13, 2024 at 17:30, Turt ***@***.***> wrote:   


Closed #5994 as not planned.
