### ISSUE TITLE
"Freedom For All Creatures" Kindal Moonweaver doesn't join player

### ISSUE THREAD

**Issue by Writm0nkey** [slowtorta/turtlewow-bug-tracker#5995]
**Please, provide a clear description what the bug is:**
The quest "Freedom For All Creatures" is supposed to have the questgiver Kindal Moonweaver follow you while freeing the sprite darters, saying "I'm ready when you are [name]. Lead the way." upon accepting the quest. Instead she says her line then immediately stealths, then respawning at her normal position, never joining the player. She used to behave normally a couple of months ago, so it's a recent change.

**Steps to reproduce the behavior with as much detail as possible:**

1. Accept quest "Freedom For All Creatures" from Kindal Moonweaver at the Grimtotem compound, Feralas.
2. Jump down the cliff to do the quest. Kindal stealths at her normal spot and respawns, not following the player.

**IDs of affected creatures, items, quests or spells with a link to the relevant page:**

NPC: https://database.turtle-wow.org/?npc=7956
Quest: https://database.turtle-wow.org/?quest=2969

**Expected behavior. Describe how it should work:**
Kindal should follow the player until the quest objective is complete (free 6 sprite darters), where she says another message to meet her back at her normal location.

I noticed that this quest was bugging out according to the bug reports, so I don't know if this change here was accidental, or was intentional to help fix the previous bug if this quest randomly failing.

**Comment by twowTurtReynolds** [comment]
![image](https://github.com/slowtorta/turtlewow-bug-tracker/assets/151180101/b0aec66d-79e6-41a2-981c-41f5264ce534)
Seems to be working on both PTR and my vmangos install.
