### ISSUE TITLE
Ley-Technician Staff is upside down on male high elves

### ISSUE THREAD

**Issue by ffann1998** [slowtorta/turtlewow-bug-tracker#5996]
The spearhead is supposed to be over shoulders like on female characters.
![WoWScrnShot_011324_173827](https://github.com/slowtorta/turtlewow-bug-tracker/assets/87450254/81084d39-e1e4-43b5-aec8-637a367cb518)

**Comment by twowTurtReynolds** [comment]
https://database.turtle-wow.org/?item=41110

**Comment by Dragunovi** [comment]
This issue should be fixed in an upcoming restart.
