### ISSUE TITLE
Bugged Alliance Chest Silverpine Forest

### ISSUE THREAD

**Issue by ikillkings** [slowtorta/turtlewow-bug-tracker#5999]
**Please, provide a clear description what the bug is:**

LoS bug on Alliance chest, in the farm house just north of Ambermill. (Both servers)

![WoWScrnShot_011424_235528](https://github.com/slowtorta/turtlewow-bug-tracker/assets/52655995/1b7089c7-138e-47fa-88d6-f64fad30b126)

**Steps to reproduce the behavior with as much detail as possible:**

1. Go into first house (next to barn) above Ambermill in Silverpine Forest
2. Find 'Alliance Chest' at back room on first floor
3. Try to open - says "Target not in line of sight", no matter where you stand
4. Sad

**IDs of affected creatures, items, quests or spells with a link to the relevant page:**

Item: https://database.turtle-wow.org/?object=111095

**Expected behavior. Describe how it should work:**

1. Go into first house (next to barn) above Ambermill in Silverpine Forest
2. Find 'Alliance Chest' at back room on first floor
3. Try to open - it opens! I get loot!
4. Happy

**Comment by byvide** [comment]
Can confirm, that chest have the same issue on Nordanaar as well.
