### ISSUE TITLE
Mother's Milk

### ISSUE THREAD

**Issue by Dragunovi** [slowtorta/turtlewow-bug-tracker#60]
By opening this Issue, I admit to having done the pertinent research using sources from Vanilla (preferably) or Classic. I also understand that sources from other private servers are not acceptable.

**Current behavior**: 
Ragged John doesn't milk the poison from you, making the quest incompleteable.
**Expected behavior**: 
Ragged John should dispel aka "milk" the poison from you, completing the quest.
**Proofs**:
The quest specifies that you come back to him to get the poison "milked".
**Steps to reproduce**:

1. Accept the quest [Mother's Milk].
2. Afflict yourself with Mother Smolderweb's "Mother's Milk"
3. Come back to Ragged John to try to get it milked.

**Comment by Nolin7777** [comment]
Tested right now, it's working like a charm.
Take the quest, go inside lbrs, get debuff from boss, return to john and click "Milk me!".
He removes the debuff from you and the quest is completed...
