### ISSUE TITLE
Genesis Set (Druid tier 2.5) bonus appears bugged.

### ISSUE THREAD

**Issue by OlWeigand** [slowtorta/turtlewow-bug-tracker#6001]
**Please, provide a clear description what the bug is:**
![2024-01-14 18_14_31-World of Warcraft](https://github.com/slowtorta/turtlewow-bug-tracker/assets/22148292/3932949a-bb64-490b-97ae-0a83137b5dc7)

In the above picture, I have the Genesis Helm, the Genesis Vest and the Genesis Boots equipped. However, for purposes of the set bonus, it seems like only the Genesis Boots are equipped. Unequipping and re-equipping these pieces makes no difference. Hovering over any one of these items in the inventory correctly shows whichever of the other pieces is currently equipped, but mouseovering on them while equipped does not.

**Steps to reproduce the behavior with as much detail as possible:**

1. Equip the above 3 pieces of the Genesis Set.
2. Mouseover on the equipped items in your character pane.
3. Note that the set display does not correctly display the number of pieces equipped and does not appear to grant the set bonus.

**IDs of affected creatures, items, quests or spells with a link to the relevant page:**

Items: 
https://database.turtle-wow.org/?item=21355
https://database.turtle-wow.org/?item=21357
https://database.turtle-wow.org/?item=21353

**Expected behavior. Describe how it should work:**
When equipped, set items should display how many items in the set are equipped and which, if any, set bonuses are active.

**Comment by byvide** [comment]
As far as i know, if you transmog an item which is part of a set, then it wont appear as part of the set for the other items of that set anymore, consequently the setbonuses wont light up as well, but this is just a ui thing only.

**Comment by twowTurtReynolds** [comment]
Byvide is correct, that is the issue there and is well known, can't fix.
