### ISSUE TITLE
Cannot tame Sky Shadow (beast) in deadwin pass

### ISSUE THREAD

**Issue by saintpier** [slowtorta/turtlewow-bug-tracker#6002]
**Please, provide a clear description what the bug is:**

Cannot tame Sky Shadow (they're beast) in deadwin pass

**Steps to reproduce the behavior with as much detail as possible:**

1. frost trap
2. Tame Sky Shadow
3. Enjoy. (not)

**IDs of affected creatures, items, quests or spells with a link to the relevant page:**

NPC: https://database.turtle-wow.org/?npc=
Item: https://database.turtle-wow.org/?item=
Quest: https://database.turtle-wow.org/?quest=
Spell: https://database.turtle-wow.org/?spell=
Object: https://database.turtle-wow.org/?object=

**Expected behavior. Describe how it should work:**

**Comment by saintpier** [comment]
![Sky shadow not tamable](https://github.com/slowtorta/turtlewow-bug-tracker/assets/154566182/2a02cc38-9a43-4aa2-84e5-23022c59c4ce)

**Comment by byvide** [comment]
With a little research, I found that these beasts only became tameable with TBC, although there are similar ones in Desolace ([Dread Ripper](https://database.turtle-wow.org/?npc=4694)), so this is less of a bug and more of a request/content polish.

**Comment by saintpier** [comment]
Yeah… but lvl doesnt scale with mine so i habe to grind lvl36 to 60 instead of this one 56.

But thanks for info, guess it makes sense.
________________________________
De : byvide ***@***.***>
Envoyé : Sunday, January 14, 2024 5:32:07 PM
À : slowtorta/turtlewow-bug-tracker ***@***.***>
Cc : saintpier ***@***.***>; Author ***@***.***>
Objet : Re: [slowtorta/turtlewow-bug-tracker] Cannot tame Sky Shadow (beast) in deadwin pass (Issue #6002)


With a little research, I found that these beasts only became tameable with TBC, although there are similar ones in Desolace (Dread Ripper<https://database.turtle-wow.org/?npc=4694>), so this is less of a bug and more of a request/content polish.
