### ISSUE TITLE
邮箱邮寄物品 玩家30天没有收取后   没有正常退回邮件

### ISSUE THREAD

**Issue by Virulent165** [slowtorta/turtlewow-bug-tracker#6007]
邮箱邮寄物品 玩家30天没有收取后   没有正常退回邮件

我是亚服 拉文郡服务器的玩家    我的游戏角色名叫做  看看技能.

12月份 我给玩家  静静 邮寄了大量的草药 让他帮我制作药水.

但他工作比较忙 一直未上线.

从邮寄草药至今已经超过了30天.   我邮寄的草药没有正确的退回给我

请求帮助解决

**Comment by twowTurtReynolds** [comment]
请用英文提交问题。我们无法通过自动翻译准确地翻译中文提交的错误报告，这使得我们难以理解问题的确切性质。谢谢！

Please submit the issues in English. We're unable to accurately translate bug reports submitted in Chinese through automatic translation, which makes it difficult for us to understand the exact nature of the issue. Thank you!
