### ISSUE TITLE
Can't finish the mission "champion's battlegear"

### ISSUE THREAD

**Issue by zongjiezhe** [slowtorta/turtlewow-bug-tracker#6008]
Hello 

(Im sure I am not  in a raid group , and I juest delete WDB folder)

After a long period of painful torture, I completed the mission "champion's battlegear"

Now it says "Complete" in the quest log and the items required for the quest are in my bag (not in the bank)

But I can't finish the task at the NPC. 

Please help me. Thank you so much

My ID : 2756419002
Character'name : zzongjiezhe

NPC: https://database.turtle-wow.org/?npc=15176

Item: 
https://database.turtle-wow.org/?item=20802
https://database.turtle-wow.org/?item=20800
https://database.turtle-wow.org/?item=20801
https://database.turtle-wow.org/?item=21508

Quest: https://database.turtle-wow.org/?quest=8573

**Comment by byvide** [comment]
I didnt find other reports about this quest bug on discord or the forum, it may be a bug.
But to resolve this in your case, open an ingame ticket so a gm can assist you.
You can open ticket with the red question mark icon on the vanilla ui, or type `/gm` if you are using pfui addon.

**Comment by twowTurtReynolds** [comment]
Please see https://github.com/slowtorta/turtlewow-bug-tracker/issues/6042
