### ISSUE TITLE
[Regarding the bug issue with the Pastor's Atiesh, Greatstaff of the Guardian]

### ISSUE THREAD

**Issue by wk2611101** [slowtorta/turtlewow-bug-tracker#6009]
[Regarding the bug issue with the Pastor's Atiesh, Greatstaff of the Guardian]
I am a Shadow Priest player
After three months of hard work, I finally obtained this weapon
But after testing, this weapon has some bugs
According to the instructions, this weapon should provide around 182 spell damage points, but when implemented, it only costs around 120 points
And the property panel does not display either
This ultimate weapon's attributes are not as good as my original low-level equipment
I'm sorry, please fix these bugs
PLEASE

**Comment by byvide** [comment]
When submitting an issue, following the required format helps communicating the issue better, especially if it was made with a translator.

As a priest, you are talking about [this](https://database.turtle-wow.org/?item=22631) weapon
* gives a party buff, increasing healing stat by **up to** 62 for players in the party
* increases spell damage by **up to** 120 and healing by **up to** 300

So the weapon increases spell damage by *up to* 120 and healing by **up to** 362 for the wearer.

If anyone wonders where the 182 comes from in the report:
* 62 is only healing, not spell damage

these effects are not simple extra stats ("by UP TO x")
* so it wont show up in the ui
* you cannot just add them together

Although i didnt test this, im certain that this is either:
* a translation error on the SEA realm
* a translation error by the author
* a misreading by the author

**Comment by twowTurtReynolds** [comment]
@byvide is correct.
