### ISSUE TITLE
Crescent grove quest under wrong category

### ISSUE THREAD

**Issue by Jerem-Suj** [slowtorta/turtlewow-bug-tracker#601]
**Please, provide a clear description what the bug is:**

Crescent grove quest "Kalanar's Mallet" Shows up under swamp of sorrows category in quest log.

**Steps to reproduce the behavior with as much detail as possible:**

1.Accept the quest
2. Open quest log
3. 

**IDs of affected creatures, items, quests or spells with a link to the relevant page:**

Database is disabled, sorry can't provide.

NPC: https://database.turtle-wow.org/?npc=
Item: https://database.turtle-wow.org/?item=
Quest: https://database.turtle-wow.org/?quest=
Spell: https://database.turtle-wow.org/?spell=
Object: https://database.turtle-wow.org/?object=

**Expected behavior. Describe how it should work:**
I guess it should have separate category like all the other dungeons.
![image](https://user-images.githubusercontent.com/66302374/147566003-56485d98-3fac-4603-8c15-f3863dfdbf28.png)

**Comment by Kruxis** [comment]
Thanks for your report! 

The issue will be fixed on the next restart.

Safe Travels =)
