### ISSUE TITLE
Missing mage quest "In Search of the Owner"

### ISSUE THREAD

**Issue by Lichbanez** [slowtorta/turtlewow-bug-tracker#6010]
I'd like to know if this quest is currently working or has been removed, I spent days checking every bookcase and book I could find in every zone and dungeon but I was unable to find the "uncommon journal", no location or hint for it on both discord and the forum. 

Quest: https://database.turtle-wow.org/?quest=40273
Object: https://database.turtle-wow.org/?object=2010854

**Comment by ratkosrb** [comment]
It does not appear to be spawned. I'll add a spawn for it.

**Comment by Lichbanez** [comment]
It would be possible to know the general area or do I have to recheck everything again? Thanks.

**Comment by Lichbanez** [comment]
Can I have a hint of some sort? I give up I just cannot find this journal or the NPC

**Comment by ratkosrb** [comment]
Southshore

**Comment by Lichbanez** [comment]
Thanks I didn't find it but I'll keep looking maybe it was on cooldown

**Comment by ratkosrb** [comment]
There is no respawn time.

**Comment by Lichbanez** [comment]
But when you say Southshore do you mean Hillsbrad Foothills? I searched all the city for books or parchments it seems weird.
