### ISSUE TITLE
KLZ下层尾王打死后没有掉落物

### ISSUE THREAD

**Issue by bazhetianshen** [slowtorta/turtlewow-bug-tracker#6011]
**Please, provide a clear description what the bug is:**

**Steps to reproduce the behavior with as much detail as possible:**

1.亚服无尽之海服，ID11320的KLZ下层团本，尾王打死后没有掉落物，以前都是一阶段打死后还有二阶段打死然后有掉落物，这次的尾王直接在一阶段打死了，然后没有任何掉落物，也没有对话啥的，直接打死了，尸体没有东西啊，怎么回事，请求解决
2. 
3. 

**IDs of affected creatures, items, quests or spells with a link to the relevant page:**

NPC: https://database.turtle-wow.org/?npc=
Item: https://database.turtle-wow.org/?item=
Quest: https://database.turtle-wow.org/?quest=
Spell: https://database.turtle-wow.org/?spell=
Object: https://database.turtle-wow.org/?object=

**Expected behavior. Describe how it should work:**

**Comment by bazhetianshen** [comment]
亚服无尽之海，LM战士ID霸者天神，请求解决

**Comment by lyssebabz** [comment]
I've seent he same issue on Firemaw in BWL and onyxia

**Comment by twowTurtReynolds** [comment]
请用英文提交问题。我们无法通过自动翻译准确地翻译中文提交的错误报告，这使得我们难以理解问题的确切性质。谢谢！

Please submit the issues in English. We're unable to accurately translate bug reports submitted in Chinese through automatic translation, which makes it difficult for us to understand the exact nature of the issue. Thank you!
