### ISSUE TITLE
Losing combo points when equipping Idol of the Emerald Rot

### ISSUE THREAD

**Issue by DeterminedPanda** [slowtorta/turtlewow-bug-tracker#6012]
**Please, provide a clear description what the bug is:**
If you accumulate combo points as a druid in catform and then equip the Idol of the Emerald Rot you will lose all your combo points. Is this intended? This only occurs when equipping this specific idol. All the other idols let you keep your combo points.

**Steps to reproduce the behavior with as much detail as possible:**

1. Use catform
2. Accumulate Combo Points (doesn't matter how many)
3. Equip Idol of the Emerald Rot

**IDs of affected creatures, items, quests or spells with a link to the relevant page:**

NPC: https://database.turtle-wow.org/?npc=
Item: https://database.turtle-wow.org/?item=61455
Quest: https://database.turtle-wow.org/?quest=
Spell: https://database.turtle-wow.org/?spell=
Object: https://database.turtle-wow.org/?object=

**Expected behavior. Describe how it should work:**
You should keep your accumulated combo points.

**Comment by ratkosrb** [comment]
It should be fixed in the next update.
