### ISSUE TITLE
Permafrost no applying extra slow via frost bolt

### ISSUE THREAD

**Issue by MagiWolf92** [slowtorta/turtlewow-bug-tracker#6013]
So on my frost mage I noticed that the targets are not recieving the extra 10% slowing effect give by max rank permafrost.

Tool tip for frostbolt shows 50% but is only applying the base 40%

**Comment by ratkosrb** [comment]
https://github.com/slowtorta/turtlewow-bug-tracker/assets/35845488/62a31a62-78eb-402a-8069-3fb15a80ce90

I cannot reproduce the issue. You can see in the video the mob's speed is lower after applying the talent. Goes from 3.6 to 3.0 with the talent.

**Comment by MagiWolf92** [comment]
I took screen shots but idk how to convert them. The tool tip was showing 40% vs 50% and I haven't noticed an actually different

**Comment by MagiWolf92** [comment]
![Uploading frostbolt.PNG…]()

**Comment by MagiWolf92** [comment]
Had to use the snippet tool cause the screenshots are too big to upload

**Comment by jc473** [comment]
So, I can confirm that the debuff icons of Frostbolt/Cone of Cold are showing 40%/50% movement speed reduction when I have 3/3 Permafrost which is wrong. So, there is definitely a tooltip error for the debuff icons.
NB - This is true for Frost/Ice Amour spells as well!
@twowTurtReynolds Like the video above, can you please test if there is a measurable difference between Cone of Cold and Frostbolt when using the Permafrost talent?

**Comment by twowTurtReynolds** [comment]
It is a known, unfixable quirk of the 2006 client that tooltips will not reflect this. If this is the only reason you have to believe they are not working, there is no cause for concern then.

**Comment by jc473** [comment]
Fair enough re tooltip quirk.

However, as per my 'Permafrost not applying to Cone of Cold' ticket, I can't physically see or feel a noticeable difference when applying a frostbolt or cone of cold debuff to a mob. NB - I'm currently using the 3/3 Permafrost talent when testing this.

Can you please check if you can measure a tangible difference?

**Comment by MagiWolf92** [comment]
okay tyvm for getting back to me. I was completely unaware of tool tip bugs
so I do apologize for taking away from actual issues. Thanks again for at
least looking into this and informing me better :D
