### ISSUE TITLE
Mazra'alor can't be discovered

### ISSUE THREAD

**Issue by Jojjeami** [slowtorta/turtlewow-bug-tracker#6014]
**Please, provide a clear description what the bug is:**

**Steps to reproduce the behavior with as much detail as possible:**

1. Enter .cartographer
2. Next zone: Mazra'alor
3. Explore Mazra'alor and never get credit for exploring it

**IDs of affected creatures, items, quests or spells with a link to the relevant page:**

NPC: https://database.turtle-wow.org/?npc=
Item: https://database.turtle-wow.org/?item=
Quest: https://database.turtle-wow.org/?quest=
Spell: https://database.turtle-wow.org/?spell=
Object: https://database.turtle-wow.org/?object=

**Expected behavior. Describe how it should work:**

I should be able to get credit for discovering mazra'alor even when my current zone is in "mazra'alor" but my .cartographer is still stuck on "next zone: Mazra'alor"

**Comment by MayaZelda** [comment]
I have this same issue since 3 weeks ago.
Is it a bug or just very hard to find the right spot to explore it?
Or maybe it writes Mazra'alor instead of [other name]'Alor and that's why no completion?

**Comment by ratkosrb** [comment]
It should be removed from the cartographer requirements after the next update.
