### ISSUE TITLE
Same faction spirit healer.   

### ISSUE THREAD

**Issue by Dragoonduneman** [slowtorta/turtlewow-bug-tracker#6015]
As a tauren just starting out , my friend who is a troll on the orc , i spirit walk on death to the orc starting area.   I was instead denied of spawning there ... to just ported back to bloodhoof village ... I believe this to be a bug.   You could in-fact spawn by spirit healer any spot you chooses to walk to.

**Comment by ratkosrb** [comment]
This is not a bug.
