### ISSUE TITLE
Sulfuras Hammer still not fixed after update - Re opening Post : https://github.com/slowtorta/turtlewow-bug-tracker/issues/5981

### ISSUE THREAD

**Issue by Josephienvandermeersch** [slowtorta/turtlewow-bug-tracker#6017]
Original Post by Grebe360:
Sulfuras, Hand of Ragnaros is not proccing at the correct rate of 3.0. Instead, it has defaulted it its original .7 ppm.

Steps to reproduce the behavior with as much detail as possible:

I completed two /CombatLogs: one for 30 minutes and one for 46 minutes
My warrior's talents were reset and armor removed to ensure no haste or flurry was used.
I went afk and auto attacked a lvl 1 target dummy for 30 and 46 minutes.
IDs of affected creatures, items, quests or spells with a link to the relevant page:

NPC: https://database.turtle-wow.org/?npc=
Item: https://database.turtle-wow.org/?item=17182
Quest: https://database.turtle-wow.org/?quest=
[WoWCombatLog(1).txt](https://github.com/slowtorta/turtlewow-bug-tracker/files/13910178/WoWCombatLog.1.txt)
[WoWCombatLog.txt](https://github.com/slowtorta/turtlewow-bug-tracker/files/13910179/WoWCombatLog.txt)

Spell: Fireball
Object: Target Dummy

Hand of Ragnaros should be proccing 3.0 instead of .7 ppm. I have attached the two CombatLogs to review. Thank you for your time.

Personal Information:

![image](https://github.com/slowtorta/turtlewow-bug-tracker/assets/24510505/6981c84e-2b02-4762-b0b0-d6d503eabf77)
This is on 3.66 Speed - 6% Hit rating on Expert Dummy. I'm 70% Sure i used to do a lot more Fireballs two months ago then i am doing now. I've noticed dps decrease in raids as well and thought i was just slacking but seems there is an issue.

**Comment by Tabletop111** [comment]
![297255494-c53c881d-a7c3-4fff-a2b5-479ec2e7f59f](https://github.com/slowtorta/turtlewow-bug-tracker/assets/156868202/726d1e0d-bf66-44a7-9918-cba4afc31f0d)
![297259642-f1a49f3b-0fca-4440-ba07-35245a784f30](https://github.com/slowtorta/turtlewow-bug-tracker/assets/156868202/97128278-ffd7-495b-b784-36ae9fb6c381)

seems like the proc rate is still 0.7ppm

**Comment by lyssebabz** [comment]
![Screenshot from 2024-01-17 13-51-53](https://github.com/slowtorta/turtlewow-bug-tracker/assets/20995435/e1e48dc3-2b69-45e0-837e-a605c9f6a1f6)
can confirm

**Comment by Josephienvandermeersch** [comment]
Old data i found on forums suggested that this is the correct proc rate Sulfuras, Hand of Ragnaros = 10%; ppm = 1,6216 (1,6)

**Comment by Tabletop111** [comment]
> Old data i found on forums suggested that this is the correct proc rate Sulfuras, Hand of Ragnaros = 10%; ppm = 1,6216 (1,6)

Hand of Rag was buffed to 3PPM to distinguish a legendary weapon from the rest. However it seems like the proc rate had been reverted back to 0.7PPM since 1 or 2 patches ago

**Comment by twowTurtReynolds** [comment]
Do not create duplicate reports.
