### ISSUE TITLE
Voidwalker lost its abilites

### ISSUE THREAD

**Issue by frantsel** [slowtorta/turtlewow-bug-tracker#6018]
**Please, provide a clear description what the bug is:**

**Steps to reproduce the behavior with as much detail as possible:**

1. Hello! My voidwalker lost all its abilities and they are also not in the spellbook.

**IDs of affected creatures, items, quests or spells with a link to the relevant page:**

NPC: https://database.turtle-wow.org/?npc=
Item: https://database.turtle-wow.org/?item=
Quest: https://database.turtle-wow.org/?quest=
Spell: https://database.turtle-wow.org/?spell=
Object: https://database.turtle-wow.org/?object=

**Expected behavior. Describe how it should work:**

**Comment by frantsel** [comment]
It seems like he just lost the abilites. I tried to buy them new and it works.

Do I really need to pay now again for those abilities?

**Comment by byvide** [comment]
Can you add some detail, like did you do anything unusal or you just logged in and they were gone?

**Comment by twowTurtReynolds** [comment]
I believe you are the same person who contacted support and had this fixed. Somehow, your voidwalker's name changed. We have another bug report open for this.
