### ISSUE TITLE
Bloodstone Warblade & Iron Counterweight

### ISSUE THREAD

**Issue by RogueArc** [slowtorta/turtlewow-bug-tracker#6019]
**Please, provide a clear description what the bug is:**
Seems adding the Counterweight (3% increase to attack speed) to the Bloodstone Warblade causes the 2% of damage returned as healing to not work.
I have the Warblade with a 2H Impact (+5 damage) enchant on my Warrior, and I see the "green" numbers representing the healing. I do not see that on the blade with a counterweight.

**Steps to reproduce the behavior with as much detail as possible:**

1. Craft Bloodstone Warblade
2. Attach an Iron Counterweight (Blacksmithing item)
3. Go kill something and look for the green number and log entry

**IDs of affected creatures, items, quests or spells with a link to the relevant page:**
Iron Counterweight - (Item #67222)?
 /script DEFAULT_CHAT_FRAME:AddMessage("\124cffffffff\124Hitem:6043:0:0:0:0:0:0:0:0\124h[Iron Counterweight]\124h\124r");

Bloodstone Warblade - (Item #60294 )?
/script DEFAULT_CHAT_FRAME:AddMessage("\124cff1eff00\124Hitem:60294:0:0:0:0:0:0:0:0\124h[Bloodstone Warblade]\124h\124r");

NPC: https://database.turtle-wow.org/?npc=
Item: https://database.turtle-wow.org/?item= (Item #60294 )?
Quest: https://database.turtle-wow.org/?quest=
Spell: https://database.turtle-wow.org/?spell= (Item #67222)?
Object: https://database.turtle-wow.org/?object=

**Expected behavior. Describe how it should work:**
User should see a green plus number per hit on scrolling combat text, see a Combat Log entry for healing gained

**Comment by byvide** [comment]
I tested the weapon only, not the enchant, and i doubt  that you see the healing without the enchant, because i didnt. So this has nothing to do with the enchant. This works just like any other vampirism effect (and the 2% is working correctly in this case), as far as i know, healing from vampirism are happening (can confirm), they are just not logged, not to clog your combat log/make dps meters go crazy.

**Comment by RogueArc** [comment]
I do see a +2 green text on my warrior with the weapon.

I will run a test on that toon and see if there are any differences.

But I DO NOT ever see the Health gains in the UI Health Bar with the
Counterweight.

**Comment by RogueArc** [comment]
OK, I tested the sword on a warrior.

I did not see the green number gain, nor did I really notice a gain in the
UI Health Bar...

There is NO log entry for the Health gain either, as you stated.

Thank you for taking the time to verify my claim.

Hope you have a great year!
