### ISSUE TITLE
Xalvic Blackclaw (rare elite satyr in Felwood) cast Soul Corruption ~20 times/second if his target is immune to it

### ISSUE THREAD

**Issue by Shellyoung** [slowtorta/turtlewow-bug-tracker#6021]
**Please, provide a clear description what the bug is:**

https://github.com/slowtorta/turtlewow-bug-tracker/assets/40469927/e5c30988-083c-48ea-9e69-91a1424f30e1

**IDs of affected creatures, items, quests or spells with a link to the relevant page:**
NPC: https://database.turtle-wow.org/?npc=49003

**Comment by ratkosrb** [comment]
Should be fixed in the next update.
