### ISSUE TITLE
Zep from UC to GG isn't working right on Tel'Abim

### ISSUE THREAD

**Issue by Zenith-One** [slowtorta/turtlewow-bug-tracker#6026]
The zep from UC to Grom'gol only appears as it's flying away from the tower. It never docks.

**Steps to reproduce the behavior with as much detail as possible:**
1. Be at the UC zep tower
2. Watch the zep appear suddenly as it flies away in the distance, without having ever docked

**Expected behavior. Describe how it should work:**
Zep appears as it flies to the tower, docks, then flies away, instead of just popping into existence as it flies away

**Comment by schanzee** [comment]
Clear your Cache/WDB folder

**Comment by twowTurtReynolds** [comment]
Duplicate of https://github.com/slowtorta/turtlewow-bug-tracker/issues/5312
