### ISSUE TITLE
霍格公会仓库 仓库页丢失物品消失

### ISSUE THREAD

**Issue by pili889900** [slowtorta/turtlewow-bug-tracker#6029]
**Please, provide a clear description what the bug is:**霍格公会  | 夜空之歌 |  1月17日晚11点15分开公会仓库，1月18日凌晨1点更新后公会仓库第二页连物品消失

**Steps to reproduce the behavior with as much detail as possible:**

1.1月17日晚11点15分开公会仓库，并后续500G开了仓库第二页
2. 1月18日1点更新后，公会仓库第二页连同物品消失
3. 500金币花费未返还，仓库页消失，仓库后续记录消失，花费500G后，又存入200G存在但无记录

**IDs of affected creatures, items, quests or spells with a link to the relevant page:**

NPC: https://database.turtle-wow.org/?npc=
![1705540334086](https://github.com/slowtorta/turtlewow-bug-tracker/assets/156974556/076b217d-2d1b-48f1-b265-1176ee542ac8)

Item: https://database.turtle-wow.org/?item=
![1705540372250](https://github.com/slowtorta/turtlewow-bug-tracker/assets/156974556/908cafd1-4fc1-4689-b83e-23f0c4490d71)

Quest: https://database.turtle-wow.org/?quest=
Spell: https://database.turtle-wow.org/?spell=
Object: https://database.turtle-wow.org/?object=

**Expected behavior. Describe how it should work:**

**Comment by twowTurtReynolds** [comment]
请用英文提交问题。我们无法通过自动翻译准确地翻译中文提交的错误报告，这使得我们难以理解问题的确切性质。谢谢！

Please submit the issues in English. We're unable to accurately translate bug reports submitted in Chinese through automatic translation, which makes it difficult for us to understand the exact nature of the issue. Thank you!
