### ISSUE TITLE
Goblin Brainwashing Device, doesn't save spec

### ISSUE THREAD

**Issue by muchodotcool** [slowtorta/turtlewow-bug-tracker#6030]
**Please, provide a clear description what the bug is:**
Goblin Brainwashing Device, doesn't save my specs after a game crash forced to respecc each time. 
**Steps to reproduce the behavior with as much detail as possible:**

1.Respec talents 
2. Put out talent 
3. Save in Goblin brainwashing device 

**Expected behavior. Describe how it should work:**
it should save the talents. 
![Screenshot 2024-01-18 103053](https://github.com/slowtorta/turtlewow-bug-tracker/assets/156978998/89acab79-0f47-4429-be55-3bd9e2a16e27)

**Comment by twowTurtReynolds** [comment]
![image](https://github.com/slowtorta/turtlewow-bug-tracker/assets/151180101/4f56cdc2-5680-4259-91ed-b4b04f2e23a4)
I used task manager to force kill the game, preventing it from saving like a crash would.

The spec I made survived the crash and works.
