### ISSUE TITLE
Verdant Eye Necklace

### ISSUE THREAD

**Issue by Soklive** [slowtorta/turtlewow-bug-tracker#6031]
This necklace, based on its description, should provide 5% Mana regeneration when casting spells, but it does not work.

1. I lowered my character's Mana to zero and looked at how much Mana was refilled every 2 seconds when the Verdant Eye Necklace was equipped on my character. Recovered 25 Mana every 2 seconds. 
2. I removed the Verdant Eye Necklace from my character and repeated step 1. The amount of Mana restored has not changed (also 25).
3. I concluded that the 5% Mana regeneration that this item should provide does not work.

Item: https://database.turtle-wow.org/?item=61193

This neck should provide 5% Mana regeneration in battle, as stated in the description. 

Update. 
After looking at other topics and talking with people, I came to the conclusion that this item works, but there is another problem - this 5% mana regeneration does not stack with the priest’s talents. This seems to be the main problem.

**Comment by ratkosrb** [comment]
I tested it and it works for me. My mana goes up while spam casting while wearing it.

**Comment by schanzee** [comment]
Are you a priest? See https://github.com/slowtorta/turtlewow-bug-tracker/issues/1750

**Comment by Soklive** [comment]
> Are you a priest? See #1750

Yes. I'm playing a Priest and my Mana regen doesn't increase when wearing this item. 

I read the thread you posted above. Thank you. It seems that the real issue is that the effects of mana regeneration from items do not stack with the priest's talents, but one way or another this should not be the case. The percentages of mana regeneration from items should be summed up, as is the case with talents and set bonuses.

**Comment by twowTurtReynolds** [comment]
Closing as a duplicate, please subscribe to the main report.

I am going to need to set aside some time to really get some solid proof on whether or not this is working.
