### ISSUE TITLE
Training Dummys can be moved with Death coil from Warlocks

### ISSUE THREAD

**Issue by Josephienvandermeersch** [slowtorta/turtlewow-bug-tracker#6032]
Training Dummy - Moved to other location cause of fear of Death  coil

Not much more needed of information see screenshot

![image](https://github.com/slowtorta/turtlewow-bug-tracker/assets/24510505/7713a876-6479-4b88-88fa-a97dabb49e86)

**Comment by Josephienvandermeersch** [comment]
![image](https://github.com/slowtorta/turtlewow-bug-tracker/assets/24510505/d23dd633-b3dd-4761-b7a7-4d5547a911f2)

**Comment by ratkosrb** [comment]
Should be fixed in the next update.
