### ISSUE TITLE
Unable to enchant Drape of Nordrassil

### ISSUE THREAD

**Issue by SopieMunky** [slowtorta/turtlewow-bug-tracker#6036]
**Please, provide a clear description what the bug is:**
I just purchased the Drape of Nordrassil with 150 Dream Shards from Hyjal so I didn't have to farm another cloak from ZG. When my guildy tried to enchant it, it said "This cloth must be equipped." So I then went to the Auction House to purchase the recipe and try it with my own enchanting. When I tried to enchant it, it says that "this item is not a valid target."

At this point I would rather just have my 150 Dream Shards and the 20g I spent on the Auction House to get the recipe refunded. If I had known there was a bug with this item I would've never wasted my shards on it. It took me weeks to farm those.

**Steps to reproduce the behavior with as much detail as possible:**

1. Tried to enchant cloak. Didn't work.
2. Someone else tried to enchant cloak. Didn't work.
3. Someone else tried to enchant cloak. Didn't work.

**IDs of affected creatures, items, quests or spells with a link to the relevant page:**

NPC: https://database.turtle-wow.org/?npc=
Item: https://database.turtle-wow.org/?item=61753
Quest: https://database.turtle-wow.org/?quest=
Spell: https://database.turtle-wow.org/?spell=16216
Object: https://database.turtle-wow.org/?object=

**Expected behavior. Describe how it should work:**
It should be enchantable.

**Comment by Dragunovi** [comment]
Please check similiar issues before posting a bug report, this issue should be fixed next restart.
