### ISSUE TITLE
Firebrand Invoker casts fire nova out of combat

### ISSUE THREAD

**Issue by AKryukov92** [slowtorta/turtlewow-bug-tracker#6039]
**Please, provide a clear description what the bug is:**
Firebrand invoker periodically casts fire nova when he is not engaged in combat.

**Steps to reproduce the behavior with as much detail as possible:**

1. Enter LBRS
2. Go to orc part before spiders
3. Watch how firebrand invokers cast stuff.

**IDs of affected creatures, items, quests or spells with a link to the relevant page:**

https://database.turtle-wow.org/?npc=9262

**Expected behavior. Describe how it should work:**
He should cast fire nova only when in combat.

**Comment by ratkosrb** [comment]
Should be fixed in the next update.
