### ISSUE TITLE
Before  Damian <The Ripper>  died，he quickly killed our tank

### ISSUE THREAD

**Issue by WTFAMD** [slowtorta/turtlewow-bug-tracker#6040]
**Please, provide a clear description what the bug is:**
Before  Damian <The Ripper>  died，he quickly killed our tank
**Steps to reproduce the behavior with as much detail as possible:**

1.Before  Damian <The Ripper>  died，he quickly killed our tank
2. There is no damage taken in the combat record
3. The tank's health is still over 90%
4. Damian <The Ripper>Faction ID: 233 Display ID: 4867 Equipment ID: 10504

**IDs of affected creatures, items, quests or spells with a link to the relevant page:**

NPC: https://database.turtle-wow.org/?npc=
Item: https://database.turtle-wow.org/?item=
Quest: https://database.turtle-wow.org/?quest=
Spell: https://database.turtle-wow.org/?spell=
Object: https://database.turtle-wow.org/?object=

**Expected behavior. Describe how it should work:**

**Comment by WTFAMD** [comment]
Asian servers  playerID 一号位凯瑞

**Comment by WTFAMD** [comment]
We are Level 60 HC players
If it's due to a bug, it would be too unacceptable to die

**Comment by ratkosrb** [comment]
It seems to be an intentional feature of his script that he instakills players.

**Comment by twowTurtReynolds** [comment]
@ratkosrb If I remember correctly, it is indended for him to kill a player once per fight, **but only** if they drop below 20%.

**Comment by WTFAMD** [comment]
Our tank's health is still over 90%

**Comment by WTFAMD** [comment]
It was all very sudden

**Comment by WTFAMD** [comment]
![Uploading 11111111.jpg…]()

**Comment by ratkosrb** [comment]
I'll change his script so he deals damage with a spell instead of just setting player to dead with no trace in combat log.

**Comment by WTFAMD** [comment]
If it's due to a bug, it would be too unacceptable to die

**Comment by WTFAMD** [comment]
I still want to ask if it is possible to revive our Tanks？ @ratkosrb

**Comment by twowTurtReynolds** [comment]
Please read the disclaimer upon accepting the hardcore challenge.
