### ISSUE TITLE
AH Telabim | Gyrofreeze Ice Reflector mislabeled as Trade Goods

### ISSUE THREAD

**Issue by Slimthegrim** [slowtorta/turtlewow-bug-tracker#6041]
**Please, provide a clear description what the bug is:**
When shopping on the auction house, you'll notice that not all trinkets are listed under trinkets in Armor/Miscellaneous. Some engineering trinkets, such as the listed Gyrofreeze Ice Reflector only list under Trade Goods. 

See Trade Goods/Rare search result containing trinket:
![image](https://github.com/slowtorta/turtlewow-bug-tracker/assets/110629519/ca8e77cb-9699-4af0-ac4a-6a86769ba86e)

See all trinkets within Armor category does not contain this known engineering trinket but contains another:
![image](https://github.com/slowtorta/turtlewow-bug-tracker/assets/110629519/6666c1c1-665e-42be-afee-c7a5dca71214)

**Steps to reproduce the behavior with as much detail as possible:**

1. Go to auction house.
2. Search all Trade Goods Rare+
3. See a trinket surprisingly in listings
4. Try and find trinket in right Armor/ category, notice AH search fails 
5. Wonder to yourself if other reflectors are mislabeled
6. Double confirm doesn't matter if AH addon or vanilla AH, same result

**IDs of affected creatures, items, quests or spells with a link to the relevant page:**
Object: https://database.turtle-wow.org/?object=](https://database.turtle-wow.org/?item=18634)

**Expected behavior. Describe how it should work:**
I believe Turtle should clearly define ANY wearable trinket should be in Armor/Miscellaneous/Trinket category only

**Comment by Slimthegrim** [comment]
Following up with vanilla AH interface evidence showing this trinket is missing from Armor/Misc/Trinkets as well.

![image](https://github.com/slowtorta/turtlewow-bug-tracker/assets/110629519/a7d386e9-dccd-4997-be37-38adaa964741)

**Comment by Dragunovi** [comment]
Should be fixed with next server restart.
