### ISSUE TITLE
Permafrost not applying to Cone of Cold

### ISSUE THREAD

**Issue by jc473** [slowtorta/turtlewow-bug-tracker#6045]
**Please, provide a clear description what the bug is:**
The Cone of Cold spell is not receiving the 10% extra slow from the talent Permafrost.
The tooltip for Cone of Cold says it should apply a 60% slow but when you hit a mob with this spell, the debuff only shows it being slowed by 50%. Frostbolt only slows for 50% and I can visibily see no difference in movement speed when I then cast Cone of Cold on the same mob.

**Steps to reproduce the behavior with as much detail as possible:**
1. Take 3/3 Permafrost talent.
2. Cast a Cone of Cold spell on any mob.
3. Observe the Cone of Cold debuff on them and it will state that it is slowing them by 50%
4. Optional - With 3/3 Permafrost, slow any mob with a Frostbolt and then cast Cone of Cold on it too. You will notice that there is no difference in movement speed. This suggests that this is NOT just a tooltip bug.

**IDs of affected creatures, items, quests or spells with a link to the relevant page:**
Any mob but I noticed it with the mobs in Ravenhill Cemetery in Duskwood.

Spell: https://database.turtle-wow.org/?spell=120

**Expected behavior. Describe how it should work:**
With 3/3 Permafrost, Frostbolt should slow a mob by 50% and Cone of Cold should slow it by 60%.

**Comment by twowTurtReynolds** [comment]
Similar to https://github.com/slowtorta/turtlewow-bug-tracker/issues/6013

**Comment by twowTurtReynolds** [comment]
https://github.com/slowtorta/turtlewow-bug-tracker/issues/6013#issuecomment-1901206531
