### ISSUE TITLE
Nordaanar herbal tea shares CD with Alliance Battle standard (pvp) 

### ISSUE THREAD

**Issue by addiktedd** [slowtorta/turtlewow-bug-tracker#6046]
**Please, provide a clear description what the bug is:**

**Steps to reproduce the behavior with as much detail as possible:**

1.Place Flag and both share CD and vice-versa (use tea and flag is on cd) 
2. 
3. 

**IDs of affected creatures, items, quests or spells with a link to the relevant page:**

NPC: https://database.turtle-wow.org/?npc=
Item: https://database.turtle-wow.org/?item=
Quest: https://database.turtle-wow.org/?quest=
Spell: https://database.turtle-wow.org/?spell=
Object: https://database.turtle-wow.org/?object=

**Expected behavior. Describe how it should work:**

**Comment by balakethelock** [comment]
https://www.wowhead.com/classic/item=18606/alliance-battle-standard#shared-cooldown
not a bug
