### ISSUE TITLE
Hand of reckoning (improved seal of justice) not showing timer values on debuff tracking

### ISSUE THREAD

**Issue by lyssebabz** [slowtorta/turtlewow-bug-tracker#6047]
https://streamable.com/ax1z2k 

Talent: https://database.turtle-wow.org/?spell=45805

Warrior Taunt (for comparison)
![warar taunt](https://github.com/slowtorta/turtlewow-bug-tracker/assets/20995435/8e4cf44c-4b3b-4629-b79e-e18b6e73ded7)

Paladin Taunt 
![palattaunt](https://github.com/slowtorta/turtlewow-bug-tracker/assets/20995435/a12aac44-dc79-4fcd-8532-6736febb48b2)

Paladin Hand of Reckoning should show a 3 second timer like the other taunts e.g Taunt, Growl

**Comment by balakethelock** [comment]
Umm karen.. that's an addon problem not a bug :'|
