### ISSUE TITLE
Built inn unitframe target status text 

### ISSUE THREAD

**Issue by Bensonhere** [slowtorta/turtlewow-bug-tracker#605]
When enabling status text for unitframes in the interface options, it enables text and percentage hp for target unitframes. The status text stands in the way of unitrframe addons. I want to know how to disable the built inn target status text.

![disable-frame](https://user-images.githubusercontent.com/96787149/147586142-d6dc6754-1a79-496f-b965-bd2fc589dfd9.png)

**Comment by Tinyfin-github** [comment]
Greetings Please go to interface and disable status text.
