### ISSUE TITLE
Guardian of the Gate 40115 cant reaccept quest after abandoning

### ISSUE THREAD

**Issue by GekkeMannie1** [slowtorta/turtlewow-bug-tracker#6050]
I abandoned "Guardian of the Gate" (qid: 40115) but now can't get the quest anymore from the pedestal.

**Steps to reproduce the behavior with as much detail as possible:**

1.Have Guardian of the Gate 40115
2.Abandon 40115
3. Can't reaccept quest again (even after closing client and clearing WDB)

**IDs of affected creatures, items, quests or spells with a link to the relevant page:**

NPC: https://database.turtle-wow.org/?npc=
Item: https://database.turtle-wow.org/?item=
Quest: https://database.turtle-wow.org/?quest=40115
Spell: https://database.turtle-wow.org/?spell=
Object: https://database.turtle-wow.org/?object=142343

**Expected behavior. Describe how it should work:**
Abandon quest. Ability to reaccept quest from same place.

**Comment by twowTurtReynolds** [comment]
This bug should be fixed by the fix of https://github.com/slowtorta/turtlewow-bug-tracker/issues/6022.
