### ISSUE TITLE
Armored White Steed item taught me Swift White Steed mount

### ISSUE THREAD

**Issue by Shellyoung** [slowtorta/turtlewow-bug-tracker#6051]
**Please, provide a clear description what the bug is:**
Greetings. The model shows it is Swift White Steed mount, not Armored White Steed, I suppose.
![WoW_b7IIdP0988](https://github.com/slowtorta/turtlewow-bug-tracker/assets/40469927/b7ea5e95-9c9a-4998-90c8-050491344350)
![WoW_i0D4xuKUey](https://github.com/slowtorta/turtlewow-bug-tracker/assets/40469927/e4f9764b-3e59-466a-9d01-17f45d3050c5)

**Steps to reproduce the behavior with as much detail as possible:**

1. Buy [Armored White Steed](https://database.turtle-wow.org/?item=18778)
2. Learn it.

**IDs of affected creatures, items, quests or spells with a link to the relevant page:**
Item: https://database.turtle-wow.org/?item=18778

**Expected behavior. Describe how it should work:**
I think it should teach me to ride not a Swift White Steed mount, but something else.

**Comment by twowTurtReynolds** [comment]
Until this bug is fixed, please contact a GM about getting spell 23228 learned to you.

**Comment by Shellyoung** [comment]
GM's (Saelas) answer: "Greetings! System says that you have already know that spell, unfortunately developers need to take a look, there is no another spell i can teach you, please, add this to your report."

**Comment by Shellyoung** [comment]
I guess there are same items. Armored White Stead teaches Swift White Steed mount. 
Item 18778 is [Armored White Steed](https://database.turtle-wow.org/?item=18778) on Turtle WoW and [Swift White Steed](https://www.wowhead.com/classic/item=18778) on WoW Classic.
