### ISSUE TITLE
Clamlette Surprise

### ISSUE THREAD

**Issue by rmattox1277** [slowtorta/turtlewow-bug-tracker#6053]
I've completed Quest ID 6610 for item 16971 and I never was taught the recipe to create more.

I messaged a GM and asked to have the recipe added to my cooking and was told to submit a bug report here.

My character name is Udderworldly on Nordanaar.

**Comment by Jan125** [comment]
The Clamlette Surprise recipe was added in a later patch.

**Comment by slowtorta** [comment]
There's no such recipe in Vanilla WoW :)
