### ISSUE TITLE
Breathing meter appears on surface in Thalassian Islands

### ISSUE THREAD

**Issue by ffann1998** [slowtorta/turtlewow-bug-tracker#6054]
Breathing meter appears on surface in Thalassian Islands. Coodrinates: 48.7/46.5
![WoWScrnShot_012024_194423](https://github.com/slowtorta/turtlewow-bug-tracker/assets/87450254/fc0d1511-2d5b-4689-8e81-7065c83c67cb)

**Comment by twowTurtReynolds** [comment]
Please read the pinned issues.
