### ISSUE TITLE
2H and and a shield

### ISSUE THREAD

**Issue by TheGardak** [slowtorta/turtlewow-bug-tracker#6056]
**Please, provide a clear description what the bug is:**
I saw paladins and shamys using 2H weapons and shields. Its a visual bug or they get the stats of the shield?

**Steps to reproduce the behavior with as much detail as possible:**
Some kind of macro 
1.
2. 
3. 

**IDs of affected creatures, items, quests or spells with a link to the relevant page:**
![imagen_2024-01-20_175238381](https://github.com/slowtorta/turtlewow-bug-tracker/assets/156102523/aece9bce-39ca-44a2-b3f0-812f255cc307)

NPC: https://database.turtle-wow.org/?npc=
Item: https://database.turtle-wow.org/?item=
Quest: https://database.turtle-wow.org/?quest=
Spell: https://database.turtle-wow.org/?spell=
Object: https://database.turtle-wow.org/?object=

**Expected behavior. Describe how it should work:**

**Comment by twowTurtReynolds** [comment]
Looks to be a visual bug, maybe due to your addons. The armory confirms they only have the 2h equipped:
![image](https://github.com/slowtorta/turtlewow-bug-tracker/assets/151180101/a45a910c-d9ea-407e-ae0d-57cfb2315e52)
