### ISSUE TITLE
The quest "A Little Luck" seems to be missing

### ISSUE THREAD

**Issue by Lichbanez** [slowtorta/turtlewow-bug-tracker#6057]
The NPC Harlo Wigglesworth doesn't start the quest for me also on the database it's flagged as horde only but according to wowpedia both faction can take it and I don't know if the change was intended or not.

NPC: https://database.turtle-wow.org/?npc=11755
Quest: https://database.turtle-wow.org/?quest=6606

The NPC normally gives this quest to both Alliance and Horde, I can't see the quest as alliance and unfortunately I don't have any horde character to check.

**Comment by twowTurtReynolds** [comment]
This is a breadcrumb quest it seems. removed by 1.12 so not present on classic nor Twow.

**Comment by Lichbanez** [comment]
Ok thanks for the fast response I checked here https://wowpedia.fandom.com/wiki/A_Little_Luck and it said that it was removed during Cata (Patch 4.0.3a).
