### ISSUE TITLE
德鲁伊进潜行无法自动切换主动作条

### ISSUE THREAD

**Issue by nathan16888** [slowtorta/turtlewow-bug-tracker#6059]
**Please, provide a clear description what the bug is:**
服务器名：endless sea 职业：德鲁伊 角色名：泰勒斯
进潜行后无法自动切换主动作条。
**Steps to reproduce the behavior with as much detail as possible:**

1. 删除了旧的客户端，重新下载安装的官网新客户端。
2. 未使用任何插件。
3. 未开启加速器。
4. 自从上次服务器重启后出现。
5. 电脑系统为Windows11。

**IDs of affected creatures, items, quests or spells with a link to the relevant page:**

NPC: https://database.turtle-wow.org/?npc=
Item: https://database.turtle-wow.org/?item=
Quest: https://database.turtle-wow.org/?quest=
Spell: https://database.turtle-wow.org/?spell=
Object: https://database.turtle-wow.org/?object=

**Expected behavior. Describe how it should work:**
之前正常，自上次服务器重启后出现异常，询问过别的玩家，没有相同BUG。
<img width="1000" alt="1_副本" src="https://github.com/slowtorta/turtlewow-bug-tracker/assets/157255771/b3a983c5-db99-46fa-b59c-44ad5734822b">
<img width="1000" alt="2_副本" src="https://github.com/slowtorta/turtlewow-bug-tracker/assets/157255771/411d040f-fa81-4459-8494-071a807430fc">

**Comment by twowTurtReynolds** [comment]
请用英文提交问题。我们无法通过自动翻译准确地翻译中文提交的错误报告，这使得我们难以理解问题的确切性质。谢谢！

Please submit the issues in English. We're unable to accurately translate bug reports submitted in Chinese through automatic translation, which makes it difficult for us to understand the exact nature of the issue. Thank you!
