### ISSUE TITLE
[Warrior] Diamond flask heal less

### ISSUE THREAD

**Issue by Khanz0** [slowtorta/turtlewow-bug-tracker#606]
Helll fello turtles. Just notices with the last patch my diamond flask healing is lesser. With my +healing gear it healed me more than 400 hp per tick. Today healed me for 200hp. 

More warriors are having the same issue

Link of item: https://classicdb.ch/?item=20130

**Comment by Khanz0** [comment]
Anyone noticed?

Hello?

(Windy sound)

**Comment by itswicky** [comment]
I don't recall the structure for Vmangos db, but if there is a spell_bonus table, then it likely needs an entry there, otherwise there should be a similar column in spell.dbc for the corresponding effect.

**Comment by Velite12** [comment]
Can confirm this is still present.

**Comment by ratkosrb** [comment]
The healed amount is exactly what is expected.
100% of bonus healing + 9 base value

https://streamja.com/92Rok
