### ISSUE TITLE
Missing Engineering Recipe: Goblin Rocket Fuel

### ISSUE THREAD

**Issue by shumarte** [slowtorta/turtlewow-bug-tracker#6063]
**Please, provide a clear description what the bug is:**
I cannot see Engineering recipe: Goblin Rocket Fuel, despite game says it's "Already known". GM tried to re-teach it. Didn't work. I tried with and without addons. Deleted WDM folder aswell.
Can't really fill out next 1-3, as it's a continous bug on my character Legitpally.
**Steps to reproduce the behavior with as much detail as possible:**
1. 
2. 
3. 

**IDs of affected creatures, items, quests or spells with a link to the relevant page:**

Character: https://armory.turtle-wow.org/#!/character/Legitpally
Missing recipe: https://www.wowhead.com/classic/item=10644/recipe-goblin-rocket-fuel

NPC: https://database.turtle-wow.org/?npc=
Item: https://database.turtle-wow.org/?item=10644
Quest: https://database.turtle-wow.org/?quest=
Spell: https://database.turtle-wow.org/?spell=
Object: https://database.turtle-wow.org/?object=

**Expected behavior. Describe how it should work:**
I expect to see my recipe in my list.

**Comment by twowTurtReynolds** [comment]
![image](https://github.com/slowtorta/turtlewow-bug-tracker/assets/151180101/c6bddc78-c5e3-4c7c-81ab-20493d1c1dac)
The trainer has the spell, and learning it worked, and crafting it worked.

![image](https://github.com/slowtorta/turtlewow-bug-tracker/assets/151180101/6f6081f2-cc42-4268-a341-f47689b14c99)
![image](https://github.com/slowtorta/turtlewow-bug-tracker/assets/151180101/8abcb3b8-4cfd-451a-88b8-210ec1d0557f)

I am not sure how you got into the state that you did.

Please make a followup GM ticket and specify that the ID you need to learn is 12715.
![image](https://github.com/slowtorta/turtlewow-bug-tracker/assets/151180101/43142878-d54c-4f59-a26b-9909b9bb54ad)
