### ISSUE TITLE
bug quest lord valthalak`s ( chain quest mage tier t0,5

### ISSUE THREAD

**Issue by galfer91** [slowtorta/turtlewow-bug-tracker#6067]
Hello again, sorry for all the tickets. I have completed this chain of missions and I have already dropped the mission item. but I have continued doing the missions after BRD and when I have gone to complete the mission with the 3 mission items. top piece, left part and right part. The top part has disappeared from my bag and I cannot complete the mission. I have tried to get it back into brd with the flag in place and nothing. I have restarted the dungeon 4 times with friends and nothing.

**Comment by twowTurtReynolds** [comment]
Duplicate of https://github.com/slowtorta/turtlewow-bug-tracker/issues/5828

If you haven't contacted Support already, to fix your specific case, please do.

**Comment by galfer91** [comment]
and i deleted de folder WTB 3 times...

**Comment by galfer91** [comment]
But I'm not missing the banner, I'm missing a part of the amulet.
