### ISSUE TITLE
Kex Blowmaster not Targetable

### ISSUE THREAD

**Issue by Matt-Langevin** [slowtorta/turtlewow-bug-tracker#6069]
**Please, provide a clear description what the bug is:**
Unable to target or talk to Kex Blowmaster in southern Barrens

**Steps to reproduce the behavior with as much detail as possible:**

1. Go to Kex Blowmaster
2. Try to talk to him for quest
3. Unable to target or talk to him

**IDs of affected creatures, items, quests or spells with a link to the relevant page:**

NPC: https://database.turtle-wow.org/?npc=60443
Item: https://database.turtle-wow.org/?item=
Quest: https://database.turtle-wow.org/?quest=41102
Spell: https://database.turtle-wow.org/?spell=
Object: https://database.turtle-wow.org/?object=

**Expected behavior. Describe how it should work:**
Should be able to talk to him and complete quest.

**Comment by ratkosrb** [comment]
Should be fixed after the next update.
