### ISSUE TITLE
Black Riding Boots are unable to be repaired (recolor of Brown-Topped Riding Boots)

### ISSUE THREAD

**Issue by jason-burke-dev** [slowtorta/turtlewow-bug-tracker#6071]
**Please, provide a clear description what the bug is:**
Item: Black Riding Boots (common quality) is unable to be repaired.

**Steps to reproduce the behavior with as much detail as possible:**

1. Lose durability on Black Riding Boots
2. Attempt to repair at a merchant using "Repair an item" or "Repair all items" in the merchant window
3. Not able to repair

**IDs of affected creatures, items, quests or spells with a link to the relevant page:**

This should be the NPC (Alix Gres <Maison Serendipity>) who sells the boots, the boots do not return a result on the database (see below).
NPC: https://database.turtle-wow.org/?npc=61896

This is the item (Brown-Topped Riding Boots) in a different color as the boots are offered in multiple colors so the ID may be close to this.
Item: https://database.turtle-wow.org/?item=41259

**Expected behavior. Describe how it should work:**
Should be able to repair item like any other gear.

**Comment by twowTurtReynolds** [comment]
These two boots can't be repaired:
![image](https://github.com/slowtorta/turtlewow-bug-tracker/assets/151180101/ffa6339f-1bcb-445f-9f7e-a9cede50ecd0)
![image](https://github.com/slowtorta/turtlewow-bug-tracker/assets/151180101/a167d3ef-8f0e-4de6-b51a-decf0b8c3719)
This one I tried from the same vendor can:
![image](https://github.com/slowtorta/turtlewow-bug-tracker/assets/151180101/932d7d31-bc6e-461f-9692-4bb94af3aab9)
