### ISSUE TITLE
Can't turn in "Gates of Uldum" quest

### ISSUE THREAD

**Issue by koontz946** [slowtorta/turtlewow-bug-tracker#6072]
**Please, provide a clear description what the bug is:**
I followed the directions on the quest, and have the two plates in my bags.  When I go to the Pedestal to turn the quest in, it gives me a dialog window with no options to click except Goodbye.  Am unable to complete the quest.

**Steps to reproduce the behavior with as much detail as possible:**

1. Gather the two plates of Uldum (Plate of Uldum and Second Plate of Uldum) and have them in your inventory
2. Go to Tanaris, to the Uldum Pedestal
3. Click on the Uldum Pedestal

**IDs of affected creatures, items, quests or spells with a link to the relevant page:**

Item: https://database.turtle-wow.org/?item=60102
https://database.turtle-wow.org/?item=60103
Quest: https://database.turtle-wow.org/?quest=40106

**Expected behavior. Describe how it should work:**
I guess complete the quest and move on to the next quest in the chain?

<img width="1099" alt="Uldum1" src="https://github.com/slowtorta/turtlewow-bug-tracker/assets/148662006/13b30206-9f87-41a3-be25-f8d22bf6f91d">
<img width="897" alt="Uldum2" src="https://github.com/slowtorta/turtlewow-bug-tracker/assets/148662006/683a9649-f066-46fe-b5ff-710bdbf2b503">

**Comment by koontz946** [comment]
Character affected is Linissa on Tel'Abim

**Comment by twowTurtReynolds** [comment]
Duplicate of https://github.com/slowtorta/turtlewow-bug-tracker/issues/6022
