### ISSUE TITLE
Gavel of Guilnean Justice Transmog

### ISSUE THREAD

**Issue by winfire333** [slowtorta/turtlewow-bug-tracker#6074]
**Please, provide a clear description what the bug is:**

I transmogged The Crimson Spellblade to look like Gavel of Guilnean (which should sit on your back) however it doesn't do that. 
After I transmogged it, it sits on my leg. 

**Steps to reproduce the behavior with as much detail as possible:**

1.
2. 
3. 

**IDs of affected creatures, items, quests or spells with a link to the relevant page:**

Character name : Winrath (Alliance, human paladin)

https://database.turtle-wow.org/?item=61308
https://database.turtle-wow.org/?item=81018

**Expected behavior. Describe how it should work:**

**Comment by winfire333** [comment]
Character name : Winrath, Alliance, human paladin.

**Comment by twowTurtReynolds** [comment]
Same issue as https://github.com/slowtorta/turtlewow-bug-tracker/issues/4046
