### ISSUE TITLE
guild bank/guild vault doesnt record the logs and shows a lua error.

### ISSUE THREAD

**Issue by orcytanky** [slowtorta/turtlewow-bug-tracker#6076]
**Please, provide a clear description what the bug is:**

when i open the gbank log tab page, there is a lua error and the gbankgvault doesnt record the logs. 
i did change some option who can use how many items can be used and changed the name and selected the icon. i have changed many times when i first opened guild vault.

there is a lua error when i opened the log tab/page. i have posted it into support channel in twow discord.

![image](https://github.com/slowtorta/turtlewow-bug-tracker/assets/151180101/7356f489-1fd0-4a05-b148-2e8bb2f7e61f)

i wont be able to fill the rest of the details u are asking.

**Steps to reproduce the behavior with as much detail as possible:**

1. 
2. 
3. 

**IDs of affected creatures, items, quests or spells with a link to the relevant page:**

NPC: https://database.turtle-wow.org/?npc=
Item: https://database.turtle-wow.org/?item=
Quest: https://database.turtle-wow.org/?quest=
Spell: https://database.turtle-wow.org/?spell=
Object: https://database.turtle-wow.org/?object=

**Expected behavior. Describe how it should work:**

**Comment by twowTurtReynolds** [comment]
Please install a fresh client and see if the issue persists.

**Comment by orcytanky** [comment]
guildies are receiving lua error 676, too.
searched about guildies and my addons. those are not related with each other. the problem is related with UI or twow options. no idea really. after lua error, guild master can not use the guild vault. but the realy problem is that guild vault doesnt record the logs.

**Comment by orcytanky** [comment]
ok new update: whevener i change the limits and the ranks guildies are receiving lua error 676. gbank still doesnt record the logs.

**Comment by orcytanky** [comment]
i have done many changes regarding guild bank ranks' and limits' permission in order to understand how the things work.

**Comment by orcytanky** [comment]
maybe i have changed the ranks and limits so much that might be the issue.

**Comment by orcytanky** [comment]
problem has been fixed after restart of server

**Comment by twowTurtReynolds** [comment]
Interesting... I will keep an eye out for similar issues and if we can iron out replication steps, we could fix whatever problem is causing this to potentially crop up.
