### ISSUE TITLE
Kargron's Leggings - Item Stats Either Incorrect, or listed incorrectly.

### ISSUE THREAD

**Issue by OonaFae** [slowtorta/turtlewow-bug-tracker#6077]
**Please, provide a clear description what the bug is:**
The Rare Spawn Blademaster Kargron has a chance to drop Kargron's Leggings, these pants show 2% parry being listed twice when queried to the server. I haven't been able to find someone to confirm if they actually give 4% Parry or just the 2%. 

**Steps to reproduce the behavior with as much detail as possible:**

1. Loot Kargron's Leggings
2. Equip them and check stats to see if you get 4% Parry

![image](https://github.com/slowtorta/turtlewow-bug-tracker/assets/105398809/89377d2c-e71a-45a7-96b4-bb268a317b61)

**IDs of affected creatures, items, quests or spells with a link to the relevant page:**

NPC: https://database.turtle-wow.org/?npc=49002
Item: https://database.turtle-wow.org/?item=81365

**Expected behavior. Describe how it should work:**
Either these pants should only be giving 2% and it was duplicated in error, or the tooltip should be changed to show 4% on a single line.

**Comment by twowTurtReynolds** [comment]
![image](https://github.com/slowtorta/turtlewow-bug-tracker/assets/151180101/bb927209-2f6f-44ac-b5f4-da82d24480b0)
They were meant to have these stats. The fix will be arriving soon. Clear WDB after each weekly maintenance.
