### ISSUE TITLE
Skinning Trainer in Alah'Thalas doesn't teach you skinning

### ISSUE THREAD

**Issue by bean157** [slowtorta/turtlewow-bug-tracker#6079]
**The skinning trainer in Alah'Thalas does not let you train skinning from Daemar Swiftstrike. If you try, you will get a window popping up asking if skinning is 1 of the 2 professions you want to train. If you click yes, 10 copper is not taken, and the window goes away and you still don't know skinning. I have asked if other people have this issue and they confirmed the same thing happened to them.**

**Steps to reproduce the behavior with as much detail as possible:**

1. Go to skinning trainer
2. Select YES, you would like it to be one of your professions and click yes.
3. Nothing happens - you don't learn the profession

**IDs of affected creatures, items, quests or spells with a link to the relevant page:**

NPC: https://database.turtle-wow.org/?npc=    Your website does not list the skinning trainer (Daemar Swiftstrike) in Alah'Thalas as a skinning trainer

**Expected behavior. Describe how it should work:**
It should teach you skinning.

**Comment by ratkosrb** [comment]
He should be fixed after the next update.

**Comment by bean157** [comment]
Thank you! I'm really enjoying this server!
