### ISSUE TITLE
First Settlement Quest chain grants Shatterspear rep instead of Silvermoon Remnants

### ISSUE THREAD

**Issue by Valamartle** [slowtorta/turtlewow-bug-tracker#608]
**Please, provide a clear description what the bug is:**
When completing the new level 30 The First Settlement quest chain Silvermoon Remnants starting in Alah'thalas, the reputation gained is actually shatterspear. 
**Steps to reproduce the behavior with as much detail as possible:**

1.On a Level 30+? Character, collect the Quest, the First Settlement from Alaha'thalas
2. Follow the chain
3. Completing quests gives Shatterspear Rep

**IDs of affected creatures, items, quests or spells with a link to the relevant page:**
Can't get them from the DB due to the lock at the moment. 
NPC: https://database.turtle-wow.org/?npc=
Item: https://database.turtle-wow.org/?item=
Quest: https://database.turtle-wow.org/?quest=
Spell: https://database.turtle-wow.org/?spell=
Object: https://database.turtle-wow.org/?object=

**Expected behavior. Describe how it should work:**
It should grant Silvermoon Remnant Rep.

**Comment by zac32** [comment]
The same thing happened to me. Will it be possible to get back that reputation for Silvermoon?
