### ISSUE TITLE
Lord Blackwald II evading

### ISSUE THREAD

**Issue by Icfre** [slowtorta/turtlewow-bug-tracker#6080]
**Please, provide a clear description what the bug is:**
Lord Blackwald II continuously evades and resets aggro 

**Steps to reproduce the behavior with as much detail as possible:**

1. Form group for lower karazhan
2. Pull lord blackwald II
3.  He will continously reset aggro

**IDs of affected creatures, items, quests or spells with a link to the relevant page:**

NPC: https://database.turtle-wow.org/?npc=
Item: https://database.turtle-wow.org/?item=
Quest: https://database.turtle-wow.org/?quest=
Spell: https://database.turtle-wow.org/?spell=
Object: https://database.turtle-wow.org/?object=

**Expected behavior. Describe how it should work:**

**Comment by hjortmar** [comment]
+1 on this. It also prevents you from killing Moroes which is somewhat frustrating.

**Comment by twowTurtReynolds** [comment]
This is a known bug that has been fixed and is awaiting deployment. Until the patch hits live, please contact a GM with an ingame ticket for them to apply the workaround for your team.
