### ISSUE TITLE
Tela'bim | Goblins are unable to click summoning portals while swimming

### ISSUE THREAD

**Issue by Slimthegrim** [slowtorta/turtlewow-bug-tracker#6081]
**Please, provide a clear description what the bug is:**
Goblins are unable to click summoning portals while swimming but other races able to.

![image](https://github.com/slowtorta/turtlewow-bug-tracker/assets/110629519/9cd0a5c0-0193-46ee-ab17-5714f6e0b5f1)

**Steps to reproduce the behavior with as much detail as possible:**

1. Be goblin
2. Goto Summon Group in water!
3. Click the summon portal as a goblin and get an Error "Cannot use while swimming".

**IDs of affected creatures, items, quests or spells with a link to the relevant page:**

Another warlock's summoning portal.

**Expected behavior. Describe how it should work:**
Other horde races are able to click portals while swimming. Goblins should be able to (if only after bribe ;)

**Comment by twowTurtReynolds** [comment]
![image](https://github.com/slowtorta/turtlewow-bug-tracker/assets/151180101/76ec1454-20a2-4ab7-8046-dcc97db90c28)
![image](https://github.com/slowtorta/turtlewow-bug-tracker/assets/151180101/05a893f4-4680-43ce-9f7d-1359caed71e6)

Works fine with both sexes of goblin.
