### ISSUE TITLE
Master Looter Bug Molten Core

### ISSUE THREAD

**Issue by Tyrlia** [slowtorta/turtlewow-bug-tracker#6082]
**Please, provide a clear description what the bug is:**
Master Looter Bug, My character should have received the item

**Steps to reproduce the behavior with as much detail as possible:**

1. Kill Boss
2. Loot Boss
3. Master Looter (Hydroponixx) Sends Item to Player

**IDs of affected creatures, items, quests or spells with a link to the relevant page:**

NPC: https://database.turtle-wow.org/?npc=12264
Item: https://database.turtle-wow.org/?item=16811
Quest: 
Spell: 
Object: 

**Expected behavior. Describe how it should work:**
Yiel should have received the item

**Comment by Tyrlia** [comment]
I also have a recording of the run, I just need to contact Hydroponixx for it if needed!

**Comment by Tyrlia** [comment]
Raid ID 4499

**Comment by twowTurtReynolds** [comment]
These issues seem isolated to that day. Please contact us if further issues are seen. We will need solid replication steps if this does crop back up.
