### ISSUE TITLE
Hatehatehate forge

### ISSUE THREAD

**Issue by Wainerhard** [slowtorta/turtlewow-bug-tracker#6083]
![изображение_2024-01-24_111636009](https://github.com/slowtorta/turtlewow-bug-tracker/assets/155684105/e0da69ed-bd99-474f-a6ad-dfc92a7a936a)

Hello. I killed the specified boss in the raid group about 320+ times (you can check by the number of Fashion Coins received from this boss), but did not get the necessary loot. I think it's a bug. I knocked out all the items in this sub-dungeon with a 0.005% chance and several times. Also, loot from ordinary monsters is disgustingly configured in the dungeon. After so many attempts, I already know by heart the enemies who have nothing in their drop at all except silver! I don't even earn gold when I throw away my time, my life, like garbage.

Why the hell is the drop so disgustingly set up! Normally, this item should have fallen to me at least 4 times. But I didn't get any! Give me back! Give me back all, what i spend!

IDs of affected creatures, items, quests or spells with a link to the relevant page:

NPC: https://database.turtle-wow.org/?npc=60737
Har'gesh Doomcaller <Twilight's Hammer>

Item: https://database.turtle-wow.org/?item=60551
Pendant of the Faceless

Thx!

**Comment by ratkosrb** [comment]
I noticed the item was in a group by itself for some reason. Normally the combined drop chance of items in a group should add up to 100%. If the item was unable to drop, it could be because of this. I've unassigned the pointless group id from it. The issue should be resolved after the next update.

**Comment by Wainerhard** [comment]
clear..  I so want leave this place and never come back..

**Comment by twowTurtReynolds** [comment]
@ratkosrb the item is able to drop, many people on the server have it. This user was unlucky. 

The only potential loot table setup where an item cannot drop is when it is on a table above 100%, like this item: https://github.com/slowtorta/turtlewow-bug-tracker/issues/5429

I just want to make sure that when you have moved the item to group 1 or 2 that you have reduced the other items' drop chance so that the group doesn't exceed 100%.

**Comment by ratkosrb** [comment]
I didn't move it to group 1 or 2. I ungrouped it. There is no reason to have single item groups, it just makes no sense.

**Comment by twowTurtReynolds** [comment]
Oh okay, perfect!
