### ISSUE TITLE
Items disappeared on Hakkar (master loot bug?)

### ISSUE THREAD

**Issue by jimbo1111** [slowtorta/turtlewow-bug-tracker#6084]
**Please, provide a clear description what the bug is:**

Items dropped on Hakkar, then disappeared when ML tried to distribute them. Cloak of consumption was properly distributed, but warblade of the hakkari and heart of hakkar were not. Then they disappeared for master looter, nobody got them.

Happened earlier tonight in MC as well - I didn't lose any loot there, but others did.

**Steps to reproduce the behavior with as much detail as possible:**

1. It seems to be random. Looting bosses and the loot can sometimes just disappear. We couldn't find a pattern

**IDs of affected creatures, items, quests or spells with a link to the relevant page:**

https://database.turtle-wow.org/?item=19802
https://database.turtle-wow.org/?npc=14834
https://database.turtle-wow.org/?item=19865

**Expected behavior. Describe how it should work:**

Loot should drop and be distributed normally through ML without disappearing

![Screenshot 2024-01-24 at 12 35 15 AM](https://github.com/slowtorta/turtlewow-bug-tracker/assets/16787629/9a181b0a-33e1-4716-9281-82eb70ec84b3)

**Comment by jimbo1111** [comment]
I'm Fangodruid who won the heart, Suprana won the warblade

**Comment by jimbo1111** [comment]
Raid ID 5975

**Comment by jimbo1111** [comment]
Also happened in MC with same raid leader earlier in the night: https://github.com/slowtorta/turtlewow-bug-tracker/issues/6082

Was sporadic in both cases - only happened on hakkar in ZG, happened on a few items in various places in MC.

**Comment by twowTurtReynolds** [comment]
https://github.com/slowtorta/turtlewow-bug-tracker/issues/6082
