### ISSUE TITLE
Quest broken

### ISSUE THREAD

**Issue by Dzhulron** [slowtorta/turtlewow-bug-tracker#6086]
Quest broken. I took the quest in a group. My partner completed the quest. The quest giver did not accept my quest. I deleted the quest. Now I can't complete or take the quest
1. I took the quest https://database.turtle-wow.org/?quest=40476
2. My partner completed the quest and completed the quest
3. After not completing the quest, I removed it from the quest list.
https://database.turtle-wow.org/?npc=60858
https://database.turtle-wow.org/?quest=40476

**Comment by Dormilon** [comment]
The quest can be accepted again after the quest event is completed. The quest giver will be interactive.
