### ISSUE TITLE
Incorrect recipe taught from [Recipe: Lean Venison] item

### ISSUE THREAD

**Issue by themunsey** [slowtorta/turtlewow-bug-tracker#6089]
**Please, provide a clear description what the bug is:**
The item [Recipe: Lean Venison] incorrectly teaches Mystery Stew instead of the intended recipe.
**Steps to reproduce the behavior with as much detail as possible:**

1. Log in to a character that does not already know the recipe for Lean Venison
2. Purchase the recipe for Lean Venison(I am unaware if the Ashenvale recipe also does this, but the one purchased from Vendor-tron 1000 in Desolace does)
3. Use the recipe item. It should incorrectly teach Mystery Stew.

**IDs of affected creatures, items, quests or spells with a link to the relevant page:**

Item: https://database.turtle-wow.org/?item=5489

**Expected behavior. Describe how it should work:**
The recipe should teach the Lean Venison cooking recipe.

**Comment by twowTurtReynolds** [comment]
I have no idea how that happened to you. Here's me using the gm .additem 5489
![image](https://github.com/slowtorta/turtlewow-bug-tracker/assets/151180101/710b7821-3ce2-44b0-aaf9-108438da5252)

And when I went to buy and learn the vendortron version:
![image](https://github.com/slowtorta/turtlewow-bug-tracker/assets/151180101/09688752-b5ce-4a26-b48f-76d7212e9917)

Please try on a fresh client and try again. If the issue persists then, please contact a GM to get spell 6419 learned to you.
