### ISSUE TITLE
can't turn in Quest Elunes Blessing

### ISSUE THREAD

**Issue by Pezeweng** [slowtorta/turtlewow-bug-tracker#6091]
We killed the Questmob Omen to get Elunes Blessing what is required to turn in the quest.
After doing this the whole Raid couldnt turn in the quest. GM ticket says i have to report it here as a bug. 
we're doing this quest on 24.01.23 at 11:15 pm. Plz help my character is Pezeweng and my friend Heator also did the quest.
Don't know what to to maybe you can get the quest manually done for us. 

greetings Alex

**Comment by Pezeweng** [comment]
ofc some other playeds in raid have done it too

**Comment by Yazeeraa** [comment]
I was part of the raid aswell. 
Character name: Yazara

**Comment by SabineWren** [comment]
We killed the boss a few minutes ago (different raid group than above). It gives a world buff, but no quest credit. No one in the raid can turn the quest in.

**Comment by twowTurtReynolds** [comment]
https://database.turtle-wow.org/?quest=8868

**Comment by ratkosrb** [comment]
I found the issue with the quest credit and it should be fixed after the next update.
