### ISSUE TITLE
Master Loot, Item Vanishes after Looting

### ISSUE THREAD

**Issue by OonaFae** [slowtorta/turtlewow-bug-tracker#6092]
**Please, provide a clear description what the bug is:**
Master Looter (Shadowlily) attempted to loot an item (Scaled Sand Reaver Leggings) to player (Garthul) however the items was never given to the player but it vanished from the boss.
AQ40 Raid ID where the incident occured is 17845
This has been reported in 2 other issues: 
https://github.com/slowtorta/turtlewow-bug-tracker/issues/6084
https://github.com/slowtorta/turtlewow-bug-tracker/issues/6082

**Steps to reproduce the behavior with as much detail as possible:**
Unsure how to reproduce it but it seems to behave as such
1. Item is looted to a player by the Master Looter
2. The Item does not broadcast that the item was looted to a player, but it is removed from the Boss
3. The player does not receive the item, no players in the raid receive the item.

**Expected behavior. Describe how it should work:**
The item should be looted to the player, this issue seems to pop up sporadically based on what I've seen.

**Comment by twowTurtReynolds** [comment]
https://github.com/slowtorta/turtlewow-bug-tracker/issues/6082
