### ISSUE TITLE
Elunes Blessing Quest broken

### ISSUE THREAD

**Issue by Squirreled** [slowtorta/turtlewow-bug-tracker#6093]
The quest text says "receive Elune's Blessing"

Elunes blessing is a buff gained by standing in the light spawned by killing omen.
This gives a 60 min buff.

However even with the buff active the quests does not count as completed and is therefore impossible to turn in.

**Comment by twowTurtReynolds** [comment]
Duplicate of https://github.com/slowtorta/turtlewow-bug-tracker/issues/6091
