### ISSUE TITLE
[twow spring festival quest 'Elune Blessing' bug]

### ISSUE THREAD

**Issue by leesnowmountain** [slowtorta/turtlewow-bug-tracker#6094]
**Please, provide a clear description what the bug is:**

**Steps to reproduce the behavior with as much detail as possible:**

1. a raid team normal killed Omen , all mate get a 'Elune Blessing' buff ;
2. then raid team mate go to quest NPC 'Valadar Starsong' ;
3. team mate can accept quest, but cant finish quest 'Elune Blessing' , click 'Complete Quest' button no response.

**IDs of affected creatures, items, quests or spells with a link to the relevant page:**

NPC: https://database.turtle-wow.org/?npc=Valadar Starsong
Item: https://database.turtle-wow.org/?item=(none item)
Quest: https://database.turtle-wow.org/?quest=Elune's Blessing
Spell: https://database.turtle-wow.org/?spell=Elune's Blessing
Object: https://database.turtle-wow.org/?object=Omen

![001](https://github.com/slowtorta/turtlewow-bug-tracker/assets/36796165/8d31879c-9c35-48ae-bfa1-4f814f4ae71b)

**Expected behavior. Describe how it should work:**

**Comment by ratkosrb** [comment]
You must accept the quest BEFORE you kill the boss in order for it to count...

**Comment by leesnowmountain** [comment]
cant , i try 1 more time, cant complete quest yet.

![002](https://github.com/slowtorta/turtlewow-bug-tracker/assets/36796165/189b5a78-93a2-4057-92de-7c960f10020d)

**Comment by ratkosrb** [comment]
I discovered the spell was missing the script to complete the quest. You must wait for the server to be updated.

**Comment by leesnowmountain** [comment]
ty, quest done. :D
