### ISSUE TITLE
Emerald Dream Asia server cannot enter naxx

### ISSUE THREAD

**Issue by 4343421jc** [slowtorta/turtlewow-bug-tracker#6095]
**Please, provide a clear description what the bug is:
I am a player in the Emerald Dream of the Turtle server and the Asian server. My game ID is 4343421jc. My game ID is Tianzhi Dumpling Morning. I am level 60 and have completed the mission of Naxxramas. I have also accepted the Echoes of War mission, but currently Still can't enter the dungeon, please help me solve it.

![1111](https://github.com/slowtorta/turtlewow-bug-tracker/assets/147687437/c2ef2de7-e0ff-46df-85df-89e2d53669f9)
![2222](https://github.com/slowtorta/turtlewow-bug-tracker/assets/147687437/cc6ffd8e-b0f7-471d-a31f-7314c7e1583c)

My email is 33429542@qq.com looking forward to your reply
**Steps to reproduce the behavior with as much detail as possible:**

1.
2. 
3. 

**IDs of affected creatures, items, quests or spells with a link to the relevant page:**

NPC: https://database.turtle-wow.org/?npc=
Item: https://database.turtle-wow.org/?item=
Quest: https://database.turtle-wow.org/?quest=
Spell: https://database.turtle-wow.org/?spell=
Object: https://database.turtle-wow.org/?object=

**Expected behavior. Describe how it should work:**

**Comment by twowTurtReynolds** [comment]
Please contact support to verify the status of your attunement. I cannot replicate this issue.
