### ISSUE TITLE
Lunar Festival ancestor in The Sepulcher invisible due to phasing

### ISSUE THREAD

**Issue by RUTHINAS** [slowtorta/turtlewow-bug-tracker#6098]
**Please, provide a clear description what the bug is:**
I flew to The Sepulcher from Undercity, and for a brief moment before landing I could see the dwarf ancestor standing in a moonbeam and then fading from sight as I touched down.

**IDs of affected creatures, items, quests or spells with a link to the relevant page:**

NPC: https://database.turtle-wow.org/?npc=

I did not have time to target the ancestor, so I am not aware of their name and, by extension, ID.

**Expected behavior. Describe how it should work:**
Phasing should not hide mobs deep within the zone they're in. Perhaps some mobs should be flagged to never phase (if possible).

**Comment by twowTurtReynolds** [comment]
Turtle wow does not use phasing. The closest thing to that is: https://github.com/slowtorta/turtlewow-bug-tracker/issues?q=is%3Aopen+is%3Aissue+label%3A%22Continents+Instanciate%22

And this does not seem to be an issue of that, I cannot reproduce:
![image](https://github.com/slowtorta/turtlewow-bug-tracker/assets/151180101/aefb66ca-8da2-45c7-80ea-5bbf4ac147a6)
