### ISSUE TITLE
Lapidis Isle: Incorrect Quest Text for the The Boran Family 

### ISSUE THREAD

**Issue by Valamartle** [slowtorta/turtlewow-bug-tracker#610]
**Please, provide a clear description what the bug is:**
The Quest Text for The Boran family seems to be from an entirely different quest referring to a distillery of rum somewhere else and not as the NPC and quest name would imply a sailor wanting to get in touch with family back on the mainland. 
**Steps to reproduce the behavior with as much detail as possible:**

1.Talk to Arnold Boran at Caelan's Rest, the text speaks of finding a rum recipe but the objectives are to deliver letters

**Comment by ulricc66** [comment]
Can confirm this is still an issue, got no clue on how to complete this quest without the background story

**Comment by slowtorta** [comment]
Clear WDB, it's been fixed today.

**Comment by Valamartle** [comment]
It's working correctly now! Thank you!

**Comment by ulricc66** [comment]
worked after clearing WDB-folder, nice work devs :)

**Comment by Tinyfin-github** [comment]
![image](https://user-images.githubusercontent.com/83077166/153068837-1406cd80-a10e-4f50-aee7-772c16c907b7.png)

The quest broke again.
