### ISSUE TITLE
Shaman Healing Wave is not healing self reliably

### ISSUE THREAD

**Issue by Greywoolf6** [slowtorta/turtlewow-bug-tracker#6102]
**Please, provide a clear description what the bug is:**

Shaman Healing Wave is not reliably healing self, mana is spent and only heals about 1 in 5 times.  Auto Self Cast is checked

**Steps to reproduce the behavior with as much detail as possible:**

1. Self in or out of combat
2. Self selected or not selected
3. Auto Self Cast is checked

**IDs of affected creatures, items, quests or spells with a link to the relevant page:**

Spell: https://database.turtle-wow.org/?spell=331

**Expected behavior. Describe how it should work:**
Should heal Self

**Comment by OonaFae** [comment]
Do you have any other info on this so I can test more effectively? 

Does this happen on a specific rank or all ranks? 
What talents are you running? 
Have you tried it with all addons turned off?

I've tried with rank 5 and rank 10 and have not seen any issues.
Any video might help as well.

**Comment by Greywoolf6** [comment]
upon further use and trouble shooting I figured out that it does not work with a client that Vanilla Tweaks were applied.  Reverted back to Turtle Wow download client and all is well
