### ISSUE TITLE
salt shaker cooldown bugged

### ISSUE THREAD

**Issue by ghost** [slowtorta/turtlewow-bug-tracker#6103]
**Please, provide a clear description what the bug is:**

My salt shaker suddenly has a cooldown of 51 days (52 yesterday) on one character. The rest of my characters have 2 days remaining on my salt shaker but its been 3 days already.  It happended after i changed my name.

Unable to reproduce the bug.
https://database.turtle-wow.org/?item=15846

Cooldown of the item should only be 3 days.
**Steps to reproduce the behavior with as much detail as possible:**

1.
2. 
3. 

**IDs of affected creatures, items, quests or spells with a link to the relevant page:**

NPC: https://database.turtle-wow.org/?npc=
Item: https://database.turtle-wow.org/?item=
Quest: https://database.turtle-wow.org/?quest=
Spell: https://database.turtle-wow.org/?spell=
Object: https://database.turtle-wow.org/?object=

**Expected behavior. Describe how it should work:**

**Comment by saltshakercooldowns** [comment]
i changed name on a completely diff character. and one of my characters had the cooldown 52 days bug and the rest are stuck at 2.

**Comment by twowTurtReynolds** [comment]
A lot of these bugs are just visual and the server will let you use the skill even if the client thinks a wrong value.

Can you wait until the cooldown would have been up, and then let us know if it prevents the use then?

**Comment by saltshakercooldowns** [comment]
Ok thank you

**Comment by GrizB37** [comment]
Visual bug only, mostly caused by addon.

**Comment by twowTurtReynolds** [comment]
Indeed, since we have not heard back that was likely the case.
