### ISSUE TITLE
Whip lashers hit harder after server restart

### ISSUE THREAD

**Issue by taveonnarra** [slowtorta/turtlewow-bug-tracker#6105]
**Please, provide a clear description what the bug is:**
Lashers are hitting harder after restart; it seems they're using lash of pain much more often now.

**Steps to reproduce the behavior with as much detail as possible:**

1. Let them hit you at the back 
2. Or do a normal lasher farm pulling 2-3 mobs
3. 

**IDs of affected creatures, items, quests or spells with a link to the relevant page:**

NPC: https://database.turtle-wow.org/?npc= https://database.turtle-wow.org/?npc=13022
Item: https://database.turtle-wow.org/?item=
Quest: https://database.turtle-wow.org/?quest=
Spell: https://database.turtle-wow.org/?spell=https://database.turtle-wow.org/?spell=21987
Object: https://database.turtle-wow.org/?object=

**Expected behavior. Describe how it should work:**

**Comment by FreezeNaga** [comment]
Yep, I can feel this damage increase too. I am consistently dying on the same pull (3 lasher packs into an iceblock, when iceblock finishes I die before I can get distance) over and over when I normally would never die (I've done 1000+ lasher pulls on this server so I am very familiar with it).

**Comment by FreezeNaga** [comment]
This appears to be fixed now.
