### ISSUE TITLE
Lunar Festival Event quest can not be started

### ISSUE THREAD

**Issue by StasyaLyova** [slowtorta/turtlewow-bug-tracker#6109]
**Please, provide a clear description what the bug is:**
Lunar Festival Emissary not have dialogue for start event quest. So players that did it last year cant get Coins of Ancestry (from Lunar Festival Elders) for exchange them in Moonglade.

**Steps to reproduce the behavior with as much detail as possible:**

1. Do quest last year, complete it
2. Clean wdb folder (or not), try to talk with emissary in main city
3. No quest - no coins from npc from all world

**IDs of affected creatures, items, quests or spells with a link to the relevant page:**

NPC: 
https://database.turtle-wow.org/?npc=15892

Quest: https://database.turtle-wow.org/?quest=
https://database.turtle-wow.org/?quest=8870

**Expected behavior. Describe how it should work:**
emissary gives quest every year :)

**Comment by StasyaLyova** [comment]
![Screenshot_20240126-211230-004-01](https://github.com/slowtorta/turtlewow-bug-tracker/assets/153867747/b7e32d1f-be07-4478-a889-15cd157b799f)

**Comment by ratkosrb** [comment]
This should be fixed after the next update. I added a system to reset marked quests if completed in the previous year.
