### ISSUE TITLE
new flight route astranar to rachet

### ISSUE THREAD

**Issue by geojak** [slowtorta/turtlewow-bug-tracker#611]
**Please, provide a clear description what the bug is:**

when i clicked to start flying from astranar ashenvale to rachet i noticed the new direct lfight connection.
when i clicked the game froce for 20 seconds, then i just appeard in rachet. 

someone in world chat said same is happening from gatzgetan to rachet

**Steps to reproduce the behavior with as much detail as possible:**

1. fly from astranar
2. to rachet

**IDs of affected creatures, items, quests or spells with a link to the relevant page:**

NPC: https://database.turtle-wow.org/?npc=
Item: https://database.turtle-wow.org/?item=
Quest: https://database.turtle-wow.org/?quest=
Spell: https://database.turtle-wow.org/?spell=
Object: https://database.turtle-wow.org/?object=

**Expected behavior. Describe how it should work:**

normal flight behaviour

**Comment by Tinyfin-github** [comment]
Greetings!

Flight path will be temporarily disabled until the issue is fixed.
