### ISSUE TITLE
Gouge used by Blackhand Assassins in Upper Blackrock Spire has an extremely long range

### ISSUE THREAD

**Issue by patrycos** [slowtorta/turtlewow-bug-tracker#6116]
**Please, provide a clear description what the bug is:**
Blackhand Assassins in Upper Blackrock Spire use a Gouge skill, which disables the target for a few seconds. While according to the Turtle database it has a 5 yard range, I have been hit by it (many times, in many separate runs) while kiting the Assassin and being 40-50 yards away from it.

**Steps to reproduce the behavior with as much detail as possible:**
1. Aggro a Blackhand Assassin
2. Be at max range and kite the NPC for a few seconds
3. Blackhand Assassin will Gouge you at any range despite it supposedly being a 5 yard range skill

**IDs of affected creatures, items, quests or spells with a link to the relevant page:**
Blackhand Assassin: [https://database.turtle-wow.org/?npc=10318](https://database.turtle-wow.org/?npc=10318)
Gouge: [https://database.turtle-wow.org/?spell=12540](https://database.turtle-wow.org/?spell=12540)

**Expected behavior. Describe how it should work:**
Blackhand Assassin's Gouge should have a 5 yard range.

**Comment by Kangaroux** [comment]
Same ticket #3719
