### ISSUE TITLE
Purge not working on Magic Effects

### ISSUE THREAD

**Issue by discer** [slowtorta/turtlewow-bug-tracker#6118]
**Please, provide a clear description what the bug is:**
Swiftness potion and Living action potion both create a magic buff on the player but neither can be dispelled by shaman purge

**Steps to reproduce the behavior with as much detail as possible:**

1. have player pop swiftness pot
2.  attempt to purge player
3. see nothing is dispelled

**IDs of affected creatures, items, quests or spells with a link to the relevant page:**

Item: 
https://database.turtle-wow.org/?item=2459
https://database.turtle-wow.org/?item=20008
Spell: https://database.turtle-wow.org/?spell=27626

**Expected behavior. Describe how it should work:**
Purge dispels 2 magic effects

**Comment by twowTurtReynolds** [comment]
![image](https://github.com/slowtorta/turtlewow-bug-tracker/assets/151180101/917ef7de-7e5f-40e5-9196-dd7371b1949c)
