### ISSUE TITLE
乌龟服 Blood Ring 角色：丫丫的双马尾，邮箱错误问题

### ISSUE THREAD

**Issue by YY2005501** [slowtorta/turtlewow-bug-tracker#6120]
**Please, provide a clear description what the bug is:**
乌龟服
服务器： Blood Ring
角色：丫丫的双马尾
邮箱错误问题，提示该角色邮箱已经达到上限，但是该角色不能收到邮件
**Steps to reproduce the behavior with as much detail as possible:**

1. 其他角色给该角色邮寄的东西没有收到
2. 该角色没有收到邮件，没有未读或者已读邮件
3. 提示该角色邮箱已经达到上限
**IDs of affected creatures, items, quests or spells with a link to the relevant page:**

NPC: https://database.turtle-wow.org/?npc=
Item: https://database.turtle-wow.org/?item=
Quest: https://database.turtle-wow.org/?quest=
Spell: https://database.turtle-wow.org/?spell=
Object: https://database.turtle-wow.org/?object=

**Expected behavior. Describe how it should work:**

**Comment by Muigin** [comment]
Reports need to be made in English.
