### ISSUE TITLE
龙鳞制皮无法忘却

### ISSUE THREAD

**Issue by issacgit** [slowtorta/turtlewow-bug-tracker#6121]
**Please, provide a clear description what the bug is:**

**Steps to reproduce the behavior with as much detail as possible:**

1. 学习了龙鳞制皮。
2. 到训练师处忘却制皮，想重新学习部族制皮。
3. 重新学习制皮，发现龙鳞制皮仍然存在 

**IDs of affected creatures, items, quests or spells with a link to the relevant page:**

Endless Sea
盆栽西瓜

NPC: https://database.turtle-wow.org/?npc=
Item: https://database.turtle-wow.org/?item=
Quest: https://database.turtle-wow.org/?quest=
Spell: https://database.turtle-wow.org/?spell=
Object: https://database.turtle-wow.org/?object=

**Expected behavior. Describe how it should work:**

**Comment by Muigin** [comment]
Reports need to be made in English.
