### ISSUE TITLE
Plans: Rune-Etched Crown can't be learned

### ISSUE THREAD

**Issue by blundyth** [slowtorta/turtlewow-bug-tracker#6122]
Plans: Rune-Etched Crown(https://database.turtle-wow.org/?item=83504) can't be learned;
When right-click, display "No available times"

This issue occurs on Ravenshire, Asia area

**Comment by twowTurtReynolds** [comment]
![image](https://github.com/slowtorta/turtlewow-bug-tracker/assets/151180101/ce3b4689-b1ec-41dc-a08c-662557dc5808)
Works fine.
