### ISSUE TITLE
Cleaning Cloth doesn't appear in the survival panel after learning the recipe

### ISSUE THREAD

**Issue by Lichbanez** [slowtorta/turtlewow-bug-tracker#6125]
The recipe was recently re-added but when you learn it the item doesn't appear in the crafting menu

1. Buy the recipe
2. Learn the recipe
3. Open the survival menu

NPC: https://database.turtle-wow.org/?npc=50070
Item: https://database.turtle-wow.org/?item=60002

It should appear in the list just like the tent or the fishing boat.

**Comment by Avery1337** [comment]
It only appears for rogues under Survival.

**Comment by slowtorta** [comment]
Fixed in the internal build, the change will be reflected in game in the patch 1.17.2.

**Comment by Lichbanez** [comment]
I read that you're planning on reworking Survival, will we maintain the skill points? Because if so I'll just stop leveling it now and save some time and money.
