### ISSUE TITLE
"Crazy Cat Lady" title issue

### ISSUE THREAD

**Issue by Mystar711** [slowtorta/turtlewow-bug-tracker#6130]
**Please, provide a clear description what the bug is:**

**Steps to reproduce the behavior with as much detail as possible:**

1. I collected all the kitties based on the list of the "Crazy Cat Lady" title
2. I bought the black tabby in AH, but I failed to use it and it cannot occur in my pets list.
3. I cannot get the title of "Crazy Cat Lady"  sequentially.

**IDs of affected creatures, items, quests or spells with a link to the relevant page:**
https://database.turtle-wow.org/?item=8491

**Expected behavior. Describe how it should work:**

The black tabby could be added into my pet list and then get the title "Crazy Cat Lady"

**Comment by Avery1337** [comment]
Black Tabby goes into your pet log as Maine Coon.  If you have this pet you will know based on when you pull the Maine Coon out of your pet log it will read Black Tabby ontop of its NPC frame.  https://forum.turtle-wow.org/viewtopic.php?t=8172 This forum post will assist you on how to get all pets if you think you are missing one.  If you don't have Maine Coon and still are having issues getting Black Tabby then this might be a valid bug.
