### ISSUE TITLE
Mass Semi-AFK farm of Bright Dream Shards is getting out of hand.

### ISSUE THREAD

**Issue by itdelta-prog** [slowtorta/turtlewow-bug-tracker#6132]
Repeatable quest 'Corrupted Dream Shards' in Hyjal rewards a Bright Dream Shard for  delivered 5 quest items 'Corrupt Dream Shard'.
'Corrupt Dream Shard' drop is shared for entire group/raid - everyone gets a copy of quest item and hence it is very easy to farm money with a group. The larger the group - the more money your group's total gain is.. A raid of 20 people keep the Vilemusk Satyr spawn cleared for a hour and everyone gets about 30 Bright Dream Shards each. This allows highly organized guilds from Far Asia to farm A LOT of Dreamshards without all raid members being involved directly (siting or chatting, just looting the items once in a while).

Farming Corrupted Dream Shards with a raid became a norm and scheduled daily activity, with half of the people being semi-afk, just looting the corpses once in a minute.

Steps to reproduce the behavior with as much detail as possible:
Take repeatable quest 'Corrupted Dream Shards' and Farm satyrs in Hyjal solo - quest items drop normally.
Take repeatable quest 'Corrupted Dream Shards' and Farm satyrs in Hyjal in group - everyone in group gets a copy of quest item each time it drops.
Take repeatable quest 'Corrupted Dream Shards' and Farm satyrs in Hyjal in raid - everyone in raid gets a copy of quest item each time it drops.

IDs of affected creatures, items, quests or spells with a link to the relevant page:

NPCs being raid farmed: 
https://database.turtle-wow.org/?npc=61339
https://database.turtle-wow.org/?npc=61340
https://database.turtle-wow.org/?npc=61341

Quest Item dropping for the entire raid:
 https://database.turtle-wow.org/?item=61706 - Corrupt Dream Shard.

Reward received repeatedly:
https://database.turtle-wow.org/?item=61199 

Quest involved:  
https://database.turtle-wow.org/?quest=41018

Expected behavior. Describe how it should work:

Take repeatable quest 'Corrupted Dream Shards' and Farm satyrs in Hyjal in a Group - everyone in group gets a copy of quest item each time it drops.

Take repeatable quest 'Corrupted Dream Shards' and Farm satyrs in Hyjal in a Raid - quest items will not drop.

**Comment by twowTurtReynolds** [comment]
The bug tracker is not a place for suggestions.
