### ISSUE TITLE
Chromie's Broken Pocket Watch is giving +10 haste% instead of -10% haste (part2)

### ISSUE THREAD

**Issue by uhbvv** [slowtorta/turtlewow-bug-tracker#6138]
**Please, provide a clear description what the bug is:**
This item (Chromie's Broken Pocket Watch (https://database.turtle-wow.org/?item=61564)) has a description that says that the effect increases speed by 10%. But according to the facts, we increase the casting time of the spell by +10%.
For example, fireball: base speed 3 sec, with effect 3.3 sec.
The effect in the description is given by hast spell ((6) Apply Aura #65: Haste - Spells) https://database.turtle-wow.org/?spell=45860
![base speed](https://github.com/slowtorta/turtlewow-bug-tracker/assets/17100728/215fa902-3635-46a3-8b9f-4ad67036a850)
![Borrowed Time](https://github.com/slowtorta/turtlewow-bug-tracker/assets/17100728/9e0331b9-a8b4-4c60-8ba7-ff03b003af63)

**Steps to reproduce the behavior with as much detail as possible:**

1. Have Chromie's Broken Pocket Watch equipped.
2. Cast direct dmg spells at a target until it procs.
3. Proc reduces cast "time" instead of reducing "speed"

**IDs of affected creatures, items, quests or spells with a link to the relevant page:**
(Chromie's Broken Pocket Watch (https://database.turtle-wow.org/?item=61564))

**Expected behavior. Describe how it should work:**
Here is an example of other items with the same effect, which, when triggered, receive a reduction in the casting time of the spell.

https://database.turtle-wow.org/?item=19339 (Haste - Spells (https://database.turtle-wow.org/?spell=23723))
https://database.turtle-wow.org/?item=9449 (Haste - Melee (https://database.turtle-wow.org/?spell=13494))
https://database.turtle-wow.org/?item=60501 (Haste - Melee, Haste - Ranged, Haste - Spells (https://database.turtle-wow.org/?spell=13680)

**Comment by schanzee** [comment]
The item was initially broken but is now working as intended.
Original description was misleading (honestly plain wrong) and was changed since.
Database is out of date in this case.
Check the actual tooltip ingame (if it's the same as the database clear your cache/delete yourWDB folder.

"Borrowed Time now increases cast time instead of reducing it. The spell text update is only available after a client patch."
https://forum.turtle-wow.org/viewtopic.php?p=76474&hilit=pocket+watch#p76474

**Comment by Dragunovi** [comment]
Working as intended. Database might not be updated with the current description but it should be clear that it reduces your casting speed in-game.
