### ISSUE TITLE
Flight Path from Ratchet to Gadgetzan (Alliance) will teleport you directly. 

### ISSUE THREAD

**Issue by sonpansatan** [slowtorta/turtlewow-bug-tracker#614]
**Please, provide a clear description what the bug is:**
Flight Path from Ratchet to Gadgetzan will teleport you directly instead of flying there.
**Steps to reproduce the behavior with as much detail as possible:**

1. Talk to flight master in Ratchet and request a flight to Gadgetzan (Alliance flight master).
2. Talk to Alliance flight master in Gadgetzan and request flight to Ratchet.

**IDs of affected creatures, items, quests or spells with a link to the relevant page:**

NPC:
https://classic.wowhead.com/npc=16227/bragok
https://classic.wowhead.com/npc=7823/bera-stonehammer

It should stick you on a flying mount and take the flight part.  However, now it directly teleports you.

**Comment by Tinyfin-github** [comment]
Greetings! 

This flight path has been temporarily disabled until the issue is fixed.
