### ISSUE TITLE
Floating Thalassian Daisy in HE starting area

### ISSUE THREAD

**Issue by IcemanHHW** [slowtorta/turtlewow-bug-tracker#6142]
**Please, provide a clear description what the bug is:**

There's a floating Thalassian Daisy in the Thalassian Highlands near Brinthilien around the coordinates 50.2 / 75.1

![afbeelding](https://github.com/slowtorta/turtlewow-bug-tracker/assets/20383130/6774c1bd-537d-42ca-932e-ec4b9819ae77)

![afbeelding](https://github.com/slowtorta/turtlewow-bug-tracker/assets/20383130/2e57f137-a23d-4f6e-bfec-74b9f47b712a)

**Steps to reproduce the behavior with as much detail as possible:**

1. Go to the Thalassian Highlands around 50.2 / 75.1
2. See the Thalassian Daisy floating in the air
3. 

**IDs of affected creatures, items, quests or spells with a link to the relevant page:**

NPC: https://database.turtle-wow.org/?npc=
Item: https://database.turtle-wow.org/?item=
Quest: https://database.turtle-wow.org/?quest=
Spell: https://database.turtle-wow.org/?spell=
Object: https://database.turtle-wow.org/?object=2020072

**Expected behavior. Describe how it should work:**

The Thalassian Daisy be placed on the ground or removed

**Comment by ratkosrb** [comment]
Should be fixed after the next update.
