### ISSUE TITLE
Consecrated Caduceus from Wardens of Time reputation fires shadow bolts despite dealing holy damage

### ISSUE THREAD

**Issue by RUTHINAS** [slowtorta/turtlewow-bug-tracker#6143]
**Please, provide a clear description what the bug is:**
The Consecrated Caduceus deals holy damage, but the bolts it fires are similar to what a shadow wand would fire.

**IDs of affected creatures, items, quests or spells with a link to the relevant page:**

Item: https://database.turtle-wow.org/?item=84602

**Expected behavior. Describe how it should work:**
It should fire the same holy bolts as Wand of Eternal Light (https://database.turtle-wow.org/?item=22254).

**Comment by ratkosrb** [comment]
The missile visual seems to be tied to the display id of the item.

**Comment by ratkosrb** [comment]
I'll replace the item's display id with that of Wand of Eternal Light so that it can shoot the same missile.

**Comment by RUTHINAS** [comment]
I'm not familiar with how the display ID system works. Would the change also alter the model and/or icon of the Caduceus to correspond to the Wand of Eternal Light? The star-tipped wand doesn't really fit the description of a caduceus.

**Comment by ratkosrb** [comment]
Yes it will. If you want to suggest another item's display id to use instead go ahead. Or I could change the item to do shadow damage, so it fits the current display id.

**Comment by RUTHINAS** [comment]
As far as I am aware, the Wand of Eternal Light is the only vanilla WoW wand that deals holy damage. On Turtle there is additionally one that drops from Scarlet Monastery mobs, but I do not know whether it fires holy bolts or not. If changing the display ID is the only way to adjust the bolt effect, then there are not many options to choose from.

Is it possible to create a new display ID from scratch, and pick the model and bolt effect accordingly?

I do think the holy damage fits the flavor of a Consecrated wand, and is a better suited faction reward for the Wardens of Time than a shadow wand would be.

**Comment by ratkosrb** [comment]
A client developer would have to answer that. I work on server side things, and don't know how to go about changing the missile visual assigned to an item display id, as that is handled by the client.
