### ISSUE TITLE
Item missing after mailing - 22nd November 2023

### ISSUE THREAD

**Issue by darklord098** [slowtorta/turtlewow-bug-tracker#6144]
**Please, provide a clear description what the bug is:**
Hi team, I'm Sizzer from Stormstout - Asia region.
I want to report a mailing bug. 8*Arcane crystals (https://database.turtle-wow.org/?item=12363) are missing after mailing.

**Steps to reproduce the behavior with as much detail as possible:**

1. On 22nd Nov 2023, I mailed 8* arcane crystals from my alt character Ssizzer to my main character Sizzer at 19:10 local time (11:10 server time).
2. When I logged into Sizzer, I received mail from Ssizzer which only contained a subject but no attachment.
![130170737](https://github.com/slowtorta/turtlewow-bug-tracker/assets/157976082/d0830a28-941f-4353-a57f-1ccd19c21ae5)
3. Then I logged back to my alt character Ssizzer, all of 8* arcane crystals disappeared.
4. I tried logging in to these 2 characters several times, and still can't see those items.

**IDs of affected creatures, items, quests or spells with a link to the relevant page:**

NPC: https://database.turtle-wow.org/?npc=
Item: https://database.turtle-wow.org/?item=
Quest: https://database.turtle-wow.org/?quest=
Spell: https://database.turtle-wow.org/?spell=
Object: https://database.turtle-wow.org/?object=

**Expected behavior. Describe how it should work:**
Please investigate this matter and send the items back to me.
Thanks.

**Comment by twowTurtReynolds** [comment]
Please contact support for these inquiries, instead of creating bug reports.

**Comment by darklord098** [comment]
> Please contact support for these inquiries, instead of creating bug reports.

Hi, GM asked me to contact you guys for further help, that's why I submitted this ticket.
![image](https://github.com/slowtorta/turtlewow-bug-tracker/assets/157976082/72e8bfac-f976-4539-b9a7-22a9dfd04c03)
