### ISSUE TITLE
Lor'thas the Holy has no voice lines

### ISSUE THREAD

**Issue by IcemanHHW** [slowtorta/turtlewow-bug-tracker#6145]
**Please, provide a clear description what the bug is:**

Lor'thas the Holy, the Paladin trainer in Brinthilien has no voice lines. He stays completely silent when interacting with him.

**Steps to reproduce the behavior with as much detail as possible:**

1. Go to Lor'thas the Holy
2. Click on him to interact or to annoy him
3. He stays completely silent

**IDs of affected creatures, items, quests or spells with a link to the relevant page:**

NPC: https://database.turtle-wow.org/?npc=80220
Item: https://database.turtle-wow.org/?item=
Quest: https://database.turtle-wow.org/?quest=
Spell: https://database.turtle-wow.org/?spell=
Object: https://database.turtle-wow.org/?object=

**Expected behavior. Describe how it should work:**

Lor'thas the Holy should have voice lines like the other High Elf NPC's

**Comment by luskanek** [comment]
Voice lines have been added for Lor'thas and many other Thalassian Highlands NPCs. The changes will be applied in the next patch.
