### ISSUE TITLE
BIG BUG!! we just appied 3 weeks for this bug!!no any respond!!!

### ISSUE THREAD

**Issue by kevinwxl** [slowtorta/turtlewow-bug-tracker#6147]
**Please, provide a clear description what the bug is:**

**Steps to reproduce the behavior with as much detail as possible:**

1.Serve：chinese asia----ravenshire    guild:诸神夜
2. issue: We can't see the second page of our guild bank, nor can we use the items in it, including a full warehouse of potions.
3. we just appied 3 weeks for this problem to GM online.but no any respond for us !
my email 82462138@qq.com
ty for your helping!

**IDs of affected creatures, items, quests or spells with a link to the relevant page:**

NPC: https://database.turtle-wow.org/?npc=
Item: https://database.turtle-wow.org/?item=
Quest: https://database.turtle-wow.org/?quest=
Spell: https://database.turtle-wow.org/?spell=
Object: https://database.turtle-wow.org/?object=

**Expected behavior. Describe how it should work:**

**Comment by twowTurtReynolds** [comment]
Please contact support.
