### ISSUE TITLE
Theorized bug with natural weapons talent - druid

### ISSUE THREAD

**Issue by icedcreamgaming** [slowtorta/turtlewow-bug-tracker#6148]
Theorized bug with natural weapons talent - druid :::

I theorize that there is a bug affecting the + spell hit with druid ability Natural Weapons talent and if not, then possibly with one or more gear pieces listed below. I have run DPSmate for tracking and our guild runs an independent logging program that records everyone’s damage as well. Both recordings show the same miss rate on boss encounters from our AQ40 raid. I’ve also been reviewing logs from BWL from DPSmate of my own spells, warlocks, and mages.

Total 6% hit + 3% spell hit from talent Natural Weapons talent. Bosses are to have 17% miss which can be overcome up to 16% hit cap. I should be missing about 7-8%. In raids over all bosses, I am missing 10.3-11.8% between both Starfire and wrath on tests over 100s of hits. This is also reflective of some boss target dummy runs as well.

I since recorded another BWL run with an average of 10.8% miss on bosses. In this run I received Neltharion's tear (2% hit tricket) and I ran an Onyxia after. My now total is 8% hit + 3% spell hit from natural weapons talent = +11% hit. On Onyxia I missed 8.5% now (about 2% less miss now). This is still far off from the expected 5-6% hit.

**Steps to reproduce the behavior with as much detail as possible:**

1.Login to your test server on a balance druid with talents : https://talents.turtle-wow.org/druid/V0X08Z9V-0-U5D6
2. Put on this gear

- 5 pc Genesis (+3% hit)
- Choker of the fire lord
- Cloak of consumption (+1% hit)
- Bracers of accuracy (+1% hit)
- gloves of spell mastery
- Mana igniting cord
- dragonslayer’s signet
- Band of forced concentration (1% hit)
- Corrupt reed
- Eye of the beast
- Staff of shadowflame

4. Become immortal
5. Shoot BWL or AQ40 bosses - 100+ times with each starfire and wrath.
6. Review logs

**Expected behavior. Describe how it should work:**

I have reviewed logs of my guilds mages, and they see 0-0.7% miss in raid. They do have 6% + hit in talent and more hit gear, but they are +15% hit with talents and gear combined.  I reviewed logs with a destruction warlock in my guild and he has +9% hit and our logs showed him at 5.5% miss.

Conclusion: I think the most likely reason for my significantly elevated miss is Natural weapon talent may not be functioning for spell hit. 

** Further comments **

If a question is raised about spell resist and penetration, all bosses in AQ40 and BWL (except Chromaggus) according to your data based have 15 spell resist to nature and Arcane. Further I have 40 spell penetration in my set. It is rumored that the twow engine cannot overcome the last 15 resist and caps at 15 and not zero even with spell pen. I cannot confirm this. At 15 spell resistance (if it is not capable of being reduced to zero) I don’t believe it has even 1% chance of a full resist. I believe it technically can only 25%,50%, or 75% resist.

**Comment by twowTurtReynolds** [comment]
I sat infront of the boss dummy with full haste down to GCD, .aura 23727 x13 and 3/3 natural weapons. It took about 5 minutes of GCDs to see my first full resist, the unremovable 1%. Something else is causing it to not work for you and maybe just you. Let us know if you find the culprit.
