### ISSUE TITLE
魔兽世界乌龟服拉文郡服务器物品错误缺失

### ISSUE THREAD

**Issue by wg1008** [slowtorta/turtlewow-bug-tracker#6149]
**Please, provide a clear description what the bug is:**
魔兽世界乌龟服拉文郡服务器物品错误缺失
**Steps to reproduce the behavior with as much detail as possible:**

1.2024.1.30 23:50下线前物品和2024.1.31日17.35上线后物品相差很多
2. 主要物品缺失为3组（60个）奥金锭，4组（80个）奥术水晶，3组（60个)格罗姆之血.5组（100个）黑莲花
![1月30日截图](https://github.com/slowtorta/turtlewow-bug-tracker/assets/158287257/4c930977-f7d1-433e-b16d-fdf155ad33d8)
![1月31日截图](https://github.com/slowtorta/turtlewow-bug-tracker/assets/158287257/edef3306-17ca-4e0e-bec7-f8c8247977d6)

**IDs of affected creatures, items, quests or spells with a link to the relevant page:**

NPC: https://database.turtle-wow.org/?npc=
Item: https://database.turtle-wow.org/?item=
Quest: https://database.turtle-wow.org/?quest=
Spell: https://database.turtle-wow.org/?spell=
Object: https://database.turtle-wow.org/?object=

**Expected behavior. Describe how it should work:**

**Comment by wg1008** [comment]
还有5组山鼠草，黑莲花为4组缺失

**Comment by wg1008** [comment]
ID 二五九零一号

**Comment by Muigin** [comment]
Reports need to be made in English.
