### ISSUE TITLE
[Quest Drops] Oozes in Wetlands aren't dropping Slimey Ooze-Tar for the new quest, "Preparations for Adventure" in Hawk's Vigil

### ISSUE THREAD

**Issue by ShiraZen** [slowtorta/turtlewow-bug-tracker#615]
**Please, provide a clear description what the bug is:**
Title.
**Steps to reproduce the behavior with as much detail as possible:**

1.
2. 
3. 

**IDs of affected creatures, items, quests or spells with a link to the relevant page:**

NPC: https://database.turtle-wow.org/?npc=
Item: https://database.turtle-wow.org/?item=
Quest: https://database.turtle-wow.org/?quest=
Spell: https://database.turtle-wow.org/?spell=
Object: https://database.turtle-wow.org/?object=

**Expected behavior. Describe how it should work:**

**Comment by Steelborne** [comment]
Worked for me but low drop chance. The Monstrous and Crimson Oozes in the crypt have better drop rate it seems.
