### ISSUE TITLE
魔兽乌龟服拉文郡公会仓库问题

### ISSUE THREAD

**Issue by Menethiltt** [slowtorta/turtlewow-bug-tracker#6157]
乌龟服亚服拉文郡账号Menethiltt下面角色镜仓三角色所在公会《爱从零开始》公会仓库第四格1月26日才用公会仓库1500G购买的第四个仓库格子1月26日晚断线后看就没有了 包括存在里面的10组特效法力药水 也没有退回金币

1月27日 1点40分收到回复 这是BUG，物品显示错误。目前还没有修复 请问什么时候修复 很急
![微信图片_20240202041501](https://github.com/slowtorta/turtlewow-bug-tracker/assets/158516329/9b819556-a4d1-4d4c-b7be-f324b56e6d4d)

**Comment by Muigin** [comment]
Reports need to be made in English.

**Comment by Menethiltt** [comment]
World of Warcraft Turtle server, Raven County account, Menethiltt, under the character Mirror Warehouse, the third character belongs to the guild "Love from scratch". The fourth compartment of the guild warehouse was purchased only on January 26th using the guild warehouse 1500G. After the fourth compartment was disconnected on the evening of January 26th, it disappeared, including 10 sets of special effects mana potions that exist inside, and no gold coins were returned
On January 27th at 1:40, I received a reply stating that it was a bug and the item was displayed incorrectly. At present, it has not been fixed yet. May I know when the repair is urgent
