### ISSUE TITLE
Transmog issue about armor of the same type

### ISSUE THREAD

**Issue by zac32** [slowtorta/turtlewow-bug-tracker#616]
**Please, provide a clear description what the bug is:**
I can't transmog my Mystical Robe of the Eagle into my (High Elf) Apprentice's robe even though I own it. The Apprentice's Robe does not show up in the transmog menu when I wear the other robe. Both are chest cloth armor, I should be able to replace my current robe with the Apprentice's Robe.

**Steps to reproduce the behavior with as much detail as possible:**

1. Put on the Mystical Robe of the Eagle
2. Have the Apprentice's Robe (High Elf version) in the backpack
3. Go to Transmog to see if we can change the Mystical Robe with the Apprentice's Robe

**Expected behavior. Describe how it should work:**
I should be able to transmog my Mystical Robe of the Eagle into my Apprentice's Robe.

**Comment by CosminPOP** [comment]
![image](https://user-images.githubusercontent.com/7255825/148983455-6bb7ccbe-1b54-4f83-aa45-e20668bca35f.png)

cant reproduce, it worked for me

**Comment by zac32** [comment]
That's the human version of the robe. I'm talking the high elf one.

**Comment by slowtorta** [comment]
Sorry, but there's only one version of the item `Mystical Robe` and this one is working!

**Comment by zac32** [comment]
But I'm not talking about the Mystical Robe but the Apprentice High Elf Robe
