### ISSUE TITLE
风暴烈酒焚梦精华交了任务未获得翡翠祝福技能

### ISSUE THREAD

**Issue by z1112223** [slowtorta/turtlewow-bug-tracker#6160]
**Please, provide a clear description what the bug is:**
德鲁伊翡翠祝福任务“焚梦精华”，交完“阴燃梦境精华”后没有学到“翡翠祝福”技能。
**Steps to reproduce the behavior with as much detail as possible:**

1.Tyrlar暗夜精灵德鲁伊打完翡翠圣殿获得：阴燃翡翠精华，右键接到焚梦精华任务。
2. 到海加尔山交任务大德鲁伊处交了任务。
3. 未获得“翡翠祝福”技能。

**IDs of affected creatures, items, quests or spells with a link to the relevant page:**

NPC: https://database.turtle-wow.org/?npc=海加尔山三楼大德鲁伊
Item: https://database.turtle-wow.org/?item=翡翠祝福
Quest: https://database.turtle-wow.org/?quest=Tyrlar（风暴烈酒）
Spell: https://database.turtle-wow.org/?spell=焚梦精华
Object: https://database.turtle-wow.org/?object=阴燃梦境精华

**Expected behavior. Describe how it should work:**
返还任务物品以便重新交任务或者获得翡翠祝福技能

**Comment by Muigin** [comment]
Reports must be made in English.
