### ISSUE TITLE
Many mobs and bosses in Dire Maul West have been made poison immune, making the dungeon frustrating for rogue tanks

### ISSUE THREAD

**Issue by RUTHINAS** [slowtorta/turtlewow-bug-tracker#6163]
**Please, provide a clear description what the bug is:**
In the recent immunity update (or at some other recent point in time), many of the mobs and bosses in Dire Maul West have been updated to be immune to poison damage. While this might be flavorful and vanilla-accurate, it makes tanking the dungeon as a rogue extremely difficult, as the primary threat source of Agitating Poison is completely nullified.

While for a DPS rogue the lack of poison procs is simply a DPS reduction, for a tank rogue it severely cuts threat generation to the point of being unable to tank properly. I do not think it's particularly fun gameplay to have some instances one simply can not (comfortably) tank, regardless of gear level.

**Steps to reproduce the behavior with as much detail as possible:**

1. Enter Dire Maul West as a rogue, with poisons on weapons (Agitating Poison as tank)
2. Fight mobs and bosses
3. Observe the majority of them being immune to poisons. Treants, mana elementals, whirlwind elementals, to name a few mob types.

**Expected behavior. Describe how it should work:**
No mob should be made completely immune to a specific tank class. If you wish to retain the poison immunity for flavor reasons, Agitating Poison should perhaps be made to deal its bonus threat effect even on nature immune targets.

**Comment by twowTurtReynolds** [comment]
This is not a bug, please repost onto the suggestions forum.
