### ISSUE TITLE
邮寄出现错误，收件人收不到信件

### ISSUE THREAD

**Issue by ss198126** [slowtorta/turtlewow-bug-tracker#6165]
**Please, provide a clear description what the bug is:**

**Steps to reproduce the behavior with as much detail as possible:**

1.2月3日凌晨12点左右，给朋友（账号名字：八回合）邮寄的5个萨弗隆铁锭，49块奥金锭材料做武器，但是朋友一直没有收到
2. 
3. 

**IDs of affected creatures, items, quests or spells with a link to the relevant page:**

NPC: https://database.turtle-wow.org/?npc=
Item: https://database.turtle-wow.org/?item=
Quest: https://database.turtle-wow.org/?quest=
Spell: https://database.turtle-wow.org/?spell=
Object: https://database.turtle-wow.org/?object=

**Expected behavior. Describe how it should work:**

**Comment by ss198126** [comment]
邮箱收不到物品

**Comment by Muigin** [comment]
Reports must be made in English.
