### ISSUE TITLE
Major balance druid bug?

### ISSUE THREAD

**Issue by icedcreamgaming** [slowtorta/turtlewow-bug-tracker#6167]
I believe there is either a bug with nature's grace or a combination of Improved wrath and improved starfire.  The UI shows your bar as a cast time of 1.5 seconds on wrath but using stop watch time trials and video review every cast is 2 seconds when it should be 1.5 seconds with wrath. AND starfire is casting at 3.5 seconds when it should be casting at 3 seconds with improved starfire.

I started figuring this out while doing 5 time trials of each wrath and starfire.  I began thinking that the problem was nature's grace not actually giving you the speed. I found my actual average cast time of wrath to be 1.65-1.76 seconds depending on numbers of crit. and expected time was 1.32-1.43seconds average cast time based on crits. Similar problem with starfire with an average actual cast time of 3.21-3.24 seconds per cast despite 17.6-18.8% crits.  Trial data attached.

There is a small chance that the system is actually registering 2 second normal cast on wrath and 1 second following a crit. As well, 3.5 second regular starfire followed by 2.5 second starfire after crit. If you enter these values into my trial the expected and actual are within 2-3% of expected total cast time on a trial of ~30 spells. 

**Steps to reproduce the behavior with as much detail as possible:**

1. Login to your test server on a balance druid with talents : https://talents.turtle-wow.org/druid/V0X08Z9V-0-U5D6
2. Run a third party clock and a DPS meter that logs crits, hits and misses.
3. Cast 40-100 spells per trial
4. compare your total expected time and your actual recorded time.  (there is likely a lag that can attribute to a small maybe 0.1 second difference average)

![Starfire Spam Trial](https://github.com/slowtorta/turtlewow-bug-tracker/assets/157998650/e7b2551e-d639-4bba-a999-321e286be74d)
![Wrath Spam Trial](https://github.com/slowtorta/turtlewow-bug-tracker/assets/157998650/e0c0c7fa-2817-42e7-a7d3-37f99f5687f0)

**Expected behavior. Describe how it should work:**

100% crit with wrath should experience a near 1s cast time consistently
25% crit with wrath should expect an average cast time of 1.37s 
0% crit should experience an average cast time of 1.5 s

If nature's grace cannot function due to 1.12 server limitations as some druids believe. Simple change the talent to (next wrath does 50% more damage or your next starfire does 20% more damage)
If there is a bug isolated to improved wrath and improved starfire, please resolve.

**Comment by icedcreamgaming** [comment]
I've done further video review and track each cast as:
Wrath (regular) : ~1.8 sec cast time (should be 1.5s)
Wrath (natures grace) : ~1.35s cast time (should be 1s)
Starfire (regular) : ~3.20s cast time (should be 3s)
Starfire(natures grace) : ~2.7s cast time (should be 2.5)

**Comment by twowTurtReynolds** [comment]
The reason you are not able to perfectly chaincast is a 1.12 client bug. Look into https://turtle-wow.fandom.com/wiki/Client_Fixes_and_Tweaks#Nampower

I have recently confirmed that NG does take off -0.5s fully, even Wrath from 1.5->1.0.

**Comment by icedcreamgaming** [comment]
I understand that this was a bug with the game client, however, on the druid tab of the discord people informed that Nampower had stopped working at with 1.17 or 1.17.1. It appears to be functioning again. As well, prior the client wasn't allowing for nature's grace to reduce the GCD on wrath. Now it does, yes.

Please note that this resulted in a 9.56% reduction in average cast time with Nampower. I personally still think this isn't good for the game that people need addons to make it work. It'd almost be better to just receive +dmg on crits or next hit.

Attached is the data and we still see it averaging 12.6% longer to cast. Can you tell me how you calculate your average cast speed and I can see if I can replicate?

![Wrath Spam Trial2 1](https://github.com/slowtorta/turtlewow-bug-tracker/assets/157998650/7ded1380-48d7-4c17-a75a-fba3751ca550)
![Wrath Spam Trial2 2](https://github.com/slowtorta/turtlewow-bug-tracker/assets/157998650/20aa423d-f1f0-43aa-8156-5fb427d1d503)

**Comment by twowTurtReynolds** [comment]
Just hang tight on this.
