### ISSUE TITLE
my guild bank page2 is disappeared

### ISSUE THREAD

**Issue by 200610126** [slowtorta/turtlewow-bug-tracker#6169]
im player at asian server and im also a guild master,when i log in my char at 2.4.2024 8pm before,i see my guild bank page2 is disappeared (tag2?? idk how u guys call this). all the items I put on the page2 disappeared with it. including ten sulfuron ingot（so expensive！！！）and many elementium ore（20-40，two groups im not sure）so many mixture and medicament disappeared with it. now i sent a problem report to gm, but they told me to report bug on github. i real need know where my material and my guild bank page2. im not github user so if u guys have any reply,please send an email to 200610126@qq.com.

ty for u readding and help.

**Comment by twowTurtReynolds** [comment]
Please contact support.
