### ISSUE TITLE
Underground murloc at the gate to the whispering forest

### ISSUE THREAD

**Issue by trihard711** [slowtorta/turtlewow-bug-tracker#617]
**Please, provide a clear description what the bug is:**

When you pass the gate to the whispering forest area, a murloc aggros you.

**Steps to reproduce the behavior with as much detail as possible:**

1. Walk on the road past the entrance to the whispering forest
2. Be level 5-13
3. 

**IDs of affected creatures, items, quests or spells with a link to the relevant page:**

DB is disabled

**Expected behavior. Describe how it should work:**

There should be no murloc there because it does not fit the area.

**Comment by Neto-WoW** [comment]
Unable to reproduce.
