### ISSUE TITLE
Wrong tooltip for Abyssal Wave / Unmelting Ice

### ISSUE THREAD

**Issue by Kangaroux** [slowtorta/turtlewow-bug-tracker#6170]
These items have the same tooltip as Abyssal Wind + Unyielding Gust. Tooltip should be: `Combine the Abyssal Wave with the Unmelting Ice.`

https://database.turtle-wow.org/?item=83557
https://database.turtle-wow.org/?item=83552

**Comment by byvide** [comment]
duplicate of #6033

**Comment by twowTurtReynolds** [comment]
Duplicate of https://github.com/slowtorta/turtlewow-bug-tracker/issues/6033
