### ISSUE TITLE
Tar Lurker Casting Spells after Successful Kick

### ISSUE THREAD

**Issue by Dafemega** [slowtorta/turtlewow-bug-tracker#6174]
**Please, provide a clear description what the bug is:**

**Steps to reproduce the behavior with as much detail as possible:**

1. Fight a Tar Lurker lvl 53 or greater in Un'Goro Crater with a rouge
2. Kick to interrupt Black Sludge or Entangling Root
3. Cast bar disappears but a few seconds later the spell still hits

**IDs of affected creatures, items, quests or spells with a link to the relevant page:**

NPC: https://database.turtle-wow.org/?npc=
Item: https://database.turtle-wow.org/?item=
Quest: https://database.turtle-wow.org/?quest=
Spell: https://database.turtle-wow.org/?spell=
Object: https://database.turtle-wow.org/?object=

**Expected behavior. Describe how it should work:**
Spell should be interrupted and not cast.

**Comment by Dafemega** [comment]
![Uploading WoWScrnShot_020424_163420.png…]()

**Comment by twowTurtReynolds** [comment]
Cast bars are not a 1.12 feature. Your addon that added it is incorrect.
