### ISSUE TITLE
My Game Characters“范德法特”（Emerald Dream）‘s Halo of Transcendence, Its Prophetic Aura（from Zul'Gurub）’has Disappeared

### ISSUE THREAD

**Issue by hoobo123** [slowtorta/turtlewow-bug-tracker#6175]
**Please, provide a clear description what the bug is:**

**Steps to reproduce the behavior with as much detail as possible:**

1.My Game Characters“范德法特”（Emerald Dream）‘s Halo of Transcendence, Its Prophetic Aura（from Zul'Gurub）’has Disappeared
2. help me
3. 

**IDs of affected creatures, items, quests or spells with a link to the relevant page:**

NPC: https://database.turtle-wow.org/?npc=
Item: https://database.turtle-wow.org/?item=
Quest: https://database.turtle-wow.org/?quest=
Spell: https://database.turtle-wow.org/?spell=
Object: https://database.turtle-wow.org/?object=

**Expected behavior. Describe how it should work:**

**Comment by twowTurtReynolds** [comment]
Please contact support.
