### ISSUE TITLE
关于 我们需要的物资 任务完成 没有任务奖励

### ISSUE THREAD

**Issue by mc4box** [slowtorta/turtlewow-bug-tracker#6177]
本人亚服玩家，于2024年2月5日完成 我们需要的物资 这个任务，综合面板显示任务完成，并获得 血色十字军徽记 道具，但是随即查询包裹内并没有任务奖励道具，银行内也没有任务奖励道具，修理机器人也没有卖出。是否这个任务奖励出现了BUG。请检索验证是否有这个BUG，并申请恢复任务道具奖励。
![d980bfb50584459a3b158c0caf58520](https://github.com/slowtorta/turtlewow-bug-tracker/assets/136479459/f14b6107-c7ac-4246-ab08-44b7646a5283)

![a70a1b0d79afb9cb1477ca026aa5df8](https://github.com/slowtorta/turtlewow-bug-tracker/assets/136479459/bd4bb609-311c-4740-8a24-a9a51d0e7443)
![bc6f8cbf626320c90c114eae7f49fef](https://github.com/slowtorta/turtlewow-bug-tracker/assets/136479459/6946da9f-f78c-4083-9975-5ae7cef38c20)

**Comment by Muigin** [comment]
Reports must be made in English.
