### ISSUE TITLE
Regarding the issue of completing the task but not receiving the task props

### ISSUE THREAD

**Issue by mc4box** [slowtorta/turtlewow-bug-tracker#6178]
I am an Asian server player and completed the supplies we needed on February 5, 2024 (I don’t know the  task name European server). For this task, the comprehensive panel showed that the task was completed, and I obtained the Scarlet Crusade emblem prop, but then I checked that there was no task in the package. As for reward props, there are no mission reward props in the bank, and the repair robot has not been sold. Is there a BUG in this mission reward? Please search to verify whether there is this BUG, ​​and apply for restoration mission prop rewards.The props rewarded by missions are very important
![d980bfb50584459a3b158c0caf58520](https://github.com/slowtorta/turtlewow-bug-tracker/assets/136479459/194fe967-8415-4d08-86b0-df80a1a0e99e)
![a70a1b0d79afb9cb1477ca026aa5df8](https://github.com/slowtorta/turtlewow-bug-tracker/assets/136479459/c11c0f37-4f3e-4f5b-bf36-7871400a8ea4)
![bc6f8cbf626320c90c114eae7f49fef](https://github.com/slowtorta/turtlewow-bug-tracker/assets/136479459/6ccf6030-e222-440c-87a5-128b7215196a)

**Comment by byvide** [comment]
Dont worry, the [Scarlet Crusade Insignia](https://database.turtle-wow.org/?item=53005) is on your keyring, not a bug.
