### ISSUE TITLE
纳克萨玛斯获取装备【邪恶力量巨剑】第二天无故消失

### ISSUE THREAD

**Issue by 15516619500** [slowtorta/turtlewow-bug-tracker#6180]
**Please, provide a clear description what the bug is:**

**Steps to reproduce the behavior with as much detail as possible:**

1. Hello GM, I participated in the NAXX Naxxramas group event on the evening of February 4th, copy ID: 1816.2. After defeating Gurus, the No. 3 BOSS in the structural area, obtain the [Great Sword of Evil Power] and find ID: Turtle at 0:38 on February 5, Beijing time (server time: 18:31 on February 4) Paladins and Alliance human paladins can enchant two-handed weapons with +25 agility. The material cost is about 120G, and the enchantment foundry fee is 12G.I logged in again on the afternoon of February 5th and found that the [Great Sword of Evil Power] item disappeared from my account. I had already gone to the Ratchet City NPC to check. There was no [Great Sword of Evil Power] item, and I clearly remembered this. I didn't sell or destroy the item, I just transformed it, and it mysteriously disappeared from me the next day

 3. I have taken screenshots of items that can be transmogrified with one click, screenshots of missing item names, and screenshots of Turtle Paladin players’ chats. I can provide evidence to request to retrieve items and add 25 agility enchantments to items.
 4. 我的乌龟服ID  拉文郡  联盟 高等精灵女 猎人  如花似玉 
**IDs of affected creatures, items, quests or spells with a link to the relevant page:**

NPC: https://database.turtle-wow.org/?npc=Great Sword of Evil Power
Item: https://database.turtle-wow.org/?item=Gurus
Quest: https://database.turtle-wow.org/?quest=
Spell: https://database.turtle-wow.org/?spell=
Object: https://database.turtle-wow.org/?object=

**Expected behavior. Describe how it should work:**

**Comment by twowTurtReynolds** [comment]
Please contact support.
