### ISSUE TITLE
Cannot learn 75->150 Survival cap

### ISSUE THREAD

**Issue by Promise925** [slowtorta/turtlewow-bug-tracker#6181]
Hello GM:

I am in  Asian Server （ Emerald Dream），ID is “诺尔萨斯”.

My  Survival skill    only  have  75  cease growing any taller，but  other  have  150 .

Please help me, I entreat you.

**IDs of affected creatures, items, quests or spells with a link to the relevant page:**

NPC: https://database.turtle-wow.org/?npc=
Item: https://database.turtle-wow.org/?item=
Quest: https://database.turtle-wow.org/?quest=
Spell: https://database.turtle-wow.org/?spell=
Object: https://database.turtle-wow.org/?object=

**Expected behavior. Describe how it should work:**

**Comment by EyeOfTheBeast** [comment]
You have to make Bright Campfires to reach 150.

**Comment by Promise925** [comment]
> You have to make Bright Campfires to reach 150.

Now I am 75/75 ,  I can't reach 150 .

**Comment by Promise925** [comment]
Now  is  this
![微信图片_20240207014038](https://github.com/slowtorta/turtlewow-bug-tracker/assets/158997896/9125064d-670e-4b3f-9fad-f3166155c739)

**Comment by Promise925** [comment]
I  even  can‘t  forget  it , and  learn  it  again .

![2](https://github.com/slowtorta/turtlewow-bug-tracker/assets/158997896/a9c7bf7f-f75d-4912-9337-031444bf66bd)

**Comment by EyeOfTheBeast** [comment]
Haver you done this quest? https://database.turtle-wow.org/?quest=50230

**Comment by Promise925** [comment]
> Have you done this quest? https://database.turtle-wow.org/?quest=50230

Yes ， and now I am reach 75/75 , but I don't have 150 upper limit .

![3](https://github.com/slowtorta/turtlewow-bug-tracker/assets/158997896/c0512b2b-df2a-4691-a4a3-91b3019253b5)

**Comment by EyeOfTheBeast** [comment]
Try deleting the WDB folder.

**Comment by Promise925** [comment]
> Try deleting the WDB folder.

I have been done , but it's useless .

**Comment by byvide** [comment]
With my new little warlock, i went to STV to level up my survival. When my skill reached 55 or 56, the limit went from 75 to 150 randomly. Maybe you could recreate my situation: go to Nesingwary's camp and do a Bright Campfire.

**Comment by Promise925** [comment]
> With my little warlock, i went to STV to level up my survival. When my skill reached 55 or 56, the limit went from 75 to 150 randomly. Maybe you could recreate my situation: go to Nesingwary's camp and do a Bright Campfire.

Thank you , I have been try it , but it doesn't work . My survival still is 75/75 , the limit don't went from 75 to 150 ...

**Comment by byvide** [comment]
@Promise925  maybe #4594 will help

**Comment by twowTurtReynolds** [comment]
Thank you byvide. Indeed I have confirmed with the staff and that to solve this, contact support. The learning of 75->150 is meant to be automated.

**Comment by Promise925** [comment]
> Thank you byvide. Indeed I have confirmed with the staff and that to solve this, contact support. The learning of 75->150 is meant to be automated.

Excuse me  ， how  can  I  contact support  ？

**Comment by twowTurtReynolds** [comment]
For SEA realms, this is on Kook, linked at https://cn.turtle-wow.org/

**Comment by Promise925** [comment]
> Collaborator

In fact ，this  website  don‘t  have  “ Submit the question”，GM in game let us to here submit the question .........

**Comment by Promise925** [comment]
> For SEA realms, this is on Kook, linked at https://cn.turtle-wow.org/

In fact ，this website don‘t have “ Submit the question”，GM in game let us to here submit the question .........
