### ISSUE TITLE
Invocation of Expansive Mind - Unable to apply 'Invocation of Expansive Mind' enchant to head slot

### ISSUE THREAD

**Issue by honestlywtf** [slowtorta/turtlewow-bug-tracker#6182]
**Please, provide a clear description what the bug is:**

'Invocation of Expansive Mind' is an item rewarded by NPC - Heirophant Nerseus in 'Deadwind Pass' located near Karazhan, once the quest 'Invocation of Expansive Mind' is completed.  The item 'Invocation of Expansive Mind' is meant to be applied to either the head or leg slot of a character's gear in order to grant the enchant "Use: Permanently adds 20 spell penetration to a leg or head slot item. Does not stack with other enchantments for the selected equipment slot." However, when this enchant is right clicked and then applied to the head piece, I am getting error "That item is not a valid target"

**Steps to reproduce the behavior with as much detail as possible:**

Character: Roswitha, Dwarf priest, level 60

1. When 'Invocation of Expansive Mind' enchant item is right clicked from inventory and then applied to the worn head piece, I am getting error "That item is not a valid target"
2. Attempted again to 'action click' the item 'Invocation of Expansive Mind' and apply it to head item 'Tiara of the Oracle'. Getting error "That item is not a valid target"
3. Attempted to now apply 'Invocation of Expansive Mind' to legs 'Trousers of the Oracle', only to see if it will work. Same error persists.
4. Close application. Delete game cache. Relaunch. Reattempt enchant application. Error persists.
5. Removed head piece and placed into inventory and attempted to apply the enchant from that location. No change.
![Screenshot_514](https://github.com/slowtorta/turtlewow-bug-tracker/assets/159097466/9d9a2b1e-6958-48b4-bada-ad8fc12ae75f)

6. Raise in game ticket - sent to create bug form. Item remains in inventory unable to be used.

**IDs of affected creatures, items, quests or spells with a link to the relevant page:**

NPC: https://database.turtle-wow.org/?npc= Heirophant Nerseus
Item: https://database.turtle-wow.org/?item= Invocation of Expansive Mind
Quest: https://database.turtle-wow.org/?quest=  Invocation of Expansive Mind
Spell: https://database.turtle-wow.org/?spell= Invocation of Expansive Mind - Use: [Permanently adds 20 spell penetration to a leg or head slot item. Does not stack with other enchantments for the selected equipment slot. 

**Expected behavior. Describe how it should work:**

Quest award Item 'Invocation of Expansive Mind' is supposed to be able to be applied to head or leg slot. Once applied, it permanently adds 20 spell penetration to a leg or head slot item. Does not stack with other enchantments for the selected equipment slot.

**Comment by honestlywtf** [comment]
Tried again today. Issue remains.

**Comment by twowTurtReynolds** [comment]
![image](https://github.com/slowtorta/turtlewow-bug-tracker/assets/151180101/b2f2c11b-0a9e-41aa-8a93-912b380eb42a)
Can't reproduce. 
![image](https://github.com/slowtorta/turtlewow-bug-tracker/assets/151180101/bf393b9d-1b80-4e86-952e-e8862844421e)

**Comment by honestlywtf** [comment]
I completed the quest, have the item in my inventory, and it cannot be applied.
