### ISSUE TITLE
Hazza'rah's Charm of Magic

### ISSUE THREAD

**Issue by Kevin-Yxm** [slowtorta/turtlewow-bug-tracker#6184]
**Please, provide a clear description what the bug is:**
Hello GM:
I am in Asian Server （ Blood Ring）
Hazza'rah's Charm of Magic
Use: Increases the critical hit chance of your Arcane spells by 5%, and increases the critical hit damage of your Arcane spells by 50% for 20 sec.
I tested found that the bonus didn't actually increase the critical hit damage of Arcane spells by 50%.

**Steps to reproduce the behavior with as much detail as possible:**

1.
2. 
3. 

**IDs of affected creatures, items, quests or spells with a link to the relevant page:**

NPC: https://database.turtle-wow.org/?npc=
Item: https://database.turtle-wow.org/?item=
Quest: https://database.turtle-wow.org/?quest=
Spell: https://database.turtle-wow.org/?spell=
Object: https://database.turtle-wow.org/?object=

**Expected behavior. Describe how it should work:**

**Comment by Kevin-Yxm** [comment]
Item:https://database.turtle-wow.org/?item=19959

**Comment by twowTurtReynolds** [comment]
![image](https://github.com/slowtorta/turtlewow-bug-tracker/assets/151180101/5fb1552c-8c80-4caf-9541-643dede983c5)
Works fine.
