### ISSUE TITLE
Quest bugged: Rescue from Jaedenar 

### ISSUE THREAD

**Issue by Thorgral** [slowtorta/turtlewow-bug-tracker#6185]
**Please, provide a clear description what the bug is:**

The NPC named "Captured Arko'narin" will not get out of her cage after speaking with her and starting the quest "recue from Jaedenar"

**Steps to reproduce the behavior with as much detail as possible:**

1. Loot the red key from one of the enemies in Shadow Hold (I got mine from a Jaedenar Legionnaire)
2. Accept the quest given by the key, some along the lines of "find out what the key is used for", I forget the exact wording, but the quest in called "A Strange Red Key".
3. Find the NPC named "captured Arko'narin" in a cage by the exit of Shadow Hold, turn in the quest "find out what the key is used for"
4. Accept the follow-up quest "Recue from Jaedenar"
5. Expected behavior would be for the NPC to get out of the cage and start an RP event / escort mission to find her equipment deeper into Shadow Hold before leaving the hold, but she doesn't move and stay in the cage. 
  
**IDs of affected creatures, items, quests or spells with a link to the relevant page:**

NPC: https://database.turtle-wow.org/?npc=11016

Item: https://database.turtle-wow.org/?item=

Quest: [https://database.turtle-wow.org/?quest=
https://database.turtle-wow.org/?quest=5203](https://database.turtle-wow.org/?quest=5203)

Spell: https://database.turtle-wow.org/?spell=
Object: https://database.turtle-wow.org/?object=

**Expected behavior. Describe how it should work:**
Expected behavior would be for the NPC to get out of the cage and start an RP event / escort mission to find her equipment deeper into Shadow Hold before leaving the hold, but she doesn't move and stay in the cage.

**Comment by twowTurtReynolds** [comment]
![image](https://github.com/slowtorta/turtlewow-bug-tracker/assets/151180101/e49aba69-0d90-4b83-bd1d-ff98a015eaae)
![image](https://github.com/slowtorta/turtlewow-bug-tracker/assets/151180101/2489d73c-3bd9-4183-b430-6a89b7ccee06)
Seems to be working fine.
