### ISSUE TITLE
Silvermoon Remnants Reputation grind is unfair compared to Revantusk Tribe Rep grind.

### ISSUE THREAD

**Issue by mrakis** [slowtorta/turtlewow-bug-tracker#6186]
**Please, provide a clear description what the bug is:**
Hi there, I am starting on the Silvermoon Remnants Reputation grind and I came to notice something odd. I may be wrong about this but when doing all the quests associated with the Silvermoon reputation, I came into a roadblock where there is no more quests, dailies, or mobs to kill that grant rep. The dailies were removed from Silvermoon rep in 17.1 release. However, the Revantusk trolls reputation still have daily quests to earn rep. Silvermoon has runecloth donations. This does not seem fair. Again, I may be wrong but is there something in the works to fix this or is this a known issue? I have completed every single quest I could find for the reputation that isn't either cancelled or deprecated. 
The point is, turning in a stack of 20 runecloth to silvermoon gives 50 rep per stack. While the revantusk have dailies that give 3-5 times the amount of rep for substantially less work. 

In conclusion to this, the horde have an easier time with this rep farm than alliance due to alliance having no dailies anymore and it is exhausting to say the least when you know for a fact the grass is indeed greener on the other side.

**Steps to reproduce the behavior with as much detail as possible:**

1. Complete all the quests for Silvermoon Remnants to include the starting zone, Ironforge, Stormwind and world quests.
2. Be Alliance (?)
3. 

**IDs of affected creatures, items, quests or spells with a link to the relevant page:**

NPC: https://database.turtle-wow.org/?npc=
Item: https://database.turtle-wow.org/?item=
Quest: https://database.turtle-wow.org/?faction=269#quests:0+3+1+2
Spell: https://database.turtle-wow.org/?spell=
Object: https://database.turtle-wow.org/?object=

**Expected behavior. Describe how it should work:**
There should be dailies or increased rep gain with cloth donations in place for the Silvermoon Reputation to match the Revantusk Tribe Reputation because the comparison between how hard the rep grinds are is unbelievable.

**Comment by byvide** [comment]
The bug tracker is for technical issues, and although i support your suggestion, this belongs to the forum.

**Comment by twowTurtReynolds** [comment]
https://forum.turtle-wow.org/viewforum.php?f=14
