### ISSUE TITLE
The quest "No Hope for Tomorrow" is missing

### ISSUE THREAD

**Issue by Lichbanez** [slowtorta/turtlewow-bug-tracker#6187]
The NPC Thirael Blistersong cannot be found in any wing of Dire Maul and even in the outside area

**Steps to reproduce the behavior with as much detail as possible:**

1. Run Dire Maul East, North and West
2. Spam /target Thirael Blistersong everywhere
3. Keep spamming in the outside zone too

**IDs of affected creatures, items, quests or spells with a link to the relevant page:**

NPC: https://database.turtle-wow.org/?npc=60463
Quest: https://database.turtle-wow.org/?quest=40184

The quest should be somewhere in Dire Maul but it isn't, it could have been removed but I have no way of knowing.

**Comment by twowTurtReynolds** [comment]
This quest has been removed on purpose. We'll be adding the Deprecated tag to the quest so that you and others know going forward.
