### ISSUE TITLE
Arcane Power Works Like A Toggle Skill

### ISSUE THREAD

**Issue by Nettngale** [slowtorta/turtlewow-bug-tracker#6188]
Arcane Power Works Like A Toggle Skill

After pressing a 2nd time the spell, Arcane Power buff deactivates

1.Press the spell, buff turns on (you can see in your buffs list on top right of the screen)
2.Looking at the spell icon after 1st button press, it shows this:
![image](https://github.com/slowtorta/turtlewow-bug-tracker/assets/137653051/715ad9fc-c04d-4e6c-bf30-1cec39edd0cf)
3.Press again the spell is canceled and the buff turns off

NPC:
Item: 
Quest: 
Spell: https://database.turtle-wow.org/?spell=12042
Object: 

Since it works like a toggle skill, it makes incompatible to create macros like this:
/cast Arcane power
/cast "Trinket"

What happens is, the 2nd button press to activate the trinket, you deactivate the Arcane power, you can turn it around by making a macro to search for the arcane power icon on the character buffs, if active, it will not deactivate on 2nd button press, and activate the trinket instead, but there's problems with this, the macro will search for the icon, if you have innvervate buff(same skill icon) the macro will not work, and if you have the arcane power on, no one can innervate you.
Can it be fixed to work like a normal active spell?

**Comment by RUTHINAS** [comment]
This is to facilitate the easy cancellation of the spell, as it increases the mana costs of the mage's abilities. The toggle is there on purpose.

**Comment by RUTHINAS** [comment]
`/run if not buffed( "Arcane Power",player) then cast("Arcane Power") end`
