### ISSUE TITLE
公会仓库出现BUG

### ISSUE THREAD

**Issue by mryu1206** [slowtorta/turtlewow-bug-tracker#6189]
我昨天下午的时候 给公会仓库买了第二页物品栏 花费了500金币 今天一上线发现第二页没有了 金币也没有归还我 请工作人员帮我解决一下
我所在的服务器：血环
我的阵营：联盟
我的ID：佩洛西
我的公会名称：谁问你了

**Comment by twowTurtReynolds** [comment]
English only in the tracker.
