### ISSUE TITLE
Gnomish Cloaking Device

### ISSUE THREAD

**Issue by wowtf123** [slowtorta/turtlewow-bug-tracker#6192]
When you click in good time on cloak while someone cast a spell on you, you should have immune it should work like a vanish.
It should work like in link below.
https://www.youtube.com/watch?v=ebYNoVS9T2k&t=61s
1:40

**Comment by twowTurtReynolds** [comment]
The video you posted is from a private server, see the mangos BG queue announcer in the chat. We will need proof from a blizzard server.
