### ISSUE TITLE
Cold snap doesn't reset Ice block about half the time

### ISSUE THREAD

**Issue by Xenocrates644** [slowtorta/turtlewow-bug-tracker#6195]
I pvp a lot as a frost mage so I use cold snap/ice block frequently. I've noticed for a long time now, several months at least, that cold snap doesn't reset the cooldown for ice block about half the time. This is an essential function for frost mages and has caused countless deaths for my character.

**Steps to reproduce the behavior with as much detail as possible:**

1. Fix the cold snap ability to function as it should by resetting the cooldowns for all frost spells including ice block
2. 
3. 

(https://www.wowhead.com/classic/spell=12472/cold-snap)

**Expected behavior. Describe how it should work:**

Cold snap should do what it says it does which is reset the cooldowns for ALL frost spells including ice block. It doesn't not reset it every time, but it happens frequently enough to where this is a consistent error or glitch that has caused immense frustration and has to be fixed.

**Comment by BahamutxD** [comment]
Some addons have problems refreshing/updating spell cooldowns when an special event triggers (like Cold Snap).

Are you certain that the cooldown is infact not refreshing or perhaps its just a display/UI error?

I

**Comment by twowTurtReynolds** [comment]
Indeed this is likely an addon issue. Others in the #mage discord channel haven't seen this issue.
