### ISSUE TITLE
Portal: Theramore doesn't seem to be dropping?

### ISSUE THREAD

**Issue by pepopo978** [slowtorta/turtlewow-bug-tracker#6199]
**Please, provide a clear description what the bug is:**
Unless there is a hidden prerequisite or statue you have to click or something Portal: Theramore doesn't seem to actually drop in lower kara.  I've done countless karas and still don't have it.  I've also never seen another mage with it.

**Steps to reproduce the behavior with as much detail as possible:**

1.  Do 20+ kara runs and never see it drop :)

**IDs of affected creatures, items, quests or spells with a link to the relevant page:**

NPC: https://database.turtle-wow.org/?npc=
Item: https://database.turtle-wow.org/?item=92002
Quest: https://database.turtle-wow.org/?quest=
Spell: https://database.turtle-wow.org/?spell=
Object: https://database.turtle-wow.org/?object=

**Expected behavior. Describe how it should work:**
Based on the drop rate in the database Portal should drop every 2 to 3 kara runs.

**Comment by slowtorta** [comment]
I can confirm this item has never dropped.

**Comment by pmaccamp** [comment]
@slowtorta as in there is a bug?  or are we missing something

**Comment by pepopo978** [comment]
@slowtorta as in there is a bug?  or are we missing something

**Comment by twowTurtReynolds** [comment]
Yes, that means this is indeed bugged. Once fixed this issue will be closed.

**Comment by OonaFae** [comment]
Does this issue also affect Portal: Stonard?

**Comment by Lichbanez** [comment]
Since it's hardly a game changing spell could you consider putting it somewhere a little bit easier to get especially for all those those mages that aren't planning on raiding? Thanks.
