### ISSUE TITLE
GROUNDING TOTEM BUG

### ISSUE THREAD

**Issue by katou83** [slowtorta/turtlewow-bug-tracker#6201]
**Please, provide a clear description what the bug is:**

**Steps to reproduce the behavior with as much detail as possible:**

1.Shamans Grounding totem in PVP doesnt work as inteted
2. It doesnt work with spells: Death Coil, Counterspell, Sheep (50% of the times), Hammer of Justice, Hammer of Wrath(50% of the times), Ignores all traps from hunters.
3. It also never works if you LOS it, even for 2 yards behind a tree.

**IDs of affected creatures, items, quests or spells with a link to the relevant page:**

NPC: https://database.turtle-wow.org/?npc=
Item: https://database.turtle-wow.org/?item=
Quest: https://database.turtle-wow.org/?quest=
Spell: https://database.turtle-wow.org/?spell==8179
Object: https://database.turtle-wow.org/?object=

**Expected behavior. Describe how it should work:**

**Comment by twowTurtReynolds** [comment]
There is another report tracking totem LoS issues.

![image](https://github.com/slowtorta/turtlewow-bug-tracker/assets/151180101/9ba741c4-3f7d-4a21-a788-39ba7e3cd224)
![image](https://github.com/slowtorta/turtlewow-bug-tracker/assets/151180101/721ee833-c2bf-4dda-a27d-bda22155baab)
![image](https://github.com/slowtorta/turtlewow-bug-tracker/assets/151180101/d78c1997-c04b-4e09-9c6e-bd765e58a28f)
![image](https://github.com/slowtorta/turtlewow-bug-tracker/assets/151180101/d0d20b9b-31b8-41d9-8256-5e330ce1ea72)

Its safe to assume you are incorrect about the rest.
