### ISSUE TITLE
Is my hit% 4 or 7? Hard to tell by the game ingame info.,

### ISSUE THREAD

**Issue by shumarte** [slowtorta/turtlewow-bug-tracker#6202]
**Please, provide a clear description what the bug is:**

I'm note sure if it's a bug or "feature", but when I look at my Melee-stats it says I have 4%, which is equal to the gear I have equipped. I have 3/3 in Precision which gives me another 3%, so in total this number should be at 7%. 

**Steps to reproduce the behavior with as much detail as possible:**

1.
2. 
3. 

**IDs of affected creatures, items, quests or spells with a link to the relevant page:**

https://armory.turtle-wow.org/#!/character/Legitpally
Spell: https://database.turtle-wow.org/?spell=24115

![Darkflame Helm](https://github.com/slowtorta/turtlewow-bug-tracker/assets/157279826/5a3d1c3a-5b92-48d6-95fb-5d8ad1e2e3ed)
![Precision talent](https://github.com/slowtorta/turtlewow-bug-tracker/assets/157279826/0dcc8164-7801-44b4-9ec6-954b7f8ca3c3)
![Rune of the Wildhammer Clan](https://github.com/slowtorta/turtlewow-bug-tracker/assets/157279826/4c682258-a769-4e34-8540-0a84f978fe60)
![Wyrmhide Spaulders](https://github.com/slowtorta/turtlewow-bug-tracker/assets/157279826/e943ecf6-88fd-43bc-abe6-0dbc9d3f87d2)

**Expected behavior. Describe how it should work:**
I feel like if it works properly, it should show the hit% from talent in my "Melee tab" for my character. If it's not possible, I'm happy just knowing I have 7% rather than 4% as it's a pretty big difference and those talents would be useful elsewhere..

**Comment by schanzee** [comment]
The game client doesn't show your hit %. You're using an addon that attempts to track gear, buffs and talents itself instead of actually "reading" the data from the server.
This is hence a bug of the addon and you need to create an issue on the respective github.
