### ISSUE TITLE
Baron Geddon Loottable & Lawbringer Spaulders

### ISSUE THREAD

**Issue by Ecceteran** [slowtorta/turtlewow-bug-tracker#6203]
**Please, provide a clear description what the bug is:**

Greetings,
I would just like some verification on the intended values regarding the Baron Geddon loottables, specifically loot pool number 4 concerning not just the Lawbringer Spaulders droprate but also the duplicate addition of Cenarion Spaulders

Spotted issue https://github.com/slowtorta/turtlewow-bug-tracker/issues/4306 marked as completed.
Was wondering whether an action, if any, had been undertaken and the extent of it.

Thank you.

**Steps to reproduce the behavior with as much detail as possible:**

1. Go MC
2. Slay Baron
3. Witness double Cenarion Spaulders drop
Monday's MC stream https://www.twitch.tv/videos/2054219295?t=00h56m27s

**IDs of affected creatures, items, quests or spells with a link to the relevant page:**

NPC: Baron Geddon https://database.turtle-wow.org/?npc=12056

Item: Lawbringer Spaulders https://database.turtle-wow.org/?item=16856
Item: Cenarion Spaulders https://database.turtle-wow.org/?item=16836

**Expected behavior. Describe how it should work:**

Impossibility of duplicate tierpiece drops. ( removal of extra Cenarion Spaulders )
Comparable likelihood of tierpiece droprate ( set Lawbringer Spaulders to one matching the other tierpieces of either of the other loot pools )

**Comment by twowTurtReynolds** [comment]
Double Drops is a feature of TWoW. When this happens with 2 undesirable items, it can feel bad, but the opposite is true in you can get 2 desirable items where blizzlike you cannot. The highs are higher, and the lows are lower.

We won't be changing this to be blizzlike as this takes a lot of bottlenecked dev time, and we still end up with the same overall gear distribution.
