### ISSUE TITLE
Quest: "The Flesh Does Not Lie" bugged

### ISSUE THREAD

**Issue by Bunto86** [slowtorta/turtlewow-bug-tracker#6205]
The quest in Eastern Plaguelands "The Flesh Does Not Lie" is bugged

Quest requires you to gather 20 Plagued Flesh Samples in Strathhomle, which I did
Upon returning the quest she took 14 samples leaving me with 6 and there is a yellow question mark above her now.
In the quest log, the quest is marked as complete, but when I talk to her it still says I need 20 plagued flesh samples and the continue button is grayed out.
Abandoning the quest and grabbing it again leads to the same result. Yellow question mark is still visible.

Quest ID:5212

**Comment by twowTurtReynolds** [comment]
![image](https://github.com/slowtorta/turtlewow-bug-tracker/assets/151180101/9bf842a9-c09d-4e44-bdf6-84edbdd01915)
I can't replicate. I took the https://database.turtle-wow.org/?quest=5212 , spawned https://database.turtle-wow.org/?item=13174 x20 and turned it in, and the next quest is ready.
