### ISSUE TITLE
Unforgiven

### ISSUE THREAD

**Issue by Tobbsu** [slowtorta/turtlewow-bug-tracker#6206]
The boss: ( Unforgiven ) Hides under the floor and can't be attacked -> ( https://database.turtle-wow.org/?npc=10516 ) - plz fix it.

**Comment by twowTurtReynolds** [comment]
![image](https://github.com/slowtorta/turtlewow-bug-tracker/assets/151180101/f9ff5d55-df21-43cf-ad91-e0d799e4ce8d)
Not under the floor, but they are stuck invisible.

Only visible with GM mode on:
![image](https://github.com/slowtorta/turtlewow-bug-tracker/assets/151180101/d60265d5-3dfb-452f-a4a7-5e8749572e8e)

**Comment by ratkosrb** [comment]
Should be fixed in the next update.
