### ISSUE TITLE
Removing Leper Leadership duplicate reward

### ISSUE THREAD

**Issue by AKryukov92** [slowtorta/turtlewow-bug-tracker#6207]
**Please, provide a clear description what the bug is:**
When you complete quest Removing Leper Leadership, you need to choose from single reward AND in addition you will recieve same single reward.
![image](https://github.com/slowtorta/turtlewow-bug-tracker/assets/24266616/564119ba-d469-4f75-977b-e871f6e7bb1f)
Related bug #4785
![image](https://github.com/slowtorta/turtlewow-bug-tracker/assets/24266616/716f1318-2834-49f3-ba6d-09802923ef5a)

**Steps to reproduce the behavior with as much detail as possible:**

1. Pick quest
2. Complete objective
3. Speak to questgiver to finish this quest

**IDs of affected creatures, items, quests or spells with a link to the relevant page:**

Quest: https://database.turtle-wow.org/?quest=40857

**Expected behavior. Describe how it should work:**
Player should recieve only one shield.

**Comment by twowTurtReynolds** [comment]
Looks like a problem from https://github.com/slowtorta/turtlewow-bug-tracker/issues/4785 's solution.

**Comment by Muigin** [comment]
I have applied an aggressive attempt at fixing this which should be in the next maintenance.
