### ISSUE TITLE
Klockmort Spannerspan is still in Tinker Town

### ISSUE THREAD

**Issue by Nightdawg** [slowtorta/turtlewow-bug-tracker#6209]
**Please, provide a clear description what the bug is:**
Klockmort Spannerspan's location is wrong. 
On Turtle WoW he was moved Gnomeregan Reclamation Facility (which is pointed by the quest and npc info in the database), however he's still in Tinker Town in Ironforge.

**Steps to reproduce the behavior with as much detail as possible:**

1. Go to Gnomeregan Reclamation Facility
2. He ain't there
3. Go to Tinker Town in Ironforge
4. He's there

**IDs of affected creatures, items, quests or spells with a link to the relevant page:**

https://database.turtle-wow.org/?quest=1704
https://database.turtle-wow.org/?npc=6169

**Expected behavior. Describe how it should work:**

He's supposed to be in the Gnomeregan Reclamation Facility.

![image](https://github.com/slowtorta/turtlewow-bug-tracker/assets/77711219/471e1a6e-c24d-43b1-be45-bd83c71a0dc7)

**Comment by slowtorta** [comment]
Fixed in the next update.
