### ISSUE TITLE
The Wildtusk Charms (Custom 1.16.0 Quest)

### ISSUE THREAD

**Issue by Gurky-Kronos** [slowtorta/turtlewow-bug-tracker#621]
**Please, provide a clear description what the bug is:**
The quest has you retrieve Wildtusk Charms from Ruins of Zul'Rasaz I have killed a ton of trolls here and also looked everywhere for items on the ground as well but there has been no luck. I have a feeling either the drop chance is way too low or the object is not being spawned to loot. 
**Steps to reproduce the behavior with as much detail as possible:**

1. Get the Quest The Wildtusk Charms in Arathi highlands (new horde area)
2. Head to the Ruins of Zul'Rasaz as the quest states
3. Not able to find any charms for the quest

**IDs of affected creatures, items, quests or spells with a link to the relevant page:**

I cannot, the database is turned off. 

NPC: https://database.turtle-wow.org/?npc=
Item: https://database.turtle-wow.org/?item=
Quest: https://database.turtle-wow.org/?quest=
Spell: https://database.turtle-wow.org/?spell=
Object: https://database.turtle-wow.org/?object=

**Expected behavior. Describe how it should work:**
Charms should be somewhere in the area but so far no luck, I do want to note I am not sure this is a bug or not I asked in discord if there is some tip someone can give me but was told to make a bug.

**Comment by Kruxis** [comment]
Works as intended. Read the quest carefully and keep an eye out for the not to obvious things in your surrounding =)
