### ISSUE TITLE
A Crew Under Fire quest in Azshara not reflecting completion

### ISSUE THREAD

**Issue by roundlakedan** [slowtorta/turtlewow-bug-tracker#6210]
**Please, provide a clear description what the bug is:**

**Steps to reproduce the behavior with as much detail as possible:**

1. Encounter Captain Vanessa Beltis at approximately 53, 87 in Azshara.
2. Accept quest "A Crew Under Fire".
3. Kill three waves of mobs and receive yellow quest completion text
4. Interact with Captain Vanessa Beltis to "complete" quest.
5. Exclamation point now appears over NPC prompting you to do the quest again.

**IDs of affected creatures, items, quests or spells with a link to the relevant page:**

NPC: https://database.turtle-wow.org/?npc=8380

Quest: https://database.turtle-wow.org/?quest=3382

Item: https://database.turtle-wow.org/?item=
Spell: https://database.turtle-wow.org/?spell=
Object: https://database.turtle-wow.org/?object=

**Expected behavior. Describe how it should work:**

Quest should not be offered again upon completion, and according to quest text surrounding NPCs should be offering additional quests for sub-zone.

**Comment by twowTurtReynolds** [comment]
https://www.wowhead.com/classic/quest=3382/a-crew-under-fire wowhead says its repeatable too. This quest was famously unfinished by blizzard. 

Have any proof otherwise?

**Comment by roundlakedan** [comment]
You're totally right, my bad. I was laboring under the ridiculous assumption that "there's no way this 20-year old game has a quest this obviously broken, it must be a new twow quest let me write up a helpful bug report".

I will mark as closed. I don't know how in 15+ years of playing this game I've just never run into this one before. Thanks for the sanity check!
