### ISSUE TITLE
AH-Misclassified Items

### ISSUE THREAD

**Issue by Slimthegrim** [slowtorta/turtlewow-bug-tracker#6211]
**Please, provide a clear description what the bug is:**
Tel'abim | Ironbark Branch missing item subclass and slot category

**Steps to reproduce the behavior with as much detail as possible:**

1. Go to auction house, search manually for Ironbark Branch.
2. Notice it's for sale.
3. Search all listings of Armor/Miscellaneous/Held In Off-hand and notice Ironbark Branch is not listed.
4. Notice the same when searching Armor/Miscellaneous, appears Ironbark Branch is only "armor" category but no sub categories.

Missing from category/subcategory search:
![image](https://github.com/slowtorta/turtlewow-bug-tracker/assets/110629519/1c9e8c42-2c7e-4cf7-a0e5-749092dd7ad9)

Is on the auction house though:
![image](https://github.com/slowtorta/turtlewow-bug-tracker/assets/110629519/464a3d35-3bb9-4cd3-884c-c8a3c15ddd9e)

**IDs of affected creatures, items, quests or spells with a link to the relevant page:**

Object: https://database.turtle-wow.org/?object=](https://database.turtle-wow.org/?item=80828)

**Expected behavior. Describe how it should work:**
Custom Turtle items are harder to find when sub categories and the like get misaligned. Can we get sub categories labeled like the last one I found? Thanks! 👺

**Comment by twowTurtReynolds** [comment]
Indeed, if you can find these and list these in bulk that would be most appreciated, feel free to append here. Thanks

**Comment by twowTurtReynolds** [comment]
@Dormilon Please and thanks
