### ISSUE TITLE
Equipping Blood Guard's Mail Greaves does not give 15% speed bonus if already in ghost wolf form

### ISSUE THREAD

**Issue by discer** [slowtorta/turtlewow-bug-tracker#6213]
**Please, provide a clear description what the bug is:**
If you equip the Blood Guard's Mail Greaves while already in ghost wolf form you do not receive the 15% speed bonus
It does however work if equipped before switching forms
It seem to only take into effect if the boots are equipped before changing to wolf form as unequipping the boots does not remove the speed bonus either
**Steps to reproduce the behavior with as much detail as possible:**

1. Cast Ghost Wolf
2. Run around and equip Blood Guard's Mail Greaves
3. See your speed not increase

**IDs of affected creatures, items, quests or spells with a link to the relevant page:**

Item: https://database.turtle-wow.org/?item=22857

**Expected behavior. Describe how it should work:**
On Equip the 15% speed increase should take effect whether already in wolf form or not

**Comment by ratkosrb** [comment]
This is not really a bug as spell mods are consumed on cast of the spell, but I'll add special handling to this aura to make it update ghost wolf speed instantly.
