### ISSUE TITLE
吉尔尼斯任务山谷蜘蛛任务物品bug

### ISSUE THREAD

**Issue by zhou2053** [slowtorta/turtlewow-bug-tracker#6216]
/**Please, provide a clear description what the bug is:**

**Steps to reproduce the behavior with as much detail as possible:**

1.吉尔尼斯任务山谷蜘蛛接到任务就显示有3个任务物品空洞蛛丝，打了7个就显示任务完成但是不能交任务，放弃重新接任务也是同样问题
2. wdb文件已经删除，插件全关
![微信图片_20240210131343](https://github.com/slowtorta/turtlewow-bug-tracker/assets/159604352/a7816042-377f-410b-8b8e-a0de5b79a8f0)

**IDs of affected creatures, items, quests or spells with a link to the relevant page:**

NPC: https://database.turtle-wow.org/?npc=
Item: https://database.turtle-wow.org/?item=
Quest: https://database.turtle-wow.org/?quest=
Spell: https://database.turtle-wow.org/?spell=
Object: https://database.turtle-wow.org/?object=

**Expected behavior. Describe how it should work:**

**Comment by twowTurtReynolds** [comment]
Please submit in English.
