### ISSUE TITLE
Hunter Quest Bugged

### ISSUE THREAD

**Issue by Shiekx** [slowtorta/turtlewow-bug-tracker#6217]
**Please, provide a clear description what the bug is:

The NPC "Klinfran" should respawn every 15 Minutes. He respawns now roughly every 4+ hours.
This slow down the process alot and people keep waiting for respawn all over and if he respawn people wipe each other by shooting at him ... So bacically you can't do the quest now.

**Steps to reproduce the behavior with as much detail as possible:**

1. 
2. 
3. 

**IDs of affected creatures, items, quests or spells with a link to the relevant page:**

NPC: https://database.turtle-wow.org/?npc=14534
Item: https://database.turtle-wow.org/?item=18953
Quest: https://database.turtle-wow.org/?quest=7636

**Expected behavior. Describe how it should work:**

You just announced it last update:

Reduced respawn times of Rhok'delar quest bosses to 15 minutes.

**Comment by twowTurtReynolds** [comment]
Klinfran:
![image](https://github.com/slowtorta/turtlewow-bug-tracker/assets/151180101/b7c44b46-dbc3-4d5f-965b-bc0be70fc796)
Franklin:
![image](https://github.com/slowtorta/turtlewow-bug-tracker/assets/151180101/2796505e-076b-481d-a69f-ea8721b991e8)

Franklin's spawn time needs to go from 35->15mins, the change was placed onto the scripted Klinfran instead which indeed doesn't help. 

I have no idea why you'd be seeing 4 hours though. Please tell me you are exaggerating. And if so, please don't exaggerate.

**Comment by ratkosrb** [comment]
It seems his core script overrides the respawn time in the database :expressionless:
I will remove the hardcoded respawn time overriding.

https://github.com/vmangos/core/blob/f43ae96d14e7910b9c816f112baefd82d32e9e86/src/scripts/eastern_kingdoms/burning_steppes/burning_steppes.cpp#L458
