### ISSUE TITLE
Crusader Strike does not refresh judgements.

### ISSUE THREAD

**Issue by MrToothless** [slowtorta/turtlewow-bug-tracker#6218]
Title is clear enough and can be replicated simply by judging a mob with any seal and then spamming Crusader Strike. Judged seal will only refresh off a melee swing.

Seals' wording has been quite clear on what refreshes it for 20 years and Crusader Strike's wording is quite clear on what it is; the interaction is not working as it should.

**Comment by twowTurtReynolds** [comment]
https://turtle-wow.org/#/paladin
