### ISSUE TITLE
Quest: Hidden-hidden reward - end dialog

### ISSUE THREAD

**Issue by Gasan918** [slowtorta/turtlewow-bug-tracker#6222]
**Please, provide a clear description what the bug is:**

End dialog of this gnoll quest have (I guess) some formatting errors. Look where 1 gold symbol is.

![image](https://github.com/slowtorta/turtlewow-bug-tracker/assets/96973359/838e1137-4e4f-4f20-905b-df776e1596ff)

**IDs of affected creatures, items, quests or spells with a link to the relevant page:**

Quest: https://database.turtle-wow.org/?quest=55035

**Comment by twowTurtReynolds** [comment]
![image](https://github.com/slowtorta/turtlewow-bug-tracker/assets/151180101/7d8dd3cb-5bec-4893-8cb7-edc2902a79c4)
Please disable addons before reporting UI bugs.
