### ISSUE TITLE
Klinfran the Crazed/Franklin the Friendly does not respawn within 15m as announced in patchnotes

### ISSUE THREAD

**Issue by gwetchen** [slowtorta/turtlewow-bug-tracker#6223]
**Please, provide a clear description what the bug is:**

Klinfran the Crazed/Franklin the Friendly does not respawn after 15 minutes as announced in the [patch notes from February 7th](https://forum.turtle-wow.org/viewtopic.php?t=13010):
"Reduced respawn times of Rhok'delar quest bosses to 15 minutes."

I saw Klinfran the Crazed die about 35 minutes before making this bug report. He has not respawned since and his corpse is still where he died.
I have read other players report the same issue with the other demon bosses in the patch notes' forum thread but have not checked myself.

**Steps to reproduce the behavior with as much detail as possible:**

1. Kill Klinfran the Crazed or watch him be killed
2. See Franklin the Friendly (his human form) not respawn after 15 mintues.

**IDs of affected creatures, items, quests or spells with a link to the relevant page:**

Quest: https://database.turtle-wow.org/?quest=7636
NPC: https://database.turtle-wow.org/?npc=14534
NPC: https://database.turtle-wow.org/?npc=14529

**Expected behavior. Describe how it should work:**

The npc should respawn as Franklin the Friendly after 15 minutes.

**Comment by twowTurtReynolds** [comment]
https://github.com/slowtorta/turtlewow-bug-tracker/issues/6217
