### ISSUE TITLE
Gnomeregan's Reclamation Facility Inn does not generate rested XP

### ISSUE THREAD

**Issue by somatoo** [slowtorta/turtlewow-bug-tracker#6224]
**Please, provide a clear description what the bug is:**
Gnomeragan Reclamation Facility Inn does not give rested experience

**Steps to reproduce the behavior with as much detail as possible:**

1. walk into inn
2.  notice it does not start rested xp
3. 

**IDs of affected creatures, items, quests or spells with a link to the relevant page:**

NPC: https://database.turtle-wow.org/?npc=
Item: https://database.turtle-wow.org/?item=
Quest: https://database.turtle-wow.org/?quest=
Spell: https://database.turtle-wow.org/?spell=
Object: https://database.turtle-wow.org/?object=

**Expected behavior. Describe how it should work:** walk into inn, gain rested xp

**Comment by luskanek** [comment]
The area will be correctly marked as an inn in the next patch.
