### ISSUE TITLE
Love is in the air Npc's

### ISSUE THREAD

**Issue by madzig21** [slowtorta/turtlewow-bug-tracker#6233]
**Please, provide a clear description what the bug is:**

**Steps to reproduce the behavior with as much detail as possible:**

1.Go to darnassus with perfume and or colone on
2. non of the guards or npc have the heart or talk about love is in the air
3. 

**IDs of affected creatures, items, quests or spells with a link to the relevant page:**

NPC: https://database.turtle-wow.org/?npc=
Item: https://database.turtle-wow.org/?item=
Quest: https://database.turtle-wow.org/?quest=
Spell: https://database.turtle-wow.org/?spell=
Object: https://database.turtle-wow.org/?object=

**Expected behavior. Describe how it should work:**
they should accept love tokens and have a heart over there heads.

**Comment by gala320** [comment]
There are NPCs in Darnassus that have hearts over their heads, but they are not interactable.

**Comment by twowTurtReynolds** [comment]
Please contact support if you find a case of this, they will be hotfixing these NPCS with `.aura 26869`
