### ISSUE TITLE
Can't send any mail between bank alt and main char

### ISSUE THREAD

**Issue by Xenocrates644** [slowtorta/turtlewow-bug-tracker#6234]
I've had this issue for months now. I can't send any mail between my bank alt and main character. Even if I haven't sent or received anything that day and just cleared my WDB folder, I try to send 1 piece of mail and it says: "You've hit the in-game cap of unique mail recipients." I can send mail from my main character to bank alt sometimes, but never the other way. But even that is hit or miss.

**Steps to reproduce the behavior with as much detail as possible:**

1. Allow bank alts to send mail between other characters.
2. 
3. 

**Expected behavior. Describe how it should work:**
You should be able to freely send mail between bank alts and main characters.

**Comment by twowTurtReynolds** [comment]
I believe you are running into antispam features. Try leveling up a toon on the alt account, or make a bank alt on your main account.
