### ISSUE TITLE
Nightfin Snapper and Sunscale Salmon

### ISSUE THREAD

**Issue by zipread** [slowtorta/turtlewow-bug-tracker#6235]
**Please, provide a clear description what the bug is:**
The switch from Nightfin to Sunscale happens at 0600 ST and 1800 ST

**Steps to reproduce the behavior with as much detail as possible:**
Fish in the correct area during the day/night

**IDs of affected creatures, items, quests or spells with a link to the relevant page:**
https://database.turtle-wow.org/?item=13759
https://database.turtle-wow.org/?item=13760

**Expected behavior. Describe how it should work:**
All times in Server Time
* 0600-1200 - Nightfin and Sunscale
* 1200-1800 - Sunscale only
* 1800-0000 - Nightfin and Sunscale
* 0000-0600 - Nightfin only 

Right now there is a kludgy fix with both continents being separated by 12 hours, so it's "possible" to avoid fishing for the wrong fish. I've been fishing in WPL near Andorhal, Ferelas at the Verdantis River, and Moonglade around Lake Elune'ara. Actual catch rates also seem very low, like the fish are only in 'mixed' spawns where they share the slot, despite being entirely unable to fish the other fish.

**Comment by Muigin** [comment]
This was changed deliberately at the discretion of the team for better awareness of fish availability with the day/night cycle.  Sunscales can now be caught between 6am and 6pm (continent specific times), and Nightfin between 6pm and 6am.  Both cannot be caught in the same continent at the same time any more.

Won't fix.
