### ISSUE TITLE
Darnassian Protector is not interactable even with Cologne Buff on.

### ISSUE THREAD

**Issue by motowbc0107** [slowtorta/turtlewow-bug-tracker#6237]
**Please, provide a clear description what the bug is:**

**Steps to reproduce the behavior with as much detail as possible:**

1. Obtain Cologne/Perfume buff to see the Amorous buff on NPC  "Darnassian Protector".
2. Have both Cologne/Perfume buff on, and able to see NPC "Darnassian Protector" have Amorous Buff. 
3. Can't interact with any of the NPC "Darnassian Protector" at all regardless if they have Amorous Buff or not.
4. Due to the problem mentioned in step 3, Player can't get "Gift of Friendship: Darnassus".
5. Without "Gift of Friendship: Darnassus", it is impossible for player to complete the quest "Gift Giving".

**IDs of affected creatures, items, quests or spells with a link to the relevant page:**

NPC: https://database.turtle-wow.org/?npc=4423
Item: https://database.turtle-wow.org/?item=22167
Quest: https://database.turtle-wow.org/?quest=8993
Spell: https://database.turtle-wow.org/?spell=26869

**Expected behavior. Describe how it should work:**
After player obtained Cologne/Perfume buff, they should be able to see the Amorous buff on NPC  "Darnassian Protector" with a Heart Icon Floating above that NPC. Furthermore, players should be able to interact with those NPC who have Amorous buff for obtaining the Item "Gift of Friendship: Darnassus".
![image](https://github.com/slowtorta/turtlewow-bug-tracker/assets/20158531/cc7ead6b-2818-42ee-af24-2ec027f8f8fa)

**Comment by twowTurtReynolds** [comment]
Please contact support if you find a case of this, they will be hotfixing these NPCS with .aura 26869
