### ISSUE TITLE
"Snarler" broken NPC

### ISSUE THREAD

**Issue by OhMyNutz** [slowtorta/turtlewow-bug-tracker#6238]
good afternoon, I found a bug with one monster in Feralas called Snarler(Rare), as you know, it has +100 to all attributes of schools of magic, but after you tame it, this unique ability disappears, which is not correct. Below I will indicate the evidence
 

NPC: https://database.turtle-wow.org/?npc=5356

**Comment by Dragunovi** [comment]
![image](https://github.com/slowtorta/turtlewow-bug-tracker/assets/86127352/1f558e15-0623-438a-b147-5d548f5ae8fd)
