### ISSUE TITLE
Dustwind Cave + Sparkwater Port mobs buggy

### ISSUE THREAD

**Issue by rallinex** [slowtorta/turtlewow-bug-tracker#624]
Dustwind Cave and the oil rig to the east of Sparkwater Port. I'm a warlock using voidwalker demon. When I attack from range, the mobs evade my spells. I have to get into melee range to attack and have them not evade. My demon has a lot of pathing difficulties. Often running into walls / underneath the ground. Or will stay in 1 place when I send him in to attack mobs.

**Comment by slowtorta** [comment]
Our custom maps aren't perfect but it's the best we can offer at this moment. Maybe in the future, we'll introduce a fix for all similar issues involving unexpected LOS.

**Comment by geojak** [comment]
yeah i also noticed this just now on my new mage. all the mobs in there will not move a single inch. they cast their ranged spell on you and then start evading and resetting their health. you have to go into meele as mage in order to kill them.

**Comment by geojak** [comment]
probsbly the most buggy place i have seen so far on twow
