### ISSUE TITLE
Shredder's abilities aren't used when control is over

### ISSUE THREAD

**Issue by januszthewizard** [slowtorta/turtlewow-bug-tracker#6240]
**Please, provide a clear description what the bug is:**
Shredder summoned by item in Alterac Valley doesn't use all of its abilities after we break control.

**Steps to reproduce the behavior with as much detail as possible:**

1. Use Zinfizzlex's Portable Shredder Unit in Alterac Valley.
2. Right click the buff that allows you to control the Shredder in your buff bar.
3. Wait until enemy player comes close to Shredder.
4. See that the Shredder doesn't use its abilities apart from auto attacks.

**IDs of affected creatures, items, quests or spells with a link to the relevant page:**

NPC: https://database.turtle-wow.org/?npc=13378 - Horde Shredder, https://database.turtle-wow.org/?npc=13416 - Alliance Shredder
Item: https://database.turtle-wow.org/?item=17384 - Horde, https://database.turtle-wow.org/?item=17410 - Alliance
Quest: -
Spell: https://database.turtle-wow.org/?spell=21556, https://database.turtle-wow.org/?spell=21559
Object: -

**Expected behavior. Describe how it should work:**
After breaking the control of Shredder, it should use its all abilities, especially ability called Shredder Armor Melt.

**Comment by ratkosrb** [comment]
It will be fixed in the next update.
