### ISSUE TITLE
High Inquisitor Whitemane doesn't start encounter

### ISSUE THREAD

**Issue by Szwedowski** [slowtorta/turtlewow-bug-tracker#6242]
**Please, provide a clear description what the bug is:**

**Steps to reproduce the behavior with as much detail as possible:**

1. Go into the Cathedral wing of Scarlet Monastery
2. Clear trash mobs inside the Cathedral 
3.  Kill High Inquisitor Fairbanks
4. Agro and kill Scarlet Commander Mograine
5. After his death, a gate doesn't open and High Inquisitor Whitemane doesn't start script: resurrection of Mograine and fight with them both.

![image](https://github.com/slowtorta/turtlewow-bug-tracker/assets/99164611/f9be8a2c-dc63-4e84-b4a5-0a2d736b2c87)

**IDs of affected creatures, items, quests or spells with a link to the relevant page:**

NPC: 
https://database.turtle-wow.org/?npc=3977
https://database.turtle-wow.org/?npc=3976

**Expected behavior. Describe how it should work:**
Upon death of Scarlet Commander Mograine, a gate opened, High Inquisitor Whitemane going to the group, cast [Deep Sleep](https://database.turtle-wow.org/?spell=9256), resurrect Scarlet Commander Mograine and fight begins again.

Update: killed Scarlet Commander Mograine twice - result was the same.

**Comment by Szwedowski** [comment]
Looks like fix from changelog [2024 — January 10](https://forum.turtle-wow.org/viewtopic.php?t=12632) still did not work

**Comment by twowTurtReynolds** [comment]
I tested this a few times, a few times I replicated a few times I did not. It seems if you kill him too fast as you would as a lv 60, it bugs him  out. Normal level players don't have this problem since the Jan10th fix.

Work around this by killing him slower and making sure you do a full clear of the final room beforehand.

We'll see if we can make this 100% reliable in the code.

**Comment by ratkosrb** [comment]
I don't understand how its possible to kill him before Whitemane has entered the fight. He enables invincibility on aggro, his health can't be reduced below 1. When he reaches 1 health, he applies untargetable flag to himself and changes stand state to dead, but he's actually still alive. Only after Whitemane "resurrects" him, can he truly be killed. But in your screenshot, he's actually dead. I don't get how that can happen, the invincibility threshold gets set to 1 on aggro.

**Comment by ratkosrb** [comment]
I made some changes in hopes to fix this if you were somehow bypassing the invincibility threshold of EventAI. Setting minimum HP will now function like god mode does for players, and should prevent death in all cases. Let's see if issue is fixed next week.

**Comment by Rosenebula520** [comment]
this is the problem we just met ._. We've tried to kill him very very slowly the last time. It still don't work, she just don't want to come out. :)

Uploading WeChat_20240214021213.mp4…

**Comment by Szwedowski** [comment]
It is working now. 
Upon Mograine death, a gate opened and Whitemane  came to ressurect him
