### ISSUE TITLE
Felhunter Paranoia not working properly.

### ISSUE THREAD

**Issue by Malachirizzo23** [slowtorta/turtlewow-bug-tracker#6243]
Ever since the most recent update, the warlock's pet, felhunter's spell Paranoia is no longer detecting stealthed players, no matter how close they are to the character under the affect of the spell. I have tried on multiple occasions to detect stealthed players by having them stand directly in front of me while I have both Paranoia up as well as Cat's eye elixir for added effect and have not been able to see a stealthed player before they enter melee range since the most recent update.

**Comment by twowTurtReynolds** [comment]
![image](https://github.com/slowtorta/turtlewow-bug-tracker/assets/151180101/61885223-ca40-4767-a555-c92bb6eadcb1)
![image](https://github.com/slowtorta/turtlewow-bug-tracker/assets/151180101/56b14184-ce3f-4b82-8eb5-7f738755fbc3)

Seems to work fine.

**Comment by twowTurtReynolds** [comment]
I have received further reports and have some more detailed testing:

Using .distance to find the exact values:
an equal level stealther is only visible at 9yd
Paranoia increases this to 18yd:
![image](https://github.com/slowtorta/turtlewow-bug-tracker/assets/151180101/bf1de04e-8797-4c35-8bae-5e0c497c4fa5)

Now, I've been informed that Paranoia and Hunter's Track Stealth should have the same power.
![image](https://github.com/slowtorta/turtlewow-bug-tracker/assets/151180101/af42de63-ab55-4ba7-9bb1-40234238ab7f)

At 18yd, this shadowmelded player dissappears for both.

If anyone has definitive blizzlike proof of this yardage being too small, please let us know.
