### ISSUE TITLE
Grifter's Boots BOP instead of BOE

### ISSUE THREAD

**Issue by Judo101** [slowtorta/turtlewow-bug-tracker#6245]
The Grifter's set is a great 6 piece for leather wearers. Every piece is BOE but the boots, which seems out of place, from what I've seen, the custom crafting sets have the chest piece as BOP. I believe this is a bug. 

https://database.turtle-wow.org/?item=83405
https://database.turtle-wow.org/?spell=46620

**Comment by twowTurtReynolds** [comment]
https://github.com/slowtorta/turtlewow-bug-tracker/issues/1805
