### ISSUE TITLE
Quest: "Race Against Time!"

### ISSUE THREAD

**Issue by SlippyStarfox** [slowtorta/turtlewow-bug-tracker#6246]
**Please, provide a clear description what the bug is:**

**Steps to reproduce the behavior with as much detail as possible:**

1. Speak to Daisy
2. Accept the quest "Race Against Time!"
3. Timer starts
4. Car won't spawn

**IDs of affected creatures, items, quests or spells with a link to the relevant page:**

NPC: https://database.turtle-wow.org/?npc=4507

Quest:https://database.turtle-wow.org/?quest=50316

**Comment by ratkosrb** [comment]
You need to accept this quest when you already have one of the other quests.
