### ISSUE TITLE
Learned Formula: Eternal Dreamstone Shard not appears in the enchanting skill list

### ISSUE THREAD

**Issue by BloodyHou** [slowtorta/turtlewow-bug-tracker#6248]
I learned the Formula: Eternal Dreamstone Shard, but it's not in the enchanting skill list. Could you please tell me why?

**IDs of affected creatures, items, quests or spells with a link to the relevant page:**

https://database.turtle-wow.org/?item=61733
Item: https://database.turtle-wow.org/?item=61732

**Expected behavior. Describe how it should work:**
Please add the learned the Formula: Eternal Dreamstone Shard to my enchanting skill list (my account is: ww231919520ww)

Thanks,

**Comment by BloodyHou** [comment]
![dream](https://github.com/slowtorta/turtlewow-bug-tracker/assets/159854821/3b6dbc57-9711-4a07-b70a-07a94e17184a)
Please refer to the attached image, I did leare the Formula: Eternal Dreamstone Shard, but can not find it in the enchanting skill list. Could you make a further investigation, and tell me why? Thanks.

**Comment by twowTurtReynolds** [comment]
We in the bug tracker have no access to the live accounts. If you need a GM to review your specific account to see if a spell ID of 57518 was learned correctly, please make a ticket in game.

I cannot replicate your issue, so unless you have different replication steps than I have shown, there is nothing we can do on the dev side.

**Comment by BloodyHou** [comment]
OK, thanks, I 'll contact GM in game.
