### ISSUE TITLE
Most damage shields are scaling by 40% of spellpower

### ISSUE THREAD

**Issue by Velite12** [slowtorta/turtlewow-bug-tracker#625]
![image](https://user-images.githubusercontent.com/45871932/147611496-29cfe328-324c-4298-8a47-a7494119570f.png)

Not sure if this is intended but all of my recoild (damage shield) items are scaling by a ton of my spellpower.

**Comment by geojak** [comment]
I am not sure but this might have been fixed by now

**Comment by CosminPOP** [comment]
fixed indeed
