### ISSUE TITLE
Gurubashi arena chest not spawning

### ISSUE THREAD

**Issue by ciciiig** [slowtorta/turtlewow-bug-tracker#6250]
**Please, provide a clear description what the bug is:**
I've been waiting for the chest in the middle of the battle ring to spawn, but it does not.

**Steps to reproduce the behavior with as much detail as possible:**

1. chest spawns every three hours in the middle of battle ring. 
2. players fight for it
3. it gives items that must be collected in the end to get BIS pvp trinket.

**IDs of affected creatures, items, quests or spells with a link to the relevant page:**

Item: https://www.wowhead.com/classic/object=179697/arena-treasure-chest

**Expected behavior. Describe how it should work:**
It should spawn every 3 hours.

**Comment by twowTurtReynolds** [comment]
You may have the wrong hour timer. Keep in mind that if your local time participates in daylight savings, this hour will shift back and forward an hour throughout the year.

**Comment by ciciiig** [comment]
I was adjusting to server time, that is shown under mininap in the game.
