### ISSUE TITLE
Smoldering Dream Essence should be soulbound yes / no?

### ISSUE THREAD

**Issue by Sheed90** [slowtorta/turtlewow-bug-tracker#6256]
**Please, provide a clear description what the bug is:**
Should the Druid Quest Item from Emerald Sanctum be soulbound?

If not, then the behavior of the item is a bit strange. When I tried to send it by mail, it became "soulbound". 
After consulting with a GM, it shouldn't be that way and he kindly sent it directly to our guild bank character. 
However, If I then tried to put it in the guild bank, it became 'soulbound' again on the lvl 10 character.

**Steps to reproduce the behavior with as much detail as possible:**

1. Loot Smoldering Essence from Solnius the Awakener
2. Try to put it into the guildbank or try to send it via mail
3. See that it became 'soulbound'.

**IDs of affected creatures, items, quests or spells with a link to the relevant page:**

NPC: https://database.turtle-wow.org/?npc=60748
Item: https://database.turtle-wow.org/?item=61444

**Expected behavior. Describe how it should work:**
If the DEVs don't want it to be soulbound, then it should not get the status "soulbound" after trying to move, send, etc.

**Comment by twowTurtReynolds** [comment]
The item is Bind on Pickup, but was improperly configured to display this on the item.  This will be resolved in the next maintenance, after which you should be sure to clear your WDB cache.
