### ISSUE TITLE
Zeppelin to Kargath

### ISSUE THREAD

**Issue by Gurky-Kronos** [slowtorta/turtlewow-bug-tracker#626]
**Please, provide a clear description what the bug is:**
You die during the loading screen, I took fall damage and died when taking the zep
**Steps to reproduce the behavior with as much detail as possible:**

1. Get on zep to kargath from Org
2. wait until loading screen and you will hear your character take damage (fall damage) once you can see your character he/she is dead.

**IDs of affected creatures, items, quests or spells with a link to the relevant page:**
N/A

NPC: https://database.turtle-wow.org/?npc=
Item: https://database.turtle-wow.org/?item=
Quest: https://database.turtle-wow.org/?quest=
Spell: https://database.turtle-wow.org/?spell=
Object: https://database.turtle-wow.org/?object=

**Expected behavior. Describe how it should work:**
You shouldnt take fall damage and die on  zep ride.

**Comment by slowtorta** [comment]
Sorry, it never ever happened to me and I don't know what's causing this.

**Comment by zomgits** [comment]
Please do not close this.  There are other reports of the same problem.  The bug is still there.
![image](https://user-images.githubusercontent.com/97355053/150678649-f41766a7-a169-4c7d-a835-d4fc421743a5.png)

**Comment by Gurky-Kronos** [comment]
> Please do not close this.  There are other reports of the same problem.  The bug is still there.
> ![image](https://user-images.githubusercontent.com/97355053/150678649-f41766a7-a169-4c7d-a835-d4fc421743a5.png)
> 

They closed this report.

**Comment by CaptainSlapster** [comment]
If this is still an issue that's persisting I have an idea. It maybe a flag in the SQL DB or DBC files that handles transports/game objects like boats that isn't correctly set. It's an idea to look into( I'm not at my computer. I'm at work rn.)
