### ISSUE TITLE
Valentine's Day task reward bug

### ISSUE THREAD

**Issue by cbxcc** [slowtorta/turtlewow-bug-tracker#6260]
**Please, provide a clear description what the bug is:**
After opening the Lavishly Decorated Container for task rewards, it becomes an empty box with nothing left
**Steps to reproduce the behavior with as much detail as possible:**

1.
2. 
3. 

**IDs of affected creatures, items, quests or spells with a link to the relevant page:**

NPC: https://database.turtle-wow.org/?npc=
Item: https://database.turtle-wow.org/?item=
Quest: https://database.turtle-wow.org/?quest=
Spell: https://database.turtle-wow.org/?spell=
Object: https://database.turtle-wow.org/?object=

**Expected behavior. Describe how it should work:**

**Comment by twowTurtReynolds** [comment]
I can't replicate, so there's no widespread bug here.

 Please contact support if you need help with your specific character.
