### ISSUE TITLE
Wind Stone - Summoning Duke of Cynders

### ISSUE THREAD

**Issue by chaossonic** [slowtorta/turtlewow-bug-tracker#6262]
I'm currently on the, Three Kings of Flame, quest.  I have been trying to do this on my character named, Boomsol.

Attempts to use the Crest of Beckoning: Fire to summon him directly are not pulling up the option on the Wind Stone.

1.  I have collected the neccesary items to summon the Duke of Cynders in Silithus.  The three pieces of Twilight Trappings, Medallion of Station, and the Crest of Beckoning: Fire in my inventory.
2.  I tested the Crest of Beckoning: Fire on three Lesser Wind Stones, which will summon the correct type of elemental.  Each time Crest of Beckoning: Fire is used to summon an elemental of fire, which was consumed properly on the Lesser Wind Stones.
3.  I tested to see if I could just summon a random Duke from the Wind Stones, that consumed Twilight Trappings and Medallion of Station each time.  (I know that the items being consumed is correct behavior.)
4.  I waited based on GMs response and have came back the last two days, checking all three camps to see if the option to summon the correct elemental from the Wind Stone would be available.

**Quest**
(https://www.wowhead.com/classic/quest=8961/three-kings-of-flame)

**Crest of Beckoning: Fire**
https://www.wowhead.com/classic/item=20416/crest-of-beckoning-fire

**Three Piece Set required**
https://www.wowhead.com/classic/item-set=492/twilight-trappings

**NPC that should be available to spawn.**
https://www.wowhead.com/classic/npc=15206/the-duke-of-cynders

**Medallion of Station**
https://www.wowhead.com/classic/item=20422/twilight-cultist-medallion-of-station

**Wind Stone**
https://www.wowhead.com/classic/object=180461/wind-stone

**Correct Behavior**
What should happen is that when the three pieces of Twilight Trappings and Medallion of Station are worn with the Crest of Beckoning: Fire in my bags on my character (not the bank) the option to summon The Duke of Cynders should become available on the Windstone.

**Comment by Muigin** [comment]
You are incorrect.  Crests of Beckoning are for summoning Templars.  Signets of Beckoning are for summoning Dukes.  Scepters of Beckoning are for summoning Lords (raid bosses).

This is working as intended.
