### ISSUE TITLE
turtle wow lost quests bug

### ISSUE THREAD

**Issue by Dreadnought94** [slowtorta/turtlewow-bug-tracker#6263]
**Please, provide a clear description what the bug is:**
lost about 30 completed quests today i think after the restart, some of the elders i know i did last year have been reset but i have no idea what else is reset

**Steps to reproduce the behavior with as much detail as possible:**

1.
2. 
3. 

**IDs of affected creatures, items, quests or spells with a link to the relevant page:**

NPC: https://database.turtle-wow.org/?npc=
Item: https://database.turtle-wow.org/?item=
Quest: https://database.turtle-wow.org/?quest=
Spell: https://database.turtle-wow.org/?spell=
Object: https://database.turtle-wow.org/?object=

**Expected behavior. Describe how it should work:**

**Comment by Muigin** [comment]
https://forum.turtle-wow.org/viewtopic.php?f=63&t=13088

![firefox_A6Lj2Y8zzK](https://github.com/slowtorta/turtlewow-bug-tracker/assets/148400503/02d491a3-ba07-44de-af82-aefe90617213)

**Comment by Dreadnought94** [comment]
well dont take away my game progress and most of lunar festival is not reset
