### ISSUE TITLE
Stave of the Ancients Respawn timer

### ISSUE THREAD

**Issue by Josephienvandermeersch** [slowtorta/turtlewow-bug-tracker#6268]
**Please, provide a clear description what the bug is:**
Update stated that All demons Respawn on a 15 Min timer now, They all do except Solenor the Slayer
**Steps to reproduce the behavior with as much detail as possible:**

Doesn't spawn after 15 minutes. 

**Expected behavior. Describe how it should work:**
Should spawn in 15 Minutes.

**Comment by twowTurtReynolds** [comment]
![image](https://github.com/slowtorta/turtlewow-bug-tracker/assets/151180101/4cd41c0e-7461-4d27-a60e-cec213c75b1f)
@ratkosrb same issue as https://github.com/slowtorta/turtlewow-bug-tracker/issues/6217

Looks like it affects the remaining 2 as well:

![image](https://github.com/slowtorta/turtlewow-bug-tracker/assets/151180101/9e6c6263-6c7c-4f77-b025-063fd6381e8b)
![image](https://github.com/slowtorta/turtlewow-bug-tracker/assets/151180101/0b281b62-634d-45dc-893e-d9496aafc705)

**Comment by ratkosrb** [comment]
Sigh, who hardcoded all these respawn timers. I'll remove them.

**Comment by Josephienvandermeersch** [comment]
Is this fixed? It seems like Solenor the Slayer isn't spawning at all now
