### ISSUE TITLE
One of the hyjal roots isn't working

### ISSUE THREAD

**Issue by jc473** [slowtorta/turtlewow-bug-tracker#6269]
**Please, provide a clear description what the bug is:**
One of the hyjal roots just outside Nordanaar (see picture below) doesn't work. When you have the quest to collect 8 of them, you can click on the root but after the five second timer completes, you do not receive the item into your backpack nor does the root itself disappear.

![image](https://github.com/slowtorta/turtlewow-bug-tracker/assets/155504016/7e7e5f35-11bc-4db6-955b-e12ce1ba49b6)

**Steps to reproduce the behavior with as much detail as possible:**

1.  Pick up the quest "Stockpiling Hyjalroot".
2.  Click on this root.
3.  At the end of the collection timer, you will see that the item has not been picked up nor does root itself disappear from the terrain.

Quest: https://database.turtle-wow.org/?quest= https://database.turtle-wow.org/?quest=40871

**Comment by twowTurtReynolds** [comment]
![image](https://github.com/slowtorta/turtlewow-bug-tracker/assets/151180101/eb3b5ce3-c132-45d8-b7b7-568d13ce35e6)
I can't replicate.
