### ISSUE TITLE
Kwee Q. Peddlefeet from the Love Is in the Air event doesn't give the player a buff when doing the /kiss emote to him

### ISSUE THREAD

**Issue by EyeOfTheBeast** [slowtorta/turtlewow-bug-tracker#6274]
**Please, provide a clear description what the bug is:**
The Kwee Q. Peddlefeet NPC from the Love Is in the Air event doesn't give the player a buff when doing the /kiss emote to him.

**Steps to reproduce the behavior with as much detail as possible:**
1. Find Kwee Q. Peddlefeet during the Love Is in the Air event.
2. Target Kwee Q. Peddlefeet and do the /kiss emote to him.
3. No +200 health buff will be given to the player.

**IDs of affected creatures, items, quests or spells with a link to the relevant page:**
Kwee Q. Peddlefeet NPC: https://database.turtle-wow.org/?npc=16075
Smitten spell buff that you should receive: https://database.turtle-wow.org/?spell=27572

**Expected behavior. Describe how it should work:**
[Wowhead Classic comment 1](https://www.wowhead.com/classic/npc=16075/kwee-q-peddlefeet#comments:id=2830454):
> you gather all of the stacks into a gift of alliance/horde. You turn it at ur favorite racial leader's city (right next to him/her in fact). The leader with the most votes gets to keep Kwee for awhile.
> 
> REASON WHY: Kwee buffs you at any time! /kiss him and you'll get a +200 hp buff for an hour.

[Wowhead Classic comment 2](https://www.wowhead.com/classic/npc=16075/kwee-q-peddlefeet#comments:id=41480):
> If you target Kwee and do "/kiss" you will get a +200 hp buff for 1 hour. If you logout to the char select screen and go back in and do it again, you'll get a second buff to total +400 hp. That's for you lowbies to enjoy.

**Comment by ratkosrb** [comment]
Should be fixed after the next update.
