### ISSUE TITLE
Confirmation prompt when you hit 60 while doing the HC challenge

### ISSUE THREAD

**Issue by Flecked42** [slowtorta/turtlewow-bug-tracker#6275]
I recently hit 60 by accident on a HC character doing the inferno challenge because I forgot to lock my exp.

I was thinking a confirmation prompt comes up when you hit 60 while doing the HC challenge would prevent this from happening in the future.

**Comment by twowTurtReynolds** [comment]
This is not a bug, please post on the suggestions forum.
