### ISSUE TITLE
Using Blink spell in water causes you to move 20 yards forward and downwards 

### ISSUE THREAD

**Issue by jc473** [slowtorta/turtlewow-bug-tracker#6276]
**Please, provide a clear description what the bug is:**
Go into any body of water (example Stormwind canals) and using the Mage spell 'Blink' and it will move 20 yards both forwards and downwards. This occurs when you are either blinking from a static or moving state.

Spell: https://database.turtle-wow.org/?spell= https://database.turtle-wow.org/?spell=1953

**Expected behavior. Describe how it should work:**
The spell should only move your forward by 20 yards.

**Comment by twowTurtReynolds** [comment]
![image](https://github.com/slowtorta/turtlewow-bug-tracker/assets/151180101/64e23d8d-f155-4042-9096-1d04d7491d8d)
![image](https://github.com/slowtorta/turtlewow-bug-tracker/assets/151180101/2355141c-fe31-4df7-8f19-21aa3608caaa)

**Comment by Muigin** [comment]
This should be fixed in the next maintenance.
