### ISSUE TITLE
"No pockets to pick" on mob with pickpocket table with quest item.

### ISSUE THREAD

**Issue by melg8** [slowtorta/turtlewow-bug-tracker#6277]
**Please, provide a clear description what the bug is:**

In database on site there is pickpockeiting table for mob: [Forest Ooze](https://database.turtle-wow.org/?npc=8766#pick-pocketing)
Even containing quest item: [Encoded Fragment](https://database.turtle-wow.org/?item=20023)
But when you try to pickpocket that creature you get error: "No pockets to pick".

**Steps to reproduce the behavior with as much detail as possible:**

1. Get in stealth as a rogue to Forest Ooze 
2. Try pickpocket on it.
3. Observe error message: "No pockets to pick".

**IDs of affected creatures, items, quests or spells with a link to the relevant page:**

NPC: [Forest Ooze](https://database.turtle-wow.org/?npc=8766#pick-pocketing)
Item: [Encoded Fragment](https://database.turtle-wow.org/?item=20023)
Quest: [Encoded Fragments](https://database.turtle-wow.org/?quest=8235)
Spell: [Pickpocket](https://database.turtle-wow.org/?spell=5967)

**Expected behavior. Describe how it should work:**
I would suggest one of two options: 
1.  change mob to be pickpocketable
2. change pickpocket table to be empty

**Comment by ratkosrb** [comment]
Should be fixed in the next update.
