### ISSUE TITLE
 Hazzuri trolls and Sealed Azure Bag

### ISSUE THREAD

**Issue by RaubZar** [slowtorta/turtlewow-bug-tracker#6279]
Hello, Turtles.
Hazzuri Hexxers and Hazzuri Speaker have Sealed Azure Bag (for rogue quest in Azshara) in their pickpocket loot pool.

Item: https://database.turtle-wow.org/?item=19775
Quest: https://database.turtle-wow.org/?quest=8234

**Comment by ratkosrb** [comment]
It will be fixed in the next update.
