### ISSUE TITLE
Bright Campfire flags for combat, and locks player in combat till it despawns

### ISSUE THREAD

**Issue by pjlmaster** [slowtorta/turtlewow-bug-tracker#628]
**Please, provide a clear description what the bug is:**

**Steps to reproduce the behavior with as much detail as possible:**

1. Use Bright Campfire Spell at Arena
2. Be placed into combat for reasons and be pvp flagged
3. Combat never ends
4. get killed by other faction pvp flagged players while trying to get that sweet sweet rested XP
5. ***Deleting WDB folder does clear this bug***

**IDs of affected creatures, items, quests or spells with a link to the relevant page:**

NPC: https://database.turtle-wow.org/?npc=
Item: https://database.turtle-wow.org/?item=
Quest: https://database.turtle-wow.org/?quest=
Spell: https://database.turtle-wow.org/?spell=
Object: https://database.turtle-wow.org/?object=

**Expected behavior. Describe how it should work:**
Ideally not be put in combat by leveling survival.

**Comment by Tinyfin-github** [comment]
Greetings! This it's a not bug. If you buff a player flagged for pvp you will get flagged for pvp.
