### ISSUE TITLE
BWL Suppression Room Elite Mob Respawn Rate

### ISSUE THREAD

**Issue by Youngyeety** [slowtorta/turtlewow-bug-tracker#6280]
In the suppression room in Black Wing Lair the Hatchers and the Taskmasters are respawning too quick. They normally respawn after 20 minutes but are currently respawning after 5 minutes. This is on the Tel'abim PvP server.

1.Raid Black Wing Lair on the Tel'abim PvP server , I was playing on Horde.
2. Kill a hatcher(s) and or the task master pack(s) in the suppression room 
3. Wait to see how long it takes to respawn.

Link to affected mobs ↓↓↓
Hatcher - https://database.turtle-wow.org/?npc=12468
Taskmaster - https://database.turtle-wow.org/?npc=12458

The Hatchers and Taskmasters should respawn 20 minutes after being killed.

**Comment by AkalixFrost** [comment]
I have verified on both Tel'Abim and Nordanaar that the mobs are respawning on a 12 minute timer. If you encounter this again please reopen this report and submit a GM ticket asking for them to send Akalix the `.npc info` results of the affected mobs.
