### ISSUE TITLE
Gold Vein in Burning Steppes 2

### ISSUE THREAD

**Issue by AKryukov92** [slowtorta/turtlewow-bug-tracker#6281]
**Please, provide a clear description what the bug is:**
Issue about gold veins was marked as completed last month https://github.com/slowtorta/turtlewow-bug-tracker/issues/6020
But gold veins still can be found in Burning Steppes.
![image](https://github.com/slowtorta/turtlewow-bug-tracker/assets/24266616/830446c5-8965-4e2c-b00b-886ff55a9af3)

**Steps to reproduce the behavior with as much detail as possible:**

1. Go to Dreadmaul rock
2. Wait for gold vein to spawn

**IDs of affected creatures, items, quests or spells with a link to the relevant page:**
[Gold Vein](https://database.turtle-wow.org/?object=1734)

**Expected behavior. Describe how it should work:**
Gold should not be present in Burning Steppes

**Comment by twowTurtReynolds** [comment]
Is it just this one node, or have you seen others?

**Comment by ratkosrb** [comment]
All gold veins will be gone from the zone in the next update.
