### ISSUE TITLE
Aoe abilities don't take creature Combat Reach into account

### ISSUE THREAD

**Issue by balakethelock** [slowtorta/turtlewow-bug-tracker#6283]
**Please, provide a clear description what the bug is:**
Creatures with a large hitbox require you to stand in the center of their hitbox to hit them with an aoe ability such us challenging shout or consecration.

**Steps to reproduce the behavior with as much detail as possible:**

1. Be a warrior
2. Fight a unit with a large hitbox. For example Ragnaros
3. See that to hit it with whirlwind or demo shout, you need to jump inside the lava to the center of the hitbox

or be a paladin and try with Consecration, or a mage and try with arcane explosion.

**IDs of affected creatures, items, quests or spells with a link to the relevant page:**

core

**Expected behavior. Describe how it should work:**
Aoe abilities are supposed to hit creatures on a center to edge range check (Your center, to the edge of the creature's hitbox)
https://github.com/vmangos/core/commit/fc0d6cfd6192b5c90072d77ab289f165ea540a00

**Comment by jameyboor** [comment]
This will be added on next week's update.
