### ISSUE TITLE
Orb of Pure Light quest chain seems to be missing

### ISSUE THREAD

**Issue by Lichbanez** [slowtorta/turtlewow-bug-tracker#6284]
The entire chain doesn't have a starting point but it's not labeled as deprecated so I don't know if it's because of a bug or intended.

Quest: https://database.turtle-wow.org/?quest=20000

I found evidence of the quest working in the past but now I can't find how to start it or recent informations about it.

**Comment by Szwedowski** [comment]
That quest started from legendary item Orb of Pure Light that droped in Naxx.  
But any way, quest chain stopped on step https://database.turtle-wow.org/?quest=20002 , was impossible to got Cape.

**Comment by twowTurtReynolds** [comment]
This was deprecated long ago on purpose. Thanks for the tip, we'll rename it in the DB to indicate as such.
