### ISSUE TITLE
Rich Thorium Veins in Un'Goro are non present.

### ISSUE THREAD

**Issue by Ramaan** [slowtorta/turtlewow-bug-tracker#6285]
Hello Turtle - Team

I've been farming Thorium Veins all over Un'Goro mostly but also Silithus more or less.
I've been noticing for a week now that all Rich Veins in Un'Goro doesn't spawn anymore and I've read in Discord that they all got replaced with small veins with a 10% chance to become a rich one.

In the last week I haven't been able to even find one single Rich Veins in Un'goro by any chance in the entire Zone. Is this normal ?
So far I've smelted more than 500 Bars without ANY Rich Veins in the area.

**Comment by twowTurtReynolds** [comment]
RTVs are indeed spawning.

**Comment by Ramaan** [comment]
So this literally makes it extremely difficult to farm arcane crystals because its now rng based. Could you explain this crazy change ? There are way more efficient ways to stop botters than this.
