### ISSUE TITLE
Drowning zone on Feralas path (~77.0, ~48.5)

### ISSUE THREAD

**Issue by syrathegreat** [slowtorta/turtlewow-bug-tracker#6289]
**Please, provide a clear description what the bug is:**
On the path across the river south of Camp Mojache in Feralas, there is a spot just after the log across the river which triggers the drowning timer. I would guess this is due to the water map (or whatever it's called) not matching the geometry and extending out too far resulting in some protruding from the ground as the hill descends. I've attached images below:
![image (2)](https://github.com/slowtorta/turtlewow-bug-tracker/assets/133609560/14abc4c6-849a-4b0b-85c4-c39552a165d8)
![image (1)](https://github.com/slowtorta/turtlewow-bug-tracker/assets/133609560/ba77b235-2e5b-4ffd-aa5d-0cab003d1162)

**Steps to reproduce the behavior with as much detail as possible:**

1. Follow the path around camp mojache and across the log that bridges the river 
2. As you proceed down the hill (~77.0, ~48.5) the drowning timer should flag.

**Expected behavior. Describe how it should work:**

There should be no drowning indicators triggering outside of water (or other fluid) areas.

**Comment by twowTurtReynolds** [comment]
Please read the pins.
