### ISSUE TITLE
Survial Skills Missing

### ISSUE THREAD

**Issue by Gurky-Kronos** [slowtorta/turtlewow-bug-tracker#629]
**Please, provide a clear description what the bug is:**

In the new survival window there are no skills even though I own all of them and have for quite some time. WDB does not fix this, I even went as far to try a fresh client with no addons.

**Steps to reproduce the behavior with as much detail as possible:**

1. Open the survival tab
2. Notice you have the skill all the way leveled up
3. Notice you are missing your tent and boat
4. Notice bright camp fire is the only one left in your spell book.

**IDs of affected creatures, items, quests or spells with a link to the relevant page:**

No access as of right now

NPC: https://database.turtle-wow.org/?npc=
Item: https://database.turtle-wow.org/?item=
Quest: https://database.turtle-wow.org/?quest=
Spell: https://database.turtle-wow.org/?spell=
Object: https://database.turtle-wow.org/?object=

**Expected behavior. Describe how it should work:**
The campfire tent and boat should all show up there.

**Comment by Gurky-Kronos** [comment]
Fix: Open all your profession windows and then survival and everything will display.

**Comment by hazlema** [comment]
> Fix: Open all your profession windows and then survival and everything will display.
This is not a fix its a hack.  The issue still remains.

**Comment by Gurky-Kronos** [comment]
> > Fix: Open all your profession windows and then survival and everything will display.
> 
> This is not a fix its a hack.  The issue still remains.  The resulting window shows both the survival skills and the skills of the other window you opened.
> 
> Image:
> https://ibb.co/1GZBZz5

Sorry I fixed my reply.... open a different profession and less will show. I already spoke with Torta about this.
