### ISSUE TITLE
叛徒罗玛斯任务无法提交

### ISSUE THREAD

**Issue by Aning7177** [slowtorta/turtlewow-bug-tracker#6292]
**Please, provide a clear description what the bug is:**
任务无法提交
**Steps to reproduce the behavior with as much detail as possible:**

1.NPC无法选中
2. NPC无法与其对话
3. 任务无法提交

**IDs of affected creatures, items, quests or spells with a link to the relevant page:**

NPC: https://database.turtle-wow.org/?npc=大魔导师罗玛斯
Item: https://database.turtle-wow.org/?item=任务
Quest: https://database.turtle-wow.org/?quest=叛徒罗玛斯
Spell: https://database.turtle-wow.org/?spell=
Object: https://database.turtle-wow.org/?object=

**Expected behavior. Describe how it should work:**

**Comment by twowTurtReynolds** [comment]
Reports only in English.
