### ISSUE TITLE
Testaments of true love任务，无法完成

### ISSUE THREAD

**Issue by fashionKKK** [slowtorta/turtlewow-bug-tracker#6293]
**Please, provide a clear description what the bug is:**

**Steps to reproduce the behavior with as much detail as possible:**

1.
![任务截图](https://github.com/slowtorta/turtlewow-bug-tracker/assets/160325848/4da1a7a8-89c9-45f9-9253-e6c85ce42639)

2. 
![无法提交截图](https://github.com/slowtorta/turtlewow-bug-tracker/assets/160325848/906f6e07-365c-4f3e-bed7-58bb9ffa45c1)

3. 

**IDs of affected creatures, items, quests or spells with a link to the relevant page:**

NPC: https://database.turtle-wow.org/?npc=
Item: https://database.turtle-wow.org/?item=
Quest: https://database.turtle-wow.org/?quest=
Spell: https://database.turtle-wow.org/?spell=
Object: https://database.turtle-wow.org/?object=

**Expected behavior. Describe how it should work:**

**Comment by ratkosrb** [comment]
It is actually blizzlike that you cannot turn in any quests to him in the post even phase, but I'll change it for your convenience.
