### ISSUE TITLE
mounted players won't dismount when controlled by the gnomish mind control cap.

### ISSUE THREAD

**Issue by ConcernedTurtler** [slowtorta/turtlewow-bug-tracker#6294]
**Please, provide a clear description what the bug is:**

when you use the gnomish mind control cap on an enemy player that is mounted they won't attack targets or do anything but ride beside you until the effect ends.  I'm not sure if this is how it worked on classic or not but it's already a very situational item because you can only use it on targets that are out of combat so not being able to use it effectively on mounted targets just makes it even more situational.  

I think when you use it on a mounted target they should dismount after you order them to attack another player or mob that makes the most sense to me.

**Steps to reproduce the behavior with as much detail as possible:**

1. Use the gnomish mind control cap on a mounted enemy.
2. Try to order them to attack another player or enemy.
3. Observe that they do nothing until the effect ends.

**IDs of affected creatures, items, quests or spells with a link to the relevant page:**

NPC: https://database.turtle-wow.org/?npc=
Item: https://database.turtle-wow.org/?item=
Quest: https://database.turtle-wow.org/?quest=
Spell: https://database.turtle-wow.org/?spell=
Object: https://database.turtle-wow.org/?object=

**Expected behavior. Describe how it should work:**

**Comment by ratkosrb** [comment]
Should be fixed in the next update.

**Comment by ratkosrb** [comment]
![WoWScrnShot_021924_182954](https://github.com/slowtorta/turtlewow-bug-tracker/assets/35845488/5aea03f5-d9f1-49b8-9f66-b40532319b38)

This is in fact blizzlike btw. You can't dismount mounted player when controlling him. Tested it on the official classic ptr. But since turtle is a custom server, we can change it here for player convenience.
