### ISSUE TITLE
Posting single stacks of mana oil on the ah

### ISSUE THREAD

**Issue by TurtleTester** [slowtorta/turtlewow-bug-tracker#6296]
**Please, provide a clear description what the bug is:**

**Steps to reproduce the behavior with as much detail as possible:**

1.have 5 total stacks of mana oil in varying sizes 
2. post in sizes below 5 stacks

(3.) cancel ur auction so u dont scam the community

**IDs of affected creatures, items, quests or spells with a link to the relevant page:**

NPC: https://database.turtle-wow.org/?npc=
Item: https://database.turtle-wow.org/?item=
Quest: https://database.turtle-wow.org/?quest=
Spell: https://database.turtle-wow.org/?spell=
Object: https://database.turtle-wow.org/?object=

**Expected behavior. Describe how it should work:**

**Comment by twowTurtReynolds** [comment]
![image](https://github.com/slowtorta/turtlewow-bug-tracker/assets/151180101/ce7e7c0c-bad4-43e4-bdf8-585e37fb5564)
This is reflected on the tooltip, and this is blizzlike behavior, there is no issue here.

**Comment by TurtleTester** [comment]
ah my b i thought there was something in patch notes a while back about only being able to post full stacks to stop scammers, thanks for looking into it
