### ISSUE TITLE
Quest: Breaking the Felstar repeated spawn

### ISSUE THREAD

**Issue by Janusregno** [slowtorta/turtlewow-bug-tracker#630]
**Please, provide a clear description what the bug is:**
When interacting with the Corrupted Felstone at the border of Ashenvale and Felwood you can use the interaction option as many times as possible, spawning multiple versions of the mobs on top of each other.
**Steps to reproduce the behavior with as much detail as possible:**

1. Go to Nightsong Woods with the Breaking the Felstar quest active.
2. Interact with the Corrupted Felstone, using the quest option.
3. Repeat

**IDs of affected creatures, items, quests or spells with a link to the relevant page:**

NPC: https://database.turtle-wow.org/?npc=
Item: https://database.turtle-wow.org/?item=
Quest: https://database.turtle-wow.org/?quest=
Spell: https://database.turtle-wow.org/?spell=
Object: https://database.turtle-wow.org/?object=

**Expected behavior. Describe how it should work:**
There should probably be some kind of cooldown on using the quest option on the Corrupted Felstone to avoid multiple spawnings.
![image](https://user-images.githubusercontent.com/76000153/147612609-74fb8566-7f08-4d29-9696-6cd04ea3668b.png)

**Comment by tubtubs** [comment]
Note, this bug may lead to duplicated High Elf Rangers too.

Additionally, the `dead` infernal seems to move around just a little bit.

![2022-01-03 17_11_47-World of Warcraft](https://user-images.githubusercontent.com/96892771/147993630-c6d6f1fd-474d-4f07-b55c-94b4a6d4a1d1.png)
.

**Comment by geojak** [comment]
And the elite that spawns at the end doesn't attack

**Comment by geojak** [comment]
I closed my above duplicate issue. One should be enough and this is written better

**Comment by geojak** [comment]
this is not fixed
