### ISSUE TITLE
blackwing lair attunement

### ISSUE THREAD

**Issue by evilson1** [slowtorta/turtlewow-bug-tracker#6301]
**Please, provide a clear description what the bug is:
Character nick : EvILSoN
Trying to do the bwl attunement quest,killed the below mentiond NPC 3 times and it doesn't drop the item which starts the quest.
checked inventory and bank and i don't have it.
Not sure(since i don't remember),if there is a chance that in previous ocasion i have had the item but trowing it sinsce i couldn't do the dungeon at that stage.

**Steps to reproduce the behavior with as much detail as possible:**

1. kill npc "scarshield Quartermaster"
2. Loot "blackhand's command"
3. start the quest
4. use glowing  orb behind boss "General Drakkisath"

**IDs of affected creatures, items, quests or spells with a link to the relevant page:**
Display ID: 8900 "Scarshield Quartermaster "
Display ID: 16161 "blackhand's command"

NPC: https://database.turtle-wow.org/?npc=
Item: https://database.turtle-wow.org/?item=
Quest: https://database.turtle-wow.org/?quest=
Spell: https://database.turtle-wow.org/?spell=
Object: https://database.turtle-wow.org/?object=

**Expected behavior. Describe how it should work:**
the npc should drop the "blackhand's command" when killed with 100% drop chance

**Comment by EyeOfTheBeast** [comment]
You have to kill him while NOT in a raid group for the quest item to drop.

**Comment by twowTurtReynolds** [comment]
The raid group thing was likely the problem. It works fine out of raid: ![image](https://github.com/slowtorta/turtlewow-bug-tracker/assets/151180101/f0924948-df14-44ae-9dfd-9ba4716ef9a3)
