### ISSUE TITLE
Zandalarian Hero Charm and Arcane Missiles could get an improvement

### ISSUE THREAD

**Issue by Nettngale** [slowtorta/turtlewow-bug-tracker#6304]
When using Zandalarian Hero Charm you have 30 charges, you lose 17 spell power by spending each charge, when using Arcane Missiles, you lose a charge by each missile. It means, you lose 85 spell power in one channel of Arcane Missiles.

1. Use Zandalarian Hero Charm;
2. Cast Arcane Missiles;
3. Watch your buffs list on top right of the screen showing the 30 charges go down each missile.

Item: https://database.turtle-wow.org/?item=19950
Spell: https://database.turtle-wow.org/?spell=10274
Spell: https://database.turtle-wow.org/?spell=18807

Why not make it spend 1 charge for each channel (5 missiles) of Arcane Missiles, I mean, every spell can proc equip effects, while Arcane Missiles has the advantage of chance of proccing 5 time in one channel, the damage per second still is lower than one spell normally cast between 2-3 seconds, which means an Arcane Missile should crit at least 2-3 times to be compared to a normal cast (non crit) of frostbolt/fireball/shadowbolt, which means it will take 2-3 seconds of casting to compare its damage to other spam spells. 

Mindflay does not consume those charges, is a channeling spell, channels for 3 seconds slows for 50%, (I think maybe it cannot proc equip items each tick of damage, not sure and did not tested it, all I know is from people saying it does not, and by comparing it with Arcane Missiles).

EDIT: the effect from Arcane Missiles having a chance to proc for each missile an equip effect is awesome, it is really cool and brings life to Arcane spells.

**Comment by twowTurtReynolds** [comment]
The bug tracker is not the suggestions forum.
