### ISSUE TITLE
Lost hunter pet

### ISSUE THREAD

**Issue by ctaward64** [slowtorta/turtlewow-bug-tracker#6306]
**Please, provide a clear description what the bug is:**

**Steps to reproduce the behavior with as much detail as possible:**

1. Tammed a second version of brokentooth
2. looked at both versions in my stable
3. went to summon new version back and there was nothing there

**IDs of affected creatures, items, quests or spells with a link to the relevant page:**

NPC: https://database.turtle-wow.org/?npc=2850
Item: https://database.turtle-wow.org/?item=
Quest: https://database.turtle-wow.org/?quest=
Spell: https://database.turtle-wow.org/?spell=
Object: https://database.turtle-wow.org/?object=

**Expected behavior. Describe how it should work:**
I had fed the pet, not sure if there was an issue taming the same rare spawn. Did not see message about it running away, and should not have been enough time passing for it to have ran away.

account name: WOUNDERHOUSE
Character: Nessanie

**Comment by twowTurtReynolds** [comment]
![image](https://github.com/slowtorta/turtlewow-bug-tracker/assets/151180101/ab8926b3-b8bc-4a82-9743-661416555128)

Can't replicate. I just swapped them back and forth, and both still exist.

I think it ran away and you didn't notice.
