### ISSUE TITLE
Smoldering Dream Essence can't be traded

### ISSUE THREAD

**Issue by zrss1** [slowtorta/turtlewow-bug-tracker#6307]
**Please, provide a clear description what the bug is:**

**Steps to reproduce the behavior with as much detail as possible:**

1.Smoldering Dream Essence. This item cannot be traded today. It was previously possible to buy and trade in AH. Can't trade right now.

**IDs of affected creatures, items, quests or spells with a link to the relevant page:**

Item:https://database.turtle-wow.org/?item=61444
**Expected behavior. Describe how it should work:**

**Comment by Muigin** [comment]
The item was always intended to be Bind on Pickup, and now is.  Clear your WDB to see this reflected in the tooltip.

Working as intended.
