### ISSUE TITLE
Unlearned armorsmithing by choosing to be an armorsmith

### ISSUE THREAD

**Issue by Bombg** [slowtorta/turtlewow-bug-tracker#6311]
**Please, provide a clear description what the bug is:**

So I'll start out by saying I've been a maxed out 300/300 armorsmith for a few months now and have accumulated quite a few armorsmithing only schematics. A friend asked my to craft him some thorium spurs so I went to the anvil in orgrimmar to craft them. I accidently right clicked on Krathok Moltenfist, who is near the anvil, and at the bottom of his text window there was a option to click/choose something along the lines of "I wish to be an armorsmith". Me already being an armorsmith, having done the quest previously, clicked on it to see what would happen.  

I was stripped of my blacksmithing/armorsmithing knowledge but then immediately relearned the professions(armorsmithing and blacksmithing). Unfortunately, every single schematic I learned from the trainers is now gone, and every single schematic that was armorsmithing specific is now gone from my list as well. The only schematics I appear to still have now are the ones that I learned that were not learned from a trainer nor was armorsmithing specific.  This is very unfortunate since I previously had some very rare and also some very expensive armorsmithing schematics.

**Steps to reproduce the behavior with as much detail as possible:**

1. Already be a blacksmith and armorsmith
2.  Talk to Krathok Moltenfist
3. Choose the " I wish to be an armorsmith" option -- I'm paraphrasing since I don't remember exactly what the line was

**IDs of affected creatures, items, quests or spells with a link to the relevant page:**

NPC: https://database.turtle-wow.org/?npc=11176
Item: https://database.turtle-wow.org/?item=
Quest: https://database.turtle-wow.org/?quest=
Spell: https://database.turtle-wow.org/?spell=
Object: https://database.turtle-wow.org/?object=

**Expected behavior. Describe how it should work:**

IF someone is already an armorsmith, when someone talks to Krathok Moltenfist and chooses "I wish to be an armorsmith" option, nothing should happen. Even better, if someone is already an armorsmith, the option shouldn't even be there. If this is an intentional mechanic for non armorsmiths, you'd think there would be a warning after saying that all your skills will be wiped. I had no way of knowing this would happen.  

When you even talk to Krathok Moltenfist he even says in his text "Be warned, <adventurer>. Once the choice is made and the tasks required is completed - there is no going back. One can only walk down one path.".

**Comment by ratkosrb** [comment]
This should be fixed in the next update. He wont offer the option if you already have the specialization.
