### ISSUE TITLE
Hack/bug in darnassus

### ISSUE THREAD

**Issue by LoganRill** [slowtorta/turtlewow-bug-tracker#6312]
[**Please,](

https://github.com/slowtorta/turtlewow-bug-tracker/assets/160533467/7463affa-8dbd-4155-a481-047adfba2e89

) provide a clear description what the bug is:**

**Steps to reproduce the behavior with as much detail as possible:**

1.
2. 
3. 

**IDs of affected creatures, items, quests or spells with a link to the relevant page:**

NPC: https://database.turtle-wow.org/?npc=
Item: https://database.turtle-wow.org/?item=
Quest: https://database.turtle-wow.org/?quest=
Spell: https://database.turtle-wow.org/?spell=
Object: https://database.turtle-wow.org/?object=

**Expected behavior. Describe how it should work:**

**Comment by LoganRill** [comment]
Sent a bug report yesterday about the same thing but adding a video to better explain

**Comment by twowTurtReynolds** [comment]
https://github.com/slowtorta/turtlewow-bug-tracker/issues/6309
