### ISSUE TITLE
Tmog window not appearing 

### ISSUE THREAD

**Issue by Bonkyboy** [slowtorta/turtlewow-bug-tracker#6313]
The Tmog window isn't appearing on a particular character, WHEN I INTERACT WITH THE orgrimmar fashinonista,whereas it works on every other one of mine.  I deleted the wdb folder, still nothing, how do I fix this?

Name of affected character is Rollbluntz.

THANK YOU

**Comment by twowTurtReynolds** [comment]
Please disable all addons and mods and try again. Use a fresh twow client to be sure.
