### ISSUE TITLE
Zebrian the mad (rare mob) spawn timer 

### ISSUE THREAD

**Issue by addiktedd** [slowtorta/turtlewow-bug-tracker#6314]
**Please, provide a clear description what the bug is:**
Hello, I would just like to ask if you could check the spawn timer of zebrian the mad, it would usually vary inbetween 1h20-1h30m without fail like it says on the addon of the db, but since 1-2 days ago he looks like he has bugged out and stopped spawning apart of when server restarts.
I've been camping this guy for mount and it sucks hes respawn timer looks to be broken.
Seriously, thank you in advance for checking this.

**Steps to reproduce the behavior with as much detail as possible:**

1.
2. 
3. 

**IDs of affected creatures, items, quests or spells with a link to the relevant page:**

NPC: https://database.turtle-wow.org/?npc=50103
Item: https://database.turtle-wow.org/?item=
Quest: https://database.turtle-wow.org/?quest=
Spell: https://database.turtle-wow.org/?spell=
Object: https://database.turtle-wow.org/?object=

**Expected behavior. Describe how it should work:*

**Comment by twowTurtReynolds** [comment]
His current bug is that his pathing takes him almost immediately into an inaccessible instance, see: https://github.com/slowtorta/turtlewow-bug-tracker/issues/5105
