### ISSUE TITLE
Hagen's BUG

### ISSUE THREAD

**Issue by Sean-Huangsheng** [slowtorta/turtlewow-bug-tracker#6315]
**Please, provide a clear description what the bug is:**

**Steps to reproduce the behavior with as much detail as possible:**

1.We encountered a lot of bugs in the process of killing Hagen. When we first entered the battle, mobs were refreshed on the platform at the same time, including bats and bugs.
2. 
3. 

**IDs of affected creatures, items, quests or spells with a link to the relevant page:**

NPC: https://database.turtle-wow.org/?npc=
Item: https://database.turtle-wow.org/?item=
Quest: https://database.turtle-wow.org/?quest=
Spell: https://database.turtle-wow.org/?spell=
Object: https://database.turtle-wow.org/?object=

**Expected behavior. Describe how it should work:**

**Comment by schanzee** [comment]
What platform?
The trash infront of Heigan is a gauntlet and will respawn indefinitely while the boss is alive in short intervals. If you take too long to kill it or wait too long before pulling the boss they will respawn.

**Comment by jameyboor** [comment]
This is fixed on next server update.
