### ISSUE TITLE
Lost some item in auction house

### ISSUE THREAD

**Issue by Perse-V** [slowtorta/turtlewow-bug-tracker#6316]
Posted around 8 Brilliant wizard oil in auction house, sold 2 and received the payment in mail while the other 6 is gone.
Posted on around feb 18-19, 

Brilliant Wizard Oil 1x
Bid: 9.50.0
Buyout: 9.50.0

*no other proof for these
*not sure if theres log i can check
*also deleted wdb folder

**Steps to reproduce the behavior with as much detail as possible:**

1.
2. 
3. 

**IDs of affected creatures, items, quests or spells with a link to the relevant page:**

NPC: https://database.turtle-wow.org/?npc=
Item: https://database.turtle-wow.org/?item=
Quest: https://database.turtle-wow.org/?quest=
Spell: https://database.turtle-wow.org/?spell=
Object: https://database.turtle-wow.org/?object=

**Expected behavior. Describe how it should work:**

**Comment by twowTurtReynolds** [comment]
Please contact support.
