### ISSUE TITLE
Cannot add more players to ignore list.

### ISSUE THREAD

**Issue by Robin11th** [slowtorta/turtlewow-bug-tracker#6318]
**Please, provide a clear description what the bug is:**
Cannot add more players to ignore list.

**Steps to reproduce the behaviour with as much detail as possible:**

1. Add player to ignore list
2. Error: you can't ignore any more players.
3. 

**IDs of affected creatures, items, quests or spells with a link to the relevant page:**

NPC: https://database.turtle-wow.org/?npc=
Item: https://database.turtle-wow.org/?item=
Quest: https://database.turtle-wow.org/?quest=
Spell: https://database.turtle-wow.org/?spell=
Object: https://database.turtle-wow.org/?object=

**Expected behaviour. Describe how it should work:**
Player has been added to ignore list. Please increase the maximum amount of players on ignore list. The current maximum is only 20, which is very low on such a big server.
![image](https://github.com/slowtorta/turtlewow-bug-tracker/assets/147619315/ce2e2842-e9a3-458a-82c7-fe498e5dbadf)

**Comment by Slimthegrim** [comment]
In my experience this is a client limitation and just requires https://github.com/Lexiebean/SuperIgnore or similar addon.

**Comment by Robin11th** [comment]
> In my experience this is a client limitation and just requires https://github.com/Lexiebean/SuperIgnore or similar addon.

Ah I didn't know that, thanks! :)
