### ISSUE TITLE
crazy cat lady title not working

### ISSUE THREAD

**Issue by jokuleo** [slowtorta/turtlewow-bug-tracker#6319]
**Please, provide a clear description what the bug is:**

**Steps to reproduce the behavior with as much detail as possible:**
https://forum.turtle-wow.org/viewtopic.php?f=4&t=8172
1.i am male goblin rogue i have all 10 cats needed for crazy cat lady title i use https://forum.turtle-wow.org/viewtopic.php?f=4&t=8172 as my guide. I have deleted wdb/wtf folder multiple times. i have summoned all kittens out and emote them
2. list of my cats:
 https://database.turtle-wow.org/?item=8491
https://database.turtle-wow.org/?item=8486
https://database.turtle-wow.org/?item=11903
https://database.turtle-wow.org/?item=80010
https://database.turtle-wow.org/?item=8487
https://database.turtle-wow.org/?item=8490
https://database.turtle-wow.org/?item=8488
https://database.turtle-wow.org/?item=8489
https://database.turtle-wow.org/?item=23712
https://database.turtle-wow.org/?item=81283

4. 

**IDs of affected creatures, items, quests or spells with a link to the relevant page:**

NPC: https://database.turtle-wow.org/?npc=
Item: https://database.turtle-wow.org/?item=
Quest: https://database.turtle-wow.org/?quest=
Spell: https://database.turtle-wow.org/?spell=
Object: https://database.turtle-wow.org/?object=

**Expected behavior. Describe how it should work:**

**Comment by twowTurtReynolds** [comment]
![image](https://github.com/slowtorta/turtlewow-bug-tracker/assets/151180101/939fc78c-4560-49d6-92e2-5b43b8eccd35)
Replicated, as per https://forum.turtle-wow.org/viewtopic.php?f=4&t=8172 we both have them all. Look at the first ID off your list that I added, it seems mismatched... perhaps that is the problem?

**Comment by lyssebabz** [comment]
Guide seems wrong
cats you need:
4 hard to get ones:
biggleworth
corrupted kitten
white tiger cub
midnight
7 from wetlands vendor
bombay
cornish rex
orange tabby
maine coon
siamese
silver tabby
white kitten

Guide is lacking "Bombay"

**Comment by twowTurtReynolds** [comment]
Thank you!
![image](https://github.com/slowtorta/turtlewow-bug-tracker/assets/151180101/7d74fe85-746f-434c-abcf-43958dd3cffa)

**Comment by Avery1337** [comment]
Its hard to keep these guides accurate when I am the only eyes on it. Im glad I get feedback like this. This guide has been updated. Sorry for the confusion.
