### ISSUE TITLE
Reputation change did not effect item prices

### ISSUE THREAD

**Issue by GunnaMagnusson** [slowtorta/turtlewow-bug-tracker#6321]
Hello, 
my char Outoffavor got revered in Thunder Bluff the other day but the prices of the items like supplies etc. did not change. However i am able to buy the gear that is locked behind this standing from the vendor. WDB is cleared and i made sure that it's not just displayed wrong, the prices it shows are what i pay to the copper.
need some help solving this.
thank you in advance

**Comment by twowTurtReynolds** [comment]
In vanilla wow, only Honored and R3 gives a discount.
