### ISSUE TITLE
Druid cat form bugged

### ISSUE THREAD

**Issue by Kriegbd** [slowtorta/turtlewow-bug-tracker#6322]
**Cat form is supposed to increase agility but it does not work**

**Steps to reproduce the behavior with as much detail as possible:**

1. Look at stats
2. Enter cat form
3. Look at stats again

I have added 3 screenshots, the tooltip and stats before/in catform.

![Human form](https://github.com/slowtorta/turtlewow-bug-tracker/assets/141413554/b7a2b80d-4633-4e89-a9df-340c6f5d5e7d)
![Cat tooltip](https://github.com/slowtorta/turtlewow-bug-tracker/assets/141413554/54cd47c9-c2f8-4beb-bd07-4716604989ac)
![Cat form](https://github.com/slowtorta/turtlewow-bug-tracker/assets/141413554/84bf8e12-088b-4a43-a8c0-be95fbc4c002)

**Comment by twowTurtReynolds** [comment]
Works correctly. 104 + 120 + 79 = 303
![image](https://github.com/slowtorta/turtlewow-bug-tracker/assets/151180101/68d0e0d0-3e50-4816-928b-a7580c699a40)
![image](https://github.com/slowtorta/turtlewow-bug-tracker/assets/151180101/ec1ac78c-24a0-43c0-9267-dcf507665a0d)
![image](https://github.com/slowtorta/turtlewow-bug-tracker/assets/151180101/8d2c2e97-225a-424e-8b38-be7aa0976b74)

We do not support addon issues here.
