### ISSUE TITLE
Pet Dragonslayer buff

### ISSUE THREAD

**Issue by Bibbit169** [slowtorta/turtlewow-bug-tracker#6325]
**Please, provide a clear description what the bug is:**

**Steps to reproduce the behavior with as much detail as possible:**

1.When going from place to place my pet loses it dragonslayer buff.
2.Also when it is dismissed and called upon again. 
3. 

**IDs of affected creatures, items, quests or spells with a link to the relevant page:**

NPC: https://database.turtle-wow.org/?npc=
Item: https://database.turtle-wow.org/?item=
Quest: https://database.turtle-wow.org/?quest=
Spell: https://database.turtle-wow.org/?spell=
Object: https://database.turtle-wow.org/?object=

**Expected behavior. Describe how it should work:**

**Comment by twowTurtReynolds** [comment]
Can't replicate.
![image](https://github.com/slowtorta/turtlewow-bug-tracker/assets/151180101/44d79a7c-fbec-46af-aa7f-aeea1796b0ea)
![image](https://github.com/slowtorta/turtlewow-bug-tracker/assets/151180101/4610be35-e363-4659-9ea3-6da8c1bded9a)
![image](https://github.com/slowtorta/turtlewow-bug-tracker/assets/151180101/d56fd120-58ac-4165-ade0-f39b2162689d)
![image](https://github.com/slowtorta/turtlewow-bug-tracker/assets/151180101/3c00c24f-8636-441f-bdc4-476f4328d4ba)
![image](https://github.com/slowtorta/turtlewow-bug-tracker/assets/151180101/f0e1ca74-c054-4bac-8910-131d01dd629d)
