### ISSUE TITLE
People getting teleported on 4 Horsemen during fight

### ISSUE THREAD

**Issue by Platinumcoated** [slowtorta/turtlewow-bug-tracker#6328]
**Please, provide a clear description what the bug is:**
Today during the 4HM fight, 2 of our players mentioned they're getting teleported to the boss positions. This was happening in the second half of the fight, these players were inside the room when they got teleported.

https://outplayed.tv/media/dY3YG1
in this video you can see our priest trying to run to Blaumex to heal, but they keep getting teleported back to Mograine while getting more and more marks

**Comment by twowTurtReynolds** [comment]
This should have been fixed with today's hotfix.

**Comment by vidda88** [comment]
This bug also happened to me during Wednesday's Naxx. https://youtube.com/clip/Ugkx9c2ihfE_tf7JiDrm6AyeSm0Wdl7nGOd6?si=DuT_kdfTK_HWlt9V
