### ISSUE TITLE
The Exalted rep pet from Reventusk Trolls rep cannot be learned

### ISSUE THREAD

**Issue by Toirto** [slowtorta/turtlewow-bug-tracker#633]
Whenver I try to use the item - Amani Eagle - it disappears but does not go into my pet spell book and also writes the text 'Interrupted' in red.

**Steps to reproduce the behavior with as much detail as possible:**

1.Buy the pet from Ho'Jo <Pet Collector>
2. Use it
3. Sadness

**IDs of affected creatures, items, quests or spells with a link to the relevant page:**

NPC: Ho'Jo
Item: Amani Eagle
Quest: -
Spell: Amani Eagle
Object: -
**Expected behavior. Describe how it should work:**
It should go to the spell book of course! Also the vendor Ho'Jo is kind of stuck in a tree and is  hard to notice if you are looking for him.

**Comment by Tinyfin-github** [comment]
Greetings!

The pet can be learned, but it goes into the general tab instead of the companions tab.
