### ISSUE TITLE
Darn - SW boat bug

### ISSUE THREAD

**Issue by scimitar1987** [slowtorta/turtlewow-bug-tracker#6332]
**Please, provide a clear description what the bug is:**

**Steps to reproduce the behavior with as much detail as possible:**

1. Take the boat from Darnassus to Stormwind
2. As soon as Stormwind side is loaded you end up in the water
3. Happened every time for me so far

**IDs of affected creatures, items, quests or spells with a link to the relevant page:**

NPC: https://database.turtle-wow.org/?npc=
Item: https://database.turtle-wow.org/?item=
Quest: https://database.turtle-wow.org/?quest=
Spell: https://database.turtle-wow.org/?spell=
Object: https://database.turtle-wow.org/?object=

**Expected behavior. Describe how it should work:**

**Comment by twowTurtReynolds** [comment]
This happens when your game loads too slow. There's nothing really that can be done from our end. Check for help on improving loading times, moving to SSD...

**Comment by Kangaroux** [comment]
> This happens when your game loads too slow. There's nothing really that can be done from our end. Check for help on improving loading times, moving to SSD...

Spitballing a solution here:

1. When player leaves zone check if they are on a transport, assign transport ID to player
2. When player enters zone check if they have a transport ID, if they are X distance away from transport teleport them to transport
3. Clear transport ID
