### ISSUE TITLE
Margram questgivers are non-interactable.

### ISSUE THREAD

**Issue by AbsoluteApathy** [slowtorta/turtlewow-bug-tracker#6333]
**Please, provide a clear description what the bug is:**

**Steps to reproduce the behavior with as much detail as possible:**

1.  I took the quests from npcs.
2.  Now I can't interact nor with other quests, neither turn in my completed quests.

**IDs of affected creatures, items, quests or spells with a link to the relevant page:**

NPC: https://database.turtle-wow.org/?npc=61040 , https://database.turtle-wow.org/?npc=61041
Item: -
Quest: All quests from the nps
Spell: -
Object: -

**Expected behavior. Describe how it should work:**
I need to turn in and pick up the quests.

**Comment by skytom137** [comment]
You need to go to your Reputation tab, select Magram, and untick "At War". Then you can interact with them.
