### ISSUE TITLE
关于翡翠圣殿附魔图纸公式：永恒梦境碎片的问题

### ISSUE THREAD

**Issue by pklove977** [slowtorta/turtlewow-bug-tracker#6339]
您好，我在1月23日打翡翠圣地副本（ID为410）拿到了永恒梦境碎片的附魔图纸，可是在我学习时提示学习失败，附魔技能里也找不到，而且图纸却消失了，我按照您回复的消息登陆BUG提交，烦请解决下。服务器名称：无尽之海，角色名称：可可西里网红。

**Comment by twowTurtReynolds** [comment]
English only in the bug tracker.
