### ISSUE TITLE
The Emerald Temple enchantment drawing formula: Eternal Dreamstone Shard

### ISSUE THREAD

**Issue by pklove977** [slowtorta/turtlewow-bug-tracker#6340]
Hello, I played the emerald shrine copy (ID is 410) on January 23rd to get the enchantment drawing formula： Eternal Dreamstone  Shard, but when I learned it, it prompted that the learning failed, and I could not find it in the enchantment skills, and the drawing disappeared, I submitted the BUG according to the message you replied, please solve it. Server name:Tel’Abim。Role Name：可可西里网红。
I want to get this skill in enchantment skills.

**Comment by twowTurtReynolds** [comment]
I am unable to replicate. Please contact support.
![image](https://github.com/slowtorta/turtlewow-bug-tracker/assets/151180101/0b3bdb62-a149-4b83-9e7d-eeb3908c106c)

**Comment by pklove977** [comment]
> 我无法复制。请联系支持人员。
hi sir 。
How can I contact support?

**Comment by pklove977** [comment]
How should we handle this problem?
