### ISSUE TITLE
公会仓库页面又被吞掉了

### ISSUE THREAD

**Issue by Menethiltt** [slowtorta/turtlewow-bug-tracker#6342]
公会《爱从零开始》公会仓库第四格1月26日用公会仓库1500G购买的第四个仓库格子1月26日晚重启后看就没有了 包括存在里面的10组特效法力药水 也没有退回金币 仓库的使用记录也没了
每次服务器更新我都会追问 一直不给正面答复 喊等待等待 要么就把我单子打掉
我就当处理不了了不要那1500G和药水了
可是今天2024年2月23日下午18:56开启了公会仓库第5格 服务器炸后回档又被吞掉了 
![1](https://github.com/slowtorta/turtlewow-bug-tracker/assets/158516329/8ecd6977-f15d-4812-8eac-a776132531b8)
![2](https://github.com/slowtorta/turtlewow-bug-tracker/assets/158516329/5240870a-7d95-49bf-a015-859de0cc8164)
包括仓库里的材料]
![3](https://github.com/slowtorta/turtlewow-bug-tracker/assets/158516329/2d8161dc-c09e-4241-b035-d011f8b9152f)
能不能解决

**Comment by twowTurtReynolds** [comment]
English only in the tracker.

**Comment by Menethiltt** [comment]
不能处理吗？

**Comment by Menethiltt** [comment]
不能处理吗？

**Comment by Menethiltt** [comment]
什么意思啊
