### ISSUE TITLE
Seal of Command lands after Judgement

### ISSUE THREAD

**Issue by discer** [slowtorta/turtlewow-bug-tracker#6346]
**Please, provide a clear description what the bug is:**
As seen in the Screenshot below Seal of Command lands after being Judged from being triggered by the Holy Strike above

![SoC bug](https://github.com/slowtorta/turtlewow-bug-tracker/assets/139697479/48678dfd-5369-4bf8-a706-53ac27988871)

**Steps to reproduce the behavior with as much detail as possible:**

1. 
2. 
3. 

**IDs of affected creatures, items, quests or spells with a link to the relevant page:**

Spell: https://database.turtle-wow.org/?spell=20920

**Expected behavior. Describe how it should work:**
Seal of Command Proc should never happen after it has been judged and removed from the paladin

**Comment by twowTurtReynolds** [comment]
This may be a race condition of two things happening at the same time. How far apart are these two events? If there was a  were 300ms gap, that is weird, but if these are within 10ms of eachother, this isn't an issue.

Please provide further proof with this addon: https://github.com/cyaohiri/ChatTimestamps and I will re-open.
