### ISSUE TITLE
No Title for Blood Ring Exalted

### ISSUE THREAD

**Issue by mookysolo** [slowtorta/turtlewow-bug-tracker#6348]
TWow websites states there is a title granted for reaching Blood Ring exalted

https://turtle-wow.org/#/achievement-titles
★ BLOOD RING CHAMPION
Reach Exalted with the Steamwheedle Blood Ring faction.

1. Get BR Exalted
2. No title granted

Is there a title in game for this? GM stated I should open a ticket regarding issue
![BRExalted](https://github.com/slowtorta/turtlewow-bug-tracker/assets/154543714/1056b784-b82f-40fd-9e51-3605335da4c9)

**Comment by twowTurtReynolds** [comment]
Duplicate of https://github.com/slowtorta/turtlewow-bug-tracker/issues/5003
