### ISSUE TITLE
Logistics Task Briefing II and III aren't dropping

### ISSUE THREAD

**Issue by Lichbanez** [slowtorta/turtlewow-bug-tracker#6350]
Hello, I recently opened about 20 followup logistics assignments and I've never seen these two items once now if it were just one I would have thought of a case of back luck but since there is a 34% chance (counting both) to find them there might be a bug. The turn in for these quests is quite expensive so I can't mindlessly test this over and over, I hope you can tell me if everything is working fine.

1. Open multiple Followup Logistics Assignments
2. Keep getting doubles of 4 out of 6 possible briefings

Item: https://database.turtle-wow.org/?item=21379
         https://database.turtle-wow.org/?item=21380

Quest: https://database.turtle-wow.org/?quest=8805
           https://database.turtle-wow.org/?quest=8806

Object: https://database.turtle-wow.org/?item=21386

Opening the container 20 times or so and failing to get a 34% is kind of an anomaly (I never had these troubles with Combat or Tactical ones), I should have seen at least one of the two assuming everything is working as it should.

**Comment by twowTurtReynolds** [comment]
![image](https://github.com/slowtorta/turtlewow-bug-tracker/assets/151180101/395a230e-6e67-407b-96a6-5c2ff0a0ec93)
The very first one I opened.

**Comment by Lichbanez** [comment]
I don't know what to tell you I got 30 cenarion logistics badges and I haven't seen the one you dropped once, I'm glad it's not bugged but perhaps let us choose them instead of being random.

**Comment by twowTurtReynolds** [comment]
https://forum.turtle-wow.org/viewforum.php?f=14
