### ISSUE TITLE
Gold drain

### ISSUE THREAD

**Issue by floriist** [slowtorta/turtlewow-bug-tracker#6358]
**Please, provide a clear description what the bug is:**
the problem is when i put bright dream shards on ah the deposit is so high there is almost not worth sellin em on AH. deposit takes 13g each time. when i put a 20 stack of bright dream shards.  i lost 80G easy now maybe more. first of all its timeconsuming as it is to farm to make money. but this makes me angry. almost not worth anymore. must be somthing wrong since the deposit was way lower.  and it says 2g deposit. but its way more that disappears.  plz help.
**Steps to reproduce the behavior with as much detail as possible:**

1.i put stacks on AH 20 in each stack. 
2. one 20 stack of bright dream shards takes 13g or more in deposit.
3. i have no clue why it does this. 

**IDs of affected creatures, items, quests or spells with a link to the relevant page:**

NPC: https://database.turtle-wow.org/?npc=
Item: https://database.turtle-wow.org/?item=61199
Quest: https://database.turtle-wow.org/?quest=
Spell: https://database.turtle-wow.org/?spell=
Object: https://database.turtle-wow.org/?object=

**Expected behavior. Describe how it should work:**
it should take a deposit on AH ofcourse. but that much. some golds or so sure at highest 2g.  but not more. it have worked fine since i started this character long time ago.  but noticed this issue today.

**Comment by twowTurtReynolds** [comment]
Suggestions belong on https://forum.turtle-wow.org/viewforum.php?f=14

**Comment by floriist** [comment]
this isnt a suggestion ?  i wonder if its broken since it feels like the deposit is to high ?   or should it be like that ?   if so i would like an answer plz
