### ISSUE TITLE
Frayfeather Hippogryph mount using wrong model?

### ISSUE THREAD

**Issue by Lexiebean** [slowtorta/turtlewow-bug-tracker#636]
Current model: https://i.imgur.com/E2rqZra.png

Before 1.16.0 it had an armoured texture: https://i.imgur.com/BbZXcI8.png

I feel like this may have to do with it now using flying animation instead of ground movement animation.

I briefly saw this happen before 1.16.0 when I logged out while riding it. https://www.youtube.com/watch?v=NQCVZXJAa2g  
In the last second you can see the old armoured model.

Ideally I'd like to see the old armoured model while still using the new flying animation.

**Comment by Tinyfin-github** [comment]
Will be fixed on the next restart. Please, submit a ticket and request item restoral once the fix is applied.
