### ISSUE TITLE
Majordomo Executus loot table bug?

### ISSUE THREAD

**Issue by nickdamran** [slowtorta/turtlewow-bug-tracker#6366]
**Please, provide a clear description what the bug is:**

Majordomo executus did not drop an ancient petrified leaf nor an eye of divinity. Only two random epic armor items. Is this common or a bug? 

Raid ID: 1894 
Molten Core - 2/25/2024

Character: Discomposure, 60 Human Priest

**Comment by jameyboor** [comment]
https://github.com/slowtorta/turtlewow-bug-tracker/issues/6361 Will be fixed in 1 day on server update.
