### ISSUE TITLE
In the state of Divine Shield, using Hearthstone gets interrupted.

### ISSUE THREAD

**Issue by QQ511959618** [slowtorta/turtlewow-bug-tracker#6367]
In non-HC, at level 60, while in combat with an enemy, attempting to use Hearthstone under the effect of Divine Shield gets interrupted.

**Steps to reproduce the behavior with as much detail as possible:**

1.Our side uses Divine Shield   （ID：1155）
2.Our side uses Hearthstone （ID：6418）
3. The enemy uses Clutch of Foresight  （ID：7247）
4. Our Hearthstone is interrupted, and the character remains stationary

**IDs of affected creatures, items, quests or spells with a link to the relevant page:**

NPC: https://database.turtle-wow.org/?npc=
Item: https://database.turtle-wow.org/?item=
Quest: https://database.turtle-wow.org/?quest=
Spell: https://database.turtle-wow.org/?spell=
Object: https://database.turtle-wow.org/?object=

**Expected behavior. Describe how it should work:**

**Comment by twowTurtReynolds** [comment]
Related to https://github.com/slowtorta/turtlewow-bug-tracker/issues/3424, added this case there.
