### ISSUE TITLE
Macros

### ISSUE THREAD

**Issue by thuugom** [slowtorta/turtlewow-bug-tracker#637]
**Please, provide a clear description what the bug is:**

**Steps to reproduce the behavior with as much detail as possible:**

1. Make a macro and place in the actionbar, when I log out or switch toons, the macro disappears. I.E., a macro named FTG with /y FEAR THE GRIN!
2. 
3. 

**IDs of affected creatures, items, quests or spells with a link to the relevant page:**

NPC: https://database.turtle-wow.org/?npc=
Item: https://database.turtle-wow.org/?item=
Quest: https://database.turtle-wow.org/?quest=
Spell: https://database.turtle-wow.org/?spell=
Object: https://database.turtle-wow.org/?object=

**Expected behavior. Describe how it should work:**
Shouldn't disappear upon logout or exit from game

**Comment by Tinyfin-github** [comment]
Greetings!

Please contact support on discord for assistance about macros that don't save.

https://discord.com/invite/mBGxmHy
