### ISSUE TITLE
Fey Dreamcatcher Trinket bug

### ISSUE THREAD

**Issue by midoahmadidz** [slowtorta/turtlewow-bug-tracker#6371]
**Fey Dreamcatcher it is a blue trinket level 27  **

**Steps to reproduce the behavior with as much detail as possible:**

1. the items is equipped normally.
2. once it is used no heals and 3 sec cooldown.
3. keeps casting green light like the Hearthstone for ever, without doing anything .
4. the green light keeps even if the trinket is unequipped 
![pic2](https://github.com/slowtorta/turtlewow-bug-tracker/assets/161448052/0a83fece-b7be-453a-a6c8-b22ee613deda)
![pic1](https://github.com/slowtorta/turtlewow-bug-tracker/assets/161448052/d38c92cb-0108-4471-b3b3-b8a4518095b7)

**IDs of affected creatures, items, quests or spells with a link to the relevant page:**

NPC: https://database.turtle-wow.org/?npc=4066
Item: https://database.turtle-wow.org/?item=80830
Spell: use: Heals an ally every 3 seconds  for 12 seconds

**Expected behavior. Describe how it should work:**
it should heal you or an ally ,every 3 seconds for 12 seconds

**Comment by twowTurtReynolds** [comment]
Clear your WDB. It should look like this once you fix your client:

![image](https://github.com/slowtorta/turtlewow-bug-tracker/assets/151180101/bcaa9366-fb3f-4932-8bbc-bbc5c7f48d8a)
