### ISSUE TITLE
Stormwind Barber Issues 

### ISSUE THREAD

**Issue by ShellSeeker** [slowtorta/turtlewow-bug-tracker#6372]
Hello,

I wanted to report a bug regarding the barber in Stormwind.

It looks like the function of sitting on the barber chair and editing your hairstyle is not possible at the moment, as well as you are sitting through the chair itself.

**Steps to reproduce the behavior with as much detail as possible:**

1. Go to the barbershop in Stormwind.
2. Sit on a chair.

Here I'm providing a video on how to replicate the bug - https://streamable.com/qjwp52

**IDs of affected creatures, items, quests or spells with a link to the relevant page:**

Object: https://database.turtle-wow.org/?object=105180

**Expected behavior. Describe how it should work:**

I'm providing a youtube video of how it should work. (the video is filmed by a third-party youtuber on WoWTLK however it should work the same on classic.) - https://www.youtube.com/watch?v=FZf7lPRHA_I

Best Regards, 
Your fellow Trevoman - High Elf
Hardcore (not sure how long I will be alive for my username for turtle is "glavniq")

**Comment by Szwedowski** [comment]
But this is not bug, barber on Tutle WoW only propose to buy hair dye of different color. 
And never worked like in WotLK
