### ISSUE TITLE
骑士上古圣马之魂任务无法完成任务完成没有给任务物品

### ISSUE THREAD

**Issue by crs1992** [slowtorta/turtlewow-bug-tracker#6374]
**Please, provide a clear description what the bug is:**

**Steps to reproduce the behavior with as much detail as possible:**

1.角色是在风暴烈酒的  肾光保佑你
2. 完成任务没有给任务物品奥金马铠导致无法完成后续任务上古圣马之魂任务。
3. 

**IDs of affected creatures, items, quests or spells with a link to the relevant page:**

NPC: https://database.turtle-wow.org/?npc=
Item: https://database.turtle-wow.org/?item=
Quest: https://database.turtle-wow.org/?quest=
Spell: https://database.turtle-wow.org/?spell=
Object: https://database.turtle-wow.org/?object=

**Expected behavior. Describe how it should work:**

**Comment by twowTurtReynolds** [comment]
English only in the tracker please.
