### ISSUE TITLE
Item ID 60752 ( Sentinel's Glaive) Transmogged and Item looks Bugged

### ISSUE THREAD

**Issue by tasipeter3000** [slowtorta/turtlewow-bug-tracker#6375]
The Item 60752is floating off my Back as a nightelf when equiped and isnt attached to my body/back.
When Item 60752 is transmogified on item 19865 it hangs in my shoulder inside me.

Reproduce the first sentence:

1.Be a female nightelf.
2. Equip Item 60752in your mainhand.
3. It should float now on your back.

Reproduce the second sentence:

1.Be a female nightelf.
2. Equip Item  19865 in your mainhand
3. Transmog  19865 into item 60752.
4. Now Trasmoged item 60752 should hang out of your right shoulder and be inside your chest and shoulder.

Female Nightelf Player
Item: https://database.turtle-wow.org/?item=19865
Item: https://database.turtle-wow.org/?item=60752

Transmogged Warblade of the Hakkari should be clean on the middle of the back and not offset or floating with any item. In this case with Sentinels Glaive.

With best Reggard
Peter Taschner (Getjinxed)

**Comment by tasipeter3000** [comment]
![WoWScrnShot_022724_192714](https://github.com/slowtorta/turtlewow-bug-tracker/assets/156001406/f1d40c0e-f5f8-42a3-955a-48fe0456138e)

**Comment by twowTurtReynolds** [comment]
The mountpoint of a transmogged weapon will inherit the base wep, not the visually used wep. This cannot be fixed currently.
