### ISSUE TITLE
 Triskelion of Roving Elements speed bonus doesnt stack with boots minor speed increase bonus

### ISSUE THREAD

**Issue by melg8** [slowtorta/turtlewow-bug-tracker#6376]
**Please, provide a clear description what the bug is:**
 [Triskelion of Roving Elements](https://database.turtle-wow.org/?item=60860) speed bonus doesnt stack with [boots minor speed increase](https://database.turtle-wow.org/?spell=13890) bonus.
 
**Steps to reproduce the behavior with as much detail as possible:**
1. Download and install [MonkeySpeed](https://github.com/for-wow/MonkeySpeed) for speed measurement
2. Start running at normal speed (no speed modifiers)
3. Enter the command /mscalibrate to calibrate the speed.
4. Observe addon showing 100 as we run forward (thanks to Zorg for providing test results!)
![изображение](https://github.com/slowtorta/turtlewow-bug-tracker/assets/16599015/64664e19-f421-40ff-9922-f39071fbe483)
5. Put on any boots with ["Enchant Boots - Minor Speed"](https://database.turtle-wow.org/?spell=13890) on them. Start running forward, observe speed equal to 108: 
![изображение](https://github.com/slowtorta/turtlewow-bug-tracker/assets/16599015/ba6a010c-b284-427d-a1c2-27f5d54be9df)
6. Put on  [Triskelion of Roving Elements](https://database.turtle-wow.org/?item=60860)  into trinket slot. Start running forward, observe speed still equal to 108.
![изображение](https://github.com/slowtorta/turtlewow-bug-tracker/assets/16599015/95504a5b-a68e-4a8b-b73c-bf97302493c8)
7. If you remove  speed boots, you still get 108 speed value.
![изображение](https://github.com/slowtorta/turtlewow-bug-tracker/assets/16599015/676c3060-dbcd-489f-b5b3-9e54c438b723)

**IDs of affected creatures, items, quests or spells with a link to the relevant page:**

Item:  [Triskelion of Roving Elements](https://database.turtle-wow.org/?item=60860) 
Quest: [An Honorary Gelkis](https://database.turtle-wow.org/?quest=40629)
Spell: [Enchant Boots - Minor Speed](https://database.turtle-wow.org/?spell=13890)

## How it should work
1. When both boots and trinket are put on you should get sum of their bonuses, so 116 value.

## Motivation for that change
1. As i saw after openning issue it actually related to #5126, but i think twow is about vanilla + experience. If i remember correctly some time ago + mounted speed bonuses didnt stack in the past, for 2 trinkets, but they do now. Also we got more speed boosts for mounted players - like mithrill spurs vs thorium spurs, i think its time to go to original design of this item, i didnt find any complains of people about this item being too op or somehow bad for community.
2. Also it would be coherent behavior with other speed increasing trinkets, for example - mount speed increase trinkets. If you put on gloves enchants + thorium spurs + carrot trinket + goblin car key trinket - they all stack up and give sum bonus to speed.
3. Even for increase swim speed bonus it works same way, if you put on Azure Slik Belt and Murlock's Flippers which also have + swim speed bonus, this values stack and you swim with speed equal to 100+ both of their bonuses.
4.  Everyone loves speed, it would make this item truly great trinket and balance out current meta around Gelkis vs Magram.
5. Simmilar quest with Magrams provides Dyad of Twitching Elven Ears which is great for stealth users, it would be fair if Gelkis allies also get something usefull - trinket that stacks speed with boots would be realy good for stealth users which would provide additionaly speed for their stealth movement. Giving both questlines usefullness parity.
6. It wouldn't affect pvp or pve balance that much but would really increase value of item and motivation of players to participate in this questline. 
7. Alot of buffs and effects are present in game already which increase movement speed for greater values. Think of [Swiftness of Zanza](https://database.turtle-wow.org/?item=23796) for example. So even with stacked bonus player will have running speed increased less then Zanza provides.
8. This quest item is available for both factions in any given moment, so it doesn't discriminate agains any group of players.
9. Literaly in description of item it says that it does "Minor increase to running and swimming speed" which player with boots enchant just doesnt observe at all. Imagine dissapointment of player who farmed so much reputation, did all quests, choose this trinket and saw its basically not working.

## Additional thought 
It would be great if devs can also check if Dyad of Twitching Elven Ears + stealth detection bonus stacks with all other + stealth detection bonuses, cause if it is not - it should be.

**Comment by ZorgDarkness** [comment]
I am Zorg, and i approve this message

**Comment by twowTurtReynolds** [comment]
Blizzlike prescedent is that player on foot bonuses do not stack, but player mounted bonuses do stack.

Please move this post to the suggestions forum.
