### ISSUE TITLE
小鬼相位变换，但是给队友上火焰之盾小鬼会进入战斗

### ISSUE THREAD

**Issue by fizzyFree** [slowtorta/turtlewow-bug-tracker#6378]
**Please, provide a clear description what the bug is:**

**Steps to reproduce the behavior with as much detail as possible:**

1.小鬼相位变换，但是给队友上火焰之盾小鬼会进入战斗
2. 
3. 

**IDs of affected creatures, items, quests or spells with a link to the relevant page:**

NPC: https://database.turtle-wow.org/?npc=
Item: https://database.turtle-wow.org/?item=
Quest: https://database.turtle-wow.org/?quest=
Spell: https://database.turtle-wow.org/?spell=
Object: https://database.turtle-wow.org/?object=

**Expected behavior. Describe how it should work:**

**Comment by twowTurtReynolds** [comment]
English only in the tracker please.
