### ISSUE TITLE
Chromie's Broken Pocket Watch BUG

### ISSUE THREAD

**Issue by NanaKuka** [slowtorta/turtlewow-bug-tracker#6383]
GM: The item "Chromie's Broken Pocket Watch" displays: Reduces your casting speed by 10%. As the name suggests, it reduces your casting speed by 10%, not increases your casting speed by 10%. After I purchased 1000G, the measured casting speed increased by 10%. Please fix it. If it cannot be fixed, I hope you can compensate me.
Server：霍格
Character name：茜茜

**Comment by twowTurtReynolds** [comment]
This is intended, the equip effect is a detriment.

**Comment by NanaKuka** [comment]
I have suffered losses due to the wrong description, and I hope to be compensated if the error cannot be fixed.ps:1000G.
