### ISSUE TITLE
About M-0L1Y <Weather Tracking Unit> refresh time

### ISSUE THREAD

**Issue by M-0L1y** [slowtorta/turtlewow-bug-tracker#6387]
How many hours is it? A manager replied to me before and said it would take 25 minutes, but I have been waiting for 30 minutes and still haven’t seen it.
I've been waiting for an hour and twenty minutes now
please help me
I am very depressed

**Comment by twowTurtReynolds** [comment]
![image](https://github.com/slowtorta/turtlewow-bug-tracker/assets/151180101/e8ad3a36-0398-45a4-8388-7cfd00a354f5)

Rares are about a 1 day spawn, and this mob is similar.
