### ISSUE TITLE
a must have discovery quest is bugged

### ISSUE THREAD

**Issue by xelitox** [slowtorta/turtlewow-bug-tracker#6389]
**Please, provide a clear description what the bug is:**

**Steps to reproduce the behavior with as much detail as possible:**

1. A Must have discovery
2. Deepoop is my character name
3. The giant banana cannot be looted. 

Im looking at the giant banana but there is no cog wheel or interactive cog appearing. I have tried deleting WDB folder couple of times and restarted. Dropped Quest and repicked. The banana is bugged. 

**IDs of affected creatures, items, quests or spells with a link to the relevant page:**

NPC: https://database.turtle-wow.org/?npc=
Item: https://database.turtle-wow.org/?item=
Quest: https://database.turtle-wow.org/?quest=
Spell: https://database.turtle-wow.org/?spell=
Object: https://database.turtle-wow.org/?object=

**Expected behavior. Describe how it should work:**

**Comment by schanzee** [comment]
Worked when I last did it. Were you in a raidgroup? Quests not tagged as (Raid) in your questlog will not work while your character is in a raidgroup.
