### ISSUE TITLE
Tirisfal Uplands: The Following quests: The Rogue Heights, The Magical Interference, and Stealing Arcane Goods

### ISSUE THREAD

**Issue by pyrami123** [slowtorta/turtlewow-bug-tracker#639]
These quests are labeled under the Barrens Quest Log:
The Rogue Heights
The Magical Interference
Stealing Arcane Goods

Since these quests are located and are given in Tirisfal Glades, they should appear within the quest log of the Tirisfal Glades tab. 

**Expected behavior. Describe how it should work:**

Appear under the "Tirisfal Glades" quest tab; since the quests pertain to that area.

**Comment by cygnus-xr1** [comment]
Can confirm "Rogue Heights" under the Barrens Quest log:

- https://imgur.com/a/rVmIuqm
