### ISSUE TITLE
Spellhaste [Shroud of Haunted Torment]

### ISSUE THREAD

**Issue by Saveurr** [slowtorta/turtlewow-bug-tracker#6391]
**Please, provide a clear description what the bug is:**

**Steps to reproduce the behavior with as much detail as possible:**

----------------
Problem
However both items/combinations are not giving the same haste.

No spellhaste;
-Spell; Redemption - 10 sec cast

Comb 1.
[Shroud of Haunted Torment]
Item should give 2% haste (spell and melee). But looks like its only 1%
- Spell; Redemption - 9.8 sec cast

Comb 2.
[Cape of Eternal Justice] 1% haste and [Medivh's Foresight] 1% = also 2%
- Spell; Redemption - 9.61 sec cast

----------------
Problem
However both items/combinations are not giving the same haste.

-----------------------
Question
Looks like the [Shroud of Haunted Torment] 2% is not really 2% (haste and melee), but only 1%

Can this get a checkup? ^^

**IDs of affected creatures, items, quests or spells with a link to the relevant page:**

NPC: https://database.turtle-wow.org/?npc=
Item: https://database.turtle-wow.org/?item=83465
Quest: https://database.turtle-wow.org/?quest=
Spell: https://database.turtle-wow.org/?spell=
Object: https://database.turtle-wow.org/?object=

**Expected behavior. Describe how it should work:**
 [Shroud of Haunted Torment] 2% is not really 2% (haste and melee), but only 1%

- Needs to be updated?

**Comment by schanzee** [comment]
Can confirm Shroud of Haunted Torment (https://database.turtle-wow.org/?item=83465) gives me the expected 10s/1,02=9,8s casttime (using Punschrulle for the castbar with decimals).
Staff of the Dreamer (https://database.turtle-wow.org/?item=61208) gives me the same when it should only be 10/1,01=9,9s for the 1% haste it provides.
Database shows Haste 1 (https://database.turtle-wow.org/?spell=13679) as value 2 on (which while unintended matches the value observed ingame).
Haste 2 (https://database.turtle-wow.org/?spell=8815) shows value 3 (incorrect both ways) for spellhaste and 2 for melee? 
Very confusing.

**Comment by twowTurtReynolds** [comment]
https://github.com/slowtorta/turtlewow-bug-tracker/issues/4958
