### ISSUE TITLE
乌龟魔兽邮寄物品好友没有收到

### ISSUE THREAD

**Issue by chejinbao** [slowtorta/turtlewow-bug-tracker#6392]
**Please, provide a clear description what the bug is:**

**Steps to reproduce the behavior with as much detail as possible:**

1.服务器：拉文郡，游戏ID：红孩儿闹神州。2024.2.8日，19:00左右，给好友“伊凡、“邮寄了11个奥术水晶和500gold，对方反馈没有收到，请帮忙核实，谢谢THANKS！
2. 
3. 

**IDs of affected creatures, items, quests or spells with a link to the relevant page:**

NPC: https://database.turtle-wow.org/?npc=
Item: https://database.turtle-wow.org/?item=
Quest: https://database.turtle-wow.org/?quest=
Spell: https://database.turtle-wow.org/?spell=
Object: https://database.turtle-wow.org/?object=

**Expected behavior. Describe how it should work:**

**Comment by twowTurtReynolds** [comment]
English only in the tracker.
