### ISSUE TITLE
Vampiric Embrace not working on killing mob by Pain Spike, Mind Blast

### ISSUE THREAD

**Issue by StasyaLyova** [slowtorta/turtlewow-bug-tracker#6394]
**Please, provide a clear description what the bug is:**
Improved Vampiric Embrace not healing and not give mana back for damage of Mind Blast and Pain Spike if they landed at mob with low health. 

**Steps to reproduce the behavior with as much detail as possible:**

1. Put points to Vampiric Touch (2/2)
2. Cast Vampiric Embrace
3. Land last hit by Pain Spike (or Mind Blast)
4. Check logs or look on screen
5. Check it few more times same way

**IDs of affected creatures, items, quests or spells with a link to the relevant page:**

Vampiric Embrace (20% of damage to health): 
https://database.turtle-wow.org/?spell=15286

Vampiric Touch (4% of damage to mana):
https://database.turtle-wow.org/?spell=45558

Pain Spike: 
https://database.turtle-wow.org/?spell=45555

Mind Blast: 
https://database.turtle-wow.org/?spell=10947

**Expected behavior. Describe how it should work:**
As written in description Vampiric Embrace should heal 20% (and 30% in Improved version) of damage and give mana 4% of damage (from Vampiric Touch). 

![IMG_20240229_172606255_HDR-01-01](https://github.com/slowtorta/turtlewow-bug-tracker/assets/153867747/6ad42c30-d4c8-4ac1-94e3-ead6cf7bfaf3)

**Comment by ratkosrb** [comment]
It should be fixed in the next update.
