### ISSUE TITLE
Number of guild members stucked on 868

### ISSUE THREAD

**Issue by PabloLata** [slowtorta/turtlewow-bug-tracker#6395]
Hi, I have a problem with the number of guild members, when I put the option of "Show Offline Members" always show me 868 members, not matters if I invite a new member or if I kick a member, the number doesn´t change, also doesn´t show me all the members, I can´t find a guild member, guess it´s because the guild list just show the first 868 members.

**Comment by jameyboor** [comment]
Client limitation. Won't be fixed.
