### ISSUE TITLE
Configurations of Guild Bank

### ISSUE THREAD

**Issue by PabloLata** [slowtorta/turtlewow-bug-tracker#6397]
Hi, I recently bought the Guild Bank, but now I can´t configure the Withdraws per week, no matters which number I set, the members still can withdraw unlimited items, also when I set the lowest rank to access to the first tab, they can´t, just can the ranks that are 1 lvl over the rank I set.

**Comment by twowTurtReynolds** [comment]
It worked for me. On the guild master, I set these settings:
![image](https://github.com/slowtorta/turtlewow-bug-tracker/assets/151180101/05b72082-4eda-4501-97a6-86f475bb2b38)

And on the officer alt, I removed one item, and the page locked itself:
![image](https://github.com/slowtorta/turtlewow-bug-tracker/assets/151180101/6f0fb525-4e54-4100-90b7-5fb15587d313)
