### ISSUE TITLE
Improved Blessing of Might BUG

### ISSUE THREAD

**Issue by Bresca00** [slowtorta/turtlewow-bug-tracker#6398]
**Please, provide a clear description what the bug is:**
The row 1 paladin talent (improved blessing of might) is not working as intended, e.g.: is not giving the 4% bonus to attack power.
**Steps to reproduce the behavior with as much detail as possible:**

1.it should be easily reproduced just leveling the talent and using blessing of might on a player character
**IDs of affected creatures, items, quests or spells with a link to the relevant page:**
Player
NPC: https://database.turtle-wow.org/?npc=
Item: https://database.turtle-wow.org/?item=
Quest: https://database.turtle-wow.org/?quest=
Spell: https://database.turtle-wow.org/?spell=
Object: https://database.turtle-wow.org/?object=

**Expected behavior. Describe how it should work:**
it should improve the attack power bonus of blessing of might

**Comment by cyaohiri** [comment]
Did you check the spell tooltip (not the buff tooltip) and your character stats in the character screen? Only they matter, not the tooltip of the buff, as that doesn't get updated.

**Comment by Szwedowski** [comment]
The same equip, different talents.
Unarmed attacks with Improved BoM:
![image](https://github.com/slowtorta/turtlewow-bug-tracker/assets/99164611/e1e4b74b-7fb6-40ad-b348-eb8e7a0ec53e)
Unarmed attack without Improved BoM:
![image](https://github.com/slowtorta/turtlewow-bug-tracker/assets/99164611/5fece53a-0c00-4930-8121-81f3e4ad2c50)
