### ISSUE TITLE
Tirsfal Uplands: Steepwater Cliff Graveyard Broken

### ISSUE THREAD

**Issue by pyrami123** [slowtorta/turtlewow-bug-tracker#640]
There is a Graveyard in Steepwater Cliff that isn't functional (located in the far north of Steepwater Cliff.) There are five gravestones and no placards listed; I've interpreted that this is supposed to be a graveyard and not some detail.

I think the designers originally intended a functional Graveyard in Tirisfal Uplands, but the player is sent back to Deathknell when the player dies.

**Comment by nobodyinteresting** [comment]
Vouching for this. Died falling down the eponymous steep cliffs, spawned back in the undead noob zone. Not fun.
