### ISSUE TITLE
Race Night Elf class druid report bug

### ISSUE THREAD

**Issue by Auri558** [slowtorta/turtlewow-bug-tracker#6400]
**Please, provide a clear description what the bug is:**

**Steps to reproduce the behavior with as much detail as possible:**

1.The walking and running animation is bugged as well as the healing of the Druid's arm remains up every now and then, just like when in the form transformation bear cat or travel form the walking is fixed  and it is unplayable
2. and the walk and run animation is incorrect even without a gestalt character
3.  Once you reach a certain level, the druid's walking and running animation starts to get very strange

**IDs of affected creatures, items, quests or spells with a link to the relevant page:**

the attributes are bugged it often shows me intelect op probably I don't have it on and I have strength but I have red minus 
NPC: https://database.turtle-wow.org/?npc=
Item: https://database.turtle-wow.org/?item=
Quest: https://database.turtle-wow.org/?quest=
Spell: https://database.turtle-wow.org/?spell=
Object: https://database.turtle-wow.org/?object=

**Expected behavior. Describe how it should work:**

**Comment by twowTurtReynolds** [comment]
From what I understand. A cast effect failing to disable is often due to poor internet connections with packet loss.

Nobody else has reported these problems, and everything looks fine on my night elf druid on the PTR. I would suggest playing with a fresh client, and a better internet connection.

**Comment by Auri558** [comment]
No, I have a good internet connection. The bug that is from 2004 is the walk and run animation that is bugged

**Comment by twowTurtReynolds** [comment]
Could you show a video of the animation issues? With a fresh client.

**Comment by Auri558** [comment]
If the bug occurs, I can film it, but it's difficult to upload something like that to Github

**Comment by twowTurtReynolds** [comment]
@Auri558 please do not create duplicate threads.

Use the fresh client provided on https://turtle-wow.org/
