### ISSUE TITLE
Arcane Missiles Issue

### ISSUE THREAD

**Issue by Ansciennt** [slowtorta/turtlewow-bug-tracker#6401]
**Please, provide a clear description what the bug is:**
Arcane Missiles spell - Char: Ansciennt

**Steps to reproduce the behavior with as much detail as possible:**

1. Arcane missiles cant be spelled SOMETIMES - OFFTEN, nothing in front of me, no global cd, no Los, but cant spell
2. Game say too: Target isnt in line of sight.
3. 

**IDs of affected creatures, items, quests or spells with a link to the relevant page:**

NPC: https://database.turtle-wow.org/?npc=
Item: https://database.turtle-wow.org/?item=21280
Quest: https://database.turtle-wow.org/?quest=
Spell: https://database.turtle-wow.org/?spell= 25979
Object: https://database.turtle-wow.org/?object=

**Expected behavior. Describe how it should work:**
I rly dont know whats wrong with that spell.

**Comment by Ansciennt** [comment]
my friend ellryn say's that sometimes got the same issue. She's too arcane mage

**Comment by twowTurtReynolds** [comment]
I tested on about 30 mobs and it all worked correctly. If you can explain exactly how to replicate this issue, we can look into it.
