### ISSUE TITLE
Venom bottle quest and another issue with advanced options.

### ISSUE THREAD

**Issue by Qlorforfun** [slowtorta/turtlewow-bug-tracker#6402]
**Please, provide a clear description what the bug is:**
A) I'm a lvl 50 orc female horde player and planned to do the venom bottle "pick up quest" in The Hinterlands zone. Location of it? The troll camp the western area.  but was not able to interact with it. I asked around and looked at the turtle data base for information to double check. In the end, I removed the WDB folder twice. And looked around in diff camps with the the bottle but no such luck. 
B) Advanced options, links arent working for me. Even tho the book mark is "checked" 
**Steps to reproduce the behavior with as much detail as possible:**
Good question? I dont know what caused it, besides stumble upon the issue. Walked over there and didnt work and advanced options didnt seem to work and a friend of mine tried to help me guide me thru it and seems it might be bugged too.  I havent played in few months. Got back and updated things and now I seem to have a bug? Dont know why or what causing it. 
1. 
2. 
3. 

**IDs of affected creatures, items, quests or spells with a link to the relevant page:**

NPC: 
Item: https://database.turtle-wow.org/?item=9321
Quest: https://database.turtle-wow.org/?quest=2933
Spell: 
Object: https://database.turtle-wow.org/?object=142702

**Expected behavior. Describe how it should work:**
A) Be able to interact with it and pick up the quest as a horde player at lvl 50 because the quest is supposed to be able to do it at lvl 40.
B) Advanced option bookmarks do not work and it should be possible.

**Comment by twowTurtReynolds** [comment]
![image](https://github.com/slowtorta/turtlewow-bug-tracker/assets/151180101/ad59b407-39d7-4a5d-9627-726d00ddf5a0)

I'm not sure why you are experiencing this issue. Do you know of other people who also are having trouble?

**Comment by Qlorforfun** [comment]
![image](https://github.com/slowtorta/turtlewow-bug-tracker/assets/161888207/38e69171-5f49-4634-bb60-5a634c65c217)
Yep its very confusing never experienced something like it before, only thing I can think of? maybe theres a pre quest REQ? but I dont know, I done the same route as before? I dont know.

**Comment by twowTurtReynolds** [comment]
Its possible or probably you have already done the quest.  I'm not sure if support will check for you or not.
