### ISSUE TITLE
he never received it

### ISSUE THREAD

**Issue by chejinbao** [slowtorta/turtlewow-bug-tracker#6403]
**Please, provide a clear description what the bug is:**

**Steps to reproduce the behavior with as much detail as possible:**

1.Server:Ravenshire  Account number:chejinbao  Game ID:红孩儿闹神州 Time：2024/3/28 18:00-19：00（maybe 3/29，I can't remember exactly），I sent Arcane crystals and 500 gold coins to my friend，But he never received it,My friend's game ID：伊凡、，Please help me to check whether there is a bug in the email，thanks！
2. 
3. 

**IDs of affected creatures, items, quests or spells with a link to the relevant page:**

NPC: https://database.turtle-wow.org/?npc=
Item: https://database.turtle-wow.org/?item=
Quest: https://database.turtle-wow.org/?quest=
Spell: https://database.turtle-wow.org/?spell=
Object: https://database.turtle-wow.org/?object=

**Expected behavior. Describe how it should work:**

**Comment by twowTurtReynolds** [comment]
Please contact support.
