### ISSUE TITLE
TAQ raiding Ouro boss fighting BUG

### ISSUE THREAD

**Issue by Unicornsolo** [slowtorta/turtlewow-bug-tracker#6405]
Hi，yesterday afternoon（about 3pm 1st March），we were raiding TAQ （ID：28451）while a BUG appeared during Ouro boss fighting，the boss simply disappeared and never showed up even we tried several times to trigger boss fighting.Right now it has been 24 hours and still nothing changed，could you deal with it plz？

**Comment by twowTurtReynolds** [comment]
Please contact Support.
