### ISSUE TITLE
Tirisfal Uplands: Murloc Stuck at the Northeast Gate

### ISSUE THREAD

**Issue by pyrami123** [slowtorta/turtlewow-bug-tracker#641]
Upon entering Tirisfal Uplands from Solliden Farmstead(Tirisfal Glades), players are greeted with a hostile and deadly level 9 Vile Fin Minor Oracle that's capable of shooting lightning bolts from the underground.  The Murloc is located in between the first tree(on the left) and the very end of the second wooden fence(on the right) underneath the ground.

**Comment by Neto-WoW** [comment]
Seems to be fixed!
