### ISSUE TITLE
Solakar Flamewreath Bug - Not Spawning

### ISSUE THREAD

**Issue by gamling-dragonblade** [slowtorta/turtlewow-bug-tracker#6414]
**Please, provide a clear description what the bug is:**
After looting the Father Flame from the pylon inside the rookery, the waves of dragonkin are to spawn and walk on a pre-determined path towards the former pylon after it despawns from looting. After all waves have spawned, Solakar Flamewreath should spawn. However, from my experience Solakar has not spawned due to the following reasons:
1: The activator of the event dies.
2: The group remains out of the Rookery longer than the next wave of dragonkin are meant to spawn after the former wave, causing the event to stop altogether (for some reason - and this seems to be the largest cause of Solakar not spawning).
3: Three or more people die (not including the activator.).
4: Elongated combat in or out of the rookery, but not on the main floor.
(5: 54 runs and no tier 0.5 shoulders for 8 runs of buggy behavior.)
If any of these four things happen, it appears that these are the biggest correlations to the event stopping altogether after several attempts of his failed summoning.

**IDs of affected creatures, items, quests or spells with a link to the relevant page:**

NPC: https://database.turtle-wow.org/?npc=10264
Item: https://database.turtle-wow.org/?item=61693
Quest: https://database.turtle-wow.org/?quest=41011
Object: https://database.turtle-wow.org/?object=175245

**Expected behavior. Describe how it should work:**
"After looting the Father Flame from the pylon inside the rookery, the waves of dragonkin are to spawn and walk on a pre-determined path towards the former pylon after it despawns from looting. After all waves have spawned, Solakar Flamewreath should spawn."

**Comment by ratkosrb** [comment]
I've made some changes to the script. It ought to be fixed after the next update.
