### ISSUE TITLE
Didn't get credit for The Royal Rescue quest in BRD despite keeping Princess alive

### ISSUE THREAD

**Issue by jackbrundage97** [slowtorta/turtlewow-bug-tracker#6415]
**Please, provide a clear description what the bug is:**

**Steps to reproduce the behavior with as much detail as possible:**

1. We killed Emperor Dagran Thaurissan in Blackrock Depths, we left Princess Moria Bronzebeard alive.
2. After killing Thaurissan, Princess became friendly, but we did not get credit for the quest, she is just there, friendly, with a gray question mark. 

**IDs of affected creatures, items, quests or spells with a link to the relevant page:**

NPC: https://database.turtle-wow.org/?npc=8929
Item: https://database.turtle-wow.org/?item=
Quest: https://database.turtle-wow.org/?quest=4003
Spell: https://database.turtle-wow.org/?spell=
Object: https://database.turtle-wow.org/?object=

**Expected behavior. Describe how it should work:**
As far as I know, you get credit for killing Emperor Dagran Thaurissan as long as you keep Princess Moira Bronzebeard alive, then you can turn in the quest to her after she becomes friendly. I could be wrong, I've seen some sites say you can't damage her at all to get credit, but other sources saying it doesn't matter as long as she is kept alive.

**Comment by ratkosrb** [comment]
Could you possibly have been in a raid group?

**Comment by jackbrundage97** [comment]
> Could you possibly have been in a raid group?
