### ISSUE TITLE
Partial and full resists are not applied correctly

### ISSUE THREAD

**Issue by Bubblegumz** [slowtorta/turtlewow-bug-tracker#6416]
**Please, provide a clear description what the bug is:**
Partial resists, Hit cap and full resists are not working properly. Even in some cases where the character has above 60 spell penetration.
7 % melee hit or 3% spell hit. This is just the case for holy damage, which is absurd as in theory a player can have max 0 holy resistance in pvp at level 60 as there is no holy resistance. I can understand that a fictional 24 is added to ensure that people have their 3% spell hit for that purpose. So I can only imagine what other classes are experiencing right now.

This is my first post so please correct me where I'm wrong and what I'm misunderstanding in this situation.

**Steps to reproduce the behavior with as much detail as possible:**
<img width="383" alt="Screenshot_2024-02-24_222850" src="https://github.com/slowtorta/turtlewow-bug-tracker/assets/28448517/bc34578a-2d7c-475b-8ba7-55c36ab5c61a">
<img width="389" alt="Screenshot_2024-02-24_224207" src="https://github.com/slowtorta/turtlewow-bug-tracker/assets/28448517/3040edb8-d44e-477b-8a81-ed4b168fde67">
<img width="383" alt="Screenshot_2024-02-24_232210" src="https://github.com/slowtorta/turtlewow-bug-tracker/assets/28448517/cc70ba5f-58a9-42ac-95cc-774cec66cf33">
<img width="381" alt="Screenshot_2024-02-26_143005" src="https://github.com/slowtorta/turtlewow-bug-tracker/assets/28448517/6a9c6310-9e51-497e-882e-c7a2c66a96cf">
<img width="371" alt="Screenshot_2024-02-27_193150" src="https://github.com/slowtorta/turtlewow-bug-tracker/assets/28448517/a68a3160-83b1-462c-9534-0b2f67c3dbb2">

**Expected behavior. Describe how it should work:**
So here is the deal in regards to partial resists, as of right now I'm mostly healing and I cannot confirm these things firsthand. However I have guildmates who are well overgeared in both pve and pvp cases and they experiencing an absurd amount of partial resists. Things like thunderfury fully or partially resisting more often than it should, mages with over 70 spell penetration in pvp getting double partial resist or full resists against green geared players. The most recent instance that was caught is death coil being fully resisted. It is a binary spell, and as such it can only hit or miss. Neither critical hits nor partial resists are possible. However items like storm gauntlets have a 100% proc chance and are added to your melee attack, so if your melee hit doesn't land ( dodged, parry, miss etc.). It won't be applied. I have never seen it resist, do partial or even miss. It can crit and is not modified by spellpower, only by spellcrit chance. However the target can be immune to the damage type, hence why a lost of paladin are using 2 sets of gloves for those cases.

**Comment by twowTurtReynolds** [comment]
> I can understand that a fictional 24 is added to ensure that people have their 3% spell hit for that purpose.

In Vanilla, mobs have +5 resist every level above you, so bosses will have +15. I believe this was +8 in TBC, therefore the 24 number. Spell hit is an entirely unrelated mechanic.

Please discuss your misunderstandings on our discord with more knowledgeable players, and if they do see a bug here, if they could report it with the correct information that would be appreciated.

**Comment by Bubblegumz** [comment]
Hi, thank you for your swift response. The pictures provided are from a paladin wearing 73 spell penetration. 7 melee hit and 3% spell hit gear. Just for the testing purpose. How is he getting a Holy Strike dodge on a Berserker Owlbeast ( the npc is just one of the examples). Getting the same results in pvp, duels too. Duel example, people did not have any shadow resistance gear.

**Comment by twowTurtReynolds** [comment]
Holy Strike calculates a weapon swing first. Please contact fellow players for further assistance.
