### ISSUE TITLE
issue with loot from boxes and tactical assignment

### ISSUE THREAD

**Issue by Shedar29** [slowtorta/turtlewow-bug-tracker#6417]
Hello,

i've an issue with my character (Shedar). Cannot loot Fashion tokens from Anniversary Gift (https://database.turtle-wow.org/?item=83270) and cannot loot task briefings from Tactical Assignment (https://database.turtle-wow.org/?item=20809 and  https://database.turtle-wow.org/?item=21266) ,

I've cleared WDB folder several times, but it did not help.

Kindly help

**Comment by twowTurtReynolds** [comment]
It is likely that an addon or modification to your game is causing the loot UI function to break. Please try again with a fresh client.
