### ISSUE TITLE
Quest: A People Restored cannot complete

### ISSUE THREAD

**Issue by Janusregno** [slowtorta/turtlewow-bug-tracker#642]
**Please, provide a clear description what the bug is:**
After speaking with Tyrande and picking up the quest A People Restored I returned to Alah'Thalas, speaking to Vereesa gives you a prompt to go to the new Moonwell Location, going there does not trigger any kind of event, there is nobody to speak to, and the quest triggers seem broken in the quest log.
**Steps to reproduce the behavior with as much detail as possible:**

1. Pick up A People Restored from Tyrande.
2. Speak to Vereesa in Alah'Thalas.
3. Go to Golden Dawn Institute where the Moonwell is.

**IDs of affected creatures, items, quests or spells with a link to the relevant page:**

NPC: https://database.turtle-wow.org/?npc=
Item: https://database.turtle-wow.org/?item=
Quest: https://database.turtle-wow.org/?quest=
Spell: https://database.turtle-wow.org/?spell=
Object: https://database.turtle-wow.org/?object=

**Expected behavior. Describe how it should work:**
Some kind of trigger happens and theres a cutscene, or an npc is interactable, or just a trigger happens of us seeing the Moonwell.
![image](https://user-images.githubusercontent.com/76000153/147618803-cc71abf5-aab3-4f54-8f7f-e8d47a51f4f4.png)

**Comment by Tinyfin-github** [comment]
Greetings!

The quest is not fully implemented yet in game.
