### ISSUE TITLE
My character stuck in dalaran area,floating in air,can't use hearthstone,can't autounstuck.

### ISSUE THREAD

**Issue by sahalin999** [slowtorta/turtlewow-bug-tracker#6420]
**Please, provide a clear description what the bug is:**
My character stuck in dalaran area,floating in air,can't use hearthstone,can't autounstuck.
![2024-03-03 (3)](https://github.com/slowtorta/turtlewow-bug-tracker/assets/52418526/80fee4dd-c6be-4f95-b33a-edccc6a18823)

**Steps to reproduce the behavior with as much detail as possible:**

1.
2. 
3. 

**IDs of affected creatures, items, quests or spells with a link to the relevant page:**

NPC: https://database.turtle-wow.org/?npc=
Item: https://database.turtle-wow.org/?item=
Quest: https://database.turtle-wow.org/?quest=
Spell: https://database.turtle-wow.org/?spell=
Object: https://database.turtle-wow.org/?object=

**Expected behavior. Describe how it should work:**

**Comment by twowTurtReynolds** [comment]
Use the website unstuck feature please.
