### ISSUE TITLE
High Elf Male Character Creation Bug

### ISSUE THREAD

**Issue by ironsaitali** [slowtorta/turtlewow-bug-tracker#6421]
on character creation screen you cant pair any type of beard with "pale white hair color" as High Elf Male. (one comes after orange as you slide(click) to right to change hair colors 

1. When you pair that "pale white" with any type of beard and click "create" character it shows previous orange hair/beard color on character screen (also in-game).
2. Only exception you can make "pale white hair color" male highelf is with NO beard option .
3. Color stays orange with short windswept hair(short one after sided front drop hair type)
(rightclick once from orange still orange) wont show white .
4. Colors mentioned comes after black (black --> orange --> pale white) as you swipe right.

**Comment by twowTurtReynolds** [comment]
https://github.com/slowtorta/turtlewow-bug-tracker/issues/6100
