### ISSUE TITLE
Aboriginal Loincloth doesn't hide the underpants on male High Elves when equipped

### ISSUE THREAD

**Issue by EyeOfTheBeast** [slowtorta/turtlewow-bug-tracker#6423]
**Please, provide a clear description what the bug is:**
Aboriginal Loincloth doesn't hide the underpants on male High Elves:
![highelfaboriginal](https://github.com/slowtorta/turtlewow-bug-tracker/assets/142637959/c8005888-0fcd-4107-b5e2-feaac3e597a0)

**Steps to reproduce the behavior with as much detail as possible:**
1. Play a High Elf male character.
2. Uniequip all of your gear.
3. Equip Aboriginal Loincloth and notice how your underpants still show beneath it.

**IDs of affected creatures, items, quests or spells with a link to the relevant page:**
Aboriginal Loincloth item: https://database.turtle-wow.org/?item=14119

**Expected behavior. Describe how it should work:**
It should work like it did in TBC on Blood Elves (same character model as High Elves), which hid the male underpants when equipped:
![image](https://github.com/slowtorta/turtlewow-bug-tracker/assets/142637959/51d58bf8-d175-4897-9639-6e4f09f5f4c2)

And on other races who are male on Turtle WoW, the Aboriginal Loincloth does hide their underpants:
![image](https://github.com/slowtorta/turtlewow-bug-tracker/assets/142637959/873c4a31-db9a-4ae4-ba1a-211e3eabe1da)

**Comment by wmichon237** [comment]
Fixed in the next client update.
