### ISSUE TITLE
Combat bug after grobbulus, reproduced in many guild's runs

### ISSUE THREAD

**Issue by balakethelock** [slowtorta/turtlewow-bug-tracker#6426]
**Please, provide a clear description what the bug is:**
Starting this week, people are getting placed in permanent combat after the grobbulus bug. This persists until the raid wipes (Everybody dies) or everybody logs out simultaneously

**Steps to reproduce the behavior with as much detail as possible:**

1. Progress through naxx, until killing grobbulus (Probably have to wait for him to spawn some poison farts?)
2. kill the boss, find that you are still in combatd
3. 

**IDs of affected creatures, items, quests or spells with a link to the relevant page:**

NPC: https://database.turtle-wow.org/?npc=15931

**Expected behavior. Describe how it should work:**
Shouldn't cause a combat bug

**Comment by jameyboor** [comment]
Fixed next update.
