### ISSUE TITLE
Guild Bank bug

### ISSUE THREAD

**Issue by PabloLata** [slowtorta/turtlewow-bug-tracker#6427]
Hi, I wrote here before for the Gbanks bugs that I have, I bought the Gbank some days ago and since I bought it, it was bug, I can´t set up a limit on the withdraws per week, gonna add screenshots of the problem.
Here is my configuration, Begginers, the lowest rank of the guild, can access to Gbank with 2 withdraws per week.

![image](https://github.com/slowtorta/turtlewow-bug-tracker/assets/93834732/4f909faf-70d6-459c-8e8f-f772c88554b7)

Now gonna log with my alter and show the bug

![image](https://github.com/slowtorta/turtlewow-bug-tracker/assets/93834732/10860875-f48b-4cb0-8299-595c5d295a14)

As you can see, my alt is with the Begginer Rank, so I should access to Gbank with a max of 2 withdraws per week 

![image](https://github.com/slowtorta/turtlewow-bug-tracker/assets/93834732/b5e3ff76-ce05-45b9-beee-fbff084b8b97)

As you can see, I don´t have access to Gbank.

That is the bug, I know that maybe for you could work, but for me it doesn´t, I already tried to give Gmaster to different members of the guild and they try to configure the Gbank, but it still doesn´t work.

Thanks for the attention :3

**Comment by twowTurtReynolds** [comment]
I couldn't reproduce this on https://github.com/slowtorta/turtlewow-bug-tracker/issues/6397 either. Nothing has changed clientside for a while, perhaps a just this week issue only on live? Can you wait until the week ends with the weekly reset this coming tuesday? Reply back and let us know if all is well after that point in time and if the bank doesnt open up to 2 with the reset, then I will have our core devs investigate.
