### ISSUE TITLE
Prince Thunderaan Kiting

### ISSUE THREAD

**Issue by orcytanky** [slowtorta/turtlewow-bug-tracker#6429]
**Please, provide a clear description what the bug is:**

**Steps to reproduce the behavior with as much detail as possible:**

1. We, as Blackrock Clan, wanted to bring some fun to the server by kiting Prince Thunderaan to Orgrimmar. We managed to bring him to edge of tanaris, near the shimmering flats. But we couldnt keep on kiting. Prince turned back.
2.  opened a ticket and game master referred to use bugtracker.
3.  Akalix said that it cuts off edge of the zone, but we managed to pass silithus and ungoro. 
4. this is the video we have recorded. https://www.youtube.com/watch?v=KHtgPn4eyns
5. Do we have chance to kite him to Orgrimmar? 
6. What i know that world bosses chained at 1.7 patch in vanilla(blizz did it) after Lord Kazzak incidents in Stormwind. I think it is not same for Prince Thunderaan since we were able to kite him to North of Gadgetzan.
7. we need to learn if it is possible or not? If it is bug(as game master has written) will it be fixed? Is there any chance kiting him by using waterwalk without zone issue?
8. If developers reply we will be happy. We really want to experience vanilla thing.
9. Will we get banned because of this action?
10. Sry for so many questions. Kind Regards.
**IDs of affected creatures, items, quests or spells with a link to the relevant page:**

NPC: https://database.turtle-wow.org/?npc= https://database.turtle-wow.org/?npc=14435
Item: https://database.turtle-wow.org/?item=
Quest: https://database.turtle-wow.org/?quest= 
Spell: https://database.turtle-wow.org/?spell=
Object: https://database.turtle-wow.org/?object=

**Expected behavior. Describe how it should work:**

**Comment by twowTurtReynolds** [comment]
Unfortunately, we've had to implement measures against world mob kiting to limit tools used by griefers to kill PVE Hardcore players. 

Mobs like Teremus and the Green Dragon trash mobs are leashed, Kazzak style. However, IIRC thunderran doesn't do AOE damage? IIRC He only knocks up players to deal falling damage, which hardcores are immune to anyway.

The issue you are running into has to do with https://github.com/slowtorta/turtlewow-bug-tracker/issues?q=is%3Aopen+is%3Aissue+label%3A%22Continents+Instanciate%22 where bringing mobs over the border between two zones is troublesome. 

If those issues with that feature are addressed allowing you to kite thunderran to Org, we'll take a second look on if it is something we will allow or not.
