### ISSUE TITLE
Issue with character weapon skill

### ISSUE THREAD

**Issue by gedoreundhazet** [slowtorta/turtlewow-bug-tracker#6434]
My character should have a +5 sword skill from the racial trait, as well as the Combat spec +5 "Weapon Expertise". However, in the Character Skill list, it shows only as 305 (+5).

![image](https://github.com/slowtorta/turtlewow-bug-tracker/assets/162136235/16f5f7d9-f05f-405e-951b-34ac1eb426a6)

Or perhaps does TWoW does not have these two effects stack? Or perhaps this is just a visual bug?

**Comment by twowTurtReynolds** [comment]
305 + 5 = 310. Blizzard's UI is awkward but this is how 310 correctly looks.
