### ISSUE TITLE
Rogue Poison will reset the movement of wielding weapons

### ISSUE THREAD

**Issue by 6556004** [slowtorta/turtlewow-bug-tracker#6442]
[2024 — March 6](https://forum.turtle-wow.org/viewtopic.php?t=13319)
Chance on Hit effects, such as rogue poisons or shaman weapon enchants, will no longer cause you to unsheath your weapon and perform a casting animation when they proc.
------------------------------------------------------------------
yeah, very nice.

But now Rogue Poison will reset the weapon wielding action.

**Comment by twowTurtReynolds** [comment]
I'm not sure what you mean? I don't see anything wrong. Please show a video if you can.
