### ISSUE TITLE
Dream's Herald No Nature damage

### ISSUE THREAD

**Issue by Josephienvandermeersch** [slowtorta/turtlewow-bug-tracker#6443]
**Please, provide a clear description what the bug is:**
Dream's Herald Does 58 - 109 Melee White Damagee
+ 3 - 5 Nature Damage.   Yet Logs and Dps do not show any Nature damage being done. Combat text also gives no indication.
**Steps to reproduce the behavior with as much detail as possible:**

1. Hit With Dream Herald on Target Dummy With Addons.

**IDs of affected creatures, items, quests or spells with a link to the relevant page:**

Item: https://database.turtle-wow.org/?item=
https://database.turtle-wow.org/?item=65008

**Expected behavior. Describe how it should work:**
Should give the extra damage as nature damage?
![image](https://github.com/slowtorta/turtlewow-bug-tracker/assets/24510505/0a651614-90cd-4f71-b911-e70fde0c50d9)

**Comment by Josephienvandermeersch** [comment]
The 20 damage you see is from Poison not the Nature dmg from the Melee Swing.

**Comment by twowTurtReynolds** [comment]
This is how this 1.12 mechanic works. The elemental portion effectively penetrates armor, that's all it does.
