### ISSUE TITLE
Uniting the Shattered Amulet quest elites immune to magic damage

### ISSUE THREAD

**Issue by Rafiky92** [slowtorta/turtlewow-bug-tracker#6446]
**Please, provide a clear description what the bug is:**

I would like to do the quest called Uniting the Shattered Amulet in Blasted Lands, but the elites that drop the quest items are immune to magic damage (fire,frost,shadow at least). There is a weapon provided by the previous quest, that should be used at low health of the elites to be able to kill them, after using it, they get a short debuff, but even with that they still immune.

**Steps to reproduce the behavior with as much detail as possible:**

1.Do the prequests, and pick up Uniting the Shattered Amulet quest.
2. Go to Blasted Lands, for example 40,30
3. Try to damage Lady Sevine with any magic spell or ability.

**IDs of affected creatures, items, quests or spells with a link to the relevant page:**

NPC: https://database.turtle-wow.org/?npc=7667
Item: https://database.turtle-wow.org/?item=10698
Quest: https://database.turtle-wow.org/?quest=3627
Spell: https://database.turtle-wow.org/?spell=
Object: https://database.turtle-wow.org/?object=

**Expected behavior. Describe how it should work:**

I should be able to damage elites with spells till low health, when they should be weaked with linked weapon.

**Comment by twowTurtReynolds** [comment]
![image](https://github.com/slowtorta/turtlewow-bug-tracker/assets/151180101/47894eee-1772-4f30-8ca2-9f0bfa92364d)
I'm not sure exactly how this questline works, but I can tell you this NPC is not immune to shadow. Can you show exactly how it should work? And footage of the problem on twow?
