### ISSUE TITLE
Druid - Ferocius Bite (Rank 5) drains ALL energy

### ISSUE THREAD

**Issue by Rytorcen** [slowtorta/turtlewow-bug-tracker#6447]
Greetings, 
if **ferocious bite (rank 5 from book)** is used with any number of combat points, my energy is drained completly. 
No matter how much energy was left, all is gone to zero.
Additionally the omen of clarity proc doesn't matter ether. All energy is gone after using ferocious bite rank 5.

(Alliance, Nightelf, female, 60, Name:Lyri)

**Steps to reproduce the behavior with as much detail as possible:**

1. stack any number of combat points
2. use ferocious bite rank 5
3. see all energy is gone

**IDs of affected creatures, items, quests or spells with a link to the relevant page:**

Item: https://database.turtle-wow.org/?item=24101
Spell: https://database.turtle-wow.org/?spell=31020

**Comment by schanzee** [comment]
https://database.turtle-wow.org/?spell=31018
"and converts each extra point of energy into 2.7 additional damage"
This is the spell description. Having more energy will increase the damage but use all excess energy in the process. It's like a warrior's execute.

**Comment by adrian-treffurth** [comment]
Oh.. Why I didn't read that.
You are right, it's not a bug.
Thank You.
