### ISSUE TITLE
Typo to many zero's on stormwind vaults boe trash drops it should be 0.013% and not 0.0013%

### ISSUE THREAD

**Issue by badmojo74** [slowtorta/turtlewow-bug-tracker#6450]
**Please, provide a clear description what the bug is:**

**Steps to reproduce the behavior with as much detail as possible:**

1.
2. 
3. 

**IDs of affected creatures, items, quests or spells with a link to the relevant page:**

NPC: https://database.turtle-wow.org/?npc=
Item: https://database.turtle-wow.org/?item=
Quest: https://database.turtle-wow.org/?quest=
Spell: https://database.turtle-wow.org/?spell=
Object: https://database.turtle-wow.org/?object=

**Expected behavior. Describe how it should work:**

**Comment by twowTurtReynolds** [comment]
We read the suggestions forum post and this has already been fixed, ready for next week's patch.

> NPCs Maddened Vault Guard, Black Blood of the Demented, Soulless Husk, Grellkin Sorcerer, Grellkin Scorcher, Manacrazed Grell, Wicked Skitterer: Drop chance of items Arcanic Bracers, Defender's Glaive, Grimoire of Grells, Helmet of the Elite Guard, Leggings of the Elite Guard, Magus Blade, Shadow Silk Cloak, Sharpened Iron Bar has been increased to 0.01%
