### ISSUE TITLE
Using Frostwolf Insignia Rank 6 sent me flying

### ISSUE THREAD

**Issue by 3m2xx** [slowtorta/turtlewow-bug-tracker#6452]
**Please, provide a clear description what the bug is:** I used Frostwolf Insignia Rank 6  just outside of Stonehearth Bunker in order to teleport back to base. I was reorganizing my hotkeys as the teleport took effect, and then my character began flying/falling across the battlefield from Frostwolf Keep all the way back to Stonehearth bunker, landing me at my point of origin.

**Steps to reproduce the behavior with as much detail as possible:**

1. Use Frostwolf Insignia Rank 6
2. (Possibly?) move things around on your character's ActionBar
3.  Get lucky. 
Sorry that I don't have more information. Part of me wonders if a bowman spawned and put me in combat the moment the trinket's cast finished, but I can't know for certain.
 

**IDs of affected creatures, items, quests or spells with a link to the relevant page:**

Item: https://database.turtle-wow.org/?item=17909

**Expected behavior. Describe how it should work:** When using Frostwolf Insignia Rank 6, I should teleport to Frostwolf Keep and then *not* fly across the world to land back at Stonehearth Bunker.

**Comment by twowTurtReynolds** [comment]
If you can try to reproduce this, and provide the footage of this issue in action, we can take a look.
