### ISSUE TITLE
Rommath untargetable

### ISSUE THREAD

**Issue by Xerathi1** [slowtorta/turtlewow-bug-tracker#6453]
**Please, provide a clear description what the bug is:**
Quest Rommath, the Traitor is bugged can't target Rommath to talk to him
**Steps to reproduce the behavior with as much detail as possible:**

1. Got the quest
2. Used the teleportation device to get to him( the device had the option to teleport ilustrated with a ? at first)
3. Rommath is there but is untargetable
4. Gm tried to reset him but still not works
5. People say he was fine a day before
6. 
7. 

**IDs of affected creatures, items, quests or spells with a link to the relevant page:**

NPC: https://database.turtle-wow.org/?npc=
Item: https://database.turtle-wow.org/?item=
Quest: https://database.turtle-wow.org/?quest=
Spell: https://database.turtle-wow.org/?spell=
Object: https://database.turtle-wow.org/?object=

**Expected behavior. Describe how it should work:**

**Comment by twowTurtReynolds** [comment]
https://github.com/slowtorta/turtlewow-bug-tracker/issues/5831
