### ISSUE TITLE
垃圾收集者物品找回BUG

### ISSUE THREAD

**Issue by itstwelve** [slowtorta/turtlewow-bug-tracker#6454]
紫色T2.5肩膀，误操作卖给NPC，游戏内联系GM，回复让去：棘齿城垃圾收集者找回，来到棘齿城和npc对话，提示："You do not have any items that can be restored."，误操作时间是当天，2024年3月7日13点-15:40之间，装备为紫色T2.5，虽有有少量（不超过20）垃圾物品卖出。再次联系游戏内GM，让我反馈bug，理论上来讲装备会出现在垃圾回收者列表，同时其他游戏玩家也反映装备找回功能有bug

BUG重现操作步骤：
1.召唤修理机器人，出售紫色物品；
2. 与棘齿城垃圾收集者对话，期望找回物品；
3. 满足找回物品条件，但是NPC提醒物品恢复列表为空；

**Comment by melg8** [comment]
Repeated in #6456
