### ISSUE TITLE
Brute force agent

### ISSUE THREAD

**Issue by chiyuv** [slowtorta/turtlewow-bug-tracker#6455]
Paladins do not increase their stats after using a brute force potion

**Comment by twowTurtReynolds** [comment]
Works fine.

![image](https://github.com/slowtorta/turtlewow-bug-tracker/assets/151180101/cd630b25-35df-410c-88c4-4c927c173bec)
![image](https://github.com/slowtorta/turtlewow-bug-tracker/assets/151180101/cbb32662-cebe-4b30-a913-b1c52bcc9e71)

Keep in mind that brute force doesn't stack with a lot of other buffs.
