### ISSUE TITLE
Random Water zone in Anasterian Park

### ISSUE THREAD

**Issue by SPQR-Phoenix** [slowtorta/turtlewow-bug-tracker#6457]
Simply an area where one seems to be marked as underwater whilst clearly not being.
1. Clearest position I could find to help locate it.
![Screenshot 2024-03-07 231849](https://github.com/slowtorta/turtlewow-bug-tracker/assets/60262097/da4bab5a-6f6c-47ed-832a-0fef28346981)

**Comment by twowTurtReynolds** [comment]
Please read the pins. https://github.com/slowtorta/turtlewow-bug-tracker/issues/5811
