### ISSUE TITLE
shaman totems are affected by LOS

### ISSUE THREAD

**Issue by balakethelock** [slowtorta/turtlewow-bug-tracker#6459]
**Please, provide a clear description what the bug is:**
Pulsating shaman totems (poison/disease/tremor totems & imbue weapon totems) can't affect allies through LOS.

**Steps to reproduce the behavior with as much detail as possible:**

1. Log in with a shaman and another character
2. Place a windfury totem by the shaman
3. have the other character stand hidden from the totem by an object
4. See that the totem can't hit the character to imbue its weapon

**IDs of affected creatures, items, quests or spells with a link to the relevant page:**

Spell: Probably core? Not sure

**Expected behavior. Describe how it should work:**
![image](https://github.com/slowtorta/turtlewow-bug-tracker/assets/111737968/5df47e2a-1b88-4b09-864b-779c6c607d14)
https://discord.com/channels/260297137554849794/539537300728840194/695193930471440434
Classic says windfury and all (friendly?) totems can hit through LOS

**Comment by twowTurtReynolds** [comment]
https://github.com/slowtorta/turtlewow-bug-tracker/issues/3656
