### ISSUE TITLE
The Boran Family (given by Arnold Boran of Lapidis Isle) has incorrect quest description for what the quest objectives are.

### ISSUE THREAD

**Issue by Zhohan** [slowtorta/turtlewow-bug-tracker#646]
The quest objectives involve delivering letters, but the description asks the player to travel to Southsea Sandbar to get a rum recipe from 'Moonshine Marty'.

**Comment by Mikik3jr** [comment]
[The Boran Family](https://database.turtle-wow.org/?quest=40141) has the same description as [Southsea Reserve](https://database.turtle-wow.org/?quest=40148)

The Boran Family:
![image](https://user-images.githubusercontent.com/43505031/152226883-e3ccf3a5-54a5-4102-b73e-a6e6451e2465.png)

Southsea Reserve
![image](https://user-images.githubusercontent.com/43505031/152226927-ac5d83c4-9baa-432c-9d98-835f74092368.png)
