### ISSUE TITLE
Argent Dawn Commissions

### ISSUE THREAD

**Issue by Shadowsong777J** [slowtorta/turtlewow-bug-tracker#6463]
**Please, provide a clear description what the bug is:**

**Steps to reproduce the behavior with as much detail as possible:**

1. Speak to Dispatch Commander Metz at Light's Hope Chapel in the Eastern Plaguelands.
2. Accept his quest for Craftsman's Writ.
3. Click complete quest. 
4. Error message: "The item was not found.
5. Cannot complete quest.

**IDs of affected creatures, items, quests or spells with a link to the relevant page:**

NPC: https://database.turtle-wow.org/?npc=DispatchCommanderMetz
Item: https://database.turtle-wow.org/?item=SealedCraftsman'sWrit
Quest: https://database.turtle-wow.org/?quest=Craftsman's Writ
Spell: https://database.turtle-wow.org/?spell=CompleteQuest
Object: https://database.turtle-wow.org/?object=

**Expected behavior. Describe how it should work:**
This should give me an item called "Sealed Craftsman's Writ".

**Comment by twowTurtReynolds** [comment]
https://github.com/slowtorta/turtlewow-bug-tracker/issues/5837
