### ISSUE TITLE
Engineering trainer teaches you both Apprentice and Journeyman ability at same time at relearn

### ISSUE THREAD

**Issue by melg8** [slowtorta/turtlewow-bug-tracker#6467]
**Please, provide a clear description what the bug is:**
Engineering trainer [Nogg](https://database.turtle-wow.org/?npc=3412) is out of his mind! When you try to learn from him secondary proffesion he teaches both Apprentice and Journeman skill into you instead of just Apprentice.
It looks like this:
![изображение](https://github.com/slowtorta/turtlewow-bug-tracker/assets/16599015/3ac32dbf-f500-43a1-a8ff-c38f95c01943)

But after that you still have only 0-75 skill available, and he doesnt teach Journeyman again. So it is softlocked after that. I was able to overcome this only with gm help, which also asked me to open this ticket.

Probably true for all professions, related to same source of problem as in:
- #4262 
- #4168
- #3902
- #1091

**Steps to reproduce the behavior with as much detail as possible:**
1. Learn Engineering in 2021 till you can make iron grenades.
2. Unlearn it in 2021, learn mining instead.
3. Unlearn Mining in 2024.
4. Try to talk to Nogg and ask him to teach you Apprentice engineering.
5. Observe issue as on screenshot.

**IDs of affected creatures, items, quests or spells with a link to the relevant page:**

NPC: [Nogg](https://database.turtle-wow.org/?npc=3412)

**Expected behavior. Describe how it should work:**
Should only learn Apprentice part.

**Comment by twowTurtReynolds** [comment]
![image](https://github.com/slowtorta/turtlewow-bug-tracker/assets/151180101/a1f4de69-abd3-4562-a833-5b61d2ea6722)
![image](https://github.com/slowtorta/turtlewow-bug-tracker/assets/151180101/d2568933-1b4f-4b64-ad0f-d53c646b29ba)
I can't replicate. Please contact support to address your character specifically.

**Comment by twowTurtReynolds** [comment]
Ah I did miss the part about it being a re-learn. But no, I can't replicate this still.
![image](https://github.com/slowtorta/turtlewow-bug-tracker/assets/151180101/75c51d28-1663-4549-9f61-0dcbbd22f4d0)
![image](https://github.com/slowtorta/turtlewow-bug-tracker/assets/151180101/15c1912f-6a3e-4fba-8b9a-716cbefb256c)
![image](https://github.com/slowtorta/turtlewow-bug-tracker/assets/151180101/1d139823-5841-4576-aeb2-38a4eb6cb030)
![image](https://github.com/slowtorta/turtlewow-bug-tracker/assets/151180101/ef425a07-0b7e-4013-9806-05b1a5fda3ef)

It looks fixed for the other issue as well.

In your case, please contact support. It may be something that affects only old characters now.
