### ISSUE TITLE
Unable to dismount if mounting up after reaching the buff limit cap

### ISSUE THREAD

**Issue by EyeOfTheBeast** [slowtorta/turtlewow-bug-tracker#6468]
**Please, provide a clear description what the bug is:**
You can be unable to dismount if mounting up after reaching buff limit cap. You may have to intentionally die in order to get dismounted.

Video of the bug here: https://www.youtube.com/live/fVPF_JPKuyw?si=qpjj45fSTeWAHdch&t=3345 (at 55:45 timestamp)

**Steps to reproduce the behavior with as much detail as possible:**
1. Reach the buff cap.
2. Mount up.
3. You won't be able to dismount.

**Expected behavior. Describe how it should work:**
You should be able to dismount if mounting up after reaching the buff limit cap.

**Comment by ratkosrb** [comment]
Should be fixed in the next update.
