### ISSUE TITLE
Devotion Aura buff not displaying proper amount of armor

### ISSUE THREAD

**Issue by AMuffinLink** [slowtorta/turtlewow-bug-tracker#6469]
**Please, provide a clear description what the bug is:**
Hello, I found this bug on my character AMuffinLink. If you take 5/5 Improved Devotion Aura, the buff you get from Devotion Aura will read the base armor given (275) and not the modified armor given (343). When you check your armor stat it will be correct but the buff wouldn't in your buff list. I will include screenshots to better illustrate.
**Steps to reproduce the behavior with as much detail as possible:**

1.Get 5/5 Improved Devotion Aura
2. Cast Devotion Aura
3. Hover your mouse over the Devotion Aura buff

**IDs of affected creatures, items, quests or spells with a link to the relevant page:**

NPC: N/A
Item: N/A
Quest: N/A
Spell: N/A (Can't find it on the database)
Object: N/A

**Expected behavior. Describe how it should work:**
The buff should read 343 armor not 275 armor.

![image](https://github.com/slowtorta/turtlewow-bug-tracker/assets/160769557/1992a335-d583-4bcf-b7d2-34bf6f99c719)
![image](https://github.com/slowtorta/turtlewow-bug-tracker/assets/160769557/bf62ad47-2cd1-45d9-a042-eafe35359f15)
![image](https://github.com/slowtorta/turtlewow-bug-tracker/assets/160769557/0537f888-495b-43df-aefc-2aeb38276adb)
![image](https://github.com/slowtorta/turtlewow-bug-tracker/assets/160769557/a4954217-87bf-4962-ac9e-562f94620e0a)

**Comment by Muigin** [comment]
This is not a bug.  It is a limitation of the vanilla client.  Buff tooltips do not reflect talents or other improvements, only your spellbook tooltip will reflect the correct value.

Working as intended.

**Comment by AMuffinLink** [comment]
Alright thank you
    On Saturday, March 9, 2024 at 03:41:02 AM EST, Muigin ***@***.***> wrote:  
 
 


This is not a bug. It is a limitation of the vanilla client. Buff tooltips do not reflect talents or other improvements, only your spellbook tooltip will reflect the correct value.

Working as intended.
