### ISSUE TITLE
Dwarf/Gnome Glyph Master not offering Slow/Steady

### ISSUE THREAD

**Issue by Vikkyne** [slowtorta/turtlewow-bug-tracker#647]
**Please, provide a clear description what the bug is:**
Unlike the other glyph masters, the glyph master in Coldridge Valley (dwarves/gnomes) does not offer a change to start the Slow & Steady challenge (nor the Exhaustion challenge, for that matter).

Note that I have not attacked anything and I am still level 1 (only collected a couple quests)

1. Create dwarf or gnome character
2.  Speak with glyph master - who only offers scrolls, but NOT the challenges verbally

**Expected behavior. Describe how it should work:**
The glyph master should, along with glyphs to purchase, offer the Slow/Steady challenge as well as the Exhaustion challenge

**Comment by Tinyfin-github** [comment]
Greetings! You now start the  Slow&Steady and Exhaust challenge by buying the Glyph of the Turtle and Glyph of Exhaust and right clicking it to consume them. A spell will show in your spell book after you start the challenge successfully.


![WoW_jqpGS3i5fq](https://user-images.githubusercontent.com/83077166/147810033-9b0440dc-582d-48a4-b2a4-291a48934381.jpg)
