### ISSUE TITLE
Dragon fly bag

### ISSUE THREAD

**Issue by Shockrus** [slowtorta/turtlewow-bug-tracker#6471]
**Please, provide a clear description what the bug is:**

Levitation on horseback, levitation on foot. It does not subside after teleportation. It does NOT subside after death. Also valid on BG

**Steps to reproduce the behavior with as much detail as possible:**

1. Used the Time-Worn Rune and teleported
2. Ran up to the NPC dragon Alormion
3. Talked to him
4. Summoned the proposed dragon
5. Flew to the side Gadgetzan
6. The transport stopped working and I began to fall to the bottom
7. Called the sled horse of the dead
8. After the calling, the horse began to run with the effect of levitation.
9. The effect did not disappear after death, and also acted on bg.

**IDs of affected creatures, items, quests or spells with a link to the relevant page:**

NPC: https://database.turtle-wow.org/?npc=65018
Item: https://database.turtle-wow.org/?item=61000
Quest: https://database.turtle-wow.org/?quest=
Spell: https://database.turtle-wow.org/?spell=
Object: https://database.turtle-wow.org/?object=14558

**Expected behavior. Describe how it should work:**
Levitation should disappear after falling from the dragon.

**Comment by ratkosrb** [comment]
Not sure what circumstances can lead to the flying flags remaining on the player after aura removal, but I'll add some extra checks to try and prevent it.

**Comment by Shockrus** [comment]
I have a video where I experiment with this bug in one of the locations. I jump into a cliff on a horse, but it flies as if on a feather. And he gets damage like from a normal fall.
[https://drive.google.com/file/d/1CNygG4CbNbhOxHnq2JFUI7zirG5pcYZn/view?usp=drive_link]
