### ISSUE TITLE
Consumes disappearing after disconnect

### ISSUE THREAD

**Issue by Afraido** [slowtorta/turtlewow-bug-tracker#6473]
If you get disconnected in dungeon or raid and die during the disconnection your consumes will disappear. Not big bug but huge "f*ck you" if you get DC lol

**Comment by ConcernedTurtler** [comment]
happened to me during 4hm on Friday.

**Comment by twowTurtReynolds** [comment]
![image](https://github.com/slowtorta/turtlewow-bug-tracker/assets/151180101/5a91a150-2ee9-4088-a1f6-32a2dd169aef)

And then I pulled my internet plug, waited a bit, killed the process, and I reload the game, seems to work fine: 
![image](https://github.com/slowtorta/turtlewow-bug-tracker/assets/151180101/c66766d3-1c96-420e-b557-674dc586e1b4)

In your cases, it could have been a small rollback from a server crash (not a disconnect), or something else. We'll need more info, preferably footage, about this to properly replicate what is probably not a DC issue.
