### ISSUE TITLE
Twilight Base Camp duke windstone spawns are stuck.

### ISSUE THREAD

**Issue by Kharkov72** [slowtorta/turtlewow-bug-tracker#6477]
At the Twilight Base Camp (The one closest outside town), the duke windstone dukes get spawned kinda inside the crystal holder, and cannot leave the platform they spawned on. This is most annoying with the wind/water dukes that knock you back since you either need to have someone taunt off, or they evade heal.
![bug 1](https://github.com/slowtorta/turtlewow-bug-tracker/assets/25846834/db08e621-15b0-49f6-badc-1112a74378da)
![bug 2](https://github.com/slowtorta/turtlewow-bug-tracker/assets/25846834/7097f2d4-0b2d-4f5b-9be5-ac89f05eb96a)

**Comment by twowTurtReynolds** [comment]
![image](https://github.com/slowtorta/turtlewow-bug-tracker/assets/151180101/be14ac4f-c22f-4e6a-80d2-6aa3383c83a0)
