### ISSUE TITLE
Picnic Basket does not work

### ISSUE THREAD

**Issue by blargsnarf** [slowtorta/turtlewow-bug-tracker#648]
**Please, provide a clear description what the bug is:**
Picnic Basket used to summon a cute picnic set, but now has the thumbnail "Reduce damage your summoned demon takes from area of effect attacks by an additional 50%".

**Steps to reproduce the behavior with as much detail as possible:**

1. Have the Picnic Basket.
2. Try to use it.

**IDs of affected creatures, items, quests or spells with a link to the relevant page:**

Unfortunately I can't link any DB entries as DB is down. Picnic Basket is a reward from a custon Tanaris beach quest.

**Expected behavior. Describe how it should work:**
Picnic Basket should summon a cute picnic set on use. I think it had a 1hr cooldown.

**Comment by shagu** [comment]
According to the guild chat, it looks like Hunters and Warlocks can still use it (as they have a pet).

Here's a screenshot of the tooltip right now:
![image](https://user-images.githubusercontent.com/11586807/147823295-740b7eac-bda1-484e-bd69-c2bf3e9a20be.png)

**Comment by shagu** [comment]
Picnic Basket seems to be broken again. 
Clicking it triggers a cooldown, but does not do anything.
