### ISSUE TITLE
Unable to use [Barov Peasant Caller] in Bloodring

### ISSUE THREAD

**Issue by Robin11th** [slowtorta/turtlewow-bug-tracker#6481]
**Please, provide a clear description what the bug is:**
When I use the item [Barov Peasant Caller] it gives a message: can only use in battlegrounds. I see many other people use [Barov Peasant Caller] in bloodring.

**Steps to reproduce the behaviour with as much detail as possible:**

1. I click on [Barov Peasant Caller] to trigger it.
2. Message shows up in the screen: can only use in battlegrounds
3. Nothing else happens 

**IDs of affected creatures, items, quests or spells with a link to the relevant page:**

NPC: https://database.turtle-wow.org/?npc=
Item: https://database.turtle-wow.org/?item=14023
Quest: https://database.turtle-wow.org/?quest=
Spell: https://database.turtle-wow.org/?spell=18308
Object: https://database.turtle-wow.org/?object=

**Expected behavior. Describe how it should work:**
Barov peasants summon when trinket is activated.

![image](https://github.com/slowtorta/turtlewow-bug-tracker/assets/147619315/dc85039c-e9d9-44c1-bfa9-ea2680f4b74f)

**Comment by ratkosrb** [comment]
It's not a bug that you can't use it. There is specifically a check on purpose in the code to disable it in arena. This is 100% intentional. I don't see how you could have seen someone else use it when its in fact disabled.

**Comment by Robin11th** [comment]
Ok I've seen at least 5 alliance players use it. I'll screenshot it next time I see it.

**Comment by twowTurtReynolds** [comment]
@ratkosrb turns out there's 2 different barov items? One for horde, one for alliance.

![image](https://github.com/slowtorta/turtlewow-bug-tracker/assets/151180101/7e0bd687-8f99-4583-ad30-899c75c3e3aa)

One of them does indeed work:
![image](https://github.com/slowtorta/turtlewow-bug-tracker/assets/151180101/b12a89ef-54b3-4358-969f-2f059a0c9aa4)

Both should be disabled.

**Comment by ratkosrb** [comment]
It will be disabled in the next update.
