### ISSUE TITLE
Journeyman mining bugged

### ISSUE THREAD

**Issue by Krontprikker** [slowtorta/turtlewow-bug-tracker#6483]
![image](https://github.com/slowtorta/turtlewow-bug-tracker/assets/162956183/6138cb70-eec0-4706-81a6-f5e3d1c71be5)
![image](https://github.com/slowtorta/turtlewow-bug-tracker/assets/162956183/1af268fd-5dfb-41bf-ae73-35047df9fcde)

Description:  The error is that I reached 70 in mining and I can not continue, since the ogrimmar instructor does not sell me the skill, investigating a little more I realized that I had already bought the skill but the level 70 limit is maintained.

Steps:  I upgraded my mining level to around level 220 then deleted the profession to herbalism and switched back to mining.

I have not been able to find the identifier in the miner skills database.

Expected results: the normal thing is to just buy the skill and the limits go to 150 as normal
![image](https://github.com/slowtorta/turtlewow-bug-tracker/assets/162956183/141a705f-bd0f-4d2b-9915-8fad4eb0f8f6)

**Comment by Krontprikker** [comment]
![image](https://github.com/slowtorta/turtlewow-bug-tracker/assets/162956183/115860c1-2c82-46d5-9f0f-76d502b6c4d8)

**Comment by ratkosrb** [comment]
You should try dropping Mining again and relearning it.

**Comment by twowTurtReynolds** [comment]
![image](https://github.com/slowtorta/turtlewow-bug-tracker/assets/151180101/4313a3b6-a6fa-41ba-b28d-8cc7ce8a1585)
![image](https://github.com/slowtorta/turtlewow-bug-tracker/assets/151180101/ff6ff749-c98d-438a-8191-e3074fb9488d)
All seems to work fine. Try drop/relearing it or contact support.

**Comment by Krontprikker** [comment]
I discovered what was the bug, somehow my character had learned mining twice, I left the profession and realized that I was still a miner but at level 1, I had to leave it twice to be able to learn it without any errors.
