### ISSUE TITLE
gillijim's isle mobs

### ISSUE THREAD

**Issue by kyoukowet** [slowtorta/turtlewow-bug-tracker#6484]
**Please, provide a clear description what the bug is:**
gillijim's isle mobs will reset after being drug a short distance
**Steps to reproduce the behavior with as much detail as possible:**

1.aggro a mob on gillijim's isle
2. attacking or not, drag it away
3. 

**IDs of affected creatures, items, quests or spells with a link to the relevant page:**
most npc's ive encountered on gillijim's isle
NPC: https://database.turtle-wow.org/?npc=
Item: https://database.turtle-wow.org/?item=
Quest: https://database.turtle-wow.org/?quest=
Spell: https://database.turtle-wow.org/?spell=
Object: https://database.turtle-wow.org/?object=

**Expected behavior. Describe how it should work:**

**Comment by ratkosrb** [comment]
Should be fixed in the next update.
