### ISSUE TITLE
Set Bonus after Transmog not working anymore

### ISSUE THREAD

**Issue by Josephienvandermeersch** [slowtorta/turtlewow-bug-tracker#6485]
**Please, provide a clear description what the bug is:**
Ive Transmogged my T2 Set and my 5 Bonus is not working anymore

![image](https://github.com/slowtorta/turtlewow-bug-tracker/assets/24510505/909649f7-3265-4126-8be9-d50f913c6030)
This picture shows my Healing with 5 Pieces on.

This picture shows my healing with 4 Pieces on 
![image](https://github.com/slowtorta/turtlewow-bug-tracker/assets/24510505/95777e11-8b25-421c-b3e6-58a136112736)

And my Gloves off in my Bags

If i eguip the gloves back i only get 45+ from Enchant and Gear but not the Bonus.

**Comment by twowTurtReynolds** [comment]
Visual bug, the bonus still works.
