### ISSUE TITLE
Jaedenar Adept zero distance blink + no delay

### ISSUE THREAD

**Issue by melg8** [slowtorta/turtlewow-bug-tracker#6487]
**Please, provide a clear description what the bug is:**
After being distracted when Jaedenar Adept uses blink ability they stay in same position after blink as they were before blink.

**Steps to reproduce the behavior with as much detail as possible:**
1. As rogue throw distract such that Jaedenar Adept is affected by it, but yet not aggroed by you.
2. Go close enough so Jaedenar Adept aggroes on you, start melee range attacks
3. Kick his first fireball which provokes blink
4. Or just wait for first spell to be casted, while still attacking Jaedenar Adept with melee attacks
5. Observe Jaedenar Adept blink to same place it was before.

Video of such thing happening:
[ ![video](https://github.com/slowtorta/turtlewow-bug-tracker/assets/16599015/437871a9-65ae-4ecb-a8df-edc772978871)](https://www.youtube.com/watch?v=bZ7qf7L8-Y0)

No Jaedenar Adept were harmed while filming that video.

**IDs of affected creatures, items, quests or spells with a link to the relevant page:**
NPC: [Jaedenar Adept](https://database.turtle-wow.org/?npc=7115)
Spell: [Blink](https://database.turtle-wow.org/?spell=14514), [Distract](https://database.turtle-wow.org/?spell=1725)

**Expected behavior. Describe how it should work:**
As per [spell](https://database.turtle-wow.org/?spell=14514) tooltip Jaedenar Adept should blink and appear in 20 yards from his initial position. Even after being distracted.

**Comment by twowTurtReynolds** [comment]
It seems distract and kick are completely unrelated to these mobs using blink strangely.

On the PTR, I did see them use it right inbetween two consecurtive fireball casts, and also 0 distance, and there is no delay on the 2nd fireball.

On Vmangos, when they use it right after the first fireball, they often end up behind you, and also don't cast until 2 seconds later.

**Comment by ratkosrb** [comment]
It was because of the inclination of the terrain. There was a check to prevent mobs from blinking if the Z difference between the old and new position is greater than 5 yards. On this slope you were fighting the mobs, 20 yards ahead leads to a vertical distance of more than 5 yards, and thus the Blink didn't do anything. I've removed this limit. Try again next week.
