### ISSUE TITLE
Jaedenar Adept doesn't blink out of stunlock

### ISSUE THREAD

**Issue by melg8** [slowtorta/turtlewow-bug-tracker#6488]
**Please, provide a clear description what the bug is:**
When stunlocked Jaedenar Adept doesn't use blink ability to get out of it and just dies.

**Steps to reproduce the behavior with as much detail as possible:**
1. Apply any stunlock abilities towards Jaedenar Adept while being in melee range with it
2. Observe it not using blink to get out of stunlock and get distance.
Example:

[![video](https://github.com/slowtorta/turtlewow-bug-tracker/assets/16599015/b5227ed9-128d-4d10-a69e-519ee8eeff4d)](https://www.youtube.com/watch?v=cEZEKQlMuLM)

**IDs of affected creatures, items, quests or spells with a link to the relevant page:**

NPC: [Jaedenar Adept](https://database.turtle-wow.org/?npc=7115)
Spell: [Blink](https://database.turtle-wow.org/?spell=14514)

**Expected behavior. Describe how it should work:**
This iconic spell is used by mages to not only gain distance but also to get out of stuns. If Jaedenar Adept has it, it should use it to get out of stunlock. I discovered this bug whien i tried to use Jaedenar Adept as target dummy to test my macroses, but was dissapointed that it doesnt perform blink while stunned.

**Comment by ratkosrb** [comment]
It should be fixed in the next update.
