### ISSUE TITLE
Dense Dynamite radius

### ISSUE THREAD

**Issue by Flecked42** [slowtorta/turtlewow-bug-tracker#6489]
Dense Dynamite https://database.turtle-wow.org/?item=18641 seems to be showing a 10yd radius on the ground and its stated as 5yd radius.

Dense Dynamite shows the same radius on the ground as Stratholme Holy Water https://database.turtle-wow.org/?item=13180 which is a 10yd radius.

**Comment by ratkosrb** [comment]
The radius is in fact 5 like it says, not 10.
