### ISSUE TITLE
Hardcore party with higher level players

### ISSUE THREAD

**Issue by AMuffinLink** [slowtorta/turtlewow-bug-tracker#6493]
**Please, provide a clear description what the bug is:**
I was playing a new Hardcore character with a friend when we found a way to party even though we were 6 levels apart. As soon as we found this I took pictures and we didn't do anything as not to violate the rules. I'm not entirely sure if this is a bug or a feature but as per the Hardcore rules I would say its a bug unless told otherwise. I will include some screenshots at the bottom. Last pic is showing we are both Hardcore.
**Steps to reproduce the behavior with as much detail as possible:**

1. Form the party when you are 5 levels apart
2. The higher level member then levels up
3. It wont disband the party and you can have 2 people in the party that are 6+ levels apart 

**IDs of affected creatures, items, quests or spells with a link to the relevant page:**

NPC: N/A
Item: N/A
Quest: N/A
Spell: N/A
Object: N/A

**Expected behavior. Describe how it should work:**
We should not have been able to party as the Hardcore rules state that you can only party with those +-5 levels not 6.

![image](https://github.com/slowtorta/turtlewow-bug-tracker/assets/160769557/e701b0ee-c841-47fd-93fa-6b822e5511a5)
![image](https://github.com/slowtorta/turtlewow-bug-tracker/assets/160769557/d46854e8-297d-484b-8142-5b1715d46d72)
![image](https://github.com/slowtorta/turtlewow-bug-tracker/assets/160769557/8c9a8162-d667-4d67-bcd5-9b921d2c73ed)

**Comment by melg8** [comment]
@AMuffinLink i think its not even about 1 lvl apart, if you start after server restart as group of 2 players with lvl 1. and one will pump levels, while other just stays afk, by the end of the week you can have lvl 1 and lvl 30 in same group. And actually im okay with 6 lvl difference - cause imagine that - you go to instance with 25 and 30 lvl tank, lvl 30 gets level up... Now what? need to find other tank cause that is too high level or kick lvl 25? cause he is dragging group level down? So it would be bad qol change. But for preventing some kind of abuse mechanics - i would suggest to disband party if it somehow get 7 lvl difference, cause 2 levels diff while in same party is really rare and looks more like some kind of abuse.

**Comment by twowTurtReynolds** [comment]
Don't worry Muffin, this is not something bannable, nor something that needs to be fixed, you can continue without worry if this ever happens.
