### ISSUE TITLE
Can teleport to battleground while in combat and under crowd control spells

### ISSUE THREAD

**Issue by melg8** [slowtorta/turtlewow-bug-tracker#6495]
**Please, provide a clear description what the bug is:**
When battleground queue procs, you can enter battleground from in combat state. Not only that, you can enter it while being under crowd control spells from mobs or from players.

**Steps to reproduce the behavior with as much detail as possible:**
1. Queue AV as horde for quick procs
2. Start combat with any npc or player
3. Press enter battleground
4. Observe being teleported to battleground

**Expected behavior. Describe how it should work:**
Queue proc should not accept players entering battleground untill they are out of combat.
Because of current mechanics people abuse it world pvp situations, like teleporting out of combat/rogue cc from middle of enemy city to avoid being killed. Or do one-shot attacks in gadgedzan (and other neutral cities) and then immediately accepting battlegound proc for avoiding being punished by guards.

**Comment by ratkosrb** [comment]
Should be fixed in the next update.
