### ISSUE TITLE
/afk removes you from battleground instantly even in combat and under crowd control spells

### ISSUE THREAD

**Issue by melg8** [slowtorta/turtlewow-bug-tracker#6496]
**Please, provide a clear description what the bug is:**
If you use /afk on battlegound you get afk state and get teleported out of battleground right away. Even if you are in middle of fight and under crowd control spells of other players.

**Steps to reproduce the behavior with as much detail as possible:**
1. Get into any battleground
2. Start fight with other player, get "In combat status"
3. type /afk in chat
4. Observe being removed from battleground while still in combat.

**Expected behavior. Describe how it should work:**
Afk status should remove frome battleground only if you are not in combat. When you are in combat or under crowd control spells you should not be able to escape pvp by just typing /afk. 

In current situation players abuse such mechanics, for example they showup on AV, run for black lotus spawn, even if its on enemy side of map, and after they got it(or not) they simply /afk out of battleground, while under guards, enemy rogues stunlocks etc. Which is quite annoying for players who could get honorable kills but miss them just cause someone used /afk command. Also this mechanics sometiimes is abused by hardcore characters, which feel safe to join av and try to farm there, cause in case of any danger they can insta /afk away from bg while not being punished for that.

**Comment by ratkosrb** [comment]
https://github.com/slowtorta/turtlewow-bug-tracker/assets/35845488/66165252-65fa-495f-9cda-aaa67c525626

I can't reproduce the issue. It does not kick you from the BG if you are in combat.

**Comment by melg8** [comment]
@ratkosrb my bad was writing from memory of some time ago, probably were fixed for a while then. Ty!
