### ISSUE TITLE
Stealthed players on same team can't see eachother in same raid group in stealth on battlegrounds.

### ISSUE THREAD

**Issue by melg8** [slowtorta/turtlewow-bug-tracker#6497]
**Please, provide a clear description what the bug is:**
When two players are in same group you can see stealthed player just fine. But if you are in same raid group, like on AV, but in different party groups - you can only see eachother on close range via stealth detection. 

**Steps to reproduce the behavior with as much detail as possible:**
1. Join Alterac Valley battleground
2. Find some rogue or other stealther class in your team but in different group
3. Observe  not being able to see him in distance while he is stealthed.

**Expected behavior. Describe how it should work:**
While in same raid group on battlegrounds you should be able to see all stealthed friendly players no matter if they are in same party or not. Because of current implementation its hard for stealthed players to coordinate actions with each other, because only way they can see each other is on minimap. So in critical situations players may miscoordinate (for example going onto two different objectives, instead of one) or not approaching enemy at the same time. In other vmangos derived servers i saw that strategy implemented and it works great for improving teamplay.

**Comment by twowTurtReynolds** [comment]
https://github.com/slowtorta/turtlewow-bug-tracker/issues/5728
