### ISSUE TITLE
The  cloth reputation turn-in for the Gnomeregan Exiles is bugged

### ISSUE THREAD

**Issue by SierraNairn** [slowtorta/turtlewow-bug-tracker#65]
https://database.turtle-wow.org/?npc=14724  -Bubulo Acerbus
Only a Donation of Wool can be completed.
Can't complete quests  cloth turn in beyond  A Donation of Wool.

**Comment by slowtorta** [comment]
Thanks for reporting it. It'll be fixed on the next server restart. Make sure to clear your WDB folder.
