### ISSUE TITLE
Goblin's barber stole my hair

### ISSUE THREAD

**Issue by GloutonLeVrai** [slowtorta/turtlewow-bug-tracker#650]
The Goblin's barber in Sparkwater Port (Bebri Coifcurl) is bugged: you can change your hair (and trime your beard) a few times but in the end you get totally bald and there is no way back.
I was able to change my own hair 3 times exactly. Two other Goblin characters came after me and they became bald after the first hair change.

NPC: can't find the NPC ID in the database... but it's **Bebri Coifcurl**.

**Comment by slowtorta** [comment]
Please, try using the option a few more times.

**Comment by slowtorta** [comment]
I plan to rework them in the near future. Submit a GM ticket if your character is still broken, please!
