### ISSUE TITLE
Human Racial +5 

### ISSUE THREAD

**Issue by xAzeroth** [slowtorta/turtlewow-bug-tracker#6500]
Hello , something is wrong with human racial +5 , having sword +8 hit% still makes you miss is maybe Human Racial not working right now after some patch updates ?   would you like me do faivor and run some tests on general  Human racial too see if its working properly becouse it's weird too see lots of miss on low lvl target

**Comment by twowTurtReynolds** [comment]
All is working correctly, it sounds like you experienced a debuff, or are confused how dual wield works.
