### ISSUE TITLE
Drowning above ground in the Thalassian Highlands

### ISSUE THREAD

**Issue by RSRP** [slowtorta/turtlewow-bug-tracker#6503]
**Please, provide a clear description what the bug is:**

**Steps to reproduce the behavior with as much detail as possible:**

1. Go to the area in the Thalassian Highlands
2. Move around between pond and ocean until you find the exact spot
3. Drown

**IDs of affected creatures, items, quests or spells with a link to the relevant page:**

https://imgur.com/a/Es3C8iZ is a screenshot of the spot / tick down for drowning

**Expected behavior. Describe how it should work:**

This area is falsely flagged as you being underwater even when you're standing above ground, making it so that you drown if you stay there too long.

**Comment by twowTurtReynolds** [comment]
https://github.com/slowtorta/turtlewow-bug-tracker/issues/5811 in the pins
