### ISSUE TITLE
Killed Madness 4 times, no 85% weapon drop.

### ISSUE THREAD

**Issue by Kharkov72** [slowtorta/turtlewow-bug-tracker#6504]
Only been getting a single madness trinket mat three times in a row, with three Hazza'rah kills and one Renataki kill. Been chalking it up to bad luck so far, but I'm starting to get a little worried something got fucked up with the loot tables when the eye of divinity and ancient leaf got fixed in MC.

**Comment by twowTurtReynolds** [comment]
First three kills rewarded the weapon.
