### ISSUE TITLE
Alromion gives you hard epilepsy check instead of flying.

### ISSUE THREAD

**Issue by melg8** [slowtorta/turtlewow-bug-tracker#6505]
**Please, provide a clear description what the bug is:**
When you press gossip of Alromion "Please guide me through Caverns of Time" instead of just mounting you on fly mount, it also snaps you into the ground and starts randomly spin you character and camera. 

**Steps to reproduce the behavior with as much detail as possible:**
1. Stay infront of Alromion and press "Please guide me through Caverns of Time"
2. Press forward as soon as gossip closed. This will just stop you inplace, but if you hold your right mouse button, or move in other directions it will add to the shuttering effect.
3. You can increase effect if you continue to try to press movement in different directions.

# WARNING!!! if you have epilepsy do not play this videos.
Steps to reproduce effect:
[![reproduce](https://github.com/slowtorta/turtlewow-bug-tracker/assets/16599015/73b7c05d-64ad-4ade-ae51-3648d2e9d446)](https://www.youtube.com/watch?v=mMLrQ26BXA4)

When i first encountered this, looked like so:
[![first time](https://github.com/slowtorta/turtlewow-bug-tracker/assets/16599015/d9507b4f-10d3-4b9e-bb30-4a9025ad55e7)](https://www.youtube.com/watch?v=slp4xmGcVTM)

Other person near me also got checked:
[![other person](https://github.com/slowtorta/turtlewow-bug-tracker/assets/16599015/7c08b5a8-9b84-49b9-b399-dc37bf091ce9)](https://www.youtube.com/watch?v=Rg2rYhw0MKo)

Please fix it asap, its like a warcrime agains humanity, kek.

**IDs of affected creatures, items, quests or spells with a link to the relevant page:**

NPC: [Alormion](https://database.turtle-wow.org/?npc=65018)

**Expected behavior. Describe how it should work:**
Should just roam left and right on ground normally, and not prevent to take off ground.

## Bonus points!
If you can fix Alormion site description, cause now when you search for him you get this page: https://database.turtle-wow.org/?npc=65018 which... lacks some info i guess.

**Comment by Szwedowski** [comment]
Just press NumLock or ↑ arrow and fly forward. Don't try to break the game.

**Comment by twowTurtReynolds** [comment]
This is unfixable. The workaround is to stop moving for a second before doing the transition.
