### ISSUE TITLE
Some of riding animals doesn't provide gossip for riding for 50 copper near gadgedzan

### ISSUE THREAD

**Issue by melg8** [slowtorta/turtlewow-bug-tracker#6506]
**Please, provide a clear description what the bug is:**
Some of Riding animals near Gadgetzan doesnt provide option to ride them for 50 copper.

**Steps to reproduce the behavior with as much detail as possible:**
1. Do as in video:
[![video](https://github.com/slowtorta/turtlewow-bug-tracker/assets/16599015/df2f3492-d6e7-4c5b-a6e4-37f52c6692df)](https://youtu.be/VCzTyrHlLAQ)

**IDs of affected creatures, items, quests or spells with a link to the relevant page:**

NPC: 
- [Riding Horse](https://database.turtle-wow.org/?npc=8883)
- [Riding Tiger](https://database.turtle-wow.org/?npc=8882)
- [Riding Raptor](https://database.turtle-wow.org/?npc=8885)

**Expected behavior. Describe how it should work:**
Should be able to click on each of them and ride them for 50 copper.

**Comment by twowTurtReynolds** [comment]
Suggestions forum please.
