### ISSUE TITLE
Some mounts doesnt have sound for spacebar press while standing still

### ISSUE THREAD

**Issue by melg8** [slowtorta/turtlewow-bug-tracker#6507]
**Please, provide a clear description what the bug is:**
For example Riding Zhevra doesnt produce any sound when you press space bar while standing still. 

**Steps to reproduce the behavior with as much detail as possible:**
1. Mount Zhevra, or Immortal's Champion Drake for example
2. Stay still
3. Press space bar
4. Observe animation playing while no sounds made by mount.

[![изображение](https://github.com/slowtorta/turtlewow-bug-tracker/assets/16599015/0bdbd953-3284-4b7b-9057-8c86658d81fd)](https://youtu.be/IefdeIrGoKU)

**IDs of affected creatures, items, quests or spells with a link to the relevant page:**
Spells: 
- [Riding Zhevra](https://database.turtle-wow.org/?spell=46446)
- [Immortal Champion's Drake](https://database.turtle-wow.org/?spell=46211)

**Expected behavior. Describe how it should work:**
The can produce same sound as they do when you just mountup first time. Or some castom sound can be used, like zhevra can use sounds from horses.

**Comment by twowTurtReynolds** [comment]
This is normal in vanilla. Suggestions forum please.
