### ISSUE TITLE
Scorch can hit but fire vulnerability can resist

### ISSUE THREAD

**Issue by pepopo978** [slowtorta/turtlewow-bug-tracker#6508]
**Please, provide a clear description what the bug is:**
![image](https://github.com/slowtorta/turtlewow-bug-tracker/assets/1526649/8939575b-a8a0-4464-b987-668960150fd1)

Not sure if it this is intended but is scorch supposed to be able to hit and just fire vulnerability resist?  Same thing happens with winter's chill.  Feel like it didn't used to happen but maybe I'm wrong.

If it is intended would be nice to have the resist message display the correct target for use in addons.  

**Steps to reproduce the behavior with as much detail as possible:**

1.  Scorch heroic training dummy with no gear on so hit % is low

**IDs of affected creatures, items, quests or spells with a link to the relevant page:**

NPC: https://database.turtle-wow.org/?npc=
Item: https://database.turtle-wow.org/?item=
Quest: https://database.turtle-wow.org/?quest=
Spell: https://database.turtle-wow.org/?spell=
Object: https://database.turtle-wow.org/?object=

**Expected behavior. Describe how it should work:**
If not intended, scorch hitting should always apply fire vulnerability.

Fire Vulnerability resist message should display the correct target instead of the caster.

**Comment by twowTurtReynolds** [comment]
On latest vmangos:
![image](https://github.com/slowtorta/turtlewow-bug-tracker/assets/151180101/7cc85f0c-1023-4248-8509-5c3097d7e4e7)

You will need to provide blizzlike proof to the contrary.
