### ISSUE TITLE
Shaman enhances talent, strengthens power totem, strengthens after use or 77 points value, can not do 88 points value

### ISSUE THREAD

**Issue by frseven6410** [slowtorta/turtlewow-bug-tracker#6511]
**Please, provide a clear description what the bug is:**

**Steps to reproduce the behavior with as much detail as possible:**

1.gm, hello, enhance the Shaman talent to enhance the power totem and enhance the grace totem, after selecting this talent, the skill shows a value of 88 points, but only 77 points after the skill is used, is it a BUG? Please help solve it.
2. 
3. 

**IDs of affected creatures, items, quests or spells with a link to the relevant page:**

NPC: https://database.turtle-wow.org/?npc=
Item: https://database.turtle-wow.org/?item=
Quest: https://database.turtle-wow.org/?quest=
Spell: https://database.turtle-wow.org/?spell=
Object: https://database.turtle-wow.org/?object=

**Expected behavior. Describe how it should work:**

**Comment by twowTurtReynolds** [comment]
Tooltips will not reflect these changes, but your character stats should be correct.
