### ISSUE TITLE
Azshara quest: The Turbocharged Wobble-Free Fizz Disk requirement cannot be activated

### ISSUE THREAD

**Issue by cydith** [slowtorta/turtlewow-bug-tracker#652]
**Please, provide a clear description what the bug is:** In the cave mentioned in the quest, the control panel cannot be interacted with.

**Steps to reproduce the behavior with as much detail as possible:**

1. Take the specified quest in Azshara from Flaxwhisker port
2. Find the cave mentioned in the description
3. Attempt to interact with control panel

**IDs of affected creatures, items, quests or spells with a link to the relevant page:**

NPC: https://database.turtle-wow.org/?npc=
Item: https://database.turtle-wow.org/?item=
Quest: https://database.turtle-wow.org/?quest=
Spell: https://database.turtle-wow.org/?spell=
Object: https://database.turtle-wow.org/?object=

**Expected behavior. Describe how it should work:**

**Comment by Valamartle** [comment]
Can confirm, tried this quest today, same issue.
