### ISSUE TITLE
Azshara: Broken Oath - Myrmidon signets don't drop or have a very low drop chance

### ISSUE THREAD

**Issue by cydith** [slowtorta/turtlewow-bug-tracker#653]
**Please, provide a clear description what the bug is:** During the Broken oath quest in Azshara, which requires 20 signets, can be noticed that they don't drop. After killing around 30 mobs, not one signet dropped.

**Steps to reproduce the behavior with as much detail as possible:**

1. Take the Broken Oath quest from Rethress Sanctum
2. Proceed to kill Spitelash myrmidons
3. 

**IDs of affected creatures, items, quests or spells with a link to the relevant page:**

NPC: https://database.turtle-wow.org/?npc=
Item: https://database.turtle-wow.org/?item=
Quest: https://database.turtle-wow.org/?quest=
Spell: https://database.turtle-wow.org/?spell=
Object: https://database.turtle-wow.org/?object=

**Expected behavior. Describe how it should work:**

**Comment by bobz120** [comment]
Yeah killed 30 of them too, can confirm they don't drop signets.
