### ISSUE TITLE
Two-handed maces not available for high elves

### ISSUE THREAD

**Issue by kovacskri** [slowtorta/turtlewow-bug-tracker#654]
**Please, provide a clear description what the bug is:**

I started a high elf warrior and went to Ironforge to the dwarven weapon master. The two-handed maces skill is not available for training.

**Steps to reproduce the behavior with as much detail as possible:**

1. Create a high elf warrior
2. Talk to Buliwyf Stonehand in Ironforge
3. The weapon skill is not listed

**IDs of affected creatures, items, quests or spells with a link to the relevant page:**

NPC: https://database.turtle-wow.org/?npc=
Item: https://database.turtle-wow.org/?item=
Quest: https://database.turtle-wow.org/?quest=
Spell: https://database.turtle-wow.org/?spell=
Object: https://database.turtle-wow.org/?object=

**Expected behavior. Describe how it should work:**
The weapons skill should either be available for training or unlocked upon character creation.
![WoW_LkjkThnm7h](https://user-images.githubusercontent.com/19145864/147657471-58005036-1e6b-447b-aecb-58e54509719e.jpg)

**Comment by Tinyfin-github** [comment]
Greetings!

Please open an in game ticket and a Game Master will Teach you until the issue is solved.
