### ISSUE TITLE
Shadowfang Keep - "Loot is still being rolled for."

### ISSUE THREAD

**Issue by jlautenbach** [slowtorta/turtlewow-bug-tracker#656]
**Please, provide a clear description what the bug is:**

**Steps to reproduce the behavior with as much detail as possible:**

1. Enter SFK around 21:15 CET with a cross-faction group of 5. I entered with an Alliance character.
2. Kill Wolf Master Nandos. He drops Feline Mantle. All roll (2x need, rest greed) and let the group die once the roll is finished.
3. Corpse walk back to the instance and body of Wolf Master Nandos.
4. Let the winner try and loot the Feline Mantle from the corpse, it will say: roll is still in progress.

**IDs of affected creatures, items, quests or spells with a link to the relevant page:**

NPC: https://database.turtle-wow.org/?npc=3927
Item: https://database.turtle-wow.org/?item=3748
Quest: https://database.turtle-wow.org/?quest= **N/A**
Spell: https://database.turtle-wow.org/?spell= **Unknown**
Object: https://database.turtle-wow.org/?object= **Unknown**

**Expected behavior. Describe how it should work:** 
We would expect one who won the roll would be able to loot the item. Everybody rolled and chatWindow confirmed 'Niralthas' as the winner. Even after a corpse walk and the item still being available on NPC's corpse and before NPC de-spawns. 

**Extra info:**  
I had just removed my WDB folder due to a number of crashes and disabled all addons except Healbot.

**Extra comment**
As this seemed like something that can happen on any private server, I tried a GM ticket first. However, deducting from the answer below no logs are available to verify such a claim by the support team. I therefore wonder if this issue has any merit but the Support Team explicitly asked me to create an issue. Here you go. 👍 

![Capture2](https://user-images.githubusercontent.com/73019779/147666874-4dbf8a6b-3cee-41d5-991c-0610390c4925.PNG)

Note that we also had the issue that the bindings/corpse of a voidwalker would keep following us and we would stay in combat and could not move to the next room. We had to let ourselves die in order to solve this. A video has been made, as soon as I have received it a ticket will be created.

**Comment by Kruxis** [comment]
Did it only happen once?

Usually the roll still proceeds even tho the group died. It might be just a bug which happens randomly every century.
