### ISSUE TITLE
Tirsfal Uplands: Quest The First Settlement

### ISSUE THREAD

**Issue by dshwedovsky-sc** [slowtorta/turtlewow-bug-tracker#657]
At completing quest **The First Settlement** awarded reputation with Shaterspear Trolls instead of Silvermoon Remnant.

![WoWScrnShot_122921_162444](https://user-images.githubusercontent.com/25076735/147667899-43a555f5-3e1d-4016-84a8-edfc246bbe84.jpg)
![WoWScrnShot_122921_162431](https://user-images.githubusercontent.com/25076735/147667917-89849889-6d43-4eb3-95e4-6cdc3f18ad84.jpg)
![WoWScrnShot_122921_163554](https://user-images.githubusercontent.com/25076735/147667919-7405c2fa-0df7-4ce3-81d5-a97fa7ed3388.jpg)

Expected behavior: awarded reputation with Silvermoon Remnant at completing.
Database now is not working:
Quest: https://database.turtle-wow.org/?quest=

**Comment by Neto-WoW** [comment]
Fixed.
