### ISSUE TITLE
parachute cloak didn't work

### ISSUE THREAD

**Issue by Crableth** [slowtorta/turtlewow-bug-tracker#658]
**Please, provide a clear description what the bug is:**
had used my parachute cloak and jumped from a cliff in Whelgar's excavation site, but still died when hit the ground.

**Steps to reproduce the behavior with as much detail as possible:**

1. activated the item parachute cloak
2. jumped and still had the animation and buff of slow fall
3. died when hit the ground

**Expected behavior. Describe how it should work:**

i would jump and don't die from the fall

**Comment by Neto-WoW** [comment]
Working as intended. Cannot reproduce the issue.
