### ISSUE TITLE
Boat dissapears.

### ISSUE THREAD

**Issue by Tinyfin-github** [slowtorta/turtlewow-bug-tracker#66]
The boat sometimes gets stuck , After a while it dissapears and the players get dropped into water.
It seems the boat apears correctly where it was supossed to continue moving if it did not stop.

Get on a boat,
The boat gets stuck.
The boat goes missing.
The player dies because of fatigue in water.
The problem seems to be only for the player side , the boat keeps moving the world.
Latency and FPS  have good value.

**Comment by Nolin7777** [comment]
Please add steps to reproduce.
Ticket will be closed meanwhile.

**Comment by Tinyfin-github** [comment]
Updated with more information.
