### ISSUE TITLE
PVP Rewards - Losers not gaining anything if game lasts less than 10 min or Dominated

### ISSUE THREAD

**Issue by Rakura1** [slowtorta/turtlewow-bug-tracker#660]
Patch Note: Losers of specific Battlegrounds will now be rewarded accordingly to incentivize Battlegrounds.

Problem: When in Arathi Basin or Warson Gulch and enemy team is dominated either 5 cap or 3-0 "incentivized rewards" are not being given.

**Steps to reproduce the behavior with as much detail as possible:**

1. Enter in AB
2. Get 5 capped
3. Lose the match

You will receive no rewards ie token or rep. Also it should be further noted as a part 2 to this that Bonus honor is not working in Arathi Basin at all for specific RSS gained.

**Expected behavior. Describe how it should work:**
Losers of specific Battlegrounds will now be rewarded accordingly to incentivize Battlegrounds.

**Comment by CosminPOP** [comment]
Working as intended

https://wowwiki-archive.fandom.com/wiki/Patch_1.8.4

Battlegrounds
Battles must now last at least ten minutes after the start of the battle in order for the losing team to receive a Mark of Honor.

**Comment by usedcars4cheap** [comment]
Looks like this change was revered immediately the next day:

https://wowpedia.fandom.com/wiki/Battleground

![image](https://user-images.githubusercontent.com/68176649/191661928-315e2bd4-e792-4057-b610-bcd3391a6164.png)
