### ISSUE TITLE
Mage table and warlock soulwell broken

### ISSUE THREAD

**Issue by afizzler** [slowtorta/turtlewow-bug-tracker#661]
As stated by the title, the items to make a mage table and warlock soulwell can not spawn the intended objects of a mage table and warlock soulwell. The error message is related to it affecting a pet, which is clearly not the intended behavior of the items to spawn them. 

Database is disabled, so I can't link the direct items that create the mage table and warlock soulwell.

**Comment by gorxen** [comment]
This is fixed now
