### ISSUE TITLE
Mage clearcasting/arcane missiles

### ISSUE THREAD

**Issue by afizzler** [slowtorta/turtlewow-bug-tracker#662]
Arcane missiles do not proc clearcasting per tick. The intentional behavior should be to proc clearcasting per tick. This is same for the 8/8 T2 set bonus for mages in which arcane missiles do not proc the T2 set bonus per tick.

**Comment by afizzler** [comment]
i need to check first before seeing if i should reopen

**Comment by slowtorta** [comment]
Fixed in the next revision.
