### ISSUE TITLE
(Item) Skin Change Token: Forest Troll (female)

### ISSUE THREAD

**Issue by avaruu** [slowtorta/turtlewow-bug-tracker#663]
Hello! After Mysteries of Azeroth released, female trolls had several new skins added specific for forest trolls.

The Skin Change Token: Forest Troll now applies one of those forest troll skins available at character creation. Previously, it applied a pale green skin that uses the base female troll texture that is not available at character creation. Clearing WDB and re-using the item did not fix this issue.

Item: **Skin Change Token: Forest Troll**

Apologies for lack of good images, here is a portrait comparison.

![FT](https://user-images.githubusercontent.com/96836426/147684297-6af8a199-723f-4010-877f-2fb17a34e58e.jpg)

Thanks!

**Comment by slowtorta** [comment]
Will be fixed on the next update. Token will include 2 version of the Forest skin troll toggled randomly on use.
