### ISSUE TITLE
Quest: The Bloodsail Compound III

### ISSUE THREAD

**Issue by Janusregno** [slowtorta/turtlewow-bug-tracker#664]
**Please, provide a clear description what the bug is:**
In The Bloodsail Compound III, a quest that basically requires hated with all of the Steamwheedle Cartel requires you to speak with someone that is listed as a member of Gadgetzan, so he is hostile and the quest cannot progress.
**Steps to reproduce the behavior with as much detail as possible:**

1. Pick up quest The Bloodsail Compound III
2. Go to Steamwheedle Port
3. Approach Jabbey

**IDs of affected creatures, items, quests or spells with a link to the relevant page:**

NPC: https://database.turtle-wow.org/?npc=
Item: https://database.turtle-wow.org/?item=
Quest: https://database.turtle-wow.org/?quest=
Spell: https://database.turtle-wow.org/?spell=
Object: https://database.turtle-wow.org/?object=

**Expected behavior. Describe how it should work:**
Jabbey should be interactable.
![image](https://user-images.githubusercontent.com/76000153/147684514-2739484c-df00-4052-bc4a-f0fe94b13ef2.png)

**Comment by Neto-WoW** [comment]
Fixed.
