### ISSUE TITLE
Quest: Grizzlore Wants Thunder impossible to complete as Horde

### ISSUE THREAD

**Issue by Jake-Malinov** [slowtorta/turtlewow-bug-tracker#666]
![quest in question](https://user-images.githubusercontent.com/96836447/147684696-68260039-0aed-464e-8694-f11fc758360c.png)

The winterveil quest **Grizzlore Wants Thunder** which rewards the item **Illusion: Furbolg** isn't possible to be completed by Horde players. The NPC in Westfall named **Grombooze Thunderbrew** is hostile towards Horde and thus cannot be talked to in order to receive the **Keg of Thunderbrew Lager** from a repeatable quest called **Thunderbrew Lager**.

I have asked in world chat whether this is the case for others and one Horde player stated that they were able to complete the quest at an earlier date before 1.16's release. Most other people stated that they are in the same situation as me - currently unable to complete the quest due to the NPC being hostile.

IDs cannot be provided because of the DB being disabled.

The expected behaviour would be either for the quest NPC **Grombooze Thunderbrew** to be neutral towards Horde or to have a separate Horde-only quest.

**Comment by Tinyfin-github** [comment]
You can't interact with the NPC from the opposite faction. Horde has their own NPC to get the item from.
