### ISSUE TITLE
Tirisifal Uplands: Magister Salorn Underpowered

### ISSUE THREAD

**Issue by pyrami123** [slowtorta/turtlewow-bug-tracker#667]
Magister Salorn is a level 20 elite mob that casts frost bolts and healing spells. These frost bolts hit for an incredibly low amount of damage, 30-40ish damage from what I've tested(which is an ordinary amount of damage for a normal enemy couple levels under level 20.) Without mana, his auto-attacks deal 60-100 damage. This elite enemy could need a buff, as he poses no particular threat compared to his elite counterparts.

**Comment by Neto-WoW** [comment]
Agreed. Buffed the spell damage. Thanks!
