### ISSUE TITLE
Ribbly's Cronies Overprotective

### ISSUE THREAD

**Issue by Dragunovi** [slowtorta/turtlewow-bug-tracker#67]
**Please, provide a clear description what the bug is:**
Ribbly's cronies attack Blackbreath and his cronies when combat is engaged when this shouldn't happen, this wouldn't bother people if them attacking Hurley Blackbreath didn't make him not drop his quest item [Lost Thunderbrew Recipe], making it incompleteable.
**Steps to reproduce the behavior with as much detail as possible:**

1. Go to Blackrock Depths bar.
2. Break the ale barrels inside the room and start the encounters.
3. They will run to help fight Blackbreath and his cronies.

**IDs of affected creatures, items, quests or spells with a link to the relevant page:**

NPC: https://database.turtle-wow.org/?npc=10043

**Expected behavior. Describe how it should work:**
They should not attack mobs that are fighting the players at all, just stand there until the encounter is manually engaged by a player.

**Comment by Nolin7777** [comment]
Closed until source added.
