### ISSUE TITLE
Strange Error upon logging related to transmog UI

### ISSUE THREAD

**Issue by inxdigo** [slowtorta/turtlewow-bug-tracker#670]
Strange Error that pops up sometimes upon logging in to any character. WDB folder has been cleared more than once to verify it's not that. I have no idea what it affects, seem to be able to use the transmog feature without issues.

![WoWScrnShot_122921_121712](https://user-images.githubusercontent.com/74259373/147688753-74bb5ebc-b4c7-4627-a4a5-3d26e27ca621.png)

**Comment by Neto-WoW** [comment]
Hi there. This is an issue with one of your addons.
