### ISSUE TITLE
Tears of the Poppy  (minor) 

### ISSUE THREAD

**Issue by Lothlens** [slowtorta/turtlewow-bug-tracker#671]
Tears of the Poppy -Custom daily quest for Silvermoon Remnant picked up in Alah'thalas- quest text in log is for Tears of The Moon, Teldrassil levelling quest

Cheers! loving the server x 

- Dooland (Lothlens)

![image](https://user-images.githubusercontent.com/96839366/147689879-2466146f-2bbe-4422-8124-293eba4ffd34.png)

**Comment by Lexiebean** [comment]
@Lothlens Appears fine for me - https://i.imgur.com/p5K5HTS.png

Clear your WDB folder.
