### ISSUE TITLE
Blacksmithing: Copper Knuckles takes money but doesn't train the skill

### ISSUE THREAD

**Issue by trihard711** [slowtorta/turtlewow-bug-tracker#676]
*
![Screenshot (10)](https://user-images.githubusercontent.com/96794610/147692969-20ccf6f3-5723-4e5d-8fef-cee7f3553c73.png)
*Please, provide a clear description what the bug is:**

When you attempt to train the Copper Knuckles from a blacksmithing trainer, it takes the money from your character. However, it does not train that skill.

**Steps to reproduce the behavior with as much detail as possible:**

1. Talk to blacksmithing trainer
2. Attempt to train Copper Knuckles
3. Notice that it takes the money from you while the skill remains untrained
![Screenshot (11)](https://user-images.githubusercontent.com/96794610/147692976-a75fe7e5-4672-4d46-be7a-e41767adc10a.png)

**IDs of affected creatures, items, quests or spells with a link to the relevant page:**

DB is disabled

**Expected behavior. Describe how it should work:**

The skill should have been taught instead of staying in as available to be trained.

**Comment by Neto-WoW** [comment]
Unable to reproduce. Please clear WDB and disable addons.

![image](https://user-images.githubusercontent.com/79717052/148000671-59483c0b-6802-4af3-af8b-5a71683f3796.png)
![image](https://user-images.githubusercontent.com/79717052/148000681-90bce13d-e832-4c6d-a914-a059b97e0196.png)
