### ISSUE TITLE
Mechnical Squirrel disappears when summoned. 

### ISSUE THREAD

**Issue by mybrid** [slowtorta/turtlewow-bug-tracker#677]
Toon: Xraylen, level 18 Warlock, 90 Eng. 
I created a mechanical squirrel and when I summoned it the summon hung and the squirrel box disappeared from my bag. I was able to use the 'Esc' key to stop the summons. 

**Steps to reproduce the behavior with as much detail as possible:**

1. Summon Mechanical Squirrel.  

**IDs of affected creatures, items, quests or spells with a link to the relevant page:**
https://www.wowhead.com/npc=2671/mechanical-squirrel
NPC: https://database.turtle-wow.org/?npc=267

**Expected behavior. Describe how it should work:**
The vanity pet should summon.

**Comment by Lexiebean** [comment]
@mybrid check the General tab of your spellbook: https://i.imgur.com/EYbUbiV.png

**Comment by mybrid** [comment]
That works! I guess I just needed to know this would happen!
