### ISSUE TITLE
The Tortured Elf by Naxiar can be hit by AoE

### ISSUE THREAD

**Issue by imcdermott13** [slowtorta/turtlewow-bug-tracker#678]
The Tortured Elf by Naxiar in Ashenvale can be hit by Area of Effect attacks, and when struck slides along the ground to attack the player, despite being classified as a corpse.

1. Travel to Naxiar by the lake in Eastern Ashenvale.
2. Use an Area of Effect attack on The Tortured Elf.
3. Notice that The Tortured Elf slides along the ground to attack the player that hit it.

The Tortured Elf is a corpse, and should not be able to be struck by or attack players.

**Comment by Neto-WoW** [comment]
Fixed. Thanks.
