### ISSUE TITLE
Fatigue in Northshire Valley River

### ISSUE THREAD

**Issue by iagodiago** [slowtorta/turtlewow-bug-tracker#679]
**Please, provide a clear description what the bug is:**

The fatigue bar appears when standing in several spots in the Northshire Valley river. When standing in there for too long, the fatigue will eventually kill the player.

**Steps to reproduce the behavior with as much detail as possible:**

1. Go to Northshire valley into the river between the two big grasses (approx. x50.3, y47.4). The fatigue will activate there.
![image_2021-12-29_204450](https://user-images.githubusercontent.com/96843078/147698029-630745f9-6d44-4d3e-8473-bd857e307c05.png)

**IDs of affected creatures, items, quests or spells with a link to the relevant page:**

No creature, item, quest etc. affected.

**Expected behavior. Describe how it should work:**

Fatigue should not apply here, as it normally applies when going to far into the ocean or outside of the normal map bounds.

**Comment by Neto-WoW** [comment]
Fixed.
