### ISSUE TITLE
Bloodvenom Post Guards are smol

### ISSUE THREAD

**Issue by Dragunovi** [slowtorta/turtlewow-bug-tracker#68]
**Please, provide a clear description what the bug is:**
The tauren guards are shorter and smaller than other tauren, being roughly at the same size as a troll, its very odd.
**Steps to reproduce the behavior with as much detail as possible:**

1. Go to Bloodvenom Post
2. Compare your size with the guards
3. Laugh at their shortness

**IDs of affected creatures, items, quests or spells with a link to the relevant page:**

NPC: https://database.turtle-wow.org/?npc=11180

**Expected behavior. Describe how it should work:**
They should be as big as a normal tauren.

**Comment by slowtorta** [comment]
Thanks for reporting it. It'll be fixed on the next server restart. Make sure to clear your WDB folder.
