### ISSUE TITLE
Stone Guardian Pathing Seems Wrong

### ISSUE THREAD

**Issue by imcdermott13** [slowtorta/turtlewow-bug-tracker#681]
The Stone Guardians around the Plate of Uldum in Un'Goro Crater aren't able to move or attack players if they are on different y-levels.

1. Go to the North Resonating Crystal in Un'Goro Crater.
2. Stand slightly above one of the Stone Guardians on the hill.
3. Note that the Guardians are unable to move to the player and will not attack.

**Comment by Nolin7777** [comment]
Not reproduceable, working as intended.

**Comment by geojak** [comment]
hello i was just able to reproduce this issue
here are some screenshots
pls reopen thi
![WoWScrnShot_031222_165606](https://user-images.githubusercontent.com/25199983/158025225-a80b92ef-6382-4e55-9fb0-9dc63fe6f8af.jpg)
![WoWScrnShot_031222_165622](https://user-images.githubusercontent.com/25199983/158025230-fea63f6f-79c3-4bb4-8dac-3fd2d06415f7.jpg)
![WoWScrnShot_031222_165630](https://user-images.githubusercontent.com/25199983/158025231-da3140db-2f1c-4eac-aced-65d33e792a69.jpg)

**Comment by geojak** [comment]
another issue with these guarians, they are super easy to kill and drop the green guardian stne.

this makes farming the patrolling elite ones compeltey obsolete and should be changed

**Comment by geojak** [comment]
@slowtorta hello torta, could you have a second look at this issue? I encountered the same issue as the OP and included some screenshots thaz might help to reproduce the issue
