### ISSUE TITLE
The - Ancient Treasure - chest from the treasure room from uldaman is missing

### ISSUE THREAD

**Issue by Toirto** [slowtorta/turtlewow-bug-tracker#684]
**Please, provide a clear description what the bug is:**
In the dungeon Uldaman after killing the last boss of the instance Archaedas there is a treasure room behind him full of gold in which you complete some quests and in which there is a chest called - Ancient Treasure - in which there are some greens. Unfortunley in current version of Turtle WoW that chest is missing from the instance and a now there is a quest which is supposed to be completed by reciving an item from that said chest supposedly called Intact Power Core but it cannot be completed because of the matter above.

**Steps to reproduce the behavior with as much detail as possible:**

1. Do Uldaman
2. Complete Uldaman
3. Sadness

**IDs of affected creatures, items, quests or spells with a link to the relevant page:**

NPC: none
Item: Intact Power Core
Quest: Requisitioning a core
Spell: none
Object: Ancient Treasure

**Expected behavior. Describe how it should work:**

The chest is there on classic that's where I done vanilla uldaman.
Here is a Platinum WoW video that has the chest and it's location on video. (it's next to the pillar to the right of the room from the entrance side and a litlle bit turned to the gold pile)
https://youtu.be/stxSimvCaPU?t=669 - the link has the exact moment where it is

**Comment by Neto-WoW** [comment]
Hi there. I'm unable to verify that it drops items as well as the quest item. I've only found videos online of the chest being empty (except for the quest item).

Added quest item and chest though!
