### ISSUE TITLE
Decrepit Darkhound PvP flag

### ISSUE THREAD

**Issue by chrissie8000** [slowtorta/turtlewow-bug-tracker#685]
**Please, provide a clear description what the bug is:**
The Decrepit Darkhound near Brill, the one on the hill towards Zappelin tower, he is flagged for PvP, so anyone who attacks him gets flagged in turn, he never did that before.
**Steps to reproduce the behavior with as much detail as possible:**

1.Wait for him to spawn
2. Profit
3. 

**IDs of affected creatures, items, quests or spells with a link to the relevant page:**

NPC: https://database.turtle-wow.org/?npc=
Item: https://database.turtle-wow.org/?item=
Quest: https://database.turtle-wow.org/?quest=
Spell: https://database.turtle-wow.org/?spell=
Object: https://database.turtle-wow.org/?object=

**Expected behavior. Describe how it should work:**
He shouldn't flag people, he never did before, all those low level hc's are gonna die when alliance will decide to show up.

**Comment by slowtorta** [comment]
Sorry, I couldn't reproduce this issue. Probably you got flagged on something else.
