### ISSUE TITLE
alchemy trainer Ainethil  missing 4 potions

### ISSUE THREAD

**Issue by Steevo2** [slowtorta/turtlewow-bug-tracker#686]
The artizan alchemy trainer Ainethil (in darnasus) is supposed to train greater mana pot, superior healing pot, immolation oil and greater water breathing elixir according to wowhead classic, but she does not. I have 225 alch so its not that.

**Comment by Tinyfin-github** [comment]
Greetings!

In vanilla those she did not sell those items.

https://vanillawowdb.com/?npc=4160
