### ISSUE TITLE
Kul Tiran rep

### ISSUE THREAD

**Issue by Lordanthony** [slowtorta/turtlewow-bug-tracker#689]
Me and a friend were doing quests in Lapidis and we start completing quests, we notice we weren't getting reputation, so we stopped.

here i have some pictures

before completing the quest
![image](https://user-images.githubusercontent.com/96844239/147712925-66b31dac-d0b0-474a-a882-cae42fa6f070.png)

after completing the quest

![image](https://user-images.githubusercontent.com/96844239/147713059-4cdc58fc-ef4c-46e0-be33-17630b7c06fa.png)

and the reputation bar its still in 0

I suppose this quests should give Kul Tiran rep but maybe i am wrong.

Thanks in advance and stay safe.

**Comment by ulricc66** [comment]
I have completed about 10-15 of them now and can confirm this, zero Rep so far.
