### ISSUE TITLE
UNSPECIFIED TAXI ERROR

### ISSUE THREAD

**Issue by hazlema** [slowtorta/turtlewow-bug-tracker#691]
**Please, provide a clear description what the bug is:**

**Steps to reproduce the behavior with as much detail as possible:**

1.Click on Gryphon Master in Theramore and choose Astranaar

**IDs of affected creatures, items, quests or spells with a link to the relevant page:**

NPC: https://database.turtle-wow.org/?npc=
Item: https://database.turtle-wow.org/?item=
Quest: https://database.turtle-wow.org/?quest=
Spell: https://database.turtle-wow.org/?spell=
Object: https://database.turtle-wow.org/?object=

**Expected behavior. Describe how it should work:**

You should be able to fly and not get the error UNSPECIFIED TAXI ERROR.  Other flightpaths work, just this one so far.

Image:
https://ibb.co/Kq9wKn3

**Comment by Tinyfin-github** [comment]
Greetings! This flight path has been temporarily dissabled until some issues are fixed.
