### ISSUE TITLE
Typo in Old Greypaw quest (Ashenvale new quest)

### ISSUE THREAD

**Issue by SlabheadMaguire** [slowtorta/turtlewow-bug-tracker#692]
Just a typo in the quest text
 
![image](https://user-images.githubusercontent.com/96760583/147715738-0640a9f6-b1d2-4c10-be48-4a1f6c3e10c9.png)
 
side note this quest is morbid why do we have to murder an old depressed furbolg :(

**Comment by Kruxis** [comment]
Thanks for your report! 

The issue will be fixed on the next restart.

Safe Travels =)
