### ISSUE TITLE
Cursed Darkhound untameable

### ISSUE THREAD

**Issue by Rangtuk** [slowtorta/turtlewow-bug-tracker#693]
**Please, provide a clear description what the bug is:**
Using the spell "Tame Beast" on a Cursed Darkhound in Tirisfal, will undergo the entire tame duration (20s) before showing error text that the creature is untameable
**Steps to reproduce the behavior with as much detail as possible:**

1. Target Cursed Darkhound (possibly Decrepit one too)
2. Cast Tame Beast
3.  Don't have a darkhound as a pet (classified as Beast as of 1.16 so I dont wanna hear any comments its part of the UD hunter quest)

**IDs of affected creatures, items, quests or spells with a link to the relevant page:**

NPC: https://database.turtle-wow.org/?npc=
Item: https://database.turtle-wow.org/?item=
Quest: https://database.turtle-wow.org/?quest=
Spell: https://database.turtle-wow.org/?spell=
Object: https://database.turtle-wow.org/?object=

**Expected behavior. Describe how it should work:**
Darkhound should be a tameable beast or reclassified as a Demon (like the rare mob "Bayne" still is, side glitch report for you)

**Comment by Neto-WoW** [comment]
Fixed.
