### ISSUE TITLE
Zandozan in Org bug

### ISSUE THREAD

**Issue by Loon15** [slowtorta/turtlewow-bug-tracker#694]
**Please, provide a clear description what the bug is:**
Talking to Zandozan give the text Friendly with "."
**Steps to reproduce the behavior with as much detail as possible:**

1.Click on Zandozan
2. 
3. 

**IDs of affected creatures, items, quests or spells with a link to the relevant page:**

NPC: https://database.turtle-wow.org/?npc=Zandozan
Item: https://database.turtle-wow.org/?item=
Quest: https://database.turtle-wow.org/?quest=
Spell: https://database.turtle-wow.org/?spell=
Object: https://database.turtle-wow.org/?object=

**Expected behavior. Describe how it should work:**

**Comment by slowtorta** [comment]
Will be fixed in 1.16.1, thank you!
