### ISSUE TITLE
Orgrimmar To Ratchet Flight Broken

### ISSUE THREAD

**Issue by MDGitHubRepo** [slowtorta/turtlewow-bug-tracker#695]
**Please, provide a clear description what the bug is:**
When clicking Ratchet from the flight master in Orgrimmar an error comes up reporting 'UNSPECIFIED TAXI SERVER ERROR'
![image](https://user-images.githubusercontent.com/28200369/147719022-76bcd15e-eff1-4388-989c-2bd1f2a3dd28.png)

**Steps to reproduce the behavior with as much detail as possible:**
1. Go to Doras in Org
2. Select a flight to Ratchet
3. Error should occur 

**IDs of affected creatures, items, quests or spells with a link to the relevant page:**
n/a

**Expected behavior. Describe how it should work:**
Flight from org to ratchet should work without error.

**Comment by Tinyfin-github** [comment]
Greetings! This flight path has been temporarily dissabled until some issues are fixed.
