### ISSUE TITLE
Taxi Server Error: Flame Crest -> Grom'gol

### ISSUE THREAD

**Issue by avaruu** [slowtorta/turtlewow-bug-tracker#696]
The flight path from Flame Crest in Burning Steppes to Grom'gol in Stranglethorn Vale fails with an UNSPECIFIED TAXI SERVER ERROR message.

NPC: Vahgruk (Flame Crest, Burning Steppes)

![fc](https://user-images.githubusercontent.com/96836426/147720064-b24106b7-2961-465f-a876-5b944d938672.jpg)

**Comment by Tinyfin-github** [comment]
Greetings! This flight path has been temporarily dissabled until some issues are fixed.
