### ISSUE TITLE
Grammar in new quest Securing Darnassus

### ISSUE THREAD

**Issue by ahhh-reptar** [slowtorta/turtlewow-bug-tracker#699]
Here to fix some grammar stuff again.  

Wrong: "more active a threat then" - then should be than
Off/Wrong: "I had simply envisioned them as our ally to stand against whatever would come to bring harm to Teldrassil, not be fighting against them."  Very wordy, especially early on.  Also ally should be allies, because them refers to Furbolg, which isn't a specific (herein the Gnarlpine) group of Furbolg.    Maybe try something like, "I had envisioned them as our allies in the stand against whatever would bring harm to Teldrassil, not our enemies."

Wrong: "to keep traveller's safe" drop the apostrophe and put a comma after safe
Off:  "and stop the buildup of a much larger threat"  Buildup is kinda slangy and a little modern,  and this sentence is kinda long and wordy.  Maybe drop "of a much larger threat" and replace buildup with something like encroachment or advance, since we're talking about protecting our borders. 

Wrong: "to the south east" should be southeast
Off: "It shouldn't be long now until they are bold enough to begin" - wordy, action is buried (they are bold), too many vague words (it, they, etc.).  Wordiness can be easily remedied by using a comma to set off a prepositional statement, maybe try something like, "Before long, they will be bold enough to begin"
Wrong: "Dolanaar, or Shadowglen" remove the comma

Wrong: "Travel to Gnarlpine hold, and slay" remove the comma

**Comment by Kruxis** [comment]
Thanks for the Report, will be fixed on next server restart =)

Safe travels!
