### ISSUE TITLE
Hatchery Protection aka Father Flame aka Solakar Flamewreath Spawn Trigger Broken

### ISSUE THREAD

**Issue by Dragunovi** [slowtorta/turtlewow-bug-tracker#70]
**Please, provide a clear description what the bug is:**
Father Flame event stopped working entirely since the last restart, no guardians or boss spawn after the father flame is picked up.
**Steps to reproduce the behavior with as much detail as possible:**

1. Go to Upper Blackrock Spire
2. Pick up the Father Flame in the Hatchery.
3. Wait for something to happen

**IDs of affected creatures, items, quests or spells with a link to the relevant page:**

NPC: https://database.turtle-wow.org/?npc=10264
Object: https://database.turtle-wow.org/?object=175245
Object/NPC?: https://database.turtle-wow.org/?npc=160014

**Expected behavior. Describe how it should work:**
Picking up the Father Flame from the hatchery room should start an event where you fight waves of guardians and hatchers that end with Solakar Flamewreath itself coming to stop the party.

**Comment by Lunkdunk** [comment]
I remember our group couldnt start it after drakkisath was dead but yesterday we could start it prior to drakkisath and it worked.

**Comment by Nolin7777** [comment]
Unable to reproduce
