### ISSUE TITLE
Quest text for "A Secret Admirer" gives no information about where to find Shailea

### ISSUE THREAD

**Issue by rptb1** [slowtorta/turtlewow-bug-tracker#700]
**Please, provide a clear description what the bug is:**
The quest text for "A Secret Admirer" says to deliver a gift to Shailea "in Stormwind City", but unlike other quests gives no hint of where.  Stormwind is big and complex.

**Steps to reproduce the behavior with as much detail as possible:**

1. Take the quest "A Secret Admirer"
2. Travel to Stormwind
3. Try to locate Shailea

**IDs of affected creatures, items, quests or spells with a link to the relevant page:**

NPC: https://database.turtle-wow.org/?npc= *database offline*
Item: https://database.turtle-wow.org/?item= *database offline*
Quest: https://database.turtle-wow.org/?quest= *database offline*

**Expected behavior. Describe how it should work:**
The quest text should at least indicate which quarter to look in.

Also: quest text should say the name of the NPC you got the quest from originally.

**Comment by Kruxis** [comment]
After carefully reading i found out the quest DOES give a hint on the location.

Working as intended.

**Comment by zomgits** [comment]
I have figured out why this is confusing. It has a run-on sentence with an ambiguous subject.

> The quickest way to get to Stormwind would be from the Auberdine dock, a boat will take you there, she should reside in the park.

This is three separate sentences with two subjects, but spliced together with commas.  Boats are called "she" and the boats go to near the park.

I suggest: "The quickest way to get to Stormwind is by boat from the Auberdine dock. Shailiea resides in the park."

**Comment by Kruxis** [comment]
Hm...

I will look into it and see if i can improve the wording.
