### ISSUE TITLE
A Cannon's Misfortune

### ISSUE THREAD

**Issue by Claboth** [slowtorta/turtlewow-bug-tracker#702]
**Please, provide a clear description what the bug is:**
The npc gives you 'Special Water' to pour into blasting powder kegs, found around Booty Bay. There is no interaction possible with either the quest item or the kegs with an activation wheel. 
**Steps to reproduce the behavior with as much detail as possible:**

1. Either provide an activation wheel when doing a mouseover on the kegs.
2. Allow the quest item to be dragged into the action bar and make it an 'use' item.
3. 

**IDs of affected creatures, items, quests or spells with a link to the relevant page:**
Database is currently disabled. Cannot add links.
NPC: https://database.turtle-wow.org/?npc=
Item: https://database.turtle-wow.org/?item=
Quest: https://database.turtle-wow.org/?quest=
Spell: https://database.turtle-wow.org/?spell=
Object: https://database.turtle-wow.org/?object=

**Expected behavior. Describe how it should work:**
Right-click on any key available until the required number is reached to complete the quest.

**Comment by Gurky-Kronos** [comment]
The barrels for this are not interactable or the item he gives is not useable.

**Comment by Claboth** [comment]
STill not working. The activation wheel is present on the kegs. you get a message: 'this seems like one of the kegs we need to ...' but nothing happens towards the progress of finishing the quest.

**Comment by Gurky-Kronos** [comment]
try clearing WDB and also retaking the quest. I completed mine and only got
that message when trying to use the same barrel more than once. (Maybe
someone else used it?)

P.s. you might want to wait on this until they fix
https://github.com/slowtorta/turtlewow-bug-tracker/issues/772 you cant go
back to Booty bay without this quest and it doesn't work.
