### ISSUE TITLE
Loch Threshadons chase you on to the land

### ISSUE THREAD

**Issue by rptb1** [slowtorta/turtlewow-bug-tracker#705]
**Please, provide a clear description what the bug is:**
Loch Threshadons in Loch Modan will chase you on to the land, apparently hovering in the air using their flippers!

**Steps to reproduce the behavior with as much detail as possible:**

1. Go to Loch Modan and swim in the loch.
2. Aggro a threshadon.
3. Attempt to escape on to the south island.
4. Threshadon hovers over the ground.

**IDs of affected creatures, items, quests or spells with a link to the relevant page:**

NPC: https://database.turtle-wow.org/?npc= *database offline*

**Expected behavior. Describe how it should work:**
Threshadons should behave like e.g. Loch Frenzy fish, and stop at the waters edge.

**Comment by slowtorta** [comment]
This will be fixed on the next update.
