### ISSUE TITLE
Water splashes loop endlessly (client side)

### ISSUE THREAD

**Issue by bakemeat** [slowtorta/turtlewow-bug-tracker#706]
**Please, provide a clear description what the bug is:**

When walking over shallow water, splashing animation appears. The animation doesn't stop looping, creating phantom splashes that stay on the water where the player has gone across. 
This is purely a visual bug affecting only the client side, not the server (splashes of other players aren't visible). With enough splashes on screen, the FPS drops, but that's about it. The splashes disappear when the player leaves the visual range of them.

**Steps to reproduce the behavior with as much detail as possible:**

1. Noticed this when walking across shallow water before.
2. Attempted to create a circle of white using splashes just for fun (successful, see image below)

**IDs of affected creatures, items, quests or spells with a link to the relevant page:**

No affected items

**Expected behavior. Describe how it should work:**

Splashing animation should disappear after 1 loop I'm guessing.

Image below shows what the result is of walking in circles on water for an extended period of time looks like.

![image](https://user-images.githubusercontent.com/91905839/147758108-9241ed61-fb64-4b39-9160-983dd49526eb.png)

**Comment by bakemeat** [comment]
Correction: The looping splashes are also seen by players within range, which means it can cause FPS lag for both parties.

**Comment by slowtorta** [comment]
Fixed in 1.16.1.
