### ISSUE TITLE
Quest "The Deserters", NPC at the wrong place.

### ISSUE THREAD

**Issue by Radiesler** [slowtorta/turtlewow-bug-tracker#707]
The Quest-NPC "Balos Jacken" for the quest "The Deserters" is bugged.
He shoudn't be standing in Theramore (65.0/47.8), but here, at Lost Point (35.9/45.0)

Right now he is standing in Theramore, but you cant interact with him.

**Comment by Tinyfin-github** [comment]
Issue in the vein of #336 

The npc was fixed for now.
