### ISSUE TITLE
Paladin Anticipation Talent

### ISSUE THREAD

**Issue by Raptor6D** [slowtorta/turtlewow-bug-tracker#708]
**Please, provide a clear description what the bug is:**

The Anticipation Talent in the Paladin Tree doesn't allow the Defense to increase beyond 300 to 310.

**Steps to reproduce the behavior with as much detail as possible:**

1.
2. 
3. 

**IDs of affected creatures, items, quests or spells with a link to the relevant page:**

NPC: https://database.turtle-wow.org/?npc=
Item: https://database.turtle-wow.org/?item=
Quest: https://database.turtle-wow.org/?quest=
Spell: https://database.turtle-wow.org/?spell=
Object: https://database.turtle-wow.org/?object=

**Expected behavior. Describe how it should work:**

**Comment by Nolin7777** [comment]
![0](https://user-images.githubusercontent.com/20132236/157676928-10f94fd1-1296-4644-8bdd-5d66b979e048.png)
![2](https://user-images.githubusercontent.com/20132236/157676934-65697a81-e7c5-4492-b5fb-97f2749a53b6.png)

**Comment by geojak** [comment]
https://forum.turtle-wow.org/viewtopic.php?f=3&t=2969&p=18468&sid=572c9653b8c007e74052884cb0424ec4#p18468

Warrior seem also Affected

**Comment by geojak** [comment]
@Nolin7777 could you check the forum post out? There seems to be a remaining issue

**Comment by Xerrash** [comment]
Could it be that it bugs out if you are not already max defense? It happened on my level 35 warrior while levelling.

**Comment by JKendall3rd** [comment]
I am having this exact same issue. I am in game while I type this post, having 3 wolves attack me repeatedly, and I am stuck at 210/218. Who said this couldn't be reproduced? Just make a Paladin and skill Anticipation and then let things hit you for 500 hours.

**Comment by redmagejoe** [comment]
Now level 49. It took me 13 whole minutes to get from 244 to 245 defense with 5 level 1 wolves attacking me the entire time. As such, I cannot confirm that the curve for skill gain isn't just absolutely obscene, but I'm standing here letting these wolves continue to hit me to see if I can clear the 245/255 threshold. Having +defense gear (green numbers) on or off doesn't seem to have any bearing.

**Comment by redmagejoe** [comment]
As of the last restart, this has been fixed. Please mark as fixed and closed.

**Comment by geojak** [comment]
@Velite12 you are a dev now laughadin? would be amazing news for #paladin
