### ISSUE TITLE
Serpentbloom Hitbox Broken

### ISSUE THREAD

**Issue by Dragunovi** [slowtorta/turtlewow-bug-tracker#71]
**Please, provide a clear description what the bug is:**
Serpentbloom hitboxes are pretty messed up, it takes like 1-2 minutes just to get the proper angle to click and collect the flowers.
**Steps to reproduce the behavior with as much detail as possible:**

1. Take one of the Serpentbloom quests.
2. Go to Wailing Caverns.
3. Try to collect the flowers.
4. suffer

**IDs of affected creatures, items, quests or spells with a link to the relevant page:**

Object: https://database.turtle-wow.org/?object=19535

**Expected behavior. Describe how it should work:**
You should be able to click and collect them without having to use weird angle witchery.

**Comment by slowtorta** [comment]
Wrong. The correct object is this one: https://database.turtle-wow.org/?object=13891 Tested, no problems.
