### ISSUE TITLE
dust devils not patrilling in westfall

### ISSUE THREAD

**Issue by geojak** [slowtorta/turtlewow-bug-tracker#714]
**Please, provide a clear description what the bug is:**

the dust devil elementals in westfall are spoosed to patrol and roam instead of standing around their local spawn point

**Steps to reproduce the behavior with as much detail as possible:**

1. go to westfall
2. find a dust devil
3. observe they dont move around much

**IDs of affected creatures, items, quests or spells with a link to the relevant page:**

NPC: https://database.turtle-wow.org/?npc=
Item: https://database.turtle-wow.org/?item=
Quest: https://database.turtle-wow.org/?quest=
Spell: https://database.turtle-wow.org/?spell=
Object: https://database.turtle-wow.org/?object=

**Expected behavior. Describe how it should work:**

dust devils in classic are always roaming around killing lowbies

**Comment by slowtorta** [comment]
Fixed on the next update.
