### ISSUE TITLE
Broken spear quest wont start.

### ISSUE THREAD

**Issue by Crableth** [slowtorta/turtlewow-bug-tracker#715]
**Please, provide a clear description what the bug is:**
Got the item Broken Spear from a mob, says it should start a quest, but i dont have the requeriment. The requirement says it needs to be lvl 27, and im 47.

**Steps to reproduce the behavior with as much detail as possible:**

1. Clicking on the item wont start the quest
2. Error message says i dont have the requirements

**Expected behavior. Describe how it should work:**
It should be able to start the quest with no problems

**Comment by Tinyfin-github** [comment]
Greetings! I  have checked and i have been unable to find any issues with quest.

Please make sure you have completed the pre required quest chain.  You need to complete "Norvok of the Spear" to be able to use the item.
