### ISSUE TITLE
"." reputation gain from quest "For Love Eternal" in Darkshore

### ISSUE THREAD

**Issue by tubtubs** [slowtorta/turtlewow-bug-tracker#717]
**Please, provide a clear description what the bug is:**

**Steps to reproduce the behavior with as much detail as possible:**

1. Complete quest "For Love Eternal" in Darkshore. (https://classic.wowhead.com/quest=963/for-love-eternal)
2. Receive reputation with the reputation "."
3. The reputation gain doesn't show up in my chat log, but then a strange new reputation shows with 300 rep into friendly

**IDs of affected creatures, items, quests or spells with a link to the relevant page:**

NPC: https://database.turtle-wow.org/?npc=
Item: https://database.turtle-wow.org/?item=
Quest: https://database.turtle-wow.org/?quest=963
Spell: https://database.turtle-wow.org/?spell=
Object: https://database.turtle-wow.org/?object=

**Expected behavior. Describe how it should work:**
As far as I can tell, I received the expected 75 Darnassus rep gain (82 because human)
The only odd occurrence is the "." reputation.

![For Love Eternal Odd Rep Gain](https://user-images.githubusercontent.com/96892771/147793628-92000ae7-e518-49e9-b817-d95c47fabe59.png)
.

**Comment by Kruxis** [comment]
![image](https://user-images.githubusercontent.com/32237664/149017821-275cf4f5-bdbc-4f34-8d98-cc4b24ae4a00.png)
The quest does give points for Darnassus. 

Try deleting your WDB folder =)
