### ISSUE TITLE
Horse Hoof Sounds Not Playing

### ISSUE THREAD

**Issue by Thaddian** [slowtorta/turtlewow-bug-tracker#720]
The hoof sounds from your horse mount will not play at all.

1. Turn off your music.
2. Mount your horse.
3. Hear nothing but your armor foley sounds as you move.

The way it's supposed to work is that you can hear hoof sounds coming from your horse as you move on it. It might've been hard to notice before, but if you were to replace the sounds with something louder, you'd be able to hear it. Unfortunately, it seems the new patch release disabled them.

**Comment by pypaut** [comment]
Same thing with my Black Ram, and another character's (I asked another ram owner in game).
