### ISSUE TITLE
WANTED: Murkdeep quest: Murkdeep doesn't spawn

### ISSUE THREAD

**Issue by mybrid** [slowtorta/turtlewow-bug-tracker#721]
The WANTED: Murkdeep quest will spawn a group of murlocs that include Murkdeep once the hovel of murlocs is cleared. I cleared the hovel three times. The first time nothing spawned. The second time and the third time a group of murlocs came from the ocean as expected but Murkdeep was not with them. 

**Steps to reproduce the behavior with as much detail as possible:**

1. Go to Darkshore coast at the norhern most Murloc hovel on the beach. 
2. Kill all the murlocs at the hovel. 
3. Either nothing will spawn from the ocean or  a group of murloc warriers spawn, but no Murkdeep. 

**IDs of affected creatures, items, quests or spells with a link to the relevant page:**
https://www.wowhead.com/npc=10323/murkdeep
NPC: https://database.turtle-wow.org/?npc=1023
Quest: https://database.turtle-wow.org/?quest=4740
https://www.wowhead.com/quest=4740/wanted-murkdeep

**Expected behavior. Describe how it should work:**
See steps to reproduce.

**Comment by Gasan918** [comment]
To spawn mobs you need to stand right at the center of murloc camp. I think TWOW team could widen the scrit area a bit.

**Comment by slowtorta** [comment]
Sorry, this one is working as intended, couldn't reproduce it. The range is reasonably wide at the moment.
