### ISSUE TITLE
Crescent Grove: Can't exit dungeon while in combat.

### ISSUE THREAD

**Issue by Aeliren** [slowtorta/turtlewow-bug-tracker#722]
I could not exit the new dungeon "The Crescent Grove" in Ashenvale without leaving combat, which happened as I was attempting to leave the dungeon on foot after killing the final boss. As I was playing on a hunter, I was able to feign death while on the edge of the instance portal, which allowed me to exit, but my priest party member was unable to exit the dungeon and died.

Steps to reproduce:

1. Enter the Crescent Grove dungeon.
2. Enter combat.
3. Attempt to exit the dungeon while still in combat.

The database is currently still offline, so I cannot link anything at the moment.

Expected behavior: I should be able to exit an instance regardless of my combat status.

**Comment by slowtorta** [comment]
This is an intended behavior.

**Comment by Aeliren** [comment]
May I ask the reason why it is intended? I'm more than a little confused, as to my knowledge you've always been able to exit an instance even while in combat.
