### ISSUE TITLE
Snowball Wars quest bug: throwing at self

### ISSUE THREAD

**Issue by TrangOul** [slowtorta/turtlewow-bug-tracker#725]
**Please, provide a clear description what the bug is:**

The objective of Snowball Wars quests is to throw a snowball at each class (except Rogue - another bug?).
The objective is completed when a snowball is thrown at self.

**Steps to reproduce the behavior with as much detail as possible:**

1. Start Snowball Wars: Episode I (quest=50319) or Snowball Wars: Episode II (quest=50320) quests from Mr. Mistletoe (npc=50654).
1. Purchase Weird Snowball (item=51058) or Snowball from Quark (npc=50653).
1. Target self (F1).
1. Use either Weird Snowball or Snowball.

**Expected behavior. Describe how it should work:**

Throwing a snowball at self does not fulfill the objective of throwing at self's class. You have to target another player character.
Actually, throwing at self should not be possible at all.

**Comment by slowtorta** [comment]
That's an intended funny perk.
