### ISSUE TITLE
Guards in capital cities do not give directions to new class trainers

### ISSUE THREAD

**Issue by TrangOul** [slowtorta/turtlewow-bug-tracker#726]
**Please, provide a clear description what the bug is:**

Guards (Abominations) in Undercity provide directions to class trainers - except Hunter, which is a new class for Undead.
I did not check that, but it is possible that Ironforge guards know nothing about Mage trainers.

**Steps to reproduce the behavior with as much detail as possible:**

1. Create a character with a new race/class combination (Undead Hunter or Dwarf Mage).
1. Go to the capital city - Undercity or Ironforge respectively.
1. Talk to Undercity Guardian or Ironforge Guard and ask about class trainers.

**Expected behavior. Describe how it should work:**

Guards give directions to all class trainers, including newly introduced ones.

**Comment by Dormilon** [comment]
Mark for hunter trainer in Undercity added. Mark in Ironforge for mages workes
