### ISSUE TITLE
Quest "What the Wind Carries" doesn't work.

### ISSUE THREAD

**Issue by MagnusKC** [slowtorta/turtlewow-bug-tracker#728]
**Please, provide a clear description what the bug is:**

**Steps to reproduce the behavior with as much detail as possible:**

1. Accept the quest "What the Wind Carries" from Thrall.
2. Sit down.
3. Interact with Thrall.

Expected behavior: Thrall gives a dialog option to listen to his tale.
Actual behavior: There is no such option.

**Comment by Gurky-Kronos** [comment]
I have run into this as well, please keep in mind Horde cannot get attuned with Onyxia due to this bug.
