### ISSUE TITLE
Race Changed - Can no longer res at Graveyard

### ISSUE THREAD

**Issue by Rakura1** [slowtorta/turtlewow-bug-tracker#729]
**Please, provide a clear description what the bug is:**
When in game and especially in battlegrounds after race change the only way to ressurect is to find my body and res there or be res'd by a player. Should my pvp tag be taken I am permanently stuck in perma death and the only way to res at that point is to be moved to another instance of the game ie round ends or I accept another bg q.
**Steps to reproduce the behavior with as much detail as possible:**

1. Create a character
2. Race change to another race ie Tauren to Night Elf
3. Go into a battleground or trigger a world event that causes death
4. Try to res at graveyard
5. Try to res at body
6. Have pvp tag taken and try to res

**Expected behavior. Describe how it should work:**
On death player should be able to res at graveyard to continue play
On death player should be able to release body (this doesn't happen all the time)
![cap1](https://user-images.githubusercontent.com/90916104/147826067-add5cd1f-2848-4ba5-9077-27e2d3695e73.png)
![cap2](https://user-images.githubusercontent.com/90916104/147826082-d532e189-f3e3-41d0-84ad-46f84d4c26fa.png)
![cap5](https://user-images.githubusercontent.com/90916104/147826792-ad248f33-b833-4cf2-9c2f-a9ebd6d9adba.PNG)
![cap6](https://user-images.githubusercontent.com/90916104/147827597-5bade204-c9f3-433b-8a3c-2b299d332baf.PNG)

**Comment by Rakura1** [comment]
Tried dying in world and then ressurecting at graveyward. while I was able to res it did not change any thing when a battleground.

**Comment by Rakura1** [comment]
Everytime I log in i get this error. I believe it is related to my titles as previously stated.
![image](https://user-images.githubusercontent.com/90916104/148861256-c6c09d53-231b-4489-a722-23837fc359ee.png)

**Comment by geojak** [comment]
i got that error too, and i am just lvl 42 highelf leveling. i dont thing that error is related

**Comment by Rakura1** [comment]
Had devs remove tags and cleared WDB folder today. A server restart may shock the system but just client side ot server side communication removing tags did not fix the issue as hypothesised.

Problem remains game still believes I'm on both sides of the fence at the same time adn will not let me res.
![image](https://user-images.githubusercontent.com/90916104/149636947-b4a6f342-9930-491c-a85b-a31a9c7308a8.png)

**Comment by Rakura1** [comment]
Issue was fixed by turning off at war with "other" reputation.
![image](https://user-images.githubusercontent.com/90916104/151625341-17e2a342-c3c4-49b7-9085-4c2559ab7c4a.png)

**Comment by littletoads** [comment]
Was there another fix for this my other tab doesnt look like urags
![Screenshot (4)](https://user-images.githubusercontent.com/72800555/152173011-7d5e2cbc-3166-4b02-a822-bd08e29a4975.png)
?
