### ISSUE TITLE
Buru the Gorger Aggro Table

### ISSUE THREAD

**Issue by Dragunovi** [slowtorta/turtlewow-bug-tracker#73]
**Please, provide a clear description what the bug is:**
Buru the Gorger's script seems more angry and started chasing people that wasn't her original fixate target when overaggroed. This should not happen as the purpose of the fight is for the **random** fixated target to kite her towards an egg and blow it up when she's near it, damaging her, spawning an add and changing her fixate target, with an aggro table present a tank can get her aggro and kite it with every egg explosion, making the fight more trivial.
**Steps to reproduce the behavior with as much detail as possible:**

1. Go to Ruins of Ahn'Qiraj
2. Bring multiple player characters with you and engage Buru the Gorger.
3. Someone that's not fixated by Buru uses high aggro abilities to pull the mob off.

**IDs of affected creatures, items, quests or spells with a link to the relevant page:**

NPC: https://database.turtle-wow.org/?npc=15370

**Expected behavior. Describe how it should work:**
Buru the Gorger should ignore any damage and aggro source and chase her fixated target regardless of outside input.

**Comment by Nolin7777** [comment]
Should be fixed at next update
