### ISSUE TITLE
Transmog Issue for Mystic's Robe

### ISSUE THREAD

**Issue by inxdigo** [slowtorta/turtlewow-bug-tracker#734]
I'm unable to transmog mystic's robe onto my cloth chest (my character is a mage). I own it, it's been equipped, and the message "Mystic's Robe has been added to your collection" was displayed after I equipped it. However it doesn't appear as an option in the transmog window.
![Cant_Transmog_Mystic's_Robe](https://user-images.githubusercontent.com/74259373/147843279-b5d2d8da-0dbe-4713-8440-2f65faba5383.png)

**Comment by CosminPOP** [comment]
Game has two different categories for chest items: chest (like vests or chests that a warrior use, torso items) and robes (that go over your legs too). Currently Transmog tries to match 1:1 so that's why you're not seeing a robe when you have a vest equipped. It may be changed in a future update.
