### ISSUE TITLE
Quest: Gnoll Bounty not allowing turn in

### ISSUE THREAD

**Issue by trihard711** [slowtorta/turtlewow-bug-tracker#736]
**Please, provide a clear description what the bug is:**

In the quest log for Gnoll Bounty, you can end up overdoing the quest and it can show that you killed 15/10 runts. Also when you get to the turn in NPC, it wont allow turn in even though all objectives are complete.

**Steps to reproduce the behavior with as much detail as possible:**

1. Kill more gnolls then required
2. Head to NPC named Supervisor Raelen.
![Screenshot (12)](https://user-images.githubusercontent.com/96794610/147845540-c18fa197-8aa2-4937-a0cc-e9e6528f30f5.png)

**IDs of affected creatures, items, quests or spells with a link to the relevant page:**

DB is disabled

**Expected behavior. Describe how it should work:**

The counter for gnolls killed should not go over the amount needed and you should be able to turn in the quest.

**Comment by Tinyfin-github** [comment]
Greetings! Please clear your WDB folder while the game is closed to see the correct kill count."
