### ISSUE TITLE
[Hunter] Hunter: Pet Training

### ISSUE THREAD

**Issue by Entrix22** [slowtorta/turtlewow-bug-tracker#739]
**Training pet doesnt consume training points when using Beast Training**

**Steps to reproduce the behavior with as much detail as possible:**

1. Untrain pet at pet trainer. 
2. Use Beast Training ability.
3. Train pet without consuming training points.

**Used wowhead links since turtle wow database is down**

NPC: https://classic.wowhead.com/npc=10089/silvaria
Spell: https://classic.wowhead.com/spell=5149/beast-training
Pet used: https://classic.wowhead.com/npc=2850/broken-tooth

**Training a pet should consume training points.**

**Comment by Velite12** [comment]
Can confirm this is still present.

![image](https://user-images.githubusercontent.com/45871932/192031270-25c7265e-f3c7-4ac1-97f7-cae621a0c5a1.png)
