### ISSUE TITLE
Problems with goblin female models

### ISSUE THREAD

**Issue by Notawen** [slowtorta/turtlewow-bug-tracker#742]
- The "Features" button doesn't do anything in the character creation menu.
- The damage sounds are of the male version.
- The tools in the mining/hammering animation need to be rotated by 90 degree.
- Face clips through  masks/bandannas.

**Comment by jlautenbach** [comment]
Would like to add: 

Esras — Today at 10:56 AM
is the hairbase you can see beneath most of the "pulled back" female goblin hairstyle something that is planned to be fixed in a future update?

@slowtorta or would this better fit a seperate issue for on the list?
