### ISSUE TITLE
Quest "The Master's Glaive" cannot be completed

### ISSUE THREAD

**Issue by SaxxonPike** [slowtorta/turtlewow-bug-tracker#744]
**Please, provide a clear description what the bug is:**

The quest, "The Master's Glaive", does not register when you enter the zone called The Master's Glaive in Darkshore. Entering the area is all that is required to complete the objective.

**Steps to reproduce the behavior with as much detail as possible:**

1. Accept "The Master's Glaive".
2. Go to the area in Darkshore called The Master's Glaive.
3. Observe that no credit is given for entering the area.

**IDs of affected creatures, items, quests or spells with a link to the relevant page:**

The database is currently disabled due to the new content release.

**Expected behavior. Describe how it should work:**
You should just be able to enter the area, complete the objective by doing so, then use the "Phial of Scrying" to complete the quest.

**Comment by pypaut** [comment]
Hello, I was able to complete the quest, though it was not obvious when it actually worked.

I suggest you try completing the escort quest in this area, and then check "The Master's Glaive" objective.

**Comment by rptb1** [comment]
I think there is a minor problem here.  The area that triggers the quest as completed is not where I expected either.  I had to walk around to the back of the glaive, and it didn't work right at the shrine, where you'd expect.
