### ISSUE TITLE
Boat drops the player into the ocean

### ISSUE THREAD

**Issue by mikefirefly** [slowtorta/turtlewow-bug-tracker#745]
**Please, provide a clear description what the bug is:**
Boat from Darkshore to Stormwind very often drops the player into the ocean.

**Steps to reproduce the behavior with as much detail as possible:**

1. Get on the elven boat from Darkshore to Stormwind Harbor.
2. Upon screen transition, very often (currently it happened to me 3 times out of 5 journeys) you will end up in the ocean. This is extremely scary since even with Aspect of the Cheetah it is JUST enough time to reach safe waters and not die due to fatigue. I don't think any other class can do it - the only escape is Hearthstone (if you have it available).

**Expected behavior. Describe how it should work:**
Player should be still on the boat.

**Comment by zomgits** [comment]
There are regular reports of this problem in Stay Alive chat. Even today.

**Comment by zomgits** [comment]
Just now.
![image](https://user-images.githubusercontent.com/97355053/149655794-8ee51e3b-b881-45fc-89cf-2fd021bdb03d.png)

**Comment by Mosch0512** [comment]
Just want to know why this is closed this is something still happening? @slowtorta 
![grafik](https://github.com/slowtorta/turtlewow-bug-tracker/assets/48485443/a1bdc1c9-91b3-4bda-b428-e32fbdbbd523)
