### ISSUE TITLE
Azshara Quest: The Rethress Tide Scepter - No Quest Object

### ISSUE THREAD

**Issue by Valamartle** [slowtorta/turtlewow-bug-tracker#746]
**Please, provide a clear description what the bug is:**
Part of the Rethress Sanctum Chain- You are sent up to the Tower of Eldara and to search for a buried Scepter which is supposedly buried by 4 rocks. There's a couple rock areas that fit the description but no quest object on any shore at all. 
**Steps to reproduce the behavior with as much detail as possible:**

1.Accept Quest: The Rethress Tidal Scepter
2. Go to the area denoted in the quest.
3. The Quest Object does not appear to be anywhere on the map. 

**IDs of affected creatures, items, quests or spells with a link to the relevant page:**

Database is currently down.

**Expected behavior. Describe how it should work:**
I'm presuming there should be a dirt pile or possibly many where you have to try and find the buried scepter.

**Comment by slowtorta** [comment]
This quest is working as intended: https://database.turtle-wow.org/?object=2010808
