### ISSUE TITLE
Azshara Quest: A Broken Oath - Quest Item is not dropping. 

### ISSUE THREAD

**Issue by Valamartle** [slowtorta/turtlewow-bug-tracker#748]
**Please, provide a clear description what the bug is:**
There are Spitelash Myrmidon wandering around the shores east of Eldarath, they should be dropping Myrmidon Signets for this quest but they are not. 
**Steps to reproduce the behavior with as much detail as possible:**

1.Accept Quest: A Broken Oath
2. Hunt Spitelash Myrmidon on Shattered Strand and Southridge Beach
3. They do not appear to be dropping their Signets

**IDs of affected creatures, items, quests or spells with a link to the relevant page:**

NPC: https://database.turtle-wow.org/?npc=Spitelash_Myrmidon
(guess, as db is down for launch )

**Expected behavior. Describe how it should work:**
The myrmidons should be dropping Signets for the quest.

**Comment by Tinyfin-github** [comment]
#653
