### ISSUE TITLE
Anubisath Guardian Adds

### ISSUE THREAD

**Issue by Dragunovi** [slowtorta/turtlewow-bug-tracker#75]
**Please, provide a clear description what the bug is:**
Anubisath Guardians keep spawning adds from their corpses even after death, making obsidian chunk mining quite tedious, and the adds can catch your raid by surprise and cleave your caster group while you're fighting another guardian.
**Steps to reproduce the behavior with as much detail as possible:**

1. Go to Ruins of Ahn'Qiraj.
2. Kill one of the Anubisath Guardians.
3. Stay near his corpse and wait for adds to spawn.

**IDs of affected creatures, items, quests or spells with a link to the relevant page:**

NPC: https://database.turtle-wow.org/?npc=15355

**Expected behavior. Describe how it should work:**
Anubisath Guardians should stop spawning adds from their corpses after slain.

**Comment by Nolin7777** [comment]
Fixed after next update.
