### ISSUE TITLE
Apostrophe catastrophe in "Help the League?"

### ISSUE THREAD

**Issue by rptb1** [slowtorta/turtlewow-bug-tracker#750]
**Please, provide a clear description what the bug is:**
The quest "Help the League?" has uses an apostrophe in a plural: "egg's" instead of "eggs".

**Steps to reproduce the behavior with as much detail as possible:**

1. Take the quest "Help the League?" from Merrin Rockweaver.
2. Read the quest text.
3. Become triggered by the punctuation.

**IDs of affected creatures, items, quests or spells with a link to the relevant page:**

NPC: https://database.turtle-wow.org/?npc=1076
Quest: https://database.turtle-wow.org/?quest= *database offline*

**Expected behavior. Describe how it should work:**
https://www.youtube.com/watch?v=8Gv0H-vPoDc

Seriously guys thank you for the new content!

**Comment by Kruxis** [comment]
Thanks for your report! 

The issue will be fixed on the next restart.

Safe Travels =)

**Comment by Kruxis** [comment]
Should be fixed, please go to your WoW-Directory and delete the WDB folder. 

If it still doesn't work, i'll fix the issue

**Comment by zomgits** [comment]
Please take this in the right spirit, but have you, yourself, tested this fix?  This isn't the only text issue that I've submitted that has claimed to be fixed but isn't (see https://github.com/slowtorta/turtlewow-bug-tracker/issues/872).  Clearly some fixes aren't getting to the players.  I'd like to help you guys improve your bug fix process.  In project I've worked on, issues can only be closed when they've been confirmed to be fixed, usually by a third party.  I suspect you're closing them at the stage of "I did something to fix this".  I know you're not an AAA team (thank goodness) but I'd like to save you from being overwhelmed by regressions.

I don't even have a writeable WDB, as [per your instructions](https://forum.turtle-wow.org/viewtopic.php?f=18&t=539&sid=704d499d8dc55de4498b1285c332e690).

Many thanks. <3

**Comment by Kruxis** [comment]
Hm. I don't like it when my fixes don't get pushed from test to Live. 

Thanks for notifying

**Comment by zomgits** [comment]
So maybe a step in your process where fixes are verified on live at some point?  Depends what went wrong here of course.  I have no idea how your staging works.  All the best!

**Comment by Kruxis** [comment]
This time it should be fixed on server reset.
