### ISSUE TITLE
"You are now friendly with ." (Darnassus, "Escape Through Force" -> Senteniel Selarin -> "Trek to Ashenvale")

### ISSUE THREAD

**Issue by Gasan918** [slowtorta/turtlewow-bug-tracker#751]
**Please, provide a clear description what the bug is:**

When you talk to Senteniel Selarin, but not accept "Trek to Ashenvale" quest, you become friendly with unkonwn faction/group. 
(Have deleted WDB. Still have this rep in my tab.)

**Steps to reproduce the behavior with as much detail as possible:**

1. Finish "Escape Through Force" quest
2. Wait for Senteniel Selarin to come near
3. Talk to Senteniel Selarin, do not take "Trek to Ashenvale" quest
4. Check chat window message "You are now friendly with ." (or Reputation tab. It will show empty bar in "Other")

**IDs of affected creatures, items, quests or spells with a link to the relevant page:**

NPC: https://database.turtle-wow.org/?npc=3694 (wowhead, because your db is offline now)
Item: https://database.turtle-wow.org/?item=
Quest: https://database.turtle-wow.org/?quest=995, 990 (wowhead)
Spell: https://database.turtle-wow.org/?spell=
Object: https://database.turtle-wow.org/?object=

**Expected behavior. Describe how it should work:**
Some rep with Darnassus maybe.

**Comment by slowtorta** [comment]
Will be fixed in 1.16.1
