### ISSUE TITLE
Appealing to the Alliance Dialogue - Mekkatorque

### ISSUE THREAD

**Issue by inxdigo** [slowtorta/turtlewow-bug-tracker#753]
I don't know if this is deliberate but 'empathize' is spelled 'emphasise' in Mekkatorque's dialogue after you get the letter from him. Screenshot shows his dialogue in the text log (missed screencapping it the moment he said it)
![Appealing _to_the_alliance_Mekkatorque](https://user-images.githubusercontent.com/74259373/147880295-d2708bbf-c513-4064-87e5-d1270da41aa4.png)

**Comment by geojak** [comment]
This Dialog was avaible to me without I having the quest yet. So I had one reply already when I got the quest without even having the 3 provided blank papers in the bag
