### ISSUE TITLE
Fashion Demands Sacrifices (lvl 20) - Quest log still shows wrong requirements

### ISSUE THREAD

**Issue by inxdigo** [slowtorta/turtlewow-bug-tracker#754]
In the quest log, Fashion Demands Sacrifices still shows the requirements "20 wool cloth, 10 Medium Leather, 10 Shadows gems, and 5 Small Furry Paw". It should specify 5 of each to match the requirements.

She also refers to herself as a Goblin in the quest description 

![Fashion_Demands_sacrifice_lvl20](https://user-images.githubusercontent.com/74259373/147880465-04a106b7-1dff-4139-87b4-e1477c4ed3aa.gif)

**Comment by slowtorta** [comment]
This has been fixed a few days ago. Please clear your WDB folder.
