### ISSUE TITLE
Inn not working at Sparkwater Port

### ISSUE THREAD

**Issue by serranoble** [slowtorta/turtlewow-bug-tracker#755]
**Please, provide a clear description what the bug is:**
After you enter into Sparkwater Port Inn, resting mode is not enabled.

**Steps to reproduce the behavior with as much detail as possible:**

1. Enter into Sparkwater Port Inn
2. Wait for resting mode enabled
3. Nothing happens

**Expected behavior. Describe how it should work:**
After your character enters into the Inn, the resting mode must trigger allowing to you to logout and reflecting this state as "ZZZ" over your level bubble inside your avatar image. None of these actions are happening

**Comment by nobodyinteresting** [comment]
Inn also doesn't work in Steepcliff Port in Tirisfal Uplands. Has an innkeeper but no rest bonus.

**Comment by zomgits** [comment]
Shimmering Flats also.

**Comment by slowtorta** [comment]
Fixed in 1.16.1.
