### ISSUE TITLE
See through stormwind

### ISSUE THREAD

**Issue by LeeJoint** [slowtorta/turtlewow-bug-tracker#758]
**Please, provide a clear description what the bug is:**

**Steps to reproduce the behavior with as much detail as possible:**

1. Find the right angle in the tunnel from dwarven district canals to old town, maye can be done in other tunnels?
2. 
3. 

**IDs of affected creatures, items, quests or spells with a link to the relevant page:**

NPC: https://database.turtle-wow.org/?npc=
Item: https://database.turtle-wow.org/?item=
Quest: https://database.turtle-wow.org/?quest=
Spell: https://database.turtle-wow.org/?spell=
Object: https://database.turtle-wow.org/?object=

**Expected behavior. Describe how it should work:**

No see through
![image](https://user-images.githubusercontent.com/96999031/147889319-e59a48a9-2704-46d4-aa2c-35fa0f35679e.png)

**Comment by slowtorta** [comment]
We cannot fix it, sorry.
