### ISSUE TITLE
Quest: The Maul'ogg Crisis (Part VII)

### ISSUE THREAD

**Issue by gorxen** [slowtorta/turtlewow-bug-tracker#759]
**Please, provide a clear description what the bug is:**

Quest: **The Maul'ogg Crisis (Part VII)**

This is a new quest in Kazon Island, it asks for an "Atal'ai Rod" from boss Jammal'an in Sunken Temple. the quest text says "It should be kept close from where this troll channels his magic". Well I spent around 10 minutes looking for it all over the room where he spawns and it was nowhere to be found, nor did he himself dropped it. So I just want confirmation that it is indeed working and not just me sucking at finding quest items. thanks.

**Expected behavior. Describe how it should work:**

The Rod should be easily accessible or at least visible enough for us to be able to loot it.

**Comment by Avery1337** [comment]
I can confirm that this is happening to me as well I killed Jammal'an Prophet but didnt get anything and looked inside the room to find nothing. I even killed erenkus believing that maybe he unlocks some secret of getting the staff but nothing.
