### ISSUE TITLE
Warsong Saw Blades Doesn't Remove Blunderbuss

### ISSUE THREAD

**Issue by Dragunovi** [slowtorta/turtlewow-bug-tracker#76]
**Please, provide a clear description what the bug is:**
Completion of [Warsong Saw Blades] doesn't remove the [Deadly Blunderbluss] from your inventory on completion, getting you the quest item but letting you keep the gun.
**Steps to reproduce the behavior with as much detail as possible:**

1. Give yourself a [Deadly Blunderbuss] and the quest [Warsong Saw Blades] (As Horde of course)
2. Go to Pixel in Ashenvale and turn in the quest.
3. She doesn't take the gun, I guess she didn't need it after all.

**IDs of affected creatures, items, quests or spells with a link to the relevant page:**

Quest: https://database.turtle-wow.org/?quest=6581

**Expected behavior. Describe how it should work:**
The Deadly Blunderbuss should be removed from the player's inventory when the quest is completed.

**Comment by slowtorta** [comment]
Working as intended, cannot reproduce. I was able to complete this quest and she took the gun from my inventory.
