### ISSUE TITLE
Quest Bug - The Tome of Valor - Defend Daphne Stilwell from Defias

### ISSUE THREAD

**Issue by Yourztru1y** [slowtorta/turtlewow-bug-tracker#760]
Quest Bug - The Tome of Valor - Defend Daphne Stilwell from Defias

Daphne Stilwell walks to the house to grab her gun. Gun comes out as a missing image (blue/white cube) in her hand. Enemies spawn in 3s but that spam spawn. To the point of their being 30+ enemies running at your. They also reappear/disappear while spawning.

Location of quest is southern Westfall. I believe its part of paladin quest but comes from Tome of Valor in your inventory.

**IDs of affected creatures, items, quests or spells with a link to the relevant page:**

https://classic.wowhead.com/quest=1651/the-tome-of-valor#comments

**Expected behavior. Describe how it should work:**
Enemies spawn. Not 30+ of them. You kill them and no more appear.

**Comment by exidtv** [comment]
This is still bugged - wave 1 spawns and about 5 seconds later wave 2 spawns with the third wave spawning another 5 seconds after the second wave.

This is a quick way to lose your HC paladin character (as I did, as a new player I was not aware that this was bugged)

This should be a big priority in fixing as it also turns into a hard block for paladins chasing their quest hammer, unless you get help from a higher level (which is not easy to do)

**Comment by redmagejoe** [comment]
Scripting on this event is still incorrect. Spawns are too frequent and buggy (phasing in and out).
