### ISSUE TITLE
hawk's beak quest from [Broken Spear] item

### ISSUE THREAD

**Issue by TorTun** [slowtorta/turtlewow-bug-tracker#762]
1. cant accept that new quest via quest item (54 hc dwarf priest)
2. 
![image](https://user-images.githubusercontent.com/95168215/147894654-e66d0bdb-507d-4834-8f1e-671116b5e7f9.png)

**Comment by Tinyfin-github** [comment]
Greetings! I have checked and i have been unable to find any issues with quest.

Please make sure you have completed the pre required quest chain. You need to complete "Norvok of the Spear" to be able to use the item.
