### ISSUE TITLE
A Donation of Wool not available for Goblins.

### ISSUE THREAD

**Issue by Matuselah** [slowtorta/turtlewow-bug-tracker#763]
Quest [A Donation of Wool](https://classic.wowhead.com/quest=7826/a-donation-of-wool) as well as Tauren version of that quest. Doesn't available for Golbins. Probably Undercity as well, not checked. Revantusk Trolls turn in, working as intended
![WoW 2022-01-03 12-02-31](https://user-images.githubusercontent.com/94643131/147899269-fb47e346-91c5-4334-948c-4815fd231403.png)
Also it will be good if future versions of turn in cloth will be checked as well silk/mageweave/runecloth

**Comment by Matuselah** [comment]
Just checked Undercity doesn't work either.

**Comment by geojak** [comment]
Similiar problem for highelfs
