### ISSUE TITLE
Undead hunter talent trees bugged, missing talents!

### ISSUE THREAD

**Issue by bolivianospk** [slowtorta/turtlewow-bug-tracker#764]
My marksman tree is missing the whole 15 points talent row.  Survival missing quite a few talents as well.  Beast master I can't learn pathfinding.  and one other talent missing.  Please help! 
![Screenshot 2022-01-02 234839](https://user-images.githubusercontent.com/42015400/147908784-91b1e203-1b89-43a5-8755-82fce78ad019.png)
![Talent glitch](https://user-images.githubusercontent.com/42015400/147908793-75d58ce1-3a27-416d-8e86-c0c880bd6b9c.png)
![Screenshot 2022-01-02 234856](https://user-images.githubusercontent.com/42015400/147908803-73c1cb0b-f6a3-489b-b177-671c928f6308.png)

**Comment by slowtorta** [comment]
Seems like you're using Vanilla Plus client to play on Turtle WoW, is that correct?

**Comment by bolivianospk** [comment]
Yes that is true,  thanks. I downloaded yours and my talents are fixed!
