### ISSUE TITLE
issue in the mount appearance

### ISSUE THREAD

**Issue by pedrostrik** [slowtorta/turtlewow-bug-tracker#765]
**Please, provide a clear description what the bug is:**
the mount from token (shop) named as nightmare dreamrunner , changed its appearance as a moose or deer (dark color)

**Steps to reproduce the behavior with as much detail as possible:**

1.Object: https://forum.turtle-wow.org/images/shop/mounts/40.jpg
2. 
3. 

**IDs of affected creatures, items, quests or spells with a link to the relevant page:**

NPC: https://database.turtle-wow.org/?npc=
Item: https://database.turtle-wow.org/?item=
Quest: https://database.turtle-wow.org/?quest=
Spell: https://database.turtle-wow.org/?spell=
Object: https://database.turtle-wow.org/?object=

**Expected behavior. Describe how it should work:**

THANKS

**Comment by slowtorta** [comment]
This has been fixed a few days ago, please clear your WDB cache and try again. Re-open this issue if you encounter this bug again.

**Comment by pedrostrik** [comment]
Thanks, I was not playing with that caracter :-))
i will check it later
