### ISSUE TITLE
Spellpower coefficient on Life Tap is too low again

### ISSUE THREAD

**Issue by Lunkdunk** [slowtorta/turtlewow-bug-tracker#767]
**Please, provide a clear description what the bug is:**
With no talents and 703 shadow power max rank  life tap does 725, which is a spell power coefficient of 0,41. It should be 0,8 untalented.
**IDs of affected creatures, items, quests or spells with a link to the relevant page:**

NPC: https://database.turtle-wow.org/?npc=
Item: https://database.turtle-wow.org/?item=
Quest: https://database.turtle-wow.org/?quest=
Spell: https://database.turtle-wow.org/?spell=
Object: https://database.turtle-wow.org/?object=

**Expected behavior. Describe how it should work:**

**Comment by slowtorta** [comment]
Thanks, will be fixed onthe next update.
