### ISSUE TITLE
Grammar in quest Kalanar's Mallet

### ISSUE THREAD

**Issue by ahhh-reptar** [slowtorta/turtlewow-bug-tracker#769]
Objective text-
Optional off?: "burnt" most (maybe all?) of this game's quests are written in American English, which would be burned.  Not a huge deal but may as well point it out.
Wrong and Off: "Kalanar Brightshine, from it gather Kalanar's Mallet and return it to him in Astranaar."  Comma splice, either remove the comma after Brightshine or replace it with a period (probably better), and probably replace "from it gather" with something like  "retrieve", setup something like this: "Kalanar Brightshine.  Then retrieve Kalanar's Mallet and..."

Description-
Off: "As the druids tended..." As is unclear here; I initially thought we were going to have a time-based comparison but it was meant as a cause-effect statement.  Maybe replace As with Because for clarity.
Wrong: "tended to The Crescent Grove I" add a comma after Grove
Off: "whatever it was they needed" can drop it was and have the same meaning without sounding dismissive

Wrong: "As of recently a band" put a comma after recently.  As of recently is a verb phrase describing "moved in" at the end of the sentence
Off: "calling themselves the Groveweald" is a verb phrase describing "band of Furbolg", consider moving it immediately next to "band of Furbolg" for sentence flow
Wrong: "In my panic" separate with comma, same reason as before, verb phrase describing why he left stuff behind
Wrong: "treasures, most of it, no doubt burnt to the ground" Period after treasures.  Comma after doubt, was before burnt, consider putting No doubt at the start of the phrase and dropping the comma after most of it.  Also consider burned instead of burnt.  End result: "treasures.  No doubt, most of it was burned to the ground."

Off: "I ask of you" you can drop of here and maintain the same meaning.  Generally prepositional phrases will sound odd when immediately following a verb.
Wrong: "to the Crescent Grove, and to my burnt down home, gather from behind the house my mallet."  Again, consider swapping burnt for burned.  The wrong part is the first two phrases however.  Because his house is in the Crescent Grove, you should just combine the two phrases, like this "to my burned down home in the Crescent Grove" Also the next part is kinda rambling but it can be cleaned up while keeping the spirit of it there (for the sake of the next sentence" by just adjoining the two phrases with an and, overall like this: "to my burned down home in the Crescent Grove and find my mallet behind it."  
Wrong: "It was given to me from my father" from should be by
Off: "and was used to build my house."  Unless somebody else built his house, he should own the action, like "and I used it to build my house."
Wrong: "alot" should be "a lot"

**Comment by Kruxis** [comment]
Thanks again. Keep up the good work!
