### ISSUE TITLE
Dark Strand Mobs Allied with Undead Scourge?

### ISSUE THREAD

**Issue by Dragunovi** [slowtorta/turtlewow-bug-tracker#77]
**Please, provide a clear description what the bug is:**
Some Dark Strand cult members decided to ally themselves with the Scourge, which seems to be unintentional.
**Steps to reproduce the behavior with as much detail as possible:**

1. Go to Ashenvale/Darkshore.
2. Check the mobs' faction. 

**IDs of affected creatures, items, quests or spells with a link to the relevant page:**

NPC 1: https://database.turtle-wow.org/?npc=3725
NPC 2: https://database.turtle-wow.org/?npc=3727
NPC 3: https://database.turtle-wow.org/?npc=3730

**Expected behavior. Describe how it should work:**
They should be classified as normal monsters like their non-scourge brethren.

**Comment by slowtorta** [comment]
I cannot find any sources with the correct faction ID for their kind. Please re-open this issue if you have more information on this matter.
