### ISSUE TITLE
Game constantly crashes.

### ISSUE THREAD

**Issue by Ygriel** [slowtorta/turtlewow-bug-tracker#771]
**Please, provide a clear description what the bug is:**

The crashing issue only started this evening (03/01/2022), but for the past few days the game has been a bit laggy / jittery but still playable and enjoyable. My character is currently in Stormwind, and whenever I log in, the game crashes within 15-20 seconds. I read an in game message which said, before contacting a GM with errors, please delete the WDB folder. I tried this, but it hasn't made a difference. 

I have attached some photo's of error messages which I hope are helpful (and a funny photo of a fox).

![IMG-0394](https://user-images.githubusercontent.com/97055792/147969615-234a38ef-22d1-425e-b35b-f64e87ac6b24.jpg)

![IMG-0395](https://user-images.githubusercontent.com/97055792/147969651-1dbc993f-62a8-4a81-8f7f-f87d8ba4251c.jpg)

![IMG-0396](https://user-images.githubusercontent.com/97055792/147969187-c41e745a-b789-4711-b99d-f4263ae0ec46.jpg)

![IMG-0397](https://user-images.githubusercontent.com/97055792/147969177-5453c313-71bf-45d6-99f8-46d45285b719.jpg)

Something is very wrong with my fox

**Comment by Tinyfin-github** [comment]
Greetings! Please turn Vertex Animation Shaders on in video settings.
