### ISSUE TITLE
Spawn after battleground is wrong

### ISSUE THREAD

**Issue by pypaut** [slowtorta/turtlewow-bug-tracker#773]
**Please, provide a clear description what the bug is:**

I successfully entered and participated in a Warsong Gulch battleground. I was in Stormwind when I accepted the battleground, but afterwards was spawned somewhere else (Dun Morough), where I **previously** was (maybe last battleground respawn, but cannot confirm).

**Steps to reproduce the behavior with as much detail as possible:**

1. Queue battleground (Warsong Gulch here)
2. Accept battleground
3. Fight
4. Click "Leave battleground"
5. Get spawned back to the world (wrong place)

**IDs of affected creatures, items, quests or spells with a link to the relevant page:**

**Expected behavior. Describe how it should work:**

I would like to be respawned in the world exactly where I left it.

(no big deal tho i don't want to sound rude, just accurate. thanks for reading)

**Comment by slowtorta** [comment]
It's saving your position at the moment of queuing. It's too low a priority given the number of expansion bugs, sorry. It'll probably stay as it is now.

**Comment by burner1024** [comment]
This is very bad. It screws up the entire game for people who play bgs. With this, there's literally no reason to go anywhere while you're queued, so you just sit and waste your time waiting.
This should be an easy fix and huge QoL improvement. Please consider this again.
