### ISSUE TITLE
Sun's Embrace does not work

### ISSUE THREAD

**Issue by valmoranepi** [slowtorta/turtlewow-bug-tracker#774]
High Elf priest racial skill "Sun's Embrace" does not give any sign of activity and Holy Fire and Smite don't get their mana cost reduced. 

Steps:

1. Buy Sun's Embrace codex from vendor
2. Learn Sun's Embrace
3. Cast Sun's Embrace

Cannot provide ID's because of database being hidden at the moment. 

Expected: 

Sun's Embrace should lower Smite and Holy Fire's mana costs

**Comment by Zebouski** [comment]
this fix was supposed to come with 1.16 as part of the class update, but it probably was lumped in with the class changes that will now release in 3 days. check again then
