### ISSUE TITLE
Item "Grayson's Torch" have no model?

### ISSUE THREAD

**Issue by Gasan918** [slowtorta/turtlewow-bug-tracker#775]
**Please, provide a clear description what the bug is:**

Item "Grayson's Torch" is not visible at all if you equip it. No torch, no light while playing. But at Character Select (start) screen everything is fine.

![image](https://user-images.githubusercontent.com/96973359/148018742-793a35e7-0a5b-4d51-b27f-91fe4ed8e78a.png)

[https://radikal.ru/lfp/a.radikal.ru/a19/2201/1a/d4e965975fcc.jpg/htm](url)

**Steps to reproduce the behavior with as much detail as possible:**

1. Equip item
2. Check toon's appearance at "Character Info" or at main screen
3. 

**IDs of affected creatures, items, quests or spells with a link to the relevant page:**

NPC: https://database.turtle-wow.org/?npc=
Item: https://database.turtle-wow.org/?item=1172
Quest: https://database.turtle-wow.org/?quest=
Spell: https://database.turtle-wow.org/?spell=
Object: https://database.turtle-wow.org/?object=

**Expected behavior. Describe how it should work:**

Same model as other off-hand have? Some slightly differenl color of light (more orange or white) would be great.

**Comment by Tinyfin-github** [comment]
Greetings! The torch is visible when used. It's invisible when sheathed 

https://user-images.githubusercontent.com/83077166/148406290-f9a83dfe-6bfd-4a53-88ce-ab6e2e60126c.mp4
