### ISSUE TITLE
NPC names at SW Harbor ("Cody" boy and "Cody" girl)

### ISSUE THREAD

**Issue by Gasan918** [slowtorta/turtlewow-bug-tracker#776]
**Please, provide a clear description what the bug is:**

Kids at SW Harbor have same names.

![image](https://user-images.githubusercontent.com/96973359/148018456-1cb432a5-48fe-4a80-87f7-6b5ece18e8d2.png)

**Comment by Kruxis** [comment]
Thanks for your report! 

The issue will be fixed on the next restart.

Safe Travels =)
