### ISSUE TITLE
Quest "Freedom For All Creatures" Bug

### ISSUE THREAD

**Issue by virre117** [slowtorta/turtlewow-bug-tracker#779]
**Please, provide a clear description what the bug is:**

For the quest "Freedom For All Creatures" in Feralas where u are supposed to help an NPC free some Spirit Darters from an Cage within a 6 minutes timer, guarded by Grimtotem Taurens, is broken. This is due to the fact that there isnt any Spirit Darters spawning within the cage which results in the quest getting failed when timer runs out.

**Steps to reproduce the behavior with as much detail as possible:**

1. Ive tried to do the quest 3 times. Issue still stands
2. 
3. 

**IDs of affected creatures, items, quests or spells with a link to the relevant page:**
Databas is put down due to new expansion

NPC: https://database.turtle-wow.org/?npc=
Item: https://database.turtle-wow.org/?item=
Quest: https://database.turtle-wow.org/?quest=
Spell: https://database.turtle-wow.org/?spell=
Object: https://database.turtle-wow.org/?object=

**Expected behavior. Describe how it should work:**

See the first description

**Comment by slowtorta** [comment]
![image](https://user-images.githubusercontent.com/66763404/149940953-1ce6f474-c861-4738-9226-2ff4d3774f1b.png)

They're there. Probably someone killed them at the time you tried to do this quest.
