### ISSUE TITLE
Fishing from the pier on Lapidis Isle yields nothing

### ISSUE THREAD

**Issue by rptb1** [slowtorta/turtlewow-bug-tracker#780]
**Please, provide a clear description what the bug is:**
Fishing from the pier at Caelan's Rest on Lapidis Isle always yields an empty result.  Not a "your fish got away", but an empty loot window.

**Steps to reproduce the behavior with as much detail as possible:**

1. Fly to Lapidis Isle and got to the pier.
2. Talk to Fisherman Delavey who says "A wonderful day to fish, is it not?"
3. Try fishing.
4. Delavey is wrong.  Your bobber bobs and you strike, but the result is always empty.

**Expected behavior. Describe how it should work:**
Fish.

**Comment by Dormilon** [comment]
Sorry I tried that and it's working as intended, cannot reproduce.
![image_2022-02-08_12-51-07](https://user-images.githubusercontent.com/79369417/152962683-6b53268d-e63e-40f0-abe3-65842ad9e574.png)
