### ISSUE TITLE
Friends list window is empty.

### ISSUE THREAD

**Issue by Gasan918** [slowtorta/turtlewow-bug-tracker#782]
**Please, provide a clear description what the bug is:**

Even if you have lots of friends, "friends list" tab remains empty until you click it.

**Steps to reproduce the behavior with as much detail as possible:**

1. Load client
2. Open "Friends List" tab
3. List is empty
4. Click at it
5. Friends are shown

**Expected behavior. Describe how it should work:**

You load client, you open "Friends List" tab, you see list of your friends.

**Comment by Tinyfin-github** [comment]
Greetings! One of your friends deleted his character. Please press the delete button until you remove Unknown and it will return to normal.
