### ISSUE TITLE
Tiger mount speed dont scale

### ISSUE THREAD

**Issue by Khanz0** [slowtorta/turtlewow-bug-tracker#783]
Hello fellow turtles.

The tiger mount from shop (previously called bengal tiger. Later stranglethorn tiger and now just tiger) have a speed bug. His speed used to increase with riding level

But with epic riding at level 60 still runs at 60% instead 100% (tested with the holy mistletoe which turns it into a reeinder. The reeinder run much faster than the tiger form)

And tested with purple tallstrider (reward for getting level 60 in turtle mode). He runs faster than the tiger

Could you fix it? Is my main mount and i bought it with real money because i love it and i would hate if he becomes slower than usual and becomes useless

**Comment by jameyboor** [comment]
No repro, please try again.
