### ISSUE TITLE
Hedwig companion in wrong tab of the spellbook

### ISSUE THREAD

**Issue by bakemeat** [slowtorta/turtlewow-bug-tracker#784]
**Please, provide a clear description what the bug is:**
Hedwig companion appears in the general tab of the spellbook instead of under the companions tab.

**Steps to reproduce the behavior with as much detail as possible:**
Me and other people have noticed the same issue with that exact companion.

**IDs of affected creatures, items, quests or spells with a link to the relevant page:**
Database unavailable at the moment.

**Expected behavior. Describe how it should work:**
Hedwig should appear in the same tab of the sepllbook as all other companions.

![image](https://user-images.githubusercontent.com/91905839/148102680-b330c485-1a5e-4824-b621-cd9d3e1f54ff.png)

**Comment by Tinyfin-github** [comment]
#603
