### ISSUE TITLE
The inn at Mirage Raceway does not give rested

### ISSUE THREAD

**Issue by rptb1** [slowtorta/turtlewow-bug-tracker#787]
**Please, provide a clear description what the bug is:**
The inn at the Mirage Raceway (run by Innkeeper Gazz) does not give rested XP.

**Steps to reproduce the behavior with as much detail as possible:**

1. Go to the inn in Mirage Raceway.
2. Observe your character portrait.

**Expected behavior. Describe how it should work:**
Inns should give rested XP.

**Comment by slowtorta** [comment]
This is a Guild House, those are not supposed to have rested bonuses.
