### ISSUE TITLE
There are 2 ways to make Dim Torches.  One can raise Survival skill the other doesn't.

### ISSUE THREAD

**Issue by thrassoss** [slowtorta/turtlewow-bug-tracker#788]
**Please, provide a clear description what the bug is:**
Clicking on a torch in your inventory while standing near a fire will still create a Dim Torch, and trigger a 1 minute CD.  It will not raise your survival skill.

Using the Survival Menu to craft dim torches requires torches in your inventory and a fire, but will NOT trigger the 1 minute CD between crafting and will give a chance for the Survival skill to increase.  Seemingly as normal.

**Steps to reproduce the behavior with as much detail as possible:**

1.  Have Survival skill of 1.
2. Buy 20 unlit torches.
3. While standing near a fire, light 10 of them from your inventory.  This will take 10 minutes as each torch will trigger the 1 minute cooldown.  You will still have a survival skill of 1.
4. Light 10 dim torches from your survival menu, this will take less than a minute or so.  There is no 1 minute CD between.  You will also probably have a Survival skill of 10 as each lighting has a very high or 100% chance to trigger a skill increase.
5. 

**IDs of affected creatures, items, quests or spells with a link to the relevant page:**

Sorry, DB is still down.

NPC: https://database.turtle-wow.org/?npc=
Item: https://database.turtle-wow.org/?item=
Quest: https://database.turtle-wow.org/?quest=
Spell: https://database.turtle-wow.org/?spell=
Object: https://database.turtle-wow.org/?object=

**Expected behavior. Describe how it should work:**

I would expect the Survival crafting menu to limit the craft some way similar to the 1 min. CD on the torch?  A 1 minute craft for a torch seems excessive though, usually 1 minute craft times are for like 290-300 gear.  On the other hand it seems a 'bit cheap' from an investment standpoint to just spend 2 minute getting survival to 75.  I'm not sure if there is an easy way to trigger a CD from a crafting menu though.

I have no idea what the balance here should be.  It's probably not critical either way it should just probably be consistent.  

Thanks.

**Comment by jameyboor** [comment]
Fixed.
