### ISSUE TITLE
Overlord Wyrmthalak Not Guaranteed to Drop Loot

### ISSUE THREAD

**Issue by Dragunovi** [slowtorta/turtlewow-bug-tracker#79]
**Please, provide a clear description what the bug is:**
Overlord Wyrmthalak doesn't seem to be dropping loot %100. I have checked the loottables in the database but people have reported this is still the case, wouldn't hurt to take a look at it.
**Steps to reproduce the behavior with as much detail as possible:**

1. Go to Lower Blackrock Spire
2. Teleport to Overlord Wyrmthalak.
3. Repeatedly kill and respawn him a lot.

**IDs of affected creatures, items, quests or spells with a link to the relevant page:**

NPC: https://database.turtle-wow.org/?npc=9568

**Expected behavior. Describe how it should work:**
Overlord Wyrmthalak should always drop an item with %30 chance for his gemstone and %2 chance for the epic ring.

**Comment by slowtorta** [comment]
Please, re-open this issue if issue is still present after the next update.

**Comment by Tinyfin-github** [comment]
Issue persists.
