### ISSUE TITLE
Tirsfal Uplands: Quest The Lost Tablets

### ISSUE THREAD

**Issue by dshwedovsky-sc** [slowtorta/turtlewow-bug-tracker#792]
At completing quest **The Lost Tablets** awarded reputation with Shaterspear Trolls instead of Silvermoon Remnant.
https://database.turtle-wow.org/?quest=80290

![WoWScrnShot_010522_161923](https://user-images.githubusercontent.com/25076735/148224881-2d0b62c5-018b-441c-988d-3e4d5f83b409.jpg)
![WoWScrnShot_010522_161936](https://user-images.githubusercontent.com/25076735/148224890-4998fa79-3283-4029-a3ff-7445b5808008.jpg)
![WoWScrnShot_010522_162426](https://user-images.githubusercontent.com/25076735/148224896-c456693c-9c11-4ec7-a9bb-a7c6333bbb8b.jpg)

Expected behavior: awarded reputation with Silvermoon Remnant at completing.

**Comment by dshwedovsky-sc** [comment]
Looks like that all quest chaing give incorrect reputation.
Prequest was https://github.com/slowtorta/turtlewow-bug-tracker/issues/657
Please check next quest in chain: The Shadow Well

**Comment by geojak** [comment]
another bug with this quest, the lvl 30 wrath that spawn when looting the tablet does not attack or do any dmaage.

**Comment by Kruxis** [comment]
Rep issue will be fixed on next server restart.
