### ISSUE TITLE
Flame wrath is not scaling by 100%

### ISSUE THREAD

**Issue by Velite12** [slowtorta/turtlewow-bug-tracker#797]
![image](https://user-images.githubusercontent.com/45871932/148286074-f690a5aa-9abf-4482-b6f3-0953ea922ef4.png)

Flame wrath is currently scaling by 12% of spellpower, it should scale by 100% as it did before the patch.

**Comment by Khanz0** [comment]
Same happened with Diamond flask. It scales much less than should be. I made a post about it too
