### ISSUE TITLE
[Hunter] hunter explosive trap doesn't leave a patch of fire on the ground after triggering.

### ISSUE THREAD

**Issue by OrnsteinHunter** [slowtorta/turtlewow-bug-tracker#799]
**Please, provide a clear description what the bug is:**

Explosive trap is supposed to leave a patch of fire on the ground that applies the dot to enemies that enter it. It currently only applies the dot to enemies in range of the trap when it triggers.

**Expected behavior. Describe how it should work:**

In vanilla and classic when you trigger explosive trap, it should leave a patch of fire on the ground, similar to flamestrike or consecration, that lasts 20 seconds, and applies the dot to enemies that enter.

classic wowhead spell effect that leaves the patch of fire on the ground. "persistent area aura: periodic damage:"

https://classic.wowhead.com/spell=13812/explosive-trap-effect

I found this 2007 video as evidence of this happening. (mute the music LOL.) It's super early TBC, but the only early video i could really find of explosive trap being used and the effect I'm talking about. 

@ 0:42 the trap triggers and leaves a patch of fire on the ground.

https://youtu.be/e9z2GcmgkgM?t=42

https://classic.wowhead.com/spell=13813/explosive-trap

explosive trap classic wowhead with an image of the effect.

**Comment by Velite12** [comment]
Can confirm there is no flamestrike effect present.

**Comment by ratkosrb** [comment]
This is not a bug. There is no visual left on the ground on the official Classic servers either. The spell was changed in TBC, compare the descriptions.

https://www.wowhead.com/classic/spell=13813/explosive-trap
https://www.wowhead.com/tbc/spell=13813/explosive-trap
