### ISSUE TITLE
Goblin Spawn Area Mobs bug

### ISSUE THREAD

**Issue by Plainbear** [slowtorta/turtlewow-bug-tracker#8]
By opening this Issue, I admit to having done the pertinent research using sources from Vanilla (preferably) or Classic. I also understand that sources from other private servers are not acceptable.

**Current behavior**: 
Mobs reset after one hit
**Expected behavior**: 
Mobs do not recover health and try to attack me
**Proofs**:
Did a Goblin and tried to do the quests and they are impossible to achieve
**Steps to reproduce**:

1. Attack a Chicken or Robot or Plant
2. 
3.

**Comment by slowtorta** [comment]
Please close your client completely, locate a folder called WDB and delete it. Then safely start client again and try to reproduce the same bug. It's probably just a cache issue.

**Comment by Plainbear** [comment]
Yep, that was right. I was confused because the other starting zones worked fine.
