### ISSUE TITLE
Smashing Zul’Mashar Missing Daily Flag

### ISSUE THREAD

**Issue by Dragunovi** [slowtorta/turtlewow-bug-tracker#80]
**Please, provide a clear description what the bug is:**
[Smashing Zul’Mashar] can be only done once per character when it was intended to be a daily quest, resetting at 0 Server Time every day and becoming open to get completed again.
**Steps to reproduce the behavior with as much detail as possible:**

1. Get the quest [Smashing Zul’Mashar].
2. Complete the quest.
3. Wait a day for the quest to reset. Or check if the quest has the daily flag on it.

**IDs of affected creatures, items, quests or spells with a link to the relevant page:**

Quest: https://database.turtle-wow.org/?quest=80254

**Expected behavior. Describe how it should work:**
[Smashing Zul’Mashar] should be doable once a day with the daily quest flag.

**Comment by slowtorta** [comment]
Thanks for reporting it. It'll be fixed on the next server restart. Make sure to clear your WDB folder.
