### ISSUE TITLE
Tyrant Devilsaur is floating around at high speed

### ISSUE THREAD

**Issue by ulricc66** [slowtorta/turtlewow-bug-tracker#800]
Today at 10:49 the Tyrant Devilsaur got bugged and was moving at maybe 200% speed, from north to south and back north again for a while. It did not follow it normal animation, was stuck in one frame. Maybe a one-time thing but wanted to report it anyway

**Comment by geojak** [comment]
Not one time, I have heard this coem up already a few times in world or beginners chat

**Comment by zomgits** [comment]
This has also been mentioned in HC chat and causes HCs to avoid Un'goro altogether.

**Comment by zomgits** [comment]
![image](https://user-images.githubusercontent.com/97355053/153052099-7e082b1c-37a9-4a81-bd8d-8ab29100aaa5.png)

**Comment by Kruxis** [comment]
Existing issue: https://github.com/slowtorta/turtlewow-bug-tracker/issues/529

Closing, thanks for notifying that it's still an issue =)
