### ISSUE TITLE
[Paladin] Consecrate is ticking 7 times, not 8 times

### ISSUE THREAD

**Issue by Velite12** [slowtorta/turtlewow-bug-tracker#802]
Using Rank 5 Consecrate on a level 1 mob with 0 spell power:
![image](https://user-images.githubusercontent.com/45871932/148308493-62544534-d69a-424e-93f8-1ed2018006df.png)

![image](https://user-images.githubusercontent.com/45871932/148308655-a6ed5912-8524-4ca3-b5b0-c6c340edd53c.png)

How it should work:

Tested on classic with rank 1 consecrate: 8 ticks on a level 5 mob
![image](https://user-images.githubusercontent.com/45871932/148309276-0156d291-c74f-4061-a189-b6af0b63e31b.png)

![image](https://user-images.githubusercontent.com/45871932/148308523-d1a2fb00-e916-43cf-9ce7-9d7145d545e2.png)

Spell tooltip says it does 384 damage over 8 seconds. This means 8 ticks of 48 damage. But as we are only seeing 7 ticks, it does 336 damage.

**Comment by Velite12** [comment]
Update: Rarely this is possible, but 8 ticks can be achieved, but only when I was testing against a level 63 mob:

![image](https://user-images.githubusercontent.com/45871932/148310256-2aef0c2a-51e3-4c8d-9ec1-278e46a5adc8.png)
![image](https://user-images.githubusercontent.com/45871932/148310281-7c94e32d-7289-4b0b-811b-952b56d770f1.png)

However I have not been able to replicate 8 ticks on a level 1 mob. This means that there is possibly an issue with the resist and the dot ticks interaction

**Comment by geojak** [comment]
arcane missiles rank 1 have the same problem.

the tooltip says deals 24 damage each second for 3 seconds. it only shots twice.

**Comment by slowtorta** [comment]
![image](https://user-images.githubusercontent.com/66763404/167004516-be268bb0-9459-4750-bd32-cf49fca8fbe0.png)
8 ticks on level 5 target dummy. Sometimes it does only 7, I haven't tested what's causing it yet.

**Comment by slowtorta** [comment]
> arcane missiles rank 1 have the same problem.
> 
> the tooltip says deals 24 damage each second for 3 seconds. it only shots twice, when it should be trice.

It ticks 3 times. The last one is de-synched, it's a different bug.

**Comment by geojak** [comment]
Someone on discord reported that since the last patch also mage Blizzard only ticks 7 times. Maybe it helps figure out a joint root 

He is absolutely sure that it's a newly introduced issue as of last restart on Tuesday of this comment on a Thursday.

**Comment by itswicky** [comment]
This is likely misses and resists not being written to the combat log. There was a similar issue in TC previously. If I can find a commit they made to fix then I'll post a link here.

**Comment by Velite12** [comment]
> This is likely misses and resists not being written to the combat log. There was a similar issue in TC previously. If I can find a commit they made to fix then I'll post a link here.

If that's the case then the larger issue is why a level 1 ends up resisting often when it should be 1%
