### ISSUE TITLE
[Sparkwater Special] consumable item doesn't get consumed (infinite uses)

### ISSUE THREAD

**Issue by bakemeat** [slowtorta/turtlewow-bug-tracker#803]
**Please, provide a clear description what the bug is:**
The newly added item [Sparkwater Special] sold in Sparkwater Port doesn't get consumed on use. It has infinite uses with a cooldown of 10 sec per use.

**Steps to reproduce the behavior with as much detail as possible:**
Used the item several times, bought a new one, which had the same effect. They also don't stack.

**IDs of affected creatures, items, quests or spells with a link to the relevant page:**
Database unavailable.

NPC name (vendor): Faz
Item name: Sparkwater Special

**Expected behavior. Describe how it should work:**
Unless infinite uses is an intended effect, the beverage should get consumed on use. Stacking like other similar drinks (up to 20) would also be beneficial.

![image](https://user-images.githubusercontent.com/91905839/148311678-3c0a9437-67ee-4551-b3d8-f8b17539f6d2.png)

**Comment by Kruxis** [comment]
Thanks for your commit! 

The issue will be fixed on the next restart.

Safe Travels =)
