### ISSUE TITLE
Typo in Ashenvale quest 'Aggressive Wildlife' 

### ISSUE THREAD

**Issue by inxdigo** [slowtorta/turtlewow-bug-tracker#805]
Quest is spelled 'Aggresive Wildlife' but it should be spelled 'Aggressive Wildlife'
![Aggressive_Wildlife_Quest_Spelled_wrong](https://user-images.githubusercontent.com/74259373/148396875-fc41ba6e-1ec6-4370-9051-49cfa086f2c4.png)
'

**Comment by Kruxis** [comment]
Thanks for your report! 

The issue will be fixed on the next restart.

Safe Travels =)
