### ISSUE TITLE
Dead mob in Shadowfang Keep still attacking after fight

### ISSUE THREAD

**Issue by inxdigo** [slowtorta/turtlewow-bug-tracker#806]
After the boss Fenrus the Devourer and the mobs Arugal's Voidwalker have been killed one of the corpses of the Arugal's Voidwalkers continues to attack players after death, following them around as they moved around the dungeon. This also keeps the gates from opening so we can continue to the rest of the dungeon. Dying/leaving the instance eventually caused it to despawn.

**Steps to reproduce the behavior with as much detail as possible:**

1. Kill Fenrus the Devourer
2. Kill Argual's Voidwalkers that spawn after

Expected behavior: Corpse shouldn't attack after death & gates should open
![SFK_Arugals_Voidwalker_Bug_2](https://user-images.githubusercontent.com/74259373/148398197-5828f22c-a942-4ced-94f8-f0403b6aa7c4.png)
![SFK_Arguals_Voidwalker_Dead_Attacking](https://user-images.githubusercontent.com/74259373/148398202-fd088592-8721-44ec-9051-fd479db2f10e.png)

**Comment by Khanz0** [comment]
Yep. Same happened to me yesterday

**Comment by zomgits** [comment]
Possibly related to https://github.com/slowtorta/turtlewow-bug-tracker/issues/851

**Comment by AyleeJenn** [comment]
My group and I also encountered this. A GM was so kind to help us open the gate so we could finish our run.

**Comment by AyleeJenn** [comment]
My group and I found a work around for this problem that might be useful until it is fixed (if it isn't fixed already). Here is how it works:

After the void walkers spawn the players need to refrain from using area of effect attacks and, instead, fight the void walkers one by one.

We have tested this several times and it has worked without error.

**Comment by Kruxis** [comment]
Greetings, thanks for the report, this issue should be fixed on next restart =)

**Comment by Tinyfin-github** [comment]
Issue persists.

**Comment by nobodyinteresting** [comment]
Still an issue in June 2022 :(.

**Comment by jameyboor** [comment]
Fixed after next update.
