### ISSUE TITLE
Alliance quest Arugal's Folly can't be shared

### ISSUE THREAD

**Issue by inxdigo** [slowtorta/turtlewow-bug-tracker#807]
While in a group which included another alliance player I wasn't able to share the SFK dungeon quest 'Arugal's Folly'. It isn't part of a chain and as far as I know has no special requirements for accessing the quest. I was able to share 'The Missing Sorcerer' which came from the same questgiver. I logged out, cleared my WDB folder, and logged back in and was still unable to share
![Arugals_Folly_Cant_share_Alliance](https://user-images.githubusercontent.com/74259373/148399310-fd124fbf-97eb-4839-9560-7bebcab70280.png)

**Comment by geojak** [comment]
Same problem with the crescent Grove quests which should be shareable since no wirst items involved or prewuests
