### ISSUE TITLE
Velinde Starsong Solid

### ISSUE THREAD

**Issue by Dragunovi** [slowtorta/turtlewow-bug-tracker#81]
**Please, provide a clear description what the bug is:**
Velinde Starsong looks like a normal alive night elf when she should look like a ghost.
**Steps to reproduce the behavior with as much detail as possible:**

1. Do the quest [The Scythe of Elune].
2. Check Velinde Starsong's state.

**IDs of affected creatures, items, quests or spells with a link to the relevant page:**

NPC: https://database.turtle-wow.org/?npc=3946
Quest: https://database.turtle-wow.org/?quest=1043

**Expected behavior. Describe how it should work:**
Velinde Starsong should look like a ghost as she's a memory from the past and shouldn't look like a normal alive elf.

**Comment by slowtorta** [comment]
Thanks for reporting it. It'll be fixed on the next server restart. Make sure to clear your WDB folder.
