### ISSUE TITLE
wormhole generator sw still chagres silver on use

### ISSUE THREAD

**Issue by geojak** [slowtorta/turtlewow-bug-tracker#810]
**Please, provide a clear description what the bug is:**

the engineer craft for the stormwind wormhole still makes the paying sound and i guess silver are charged on use.
it is not written on the tooltip, and there a crafting costs too since item is not permanent.
i think this is an oversight or should be stated on the tooltip.

**Steps to reproduce the behavior with as much detail as possible:**

1. craft the engineer wormhole
2. use the tiem
3. here the paying sound and check money

**IDs of affected creatures, items, quests or spells with a link to the relevant page:**

NPC: https://database.turtle-wow.org/?npc=
Item: https://database.turtle-wow.org/?item=
Quest: https://database.turtle-wow.org/?quest=
Spell: https://database.turtle-wow.org/?spell=
Object: https://database.turtle-wow.org/?object=

**Expected behavior. Describe how it should work:**

either not getting charged and no paying sound or its stated on the tooltip

**Comment by slowtorta** [comment]
This is working as intended.

**Comment by geojak** [comment]
Hey torta, if the silver charge is intended then shouldn't the tooltip also state this surcharge?

The tool tip is wrong then
