### ISSUE TITLE
High elf warriors not able to learn 2h mace skill

### ISSUE THREAD

**Issue by SMTfan** [slowtorta/turtlewow-bug-tracker#811]
**Please, provide a clear description what the bug is:**

**Steps to reproduce the behavior with as much detail as possible:**

1.
2. 
3. 

**IDs of affected creatures, items, quests or spells with a link to the relevant page:**

NPC: https://database.turtle-wow.org/?npc=
Item: https://database.turtle-wow.org/?item=
Quest: https://database.turtle-wow.org/?quest=
Spell: https://database.turtle-wow.org/?spell=
Object: https://database.turtle-wow.org/?object=

**Expected behavior. Describe how it should work:**

**Comment by SMTfan** [comment]
High elf warrior not able to learn 2h maces

made a female high elf warrior.  Did not start with the skill.  Not able to learn it from all 4 weapon master trainers.

**Comment by Tinyfin-github** [comment]
#654
