### ISSUE TITLE
Mistake in quest text for 'Investigating Corinth' 

### ISSUE THREAD

**Issue by inxdigo** [slowtorta/turtlewow-bug-tracker#812]
The Quest 'Investigating Corinth' picked up from Mathias Shaw (in the Hawk's Vigil questchain) mentions that you should speak to the innkeep in Southshore, but the quest is pointing you to Menethil (which is where the the turn is actually is).
![Investigating_Corinth_mistake](https://user-images.githubusercontent.com/74259373/148437277-5729dfad-fb40-4076-a478-1810d2f542b9.png)

**Comment by Kruxis** [comment]
Thanks for your report! 

The issue will be fixed on the next restart.

Safe Travels =)
