### ISSUE TITLE
npcs text still states sw - menethil boat

### ISSUE THREAD

**Issue by geojak** [slowtorta/turtlewow-bug-tracker#813]
**Please, provide a clear description what the bug is:**

when talking with the boat npcs they will show a text saying what boats are coming and here and to were.

in auberdine the npc still says it is going to menethil. possibly in menethil the same thing

**Steps to reproduce the behavior with as much detail as possible:**

1. go to auberdine or menethil
2. go to the old auberdine - menethil ports
3. read the npc texts and see they state wrong info

**IDs of affected creatures, items, quests or spells with a link to the relevant page:**

NPC: https://database.turtle-wow.org/?npc=
Item: https://database.turtle-wow.org/?item=
Quest: https://database.turtle-wow.org/?quest=
Spell: https://database.turtle-wow.org/?spell=
Object: https://database.turtle-wow.org/?object=

**Expected behavior. Describe how it should work:**

npc adjusted to refelct to stormwind boat change

**Comment by Kruxis** [comment]
Thanks for your commit! 

The issue will be fixed on the next restart.

Safe Travels =)

**Comment by geojak** [comment]
thank you!

**Comment by geojak** [comment]
![WoWScrnShot_011422_184012](https://user-images.git
![WoWScrnShot_011422_183945](https://user-images.githubusercontent.com/25199983/149560749-1b55b573-7b5d-4552-baf4-9b2b213ac687.jpg)
hubusercontent.com/25199983/149560744-f4c160d2-48d5-4639-90d0-f1949643ab6c.jpg)

did you also fix the sign seen in the screenshot?

**Comment by geojak** [comment]
honestly it would be collect to just have the aub menethil boad additionally to sw back. i mean horde has a huge advantage at the moment and there are actual quests in game that tell you to tkae that boat to menethin in darkshore.

**Comment by Kruxis** [comment]
NPC in the middle should befixed o_O sign not fixed yet

**Comment by Kruxis** [comment]
`Both are fixed. Delete WDB folder ;)`
