### ISSUE TITLE
daisy at raceway shows quest avialble but nothing there

### ISSUE THREAD

**Issue by geojak** [slowtorta/turtlewow-bug-tracker#814]
**Please, provide a clear description what the bug is:**

the npc daisy at the raceway at the shimmering flat has a yellow explanation mark shown but threre is no quest when you talk to here.

deleted wdb and did not help

**Steps to reproduce the behavior with as much detail as possible:**

1. go to shimmering flat as alliance 
2. speak to daisy
3. see a yellow explanation mark for a qeust
4. talk with here and see nothing offered

**IDs of affected creatures, items, quests or spells with a link to the relevant page:**

NPC: https://database.turtle-wow.org/?npc=
Item: https://database.turtle-wow.org/?item=
Quest: https://database.turtle-wow.org/?quest=
Spell: https://database.turtle-wow.org/?spell=
Object: https://database.turtle-wow.org/?object=

**Expected behavior. Describe how it should work:**

she should offera quest if a yellow explanation mark is displayed

**Comment by geojak** [comment]
edit: she offeres me a qeust after i completed that gave me the new race car manual.

it seems that the yellow explanation mark just needs to have a quest prerequeriment that is missing

**Comment by slowtorta** [comment]
You have to complete the following quests to gain access to Daisy's quest: 

https://database.turtle-wow.org/?quest=50312
https://database.turtle-wow.org/?quest=50313
https://database.turtle-wow.org/?quest=50310
https://database.turtle-wow.org/?quest=50311

**Comment by geojak** [comment]
Yea, the bug it's that daidyhas a yellow quest mark before I even finished those. Since I had not finished the quests yet, there was no quest for me to accept.

The bug is the wrongly , too ealey displayed yellow marks before the pre quests were even completed
