### ISSUE TITLE
Typo in dialogue with Aerla Goldenmoon (Boatmaster Auberdine - SW)

### ISSUE THREAD

**Issue by inxdigo** [slowtorta/turtlewow-bug-tracker#816]
When talking to the boatmaster outside of the boat to SW in Auberdine, she says "If it not here yet, simply wait...", when it should read "If it **is** not here yet, simply wait...".
There's also a period missing at the end of "If you are looking to travel, this would be the boat to board."

![Boat_to_SW_typo](https://user-images.githubusercontent.com/74259373/148445183-14de8ac4-5d3c-4660-8005-f9b027d93587.png)

**Comment by Kruxis** [comment]
Thanks for your commit!

The issue will be fixed on the next restart.

Safe Travels =)
