### ISSUE TITLE
Schematic: Goblin Radio

### ISSUE THREAD

**Issue by Dragunovi** [slowtorta/turtlewow-bug-tracker#82]
**Please, provide a clear description what the bug is:**
The item [Schematic: Goblin Radio] can teach the recipe to whoever is your target, which should not be the case.
**Steps to reproduce the behavior with as much detail as possible:**

1. Make yourself Revered with Durotar Trade Co.
2. Target another player character.
3. Use the schematic.

**IDs of affected creatures, items, quests or spells with a link to the relevant page:**

Item: https://database.turtle-wow.org/?item=81196

**Expected behavior. Describe how it should work:**
The schematic should be able to teach the recipe item to only you.

**Comment by slowtorta** [comment]
Thanks for reporting it. It'll be fixed on the next server restart. Make sure to clear your WDB folder.
