### ISSUE TITLE
Noboru the Cudgel in Swamp of Sworrows should patrol

### ISSUE THREAD

**Issue by tubtubs** [slowtorta/turtlewow-bug-tracker#820]
**Please, provide a clear description what the bug is:**
Noboru the Cudgel should patrol through, or around the village, with the two guards that tail behind him.

**Steps to reproduce the behavior with as much detail as possible:**

1. Come across Noboru the Cudgel ~45 37 in Swamp of Sorrows
2. Notice how neither Noboro or the guards patrol, instead Noboru is stuck in place behind a tree

**IDs of affected creatures, items, quests or spells with a link to the relevant page:**

NPC: https://database.turtle-wow.org/?npc=5477
Item: https://database.turtle-wow.org/?item=
Quest: https://database.turtle-wow.org/?quest=
Spell: https://database.turtle-wow.org/?spell=
Object: https://database.turtle-wow.org/?object=

**Expected behavior. Describe how it should work:**
I know it's not exactly a great description, but I did manage to come across a wow classic source that shows the NPC patrolling briefly before getting charged.

https://youtu.be/dQJSxaVpYbM?t=5

**Comment by geojak** [comment]
https://classic.wowhead.com/npc=5477/noboru-the-cudgel

Wow head has a rough map of where he should patrol

**Comment by geojak** [comment]
Another issue currently, the 2 gaurds mob dotn aggro together with noboru. You can actually pull novuru without the 2 guards which should not be possible

**Comment by slowtorta** [comment]
Fixed in the next revision.
