### ISSUE TITLE
Underground Murlocs near entrance to new Tirisfal zone

### ISSUE THREAD

**Issue by fatpowaranga** [slowtorta/turtlewow-bug-tracker#821]
**Please, provide a clear description what the bug is:** There appear to be murlocs left over from before the new Tirisfal zone was added. I don't have access to the db anymore to look up their ID, but I presume they are the same NPC as the ones by the beach. I think they are underground near where the little pond is, but I can't see them  or their targetting. I only know cause I  got aggroed and attacked by an oracle.

**Steps to reproduce the behavior with as much detail as possible:**

1. Walk towards the new area in Trisifal via the northern entrance
2. Walk by the pond (where murlocs used to live)
3. Get aggroed by them (I was level 8 and got attacked by at least an oracle)

**IDs of affected creatures, items, quests or spells with a link to the relevant page:**

NPC: https://database.turtle-wow.org/?npc=  sorry dont have access to db

**Expected behavior. Describe how it should work:** I don't think they should be there anymore, or if they are then maybe they can still spawn underground by accident.

**Comment by slowtorta** [comment]
Thanks, fixed.
