### ISSUE TITLE
Companion items in spellbook show wrong tooltip

### ISSUE THREAD

**Issue by geojak** [slowtorta/turtlewow-bug-tracker#822]
**Please, provide a clear description what the bug is:**

Many of the companion items in the speel box have the babyseal icon. Only a few keep the tool tip they had. 

**Steps to reproduce the behavior with as much detail as possible:**

1. See icons in speel ox of companions doesn't match the items they are learned from

**IDs of affected creatures, items, quests or spells with a link to the relevant page:**

NPC: https://database.turtle-wow.org/?npc=
Item: https://database.turtle-wow.org/?item=
Quest: https://database.turtle-wow.org/?quest=
Spell: https://database.turtle-wow.org/?spell=
Object: https://database.turtle-wow.org/?object=

**Expected behavior. Describe how it should work:**

Consistent behaviour of spellbook companion icons and items

**Comment by slowtorta** [comment]
Sorry, but you should re-open this issue only if you have at least a shortlist of some of the broken spells.

**Comment by geojak** [comment]
Hey sure, I can write up a list atleast for the few pets I have if that makes it easier.
