### ISSUE TITLE
Schematic: Recharge Manual Crowd Pummeler is not appearing in recipe list

### ISSUE THREAD

**Issue by chloejaynebond** [slowtorta/turtlewow-bug-tracker#825]
**Please, provide a clear description what the bug is:**

"Schematic: Recharge Manual Crowd Pummeler" which drops from Tinkerer Gizlock in Maraudon is not appearing in my recipe book after looting and learning it. I farmed a second one on the same character (Vierna) and it didn't recognise it as already learned and let me "learn" it again but it is still in not in my recipe list.

**Steps to reproduce the behavior with as much detail as possible:**

1. Loot "Schematic: Recharge Manual Crowd Pummeler" for Tinkerer Gizlock
2. Learn the recipe
3. Check the spellbook to see that it doesn't appear

**IDs of affected creatures, items, quests or spells with a link to the relevant page:**

NPC: https://database.turtle-wow.org/?npc=13601
Item: https://database.turtle-wow.org/?item=51801
Quest: https://database.turtle-wow.org/?quest=
Spell: https://database.turtle-wow.org/?spell=
Object: https://database.turtle-wow.org/?object=

**Expected behaviour. Describe how it should work:**

Recipe should appear in the list of engineering recipes

I've posted some screenshots of it dropping on the Support channel on discord to show that I've looted it twice.

**Comment by geojak** [comment]
hello this issue is still there
@slowtorta 
only found out after 30 runs to farm the recipe. upon learnig it there is a short failed message and its gone. :(
