### ISSUE TITLE
inkeepers dont talk about new dungeons

### ISSUE THREAD

**Issue by geojak** [slowtorta/turtlewow-bug-tracker#827]
**Please, provide a clear description what the bug is:**

the inkeepers can be talked to, to ask what dungeons we could explore.
they do not recommend cresent grove even thought at the right lvl for it, only scarlet monastery or razorfen downs

**Steps to reproduce the behavior with as much detail as possible:**

1. go to an inkeeper at lvl 39
2. click the dialog option what dungeon i could explore
3. no cresent grove

**IDs of affected creatures, items, quests or spells with a link to the relevant page:**

NPC: https://database.turtle-wow.org/?npc=
Item: https://database.turtle-wow.org/?item=
Quest: https://database.turtle-wow.org/?quest=
Spell: https://database.turtle-wow.org/?spell=
Object: https://database.turtle-wow.org/?object=

**Expected behavior. Describe how it should work:**

npc should recommend also new dungeons for consistentcy

**Comment by slowtorta** [comment]
Please, use the LFT button on your minimap for that. We don't support Innkeeper's LFG feature and it'll be probably just removed soon.

**Comment by geojak** [comment]
heho torta, thx for checking this issue. i think you missunderstood me. i wasnt talking about the LFG feature, just a npc dialog where they feed the player a bit of information about hte dungeon, just for infromation what they could do, and where to find it. its more a lore thing than anything else

**Comment by twowTurtReynolds** [comment]
@geojak I personally agree, this would be a nice touch. Put in a suggestion for this and maybe even write a bit of the dialogue in the post, if you haven't already after 2 years :)
