### ISSUE TITLE
One Shot One Kl

### ISSUE THREAD

**Issue by Coloradomtnman** [slowtorta/turtlewow-bug-tracker#828]
**Please, provide a clear description what the bug is:**

**Steps to reproduce the behavior with as much detail as possible:**

1. Quest is not available to me (Lvl 23 Dwarf Hunter)
2. The quest shows on the map, but Sentinel Aynasha does not have an exclamation above her head and she is not interactable.
3. https://vanillawowdb.com/?quest=5713

**IDs of affected creatures, items, quests or spells with a link to the relevant page:**

NPC: https://database.turtle-wow.org/?npc=
Item: https://database.turtle-wow.org/?item=
Quest: https://database.turtle-wow.org/?quest=
Spell: https://database.turtle-wow.org/?spell=
Object: https://database.turtle-wow.org/?object=

**Expected behavior. Describe how it should work:**

**Comment by Tinyfin-github** [comment]
#336
