### ISSUE TITLE
Mudsprocket Inn

### ISSUE THREAD

**Issue by Dragunovi** [slowtorta/turtlewow-bug-tracker#83]
**Please, provide a clear description what the bug is:**
Mudsprocket Inn doesn't generate rested experience and doesn't allow you to log out instantly when inside.
**Steps to reproduce the behavior with as much detail as possible:**

1. Go to Mudsprocket in Dustwallow Marsh.
2. Go in the big building (The Inn)
3. Check if your experience bar is blue and giving you rested experience.

**IDs of affected creatures, items, quests or spells with a link to the relevant page:**

Null

**Expected behavior. Describe how it should work:**
You should accumulate rested experience and be able to log out instantly inside the inn.

**Comment by slowtorta** [comment]
Thanks for reporting it. It'll be fixed on the next server restart. Make sure to clear your WDB folder.
