### ISSUE TITLE
Horde Quest, Clamlette Surprise

### ISSUE THREAD

**Issue by Dergullen** [slowtorta/turtlewow-bug-tracker#830]
**Steps to reproduce the behavior with as much detail as possible:**

1. Accumulate quest items - Quest log says quest is complete
2. Return to Dirge Quikcleave in Gadgetzan to complete quest
3. Unable to complete quest because '?' is still silver.

**IDs of affected creatures, items, quests or spells with a link to the relevant page:**

NPC: https://database.turtle-wow.org/?npc=8125
Quest: https://database.turtle-wow.org/?quest=6610

**Expected behavior. Describe how it should work:**
I should be able to complete the quest.

**Comment by Tinyfin-github** [comment]
Greetings! I was unable to find any issue with the quest.

Please clear your WDB folder while the game is closed. If the issue persists please open an in game ticket for GM assistance.
