### ISSUE TITLE
WANTED: Hole Escapee

### ISSUE THREAD

**Issue by Drwarlocke** [slowtorta/turtlewow-bug-tracker#832]
**Please, provide a clear description what the bug is:**
WANTED: Hole Escapee...
the NPC Baxxil is stuck dont wake or speak....
plus he's 100 miles from what he's supposed to be

**Steps to reproduce the behavior with as much detail as possible:**

1.
2. 
3. 

**IDs of affected creatures, items, quests or spells with a link to the relevant page:**

NPC: https://database.turtle-wow.org/?npc=
Item: https://database.turtle-wow.org/?item=
Quest: https://database.turtle-wow.org/?quest=
Spell: https://database.turtle-wow.org/?spell=
Object: https://database.turtle-wow.org/?object=

**Expected behavior. Describe how it should work:**

**Comment by Neto-WoW** [comment]
Fixed!

**Comment by Neto-WoW** [comment]
@Tinyfin-github - can you post more information as to why this was reopened

**Comment by slowtorta** [comment]
The fix will be applied this Wednesday's maintenance.
