### ISSUE TITLE
Graypaw Wolf can't be skinned

### ISSUE THREAD

**Issue by varlotto** [slowtorta/turtlewow-bug-tracker#833]
**Please, provide a clear description what the bug is:**
The Graypaw Wolf enemies in Tirisfal Uplands are not able to be skinned and may not drop loot.

**Steps to reproduce the behavior with as much detail as possible:**

1. Kill Wolf
2. Acquire no loot
3. Be unable to skin them

**IDs of affected creatures, items, quests or spells with a link to the relevant page:**

NPC: https://database.turtle-wow.org/?npc=91989

**Expected behavior. Describe how it should work:**
The corpse should be able to be skinned presumably like most wolves in-game.

**Comment by Kruxis** [comment]
Thanks for your commit!

The issue will be fixed on the next restart.

Safe Travels =)
