### ISSUE TITLE
Unstable Belt Of Striking cannot be disenchanted

### ISSUE THREAD

**Issue by AdmiralAwsum** [slowtorta/turtlewow-bug-tracker#837]
**Please, provide a clear description what the bug is:**

**Steps to reproduce the behavior with as much detail as possible:**

1. Click Disenchant
2. Click on Unstable Belt Of Striking
3. Item cannot be disenchanted error message gets displayed

**IDs of affected creatures, items, quests or spells with a link to the relevant page:**

Item: https://database.turtle-wow.org/?item=60502

**Expected behavior. Describe how it should work:**
The item should be disenchantable.

**Comment by Dragunovi** [comment]
This issue has been fixed, make sure to delete your WDB file and restart your client for it to take effect.
