### ISSUE TITLE
alpha aggression custom qeust lvl

### ISSUE THREAD

**Issue by geojak** [slowtorta/turtlewow-bug-tracker#838]
**Please, provide a clear description what the bug is:**

the ashenvale custom qeust alpha aggresion is lvl 13 while ghoststalker, the wolf you got to kill, is lvl 27. this doesnt match up

**Steps to reproduce the behavior with as much detail as possible:**

1. get the turtle wow qeust ghoststalker in ashenvale
2. use a addon that shows you the qeust lvl as lv l13
3. see ghoststalker wolf is 27!

**IDs of affected creatures, items, quests or spells with a link to the relevant page:**

NPC: https://database.turtle-wow.org/?npc=
Item: https://database.turtle-wow.org/?item=
Quest: https://database.turtle-wow.org/?quest=
Spell: https://database.turtle-wow.org/?spell=
Object: https://database.turtle-wow.org/?object=

**Expected behavior. Describe how it should work:**

the qyest lvl should be lvl 22 atleast

**Comment by Kruxis** [comment]
MinLvReq is higher than 13.
