### ISSUE TITLE
kodos in desolace make to stomping sound

### ISSUE THREAD

**Issue by geojak** [slowtorta/turtlewow-bug-tracker#839]
**Please, provide a clear description what the bug is:**

the kodo escort in desolcae, other kodos, or also just my paladin mount. they all have should have a specific sound when walking. kodos stomp, pala horse gallops. the sounds seem missing

**Steps to reproduce the behavior with as much detail as possible:**

1. do the kodo desolace escort
2. turn out sound
3. no stomping
4. mount your pala horrse
5. no galloping sound either
6. press space on mount while standing still
7. the special mount sounds is missing too

**IDs of affected creatures, items, quests or spells with a link to the relevant page:**

NPC: https://database.turtle-wow.org/?npc=
Item: https://database.turtle-wow.org/?item=
Quest: https://database.turtle-wow.org/?quest=
Spell: https://database.turtle-wow.org/?spell=
Object: https://database.turtle-wow.org/?object=

**Expected behavior. Describe how it should work:**

sounds played for mounts and kodos

**Comment by geojak** [comment]
What happens with issues that end up in client issues? Are these impossible to be fixed?

**Comment by slowtorta** [comment]
> What happens with issues that end up in client issues? Are these impossible to be fixed?

It simply takes more time and it's more comfortable for us to have them all in one report.

**Comment by geojak** [comment]
Ah, I see. Thank you for the explanation torta!
