### ISSUE TITLE
Arcane Missiles Messed Up

### ISSUE THREAD

**Issue by Dragunovi** [slowtorta/turtlewow-bug-tracker#84]
**Please, provide a clear description what the bug is:**
Since the last batch of pushes Arcane Missiles got wrecked hard, only having a chance of proccing Clearcasting on initial cast, not proccing the Tier 2 8 set bonus effect and Blade of Eternal Darkness at all.
**Steps to reproduce the behavior with as much detail as possible:**

1. Equip the aforementioned items and get the Clearcasting talent.
2. Spam Arcane Missiles at a target dummy.
3. Check if any of the procs happen.

**IDs of affected creatures, items, quests or spells with a link to the relevant page:**

Spell (Rank 1): https://database.turtle-wow.org/?spell=5143
Spell (Rank 2): https://database.turtle-wow.org/?spell=5144
Spell (Rank 3): https://database.turtle-wow.org/?spell=5145
Spell (Rank 4): https://database.turtle-wow.org/?spell=8416
Spell (Rank 5): https://database.turtle-wow.org/?spell=8417
Spell (Rank 6): https://database.turtle-wow.org/?spell=10211
Spell (Rank 7): https://database.turtle-wow.org/?spell=10212
Spell (Rank 8): https://database.turtle-wow.org/?spell=25345

**Expected behavior. Describe how it should work:**
Arcane Missiles should have a chance of proccing the aforementioned items and clearcasting with every missile volley, this really slaps the already weak arcane hard and should not be the case.

**Comment by ttdgrin** [comment]
can confirm that arcane missile no longer proc clearcast on pulse, only has a chance to proc on initial cast ( lvl 24 mage )

**Comment by ttdgrin** [comment]
when will there be a fix to clearcast for arcane missile?

**Comment by Nolin7777** [comment]
As the label already says, a reliable source is required to "fix".

**Comment by ttdgrin** [comment]
well dont see what source is needed, before the patch ~2 weeks ago arcane missile procked clearcast during the channel, not it only prock when inital cast, witch make it broken, if this wasnt an intended thing to happen with said patch

**Comment by Axoc77** [comment]
https://vanilla-wow-archive.fandom.com/wiki/Patch_1.9.0
>Class Related Changes
   >Mages
      >Arcane Missiles - Will now be able to trigger procs based on dealing damage.
https://www.wowhead.com/patchnotes=3.0.8
>Classes
   >Mages
      >Arcane Missiles: This spell now only has one chance to trigger Arcane Concentration.

These sources show that prior to Patch 1.9.0, AM could not trigger Clearcasting. After 1.9.0, it could. In Patch 3.0.8, this was changed to one chance per cast, meaning it was one chance per pulse between Patch 1.9.0 and Patch 3.0.8.

**Comment by ttdgrin** [comment]
not fixed yet, still broken

**Comment by Qix03** [comment]
Still broken.
