### ISSUE TITLE
If you die in the pool of Karazhan crypt you get spawned at the graveyard in Raven Hill, Duskwood

### ISSUE THREAD

**Issue by AdmiralAwsum** [slowtorta/turtlewow-bug-tracker#840]
**Steps to reproduce the behavior with as much detail as possible:**

1. Drown/die in the pools of Karazhan crypts
2.  Release Spirit
3. You get spawned in the Raven Hill graveyard in Duskwood instead of near Karazhan.

**Expected behavior. Describe how it should work:**
Players should be spawned at the graveyard of Karazhan instead of Raven Hill.

**Comment by slowtorta** [comment]
Will be fixed on the next update!
