### ISSUE TITLE
Quest description for "The Shadow Well"

### ISSUE THREAD

**Issue by inxdigo** [slowtorta/turtlewow-bug-tracker#841]
The quest description reads "The air is smelly and these black slimes are overflowing, they even seem resistant to my **slime**." but I'm assuming the second 'slime' should read something like 'magic' or 'spells'?
![The_Shadow_well_Quest_Description](https://user-images.githubusercontent.com/74259373/148649391-472fa371-1768-4ecc-985d-9558290d6a45.png)

**Comment by Kruxis** [comment]
Thanks for your commit!

The issue will be fixed on the next restart.

Safe Travels =)
