### ISSUE TITLE
Got killed by invisible and "unknown" foe during last step of "The Legend of Stalvan"

### ISSUE THREAD

**Issue by valmoranepi** [slowtorta/turtlewow-bug-tracker#843]
Bug description:

I was in a three-men party trying to defeat Stalvan when suddenly I got hit hard by "Unkown" and died, losing my 5% experience as I am in Slow & Steady mode. I am attaching a screenshot from the combat log for further details. 

![immagine](https://user-images.githubusercontent.com/97070728/148654485-499103d9-cd9d-4bcc-863c-d0ea696f8ee0.png)

Steps to reproduce:

1. Engage Stalvan while doing last step of the quest chain with a party
2. Unkown will engage too
3. Eventually get killed

My player name is "Valmora".

NPC: https://database.turtle-wow.org/?npc=315
Quest: https://database.turtle-wow.org/?quest=98

Expected behavior: 

An unknown foe should not intervene in the battle.

**Comment by Qix03** [comment]
You used an aoe and aggroed an invisible mob called The Unseen.

**Comment by Khanz0** [comment]
The unseen killed you. Is not a bug

**Comment by Tinyfin-github** [comment]
https://database.turtle-wow.org/?npc=3094
https://wowpedia.fandom.com/wiki/Unseen
