### ISSUE TITLE
[Sealed Response from Gnomeregan] given to me without being on Appealing to the Alliance quest

### ISSUE THREAD

**Issue by valmoranepi** [slowtorta/turtlewow-bug-tracker#844]
Bug description: 

As a high elf player, I approached High Tinker Mekkatorque to acquire a Gnomoregan quest only to find out a dialogue option which gave me the [Sealed Response from Gnomeregan]. Later on, upon DB reopening, I found out that said object is needed for the Appealing to the Alliance quest which I was not on on object acquiral. 

Steps to reproduce:

1. Be a High Elf
2. Miss Appealing to the Alliance quest start
3. Speak to High Tinker Mekkatorque
4. Obtain [Sealed Response from Gnomeregan]

NPC: https://database.turtle-wow.org/?npc=7937
Item: https://database.turtle-wow.org/?item=83019
Quest: https://database.turtle-wow.org/?quest=80750

Expected behavior: 

Dialogue option with High Tinker Mekkatorque should not be available without required quest.

**Comment by slowtorta** [comment]
Thank you for reporting this. Fixed on the next update.
