### ISSUE TITLE
Darkmoon Card: Blue Dragon might be bugged

### ISSUE THREAD

**Issue by PashaKova** [slowtorta/turtlewow-bug-tracker#847]
**Please, provide a clear description what the bug is:**
Hi! 

I equipped the Blue Dragon card and tried to get it to proc on my priest Aideen, but had zero success. I used spells with cast time (Flash heal Rank 1, Rank 5, lesser heal) and spells with no cast time (Renew Rank 1). I’ve been trying to get it to proc for 10 min.

**Steps to reproduce the behavior with as much detail as possible:**

1. Cast Flash heal Rank 1 until oom 8 times
2. Get no buff (Aura of the Blue Dragon)
3. Repeat

**IDs of affected creatures, items, quests or spells with a link to the relevant page:**

Item: https://database.turtle-wow.org/?item=19288
Quest: https://database.turtle-wow.org/?quest=7907
Spell: https://database.turtle-wow.org/?spell=23684

**Expected behavior. Describe how it should work:**

My character should get a working Aura of the Blue Dragon buff after a successful cast of Renew, Dispel, Flash heal, or any other spell with a 2% chance. (Approximately once every 40-60 casts).

**Comment by CosminPOP** [comment]
You're just unlucky.
Proc chance is pretty low as it is. I've been using this for over a year and its either 3 procs / fight or no procs for two fights back to back.
Working as intended, 2% is 2%.

![image](https://user-images.githubusercontent.com/7255825/149124955-1a81c302-94b6-40a8-982c-ed360daf3259.png)
