### ISSUE TITLE
Armored Obsidian Raptor - Wrong Model

### ISSUE THREAD

**Issue by Paenthy** [slowtorta/turtlewow-bug-tracker#848]
**Please, provide a clear description what the bug is:**

The purchased mount was "Armored Obsidian Raptor" on patch 1.15.2. On current patch, my mount now has the model of a generic raptor.
Riding animations are also a bit exagerated as my gnome now wobbles on it almost twice. 

**Steps to reproduce the behavior with as much detail as possible:**

1. Buy Armored Obsidian Raptor on patch 1.15.2
2. Use Armored Obsidian Raptor on patch 1.16
3. --

**IDs of affected creatures, items, quests or spells with a link to the relevant page:**

Item: https://database.turtle-wow.org/?item=50404

**Expected behavior. Describe how it should work:**

Instead of the generic model, it should be used the Armored Obsidian Raptor model, where it has armor around the body.

Old Model: https://imgur.com/a/hwJ6vn2
Current Model: https://imgur.com/a/5qZIor5

**Comment by slowtorta** [comment]
Will be fixed on the next restart. Please, submit a ticket and request item restoral once the fix is applied.
