### ISSUE TITLE
Dire Maul Books and [Head of Ossirian the Unscarred] Invisible After Quest Turn-In

### ISSUE THREAD

**Issue by Dragunovi** [slowtorta/turtlewow-bug-tracker#85]
**Please, provide a clear description what the bug is:**
The Dire Maul class specific books and [Head of Ossirian the Unscarred] become invisible after their quest have been completed, making loot distribution and dusty tome farming them impossible for people that did their quests.
**Steps to reproduce the behavior with as much detail as possible:**

1. Take one of the items mentioned below.
2. Turn in the quest.
3. Kill Ossirian the Unscarred or check some Dusty Tomes to check if you can see the head/turned-in book.

**IDs of affected creatures, items, quests or spells with a link to the relevant page:**

Item: https://database.turtle-wow.org/?item=21220
Items (Dire Maul Books List): https://database.turtle-wow.org/?object=179547

**Expected behavior. Describe how it should work:**
They should be visible and takeable even after their quests are turned in.

**Comment by Nolin7777** [comment]
Working as intended
