### ISSUE TITLE
Quest: The Great Hermit - Overlapping Triggers and Spawning issue

### ISSUE THREAD

**Issue by Valamartle** [slowtorta/turtlewow-bug-tracker#850]
**Please, provide a clear description what the bug is:**
When accepting Insom'ni's first quest, you are asked to listen to his tale. He tells it but also does the finisher interaction for his chain and summons an enemy. 
**Steps to reproduce the behavior with as much detail as possible:**

1.Accept Quest: The Hermit from Insom'ni on Kazon isle between gilijim and Lapidis. 
2. Talk to Insom'ni and say you are ready to listen to his tale. 
3. He begins to walk and tells both his tale and that of summoning an evil. He eventually transforms after summoning an enemy. His new form does not despawn after the enemy death and stays there. There were 4 of them when I got there. 

**IDs of affected creatures, items, quests or spells with a link to the relevant page:**

NPC: https://database.turtle-wow.org/?npc=60498
NPC: https://database.turtle-wow.org/?npc=60446
Quest: https://database.turtle-wow.org/?quest=40210

**Expected behavior. Describe how it should work:**
He should likely stand still and tell his story in the cave, he shouldn't also finish off his own enemy at our first meeting.

**Comment by Neto-WoW** [comment]
Fixed!
