### ISSUE TITLE
Attack from the Inside

### ISSUE THREAD

**Issue by Drwarlocke** [slowtorta/turtlewow-bug-tracker#852]
**Please, provide a clear description what the bug is:**
quest Attack from the Inside
the quest you get from Duchess Grelda no problem
the Poisoned Grain is bug..
**Steps to reproduce the behavior with as much detail as possible:**

1.the quest you get from Duchess Grelda no problem
2. You can kill Remnants Farmer and Militia no problem at all
3. But the Poisoned Grain is bug i have delete the quest 2 tims
4. https://database.turtle-wow.org/?quest=40099

**IDs of affected creatures, items, quests or spells with a link to the relevant page:**

NPC: https://database.turtle-wow.org/?npc=
Item: https://database.turtle-wow.org/?item=
Quest: https://database.turtle-wow.org/?quest=
Spell: https://database.turtle-wow.org/?spell=
Object: https://database.turtle-wow.org/?object=

**Expected behavior. Describe how it should work:**

**Comment by slowtorta** [comment]
Thank you. Will be fixed tomorrow morning.
