### ISSUE TITLE
Quest: Arathi Basin - Take/Control 4 Bases

### ISSUE THREAD

**Issue by Rakura1** [slowtorta/turtlewow-bug-tracker#853]
**Please, provide a clear description what the bug is:**
When this quest is completed it only gives 100 rep. 
**Steps to reproduce the behavior with as much detail as possible:**

1. Go to Arathi Highlands
2. Accept quest Control 4 bases or for horde take 4 bases
3. Take / Control 4 bases and finish a round
4. Turn in quest

**IDs of affected creatures, items, quests or spells with a link to the relevant page:**

Quest: https://database.turtle-wow.org/?quest=8114

**Expected behavior. Describe how it should work:**
Quest should give 800 rep for turn in as described in wowhead classic: https://classic.wowhead.com/quest=8114/control-four-bases
Please also see comment section for confirmation.

This ensures also that this quest is in line with the rest of the quests available which give 500+ rep.

**Comment by Rakura1** [comment]
Confirmed fixed. Quest rewards 1000 rep for horde variant.

**Comment by Kruxis** [comment]
Thanks for your report! 

The issue will be fixed on the next restart.

Safe Travels =)
