### ISSUE TITLE
Quest: Arathi Basin - Take / Control 5 bases

### ISSUE THREAD

**Issue by Rakura1** [slowtorta/turtlewow-bug-tracker#855]
**Please, provide a clear description what the bug is:**
Quest is made available after completing the quest "Take / Control 4 bases". However the quest immediately tells you you do not meet the requirements for this quest. The bug is that you need to be exalted for this quest which in original wow is correct but based on turtle wow is incorrect.
**Steps to reproduce the behavior with as much detail as possible:**

1. Complete 4 bases quest which is the pre-requesite
2. Attempt to accept control/take 5 bases quest
3. Fail to accept.

**IDs of affected creatures, items, quests or spells with a link to the relevant page:**

Quest: https://database.turtle-wow.org/?quest=8115

**Expected behavior. Describe how it should work:**
Complete 4 bases quest and should be able to accept capture / take 5 bases quest to earn an additional 500 rep. It makes no sense to have this quest be for exalted as rep is meaningless at this point and the tabard which is the reward can be bought at any time from the main city pvp vendor. This quest needs to be fixed to allow for faster rep gain.

**Comment by slowtorta** [comment]
I have actually had a plan to remove War Recruiter and return PvP tabards back to their original state with 1.16.0. Seems like I forgot. I'll tweak the quest anyway, there's no point to keep it on Exalted only on Turtle WoW.
