### ISSUE TITLE
Strahnbrad Mages - Bugged

### ISSUE THREAD

**Issue by thecreth** [slowtorta/turtlewow-bug-tracker#856]
Caster mobs in Strahnbrad (Alterac Mtns) do not behave appropriately. They run erratically and appear to be able to cast while moving (this might not be true, it may be that they start to cast and then run around instead, it was hard to tell):

1. Go to Strahnbrad
2. Engage any of the mages (there's one in the courtyard that's easy to test)

NPC: https://database.turtle-wow.org/?npc=2319

Normal casters should aggro, attempt to cast if they have LoS, or run closer to you if they do not.

**Comment by perka123** [comment]
They are actually supposed to run around, not sure about casting spells while running though

**Comment by geojak** [comment]
Maybe not 100% blizzloke, but the npc behavior was a fun surprise to deal with as meele.
This ai script should be applied to more npcs that have rooting me hanics and range attacks
