### ISSUE TITLE
Mispelled Item - Darlthos Jewelry Box

### ISSUE THREAD

**Issue by fatpowaranga** [slowtorta/turtlewow-bug-tracker#857]
**Please, provide a clear description what the bug is:**  Just a mispelled item

**IDs of affected creatures, items, quests or spells with a link to the relevant page:**

Item: https://database.turtle-wow.org/?item=60189

**Comment by Kruxis** [comment]
Thanks for your commit! 

The issue will be fixed on the next restart.

Safe Travels =)
