### ISSUE TITLE
Typo in quest description - An Azure Scale for Gnomeregan!

### ISSUE THREAD

**Issue by mikefirefly** [slowtorta/turtlewow-bug-tracker#858]
**Please, provide a clear description what the bug is:**
Gnomeregon instead of Gnomeregan in quest description:
![image](https://user-images.githubusercontent.com/13250690/148693839-1a6482c5-fc16-41d4-8913-f2ac11578838.png)

**Comment by Kruxis** [comment]
Will be fixed on the next restart.
