### ISSUE TITLE
kodo and hyena packs in desolace

### ISSUE THREAD

**Issue by geojak** [slowtorta/turtlewow-bug-tracker#859]
**Please, provide a clear description what the bug is:**

the kodo herds and hyena packs in desolace are supposed to roam around desolace. on this server they just stay around hteir spawn points

**Steps to reproduce the behavior with as much detail as possible:**

1. go to desolace
2. find a hyena pack or kodo herd (not the ones in center)
3. they do not roam around but just stay at one point

**IDs of affected creatures, items, quests or spells with a link to the relevant page:**

NPC: https://database.turtle-wow.org/?npc=
Item: https://database.turtle-wow.org/?item=
Quest: https://database.turtle-wow.org/?quest=
Spell: https://database.turtle-wow.org/?spell=
Object: https://database.turtle-wow.org/?object=

**Expected behavior. Describe how it should work:**

they group of npcs should patrol around all over desolcae

**Comment by geojak** [comment]
some examples

![WoWScrnShot_010922_190253](https://user-images.githubusercontent.com/25199983/148694864-7c64f790-95e6-4d49-91e5-a26164ad0952.jpg)
![WoWScrnShot_010922_190300](https://user-images.githubusercontent.com/25199983/148694867-f7312cd1-576d-43a9-b148-a541504d13f1.jpg)
![WoWScrnShot_010922_190345](https://user-images.githubusercontent.com/25199983/148694890-454eca5c-d2c6-4513-ae09-6a0f18d3fdd2.jpg)
![WoWScrnShot_010922_190348](https://user-images.githubusercontent.com/25199983/148694893-60901e0b-f6fc-4055-ae32-26f39b8fa5ab.jpg)
![WoWScrnShot_010922_190440](https://user-images.githubusercontent.com/25199983/148694918-a4f2b950-04bf-4026-bde4-e79b256320ad.jpg)
![WoWScrnShot_010922_190442](https://user-images.githubusercontent.com/25199983/148694919-e4d35e56-0c27-4504-a6fd-eeb5e19d8628.jpg)

**Comment by LeopoldHock** [comment]
At the small base south of Far Watch Post (northern Barrens), now the Southfury guild house, are two peons that also should patrol, but instead stand around on one spot. Could be related.
![image](https://user-images.githubusercontent.com/39671641/150781999-6b3dc6b8-a49f-45e0-bb43-b9736fd29e84.png)

**Comment by geojak** [comment]
its seems a lot of patrol are broken, westfall wind elementals, swamp of sorrow nobuga (i made isseues for both these)
the kodos and scoprions in deolsace

the oger in badlands works but his patrol is not moving together with him properly (no issue for this yet)

all we can do is report all the ones we find and hope it can be fixed

**Comment by geojak** [comment]
I don't thing the visual and text tag on this issue is right

**Comment by slowtorta** [comment]
https://github.com/slowtorta/turtlewow-bug-tracker/issues/1491

**Comment by slowtorta** [comment]
Fixed in the next revision.

**Comment by geojak** [comment]
Oh finally, this rly makes me happy
