### ISSUE TITLE
Potion of Fortitude Missing From Trainers

### ISSUE THREAD

**Issue by Dragunovi** [slowtorta/turtlewow-bug-tracker#86]
**Please, provide a clear description what the bug is:**
The recipe for [Potion of Fortitude] is missing from alchemy trainers and only trainable via a really rare recipe as of currently.
**Steps to reproduce the behavior with as much detail as possible:**

1. Go to one of the listed trainers.
2. Check their trainable recipes.

**IDs of affected creatures, items, quests or spells with a link to the relevant page:**

NPC 1: https://database.turtle-wow.org/?npc=4160
NPC 2: https://database.turtle-wow.org/?npc=4611
NPC 3: https://database.turtle-wow.org/?npc=7948
NPC 4: https://database.turtle-wow.org/?npc=1386

**Expected behavior. Describe how it should work:**
These recipes should be trainable from the aforementioned NPCs, as seen here on Wowhead Classic: https://classic.wowhead.com/spell=3450/elixir-of-fortitude

**Comment by slowtorta** [comment]
Thanks for reporting it. It'll be fixed on the next server restart. Make sure to clear your WDB folder.

**Comment by slowtorta** [comment]
Dev note: yes the entry is now present in the trainer template, it might not show up due to DBC limitation/bug.
