### ISSUE TITLE
Betrayal from Within - Nak + Kuz do not patrol (Quillboars in the Barrens)

### ISSUE THREAD

**Issue by nobodyinteresting** [slowtorta/turtlewow-bug-tracker#860]
**Please, provide a clear description what the bug is:**
Nak + Kuz, quillboar quest NPCs, should patrol around their area. They currently do not.

**IDs of affected creatures, items, quests or spells with a link to the relevant page:**

https://database.turtle-wow.org/?npc=3436
https://database.turtle-wow.org/?npc=3434
Quest: https://database.turtle-wow.org/?quest=879

**Expected behavior. Describe how it should work:**
Kuz patrols west of his spawn, and Nak patrols north/south on other servers.

**Comment by LeopoldHock** [comment]
Possibly related to #859.

**Comment by slowtorta** [comment]
Thank you, it'll be fixed on the next server update.
