### ISSUE TITLE
"They Call Him Morgan the Storm"

### ISSUE THREAD

**Issue by Aeliren** [slowtorta/turtlewow-bug-tracker#861]
The quest completion text for "They Call Him Morgan the Storm" has a minor mistake in it. Additionally, the flow of the text also feels a bit awkward.

Current:
"The Baron sent you? How kind of him to actually send reinforcements, come hear mate, lend me your ear, can't just say it out loud!"
![image](https://user-images.githubusercontent.com/96898927/148726797-5dd0b0b9-6046-4982-bc22-bc784696697c.png)

My suggested edit:
"The Baron sent you? How kind of him to actually send reinforcements. Come here mate, lend me your ear, can't just say it out loud!"

**Steps to reproduce the behavior with as much detail as possible:**

1. Complete "The Bloodsail Buccaneers (4)" from Fleet Master Seahorn in Booty Bay - https://wowpedia.fandom.com/wiki/The_Bloodsail_Buccaneers_(4)
2. Take the quest "They Call Him Morgan the Storm" from Baron Revilgaz in Booty Bay

An additional possible issue: the quest text for "They Call Him Morgan the Storm" and "Exterminate the Rat" mention that Morgan the Storm is male, which is supported by the model shown in the database. However, the in-game model is female. The in-game model wears the same equipment as the male model shown in the database.
![image](https://user-images.githubusercontent.com/96898927/148726751-e1a9c8f9-38a2-43ac-8c87-a4d24001b9af.png)
![image](https://user-images.githubusercontent.com/96898927/148726836-78da1b3a-ca94-4c27-b46e-398a8a261d4e.png)

**IDs of affected creatures, items, quests or spells with a link to the relevant page:**

NPC: https://database.turtle-wow.org/?npc=51607
Quest: https://database.turtle-wow.org/?quest=60152, https://database.turtle-wow.org/?quest=40179

**Comment by Kruxis** [comment]
Thanks for your report! 

The issue will be fixed on the next restart.

Safe Travels =)
