### ISSUE TITLE
Scholomance Risen Lackeys are overpowered

### ISSUE THREAD

**Issue by Zebouski** [slowtorta/turtlewow-bug-tracker#862]
**Please, provide a clear description what the bug is:**
Risen lackeys are sapwned by scholomance dark summonoers, and there are 2 issues:

Here, the summon spell cannot be interrupted, thus guaranteeing a spawn without hard CC. on classic, normal interrupts can work, see kick on this clip: https://youtu.be/ej5Y4tAQ0zI?t=605
When they do spawn, they have a very very high amount of HP, which is extremely punishing to a group that cannot CC the summoner. Classic has the mob with 15 times less HP where it feels far less punishing. https://classic.wowhead.com/npc=10482/risen-lackey

**Steps to reproduce the behavior with as much detail as possible:**

1. enter scholomance, go to the room before kirtonos with the 6 packs on bones
2. pull a Scholomance Dark Summoner pack
3. try to counterspell, shield bash, and kick it, all 3 should work but they don't. it will summon a risen lackey, check HP of lackey

**IDs of affected creatures, items, quests or spells with a link to the relevant page:**
NPC: https://database.turtle-wow.org/?npc=10482

**Expected behavior. Describe how it should work:**
risen lackeys shouldn't be so impactful to a group that cannot hard CC. Adding support for all: kick, pummel, earth shock, counterspell, spell lock, spriest silence, will mostly guarantee that an average group has at least 1 way of managing these pulls correctly

**Comment by CosminPOP** [comment]
Hp confirmed here
https://youtu.be/UCF5b3uLAGc?t=155

Will be updated to a value that's closer to classic soon.
