### ISSUE TITLE
Shadowy Assassins not spawning in Southshore

### ISSUE THREAD

**Issue by Azeron223** [slowtorta/turtlewow-bug-tracker#867]
[Shadowy Assassins ](https://database.turtle-wow.org/?npc=2434) do not seem to be spawning on the server.

These NPCs drop the quest starting item [Assassin's Contract](https://database.turtle-wow.org/?item=3668) for alliance.

I've checked their known spawn locations around Southshore on a LOT of occasions to no avail and can personally confirm it's typical for stock 1.12 private servers to not have these NPCs spawning as standard.. or at least I've not seem them spawn in at least 6+ years of playing private servers over perhaps 20-30 alliance characters, checking for their spawn on every character (I really like questing).

While I can't be sure of the respawn timer, I'd be fairly confident in saying they should have an above average respawn timer of perhaps 30 or so minutes with the spawn locations already listed in the database seeming to be correct.

**Comment by Dormilon** [comment]
This is a timed/scripted event, it starts with the Southshore Crier running into Southshore (form Tarren's Mill direction) and yelling: "Help me! Help! Assassins in the Hills! To arms! To arms!"
Then Southshore Guard says: "Go to your posts! Let no invader reach Southshore!" and "Anyone suspicous is to be taken down quickly. Get to your posts as quickly as possible" Even if you miss this part with all the yelling, you can still figure out if the Assassins are about if you just take a look a the guards. While this event is active, almost all guards around Southshore are doubled, so if you see many more than usual guards patrolling, then the assassins are near. They try to sneak into Southshore and some are just waiting around SS.

**Comment by s1lver1us** [comment]
I'm trying to obtain the item that starts a quest from this event, what are the triggers or at what time does the event start?

https://github.com/vmangos/core/issues/599
Various comments says it starts exactly at 5 AM and 5 PM server time or once every two hours, but I had been camping for over 12 hours outside the Southshore Inn and logged on at both 5am/pm server time to check but the event does not occur.

Any help is appreciate thanks:) Also if a GM could spawn the quest starting item [Assassin's Contract ](https://database.turtle-wow.org/?item=3668) in my inventory that would be great!

**Comment by slowtorta** [comment]
Please try this event again after the next server update on wednesday, May 4. Reopen this issues if you encounter any problems.

**Comment by geojak** [comment]
@slowtorta hello torta, i have been trying to camp out this event over the past motnh without any luck. 5 pm server time just passed and there was no event. every 2 hours as stated above is defitively also untrue.

do you happen to have any infoamtion when this is supposed to be happening, becuase over weeks i nver saw it, trying multiple times and afking around for hours a few times.

**Comment by geojak** [comment]
also the vmangoc commit says should be very 2 hours.
https://github.com/vmangos/core/pull/1420

thast defivitevly not the case on twow

**Comment by gabryatfendor** [comment]
Agree, camped quite a while without success

**Comment by geojak** [comment]
@slowtorta not fixed pls reopen
