### ISSUE TITLE
Site database: obsolete map and NPC coordinates for Stormwind location (1519)

### ISSUE THREAD

**Issue by Gasan918** [slowtorta/turtlewow-bug-tracker#870]
**Please, provide a clear description what the bug is:**

Stormwind: database still have Vanilla map and Vanilla NPC locations. No new harbor NPC's also.

**Expected behavior. Describe how it should work:**

Site needs new map and actual NPC positions.

**Comment by slowtorta** [comment]
We have an internal tracker for web-related issues, I'll just move it there. Thank you :)
