### ISSUE TITLE
[NPC Issue] Insomn'ni Cannot Interact with NPC, no dialogue box.

### ISSUE THREAD

**Issue by Valamartle** [slowtorta/turtlewow-bug-tracker#873]
**Please, provide a clear description what the bug is:**
Cannot interact with Insom'ni on Kazon Isle. I reported a bug with him spawning and doing something for his chain finale, and still have quests from that time. I'm not sure if that is causing my issue, but it'd be nice not to have to do the quest again. 
**Steps to reproduce the behavior with as much detail as possible:**

1. Travel to Kazon Isle between Gilijim and Lapidis. 
2. Try to click on Insomni to talk. 

**IDs of affected creatures, items, quests or spells with a link to the relevant page:**

NPC: https://database.turtle-wow.org/?npc=60446

**Expected behavior. Describe how it should work:**
He should have a text box show up to interact and and to complete quests.

**Comment by Valamartle** [comment]
After the restart, the NPC is now interactable again. Cheers!

**Comment by Khanz0** [comment]
Bugged again cant click him
