### ISSUE TITLE
PVP: Game Clock unreadable until end of match

### ISSUE THREAD

**Issue by Rakura1** [slowtorta/turtlewow-bug-tracker#875]
**Please, provide a clear description what the bug is:**
When in a battleground if you look at the score screen everything shows fine except the clock. It seems to be right justified off screen but at the end of a match will auto correct. This is frustrating when combined with the fact a game needs to last 10 minutes in order for the losing team to get a token.
**Steps to reproduce the behavior with as much detail as possible:**

1. Join a battleground
2. Open all stats screen
3. Try to see game time

**IDs of affected creatures, items, quests or spells with a link to the relevant page:**

**Expected behavior. Describe how it should work:**
Opening all stats screen should show the game time in real time not just post game.

![image](https://user-images.githubusercontent.com/90916104/148947926-e383bc1f-be66-4f11-bf41-4f8078a01f5b.png)

**Comment by CosminPOP** [comment]
happens when you join a bg from another bg, cant do anything about it, its just the game
