### ISSUE TITLE
PVP: Warsong Gulch - Alliance gates not dropping on start of match for horde

### ISSUE THREAD

**Issue by Rakura1** [slowtorta/turtlewow-bug-tracker#876]
**Please, provide a clear description what the bug is:**
When starting a round of Warsong Gulch the Alliance gates do not disappear as expected for horde. Meanwhile the horde barriers drop just fine in the opening seconds of the game for both sides.
**Steps to reproduce the behavior with as much detail as possible:**

1. Join Warsong Gulch once for ALliance and once for horde to see difference
2. Cross the map to opposite faction
3.  Attempt to enter base from Graveyard or ramp side entrances
4. Notice that as Alliance you can do this no problem. Notice for horde you either have to blink through or wait till the gates disappear which burns 30 seconds or more off the game clock giving alliance a defensive advantage

**IDs of affected creatures, items, quests or spells with a link to the relevant page:**

**Expected behavior. Describe how it should work:**
When gates drop for alliance the gates should also drop for horde at the same time.

![image](https://user-images.githubusercontent.com/90916104/148960322-f1995940-d61d-40b2-a28e-af9b9bdab389.png)

**Comment by slowtorta** [comment]
That's a client-side glitch, server-side it happens simultaneously. Sorry, nothing we can do about it.

**Comment by burner1024** [comment]
1. Not sure what do you mean by "nothing", you definitely can and do modify the client.
2. Doesn't happen on other pservers, therefore definitely a twow issue.
3. Worst case, can delay horde gates for alliance as well, to even out the situation.
