### ISSUE TITLE
Quest: Jadefire Revenge

### ISSUE THREAD

**Issue by Kiwijello** [slowtorta/turtlewow-bug-tracker#877]
The NPC for the quest, Jadefire Revenge, is unclickable. His name is Insom'ni.

1. Completed quest
2. Unable to click or interact with NPC

**IDs of affected creatures, items, quests or spells with a link to the relevant page:**

NPC: https://database.turtle-wow.org/?npc=60446
Quest: https://database.turtle-wow.org/?quest=40211

**Expected behavior. Describe how it should work:**

I should be able to interact with the NPC for quest completion. First interaction returned "Unknown Object". I deleted my WDB folder and logged back in. The NPC, Insom'ni, was no longer active at all.  A hunter attempting to turn in quest confirmed as well.

**Comment by mikefirefly** [comment]
This looks fixed - I was just able to interact with this NPC.

**Comment by mikefirefly** [comment]
According to this thread, it's not fixed:

https://forum.turtle-wow.org/viewtopic.php?f=3&t=2695&sid=a393f2b77c08a44a6672bcc7ef167102

**Comment by slowtorta** [comment]
Fix will be applied during this Wednesday maintenance, sorry.
