### ISSUE TITLE
Twisted Reflection and Sheen of Zanza

### ISSUE THREAD

**Issue by Dragunovi** [slowtorta/turtlewow-bug-tracker#88]
**Please, provide a clear description what the bug is:**
Kazzak's Twisted Reflection can get reflected by players that drank [Sheen of Zanza], reflecting the debuff back to Kazzak, allowing any attack of spell of the reflecting player to heal the raid for 20000 health. I've searched up the internet and there's nothing saying this was the case in Classic.
**Steps to reproduce the behavior with as much detail as possible:**

1. Drink a Sheen of Zanza.
2. Engage Kazzak in Blasted Lands.
3. Get hit by his Twisted Reflection and reflect it back at him.
4. Hit him with any attack or spell.

**IDs of affected creatures, items, quests or spells with a link to the relevant page:**

Spell: https://database.turtle-wow.org/?spell=21063

**Expected behavior. Describe how it should work:**
Sheen of Zanza shouldn't be able to reflect Twisted Reflection.

**Comment by jameyboor** [comment]
Fixed
