### ISSUE TITLE
Enslaved demons do not move quicker when mounted

### ISSUE THREAD

**Issue by triana2021** [slowtorta/turtlewow-bug-tracker#881]
Issue: when a warlock with an enslaved demon mounts, it does not function properly. The enslaved demon stays at it normal movement speed and falls behind immediately.

**Steps to reproduce the behavior with as much detail as possible:**

1. enslave a demon as a warlock with a mount
2. mount and watch enslaved pet
3. travel a short distance

expected behaviour: normally we would expect the demon to quickly follow like other pets. 

importance: This issue is significant  given the warlock changes leaning into the spell’s use (infernal cd reduction, talent adjustment).

**Comment by jameyboor** [comment]
Fixed on next update.
