### ISSUE TITLE
Incorrect Quest Reward? Azshara Quest: Killing the Tidelord

### ISSUE THREAD

**Issue by Valamartle** [slowtorta/turtlewow-bug-tracker#882]
**Please, provide a clear description what the bug is:**
The quest reward seems to be a quest item for a completely different quest, which is even for a lower level. 
**Steps to reproduce the behavior with as much detail as possible:**

1.Go through the Rethress Sanctum Quests until you get Killing the Tidelord. 
2. The reward is an Azure Scale which is actually an objective for a Flaxwhisker front quest. 

**IDs of affected creatures, items, quests or spells with a link to the relevant page:**

Azure Scale
Item: https://database.turtle-wow.org/?item=60158

Killing the Tidelord
Quest: https://database.turtle-wow.org/?quest=40061

Flaxwhisker Quest that requires the scale
Quest: https://database.turtle-wow.org/?quest=40062

**Expected behavior. Describe how it should work:**
Presumably we'd receive a blue item or something? It is a near max level group quest and the others in the region also reward blues. I can't find any items in the DB that might be the reward but i wouldn't know what to look for.

**Comment by Kruxis** [comment]
Greetings! 

Thanks for the report, it's fixed and will be applied on next Server restart.

Save Travels!
