### ISSUE TITLE
Kul Tiran Expeditionary Fleet Repuation: No reputation or experience from any of their quests? 

### ISSUE THREAD

**Issue by Valamartle** [slowtorta/turtlewow-bug-tracker#884]
**Please, provide a clear description what the bug is:**
I've finished the majority of their quests and still haven't gotten any reputation. No rep for the wrong faction, just none at all. And according to the Turtle DB, they also give no experience either. ( I am not 100% on the experience claim as I did them on a level 60, not level ~50 yet)
**Steps to reproduce the behavior with as much detail as possible:**

1.Venture to Caelan's Rest, do their quests. 
2. They do not grant reputation for the Kul Tiran Expeditionary fleet, despite the quests all being offered by them. 

**IDs of affected creatures, items, quests or spells with a link to the relevant page:**

These are just a handful, but if you wish I can find all of them. 
Quest: https://database.turtle-wow.org/?quest=40163
Quest: https://database.turtle-wow.org/?quest=40094
Quest: https://database.turtle-wow.org/?quest=40144
Quest: https://database.turtle-wow.org/?quest=40141
Quest: https://database.turtle-wow.org/?quest=40093

**Expected behavior. Describe how it should work:**
Presumably we should be getting experience and rep for doing these quests.

**Comment by slowtorta** [comment]
Thank you, this will be fixed on the next server update. Characters who already completed the quests will be granted a missing reputation during the maintenance!
