### ISSUE TITLE
Half buried Barrel for Lapidis Isle Quest: An Extravagent Book not active?

### ISSUE THREAD

**Issue by Valamartle** [slowtorta/turtlewow-bug-tracker#885]
**Please, provide a clear description what the bug is:**
I've been trying to find this barrel near the Faelon's Folly, and I found a barrel on the ship closest to Zul'razar that looks like it _should_ be interact-able. 
**Steps to reproduce the behavior with as much detail as possible:**

1.Search for an interactable barrel on one of the elven ships during the alliance quest: Faelon's Folly. 
2. None of the barrels in the sand look like they can be activated. 
3. 

**IDs of affected creatures, items, quests or spells with a link to the relevant page:**

Quest: https://database.turtle-wow.org/?quest=40153
Object: https://database.turtle-wow.org/?object=2010830

**Expected behavior. Describe how it should work:**
I can't seem to find the object anywhere, i found a barrel that looks like a quest object but maybe I'm still looking in the wrong spot?

**Comment by Dormilon** [comment]
The barrel will be added the next time the server is restarted.
