### ISSUE TITLE
Paladin: Righteous Fury + Improved Righteous Fury

### ISSUE THREAD

**Issue by Noemad** [slowtorta/turtlewow-bug-tracker#889]
I'm not 100% sure, but I believe the improved righteous fury talent is bugged. At my current level (37) and 3/3 on Improved Righteous Fury, my tooltip for the spell shows it as an increase of 90% threat from holy sources. However, when I buff myself, it only shows 60%.

I saw no significant difference in my threat gain across the 3 levels (35, 36 & 37) that I spent points on Improved Righteous Fury.

**Steps to reproduce the behavior with as much detail as possible:**

1. 3/3 Improved Righteous Fury
2. Highest rank of Righteous Fury available
3. Compare tooltip to actual buff, test threat.

**IDs of affected creatures, items, quests or spells with a link to the relevant page:**

Spell: https://database.turtle-wow.org/?spell=

https://classic.wowhead.com/spell=20470/improved-righteous-fury

**Expected behavior. Describe how it should work:**

Should dramatically increase threat generation by holy spells for the paladin. Not seeing this represented.

**Comment by Velite12** [comment]
Tooltip never shows gain from talent

**Comment by CosminPOP** [comment]
seems like its just another case of vanilla/1.12 inconsistency, working as intended.
