### ISSUE TITLE
Plague Spreaders Wrong Faction

### ISSUE THREAD

**Issue by Dragunovi** [slowtorta/turtlewow-bug-tracker#89]
**Please, provide a clear description what the bug is:**
Plague Spreaders in Raven Hill Cemetery, Duskwood are neutral to the player, which shouldn't be the case.
**Steps to reproduce the behavior with as much detail as possible:**

1. Check Plague Spreader's faction flag.

**IDs of affected creatures, items, quests or spells with a link to the relevant page:**

NPC: https://database.turtle-wow.org/?npc=604

**Expected behavior. Describe how it should work:**
Plague Spreaders should be the part of the Undead - Scourge faction and not Villan (which makes them neutral).

**Comment by slowtorta** [comment]
Thanks for reporting it. It'll be fixed on the next server restart. Make sure to clear your WDB folder.
