### ISSUE TITLE
Many line-of-sight errors in Thelgen Rock

### ISSUE THREAD

**Issue by zomgits** [slowtorta/turtlewow-bug-tracker#890]
**Please, provide a clear description what the bug is:**
In many cases the game claims spiders are not in line of sight when they really most definitely should be.

![image](https://user-images.githubusercontent.com/97355053/149157414-6a821901-4251-425d-8314-5b96493e6923.png)
![image](https://user-images.githubusercontent.com/97355053/149157485-7d26e726-6e33-4258-adba-91bd34578b5c.png)

**Steps to reproduce the behavior with as much detail as possible:**

1. Take a ranged character to Thelgen Rock.
2. Target spiders, especially at corners.
3. Try ranged attacks.

**IDs of affected creatures, items, quests or spells with a link to the relevant page:**

NPC: https://database.turtle-wow.org/?npc=4040
Quest: https://database.turtle-wow.org/?quest=466

**Expected behavior. Describe how it should work:**
Mobs should be in line of sight when there is no visible object between them and the character.

**Comment by slowtorta** [comment]
Moving this issue to the internal tracker for client-related problems, thank you.

**Comment by zomgits** [comment]
Players report similar problems in Dustwind Cave.  Please add.

**Comment by slowtorta** [comment]
Possibly fixed or at least improved on the previous server update.
