### ISSUE TITLE
Scaling on items bugged

### ISSUE THREAD

**Issue by Khanz0** [slowtorta/turtlewow-bug-tracker#891]
Hello

I noticed some items have his scaling bugged

For example diamond flask ( https://database.turtle-wow.org/?item=20130 ) used to scale 1:1 with +healing. Now scales half of it. Tested by myself

Other items i read in the "world chat " with the scaling bugged are flame wrath( https://database.turtle-wow.org/?item=11809 his fire aura should scale with +spell damage 1:1. Now buffs half of it)  and hakkari manslayer (https://database.turtle-wow.org/?item=19852)

Other im not sure. I dont tested it. Maybe someone have more information about other items with his scaling reduced.

Could you fix it?

**Comment by geojak** [comment]
even if this isnt classic blizzlike. nerfing these items spell power scalling might also be preferably and inteed. i mean a warrior with a spellpower set just to abuse the diamond flask is a but corrupted if you ask me.
