### ISSUE TITLE
Ashenvale Quest: Saltspittle Raiders - No Completion Text

### ISSUE THREAD

**Issue by Valamartle** [slowtorta/turtlewow-bug-tracker#892]
**Please, provide a clear description what the bug is:**
I have deleted my WDB folder but this still seems to be what's happening. 
No text when you turn in the quest. 
**Steps to reproduce the behavior with as much detail as possible:**

1.Go to Maestra's Post in Ashenvale and accept the quest Saltspittle raiders from Hadranos Greenblade. 
2. Do the tasks and try to turn in, there is no quest text. 
3. 

**IDs of affected creatures, items, quests or spells with a link to the relevant page:**

Quest: https://database.turtle-wow.org/?quest=40230

**Expected behavior. Describe how it should work:**
Presumably Hadranos might read out something from the book to tell us what was in it, maybe there's a reward? 

![Raiders-bug](https://user-images.githubusercontent.com/96789411/149167625-49e691ea-127f-4df1-92ba-9992838d1884.png)

**Comment by Kruxis** [comment]
Fixed, done and ready on next restart ;)
