### ISSUE TITLE
maraudine wrangler not tagged as elite

### ISSUE THREAD

**Issue by geojak** [slowtorta/turtlewow-bug-tracker#893]
**Please, provide a clear description what the bug is:**

the maraudin warnglers above surface near the entrace of mauradon are not marked as elite.
the maraudine scouts are elite and they have both similiar hp. both should be elite in classic

**Steps to reproduce the behavior with as much detail as possible:**

1. go to the maraudon entrance
2.  see maraudin wcouts as elite
3. see maraudin wranglers not elite

**IDs of affected creatures, items, quests or spells with a link to the relevant page:**

NPC: https://database.turtle-wow.org/?npc=
Item: https://database.turtle-wow.org/?item=
Quest: https://database.turtle-wow.org/?quest=
Spell: https://database.turtle-wow.org/?spell=
Object: https://database.turtle-wow.org/?object=

**Expected behavior. Describe how it should work:**

should have a golden nameplate

**Comment by geojak** [comment]
possibly more centaurs in that area are affected

**Comment by Kruxis** [comment]
Greetings! Working as intended: 
https://classicdb.ch/?npc=4655 Wranglers are non elite
https://classicdb.ch/?npc=4654 Scouts are elite

**Comment by geojak** [comment]
weird, thx for checking!
