### ISSUE TITLE
Impossible to take the taxi from Ratchet to Gadgetzan

### ISSUE THREAD

**Issue by prismatic-digital** [slowtorta/turtlewow-bug-tracker#894]
Impossible to take the taxi from Ratchet to Gadgetzan.

**Steps to reproduce the behavior with as much detail as possible:**

1. Talk to the flight master in Ratchet
2. Choose Gadgetzan as destination
3. Error displayed as in-game alert

**Expected behavior. Describe how it should work:**

1. Flight should start to Gadgetzan

**Comment by Kruxis** [comment]
Greetings!

This issue is known, we deactivated the TaxiNode for maintance =)

I'll close this issue once it is fixed!

**Comment by slowtorta** [comment]
Duplicate, known. Thanks for reporting!
