### ISSUE TITLE
The new haste items do not affect ranged attack speed

### ISSUE THREAD

**Issue by Qix03** [slowtorta/turtlewow-bug-tracker#895]
**Please, provide a clear description what the bug is:** The new items with the haste stat added do not apply the haste to ranged attacks. Enchant Gloves - Haste has the same effect (Increasing attack speed by 1%) and properly applies, so it is likely an issue with the spell effect not properly flagging things, like Rallying Cry and Jujus.

**Steps to reproduce the behavior with as much detail as possible:**

1. Put on one of the new haste items
2. Note your ranged attack speed did not change
3. Profit

**IDs of affected creatures, items, quests or spells with a link to the relevant page:**

Item: https://database.turtle-wow.org/?item=60258
https://database.turtle-wow.org/?item=83484
https://database.turtle-wow.org/?item=83462
https://database.turtle-wow.org/?item=83237

**Expected behavior. Describe how it should work:** Your ranged attack speed should be increased accordingly.

**Comment by slowtorta** [comment]
Moon said he fixed it, closing it for him.
