### ISSUE TITLE
Quest:"Once upon a sheep"- can't turn in

### ISSUE THREAD

**Issue by MadLitrus** [slowtorta/turtlewow-bug-tracker#897]
**Please, provide a clear description what the bug is:**
I am trying to turn in a quest called "Once upon a sheep" to Ol' Reinald Osworth in Goldshire. My quest say Lost farm sheep 15/15, but it will not let me turn in the quest. i already tried deleting the WDB folder multiple times and does not seem to work,
**Steps to reproduce the behavior with as much detail as possible:**

1.I click on Ol' Reinald Osworth. He has a gray exclamation mark over her head.
2. The continue button is grayed out. I cannot turn in the quest.
3. 

**IDs of affected creatures, items, quests or spells with a link to the relevant page:**

NPC: https://database.turtle-wow.org/?npc=50604#ends
Quest: https://database.turtle-wow.org/?quest=60005
Character: Bjornlongbow(Dwarf Hunter)
![Untitled](https://user-images.githubusercontent.com/97635850/149223735-e0be1e11-2284-430b-bb0e-7a4a34881a2c.png)

**Expected behavior. Describe how it should work:**
I expected to be able to turn in the quest. It will not let me Complete the quest to turn it in.

**Comment by Kruxis** [comment]
Greetings! 
I tested the quest and unfortunately i couldn't reproduce the issue. 
Works as intended. Please try abandoning the quest and redoing it. 

Safe Travels!

**Comment by MadLitrus** [comment]
Update: After i abandoned the quest i somehow could turn it in without completing it a second time. I even kept the chocolate bars
