### ISSUE TITLE
Mithril Deposit near The Dark Portal in Blasted Lands under ground

### ISSUE THREAD

**Issue by tubtubs** [slowtorta/turtlewow-bug-tracker#898]
**Please, provide a clear description what the bug is:**
There is a Mithril Deposit that appears under the ground near the Dark Portal in Blasted Lands. It can still be mined, but perhaps should be on the surface.

I think it's the deposit at 57.6 52.3 in Blasted Lands

In the attached screenshots my character is standing close enough to mine this deposit, hovering cursor over it.

**Steps to reproduce the behavior with as much detail as possible:**

1. Roll up to the Dark Portal looking for Mithril
2.  Find a vein under the ground, slightly inside the hill
3.  Realize you can still click it if you're in the right spot after running into the hill for a bit

**IDs of affected creatures, items, quests or spells with a link to the relevant page:**

Object: https://database.turtle-wow.org/?object=2040

**Expected behavior. Describe how it should work:**
I would expect this deposit to be a little higher up, resting on the hill

![2022-01-12 20_19_45-weird mithril](https://user-images.githubusercontent.com/96892771/149260676-7ade193a-cfdf-411d-bcf2-f0572b6c8a99.png)

![WoW 2022-01-12 20-18-49](https://user-images.githubusercontent.com/96892771/149260742-0a4caf28-6ec8-4e35-8b3c-ff7fe3ddb601.png)

**Comment by geojak** [comment]
hello, this is not fixed, here some screenshits

**Comment by geojak** [comment]
![WoWScrnShot_042422_120142](https://user-images.githubusercontent.com/25199983/164971208-6e12e7cb-df0d-4a81-b59e-00d6ebfe31c6.jpg)
![WoWScrnShot_042422_120156](https://user-images.githubusercontent.com/25199983/164971211-8995d963-166b-4d0a-aba7-efe699c57ab2.jpg)
![WoWScrnShot_042422_120139](https://user-images.githubusercontent.com/25199983/164971214-e9b06a19-0ec9-4104-a612-20e25ce4a5fc.jpg)

**Comment by geojak** [comment]
could this pls had a second look and be reopened @slowtorta?
