### ISSUE TITLE
Apostrophe catastrophe in quest title "The Stockade's Search"

### ISSUE THREAD

**Issue by zomgits** [slowtorta/turtlewow-bug-tracker#899]
**Please, provide a clear description what the bug is:**
The quest "The Stockade's Search" has an extraneous apostrophe, unless there is a search that belongs to a singular stockade.

**IDs of affected creatures, items, quests or spells with a link to the relevant page:**

Quest: https://database.turtle-wow.org/?quest=55221

**Expected behavior. Describe how it should work:**
I suggest "Search the Stockades".

Also I suggest "Information on Martin Corinth" not "Martin Corinth's Information" unless that information *belongs* to Martin Corinth.

Also https://www.youtube.com/watch?v=8Gv0H-vPoDc :D

**Comment by Kruxis** [comment]
Greetings! 

Thanks for the report!
Fix will be applied on next server restart =)

Safe Travels!

**Comment by zomgits** [comment]
Woah fast work. Props.
