### ISSUE TITLE
The Reventusk Pet spell in the general tab does not work

### ISSUE THREAD

**Issue by Toirto** [slowtorta/turtlewow-bug-tracker#901]
Upon learning the Amani Eagle pet from the Reventusk Trolls reputation it goes into your general tab but cannot be summoned or cast in anyway.

**Steps to reproduce the behavior with as much detail as possible:**

1. Buy the Amani Eagle
2. Learn the Summon Amani Eagle
3. Sadness

**IDs of affected creatures, items, quests or spells with a link to the relevant page:**

NPC: none
Item: Amani Eagle
Quest: none
Spell: Summon Amani Eagle
Object: none

**Expected behavior. Describe how it should work:**
When using the spell from your general tab Summon Amani Eagle it should be summoned.

**Comment by slowtorta** [comment]
It will be fixed in 1.16.1,  thank you!
