### ISSUE TITLE
QUEST IN WESTERN PLAUGEND

### ISSUE THREAD

**Issue by nedddzad** [slowtorta/turtlewow-bug-tracker#902]
**Please, provide a clear description what the bug is:**

**Steps to reproduce the behavior with as much detail as possible:**

1.QUEST NO WORK TERMITES NOT RESPAWN AND NO DO THE JOB 
2. J PLACED BARREL ON PLACE BE QUEST TERMITES THEY NOT RESPAWN FOR FINISH QUEST
3. https://github.com/slowtorta/turtlewow-bug-tracker/issues/902#issue-1102003629
3. 

**IDs of affected creatures, items, quests or spells with a link to the relevant page:**

NPC: https://database.turtle-wow.org/?npc=
Item: https://database.turtle-wow.org/?item=
Quest: https://database.turtle-wow.org/?quest=
Spell: https://database.turtle-wow.org/?spell=
Object: https://database.turtle-wow.org/?object=

**Expected behavior. Describe how it should work:**

**Comment by LeopoldHock** [comment]
Needs more information. What part of the quest chain is not working?
https://classic.wowhead.com/quest=5901/a-plague-upon-thee
https://classic.wowhead.com/quest=5902/a-plague-upon-thee
https://classic.wowhead.com/quest=6390/a-plague-upon-thee
