### ISSUE TITLE
Final encounter with Naralex and Mutanus the Devourer in Wailing Caverns bugged spawn

### ISSUE THREAD

**Issue by Morridinngh** [slowtorta/turtlewow-bug-tracker#904]
In this encounter many waves of mobs should spawn one at a time and then Mutanus once all the waves have been cleared. However all of the waves spawned at the same time which proceed to overwhelm Naralex and kill him. 

1. Begin the event at the end of Wailing Caverns in which the Tauren NPC attempts to awaken Naralex. 
2. 
3. 

**IDs of affected creatures, items, quests or spells with a link to the relevant page:**

NPC: https://database.turtle-wow.org/?npc=3654
https://database.turtle-wow.org/?quest=60124

**Expected behavior. Describe how it should work:**
The waves should spawn one at a time as the waves are cleared and then finally Mutanus once all waves are cleared.

**Comment by geojak** [comment]
About a month ago I was in wc. Back then the waves spawned correctly

**Comment by Kruxis** [comment]
Thanks for the report, unfortunately (or fortunately) i couldn't reproduce the issue. 

The waves do indeed spawn fairly frequent but not all at once.
