### ISSUE TITLE
Quest 'The Blackwood Corrupted' final event not scripted

### ISSUE THREAD

**Issue by Morridinngh** [slowtorta/turtlewow-bug-tracker#905]
**Please, provide a clear description what the bug is:**
At the end of the quest The Blackwood Corrupted an event should occur after the player uses the filled cleansing bowl by the bonfire. Using the bowl should cause all nearby _Hostile_ Furbolg to run to the cleansing bowl and become _Friendly_ . At which point the satyr Xabraxxis should yell 'What the...nobody cleanses a furbolg in MY camp! Face the wrath of Xabraxxis!' He then should spawn and immidiately rush towards the fire and attack the player. 
 Instead of all of this what happens is after using the cleansing bowl nothing happens with the Furbolg and Xabraxxis just spawns off to the side of the camp without saying anything and doesnt move until engaged by the player. 
**Steps to reproduce the behavior with as much detail as possible:**

1. Aqquire the quest The Blackwood Corrupted and complete all of the required tasks. 
2. 
3. 

**IDs of affected creatures, items, quests or spells with a link to the relevant page:**

NPC: https://database.turtle-wow.org/?npc=10373
https://database.turtle-wow.org/?npc=2169
https://database.turtle-wow.org/?npc=2168

Item: https://database.turtle-wow.org/?item=12347

Quest: https://database.turtle-wow.org/?quest=4763

**Expected behavior. Describe how it should work:**
Here is a video of someone completing the quest from beginning to end in its entirety in which the event is clearly shown. She triggers the event at 3:00 in. However some of the Furbolg are already friendly at that point in this video as a nearby warlock also triggered the event moments before which is also visible in the video. 
https://www.youtube.com/watch?v=O0skyfDp_tQ

**Comment by geojak** [comment]
i made another issue about this qeusts because when collecting the 3 ingredient from the barrels the furbolgs down spawn either. its here on github

**Comment by Gasan918** [comment]
Yes current script is very simple. You use bowl, satyr comes, you fight, he spawns his bow when defeated.

**Comment by geojak** [comment]
Additional problem. The bag that is spanned after killing stays around on this server for ages, which allows players often to skip the hole thing and loot it from previous players.

I think the bag should disappear after loot would be better

**Comment by redmagejoe** [comment]
This event is still not scripted.

**Comment by geojak** [comment]
Did you check if this is fixed: "when doing the blackwood corrupted quest in darkshire and looting the 3 barrels in the blackwood camp for the 3 ingredient, each time when looting a group of furbolgs should spawn and attack the player"

My issue was closed as, duplicate even thought it's not mentioned in here explicitly as an issue
