### ISSUE TITLE
Druid: Omen of Clarity proc'ing less than intended

### ISSUE THREAD

**Issue by Rakura1** [slowtorta/turtlewow-bug-tracker#907]
**Please, provide a clear description what the bug is:**
On regular hits Omen of Clarity is procing as intended. The problem comes when combining it with actions like Maul, Swipe and cat form attacks like claw. These used to also proc omen since they were melee strikes. This is no longer happening. 

**Steps to reproduce the behavior with as much detail as possible:**

1. Get a druid to 60
2. Take omen of clarity
3. Attempt to get omen of clarity to proc
4. Check proc rate against that of HoJ or ELementals deck while in form and attack with skills

**IDs of affected creatures, items, quests or spells with a link to the relevant page:**

Spell: https://database.turtle-wow.org/?spell=16864

**Expected behavior. Describe how it should work:**
Omen of Clarity should be at a 6 to 10% proc rate regardless if using normal attacks or skills.

**Comment by Rakura1** [comment]
![image](https://user-images.githubusercontent.com/90916104/152718184-1e0d11fa-0ed4-4c0b-b433-5d3d79e1b426.png)
clearcasting from maul
![image](https://user-images.githubusercontent.com/90916104/152718208-7705d2bc-1b1c-43c3-bea4-48bca1e738d9.png)
clearcasting from swipe
![image](https://user-images.githubusercontent.com/90916104/152718241-c663c16a-757b-44a9-bf71-ee1f32aa05c8.png)
clearcast from claw

Omen at 2ppm from autos is like a 3% proc chance
from gcd spells, more like 5% i think

**Comment by SaxxonPike** [comment]
The ability for OoC to proc off specials was removed in build 8770 of the WotLK beta. Source: https://www.mmo-champion.com/threads/611531-WotLK-Beta-Build-8770

But up until that point, Maul and Swipe and so on could trigger the effect.

**Comment by jameyboor** [comment]
Fixed on next update.
