### ISSUE TITLE
triage 225 first aid quests not blizzlike

### ISSUE THREAD

**Issue by geojak** [slowtorta/turtlewow-bug-tracker#909]
**Please, provide a clear description what the bug is:**

the first aid triage quests only spawns one soldier at a time, there is no point of triage here. it should spawn soldiers at a fast rate, and you need to priotize and remeber how old they are spawned in in classic

**Steps to reproduce the behavior with as much detail as possible:**

1. be first aid 225 and go to theramore for triage quest
2. observe they spawn in one at a time
3. just do one after another until 15 are healed with 0 challenge and 0 triage 

**IDs of affected creatures, items, quests or spells with a link to the relevant page:**

NPC: https://database.turtle-wow.org/?npc=
Item: https://database.turtle-wow.org/?item=
Quest: https://database.turtle-wow.org/?quest=
Spell: https://database.turtle-wow.org/?spell=
Object: https://database.turtle-wow.org/?object=

**Expected behavior. Describe how it should work:**

soldiers should spawn in faster, and randomly, mostly not too bad injured ones and way less cirtically injured ones as currently. You actively need to choose which to heal first instead of their being just one after another soldier

**Comment by geojak** [comment]
Found you a video from classic
https://m.youtube.com/watch?v=CXM162uXIjo

**Comment by Zmitrok1984** [comment]
As I see in that video, soldier's HP are static and they  do not loose HP over time. 
When I did such quest on Turtle, soldier's HP is decreased over time faster, and if I am not a start to heal a badly injured soldier as soon as he appeared, then he was dying before I finished bandaging him.
So I can say, that on Turtle this quest is hadrer that on Wow Classic.

**Comment by slowtorta** [comment]
Also Triage-related issue: https://github.com/slowtorta/turtlewow-bug-tracker/issues/290

**Comment by ratkosrb** [comment]
https://github.com/slowtorta/turtle-wow/commit/bc33754a3caa8cc0e637f388a538c11f38d12ada
