### ISSUE TITLE
Durotar Labor Union Reputation Not Updated on Race Change

### ISSUE THREAD

**Issue by Dragunovi** [slowtorta/turtlewow-bug-tracker#91]
**Please, provide a clear description what the bug is:**
The Durotar Labour Union reputation isn't updated for the player when swapping from an Alliance to a Horde race.
**Steps to reproduce the behavior with as much detail as possible:**

1. Start an Alliance character.
2. Use a race change token that changes you into a Horde race.
3. Check Durotar Labor Union reputation.

**IDs of affected creatures, items, quests or spells with a link to the relevant page:**

NULL

**Expected behavior. Describe how it should work:**
The player should atleast become Neutral with Durotar Labor Union when race changing from Alliance into a Horde race.

**Comment by slowtorta** [comment]
Thanks for reporting it. It'll be fixed on the next server restart. Make sure to clear your WDB folder.
