### ISSUE TITLE
[Hunter] pet dash ability bug

### ISSUE THREAD

**Issue by fantly** [slowtorta/turtlewow-bug-tracker#910]
Hello, i would like to report a bug with pet ability, I have a pig as a pet and recently I have tamed dog, after learning ability "dash" I  could learn that ability with my pig and that should not be like that. 

dash was ability only for dogs and cats

**Comment by fantly** [comment]
Also there is another bug:

after taming another pet, I was able to learn maxim resistances on it: stamina, armor and etc, no matter that pet had 0 training points on itself.

**Comment by zomgits** [comment]
> after taming another pet, I was able to learn maxim resistances on it: stamina, armor and etc, no matter that pet had 0 training points on itself.

Sounds like https://github.com/slowtorta/turtlewow-bug-tracker/issues/768#issue-1092649864

**Comment by LeopoldHock** [comment]
Yeah, could indeed be related.

**Comment by Velite12** [comment]
![image](https://user-images.githubusercontent.com/45871932/192040669-a6f5ffff-72a4-4dda-91bc-737b6097946f.png)
Can confirm this is still present.

**Comment by redmagejoe** [comment]
This should now be resolved with the recent fix to Hunter Training Points.
