### ISSUE TITLE
Tin Vein is not shown on Minimap

### ISSUE THREAD

**Issue by Gasan918** [slowtorta/turtlewow-bug-tracker#911]
**Please, provide a clear description what the bug is:**

Tin vein in Jangolode Mine near point 44.7, 20.4 is not shown on minimap when "Find Minerals" radar is on.

![image](https://user-images.githubusercontent.com/96973359/149630729-e8528a1d-3d61-4e92-809c-b33a8d89005d.png)

**Comment by slowtorta** [comment]
Hey. As far as my knowledge goes there's no way it can be fixed server-side. It's probably a glitch in a client that I cannot fix. Correct me if I'm wrong but I don't see any flags or other parameters which would make this node different from any other Mining node. Sorry.
