### ISSUE TITLE
Incorrect Oily Blackmouth and Sagefish School locations

### ISSUE THREAD

**Issue by Zeebler** [slowtorta/turtlewow-bug-tracker#912]
Incorrect spawn points for various fish. Sagefish schools appear in Westfall. Oily Blackmouth appear in the Loch.
Reference Wow Classic Data.

**Steps to reproduce the behavior with as much detail as possible:**

1. Check for schools of fish in Loch Modan lake.
2. Check for schools of fish in Westfall coastline.

**IDs of affected creatures, items, quests or spells with a link to the relevant page:**

Oily Blackmouth: https://database.turtle-wow.org/?item=6358#fished-in
    Classic Link: https://classic.wowhead.com/item=6358/oily-blackmouth#comments
Raw Sagefish: https://database.turtle-wow.org/?item=21071#fished-in
    Classic Link: https://classic.wowhead.com/item=21071/raw-sagefish

Links show spawn locations.

**Expected behavior. Describe how it should work:**

Raw Sagefish should not spawn in Westfall coast. There should be more Oily Blackmouth in Westfall. 
Oily Blackmouth should not spawn in Loch Modan. There should be more Raw Sagefish.
![Sagefish in Westfall](https://user-images.githubusercontent.com/26336411/149632027-d26f94a7-3113-427e-98b0-1d305475f995.jpg)
![Oily Blackmouth Loch Modan](https://user-images.githubusercontent.com/26336411/149632029-da0428c8-ce46-439d-810b-23c2c5ed8b32.jpg)

**Comment by Zeebler** [comment]
Any comments?

**Comment by Kruxis** [comment]
Thanks for the report,

will be fixed on next server restart =)
