### ISSUE TITLE
Muglash for "Vorsha the Lasher" doesn't despawn/return correctly.

### ISSUE THREAD

**Issue by nobodyinteresting** [slowtorta/turtlewow-bug-tracker#913]
**Please, provide a clear description what the bug is:**
Muglash, the Zoram Strand NPC who gives you Vorsha the Lasher, currently stays at the quest end location forever. He doesn't despawn or go back to Zoram'gar. If you accept the quest from him while at the end location, he walks back to Zoram'gar then walks back to the end location.

**Steps to reproduce the behavior with as much detail as possible:**

1. Complete Vorsha the Lasher in Ashenvale.
2. Wait several minutes. Muglash will not despawn. Accept Vorsha the Lasher from him on another character.
3. Muglash will now walk back to his spawn location.

**IDs of affected creatures, items, quests or spells with a link to the relevant page:**

NPC: https://database.turtle-wow.org/?npc=12717
Quest: https://database.turtle-wow.org/?quest=6641

**Expected behavior. Describe how it should work:**
Muglash should despawn after several minutes, and respawn back at Zoram'gar, so another character can do the quest properly.

**Comment by 9600bauds** [comment]
Can confirm this is still an issue, and if you start the quest while he's hanging out at the island, then you don't even need to kill the hydra he just spawns it and gives you credit

**Comment by redmagejoe** [comment]
This has been fixed on current version. Abandoning the quest will not break the script's attachment to your character, during which no quests can be accepted from the NPC. Once the script is finished (if you kill all mobs anyway even while not being on the quest), the NPC will state that he will patrol for a while longer, then despawn within 15ish seconds and reappear back in Zoram'gar.

Fixed.
