### ISSUE TITLE
Deeprun Tram is missing ambient sounds.

### ISSUE THREAD

**Issue by Zeebler** [slowtorta/turtlewow-bug-tracker#915]
Deeprun Tram is missing ambient music sound. 

**Steps to reproduce the behavior with as much detail as possible:**

1. Go to Deeprun Tram.
2. Turn up game volume.

**IDs of affected creatures, items, quests or spells with a link to the relevant page:**

Sound Reference: https://www.youtube.com/watch?v=nxw0c0e71xo

**Expected behavior. Describe how it should work:**
Should have noises in background in the Deeprun Tram zone. Not silence.

**Comment by slowtorta** [comment]
Moving this issue to the internal tracker for client-related problems, thank you.
