### ISSUE TITLE
Hunter training pet spells at Pet Trainer not showing in Pet's Spell book

### ISSUE THREAD

**Issue by 1Strawz1** [slowtorta/turtlewow-bug-tracker#917]
**Please, provide a clear description what the bug is:**

**Steps to reproduce the behavior with as much detail as possible:**

1. Open Pet's Spell Book
2. Talk to Pet trainer and train available skills
3. Skills are shown in message box as "You have learned a new spell: ..."
4. Open Pet spell book and learned spells aren't there

**Expected behavior. Describe how it should work:**
Trained spells at the pet trainer should show in Pet's spell book.

![image](https://user-images.githubusercontent.com/97827077/149653796-a72328f2-26b6-4be7-a13c-0d945c33c52a.png)

**Comment by nobodyinteresting** [comment]
The trainer teaches you, and then you teach your pet by using the "Beast Training" ability. It has a slingshot as an icon.
