### ISSUE TITLE
Blank faction text on Arathi horde patrol

### ISSUE THREAD

**Issue by zomgits** [slowtorta/turtlewow-bug-tracker#920]
**Please, provide a clear description what the bug is:**
The first time you target the horde patrol in Arathi Highlands as alliance, you get blank faction text "You are now hated with ."

![image](https://user-images.githubusercontent.com/97355053/149661828-1dc1bae1-262f-42aa-a633-c5cb8a63ba57.png)

**Steps to reproduce the behavior with as much detail as possible:**

1. Make an alliance character and travel to Arathi Highlands.
2. Find the horde patrol.
3. Click on Forsaken Bodyguard from a distance.

**IDs of affected creatures, items, quests or spells with a link to the relevant page:**

NPC: https://database.turtle-wow.org/?npc=2721 *empty faction here*

**Expected behavior. Describe how it should work:**
Should say "Undercity"?

**Comment by zomgits** [comment]
This bug may have created bogus reputation records, which will need fixing up. For example, mine:
![image](https://user-images.githubusercontent.com/97355053/149661925-3eeb24a7-9244-422f-8822-5abca83ff69c.png)

**Comment by zomgits** [comment]
Suggest a DB-wide search for null factions. :)

**Comment by Kruxis** [comment]
Greetings,

please close WoW, go to its directory and delete the WDB folder. Then restart the game. 
Update here if you still don't see the faction.

**Comment by zomgits** [comment]
My WDB folder is read-only and empty, as [per your instructions](https://forum.turtle-wow.org/viewtopic.php?f=18&t=539&sid=704d499d8dc55de4498b1285c332e690).

**Comment by zomgits** [comment]
More blank factions have appeared, but I didn't notice where from.  If you haven't maybe check the whole database for these.
![image](https://user-images.githubusercontent.com/97355053/150200947-817083c4-1d2d-465f-b475-3f5c7a168c7b.png)
