### ISSUE TITLE
Dustwallow Marsh Map and Minimap/World Discrepancy

### ISSUE THREAD

**Issue by Aeliren** [slowtorta/turtlewow-bug-tracker#923]
The Dustwallow Marsh map shows a road leading into the Quagmire leading to Tabetha's house. However, this road does not exist in the world or the minimap.
![image](https://user-images.githubusercontent.com/96898927/149710715-30ae37e1-4977-4554-8c05-af6ddc0bd8dd.png)
![image](https://user-images.githubusercontent.com/96898927/149710735-29a9b66b-3d38-4082-bd33-330147c1e881.png)
![image](https://user-images.githubusercontent.com/96898927/149710752-b1f2272a-2448-47bb-9c5e-e606750ba2d5.png)

**Steps to reproduce the behavior with as much detail as possible:**

1. Go to Dustwallow Marsh, explore "The Quagmire" and "The Den of Flame" to make them appear on the map if not already done.
2. Look at map, and compare to the world.

**Expected behavior. Describe how it should work:**
The road leading into the Quagmire seems to be the anomaly here; it should either be added to the world or removed from the world map.

**Comment by LeopoldHock** [comment]
It's a Vanilla thing. Both map and terrain are client-side. Turtle hasn't changed these areas.
