### ISSUE TITLE
Perpetual Purple Firework is not Purple

### ISSUE THREAD

**Issue by Lexiebean** [slowtorta/turtlewow-bug-tracker#924]
**Steps to reproduce the behavior with as much detail as possible:**

1. Equip Perpetual Purple Firework
2. Use Perpetual Purple Firework

Item: https://database.turtle-wow.org/?item=23714
Spell: https://database.turtle-wow.org/?spell=30161
Object: https://database.turtle-wow.org/?object=181886

**Expected behaviour. Describe how it should work:**

The visual fireworks created by Perpetual Purple Firework are the standard orange/red fireworks. And not purple.

Purple is not just my favourite colour, it's my way of life!

**Comment by slowtorta** [comment]
Indeed not purple. Sadly it's not possible to make it purple w/o modifying the effect color in the client so the best I can do is to rename this object and give it a prettier effect in general :)

![image](https://user-images.githubusercontent.com/66763404/150128912-a580e057-ff73-42d0-90a2-fa6f27a96191.png)
