### ISSUE TITLE
Forum: "report port" feature does not work

### ISSUE THREAD

**Issue by TrangOul** [slowtorta/turtlewow-bug-tracker#925]
**Please, provide a clear description what the bug is:**
"Report post" leads to a 404 page:
`https://forum.turtle-wow.org/app.php/post/<post ID>/report`
[Example](https://forum.turtle-wow.org/app.php/post/10848/report).
![image](https://user-images.githubusercontent.com/5629046/149727453-0a194a06-b407-4248-b740-bf77e5a0fb3a.png)

**Steps to reproduce the behavior with as much detail as possible:**

1. Open any topic on the forum.
2. Pick any post, and click the "Report this post" button (next to the quote button).

**Expected behavior. Describe how it should work:**
A form is opened, so I can describe an issue. Or just a pre-defined list. Or just notify a moderator (not ideal - it can be ambiguous) - anything other than 404.

**Comment by slowtorta** [comment]
Sorry, this one isn't going to be fixed. The forum runs on a very old version of an engine with custom modifications so I'm happy as long as it works at all.
