### ISSUE TITLE
Shredder Operation Manual pages don't drop at all. 

### ISSUE THREAD

**Issue by keirra** [slowtorta/turtlewow-bug-tracker#927]
**Please, provide a clear description what the bug is:**

**Steps to reproduce the behavior with as much detail as possible:**

1.  I've been question through Ashenvale and have completed almost all quests. Not a single page has dropped either with The Lost Pages quest in my questlog or without. 

**IDs of affected creatures, items, quests or spells with a link to the relevant page:**

Quest: https://database.turtle-wow.org/?quest=6504

**Expected behavior. Describe how it should work:**

Pages should drop regularly from all mobs in Ashenvale as Horde player.

**Comment by geojak** [comment]
i think shredder manuals are added in tbc?

**Comment by Jezofine** [comment]
I've had the same issue maybe a month ago on my hardcore character. Killed hundreds of mobs from all parts of Ashenvale trying to get last page, and 0 pages dropped at all.

**Comment by Kruxis** [comment]
"Works as intended" Droprate is utterly low. We'll adjust it.

Fix will be applied on next restart.

Safe Travels!
