### ISSUE TITLE
Netherwind Gloves drop rate in BWL

### ISSUE THREAD

**Issue by frostyfyre** [slowtorta/turtlewow-bug-tracker#931]
**Please, provide a clear description what the bug is:**
There is something wrong with the drop rate of Netherwind Gloves (T2 gloves). The Doom raiding team has been clearing BWL for more than a year now and in this whole time, it dropped only ONCE (maybe twice, but i'm not sure i'm not thinking about another guild's raid)
The drop rate should be 8-9% for each of the THREE bosses. 

**Steps to reproduce the behavior with as much detail as possible:**

1.
2. 
3. 

**IDs of affected creatures, items, quests or spells with a link to the relevant page:**

Item: https://database.turtle-wow.org/?item=16913

**Expected behavior. Describe how it should work:**

drop more than once a year :)

**Comment by LeopoldHock** [comment]
According to the DB, drop rate is 7% on each of the bosses, they share the same loot group with all other T2 glove. *Could* be bad luck.
