### ISSUE TITLE
private thorsen patrol

### ISSUE THREAD

**Issue by geojak** [slowtorta/turtlewow-bug-tracker#934]
**Please, provide a clear description what the bug is:**

when private thorsen goes for his random patnrol that should result in kurzen assasins attack him and afterwards he would offer a quests, there is a problem. 

IF you talk with the private while he is walking, the script of the event breaks and he just stands there, ruining the hole thing.

**Steps to reproduce the behavior with as much detail as possible:**

1. wait for private thorsen do start his patrol
2. speak with him while he is walking
3. he will just stand still from now

**IDs of affected creatures, items, quests or spells with a link to the relevant page:**

https://database.turtle-wow.org/?npc=738
https://database.turtle-wow.org/?quest=215 

**Expected behavior. Describe how it should work:**

it should not be possible to interact wihm him during his patrol

**Comment by geojak** [comment]
i wanted for another round. and even if you dont speak to him which will make him freeze for some time, he doesnt even walk to the assasination point ant turns back half way there.

https://database.turtle-wow.org/?quest=215 
seems to be wrongly avaible anyway from him

**Comment by nobodyinteresting** [comment]
Adding NPC and Quest links since geojak did not:

https://database.turtle-wow.org/?npc=738
https://database.turtle-wow.org/?quest=215

**Comment by geojak** [comment]
Edited you links in. Thx

**Comment by slowtorta** [comment]
Had to revert this fix for now, sorry.

**Comment by nobodyinteresting** [comment]
Poor Thorsen :(

**Comment by redmagejoe** [comment]
Not sure if this is relevant, but this NPC is also offering his quest to anyone so long as he survived the encounter, which I believe he should not be able to survive alone without player intervention. I doubt there is a way to check to see if the player participated in saving him on ancient scripting to only offer it to those players who helped, but at the very least, if no player participated, this NPC should NOT survive.

**Comment by redmagejoe** [comment]
@ratkosrb This may require a sniff on Classic to see precisely how he's supposed to handle his patrol and under what circumstances he's supposed to offer the quest and to who when surviving his assassination.

**Comment by cyaohiri** [comment]
According to a comment from 2006 from Wowhead (https://www.wowhead.com/classic/quest=215/jungle-secrets#comments):
_Every so often, Thorsen will go on patrol. If you follow him, he will be ambushed by two of Kurzen's lackeys (at around (40, 8) ) - if he survives, you will be able to start this quest off him then._

This matches the following videos that are, however, from TBC or later.
https://www.youtube.com/watch?v=GF1SkliEVGo
https://www.youtube.com/watch?v=MMHBqCSi-M0
https://www.youtube.com/watch?v=phnVpNDDrQc

In that first video, it seems like the other player got the quest as well, as they said _"oh, that's how it works"_ in the end.

**Comment by twowTurtReynolds** [comment]
Thank you for the blizzlike proof.
