### ISSUE TITLE
Multiple bugs found.

### ISSUE THREAD

**Issue by shmellyorc** [slowtorta/turtlewow-bug-tracker#936]
**Please, provide a clear description what the bug is:**
Found a bunch of bugs that are kinda weird.

**Steps to reproduce the behavior with as much detail as possible:**
All these bugs can be easily reproduced by just playing the game.

- [Warlock]: the spell that summons a minion, doesn't generate any sound.
- [Warlock]: Using drain soul, Drain life and Health funnel, it has no sound effect
- [Warlock]: When collecting a soul shard from soul drain, it has no sound effect
- When your minion is attaching two or more mobs, when that mob dies, your minion comes back to you. Not going for the next attacker whom is attacking your minion. Even if your minion is set to Defensive.
- using spacebar, in water, makes you jump not move upwards in the water.
- Human starter zone, water makes you fatigue. Even if its only touching your feet.

**Comment by mikefirefly** [comment]
> using spacebar, in water, makes you jump not move upwards in the water.

This is the vanilla way, however weird it looks.

**Comment by LeopoldHock** [comment]
Pet behavior is also Vanilla. The pet returns after killing its current target. When it gets attacked _while_ returning, it will then attack the attacker.

The rest should be separate issues.

**Comment by slowtorta** [comment]
Moving this issue to the internal tracker for client-related problems, thank you.
