### ISSUE TITLE
one shot one kill is not given out

### ISSUE THREAD

**Issue by poposhka** [slowtorta/turtlewow-bug-tracker#939]
**Please, provide a clear description what the bug is:**
seems the quest NPC is not handing out the quest.

**Steps to reproduce the behavior with as much detail as possible:**

1. visit quest npc Sentinel Aynasha: 45,90
2. she does not give out the quest

**IDs of affected creatures, items, quests or spells with a link to the relevant page:**

NPC: https://database.turtle-wow.org/?npc=11711
Quest: https://database.turtle-wow.org/?quest=5713

**Expected behavior. Describe how it should work:**
she should hand out the quest. there are no reqs other than level

**Comment by Tinyfin-github** [comment]
#336
