### ISSUE TITLE
Cenarion Circle "At War" By Default

### ISSUE THREAD

**Issue by Dragunovi** [slowtorta/turtlewow-bug-tracker#94]
**Please, provide a clear description what the bug is:**
Cenarion Circle is toggled "At War" by default for new created characters, which caused quite a few death for Hardcore players clicking the emissary at Orgrimmar without knowing they would attack it.
**Steps to reproduce the behavior with as much detail as possible:**

1. Make a new character.
2. Click a Cenarion Circle NPC.
3. Check Reputations tab to see if the character is already toggled "At War".

**IDs of affected creatures, items, quests or spells with a link to the relevant page:**

General Issue with the reputation itself.

**Expected behavior. Describe how it should work:**
Characters shouldn't have "At War" toggled by default on character creation.

**Comment by TrangOul** [comment]
Just lost HC character because of that...
What is worse, Cenarion Circle rep is not available initially, so newly created characters are not even aware of default "at war" setting.

**Comment by Nolin7777** [comment]
Fixed after next update
