### ISSUE TITLE
Vorsha the Lasher Bugged

### ISSUE THREAD

**Issue by Tremaa** [slowtorta/turtlewow-bug-tracker#940]
While doing the quest "Vorsha the Lasher" on my lvl 21 goblin hunter, when Vorsha spawned the quest completed without me killing it. I killed it anyways, and then it respawned. Didn't kill it a 2nd time

NPC: https://database.turtle-wow.org/?npc=12940
Item: https://database.turtle-wow.org/?item=
Quest: https://database.turtle-wow.org/?quest=6641
Spell: https://database.turtle-wow.org/?spell=
Object: https://database.turtle-wow.org/?object=

The quest is supposed to complete when you kill Vorsha, but it's completing when it spawns instead.

**Comment by slowtorta** [comment]
Thank you! But this issue has been already reported: https://github.com/slowtorta/turtlewow-bug-tracker/issues/913
