### ISSUE TITLE
"Escape Through Stealth" quest window not closed

### ISSUE THREAD

**Issue by Gasan918** [slowtorta/turtlewow-bug-tracker#943]
**Please, provide a clear description what the bug is:**

"Escape Through Stealth" quest window not closed after I click "Complete Quest" button. You need to click two times. This can be because there starts additional script that spawns Sentinel Selarin NPC who gives "Trek to Ashenvale" quest. Please check "Escape Through Stealth" quest too.

**IDs of affected creatures, items, quests or spells with a link to the relevant page:**

NPC: https://database.turtle-wow.org/?npc=3693
Quest: https://database.turtle-wow.org/?quest=995

![image](https://user-images.githubusercontent.com/96973359/150100736-252c7e4a-7fbb-4537-a335-17b843ced76e.png)

**Comment by slowtorta** [comment]
Fun fact, seems like Blizzard had this issue as well and had to hackfix it somehow: https://youtu.be/0sm-ThSRF0o?t=299

**Comment by slowtorta** [comment]
Will be fixed on the next update.
