### ISSUE TITLE
Auberdine boat boarding safety issues

### ISSUE THREAD

**Issue by zomgits** [slowtorta/turtlewow-bug-tracker#946]
**Please, provide a clear description what the bug is:**
You can't walk on to the boats at Auberdine without falling in the sea since 1.16 when the models were changed.

Here's the gap on the boat to Stormwind.
![image](https://user-images.githubusercontent.com/97355053/150107914-8814bf9e-eabc-4d2d-bafd-30020257d956.png)

On the Darnassus side there isn't even a boarding plank and the boarding zone of the boat doesn't line up with the dock.
![image](https://user-images.githubusercontent.com/97355053/150108040-83b6f8b5-4895-438e-9302-5c144e0cc468.png)

**Steps to reproduce the behavior with as much detail as possible:**

1. Try to walk on to the boats at Auberdine without jumping.
2. Get wet.

**Expected behavior. Describe how it should work:**
It should be possible to walk on and off these boats.

The boat planks at the ends of the docks should intersect the boat models.

(I liked the old boats but that's preference!)

**Comment by slowtorta** [comment]
Gnomes are safe now.

**Comment by zomgits** [comment]
I see one new plank, but it fixed none of the issues, sorry.
