### ISSUE TITLE
Bug: Characters Being Able to Dodge While Casting

### ISSUE THREAD

**Issue by mauntler** [slowtorta/turtlewow-bug-tracker#952]
**Please, provide a clear description what the bug is:**

I was able to dodge melee attacks from NPCs while casting/channeling spells.

**Steps to reproduce the behavior with as much detail as possible:**

1. Aggro melee npc
2. Cast spell (I used Rain of Fire, Soul Fire and Drain Soul)
3. Wait for dodge animation, scrolling combat text and combat log report to appear

**IDs of affected creatures, items, quests or spells with a link to the relevant page:**

https://database.turtle-wow.org/?spell=1120 Drain Soul Rank 1
https://database.turtle-wow.org/?spell=5740 Rain of Fire Rank 1
https://database.turtle-wow.org/?spell=11678 Rain of Fire Rank 4
https://database.turtle-wow.org/?spell=18160 Soul Fire Rank 2
https://database.turtle-wow.org/?spell=688 Summon Imp

These are the spells I tested and noticed the issue with. Others mentioned testing with other spells and hearthstone in TWoW Warlock Discord channel.

I performed these tests on:

https://database.turtle-wow.org/?npc=11687

**Expected behavior. Describe how it should work:**

To my understanding, one should not be able to dodge while casting a spell :(

![dodgewhilecastingcharactermotion](https://user-images.githubusercontent.com/66697103/150228076-08c99f73-f53a-40e7-94ee-1734bb07025e.png)
![dodgewhilecastingquestionmarkquestionmarkquestionmark](https://user-images.githubusercontent.com/66697103/150228144-045e6b8e-23b2-49e2-9f4e-672743cb0fe3.png)
![dodgewhilechannelingquestionmarkquestionmarkquestionmark](https://user-images.githubusercontent.com/66697103/150228180-eedfac09-8790-4205-9f27-6c5c0dbb10db.png)

**Comment by Kruxis** [comment]
Greetings! 

That's normal in WoW. Would be unfair if you cant move since you cast, you cant runaway far enough from enemys to cast when they got into meele range and you wear nothing but Cloth and leather. Not being able to dodge would make the game pretty hard for some casters :P

Short: it's normal behavior and not a bug =)

Safe Travels!

**Comment by cyaohiri** [comment]
> Greetings!
> 
> That's normal in WoW. Would be unfair if you cant move since you cast, you cant runaway far enough from enemys to cast when they got into meele range and you wear nothing but Cloth and leather. Not being able to dodge would make the game pretty hard for some casters :P
> 
> Short: it's normal behavior and not a bug =)
> 
> Safe Travels!

Looking at the bug report here (https://github.com/vmangos/core/issues/1449), it looks like this is indeed a bug.
In the latest VMaNGOS, however, this appears to be fixed. You practically can't dodge while casting/channeling.
https://streamable.com/ojk10m

I do agree with your reasoning, though. Probably most notably, it makes your Aspect of the Monkey useless while taming your pet.

Was this fixed on Turtle WoW in the meantime, @twowTurtReynolds?

**Comment by twowTurtReynolds** [comment]
This has been fixed for a while as we inherited the vmangos fix. 

I'd actually like to see this return as a feature but this is a suggestion for the forums.
