### ISSUE TITLE
One of the new/custom guns has bugged shooting animation

### ISSUE THREAD

**Issue by mikefirefly** [slowtorta/turtlewow-bug-tracker#953]
**Please, provide a clear description what the bug is:**
One of the new/custom guns has bugged shooting animation. I mean, I am pretty agile but not *that* agile!

**Steps to reproduce the behavior with as much detail as possible:**

1. Get this gun: https://database.turtle-wow.org/?item=83257
2. Shoot.
3. This happens: https://streamable.com/pp6thq

**IDs of affected creatures, items, quests or spells with a link to the relevant page:**

Item: https://database.turtle-wow.org/?item=83257

**Expected behavior. Describe how it should work:**
Gun should shoot like any well-behaving gun.

**Comment by mikefirefly** [comment]
If this is supposed to be fixed on live now, it isn't.

**Comment by slowtorta** [comment]
It is. Please clear your WDB while your game is closed and try again.

**Comment by mikefirefly** [comment]
I deleted the whole WDB folder and reqequipped the gun but the problem still persists. Other guns work correctly. Is there anything else I can do?

**Comment by LeopoldHock** [comment]
Can confirm that animation of https://database.turtle-wow.org/?item=83257is still broken.

**Comment by mikefirefly** [comment]
Can we reopen this please?
