### ISSUE TITLE
Stone Keepers in uldaman dont explode

### ISSUE THREAD

**Issue by geojak** [slowtorta/turtlewow-bug-tracker#956]
**Please, provide a clear description what the bug is:**

the stone keepers are the 4 golems tack attack the players at the room before the endboss where you need to click the stone in order to open the door. (see id later). This encounter is pretty hard on classic since the golems explode for seroius aoe damage.

on here its a piece of cake since they dont explode at all and barely deal damage

**Steps to reproduce the behavior with as much detail as possible:**

1. go to uldaman, the room before the endboss where the door is locked and you need to click the stone at the center with 3+ players
2. golems start attacking kill them slowly
3. they dont do any serous aoe explosion at all 

**IDs of affected creatures, items, quests or spells with a link to the relevant page:**

NPC: https://database.turtle-wow.org/?npc=4857
possibly other golems too, but these linke here for sure

**Expected behavior. Describe how it should work:**

golems should explode on death for insane aoe damage, something like 700ish

p.s. i added the ID in my first new issue after your (tortas) requests last time, as you had wished.

**Comment by geojak** [comment]
wow head has the explosion
https://classic.wowhead.com/npc=4857/stone-keeper#abilities;mode:normal

**Comment by redmagejoe** [comment]
I don't think they explode, per se, but rather when they fall over (so calculate 1-2 seconds), they're supposed to emulate "crushing" a player. I noticed immediately that they don't do that here. The idea is to run away from the falling golems so as not to be crushed. Hoping this gets fixed before long, as it's a good and funny way to filter the noobs.

Of course reading the abilities, it seems like it is supposed to be considered self destructing, so maybe it's that they self destructed after that brief delay of falling over? Everyone I knew described it as being crushed under the golems.

**Comment by slowtorta** [comment]
Duplicate for https://github.com/slowtorta/turtlewow-bug-tracker/issues/1989

**Comment by geojak** [comment]
But now you closed both issues as duplicates of each other? Is this fixed?
