### ISSUE TITLE
Opening Transmog window seems to stop the 'main menu' from opening.

### ISSUE THREAD

**Issue by thrassoss** [slowtorta/turtlewow-bug-tracker#959]
**Please, provide a clear description what the bug is:**
Once I talk to the Fasionista in Orgrimmar and the Transmog window opens, I am unable to open the 'Main menu'. I can't use the Escape key on my keyboard nor does clicking the 'Main menu' button work.  When I ctrl-alt-del out and close wow and relauch the main menu works fine.  I deleted wdb and retested and it worked the same.

**Steps to reproduce the behavior with as much detail as possible:**

1. Confirm you can open your main menu by hitting your escape key to see that it works fine.
2. Talk to the Fashionista character. 
3. Wait for the Transmog window to open.
4. If you are lagging and the Transmog window doesn't open, the Fashionistas conversation window just says "Greetings".  The main menu is unaffected if this happens.
5. The Transmog window opens.  At this point I always clicked some chest piece items, just to use the window a bit, I didn't actually transmog anything. I just clicked on some appearances.  
6. Close out the Transmog window.
7. Confirm you are not in an Isekai. ( for safety, obviously )
8.  Attempt to open your main menu.  Neither the Escape Key or Menu button work.

**IDs of affected creatures, items, quests or spells with a link to the relevant page:**

NPC: https://database.turtle-wow.org/?npc=
Item: https://database.turtle-wow.org/?item=
Quest: https://database.turtle-wow.org/?quest=
Spell: https://database.turtle-wow.org/?spell=
Object: https://database.turtle-wow.org/?object=

**Expected behavior. Describe how it should work:**
Both Escape and clicking with a mouse on the Main menu button should open the main menu while not in an Isekai.

**Comment by slowtorta** [comment]
Moving this issue to the internal tracker for client-related problems, thank you.
