### ISSUE TITLE
Survival Skill: Multiple Bright Campfire Spells in Spell Book

### ISSUE THREAD

**Issue by Stilleta** [slowtorta/turtlewow-bug-tracker#96]
If you are upgrading your survival "spells" since the upgrade and relearn "bright campfire", you will discover you now have two bright campfire spells in your spell book.

**Steps to reproduce the behavior with as much detail as possible:**

1. Have bright campfire learned prior to the upgrade. Spell is in spell book in the general category following basic campfire (if you learned it).
2. From the survival expert NPC, Rufus Hardwick, purchase "Outline: Bright Campfire".
3. select "Outline: Bright Campfire" and learn spell
4. you now will have two copies of the spell Bright Campfire in your spell book

**IDs of affected creatures, items, quests or spells with a link to the relevant page:**
https://database.turtle-wow.org/?item=50254

**Expected behavior. Describe how it should work:**
The spell should be unique. Only one copy should appear in the spell book.

**Comment by tmt01** [comment]
Besides that, one of the two spells doesn't increase survival skill.

**Comment by slowtorta** [comment]
Thanks for reporting it. It'll be fixed on the next server restart. Make sure to clear your WDB folder.
