### ISSUE TITLE
Highlord Bolvar Fordragon does not attack Onyxia's Elite Guard during The Great Masquerade

### ISSUE THREAD

**Issue by Tinyfin-github** [slowtorta/turtlewow-bug-tracker#962]
Highlord Bolvar Fordragon does not attack Onyxia's Elite Guard during  The Great Masquerade

https://database.turtle-wow.org/?quest=6403 The Great Masquerade
https://database.turtle-wow.org/?npc=1748 Highlord Bolvar Fordragon
https://database.turtle-wow.org/?npc=12739 Onyxia's Elite Guard

Video of how it should work: https://www.youtube.com/watch?v=5LbRbxCbZ5o

**Comment by slowtorta** [comment]
Fixed on the next update!
