### ISSUE TITLE
speck of dreamdust droprate

### ISSUE THREAD

**Issue by geojak** [slowtorta/turtlewow-bug-tracker#963]
**Please, provide a clear description what the bug is:**

the item speck of drum dust has a too high drop rate on this server. pfqeust displays the droprate as 80%, which is probably right for the server, but doesnt match wow head classic data. see wow head link and links to turtle wow db

**IDs of affected creatures, items, quests or spells with a link to the relevant page:**

NPC: https://database.turtle-wow.org/?npc=740
Item:https://database.turtle-wow.org/?item=5803

**Expected behavior. Describe how it should work:**

https://classic.wowhead.com/item=5803/speck-of-dream-dust

**Comment by slowtorta** [comment]
I don't consider this being a bug, sorry.
