### ISSUE TITLE
Hunter Pet Talent Points

### ISSUE THREAD

**Issue by HaydenRWK** [slowtorta/turtlewow-bug-tracker#965]
**Please, provide a clear description what the bug is:**

when learning new hunter pet abilities that have a talent point cost, the number of available training points left does not go down. Unsure if it is purely a visible error, or if it means a pet can now learn as many abilities as they want regardless of cost. 
(Error persisted after deleting wdb folder) 

**Steps to reproduce the behavior with as much detail as possible:**

1.
2. 
3. 

**IDs of affected creatures, items, quests or spells with a link to the relevant page:**

NPC: https://database.turtle-wow.org/?npc=
Item: https://database.turtle-wow.org/?item=
Quest: https://database.turtle-wow.org/?quest=
Spell: https://database.turtle-wow.org/?spell=
Object: https://database.turtle-wow.org/?object=

**Expected behavior. Describe how it should work:**

**Comment by mikefirefly** [comment]
Duplicate of #739 #768

**Comment by LeopoldHock** [comment]
Closing because of duplicate.
