### ISSUE TITLE
300/6000 reputation with unknown faction/group

### ISSUE THREAD

**Issue by Gasan918** [slowtorta/turtlewow-bug-tracker#967]
**Please, provide a clear description what the bug is:**

Just noticed that my toon have rep with unknown faction.  Sadly, I wasn't checking rep tab after every quest done, so I can't say for sure when I got it. But the most likely it was some Darkshore quest.

![image](https://user-images.githubusercontent.com/96973359/150639610-9abe8b3c-ef27-4d2b-9952-006ff4b20453.png)

**Comment by zomgits** [comment]
Related to https://github.com/slowtorta/turtlewow-bug-tracker/issues/920#issuecomment-1016800007

**Comment by slowtorta** [comment]
This will be fixed in 1.16.1.
