### ISSUE TITLE
Pet's patfinding and collision problem in a some enclosed and multileveled spaces.

### ISSUE THREAD

**Issue by Valderien** [slowtorta/turtlewow-bug-tracker#969]
**Please, provide a clear description what the bug is:**
Warlock and hunter's pets acting strange in a buildings, on a platforms and inside the caves: they just stucks and refuses to attack like there is invisible walls between them and mobs. If you go further, sometimes they just refuses to follow you, but after that they can just run chaotically through floor and walls, aggroed every mob in radius. Mobs bugged too, btw - if they aggroed on a pet, they stucks too and evade every your attack, and sometimes on a random spots they just sees you through walls and ceiling and running to attack you, collecting every other mobs in a way. Most of the complains (and my personnel) are about Fenris Keep, Skull Rock, Dustwind Cave and Sparkwater Port oil platforn - but it could be more zones with that problem.  
**Steps to reproduce the behavior with as much detail as possible:**

1. Being a warlock or a hunter with a pet.
2. Walk into a cave (like a Skull rock), castle (like Fenris Keep) or on a platform.
3. Try to cleanse it and find a bug into various areas. 

**IDs of affected creatures, items, quests or spells with a link to the relevant page:**

NPC: https://database.turtle-wow.org/?npc=
Item: https://database.turtle-wow.org/?item=
Quest: https://database.turtle-wow.org/?quest=
Spell: https://database.turtle-wow.org/?spell=
Object: https://database.turtle-wow.org/?object=

**Expected behavior. Describe how it should work:**
Apparently there's shouldn't be something like that and all pets should attack and pathfind without any problems, and the mobs - see player only in their aggro range.

**Comment by slowtorta** [comment]
Probably not perfect but for sure improved in the next revision.
