### ISSUE TITLE
Duel projectiles can hurt/kill players after the duel ends

### ISSUE THREAD

**Issue by zetanor** [slowtorta/turtlewow-bug-tracker#970]
Damage and true death can occur from mid-air projectiles after the duel ends.

To replicate the screenshot below:

* Made level 1 alt (and took hardcore to further illustrate the problem)
* Dueled alt with priest
* Cast SW:P
* Shot wand
* Alt died to SW:P tick
* Duel ends with alt at 1 HP
* Projectile hits alt, causing a non-duel death (and in this case, a hardcore death)

![image](https://user-images.githubusercontent.com/6922903/150661480-1e5118b1-cae7-44ea-bfdf-452286e3605c.png)

Similar to prior https://github.com/slowtorta/turtlewow-bug-tracker/issues/252 but with different means.

**Comment by triana2021** [comment]
This is the original vanilla behaviour.

**Comment by zetanor** [comment]
> This is the original vanilla behaviour.

I don't remember it happening in my couple of years playing, but even so, it's harsh for hardcore players.

**Comment by slowtorta** [comment]
Fixed on the next server update.
