### ISSUE TITLE
Quest bug: "Freedom for all creatures" in Feralas.

### ISSUE THREAD

**Issue by virre117** [slowtorta/turtlewow-bug-tracker#971]
**Please, provide a clear description what the bug is:**
The quest "Freedom for all creatures" in Feralas, where you are supposed to let sprite darters out of a cage in a tauren village within a 6 min timer seems to be bugged since there are only one (1) Captured sprite darter in the cage the quest goes Failed after the timer runs out.
**Steps to reproduce the behavior with as much detail as possible:**

1.
2. 
3. 

**IDs of affected creatures, items, quests or spells with a link to the relevant page:**

NPC: https://database.turtle-wow.org/?npc=
Item: https://database.turtle-wow.org/?item=
Quest: https://database.turtle-wow.org/?quest=
Spell: https://database.turtle-wow.org/?spell=
Object: https://database.turtle-wow.org/?object=

**Expected behavior. Describe how it should work:**

**Comment by geojak** [comment]
Another bug with this quest line.
Later one you get an egg and in need 3 days to hatch on classic. On TWoW you can just turn in and continue immideitly

**Comment by slowtorta** [comment]
Thank you. This will be fixed on the next server update! 
![image](https://user-images.githubusercontent.com/66763404/153706116-b541507e-bf1f-45e1-939d-04f621db257e.png)
