### ISSUE TITLE
Entrapment does not proc on immolation trap

### ISSUE THREAD

**Issue by zomgits** [slowtorta/turtlewow-bug-tracker#972]
**Please, provide a clear description what the bug is:**
The Entrapment talent in the hunter survival tree does not proc.  Mobs are never immobilized.

![image](https://user-images.githubusercontent.com/97355053/150678811-2e4cf4dd-a876-4724-a693-a5a95d3d107e.png)

**Steps to reproduce the behavior with as much detail as possible:**

1. Create a level 36 hunter with the Entrapment talent 1/5.
2. Grind about a 150 (calculated from drops) Snapjaws at Lordamere for some hours, dropping an immolation trap for every kill.
3. Never observe an entrapment proc.

**IDs of affected creatures, items, quests or spells with a link to the relevant page:**

Spell: https://database.turtle-wow.org/?spell=19184

**Expected behavior. Describe how it should work:**
Approximately 1 in 20 traps should immobilize a mob.

I also tested this with Frost Trap.  In Vanilla, Frost Trap had a chance to immobilize once per server tick for every mob in the trap, which means there should be a very high chance of a proc.  You can kite a mob around in the Frost Trap effect on TWoW and it *will* be immobilized occasionally.  So something's working.

Perhaps Immo trap is not properly applying the chance when it is first triggered?

Or I have extraordinarly bad luck.  If it ever procs I'll amend this report!

I use immo trap for every kill, so I will report back with more results later.

**Comment by zomgits** [comment]
Several hundred more kills.  No procs.

**Comment by zomgits** [comment]
Many more kills with no procs.
But now my character is dead.

**Comment by Khanz0** [comment]
Still bugged? I was thinking in getting this talent for kitting

**Comment by zomgits** [comment]
> Still bugged? I was thinking in getting this talent for kitting

My HC character that had it is dead, so I can no longer provide info.  There's been no developer feedback about any change, so I'd guess it's still broken.

**Comment by zomgits** [comment]
Because I'd *really* like this to work, I put 3/5 points into Entrapment on my new level 50 HC hunter, just in case it was only a problem with 1/5 points.  Nope.  No procs from Immolation Trap after hundreds of kills.

**Comment by Khanz0** [comment]
Was fixed?

**Comment by slowtorta** [comment]
Please test it again after the next update (May 18) and let me know if it's still not working as intended!
