### ISSUE TITLE
noboru the cudgel in swamp of sorows

### ISSUE THREAD

**Issue by geojak** [slowtorta/turtlewow-bug-tracker#973]
**Please, provide a clear description what the bug is:**

noboru the cudgel in swamp of sorows is supposed to patroll around swamp of sorrows together with his 2 pats.
if you angry any of the three mobs they should all attack you.

First Issue, the dude does no move around and just stands around with his 2 pats at this spawn point
Second Issue, i was able to pull the named dude and the 2 pats didnt not aggro at all

**Steps to reproduce the behavior with as much detail as possible:**

1. go to the spawn point of the npc
2. obvserve he doesnt move at all
3. pull the named mob
4. the 2 pats will not attack with hin

**IDs of affected creatures, items, quests or spells with a link to the relevant page:**

[NPC: https://database.turtle-wow.org/?npc=](https://database.turtle-wow.org/?npc=5477)

**Expected behavior. Describe how it should work:**

see wow head for patrol
https://classic.wowhead.com/npc=5477/noboru-the-cudgel

and make the 2 mobs with him aggro as a pack

**Comment by mikefirefly** [comment]
Duplicate of #820

**Comment by geojak** [comment]
I close it due to duplicate
