### ISSUE TITLE
The Inn in Sparkwater Port has no rested status.

### ISSUE THREAD

**Issue by chrissie8000** [slowtorta/turtlewow-bug-tracker#974]
**Please, provide a clear description what the bug is:**
The Inn over at Sparkwater doesn't actually give any rested XP or rested status.
**Steps to reproduce the behavior with as much detail as possible:**

1.Enter Inn
2. ...
3. Profit

**IDs of affected creatures, items, quests or spells with a link to the relevant page:**

NPC: https://database.turtle-wow.org/?npc=
Item: https://database.turtle-wow.org/?item=
Quest: https://database.turtle-wow.org/?quest=
Spell: https://database.turtle-wow.org/?spell=
Object: https://database.turtle-wow.org/?object=

**Expected behavior. Describe how it should work:**
It should give rested i think?

**Comment by slowtorta** [comment]
Fixed in 1.16.1.
