### ISSUE TITLE
[Paladin] Judgement not refreshed by Holy Strike

### ISSUE THREAD

**Issue by Seraphic8x2244** [slowtorta/turtlewow-bug-tracker#975]
**Please, provide a clear description what the bug is:**
Paladin's Judgements (Crusader, Light, Wisdom, Justice) are being dropped too frequently, due to that fact that Holy Strike does not refresh the active judgement's duration.

This is exacerbated for retribution paladins, who have 3.6 (circa) weapon speed with only a 10 second window to refresh a judgement. 

**Steps to reproduce the behavior with as much detail as possible:**

1. Judge any seal that leaves a debuff (Crusader, Light, Wisdom, Justice)
2. Stop attacking.
3. Enable Holy Strike with <2 seconds left on judgement.
4. Judgement will fall off.

**Expected behavior. Describe how it should work:**
Adjusting judgement durations or other class remedies would be out of the scope of this bug report.

Holy Strike should just refresh judgements because;
1. It replaces your autoattack, which is the classes only method of extending judgement durations. This causes a bad-taste trade off between gaining an ability, which hinders other parts of the paladin's (limited) toolkit.
2. The tooltip for judgements says "Your melee strikes refresh it's duration". Whilst I realise this tooltip was written before paladins had other strikes, it means this behavior would be within keeping of the mild changes you have made on Turtle.

Thanks for your time.

**Comment by redmagejoe** [comment]
Holy Strike still does not refresh Judgements.

**Comment by gene314159** [comment]
@slowtorta all ranks of holy strike works fine now except rank 1 as per tested, do we have a plan to fix rank 1 as well?

**Comment by Gurky-Turtle** [comment]
https://github.com/slowtorta/turtlewow-bug-tracker/issues/3825

**Comment by Dragunovi** [comment]
Should be fixed as of the latest server restart.
