### ISSUE TITLE
Druid: Cat form Damage not being calculated correctly

### ISSUE THREAD

**Issue by Rakura1** [slowtorta/turtlewow-bug-tracker#978]
**Please, provide a clear description what the bug is:**
Cat form damage not being shown correctly compared to sites like wowhead classic

**Steps to reproduce the behavior with as much detail as possible:**

1. Build gear set or look at birthday suit level damage
2. Go build the exact same thing within wowhead classic gear simulator
3. See that they are no where close to being the same. Notice performing the same test for bear form its almost exactly the same.

**IDs of affected creatures, items, quests or spells with a link to the relevant page:**

**Expected behavior. Describe how it should work:**
Cat form Damage should be heavily increased see screenshots for comparison
https://classic.wowhead.com/gear-planner/druid/tauren/AjwPUAAFMB9SUAATIyAhUfBfAUCmAljMg1ShX2aFWrpOOQZLxAdAqIhLtU43iVRiNnmKVGVh-AtS1QxLuA1LWQ4uJ49L7DY6EFOfETRJEld9
![image](https://user-images.githubusercontent.com/90916104/150723775-a74f3521-8143-45f6-b86b-a1719cb21fe2.png)
![image](https://user-images.githubusercontent.com/90916104/150723788-424264ef-28bd-46c3-990a-511e109e6041.png)

**Comment by LeopoldHock** [comment]
You seem to be using BetterStats. Can you please test without the addon?

**Comment by Rakura1** [comment]
> You seem to be using BetterStats. Can you please test without the addon?

How would you like me to test? Just want to make sure I provide solid feedback.

**Comment by geojak** [comment]
maybem ake the same screenshots with the addon disbaled?

**Comment by Rakura1** [comment]
SS with addon disabled as you see its still showing the same number
![image](https://user-images.githubusercontent.com/90916104/150866522-d9d5eb91-30fc-4a4a-a223-4ab5baf1aae1.png)
