### ISSUE TITLE
Devotion Aura glitches at Dun Garok

### ISSUE THREAD

**Issue by zomgits** [slowtorta/turtlewow-bug-tracker#979]
**Please, provide a clear description what the bug is:**
Alliance characters near Dun Garok have Devotion Aura gain and fade continuously, many times per second.

![image](https://user-images.githubusercontent.com/97355053/150778577-0a9120b4-4b0c-42eb-bd0e-2e7fe3d8570e.png)

This seems to be an aura bug to do with the Dun Garok mobs.

**Steps to reproduce the behavior with as much detail as possible:**

1. Make an alliance character
2. Go to Dun Garok.
3. Watch the combat log.

**IDs of affected creatures, items, quests or spells with a link to the relevant page:**

NPC: https://database.turtle-wow.org/?npc=2344

**Expected behavior. Describe how it should work:**
1. I'm not expecting any aura from an NPC.
2. If the aura is supposed to be there, it should apply in range, and fade out of range, and not flicker on and off.

**Comment by slowtorta** [comment]
Thanks for reporting it, it'll be fixed on the next server update :)
