### ISSUE TITLE
Can't enter game after loadscreen

### ISSUE THREAD

**Issue by NeroAnemos** [slowtorta/turtlewow-bug-tracker#988]
On 01/25 after server update on 01/24 my character stopped entering in game after loading screen.
Loading stopped at 100% and nothings happens.
The same happened with new full client (downloaded 1.16.0 from forum), new characters and a new account.
![image](https://user-images.githubusercontent.com/57539438/151077266-cd5f2711-f161-40ae-91eb-5bc4b27ed342.png)

**Comment by slowtorta** [comment]
What is your character's name?

**Comment by NeroAnemos** [comment]
> What is your character's name?

Apelsin

**Comment by slowtorta** [comment]
Please clear your WDB folder and try again.

**Comment by NeroAnemos** [comment]
> Please clear your WDB folder and try again.

I tried it before and now, still can't get in

**Comment by slowtorta** [comment]
So it doesn't work even with the fresh client and new characters?

**Comment by NeroAnemos** [comment]
> So it doesn't work even with the fresh client and new characters?

Yes :(

**Comment by slowtorta** [comment]
Please join our Discord and contact our support, they might have a few more ideas on how to troubleshoot it.

**Comment by NeroAnemos** [comment]
> Please join our Discord and contact our support, they might have a few more ideas on how to troubleshoot it.

Already there and asked about this problem.
That's why I'm here

**Comment by slowtorta** [comment]
Do you have any error logs created in your Logs or Errors folders when this happens to you?

**Comment by NeroAnemos** [comment]
> Do you have any error logs created in your Logs or Errors folders when this happens to you?

Can problem be in this?
![image](https://user-images.githubusercontent.com/57539438/151081228-a7fff956-382c-42d8-adc8-9eedf7d82beb.png)

**Comment by slowtorta** [comment]
Where's your client located? Can you ensure it's not flagged as Read Only?

**Comment by NeroAnemos** [comment]
> Where's your client located? Can you ensure it's not flagged as Read Only?

C:\World of Warcraft Classic

It actually is Read Only. I am trying to get rid of this flag rn, but it returns somehow.

**Comment by slowtorta** [comment]
Right Click / Properties / Security > Check Permissions for your user!

**Comment by slowtorta** [comment]
Move it under C:\Games too or something similar, please.

**Comment by NeroAnemos** [comment]
> Right Click / Properties / Security > Check Permissions for your user!
Done, but it still returns. Is it ok on Windows 10?

> Move it under C:\Games too or something similar, please.
Done. Now it in C:\Games\World of Warcraft Classic

Still can't get in

**Comment by slowtorta** [comment]
Can you please try to temporarily remove Patch-W.MPQ from your Data folder to see if you can login?

**Comment by NeroAnemos** [comment]
> Can you please try to temporarily remove Patch-W.MPQ from your Data folder to see if you can login?

Don't have this file
![image](https://user-images.githubusercontent.com/57539438/151084748-d59f43d8-2a27-4404-a37c-c42c1704e450.png)

**Comment by slowtorta** [comment]
I'm sorry, I meant Patch-V.MPQ.

**Comment by NeroAnemos** [comment]
> I'm sorry, I meant Patch-V.MPQ.

Still can't

**Comment by slowtorta** [comment]
Any firewalls running? Maybe try to disable Windows Defender temporarily to see if it helps?

**Comment by slowtorta** [comment]
Return Patch-V in the Data folder please :)

**Comment by NeroAnemos** [comment]
> Any firewalls running? Maybe try to disable Windows Defender temporarily to see if it helps?

Already have been disabled

**Comment by slowtorta** [comment]
Do you have any addons installed? Try disabling them all.

**Comment by slowtorta** [comment]
Try to edit t he contents of your WTF/Config.wtf file to the following:

`SET hwDetect "0"
SET gxColorBits "24"
SET gxDepthBits "24"
SET gxResolution "2560x1440"
SET gxRefresh "60"
SET gxWindow "1"
SET gxMaximize "1"
SET gxMultisampleQuality "0.000000"
SET gxFixLag "0"
SET fullAlpha "1"
SET lodDist "100.000000"
SET SmallCull "0.010000"
SET DistCull "500.000000"
SET shadowLevel "0"
SET trilinear "1"
SET frillDensity "48"
SET farclip "777"
SET specular "1"
SET pixelShaders "1"
SET particleDensity "1.000000"
SET unitDrawDist "300.000000"
SET anisotropic "8"
SET movie "0"
SET Gamma "1.000000"
SET readTOS "1"
SET readEULA "1"
SET MusicVolume "0.69999998807907"
SET SoundVolume "1"
SET MasterVolume "1"
SET patchlist "127.0.0.1"
SET gameTip "39"
SET AmbienceVolume "0.40000000596046"
SET uiScale "0.79999995231628"
SET useUiScale "1"
SET mouseSpeed "1"
SET DesktopGamma "1"
SET weatherDensity "3"
SET cameraYawMoveSpeed "180"
SET cameraYawSmoothSpeed "180"
SET cameraDistanceMaxFactor "1"
SET minimapZoom "0"
SET SoundZoneMusicNoDelay "1"
SET profanityFilter "0"
SET spamFilter "0"
SET minimapInsideZoom "0"
SET UnitNameNPC "1"`

**Comment by NeroAnemos** [comment]
> Do you have any addons installed? Try disabling them all.

Tried on new client without addons and on old client with disabled addons, didn't help

>Try to edit t he contents of your WTF/Config.wtf file to the following:

Still nothing happens :(

Am I the only one who has this problem?

I better go to sleep and think about it later.

Thank you for trying to help.

**Comment by slowtorta** [comment]
I think it's worth a try to update graphic drivers maybe :) Stay safe!

**Comment by NeroAnemos** [comment]
Tried to enter game on TBC server and the same happens. Problem is on my side
