### ISSUE TITLE
Weekly raid reset, and weekly server restart, are misaligned

### ISSUE THREAD

**Issue by Zebouski** [slowtorta/turtlewow-bug-tracker#989]
**Please, provide a clear description what the bug is:**
these two should be at the same time, they always were on blizzard and other servers. currently the raid reset is 3.75 hours later 

![image](https://user-images.githubusercontent.com/11151284/151081992-b34de165-28e6-4188-9afb-a238e6bb8a62.png)

**Steps to reproduce the behavior with as much detail as possible:**

1. get locked one week
2. wait for tues night weekly reset
3. see that you are still locked for another 4 hours

**Expected behavior. Describe how it should work:**
the weekyl restart should release all raid lockouts like it updates pvp ranks

**Comment by LeopoldHock** [comment]
Weekly maintenance windows are done manually. There is no automated weekly restart. The difference is that PvP ranking calculations are done while the server is offline, while raid lockout resets can be done while the server is running.

**Comment by LeopoldHock** [comment]
Actually, I was misinformed and there is an automated weekly restart during tuesday night. Reopening.

**Comment by slowtorta** [comment]
It's often that I have to be awake during the maintenance aka honor update to ensure that server update went as planned. 1-2AM is still a comfortable timeframe for me, but I cannot stay up till the early morning :) Thanks for reporting it, but sorry, this will stay as it is!

**Comment by Zebouski** [comment]
oh, i was hoping it was going to be the other way, where raids reset right around the restart at 7pm EST, instead of 11pm EST which is kinda in the middle of ideal NA time raiding. Or am I misunderstanding and that can't be the fix either?
