### ISSUE TITLE
Scepter of Aka'sha Sheathes on Back Should Disappear

### ISSUE THREAD

**Issue by tubtubs** [slowtorta/turtlewow-bug-tracker#990]
**Please, provide a clear description what the bug is:**
The offhand Scepter of Aka'sha sheathes on the back, when most off hand non-weapons disappear when sheathed. 
**Steps to reproduce the behavior with as much detail as possible:**

1. Acquire Scepter of Aka'sha
2. Equip Scepter of Aka'sha
3. Observe the offhand on the character's back, instead of invisible until un-sheathed

**IDs of affected creatures, items, quests or spells with a link to the relevant page:**

Item: https://database.turtle-wow.org/?item=60131

**Expected behavior. Describe how it should work:**
The offhand should disappear when sheathed

![image](https://user-images.githubusercontent.com/96892771/151128140-58d93b95-6b15-46ee-a180-7ceda92dc002.png)
![image](https://user-images.githubusercontent.com/96892771/151128163-df6765e2-afa7-4fb9-ab74-cbc9617e8690.png)

**Comment by Kruxis** [comment]
Greetings! 

Thanks for the report, will be fixed on next server restart.

Safe Travels!
