### ISSUE TITLE
Inkeeper Kauth

### ISSUE THREAD

**Issue by nulajedan** [slowtorta/turtlewow-bug-tracker#991]
**Please, provide a clear description what the bug is:**
Inkeeper Kauth Kauth does not offer the possibility to set your Hearthstone to Bloodhoof Village Inn.
He only says: "Greetings, <your_name>."

**Steps to reproduce the behavior with as much detail as possible:**

1. Talk to Inkeeper Kauth

**IDs of affected creatures, items, quests or spells with a link to the relevant page:**

NPC: https://database.turtle-wow.org/?npc=6747

**Expected behavior. Describe how it should work:**
You should be able to set your Hearthstone to Bloodhoof Village.

**Comment by Shhizuha** [comment]
To add to this I am also unable to turn in a quest to him either (A Task Unfinished)
