### ISSUE TITLE
The boss C'thun is still bugged.

### ISSUE THREAD

**Issue by JohnColdway** [slowtorta/turtlewow-bug-tracker#997]
**Please, provide a clear description what the bug is:**
 During phase 1 of the encounter, the boss still does not spawn neither [Eye Tentacles] or [Claw Tentacles], carrying over a similar problem into phase 2 where [Giant Eye Tentacles] and [Giant Claw Tentacles] are not spawned. During phase 2 the boss also immediately goes into his weakened phase as soon as his spawning animation ends, and once said weakened phase ends, he enters another one until dead.
**Steps to reproduce the behavior with as much detail as possible:**

1.
2. 
3. 

**IDs of affected creatures, items, quests or spells with a link to the relevant page:**

NPC: https://database.turtle-wow.org/?npc=15589
https://database.turtle-wow.org/?npc=15727

**Expected behavior. Describe how it should work:**

**Comment by slowtorta** [comment]
Should be fixed now.
