### ISSUE TITLE
Getting on mount gets rid of Shadowform dark silhouette

### ISSUE THREAD

**Issue by amoussav** [slowtorta/turtlewow-bug-tracker#999]
**Please, provide a clear description what the bug is:**

When getting on a mount (tested with turtle mount and pink tallstrider), the dark silhouette on my Shadowform character disappears. The colorful aura, however, remains on my character. After dismounting, the silhouette is still gone. Getting out and back into Shadowform afterward will cause the silhouette to reappear.

**Steps to reproduce the behavior with as much detail as possible:**

1. Cast Shadowform
2.  Get on mount
3. 

**IDs of affected creatures, items, quests or spells with a link to the relevant page:**

Item: https://database.turtle-wow.org/?item=23720
Spell: https://classic.wowhead.com/spell=15473/shadowform

**Expected behavior. Describe how it should work:**

Dark silhouette should remain.

Before and after mounting:
![image](https://user-images.githubusercontent.com/38815455/151430639-bf1e23c0-cd81-42fd-8366-a094ffb013a3.png)
![image](https://user-images.githubusercontent.com/38815455/151430729-c40b2a3c-60d9-49c0-85fc-c3ff11324e49.png)

**Comment by amoussav** [comment]
I noticed it also happens while you're targeting yourself in shadow form, but when you stop targeting yourself, the silhouette comes back

**Comment by LeopoldHock** [comment]
The behavior while targeting is normal. When actors (NPCs or players), they get highlighted.

**Comment by slowtorta** [comment]
Sadly, this is normal Vanilla client behavior, I don't think we can fix it.
